ns-3: src/traffic-control/examples/adaptive-red-tests.cc File Reference
adaptive-red-tests.cc File Reference
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/flow-monitor-helper.h"
#include "ns3/point-to-point-module.h"
#include "ns3/applications-module.h"
#include "ns3/traffic-control-module.h"
Functions
void BuildAppsTest (uint32_t test)
void CheckQueueDiscSize (Ptr< QueueDisc > queue)
Variables
double avgQueueDiscSize
uint32_t checkTimes
double client_start_time
double client_stop_time
std::stringstream filePlotQueueDisc
std::stringstream filePlotQueueDiscAvg
double global_start_time
double global_stop_time
Ipv4InterfaceContainer i0i2
Ipv4InterfaceContainer i1i2
Ipv4InterfaceContainer i2i3
Ipv4InterfaceContainer i3i4
Ipv4InterfaceContainer i3i5
NodeContainer n0n2
NodeContainer n1n2
NodeContainer n2n3
NodeContainer n3n4
NodeContainer n3n5
double sink_start_time
double sink_stop_time
Function Documentation
BuildAppsTest()
void BuildAppsTest (uint32_t test)
Definition at line 126 of file adaptive-red-tests.cc.
CheckQueueDiscSize()
void CheckQueueDiscSize (Ptr< QueueDisc > queue)
Definition at line 106 of file adaptive-red-tests.cc.
References avgQueueDiscSize, checkTimes, filePlotQueueDisc, filePlotQueueDiscAvg, ns3::QueueDisc::GetCurrentSize(), ns3::Time::GetSeconds(), ns3::QueueSize::GetValue(), ns3::Simulator::Now(), ns3::Simulator::Schedule(), and ns3::Seconds().
Variable Documentation
avgQueueDiscSize
double avgQueueDiscSize
Definition at line 80 of file adaptive-red-tests.cc.
Referenced by CheckQueueDiscSize().
checkTimes
uint32_t checkTimes
Definition at line 79 of file adaptive-red-tests.cc.
Referenced by CheckQueueDiscSize().
client_start_time
double client_start_time
Definition at line 87 of file adaptive-red-tests.cc.
client_stop_time
double client_stop_time
Definition at line 88 of file adaptive-red-tests.cc.
filePlotQueueDisc
std::stringstream filePlotQueueDisc
Definition at line 102 of file adaptive-red-tests.cc.
Referenced by CheckQueueDiscSize().
filePlotQueueDiscAvg
std::stringstream filePlotQueueDiscAvg
Definition at line 103 of file adaptive-red-tests.cc.
Referenced by CheckQueueDiscSize().
global_start_time
double global_start_time
Definition at line 83 of file adaptive-red-tests.cc.
global_stop_time
double global_stop_time
Definition at line 84 of file adaptive-red-tests.cc.
i0i2
Ipv4InterfaceContainer i0i2
Definition at line 96 of file adaptive-red-tests.cc.
i1i2
Ipv4InterfaceContainer i1i2
Definition at line 97 of file adaptive-red-tests.cc.
i2i3
Ipv4InterfaceContainer i2i3
Definition at line 98 of file adaptive-red-tests.cc.
i3i4
Ipv4InterfaceContainer i3i4
Definition at line 99 of file adaptive-red-tests.cc.
i3i5
Ipv4InterfaceContainer i3i5
Definition at line 100 of file adaptive-red-tests.cc.
n0n2
NodeContainer n0n2
Definition at line 90 of file adaptive-red-tests.cc.
Referenced by Ipv4DynamicGlobalRoutingTestCase::DoRun().
n1n2
NodeContainer n1n2
Definition at line 91 of file adaptive-red-tests.cc.
Referenced by IcmpTimeExceedTestCase::DoRun(), IcmpV6TimeExceedTestCase::DoRun(), Ipv4DynamicGlobalRoutingTestCase::DoRun(), Ns3TcpCwndTestCase2::DoRun(), and Ns3TcpStateTestCase::DoRun().
n2n3
NodeContainer n2n3
Definition at line 92 of file adaptive-red-tests.cc.
Referenced by Ns3TcpCwndTestCase2::DoRun().
n3n4
NodeContainer n3n4
Definition at line 93 of file adaptive-red-tests.cc.
n3n5
NodeContainer n3n5
Definition at line 94 of file adaptive-red-tests.cc.
sink_start_time
double sink_start_time
Definition at line 85 of file adaptive-red-tests.cc.
sink_stop_time
double sink_stop_time
Definition at line 86 of file adaptive-red-tests.cc.