ns-3: src/spectrum/examples/adhoc-aloha-ideal-phy.cc File Reference
adhoc-aloha-ideal-phy.cc File Reference
#include <iostream>
#include <ns3/core-module.h>
#include <ns3/network-module.h>
#include <ns3/spectrum-model-ism2400MHz-res1MHz.h>
#include <ns3/spectrum-model-300kHz-300GHz-log.h>
#include <ns3/wifi-spectrum-value-helper.h>
#include <ns3/single-model-spectrum-channel.h>
#include <ns3/waveform-generator.h>
#include <ns3/spectrum-analyzer.h>
#include <ns3/log.h>
#include <string>
#include <ns3/friis-spectrum-propagation-loss.h>
#include <ns3/propagation-delay-model.h>
#include <ns3/mobility-module.h>
#include <ns3/spectrum-helper.h>
#include <ns3/applications-module.h>
#include <ns3/adhoc-aloha-noack-ideal-phy-helper.h>
Functions
void PhyRxEndErrorTrace (std::string context, Ptr< const Packet > p)
void PhyRxEndOkTrace (std::string context, Ptr< const Packet > p)
void PhyRxStartTrace (std::string context, Ptr< const Packet > p)
void PhyTxEndTrace (std::string context, Ptr< const Packet > p)
void PhyTxStartTrace (std::string context, Ptr< const Packet > p)
void ReceivePacket (Ptr< Socket > socket)
Ptr< Socket > SetupPacketReceive (Ptr< Node > node)
Variables
static bool g_verbose = false
Function Documentation
PhyRxEndErrorTrace()
void PhyRxEndErrorTrace (std::string context, Ptr< const Packet > p)
Definition at line 86 of file adhoc-aloha-ideal-phy.cc.
References g_verbose.
PhyRxEndOkTrace()
void PhyRxEndOkTrace (std::string context, Ptr< const Packet > p)
Definition at line 77 of file adhoc-aloha-ideal-phy.cc.
References g_verbose.
PhyRxStartTrace()
void PhyRxStartTrace (std::string context, Ptr< const Packet > p)
Definition at line 68 of file adhoc-aloha-ideal-phy.cc.
References g_verbose.
PhyTxEndTrace()
void PhyTxEndTrace (std::string context, Ptr< const Packet > p)
Definition at line 59 of file adhoc-aloha-ideal-phy.cc.
References g_verbose.
PhyTxStartTrace()
void PhyTxStartTrace (std::string context, Ptr< const Packet > p)
Definition at line 49 of file adhoc-aloha-ideal-phy.cc.
References g_verbose.
ReceivePacket()
void ReceivePacket (Ptr< Socket > socket)
Definition at line 96 of file adhoc-aloha-ideal-phy.cc.
References g_verbose, ns3::Packet::GetSize(), and ns3::Socket::Recv().
Referenced by SetupPacketReceive().
SetupPacketReceive()
Ptr<Socket> SetupPacketReceive (Ptr< Node > node)
Definition at line 111 of file adhoc-aloha-ideal-phy.cc.
References ns3::Socket::CreateSocket(), ns3::TypeId::LookupByName(), ns3::MakeCallback(), ReceivePacket(), and sink.
Variable Documentation
g_verbose
bool g_verbose = false static
Definition at line 46 of file adhoc-aloha-ideal-phy.cc.
Referenced by PhyRxEndErrorTrace(), PhyRxEndOkTrace(), PhyRxStartTrace(), PhyTxEndTrace(), PhyTxStartTrace(), and ReceivePacket().