ns-3: ns3::Ipv6Address Class Reference
ns3::Ipv6Address Class Reference
Network » Address
Describes an IPv6 address.
#include "ipv6-address.h"
Public Member Functions
Ipv6Address ()
Default constructor.
Ipv6Address (char const *address)
Constructs an Ipv6Address by parsing the input C-string.
Ipv6Address (Ipv6Address const &addr)
Copy constructor.
Ipv6Address (Ipv6Address const *addr)
Copy constructor.
Ipv6Address (uint8_t address[16])
Constructs an Ipv6Address by using the input 16 bytes.
~Ipv6Address ()
Destructor.
Ipv6Address CombinePrefix (Ipv6Prefix const &prefix) const
Combine this address with a prefix.
void GetBytes (uint8_t buf[16]) const
Get the bytes corresponding to the address.
Ipv4Address GetIpv4MappedAddress () const
Return the Ipv4 address.
bool HasPrefix (Ipv6Prefix const &prefix) const
Compares an address and a prefix.
bool IsAllNodesMulticast () const
If the IPv6 address is "all nodes multicast" (ff02::1/8).
bool IsAllRoutersMulticast () const
If the IPv6 address is "all routers multicast" (ff02::2/8).
bool IsAny () const
If the IPv6 address is the "Any" address.
bool IsDocumentation () const
If the IPv6 address is a documentation address (2001:DB8::/32).
NS_DEPRECATED_3_31 bool IsEqual (const Ipv6Address &other) const
Comparison operation between two Ipv6Addresses.
bool IsInitialized (void) const
bool IsIpv4MappedAddress () const
If the address is an IPv4-mapped address.
bool IsLinkLocal () const
If the IPv6 address is a link-local address (fe80::/64).
bool IsLinkLocalMulticast () const
If the IPv6 address is link-local multicast (ff02::/16).
bool IsLocalhost () const
If the IPv6 address is localhost (::1).
bool IsMulticast () const
If the IPv6 address is multicast (ff00::/8).
bool IsSolicitedMulticast () const
If the IPv6 address is a Solicited multicast address.
operator Address () const
Convert to Address object.
void Print (std::ostream &os) const
Print this address to the given output stream.
void Serialize (uint8_t buf[16]) const
Serialize this address to a 16-byte buffer.
void Set (char const *address)
Sets an Ipv6Address by parsing the input C-string.
void Set (uint8_t address[16])
Set an Ipv6Address by using the input 16 bytes.
Static Public Member Functions
static Ipv6Address ConvertFrom (const Address &address)
Convert the Address object into an Ipv6Address ones.
static Ipv6Address Deserialize (const uint8_t buf[16])
Deserialize this address.
static Ipv6Address GetAllHostsMulticast ()
Get the "all hosts multicast" address.
static Ipv6Address GetAllNodesMulticast ()
Get the "all nodes multicast" address.
static Ipv6Address GetAllRoutersMulticast ()
Get the "all routers multicast" address.
static Ipv6Address GetAny ()
Get the "any" (::) Ipv6Address.
static Ipv6Address GetLoopback ()
Get the loopback address.
static Ipv6Address GetOnes ()
Get the "all-1" IPv6 address (ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff).
static Ipv6Address GetZero ()
Get the 0 (::) Ipv6Address.
static bool IsMatchingType (const Address &address)
If the Address matches the type.
static Ipv6Address MakeAutoconfiguredAddress (Address addr, Ipv6Address prefix)
Make the autoconfigured IPv6 address from a Mac address.
static Ipv6Address MakeAutoconfiguredAddress (Mac16Address addr, Ipv6Address prefix)
Make the autoconfigured IPv6 address with Mac16Address.
static Ipv6Address MakeAutoconfiguredAddress (Mac48Address addr, Ipv6Address prefix)
Make the autoconfigured IPv6 address with Mac48Address.
static Ipv6Address MakeAutoconfiguredAddress (Mac64Address addr, Ipv6Address prefix)
Make the autoconfigured IPv6 address with Mac64Address.
static Ipv6Address MakeAutoconfiguredAddress (Mac8Address addr, Ipv6Address prefix)
Make the autoconfigured IPv6 address with Mac8Address.
static Ipv6Address MakeAutoconfiguredLinkLocalAddress (Address mac)
Make the autoconfigured link-local IPv6 address from a Mac address.
static Ipv6Address MakeAutoconfiguredLinkLocalAddress (Mac16Address mac)
Make the autoconfigured link-local IPv6 address with Mac16Address.
static Ipv6Address MakeAutoconfiguredLinkLocalAddress (Mac48Address mac)
Make the autoconfigured link-local IPv6 address with Mac48Address.
static Ipv6Address MakeAutoconfiguredLinkLocalAddress (Mac64Address mac)
Make the autoconfigured link-local IPv6 address with Mac64Address.
static Ipv6Address MakeAutoconfiguredLinkLocalAddress (Mac8Address mac)
Make the autoconfigured link-local IPv6 address with Mac8Address.
static Ipv6Address MakeIpv4MappedAddress (Ipv4Address addr)
Make the Ipv4-mapped IPv6 address.
static Ipv6Address MakeSolicitedAddress (Ipv6Address addr)
Make the solicited IPv6 address.
Private Member Functions
Address ConvertTo (void) const
convert the IPv6Address object to an Address object.
Static Private Member Functions
static uint8_t GetType (void)
Return the Type of address.
Private Attributes
uint8_t m_address [16]
The address representation on 128 bits (16 bytes).
bool m_initialized
IPv6 address has been explicitly initialized to a valid value.
Friends
bool operator!= (Ipv6Address const &a, Ipv6Address const &b)
Not equal to operator.
bool operator< (Ipv6Address const &a, Ipv6Address const &b)
Less than to operator.
bool operator== (Ipv6Address const &a, Ipv6Address const &b)
Equal to operator.
Detailed Description
Describes an IPv6 address.
See also
Ipv6Prefix
Ipv6Address Attribute
Definition at line 49 of file ipv6-address.h.
Constructor & Destructor Documentation
Ipv6Address() [1/5]
ns3::Ipv6Address::Ipv6Address ()
Default constructor.
Definition at line 281 of file ipv6-address.cc.
References m_address, m_initialized, and NS_LOG_FUNCTION.
Ipv6Address() [2/5]
ns3::Ipv6Address::Ipv6Address (char const * address)
Constructs an Ipv6Address by parsing the input C-string.
Parameters
address the C-string containing the IPv6 address (e.g. 2001:660:4701::1).
Definition at line 302 of file ipv6-address.cc.
References first::address, ns3::AsciiToIpv6Host(), m_address, m_initialized, and NS_LOG_FUNCTION.
Ipv6Address() [3/5]
ns3::Ipv6Address::Ipv6Address (uint8_t address[16])
Constructs an Ipv6Address by using the input 16 bytes.
Parameters
address the 128-bit address
Warning
the parameter must point on a 16 bytes integer array!
Definition at line 309 of file ipv6-address.cc.
References first::address, m_address, m_initialized, and NS_LOG_FUNCTION.
Ipv6Address() [4/5]
ns3::Ipv6Address::Ipv6Address (Ipv6Address const & addr)
Copy constructor.
Parameters
addr Ipv6Address object
Definition at line 288 of file ipv6-address.cc.
References m_address, and m_initialized.
Ipv6Address() [5/5]
ns3::Ipv6Address::Ipv6Address (Ipv6Address const * addr)
Copy constructor.
Parameters
addr Ipv6Address pointer
Definition at line 295 of file ipv6-address.cc.
References m_address, and m_initialized.
~Ipv6Address()
ns3::Ipv6Address::~Ipv6Address ()
Destructor.
Definition at line 317 of file ipv6-address.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CombinePrefix()
Ipv6Address ns3::Ipv6Address::CombinePrefix (Ipv6Prefix const & prefix) const
Combine this address with a prefix.
Parameters
prefix a IPv6 prefix
Returns
an IPv6 address that is this address combined (bitwise AND) with a prefix, yielding an IPv6 network address.
Definition at line 740 of file ipv6-address.cc.
References m_address, NS_LOG_FUNCTION, and Set().
Referenced by ns3::Ipv6AddressHelper::Ipv6AddressHelper(), ns3::RipNg::HandleRequests(), ns3::RipNg::HandleResponses(), HasPrefix(), IsDocumentation(), ns3::Ipv6InterfaceAddress::IsInSameSubnet(), IsLinkLocal(), ns3::Ipv6AddressGeneratorImpl::IsNetworkAllocated(), ns3::Ipv6AddressHelper::NewAddress(), and ns3::Ipv6AddressHelper::SetBase().
ConvertFrom()
Ipv6Address ns3::Ipv6Address::ConvertFrom (const Address & address) static
Convert the Address object into an Ipv6Address ones.
Parameters
address address to convert
Returns
an Ipv6Address
Definition at line 845 of file ipv6-address.cc.
References first::address, Deserialize(), GetType(), NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::UdpSocketImpl::DoSend(), ns3::UdpSocketImpl::GetPeerName(), ns3::ThreeGppHttpClient::OpenConnection(), ns3::PbbAddressBlockIpv6::PrintAddress(), ns3::PbbMessageIpv6::PrintOriginatorAddress(), ns3::UdpClient::Send(), ns3::UdpEchoClient::Send(), ns3::TcpL4Protocol::SendPacket(), ns3::UdpTraceClient::SendPacket(), UanExperiment::SendSinglePacket(), ns3::PbbAddressBlockIpv6::SerializeAddress(), ns3::PbbMessageIpv6::SerializeOriginatorAddress(), ns3::ThreeGppHttpServer::StartApplication(), ns3::UdpClient::StartApplication(), ns3::UdpEchoClient::StartApplication(), and ns3::UdpTraceClient::StartApplication().
ConvertTo()
Address ns3::Ipv6Address::ConvertTo (void) const private
convert the IPv6Address object to an Address object.
Returns
the Address object corresponding to this object.
Definition at line 837 of file ipv6-address.cc.
References GetType(), NS_LOG_FUNCTION, and Serialize().
Deserialize()
Ipv6Address ns3::Ipv6Address::Deserialize (const uint8_t buf[16]) static
Deserialize this address.
Parameters
buf buffer to read address from
Returns
an Ipv6Address
Definition at line 344 of file ipv6-address.cc.
References m_initialized, and NS_LOG_FUNCTION.
Referenced by ns3::Inet6SocketAddress::ConvertFrom(), ConvertFrom(), ns3::SixLowPanIphc::Deserialize(), ns3::Ipv6PacketInfoTag::Deserialize(), ns3::PbbAddressBlockIpv6::DeserializeAddress(), and ns3::PbbMessageIpv6::DeserializeOriginatorAddress().
GetAllHostsMulticast()
Ipv6Address ns3::Ipv6Address::GetAllHostsMulticast () static
Get the "all hosts multicast" address.
Returns
the "ff02::3/8" Ipv6Address representation
Definition at line 875 of file ipv6-address.cc.
References NS_LOG_FUNCTION_NOARGS.
GetAllNodesMulticast()
Ipv6Address ns3::Ipv6Address::GetAllNodesMulticast () static
Get the "all nodes multicast" address.
Returns
the "ff02::2/8" Ipv6Address representation
Definition at line 861 of file ipv6-address.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Icmpv6L4Protocol::HandleNS(), ns3::Radvd::HandleRead(), ns3::Radvd::Send(), ns3::Icmpv6L4Protocol::SendNS(), and ns3::Radvd::StartApplication().
GetAllRoutersMulticast()
Ipv6Address ns3::Ipv6Address::GetAllRoutersMulticast () static
Get the "all routers multicast" address.
Returns
the "ff02::2/8" Ipv6Address representation
Definition at line 868 of file ipv6-address.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Icmpv6L4Protocol::FunctionDadTimeout(), ns3::Ipv6EndPointDemux::Lookup(), and ns3::Radvd::StartApplication().
GetAny()
Ipv6Address ns3::Ipv6Address::GetAny (void) static
Get the "any" (::) Ipv6Address.
Returns
the "any" (::) Ipv6Address
Definition at line 896 of file ipv6-address.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Ipv6RawSocketImpl::Ipv6RawSocketImpl(), ns3::Ipv6L3Protocol::AddAutoconfiguredAddress(), ns3::Ipv6EndPointDemux::Allocate(), ns3::Ipv6RawSocketImpl::Bind(), ns3::TcpSocketBase::Bind(), ns3::UdpSocketImpl::Bind(), ns3::SixLowPanNetDevice::DecompressLowPanIphc(), ns3::RipNg::DoSendRouteUpdate(), ns3::UdpSocketImpl::DoSendTo(), ns3::Icmpv6L4Protocol::ForgeNA(), ns3::Ipv6RawSocketImpl::ForwardUp(), ns3::Ipv6InterfaceContainer::GetLinkLocalAddress(), ns3::Icmpv6L4Protocol::HandleNS(), ns3::RipNg::HandleRequests(), ns3::RipNg::HandleResponses(), ns3::Icmpv6L4Protocol::HandleRS(), ns3::Ipv6L3Protocol::IpMulticastForward(), ns3::Socket::Ipv6LeaveGroup(), ns3::Ipv6EndPointDemux::Lookup(), MakeAutoconfiguredAddress(), MakeAutoconfiguredLinkLocalAddress(), ns3::Ipv6L3Protocol::RemoveAutoconfiguredAddress(), ns3::Icmpv6L4Protocol::SendNA(), ns3::Icmpv6L4Protocol::SendNS(), ns3::Ipv6L3Protocol::SendRealOut(), ns3::RipNg::SendRouteRequest(), ns3::Icmpv6L4Protocol::SendRS(), ns3::Ipv6InterfaceContainer::SetDefaultRoute(), ns3::Ipv6InterfaceContainer::SetDefaultRouteInAllNodes(), UanExperiment::SetupApplications(), ns3::Ipv6EndPointDemux::SimpleLookup(), ns3::UdpEchoServer::StartApplication(), and ns3::UdpServer::StartApplication().
GetBytes()
void ns3::Ipv6Address::GetBytes (uint8_t buf[16]) const
Get the bytes corresponding to the address.
Parameters
buf buffer to store the data
Returns
bytes of the address
Definition at line 910 of file ipv6-address.cc.
References m_address, and NS_LOG_FUNCTION.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanHc1(), ns3::SixLowPanNetDevice::CompressLowPanIphc(), ns3::Ipv6AddressGeneratorImpl::Init(), ns3::Ipv6AddressGeneratorImpl::InitAddress(), ns3::Ipv6Prefix::IsMatch(), MakeAutoconfiguredAddress(), ns3::Ipv6AddressHelper::NewAddress(), ns3::Ipv6AddressHelper::NewNetwork(), ns3::Ipv6AddressGeneratorImpl::NextNetwork(), ns3::Icmpv6OptionPrefixInformation::Serialize(), and ns3::WriteTo().
GetIpv4MappedAddress()
Ipv4Address ns3::Ipv6Address::GetIpv4MappedAddress () const
Return the Ipv4 address.
Returns
Ipv4 address
Definition at line 361 of file ipv6-address.cc.
References ns3::Ipv4Address::Deserialize(), NS_LOG_FUNCTION, and Serialize().
Referenced by ns3::TcpSocketBase::Connect(), ns3::UdpSocketImpl::DoSendTo(), and ns3::TcpL4Protocol::SendPacketV6().
GetLoopback()
Ipv6Address ns3::Ipv6Address::GetLoopback (void) static
Get the loopback address.
Returns
the "::1/128" Ipv6Address representation.
Definition at line 882 of file ipv6-address.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Ipv6L3Protocol::RemoveAddress(), and ns3::Ipv6L3Protocol::SetupLoopback().
GetOnes()
Ipv6Address ns3::Ipv6Address::GetOnes (void) static
Get the "all-1" IPv6 address (ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff).
Returns
all-1 Ipv6Address representation
Definition at line 903 of file ipv6-address.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by HasPrefix().
GetType()
uint8_t ns3::Ipv6Address::GetType (void) static private
Return the Type of address.
Returns
type of address
Definition at line 854 of file ipv6-address.cc.
References NS_LOG_FUNCTION_NOARGS, and ns3::Address::Register().
Referenced by ConvertFrom(), ConvertTo(), and IsMatchingType().
GetZero()
Ipv6Address ns3::Ipv6Address::GetZero (void) static
Get the 0 (::) Ipv6Address.
Returns
the :: Ipv6Address representation
Definition at line 889 of file ipv6-address.cc.
References NS_LOG_FUNCTION_NOARGS, and zero.
Referenced by ns3::Ipv6AddressHelper::Ipv6AddressHelper(), ns3::TapFdNetDeviceHelper::TapFdNetDeviceHelper(), ns3::Ipv6RoutingTableEntry::CreateDefaultRoute(), ns3::TapFdNetDeviceHelper::CreateFileDescriptor(), ns3::Ipv6FlowClassifier::FindFlow(), ns3::Icmpv6L4Protocol::HandleRA(), ns3::Ipv6RoutingTableEntry::IsDefault(), ns3::Ipv6RoutingTableEntry::IsGateway(), ns3::RipNg::Lookup(), ns3::Ipv6StaticRouting::LookupStatic(), ns3::Ipv6AddressHelper::NewAddress(), ns3::Ipv6StaticRouting::NotifyAddRoute(), ns3::Ipv6StaticRouting::NotifyRemoveRoute(), ns3::Ipv6L3Protocol::Send(), and ns3::Ipv6AddressHelper::SetBase().
HasPrefix()
bool ns3::Ipv6Address::HasPrefix (Ipv6Prefix const & prefix) const
Compares an address and a prefix.
Parameters
prefix the prefix to compare with
Returns
true if the address has the given prefix
Definition at line 815 of file ipv6-address.cc.
References CombinePrefix(), GetOnes(), NS_LOG_FUNCTION, and anonymous_namespace{print-introspected-doxygen.cc}::reference.
IsAllNodesMulticast()
bool ns3::Ipv6Address::IsAllNodesMulticast () const
If the IPv6 address is "all nodes multicast" (ff02::1/8).
Returns
true if "all nodes multicast", false otherwise
Definition at line 777 of file ipv6-address.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::Ipv6L3Protocol::Receive().
IsAllRoutersMulticast()
bool ns3::Ipv6Address::IsAllRoutersMulticast () const
If the IPv6 address is "all routers multicast" (ff02::2/8).
Returns
true if "all routers multicast", false otherwise
Definition at line 786 of file ipv6-address.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::Ipv6L3Protocol::Receive().
IsAny()
bool ns3::Ipv6Address::IsAny (void) const
If the IPv6 address is the "Any" address.
Returns
true if it is, false otherwise
Definition at line 796 of file ipv6-address.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::Ipv6Interface::AddAddress(), ns3::Ipv6L3Protocol::AddAutoconfiguredAddress(), ns3::NdiscCache::Entry::FunctionDelayTimeout(), ns3::NdiscCache::Entry::FunctionProbeTimeout(), ns3::NdiscCache::Entry::FunctionRetransmitTimeout(), ns3::Ipv6RawSocketImpl::GetPeerName(), ns3::Icmpv6L4Protocol::HandleNS(), ns3::Ipv6L3Protocol::IpForward(), ns3::Ipv6RawSocketImpl::Ipv6JoinGroup(), ns3::UdpSocketImpl::Ipv6JoinGroup(), ns3::Socket::Ipv6LeaveGroup(), ns3::RipNg::Lookup(), ns3::Ipv6StaticRouting::LookupStatic(), MakeAutoconfiguredAddress(), MakeAutoconfiguredLinkLocalAddress(), and ns3::Ipv6RawSocketImpl::SendTo().
IsDocumentation()
bool ns3::Ipv6Address::IsDocumentation () const
If the IPv6 address is a documentation address (2001:DB8::/32).
Returns
true if the address is documentation, false otherwise
Definition at line 804 of file ipv6-address.cc.
References CombinePrefix(), and NS_LOG_FUNCTION.
Referenced by ns3::Ipv6L3Protocol::IpForward().
IsEqual()
bool ns3::Ipv6Address::IsEqual (const Ipv6Address & other) const
Comparison operation between two Ipv6Addresses.
Deprecated:
Use the == operator (same functionality)
Parameters
other the IPv6 address to which to compare this address
Returns
true if the addresses are equal, false otherwise
Definition at line 927 of file ipv6-address.cc.
References m_address, and NS_LOG_FUNCTION.
IsInitialized()
bool ns3::Ipv6Address::IsInitialized (void) const
Returns
true if address is initialized (i.e., set to something), false otherwise
Definition at line 937 of file ipv6-address.cc.
References m_initialized, and NS_LOG_FUNCTION.
IsIpv4MappedAddress()
bool ns3::Ipv6Address::IsIpv4MappedAddress () const
If the address is an IPv4-mapped address.
Returns
true if address is an IPv4-mapped address, otherwise false.
Definition at line 728 of file ipv6-address.cc.
References m_address, and NS_LOG_FUNCTION.
Referenced by ns3::TcpSocketBase::Connect(), ns3::UdpSocketImpl::DoSendTo(), Print(), and ns3::TcpL4Protocol::SendPacketV6().
IsLinkLocal()
bool ns3::Ipv6Address::IsLinkLocal () const
If the IPv6 address is a link-local address (fe80::/64).
Returns
true if the address is link-local, false otherwise
Definition at line 916 of file ipv6-address.cc.
References CombinePrefix(), IsMulticast(), and NS_LOG_FUNCTION.
Referenced by ns3::Ipv6StaticRouting::AddHostRouteTo(), ns3::RipNg::AddNetworkRouteTo(), ns3::Ipv6StaticRouting::AddNetworkRouteTo(), ns3::SixLowPanNetDevice::CompressLowPanHc1(), ns3::SixLowPanNetDevice::CompressLowPanIphc(), Ipv6L3ProtocolTestCase::DoRun(), ns3::Icmpv6L4Protocol::FunctionDadTimeout(), ns3::AnimationInterface::GetIpv6Address(), ns3::Icmpv6L4Protocol::HandleNS(), ns3::RipNg::HandleRequests(), ns3::RipNg::HandleResponses(), ns3::Ipv6L3Protocol::IpForward(), ns3::Ipv6InterfaceAddress::IsInSameSubnet(), ns3::Icmpv6L4Protocol::Lookup(), ns3::RipNg::RouteInput(), ns3::Ipv6L3Protocol::Send(), and ns3::Ipv6L3Protocol::SourceAddressSelection().
IsLinkLocalMulticast()
bool ns3::Ipv6Address::IsLinkLocalMulticast () const
If the IPv6 address is link-local multicast (ff02::/16).
Returns
true if link-local multicast, false otherwise
Definition at line 718 of file ipv6-address.cc.
References m_address, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv6InterfaceAddress::IsInSameSubnet(), ns3::RipNg::Lookup(), ns3::Ipv6StaticRouting::LookupStatic(), ns3::Ipv6L3Protocol::Send(), and ns3::Ipv6L3Protocol::SourceAddressSelection().
IsLocalhost()
bool ns3::Ipv6Address::IsLocalhost (void) const
If the IPv6 address is localhost (::1).
Returns
true if localhost, false otherwise
Definition at line 701 of file ipv6-address.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::Ipv6Interface::AddAddress().
IsMatchingType()
bool ns3::Ipv6Address::IsMatchingType (const Address & address) static
If the Address matches the type.
Parameters
address other address
Returns
true if the type matches, false otherwise
Definition at line 826 of file ipv6-address.cc.
References first::address, GetType(), and NS_LOG_FUNCTION.
Referenced by ns3::UdpHeader::CalculateHeaderChecksum(), ns3::UdpSocketImpl::DoSend(), ns3::UdpSocketImpl::GetPeerName(), ns3::ThreeGppHttpClient::OpenConnection(), ns3::UdpClient::Send(), ns3::UdpEchoClient::Send(), ns3::TcpL4Protocol::SendPacket(), ns3::UdpTraceClient::SendPacket(), ns3::ThreeGppHttpServer::StartApplication(), ns3::UdpClient::StartApplication(), ns3::UdpEchoClient::StartApplication(), and ns3::UdpTraceClient::StartApplication().
IsMulticast()
bool ns3::Ipv6Address::IsMulticast (void) const
If the IPv6 address is multicast (ff00::/8).
Returns
true if multicast, false otherwise
Definition at line 708 of file ipv6-address.cc.
References m_address, and NS_LOG_FUNCTION.
Referenced by ns3::UdpSocketImpl::Bind(), ns3::UdpSocketImpl::BindToNetDevice(), ns3::Ipv6FlowClassifier::Classify(), ns3::SixLowPanNetDevice::CompressLowPanIphc(), ns3::UdpSocketImpl::DoSendTo(), ns3::Icmpv6L4Protocol::HandleEchoRequest(), ns3::Ipv6L3Protocol::IpForward(), IsLinkLocal(), ns3::Ipv6L3Protocol::LocalDeliver(), ns3::Ipv6ExtensionLooseRouting::Process(), ns3::Ipv6Extension::ProcessOptions(), ns3::Ipv6L3Protocol::Receive(), ns3::Ipv6StaticRouting::RouteInput(), ns3::RipNg::RouteInput(), ns3::Ipv6L3Protocol::RouteInputError(), ns3::Ipv6StaticRouting::RouteOutput(), ns3::RipNg::RouteOutput(), ns3::Ipv6Interface::Send(), ns3::Icmpv6L4Protocol::SendNS(), and ns3::Icmpv6L4Protocol::SendRS().
IsSolicitedMulticast()
bool ns3::Ipv6Address::IsSolicitedMulticast () const
If the IPv6 address is a Solicited multicast address.
Returns
true if it is, false otherwise
Definition at line 760 of file ipv6-address.cc.
References NS_LOG_FUNCTION, and Serialize().
MakeAutoconfiguredAddress() [1/5]
Ipv6Address ns3::Ipv6Address::MakeAutoconfiguredAddress (Address addr, Ipv6Address prefix) static
Make the autoconfigured IPv6 address from a Mac address.
Actually the MAC supported are: Mac8, Mac16, Mac48, and Mac64.
Parameters
addr the MAC address.
prefix the IPv6 prefix
Returns
autoconfigured IPv6 address
Definition at line 372 of file ipv6-address.cc.
References ns3::Mac16Address::ConvertFrom(), ns3::Mac48Address::ConvertFrom(), ns3::Mac64Address::ConvertFrom(), ns3::Mac8Address::ConvertFrom(), GetAny(), IsAny(), ns3::Mac16Address::IsMatchingType(), ns3::Mac48Address::IsMatchingType(), ns3::Mac64Address::IsMatchingType(), ns3::Mac8Address::IsMatchingType(), and NS_ABORT_MSG.
Referenced by ns3::Ipv6L3Protocol::AddAutoconfiguredAddress(), ns3::SixLowPanNetDevice::DecompressLowPanHc1(), ns3::Ipv6AddressHelper::NewAddress(), and ns3::Ipv6L3Protocol::RemoveAutoconfiguredAddress().
MakeAutoconfiguredAddress() [2/5]
Ipv6Address ns3::Ipv6Address::MakeAutoconfiguredAddress (Mac16Address addr, Ipv6Address prefix) static
Make the autoconfigured IPv6 address with Mac16Address.
The EUI-64 scheme used is based on the RFC 4944.
Parameters
addr the MAC address (16 bits).
prefix the IPv6 prefix
Returns
autoconfigured IPv6 address
Definition at line 400 of file ipv6-address.cc.
References ns3::Mac16Address::CopyTo(), GetBytes(), NS_LOG_FUNCTION, and Set().
MakeAutoconfiguredAddress() [3/5]
Ipv6Address ns3::Ipv6Address::MakeAutoconfiguredAddress (Mac48Address addr, Ipv6Address prefix) static
Make the autoconfigured IPv6 address with Mac48Address.
The EUI-64 scheme used is based on RFC 2464.
Parameters
addr the MAC address (48 bits).
prefix the IPv6 prefix
Returns
autoconfigured IPv6 address
Definition at line 419 of file ipv6-address.cc.
References ns3::Mac48Address::CopyTo(), GetBytes(), NS_LOG_FUNCTION, and Set().
MakeAutoconfiguredAddress() [4/5]
Ipv6Address ns3::Ipv6Address::MakeAutoconfiguredAddress (Mac64Address addr, Ipv6Address prefix) static
Make the autoconfigured IPv6 address with Mac64Address.
Parameters
addr the MAC address (64 bits).
prefix the IPv6 prefix
Returns
autoconfigured IPv6 address
Definition at line 439 of file ipv6-address.cc.
References ns3::Mac64Address::CopyTo(), GetBytes(), NS_LOG_FUNCTION, and Set().
MakeAutoconfiguredAddress() [5/5]
Ipv6Address ns3::Ipv6Address::MakeAutoconfiguredAddress (Mac8Address addr, Ipv6Address prefix) static
Make the autoconfigured IPv6 address with Mac8Address.
The EUI-64 scheme used is loosely based on the RFC 2464.
Parameters
addr the Mac8Address address (8 bits).
prefix the IPv6 prefix
Returns
autoconfigured IPv6 address
Definition at line 455 of file ipv6-address.cc.
References ns3::Mac8Address::CopyTo(), GetBytes(), NS_LOG_FUNCTION, and Set().
MakeAutoconfiguredLinkLocalAddress() [1/5]
Ipv6Address ns3::Ipv6Address::MakeAutoconfiguredLinkLocalAddress (Address mac) static
Make the autoconfigured link-local IPv6 address from a Mac address.
Actually the MAC supported are: Mac8, Mac16, Mac48, and Mac64.
Parameters
mac the MAC address.
Returns
autoconfigured link-local IPv6 address
Definition at line 475 of file ipv6-address.cc.
References ns3::Mac16Address::ConvertFrom(), ns3::Mac48Address::ConvertFrom(), ns3::Mac64Address::ConvertFrom(), ns3::Mac8Address::ConvertFrom(), GetAny(), IsAny(), ns3::Mac16Address::IsMatchingType(), ns3::Mac48Address::IsMatchingType(), ns3::Mac64Address::IsMatchingType(), ns3::Mac8Address::IsMatchingType(), and NS_ABORT_MSG.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanHc1(), ns3::SixLowPanNetDevice::CompressLowPanIphc(), ns3::SixLowPanNetDevice::DecompressLowPanHc1(), ns3::SixLowPanNetDevice::DecompressLowPanIphc(), and ns3::Ipv6Interface::DoSetup().
MakeAutoconfiguredLinkLocalAddress() [2/5]
Ipv6Address ns3::Ipv6Address::MakeAutoconfiguredLinkLocalAddress (Mac16Address mac) static
Make the autoconfigured link-local IPv6 address with Mac16Address.
The EUI-64 scheme used is based on the RFC 4944.
Parameters
mac the MAC address (16 bits).
Returns
autoconfigured link-local IPv6 address
Definition at line 503 of file ipv6-address.cc.
References ns3::Mac16Address::CopyTo(), NS_LOG_FUNCTION, and Set().
MakeAutoconfiguredLinkLocalAddress() [3/5]
Ipv6Address ns3::Ipv6Address::MakeAutoconfiguredLinkLocalAddress (Mac48Address mac) static
Make the autoconfigured link-local IPv6 address with Mac48Address.
The EUI-64 scheme used is based on RFC 2464.
Parameters
mac the MAC address (48 bits).
Returns
autoconfigured link-local IPv6 address
Definition at line 523 of file ipv6-address.cc.
References ns3::Mac48Address::CopyTo(), NS_LOG_FUNCTION, and Set().
MakeAutoconfiguredLinkLocalAddress() [4/5]
Ipv6Address ns3::Ipv6Address::MakeAutoconfiguredLinkLocalAddress (Mac64Address mac) static
Make the autoconfigured link-local IPv6 address with Mac64Address.
Parameters
mac the MAC address (64 bits).
Returns
autoconfigured link-local IPv6 address
Definition at line 545 of file ipv6-address.cc.
References ns3::Mac64Address::CopyTo(), NS_LOG_FUNCTION, and Set().
MakeAutoconfiguredLinkLocalAddress() [5/5]
Ipv6Address ns3::Ipv6Address::MakeAutoconfiguredLinkLocalAddress (Mac8Address mac) static
Make the autoconfigured link-local IPv6 address with Mac8Address.
The EUI-64 scheme used is loosely based on the RFC 2464.
Parameters
mac the MAC address (8 bits).
Returns
autoconfigured link-local IPv6 address
Definition at line 563 of file ipv6-address.cc.
References ns3::Mac8Address::CopyTo(), NS_LOG_FUNCTION, and Set().
MakeIpv4MappedAddress()
Ipv6Address ns3::Ipv6Address::MakeIpv4MappedAddress (Ipv4Address addr) static
Make the Ipv4-mapped IPv6 address.
Parameters
addr the IPv4 address
Returns
Ipv4-mapped IPv6 address
Definition at line 352 of file ipv6-address.cc.
References NS_LOG_FUNCTION, and ns3::Ipv4Address::Serialize().
MakeSolicitedAddress()
Ipv6Address ns3::Ipv6Address::MakeSolicitedAddress (Ipv6Address addr) static
Make the solicited IPv6 address.
Parameters
addr the IPv6 address
Returns
Solicited IPv6 address
Definition at line 584 of file ipv6-address.cc.
References NS_LOG_FUNCTION, Serialize(), and Set().
Referenced by ns3::Ipv6Interface::AddAddress(), ns3::Icmpv6L4Protocol::DoDAD(), ns3::NdiscCache::Entry::FunctionRetransmitTimeout(), and ns3::Icmpv6L4Protocol::Lookup().
operator Address()
ns3::Ipv6Address::operator Address () const
Convert to Address object.
Definition at line 832 of file ipv6-address.cc.
Print()
void ns3::Ipv6Address::Print (std::ostream & os) const
Print this address to the given output stream.
The print format is in the typical "2001:660:4701::1".
Parameters
os the output stream to which this Ipv6Address is printed
Definition at line 606 of file ipv6-address.cc.
References first::address, IsIpv4MappedAddress(), m_address, and NS_LOG_FUNCTION.
Referenced by ns3::PbbAddressBlockIpv6::PrintAddress(), and ns3::PbbMessageIpv6::PrintOriginatorAddress().
Serialize()
void ns3::Ipv6Address::Serialize (uint8_t buf[16]) const
Serialize this address to a 16-byte buffer.
Parameters
buf the output buffer to which this address gets overwritten with this Ipv6Address
Definition at line 338 of file ipv6-address.cc.
References m_address, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6Header::CalculatePseudoHeaderChecksum(), ns3::Inet6SocketAddress::ConvertTo(), ConvertTo(), Ipv6AddressTestCase::DoRun(), GetIpv4MappedAddress(), ns3::Mac48Address::GetMulticast(), ns3::Ipv6QueueDiscItem::Hash(), IsSolicitedMulticast(), MakeSolicitedAddress(), ns3::Icmpv6NS::Serialize(), ns3::Icmpv6NA::Serialize(), ns3::Icmpv6Redirection::Serialize(), ns3::RipNgRte::Serialize(), ns3::SixLowPanIphc::Serialize(), ns3::Ipv6PacketInfoTag::Serialize(), ns3::PbbAddressBlockIpv6::SerializeAddress(), and ns3::PbbMessageIpv6::SerializeOriginatorAddress().
Set() [1/2]
void ns3::Ipv6Address::Set (char const * address)
Sets an Ipv6Address by parsing the input C-string.
Parameters
address the C-string containing the IPv6 address (e.g. 2001:660:4701::1).
Definition at line 323 of file ipv6-address.cc.
References first::address, ns3::AsciiToIpv6Host(), m_address, m_initialized, and NS_LOG_FUNCTION.
Referenced by EpcTftClassifierTestSuite::EpcTftClassifierTestSuite(), CombinePrefix(), ns3::Icmpv6NS::Deserialize(), ns3::Icmpv6NA::Deserialize(), ns3::Icmpv6Redirection::Deserialize(), ns3::RipNgRte::Deserialize(), MakeAutoconfiguredAddress(), MakeAutoconfiguredLinkLocalAddress(), MakeSolicitedAddress(), and ns3::ReadFrom().
Set() [2/2]
void ns3::Ipv6Address::Set (uint8_t address[16])
Set an Ipv6Address by using the input 16 bytes.
Parameters
address the 128-bit address
Warning
the parameter must point on a 16 bytes integer array!
Definition at line 330 of file ipv6-address.cc.
References first::address, m_address, m_initialized, and NS_LOG_FUNCTION.
Friends And Related Function Documentation
operator!=
bool operator!= (Ipv6Address const & a, Ipv6Address const & b) friend
Not equal to operator.
Parameters
a the first operand.
b the first operand.
Returns
true if the operands are not equal.
Definition at line 664 of file ipv6-address.h.
operator<
bool operator< (Ipv6Address const & a, Ipv6Address const & b) friend
Less than to operator.
Parameters
a the first operand.
b the first operand.
Returns
true if the first operand is less than the second.
Definition at line 669 of file ipv6-address.h.
operator==
bool operator== (Ipv6Address const & a, Ipv6Address const & b) friend
Equal to operator.
Parameters
a the first operand.
b the first operand.
Returns
true if the operands are equal.
Definition at line 659 of file ipv6-address.h.
Member Data Documentation
m_address
uint8_t ns3::Ipv6Address::m_address[16] private
The address representation on 128 bits (16 bytes).
Definition at line 417 of file ipv6-address.h.
Referenced by Ipv6Address(), CombinePrefix(), GetBytes(), IsEqual(), IsIpv4MappedAddress(), IsLinkLocalMulticast(), IsMulticast(), Print(), Serialize(), and Set().
m_initialized
bool ns3::Ipv6Address::m_initialized private
IPv6 address has been explicitly initialized to a valid value.
Definition at line 418 of file ipv6-address.h.
Referenced by Ipv6Address(), Deserialize(), IsInitialized(), and Set().
The documentation for this class was generated from the following files:
src/network/utils/ipv6-address.h
src/network/utils/ipv6-address.cc