ns-3: ns3::ConstantVelocityHelper Class Reference
ns3::ConstantVelocityHelper Class Reference
Mobility
Utility class used to move node with constant velocity.
#include "constant-velocity-helper.h"
Public Member Functions
ConstantVelocityHelper ()
ConstantVelocityHelper (const Vector &position)
Create object and set position.
ConstantVelocityHelper (const Vector &position, const Vector &vel)
Create object and set position and velocity.
Vector GetCurrentPosition (void) const
Get current position vector.
Vector GetVelocity (void) const
Get velocity; if paused, will return a zero vector.
void Pause (void)
Pause mobility at current position.
void SetPosition (const Vector &position)
Set position vector.
void SetVelocity (const Vector &vel)
Set new velocity vector.
void Unpause (void)
Resume mobility from current position at current velocity.
void Update (void) const
Update position, if not paused, from last position and time of last update.
void UpdateWithBounds (const Box &bounds) const
Update position, if not paused, from last position and time of last update.
void UpdateWithBounds (const Rectangle &rectangle) const
Update position, if not paused, from last position and time of last update.
Private Attributes
Time m_lastUpdate
time of last update
bool m_paused
state variable for paused
Vector m_position
state variable for current position
Vector m_velocity
state variable for velocity
Detailed Description
Utility class used to move node with constant velocity.
Definition at line 36 of file constant-velocity-helper.h.
Constructor & Destructor Documentation
ConstantVelocityHelper() [1/3]
ns3::ConstantVelocityHelper::ConstantVelocityHelper ()
Definition at line 30 of file constant-velocity-helper.cc.
References NS_LOG_FUNCTION.
ConstantVelocityHelper() [2/3]
ns3::ConstantVelocityHelper::ConstantVelocityHelper (const Vector & position)
Create object and set position.
Parameters
position the position vector
Definition at line 35 of file constant-velocity-helper.cc.
References NS_LOG_FUNCTION.
ConstantVelocityHelper() [3/3]
ns3::ConstantVelocityHelper::ConstantVelocityHelper (const Vector & position, const Vector & vel)
Create object and set position and velocity.
Parameters
position the position vector
vel the velocity vector
Definition at line 41 of file constant-velocity-helper.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
GetCurrentPosition()
Vector ns3::ConstantVelocityHelper::GetCurrentPosition (void) const
Get current position vector.
Returns
Position vector
Definition at line 59 of file constant-velocity-helper.cc.
References m_position, and NS_LOG_FUNCTION.
Referenced by ns3::RandomWaypointMobilityModel::BeginWalk(), ns3::SteadyStateRandomWaypointMobilityModel::BeginWalk(), ns3::RandomWalk2dOutdoorMobilityModel::DoGetPosition(), ns3::ConstantVelocityMobilityModel::DoGetPosition(), ns3::GaussMarkovMobilityModel::DoGetPosition(), ns3::RandomDirection2dMobilityModel::DoGetPosition(), ns3::RandomWalk2dMobilityModel::DoGetPosition(), ns3::RandomWaypointMobilityModel::DoGetPosition(), ns3::SteadyStateRandomWaypointMobilityModel::DoGetPosition(), ns3::RandomWalk2dOutdoorMobilityModel::DoWalk(), ns3::GaussMarkovMobilityModel::DoWalk(), ns3::RandomWalk2dMobilityModel::DoWalk(), ns3::RandomWalk2dOutdoorMobilityModel::Rebound(), ns3::RandomWalk2dMobilityModel::Rebound(), ns3::RandomDirection2dMobilityModel::ResetDirectionAndSpeed(), ns3::RandomDirection2dMobilityModel::SetDirectionAndSpeed(), and ns3::SteadyStateRandomWaypointMobilityModel::SteadyStateBeginWalk().
GetVelocity()
Vector ns3::ConstantVelocityHelper::GetVelocity (void) const
Get velocity; if paused, will return a zero vector.
Returns
Velocity vector
Definition at line 66 of file constant-velocity-helper.cc.
References m_paused, m_velocity, and NS_LOG_FUNCTION.
Referenced by ns3::RandomWalk2dOutdoorMobilityModel::DoGetVelocity(), ns3::ConstantVelocityMobilityModel::DoGetVelocity(), ns3::GaussMarkovMobilityModel::DoGetVelocity(), ns3::RandomDirection2dMobilityModel::DoGetVelocity(), ns3::RandomWalk2dMobilityModel::DoGetVelocity(), ns3::RandomWaypointMobilityModel::DoGetVelocity(), ns3::SteadyStateRandomWaypointMobilityModel::DoGetVelocity(), ns3::RandomWalk2dOutdoorMobilityModel::DoWalk(), ns3::GaussMarkovMobilityModel::DoWalk(), ns3::RandomWalk2dMobilityModel::DoWalk(), ns3::RandomWalk2dOutdoorMobilityModel::Rebound(), and ns3::RandomWalk2dMobilityModel::Rebound().
Pause()
void ns3::ConstantVelocityHelper::Pause (void)
Pause mobility at current position.
Definition at line 122 of file constant-velocity-helper.cc.
References m_paused, and NS_LOG_FUNCTION.
Referenced by ns3::RandomDirection2dMobilityModel::BeginPause(), ns3::RandomWaypointMobilityModel::DoInitializePrivate(), ns3::SteadyStateRandomWaypointMobilityModel::DoInitializePrivate(), and ns3::SteadyStateRandomWaypointMobilityModel::Start().
SetPosition()
void ns3::ConstantVelocityHelper::SetPosition (const Vector & position)
Set position vector.
Parameters
position Position vector
Definition at line 50 of file constant-velocity-helper.cc.
References m_lastUpdate, m_position, m_velocity, ns3::Simulator::Now(), and NS_LOG_FUNCTION.
Referenced by ns3::SteadyStateRandomWaypointMobilityModel::DoInitializePrivate(), ns3::RandomWalk2dOutdoorMobilityModel::DoSetPosition(), ns3::ConstantVelocityMobilityModel::DoSetPosition(), ns3::GaussMarkovMobilityModel::DoSetPosition(), ns3::RandomDirection2dMobilityModel::DoSetPosition(), ns3::RandomWalk2dMobilityModel::DoSetPosition(), ns3::RandomWaypointMobilityModel::DoSetPosition(), and ns3::SteadyStateRandomWaypointMobilityModel::DoSetPosition().
SetVelocity()
void ns3::ConstantVelocityHelper::SetVelocity (const Vector & vel)
Set new velocity vector.
Parameters
vel Velocity vector
Definition at line 72 of file constant-velocity-helper.cc.
References m_lastUpdate, m_velocity, ns3::Simulator::Now(), and NS_LOG_FUNCTION.
Referenced by ns3::RandomWalk2dOutdoorMobilityModel::AvoidBuilding(), ns3::RandomWaypointMobilityModel::BeginWalk(), ns3::SteadyStateRandomWaypointMobilityModel::BeginWalk(), ns3::RandomWalk2dOutdoorMobilityModel::DoInitializePrivate(), ns3::RandomWalk2dMobilityModel::DoInitializePrivate(), ns3::GaussMarkovMobilityModel::DoWalk(), ns3::RandomWalk2dOutdoorMobilityModel::Rebound(), ns3::RandomWalk2dMobilityModel::Rebound(), ns3::RandomDirection2dMobilityModel::SetDirectionAndSpeed(), ns3::ConstantVelocityMobilityModel::SetVelocity(), ns3::GaussMarkovMobilityModel::Start(), and ns3::SteadyStateRandomWaypointMobilityModel::SteadyStateBeginWalk().
Unpause()
void ns3::ConstantVelocityHelper::Unpause (void)
Resume mobility from current position at current velocity.
Definition at line 129 of file constant-velocity-helper.cc.
References m_paused, and NS_LOG_FUNCTION.
Referenced by ns3::GaussMarkovMobilityModel::GaussMarkovMobilityModel(), ns3::RandomWalk2dOutdoorMobilityModel::AvoidBuilding(), ns3::RandomWaypointMobilityModel::BeginWalk(), ns3::SteadyStateRandomWaypointMobilityModel::BeginWalk(), ns3::RandomWalk2dOutdoorMobilityModel::DoInitializePrivate(), ns3::RandomWalk2dMobilityModel::DoInitializePrivate(), ns3::GaussMarkovMobilityModel::DoWalk(), ns3::RandomWalk2dOutdoorMobilityModel::Rebound(), ns3::RandomWalk2dMobilityModel::Rebound(), ns3::RandomDirection2dMobilityModel::SetDirectionAndSpeed(), ns3::ConstantVelocityMobilityModel::SetVelocity(), ns3::GaussMarkovMobilityModel::Start(), and ns3::SteadyStateRandomWaypointMobilityModel::SteadyStateBeginWalk().
Update()
void ns3::ConstantVelocityHelper::Update (void) const
Update position, if not paused, from last position and time of last update.
Definition at line 80 of file constant-velocity-helper.cc.
References ns3::Time::GetSeconds(), m_lastUpdate, m_paused, m_position, m_velocity, ns3::Simulator::Now(), NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::RandomWalk2dOutdoorMobilityModel::AvoidBuilding(), ns3::RandomDirection2dMobilityModel::BeginPause(), ns3::RandomWaypointMobilityModel::BeginWalk(), ns3::SteadyStateRandomWaypointMobilityModel::BeginWalk(), ns3::ConstantVelocityMobilityModel::DoGetPosition(), ns3::GaussMarkovMobilityModel::DoGetPosition(), ns3::RandomWaypointMobilityModel::DoGetPosition(), ns3::SteadyStateRandomWaypointMobilityModel::DoGetPosition(), ns3::RandomWalk2dOutdoorMobilityModel::DoInitializePrivate(), ns3::RandomWalk2dMobilityModel::DoInitializePrivate(), ns3::RandomWaypointMobilityModel::DoInitializePrivate(), ns3::SteadyStateRandomWaypointMobilityModel::DoInitializePrivate(), ns3::ConstantVelocityMobilityModel::SetVelocity(), ns3::GaussMarkovMobilityModel::Start(), ns3::SteadyStateRandomWaypointMobilityModel::Start(), ns3::SteadyStateRandomWaypointMobilityModel::SteadyStateBeginWalk(), and UpdateWithBounds().
UpdateWithBounds() [1/2]
void ns3::ConstantVelocityHelper::UpdateWithBounds (const Box & bounds) const
Update position, if not paused, from last position and time of last update.
Parameters
bounds 3D bounding box for resulting position; object will not move outside the box
Definition at line 109 of file constant-velocity-helper.cc.
References m_position, max, min, NS_LOG_FUNCTION, Update(), ns3::Box::xMax, ns3::Box::xMin, ns3::Box::yMax, ns3::Box::yMin, ns3::Box::zMax, and ns3::Box::zMin.
UpdateWithBounds() [2/2]
void ns3::ConstantVelocityHelper::UpdateWithBounds (const Rectangle & rectangle) const
Update position, if not paused, from last position and time of last update.
Parameters
rectangle 2D bounding rectangle for resulting position; object will not move outside the rectangle
Definition at line 98 of file constant-velocity-helper.cc.
References m_position, max, min, NS_LOG_FUNCTION, Update(), ns3::Rectangle::xMax, ns3::Rectangle::xMin, ns3::Rectangle::yMax, and ns3::Rectangle::yMin.
Referenced by ns3::RandomWalk2dOutdoorMobilityModel::DoGetPosition(), ns3::RandomDirection2dMobilityModel::DoGetPosition(), ns3::RandomWalk2dMobilityModel::DoGetPosition(), ns3::GaussMarkovMobilityModel::DoWalk(), ns3::RandomWalk2dOutdoorMobilityModel::Rebound(), ns3::RandomWalk2dMobilityModel::Rebound(), ns3::RandomDirection2dMobilityModel::ResetDirectionAndSpeed(), and ns3::RandomDirection2dMobilityModel::SetDirectionAndSpeed().
Member Data Documentation
m_lastUpdate
Time ns3::ConstantVelocityHelper::m_lastUpdate mutable private
time of last update
Definition at line 97 of file constant-velocity-helper.h.
Referenced by SetPosition(), SetVelocity(), and Update().
m_paused
bool ns3::ConstantVelocityHelper::m_paused private
state variable for paused
Definition at line 100 of file constant-velocity-helper.h.
Referenced by GetVelocity(), Pause(), Unpause(), and Update().
m_position
Vector ns3::ConstantVelocityHelper::m_position mutable private
state variable for current position
Definition at line 98 of file constant-velocity-helper.h.
Referenced by GetCurrentPosition(), SetPosition(), Update(), and UpdateWithBounds().
m_velocity
Vector ns3::ConstantVelocityHelper::m_velocity private
state variable for velocity
Definition at line 99 of file constant-velocity-helper.h.
Referenced by GetVelocity(), SetPosition(), SetVelocity(), and Update().
The documentation for this class was generated from the following files:
src/mobility/model/constant-velocity-helper.h
src/mobility/model/constant-velocity-helper.cc