ns-3: Issue211Test Class Reference
Issue211Test Class Reference
Wifi Models » wifi module tests | Test suites
Test for issue 211 (https://gitlab.com/nsnam/ns-3-dev/-/issues/211)
Public Member Functions
Issue211Test ()
Constructor.
virtual ~Issue211Test ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CalcThroughput (Ptr< UdpServer > server)
Compute the average throughput since the last check-point.
Private Attributes
Time m_lastCheckPointTime
time of last check-point
uint64_t m_lastRxBytes
RX bytes at last check-point.
uint32_t m_payloadSize
payload size in bytes
std::vector< double > m_tputValues
throughput in sub-intervals
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test for issue 211 (https://gitlab.com/nsnam/ns-3-dev/-/issues/211)
This test aims to check that the transmission of data frames (under a Block Ack agreement) resumes after a period in which the connectivity between originator and recipient is interrupted (e.g., the station moves away and comes back). Issue 211 revealed that MSDUs with expired lifetime were not removed from the wifi MAC queue if the station had to transmit a Block Ack Request. If the connectivity was lost for enough time, the wifi MAC queue could become full of MSDUs with expired lifetime, thus preventing the traffic control layer to forward down new packets. At this point, the station gave up transmitting the Block Ack Request and did not request channel access anymore.
Definition at line 58 of file wifi-issue-211-test-suite.cc.
Constructor & Destructor Documentation
Issue211Test()
Issue211Test::Issue211Test ()
Constructor.
Definition at line 82 of file wifi-issue-211-test-suite.cc.
~Issue211Test()
Issue211Test::~Issue211Test () virtual
Definition at line 90 of file wifi-issue-211-test-suite.cc.
Member Function Documentation
CalcThroughput()
void Issue211Test::CalcThroughput (Ptr< UdpServer > server) private
Compute the average throughput since the last check-point.
Parameters
server the UDP server
Definition at line 95 of file wifi-issue-211-test-suite.cc.
References m_lastCheckPointTime, m_lastRxBytes, m_payloadSize, m_tputValues, and ns3::Now().
Referenced by DoRun().
DoRun()
void Issue211Test::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 105 of file wifi-issue-211-test-suite.cc.
References first::address, third::apDevices, CalcThroughput(), ns3::NodeContainer::Create(), ns3::ApplicationContainer::Get(), ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::Object::GetObject(), ns3::UdpServerHelper::Install(), ns3::UdpClientHelper::Install(), m_payloadSize, m_tputValues, third::mac, ns3::MilliSeconds(), third::mobility, NS_TEST_EXPECT_MSG_EQ, NS_TEST_EXPECT_MSG_GT, third::phy, port, ns3::Seconds(), ns3::UdpClientHelper::SetAttribute(), ns3::Config::SetDefault(), SetPosition(), first::stack, third::staDevices, ns3::ApplicationContainer::Start(), ns3::ApplicationContainer::Stop(), third::wifi, ns3::WIFI_STANDARD_80211n_5GHZ, and third::wifiApNode.
Member Data Documentation
m_lastCheckPointTime
Time Issue211Test::m_lastCheckPointTime private
time of last check-point
Definition at line 78 of file wifi-issue-211-test-suite.cc.
Referenced by CalcThroughput().
m_lastRxBytes
uint64_t Issue211Test::m_lastRxBytes private
RX bytes at last check-point.
Definition at line 77 of file wifi-issue-211-test-suite.cc.
Referenced by CalcThroughput().
m_payloadSize
uint32_t Issue211Test::m_payloadSize private
payload size in bytes
Definition at line 79 of file wifi-issue-211-test-suite.cc.
Referenced by CalcThroughput(), and DoRun().
m_tputValues
std::vector<double> Issue211Test::m_tputValues private
throughput in sub-intervals
Definition at line 76 of file wifi-issue-211-test-suite.cc.
Referenced by CalcThroughput(), and DoRun().
The documentation for this class was generated from the following file:
src/test/ns3wifi/wifi-issue-211-test-suite.cc