ns-3: ns3::InetSocketAddress Class Reference
ns3::InetSocketAddress Class Reference
Network » Address
an Inet address class
#include "inet-socket-address.h"
Public Member Functions
InetSocketAddress (const char *ipv4)
InetSocketAddress (const char *ipv4, uint16_t port)
InetSocketAddress (Ipv4Address ipv4)
InetSocketAddress (Ipv4Address ipv4, uint16_t port)
InetSocketAddress (uint16_t port)
Ipv4Address GetIpv4 (void) const
uint16_t GetPort (void) const
uint8_t GetTos (void) const
operator Address () const
void SetIpv4 (Ipv4Address address)
void SetPort (uint16_t port)
void SetTos (uint8_t tos)
Static Public Member Functions
static InetSocketAddress ConvertFrom (const Address &address)
Returns an InetSocketAddress which corresponds to the input Address.
static bool IsMatchingType (const Address &address)
Private Member Functions
Address ConvertTo (void) const
Convert to an Address type.
Static Private Member Functions
static uint8_t GetType (void)
Get the underlying address type (automatically assigned).
Private Attributes
Ipv4Address m_ipv4
the IPv4 address
uint16_t m_port
the port
uint8_t m_tos
the ToS
Detailed Description
an Inet address class
This class is similar to inet_sockaddr in the BSD socket API. i.e., this class holds an Ipv4Address and a port number to form an ipv4 transport endpoint.
Definition at line 40 of file inet-socket-address.h.
Constructor & Destructor Documentation
InetSocketAddress() [1/5]
ns3::InetSocketAddress::InetSocketAddress (Ipv4Address ipv4, uint16_t port)
Parameters
ipv4 the ipv4 address
port the port number
Definition at line 29 of file inet-socket-address.cc.
References NS_LOG_FUNCTION, and port.
InetSocketAddress() [2/5]
ns3::InetSocketAddress::InetSocketAddress (Ipv4Address ipv4)
Parameters
ipv4 the ipv4 address
The port number is set to zero by default.
Definition at line 36 of file inet-socket-address.cc.
References NS_LOG_FUNCTION.
InetSocketAddress() [3/5]
ns3::InetSocketAddress::InetSocketAddress (uint16_t port)
Parameters
port the port number
The ipv4 address is set to the "Any" address by default.
Definition at line 57 of file inet-socket-address.cc.
References NS_LOG_FUNCTION, and port.
InetSocketAddress() [4/5]
ns3::InetSocketAddress::InetSocketAddress (const char * ipv4, uint16_t port)
Parameters
ipv4 string which represents an ipv4 address
port the port number
Definition at line 43 of file inet-socket-address.cc.
References NS_LOG_FUNCTION, and port.
InetSocketAddress() [5/5]
ns3::InetSocketAddress::InetSocketAddress (const char * ipv4)
Parameters
ipv4 string which represents an ipv4 address
The port number is set to zero.
Definition at line 50 of file inet-socket-address.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
ConvertFrom()
InetSocketAddress ns3::InetSocketAddress::ConvertFrom (const Address & address) static
Returns an InetSocketAddress which corresponds to the input Address.
Parameters
address the Address instance to convert from.
Returns
an InetSocketAddress
Definition at line 126 of file inet-socket-address.cc.
References first::address, ns3::Ipv4Address::Deserialize(), GetType(), NS_ASSERT, NS_LOG_FUNCTION, port, and SetTos().
Referenced by ns3::DhcpClient::AcceptAck(), ns3::Ipv4RawSocketImpl::Bind(), ns3::NscTcpSocketImpl::Bind(), ns3::TcpSocketBase::Bind(), ns3::UdpSocketImpl::Bind(), ns3::TcpSocketBase::CompleteFork(), ns3::Ipv4RawSocketImpl::Connect(), ns3::NscTcpSocketImpl::Connect(), ns3::TcpSocketBase::Connect(), ns3::UdpSocketImpl::Connect(), dstSocketRecv(), ns3::aodv::LoopbackTestCase::EchoData(), ns3::SinkTracer::FormatAddress(), ns3::PacketSink::HandleRead(), ns3::UdpEchoClient::HandleRead(), ns3::UdpEchoServer::HandleRead(), ns3::UdpServer::HandleRead(), ns3::addressUtils::IsMulticast(), ns3::DhcpServer::NetHandler(), ns3::PacketSink::AddressHash::operator()(), PrintReceivedPacket(), ns3::TcpSocketBase::ProcessSynRcvd(), ns3::V4Ping::Receive(), ns3::V4TraceRoute::Receive(), ns3::Rip::Receive(), ns3::olsr::Bug780Test::Receive(), ns3::ThreeGppHttpClient::ReceivedDataCallback(), ns3::ThreeGppHttpServer::ReceivedDataCallback(), ns3::BsmApplication::ReceiveWavePacket(), ns3::aodv::RoutingProtocol::RecvAodv(), ns3::dsdv::RoutingProtocol::RecvDsdv(), ns3::olsr::RoutingProtocol::RecvOlsr(), ns3::UdpEchoClient::Send(), ns3::OnOffApplication::SendPacket(), ns3::TcpL4Protocol::SendPacket(), ns3::UdpSocketImpl::SendTo(), ns3::Ipv4RawSocketImpl::SendTo(), and srcSocketRecv().
ConvertTo()
Address ns3::InetSocketAddress::ConvertTo (void) const private
Convert to an Address type.
Returns
the Address corresponding to this object.
Definition at line 115 of file inet-socket-address.cc.
References GetType(), m_ipv4, m_port, m_tos, NS_LOG_FUNCTION, and ns3::Ipv4Address::Serialize().
GetIpv4()
Ipv4Address ns3::InetSocketAddress::GetIpv4 (void) const
Returns
the ipv4 address
Definition at line 71 of file inet-socket-address.cc.
References m_ipv4, and NS_LOG_FUNCTION.
Referenced by ns3::DhcpClient::AcceptAck(), ns3::Ipv4RawSocketImpl::Bind(), ns3::NscTcpSocketImpl::Bind(), ns3::TcpSocketBase::Bind(), ns3::UdpSocketImpl::Bind(), ns3::Ipv4RawSocketImpl::Connect(), ns3::NscTcpSocketImpl::Connect(), ns3::TcpSocketBase::Connect(), ns3::UdpSocketImpl::Connect(), ns3::aodv::LoopbackTestCase::EchoData(), ns3::SinkTracer::FormatAddress(), ns3::PacketSink::HandleRead(), ns3::UdpEchoClient::HandleRead(), ns3::UdpEchoServer::HandleRead(), ns3::UdpServer::HandleRead(), ns3::addressUtils::IsMulticast(), ns3::PacketSink::AddressHash::operator()(), PrintReceivedPacket(), PrintReceivedRoutingPacket(), ns3::V4Ping::Receive(), ns3::V4TraceRoute::Receive(), ns3::Rip::Receive(), ns3::ThreeGppHttpClient::ReceivedDataCallback(), ns3::ThreeGppHttpServer::ReceivedDataCallback(), ns3::BsmApplication::ReceiveWavePacket(), ns3::aodv::RoutingProtocol::RecvAodv(), ns3::dsdv::RoutingProtocol::RecvDsdv(), ns3::olsr::RoutingProtocol::RecvOlsr(), ns3::DhcpServer::SendAck(), ns3::DhcpServer::SendOffer(), ns3::OnOffApplication::SendPacket(), ns3::TcpL4Protocol::SendPacket(), ns3::UdpSocketImpl::SendTo(), ns3::Ipv4RawSocketImpl::SendTo(), and srcSocketRecv().
GetPort()
uint16_t ns3::InetSocketAddress::GetPort (void) const
Returns
the port number
Definition at line 65 of file inet-socket-address.cc.
References m_port, and NS_LOG_FUNCTION.
Referenced by ns3::NscTcpSocketImpl::Bind(), ns3::TcpSocketBase::Bind(), ns3::UdpSocketImpl::Bind(), ns3::NscTcpSocketImpl::Connect(), ns3::TcpSocketBase::Connect(), ns3::UdpSocketImpl::Connect(), ns3::SinkTracer::FormatAddress(), ns3::PacketSink::HandleRead(), ns3::UdpEchoClient::HandleRead(), ns3::UdpEchoServer::HandleRead(), PrintReceivedPacket(), ns3::V4Ping::Receive(), ns3::V4TraceRoute::Receive(), ns3::Rip::Receive(), ns3::olsr::Bug780Test::Receive(), ns3::ThreeGppHttpClient::ReceivedDataCallback(), ns3::ThreeGppHttpServer::ReceivedDataCallback(), ns3::olsr::RoutingProtocol::RecvOlsr(), ns3::DhcpServer::SendAck(), ns3::DhcpServer::SendOffer(), ns3::OnOffApplication::SendPacket(), and ns3::UdpSocketImpl::SendTo().
GetTos()
uint8_t ns3::InetSocketAddress::GetTos (void) const
Returns
the ToS
Definition at line 77 of file inet-socket-address.cc.
References m_tos, and NS_LOG_FUNCTION.
Referenced by ns3::TcpSocketBase::Bind(), ns3::UdpSocketImpl::Bind(), ns3::Ipv4RawSocketImpl::Connect(), ns3::TcpSocketBase::Connect(), ns3::UdpSocketImpl::Connect(), ns3::UdpSocketImpl::SendTo(), and ns3::Ipv4RawSocketImpl::SendTo().
GetType()
uint8_t ns3::InetSocketAddress::GetType (void) static private
Get the underlying address type (automatically assigned).
Returns
the address type
Definition at line 140 of file inet-socket-address.cc.
References NS_LOG_FUNCTION_NOARGS, and ns3::Address::Register().
Referenced by ConvertFrom(), ConvertTo(), and IsMatchingType().
IsMatchingType()
bool ns3::InetSocketAddress::IsMatchingType (const Address & address) static
Parameters
address address to test
Returns
true if the address matches, false otherwise.
Definition at line 103 of file inet-socket-address.cc.
References first::address, GetType(), and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4RawSocketImpl::Bind(), ns3::NscTcpSocketImpl::Bind(), ns3::TcpSocketBase::Bind(), ns3::UdpSocketImpl::Bind(), ns3::TcpSocketBase::CompleteFork(), ns3::Ipv4RawSocketImpl::Connect(), ns3::TcpSocketBase::Connect(), ns3::UdpSocketImpl::Connect(), ns3::SinkTracer::FormatAddress(), ns3::PacketSink::HandleRead(), ns3::UdpEchoClient::HandleRead(), ns3::UdpEchoServer::HandleRead(), ns3::UdpServer::HandleRead(), ns3::addressUtils::IsMulticast(), ns3::PacketSink::AddressHash::operator()(), ns3::V4Ping::Receive(), ns3::V4TraceRoute::Receive(), ns3::olsr::Bug780Test::Receive(), ns3::ThreeGppHttpClient::ReceivedDataCallback(), ns3::ThreeGppHttpServer::ReceivedDataCallback(), ns3::BsmApplication::ReceiveWavePacket(), ns3::UdpEchoClient::Send(), ns3::OnOffApplication::SendPacket(), ns3::TcpL4Protocol::SendPacket(), ns3::UdpSocketImpl::SendTo(), ns3::Ipv4RawSocketImpl::SendTo(), ns3::BulkSendApplication::StartApplication(), ns3::OnOffApplication::StartApplication(), ns3::UdpClient::StartApplication(), ns3::UdpEchoClient::StartApplication(), and ns3::UdpTraceClient::StartApplication().
operator Address()
ns3::InetSocketAddress::operator Address () const
Returns
an Address instance which represents this InetSocketAddress instance.
Definition at line 109 of file inet-socket-address.cc.
SetIpv4()
void ns3::InetSocketAddress::SetIpv4 (Ipv4Address address)
Parameters
address the new ipv4 address
Definition at line 90 of file inet-socket-address.cc.
References first::address, m_ipv4, and NS_LOG_FUNCTION.
Referenced by Ipv4FragmentationTest::SendClient().
SetPort()
void ns3::InetSocketAddress::SetPort (uint16_t port)
Parameters
port the new port number.
Definition at line 84 of file inet-socket-address.cc.
References m_port, NS_LOG_FUNCTION, and port.
Referenced by Ipv4RawSocketImplTest::DoRun().
SetTos()
void ns3::InetSocketAddress::SetTos (uint8_t tos)
Parameters
tos the new ToS.
Definition at line 96 of file inet-socket-address.cc.
References m_tos, and NS_LOG_FUNCTION.
Referenced by ConvertFrom(), UdpSocketImplTest::DoRun(), WifiAcMappingTest::DoRun(), ns3::UdpSocketImpl::GetPeerName(), and ns3::Ipv4RawSocketImpl::Send().
Member Data Documentation
m_ipv4
Ipv4Address ns3::InetSocketAddress::m_ipv4 private
the IPv4 address
Definition at line 130 of file inet-socket-address.h.
Referenced by ConvertTo(), GetIpv4(), and SetIpv4().
m_port
uint16_t ns3::InetSocketAddress::m_port private
the port
Definition at line 131 of file inet-socket-address.h.
Referenced by ConvertTo(), GetPort(), and SetPort().
m_tos
uint8_t ns3::InetSocketAddress::m_tos private
the ToS
Definition at line 132 of file inet-socket-address.h.
Referenced by ConvertTo(), GetTos(), and SetTos().
The documentation for this class was generated from the following files:
src/network/utils/inet-socket-address.h
src/network/utils/inet-socket-address.cc