ns-3: ns3::Ipv4L3Protocol::Fragments Class Reference
ns3::Ipv4L3Protocol::Fragments Class Reference
A Set of Fragment belonging to the same packet (src, dst, identification and proto)
Public Member Functions
Fragments ()
Constructor.
~Fragments ()
Destructor.
void AddFragment (Ptr< Packet > fragment, uint16_t fragmentOffset, bool moreFragment)
Add a fragment.
Ptr< Packet > GetPacket () const
Get the entire packet.
Ptr< Packet > GetPartialPacket () const
Get the complete part of the packet.
FragmentsTimeoutsListI_t GetTimeoutIter ()
Get the Timeout iterator.
bool IsEntire () const
If all fragments have been added.
void SetTimeoutIter (FragmentsTimeoutsListI_t iter)
Set the Timeout iterator.
Public Member Functions inherited from ns3::SimpleRefCount< Fragments >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
std::list< std::pair< Ptr< Packet >, uint16_t > > m_fragments
The current fragments.
bool m_moreFragment
True if other fragments will be sent.
FragmentsTimeoutsListI_t m_timeoutIter
Timeout iterator to "event" handler.
Detailed Description
A Set of Fragment belonging to the same packet (src, dst, identification and proto)
Definition at line 537 of file ipv4-l3-protocol.h.
Constructor & Destructor Documentation
Fragments()
ns3::Ipv4L3Protocol::Fragments::Fragments ()
Constructor.
Definition at line 1565 of file ipv4-l3-protocol.cc.
References NS_LOG_FUNCTION.
~Fragments()
ns3::Ipv4L3Protocol::Fragments::~Fragments ()
Destructor.
Definition at line 1571 of file ipv4-l3-protocol.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddFragment()
void ns3::Ipv4L3Protocol::Fragments::AddFragment (Ptr< Packet > fragment, uint16_t fragmentOffset, bool moreFragment)
Add a fragment.
Parameters
fragment the fragment
fragmentOffset the offset of the fragment
moreFragment the bit "More Fragment"
Definition at line 1577 of file ipv4-l3-protocol.cc.
References ns3::Ipv4L3Protocol::m_fragments, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4L3Protocol::ProcessFragment().
GetPacket()
Ptr< Packet > ns3::Ipv4L3Protocol::Fragments::GetPacket () const
Get the entire packet.
Returns
the entire packet
Definition at line 1630 of file ipv4-l3-protocol.cc.
References ns3::Packet::AddAtEnd(), ns3::Packet::Copy(), ns3::Packet::CreateFragment(), ns3::Packet::GetSize(), ns3::Ipv4L3Protocol::m_fragments, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by ns3::Ipv4L3Protocol::ProcessFragment().
GetPartialPacket()
Ptr< Packet > ns3::Ipv4L3Protocol::Fragments::GetPartialPacket () const
Get the complete part of the packet.
Returns
the part we have comeplete
Definition at line 1668 of file ipv4-l3-protocol.cc.
References ns3::Packet::AddAtEnd(), ns3::Packet::CreateFragment(), ns3::Packet::GetSize(), ns3::Ipv4L3Protocol::m_fragments, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
GetTimeoutIter()
Ipv4L3Protocol::FragmentsTimeoutsListI_t ns3::Ipv4L3Protocol::Fragments::GetTimeoutIter ()
Get the Timeout iterator.
Returns
The iterator.
Definition at line 1710 of file ipv4-l3-protocol.cc.
Referenced by ns3::Ipv4L3Protocol::ProcessFragment().
IsEntire()
bool ns3::Ipv4L3Protocol::Fragments::IsEntire () const
If all fragments have been added.
Returns
true if the packet is entire
Definition at line 1600 of file ipv4-l3-protocol.cc.
References list, ns3::Ipv4L3Protocol::m_fragments, max, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by ns3::Ipv4L3Protocol::ProcessFragment().
SetTimeoutIter()
void ns3::Ipv4L3Protocol::Fragments::SetTimeoutIter (FragmentsTimeoutsListI_t iter)
Set the Timeout iterator.
Parameters
iter The iterator.
Definition at line 1703 of file ipv4-l3-protocol.cc.
Referenced by ns3::Ipv4L3Protocol::ProcessFragment().
Member Data Documentation
m_fragments
std::list<std::pair<Ptr<Packet>, uint16_t> > ns3::Ipv4L3Protocol::Fragments::m_fragments private
The current fragments.
Definition at line 597 of file ipv4-l3-protocol.h.
m_moreFragment
bool ns3::Ipv4L3Protocol::Fragments::m_moreFragment private
True if other fragments will be sent.
Definition at line 592 of file ipv4-l3-protocol.h.
m_timeoutIter
FragmentsTimeoutsListI_t ns3::Ipv4L3Protocol::Fragments::m_timeoutIter private
Timeout iterator to "event" handler.
Definition at line 602 of file ipv4-l3-protocol.h.
The documentation for this class was generated from the following files:
src/internet/model/ipv4-l3-protocol.h
src/internet/model/ipv4-l3-protocol.cc