ns-3: ns3::DhcpClient Class Reference
ns3::DhcpClient Class Reference
Internet Applications » DHCPv4 Client and Server
Implements the functionality of a DHCP client.
#include "dhcp-client.h"
Public Member Functions
DhcpClient ()
DhcpClient (Ptr< NetDevice > netDevice)
Constructor.
virtual ~DhcpClient ()
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Ptr< NetDevice > GetDhcpClientNetDevice (void)
Get the the NetDevice DHCP should work on.
Ipv4Address GetDhcpServer (void)
Get the IPv4Address of current DHCP server.
void SetDhcpClientNetDevice (Ptr< NetDevice > netDevice)
Set the NetDevice DHCP should work on.
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Application
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
enum States { WAIT_OFFER = 1 , REFRESH_LEASE = 2 , WAIT_ACK = 9 }
client states
Private Member Functions
void AcceptAck (DhcpHeader header, Address from)
Receives the DHCP ACK and configures IP address of the client.
void Boot (void)
Sends DHCP DISCOVER and changes the client state to WAIT_OFFER.
void LinkStateHandler (void)
Handles changes in LinkState.
void NetHandler (Ptr< Socket > socket)
Handles incoming packets from the network.
void OfferHandler (DhcpHeader header)
Stores DHCP offers in m_offerList.
void RemoveAndStart ()
Remove the current DHCP information and restart the process.
void Request (void)
Sends the DHCP REQUEST message and changes the client state to WAIT_ACK.
void Select (void)
Selects an OFFER from m_offerList.
virtual void StartApplication (void)
Application specific startup code.
virtual void StopApplication (void)
Application specific shutdown code.
Private Attributes
Address m_chaddr
chaddr of the interface (stored as an Address for convenience).
Time m_collect
Time for which client should collect offers.
EventId m_collectEvent
Offer collection event.
Ptr< NetDevice > m_device
NetDevice pointer.
EventId m_discoverEvent
Message retransmission event.
TracedCallback< const Ipv4Address & > m_expiry
Trace of lease expire.
bool m_firstBoot
First boot (used to add the link state change callback)
Ipv4Address m_gateway
Address of the gateway.
Time m_lease
Store the lease time of address.
Ipv4Address m_myAddress
Address assigned to the client.
Ipv4Mask m_myMask
Mask of the address assigned.
TracedCallback< const Ipv4Address & > m_newLease
Trace of new lease.
Time m_nextoffer
Time to try the next offer (if request gets no reply)
EventId m_nextOfferEvent
Message next offer event.
bool m_offered
Specify if the client has got any offer.
Ipv4Address m_offeredAddress
Address offered to the client.
std::list< DhcpHeader > m_offerList
Stores all the offers given to the client.
Ptr< RandomVariableStream > m_ran
Uniform random variable for transaction ID.
Time m_rebind
Store the rebind time of address.
EventId m_rebindEvent
Message rebind event.
EventId m_refreshEvent
Message refresh event.
Ipv4Address m_remoteAddress
Initially set to 255.255.255.255 to start DHCP.
Time m_renew
Store the renew time of address.
EventId m_requestEvent
Address refresh event.
Time m_rtrs
Defining the time for retransmission.
Ipv4Address m_server
Address of the DHCP server.
Ptr< Socket > m_socket
Socket for remote communication.
uint8_t m_state
State of the DHCP client.
EventId m_timeout
The timeout period.
uint32_t m_tran
Stores the current transaction number to be used.
Static Private Attributes
static const int DHCP_PEER_PORT = 67
DHCP server port.
Additional Inherited Members
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implements the functionality of a DHCP client.
Config Paths
ns3::DhcpClient is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/ApplicationList/[i]/$ns3::DhcpClient"
Attributes
RTRS: Time for retransmission of Discover message
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +5e+09ns
Flags: construct write read
Collect: Time for which offer collection starts
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +5e+09ns
Flags: construct write read
ReRequest: Time after which request will be resent to next server
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+10ns
Flags: construct write read
Transactions: The possible value of transaction numbers
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::RandomVariableStream>
Initial value: ns3::UniformRandomVariable[Min=0.0|Max=1000000.0]
Flags: construct write read
Attributes defined in parent class ns3::Application
StartTime: Time at which the application will start
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
StopTime: Time at which the application will stop
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
TraceSources
NewLease: Get a NewLease
Callback signature: ns3::Ipv4Address::TracedCallback
ExpireLease: A lease expires
Callback signature: ns3::Ipv4Address::TracedCallback
Size of this type is 512 bytes (on a 64-bit architecture).
Definition at line 45 of file dhcp-client.h.
Member Enumeration Documentation
States
enum ns3::DhcpClient::States private
client states
Enumerator
WAIT_OFFER
State of a client that waits for the offer.
REFRESH_LEASE
State of a client that needs to refresh the lease.
WAIT_ACK
State of a client that waits for acknowledgment.
Definition at line 97 of file dhcp-client.h.
Constructor & Destructor Documentation
DhcpClient() [1/2]
ns3::DhcpClient::DhcpClient ()
Definition at line 76 of file dhcp-client.cc.
References ns3::Ipv4Address::GetAny(), m_collectEvent, m_discoverEvent, m_firstBoot, m_nextOfferEvent, m_rebindEvent, m_refreshEvent, m_requestEvent, m_server, m_socket, m_timeout, and NS_LOG_FUNCTION.
~DhcpClient()
ns3::DhcpClient::~DhcpClient () virtual
Definition at line 107 of file dhcp-client.cc.
References NS_LOG_FUNCTION.
DhcpClient() [2/2]
ns3::DhcpClient::DhcpClient (Ptr< NetDevice > netDevice)
Constructor.
Parameters
netDevice the NetDevice DHCP should work on
Definition at line 91 of file dhcp-client.cc.
References ns3::Ipv4Address::GetAny(), m_collectEvent, m_device, m_discoverEvent, m_firstBoot, m_nextOfferEvent, m_rebindEvent, m_refreshEvent, m_requestEvent, m_server, m_socket, m_timeout, and NS_LOG_FUNCTION.
Member Function Documentation
AcceptAck()
void ns3::DhcpClient::AcceptAck (DhcpHeader header, Address from) private
Receives the DHCP ACK and configures IP address of the client.
It also triggers the timeout, renew and rebind events.
Parameters
header DhcpHeader of the DHCP ACK message
from Address of DHCP server that sent the DHCP ACK
Definition at line 435 of file dhcp-client.cc.
References ns3::EventId::Cancel(), ns3::Socket::Connect(), ns3::InetSocketAddress::ConvertFrom(), DHCP_PEER_PORT, ns3::InetSocketAddress::GetIpv4(), ns3::Application::GetNode(), ns3::Object::GetObject(), ns3::Ipv4StaticRoutingHelper::GetStaticRouting(), m_device, m_expiry, m_gateway, m_lease, m_myAddress, m_myMask, m_newLease, m_offeredAddress, m_offerList, m_rebind, m_rebindEvent, m_refreshEvent, m_remoteAddress, m_renew, m_socket, m_state, m_timeout, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, REFRESH_LEASE, RemoveAndStart(), Request(), and ns3::Simulator::Schedule().
Referenced by NetHandler().
AssignStreams()
int64_t ns3::DhcpClient::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream First stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 148 of file dhcp-client.cc.
References m_ran, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
Boot()
void ns3::DhcpClient::Boot (void) private
Sends DHCP DISCOVER and changes the client state to WAIT_OFFER.
Definition at line 325 of file dhcp-client.cc.
References ns3::Packet::AddHeader(), DHCP_PEER_PORT, ns3::DhcpHeader::DHCPDISCOVER, ns3::RandomVariableStream::GetValue(), m_chaddr, m_discoverEvent, m_offered, m_ran, m_remoteAddress, m_rtrs, m_socket, m_state, m_tran, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::DhcpHeader::ResetOpt(), ns3::Simulator::Schedule(), ns3::Socket::SendTo(), ns3::DhcpHeader::SetChaddr(), ns3::DhcpHeader::SetTime(), ns3::DhcpHeader::SetTran(), ns3::DhcpHeader::SetType(), and WAIT_OFFER.
Referenced by NetHandler(), Select(), and StartApplication().
DoDispose()
void ns3::DhcpClient::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Application.
Definition at line 129 of file dhcp-client.cc.
References ns3::EventId::Cancel(), ns3::Application::DoDispose(), m_collectEvent, m_device, m_discoverEvent, m_nextOfferEvent, m_rebindEvent, m_refreshEvent, m_requestEvent, m_timeout, and NS_LOG_FUNCTION.
GetDhcpClientNetDevice()
Ptr< NetDevice > ns3::DhcpClient::GetDhcpClientNetDevice (void)
Get the the NetDevice DHCP should work on.
Returns
the NetDevice DHCP should work on
Definition at line 112 of file dhcp-client.cc.
References m_device.
GetDhcpServer()
Ipv4Address ns3::DhcpClient::GetDhcpServer (void)
Get the IPv4Address of current DHCP server.
Returns
Ipv4Address of current DHCP server
Definition at line 123 of file dhcp-client.cc.
References m_server.
GetTypeId()
TypeId ns3::DhcpClient::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 42 of file dhcp-client.cc.
References m_collect, m_expiry, m_newLease, m_nextoffer, m_ran, m_rtrs, ns3::MakePointerAccessor(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::Seconds(), and ns3::TypeId::SetParent().
Referenced by ns3::DhcpHelper::DhcpHelper().
LinkStateHandler()
void ns3::DhcpClient::LinkStateHandler (void) private
Handles changes in LinkState.
Definition at line 239 of file dhcp-client.cc.
References ns3::EventId::Cancel(), ns3::Application::GetNode(), ns3::Object::GetObject(), ns3::Ipv4StaticRoutingHelper::GetStaticRouting(), m_collectEvent, m_device, m_discoverEvent, m_gateway, m_myAddress, m_nextOfferEvent, m_rebindEvent, m_refreshEvent, m_requestEvent, m_socket, m_state, m_timeout, ns3::MakeCallback(), ns3::MakeNullCallback(), NetHandler(), ns3::Simulator::Now(), NS_LOG_FUNCTION, NS_LOG_INFO, ns3::Time::S, ns3::Socket::SetRecvCallback(), and StartApplication().
Referenced by StartApplication().
NetHandler()
void ns3::DhcpClient::NetHandler (Ptr< Socket > socket) private
Handles incoming packets from the network.
Parameters
socket Socket bound to port 68 of the DHCP client
Definition at line 294 of file dhcp-client.cc.
References AcceptAck(), Boot(), ns3::EventId::Cancel(), ns3::DhcpHeader::DHCPACK, ns3::DhcpHeader::DHCPNACK, ns3::DhcpHeader::DHCPOFFER, ns3::DhcpHeader::GetChaddr(), ns3::DhcpHeader::GetType(), m_chaddr, m_nextOfferEvent, m_socket, m_state, NS_LOG_FUNCTION, OfferHandler(), ns3::Socket::RecvFrom(), ns3::Packet::RemoveHeader(), WAIT_ACK, and WAIT_OFFER.
Referenced by LinkStateHandler(), and StartApplication().
OfferHandler()
void ns3::DhcpClient::OfferHandler (DhcpHeader header) private
Stores DHCP offers in m_offerList.
Parameters
header DhcpHeader of the DHCP OFFER message
Definition at line 353 of file dhcp-client.cc.
References ns3::EventId::Cancel(), m_collect, m_collectEvent, m_discoverEvent, m_offered, m_offerList, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), and Select().
Referenced by NetHandler().
RemoveAndStart()
void ns3::DhcpClient::RemoveAndStart () private
Remove the current DHCP information and restart the process.
Definition at line 493 of file dhcp-client.cc.
References ns3::EventId::Cancel(), ns3::Application::GetNode(), ns3::Object::GetObject(), ns3::Ipv4StaticRoutingHelper::GetStaticRouting(), m_device, m_expiry, m_gateway, m_myAddress, m_nextOfferEvent, m_rebindEvent, m_refreshEvent, m_timeout, NS_LOG_FUNCTION, and StartApplication().
Referenced by AcceptAck().
Request()
void ns3::DhcpClient::Request (void) private
Sends the DHCP REQUEST message and changes the client state to WAIT_ACK.
Definition at line 390 of file dhcp-client.cc.
References ns3::Packet::AddHeader(), DHCP_PEER_PORT, ns3::DhcpHeader::DHCPREQ, ns3::Ipv4Address::Get(), ns3::RandomVariableStream::GetValue(), m_chaddr, m_myAddress, m_nextoffer, m_nextOfferEvent, m_offeredAddress, m_ran, m_remoteAddress, m_socket, m_state, m_tran, NS_LOG_FUNCTION, NS_LOG_INFO, REFRESH_LEASE, ns3::DhcpHeader::ResetOpt(), ns3::Simulator::Schedule(), Select(), ns3::Socket::SendTo(), ns3::DhcpHeader::SetChaddr(), ns3::DhcpHeader::SetReq(), ns3::DhcpHeader::SetTime(), ns3::DhcpHeader::SetTran(), ns3::DhcpHeader::SetType(), and WAIT_ACK.
Referenced by AcceptAck(), and Select().
Select()
void ns3::DhcpClient::Select (void) private
Selects an OFFER from m_offerList.
Definition at line 366 of file dhcp-client.cc.
References Boot(), ns3::DhcpHeader::GetDhcps(), ns3::DhcpHeader::GetLease(), ns3::DhcpHeader::GetMask(), ns3::DhcpHeader::GetRebind(), ns3::DhcpHeader::GetRenew(), ns3::DhcpHeader::GetRouter(), ns3::DhcpHeader::GetYiaddr(), m_gateway, m_lease, m_myMask, m_offered, m_offeredAddress, m_offerList, m_rebind, m_renew, m_server, NS_LOG_FUNCTION, Request(), and ns3::Seconds().
Referenced by OfferHandler(), and Request().
SetDhcpClientNetDevice()
void ns3::DhcpClient::SetDhcpClientNetDevice (Ptr< NetDevice > netDevice)
Set the NetDevice DHCP should work on.
Parameters
netDevice the NetDevice DHCP should work on
Definition at line 118 of file dhcp-client.cc.
References m_device.
StartApplication()
void ns3::DhcpClient::StartApplication (void) private virtual
Application specific startup code.
The StartApplication method is called at the start time specified by Start This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 156 of file dhcp-client.cc.
References ns3::Socket::Bind(), ns3::Socket::BindToNetDevice(), Boot(), ns3::Address::CopyFrom(), ns3::Address::CopyTo(), ns3::Socket::CreateSocket(), ns3::Ipv4Address::GetAny(), ns3::Application::GetNode(), ns3::Object::GetObject(), LinkStateHandler(), ns3::TypeId::LookupByName(), m_chaddr, m_device, m_firstBoot, m_gateway, m_myAddress, m_remoteAddress, m_socket, ns3::MakeCallback(), ns3::Address::MAX_SIZE, NetHandler(), NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::Socket::SetAllowBroadcast(), and ns3::Socket::SetRecvCallback().
Referenced by LinkStateHandler(), and RemoveAndStart().
StopApplication()
void ns3::DhcpClient::StopApplication (void) private virtual
Application specific shutdown code.
The StopApplication method is called at the stop time specified by Stop This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 210 of file dhcp-client.cc.
References ns3::EventId::Cancel(), ns3::Socket::Close(), ns3::Application::GetNode(), ns3::Object::GetObject(), m_collectEvent, m_device, m_discoverEvent, m_myAddress, m_nextOfferEvent, m_rebindEvent, m_refreshEvent, m_requestEvent, m_socket, m_timeout, ns3::MakeNullCallback(), NS_LOG_FUNCTION, and ns3::Socket::SetRecvCallback().
Member Data Documentation
DHCP_PEER_PORT
const int ns3::DhcpClient::DHCP_PEER_PORT = 67 static private
DHCP server port.
Definition at line 104 of file dhcp-client.h.
Referenced by AcceptAck(), Boot(), and Request().
m_chaddr
Address ns3::DhcpClient::m_chaddr private
chaddr of the interface (stored as an Address for convenience).
Definition at line 168 of file dhcp-client.h.
Referenced by Boot(), NetHandler(), Request(), and StartApplication().
m_collect
Time ns3::DhcpClient::m_collect private
Time for which client should collect offers.
Definition at line 185 of file dhcp-client.h.
Referenced by GetTypeId(), and OfferHandler().
m_collectEvent
EventId ns3::DhcpClient::m_collectEvent private
Offer collection event.
Definition at line 178 of file dhcp-client.h.
Referenced by DhcpClient(), DoDispose(), LinkStateHandler(), OfferHandler(), and StopApplication().
m_device
Ptr<NetDevice> ns3::DhcpClient::m_device private
NetDevice pointer.
Definition at line 163 of file dhcp-client.h.
Referenced by DhcpClient(), AcceptAck(), DoDispose(), GetDhcpClientNetDevice(), LinkStateHandler(), RemoveAndStart(), SetDhcpClientNetDevice(), StartApplication(), and StopApplication().
m_discoverEvent
EventId ns3::DhcpClient::m_discoverEvent private
Message retransmission event.
Definition at line 173 of file dhcp-client.h.
Referenced by DhcpClient(), Boot(), DoDispose(), LinkStateHandler(), OfferHandler(), and StopApplication().
m_expiry
TracedCallback<const Ipv4Address&> ns3::DhcpClient::m_expiry private
Trace of lease expire.
Definition at line 190 of file dhcp-client.h.
Referenced by AcceptAck(), GetTypeId(), and RemoveAndStart().
m_firstBoot
bool ns3::DhcpClient::m_firstBoot private
First boot (used to add the link state change callback)
Definition at line 162 of file dhcp-client.h.
Referenced by DhcpClient(), and StartApplication().
m_gateway
Ipv4Address ns3::DhcpClient::m_gateway private
Address of the gateway.
Definition at line 171 of file dhcp-client.h.
Referenced by AcceptAck(), LinkStateHandler(), RemoveAndStart(), Select(), and StartApplication().
m_lease
Time ns3::DhcpClient::m_lease private
Store the lease time of address.
Definition at line 179 of file dhcp-client.h.
Referenced by AcceptAck(), and Select().
m_myAddress
Ipv4Address ns3::DhcpClient::m_myAddress private
Address assigned to the client.
Definition at line 167 of file dhcp-client.h.
Referenced by AcceptAck(), LinkStateHandler(), RemoveAndStart(), Request(), StartApplication(), and StopApplication().
m_myMask
Ipv4Mask ns3::DhcpClient::m_myMask private
Mask of the address assigned.
Definition at line 169 of file dhcp-client.h.
Referenced by AcceptAck(), and Select().
m_newLease
TracedCallback<const Ipv4Address&> ns3::DhcpClient::m_newLease private
Trace of new lease.
Definition at line 189 of file dhcp-client.h.
Referenced by AcceptAck(), and GetTypeId().
m_nextoffer
Time ns3::DhcpClient::m_nextoffer private
Time to try the next offer (if request gets no reply)
Definition at line 182 of file dhcp-client.h.
Referenced by GetTypeId(), and Request().
m_nextOfferEvent
EventId ns3::DhcpClient::m_nextOfferEvent private
Message next offer event.
Definition at line 176 of file dhcp-client.h.
Referenced by DhcpClient(), DoDispose(), LinkStateHandler(), NetHandler(), RemoveAndStart(), Request(), and StopApplication().
m_offered
bool ns3::DhcpClient::m_offered private
Specify if the client has got any offer.
Definition at line 186 of file dhcp-client.h.
Referenced by Boot(), OfferHandler(), and Select().
m_offeredAddress
Ipv4Address ns3::DhcpClient::m_offeredAddress private
Address offered to the client.
Definition at line 166 of file dhcp-client.h.
Referenced by AcceptAck(), Request(), and Select().
m_offerList
std::list<DhcpHeader> ns3::DhcpClient::m_offerList private
Stores all the offers given to the client.
Definition at line 187 of file dhcp-client.h.
Referenced by AcceptAck(), OfferHandler(), and Select().
m_ran
Ptr<RandomVariableStream> ns3::DhcpClient::m_ran private
Uniform random variable for transaction ID.
Definition at line 183 of file dhcp-client.h.
Referenced by AssignStreams(), Boot(), GetTypeId(), and Request().
m_rebind
Time ns3::DhcpClient::m_rebind private
Store the rebind time of address.
Definition at line 181 of file dhcp-client.h.
Referenced by AcceptAck(), and Select().
m_rebindEvent
EventId ns3::DhcpClient::m_rebindEvent private
Message rebind event.
Definition at line 175 of file dhcp-client.h.
Referenced by DhcpClient(), AcceptAck(), DoDispose(), LinkStateHandler(), RemoveAndStart(), and StopApplication().
m_refreshEvent
EventId ns3::DhcpClient::m_refreshEvent private
Message refresh event.
Definition at line 174 of file dhcp-client.h.
Referenced by DhcpClient(), AcceptAck(), DoDispose(), LinkStateHandler(), RemoveAndStart(), and StopApplication().
m_remoteAddress
Ipv4Address ns3::DhcpClient::m_remoteAddress private
Initially set to 255.255.255.255 to start DHCP.
Definition at line 165 of file dhcp-client.h.
Referenced by AcceptAck(), Boot(), Request(), and StartApplication().
m_renew
Time ns3::DhcpClient::m_renew private
Store the renew time of address.
Definition at line 180 of file dhcp-client.h.
Referenced by AcceptAck(), and Select().
m_requestEvent
EventId ns3::DhcpClient::m_requestEvent private
Address refresh event.
Definition at line 172 of file dhcp-client.h.
Referenced by DhcpClient(), DoDispose(), LinkStateHandler(), and StopApplication().
m_rtrs
Time ns3::DhcpClient::m_rtrs private
Defining the time for retransmission.
Definition at line 184 of file dhcp-client.h.
Referenced by Boot(), and GetTypeId().
m_server
Ipv4Address ns3::DhcpClient::m_server private
Address of the DHCP server.
Definition at line 170 of file dhcp-client.h.
Referenced by DhcpClient(), GetDhcpServer(), and Select().
m_socket
Ptr<Socket> ns3::DhcpClient::m_socket private
Socket for remote communication.
Definition at line 164 of file dhcp-client.h.
Referenced by DhcpClient(), AcceptAck(), Boot(), LinkStateHandler(), NetHandler(), Request(), StartApplication(), and StopApplication().
m_state
uint8_t ns3::DhcpClient::m_state private
State of the DHCP client.
Definition at line 161 of file dhcp-client.h.
Referenced by AcceptAck(), Boot(), LinkStateHandler(), NetHandler(), and Request().
m_timeout
EventId ns3::DhcpClient::m_timeout private
The timeout period.
Definition at line 177 of file dhcp-client.h.
Referenced by DhcpClient(), AcceptAck(), DoDispose(), LinkStateHandler(), RemoveAndStart(), and StopApplication().
m_tran
uint32_t ns3::DhcpClient::m_tran private
Stores the current transaction number to be used.
Definition at line 188 of file dhcp-client.h.
Referenced by Boot(), and Request().
The documentation for this class was generated from the following files:
src/internet-apps/model/dhcp-client.h
src/internet-apps/model/dhcp-client.cc