ns-3: ns3::UeMemberLteUeCmacSapProvider Class Reference
ns3::UeMemberLteUeCmacSapProvider Class Reference
UeMemberLteUeCmacSapProvider class.
Public Member Functions
UeMemberLteUeCmacSapProvider (LteUeMac *mac)
Constructor.
virtual void AddLc (uint8_t lcId, LteUeCmacSapProvider::LogicalChannelConfig lcConfig, LteMacSapUser *msu)
add a new Logical Channel (LC)
virtual void ConfigureRach (RachConfig rc)
Configure RACH function.
virtual void NotifyConnectionSuccessful ()
Notify MAC about the successful RRC connection establishment.
virtual void RemoveLc (uint8_t lcId)
remove an existing LC
virtual void Reset ()
reset the MAC
virtual void SetImsi (uint64_t imsi)
A method call by UE RRC to communicate the IMSI to the UE MAC.
virtual void SetRnti (uint16_t rnti)
virtual void StartContentionBasedRandomAccessProcedure ()
tell the MAC to start a contention-based random access procedure, e.g., to perform RRC connection establishment
virtual void StartNonContentionBasedRandomAccessProcedure (uint16_t rnti, uint8_t preambleId, uint8_t prachMask)
tell the MAC to start a non-contention-based random access procedure, e.g., as a consequence of handover
Public Member Functions inherited from ns3::LteUeCmacSapProvider
virtual ~LteUeCmacSapProvider ()
Private Attributes
LteUeMac * m_mac
the UE MAC
Detailed Description
UeMemberLteUeCmacSapProvider class.
Definition at line 52 of file lte-ue-mac.cc.
Constructor & Destructor Documentation
UeMemberLteUeCmacSapProvider()
ns3::UeMemberLteUeCmacSapProvider::UeMemberLteUeCmacSapProvider (LteUeMac * mac)
Constructor.
Parameters
mac the UE MAC
Definition at line 78 of file lte-ue-mac.cc.
Member Function Documentation
AddLc()
void ns3::UeMemberLteUeCmacSapProvider::AddLc (uint8_t lcId, LteUeCmacSapProvider::LogicalChannelConfig lcConfig, LteMacSapUser * msu) virtual
add a new Logical Channel (LC)
Parameters
lcId the ID of the LC
lcConfig the LC configuration provided by the RRC
msu the corresponding LteMacSapUser
Implements ns3::LteUeCmacSapProvider.
Definition at line 108 of file lte-ue-mac.cc.
References ns3::LteUeMac::DoAddLc(), and m_mac.
ConfigureRach()
void ns3::UeMemberLteUeCmacSapProvider::ConfigureRach (RachConfig rc) virtual
Configure RACH function.
Parameters
rc the RACH config
Implements ns3::LteUeCmacSapProvider.
Definition at line 84 of file lte-ue-mac.cc.
References ns3::LteUeMac::DoConfigureRach(), and m_mac.
NotifyConnectionSuccessful()
void ns3::UeMemberLteUeCmacSapProvider::NotifyConnectionSuccessful () virtual
Notify MAC about the successful RRC connection establishment.
Implements ns3::LteUeCmacSapProvider.
Definition at line 126 of file lte-ue-mac.cc.
References ns3::LteUeMac::DoNotifyConnectionSuccessful(), and m_mac.
RemoveLc()
void ns3::UeMemberLteUeCmacSapProvider::RemoveLc (uint8_t lcId) virtual
remove an existing LC
Parameters
lcId
Implements ns3::LteUeCmacSapProvider.
Definition at line 114 of file lte-ue-mac.cc.
References ns3::LteUeMac::DoRemoveLc(), and m_mac.
Reset()
void ns3::UeMemberLteUeCmacSapProvider::Reset () virtual
reset the MAC
Implements ns3::LteUeCmacSapProvider.
Definition at line 120 of file lte-ue-mac.cc.
References ns3::LteUeMac::DoReset(), and m_mac.
SetImsi()
void ns3::UeMemberLteUeCmacSapProvider::SetImsi (uint64_t imsi) virtual
A method call by UE RRC to communicate the IMSI to the UE MAC.
Parameters
imsi the IMSI of the UE
Implements ns3::LteUeCmacSapProvider.
Definition at line 132 of file lte-ue-mac.cc.
References ns3::LteUeMac::DoSetImsi(), and m_mac.
SetRnti()
void ns3::UeMemberLteUeCmacSapProvider::SetRnti (uint16_t rnti) virtual
Parameters
rnti the cell-specific UE identifier
Implements ns3::LteUeCmacSapProvider.
Definition at line 102 of file lte-ue-mac.cc.
References ns3::LteUeMac::DoSetRnti(), and m_mac.
StartContentionBasedRandomAccessProcedure()
void ns3::UeMemberLteUeCmacSapProvider::StartContentionBasedRandomAccessProcedure () virtual
tell the MAC to start a contention-based random access procedure, e.g., to perform RRC connection establishment
Implements ns3::LteUeCmacSapProvider.
Definition at line 90 of file lte-ue-mac.cc.
References ns3::LteUeMac::DoStartContentionBasedRandomAccessProcedure(), and m_mac.
StartNonContentionBasedRandomAccessProcedure()
void ns3::UeMemberLteUeCmacSapProvider::StartNonContentionBasedRandomAccessProcedure (uint16_t rnti, uint8_t rapId, uint8_t prachMask) virtual
tell the MAC to start a non-contention-based random access procedure, e.g., as a consequence of handover
Parameters
rnti
rapId Random Access Preamble Identifier
prachMask
Implements ns3::LteUeCmacSapProvider.
Definition at line 96 of file lte-ue-mac.cc.
References ns3::LteUeMac::DoStartNonContentionBasedRandomAccessProcedure(), and m_mac.
Member Data Documentation
m_mac
LteUeMac* ns3::UeMemberLteUeCmacSapProvider::m_mac private
the UE MAC
Definition at line 74 of file lte-ue-mac.cc.
Referenced by AddLc(), ConfigureRach(), NotifyConnectionSuccessful(), RemoveLc(), Reset(), SetImsi(), SetRnti(), StartContentionBasedRandomAccessProcedure(), and StartNonContentionBasedRandomAccessProcedure().
The documentation for this class was generated from the following file:
src/lte/model/lte-ue-mac.cc