ns-3: ns3::PendingData Class Reference
ns3::PendingData Class Reference
Internet » TCP
class for managing I/O between applications and TCP
#include "pending-data.h"
Public Member Functions
PendingData ()
PendingData (const PendingData &o)
Copy constructor.
PendingData (const std::string &s)
Constructor from string.
PendingData (uint32_t s, uint8_t *d=NULL, uint32_t msg=0, uint32_t resp=0)
Constructor.
virtual ~PendingData ()
virtual void Add (Ptr< Packet > p)
Add some data to end.
virtual void Add (uint32_t s, const uint8_t *d=0)
Add some data to end.
virtual void Clear ()
Remove all associated data.
PendingData * Copy () const
Create a copy of self.
virtual Ptr< Packet > CopyFromOffset (uint32_t s, uint32_t o)
Copy data starting from a give offset.
virtual Ptr< Packet > CopyFromSeq (uint32_t s, const SequenceNumber32 &f, const SequenceNumber32 &o)
Copy data starting from a give offset.
PendingData * CopyS (uint32_t s)
Create a copy of self with new size.
PendingData * CopySD (uint32_t s, uint8_t *d)
Create a copy of self with new size, new data.
virtual uint32_t OffsetFromSeq (const SequenceNumber32 &seqFront, const SequenceNumber32 &seqOffset)
Subtracts seqFront from seqOffset after enforcing seqFront is less than seqOffset.
virtual uint32_t RemoveToSeq (const SequenceNumber32 &seqFront, const SequenceNumber32 &seqOffset)
Permits object to clear any pending data between seqFront and seqOffset - 1).
uint32_t Size () const
Returns the size of the pending data.
virtual uint32_t SizeFromOffset (uint32_t offset)
virtual uint32_t SizeFromSeq (const SequenceNumber32 &seqFront, const SequenceNumber32 &seqOffset)
This method returns the number of bytes in the PendingData buffer beyond the sequence number specified by seqOffset.
Public Attributes
std::vector< Ptr< Packet > > data
Corresponding data (may be null)
uint32_t msgSize
Total size of message.
uint32_t responseSize
Size of response requested.
uint32_t size
Number of data bytes.
Detailed Description
class for managing I/O between applications and TCP
Definition at line 41 of file pending-data.h.
Constructor & Destructor Documentation
PendingData() [1/4]
ns3::PendingData::PendingData ()
Definition at line 42 of file pending-data.cc.
References NS_LOG_FUNCTION.
Referenced by Copy(), CopyS(), and CopySD().
PendingData() [2/4]
ns3::PendingData::PendingData (uint32_t s, uint8_t * d = NULL, uint32_t msg = 0, uint32_t resp = 0)
Constructor.
Parameters
s size
d data
msg message size
resp response size
Definition at line 48 of file pending-data.cc.
References data, NS_LOG_FUNCTION, and size.
PendingData() [3/4]
ns3::PendingData::PendingData (const std::string & s)
Constructor from string.
Parameters
s string
Definition at line 58 of file pending-data.cc.
References data, NS_LOG_FUNCTION, and size.
PendingData() [4/4]
ns3::PendingData::PendingData (const PendingData & o)
Copy constructor.
Parameters
o object to copy
Definition at line 66 of file pending-data.cc.
References NS_LOG_FUNCTION, and Size().
~PendingData()
ns3::PendingData::~PendingData () virtual
Definition at line 73 of file pending-data.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Add() [1/2]
void ns3::PendingData::Add (Ptr< Packet > p) virtual
Add some data to end.
Parameters
p packet containing the data.
Definition at line 110 of file pending-data.cc.
References data, ns3::Packet::GetSize(), NS_LOG_FUNCTION, and size.
Add() [2/2]
void ns3::PendingData::Add (uint32_t s, const uint8_t * d = 0) virtual
Add some data to end.
Parameters
s the data size.
d the data to store.
Definition at line 103 of file pending-data.cc.
References data, NS_LOG_FUNCTION, and size.
Clear()
void ns3::PendingData::Clear (void) virtual
Remove all associated data.
Definition at line 96 of file pending-data.cc.
References data, NS_LOG_FUNCTION, and size.
Referenced by RemoveToSeq().
Copy()
PendingData * ns3::PendingData::Copy (void) const
Create a copy of self.
Returns
copy of pending data
Definition at line 78 of file pending-data.cc.
References PendingData(), and NS_LOG_FUNCTION.
CopyFromOffset()
Ptr< Packet > ns3::PendingData::CopyFromOffset (uint32_t s, uint32_t o) virtual
Copy data starting from a give offset.
Parameters
s size of data to copy
o offset
Returns
a packet containing the requested data
Definition at line 142 of file pending-data.cc.
References ns3::Packet::AddAtEnd(), ns3::Packet::CreateFragment(), data, ns3::Packet::GetSize(), min, NS_ASSERT, NS_LOG_FUNCTION, and SizeFromOffset().
Referenced by CopyFromSeq().
CopyFromSeq()
Ptr< Packet > ns3::PendingData::CopyFromSeq (uint32_t s, const SequenceNumber32 & f, const SequenceNumber32 & o) virtual
Copy data starting from a give offset.
Parameters
s size of data to copy
f Front sequence
o Offset sequence
See also
PendingData::OffsetFromSeq()
Returns
a packet containing the requested data
Definition at line 213 of file pending-data.cc.
References CopyFromOffset(), f(), NS_LOG_FUNCTION, and OffsetFromSeq().
CopyS()
PendingData * ns3::PendingData::CopyS (uint32_t s)
Create a copy of self with new size.
Assumes no associated data
Parameters
s new size
Returns
copy of pending data
Definition at line 84 of file pending-data.cc.
References PendingData(), msgSize, NS_LOG_FUNCTION, and responseSize.
CopySD()
PendingData * ns3::PendingData::CopySD (uint32_t s, uint8_t * d)
Create a copy of self with new size, new data.
Assumes no associated data
Parameters
s new size
d new data
Returns
copy of pending data
Definition at line 90 of file pending-data.cc.
References PendingData(), msgSize, NS_LOG_FUNCTION, and responseSize.
OffsetFromSeq()
uint32_t ns3::PendingData::OffsetFromSeq (const SequenceNumber32 & seqFront, const SequenceNumber32 & seqOffset) virtual
Subtracts seqFront from seqOffset after enforcing seqFront is less than seqOffset.
Parameters
seqFront sequence number to be subtracted from seqOffset
seqOffset higher sequence number
Returns
seqOffset-seqFront
Definition at line 132 of file pending-data.cc.
References NS_LOG_FUNCTION.
Referenced by CopyFromSeq(), RemoveToSeq(), and SizeFromSeq().
RemoveToSeq()
uint32_t ns3::PendingData::RemoveToSeq (const SequenceNumber32 & seqFront, const SequenceNumber32 & seqOffset) virtual
Permits object to clear any pending data between seqFront and seqOffset - 1).
Callers should check the return value to determine whether any data was removed from the front.
Parameters
seqFront sequence number to start to try to remove from
seqOffset first sequence number in buffer that should be retained
Returns
number of bytes from the front that were removed from the buffer
Definition at line 220 of file pending-data.cc.
References Clear(), data, NS_ASSERT_MSG, NS_LOG_FUNCTION, OffsetFromSeq(), and size.
Size()
uint32_t ns3::PendingData::Size (void) const inline
Returns the size of the pending data.
Returns
size of pending data
Definition at line 69 of file pending-data.h.
References size.
Referenced by PendingData().
SizeFromOffset()
uint32_t ns3::PendingData::SizeFromOffset (uint32_t offset) virtual
Returns
number of bytes in the data buffer beyond the offset specified
Parameters
offset offset (from zero)
Todo:
should this return zero, or error out?
Definition at line 124 of file pending-data.cc.
References NS_LOG_FUNCTION, and size.
Referenced by CopyFromOffset(), and SizeFromSeq().
SizeFromSeq()
uint32_t ns3::PendingData::SizeFromSeq (const SequenceNumber32 & seqFront, const SequenceNumber32 & seqOffset) virtual
This method returns the number of bytes in the PendingData buffer beyond the sequence number specified by seqOffset.
The variables seqFront and seqOffset correspond to a sequence number space in use by the user. What is significant in this method is the difference between them; i.e. the quantity (seqOffset - seqFront). This difference is subtracted from Size(), yielding the number of bytes beyond seqOffset, from the user perspective, in the PendingData buffer.
If the first number specified is not a sequence number that corresponds to the first data byte in the PendingData buffer, the computation returned will be in error.
Returns
number of bytes
Parameters
seqFront sequence number of assumed first byte in the PendingData
seqOffset sequence number of offset
Definition at line 117 of file pending-data.cc.
References NS_LOG_FUNCTION, OffsetFromSeq(), and SizeFromOffset().
Member Data Documentation
data
std::vector<Ptr<Packet> > ns3::PendingData::data
Corresponding data (may be null)
Definition at line 176 of file pending-data.h.
Referenced by PendingData(), Add(), Clear(), CopyFromOffset(), and RemoveToSeq().
msgSize
uint32_t ns3::PendingData::msgSize
Total size of message.
Definition at line 178 of file pending-data.h.
Referenced by CopyS(), and CopySD().
responseSize
uint32_t ns3::PendingData::responseSize
Size of response requested.
Definition at line 179 of file pending-data.h.
Referenced by CopyS(), and CopySD().
size
uint32_t ns3::PendingData::size
Number of data bytes.
Definition at line 175 of file pending-data.h.
Referenced by PendingData(), Add(), Clear(), RemoveToSeq(), Size(), and SizeFromOffset().
The documentation for this class was generated from the following files:
src/internet/model/pending-data.h
src/internet/model/pending-data.cc