ns-3: ns3::RateErrorModel Class Reference
ns3::RateErrorModel Class Reference
Determine which packets are errored corresponding to an underlying distribution, rate, and unit.
#include "error-model.h"
Public Types
enum ErrorUnit { ERROR_UNIT_BIT , ERROR_UNIT_BYTE , ERROR_UNIT_PACKET }
Error unit.
Public Member Functions
RateErrorModel ()
virtual ~RateErrorModel ()
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
double GetRate (void) const
RateErrorModel::ErrorUnit GetUnit (void) const
void SetRandomVariable (Ptr< RandomVariableStream >)
void SetRate (double rate)
void SetUnit (enum ErrorUnit error_unit)
Public Member Functions inherited from ns3::ErrorModel
ErrorModel ()
virtual ~ErrorModel ()
void Disable (void)
Disable the error model.
void Enable (void)
Enable the error model.
bool IsCorrupt (Ptr< Packet > pkt)
Note: Depending on the error model, this function may or may not alter the contents of the packet upon returning true.
bool IsEnabled (void) const
void Reset (void)
Reset any state associated with the error model.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ErrorModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual bool DoCorrupt (Ptr< Packet > p)
Corrupt a packet according to the specified model.
virtual bool DoCorruptBit (Ptr< Packet > p)
Corrupt a packet (bit unit).
virtual bool DoCorruptByte (Ptr< Packet > p)
Corrupt a packet (Byte unit).
virtual bool DoCorruptPkt (Ptr< Packet > p)
Corrupt a packet (packet unit).
virtual void DoReset (void)
Re-initialize any state.
Private Attributes
Ptr< RandomVariableStream > m_ranvar
rng stream
double m_rate
Error rate.
enum ErrorUnit m_unit
Error rate unit.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Determine which packets are errored corresponding to an underlying distribution, rate, and unit.
This object is used to flag packets as being lost/errored or not. The two parameters that govern the behavior are the rate (or equivalently, the mean duration/spacing between errors), and the unit (which may be per-bit, per-byte, and per-packet). Users can optionally provide a RandomVariableStream object; the default is to use a Uniform(0,1) distribution.
Reset() on this model will do nothing
IsCorrupt() will not modify the packet data buffer
Config Paths
ns3::RateErrorModel is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::SimpleNetDevice/ReceiveErrorModel/$ns3::RateErrorModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Phy/PostReceptionErrorModel/$ns3::RateErrorModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::PointToPointNetDevice/ReceiveErrorModel/$ns3::RateErrorModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::CsmaNetDevice/ReceiveErrorModel/$ns3::RateErrorModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/PhyEntities/[i]/PostReceptionErrorModel/$ns3::RateErrorModel"
Attributes
ErrorUnit: The error unit
Set with class: ns3::EnumValue
Underlying type:
Initial value: ERROR_UNIT_BYTE
Flags: construct write read
ErrorRate: The error rate.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0
Flags: construct write read
RanVar: The decision variable attached to this error model.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::RandomVariableStream>
Initial value: ns3::UniformRandomVariable[Min=0.0|Max=1.0]
Flags: construct write read
Attributes defined in parent class ns3::ErrorModel
IsEnabled: Whether this ErrorModel is enabled or not.
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 56 bytes (on a 64-bit architecture).
Definition at line 182 of file error-model.h.
Member Enumeration Documentation
ErrorUnit
enum ns3::RateErrorModel::ErrorUnit
Error unit.
The error model can be packet, Byte or bit based.
Enumerator
ERROR_UNIT_BIT
ERROR_UNIT_BYTE
ERROR_UNIT_PACKET
Definition at line 197 of file error-model.h.
Constructor & Destructor Documentation
RateErrorModel()
ns3::RateErrorModel::RateErrorModel ()
Definition at line 176 of file error-model.cc.
References NS_LOG_FUNCTION.
~RateErrorModel()
ns3::RateErrorModel::~RateErrorModel () virtual
Definition at line 181 of file error-model.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AssignStreams()
int64_t ns3::RateErrorModel::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 222 of file error-model.cc.
References m_ranvar, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
Referenced by LteRlcAmE2eTestCase::DoRun().
DoCorrupt()
bool ns3::RateErrorModel::DoCorrupt (Ptr< Packet > p) private virtual
Corrupt a packet according to the specified model.
Parameters
p the packet to corrupt
Returns
true if the packet is corrupted
Implements ns3::ErrorModel.
Definition at line 230 of file error-model.cc.
References DoCorruptBit(), DoCorruptByte(), DoCorruptPkt(), ERROR_UNIT_BIT, ERROR_UNIT_BYTE, ERROR_UNIT_PACKET, ns3::ErrorModel::IsEnabled(), m_unit, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
DoCorruptBit()
bool ns3::RateErrorModel::DoCorruptBit (Ptr< Packet > p) private virtual
Corrupt a packet (bit unit).
Parameters
p the packet to corrupt
Returns
true if the packet is corrupted
Definition at line 269 of file error-model.cc.
References ns3::Packet::GetSize(), ns3::RandomVariableStream::GetValue(), m_ranvar, m_rate, and NS_LOG_FUNCTION.
Referenced by DoCorrupt().
DoCorruptByte()
bool ns3::RateErrorModel::DoCorruptByte (Ptr< Packet > p) private virtual
Corrupt a packet (Byte unit).
Parameters
p the packet to corrupt
Returns
true if the packet is corrupted
Definition at line 260 of file error-model.cc.
References ns3::Packet::GetSize(), ns3::RandomVariableStream::GetValue(), m_ranvar, m_rate, and NS_LOG_FUNCTION.
Referenced by DoCorrupt().
DoCorruptPkt()
bool ns3::RateErrorModel::DoCorruptPkt (Ptr< Packet > p) private virtual
Corrupt a packet (packet unit).
Parameters
p the packet to corrupt
Returns
true if the packet is corrupted
Definition at line 253 of file error-model.cc.
References ns3::RandomVariableStream::GetValue(), m_ranvar, m_rate, and NS_LOG_FUNCTION.
Referenced by DoCorrupt().
DoReset()
void ns3::RateErrorModel::DoReset (void) private virtual
Re-initialize any state.
Implements ns3::ErrorModel.
Definition at line 278 of file error-model.cc.
References NS_LOG_FUNCTION.
GetRate()
double ns3::RateErrorModel::GetRate (void) const
Returns
the error rate being applied by the model
Definition at line 201 of file error-model.cc.
References m_rate, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::RateErrorModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 151 of file error-model.cc.
References ERROR_UNIT_BIT, ERROR_UNIT_BYTE, ERROR_UNIT_PACKET, m_ranvar, m_rate, m_unit, ns3::MakeDoubleAccessor(), ns3::MakeEnumAccessor(), ns3::MakeEnumChecker(), ns3::MakePointerAccessor(), and ns3::TypeId::SetParent().
GetUnit()
RateErrorModel::ErrorUnit ns3::RateErrorModel::GetUnit (void) const
Returns
the ErrorUnit being used by the underlying model
Definition at line 187 of file error-model.cc.
References m_unit, and NS_LOG_FUNCTION.
SetRandomVariable()
void ns3::RateErrorModel::SetRandomVariable (Ptr< RandomVariableStream > ranvar)
Parameters
ranvar A random variable distribution to generate random variates
Definition at line 215 of file error-model.cc.
References m_ranvar, and NS_LOG_FUNCTION.
Referenced by ErrorModelSimple::DoRun().
SetRate()
void ns3::RateErrorModel::SetRate (double rate)
Parameters
rate the error rate to be used by the model
Definition at line 208 of file error-model.cc.
References m_rate, and NS_LOG_FUNCTION.
Referenced by ThreeGppHttpObjectTestCase::ThreeGppHttpObjectTestCase().
SetUnit()
void ns3::RateErrorModel::SetUnit (enum ErrorUnit error_unit)
Parameters
error_unit the ErrorUnit to be used by the underlying model
Definition at line 194 of file error-model.cc.
References m_unit, and NS_LOG_FUNCTION.
Referenced by ThreeGppHttpObjectTestCase::ThreeGppHttpObjectTestCase().
Member Data Documentation
m_ranvar
Ptr<RandomVariableStream> ns3::RateErrorModel::m_ranvar private
rng stream
Definition at line 262 of file error-model.h.
Referenced by AssignStreams(), DoCorruptBit(), DoCorruptByte(), DoCorruptPkt(), GetTypeId(), and SetRandomVariable().
m_rate
double ns3::RateErrorModel::m_rate private
Error rate.
Definition at line 260 of file error-model.h.
Referenced by DoCorruptBit(), DoCorruptByte(), DoCorruptPkt(), GetRate(), GetTypeId(), and SetRate().
m_unit
enum ErrorUnit ns3::RateErrorModel::m_unit private
Error rate unit.
Definition at line 257 of file error-model.h.
Referenced by DoCorrupt(), GetTypeId(), GetUnit(), and SetUnit().
The documentation for this class was generated from the following files:
src/network/utils/error-model.h
src/network/utils/error-model.cc