ns-3: ChainRegressionTest Class Reference
ChainRegressionTest Class Reference
AODV Routing
AODV chain regression test.
#include "aodv-regression.h"
Public Member Functions
ChainRegressionTest (const char *const prefix, Time time=Seconds(10), uint32_t size=5, Time arpAliveTimeout=Seconds(120))
Create test case.
~ChainRegressionTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CheckResults ()
Compare traces with reference ones.
void CreateDevices ()
Create devices, install TCP/IP stack and applications.
void CreateNodes ()
Create test topology.
void DoRun ()
Go.
void SendPing ()
Send one ping.
Private Attributes
const Time m_arpAliveTimeout
ARP alive timeout.
NodeContainer * m_nodes
const std::string m_prefix
PCAP file names prefix.
uint16_t m_seq
Sequence number.
const uint32_t m_size
Chain size.
Ptr< Socket > m_socket
Socket.
const double m_step
Chain step, meters.
const Time m_time
Total simulation time.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
AODV chain regression test.
This script creates 1-dimensional grid topology and then ping last node from the first one:
[10.1.1.1] <– step --> [10.1.1.2] <– step --> [10.1.1.3] <– step --> [10.1.1.4] <– step --> [10.1.1.5]
Each node can hear only his right and his left neighbor, if they exist. When one third of total time expired, central node moves away. After this, node 3 doesn't hear any packets from other nodes and nobody hears his packets. We want to demonstrate in this script 1) route establishing 2) broken link detection both from layer 2 information and hello messages.
 Expected packets time diagram.
           1       2       3       4       5
    <------|------>|       |       |       |        RREQ (orig 10.1.1.1, dst 10.1.1.5, G=1, U=1, hop=0, ID=1, org_seqno=1) src = 10.1.1.1
           |<------|------>|       |       |        RREQ (orig 10.1.1.1, dst 10.1.1.5, G=1, U=1, hop=1, ID=1, org_seqno=1) src = 10.1.1.2
           |       |<------|------>|       |        RREQ (orig 10.1.1.1, dst 10.1.1.5, G=1, U=1, hop=2, ID=1, org_seqno=1) src = 10.1.1.3
           |       |       |<------|------>|        RREQ (orig 10.1.1.1, dst 10.1.1.5, G=1, U=1, hop=3, ID=1, org_seqno=1) src = 10.1.1.4
           |       |       |       |<------|------> ARP request. Who has 10.1.1.4? Tell 10.1.1.5
           |       |       |       |======>|        ARP reply
           |       |       |       |<======|        RREP (orig 10.1.1.1, dst 10.1.1.5, hop=0, dst_seqno=0) src=10.1.1.5
           |       |       |<------|------>|        ARP request. Who has 10.1.1.3? Tell 10.1.1.4
           |       |       |======>|       |        ARP reply
           |       |       |<======|       |        RREP (orig 10.1.1.1, dst 10.1.1.5, hop=1, dst_seqno=0) src=10.1.1.4
           |       |<------|------>|       |        ARP request. Who has 10.1.1.2? Tell 10.1.1.3
           |       |======>|       |       |        ARP reply
           |       |<======|       |       |        RREP (orig 10.1.1.1, dst 10.1.1.5, hop=2, dst_seqno=0) src=10.1.1.3
           |<------|------>|       |       |        ARP request. Who has 10.1.1.1? Tell 10.1.1.2
           |======>|       |       |       |        ARP reply
           |<======|       |       |       |        RREP (orig 10.1.1.1, dst 10.1.1.5, hop=3, dst_seqno=0) src=10.1.1.2
   <-------|------>|       |       |       |        ARP request. Who has 10.1.1.2? Tell 10.1.1.1
           |<======|       |       |       |
           |======>|       |       |       |        ICMP (ping) request 0 from 10.1.1.1 to 10.1.1.5; src=10.1.1.1 next_hop=10.1.1.2
           |<------|------>|       |       |        ARP request. Who has 10.1.1.3? Tell 10.1.1.2
           |       |<======|       |       |        ARP reply
           |       |======>|       |       |        ICMP (ping) request 0 from 10.1.1.1 to 10.1.1.5; src=10.1.1.2 next_hop=10.1.1.3
           |       |<------|------>|       |        ARP request. Who has 10.1.1.4? Tell 10.1.1.3
           |       |       |<======|       |        ARP reply
           |       |       |======>|       |        ICMP (ping) request 0 from 10.1.1.1 to 10.1.1.5; src=10.1.1.3 next_hop=10.1.1.4
           |       |       |<------|------>|        ARP request. Who has 10.1.1.5? Tell 10.1.1.4
           |       |       |       |<======|        ARP reply
           |       |       |       |======>|        ICMP (ping) request 0; src=10.1.1.4 next_hop=10.1.1.5
           |       |       |       |<======|        ICMP (ping) reply 0; src=10.1.1.5 next_hop=10.1.1.4
           |       |       |<======|       |        ICMP (ping) reply 0; src=10.1.1.4 next_hop=10.1.1.3
           |       |<======|       |       |        ICMP (ping) reply 0; src=10.1.1.3 next_hop=10.1.1.2
           |<======|       |       |       |        ICMP (ping) reply 0; src=10.1.1.2 next_hop=10.1.1.1
           |       |       |       |<------|------> Hello
           |<------|------>|       |       |        Hello
    <------|------>|       |       |       |        Hello
           |       |<------|------>|       |        Hello
           |======>|       |       |       |        ICMP (ping) request 1; src=10.1.1.1 next_hop=10.1.1.2
           |       |       |<------|------>|        Hello
           |       |======>|       |       |        ICMP (ping) request 1; src=10.1.1.2 next_hop=10.1.1.3
           |       |       |======>|       |        ICMP (ping) request 1; src=10.1.1.3 next_hop=10.1.1.4
           |       |       |       |======>|        ICMP (ping) request 1; src=10.1.1.4 next_hop=10.1.1.5
           |       |       |       |<======|        ICMP (ping) reply 1; src=10.1.1.5 next_hop=10.1.1.4
           |       |       |<======|       |        ICMP (ping) reply 1; src=10.1.1.4 next_hop=10.1.1.3
           |       |<======|       |       |        ICMP (ping) reply 11; src=10.1.1.3 next_hop=10.1.1.2
           |<======|       |       |       |        ICMP (ping) reply 1; src=10.1.1.2 next_hop=10.1.1.1
           |       |       |       |<------|------> Hello
           |<------|------>|       |       |        Hello
    <------|------>|       |       |       |        Hello
           |       |       |<------|------>|        Hello
           |       |<------|------>|       |        Hello
           |======>|       |       |       |        ICMP (ping) request 2; src=10.1.1.1 next_hop=10.1.1.2
           |       |======>|       |       |        ICMP (ping) request 2; src=10.1.1.2 next_hop=10.1.1.3
           |       |       |======>|       |        ICMP (ping) request 2; src=10.1.1.3 next_hop=10.1.1.4
           |       |       |       |======>|        ICMP (ping) request 2; src=10.1.1.4 next_hop=10.1.1.5
           |       |       |       |<======|        ICMP (ping) reply 2; src=10.1.1.5 next_hop=10.1.1.4
           |       |       |<======|       |        ICMP (ping) reply 2; src=10.1.1.4 next_hop=10.1.1.3
           |       |<======|       |       |        ICMP (ping) reply 2; src=10.1.1.3 next_hop=10.1.1.2
           |<======|       |       |       |        ICMP (ping) reply 2; src=10.1.1.2 next_hop=10.1.1.1
           |       |       |       |<------|------> Hello
    <------|------>|       |       |       |        Hello
           |       |<------|------>|       |        Hello
           |<------|------>|       |       |        Hello
           |       |       |<------|------>|        Hello
           |======>|       |       |       |        ICMP (ping) request 3; src=10.1.1.1 next_hop=10.1.1.2
           |       |======>|       |       |        ICMP (ping) request 3; src=10.1.1.2 next_hop=10.1.1.3
           |       |       |======>|       |        ICMP (ping) request 3; src=10.1.1.3 next_hop=10.1.1.4
           |       |       |       |======>|        ICMP (ping) request 3; src=10.1.1.4 next_hop=10.1.1.5
           |       |       |       |<======|        ICMP (ping) reply 3; src=10.1.1.5 next_hop=10.1.1.4
           |       |       |<======|       |        ICMP (ping) reply 3; src=10.1.1.4 next_hop=10.1.1.3
           |       |<======|       |       |        ICMP (ping) reply 3; src=10.1.1.3 next_hop=10.1.1.2
           |<======|       |       |       |        ICMP (ping) reply 3; src=10.1.1.2 next_hop=10.1.1.1
           |       |       |       |<------|------> Hello
    <------|------>|       |       |       |        Hello
           |<------|-->    |       |       |        Hello   |
           |       |    <--|-->    |       |        Hello   |Node 3 move away => nobody hear his packets and node 3 doesn't hear anything !
           |       |       |    <--|------>|        Hello   |
           |======>|       |       |       |        ICMP (ping) request 4; src=10.1.1.1 next_hop=10.1.1.2
           |       |==>    |       |       |        ICMP (ping) request 4; src=10.1.1.2 next_hop=10.1.1.3.   7 retries.
           |<======|       |       |       |        RERR (unreachable dst 10.1.1.3 & 10.1.1.5) src=10.1.1.2
           |       |       |       |<------|------> Hello
    <------|------>|       |       |       |        Hello
           |<------|-->    |       |       |        Hello
           |       |    <--|-->    |       |        Hello
           |       |       |    <--|------>|        Hello
    <------|------>|       |       |       |        RREQ (orig 10.1.1.1, dst 10.1.1.5, G=1, hop=0, ID=2, org_seqno=2) src = 10.1.1.1
           |<------|-->    |       |       |        RREQ (orig 10.1.1.1, dst 10.1.1.5, G=1, hop=1, ID=2, org_seqno=2) src = 10.1.1.2
           |       |       |       |<------|------> Hello
           |       |       |    <--|------>|        Hello
           |       |    <--|-->    |       |        Hello
           |<------|-->    |       |       |        Hello
    <------|------>|       |       |       |        Hello
           |       |       |       |======>|        RERR (unreachable dst 10.1.1.1 & 10.1.1.3) src=10.1.1.4
           |       |       |       |<------|------> Hello
           |       |       |    <--|------>|        Hello
           |       |    <--|-->    |       |        Hello
           |<------|-->    |       |       |        Hello
    <------|------>|       |       |       |        Hello
           |       |       |       |<------|------> Hello
    <------|------>|       |       |       |        RREQ (orig 10.1.1.1, dst 10.1.1.5, G=1, hop=0, ID=4, org_seqno=3) src = 10.1.1.1
           |<------|-->    |       |       |        RREQ (orig 10.1.1.1, dst 10.1.1.5, G=1, hop=1, ID=4, org_seqno=3) src = 10.1.1.2
..................................................................
 *
Definition at line 153 of file aodv-regression.h.
Constructor & Destructor Documentation
~ChainRegressionTest()
ChainRegressionTest::~ChainRegressionTest ()
Definition at line 85 of file aodv-regression.cc.
References m_nodes.
Member Function Documentation
CheckResults()
void ChainRegressionTest::CheckResults () private
Compare traces with reference ones.
Definition at line 217 of file aodv-regression.cc.
References m_prefix, m_size, and NS_PCAP_TEST_EXPECT_EQ.
Referenced by DoRun().
CreateDevices()
void ChainRegressionTest::CreateDevices () private
Create devices, install TCP/IP stack and applications.
Definition at line 161 of file aodv-regression.cc.
References first::address, ns3::AodvHelper::AssignStreams(), ns3::InternetStackHelper::AssignStreams(), ns3::YansWifiChannelHelper::AssignStreams(), ns3::Socket::Bind(), ns3::Socket::Connect(), ns3::YansWifiChannelHelper::Create(), ns3::TestCase::CreateTempDirFilename(), first::devices, ns3::PcapHelperForDevice::EnablePcapAll(), ns3::NodeContainer::Get(), ns3::InternetStackHelper::Install(), first::interfaces, m_nodes, m_prefix, m_size, m_socket, NS_TEST_ASSERT_MSG_EQ, SendPing(), ns3::ObjectBase::SetAttribute(), ns3::YansWifiPhyHelper::SetChannel(), ns3::WifiPhyHelper::SetErrorRateModel(), ns3::InternetStackHelper::SetRoutingHelper(), ns3::WifiMacHelper::SetType(), and third::wifi.
Referenced by DoRun().
CreateNodes()
void ChainRegressionTest::CreateNodes () private
Create test topology.
Definition at line 144 of file aodv-regression.cc.
References ns3::NodeContainer::Create(), m_nodes, m_size, m_step, and third::mobility.
Referenced by DoRun().
DoRun()
void ChainRegressionTest::DoRun (void) private virtual
Go.
Implements ns3::TestCase.
Definition at line 120 of file aodv-regression.cc.
References CheckResults(), CreateDevices(), CreateNodes(), ns3::NodeContainer::Get(), ns3::Object::GetObject(), m_arpAliveTimeout, m_nodes, m_size, m_time, ns3::Config::SetDefault(), and SetPosition().
SendPing()
void ChainRegressionTest::SendPing () private
Send one ping.
Definition at line 91 of file aodv-regression.cc.
References ns3::Packet::AddHeader(), ns3::Icmpv4Header::EnableChecksum(), m_seq, m_socket, m_time, ns3::Now(), ns3::Seconds(), ns3::Socket::Send(), ns3::Icmpv4Header::SetCode(), ns3::Icmpv4Echo::SetData(), ns3::Icmpv4Echo::SetIdentifier(), ns3::Icmpv4Echo::SetSequenceNumber(), and ns3::Icmpv4Header::SetType().
Referenced by CreateDevices().
Member Data Documentation
m_arpAliveTimeout
const Time ChainRegressionTest::m_arpAliveTimeout private
ARP alive timeout.
Definition at line 180 of file aodv-regression.h.
Referenced by DoRun().
m_nodes
NodeContainer* ChainRegressionTest::m_nodes private
Internal: It is important to have pointers here
Definition at line 169 of file aodv-regression.h.
Referenced by ~ChainRegressionTest(), CreateDevices(), CreateNodes(), and DoRun().
m_prefix
const std::string ChainRegressionTest::m_prefix private
PCAP file names prefix.
Definition at line 172 of file aodv-regression.h.
Referenced by CheckResults(), and CreateDevices().
m_seq
uint16_t ChainRegressionTest::m_seq private
Sequence number.
Definition at line 184 of file aodv-regression.h.
Referenced by SendPing().
m_size
const uint32_t ChainRegressionTest::m_size private
Chain size.
Definition at line 176 of file aodv-regression.h.
Referenced by CheckResults(), CreateDevices(), CreateNodes(), and DoRun().
m_socket
Ptr<Socket> ChainRegressionTest::m_socket private
Socket.
Definition at line 182 of file aodv-regression.h.
Referenced by CreateDevices(), and SendPing().
m_step
const double ChainRegressionTest::m_step private
Chain step, meters.
Definition at line 178 of file aodv-regression.h.
Referenced by CreateNodes().
m_time
const Time ChainRegressionTest::m_time private
Total simulation time.
Definition at line 174 of file aodv-regression.h.
Referenced by DoRun(), and SendPing().
The documentation for this class was generated from the following files:
src/aodv/test/aodv-regression.h
src/aodv/test/aodv-regression.cc