ns-3: ns3::ItuR1411NlosOverRooftopPropagationLossModel Class Reference
ns3::ItuR1411NlosOverRooftopPropagationLossModel Class Reference
Propagation Models
the ITU-R 1411 NLOS over rooftop propagation model
#include "itu-r-1411-nlos-over-rooftop-propagation-loss-model.h"
Public Member Functions
ItuR1411NlosOverRooftopPropagationLossModel ()
virtual ~ItuR1411NlosOverRooftopPropagationLossModel ()
double GetLoss (Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
void SetFrequency (double freq)
Set the operating frequency.
Public Member Functions inherited from ns3::PropagationLossModel
PropagationLossModel ()
virtual ~PropagationLossModel ()
int64_t AssignStreams (int64_t stream)
If this loss model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
double CalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account all the PropagationLossModel(s) chained to the current one.
Ptr< PropagationLossModel > GetNext ()
Gets the next PropagationLossModel in the chain of loss models that act on the signal.
void SetNext (Ptr< PropagationLossModel > next)
Enables a chain of loss models to act on the signal.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::PropagationLossModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
ItuR1411NlosOverRooftopPropagationLossModel (const ItuR1411NlosOverRooftopPropagationLossModel &)
Copy constructor.
virtual int64_t DoAssignStreams (int64_t stream)
Subclasses must implement this; those not using random variables can return zero.
virtual double DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account only the particular PropagationLossModel.
ItuR1411NlosOverRooftopPropagationLossModel & operator= (const ItuR1411NlosOverRooftopPropagationLossModel &)
Copy constructor.
Private Attributes
double m_buildingSeparation
in meters
double m_buildingsExtend
in meters
CitySize m_citySize
Dimension of the city.
EnvironmentType m_environment
Environment Scenario.
double m_frequency
frequency in MHz
double m_lambda
wavelength
double m_rooftopHeight
in meters
double m_streetsOrientation
in degrees [0,90]
double m_streetsWidth
in meters
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
the ITU-R 1411 NLOS over rooftop propagation model
This class implements the ITU-R 1411 LOS propagation model for Non-Line-of-Sight (NLoS) short range outdoor communication over rooftops in the frequency range 300 MHz to 100 GHz.
For more information about the model, please see the propagation module documentation in .rst format.
Config Paths
ns3::ItuR1411NlosOverRooftopPropagationLossModel is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::SpectrumChannel/PropagationLossModel/$ns3::ItuR1411NlosOverRooftopPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::YansWifiChannel/PropagationLossModel/$ns3::ItuR1411NlosOverRooftopPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::LrWpanNetDevice/Channel/PropagationLossModel/$ns3::ItuR1411NlosOverRooftopPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::SpectrumChannel/PropagationLossModel/$ns3::ItuR1411NlosOverRooftopPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::YansWifiChannel/PropagationLossModel/$ns3::ItuR1411NlosOverRooftopPropagationLossModel"
"/ChannelList/[i]/$ns3::SpectrumChannel/PropagationLossModel/$ns3::ItuR1411NlosOverRooftopPropagationLossModel"
"/ChannelList/[i]/$ns3::YansWifiChannel/PropagationLossModel/$ns3::ItuR1411NlosOverRooftopPropagationLossModel"
Attributes
Frequency: The Frequency (default is 2.106 GHz).
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 2.16e+09
Flags: construct write
Environment: Environment Scenario
Set with class: ns3::EnumValue
Underlying type:
Initial value: Urban
Flags: construct write read
CitySize: Dimension of the city
Set with class: ns3::EnumValue
Underlying type:
Initial value: Large
Flags: construct write read
RooftopLevel: The height of the rooftop level in meters
Set with class: ns3::DoubleValue
Underlying type: double 0:90
Initial value: 20
Flags: construct write read
StreetsOrientation: The orientation of streets in degrees [0,90] with respect to the direction of propagation
Set with class: ns3::DoubleValue
Underlying type: double 0:90
Initial value: 45
Flags: construct write read
StreetsWidth: The width of streets
Set with class: ns3::DoubleValue
Underlying type: double 0:1000
Initial value: 20
Flags: construct write read
BuildingsExtend: The distance over which the buildings extend
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 80
Flags: construct write read
BuildingSeparation: The separation between buildings
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 50
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 104 bytes (on a 64-bit architecture).
Definition at line 42 of file itu-r-1411-nlos-over-rooftop-propagation-loss-model.h.
Constructor & Destructor Documentation
ItuR1411NlosOverRooftopPropagationLossModel() [1/2]
ns3::ItuR1411NlosOverRooftopPropagationLossModel::ItuR1411NlosOverRooftopPropagationLossModel ()
Definition at line 92 of file itu-r-1411-nlos-over-rooftop-propagation-loss-model.cc.
~ItuR1411NlosOverRooftopPropagationLossModel()
ns3::ItuR1411NlosOverRooftopPropagationLossModel::~ItuR1411NlosOverRooftopPropagationLossModel () virtual
Definition at line 97 of file itu-r-1411-nlos-over-rooftop-propagation-loss-model.cc.
ItuR1411NlosOverRooftopPropagationLossModel() [2/2]
ns3::ItuR1411NlosOverRooftopPropagationLossModel::ItuR1411NlosOverRooftopPropagationLossModel (const ItuR1411NlosOverRooftopPropagationLossModel &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Member Function Documentation
DoAssignStreams()
int64_t ns3::ItuR1411NlosOverRooftopPropagationLossModel::DoAssignStreams (int64_t stream) private virtual
Subclasses must implement this; those not using random variables can return zero.
Implements ns3::PropagationLossModel.
Definition at line 224 of file itu-r-1411-nlos-over-rooftop-propagation-loss-model.cc.
DoCalcRxPower()
double ns3::ItuR1411NlosOverRooftopPropagationLossModel::DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const private virtual
Returns the Rx Power taking into account only the particular PropagationLossModel.
Parameters
txPowerDbm current transmission power (in dBm)
a the mobility model of the source
b the mobility model of the destination
Returns
the reception power after adding/multiplying propagation loss (in dBm)
Implements ns3::PropagationLossModel.
Definition at line 216 of file itu-r-1411-nlos-over-rooftop-propagation-loss-model.cc.
References GetLoss().
GetLoss()
double ns3::ItuR1411NlosOverRooftopPropagationLossModel::GetLoss (Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Parameters
a the first mobility model
b the second mobility model
Returns
the loss in dBm for the propagation between the two given mobility models
Definition at line 102 of file itu-r-1411-nlos-over-rooftop-propagation-loss-model.cc.
References ns3::MobilityModel::GetDistanceFrom(), ns3::MobilityModel::GetPosition(), ns3::LargeCity, m_buildingSeparation, m_buildingsExtend, m_citySize, m_environment, m_frequency, m_lambda, m_rooftopHeight, m_streetsOrientation, m_streetsWidth, NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, and ns3::UrbanEnvironment.
Referenced by DoCalcRxPower().
GetTypeId()
TypeId ns3::ItuR1411NlosOverRooftopPropagationLossModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 38 of file itu-r-1411-nlos-over-rooftop-propagation-loss-model.cc.
References ns3::LargeCity, m_buildingSeparation, m_buildingsExtend, m_citySize, m_environment, m_rooftopHeight, m_streetsOrientation, m_streetsWidth, ns3::MakeDoubleAccessor(), ns3::MakeEnumAccessor(), ns3::MakeEnumChecker(), ns3::MediumCity, ns3::OpenAreasEnvironment, SetFrequency(), ns3::TypeId::SetParent(), ns3::SmallCity, ns3::SubUrbanEnvironment, and ns3::UrbanEnvironment.
operator=()
ItuR1411NlosOverRooftopPropagationLossModel& ns3::ItuR1411NlosOverRooftopPropagationLossModel::operator= (const ItuR1411NlosOverRooftopPropagationLossModel &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Returns
SetFrequency()
void ns3::ItuR1411NlosOverRooftopPropagationLossModel::SetFrequency (double freq)
Set the operating frequency.
Parameters
freq the frequency in Hz
Definition at line 208 of file itu-r-1411-nlos-over-rooftop-propagation-loss-model.cc.
References m_frequency, and m_lambda.
Referenced by GetTypeId().
Member Data Documentation
m_buildingSeparation
double ns3::ItuR1411NlosOverRooftopPropagationLossModel::m_buildingSeparation private
in meters
Definition at line 102 of file itu-r-1411-nlos-over-rooftop-propagation-loss-model.h.
Referenced by GetLoss(), and GetTypeId().
m_buildingsExtend
double ns3::ItuR1411NlosOverRooftopPropagationLossModel::m_buildingsExtend private
in meters
Definition at line 101 of file itu-r-1411-nlos-over-rooftop-propagation-loss-model.h.
Referenced by GetLoss(), and GetTypeId().
m_citySize
CitySize ns3::ItuR1411NlosOverRooftopPropagationLossModel::m_citySize private
Dimension of the city.
Definition at line 97 of file itu-r-1411-nlos-over-rooftop-propagation-loss-model.h.
Referenced by GetLoss(), and GetTypeId().
m_environment
EnvironmentType ns3::ItuR1411NlosOverRooftopPropagationLossModel::m_environment private
Environment Scenario.
Definition at line 96 of file itu-r-1411-nlos-over-rooftop-propagation-loss-model.h.
Referenced by GetLoss(), and GetTypeId().
m_frequency
double ns3::ItuR1411NlosOverRooftopPropagationLossModel::m_frequency private
frequency in MHz
Definition at line 94 of file itu-r-1411-nlos-over-rooftop-propagation-loss-model.h.
Referenced by GetLoss(), and SetFrequency().
m_lambda
double ns3::ItuR1411NlosOverRooftopPropagationLossModel::m_lambda private
wavelength
Definition at line 95 of file itu-r-1411-nlos-over-rooftop-propagation-loss-model.h.
Referenced by GetLoss(), and SetFrequency().
m_rooftopHeight
double ns3::ItuR1411NlosOverRooftopPropagationLossModel::m_rooftopHeight private
in meters
Definition at line 98 of file itu-r-1411-nlos-over-rooftop-propagation-loss-model.h.
Referenced by GetLoss(), and GetTypeId().
m_streetsOrientation
double ns3::ItuR1411NlosOverRooftopPropagationLossModel::m_streetsOrientation private
in degrees [0,90]
Definition at line 99 of file itu-r-1411-nlos-over-rooftop-propagation-loss-model.h.
Referenced by GetLoss(), and GetTypeId().
m_streetsWidth
double ns3::ItuR1411NlosOverRooftopPropagationLossModel::m_streetsWidth private
in meters
Definition at line 100 of file itu-r-1411-nlos-over-rooftop-propagation-loss-model.h.
Referenced by GetLoss(), and GetTypeId().
The documentation for this class was generated from the following files:
src/propagation/model/itu-r-1411-nlos-over-rooftop-propagation-loss-model.h
src/propagation/model/itu-r-1411-nlos-over-rooftop-propagation-loss-model.cc