ns-3: LteUplinkSrsSinrTestCase Class Reference
LteUplinkSrsSinrTestCase Class Reference
LTE Models » lte module tests | Test suites
In this test one signal will be of interest, i.e., the SRS of the first signal will have the same CellId of the receiving PHY; the others will have a different CellId and hence will be the interfering signals.
#include "lte-test-uplink-sinr.h"
Public Member Functions
LteUplinkSrsSinrTestCase (Ptr< SpectrumValue > sv1, Ptr< SpectrumValue > sv2, Ptr< SpectrumValue > sinr, std::string name)
Constructor.
virtual ~LteUplinkSrsSinrTestCase ()
void ReportSinr (const SpectrumValue &sinr)
Callback to be connected to an LteChunkProcessor to collect the reported SINR.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
Ptr< SpectrumValue > m_actualSinr
the actual SINR
Ptr< SpectrumValue > m_expectedSinr
the expected SINR
Ptr< const SpectrumModel > m_sm
the spectrum model
Ptr< SpectrumValue > m_sv1
the spectrum value #1
Ptr< SpectrumValue > m_sv2
the spectrum value #2
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
In this test one signal will be of interest, i.e., the SRS of the first signal will have the same CellId of the receiving PHY; the others will have a different CellId and hence will be the interfering signals.
The test checks whether the SINR of the signal correspond to the theoretical value.
Definition at line 90 of file lte-test-uplink-sinr.h.
Constructor & Destructor Documentation
LteUplinkSrsSinrTestCase()
LteUplinkSrsSinrTestCase::LteUplinkSrsSinrTestCase (Ptr< SpectrumValue > sv1, Ptr< SpectrumValue > sv2, Ptr< SpectrumValue > sinr, std::string name)
Constructor.
TestCase Srs.
Parameters
sv1 spectrum value 1
sv2 spectrum value 2
sinr the SINR
name the reference name
Definition at line 316 of file lte-test-uplink-sinr.cc.
References NS_LOG_INFO.
~LteUplinkSrsSinrTestCase()
LteUplinkSrsSinrTestCase::~LteUplinkSrsSinrTestCase () virtual
Definition at line 326 of file lte-test-uplink-sinr.cc.
Member Function Documentation
DoRun()
void LteUplinkSrsSinrTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Instantiate a single receiving LteSpectrumPhy
Generate several calls to LteSpectrumPhy::StartRx corresponding to several signals. One will be the signal of interest, i.e., the LteSpectrumSignalParametersUlSrsFrame of the first signal will have the same CellId of the receiving PHY; the others will have a different CellId and hence will be the interfering signals
Build packet burst (Data and interference)
Schedule the reception of the data signals plus the interference signals
Implements ns3::TestCase.
Definition at line 337 of file lte-test-uplink-sinr.cc.
References m_actualSinr, m_expectedSinr, m_sm, m_sv1, m_sv2, ns3::MakeCallback(), NS_ASSERT_MSG, NS_LOG_INFO, NS_TEST_ASSERT_MSG_SPECTRUM_VALUE_EQ_TOL, ReportSinr(), and ns3::Seconds().
ReportSinr()
void LteUplinkSrsSinrTestCase::ReportSinr (const SpectrumValue & sinr)
Callback to be connected to an LteChunkProcessor to collect the reported SINR.
Parameters
sinr
Definition at line 331 of file lte-test-uplink-sinr.cc.
References ns3::SpectrumValue::Copy(), and m_actualSinr.
Referenced by DoRun().
Member Data Documentation
m_actualSinr
Ptr<SpectrumValue> LteUplinkSrsSinrTestCase::m_actualSinr private
the actual SINR
Definition at line 119 of file lte-test-uplink-sinr.h.
Referenced by DoRun(), and ReportSinr().
m_expectedSinr
Ptr<SpectrumValue> LteUplinkSrsSinrTestCase::m_expectedSinr private
the expected SINR
Definition at line 118 of file lte-test-uplink-sinr.h.
Referenced by DoRun().
m_sm
Ptr<const SpectrumModel> LteUplinkSrsSinrTestCase::m_sm private
the spectrum model
Definition at line 116 of file lte-test-uplink-sinr.h.
Referenced by DoRun().
m_sv1
Ptr<SpectrumValue> LteUplinkSrsSinrTestCase::m_sv1 private
the spectrum value #1
Definition at line 114 of file lte-test-uplink-sinr.h.
Referenced by DoRun().
m_sv2
Ptr<SpectrumValue> LteUplinkSrsSinrTestCase::m_sv2 private
the spectrum value #2
Definition at line 115 of file lte-test-uplink-sinr.h.
Referenced by DoRun().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-uplink-sinr.h
src/lte/test/lte-test-uplink-sinr.cc