ns-3: ns3::ThreeGppHttpServerHelper Class Reference
ns3::ThreeGppHttpServerHelper Class Reference
Applications » ThreeGppHttpClientServer
Helper to make it easier to instantiate an ThreeGppHttpServer on a set of nodes.
#include "three-gpp-http-helper.h"
Public Member Functions
ThreeGppHttpServerHelper (const Address &address)
Create a ThreeGppHttpServerHelper to make it easier to work with ThreeGppHttpServer applications.
ApplicationContainer Install (const std::string &nodeName) const
Install an ThreeGppHttpServer on each node of the input container configured with all the attributes set with SetAttribute().
ApplicationContainer Install (NodeContainer c) const
Install an ThreeGppHttpServer on each node of the input container configured with all the attributes set with SetAttribute().
ApplicationContainer Install (Ptr< Node > node) const
Install an ThreeGppHttpServer on each node of the input container configured with all the attributes set with SetAttribute().
void SetAttribute (const std::string &name, const AttributeValue &value)
Helper function used to set the underlying application attributes, but not the socket attributes.
Private Member Functions
Ptr< Application > InstallPriv (Ptr< Node > node) const
Private Attributes
ObjectFactory m_factory
Used to instantiate a ThreeGppHttpServer instance.
Detailed Description
Helper to make it easier to instantiate an ThreeGppHttpServer on a set of nodes.
Definition at line 108 of file three-gpp-http-helper.h.
Constructor & Destructor Documentation
ThreeGppHttpServerHelper()
ns3::ThreeGppHttpServerHelper::ThreeGppHttpServerHelper (const Address & address)
Create a ThreeGppHttpServerHelper to make it easier to work with ThreeGppHttpServer applications.
Parameters
address The address of the server.
Definition at line 85 of file three-gpp-http-helper.cc.
References first::address, m_factory, ns3::ObjectFactory::Set(), and ns3::ObjectFactory::SetTypeId().
Member Function Documentation
Install() [1/3]
ApplicationContainer ns3::ThreeGppHttpServerHelper::Install (const std::string & nodeName) const
Install an ThreeGppHttpServer on each node of the input container configured with all the attributes set with SetAttribute().
Parameters
nodeName The name of the node on which an ThreeGppHttpServer will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 105 of file three-gpp-http-helper.cc.
References InstallPriv().
Install() [2/3]
ApplicationContainer ns3::ThreeGppHttpServerHelper::Install (NodeContainer c) const
Install an ThreeGppHttpServer on each node of the input container configured with all the attributes set with SetAttribute().
Parameters
c NodeContainer of the set of nodes on which an ThreeGppHttpServer will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 112 of file three-gpp-http-helper.cc.
References ns3::ApplicationContainer::Add(), ns3::NodeContainer::Begin(), ns3::NodeContainer::End(), and InstallPriv().
Referenced by ThreeGppHttpObjectTestCase::DoRun().
Install() [3/3]
ApplicationContainer ns3::ThreeGppHttpServerHelper::Install (Ptr< Node > node) const
Install an ThreeGppHttpServer on each node of the input container configured with all the attributes set with SetAttribute().
Parameters
node The node on which an ThreeGppHttpServer will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 99 of file three-gpp-http-helper.cc.
References InstallPriv().
InstallPriv()
Ptr< Application > ns3::ThreeGppHttpServerHelper::InstallPriv (Ptr< Node > node) const private
Internal:
Install an ThreeGppHttpServer on the node configured with all the attributes set with SetAttribute().
Parameters
node The node on which an ThreeGppHttpServer will be installed.
Returns
Ptr to the application installed.
Definition at line 124 of file three-gpp-http-helper.cc.
References ns3::Node::AddApplication(), ns3::ObjectFactory::Create(), and m_factory.
Referenced by Install().
SetAttribute()
void ns3::ThreeGppHttpServerHelper::SetAttribute (const std::string & name, const AttributeValue & value)
Helper function used to set the underlying application attributes, but not the socket attributes.
Parameters
name The name of the application attribute to set.
value The value of the application attribute to set.
Definition at line 92 of file three-gpp-http-helper.cc.
References m_factory, and ns3::ObjectFactory::Set().
Member Data Documentation
m_factory
ObjectFactory ns3::ThreeGppHttpServerHelper::m_factory private
Used to instantiate a ThreeGppHttpServer instance.
Definition at line 164 of file three-gpp-http-helper.h.
Referenced by ThreeGppHttpServerHelper(), InstallPriv(), and SetAttribute().
The documentation for this class was generated from the following files:
src/applications/helper/three-gpp-http-helper.h
src/applications/helper/three-gpp-http-helper.cc