ns-3: ns3::OlsrHelper Class Reference
ns3::OlsrHelper Class Reference
OLSR Routing
Helper class that adds OLSR routing to nodes.
#include "olsr-helper.h"
Public Member Functions
OlsrHelper ()
Create an OlsrHelper that makes life easier for people who want to install OLSR routing to nodes.
OlsrHelper (const OlsrHelper &)
Construct an OlsrHelper from another previously initialized instance (Copy Constructor).
int64_t AssignStreams (NodeContainer c, int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
OlsrHelper * Copy (void) const
virtual Ptr< Ipv4RoutingProtocol > Create (Ptr< Node > node) const
void ExcludeInterface (Ptr< Node > node, uint32_t interface)
void Set (std::string name, const AttributeValue &value)
Public Member Functions inherited from ns3::Ipv4RoutingHelper
virtual ~Ipv4RoutingHelper ()
Private Member Functions
OlsrHelper & operator= (const OlsrHelper &)
Assignment operator declared private and not implemented to disallow assignment and prevent the compiler from happily inserting its own.
Private Attributes
ObjectFactory m_agentFactory
Object factory.
std::map< Ptr< Node >, std::set< uint32_t > > m_interfaceExclusions
container of interfaces excluded from OLSR operations
Additional Inherited Members
Static Public Member Functions inherited from ns3::Ipv4RoutingHelper
template<class T >
static Ptr< T > GetRouting (Ptr< Ipv4RoutingProtocol > protocol)
Request a specified routing protocol <T> from Ipv4RoutingProtocol protocol.
static void PrintNeighborCacheAllAt (Time printTime, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the neighbor cache of all nodes at a particular time.
static void PrintNeighborCacheAllEvery (Time printInterval, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the neighbor cache of all nodes at regular intervals specified by user.
static void PrintNeighborCacheAt (Time printTime, Ptr< Node > node, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the neighbor cache of a node at a particular time.
static void PrintNeighborCacheEvery (Time printInterval, Ptr< Node > node, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the neighbor cache of a node at regular intervals specified by user.
static void PrintRoutingTableAllAt (Time printTime, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of all nodes at a particular time.
static void PrintRoutingTableAllEvery (Time printInterval, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of all nodes at regular intervals specified by user.
static void PrintRoutingTableAt (Time printTime, Ptr< Node > node, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of a node at a particular time.
static void PrintRoutingTableEvery (Time printInterval, Ptr< Node > node, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of a node at regular intervals specified by user.
Detailed Description
Helper class that adds OLSR routing to nodes.
This class is expected to be used in conjunction with ns3::InternetStackHelper::SetRoutingHelper
Definition at line 40 of file olsr-helper.h.
Constructor & Destructor Documentation
OlsrHelper() [1/2]
ns3::OlsrHelper::OlsrHelper ()
Create an OlsrHelper that makes life easier for people who want to install OLSR routing to nodes.
Definition at line 29 of file olsr-helper.cc.
References m_agentFactory, and ns3::ObjectFactory::SetTypeId().
Referenced by Copy().
OlsrHelper() [2/2]
ns3::OlsrHelper::OlsrHelper (const OlsrHelper & o)
Construct an OlsrHelper from another previously initialized instance (Copy Constructor).
Definition at line 34 of file olsr-helper.cc.
References m_interfaceExclusions.
Member Function Documentation
AssignStreams()
int64_t ns3::OlsrHelper::AssignStreams (NodeContainer c, int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned. The Install() method of the InternetStackHelper should have previously been called by the user.
Parameters
stream first stream index to use
c NodeContainer of the set of nodes for which the OlsrRoutingProtocol should be modified to use a fixed stream
Returns
the number of stream indices assigned by this helper
Definition at line 87 of file olsr-helper.cc.
References ns3::NodeContainer::Begin(), ns3::NodeContainer::End(), ns3::Object::GetObject(), list, and NS_ASSERT_MSG.
Copy()
OlsrHelper * ns3::OlsrHelper::Copy (void) const virtual
Returns
pointer to clone of this OlsrHelper
This method is mainly for internal use by the other helpers; clients are expected to free the dynamic memory allocated by this method
Implements ns3::Ipv4RoutingHelper.
Definition at line 41 of file olsr-helper.cc.
References OlsrHelper().
Create()
Ptr< Ipv4RoutingProtocol > ns3::OlsrHelper::Create (Ptr< Node > node) const virtual
Parameters
node the node on which the routing protocol will run
Returns
a newly-created routing protocol
This method will be called by ns3::InternetStackHelper::Install
Implements ns3::Ipv4RoutingHelper.
Definition at line 65 of file olsr-helper.cc.
References ns3::Object::AggregateObject(), ns3::ObjectFactory::Create(), m_agentFactory, and m_interfaceExclusions.
ExcludeInterface()
void ns3::OlsrHelper::ExcludeInterface (Ptr< Node > node, uint32_t interface)
Parameters
node the node for which an exception is to be defined
interface an interface of node on which OLSR is not to be installed
This method allows the user to specify an interface on which OLSR is not to be installed on
Definition at line 47 of file olsr-helper.cc.
References first::interfaces, and m_interfaceExclusions.
operator=()
OlsrHelper& ns3::OlsrHelper::operator= (const OlsrHelper &) private
Assignment operator declared private and not implemented to disallow assignment and prevent the compiler from happily inserting its own.
Returns
nothing
Set()
void ns3::OlsrHelper::Set (std::string name, const AttributeValue & value)
Parameters
name the name of the attribute to set
value the value of the attribute to set.
This method controls the attributes of ns3::olsr::RoutingProtocol
Definition at line 81 of file olsr-helper.cc.
References m_agentFactory, and ns3::ObjectFactory::Set().
Member Data Documentation
m_agentFactory
ObjectFactory ns3::OlsrHelper::m_agentFactory private
Object factory.
Definition at line 107 of file olsr-helper.h.
Referenced by OlsrHelper(), Create(), and Set().
m_interfaceExclusions
std::map< Ptr<Node>, std::set<uint32_t> > ns3::OlsrHelper::m_interfaceExclusions private
container of interfaces excluded from OLSR operations
Definition at line 109 of file olsr-helper.h.
Referenced by OlsrHelper(), Create(), and ExcludeInterface().
The documentation for this class was generated from the following files:
src/olsr/helper/olsr-helper.h
src/olsr/helper/olsr-helper.cc