ns-3: ns3::DsdvHelper Class Reference
ns3::DsdvHelper Class Reference
DSDV Routing
Helper class that adds DSDV routing to nodes.
#include "dsdv-helper.h"
Public Member Functions
DsdvHelper ()
~DsdvHelper ()
DsdvHelper * Copy (void) const
virtual Ptr< Ipv4RoutingProtocol > Create (Ptr< Node > node) const
void Set (std::string name, const AttributeValue &value)
Public Member Functions inherited from ns3::Ipv4RoutingHelper
virtual ~Ipv4RoutingHelper ()
Private Attributes
ObjectFactory m_agentFactory
Object factory.
Additional Inherited Members
Static Public Member Functions inherited from ns3::Ipv4RoutingHelper
template<class T >
static Ptr< T > GetRouting (Ptr< Ipv4RoutingProtocol > protocol)
Request a specified routing protocol <T> from Ipv4RoutingProtocol protocol.
static void PrintNeighborCacheAllAt (Time printTime, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the neighbor cache of all nodes at a particular time.
static void PrintNeighborCacheAllEvery (Time printInterval, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the neighbor cache of all nodes at regular intervals specified by user.
static void PrintNeighborCacheAt (Time printTime, Ptr< Node > node, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the neighbor cache of a node at a particular time.
static void PrintNeighborCacheEvery (Time printInterval, Ptr< Node > node, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the neighbor cache of a node at regular intervals specified by user.
static void PrintRoutingTableAllAt (Time printTime, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of all nodes at a particular time.
static void PrintRoutingTableAllEvery (Time printInterval, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of all nodes at regular intervals specified by user.
static void PrintRoutingTableAt (Time printTime, Ptr< Node > node, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of a node at a particular time.
static void PrintRoutingTableEvery (Time printInterval, Ptr< Node > node, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of a node at regular intervals specified by user.
Detailed Description
Helper class that adds DSDV routing to nodes.
Definition at line 45 of file dsdv-helper.h.
Constructor & Destructor Documentation
DsdvHelper()
ns3::DsdvHelper::DsdvHelper ()
Definition at line 42 of file dsdv-helper.cc.
References m_agentFactory, and ns3::ObjectFactory::SetTypeId().
Referenced by Copy().
~DsdvHelper()
ns3::DsdvHelper::~DsdvHelper ()
Definition at line 38 of file dsdv-helper.cc.
Member Function Documentation
Copy()
DsdvHelper * ns3::DsdvHelper::Copy (void) const virtual
Returns
pointer to clone of this DsdvHelper
This method is mainly for internal use by the other helpers; clients are expected to free the dynamic memory allocated by this method
Implements ns3::Ipv4RoutingHelper.
Definition at line 48 of file dsdv-helper.cc.
References DsdvHelper().
Create()
Ptr< Ipv4RoutingProtocol > ns3::DsdvHelper::Create (Ptr< Node > node) const virtual
Parameters
node the node on which the routing protocol will run
Returns
a newly-created routing protocol
This method will be called by ns3::InternetStackHelper::Install
Implements ns3::Ipv4RoutingHelper.
Definition at line 54 of file dsdv-helper.cc.
References ns3::Object::AggregateObject(), ns3::ObjectFactory::Create(), and m_agentFactory.
Set()
void ns3::DsdvHelper::Set (std::string name, const AttributeValue & value)
Parameters
name the name of the attribute to set
value the value of the attribute to set.
This method controls the attributes of ns3::dsdv::RoutingProtocol
Definition at line 62 of file dsdv-helper.cc.
References m_agentFactory, and ns3::ObjectFactory::Set().
Referenced by DsdvManetExample::InstallInternetStack().
Member Data Documentation
m_agentFactory
ObjectFactory ns3::DsdvHelper::m_agentFactory private
Object factory.
Definition at line 75 of file dsdv-helper.h.
Referenced by DsdvHelper(), Create(), and Set().
The documentation for this class was generated from the following files:
src/dsdv/helper/dsdv-helper.h
src/dsdv/helper/dsdv-helper.cc