ns-3: LteRlcAmTransmitterTestCase Class Reference
LteRlcAmTransmitterTestCase Class Reference
LTE Models » lte module tests | Test suites
Test case used by LteRlcAmTransmitterOneSduTestCase to create topology and to implement functionalities and check if data received corresponds to data sent.
#include "lte-test-rlc-am-transmitter.h"
Public Member Functions
LteRlcAmTransmitterTestCase ()
LteRlcAmTransmitterTestCase (std::string name)
Constructor.
virtual ~LteRlcAmTransmitterTestCase ()
void CheckDataReceived (Time time, std::string shouldReceived, std::string assertMsg)
Check data received function.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Protected Attributes
Ptr< LteTestMac > txMac
the MAC
Ptr< LteTestPdcp > txPdcp
the transmit PDCP
Ptr< LteRlc > txRlc
the RLC
Private Member Functions
void DoCheckDataReceived (std::string shouldReceived, std::string assertMsg)
Check data received function.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Detailed Description
Test case used by LteRlcAmTransmitterOneSduTestCase to create topology and to implement functionalities and check if data received corresponds to data sent.
Definition at line 57 of file lte-test-rlc-am-transmitter.h.
Constructor & Destructor Documentation
LteRlcAmTransmitterTestCase() [1/2]
LteRlcAmTransmitterTestCase::LteRlcAmTransmitterTestCase (std::string name)
Constructor.
Parameters
name the reference name
Definition at line 54 of file lte-test-rlc-am-transmitter.cc.
LteRlcAmTransmitterTestCase() [2/2]
LteRlcAmTransmitterTestCase::LteRlcAmTransmitterTestCase ()
~LteRlcAmTransmitterTestCase()
LteRlcAmTransmitterTestCase::~LteRlcAmTransmitterTestCase () virtual
Definition at line 59 of file lte-test-rlc-am-transmitter.cc.
Member Function Documentation
CheckDataReceived()
void LteRlcAmTransmitterTestCase::CheckDataReceived (Time time, std::string shouldReceived, std::string assertMsg)
Check data received function.
Parameters
time the time to check
shouldReceived shoul dhave received indicator
assertMsg the assert message
Definition at line 102 of file lte-test-rlc-am-transmitter.cc.
References DoCheckDataReceived().
Referenced by LteRlcAmTransmitterOneSduTestCase::DoRun(), LteRlcAmTransmitterSegmentationTestCase::DoRun(), LteRlcAmTransmitterConcatenationTestCase::DoRun(), and LteRlcAmTransmitterReportBufferStatusTestCase::DoRun().
DoCheckDataReceived()
void LteRlcAmTransmitterTestCase::DoCheckDataReceived (std::string shouldReceived, std::string assertMsg) private
Check data received function.
Parameters
shouldReceived shoul dhave received indicator
assertMsg the assert message
Definition at line 108 of file lte-test-rlc-am-transmitter.cc.
References ns3::LteTestMac::GetDataReceived(), NS_TEST_ASSERT_MSG_EQ, and txMac.
Referenced by CheckDataReceived().
DoRun()
void LteRlcAmTransmitterTestCase::DoRun (void) protected virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Reimplemented in LteRlcAmTransmitterReportBufferStatusTestCase, LteRlcAmTransmitterConcatenationTestCase, LteRlcAmTransmitterSegmentationTestCase, and LteRlcAmTransmitterOneSduTestCase.
Definition at line 64 of file lte-test-rlc-am-transmitter.cc.
References ns3::LteTestMac::GetLteMacSapProvider(), ns3::LteRlc::GetLteMacSapUser(), ns3::LteRlc::GetLteRlcSapProvider(), ns3::LteTestPdcp::GetLteRlcSapUser(), ns3::LteRlc::SetLcId(), ns3::LteRlc::SetLteMacSapProvider(), ns3::LteTestMac::SetLteMacSapUser(), ns3::LteTestPdcp::SetLteRlcSapProvider(), ns3::LteRlc::SetLteRlcSapUser(), ns3::LteTestMac::SetRlcHeaderType(), ns3::LteRlc::SetRnti(), txMac, txPdcp, and txRlc.
Referenced by LteRlcAmTransmitterOneSduTestCase::DoRun(), LteRlcAmTransmitterSegmentationTestCase::DoRun(), LteRlcAmTransmitterConcatenationTestCase::DoRun(), and LteRlcAmTransmitterReportBufferStatusTestCase::DoRun().
Member Data Documentation
txMac
Ptr<LteTestMac> LteRlcAmTransmitterTestCase::txMac protected
the MAC
Definition at line 82 of file lte-test-rlc-am-transmitter.h.
Referenced by DoCheckDataReceived(), DoRun(), LteRlcAmTransmitterOneSduTestCase::DoRun(), LteRlcAmTransmitterSegmentationTestCase::DoRun(), LteRlcAmTransmitterConcatenationTestCase::DoRun(), and LteRlcAmTransmitterReportBufferStatusTestCase::DoRun().
txPdcp
Ptr<LteTestPdcp> LteRlcAmTransmitterTestCase::txPdcp protected
the transmit PDCP
Definition at line 80 of file lte-test-rlc-am-transmitter.h.
Referenced by DoRun(), LteRlcAmTransmitterOneSduTestCase::DoRun(), LteRlcAmTransmitterSegmentationTestCase::DoRun(), LteRlcAmTransmitterConcatenationTestCase::DoRun(), and LteRlcAmTransmitterReportBufferStatusTestCase::DoRun().
txRlc
Ptr<LteRlc> LteRlcAmTransmitterTestCase::txRlc protected
the RLC
Definition at line 81 of file lte-test-rlc-am-transmitter.h.
Referenced by DoRun().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-rlc-am-transmitter.h
src/lte/test/lte-test-rlc-am-transmitter.cc