ns-3: TimeSimpleTestCase Class Reference
TimeSimpleTestCase Class Reference
Test suites | Core » Core module tests
time simple test case, Checks the basic operations on time
Public Member Functions
TimeSimpleTestCase ()
constructor for TimeSimpleTestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Runs the Simple Time test case.
virtual void DoSetup (void)
setup function for TimeSimpleTestCase.
virtual void DoTeardown (void)
Does the tear down for TimeSimpleTestCase.
virtual void DoTimeOperations (void)
Tests the Time Operations.
template<typename T >
void TestDivision (Time t, Time expected, T val, const std::string &msg)
Helper function to handle boilerplate code for division tests.
void TestDivisionByDecimalTypes ()
Test dividing a Time instance by various decimal types.
void TestDivisionByIntegerTypes ()
Test dividing a Time instance by various integer types.
template<typename T >
void TestMultiplication (Time t, Time expected, T val, const std::string &msg)
Helper function to handle boilerplate code for multiplication tests.
void TestMultiplicationByDecimalTypes ()
Test multiplying a Time instance by various decimal types.
void TestMultiplicationByIntegerTypes ()
Test multiplying a Time instance by various integer types.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
time simple test case, Checks the basic operations on time
Definition at line 39 of file time-test-suite.cc.
Constructor & Destructor Documentation
TimeSimpleTestCase()
TimeSimpleTestCase::TimeSimpleTestCase ()
constructor for TimeSimpleTestCase.
Definition at line 115 of file time-test-suite.cc.
Member Function Documentation
DoRun()
void TimeSimpleTestCase::DoRun (void) private virtual
Runs the Simple Time test case.
Implements ns3::TestCase.
Definition at line 158 of file time-test-suite.cc.
References ns3::Days(), DoTimeOperations(), ns3::FemtoSeconds(), ns3::Time::GetInteger(), ns3::Time::GetNanoSeconds(), ns3::Hours(), ns3::MicroSeconds(), ns3::MilliSeconds(), ns3::Minutes(), ns3::NanoSeconds(), NS_TEST_ASSERT_MSG_EQ, NS_TEST_ASSERT_MSG_EQ_TOL, ns3::PicoSeconds(), ns3::Seconds(), and ns3::Years().
DoSetup()
void TimeSimpleTestCase::DoSetup (void) private virtual
setup function for TimeSimpleTestCase.
Reimplemented from ns3::TestCase.
Definition at line 120 of file time-test-suite.cc.
DoTeardown()
void TimeSimpleTestCase::DoTeardown (void) private virtual
Does the tear down for TimeSimpleTestCase.
Reimplemented from ns3::TestCase.
Definition at line 207 of file time-test-suite.cc.
DoTimeOperations()
void TimeSimpleTestCase::DoTimeOperations (void) private virtual
Tests the Time Operations.
Definition at line 123 of file time-test-suite.cc.
References ns3::Div(), NS_TEST_ASSERT_MSG_EQ, ns3::Rem(), TestDivisionByDecimalTypes(), TestDivisionByIntegerTypes(), TestMultiplicationByDecimalTypes(), and TestMultiplicationByIntegerTypes().
Referenced by DoRun().
TestDivision()
template<typename T > void TimeSimpleTestCase::TestDivision (Time t, Time expected, T val, const std::string & msg) private
Helper function to handle boilerplate code for division tests.
Template Parameters
T type of division value
Parameters
t Time value to divide
expected Expected result of the divsion
val Value to divide by
msg Error message to print if test fails
Definition at line 278 of file time-test-suite.cc.
References NS_TEST_ASSERT_MSG_EQ.
Referenced by TestDivisionByDecimalTypes(), and TestDivisionByIntegerTypes().
TestDivisionByDecimalTypes()
void TimeSimpleTestCase::TestDivisionByDecimalTypes () private
Test dividing a Time instance by various decimal types.
Definition at line 318 of file time-test-suite.cc.
References ns3::Seconds(), and TestDivision().
Referenced by DoTimeOperations().
TestDivisionByIntegerTypes()
void TimeSimpleTestCase::TestDivisionByIntegerTypes () private
Test dividing a Time instance by various integer types.
Definition at line 286 of file time-test-suite.cc.
References ns3::Time::GetTimeStep(), ns3::Seconds(), and TestDivision().
Referenced by DoTimeOperations().
TestMultiplication()
template<typename T > void TimeSimpleTestCase::TestMultiplication (Time t, Time expected, T val, const std::string & msg) private
Helper function to handle boilerplate code for multiplication tests.
Template Parameters
T type of multiplication value
Parameters
t Time value to multiply
expected Expected result of the multiplication
val Value to multiply by
msg Error message to print if test fails
Definition at line 212 of file time-test-suite.cc.
Referenced by TestMultiplicationByDecimalTypes(), and TestMultiplicationByIntegerTypes().
TestMultiplicationByDecimalTypes()
void TimeSimpleTestCase::TestMultiplicationByDecimalTypes () private
Test multiplying a Time instance by various decimal types.
Definition at line 263 of file time-test-suite.cc.
References ns3::Time::GetDouble(), ns3::Seconds(), and TestMultiplication().
Referenced by DoTimeOperations().
TestMultiplicationByIntegerTypes()
void TimeSimpleTestCase::TestMultiplicationByIntegerTypes () private
Test multiplying a Time instance by various integer types.
Definition at line 231 of file time-test-suite.cc.
References ns3::Time::GetTimeStep(), ns3::Seconds(), and TestMultiplication().
Referenced by DoTimeOperations().
The documentation for this class was generated from the following file:
src/core/test/time-test-suite.cc