ns-3: ns3::aodv::QueueEntry Class Reference
ns3::aodv::QueueEntry Class Reference
AODV Routing
AODV Queue Entry.
#include "aodv-rqueue.h"
Public Types
typedef Ipv4RoutingProtocol::ErrorCallback ErrorCallback
IPv4 routing error callback typedef.
typedef Ipv4RoutingProtocol::UnicastForwardCallback UnicastForwardCallback
IPv4 routing unicast forward callback typedef.
Public Member Functions
QueueEntry (Ptr< const Packet > pa=0, Ipv4Header const &h=Ipv4Header(), UnicastForwardCallback ucb=UnicastForwardCallback(), ErrorCallback ecb=ErrorCallback(), Time exp=Simulator::Now())
constructor
ErrorCallback GetErrorCallback () const
Get error callback.
Time GetExpireTime () const
Get expire time.
Ipv4Header GetIpv4Header () const
Get IPv4 header.
Ptr< const Packet > GetPacket () const
Get packet from entry.
UnicastForwardCallback GetUnicastForwardCallback () const
Get unicast forward callback.
bool operator== (QueueEntry const &o) const
Compare queue entries.
void SetErrorCallback (ErrorCallback ecb)
Set error callback.
void SetExpireTime (Time exp)
Set expire time.
void SetIpv4Header (Ipv4Header h)
Set IPv4 header.
void SetPacket (Ptr< const Packet > p)
Set packet in entry.
void SetUnicastForwardCallback (UnicastForwardCallback ucb)
Set unicast forward callback.
Private Attributes
ErrorCallback m_ecb
Error callback.
Time m_expire
Expire time for queue entry.
Ipv4Header m_header
IP header.
Ptr< const Packet > m_packet
Data packet.
UnicastForwardCallback m_ucb
Unicast forward callback.
Detailed Description
AODV Queue Entry.
Definition at line 43 of file aodv-rqueue.h.
Member Typedef Documentation
ErrorCallback
typedef Ipv4RoutingProtocol::ErrorCallback ns3::aodv::QueueEntry::ErrorCallback
IPv4 routing error callback typedef.
Definition at line 49 of file aodv-rqueue.h.
UnicastForwardCallback
typedef Ipv4RoutingProtocol::UnicastForwardCallback ns3::aodv::QueueEntry::UnicastForwardCallback
IPv4 routing unicast forward callback typedef.
Definition at line 47 of file aodv-rqueue.h.
Constructor & Destructor Documentation
QueueEntry()
ns3::aodv::QueueEntry::QueueEntry (Ptr< const Packet > pa = 0, Ipv4Header const & h = Ipv4Header (), UnicastForwardCallback ucb = UnicastForwardCallback (), ErrorCallback ecb = ErrorCallback (), Time exp = Simulator::Now ()) inline
constructor
Parameters
pa the packet to add to the queue
h the Ipv4Header
ucb the UnicastForwardCallback function
ecb the ErrorCallback function
exp the expiration time
Definition at line 59 of file aodv-rqueue.h.
Member Function Documentation
GetErrorCallback()
ErrorCallback ns3::aodv::QueueEntry::GetErrorCallback () const inline
Get error callback.
Returns
the error callback
Definition at line 101 of file aodv-rqueue.h.
References m_ecb.
Referenced by ns3::aodv::QueueEntryTest::DoRun(), and ns3::aodv::RequestQueue::Drop().
GetExpireTime()
Time ns3::aodv::QueueEntry::GetExpireTime () const inline
Get expire time.
Returns
the expiration time
Definition at line 157 of file aodv-rqueue.h.
References m_expire, and ns3::Simulator::Now().
Referenced by ns3::aodv::QueueEntryTest::DoRun(), and ns3::aodv::IsExpired::operator()().
GetIpv4Header()
Ipv4Header ns3::aodv::QueueEntry::GetIpv4Header () const inline
Get IPv4 header.
Returns
the IPv4 header
Definition at line 133 of file aodv-rqueue.h.
References m_header.
Referenced by ns3::aodv::QueueEntryTest::DoRun(), ns3::aodv::RequestQueue::Drop(), ns3::aodv::RequestQueue::Enqueue(), and ns3::aodv::RoutingProtocol::SendPacketFromQueue().
GetPacket()
Ptr<const Packet> ns3::aodv::QueueEntry::GetPacket () const inline
Get packet from entry.
Returns
the packet
Definition at line 117 of file aodv-rqueue.h.
References m_packet.
Referenced by ns3::aodv::QueueEntryTest::DoRun(), ns3::aodv::RequestQueue::Drop(), ns3::aodv::RequestQueue::Enqueue(), and ns3::aodv::RoutingProtocol::SendPacketFromQueue().
GetUnicastForwardCallback()
UnicastForwardCallback ns3::aodv::QueueEntry::GetUnicastForwardCallback () const inline
Get unicast forward callback.
Returns
unicast callback
Definition at line 85 of file aodv-rqueue.h.
References m_ucb.
Referenced by ns3::aodv::QueueEntryTest::DoRun(), and ns3::aodv::RoutingProtocol::SendPacketFromQueue().
operator==()
bool ns3::aodv::QueueEntry::operator== (QueueEntry const & o) const inline
Compare queue entries.
Parameters
o QueueEntry to compare
Returns
true if equal
Definition at line 75 of file aodv-rqueue.h.
References ns3::Ipv4Header::GetDestination(), m_expire, m_header, and m_packet.
SetErrorCallback()
void ns3::aodv::QueueEntry::SetErrorCallback (ErrorCallback ecb) inline
Set error callback.
Parameters
ecb The error callback
Definition at line 109 of file aodv-rqueue.h.
References m_ecb.
Referenced by ns3::aodv::QueueEntryTest::DoRun().
SetExpireTime()
void ns3::aodv::QueueEntry::SetExpireTime (Time exp) inline
Set expire time.
Parameters
exp The expiration time
Definition at line 149 of file aodv-rqueue.h.
References m_expire, and ns3::Simulator::Now().
Referenced by ns3::aodv::QueueEntryTest::DoRun(), and ns3::aodv::RequestQueue::Enqueue().
SetIpv4Header()
void ns3::aodv::QueueEntry::SetIpv4Header (Ipv4Header h) inline
Set IPv4 header.
Parameters
h the IPv4 header
Definition at line 141 of file aodv-rqueue.h.
References m_header.
Referenced by ns3::aodv::QueueEntryTest::DoRun().
SetPacket()
void ns3::aodv::QueueEntry::SetPacket (Ptr< const Packet > p) inline
Set packet in entry.
Parameters
p The packet
Definition at line 125 of file aodv-rqueue.h.
References m_packet.
SetUnicastForwardCallback()
void ns3::aodv::QueueEntry::SetUnicastForwardCallback (UnicastForwardCallback ucb) inline
Set unicast forward callback.
Parameters
ucb The unicast callback
Definition at line 93 of file aodv-rqueue.h.
References m_ucb.
Referenced by ns3::aodv::QueueEntryTest::DoRun().
Member Data Documentation
m_ecb
ErrorCallback ns3::aodv::QueueEntry::m_ecb private
Error callback.
Definition at line 170 of file aodv-rqueue.h.
Referenced by GetErrorCallback(), and SetErrorCallback().
m_expire
Time ns3::aodv::QueueEntry::m_expire private
Expire time for queue entry.
Definition at line 172 of file aodv-rqueue.h.
Referenced by GetExpireTime(), operator==(), and SetExpireTime().
m_header
Ipv4Header ns3::aodv::QueueEntry::m_header private
IP header.
Definition at line 166 of file aodv-rqueue.h.
Referenced by GetIpv4Header(), operator==(), and SetIpv4Header().
m_packet
Ptr<const Packet> ns3::aodv::QueueEntry::m_packet private
Data packet.
Definition at line 164 of file aodv-rqueue.h.
Referenced by GetPacket(), operator==(), and SetPacket().
m_ucb
UnicastForwardCallback ns3::aodv::QueueEntry::m_ucb private
Unicast forward callback.
Definition at line 168 of file aodv-rqueue.h.
Referenced by GetUnicastForwardCallback(), and SetUnicastForwardCallback().
The documentation for this class was generated from the following file:
src/aodv/model/aodv-rqueue.h