ns-3: ns3::ArpQueueDiscItem Class Reference
ns3::ArpQueueDiscItem Class Reference
Internet » IPv4 classes and sub-modules » ARP protocol. | Traffic-control
ArpQueueDiscItem is a subclass of QueueDiscItem which stores ARP packets.
#include "arp-queue-disc-item.h"
Public Member Functions
ArpQueueDiscItem (Ptr< Packet > p, const Address &addr, uint16_t protocol, const ArpHeader &header)
Create an ARP queue disc item containing an ARP packet.
virtual ~ArpQueueDiscItem ()
virtual void AddHeader (void)
Add the header to the packet.
const ArpHeader & GetHeader (void) const
virtual uint32_t GetSize (void) const
virtual uint32_t Hash (uint32_t perturbation) const
Computes the hash of the packet's 5-tuple.
virtual bool Mark (void)
Inherited from the base class, but we cannot mark ARP packets.
virtual void Print (std::ostream &os) const
Print the item contents.
Public Member Functions inherited from ns3::QueueDiscItem
QueueDiscItem (Ptr< Packet > p, const Address &addr, uint16_t protocol)
Create a queue disc item.
virtual ~QueueDiscItem ()
Address GetAddress (void) const
Get the MAC address included in this item.
uint16_t GetProtocol (void) const
Get the L3 protocol included in this item.
Time GetTimeStamp (void) const
Get the timestamp included in this item.
uint8_t GetTxQueueIndex (void) const
Get the transmission queue index included in this item.
void SetTimeStamp (Time t)
Set the timestamp included in this item.
void SetTxQueueIndex (uint8_t txq)
Set the transmission queue index to store in this item.
Public Member Functions inherited from ns3::QueueItem
QueueItem (Ptr< Packet > p)
Create a queue item containing a packet.
virtual ~QueueItem ()
Ptr< Packet > GetPacket (void) const
virtual bool GetUint8Value (Uint8Values field, uint8_t &value) const
Retrieve the value of a given field from the packet, if present.
Public Member Functions inherited from ns3::SimpleRefCount< QueueItem >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Member Functions
ArpQueueDiscItem ()
Default constructor.
ArpQueueDiscItem (const ArpQueueDiscItem &)
Copy constructor.
ArpQueueDiscItem & operator= (const ArpQueueDiscItem &)
Assignment operator.
Private Attributes
ArpHeader m_header
The ARP header.
bool m_headerAdded
True if the header has already been added to the packet.
Additional Inherited Members
Public Types inherited from ns3::QueueItem
typedef void(* TracedCallback) (Ptr< const QueueItem > item)
TracedCallback signature for Ptr<QueueItem>
enum Uint8Values { IP_DSFIELD }
1-byte fields of the packet whose value can be retrieved, if present
Detailed Description
ArpQueueDiscItem is a subclass of QueueDiscItem which stores ARP packets.
Header and payload are kept separate to allow the queue disc to hash the fields of the header, which is added to the packet when the packet is dequeued.
Definition at line 36 of file arp-queue-disc-item.h.
Constructor & Destructor Documentation
ArpQueueDiscItem() [1/3]
ns3::ArpQueueDiscItem::ArpQueueDiscItem (Ptr< Packet > p, const Address & addr, uint16_t protocol, const ArpHeader & header)
Create an ARP queue disc item containing an ARP packet.
Parameters
p the packet included in the created item.
addr the destination MAC address
protocol the protocol number
header the ARP header
Definition at line 26 of file arp-queue-disc-item.cc.
~ArpQueueDiscItem()
ns3::ArpQueueDiscItem::~ArpQueueDiscItem () virtual
Definition at line 34 of file arp-queue-disc-item.cc.
References NS_LOG_FUNCTION.
ArpQueueDiscItem() [2/3]
ns3::ArpQueueDiscItem::ArpQueueDiscItem () private
Default constructor.
Defined and unimplemented to avoid misuse
ArpQueueDiscItem() [3/3]
ns3::ArpQueueDiscItem::ArpQueueDiscItem (const ArpQueueDiscItem &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Member Function Documentation
AddHeader()
void ns3::ArpQueueDiscItem::AddHeader (void) virtual
Add the header to the packet.
Implements ns3::QueueDiscItem.
Definition at line 58 of file arp-queue-disc-item.cc.
References ns3::Packet::AddHeader(), ns3::QueueItem::GetPacket(), m_header, m_headerAdded, NS_ASSERT, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
GetHeader()
const ArpHeader & ns3::ArpQueueDiscItem::GetHeader (void) const
Returns
the header stored in this item..
Definition at line 53 of file arp-queue-disc-item.cc.
References m_header.
GetSize()
uint32_t ns3::ArpQueueDiscItem::GetSize (void) const virtual
Returns
the correct packet size (header plus payload).
Reimplemented from ns3::QueueItem.
Definition at line 39 of file arp-queue-disc-item.cc.
References ns3::QueueItem::GetPacket(), ns3::ArpHeader::GetSerializedSize(), ns3::Packet::GetSize(), m_header, m_headerAdded, NS_ASSERT, and NS_LOG_FUNCTION.
Hash()
uint32_t ns3::ArpQueueDiscItem::Hash (uint32_t perturbation) const virtual
Computes the hash of the packet's 5-tuple.
Parameters
perturbation hash perturbation value
Returns
the hash of the packet's 5-tuple
Reimplemented from ns3::QueueDiscItem.
Definition at line 91 of file arp-queue-disc-item.cc.
References ns3::ArpHeader::ARP_TYPE_REPLY, ns3::ArpHeader::ARP_TYPE_REQUEST, ns3::Address::CopyTo(), ns3::ArpHeader::GetDestinationHardwareAddress(), ns3::ArpHeader::GetDestinationIpv4Address(), ns3::Address::GetLength(), ns3::ArpHeader::GetSourceHardwareAddress(), ns3::ArpHeader::GetSourceIpv4Address(), hash, ns3::Hash32(), ns3::ArpHeader::IsRequest(), m_header, NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::Ipv4Address::Serialize().
Mark()
bool ns3::ArpQueueDiscItem::Mark (void) virtual
Inherited from the base class, but we cannot mark ARP packets.
Returns
false
Implements ns3::QueueDiscItem.
Definition at line 84 of file arp-queue-disc-item.cc.
References NS_LOG_FUNCTION.
operator=()
ArpQueueDiscItem& ns3::ArpQueueDiscItem::operator= (const ArpQueueDiscItem &) private
Assignment operator.
Defined and unimplemented to avoid misuse
Returns
Print()
void ns3::ArpQueueDiscItem::Print (std::ostream & os) const virtual
Print the item contents.
Parameters
os output stream in which the data should be printed.
Reimplemented from ns3::QueueDiscItem.
Definition at line 70 of file arp-queue-disc-item.cc.
References ns3::QueueDiscItem::GetAddress(), ns3::QueueItem::GetPacket(), ns3::QueueDiscItem::GetProtocol(), ns3::QueueDiscItem::GetTxQueueIndex(), m_header, and m_headerAdded.
Member Data Documentation
m_header
ArpHeader ns3::ArpQueueDiscItem::m_header private
The ARP header.
Definition at line 105 of file arp-queue-disc-item.h.
Referenced by AddHeader(), GetHeader(), GetSize(), Hash(), and Print().
m_headerAdded
bool ns3::ArpQueueDiscItem::m_headerAdded private
True if the header has already been added to the packet.
Definition at line 106 of file arp-queue-disc-item.h.
Referenced by AddHeader(), GetSize(), and Print().
The documentation for this class was generated from the following files:
src/internet/model/arp-queue-disc-item.h
src/internet/model/arp-queue-disc-item.cc