ns-3: ns3::PropagationLossModel Class Reference
ns3::PropagationLossModel Class Reference abstract
Propagation Models
Models the propagation loss through a transmission medium.
#include "propagation-loss-model.h"
Public Member Functions
PropagationLossModel ()
virtual ~PropagationLossModel ()
int64_t AssignStreams (int64_t stream)
If this loss model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
double CalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account all the PropagationLossModel(s) chained to the current one.
Ptr< PropagationLossModel > GetNext ()
Gets the next PropagationLossModel in the chain of loss models that act on the signal.
void SetNext (Ptr< PropagationLossModel > next)
Enables a chain of loss models to act on the signal.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
PropagationLossModel (const PropagationLossModel &)
Copy constructor.
virtual int64_t DoAssignStreams (int64_t stream)=0
Subclasses must implement this; those not using random variables can return zero.
virtual double DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const =0
Returns the Rx Power taking into account only the particular PropagationLossModel.
PropagationLossModel & operator= (const PropagationLossModel &)
Copy constructor.
Private Attributes
Ptr< PropagationLossModel > m_next
Next propagation loss model in the list.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Models the propagation loss through a transmission medium.
Calculate the receive power (dbm) from a transmit power (dbm) and a mobility model for the source and destination positions.
Config Paths
ns3::PropagationLossModel is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::SpectrumChannel/PropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::YansWifiChannel/PropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::LrWpanNetDevice/Channel/PropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::SpectrumChannel/PropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::YansWifiChannel/PropagationLossModel"
"/ChannelList/[i]/$ns3::SpectrumChannel/PropagationLossModel"
"/ChannelList/[i]/$ns3::YansWifiChannel/PropagationLossModel"
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 40 bytes (on a 64-bit architecture).
Definition at line 49 of file propagation-loss-model.h.
Constructor & Destructor Documentation
PropagationLossModel() [1/2]
ns3::PropagationLossModel::PropagationLossModel ()
Definition at line 51 of file propagation-loss-model.cc.
~PropagationLossModel()
ns3::PropagationLossModel::~PropagationLossModel () virtual
Definition at line 56 of file propagation-loss-model.cc.
PropagationLossModel() [2/2]
ns3::PropagationLossModel::PropagationLossModel (const PropagationLossModel &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Member Function Documentation
AssignStreams()
int64_t ns3::PropagationLossModel::AssignStreams (int64_t stream)
If this loss model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
Return the number of streams (possibly zero) that have been assigned. If there are PropagationLossModels chained together, this method will also assign streams to the downstream models.
Parameters
stream
Returns
the number of stream indices assigned by this model
Definition at line 86 of file propagation-loss-model.cc.
References AssignStreams(), DoAssignStreams(), and m_next.
Referenced by AssignStreams(), and ns3::YansWifiChannel::AssignStreams().
CalcRxPower()
double ns3::PropagationLossModel::CalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account all the PropagationLossModel(s) chained to the current one.
Parameters
txPowerDbm current transmission power (in dBm)
a the mobility model of the source
b the mobility model of the destination
Returns
the reception power after adding/multiplying propagation loss (in dBm)
Definition at line 73 of file propagation-loss-model.cc.
References CalcRxPower(), DoCalcRxPower(), and m_next.
Referenced by CalcRxPower(), ComputeSnr(), MatrixPropagationLossModelTestCase::DoRun(), ThreeGppV2vUrbanPropagationLossModelTestCase::DoRun(), ThreeGppV2vHighwayPropagationLossModelTestCase::DoRun(), ThreeGppShadowingTestCase::EvaluateLoss(), JakesPropagationExample::Next(), ns3::YansWifiChannel::Send(), ns3::SimpleOfdmWimaxChannel::Send(), ns3::MultiModelSpectrumChannel::StartTx(), ns3::SingleModelSpectrumChannel::StartTx(), TestDeterministic(), TestDeterministicByTime(), and TestProbabilistic().
DoAssignStreams()
virtual int64_t ns3::PropagationLossModel::DoAssignStreams (int64_t stream) private pure virtual
Subclasses must implement this; those not using random variables can return zero.
Implemented in ns3::ThreeGppUmaPropagationLossModel, ns3::ThreeGppPropagationLossModel, ns3::RangePropagationLossModel, ns3::MatrixPropagationLossModel, ns3::FixedRssLossModel, ns3::NakagamiPropagationLossModel, ns3::ThreeLogDistancePropagationLossModel, ns3::LogDistancePropagationLossModel, ns3::TwoRayGroundPropagationLossModel, ns3::FriisPropagationLossModel, ns3::RandomPropagationLossModel, ns3::OkumuraHataPropagationLossModel, ns3::Kun2600MhzPropagationLossModel, ns3::JakesPropagationLossModel, ns3::ItuR1411NlosOverRooftopPropagationLossModel, ns3::ItuR1411LosPropagationLossModel, ns3::Cost231PropagationLossModel, ns3::ItuR1238PropagationLossModel, and ns3::BuildingsPropagationLossModel.
Referenced by AssignStreams().
DoCalcRxPower()
virtual double ns3::PropagationLossModel::DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const private pure virtual
Returns the Rx Power taking into account only the particular PropagationLossModel.
Parameters
txPowerDbm current transmission power (in dBm)
a the mobility model of the source
b the mobility model of the destination
Returns
the reception power after adding/multiplying propagation loss (in dBm)
Implemented in ns3::ThreeGppPropagationLossModel, ns3::RangePropagationLossModel, ns3::MatrixPropagationLossModel, ns3::FixedRssLossModel, ns3::NakagamiPropagationLossModel, ns3::ThreeLogDistancePropagationLossModel, ns3::LogDistancePropagationLossModel, ns3::TwoRayGroundPropagationLossModel, ns3::FriisPropagationLossModel, ns3::RandomPropagationLossModel, ns3::OkumuraHataPropagationLossModel, ns3::Kun2600MhzPropagationLossModel, ns3::JakesPropagationLossModel, ns3::ItuR1411NlosOverRooftopPropagationLossModel, ns3::ItuR1411LosPropagationLossModel, ns3::Cost231PropagationLossModel, ns3::ItuR1238PropagationLossModel, and ns3::BuildingsPropagationLossModel.
Referenced by CalcRxPower().
GetNext()
Ptr< PropagationLossModel > ns3::PropagationLossModel::GetNext (void)
Gets the next PropagationLossModel in the chain of loss models that act on the signal.
Returns
The next PropagationLossModel in the chain
This method of chaining propagation loss models only works commutatively if the propagation loss of all models in the chain are independent of transmit power.
Definition at line 67 of file propagation-loss-model.cc.
References m_next.
GetTypeId()
TypeId ns3::PropagationLossModel::GetTypeId (void) static
Get the type ID.
Get the type ID.
Returns
the object TypeId
Definition at line 42 of file propagation-loss-model.cc.
References ns3::TypeId::SetParent().
operator=()
PropagationLossModel& ns3::PropagationLossModel::operator= (const PropagationLossModel &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Returns
SetNext()
void ns3::PropagationLossModel::SetNext (Ptr< PropagationLossModel > next)
Enables a chain of loss models to act on the signal.
Parameters
next The next PropagationLossModel to add to the chain
This method of chaining propagation loss models only works commutatively if the propagation loss of all models in the chain are independent of transmit power.
Definition at line 61 of file propagation-loss-model.cc.
References m_next.
Referenced by ns3::SpectrumChannelHelper::AddPropagationLoss(), ns3::SpectrumChannel::AddPropagationLossModel(), and ns3::YansWifiChannelHelper::Create().
Member Data Documentation
m_next
Ptr<PropagationLossModel> ns3::PropagationLossModel::m_next private
Next propagation loss model in the list.
Definition at line 143 of file propagation-loss-model.h.
Referenced by AssignStreams(), CalcRxPower(), GetNext(), and SetNext().
The documentation for this class was generated from the following files:
src/propagation/model/propagation-loss-model.h
src/propagation/model/propagation-loss-model.cc