ns-3: UanExperiment Class Reference
UanExperiment Class Reference
This example shows the usage of UDP over 6LoWPAN to transfer data.
Public Member Functions
UanExperiment ()
UanExperiment ()
UanExperiment ()
UanExperiment ()
void Prepare ()
Prepare the experiment.
void Prepare ()
Prepare the experiment.
void Prepare ()
Prepare the experiment.
void Prepare ()
Prepare the experiment.
void PrintReceivedPacket (Ptr< Socket > socket)
Print the received packet.
void PrintReceivedPacket (Ptr< Socket > socket)
Print the received packet.
void PrintReceivedPacket (Ptr< Socket > socket)
Print the received packet.
void PrintReceivedPacket (Ptr< Socket > socket)
Print the received packet.
void SendPackets ()
Send a packet from all the nodes.
void SendPackets ()
Send a packet from all the nodes.
void SendPackets ()
Send a packet from all the nodes.
void SendPackets ()
Send a packet from all the nodes.
void SendSinglePacket (Ptr< Node > node, Ptr< Packet > pkt, Ipv4Address dst)
Send a packet from one of the nodes.
void SendSinglePacket (Ptr< Node > node, Ptr< Packet > pkt, Ipv6Address dst)
Send a packet from one of the nodes.
void SendSinglePacket (Ptr< Node > node, Ptr< Packet > pkt, Ipv6Address dst)
Send a packet from one of the nodes.
void SendSinglePacket (Ptr< Node > node, Ptr< Packet > pkt, Mac8Address dst)
Send a packet from one of the nodes.
void SetupApplications ()
Set the UAN nodes communication channels.
void SetupApplications ()
Set the UAN nodes communication channels.
void SetupApplications ()
Set the UAN nodes communication channels.
void SetupApplications ()
Set the UAN nodes communication channels.
void SetupCommunications ()
Set the UAN nodes communication channels.
void SetupCommunications ()
Set the UAN nodes communication channels.
void SetupCommunications ()
Set the UAN nodes communication channels.
void SetupCommunications ()
Set the UAN nodes communication channels.
void SetupEnergy ()
Set the UAN nodes energy.
void SetupEnergy ()
Set the UAN nodes energy.
void SetupEnergy ()
Set the UAN nodes energy.
void SetupEnergy ()
Set the UAN nodes energy.
void SetupPositions ()
Set the UAN nodes position.
void SetupPositions ()
Set the UAN nodes position.
void SetupPositions ()
Set the UAN nodes position.
void SetupPositions ()
Set the UAN nodes position.
void Teardown ()
Teardown the experiment.
void Teardown ()
Teardown the experiment.
void Teardown ()
Teardown the experiment.
void Teardown ()
Teardown the experiment.
Private Attributes
NodeContainer m_nodes
UAN nodes.
std::map< Ptr< Node >, Ptr< Socket > > m_sockets
send and receive sockets
Detailed Description
This example shows the usage of UDP over 6LoWPAN to transfer data.
This example shows the usage of raw packets transfer data.
This example shows the usage of UDP over IPv6 to transfer data.
This example shows the usage of UDP over IPv4 to transfer data.
Two nodes are sending their remaining energy percentage (1 byte) to a gateway node, that prints the received data. The transmissions are scheduled at random times to avoid collisions
Definition at line 47 of file uan-6lowpan-example.cc.
Constructor & Destructor Documentation
UanExperiment() [1/4]
UanExperiment::UanExperiment ()
Definition at line 107 of file uan-6lowpan-example.cc.
UanExperiment() [2/4]
UanExperiment::UanExperiment ()
UanExperiment() [3/4]
UanExperiment::UanExperiment ()
UanExperiment() [4/4]
UanExperiment::UanExperiment ()
Member Function Documentation
Prepare() [1/4]
void UanExperiment::Prepare ()
Prepare the experiment.
Definition at line 233 of file uan-6lowpan-example.cc.
Prepare() [2/4]
void UanExperiment::Prepare ()
Prepare the experiment.
Prepare() [3/4]
void UanExperiment::Prepare ()
Prepare the experiment.
Prepare() [4/4]
void UanExperiment::Prepare ()
Prepare the experiment.
PrintReceivedPacket() [1/4]
void UanExperiment::PrintReceivedPacket (Ptr< Socket > socket)
Print the received packet.
Parameters
socket The receiving socket
Definition at line 167 of file uan-6lowpan-example.cc.
References ns3::Inet6SocketAddress::ConvertFrom(), ns3::Packet::CopyData(), ns3::Socket::GetRxAvailable(), ns3::Inet6SocketAddress::IsMatchingType(), ns3::Simulator::Now(), NS_LOG_UNCOND, and ns3::Socket::RecvFrom().
Referenced by SetupApplications().
PrintReceivedPacket() [2/4]
void UanExperiment::PrintReceivedPacket (Ptr< Socket > socket)
Print the received packet.
Parameters
socket The receiving socket
PrintReceivedPacket() [3/4]
void UanExperiment::PrintReceivedPacket (Ptr< Socket > socket)
Print the received packet.
Parameters
socket The receiving socket
PrintReceivedPacket() [4/4]
void UanExperiment::PrintReceivedPacket (Ptr< Socket > socket)
Print the received packet.
Parameters
socket The receiving socket
SendPackets() [1/4]
void UanExperiment::SendPackets ()
Send a packet from all the nodes.
Definition at line 204 of file uan-6lowpan-example.cc.
References ns3::Ipv6InterfaceAddress::GetAddress(), ns3::Ipv6L3Protocol::GetAddress(), ns3::UniformRandomVariable::GetValue(), ns3::Hours(), ns3::Simulator::Schedule(), ns3::Seconds(), and SendSinglePacket().
SendPackets() [2/4]
void UanExperiment::SendPackets ()
Send a packet from all the nodes.
SendPackets() [3/4]
void UanExperiment::SendPackets ()
Send a packet from all the nodes.
SendPackets() [4/4]
void UanExperiment::SendPackets ()
Send a packet from all the nodes.
SendSinglePacket() [1/4]
void UanExperiment::SendSinglePacket (Ptr< Node > node, Ptr< Packet > pkt, Ipv4Address dst)
Send a packet from one of the nodes.
Parameters
node The sending node
pkt The packet
dst the destination
Definition at line 217 of file uan-ipv4-example.cc.
References ns3::Simulator::Now(), and NS_LOG_UNCOND.
SendSinglePacket() [2/4]
void UanExperiment::SendSinglePacket (Ptr< Node > node, Ptr< Packet > pkt, Ipv6Address dst)
Send a packet from one of the nodes.
Parameters
node The sending node
pkt The packet
dst the destination
Definition at line 225 of file uan-6lowpan-example.cc.
References ns3::Ipv6Address::ConvertFrom(), ns3::Simulator::Now(), and NS_LOG_UNCOND.
Referenced by SendPackets().
SendSinglePacket() [3/4]
void UanExperiment::SendSinglePacket (Ptr< Node > node, Ptr< Packet > pkt, Ipv6Address dst)
Send a packet from one of the nodes.
Parameters
node The sending node
pkt The packet
dst the destination
SendSinglePacket() [4/4]
void UanExperiment::SendSinglePacket (Ptr< Node > node, Ptr< Packet > pkt, Mac8Address dst)
Send a packet from one of the nodes.
Parameters
node The sending node
pkt The packet
dst the destination
Definition at line 209 of file uan-raw-example.cc.
References ns3::Node::GetDevice(), ns3::Simulator::Now(), NS_LOG_UNCOND, ns3::PacketSocketAddress::SetPhysicalAddress(), ns3::PacketSocketAddress::SetProtocol(), and ns3::PacketSocketAddress::SetSingleDevice().
SetupApplications() [1/4]
void UanExperiment::SetupApplications ()
Set the UAN nodes communication channels.
Definition at line 186 of file uan-6lowpan-example.cc.
References ns3::Socket::CreateSocket(), ns3::Ipv6Address::GetAny(), ns3::TypeId::LookupByName(), ns3::MakeCallback(), and PrintReceivedPacket().
SetupApplications() [2/4]
void UanExperiment::SetupApplications ()
Set the UAN nodes communication channels.
SetupApplications() [3/4]
void UanExperiment::SetupApplications ()
Set the UAN nodes communication channels.
SetupApplications() [4/4]
void UanExperiment::SetupApplications ()
Set the UAN nodes communication channels.
SetupCommunications() [1/4]
void UanExperiment::SetupCommunications ()
Set the UAN nodes communication channels.
Definition at line 131 of file uan-6lowpan-example.cc.
References ns3::EnergySourceContainer::Add(), ns3::Ipv6AddressHelper::Assign(), ns3::EnergySourceContainer::Begin(), ns3::Ipv6InterfaceContainer::Begin(), third::channel, ns3::EnergySourceContainer::Get(), ns3::Object::GetObject(), ns3::SixLowPanHelper::Install(), ns3::UanHelper::Install(), ns3::DeviceEnergyModelHelper::Install(), ns3::InternetStackHelper::Install(), ns3::Seconds(), and ns3::Ipv6AddressHelper::SetBase().
SetupCommunications() [2/4]
void UanExperiment::SetupCommunications ()
Set the UAN nodes communication channels.
SetupCommunications() [3/4]
void UanExperiment::SetupCommunications ()
Set the UAN nodes communication channels.
SetupCommunications() [4/4]
void UanExperiment::SetupCommunications ()
Set the UAN nodes communication channels.
SetupEnergy() [1/4]
void UanExperiment::SetupEnergy ()
Set the UAN nodes energy.
Definition at line 123 of file uan-6lowpan-example.cc.
References ns3::EnergySourceHelper::Install(), and ns3::BasicEnergySourceHelper::Set().
SetupEnergy() [2/4]
void UanExperiment::SetupEnergy ()
Set the UAN nodes energy.
SetupEnergy() [3/4]
void UanExperiment::SetupEnergy ()
Set the UAN nodes energy.
SetupEnergy() [4/4]
void UanExperiment::SetupEnergy ()
Set the UAN nodes energy.
SetupPositions() [1/4]
void UanExperiment::SetupPositions ()
Set the UAN nodes position.
Definition at line 112 of file uan-6lowpan-example.cc.
References ns3::MobilityHelper::Install(), ns3::MobilityHelper::SetMobilityModel(), and SetPosition().
SetupPositions() [2/4]
void UanExperiment::SetupPositions ()
Set the UAN nodes position.
SetupPositions() [3/4]
void UanExperiment::SetupPositions ()
Set the UAN nodes position.
SetupPositions() [4/4]
void UanExperiment::SetupPositions ()
Set the UAN nodes position.
Teardown() [1/4]
void UanExperiment::Teardown ()
Teardown the experiment.
Definition at line 244 of file uan-6lowpan-example.cc.
References ns3::Socket::Close().
Teardown() [2/4]
void UanExperiment::Teardown ()
Teardown the experiment.
Teardown() [3/4]
void UanExperiment::Teardown ()
Teardown the experiment.
Teardown() [4/4]
void UanExperiment::Teardown ()
Teardown the experiment.
Member Data Documentation
m_nodes
NodeContainer UanExperiment::m_nodes private
UAN nodes.
Definition at line 102 of file uan-6lowpan-example.cc.
m_sockets
std::map< Ptr< Node >, Ptr< Socket > > UanExperiment::m_sockets private
send and receive sockets
Definition at line 103 of file uan-6lowpan-example.cc.
The documentation for this class was generated from the following files:
src/uan/examples/uan-6lowpan-example.cc
src/uan/examples/uan-ipv4-example.cc
src/uan/examples/uan-ipv6-example.cc
src/uan/examples/uan-raw-example.cc