ns-3: ns3::LteRlcUm Class Reference
ns3::LteRlcUm Class Reference
LTE RLC Unacknowledged Mode (UM), see 3GPP TS 36.322.
#include "lte-rlc-um.h"
Classes
struct TxPdu
Store an incoming (from layer above us) PDU, waiting to transmit it.
Public Member Functions
LteRlcUm ()
virtual ~LteRlcUm ()
virtual void DoDispose ()
Destructor implementation.
virtual void DoNotifyHarqDeliveryFailure ()
Notify HARQ delivery failure.
virtual void DoNotifyTxOpportunity (LteMacSapUser::TxOpportunityParameters txOpParams)
MAC SAP.
virtual void DoReceivePdu (LteMacSapUser::ReceivePduParameters rxPduParams)
Receive PDU function.
virtual void DoTransmitPdcpPdu (Ptr< Packet > p)
RLC SAP.
Public Member Functions inherited from ns3::LteRlc
LteRlc ()
virtual ~LteRlc ()
LteMacSapUser * GetLteMacSapUser ()
LteRlcSapProvider * GetLteRlcSapProvider ()
void SetLcId (uint8_t lcId)
void SetLteMacSapProvider (LteMacSapProvider *s)
void SetLteRlcSapUser (LteRlcSapUser *s)
void SetRnti (uint16_t rnti)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::LteRlc
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
enum ReassemblingState_t { NONE = 0 , WAITING_S0_FULL = 1 , WAITING_SI_SF = 2 }
Reassembling state.
Private Member Functions
void DoReportBufferStatus ()
Report buffer status.
void ExpireRbsTimer (void)
Expire RBS timer.
void ExpireReorderingTimer (void)
Expire reordering timer.
bool IsInsideReorderingWindow (SequenceNumber10 seqNumber)
Is inside reordering window function.
void ReassembleAndDeliver (Ptr< Packet > packet)
Reassemble and deliver function.
void ReassembleOutsideWindow (void)
Reassemble outside window.
void ReassembleSnInterval (SequenceNumber10 lowSeqNumber, SequenceNumber10 highSeqNumber)
Reassemble SN interval function.
Private Attributes
SequenceNumber10 m_expectedSeqNumber
Expected Sequence Number.
Ptr< Packet > m_keepS0
keep S0
uint32_t m_maxTxBufferSize
maximum transmit buffer status
EventId m_rbsTimer
RBS timer.
std::vector< Ptr< Packet > > m_reasBuffer
Reassembling buffer.
ReassemblingState_t m_reassemblingState
reassembling state
EventId m_reorderingTimer
reordering timer
Time m_reorderingTimerValue
Timers.
std::map< uint16_t, Ptr< Packet > > m_rxBuffer
Reception buffer.
std::list< Ptr< Packet > > m_sdusBuffer
List of SDUs in a packet.
SequenceNumber10 m_sequenceNumber
State variables.
std::vector< TxPdu > m_txBuffer
Transmission buffer.
uint32_t m_txBufferSize
transmit buffer size
SequenceNumber10 m_vrUh
VR(UH)
SequenceNumber10 m_vrUr
VR(UR)
SequenceNumber10 m_vrUx
VR(UX)
uint16_t m_windowSize
Constants.
Additional Inherited Members
Public Types inherited from ns3::LteRlc
typedef void(* NotifyTxTracedCallback) (uint16_t rnti, uint8_t lcid, uint32_t bytes)
TracedCallback signature for NotifyTxOpportunity events.
typedef void(* ReceiveTracedCallback) (uint16_t rnti, uint8_t lcid, uint32_t bytes, uint64_t delay)
TracedCallback signature for.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::LteRlc
uint8_t m_lcid
LCID.
LteMacSapProvider * m_macSapProvider
MAC SAP provider.
LteMacSapUser * m_macSapUser
MAC SAP user.
LteRlcSapProvider * m_rlcSapProvider
RLC SAP provider.
LteRlcSapUser * m_rlcSapUser
RLC SAP user.
uint16_t m_rnti
RNTI.
TracedCallback< uint16_t, uint8_t, uint32_t, uint64_t > m_rxPdu
Used to inform of a PDU reception from the MAC SAP user.
TracedCallback< uint16_t, uint8_t, uint32_t > m_txPdu
Used to inform of a PDU delivery to the MAC SAP provider.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
LTE RLC Unacknowledged Mode (UM), see 3GPP TS 36.322.
Config Paths
ns3::LteRlcUm is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteEnbNetDevice/LteEnbRrc/UeMap/[i]/DataRadioBearerMap/[i]/LteRlc/$ns3::LteRlcUm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteEnbNetDevice/LteEnbRrc/UeMap/[i]/Srb0/LteRlc/$ns3::LteRlcUm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteEnbNetDevice/LteEnbRrc/UeMap/[i]/Srb1/LteRlc/$ns3::LteRlcUm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteUeNetDevice/LteUeRrc/DataRadioBearerMap/[i]/LteRlc/$ns3::LteRlcUm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteUeNetDevice/LteUeRrc/Srb0/LteRlc/$ns3::LteRlcUm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteUeNetDevice/LteUeRrc/Srb1/LteRlc/$ns3::LteRlcUm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteEnbNetDevice/LteEnbRrc/UeMap/[i]/DataRadioBearerMap/[i]/LteRlc/$ns3::LteRlcUm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteEnbNetDevice/LteEnbRrc/UeMap/[i]/Srb0/LteRlc/$ns3::LteRlcUm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteEnbNetDevice/LteEnbRrc/UeMap/[i]/Srb1/LteRlc/$ns3::LteRlcUm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteUeNetDevice/LteUeRrc/DataRadioBearerMap/[i]/LteRlc/$ns3::LteRlcUm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteUeNetDevice/LteUeRrc/Srb0/LteRlc/$ns3::LteRlcUm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteUeNetDevice/LteUeRrc/Srb1/LteRlc/$ns3::LteRlcUm"
Attributes
MaxTxBufferSize: Maximum Size of the Transmission Buffer (in Bytes)
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 10240
Flags: construct write read
ReorderingTimer: Value of the t-Reordering timer (See section 7.3 of 3GPP TS 36.322)
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+08ns
Flags: construct write read
No TraceSources are defined for this type.
TraceSources defined in parent class ns3::LteRlc
TxPDU: PDU transmission notified to the MAC.
Callback signature: ns3::LteRlc::NotifyTxTracedCallback
RxPDU: PDU received.
Callback signature: ns3::LteRlc::ReceiveTracedCallback
Size of this type is 328 bytes (on a 64-bit architecture).
Definition at line 35 of file lte-rlc-um.h.
Member Enumeration Documentation
ReassemblingState_t
enum ns3::LteRlcUm::ReassemblingState_t private
Reassembling state.
Enumerator
NONE
WAITING_S0_FULL
WAITING_SI_SF
Definition at line 151 of file lte-rlc-um.h.
Constructor & Destructor Documentation
LteRlcUm()
ns3::LteRlcUm::LteRlcUm ()
Definition at line 35 of file lte-rlc-um.cc.
References m_reassemblingState, NS_LOG_FUNCTION, and WAITING_S0_FULL.
~LteRlcUm()
ns3::LteRlcUm::~LteRlcUm () virtual
Definition at line 49 of file lte-rlc-um.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::LteRlcUm::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::LteRlc.
Definition at line 76 of file lte-rlc-um.cc.
References ns3::EventId::Cancel(), ns3::LteRlc::DoDispose(), m_rbsTimer, m_reorderingTimer, and NS_LOG_FUNCTION.
DoNotifyHarqDeliveryFailure()
void ns3::LteRlcUm::DoNotifyHarqDeliveryFailure () virtual
Notify HARQ delivery failure.
Implements ns3::LteRlc.
Definition at line 407 of file lte-rlc-um.cc.
References NS_LOG_FUNCTION.
DoNotifyTxOpportunity()
void ns3::LteRlcUm::DoNotifyTxOpportunity (LteMacSapUser::TxOpportunityParameters txOpParams) virtual
MAC SAP.
Parameters
txOpParams the LteMacSapUser::TxOpportunityParameters
Implements ns3::LteRlc.
Definition at line 127 of file lte-rlc-um.cc.
References ns3::Packet::AddAtEnd(), ns3::Packet::AddByteTag(), ns3::Packet::AddHeader(), ns3::Packet::AddPacketTag(), ns3::LteMacSapUser::TxOpportunityParameters::bytes, ns3::EventId::Cancel(), ns3::LteMacSapProvider::TransmitPduParameters::componentCarrierId, ns3::LteMacSapUser::TxOpportunityParameters::componentCarrierId, ns3::Packet::CreateFragment(), ns3::LteRlcHeader::DATA_FIELD_FOLLOWS, ns3::LteRlcHeader::E_LI_FIELDS_FOLLOWS, ExpireRbsTimer(), ns3::LteRlcHeader::FIRST_BYTE, ns3::LteRlcSduStatusTag::FIRST_SEGMENT, ns3::LteRlcSduStatusTag::FULL_SDU, ns3::LteRlcHeader::GetSerializedSize(), ns3::Packet::GetSize(), ns3::LteRlcSduStatusTag::GetStatus(), ns3::LteMacSapUser::TxOpportunityParameters::harqId, ns3::LteMacSapProvider::TransmitPduParameters::harqProcessId, ns3::LteRlcHeader::LAST_BYTE, ns3::LteRlcSduStatusTag::LAST_SEGMENT, ns3::LteMacSapProvider::TransmitPduParameters::layer, ns3::LteMacSapUser::TxOpportunityParameters::layer, ns3::LteMacSapProvider::TransmitPduParameters::lcid, ns3::LteRlc::m_lcid, ns3::LteRlc::m_macSapProvider, m_rbsTimer, ns3::LteRlc::m_rnti, m_sequenceNumber, m_txBuffer, m_txBufferSize, ns3::LteRlc::m_txPdu, ns3::LteRlcSduStatusTag::MIDDLE_SEGMENT, ns3::MilliSeconds(), min, ns3::LteRlcHeader::NO_FIRST_BYTE, ns3::LteRlcHeader::NO_LAST_BYTE, ns3::Simulator::Now(), NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::LteMacSapProvider::TransmitPduParameters::pdu, ns3::LteRlcHeader::PushExtensionBit(), ns3::LteRlcHeader::PushLengthIndicator(), ns3::Packet::RemoveAtStart(), ns3::Packet::RemovePacketTag(), ns3::LteMacSapProvider::TransmitPduParameters::rnti, ns3::Simulator::Schedule(), ns3::LteRlcHeader::SetFramingInfo(), ns3::LteRlcHeader::SetSequenceNumber(), ns3::LteRlcSduStatusTag::SetStatus(), and ns3::LteMacSapProvider::TransmitPdu().
DoReceivePdu()
void ns3::LteRlcUm::DoReceivePdu (LteMacSapUser::ReceivePduParameters params) virtual
Receive PDU function.
Parameters
params the LteMacSapUser::ReceivePduParameters
Implements ns3::LteRlc.
Definition at line 413 of file lte-rlc-um.cc.
References ns3::EventId::Cancel(), ExpireReorderingTimer(), ns3::Packet::FindFirstMatchingByteTag(), ns3::Time::GetNanoSeconds(), ns3::RlcTag::GetSenderTimestamp(), ns3::LteRlcHeader::GetSequenceNumber(), ns3::Packet::GetSize(), ns3::SequenceNumber10::GetValue(), IsInsideReorderingWindow(), ns3::EventId::IsRunning(), ns3::LteRlc::m_lcid, m_reorderingTimer, m_reorderingTimerValue, ns3::LteRlc::m_rnti, m_rxBuffer, ns3::LteRlc::m_rxPdu, m_vrUh, m_vrUr, m_vrUx, m_windowSize, ns3::Simulator::Now(), NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::LteMacSapUser::ReceivePduParameters::p, ns3::Packet::PeekHeader(), ReassembleOutsideWindow(), ReassembleSnInterval(), ns3::Simulator::Schedule(), and ns3::SequenceNumber10::SetModulusBase().
DoReportBufferStatus()
void ns3::LteRlcUm::DoReportBufferStatus (void) private
Report buffer status.
Definition at line 1124 of file lte-rlc-um.cc.
References ns3::Time::GetMilliSeconds(), ns3::LteMacSapProvider::ReportBufferStatusParameters::lcid, ns3::LteRlc::m_lcid, ns3::LteRlc::m_macSapProvider, ns3::LteRlc::m_rnti, m_txBuffer, m_txBufferSize, ns3::Simulator::Now(), NS_LOG_LOGIC, ns3::LteMacSapProvider::ReportBufferStatus(), ns3::LteMacSapProvider::ReportBufferStatusParameters::retxQueueHolDelay, ns3::LteMacSapProvider::ReportBufferStatusParameters::retxQueueSize, ns3::LteMacSapProvider::ReportBufferStatusParameters::rnti, ns3::LteMacSapProvider::ReportBufferStatusParameters::statusPduSize, ns3::LteMacSapProvider::ReportBufferStatusParameters::txQueueHolDelay, and ns3::LteMacSapProvider::ReportBufferStatusParameters::txQueueSize.
Referenced by DoTransmitPdcpPdu(), and ExpireRbsTimer().
DoTransmitPdcpPdu()
void ns3::LteRlcUm::DoTransmitPdcpPdu (Ptr< Packet > p) virtual
RLC SAP.
Parameters
p packet
Store PDCP PDU
Report Buffer Status
Implements ns3::LteRlc.
Definition at line 90 of file lte-rlc-um.cc.
References ns3::Packet::AddPacketTag(), ns3::EventId::Cancel(), DoReportBufferStatus(), ns3::LteRlcSduStatusTag::FULL_SDU, ns3::Packet::GetSize(), ns3::LteRlc::m_lcid, m_maxTxBufferSize, m_rbsTimer, ns3::LteRlc::m_rnti, m_txBuffer, m_txBufferSize, ns3::Simulator::Now(), NS_LOG_FUNCTION, NS_LOG_LOGIC, and ns3::LteRlcSduStatusTag::SetStatus().
ExpireRbsTimer()
void ns3::LteRlcUm::ExpireRbsTimer (void) private
Expire RBS timer.
Definition at line 1190 of file lte-rlc-um.cc.
References DoReportBufferStatus(), m_rbsTimer, m_txBuffer, ns3::MilliSeconds(), NS_LOG_LOGIC, and ns3::Simulator::Schedule().
Referenced by DoNotifyTxOpportunity().
ExpireReorderingTimer()
void ns3::LteRlcUm::ExpireReorderingTimer (void) private
Expire reordering timer.
Definition at line 1151 of file lte-rlc-um.cc.
References ns3::SequenceNumber10::GetValue(), ns3::LteRlc::m_lcid, m_reorderingTimer, m_reorderingTimerValue, ns3::LteRlc::m_rnti, m_rxBuffer, m_vrUh, m_vrUr, m_vrUx, NS_LOG_FUNCTION, NS_LOG_LOGIC, ReassembleSnInterval(), and ns3::Simulator::Schedule().
Referenced by DoReceivePdu().
GetTypeId()
TypeId ns3::LteRlcUm::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 55 of file lte-rlc-um.cc.
References m_maxTxBufferSize, m_reorderingTimerValue, ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeUintegerAccessor(), ns3::MilliSeconds(), and ns3::TypeId::SetParent().
Referenced by ns3::LteUeRrc::ApplyRadioResourceConfigDedicated(), and ns3::LteEnbRrc::GetRlcType().
IsInsideReorderingWindow()
bool ns3::LteRlcUm::IsInsideReorderingWindow (SequenceNumber10 seqNumber) private
Is inside reordering window function.
Parameters
seqNumber the sequence number
Returns
true if inside the window
Definition at line 577 of file lte-rlc-um.cc.
References m_vrUh, m_windowSize, NS_LOG_FUNCTION, NS_LOG_LOGIC, and ns3::SequenceNumber10::SetModulusBase().
Referenced by DoReceivePdu(), and ReassembleOutsideWindow().
ReassembleAndDeliver()
void ns3::LteRlcUm::ReassembleAndDeliver (Ptr< Packet > packet) private
Reassemble and deliver function.
Parameters
packet the packet
Deliver one or multiple PDUs
Deliver full PDUs
Keep S0
Discard SI or SN
Deliver zero, one or multiple PDUs
Discard SI or SN
Deliver zero, one or multiple PDUs
Keep S0
ERROR: Transition not possible
Deliver (Kept)S0 + SN
Deliver zero, one or multiple PDUs
Keep SI
Deliver (Kept)S0 + SN
Deliver zero, one or multiple PDUs
Keep S0
ERROR: Transition not possible
Deliver one or multiple PDUs
Deliver full PDUs
Keep S0
Discard SN
Deliver zero, one or multiple PDUs
Discard SI or SN
Deliver zero, one or multiple PDUs
Keep S0
ERROR: Transition not possible
Discard S0
Deliver one or multiple PDUs
Discard S0
Deliver zero, one or multiple PDUs
Keep S0
Discard S0
Discard SI or SN
Deliver zero, one or multiple PDUs
Discard S0
Discard SI or SN
Deliver zero, one or multiple PDUs
Keep S0
ERROR: Transition not possible
Definition at line 600 of file lte-rlc-um.cc.
References ns3::Packet::AddAtEnd(), ns3::Packet::CreateFragment(), ns3::LteRlcHeader::FIRST_BYTE, ns3::LteRlcHeader::GetFramingInfo(), ns3::LteRlcHeader::GetSequenceNumber(), ns3::Packet::GetSize(), ns3::LteRlcHeader::LAST_BYTE, m_expectedSeqNumber, m_keepS0, m_reassemblingState, ns3::LteRlc::m_rlcSapUser, m_sdusBuffer, ns3::LteRlcHeader::NO_FIRST_BYTE, ns3::LteRlcHeader::NO_LAST_BYTE, NS_LOG_LOGIC, ns3::LteRlcHeader::PopExtensionBit(), ns3::LteRlcHeader::PopLengthIndicator(), ns3::LteRlcSapUser::ReceivePdcpPdu(), ns3::Packet::RemoveAtStart(), ns3::Packet::RemoveHeader(), WAITING_S0_FULL, and WAITING_SI_SF.
Referenced by ReassembleOutsideWindow(), and ReassembleSnInterval().
ReassembleOutsideWindow()
void ns3::LteRlcUm::ReassembleOutsideWindow (void) private
Reassemble outside window.
Definition at line 1067 of file lte-rlc-um.cc.
References IsInsideReorderingWindow(), m_rxBuffer, NS_LOG_LOGIC, and ReassembleAndDeliver().
Referenced by DoReceivePdu().
ReassembleSnInterval()
void ns3::LteRlcUm::ReassembleSnInterval (SequenceNumber10 lowSeqNumber, SequenceNumber10 highSeqNumber) private
Reassemble SN interval function.
Parameters
lowSeqNumber the low sequence number
highSeqNumber the high sequence number
Definition at line 1093 of file lte-rlc-um.cc.
References ns3::SequenceNumber10::GetValue(), m_rxBuffer, NS_LOG_LOGIC, and ReassembleAndDeliver().
Referenced by DoReceivePdu(), and ExpireReorderingTimer().
Member Data Documentation
m_expectedSeqNumber
SequenceNumber10 ns3::LteRlcUm::m_expectedSeqNumber private
Expected Sequence Number.
Definition at line 160 of file lte-rlc-um.h.
Referenced by ReassembleAndDeliver().
m_keepS0
Ptr<Packet> ns3::LteRlcUm::m_keepS0 private
keep S0
Definition at line 155 of file lte-rlc-um.h.
Referenced by ReassembleAndDeliver().
m_maxTxBufferSize
uint32_t ns3::LteRlcUm::m_maxTxBufferSize private
maximum transmit buffer status
Definition at line 98 of file lte-rlc-um.h.
Referenced by DoTransmitPdcpPdu(), and GetTypeId().
m_rbsTimer
EventId ns3::LteRlcUm::m_rbsTimer private
RBS timer.
Definition at line 146 of file lte-rlc-um.h.
Referenced by DoDispose(), DoNotifyTxOpportunity(), DoTransmitPdcpPdu(), and ExpireRbsTimer().
m_reasBuffer
std::vector< Ptr<Packet> > ns3::LteRlcUm::m_reasBuffer private
Reassembling buffer.
Definition at line 123 of file lte-rlc-um.h.
m_reassemblingState
ReassemblingState_t ns3::LteRlcUm::m_reassemblingState private
reassembling state
Definition at line 154 of file lte-rlc-um.h.
Referenced by LteRlcUm(), and ReassembleAndDeliver().
m_reorderingTimer
EventId ns3::LteRlcUm::m_reorderingTimer private
reordering timer
Definition at line 145 of file lte-rlc-um.h.
Referenced by DoDispose(), DoReceivePdu(), and ExpireReorderingTimer().
m_reorderingTimerValue
Time ns3::LteRlcUm::m_reorderingTimerValue private
Timers.
See section 7.3 in TS 36.322 reordering timer value
Definition at line 144 of file lte-rlc-um.h.
Referenced by DoReceivePdu(), ExpireReorderingTimer(), and GetTypeId().
m_rxBuffer
std::map<uint16_t, Ptr<Packet> > ns3::LteRlcUm::m_rxBuffer private
Reception buffer.
Definition at line 122 of file lte-rlc-um.h.
Referenced by DoReceivePdu(), ExpireReorderingTimer(), ReassembleOutsideWindow(), and ReassembleSnInterval().
m_sdusBuffer
std::list< Ptr<Packet> > ns3::LteRlcUm::m_sdusBuffer private
List of SDUs in a packet.
Definition at line 125 of file lte-rlc-um.h.
Referenced by ReassembleAndDeliver().
m_sequenceNumber
SequenceNumber10 ns3::LteRlcUm::m_sequenceNumber private
State variables.
See section 7.1 in TS 36.322 VT(US)
Definition at line 130 of file lte-rlc-um.h.
Referenced by DoNotifyTxOpportunity().
m_txBuffer
std::vector< TxPdu > ns3::LteRlcUm::m_txBuffer private
Transmission buffer.
Definition at line 121 of file lte-rlc-um.h.
Referenced by DoNotifyTxOpportunity(), DoReportBufferStatus(), DoTransmitPdcpPdu(), and ExpireRbsTimer().
m_txBufferSize
uint32_t ns3::LteRlcUm::m_txBufferSize private
transmit buffer size
Definition at line 99 of file lte-rlc-um.h.
Referenced by DoNotifyTxOpportunity(), DoReportBufferStatus(), and DoTransmitPdcpPdu().
m_vrUh
SequenceNumber10 ns3::LteRlcUm::m_vrUh private
VR(UH)
Definition at line 134 of file lte-rlc-um.h.
Referenced by DoReceivePdu(), ExpireReorderingTimer(), and IsInsideReorderingWindow().
m_vrUr
SequenceNumber10 ns3::LteRlcUm::m_vrUr private
VR(UR)
Definition at line 132 of file lte-rlc-um.h.
Referenced by DoReceivePdu(), and ExpireReorderingTimer().
m_vrUx
SequenceNumber10 ns3::LteRlcUm::m_vrUx private
VR(UX)
Definition at line 133 of file lte-rlc-um.h.
Referenced by DoReceivePdu(), and ExpireReorderingTimer().
m_windowSize
uint16_t ns3::LteRlcUm::m_windowSize private
Constants.
See section 7.2 in TS 36.322 windows size
Definition at line 139 of file lte-rlc-um.h.
Referenced by DoReceivePdu(), and IsInsideReorderingWindow().
The documentation for this class was generated from the following files:
src/lte/model/lte-rlc-um.h
src/lte/model/lte-rlc-um.cc