ns-3: ns3::dsr::DsrNetworkQueue Class Reference
ns3::dsr::DsrNetworkQueue Class Reference
Introspection did not find any typical Config paths.
#include "dsr-network-queue.h"
Public Member Functions
DsrNetworkQueue ()
DsrNetworkQueue (uint32_t maxLen, Time maxDelay)
Construct a DsrNetworkQueue with the given maximum length and maximum delay.
~DsrNetworkQueue ()
bool Dequeue (DsrNetworkQueueEntry &entry)
Return first found (the earliest) entry for given destination.
bool Enqueue (DsrNetworkQueueEntry &entry)
Push entry in queue, if there is no entry with the same packet and destination address in queue.
bool Find (Ipv4Address nextHop)
Try to find an entry with a particular next hop, and return true if found.
bool FindPacketWithNexthop (Ipv4Address nextHop, DsrNetworkQueueEntry &entry)
Find the packet entry with a given next hop.
void Flush (void)
Clear the queue.
Time GetMaxNetworkDelay (void) const
Return the maximum entry lifetime for this queue.
uint32_t GetMaxNetworkSize (void) const
Return the maximum queue size.
std::vector< DsrNetworkQueueEntry > & GetQueue ()
Return the current queue entry.
uint32_t GetSize ()
Number of entries.
void SetMaxNetworkDelay (Time delay)
Set the maximum entry lifetime in the queue.
void SetMaxNetworkSize (uint32_t maxSize)
Set the maximum queue size.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void Cleanup (void)
Clean the queue by removing entries that exceeded lifetime.
Private Attributes
std::vector< DsrNetworkQueueEntry > m_dsrNetworkQueue
Queue (vector) of entries.
Time m_maxDelay
Maximum entry lifetime.
uint32_t m_maxSize
Maximum queue size.
uint32_t m_size
Current queue size.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Introspection did not find any typical Config paths.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 72 bytes (on a 64-bit architecture).
Definition at line 177 of file dsr-network-queue.h.
Constructor & Destructor Documentation
DsrNetworkQueue() [1/2]
ns3::dsr::DsrNetworkQueue::DsrNetworkQueue ()
Definition at line 68 of file dsr-network-queue.cc.
References NS_LOG_FUNCTION.
DsrNetworkQueue() [2/2]
ns3::dsr::DsrNetworkQueue::DsrNetworkQueue (uint32_t maxLen, Time maxDelay)
Construct a DsrNetworkQueue with the given maximum length and maximum delay.
Parameters
maxLen Maximum queue size
maxDelay Maximum entry lifetime in the queue
Definition at line 60 of file dsr-network-queue.cc.
References NS_LOG_FUNCTION.
~DsrNetworkQueue()
ns3::dsr::DsrNetworkQueue::~DsrNetworkQueue ()
Definition at line 73 of file dsr-network-queue.cc.
References Flush(), and NS_LOG_FUNCTION.
Member Function Documentation
Cleanup()
void ns3::dsr::DsrNetworkQueue::Cleanup (void) private
Clean the queue by removing entries that exceeded lifetime.
Definition at line 168 of file dsr-network-queue.cc.
References m_dsrNetworkQueue, m_maxDelay, m_size, sample-rng-plot::n, ns3::Simulator::Now(), NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by Dequeue(), Find(), and FindPacketWithNexthop().
Dequeue()
bool ns3::dsr::DsrNetworkQueue::Dequeue (DsrNetworkQueueEntry & entry)
Return first found (the earliest) entry for given destination.
Parameters
entry pointer to the return entry
Returns
true if an entry is returned, false otherwise
Definition at line 150 of file dsr-network-queue.cc.
References Cleanup(), m_dsrNetworkQueue, m_size, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Enqueue()
bool ns3::dsr::DsrNetworkQueue::Enqueue (DsrNetworkQueueEntry & entry)
Push entry in queue, if there is no entry with the same packet and destination address in queue.
Parameters
entry packet entry
Returns
true if the given entry was put in the queue, false otherwise
Definition at line 134 of file dsr-network-queue.cc.
References m_dsrNetworkQueue, m_maxSize, m_size, ns3::Simulator::Now(), NS_LOG_FUNCTION, NS_LOG_LOGIC, and ns3::dsr::DsrNetworkQueueEntry::SetInsertedTimeStamp().
Find()
bool ns3::dsr::DsrNetworkQueue::Find (Ipv4Address nextHop)
Try to find an entry with a particular next hop, and return true if found.
Parameters
nextHop the next hop IP address
Returns
true if found
Definition at line 120 of file dsr-network-queue.cc.
References Cleanup(), and m_dsrNetworkQueue.
FindPacketWithNexthop()
bool ns3::dsr::DsrNetworkQueue::FindPacketWithNexthop (Ipv4Address nextHop, DsrNetworkQueueEntry & entry)
Find the packet entry with a given next hop.
Parameters
nextHop the IP address of the next hop
entry the DSR queue entry
Returns
true if found
Definition at line 104 of file dsr-network-queue.cc.
References Cleanup(), and m_dsrNetworkQueue.
Flush()
void ns3::dsr::DsrNetworkQueue::Flush (void)
Clear the queue.
Definition at line 202 of file dsr-network-queue.cc.
References m_dsrNetworkQueue, m_size, and NS_LOG_FUNCTION.
Referenced by ~DsrNetworkQueue().
GetMaxNetworkDelay()
Time ns3::dsr::DsrNetworkQueue::GetMaxNetworkDelay (void) const
Return the maximum entry lifetime for this queue.
Returns
the maximum entry lifetime for this queue
Definition at line 98 of file dsr-network-queue.cc.
References m_maxDelay.
GetMaxNetworkSize()
uint32_t ns3::dsr::DsrNetworkQueue::GetMaxNetworkSize (void) const
Return the maximum queue size.
Returns
the maximum queue size
Definition at line 92 of file dsr-network-queue.cc.
References m_maxSize.
GetQueue()
std::vector<DsrNetworkQueueEntry>& ns3::dsr::DsrNetworkQueue::GetQueue (void) inline
Return the current queue entry.
Returns
the current queue entry
Definition at line 268 of file dsr-network-queue.h.
References m_dsrNetworkQueue.
GetSize()
uint32_t ns3::dsr::DsrNetworkQueue::GetSize (void)
Number of entries.
Returns
the current queue size/length
Definition at line 195 of file dsr-network-queue.cc.
References m_size, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::dsr::DsrNetworkQueue::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 50 of file dsr-network-queue.cc.
References ns3::TypeId::SetParent().
SetMaxNetworkDelay()
void ns3::dsr::DsrNetworkQueue::SetMaxNetworkDelay (Time delay)
Set the maximum entry lifetime in the queue.
Parameters
delay the maximum entry lifetime
Definition at line 86 of file dsr-network-queue.cc.
References m_maxDelay.
SetMaxNetworkSize()
void ns3::dsr::DsrNetworkQueue::SetMaxNetworkSize (uint32_t maxSize)
Set the maximum queue size.
Parameters
maxSize the maximum queue size
Definition at line 80 of file dsr-network-queue.cc.
References m_maxSize.
Member Data Documentation
m_dsrNetworkQueue
std::vector<DsrNetworkQueueEntry> ns3::dsr::DsrNetworkQueue::m_dsrNetworkQueue private
Queue (vector) of entries.
Definition at line 278 of file dsr-network-queue.h.
Referenced by Cleanup(), Dequeue(), Enqueue(), Find(), FindPacketWithNexthop(), Flush(), and GetQueue().
m_maxDelay
Time ns3::dsr::DsrNetworkQueue::m_maxDelay private
Maximum entry lifetime.
Definition at line 281 of file dsr-network-queue.h.
Referenced by Cleanup(), GetMaxNetworkDelay(), and SetMaxNetworkDelay().
m_maxSize
uint32_t ns3::dsr::DsrNetworkQueue::m_maxSize private
Maximum queue size.
Definition at line 280 of file dsr-network-queue.h.
Referenced by Enqueue(), GetMaxNetworkSize(), and SetMaxNetworkSize().
m_size
uint32_t ns3::dsr::DsrNetworkQueue::m_size private
Current queue size.
Definition at line 279 of file dsr-network-queue.h.
Referenced by Cleanup(), Dequeue(), Enqueue(), Flush(), and GetSize().
The documentation for this class was generated from the following files:
src/dsr/model/dsr-network-queue.h
src/dsr/model/dsr-network-queue.cc