ns-3: ns3::BlockAckAgreement Class Reference
ns3::BlockAckAgreement Class Reference
Wifi Models
Maintains information for a block ack agreement.
#include "block-ack-agreement.h"
Public Member Functions
BlockAckAgreement (Mac48Address peer, uint8_t tid)
Constructor for BlockAckAgreement with given peer and TID.
~BlockAckAgreement ()
uint16_t GetBufferSize (void) const
Return the buffer size.
Mac48Address GetPeer (void) const
Return the peer address.
uint16_t GetStartingSequence (void) const
Return the starting sequence number.
uint16_t GetStartingSequenceControl (void) const
Return the starting sequence control.
uint8_t GetTid (void) const
Return the Traffic ID (TID).
uint16_t GetTimeout (void) const
Return the timeout.
uint16_t GetWinEnd (void) const
Return the last sequence number covered by the ack window.
bool IsAmsduSupported (void) const
Check whether A-MSDU is supported.
bool IsHtSupported (void) const
Check whether HT is supported.
bool IsImmediateBlockAck (void) const
Check whether the current ack policy is immediate BlockAck.
void SetAmsduSupport (bool supported)
Enable or disable A-MSDU support.
void SetBufferSize (uint16_t bufferSize)
Set buffer size.
void SetDelayedBlockAck (void)
Set block ack policy to delayed Ack.
void SetHtSupported (bool htSupported)
Enable or disable HT support.
void SetImmediateBlockAck (void)
Set block ack policy to immediate Ack.
void SetStartingSequence (uint16_t seq)
Set starting sequence number.
void SetStartingSequenceControl (uint16_t seq)
Set starting sequence control.
void SetTimeout (uint16_t timeout)
Set timeout.
Protected Attributes
uint8_t m_amsduSupported
Flag whether MSDU aggregation is supported.
uint8_t m_blockAckPolicy
Type of block ack: immediate or delayed.
uint16_t m_bufferSize
Buffer size.
uint8_t m_htSupported
Flag whether HT is supported.
EventId m_inactivityEvent
inactivity event
Mac48Address m_peer
Peer address.
uint16_t m_startingSeq
Starting sequence control.
uint8_t m_tid
Traffic ID.
uint16_t m_timeout
Timeout.
uint16_t m_winEnd
Ending sequence number.
Friends
class MacLow
Provide access to MacLow class.
Detailed Description
Maintains information for a block ack agreement.
Definition at line 32 of file block-ack-agreement.h.
Constructor & Destructor Documentation
BlockAckAgreement()
ns3::BlockAckAgreement::BlockAckAgreement (Mac48Address peer, uint8_t tid)
Constructor for BlockAckAgreement with given peer and TID.
Parameters
peer the peer station
tid the TID
Definition at line 29 of file block-ack-agreement.cc.
References NS_LOG_FUNCTION.
~BlockAckAgreement()
ns3::BlockAckAgreement::~BlockAckAgreement ()
Definition at line 40 of file block-ack-agreement.cc.
References ns3::EventId::Cancel(), m_inactivityEvent, and NS_LOG_FUNCTION.
Member Function Documentation
GetBufferSize()
uint16_t ns3::BlockAckAgreement::GetBufferSize (void) const
Return the buffer size.
Returns
the buffer size (in number of MPDUs)
Definition at line 113 of file block-ack-agreement.cc.
References m_bufferSize.
Referenced by GetWinEnd().
GetPeer()
Mac48Address ns3::BlockAckAgreement::GetPeer (void) const
Return the peer address.
Returns
the peer MAC address
Definition at line 106 of file block-ack-agreement.cc.
References m_peer, and NS_LOG_FUNCTION.
Referenced by ns3::MacLow::ResetBlockAckInactivityTimerIfNeeded().
GetStartingSequence()
uint16_t ns3::BlockAckAgreement::GetStartingSequence (void) const
Return the starting sequence number.
Returns
starting sequence number
Definition at line 125 of file block-ack-agreement.cc.
References m_startingSeq.
Referenced by GetWinEnd().
GetStartingSequenceControl()
uint16_t ns3::BlockAckAgreement::GetStartingSequenceControl (void) const
Return the starting sequence control.
Returns
starting sequence control
Definition at line 131 of file block-ack-agreement.cc.
References m_startingSeq.
GetTid()
uint8_t ns3::BlockAckAgreement::GetTid (void) const
Return the Traffic ID (TID).
Returns
TID
Definition at line 100 of file block-ack-agreement.cc.
References m_tid.
Referenced by ns3::MacLow::CreateBlockAckAgreement(), and ns3::MacLow::ResetBlockAckInactivityTimerIfNeeded().
GetTimeout()
uint16_t ns3::BlockAckAgreement::GetTimeout (void) const
Return the timeout.
Returns
the timeout
Definition at line 119 of file block-ack-agreement.cc.
References m_timeout.
Referenced by ns3::MacLow::CreateBlockAckAgreement(), ns3::MacLow::ResetBlockAckInactivityTimerIfNeeded(), and ns3::BlockAckManager::UpdateAgreement().
GetWinEnd()
uint16_t ns3::BlockAckAgreement::GetWinEnd (void) const
Return the last sequence number covered by the ack window.
Returns
ending sequence number
Definition at line 150 of file block-ack-agreement.cc.
References GetBufferSize(), GetStartingSequence(), and ns3::SEQNO_SPACE_SIZE.
IsAmsduSupported()
bool ns3::BlockAckAgreement::IsAmsduSupported (void) const
Check whether A-MSDU is supported.
Returns
true if A-MSDU is supported, false otherwise
Definition at line 144 of file block-ack-agreement.cc.
References m_amsduSupported.
IsHtSupported()
bool ns3::BlockAckAgreement::IsHtSupported (void) const
Check whether HT is supported.
Returns
true if HT is supported, false otherwise
Definition at line 163 of file block-ack-agreement.cc.
References m_htSupported.
IsImmediateBlockAck()
bool ns3::BlockAckAgreement::IsImmediateBlockAck (void) const
Check whether the current ack policy is immediate BlockAck.
Returns
true if the current ack policy is immediate BlockAck, false otherwise
Definition at line 138 of file block-ack-agreement.cc.
References m_blockAckPolicy.
SetAmsduSupport()
void ns3::BlockAckAgreement::SetAmsduSupport (bool supported)
Enable or disable A-MSDU support.
Parameters
supported enable or disable A-MSDU support
Definition at line 93 of file block-ack-agreement.cc.
References m_amsduSupported, and NS_LOG_FUNCTION.
Referenced by ns3::BlockAckManager::CreateAgreement(), ns3::MacLow::CreateBlockAckAgreement(), and ns3::BlockAckManager::UpdateAgreement().
SetBufferSize()
void ns3::BlockAckAgreement::SetBufferSize (uint16_t bufferSize)
Set buffer size.
Parameters
bufferSize the buffer size (in number of MPDUs)
Definition at line 47 of file block-ack-agreement.cc.
References m_bufferSize, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::BlockAckManager::CreateAgreement(), ns3::MacLow::CreateBlockAckAgreement(), OriginatorBlockAckWindowTest::DoRun(), and ns3::BlockAckManager::UpdateAgreement().
SetDelayedBlockAck()
void ns3::BlockAckAgreement::SetDelayedBlockAck (void)
Set block ack policy to delayed Ack.
Definition at line 86 of file block-ack-agreement.cc.
References m_blockAckPolicy, and NS_LOG_FUNCTION.
Referenced by ns3::BlockAckManager::CreateAgreement(), ns3::MacLow::CreateBlockAckAgreement(), and ns3::BlockAckManager::UpdateAgreement().
SetHtSupported()
void ns3::BlockAckAgreement::SetHtSupported (bool htSupported)
Enable or disable HT support.
Parameters
htSupported enable or disable HT support
Definition at line 156 of file block-ack-agreement.cc.
References m_htSupported, and NS_LOG_FUNCTION.
Referenced by ns3::BlockAckManager::CreateAgreement().
SetImmediateBlockAck()
void ns3::BlockAckAgreement::SetImmediateBlockAck (void)
Set block ack policy to immediate Ack.
Definition at line 79 of file block-ack-agreement.cc.
References m_blockAckPolicy, and NS_LOG_FUNCTION.
Referenced by ns3::BlockAckManager::CreateAgreement(), ns3::MacLow::CreateBlockAckAgreement(), and ns3::BlockAckManager::UpdateAgreement().
SetStartingSequence()
void ns3::BlockAckAgreement::SetStartingSequence (uint16_t seq)
Set starting sequence number.
Parameters
seq the starting sequence number
Definition at line 63 of file block-ack-agreement.cc.
References m_startingSeq, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::BlockAckManager::CreateAgreement(), ns3::MacLow::CreateBlockAckAgreement(), OriginatorBlockAckWindowTest::DoRun(), and ns3::BlockAckManager::UpdateAgreement().
SetStartingSequenceControl()
void ns3::BlockAckAgreement::SetStartingSequenceControl (uint16_t seq)
Set starting sequence control.
Parameters
seq the starting sequence control
Definition at line 71 of file block-ack-agreement.cc.
References m_startingSeq, NS_ASSERT, and NS_LOG_FUNCTION.
SetTimeout()
void ns3::BlockAckAgreement::SetTimeout (uint16_t timeout)
Set timeout.
Parameters
timeout the timeout value
Definition at line 56 of file block-ack-agreement.cc.
References m_timeout, NS_LOG_FUNCTION, and timeout.
Referenced by ns3::BlockAckManager::CreateAgreement(), ns3::MacLow::CreateBlockAckAgreement(), and ns3::BlockAckManager::UpdateAgreement().
Friends And Related Function Documentation
MacLow
friend class MacLow friend
Provide access to MacLow class.
Definition at line 35 of file block-ack-agreement.h.
Member Data Documentation
m_amsduSupported
uint8_t ns3::BlockAckAgreement::m_amsduSupported protected
Flag whether MSDU aggregation is supported.
Definition at line 158 of file block-ack-agreement.h.
Referenced by IsAmsduSupported(), and SetAmsduSupport().
m_blockAckPolicy
uint8_t ns3::BlockAckAgreement::m_blockAckPolicy protected
Type of block ack: immediate or delayed.
Definition at line 159 of file block-ack-agreement.h.
Referenced by IsImmediateBlockAck(), SetDelayedBlockAck(), and SetImmediateBlockAck().
m_bufferSize
uint16_t ns3::BlockAckAgreement::m_bufferSize protected
Buffer size.
Definition at line 161 of file block-ack-agreement.h.
Referenced by GetBufferSize(), ns3::OriginatorBlockAckAgreement::InitTxWindow(), and SetBufferSize().
m_htSupported
uint8_t ns3::BlockAckAgreement::m_htSupported protected
Flag whether HT is supported.
Definition at line 165 of file block-ack-agreement.h.
Referenced by IsHtSupported(), and SetHtSupported().
m_inactivityEvent
EventId ns3::BlockAckAgreement::m_inactivityEvent protected
inactivity event
Definition at line 166 of file block-ack-agreement.h.
Referenced by ~BlockAckAgreement(), ns3::MacLow::ResetBlockAckInactivityTimerIfNeeded(), and ns3::BlockAckManager::UpdateAgreement().
m_peer
Mac48Address ns3::BlockAckAgreement::m_peer protected
Peer address.
Definition at line 157 of file block-ack-agreement.h.
Referenced by GetPeer().
m_startingSeq
uint16_t ns3::BlockAckAgreement::m_startingSeq protected
Starting sequence control.
Definition at line 163 of file block-ack-agreement.h.
Referenced by GetStartingSequence(), ns3::OriginatorBlockAckAgreement::GetStartingSequence(), GetStartingSequenceControl(), ns3::OriginatorBlockAckAgreement::InitTxWindow(), SetStartingSequence(), and SetStartingSequenceControl().
m_tid
uint8_t ns3::BlockAckAgreement::m_tid protected
Traffic ID.
Definition at line 160 of file block-ack-agreement.h.
Referenced by GetTid().
m_timeout
uint16_t ns3::BlockAckAgreement::m_timeout protected
Timeout.
Definition at line 162 of file block-ack-agreement.h.
Referenced by GetTimeout(), and SetTimeout().
m_winEnd
uint16_t ns3::BlockAckAgreement::m_winEnd protected
Ending sequence number.
Definition at line 164 of file block-ack-agreement.h.
The documentation for this class was generated from the following files:
src/wifi/model/block-ack-agreement.h
src/wifi/model/block-ack-agreement.cc