ns-3: HwmpRtableTest Class Reference
HwmpRtableTest Class Reference
Mesh Device » mesh module tests | Test suites
Unit test for HwmpRtable.
Public Member Functions
HwmpRtableTest ()
virtual void DoRun ()
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void TestAddPath ()
Test add path and try to lookup after entry has expired.
void TestExpire ()
Test add path and try to lookup after entry has expired.
void TestLookup ()
Test Add apth and lookup path;.
void TestPrecursorAdd ()
Test add precursors and find precursor list in rtable.
void TestPrecursorFind ()
Test add precursors and find precursor list in rtable.
Private Attributes
Mac48Address dst
destination address
Time expire
expiration time
Mac48Address hop
hop address
uint32_t iface
interface
uint32_t metric
metric
std::vector< Mac48Address > precursors
precursors
uint32_t seqnum
sequence number
Ptr< HwmpRtable > table
tab;e
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Unit test for HwmpRtable.
Definition at line 103 of file dot11s-test-suite.cc.
Constructor & Destructor Documentation
HwmpRtableTest()
HwmpRtableTest::HwmpRtableTest ()
Definition at line 134 of file dot11s-test-suite.cc.
References precursors.
Member Function Documentation
DoRun()
void HwmpRtableTest::DoRun () virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 209 of file dot11s-test-suite.cc.
References expire, ns3::Seconds(), table, TestAddPath(), TestExpire(), TestLookup(), TestPrecursorAdd(), and TestPrecursorFind().
TestAddPath()
void HwmpRtableTest::TestAddPath () private
Test add path and try to lookup after entry has expired.
Definition at line 167 of file dot11s-test-suite.cc.
References ns3::dot11s::HwmpRtable::AddProactivePath(), ns3::dot11s::HwmpRtable::AddReactivePath(), dst, expire, hop, iface, metric, seqnum, and table.
Referenced by DoRun().
TestExpire()
void HwmpRtableTest::TestExpire () private
Test add path and try to lookup after entry has expired.
Definition at line 174 of file dot11s-test-suite.cc.
References dst, hop, iface, ns3::dot11s::HwmpRtable::LookupResult::IsValid(), ns3::dot11s::HwmpRtable::LookupProactive(), ns3::dot11s::HwmpRtable::LookupProactiveExpired(), ns3::dot11s::HwmpRtable::LookupReactive(), ns3::dot11s::HwmpRtable::LookupReactiveExpired(), metric, NS_TEST_EXPECT_MSG_EQ, seqnum, and table.
Referenced by DoRun().
TestLookup()
void HwmpRtableTest::TestLookup () private
Test Add apth and lookup path;.
Definition at line 149 of file dot11s-test-suite.cc.
References ns3::dot11s::HwmpRtable::AddProactivePath(), ns3::dot11s::HwmpRtable::AddReactivePath(), ns3::dot11s::HwmpRtable::DeleteProactivePath(), ns3::dot11s::HwmpRtable::DeleteReactivePath(), dst, expire, hop, iface, ns3::dot11s::HwmpRtable::LookupResult::IsValid(), ns3::dot11s::HwmpRtable::LookupProactive(), ns3::dot11s::HwmpRtable::LookupReactive(), metric, NS_TEST_EXPECT_MSG_EQ, seqnum, and table.
Referenced by DoRun().
TestPrecursorAdd()
void HwmpRtableTest::TestPrecursorAdd () private
Test add precursors and find precursor list in rtable.
Definition at line 186 of file dot11s-test-suite.cc.
References ns3::dot11s::HwmpRtable::AddPrecursor(), dst, iface, precursors, ns3::Seconds(), and table.
Referenced by DoRun().
TestPrecursorFind()
void HwmpRtableTest::TestPrecursorFind () private
Test add precursors and find precursor list in rtable.
Definition at line 197 of file dot11s-test-suite.cc.
References dst, ns3::dot11s::HwmpRtable::GetPrecursors(), iface, NS_TEST_EXPECT_MSG_EQ, precursors, and table.
Referenced by DoRun().
Member Data Documentation
dst
Mac48Address HwmpRtableTest::dst private
destination address
Definition at line 124 of file dot11s-test-suite.cc.
Referenced by check-style.PatchChunk::dst_len(), TestAddPath(), TestExpire(), TestLookup(), TestPrecursorAdd(), and TestPrecursorFind().
expire
Time HwmpRtableTest::expire private
expiration time
Definition at line 129 of file dot11s-test-suite.cc.
Referenced by DoRun(), TestAddPath(), and TestLookup().
hop
Mac48Address HwmpRtableTest::hop private
hop address
Definition at line 125 of file dot11s-test-suite.cc.
Referenced by TestAddPath(), TestExpire(), and TestLookup().
iface
uint32_t HwmpRtableTest::iface private
interface
Definition at line 126 of file dot11s-test-suite.cc.
Referenced by TestAddPath(), TestExpire(), TestLookup(), TestPrecursorAdd(), and TestPrecursorFind().
metric
uint32_t HwmpRtableTest::metric private
metric
Definition at line 127 of file dot11s-test-suite.cc.
Referenced by TestAddPath(), TestExpire(), and TestLookup().
precursors
std::vector<Mac48Address> HwmpRtableTest::precursors private
precursors
Definition at line 131 of file dot11s-test-suite.cc.
Referenced by HwmpRtableTest(), TestPrecursorAdd(), and TestPrecursorFind().
seqnum
uint32_t HwmpRtableTest::seqnum private
sequence number
Definition at line 128 of file dot11s-test-suite.cc.
Referenced by TestAddPath(), TestExpire(), and TestLookup().
table
Ptr<HwmpRtable> HwmpRtableTest::table private
tab;e
Definition at line 130 of file dot11s-test-suite.cc.
Referenced by DoRun(), TestAddPath(), TestExpire(), TestLookup(), TestPrecursorAdd(), and TestPrecursorFind().
The documentation for this class was generated from the following file:
src/mesh/test/dot11s/dot11s-test-suite.cc