ns-3: ns3::NullMessageSimulatorImpl Class Reference
ns3::NullMessageSimulatorImpl Class Reference
MPI Distributed Simulation
Simulator implementation using MPI and a Null Message algorithm.
#include "null-message-simulator-impl.h"
Public Member Functions
NullMessageSimulatorImpl ()
Default constructor.
~NullMessageSimulatorImpl ()
Destructor.
virtual void Cancel (const EventId &id)
Set the cancel bit on this event: the event's associated function will not be invoked when it expires.
virtual void Destroy ()
Execute the events scheduled with ScheduleDestroy().
virtual uint32_t GetContext (void) const
Get the current simulation context.
virtual Time GetDelayLeft (const EventId &id) const
Get the remaining time until this event will execute.
virtual uint64_t GetEventCount (void) const
Get the number of events executed.
virtual Time GetMaximumSimulationTime (void) const
Get the maximum representable simulation time.
virtual uint32_t GetSystemId (void) const
Get the system id of this simulator.
virtual bool IsExpired (const EventId &id) const
Check if an event has already run or been cancelled.
virtual bool IsFinished (void) const
Check if the simulation should finish.
virtual Time Now (void) const
Return the current simulation virtual time.
virtual void Remove (const EventId &id)
Remove an event from the event list.
virtual void Run (void)
Run the simulation.
virtual EventId Schedule (Time const &delay, EventImpl *event)
Schedule a future event execution (in the same context).
virtual EventId ScheduleDestroy (EventImpl *event)
Schedule an event to run at the end of the simulation, after the Stop() time or condition has been reached.
virtual EventId ScheduleNow (EventImpl *event)
Schedule an event to run at the current virtual time.
virtual void ScheduleWithContext (uint32_t context, Time const &delay, EventImpl *event)
Schedule a future event execution (in a different context).
virtual void SetScheduler (ObjectFactory schedulerFactory)
Set the Scheduler to be used to manage the event list.
virtual void Stop (Time const &delay)
Schedule the time delay until the Simulator should stop.
virtual void Stop (void)
Tell the Simulator the calling event should be the last one executed.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static NullMessageSimulatorImpl * GetInstance (void)
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::SimulatorImpl
static TypeId GetTypeId (void)
Get the registered TypeId for this class.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef std::list< EventId > DestroyEvents
Container type for the events to run at Simulator::Destroy().
Private Member Functions
Time CalculateGuaranteeTime (uint32_t systemId)
void CalculateLookAhead (void)
Calculate the lookahead allowable for this MPI task.
void CalculateSafeTime (void)
Calculate the SafeTime.
virtual void DoDispose (void)
Destructor implementation.
Time GetSafeTime (void)
Get the current SafeTime; the maximum time that events can be processed based on information received from neighboring MPI tasks.
void HandleArrivingMessagesBlocking (void)
Blocking receive of arriving messages.
void HandleArrivingMessagesNonBlocking (void)
Non blocking receive of pending messages.
Time Next (void) const
void NullMessageEventHandler (RemoteChannelBundle *bundle)
void ProcessOneEvent (void)
Process the next event on the queue.
void RescheduleNullMessageEvent (Ptr< RemoteChannelBundle > bundle)
void RescheduleNullMessageEvent (uint32_t nodeSysId)
void ScheduleNullMessageEvent (Ptr< RemoteChannelBundle > bundle)
Private Attributes
uint32_t m_currentContext
Execution context of the current event.
uint64_t m_currentTs
Timestamp of the current event.
uint32_t m_currentUid
Unique id of the current event.
DestroyEvents m_destroyEvents
The container of events to run at Destroy()
uint64_t m_eventCount
The event count.
Ptr< Scheduler > m_events
The event priority queue.
uint32_t m_myId
MPI rank.
Time m_safeTime
The time for which it is safe for this task to execute events without danger of out-of-order events.
double m_schedulerTune
Null Message performance tuning parameter.
bool m_stop
Flag calling for the end of the simulation.
uint32_t m_systemCount
MPI communicator size.
uint32_t m_uid
Next event unique id.
int m_unscheduledEvents
Number of events that have been inserted but not yet scheduled, not counting the "destroy" events; this is used for validation.
Static Private Attributes
static NullMessageSimulatorImpl * g_instance = 0
Singleton instance.
Friends
class NullMessageEvent
class NullMessageMpiInterface
class RemoteChannelBundleManager
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Simulator implementation using MPI and a Null Message algorithm.
Definition at line 51 of file null-message-simulator-impl.h.
Member Typedef Documentation
DestroyEvents
typedef std::list<EventId> ns3::NullMessageSimulatorImpl::DestroyEvents private
Container type for the events to run at Simulator::Destroy().
Definition at line 184 of file null-message-simulator-impl.h.
Constructor & Destructor Documentation
NullMessageSimulatorImpl()
ns3::NullMessageSimulatorImpl::NullMessageSimulatorImpl ()
Default constructor.
Definition at line 74 of file null-message-simulator-impl.cc.
References g_instance, ns3::MpiInterface::GetSize(), ns3::MpiInterface::GetSystemId(), m_currentContext, m_currentTs, m_currentUid, m_eventCount, m_events, m_myId, m_safeTime, m_stop, m_systemCount, m_uid, m_unscheduledEvents, ns3::Simulator::NO_CONTEXT, NS_ASSERT, NS_LOG_FUNCTION, and ns3::Seconds().
~NullMessageSimulatorImpl()
ns3::NullMessageSimulatorImpl::~NullMessageSimulatorImpl ()
Destructor.
Definition at line 101 of file null-message-simulator-impl.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CalculateGuaranteeTime()
Time ns3::NullMessageSimulatorImpl::CalculateGuaranteeTime (uint32_t systemId) private
Parameters
systemId SystemID to compute guarantee time for
Returns
Guarantee time
Calculate the guarantee time for incoming RemoteChannelBundel from task nodeSysId. No message should arrive from task nodeSysId with a receive time less than the guarantee time.
Definition at line 579 of file null-message-simulator-impl.cc.
References ns3::RemoteChannelBundleManager::Find(), GetInstance(), GetSafeTime(), ns3::Min(), Next(), and NS_ASSERT.
Referenced by ns3::NullMessageMpiInterface::SendPacket().
CalculateLookAhead()
void ns3::NullMessageSimulatorImpl::CalculateLookAhead (void) private
Calculate the lookahead allowable for this MPI task.
Basically the minimum latency on links to neighbor MPI tasks.
Add this channel to the remote channel bundle from this task to MPI task on other side of the channel.
Definition at line 141 of file null-message-simulator-impl.cc.
References ns3::RemoteChannelBundleManager::Add(), ns3::NodeContainer::Begin(), third::channel, ns3::NodeContainer::End(), ns3::RemoteChannelBundleManager::Find(), ns3::TimeValue::Get(), ns3::NodeContainer::GetGlobal(), ns3::MpiInterface::GetSize(), ns3::MpiInterface::GetSystemId(), ns3::Node::GetSystemId(), ns3::NullMessageMpiInterface::InitializeSendReceiveBuffers(), m_safeTime, and NS_LOG_FUNCTION.
Referenced by Run().
CalculateSafeTime()
void ns3::NullMessageSimulatorImpl::CalculateSafeTime (void) private
Calculate the SafeTime.
Should be called after message receives.
Definition at line 357 of file null-message-simulator-impl.cc.
References ns3::RemoteChannelBundleManager::GetSafeTime(), m_currentTs, m_safeTime, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by HandleArrivingMessagesBlocking(), and HandleArrivingMessagesNonBlocking().
Cancel()
void ns3::NullMessageSimulatorImpl::Cancel (const EventId & id) virtual
Set the cancel bit on this event: the event's associated function will not be invoked when it expires.
This method has the same visible effect as the ns3::Simulator::Remove method but its algorithmic complexity is much lower: it has O(1) complexity. This method has the exact same semantics as ns3::EventId::Cancel. Note that it is not possible to cancel events which were scheduled for the "destroy" time. Doing so will result in a program error (crash).
Parameters
[in] id the event to cancel
Implements ns3::SimulatorImpl.
Definition at line 517 of file null-message-simulator-impl.cc.
References IsExpired().
Destroy()
void ns3::NullMessageSimulatorImpl::Destroy () virtual
Execute the events scheduled with ScheduleDestroy().
This method is typically invoked at the end of a simulation to avoid false-positive reports by a leak checker. After this method has been invoked, it is actually possible to restart a new simulation with a set of calls to Simulator::Run, Simulator::Schedule and Simulator::ScheduleWithContext.
Implements ns3::SimulatorImpl.
Definition at line 121 of file null-message-simulator-impl.cc.
References ns3::MpiInterface::Destroy(), ns3::RemoteChannelBundleManager::Destroy(), m_destroyEvents, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
DoDispose()
void ns3::NullMessageSimulatorImpl::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 107 of file null-message-simulator-impl.cc.
References ns3::Object::DoDispose(), ns3::Scheduler::Event::impl, m_events, NS_LOG_FUNCTION, and ns3::SimpleRefCount< T, PARENT, DELETER >::Unref().
GetContext()
uint32_t ns3::NullMessageSimulatorImpl::GetContext (void) const virtual
Get the current simulation context.
The simulation context is the ns-3 notion of a Logical Process. Events in a single context should only modify state associated with that context. Events for objects in other contexts should be scheduled with ScheduleWithContext() to track the context switches. In other words, events in different contexts should be mutually thread safe, by not modify overlapping model state.
In circumstances where the context can't be determined, such as during object initialization, the enum value NO_CONTEXT should be used.
Returns
The current simulation context
Implements ns3::SimulatorImpl.
Definition at line 568 of file null-message-simulator-impl.cc.
References m_currentContext.
Referenced by Schedule(), and ScheduleNow().
GetDelayLeft()
Time ns3::NullMessageSimulatorImpl::GetDelayLeft (const EventId & id) const virtual
Get the remaining time until this event will execute.
Parameters
[in] id The event id to analyse.
Returns
The delay left until the input event id expires. if the event is not running, this method returns zero.
Implements ns3::SimulatorImpl.
Definition at line 471 of file null-message-simulator-impl.cc.
References IsExpired(), and m_currentTs.
GetEventCount()
uint64_t ns3::NullMessageSimulatorImpl::GetEventCount (void) const virtual
Get the number of events executed.
Returns
The total number of events executed.
Implements ns3::SimulatorImpl.
Definition at line 574 of file null-message-simulator-impl.cc.
References m_eventCount.
GetInstance()
NullMessageSimulatorImpl * ns3::NullMessageSimulatorImpl::GetInstance (void) static
Returns
singleton instance
Singleton accessor.
Definition at line 599 of file null-message-simulator-impl.cc.
References g_instance, and NS_ASSERT.
Referenced by CalculateGuaranteeTime(), ns3::RemoteChannelBundleManager::InitializeNullMessageEvents(), and ns3::NullMessageMpiInterface::SendPacket().
GetMaximumSimulationTime()
Time ns3::NullMessageSimulatorImpl::GetMaximumSimulationTime (void) const virtual
Get the maximum representable simulation time.
Returns
The maximum simulation time at which an event can be scheduled.
The returned value will always be bigger than or equal to Simulator::Now.
Implements ns3::SimulatorImpl.
Definition at line 560 of file null-message-simulator-impl.cc.
GetSafeTime()
Time ns3::NullMessageSimulatorImpl::GetSafeTime (void) private
Get the current SafeTime; the maximum time that events can be processed based on information received from neighboring MPI tasks.
Definition at line 366 of file null-message-simulator-impl.cc.
References m_safeTime.
Referenced by CalculateGuaranteeTime(), NullMessageEventHandler(), and Run().
GetSystemId()
uint32_t ns3::NullMessageSimulatorImpl::GetSystemId (void) const virtual
Get the system id of this simulator.
The system id is the identifier for this simulator instance in a distributed simulation. For MPI this is the MPI rank.
Returns
The system id for this simulator.
Implements ns3::SimulatorImpl.
Definition at line 373 of file null-message-simulator-impl.cc.
References m_myId.
GetTypeId()
TypeId ns3::NullMessageSimulatorImpl::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 60 of file null-message-simulator-impl.cc.
References m_schedulerTune, ns3::MakeDoubleAccessor(), and ns3::TypeId::SetParent().
HandleArrivingMessagesBlocking()
void ns3::NullMessageSimulatorImpl::HandleArrivingMessagesBlocking (void) private
Blocking receive of arriving messages.
Definition at line 344 of file null-message-simulator-impl.cc.
References CalculateSafeTime(), NS_LOG_FUNCTION, ns3::NullMessageMpiInterface::ReceiveMessagesBlocking(), and ns3::NullMessageMpiInterface::TestSendComplete().
Referenced by Run().
HandleArrivingMessagesNonBlocking()
void ns3::NullMessageSimulatorImpl::HandleArrivingMessagesNonBlocking (void) private
Non blocking receive of pending messages.
Definition at line 331 of file null-message-simulator-impl.cc.
References CalculateSafeTime(), NS_LOG_FUNCTION, ns3::NullMessageMpiInterface::ReceiveMessagesNonBlocking(), and ns3::NullMessageMpiInterface::TestSendComplete().
Referenced by Run().
IsExpired()
bool ns3::NullMessageSimulatorImpl::IsExpired (const EventId & id) const virtual
Check if an event has already run or been cancelled.
This method has O(1) complexity. Note that it is not possible to test for the expiration of events which were scheduled for the "destroy" time. Doing so will result in a program error (crash). An event is said to "expire" when it starts being scheduled which means that if the code executed by the event calls this function, it will get true.
Parameters
[in] id The event to test for expiration.
Returns
true if the event has expired, false otherwise.
Implements ns3::SimulatorImpl.
Definition at line 526 of file null-message-simulator-impl.cc.
References m_currentTs, m_currentUid, and m_destroyEvents.
Referenced by Cancel(), GetDelayLeft(), and Remove().
IsFinished()
bool ns3::NullMessageSimulatorImpl::IsFinished (void) const virtual
Check if the simulation should finish.
Reasons to finish are because there are no more events lefts to be scheduled, or if simulation time has already reached the "stop time" (see Simulator::Stop()).
Returns
true if no more events or stop time reached.
Implements ns3::SimulatorImpl.
Definition at line 251 of file null-message-simulator-impl.cc.
References m_events, and m_stop.
Referenced by Run().
Next()
Time ns3::NullMessageSimulatorImpl::Next (void) const private
Returns
next local event time.
Definition at line 257 of file null-message-simulator-impl.cc.
References ns3::Scheduler::Event::key, m_events, ns3::Scheduler::EventKey::m_ts, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by CalculateGuaranteeTime(), NullMessageEventHandler(), and Run().
Now()
Time ns3::NullMessageSimulatorImpl::Now (void) const virtual
Return the current simulation virtual time.
Returns
The current virtual time.
Implements ns3::SimulatorImpl.
Definition at line 465 of file null-message-simulator-impl.cc.
References m_currentTs.
NullMessageEventHandler()
void ns3::NullMessageSimulatorImpl::NullMessageEventHandler (RemoteChannelBundle * bundle) private
Parameters
bundle remote channel bundle to schedule an event for.
Null message event handler. Scheduled to send a null message for the specified bundle at regular intervals. Will canceled and rescheduled when packets are sent.
Definition at line 587 of file null-message-simulator-impl.cc.
References ns3::RemoteChannelBundle::GetDelay(), GetSafeTime(), ns3::Min(), Next(), NS_LOG_FUNCTION, ScheduleNullMessageEvent(), and ns3::NullMessageMpiInterface::SendNullMessage().
Referenced by RescheduleNullMessageEvent(), and ScheduleNullMessageEvent().
ProcessOneEvent()
void ns3::NullMessageSimulatorImpl::ProcessOneEvent (void) private
Process the next event on the queue.
Definition at line 232 of file null-message-simulator-impl.cc.
References ns3::Scheduler::Event::impl, ns3::EventImpl::Invoke(), ns3::Scheduler::Event::key, ns3::Scheduler::EventKey::m_context, m_currentContext, m_currentTs, m_currentUid, m_eventCount, m_events, ns3::Scheduler::EventKey::m_ts, ns3::Scheduler::EventKey::m_uid, m_unscheduledEvents, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, and ns3::SimpleRefCount< T, PARENT, DELETER >::Unref().
Referenced by Run().
Remove()
void ns3::NullMessageSimulatorImpl::Remove (const EventId & id) virtual
Remove an event from the event list.
This method has the same visible effect as the ns3::EventId::Cancel method but its algorithmic complexity is much higher: it has often O(log(n)) complexity, sometimes O(n), sometimes worse. Note that it is not possible to remove events which were scheduled for the "destroy" time. Doing so will result in a program error (crash).
Parameters
[in] id The event to remove from the list of scheduled events.
Implements ns3::SimulatorImpl.
Definition at line 484 of file null-message-simulator-impl.cc.
References ns3::Scheduler::Event::impl, IsExpired(), m_destroyEvents, m_events, and m_unscheduledEvents.
RescheduleNullMessageEvent() [1/2]
void ns3::NullMessageSimulatorImpl::RescheduleNullMessageEvent (Ptr< RemoteChannelBundle > bundle) private
Parameters
bundle Bundle to reschedule Null Message event for
Reschedule Null Message event for the specified RemoteChannelBundel. Existing event will be canceled.
Definition at line 279 of file null-message-simulator-impl.cc.
References ns3::Simulator::Cancel(), m_schedulerTune, NS_LOG_FUNCTION, NullMessageEventHandler(), ns3::PeekPointer(), and ns3::Simulator::Schedule().
Referenced by RescheduleNullMessageEvent(), and ns3::NullMessageMpiInterface::SendPacket().
RescheduleNullMessageEvent() [2/2]
void ns3::NullMessageSimulatorImpl::RescheduleNullMessageEvent (uint32_t nodeSysId) private
Parameters
nodeSysId SystemID to reschedule null event for
Reschedule Null Message event for the RemoteChannelBundel to the task nodeSysId. Existing event will be canceled.
Definition at line 292 of file null-message-simulator-impl.cc.
References ns3::RemoteChannelBundleManager::Find(), NS_ASSERT, NS_LOG_FUNCTION, and RescheduleNullMessageEvent().
Run()
void ns3::NullMessageSimulatorImpl::Run (void) virtual
Run the simulation.
The simulation will run until one of:
No events are present anymore
The user called Simulator::Stop
The user called Simulator::Stop with a stop time and the expiration time of the next event to be processed is greater than or equal to the stop time.
Implements ns3::SimulatorImpl.
Definition at line 303 of file null-message-simulator-impl.cc.
References CalculateLookAhead(), GetSafeTime(), HandleArrivingMessagesBlocking(), HandleArrivingMessagesNonBlocking(), ns3::RemoteChannelBundleManager::InitializeNullMessageEvents(), IsFinished(), m_stop, Next(), NS_LOG_FUNCTION, and ProcessOneEvent().
Schedule()
EventId ns3::NullMessageSimulatorImpl::Schedule (Time const & delay, EventImpl * event) virtual
Schedule a future event execution (in the same context).
Parameters
[in] delay Delay until the event expires.
[in] event The event to schedule.
Returns
A unique identifier for the newly-scheduled event.
Implements ns3::SimulatorImpl.
Definition at line 398 of file null-message-simulator-impl.cc.
References GetContext(), ns3::Time::GetTimeStep(), ns3::Scheduler::Event::impl, ns3::Time::IsPositive(), ns3::Scheduler::Event::key, ns3::Scheduler::EventKey::m_context, m_currentTs, m_events, ns3::Scheduler::EventKey::m_ts, ns3::Scheduler::EventKey::m_uid, m_uid, m_unscheduledEvents, NS_ASSERT, and NS_LOG_FUNCTION.
ScheduleDestroy()
EventId ns3::NullMessageSimulatorImpl::ScheduleDestroy (EventImpl * event) virtual
Schedule an event to run at the end of the simulation, after the Stop() time or condition has been reached.
Parameters
[in] event The event to schedule.
Returns
A unique identifier for the newly-scheduled event.
Implements ns3::SimulatorImpl.
Definition at line 454 of file null-message-simulator-impl.cc.
References m_currentTs, m_destroyEvents, m_uid, and NS_LOG_FUNCTION.
ScheduleNow()
EventId ns3::NullMessageSimulatorImpl::ScheduleNow (EventImpl * event) virtual
Schedule an event to run at the current virtual time.
Parameters
[in] event The event to schedule.
Returns
A unique identifier for the newly-scheduled event.
Implements ns3::SimulatorImpl.
Definition at line 438 of file null-message-simulator-impl.cc.
References GetContext(), ns3::Scheduler::Event::impl, ns3::Scheduler::Event::key, ns3::Scheduler::EventKey::m_context, m_currentTs, m_events, ns3::Scheduler::EventKey::m_ts, ns3::Scheduler::EventKey::m_uid, m_uid, m_unscheduledEvents, and NS_LOG_FUNCTION.
ScheduleNullMessageEvent()
void ns3::NullMessageSimulatorImpl::ScheduleNullMessageEvent (Ptr< RemoteChannelBundle > bundle) private
Parameters
bundle Bundle to schedule Null Message event for
Schedule Null Message event for the specified RemoteChannelBundle.
Definition at line 268 of file null-message-simulator-impl.cc.
References m_schedulerTune, NS_LOG_FUNCTION, NullMessageEventHandler(), ns3::PeekPointer(), and ns3::Simulator::Schedule().
Referenced by ns3::RemoteChannelBundleManager::InitializeNullMessageEvents(), and NullMessageEventHandler().
ScheduleWithContext()
void ns3::NullMessageSimulatorImpl::ScheduleWithContext (uint32_t context, Time const & delay, EventImpl * event) virtual
Schedule a future event execution (in a different context).
This method is thread-safe: it can be called from any thread.
Parameters
[in] delay Delay until the event expires.
[in] context Event context.
[in] event The event to schedule.
Returns
A unique identifier for the newly-scheduled event.
Implements ns3::SimulatorImpl.
Definition at line 418 of file null-message-simulator-impl.cc.
References ns3::Time::GetTimeStep(), ns3::Scheduler::Event::impl, ns3::Time::IsPositive(), ns3::Scheduler::Event::key, ns3::Scheduler::EventKey::m_context, m_currentTs, m_events, ns3::Scheduler::EventKey::m_ts, ns3::Scheduler::EventKey::m_uid, m_uid, m_unscheduledEvents, NS_ASSERT, and NS_LOG_FUNCTION.
SetScheduler()
void ns3::NullMessageSimulatorImpl::SetScheduler (ObjectFactory schedulerFactory) virtual
Set the Scheduler to be used to manage the event list.
Parameters
[in] schedulerFactory A new event scheduler factory.
The event scheduler can be set at any time: the events scheduled in the previous scheduler will be transferred to the new scheduler before we start to use it.
Implements ns3::SimulatorImpl.
Definition at line 214 of file null-message-simulator-impl.cc.
References ns3::ObjectFactory::Create(), m_events, and NS_LOG_FUNCTION.
Stop() [1/2]
void ns3::NullMessageSimulatorImpl::Stop (Time const & delay) virtual
Schedule the time delay until the Simulator should stop.
Force the Simulator::Run method to return to the caller when the expiration time of the next event to be processed is greater than or equal to the stop time. The stop time is relative to the current simulation time.
Parameters
[in] delay The stop time, relative to the current time.
Implements ns3::SimulatorImpl.
Definition at line 387 of file null-message-simulator-impl.cc.
References ns3::Time::GetTimeStep(), NS_LOG_FUNCTION, ns3::Simulator::Schedule(), and ns3::Simulator::Stop().
Stop() [2/2]
void ns3::NullMessageSimulatorImpl::Stop (void) virtual
Tell the Simulator the calling event should be the last one executed.
If a running event invokes this method, it will be the last event executed by the Simulator::Run method before returning to the caller.
Implements ns3::SimulatorImpl.
Definition at line 379 of file null-message-simulator-impl.cc.
References m_stop, and NS_LOG_FUNCTION.
Friends And Related Function Documentation
NullMessageEvent
friend class NullMessageEvent friend
Definition at line 96 of file null-message-simulator-impl.h.
NullMessageMpiInterface
friend class NullMessageMpiInterface friend
Definition at line 97 of file null-message-simulator-impl.h.
RemoteChannelBundleManager
friend class RemoteChannelBundleManager friend
Definition at line 98 of file null-message-simulator-impl.h.
Member Data Documentation
g_instance
NullMessageSimulatorImpl * ns3::NullMessageSimulatorImpl::g_instance = 0 static private
Singleton instance.
Definition at line 231 of file null-message-simulator-impl.h.
Referenced by NullMessageSimulatorImpl(), and GetInstance().
m_currentContext
uint32_t ns3::NullMessageSimulatorImpl::m_currentContext private
Execution context of the current event.
Definition at line 200 of file null-message-simulator-impl.h.
Referenced by NullMessageSimulatorImpl(), GetContext(), and ProcessOneEvent().
m_currentTs
uint64_t ns3::NullMessageSimulatorImpl::m_currentTs private
Timestamp of the current event.
Definition at line 198 of file null-message-simulator-impl.h.
Referenced by NullMessageSimulatorImpl(), CalculateSafeTime(), GetDelayLeft(), IsExpired(), Now(), ProcessOneEvent(), Schedule(), ScheduleDestroy(), ScheduleNow(), and ScheduleWithContext().
m_currentUid
uint32_t ns3::NullMessageSimulatorImpl::m_currentUid private
Unique id of the current event.
Definition at line 196 of file null-message-simulator-impl.h.
Referenced by NullMessageSimulatorImpl(), IsExpired(), and ProcessOneEvent().
m_destroyEvents
DestroyEvents ns3::NullMessageSimulatorImpl::m_destroyEvents private
The container of events to run at Destroy()
Definition at line 187 of file null-message-simulator-impl.h.
Referenced by Destroy(), IsExpired(), Remove(), and ScheduleDestroy().
m_eventCount
uint64_t ns3::NullMessageSimulatorImpl::m_eventCount private
The event count.
Definition at line 202 of file null-message-simulator-impl.h.
Referenced by NullMessageSimulatorImpl(), GetEventCount(), and ProcessOneEvent().
m_events
Ptr<Scheduler> ns3::NullMessageSimulatorImpl::m_events private
The event priority queue.
Definition at line 191 of file null-message-simulator-impl.h.
Referenced by NullMessageSimulatorImpl(), DoDispose(), IsFinished(), Next(), ProcessOneEvent(), Remove(), Schedule(), ScheduleNow(), ScheduleWithContext(), and SetScheduler().
m_myId
uint32_t ns3::NullMessageSimulatorImpl::m_myId private
MPI rank.
Definition at line 209 of file null-message-simulator-impl.h.
Referenced by NullMessageSimulatorImpl(), and GetSystemId().
m_safeTime
Time ns3::NullMessageSimulatorImpl::m_safeTime private
The time for which it is safe for this task to execute events without danger of out-of-order events.
Definition at line 216 of file null-message-simulator-impl.h.
Referenced by NullMessageSimulatorImpl(), CalculateLookAhead(), CalculateSafeTime(), and GetSafeTime().
m_schedulerTune
double ns3::NullMessageSimulatorImpl::m_schedulerTune private
Null Message performance tuning parameter.
Controls when Null messages are sent. When value is 1 the minimum number of Null messages are sent conserving bandwidth. The delay in arrival of lookahead information is the greatest resulting in maximum unnecessary blocking of the receiver. When the value is near 0 Null Messages are sent with high frequency, costing more bandwidth and Null Message processing time, but there is minimum unnecessary block of the receiver.
Definition at line 228 of file null-message-simulator-impl.h.
Referenced by GetTypeId(), RescheduleNullMessageEvent(), and ScheduleNullMessageEvent().
m_stop
bool ns3::NullMessageSimulatorImpl::m_stop private
Flag calling for the end of the simulation.
Definition at line 189 of file null-message-simulator-impl.h.
Referenced by NullMessageSimulatorImpl(), IsFinished(), Run(), and Stop().
m_systemCount
uint32_t ns3::NullMessageSimulatorImpl::m_systemCount private
MPI communicator size.
Definition at line 210 of file null-message-simulator-impl.h.
Referenced by NullMessageSimulatorImpl().
m_uid
uint32_t ns3::NullMessageSimulatorImpl::m_uid private
Next event unique id.
Definition at line 194 of file null-message-simulator-impl.h.
Referenced by NullMessageSimulatorImpl(), Schedule(), ScheduleDestroy(), ScheduleNow(), and ScheduleWithContext().
m_unscheduledEvents
int ns3::NullMessageSimulatorImpl::m_unscheduledEvents private
Number of events that have been inserted but not yet scheduled, not counting the "destroy" events; this is used for validation.
Definition at line 207 of file null-message-simulator-impl.h.
Referenced by NullMessageSimulatorImpl(), ProcessOneEvent(), Remove(), Schedule(), ScheduleNow(), and ScheduleWithContext().
The documentation for this class was generated from the following files:
src/mpi/model/null-message-simulator-impl.h
src/mpi/model/null-message-simulator-impl.cc