ns-3: ns3::HtSigHeader Class Reference
ns3::HtSigHeader Class Reference
Wifi Models
Implements the IEEE 802.11n PHY header (HT-SIG1/2).
#include "wifi-phy-header.h"
Public Member Functions
HtSigHeader ()
virtual ~HtSigHeader ()
uint32_t Deserialize (Buffer::Iterator start)
bool GetAggregation (void) const
Return the aggregation field of HT-SIG.
uint16_t GetChannelWidth (void) const
Return the channel width (in MHz).
uint16_t GetHtLength (void) const
Return the HT length field of HT-SIG (in bytes).
TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint8_t GetMcs (void) const
Return the MCS field of HT-SIG.
uint32_t GetSerializedSize (void) const
bool GetShortGuardInterval (void) const
Return the short guard interval field of HT-SIG.
bool IsLdpcFecCoding (void) const
Return whether LDPC is used or not.
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetAggregation (bool aggregation)
Fill the aggregation field of HT-SIG.
void SetChannelWidth (uint16_t channelWidth)
Fill the channel width field of HT-SIG (in MHz).
void SetFecCoding (bool ldpc)
Fill the FEC coding field of HT-SIG.
void SetHtLength (uint16_t length)
Fill the HT length field of HT-SIG (in bytes).
void SetMcs (uint8_t mcs)
Fill the MCS field of HT-SIG.
void SetShortGuardInterval (bool sgi)
Fill the short guard interval field of HT-SIG.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_aggregation
Aggregation.
uint8_t m_cbw20_40
CBW 20/40.
uint8_t m_fecCoding
FEC coding (0 for BCC or 1 for LDPC)
uint16_t m_htLength
HT length.
uint8_t m_mcs
Modulation and Coding Scheme index.
uint8_t m_sgi
Short Guard Interval.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implements the IEEE 802.11n PHY header (HT-SIG1/2).
Introspection did not find any typical Config paths.
See section 19.3.9 in IEEE 802.11-2016.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 16 bytes (on a 64-bit architecture).
Definition at line 146 of file wifi-phy-header.h.
Constructor & Destructor Documentation
HtSigHeader()
ns3::HtSigHeader::HtSigHeader ()
Definition at line 334 of file wifi-phy-header.cc.
~HtSigHeader()
ns3::HtSigHeader::~HtSigHeader () virtual
Definition at line 343 of file wifi-phy-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::HtSigHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 470 of file wifi-phy-header.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_aggregation, m_cbw20_40, m_fecCoding, m_htLength, m_mcs, m_sgi, ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetAggregation()
bool ns3::HtSigHeader::GetAggregation (void) const
Return the aggregation field of HT-SIG.
Returns
the aggregation field of HT-SIG
Definition at line 425 of file wifi-phy-header.cc.
References m_aggregation.
GetChannelWidth()
uint16_t ns3::HtSigHeader::GetChannelWidth (void) const
Return the channel width (in MHz).
Returns
the channel width (in MHz)
Definition at line 401 of file wifi-phy-header.cc.
References m_cbw20_40.
Referenced by ns3::WifiPpdu::GetTxVector(), and Print().
GetHtLength()
uint16_t ns3::HtSigHeader::GetHtLength (void) const
Return the HT length field of HT-SIG (in bytes).
Returns
the HT length field of HT-SIG (in bytes)
Definition at line 413 of file wifi-phy-header.cc.
References m_htLength.
Referenced by ns3::WifiPpdu::GetTxDuration().
GetInstanceTypeId()
TypeId ns3::HtSigHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 359 of file wifi-phy-header.cc.
References GetTypeId().
GetMcs()
uint8_t ns3::HtSigHeader::GetMcs (void) const
Return the MCS field of HT-SIG.
Returns
the MCS field of HT-SIG
Definition at line 389 of file wifi-phy-header.cc.
References m_mcs.
Referenced by ns3::WifiPpdu::GetTxVector().
GetSerializedSize()
uint32_t ns3::HtSigHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 376 of file wifi-phy-header.cc.
GetShortGuardInterval()
bool ns3::HtSigHeader::GetShortGuardInterval (void) const
Return the short guard interval field of HT-SIG.
Returns
the short guard interval field of HT-SIG
Definition at line 449 of file wifi-phy-header.cc.
References m_sgi.
Referenced by ns3::WifiPpdu::GetTxVector().
GetTypeId()
TypeId ns3::HtSigHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 348 of file wifi-phy-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
IsLdpcFecCoding()
bool ns3::HtSigHeader::IsLdpcFecCoding (void) const
Return whether LDPC is used or not.
Returns
whether LDPC is used or not
Definition at line 437 of file wifi-phy-header.cc.
References m_fecCoding.
Referenced by ns3::WifiPpdu::GetTxVector().
Print()
void ns3::HtSigHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 365 of file wifi-phy-header.cc.
References GetChannelWidth(), m_aggregation, m_fecCoding, m_htLength, m_mcs, and m_sgi.
Serialize()
void ns3::HtSigHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 455 of file wifi-phy-header.cc.
References m_aggregation, m_cbw20_40, m_fecCoding, m_htLength, m_mcs, m_sgi, and visualizer.core::start().
SetAggregation()
void ns3::HtSigHeader::SetAggregation (bool aggregation)
Fill the aggregation field of HT-SIG.
Parameters
aggregation whether the PSDU contains A-MPDU or not
Definition at line 419 of file wifi-phy-header.cc.
References m_aggregation.
Referenced by ns3::WifiPpdu::SetPhyHeaders().
SetChannelWidth()
void ns3::HtSigHeader::SetChannelWidth (uint16_t channelWidth)
Fill the channel width field of HT-SIG (in MHz).
Parameters
channelWidth the channel width (in MHz)
Definition at line 395 of file wifi-phy-header.cc.
References m_cbw20_40.
Referenced by ns3::WifiPpdu::SetPhyHeaders().
SetFecCoding()
void ns3::HtSigHeader::SetFecCoding (bool ldpc)
Fill the FEC coding field of HT-SIG.
Parameters
ldpc whether LDPC is used or not
Definition at line 431 of file wifi-phy-header.cc.
References m_fecCoding.
Referenced by ns3::WifiPpdu::SetPhyHeaders().
SetHtLength()
void ns3::HtSigHeader::SetHtLength (uint16_t length)
Fill the HT length field of HT-SIG (in bytes).
Parameters
length the HT length field of HT-SIG (in bytes)
Definition at line 407 of file wifi-phy-header.cc.
References m_htLength.
Referenced by ns3::WifiPpdu::SetPhyHeaders().
SetMcs()
void ns3::HtSigHeader::SetMcs (uint8_t mcs)
Fill the MCS field of HT-SIG.
Parameters
mcs the MCS field of HT-SIG
Definition at line 382 of file wifi-phy-header.cc.
References m_mcs, and NS_ASSERT.
Referenced by ns3::WifiPpdu::SetPhyHeaders().
SetShortGuardInterval()
void ns3::HtSigHeader::SetShortGuardInterval (bool sgi)
Fill the short guard interval field of HT-SIG.
Parameters
sgi whether short guard interval is used or not
Definition at line 443 of file wifi-phy-header.cc.
References m_sgi.
Referenced by ns3::WifiPpdu::SetPhyHeaders().
Member Data Documentation
m_aggregation
uint8_t ns3::HtSigHeader::m_aggregation private
Aggregation.
Definition at line 241 of file wifi-phy-header.h.
Referenced by Deserialize(), GetAggregation(), Print(), Serialize(), and SetAggregation().
m_cbw20_40
uint8_t ns3::HtSigHeader::m_cbw20_40 private
CBW 20/40.
Definition at line 239 of file wifi-phy-header.h.
Referenced by Deserialize(), GetChannelWidth(), Serialize(), and SetChannelWidth().
m_fecCoding
uint8_t ns3::HtSigHeader::m_fecCoding private
FEC coding (0 for BCC or 1 for LDPC)
Definition at line 242 of file wifi-phy-header.h.
Referenced by Deserialize(), IsLdpcFecCoding(), Print(), Serialize(), and SetFecCoding().
m_htLength
uint16_t ns3::HtSigHeader::m_htLength private
HT length.
Definition at line 240 of file wifi-phy-header.h.
Referenced by Deserialize(), GetHtLength(), Print(), Serialize(), and SetHtLength().
m_mcs
uint8_t ns3::HtSigHeader::m_mcs private
Modulation and Coding Scheme index.
Definition at line 238 of file wifi-phy-header.h.
Referenced by Deserialize(), GetMcs(), Print(), Serialize(), and SetMcs().
m_sgi
uint8_t ns3::HtSigHeader::m_sgi private
Short Guard Interval.
Definition at line 243 of file wifi-phy-header.h.
Referenced by Deserialize(), GetShortGuardInterval(), Print(), Serialize(), and SetShortGuardInterval().
The documentation for this class was generated from the following files:
src/wifi/model/wifi-phy-header.h
src/wifi/model/wifi-phy-header.cc