ns-3: ns3::RandomWaypointMobilityModel Class Reference
ns3::RandomWaypointMobilityModel Class Reference
Mobility
Random waypoint mobility model.
#include "random-waypoint-mobility-model.h"
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type with the TypeId system.
Static Public Member Functions inherited from ns3::MobilityModel
static TypeId GetTypeId (void)
Register this type with the TypeId system.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::MobilityModel
void NotifyCourseChange (void) const
Must be invoked by subclasses when the course of the position changes to notify course change listeners.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void BeginWalk (void)
Get next position, begin moving towards it, schedule future pause event.
virtual int64_t DoAssignStreams (int64_t)
The default implementation does nothing but return the passed-in parameter.
virtual Vector DoGetPosition (void) const
virtual Vector DoGetVelocity (void) const
void DoInitializePrivate (void)
Begin current pause event, schedule future walk event.
virtual void DoSetPosition (const Vector &position)
Private Attributes
EventId m_event
event ID of next scheduled event
ConstantVelocityHelper m_helper
helper for velocity computations
Ptr< RandomVariableStream > m_pause
random variable to generate pauses
Ptr< PositionAllocator > m_position
pointer to position allocator
Ptr< RandomVariableStream > m_speed
random variable to generate speeds
Additional Inherited Members
Public Types inherited from ns3::MobilityModel
typedef void(* TracedCallback) (Ptr< const MobilityModel > model)
TracedCallback signature.
Public Member Functions inherited from ns3::MobilityModel
MobilityModel ()
virtual ~MobilityModel ()=0
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
double GetDistanceFrom (Ptr< const MobilityModel > position) const
Vector GetPosition (void) const
double GetRelativeSpeed (Ptr< const MobilityModel > other) const
Vector GetVelocity (void) const
void SetPosition (const Vector &position)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Random waypoint mobility model.
Each object starts by pausing at time zero for the duration governed by the random variable "Pause". After pausing, the object will pick a new waypoint (via the PositionAllocator) and a new random speed via the random variable "Speed", and will begin moving towards the waypoint at a constant speed. When it reaches the destination, the process starts over (by pausing).
This mobility model enforces no bounding box by itself; the PositionAllocator assigned to this object will bound the movement. If the user fails to provide a pointer to a PositionAllocator to be used to pick waypoints, the simulation program will assert.
The implementation of this model is not 2d-specific. i.e. if you provide a 3d random waypoint position model to this mobility model, the model will still work. There is no 3d position allocator for now but it should be trivial to add one.
Config Paths
ns3::RandomWaypointMobilityModel is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel"
Attributes
Speed: A random variable used to pick the speed of a random waypoint model.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::RandomVariableStream>
Initial value: ns3::UniformRandomVariable[Min=0.3|Max=0.7]
Flags: construct write read
Pause: A random variable used to pick the pause of a random waypoint model.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::RandomVariableStream>
Initial value: ns3::ConstantRandomVariable[Constant=2.0]
Flags: construct write read
PositionAllocator: The position model used to pick a destination point.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::PositionAllocator>
Initial value: 0x0
Flags: construct write read
Attributes defined in parent class ns3::MobilityModel
Position: The current position of the mobility model.
Set with class: Vector3DValue
Underlying type: Vector3D
Flags: write read
Velocity: The current velocity of the mobility model.
Set with class: Vector3DValue
Underlying type: Vector3D
Flags: read
No TraceSources are defined for this type.
TraceSources defined in parent class ns3::MobilityModel
CourseChange: The value of the position and/or velocity vector changed
Callback signature: ns3::MobilityModel::TracedCallback
Size of this type is 168 bytes (on a 64-bit architecture).
Definition at line 52 of file random-waypoint-mobility-model.h.
Member Function Documentation
BeginWalk()
void ns3::RandomWaypointMobilityModel::BeginWalk (void) private
Get next position, begin moving towards it, schedule future pause event.
Definition at line 59 of file random-waypoint-mobility-model.cc.
References ns3::CalculateDistance(), ns3::EventId::Cancel(), DoInitializePrivate(), ns3::ConstantVelocityHelper::GetCurrentPosition(), ns3::RandomVariableStream::GetValue(), m_event, m_helper, m_position, m_speed, ns3::MobilityModel::NotifyCourseChange(), NS_ASSERT_MSG, ns3::Simulator::Schedule(), ns3::Seconds(), ns3::ConstantVelocityHelper::SetVelocity(), ns3::ConstantVelocityHelper::Unpause(), and ns3::ConstantVelocityHelper::Update().
Referenced by DoInitializePrivate().
DoAssignStreams()
int64_t ns3::RandomWaypointMobilityModel::DoAssignStreams (int64_t start) private virtual
The default implementation does nothing but return the passed-in parameter.
Subclasses using random variables are expected to override this.
Parameters
start starting stream index
Returns
the number of streams used
Reimplemented from ns3::MobilityModel.
Definition at line 116 of file random-waypoint-mobility-model.cc.
References m_pause, m_position, m_speed, NS_ASSERT_MSG, and ns3::RandomVariableStream::SetStream().
DoGetPosition()
Vector ns3::RandomWaypointMobilityModel::DoGetPosition (void) const private virtual
Returns
the current position.
Concrete subclasses of this base class must implement this method.
Implements ns3::MobilityModel.
Definition at line 98 of file random-waypoint-mobility-model.cc.
References ns3::ConstantVelocityHelper::GetCurrentPosition(), m_helper, and ns3::ConstantVelocityHelper::Update().
DoGetVelocity()
Vector ns3::RandomWaypointMobilityModel::DoGetVelocity (void) const private virtual
Returns
the current velocity.
Concrete subclasses of this base class must implement this method.
Implements ns3::MobilityModel.
Definition at line 111 of file random-waypoint-mobility-model.cc.
References ns3::ConstantVelocityHelper::GetVelocity(), and m_helper.
DoInitialize()
void ns3::RandomWaypointMobilityModel::DoInitialize (void) protected virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 81 of file random-waypoint-mobility-model.cc.
References ns3::Object::DoInitialize(), and DoInitializePrivate().
DoInitializePrivate()
void ns3::RandomWaypointMobilityModel::DoInitializePrivate (void) private
Begin current pause event, schedule future walk event.
Definition at line 88 of file random-waypoint-mobility-model.cc.
References BeginWalk(), ns3::RandomVariableStream::GetValue(), m_event, m_helper, m_pause, ns3::MobilityModel::NotifyCourseChange(), ns3::ConstantVelocityHelper::Pause(), ns3::Simulator::Schedule(), ns3::Seconds(), and ns3::ConstantVelocityHelper::Update().
Referenced by BeginWalk(), DoInitialize(), and DoSetPosition().
DoSetPosition()
void ns3::RandomWaypointMobilityModel::DoSetPosition (const Vector & position) private virtual
Parameters
position the position to set.
Concrete subclasses of this base class must implement this method.
Implements ns3::MobilityModel.
Definition at line 104 of file random-waypoint-mobility-model.cc.
References ns3::EventId::Cancel(), DoInitializePrivate(), m_event, m_helper, ns3::Simulator::ScheduleNow(), and ns3::ConstantVelocityHelper::SetPosition().
GetTypeId()
TypeId ns3::RandomWaypointMobilityModel::GetTypeId (void) static
Register this type with the TypeId system.
Returns
the object TypeId
Definition at line 33 of file random-waypoint-mobility-model.cc.
References m_pause, m_position, m_speed, ns3::MakePointerAccessor(), and ns3::TypeId::SetParent().
Member Data Documentation
m_event
EventId ns3::RandomWaypointMobilityModel::m_event private
event ID of next scheduled event
Definition at line 80 of file random-waypoint-mobility-model.h.
Referenced by BeginWalk(), DoInitializePrivate(), and DoSetPosition().
m_helper
ConstantVelocityHelper ns3::RandomWaypointMobilityModel::m_helper private
helper for velocity computations
Definition at line 76 of file random-waypoint-mobility-model.h.
Referenced by BeginWalk(), DoGetPosition(), DoGetVelocity(), DoInitializePrivate(), and DoSetPosition().
m_pause
Ptr<RandomVariableStream> ns3::RandomWaypointMobilityModel::m_pause private
random variable to generate pauses
Definition at line 79 of file random-waypoint-mobility-model.h.
Referenced by DoAssignStreams(), DoInitializePrivate(), and GetTypeId().
m_position
Ptr<PositionAllocator> ns3::RandomWaypointMobilityModel::m_position private
pointer to position allocator
Definition at line 77 of file random-waypoint-mobility-model.h.
Referenced by BeginWalk(), DoAssignStreams(), and GetTypeId().
m_speed
Ptr<RandomVariableStream> ns3::RandomWaypointMobilityModel::m_speed private
random variable to generate speeds
Definition at line 78 of file random-waypoint-mobility-model.h.
Referenced by BeginWalk(), DoAssignStreams(), and GetTypeId().
The documentation for this class was generated from the following files:
src/mobility/model/random-waypoint-mobility-model.h
src/mobility/model/random-waypoint-mobility-model.cc