ns-3: ns3::ItuR1411LosPropagationLossModel Class Reference
ns3::ItuR1411LosPropagationLossModel Class Reference
Propagation Models
the ITU-R 1411 LOS propagation model
#include "itu-r-1411-los-propagation-loss-model.h"
Public Member Functions
ItuR1411LosPropagationLossModel ()
virtual ~ItuR1411LosPropagationLossModel ()
double GetLoss (Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
void SetFrequency (double freq)
Set the operating frequency.
Public Member Functions inherited from ns3::PropagationLossModel
PropagationLossModel ()
virtual ~PropagationLossModel ()
int64_t AssignStreams (int64_t stream)
If this loss model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
double CalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account all the PropagationLossModel(s) chained to the current one.
Ptr< PropagationLossModel > GetNext ()
Gets the next PropagationLossModel in the chain of loss models that act on the signal.
void SetNext (Ptr< PropagationLossModel > next)
Enables a chain of loss models to act on the signal.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::PropagationLossModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
ItuR1411LosPropagationLossModel (const ItuR1411LosPropagationLossModel &)
Copy constructor.
virtual int64_t DoAssignStreams (int64_t stream)
Subclasses must implement this; those not using random variables can return zero.
virtual double DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account only the particular PropagationLossModel.
ItuR1411LosPropagationLossModel & operator= (const ItuR1411LosPropagationLossModel &)
Copy constructor.
Private Attributes
double m_lambda
wavelength
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
the ITU-R 1411 LOS propagation model
This class implements the ITU-R 1411 LOS propagation model for Line-of-Sight (LoS) short range outdoor communication in the frequency range 300 MHz to 100 GHz.
For more information about the model, please see the propagation module documentation in .rst format.
Config Paths
ns3::ItuR1411LosPropagationLossModel is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::SpectrumChannel/PropagationLossModel/$ns3::ItuR1411LosPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::YansWifiChannel/PropagationLossModel/$ns3::ItuR1411LosPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::LrWpanNetDevice/Channel/PropagationLossModel/$ns3::ItuR1411LosPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::SpectrumChannel/PropagationLossModel/$ns3::ItuR1411LosPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::YansWifiChannel/PropagationLossModel/$ns3::ItuR1411LosPropagationLossModel"
"/ChannelList/[i]/$ns3::SpectrumChannel/PropagationLossModel/$ns3::ItuR1411LosPropagationLossModel"
"/ChannelList/[i]/$ns3::YansWifiChannel/PropagationLossModel/$ns3::ItuR1411LosPropagationLossModel"
Attributes
Frequency: The propagation frequency in Hz
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 2.16e+09
Flags: construct write
No TraceSources are defined for this type.
Size of this type is 48 bytes (on a 64-bit architecture).
Definition at line 42 of file itu-r-1411-los-propagation-loss-model.h.
Constructor & Destructor Documentation
ItuR1411LosPropagationLossModel() [1/2]
ns3::ItuR1411LosPropagationLossModel::ItuR1411LosPropagationLossModel ()
Definition at line 52 of file itu-r-1411-los-propagation-loss-model.cc.
~ItuR1411LosPropagationLossModel()
ns3::ItuR1411LosPropagationLossModel::~ItuR1411LosPropagationLossModel () virtual
Definition at line 57 of file itu-r-1411-los-propagation-loss-model.cc.
ItuR1411LosPropagationLossModel() [2/2]
ns3::ItuR1411LosPropagationLossModel::ItuR1411LosPropagationLossModel (const ItuR1411LosPropagationLossModel &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Member Function Documentation
DoAssignStreams()
int64_t ns3::ItuR1411LosPropagationLossModel::DoAssignStreams (int64_t stream) private virtual
Subclasses must implement this; those not using random variables can return zero.
Implements ns3::PropagationLossModel.
Definition at line 106 of file itu-r-1411-los-propagation-loss-model.cc.
DoCalcRxPower()
double ns3::ItuR1411LosPropagationLossModel::DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const private virtual
Returns the Rx Power taking into account only the particular PropagationLossModel.
Parameters
txPowerDbm current transmission power (in dBm)
a the mobility model of the source
b the mobility model of the destination
Returns
the reception power after adding/multiplying propagation loss (in dBm)
Implements ns3::PropagationLossModel.
Definition at line 98 of file itu-r-1411-los-propagation-loss-model.cc.
References GetLoss().
GetLoss()
double ns3::ItuR1411LosPropagationLossModel::GetLoss (Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Parameters
a the first mobility model
b the second mobility model
Returns
the loss in dBm for the propagation between the two given mobility models
Definition at line 62 of file itu-r-1411-los-propagation-loss-model.cc.
References ns3::MobilityModel::GetDistanceFrom(), ns3::MobilityModel::GetPosition(), m_lambda, NS_ASSERT_MSG, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by DoCalcRxPower().
GetTypeId()
TypeId ns3::ItuR1411LosPropagationLossModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 37 of file itu-r-1411-los-propagation-loss-model.cc.
References ns3::MakeDoubleAccessor(), SetFrequency(), and ns3::TypeId::SetParent().
operator=()
ItuR1411LosPropagationLossModel& ns3::ItuR1411LosPropagationLossModel::operator= (const ItuR1411LosPropagationLossModel &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Returns
SetFrequency()
void ns3::ItuR1411LosPropagationLossModel::SetFrequency (double freq)
Set the operating frequency.
Parameters
freq the frequency in Hz
Definition at line 90 of file itu-r-1411-los-propagation-loss-model.cc.
References m_lambda, and NS_ASSERT.
Referenced by GetTypeId().
Member Data Documentation
m_lambda
double ns3::ItuR1411LosPropagationLossModel::m_lambda private
wavelength
Definition at line 94 of file itu-r-1411-los-propagation-loss-model.h.
Referenced by GetLoss(), and SetFrequency().
The documentation for this class was generated from the following files:
src/propagation/model/itu-r-1411-los-propagation-loss-model.h
src/propagation/model/itu-r-1411-los-propagation-loss-model.cc