ns-3: ns3::BsServiceFlowManager Class Reference
ns3::BsServiceFlowManager Class Reference
WiMAX Models
BsServiceFlowManager.
#include "bs-service-flow-manager.h"
Public Types
enum ConfirmationCode { CONFIRMATION_CODE_SUCCESS , CONFIRMATION_CODE_REJECT }
Confirmation code enumeration.
Public Types inherited from ns3::ServiceFlowManager
enum ConfirmationCode { CONFIRMATION_CODE_SUCCESS , CONFIRMATION_CODE_REJECT }
confirmation code enumeration as per Table 384 (not all codes implemented)
Public Member Functions
BsServiceFlowManager (Ptr< BaseStationNetDevice > device)
Constructor.
~BsServiceFlowManager (void)
void AddMulticastServiceFlow (ServiceFlow sf, enum WimaxPhy::ModulationType modulation)
add a multicast service flow
void AddServiceFlow (ServiceFlow *serviceFlow)
Add a new service flow.
void AllocateServiceFlows (const DsaReq &dsaReq, Cid cid)
allocate service flows
void DoDispose (void)
Destructor implementation.
EventId GetDsaAckTimeoutEvent (void) const
ServiceFlow * GetServiceFlow (Cid cid) const
ServiceFlow * GetServiceFlow (uint32_t sfid) const
std::vector< ServiceFlow * > GetServiceFlows (ServiceFlow::SchedulingType schedulingType) const
void ProcessDsaAck (const DsaAck &dsaAck, Cid cid)
process a DSA-ACK message
ServiceFlow * ProcessDsaReq (const DsaReq &dsaReq, Cid cid)
process a DSA-Req message
void SetMaxDsaRspRetries (uint8_t maxDsaRspRetries)
set the maximum Dynamic ServiceFlow Add (DSA) retries
Public Member Functions inherited from ns3::ServiceFlowManager
ServiceFlowManager ()
~ServiceFlowManager (void)
void AddServiceFlow (ServiceFlow *serviceFlow)
Add service flow function.
bool AreServiceFlowsAllocated ()
bool AreServiceFlowsAllocated (std::vector< ServiceFlow * > *serviceFlows)
bool AreServiceFlowsAllocated (std::vector< ServiceFlow * > serviceFlows)
ServiceFlow * DoClassify (Ipv4Address SrcAddress, Ipv4Address DstAddress, uint16_t SrcPort, uint16_t DstPort, uint8_t Proto, ServiceFlow::Direction dir) const
void DoDispose (void)
Destructor implementation.
ServiceFlow * GetNextServiceFlowToAllocate ()
uint32_t GetNrServiceFlows (void) const
ServiceFlow * GetServiceFlow (Cid cid) const
Get service flow by CID.
ServiceFlow * GetServiceFlow (uint32_t sfid) const
Get service flow by flow id.
std::vector< ServiceFlow * > GetServiceFlows (enum ServiceFlow::SchedulingType schedulingType) const
Get service flows function.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ServiceFlowManager
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
DsaRsp CreateDsaRsp (const ServiceFlow *serviceFlow, uint16_t transactionId)
Create DSA response function.
uint8_t GetMaxDsaRspRetries (void) const
void ScheduleDsaRsp (ServiceFlow *serviceFlow, Cid cid)
Create DSA response function.
Private Attributes
Ptr< WimaxNetDevice > m_device
the device
EventId m_dsaAckTimeoutEvent
DSA ack timeout event.
Cid m_inuseScheduleDsaRspCid
in use schedule DSA response CID
uint8_t m_maxDsaRspRetries
maximum number of DSA response retries
uint32_t m_sfidIndex
SFID index.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
BsServiceFlowManager.
Definition at line 44 of file bs-service-flow-manager.h.
Member Enumeration Documentation
ConfirmationCode
enum ns3::BsServiceFlowManager::ConfirmationCode
Confirmation code enumeration.
Enumerator
CONFIRMATION_CODE_SUCCESS
CONFIRMATION_CODE_REJECT
Definition at line 48 of file bs-service-flow-manager.h.
Constructor & Destructor Documentation
BsServiceFlowManager()
ns3::BsServiceFlowManager::BsServiceFlowManager (Ptr< BaseStationNetDevice > device)
Constructor.
Parameters
device base station device
Definition at line 45 of file bs-service-flow-manager.cc.
References ns3::Cid::InitialRanging(), and m_inuseScheduleDsaRspCid.
~BsServiceFlowManager()
ns3::BsServiceFlowManager::~BsServiceFlowManager (void)
Definition at line 53 of file bs-service-flow-manager.cc.
Member Function Documentation
AddMulticastServiceFlow()
void ns3::BsServiceFlowManager::AddMulticastServiceFlow (ServiceFlow sf, enum WimaxPhy::ModulationType modulation)
add a multicast service flow
Parameters
sf the service flow
modulation the wimax phy modulation type
Definition at line 223 of file bs-service-flow-manager.cc.
References AddServiceFlow(), ns3::ServiceFlow::CopyParametersFrom(), m_device, ns3::Cid::MULTICAST, ns3::ServiceFlow::SetConnection(), ns3::ServiceFlow::SetIsEnabled(), ns3::ServiceFlow::SetIsMulticast(), ns3::ServiceFlow::SetModulation(), ns3::ServiceFlow::SetType(), and ns3::ServiceFlow::SF_TYPE_ACTIVE.
AddServiceFlow()
void ns3::BsServiceFlowManager::AddServiceFlow (ServiceFlow * serviceFlow)
Add a new service flow.
Parameters
serviceFlow the service flow to add
Definition at line 94 of file bs-service-flow-manager.cc.
References ns3::ServiceFlowManager::AddServiceFlow().
Referenced by AddMulticastServiceFlow(), and ProcessDsaReq().
AllocateServiceFlows()
void ns3::BsServiceFlowManager::AllocateServiceFlows (const DsaReq & dsaReq, Cid cid)
allocate service flows
Parameters
dsaReq the DSA request
cid the connection identifier
Definition at line 239 of file bs-service-flow-manager.cc.
References NS_LOG_INFO, ProcessDsaReq(), and ScheduleDsaRsp().
CreateDsaRsp()
DsaRsp ns3::BsServiceFlowManager::CreateDsaRsp (const ServiceFlow * serviceFlow, uint16_t transactionId) private
Create DSA response function.
Parameters
serviceFlow service flow
transactionId transaction ID
Returns
the DSA response
Definition at line 118 of file bs-service-flow-manager.cc.
References CONFIRMATION_CODE_SUCCESS, ns3::DsaRsp::SetConfirmationCode(), ns3::DsaRsp::SetServiceFlow(), and ns3::DsaRsp::SetTransactionId().
Referenced by ScheduleDsaRsp().
DoDispose()
void ns3::BsServiceFlowManager::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 70 of file bs-service-flow-manager.cc.
References ns3::ServiceFlowManager::DoDispose().
GetDsaAckTimeoutEvent()
EventId ns3::BsServiceFlowManager::GetDsaAckTimeoutEvent (void) const
Returns
the DSA ack timeout event
Definition at line 88 of file bs-service-flow-manager.cc.
References m_dsaAckTimeoutEvent.
GetMaxDsaRspRetries()
uint8_t ns3::BsServiceFlowManager::GetMaxDsaRspRetries (void) const private
Returns
the maximum DSA response retries
Definition at line 82 of file bs-service-flow-manager.cc.
References m_maxDsaRspRetries.
GetServiceFlow() [1/2]
ServiceFlow * ns3::BsServiceFlowManager::GetServiceFlow (Cid cid) const
Parameters
cid the connection identifier
Returns
the service flow which has as connection identifier cid
Definition at line 106 of file bs-service-flow-manager.cc.
References ns3::ServiceFlowManager::GetServiceFlow().
GetServiceFlow() [2/2]
ServiceFlow * ns3::BsServiceFlowManager::GetServiceFlow (uint32_t sfid) const
Parameters
sfid the service flow identifier
Returns
the service flow which has as identifier sfid
Definition at line 100 of file bs-service-flow-manager.cc.
References ns3::ServiceFlowManager::GetServiceFlow().
Referenced by ProcessDsaReq().
GetServiceFlows()
std::vector< ServiceFlow * > ns3::BsServiceFlowManager::GetServiceFlows (ServiceFlow::SchedulingType schedulingType) const
Parameters
schedulingType the scheduling type
Returns
the list of service flows configured with schedulingType as a QoS class
Definition at line 112 of file bs-service-flow-manager.cc.
References ns3::ServiceFlowManager::GetServiceFlows().
GetTypeId()
TypeId ns3::BsServiceFlowManager::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 59 of file bs-service-flow-manager.cc.
References ns3::TypeId::SetParent().
ProcessDsaAck()
void ns3::BsServiceFlowManager::ProcessDsaAck (const DsaAck & dsaAck, Cid cid)
process a DSA-ACK message
Parameters
dsaAck the message to process
cid the identifier of the connection on which the message was received
Definition at line 250 of file bs-service-flow-manager.cc.
References ns3::ServiceFlowManager::AreServiceFlowsAllocated(), ns3::DsaAck::GetTransactionId(), m_device, and ns3::ServiceFlow::SF_TYPE_ALL.
ProcessDsaReq()
ServiceFlow * ns3::BsServiceFlowManager::ProcessDsaReq (const DsaReq & dsaReq, Cid cid)
process a DSA-Req message
Parameters
dsaReq the message to process
cid the identifier of the connection on which the message was received
Returns
a pointer to the service flow
Definition at line 188 of file bs-service-flow-manager.cc.
References AddServiceFlow(), ns3::ServiceFlow::CopyParametersFrom(), ns3::ServiceFlow::GetCid(), ns3::ServiceFlow::GetConvergenceSublayerParam(), ns3::ServiceFlow::GetDirection(), GetServiceFlow(), ns3::DsaReq::GetServiceFlow(), ns3::ServiceFlow::GetSfid(), ns3::DsaReq::GetTransactionId(), m_device, m_sfidIndex, NS_ASSERT_MSG, NS_LOG_INFO, ns3::ServiceFlow::SetConvergenceSublayerParam(), ns3::ServiceFlow::SetUnsolicitedGrantInterval(), ns3::ServiceFlow::SetUnsolicitedPollingInterval(), and ns3::Cid::TRANSPORT.
Referenced by AllocateServiceFlows().
ScheduleDsaRsp()
void ns3::BsServiceFlowManager::ScheduleDsaRsp (ServiceFlow * serviceFlow, Cid cid) private
Create DSA response function.
Parameters
serviceFlow service flow
cid the identifier of the connection on which the message was received
Definition at line 130 of file bs-service-flow-manager.cc.
References ns3::Packet::AddHeader(), ns3::Simulator::Cancel(), CreateDsaRsp(), ns3::EventId::IsRunning(), m_device, m_dsaAckTimeoutEvent, m_inuseScheduleDsaRspCid, m_maxDsaRspRetries, ns3::ManagementMessageType::MESSAGE_TYPE_DSA_RSP, NS_LOG_DEBUG, NS_LOG_INFO, ns3::Simulator::Schedule(), ns3::ServiceFlow::SetIsEnabled(), ns3::ServiceFlow::SetType(), and ns3::ServiceFlow::SF_TYPE_ACTIVE.
Referenced by AllocateServiceFlows().
SetMaxDsaRspRetries()
void ns3::BsServiceFlowManager::SetMaxDsaRspRetries (uint8_t maxDsaRspRetries)
set the maximum Dynamic ServiceFlow Add (DSA) retries
Parameters
maxDsaRspRetries the maximum DSA response retries
Definition at line 76 of file bs-service-flow-manager.cc.
References m_maxDsaRspRetries.
Member Data Documentation
m_device
Ptr<WimaxNetDevice> ns3::BsServiceFlowManager::m_device private
the device
Definition at line 142 of file bs-service-flow-manager.h.
Referenced by AddMulticastServiceFlow(), ProcessDsaAck(), ProcessDsaReq(), and ScheduleDsaRsp().
m_dsaAckTimeoutEvent
EventId ns3::BsServiceFlowManager::m_dsaAckTimeoutEvent private
DSA ack timeout event.
Definition at line 145 of file bs-service-flow-manager.h.
Referenced by GetDsaAckTimeoutEvent(), and ScheduleDsaRsp().
m_inuseScheduleDsaRspCid
Cid ns3::BsServiceFlowManager::m_inuseScheduleDsaRspCid private
in use schedule DSA response CID
Definition at line 146 of file bs-service-flow-manager.h.
Referenced by BsServiceFlowManager(), and ScheduleDsaRsp().
m_maxDsaRspRetries
uint8_t ns3::BsServiceFlowManager::m_maxDsaRspRetries private
maximum number of DSA response retries
Definition at line 144 of file bs-service-flow-manager.h.
Referenced by GetMaxDsaRspRetries(), ScheduleDsaRsp(), and SetMaxDsaRspRetries().
m_sfidIndex
uint32_t ns3::BsServiceFlowManager::m_sfidIndex private
SFID index.
Definition at line 143 of file bs-service-flow-manager.h.
Referenced by ProcessDsaReq().
The documentation for this class was generated from the following files:
src/wimax/model/bs-service-flow-manager.h
src/wimax/model/bs-service-flow-manager.cc