ns-3: ns3::ThreeGppSpectrumPropagationLossModel Class Reference
ns3::ThreeGppSpectrumPropagationLossModel Class Reference
Spectrum Models
3GPP Spectrum Propagation Loss Model
#include "three-gpp-spectrum-propagation-loss-model.h"
Classes
struct LongTerm
Data structure that stores the long term component for a tx-rx pair.
Public Member Functions
ThreeGppSpectrumPropagationLossModel ()
Constructor.
~ThreeGppSpectrumPropagationLossModel ()
Destructor.
void AddDevice (Ptr< NetDevice > n, Ptr< const ThreeGppAntennaArrayModel > a)
Add a device-antenna pair.
Ptr< SpectrumValue > DoCalcRxPowerSpectralDensity (Ptr< const SpectrumValue > txPsd, Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const override
Computes the received PSD.
void DoDispose () override
Destructor implementation.
Ptr< MatrixBasedChannelModel > GetChannelModel () const
Get the channel model object.
void GetChannelModelAttribute (const std::string &name, AttributeValue &value) const
Returns the value of an attribute belonging to the associated MatrixBasedChannelModel instance.
void SetChannelModel (Ptr< MatrixBasedChannelModel > channel)
Set the channel model object.
void SetChannelModelAttribute (const std::string &name, const AttributeValue &value)
Sets the value of an attribute belonging to the associated MatrixBasedChannelModel instance.
Public Member Functions inherited from ns3::SpectrumPropagationLossModel
SpectrumPropagationLossModel ()
virtual ~SpectrumPropagationLossModel ()
Ptr< SpectrumValue > CalcRxPowerSpectralDensity (Ptr< const SpectrumValue > txPsd, Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const
This method is to be called to calculate.
void SetNext (Ptr< SpectrumPropagationLossModel > next)
Used to chain various instances of SpectrumPropagationLossModel.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::SpectrumPropagationLossModel
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
Ptr< SpectrumValue > CalcBeamformingGain (Ptr< SpectrumValue > txPsd, ThreeGppAntennaArrayModel::ComplexVector longTerm, Ptr< const MatrixBasedChannelModel::ChannelMatrix > params, const Vector &sSpeed, const Vector &uSpeed) const
Computes the beamforming gain and applies it to the tx PSD.
ThreeGppAntennaArrayModel::ComplexVector CalcLongTerm (Ptr< const MatrixBasedChannelModel::ChannelMatrix > channelMatrix, const ThreeGppAntennaArrayModel::ComplexVector &sW, const ThreeGppAntennaArrayModel::ComplexVector &uW) const
Computes the long term component.
double GetFrequency () const
Get the operating frequency.
ThreeGppAntennaArrayModel::ComplexVector GetLongTerm (uint32_t aId, uint32_t bId, Ptr< const MatrixBasedChannelModel::ChannelMatrix > channelMatrix, const ThreeGppAntennaArrayModel::ComplexVector &aW, const ThreeGppAntennaArrayModel::ComplexVector &bW) const
Looks for the long term component in m_longTermMap.
Private Attributes
Ptr< MatrixBasedChannelModel > m_channelModel
the model to generate the channel matrix
std::unordered_map< uint32_t, Ptr< const ThreeGppAntennaArrayModel > > m_deviceAntennaMap
map containig the <node, antenna> associations
std::unordered_map< uint32_t, Ptr< const LongTerm > > m_longTermMap
map containing the long term components
Ptr< UniformRandomVariable > m_uniformRv
uniform random variable, used to compute the additional Doppler contribution
double m_vScatt
value used to compute the additional Doppler contribution for the delayed paths
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
3GPP Spectrum Propagation Loss Model
Introspection did not find any typical Config paths.
This class models the frequency dependent propagation phenomena in the way described by 3GPP TR 38.901 document. The main method is DoCalcRxPowerSpectralDensity, which takes as input the power spectral density (PSD) of the transmitted signal, the mobility models of the transmitting node and receiving node, and returns the PSD of the received signal.
See also
MatrixBasedChannelModel
ThreeGppAntennaArrayModel
ChannelCondition
Attributes
ChannelModel: The channel model. It needs to implement the MatrixBasedChannelModel interface
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::Object>
Initial value: ns3::ThreeGppChannelModel
Flags: construct write read
vScatt: Maximum speed of the vehicle in the layout (see 3GPP TR 37.885 v15.3.0, Sec. 6.2.3).Used to compute the additional contribution for the Doppler ofdelayed (reflected) paths
Set with class: ns3::DoubleValue
Underlying type: double 0:1.79769e+308
Initial value: 0
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 144 bytes (on a 64-bit architecture).
Definition at line 52 of file three-gpp-spectrum-propagation-loss-model.h.
Constructor & Destructor Documentation
ThreeGppSpectrumPropagationLossModel()
ns3::ThreeGppSpectrumPropagationLossModel::ThreeGppSpectrumPropagationLossModel ()
Constructor.
Definition at line 41 of file three-gpp-spectrum-propagation-loss-model.cc.
References m_uniformRv, and NS_LOG_FUNCTION.
~ThreeGppSpectrumPropagationLossModel()
ns3::ThreeGppSpectrumPropagationLossModel::~ThreeGppSpectrumPropagationLossModel ()
Destructor.
Definition at line 47 of file three-gpp-spectrum-propagation-loss-model.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddDevice()
void ns3::ThreeGppSpectrumPropagationLossModel::AddDevice (Ptr< NetDevice > n, Ptr< const ThreeGppAntennaArrayModel > a)
Add a device-antenna pair.
Parameters
n a pointer to the NetDevice
a a pointer to the associated ThreeGppAntennaArrayModel
Definition at line 98 of file three-gpp-spectrum-propagation-loss-model.cc.
References m_deviceAntennaMap, sample-rng-plot::n, and NS_ASSERT_MSG.
CalcBeamformingGain()
Ptr< SpectrumValue > ns3::ThreeGppSpectrumPropagationLossModel::CalcBeamformingGain (Ptr< SpectrumValue > txPsd, ThreeGppAntennaArrayModel::ComplexVector longTerm, Ptr< const MatrixBasedChannelModel::ChannelMatrix > params, const Vector & sSpeed, const Vector & uSpeed) const private
Computes the beamforming gain and applies it to the tx PSD.
Parameters
txPsd the tx PSD
longTerm the long term component
params The channel matrix
sSpeed speed of the first node
uSpeed speed of the second node
Returns
the rx PSD
Definition at line 158 of file three-gpp-spectrum-propagation-loss-model.cc.
References sample-rng-plot::alpha, ns3::MatrixBasedChannelModel::AOA_INDEX, ns3::MatrixBasedChannelModel::AOD_INDEX, ns3::SpectrumValue::ConstBandsBegin(), GetFrequency(), ns3::Time::GetSeconds(), ns3::UniformRandomVariable::GetValue(), m_uniformRv, m_vScatt, MRG32k3a::norm, ns3::Simulator::Now(), NS_LOG_FUNCTION, ns3::SpectrumValue::ValuesBegin(), ns3::SpectrumValue::ValuesEnd(), ns3::MatrixBasedChannelModel::ZOA_INDEX, and ns3::MatrixBasedChannelModel::ZOD_INDEX.
Referenced by DoCalcRxPowerSpectralDensity().
CalcLongTerm()
ThreeGppAntennaArrayModel::ComplexVector ns3::ThreeGppSpectrumPropagationLossModel::CalcLongTerm (Ptr< const MatrixBasedChannelModel::ChannelMatrix > channelMatrix, const ThreeGppAntennaArrayModel::ComplexVector & sW, const ThreeGppAntennaArrayModel::ComplexVector & uW) const private
Computes the long term component.
Parameters
channelMatrix the channel matrix H
sW the beamforming vector of the s device
uW the beamforming vector of the u device
Returns
the long term component
Definition at line 125 of file three-gpp-spectrum-propagation-loss-model.cc.
References NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by GetLongTerm().
DoCalcRxPowerSpectralDensity()
Ptr< SpectrumValue > ns3::ThreeGppSpectrumPropagationLossModel::DoCalcRxPowerSpectralDensity (Ptr< const SpectrumValue > txPsd, Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const override virtual
Computes the received PSD.
This function computes the received PSD by applying the 3GPP fast fading model and the beamforming gain. In particular, it retrieves the matrix representing the channel between node a and node b, computes the corresponding long term component, i.e., the product between the cluster matrices and the TX and RX beamforming vectors (w_rx^T H^n_ab w_tx), and accounts for the Doppler component and the propagation delay. To reduce the computational load, the long term component associated with a certain channel is cached and recomputed only when the channel realization is updated, or when the beamforming vectors change.
Parameters
txPsd tx PSD
a first node mobility model
b second node mobility model
Returns
the received PSD
Implements ns3::SpectrumPropagationLossModel.
Definition at line 299 of file three-gpp-spectrum-propagation-loss-model.cc.
References CalcBeamformingGain(), GetLongTerm(), m_channelModel, m_deviceAntennaMap, NS_ASSERT, NS_ASSERT_MSG, NS_LOG_DEBUG, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
DoDispose()
void ns3::ThreeGppSpectrumPropagationLossModel::DoDispose (void) override virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::SpectrumPropagationLossModel.
Definition at line 53 of file three-gpp-spectrum-propagation-loss-model.cc.
References m_channelModel, m_deviceAntennaMap, and m_longTermMap.
GetChannelModel()
Ptr< MatrixBasedChannelModel > ns3::ThreeGppSpectrumPropagationLossModel::GetChannelModel () const
Get the channel model object.
Returns
a pointer to the object implementing the MatrixBasedChannelModel interface
Definition at line 92 of file three-gpp-spectrum-propagation-loss-model.cc.
References m_channelModel.
Referenced by GetTypeId().
GetChannelModelAttribute()
void ns3::ThreeGppSpectrumPropagationLossModel::GetChannelModelAttribute (const std::string & name, AttributeValue & value) const
Returns the value of an attribute belonging to the associated MatrixBasedChannelModel instance.
Parameters
name name of the attribute
where the result should be stored
Definition at line 119 of file three-gpp-spectrum-propagation-loss-model.cc.
References m_channelModel.
GetFrequency()
double ns3::ThreeGppSpectrumPropagationLossModel::GetFrequency (void) const private
Get the operating frequency.
Returns
the operating frequency in Hz
Definition at line 105 of file three-gpp-spectrum-propagation-loss-model.cc.
References ns3::DoubleValue::Get(), and m_channelModel.
Referenced by CalcBeamformingGain().
GetLongTerm()
ThreeGppAntennaArrayModel::ComplexVector ns3::ThreeGppSpectrumPropagationLossModel::GetLongTerm (uint32_t aId, uint32_t bId, Ptr< const MatrixBasedChannelModel::ChannelMatrix > channelMatrix, const ThreeGppAntennaArrayModel::ComplexVector & aW, const ThreeGppAntennaArrayModel::ComplexVector & bW) const private
Looks for the long term component in m_longTermMap.
If found, checks whether it has to be updated. If not found or if it has to be updated, calls the method CalcLongTerm to compute it.
Parameters
aId id of the first node
bId id of the second node
channelMatrix the channel matrix
aW the beamforming vector of the first device
bW the beamforming vector of the second device
Returns
vector containing the long term compoenent for each cluster
Definition at line 230 of file three-gpp-spectrum-propagation-loss-model.cc.
References CalcLongTerm(), ns3::MatrixBasedChannelModel::GetKey(), m_longTermMap, max, min, and NS_LOG_DEBUG.
Referenced by DoCalcRxPowerSpectralDensity().
GetTypeId()
TypeId ns3::ThreeGppSpectrumPropagationLossModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 62 of file three-gpp-spectrum-propagation-loss-model.cc.
References GetChannelModel(), m_vScatt, ns3::MakeDoubleAccessor(), ns3::MakePointerAccessor(), SetChannelModel(), and ns3::TypeId::SetParent().
SetChannelModel()
void ns3::ThreeGppSpectrumPropagationLossModel::SetChannelModel (Ptr< MatrixBasedChannelModel > channel)
Set the channel model object.
Parameters
channel a pointer to an object implementing the MatrixBasedChannelModel interface
Definition at line 86 of file three-gpp-spectrum-propagation-loss-model.cc.
References third::channel, and m_channelModel.
Referenced by GetTypeId().
SetChannelModelAttribute()
void ns3::ThreeGppSpectrumPropagationLossModel::SetChannelModelAttribute (const std::string & name, const AttributeValue & value)
Sets the value of an attribute belonging to the associated MatrixBasedChannelModel instance.
Parameters
name name of the attribute
value the attribute value
Definition at line 113 of file three-gpp-spectrum-propagation-loss-model.cc.
References m_channelModel.
Member Data Documentation
m_channelModel
Ptr<MatrixBasedChannelModel> ns3::ThreeGppSpectrumPropagationLossModel::m_channelModel private
the model to generate the channel matrix
Definition at line 193 of file three-gpp-spectrum-propagation-loss-model.h.
Referenced by DoCalcRxPowerSpectralDensity(), DoDispose(), GetChannelModel(), GetChannelModelAttribute(), GetFrequency(), SetChannelModel(), and SetChannelModelAttribute().
m_deviceAntennaMap
std::unordered_map<uint32_t, Ptr<const ThreeGppAntennaArrayModel> > ns3::ThreeGppSpectrumPropagationLossModel::m_deviceAntennaMap private
map containig the <node, antenna> associations
Definition at line 191 of file three-gpp-spectrum-propagation-loss-model.h.
Referenced by AddDevice(), DoCalcRxPowerSpectralDensity(), and DoDispose().
m_longTermMap
std::unordered_map< uint32_t, Ptr<const LongTerm> > ns3::ThreeGppSpectrumPropagationLossModel::m_longTermMap mutable private
map containing the long term components
Definition at line 192 of file three-gpp-spectrum-propagation-loss-model.h.
Referenced by DoDispose(), and GetLongTerm().
m_uniformRv
Ptr<UniformRandomVariable> ns3::ThreeGppSpectrumPropagationLossModel::m_uniformRv private
uniform random variable, used to compute the additional Doppler contribution
Definition at line 198 of file three-gpp-spectrum-propagation-loss-model.h.
Referenced by ThreeGppSpectrumPropagationLossModel(), and CalcBeamformingGain().
m_vScatt
double ns3::ThreeGppSpectrumPropagationLossModel::m_vScatt private
value used to compute the additional Doppler contribution for the delayed paths
Definition at line 197 of file three-gpp-spectrum-propagation-loss-model.h.
Referenced by CalcBeamformingGain(), and GetTypeId().
The documentation for this class was generated from the following files:
src/spectrum/model/three-gpp-spectrum-propagation-loss-model.h
src/spectrum/model/three-gpp-spectrum-propagation-loss-model.cc