ns-3: ns3::GtkConfigStore Class Reference
ns3::GtkConfigStore Class Reference
Configuration Store/Load
A class that provides a GTK-based front end to ns3::ConfigStore.
#include "gtk-config-store.h"
Public Member Functions
GtkConfigStore ()
void ConfigureAttributes (void)
Process attribute values.
void ConfigureDefaults (void)
Process default values.
Detailed Description
A class that provides a GTK-based front end to ns3::ConfigStore.
Definition at line 30 of file gtk-config-store.h.
Constructor & Destructor Documentation
GtkConfigStore()
ns3::GtkConfigStore::GtkConfigStore ()
Definition at line 31 of file gtk-config-store.cc.
Member Function Documentation
ConfigureAttributes()
void ns3::GtkConfigStore::ConfigureAttributes (void)
Process attribute values.
Definition at line 87 of file gtk-config-store.cc.
References ns3::ModelCreator::Build(), ns3::clean_model_callback(), ns3::COL_LAST, ns3::create_view(), ns3::delete_event_callback(), ns3::exit_clicked_callback(), ns3::load_clicked_attribute(), ns3::save_clicked_attribute(), and visualizer.ipython_view::window.
ConfigureDefaults()
void ns3::GtkConfigStore::ConfigureDefaults (void)
Process default values.
Definition at line 36 of file gtk-config-store.cc.
References ns3::ModelTypeidCreator::Build(), ns3::clean_model_callback_config_default(), ns3::COL_LAST, ns3::create_view_config_default(), ns3::delete_event_callback(), ns3::exit_clicked_callback(), ns3::load_clicked_default(), ns3::save_clicked_default(), and visualizer.ipython_view::window.
The documentation for this class was generated from the following files:
src/config-store/model/gtk-config-store.h
src/config-store/model/gtk-config-store.cc