ns-3: ns3::TcpVegas Class Reference
ns3::TcpVegas Class Reference
Internet » TCP » Congestion Control Algorithms.
An implementation of TCP Vegas.
#include "tcp-vegas.h"
Public Member Functions
TcpVegas (const TcpVegas &sock)
Copy constructor.
TcpVegas (void)
Create an unbound tcp socket.
virtual ~TcpVegas (void)
virtual void CongestionStateSet (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCongState_t newState)
Enable/disable Vegas algorithm depending on the congestion state.
virtual Ptr< TcpCongestionOps > Fork ()
Copy the congestion control algorithm across sockets.
virtual std::string GetName () const
Get the name of the congestion control algorithm.
virtual uint32_t GetSsThresh (Ptr< const TcpSocketState > tcb, uint32_t bytesInFlight)
Get slow start threshold following Vegas principle.
virtual void IncreaseWindow (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
Adjust cwnd following Vegas linear increase/decrease algorithm.
virtual void PktsAcked (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked, const Time &rtt)
Compute RTTs needed to execute Vegas algorithm.
Public Member Functions inherited from ns3::TcpNewReno
TcpNewReno ()
TcpNewReno (const TcpNewReno &sock)
Copy constructor.
~TcpNewReno ()
Public Member Functions inherited from ns3::TcpCongestionOps
TcpCongestionOps ()
TcpCongestionOps (const TcpCongestionOps &other)
Copy constructor.
virtual ~TcpCongestionOps ()
virtual void CongControl (Ptr< TcpSocketState > tcb, const TcpRateOps::TcpRateConnection &rc, const TcpRateOps::TcpRateSample &rs)
Called when packets are delivered to update cwnd and pacing rate.
virtual void CwndEvent (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCAEvent_t event)
Trigger events/calculations on occurrence of congestion window event.
virtual bool HasCongControl () const
Returns true when Congestion Control Algorithm implements CongControl.
virtual void Init (Ptr< TcpSocketState > tcb)
Set configuration required by congestion control algorithm.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpNewReno
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpCongestionOps
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void DisableVegas ()
Stop taking Vegas samples.
void EnableVegas (Ptr< TcpSocketState > tcb)
Enable Vegas algorithm to start taking Vegas samples.
Private Attributes
uint32_t m_alpha
Alpha threshold, lower bound of packets in network.
Time m_baseRtt
Minimum of all Vegas RTT measurements seen during connection.
SequenceNumber32 m_begSndNxt
Right edge during last RTT.
uint32_t m_beta
Beta threshold, upper bound of packets in network.
uint32_t m_cntRtt
Number of RTT measurements during last RTT.
bool m_doingVegasNow
If true, do Vegas for this RTT.
uint32_t m_gamma
Gamma threshold, limit on increase.
Time m_minRtt
Minimum of all RTT measurements within last RTT.
Additional Inherited Members
Protected Member Functions inherited from ns3::TcpNewReno
virtual void CongestionAvoidance (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
NewReno congestion avoidance.
virtual uint32_t SlowStart (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
Tcp NewReno slow start algorithm.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
An implementation of TCP Vegas.
TCP Vegas is a pure delay-based congestion control algorithm implementing a proactive scheme that tries to prevent packet drops by maintaining a small backlog at the bottleneck queue.
Vegas continuously measures the actual throughput a connection achieves as shown in Equation (1) and compares it with the expected throughput calculated in Equation (2). The difference between these 2 sending rates in Equation (3) reflects the amount of extra packets being queued at the bottleneck.
         actual = cwnd / RTT        (1)
         expected = cwnd / BaseRTT  (2)
         diff = expected - actual   (3)
To avoid congestion, Vegas linearly increases/decreases its congestion window to ensure the diff value fall between the 2 predefined thresholds, alpha and beta. diff and another threshold, gamma, are used to determine when Vegas should change from its slow-start mode to linear increase/decrease mode.
Following the implementation of Vegas in Linux, we use 2, 4, and 1 as the default values of alpha, beta, and gamma, respectively.
More information: http://dx.doi.org/10.1109/49.464716
Config Paths
ns3::TcpVegas is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::TcpL4Protocol/SocketList/[i]/CongestionOps/$ns3::TcpNewReno/$ns3::TcpVegas"
"/NodeList/[i]/$ns3::TcpL4Protocol/SocketList/[i]/CongestionOps/$ns3::TcpVegas"
Attributes
Alpha: Lower bound of packets in network
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 2
Flags: construct write read
Beta: Upper bound of packets in network
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 4
Flags: construct write read
Gamma: Limit on increase
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 1
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 72 bytes (on a 64-bit architecture).
Definition at line 65 of file tcp-vegas.h.
Constructor & Destructor Documentation
TcpVegas() [1/2]
ns3::TcpVegas::TcpVegas (void)
Create an unbound tcp socket.
Definition at line 60 of file tcp-vegas.cc.
References NS_LOG_FUNCTION.
TcpVegas() [2/2]
ns3::TcpVegas::TcpVegas (const TcpVegas & sock)
Copy constructor.
Parameters
sock the object to copy
Definition at line 74 of file tcp-vegas.cc.
References NS_LOG_FUNCTION.
~TcpVegas()
ns3::TcpVegas::~TcpVegas (void) virtual
Definition at line 88 of file tcp-vegas.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CongestionStateSet()
void ns3::TcpVegas::CongestionStateSet (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCongState_t newState) virtual
Enable/disable Vegas algorithm depending on the congestion state.
We only start a Vegas cycle when we are in normal congestion state (CA_OPEN state).
Parameters
tcb internal congestion state
newState new congestion state to which the TCP is going to switch
Reimplemented from ns3::TcpCongestionOps.
Definition at line 141 of file tcp-vegas.cc.
References ns3::TcpSocketState::CA_OPEN, DisableVegas(), EnableVegas(), and NS_LOG_FUNCTION.
DisableVegas()
void ns3::TcpVegas::DisableVegas () private
Stop taking Vegas samples.
Definition at line 133 of file tcp-vegas.cc.
References m_doingVegasNow, and NS_LOG_FUNCTION.
Referenced by CongestionStateSet().
EnableVegas()
void ns3::TcpVegas::EnableVegas (Ptr< TcpSocketState > tcb) private
Enable Vegas algorithm to start taking Vegas samples.
Vegas algorithm is enabled in the following situations:
at the establishment of a connection
after an RTO
after fast recovery
when an idle connection is restarted
Parameters
tcb internal congestion state
Definition at line 122 of file tcp-vegas.cc.
References m_begSndNxt, m_cntRtt, m_doingVegasNow, m_minRtt, ns3::TcpSocketState::m_nextTxSequence, ns3::Time::Max(), and NS_LOG_FUNCTION.
Referenced by CongestionStateSet().
Fork()
Ptr< TcpCongestionOps > ns3::TcpVegas::Fork () virtual
Copy the congestion control algorithm across sockets.
Returns
a pointer of the copied object
Reimplemented from ns3::TcpNewReno.
Definition at line 94 of file tcp-vegas.cc.
GetName()
std::string ns3::TcpVegas::GetName () const virtual
Get the name of the congestion control algorithm.
Returns
A string identifying the name
Reimplemented from ns3::TcpNewReno.
Definition at line 283 of file tcp-vegas.cc.
GetSsThresh()
uint32_t ns3::TcpVegas::GetSsThresh (Ptr< const TcpSocketState > tcb, uint32_t bytesInFlight) virtual
Get slow start threshold following Vegas principle.
Parameters
tcb internal congestion state
bytesInFlight bytes in flight
Returns
the slow start threshold value
Reimplemented from ns3::TcpNewReno.
Definition at line 289 of file tcp-vegas.cc.
References max, min, and NS_LOG_FUNCTION.
Referenced by IncreaseWindow().
GetTypeId()
TypeId ns3::TcpVegas::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 38 of file tcp-vegas.cc.
References m_alpha, m_beta, m_gamma, ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
IncreaseWindow()
void ns3::TcpVegas::IncreaseWindow (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked) virtual
Adjust cwnd following Vegas linear increase/decrease algorithm.
Parameters
tcb internal congestion state
segmentsAcked count of segments ACKed
Reimplemented from ns3::TcpNewReno.
Definition at line 156 of file tcp-vegas.cc.
References ns3::TcpSocketState::GetCwndInSegments(), ns3::Time::GetSeconds(), GetSsThresh(), ns3::TcpNewReno::IncreaseWindow(), m_alpha, m_baseRtt, m_begSndNxt, m_beta, m_cntRtt, ns3::TcpSocketState::m_cWnd, m_doingVegasNow, m_gamma, ns3::TcpSocketState::m_lastAckedSeq, m_minRtt, ns3::TcpSocketState::m_nextTxSequence, ns3::TcpSocketState::m_segmentSize, ns3::TcpSocketState::m_ssThresh, ns3::Time::Max(), max, min, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, and ns3::TcpNewReno::SlowStart().
PktsAcked()
void ns3::TcpVegas::PktsAcked (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked, const Time & rtt) virtual
Compute RTTs needed to execute Vegas algorithm.
The function filters RTT samples from the last RTT to find the current smallest propagation delay + queueing delay (minRtt). We take the minimum to avoid the effects of delayed ACKs.
The function also min-filters all RTT measurements seen to find the propagation delay (baseRtt).
Parameters
tcb internal congestion state
segmentsAcked count of segments ACKed
rtt last RTT
Reimplemented from ns3::TcpCongestionOps.
Definition at line 100 of file tcp-vegas.cc.
References ns3::Time::IsZero(), m_baseRtt, m_cntRtt, m_minRtt, min, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Member Data Documentation
m_alpha
uint32_t ns3::TcpVegas::m_alpha private
Alpha threshold, lower bound of packets in network.
Definition at line 159 of file tcp-vegas.h.
Referenced by GetTypeId(), and IncreaseWindow().
m_baseRtt
Time ns3::TcpVegas::m_baseRtt private
Minimum of all Vegas RTT measurements seen during connection.
Definition at line 162 of file tcp-vegas.h.
Referenced by IncreaseWindow(), and PktsAcked().
m_begSndNxt
SequenceNumber32 ns3::TcpVegas::m_begSndNxt private
Right edge during last RTT.
Definition at line 166 of file tcp-vegas.h.
Referenced by EnableVegas(), and IncreaseWindow().
m_beta
uint32_t ns3::TcpVegas::m_beta private
Beta threshold, upper bound of packets in network.
Definition at line 160 of file tcp-vegas.h.
Referenced by GetTypeId(), and IncreaseWindow().
m_cntRtt
uint32_t ns3::TcpVegas::m_cntRtt private
Number of RTT measurements during last RTT.
Definition at line 164 of file tcp-vegas.h.
Referenced by EnableVegas(), IncreaseWindow(), and PktsAcked().
m_doingVegasNow
bool ns3::TcpVegas::m_doingVegasNow private
If true, do Vegas for this RTT.
Definition at line 165 of file tcp-vegas.h.
Referenced by DisableVegas(), EnableVegas(), and IncreaseWindow().
m_gamma
uint32_t ns3::TcpVegas::m_gamma private
Gamma threshold, limit on increase.
Definition at line 161 of file tcp-vegas.h.
Referenced by GetTypeId(), and IncreaseWindow().
m_minRtt
Time ns3::TcpVegas::m_minRtt private
Minimum of all RTT measurements within last RTT.
Definition at line 163 of file tcp-vegas.h.
Referenced by EnableVegas(), IncreaseWindow(), and PktsAcked().
The documentation for this class was generated from the following files:
src/internet/model/tcp-vegas.h
src/internet/model/tcp-vegas.cc