ns-3: ns3::NscTcpSocketImpl Class Reference
ns3::NscTcpSocketImpl Class Reference
Network » Socket | Internet » NscTcp
Socket logic for the NSC TCP sockets.
#include "nsc-tcp-socket-impl.h"
Public Member Functions
NscTcpSocketImpl ()
Create an unbound tcp socket.
NscTcpSocketImpl (const NscTcpSocketImpl &sock)
Clone a TCP socket, for use upon receiving a connection request in LISTEN state.
virtual ~NscTcpSocketImpl ()
virtual int Bind (const Address &address)
Allocate a local endpoint for this socket.
virtual int Bind (void)
Allocate a local IPv4 endpoint for this socket.
virtual int Bind6 (void)
Allocate a local IPv6 endpoint for this socket.
virtual void BindToNetDevice (Ptr< NetDevice > netdevice)
Bind a socket to specific device.
virtual int Close (void)
Close a socket.
virtual int Connect (const Address &address)
Initiate a connection to a remote host.
virtual bool GetAllowBroadcast () const
Query whether broadcast datagram transmissions are allowed.
virtual enum SocketErrno GetErrno (void) const
Get last error number.
virtual Ptr< Node > GetNode (void) const
Return the node this socket is associated with.
virtual int GetPeerName (Address &address) const
Get the peer address of a connected socket.
virtual uint32_t GetRxAvailable (void) const
Return number of bytes which can be returned from one or multiple calls to Recv.
virtual enum SocketType GetSocketType (void) const
virtual int GetSockName (Address &address) const
Get socket address.
virtual uint32_t GetTxAvailable (void) const
Returns the number of bytes which can be sent in a single call to Send.
virtual int Listen (void)
Listen for incoming connections.
virtual Ptr< Packet > Recv (uint32_t maxSize, uint32_t flags)
Read data from the socket.
virtual Ptr< Packet > RecvFrom (uint32_t maxSize, uint32_t flags, Address &fromAddress)
Read a single packet from the socket and retrieve the sender address.
virtual int Send (Ptr< Packet > p, uint32_t flags)
Send data (or dummy data) to the remote host.
virtual int SendTo (Ptr< Packet > p, uint32_t flags, const Address &toAddress)
Send data to a specified peer.
virtual bool SetAllowBroadcast (bool allowBroadcast)
Configure whether broadcast datagram transmissions are allowed.
void SetNode (Ptr< Node > node)
Set the associated node.
void SetTcp (Ptr< NscTcpL4Protocol > tcp)
Set the associated TCP L4 protocol.
virtual int ShutdownRecv (void)
virtual int ShutdownSend (void)
Public Member Functions inherited from ns3::TcpSocket
TcpSocket (void)
virtual ~TcpSocket (void)
Public Member Functions inherited from ns3::Socket
Socket (void)
virtual ~Socket (void)
Ptr< NetDevice > GetBoundNetDevice ()
Returns socket's bound NetDevice, if any.
uint8_t GetIpTos (void) const
Query the value of IP Type of Service of this socket.
virtual uint8_t GetIpTtl (void) const
Query the value of IP Time to Live field of this socket.
virtual uint8_t GetIpv6HopLimit (void) const
Query the value of IP Hop Limit field of this socket.
uint8_t GetIpv6Tclass (void) const
Query the value of IPv6 Traffic Class field of this socket.
uint8_t GetPriority (void) const
Query the priority value of this socket.
virtual void Ipv6JoinGroup (Ipv6Address address)
Joins a IPv6 multicast group without filters.
virtual void Ipv6JoinGroup (Ipv6Address address, Ipv6MulticastFilterMode filterMode, std::vector< Ipv6Address > sourceAddresses)
Joins a IPv6 multicast group.
virtual void Ipv6LeaveGroup (void)
Leaves IPv6 multicast group this socket is joined to.
bool IsIpRecvTos (void) const
Ask if the socket is currently passing information about IP Type of Service up the stack.
bool IsIpRecvTtl (void) const
Ask if the socket is currently passing information about IP_TTL up the stack.
bool IsIpv6RecvHopLimit (void) const
Ask if the socket is currently passing information about IPv6 Hop Limit up the stack.
bool IsIpv6RecvTclass (void) const
Ask if the socket is currently passing information about IPv6 Traffic Class up the stack.
bool IsRecvPktInfo () const
Get status indicating whether enable/disable packet information to socket.
int Recv (uint8_t *buf, uint32_t size, uint32_t flags)
Recv data (or dummy data) from the remote host.
Ptr< Packet > Recv (void)
Read a single packet from the socket.
Ptr< Packet > RecvFrom (Address &fromAddress)
Read a single packet from the socket and retrieve the sender address.
int RecvFrom (uint8_t *buf, uint32_t size, uint32_t flags, Address &fromAddress)
Read a single packet from the socket and retrieve the sender address.
int Send (const uint8_t *buf, uint32_t size, uint32_t flags)
Send data (or dummy data) to the remote host.
int Send (Ptr< Packet > p)
Send data (or dummy data) to the remote host.
int SendTo (const uint8_t *buf, uint32_t size, uint32_t flags, const Address &address)
Send data to a specified peer.
void SetAcceptCallback (Callback< bool, Ptr< Socket >, const Address & > connectionRequest, Callback< void, Ptr< Socket >, const Address & > newConnectionCreated)
Accept connection requests from remote hosts.
void SetCloseCallbacks (Callback< void, Ptr< Socket > > normalClose, Callback< void, Ptr< Socket > > errorClose)
Detect socket recv() events such as graceful shutdown or error.
void SetConnectCallback (Callback< void, Ptr< Socket > > connectionSucceeded, Callback< void, Ptr< Socket > > connectionFailed)
Specify callbacks to allow the caller to determine if the connection succeeds of fails.
void SetDataSentCallback (Callback< void, Ptr< Socket >, uint32_t > dataSent)
Notify application when a packet has been sent from transport protocol (non-standard socket call)
void SetIpRecvTos (bool ipv4RecvTos)
Tells a socket to pass information about IP Type of Service up the stack.
void SetIpRecvTtl (bool ipv4RecvTtl)
Tells a socket to pass information about IP_TTL up the stack.
void SetIpTos (uint8_t ipTos)
Manually set IP Type of Service field.
virtual void SetIpTtl (uint8_t ipTtl)
Manually set IP Time to Live field.
virtual void SetIpv6HopLimit (uint8_t ipHopLimit)
Manually set IPv6 Hop Limit.
void SetIpv6RecvHopLimit (bool ipv6RecvHopLimit)
Tells a socket to pass information about IPv6 Hop Limit up the stack.
void SetIpv6RecvTclass (bool ipv6RecvTclass)
Tells a socket to pass information about IPv6 Traffic Class up the stack.
void SetIpv6Tclass (int ipTclass)
Manually set IPv6 Traffic Class field.
void SetPriority (uint8_t priority)
Manually set the socket priority.
void SetRecvCallback (Callback< void, Ptr< Socket > >)
Notify application when new data is available to be read.
void SetRecvPktInfo (bool flag)
Enable/Disable receive packet information to socket.
void SetSendCallback (Callback< void, Ptr< Socket >, uint32_t > sendCb)
Notify application when space in transmit buffer is added.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpSocket
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Socket
static Ptr< Socket > CreateSocket (Ptr< Node > node, TypeId tid)
This method wraps the creation of sockets that is performed on a given node by a SocketFactory specified by TypeId.
static TypeId GetTypeId (void)
Get the type ID.
static uint8_t IpTos2Priority (uint8_t ipTos)
Return the priority corresponding to a given TOS value.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
bool Accept (void)
Accept an incoming connection.
void CompleteFork (void)
Complete the Fork operations (after a connection has been accepted)
void ConnectionSucceeded ()
Called when a connection is in Established state.
Ptr< NscTcpSocketImpl > Copy ()
Copy self.
void Destroy (void)
Kill this socket by zeroing its attributes (IPv4)
int FinishBind (void)
Finish the binding process.
void ForwardUp (Ptr< Packet > p, Ipv4Header header, uint16_t port, Ptr< Ipv4Interface > incomingInterface)
Called by the L3 protocol when it received a packet to pass on to TCP.
virtual uint32_t GetAdvWin (void) const
Get the Advertised Window size.
virtual Time GetConnTimeout (void) const
Get the connection timeout.
virtual uint32_t GetDataRetries (void) const
Get the number of data transmission retries before giving up.
virtual uint32_t GetDelAckMaxCount (void) const
Get the number of packet to fire an ACK before delay timeout.
virtual Time GetDelAckTimeout (void) const
Get the time to delay an ACK.
virtual uint32_t GetInitialCwnd (void) const
Get the initial Congestion Window.
virtual uint32_t GetInitialSSThresh (void) const
Get the initial Slow Start Threshold.
enum Socket::SocketErrno GetNativeNs3Errno (int err) const
Translate between a NSC error and a ns-3 error code.
virtual Time GetPersistTimeout (void) const
Get the timeout for persistent connection.
virtual uint32_t GetRcvBufSize (void) const
Get the receive buffer size.
virtual uint32_t GetSegSize (void) const
Get the segment size.
virtual uint32_t GetSndBufSize (void) const
Get the send buffer size.
virtual uint32_t GetSynRetries (void) const
Get the number of connection retries before giving up.
virtual bool GetTcpNoDelay (void) const
Check if Nagle's algorithm is enabled or not.
void NSCWakeup (void)
Called by NscTcpSocketImpl::ForwardUp()
bool ReadPendingData (void)
Read all the pending data.
bool SendPendingData (void)
Send all the pending data.
virtual void SetAdvWin (uint32_t window)
Set the Advertised Window size.
virtual void SetConnTimeout (Time timeout)
Set the connection timeout.
virtual void SetDataRetries (uint32_t retries)
Set the number of data transmission retries before giving up.
virtual void SetDelAckMaxCount (uint32_t count)
Set the number of packet to fire an ACK before delay timeout.
virtual void SetDelAckTimeout (Time timeout)
Set the time to delay an ACK.
virtual void SetInitialCwnd (uint32_t cwnd)
Set the initial Congestion Window.
virtual void SetInitialSSThresh (uint32_t threshold)
Set the initial Slow Start Threshold.
virtual void SetPersistTimeout (Time timeout)
Set the timeout for persistent connection.
virtual void SetRcvBufSize (uint32_t size)
Set the receive buffer size.
virtual void SetSegSize (uint32_t size)
Set the segment size.
virtual void SetSndBufSize (uint32_t size)
Set the send buffer size.
virtual void SetSynRetries (uint32_t count)
Set the number of connection retries before giving up.
virtual void SetTcpNoDelay (bool noDelay)
Enable/Disable Nagle's algorithm.
Private Attributes
uint32_t m_advertisedWindowSize
Window to advertise.
bool m_closeOnEmpty
true if socket will close when buffer is empty
Time m_cnTimeout
Timeout for connection retry.
bool m_connected
Connection established.
TracedValue< uint32_t > m_cWnd
Congestion window.
uint32_t m_dataRetries
Count of remaining data retransmission attempts.
uint32_t m_delAckMaxCount
Number of packet to fire an ACK before delay timeout.
Time m_delAckTimeout
Time to delay an ACK.
std::queue< Ptr< Packet > > m_deliveryQueue
receive buffer
Ipv4EndPoint * m_endPoint
the IPv4 endpoint
enum SocketErrno m_errno
last error number
uint32_t m_initialCWnd
Initial cWnd value.
uint32_t m_initialSsThresh
Initial Slow Start Threshold.
Time m_lastMeasuredRtt
Last measured RTT.
Ipv4Address m_localAddress
local address
uint16_t m_localPort
local port
Ptr< Node > m_node
the associated node
bool m_noDelay
Disable ACk delay.
INetStreamSocket * m_nscTcpSocket
the real NSC TCP socket
InetSocketAddress m_peerAddress
peer IP and port
Time m_persistTimeout
Time between sending 1-byte probes.
uint32_t m_rcvBufSize
maximum receive socket buffer size
Ipv4Address m_remoteAddress
peer IP address
uint16_t m_remotePort
peer port
uint32_t m_rxAvailable
receive buffer available size
uint32_t m_rxWindowSize
Receive window size.
uint32_t m_segmentSize
SegmentSize.
bool m_shutdownRecv
Receive no longer allowed.
bool m_shutdownSend
Send no longer allowed.
uint32_t m_sndBufSize
buffer limit for the outgoing queue
TracedValue< uint32_t > m_ssThresh
Slow Start Threshold.
TracedValue< TcpStates_t > m_state
state information
uint32_t m_synRetries
Count of remaining connection retries.
Ptr< NscTcpL4Protocol > m_tcp
the associated TCP L4 protocol
std::queue< Ptr< Packet > > m_txBuffer
transmission buffer
uint32_t m_txBufferSize
transmission buffer size
Related Functions
(Note that these are not member functions.)
class Tcp
Tcp friend class.
Additional Inherited Members
Public Types inherited from ns3::TcpSocket
enum TcpStates_t {
CLOSED = 0 , LISTEN , SYN_SENT , SYN_RCVD ,
ESTABLISHED , CLOSE_WAIT , LAST_ACK , FIN_WAIT_1 ,
FIN_WAIT_2 , CLOSING , TIME_WAIT , LAST_STATE
}
Names of the 11 TCP states.
Public Types inherited from ns3::Socket
enum Ipv6MulticastFilterMode { INCLUDE =1 , EXCLUDE }
Enumeration of the possible filter of a socket.
enum SocketErrno {
ERROR_NOTERROR , ERROR_ISCONN , ERROR_NOTCONN , ERROR_MSGSIZE ,
ERROR_AGAIN , ERROR_SHUTDOWN , ERROR_OPNOTSUPP , ERROR_AFNOSUPPORT ,
ERROR_INVAL , ERROR_BADF , ERROR_NOROUTETOHOST , ERROR_NODEV ,
ERROR_ADDRNOTAVAIL , ERROR_ADDRINUSE , SOCKET_ERRNO_LAST
}
Enumeration of the possible errors returned by a socket.
enum SocketPriority {
NS3_PRIO_BESTEFFORT = 0 , NS3_PRIO_FILLER = 1 , NS3_PRIO_BULK = 2 , NS3_PRIO_INTERACTIVE_BULK = 4 ,
NS3_PRIO_INTERACTIVE = 6 , NS3_PRIO_CONTROL = 7
}
Enumeration of the possible socket priorities.
enum SocketType { NS3_SOCK_STREAM , NS3_SOCK_SEQPACKET , NS3_SOCK_DGRAM , NS3_SOCK_RAW }
Enumeration of the possible socket types.
Static Public Attributes inherited from ns3::TcpSocket
static const char *const TcpStateName [TcpSocket::LAST_STATE]
Literal names of TCP states for use in log messages.
Protected Member Functions inherited from ns3::Socket
virtual void DoDispose (void)
Destructor implementation.
bool IsManualIpTtl (void) const
Checks if the socket has a specific IPv4 TTL set.
bool IsManualIpv6HopLimit (void) const
Checks if the socket has a specific IPv6 Hop Limit set.
bool IsManualIpv6Tclass (void) const
Checks if the socket has a specific IPv6 Tclass set.
void NotifyConnectionFailed (void)
Notify through the callback (if set) that the connection has not been established due to an error.
bool NotifyConnectionRequest (const Address &from)
Notify through the callback (if set) that an incoming connection is being requested by a remote host.
void NotifyConnectionSucceeded (void)
Notify through the callback (if set) that the connection has been established.
void NotifyDataRecv (void)
Notify through the callback (if set) that some data have been received.
void NotifyDataSent (uint32_t size)
Notify through the callback (if set) that some data have been sent.
void NotifyErrorClose (void)
Notify through the callback (if set) that the connection has been closed due to an error.
void NotifyNewConnectionCreated (Ptr< Socket > socket, const Address &from)
Notify through the callback (if set) that a new connection has been created.
void NotifyNormalClose (void)
Notify through the callback (if set) that the connection has been closed.
void NotifySend (uint32_t spaceAvailable)
Notify through the callback (if set) that some data have been sent.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Socket
Ptr< NetDevice > m_boundnetdevice
the device this socket is bound to (might be null).
Ipv6Address m_ipv6MulticastGroupAddress
IPv6 multicast group address.
bool m_recvPktInfo
if the socket should add packet info tags to the packet forwarded to L4.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Socket logic for the NSC TCP sockets.
Most of the TCP internal logic is handled by the NSC tcp library itself; this class maps ns3::Socket calls to the NSC TCP library.
Definition at line 53 of file nsc-tcp-socket-impl.h.
Constructor & Destructor Documentation
NscTcpSocketImpl() [1/2]
ns3::NscTcpSocketImpl::NscTcpSocketImpl ()
Create an unbound tcp socket.
Definition at line 74 of file nsc-tcp-socket-impl.cc.
References NS_LOG_FUNCTION.
NscTcpSocketImpl() [2/2]
ns3::NscTcpSocketImpl::NscTcpSocketImpl (const NscTcpSocketImpl & sock)
Clone a TCP socket, for use upon receiving a connection request in LISTEN state.
Parameters
sock the original Tcp Socket
Definition at line 93 of file nsc-tcp-socket-impl.cc.
References m_txBuffer, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
~NscTcpSocketImpl()
ns3::NscTcpSocketImpl::~NscTcpSocketImpl () virtual
Note that this piece of code is a bit tricky: when DeAllocate is called, it will call into Ipv4EndPointDemux::Deallocate which triggers a delete of the associated endPoint which triggers in turn a call to the method NscTcpSocketImpl::Destroy below will will zero the m_endPoint field.
Definition at line 138 of file nsc-tcp-socket-impl.cc.
References m_endPoint, m_node, m_tcp, NS_ASSERT, and NS_LOG_FUNCTION.
Member Function Documentation
Accept()
bool ns3::NscTcpSocketImpl::Accept (void) private
Accept an incoming connection.
Returns
true on success
Definition at line 585 of file nsc-tcp-socket-impl.cc.
References INetStreamSocket::accept(), ns3::TcpSocket::CLOSED, CompleteFork(), Copy(), INetStreamSocket::is_listening(), ns3::TcpSocket::LISTEN, m_nscTcpSocket, m_state, NS_ASSERT, NS_LOG_LOGIC, and ns3::Simulator::ScheduleNow().
Referenced by NSCWakeup().
Bind() [1/2]
int ns3::NscTcpSocketImpl::Bind (const Address & address) virtual
Allocate a local endpoint for this socket.
Parameters
address the address to try to allocate
Returns
0 on success, -1 on failure.
Implements ns3::Socket.
Definition at line 236 of file nsc-tcp-socket-impl.cc.
References first::address, ns3::InetSocketAddress::ConvertFrom(), ns3::Socket::ERROR_INVAL, FinishBind(), ns3::Ipv4Address::GetAny(), ns3::Socket::GetBoundNetDevice(), ns3::InetSocketAddress::GetIpv4(), ns3::InetSocketAddress::GetPort(), ns3::InetSocketAddress::IsMatchingType(), m_endPoint, m_localPort, m_tcp, NS_LOG_FUNCTION, NS_LOG_LOGIC, and port.
Bind() [2/2]
int ns3::NscTcpSocketImpl::Bind (void) virtual
Allocate a local IPv4 endpoint for this socket.
Returns
0 on success, -1 on failure.
Implements ns3::Socket.
Definition at line 222 of file nsc-tcp-socket-impl.cc.
References FinishBind(), m_endPoint, m_tcp, and NS_LOG_FUNCTION.
Referenced by Connect().
Bind6()
int ns3::NscTcpSocketImpl::Bind6 (void) virtual
Allocate a local IPv6 endpoint for this socket.
Returns
0 on success, -1 on failure.
Implements ns3::Socket.
Definition at line 229 of file nsc-tcp-socket-impl.cc.
References ns3::Socket::ERROR_AFNOSUPPORT, m_errno, and NS_LOG_LOGIC.
BindToNetDevice()
void ns3::NscTcpSocketImpl::BindToNetDevice (Ptr< NetDevice > netdevice) virtual
Bind a socket to specific device.
This method corresponds to using setsockopt() SO_BINDTODEVICE of real network or BSD sockets. If set on a socket, this option will force packets to leave the bound device regardless of the device that IP routing would naturally choose. In the receive direction, only packets received from the bound interface will be delivered.
This option has no particular relationship to binding sockets to an address via Socket::Bind (). It is possible to bind sockets to a specific IP address on the bound interface by calling both Socket::Bind (address) and Socket::BindToNetDevice (device), but it is also possible to bind to mismatching device and address, even if the socket can not receive any packets as a result.
Parameters
netdevice Pointer to NetDevice of desired interface
Returns
nothing
Reimplemented from ns3::Socket.
Definition at line 273 of file nsc-tcp-socket-impl.cc.
References ns3::Ipv4EndPoint::BindToNetDevice(), ns3::Socket::BindToNetDevice(), m_endPoint, and NS_LOG_FUNCTION.
Close()
int ns3::NscTcpSocketImpl::Close (void) virtual
Close a socket.
Returns
zero on success, -1 on failure.
After the Close call, the socket is no longer valid, and cannot safely be used for subsequent operations.
Implements ns3::Socket.
Definition at line 300 of file nsc-tcp-socket-impl.cc.
References ns3::TcpSocket::CLOSED, INetStreamSocket::disconnect(), m_closeOnEmpty, m_nscTcpSocket, m_state, m_txBuffer, NS_LOG_FUNCTION, NS_LOG_LOGIC, and ShutdownSend().
CompleteFork()
void ns3::NscTcpSocketImpl::CompleteFork (void) private
Complete the Fork operations (after a connection has been accepted)
Definition at line 530 of file nsc-tcp-socket-impl.cc.
References ns3::Ipv4Address::Deserialize(), Destroy(), ns3::TcpSocket::ESTABLISHED, ForwardUp(), INetStreamSocket::getpeername(), INetStreamSocket::getsockname(), ns3::TcpSocket::LISTEN, m_endPoint, m_localAddress, m_localPort, m_nscTcpSocket, m_peerAddress, m_remoteAddress, m_remotePort, m_state, m_tcp, ns3::MakeCallback(), ns3::Socket::NotifyNewConnectionCreated(), NS_ASSERT, NS_LOG_LOGIC, ns3::Ipv4EndPoint::SetDestroyCallback(), and ns3::Ipv4EndPoint::SetRxCallback().
Referenced by Accept().
Connect()
int ns3::NscTcpSocketImpl::Connect (const Address & address) virtual
Initiate a connection to a remote host.
Parameters
address Address of remote.
Returns
0 on success, -1 on error (in which case errno is set).
Implements ns3::Socket.
Definition at line 324 of file nsc-tcp-socket-impl.cc.
References first::address, Bind(), INetStreamSocket::connect(), ns3::InetSocketAddress::ConvertFrom(), ns3::InetSocketAddress::GetIpv4(), ns3::InetSocketAddress::GetPort(), m_endPoint, m_nscTcpSocket, m_remoteAddress, m_remotePort, m_state, NS_ASSERT, NS_LOG_FUNCTION, ns3::Ipv4Address::Print(), and ns3::TcpSocket::SYN_SENT.
ConnectionSucceeded()
void ns3::NscTcpSocketImpl::ConnectionSucceeded () private
Called when a connection is in Established state.
Definition at line 567 of file nsc-tcp-socket-impl.cc.
References ns3::Ipv4Address::Deserialize(), INetStreamSocket::getsockname(), m_localAddress, m_localPort, m_nscTcpSocket, m_remoteAddress, m_remotePort, ns3::Socket::NotifyConnectionSucceeded(), and NS_LOG_LOGIC.
Referenced by NSCWakeup().
Copy()
Ptr< NscTcpSocketImpl > ns3::NscTcpSocketImpl::Copy (void) private
Copy self.
Returns
a copy of self
Definition at line 723 of file nsc-tcp-socket-impl.cc.
Referenced by Accept().
Destroy()
void ns3::NscTcpSocketImpl::Destroy (void) private
Kill this socket by zeroing its attributes (IPv4)
This is a callback function configured to m_endpoint in SetupCallback(), invoked when the endpoint is destroyed.
Definition at line 199 of file nsc-tcp-socket-impl.cc.
References m_endPoint, m_node, m_tcp, and NS_LOG_FUNCTION.
Referenced by CompleteFork(), and FinishBind().
FinishBind()
int ns3::NscTcpSocketImpl::FinishBind (void) private
Finish the binding process.
Returns
0 on success, -1 on failure
Definition at line 207 of file nsc-tcp-socket-impl.cc.
References Destroy(), ForwardUp(), ns3::Ipv4EndPoint::GetLocalAddress(), ns3::Ipv4EndPoint::GetLocalPort(), m_endPoint, m_localAddress, m_localPort, ns3::MakeCallback(), NS_LOG_FUNCTION, ns3::Ipv4EndPoint::SetDestroyCallback(), and ns3::Ipv4EndPoint::SetRxCallback().
Referenced by Bind().
ForwardUp()
void ns3::NscTcpSocketImpl::ForwardUp (Ptr< Packet > p, Ipv4Header header, uint16_t port, Ptr< Ipv4Interface > incomingInterface) private
Called by the L3 protocol when it received a packet to pass on to TCP.
Parameters
p the incoming packet
header the packet's IPv4 header
port the incoming port
incomingInterface the incoming interface
Definition at line 524 of file nsc-tcp-socket-impl.cc.
References NSCWakeup().
Referenced by CompleteFork(), and FinishBind().
GetAdvWin()
uint32_t ns3::NscTcpSocketImpl::GetAdvWin (void) const private virtual
Get the Advertised Window size.
Returns
the window size
Definition at line 771 of file nsc-tcp-socket-impl.cc.
References m_advertisedWindowSize.
GetAllowBroadcast()
bool ns3::NscTcpSocketImpl::GetAllowBroadcast () const virtual
Query whether broadcast datagram transmissions are allowed.
This method corresponds to using getsockopt() SO_BROADCAST of real network or BSD sockets.
Returns
true if broadcast is allowed, false otherwise
Implements ns3::Socket.
Definition at line 932 of file nsc-tcp-socket-impl.cc.
GetConnTimeout()
Time ns3::NscTcpSocketImpl::GetConnTimeout (void) const private virtual
Get the connection timeout.
Returns
the connection timeout
Implements ns3::TcpSocket.
Definition at line 807 of file nsc-tcp-socket-impl.cc.
References m_cnTimeout.
GetDataRetries()
uint32_t ns3::NscTcpSocketImpl::GetDataRetries (void) const private virtual
Get the number of data transmission retries before giving up.
Returns
the number of data transmission retries
Implements ns3::TcpSocket.
Definition at line 838 of file nsc-tcp-socket-impl.cc.
References m_dataRetries, and NS_LOG_FUNCTION.
GetDelAckMaxCount()
uint32_t ns3::NscTcpSocketImpl::GetDelAckMaxCount (void) const private virtual
Get the number of packet to fire an ACK before delay timeout.
Returns
the number of packet to fire an ACK before delay timeout
Implements ns3::TcpSocket.
Definition at line 857 of file nsc-tcp-socket-impl.cc.
References m_delAckMaxCount.
GetDelAckTimeout()
Time ns3::NscTcpSocketImpl::GetDelAckTimeout (void) const private virtual
Get the time to delay an ACK.
Returns
the time to delay an ACK
Implements ns3::TcpSocket.
Definition at line 845 of file nsc-tcp-socket-impl.cc.
References m_delAckTimeout.
GetErrno()
enum Socket::SocketErrno ns3::NscTcpSocketImpl::GetErrno (void) const virtual
Get last error number.
Returns
the errno associated to the last call which failed in this socket. Each socket's errno is initialized to zero when the socket is created.
Implements ns3::Socket.
Definition at line 171 of file nsc-tcp-socket-impl.cc.
References m_nscTcpSocket, and m_tcp.
GetInitialCwnd()
uint32_t ns3::NscTcpSocketImpl::GetInitialCwnd (void) const private virtual
Get the initial Congestion Window.
Returns
the initial congestion window (in segments)
Implements ns3::TcpSocket.
Definition at line 795 of file nsc-tcp-socket-impl.cc.
References m_initialCWnd.
GetInitialSSThresh()
uint32_t ns3::NscTcpSocketImpl::GetInitialSSThresh (void) const private virtual
Get the initial Slow Start Threshold.
Returns
the Slow Start Threshold (in bytes)
Implements ns3::TcpSocket.
Definition at line 783 of file nsc-tcp-socket-impl.cc.
References m_initialSsThresh.
GetNativeNs3Errno()
enum Socket::SocketErrno ns3::NscTcpSocketImpl::GetNativeNs3Errno (int err) const private
Translate between a NSC error and a ns-3 error code.
Parameters
err NSC error
Returns
ns-3 error code
Todo:
better mapping?
Todo:
this mapping isn't correct
Definition at line 881 of file nsc-tcp-socket-impl.cc.
References m_persistTimeout.
Referenced by ReadPendingData().
GetNode()
Ptr< Node > ns3::NscTcpSocketImpl::GetNode (void) const virtual
Return the node this socket is associated with.
Returns
the node
Implements ns3::Socket.
Definition at line 192 of file nsc-tcp-socket-impl.cc.
References m_node, and NS_LOG_FUNCTION.
GetPeerName()
int ns3::NscTcpSocketImpl::GetPeerName (Address & address) const virtual
Get the peer address of a connected socket.
Parameters
address the address this socket is connected to.
Returns
0 if success, -1 otherwise
Implements ns3::Socket.
Definition at line 500 of file nsc-tcp-socket-impl.cc.
References first::address, ns3::Socket::ERROR_NOTCONN, ns3::Ipv4EndPoint::GetPeerAddress(), ns3::Ipv4EndPoint::GetPeerPort(), m_endPoint, m_errno, and NS_LOG_FUNCTION.
Referenced by RecvFrom().
GetPersistTimeout()
Time ns3::NscTcpSocketImpl::GetPersistTimeout (void) const private virtual
Get the timeout for persistent connection.
When the timeout expires, send 1-byte data to probe for the window size at the receiver when the local knowledge tells that the receiver has zero window size
Returns
the persistent timeout
Implements ns3::TcpSocket.
Definition at line 881 of file nsc-tcp-socket-impl.cc.
GetRcvBufSize()
uint32_t ns3::NscTcpSocketImpl::GetRcvBufSize (void) const private virtual
Get the receive buffer size.
Returns
the buffer size (in bytes)
Implements ns3::TcpSocket.
Definition at line 747 of file nsc-tcp-socket-impl.cc.
References m_rcvBufSize.
GetRxAvailable()
uint32_t ns3::NscTcpSocketImpl::GetRxAvailable (void) const virtual
Return number of bytes which can be returned from one or multiple calls to Recv.
Must be possible to call this method from the Recv callback.
Returns
the number of bytes which can be returned from one or multiple Recv calls.
Implements ns3::Socket.
Definition at line 515 of file nsc-tcp-socket-impl.cc.
References m_rxAvailable, and NS_LOG_FUNCTION.
GetSegSize()
uint32_t ns3::NscTcpSocketImpl::GetSegSize (void) const private virtual
Get the segment size.
Returns
the segment size (in bytes)
Implements ns3::TcpSocket.
Definition at line 759 of file nsc-tcp-socket-impl.cc.
References m_segmentSize.
GetSndBufSize()
uint32_t ns3::NscTcpSocketImpl::GetSndBufSize (void) const private virtual
Get the send buffer size.
Returns
the buffer size (in bytes)
Implements ns3::TcpSocket.
Definition at line 735 of file nsc-tcp-socket-impl.cc.
References m_sndBufSize.
GetSocketType()
enum Socket::SocketType ns3::NscTcpSocketImpl::GetSocketType (void) const virtual
Returns
the socket type, analogous to getsockopt (SO_TYPE)
Implements ns3::Socket.
Definition at line 171 of file nsc-tcp-socket-impl.cc.
GetSockName()
int ns3::NscTcpSocketImpl::GetSockName (Address & address) const virtual
Get socket address.
Parameters
address the address name this socket is associated with.
Returns
0 if success, -1 otherwise
Implements ns3::Socket.
Definition at line 492 of file nsc-tcp-socket-impl.cc.
References first::address, m_localAddress, m_localPort, and NS_LOG_FUNCTION.
GetSynRetries()
uint32_t ns3::NscTcpSocketImpl::GetSynRetries (void) const private virtual
Get the number of connection retries before giving up.
Returns
the number of connection retries
Implements ns3::TcpSocket.
Definition at line 819 of file nsc-tcp-socket-impl.cc.
References m_synRetries.
GetTcpNoDelay()
bool ns3::NscTcpSocketImpl::GetTcpNoDelay (void) const private virtual
Check if Nagle's algorithm is enabled or not.
Returns
true if Nagle's algorithm is DISABLED
Implements ns3::TcpSocket.
Definition at line 869 of file nsc-tcp-socket-impl.cc.
References m_noDelay.
GetTxAvailable()
uint32_t ns3::NscTcpSocketImpl::GetTxAvailable (void) const virtual
Returns the number of bytes which can be sent in a single call to Send.
For datagram sockets, this returns the number of bytes that can be passed atomically through the underlying protocol.
For stream sockets, this returns the available space in bytes left in the transmit buffer.
Returns
The number of bytes which can be sent in a single Send call.
Implements ns3::Socket.
Definition at line 400 of file nsc-tcp-socket-impl.cc.
References m_sndBufSize, m_txBufferSize, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by NSCWakeup(), and Send().
GetTypeId()
TypeId ns3::NscTcpSocketImpl::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 53 of file nsc-tcp-socket-impl.cc.
References m_cWnd, m_ssThresh, m_state, ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
Listen()
int ns3::NscTcpSocketImpl::Listen (void) virtual
Listen for incoming connections.
Returns
0 on success, -1 on error (in which case errno is set).
Implements ns3::Socket.
Definition at line 415 of file nsc-tcp-socket-impl.cc.
References INetStreamSocket::listen(), ns3::TcpSocket::LISTEN, m_localPort, m_nscTcpSocket, m_state, and NS_LOG_FUNCTION.
NSCWakeup()
void ns3::NscTcpSocketImpl::NSCWakeup (void) private
Called by NscTcpSocketImpl::ForwardUp()
Actually performs the ForwardUp operations
Definition at line 425 of file nsc-tcp-socket-impl.cc.
References Accept(), ns3::TcpSocket::CLOSED, ConnectionSucceeded(), ns3::TcpSocket::ESTABLISHED, GetTxAvailable(), INetStreamSocket::is_connected(), ns3::TcpSocket::LISTEN, m_nscTcpSocket, m_state, m_txBuffer, ns3::Socket::NotifySend(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ReadPendingData(), ns3::Simulator::ScheduleNow(), SendPendingData(), and ns3::TcpSocket::SYN_SENT.
Referenced by ForwardUp().
ReadPendingData()
bool ns3::NscTcpSocketImpl::ReadPendingData (void) private
Read all the pending data.
Returns
true on success
Definition at line 618 of file nsc-tcp-socket-impl.cc.
References ns3::TcpSocket::CLOSE_WAIT, ns3::TcpSocket::CLOSED, ns3::Socket::ERROR_AGAIN, ns3::Socket::ERROR_NOTERROR, ns3::TcpSocket::ESTABLISHED, GetNativeNs3Errno(), ns3::Packet::GetSize(), m_deliveryQueue, m_errno, m_nscTcpSocket, m_rxAvailable, m_state, ns3::Socket::NotifyDataRecv(), NS_LOG_LOGIC, NS_LOG_WARN, and INetStreamSocket::read_data().
Referenced by NSCWakeup().
Recv()
Ptr< Packet > ns3::NscTcpSocketImpl::Recv (uint32_t maxSize, uint32_t flags) virtual
Read data from the socket.
This function matches closely in semantics to the recv() function call in the standard C library (libc): ssize_t recv (int s, void *buf, size_t len, int flags); except that the receive I/O is asynchronous. This is the primary Recv method at this low-level API and must be implemented by subclasses.
This method is normally used only on a connected socket. In a typical blocking sockets model, this call would block until at least one byte is returned or the connection closes. In ns-3 at this API, the call returns immediately in such a case and returns 0 if nothing is available to be read. However, an application can set a callback, ns3::SetRecvCallback, to be notified of data being available to be read (when it conceptually unblocks); this is an asynchronous I/O model for recv().
This variant of Recv() uses class ns3::Packet to encapsulate data, rather than providing a raw pointer and length field. This allows an ns-3 application to attach tags if desired (such as a flow ID) and may allow the simulator to avoid some data copies. Despite the appearance of receiving Packets on a stream socket, just think of it as a fancy byte buffer with streaming semantics.
The semantics depend on the type of socket. For a datagram socket, each Recv() returns the data from at most one Send(), and order is not necessarily preserved. For a stream socket, the bytes are delivered in order, and on-the-wire packet boundaries are not preserved.
The flags argument is formed by or'ing one or more of the values: MSG_OOB process out-of-band data MSG_PEEK peek at incoming message None of these flags are supported for now.
Some variants of Recv() are supported as additional API, including RecvFrom(), overloaded Recv() without arguments, and variants that use raw character buffers.
Parameters
maxSize reader will accept packet up to maxSize
flags Socket control flags
Returns
Ptr<Packet> of the next in-sequence packet. Returns 0 if the socket cannot return a next in-sequence packet conforming to the maxSize and flags.
See also
SetRecvCallback
Implements ns3::Socket.
Definition at line 459 of file nsc-tcp-socket-impl.cc.
References ns3::Socket::ERROR_AGAIN, ns3::Packet::GetSize(), m_deliveryQueue, m_errno, m_rxAvailable, and NS_LOG_FUNCTION.
RecvFrom()
Ptr< Packet > ns3::NscTcpSocketImpl::RecvFrom (uint32_t maxSize, uint32_t flags, Address & fromAddress) virtual
Read a single packet from the socket and retrieve the sender address.
Calls Recv(maxSize, flags) with maxSize implicitly set to maximum sized integer, and flags set to zero.
This method has similar semantics to Recv () but subclasses may want to provide checks on socket state, so the implementation is pushed to subclasses.
Parameters
maxSize reader will accept packet up to maxSize
flags Socket control flags
fromAddress output parameter that will return the address of the sender of the received packet, if any. Remains untouched if no packet is received.
Returns
Ptr<Packet> of the next in-sequence packet. Returns 0 if the socket cannot return a next in-sequence packet.
Implements ns3::Socket.
Definition at line 482 of file nsc-tcp-socket-impl.cc.
References GetPeerName(), NS_LOG_FUNCTION, and ns3::Socket::Recv().
Send()
int ns3::NscTcpSocketImpl::Send (Ptr< Packet > p, uint32_t flags) virtual
Send data (or dummy data) to the remote host.
This function matches closely in semantics to the send() function call in the standard C library (libc): ssize_t send (int s, const void *msg, size_t len, int flags); except that the send I/O is asynchronous. This is the primary Send method at this low-level API and must be implemented by subclasses.
In a typical blocking sockets model, this call would block upon lack of space to hold the message to be sent. In ns-3 at this API, the call returns immediately in such a case, but the callback registered with SetSendCallback() is invoked when the socket has space (when it conceptually unblocks); this is an asynchronous I/O model for send().
This variant of Send() uses class ns3::Packet to encapsulate data, rather than providing a raw pointer and length field. This allows an ns-3 application to attach tags if desired (such as a flow ID) and may allow the simulator to avoid some data copies. Despite the appearance of sending Packets on a stream socket, just think of it as a fancy byte buffer with streaming semantics.
If either the message buffer within the Packet is too long to pass atomically through the underlying protocol (for datagram sockets), or the message buffer cannot entirely fit in the transmit buffer (for stream sockets), -1 is returned and SocketErrno is set to ERROR_MSGSIZE. If the packet does not fit, the caller can split the Packet (based on information obtained from GetTxAvailable) and reattempt to send the data.
The flags argument is formed by or'ing one or more of the values: MSG_OOB process out-of-band data MSG_DONTROUTE bypass routing, use direct interface These flags are unsupported as of ns-3.1.
Parameters
p ns3::Packet to send
flags Socket control flags
Returns
the number of bytes accepted for transmission if no error occurs, and -1 otherwise.
See also
SetSendCallback
Implements ns3::Socket.
Definition at line 350 of file nsc-tcp-socket-impl.cc.
References ns3::TcpSocket::CLOSE_WAIT, ns3::Socket::ERROR_MSGSIZE, ns3::Socket::ERROR_NOTCONN, ns3::TcpSocket::ESTABLISHED, ns3::Packet::GetSize(), GetTxAvailable(), m_errno, m_state, m_txBuffer, m_txBufferSize, NS_ASSERT, NS_LOG_FUNCTION, SendPendingData(), and ns3::TcpSocket::SYN_SENT.
Referenced by SendTo().
SendPendingData()
bool ns3::NscTcpSocketImpl::SendPendingData (void) private
Send all the pending data.
Returns
true on success
Definition at line 656 of file nsc-tcp-socket-impl.cc.
References ns3::TcpSocket::CLOSED, ns3::Packet::CopyData(), INetStreamSocket::disconnect(), ns3::Socket::ERROR_NOTERROR, ns3::Packet::GetSize(), m_closeOnEmpty, m_errno, m_nscTcpSocket, m_state, m_txBuffer, m_txBufferSize, ns3::Socket::NotifyDataSent(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Packet::RemoveAtStart(), ns3::Simulator::ScheduleNow(), and INetStreamSocket::send_data().
Referenced by NSCWakeup(), and Send().
SendTo()
int ns3::NscTcpSocketImpl::SendTo (Ptr< Packet > p, uint32_t flags, const Address & toAddress) virtual
Send data to a specified peer.
This method has similar semantics to Send () but subclasses may want to provide checks on socket state, so the implementation is pushed to subclasses.
Parameters
p packet to send
flags Socket control flags
toAddress IP Address of remote host
Returns
-1 in case of error or the number of bytes copied in the internal buffer and accepted for transmission.
Implements ns3::Socket.
Definition at line 385 of file nsc-tcp-socket-impl.cc.
References first::address, ns3::Socket::ERROR_NOTCONN, m_connected, m_errno, NS_LOG_FUNCTION, and Send().
SetAdvWin()
void ns3::NscTcpSocketImpl::SetAdvWin (uint32_t window) private virtual
Set the Advertised Window size.
Parameters
window the window size
Definition at line 765 of file nsc-tcp-socket-impl.cc.
References m_advertisedWindowSize, and visualizer.ipython_view::window.
SetAllowBroadcast()
bool ns3::NscTcpSocketImpl::SetAllowBroadcast (bool allowBroadcast) virtual
Configure whether broadcast datagram transmissions are allowed.
This method corresponds to using setsockopt() SO_BROADCAST of real network or BSD sockets. If set on a socket, this option will enable or disable packets to be transmitted to broadcast destination addresses.
Parameters
allowBroadcast Whether broadcast is allowed
Returns
true if operation succeeds
Implements ns3::Socket.
Definition at line 922 of file nsc-tcp-socket-impl.cc.
SetConnTimeout()
void ns3::NscTcpSocketImpl::SetConnTimeout (Time timeout) private virtual
Set the connection timeout.
Parameters
timeout the connection timeout
Implements ns3::TcpSocket.
Definition at line 801 of file nsc-tcp-socket-impl.cc.
References m_cnTimeout, and timeout.
SetDataRetries()
void ns3::NscTcpSocketImpl::SetDataRetries (uint32_t retries) private virtual
Set the number of data transmission retries before giving up.
Parameters
retries the number of data transmission retries
Implements ns3::TcpSocket.
Definition at line 831 of file nsc-tcp-socket-impl.cc.
References m_dataRetries, and NS_LOG_FUNCTION.
SetDelAckMaxCount()
void ns3::NscTcpSocketImpl::SetDelAckMaxCount (uint32_t count) private virtual
Set the number of packet to fire an ACK before delay timeout.
Parameters
count the umber of packet to fire an ACK before delay timeout
Implements ns3::TcpSocket.
Definition at line 851 of file nsc-tcp-socket-impl.cc.
References m_delAckMaxCount.
SetDelAckTimeout()
void ns3::NscTcpSocketImpl::SetDelAckTimeout (Time timeout) private virtual
Set the time to delay an ACK.
Parameters
timeout the time to delay an ACK
Implements ns3::TcpSocket.
Definition at line 825 of file nsc-tcp-socket-impl.cc.
References m_delAckTimeout, and timeout.
SetInitialCwnd()
void ns3::NscTcpSocketImpl::SetInitialCwnd (uint32_t cwnd) private virtual
Set the initial Congestion Window.
Parameters
cwnd the initial congestion window (in segments)
Implements ns3::TcpSocket.
Definition at line 789 of file nsc-tcp-socket-impl.cc.
References m_initialCWnd.
SetInitialSSThresh()
void ns3::NscTcpSocketImpl::SetInitialSSThresh (uint32_t threshold) private virtual
Set the initial Slow Start Threshold.
Parameters
threshold the Slow Start Threshold (in bytes)
Implements ns3::TcpSocket.
Definition at line 777 of file nsc-tcp-socket-impl.cc.
References m_initialSsThresh.
SetNode()
void ns3::NscTcpSocketImpl::SetNode (Ptr< Node > node)
Set the associated node.
Parameters
node the node
Definition at line 161 of file nsc-tcp-socket-impl.cc.
References m_advertisedWindowSize, m_cWnd, m_initialCWnd, m_initialSsThresh, m_node, m_rxWindowSize, m_segmentSize, and m_ssThresh.
SetPersistTimeout()
void ns3::NscTcpSocketImpl::SetPersistTimeout (Time timeout) private virtual
Set the timeout for persistent connection.
When the timeout expires, send 1-byte data to probe for the window size at the receiver when the local knowledge tells that the receiver has zero window size
Parameters
timeout the persistent timeout
Implements ns3::TcpSocket.
Definition at line 875 of file nsc-tcp-socket-impl.cc.
References m_persistTimeout, and timeout.
SetRcvBufSize()
void ns3::NscTcpSocketImpl::SetRcvBufSize (uint32_t size) private virtual
Set the receive buffer size.
Parameters
size the buffer size (in bytes)
Implements ns3::TcpSocket.
Definition at line 741 of file nsc-tcp-socket-impl.cc.
References m_rcvBufSize.
SetSegSize()
void ns3::NscTcpSocketImpl::SetSegSize (uint32_t size) private virtual
Set the segment size.
Parameters
size the segment size (in bytes)
Implements ns3::TcpSocket.
Definition at line 753 of file nsc-tcp-socket-impl.cc.
References m_segmentSize.
SetSndBufSize()
void ns3::NscTcpSocketImpl::SetSndBufSize (uint32_t size) private virtual
Set the send buffer size.
Parameters
size the buffer size (in bytes)
Implements ns3::TcpSocket.
Definition at line 729 of file nsc-tcp-socket-impl.cc.
References m_sndBufSize.
SetSynRetries()
void ns3::NscTcpSocketImpl::SetSynRetries (uint32_t count) private virtual
Set the number of connection retries before giving up.
Parameters
count the number of connection retries
Implements ns3::TcpSocket.
Definition at line 813 of file nsc-tcp-socket-impl.cc.
References m_synRetries.
SetTcp()
void ns3::NscTcpSocketImpl::SetTcp (Ptr< NscTcpL4Protocol > tcp)
Set the associated TCP L4 protocol.
Parameters
tcp the TCP L4 protocol
Definition at line 171 of file nsc-tcp-socket-impl.cc.
SetTcpNoDelay()
void ns3::NscTcpSocketImpl::SetTcpNoDelay (bool noDelay) private virtual
Enable/Disable Nagle's algorithm.
Parameters
noDelay true to DISABLE Nagle's algorithm
Implements ns3::TcpSocket.
Definition at line 863 of file nsc-tcp-socket-impl.cc.
References m_noDelay.
ShutdownRecv()
int ns3::NscTcpSocketImpl::ShutdownRecv (void) virtual
Returns
zero on success, -1 on failure.
Do not allow any further Recv calls. This method is typically implemented for Tcp sockets by a half close.
Implements ns3::Socket.
Definition at line 292 of file nsc-tcp-socket-impl.cc.
References m_shutdownRecv, and NS_LOG_FUNCTION.
ShutdownSend()
int ns3::NscTcpSocketImpl::ShutdownSend (void) virtual
Returns
zero on success, -1 on failure.
Do not allow any further Send calls. This method is typically implemented for Tcp sockets by a half close.
Implements ns3::Socket.
Definition at line 285 of file nsc-tcp-socket-impl.cc.
References m_shutdownSend, and NS_LOG_FUNCTION.
Referenced by Close().
Friends And Related Function Documentation
Tcp
friend class Tcp friend
Tcp friend class.
Definition at line 121 of file nsc-tcp-socket-impl.h.
Member Data Documentation
m_advertisedWindowSize
uint32_t ns3::NscTcpSocketImpl::m_advertisedWindowSize private
Window to advertise.
Definition at line 250 of file nsc-tcp-socket-impl.h.
Referenced by GetAdvWin(), SetAdvWin(), and SetNode().
m_closeOnEmpty
bool ns3::NscTcpSocketImpl::m_closeOnEmpty private
true if socket will close when buffer is empty
Definition at line 241 of file nsc-tcp-socket-impl.h.
Referenced by Close(), and SendPendingData().
m_cnTimeout
Time ns3::NscTcpSocketImpl::m_cnTimeout private
Timeout for connection retry.
Definition at line 260 of file nsc-tcp-socket-impl.h.
Referenced by GetConnTimeout(), and SetConnTimeout().
m_connected
bool ns3::NscTcpSocketImpl::m_connected private
Connection established.
Definition at line 237 of file nsc-tcp-socket-impl.h.
Referenced by SendTo().
m_cWnd
TracedValue<uint32_t> ns3::NscTcpSocketImpl::m_cWnd private
Congestion window.
Definition at line 251 of file nsc-tcp-socket-impl.h.
Referenced by GetTypeId(), and SetNode().
m_dataRetries
uint32_t ns3::NscTcpSocketImpl::m_dataRetries private
Count of remaining data retransmission attempts.
Definition at line 262 of file nsc-tcp-socket-impl.h.
Referenced by GetDataRetries(), and SetDataRetries().
m_delAckMaxCount
uint32_t ns3::NscTcpSocketImpl::m_delAckMaxCount private
Number of packet to fire an ACK before delay timeout.
Definition at line 221 of file nsc-tcp-socket-impl.h.
Referenced by GetDelAckMaxCount(), and SetDelAckMaxCount().
m_delAckTimeout
Time ns3::NscTcpSocketImpl::m_delAckTimeout private
Time to delay an ACK.
Definition at line 222 of file nsc-tcp-socket-impl.h.
Referenced by GetDelAckTimeout(), and SetDelAckTimeout().
m_deliveryQueue
std::queue<Ptr<Packet> > ns3::NscTcpSocketImpl::m_deliveryQueue private
receive buffer
Definition at line 266 of file nsc-tcp-socket-impl.h.
Referenced by ReadPendingData(), and Recv().
m_endPoint
Ipv4EndPoint* ns3::NscTcpSocketImpl::m_endPoint private
the IPv4 endpoint
Definition at line 225 of file nsc-tcp-socket-impl.h.
Referenced by ~NscTcpSocketImpl(), Bind(), BindToNetDevice(), CompleteFork(), Connect(), Destroy(), FinishBind(), and GetPeerName().
m_errno
enum SocketErrno ns3::NscTcpSocketImpl::m_errno mutable private
last error number
Definition at line 233 of file nsc-tcp-socket-impl.h.
Referenced by Bind6(), GetPeerName(), ReadPendingData(), Recv(), Send(), SendPendingData(), and SendTo().
m_initialCWnd
uint32_t ns3::NscTcpSocketImpl::m_initialCWnd private
Initial cWnd value.
Definition at line 253 of file nsc-tcp-socket-impl.h.
Referenced by GetInitialCwnd(), SetInitialCwnd(), and SetNode().
m_initialSsThresh
uint32_t ns3::NscTcpSocketImpl::m_initialSsThresh private
Initial Slow Start Threshold.
Definition at line 254 of file nsc-tcp-socket-impl.h.
Referenced by GetInitialSSThresh(), SetInitialSSThresh(), and SetNode().
m_lastMeasuredRtt
Time ns3::NscTcpSocketImpl::m_lastMeasuredRtt private
Last measured RTT.
Definition at line 257 of file nsc-tcp-socket-impl.h.
m_localAddress
Ipv4Address ns3::NscTcpSocketImpl::m_localAddress private
local address
Definition at line 231 of file nsc-tcp-socket-impl.h.
Referenced by CompleteFork(), ConnectionSucceeded(), FinishBind(), and GetSockName().
m_localPort
uint16_t ns3::NscTcpSocketImpl::m_localPort private
local port
Definition at line 232 of file nsc-tcp-socket-impl.h.
Referenced by Bind(), CompleteFork(), ConnectionSucceeded(), FinishBind(), GetSockName(), and Listen().
m_node
Ptr<Node> ns3::NscTcpSocketImpl::m_node private
the associated node
Definition at line 226 of file nsc-tcp-socket-impl.h.
Referenced by ~NscTcpSocketImpl(), Destroy(), GetNode(), and SetNode().
m_noDelay
bool ns3::NscTcpSocketImpl::m_noDelay private
Disable ACk delay.
Definition at line 223 of file nsc-tcp-socket-impl.h.
Referenced by GetTcpNoDelay(), and SetTcpNoDelay().
m_nscTcpSocket
INetStreamSocket* ns3::NscTcpSocketImpl::m_nscTcpSocket private
the real NSC TCP socket
Definition at line 268 of file nsc-tcp-socket-impl.h.
Referenced by Accept(), Close(), CompleteFork(), Connect(), ConnectionSucceeded(), GetErrno(), Listen(), NSCWakeup(), ReadPendingData(), and SendPendingData().
m_peerAddress
InetSocketAddress ns3::NscTcpSocketImpl::m_peerAddress private
peer IP and port
Definition at line 233 of file nsc-tcp-socket-impl.h.
Referenced by CompleteFork().
m_persistTimeout
Time ns3::NscTcpSocketImpl::m_persistTimeout private
Time between sending 1-byte probes.
Definition at line 263 of file nsc-tcp-socket-impl.h.
Referenced by GetNativeNs3Errno(), and SetPersistTimeout().
m_rcvBufSize
uint32_t ns3::NscTcpSocketImpl::m_rcvBufSize private
maximum receive socket buffer size
Definition at line 272 of file nsc-tcp-socket-impl.h.
Referenced by GetRcvBufSize(), and SetRcvBufSize().
m_remoteAddress
Ipv4Address ns3::NscTcpSocketImpl::m_remoteAddress private
peer IP address
Definition at line 228 of file nsc-tcp-socket-impl.h.
Referenced by CompleteFork(), Connect(), and ConnectionSucceeded().
m_remotePort
uint16_t ns3::NscTcpSocketImpl::m_remotePort private
peer port
Definition at line 229 of file nsc-tcp-socket-impl.h.
Referenced by CompleteFork(), Connect(), and ConnectionSucceeded().
m_rxAvailable
uint32_t ns3::NscTcpSocketImpl::m_rxAvailable private
receive buffer available size
Definition at line 267 of file nsc-tcp-socket-impl.h.
Referenced by GetRxAvailable(), ReadPendingData(), and Recv().
m_rxWindowSize
uint32_t ns3::NscTcpSocketImpl::m_rxWindowSize private
Receive window size.
Definition at line 249 of file nsc-tcp-socket-impl.h.
Referenced by SetNode().
m_segmentSize
uint32_t ns3::NscTcpSocketImpl::m_segmentSize private
SegmentSize.
Definition at line 248 of file nsc-tcp-socket-impl.h.
Referenced by GetSegSize(), SetNode(), and SetSegSize().
m_shutdownRecv
bool ns3::NscTcpSocketImpl::m_shutdownRecv private
Receive no longer allowed.
Definition at line 236 of file nsc-tcp-socket-impl.h.
Referenced by ShutdownRecv().
m_shutdownSend
bool ns3::NscTcpSocketImpl::m_shutdownSend private
Send no longer allowed.
Definition at line 235 of file nsc-tcp-socket-impl.h.
Referenced by ShutdownSend().
m_sndBufSize
uint32_t ns3::NscTcpSocketImpl::m_sndBufSize private
buffer limit for the outgoing queue
Definition at line 271 of file nsc-tcp-socket-impl.h.
Referenced by GetSndBufSize(), GetTxAvailable(), and SetSndBufSize().
m_ssThresh
TracedValue<uint32_t> ns3::NscTcpSocketImpl::m_ssThresh private
Slow Start Threshold.
Definition at line 252 of file nsc-tcp-socket-impl.h.
Referenced by GetTypeId(), and SetNode().
m_state
TracedValue<TcpStates_t> ns3::NscTcpSocketImpl::m_state private
state information
Definition at line 240 of file nsc-tcp-socket-impl.h.
Referenced by Accept(), Close(), CompleteFork(), Connect(), GetTypeId(), Listen(), NSCWakeup(), ReadPendingData(), Send(), and SendPendingData().
m_synRetries
uint32_t ns3::NscTcpSocketImpl::m_synRetries private
Count of remaining connection retries.
Definition at line 261 of file nsc-tcp-socket-impl.h.
Referenced by GetSynRetries(), and SetSynRetries().
m_tcp
Ptr<NscTcpL4Protocol> ns3::NscTcpSocketImpl::m_tcp private
the associated TCP L4 protocol
Definition at line 227 of file nsc-tcp-socket-impl.h.
Referenced by ~NscTcpSocketImpl(), Bind(), CompleteFork(), Destroy(), and GetErrno().
m_txBuffer
std::queue<Ptr<Packet> > ns3::NscTcpSocketImpl::m_txBuffer private
transmission buffer
Definition at line 244 of file nsc-tcp-socket-impl.h.
Referenced by NscTcpSocketImpl(), Close(), NSCWakeup(), Send(), and SendPendingData().
m_txBufferSize
uint32_t ns3::NscTcpSocketImpl::m_txBufferSize private
transmission buffer size
Definition at line 245 of file nsc-tcp-socket-impl.h.
Referenced by GetTxAvailable(), Send(), and SendPendingData().
The documentation for this class was generated from the following files:
src/internet/model/nsc-tcp-socket-impl.h
src/internet/model/nsc-tcp-socket-impl.cc