ns-3: ns3::LrWpanPhy Class Reference
ns3::LrWpanPhy Class Reference
LR-WPAN models
Make LrWpanPhy a SpectrumPhy so we can enable the eventual modeling of device interference.
#include "lr-wpan-phy.h"
Public Types
typedef void(* StateTracedCallback) (Time time, LrWpanPhyEnumeration oldState, LrWpanPhyEnumeration newState)
TracedCallback signature for Trx state change events.
Public Member Functions
LrWpanPhy (void)
Default constructor.
virtual ~LrWpanPhy (void)
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Ptr< SpectrumChannel > GetChannel (void)
Get the currently attached channel.
double GetDataOrSymbolRate (bool isData)
implement PLME SetAttribute confirm SAP bit rate is in kbit/s.
Ptr< NetDevice > GetDevice (void) const
Get the associated NetDevice instance.
Ptr< LrWpanErrorModel > GetErrorModel (void) const
get the error model in use
Ptr< MobilityModel > GetMobility (void)
Get the associated MobilityModel instance.
Ptr< const SpectrumValue > GetNoisePowerSpectralDensity (void)
Get the noise power spectral density.
uint64_t GetPhySHRDuration (void) const
Get the duration of the SHR (preamble and SFD) in symbols, depending on the currently selected channel.
double GetPhySymbolsPerOctet (void) const
Get the number of symbols per octet, depending on the currently selected channel.
Ptr< AntennaModel > GetRxAntenna (void)
Get the AntennaModel used by the NetDevice for reception.
virtual Ptr< const SpectrumModel > GetRxSpectrumModel (void) const
void PdDataRequest (const uint32_t psduLength, Ptr< Packet > p)
IEEE 802.15.4-2006 section 6.2.1.1 PD-DATA.request Request to transfer MPDU from MAC (transmitting)
void PlmeCcaRequest (void)
IEEE 802.15.4-2006 section 6.2.2.1 PLME-CCA.request Perform a CCA per section 6.9.9.
void PlmeEdRequest (void)
IEEE 802.15.4-2006 section 6.2.2.3 PLME-ED.request Perform an ED per section 6.9.7.
void PlmeGetAttributeRequest (LrWpanPibAttributeIdentifier id)
IEEE 802.15.4-2006 section 6.2.2.5 PLME-GET.request Get attributes per definition from Table 23 in section 6.4.2.
void PlmeSetAttributeRequest (LrWpanPibAttributeIdentifier id, LrWpanPhyPibAttributes *attribute)
IEEE 802.15.4-2006 section 6.2.2.9 PLME-SET.request Set attributes per definition from Table 23 in section 6.4.2.
void PlmeSetTRXStateRequest (LrWpanPhyEnumeration state)
IEEE 802.15.4-2006 section 6.2.2.7 PLME-SET-TRX-STATE.request Set PHY state.
void SetAntenna (Ptr< AntennaModel > a)
Set the attached antenna.
void SetChannel (Ptr< SpectrumChannel > c)
Set the channel attached to this device.
void SetDevice (Ptr< NetDevice > d)
Set the associated NetDevice instance.
void SetErrorModel (Ptr< LrWpanErrorModel > e)
set the error model to use
void SetMobility (Ptr< MobilityModel > m)
Set the mobility model associated with this device.
void SetNoisePowerSpectralDensity (Ptr< const SpectrumValue > noisePsd)
Set the noise power spectral density.
void SetPdDataConfirmCallback (PdDataConfirmCallback c)
set the callback for the end of a TX, as part of the interconnections betweenthe PHY and the MAC.
void SetPdDataIndicationCallback (PdDataIndicationCallback c)
set the callback for the end of a RX, as part of the interconnections betweenthe PHY and the MAC.
void SetPlmeCcaConfirmCallback (PlmeCcaConfirmCallback c)
set the callback for the end of a CCA, as part of the interconnections betweenthe PHY and the MAC.
void SetPlmeEdConfirmCallback (PlmeEdConfirmCallback c)
set the callback for the end of an ED, as part of the interconnections betweenthe PHY and the MAC.
void SetPlmeGetAttributeConfirmCallback (PlmeGetAttributeConfirmCallback c)
set the callback for the end of an GetAttribute, as part of the interconnections betweenthe PHY and the MAC.
void SetPlmeSetAttributeConfirmCallback (PlmeSetAttributeConfirmCallback c)
set the callback for the end of an SetAttribute, as part of the interconnections betweenthe PHY and the MAC.
void SetPlmeSetTRXStateConfirmCallback (PlmeSetTRXStateConfirmCallback c)
set the callback for the end of an SetTRXState, as part of the interconnections betweenthe PHY and the MAC.
void SetTxPowerSpectralDensity (Ptr< SpectrumValue > txPsd)
Set the Power Spectral Density of outgoing signals in W/Hz.
virtual void StartRx (Ptr< SpectrumSignalParameters > params)
Notify the SpectrumPhy instance of an incoming waveform.
Public Member Functions inherited from ns3::SpectrumPhy
SpectrumPhy ()
virtual ~SpectrumPhy ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::SpectrumPhy
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static const uint32_t aMaxPhyPacketSize = 127
The maximum packet size accepted by the PHY.
static const uint32_t aTurnaroundTime = 12
The turnaround time for switching the transceiver from RX to TX or vice versa.
Static Protected Attributes
static const LrWpanPhyDataAndSymbolRates dataSymbolRates [7]
The data and symbol rates for the different PHY options.
static const LrWpanPhyPpduHeaderSymbolNumber ppduHeaderSymbolNumbers [7]
The preamble, SFD, and PHR lengths in symbols for the different PHY options.
Private Types
typedef std::pair< Ptr< Packet >, bool > PacketAndStatus
The second is true if the first is flagged as error/invalid.
Private Member Functions
Time CalculateTxTime (Ptr< const Packet > packet)
Calculate the time required for sending the given packet, including preamble, SFD and PHR.
void CancelEd (LrWpanPhyEnumeration state)
Cancel an ongoing ED procedure.
void ChangeTrxState (LrWpanPhyEnumeration newState)
Change the PHY state to the given new state, firing the state change trace.
bool ChannelSupported (uint8_t channel)
Check if the given channel is supported by the PHY.
void CheckInterference (void)
Check if the interference destroys a frame currently received.
virtual void DoDispose (void)
Destructor implementation.
void EndCca (void)
Called at the end of the CCA.
void EndEd (void)
Called at the end of the ED procedure.
void EndRx (Ptr< SpectrumSignalParameters > params)
Finish the reception of a frame.
void EndSetTRXState (void)
Called after applying a deferred transceiver state switch.
void EndTx (void)
Finish the transmission of a frame.
LrWpanPhyOption GetMyPhyOption (void)
Get the currently configured PHY option.
Time GetPpduHeaderTxTime (void)
Calculate the time required for sending the PPDU header, that is the preamble, SFD and PHR.
bool PhyIsBusy (void) const
Check if the PHY is busy, which is the case if the PHY is currently sending or receiving a frame.
void SetMyPhyOption (void)
Configure the PHY option according to the current channel and channel page.
Private Attributes
Ptr< AntennaModel > m_antenna
The antenna used by the transceiver.
double m_ccaPeakPower
Helper value for the peak power value during CCA.
EventId m_ccaRequest
Scheduler event of a currently running CCA request.
Ptr< SpectrumChannel > m_channel
The channel attached to this transceiver.
std::pair< Ptr< LrWpanSpectrumSignalParameters >, bool > m_currentRxPacket
Statusinformation of the currently received packet.
PacketAndStatus m_currentTxPacket
Statusinformation of the currently transmitted packet.
Ptr< NetDevice > m_device
The configured net device.
LrWpanEdPower m_edPower
Helper value for tracking the average power during ED.
EventId m_edRequest
Scheduler event of a currently running ED request.
Ptr< LrWpanErrorModel > m_errorModel
The error model describing the bit and packet error rates.
Ptr< MobilityModel > m_mobility
The mobility model used by the PHY.
Ptr< const SpectrumValue > m_noise
The spectral density for for the noise.
PdDataConfirmCallback m_pdDataConfirmCallback
This callback is used to report packet transmission status to the MAC layer.
PdDataIndicationCallback m_pdDataIndicationCallback
This callback is used to notify incoming packets to the MAC layer.
EventId m_pdDataRequest
Scheduler event of a currently running data transmission request.
LrWpanPhyOption m_phyOption
The currently configured PHY type.
LrWpanPhyPibAttributes m_phyPIBAttributes
The current PHY PIB attributes.
TracedCallback< Ptr< const Packet > > m_phyRxBeginTrace
The trace source fired when a packet begins the reception process from the medium.
TracedCallback< Ptr< const Packet > > m_phyRxDropTrace
The trace source fired when the phy layer drops a packet it has received.
TracedCallback< Ptr< const Packet >, double > m_phyRxEndTrace
The trace source fired when a packet ends the reception process from the medium.
TracedCallback< Ptr< const Packet > > m_phyTxBeginTrace
The trace source fired when a packet begins the transmission process on the medium.
TracedCallback< Ptr< const Packet > > m_phyTxDropTrace
The trace source fired when the phy layer drops a packet as it tries to transmit it.
TracedCallback< Ptr< const Packet > > m_phyTxEndTrace
The trace source fired when a packet ends the transmission process on the medium.
PlmeCcaConfirmCallback m_plmeCcaConfirmCallback
This callback is used to report CCA status to the MAC or CSMA/CA.
PlmeEdConfirmCallback m_plmeEdConfirmCallback
This callback is used to report ED status to the MAC.
PlmeGetAttributeConfirmCallback m_plmeGetAttributeConfirmCallback
This callback is used to report requested attribute values back to the MAC.
PlmeSetAttributeConfirmCallback m_plmeSetAttributeConfirmCallback
This callback is used to report attribute set results back to the MAC.
PlmeSetTRXStateConfirmCallback m_plmeSetTRXStateConfirmCallback
This callback is used to report transceiver state change status to the MAC.
Ptr< UniformRandomVariable > m_random
Uniform random variable stream.
Time m_rxLastUpdate
Timestamp of the last calculation of the PER of a packet currently received.
double m_rxSensitivity
The receiver sensitivity.
EventId m_setTRXState
Scheduler event of a currently running deferred transceiver state switch.
Ptr< LrWpanInterferenceHelper > m_signal
The accumulated signals currently received by the transceiver, including the signal of a possibly received packet, as well as all signals considered noise.
TracedValue< LrWpanPhyEnumeration > m_trxState
The current transceiver state.
TracedCallback< Time, LrWpanPhyEnumeration, LrWpanPhyEnumeration > m_trxStateLogger
The trace source fired when the phy layer changes the transceiver state.
LrWpanPhyEnumeration m_trxStatePending
The next pending state to applied after the current action of the PHY is completed.
Ptr< SpectrumValue > m_txPsd
The transmit power spectral density.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Make LrWpanPhy a SpectrumPhy so we can enable the eventual modeling of device interference.
Config Paths
ns3::LrWpanPhy is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::LrWpanNetDevice/Phy"
No Attributes are defined for this type.
TraceSources
TrxStateValue: The state of the transceiver
Callback signature: ns3::TracedValueCallback::LrWpanPhyEnumeration
TrxState: The state of the transceiver
Callback signature: ns3::LrWpanPhy::StateTracedCallback
PhyTxBegin: Trace source indicating a packet has begun transmitting over the channel medium
Callback signature: ns3::Packet::TracedCallback
PhyTxEnd: Trace source indicating a packet has been completely transmitted over the channel.
Callback signature: ns3::Packet::TracedCallback
PhyTxDrop: Trace source indicating a packet has been dropped by the device during transmission
Callback signature: ns3::Packet::TracedCallback
PhyRxBegin: Trace source indicating a packet has begun being received from the channel medium by the device
Callback signature: ns3::Packet::TracedCallback
PhyRxEnd: Trace source indicating a packet has been completely received from the channel medium by the device
Callback signature: ns3::Packet::SinrTracedCallback
PhyRxDrop: Trace source indicating a packet has been dropped by the device during reception
Callback signature: ns3::Packet::TracedCallback
Size of this type is 712 bytes (on a 64-bit architecture).
Definition at line 247 of file lr-wpan-phy.h.
Member Typedef Documentation
PacketAndStatus
typedef std::pair<Ptr<Packet>, bool> ns3::LrWpanPhy::PacketAndStatus private
The second is true if the first is flagged as error/invalid.
Definition at line 510 of file lr-wpan-phy.h.
StateTracedCallback
typedef void(* ns3::LrWpanPhy::StateTracedCallback) (Time time, LrWpanPhyEnumeration oldState, LrWpanPhyEnumeration newState)
TracedCallback signature for Trx state change events.
Parameters
[in] time The time of the state change.
[in] oldState The old state.
[in] newState The new state.
Deprecated:
The LrWpanPhyEnumeration state is now accessible as the TracedValue TrxStateValue. The TrxState TracedCallback will be removed in a future release.
Definition at line 490 of file lr-wpan-phy.h.
Constructor & Destructor Documentation
LrWpanPhy()
ns3::LrWpanPhy::LrWpanPhy (void)
Default constructor.
Definition at line 123 of file lr-wpan-phy.cc.
References ns3::LrWpanEdPower::averagePower, ChangeTrxState(), ns3::LrWpanSpectrumValueHelper::CreateNoisePowerSpectralDensity(), ns3::LrWpanSpectrumValueHelper::CreateTxPowerSpectralDensity(), ns3::IEEE_802_15_4_PHY_IDLE, ns3::IEEE_802_15_4_PHY_TRX_OFF, ns3::LrWpanEdPower::lastUpdate, m_currentRxPacket, m_currentTxPacket, m_edPower, m_errorModel, m_noise, m_phyPIBAttributes, m_random, m_rxLastUpdate, m_rxSensitivity, m_signal, m_trxState, m_trxStatePending, m_txPsd, ns3::LrWpanEdPower::measurementLength, ns3::LrWpanPhyPibAttributes::phyCCAMode, ns3::LrWpanPhyPibAttributes::phyChannelsSupported, ns3::LrWpanPhyPibAttributes::phyCurrentChannel, ns3::LrWpanPhyPibAttributes::phyCurrentPage, ns3::LrWpanPhyPibAttributes::phyTransmitPower, ns3::Seconds(), ns3::ObjectBase::SetAttribute(), and SetMyPhyOption().
~LrWpanPhy()
ns3::LrWpanPhy::~LrWpanPhy (void) virtual
Definition at line 168 of file lr-wpan-phy.cc.
Member Function Documentation
AssignStreams()
int64_t ns3::LrWpanPhy::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 1420 of file lr-wpan-phy.cc.
References m_random, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
CalculateTxTime()
Time ns3::LrWpanPhy::CalculateTxTime (Ptr< const Packet > packet) private
Calculate the time required for sending the given packet, including preamble, SFD and PHR.
Parameters
packet the packet for which the transmission time should be calculated
Returns
the time required for transmitting the packet
Definition at line 1256 of file lr-wpan-phy.cc.
References GetDataOrSymbolRate(), GetPpduHeaderTxTime(), NS_LOG_FUNCTION, and ns3::Seconds().
Referenced by PdDataRequest().
CancelEd()
void ns3::LrWpanPhy::CancelEd (LrWpanPhyEnumeration state) private
Cancel an ongoing ED procedure.
This is called when the transceiver is switched off or set to TX mode. This calls the appropriate confirm callback of the MAC.
Parameters
state the new state which is the cause for canceling ED
Definition at line 1063 of file lr-wpan-phy.cc.
References ns3::EventId::Cancel(), ns3::IEEE_802_15_4_PHY_TRX_OFF, ns3::IEEE_802_15_4_PHY_TX_ON, ns3::EventId::IsExpired(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_edRequest, m_plmeEdConfirmCallback, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by PlmeSetTRXStateRequest().
ChangeTrxState()
void ns3::LrWpanPhy::ChangeTrxState (LrWpanPhyEnumeration newState) private
Change the PHY state to the given new state, firing the state change trace.
Parameters
newState the new state
Definition at line 1046 of file lr-wpan-phy.cc.
References m_trxState, m_trxStateLogger, ns3::Simulator::Now(), and NS_LOG_LOGIC.
Referenced by LrWpanPhy(), EndRx(), EndSetTRXState(), EndTx(), PdDataRequest(), PlmeSetTRXStateRequest(), and StartRx().
ChannelSupported()
bool ns3::LrWpanPhy::ChannelSupported (uint8_t channel) private
Check if the given channel is supported by the PHY.
Parameters
channel the channel to check
Returns
true, if the channel is supported, false otherwise
Definition at line 875 of file lr-wpan-phy.cc.
References third::channel, m_phyPIBAttributes, NS_LOG_FUNCTION, and ns3::LrWpanPhyPibAttributes::phyChannelsSupported.
Referenced by PlmeSetAttributeRequest().
CheckInterference()
void ns3::LrWpanPhy::CheckInterference (void) private
Check if the interference destroys a frame currently received.
Called whenever a change in interference is detected.
Definition at line 397 of file lr-wpan-phy.cc.
References ns3::LrWpanLqiTag::Get(), GetDataOrSymbolRate(), ns3::UniformRandomVariable::GetValue(), ns3::IEEE_802_15_4_PHY_BUSY_RX, m_currentRxPacket, m_errorModel, m_noise, m_phyPIBAttributes, m_random, m_rxLastUpdate, m_signal, m_trxState, max, ns3::Time::MS, ns3::Simulator::Now(), NS_LOG_WARN, ns3::Packet::PeekPacketTag(), ns3::LrWpanPhyPibAttributes::phyCurrentChannel, ns3::Packet::ReplacePacketTag(), ns3::LrWpanLqiTag::Set(), and ns3::LrWpanSpectrumValueHelper::TotalAvgPower().
Referenced by EndRx(), and StartRx().
DoDispose()
void ns3::LrWpanPhy::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 173 of file lr-wpan-phy.cc.
References ns3::EventId::Cancel(), ns3::Object::DoDispose(), ns3::IEEE_802_15_4_PHY_IDLE, ns3::IEEE_802_15_4_PHY_TRX_OFF, m_channel, m_device, m_errorModel, m_mobility, m_noise, m_pdDataConfirmCallback, m_pdDataIndicationCallback, m_plmeCcaConfirmCallback, m_plmeEdConfirmCallback, m_plmeGetAttributeConfirmCallback, m_plmeSetAttributeConfirmCallback, m_plmeSetTRXStateConfirmCallback, m_setTRXState, m_signal, m_trxState, m_trxStatePending, m_txPsd, and NS_LOG_FUNCTION.
EndCca()
void ns3::LrWpanPhy::EndCca (void) private
Called at the end of the CCA.
The channel condition (busy or idle) is reported to the MAC or CSMA/CA.
Definition at line 1111 of file lr-wpan-phy.cc.
References ns3::IEEE_802_15_4_PHY_BUSY, ns3::IEEE_802_15_4_PHY_BUSY_RX, ns3::IEEE_802_15_4_PHY_IDLE, ns3::IEEE_802_15_4_PHY_UNSPECIFIED, ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_ccaPeakPower, m_phyPIBAttributes, m_plmeCcaConfirmCallback, m_rxSensitivity, m_signal, m_trxState, NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::LrWpanPhyPibAttributes::phyCCAMode, ns3::LrWpanPhyPibAttributes::phyCurrentChannel, PhyIsBusy(), and ns3::LrWpanSpectrumValueHelper::TotalAvgPower().
Referenced by PlmeCcaRequest().
EndEd()
void ns3::LrWpanPhy::EndEd (void) private
Called at the end of the ED procedure.
The average energy detected is reported to the MAC.
Definition at line 1079 of file lr-wpan-phy.cc.
References ns3::LrWpanEdPower::averagePower, ns3::Time::GetTimeStep(), ns3::IEEE_802_15_4_PHY_SUCCESS, ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), ns3::LrWpanEdPower::lastUpdate, m_edPower, m_phyPIBAttributes, m_plmeEdConfirmCallback, m_rxSensitivity, m_signal, ns3::LrWpanEdPower::measurementLength, ns3::Simulator::Now(), NS_LOG_FUNCTION, ns3::LrWpanPhyPibAttributes::phyCurrentChannel, and ns3::LrWpanSpectrumValueHelper::TotalAvgPower().
Referenced by PlmeEdRequest().
EndRx()
void ns3::LrWpanPhy::EndRx (Ptr< SpectrumSignalParameters > params) private
Finish the reception of a frame.
This is called at the end of a frame reception, applying possibly pending PHY state changes and fireing the appropriate trace sources and indication callbacks to the MAC. A frame destroyed by noise/interference is dropped here, but not during reception. This method is also called for every packet which only contributes to interference.
Parameters
params signal parameters of the packet
Definition at line 443 of file lr-wpan-phy.cc.
References ns3::LrWpanEdPower::averagePower, ChangeTrxState(), CheckInterference(), ns3::LrWpanLqiTag::Get(), ns3::Packet::GetSize(), ns3::Time::GetTimeStep(), ns3::IEEE_802_15_4_PHY_IDLE, ns3::IEEE_802_15_4_PHY_RX_ON, ns3::IEEE_802_15_4_PHY_SUCCESS, ns3::EventId::IsExpired(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), ns3::EventId::IsRunning(), ns3::LrWpanEdPower::lastUpdate, m_currentRxPacket, m_device, m_edPower, m_edRequest, m_pdDataIndicationCallback, m_phyPIBAttributes, m_phyRxDropTrace, m_phyRxEndTrace, m_plmeSetTRXStateConfirmCallback, m_setTRXState, m_signal, m_trxStatePending, max, ns3::LrWpanEdPower::measurementLength, ns3::Simulator::Now(), NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Packet::PeekPacketTag(), ns3::LrWpanPhyPibAttributes::phyCurrentChannel, and ns3::LrWpanSpectrumValueHelper::TotalAvgPower().
Referenced by StartRx().
EndSetTRXState()
void ns3::LrWpanPhy::EndSetTRXState (void) private
Called after applying a deferred transceiver state switch.
The result of the state switch is reported to the MAC.
Definition at line 1185 of file lr-wpan-phy.cc.
References ChangeTrxState(), ns3::IEEE_802_15_4_PHY_IDLE, ns3::IEEE_802_15_4_PHY_RX_ON, ns3::IEEE_802_15_4_PHY_TX_ON, ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_plmeSetTRXStateConfirmCallback, m_trxState, m_trxStatePending, NS_ABORT_IF, and NS_LOG_FUNCTION.
Referenced by PlmeSetTRXStateRequest().
EndTx()
void ns3::LrWpanPhy::EndTx (void) private
Finish the transmission of a frame.
This is called at the end of a frame transmission, applying possibly pending PHY state changes and fireing the appropriate trace sources and confirm callbacks to the MAC.
Definition at line 1200 of file lr-wpan-phy.cc.
References ChangeTrxState(), ns3::IEEE_802_15_4_PHY_BUSY_TX, ns3::IEEE_802_15_4_PHY_IDLE, ns3::IEEE_802_15_4_PHY_SUCCESS, ns3::IEEE_802_15_4_PHY_TRX_OFF, ns3::IEEE_802_15_4_PHY_TX_ON, ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), ns3::EventId::IsRunning(), m_currentTxPacket, m_pdDataConfirmCallback, m_phyTxDropTrace, m_phyTxEndTrace, m_plmeSetTRXStateConfirmCallback, m_setTRXState, m_trxState, m_trxStatePending, NS_ABORT_IF, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by PdDataRequest().
GetChannel()
Ptr< SpectrumChannel > ns3::LrWpanPhy::GetChannel (void)
Get the currently attached channel.
Returns
the channel
Definition at line 241 of file lr-wpan-phy.cc.
References m_channel, and NS_LOG_FUNCTION.
GetDataOrSymbolRate()
double ns3::LrWpanPhy::GetDataOrSymbolRate (bool isData)
implement PLME SetAttribute confirm SAP bit rate is in kbit/s.
Symbol rate is in ksymbol/s.
Parameters
isData is true for data rate or false for symbol rate
Returns
the rate value of this PHY
Definition at line 1269 of file lr-wpan-phy.cc.
References ns3::LrWpanPhyDataAndSymbolRates::bitRate, dataSymbolRates, ns3::IEEE_802_15_4_INVALID_PHY_OPTION, m_phyOption, NS_ASSERT, NS_LOG_FUNCTION, and ns3::LrWpanPhyDataAndSymbolRates::symbolRate.
Referenced by CalculateTxTime(), CheckInterference(), GetPpduHeaderTxTime(), PlmeCcaRequest(), PlmeEdRequest(), and PlmeSetTRXStateRequest().
GetDevice()
Ptr< NetDevice > ns3::LrWpanPhy::GetDevice (void) const virtual
Get the associated NetDevice instance.
Returns
a Ptr to the associated NetDevice instance
Implements ns3::SpectrumPhy.
Definition at line 201 of file lr-wpan-phy.cc.
References m_device, and NS_LOG_FUNCTION.
GetErrorModel()
Ptr< LrWpanErrorModel > ns3::LrWpanPhy::GetErrorModel (void) const
get the error model in use
Returns
pointer to LrWpanErrorModel in use
Definition at line 1394 of file lr-wpan-phy.cc.
References m_errorModel, and NS_LOG_FUNCTION.
GetMobility()
Ptr< MobilityModel > ns3::LrWpanPhy::GetMobility (void) virtual
Get the associated MobilityModel instance.
Returns
a Ptr to the associated MobilityModel instance
Implements ns3::SpectrumPhy.
Definition at line 209 of file lr-wpan-phy.cc.
References m_mobility, and NS_LOG_FUNCTION.
GetMyPhyOption()
LrWpanPhyOption ns3::LrWpanPhy::GetMyPhyOption (void) private
Get the currently configured PHY option.
See IEEE 802.15.4-2006, section 6.1.2, Table 2.
Returns
the PHY option
Definition at line 1354 of file lr-wpan-phy.cc.
References m_phyOption, and NS_LOG_FUNCTION.
GetNoisePowerSpectralDensity()
Ptr< const SpectrumValue > ns3::LrWpanPhy::GetNoisePowerSpectralDensity (void)
Get the noise power spectral density.
Returns
the Noise Power Spectral Density
Definition at line 1379 of file lr-wpan-phy.cc.
References m_noise, and NS_LOG_FUNCTION.
GetPhySHRDuration()
uint64_t ns3::LrWpanPhy::GetPhySHRDuration (void) const
Get the duration of the SHR (preamble and SFD) in symbols, depending on the currently selected channel.
Returns
the SHR duration in symbols
Definition at line 1401 of file lr-wpan-phy.cc.
References ns3::IEEE_802_15_4_INVALID_PHY_OPTION, m_phyOption, NS_ASSERT, NS_LOG_FUNCTION, ppduHeaderSymbolNumbers, ns3::LrWpanPhyPpduHeaderSymbolNumber::shrPreamble, and ns3::LrWpanPhyPpduHeaderSymbolNumber::shrSfd.
GetPhySymbolsPerOctet()
double ns3::LrWpanPhy::GetPhySymbolsPerOctet (void) const
Get the number of symbols per octet, depending on the currently selected channel.
Returns
the number of symbols per octet
Definition at line 1411 of file lr-wpan-phy.cc.
References ns3::LrWpanPhyDataAndSymbolRates::bitRate, dataSymbolRates, ns3::IEEE_802_15_4_INVALID_PHY_OPTION, m_phyOption, NS_ASSERT, NS_LOG_FUNCTION, and ns3::LrWpanPhyDataAndSymbolRates::symbolRate.
GetPpduHeaderTxTime()
Time ns3::LrWpanPhy::GetPpduHeaderTxTime (void) private
Calculate the time required for sending the PPDU header, that is the preamble, SFD and PHR.
Returns
The time required for sending the PPDU header.
Definition at line 1290 of file lr-wpan-phy.cc.
References GetDataOrSymbolRate(), ns3::IEEE_802_15_4_INVALID_PHY_OPTION, m_phyOption, NS_ASSERT, NS_LOG_FUNCTION, ns3::LrWpanPhyPpduHeaderSymbolNumber::phr, ppduHeaderSymbolNumbers, ns3::Seconds(), ns3::LrWpanPhyPpduHeaderSymbolNumber::shrPreamble, and ns3::LrWpanPhyPpduHeaderSymbolNumber::shrSfd.
Referenced by CalculateTxTime().
GetRxAntenna()
Ptr< AntennaModel > ns3::LrWpanPhy::GetRxAntenna (void) virtual
Get the AntennaModel used by the NetDevice for reception.
Returns
a Ptr to the AntennaModel used by the NetDevice for reception
Implements ns3::SpectrumPhy.
Definition at line 263 of file lr-wpan-phy.cc.
References m_antenna, and NS_LOG_FUNCTION.
GetRxSpectrumModel()
Ptr< const SpectrumModel > ns3::LrWpanPhy::GetRxSpectrumModel (void) const virtual
Returns
returns the SpectrumModel that this SpectrumPhy expects to be used for all SpectrumValues that are passed to StartRx. If 0 is returned, it means that any model will be accepted.
Implements ns3::SpectrumPhy.
Definition at line 249 of file lr-wpan-phy.cc.
References ns3::SpectrumValue::GetSpectrumModel(), m_txPsd, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::LrWpanPhy::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 74 of file lr-wpan-phy.cc.
References m_phyRxBeginTrace, m_phyRxDropTrace, m_phyRxEndTrace, m_phyTxBeginTrace, m_phyTxDropTrace, m_phyTxEndTrace, m_trxState, m_trxStateLogger, ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
PdDataRequest()
void ns3::LrWpanPhy::PdDataRequest (const uint32_t psduLength, Ptr< Packet > p)
IEEE 802.15.4-2006 section 6.2.1.1 PD-DATA.request Request to transfer MPDU from MAC (transmitting)
Parameters
psduLength number of bytes in the PSDU
p the packet to be transmitted
Definition at line 523 of file lr-wpan-phy.cc.
References aMaxPhyPacketSize, CalculateTxTime(), ChangeTrxState(), EndTx(), ns3::IEEE_802_15_4_PHY_BUSY_TX, ns3::IEEE_802_15_4_PHY_RX_ON, ns3::IEEE_802_15_4_PHY_TRX_OFF, ns3::IEEE_802_15_4_PHY_TX_ON, ns3::IEEE_802_15_4_PHY_UNSPECIFIED, ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), ns3::EventId::IsRunning(), m_antenna, m_channel, m_currentTxPacket, m_pdDataConfirmCallback, m_pdDataRequest, m_phyTxBeginTrace, m_phyTxDropTrace, m_setTRXState, m_trxState, m_txPsd, NS_ASSERT, NS_FATAL_ERROR, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Packet::RemovePacketTag(), and ns3::Simulator::Schedule().
PhyIsBusy()
bool ns3::LrWpanPhy::PhyIsBusy (void) const private
Check if the PHY is busy, which is the case if the PHY is currently sending or receiving a frame.
Returns
true, if the PHY is busy, false otherwise
Definition at line 1054 of file lr-wpan-phy.cc.
References ns3::IEEE_802_15_4_PHY_BUSY, ns3::IEEE_802_15_4_PHY_BUSY_RX, ns3::IEEE_802_15_4_PHY_BUSY_TX, m_trxState, and NS_LOG_FUNCTION.
Referenced by EndCca(), and PlmeSetAttributeRequest().
PlmeCcaRequest()
void ns3::LrWpanPhy::PlmeCcaRequest (void)
IEEE 802.15.4-2006 section 6.2.2.1 PLME-CCA.request Perform a CCA per section 6.9.9.
Definition at line 598 of file lr-wpan-phy.cc.
References EndCca(), GetDataOrSymbolRate(), ns3::IEEE_802_15_4_PHY_BUSY, ns3::IEEE_802_15_4_PHY_BUSY_RX, ns3::IEEE_802_15_4_PHY_RX_ON, ns3::IEEE_802_15_4_PHY_TRX_OFF, ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_ccaPeakPower, m_ccaRequest, m_plmeCcaConfirmCallback, m_trxState, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), and ns3::Seconds().
PlmeEdRequest()
void ns3::LrWpanPhy::PlmeEdRequest (void)
IEEE 802.15.4-2006 section 6.2.2.3 PLME-ED.request Perform an ED per section 6.9.7.
Definition at line 625 of file lr-wpan-phy.cc.
References ns3::LrWpanEdPower::averagePower, EndEd(), GetDataOrSymbolRate(), ns3::IEEE_802_15_4_PHY_BUSY_RX, ns3::IEEE_802_15_4_PHY_BUSY_TX, ns3::IEEE_802_15_4_PHY_RX_ON, ns3::IEEE_802_15_4_PHY_TX_ON, ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), ns3::LrWpanEdPower::lastUpdate, m_edPower, m_edRequest, m_plmeEdConfirmCallback, m_trxState, ns3::LrWpanEdPower::measurementLength, ns3::Simulator::Now(), NS_LOG_FUNCTION, ns3::Simulator::Schedule(), and ns3::Seconds().
PlmeGetAttributeRequest()
void ns3::LrWpanPhy::PlmeGetAttributeRequest (LrWpanPibAttributeIdentifier id)
IEEE 802.15.4-2006 section 6.2.2.5 PLME-GET.request Get attributes per definition from Table 23 in section 6.4.2.
Parameters
id the attributed identifier
Definition at line 652 of file lr-wpan-phy.cc.
References ns3::IEEE_802_15_4_PHY_SUCCESS, ns3::IEEE_802_15_4_PHY_UNSUPPORTED_ATTRIBUTE, ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_phyPIBAttributes, m_plmeGetAttributeConfirmCallback, NS_LOG_FUNCTION, ns3::phyCCAMode, ns3::phyChannelsSupported, ns3::phyCurrentChannel, ns3::phyCurrentPage, ns3::phyMaxFrameDuration, ns3::phySHRDuration, ns3::phySymbolsPerOctet, and ns3::phyTransmitPower.
PlmeSetAttributeRequest()
void ns3::LrWpanPhy::PlmeSetAttributeRequest (LrWpanPibAttributeIdentifier id, LrWpanPhyPibAttributes * attribute)
IEEE 802.15.4-2006 section 6.2.2.9 PLME-SET.request Set attributes per definition from Table 23 in section 6.4.2.
Parameters
id the attributed identifier
attribute the attribute value
Definition at line 893 of file lr-wpan-phy.cc.
References ns3::EventId::Cancel(), ChannelSupported(), ns3::LrWpanSpectrumValueHelper::CreateTxPowerSpectralDensity(), ns3::IEEE_802_15_4_PHY_IDLE, ns3::IEEE_802_15_4_PHY_INVALID_PARAMETER, ns3::IEEE_802_15_4_PHY_SUCCESS, ns3::IEEE_802_15_4_PHY_TRX_OFF, ns3::IEEE_802_15_4_PHY_UNSUPPORTED_ATTRIBUTE, ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_currentRxPacket, m_currentTxPacket, m_pdDataConfirmCallback, m_pdDataRequest, m_phyPIBAttributes, m_plmeSetAttributeConfirmCallback, m_plmeSetTRXStateConfirmCallback, m_setTRXState, m_trxState, m_trxStatePending, m_txPsd, NS_ASSERT, NS_LOG_FUNCTION, ns3::phyCCAMode, ns3::LrWpanPhyPibAttributes::phyCCAMode, ns3::phyChannelsSupported, ns3::LrWpanPhyPibAttributes::phyChannelsSupported, ns3::phyCurrentChannel, ns3::LrWpanPhyPibAttributes::phyCurrentChannel, PhyIsBusy(), ns3::phyTransmitPower, and ns3::LrWpanPhyPibAttributes::phyTransmitPower.
PlmeSetTRXStateRequest()
void ns3::LrWpanPhy::PlmeSetTRXStateRequest (LrWpanPhyEnumeration state)
IEEE 802.15.4-2006 section 6.2.2.7 PLME-SET-TRX-STATE.request Set PHY state.
Parameters
state in RX_ON,TRX_OFF,FORCE_TRX_OFF,TX_ON
Definition at line 687 of file lr-wpan-phy.cc.
References aTurnaroundTime, ns3::EventId::Cancel(), CancelEd(), ChangeTrxState(), EndSetTRXState(), GetDataOrSymbolRate(), ns3::IEEE_802_15_4_PHY_BUSY, ns3::IEEE_802_15_4_PHY_BUSY_RX, ns3::IEEE_802_15_4_PHY_BUSY_TX, ns3::IEEE_802_15_4_PHY_FORCE_TRX_OFF, ns3::IEEE_802_15_4_PHY_IDLE, ns3::IEEE_802_15_4_PHY_RX_ON, ns3::IEEE_802_15_4_PHY_SUCCESS, ns3::IEEE_802_15_4_PHY_TRX_OFF, ns3::IEEE_802_15_4_PHY_TX_ON, ns3::EventId::IsExpired(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_ccaRequest, m_currentRxPacket, m_currentTxPacket, m_plmeCcaConfirmCallback, m_plmeSetTRXStateConfirmCallback, m_setTRXState, m_trxState, m_trxStatePending, NS_ABORT_IF, NS_FATAL_ERROR, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Simulator::Schedule(), and ns3::Seconds().
SetAntenna()
void ns3::LrWpanPhy::SetAntenna (Ptr< AntennaModel > a)
Set the attached antenna.
Parameters
a the antenna
Definition at line 270 of file lr-wpan-phy.cc.
References m_antenna, and NS_LOG_FUNCTION.
SetChannel()
void ns3::LrWpanPhy::SetChannel (Ptr< SpectrumChannel > c) virtual
Set the channel attached to this device.
Parameters
c the channel
Implements ns3::SpectrumPhy.
Definition at line 233 of file lr-wpan-phy.cc.
References m_channel, and NS_LOG_FUNCTION.
SetDevice()
void ns3::LrWpanPhy::SetDevice (Ptr< NetDevice > d) virtual
Set the associated NetDevice instance.
Parameters
d the NetDevice instance
Implements ns3::SpectrumPhy.
Definition at line 217 of file lr-wpan-phy.cc.
References m_device, and NS_LOG_FUNCTION.
SetErrorModel()
void ns3::LrWpanPhy::SetErrorModel (Ptr< LrWpanErrorModel > e)
set the error model to use
Parameters
e pointer to LrWpanErrorModel to use
Definition at line 1386 of file lr-wpan-phy.cc.
References m_errorModel, NS_ASSERT, and NS_LOG_FUNCTION.
SetMobility()
void ns3::LrWpanPhy::SetMobility (Ptr< MobilityModel > m) virtual
Set the mobility model associated with this device.
Parameters
m the mobility model
Implements ns3::SpectrumPhy.
Definition at line 225 of file lr-wpan-phy.cc.
References m_mobility, and NS_LOG_FUNCTION.
SetMyPhyOption()
void ns3::LrWpanPhy::SetMyPhyOption (void) private
Configure the PHY option according to the current channel and channel page.
See IEEE 802.15.4-2006, section 6.1.2, Table 2.
Definition at line 1308 of file lr-wpan-phy.cc.
References ns3::IEEE_802_15_4_2_4GHZ_OQPSK, ns3::IEEE_802_15_4_868MHZ_ASK, ns3::IEEE_802_15_4_868MHZ_BPSK, ns3::IEEE_802_15_4_868MHZ_OQPSK, ns3::IEEE_802_15_4_915MHZ_ASK, ns3::IEEE_802_15_4_915MHZ_BPSK, ns3::IEEE_802_15_4_915MHZ_OQPSK, ns3::IEEE_802_15_4_INVALID_PHY_OPTION, m_phyOption, m_phyPIBAttributes, NS_LOG_FUNCTION, ns3::LrWpanPhyPibAttributes::phyCurrentChannel, and ns3::LrWpanPhyPibAttributes::phyCurrentPage.
Referenced by LrWpanPhy().
SetNoisePowerSpectralDensity()
void ns3::LrWpanPhy::SetNoisePowerSpectralDensity (Ptr< const SpectrumValue > noisePsd)
Set the noise power spectral density.
Parameters
noisePsd the Noise Power Spectral Density in power units (Watt, Pascal...) per Hz.
Definition at line 1370 of file lr-wpan-phy.cc.
References m_noise, NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_INFO.
SetPdDataConfirmCallback()
void ns3::LrWpanPhy::SetPdDataConfirmCallback (PdDataConfirmCallback c)
set the callback for the end of a TX, as part of the interconnections betweenthe PHY and the MAC.
The callback implements PD SAP.
Parameters
c the callback
Definition at line 1004 of file lr-wpan-phy.cc.
References m_pdDataConfirmCallback, and NS_LOG_FUNCTION.
SetPdDataIndicationCallback()
void ns3::LrWpanPhy::SetPdDataIndicationCallback (PdDataIndicationCallback c)
set the callback for the end of a RX, as part of the interconnections betweenthe PHY and the MAC.
The callback implements PD Indication SAP.
Parameters
c the callback
Definition at line 997 of file lr-wpan-phy.cc.
References m_pdDataIndicationCallback, and NS_LOG_FUNCTION.
SetPlmeCcaConfirmCallback()
void ns3::LrWpanPhy::SetPlmeCcaConfirmCallback (PlmeCcaConfirmCallback c)
set the callback for the end of a CCA, as part of the interconnections betweenthe PHY and the MAC.
The callback implement PLME CCA confirm SAP
Parameters
c the callback
Definition at line 1011 of file lr-wpan-phy.cc.
References m_plmeCcaConfirmCallback, and NS_LOG_FUNCTION.
SetPlmeEdConfirmCallback()
void ns3::LrWpanPhy::SetPlmeEdConfirmCallback (PlmeEdConfirmCallback c)
set the callback for the end of an ED, as part of the interconnections betweenthe PHY and the MAC.
The callback implement PLME ED confirm SAP
Parameters
c the callback
Definition at line 1018 of file lr-wpan-phy.cc.
References m_plmeEdConfirmCallback, and NS_LOG_FUNCTION.
SetPlmeGetAttributeConfirmCallback()
void ns3::LrWpanPhy::SetPlmeGetAttributeConfirmCallback (PlmeGetAttributeConfirmCallback c)
set the callback for the end of an GetAttribute, as part of the interconnections betweenthe PHY and the MAC.
The callback implement PLME GetAttribute confirm SAP
Parameters
c the callback
Definition at line 1025 of file lr-wpan-phy.cc.
References m_plmeGetAttributeConfirmCallback, and NS_LOG_FUNCTION.
SetPlmeSetAttributeConfirmCallback()
void ns3::LrWpanPhy::SetPlmeSetAttributeConfirmCallback (PlmeSetAttributeConfirmCallback c)
set the callback for the end of an SetAttribute, as part of the interconnections betweenthe PHY and the MAC.
The callback implement PLME SetAttribute confirm SAP
Parameters
c the callback
Definition at line 1039 of file lr-wpan-phy.cc.
References m_plmeSetAttributeConfirmCallback, and NS_LOG_FUNCTION.
SetPlmeSetTRXStateConfirmCallback()
void ns3::LrWpanPhy::SetPlmeSetTRXStateConfirmCallback (PlmeSetTRXStateConfirmCallback c)
set the callback for the end of an SetTRXState, as part of the interconnections betweenthe PHY and the MAC.
The callback implement PLME SetTRXState confirm SAP
Parameters
c the callback
Definition at line 1032 of file lr-wpan-phy.cc.
References m_plmeSetTRXStateConfirmCallback, and NS_LOG_FUNCTION.
SetTxPowerSpectralDensity()
void ns3::LrWpanPhy::SetTxPowerSpectralDensity (Ptr< SpectrumValue > txPsd)
Set the Power Spectral Density of outgoing signals in W/Hz.
Parameters
txPsd the Power Spectral Density value
Definition at line 1361 of file lr-wpan-phy.cc.
References m_txPsd, NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_INFO.
StartRx()
void ns3::LrWpanPhy::StartRx (Ptr< SpectrumSignalParameters > params) virtual
Notify the SpectrumPhy instance of an incoming waveform.
Parameters
params the SpectrumSignalParameters associated with the incoming waveform
Implements ns3::SpectrumPhy.
Definition at line 277 of file lr-wpan-phy.cc.
References ns3::LrWpanEdPower::averagePower, ChangeTrxState(), CheckInterference(), EndRx(), ns3::Time::GetTimeStep(), ns3::IEEE_802_15_4_PHY_BUSY_RX, ns3::IEEE_802_15_4_PHY_RX_ON, ns3::EventId::IsExpired(), ns3::EventId::IsRunning(), ns3::LrWpanEdPower::lastUpdate, m_ccaPeakPower, m_ccaRequest, m_currentRxPacket, m_edPower, m_edRequest, m_noise, m_phyPIBAttributes, m_phyRxBeginTrace, m_phyRxDropTrace, m_rxLastUpdate, m_setTRXState, m_signal, m_trxState, ns3::LrWpanEdPower::measurementLength, ns3::Simulator::Now(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::LrWpanPhyPibAttributes::phyCurrentChannel, ns3::Simulator::Schedule(), and ns3::LrWpanSpectrumValueHelper::TotalAvgPower().
Member Data Documentation
aMaxPhyPacketSize
const uint32_t ns3::LrWpanPhy::aMaxPhyPacketSize = 127 static
The maximum packet size accepted by the PHY.
See Table 22 in section 6.4.1 of IEEE 802.15.4-2006
Definition at line 262 of file lr-wpan-phy.h.
Referenced by ns3::LrWpanMac::McpsDataRequest(), and PdDataRequest().
aTurnaroundTime
const uint32_t ns3::LrWpanPhy::aTurnaroundTime = 12 static
The turnaround time for switching the transceiver from RX to TX or vice versa.
See Table 22 in section 6.4.1 of IEEE 802.15.4-2006
Definition at line 269 of file lr-wpan-phy.h.
Referenced by PlmeSetTRXStateRequest().
dataSymbolRates
const LrWpanPhyDataAndSymbolRates ns3::LrWpanPhy::dataSymbolRates static protected
Initial value:
= { { 20.0, 20.0},
                                  { 40.0, 40.0},
                                  { 250.0, 12.5},
                                  { 250.0, 50.0},
                                  { 100.0, 25.0},
                                  { 250.0, 62.5},
                                  { 250.0, 62.5}}
The data and symbol rates for the different PHY options.
See Table 2 in section 6.1.2 IEEE 802.15.4-2006. Bit rate is in kbit/s. Symbol rate is in ksymbol/s.
Definition at line 499 of file lr-wpan-phy.h.
Referenced by GetDataOrSymbolRate(), and GetPhySymbolsPerOctet().
m_antenna
Ptr<AntennaModel> ns3::LrWpanPhy::m_antenna private
The antenna used by the transceiver.
Definition at line 696 of file lr-wpan-phy.h.
Referenced by GetRxAntenna(), PdDataRequest(), and SetAntenna().
m_ccaPeakPower
double ns3::LrWpanPhy::m_ccaPeakPower private
Helper value for the peak power value during CCA.
Definition at line 786 of file lr-wpan-phy.h.
Referenced by EndCca(), PlmeCcaRequest(), and StartRx().
m_ccaRequest
EventId ns3::LrWpanPhy::m_ccaRequest private
Scheduler event of a currently running CCA request.
Definition at line 824 of file lr-wpan-phy.h.
Referenced by PlmeCcaRequest(), PlmeSetTRXStateRequest(), and StartRx().
m_channel
Ptr<SpectrumChannel> ns3::LrWpanPhy::m_channel private
The channel attached to this transceiver.
Definition at line 691 of file lr-wpan-phy.h.
Referenced by DoDispose(), GetChannel(), PdDataRequest(), and SetChannel().
m_currentRxPacket
std::pair<Ptr<LrWpanSpectrumSignalParameters>, bool> ns3::LrWpanPhy::m_currentRxPacket private
Statusinformation of the currently received packet.
The first parameter contains the frame, as well the signal power of the frame. The second parameter is set to false, if the frame is either invalid or destroyed due to interference.
Definition at line 811 of file lr-wpan-phy.h.
Referenced by LrWpanPhy(), CheckInterference(), EndRx(), PlmeSetAttributeRequest(), PlmeSetTRXStateRequest(), and StartRx().
m_currentTxPacket
PacketAndStatus ns3::LrWpanPhy::m_currentTxPacket private
Statusinformation of the currently transmitted packet.
The first parameter contains the frame. The second parameter is set to false, if the frame not completely transmitted, in the event of a force transceiver switch, for example.
Definition at line 819 of file lr-wpan-phy.h.
Referenced by LrWpanPhy(), EndTx(), PdDataRequest(), PlmeSetAttributeRequest(), and PlmeSetTRXStateRequest().
m_device
Ptr<NetDevice> ns3::LrWpanPhy::m_device private
The configured net device.
Definition at line 686 of file lr-wpan-phy.h.
Referenced by DoDispose(), EndRx(), GetDevice(), and SetDevice().
m_edPower
LrWpanEdPower ns3::LrWpanPhy::m_edPower private
Helper value for tracking the average power during ED.
Definition at line 781 of file lr-wpan-phy.h.
Referenced by LrWpanPhy(), EndEd(), EndRx(), PlmeEdRequest(), and StartRx().
m_edRequest
EventId ns3::LrWpanPhy::m_edRequest private
Scheduler event of a currently running ED request.
Definition at line 829 of file lr-wpan-phy.h.
Referenced by CancelEd(), EndRx(), PlmeEdRequest(), and StartRx().
m_errorModel
Ptr<LrWpanErrorModel> ns3::LrWpanPhy::m_errorModel private
The error model describing the bit and packet error rates.
Definition at line 711 of file lr-wpan-phy.h.
Referenced by LrWpanPhy(), CheckInterference(), DoDispose(), GetErrorModel(), and SetErrorModel().
m_mobility
Ptr<MobilityModel> ns3::LrWpanPhy::m_mobility private
The mobility model used by the PHY.
Definition at line 681 of file lr-wpan-phy.h.
Referenced by DoDispose(), GetMobility(), and SetMobility().
m_noise
Ptr<const SpectrumValue> ns3::LrWpanPhy::m_noise private
The spectral density for for the noise.
Definition at line 706 of file lr-wpan-phy.h.
Referenced by LrWpanPhy(), CheckInterference(), DoDispose(), GetNoisePowerSpectralDensity(), SetNoisePowerSpectralDensity(), and StartRx().
m_pdDataConfirmCallback
PdDataConfirmCallback ns3::LrWpanPhy::m_pdDataConfirmCallback private
This callback is used to report packet transmission status to the MAC layer.
See IEEE 802.15.4-2006, section 6.2.1.2.
Definition at line 741 of file lr-wpan-phy.h.
Referenced by DoDispose(), EndTx(), PdDataRequest(), PlmeSetAttributeRequest(), and SetPdDataConfirmCallback().
m_pdDataIndicationCallback
PdDataIndicationCallback ns3::LrWpanPhy::m_pdDataIndicationCallback private
This callback is used to notify incoming packets to the MAC layer.
See IEEE 802.15.4-2006, section 6.2.1.3.
Definition at line 735 of file lr-wpan-phy.h.
Referenced by DoDispose(), EndRx(), and SetPdDataIndicationCallback().
m_pdDataRequest
EventId ns3::LrWpanPhy::m_pdDataRequest private
Scheduler event of a currently running data transmission request.
Definition at line 839 of file lr-wpan-phy.h.
Referenced by PdDataRequest(), and PlmeSetAttributeRequest().
m_phyOption
LrWpanPhyOption ns3::LrWpanPhy::m_phyOption private
The currently configured PHY type.
Definition at line 776 of file lr-wpan-phy.h.
Referenced by GetDataOrSymbolRate(), GetMyPhyOption(), GetPhySHRDuration(), GetPhySymbolsPerOctet(), GetPpduHeaderTxTime(), and SetMyPhyOption().
m_phyPIBAttributes
LrWpanPhyPibAttributes ns3::LrWpanPhy::m_phyPIBAttributes private
The current PHY PIB attributes.
Definition at line 716 of file lr-wpan-phy.h.
Referenced by LrWpanPhy(), ChannelSupported(), CheckInterference(), EndCca(), EndEd(), EndRx(), PlmeGetAttributeRequest(), PlmeSetAttributeRequest(), SetMyPhyOption(), and StartRx().
m_phyRxBeginTrace
TracedCallback<Ptr<const Packet> > ns3::LrWpanPhy::m_phyRxBeginTrace private
The trace source fired when a packet begins the reception process from the medium.
See also
class CallBackTraceSource
Definition at line 651 of file lr-wpan-phy.h.
Referenced by GetTypeId(), and StartRx().
m_phyRxDropTrace
TracedCallback<Ptr<const Packet> > ns3::LrWpanPhy::m_phyRxDropTrace private
The trace source fired when the phy layer drops a packet it has received.
See also
class CallBackTraceSource
Definition at line 666 of file lr-wpan-phy.h.
Referenced by EndRx(), GetTypeId(), and StartRx().
m_phyRxEndTrace
TracedCallback<Ptr<const Packet>, double > ns3::LrWpanPhy::m_phyRxEndTrace private
The trace source fired when a packet ends the reception process from the medium.
Second quantity is received SINR.
See also
class CallBackTraceSource
Definition at line 659 of file lr-wpan-phy.h.
Referenced by EndRx(), and GetTypeId().
m_phyTxBeginTrace
TracedCallback<Ptr<const Packet> > ns3::LrWpanPhy::m_phyTxBeginTrace private
The trace source fired when a packet begins the transmission process on the medium.
See also
class CallBackTraceSource
Definition at line 627 of file lr-wpan-phy.h.
Referenced by GetTypeId(), and PdDataRequest().
m_phyTxDropTrace
TracedCallback<Ptr<const Packet> > ns3::LrWpanPhy::m_phyTxDropTrace private
The trace source fired when the phy layer drops a packet as it tries to transmit it.
See also
class CallBackTraceSource
Definition at line 643 of file lr-wpan-phy.h.
Referenced by EndTx(), GetTypeId(), and PdDataRequest().
m_phyTxEndTrace
TracedCallback<Ptr<const Packet> > ns3::LrWpanPhy::m_phyTxEndTrace private
The trace source fired when a packet ends the transmission process on the medium.
See also
class CallBackTraceSource
Definition at line 635 of file lr-wpan-phy.h.
Referenced by EndTx(), and GetTypeId().
m_plmeCcaConfirmCallback
PlmeCcaConfirmCallback ns3::LrWpanPhy::m_plmeCcaConfirmCallback private
This callback is used to report CCA status to the MAC or CSMA/CA.
See IEEE 802.15.4-2006, section 6.2.2.2.
Definition at line 747 of file lr-wpan-phy.h.
Referenced by DoDispose(), EndCca(), PlmeCcaRequest(), PlmeSetTRXStateRequest(), and SetPlmeCcaConfirmCallback().
m_plmeEdConfirmCallback
PlmeEdConfirmCallback ns3::LrWpanPhy::m_plmeEdConfirmCallback private
This callback is used to report ED status to the MAC.
See IEEE 802.15.4-2006, section 6.2.2.4.
Definition at line 753 of file lr-wpan-phy.h.
Referenced by CancelEd(), DoDispose(), EndEd(), PlmeEdRequest(), and SetPlmeEdConfirmCallback().
m_plmeGetAttributeConfirmCallback
PlmeGetAttributeConfirmCallback ns3::LrWpanPhy::m_plmeGetAttributeConfirmCallback private
This callback is used to report requested attribute values back to the MAC.
See IEEE 802.15.4-2006, section 6.2.2.6.
Definition at line 759 of file lr-wpan-phy.h.
Referenced by DoDispose(), PlmeGetAttributeRequest(), and SetPlmeGetAttributeConfirmCallback().
m_plmeSetAttributeConfirmCallback
PlmeSetAttributeConfirmCallback ns3::LrWpanPhy::m_plmeSetAttributeConfirmCallback private
This callback is used to report attribute set results back to the MAC.
See IEEE 802.15.4-2006, section 6.2.2.10.
Definition at line 771 of file lr-wpan-phy.h.
Referenced by DoDispose(), PlmeSetAttributeRequest(), and SetPlmeSetAttributeConfirmCallback().
m_plmeSetTRXStateConfirmCallback
PlmeSetTRXStateConfirmCallback ns3::LrWpanPhy::m_plmeSetTRXStateConfirmCallback private
This callback is used to report transceiver state change status to the MAC.
See IEEE 802.15.4-2006, section 6.2.2.8.
Definition at line 765 of file lr-wpan-phy.h.
Referenced by DoDispose(), EndRx(), EndSetTRXState(), EndTx(), PlmeSetAttributeRequest(), PlmeSetTRXStateRequest(), and SetPlmeSetTRXStateConfirmCallback().
m_random
Ptr<UniformRandomVariable> ns3::LrWpanPhy::m_random private
Uniform random variable stream.
Definition at line 844 of file lr-wpan-phy.h.
Referenced by LrWpanPhy(), AssignStreams(), and CheckInterference().
m_rxLastUpdate
Time ns3::LrWpanPhy::m_rxLastUpdate private
Timestamp of the last calculation of the PER of a packet currently received.
Definition at line 803 of file lr-wpan-phy.h.
Referenced by LrWpanPhy(), CheckInterference(), and StartRx().
m_rxSensitivity
double ns3::LrWpanPhy::m_rxSensitivity private
The receiver sensitivity.
Definition at line 791 of file lr-wpan-phy.h.
Referenced by LrWpanPhy(), EndCca(), and EndEd().
m_setTRXState
EventId ns3::LrWpanPhy::m_setTRXState private
Scheduler event of a currently running deferred transceiver state switch.
Definition at line 834 of file lr-wpan-phy.h.
Referenced by DoDispose(), EndRx(), EndTx(), PdDataRequest(), PlmeSetAttributeRequest(), PlmeSetTRXStateRequest(), and StartRx().
m_signal
Ptr<LrWpanInterferenceHelper> ns3::LrWpanPhy::m_signal private
The accumulated signals currently received by the transceiver, including the signal of a possibly received packet, as well as all signals considered noise.
Definition at line 798 of file lr-wpan-phy.h.
Referenced by LrWpanPhy(), CheckInterference(), DoDispose(), EndCca(), EndEd(), EndRx(), and StartRx().
m_trxState
TracedValue<LrWpanPhyEnumeration> ns3::LrWpanPhy::m_trxState private
The current transceiver state.
Definition at line 722 of file lr-wpan-phy.h.
Referenced by LrWpanPhy(), ChangeTrxState(), CheckInterference(), DoDispose(), EndCca(), EndSetTRXState(), EndTx(), GetTypeId(), PdDataRequest(), PhyIsBusy(), PlmeCcaRequest(), PlmeEdRequest(), PlmeSetAttributeRequest(), PlmeSetTRXStateRequest(), and StartRx().
m_trxStateLogger
TracedCallback<Time, LrWpanPhyEnumeration, LrWpanPhyEnumeration> ns3::LrWpanPhy::m_trxStateLogger private
The trace source fired when the phy layer changes the transceiver state.
See also
class CallBackTraceSource
Deprecated:
The LrWpanPhyEnumeration state is now accessible as the TracedValue TrxStateValue. This TracedCallback will be removed in a future release.
Definition at line 676 of file lr-wpan-phy.h.
Referenced by ChangeTrxState(), and GetTypeId().
m_trxStatePending
LrWpanPhyEnumeration ns3::LrWpanPhy::m_trxStatePending private
The next pending state to applied after the current action of the PHY is completed.
Definition at line 728 of file lr-wpan-phy.h.
Referenced by LrWpanPhy(), DoDispose(), EndRx(), EndSetTRXState(), EndTx(), PlmeSetAttributeRequest(), and PlmeSetTRXStateRequest().
m_txPsd
Ptr<SpectrumValue> ns3::LrWpanPhy::m_txPsd private
The transmit power spectral density.
Definition at line 701 of file lr-wpan-phy.h.
Referenced by LrWpanPhy(), DoDispose(), GetRxSpectrumModel(), PdDataRequest(), PlmeSetAttributeRequest(), and SetTxPowerSpectralDensity().
ppduHeaderSymbolNumbers
const LrWpanPhyPpduHeaderSymbolNumber ns3::LrWpanPhy::ppduHeaderSymbolNumbers static protected
Initial value:
= { { 32.0, 8.0, 8.0},
                                          { 32.0, 8.0, 8.0},
                                          { 2.0, 1.0, 0.4},
                                          { 6.0, 1.0, 1.6},
                                          { 8.0, 2.0, 2.0},
                                          { 8.0, 2.0, 2.0},
                                          { 8.0, 2.0, 2.0}}
The preamble, SFD, and PHR lengths in symbols for the different PHY options.
See Table 19 and Table 20 in section 6.3 IEEE 802.15.4-2006
Definition at line 504 of file lr-wpan-phy.h.
Referenced by GetPhySHRDuration(), and GetPpduHeaderTxTime().
The documentation for this class was generated from the following files:
src/lr-wpan/model/lr-wpan-phy.h
src/lr-wpan/model/lr-wpan-phy.cc