ns-3: ns3::UanTransducerHd Class Reference
ns3::UanTransducerHd Class Reference
UAN Models
Half duplex implementation of transducer object.
#include "uan-transducer-hd.h"
Public Member Functions
UanTransducerHd ()
Constructor.
virtual ~UanTransducerHd ()
Dummy destructor, see DoDispose.
virtual void AddPhy (Ptr< UanPhy >)
Attach a physical network layer above this transducer.
virtual double ApplyRxGainDb (double rxPowerDb, UanTxMode mode)
Apply receiver gain in dB to the received power.
virtual void Clear (void)
Clears all pointer references.
virtual const ArrivalList & GetArrivalList (void) const
Get the list of overlapped (in time) packets at this transducer.
virtual Ptr< UanChannel > GetChannel (void) const
Get the attached channel.
virtual const UanPhyList & GetPhyList (void) const
Get the list of physical layer above this transducer.
virtual double GetRxGainDb (void)
Get the receiver gain added to signal at receiver in dB.
virtual State GetState (void) const
Get the transducer state.
virtual bool IsRx (void) const
Is the state receiving (or available for reception)?
virtual bool IsTx (void) const
Is the state transmitting?
virtual void Receive (Ptr< Packet > packet, double rxPowerDb, UanTxMode txMode, UanPdp pdp)
Notify this object that a new packet has arrived at this nodes location.
virtual void SetChannel (Ptr< UanChannel > chan)
Attach this transducer to a channel.
virtual void SetRxGainDb (double gainDb)
Set the receiver gain.
virtual void Transmit (Ptr< UanPhy > src, Ptr< Packet > packet, double txPowerDb, UanTxMode txMode)
Transmit a packet from this transducer.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::UanTransducer
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose ()
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void EndTx (void)
Handle end of transmission event.
void RemoveArrival (UanPacketArrival arrival)
Remove an entry from the arrival list.
Private Attributes
ArrivalList m_arrivalList
List of arriving packets which overlap in time.
Ptr< UanChannel > m_channel
The attached channel.
bool m_cleared
Flab when we've been cleared.
EventId m_endTxEvent
Event scheduled for end of transmission.
Time m_endTxTime
Time at which transmission will be completed.
UanPhyList m_phyList
List of physical layers attached above this tranducer.
double m_rxGainDb
Receive gain in dB.
State m_state
Transducer state.
Additional Inherited Members
Public Types inherited from ns3::UanTransducer
typedef std::list< UanPacketArrival > ArrivalList
List of arriving packets overlapping in time.
enum State { TX , RX }
Transducer state.
typedef std::list< Ptr< UanPhy > > UanPhyList
List of UanPhy objects.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Half duplex implementation of transducer object.
This class will only allow attached Phy's to receive packets if not in TX mode.
Config Paths
ns3::UanTransducerHd is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::UanNetDevice/Transducer/$ns3::UanTransducerHd"
Attributes
RxGainDb: Gain in Db added to incoming signal at receiver.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 136 bytes (on a 64-bit architecture).
Definition at line 36 of file uan-transducer-hd.h.
Constructor & Destructor Documentation
UanTransducerHd()
ns3::UanTransducerHd::UanTransducerHd ()
Constructor.
Definition at line 36 of file uan-transducer-hd.cc.
~UanTransducerHd()
ns3::UanTransducerHd::~UanTransducerHd () virtual
Dummy destructor, see DoDispose.
Definition at line 45 of file uan-transducer-hd.cc.
Member Function Documentation
AddPhy()
void ns3::UanTransducerHd::AddPhy (Ptr< UanPhy > phy) virtual
Attach a physical network layer above this transducer.
More than one physical layer may be attached.
Parameters
phy The physical layer.
Implements ns3::UanTransducer.
Definition at line 244 of file uan-transducer-hd.cc.
References m_phyList, and third::phy.
ApplyRxGainDb()
double ns3::UanTransducerHd::ApplyRxGainDb (double rxPowerDb, UanTxMode mode) virtual
Apply receiver gain in dB to the received power.
Parameters
rxPowerDb Signal power in dB of arriving packet.
mode Mode arriving packet is using.
Returns
Updated receive power (in dB) with gain applied.
Implements ns3::UanTransducer.
Definition at line 143 of file uan-transducer-hd.cc.
References GetRxGainDb(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by Receive().
Clear()
void ns3::UanTransducerHd::Clear (void) virtual
Clears all pointer references.
Implements ns3::UanTransducer.
Definition at line 50 of file uan-transducer-hd.cc.
References ns3::EventId::Cancel(), m_arrivalList, m_channel, m_cleared, m_endTxEvent, and m_phyList.
Referenced by DoDispose().
DoDispose()
void ns3::UanTransducerHd::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 83 of file uan-transducer-hd.cc.
References Clear(), and ns3::Object::DoDispose().
EndTx()
void ns3::UanTransducerHd::EndTx (void) private
Handle end of transmission event.
Definition at line 225 of file uan-transducer-hd.cc.
References m_endTxTime, m_state, NS_ASSERT, ns3::UanTransducer::RX, ns3::Seconds(), and ns3::UanTransducer::TX.
Referenced by Transmit().
GetArrivalList()
const UanTransducer::ArrivalList & ns3::UanTransducerHd::GetArrivalList (void) const virtual
Get the list of overlapped (in time) packets at this transducer.
Returns
List of all packets currently crossing this node in the water.
Implements ns3::UanTransducer.
Definition at line 125 of file uan-transducer-hd.cc.
References m_arrivalList.
GetChannel()
Ptr< UanChannel > ns3::UanTransducerHd::GetChannel (void) const virtual
Get the attached channel.
Returns
The channel.
Implements ns3::UanTransducer.
Definition at line 239 of file uan-transducer-hd.cc.
References m_channel.
GetPhyList()
const UanTransducer::UanPhyList & ns3::UanTransducerHd::GetPhyList (void) const virtual
Get the list of physical layer above this transducer.
Returns
List of attached physical layers.
Implements ns3::UanTransducer.
Definition at line 250 of file uan-transducer-hd.cc.
References m_phyList.
GetRxGainDb()
double ns3::UanTransducerHd::GetRxGainDb (void) virtual
Get the receiver gain added to signal at receiver in dB.
Returns
The gain (in dB).
Implements ns3::UanTransducer.
Definition at line 137 of file uan-transducer-hd.cc.
References m_rxGainDb.
Referenced by ApplyRxGainDb().
GetState()
UanTransducer::State ns3::UanTransducerHd::GetState (void) const virtual
Get the transducer state.
Returns
State (TX or RX) of this transducer.
Implements ns3::UanTransducer.
Definition at line 105 of file uan-transducer-hd.cc.
References m_state.
GetTypeId()
TypeId ns3::UanTransducerHd::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 89 of file uan-transducer-hd.cc.
References m_rxGainDb, ns3::MakeDoubleAccessor(), and ns3::TypeId::SetParent().
IsRx()
bool ns3::UanTransducerHd::IsRx (void) const virtual
Is the state receiving (or available for reception)?
Returns
True if this transducer is available for receiving an incoming packet.
Implements ns3::UanTransducer.
Definition at line 112 of file uan-transducer-hd.cc.
References m_state, and ns3::UanTransducer::RX.
IsTx()
bool ns3::UanTransducerHd::IsTx (void) const virtual
Is the state transmitting?
Returns
True if there is a packet being transmitted from this transducer.
Implements ns3::UanTransducer.
Definition at line 118 of file uan-transducer-hd.cc.
References m_state, and ns3::UanTransducer::TX.
Receive()
void ns3::UanTransducerHd::Receive (Ptr< Packet > packet, double rxPowerDb, UanTxMode txMode, UanPdp pdp) virtual
Notify this object that a new packet has arrived at this nodes location.
Parameters
packet Packet arriving.
rxPowerDb Signal power in dB of arriving packet.
txMode Mode arriving packet is using.
pdp PDP of arriving signal.
Implements ns3::UanTransducer.
Definition at line 152 of file uan-transducer-hd.cc.
References ApplyRxGainDb(), ns3::UanTxMode::GetDataRateBps(), ns3::Packet::GetSize(), m_arrivalList, m_phyList, m_state, ns3::Now(), ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, RemoveArrival(), ns3::UanTransducer::RX, ns3::Time::S, ns3::Simulator::Schedule(), and ns3::Seconds().
RemoveArrival()
void ns3::UanTransducerHd::RemoveArrival (UanPacketArrival arrival) private
Remove an entry from the arrival list.
Parameters
arrival The packet arrival to remove.
Definition at line 256 of file uan-transducer-hd.cc.
References ns3::UanPacketArrival::GetPacket(), m_arrivalList, and m_phyList.
Referenced by Receive().
SetChannel()
void ns3::UanTransducerHd::SetChannel (Ptr< UanChannel > chan) virtual
Attach this transducer to a channel.
Parameters
chan The channel
Implements ns3::UanTransducer.
Definition at line 232 of file uan-transducer-hd.cc.
References m_channel, and NS_LOG_DEBUG.
SetRxGainDb()
void ns3::UanTransducerHd::SetRxGainDb (double gainDb) virtual
Set the receiver gain.
Parameters
gainDb Gain added at receiver, in dB.
Implements ns3::UanTransducer.
Definition at line 131 of file uan-transducer-hd.cc.
References m_rxGainDb.
Transmit()
void ns3::UanTransducerHd::Transmit (Ptr< UanPhy > src, Ptr< Packet > packet, double txPowerDb, UanTxMode txMode) virtual
Transmit a packet from this transducer.
Parameters
src Source PHY.
packet Packet to transmit.
txPowerDb Outgoing Tx power of packet.
txMode Mode to transmit packet with.
Implements ns3::UanTransducer.
Definition at line 184 of file uan-transducer-hd.cc.
References ns3::EventId::Cancel(), EndTx(), ns3::UanTxMode::GetDataRateBps(), ns3::Packet::GetSize(), m_channel, m_endTxEvent, m_endTxTime, m_phyList, m_state, max, ns3::UanPhy::NotifyTxEnd(), ns3::Simulator::Now(), NS_LOG_DEBUG, ns3::Simulator::Schedule(), ns3::Seconds(), and ns3::UanTransducer::TX.
Member Data Documentation
m_arrivalList
ArrivalList ns3::UanTransducerHd::m_arrivalList private
List of arriving packets which overlap in time.
Definition at line 68 of file uan-transducer-hd.h.
Referenced by Clear(), GetArrivalList(), Receive(), and RemoveArrival().
m_channel
Ptr<UanChannel> ns3::UanTransducerHd::m_channel private
The attached channel.
Definition at line 70 of file uan-transducer-hd.h.
Referenced by Clear(), GetChannel(), SetChannel(), and Transmit().
m_cleared
bool ns3::UanTransducerHd::m_cleared private
Flab when we've been cleared.
Definition at line 73 of file uan-transducer-hd.h.
Referenced by Clear().
m_endTxEvent
EventId ns3::UanTransducerHd::m_endTxEvent private
Event scheduled for end of transmission.
Definition at line 71 of file uan-transducer-hd.h.
Referenced by Clear(), and Transmit().
m_endTxTime
Time ns3::UanTransducerHd::m_endTxTime private
Time at which transmission will be completed.
Definition at line 72 of file uan-transducer-hd.h.
Referenced by EndTx(), and Transmit().
m_phyList
UanPhyList ns3::UanTransducerHd::m_phyList private
List of physical layers attached above this tranducer.
Definition at line 69 of file uan-transducer-hd.h.
Referenced by AddPhy(), Clear(), GetPhyList(), Receive(), RemoveArrival(), and Transmit().
m_rxGainDb
double ns3::UanTransducerHd::m_rxGainDb private
Receive gain in dB.
Definition at line 74 of file uan-transducer-hd.h.
Referenced by GetRxGainDb(), GetTypeId(), and SetRxGainDb().
m_state
State ns3::UanTransducerHd::m_state private
Transducer state.
Definition at line 67 of file uan-transducer-hd.h.
Referenced by EndTx(), GetState(), IsRx(), IsTx(), Receive(), and Transmit().
The documentation for this class was generated from the following files:
src/uan/model/uan-transducer-hd.h
src/uan/model/uan-transducer-hd.cc