ns-3: ns3::LteFfrDistributedAlgorithm Class Reference
ns3::LteFfrDistributedAlgorithm Class Reference
Distributed Fractional Frequency Reuse algorithm implementation.
#include "lte-ffr-distributed-algorithm.h"
Classes
class UeMeasure
Measurements reported by a UE for a cell ID.
Public Member Functions
LteFfrDistributedAlgorithm ()
virtual ~LteFfrDistributedAlgorithm ()
virtual LteFfrRrcSapProvider * GetLteFfrRrcSapProvider ()
Export the "provider" part of the LteFfrRrcSap interface.
virtual LteFfrSapProvider * GetLteFfrSapProvider ()
Export the "provider" part of the LteFfrSap interface.
virtual void SetLteFfrRrcSapUser (LteFfrRrcSapUser *s)
Set the "user" part of the LteFfrRrcSap interface that this frequency reuse algorithm instance will interact with.
virtual void SetLteFfrSapUser (LteFfrSapUser *s)
Set the "user" part of the LteFfrSap interface that this frequency reuse algorithm instance will interact with.
Public Member Functions inherited from ns3::LteFfrAlgorithm
LteFfrAlgorithm ()
virtual ~LteFfrAlgorithm ()
uint16_t GetDlBandwidth () const
uint8_t GetFrCellTypeId () const
uint16_t GetUlBandwidth () const
void SetDlBandwidth (uint16_t bw)
void SetFrCellTypeId (uint8_t cellTypeId)
void SetUlBandwidth (uint16_t bw)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::LteFfrAlgorithm
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose ()
Destructor implementation.
virtual std::vector< bool > DoGetAvailableDlRbg ()
Implementation of LteFfrSapProvider::GetAvailableDlRbg.
virtual std::vector< bool > DoGetAvailableUlRbg ()
Implementation of LteFfrSapProvider::GetAvailableUlRbg.
virtual uint16_t DoGetMinContinuousUlBandwidth ()
DoGetMinContinuousUlBandwidth in number of RB.
virtual uint8_t DoGetTpc (uint16_t rnti)
DoGetTpc for UE.
virtual void DoInitialize ()
Initialize() implementation.
virtual bool DoIsDlRbgAvailableForUe (int i, uint16_t rnti)
Implementation of LteFfrSapProvider::IsDlRbgAvailableForUe.
virtual bool DoIsUlRbgAvailableForUe (int i, uint16_t rnti)
Implementation of LteFfrSapProvider::IsUlRbgAvailableForUe.
virtual void DoRecvLoadInformation (EpcX2Sap::LoadInformationParams params)
DoRecvLoadInformation.
virtual void DoReportDlCqiInfo (const struct FfMacSchedSapProvider::SchedDlCqiInfoReqParameters &params)
DoReportDlCqiInfo.
virtual void DoReportUeMeas (uint16_t rnti, LteRrcSap::MeasResults measResults)
Implementation of LteFfrRrcSapProvider::ReportUeMeas.
virtual void DoReportUlCqiInfo (const struct FfMacSchedSapProvider::SchedUlCqiInfoReqParameters &params)
DoReportUlCqiInfo.
virtual void DoReportUlCqiInfo (std::map< uint16_t, std::vector< double > > ulCqiMap)
DoReportUlCqiInfo.
virtual void Reconfigure ()
Automatic FR reconfiguration.
Protected Member Functions inherited from ns3::LteFfrAlgorithm
virtual void DoSetBandwidth (uint16_t ulBandwidth, uint16_t dlBandwidth)
Implementation of LteFfrRrcSapProvider::SetBandwidth.
virtual void DoSetCellId (uint16_t cellId)
SetCellId.
int GetRbgSize (int dlbandwidth)
Get RBG size for DL Bandwidth according to table 7.1.6.1-1 of 36.213.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
typedef std::map< uint16_t, Ptr< UeMeasure > > MeasurementRow_t
Cell Id is used as the key for the following map.
typedef std::map< uint16_t, MeasurementRow_t > MeasurementTable_t
RNTI is used as the key for the following map.
enum UePosition { AreaUnset , CenterArea , EdgeArea }
UePosition enumeration.
Private Member Functions
void Calculate ()
Calculate function.
void InitializeDownlinkRbgMaps ()
Initialize down link RGB maps function.
void InitializeUplinkRbgMaps ()
Initialize up link RGB maps function.
void SendLoadInformation (uint16_t targetCellId)
Send load information function.
void SetDownlinkConfiguration (uint16_t cellId, uint8_t bandwidth)
Set down link configuration function.
void SetUplinkConfiguration (uint16_t cellId, uint8_t bandwidth)
Set up link configuration function.
void UpdateNeighbourMeasurements (uint16_t rnti, uint16_t cellId, uint8_t rsrp, uint8_t rsrq)
Initialize up link RGB maps function.
Private Attributes
EventId m_calculationEvent
calculation event
Time m_calculationInterval
calculation interval
std::map< uint16_t, uint32_t > m_cellWeightMap
cell weight map
uint8_t m_centerAreaTpc
center area TPC
uint8_t m_centerPowerOffset
center power offset
std::vector< bool > m_dlEdgeRbgMap
DL edge RBG map.
std::vector< bool > m_dlRbgMap
DL RBG map.
uint8_t m_edgeAreaTpc
edge area TCP
uint8_t m_edgePowerOffset
edge power offset
uint8_t m_edgeRbNum
edge RB number
uint8_t m_edgeSubBandRsrqThreshold
edge sub band RSRQ threshold
LteFfrRrcSapProvider * m_ffrRrcSapProvider
FFR RRC SAP Provider.
LteFfrRrcSapUser * m_ffrRrcSapUser
FFR RRC SAP User.
LteFfrSapProvider * m_ffrSapProvider
FFR SAP Provider.
LteFfrSapUser * m_ffrSapUser
FFR SAP User.
std::vector< uint16_t > m_neigborCell
neighbor cell
std::map< uint16_t, std::vector< bool > > m_rntp
RNTP.
uint8_t m_rsrpDifferenceThreshold
RSRP difference threshold.
uint8_t m_rsrpMeasId
RSRP measurement ID.
uint8_t m_rsrqMeasId
RSRQ measurement ID.
MeasurementTable_t m_ueMeasures
UE measures.
std::map< uint16_t, uint8_t > m_ues
UEs map.
std::vector< bool > m_ulEdgeRbgMap
UL edge RBG map.
std::vector< bool > m_ulRbgMap
UL RBG map.
Friends
class MemberLteFfrRrcSapProvider< LteFfrDistributedAlgorithm >
let the forwarder class access the protected and private members
class MemberLteFfrSapProvider< LteFfrDistributedAlgorithm >
let the forwarder class access the protected and private members
Additional Inherited Members
Protected Attributes inherited from ns3::LteFfrAlgorithm
uint16_t m_cellId
cell ID
uint8_t m_dlBandwidth
downlink bandwidth in RBs
bool m_enabledInUplink
If true FR algorithm will also work in Uplink.
uint8_t m_frCellTypeId
FFR cell type ID for automatic configuration.
bool m_needReconfiguration
If true FR algorithm will be reconfigured.
uint8_t m_ulBandwidth
uplink bandwidth in RBs
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Distributed Fractional Frequency Reuse algorithm implementation.
Config Paths
ns3::LteFfrDistributedAlgorithm is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteEnbNetDevice/LteFfrAlgorithm/$ns3::LteFfrDistributedAlgorithm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteEnbNetDevice/ComponentCarrierMap/[i]/LteFfrAlgorithm/$ns3::LteFfrDistributedAlgorithm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteEnbNetDevice/LteFfrAlgorithm/$ns3::LteFfrDistributedAlgorithm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteEnbNetDevice/ComponentCarrierMap/[i]/LteFfrAlgorithm/$ns3::LteFfrDistributedAlgorithm"
Attributes
CalculationInterval: Time interval between calculation of Edge sub-band, Default value 1 second
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+09ns
Flags: construct write read
RsrqThreshold: If the RSRQ of is worse than this threshold, UE should be served in Edge sub-band
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Initial value: 20
Flags: construct write read
RsrpDifferenceThreshold: If the difference between the power of the signal received by UE from the serving cell and the power of the signal received from the adjacent cell is less than a RsrpDifferenceThreshold value, the cell weight is incremented
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Initial value: 20
Flags: construct write read
CenterPowerOffset: PdschConfigDedicated::Pa value for Edge Sub-band, default value dB0
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Initial value: 5
Flags: construct write read
EdgePowerOffset: PdschConfigDedicated::Pa value for Edge Sub-band, default value dB0
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Initial value: 5
Flags: construct write read
EdgeRbNum: Number of RB that can be used in edge Sub-band
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Initial value: 8
Flags: construct write read
CenterAreaTpc: TPC value which will be set in DL-DCI for UEs in center areaAbsolute mode is used, default value 1 is mapped to -1 according toTS36.213 Table 5.1.1.1-2
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Initial value: 1
Flags: construct write read
EdgeAreaTpc: TPC value which will be set in DL-DCI for UEs in edge areaAbsolute mode is used, default value 1 is mapped to -1 according toTS36.213 Table 5.1.1.1-2
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Initial value: 1
Flags: construct write read
Attributes defined in parent class ns3::LteFfrAlgorithm
FrCellTypeId: Downlink FR cell type ID for automatic configuration,default value is 0 and it means that user needs to configure FR algorithm manually,if it is set to 1,2 or 3 FR algorithm will be configured automatically
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Initial value: 0
Flags: construct write read
EnabledInUplink: If FR algorithm will also work in Uplink, default value true
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 352 bytes (on a 64-bit architecture).
Definition at line 35 of file lte-ffr-distributed-algorithm.h.
Member Typedef Documentation
MeasurementRow_t
typedef std::map<uint16_t, Ptr<UeMeasure> > ns3::LteFfrDistributedAlgorithm::MeasurementRow_t private
Cell Id is used as the key for the following map.
Definition at line 178 of file lte-ffr-distributed-algorithm.h.
MeasurementTable_t
typedef std::map<uint16_t, MeasurementRow_t> ns3::LteFfrDistributedAlgorithm::MeasurementTable_t private
RNTI is used as the key for the following map.
Definition at line 180 of file lte-ffr-distributed-algorithm.h.
Member Enumeration Documentation
UePosition
enum ns3::LteFfrDistributedAlgorithm::UePosition private
UePosition enumeration.
Enumerator
AreaUnset
CenterArea
EdgeArea
Definition at line 140 of file lte-ffr-distributed-algorithm.h.
Constructor & Destructor Documentation
LteFfrDistributedAlgorithm()
ns3::LteFfrDistributedAlgorithm::LteFfrDistributedAlgorithm ()
Definition at line 32 of file lte-ffr-distributed-algorithm.cc.
References m_ffrRrcSapProvider, m_ffrSapProvider, MemberLteFfrRrcSapProvider< LteFfrDistributedAlgorithm >, MemberLteFfrSapProvider< LteFfrDistributedAlgorithm >, and NS_LOG_FUNCTION.
~LteFfrDistributedAlgorithm()
ns3::LteFfrDistributedAlgorithm::~LteFfrDistributedAlgorithm () virtual
Definition at line 42 of file lte-ffr-distributed-algorithm.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Calculate()
void ns3::LteFfrDistributedAlgorithm::Calculate () private
Calculate function.
Definition at line 479 of file lte-ffr-distributed-algorithm.cc.
References EdgeArea, ns3::LteFfrAlgorithm::GetRbgSize(), m_calculationEvent, m_calculationInterval, ns3::LteFfrAlgorithm::m_cellId, m_cellWeightMap, ns3::LteFfrAlgorithm::m_dlBandwidth, m_dlEdgeRbgMap, m_edgeRbNum, m_neigborCell, m_rntp, m_rsrpDifferenceThreshold, m_ueMeasures, m_ues, ns3::LteFfrAlgorithm::m_ulBandwidth, m_ulEdgeRbgMap, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::Simulator::Schedule(), and SendLoadInformation().
Referenced by DoInitialize().
DoDispose()
void ns3::LteFfrDistributedAlgorithm::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::LteFfrAlgorithm.
Definition at line 49 of file lte-ffr-distributed-algorithm.cc.
References m_ffrRrcSapProvider, m_ffrSapProvider, and NS_LOG_FUNCTION.
DoGetAvailableDlRbg()
std::vector< bool > ns3::LteFfrDistributedAlgorithm::DoGetAvailableDlRbg () protected virtual
Implementation of LteFfrSapProvider::GetAvailableDlRbg.
Returns
vector of size (m_dlBandwidth/RbgSize); false indicates that RBG is free to use, true otherwise
Implements ns3::LteFfrAlgorithm.
Definition at line 228 of file lte-ffr-distributed-algorithm.cc.
References InitializeDownlinkRbgMaps(), m_dlRbgMap, ns3::LteFfrAlgorithm::m_needReconfiguration, NS_LOG_FUNCTION, and Reconfigure().
DoGetAvailableUlRbg()
std::vector< bool > ns3::LteFfrDistributedAlgorithm::DoGetAvailableUlRbg () protected virtual
Implementation of LteFfrSapProvider::GetAvailableUlRbg.
Returns
vector of size m_ulBandwidth; false indicates that RB is free to use, true otherwise
Implements ns3::LteFfrAlgorithm.
Definition at line 269 of file lte-ffr-distributed-algorithm.cc.
References InitializeUplinkRbgMaps(), m_ulRbgMap, and NS_LOG_FUNCTION.
DoGetMinContinuousUlBandwidth()
uint16_t ns3::LteFfrDistributedAlgorithm::DoGetMinContinuousUlBandwidth () protected virtual
DoGetMinContinuousUlBandwidth in number of RB.
Returns
number of RB in min continuous UL Bandwidth
Implements ns3::LteFfrAlgorithm.
Definition at line 369 of file lte-ffr-distributed-algorithm.cc.
References m_edgeRbNum, ns3::LteFfrAlgorithm::m_enabledInUplink, ns3::LteFfrAlgorithm::m_ulBandwidth, and NS_LOG_FUNCTION.
DoGetTpc()
uint8_t ns3::LteFfrDistributedAlgorithm::DoGetTpc (uint16_t rnti) protected virtual
DoGetTpc for UE.
Parameters
rnti
Returns
TPC value
Implements ns3::LteFfrAlgorithm.
Definition at line 331 of file lte-ffr-distributed-algorithm.cc.
References EdgeArea, m_centerAreaTpc, m_edgeAreaTpc, ns3::LteFfrAlgorithm::m_enabledInUplink, m_ues, and NS_LOG_FUNCTION.
DoInitialize()
void ns3::LteFfrDistributedAlgorithm::DoInitialize (void) protected virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 148 of file lte-ffr-distributed-algorithm.cc.
References ns3::LteFfrRrcSapUser::AddUeMeasReportConfigForFfr(), Calculate(), ns3::LteRrcSap::ThresholdEutra::choice, ns3::Object::DoInitialize(), ns3::LteRrcSap::ReportConfigEutra::EVENT_A1, ns3::LteRrcSap::ReportConfigEutra::EVENT_A4, ns3::LteRrcSap::ReportConfigEutra::eventId, ns3::LteFfrAlgorithm::GetRbgSize(), m_calculationEvent, ns3::LteFfrAlgorithm::m_dlBandwidth, m_dlEdgeRbgMap, m_ffrRrcSapUser, ns3::LteFfrAlgorithm::m_frCellTypeId, m_rsrpMeasId, m_rsrqMeasId, ns3::LteFfrAlgorithm::m_ulBandwidth, m_ulEdgeRbgMap, ns3::LteRrcSap::ReportConfigEutra::MS120, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::LteRrcSap::ThresholdEutra::range, ns3::LteRrcSap::ReportConfigEutra::reportInterval, ns3::LteRrcSap::ReportConfigEutra::RSRP, ns3::LteRrcSap::ReportConfigEutra::RSRQ, ns3::Simulator::ScheduleNow(), SetDownlinkConfiguration(), SetUplinkConfiguration(), ns3::LteRrcSap::ReportConfigEutra::threshold1, ns3::LteRrcSap::ThresholdEutra::THRESHOLD_RSRP, ns3::LteRrcSap::ThresholdEutra::THRESHOLD_RSRQ, and ns3::LteRrcSap::ReportConfigEutra::triggerQuantity.
DoIsDlRbgAvailableForUe()
bool ns3::LteFfrDistributedAlgorithm::DoIsDlRbgAvailableForUe (int rbId, uint16_t rnti) protected virtual
Implementation of LteFfrSapProvider::IsDlRbgAvailableForUe.
Parameters
rbId
rnti Radio Network Temporary Identity, an integer identifying the UE where the report originates from
Returns
true if UE can be served on i-th RB, false otherwise
Implements ns3::LteFfrAlgorithm.
Definition at line 246 of file lte-ffr-distributed-algorithm.cc.
References AreaUnset, EdgeArea, m_dlEdgeRbgMap, m_ues, and NS_LOG_FUNCTION.
DoIsUlRbgAvailableForUe()
bool ns3::LteFfrDistributedAlgorithm::DoIsUlRbgAvailableForUe (int rbId, uint16_t rnti) protected virtual
Implementation of LteFfrSapProvider::IsUlRbgAvailableForUe.
Parameters
rbId
rnti Radio Network Temporary Identity, an integer identifying the UE where the report originates from
Returns
true if UE can be served on i-th RB, false otherwise
Implements ns3::LteFfrAlgorithm.
Definition at line 282 of file lte-ffr-distributed-algorithm.cc.
References AreaUnset, EdgeArea, ns3::LteFfrAlgorithm::m_enabledInUplink, m_ues, m_ulEdgeRbgMap, and NS_LOG_FUNCTION.
DoRecvLoadInformation()
void ns3::LteFfrDistributedAlgorithm::DoRecvLoadInformation (EpcX2Sap::LoadInformationParams params) protected virtual
DoRecvLoadInformation.
Parameters
params
Implements ns3::LteFfrAlgorithm.
Definition at line 644 of file lte-ffr-distributed-algorithm.cc.
References ns3::EpcX2Sap::LoadInformationParams::cellInformationList, ns3::LteFfrAlgorithm::m_cellId, m_rntp, NS_LOG_FUNCTION, and NS_LOG_INFO.
DoReportDlCqiInfo()
void ns3::LteFfrDistributedAlgorithm::DoReportDlCqiInfo (const struct FfMacSchedSapProvider::SchedDlCqiInfoReqParameters & params) protected virtual
DoReportDlCqiInfo.
Parameters
params
Implements ns3::LteFfrAlgorithm.
Definition at line 310 of file lte-ffr-distributed-algorithm.cc.
References NS_LOG_FUNCTION, and NS_LOG_WARN.
DoReportUeMeas()
void ns3::LteFfrDistributedAlgorithm::DoReportUeMeas (uint16_t rnti, LteRrcSap::MeasResults measResults) protected virtual
Implementation of LteFfrRrcSapProvider::ReportUeMeas.
Parameters
rnti Radio Network Temporary Identity, an integer identifying the UE where the report originates from
measResults a single report of one measurement identity
Implements ns3::LteFfrAlgorithm.
Definition at line 387 of file lte-ffr-distributed-algorithm.cc.
References AreaUnset, CenterArea, EdgeArea, ns3::LteRrcSap::MeasResults::haveMeasResultNeighCells, ns3::LteFfrAlgorithm::m_cellId, m_centerPowerOffset, m_edgePowerOffset, m_edgeSubBandRsrqThreshold, m_ffrRrcSapUser, m_neigborCell, m_rsrpMeasId, m_rsrqMeasId, m_ues, ns3::LteRrcSap::MeasResults::measId, ns3::LteRrcSap::MeasResults::measResultListEutra, NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_WARN, ns3::LteRrcSap::PdschConfigDedicated::pa, ns3::LteRrcSap::MeasResults::rsrpResult, ns3::LteRrcSap::MeasResults::rsrqResult, ns3::LteFfrRrcSapUser::SetPdschConfigDedicated(), and UpdateNeighbourMeasurements().
DoReportUlCqiInfo() [1/2]
void ns3::LteFfrDistributedAlgorithm::DoReportUlCqiInfo (const struct FfMacSchedSapProvider::SchedUlCqiInfoReqParameters & params) protected virtual
DoReportUlCqiInfo.
Parameters
params
Implements ns3::LteFfrAlgorithm.
Definition at line 317 of file lte-ffr-distributed-algorithm.cc.
References NS_LOG_FUNCTION, and NS_LOG_WARN.
DoReportUlCqiInfo() [2/2]
void ns3::LteFfrDistributedAlgorithm::DoReportUlCqiInfo (std::map< uint16_t, std::vector< double > > ulCqiMap) protected virtual
DoReportUlCqiInfo.
Parameters
ulCqiMap
Implements ns3::LteFfrAlgorithm.
Definition at line 324 of file lte-ffr-distributed-algorithm.cc.
References NS_LOG_FUNCTION, and NS_LOG_WARN.
GetLteFfrRrcSapProvider()
LteFfrRrcSapProvider * ns3::LteFfrDistributedAlgorithm::GetLteFfrRrcSapProvider () virtual
Export the "provider" part of the LteFfrRrcSap interface.
Returns
the reference to the "provider" part of the interface, typically to be kept by an LteEnbRrc instance
Implements ns3::LteFfrAlgorithm.
Definition at line 140 of file lte-ffr-distributed-algorithm.cc.
References m_ffrRrcSapProvider, and NS_LOG_FUNCTION.
GetLteFfrSapProvider()
LteFfrSapProvider * ns3::LteFfrDistributedAlgorithm::GetLteFfrSapProvider () virtual
Export the "provider" part of the LteFfrSap interface.
Returns
the reference to the "provider" part of the interface, typically to be kept by an Scheduler instance
Implements ns3::LteFfrAlgorithm.
Definition at line 125 of file lte-ffr-distributed-algorithm.cc.
References m_ffrSapProvider, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::LteFfrDistributedAlgorithm::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 58 of file lte-ffr-distributed-algorithm.cc.
References m_calculationInterval, m_centerAreaTpc, m_centerPowerOffset, m_edgeAreaTpc, m_edgePowerOffset, m_edgeRbNum, m_edgeSubBandRsrqThreshold, m_rsrpDifferenceThreshold, ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeUintegerAccessor(), ns3::Seconds(), and ns3::TypeId::SetParent().
InitializeDownlinkRbgMaps()
void ns3::LteFfrDistributedAlgorithm::InitializeDownlinkRbgMaps () private
Initialize down link RGB maps function.
Definition at line 211 of file lte-ffr-distributed-algorithm.cc.
References ns3::LteFfrAlgorithm::GetRbgSize(), ns3::LteFfrAlgorithm::m_dlBandwidth, m_dlRbgMap, and NS_LOG_FUNCTION.
Referenced by DoGetAvailableDlRbg(), and Reconfigure().
InitializeUplinkRbgMaps()
void ns3::LteFfrDistributedAlgorithm::InitializeUplinkRbgMaps () private
Initialize up link RGB maps function.
Definition at line 220 of file lte-ffr-distributed-algorithm.cc.
References ns3::LteFfrAlgorithm::m_ulBandwidth, m_ulRbgMap, and NS_LOG_FUNCTION.
Referenced by DoGetAvailableUlRbg(), and Reconfigure().
Reconfigure()
void ns3::LteFfrDistributedAlgorithm::Reconfigure () protected virtual
Automatic FR reconfiguration.
Implements ns3::LteFfrAlgorithm.
Definition at line 185 of file lte-ffr-distributed-algorithm.cc.
References InitializeDownlinkRbgMaps(), InitializeUplinkRbgMaps(), ns3::LteFfrAlgorithm::m_dlBandwidth, ns3::LteFfrAlgorithm::m_frCellTypeId, ns3::LteFfrAlgorithm::m_needReconfiguration, ns3::LteFfrAlgorithm::m_ulBandwidth, NS_LOG_FUNCTION, SetDownlinkConfiguration(), and SetUplinkConfiguration().
Referenced by DoGetAvailableDlRbg().
SendLoadInformation()
void ns3::LteFfrDistributedAlgorithm::SendLoadInformation (uint16_t targetCellId) private
Send load information function.
Parameters
targetCellId the cell ID
Definition at line 618 of file lte-ffr-distributed-algorithm.cc.
References ns3::EpcX2Sap::LoadInformationParams::cellInformationList, ns3::LteFfrAlgorithm::m_cellId, m_dlEdgeRbgMap, m_ffrRrcSapUser, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::EpcX2Sap::CellInformationItem::relativeNarrowbandTxBand, ns3::EpcX2Sap::RelativeNarrowbandTxBand::rntpPerPrbList, ns3::LteFfrRrcSapUser::SendLoadInformation(), ns3::EpcX2Sap::CellInformationItem::sourceCellId, ns3::EpcX2Sap::LoadInformationParams::targetCellId, ns3::EpcX2Sap::CellInformationItem::ulHighInterferenceInformationList, and ns3::EpcX2Sap::CellInformationItem::ulInterferenceOverloadIndicationList.
Referenced by Calculate().
SetDownlinkConfiguration()
void ns3::LteFfrDistributedAlgorithm::SetDownlinkConfiguration (uint16_t cellId, uint8_t bandwidth) private
Set down link configuration function.
Parameters
cellId cell ID
bandwidth the bandwidth
Definition at line 199 of file lte-ffr-distributed-algorithm.cc.
References NS_LOG_FUNCTION.
Referenced by DoInitialize(), and Reconfigure().
SetLteFfrRrcSapUser()
void ns3::LteFfrDistributedAlgorithm::SetLteFfrRrcSapUser (LteFfrRrcSapUser * s) virtual
Set the "user" part of the LteFfrRrcSap interface that this frequency reuse algorithm instance will interact with.
Parameters
s a reference to the "user" part of the interface, typically a member of an LteEnbRrc instance
Implements ns3::LteFfrAlgorithm.
Definition at line 132 of file lte-ffr-distributed-algorithm.cc.
References m_ffrRrcSapUser, and NS_LOG_FUNCTION.
SetLteFfrSapUser()
void ns3::LteFfrDistributedAlgorithm::SetLteFfrSapUser (LteFfrSapUser * s) virtual
Set the "user" part of the LteFfrSap interface that this frequency reuse algorithm instance will interact with.
Parameters
s a reference to the "user" part of the interface, typically a member of an Scheduler instance
Implements ns3::LteFfrAlgorithm.
Definition at line 117 of file lte-ffr-distributed-algorithm.cc.
References m_ffrSapUser, and NS_LOG_FUNCTION.
SetUplinkConfiguration()
void ns3::LteFfrDistributedAlgorithm::SetUplinkConfiguration (uint16_t cellId, uint8_t bandwidth) private
Set up link configuration function.
Parameters
cellId cell ID
bandwidth the bandwidth
Definition at line 205 of file lte-ffr-distributed-algorithm.cc.
References NS_LOG_FUNCTION.
Referenced by DoInitialize(), and Reconfigure().
UpdateNeighbourMeasurements()
void ns3::LteFfrDistributedAlgorithm::UpdateNeighbourMeasurements (uint16_t rnti, uint16_t cellId, uint8_t rsrp, uint8_t rsrq) private
Initialize up link RGB maps function.
Parameters
rnti the RNTI
cellId the cell ID
rsrp the RSRP
rsrq the RSRQ
Definition at line 668 of file lte-ffr-distributed-algorithm.cc.
References m_ueMeasures, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by DoReportUeMeas().
Friends And Related Function Documentation
MemberLteFfrRrcSapProvider< LteFfrDistributedAlgorithm >
friend class MemberLteFfrRrcSapProvider< LteFfrDistributedAlgorithm > friend
let the forwarder class access the protected and private members
Definition at line 52 of file lte-ffr-distributed-algorithm.h.
Referenced by LteFfrDistributedAlgorithm().
MemberLteFfrSapProvider< LteFfrDistributedAlgorithm >
friend class MemberLteFfrSapProvider< LteFfrDistributedAlgorithm > friend
let the forwarder class access the protected and private members
Definition at line 52 of file lte-ffr-distributed-algorithm.h.
Referenced by LteFfrDistributedAlgorithm().
Member Data Documentation
m_calculationEvent
EventId ns3::LteFfrDistributedAlgorithm::m_calculationEvent private
calculation event
Definition at line 158 of file lte-ffr-distributed-algorithm.h.
Referenced by Calculate(), and DoInitialize().
m_calculationInterval
Time ns3::LteFfrDistributedAlgorithm::m_calculationInterval private
calculation interval
Definition at line 157 of file lte-ffr-distributed-algorithm.h.
Referenced by Calculate(), and GetTypeId().
m_cellWeightMap
std::map<uint16_t, uint32_t> ns3::LteFfrDistributedAlgorithm::m_cellWeightMap private
cell weight map
Definition at line 187 of file lte-ffr-distributed-algorithm.h.
Referenced by Calculate().
m_centerAreaTpc
uint8_t ns3::LteFfrDistributedAlgorithm::m_centerAreaTpc private
center area TPC
Definition at line 154 of file lte-ffr-distributed-algorithm.h.
Referenced by DoGetTpc(), and GetTypeId().
m_centerPowerOffset
uint8_t ns3::LteFfrDistributedAlgorithm::m_centerPowerOffset private
center power offset
Definition at line 151 of file lte-ffr-distributed-algorithm.h.
Referenced by DoReportUeMeas(), and GetTypeId().
m_dlEdgeRbgMap
std::vector<bool> ns3::LteFfrDistributedAlgorithm::m_dlEdgeRbgMap private
DL edge RBG map.
Definition at line 136 of file lte-ffr-distributed-algorithm.h.
Referenced by Calculate(), DoInitialize(), DoIsDlRbgAvailableForUe(), and SendLoadInformation().
m_dlRbgMap
std::vector<bool> ns3::LteFfrDistributedAlgorithm::m_dlRbgMap private
DL RBG map.
Definition at line 132 of file lte-ffr-distributed-algorithm.h.
Referenced by DoGetAvailableDlRbg(), and InitializeDownlinkRbgMaps().
m_edgeAreaTpc
uint8_t ns3::LteFfrDistributedAlgorithm::m_edgeAreaTpc private
edge area TCP
Definition at line 155 of file lte-ffr-distributed-algorithm.h.
Referenced by DoGetTpc(), and GetTypeId().
m_edgePowerOffset
uint8_t ns3::LteFfrDistributedAlgorithm::m_edgePowerOffset private
edge power offset
Definition at line 152 of file lte-ffr-distributed-algorithm.h.
Referenced by DoReportUeMeas(), and GetTypeId().
m_edgeRbNum
uint8_t ns3::LteFfrDistributedAlgorithm::m_edgeRbNum private
edge RB number
Definition at line 135 of file lte-ffr-distributed-algorithm.h.
Referenced by Calculate(), DoGetMinContinuousUlBandwidth(), and GetTypeId().
m_edgeSubBandRsrqThreshold
uint8_t ns3::LteFfrDistributedAlgorithm::m_edgeSubBandRsrqThreshold private
edge sub band RSRQ threshold
Definition at line 149 of file lte-ffr-distributed-algorithm.h.
Referenced by DoReportUeMeas(), and GetTypeId().
m_ffrRrcSapProvider
LteFfrRrcSapProvider* ns3::LteFfrDistributedAlgorithm::m_ffrRrcSapProvider private
FFR RRC SAP Provider.
Definition at line 130 of file lte-ffr-distributed-algorithm.h.
Referenced by LteFfrDistributedAlgorithm(), DoDispose(), and GetLteFfrRrcSapProvider().
m_ffrRrcSapUser
LteFfrRrcSapUser* ns3::LteFfrDistributedAlgorithm::m_ffrRrcSapUser private
FFR RRC SAP User.
Definition at line 129 of file lte-ffr-distributed-algorithm.h.
Referenced by DoInitialize(), DoReportUeMeas(), SendLoadInformation(), and SetLteFfrRrcSapUser().
m_ffrSapProvider
LteFfrSapProvider* ns3::LteFfrDistributedAlgorithm::m_ffrSapProvider private
FFR SAP Provider.
Definition at line 126 of file lte-ffr-distributed-algorithm.h.
Referenced by LteFfrDistributedAlgorithm(), DoDispose(), and GetLteFfrSapProvider().
m_ffrSapUser
LteFfrSapUser* ns3::LteFfrDistributedAlgorithm::m_ffrSapUser private
FFR SAP User.
Definition at line 125 of file lte-ffr-distributed-algorithm.h.
Referenced by SetLteFfrSapUser().
m_neigborCell
std::vector<uint16_t> ns3::LteFfrDistributedAlgorithm::m_neigborCell private
neighbor cell
Definition at line 183 of file lte-ffr-distributed-algorithm.h.
Referenced by Calculate(), and DoReportUeMeas().
m_rntp
std::map<uint16_t, std::vector <bool> > ns3::LteFfrDistributedAlgorithm::m_rntp private
RNTP.
Definition at line 189 of file lte-ffr-distributed-algorithm.h.
Referenced by Calculate(), and DoRecvLoadInformation().
m_rsrpDifferenceThreshold
uint8_t ns3::LteFfrDistributedAlgorithm::m_rsrpDifferenceThreshold private
RSRP difference threshold.
Definition at line 185 of file lte-ffr-distributed-algorithm.h.
Referenced by Calculate(), and GetTypeId().
m_rsrpMeasId
uint8_t ns3::LteFfrDistributedAlgorithm::m_rsrpMeasId private
RSRP measurement ID.
Definition at line 162 of file lte-ffr-distributed-algorithm.h.
Referenced by DoInitialize(), and DoReportUeMeas().
m_rsrqMeasId
uint8_t ns3::LteFfrDistributedAlgorithm::m_rsrqMeasId private
RSRQ measurement ID.
Definition at line 161 of file lte-ffr-distributed-algorithm.h.
Referenced by DoInitialize(), and DoReportUeMeas().
m_ueMeasures
MeasurementTable_t ns3::LteFfrDistributedAlgorithm::m_ueMeasures private
UE measures.
Definition at line 181 of file lte-ffr-distributed-algorithm.h.
Referenced by Calculate(), and UpdateNeighbourMeasurements().
m_ues
std::map< uint16_t, uint8_t > ns3::LteFfrDistributedAlgorithm::m_ues private
UEs map.
Definition at line 147 of file lte-ffr-distributed-algorithm.h.
Referenced by Calculate(), DoGetTpc(), DoIsDlRbgAvailableForUe(), DoIsUlRbgAvailableForUe(), and DoReportUeMeas().
m_ulEdgeRbgMap
std::vector<bool> ns3::LteFfrDistributedAlgorithm::m_ulEdgeRbgMap private
UL edge RBG map.
Definition at line 137 of file lte-ffr-distributed-algorithm.h.
Referenced by Calculate(), DoInitialize(), and DoIsUlRbgAvailableForUe().
m_ulRbgMap
std::vector<bool> ns3::LteFfrDistributedAlgorithm::m_ulRbgMap private
UL RBG map.
Definition at line 133 of file lte-ffr-distributed-algorithm.h.
Referenced by DoGetAvailableUlRbg(), and InitializeUplinkRbgMaps().
The documentation for this class was generated from the following files:
src/lte/model/lte-ffr-distributed-algorithm.h
src/lte/model/lte-ffr-distributed-algorithm.cc