ns-3: ns3::SimpleFrameCaptureModel Class Reference
ns3::SimpleFrameCaptureModel Class Reference
Wifi Models
A simple threshold-based model for frame capture effect.
#include "simple-frame-capture-model.h"
Public Member Functions
SimpleFrameCaptureModel ()
~SimpleFrameCaptureModel ()
bool CaptureNewFrame (Ptr< Event > currentEvent, Ptr< Event > newEvent) const
This method returns whether the reception should be switched to a new incoming frame.
double GetMargin (void) const
Return the frame capture margin (dB).
void SetMargin (double margin)
Sets the frame capture margin (dB).
Public Member Functions inherited from ns3::FrameCaptureModel
virtual bool IsInCaptureWindow (Time timePreambleDetected) const
This method returns true if the capture window duration has not elapsed yet, false otherwise.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::FrameCaptureModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
double m_margin
margin for determining if a new frame (dB)
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A simple threshold-based model for frame capture effect.
If the new incoming frame arrives while the receiver is receiving the preamble of another frame and the SIR of the new incoming frame is above a fixed margin, then the current frame is dropped and the receiver locks onto the new incoming frame.
Config Paths
ns3::SimpleFrameCaptureModel is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Phy/FrameCaptureModel/$ns3::SimpleFrameCaptureModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/PhyEntities/[i]/FrameCaptureModel/$ns3::SimpleFrameCaptureModel"
Attributes
Margin: Reception is switched if the newly arrived frame has a power higher than this value above the frame currently being received (expressed in dB).
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 5
Flags: construct write read
Attributes defined in parent class ns3::FrameCaptureModel
CaptureWindow: The duration of the capture window.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +16000ns
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 48 bytes (on a 64-bit architecture).
Definition at line 37 of file simple-frame-capture-model.h.
Constructor & Destructor Documentation
SimpleFrameCaptureModel()
ns3::SimpleFrameCaptureModel::SimpleFrameCaptureModel ()
Definition at line 52 of file simple-frame-capture-model.cc.
References NS_LOG_FUNCTION.
~SimpleFrameCaptureModel()
ns3::SimpleFrameCaptureModel::~SimpleFrameCaptureModel ()
Definition at line 57 of file simple-frame-capture-model.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CaptureNewFrame()
bool ns3::SimpleFrameCaptureModel::CaptureNewFrame (Ptr< Event > currentEvent, Ptr< Event > newEvent) const virtual
This method returns whether the reception should be switched to a new incoming frame.
Parameters
currentEvent the event of the current frame
newEvent the event of the new incoming frame
Returns
true if the reception should be switched to a new incoming frame, false otherwise
Implements ns3::FrameCaptureModel.
Definition at line 76 of file simple-frame-capture-model.cc.
References GetMargin(), ns3::FrameCaptureModel::IsInCaptureWindow(), NS_LOG_FUNCTION, and ns3::WToDbm().
GetMargin()
double ns3::SimpleFrameCaptureModel::GetMargin (void) const
Return the frame capture margin (dB).
Returns
the frame capture margin in dB
Definition at line 70 of file simple-frame-capture-model.cc.
References m_margin.
Referenced by CaptureNewFrame(), and GetTypeId().
GetTypeId()
TypeId ns3::SimpleFrameCaptureModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 35 of file simple-frame-capture-model.cc.
References GetMargin(), ns3::MakeDoubleAccessor(), SetMargin(), and ns3::TypeId::SetParent().
SetMargin()
void ns3::SimpleFrameCaptureModel::SetMargin (double margin)
Sets the frame capture margin (dB).
Parameters
margin the frame capture margin in dB
Definition at line 63 of file simple-frame-capture-model.cc.
References m_margin, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
Member Data Documentation
m_margin
double ns3::SimpleFrameCaptureModel::m_margin private
margin for determining if a new frame (dB)
Definition at line 76 of file simple-frame-capture-model.h.
Referenced by GetMargin(), and SetMargin().
The documentation for this class was generated from the following files:
src/wifi/model/simple-frame-capture-model.h
src/wifi/model/simple-frame-capture-model.cc