ns-3: ns3::WifiRadioEnergyModel Class Reference
ns3::WifiRadioEnergyModel Class Reference
Energy Models
A WiFi radio energy model.
#include "wifi-radio-energy-model.h"
Public Types
typedef Callback< void > WifiRadioEnergyDepletionCallback
Callback type for energy depletion handling.
typedef Callback< void > WifiRadioEnergyRechargedCallback
Callback type for energy recharged handling.
Public Types inherited from ns3::DeviceEnergyModel
typedef Callback< void, int > ChangeStateCallback
Callback type for ChangeState function.
Public Member Functions
WifiRadioEnergyModel ()
virtual ~WifiRadioEnergyModel ()
void ChangeState (int newState)
Changes state of the WifiRadioEnergyMode.
double GetCcaBusyCurrentA (void) const
Gets CCA busy current in Amperes.
WifiPhyState GetCurrentState (void) const
double GetIdleCurrentA (void) const
Gets idle current in Amperes.
Time GetMaximumTimeInState (int state) const
WifiRadioEnergyModelPhyListener * GetPhyListener (void)
double GetRxCurrentA (void) const
Gets receive current in Amperes.
double GetSleepCurrentA (void) const
Gets sleep current in Amperes.
double GetSwitchingCurrentA (void) const
Gets switching current in Amperes.
double GetTotalEnergyConsumption (void) const
double GetTxCurrentA (void) const
Gets transmit current in Amperes.
void HandleEnergyChanged (void)
Handles energy changed.
void HandleEnergyDepletion (void)
Handles energy depletion.
void HandleEnergyRecharged (void)
Handles energy recharged.
void SetCcaBusyCurrentA (double ccaBusyCurrentA)
Sets CCA busy current in Amperes.
void SetEnergyDepletionCallback (WifiRadioEnergyDepletionCallback callback)
void SetEnergyRechargedCallback (WifiRadioEnergyRechargedCallback callback)
void SetEnergySource (const Ptr< EnergySource > source)
Sets pointer to EnergySouce installed on node.
void SetIdleCurrentA (double idleCurrentA)
Sets idle current in Amperes.
void SetRxCurrentA (double rxCurrentA)
Sets receive current in Amperes.
void SetSleepCurrentA (double sleepCurrentA)
Sets sleep current in Amperes.
void SetSwitchingCurrentA (double switchingCurrentA)
Sets switching current in Amperes.
void SetTxCurrentA (double txCurrentA)
Sets transmit current in Amperes.
void SetTxCurrentFromModel (double txPowerDbm)
Calls the CalcTxCurrent method of the TX current model to compute the TX current based on such model.
void SetTxCurrentModel (const Ptr< WifiTxCurrentModel > model)
Public Member Functions inherited from ns3::DeviceEnergyModel
DeviceEnergyModel ()
virtual ~DeviceEnergyModel ()
double GetCurrentA (void) const
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::DeviceEnergyModel
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void DoDispose (void)
Destructor implementation.
double DoGetCurrentA (void) const
double GetStateA (int state) const
void SetWifiRadioState (const WifiPhyState state)
Private Attributes
double m_ccaBusyCurrentA
CCA busy current in Amperes.
WifiPhyState m_currentState
current state the radio is in
WifiRadioEnergyDepletionCallback m_energyDepletionCallback
Energy depletion callback.
WifiRadioEnergyRechargedCallback m_energyRechargedCallback
Energy recharged callback.
double m_idleCurrentA
idle current in Amperes
Time m_lastUpdateTime
time stamp of previous energy update
WifiRadioEnergyModelPhyListener * m_listener
WifiPhy listener.
uint8_t m_nPendingChangeState
pending state change
double m_rxCurrentA
receive current in Amperes
double m_sleepCurrentA
sleep current in Amperes
Ptr< EnergySource > m_source
energy source
double m_switchingCurrentA
switching current in Amperes
EventId m_switchToOffEvent
switch to off event
TracedValue< double > m_totalEnergyConsumption
This variable keeps track of the total energy consumed by this model in watts.
double m_txCurrentA
transmit current in Amperes
Ptr< WifiTxCurrentModel > m_txCurrentModel
current model
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A WiFi radio energy model.
Introspection did not find any typical Config paths.
4 states are defined for the radio: TX, RX, IDLE, SLEEP. Default state is IDLE. The different types of transactions that are defined are:
Tx: State goes from IDLE to TX, radio is in TX state for TX_duration, then state goes from TX to IDLE.
Rx: State goes from IDLE to RX, radio is in RX state for RX_duration, then state goes from RX to IDLE.
Go_to_Sleep: State goes from IDLE to SLEEP.
End_of_Sleep: State goes from SLEEP to IDLE. The class keeps track of what state the radio is currently in.
Energy calculation: For each transaction, this model notifies EnergySource object. The EnergySource object will query this model for the total current. Then the EnergySource object uses the total current to calculate energy.
Default values for power consumption are based on measurements reported in:
Daniel Halperin, Ben Greenstein, Anmol Sheth, David Wetherall, "Demystifying 802.11n power consumption", Proceedings of HotPower'10
Power consumption in Watts (single antenna):
(transmit at 0dBm)
Hence, considering the default supply voltage of 3.0 V for the basic energy source, the default current values in Ampere are:
The dependence of the power consumption in transmission mode on the nominal transmit power can also be achieved through a wifi TX current model.
Attributes
IdleCurrentA: The default radio Idle current in Ampere.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0.273
Flags: construct write read
CcaBusyCurrentA: The default radio CCA Busy State current in Ampere.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0.273
Flags: construct write read
TxCurrentA: The radio TX current in Ampere.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0.38
Flags: construct write read
RxCurrentA: The radio RX current in Ampere.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0.313
Flags: construct write read
SwitchingCurrentA: The default radio Channel Switch current in Ampere.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0.273
Flags: construct write read
SleepCurrentA: The radio Sleep current in Ampere.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0.033
Flags: construct write read
TxCurrentModel: A pointer to the attached TX current model.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::WifiTxCurrentModel>
Initial value: 0x0
Flags: construct write read
TraceSources
TotalEnergyConsumption: Total energy consumption of the radio device.
Callback signature: ns3::TracedValueCallback::Double
Size of this type is 200 bytes (on a 64-bit architecture).
Definition at line 213 of file wifi-radio-energy-model.h.
Member Typedef Documentation
WifiRadioEnergyDepletionCallback
typedef Callback<void> ns3::WifiRadioEnergyModel::WifiRadioEnergyDepletionCallback
Callback type for energy depletion handling.
Definition at line 219 of file wifi-radio-energy-model.h.
WifiRadioEnergyRechargedCallback
typedef Callback<void> ns3::WifiRadioEnergyModel::WifiRadioEnergyRechargedCallback
Callback type for energy recharged handling.
Definition at line 224 of file wifi-radio-energy-model.h.
Constructor & Destructor Documentation
WifiRadioEnergyModel()
ns3::WifiRadioEnergyModel::WifiRadioEnergyModel ()
Definition at line 89 of file wifi-radio-energy-model.cc.
References ns3::DeviceEnergyModel::ChangeState(), m_energyDepletionCallback, m_listener, ns3::MakeCallback(), NS_LOG_FUNCTION, ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::Nullify(), ns3::WifiRadioEnergyModelPhyListener::SetChangeStateCallback(), SetTxCurrentFromModel(), and ns3::WifiRadioEnergyModelPhyListener::SetUpdateTxCurrentCallback().
~WifiRadioEnergyModel()
ns3::WifiRadioEnergyModel::~WifiRadioEnergyModel () virtual
Definition at line 104 of file wifi-radio-energy-model.cc.
References m_listener, m_txCurrentModel, and NS_LOG_FUNCTION.
Member Function Documentation
ChangeState()
void ns3::WifiRadioEnergyModel::ChangeState (int newState) virtual
Changes state of the WifiRadioEnergyMode.
Parameters
newState New state the wifi radio is in.
Implements DeviceEnergyModel::ChangeState.
Implements ns3::DeviceEnergyModel.
Definition at line 284 of file wifi-radio-energy-model.cc.
References ns3::EventId::Cancel(), GetMaximumTimeInState(), ns3::Time::GetSeconds(), GetStateA(), ns3::Time::IsPositive(), m_currentState, m_lastUpdateTime, m_nPendingChangeState, m_source, m_switchToOffEvent, m_totalEnergyConsumption, ns3::Simulator::Now(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, OFF, ns3::Simulator::Schedule(), and SetWifiRadioState().
Referenced by HandleEnergyChanged(), SetEnergySource(), and BasicEnergyUpdateTest::StateSwitchTest().
DoDispose()
void ns3::WifiRadioEnergyModel::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 390 of file wifi-radio-energy-model.cc.
References m_energyDepletionCallback, m_source, NS_LOG_FUNCTION, and ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::Nullify().
DoGetCurrentA()
double ns3::WifiRadioEnergyModel::DoGetCurrentA (void) const private virtual
Returns
Current draw of device in Amperes, at current state.
Implements DeviceEnergyModel::GetCurrentA.
Reimplemented from ns3::DeviceEnergyModel.
Definition at line 421 of file wifi-radio-energy-model.cc.
References GetStateA(), and m_currentState.
GetCcaBusyCurrentA()
double ns3::WifiRadioEnergyModel::GetCcaBusyCurrentA (void) const
Gets CCA busy current in Amperes.
Returns
CCA Busy current of the wifi device.
Definition at line 155 of file wifi-radio-energy-model.cc.
References m_ccaBusyCurrentA, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetCurrentState()
WifiPhyState ns3::WifiRadioEnergyModel::GetCurrentState (void) const
Returns
Current state.
Definition at line 225 of file wifi-radio-energy-model.cc.
References m_currentState, and NS_LOG_FUNCTION.
GetIdleCurrentA()
double ns3::WifiRadioEnergyModel::GetIdleCurrentA (void) const
Gets idle current in Amperes.
Returns
idle current of the wifi device.
Definition at line 141 of file wifi-radio-energy-model.cc.
References m_idleCurrentA, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetMaximumTimeInState()
Time ns3::WifiRadioEnergyModel::GetMaximumTimeInState (int state) const
Parameters
state the wifi state
Returns
the time the radio can stay in that state based on the remaining energy.
Definition at line 271 of file wifi-radio-energy-model.cc.
References GetStateA(), m_source, NS_FATAL_ERROR, OFF, and ns3::Seconds().
Referenced by ChangeState(), HandleEnergyChanged(), and SetEnergySource().
GetPhyListener()
WifiRadioEnergyModelPhyListener * ns3::WifiRadioEnergyModel::GetPhyListener (void)
Returns
Pointer to the PHY listener.
Definition at line 379 of file wifi-radio-energy-model.cc.
References m_listener, and NS_LOG_FUNCTION.
GetRxCurrentA()
double ns3::WifiRadioEnergyModel::GetRxCurrentA (void) const
Gets receive current in Amperes.
Returns
receive current of the wifi device.
Definition at line 183 of file wifi-radio-energy-model.cc.
References m_rxCurrentA, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetSleepCurrentA()
double ns3::WifiRadioEnergyModel::GetSleepCurrentA (void) const
Gets sleep current in Amperes.
Returns
sleep current of the wifi device.
Definition at line 211 of file wifi-radio-energy-model.cc.
References m_sleepCurrentA, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetStateA()
double ns3::WifiRadioEnergyModel::GetStateA (int state) const private
Parameters
state the wifi state
Returns
draw of device in Amperes, at given state.
Definition at line 398 of file wifi-radio-energy-model.cc.
References CCA_BUSY, IDLE, m_ccaBusyCurrentA, m_idleCurrentA, m_rxCurrentA, m_sleepCurrentA, m_switchingCurrentA, m_txCurrentA, NS_FATAL_ERROR, OFF, RX, SLEEP, SWITCHING, and TX.
Referenced by ChangeState(), DoGetCurrentA(), GetMaximumTimeInState(), and GetTotalEnergyConsumption().
GetSwitchingCurrentA()
double ns3::WifiRadioEnergyModel::GetSwitchingCurrentA (void) const
Gets switching current in Amperes.
Returns
switching current of the wifi device.
Definition at line 197 of file wifi-radio-energy-model.cc.
References m_switchingCurrentA, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetTotalEnergyConsumption()
double ns3::WifiRadioEnergyModel::GetTotalEnergyConsumption (void) const virtual
Returns
Total energy consumption of the wifi device in watts.
Implements DeviceEnergyModel::GetTotalEnergyConsumption.
Implements ns3::DeviceEnergyModel.
Definition at line 123 of file wifi-radio-energy-model.cc.
References ns3::Time::GetSeconds(), GetStateA(), ns3::Time::IsPositive(), m_currentState, m_lastUpdateTime, m_source, m_totalEnergyConsumption, ns3::Simulator::Now(), NS_ASSERT, and NS_LOG_FUNCTION.
GetTxCurrentA()
double ns3::WifiRadioEnergyModel::GetTxCurrentA (void) const
Gets transmit current in Amperes.
Returns
transmit current of the wifi device.
Definition at line 169 of file wifi-radio-energy-model.cc.
References m_txCurrentA, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::WifiRadioEnergyModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 35 of file wifi-radio-energy-model.cc.
References GetCcaBusyCurrentA(), GetIdleCurrentA(), GetRxCurrentA(), GetSleepCurrentA(), GetSwitchingCurrentA(), GetTxCurrentA(), m_totalEnergyConsumption, m_txCurrentModel, ns3::MakeDoubleAccessor(), ns3::MakePointerAccessor(), ns3::MakeTraceSourceAccessor(), SetCcaBusyCurrentA(), SetIdleCurrentA(), ns3::TypeId::SetParent(), SetRxCurrentA(), SetSleepCurrentA(), SetSwitchingCurrentA(), and SetTxCurrentA().
HandleEnergyChanged()
void ns3::WifiRadioEnergyModel::HandleEnergyChanged (void) virtual
Handles energy changed.
Implements DeviceEnergyModel::HandleEnergyChanged
Implements ns3::DeviceEnergyModel.
Definition at line 366 of file wifi-radio-energy-model.cc.
References ns3::EventId::Cancel(), ChangeState(), GetMaximumTimeInState(), m_currentState, m_switchToOffEvent, NS_LOG_DEBUG, NS_LOG_FUNCTION, OFF, and ns3::Simulator::Schedule().
HandleEnergyDepletion()
void ns3::WifiRadioEnergyModel::HandleEnergyDepletion (void) virtual
Handles energy depletion.
Implements DeviceEnergyModel::HandleEnergyDepletion
Implements ns3::DeviceEnergyModel.
Definition at line 342 of file wifi-radio-energy-model.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_energyDepletionCallback, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
HandleEnergyRecharged()
void ns3::WifiRadioEnergyModel::HandleEnergyRecharged (void) virtual
Handles energy recharged.
Implements DeviceEnergyModel::HandleEnergyRecharged
Implements ns3::DeviceEnergyModel.
Definition at line 354 of file wifi-radio-energy-model.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_energyRechargedCallback, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
SetCcaBusyCurrentA()
void ns3::WifiRadioEnergyModel::SetCcaBusyCurrentA (double ccaBusyCurrentA)
Sets CCA busy current in Amperes.
Parameters
ccaBusyCurrentA the CCA busy current
Definition at line 162 of file wifi-radio-energy-model.cc.
References m_ccaBusyCurrentA, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetEnergyDepletionCallback()
void ns3::WifiRadioEnergyModel::SetEnergyDepletionCallback (WifiRadioEnergyDepletionCallback callback)
Parameters
callback Callback function.
Sets callback for energy depletion handling.
Definition at line 232 of file wifi-radio-energy-model.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_energyDepletionCallback, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
SetEnergyRechargedCallback()
void ns3::WifiRadioEnergyModel::SetEnergyRechargedCallback (WifiRadioEnergyRechargedCallback callback)
Parameters
callback Callback function.
Sets callback for energy recharged handling.
Definition at line 244 of file wifi-radio-energy-model.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_energyRechargedCallback, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
SetEnergySource()
void ns3::WifiRadioEnergyModel::SetEnergySource (const Ptr< EnergySource > source) virtual
Sets pointer to EnergySouce installed on node.
Parameters
source Pointer to EnergySource installed on node.
Implements DeviceEnergyModel::SetEnergySource.
Implements ns3::DeviceEnergyModel.
Definition at line 112 of file wifi-radio-energy-model.cc.
References ns3::EventId::Cancel(), ChangeState(), GetMaximumTimeInState(), m_currentState, m_source, m_switchToOffEvent, NS_ASSERT, NS_LOG_FUNCTION, OFF, and ns3::Simulator::Schedule().
SetIdleCurrentA()
void ns3::WifiRadioEnergyModel::SetIdleCurrentA (double idleCurrentA)
Sets idle current in Amperes.
Parameters
idleCurrentA the idle current
Definition at line 148 of file wifi-radio-energy-model.cc.
References m_idleCurrentA, and NS_LOG_FUNCTION.
Referenced by GetTypeId(), and BatteryLifetimeTest::VariableLoadTest().
SetRxCurrentA()
void ns3::WifiRadioEnergyModel::SetRxCurrentA (double rxCurrentA)
Sets receive current in Amperes.
Parameters
rxCurrentA the receive current
Definition at line 190 of file wifi-radio-energy-model.cc.
References m_rxCurrentA, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetSleepCurrentA()
void ns3::WifiRadioEnergyModel::SetSleepCurrentA (double sleepCurrentA)
Sets sleep current in Amperes.
Parameters
sleepCurrentA the sleep current
Definition at line 218 of file wifi-radio-energy-model.cc.
References m_sleepCurrentA, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetSwitchingCurrentA()
void ns3::WifiRadioEnergyModel::SetSwitchingCurrentA (double switchingCurrentA)
Sets switching current in Amperes.
Parameters
switchingCurrentA the switching current
Definition at line 204 of file wifi-radio-energy-model.cc.
References m_switchingCurrentA, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetTxCurrentA()
void ns3::WifiRadioEnergyModel::SetTxCurrentA (double txCurrentA)
Sets transmit current in Amperes.
Parameters
txCurrentA the transmit current
Definition at line 176 of file wifi-radio-energy-model.cc.
References m_txCurrentA, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetTxCurrentFromModel()
void ns3::WifiRadioEnergyModel::SetTxCurrentFromModel (double txPowerDbm)
Calls the CalcTxCurrent method of the TX current model to compute the TX current based on such model.
Parameters
txPowerDbm the nominal TX power in dBm
Definition at line 262 of file wifi-radio-energy-model.cc.
References m_txCurrentA, and m_txCurrentModel.
Referenced by WifiRadioEnergyModel().
SetTxCurrentModel()
void ns3::WifiRadioEnergyModel::SetTxCurrentModel (const Ptr< WifiTxCurrentModel > model)
Parameters
model the model used to compute the wifi TX current.
Definition at line 256 of file wifi-radio-energy-model.cc.
References m_txCurrentModel.
SetWifiRadioState()
void ns3::WifiRadioEnergyModel::SetWifiRadioState (const WifiPhyState state) private
Parameters
state New state the radio device is currently in.
Sets current state. This function is private so that only the energy model can change its own state.
Definition at line 427 of file wifi-radio-energy-model.cc.
References CCA_BUSY, IDLE, m_currentState, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, OFF, RX, SLEEP, SWITCHING, and TX.
Referenced by ChangeState().
Member Data Documentation
m_ccaBusyCurrentA
double ns3::WifiRadioEnergyModel::m_ccaBusyCurrentA private
CCA busy current in Amperes.
Definition at line 429 of file wifi-radio-energy-model.h.
Referenced by GetCcaBusyCurrentA(), GetStateA(), and SetCcaBusyCurrentA().
m_currentState
WifiPhyState ns3::WifiRadioEnergyModel::m_currentState private
current state the radio is in
Definition at line 438 of file wifi-radio-energy-model.h.
Referenced by ChangeState(), DoGetCurrentA(), GetCurrentState(), GetTotalEnergyConsumption(), HandleEnergyChanged(), SetEnergySource(), and SetWifiRadioState().
m_energyDepletionCallback
WifiRadioEnergyDepletionCallback ns3::WifiRadioEnergyModel::m_energyDepletionCallback private
Energy depletion callback.
Definition at line 444 of file wifi-radio-energy-model.h.
Referenced by WifiRadioEnergyModel(), DoDispose(), HandleEnergyDepletion(), and SetEnergyDepletionCallback().
m_energyRechargedCallback
WifiRadioEnergyRechargedCallback ns3::WifiRadioEnergyModel::m_energyRechargedCallback private
Energy recharged callback.
Definition at line 447 of file wifi-radio-energy-model.h.
Referenced by HandleEnergyRecharged(), and SetEnergyRechargedCallback().
m_idleCurrentA
double ns3::WifiRadioEnergyModel::m_idleCurrentA private
idle current in Amperes
Definition at line 428 of file wifi-radio-energy-model.h.
Referenced by GetIdleCurrentA(), GetStateA(), and SetIdleCurrentA().
m_lastUpdateTime
Time ns3::WifiRadioEnergyModel::m_lastUpdateTime private
time stamp of previous energy update
Definition at line 439 of file wifi-radio-energy-model.h.
Referenced by ChangeState(), and GetTotalEnergyConsumption().
m_listener
WifiRadioEnergyModelPhyListener* ns3::WifiRadioEnergyModel::m_listener private
WifiPhy listener.
Definition at line 450 of file wifi-radio-energy-model.h.
Referenced by WifiRadioEnergyModel(), ~WifiRadioEnergyModel(), and GetPhyListener().
m_nPendingChangeState
uint8_t ns3::WifiRadioEnergyModel::m_nPendingChangeState private
pending state change
Definition at line 441 of file wifi-radio-energy-model.h.
Referenced by ChangeState().
m_rxCurrentA
double ns3::WifiRadioEnergyModel::m_rxCurrentA private
receive current in Amperes
Definition at line 427 of file wifi-radio-energy-model.h.
Referenced by GetRxCurrentA(), GetStateA(), and SetRxCurrentA().
m_sleepCurrentA
double ns3::WifiRadioEnergyModel::m_sleepCurrentA private
sleep current in Amperes
Definition at line 431 of file wifi-radio-energy-model.h.
Referenced by GetSleepCurrentA(), GetStateA(), and SetSleepCurrentA().
m_source
Ptr<EnergySource> ns3::WifiRadioEnergyModel::m_source private
energy source
Definition at line 423 of file wifi-radio-energy-model.h.
Referenced by ChangeState(), DoDispose(), GetMaximumTimeInState(), GetTotalEnergyConsumption(), and SetEnergySource().
m_switchingCurrentA
double ns3::WifiRadioEnergyModel::m_switchingCurrentA private
switching current in Amperes
Definition at line 430 of file wifi-radio-energy-model.h.
Referenced by GetStateA(), GetSwitchingCurrentA(), and SetSwitchingCurrentA().
m_switchToOffEvent
EventId ns3::WifiRadioEnergyModel::m_switchToOffEvent private
switch to off event
Definition at line 452 of file wifi-radio-energy-model.h.
Referenced by ChangeState(), HandleEnergyChanged(), and SetEnergySource().
m_totalEnergyConsumption
TracedValue<double> ns3::WifiRadioEnergyModel::m_totalEnergyConsumption private
This variable keeps track of the total energy consumed by this model in watts.
Definition at line 435 of file wifi-radio-energy-model.h.
Referenced by ChangeState(), GetTotalEnergyConsumption(), and GetTypeId().
m_txCurrentA
double ns3::WifiRadioEnergyModel::m_txCurrentA private
transmit current in Amperes
Definition at line 426 of file wifi-radio-energy-model.h.
Referenced by GetStateA(), GetTxCurrentA(), SetTxCurrentA(), and SetTxCurrentFromModel().
m_txCurrentModel
Ptr<WifiTxCurrentModel> ns3::WifiRadioEnergyModel::m_txCurrentModel private
current model
Definition at line 432 of file wifi-radio-energy-model.h.
Referenced by ~WifiRadioEnergyModel(), GetTypeId(), SetTxCurrentFromModel(), and SetTxCurrentModel().
The documentation for this class was generated from the following files:
src/wifi/model/wifi-radio-energy-model.h
src/wifi/model/wifi-radio-energy-model.cc