ns-3: ns3::UintegerValue Class Reference
ns3::UintegerValue Class Reference
Uinteger Attribute
Hold an unsigned integer type.
#include "uinteger.h"
Public Member Functions
UintegerValue ()
UintegerValue (const uint64_t &value)
Copy constructor.
virtual Ptr< AttributeValue > Copy (void) const
virtual bool DeserializeFromString (std::string value, Ptr< const AttributeChecker > checker)
uint64_t Get (void) const
template<typename T >
bool GetAccessor (T &value) const
Access the Uinteger value as type T.
virtual std::string SerializeToString (Ptr< const AttributeChecker > checker) const
void Set (const uint64_t &value)
Set the value.
Public Member Functions inherited from ns3::AttributeValue
AttributeValue ()
virtual ~AttributeValue ()
Public Member Functions inherited from ns3::SimpleRefCount< AttributeValue >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
uint64_t m_value
The stored Uinteger instance.
Detailed Description
Hold an unsigned integer type.
AttributeValue implementation for Uinteger.
This class can be used to hold variables of unsigned integer type such as uint8_t, uint16_t, uint32_t, uint64_t, or, unsigned int, etc.
See also
AttributeValue
Definition at line 44 of file uinteger.h.
Constructor & Destructor Documentation
UintegerValue() [1/2]
ns3::UintegerValue::UintegerValue ()
Definition at line 35 of file uinteger.cc.
UintegerValue() [2/2]
Uinteger ns3::UintegerValue::UintegerValue (const uint64_t & value)
Copy constructor.
Parameters
[in] value The Uinteger value to copy.
Definition at line 35 of file uinteger.cc.
Member Function Documentation
Copy()
Ptr< AttributeValue > ns3::UintegerValue::Copy (void) const virtual
Returns
a deep copy of this class, wrapped into an Attribute object.
Implements ns3::AttributeValue.
Definition at line 35 of file uinteger.cc.
DeserializeFromString()
bool ns3::UintegerValue::DeserializeFromString (std::string value, Ptr< const AttributeChecker > checker) virtual
Parameters
[in] value A string representation of the value
[in] checker A pointer to the checker associated to the attribute.
Returns
true if the input string was correctly-formatted and could be successfully deserialized, false otherwise.
Upon return of this function, this AttributeValue instance contains the deserialized value. In most cases, this method will not make any use of the checker argument. However, in a very limited set of cases, the checker argument is needed to perform proper serialization. A nice example of code which needs it is the EnumValue::SerializeToString code.
Implements ns3::AttributeValue.
Definition at line 35 of file uinteger.cc.
Get()
uint64_t ns3::UintegerValue::Get (void) const
Returns
The Uinteger value.
Definition at line 35 of file uinteger.cc.
Referenced by TcpVenoTest::AdditiveIncrease(), TcpIllinoisTest::CalculateAlpha(), TcpYeahDecrementTest::CalculateSsThresh(), ns3::tests::GlobalValueTestCase::DoRun(), TcpScalableIncrementTest::DoRun(), TcpBicDecrementTest::ExecuteTest(), TcpLedbatDecrementTest::ExecuteTest(), ns3::WifiPhy::GetAddressedPsduInPpdu(), ns3::WifiRemoteStationManager::GetDataTxVector(), ns3::ApWifiMac::GetHeOperation(), ns3::MpduAggregator::GetMaxAmpduSize(), ns3::MsduAggregator::GetMaxAmsduSize(), ns3::RngSeedManager::GetRun(), ns3::RngSeedManager::GetSeed(), TcpVegasTest::IncreaseWindow(), TcpYeahIncrementTest::IncreaseWindow(), ns3::internal::MakeUintegerChecker(), TcpVenoTest::MultiplicativeDecrease(), TcpIllinoisTest::RecalcParam(), ns3::ConstantObssPdAlgorithm::ReceiveHeSig(), ns3::ObssPdAlgorithm::ResetPhy(), VanetRoutingExperiment::SetConfigFromGlobals(), and TcpBicIncrementTest::Update().
GetAccessor()
template<typename T > bool ns3::UintegerValue::GetAccessor (T & value) const inline
Access the Uinteger value as type T.
Template Parameters
T [explicit] The type to cast to.
Parameters
[out] value The Uinteger value, as type T.
Returns
true.
Definition at line 44 of file uinteger.h.
SerializeToString()
std::string ns3::UintegerValue::SerializeToString (Ptr< const AttributeChecker > checker) const virtual
Parameters
[in] checker The checker associated to the attribute
Returns
A string representation of this value.
In most cases, this method will not make any use of the checker argument. However, in a very limited set of cases, the checker argument is needed to perform proper serialization. A nice example of code which needs it is the EnumValue::SerializeToString code.
Implements ns3::AttributeValue.
Definition at line 35 of file uinteger.cc.
Set()
void ns3::UintegerValue::Set (const uint64_t & value)
Set the value.
Parameters
[in] value The value to adopt.
Definition at line 35 of file uinteger.cc.
Member Data Documentation
m_value
uint64_t ns3::UintegerValue::m_value private
The stored Uinteger instance.
Definition at line 44 of file uinteger.h.
The documentation for this class was generated from the following files:
src/core/model/uinteger.h
src/core/model/uinteger.cc
doc/introspected-doxygen.h