ns-3: ns3::flame::FlameProtocolMac Class Reference
ns3::flame::FlameProtocolMac Class Reference
Mesh Device » FLAME
Interface MAC plugin for FLAME routing protocol.
#include "flame-protocol-mac.h"
Classes
struct Statistics
Statistics structure.
Public Member Functions
FlameProtocolMac (Ptr< FlameProtocol > protocol)
Constructor.
~FlameProtocolMac ()
int64_t AssignStreams (int64_t stream)
AssignStreams is empty, because this model doesn't use random variables.
uint16_t GetChannelId () const
Get channel ID function.
bool Receive (Ptr< Packet > packet, const WifiMacHeader &header)
Receive and process a packet; packets are given a FlameTag packet tag.
void Report (std::ostream &os) const
Report statistics.
void ResetStats ()
Reset statistics function.
void SetParent (Ptr< MeshWifiInterfaceMac > parent)
Set parent of this instance.
void UpdateBeacon (MeshWifiBeacon &beacon) const
Update beacon is empty, because FLAME does not know anything about beacons.
bool UpdateOutcomingFrame (Ptr< Packet > packet, WifiMacHeader &header, Mac48Address from, Mac48Address to)
Process an outgoing frame.
Public Member Functions inherited from ns3::MeshWifiInterfaceMacPlugin
virtual ~MeshWifiInterfaceMacPlugin ()
This is for subclasses.
Public Member Functions inherited from ns3::SimpleRefCount< MeshWifiInterfaceMacPlugin >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
Ptr< MeshWifiInterfaceMac > m_parent
parent
Ptr< FlameProtocol > m_protocol
protocol
Statistics m_stats
statistics
Detailed Description
Interface MAC plugin for FLAME routing protocol.
Definition at line 34 of file flame-protocol-mac.h.
Constructor & Destructor Documentation
FlameProtocolMac()
ns3::flame::FlameProtocolMac::FlameProtocolMac (Ptr< FlameProtocol > protocol)
Constructor.
Parameters
protocol flame protocol object
Definition at line 32 of file flame-protocol-mac.cc.
~FlameProtocolMac()
ns3::flame::FlameProtocolMac::~FlameProtocolMac ()
Definition at line 36 of file flame-protocol-mac.cc.
References m_parent, and m_protocol.
Member Function Documentation
AssignStreams()
int64_t ns3::flame::FlameProtocolMac::AssignStreams (int64_t stream) inline virtual
AssignStreams is empty, because this model doesn't use random variables.
Parameters
stream
Returns
0 (no streams used)
Implements ns3::MeshWifiInterfaceMacPlugin.
Definition at line 78 of file flame-protocol-mac.h.
GetChannelId()
uint16_t ns3::flame::FlameProtocolMac::GetChannelId () const
Get channel ID function.
Returns
the channel
Definition at line 99 of file flame-protocol-mac.cc.
References m_parent.
Receive()
bool ns3::flame::FlameProtocolMac::Receive (Ptr< Packet > packet, const WifiMacHeader & header) virtual
Receive and process a packet; packets are given a FlameTag packet tag.
Parameters
packet the packet received
header the header
Returns
true if successful
Implements ns3::MeshWifiInterfaceMacPlugin.
Definition at line 48 of file flame-protocol-mac.cc.
References ns3::Packet::AddPacketTag(), ns3::WifiMacHeader::GetAddr1(), ns3::WifiMacHeader::GetAddr2(), ns3::Mac48Address::GetBroadcast(), ns3::Packet::GetSize(), ns3::WifiMacHeader::IsData(), m_stats, NS_FATAL_ERROR, ns3::Packet::PeekPacketTag(), ns3::flame::FlameTag::receiver, ns3::flame::FlameProtocolMac::Statistics::rxBroadcast, ns3::flame::FlameProtocolMac::Statistics::rxBytes, ns3::flame::FlameProtocolMac::Statistics::rxUnicast, and ns3::flame::FlameTag::transmitter.
Report()
void ns3::flame::FlameProtocolMac::Report (std::ostream & os) const
Report statistics.
Parameters
os the output stream
Definition at line 119 of file flame-protocol-mac.cc.
References m_parent, m_stats, and ns3::flame::FlameProtocolMac::Statistics::Print().
ResetStats()
void ns3::flame::FlameProtocolMac::ResetStats ()
Reset statistics function.
Definition at line 128 of file flame-protocol-mac.cc.
References m_stats.
SetParent()
void ns3::flame::FlameProtocolMac::SetParent (Ptr< MeshWifiInterfaceMac > parent) virtual
Set parent of this instance.
Parameters
parent pointer to the parent MeshWifiInterfaceMac
Implements ns3::MeshWifiInterfaceMacPlugin.
Definition at line 42 of file flame-protocol-mac.cc.
References m_parent.
UpdateBeacon()
void ns3::flame::FlameProtocolMac::UpdateBeacon (MeshWifiBeacon & beacon) const inline virtual
Update beacon is empty, because FLAME does not know anything about beacons.
Parameters
beacon the beacon
Implements ns3::MeshWifiInterfaceMacPlugin.
Definition at line 72 of file flame-protocol-mac.h.
UpdateOutcomingFrame()
bool ns3::flame::FlameProtocolMac::UpdateOutcomingFrame (Ptr< Packet > packet, WifiMacHeader & header, Mac48Address from, Mac48Address to) virtual
Process an outgoing frame.
Remove the FlameTag and increment stats counters.
Parameters
packet the packet received
header the header
from the MAC address of the sender
to the MAC address of the receiver
Returns
true if successful
Implements ns3::MeshWifiInterfaceMacPlugin.
Definition at line 74 of file flame-protocol-mac.cc.
References ns3::Mac48Address::GetBroadcast(), ns3::Packet::GetSize(), ns3::WifiMacHeader::IsData(), m_stats, NS_FATAL_ERROR, ns3::flame::FlameTag::receiver, ns3::Packet::RemovePacketTag(), ns3::WifiMacHeader::SetAddr1(), ns3::flame::FlameProtocolMac::Statistics::txBroadcast, ns3::flame::FlameProtocolMac::Statistics::txBytes, and ns3::flame::FlameProtocolMac::Statistics::txUnicast.
Member Data Documentation
m_parent
Ptr<MeshWifiInterfaceMac> ns3::flame::FlameProtocolMac::m_parent private
parent
Definition at line 97 of file flame-protocol-mac.h.
Referenced by ~FlameProtocolMac(), GetChannelId(), Report(), and SetParent().
m_protocol
Ptr<FlameProtocol> ns3::flame::FlameProtocolMac::m_protocol private
protocol
Definition at line 96 of file flame-protocol-mac.h.
Referenced by ~FlameProtocolMac().
m_stats
Statistics ns3::flame::FlameProtocolMac::m_stats private
statistics
Definition at line 116 of file flame-protocol-mac.h.
Referenced by Receive(), Report(), ResetStats(), and UpdateOutcomingFrame().
The documentation for this class was generated from the following files:
src/mesh/model/flame/flame-protocol-mac.h
src/mesh/model/flame/flame-protocol-mac.cc