ns-3: ns3::DhcpServer Class Reference
ns3::DhcpServer Class Reference
Internet Applications » DHCPv4 Client and Server
Implements the functionality of a DHCP server.
#include "dhcp-server.h"
Public Member Functions
DhcpServer ()
virtual ~DhcpServer ()
void AddStaticDhcpEntry (Address chaddr, Ipv4Address addr)
Add a static entry to the pool.
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Application
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
typedef std::list< Ipv4Address > AvailableAddress
Available address container - IP addr.
typedef std::list< Address > ExpiredAddress
Expired address container - chaddr.
typedef std::list< Address >::const_iterator ExpiredAddressCIter
Expired address const iterator - chaddr.
typedef std::list< Address >::iterator ExpiredAddressIter
Expired address iterator - chaddr.
typedef std::map< Address, std::pair< Ipv4Address, uint32_t > > LeasedAddress
Leased address container - chaddr + IP addr / lease time.
typedef std::map< Address, std::pair< Ipv4Address, uint32_t > >::const_iterator LeasedAddressCIter
Leased address const iterator - chaddr + IP addr / lease time.
typedef std::map< Address, std::pair< Ipv4Address, uint32_t > >::iterator LeasedAddressIter
Leased address iterator - chaddr + IP addr / lease time.
Private Member Functions
void NetHandler (Ptr< Socket > socket)
Handles incoming packets from the network.
void SendAck (Ptr< NetDevice > iDev, DhcpHeader header, InetSocketAddress from)
Sends DHCP ACK (or NACK) after receiving Request.
void SendOffer (Ptr< NetDevice > iDev, DhcpHeader header, InetSocketAddress from)
Sends DHCP offer after receiving DHCP Discover.
virtual void StartApplication (void)
Starts the DHCP Server application.
virtual void StopApplication (void)
Stops the DHCP client application.
void TimerHandler (void)
Modifies the remaining lease time of addresses.
Private Attributes
AvailableAddress m_availableAddresses
Available addresses to be used (IP addresses)
ExpiredAddress m_expiredAddresses
Expired addresses to be reused (chaddr of the clients)
EventId m_expiredEvent
The Event to trigger TimerHandler.
Ipv4Address m_gateway
The gateway address.
Time m_lease
The granted lease time for an address.
LeasedAddress m_leasedAddresses
Leased address and their status (cache memory)
Ipv4Address m_maxAddress
The last address in the address pool.
Ipv4Address m_minAddress
The first address in the address pool.
Ipv4Address m_poolAddress
The network address available to the server.
Ipv4Mask m_poolMask
The network mask of the pool.
Time m_rebind
The rebinding time for an address.
Time m_renew
The renewal time for an address.
Ptr< Socket > m_socket
The socket bound to port 67.
Static Private Attributes
static const int PORT = 67
Port number of DHCP server.
Additional Inherited Members
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implements the functionality of a DHCP server.
Config Paths
ns3::DhcpServer is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/ApplicationList/[i]/$ns3::DhcpServer"
Attributes
LeaseTime: Lease for which address will be leased.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +3e+10ns
Flags: construct write read
RenewTime: Time after which client should renew.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1.5e+10ns
Flags: construct write read
RebindTime: Time after which client should rebind.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +2.5e+10ns
Flags: construct write read
PoolAddresses: Pool of addresses to provide on request.
Set with class: Ipv4AddressValue
Underlying type: Ipv4Address
Initial value: 102.102.102.102
Flags: construct write read
FirstAddress: The First valid address that can be given.
Set with class: Ipv4AddressValue
Underlying type: Ipv4Address
Initial value: 102.102.102.102
Flags: construct write read
LastAddress: The Last valid address that can be given.
Set with class: Ipv4AddressValue
Underlying type: Ipv4Address
Initial value: 102.102.102.102
Flags: construct write read
PoolMask: Mask of the pool of addresses.
Set with class: Ipv4MaskValue
Underlying type: Ipv4Mask
Initial value: 102.102.102.102
Flags: construct write read
Gateway: Address of default gateway
Set with class: Ipv4AddressValue
Underlying type: Ipv4Address
Initial value: 102.102.102.102
Flags: construct write read
Attributes defined in parent class ns3::Application
StartTime: Time at which the application will start
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
StopTime: Time at which the application will stop
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 272 bytes (on a 64-bit architecture).
Definition at line 44 of file dhcp-server.h.
Member Typedef Documentation
AvailableAddress
typedef std::list<Ipv4Address> ns3::DhcpServer::AvailableAddress private
Available address container - IP addr.
Definition at line 130 of file dhcp-server.h.
ExpiredAddress
typedef std::list<Address> ns3::DhcpServer::ExpiredAddress private
Expired address container - chaddr.
Definition at line 123 of file dhcp-server.h.
ExpiredAddressCIter
typedef std::list<Address>::const_iterator ns3::DhcpServer::ExpiredAddressCIter private
Expired address const iterator - chaddr.
Definition at line 127 of file dhcp-server.h.
ExpiredAddressIter
typedef std::list<Address>::iterator ns3::DhcpServer::ExpiredAddressIter private
Expired address iterator - chaddr.
Definition at line 125 of file dhcp-server.h.
LeasedAddress
typedef std::map<Address, std::pair<Ipv4Address, uint32_t> > ns3::DhcpServer::LeasedAddress private
Leased address container - chaddr + IP addr / lease time.
Definition at line 116 of file dhcp-server.h.
LeasedAddressCIter
typedef std::map<Address, std::pair<Ipv4Address, uint32_t> >::const_iterator ns3::DhcpServer::LeasedAddressCIter private
Leased address const iterator - chaddr + IP addr / lease time.
Definition at line 120 of file dhcp-server.h.
LeasedAddressIter
typedef std::map<Address, std::pair<Ipv4Address, uint32_t> >::iterator ns3::DhcpServer::LeasedAddressIter private
Leased address iterator - chaddr + IP addr / lease time.
Definition at line 118 of file dhcp-server.h.
Constructor & Destructor Documentation
DhcpServer()
ns3::DhcpServer::DhcpServer ()
Definition at line 93 of file dhcp-server.cc.
References NS_LOG_FUNCTION.
~DhcpServer()
ns3::DhcpServer::~DhcpServer () virtual
Definition at line 98 of file dhcp-server.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddStaticDhcpEntry()
void ns3::DhcpServer::AddStaticDhcpEntry (Address chaddr, Ipv4Address addr)
Add a static entry to the pool.
Parameters
chaddr The client chaddr.
addr The address to handle to the client.
Definition at line 386 of file dhcp-server.cc.
References ns3::Address::CopyFrom(), ns3::Address::CopyTo(), ns3::Ipv4Address::Get(), m_availableAddresses, m_leasedAddresses, m_maxAddress, m_minAddress, ns3::Address::MAX_SIZE, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
DoDispose()
void ns3::DhcpServer::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Application.
Definition at line 104 of file dhcp-server.cc.
References ns3::Application::DoDispose(), and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::DhcpServer::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 43 of file dhcp-server.cc.
References m_gateway, m_lease, m_maxAddress, m_minAddress, m_poolAddress, m_poolMask, m_rebind, m_renew, ns3::MakeIpv4AddressAccessor(), ns3::MakeIpv4AddressChecker(), ns3::MakeIpv4MaskAccessor(), ns3::MakeIpv4MaskChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::Seconds(), and ns3::TypeId::SetParent().
Referenced by ns3::DhcpHelper::DhcpHelper().
NetHandler()
void ns3::DhcpServer::NetHandler (Ptr< Socket > socket) private
Handles incoming packets from the network.
Parameters
socket Socket bound to port 67 of the DHCP server
Definition at line 209 of file dhcp-server.cc.
References ns3::InetSocketAddress::ConvertFrom(), ns3::DhcpHeader::DHCPDISCOVER, ns3::DhcpHeader::DHCPREQ, ns3::Ipv4Address::Get(), ns3::Node::GetDevice(), ns3::Application::GetNode(), ns3::Ipv4PacketInfoTag::GetRecvIf(), ns3::DhcpHeader::GetReq(), ns3::DhcpHeader::GetType(), m_maxAddress, m_minAddress, m_socket, NS_ABORT_MSG, NS_LOG_FUNCTION, ns3::Socket::RecvFrom(), ns3::Packet::RemoveHeader(), ns3::Packet::RemovePacketTag(), SendAck(), and SendOffer().
Referenced by StartApplication().
SendAck()
void ns3::DhcpServer::SendAck (Ptr< NetDevice > iDev, DhcpHeader header, InetSocketAddress from) private
Sends DHCP ACK (or NACK) after receiving Request.
Parameters
iDev incoming NetDevice
header DHCP header of the received message
from Address of the DHCP client
Definition at line 326 of file dhcp-server.cc.
References ns3::Packet::AddHeader(), first::address, ns3::DhcpHeader::DHCPACK, ns3::DhcpHeader::DHCPNACK, ns3::DhcpHeader::GetChaddr(), ns3::InetSocketAddress::GetIpv4(), ns3::InetSocketAddress::GetPort(), ns3::DhcpHeader::GetReq(), ns3::Time::GetSeconds(), ns3::DhcpHeader::GetTran(), m_lease, m_leasedAddresses, m_socket, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::DhcpHeader::ResetOpt(), ns3::Socket::SendTo(), ns3::DhcpHeader::SetChaddr(), ns3::DhcpHeader::SetTime(), ns3::DhcpHeader::SetTran(), ns3::DhcpHeader::SetType(), and ns3::DhcpHeader::SetYiaddr().
Referenced by NetHandler().
SendOffer()
void ns3::DhcpServer::SendOffer (Ptr< NetDevice > iDev, DhcpHeader header, InetSocketAddress from) private
Sends DHCP offer after receiving DHCP Discover.
Parameters
iDev incoming NetDevice
header DHCP header of the received message
from Address of the DHCP client
Definition at line 242 of file dhcp-server.cc.
References ns3::Packet::AddHeader(), ns3::DhcpHeader::DHCPOFFER, ns3::Ipv4Mask::Get(), ns3::DhcpHeader::GetChaddr(), ns3::InetSocketAddress::GetIpv4(), ns3::Application::GetNode(), ns3::Object::GetObject(), ns3::InetSocketAddress::GetPort(), ns3::Time::GetSeconds(), ns3::DhcpHeader::GetTran(), m_availableAddresses, m_expiredAddresses, m_gateway, m_lease, m_leasedAddresses, m_poolMask, m_rebind, m_renew, m_socket, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, ns3::DhcpHeader::ResetOpt(), ns3::Socket::SendTo(), ns3::DhcpHeader::SetChaddr(), ns3::DhcpHeader::SetDhcps(), ns3::DhcpHeader::SetLease(), ns3::DhcpHeader::SetMask(), ns3::DhcpHeader::SetRebind(), ns3::DhcpHeader::SetRenew(), ns3::DhcpHeader::SetRouter(), ns3::DhcpHeader::SetTime(), ns3::DhcpHeader::SetTran(), ns3::DhcpHeader::SetType(), and ns3::DhcpHeader::SetYiaddr().
Referenced by NetHandler().
StartApplication()
void ns3::DhcpServer::StartApplication (void) private virtual
Starts the DHCP Server application.
Reimplemented from ns3::Application.
Definition at line 110 of file dhcp-server.cc.
References ns3::Socket::Bind(), ns3::Socket::BindToNetDevice(), ns3::Socket::CreateSocket(), ns3::Ipv4Address::Get(), ns3::Ipv4Address::GetAny(), ns3::Application::GetNode(), ns3::Object::GetObject(), ns3::TypeId::LookupByName(), m_availableAddresses, m_expiredEvent, m_leasedAddresses, m_maxAddress, m_minAddress, m_poolAddress, m_poolMask, m_socket, ns3::MakeCallback(), NetHandler(), NS_ABORT_MSG, NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, PORT, ns3::Simulator::Schedule(), ns3::Seconds(), ns3::Socket::SetAllowBroadcast(), ns3::Socket::SetRecvCallback(), ns3::Socket::SetRecvPktInfo(), and TimerHandler().
StopApplication()
void ns3::DhcpServer::StopApplication (void) private virtual
Stops the DHCP client application.
Reimplemented from ns3::Application.
Definition at line 171 of file dhcp-server.cc.
References ns3::EventId::Cancel(), m_expiredEvent, m_leasedAddresses, m_socket, ns3::MakeNullCallback(), NS_LOG_FUNCTION, and ns3::Socket::SetRecvCallback().
TimerHandler()
void ns3::DhcpServer::TimerHandler (void) private
Modifies the remaining lease time of addresses.
Definition at line 184 of file dhcp-server.cc.
References m_expiredAddresses, m_expiredEvent, m_leasedAddresses, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::Simulator::Schedule(), and ns3::Seconds().
Referenced by StartApplication().
Member Data Documentation
m_availableAddresses
AvailableAddress ns3::DhcpServer::m_availableAddresses private
Available addresses to be used (IP addresses)
Definition at line 134 of file dhcp-server.h.
Referenced by AddStaticDhcpEntry(), SendOffer(), and StartApplication().
m_expiredAddresses
ExpiredAddress ns3::DhcpServer::m_expiredAddresses private
Expired addresses to be reused (chaddr of the clients)
Definition at line 133 of file dhcp-server.h.
Referenced by SendOffer(), and TimerHandler().
m_expiredEvent
EventId ns3::DhcpServer::m_expiredEvent private
The Event to trigger TimerHandler.
Definition at line 138 of file dhcp-server.h.
Referenced by StartApplication(), StopApplication(), and TimerHandler().
m_gateway
Ipv4Address ns3::DhcpServer::m_gateway private
The gateway address.
Definition at line 113 of file dhcp-server.h.
Referenced by GetTypeId(), and SendOffer().
m_lease
Time ns3::DhcpServer::m_lease private
The granted lease time for an address.
Definition at line 135 of file dhcp-server.h.
Referenced by GetTypeId(), SendAck(), and SendOffer().
m_leasedAddresses
LeasedAddress ns3::DhcpServer::m_leasedAddresses private
Leased address and their status (cache memory)
Definition at line 132 of file dhcp-server.h.
Referenced by AddStaticDhcpEntry(), SendAck(), SendOffer(), StartApplication(), StopApplication(), and TimerHandler().
m_maxAddress
Ipv4Address ns3::DhcpServer::m_maxAddress private
The last address in the address pool.
Definition at line 111 of file dhcp-server.h.
Referenced by AddStaticDhcpEntry(), GetTypeId(), NetHandler(), and StartApplication().
m_minAddress
Ipv4Address ns3::DhcpServer::m_minAddress private
The first address in the address pool.
Definition at line 110 of file dhcp-server.h.
Referenced by AddStaticDhcpEntry(), GetTypeId(), NetHandler(), and StartApplication().
m_poolAddress
Ipv4Address ns3::DhcpServer::m_poolAddress private
The network address available to the server.
Definition at line 109 of file dhcp-server.h.
Referenced by GetTypeId(), and StartApplication().
m_poolMask
Ipv4Mask ns3::DhcpServer::m_poolMask private
The network mask of the pool.
Definition at line 112 of file dhcp-server.h.
Referenced by GetTypeId(), SendOffer(), and StartApplication().
m_rebind
Time ns3::DhcpServer::m_rebind private
The rebinding time for an address.
Definition at line 137 of file dhcp-server.h.
Referenced by GetTypeId(), and SendOffer().
m_renew
Time ns3::DhcpServer::m_renew private
The renewal time for an address.
Definition at line 136 of file dhcp-server.h.
Referenced by GetTypeId(), and SendOffer().
m_socket
Ptr<Socket> ns3::DhcpServer::m_socket private
The socket bound to port 67.
Definition at line 108 of file dhcp-server.h.
Referenced by NetHandler(), SendAck(), SendOffer(), StartApplication(), and StopApplication().
PORT
const int ns3::DhcpServer::PORT = 67 static private
Port number of DHCP server.
Definition at line 69 of file dhcp-server.h.
Referenced by StartApplication().
The documentation for this class was generated from the following files:
src/internet-apps/model/dhcp-server.h
src/internet-apps/model/dhcp-server.cc