ns-3: ns3::Icmpv6Header Class Reference
ns3::Icmpv6Header Class Reference
Internet » IPv6 classes and sub-modules » ICMPv6 protocol and associated headers.
ICMPv6 header.
#include "icmpv6-header.h"
Public Types
enum ErrorDestinationUnreachable_e {
ICMPV6_NO_ROUTE = 0 , ICMPV6_ADM_PROHIBITED , ICMPV6_NOT_NEIGHBOUR , ICMPV6_ADDR_UNREACHABLE ,
ICMPV6_PORT_UNREACHABLE
}
ICMPv6 error code : Destination Unreachable.
enum ErrorParameterError_e { ICMPV6_MALFORMED_HEADER = 0 , ICMPV6_UNKNOWN_NEXT_HEADER , ICMPV6_UNKNOWN_OPTION }
ICMPv6 error code : Parameter Error.
enum ErrorTimeExceeded_e { ICMPV6_HOPLIMIT = 0 , ICMPV6_FRAGTIME }
ICMPv6 error code : Time Exceeded.
enum OptionType_e {
ICMPV6_OPT_LINK_LAYER_SOURCE = 1 , ICMPV6_OPT_LINK_LAYER_TARGET , ICMPV6_OPT_PREFIX , ICMPV6_OPT_REDIRECTED ,
ICMPV6_OPT_MTU
}
ICMPv6 Option type code.
enum Type_e {
ICMPV6_ERROR_DESTINATION_UNREACHABLE = 1 , ICMPV6_ERROR_PACKET_TOO_BIG , ICMPV6_ERROR_TIME_EXCEEDED , ICMPV6_ERROR_PARAMETER_ERROR ,
ICMPV6_ECHO_REQUEST = 128 , ICMPV6_ECHO_REPLY , ICMPV6_SUBSCRIBE_REQUEST , ICMPV6_SUBSCRIBE_REPORT ,
ICMPV6_SUBSCRIVE_END , ICMPV6_ND_ROUTER_SOLICITATION , ICMPV6_ND_ROUTER_ADVERTISEMENT , ICMPV6_ND_NEIGHBOR_SOLICITATION ,
ICMPV6_ND_NEIGHBOR_ADVERTISEMENT , ICMPV6_ND_REDIRECTION , ICMPV6_ROUTER_RENUMBER , ICMPV6_INFORMATION_REQUEST ,
ICMPV6_INFORMATION_RESPONSE , ICMPV6_INVERSE_ND_SOLICITATION , ICMPV6_INVERSE_ND_ADVERSTISEMENT , ICMPV6_MLDV2_SUBSCRIBE_REPORT ,
ICMPV6_MOBILITY_HA_DISCOVER_REQUEST , ICMPV6_MOBILITY_HA_DISCOVER_RESPONSE , ICMPV6_MOBILITY_MOBILE_PREFIX_SOLICITATION , ICMPV6_SECURE_ND_CERTIFICATE_PATH_SOLICITATION ,
ICMPV6_SECURE_ND_CERTIFICATE_PATH_ADVERTISEMENT , ICMPV6_EXPERIMENTAL_MOBILITY
}
ICMPv6 type code.
Public Member Functions
Icmpv6Header ()
Constructor.
virtual ~Icmpv6Header ()
Destructor.
void CalculatePseudoHeaderChecksum (Ipv6Address src, Ipv6Address dst, uint16_t length, uint8_t protocol)
Calculate pseudo header checksum for IPv6.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
uint16_t GetChecksum () const
Get the checksum.
uint8_t GetCode () const
Get the code field.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
virtual uint32_t GetSerializedSize () const
Get the serialized size.
uint8_t GetType () const
Get the type field.
virtual void Print (std::ostream &os) const
Print information.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetChecksum (uint16_t checksum)
Set the checksum.
void SetCode (uint8_t code)
Set the code field.
void SetType (uint8_t type)
Set the type.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the UID of this class.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Attributes
bool m_calcChecksum
Checksum enable or not.
uint16_t m_checksum
The checksum.
Private Attributes
uint8_t m_code
The code.
uint8_t m_type
The type.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
ICMPv6 header.
Introspection did not find any typical Config paths.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 16 bytes (on a 64-bit architecture).
Definition at line 38 of file icmpv6-header.h.
Member Enumeration Documentation
ErrorDestinationUnreachable_e
enum ns3::Icmpv6Header::ErrorDestinationUnreachable_e
ICMPv6 error code : Destination Unreachable.
Enumerator
ICMPV6_NO_ROUTE
ICMPV6_ADM_PROHIBITED
ICMPV6_NOT_NEIGHBOUR
ICMPV6_ADDR_UNREACHABLE
ICMPV6_PORT_UNREACHABLE
Definition at line 89 of file icmpv6-header.h.
ErrorParameterError_e
enum ns3::Icmpv6Header::ErrorParameterError_e
ICMPv6 error code : Parameter Error.
Enumerator
ICMPV6_MALFORMED_HEADER
ICMPV6_UNKNOWN_NEXT_HEADER
ICMPV6_UNKNOWN_OPTION
Definition at line 110 of file icmpv6-header.h.
ErrorTimeExceeded_e
enum ns3::Icmpv6Header::ErrorTimeExceeded_e
ICMPv6 error code : Time Exceeded.
Enumerator
ICMPV6_HOPLIMIT
ICMPV6_FRAGTIME
Definition at line 101 of file icmpv6-header.h.
OptionType_e
enum ns3::Icmpv6Header::OptionType_e
ICMPv6 Option type code.
Enumerator
ICMPV6_OPT_LINK_LAYER_SOURCE
ICMPV6_OPT_LINK_LAYER_TARGET
ICMPV6_OPT_PREFIX
ICMPV6_OPT_REDIRECTED
ICMPV6_OPT_MTU
Definition at line 77 of file icmpv6-header.h.
Type_e
enum ns3::Icmpv6Header::Type_e
ICMPv6 type code.
Enumerator
ICMPV6_ERROR_DESTINATION_UNREACHABLE
ICMPV6_ERROR_PACKET_TOO_BIG
ICMPV6_ERROR_TIME_EXCEEDED
ICMPV6_ERROR_PARAMETER_ERROR
ICMPV6_ECHO_REQUEST
ICMPV6_ECHO_REPLY
ICMPV6_SUBSCRIBE_REQUEST
ICMPV6_SUBSCRIBE_REPORT
ICMPV6_SUBSCRIVE_END
ICMPV6_ND_ROUTER_SOLICITATION
ICMPV6_ND_ROUTER_ADVERTISEMENT
ICMPV6_ND_NEIGHBOR_SOLICITATION
ICMPV6_ND_NEIGHBOR_ADVERTISEMENT
ICMPV6_ND_REDIRECTION
ICMPV6_ROUTER_RENUMBER
ICMPV6_INFORMATION_REQUEST
ICMPV6_INFORMATION_RESPONSE
ICMPV6_INVERSE_ND_SOLICITATION
ICMPV6_INVERSE_ND_ADVERSTISEMENT
ICMPV6_MLDV2_SUBSCRIBE_REPORT
ICMPV6_MOBILITY_HA_DISCOVER_REQUEST
ICMPV6_MOBILITY_HA_DISCOVER_RESPONSE
ICMPV6_MOBILITY_MOBILE_PREFIX_SOLICITATION
ICMPV6_SECURE_ND_CERTIFICATE_PATH_SOLICITATION
ICMPV6_SECURE_ND_CERTIFICATE_PATH_ADVERTISEMENT
ICMPV6_EXPERIMENTAL_MOBILITY
Definition at line 44 of file icmpv6-header.h.
Constructor & Destructor Documentation
Icmpv6Header()
ns3::Icmpv6Header::Icmpv6Header ()
Constructor.
Definition at line 52 of file icmpv6-header.cc.
References NS_LOG_FUNCTION.
~Icmpv6Header()
ns3::Icmpv6Header::~Icmpv6Header () virtual
Destructor.
Definition at line 61 of file icmpv6-header.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CalculatePseudoHeaderChecksum()
void ns3::Icmpv6Header::CalculatePseudoHeaderChecksum (Ipv6Address src, Ipv6Address dst, uint16_t length, uint8_t protocol)
Calculate pseudo header checksum for IPv6.
Parameters
src source address
dst destination address
length length
protocol the protocol number to use in the underlying IPv6 packet.
Definition at line 150 of file icmpv6-header.cc.
References ns3::Buffer::AddAtStart(), ns3::Buffer::Begin(), ns3::Buffer::Iterator::CalculateIpChecksum(), m_checksum, NS_LOG_FUNCTION, ns3::Ipv6Address::Serialize(), ns3::Buffer::Iterator::Write(), ns3::Buffer::Iterator::WriteU16(), and ns3::Buffer::Iterator::WriteU8().
Referenced by ns3::Icmpv6L4Protocol::ForgeEchoRequest(), ns3::Icmpv6L4Protocol::ForgeNA(), ns3::Icmpv6L4Protocol::ForgeNS(), ns3::Icmpv6L4Protocol::ForgeRS(), ns3::Radvd::Send(), ns3::Icmpv6L4Protocol::SendEchoReply(), ns3::Icmpv6L4Protocol::SendMessage(), ns3::Icmpv6L4Protocol::SendNA(), ns3::Icmpv6L4Protocol::SendNS(), ns3::Icmpv6L4Protocol::SendRedirection(), ns3::Icmpv6L4Protocol::SendRS(), and ns3::Ipv6RawSocketImpl::SendTo().
Deserialize()
uint32_t ns3::Icmpv6Header::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start start offset
Returns
length of packet
Implements ns3::Header.
Reimplemented in ns3::Icmpv6ParameterError, ns3::Icmpv6TimeExceeded, ns3::Icmpv6TooBig, ns3::Icmpv6DestinationUnreachable, ns3::Icmpv6Echo, ns3::Icmpv6Redirection, ns3::Icmpv6RS, ns3::Icmpv6RA, ns3::Icmpv6NA, and ns3::Icmpv6NS.
Definition at line 114 of file icmpv6-header.cc.
References GetSerializedSize(), m_checksum, m_code, m_type, NS_LOG_FUNCTION, ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadU32(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetChecksum()
uint16_t ns3::Icmpv6Header::GetChecksum () const
Get the checksum.
Returns
checksum
Definition at line 90 of file icmpv6-header.cc.
References m_checksum, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6NS::Print(), ns3::Icmpv6NA::Print(), ns3::Icmpv6RA::Print(), ns3::Icmpv6RS::Print(), ns3::Icmpv6Redirection::Print(), ns3::Icmpv6Echo::Print(), ns3::Icmpv6DestinationUnreachable::Print(), ns3::Icmpv6TooBig::Print(), ns3::Icmpv6TimeExceeded::Print(), ns3::Icmpv6ParameterError::Print(), ns3::Icmpv6NA::Serialize(), ns3::Icmpv6RA::Serialize(), ns3::Icmpv6RS::Serialize(), ns3::Icmpv6Redirection::Serialize(), ns3::Icmpv6Echo::Serialize(), ns3::Icmpv6DestinationUnreachable::Serialize(), ns3::Icmpv6TooBig::Serialize(), ns3::Icmpv6TimeExceeded::Serialize(), and ns3::Icmpv6ParameterError::Serialize().
GetCode()
uint8_t ns3::Icmpv6Header::GetCode (void) const
Get the code field.
Returns
code of ICMPv6 message
Definition at line 78 of file icmpv6-header.cc.
References m_code, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::Forward(), ns3::Icmpv6L4Protocol::HandleDestinationUnreachable(), ns3::Icmpv6L4Protocol::HandleParameterError(), ns3::Radvd::HandleRead(), ns3::Icmpv6L4Protocol::HandleTimeExceeded(), ns3::Icmpv6NS::Print(), ns3::Icmpv6NA::Print(), ns3::Icmpv6RA::Print(), ns3::Icmpv6RS::Print(), ns3::Icmpv6Redirection::Print(), ns3::Icmpv6Echo::Print(), ns3::Icmpv6DestinationUnreachable::Print(), ns3::Icmpv6TooBig::Print(), ns3::Icmpv6TimeExceeded::Print(), ns3::Icmpv6ParameterError::Print(), ns3::Icmpv6NS::Serialize(), ns3::Icmpv6NA::Serialize(), ns3::Icmpv6RA::Serialize(), ns3::Icmpv6RS::Serialize(), ns3::Icmpv6Redirection::Serialize(), ns3::Icmpv6Echo::Serialize(), ns3::Icmpv6DestinationUnreachable::Serialize(), ns3::Icmpv6TooBig::Serialize(), ns3::Icmpv6TimeExceeded::Serialize(), and ns3::Icmpv6ParameterError::Serialize().
GetInstanceTypeId()
TypeId ns3::Icmpv6Header::GetInstanceTypeId (void) const virtual
Get the instance type ID.
Returns
instance type ID
Implements ns3::ObjectBase.
Reimplemented in ns3::Icmpv6ParameterError, ns3::Icmpv6TimeExceeded, ns3::Icmpv6TooBig, ns3::Icmpv6DestinationUnreachable, ns3::Icmpv6Echo, ns3::Icmpv6Redirection, ns3::Icmpv6RS, ns3::Icmpv6RA, ns3::Icmpv6NA, and ns3::Icmpv6NS.
Definition at line 46 of file icmpv6-header.cc.
References GetTypeId(), and NS_LOG_FUNCTION.
GetSerializedSize()
uint32_t ns3::Icmpv6Header::GetSerializedSize (void) const virtual
Get the serialized size.
Returns
serialized size
Implements ns3::Header.
Reimplemented in ns3::Icmpv6ParameterError, ns3::Icmpv6TimeExceeded, ns3::Icmpv6TooBig, ns3::Icmpv6DestinationUnreachable, ns3::Icmpv6Echo, ns3::Icmpv6Redirection, ns3::Icmpv6RS, ns3::Icmpv6RA, ns3::Icmpv6NA, and ns3::Icmpv6NS.
Definition at line 108 of file icmpv6-header.cc.
References NS_LOG_FUNCTION.
Referenced by Deserialize(), and ns3::Icmpv6L4Protocol::SendMessage().
GetType()
uint8_t ns3::Icmpv6Header::GetType (void) const
Get the type field.
Returns
type of ICMPv6 message
Definition at line 66 of file icmpv6-header.cc.
References m_type, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::Forward(), ns3::Ipv6RawSocketImpl::ForwardUp(), ns3::Icmpv6NS::Print(), ns3::Icmpv6NA::Print(), ns3::Icmpv6RA::Print(), ns3::Icmpv6RS::Print(), ns3::Icmpv6Redirection::Print(), ns3::Icmpv6Echo::Print(), ns3::Icmpv6DestinationUnreachable::Print(), ns3::Icmpv6TooBig::Print(), ns3::Icmpv6TimeExceeded::Print(), ns3::Icmpv6ParameterError::Print(), IcmpV6EchoReplyTestCase::ReceivePkt(), IcmpV6TimeExceedTestCase::ReceivePkt(), ns3::Icmpv6NS::Serialize(), ns3::Icmpv6NA::Serialize(), ns3::Icmpv6RA::Serialize(), ns3::Icmpv6RS::Serialize(), ns3::Icmpv6Redirection::Serialize(), ns3::Icmpv6Echo::Serialize(), ns3::Icmpv6DestinationUnreachable::Serialize(), ns3::Icmpv6TooBig::Serialize(), ns3::Icmpv6TimeExceeded::Serialize(), and ns3::Icmpv6ParameterError::Serialize().
GetTypeId()
TypeId ns3::Icmpv6Header::GetTypeId (void) static
Get the UID of this class.
Returns
UID
Definition at line 36 of file icmpv6-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::Icmpv6Header::Print (std::ostream & os) const virtual
Print information.
Parameters
os output stream
Implements ns3::Header.
Reimplemented in ns3::Icmpv6ParameterError, ns3::Icmpv6TimeExceeded, ns3::Icmpv6TooBig, ns3::Icmpv6DestinationUnreachable, ns3::Icmpv6Echo, ns3::Icmpv6Redirection, ns3::Icmpv6RS, ns3::Icmpv6RA, ns3::Icmpv6NA, and ns3::Icmpv6NS.
Definition at line 102 of file icmpv6-header.cc.
References m_checksum, m_code, m_type, and NS_LOG_FUNCTION.
Serialize()
void ns3::Icmpv6Header::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start start offset
Implements ns3::Header.
Reimplemented in ns3::Icmpv6ParameterError, ns3::Icmpv6TimeExceeded, ns3::Icmpv6TooBig, ns3::Icmpv6DestinationUnreachable, ns3::Icmpv6Echo, ns3::Icmpv6Redirection, ns3::Icmpv6RS, ns3::Icmpv6RA, ns3::Icmpv6NA, and ns3::Icmpv6NS.
Definition at line 128 of file icmpv6-header.cc.
References ns3::Buffer::Iterator::CalculateIpChecksum(), ns3::Buffer::Iterator::GetSize(), m_calcChecksum, m_checksum, m_code, m_type, ns3::Buffer::Iterator::Next(), NS_LOG_FUNCTION, visualizer.core::start(), ns3::Buffer::Iterator::WriteU16(), ns3::Buffer::Iterator::WriteU32(), and ns3::Buffer::Iterator::WriteU8().
SetChecksum()
void ns3::Icmpv6Header::SetChecksum (uint16_t checksum)
Set the checksum.
Parameters
checksum to set
Definition at line 96 of file icmpv6-header.cc.
References m_checksum, and NS_LOG_FUNCTION.
SetCode()
void ns3::Icmpv6Header::SetCode (uint8_t code)
Set the code field.
Parameters
code code to set
Definition at line 84 of file icmpv6-header.cc.
References m_code, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6Echo::Icmpv6Echo(), ns3::Icmpv6NA::Icmpv6NA(), ns3::Icmpv6NS::Icmpv6NS(), ns3::Icmpv6RA::Icmpv6RA(), ns3::Icmpv6Redirection::Icmpv6Redirection(), ns3::Icmpv6RS::Icmpv6RS(), ns3::Icmpv6NS::Deserialize(), ns3::Icmpv6NA::Deserialize(), ns3::Icmpv6RA::Deserialize(), ns3::Icmpv6RS::Deserialize(), ns3::Icmpv6Redirection::Deserialize(), ns3::Icmpv6Echo::Deserialize(), ns3::Icmpv6DestinationUnreachable::Deserialize(), ns3::Icmpv6TooBig::Deserialize(), ns3::Icmpv6TimeExceeded::Deserialize(), ns3::Icmpv6ParameterError::Deserialize(), IcmpV6EchoReplyTestCase::DoSendData(), IcmpV6TimeExceedTestCase::DoSendData(), ns3::Icmpv6L4Protocol::SendErrorDestinationUnreachable(), ns3::Icmpv6L4Protocol::SendErrorParameterError(), ns3::Icmpv6L4Protocol::SendErrorTimeExceeded(), and ns3::Icmpv6L4Protocol::SendErrorTooBig().
SetType()
void ns3::Icmpv6Header::SetType (uint8_t type)
Set the type.
Parameters
type type to set
Definition at line 72 of file icmpv6-header.cc.
References m_type, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6DestinationUnreachable::Icmpv6DestinationUnreachable(), ns3::Icmpv6Echo::Icmpv6Echo(), ns3::Icmpv6NA::Icmpv6NA(), ns3::Icmpv6NS::Icmpv6NS(), ns3::Icmpv6ParameterError::Icmpv6ParameterError(), ns3::Icmpv6RA::Icmpv6RA(), ns3::Icmpv6Redirection::Icmpv6Redirection(), ns3::Icmpv6RS::Icmpv6RS(), ns3::Icmpv6TimeExceeded::Icmpv6TimeExceeded(), ns3::Icmpv6TooBig::Icmpv6TooBig(), ns3::Icmpv6NS::Deserialize(), ns3::Icmpv6NA::Deserialize(), ns3::Icmpv6RA::Deserialize(), ns3::Icmpv6RS::Deserialize(), ns3::Icmpv6Redirection::Deserialize(), ns3::Icmpv6Echo::Deserialize(), ns3::Icmpv6DestinationUnreachable::Deserialize(), ns3::Icmpv6TooBig::Deserialize(), ns3::Icmpv6TimeExceeded::Deserialize(), ns3::Icmpv6ParameterError::Deserialize(), IcmpV6EchoReplyTestCase::DoSendData(), and IcmpV6TimeExceedTestCase::DoSendData().
Member Data Documentation
m_calcChecksum
bool ns3::Icmpv6Header::m_calcChecksum protected
Checksum enable or not.
Definition at line 214 of file icmpv6-header.h.
Referenced by Serialize(), ns3::Icmpv6NS::Serialize(), ns3::Icmpv6NA::Serialize(), ns3::Icmpv6RS::Serialize(), ns3::Icmpv6Redirection::Serialize(), and ns3::Icmpv6Echo::Serialize().
m_checksum
uint16_t ns3::Icmpv6Header::m_checksum protected
The checksum.
Definition at line 219 of file icmpv6-header.h.
Referenced by ns3::Icmpv6Echo::Icmpv6Echo(), ns3::Icmpv6NA::Icmpv6NA(), ns3::Icmpv6NS::Icmpv6NS(), ns3::Icmpv6Redirection::Icmpv6Redirection(), CalculatePseudoHeaderChecksum(), Deserialize(), ns3::Icmpv6NS::Deserialize(), ns3::Icmpv6NA::Deserialize(), ns3::Icmpv6RA::Deserialize(), ns3::Icmpv6RS::Deserialize(), ns3::Icmpv6Redirection::Deserialize(), ns3::Icmpv6Echo::Deserialize(), ns3::Icmpv6DestinationUnreachable::Deserialize(), ns3::Icmpv6TooBig::Deserialize(), ns3::Icmpv6TimeExceeded::Deserialize(), ns3::Icmpv6ParameterError::Deserialize(), GetChecksum(), Print(), Serialize(), ns3::Icmpv6NS::Serialize(), and SetChecksum().
m_code
uint8_t ns3::Icmpv6Header::m_code private
The code.
Definition at line 230 of file icmpv6-header.h.
Referenced by Deserialize(), GetCode(), Print(), Serialize(), and SetCode().
m_type
uint8_t ns3::Icmpv6Header::m_type private
The type.
Definition at line 225 of file icmpv6-header.h.
Referenced by Deserialize(), GetType(), Print(), Serialize(), and SetType().
The documentation for this class was generated from the following files:
src/internet/model/icmpv6-header.h
src/internet/model/icmpv6-header.cc