ns-3: ns3::PacketSocket Class Reference
ns3::PacketSocket Class Reference
Network » Socket
A PacketSocket is a link between an application and a net device.
#include "packet-socket.h"
Public Member Functions
PacketSocket ()
virtual ~PacketSocket ()
virtual int Bind (const Address &address)
Bind the socket to the NetDevice and register the protocol handler specified in the address.
virtual int Bind (void)
Bind the socket to the NetDevice and register the protocol handler.
virtual int Bind6 (void)
Bind the socket to the NetDevice and register the protocol handler.
virtual int Close (void)
Close a socket.
virtual int Connect (const Address &address)
Initiate a connection to a remote host.
virtual bool GetAllowBroadcast () const
Query whether broadcast datagram transmissions are allowed.
virtual enum SocketErrno GetErrno (void) const
Get last error number.
virtual Ptr< Node > GetNode (void) const
Return the node this socket is associated with.
virtual int GetPeerName (Address &address) const
Get the peer address of a connected socket.
virtual uint32_t GetRxAvailable (void) const
Return number of bytes which can be returned from one or multiple calls to Recv.
virtual enum SocketType GetSocketType (void) const
virtual int GetSockName (Address &address) const
Get socket address.
virtual uint32_t GetTxAvailable (void) const
Returns the number of bytes which can be sent in a single call to Send.
virtual int Listen (void)
Listen for incoming connections.
virtual Ptr< Packet > Recv (uint32_t maxSize, uint32_t flags)
Read data from the socket.
virtual Ptr< Packet > RecvFrom (uint32_t maxSize, uint32_t flags, Address &fromAddress)
Read a single packet from the socket and retrieve the sender address.
virtual int Send (Ptr< Packet > p, uint32_t flags)
Send data (or dummy data) to the remote host.
virtual int SendTo (Ptr< Packet > p, uint32_t flags, const Address &toAddress)
Send data to a specified peer.
virtual bool SetAllowBroadcast (bool allowBroadcast)
Configure whether broadcast datagram transmissions are allowed.
void SetNode (Ptr< Node > node)
Set the associated node.
virtual int ShutdownRecv (void)
virtual int ShutdownSend (void)
Public Member Functions inherited from ns3::Socket
Socket (void)
virtual ~Socket (void)
virtual void BindToNetDevice (Ptr< NetDevice > netdevice)
Bind a socket to specific device.
Ptr< NetDevice > GetBoundNetDevice ()
Returns socket's bound NetDevice, if any.
uint8_t GetIpTos (void) const
Query the value of IP Type of Service of this socket.
virtual uint8_t GetIpTtl (void) const
Query the value of IP Time to Live field of this socket.
virtual uint8_t GetIpv6HopLimit (void) const
Query the value of IP Hop Limit field of this socket.
uint8_t GetIpv6Tclass (void) const
Query the value of IPv6 Traffic Class field of this socket.
uint8_t GetPriority (void) const
Query the priority value of this socket.
virtual void Ipv6JoinGroup (Ipv6Address address)
Joins a IPv6 multicast group without filters.
virtual void Ipv6JoinGroup (Ipv6Address address, Ipv6MulticastFilterMode filterMode, std::vector< Ipv6Address > sourceAddresses)
Joins a IPv6 multicast group.
virtual void Ipv6LeaveGroup (void)
Leaves IPv6 multicast group this socket is joined to.
bool IsIpRecvTos (void) const
Ask if the socket is currently passing information about IP Type of Service up the stack.
bool IsIpRecvTtl (void) const
Ask if the socket is currently passing information about IP_TTL up the stack.
bool IsIpv6RecvHopLimit (void) const
Ask if the socket is currently passing information about IPv6 Hop Limit up the stack.
bool IsIpv6RecvTclass (void) const
Ask if the socket is currently passing information about IPv6 Traffic Class up the stack.
bool IsRecvPktInfo () const
Get status indicating whether enable/disable packet information to socket.
int Recv (uint8_t *buf, uint32_t size, uint32_t flags)
Recv data (or dummy data) from the remote host.
Ptr< Packet > Recv (void)
Read a single packet from the socket.
Ptr< Packet > RecvFrom (Address &fromAddress)
Read a single packet from the socket and retrieve the sender address.
int RecvFrom (uint8_t *buf, uint32_t size, uint32_t flags, Address &fromAddress)
Read a single packet from the socket and retrieve the sender address.
int Send (const uint8_t *buf, uint32_t size, uint32_t flags)
Send data (or dummy data) to the remote host.
int Send (Ptr< Packet > p)
Send data (or dummy data) to the remote host.
int SendTo (const uint8_t *buf, uint32_t size, uint32_t flags, const Address &address)
Send data to a specified peer.
void SetAcceptCallback (Callback< bool, Ptr< Socket >, const Address & > connectionRequest, Callback< void, Ptr< Socket >, const Address & > newConnectionCreated)
Accept connection requests from remote hosts.
void SetCloseCallbacks (Callback< void, Ptr< Socket > > normalClose, Callback< void, Ptr< Socket > > errorClose)
Detect socket recv() events such as graceful shutdown or error.
void SetConnectCallback (Callback< void, Ptr< Socket > > connectionSucceeded, Callback< void, Ptr< Socket > > connectionFailed)
Specify callbacks to allow the caller to determine if the connection succeeds of fails.
void SetDataSentCallback (Callback< void, Ptr< Socket >, uint32_t > dataSent)
Notify application when a packet has been sent from transport protocol (non-standard socket call)
void SetIpRecvTos (bool ipv4RecvTos)
Tells a socket to pass information about IP Type of Service up the stack.
void SetIpRecvTtl (bool ipv4RecvTtl)
Tells a socket to pass information about IP_TTL up the stack.
void SetIpTos (uint8_t ipTos)
Manually set IP Type of Service field.
virtual void SetIpTtl (uint8_t ipTtl)
Manually set IP Time to Live field.
virtual void SetIpv6HopLimit (uint8_t ipHopLimit)
Manually set IPv6 Hop Limit.
void SetIpv6RecvHopLimit (bool ipv6RecvHopLimit)
Tells a socket to pass information about IPv6 Hop Limit up the stack.
void SetIpv6RecvTclass (bool ipv6RecvTclass)
Tells a socket to pass information about IPv6 Traffic Class up the stack.
void SetIpv6Tclass (int ipTclass)
Manually set IPv6 Traffic Class field.
void SetPriority (uint8_t priority)
Manually set the socket priority.
void SetRecvCallback (Callback< void, Ptr< Socket > >)
Notify application when new data is available to be read.
void SetRecvPktInfo (bool flag)
Enable/Disable receive packet information to socket.
void SetSendCallback (Callback< void, Ptr< Socket >, uint32_t > sendCb)
Notify application when space in transmit buffer is added.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Socket
static Ptr< Socket > CreateSocket (Ptr< Node > node, TypeId tid)
This method wraps the creation of sockets that is performed on a given node by a SocketFactory specified by TypeId.
static TypeId GetTypeId (void)
Get the type ID.
static uint8_t IpTos2Priority (uint8_t ipTos)
Return the priority corresponding to a given TOS value.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
enum State { STATE_OPEN , STATE_BOUND , STATE_CONNECTED , STATE_CLOSED }
States of the socket.
Private Member Functions
int DoBind (const PacketSocketAddress &address)
Bind the socket to the NetDevice and register the protocol handler specified in the address.
virtual void DoDispose (void)
Destructor implementation.
void ForwardUp (Ptr< NetDevice > device, Ptr< const Packet > packet, uint16_t protocol, const Address &from, const Address &to, NetDevice::PacketType packetType)
Called by the L3 protocol when it received a packet to pass on to TCP.
uint32_t GetMinMtu (PacketSocketAddress ad) const
Get the minimum MTU supported by the NetDevices bound to a specific address.
Private Attributes
std::queue< std::pair< Ptr< Packet >, Address > > m_deliveryQueue
Rx queue.
Address m_destAddr
Default destination address.
uint32_t m_device
index of the bound NetDevice
TracedCallback< Ptr< const Packet > > m_dropTrace
Traced callback: dropped packets.
enum SocketErrno m_errno
Socket error code.
bool m_isSingleDevice
Is bound to a single netDevice.
Ptr< Node > m_node
the associated node
uint16_t m_protocol
Socket protocol.
uint32_t m_rcvBufSize
Rx buffer size [Bytes].
uint32_t m_rxAvailable
Rx queue size [Bytes].
bool m_shutdownRecv
Receive no longer allowed.
bool m_shutdownSend
Send no longer allowed.
enum State m_state
Socket state.
Additional Inherited Members
Public Types inherited from ns3::Socket
enum Ipv6MulticastFilterMode { INCLUDE =1 , EXCLUDE }
Enumeration of the possible filter of a socket.
enum SocketErrno {
ERROR_NOTERROR , ERROR_ISCONN , ERROR_NOTCONN , ERROR_MSGSIZE ,
ERROR_AGAIN , ERROR_SHUTDOWN , ERROR_OPNOTSUPP , ERROR_AFNOSUPPORT ,
ERROR_INVAL , ERROR_BADF , ERROR_NOROUTETOHOST , ERROR_NODEV ,
ERROR_ADDRNOTAVAIL , ERROR_ADDRINUSE , SOCKET_ERRNO_LAST
}
Enumeration of the possible errors returned by a socket.
enum SocketPriority {
NS3_PRIO_BESTEFFORT = 0 , NS3_PRIO_FILLER = 1 , NS3_PRIO_BULK = 2 , NS3_PRIO_INTERACTIVE_BULK = 4 ,
NS3_PRIO_INTERACTIVE = 6 , NS3_PRIO_CONTROL = 7
}
Enumeration of the possible socket priorities.
enum SocketType { NS3_SOCK_STREAM , NS3_SOCK_SEQPACKET , NS3_SOCK_DGRAM , NS3_SOCK_RAW }
Enumeration of the possible socket types.
Protected Member Functions inherited from ns3::Socket
bool IsManualIpTtl (void) const
Checks if the socket has a specific IPv4 TTL set.
bool IsManualIpv6HopLimit (void) const
Checks if the socket has a specific IPv6 Hop Limit set.
bool IsManualIpv6Tclass (void) const
Checks if the socket has a specific IPv6 Tclass set.
void NotifyConnectionFailed (void)
Notify through the callback (if set) that the connection has not been established due to an error.
bool NotifyConnectionRequest (const Address &from)
Notify through the callback (if set) that an incoming connection is being requested by a remote host.
void NotifyConnectionSucceeded (void)
Notify through the callback (if set) that the connection has been established.
void NotifyDataRecv (void)
Notify through the callback (if set) that some data have been received.
void NotifyDataSent (uint32_t size)
Notify through the callback (if set) that some data have been sent.
void NotifyErrorClose (void)
Notify through the callback (if set) that the connection has been closed due to an error.
void NotifyNewConnectionCreated (Ptr< Socket > socket, const Address &from)
Notify through the callback (if set) that a new connection has been created.
void NotifyNormalClose (void)
Notify through the callback (if set) that the connection has been closed.
void NotifySend (uint32_t spaceAvailable)
Notify through the callback (if set) that some data have been sent.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Socket
Ptr< NetDevice > m_boundnetdevice
the device this socket is bound to (might be null).
Ipv6Address m_ipv6MulticastGroupAddress
IPv6 multicast group address.
bool m_recvPktInfo
if the socket should add packet info tags to the packet forwarded to L4.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A PacketSocket is a link between an application and a net device.
Introspection did not find any typical Config paths.
A PacketSocket can be used to connect an application to a net device. The application provides the buffers of data, the socket converts them to a raw packet and the net device then adds the protocol specific headers and trailers. This socket type is very similar to the linux and BSD "packet" sockets.
Here is a summary of the semantics of this class:
Bind: Bind uses only the protocol and device fields of the PacketSocketAddress. If none are provided, Bind uses zero for both, which means that the socket is bound to all protocols on all devices on the node.
Connect: uses only the protocol, device and "physical address" field of the PacketSocketAddress. It is used to set the default destination address for outgoing packets.
Send: send the input packet to the underlying NetDevices with the default destination address. The socket must be bound and connected.
SendTo: uses the protocol, device, and "physical address" fields of the PacketSocketAddress. The device value is used to specialize the packet transmission to a single device, the protocol value specifies the protocol of this packet only and the "physical address" field is used to override the default destination address. The socket must be bound.
Recv: The address represents the address of the packer originator. The fields "physical address", device, and protocol are filled.
Accept: not allowed
Listen: returns -1 (OPNOTSUPP)
Socket data that is read from this socket using the methods returning an ns3::Packet object (i.e., Recv (), RecvMsg (), RecvFrom ()) will return Packet objects with three PacketTag objects attached. Applications may wish to read the extra out-of-band data provided in these tags, and may safely remove the tags from the Packet.
PacketSocketTag: contains destination address (type PacketSocketAddress) and packet type of the received packet
DeviceNameTag: contains the TypeId string of the relevant NetDevice
See also
class PacketSocketTag
class DeviceNameTag
Attributes
RcvBufSize: PacketSocket maximum receive buffer size (bytes)
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 131072
Flags: construct write read
TraceSources
Drop: Drop packet due to receive buffer overflow
Callback signature: ns3::Packet::TracedCallback
Size of this type is 296 bytes (on a 64-bit architecture).
Definition at line 93 of file packet-socket.h.
Member Enumeration Documentation
State
enum ns3::PacketSocket::State private
States of the socket.
Enumerator
STATE_OPEN
STATE_BOUND
STATE_CONNECTED
STATE_CLOSED
Definition at line 188 of file packet-socket.h.
Constructor & Destructor Documentation
PacketSocket()
ns3::PacketSocket::PacketSocket ()
Definition at line 57 of file packet-socket.cc.
References ns3::Socket::ERROR_NOTERROR, m_device, m_errno, m_isSingleDevice, m_shutdownRecv, m_shutdownSend, m_state, NS_LOG_FUNCTION, and STATE_OPEN.
~PacketSocket()
ns3::PacketSocket::~PacketSocket () virtual
Definition at line 75 of file packet-socket.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Bind() [1/2]
int ns3::PacketSocket::Bind (const Address & address) virtual
Bind the socket to the NetDevice and register the protocol handler specified in the address.
Parameters
address the packet socket address
Returns
0 on success, -1 on failure.
Implements ns3::Socket.
Definition at line 126 of file packet-socket.cc.
References first::address, ns3::PacketSocketAddress::ConvertFrom(), DoBind(), ns3::Socket::ERROR_INVAL, ns3::PacketSocketAddress::IsMatchingType(), m_errno, and NS_LOG_FUNCTION.
Bind() [2/2]
int ns3::PacketSocket::Bind (void) virtual
Bind the socket to the NetDevice and register the protocol handler.
Warning
this will actually bind protocol "0".
Returns
0 on success, -1 on failure.
Implements ns3::Socket.
Definition at line 109 of file packet-socket.cc.
References first::address, DoBind(), and NS_LOG_FUNCTION.
Referenced by Bind6().
Bind6()
int ns3::PacketSocket::Bind6 (void) virtual
Bind the socket to the NetDevice and register the protocol handler.
Warning
this will actually bind protocol "0".
Returns
0 on success, -1 on failure.
Implements ns3::Socket.
Definition at line 119 of file packet-socket.cc.
References Bind(), and NS_LOG_FUNCTION.
Close()
int ns3::PacketSocket::Close (void) virtual
Close a socket.
Returns
zero on success, -1 on failure.
After the Close call, the socket is no longer valid, and cannot safely be used for subsequent operations.
Implements ns3::Socket.
Definition at line 199 of file packet-socket.cc.
References ns3::Socket::ERROR_BADF, ForwardUp(), m_errno, m_node, m_shutdownRecv, m_shutdownSend, m_state, ns3::MakeCallback(), NS_LOG_FUNCTION, STATE_BOUND, STATE_CLOSED, STATE_CONNECTED, and ns3::Node::UnregisterProtocolHandler().
Connect()
int ns3::PacketSocket::Connect (const Address & address) virtual
Initiate a connection to a remote host.
Parameters
address Address of remote.
Returns
0 on success, -1 on error (in which case errno is set).
Implements ns3::Socket.
Definition at line 218 of file packet-socket.cc.
References first::address, ns3::Socket::ERROR_AFNOSUPPORT, ns3::Socket::ERROR_BADF, ns3::Socket::ERROR_INVAL, ns3::Socket::ERROR_ISCONN, ns3::PacketSocketAddress::IsMatchingType(), m_destAddr, m_errno, m_state, ns3::Socket::NotifyConnectionFailed(), ns3::Socket::NotifyConnectionSucceeded(), NS_LOG_FUNCTION, STATE_CLOSED, STATE_CONNECTED, and STATE_OPEN.
DoBind()
int ns3::PacketSocket::DoBind (const PacketSocketAddress & address) private
Bind the socket to the NetDevice and register the protocol handler specified in the address.
Parameters
address the packet socket address
Returns
0 on success, -1 on failure.
Definition at line 139 of file packet-socket.cc.
References first::address, ns3::Socket::ERROR_BADF, ns3::Socket::ERROR_INVAL, ForwardUp(), ns3::Node::GetDevice(), ns3::Socket::m_boundnetdevice, m_device, m_errno, m_isSingleDevice, m_node, m_protocol, m_state, ns3::MakeCallback(), NS_LOG_FUNCTION, ns3::Node::RegisterProtocolHandler(), STATE_BOUND, STATE_CLOSED, and STATE_CONNECTED.
Referenced by Bind().
DoDispose()
void ns3::PacketSocket::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Socket.
Definition at line 81 of file packet-socket.cc.
References m_device, and NS_LOG_FUNCTION.
ForwardUp()
void ns3::PacketSocket::ForwardUp (Ptr< NetDevice > device, Ptr< const Packet > packet, uint16_t protocol, const Address & from, const Address & to, NetDevice::PacketType packetType) private
Called by the L3 protocol when it received a packet to pass on to TCP.
Parameters
device the incoming NetDevice
packet the incoming packet
protocol the protocol
from sender address
to destination address
packetType packet type
Definition at line 387 of file packet-socket.cc.
References ns3::Packet::AddPacketTag(), first::address, m_deliveryQueue, m_dropTrace, m_rcvBufSize, m_rxAvailable, m_shutdownRecv, ns3::Socket::NotifyDataRecv(), NS_LOG_FUNCTION, NS_LOG_LOGIC, NS_LOG_WARN, ns3::Packet::RemovePacketTag(), ns3::PacketSocketTag::SetDestAddress(), ns3::DeviceNameTag::SetDeviceName(), and ns3::PacketSocketTag::SetPacketType().
Referenced by Close(), and DoBind().
GetAllowBroadcast()
bool ns3::PacketSocket::GetAllowBroadcast () const virtual
Query whether broadcast datagram transmissions are allowed.
This method corresponds to using getsockopt() SO_BROADCAST of real network or BSD sockets.
Returns
true if broadcast is allowed, false otherwise
Implements ns3::Socket.
Definition at line 525 of file packet-socket.cc.
References NS_LOG_FUNCTION.
GetErrno()
enum Socket::SocketErrno ns3::PacketSocket::GetErrno (void) const virtual
Get last error number.
Returns
the errno associated to the last call which failed in this socket. Each socket's errno is initialized to zero when the socket is created.
Implements ns3::Socket.
Definition at line 81 of file packet-socket.cc.
GetMinMtu()
uint32_t ns3::PacketSocket::GetMinMtu (PacketSocketAddress ad) const private
Get the minimum MTU supported by the NetDevices bound to a specific address.
Parameters
ad the socket address to check for
Returns
The minimum MTU
Definition at line 273 of file packet-socket.cc.
References ns3::Node::GetDevice(), ns3::Node::GetNDevices(), ns3::PacketSocketAddress::GetSingleDevice(), ns3::PacketSocketAddress::IsSingleDevice(), m_node, min, and NS_LOG_FUNCTION.
Referenced by GetTxAvailable(), and SendTo().
GetNode()
Ptr< Node > ns3::PacketSocket::GetNode (void) const virtual
Return the node this socket is associated with.
Returns
the node
Implements ns3::Socket.
Definition at line 102 of file packet-socket.cc.
References m_node, and NS_LOG_FUNCTION.
GetPeerName()
int ns3::PacketSocket::GetPeerName (Address & address) const virtual
Get the peer address of a connected socket.
Parameters
address the address this socket is connected to.
Returns
0 if success, -1 otherwise
Implements ns3::Socket.
Definition at line 498 of file packet-socket.cc.
References first::address, ns3::Socket::ERROR_NOTCONN, m_destAddr, m_errno, m_state, NS_LOG_FUNCTION, and STATE_CONNECTED.
GetRxAvailable()
uint32_t ns3::PacketSocket::GetRxAvailable (void) const virtual
Return number of bytes which can be returned from one or multiple calls to Recv.
Must be possible to call this method from the Recv callback.
Returns
the number of bytes which can be returned from one or multiple Recv calls.
Implements ns3::Socket.
Definition at line 432 of file packet-socket.cc.
References m_rxAvailable, and NS_LOG_FUNCTION.
GetSocketType()
enum Socket::SocketType ns3::PacketSocket::GetSocketType (void) const virtual
Returns
the socket type, analogous to getsockopt (SO_TYPE)
Implements ns3::Socket.
Definition at line 81 of file packet-socket.cc.
GetSockName()
int ns3::PacketSocket::GetSockName (Address & address) const virtual
Get socket address.
Parameters
address the address name this socket is associated with.
Returns
0 if success, -1 otherwise
Implements ns3::Socket.
Definition at line 475 of file packet-socket.cc.
References first::address, ns3::Node::GetDevice(), m_device, m_isSingleDevice, m_node, m_protocol, NS_LOG_FUNCTION, ns3::PacketSocketAddress::SetAllDevices(), ns3::PacketSocketAddress::SetPhysicalAddress(), ns3::PacketSocketAddress::SetProtocol(), and ns3::PacketSocketAddress::SetSingleDevice().
GetTxAvailable()
uint32_t ns3::PacketSocket::GetTxAvailable (void) const virtual
Returns the number of bytes which can be sent in a single call to Send.
For datagram sockets, this returns the number of bytes that can be passed atomically through the underlying protocol.
For stream sockets, this returns the available space in bytes left in the transmit buffer.
Returns
The number of bytes which can be sent in a single Send call.
Implements ns3::Socket.
Definition at line 294 of file packet-socket.cc.
References ns3::PacketSocketAddress::ConvertFrom(), GetMinMtu(), m_destAddr, m_state, NS_LOG_FUNCTION, and STATE_CONNECTED.
Referenced by SendTo().
GetTypeId()
TypeId ns3::PacketSocket::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 39 of file packet-socket.cc.
References m_dropTrace, m_rcvBufSize, ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
Listen()
int ns3::PacketSocket::Listen (void) virtual
Listen for incoming connections.
Returns
0 on success, -1 on error (in which case errno is set).
Implements ns3::Socket.
Definition at line 252 of file packet-socket.cc.
References ns3::Socket::ERROR_OPNOTSUPP, m_errno, and NS_LOG_FUNCTION.
Recv()
Ptr< Packet > ns3::PacketSocket::Recv (uint32_t maxSize, uint32_t flags) virtual
Read data from the socket.
This function matches closely in semantics to the recv() function call in the standard C library (libc): ssize_t recv (int s, void *buf, size_t len, int flags); except that the receive I/O is asynchronous. This is the primary Recv method at this low-level API and must be implemented by subclasses.
This method is normally used only on a connected socket. In a typical blocking sockets model, this call would block until at least one byte is returned or the connection closes. In ns-3 at this API, the call returns immediately in such a case and returns 0 if nothing is available to be read. However, an application can set a callback, ns3::SetRecvCallback, to be notified of data being available to be read (when it conceptually unblocks); this is an asynchronous I/O model for recv().
This variant of Recv() uses class ns3::Packet to encapsulate data, rather than providing a raw pointer and length field. This allows an ns-3 application to attach tags if desired (such as a flow ID) and may allow the simulator to avoid some data copies. Despite the appearance of receiving Packets on a stream socket, just think of it as a fancy byte buffer with streaming semantics.
The semantics depend on the type of socket. For a datagram socket, each Recv() returns the data from at most one Send(), and order is not necessarily preserved. For a stream socket, the bytes are delivered in order, and on-the-wire packet boundaries are not preserved.
The flags argument is formed by or'ing one or more of the values: MSG_OOB process out-of-band data MSG_PEEK peek at incoming message None of these flags are supported for now.
Some variants of Recv() are supported as additional API, including RecvFrom(), overloaded Recv() without arguments, and variants that use raw character buffers.
Parameters
maxSize reader will accept packet up to maxSize
flags Socket control flags
Returns
Ptr<Packet> of the next in-sequence packet. Returns 0 if the socket cannot return a next in-sequence packet conforming to the maxSize and flags.
See also
SetRecvCallback
Implements ns3::Socket.
Definition at line 441 of file packet-socket.cc.
References NS_LOG_FUNCTION, and RecvFrom().
RecvFrom()
Ptr< Packet > ns3::PacketSocket::RecvFrom (uint32_t maxSize, uint32_t flags, Address & fromAddress) virtual
Read a single packet from the socket and retrieve the sender address.
Calls Recv(maxSize, flags) with maxSize implicitly set to maximum sized integer, and flags set to zero.
This method has similar semantics to Recv () but subclasses may want to provide checks on socket state, so the implementation is pushed to subclasses.
Parameters
maxSize reader will accept packet up to maxSize
flags Socket control flags
fromAddress output parameter that will return the address of the sender of the received packet, if any. Remains untouched if no packet is received.
Returns
Ptr<Packet> of the next in-sequence packet. Returns 0 if the socket cannot return a next in-sequence packet.
Implements ns3::Socket.
Definition at line 451 of file packet-socket.cc.
References ns3::Packet::GetSize(), m_deliveryQueue, m_rxAvailable, and NS_LOG_FUNCTION.
Referenced by Recv().
Send()
int ns3::PacketSocket::Send (Ptr< Packet > p, uint32_t flags) virtual
Send data (or dummy data) to the remote host.
This function matches closely in semantics to the send() function call in the standard C library (libc): ssize_t send (int s, const void *msg, size_t len, int flags); except that the send I/O is asynchronous. This is the primary Send method at this low-level API and must be implemented by subclasses.
In a typical blocking sockets model, this call would block upon lack of space to hold the message to be sent. In ns-3 at this API, the call returns immediately in such a case, but the callback registered with SetSendCallback() is invoked when the socket has space (when it conceptually unblocks); this is an asynchronous I/O model for send().
This variant of Send() uses class ns3::Packet to encapsulate data, rather than providing a raw pointer and length field. This allows an ns-3 application to attach tags if desired (such as a flow ID) and may allow the simulator to avoid some data copies. Despite the appearance of sending Packets on a stream socket, just think of it as a fancy byte buffer with streaming semantics.
If either the message buffer within the Packet is too long to pass atomically through the underlying protocol (for datagram sockets), or the message buffer cannot entirely fit in the transmit buffer (for stream sockets), -1 is returned and SocketErrno is set to ERROR_MSGSIZE. If the packet does not fit, the caller can split the Packet (based on information obtained from GetTxAvailable) and reattempt to send the data.
The flags argument is formed by or'ing one or more of the values: MSG_OOB process out-of-band data MSG_DONTROUTE bypass routing, use direct interface These flags are unsupported as of ns-3.1.
Parameters
p ns3::Packet to send
flags Socket control flags
Returns
the number of bytes accepted for transmission if no error occurs, and -1 otherwise.
See also
SetSendCallback
Implements ns3::Socket.
Definition at line 260 of file packet-socket.cc.
References ns3::Socket::ERROR_NOTCONN, m_destAddr, m_errno, m_state, NS_LOG_FUNCTION, SendTo(), STATE_BOUND, and STATE_OPEN.
SendTo()
int ns3::PacketSocket::SendTo (Ptr< Packet > p, uint32_t flags, const Address & toAddress) virtual
Send data to a specified peer.
This method has similar semantics to Send () but subclasses may want to provide checks on socket state, so the implementation is pushed to subclasses.
Parameters
p packet to send
flags Socket control flags
toAddress IP Address of remote host
Returns
-1 in case of error or the number of bytes copied in the internal buffer and accepted for transmission.
Implements ns3::Socket.
Definition at line 307 of file packet-socket.cc.
References first::address, ns3::PacketSocketAddress::ConvertFrom(), ns3::Socket::ERROR_AFNOSUPPORT, ns3::Socket::ERROR_BADF, ns3::Socket::ERROR_INVAL, ns3::Socket::ERROR_MSGSIZE, ns3::Socket::ERROR_SHUTDOWN, ns3::Node::GetDevice(), GetMinMtu(), ns3::Node::GetNDevices(), ns3::PacketSocketAddress::GetPhysicalAddress(), ns3::Socket::GetPriority(), ns3::PacketSocketAddress::GetProtocol(), ns3::PacketSocketAddress::GetSingleDevice(), ns3::Packet::GetSize(), GetTxAvailable(), ns3::PacketSocketAddress::IsMatchingType(), ns3::PacketSocketAddress::IsSingleDevice(), m_errno, m_node, m_shutdownSend, m_state, ns3::Socket::NotifyDataSent(), ns3::Socket::NotifySend(), NS_LOG_FUNCTION, NS_LOG_LOGIC, pktSize, ns3::Packet::ReplacePacketTag(), ns3::SocketPriorityTag::SetPriority(), and STATE_CLOSED.
Referenced by Send().
SetAllowBroadcast()
bool ns3::PacketSocket::SetAllowBroadcast (bool allowBroadcast) virtual
Configure whether broadcast datagram transmissions are allowed.
This method corresponds to using setsockopt() SO_BROADCAST of real network or BSD sockets. If set on a socket, this option will enable or disable packets to be transmitted to broadcast destination addresses.
Parameters
allowBroadcast Whether broadcast is allowed
Returns
true if operation succeeds
Implements ns3::Socket.
Definition at line 514 of file packet-socket.cc.
References NS_LOG_FUNCTION.
SetNode()
void ns3::PacketSocket::SetNode (Ptr< Node > node)
Set the associated node.
Parameters
node the node
Definition at line 69 of file packet-socket.cc.
References m_node, and NS_LOG_FUNCTION.
ShutdownRecv()
int ns3::PacketSocket::ShutdownRecv (void) virtual
Returns
zero on success, -1 on failure.
Do not allow any further Recv calls. This method is typically implemented for Tcp sockets by a half close.
Implements ns3::Socket.
Definition at line 186 of file packet-socket.cc.
References ns3::Socket::ERROR_BADF, m_errno, m_shutdownRecv, m_state, NS_LOG_FUNCTION, and STATE_CLOSED.
ShutdownSend()
int ns3::PacketSocket::ShutdownSend (void) virtual
Returns
zero on success, -1 on failure.
Do not allow any further Send calls. This method is typically implemented for Tcp sockets by a half close.
Implements ns3::Socket.
Definition at line 173 of file packet-socket.cc.
References ns3::Socket::ERROR_BADF, m_errno, m_shutdownSend, m_state, NS_LOG_FUNCTION, and STATE_CLOSED.
Member Data Documentation
m_deliveryQueue
std::queue<std::pair<Ptr<Packet>, Address> > ns3::PacketSocket::m_deliveryQueue private
Rx queue.
Definition at line 205 of file packet-socket.h.
Referenced by ForwardUp(), and RecvFrom().
m_destAddr
Address ns3::PacketSocket::m_destAddr private
Default destination address.
Definition at line 203 of file packet-socket.h.
Referenced by Connect(), GetPeerName(), GetTxAvailable(), and Send().
m_device
uint32_t ns3::PacketSocket::m_device private
index of the bound NetDevice
Definition at line 202 of file packet-socket.h.
Referenced by PacketSocket(), DoBind(), DoDispose(), and GetSockName().
m_dropTrace
TracedCallback<Ptr<const Packet> > ns3::PacketSocket::m_dropTrace private
Traced callback: dropped packets.
Definition at line 209 of file packet-socket.h.
Referenced by ForwardUp(), and GetTypeId().
m_errno
enum SocketErrno ns3::PacketSocket::m_errno mutable private
Socket error code.
Definition at line 195 of file packet-socket.h.
Referenced by PacketSocket(), Bind(), Close(), Connect(), DoBind(), GetPeerName(), Listen(), Send(), SendTo(), ShutdownRecv(), and ShutdownSend().
m_isSingleDevice
bool ns3::PacketSocket::m_isSingleDevice private
Is bound to a single netDevice.
Definition at line 201 of file packet-socket.h.
Referenced by PacketSocket(), DoBind(), and GetSockName().
m_node
Ptr<Node> ns3::PacketSocket::m_node private
the associated node
Definition at line 195 of file packet-socket.h.
Referenced by Close(), DoBind(), GetMinMtu(), GetNode(), GetSockName(), SendTo(), and SetNode().
m_protocol
uint16_t ns3::PacketSocket::m_protocol private
Socket protocol.
Definition at line 200 of file packet-socket.h.
Referenced by DoBind(), and GetSockName().
m_rcvBufSize
uint32_t ns3::PacketSocket::m_rcvBufSize private
Rx buffer size [Bytes].
Definition at line 212 of file packet-socket.h.
Referenced by ForwardUp(), and GetTypeId().
m_rxAvailable
uint32_t ns3::PacketSocket::m_rxAvailable private
Rx queue size [Bytes].
Definition at line 206 of file packet-socket.h.
Referenced by ForwardUp(), GetRxAvailable(), and RecvFrom().
m_shutdownRecv
bool ns3::PacketSocket::m_shutdownRecv private
Receive no longer allowed.
Definition at line 198 of file packet-socket.h.
Referenced by PacketSocket(), Close(), ForwardUp(), and ShutdownRecv().
m_shutdownSend
bool ns3::PacketSocket::m_shutdownSend private
Send no longer allowed.
Definition at line 197 of file packet-socket.h.
Referenced by PacketSocket(), Close(), SendTo(), and ShutdownSend().
m_state
enum State ns3::PacketSocket::m_state private
Socket state.
Definition at line 198 of file packet-socket.h.
Referenced by PacketSocket(), Close(), Connect(), DoBind(), GetPeerName(), GetTxAvailable(), Send(), SendTo(), ShutdownRecv(), and ShutdownSend().
The documentation for this class was generated from the following files:
src/network/utils/packet-socket.h
src/network/utils/packet-socket.cc