ns-3: ns3::OnOffHelper Class Reference
ns3::OnOffHelper Class Reference
Applications » OnOffApplication
A helper to make it easier to instantiate an ns3::OnOffApplication on a set of nodes.
#include "on-off-helper.h"
Public Member Functions
OnOffHelper (std::string protocol, Address address)
Create an OnOffHelper to make it easier to work with OnOffApplications.
int64_t AssignStreams (NodeContainer c, int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
ApplicationContainer Install (NodeContainer c) const
Install an ns3::OnOffApplication on each node of the input container configured with all the attributes set with SetAttribute.
ApplicationContainer Install (Ptr< Node > node) const
Install an ns3::OnOffApplication on the node configured with all the attributes set with SetAttribute.
ApplicationContainer Install (std::string nodeName) const
Install an ns3::OnOffApplication on the node configured with all the attributes set with SetAttribute.
void SetAttribute (std::string name, const AttributeValue &value)
Helper function used to set the underlying application attributes.
void SetConstantRate (DataRate dataRate, uint32_t packetSize=512)
Helper function to set a constant rate source.
Private Member Functions
Ptr< Application > InstallPriv (Ptr< Node > node) const
Install an ns3::OnOffApplication on the node configured with all the attributes set with SetAttribute.
Private Attributes
ObjectFactory m_factory
Object factory.
Detailed Description
A helper to make it easier to instantiate an ns3::OnOffApplication on a set of nodes.
Definition at line 42 of file on-off-helper.h.
Constructor & Destructor Documentation
OnOffHelper()
ns3::OnOffHelper::OnOffHelper (std::string protocol, Address address)
Create an OnOffHelper to make it easier to work with OnOffApplications.
Parameters
protocol the name of the protocol to use to send traffic by the applications. This string identifies the socket factory type used to create sockets for the applications. A typical value would be ns3::UdpSocketFactory.
address the address of the remote node to send traffic to.
Definition at line 32 of file on-off-helper.cc.
References first::address, m_factory, ns3::ObjectFactory::Set(), and ns3::ObjectFactory::SetTypeId().
Member Function Documentation
AssignStreams()
int64_t ns3::OnOffHelper::AssignStreams (NodeContainer c, int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned. The Install() method should have previously been called by the user.
Parameters
stream first stream index to use
c NodeContainer of the set of nodes for which the OnOffApplication should be modified to use a fixed stream
Returns
the number of stream indices assigned by this helper
Definition at line 80 of file on-off-helper.cc.
References ns3::NodeContainer::Begin(), ns3::NodeContainer::End(), ns3::Node::GetApplication(), and ns3::Node::GetNApplications().
Install() [1/3]
ApplicationContainer ns3::OnOffHelper::Install (NodeContainer c) const
Install an ns3::OnOffApplication on each node of the input container configured with all the attributes set with SetAttribute.
Parameters
c NodeContainer of the set of nodes on which an OnOffApplication will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 59 of file on-off-helper.cc.
References ns3::ApplicationContainer::Add(), ns3::NodeContainer::Begin(), ns3::NodeContainer::End(), and InstallPriv().
Referenced by Experiment::ApplicationSetup(), BuildAppsTest(), CreateOnOffFlow(), BriteTopologyFunctionTestCase::DoRun(), CsmaBridgeTestCase::DoRun(), CsmaBroadcastTestCase::DoRun(), CsmaMulticastTestCase::DoRun(), CsmaOneSubnetTestCase::DoRun(), CsmaPacketSocketTestCase::DoRun(), CsmaPingTestCase::DoRun(), CsmaRawIpSocketTestCase::DoRun(), CsmaStarTestCase::DoRun(), Ns3TcpInteroperabilityTestCase::DoRun(), WifiAcMappingTest::DoRun(), WifiMsduAggregatorThroughputTest::DoRun(), experiment(), DsdvManetExample::InstallApplications(), Experiment::Run(), RoutingExperiment::Run(), NetAnimExperiment::Run(), and RoutingHelper::SetupRoutingMessages().
Install() [2/3]
ApplicationContainer ns3::OnOffHelper::Install (Ptr< Node > node) const
Install an ns3::OnOffApplication on the node configured with all the attributes set with SetAttribute.
Parameters
node The node on which an OnOffApplication will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 46 of file on-off-helper.cc.
References InstallPriv().
Install() [3/3]
ApplicationContainer ns3::OnOffHelper::Install (std::string nodeName) const
Install an ns3::OnOffApplication on the node configured with all the attributes set with SetAttribute.
Parameters
nodeName The node on which an OnOffApplication will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 52 of file on-off-helper.cc.
References InstallPriv().
InstallPriv()
Ptr< Application > ns3::OnOffHelper::InstallPriv (Ptr< Node > node) const private
Install an ns3::OnOffApplication on the node configured with all the attributes set with SetAttribute.
Parameters
node The node on which an OnOffApplication will be installed.
Returns
Ptr to the application installed.
Definition at line 71 of file on-off-helper.cc.
References ns3::Node::AddApplication(), ns3::ObjectFactory::Create(), and m_factory.
Referenced by Install().
SetAttribute()
void ns3::OnOffHelper::SetAttribute (std::string name, const AttributeValue & value)
Helper function used to set the underlying application attributes.
Parameters
name the name of the application attribute to set
value the value of the application attribute to set
Definition at line 40 of file on-off-helper.cc.
References m_factory, and ns3::ObjectFactory::Set().
Referenced by Experiment::ApplicationSetup(), BuildAppsTest(), CreateOnOffFlow(), BriteTopologyFunctionTestCase::DoRun(), CsmaOneSubnetTestCase::DoRun(), CsmaPacketSocketTestCase::DoRun(), CsmaStarTestCase::DoRun(), Ns3TcpInteroperabilityTestCase::DoRun(), WifiMsduAggregatorThroughputTest::DoRun(), experiment(), DsdvManetExample::InstallApplications(), Experiment::Run(), RoutingExperiment::Run(), NetAnimExperiment::Run(), and RoutingHelper::SetupRoutingMessages().
SetConstantRate()
void ns3::OnOffHelper::SetConstantRate (DataRate dataRate, uint32_t packetSize = 512)
Helper function to set a constant rate source.
Equivalent to setting the attributes OnTime to constant 1000 seconds, OffTime to constant 0 seconds, and the DataRate and PacketSize set accordingly
Parameters
dataRate DataRate object for the sending rate
packetSize size in bytes of the packet payloads generated
Definition at line 100 of file on-off-helper.cc.
References m_factory, packetSize, and ns3::ObjectFactory::Set().
Referenced by Experiment::ApplicationSetup(), CsmaBridgeTestCase::DoRun(), CsmaBroadcastTestCase::DoRun(), CsmaMulticastTestCase::DoRun(), CsmaOneSubnetTestCase::DoRun(), CsmaPacketSocketTestCase::DoRun(), CsmaPingTestCase::DoRun(), CsmaRawIpSocketTestCase::DoRun(), CsmaStarTestCase::DoRun(), WifiAcMappingTest::DoRun(), WifiMsduAggregatorThroughputTest::DoRun(), and Experiment::Run().
Member Data Documentation
m_factory
ObjectFactory ns3::OnOffHelper::m_factory private
Object factory.
Definition at line 126 of file on-off-helper.h.
Referenced by OnOffHelper(), InstallPriv(), SetAttribute(), and SetConstantRate().
The documentation for this class was generated from the following files:
src/applications/helper/on-off-helper.h
src/applications/helper/on-off-helper.cc