ns-3: ns3::JakesPropagationLossModel Class Reference
ns3::JakesPropagationLossModel Class Reference
Propagation Models
a Jakes narrowband propagation model.
#include "jakes-propagation-loss-model.h"
Public Member Functions
JakesPropagationLossModel ()
virtual ~JakesPropagationLossModel ()
Public Member Functions inherited from ns3::PropagationLossModel
PropagationLossModel ()
virtual ~PropagationLossModel ()
int64_t AssignStreams (int64_t stream)
If this loss model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
double CalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account all the PropagationLossModel(s) chained to the current one.
Ptr< PropagationLossModel > GetNext ()
Gets the next PropagationLossModel in the chain of loss models that act on the signal.
void SetNext (Ptr< PropagationLossModel > next)
Enables a chain of loss models to act on the signal.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::PropagationLossModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
JakesPropagationLossModel (const JakesPropagationLossModel &)
Copy constructor.
virtual int64_t DoAssignStreams (int64_t stream)
Subclasses must implement this; those not using random variables can return zero.
double DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account only the particular PropagationLossModel.
Ptr< UniformRandomVariable > GetUniformRandomVariable () const
Get the underlying RNG stream.
JakesPropagationLossModel & operator= (const JakesPropagationLossModel &)
Copy constructor.
Private Attributes
PropagationCache< JakesProcess > m_propagationCache
Propagation cache.
Ptr< UniformRandomVariable > m_uniformVariable
random stream
Friends
class JakesProcess
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
a Jakes narrowband propagation model.
Symmetrical cache for JakesProcess
Config Paths
ns3::JakesPropagationLossModel is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::SpectrumChannel/PropagationLossModel/$ns3::JakesPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::YansWifiChannel/PropagationLossModel/$ns3::JakesPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::LrWpanNetDevice/Channel/PropagationLossModel/$ns3::JakesPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::SpectrumChannel/PropagationLossModel/$ns3::JakesPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::YansWifiChannel/PropagationLossModel/$ns3::JakesPropagationLossModel"
"/ChannelList/[i]/$ns3::SpectrumChannel/PropagationLossModel/$ns3::JakesPropagationLossModel"
"/ChannelList/[i]/$ns3::YansWifiChannel/PropagationLossModel/$ns3::JakesPropagationLossModel"
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 72 bytes (on a 64-bit architecture).
Definition at line 36 of file jakes-propagation-loss-model.h.
Constructor & Destructor Documentation
JakesPropagationLossModel() [1/2]
ns3::JakesPropagationLossModel::JakesPropagationLossModel ()
Definition at line 33 of file jakes-propagation-loss-model.cc.
References m_uniformVariable, and ns3::ObjectBase::SetAttribute().
~JakesPropagationLossModel()
ns3::JakesPropagationLossModel::~JakesPropagationLossModel () virtual
Definition at line 40 of file jakes-propagation-loss-model.cc.
JakesPropagationLossModel() [2/2]
ns3::JakesPropagationLossModel::JakesPropagationLossModel (const JakesPropagationLossModel &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Member Function Documentation
DoAssignStreams()
int64_t ns3::JakesPropagationLossModel::DoAssignStreams (int64_t stream) private virtual
Subclasses must implement this; those not using random variables can return zero.
Implements ns3::PropagationLossModel.
Definition at line 76 of file jakes-propagation-loss-model.cc.
References m_uniformVariable, and ns3::RandomVariableStream::SetStream().
DoCalcRxPower()
double ns3::JakesPropagationLossModel::DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const private virtual
Returns the Rx Power taking into account only the particular PropagationLossModel.
Parameters
txPowerDbm current transmission power (in dBm)
a the mobility model of the source
b the mobility model of the destination
Returns
the reception power after adding/multiplying propagation loss (in dBm)
Spectrum model uid is not used in PropagationLossModel
Spectrum model uid is not used in PropagationLossModel
Implements ns3::PropagationLossModel.
Definition at line 55 of file jakes-propagation-loss-model.cc.
References m_propagationCache.
GetTypeId()
TypeId ns3::JakesPropagationLossModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 44 of file jakes-propagation-loss-model.cc.
References ns3::TypeId::SetParent().
GetUniformRandomVariable()
Ptr< UniformRandomVariable > ns3::JakesPropagationLossModel::GetUniformRandomVariable () const private
Get the underlying RNG stream.
Returns
the RNG stream
Definition at line 70 of file jakes-propagation-loss-model.cc.
References m_uniformVariable.
operator=()
JakesPropagationLossModel& ns3::JakesPropagationLossModel::operator= (const JakesPropagationLossModel &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Returns
Friends And Related Function Documentation
JakesProcess
friend class JakesProcess friend
Definition at line 48 of file jakes-propagation-loss-model.h.
Member Data Documentation
m_propagationCache
PropagationCache<JakesProcess> ns3::JakesPropagationLossModel::m_propagationCache mutable private
Propagation cache.
Definition at line 75 of file jakes-propagation-loss-model.h.
Referenced by DoCalcRxPower().
m_uniformVariable
Ptr<UniformRandomVariable> ns3::JakesPropagationLossModel::m_uniformVariable private
random stream
Definition at line 74 of file jakes-propagation-loss-model.h.
Referenced by JakesPropagationLossModel(), DoAssignStreams(), and GetUniformRandomVariable().
The documentation for this class was generated from the following files:
src/propagation/model/jakes-propagation-loss-model.h
src/propagation/model/jakes-propagation-loss-model.cc