ns-3: PbbTestCase Class Reference
PbbTestCase Class Reference
Network » Network module unit tests | Test suites
PacketBb TestCase.
Public Member Functions
PbbTestCase (std::string name, Ptr< PbbPacket > packet, uint8_t *buffer, uint32_t size)
Constructor.
virtual ~PbbTestCase (void)
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Private Member Functions
void TestDeserialize (void)
Deserialization.
void TestSerialize (void)
Serialization.
Private Attributes
Buffer m_refBuffer
Reference buffer.
Ptr< PbbPacket > m_refPacket
Reference packet.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Detailed Description
PacketBb TestCase.
Definition at line 38 of file packetbb-test-suite.cc.
Constructor & Destructor Documentation
PbbTestCase()
PbbTestCase::PbbTestCase (std::string name, Ptr< PbbPacket > packet, uint8_t * buffer, uint32_t size)
Constructor.
Parameters
name Test name.
packet Packet to test.
buffer Buffer to test.
size Buffer size.
Definition at line 65 of file packetbb-test-suite.cc.
References ns3::Buffer::AddAtStart(), ns3::Buffer::Begin(), m_refBuffer, m_refPacket, and ns3::Buffer::Iterator::Write().
~PbbTestCase()
PbbTestCase::~PbbTestCase (void) virtual
Definition at line 75 of file packetbb-test-suite.cc.
Member Function Documentation
DoRun()
void PbbTestCase::DoRun (void) protected virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 81 of file packetbb-test-suite.cc.
References TestDeserialize(), and TestSerialize().
TestDeserialize()
void PbbTestCase::TestDeserialize (void) private
Deserialization.
Definition at line 105 of file packetbb-test-suite.cc.
References ns3::Buffer::Begin(), ns3::PbbPacket::Deserialize(), ns3::Buffer::GetSize(), m_refBuffer, m_refPacket, and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
TestSerialize()
void PbbTestCase::TestSerialize (void) private
Serialization.
Definition at line 88 of file packetbb-test-suite.cc.
References ns3::Buffer::AddAtStart(), ns3::Buffer::Begin(), ns3::PbbPacket::GetSerializedSize(), ns3::Buffer::GetSize(), m_refBuffer, m_refPacket, NS_TEST_ASSERT_MSG_EQ, ns3::Buffer::PeekData(), and ns3::PbbPacket::Serialize().
Referenced by DoRun().
Member Data Documentation
m_refBuffer
Buffer PbbTestCase::m_refBuffer private
Reference buffer.
Definition at line 62 of file packetbb-test-suite.cc.
Referenced by PbbTestCase(), TestDeserialize(), and TestSerialize().
m_refPacket
Ptr<PbbPacket> PbbTestCase::m_refPacket private
Reference packet.
Definition at line 61 of file packetbb-test-suite.cc.
Referenced by PbbTestCase(), TestDeserialize(), and TestSerialize().
The documentation for this class was generated from the following file:
src/network/test/packetbb-test-suite.cc