ns-3: ns3::SteadyStateRandomWaypointMobilityModel Class Reference
ns3::SteadyStateRandomWaypointMobilityModel Class Reference
Mobility
Steady-state random waypoint mobility model.
#include "steady-state-random-waypoint-mobility-model.h"
Public Member Functions
SteadyStateRandomWaypointMobilityModel ()
Public Member Functions inherited from ns3::MobilityModel
MobilityModel ()
virtual ~MobilityModel ()=0
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
double GetDistanceFrom (Ptr< const MobilityModel > position) const
Vector GetPosition (void) const
double GetRelativeSpeed (Ptr< const MobilityModel > other) const
Vector GetVelocity (void) const
void SetPosition (const Vector &position)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type with the TypeId system.
Static Public Member Functions inherited from ns3::MobilityModel
static TypeId GetTypeId (void)
Register this type with the TypeId system.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::MobilityModel
void NotifyCourseChange (void) const
Must be invoked by subclasses when the course of the position changes to notify course change listeners.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void BeginWalk (void)
Start a motion period and schedule the ending of the motion.
virtual int64_t DoAssignStreams (int64_t)
The default implementation does nothing but return the passed-in parameter.
virtual Vector DoGetPosition (void) const
virtual Vector DoGetVelocity (void) const
void DoInitializePrivate (void)
Configure random variables based on attributes; calculate the steady state probability that node is initially paused; schedule either end of pause time or initial motion of the node.
virtual void DoSetPosition (const Vector &position)
void Start (void)
Start a pause period and schedule the ending of the pause.
void SteadyStateBeginWalk (const Vector &destination)
Use provided destination to calculate travel delay, and schedule a Start() event at that time.
Private Attributes
bool alreadyStarted
flag for starting state
EventId m_event
current event ID
ConstantVelocityHelper m_helper
helper for velocity computations
double m_maxPause
maximum pause value (s)
double m_maxSpeed
maximum speed value (m/s)
double m_maxX
maximum x value of traveling region (m)
double m_maxY
maximum y value of traveling region (m)
double m_minPause
minimum pause value (s)
double m_minSpeed
minimum speed value (m/s)
double m_minX
minimum x value of traveling region (m)
double m_minY
minimum y value of traveling region (m)
Ptr< UniformRandomVariable > m_pause
random variable for pause values
Ptr< RandomBoxPositionAllocator > m_position
position allocator
Ptr< UniformRandomVariable > m_speed
random variable for speed values
Ptr< UniformRandomVariable > m_u_r
rv used in step 5 of algorithm
Ptr< UniformRandomVariable > m_x
rv used for position allocator
Ptr< UniformRandomVariable > m_x1_r
rv used in rejection sampling phase
Ptr< UniformRandomVariable > m_x2_r
rv used in rejection sampling phase
Ptr< UniformRandomVariable > m_y
rv used for position allocator
Ptr< UniformRandomVariable > m_y1_r
rv used in rejection sampling phase
Ptr< UniformRandomVariable > m_y2_r
rv used in rejection sampling phase
double m_z
z value of traveling region
Additional Inherited Members
Public Types inherited from ns3::MobilityModel
typedef void(* TracedCallback) (Ptr< const MobilityModel > model)
TracedCallback signature.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Steady-state random waypoint mobility model.
This model based on random waypoint mobility (RWM) model for case when speed, pause and position are uniformly distributed random variables. The difference is that the initial values of this parameters are not from uniform distribution but from stationary distribution of RWM model. The implementation of this model is 2D-specific and with nonzero nodes speeds. In the 3D ns-3 coordinate system, the momement occurs on the plane, where is a constant which can be configured using the Z attribute.
Based on NS-2 implementation by Toilers Research Group – Colorado School of Mines (http://toilers.mines.edu). The papers related to this code are: W. Navidi and T. Camp, Stationary Distributions for the Random Waypoint Mobility Model, IEEE Transactions on Mobile Computing, vol. 3, no. 1, pp. 99-108, January-March 2004. W. Navidi, T. Camp, and N. Bauer, Improving the Accuracy of Random Waypoint Simulations Through Steady-State Initialization, Proceedings of the 15th International Conference on Modeling and Simulation (MS '04), pp. 319-326, March 2004.
Config Paths
ns3::SteadyStateRandomWaypointMobilityModel is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::MobilityModel/$ns3::SteadyStateRandomWaypointMobilityModel"
Attributes
MinSpeed: Minimum speed value, [m/s]
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0.3
Flags: construct write read
MaxSpeed: Maximum speed value, [m/s]
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0.7
Flags: construct write read
MinPause: Minimum pause value, [s]
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0
Flags: construct write read
MaxPause: Maximum pause value, [s]
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0
Flags: construct write read
MinX: Minimum X value of traveling region, [m]
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 1
Flags: construct write read
MaxX: Maximum X value of traveling region, [m]
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 1
Flags: construct write read
MinY: Minimum Y value of traveling region, [m]
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 1
Flags: construct write read
MaxY: Maximum Y value of traveling region, [m]
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 1
Flags: construct write read
Z: Z value of traveling region (fixed), [m]
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0
Flags: construct write read
Attributes defined in parent class ns3::MobilityModel
Position: The current position of the mobility model.
Set with class: Vector3DValue
Underlying type: Vector3D
Flags: write read
Velocity: The current velocity of the mobility model.
Set with class: Vector3DValue
Underlying type: Vector3D
Flags: read
No TraceSources are defined for this type.
TraceSources defined in parent class ns3::MobilityModel
CourseChange: The value of the position and/or velocity vector changed
Callback signature: ns3::MobilityModel::TracedCallback
Size of this type is 304 bytes (on a 64-bit architecture).
Definition at line 55 of file steady-state-random-waypoint-mobility-model.h.
Constructor & Destructor Documentation
SteadyStateRandomWaypointMobilityModel()
ns3::SteadyStateRandomWaypointMobilityModel::SteadyStateRandomWaypointMobilityModel ()
Definition at line 86 of file steady-state-random-waypoint-mobility-model.cc.
References m_pause, m_position, m_speed, m_u_r, m_x, m_x1_r, m_x2_r, m_y, m_y1_r, and m_y2_r.
Member Function Documentation
BeginWalk()
void ns3::SteadyStateRandomWaypointMobilityModel::BeginWalk (void) private
Start a motion period and schedule the ending of the motion.
Definition at line 233 of file steady-state-random-waypoint-mobility-model.cc.
References ns3::CalculateDistance(), ns3::ConstantVelocityHelper::GetCurrentPosition(), ns3::UniformRandomVariable::GetValue(), m_event, m_helper, m_maxX, m_maxY, m_minX, m_minY, m_position, m_speed, ns3::MobilityModel::NotifyCourseChange(), NS_ASSERT, ns3::Simulator::Schedule(), ns3::Seconds(), ns3::ConstantVelocityHelper::SetVelocity(), Start(), ns3::ConstantVelocityHelper::Unpause(), and ns3::ConstantVelocityHelper::Update().
Referenced by DoInitializePrivate(), and Start().
DoAssignStreams()
int64_t ns3::SteadyStateRandomWaypointMobilityModel::DoAssignStreams (int64_t start) private virtual
The default implementation does nothing but return the passed-in parameter.
Subclasses using random variables are expected to override this.
Parameters
start starting stream index
Returns
the number of streams used
Reimplemented from ns3::MobilityModel.
Definition at line 286 of file steady-state-random-waypoint-mobility-model.cc.
References m_pause, m_position, m_speed, m_u_r, m_x, m_x1_r, m_x2_r, m_y, m_y1_r, m_y2_r, and ns3::RandomVariableStream::SetStream().
DoGetPosition()
Vector ns3::SteadyStateRandomWaypointMobilityModel::DoGetPosition (void) const private virtual
Returns
the current position.
Concrete subclasses of this base class must implement this method.
Implements ns3::MobilityModel.
Definition at line 265 of file steady-state-random-waypoint-mobility-model.cc.
References ns3::ConstantVelocityHelper::GetCurrentPosition(), m_helper, and ns3::ConstantVelocityHelper::Update().
DoGetVelocity()
Vector ns3::SteadyStateRandomWaypointMobilityModel::DoGetVelocity (void) const private virtual
Returns
the current velocity.
Concrete subclasses of this base class must implement this method.
Implements ns3::MobilityModel.
Definition at line 281 of file steady-state-random-waypoint-mobility-model.cc.
References ns3::ConstantVelocityHelper::GetVelocity(), and m_helper.
DoInitialize()
void ns3::SteadyStateRandomWaypointMobilityModel::DoInitialize (void) protected virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 102 of file steady-state-random-waypoint-mobility-model.cc.
References ns3::Object::DoInitialize(), and DoInitializePrivate().
DoInitializePrivate()
void ns3::SteadyStateRandomWaypointMobilityModel::DoInitializePrivate (void) private
Configure random variables based on attributes; calculate the steady state probability that node is initially paused; schedule either end of pause time or initial motion of the node.
Definition at line 109 of file steady-state-random-waypoint-mobility-model.cc.
References alreadyStarted, BeginWalk(), ns3::UniformRandomVariable::GetValue(), ns3::EventId::IsRunning(), m_event, m_helper, m_maxPause, m_maxSpeed, m_maxX, m_maxY, m_minPause, m_minSpeed, m_minX, m_minY, m_pause, m_position, m_speed, m_u_r, m_x, m_x1_r, m_x2_r, m_y, m_y1_r, m_y2_r, m_z, ns3::MobilityModel::NotifyCourseChange(), NS_ASSERT, ns3::ConstantVelocityHelper::Pause(), ns3::Simulator::Schedule(), ns3::Simulator::ScheduleNow(), ns3::Seconds(), ns3::ObjectBase::SetAttribute(), ns3::ConstantVelocityHelper::SetPosition(), SteadyStateBeginWalk(), and ns3::ConstantVelocityHelper::Update().
Referenced by DoInitialize().
DoSetPosition()
void ns3::SteadyStateRandomWaypointMobilityModel::DoSetPosition (const Vector & position) private virtual
Parameters
position the position to set.
Concrete subclasses of this base class must implement this method.
Implements ns3::MobilityModel.
Definition at line 271 of file steady-state-random-waypoint-mobility-model.cc.
References alreadyStarted, ns3::EventId::Cancel(), m_event, m_helper, ns3::Simulator::ScheduleNow(), ns3::ConstantVelocityHelper::SetPosition(), and Start().
GetTypeId()
TypeId ns3::SteadyStateRandomWaypointMobilityModel::GetTypeId (void) static
Register this type with the TypeId system.
Returns
the object TypeId
Definition at line 31 of file steady-state-random-waypoint-mobility-model.cc.
References m_maxPause, m_maxSpeed, m_maxX, m_maxY, m_minPause, m_minSpeed, m_minX, m_minY, m_z, ns3::MakeDoubleAccessor(), and ns3::TypeId::SetParent().
Start()
void ns3::SteadyStateRandomWaypointMobilityModel::Start (void) private
Start a pause period and schedule the ending of the pause.
Definition at line 255 of file steady-state-random-waypoint-mobility-model.cc.
References BeginWalk(), ns3::UniformRandomVariable::GetValue(), m_event, m_helper, m_pause, ns3::MobilityModel::NotifyCourseChange(), ns3::ConstantVelocityHelper::Pause(), ns3::Simulator::Schedule(), ns3::Seconds(), and ns3::ConstantVelocityHelper::Update().
Referenced by BeginWalk(), DoSetPosition(), and SteadyStateBeginWalk().
SteadyStateBeginWalk()
void ns3::SteadyStateRandomWaypointMobilityModel::SteadyStateBeginWalk (const Vector & destination) private
Use provided destination to calculate travel delay, and schedule a Start() event at that time.
Parameters
destination the destination to move to
Definition at line 209 of file steady-state-random-waypoint-mobility-model.cc.
References ns3::CalculateDistance(), ns3::ConstantVelocityHelper::GetCurrentPosition(), ns3::UniformRandomVariable::GetValue(), m_event, m_helper, m_maxSpeed, m_maxX, m_maxY, m_minSpeed, m_minX, m_minY, m_u_r, ns3::MobilityModel::NotifyCourseChange(), NS_ASSERT, ns3::Simulator::Schedule(), ns3::Seconds(), ns3::ConstantVelocityHelper::SetVelocity(), Start(), ns3::ConstantVelocityHelper::Unpause(), and ns3::ConstantVelocityHelper::Update().
Referenced by DoInitializePrivate().
Member Data Documentation
alreadyStarted
bool ns3::SteadyStateRandomWaypointMobilityModel::alreadyStarted private
flag for starting state
Definition at line 106 of file steady-state-random-waypoint-mobility-model.h.
Referenced by DoInitializePrivate(), and DoSetPosition().
m_event
EventId ns3::SteadyStateRandomWaypointMobilityModel::m_event private
current event ID
Definition at line 105 of file steady-state-random-waypoint-mobility-model.h.
Referenced by BeginWalk(), DoInitializePrivate(), DoSetPosition(), Start(), and SteadyStateBeginWalk().
m_helper
ConstantVelocityHelper ns3::SteadyStateRandomWaypointMobilityModel::m_helper private
helper for velocity computations
Definition at line 92 of file steady-state-random-waypoint-mobility-model.h.
Referenced by BeginWalk(), DoGetPosition(), DoGetVelocity(), DoInitializePrivate(), DoSetPosition(), Start(), and SteadyStateBeginWalk().
m_maxPause
double ns3::SteadyStateRandomWaypointMobilityModel::m_maxPause private
maximum pause value (s)
Definition at line 103 of file steady-state-random-waypoint-mobility-model.h.
Referenced by DoInitializePrivate(), and GetTypeId().
m_maxSpeed
double ns3::SteadyStateRandomWaypointMobilityModel::m_maxSpeed private
maximum speed value (m/s)
Definition at line 93 of file steady-state-random-waypoint-mobility-model.h.
Referenced by DoInitializePrivate(), GetTypeId(), and SteadyStateBeginWalk().
m_maxX
double ns3::SteadyStateRandomWaypointMobilityModel::m_maxX private
maximum x value of traveling region (m)
Definition at line 97 of file steady-state-random-waypoint-mobility-model.h.
Referenced by BeginWalk(), DoInitializePrivate(), GetTypeId(), and SteadyStateBeginWalk().
m_maxY
double ns3::SteadyStateRandomWaypointMobilityModel::m_maxY private
maximum y value of traveling region (m)
Definition at line 99 of file steady-state-random-waypoint-mobility-model.h.
Referenced by BeginWalk(), DoInitializePrivate(), GetTypeId(), and SteadyStateBeginWalk().
m_minPause
double ns3::SteadyStateRandomWaypointMobilityModel::m_minPause private
minimum pause value (s)
Definition at line 102 of file steady-state-random-waypoint-mobility-model.h.
Referenced by DoInitializePrivate(), and GetTypeId().
m_minSpeed
double ns3::SteadyStateRandomWaypointMobilityModel::m_minSpeed private
minimum speed value (m/s)
Definition at line 94 of file steady-state-random-waypoint-mobility-model.h.
Referenced by DoInitializePrivate(), GetTypeId(), and SteadyStateBeginWalk().
m_minX
double ns3::SteadyStateRandomWaypointMobilityModel::m_minX private
minimum x value of traveling region (m)
Definition at line 96 of file steady-state-random-waypoint-mobility-model.h.
Referenced by BeginWalk(), DoInitializePrivate(), GetTypeId(), and SteadyStateBeginWalk().
m_minY
double ns3::SteadyStateRandomWaypointMobilityModel::m_minY private
minimum y value of traveling region (m)
Definition at line 98 of file steady-state-random-waypoint-mobility-model.h.
Referenced by BeginWalk(), DoInitializePrivate(), GetTypeId(), and SteadyStateBeginWalk().
m_pause
Ptr<UniformRandomVariable> ns3::SteadyStateRandomWaypointMobilityModel::m_pause private
random variable for pause values
Definition at line 104 of file steady-state-random-waypoint-mobility-model.h.
Referenced by SteadyStateRandomWaypointMobilityModel(), DoAssignStreams(), DoInitializePrivate(), and Start().
m_position
Ptr<RandomBoxPositionAllocator> ns3::SteadyStateRandomWaypointMobilityModel::m_position private
position allocator
Definition at line 101 of file steady-state-random-waypoint-mobility-model.h.
Referenced by SteadyStateRandomWaypointMobilityModel(), BeginWalk(), DoAssignStreams(), and DoInitializePrivate().
m_speed
Ptr<UniformRandomVariable> ns3::SteadyStateRandomWaypointMobilityModel::m_speed private
random variable for speed values
Definition at line 95 of file steady-state-random-waypoint-mobility-model.h.
Referenced by SteadyStateRandomWaypointMobilityModel(), BeginWalk(), DoAssignStreams(), and DoInitializePrivate().
m_u_r
Ptr<UniformRandomVariable> ns3::SteadyStateRandomWaypointMobilityModel::m_u_r private
rv used in step 5 of algorithm
Definition at line 111 of file steady-state-random-waypoint-mobility-model.h.
Referenced by SteadyStateRandomWaypointMobilityModel(), DoAssignStreams(), DoInitializePrivate(), and SteadyStateBeginWalk().
m_x
Ptr<UniformRandomVariable> ns3::SteadyStateRandomWaypointMobilityModel::m_x private
rv used for position allocator
Definition at line 112 of file steady-state-random-waypoint-mobility-model.h.
Referenced by SteadyStateRandomWaypointMobilityModel(), DoAssignStreams(), and DoInitializePrivate().
m_x1_r
Ptr<UniformRandomVariable> ns3::SteadyStateRandomWaypointMobilityModel::m_x1_r private
rv used in rejection sampling phase
Definition at line 107 of file steady-state-random-waypoint-mobility-model.h.
Referenced by SteadyStateRandomWaypointMobilityModel(), DoAssignStreams(), and DoInitializePrivate().
m_x2_r
Ptr<UniformRandomVariable> ns3::SteadyStateRandomWaypointMobilityModel::m_x2_r private
rv used in rejection sampling phase
Definition at line 109 of file steady-state-random-waypoint-mobility-model.h.
Referenced by SteadyStateRandomWaypointMobilityModel(), DoAssignStreams(), and DoInitializePrivate().
m_y
Ptr<UniformRandomVariable> ns3::SteadyStateRandomWaypointMobilityModel::m_y private
rv used for position allocator
Definition at line 113 of file steady-state-random-waypoint-mobility-model.h.
Referenced by SteadyStateRandomWaypointMobilityModel(), DoAssignStreams(), and DoInitializePrivate().
m_y1_r
Ptr<UniformRandomVariable> ns3::SteadyStateRandomWaypointMobilityModel::m_y1_r private
rv used in rejection sampling phase
Definition at line 108 of file steady-state-random-waypoint-mobility-model.h.
Referenced by SteadyStateRandomWaypointMobilityModel(), DoAssignStreams(), and DoInitializePrivate().
m_y2_r
Ptr<UniformRandomVariable> ns3::SteadyStateRandomWaypointMobilityModel::m_y2_r private
rv used in rejection sampling phase
Definition at line 110 of file steady-state-random-waypoint-mobility-model.h.
Referenced by SteadyStateRandomWaypointMobilityModel(), DoAssignStreams(), and DoInitializePrivate().
m_z
double ns3::SteadyStateRandomWaypointMobilityModel::m_z private
z value of traveling region
Definition at line 100 of file steady-state-random-waypoint-mobility-model.h.
Referenced by DoInitializePrivate(), and GetTypeId().
The documentation for this class was generated from the following files:
src/mobility/model/steady-state-random-waypoint-mobility-model.h
src/mobility/model/steady-state-random-waypoint-mobility-model.cc