ns-3: ns3::EnumValue Class Reference
ns3::EnumValue Class Reference
Enum Attribute
Hold variables of type enum.
#include "enum.h"
Public Member Functions
EnumValue ()
EnumValue (int value)
Construct from an explicit value.
virtual Ptr< AttributeValue > Copy (void) const
virtual bool DeserializeFromString (std::string value, Ptr< const AttributeChecker > checker)
int Get (void) const
template<typename T >
bool GetAccessor (T &value) const
Access the Enum value as type T.
virtual std::string SerializeToString (Ptr< const AttributeChecker > checker) const
void Set (int value)
Set the value.
Public Member Functions inherited from ns3::AttributeValue
AttributeValue ()
virtual ~AttributeValue ()
Public Member Functions inherited from ns3::SimpleRefCount< AttributeValue >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
int m_value
The stored integer value.
Detailed Description
Hold variables of type enum.
AttributeValue implementation for Enum.
This class can be used to hold variables of any kind of enum.
This is often used with ObjectFactory and Config to bind the value of a particular enum to an Attribute or Config name. For example,
Ptr<RateErrorModel> model = CreateObjectWithAttributes<RateErrorModel> (
  "ErrorRate", DoubleValue (0.05),
  "ErrorUnit", EnumValue (RateErrorModel::ERROR_UNIT_PACKET));
Config::SetDefault ("ns3::RipNg::SplitHorizon",
                    EnumValue (RipNg::NO_SPLIT_HORIZON));
See also
AttributeValue
Definition at line 54 of file enum.h.
Constructor & Destructor Documentation
EnumValue() [1/2]
ns3::EnumValue::EnumValue ()
Definition at line 36 of file enum.cc.
References NS_LOG_FUNCTION.
EnumValue() [2/2]
ns3::EnumValue::EnumValue (int value)
Construct from an explicit value.
Parameters
[in] value The value to begin with.
Definition at line 41 of file enum.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Copy()
Ptr< AttributeValue > ns3::EnumValue::Copy (void) const virtual
Returns
a deep copy of this class, wrapped into an Attribute object.
Implements ns3::AttributeValue.
Definition at line 59 of file enum.cc.
References NS_LOG_FUNCTION.
DeserializeFromString()
bool ns3::EnumValue::DeserializeFromString (std::string value, Ptr< const AttributeChecker > checker) virtual
Parameters
[in] value A string representation of the value
[in] checker A pointer to the checker associated to the attribute.
Returns
true if the input string was correctly-formatted and could be successfully deserialized, false otherwise.
Upon return of this function, this AttributeValue instance contains the deserialized value. In most cases, this method will not make any use of the checker argument. However, in a very limited set of cases, the checker argument is needed to perform proper serialization. A nice example of code which needs it is the EnumValue::SerializeToString code.
Implements ns3::AttributeValue.
Definition at line 74 of file enum.cc.
References ns3::EnumChecker::GetValue(), m_value, NS_ASSERT, NS_LOG_FUNCTION, and ns3::PeekPointer().
Get()
int ns3::EnumValue::Get (void) const
Returns
The Enum value.
Definition at line 53 of file enum.cc.
References m_value, and NS_LOG_FUNCTION.
Referenced by ns3::EnumChecker::Check(), and ns3::LteHelper::InstallSingleEnbDevice().
GetAccessor()
template<typename T > bool ns3::EnumValue::GetAccessor (T & value) const
Access the Enum value as type T.
Template Parameters
T [explicit] The type to cast to.
Parameters
[out] value The Enum value, as type T.
Returns
true.
Definition at line 79 of file enum.h.
References m_value.
SerializeToString()
std::string ns3::EnumValue::SerializeToString (Ptr< const AttributeChecker > checker) const virtual
Parameters
[in] checker The checker associated to the attribute
Returns
A string representation of this value.
In most cases, this method will not make any use of the checker argument. However, in a very limited set of cases, the checker argument is needed to perform proper serialization. A nice example of code which needs it is the EnumValue::SerializeToString code.
Implements ns3::AttributeValue.
Definition at line 65 of file enum.cc.
References ns3::EnumChecker::GetName(), m_value, NS_ASSERT, NS_LOG_FUNCTION, and ns3::PeekPointer().
Set()
void ns3::EnumValue::Set (int value)
Set the value.
Parameters
[in] value The value to adopt.
Definition at line 47 of file enum.cc.
References m_value, and NS_LOG_FUNCTION.
Member Data Documentation
m_value
int ns3::EnumValue::m_value private
The stored integer value.
The stored Enum instance.
Definition at line 74 of file enum.h.
Referenced by DeserializeFromString(), Get(), GetAccessor(), SerializeToString(), and Set().
The documentation for this class was generated from the following files:
src/core/model/enum.h
src/core/model/enum.cc
doc/introspected-doxygen.h