ns-3: ns3::Ptr< T > Class Template Reference
ns3::Ptr< T > Class Template Reference
Core » Smart Pointer
Smart pointer class similar to boost::intrusive_ptr.
#include "ptr.h"
Classes
class Tester
Helper to test for null pointer.
Public Member Functions
Ptr ()
Create an empty smart pointer.
Ptr (Ptr const &o)
Copy by referencing the same underlying object.
template<typename U >
Ptr (Ptr< U > const &o)
Copy, removing const qualifier.
Ptr (T *ptr)
Create a smart pointer which points to the object pointed to by the input raw pointer ptr.
Ptr (T *ptr, bool ref)
Create a smart pointer which points to the object pointed to by the input raw pointer ptr.
~Ptr ()
Destructor.
operator Tester * () const
Test for non-NULL pointer.
bool operator! ()
Test for NULL pointer.
T & operator* ()
A dereference.
T & operator* () const
A const dereference.
T * operator-> ()
An lvalue member access.
T * operator-> () const
An rvalue member access.
Ptr< T > & operator= (Ptr const &o)
Assignment operator by referencing the same underlying object.
Private Member Functions
void Acquire (void) const
Mark this as a a reference by incrementing the reference count.
Private Attributes
T * m_ptr
The pointer.
Friends
template<typename U >
U * GetPointer (const Ptr< U > &p)
Get a permanent pointer to the underlying object.
template<typename U >
U * PeekPointer (const Ptr< U > &p)
Get a temporary pointer to the underlying object.
class Ptr< const T >
Interoperate with const instances.
Detailed Description
template<typename T>
class ns3::Ptr< T >
Smart pointer class similar to boost::intrusive_ptr.
This smart-pointer class assumes that the underlying type provides a pair of Ref and Unref methods which are expected to increment and decrement the internal reference count of the object instance. You can add Ref and Unref to a class simply by inheriting from ns3::SimpleRefCount.
This implementation allows you to manipulate the smart pointer as if it was a normal pointer: you can compare it with zero, compare it against other pointers, assign zero to it, etc.
It is possible to extract the raw pointer from this smart pointer with the GetPointer() and PeekPointer() methods.
If you want to store a new object into a smart pointer, we recommend you to use the Create() template functions to create the object and store it in a smart pointer to avoid memory leaks. These functions are really small convenience functions and their goal is just is save you a small bit of typing.
Template Parameters
T [explicit] The type of the underlying object.
Definition at line 73 of file ptr.h.
Constructor & Destructor Documentation
Ptr() [1/5]
template<typename T > ns3::Ptr< T >::Ptr
Create an empty smart pointer.
Definition at line 565 of file ptr.h.
Ptr() [2/5]
template<typename T > ns3::Ptr< T >::Ptr (T * ptr)
Create a smart pointer which points to the object pointed to by the input raw pointer ptr.
This method creates its own reference to the pointed object. The caller is responsible for Unref()'ing its own reference, and the smart pointer will eventually do the same, so that object is deleted if no more references to it remain.
Parameters
[in] ptr Raw pointer to manage
Definition at line 570 of file ptr.h.
References ns3::Ptr< T >::Acquire().
Ptr() [3/5]
template<typename T > ns3::Ptr< T >::Ptr (T * ptr, bool ref)
Create a smart pointer which points to the object pointed to by the input raw pointer ptr.
Parameters
[in] ptr Raw pointer to manage
[in] ref if set to true, this method calls Ref, otherwise, it does not call Ref.
Definition at line 577 of file ptr.h.
References ns3::Ptr< T >::Acquire().
Ptr() [4/5]
template<typename T > ns3::Ptr< T >::Ptr (Ptr< T > const & o)
Copy by referencing the same underlying object.
Parameters
[in] o The other Ptr instance.
Definition at line 587 of file ptr.h.
References ns3::Ptr< T >::Acquire().
Ptr() [5/5]
template<typename T > template<typename U > ns3::Ptr< T >::Ptr (Ptr< U > const & o)
Copy, removing const qualifier.
Template Parameters
U [deduced] The type underlying the Ptr being copied.
Parameters
[in] o The Ptr to copy.
Definition at line 594 of file ptr.h.
References ns3::Ptr< T >::Acquire().
~Ptr()
template<typename T > ns3::Ptr< T >::~Ptr
Destructor.
Definition at line 601 of file ptr.h.
Member Function Documentation
Acquire()
template<typename T > void ns3::Ptr< T >::Acquire (void) const inline private
Mark this as a a reference by incrementing the reference count.
Definition at line 556 of file ptr.h.
Referenced by ns3::Ptr< T >::Ptr().
operator Tester *()
template<typename T > ns3::Ptr< T >::operator Tester *
Test for non-NULL pointer.
This enables simple pointer checks like
Ptr<...> p = ...;
if (p) ...
This also disables deleting a Ptr
Definition at line 666 of file ptr.h.
operator!()
template<typename T > bool ns3::Ptr< T >::operator!
Test for NULL pointer.
This enables simple NULL pointer checks like
Ptr<..> p = ...;
if (!p) ...
Returns
true if the underlying pointer is NULL.
Definition at line 660 of file ptr.h.
operator*() [1/2]
template<typename T > T & ns3::Ptr< T >::operator*
A dereference.
Returns
A pointer to the underlying object.
Definition at line 652 of file ptr.h.
References NS_ASSERT_MSG.
operator*() [2/2]
template<typename T > T & ns3::Ptr< T >::operator*
A const dereference.
Returns
A pointer to the underlying object.
Definition at line 644 of file ptr.h.
References NS_ASSERT_MSG.
operator->() [1/2]
template<typename T > T * ns3::Ptr< T >::operator->
An lvalue member access.
Returns
A pointer to the underlying object.
Definition at line 628 of file ptr.h.
References NS_ASSERT_MSG.
operator->() [2/2]
template<typename T > T * ns3::Ptr< T >::operator->
An rvalue member access.
Returns
A pointer to the underlying object.
Definition at line 636 of file ptr.h.
References NS_ASSERT_MSG.
operator=()
template<typename T > Ptr< T > & ns3::Ptr< T >::operator= (Ptr< T > const & o)
Assignment operator by referencing the same underlying object.
Parameters
[in] o The other Ptr instance.
Returns
A reference to self.
Definition at line 611 of file ptr.h.
References ns3::Ptr< T >::m_ptr.
Friends And Related Function Documentation
GetPointer
template<typename T > template<typename U > U* GetPointer (const Ptr< U > & p) friend
Get a permanent pointer to the underlying object.
The underlying refcount is incremented prior to returning to the caller so the caller is responsible for calling Unref himself.
Template Parameters
U [deduced] The actual type of the argument and return pointer.
Parameters
[in] p Smart pointer
Returns
The pointer managed by this smart pointer.
Definition at line 417 of file ptr.h.
PeekPointer
template<typename T > template<typename U > U* PeekPointer (const Ptr< U > & p) friend
Get a temporary pointer to the underlying object.
The underlying refcount is not incremented prior to returning to the caller so the caller is not responsible for calling Unref himself.
Template Parameters
U [deduced] The actual type of the argument and return pointer.
Parameters
[in] p Smart pointer
Returns
The pointer managed by this smart pointer.
Definition at line 411 of file ptr.h.
Ptr< const T >
template<typename T > friend class Ptr< const T > friend
Interoperate with const instances.
Definition at line 78 of file ptr.h.
Member Data Documentation
m_ptr
template<typename T > T* ns3::Ptr< T >::m_ptr private
The pointer.
Definition at line 78 of file ptr.h.
Referenced by ns3::Ptr< T >::operator=().
The documentation for this class was generated from the following file:
src/core/model/ptr.h