ns-3: ns3::XmlConfigLoad Class Reference
ns3::XmlConfigLoad Class Reference
Configuration Store/Load
A class to enable loading of configuration store from an XML file.
#include "xml-config.h"
Public Member Functions
XmlConfigLoad ()
virtual ~XmlConfigLoad ()
virtual void Attributes (void)
Load or save the attributes values.
virtual void Default (void)
Load or save the default values.
virtual void Global (void)
Load or save the global values.
virtual void SetFilename (std::string filename)
Set the file name.
Public Member Functions inherited from ns3::FileConfig
virtual ~FileConfig ()
Private Attributes
std::string m_filename
the file name
Detailed Description
A class to enable loading of configuration store from an XML file.
Definition at line 54 of file xml-config.h.
Constructor & Destructor Documentation
XmlConfigLoad()
ns3::XmlConfigLoad::XmlConfigLoad ()
Definition at line 223 of file xml-config.cc.
References NS_LOG_FUNCTION.
~XmlConfigLoad()
ns3::XmlConfigLoad::~XmlConfigLoad () virtual
Definition at line 227 of file xml-config.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Attributes()
void ns3::XmlConfigLoad::Attributes (void) virtual
Load or save the attributes values.
Implements ns3::FileConfig.
Definition at line 315 of file xml-config.cc.
References m_filename, NS_FATAL_ERROR, NS_LOG_DEBUG, and ns3::Config::Set().
Default()
void ns3::XmlConfigLoad::Default (void) virtual
Load or save the default values.
Implements ns3::FileConfig.
Definition at line 239 of file xml-config.cc.
References m_filename, NS_FATAL_ERROR, NS_LOG_DEBUG, and ns3::Config::SetDefault().
Global()
void ns3::XmlConfigLoad::Global (void) virtual
Load or save the global values.
Implements ns3::FileConfig.
Definition at line 277 of file xml-config.cc.
References m_filename, NS_FATAL_ERROR, NS_LOG_DEBUG, and ns3::Config::SetGlobal().
SetFilename()
void ns3::XmlConfigLoad::SetFilename (std::string filename) virtual
Set the file name.
Parameters
filename the filename
Implements ns3::FileConfig.
Definition at line 233 of file xml-config.cc.
References m_filename, and NS_LOG_FUNCTION.
Member Data Documentation
m_filename
std::string ns3::XmlConfigLoad::m_filename private
the file name
Definition at line 65 of file xml-config.h.
Referenced by Attributes(), Default(), Global(), and SetFilename().
The documentation for this class was generated from the following files:
src/config-store/model/xml-config.h
src/config-store/model/xml-config.cc