ns-3: ns3::WifiInformationElementVector Class Reference
ns3::WifiInformationElementVector Class Reference
Wifi Models
Information element vector.
#include "wifi-information-element-vector.h"
Public Types
typedef std::vector< Ptr< WifiInformationElement > >::iterator Iterator
As soon as this is a vector, we define an Iterator.
Public Member Functions
WifiInformationElementVector ()
virtual ~WifiInformationElementVector ()
bool AddInformationElement (Ptr< WifiInformationElement > element)
add an IE, if maxSize has exceeded, returns false
Iterator Begin ()
Returns Begin of the vector.
virtual uint32_t Deserialize (Buffer::Iterator start)
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize a number of WifiInformationElements.
virtual uint32_t DeserializeSingleIe (Buffer::Iterator start)
Needed when you try to deserialize a lonely IE inside other header.
Iterator End ()
Returns End of the vector.
Ptr< WifiInformationElement > FindFirst (WifiInformationElementId id) const
vector of pointers to information elements is the body of IeVector
TypeId GetInstanceTypeId () const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize () const
virtual bool operator== (const WifiInformationElementVector &a) const
Check if the given WifiInformationElementVectors are equivalent.
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Types
typedef std::vector< Ptr< WifiInformationElement > > IE_VECTOR
typedef for a vector of WifiInformationElements.
Protected Member Functions
uint32_t GetSize () const
Current number of bytes.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes
IE_VECTOR m_elements
Information element vector.
uint16_t m_maxSize
Size in bytes (actually, max packet length)
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Information element vector.
Introspection did not find any typical Config paths.
Implements a vector of WifiInformationElements. Information elements typically come in groups, and the WifiInformationElementVector class provides a representation of a series of IEs, and the facility for serialisation to and deserialisation from the over-the-air format.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 40 bytes (on a 64-bit architecture).
Definition at line 39 of file wifi-information-element-vector.h.
Member Typedef Documentation
IE_VECTOR
typedef std::vector<Ptr<WifiInformationElement> > ns3::WifiInformationElementVector::IE_VECTOR protected
typedef for a vector of WifiInformationElements.
Definition at line 123 of file wifi-information-element-vector.h.
Iterator
typedef std::vector<Ptr<WifiInformationElement> >::iterator ns3::WifiInformationElementVector::Iterator
As soon as this is a vector, we define an Iterator.
Definition at line 82 of file wifi-information-element-vector.h.
Constructor & Destructor Documentation
WifiInformationElementVector()
ns3::WifiInformationElementVector::WifiInformationElementVector ()
Definition at line 27 of file wifi-information-element-vector.cc.
~WifiInformationElementVector()
ns3::WifiInformationElementVector::~WifiInformationElementVector () virtual
Definition at line 32 of file wifi-information-element-vector.cc.
References m_elements.
Member Function Documentation
AddInformationElement()
bool ns3::WifiInformationElementVector::AddInformationElement (Ptr< WifiInformationElement > element)
add an IE, if maxSize has exceeded, returns false
Parameters
element wifi information element to add
Returns
true is added
Definition at line 147 of file wifi-information-element-vector.cc.
References ns3::WifiInformationElement::GetInformationFieldSize(), GetSize(), m_elements, and m_maxSize.
Referenced by ns3::MeshWifiBeacon::AddInformationElement(), MeshInformationElementVectorBist::DoRun(), ns3::dot11s::HwmpProtocolMac::ForwardPerr(), ns3::dot11s::PeerManagementProtocolMac::SendPeerLinkManagementFrame(), ns3::dot11s::HwmpProtocolMac::SendPrep(), and ns3::dot11s::HwmpProtocolMac::SendPreq().
Begin()
WifiInformationElementVector::Iterator ns3::WifiInformationElementVector::Begin (void)
Returns Begin of the vector.
Returns
the begin of the vector
Definition at line 135 of file wifi-information-element-vector.cc.
References m_elements.
Referenced by ns3::dot11s::HwmpProtocolMac::ReceiveAction().
Deserialize() [1/2]
uint32_t ns3::WifiInformationElementVector::Deserialize (Buffer::Iterator start) virtual
Attention
This variant should not be used but is implemented due to backward compatibility reasons
Parameters
start buffer location to start deserializing from
Returns
number of bytes deserialized
Implements ns3::Header.
Definition at line 73 of file wifi-information-element-vector.cc.
References NS_FATAL_ERROR.
Deserialize() [2/2]
uint32_t ns3::WifiInformationElementVector::Deserialize (Buffer::Iterator start, Buffer::Iterator end) virtual
Deserialize a number of WifiInformationElements.
The size of this Header should equal start.GetDistanceFrom (end).
Parameters
start starting buffer location
end ending buffer location
Returns
number of bytes deserialized
Reimplemented from ns3::Chunk.
Definition at line 80 of file wifi-information-element-vector.cc.
References DeserializeSingleIe(), NS_ASSERT, NS_ASSERT_MSG, and visualizer.core::start().
DeserializeSingleIe()
uint32_t ns3::WifiInformationElementVector::DeserializeSingleIe (Buffer::Iterator start) virtual
Needed when you try to deserialize a lonely IE inside other header.
Parameters
start is the start of the buffer
Returns
deserialized bytes
Reimplemented in ns3::MeshInformationElementVector.
Definition at line 96 of file wifi-information-element-vector.cc.
References NS_FATAL_ERROR, ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
Referenced by Deserialize(), and ns3::MeshInformationElementVector::DeserializeSingleIe().
End()
WifiInformationElementVector::Iterator ns3::WifiInformationElementVector::End (void)
Returns End of the vector.
Returns
the end of the vector
Definition at line 141 of file wifi-information-element-vector.cc.
References m_elements.
Referenced by ns3::dot11s::HwmpProtocolMac::ReceiveAction().
FindFirst()
Ptr< WifiInformationElement > ns3::WifiInformationElementVector::FindFirst (WifiInformationElementId id) const
vector of pointers to information elements is the body of IeVector
Parameters
id the element id to find
Returns
the information element
Definition at line 158 of file wifi-information-element-vector.cc.
References m_elements.
Referenced by ns3::dot11s::PeerManagementProtocolMac::Receive().
GetInstanceTypeId()
TypeId ns3::WifiInformationElementVector::GetInstanceTypeId () const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 52 of file wifi-information-element-vector.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::WifiInformationElementVector::GetSerializedSize () const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 58 of file wifi-information-element-vector.cc.
References GetSize().
Referenced by MeshInformationElementVectorBist::DoRun().
GetSize()
uint32_t ns3::WifiInformationElementVector::GetSize (void) const protected
Current number of bytes.
Returns
the number of bytes
Definition at line 171 of file wifi-information-element-vector.cc.
References m_elements.
Referenced by AddInformationElement(), ns3::MeshInformationElementVector::DeserializeSingleIe(), and GetSerializedSize().
GetTypeId()
TypeId ns3::WifiInformationElementVector::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 42 of file wifi-information-element-vector.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
operator==()
bool ns3::WifiInformationElementVector::operator== (const WifiInformationElementVector & a) const virtual
Check if the given WifiInformationElementVectors are equivalent.
Parameters
a another WifiInformationElementVector
Returns
true if the given WifiInformationElementVectors are equivalent, false otherwise
Definition at line 182 of file wifi-information-element-vector.cc.
References m_elements, and NS_ASSERT.
Print()
void ns3::WifiInformationElementVector::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 124 of file wifi-information-element-vector.cc.
References m_elements.
Serialize()
void ns3::WifiInformationElementVector::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 64 of file wifi-information-element-vector.cc.
References m_elements, and visualizer.core::start().
Member Data Documentation
m_elements
IE_VECTOR ns3::WifiInformationElementVector::m_elements protected
Information element vector.
Definition at line 129 of file wifi-information-element-vector.h.
Referenced by ~WifiInformationElementVector(), AddInformationElement(), Begin(), ns3::MeshInformationElementVector::DeserializeSingleIe(), End(), FindFirst(), GetSize(), operator==(), Print(), and Serialize().
m_maxSize
uint16_t ns3::WifiInformationElementVector::m_maxSize protected
Size in bytes (actually, max packet length)
Definition at line 130 of file wifi-information-element-vector.h.
Referenced by AddInformationElement(), and ns3::MeshInformationElementVector::DeserializeSingleIe().
The documentation for this class was generated from the following files:
src/wifi/model/wifi-information-element-vector.h
src/wifi/model/wifi-information-element-vector.cc