ns-3: ns3::StringValue Class Reference
ns3::StringValue Class Reference
String Attribute
Hold variables of type string.
#include "string.h"
Public Member Functions
StringValue ()
StringValue (const std::string &value)
Copy constructor.
virtual Ptr< AttributeValue > Copy (void) const
virtual bool DeserializeFromString (std::string value, Ptr< const AttributeChecker > checker)
std::string Get (void) const
template<typename T >
bool GetAccessor (T &value) const
Access the String value as type T.
virtual std::string SerializeToString (Ptr< const AttributeChecker > checker) const
void Set (const std::string &value)
Set the value.
Public Member Functions inherited from ns3::AttributeValue
AttributeValue ()
virtual ~AttributeValue ()
Public Member Functions inherited from ns3::SimpleRefCount< AttributeValue >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
std::string m_value
The stored String instance.
Detailed Description
Hold variables of type string.
AttributeValue implementation for String.
This class can be used to hold variables of type string, that is, either char * or std::string.
See also
AttributeValue
Definition at line 41 of file string.h.
Constructor & Destructor Documentation
StringValue() [1/2]
ns3::StringValue::StringValue ()
Definition at line 31 of file string.cc.
StringValue() [2/2]
String ns3::StringValue::StringValue (const std::string & value)
Copy constructor.
Parameters
[in] value The String value to copy.
Definition at line 31 of file string.cc.
Member Function Documentation
Copy()
Ptr< AttributeValue > ns3::StringValue::Copy (void) const virtual
Returns
a deep copy of this class, wrapped into an Attribute object.
Implements ns3::AttributeValue.
Definition at line 31 of file string.cc.
DeserializeFromString()
bool ns3::StringValue::DeserializeFromString (std::string value, Ptr< const AttributeChecker > checker) virtual
Parameters
[in] value A string representation of the value
[in] checker A pointer to the checker associated to the attribute.
Returns
true if the input string was correctly-formatted and could be successfully deserialized, false otherwise.
Upon return of this function, this AttributeValue instance contains the deserialized value. In most cases, this method will not make any use of the checker argument. However, in a very limited set of cases, the checker argument is needed to perform proper serialization. A nice example of code which needs it is the EnumValue::SerializeToString code.
Implements ns3::AttributeValue.
Definition at line 31 of file string.cc.
Get()
std::string ns3::StringValue::Get (void) const
Returns
The String value.
Definition at line 31 of file string.cc.
Referenced by ns3::RawTextConfigSave::Attributes(), ns3::XmlConfigSave::Attributes(), ns3::cell_data_function_col_1(), AttributeTestCase< T >::CheckGetCodePaths(), ns3::AttributeChecker::CreateValidValue(), PrioQueueDiscTestCase::DoRun(), ns3::GetImpl(), ns3::RawTextConfigSave::Global(), ns3::XmlConfigSave::Global(), PrintAllGlobals(), ns3::CommandLine::PrintGlobals(), ns3::NscStackStringAccessor::Set(), VanetRoutingExperiment::SetConfigFromGlobals(), VanetRoutingExperiment::SetGlobalsFromConfig(), ns3::Simulator::SetImplementation(), and ns3::MpiInterface::SetParallelSimulatorImpl().
GetAccessor()
template<typename T > bool ns3::StringValue::GetAccessor (T & value) const inline
Access the String value as type T.
Template Parameters
T [explicit] The type to cast to.
Parameters
[out] value The String value, as type T.
Returns
true.
Definition at line 41 of file string.h.
SerializeToString()
std::string ns3::StringValue::SerializeToString (Ptr< const AttributeChecker > checker) const virtual
Parameters
[in] checker The checker associated to the attribute
Returns
A string representation of this value.
In most cases, this method will not make any use of the checker argument. However, in a very limited set of cases, the checker argument is needed to perform proper serialization. A nice example of code which needs it is the EnumValue::SerializeToString code.
Implements ns3::AttributeValue.
Definition at line 31 of file string.cc.
Set()
void ns3::StringValue::Set (const std::string & value)
Set the value.
Parameters
[in] value The value to adopt.
Definition at line 31 of file string.cc.
Referenced by ns3::NscStackStringAccessor::Get(), ns3::ObjectBase::GetAttribute(), ns3::ObjectBase::GetAttributeFailSafe(), and ns3::GlobalValue::GetValue().
Member Data Documentation
m_value
std::string ns3::StringValue::m_value private
The stored String instance.
Definition at line 41 of file string.h.
The documentation for this class was generated from the following files:
src/core/model/string.h
src/core/model/string.cc
doc/introspected-doxygen.h