ns-3: ns3::Ipv6ExtensionHeader Class Reference
ns3::Ipv6ExtensionHeader Class Reference
Internet » IPv6 classes and sub-modules » IPV6 Header extension system.
Header for IPv6 Extension.
#include "ipv6-extension-header.h"
Public Member Functions
Ipv6ExtensionHeader ()
Constructor.
virtual ~Ipv6ExtensionHeader ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
uint16_t GetLength () const
Get the length of the extension.
uint8_t GetNextHeader () const
Get the next header.
virtual uint32_t GetSerializedSize () const
Get the serialized size of the packet.
virtual void Print (std::ostream &os) const
Print some information about the packet.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetLength (uint16_t length)
brief Set the length of the extension.
void SetNextHeader (uint8_t nextHeader)
Set the "Next header" field.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Attributes
uint8_t m_length
The "length" field.
Private Attributes
Buffer m_data
The data of the extension.
uint8_t m_nextHeader
The "next header" field.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Header for IPv6 Extension.
Introspection did not find any typical Config paths.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 48 bytes (on a 64-bit architecture).
Definition at line 40 of file ipv6-extension-header.h.
Constructor & Destructor Documentation
Ipv6ExtensionHeader()
ns3::Ipv6ExtensionHeader::Ipv6ExtensionHeader ()
Constructor.
Definition at line 48 of file ipv6-extension-header.cc.
~Ipv6ExtensionHeader()
ns3::Ipv6ExtensionHeader::~Ipv6ExtensionHeader () virtual
Destructor.
Definition at line 55 of file ipv6-extension-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::Ipv6ExtensionHeader::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start Buffer iterator
Returns
size of the packet
Implements ns3::Header.
Reimplemented in ns3::Ipv6ExtensionAHHeader, ns3::Ipv6ExtensionESPHeader, ns3::Ipv6ExtensionLooseRoutingHeader, ns3::Ipv6ExtensionRoutingHeader, ns3::Ipv6ExtensionFragmentHeader, ns3::Ipv6ExtensionDestinationHeader, and ns3::Ipv6ExtensionHopByHopHeader.
Definition at line 102 of file ipv6-extension-header.cc.
References ns3::Buffer::AddAtEnd(), ns3::Buffer::Begin(), data, GetLength(), GetSerializedSize(), ns3::Buffer::GetSize(), m_data, m_length, m_nextHeader, ns3::Buffer::Iterator::Read(), ns3::Buffer::Iterator::ReadU8(), ns3::Buffer::RemoveAtEnd(), visualizer.core::start(), and ns3::Buffer::Iterator::Write().
GetInstanceTypeId()
TypeId ns3::Ipv6ExtensionHeader::GetInstanceTypeId (void) const virtual
Get the instance type ID.
Returns
instance type ID
Implements ns3::ObjectBase.
Reimplemented in ns3::Ipv6ExtensionAHHeader, ns3::Ipv6ExtensionESPHeader, ns3::Ipv6ExtensionLooseRoutingHeader, ns3::Ipv6ExtensionRoutingHeader, ns3::Ipv6ExtensionFragmentHeader, ns3::Ipv6ExtensionDestinationHeader, and ns3::Ipv6ExtensionHopByHopHeader.
Definition at line 43 of file ipv6-extension-header.cc.
References GetTypeId().
GetLength()
uint16_t ns3::Ipv6ExtensionHeader::GetLength () const
Get the length of the extension.
Returns
the length of the extension
Definition at line 78 of file ipv6-extension-header.cc.
References m_length.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanNhc(), Deserialize(), ns3::Ipv6ExtensionHopByHopHeader::Deserialize(), ns3::Ipv6ExtensionDestinationHeader::Deserialize(), ns3::Ipv6ExtensionFragment::GetFragments(), Print(), ns3::Ipv6ExtensionHopByHopHeader::Print(), ns3::Ipv6ExtensionDestinationHeader::Print(), ns3::Ipv6ExtensionFragmentHeader::Print(), ns3::Ipv6ExtensionRoutingHeader::Print(), ns3::Ipv6ExtensionLooseRoutingHeader::Print(), ns3::Ipv6ExtensionHopByHop::Process(), ns3::Ipv6ExtensionDestination::Process(), and ns3::Ipv6ExtensionLooseRouting::Process().
GetNextHeader()
uint8_t ns3::Ipv6ExtensionHeader::GetNextHeader () const
Get the next header.
Returns
the next header number
Definition at line 64 of file ipv6-extension-header.cc.
References m_nextHeader.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanNhc(), ns3::Ipv6ExtensionFragment::GetFragments(), Print(), ns3::Ipv6ExtensionHopByHopHeader::Print(), ns3::Ipv6ExtensionDestinationHeader::Print(), ns3::Ipv6ExtensionFragmentHeader::Print(), ns3::Ipv6ExtensionRoutingHeader::Print(), ns3::Ipv6ExtensionLooseRoutingHeader::Print(), ns3::Ipv6ExtensionHopByHop::Process(), ns3::Ipv6ExtensionDestination::Process(), ns3::Ipv6ExtensionFragment::Process(), ns3::Ipv6ExtensionLooseRouting::Process(), ns3::Ipv6ExtensionHopByHopHeader::Serialize(), ns3::Ipv6ExtensionDestinationHeader::Serialize(), ns3::Ipv6ExtensionFragmentHeader::Serialize(), ns3::Ipv6ExtensionRoutingHeader::Serialize(), and ns3::Ipv6ExtensionLooseRoutingHeader::Serialize().
GetSerializedSize()
uint32_t ns3::Ipv6ExtensionHeader::GetSerializedSize (void) const virtual
Get the serialized size of the packet.
Returns
size
Implements ns3::Header.
Reimplemented in ns3::Ipv6ExtensionAHHeader, ns3::Ipv6ExtensionESPHeader, ns3::Ipv6ExtensionLooseRoutingHeader, ns3::Ipv6ExtensionRoutingHeader, ns3::Ipv6ExtensionFragmentHeader, ns3::Ipv6ExtensionDestinationHeader, and ns3::Ipv6ExtensionHopByHopHeader.
Definition at line 88 of file ipv6-extension-header.cc.
Referenced by Deserialize().
GetTypeId()
TypeId ns3::Ipv6ExtensionHeader::GetTypeId (void) static
Get the type identificator.
Returns
type identificator
Definition at line 33 of file ipv6-extension-header.cc.
References ns3::TypeId::AddConstructor().
Referenced by GetInstanceTypeId().
Print()
void ns3::Ipv6ExtensionHeader::Print (std::ostream & os) const virtual
Print some information about the packet.
Parameters
os output stream
Returns
info about this packet
Implements ns3::Header.
Reimplemented in ns3::Ipv6ExtensionAHHeader, ns3::Ipv6ExtensionESPHeader, ns3::Ipv6ExtensionLooseRoutingHeader, ns3::Ipv6ExtensionRoutingHeader, ns3::Ipv6ExtensionFragmentHeader, ns3::Ipv6ExtensionDestinationHeader, and ns3::Ipv6ExtensionHopByHopHeader.
Definition at line 83 of file ipv6-extension-header.cc.
References GetLength(), and GetNextHeader().
Serialize()
void ns3::Ipv6ExtensionHeader::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start Buffer iterator
Implements ns3::Header.
Reimplemented in ns3::Ipv6ExtensionAHHeader, ns3::Ipv6ExtensionESPHeader, ns3::Ipv6ExtensionLooseRoutingHeader, ns3::Ipv6ExtensionRoutingHeader, ns3::Ipv6ExtensionFragmentHeader, ns3::Ipv6ExtensionDestinationHeader, and ns3::Ipv6ExtensionHopByHopHeader.
Definition at line 93 of file ipv6-extension-header.cc.
References ns3::Buffer::GetSize(), m_data, m_length, m_nextHeader, ns3::Buffer::PeekData(), visualizer.core::start(), ns3::Buffer::Iterator::Write(), and ns3::Buffer::Iterator::WriteU8().
SetLength()
void ns3::Ipv6ExtensionHeader::SetLength (uint16_t length)
brief Set the length of the extension.
Parameters
length the length of the extension in bytes
Definition at line 69 of file ipv6-extension-header.cc.
References m_length, and NS_ASSERT_MSG.
SetNextHeader()
void ns3::Ipv6ExtensionHeader::SetNextHeader (uint8_t nextHeader)
Set the "Next header" field.
Parameters
nextHeader the next header number
Definition at line 59 of file ipv6-extension-header.cc.
References m_nextHeader.
Referenced by ns3::Ipv6ExtensionHopByHopHeader::Deserialize(), ns3::Ipv6ExtensionDestinationHeader::Deserialize(), ns3::Ipv6ExtensionFragmentHeader::Deserialize(), ns3::Ipv6ExtensionRoutingHeader::Deserialize(), ns3::Ipv6ExtensionLooseRoutingHeader::Deserialize(), ns3::Ipv6ExtensionFragment::GetFragments(), and ns3::Ping6::Send().
Member Data Documentation
m_data
Buffer ns3::Ipv6ExtensionHeader::m_data private
The data of the extension.
Definition at line 130 of file ipv6-extension-header.h.
Referenced by Deserialize(), and Serialize().
m_length
uint8_t ns3::Ipv6ExtensionHeader::m_length protected
The "length" field.
Definition at line 119 of file ipv6-extension-header.h.
Referenced by ns3::Ipv6ExtensionFragmentHeader::Ipv6ExtensionFragmentHeader(), Deserialize(), ns3::Ipv6ExtensionHopByHopHeader::Deserialize(), ns3::Ipv6ExtensionDestinationHeader::Deserialize(), ns3::Ipv6ExtensionRoutingHeader::Deserialize(), ns3::Ipv6ExtensionLooseRoutingHeader::Deserialize(), GetLength(), Serialize(), ns3::Ipv6ExtensionRoutingHeader::Serialize(), and SetLength().
m_nextHeader
uint8_t ns3::Ipv6ExtensionHeader::m_nextHeader private
The "next header" field.
Definition at line 125 of file ipv6-extension-header.h.
Referenced by Deserialize(), GetNextHeader(), Serialize(), and SetNextHeader().
The documentation for this class was generated from the following files:
src/internet/model/ipv6-extension-header.h
src/internet/model/ipv6-extension-header.cc