ns-3: ns3::RandomDirection2dMobilityModel Class Reference
ns3::RandomDirection2dMobilityModel Class Reference
Mobility
Random direction mobility model.
#include "random-direction-2d-mobility-model.h"
Public Member Functions
RandomDirection2dMobilityModel ()
Public Member Functions inherited from ns3::MobilityModel
MobilityModel ()
virtual ~MobilityModel ()=0
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
double GetDistanceFrom (Ptr< const MobilityModel > position) const
Vector GetPosition (void) const
double GetRelativeSpeed (Ptr< const MobilityModel > other) const
Vector GetVelocity (void) const
void SetPosition (const Vector &position)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type with the TypeId system.
Static Public Member Functions inherited from ns3::MobilityModel
static TypeId GetTypeId (void)
Register this type with the TypeId system.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void BeginPause (void)
Pause, cancel currently scheduled event, schedule end of pause event.
virtual int64_t DoAssignStreams (int64_t)
The default implementation does nothing but return the passed-in parameter.
virtual void DoDispose (void)
Destructor implementation.
virtual Vector DoGetPosition (void) const
virtual Vector DoGetVelocity (void) const
virtual void DoInitialize (void)
Initialize() implementation.
void DoInitializePrivate (void)
Sets a new random direction and calls SetDirectionAndSpeed.
virtual void DoSetPosition (const Vector &position)
void ResetDirectionAndSpeed (void)
Set a new direction and speed.
void SetDirectionAndSpeed (double direction)
Set new velocity and direction, and schedule next pause event
Private Attributes
Rectangle m_bounds
the 2D bounding area
Ptr< UniformRandomVariable > m_direction
rv to control direction
EventId m_event
event ID of next scheduled event
ConstantVelocityHelper m_helper
helper for velocity computations
Ptr< RandomVariableStream > m_pause
a random variable to control pause
Ptr< RandomVariableStream > m_speed
a random variable to control speed
Additional Inherited Members
Public Types inherited from ns3::MobilityModel
typedef void(* TracedCallback) (Ptr< const MobilityModel > model)
TracedCallback signature.
Protected Member Functions inherited from ns3::MobilityModel
void NotifyCourseChange (void) const
Must be invoked by subclasses when the course of the position changes to notify course change listeners.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Random direction mobility model.
The movement of objects is based on random directions: each object pauses for a specific delay, chooses a random direction and speed and then travels in the specific direction until it reaches one of the boundaries of the model. When it reaches the boundary, it pauses, selects a new direction and speed, aso.
Config Paths
ns3::RandomDirection2dMobilityModel is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomDirection2dMobilityModel"
Attributes
Bounds: The 2d bounding area
Set with class: RectangleValue
Underlying type: Rectangle
Initial value: -100|100|-100|100
Flags: construct write read
Speed: A random variable to control the speed (m/s).
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::RandomVariableStream>
Initial value: ns3::UniformRandomVariable[Min=1.0|Max=2.0]
Flags: construct write read
Pause: A random variable to control the pause (s).
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::RandomVariableStream>
Initial value: ns3::ConstantRandomVariable[Constant=2.0]
Flags: construct write read
Attributes defined in parent class ns3::MobilityModel
Position: The current position of the mobility model.
Set with class: Vector3DValue
Underlying type: Vector3D
Flags: write read
Velocity: The current velocity of the mobility model.
Set with class: Vector3DValue
Underlying type: Vector3D
Flags: read
No TraceSources are defined for this type.
TraceSources defined in parent class ns3::MobilityModel
CourseChange: The value of the position and/or velocity vector changed
Callback signature: ns3::MobilityModel::TracedCallback
Size of this type is 200 bytes (on a 64-bit architecture).
Definition at line 44 of file random-direction-2d-mobility-model.h.
Constructor & Destructor Documentation
RandomDirection2dMobilityModel()
ns3::RandomDirection2dMobilityModel::RandomDirection2dMobilityModel ()
Definition at line 58 of file random-direction-2d-mobility-model.cc.
References m_direction.
Member Function Documentation
BeginPause()
void ns3::RandomDirection2dMobilityModel::BeginPause (void) private
Pause, cancel currently scheduled event, schedule end of pause event.
Definition at line 84 of file random-direction-2d-mobility-model.cc.
References ns3::EventId::Cancel(), ns3::RandomVariableStream::GetValue(), m_event, m_helper, m_pause, ns3::MobilityModel::NotifyCourseChange(), ns3::ConstantVelocityHelper::Pause(), ResetDirectionAndSpeed(), ns3::Simulator::Schedule(), ns3::Seconds(), and ns3::ConstantVelocityHelper::Update().
Referenced by SetDirectionAndSpeed().
DoAssignStreams()
int64_t ns3::RandomDirection2dMobilityModel::DoAssignStreams (int64_t start) private virtual
The default implementation does nothing but return the passed-in parameter.
Subclasses using random variables are expected to override this.
Parameters
start starting stream index
Returns
the number of streams used
Reimplemented from ns3::MobilityModel.
Definition at line 156 of file random-direction-2d-mobility-model.cc.
References m_direction, m_pause, m_speed, and ns3::RandomVariableStream::SetStream().
DoDispose()
void ns3::RandomDirection2dMobilityModel::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 64 of file random-direction-2d-mobility-model.cc.
References ns3::Object::DoDispose().
DoGetPosition()
Vector ns3::RandomDirection2dMobilityModel::DoGetPosition (void) const private virtual
Returns
the current position.
Concrete subclasses of this base class must implement this method.
Implements ns3::MobilityModel.
Definition at line 138 of file random-direction-2d-mobility-model.cc.
References ns3::ConstantVelocityHelper::GetCurrentPosition(), m_bounds, m_helper, and ns3::ConstantVelocityHelper::UpdateWithBounds().
DoGetVelocity()
Vector ns3::RandomDirection2dMobilityModel::DoGetVelocity (void) const private virtual
Returns
the current velocity.
Concrete subclasses of this base class must implement this method.
Implements ns3::MobilityModel.
Definition at line 151 of file random-direction-2d-mobility-model.cc.
References ns3::ConstantVelocityHelper::GetVelocity(), and m_helper.
DoInitialize()
void ns3::RandomDirection2dMobilityModel::DoInitialize (void) private virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 70 of file random-direction-2d-mobility-model.cc.
References ns3::Object::DoInitialize(), and DoInitializePrivate().
DoInitializePrivate()
void ns3::RandomDirection2dMobilityModel::DoInitializePrivate (void) private
Sets a new random direction and calls SetDirectionAndSpeed.
Definition at line 77 of file random-direction-2d-mobility-model.cc.
References ns3::UniformRandomVariable::GetValue(), m_direction, and SetDirectionAndSpeed().
Referenced by DoInitialize(), and DoSetPosition().
DoSetPosition()
void ns3::RandomDirection2dMobilityModel::DoSetPosition (const Vector & position) private virtual
Parameters
position the position to set.
Concrete subclasses of this base class must implement this method.
Implements ns3::MobilityModel.
Definition at line 144 of file random-direction-2d-mobility-model.cc.
References ns3::EventId::Cancel(), DoInitializePrivate(), m_event, m_helper, ns3::Simulator::ScheduleNow(), and ns3::ConstantVelocityHelper::SetPosition().
GetTypeId()
TypeId ns3::RandomDirection2dMobilityModel::GetTypeId (void) static
Register this type with the TypeId system.
Returns
the object TypeId
Definition at line 36 of file random-direction-2d-mobility-model.cc.
References m_bounds, m_pause, m_speed, ns3::MakePointerAccessor(), ns3::MakeRectangleAccessor(), ns3::MakeRectangleChecker(), and ns3::TypeId::SetParent().
ResetDirectionAndSpeed()
void ns3::RandomDirection2dMobilityModel::ResetDirectionAndSpeed (void) private
Set a new direction and speed.
Definition at line 114 of file random-direction-2d-mobility-model.cc.
References ns3::Rectangle::BOTTOM, ns3::Rectangle::GetClosestSide(), ns3::ConstantVelocityHelper::GetCurrentPosition(), ns3::UniformRandomVariable::GetValue(), ns3::Rectangle::LEFT, m_bounds, m_direction, m_helper, ns3::Rectangle::RIGHT, SetDirectionAndSpeed(), ns3::Rectangle::TOP, and ns3::ConstantVelocityHelper::UpdateWithBounds().
Referenced by BeginPause().
SetDirectionAndSpeed()
void ns3::RandomDirection2dMobilityModel::SetDirectionAndSpeed (double direction) private
Set new velocity and direction, and schedule next pause event
Parameters
direction (radians)
Definition at line 95 of file random-direction-2d-mobility-model.cc.
References BeginPause(), ns3::CalculateDistance(), ns3::Rectangle::CalculateIntersection(), ns3::EventId::Cancel(), ns3::ConstantVelocityHelper::GetCurrentPosition(), ns3::RandomVariableStream::GetValue(), m_bounds, m_event, m_helper, m_speed, ns3::MobilityModel::NotifyCourseChange(), NS_LOG_FUNCTION_NOARGS, ns3::Simulator::Schedule(), ns3::Seconds(), ns3::ConstantVelocityHelper::SetVelocity(), ns3::ConstantVelocityHelper::Unpause(), and ns3::ConstantVelocityHelper::UpdateWithBounds().
Referenced by DoInitializePrivate(), and ResetDirectionAndSpeed().
Member Data Documentation
m_bounds
Rectangle ns3::RandomDirection2dMobilityModel::m_bounds private
the 2D bounding area
Definition at line 80 of file random-direction-2d-mobility-model.h.
Referenced by DoGetPosition(), GetTypeId(), ResetDirectionAndSpeed(), and SetDirectionAndSpeed().
m_direction
Ptr<UniformRandomVariable> ns3::RandomDirection2dMobilityModel::m_direction private
rv to control direction
Definition at line 79 of file random-direction-2d-mobility-model.h.
Referenced by RandomDirection2dMobilityModel(), DoAssignStreams(), DoInitializePrivate(), and ResetDirectionAndSpeed().
m_event
EventId ns3::RandomDirection2dMobilityModel::m_event private
event ID of next scheduled event
Definition at line 83 of file random-direction-2d-mobility-model.h.
Referenced by BeginPause(), DoSetPosition(), and SetDirectionAndSpeed().
m_helper
ConstantVelocityHelper ns3::RandomDirection2dMobilityModel::m_helper private
helper for velocity computations
Definition at line 84 of file random-direction-2d-mobility-model.h.
Referenced by BeginPause(), DoGetPosition(), DoGetVelocity(), DoSetPosition(), ResetDirectionAndSpeed(), and SetDirectionAndSpeed().
m_pause
Ptr<RandomVariableStream> ns3::RandomDirection2dMobilityModel::m_pause private
a random variable to control pause
Definition at line 82 of file random-direction-2d-mobility-model.h.
Referenced by BeginPause(), DoAssignStreams(), and GetTypeId().
m_speed
Ptr<RandomVariableStream> ns3::RandomDirection2dMobilityModel::m_speed private
a random variable to control speed
Definition at line 81 of file random-direction-2d-mobility-model.h.
Referenced by DoAssignStreams(), GetTypeId(), and SetDirectionAndSpeed().
The documentation for this class was generated from the following files:
src/mobility/model/random-direction-2d-mobility-model.h
src/mobility/model/random-direction-2d-mobility-model.cc