ns-3: ns3::SimulatorImpl Class Reference
ns3::SimulatorImpl Class Reference abstract
Core » Simulator
The SimulatorImpl base class.
#include "simulator-impl.h"
Public Member Functions
virtual void Cancel (const EventId &id)=0
Set the cancel bit on this event: the event's associated function will not be invoked when it expires.
virtual void Destroy ()=0
Execute the events scheduled with ScheduleDestroy().
virtual uint32_t GetContext (void) const =0
Get the current simulation context.
virtual Time GetDelayLeft (const EventId &id) const =0
Get the remaining time until this event will execute.
virtual uint64_t GetEventCount (void) const =0
Get the number of events executed.
virtual Time GetMaximumSimulationTime (void) const =0
Get the maximum representable simulation time.
virtual uint32_t GetSystemId () const =0
Get the system id of this simulator.
virtual bool IsExpired (const EventId &id) const =0
Check if an event has already run or been cancelled.
virtual bool IsFinished (void) const =0
Check if the simulation should finish.
virtual Time Now (void) const =0
Return the current simulation virtual time.
virtual void Remove (const EventId &id)=0
Remove an event from the event list.
virtual void Run (void)=0
Run the simulation.
virtual EventId Schedule (const Time &delay, EventImpl *event)=0
Schedule a future event execution (in the same context).
virtual EventId ScheduleDestroy (EventImpl *event)=0
Schedule an event to run at the end of the simulation, after the Stop() time or condition has been reached.
virtual EventId ScheduleNow (EventImpl *event)=0
Schedule an event to run at the current virtual time.
virtual void ScheduleWithContext (uint32_t context, const Time &delay, EventImpl *event)=0
Schedule a future event execution (in a different context).
virtual void SetScheduler (ObjectFactory schedulerFactory)=0
Set the Scheduler to be used to manage the event list.
virtual void Stop (const Time &delay)=0
Schedule the time delay until the Simulator should stop.
virtual void Stop (void)=0
Tell the Simulator the calling event should be the last one executed.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the registered TypeId for this class.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The SimulatorImpl base class.
Introspection did not find any typical Config paths.
Todo:
Define what the simulation or event context means.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 32 bytes (on a 64-bit architecture).
Definition at line 48 of file simulator-impl.h.
Member Function Documentation
Cancel()
virtual void ns3::SimulatorImpl::Cancel (const EventId & id) pure virtual
Set the cancel bit on this event: the event's associated function will not be invoked when it expires.
This method has the same visible effect as the ns3::Simulator::Remove method but its algorithmic complexity is much lower: it has O(1) complexity. This method has the exact same semantics as ns3::EventId::Cancel. Note that it is not possible to cancel events which were scheduled for the "destroy" time. Doing so will result in a program error (crash).
Parameters
[in] id the event to cancel
Implemented in ns3::VisualSimulatorImpl, ns3::NullMessageSimulatorImpl, ns3::DistributedSimulatorImpl, ns3::DefaultSimulatorImpl, and ns3::RealtimeSimulatorImpl.
Referenced by ns3::Simulator::Cancel().
Destroy()
virtual void ns3::SimulatorImpl::Destroy () pure virtual
Execute the events scheduled with ScheduleDestroy().
This method is typically invoked at the end of a simulation to avoid false-positive reports by a leak checker. After this method has been invoked, it is actually possible to restart a new simulation with a set of calls to Simulator::Run, Simulator::Schedule and Simulator::ScheduleWithContext.
Implemented in ns3::VisualSimulatorImpl, ns3::NullMessageSimulatorImpl, ns3::DistributedSimulatorImpl, ns3::RealtimeSimulatorImpl, and ns3::DefaultSimulatorImpl.
GetContext()
virtual uint32_t ns3::SimulatorImpl::GetContext (void) const pure virtual
Get the current simulation context.
The simulation context is the ns-3 notion of a Logical Process. Events in a single context should only modify state associated with that context. Events for objects in other contexts should be scheduled with ScheduleWithContext() to track the context switches. In other words, events in different contexts should be mutually thread safe, by not modify overlapping model state.
In circumstances where the context can't be determined, such as during object initialization, the enum value NO_CONTEXT should be used.
Returns
The current simulation context
Implemented in ns3::VisualSimulatorImpl, ns3::NullMessageSimulatorImpl, ns3::DistributedSimulatorImpl, ns3::RealtimeSimulatorImpl, and ns3::DefaultSimulatorImpl.
Referenced by ns3::Simulator::GetContext().
GetDelayLeft()
virtual Time ns3::SimulatorImpl::GetDelayLeft (const EventId & id) const pure virtual
Get the remaining time until this event will execute.
Parameters
[in] id The event id to analyse.
Returns
The delay left until the input event id expires. if the event is not running, this method returns zero.
Implemented in ns3::VisualSimulatorImpl, ns3::NullMessageSimulatorImpl, ns3::DistributedSimulatorImpl, ns3::RealtimeSimulatorImpl, and ns3::DefaultSimulatorImpl.
Referenced by ns3::Simulator::GetDelayLeft().
GetEventCount()
virtual uint64_t ns3::SimulatorImpl::GetEventCount (void) const pure virtual
Get the number of events executed.
Returns
The total number of events executed.
Implemented in ns3::VisualSimulatorImpl, ns3::NullMessageSimulatorImpl, ns3::DistributedSimulatorImpl, ns3::RealtimeSimulatorImpl, and ns3::DefaultSimulatorImpl.
Referenced by ns3::Simulator::GetEventCount().
GetMaximumSimulationTime()
virtual Time ns3::SimulatorImpl::GetMaximumSimulationTime (void) const pure virtual
Get the maximum representable simulation time.
Returns
The maximum simulation time at which an event can be scheduled.
The returned value will always be bigger than or equal to Simulator::Now.
Implemented in ns3::VisualSimulatorImpl, ns3::NullMessageSimulatorImpl, ns3::DistributedSimulatorImpl, ns3::RealtimeSimulatorImpl, and ns3::DefaultSimulatorImpl.
Referenced by ns3::Simulator::GetMaximumSimulationTime().
GetSystemId()
virtual uint32_t ns3::SimulatorImpl::GetSystemId () const pure virtual
Get the system id of this simulator.
The system id is the identifier for this simulator instance in a distributed simulation. For MPI this is the MPI rank.
Returns
The system id for this simulator.
Implemented in ns3::VisualSimulatorImpl, ns3::NullMessageSimulatorImpl, ns3::DistributedSimulatorImpl, ns3::RealtimeSimulatorImpl, and ns3::DefaultSimulatorImpl.
Referenced by ns3::Simulator::GetSystemId().
GetTypeId()
TypeId ns3::SimulatorImpl::GetTypeId (void) static
Get the registered TypeId for this class.
Returns
The object TypeId.
Definition at line 36 of file simulator-impl.cc.
References ns3::TypeId::SetParent().
IsExpired()
virtual bool ns3::SimulatorImpl::IsExpired (const EventId & id) const pure virtual
Check if an event has already run or been cancelled.
This method has O(1) complexity. Note that it is not possible to test for the expiration of events which were scheduled for the "destroy" time. Doing so will result in a program error (crash). An event is said to "expire" when it starts being scheduled which means that if the code executed by the event calls this function, it will get true.
Parameters
[in] id The event to test for expiration.
Returns
true if the event has expired, false otherwise.
Implemented in ns3::VisualSimulatorImpl, ns3::NullMessageSimulatorImpl, ns3::DistributedSimulatorImpl, ns3::DefaultSimulatorImpl, and ns3::RealtimeSimulatorImpl.
Referenced by ns3::Simulator::IsExpired().
IsFinished()
virtual bool ns3::SimulatorImpl::IsFinished (void) const pure virtual
Check if the simulation should finish.
Reasons to finish are because there are no more events lefts to be scheduled, or if simulation time has already reached the "stop time" (see Simulator::Stop()).
Returns
true if no more events or stop time reached.
Implemented in ns3::VisualSimulatorImpl, ns3::NullMessageSimulatorImpl, ns3::DistributedSimulatorImpl, ns3::RealtimeSimulatorImpl, and ns3::DefaultSimulatorImpl.
Referenced by ns3::Simulator::IsFinished().
Now()
virtual Time ns3::SimulatorImpl::Now (void) const pure virtual
Return the current simulation virtual time.
Returns
The current virtual time.
Implemented in ns3::VisualSimulatorImpl, ns3::NullMessageSimulatorImpl, ns3::DistributedSimulatorImpl, ns3::RealtimeSimulatorImpl, and ns3::DefaultSimulatorImpl.
Referenced by ns3::Simulator::Now().
Remove()
virtual void ns3::SimulatorImpl::Remove (const EventId & id) pure virtual
Remove an event from the event list.
This method has the same visible effect as the ns3::EventId::Cancel method but its algorithmic complexity is much higher: it has often O(log(n)) complexity, sometimes O(n), sometimes worse. Note that it is not possible to remove events which were scheduled for the "destroy" time. Doing so will result in a program error (crash).
Parameters
[in] id The event to remove from the list of scheduled events.
Implemented in ns3::VisualSimulatorImpl, ns3::NullMessageSimulatorImpl, ns3::DistributedSimulatorImpl, ns3::DefaultSimulatorImpl, and ns3::RealtimeSimulatorImpl.
Referenced by ns3::Simulator::Remove().
Run()
virtual void ns3::SimulatorImpl::Run (void) pure virtual
Run the simulation.
The simulation will run until one of:
No events are present anymore
The user called Simulator::Stop
The user called Simulator::Stop with a stop time and the expiration time of the next event to be processed is greater than or equal to the stop time.
Implemented in ns3::VisualSimulatorImpl, ns3::NullMessageSimulatorImpl, ns3::DistributedSimulatorImpl, ns3::RealtimeSimulatorImpl, and ns3::DefaultSimulatorImpl.
Referenced by ns3::Simulator::Run().
Schedule()
virtual EventId ns3::SimulatorImpl::Schedule (const Time & delay, EventImpl * event) pure virtual
Schedule a future event execution (in the same context).
Parameters
[in] delay Delay until the event expires.
[in] event The event to schedule.
Returns
A unique identifier for the newly-scheduled event.
Implemented in ns3::VisualSimulatorImpl, ns3::NullMessageSimulatorImpl, ns3::DistributedSimulatorImpl, ns3::RealtimeSimulatorImpl, and ns3::DefaultSimulatorImpl.
Referenced by ns3::Simulator::DoSchedule().
ScheduleDestroy()
virtual EventId ns3::SimulatorImpl::ScheduleDestroy (EventImpl * event) pure virtual
Schedule an event to run at the end of the simulation, after the Stop() time or condition has been reached.
Parameters
[in] event The event to schedule.
Returns
A unique identifier for the newly-scheduled event.
Implemented in ns3::VisualSimulatorImpl, ns3::NullMessageSimulatorImpl, ns3::DistributedSimulatorImpl, ns3::RealtimeSimulatorImpl, and ns3::DefaultSimulatorImpl.
Referenced by ns3::Simulator::DoScheduleDestroy().
ScheduleNow()
virtual EventId ns3::SimulatorImpl::ScheduleNow (EventImpl * event) pure virtual
Schedule an event to run at the current virtual time.
Parameters
[in] event The event to schedule.
Returns
A unique identifier for the newly-scheduled event.
Implemented in ns3::VisualSimulatorImpl, ns3::NullMessageSimulatorImpl, ns3::DistributedSimulatorImpl, ns3::RealtimeSimulatorImpl, and ns3::DefaultSimulatorImpl.
Referenced by ns3::Simulator::DoScheduleNow().
ScheduleWithContext()
virtual void ns3::SimulatorImpl::ScheduleWithContext (uint32_t context, const Time & delay, EventImpl * event) pure virtual
Schedule a future event execution (in a different context).
This method is thread-safe: it can be called from any thread.
Parameters
[in] delay Delay until the event expires.
[in] context Event context.
[in] event The event to schedule.
Returns
A unique identifier for the newly-scheduled event.
Implemented in ns3::VisualSimulatorImpl, ns3::NullMessageSimulatorImpl, ns3::DistributedSimulatorImpl, ns3::RealtimeSimulatorImpl, and ns3::DefaultSimulatorImpl.
Referenced by ns3::Simulator::ScheduleWithContext().
SetScheduler()
virtual void ns3::SimulatorImpl::SetScheduler (ObjectFactory schedulerFactory) pure virtual
Set the Scheduler to be used to manage the event list.
Parameters
[in] schedulerFactory A new event scheduler factory.
The event scheduler can be set at any time: the events scheduled in the previous scheduler will be transferred to the new scheduler before we start to use it.
Implemented in ns3::VisualSimulatorImpl, ns3::NullMessageSimulatorImpl, ns3::DistributedSimulatorImpl, ns3::RealtimeSimulatorImpl, and ns3::DefaultSimulatorImpl.
Referenced by ns3::Simulator::SetScheduler().
Stop() [1/2]
virtual void ns3::SimulatorImpl::Stop (const Time & delay) pure virtual
Schedule the time delay until the Simulator should stop.
Force the Simulator::Run method to return to the caller when the expiration time of the next event to be processed is greater than or equal to the stop time. The stop time is relative to the current simulation time.
Parameters
[in] delay The stop time, relative to the current time.
Implemented in ns3::VisualSimulatorImpl, ns3::NullMessageSimulatorImpl, ns3::DistributedSimulatorImpl, ns3::RealtimeSimulatorImpl, and ns3::DefaultSimulatorImpl.
Stop() [2/2]
virtual void ns3::SimulatorImpl::Stop (void) pure virtual
Tell the Simulator the calling event should be the last one executed.
If a running event invokes this method, it will be the last event executed by the Simulator::Run method before returning to the caller.
Implemented in ns3::VisualSimulatorImpl, ns3::NullMessageSimulatorImpl, ns3::DistributedSimulatorImpl, ns3::RealtimeSimulatorImpl, and ns3::DefaultSimulatorImpl.
Referenced by ns3::Simulator::Stop().
The documentation for this class was generated from the following files:
src/core/model/simulator-impl.h
src/core/model/simulator-impl.cc