ns-3: ns3::UdpServer Class Reference
ns3::UdpServer Class Reference
Applications » UdpClientServer
A UDP server, receives UDP packets from a remote host.
#include "udp-server.h"
Public Member Functions
UdpServer ()
virtual ~UdpServer ()
uint32_t GetLost (void) const
Returns the number of lost packets.
uint16_t GetPacketWindowSize () const
Returns the size of the window used for checking loss.
uint64_t GetReceived (void) const
Returns the number of received packets.
void SetPacketWindowSize (uint16_t size)
Set the size of the window used for checking loss.
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Application
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void HandleRead (Ptr< Socket > socket)
Handle a packet reception.
virtual void StartApplication (void)
Application specific startup code.
virtual void StopApplication (void)
Application specific shutdown code.
Private Attributes
PacketLossCounter m_lossCounter
Lost packet counter.
uint16_t m_port
Port on which we listen for incoming packets.
uint64_t m_received
Number of received packets.
TracedCallback< Ptr< const Packet > > m_rxTrace
Callbacks for tracing the packet Rx events.
TracedCallback< Ptr< const Packet >, const Address &, const Address & > m_rxTraceWithAddresses
Callbacks for tracing the packet Rx events, includes source and destination addresses.
Ptr< Socket > m_socket
IPv4 Socket.
Ptr< Socket > m_socket6
IPv6 Socket.
Additional Inherited Members
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A UDP server, receives UDP packets from a remote host.
UDP packets carry a 32bits sequence number followed by a 64bits time stamp in their payloads. The application uses the sequence number to determine if a packet is lost, and the time stamp to compute the delay.
Config Paths
ns3::UdpServer is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/ApplicationList/[i]/$ns3::UdpServer"
Attributes
Port: Port on which we listen for incoming packets.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 100
Flags: construct write read
PacketWindowSize: The size of the window used to compute the packet loss. This value should be a multiple of 8.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 8:256
Initial value: 32
Flags: construct write read
Attributes defined in parent class ns3::Application
StartTime: Time at which the application will start
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
StopTime: Time at which the application will stop
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
TraceSources
Rx: A packet has been received
Callback signature: ns3::Packet::TracedCallback
RxWithAddresses: A packet has been received
Callback signature: ns3::Packet::TwoAddressTracedCallback
Size of this type is 208 bytes (on a 64-bit architecture).
Definition at line 48 of file udp-server.h.
Constructor & Destructor Documentation
UdpServer()
ns3::UdpServer::UdpServer ()
Definition at line 72 of file udp-server.cc.
References m_received, and NS_LOG_FUNCTION.
~UdpServer()
ns3::UdpServer::~UdpServer () virtual
Definition at line 79 of file udp-server.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::UdpServer::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Application.
Definition at line 113 of file udp-server.cc.
References ns3::Application::DoDispose(), and NS_LOG_FUNCTION.
GetLost()
uint32_t ns3::UdpServer::GetLost (void) const
Returns the number of lost packets.
Returns
the number of lost packets
Definition at line 99 of file udp-server.cc.
References ns3::PacketLossCounter::GetLost(), m_lossCounter, and NS_LOG_FUNCTION.
GetPacketWindowSize()
uint16_t ns3::UdpServer::GetPacketWindowSize () const
Returns the size of the window used for checking loss.
Returns
the size of the window used for checking loss.
Definition at line 85 of file udp-server.cc.
References ns3::PacketLossCounter::GetBitMapSize(), m_lossCounter, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetReceived()
uint64_t ns3::UdpServer::GetReceived (void) const
Returns the number of received packets.
Returns
the number of received packets
Definition at line 106 of file udp-server.cc.
References m_received, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::UdpServer::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 45 of file udp-server.cc.
References GetPacketWindowSize(), m_port, m_rxTrace, m_rxTraceWithAddresses, ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), SetPacketWindowSize(), and ns3::TypeId::SetParent().
Referenced by ns3::UdpServerHelper::UdpServerHelper().
HandleRead()
void ns3::UdpServer::HandleRead (Ptr< Socket > socket) private
Handle a packet reception.
This function is called by lower layers.
Parameters
socket the socket the packet was received to.
Definition at line 166 of file udp-server.cc.
References ns3::Inet6SocketAddress::ConvertFrom(), ns3::InetSocketAddress::ConvertFrom(), ns3::InetSocketAddress::GetIpv4(), ns3::Inet6SocketAddress::GetIpv6(), ns3::SeqTsHeader::GetSeq(), ns3::Packet::GetSize(), ns3::Socket::GetSockName(), ns3::SeqTsHeader::GetTs(), ns3::Packet::GetUid(), ns3::Inet6SocketAddress::IsMatchingType(), ns3::InetSocketAddress::IsMatchingType(), m_lossCounter, m_received, m_rxTrace, m_rxTraceWithAddresses, ns3::PacketLossCounter::NotifyReceived(), ns3::Simulator::Now(), NS_LOG_FUNCTION, NS_LOG_INFO, ns3::Socket::RecvFrom(), and ns3::Packet::RemoveHeader().
Referenced by StartApplication().
SetPacketWindowSize()
void ns3::UdpServer::SetPacketWindowSize (uint16_t size)
Set the size of the window used for checking loss.
This value should be a multiple of 8
Parameters
size the size of the window used for checking loss. This value should be a multiple of 8
Definition at line 92 of file udp-server.cc.
References m_lossCounter, NS_LOG_FUNCTION, and ns3::PacketLossCounter::SetBitMapSize().
Referenced by GetTypeId().
StartApplication()
void ns3::UdpServer::StartApplication (void) private virtual
Application specific startup code.
The StartApplication method is called at the start time specified by Start This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 120 of file udp-server.cc.
References ns3::Socket::Bind(), ns3::Socket::CreateSocket(), ns3::Ipv6Address::GetAny(), ns3::Ipv4Address::GetAny(), ns3::Application::GetNode(), HandleRead(), ns3::TypeId::LookupByName(), m_port, m_socket, m_socket6, ns3::MakeCallback(), NS_FATAL_ERROR, NS_LOG_FUNCTION, and ns3::Socket::SetRecvCallback().
StopApplication()
void ns3::UdpServer::StopApplication (void) private virtual
Application specific shutdown code.
The StopApplication method is called at the stop time specified by Stop This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 155 of file udp-server.cc.
References m_socket, ns3::MakeNullCallback(), NS_LOG_FUNCTION, and ns3::Socket::SetRecvCallback().
Member Data Documentation
m_lossCounter
PacketLossCounter ns3::UdpServer::m_lossCounter private
Lost packet counter.
Definition at line 104 of file udp-server.h.
Referenced by GetLost(), GetPacketWindowSize(), HandleRead(), and SetPacketWindowSize().
m_port
uint16_t ns3::UdpServer::m_port private
Port on which we listen for incoming packets.
Definition at line 100 of file udp-server.h.
Referenced by GetTypeId(), and StartApplication().
m_received
uint64_t ns3::UdpServer::m_received private
Number of received packets.
Definition at line 103 of file udp-server.h.
Referenced by UdpServer(), GetReceived(), and HandleRead().
m_rxTrace
TracedCallback<Ptr<const Packet> > ns3::UdpServer::m_rxTrace private
Callbacks for tracing the packet Rx events.
Definition at line 107 of file udp-server.h.
Referenced by GetTypeId(), and HandleRead().
m_rxTraceWithAddresses
TracedCallback<Ptr<const Packet>, const Address &, const Address &> ns3::UdpServer::m_rxTraceWithAddresses private
Callbacks for tracing the packet Rx events, includes source and destination addresses.
Definition at line 110 of file udp-server.h.
Referenced by GetTypeId(), and HandleRead().
m_socket
Ptr<Socket> ns3::UdpServer::m_socket private
IPv4 Socket.
Definition at line 101 of file udp-server.h.
Referenced by StartApplication(), and StopApplication().
m_socket6
Ptr<Socket> ns3::UdpServer::m_socket6 private
IPv6 Socket.
Definition at line 102 of file udp-server.h.
Referenced by StartApplication().
The documentation for this class was generated from the following files:
src/applications/model/udp-server.h
src/applications/model/udp-server.cc