ns-3: ns3::PacketMetadata::ItemIterator Class Reference
ns3::PacketMetadata::ItemIterator Class Reference
Iterator class for metadata items.
#include "packet-metadata.h"
Public Member Functions
ItemIterator (const PacketMetadata *metadata, Buffer buffer)
Constructor.
bool HasNext (void) const
Checks if there is another metadata item.
Item Next (void)
Retrieve the next metadata item.
Private Attributes
Buffer m_buffer
buffer the metadata refers to
uint16_t m_current
current position
bool m_hasReadTail
true if the metadata tail has been read
const PacketMetadata * m_metadata
pointer to the metadata
uint32_t m_offset
offset
Detailed Description
Iterator class for metadata items.
Definition at line 128 of file packet-metadata.h.
Constructor & Destructor Documentation
ItemIterator()
ns3::PacketMetadata::ItemIterator::ItemIterator (const PacketMetadata * metadata, Buffer buffer)
Constructor.
Parameters
metadata a pointer to the metadata
buffer the buffer the metadata refers to
Definition at line 1051 of file packet-metadata.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
HasNext()
bool ns3::PacketMetadata::ItemIterator::HasNext (void) const
Checks if there is another metadata item.
Returns
true if there is another item
Definition at line 1061 of file packet-metadata.cc.
References NS_LOG_FUNCTION.
Referenced by PacketMetadataTest::CheckHistory(), ns3::PyViz::FilterPacket(), and ns3::Packet::Print().
Next()
PacketMetadata::Item ns3::PacketMetadata::ItemIterator::Next (void)
Retrieve the next metadata item.
Returns
the next metadata item
Definition at line 1075 of file packet-metadata.cc.
References ns3::PacketMetadata::Item::current, ns3::PacketMetadata::Item::currentSize, ns3::PacketMetadata::Item::currentTrimedFromEnd, ns3::PacketMetadata::Item::currentTrimedFromStart, ns3::PacketMetadata::ExtraItem::fragmentEnd, ns3::PacketMetadata::ExtraItem::fragmentStart, ns3::Header::GetTypeId(), ns3::Trailer::GetTypeId(), ns3::PacketMetadata::Item::HEADER, ns3::TypeId::IsChildOf(), ns3::PacketMetadata::Item::isFragment, ns3::Buffer::Iterator::Next(), ns3::PacketMetadata::SmallItem::next, NS_ASSERT, NS_LOG_FUNCTION, ns3::PacketMetadata::Item::PAYLOAD, ns3::Buffer::Iterator::Prev(), ns3::TypeId::SetUid(), ns3::PacketMetadata::SmallItem::size, ns3::PacketMetadata::Item::tid, ns3::PacketMetadata::Item::TRAILER, ns3::PacketMetadata::Item::type, and ns3::PacketMetadata::SmallItem::typeUid.
Referenced by PacketMetadataTest::CheckHistory(), ns3::PyViz::FilterPacket(), and ns3::Packet::Print().
Member Data Documentation
m_buffer
Buffer ns3::PacketMetadata::ItemIterator::m_buffer private
buffer the metadata refers to
Definition at line 149 of file packet-metadata.h.
m_current
uint16_t ns3::PacketMetadata::ItemIterator::m_current private
current position
Definition at line 150 of file packet-metadata.h.
m_hasReadTail
bool ns3::PacketMetadata::ItemIterator::m_hasReadTail private
true if the metadata tail has been read
Definition at line 152 of file packet-metadata.h.
m_metadata
const PacketMetadata* ns3::PacketMetadata::ItemIterator::m_metadata private
pointer to the metadata
Definition at line 148 of file packet-metadata.h.
m_offset
uint32_t ns3::PacketMetadata::ItemIterator::m_offset private
offset
Definition at line 151 of file packet-metadata.h.
The documentation for this class was generated from the following files:
src/network/model/packet-metadata.h
src/network/model/packet-metadata.cc