ns-3: ns3::RipNgHeader Class Reference
ns3::RipNgHeader Class Reference
Internet » IPv6 Routing Protocols. » RIPng
RipNgHeader - see RFC 2080
#include "ripng-header.h"
Public Types
enum Command_e { REQUEST = 0x1 , RESPONSE = 0x2 }
Commands to be used in RipNg headers.
Public Member Functions
RipNgHeader (void)
void AddRte (RipNgRte rte)
Add a RTE to the message.
void ClearRtes ()
Clear all the RTEs from the header.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
Command_e GetCommand (void) const
Get the command.
virtual TypeId GetInstanceTypeId (void) const
Return the instance type identifier.
std::list< RipNgRte > GetRteList (void) const
Get the list of the RTEs included in the message.
uint16_t GetRteNumber (void) const
Get the number of RTE included in the message.
virtual uint32_t GetSerializedSize (void) const
Get the serialized size of the packet.
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetCommand (Command_e command)
Set the command.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_command
command type
std::list< RipNgRte > m_rteList
list of the RTEs in the message
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
RipNgHeader - see RFC 2080
Introspection did not find any typical Config paths.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 40 bytes (on a 64-bit architecture).
Definition at line 146 of file ripng-header.h.
Member Enumeration Documentation
Command_e
enum ns3::RipNgHeader::Command_e
Commands to be used in RipNg headers.
Enumerator
REQUEST
RESPONSE
Definition at line 187 of file ripng-header.h.
Constructor & Destructor Documentation
RipNgHeader()
ns3::RipNgHeader::RipNgHeader (void)
Definition at line 138 of file ripng-header.cc.
Member Function Documentation
AddRte()
void ns3::RipNgHeader::AddRte (RipNgRte rte)
Add a RTE to the message.
Parameters
rte the RTE
Definition at line 238 of file ripng-header.cc.
References m_rteList.
Referenced by ns3::RipNg::DoSendRouteUpdate(), ns3::RipNg::HandleRequests(), and ns3::RipNg::SendRouteRequest().
ClearRtes()
void ns3::RipNgHeader::ClearRtes ()
Clear all the RTEs from the header.
Definition at line 243 of file ripng-header.cc.
References m_rteList.
Referenced by ns3::RipNg::DoSendRouteUpdate(), and ns3::RipNg::HandleRequests().
Deserialize()
uint32_t ns3::RipNgHeader::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start Buffer iterator
Returns
size of the packet
Implements ns3::Header.
Definition at line 190 of file ripng-header.cc.
References ns3::RipNgRte::Deserialize(), ns3::Buffer::Iterator::GetRemainingSize(), GetSerializedSize(), m_command, m_rteList, sample-rng-plot::n, ns3::Buffer::Iterator::Next(), NS_LOG_LOGIC, ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU8(), REQUEST, RESPONSE, and visualizer.core::start().
GetCommand()
RipNgHeader::Command_e ns3::RipNgHeader::GetCommand (void) const
Get the command.
Returns
the command
Definition at line 233 of file ripng-header.cc.
References m_command.
Referenced by ns3::RipNg::Receive().
GetInstanceTypeId()
TypeId ns3::RipNgHeader::GetInstanceTypeId (void) const virtual
Return the instance type identifier.
Returns
instance type ID
Implements ns3::ObjectBase.
Definition at line 152 of file ripng-header.cc.
References GetTypeId().
GetRteList()
std::list< RipNgRte > ns3::RipNgHeader::GetRteList (void) const
Get the list of the RTEs included in the message.
Returns
the list of the RTEs in the message
Definition at line 253 of file ripng-header.cc.
References m_rteList.
Referenced by ns3::RipNg::HandleRequests(), ns3::RipNg::HandleResponses(), and Ipv6RipngSplitHorizonStrategyTest::ReceivePktProbe().
GetRteNumber()
uint16_t ns3::RipNgHeader::GetRteNumber (void) const
Get the number of RTE included in the message.
Returns
the number of RTE in the message
Definition at line 248 of file ripng-header.cc.
References m_rteList.
Referenced by ns3::RipNg::DoSendRouteUpdate(), and ns3::RipNg::HandleRequests().
GetSerializedSize()
uint32_t ns3::RipNgHeader::GetSerializedSize (void) const virtual
Get the serialized size of the packet.
Returns
size
Implements ns3::Header.
Definition at line 168 of file ripng-header.cc.
References ns3::RipNgRte::GetSerializedSize(), and m_rteList.
Referenced by Deserialize(), ns3::RipNg::DoSendRouteUpdate(), and ns3::RipNg::HandleRequests().
GetTypeId()
TypeId ns3::RipNgHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 143 of file ripng-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::RipNgHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 157 of file ripng-header.cc.
References m_command, and m_rteList.
Referenced by ns3::operator<<().
Serialize()
void ns3::RipNgHeader::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start Buffer iterator
Implements ns3::Header.
Definition at line 174 of file ripng-header.cc.
References m_command, m_rteList, ns3::Buffer::Iterator::Next(), visualizer.core::start(), ns3::Buffer::Iterator::WriteU16(), and ns3::Buffer::Iterator::WriteU8().
SetCommand()
void ns3::RipNgHeader::SetCommand (RipNgHeader::Command_e command)
Set the command.
Parameters
command the command
Definition at line 228 of file ripng-header.cc.
References m_command.
Referenced by ns3::RipNg::DoSendRouteUpdate(), ns3::RipNg::HandleRequests(), and ns3::RipNg::SendRouteRequest().
Member Data Documentation
m_command
uint8_t ns3::RipNgHeader::m_command private
command type
Definition at line 229 of file ripng-header.h.
Referenced by Deserialize(), GetCommand(), Print(), Serialize(), and SetCommand().
m_rteList
std::list<RipNgRte> ns3::RipNgHeader::m_rteList private
list of the RTEs in the message
Definition at line 230 of file ripng-header.h.
Referenced by AddRte(), ClearRtes(), Deserialize(), GetRteList(), GetRteNumber(), GetSerializedSize(), Print(), and Serialize().
The documentation for this class was generated from the following files:
src/internet/model/ripng-header.h
src/internet/model/ripng-header.cc