ns-3: ns3::TcpL4Protocol Class Reference
ns3::TcpL4Protocol Class Reference
Internet » TCP
TCP socket creation and multiplexing/demultiplexing.
#include "tcp-l4-protocol.h"
Public Member Functions
TcpL4Protocol ()
virtual ~TcpL4Protocol ()
void AddSocket (Ptr< TcpSocketBase > socket)
Make a socket fully operational.
Ipv4EndPoint * Allocate (Ipv4Address address)
Allocate an IPv4 Endpoint.
Ipv4EndPoint * Allocate (Ptr< NetDevice > boundNetDevice, Ipv4Address address, uint16_t port)
Allocate an IPv4 Endpoint.
Ipv4EndPoint * Allocate (Ptr< NetDevice > boundNetDevice, Ipv4Address localAddress, uint16_t localPort, Ipv4Address peerAddress, uint16_t peerPort)
Allocate an IPv4 Endpoint.
Ipv4EndPoint * Allocate (Ptr< NetDevice > boundNetDevice, uint16_t port)
Allocate an IPv4 Endpoint.
Ipv4EndPoint * Allocate (void)
Allocate an IPv4 Endpoint.
Ipv6EndPoint * Allocate6 (Ipv6Address address)
Allocate an IPv6 Endpoint.
Ipv6EndPoint * Allocate6 (Ptr< NetDevice > boundNetDevice, Ipv6Address address, uint16_t port)
Allocate an IPv6 Endpoint.
Ipv6EndPoint * Allocate6 (Ptr< NetDevice > boundNetDevice, Ipv6Address localAddress, uint16_t localPort, Ipv6Address peerAddress, uint16_t peerPort)
Allocate an IPv6 Endpoint.
Ipv6EndPoint * Allocate6 (Ptr< NetDevice > boundNetDevice, uint16_t port)
Allocate an IPv6 Endpoint.
Ipv6EndPoint * Allocate6 (void)
Allocate an IPv6 Endpoint.
Ptr< Socket > CreateSocket (TypeId congestionTypeId)
Create a TCP socket using the specified congestion control algorithm.
Ptr< Socket > CreateSocket (TypeId congestionTypeId, TypeId recoveryTypeId)
Create a TCP socket using the specified congestion control algorithm TypeId.
Ptr< Socket > CreateSocket (void)
Create a TCP socket using the TypeId set by SocketType attribute.
void DeAllocate (Ipv4EndPoint *endPoint)
Remove an IPv4 Endpoint.
void DeAllocate (Ipv6EndPoint *endPoint)
Remove an IPv6 Endpoint.
virtual IpL4Protocol::DownTargetCallback GetDownTarget (void) const
This method allows a caller to get the current down target callback set for this L4 protocol (IPv4 case)
virtual IpL4Protocol::DownTargetCallback6 GetDownTarget6 (void) const
This method allows a caller to get the current down target callback set for this L4 protocol (IPv6 case)
virtual int GetProtocolNumber (void) const
Returns the protocol number of this protocol.
virtual enum IpL4Protocol::RxStatus Receive (Ptr< Packet > p, Ipv4Header const &incomingIpHeader, Ptr< Ipv4Interface > incomingInterface)
Called from lower-level layers to send the packet up in the stack.
virtual enum IpL4Protocol::RxStatus Receive (Ptr< Packet > p, Ipv6Header const &incomingIpHeader, Ptr< Ipv6Interface > incomingInterface)
Called from lower-level layers to send the packet up in the stack.
virtual void ReceiveIcmp (Ipv4Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo, Ipv4Address payloadSource, Ipv4Address payloadDestination, const uint8_t payload[8])
Called from lower-level layers to send the ICMP packet up in the stack.
virtual void ReceiveIcmp (Ipv6Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo, Ipv6Address payloadSource, Ipv6Address payloadDestination, const uint8_t payload[8])
Called from lower-level layers to send the ICMPv6 packet up in the stack.
bool RemoveSocket (Ptr< TcpSocketBase > socket)
Remove a socket from the internal list.
void SendPacket (Ptr< Packet > pkt, const TcpHeader &outgoing, const Address &saddr, const Address &daddr, Ptr< NetDevice > oif=0) const
Send a packet via TCP (IP-agnostic)
virtual void SetDownTarget (IpL4Protocol::DownTargetCallback cb)
This method allows a caller to set the current down target callback set for this L4 protocol (IPv4 case)
virtual void SetDownTarget6 (IpL4Protocol::DownTargetCallback6 cb)
This method allows a caller to set the current down target callback set for this L4 protocol (IPv6 case)
void SetNode (Ptr< Node > node)
Set node associated with this stack.
Public Member Functions inherited from ns3::IpL4Protocol
virtual ~IpL4Protocol ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::IpL4Protocol
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static const uint8_t PROT_NUMBER = 6
protocol number (0x6)
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
void NoEndPointsFound (const TcpHeader &incomingHeader, const Address &incomingSAddr, const Address &incomingDAddr)
Check if RST packet should be sent, and in case, send it.
virtual void NotifyNewAggregate ()
Setup socket factory and callbacks when aggregated to a node.
enum IpL4Protocol::RxStatus PacketReceived (Ptr< Packet > packet, TcpHeader &incomingTcpHeader, const Address &source, const Address &destination)
Get the tcp header of the incoming packet and checks its checksum if needed.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
TcpL4Protocol (const TcpL4Protocol &)
Copy constructor.
TcpL4Protocol & operator= (const TcpL4Protocol &)
Copy constructor.
void SendPacketV4 (Ptr< Packet > pkt, const TcpHeader &outgoing, const Ipv4Address &saddr, const Ipv4Address &daddr, Ptr< NetDevice > oif=0) const
Send a packet via TCP (IPv4)
void SendPacketV6 (Ptr< Packet > pkt, const TcpHeader &outgoing, const Ipv6Address &saddr, const Ipv6Address &daddr, Ptr< NetDevice > oif=0) const
Send a packet via TCP (IPv6)
Private Attributes
TypeId m_congestionTypeId
The socket TypeId.
IpL4Protocol::DownTargetCallback m_downTarget
Callback to send packets over IPv4.
IpL4Protocol::DownTargetCallback6 m_downTarget6
Callback to send packets over IPv6.
Ipv4EndPointDemux * m_endPoints
A list of IPv4 end points.
Ipv6EndPointDemux * m_endPoints6
A list of IPv6 end points.
Ptr< Node > m_node
the node this stack is associated with
TypeId m_recoveryTypeId
The recovery TypeId.
TypeId m_rttTypeId
The RTT Estimator TypeId.
std::vector< Ptr< TcpSocketBase > > m_sockets
list of sockets
Additional Inherited Members
Public Types inherited from ns3::IpL4Protocol
typedef Callback< void, Ptr< Packet >, Ipv4Address, Ipv4Address, uint8_t, Ptr< Ipv4Route > > DownTargetCallback
callback to send packets over IPv4
typedef Callback< void, Ptr< Packet >, Ipv6Address, Ipv6Address, uint8_t, Ptr< Ipv6Route > > DownTargetCallback6
callback to send packets over IPv6
enum RxStatus { RX_OK , RX_CSUM_FAILED , RX_ENDPOINT_CLOSED , RX_ENDPOINT_UNREACH }
Rx status codes.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
TCP socket creation and multiplexing/demultiplexing.
A single instance of this class is held by one instance of class Node.
The creation of TcpSocket are handled in the method CreateSocket, which is called by TcpSocketFactory. Upon creation, this class is responsible to the socket initialization and handle multiplexing/demultiplexing of data between node's TCP sockets. Demultiplexing is done by receiving packets from IP, and forwards them up to the right socket. Multiplexing is done through the SendPacket function, which sends the packet down the stack.
Moreover, this class allocates "endpoint" objects (ns3::Ipv4EndPoint) for TCP, and SHOULD checksum packets its receives from the socket layer going down the stack, but currently checksumming is disabled.
See also
CreateSocket
NotifyNewAggregate
SendPacket
Config Paths
ns3::TcpL4Protocol is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::TcpL4Protocol"
Attributes
RttEstimatorType: Type of RttEstimator objects.
Set with class: TypeIdValue
Underlying type: TypeId
Initial value: ns3::RttMeanDeviation
Flags: construct write read
SocketType: Socket type of TCP objects.
Set with class: TypeIdValue
Underlying type: TypeId
Initial value: ns3::TcpNewReno
Flags: construct write read
RecoveryType: Recovery type of TCP objects.
Set with class: TypeIdValue
Underlying type: TypeId
Initial value: ns3::TcpPrrRecovery
Flags: construct write read
SocketList: The list of sockets associated to this protocol.
Set with class: ns3::ObjectPtrContainerValue
Underlying type: ns3::Ptr< ns3::TcpSocketBase>
Flags: read
Attributes defined in parent class ns3::IpL4Protocol
ProtocolNumber: The IP protocol number.
Set with class: ns3::IntegerValue
Underlying type: int32_t 0:255
Flags: read
No TraceSources are defined for this type.
Size of this type is 104 bytes (on a 64-bit architecture).
Definition at line 80 of file tcp-l4-protocol.h.
Constructor & Destructor Documentation
TcpL4Protocol() [1/2]
ns3::TcpL4Protocol::TcpL4Protocol ()
Definition at line 98 of file tcp-l4-protocol.cc.
References NS_LOG_FUNCTION.
~TcpL4Protocol()
ns3::TcpL4Protocol::~TcpL4Protocol () virtual
Definition at line 104 of file tcp-l4-protocol.cc.
References NS_LOG_FUNCTION.
TcpL4Protocol() [2/2]
ns3::TcpL4Protocol::TcpL4Protocol (const TcpL4Protocol &) private
Copy constructor.
Defined and not implemented to avoid misuse
Member Function Documentation
AddSocket()
void ns3::TcpL4Protocol::AddSocket (Ptr< TcpSocketBase > socket)
Make a socket fully operational.
Called after a socket has been bound, it is inserted in an internal vector.
Parameters
socket Socket to be added
Definition at line 706 of file tcp-l4-protocol.cc.
References m_sockets, and NS_LOG_FUNCTION.
Allocate() [1/5]
Ipv4EndPoint * ns3::TcpL4Protocol::Allocate (Ipv4Address address)
Allocate an IPv4 Endpoint.
Parameters
address address to use
Returns
the Endpoint
Definition at line 229 of file tcp-l4-protocol.cc.
References first::address, ns3::Ipv4EndPointDemux::Allocate(), m_endPoints, and NS_LOG_FUNCTION.
Allocate() [2/5]
Ipv4EndPoint * ns3::TcpL4Protocol::Allocate (Ptr< NetDevice > boundNetDevice, Ipv4Address address, uint16_t port)
Allocate an IPv4 Endpoint.
Parameters
boundNetDevice Bound NetDevice (if any)
address address to use
port port to use
Returns
the Endpoint
Definition at line 243 of file tcp-l4-protocol.cc.
References first::address, ns3::Ipv4EndPointDemux::Allocate(), m_endPoints, NS_LOG_FUNCTION, and port.
Allocate() [3/5]
Ipv4EndPoint * ns3::TcpL4Protocol::Allocate (Ptr< NetDevice > boundNetDevice, Ipv4Address localAddress, uint16_t localPort, Ipv4Address peerAddress, uint16_t peerPort)
Allocate an IPv4 Endpoint.
Parameters
boundNetDevice Bound NetDevice (if any)
localAddress local address to use
localPort local port to use
peerAddress remote address to use
peerPort remote port to use
Returns
the Endpoint
Definition at line 250 of file tcp-l4-protocol.cc.
References ns3::Ipv4EndPointDemux::Allocate(), m_endPoints, and NS_LOG_FUNCTION.
Allocate() [4/5]
Ipv4EndPoint * ns3::TcpL4Protocol::Allocate (Ptr< NetDevice > boundNetDevice, uint16_t port)
Allocate an IPv4 Endpoint.
Parameters
boundNetDevice Bound NetDevice (if any)
port port to use
Returns
the Endpoint
Definition at line 236 of file tcp-l4-protocol.cc.
References ns3::Ipv4EndPointDemux::Allocate(), m_endPoints, NS_LOG_FUNCTION, and port.
Allocate() [5/5]
Ipv4EndPoint * ns3::TcpL4Protocol::Allocate (void)
Allocate an IPv4 Endpoint.
Returns
the Endpoint
Definition at line 222 of file tcp-l4-protocol.cc.
References ns3::Ipv4EndPointDemux::Allocate(), m_endPoints, and NS_LOG_FUNCTION.
Allocate6() [1/5]
Ipv6EndPoint * ns3::TcpL4Protocol::Allocate6 (Ipv6Address address)
Allocate an IPv6 Endpoint.
Parameters
address address to use
Returns
the Endpoint
Definition at line 275 of file tcp-l4-protocol.cc.
References first::address, ns3::Ipv6EndPointDemux::Allocate(), m_endPoints6, and NS_LOG_FUNCTION.
Allocate6() [2/5]
Ipv6EndPoint * ns3::TcpL4Protocol::Allocate6 (Ptr< NetDevice > boundNetDevice, Ipv6Address address, uint16_t port)
Allocate an IPv6 Endpoint.
Parameters
boundNetDevice Bound NetDevice (if any)
address address to use
port port to use
Returns
the Endpoint
Definition at line 289 of file tcp-l4-protocol.cc.
References first::address, ns3::Ipv6EndPointDemux::Allocate(), m_endPoints6, NS_LOG_FUNCTION, and port.
Allocate6() [3/5]
Ipv6EndPoint * ns3::TcpL4Protocol::Allocate6 (Ptr< NetDevice > boundNetDevice, Ipv6Address localAddress, uint16_t localPort, Ipv6Address peerAddress, uint16_t peerPort)
Allocate an IPv6 Endpoint.
Parameters
boundNetDevice Bound NetDevice (if any)
localAddress local address to use
localPort local port to use
peerAddress remote address to use
peerPort remote port to use
Returns
the Endpoint
Definition at line 296 of file tcp-l4-protocol.cc.
References ns3::Ipv6EndPointDemux::Allocate(), m_endPoints6, and NS_LOG_FUNCTION.
Allocate6() [4/5]
Ipv6EndPoint * ns3::TcpL4Protocol::Allocate6 (Ptr< NetDevice > boundNetDevice, uint16_t port)
Allocate an IPv6 Endpoint.
Parameters
boundNetDevice Bound NetDevice (if any)
port port to use
Returns
the Endpoint
Definition at line 282 of file tcp-l4-protocol.cc.
References ns3::Ipv6EndPointDemux::Allocate(), m_endPoints6, NS_LOG_FUNCTION, and port.
Allocate6() [5/5]
Ipv6EndPoint * ns3::TcpL4Protocol::Allocate6 (void)
Allocate an IPv6 Endpoint.
Returns
the Endpoint
Definition at line 268 of file tcp-l4-protocol.cc.
References ns3::Ipv6EndPointDemux::Allocate(), m_endPoints6, and NS_LOG_FUNCTION.
CreateSocket() [1/3]
Ptr< Socket > ns3::TcpL4Protocol::CreateSocket (TypeId congestionTypeId)
Create a TCP socket using the specified congestion control algorithm.
Returns
A smart Socket pointer to a TcpSocket allocated by this instance of the TCP protocol
Parameters
congestionTypeId the congestion control algorithm TypeId
Definition at line 184 of file tcp-l4-protocol.cc.
References CreateSocket(), and m_recoveryTypeId.
CreateSocket() [2/3]
Ptr< Socket > ns3::TcpL4Protocol::CreateSocket (TypeId congestionTypeId, TypeId recoveryTypeId)
Create a TCP socket using the specified congestion control algorithm TypeId.
Returns
A smart Socket pointer to a TcpSocket allocated by this instance of the TCP protocol
Warning
using a congestionTypeId other than TCP is a bad idea.
Parameters
congestionTypeId the congestion control algorithm TypeId
recoveryTypeId the recovery algorithm TypeId
Definition at line 190 of file tcp-l4-protocol.cc.
References ns3::ObjectFactory::Create(), ns3::TypeId::GetName(), m_node, m_rttTypeId, m_sockets, NS_LOG_FUNCTION, and ns3::ObjectFactory::SetTypeId().
CreateSocket() [3/3]
Ptr< Socket > ns3::TcpL4Protocol::CreateSocket (void)
Create a TCP socket using the TypeId set by SocketType attribute.
Returns
A smart Socket pointer to a TcpSocket allocated by this instance of the TCP protocol
Definition at line 216 of file tcp-l4-protocol.cc.
References m_congestionTypeId, and m_recoveryTypeId.
Referenced by CreateSocket().
DeAllocate() [1/2]
void ns3::TcpL4Protocol::DeAllocate (Ipv4EndPoint * endPoint)
Remove an IPv4 Endpoint.
Parameters
endPoint the end point to remove
Definition at line 261 of file tcp-l4-protocol.cc.
References ns3::Ipv4EndPointDemux::DeAllocate(), m_endPoints, and NS_LOG_FUNCTION.
DeAllocate() [2/2]
void ns3::TcpL4Protocol::DeAllocate (Ipv6EndPoint * endPoint)
Remove an IPv6 Endpoint.
Parameters
endPoint the end point to remove
Definition at line 307 of file tcp-l4-protocol.cc.
References ns3::Ipv6EndPointDemux::DeAllocate(), m_endPoints6, and NS_LOG_FUNCTION.
DoDispose()
void ns3::TcpL4Protocol::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 160 of file tcp-l4-protocol.cc.
References ns3::Object::DoDispose(), m_downTarget, m_downTarget6, m_endPoints, m_endPoints6, m_node, m_sockets, NS_LOG_FUNCTION, and ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::Nullify().
GetDownTarget()
IpL4Protocol::DownTargetCallback ns3::TcpL4Protocol::GetDownTarget (void) const virtual
This method allows a caller to get the current down target callback set for this L4 protocol (IPv4 case)
Returns
current Callback for the L4 protocol
Implements ns3::IpL4Protocol.
Definition at line 751 of file tcp-l4-protocol.cc.
References m_downTarget.
GetDownTarget6()
IpL4Protocol::DownTargetCallback6 ns3::TcpL4Protocol::GetDownTarget6 (void) const virtual
This method allows a caller to get the current down target callback set for this L4 protocol (IPv6 case)
Returns
current Callback for the L4 protocol
Implements ns3::IpL4Protocol.
Definition at line 763 of file tcp-l4-protocol.cc.
References m_downTarget6.
GetProtocolNumber()
int ns3::TcpL4Protocol::GetProtocolNumber (void) const virtual
Returns the protocol number of this protocol.
Returns
the protocol number.
Implements ns3::IpL4Protocol.
Definition at line 154 of file tcp-l4-protocol.cc.
References PROT_NUMBER.
GetTypeId()
TypeId ns3::TcpL4Protocol::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 69 of file tcp-l4-protocol.cc.
References ns3::RttMeanDeviation::GetTypeId(), ns3::TcpNewReno::GetTypeId(), ns3::TcpPrrRecovery::GetTypeId(), m_congestionTypeId, m_recoveryTypeId, m_rttTypeId, m_sockets, ns3::MakeObjectVectorAccessor(), ns3::MakeTypeIdAccessor(), ns3::MakeTypeIdChecker(), and ns3::TypeId::SetParent().
NoEndPointsFound()
void ns3::TcpL4Protocol::NoEndPointsFound (const TcpHeader & incomingHeader, const Address & incomingSAddr, const Address & incomingDAddr) protected
Check if RST packet should be sent, and in case, send it.
The function is called when no endpoint is found for the received packet. So TcpL4Protocol do not know to who the packet should be given to. An RST packet is sent out as reply unless the received packet has the RST flag set.
Parameters
incomingHeader TCP header of the incoming packet
incomingSAddr Source address of the incoming packet
incomingDAddr Destination address of the incoming packet
Definition at line 397 of file tcp-l4-protocol.cc.
References ns3::TcpHeader::ACK, ns3::TcpHeader::GetAckNumber(), ns3::TcpHeader::GetDestinationPort(), ns3::TcpHeader::GetFlags(), ns3::TcpHeader::GetSequenceNumber(), ns3::TcpHeader::GetSourcePort(), NS_LOG_FUNCTION, ns3::TcpHeader::RST, SendPacket(), ns3::TcpHeader::SetAckNumber(), ns3::TcpHeader::SetDestinationPort(), ns3::TcpHeader::SetFlags(), ns3::TcpHeader::SetSequenceNumber(), and ns3::TcpHeader::SetSourcePort().
NotifyNewAggregate()
void ns3::TcpL4Protocol::NotifyNewAggregate (void) protected virtual
Setup socket factory and callbacks when aggregated to a node.
This function will notify other components connected to the node that a new stack member is now connected. This will be used to notify Layer 3 protocol of layer 4 protocol stack to connect them together. The aggregation is completed by setting the node in the TCP stack, link it to the ipv4 or ipv6 stack and adding TCP socket factory to the node.
Reimplemented from ns3::Object.
Definition at line 117 of file tcp-l4-protocol.cc.
References ns3::Object::AggregateObject(), ns3::Object::GetObject(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_downTarget, m_downTarget6, m_node, ns3::MakeCallback(), ns3::Object::NotifyNewAggregate(), NS_LOG_FUNCTION, ns3::Ipv4::Send(), ns3::Ipv6::Send(), SetDownTarget(), SetDownTarget6(), and SetNode().
operator=()
TcpL4Protocol& ns3::TcpL4Protocol::operator= (const TcpL4Protocol &) private
Copy constructor.
Defined and not implemented to avoid misuse
Returns
PacketReceived()
enum IpL4Protocol::RxStatus ns3::TcpL4Protocol::PacketReceived (Ptr< Packet > packet, TcpHeader & incomingTcpHeader, const Address & source, const Address & destination) protected
Get the tcp header of the incoming packet and checks its checksum if needed.
Parameters
packet Received packet
incomingTcpHeader Overwritten with the tcp header of the packet
source Source address (an underlying Ipv4Address or Ipv6Address)
destination Destination address (an underlying Ipv4Address or Ipv6Address)
Returns
RX_CSUM_FAILED if the checksum check fails, RX_OK otherwise
Definition at line 341 of file tcp-l4-protocol.cc.
References ns3::Ipv6EndPoint::ForwardIcmp(), m_endPoints6, NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::Ipv6EndPointDemux::SimpleLookup().
Receive() [1/2]
enum IpL4Protocol::RxStatus ns3::TcpL4Protocol::Receive (Ptr< Packet > p, Ipv4Header const & header, Ptr< Ipv4Interface > incomingInterface) virtual
Called from lower-level layers to send the packet up in the stack.
Parameters
p packet to forward up
header IPv4 Header information
incomingInterface the Ipv4Interface on which the packet arrived
Returns
Rx status code
Implements ns3::IpL4Protocol.
Definition at line 397 of file tcp-l4-protocol.cc.
Receive() [2/2]
enum IpL4Protocol::RxStatus ns3::TcpL4Protocol::Receive (Ptr< Packet > p, Ipv6Header const & header, Ptr< Ipv6Interface > incomingInterface) virtual
Called from lower-level layers to send the packet up in the stack.
Parameters
p packet to forward up
header IPv6 Header information
incomingInterface the Ipv6Interface on which the packet arrived
Returns
Rx status code
Implements ns3::IpL4Protocol.
Definition at line 397 of file tcp-l4-protocol.cc.
ReceiveIcmp() [1/2]
void ns3::TcpL4Protocol::ReceiveIcmp (Ipv4Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo, Ipv4Address payloadSource, Ipv4Address payloadDestination, const uint8_t payload[8]) virtual
Called from lower-level layers to send the ICMP packet up in the stack.
Parameters
icmpSource the source address of the icmp message
icmpTtl the ttl of the icmp message
icmpType the 'type' field of the icmp message
icmpCode the 'code' field of the icmp message
icmpInfo extra information dependent on the icmp message generated by Icmpv4L4Protocol
payloadSource the source address of the packet which triggered the icmp message
payloadDestination the destination address of the packet which triggered the icmp message.
payload the first 8 bytes of the packet payload which triggered the icmp message.
Reimplemented from ns3::IpL4Protocol.
Definition at line 314 of file tcp-l4-protocol.cc.
References ns3::Ipv4EndPoint::ForwardIcmp(), m_endPoints, NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::Ipv4EndPointDemux::SimpleLookup().
ReceiveIcmp() [2/2]
void ns3::TcpL4Protocol::ReceiveIcmp (Ipv6Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo, Ipv6Address payloadSource, Ipv6Address payloadDestination, const uint8_t payload[8]) virtual
Called from lower-level layers to send the ICMPv6 packet up in the stack.
Parameters
icmpSource the source address of the icmp message
icmpTtl the ttl of the icmp message
icmpType the 'type' field of the icmp message
icmpCode the 'code' field of the icmp message
icmpInfo extra information dependent on the icmp message generated by Icmpv6L4Protocol
payloadSource the source address of the packet which triggered the icmp message
payloadDestination the destination address of the packet which triggered the icmp message.
payload the first 8 bytes of the packet payload which triggered the icmp message.
Reimplemented from ns3::IpL4Protocol.
Definition at line 341 of file tcp-l4-protocol.cc.
RemoveSocket()
bool ns3::TcpL4Protocol::RemoveSocket (Ptr< TcpSocketBase > socket)
Remove a socket from the internal list.
Parameters
socket socket to Remove
Returns
true if the socket has been removed
Definition at line 725 of file tcp-l4-protocol.cc.
References m_sockets, and NS_LOG_FUNCTION.
SendPacket()
void ns3::TcpL4Protocol::SendPacket (Ptr< Packet > pkt, const TcpHeader & outgoing, const Address & saddr, const Address & daddr, Ptr< NetDevice > oif = 0) const
Send a packet via TCP (IP-agnostic)
Parameters
pkt The packet to send
outgoing The packet header
saddr The source Ipv4Address
daddr The destination Ipv4Address
oif The output interface bound. Defaults to null (unspecified).
Definition at line 660 of file tcp-l4-protocol.cc.
References ns3::Inet6SocketAddress::ConvertFrom(), ns3::InetSocketAddress::ConvertFrom(), ns3::Ipv4Address::ConvertFrom(), ns3::Ipv6Address::ConvertFrom(), ns3::InetSocketAddress::GetIpv4(), ns3::Inet6SocketAddress::GetIpv6(), ns3::Inet6SocketAddress::IsMatchingType(), ns3::InetSocketAddress::IsMatchingType(), ns3::Ipv4Address::IsMatchingType(), ns3::Ipv6Address::IsMatchingType(), NS_ASSERT, NS_FATAL_ERROR, NS_LOG_FUNCTION, SendPacketV4(), and SendPacketV6().
Referenced by NoEndPointsFound(), and SendPacketV6().
SendPacketV4()
void ns3::TcpL4Protocol::SendPacketV4 (Ptr< Packet > pkt, const TcpHeader & outgoing, const Ipv4Address & saddr, const Ipv4Address & daddr, Ptr< NetDevice > oif = 0) const private
Send a packet via TCP (IPv4)
Parameters
pkt The packet to send
outgoing The packet header
saddr The source Ipv4Address
daddr The destination Ipv4Address
oif The output interface bound. Defaults to null (unspecified).
Todo:
UrgentPointer
Definition at line 555 of file tcp-l4-protocol.cc.
References ns3::Packet::AddHeader(), ns3::Node::ChecksumEnabled(), ns3::TcpHeader::EnableChecksums(), ns3::TcpHeader::FlagsToString(), ns3::TcpHeader::GetAckNumber(), ns3::TcpHeader::GetFlags(), ns3::Object::GetObject(), ns3::TcpHeader::GetSequenceNumber(), ns3::Packet::GetSize(), ns3::TcpHeader::InitializeChecksum(), m_downTarget, m_node, NS_FATAL_ERROR, NS_LOG_ERROR, NS_LOG_FUNCTION, NS_LOG_LOGIC, PROT_NUMBER, ns3::Ipv4Header::SetDestination(), ns3::Ipv4Header::SetProtocol(), and ns3::Ipv4Header::SetSource().
Referenced by SendPacket().
SendPacketV6()
void ns3::TcpL4Protocol::SendPacketV6 (Ptr< Packet > pkt, const TcpHeader & outgoing, const Ipv6Address & saddr, const Ipv6Address & daddr, Ptr< NetDevice > oif = 0) const private
Send a packet via TCP (IPv6)
Parameters
pkt The packet to send
outgoing The packet header
saddr The source Ipv4Address
daddr The destination Ipv4Address
oif The output interface bound. Defaults to null (unspecified).
Todo:
UrgentPointer
Definition at line 606 of file tcp-l4-protocol.cc.
References ns3::Packet::AddHeader(), ns3::Node::ChecksumEnabled(), ns3::TcpHeader::EnableChecksums(), ns3::TcpHeader::FlagsToString(), ns3::TcpHeader::GetAckNumber(), ns3::TcpHeader::GetFlags(), ns3::Ipv6Address::GetIpv4MappedAddress(), ns3::Object::GetObject(), ns3::TcpHeader::GetSequenceNumber(), ns3::Packet::GetSize(), ns3::TcpHeader::InitializeChecksum(), ns3::Ipv6Address::IsIpv4MappedAddress(), m_downTarget6, m_node, NS_FATAL_ERROR, NS_LOG_ERROR, NS_LOG_FUNCTION, NS_LOG_LOGIC, PROT_NUMBER, SendPacket(), ns3::Ipv6Header::SetDestinationAddress(), ns3::Ipv6Header::SetNextHeader(), and ns3::Ipv6Header::SetSourceAddress().
Referenced by SendPacket().
SetDownTarget()
void ns3::TcpL4Protocol::SetDownTarget (IpL4Protocol::DownTargetCallback cb) virtual
This method allows a caller to set the current down target callback set for this L4 protocol (IPv4 case)
Parameters
cb current Callback for the L4 protocol
Implements ns3::IpL4Protocol.
Definition at line 745 of file tcp-l4-protocol.cc.
References m_downTarget.
Referenced by NotifyNewAggregate().
SetDownTarget6()
void ns3::TcpL4Protocol::SetDownTarget6 (IpL4Protocol::DownTargetCallback6 cb) virtual
This method allows a caller to set the current down target callback set for this L4 protocol (IPv6 case)
Parameters
cb current Callback for the L4 protocol
Implements ns3::IpL4Protocol.
Definition at line 757 of file tcp-l4-protocol.cc.
References m_downTarget6.
Referenced by NotifyNewAggregate().
SetNode()
void ns3::TcpL4Protocol::SetNode (Ptr< Node > node)
Set node associated with this stack.
Parameters
node the node
Definition at line 110 of file tcp-l4-protocol.cc.
References m_node, and NS_LOG_FUNCTION.
Referenced by NotifyNewAggregate().
Member Data Documentation
m_congestionTypeId
TypeId ns3::TcpL4Protocol::m_congestionTypeId private
The socket TypeId.
Definition at line 321 of file tcp-l4-protocol.h.
Referenced by CreateSocket(), and GetTypeId().
m_downTarget
IpL4Protocol::DownTargetCallback ns3::TcpL4Protocol::m_downTarget private
Callback to send packets over IPv4.
Definition at line 324 of file tcp-l4-protocol.h.
Referenced by DoDispose(), GetDownTarget(), NotifyNewAggregate(), SendPacketV4(), and SetDownTarget().
m_downTarget6
IpL4Protocol::DownTargetCallback6 ns3::TcpL4Protocol::m_downTarget6 private
Callback to send packets over IPv6.
Definition at line 325 of file tcp-l4-protocol.h.
Referenced by DoDispose(), GetDownTarget6(), NotifyNewAggregate(), SendPacketV6(), and SetDownTarget6().
m_endPoints
Ipv4EndPointDemux* ns3::TcpL4Protocol::m_endPoints private
A list of IPv4 end points.
Definition at line 318 of file tcp-l4-protocol.h.
Referenced by Allocate(), DeAllocate(), DoDispose(), and ReceiveIcmp().
m_endPoints6
Ipv6EndPointDemux* ns3::TcpL4Protocol::m_endPoints6 private
A list of IPv6 end points.
Definition at line 319 of file tcp-l4-protocol.h.
Referenced by Allocate6(), DeAllocate(), DoDispose(), and PacketReceived().
m_node
Ptr<Node> ns3::TcpL4Protocol::m_node private
the node this stack is associated with
Definition at line 317 of file tcp-l4-protocol.h.
Referenced by CreateSocket(), DoDispose(), NotifyNewAggregate(), SendPacketV4(), SendPacketV6(), and SetNode().
m_recoveryTypeId
TypeId ns3::TcpL4Protocol::m_recoveryTypeId private
The recovery TypeId.
Definition at line 322 of file tcp-l4-protocol.h.
Referenced by CreateSocket(), and GetTypeId().
m_rttTypeId
TypeId ns3::TcpL4Protocol::m_rttTypeId private
The RTT Estimator TypeId.
Definition at line 320 of file tcp-l4-protocol.h.
Referenced by CreateSocket(), and GetTypeId().
m_sockets
std::vector<Ptr<TcpSocketBase> > ns3::TcpL4Protocol::m_sockets private
list of sockets
Definition at line 323 of file tcp-l4-protocol.h.
Referenced by AddSocket(), CreateSocket(), DoDispose(), GetTypeId(), and RemoveSocket().
PROT_NUMBER
const uint8_t ns3::TcpL4Protocol::PROT_NUMBER = 6 static
protocol number (0x6)
Definition at line 87 of file tcp-l4-protocol.h.
Referenced by ns3::IpcsClassifier::Classify(), ns3::EpcTftClassifier::Classify(), GetProtocolNumber(), SendPacketV4(), and SendPacketV6().
The documentation for this class was generated from the following files:
src/internet/model/tcp-l4-protocol.h
src/internet/model/tcp-l4-protocol.cc