ns-3: ns3::JakesProcess Class Reference
ns3::JakesProcess Class Reference
Implementation for a single path Stationary Jakes propagation loss model.
#include "jakes-process.h"
Classes
struct Oscillator
This class Represents a single oscillator.
Public Member Functions
JakesProcess ()
virtual ~JakesProcess ()
virtual void DoDispose ()
Destructor implementation.
double GetChannelGainDb () const
Get the channel gain in dB.
std::complex< double > GetComplexGain () const
Get the channel complex gain.
void SetPropagationLossModel (Ptr< const PropagationLossModel > model)
Set the propagation model using this class.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void ConstructOscillators ()
void SetDopplerFrequencyHz (double dopplerFrequencyHz)
Set the Doppler frequency.
void SetNOscillators (unsigned int nOscillators)
Set the number of Oscillators to use.
Private Attributes
Ptr< const JakesPropagationLossModel > m_jakes
pointer to the propagation loss model
unsigned int m_nOscillators
number of oscillators
double m_omegaDopplerMax
max rotation speed Doppler frequency
std::vector< Oscillator > m_oscillators
Vector of oscillators.
Ptr< UniformRandomVariable > m_uniformVariable
random stream
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implementation for a single path Stationary Jakes propagation loss model.
Introspection did not find any typical Config paths.
The Jakes propagation loss model implemented here is described in [1].
We consider one transmitter - receiver pair and calculate the complex coefficients for this case as follow:
with
where , , and are statically independent and uniformly distributed over for all .
[1] Y. R. Zheng and C. Xiao, "Simulation Models With Correct Statistical Properties for Rayleigh Fading Channel", IEEE Trans. on Communications, Vol. 51, pp 920-928, June 2003
Attributes
DopplerFrequencyHz: Corresponding doppler frequency[Hz]
Set with class: ns3::DoubleValue
Underlying type: double 0:10000
Initial value: 80
Flags: construct write
NumberOfOscillators: The number of oscillators
Set with class: ns3::UintegerValue
Underlying type: uint32_t 4:1000
Initial value: 20
Flags: construct write
No TraceSources are defined for this type.
Size of this type is 88 bytes (on a 64-bit architecture).
Definition at line 55 of file jakes-process.h.
Constructor & Destructor Documentation
JakesProcess()
ns3::JakesProcess::JakesProcess ()
Definition at line 116 of file jakes-process.cc.
~JakesProcess()
ns3::JakesProcess::~JakesProcess () virtual
Definition at line 122 of file jakes-process.cc.
References m_oscillators.
Member Function Documentation
ConstructOscillators()
void ns3::JakesProcess::ConstructOscillators () private
Rotation speed 1a. Initiate
, n is oscillatorNumber, M is m_nOscillators
1b. Initiate rotation speed:
Initiate complex amplitude:
Construct oscillator:
Definition at line 93 of file jakes-process.cc.
References sample-rng-plot::alpha, m_jakes, m_nOscillators, m_omegaDopplerMax, m_oscillators, sample-rng-plot::n, and NS_ASSERT.
Referenced by SetPropagationLossModel().
DoDispose()
void ns3::JakesProcess::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 128 of file jakes-process.cc.
References m_jakes.
GetChannelGainDb()
double ns3::JakesProcess::GetChannelGainDb () const
Get the channel gain in dB.
Returns
the channel gain [dB]
Definition at line 145 of file jakes-process.cc.
References GetComplexGain().
GetComplexGain()
std::complex< double > ns3::JakesProcess::GetComplexGain () const
Get the channel complex gain.
Returns
the channel complex gain
Definition at line 134 of file jakes-process.cc.
References m_oscillators, and ns3::Now().
Referenced by GetChannelGainDb().
GetTypeId()
TypeId ns3::JakesProcess::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 49 of file jakes-process.cc.
References ns3::MakeDoubleAccessor(), ns3::MakeUintegerAccessor(), SetDopplerFrequencyHz(), SetNOscillators(), and ns3::TypeId::SetParent().
SetDopplerFrequencyHz()
void ns3::JakesProcess::SetDopplerFrequencyHz (double dopplerFrequencyHz) private
Set the Doppler frequency.
Parameters
dopplerFrequencyHz the Doppler frequency [Hz]
Definition at line 87 of file jakes-process.cc.
References m_omegaDopplerMax.
Referenced by GetTypeId().
SetNOscillators()
void ns3::JakesProcess::SetNOscillators (unsigned int nOscillators) private
Set the number of Oscillators to use.
Parameters
nOscillators the number of oscillators
Definition at line 81 of file jakes-process.cc.
References m_nOscillators.
Referenced by GetTypeId().
SetPropagationLossModel()
void ns3::JakesProcess::SetPropagationLossModel (Ptr< const PropagationLossModel > model)
Set the propagation model using this class.
Parameters
model the propagation model using this class
Definition at line 68 of file jakes-process.cc.
References ConstructOscillators(), m_jakes, m_nOscillators, m_omegaDopplerMax, NS_ASSERT, and NS_ASSERT_MSG.
Member Data Documentation
m_jakes
Ptr<const JakesPropagationLossModel> ns3::JakesProcess::m_jakes private
pointer to the propagation loss model
Definition at line 130 of file jakes-process.h.
Referenced by ConstructOscillators(), DoDispose(), and SetPropagationLossModel().
m_nOscillators
unsigned int ns3::JakesProcess::m_nOscillators private
number of oscillators
Definition at line 128 of file jakes-process.h.
Referenced by ConstructOscillators(), SetNOscillators(), and SetPropagationLossModel().
m_omegaDopplerMax
double ns3::JakesProcess::m_omegaDopplerMax private
max rotation speed Doppler frequency
Definition at line 127 of file jakes-process.h.
Referenced by ConstructOscillators(), SetDopplerFrequencyHz(), and SetPropagationLossModel().
m_oscillators
std::vector<Oscillator> ns3::JakesProcess::m_oscillators private
Vector of oscillators.
Definition at line 126 of file jakes-process.h.
Referenced by ~JakesProcess(), ConstructOscillators(), and GetComplexGain().
m_uniformVariable
Ptr<UniformRandomVariable> ns3::JakesProcess::m_uniformVariable private
random stream
Definition at line 129 of file jakes-process.h.
The documentation for this class was generated from the following files:
src/propagation/model/jakes-process.h
src/propagation/model/jakes-process.cc