ns-3: ns3::TestVectors< T > Class Template Reference
ns3::TestVectors< T > Class Template Reference
Core » Testing
A simple way to store test vectors (for stimulus or from responses)
#include "test.h"
Public Member Functions
TestVectors ()
Constructor.
virtual ~TestVectors ()
Virtual destructor.
std::size_t Add (T vector)
T Get (std::size_t i) const
Get the i'th test vector.
std::size_t GetN (void) const
Get the total number of test vectors.
void Reserve (uint32_t reserve)
Set the expected length of this vector.
Private Types
typedef std::vector< T > TestVector
Container type.
Private Attributes
TestVector m_vectors
The list of test vectors.
Additional Inherited Members
Private Member Functions inherited from ns3::NonCopyable
NonCopyable ()
Constructor.
~NonCopyable ()
Destructor.
Detailed Description
template<typename T>
class ns3::TestVectors< T >
A simple way to store test vectors (for stimulus or from responses)
Definition at line 1406 of file test.h.
Member Typedef Documentation
TestVector
template<typename T > typedef std::vector<T> ns3::TestVectors< T >::TestVector private
Container type.
Definition at line 1445 of file test.h.
Constructor & Destructor Documentation
TestVectors()
template<typename T > ns3::TestVectors< T >::TestVectors
Constructor.
Definition at line 1450 of file test.h.
~TestVectors()
template<typename T > ns3::TestVectors< T >::~TestVectors virtual
Virtual destructor.
Definition at line 1462 of file test.h.
Member Function Documentation
Add()
template<typename T > std::size_t ns3::TestVectors< T >::Add (T vector)
Parameters
[in] vector The test vector to add
Returns
The new test vector index
Definition at line 1467 of file test.h.
Referenced by Ns3TcpNoDelayTestCase::DoRun(), Ns3TcpSocketTestCase1::DoRun(), Ns3TcpSocketTestCase2::DoRun(), NscTcpLossTestCase1::DoRun(), NscTcpLossTestCase2::DoRun(), Ns3TcpNoDelayTestCase::SinkRx(), Ns3TcpSocketTestCase1::SinkRx(), Ns3TcpSocketTestCase2::SinkRx(), NscTcpLossTestCase1::SinkRx(), and NscTcpLossTestCase2::SinkRx().
Get()
template<typename T > T ns3::TestVectors< T >::Get (std::size_t i) const
Get the i'th test vector.
Parameters
[in] i The requested vector index
Returns
The requested vector
Definition at line 1483 of file test.h.
References NS_ABORT_MSG_UNLESS.
Referenced by Ns3TcpNoDelayTestCase::DoRun(), Ns3TcpSocketTestCase1::DoRun(), Ns3TcpSocketTestCase2::DoRun(), NscTcpLossTestCase1::DoRun(), and NscTcpLossTestCase2::DoRun().
GetN()
template<typename T > std::size_t ns3::TestVectors< T >::GetN (void) const
Get the total number of test vectors.
Returns
The number of test vectors
Definition at line 1476 of file test.h.
Referenced by Ns3TcpNoDelayTestCase::DoRun(), Ns3TcpSocketTestCase1::DoRun(), Ns3TcpSocketTestCase2::DoRun(), NscTcpLossTestCase1::DoRun(), and NscTcpLossTestCase2::DoRun().
Reserve()
template<typename T > void ns3::TestVectors< T >::Reserve (uint32_t reserve)
Set the expected length of this vector.
Parameters
[in] reserve The number of entries to reserve
Definition at line 1456 of file test.h.
Member Data Documentation
m_vectors
template<typename T > TestVector ns3::TestVectors< T >::m_vectors private
The list of test vectors.
Definition at line 1446 of file test.h.
The documentation for this class was generated from the following file:
src/core/model/test.h