ns-3: ns3::Average< T > Class Template Reference
ns3::Average< T > Class Template Reference
Statistics
Simple average, min, max and std.
#include "average.h"
Public Member Functions
Average ()
double Avg () const
Sample average.
uint32_t Count () const
Sample size.
T Max () const
Maximum.
double Mean () const
Estimate of mean, alias to Avg.
T Min () const
Minimum.
void Reset ()
Reset statistics.
double Stddev () const
Standard deviation.
void Update (T const &x)
Add new sample.
double Var () const
Unbiased estimate of variance.
Error of the mean estimates
double Error90 () const
Margin of error of the mean for 90% confidence level.
double Error95 () const
Margin of error of the mean for 95% confidence level.
double Error99 () const
Margin of error of the mean for 99% confidence level.
Private Attributes
T m_max
Maximum value observed.
T m_min
Minimum value observed.
uint32_t m_size
Number of sampled data.
MinMaxAvgTotalCalculator< double > m_varianceCalculator
Variance calculator.
Detailed Description
template<typename T = double>
class ns3::Average< T >
Simple average, min, max and std.
deviation calculator
Definition at line 40 of file average.h.
Constructor & Destructor Documentation
Average()
template<typename T = double> ns3::Average< T >::Average () inline
Definition at line 43 of file average.h.
Member Function Documentation
Avg()
template<typename T = double> double ns3::Average< T >::Avg () const inline
Sample average.
Definition at line 76 of file average.h.
References ns3::MinMaxAvgTotalCalculator< T >::getMean(), and ns3::Average< T >::m_varianceCalculator.
Referenced by ns3::Average< T >::Mean(), and ns3::V4Ping::StopApplication().
Count()
template<typename T = double> uint32_t ns3::Average< T >::Count (void) const inline
Sample size.
Definition at line 70 of file average.h.
References ns3::Average< T >::m_size.
Referenced by OneIntegerAverageTestCase::DoRun(), FiveIntegersAverageTestCase::DoRun(), FiveDoublesAverageTestCase::DoRun(), ns3::Average< T >::Error90(), ns3::Average< T >::Error95(), ns3::Average< T >::Error99(), and ns3::V4Ping::StopApplication().
Error90()
template<typename T = double> double ns3::Average< T >::Error90 () const inline
Margin of error of the mean for 90% confidence level.
Note that estimates are valid for
uncorrelated measurements,
normal distribution and
large enough sample size.
Returns
Margin of error of the mean for 90% confidence level
Definition at line 99 of file average.h.
References ns3::Average< T >::Count(), and ns3::Average< T >::Var().
Error95()
template<typename T = double> double ns3::Average< T >::Error95 () const inline
Margin of error of the mean for 95% confidence level.
Note that estimates are valid for
uncorrelated measurements,
normal distribution and
large enough sample size.
Returns
Margin of error of the mean for 95% confidence level
Definition at line 110 of file average.h.
References ns3::Average< T >::Count(), and ns3::Average< T >::Var().
Error99()
template<typename T = double> double ns3::Average< T >::Error99 () const inline
Margin of error of the mean for 99% confidence level.
Note that estimates are valid for
uncorrelated measurements,
normal distribution and
large enough sample size.
Returns
Margin of error of the mean for 99% confidence level
Definition at line 122 of file average.h.
References ns3::Average< T >::Count(), and ns3::Average< T >::Var().
Max()
template<typename T = double> T ns3::Average< T >::Max () const inline
Maximum.
Definition at line 74 of file average.h.
References ns3::Average< T >::m_max.
Referenced by OneIntegerAverageTestCase::DoRun(), FiveIntegersAverageTestCase::DoRun(), FiveDoublesAverageTestCase::DoRun(), and ns3::V4Ping::StopApplication().
Mean()
template<typename T = double> double ns3::Average< T >::Mean () const inline
Estimate of mean, alias to Avg.
Definition at line 78 of file average.h.
References ns3::Average< T >::Avg().
Referenced by OneIntegerAverageTestCase::DoRun(), FiveIntegersAverageTestCase::DoRun(), and FiveDoublesAverageTestCase::DoRun().
Min()
template<typename T = double> T ns3::Average< T >::Min () const inline
Minimum.
Definition at line 72 of file average.h.
References ns3::Average< T >::m_min.
Referenced by OneIntegerAverageTestCase::DoRun(), FiveIntegersAverageTestCase::DoRun(), FiveDoublesAverageTestCase::DoRun(), and ns3::V4Ping::StopApplication().
Reset()
template<typename T = double> void ns3::Average< T >::Reset (void) inline
Reset statistics.
Definition at line 59 of file average.h.
References ns3::Average< T >::m_max, ns3::Average< T >::m_min, ns3::Average< T >::m_size, ns3::Average< T >::m_varianceCalculator, max, and ns3::MinMaxAvgTotalCalculator< T >::Reset().
Stddev()
template<typename T = double> double ns3::Average< T >::Stddev () const inline
Standard deviation.
Definition at line 82 of file average.h.
References ns3::Average< T >::Var().
Referenced by OneIntegerAverageTestCase::DoRun(), FiveIntegersAverageTestCase::DoRun(), FiveDoublesAverageTestCase::DoRun(), and ns3::V4Ping::StopApplication().
Update()
template<typename T = double> void ns3::Average< T >::Update (T const & x) inline
Add new sample.
Definition at line 49 of file average.h.
References ns3::Average< T >::m_max, ns3::Average< T >::m_min, ns3::Average< T >::m_size, ns3::Average< T >::m_varianceCalculator, max, min, ns3::MinMaxAvgTotalCalculator< T >::Update(), and sample-rng-plot::x.
Referenced by OneIntegerAverageTestCase::DoRun(), FiveIntegersAverageTestCase::DoRun(), FiveDoublesAverageTestCase::DoRun(), and ns3::V4Ping::Receive().
Var()
template<typename T = double> double ns3::Average< T >::Var () const inline
Unbiased estimate of variance.
Definition at line 80 of file average.h.
References ns3::MinMaxAvgTotalCalculator< T >::getVariance(), and ns3::Average< T >::m_varianceCalculator.
Referenced by OneIntegerAverageTestCase::DoRun(), FiveIntegersAverageTestCase::DoRun(), FiveDoublesAverageTestCase::DoRun(), ns3::Average< T >::Error90(), ns3::Average< T >::Error95(), ns3::Average< T >::Error99(), and ns3::Average< T >::Stddev().
Member Data Documentation
m_max
template<typename T = double> T ns3::Average< T >::m_max private
Maximum value observed.
Definition at line 128 of file average.h.
Referenced by ns3::Average< T >::Max(), ns3::Average< T >::Reset(), and ns3::Average< T >::Update().
m_min
template<typename T = double> T ns3::Average< T >::m_min private
Minimum value observed.
Definition at line 127 of file average.h.
Referenced by ns3::Average< T >::Min(), ns3::Average< T >::Reset(), and ns3::Average< T >::Update().
m_size
template<typename T = double> uint32_t ns3::Average< T >::m_size private
Number of sampled data.
Definition at line 126 of file average.h.
Referenced by ns3::Average< T >::Count(), ns3::Average< T >::Reset(), and ns3::Average< T >::Update().
m_varianceCalculator
template<typename T = double> MinMaxAvgTotalCalculator<double> ns3::Average< T >::m_varianceCalculator private
Variance calculator.
Definition at line 129 of file average.h.
Referenced by ns3::Average< T >::Avg(), ns3::Average< T >::Reset(), ns3::Average< T >::Update(), and ns3::Average< T >::Var().
The documentation for this class was generated from the following file:
src/stats/model/average.h