ns-3: ns3::dsr::DsrRoutingHeader Class Reference
ns3::dsr::DsrRoutingHeader Class Reference
Header of Dsr Routing.
#include "dsr-fs-header.h"
Public Member Functions
DsrRoutingHeader ()
Constructor.
virtual ~DsrRoutingHeader ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
virtual uint32_t GetSerializedSize () const
Get the serialized size of the packet.
virtual void Print (std::ostream &os) const
Print some information about the packet.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
Public Member Functions inherited from ns3::dsr::DsrFsHeader
DsrFsHeader ()
Constructor.
virtual ~DsrFsHeader ()
Destructor.
uint16_t GetDestId () const
brief Get the dest ID of the header.
uint8_t GetMessageType () const
brief Get the message type of the header.
uint8_t GetNextHeader () const
Get the next header.
uint16_t GetPayloadLength () const
Get the payload length of the header.
uint16_t GetSourceId () const
brief Get the source ID of the header.
void SetDestId (uint16_t destId)
brief Set the dest ID of the header.
void SetMessageType (uint8_t messageType)
brief Set the message type of the header.
void SetNextHeader (uint8_t protocol)
Set the "Next header" field.
void SetPayloadLength (uint16_t length)
brief Set the payload length of the header.
void SetSourceId (uint16_t sourceId)
brief Set the source ID of the header.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Public Member Functions inherited from ns3::dsr::DsrOptionField
DsrOptionField (uint32_t optionsOffset)
Constructor.
~DsrOptionField ()
Destructor.
void AddDsrOption (DsrOptionHeader const &option)
Serialize the option, prepending pad1 or padn option as necessary.
uint32_t Deserialize (Buffer::Iterator start, uint32_t length)
Deserialize the packet.
Buffer GetDsrOptionBuffer ()
Get the buffer.
uint32_t GetDsrOptionsOffset ()
Get the offset where the options begin, measured from the start of the extension header.
uint32_t GetSerializedSize () const
Get the serialized size of the packet.
void Serialize (Buffer::Iterator start) const
Serialize all added options.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::dsr::DsrFsHeader
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Header of Dsr Routing.
Definition at line 277 of file dsr-fs-header.h.
Constructor & Destructor Documentation
DsrRoutingHeader()
ns3::dsr::DsrRoutingHeader::DsrRoutingHeader ()
Constructor.
Definition at line 279 of file dsr-fs-header.cc.
~DsrRoutingHeader()
ns3::dsr::DsrRoutingHeader::~DsrRoutingHeader () virtual
Destructor.
Definition at line 284 of file dsr-fs-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::dsr::DsrRoutingHeader::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start Buffer iterator
Returns
size of the packet
Reimplemented from ns3::dsr::DsrFsHeader.
Definition at line 315 of file dsr-fs-header.cc.
References ns3::dsr::DsrOptionField::Deserialize(), ns3::dsr::DsrFsHeader::GetPayloadLength(), GetSerializedSize(), ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU8(), ns3::dsr::DsrFsHeader::SetDestId(), ns3::dsr::DsrFsHeader::SetMessageType(), ns3::dsr::DsrFsHeader::SetNextHeader(), ns3::dsr::DsrFsHeader::SetPayloadLength(), ns3::dsr::DsrFsHeader::SetSourceId(), and visualizer.core::start().
GetInstanceTypeId()
TypeId ns3::dsr::DsrRoutingHeader::GetInstanceTypeId (void) const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::dsr::DsrFsHeader.
Definition at line 274 of file dsr-fs-header.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::dsr::DsrRoutingHeader::GetSerializedSize (void) const virtual
Get the serialized size of the packet.
Returns
size
Reimplemented from ns3::dsr::DsrFsHeader.
Definition at line 296 of file dsr-fs-header.cc.
References ns3::dsr::DsrOptionField::GetSerializedSize().
Referenced by Deserialize(), and DsrFsHeaderTest::DoRun().
GetTypeId()
TypeId ns3::dsr::DsrRoutingHeader::GetTypeId (void) static
Get the type identificator.
Returns
type identificator
Definition at line 265 of file dsr-fs-header.cc.
References ns3::TypeId::AddConstructor().
Referenced by GetInstanceTypeId().
Print()
void ns3::dsr::DsrRoutingHeader::Print (std::ostream & os) const virtual
Print some information about the packet.
Parameters
os output stream
Returns
info about this packet
Reimplemented from ns3::dsr::DsrFsHeader.
Definition at line 288 of file dsr-fs-header.cc.
References ns3::dsr::DsrFsHeader::GetDestId(), ns3::dsr::DsrFsHeader::GetMessageType(), ns3::dsr::DsrFsHeader::GetNextHeader(), ns3::dsr::DsrFsHeader::GetPayloadLength(), and ns3::dsr::DsrFsHeader::GetSourceId().
Referenced by ns3::dsr::operator<<().
Serialize()
void ns3::dsr::DsrRoutingHeader::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start Buffer iterator
Reimplemented from ns3::dsr::DsrFsHeader.
Definition at line 302 of file dsr-fs-header.cc.
References ns3::dsr::DsrFsHeader::GetDestId(), ns3::dsr::DsrFsHeader::GetMessageType(), ns3::dsr::DsrFsHeader::GetNextHeader(), ns3::dsr::DsrFsHeader::GetPayloadLength(), ns3::dsr::DsrFsHeader::GetSourceId(), ns3::dsr::DsrOptionField::Serialize(), visualizer.core::start(), ns3::Buffer::Iterator::WriteU16(), and ns3::Buffer::Iterator::WriteU8().
Referenced by DsrFsHeaderTest::DoRun().
The documentation for this class was generated from the following files:
src/dsr/model/dsr-fs-header.h
src/dsr/model/dsr-fs-header.cc