ns-3: ns3::ByteTagIterator Class Reference
ns3::ByteTagIterator Class Reference
Network » Packet
Iterator over the set of byte tags in a packet.
#include "packet.h"
Classes
class Item
Identifies a byte tag and a set of bytes within a packet to which the tag applies.
Public Member Functions
bool HasNext (void) const
Item Next (void)
Private Member Functions
ByteTagIterator (ByteTagList::Iterator i)
Copy Constructor.
Private Attributes
ByteTagList::Iterator m_current
actual position over the set of byte tags in a packet
Friends
class Packet
Friend class.
Detailed Description
Iterator over the set of byte tags in a packet.
This is a java-style iterator.
Definition at line 54 of file packet.h.
Constructor & Destructor Documentation
ByteTagIterator()
ns3::ByteTagIterator::ByteTagIterator (ByteTagList::Iterator i) private
Copy Constructor.
Parameters
i object to copy
Definition at line 78 of file packet.cc.
Member Function Documentation
HasNext()
bool ns3::ByteTagIterator::HasNext (void) const
Returns
true if calling Next is safe, false otherwise.
Definition at line 65 of file packet.cc.
References ns3::ByteTagList::Iterator::HasNext(), and m_current.
Referenced by PacketTest::DoCheck(), PacketTest::DoCheckData(), Ipv4FragmentationTest::DoRun(), Ipv6FragmentationTest::DoRun(), ns3::Packet::FindFirstMatchingByteTag(), ns3::AnimationInterface::GetAnimUidFromPacket(), and ns3::Packet::PrintByteTags().
Next()
ByteTagIterator::Item ns3::ByteTagIterator::Next (void)
Returns
the next item found and prepare for the next one.
Definition at line 70 of file packet.cc.
References ns3::ByteTagList::Iterator::Item::buf, ns3::ByteTagList::Iterator::Item::end, ns3::ByteTagList::Iterator::GetOffsetStart(), m_current, ns3::ByteTagList::Iterator::Next(), ns3::ByteTagList::Iterator::Item::start, and ns3::ByteTagList::Iterator::Item::tid.
Referenced by PacketTest::DoCheck(), PacketTest::DoCheckData(), Ipv4FragmentationTest::DoRun(), Ipv6FragmentationTest::DoRun(), ns3::Packet::FindFirstMatchingByteTag(), ns3::AnimationInterface::GetAnimUidFromPacket(), and ns3::Packet::PrintByteTags().
Friends And Related Function Documentation
Packet
friend class Packet friend
Friend class.
Definition at line 116 of file packet.h.
Member Data Documentation
m_current
ByteTagList::Iterator ns3::ByteTagIterator::m_current private
actual position over the set of byte tags in a packet
Definition at line 122 of file packet.h.
Referenced by HasNext(), and Next().
The documentation for this class was generated from the following files:
src/network/model/packet.h
src/network/model/packet.cc