ns-3: ns3::SpectrumPhy Class Reference
ns3::SpectrumPhy Class Reference abstract
Spectrum Models
Abstract base class for Spectrum-aware PHY layers.
#include "spectrum-phy.h"
Public Member Functions
SpectrumPhy ()
virtual ~SpectrumPhy ()
virtual Ptr< NetDevice > GetDevice () const =0
Get the associated NetDevice instance.
virtual Ptr< MobilityModel > GetMobility ()=0
Get the associated MobilityModel instance.
virtual Ptr< AntennaModel > GetRxAntenna ()=0
Get the AntennaModel used by the NetDevice for reception.
virtual Ptr< const SpectrumModel > GetRxSpectrumModel () const =0
virtual void SetChannel (Ptr< SpectrumChannel > c)=0
Set the channel attached to this device.
virtual void SetDevice (Ptr< NetDevice > d)=0
Set the associated NetDevice instance.
virtual void SetMobility (Ptr< MobilityModel > m)=0
Set the mobility model associated with this device.
virtual void StartRx (Ptr< SpectrumSignalParameters > params)=0
Notify the SpectrumPhy instance of an incoming signal.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
SpectrumPhy (SpectrumPhy const &)
Copy constructor.
SpectrumPhy & operator= (SpectrumPhy const &)
Copy constructor.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Abstract base class for Spectrum-aware PHY layers.
Introspection did not find any typical Config paths.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 32 bytes (on a 64-bit architecture).
Definition at line 45 of file spectrum-phy.h.
Constructor & Destructor Documentation
SpectrumPhy() [1/2]
ns3::SpectrumPhy::SpectrumPhy ()
Definition at line 45 of file spectrum-phy.cc.
References NS_LOG_FUNCTION.
~SpectrumPhy()
ns3::SpectrumPhy::~SpectrumPhy () virtual
Definition at line 50 of file spectrum-phy.cc.
References NS_LOG_FUNCTION.
SpectrumPhy() [2/2]
ns3::SpectrumPhy::SpectrumPhy (SpectrumPhy const &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Member Function Documentation
GetDevice()
virtual Ptr<NetDevice> ns3::SpectrumPhy::GetDevice () const pure virtual
Get the associated NetDevice instance.
Returns
a Ptr to the associated NetDevice instance
Implemented in ns3::LrWpanPhy, ns3::WifiSpectrumPhyInterface, ns3::WaveformGenerator, ns3::TvSpectrumTransmitter, ns3::SpectrumAnalyzer, ns3::HalfDuplexIdealPhy, ns3::LteSimpleSpectrumPhy, ns3::RemSpectrumPhy, and ns3::LteSpectrumPhy.
GetMobility()
virtual Ptr<MobilityModel> ns3::SpectrumPhy::GetMobility () pure virtual
Get the associated MobilityModel instance.
Returns
a Ptr to the associated MobilityModel instance
Implemented in ns3::LrWpanPhy, ns3::WifiSpectrumPhyInterface, ns3::WaveformGenerator, ns3::TvSpectrumTransmitter, ns3::SpectrumAnalyzer, ns3::HalfDuplexIdealPhy, ns3::LteSimpleSpectrumPhy, ns3::RemSpectrumPhy, and ns3::LteSpectrumPhy.
Referenced by GlobalPathlossDatabase::UpdatePathloss().
GetRxAntenna()
virtual Ptr<AntennaModel> ns3::SpectrumPhy::GetRxAntenna () pure virtual
Get the AntennaModel used by the NetDevice for reception.
Returns
a Ptr to the AntennaModel used by the NetDevice for reception
Implemented in ns3::LrWpanPhy, ns3::WifiSpectrumPhyInterface, ns3::WaveformGenerator, ns3::TvSpectrumTransmitter, ns3::SpectrumAnalyzer, ns3::HalfDuplexIdealPhy, ns3::LteSimpleSpectrumPhy, ns3::RemSpectrumPhy, and ns3::LteSpectrumPhy.
GetRxSpectrumModel()
virtual Ptr<const SpectrumModel> ns3::SpectrumPhy::GetRxSpectrumModel () const pure virtual
Returns
returns the SpectrumModel that this SpectrumPhy expects to be used for all SpectrumValues that are passed to StartRx. If 0 is returned, it means that any model will be accepted.
Implemented in ns3::LrWpanPhy, ns3::WifiSpectrumPhyInterface, ns3::WaveformGenerator, ns3::TvSpectrumTransmitter, ns3::SpectrumAnalyzer, ns3::HalfDuplexIdealPhy, ns3::LteSimpleSpectrumPhy, ns3::RemSpectrumPhy, and ns3::LteSpectrumPhy.
GetTypeId()
TypeId ns3::SpectrumPhy::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 36 of file spectrum-phy.cc.
References ns3::TypeId::SetParent().
operator=()
SpectrumPhy& ns3::SpectrumPhy::operator= (SpectrumPhy const &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Returns
SetChannel()
virtual void ns3::SpectrumPhy::SetChannel (Ptr< SpectrumChannel > c) pure virtual
Set the channel attached to this device.
Parameters
c the channel
Implemented in ns3::WaveformGenerator, ns3::TvSpectrumTransmitter, ns3::SpectrumAnalyzer, ns3::HalfDuplexIdealPhy, ns3::LteSimpleSpectrumPhy, ns3::RemSpectrumPhy, ns3::LteSpectrumPhy, ns3::LrWpanPhy, and ns3::WifiSpectrumPhyInterface.
SetDevice()
virtual void ns3::SpectrumPhy::SetDevice (Ptr< NetDevice > d) pure virtual
Set the associated NetDevice instance.
Parameters
d the NetDevice instance
Implemented in ns3::WaveformGenerator, ns3::TvSpectrumTransmitter, ns3::SpectrumAnalyzer, ns3::HalfDuplexIdealPhy, ns3::LteSimpleSpectrumPhy, ns3::RemSpectrumPhy, ns3::LteSpectrumPhy, ns3::LrWpanPhy, and ns3::WifiSpectrumPhyInterface.
SetMobility()
virtual void ns3::SpectrumPhy::SetMobility (Ptr< MobilityModel > m) pure virtual
Set the mobility model associated with this device.
Parameters
m the mobility model
Implemented in ns3::WaveformGenerator, ns3::TvSpectrumTransmitter, ns3::SpectrumAnalyzer, ns3::HalfDuplexIdealPhy, ns3::LteSimpleSpectrumPhy, ns3::RemSpectrumPhy, ns3::LteSpectrumPhy, ns3::LrWpanPhy, and ns3::WifiSpectrumPhyInterface.
StartRx()
virtual void ns3::SpectrumPhy::StartRx (Ptr< SpectrumSignalParameters > params) pure virtual
Notify the SpectrumPhy instance of an incoming signal.
Parameters
params the parameters of the signals being received
Implemented in ns3::WifiSpectrumPhyInterface, ns3::WaveformGenerator, ns3::TvSpectrumTransmitter, ns3::SpectrumAnalyzer, ns3::HalfDuplexIdealPhy, ns3::LteSimpleSpectrumPhy, ns3::RemSpectrumPhy, ns3::LteSpectrumPhy, and ns3::LrWpanPhy.
Referenced by ns3::MultiModelSpectrumChannel::StartRx(), and ns3::SingleModelSpectrumChannel::StartRx().
The documentation for this class was generated from the following files:
src/spectrum/model/spectrum-phy.h
src/spectrum/model/spectrum-phy.cc