ns-3: PsrExperiment Class Reference
PsrExperiment Class Reference
PsrExperiment.
Classes
struct Input
Input structure.
struct Output
Output structure.
Public Member Functions
PsrExperiment ()
struct PsrExperiment::Output Run (struct PsrExperiment::Input input)
Run function.
Private Member Functions
void Receive (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector, std::vector< bool > statusPerMpdu)
Send receive function.
void Send (void)
Send function.
Private Attributes
struct Input m_input
input
struct Output m_output
output
Ptr< WifiPhy > m_tx
transmit
Detailed Description
PsrExperiment.
Definition at line 36 of file wifi-phy-test.cc.
Constructor & Destructor Documentation
PsrExperiment()
PsrExperiment::PsrExperiment ()
Definition at line 97 of file wifi-phy-test.cc.
Member Function Documentation
Receive()
void PsrExperiment::Receive (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector, std::vector< bool > statusPerMpdu) private
Send receive function.
Parameters
psdu the PSDU
snr the SNR
txVector the wifi transmit vector
statusPerMpdu reception status per MPDU
Definition at line 92 of file wifi-phy-test.cc.
Run()
struct PsrExperiment::Output PsrExperiment::Run (struct PsrExperiment::Input input)
Run function.
Parameters
input the PSR experiment
Returns
the PSR experiment output
Definition at line 100 of file wifi-phy-test.cc.
Send()
void PsrExperiment::Send (void) private
Send function.
Definition at line 80 of file wifi-phy-test.cc.
References ns3::WifiTxVector::SetMode(), ns3::WifiTxVector::SetPreambleType(), ns3::WifiTxVector::SetTxPowerLevel(), and ns3::WIFI_PREAMBLE_LONG.
Member Data Documentation
m_input
struct Input PsrExperiment::m_input private
input
Definition at line 74 of file wifi-phy-test.cc.
Referenced by CollisionExperiment::SendA(), and CollisionExperiment::SendB().
m_output
struct Output PsrExperiment::m_output private
output
Definition at line 74 of file wifi-phy-test.cc.
Referenced by CollisionExperiment::Receive().
m_tx
Ptr<WifiPhy> PsrExperiment::m_tx private
transmit
Definition at line 74 of file wifi-phy-test.cc.
The documentation for this class was generated from the following file:
src/wifi/examples/wifi-phy-test.cc