ns-3: ns3::Icmpv4L4Protocol Class Reference
ns3::Icmpv4L4Protocol Class Reference
Internet » IPv4 classes and sub-modules » ICMP protocol and associated headers.
This is the implementation of the ICMP protocol as described in RFC 792.
#include "icmpv4-l4-protocol.h"
Public Member Functions
Icmpv4L4Protocol ()
virtual ~Icmpv4L4Protocol ()
virtual IpL4Protocol::DownTargetCallback GetDownTarget (void) const
This method allows a caller to get the current down target callback set for this L4 protocol (IPv4 case)
virtual IpL4Protocol::DownTargetCallback6 GetDownTarget6 (void) const
This method allows a caller to get the current down target callback set for this L4 protocol (IPv6 case)
virtual int GetProtocolNumber (void) const
Get the protocol number.
virtual enum IpL4Protocol::RxStatus Receive (Ptr< Packet > p, Ipv4Header const &header, Ptr< Ipv4Interface > incomingInterface)
Receive method.
virtual enum IpL4Protocol::RxStatus Receive (Ptr< Packet > p, Ipv6Header const &header, Ptr< Ipv6Interface > incomingInterface)
Receive method.
void SendDestUnreachFragNeeded (Ipv4Header header, Ptr< const Packet > orgData, uint16_t nextHopMtu)
Send a Destination Unreachable - Fragmentation needed ICMP error.
void SendDestUnreachPort (Ipv4Header header, Ptr< const Packet > orgData)
Send a Time Exceeded ICMP error.
void SendTimeExceededTtl (Ipv4Header header, Ptr< const Packet > orgData, bool isFragment)
Send a Time Exceeded ICMP error.
virtual void SetDownTarget (IpL4Protocol::DownTargetCallback cb)
This method allows a caller to set the current down target callback set for this L4 protocol (IPv4 case)
virtual void SetDownTarget6 (IpL4Protocol::DownTargetCallback6 cb)
This method allows a caller to set the current down target callback set for this L4 protocol (IPv6 case)
void SetNode (Ptr< Node > node)
Set the node the protocol is associated with.
Public Member Functions inherited from ns3::IpL4Protocol
virtual ~IpL4Protocol ()
virtual void ReceiveIcmp (Ipv4Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo, Ipv4Address payloadSource, Ipv4Address payloadDestination, const uint8_t payload[8])
Called from lower-level layers to send the ICMP packet up in the stack.
virtual void ReceiveIcmp (Ipv6Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo, Ipv6Address payloadSource, Ipv6Address payloadDestination, const uint8_t payload[8])
Called from lower-level layers to send the ICMPv6 packet up in the stack.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static uint16_t GetStaticProtocolNumber (void)
Get the protocol number.
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::IpL4Protocol
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static const uint8_t PROT_NUMBER = 1
ICMP protocol number (0x1)
Protected Member Functions
virtual void NotifyNewAggregate ()
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
virtual void DoDispose (void)
Destructor implementation.
void Forward (Ipv4Address source, Icmpv4Header icmp, uint32_t info, Ipv4Header ipHeader, const uint8_t payload[8])
Forward the message to an L4 protocol.
void HandleDestUnreach (Ptr< Packet > p, Icmpv4Header header, Ipv4Address source, Ipv4Address destination)
Handles an incoming ICMP Destination Unreachable packet.
void HandleEcho (Ptr< Packet > p, Icmpv4Header header, Ipv4Address source, Ipv4Address destination)
Handles an incoming ICMP Echo packet.
void HandleTimeExceeded (Ptr< Packet > p, Icmpv4Header icmp, Ipv4Address source, Ipv4Address destination)
Handles an incoming ICMP Time Exceeded packet.
void SendDestUnreach (Ipv4Header header, Ptr< const Packet > orgData, uint8_t code, uint16_t nextHopMtu)
Send an ICMP Destination Unreachable packet.
void SendMessage (Ptr< Packet > packet, Ipv4Address dest, uint8_t type, uint8_t code)
Send a generic ICMP packet.
void SendMessage (Ptr< Packet > packet, Ipv4Address source, Ipv4Address dest, uint8_t type, uint8_t code, Ptr< Ipv4Route > route)
Send a generic ICMP packet.
Private Attributes
IpL4Protocol::DownTargetCallback m_downTarget
callback to Ipv4::Send
Ptr< Node > m_node
the node this protocol is associated with
Additional Inherited Members
Public Types inherited from ns3::IpL4Protocol
typedef Callback< void, Ptr< Packet >, Ipv4Address, Ipv4Address, uint8_t, Ptr< Ipv4Route > > DownTargetCallback
callback to send packets over IPv4
typedef Callback< void, Ptr< Packet >, Ipv6Address, Ipv6Address, uint8_t, Ptr< Ipv6Route > > DownTargetCallback6
callback to send packets over IPv6
enum RxStatus { RX_OK , RX_CSUM_FAILED , RX_ENDPOINT_CLOSED , RX_ENDPOINT_UNREACH }
Rx status codes.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This is the implementation of the ICMP protocol as described in RFC 792.
Config Paths
ns3::Icmpv4L4Protocol is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::Icmpv4L4Protocol"
"/NodeList/[i]/$ns3::Icmpv4L4Protocol"
No Attributes are defined for this type.
Attributes defined in parent class ns3::IpL4Protocol
ProtocolNumber: The IP protocol number.
Set with class: ns3::IntegerValue
Underlying type: int32_t 0:255
Flags: read
No TraceSources are defined for this type.
Size of this type is 48 bytes (on a 64-bit architecture).
Definition at line 45 of file icmpv4-l4-protocol.h.
Constructor & Destructor Documentation
Icmpv4L4Protocol()
ns3::Icmpv4L4Protocol::Icmpv4L4Protocol ()
Definition at line 53 of file icmpv4-l4-protocol.cc.
References NS_LOG_FUNCTION.
~Icmpv4L4Protocol()
ns3::Icmpv4L4Protocol::~Icmpv4L4Protocol () virtual
Definition at line 58 of file icmpv4-l4-protocol.cc.
References m_node, NS_ASSERT, and NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::Icmpv4L4Protocol::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 295 of file icmpv4-l4-protocol.cc.
References ns3::Object::DoDispose(), m_downTarget, m_node, NS_LOG_FUNCTION, and ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::Nullify().
Forward()
void ns3::Icmpv4L4Protocol::Forward (Ipv4Address source, Icmpv4Header icmp, uint32_t info, Ipv4Header ipHeader, const uint8_t payload[8]) private
Forward the message to an L4 protocol.
Parameters
source the source
icmp the ICMP header
info info data (e.g., the target MTU)
ipHeader the IP header carried by ICMP
payload payload chunk carried by ICMP
Definition at line 215 of file icmpv4-l4-protocol.cc.
References ns3::Icmpv4Header::GetCode(), ns3::Ipv4Header::GetDestination(), ns3::Object::GetObject(), ns3::Ipv4Header::GetProtocol(), ns3::Ipv4Header::GetSource(), ns3::Ipv4Header::GetTtl(), ns3::Icmpv4Header::GetType(), m_node, and NS_LOG_FUNCTION.
Referenced by HandleDestUnreach(), and HandleTimeExceeded().
GetDownTarget()
IpL4Protocol::DownTargetCallback ns3::Icmpv4L4Protocol::GetDownTarget (void) const virtual
This method allows a caller to get the current down target callback set for this L4 protocol (IPv4 case)
Returns
current Callback for the L4 protocol
Implements ns3::IpL4Protocol.
Definition at line 317 of file icmpv4-l4-protocol.cc.
References m_downTarget, and NS_LOG_FUNCTION.
GetDownTarget6()
IpL4Protocol::DownTargetCallback6 ns3::Icmpv4L4Protocol::GetDownTarget6 (void) const virtual
This method allows a caller to get the current down target callback set for this L4 protocol (IPv6 case)
Returns
current Callback for the L4 protocol
Implements ns3::IpL4Protocol.
Definition at line 324 of file icmpv4-l4-protocol.cc.
References NS_LOG_FUNCTION.
GetProtocolNumber()
int ns3::Icmpv4L4Protocol::GetProtocolNumber (void) const virtual
Get the protocol number.
Returns
the protocol number
Implements ns3::IpL4Protocol.
Definition at line 107 of file icmpv4-l4-protocol.cc.
References NS_LOG_FUNCTION, and PROT_NUMBER.
GetStaticProtocolNumber()
uint16_t ns3::Icmpv4L4Protocol::GetStaticProtocolNumber (void) static
Get the protocol number.
Returns
the protocol number
Definition at line 100 of file icmpv4-l4-protocol.cc.
References NS_LOG_FUNCTION_NOARGS, and PROT_NUMBER.
Referenced by ns3::Ipv4L3Protocol::GetIcmp().
GetTypeId()
TypeId ns3::Icmpv4L4Protocol::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 43 of file icmpv4-l4-protocol.cc.
References ns3::TypeId::SetParent().
HandleDestUnreach()
void ns3::Icmpv4L4Protocol::HandleDestUnreach (Ptr< Packet > p, Icmpv4Header header, Ipv4Address source, Ipv4Address destination) private
Handles an incoming ICMP Destination Unreachable packet.
Parameters
p the packet
header the IP header
source the source address
destination the destination address
Definition at line 230 of file icmpv4-l4-protocol.cc.
References Forward(), ns3::Icmpv4DestinationUnreachable::GetData(), ns3::Icmpv4DestinationUnreachable::GetHeader(), ns3::Icmpv4DestinationUnreachable::GetNextHopMtu(), NS_LOG_FUNCTION, and ns3::Packet::PeekHeader().
HandleEcho()
void ns3::Icmpv4L4Protocol::HandleEcho (Ptr< Packet > p, Icmpv4Header header, Ipv4Address source, Ipv4Address destination) private
Handles an incoming ICMP Echo packet.
Parameters
p the packet
header the IP header
source the source address
destination the destination address
Definition at line 201 of file icmpv4-l4-protocol.cc.
References ns3::Packet::AddHeader(), ns3::Icmpv4Header::ICMPV4_ECHO_REPLY, NS_LOG_FUNCTION, ns3::Packet::RemoveHeader(), and SendMessage().
HandleTimeExceeded()
void ns3::Icmpv4L4Protocol::HandleTimeExceeded (Ptr< Packet > p, Icmpv4Header icmp, Ipv4Address source, Ipv4Address destination) private
Handles an incoming ICMP Time Exceeded packet.
Parameters
p the packet
icmp the ICMP header
source the source address
destination the destination address
Definition at line 245 of file icmpv4-l4-protocol.cc.
References Forward(), ns3::Icmpv4TimeExceeded::GetData(), ns3::Icmpv4TimeExceeded::GetHeader(), NS_LOG_FUNCTION, and ns3::Packet::PeekHeader().
NotifyNewAggregate()
void ns3::Icmpv4L4Protocol::NotifyNewAggregate (void) protected virtual
Notify all Objects aggregated to this one of a new Object being aggregated.
This function must be implemented in the stack that needs to notify other stacks connected to the node of their presence in the node.
This method is invoked whenever two sets of Objects are aggregated together. It is invoked exactly once for each Object in both sets. This method can be overridden by subclasses who wish to be notified of aggregation events. These subclasses must chain up to their base class NotifyNewAggregate() method.
It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 77 of file icmpv4-l4-protocol.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_downTarget, m_node, ns3::MakeCallback(), ns3::Object::NotifyNewAggregate(), NS_LOG_FUNCTION, ns3::Ipv4::Send(), SetDownTarget(), and SetNode().
Receive() [1/2]
enum IpL4Protocol::RxStatus ns3::Icmpv4L4Protocol::Receive (Ptr< Packet > p, Ipv4Header const & header, Ptr< Ipv4Interface > incomingInterface) virtual
Receive method.
Parameters
p the packet
header the IPv4 header
incomingInterface the interface from which the packet is coming
Returns
the receive status
Implements ns3::IpL4Protocol.
Definition at line 245 of file icmpv4-l4-protocol.cc.
Receive() [2/2]
enum IpL4Protocol::RxStatus ns3::Icmpv4L4Protocol::Receive (Ptr< Packet > p, Ipv6Header const & header, Ptr< Ipv6Interface > incomingInterface) virtual
Receive method.
Parameters
p the packet
header the IPv6 header
incomingInterface the interface from which the packet is coming
Returns
the receive status
Implements ns3::IpL4Protocol.
Definition at line 245 of file icmpv4-l4-protocol.cc.
SendDestUnreach()
void ns3::Icmpv4L4Protocol::SendDestUnreach (Ipv4Header header, Ptr< const Packet > orgData, uint8_t code, uint16_t nextHopMtu) private
Send an ICMP Destination Unreachable packet.
Parameters
header the original IP header
orgData the original packet
code the ICMP code
nextHopMtu the next hop MTU
Definition at line 168 of file icmpv4-l4-protocol.cc.
References ns3::Packet::AddHeader(), ns3::Ipv4Header::GetSource(), ns3::Icmpv4Header::ICMPV4_DEST_UNREACH, NS_LOG_FUNCTION, SendMessage(), ns3::Icmpv4DestinationUnreachable::SetData(), ns3::Icmpv4DestinationUnreachable::SetHeader(), and ns3::Icmpv4DestinationUnreachable::SetNextHopMtu().
Referenced by SendDestUnreachFragNeeded(), and SendDestUnreachPort().
SendDestUnreachFragNeeded()
void ns3::Icmpv4L4Protocol::SendDestUnreachFragNeeded (Ipv4Header header, Ptr< const Packet > orgData, uint16_t nextHopMtu)
Send a Destination Unreachable - Fragmentation needed ICMP error.
Parameters
header the original IP header
orgData the original packet
nextHopMtu the next hop MTU
Definition at line 153 of file icmpv4-l4-protocol.cc.
References ns3::Icmpv4DestinationUnreachable::ICMPV4_FRAG_NEEDED, NS_LOG_FUNCTION, and SendDestUnreach().
SendDestUnreachPort()
void ns3::Icmpv4L4Protocol::SendDestUnreachPort (Ipv4Header header, Ptr< const Packet > orgData)
Send a Time Exceeded ICMP error.
Parameters
header the original IP header
orgData the original packet
Definition at line 161 of file icmpv4-l4-protocol.cc.
References ns3::Icmpv4DestinationUnreachable::ICMPV4_PORT_UNREACHABLE, NS_LOG_FUNCTION, and SendDestUnreach().
SendMessage() [1/2]
void ns3::Icmpv4L4Protocol::SendMessage (Ptr< Packet > packet, Ipv4Address dest, uint8_t type, uint8_t code) private
Send a generic ICMP packet.
Parameters
packet the packet
dest the destination
type the ICMP type
code the ICMP code
Definition at line 113 of file icmpv4-l4-protocol.cc.
References ns3::Object::GetObject(), ns3::Ipv4Route::GetSource(), m_node, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, NS_LOG_WARN, PROT_NUMBER, ns3::Ipv4Header::SetDestination(), and ns3::Ipv4Header::SetProtocol().
Referenced by HandleEcho(), SendDestUnreach(), and SendTimeExceededTtl().
SendMessage() [2/2]
void ns3::Icmpv4L4Protocol::SendMessage (Ptr< Packet > packet, Ipv4Address source, Ipv4Address dest, uint8_t type, uint8_t code, Ptr< Ipv4Route > route) private
Send a generic ICMP packet.
Parameters
packet the packet
source the source
dest the destination
type the ICMP type
code the ICMP code
route the route to be used
Definition at line 138 of file icmpv4-l4-protocol.cc.
References ns3::Packet::AddHeader(), ns3::Node::ChecksumEnabled(), ns3::Icmpv4Header::EnableChecksum(), m_downTarget, NS_LOG_FUNCTION, PROT_NUMBER, ns3::Icmpv4Header::SetCode(), and ns3::Icmpv4Header::SetType().
SendTimeExceededTtl()
void ns3::Icmpv4L4Protocol::SendTimeExceededTtl (Ipv4Header header, Ptr< const Packet > orgData, bool isFragment)
Send a Time Exceeded ICMP error.
Parameters
header the original IP header
orgData the original packet
isFragment true if the opcode must be FRAGMENT_REASSEMBLY
Definition at line 182 of file icmpv4-l4-protocol.cc.
References ns3::Packet::AddHeader(), ns3::Ipv4Header::GetSource(), ns3::Icmpv4TimeExceeded::ICMPV4_FRAGMENT_REASSEMBLY, ns3::Icmpv4Header::ICMPV4_TIME_EXCEEDED, ns3::Icmpv4TimeExceeded::ICMPV4_TIME_TO_LIVE, NS_LOG_FUNCTION, SendMessage(), ns3::Icmpv4TimeExceeded::SetData(), and ns3::Icmpv4TimeExceeded::SetHeader().
SetDownTarget()
void ns3::Icmpv4L4Protocol::SetDownTarget (IpL4Protocol::DownTargetCallback cb) virtual
This method allows a caller to set the current down target callback set for this L4 protocol (IPv4 case)
Parameters
cb current Callback for the L4 protocol
Implements ns3::IpL4Protocol.
Definition at line 304 of file icmpv4-l4-protocol.cc.
References m_downTarget, and NS_LOG_FUNCTION.
Referenced by NotifyNewAggregate().
SetDownTarget6()
void ns3::Icmpv4L4Protocol::SetDownTarget6 (IpL4Protocol::DownTargetCallback6 cb) virtual
This method allows a caller to set the current down target callback set for this L4 protocol (IPv6 case)
Parameters
cb current Callback for the L4 protocol
Implements ns3::IpL4Protocol.
Definition at line 311 of file icmpv4-l4-protocol.cc.
References NS_LOG_FUNCTION.
SetNode()
void ns3::Icmpv4L4Protocol::SetNode (Ptr< Node > node)
Set the node the protocol is associated with.
Parameters
node the node
Definition at line 65 of file icmpv4-l4-protocol.cc.
References m_node, and NS_LOG_FUNCTION.
Referenced by NotifyNewAggregate().
Member Data Documentation
m_downTarget
IpL4Protocol::DownTargetCallback ns3::Icmpv4L4Protocol::m_downTarget private
callback to Ipv4::Send
Definition at line 213 of file icmpv4-l4-protocol.h.
Referenced by DoDispose(), GetDownTarget(), NotifyNewAggregate(), SendMessage(), and SetDownTarget().
m_node
Ptr<Node> ns3::Icmpv4L4Protocol::m_node private
the node this protocol is associated with
Definition at line 212 of file icmpv4-l4-protocol.h.
Referenced by ~Icmpv4L4Protocol(), DoDispose(), Forward(), NotifyNewAggregate(), SendMessage(), and SetNode().
PROT_NUMBER
const uint8_t ns3::Icmpv4L4Protocol::PROT_NUMBER = 1 static
ICMP protocol number (0x1)
Definition at line 53 of file icmpv4-l4-protocol.h.
Referenced by GetProtocolNumber(), GetStaticProtocolNumber(), ns3::V4TraceRoute::Receive(), SendMessage(), and ns3::V4TraceRoute::StartApplication().
The documentation for this class was generated from the following files:
src/internet/model/icmpv4-l4-protocol.h
src/internet/model/icmpv4-l4-protocol.cc