ns-3: ns3::UanMacRc Class Reference
ns3::UanMacRc Class Reference
UAN Models
Non-gateway node MAC for reservation channel MAC protocol.
#include "uan-mac-rc.h"
Public Types
enum {
TYPE_DATA , TYPE_GWPING , TYPE_RTS , TYPE_CTS ,
TYPE_ACK
}
Packet types.
typedef void(* QueueTracedCallback) (Ptr< const Packet > packet, uint32_t proto)
TracedCallback signature for dequeue of a packet.
Public Types inherited from ns3::UanMac
typedef void(* PacketModeTracedCallback) (Ptr< const Packet > packet, UanTxMode mode)
TracedCallback signature for packet reception/enqueue/dequeue events.
Public Member Functions
UanMacRc ()
Default constructor.
virtual ~UanMacRc ()
Dummy destructor, DoDispose.
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
virtual void AttachPhy (Ptr< UanPhy > phy)
Attach PHY layer to this MAC.
virtual void Clear (void)
Clears all pointer references.
virtual bool Enqueue (Ptr< Packet > pkt, uint16_t protocolNumber, const Address &dest)
Enqueue packet to be transmitted.
virtual void SetForwardUpCb (Callback< void, Ptr< Packet >, uint16_t, const Mac8Address & > cb)
Set the callback to forward packets up to higher layers.
Public Member Functions inherited from ns3::UanMac
UanMac ()
Default constructor.
virtual Address GetAddress (void)
Get the MAC Address.
virtual Address GetBroadcast (void) const
Get the broadcast address.
uint32_t GetTxModeIndex ()
virtual void SetAddress (Mac8Address addr)
Set the address.
void SetTxModeIndex (uint32_t txModeIndex)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::UanMac
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
void DoDispose ()
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
enum State {
UNASSOCIATED , GWPSENT , IDLE , RTSSENT ,
DATATX
}
MAC state.
Private Member Functions
void Associate (void)
Associate with a gateway by sending the first GWPING.
void AssociateTimeout (void)
Periodically retry association.
void BlockRtsing (void)
Callback to block RST.
UanHeaderRcRts CreateRtsHeader (const Reservation &res)
Create the RTS header from a Reservation.
bool IsPhy1Ok (void)
Check that PHY is ok: not CTS or ACK not to my address.
void ProcessAck (Ptr< Packet > ack)
Process a received ACK.
void ReceiveOkFromPhy (Ptr< Packet > pkt, double sinr, UanTxMode mode)
PHY receive ok Callback.
void RtsTimeout (void)
Retry RTS.
void ScheduleData (const UanHeaderRcCts &ctsh, const UanHeaderRcCtsGlobal &ctsg, uint32_t ctsBytes)
Schedule Packet sends.
void SendPacket (Ptr< Packet > pkt, uint32_t rate)
Send on packet on the PHY.
void SendRts (void)
Send RTS packet.
Private Attributes
Mac8Address m_assocAddr
Next hop address.
bool m_cleared
Flag when we've been cleared.
uint32_t m_ctsSizeG
Size of UanHeaderCommon and UanHeaderRcCtsGlobal.
uint32_t m_ctsSizeN
Size of UanHeaderRcCts.
uint32_t m_currentRate
Rate number corresponding to data rate of current cycle.
TracedCallback< Ptr< const Packet >, uint32_t > m_dequeueLogger
A was passed down to the PHY from the MAC.
TracedCallback< Ptr< const Packet >, uint32_t > m_enqueueLogger
A packet arrived at the MAC for transmission.
Ptr< ExponentialRandomVariable > m_ev
Provides exponential random variables.
Callback< void, Ptr< Packet >, uint16_t, const Mac8Address & > m_forwardUpCb
The callback to forward a packet up to higher layer.
uint8_t m_frameNo
Current frame number.
Time m_learnedProp
Propagation delay to gateway.
uint32_t m_maxFrames
Maximum number of frames to include in a single RTS.
double m_minRetryRate
Smallest allowed RTS retry rate.
uint32_t m_numRates
Number of rates per Phy layer.
Ptr< UanPhy > m_phy
PHY layer attached to this MAC.
std::list< std::pair< Ptr< Packet >, Mac8Address > > m_pktQueue
Pending packets.
uint32_t m_queueLimit
Maximum packets to queue at MAC.
std::list< Reservation > m_resList
List of scheduled reservations.
double m_retryRate
Number of retry attempts per second (of RTS/GWPING.
double m_retryStep
Retry rate increment.
bool m_rtsBlocked
RTS blocked while processing ACK.
EventId m_rtsEvent
The RTS event.
TracedCallback< Ptr< const Packet >, UanTxMode > m_rxLogger
A packet was destined for and received at this MAC layer.
Time m_sifs
Spacing between frames to account for timing error and processing delay.
EventId m_startAgain
(Unused).
State m_state
MAC state.
Static Private Attributes
static uint32_t m_cntrlSends = 0
Global count of calls to Associate, AssociateTimeout, SendRts, and RtsTimeout.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Non-gateway node MAC for reservation channel MAC protocol.
This MAC protocol assumes a network topology where all traffic is destined for a set of GW nodes which are connected via some out of band (RF?) means. This particular implementation assumes that there is only a single gateway.
For more information on class operation email lentr.nosp@m.acy@.nosp@m.u.was.nosp@m.hing.nosp@m.ton.e.nosp@m.du (This work is, as of yet, unpublished)
Config Paths
ns3::UanMacRc is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::UanNetDevice/Mac/$ns3::UanMacRc"
Attributes
RetryRate: Number of retry attempts per second (of RTS/GWPING).
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0.2
Flags: construct write read
MaxFrames: Maximum number of frames to include in a single RTS.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 1
Flags: construct write read
QueueLimit: Maximum packets to queue at MAC.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 10
Flags: construct write read
SIFS: Spacing to give between frames (this should match gateway).
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +2e+08ns
Flags: construct write read
NumberOfRates: Number of rate divisions supported by each PHY.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 0
Flags: construct write read
MinRetryRate: Smallest allowed RTS retry rate.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0.01
Flags: construct write read
RetryStep: Retry rate increment.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0.01
Flags: construct write read
MaxPropDelay: Maximum possible propagation delay to gateway.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +2e+09ns
Flags: construct write read
TraceSources
Enqueue: A (data) packet arrived at MAC for transmission.
Callback signature: ns3::UanMacRc::QueueTracedCallback
Dequeue: A (data) packet was passed down to PHY from MAC.
Callback signature: ns3::UanMacRc::QueueTracedCallback
RX: A packet was destined for and received at this MAC layer.
Callback signature: ns3::UanMac::PacketModeTracedCallback
Size of this type is 344 bytes (on a 64-bit architecture).
Definition at line 163 of file uan-mac-rc.h.
Member Typedef Documentation
QueueTracedCallback
typedef void(* ns3::UanMacRc::QueueTracedCallback) (Ptr< const Packet > packet, uint32_t proto)
TracedCallback signature for dequeue of a packet.
Parameters
[in] packet The Packet being received.
[in] proto The protocol number.
Definition at line 198 of file uan-mac-rc.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Packet types.
Enumerator
TYPE_DATA
Data.
TYPE_GWPING
Gateway ping.
TYPE_RTS
RTS.
TYPE_CTS
CTS.
TYPE_ACK
ACK.
Definition at line 167 of file uan-mac-rc.h.
State
enum ns3::UanMacRc::State private
MAC state.
Enumerator
UNASSOCIATED
Initial state.
GWPSENT
Associated with gateway.
IDLE
Finished scheduling packet sends.
RTSSENT
RTS just sent.
DATATX
(Unused).
Definition at line 203 of file uan-mac-rc.h.
Constructor & Destructor Documentation
UanMacRc()
ns3::UanMacRc::UanMacRc ()
Default constructor.
Definition at line 155 of file uan-mac-rc.cc.
References ns3::UanHeaderCommon::GetSerializedSize(), ns3::UanHeaderRcCtsGlobal::GetSerializedSize(), ns3::UanHeaderRcCts::GetSerializedSize(), m_ctsSizeG, m_ctsSizeN, and m_ev.
~UanMacRc()
ns3::UanMacRc::~UanMacRc () virtual
Dummy destructor, DoDispose.
Definition at line 173 of file uan-mac-rc.cc.
Member Function Documentation
AssignStreams()
int64_t ns3::UanMacRc::AssignStreams (int64_t stream) virtual
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream First stream index to use.
Returns
The number of stream indices assigned by this model.
Implements ns3::UanMac.
Definition at line 272 of file uan-mac-rc.cc.
References m_ev, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
Associate()
void ns3::UanMacRc::Associate (void) private
Associate with a gateway by sending the first GWPING.
Definition at line 620 of file uan-mac-rc.cc.
References ns3::Packet::AddHeader(), ns3::Reservation::AddTimestamp(), AssociateTimeout(), ns3::Mac8Address::ConvertFrom(), CreateRtsHeader(), ns3::UanMac::GetAddress(), ns3::Mac8Address::GetBroadcast(), ns3::ExponentialRandomVariable::GetValue(), GWPSENT, IsPhy1Ok(), ns3::EventId::IsRunning(), m_cntrlSends, m_currentRate, m_ev, m_frameNo, m_maxFrames, m_numRates, m_phy, m_pktQueue, m_resList, m_retryRate, m_rtsBlocked, m_rtsEvent, m_state, ns3::Now(), ns3::Simulator::Now(), NS_ASSERT, NS_LOG_DEBUG, ns3::Time::S, ns3::Simulator::Schedule(), ns3::Seconds(), SendPacket(), ns3::ObjectBase::SetAttribute(), timeout, and TYPE_GWPING.
Referenced by Enqueue().
AssociateTimeout()
void ns3::UanMacRc::AssociateTimeout (void) private
Periodically retry association.
Definition at line 646 of file uan-mac-rc.cc.
References ns3::Packet::AddHeader(), ns3::Reservation::AddTimestamp(), ns3::Mac8Address::ConvertFrom(), CreateRtsHeader(), ns3::UanMac::GetAddress(), ns3::Mac8Address::GetBroadcast(), ns3::ExponentialRandomVariable::GetValue(), GWPSENT, ns3::Reservation::IncrementRetry(), IsPhy1Ok(), ns3::EventId::IsRunning(), m_cntrlSends, m_currentRate, m_ev, m_numRates, m_phy, m_resList, m_retryRate, m_rtsBlocked, m_rtsEvent, m_state, ns3::Simulator::Now(), NS_ASSERT, ns3::Simulator::Schedule(), ns3::Seconds(), SendPacket(), ns3::ObjectBase::SetAttribute(), timeout, and TYPE_GWPING.
Referenced by Associate().
AttachPhy()
void ns3::UanMacRc::AttachPhy (Ptr< UanPhy > phy) virtual
Attach PHY layer to this MAC.
Some MACs may be designed to work with multiple PHY layers. Others may only work with one.
Parameters
phy Phy layer to attach to this MAC.
Implements ns3::UanMac.
Definition at line 322 of file uan-mac-rc.cc.
References m_phy, ns3::MakeCallback(), third::phy, and ReceiveOkFromPhy().
BlockRtsing()
void ns3::UanMacRc::BlockRtsing (void) private
Callback to block RST.
Definition at line 775 of file uan-mac-rc.cc.
References m_rtsBlocked.
Referenced by ReceiveOkFromPhy().
Clear()
void ns3::UanMacRc::Clear (void) virtual
Clears all pointer references.
Implements ns3::UanMac.
Definition at line 178 of file uan-mac-rc.cc.
References ns3::EventId::Cancel(), m_cleared, m_phy, m_pktQueue, m_resList, m_rtsEvent, and m_startAgain.
Referenced by DoDispose().
CreateRtsHeader()
UanHeaderRcRts ns3::UanMacRc::CreateRtsHeader (const Reservation & res) private
Create the RTS header from a Reservation.
Parameters
res The Reservation.
Returns
A RTS header.
Definition at line 607 of file uan-mac-rc.cc.
References ns3::Reservation::GetFrameNo(), ns3::Reservation::GetLength(), ns3::Reservation::GetNoFrames(), ns3::Reservation::GetRetryNo(), ns3::Reservation::GetTimestamp(), ns3::UanHeaderRcRts::SetFrameNo(), ns3::UanHeaderRcRts::SetLength(), ns3::UanHeaderRcRts::SetNoFrames(), ns3::UanHeaderRcRts::SetRetryNo(), and ns3::UanHeaderRcRts::SetTimeStamp().
Referenced by Associate(), AssociateTimeout(), RtsTimeout(), and SendRts().
DoDispose()
void ns3::UanMacRc::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 202 of file uan-mac-rc.cc.
References Clear(), and ns3::Object::DoDispose().
Enqueue()
bool ns3::UanMacRc::Enqueue (Ptr< Packet > pkt, uint16_t protocolNumber, const Address & dest) virtual
Enqueue packet to be transmitted.
Parameters
pkt Packet to be transmitted.
dest Destination address.
protocolNumber The type of the packet.
Returns
True if packet was successfully enqueued.
Implements ns3::UanMac.
Definition at line 280 of file uan-mac-rc.cc.
References Associate(), ns3::Mac8Address::ConvertFrom(), DATATX, GWPSENT, IDLE, ns3::EventId::IsRunning(), m_pktQueue, m_queueLimit, m_rtsEvent, m_state, NS_LOG_WARN, RTSSENT, SendRts(), and UNASSOCIATED.
GetTypeId()
TypeId ns3::UanMacRc::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 209 of file uan-mac-rc.cc.
References m_dequeueLogger, m_enqueueLogger, m_learnedProp, m_maxFrames, m_minRetryRate, m_numRates, m_queueLimit, m_retryRate, m_retryStep, m_rxLogger, m_sifs, ns3::MakeDoubleAccessor(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), ns3::Seconds(), and ns3::TypeId::SetParent().
IsPhy1Ok()
bool ns3::UanMacRc::IsPhy1Ok (void) private
Check that PHY is ok: not CTS or ACK not to my address.
Returns
True if PHY is ok.
Definition at line 711 of file uan-mac-rc.cc.
References ns3::Mac8Address::ConvertFrom(), ns3::UanMac::GetAddress(), ns3::UanHeaderCommon::GetDest(), ns3::UanHeaderCommon::GetType(), m_phy, ns3::Packet::PeekHeader(), TYPE_ACK, and TYPE_CTS.
Referenced by Associate(), AssociateTimeout(), RtsTimeout(), and SendRts().
ProcessAck()
void ns3::UanMacRc::ProcessAck (Ptr< Packet > ack) private
Process a received ACK.
Parameters
ack The ACK packet.
Definition at line 551 of file uan-mac-rc.cc.
References ns3::Mac8Address::ConvertFrom(), ns3::UanMac::GetAddress(), ns3::UanHeaderRcAck::GetFrameNo(), ns3::UanHeaderRcAck::GetNackedFrames(), ns3::UanHeaderRcAck::GetNoNacks(), m_pktQueue, m_resList, ns3::Now(), NS_LOG_DEBUG, ns3::Packet::RemoveHeader(), and ns3::Time::S.
Referenced by ReceiveOkFromPhy().
ReceiveOkFromPhy()
void ns3::UanMacRc::ReceiveOkFromPhy (Ptr< Packet > pkt, double sinr, UanTxMode mode) private
PHY receive ok Callback.
Parameters
pkt The received packet.
sinr (Unused).
mode Modulation mode.
Definition at line 329 of file uan-mac-rc.cc.
References BlockRtsing(), ns3::Mac8Address::ConvertFrom(), ns3::UanMac::GetAddress(), ns3::UanHeaderRcCts::GetAddress(), ns3::Mac8Address::GetBroadcast(), ns3::UanHeaderCommon::GetDest(), ns3::UanHeaderCommon::GetProtocolNumber(), ns3::UanHeaderRcCtsGlobal::GetRateNum(), ns3::UanHeaderRcCtsGlobal::GetRetryRate(), ns3::UanHeaderCommon::GetSerializedSize(), ns3::Packet::GetSize(), ns3::UanHeaderCommon::GetSrc(), ns3::UanHeaderCommon::GetType(), ns3::UanHeaderRcCtsGlobal::GetWindowTime(), GWPSENT, m_assocAddr, m_currentRate, m_forwardUpCb, m_minRetryRate, m_retryRate, m_retryStep, m_rtsBlocked, m_rxLogger, m_state, ns3::Now(), NS_FATAL_ERROR, NS_LOG_DEBUG, NS_UNUSED, ProcessAck(), ns3::Packet::RemoveHeader(), RTSSENT, ns3::Time::S, ns3::Simulator::Schedule(), ScheduleData(), ns3::UanHeaderRcCts::SetAddress(), TYPE_ACK, TYPE_CTS, TYPE_DATA, TYPE_GWPING, and TYPE_RTS.
Referenced by AttachPhy().
RtsTimeout()
void ns3::UanMacRc::RtsTimeout (void) private
Retry RTS.
Definition at line 734 of file uan-mac-rc.cc.
References ns3::Packet::AddHeader(), ns3::Reservation::AddTimestamp(), ns3::Mac8Address::ConvertFrom(), CreateRtsHeader(), ns3::UanMac::GetAddress(), ns3::Mac8Address::GetBroadcast(), ns3::ExponentialRandomVariable::GetValue(), ns3::Reservation::IncrementRetry(), IsPhy1Ok(), ns3::EventId::IsRunning(), ns3::Reservation::IsTransmitted(), m_cntrlSends, m_currentRate, m_ev, m_numRates, m_phy, m_resList, m_retryRate, m_rtsBlocked, m_rtsEvent, m_state, ns3::Now(), ns3::Simulator::Now(), NS_ASSERT, NS_FATAL_ERROR, RTSSENT, ns3::Time::S, ns3::Simulator::Schedule(), ns3::Seconds(), SendPacket(), ns3::ObjectBase::SetAttribute(), timeout, and TYPE_RTS.
Referenced by SendRts().
ScheduleData()
void ns3::UanMacRc::ScheduleData (const UanHeaderRcCts & ctsh, const UanHeaderRcCtsGlobal & ctsg, uint32_t ctsBytes) private
Schedule Packet sends.
Parameters
ctsh The CTS header identifying the frame number and delay.
ctsg The CTS global header giving the transmit time stamp base.
ctsBytes Number of bytes total in CTS packet.
Definition at line 424 of file uan-mac-rc.cc.
References ns3::Packet::AddHeader(), ns3::Time::As(), ns3::EventId::Cancel(), ns3::Mac8Address::ConvertFrom(), ns3::Packet::Copy(), ns3::UanMac::GetAddress(), ns3::UanHeaderRcCts::GetDelayToTx(), ns3::UanHeaderRcCts::GetFrameNo(), ns3::Packet::GetSize(), ns3::UanHeaderRcCtsGlobal::GetTxTimeStamp(), ns3::ExponentialRandomVariable::GetValue(), GWPSENT, IDLE, ns3::EventId::IsRunning(), m_assocAddr, m_currentRate, m_ev, m_learnedProp, m_phy, m_pktQueue, m_resList, m_retryRate, m_rtsEvent, m_sifs, m_state, ns3::Now(), ns3::Simulator::Now(), NS_ASSERT, NS_FATAL_ERROR, NS_LOG_DEBUG, RTSSENT, ns3::Time::S, ns3::Simulator::Schedule(), ns3::Seconds(), SendPacket(), SendRts(), ns3::ObjectBase::SetAttribute(), ns3::UanHeaderCommon::SetDest(), ns3::UanHeaderRcData::SetFrameNo(), ns3::UanHeaderRcData::SetPropDelay(), ns3::UanHeaderCommon::SetSrc(), ns3::UanHeaderCommon::SetType(), timeout, and TYPE_DATA.
Referenced by ReceiveOkFromPhy().
SendPacket()
void ns3::UanMacRc::SendPacket (Ptr< Packet > pkt, uint32_t rate) private
Send on packet on the PHY.
Parameters
pkt The packet.
rate The transmission rate.
Definition at line 515 of file uan-mac-rc.cc.
References ns3::Mac8Address::ConvertFrom(), ns3::UanMac::GetAddress(), ns3::UanHeaderCommon::GetDest(), ns3::Packet::GetSize(), ns3::UanHeaderCommon::GetType(), m_dequeueLogger, m_phy, ns3::Now(), NS_LOG_DEBUG, ns3::Packet::PeekHeader(), ns3::Time::S, TYPE_ACK, TYPE_CTS, TYPE_DATA, TYPE_GWPING, and TYPE_RTS.
Referenced by Associate(), AssociateTimeout(), RtsTimeout(), ScheduleData(), and SendRts().
SendRts()
void ns3::UanMacRc::SendRts (void) private
Send RTS packet.
Definition at line 678 of file uan-mac-rc.cc.
References ns3::Packet::AddHeader(), ns3::Reservation::AddTimestamp(), ns3::Mac8Address::ConvertFrom(), CreateRtsHeader(), ns3::UanMac::GetAddress(), ns3::Mac8Address::GetBroadcast(), ns3::ExponentialRandomVariable::GetValue(), IsPhy1Ok(), ns3::EventId::IsRunning(), m_cntrlSends, m_currentRate, m_ev, m_frameNo, m_maxFrames, m_numRates, m_phy, m_pktQueue, m_resList, m_retryRate, m_rtsBlocked, m_rtsEvent, m_state, ns3::Simulator::Now(), NS_ASSERT, RTSSENT, RtsTimeout(), ns3::Simulator::Schedule(), ns3::Seconds(), SendPacket(), ns3::ObjectBase::SetAttribute(), timeout, and TYPE_RTS.
Referenced by Enqueue(), and ScheduleData().
SetForwardUpCb()
void ns3::UanMacRc::SetForwardUpCb (Callback< void, Ptr< Packet >, uint16_t, const Mac8Address & > cb) virtual
Set the callback to forward packets up to higher layers.
Parameters
cb The callback. packet The packet. address The source address.
Implements ns3::UanMac.
Definition at line 316 of file uan-mac-rc.cc.
References m_forwardUpCb.
Member Data Documentation
m_assocAddr
Mac8Address ns3::UanMacRc::m_assocAddr private
Next hop address.
Definition at line 216 of file uan-mac-rc.h.
Referenced by ReceiveOkFromPhy(), and ScheduleData().
m_cleared
bool ns3::UanMacRc::m_cleared private
Flag when we've been cleared.
Definition at line 232 of file uan-mac-rc.h.
Referenced by Clear().
m_cntrlSends
uint32_t ns3::UanMacRc::m_cntrlSends = 0 static private
Global count of calls to Associate, AssociateTimeout, SendRts, and RtsTimeout.
Definition at line 309 of file uan-mac-rc.h.
Referenced by Associate(), AssociateTimeout(), RtsTimeout(), and SendRts().
m_ctsSizeG
uint32_t ns3::UanMacRc::m_ctsSizeG private
Size of UanHeaderCommon and UanHeaderRcCtsGlobal.
Definition at line 230 of file uan-mac-rc.h.
Referenced by UanMacRc().
m_ctsSizeN
uint32_t ns3::UanMacRc::m_ctsSizeN private
Size of UanHeaderRcCts.
Definition at line 229 of file uan-mac-rc.h.
Referenced by UanMacRc().
m_currentRate
uint32_t ns3::UanMacRc::m_currentRate private
Rate number corresponding to data rate of current cycle.
Definition at line 219 of file uan-mac-rc.h.
Referenced by Associate(), AssociateTimeout(), ReceiveOkFromPhy(), RtsTimeout(), ScheduleData(), and SendRts().
m_dequeueLogger
TracedCallback<Ptr<const Packet>, uint32_t > ns3::UanMacRc::m_dequeueLogger private
A was passed down to the PHY from the MAC.
Definition at line 247 of file uan-mac-rc.h.
Referenced by GetTypeId(), and SendPacket().
m_enqueueLogger
TracedCallback<Ptr<const Packet>, uint32_t > ns3::UanMacRc::m_enqueueLogger private
A packet arrived at the MAC for transmission.
Definition at line 245 of file uan-mac-rc.h.
Referenced by GetTypeId().
m_ev
Ptr<ExponentialRandomVariable> ns3::UanMacRc::m_ev private
Provides exponential random variables.
Definition at line 312 of file uan-mac-rc.h.
Referenced by UanMacRc(), AssignStreams(), Associate(), AssociateTimeout(), RtsTimeout(), ScheduleData(), and SendRts().
m_forwardUpCb
Callback<void, Ptr<Packet>, uint16_t, const Mac8Address&> ns3::UanMacRc::m_forwardUpCb private
The callback to forward a packet up to higher layer.
Definition at line 240 of file uan-mac-rc.h.
Referenced by ReceiveOkFromPhy(), and SetForwardUpCb().
m_frameNo
uint8_t ns3::UanMacRc::m_frameNo private
Current frame number.
Definition at line 222 of file uan-mac-rc.h.
Referenced by Associate(), and SendRts().
m_learnedProp
Time ns3::UanMacRc::m_learnedProp private
Propagation delay to gateway.
Definition at line 224 of file uan-mac-rc.h.
Referenced by GetTypeId(), and ScheduleData().
m_maxFrames
uint32_t ns3::UanMacRc::m_maxFrames private
Maximum number of frames to include in a single RTS.
Definition at line 220 of file uan-mac-rc.h.
Referenced by Associate(), GetTypeId(), and SendRts().
m_minRetryRate
double ns3::UanMacRc::m_minRetryRate private
Smallest allowed RTS retry rate.
Definition at line 226 of file uan-mac-rc.h.
Referenced by GetTypeId(), and ReceiveOkFromPhy().
m_numRates
uint32_t ns3::UanMacRc::m_numRates private
Number of rates per Phy layer.
Definition at line 218 of file uan-mac-rc.h.
Referenced by Associate(), AssociateTimeout(), GetTypeId(), RtsTimeout(), and SendRts().
m_phy
Ptr<UanPhy> ns3::UanMacRc::m_phy private
PHY layer attached to this MAC.
Definition at line 217 of file uan-mac-rc.h.
Referenced by Associate(), AssociateTimeout(), AttachPhy(), Clear(), IsPhy1Ok(), RtsTimeout(), ScheduleData(), SendPacket(), and SendRts().
m_pktQueue
std::list<std::pair <Ptr<Packet>, Mac8Address > > ns3::UanMacRc::m_pktQueue private
Pending packets.
Definition at line 235 of file uan-mac-rc.h.
Referenced by Associate(), Clear(), Enqueue(), ProcessAck(), ScheduleData(), and SendRts().
m_queueLimit
uint32_t ns3::UanMacRc::m_queueLimit private
Maximum packets to queue at MAC.
Definition at line 221 of file uan-mac-rc.h.
Referenced by Enqueue(), and GetTypeId().
m_resList
std::list<Reservation> ns3::UanMacRc::m_resList private
List of scheduled reservations.
Definition at line 237 of file uan-mac-rc.h.
Referenced by Associate(), AssociateTimeout(), Clear(), ProcessAck(), RtsTimeout(), ScheduleData(), and SendRts().
m_retryRate
double ns3::UanMacRc::m_retryRate private
Number of retry attempts per second (of RTS/GWPING.
Definition at line 215 of file uan-mac-rc.h.
Referenced by Associate(), AssociateTimeout(), GetTypeId(), ReceiveOkFromPhy(), RtsTimeout(), ScheduleData(), and SendRts().
m_retryStep
double ns3::UanMacRc::m_retryStep private
Retry rate increment.
Definition at line 227 of file uan-mac-rc.h.
Referenced by GetTypeId(), and ReceiveOkFromPhy().
m_rtsBlocked
bool ns3::UanMacRc::m_rtsBlocked private
RTS blocked while processing ACK.
Definition at line 212 of file uan-mac-rc.h.
Referenced by Associate(), AssociateTimeout(), BlockRtsing(), ReceiveOkFromPhy(), RtsTimeout(), and SendRts().
m_rtsEvent
EventId ns3::UanMacRc::m_rtsEvent private
The RTS event.
Definition at line 250 of file uan-mac-rc.h.
Referenced by Associate(), AssociateTimeout(), Clear(), Enqueue(), RtsTimeout(), ScheduleData(), and SendRts().
m_rxLogger
TracedCallback<Ptr<const Packet>, UanTxMode > ns3::UanMacRc::m_rxLogger private
A packet was destined for and received at this MAC layer.
Definition at line 243 of file uan-mac-rc.h.
Referenced by GetTypeId(), and ReceiveOkFromPhy().
m_sifs
Time ns3::UanMacRc::m_sifs private
Spacing between frames to account for timing error and processing delay.
Definition at line 223 of file uan-mac-rc.h.
Referenced by GetTypeId(), and ScheduleData().
m_startAgain
EventId ns3::UanMacRc::m_startAgain private
(Unused).
Definition at line 214 of file uan-mac-rc.h.
Referenced by Clear().
m_state
State ns3::UanMacRc::m_state private
MAC state.
Definition at line 211 of file uan-mac-rc.h.
Referenced by Associate(), AssociateTimeout(), Enqueue(), ReceiveOkFromPhy(), RtsTimeout(), ScheduleData(), and SendRts().
The documentation for this class was generated from the following files:
src/uan/model/uan-mac-rc.h
src/uan/model/uan-mac-rc.cc