ns-3: ns3::OnOffApplication Class Reference
ns3::OnOffApplication Class Reference
Applications » OnOffApplication
Generate traffic to a single destination according to an OnOff pattern.
#include "onoff-application.h"
Public Member Functions
OnOffApplication ()
virtual ~OnOffApplication ()
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Ptr< Socket > GetSocket (void) const
Return a pointer to associated socket.
void SetMaxBytes (uint64_t maxBytes)
Set the total number of bytes to send.
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Application
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void CancelEvents ()
Cancel all pending events.
void ConnectionFailed (Ptr< Socket > socket)
Handle a Connection Failed event.
void ConnectionSucceeded (Ptr< Socket > socket)
Handle a Connection Succeed event.
void ScheduleNextTx ()
Schedule the next packet transmission.
void ScheduleStartEvent ()
Schedule the next On period start.
void ScheduleStopEvent ()
Schedule the next Off period start.
void SendPacket ()
Send a packet.
virtual void StartApplication (void)
Application specific startup code.
void StartSending ()
Start an On period.
virtual void StopApplication (void)
Application specific shutdown code.
void StopSending ()
Start an Off period.
Private Attributes
DataRate m_cbrRate
Rate that data is generated.
DataRate m_cbrRateFailSafe
Rate that data is generated (check copy)
bool m_connected
True if connected.
bool m_enableSeqTsSizeHeader {false}
Enable or disable the use of SeqTsSizeHeader.
Time m_lastStartTime
Time last packet sent.
Address m_local
Local address to bind to.
uint64_t m_maxBytes
Limit total number of bytes sent.
Ptr< RandomVariableStream > m_offTime
rng for Off Time
Ptr< RandomVariableStream > m_onTime
rng for On Time
Address m_peer
Peer address.
uint32_t m_pktSize
Size of packets.
uint32_t m_residualBits
Number of generated, but not sent, bits.
EventId m_sendEvent
Event id of pending "send packet" event.
uint32_t m_seq {0}
Sequence.
Ptr< Socket > m_socket
Associated socket.
EventId m_startStopEvent
Event id for next start or stop event.
TypeId m_tid
Type of the socket used.
uint64_t m_totBytes
Total bytes sent so far.
TracedCallback< Ptr< const Packet > > m_txTrace
Traced Callback: transmitted packets.
TracedCallback< Ptr< const Packet >, const Address &, const Address & > m_txTraceWithAddresses
Callbacks for tracing the packet Tx events, includes source and destination addresses.
TracedCallback< Ptr< const Packet >, const Address &, const Address &, const SeqTsSizeHeader & > m_txTraceWithSeqTsSize
Callback for tracing the packet Tx events, includes source, destination, the packet sent, and header.
Ptr< Packet > m_unsentPacket
Unsent packet cached for future attempt.
Additional Inherited Members
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Generate traffic to a single destination according to an OnOff pattern.
This traffic generator follows an On/Off pattern: after Application::StartApplication is called, "On" and "Off" states alternate. The duration of each of these states is determined with the onTime and the offTime random variables. During the "Off" state, no traffic is generated. During the "On" state, cbr traffic is generated. This cbr traffic is characterized by the specified "data rate" and "packet size".
Note: When an application is started, the first packet transmission occurs after a delay equal to (packet size/bit rate). Note also, when an application transitions into an off state in between packet transmissions, the remaining time until when the next transmission would have occurred is cached and is used when the application starts up again. Example: packet size = 1000 bits, bit rate = 500 bits/sec. If the application is started at time 3 seconds, the first packet transmission will be scheduled for time 5 seconds (3 + 1000/500) and subsequent transmissions at 2 second intervals. If the above application were instead stopped at time 4 seconds, and restarted at time 5.5 seconds, then the first packet would be sent at time 6.5 seconds, because when it was stopped at 4 seconds, there was only 1 second remaining until the originally scheduled transmission, and this time remaining information is cached and used to schedule the next transmission upon restarting.
If the underlying socket type supports broadcast, this application will automatically enable the SetAllowBroadcast(true) socket option.
If the attribute "EnableSeqTsSizeHeader" is enabled, the application will use some bytes of the payload to store an header with a sequence number, a timestamp, and the size of the packet sent. Support for extracting statistics from this header have been added to ns3::PacketSink (enable its "EnableSeqTsSizeHeader" attribute), or users may extract the header via trace sources. Note that the continuity of the sequence number may be disrupted across On/Off cycles.
Config Paths
ns3::OnOffApplication is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/ApplicationList/[i]/$ns3::OnOffApplication"
Attributes
DataRate: The data rate in on state.
Set with class: DataRateValue
Underlying type: DataRate
Initial value: 500000bps
Flags: construct write read
PacketSize: The size of packets sent in on state
Set with class: ns3::UintegerValue
Underlying type: uint32_t 1:4294967295
Initial value: 512
Flags: construct write read
Remote: The address of the destination
Set with class: AddressValue
Underlying type: Address
Initial value: 00-00-00
Flags: construct write read
Local: The Address on which to bind the socket. If not set, it is generated automatically.
Set with class: AddressValue
Underlying type: Address
Initial value: 00-00-00
Flags: construct write read
OnTime: A RandomVariableStream used to pick the duration of the 'On' state.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::RandomVariableStream>
Initial value: ns3::ConstantRandomVariable[Constant=1.0]
Flags: construct write read
OffTime: A RandomVariableStream used to pick the duration of the 'Off' state.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::RandomVariableStream>
Initial value: ns3::ConstantRandomVariable[Constant=1.0]
Flags: construct write read
MaxBytes: The total number of bytes to send. Once these bytes are sent, no packet is sent again, even in on state. The value zero means that there is no limit.
Set with class: ns3::UintegerValue
Underlying type: uint64_t 0:18446744073709551615
Initial value: 0
Flags: construct write read
Protocol: The type of protocol to use. This should be a subclass of ns3::SocketFactory
Set with class: TypeIdValue
Underlying type: TypeId
Initial value: ns3::UdpSocketFactory
Flags: construct write read
EnableSeqTsSizeHeader: Enable use of SeqTsSizeHeader for sequence number and timestamp
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
Attributes defined in parent class ns3::Application
StartTime: Time at which the application will start
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
StopTime: Time at which the application will stop
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
TraceSources
Tx: A new packet is created and is sent
Callback signature: ns3::Packet::TracedCallback
TxWithAddresses: A new packet is created and is sent
Callback signature: ns3::Packet::TwoAddressTracedCallback
TxWithSeqTsSize: A new packet is created with SeqTsSizeHeader
Callback signature: ns3::PacketSink::SeqTsSizeCallback
Size of this type is 368 bytes (on a 64-bit architecture).
Definition at line 95 of file onoff-application.h.
Constructor & Destructor Documentation
OnOffApplication()
ns3::OnOffApplication::OnOffApplication ()
Definition at line 116 of file onoff-application.cc.
References NS_LOG_FUNCTION.
~OnOffApplication()
ns3::OnOffApplication::~OnOffApplication () virtual
Definition at line 127 of file onoff-application.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AssignStreams()
int64_t ns3::OnOffApplication::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 147 of file onoff-application.cc.
References m_offTime, m_onTime, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
CancelEvents()
void ns3::OnOffApplication::CancelEvents () private
Cancel all pending events.
Definition at line 236 of file onoff-application.cc.
References ns3::Simulator::Cancel(), ns3::DataRate::GetBitRate(), ns3::int64x64_t::GetHigh(), ns3::EventId::IsRunning(), m_cbrRate, m_cbrRateFailSafe, m_lastStartTime, m_residualBits, m_sendEvent, m_startStopEvent, m_unsentPacket, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Time::S, and ns3::Time::To().
Referenced by DoDispose(), StartApplication(), StopApplication(), and StopSending().
ConnectionFailed()
void ns3::OnOffApplication::ConnectionFailed (Ptr< Socket > socket) private
Handle a Connection Failed event.
Parameters
socket the not connected socket
Definition at line 393 of file onoff-application.cc.
References NS_FATAL_ERROR, and NS_LOG_FUNCTION.
Referenced by StartApplication().
ConnectionSucceeded()
void ns3::OnOffApplication::ConnectionSucceeded (Ptr< Socket > socket) private
Handle a Connection Succeed event.
Parameters
socket the connected socket
Definition at line 387 of file onoff-application.cc.
References m_connected, and NS_LOG_FUNCTION.
Referenced by StartApplication().
DoDispose()
void ns3::OnOffApplication::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Application.
Definition at line 156 of file onoff-application.cc.
References CancelEvents(), ns3::Application::DoDispose(), m_socket, m_unsentPacket, and NS_LOG_FUNCTION.
GetSocket()
Ptr< Socket > ns3::OnOffApplication::GetSocket (void) const
Return a pointer to associated socket.
Returns
pointer to associated socket
Definition at line 140 of file onoff-application.cc.
References m_socket, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::OnOffApplication::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 53 of file onoff-application.cc.
References ns3::UdpSocketFactory::GetTypeId(), m_cbrRate, m_enableSeqTsSizeHeader, m_local, m_maxBytes, m_offTime, m_onTime, m_peer, m_pktSize, m_tid, m_txTrace, m_txTraceWithAddresses, m_txTraceWithSeqTsSize, ns3::MakeAddressAccessor(), ns3::MakeAddressChecker(), ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeDataRateAccessor(), ns3::MakeDataRateChecker(), ns3::MakePointerAccessor(), ns3::MakeTraceSourceAccessor(), ns3::MakeTypeIdAccessor(), ns3::MakeTypeIdChecker(), ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
ScheduleNextTx()
void ns3::OnOffApplication::ScheduleNextTx () private
Schedule the next packet transmission.
Definition at line 277 of file onoff-application.cc.
References ns3::Time::As(), ns3::DataRate::GetBitRate(), m_cbrRate, m_maxBytes, m_pktSize, m_residualBits, m_sendEvent, m_totBytes, NS_ABORT_MSG_IF, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Time::S, ns3::Simulator::Schedule(), ns3::Seconds(), SendPacket(), and StopApplication().
Referenced by SendPacket(), and StartSending().
ScheduleStartEvent()
void ns3::OnOffApplication::ScheduleStartEvent () private
Schedule the next On period start.
Definition at line 298 of file onoff-application.cc.
References ns3::Time::As(), ns3::RandomVariableStream::GetValue(), m_offTime, m_startStopEvent, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Time::S, ns3::Simulator::Schedule(), ns3::Seconds(), and StartSending().
Referenced by StartApplication(), and StopSending().
ScheduleStopEvent()
void ns3::OnOffApplication::ScheduleStopEvent () private
Schedule the next Off period start.
Definition at line 307 of file onoff-application.cc.
References ns3::Time::As(), ns3::RandomVariableStream::GetValue(), m_onTime, m_startStopEvent, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Time::S, ns3::Simulator::Schedule(), ns3::Seconds(), and StopSending().
Referenced by StartSending().
SendPacket()
void ns3::OnOffApplication::SendPacket (void) private
Send a packet.
Definition at line 317 of file onoff-application.cc.
References ns3::Packet::AddHeader(), ns3::Inet6SocketAddress::ConvertFrom(), ns3::InetSocketAddress::ConvertFrom(), ns3::InetSocketAddress::GetIpv4(), ns3::Inet6SocketAddress::GetIpv6(), ns3::Socket::GetPeerName(), ns3::InetSocketAddress::GetPort(), ns3::Inet6SocketAddress::GetPort(), ns3::SeqTsSizeHeader::GetSerializedSize(), ns3::Packet::GetSize(), ns3::Socket::GetSockName(), ns3::EventId::IsExpired(), ns3::Inet6SocketAddress::IsMatchingType(), ns3::InetSocketAddress::IsMatchingType(), m_enableSeqTsSizeHeader, m_lastStartTime, m_peer, m_pktSize, m_residualBits, m_sendEvent, m_seq, m_socket, m_totBytes, m_txTrace, m_txTraceWithAddresses, m_txTraceWithSeqTsSize, m_unsentPacket, ns3::Simulator::Now(), NS_ABORT_IF, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::Time::S, ScheduleNextTx(), ns3::Socket::Send(), ns3::SeqTsHeader::SetSeq(), and ns3::SeqTsSizeHeader::SetSize().
Referenced by ScheduleNextTx().
SetMaxBytes()
void ns3::OnOffApplication::SetMaxBytes (uint64_t maxBytes)
Set the total number of bytes to send.
Once these bytes are sent, no packet is sent again, even in on state. The value zero means that there is no limit.
Parameters
maxBytes the total number of bytes to send
Definition at line 133 of file onoff-application.cc.
References m_maxBytes, and NS_LOG_FUNCTION.
StartApplication()
void ns3::OnOffApplication::StartApplication (void) private virtual
Application specific startup code.
The StartApplication method is called at the start time specified by Start This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 168 of file onoff-application.cc.
References ns3::Socket::Bind(), ns3::Socket::Bind6(), CancelEvents(), ns3::Socket::Connect(), ConnectionFailed(), ConnectionSucceeded(), ns3::Socket::CreateSocket(), ns3::Application::GetNode(), ns3::Address::IsInvalid(), ns3::Inet6SocketAddress::IsMatchingType(), ns3::InetSocketAddress::IsMatchingType(), ns3::PacketSocketAddress::IsMatchingType(), m_cbrRate, m_cbrRateFailSafe, m_local, m_peer, m_socket, m_tid, ns3::MakeCallback(), NS_ABORT_MSG_IF, NS_FATAL_ERROR, NS_LOG_FUNCTION, ScheduleStartEvent(), ns3::Socket::SetAllowBroadcast(), ns3::Socket::SetConnectCallback(), and ns3::Socket::ShutdownRecv().
StartSending()
void ns3::OnOffApplication::StartSending () private
Start an On period.
Definition at line 260 of file onoff-application.cc.
References m_lastStartTime, ns3::Simulator::Now(), NS_LOG_FUNCTION, ScheduleNextTx(), and ScheduleStopEvent().
Referenced by ScheduleStartEvent().
StopApplication()
void ns3::OnOffApplication::StopApplication (void) private virtual
Application specific shutdown code.
The StopApplication method is called at the stop time specified by Stop This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 221 of file onoff-application.cc.
References CancelEvents(), ns3::Socket::Close(), m_socket, NS_LOG_FUNCTION, and NS_LOG_WARN.
Referenced by ScheduleNextTx().
StopSending()
void ns3::OnOffApplication::StopSending () private
Start an Off period.
Definition at line 268 of file onoff-application.cc.
References CancelEvents(), NS_LOG_FUNCTION, and ScheduleStartEvent().
Referenced by ScheduleStopEvent().
Member Data Documentation
m_cbrRate
DataRate ns3::OnOffApplication::m_cbrRate private
Rate that data is generated.
Definition at line 166 of file onoff-application.h.
Referenced by CancelEvents(), GetTypeId(), ScheduleNextTx(), and StartApplication().
m_cbrRateFailSafe
DataRate ns3::OnOffApplication::m_cbrRateFailSafe private
Rate that data is generated (check copy)
Definition at line 167 of file onoff-application.h.
Referenced by CancelEvents(), and StartApplication().
m_connected
bool ns3::OnOffApplication::m_connected private
True if connected.
Definition at line 163 of file onoff-application.h.
Referenced by ConnectionSucceeded().
m_enableSeqTsSizeHeader
bool ns3::OnOffApplication::m_enableSeqTsSizeHeader {false} private
Enable or disable the use of SeqTsSizeHeader.
Definition at line 178 of file onoff-application.h.
Referenced by GetTypeId(), and SendPacket().
m_lastStartTime
Time ns3::OnOffApplication::m_lastStartTime private
Time last packet sent.
Definition at line 170 of file onoff-application.h.
Referenced by CancelEvents(), SendPacket(), and StartSending().
m_local
Address ns3::OnOffApplication::m_local private
Local address to bind to.
Definition at line 162 of file onoff-application.h.
Referenced by GetTypeId(), and StartApplication().
m_maxBytes
uint64_t ns3::OnOffApplication::m_maxBytes private
Limit total number of bytes sent.
Definition at line 171 of file onoff-application.h.
Referenced by GetTypeId(), ScheduleNextTx(), and SetMaxBytes().
m_offTime
Ptr<RandomVariableStream> ns3::OnOffApplication::m_offTime private
rng for Off Time
Definition at line 165 of file onoff-application.h.
Referenced by AssignStreams(), GetTypeId(), and ScheduleStartEvent().
m_onTime
Ptr<RandomVariableStream> ns3::OnOffApplication::m_onTime private
rng for On Time
Definition at line 164 of file onoff-application.h.
Referenced by AssignStreams(), GetTypeId(), and ScheduleStopEvent().
m_peer
Address ns3::OnOffApplication::m_peer private
Peer address.
Definition at line 161 of file onoff-application.h.
Referenced by GetTypeId(), SendPacket(), and StartApplication().
m_pktSize
uint32_t ns3::OnOffApplication::m_pktSize private
Size of packets.
Definition at line 168 of file onoff-application.h.
Referenced by GetTypeId(), ScheduleNextTx(), and SendPacket().
m_residualBits
uint32_t ns3::OnOffApplication::m_residualBits private
Number of generated, but not sent, bits.
Definition at line 169 of file onoff-application.h.
Referenced by CancelEvents(), ScheduleNextTx(), and SendPacket().
m_sendEvent
EventId ns3::OnOffApplication::m_sendEvent private
Event id of pending "send packet" event.
Definition at line 174 of file onoff-application.h.
Referenced by CancelEvents(), ScheduleNextTx(), and SendPacket().
m_seq
uint32_t ns3::OnOffApplication::m_seq {0} private
Sequence.
Definition at line 176 of file onoff-application.h.
Referenced by SendPacket().
m_socket
Ptr<Socket> ns3::OnOffApplication::m_socket private
Associated socket.
Definition at line 160 of file onoff-application.h.
Referenced by DoDispose(), GetSocket(), SendPacket(), StartApplication(), and StopApplication().
m_startStopEvent
EventId ns3::OnOffApplication::m_startStopEvent private
Event id for next start or stop event.
Definition at line 173 of file onoff-application.h.
Referenced by CancelEvents(), ScheduleStartEvent(), and ScheduleStopEvent().
m_tid
TypeId ns3::OnOffApplication::m_tid private
Type of the socket used.
Definition at line 175 of file onoff-application.h.
Referenced by GetTypeId(), and StartApplication().
m_totBytes
uint64_t ns3::OnOffApplication::m_totBytes private
Total bytes sent so far.
Definition at line 172 of file onoff-application.h.
Referenced by ScheduleNextTx(), and SendPacket().
m_txTrace
TracedCallback<Ptr<const Packet> > ns3::OnOffApplication::m_txTrace private
Traced Callback: transmitted packets.
Definition at line 182 of file onoff-application.h.
Referenced by GetTypeId(), and SendPacket().
m_txTraceWithAddresses
TracedCallback<Ptr<const Packet>, const Address &, const Address &> ns3::OnOffApplication::m_txTraceWithAddresses private
Callbacks for tracing the packet Tx events, includes source and destination addresses.
Definition at line 185 of file onoff-application.h.
Referenced by GetTypeId(), and SendPacket().
m_txTraceWithSeqTsSize
TracedCallback<Ptr<const Packet>, const Address &, const Address &, const SeqTsSizeHeader &> ns3::OnOffApplication::m_txTraceWithSeqTsSize private
Callback for tracing the packet Tx events, includes source, destination, the packet sent, and header.
Definition at line 188 of file onoff-application.h.
Referenced by GetTypeId(), and SendPacket().
m_unsentPacket
Ptr<Packet> ns3::OnOffApplication::m_unsentPacket private
Unsent packet cached for future attempt.
Definition at line 177 of file onoff-application.h.
Referenced by CancelEvents(), DoDispose(), and SendPacket().
The documentation for this class was generated from the following files:
src/applications/model/onoff-application.h
src/applications/model/onoff-application.cc