ns-3: ns3::dot11s::PeerManagementProtocolMac Class Reference
ns3::dot11s::PeerManagementProtocolMac Class Reference
Mesh Device » IEEE 802.11s draft
This is plugin to Mesh WiFi MAC, which implements the interface to dot11s peer management protocol: it takes proper frames from MAC-layer, extracts peer link management information element and mesh configuration element and passes it to main part of protocol.
#include "peer-management-protocol-mac.h"
Classes
struct PlinkFrameStart
This structure keeps all fields in peer link management frame, which are not subclasses of WifiInformationElement.
struct Statistics
Statistics structure.
Public Member Functions
PeerManagementProtocolMac (uint32_t interface, Ptr< PeerManagementProtocol > protocol)
Constructor.
~PeerManagementProtocolMac ()
int64_t AssignStreams (int64_t stream)
Assign the streams.
bool Receive (Ptr< Packet > packet, const WifiMacHeader &header)
Receive and process a packet.
void SetParent (Ptr< MeshWifiInterfaceMac > parent)
Set pointer to parent.
void UpdateBeacon (MeshWifiBeacon &beacon) const
Add beacon timing and mesh ID information elements, and notify beacon sent.
bool UpdateOutcomingFrame (Ptr< Packet > packet, WifiMacHeader &header, Mac48Address from, Mac48Address to)
This method appears to test a few conditions.
Public Member Functions inherited from ns3::MeshWifiInterfaceMacPlugin
virtual ~MeshWifiInterfaceMacPlugin ()
This is for subclasses.
Public Member Functions inherited from ns3::SimpleRefCount< MeshWifiInterfaceMacPlugin >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
Information about MAC and protocol:
Ptr< MeshWifiInterfaceMac > m_parent
parent
uint32_t m_ifIndex
IF index.
Ptr< PeerManagementProtocol > m_protocol
protocol
Statistics
class PeerManagementProtocol
allow PeerManagementProtocol class access friend access
class PeerLink
allow PeerLink class access friend access
void Report (std::ostream &) const
allow PeerManagementProtocol class access friend access
void ResetStats ()
allow PeerManagementProtocol class access friend access
uint32_t GetLinkMetric (Mac48Address peerAddress)
allow PeerManagementProtocol class access friend access
PeerManagementProtocolMac & operator= (const PeerManagementProtocolMac &peer)
assignment operator
PeerManagementProtocolMac (const PeerManagementProtocolMac &)
type conversion operator
Create peer link management frames
struct Statistics m_stats
statistics
Ptr< Packet > CreatePeerLinkOpenFrame ()
Create peer link open frame function.
Ptr< Packet > CreatePeerLinkConfirmFrame ()
Create peer link confirm frame function.
Ptr< Packet > CreatePeerLinkCloseFrame ()
Create peer link clode frame function.
PlinkFrameStart ParsePlinkFrame (Ptr< const Packet > packet)
Parses the start of the frame, where no WifiInformationElements exist.
void TxError (WifiMacHeader const &hdr)
Closes link when a proper number of successive transmissions have failed.
void TxOk (WifiMacHeader const &hdr)
Transmit OK function.
void SetBeaconShift (Time shift)
Set beacon shift function.
void SetPeerManagerProtcol (Ptr< PeerManagementProtocol > protocol)
Set peer manager protocol function.
void SendPeerLinkManagementFrame (Mac48Address peerAddress, Mac48Address peerMpAddress, uint16_t aid, IePeerManagement peerElement, IeConfiguration meshConfig)
Send peer link management frame function.
Mac48Address GetAddress () const
debug only, used to print established links
Detailed Description
This is plugin to Mesh WiFi MAC, which implements the interface to dot11s peer management protocol: it takes proper frames from MAC-layer, extracts peer link management information element and mesh configuration element and passes it to main part of protocol.
Definition at line 42 of file peer-management-protocol-mac.h.
Constructor & Destructor Documentation
PeerManagementProtocolMac() [1/2]
ns3::dot11s::PeerManagementProtocolMac::PeerManagementProtocolMac (uint32_t interface, Ptr< PeerManagementProtocol > protocol)
Constructor.
Parameters
interface interface index
protocol peer management protocol
Definition at line 37 of file peer-management-protocol-mac.cc.
References m_ifIndex, and m_protocol.
~PeerManagementProtocolMac()
ns3::dot11s::PeerManagementProtocolMac::~PeerManagementProtocolMac ()
Definition at line 44 of file peer-management-protocol-mac.cc.
PeerManagementProtocolMac() [2/2]
ns3::dot11s::PeerManagementProtocolMac::PeerManagementProtocolMac (const PeerManagementProtocolMac &) private
type conversion operator
Member Function Documentation
AssignStreams()
int64_t ns3::dot11s::PeerManagementProtocolMac::AssignStreams (int64_t stream) virtual
Assign the streams.
Parameters
stream the stream to assign
Returns
the assigned stream
Implements ns3::MeshWifiInterfaceMacPlugin.
Definition at line 389 of file peer-management-protocol-mac.cc.
References m_protocol.
CreatePeerLinkCloseFrame()
Ptr<Packet> ns3::dot11s::PeerManagementProtocolMac::CreatePeerLinkCloseFrame () private
Create peer link clode frame function.
Returns
the packet
CreatePeerLinkConfirmFrame()
Ptr<Packet> ns3::dot11s::PeerManagementProtocolMac::CreatePeerLinkConfirmFrame () private
Create peer link confirm frame function.
Returns
the packet
CreatePeerLinkOpenFrame()
Ptr<Packet> ns3::dot11s::PeerManagementProtocolMac::CreatePeerLinkOpenFrame () private
Create peer link open frame function.
Returns
the packet
GetAddress()
Mac48Address ns3::dot11s::PeerManagementProtocolMac::GetAddress (void) const private
debug only, used to print established links
Returns
the MAC address
Definition at line 327 of file peer-management-protocol-mac.cc.
References m_parent.
Referenced by ns3::dot11s::PeerLink::Report().
GetLinkMetric()
uint32_t ns3::dot11s::PeerManagementProtocolMac::GetLinkMetric (Mac48Address peerAddress)
allow PeerManagementProtocol class access friend access
Definition at line 384 of file peer-management-protocol-mac.cc.
References m_parent.
Referenced by ns3::dot11s::PeerLink::Report().
operator=()
PeerManagementProtocolMac& ns3::dot11s::PeerManagementProtocolMac::operator= (const PeerManagementProtocolMac & peer) private
assignment operator
Parameters
peer the object to assign
Returns
the assigned value
ParsePlinkFrame()
PlinkFrameStart ns3::dot11s::PeerManagementProtocolMac::ParsePlinkFrame (Ptr< const Packet > packet) private
Parses the start of the frame, where no WifiInformationElements exist.
Parameters
packet the packet
Returns
PlinkFrameStart
Receive()
bool ns3::dot11s::PeerManagementProtocolMac::Receive (Ptr< Packet > packet, const WifiMacHeader & header) virtual
Receive and process a packet.
Parameters
packet the packet received
header the header
Returns
true if received
Implements ns3::MeshWifiInterfaceMacPlugin.
Definition at line 66 of file peer-management-protocol-mac.cc.
References ns3::dot11s::PeerLinkConfirmStart::PlinkConfirmStartFields::aid, ns3::dot11s::PeerManagementProtocolMac::Statistics::brokenMgt, ns3::dot11s::PeerLinkOpenStart::PlinkOpenStartFields::config, ns3::dot11s::PeerLinkConfirmStart::PlinkConfirmStartFields::config, ns3::Packet::Copy(), ns3::WifiInformationElementVector::FindFirst(), ns3::WifiActionHeader::GetAction(), ns3::WifiMacHeader::GetAddr2(), ns3::WifiMacHeader::GetAddr3(), ns3::MgtProbeResponseHeader::GetBeaconIntervalUs(), ns3::WifiActionHeader::GetCategory(), ns3::dot11s::PeerLinkOpenStart::GetFields(), ns3::dot11s::PeerLinkCloseStart::GetFields(), ns3::dot11s::PeerLinkConfirmStart::GetFields(), ns3::Packet::GetSize(), IE_BEACON_TIMING, IE_MESH_ID, IE_MESH_PEERING_MANAGEMENT, ns3::WifiMacHeader::IsAction(), ns3::WifiMacHeader::IsBeacon(), ns3::dot11s::IeMeshId::IsEqual(), m_ifIndex, m_parent, m_protocol, m_stats, ns3::dot11s::PeerLinkOpenStart::PlinkOpenStartFields::meshId, ns3::dot11s::PeerLinkCloseStart::PlinkCloseStartFields::meshId, ns3::MicroSeconds(), NS_ASSERT, NS_FATAL_ERROR, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::WifiActionHeader::PEER_LINK_CLOSE, ns3::WifiActionHeader::PEER_LINK_CONFIRM, ns3::WifiActionHeader::PEER_LINK_OPEN, ns3::dot11s::PeerLinkOpenStart::PlinkOpenStartFields::rates, ns3::dot11s::PeerLinkConfirmStart::PlinkConfirmStartFields::rates, ns3::Packet::RemoveHeader(), ns3::dot11s::PeerManagementProtocolMac::Statistics::rxClose, ns3::dot11s::PeerManagementProtocolMac::Statistics::rxConfirm, ns3::dot11s::PeerManagementProtocolMac::Statistics::rxMgt, ns3::dot11s::PeerManagementProtocolMac::Statistics::rxMgtBytes, ns3::dot11s::PeerManagementProtocolMac::Statistics::rxOpen, ns3::WifiActionHeader::SELF_PROTECTED, and ns3::WifiActionHeader::ActionValue::selfProtectedAction.
Report()
void ns3::dot11s::PeerManagementProtocolMac::Report (std::ostream & os) const
allow PeerManagementProtocol class access friend access
Definition at line 371 of file peer-management-protocol-mac.cc.
References m_parent, m_stats, and ns3::dot11s::PeerManagementProtocolMac::Statistics::Print().
ResetStats()
void ns3::dot11s::PeerManagementProtocolMac::ResetStats ()
allow PeerManagementProtocol class access friend access
Definition at line 379 of file peer-management-protocol-mac.cc.
References m_stats.
SendPeerLinkManagementFrame()
void ns3::dot11s::PeerManagementProtocolMac::SendPeerLinkManagementFrame (Mac48Address peerAddress, Mac48Address peerMpAddress, uint16_t aid, IePeerManagement peerElement, IeConfiguration meshConfig) private
Send peer link management frame function.
Parameters
peerAddress the peer MAC address
peerMpAddress the peer MP address
aid the AID
peerElement IePeerManagement
meshConfig IeConfiguration
Definition at line 252 of file peer-management-protocol-mac.cc.
References ns3::Packet::AddHeader(), ns3::WifiInformationElementVector::AddInformationElement(), ns3::dot11s::PeerLinkConfirmStart::PlinkConfirmStartFields::aid, ns3::dot11s::PeerLinkOpenStart::PlinkOpenStartFields::capability, ns3::dot11s::PeerLinkConfirmStart::PlinkConfirmStartFields::capability, ns3::dot11s::PeerLinkOpenStart::PlinkOpenStartFields::config, ns3::dot11s::PeerLinkConfirmStart::PlinkConfirmStartFields::config, ns3::Packet::GetSize(), m_parent, m_protocol, m_stats, ns3::dot11s::PeerLinkOpenStart::PlinkOpenStartFields::meshId, ns3::dot11s::PeerLinkCloseStart::PlinkCloseStartFields::meshId, NS_LOG_FUNCTION, ns3::WifiActionHeader::PEER_LINK_CLOSE, ns3::WifiActionHeader::PEER_LINK_CONFIRM, ns3::WifiActionHeader::PEER_LINK_OPEN, ns3::dot11s::PeerLinkOpenStart::PlinkOpenStartFields::rates, ns3::dot11s::PeerLinkConfirmStart::PlinkConfirmStartFields::rates, ns3::WifiActionHeader::SELF_PROTECTED, ns3::WifiActionHeader::ActionValue::selfProtectedAction, ns3::WifiActionHeader::SetAction(), ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetAddr2(), ns3::WifiMacHeader::SetAddr3(), ns3::WifiMacHeader::SetDsNotFrom(), ns3::WifiMacHeader::SetDsNotTo(), ns3::dot11s::IeConfiguration::SetNeighborCount(), ns3::dot11s::PeerLinkCloseStart::SetPlinkCloseStart(), ns3::dot11s::PeerLinkConfirmStart::SetPlinkConfirmStart(), ns3::dot11s::PeerLinkOpenStart::SetPlinkOpenStart(), ns3::WifiMacHeader::SetType(), ns3::dot11s::IePeerManagement::SubtypeIsClose(), ns3::dot11s::IePeerManagement::SubtypeIsConfirm(), ns3::dot11s::IePeerManagement::SubtypeIsOpen(), ns3::dot11s::PeerManagementProtocolMac::Statistics::txClose, ns3::dot11s::PeerManagementProtocolMac::Statistics::txConfirm, ns3::dot11s::PeerManagementProtocolMac::Statistics::txMgt, ns3::dot11s::PeerManagementProtocolMac::Statistics::txMgtBytes, ns3::dot11s::PeerManagementProtocolMac::Statistics::txOpen, and ns3::WIFI_MAC_MGT_ACTION.
Referenced by ns3::dot11s::PeerLink::SendPeerLinkClose(), ns3::dot11s::PeerLink::SendPeerLinkConfirm(), and ns3::dot11s::PeerLink::SendPeerLinkOpen().
SetBeaconShift()
void ns3::dot11s::PeerManagementProtocolMac::SetBeaconShift (Time shift) private
Set beacon shift function.
Parameters
shift the beacon time shift
Definition at line 339 of file peer-management-protocol-mac.cc.
References ns3::dot11s::PeerManagementProtocolMac::Statistics::beaconShift, m_parent, m_stats, and ns3::Seconds().
SetParent()
void ns3::dot11s::PeerManagementProtocolMac::SetParent (Ptr< MeshWifiInterfaceMac > parent) virtual
Set pointer to parent.
Parameters
parent Ptr<MeshWifiInterfaceMac>
Implements ns3::MeshWifiInterfaceMacPlugin.
Definition at line 49 of file peer-management-protocol-mac.cc.
References m_parent, ns3::MakeCallback(), TxError(), and TxOk().
SetPeerManagerProtcol()
void ns3::dot11s::PeerManagementProtocolMac::SetPeerManagerProtcol (Ptr< PeerManagementProtocol > protocol) private
Set peer manager protocol function.
Parameters
protocol the peer manager protocol
TxError()
void ns3::dot11s::PeerManagementProtocolMac::TxError (WifiMacHeader const & hdr) private
Closes link when a proper number of successive transmissions have failed.
Parameters
hdr the header
Definition at line 56 of file peer-management-protocol-mac.cc.
References ns3::WifiMacHeader::GetAddr1(), m_ifIndex, and m_protocol.
Referenced by SetParent().
TxOk()
void ns3::dot11s::PeerManagementProtocolMac::TxOk (WifiMacHeader const & hdr) private
Transmit OK function.
Parameters
hdr the header
Definition at line 61 of file peer-management-protocol-mac.cc.
References ns3::WifiMacHeader::GetAddr1(), m_ifIndex, and m_protocol.
Referenced by SetParent().
UpdateBeacon()
void ns3::dot11s::PeerManagementProtocolMac::UpdateBeacon (MeshWifiBeacon & beacon) const virtual
Add beacon timing and mesh ID information elements, and notify beacon sent.
Parameters
beacon the beacon
Implements ns3::MeshWifiInterfaceMacPlugin.
Definition at line 240 of file peer-management-protocol-mac.cc.
References ns3::MeshWifiBeacon::AddInformationElement(), ns3::MeshWifiBeacon::GetBeaconInterval(), m_ifIndex, and m_protocol.
UpdateOutcomingFrame()
bool ns3::dot11s::PeerManagementProtocolMac::UpdateOutcomingFrame (Ptr< Packet > packet, WifiMacHeader & header, Mac48Address from, Mac48Address to) virtual
This method appears to test a few conditions.
If an action frame, it returns true if SELF_PROTECTED. It then checks if it is either a broadcast or sent on an active link, and returns true if so. Otherwise, it returns false (indicating it is to be dropped)
Parameters
packet the packet
header the header
from the MAC address of the sender
to the MAC address of the receiver
Returns
true if successful, false if to be dropped
Implements ns3::MeshWifiInterfaceMacPlugin.
Definition at line 209 of file peer-management-protocol-mac.cc.
References ns3::dot11s::PeerManagementProtocolMac::Statistics::dropped, ns3::WifiMacHeader::GetAddr1(), ns3::WifiActionHeader::GetCategory(), ns3::WifiMacHeader::IsAction(), ns3::Mac48Address::IsGroup(), m_ifIndex, m_protocol, m_stats, NS_LOG_FUNCTION, ns3::Packet::PeekHeader(), and ns3::WifiActionHeader::SELF_PROTECTED.
Friends And Related Function Documentation
PeerLink
friend class PeerLink friend
allow PeerLink class access friend access
Definition at line 111 of file peer-management-protocol-mac.h.
PeerManagementProtocol
friend class PeerManagementProtocol friend
allow PeerManagementProtocol class access friend access
Definition at line 109 of file peer-management-protocol-mac.h.
Member Data Documentation
m_ifIndex
uint32_t ns3::dot11s::PeerManagementProtocolMac::m_ifIndex private
IF index.
Definition at line 218 of file peer-management-protocol-mac.h.
Referenced by PeerManagementProtocolMac(), Receive(), TxError(), TxOk(), UpdateBeacon(), and UpdateOutcomingFrame().
m_parent
Ptr<MeshWifiInterfaceMac> ns3::dot11s::PeerManagementProtocolMac::m_parent private
parent
Definition at line 217 of file peer-management-protocol-mac.h.
Referenced by GetAddress(), GetLinkMetric(), Receive(), Report(), SendPeerLinkManagementFrame(), SetBeaconShift(), and SetParent().
m_protocol
Ptr<PeerManagementProtocol> ns3::dot11s::PeerManagementProtocolMac::m_protocol private
protocol
Definition at line 219 of file peer-management-protocol-mac.h.
Referenced by PeerManagementProtocolMac(), AssignStreams(), Receive(), SendPeerLinkManagementFrame(), TxError(), TxOk(), UpdateBeacon(), and UpdateOutcomingFrame().
m_stats
struct Statistics ns3::dot11s::PeerManagementProtocolMac::m_stats private
statistics
Definition at line 187 of file peer-management-protocol-mac.h.
Referenced by Receive(), Report(), ResetStats(), SendPeerLinkManagementFrame(), SetBeaconShift(), and UpdateOutcomingFrame().
The documentation for this class was generated from the following files:
src/mesh/model/dot11s/peer-management-protocol-mac.h
src/mesh/model/dot11s/peer-management-protocol-mac.cc