ns-3: ns3::UdpEchoClient Class Reference
ns3::UdpEchoClient Class Reference
Applications » UdpEcho
A Udp Echo client.
#include "udp-echo-client.h"
Public Member Functions
UdpEchoClient ()
virtual ~UdpEchoClient ()
uint32_t GetDataSize (void) const
Get the number of data bytes that will be sent to the server.
void SetDataSize (uint32_t dataSize)
Set the data size of the packet (the number of bytes that are sent as data to the server).
void SetFill (std::string fill)
Set the data fill of the packet (what is sent as data to the server) to the zero-terminated contents of the fill string string.
void SetFill (uint8_t *fill, uint32_t fillSize, uint32_t dataSize)
Set the data fill of the packet (what is sent as data to the server) to the contents of the fill buffer, repeated as many times as is required.
void SetFill (uint8_t fill, uint32_t dataSize)
Set the data fill of the packet (what is sent as data to the server) to the repeated contents of the fill byte.
void SetRemote (Address addr)
set the remote address
void SetRemote (Address ip, uint16_t port)
set the remote address and port
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Application
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void HandleRead (Ptr< Socket > socket)
Handle a packet reception.
void ScheduleTransmit (Time dt)
Schedule the next packet transmission.
void Send (void)
Send a packet.
virtual void StartApplication (void)
Application specific startup code.
virtual void StopApplication (void)
Application specific shutdown code.
Private Attributes
uint32_t m_count
Maximum number of packets the application will send.
uint8_t * m_data
packet payload data
uint32_t m_dataSize
packet payload size (must be equal to m_size)
Time m_interval
Packet inter-send time.
Address m_peerAddress
Remote peer address.
uint16_t m_peerPort
Remote peer port.
TracedCallback< Ptr< const Packet > > m_rxTrace
Callbacks for tracing the packet Rx events.
TracedCallback< Ptr< const Packet >, const Address &, const Address & > m_rxTraceWithAddresses
Callbacks for tracing the packet Rx events, includes source and destination addresses.
EventId m_sendEvent
Event to send the next packet.
uint32_t m_sent
Counter for sent packets.
uint32_t m_size
Size of the sent packet.
Ptr< Socket > m_socket
Socket.
TracedCallback< Ptr< const Packet > > m_txTrace
Callbacks for tracing the packet Tx events.
TracedCallback< Ptr< const Packet >, const Address &, const Address & > m_txTraceWithAddresses
Callbacks for tracing the packet Tx events, includes source and destination addresses.
Additional Inherited Members
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A Udp Echo client.
Every packet sent should be returned by the server and received here.
Config Paths
ns3::UdpEchoClient is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/ApplicationList/[i]/$ns3::UdpEchoClient"
Attributes
MaxPackets: The maximum number of packets the application will send
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 100
Flags: construct write read
Interval: The time to wait between packets
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+09ns
Flags: construct write read
RemoteAddress: The destination Address of the outbound packets
Set with class: AddressValue
Underlying type: Address
Initial value: 00-00-00
Flags: construct write read
RemotePort: The destination port of the outbound packets
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 0
Flags: construct write read
PacketSize: Size of echo data in outbound packets
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 100
Flags: construct write read
Attributes defined in parent class ns3::Application
StartTime: Time at which the application will start
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
StopTime: Time at which the application will stop
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
TraceSources
Tx: A new packet is created and is sent
Callback signature: ns3::Packet::TracedCallback
Rx: A packet has been received
Callback signature: ns3::Packet::TracedCallback
TxWithAddresses: A new packet is created and is sent
Callback signature: ns3::Packet::TwoAddressTracedCallback
RxWithAddresses: A packet has been received
Callback signature: ns3::Packet::TwoAddressTracedCallback
Size of this type is 296 bytes (on a 64-bit architecture).
Definition at line 39 of file udp-echo-client.h.
Constructor & Destructor Documentation
UdpEchoClient()
ns3::UdpEchoClient::UdpEchoClient ()
Definition at line 86 of file udp-echo-client.cc.
References m_data, m_dataSize, m_sendEvent, m_sent, m_socket, and NS_LOG_FUNCTION.
~UdpEchoClient()
ns3::UdpEchoClient::~UdpEchoClient () virtual
Definition at line 96 of file udp-echo-client.cc.
References m_data, m_dataSize, m_socket, and NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::UdpEchoClient::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Application.
Definition at line 122 of file udp-echo-client.cc.
References ns3::Application::DoDispose(), and NS_LOG_FUNCTION.
GetDataSize()
uint32_t ns3::UdpEchoClient::GetDataSize (void) const
Get the number of data bytes that will be sent to the server.
Warning
The number of bytes may be modified by calling any one of the SetFill methods. If you have called SetFill, then the number of data bytes will correspond to the size of an initialized data buffer. If you have not called a SetFill method, the number of data bytes will correspond to the number of don't care bytes that will be sent.
Returns
The number of data bytes.
Definition at line 212 of file udp-echo-client.cc.
References m_size, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::UdpEchoClient::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 39 of file udp-echo-client.cc.
References GetDataSize(), m_count, m_interval, m_peerAddress, m_peerPort, m_rxTrace, m_rxTraceWithAddresses, m_txTrace, m_txTraceWithAddresses, ns3::MakeAddressAccessor(), ns3::MakeAddressChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), ns3::Seconds(), SetDataSize(), and ns3::TypeId::SetParent().
Referenced by ns3::UdpEchoClientHelper::UdpEchoClientHelper().
HandleRead()
void ns3::UdpEchoClient::HandleRead (Ptr< Socket > socket) private
Handle a packet reception.
This function is called by lower layers.
Parameters
socket the socket the packet was received to.
Definition at line 380 of file udp-echo-client.cc.
References ns3::Inet6SocketAddress::ConvertFrom(), ns3::InetSocketAddress::ConvertFrom(), ns3::InetSocketAddress::GetIpv4(), ns3::Inet6SocketAddress::GetIpv6(), ns3::InetSocketAddress::GetPort(), ns3::Inet6SocketAddress::GetPort(), ns3::Packet::GetSize(), ns3::Socket::GetSockName(), ns3::Inet6SocketAddress::IsMatchingType(), ns3::InetSocketAddress::IsMatchingType(), m_rxTrace, m_rxTraceWithAddresses, ns3::Simulator::Now(), NS_LOG_FUNCTION, NS_LOG_INFO, ns3::Socket::RecvFrom(), and ns3::Time::S.
Referenced by StartApplication().
ScheduleTransmit()
void ns3::UdpEchoClient::ScheduleTransmit (Time dt) private
Schedule the next packet transmission.
Parameters
dt time interval between packets.
Definition at line 299 of file udp-echo-client.cc.
References m_sendEvent, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), and Send().
Referenced by Send(), and StartApplication().
Send()
void ns3::UdpEchoClient::Send (void) private
Send a packet.
Definition at line 306 of file udp-echo-client.cc.
References ns3::Inet6SocketAddress::ConvertFrom(), ns3::InetSocketAddress::ConvertFrom(), ns3::Ipv4Address::ConvertFrom(), ns3::Ipv6Address::ConvertFrom(), ns3::Socket::GetSockName(), ns3::EventId::IsExpired(), ns3::Inet6SocketAddress::IsMatchingType(), ns3::InetSocketAddress::IsMatchingType(), ns3::Ipv4Address::IsMatchingType(), ns3::Ipv6Address::IsMatchingType(), m_count, m_data, m_dataSize, m_interval, m_peerAddress, m_peerPort, m_sendEvent, m_sent, m_size, m_socket, m_txTrace, m_txTraceWithAddresses, ns3::Simulator::Now(), NS_ASSERT, NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::Time::S, ScheduleTransmit(), and ns3::Socket::Send().
Referenced by ScheduleTransmit().
SetDataSize()
void ns3::UdpEchoClient::SetDataSize (uint32_t dataSize)
Set the data size of the packet (the number of bytes that are sent as data to the server).
The contents of the data are set to unspecified (don't care) by this call.
Warning
If you have set the fill data for the echo client using one of the SetFill calls, this will undo those effects.
Parameters
dataSize The size of the echo data you want to sent.
Definition at line 196 of file udp-echo-client.cc.
References m_data, m_dataSize, m_size, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetFill() [1/3]
void ns3::UdpEchoClient::SetFill (std::string fill)
Set the data fill of the packet (what is sent as data to the server) to the zero-terminated contents of the fill string string.
Warning
The size of resulting echo packets will be automatically adjusted to reflect the size of the fill string – this means that the PacketSize attribute may be changed as a result of this call.
Parameters
fill The string to use as the actual echo data bytes.
Definition at line 219 of file udp-echo-client.cc.
References m_data, m_dataSize, m_size, and NS_LOG_FUNCTION.
SetFill() [2/3]
void ns3::UdpEchoClient::SetFill (uint8_t * fill, uint32_t fillSize, uint32_t dataSize)
Set the data fill of the packet (what is sent as data to the server) to the contents of the fill buffer, repeated as many times as is required.
Initializing the packet to the contents of a provided single buffer is accomplished by setting the fillSize set to your desired dataSize (and providing an appropriate buffer).
Warning
The size of resulting echo packets will be automatically adjusted to reflect the dataSize parameter – this means that the PacketSize attribute of the Application may be changed as a result of this call.
Parameters
fill The fill pattern to use when constructing packets.
fillSize The number of bytes in the provided fill pattern.
dataSize The desired size of the final echo data.
Definition at line 260 of file udp-echo-client.cc.
References m_data, m_dataSize, m_size, and NS_LOG_FUNCTION.
SetFill() [3/3]
void ns3::UdpEchoClient::SetFill (uint8_t fill, uint32_t dataSize)
Set the data fill of the packet (what is sent as data to the server) to the repeated contents of the fill byte.
i.e., the fill byte will be used to initialize the contents of the data packet.
Warning
The size of resulting echo packets will be automatically adjusted to reflect the dataSize parameter – this means that the PacketSize attribute may be changed as a result of this call.
Parameters
fill The byte to be repeated in constructing the packet data..
dataSize The desired size of the resulting echo packet data.
Definition at line 241 of file udp-echo-client.cc.
References m_data, m_dataSize, m_size, and NS_LOG_FUNCTION.
SetRemote() [1/2]
void ns3::UdpEchoClient::SetRemote (Address addr)
set the remote address
Parameters
addr remote address
Definition at line 115 of file udp-echo-client.cc.
References m_peerAddress, and NS_LOG_FUNCTION.
SetRemote() [2/2]
void ns3::UdpEchoClient::SetRemote (Address ip, uint16_t port)
set the remote address and port
Parameters
ip remote IP address
port remote port
Definition at line 107 of file udp-echo-client.cc.
References m_peerAddress, m_peerPort, NS_LOG_FUNCTION, and port.
StartApplication()
void ns3::UdpEchoClient::StartApplication (void) private virtual
Application specific startup code.
The StartApplication method is called at the start time specified by Start This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 129 of file udp-echo-client.cc.
References ns3::Socket::Bind(), ns3::Socket::Bind6(), ns3::Socket::Connect(), ns3::Ipv4Address::ConvertFrom(), ns3::Ipv6Address::ConvertFrom(), ns3::Socket::CreateSocket(), ns3::Application::GetNode(), HandleRead(), ns3::Inet6SocketAddress::IsMatchingType(), ns3::InetSocketAddress::IsMatchingType(), ns3::Ipv4Address::IsMatchingType(), ns3::Ipv6Address::IsMatchingType(), ns3::TypeId::LookupByName(), m_peerAddress, m_peerPort, m_socket, ns3::MakeCallback(), NS_ASSERT_MSG, NS_FATAL_ERROR, NS_LOG_FUNCTION, ScheduleTransmit(), ns3::Seconds(), ns3::Socket::SetAllowBroadcast(), and ns3::Socket::SetRecvCallback().
StopApplication()
void ns3::UdpEchoClient::StopApplication (void) private virtual
Application specific shutdown code.
The StopApplication method is called at the stop time specified by Stop This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 181 of file udp-echo-client.cc.
References ns3::Simulator::Cancel(), ns3::Socket::Close(), m_sendEvent, m_socket, ns3::MakeNullCallback(), NS_LOG_FUNCTION, and ns3::Socket::SetRecvCallback().
Member Data Documentation
m_count
uint32_t ns3::UdpEchoClient::m_count private
Maximum number of packets the application will send.
Definition at line 160 of file udp-echo-client.h.
Referenced by GetTypeId(), and Send().
m_data
uint8_t* ns3::UdpEchoClient::m_data private
packet payload data
Definition at line 165 of file udp-echo-client.h.
Referenced by UdpEchoClient(), ~UdpEchoClient(), Send(), SetDataSize(), and SetFill().
m_dataSize
uint32_t ns3::UdpEchoClient::m_dataSize private
packet payload size (must be equal to m_size)
Definition at line 164 of file udp-echo-client.h.
Referenced by UdpEchoClient(), ~UdpEchoClient(), Send(), SetDataSize(), and SetFill().
m_interval
Time ns3::UdpEchoClient::m_interval private
Packet inter-send time.
Definition at line 161 of file udp-echo-client.h.
Referenced by GetTypeId(), and Send().
m_peerAddress
Address ns3::UdpEchoClient::m_peerAddress private
Remote peer address.
Definition at line 169 of file udp-echo-client.h.
Referenced by GetTypeId(), Send(), SetRemote(), and StartApplication().
m_peerPort
uint16_t ns3::UdpEchoClient::m_peerPort private
Remote peer port.
Definition at line 170 of file udp-echo-client.h.
Referenced by GetTypeId(), Send(), SetRemote(), and StartApplication().
m_rxTrace
TracedCallback<Ptr<const Packet> > ns3::UdpEchoClient::m_rxTrace private
Callbacks for tracing the packet Rx events.
Definition at line 177 of file udp-echo-client.h.
Referenced by GetTypeId(), and HandleRead().
m_rxTraceWithAddresses
TracedCallback<Ptr<const Packet>, const Address &, const Address &> ns3::UdpEchoClient::m_rxTraceWithAddresses private
Callbacks for tracing the packet Rx events, includes source and destination addresses.
Definition at line 183 of file udp-echo-client.h.
Referenced by GetTypeId(), and HandleRead().
m_sendEvent
EventId ns3::UdpEchoClient::m_sendEvent private
Event to send the next packet.
Definition at line 171 of file udp-echo-client.h.
Referenced by UdpEchoClient(), ScheduleTransmit(), Send(), and StopApplication().
m_sent
uint32_t ns3::UdpEchoClient::m_sent private
Counter for sent packets.
Definition at line 167 of file udp-echo-client.h.
Referenced by UdpEchoClient(), and Send().
m_size
uint32_t ns3::UdpEchoClient::m_size private
Size of the sent packet.
Definition at line 162 of file udp-echo-client.h.
Referenced by GetDataSize(), Send(), SetDataSize(), and SetFill().
m_socket
Ptr<Socket> ns3::UdpEchoClient::m_socket private
Socket.
Definition at line 168 of file udp-echo-client.h.
Referenced by UdpEchoClient(), ~UdpEchoClient(), Send(), StartApplication(), and StopApplication().
m_txTrace
TracedCallback<Ptr<const Packet> > ns3::UdpEchoClient::m_txTrace private
Callbacks for tracing the packet Tx events.
Definition at line 174 of file udp-echo-client.h.
Referenced by GetTypeId(), and Send().
m_txTraceWithAddresses
TracedCallback<Ptr<const Packet>, const Address &, const Address &> ns3::UdpEchoClient::m_txTraceWithAddresses private
Callbacks for tracing the packet Tx events, includes source and destination addresses.
Definition at line 180 of file udp-echo-client.h.
Referenced by GetTypeId(), and Send().
The documentation for this class was generated from the following files:
src/applications/model/udp-echo-client.h
src/applications/model/udp-echo-client.cc