ns-3: ns3::OcbWifiMac Class Reference
ns3::OcbWifiMac Class Reference
WAVE module
STAs communicate with each directly outside the context of a BSS.
#include "ocb-wifi-mac.h"
Public Member Functions
OcbWifiMac (void)
virtual ~OcbWifiMac (void)
void AddReceiveVscCallback (OrganizationIdentifier oi, VscCallback cb)
void CancleTx (enum AcIndex ac)
void ConfigureEdca (uint32_t cwmin, uint32_t cwmax, uint32_t aifsn, enum AcIndex ac)
virtual void ConfigureStandard (enum WifiStandard standard)
void EnableForWave (Ptr< WaveNetDevice > device)
virtual void Enqueue (Ptr< Packet > packet, Mac48Address to)
virtual Mac48Address GetBssid (void) const
This method shall not be used in WAVE environment and here it will overloaded to log warn message.
virtual Ssid GetSsid (void) const
void MakeVirtualBusy (Time duration)
void RemoveReceiveVscCallback (OrganizationIdentifier oi)
void Reset (void)
To support MAC extension for multiple channel operation, Reset current MAC entity and flush its internal queues.
void Resume (void)
To support MAC extension for multiple channel operation, Resume the activity of suspended MAC entity.
void SendVsc (Ptr< Packet > vsc, Mac48Address peer, OrganizationIdentifier oi)
virtual void SetBssid (Mac48Address bssid)
virtual void SetLinkDownCallback (Callback< void > linkDown)
virtual void SetLinkUpCallback (Callback< void > linkUp)
SetLinkUpCallback and SetLinkDownCallback will be overloaded In OCB mode, stations can send packets directly whenever they want so the link is always up and never down even during channel switch.
virtual void SetSsid (Ssid ssid)
void Suspend (void)
To support MAC extension for multiple channel operation, Suspend the activity in current MAC entity.
Public Member Functions inherited from ns3::RegularWifiMac
RegularWifiMac ()
virtual ~RegularWifiMac ()
void ConfigureStandard (WifiStandard standard)
virtual void Enqueue (Ptr< Packet > packet, Mac48Address to, Mac48Address from)
Mac48Address GetAddress (void) const
Mac48Address GetBssid (void) const
ExtendedCapabilities GetExtendedCapabilities (void) const
Return the extended capabilities of the device.
HeCapabilities GetHeCapabilities (void) const
Return the HE capabilities of the device.
HtCapabilities GetHtCapabilities (void) const
Return the HT capabilities of the device.
bool GetShortSlotTimeSupported (void) const
Ssid GetSsid (void) const
VhtCapabilities GetVhtCapabilities (void) const
Return the VHT capabilities of the device.
Ptr< WifiPhy > GetWifiPhy (void) const
Ptr< WifiRemoteStationManager > GetWifiRemoteStationManager (void) const
void ResetWifiPhy (void)
Remove currently attached WifiPhy device from this MAC.
void SetAddress (Mac48Address address)
void SetBssid (Mac48Address bssid)
void SetCtsToSelfSupported (bool enable)
Enable or disable CTS-to-self feature.
void SetForwardUpCallback (ForwardUpCallback upCallback)
void SetLinkDownCallback (Callback< void > linkDown)
void SetLinkUpCallback (Callback< void > linkUp)
void SetPromisc (void)
Sets the interface in promiscuous mode.
void SetShortSlotTimeSupported (bool enable)
Enable or disable short slot time feature.
void SetSsid (Ssid ssid)
virtual void SetWifiPhy (const Ptr< WifiPhy > phy)
virtual void SetWifiRemoteStationManager (const Ptr< WifiRemoteStationManager > stationManager)
virtual bool SupportsSendFrom (void) const
Public Member Functions inherited from ns3::WifiMac
Ptr< NetDevice > GetDevice (void) const
Return the device this PHY is associated with.
Ptr< HeConfiguration > GetHeConfiguration (void) const
Ptr< HtConfiguration > GetHtConfiguration (void) const
Ptr< VhtConfiguration > GetVhtConfiguration (void) const
void NotifyPromiscRx (Ptr< const Packet > packet)
void NotifyRx (Ptr< const Packet > packet)
void NotifyRxDrop (Ptr< const Packet > packet)
void NotifyTx (Ptr< const Packet > packet)
void NotifyTxDrop (Ptr< const Packet > packet)
void SetDevice (const Ptr< NetDevice > device)
Sets the device this PHY is associated with.
virtual void SetForwardUpCallback (Callback< void, Ptr< const Packet >, Mac48Address, Mac48Address > upCallback)=0
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::RegularWifiMac
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::WifiMac
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual void Receive (Ptr< WifiMacQueueItem > mpdu)
This method acts as the MacRxMiddle receive callback and is invoked to notify us that a frame has been received.
Private Attributes
VendorSpecificContentManager m_vscManager
VSC manager.
Additional Inherited Members
Public Types inherited from ns3::RegularWifiMac
typedef Callback< void, Ptr< const Packet >, Mac48Address, Mac48Address > ForwardUpCallback
This type defines the callback of a higher layer that a WifiMac(-derived) object invokes to pass a packet up the stack.
Protected Types inherited from ns3::RegularWifiMac
typedef std::map< AcIndex, Ptr< QosTxop > > EdcaQueues
This type defines a mapping between an Access Category index, and a pointer to the corresponding channel access function.
Protected Member Functions inherited from ns3::RegularWifiMac
void ConfigureContentionWindow (uint32_t cwMin, uint32_t cwMax)
virtual void DeaggregateAmsduAndForward (Ptr< WifiMacQueueItem > mpdu)
This method can be called to de-aggregate an A-MSDU and forward the constituent packets up the stack.
virtual void DoDispose ()
Destructor implementation.
virtual void DoInitialize ()
Initialize() implementation.
void ForwardUp (Ptr< const Packet > packet, Mac48Address from, Mac48Address to)
Forward the packet up to the device.
Ptr< QosTxop > GetBEQueue (void) const
Accessor for the AC_BE channel access function.
Ptr< QosTxop > GetBKQueue (void) const
Accessor for the AC_BK channel access function.
bool GetDsssSupported () const
Return whether the device supports DSSS.
bool GetErpSupported () const
Return whether the device supports ERP.
bool GetHeSupported () const
Return whether the device supports HE.
bool GetHtSupported () const
Return whether the device supports HT.
bool GetQosSupported () const
Return whether the device supports QoS.
Ptr< Txop > GetTxop (void) const
Accessor for the DCF object.
bool GetVhtSupported () const
Return whether the device supports VHT.
Ptr< QosTxop > GetVIQueue (void) const
Accessor for the AC_VI channel access function.
Ptr< QosTxop > GetVOQueue (void) const
Accessor for the AC_VO channel access function.
void SendAddBaResponse (const MgtAddBaRequestHeader *reqHdr, Mac48Address originator)
This method can be called to accept a received ADDBA Request.
void SetDsssSupported (bool enable)
Enable or disable DSSS support for the device.
void SetErpSupported (bool enable)
Enable or disable ERP support for the device.
virtual void SetQosSupported (bool enable)
Enable or disable QoS support for the device.
void SetTypeOfStation (TypeOfStation type)
This method is invoked by a subclass to specify what type of station it is implementing.
virtual void TxFailed (const WifiMacHeader &hdr)
The packet we sent was successfully received by the receiver (i.e.
virtual void TxOk (const WifiMacHeader &hdr)
The packet we sent was successfully received by the receiver (i.e.
Protected Member Functions inherited from ns3::WifiMac
void ConfigureDcf (Ptr< Txop > dcf, uint32_t cwmin, uint32_t cwmax, bool isDsss, AcIndex ac)
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::RegularWifiMac
Ptr< ChannelAccessManager > m_channelAccessManager
channel access manager
EdcaQueues m_edca
This is a map from Access Category index to the corresponding channel access function.
ForwardUpCallback m_forwardUp
Callback to forward packet up the stack.
Callback< void > m_linkDown
Callback when a link is down.
Callback< void > m_linkUp
Callback when a link is up.
Ptr< MacLow > m_low
MacLow (RTS, CTS, Data, Ack etc.)
Ptr< WifiPhy > m_phy
Wifi PHY.
Ptr< MacRxMiddle > m_rxMiddle
RX middle (defragmentation etc.)
Ssid m_ssid
Service Set ID (SSID)
Ptr< WifiRemoteStationManager > m_stationManager
Remote station manager (rate control, RTS/CTS/fragmentation thresholds etc.)
Ptr< MacTxMiddle > m_txMiddle
TX middle (aggregation etc.)
Ptr< Txop > m_txop
This holds a pointer to the TXOP instance for this WifiMac - used for transmission of frames to non-QoS peers.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
STAs communicate with each directly outside the context of a BSS.
In OCB mac mode,synchronization, association, dis-association and authentication of normal wifi are not used for wireless access in vehicular environments.
Although Timing Advertisement frame is a specific management frame defined in 802.11p. It is mainly used by IEEE Std 1609.4 for channel switch synchronization. However in simulation nodes are supposed to have GPS synchronization ability, so we will not implement this feature.
Config Paths
ns3::OcbWifiMac is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Mac/$ns3::RegularWifiMac/$ns3::OcbWifiMac"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Mac/$ns3::OcbWifiMac"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/MacEntities/[i]"
No Attributes are defined for this type.
Attributes defined in parent class ns3::RegularWifiMac
QosSupported: This Boolean attribute is set to enable 802.11e/WMM-style QoS support at this STA.
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
CtsToSelfSupported: Use CTS to Self when using a rate that is not in the basic rate set.
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write
VO_MaxAmsduSize: Maximum length in bytes of an A-MSDU for AC_VO access class (capped to 7935 for HT PPDUs and 11398 for VHT/HE PPDUs). Value 0 means A-MSDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:11398
Initial value: 0
Flags: construct write read
VI_MaxAmsduSize: Maximum length in bytes of an A-MSDU for AC_VI access class (capped to 7935 for HT PPDUs and 11398 for VHT/HE PPDUs). Value 0 means A-MSDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:11398
Initial value: 0
Flags: construct write read
BE_MaxAmsduSize: Maximum length in bytes of an A-MSDU for AC_BE access class (capped to 7935 for HT PPDUs and 11398 for VHT/HE PPDUs). Value 0 means A-MSDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:11398
Initial value: 0
Flags: construct write read
BK_MaxAmsduSize: Maximum length in bytes of an A-MSDU for AC_BK access class (capped to 7935 for HT PPDUs and 11398 for VHT/HE PPDUs). Value 0 means A-MSDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:11398
Initial value: 0
Flags: construct write read
VO_MaxAmpduSize: Maximum length in bytes of an A-MPDU for AC_VO access class (capped to 65535 for HT PPDUs, 1048575 for VHT PPDUs, and 8388607 for HE PPDUs). Value 0 means A-MPDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 0
Flags: construct write read
VI_MaxAmpduSize: Maximum length in bytes of an A-MPDU for AC_VI access class (capped to 65535 for HT PPDUs, 1048575 for VHT PPDUs, and 8388607 for HE PPDUs). Value 0 means A-MPDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 65535
Flags: construct write read
BE_MaxAmpduSize: Maximum length in bytes of an A-MPDU for AC_BE access class (capped to 65535 for HT PPDUs, 1048575 for VHT PPDUs, and 8388607 for HE PPDUs). Value 0 means A-MPDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 65535
Flags: construct write read
BK_MaxAmpduSize: Maximum length in bytes of an A-MPDU for AC_BK access class (capped to 65535 for HT PPDUs, 1048575 for VHT PPDUs, and 8388607 for HE PPDUs). Value 0 means A-MPDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 0
Flags: construct write read
VO_BlockAckThreshold: If number of packets in VO queue reaches this value, block ack mechanism is used. If this value is 0, block ack is never used.When A-MPDU is enabled, block ack mechanism is used regardless of this value.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:64
Initial value: 0
Flags: construct write
VI_BlockAckThreshold: If number of packets in VI queue reaches this value, block ack mechanism is used. If this value is 0, block ack is never used.When A-MPDU is enabled, block ack mechanism is used regardless of this value.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:64
Initial value: 0
Flags: construct write
BE_BlockAckThreshold: If number of packets in BE queue reaches this value, block ack mechanism is used. If this value is 0, block ack is never used.When A-MPDU is enabled, block ack mechanism is used regardless of this value.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:64
Initial value: 0
Flags: construct write
BK_BlockAckThreshold: If number of packets in BK queue reaches this value, block ack mechanism is used. If this value is 0, block ack is never used.When A-MPDU is enabled, block ack mechanism is used regardless of this value.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:64
Initial value: 0
Flags: construct write
VO_BlockAckInactivityTimeout: Represents max time (blocks of 1024 microseconds) allowed for block ackinactivity for AC_VO. If this value isn't equal to 0 a timer start after that ablock ack setup is completed and will be reset every time that a block ackframe is received. If this value is 0, block ack inactivity timeout won't be used.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 0
Flags: construct write
VI_BlockAckInactivityTimeout: Represents max time (blocks of 1024 microseconds) allowed for block ackinactivity for AC_VI. If this value isn't equal to 0 a timer start after that ablock ack setup is completed and will be reset every time that a block ackframe is received. If this value is 0, block ack inactivity timeout won't be used.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 0
Flags: construct write
BE_BlockAckInactivityTimeout: Represents max time (blocks of 1024 microseconds) allowed for block ackinactivity for AC_BE. If this value isn't equal to 0 a timer start after that ablock ack setup is completed and will be reset every time that a block ackframe is received. If this value is 0, block ack inactivity timeout won't be used.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 0
Flags: construct write
BK_BlockAckInactivityTimeout: Represents max time (blocks of 1024 microseconds) allowed for block ackinactivity for AC_BK. If this value isn't equal to 0 a timer start after that ablock ack setup is completed and will be reset every time that a block ackframe is received. If this value is 0, block ack inactivity timeout won't be used.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 0
Flags: construct write
ShortSlotTimeSupported: Whether or not short slot time is supported (only used by ERP APs or STAs).
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
Txop: The Txop object.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::Txop>
Flags: read
VO_Txop: Queue that manages packets belonging to AC_VO access class.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::QosTxop>
Flags: read
VI_Txop: Queue that manages packets belonging to AC_VI access class.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::QosTxop>
Flags: read
BE_Txop: Queue that manages packets belonging to AC_BE access class.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::QosTxop>
Flags: read
BK_Txop: Queue that manages packets belonging to AC_BK access class.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::QosTxop>
Flags: read
Attributes defined in parent class ns3::WifiMac
Ssid: The ssid we want to belong to.
Set with class: SsidValue
Underlying type: Ssid
Initial value: default
Flags: construct write read
No TraceSources are defined for this type.
TraceSources defined in parent class ns3::RegularWifiMac
TxOkHeader: The header of successfully transmitted packet.
Callback signature: ns3::WifiMacHeader::TracedCallback
TxErrHeader: The header of unsuccessfully transmitted packet.
Callback signature: ns3::WifiMacHeader::TracedCallback
TraceSources defined in parent class ns3::WifiMac
MacTx: A packet has been received from higher layers and is being processed in preparation for queueing for transmission.
Callback signature: ns3::Packet::TracedCallback
MacTxDrop: A packet has been dropped in the MAC layer before transmission.
Callback signature: ns3::Packet::TracedCallback
MacPromiscRx: A packet has been received by this device, has been passed up from the physical layer and is being forwarded up the local protocol stack. This is a promiscuous trace.
Callback signature: ns3::Packet::TracedCallback
MacRx: A packet has been received by this device, has been passed up from the physical layer and is being forwarded up the local protocol stack. This is a non-promiscuous trace.
Callback signature: ns3::Packet::TracedCallback
MacRxDrop: A packet has been dropped in the MAC layer after it has been passed up from the physical layer.
Callback signature: ns3::Packet::TracedCallback
Size of this type is 432 bytes (on a 64-bit architecture).
Definition at line 49 of file ocb-wifi-mac.h.
Constructor & Destructor Documentation
OcbWifiMac()
ns3::OcbWifiMac::OcbWifiMac (void)
Definition at line 55 of file ocb-wifi-mac.cc.
References NS_LOG_FUNCTION, ns3::OCB, ns3::RegularWifiMac::SetBssid(), ns3::RegularWifiMac::SetTypeOfStation(), and ns3::WILDCARD_BSSID.
~OcbWifiMac()
ns3::OcbWifiMac::~OcbWifiMac (void) virtual
Definition at line 64 of file ocb-wifi-mac.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddReceiveVscCallback()
void ns3::OcbWifiMac::AddReceiveVscCallback (OrganizationIdentifier oi, VscCallback cb)
Parameters
oi Organization Identifier
cb callback to invoke whenever a vender specific action frame has been received and must be forwarded to the higher layers. every node shall register first if it wants to receive specific vendor specific content.
Definition at line 97 of file ocb-wifi-mac.cc.
References m_vscManager, NS_LOG_FUNCTION, and ns3::VendorSpecificContentManager::RegisterVscCallback().
CancleTx()
void ns3::OcbWifiMac::CancleTx (enum AcIndex ac)
Parameters
ac the specified access category
To support MAC extension for multiple channel operation, Cancel transmit operation for internal queue associated with a specified Access Category.
Definition at line 420 of file ocb-wifi-mac.cc.
References ns3::RegularWifiMac::m_edca, ns3::Txop::NotifyChannelSwitching(), NS_ASSERT, and NS_LOG_FUNCTION.
ConfigureEdca()
void ns3::OcbWifiMac::ConfigureEdca (uint32_t cwmin, uint32_t cwmax, uint32_t aifsn, enum AcIndex ac)
Parameters
cwmin the min contention window
cwmax the max contention window
aifsn the arbitration inter-frame space
ac the access category index
configure EDCA queue parameters
Definition at line 331 of file ocb-wifi-mac.cc.
References ns3::AC_BE, ns3::AC_BE_NQOS, ns3::AC_BK, ns3::AC_UNDEF, ns3::AC_VI, ns3::AC_VO, ns3::RegularWifiMac::GetBEQueue(), ns3::RegularWifiMac::GetBKQueue(), ns3::RegularWifiMac::GetTxop(), ns3::RegularWifiMac::GetVIQueue(), ns3::RegularWifiMac::GetVOQueue(), NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::Txop::SetAifsn(), ns3::Txop::SetMaxCw(), and ns3::Txop::SetMinCw().
Referenced by ConfigureStandard().
ConfigureStandard()
void ns3::OcbWifiMac::ConfigureStandard (enum WifiStandard standard) virtual
Parameters
standard the wifi standard to be configured
This method completes the configuration process for a requested PHY standard. Subclasses should implement this method to configure their DCF queues according to the requested standard.
Implements ns3::WifiMac.
Definition at line 374 of file ocb-wifi-mac.cc.
References ns3::AC_BE, ns3::AC_BE_NQOS, ns3::AC_BK, ns3::AC_VI, ns3::AC_VO, ConfigureEdca(), NS_ASSERT, NS_LOG_FUNCTION, and ns3::WIFI_STANDARD_80211p.
Referenced by ns3::WaveHelper::Install().
EnableForWave()
void ns3::OcbWifiMac::EnableForWave (Ptr< WaveNetDevice > device)
Parameters
device make current MAC entity associated with WaveNetDevice
To support MAC extension for multiple channel operation, WaveMacLow object will be used to replace original MacLow object.
Definition at line 439 of file ocb-wifi-mac.cc.
References ns3::RegularWifiMac::m_channelAccessManager, ns3::RegularWifiMac::m_edca, ns3::RegularWifiMac::m_low, ns3::RegularWifiMac::m_rxMiddle, ns3::RegularWifiMac::m_txop, ns3::MakeCallback(), NS_LOG_FUNCTION, ns3::MacRxMiddle::Receive(), ns3::Txop::SetMacLow(), and ns3::ChannelAccessManager::SetupLow().
Referenced by ns3::WaveHelper::Install().
Enqueue()
void ns3::OcbWifiMac::Enqueue (Ptr< Packet > packet, Mac48Address to) virtual
Parameters
packet the packet to send.
to the address to which the packet should be sent.
The packet should be enqueued in a tx queue, and should be dequeued as soon as the channel access function determines that access is granted to this MAC.
Implements ns3::RegularWifiMac.
Definition at line 159 of file ocb-wifi-mac.cc.
References ns3::WifiRemoteStationManager::AddAllSupportedMcs(), ns3::WifiRemoteStationManager::AddAllSupportedModes(), ns3::WifiRemoteStationManager::AddStationHtCapabilities(), ns3::WifiRemoteStationManager::AddStationVhtCapabilities(), ns3::RegularWifiMac::GetAddress(), ns3::RegularWifiMac::GetHtCapabilities(), ns3::RegularWifiMac::GetHtSupported(), ns3::RegularWifiMac::GetQosSupported(), ns3::RegularWifiMac::GetVhtCapabilities(), ns3::RegularWifiMac::GetVhtSupported(), ns3::WifiRemoteStationManager::IsBrandNew(), ns3::RegularWifiMac::m_edca, ns3::RegularWifiMac::m_stationManager, ns3::RegularWifiMac::m_txop, ns3::WifiMacHeader::NORMAL_ACK, NS_ASSERT, NS_LOG_FUNCTION, ns3::QosUtilsGetTidForPacket(), ns3::QosUtilsMapTidToAc(), ns3::Txop::Queue(), ns3::WifiRemoteStationManager::RecordDisassociated(), ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetAddr2(), ns3::WifiMacHeader::SetAddr3(), ns3::WifiMacHeader::SetDsNotFrom(), ns3::WifiMacHeader::SetDsNotTo(), ns3::WifiMacHeader::SetNoOrder(), ns3::WifiMacHeader::SetQosAckPolicy(), ns3::WifiMacHeader::SetQosNoAmsdu(), ns3::WifiMacHeader::SetQosNoEosp(), ns3::WifiMacHeader::SetQosTid(), ns3::WifiMacHeader::SetQosTxopLimit(), ns3::WifiMacHeader::SetType(), ns3::WIFI_MAC_DATA, ns3::WIFI_MAC_QOSDATA, and ns3::WILDCARD_BSSID.
GetBssid()
Mac48Address ns3::OcbWifiMac::GetBssid (void) const virtual
This method shall not be used in WAVE environment and here it will overloaded to log warn message.
Implements ns3::WifiMac.
Definition at line 132 of file ocb-wifi-mac.cc.
References NS_LOG_WARN, and ns3::WILDCARD_BSSID.
GetSsid()
Ssid ns3::OcbWifiMac::GetSsid (void) const virtual
Returns
the ssid which this MAC layer is going to try to stay in.
This method shall not be used in WAVE environment and here it will overloaded to log warn message
Implements ns3::WifiMac.
Definition at line 117 of file ocb-wifi-mac.cc.
References ns3::RegularWifiMac::GetSsid(), and NS_LOG_WARN.
GetTypeId()
TypeId ns3::OcbWifiMac::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 45 of file ocb-wifi-mac.cc.
References ns3::TypeId::SetParent().
MakeVirtualBusy()
void ns3::OcbWifiMac::MakeVirtualBusy (Time duration)
Parameters
duration the virtual busy time for MAC entity
To support MAC extension for multiple channel operation, Notify MAC entity busy for some time to prevent transmission
Definition at line 413 of file ocb-wifi-mac.cc.
References ns3::RegularWifiMac::m_channelAccessManager, ns3::ChannelAccessManager::NotifyMaybeCcaBusyStartNow(), and NS_LOG_FUNCTION.
Referenced by ns3::DefaultChannelScheduler::AssignDefaultCchAccess(), and ns3::DefaultChannelScheduler::SwitchToNextChannel().
Receive()
void ns3::OcbWifiMac::Receive (Ptr< WifiMacQueueItem > mpdu) private virtual
This method acts as the MacRxMiddle receive callback and is invoked to notify us that a frame has been received.
The implementation is intended to capture logic that is going to be common to all (or most) derived classes. Specifically, handling of Block Ack management frames is dealt with here.
This method will need, however, to be overridden by derived classes so that they can perform their data handling before invoking the base version.
Parameters
mpdu the MPDU that has been received.
Reimplemented from ns3::RegularWifiMac.
Definition at line 241 of file ocb-wifi-mac.cc.
References ns3::WifiRemoteStationManager::AddAllSupportedMcs(), ns3::WifiRemoteStationManager::AddAllSupportedModes(), ns3::WifiRemoteStationManager::AddStationHtCapabilities(), ns3::WifiRemoteStationManager::AddStationVhtCapabilities(), ns3::CATEGORY_OF_VSA, ns3::RegularWifiMac::DeaggregateAmsduAndForward(), ns3::VendorSpecificContentManager::FindVscCallback(), ns3::RegularWifiMac::ForwardUp(), ns3::WifiMacHeader::GetAddr1(), ns3::WifiMacHeader::GetAddr2(), ns3::WifiMacHeader::GetAddr3(), ns3::RegularWifiMac::GetAddress(), ns3::VendorSpecificActionHeader::GetCategory(), ns3::RegularWifiMac::GetHtCapabilities(), ns3::RegularWifiMac::GetHtSupported(), ns3::VendorSpecificActionHeader::GetOrganizationIdentifier(), ns3::RegularWifiMac::GetVhtCapabilities(), ns3::RegularWifiMac::GetVhtSupported(), ns3::WifiMacHeader::IsAction(), ns3::WifiRemoteStationManager::IsBrandNew(), ns3::WifiMacHeader::IsCtl(), ns3::WifiMacHeader::IsData(), ns3::Mac48Address::IsGroup(), ns3::WifiMacHeader::IsMgt(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), ns3::WifiMacHeader::IsQosAmsdu(), ns3::WifiMacHeader::IsQosData(), ns3::RegularWifiMac::m_stationManager, m_vscManager, ns3::WifiMac::NotifyRxDrop(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Packet::PeekHeader(), ns3::RegularWifiMac::Receive(), ns3::WifiRemoteStationManager::RecordDisassociated(), ns3::Packet::RemoveHeader(), and ns3::WILDCARD_BSSID.
RemoveReceiveVscCallback()
void ns3::OcbWifiMac::RemoveReceiveVscCallback (OrganizationIdentifier oi)
Parameters
oi Organization Identifier
Definition at line 104 of file ocb-wifi-mac.cc.
References ns3::VendorSpecificContentManager::DeregisterVscCallback(), m_vscManager, and NS_LOG_FUNCTION.
Reset()
void ns3::OcbWifiMac::Reset (void)
To support MAC extension for multiple channel operation, Reset current MAC entity and flush its internal queues.
Definition at line 430 of file ocb-wifi-mac.cc.
References ns3::RegularWifiMac::m_channelAccessManager, ns3::RegularWifiMac::m_low, ns3::ChannelAccessManager::NotifySwitchingStartNow(), and NS_LOG_FUNCTION.
Resume()
void ns3::OcbWifiMac::Resume (void)
To support MAC extension for multiple channel operation, Resume the activity of suspended MAC entity.
Definition at line 405 of file ocb-wifi-mac.cc.
References ns3::RegularWifiMac::m_channelAccessManager, ns3::ChannelAccessManager::NotifyWakeupNow(), and NS_LOG_FUNCTION.
Referenced by ns3::DefaultChannelScheduler::AssignDefaultCchAccess(), and ns3::DefaultChannelScheduler::SwitchToNextChannel().
SendVsc()
void ns3::OcbWifiMac::SendVsc (Ptr< Packet > vsc, Mac48Address peer, OrganizationIdentifier oi)
Parameters
vsc management packet to send.
peer the address to which the packet should be sent.
oi Organization Identifier field see 7.3.1.31 Organization Identifier field and 10.3.29 Vendor-specific action
management information can be transmitted over vender specific action frame. This will be mainly called by IEEE Std 1609.4 to send WSA from IEEE Std 1609.3
Definition at line 70 of file ocb-wifi-mac.cc.
References ns3::Packet::AddHeader(), ns3::RegularWifiMac::GetAddress(), ns3::RegularWifiMac::GetQosSupported(), ns3::RegularWifiMac::m_edca, ns3::RegularWifiMac::m_txop, NS_LOG_FUNCTION, ns3::QosUtilsGetTidForPacket(), ns3::QosUtilsMapTidToAc(), ns3::Txop::Queue(), ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetAddr2(), ns3::WifiMacHeader::SetAddr3(), ns3::WifiMacHeader::SetDsNotFrom(), ns3::WifiMacHeader::SetDsNotTo(), ns3::VendorSpecificActionHeader::SetOrganizationIdentifier(), ns3::WifiMacHeader::SetType(), ns3::WIFI_MAC_MGT_ACTION, and ns3::WILDCARD_BSSID.
SetBssid()
void ns3::OcbWifiMac::SetBssid (Mac48Address bssid) virtual
Parameters
bssid the BSSID of the network that this device belongs to. This method shall not be used in WAVE environment and here it will overloaded to log warn message
Definition at line 126 of file ocb-wifi-mac.cc.
References NS_LOG_WARN.
SetLinkDownCallback()
void ns3::OcbWifiMac::SetLinkDownCallback (Callback< void > linkDown) virtual
Parameters
linkDown the callback to invoke when the link becomes down.
Implements ns3::WifiMac.
Definition at line 151 of file ocb-wifi-mac.cc.
References NS_LOG_FUNCTION, NS_LOG_WARN, and ns3::RegularWifiMac::SetLinkDownCallback().
SetLinkUpCallback()
void ns3::OcbWifiMac::SetLinkUpCallback (Callback< void > linkUp) virtual
SetLinkUpCallback and SetLinkDownCallback will be overloaded In OCB mode, stations can send packets directly whenever they want so the link is always up and never down even during channel switch.
Parameters
linkUp the callback to invoke when the link becomes up.
Implements ns3::WifiMac.
Definition at line 139 of file ocb-wifi-mac.cc.
References NS_LOG_FUNCTION, and ns3::RegularWifiMac::SetLinkUpCallback().
SetSsid()
void ns3::OcbWifiMac::SetSsid (Ssid ssid) virtual
Parameters
ssid the current ssid of this MAC layer.
This method shall not be used in WAVE environment and here it will overloaded to log warn message
Implements ns3::WifiMac.
Definition at line 111 of file ocb-wifi-mac.cc.
References NS_LOG_WARN.
Suspend()
void ns3::OcbWifiMac::Suspend (void)
To support MAC extension for multiple channel operation, Suspend the activity in current MAC entity.
Definition at line 397 of file ocb-wifi-mac.cc.
References ns3::RegularWifiMac::m_channelAccessManager, ns3::RegularWifiMac::m_low, ns3::ChannelAccessManager::NotifySleepNow(), and NS_LOG_FUNCTION.
Referenced by ns3::DefaultChannelScheduler::SwitchToNextChannel().
Member Data Documentation
m_vscManager
VendorSpecificContentManager ns3::OcbWifiMac::m_vscManager private
VSC manager.
Definition at line 181 of file ocb-wifi-mac.h.
Referenced by AddReceiveVscCallback(), Receive(), and RemoveReceiveVscCallback().
The documentation for this class was generated from the following files:
src/wave/model/ocb-wifi-mac.h
src/wave/model/ocb-wifi-mac.cc