ns-3: ns3::AsciiTraceHelperForIpv4 Class Reference
ns3::AsciiTraceHelperForIpv4 Class Reference abstract
Internet » IPv4 Helper classes
Base class providing common user-level ascii trace operations for helpers representing IPv4 protocols .
#include "internet-trace-helper.h"
Public Member Functions
AsciiTraceHelperForIpv4 ()
Construct an AsciiTraceHelperForIpv4.
virtual ~AsciiTraceHelperForIpv4 ()
Destroy an AsciiTraceHelperForIpv4.
void EnableAsciiIpv4 (Ptr< OutputStreamWrapper > stream, Ipv4InterfaceContainer c)
Enable ascii trace output on each device in the container which is of the appropriate type.
void EnableAsciiIpv4 (Ptr< OutputStreamWrapper > stream, NodeContainer n)
Enable ascii trace output on all Ipv4 and interface pairs existing in the nodes provided in the container.
void EnableAsciiIpv4 (Ptr< OutputStreamWrapper > stream, Ptr< Ipv4 > ipv4, uint32_t interface)
Enable ascii trace output on the indicated Ipv4 and interface pair.
void EnableAsciiIpv4 (Ptr< OutputStreamWrapper > stream, std::string ipv4Name, uint32_t interface)
Enable ascii trace output the indicated net device using a device previously named using the ns-3 object name service.
void EnableAsciiIpv4 (Ptr< OutputStreamWrapper > stream, uint32_t nodeid, uint32_t interface, bool explicitFilename)
Enable ascii trace output on the Ipv4 and interface pair specified by a global node-id (of a previously created node) and interface.
void EnableAsciiIpv4 (std::string prefix, Ipv4InterfaceContainer c)
Enable ascii trace output on each Ipv4 and interface pair in the container.
void EnableAsciiIpv4 (std::string prefix, NodeContainer n)
Enable ascii trace output on all Ipv4 and interface pairs existing in the nodes provided in the container.
void EnableAsciiIpv4 (std::string prefix, Ptr< Ipv4 > ipv4, uint32_t interface, bool explicitFilename=false)
Enable ascii trace output on the indicated Ipv4 and interface pair.
void EnableAsciiIpv4 (std::string prefix, std::string ipv4Name, uint32_t interface, bool explicitFilename=false)
Enable ascii trace output the indicated Ipv4 and interface pair using an Ipv4 previously named using the ns-3 object name service.
void EnableAsciiIpv4 (std::string prefix, uint32_t nodeid, uint32_t deviceid, bool explicitFilename)
Enable ascii trace output on the Ipv4 and interface pair specified by a global node-id (of a previously created node) and interface.
void EnableAsciiIpv4All (Ptr< OutputStreamWrapper > stream)
Enable ascii trace output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
void EnableAsciiIpv4All (std::string prefix)
Enable ascii trace output on all Ipv4 and interface pairs existing in the set of all nodes created in the simulation.
virtual void EnableAsciiIpv4Internal (Ptr< OutputStreamWrapper > stream, std::string prefix, Ptr< Ipv4 > ipv4, uint32_t interface, bool explicitFilename)=0
Enable ascii trace output on the indicated Ipv4 and interface pair.
Private Member Functions
void EnableAsciiIpv4Impl (Ptr< OutputStreamWrapper > stream, std::string prefix, Ipv4InterfaceContainer c)
Enable ascii trace output on the Ipv4 and interface pair specified by a global node-id (of a previously created node) and interface.
void EnableAsciiIpv4Impl (Ptr< OutputStreamWrapper > stream, std::string prefix, NodeContainer n)
Enable ascii trace output on the Ipv4 and interface pair specified by a global node-id (of a previously created node) and interface.
void EnableAsciiIpv4Impl (Ptr< OutputStreamWrapper > stream, std::string prefix, Ptr< Ipv4 > ipv4, uint32_t interface, bool explicitFilename)
Enable ascii trace output on the Ipv4 and interface pair specified by a global node-id (of a previously created node) and interface.
void EnableAsciiIpv4Impl (Ptr< OutputStreamWrapper > stream, std::string prefix, std::string ipv4Name, uint32_t interface, bool explicitFilename)
Enable ascii trace output on the Ipv4 and interface pair specified by a global node-id (of a previously created node) and interface.
void EnableAsciiIpv4Impl (Ptr< OutputStreamWrapper > stream, std::string prefix, uint32_t nodeid, uint32_t interface, bool explicitFilename)
Enable ascii trace output on the Ipv4 and interface pair specified by a global node-id (of a previously created node) and interface.
Detailed Description
Base class providing common user-level ascii trace operations for helpers representing IPv4 protocols .
Definition at line 130 of file internet-trace-helper.h.
Constructor & Destructor Documentation
AsciiTraceHelperForIpv4()
ns3::AsciiTraceHelperForIpv4::AsciiTraceHelperForIpv4 () inline
Construct an AsciiTraceHelperForIpv4.
Definition at line 136 of file internet-trace-helper.h.
~AsciiTraceHelperForIpv4()
virtual ns3::AsciiTraceHelperForIpv4::~AsciiTraceHelperForIpv4 () inline virtual
Destroy an AsciiTraceHelperForIpv4.
Definition at line 141 of file internet-trace-helper.h.
Member Function Documentation
EnableAsciiIpv4() [1/10]
void ns3::AsciiTraceHelperForIpv4::EnableAsciiIpv4 (Ptr< OutputStreamWrapper > stream, Ipv4InterfaceContainer c)
Enable ascii trace output on each device in the container which is of the appropriate type.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
c Ipv4InterfaceContainer of Ipv4 and interface pairs on which to enable tracing.
Definition at line 174 of file internet-trace-helper.cc.
References EnableAsciiIpv4Impl().
EnableAsciiIpv4() [2/10]
void ns3::AsciiTraceHelperForIpv4::EnableAsciiIpv4 (Ptr< OutputStreamWrapper > stream, NodeContainer n)
Enable ascii trace output on all Ipv4 and interface pairs existing in the nodes provided in the container.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
n container of nodes.
Definition at line 205 of file internet-trace-helper.cc.
References EnableAsciiIpv4Impl(), and sample-rng-plot::n.
EnableAsciiIpv4() [3/10]
void ns3::AsciiTraceHelperForIpv4::EnableAsciiIpv4 (Ptr< OutputStreamWrapper > stream, Ptr< Ipv4 > ipv4, uint32_t interface)
Enable ascii trace output on the indicated Ipv4 and interface pair.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
ipv4 Ptr<Ipv4> on which you want to enable tracing.
interface The interface on which you want to enable tracing.
Definition at line 119 of file internet-trace-helper.cc.
References EnableAsciiIpv4Internal().
EnableAsciiIpv4() [4/10]
void ns3::AsciiTraceHelperForIpv4::EnableAsciiIpv4 (Ptr< OutputStreamWrapper > stream, std::string ipv4Name, uint32_t interface)
Enable ascii trace output the indicated net device using a device previously named using the ns-3 object name service.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
ipv4Name The name of the Ipv4 on which you want to enable tracing.
interface The interface on which you want to enable tracing.
Definition at line 141 of file internet-trace-helper.cc.
References EnableAsciiIpv4Impl().
EnableAsciiIpv4() [5/10]
void ns3::AsciiTraceHelperForIpv4::EnableAsciiIpv4 (Ptr< OutputStreamWrapper > stream, uint32_t nodeid, uint32_t interface, bool explicitFilename)
Enable ascii trace output on the Ipv4 and interface pair specified by a global node-id (of a previously created node) and interface.
Since there can be only one Ipv4 aggregated to a node, the node-id unambiguously determines the Ipv4.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
nodeid The node identifier/number of the node on which to enable ascii tracing
interface The interface on which you want to enable tracing.
explicitFilename Treat the prefix as an explicit filename if true
Definition at line 252 of file internet-trace-helper.cc.
References EnableAsciiIpv4Impl().
EnableAsciiIpv4() [6/10]
void ns3::AsciiTraceHelperForIpv4::EnableAsciiIpv4 (std::string prefix, Ipv4InterfaceContainer c)
Enable ascii trace output on each Ipv4 and interface pair in the container.
Parameters
prefix Filename prefix to use for ascii files.
c Ipv4InterfaceContainer of Ipv4 and interface pairs on which to enable tracing.
Definition at line 165 of file internet-trace-helper.cc.
References EnableAsciiIpv4Impl().
EnableAsciiIpv4() [7/10]
void ns3::AsciiTraceHelperForIpv4::EnableAsciiIpv4 (std::string prefix, NodeContainer n)
Enable ascii trace output on all Ipv4 and interface pairs existing in the nodes provided in the container.
Parameters
prefix Filename prefix to use for ascii files.
n container of nodes.
Definition at line 196 of file internet-trace-helper.cc.
References EnableAsciiIpv4Impl(), and sample-rng-plot::n.
EnableAsciiIpv4() [8/10]
void ns3::AsciiTraceHelperForIpv4::EnableAsciiIpv4 (std::string prefix, Ptr< Ipv4 > ipv4, uint32_t interface, bool explicitFilename = false)
Enable ascii trace output on the indicated Ipv4 and interface pair.
Parameters
prefix Filename prefix to use for ascii files.
ipv4 Ptr<Ipv4> on which you want to enable tracing.
interface The interface on which you want to enable tracing.
explicitFilename Treat the prefix as an explicit filename if true.
Definition at line 110 of file internet-trace-helper.cc.
References EnableAsciiIpv4Internal().
EnableAsciiIpv4() [9/10]
void ns3::AsciiTraceHelperForIpv4::EnableAsciiIpv4 (std::string prefix, std::string ipv4Name, uint32_t interface, bool explicitFilename = false)
Enable ascii trace output the indicated Ipv4 and interface pair using an Ipv4 previously named using the ns-3 object name service.
Parameters
prefix filename prefix to use for ascii files.
ipv4Name The name of the Ipv4 on which you want to enable tracing.
interface The interface on which you want to enable tracing.
explicitFilename Treat the prefix as an explicit filename if true.
Definition at line 128 of file internet-trace-helper.cc.
References EnableAsciiIpv4Impl().
EnableAsciiIpv4() [10/10]
void ns3::AsciiTraceHelperForIpv4::EnableAsciiIpv4 (std::string prefix, uint32_t nodeid, uint32_t deviceid, bool explicitFilename)
Enable ascii trace output on the Ipv4 and interface pair specified by a global node-id (of a previously created node) and interface.
Since there can be only one Ipv4 aggregated to a node, the node-id unambiguously determines the Ipv4.
Parameters
prefix Filename prefix to use when creating ascii trace files
nodeid The node identifier/number of the node on which to enable ascii tracing
deviceid The device identifier/index of the device on which to enable ascii tracing
explicitFilename Treat the prefix as an explicit filename if true
Definition at line 265 of file internet-trace-helper.cc.
References EnableAsciiIpv4Impl().
EnableAsciiIpv4All() [1/2]
void ns3::AsciiTraceHelperForIpv4::EnableAsciiIpv4All (Ptr< OutputStreamWrapper > stream)
Enable ascii trace output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
Definition at line 243 of file internet-trace-helper.cc.
References EnableAsciiIpv4Impl(), and ns3::NodeContainer::GetGlobal().
EnableAsciiIpv4All() [2/2]
void ns3::AsciiTraceHelperForIpv4::EnableAsciiIpv4All (std::string prefix)
Enable ascii trace output on all Ipv4 and interface pairs existing in the set of all nodes created in the simulation.
Parameters
prefix Filename prefix to use for ascii files.
Definition at line 234 of file internet-trace-helper.cc.
References EnableAsciiIpv4Impl(), and ns3::NodeContainer::GetGlobal().
EnableAsciiIpv4Impl() [1/5]
void ns3::AsciiTraceHelperForIpv4::EnableAsciiIpv4Impl (Ptr< OutputStreamWrapper > stream, std::string prefix, Ipv4InterfaceContainer c) private
Enable ascii trace output on the Ipv4 and interface pair specified by a global node-id (of a previously created node) and interface.
Since there can be only one Ipv4 aggregated to a node, the node-id unambiguously determines the Ipv4.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
prefix Filename prefix to use when creating ascii trace files
c Ipv4InterfaceContainer of Ipv4 and interface pairs
Definition at line 183 of file internet-trace-helper.cc.
References ns3::Ipv4InterfaceContainer::Begin(), EnableAsciiIpv4Internal(), and ns3::Ipv4InterfaceContainer::End().
EnableAsciiIpv4Impl() [2/5]
void ns3::AsciiTraceHelperForIpv4::EnableAsciiIpv4Impl (Ptr< OutputStreamWrapper > stream, std::string prefix, NodeContainer n) private
Enable ascii trace output on the Ipv4 and interface pair specified by a global node-id (of a previously created node) and interface.
Since there can be only one Ipv4 aggregated to a node, the node-id unambiguously determines the Ipv4.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
prefix Filename prefix to use when creating ascii trace files
n container of nodes.
Definition at line 214 of file internet-trace-helper.cc.
References EnableAsciiIpv4Internal(), ns3::Object::GetObject(), and sample-rng-plot::n.
EnableAsciiIpv4Impl() [3/5]
void ns3::AsciiTraceHelperForIpv4::EnableAsciiIpv4Impl (Ptr< OutputStreamWrapper > stream, std::string prefix, Ptr< Ipv4 > ipv4, uint32_t interface, bool explicitFilename) private
Enable ascii trace output on the Ipv4 and interface pair specified by a global node-id (of a previously created node) and interface.
Since there can be only one Ipv4 aggregated to a node, the node-id unambiguously determines the Ipv4.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
prefix Filename prefix to use when creating ascii trace files
ipv4 Ptr<Ipv4> on which you want to enable tracing.
interface The device identifier/index of the device on which to enable ascii tracing
explicitFilename Treat the prefix as an explicit filename if true.
EnableAsciiIpv4Impl() [4/5]
void ns3::AsciiTraceHelperForIpv4::EnableAsciiIpv4Impl (Ptr< OutputStreamWrapper > stream, std::string prefix, std::string ipv4Name, uint32_t interface, bool explicitFilename) private
Enable ascii trace output on the Ipv4 and interface pair specified by a global node-id (of a previously created node) and interface.
Since there can be only one Ipv4 aggregated to a node, the node-id unambiguously determines the Ipv4.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
prefix Filename prefix to use when creating ascii trace files
ipv4Name Name of the Ptr<Ipv4> on which you want to enable tracing.
interface The device identifier/index of the device on which to enable ascii tracing
explicitFilename Treat the prefix as an explicit filename if true.
Definition at line 150 of file internet-trace-helper.cc.
References EnableAsciiIpv4Internal().
EnableAsciiIpv4Impl() [5/5]
void ns3::AsciiTraceHelperForIpv4::EnableAsciiIpv4Impl (Ptr< OutputStreamWrapper > stream, std::string prefix, uint32_t nodeid, uint32_t interface, bool explicitFilename) private
Enable ascii trace output on the Ipv4 and interface pair specified by a global node-id (of a previously created node) and interface.
Since there can be only one Ipv4 aggregated to a node, the node-id unambiguously determines the Ipv4.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
prefix Filename prefix to use when creating ascii trace files
nodeid The node identifier/number of the node on which to enable ascii tracing
interface The device identifier/index of the device on which to enable ascii tracing
explicitFilename Treat the prefix as an explicit filename if true.
Definition at line 274 of file internet-trace-helper.cc.
References EnableAsciiIpv4Internal(), ns3::NodeContainer::GetGlobal(), ns3::Node::GetId(), ns3::Object::GetObject(), and sample-rng-plot::n.
Referenced by EnableAsciiIpv4(), and EnableAsciiIpv4All().
EnableAsciiIpv4Internal()
virtual void ns3::AsciiTraceHelperForIpv4::EnableAsciiIpv4Internal (Ptr< OutputStreamWrapper > stream, std::string prefix, Ptr< Ipv4 > ipv4, uint32_t interface, bool explicitFilename) pure virtual
Enable ascii trace output on the indicated Ipv4 and interface pair.
The implementation is expected to use a provided Ptr<OutputStreamWrapper> if it is non-null. If the OutputStreamWrapper is null, the implementation is expected to use a provided prefix to construct a new file name for each net device using the rules described in the class overview.
If the prefix is provided, there will be one file per Ipv4 and interface pair created. In this case, adding a trace context to the file would be pointless, so the helper implementation is expected to TraceConnectWithoutContext.
If the output stream object is provided, there may be many different Ipv4 and interface pairs writing to a single file. In this case, the trace context could be important, so the helper implementation is expected to TraceConnect.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
prefix Filename prefix to use for ascii trace files.
ipv4 Ptr<Ipv4> on which you want to enable tracing.
interface The interface on which you want to enable tracing.
explicitFilename Treat the prefix as an explicit filename if true.
Implemented in ns3::InternetStackHelper.
Referenced by EnableAsciiIpv4(), and EnableAsciiIpv4Impl().
The documentation for this class was generated from the following files:
src/internet/helper/internet-trace-helper.h
src/internet/helper/internet-trace-helper.cc