ns-3: ns3::Queue< Item > Class Template Reference
ns3::Queue< Item > Class Template Reference abstract
Network » Queue
Template class for packet Queues.
#include "queue.h"
Public Types
typedef Item ItemType
Define ItemType as the type of the stored elements.
Public Member Functions
Queue ()
virtual ~Queue ()
virtual Ptr< Item > Dequeue (void)=0
Remove an item from the Queue (each subclass defines the position), counting it as dequeued.
virtual bool Enqueue (Ptr< Item > item)=0
Place an item into the Queue (each subclass defines the position)
void Flush (void)
Flush the queue.
virtual Ptr< const Item > Peek (void) const =0
Get a copy of an item in the queue (each subclass defines the position) without removing it.
virtual Ptr< Item > Remove (void)=0
Remove an item from the Queue (each subclass defines the position), counting it as dropped.
Public Member Functions inherited from ns3::QueueBase
QueueBase ()
virtual ~QueueBase ()
QueueSize GetCurrentSize (void) const
QueueSize GetMaxSize (void) const
uint32_t GetNBytes (void) const
uint32_t GetNPackets (void) const
uint32_t GetTotalDroppedBytes (void) const
uint32_t GetTotalDroppedBytesAfterDequeue (void) const
uint32_t GetTotalDroppedBytesBeforeEnqueue (void) const
uint32_t GetTotalDroppedPackets (void) const
uint32_t GetTotalDroppedPacketsAfterDequeue (void) const
uint32_t GetTotalDroppedPacketsBeforeEnqueue (void) const
uint32_t GetTotalReceivedBytes (void) const
uint32_t GetTotalReceivedPackets (void) const
bool IsEmpty (void) const
void ResetStatistics (void)
Resets the counts for dropped packets, dropped bytes, received packets, and received bytes.
void SetMaxSize (QueueSize size)
Set the maximum size of this queue.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::QueueBase
static void AppendItemTypeIfNotPresent (std::string &typeId, const std::string &itemType)
Append the item type to the provided type ID if the latter does not end with '>'.
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Types
typedef std::list< Ptr< Item > >::const_iterator ConstIterator
Const iterator.
typedef std::list< Ptr< Item > >::iterator Iterator
Iterator.
Protected Member Functions
Iterator begin (void)
Get an iterator which refers to the first item in the queue.
ConstIterator begin (void) const
Get a const iterator which refers to the first item in the queue.
Ptr< Item > DoDequeue (ConstIterator pos)
Pull the item to dequeue from the queue.
bool DoEnqueue (ConstIterator pos, Ptr< Item > item)
Push an item in the queue.
Ptr< const Item > DoPeek (ConstIterator pos) const
Peek the front item in the queue.
Ptr< Item > DoRemove (ConstIterator pos)
Pull the item to drop from the queue.
void DropAfterDequeue (Ptr< Item > item)
Drop a packet after dequeue.
void DropBeforeEnqueue (Ptr< Item > item)
Drop a packet before enqueue.
Iterator end (void)
Get an iterator which indicates past-the-last item in the queue.
ConstIterator end (void) const
Get a const iterator which indicates past-the-last item in the queue.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Attributes
std::list< Ptr< Item > > m_packets
the items in the queue
TracedCallback< Ptr< const Item > > m_traceDequeue
Traced callback: fired when a packet is dequeued.
TracedCallback< Ptr< const Item > > m_traceDrop
Traced callback: fired when a packet is dropped.
TracedCallback< Ptr< const Item > > m_traceDropAfterDequeue
Traced callback: fired when a packet is dropped after dequeue.
TracedCallback< Ptr< const Item > > m_traceDropBeforeEnqueue
Traced callback: fired when a packet is dropped before enqueue.
TracedCallback< Ptr< const Item > > m_traceEnqueue
Traced callback: fired when a packet is enqueued.
NS_LOG_TEMPLATE_DECLARE
the log component
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
template<typename Item>
class ns3::Queue< Item >
Template class for packet Queues.
This class defines the subset of the base APIs for packet queues in the ns-3 system that is dependent on the type of enqueued objects.
Queue is a template class. The type of the objects stored within the queue is specified by the type parameter, which can be any class providing a GetSize () method (e.g., Packet, QueueDiscItem, etc.). Subclasses need to implement the Enqueue, Dequeue, Remove and Peek methods, and are encouraged to leverage the DoEnqueue, DoDequeue, DoRemove, and DoPeek methods in doing so, to ensure that appropriate trace sources are called and statistics are maintained.
Users of the Queue template class usually hold a queue through a smart pointer, hence forward declaration is recommended to avoid pulling the implementation of the templates included in this file. Thus, do not include queue.h but add the following forward declaration in your .h file:
template <typename Item> class Queue;
Then, include queue.h in the corresponding .cc file.
Definition at line 253 of file queue.h.
Member Typedef Documentation
ConstIterator
template<typename Item > typedef std::list<Ptr<Item> >::const_iterator ns3::Queue< Item >::ConstIterator protected
Const iterator.
Definition at line 304 of file queue.h.
ItemType
template<typename Item > typedef Item ns3::Queue< Item >::ItemType
Define ItemType as the type of the stored elements.
Definition at line 299 of file queue.h.
Iterator
template<typename Item > typedef std::list<Ptr<Item> >::iterator ns3::Queue< Item >::Iterator protected
Iterator.
Definition at line 306 of file queue.h.
Constructor & Destructor Documentation
Queue()
template<typename Item > ns3::Queue< Item >::Queue
Definition at line 470 of file queue.h.
~Queue()
template<typename Item > ns3::Queue< Item >::~Queue virtual
Definition at line 476 of file queue.h.
Member Function Documentation
begin() [1/2]
template<typename Item > Queue< Item >::Iterator ns3::Queue< Item >::begin (void) protected
Get an iterator which refers to the first item in the queue.
Subclasses can browse the items in the queue by using an iterator
for (auto i = begin (); i != end (); ++i)
  {
    (*i)->method ();  // some method of the Item class
  }
Returns
an iterator which refers to the first item in the queue.
Definition at line 602 of file queue.h.
begin() [2/2]
template<typename Item > Queue< Item >::ConstIterator ns3::Queue< Item >::begin (void) const protected
Get a const iterator which refers to the first item in the queue.
Subclasses can browse the items in the queue by using a const iterator
for (auto i = begin (); i != end (); ++i)
  {
    (*i)->method ();  // some const method of the Item class
  }
Returns
a const iterator which refers to the first item in the queue.
Definition at line 596 of file queue.h.
Dequeue()
template<typename Item > virtual Ptr<Item> ns3::Queue< Item >::Dequeue (void) pure virtual
Remove an item from the Queue (each subclass defines the position), counting it as dequeued.
Returns
0 if the operation was not successful; the item otherwise.
Implemented in ns3::DropTailQueue< Item >.
DoDequeue()
template<typename Item > Ptr< Item > ns3::Queue< Item >::DoDequeue (ConstIterator pos) protected
Pull the item to dequeue from the queue.
Parameters
pos the position of the item to dequeue
Returns
the item.
Definition at line 510 of file queue.h.
References NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
DoEnqueue()
template<typename Item > bool ns3::Queue< Item >::DoEnqueue (ConstIterator pos, Ptr< Item > item) protected
Push an item in the queue.
Parameters
pos the position where the item is inserted
item the item to enqueue
Returns
true if success, false if the packet has been dropped.
Definition at line 482 of file queue.h.
References NS_LOG_FUNCTION, and NS_LOG_LOGIC.
DoPeek()
template<typename Item > Ptr< const Item > ns3::Queue< Item >::DoPeek (ConstIterator pos) const protected
Peek the front item in the queue.
Parameters
pos the position of the item to peek
Returns
the item.
Definition at line 582 of file queue.h.
References NS_LOG_FUNCTION, and NS_LOG_LOGIC.
DoRemove()
template<typename Item > Ptr< Item > ns3::Queue< Item >::DoRemove (ConstIterator pos) protected
Pull the item to drop from the queue.
Parameters
pos the position of the item to remove
Returns
the item.
Definition at line 539 of file queue.h.
References NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
DropAfterDequeue()
template<typename Item > void ns3::Queue< Item >::DropAfterDequeue (Ptr< Item > item) protected
Drop a packet after dequeue.
Parameters
item item that was dropped
This method is called by the base class when a Remove operation is requested and by the subclasses to notify parent (this class) that a packet has been dropped for other reasons after being dequeued.
Definition at line 637 of file queue.h.
References NS_LOG_FUNCTION, and NS_LOG_LOGIC.
DropBeforeEnqueue()
template<typename Item > void ns3::Queue< Item >::DropBeforeEnqueue (Ptr< Item > item) protected
Drop a packet before enqueue.
Parameters
item item that was dropped
This method is called by the base class when a packet is dropped because the queue is full and by the subclasses to notify parent (this class) that a packet has been dropped for other reasons before being enqueued.
Definition at line 621 of file queue.h.
References NS_LOG_FUNCTION, and NS_LOG_LOGIC.
end() [1/2]
template<typename Item > Queue< Item >::Iterator ns3::Queue< Item >::end (void) protected
Get an iterator which indicates past-the-last item in the queue.
Subclasses can browse the items in the queue by using an iterator
for (auto i = begin (); i != end (); ++i)
  {
    (*i)->method ();  // some method of the Item class
  }
Returns
an iterator which indicates past-the-last item in the queue.
Definition at line 614 of file queue.h.
Referenced by grid.TimelinesRenderer::draw_events(), and grid.TimelinesRenderer::draw_ranges().
end() [2/2]
template<typename Item > Queue< Item >::ConstIterator ns3::Queue< Item >::end (void) const protected
Get a const iterator which indicates past-the-last item in the queue.
Subclasses can browse the items in the queue by using a const iterator
for (auto i = begin (); i != end (); ++i)
  {
    (*i)->method ();  // some const method of the Item class
  }
Returns
a const iterator which indicates past-the-last item in the queue.
Definition at line 608 of file queue.h.
Referenced by grid.TimelinesRenderer::draw_events(), and grid.TimelinesRenderer::draw_ranges().
Enqueue()
template<typename Item > virtual bool ns3::Queue< Item >::Enqueue (Ptr< Item > item) pure virtual
Place an item into the Queue (each subclass defines the position)
Parameters
item item to enqueue
Returns
True if the operation was successful; false otherwise
Implemented in ns3::DropTailQueue< Item >.
Flush()
template<typename Item > void ns3::Queue< Item >::Flush (void)
Flush the queue.
Definition at line 571 of file queue.h.
References NS_LOG_FUNCTION.
GetTypeId()
template<typename Item > TypeId ns3::Queue< Item >::GetTypeId (void) static
Get the type ID.
Implementation of the templates declared above.
Returns
the object TypeId
Definition at line 444 of file queue.h.
References ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
Peek()
template<typename Item > virtual Ptr<const Item> ns3::Queue< Item >::Peek (void) const pure virtual
Get a copy of an item in the queue (each subclass defines the position) without removing it.
Returns
0 if the operation was not successful; the item otherwise.
Implemented in ns3::DropTailQueue< Item >.
Remove()
template<typename Item > virtual Ptr<Item> ns3::Queue< Item >::Remove (void) pure virtual
Remove an item from the Queue (each subclass defines the position), counting it as dropped.
Returns
0 if the operation was not successful; the item otherwise.
Implemented in ns3::DropTailQueue< Item >.
Member Data Documentation
m_packets
template<typename Item > std::list<Ptr<Item> > ns3::Queue< Item >::m_packets private
the items in the queue
Definition at line 422 of file queue.h.
m_traceDequeue
template<typename Item > TracedCallback<Ptr<const Item> > ns3::Queue< Item >::m_traceDequeue private
Traced callback: fired when a packet is dequeued.
Definition at line 428 of file queue.h.
m_traceDrop
template<typename Item > TracedCallback<Ptr<const Item> > ns3::Queue< Item >::m_traceDrop private
Traced callback: fired when a packet is dropped.
Definition at line 430 of file queue.h.
m_traceDropAfterDequeue
template<typename Item > TracedCallback<Ptr<const Item> > ns3::Queue< Item >::m_traceDropAfterDequeue private
Traced callback: fired when a packet is dropped after dequeue.
Definition at line 434 of file queue.h.
m_traceDropBeforeEnqueue
template<typename Item > TracedCallback<Ptr<const Item> > ns3::Queue< Item >::m_traceDropBeforeEnqueue private
Traced callback: fired when a packet is dropped before enqueue.
Definition at line 432 of file queue.h.
m_traceEnqueue
template<typename Item > TracedCallback<Ptr<const Item> > ns3::Queue< Item >::m_traceEnqueue private
Traced callback: fired when a packet is enqueued.
Definition at line 426 of file queue.h.
NS_LOG_TEMPLATE_DECLARE
template<typename Item > ns3::Queue< Item >::NS_LOG_TEMPLATE_DECLARE private
the log component
Definition at line 423 of file queue.h.
The documentation for this class was generated from the following files:
src/csma/model/csma-net-device.h
src/network/utils/queue.h