ns-3: StaticInformation Class Reference
StaticInformation Class Reference
Gather aggregation and configuration path information from registered types.
Public Member Functions
void Gather (TypeId tid)
Gather aggregation and configuration path information for tid.
std::vector< std::string > Get (TypeId tid) const
std::vector< std::string > GetNoTypeIds (void) const
void Print (void) const
Print output in "a -> b" form on std::cout.
void RecordAggregationInfo (std::string a, std::string b)
Record the a -> b aggregation relation.
Private Member Functions
void DoGather (TypeId tid)
Gather attribute, configuration path information for tid.
std::string GetCurrentPath (void) const
bool HasAlreadyBeenProcessed (TypeId tid) const
void RecordOutput (TypeId tid)
Record the current config path for tid.
Private Attributes
std::vector< std::pair< TypeId, TypeId > > m_aggregates
List of aggregation relationships.
std::vector< TypeId > m_alreadyProcessed
List of TypeIds we've already processed.
std::vector< std::string > m_currentPath
Current configuration path.
std::vector< std::string > m_noTids
List of type names without TypeIds, because those modules aren't enabled.
std::vector< std::pair< TypeId, std::string > > m_output
Configuration path for each TypeId.
Detailed Description
Gather aggregation and configuration path information from registered types.
Definition at line 211 of file print-introspected-doxygen.cc.
Member Function Documentation
DoGather()
void StaticInformation::DoGather (TypeId tid) private
Gather attribute, configuration path information for tid.
Parameters
tid [in] the TypeId to gather information from
Definition at line 421 of file print-introspected-doxygen.cc.
References ns3::TypeId::AttributeInformation::checker, ns3::TypeId::GetAttribute(), ns3::TypeId::GetAttributeN(), ns3::ObjectPtrContainerChecker::GetItemTypeId(), ns3::TypeId::GetName(), ns3::PointerChecker::GetPointeeTypeId(), ns3::TypeId::GetRegistered(), ns3::TypeId::GetRegisteredN(), ns3::TypeId::IsChildOf(), ns3::TypeId::AttributeInformation::name, NS_LOG_FUNCTION, and ns3::PeekPointer().
Gather()
void StaticInformation::Gather (TypeId tid)
Gather aggregation and configuration path information for tid.
Parameters
tid [in] the TypeId to gather information from
Definition at line 412 of file print-introspected-doxygen.cc.
References NS_LOG_FUNCTION, and Uniquefy().
Referenced by GetTypicalAggregations().
Get()
std::vector< std::string > StaticInformation::Get (TypeId tid) const
Returns
the configuration paths for tid
Parameters
tid [in] the TypeId to return information for
Definition at line 365 of file print-introspected-doxygen.cc.
References NS_LOG_FUNCTION.
Referenced by PrintConfigPaths().
GetCurrentPath()
std::string StaticInformation::GetCurrentPath (void) const private
Returns
the current configuration path
Definition at line 329 of file print-introspected-doxygen.cc.
References NS_LOG_FUNCTION.
GetNoTypeIds()
std::vector< std::string > StaticInformation::GetNoTypeIds (void) const
Returns
the type names we couldn't aggregate.
Definition at line 403 of file print-introspected-doxygen.cc.
References NS_LOG_FUNCTION, and Uniquefy().
Referenced by GetNameMap().
HasAlreadyBeenProcessed()
bool StaticInformation::HasAlreadyBeenProcessed (TypeId tid) const private
Returns
whether the tid has already been processed
Parameters
tid [in] the TypeId to check.
Definition at line 350 of file print-introspected-doxygen.cc.
References NS_LOG_FUNCTION.
Print()
void StaticInformation::Print (void) const
Print output in "a -> b" form on std::cout.
Definition at line 318 of file print-introspected-doxygen.cc.
References NS_LOG_FUNCTION.
RecordAggregationInfo()
void StaticInformation::RecordAggregationInfo (std::string a, std::string b)
Record the a -> b aggregation relation.
Parameters
a [in] the source(?) TypeId name
b [in] the destination(?) TypeId name
Definition at line 295 of file print-introspected-doxygen.cc.
References ns3::TypeId::LookupByNameFailSafe(), and NS_LOG_FUNCTION.
Referenced by GetTypicalAggregations().
RecordOutput()
void StaticInformation::RecordOutput (TypeId tid) private
Record the current config path for tid.
Parameters
tid [in] the TypeId to record.
Definition at line 342 of file print-introspected-doxygen.cc.
References NS_LOG_FUNCTION.
Member Data Documentation
m_aggregates
std::vector<std::pair<TypeId,TypeId> > StaticInformation::m_aggregates private
List of aggregation relationships.
Definition at line 282 of file print-introspected-doxygen.cc.
m_alreadyProcessed
std::vector<TypeId> StaticInformation::m_alreadyProcessed private
List of TypeIds we've already processed.
Definition at line 278 of file print-introspected-doxygen.cc.
m_currentPath
std::vector<std::string> StaticInformation::m_currentPath private
Current configuration path.
Definition at line 274 of file print-introspected-doxygen.cc.
m_noTids
std::vector<std::string> StaticInformation::m_noTids mutable private
List of type names without TypeIds, because those modules aren't enabled.
This is mutable because GetNoTypeIds sorts and uniquifies this list before returning it.
Definition at line 289 of file print-introspected-doxygen.cc.
m_output
std::vector<std::pair<TypeId,std::string> > StaticInformation::m_output private
Configuration path for each TypeId.
Definition at line 270 of file print-introspected-doxygen.cc.
The documentation for this class was generated from the following file:
utils/print-introspected-doxygen.cc