ns-3: ns3::A3RsrpHandoverAlgorithm Class Reference
ns3::A3RsrpHandoverAlgorithm Class Reference
Implementation of the strongest cell handover algorithm, based on RSRP measurements and Event A3.
#include "a3-rsrp-handover-algorithm.h"
Public Member Functions
A3RsrpHandoverAlgorithm ()
Creates a strongest cell handover algorithm instance.
virtual ~A3RsrpHandoverAlgorithm ()
virtual LteHandoverManagementSapProvider * GetLteHandoverManagementSapProvider ()
Export the "provider" part of the Handover Management SAP interface.
virtual void SetLteHandoverManagementSapUser (LteHandoverManagementSapUser *s)
Set the "user" part of the Handover Management SAP interface that this handover algorithm instance will interact with.
Public Member Functions inherited from ns3::LteHandoverAlgorithm
LteHandoverAlgorithm ()
virtual ~LteHandoverAlgorithm ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::LteHandoverAlgorithm
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose ()
Destructor implementation.
virtual void DoInitialize ()
Initialize() implementation.
void DoReportUeMeas (uint16_t rnti, LteRrcSap::MeasResults measResults)
Implementation of LteHandoverManagementSapProvider::ReportUeMeas.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
bool IsValidNeighbour (uint16_t cellId)
Determines if a neighbour cell is a valid destination for handover.
Private Attributes
LteHandoverManagementSapProvider * m_handoverManagementSapProvider
Receive API calls from the eNodeB RRC instance.
LteHandoverManagementSapUser * m_handoverManagementSapUser
Interface to the eNodeB RRC instance.
double m_hysteresisDb
The Hysteresis attribute.
uint8_t m_measId
The expected measurement identity for A3 measurements.
Time m_timeToTrigger
The TimeToTrigger attribute.
Friends
class MemberLteHandoverManagementSapProvider< A3RsrpHandoverAlgorithm >
let the forwarder class access the protected and private members
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implementation of the strongest cell handover algorithm, based on RSRP measurements and Event A3.
The algorithm utilizes Event A3 (Section 5.5.4.4 of 3GPP TS 36.331) UE measurements and the Reference Signal Reference Power (RSRP). It is defined as the event when the UE perceives that a neighbour cell's RSRP is better than the serving cell's RSRP.
Handover margin (a.k.a. hysteresis) and time-to-trigger (TTT) can be configured to delay the event triggering. The values of these parameters apply to all attached UEs.
The following code snippet is an example of using and configuring the handover algorithm in a simulation program:
Ptr<LteHelper> lteHelper = CreateObject<LteHelper> ();
NodeContainer enbNodes;
// configure the nodes here...
lteHelper->SetHandoverAlgorithmType ("ns3::A3RsrpHandoverAlgorithm");
lteHelper->SetHandoverAlgorithmAttribute ("Hysteresis",
                                          DoubleValue (3.0));
lteHelper->SetHandoverAlgorithmAttribute ("TimeToTrigger",
                                          TimeValue (MilliSeconds (256)));
NetDeviceContainer enbLteDevs = lteHelper->InstallEnbDevice (enbNodes);
Note
Setting the handover algorithm type and attributes after the call to LteHelper::InstallEnbDevice does not have any effect to the devices that have already been installed.
Config Paths
ns3::A3RsrpHandoverAlgorithm is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteEnbNetDevice/LteHandoverAlgorithm/$ns3::A3RsrpHandoverAlgorithm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteEnbNetDevice/LteHandoverAlgorithm/$ns3::A3RsrpHandoverAlgorithm"
Attributes
Hysteresis: Handover margin (hysteresis) in dB (rounded to the nearest multiple of 0.5 dB)
Set with class: ns3::DoubleValue
Underlying type: uint8_t 0:15
Initial value: 3
Flags: construct write read
TimeToTrigger: Time during which neighbour cell's RSRP must continuously higher than serving cell's RSRP in order to trigger a handover
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +2.56e+08ns
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 64 bytes (on a 64-bit architecture).
Definition at line 65 of file a3-rsrp-handover-algorithm.h.
Constructor & Destructor Documentation
A3RsrpHandoverAlgorithm()
ns3::A3RsrpHandoverAlgorithm::A3RsrpHandoverAlgorithm ()
Creates a strongest cell handover algorithm instance.
Definition at line 35 of file a3-rsrp-handover-algorithm.cc.
References m_handoverManagementSapProvider, MemberLteHandoverManagementSapProvider< A3RsrpHandoverAlgorithm >, and NS_LOG_FUNCTION.
~A3RsrpHandoverAlgorithm()
ns3::A3RsrpHandoverAlgorithm::~A3RsrpHandoverAlgorithm () virtual
Definition at line 43 of file a3-rsrp-handover-algorithm.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::A3RsrpHandoverAlgorithm::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::LteHandoverAlgorithm.
Definition at line 115 of file a3-rsrp-handover-algorithm.cc.
References m_handoverManagementSapProvider, and NS_LOG_FUNCTION.
DoInitialize()
void ns3::A3RsrpHandoverAlgorithm::DoInitialize (void) protected virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 91 of file a3-rsrp-handover-algorithm.cc.
References ns3::LteRrcSap::ReportConfigEutra::a3Offset, ns3::EutranMeasurementMapping::ActualHysteresis2IeValue(), ns3::LteHandoverManagementSapUser::AddUeMeasReportConfigForHandover(), ns3::Time::As(), ns3::Object::DoInitialize(), ns3::LteRrcSap::ReportConfigEutra::EVENT_A3, ns3::LteRrcSap::ReportConfigEutra::eventId, ns3::Time::GetMilliSeconds(), ns3::LteRrcSap::ReportConfigEutra::hysteresis, m_handoverManagementSapUser, m_hysteresisDb, m_measId, m_timeToTrigger, ns3::Time::MS, ns3::LteRrcSap::ReportConfigEutra::MS1024, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::LteRrcSap::ReportConfigEutra::reportInterval, ns3::LteRrcSap::ReportConfigEutra::reportOnLeave, ns3::LteRrcSap::ReportConfigEutra::RSRP, ns3::LteRrcSap::ReportConfigEutra::timeToTrigger, and ns3::LteRrcSap::ReportConfigEutra::triggerQuantity.
DoReportUeMeas()
void ns3::A3RsrpHandoverAlgorithm::DoReportUeMeas (uint16_t rnti, LteRrcSap::MeasResults measResults) protected virtual
Implementation of LteHandoverManagementSapProvider::ReportUeMeas.
Parameters
rnti Radio Network Temporary Identity, an integer identifying the UE where the report originates from
measResults a single report of one measurement identity
Implements ns3::LteHandoverAlgorithm.
Definition at line 123 of file a3-rsrp-handover-algorithm.cc.
References ns3::LteRrcSap::MeasResults::haveMeasResultNeighCells, IsValidNeighbour(), m_handoverManagementSapUser, m_measId, ns3::LteRrcSap::MeasResults::measId, ns3::LteRrcSap::MeasResults::measResultListEutra, NS_LOG_FUNCTION, NS_LOG_LOGIC, NS_LOG_WARN, ns3::LteRrcSap::MeasResults::rsrpResult, and ns3::LteHandoverManagementSapUser::TriggerHandover().
GetLteHandoverManagementSapProvider()
LteHandoverManagementSapProvider * ns3::A3RsrpHandoverAlgorithm::GetLteHandoverManagementSapProvider () virtual
Export the "provider" part of the Handover Management SAP interface.
Returns
the reference to the "provider" part of the interface, typically to be kept by an LteEnbRrc instance
Implements ns3::LteHandoverAlgorithm.
Definition at line 83 of file a3-rsrp-handover-algorithm.cc.
References m_handoverManagementSapProvider, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::A3RsrpHandoverAlgorithm::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 50 of file a3-rsrp-handover-algorithm.cc.
References m_hysteresisDb, m_timeToTrigger, ns3::MakeDoubleAccessor(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MilliSeconds(), and ns3::TypeId::SetParent().
IsValidNeighbour()
bool ns3::A3RsrpHandoverAlgorithm::IsValidNeighbour (uint16_t cellId) private
Determines if a neighbour cell is a valid destination for handover.
Currently always return true.
Parameters
cellId The cell ID of the neighbour cell.
Returns
True if the cell is a valid destination for handover.
Todo:
In the future, this function can be expanded to validate whether the neighbour cell is a valid target cell, e.g., taking into account the NRT in ANR and whether it is a CSG cell with closed access.
Definition at line 180 of file a3-rsrp-handover-algorithm.cc.
References NS_LOG_FUNCTION.
Referenced by DoReportUeMeas().
SetLteHandoverManagementSapUser()
void ns3::A3RsrpHandoverAlgorithm::SetLteHandoverManagementSapUser (LteHandoverManagementSapUser * s) virtual
Set the "user" part of the Handover Management SAP interface that this handover algorithm instance will interact with.
Parameters
s a reference to the "user" part of the interface, typically a member of an LteEnbRrc instance
Implements ns3::LteHandoverAlgorithm.
Definition at line 75 of file a3-rsrp-handover-algorithm.cc.
References m_handoverManagementSapUser, and NS_LOG_FUNCTION.
Friends And Related Function Documentation
MemberLteHandoverManagementSapProvider< A3RsrpHandoverAlgorithm >
friend class MemberLteHandoverManagementSapProvider< A3RsrpHandoverAlgorithm > friend
let the forwarder class access the protected and private members
Definition at line 81 of file a3-rsrp-handover-algorithm.h.
Referenced by A3RsrpHandoverAlgorithm().
Member Data Documentation
m_handoverManagementSapProvider
LteHandoverManagementSapProvider* ns3::A3RsrpHandoverAlgorithm::m_handoverManagementSapProvider private
Receive API calls from the eNodeB RRC instance.
Definition at line 121 of file a3-rsrp-handover-algorithm.h.
Referenced by A3RsrpHandoverAlgorithm(), DoDispose(), and GetLteHandoverManagementSapProvider().
m_handoverManagementSapUser
LteHandoverManagementSapUser* ns3::A3RsrpHandoverAlgorithm::m_handoverManagementSapUser private
Interface to the eNodeB RRC instance.
Definition at line 119 of file a3-rsrp-handover-algorithm.h.
Referenced by DoInitialize(), DoReportUeMeas(), and SetLteHandoverManagementSapUser().
m_hysteresisDb
double ns3::A3RsrpHandoverAlgorithm::m_hysteresisDb private
The Hysteresis attribute.
Handover margin (hysteresis) in dB (rounded to the nearest multiple of 0.5 dB).
Definition at line 111 of file a3-rsrp-handover-algorithm.h.
Referenced by DoInitialize(), and GetTypeId().
m_measId
uint8_t ns3::A3RsrpHandoverAlgorithm::m_measId private
The expected measurement identity for A3 measurements.
Definition at line 105 of file a3-rsrp-handover-algorithm.h.
Referenced by DoInitialize(), and DoReportUeMeas().
m_timeToTrigger
Time ns3::A3RsrpHandoverAlgorithm::m_timeToTrigger private
The TimeToTrigger attribute.
Time during which neighbour cell's RSRP must continuously higher than serving cell's RSRP "
Definition at line 116 of file a3-rsrp-handover-algorithm.h.
Referenced by DoInitialize(), and GetTypeId().
The documentation for this class was generated from the following files:
src/lte/model/a3-rsrp-handover-algorithm.h
src/lte/model/a3-rsrp-handover-algorithm.cc