ns-3: ns3::PointToPointEpcHelper Class Reference
ns3::PointToPointEpcHelper Class Reference
LTE Models
Create an EPC network with PointToPoint links in the backhaul network.
#include "point-to-point-epc-helper.h"
Public Member Functions
PointToPointEpcHelper ()
Constructor.
virtual ~PointToPointEpcHelper ()
Destructor.
virtual void AddEnb (Ptr< Node > enbNode, Ptr< NetDevice > lteEnbNetDevice, uint16_t cellId)
Add an eNB to the EPC.
virtual void DoDispose ()
Destructor implementation.
TypeId GetInstanceTypeId () const
Get the most derived TypeId for this Object.
Public Member Functions inherited from ns3::NoBackhaulEpcHelper
NoBackhaulEpcHelper ()
Constructor.
virtual ~NoBackhaulEpcHelper ()
Destructor.
virtual uint8_t ActivateEpsBearer (Ptr< NetDevice > ueLteDevice, uint64_t imsi, Ptr< EpcTft > tft, EpsBearer bearer)
Activate an EPS bearer, setting up the corresponding S1-U tunnel.
virtual void AddS1Interface (Ptr< Node > enb, Ipv4Address enbAddress, Ipv4Address sgwAddress, uint16_t cellId=0)
Add an S1 interface between an eNB and a SGW.
virtual void AddUe (Ptr< NetDevice > ueLteDevice, uint64_t imsi)
Notify the EPC of the existence of a new UE which might attach at a later time.
virtual void AddX2Interface (Ptr< Node > enbNode1, Ptr< Node > enbNode2)
Add an X2 interface between two eNB.
virtual Ipv4InterfaceContainer AssignUeIpv4Address (NetDeviceContainer ueDevices)
Assign IPv4 addresses to UE devices.
virtual Ipv6InterfaceContainer AssignUeIpv6Address (NetDeviceContainer ueDevices)
Assign IPv6 addresses to UE devices.
virtual Ptr< Node > GetPgwNode () const
Get the PGW node.
virtual Ptr< Node > GetSgwNode () const
Get the SGW node.
virtual Ipv4Address GetUeDefaultGatewayAddress ()
virtual Ipv6Address GetUeDefaultGatewayAddress6 ()
Public Member Functions inherited from ns3::EpcHelper
EpcHelper ()
Constructor.
virtual ~EpcHelper ()
Destructor.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::NoBackhaulEpcHelper
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::EpcHelper
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Ipv4AddressHelper m_s1apIpv4AddressHelper
Helper to assign addresses to S1-MME NetDevices.
Ipv4AddressHelper m_s1uIpv4AddressHelper
S1-U interfaces.
DataRate m_s1uLinkDataRate
The data rate to be used for the next S1-U link to be created.
Time m_s1uLinkDelay
The delay to be used for the next S1-U link to be created.
bool m_s1uLinkEnablePcap
Enable PCAP generation for S1 link.
uint16_t m_s1uLinkMtu
The MTU of the next S1-U link to be created.
std::string m_s1uLinkPcapPrefix
Prefix for the PCAP file for the S1 link.
Additional Inherited Members
Protected Member Functions inherited from ns3::NoBackhaulEpcHelper
virtual void DoActivateEpsBearerForUe (const Ptr< NetDevice > &ueDevice, const Ptr< EpcTft > &tft, const EpsBearer &bearer) const
DoActivateEpsBearerForUe: Schedule ActivateEpsBearer on the UE.
virtual void DoAddX2Interface (const Ptr< EpcX2 > &enb1X2, const Ptr< NetDevice > &enb1LteDev, const Ipv4Address &enb1X2Address, const Ptr< EpcX2 > &enb2X2, const Ptr< NetDevice > &enb2LteDev, const Ipv4Address &enb2X2Address) const
DoAddX2Interface: Call AddX2Interface on top of the Enb device pointers.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Create an EPC network with PointToPoint links in the backhaul network.
Introspection did not find any typical Config paths.
This Helper extends NoBackhaulEpcHelper creating PointToPoint links in the backhaul network (i.e. in the S1-U and S1-MME interfaces)
Attributes
S1uLinkDataRate: The data rate to be used for the next S1-U link to be created
Set with class: DataRateValue
Underlying type: DataRate
Initial value: 10000000000bps
Flags: construct write read
S1uLinkDelay: The delay to be used for the next S1-U link to be created
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
S1uLinkMtu: The MTU of the next S1-U link to be created. Note that, because of the additional GTP/UDP/IP tunneling overhead, you need a MTU larger than the end-to-end MTU that you want to support.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 2000
Flags: construct write read
S1uLinkPcapPrefix: Prefix for Pcap generated by S1-U link
Set with class: StringValue
Underlying type:
Initial value: s1u
Flags: construct write read
S1uLinkEnablePcap: Enable Pcap for X2 link
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
Attributes defined in parent class ns3::NoBackhaulEpcHelper
S5LinkDataRate: The data rate to be used for the next S5 link to be created
Set with class: DataRateValue
Underlying type: DataRate
Initial value: 10000000000bps
Flags: construct write read
S5LinkDelay: The delay to be used for the next S5 link to be created
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
S5LinkMtu: The MTU of the next S5 link to be created
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 2000
Flags: construct write read
S11LinkDataRate: The data rate to be used for the next S11 link to be created
Set with class: DataRateValue
Underlying type: DataRate
Initial value: 10000000000bps
Flags: construct write read
S11LinkDelay: The delay to be used for the next S11 link to be created
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
S11LinkMtu: The MTU of the next S11 link to be created.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 2000
Flags: construct write read
X2LinkDataRate: The data rate to be used for the next X2 link to be created
Set with class: DataRateValue
Underlying type: DataRate
Initial value: 10000000000bps
Flags: construct write read
X2LinkDelay: The delay to be used for the next X2 link to be created
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
X2LinkMtu: The MTU of the next X2 link to be created. Note that, because of some big X2 messages, you need a big MTU.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 3000
Flags: construct write read
X2LinkPcapPrefix: Prefix for Pcap generated by X2 link
Set with class: StringValue
Underlying type:
Initial value: x2
Flags: construct write read
X2LinkEnablePcap: Enable Pcap for X2 link
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 472 bytes (on a 64-bit architecture).
Definition at line 38 of file point-to-point-epc-helper.h.
Constructor & Destructor Documentation
PointToPointEpcHelper()
ns3::PointToPointEpcHelper::PointToPointEpcHelper ()
Constructor.
Definition at line 38 of file point-to-point-epc-helper.cc.
References ns3::ObjectBase::ConstructSelf(), m_s1apIpv4AddressHelper, m_s1uIpv4AddressHelper, NS_LOG_FUNCTION, and ns3::Ipv4AddressHelper::SetBase().
~PointToPointEpcHelper()
ns3::PointToPointEpcHelper::~PointToPointEpcHelper () virtual
Destructor.
Definition at line 52 of file point-to-point-epc-helper.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddEnb()
void ns3::PointToPointEpcHelper::AddEnb (Ptr< Node > enbNode, Ptr< NetDevice > lteEnbNetDevice, uint16_t cellId) virtual
Add an eNB to the EPC.
Parameters
enbNode the previously created eNB node which is to be added to the EPC
lteEnbNetDevice the LteEnbNetDevice of the eNB node
cellId ID of the eNB
Reimplemented from ns3::NoBackhaulEpcHelper.
Definition at line 109 of file point-to-point-epc-helper.cc.
References ns3::NoBackhaulEpcHelper::AddEnb(), ns3::NoBackhaulEpcHelper::AddS1Interface(), ns3::Ipv4AddressHelper::Assign(), ns3::PcapHelperForDevice::EnablePcapAll(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::Ipv4::GetNInterfaces(), ns3::Object::GetObject(), ns3::NoBackhaulEpcHelper::GetSgwNode(), ns3::PointToPointHelper::Install(), m_s1uIpv4AddressHelper, m_s1uLinkDataRate, m_s1uLinkDelay, m_s1uLinkEnablePcap, m_s1uLinkMtu, m_s1uLinkPcapPrefix, ns3::Ipv4AddressHelper::NewNetwork(), NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::PointToPointHelper::SetChannelAttribute(), and ns3::PointToPointHelper::SetDeviceAttribute().
Referenced by EpcS1uDlTestCase::DoRun(), and EpcS1uUlTestCase::DoRun().
DoDispose()
void ns3::PointToPointEpcHelper::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::NoBackhaulEpcHelper.
Definition at line 101 of file point-to-point-epc-helper.cc.
References ns3::NoBackhaulEpcHelper::DoDispose(), and NS_LOG_FUNCTION.
GetInstanceTypeId()
TypeId ns3::PointToPointEpcHelper::GetInstanceTypeId () const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Reimplemented from ns3::NoBackhaulEpcHelper.
Definition at line 95 of file point-to-point-epc-helper.cc.
References GetTypeId().
GetTypeId()
TypeId ns3::PointToPointEpcHelper::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 58 of file point-to-point-epc-helper.cc.
References m_s1uLinkDataRate, m_s1uLinkDelay, m_s1uLinkEnablePcap, m_s1uLinkMtu, m_s1uLinkPcapPrefix, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeDataRateAccessor(), ns3::MakeDataRateChecker(), ns3::MakeStringAccessor(), ns3::MakeStringChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeUintegerAccessor(), NS_LOG_FUNCTION_NOARGS, ns3::Seconds(), and ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Member Data Documentation
m_s1apIpv4AddressHelper
Ipv4AddressHelper ns3::PointToPointEpcHelper::m_s1apIpv4AddressHelper private
Helper to assign addresses to S1-MME NetDevices.
Definition at line 96 of file point-to-point-epc-helper.h.
Referenced by PointToPointEpcHelper().
m_s1uIpv4AddressHelper
Ipv4AddressHelper ns3::PointToPointEpcHelper::m_s1uIpv4AddressHelper private
S1-U interfaces.
Helper to assign addresses to S1-U NetDevices
Definition at line 73 of file point-to-point-epc-helper.h.
Referenced by PointToPointEpcHelper(), and AddEnb().
m_s1uLinkDataRate
DataRate ns3::PointToPointEpcHelper::m_s1uLinkDataRate private
The data rate to be used for the next S1-U link to be created.
Definition at line 78 of file point-to-point-epc-helper.h.
Referenced by AddEnb(), and GetTypeId().
m_s1uLinkDelay
Time ns3::PointToPointEpcHelper::m_s1uLinkDelay private
The delay to be used for the next S1-U link to be created.
Definition at line 83 of file point-to-point-epc-helper.h.
Referenced by AddEnb(), and GetTypeId().
m_s1uLinkEnablePcap
bool ns3::PointToPointEpcHelper::m_s1uLinkEnablePcap private
Enable PCAP generation for S1 link.
Definition at line 101 of file point-to-point-epc-helper.h.
Referenced by AddEnb(), and GetTypeId().
m_s1uLinkMtu
uint16_t ns3::PointToPointEpcHelper::m_s1uLinkMtu private
The MTU of the next S1-U link to be created.
Note that, because of the additional GTP/UDP/IP tunneling overhead, you need a MTU larger than the end-to-end MTU that you want to support.
Definition at line 91 of file point-to-point-epc-helper.h.
Referenced by AddEnb(), and GetTypeId().
m_s1uLinkPcapPrefix
std::string ns3::PointToPointEpcHelper::m_s1uLinkPcapPrefix private
Prefix for the PCAP file for the S1 link.
Definition at line 106 of file point-to-point-epc-helper.h.
Referenced by AddEnb(), and GetTypeId().
The documentation for this class was generated from the following files:
src/lte/helper/point-to-point-epc-helper.h
src/lte/helper/point-to-point-epc-helper.cc