ns-3: ns3::BlockAckWindow Class Reference
ns3::BlockAckWindow Class Reference
Wifi Models
Block ack window.
#include "block-ack-window.h"
Public Member Functions
BlockAckWindow ()
Constructor.
void Advance (std::size_t count)
Advance the current winStart by the given number of positions.
std::vector< bool >::reference At (std::size_t distance)
Get a reference to the element in the window having the given distance from the current winStart.
uint16_t GetWinEnd (void) const
Get the current winEnd value.
std::size_t GetWinSize (void) const
Get the window size.
uint16_t GetWinStart (void) const
Get the current winStart value.
void Init (uint16_t winStart, uint16_t winSize)
Initialize the window with the given starting sequence number and size.
void Reset (uint16_t winStart)
Reset the window by clearing all the elements and setting winStart to the given value.
Private Attributes
std::size_t m_head
index of winStart in the vector
std::vector< bool > m_window
window
uint16_t m_winStart
window start (sequence number)
Detailed Description
Block ack window.
This class provides the basic functionalities of a window sliding over a bitmap: accessing any element in the bitmap and moving the window forward a given number of positions. This class can be used to implement both an originator's window and a recipient's window.
The window is implemented as a vector of bool and managed as a circular queue. The window is moved forward by advancing the head of the queue and clearing the elements that become part of the tail of the queue. Hence, no element is required to be shifted when the window moves forward.
Example:
|0|1|1|0|1|1|1|0|1|1|1|1|1|1|1|0| ^ | HEAD
After moving the window forward three positions:
|0|1|1|0|1|1|1|0|1|1|0|0|0|1|1|0| ^ | HEAD
Definition at line 56 of file block-ack-window.h.
Constructor & Destructor Documentation
BlockAckWindow()
ns3::BlockAckWindow::BlockAckWindow ()
Constructor.
Definition at line 29 of file block-ack-window.cc.
Member Function Documentation
Advance()
void ns3::BlockAckWindow::Advance (std::size_t count)
Advance the current winStart by the given number of positions.
Parameters
count the number of positions the current winStart must be advanced by
Definition at line 77 of file block-ack-window.cc.
References m_head, m_window, m_winStart, NS_LOG_FUNCTION, Reset(), and ns3::SEQNO_SPACE_SIZE.
Referenced by ns3::OriginatorBlockAckAgreement::AdvanceTxWindow(), ns3::OriginatorBlockAckAgreement::NotifyDiscardedMpdu(), and ns3::OriginatorBlockAckAgreement::NotifyTransmittedMpdu().
At()
std::vector< bool >::reference ns3::BlockAckWindow::At (std::size_t distance)
Get a reference to the element in the window having the given distance from the current winStart.
Note that the given distance must be less than the window size.
Parameters
distance the given distance
Returns
a reference to the element in the window having the given distance from the current winStart
Definition at line 69 of file block-ack-window.cc.
References m_head, m_window, and NS_ASSERT.
Referenced by ns3::OriginatorBlockAckAgreement::AdvanceTxWindow(), OriginatorBlockAckWindowTest::DoRun(), and ns3::OriginatorBlockAckAgreement::NotifyAckedMpdu().
GetWinEnd()
uint16_t ns3::BlockAckWindow::GetWinEnd (void) const
Get the current winEnd value.
Returns
the current winEnd value
Definition at line 57 of file block-ack-window.cc.
References m_window, m_winStart, and ns3::SEQNO_SPACE_SIZE.
Referenced by OriginatorBlockAckWindowTest::DoRun().
GetWinSize()
std::size_t ns3::BlockAckWindow::GetWinSize (void) const
Get the window size.
Returns
the window size
Definition at line 63 of file block-ack-window.cc.
References m_window.
Referenced by OriginatorBlockAckWindowTest::DoRun(), ns3::OriginatorBlockAckAgreement::GetStartingSequence(), and ns3::OriginatorBlockAckAgreement::NotifyTransmittedMpdu().
GetWinStart()
uint16_t ns3::BlockAckWindow::GetWinStart (void) const
Get the current winStart value.
Returns
the current winStart value
Definition at line 51 of file block-ack-window.cc.
References m_winStart.
Referenced by OriginatorBlockAckWindowTest::DoRun(), ns3::OriginatorBlockAckAgreement::GetStartingSequence(), ns3::OriginatorBlockAckAgreement::NotifyAckedMpdu(), ns3::OriginatorBlockAckAgreement::NotifyDiscardedMpdu(), and ns3::OriginatorBlockAckAgreement::NotifyTransmittedMpdu().
Init()
void ns3::BlockAckWindow::Init (uint16_t winStart, uint16_t winSize)
Initialize the window with the given starting sequence number and size.
Parameters
winStart the window start
winSize the window size
Definition at line 36 of file block-ack-window.cc.
References m_head, m_window, m_winStart, and NS_LOG_FUNCTION.
Referenced by ns3::OriginatorBlockAckAgreement::InitTxWindow(), and Reset().
Reset()
void ns3::BlockAckWindow::Reset (uint16_t winStart)
Reset the window by clearing all the elements and setting winStart to the given value.
Parameters
winStart the window start
Definition at line 45 of file block-ack-window.cc.
References Init(), and m_window.
Referenced by Advance().
Member Data Documentation
m_head
std::size_t ns3::BlockAckWindow::m_head private
index of winStart in the vector
Definition at line 115 of file block-ack-window.h.
Referenced by Advance(), At(), and Init().
m_window
std::vector<bool> ns3::BlockAckWindow::m_window private
window
Definition at line 114 of file block-ack-window.h.
Referenced by Advance(), At(), GetWinEnd(), GetWinSize(), Init(), and Reset().
m_winStart
uint16_t ns3::BlockAckWindow::m_winStart private
window start (sequence number)
Definition at line 113 of file block-ack-window.h.
Referenced by Advance(), GetWinEnd(), GetWinStart(), and Init().
The documentation for this class was generated from the following files:
src/wifi/model/block-ack-window.h
src/wifi/model/block-ack-window.cc