ns-3: ns3::BasicEnergySource Class Reference
ns3::BasicEnergySource Class Reference
Energy Models
BasicEnergySource decreases/increases remaining energy stored in itself in linearly.
#include "basic-energy-source.h"
Public Member Functions
BasicEnergySource ()
virtual ~BasicEnergySource ()
virtual double GetEnergyFraction (void)
Time GetEnergyUpdateInterval (void) const
virtual double GetInitialEnergy (void) const
virtual double GetRemainingEnergy (void)
virtual double GetSupplyVoltage (void) const
void SetEnergyUpdateInterval (Time interval)
void SetInitialEnergy (double initialEnergyJ)
void SetSupplyVoltage (double supplyVoltageV)
virtual void UpdateEnergySource (void)
Implements UpdateEnergySource.
Public Member Functions inherited from ns3::EnergySource
EnergySource ()
virtual ~EnergySource ()
void AppendDeviceEnergyModel (Ptr< DeviceEnergyModel > deviceEnergyModelPtr)
void ConnectEnergyHarvester (Ptr< EnergyHarvester > energyHarvesterPtr)
void DisposeDeviceModels (void)
Calls Dispose () method of the device energy models.
DeviceEnergyModelContainer FindDeviceEnergyModels (std::string name)
DeviceEnergyModelContainer FindDeviceEnergyModels (TypeId tid)
Ptr< Node > GetNode (void) const
void InitializeDeviceModels (void)
Calls Start () method of the device energy models.
void SetNode (Ptr< Node > node)
Sets pointer to node containing this EnergySource.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::EnergySource
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void CalculateRemainingEnergy (void)
Calculates remaining energy.
void DoDispose (void)
Defined in ns3::Object.
void DoInitialize (void)
Defined in ns3::Object.
void HandleEnergyDrainedEvent (void)
Handles the remaining energy going to zero event.
void HandleEnergyRechargedEvent (void)
Handles the remaining energy exceeding the high threshold after it went below the low threshold.
Private Attributes
bool m_depleted
EventId m_energyUpdateEvent
Time m_energyUpdateInterval
double m_highBatteryTh
double m_initialEnergyJ
Time m_lastUpdateTime
double m_lowBatteryTh
TracedValue< double > m_remainingEnergyJ
double m_supplyVoltageV
Additional Inherited Members
Protected Member Functions inherited from ns3::EnergySource
void BreakDeviceEnergyModelRefCycle (void)
This function is called to break reference cycle between EnergySource and DeviceEnergyModel.
double CalculateTotalCurrent (void)
void NotifyEnergyChanged (void)
This function notifies all DeviceEnergyModel of energy changed event.
void NotifyEnergyDrained (void)
This function notifies all DeviceEnergyModel of energy depletion event.
void NotifyEnergyRecharged (void)
This function notifies all DeviceEnergyModel of energy recharged event.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
BasicEnergySource decreases/increases remaining energy stored in itself in linearly.
Introspection did not find any typical Config paths.
Attributes
BasicEnergySourceInitialEnergyJ: Initial energy stored in basic energy source.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 10
Flags: construct write read
BasicEnergySupplyVoltageV: Initial supply voltage for basic energy source.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 3
Flags: construct write read
BasicEnergyLowBatteryThreshold: Low battery threshold for basic energy source.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0.1
Flags: construct write read
BasicEnergyHighBatteryThreshold: High battery threshold for basic energy source.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0.15
Flags: construct write read
PeriodicEnergyUpdateInterval: Time between two consecutive periodic energy updates.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+09ns
Flags: construct write read
TraceSources
RemainingEnergy: Remaining energy at BasicEnergySource.
Callback signature: ns3::TracedValueCallback::Double
Size of this type is 200 bytes (on a 64-bit architecture).
Definition at line 37 of file basic-energy-source.h.
Constructor & Destructor Documentation
BasicEnergySource()
ns3::BasicEnergySource::BasicEnergySource ()
Definition at line 77 of file basic-energy-source.cc.
References m_depleted, m_lastUpdateTime, NS_LOG_FUNCTION, and ns3::Seconds().
~BasicEnergySource()
ns3::BasicEnergySource::~BasicEnergySource () virtual
Definition at line 84 of file basic-energy-source.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CalculateRemainingEnergy()
void ns3::BasicEnergySource::CalculateRemainingEnergy (void) private
Calculates remaining energy.
This function uses the total current from all device models to calculate the amount of energy to decrease. The energy to decrease is given by: energy to decrease = total current * supply voltage * time duration This function subtracts the calculated energy to decrease from remaining energy.
Definition at line 220 of file basic-energy-source.cc.
References ns3::EnergySource::CalculateTotalCurrent(), ns3::Time::IsPositive(), m_lastUpdateTime, m_remainingEnergyJ, m_supplyVoltageV, ns3::Simulator::Now(), NS_ASSERT, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by UpdateEnergySource().
DoDispose()
void ns3::BasicEnergySource::DoDispose (void) private virtual
Defined in ns3::Object.
Reimplemented from ns3::EnergySource.
Definition at line 197 of file basic-energy-source.cc.
References ns3::EnergySource::BreakDeviceEnergyModelRefCycle(), and NS_LOG_FUNCTION.
DoInitialize()
void ns3::BasicEnergySource::DoInitialize (void) private virtual
Defined in ns3::Object.
Reimplemented from ns3::Object.
Definition at line 190 of file basic-energy-source.cc.
References NS_LOG_FUNCTION, and UpdateEnergySource().
GetEnergyFraction()
double ns3::BasicEnergySource::GetEnergyFraction (void) virtual
Returns
Energy fraction.
Implements GetEnergyFraction.
Implements ns3::EnergySource.
Definition at line 143 of file basic-energy-source.cc.
References m_initialEnergyJ, m_remainingEnergyJ, NS_LOG_FUNCTION, and UpdateEnergySource().
GetEnergyUpdateInterval()
Time ns3::BasicEnergySource::GetEnergyUpdateInterval (void) const
Returns
The interval between each energy update.
Definition at line 113 of file basic-energy-source.cc.
References m_energyUpdateInterval, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetInitialEnergy()
double ns3::BasicEnergySource::GetInitialEnergy (void) const virtual
Returns
Initial energy stored in energy source, in Joules.
Implements GetInitialEnergy.
Implements ns3::EnergySource.
Definition at line 127 of file basic-energy-source.cc.
References m_initialEnergyJ, and NS_LOG_FUNCTION.
Referenced by BasicEnergyHarvesterTestCase::DoRun(), GetTypeId(), and BasicEnergyUpdateTest::StateSwitchTest().
GetRemainingEnergy()
double ns3::BasicEnergySource::GetRemainingEnergy (void) virtual
Returns
Remaining energy in energy source, in Joules
Implements GetRemainingEnergy.
Implements ns3::EnergySource.
Definition at line 134 of file basic-energy-source.cc.
References m_remainingEnergyJ, NS_LOG_FUNCTION, and UpdateEnergySource().
Referenced by AnimationRemainingEnergyTestCase::CheckLogic(), BasicEnergyHarvesterTestCase::DoRun(), and BasicEnergyUpdateTest::StateSwitchTest().
GetSupplyVoltage()
double ns3::BasicEnergySource::GetSupplyVoltage (void) const virtual
Returns
Supply voltage at the energy source.
Implements GetSupplyVoltage.
Implements ns3::EnergySource.
Definition at line 120 of file basic-energy-source.cc.
References m_supplyVoltageV, and NS_LOG_FUNCTION.
Referenced by GetTypeId(), and BasicEnergyUpdateTest::StateSwitchTest().
GetTypeId()
TypeId ns3::BasicEnergySource::GetTypeId (void) static
Definition at line 35 of file basic-energy-source.cc.
References GetEnergyUpdateInterval(), GetInitialEnergy(), GetSupplyVoltage(), m_highBatteryTh, m_lowBatteryTh, m_remainingEnergyJ, ns3::MakeDoubleAccessor(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::Seconds(), SetEnergyUpdateInterval(), SetInitialEnergy(), ns3::TypeId::SetParent(), and SetSupplyVoltage().
HandleEnergyDrainedEvent()
void ns3::BasicEnergySource::HandleEnergyDrainedEvent (void) private
Handles the remaining energy going to zero event.
This function notifies all the energy models aggregated to the node about the energy being depleted. Each energy model is then responsible for its own handler.
Definition at line 204 of file basic-energy-source.cc.
References ns3::EnergySource::NotifyEnergyDrained(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by UpdateEnergySource().
HandleEnergyRechargedEvent()
void ns3::BasicEnergySource::HandleEnergyRechargedEvent (void) private
Handles the remaining energy exceeding the high threshold after it went below the low threshold.
This function notifies all the energy models aggregated to the node about the energy being recharged. Each energy model is then responsible for its own handler.
Definition at line 212 of file basic-energy-source.cc.
References ns3::EnergySource::NotifyEnergyRecharged(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by UpdateEnergySource().
SetEnergyUpdateInterval()
void ns3::BasicEnergySource::SetEnergyUpdateInterval (Time interval)
Parameters
interval Energy update interval.
This function sets the interval between each energy update.
Definition at line 106 of file basic-energy-source.cc.
References m_energyUpdateInterval, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetInitialEnergy()
void ns3::BasicEnergySource::SetInitialEnergy (double initialEnergyJ)
Parameters
initialEnergyJ Initial energy, in Joules
Sets initial energy stored in the energy source. Note that initial energy is assumed to be set before simulation starts and is set only once per simulation.
Definition at line 90 of file basic-energy-source.cc.
References m_initialEnergyJ, m_remainingEnergyJ, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by GetTypeId(), AnimationRemainingEnergyTestCase::PrepareNetwork(), and BasicEnergyUpdateTest::StateSwitchTest().
SetSupplyVoltage()
void ns3::BasicEnergySource::SetSupplyVoltage (double supplyVoltageV)
Parameters
supplyVoltageV Supply voltage at the energy source, in Volts.
Sets supply voltage of the energy source.
Definition at line 99 of file basic-energy-source.cc.
References m_supplyVoltageV, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
UpdateEnergySource()
void ns3::BasicEnergySource::UpdateEnergySource (void) virtual
Implements UpdateEnergySource.
Implements ns3::EnergySource.
Definition at line 152 of file basic-energy-source.cc.
References CalculateRemainingEnergy(), HandleEnergyDrainedEvent(), HandleEnergyRechargedEvent(), ns3::EventId::IsExpired(), m_depleted, m_energyUpdateEvent, m_energyUpdateInterval, m_highBatteryTh, m_initialEnergyJ, m_lastUpdateTime, m_lowBatteryTh, m_remainingEnergyJ, ns3::EnergySource::NotifyEnergyChanged(), ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::Simulator::Schedule().
Referenced by DoInitialize(), GetEnergyFraction(), GetRemainingEnergy(), and BasicEnergyUpdateTest::StateSwitchTest().
Member Data Documentation
m_depleted
bool ns3::BasicEnergySource::m_depleted private
Definition at line 143 of file basic-energy-source.h.
Referenced by BasicEnergySource(), and UpdateEnergySource().
m_energyUpdateEvent
EventId ns3::BasicEnergySource::m_energyUpdateEvent private
Definition at line 146 of file basic-energy-source.h.
Referenced by UpdateEnergySource().
m_energyUpdateInterval
Time ns3::BasicEnergySource::m_energyUpdateInterval private
Definition at line 148 of file basic-energy-source.h.
Referenced by GetEnergyUpdateInterval(), SetEnergyUpdateInterval(), and UpdateEnergySource().
m_highBatteryTh
double ns3::BasicEnergySource::m_highBatteryTh private
Definition at line 142 of file basic-energy-source.h.
Referenced by GetTypeId(), and UpdateEnergySource().
m_initialEnergyJ
double ns3::BasicEnergySource::m_initialEnergyJ private
Definition at line 139 of file basic-energy-source.h.
Referenced by GetEnergyFraction(), GetInitialEnergy(), SetInitialEnergy(), and UpdateEnergySource().
m_lastUpdateTime
Time ns3::BasicEnergySource::m_lastUpdateTime private
Definition at line 147 of file basic-energy-source.h.
Referenced by BasicEnergySource(), CalculateRemainingEnergy(), and UpdateEnergySource().
m_lowBatteryTh
double ns3::BasicEnergySource::m_lowBatteryTh private
Definition at line 141 of file basic-energy-source.h.
Referenced by GetTypeId(), and UpdateEnergySource().
m_remainingEnergyJ
TracedValue<double> ns3::BasicEnergySource::m_remainingEnergyJ private
Definition at line 145 of file basic-energy-source.h.
Referenced by CalculateRemainingEnergy(), GetEnergyFraction(), GetRemainingEnergy(), GetTypeId(), SetInitialEnergy(), and UpdateEnergySource().
m_supplyVoltageV
double ns3::BasicEnergySource::m_supplyVoltageV private
Definition at line 140 of file basic-energy-source.h.
Referenced by CalculateRemainingEnergy(), GetSupplyVoltage(), and SetSupplyVoltage().
The documentation for this class was generated from the following files:
src/energy/model/basic-energy-source.h
src/energy/model/basic-energy-source.cc