ns-3: ns3::BuildingList Class Reference
ns3::BuildingList Class Reference
#include "building-list.h"
Public Types
typedef std::vector< Ptr< Building > >::const_iterator Iterator
Static Public Member Functions
static uint32_t Add (Ptr< Building > building)
static Iterator Begin (void)
static Iterator End (void)
static Ptr< Building > GetBuilding (uint32_t n)
static uint32_t GetNBuildings (void)
Detailed Description
Definition at line 33 of file building-list.h.
Member Typedef Documentation
Iterator
typedef std::vector< Ptr<Building> >::const_iterator ns3::BuildingList::Iterator
Definition at line 36 of file building-list.h.
Member Function Documentation
Add()
uint32_t ns3::BuildingList::Add (Ptr< Building > building) static
Parameters
building building to add
Returns
index of building in list.
This method is called automatically from Building::Building so the user has little reason to call it himself.
Definition at line 168 of file building-list.cc.
References ns3::BuildingListPriv::Get().
Referenced by ns3::Building::Building().
Begin()
BuildingList::Iterator ns3::BuildingList::Begin (void) static
Returns
a C++ iterator located at the beginning of this list.
Definition at line 173 of file building-list.cc.
References ns3::BuildingListPriv::Get().
Referenced by ns3::ThreeGppV2vHighwayChannelConditionModel::GetChCondAndFixCallback(), ns3::BuildingContainer::GetGlobal(), ns3::RandomBuildingPositionAllocator::GetNext(), ns3::OutdoorPositionAllocator::GetNext(), ns3::RandomRoomPositionAllocator::GetNext(), ns3::RandomWalk2dOutdoorMobilityModel::IsLineClearOfBuildings(), ns3::BuildingsChannelConditionModel::IsLineOfSightBlocked(), ns3::BuildingsHelper::MakeConsistent(), ns3::MobilityBuildingInfo::MakeConsistent(), and PrintGnuplottableBuildingListToFile().
End()
BuildingList::Iterator ns3::BuildingList::End (void) static
Returns
a C++ iterator located at the end of this list.
Definition at line 178 of file building-list.cc.
References ns3::BuildingListPriv::Get().
Referenced by ns3::ThreeGppV2vHighwayChannelConditionModel::GetChCondAndFixCallback(), ns3::BuildingContainer::GetGlobal(), ns3::RandomBuildingPositionAllocator::GetNext(), ns3::OutdoorPositionAllocator::GetNext(), ns3::RandomRoomPositionAllocator::GetNext(), ns3::RandomWalk2dOutdoorMobilityModel::IsLineClearOfBuildings(), ns3::BuildingsChannelConditionModel::IsLineOfSightBlocked(), ns3::BuildingsHelper::MakeConsistent(), ns3::MobilityBuildingInfo::MakeConsistent(), and PrintGnuplottableBuildingListToFile().
GetBuilding()
Ptr< Building > ns3::BuildingList::GetBuilding (uint32_t n) static
Parameters
n index of requested building.
Returns
the Building associated to index n.
Definition at line 183 of file building-list.cc.
References ns3::BuildingListPriv::Get(), and sample-rng-plot::n.
Referenced by ns3::RandomBuildingPositionAllocator::GetNext().
GetNBuildings()
uint32_t ns3::BuildingList::GetNBuildings (void) static
Returns
the number of buildings currently in the list.
Definition at line 188 of file building-list.cc.
References ns3::BuildingListPriv::Get().
Referenced by ns3::RandomBuildingPositionAllocator::GetNext(), ns3::OutdoorPositionAllocator::GetNext(), and ns3::RandomRoomPositionAllocator::GetNext().
The documentation for this class was generated from the following files:
src/buildings/model/building-list.h
src/buildings/model/building-list.cc