ns-3: ns3::Time Class Reference
ns3::Time Class Reference
Core » Virtual Time
Simulation virtual time values and global simulation resolution.
#include "nstime.h"
Classes
struct Information
How to convert between other units and the current unit.
struct Resolution
Current time unit, and conversion info.
Public Types
typedef void(* TracedCallback) (Time value)
TracedCallback signature for Time.
enum Unit {
Y = 0 , D = 1 , H = 2 , MIN = 3 ,
S = 4 , MS = 5 , US = 6 , NS = 7 ,
PS = 8 , FS = 9 , LAST = 10 , AUTO = 11
}
The unit to use to interpret a number representing time.
Public Member Functions
Time ()
Default constructor, with value 0.
Time (const std::string &s)
Construct Time object from common time expressions like "1ms".
Time (const Time &o)
Copy constructor.
Time (Time &&o)
Move constructor.
~Time ()
Destructor.
TimeWithUnit As (const enum Unit unit=Time::AUTO) const
Attach a unit to a Time, to facilitate output in a specific unit.
int Compare (const Time &o) const
Compare this to another Time.
bool IsNegative (void) const
Exactly equivalent to t <= 0.
bool IsPositive (void) const
Exactly equivalent to t >= 0.
bool IsStrictlyNegative (void) const
Exactly equivalent to t < 0.
bool IsStrictlyPositive (void) const
Exactly equivalent to t > 0.
bool IsZero (void) const
Exactly equivalent to t == 0.
Time & operator= (const Time &o)
Assignment operator.
Time RoundTo (enum Unit unit) const
Round a Time to a specific unit.
Numeric constructors
Construct from a numeric value.
Time (double v)
Construct from a numeric value.
Time (int v)
Construct from a numeric value.
Time (long int v)
Construct from a numeric value.
Time (long long int v)
Construct from a numeric value.
Time (unsigned int v)
Construct from a numeric value.
Time (unsigned long int v)
Construct from a numeric value.
Time (unsigned long long int v)
Construct from a numeric value.
Time (const int64x64_t &v)
Construct from a numeric value.
Convert to Number in a Unit
Convert a Time to number, in indicated units.
Conversions to seconds and larger will return doubles, with possible loss of precision. Conversions to units smaller than seconds will be rounded.
double GetYears (void) const
Get an approximation of the time stored in this instance in the indicated unit.
double GetDays (void) const
Get an approximation of the time stored in this instance in the indicated unit.
double GetHours (void) const
Get an approximation of the time stored in this instance in the indicated unit.
double GetMinutes (void) const
Get an approximation of the time stored in this instance in the indicated unit.
double GetSeconds (void) const
Get an approximation of the time stored in this instance in the indicated unit.
int64_t GetMilliSeconds (void) const
Get an approximation of the time stored in this instance in the indicated unit.
int64_t GetMicroSeconds (void) const
Get an approximation of the time stored in this instance in the indicated unit.
int64_t GetNanoSeconds (void) const
Get an approximation of the time stored in this instance in the indicated unit.
int64_t GetPicoSeconds (void) const
Get an approximation of the time stored in this instance in the indicated unit.
int64_t GetFemtoSeconds (void) const
Get an approximation of the time stored in this instance in the indicated unit.
Convert to Raw Value
Convert a Time to a number in the current resolution units.
int64_t GetTimeStep (void) const
Get the raw time value, in the current resolution unit.
double GetDouble (void) const
Get the raw time value, in the current resolution unit.
int64_t GetInteger (void) const
Get the raw time value, in the current resolution unit.
Get Times as Numbers in Specified Units
Get the Time as integers or doubles in the indicated unit.
int64_t ToInteger (enum Unit unit) const
Get the Time value expressed in a particular unit.
double ToDouble (enum Unit unit) const
Get the Time value expressed in a particular unit.
int64x64_t To (enum Unit unit) const
Get the Time value expressed in a particular unit.
Static Public Member Functions
static Time From (const int64x64_t &value)
Create a Time in the current unit.
static enum Unit GetResolution (void)
static Time Max ()
Maximum representable Time Not to be confused with Max(Time,Time).
static Time Min ()
Minimum representable Time Not to be confused with Min(Time,Time).
static void SetResolution (enum Unit resolution)
static bool StaticInit ()
Function to force static initialization of Time.
Create Times from Values and Units
Create Times from values given in the indicated units.
static Time FromInteger (uint64_t value, enum Unit unit)
Create a Time equal to value in unit unit.
static Time FromDouble (double value, enum Unit unit)
Create a Time equal to value in unit unit.
static Time From (const int64x64_t &value, enum Unit unit)
Create a Time equal to value in unit unit.
Private Types
typedef std::set< Time * > MarkedTimes
Record all instances of Time, so we can rescale them when the resolution changes.
Static Private Member Functions
static void Clear (Time *const time)
Remove a Time instance from the MarkedTimes, called by ~Time().
static void ClearMarkedTimes ()
Remove all MarkedTimes.
static void ConvertTimes (const enum Unit unit)
Convert existing Times to the new unit.
static void Mark (Time *const time)
Record a Time instance with the MarkedTimes.
static struct Information * PeekInformation (enum Unit timeUnit)
Get the Information record for timeUnit for the current Resolution.
static struct Resolution * PeekResolution (void)
Get the current Resolution.
static struct Resolution SetDefaultNsResolution (void)
Set the default resolution.
static void SetResolution (enum Unit unit, struct Resolution *resolution, const bool convert=true)
Set the current Resolution.
Private Attributes
int64_t m_data
Virtual time value, in the current unit.
Static Private Attributes
static MarkedTimes * g_markingTimes = 0
Record of outstanding Time objects which will need conversion when the resolution is set.
Friends
Time Abs (const Time &time)
Absolute value function for Time.
Time Max (const Time &timeA, const Time &timeB)
Max function for Time.
Time Min (const Time &timeA, const Time &timeB)
Min function for Time.
Comparison operators
bool operator== (const Time &lhs, const Time &rhs)
Equality operator for Time.
bool operator!= (const Time &lhs, const Time &rhs)
Inequality operator for Time.
bool operator<= (const Time &lhs, const Time &rhs)
Less than or equal operator for Time.
bool operator>= (const Time &lhs, const Time &rhs)
Greater than or equal operator for Time.
bool operator< (const Time &lhs, const Time &rhs)
Less than operator for Time.
bool operator> (const Time &lhs, const Time &rhs)
Greater than operator for Time.
bool operator< (const Time &time, const EventId &event)
Compare a Time to an EventId.
Arithmetic operators
Time operator+ (const Time &lhs, const Time &rhs)
Addition operator for Time.
Time operator- (const Time &lhs, const Time &rhs)
Subtraction operator for Time.
Time operator* (const Time &lhs, const int64x64_t &rhs)
Scale a Time by a numeric value.
Time operator* (const int64x64_t &lhs, const Time &rhs)
Scale a Time by a numeric value.
template<class T >
std::enable_if< std::is_integral< T >::value, Time >::type operator* (const Time &lhs, T rhs)
Scale a Time by an integer value.
template<class T >
std::enable_if< std::is_arithmetic< T >::value, Time >::type operator* (T lhs, const Time &rhs)
Limited to is_arithmetic matches for the T argument to reduce the chances of matching some arbitrary object type.
template<class T >
std::enable_if< std::is_floating_point< T >::value, Time >::type operator* (const Time &lhs, T rhs)
Scale a Time by an integer value.
int64x64_t operator/ (const Time &lhs, const Time &rhs)
Exact division, returning a dimensionless fixed point number.
Time operator/ (const Time &lhs, const int64x64_t &rhs)
Scale a Time by a numeric value.
template<class T >
std::enable_if< std::is_integral< T >::value, Time >::type operator/ (const Time &lhs, T rhs)
Divide a Time by an integer value.
template<class T >
std::enable_if< std::is_floating_point< T >::value, Time >::type operator/ (const Time &lhs, T rhs)
Divide a Time by an integer value.
Time operator% (const Time &lhs, const Time &rhs)
Remainder (modulus) from the quotient of two Times.
int64_t Div (const Time &lhs, const Time &rhs)
Integer quotient from dividing two Times.
Time Rem (const Time &lhs, const Time &rhs)
Remainder (modulus) from the quotient of two Times.
Compound assignment operators
Time & operator+= (Time &lhs, const Time &rhs)
Compound addition assignment for Time.
Time & operator-= (Time &lhs, const Time &rhs)
Compound subtraction assignment for Time.
Related Functions
(Note that these are not member functions.)
static bool g_TimeStaticInit = Time::StaticInit ()
Force static initialization order of Time in each compilation unit.
SystemMutex & GetMarkingMutex ()
Time TimeStep (uint64_t ts)
Scheduler interface.
Detailed Description
Simulation virtual time values and global simulation resolution.
This class defines all the classic C++ addition/subtraction operators: +, -, +=, -=; and all the classic comparison operators: ==, !=, <, >, <=, >=. It is thus easy to add, subtract, or compare Time objects.
For example:
Time t1 = Seconds (10.0);
Time t2 = Seconds (10.0);
Time t3 = t1;
t3 += t2;
You can also use the following non-member functions to manipulate any of these ns3::Time object:
Abs(Time)
Max(Time,Time)
Min(Time,Time)
This class also controls the resolution of the underlying time representation. The resolution is the smallest representable time interval. The default resolution is nanoseconds.
To change the resolution, use SetResolution(). All Time objects created before the call to SetResolution() will be updated to the new resolution. This can only be done once! (Tracking each Time object uses 4 pointers. For speed, once we convert the existing instances we discard the recording data structure and stop tracking new instances, so we have no way to do a second conversion.)
If you increase the global resolution, you also implicitly decrease the maximum simulation duration. The global simulation time is stored in a 64 bit integer whose interpretation will depend on the global resolution. Therefore the maximum possible duration of your simulation if you use picoseconds is 2^64 ps = 2^24 s = 7 months, whereas, had you used nanoseconds, you could have run for 584 years.
Definition at line 103 of file nstime.h.
Member Typedef Documentation
MarkedTimes
typedef std::set< Time * > ns3::Time::MarkedTimes private
Record all instances of Time, so we can rescale them when the resolution changes.
Internal:
We use a std::set so we can remove the record easily when ~Time() is called.
We don't use Ptr<Time>, because we would have to bloat every Time instance with SimpleRefCount<Time>.
Seems like this should be std::set< Time * const >, but Stack Overflow says otherwise, quoting the standard:
& sect;23.1/3 states that std::set key types must be assignable and copy constructable; clearly a const type will not be assignable.
Definition at line 655 of file nstime.h.
TracedCallback
typedef void(* ns3::Time::TracedCallback) (Time value)
TracedCallback signature for Time.
Parameters
[in] value Current value of Time
Definition at line 580 of file nstime.h.
Member Enumeration Documentation
Unit
enum ns3::Time::Unit
The unit to use to interpret a number representing time.
Enumerator
Y
year, 365 days
D
day, 24 hours
H
hour, 60 minutes
MIN
minute, 60 seconds
S
second
MS
millisecond
US
microsecond
NS
nanosecond
PS
picosecond
FS
femtosecond
LAST
marker for last normal value
AUTO
auto-scale output when using Time::As()
Definition at line 109 of file nstime.h.
Constructor & Destructor Documentation
Time() [1/12]
ns3::Time::Time () inline
Default constructor, with value 0.
Definition at line 136 of file nstime.h.
References g_markingTimes, and Mark().
Referenced by From(), FromInteger(), Max(), and Min().
Time() [2/12]
ns3::Time::Time (const Time & o) inline
Copy constructor.
Parameters
[in] o Time to copy
Definition at line 149 of file nstime.h.
References g_markingTimes, and Mark().
Time() [3/12]
ns3::Time::Time (Time && o) inline
Move constructor.
Parameters
[in] o Time from which take the data
Definition at line 163 of file nstime.h.
References g_markingTimes, and Mark().
Time() [4/12]
ns3::Time::Time (double v) inline explicit
Construct from a numeric value.
The current time resolution will be assumed as the unit.
Parameters
[in] v The value.
Definition at line 181 of file nstime.h.
References g_markingTimes, and Mark().
Time() [5/12]
ns3::Time::Time (int v) inline explicit
Construct from a numeric value.
The current time resolution will be assumed as the unit.
Parameters
[in] v The value.
Definition at line 189 of file nstime.h.
References g_markingTimes, and Mark().
Time() [6/12]
ns3::Time::Time (long int v) inline explicit
Construct from a numeric value.
The current time resolution will be assumed as the unit.
Parameters
[in] v The value.
Definition at line 197 of file nstime.h.
References g_markingTimes, and Mark().
Time() [7/12]
ns3::Time::Time (long long int v) inline explicit
Construct from a numeric value.
The current time resolution will be assumed as the unit.
Parameters
[in] v The value.
Definition at line 205 of file nstime.h.
References g_markingTimes, and Mark().
Time() [8/12]
ns3::Time::Time (unsigned int v) inline explicit
Construct from a numeric value.
The current time resolution will be assumed as the unit.
Parameters
[in] v The value.
Definition at line 213 of file nstime.h.
References g_markingTimes, and Mark().
Time() [9/12]
ns3::Time::Time (unsigned long int v) inline explicit
Construct from a numeric value.
The current time resolution will be assumed as the unit.
Parameters
[in] v The value.
Definition at line 221 of file nstime.h.
References g_markingTimes, and Mark().
Time() [10/12]
ns3::Time::Time (unsigned long long int v) inline explicit
Construct from a numeric value.
The current time resolution will be assumed as the unit.
Parameters
[in] v The value.
Definition at line 229 of file nstime.h.
References g_markingTimes, and Mark().
Time() [11/12]
ns3::Time::Time (const int64x64_t & v) inline explicit
Construct from a numeric value.
The current time resolution will be assumed as the unit.
Parameters
[in] v The value.
Definition at line 237 of file nstime.h.
References g_markingTimes, and Mark().
Time() [12/12]
ns3::Time::Time (const std::string & s) explicit
Construct Time object from common time expressions like "1ms".
Supported units include:
s (seconds)
ms (milliseconds)
us (microseconds)
ns (nanoseconds)
ps (picoseconds)
fs (femtoseconds)
min (minutes)
h (hours)
d (days)
y (years)
There can be no white space between the numerical portion and the units. Any otherwise malformed string causes a fatal error to occur.
Parameters
[in] s The string to parse into a Time
Definition at line 139 of file time.cc.
~Time()
ns3::Time::~Time () inline
Destructor.
Definition at line 289 of file nstime.h.
References Clear(), and g_markingTimes.
Member Function Documentation
As()
TimeWithUnit ns3::Time::As (const enum Unit unit = Time::AUTO) const
Attach a unit to a Time, to facilitate output in a specific unit.
For example,
Time t (3.14e9);  // Pi seconds
std::cout << t.As (Time::MS) << std::endl;
will print +3140.0ms
Parameters
[in] unit The unit to use.
Returns
The Time with embedded unit.
Definition at line 429 of file time.cc.
Referenced by ThreeGppHttpClientServerTestSuite::AddHttpObjectTestCase(), ns3::dsr::DsrRouteCache::AddRoute_Link(), ns3::AsciiLrWpanMacTransmitSinkWithContext(), ns3::AsciiLrWpanMacTransmitSinkWithoutContext(), ns3::LrWpanCsmaCa::CanProceed(), TimeInputOutputTestCase::CheckAs(), ns3::FlowMonitor::CheckForLostPackets(), ThreeGppHttpObjectTestCase::ClientRxDelayCallback(), ThreeGppHttpObjectTestCase::ClientRxRttCallback(), ns3::ThreeGppHttpServerTxBuffer::CloseAllSockets(), ns3::ThreeGppHttpServerTxBuffer::CloseSocket(), ns3::CobaltQueueDisc::CobaltShouldDrop(), BatteryLifetimeTest::ConstantLoadTest(), ns3::dsr::DsrRouteCache::DecStability(), ns3::DefaultTimePrinter(), ns3::A3RsrpHandoverAlgorithm::DoInitialize(), ns3::LteRlcSm::DoReceivePdu(), LteRadioLinkFailureTestCase::DoRun(), TimeInputOutputTestCase::DoRun(), LrWpanSlottedCsmacaTestCase::DoRun(), LteRlcAmE2eTestCase::DoRun(), LteHandoverDelayTestCase::EnbHandoverEndOkCallback(), EnbRrcTimeout(), ns3::UanMacCw::Enqueue(), ns3::ThreeGppHttpClient::EnterParsingTime(), ns3::ThreeGppHttpClient::EnterReadingTime(), ns3::dsr::DsrRouteCache::FindSameRoute(), ns3::LteUePhy::GenerateCqiRsrpRsrq(), ns3::ChannelAccessManager::GetBackoffEndFor(), ns3::ChannelAccessManager::GetBackoffStartFor(), ns3::CommandLineHelper::GetDefault< Time >(), ns3::WifiPhy::GetReceptionStatus(), ns3::dsdv::RoutingProtocol::GetSettlingTime(), ns3::LrWpanCsmaCa::GetTimeToNextSlot(), ns3::ShowProgress::GiveFeedback(), ns3::dsr::DsrRouteCache::IncStability(), ns3::aodv::RoutingTableEntry::Invalidate(), ns3::olsr::RoutingProtocol::LinkSensing(), OcbWifiMacTestCase::MacAssoc(), ns3::aodv::RoutingTable::MarkLinkAsUnidirectional(), JakesPropagationExample::Next(), NotifyConnectionEstablishedEnb(), NotifyConnectionEstablishedUe(), NotifyConnectionTimeoutUe(), NotifyHandoverEndOkEnb(), NotifyHandoverEndOkUe(), NotifyHandoverStartEnb(), NotifyHandoverStartUe(), NotifyRandomAccessErrorUe(), NotifyRaResponseTimeoutUe(), ns3::UanMacCw::NotifyTxStart(), NotifyViaTraceSource(), ns3::CoDelQueueDisc::OkToDrop(), ns3::operator<<(), ns3::LrWpanMac::PdDataConfirm(), ns3::LrWpanMac::PdDataIndication(), LrWpanCcaTestCase::PhyRxBegin(), LrWpanCcaTestCase::PhyRxDrop(), LrWpanCcaTestCase::PhyRxEnd(), OcbWifiMacTestCase::PhyRxOkTrace(), PhySyncDetection(), LrWpanCcaTestCase::PhyTxBegin(), LrWpanCcaTestCase::PhyTxEnd(), OcbWifiMacTestCase::PhyTxTrace(), LrWpanCcaTestCase::PlmeCcaConfirm(), ns3::dsdv::RoutingTableEntry::Print(), ns3::SeqTsEchoHeader::Print(), ns3::UanHeaderRcData::Print(), ns3::UanHeaderRcRts::Print(), ns3::UanHeaderRcCtsGlobal::Print(), ns3::UanHeaderRcCts::Print(), ns3::TcpTxItem::Print(), PrintCellInfo(), ns3::Ipv6RoutingHelper::PrintNdiscCache(), ns3::Ipv6RoutingHelper::PrintNdiscCacheEvery(), PrintReceivedRoutingPacket(), ns3::aodv::RoutingProtocol::PrintRoutingTable(), ns3::dsdv::RoutingProtocol::PrintRoutingTable(), ns3::Ipv4GlobalRouting::PrintRoutingTable(), ns3::Ipv4ListRouting::PrintRoutingTable(), ns3::Ipv4StaticRouting::PrintRoutingTable(), ns3::Ipv6ListRouting::PrintRoutingTable(), ns3::Ipv6StaticRouting::PrintRoutingTable(), ns3::Rip::PrintRoutingTable(), ns3::RipNg::PrintRoutingTable(), ns3::Ipv4NixVectorRouting::PrintRoutingTable(), ns3::olsr::RoutingProtocol::PrintRoutingTable(), ns3::UplinkSchedulerMBQoS::ProcessBandwidthRequest(), ns3::LrWpanCsmaCa::RandomBackoffDelay(), WaveNetDeviceExample::Receive(), ns3::V4Ping::Receive(), ns3::V4TraceRoute::Receive(), ns3::ThreeGppHttpServer::ReceivedDataCallback(), WaveNetDeviceExample::ReceiveVsa(), ns3::ThreeGppHttpServerTxBuffer::RecordNextServe(), ns3::dsdv::RoutingProtocol::RecvDsdv(), ns3::ThreeGppHttpServerTxBuffer::RemoveSocket(), ns3::UanMacRc::ScheduleData(), ns3::OnOffApplication::ScheduleNextTx(), ns3::aodv::RoutingProtocol::ScheduleRreqRetry(), ns3::dsr::DsrRouting::ScheduleRreqRetry(), ns3::OnOffApplication::ScheduleStartEvent(), ns3::OnOffApplication::ScheduleStopEvent(), ns3::MacLow::SendBlockAckAfterAmpdu(), ns3::aodv::RoutingProtocol::SendRerrMessage(), ns3::aodv::RoutingProtocol::SendRerrWhenNoRouteToForward(), ns3::ThreeGppHttpHeader::SetClientTs(), ns3::ThreeGppHttpVariables::SetEmbeddedObjectGenerationDelay(), ns3::PointToPointNetDevice::SetInterframeGap(), ns3::ThreeGppHttpVariables::SetMainObjectGenerationDelay(), ns3::ThreeGppHttpVariables::SetParsingTimeMean(), ns3::ThreeGppHttpVariables::SetReadingTimeMean(), ns3::ThreeGppHttpHeader::SetServerTs(), ns3::TimeProbe::SetValue(), ns3::TimeProbe::SetValueByPath(), ns3::dsr::DsrRouting::Start(), ns3::FlowMonitor::Start(), ns3::UanMacRcGw::StartCycle(), ns3::BaseStationNetDevice::StartDlSubFrame(), ns3::LrWpanMac::StartInactivePeriod(), ns3::SpectrumWifiPhy::StartRx(), ns3::UanMacCw::StartTimer(), ns3::WaveMacLow::StartTransmission(), ns3::BaseStationNetDevice::StartUlSubFrame(), StateChangeNotification(), ns3::FlowMonitor::Stop(), ns3::WifiPhy::SwitchMaybeToCcaBusy(), Throughput(), ns3::TimeProbe::TraceSink(), ns3::CsmaNetDevice::TransmitCompleteEvent(), ns3::CsmaChannel::TransmitEnd(), ns3::CsmaNetDevice::TransmitStart(), ns3::PointToPointNetDevice::TransmitStart(), LteHandoverDelayTestCase::UeHandoverEndOkCallback(), UeStateTransition(), and BatteryLifetimeTest::VariableLoadTest().
Clear()
void ns3::Time::Clear (Time *const time) static private
Remove a Time instance from the MarkedTimes, called by ~Time().
Parameters
[in] time The Time instance to remove.
Definition at line 354 of file time.cc.
References g_markingTimes, GetMarkingMutex(), NS_ASSERT, NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, and NS_LOG_WARN.
Referenced by ~Time().
ClearMarkedTimes()
void ns3::Time::ClearMarkedTimes () static private
Remove all MarkedTimes.
Internal:
Has to be visible to the Simulator class, hence the friending.
Internal:
We're called by Simulator::Run, which knows nothing about the mutex, so we need a critical section here.
It would seem natural to use this function at the end of ConvertTimes, but that function already has the mutex. Our SystemMutex throws a fatal error if we try to lock it more than once in the same thread (at least in the unix implementation), so calling this function from ConvertTimes is a bad idea.
Instead, we copy this body into ConvertTimes.
Definition at line 297 of file time.cc.
References g_markingTimes, GetMarkingMutex(), NS_LOG_FUNCTION_NOARGS, and NS_LOG_LOGIC.
Referenced by ns3::Simulator::Run().
Compare()
int ns3::Time::Compare (const Time & o) const inline
Compare this to another Time.
Parameters
[in] o The other Time
Returns
-1,0,+1 if this < o, this == o, or this > o
Definition at line 343 of file nstime.h.
References m_data.
ConvertTimes()
void ns3::Time::ConvertTimes (const enum Unit unit) static private
Convert existing Times to the new unit.
Parameters
[in] unit The Unit to convert existing Times to.
Definition at line 384 of file time.cc.
References g_markingTimes, GetMarkingMutex(), m_data, max, min, NS_ASSERT_MSG, NS_LOG_FUNCTION_NOARGS, NS_LOG_LOGIC, and ToInteger().
Referenced by SetResolution().
From() [1/2]
static Time ns3::Time::From (const int64x64_t & value) inline static
Create a Time in the current unit.
Parameters
[in] value The value of the new Time.
Returns
A Time with value in the current time unit.
Definition at line 451 of file nstime.h.
References Time().
Referenced by ns3::Days(), ns3::FemtoSeconds(), FromDouble(), ns3::Hours(), ns3::RttMeanDeviation::IntegerUpdate(), ns3::MicroSeconds(), ns3::MilliSeconds(), ns3::Minutes(), ns3::NanoSeconds(), ns3::PicoSeconds(), RoundTo(), ns3::Seconds(), and ns3::Years().
From() [2/2]
static Time ns3::Time::From (const int64x64_t & value, enum Unit unit) inline static
Create a Time equal to value in unit unit.
Parameters
[in] value The new Time value, expressed in unit
[in] unit The unit of value
Returns
The Time representing value in unit
Definition at line 485 of file nstime.h.
References Time(), ns3::Time::Information::fromMul, ns3::int64x64_t::MulByInvert(), PeekInformation(), and ns3::Time::Information::timeFrom.
FromDouble()
static Time ns3::Time::FromDouble (double value, enum Unit unit) inline static
Create a Time equal to value in unit unit.
Parameters
[in] value The new Time value, expressed in unit
[in] unit The unit of value
Returns
The Time representing value in unit
Definition at line 481 of file nstime.h.
References From().
Referenced by ns3::Days(), ns3::RttMeanDeviation::FloatingPointUpdate(), ns3::Hours(), ns3::Minutes(), ns3::TcpSocketBase::ReTxTimeout(), ns3::Seconds(), SetDefaultNsResolution(), and ns3::Years().
FromInteger()
static Time ns3::Time::FromInteger (uint64_t value, enum Unit unit) inline static
Create a Time equal to value in unit unit.
Parameters
[in] value The new Time value, expressed in unit
[in] unit The unit of value
Returns
The Time representing value in unit
Definition at line 468 of file nstime.h.
References Time(), ns3::Time::Information::factor, ns3::Time::Information::fromMul, and PeekInformation().
Referenced by ns3::FemtoSeconds(), ns3::MicroSeconds(), ns3::MilliSeconds(), ns3::NanoSeconds(), and ns3::PicoSeconds().
GetDays()
double ns3::Time::GetDays (void) const inline
Get an approximation of the time stored in this instance in the indicated unit.
Returns
An approximate value in the indicated unit.
Definition at line 368 of file nstime.h.
References D, and ToDouble().
GetDouble()
double ns3::Time::GetDouble (void) const inline
Get the raw time value, in the current resolution unit.
Returns
The raw time value
Definition at line 420 of file nstime.h.
References m_data.
Referenced by ns3::BsmApplication::StartApplication(), TimeSimpleTestCase::TestMultiplicationByDecimalTypes(), and ns3::TcpHtcp::UpdateBeta().
GetFemtoSeconds()
int64_t ns3::Time::GetFemtoSeconds (void) const inline
Get an approximation of the time stored in this instance in the indicated unit.
Returns
An approximate value in the indicated unit.
Definition at line 400 of file nstime.h.
References FS, and ToInteger().
Referenced by DataRateTestCase::CheckTimesEqual(), and ns3::WifiPhy::GetPayloadDuration().
GetHours()
double ns3::Time::GetHours (void) const inline
Get an approximation of the time stored in this instance in the indicated unit.
Returns
An approximate value in the indicated unit.
Definition at line 372 of file nstime.h.
References H, and ToDouble().
GetInteger()
int64_t ns3::Time::GetInteger (void) const inline
Get the raw time value, in the current resolution unit.
Returns
The raw time value
Definition at line 424 of file nstime.h.
References GetTimeStep().
Referenced by ns3::DistributedSimulatorImpl::CalculateLookAhead(), TimeSimpleTestCase::DoRun(), RttEstimatorTestCase::DoRun(), ns3::BsmApplication::GenerateWaveTraffic(), ns3::RttMeanDeviation::IntegerUpdate(), ns3::NullMessageMpiInterface::SendNullMessage(), ns3::GrantedTimeWindowMpiInterface::SendPacket(), ns3::NullMessageMpiInterface::SendPacket(), ns3::BsmApplication::StartApplication(), and anonymous_namespace{traced-value-callback-typedef-test-suite.cc}::TracedValueCbSink< Time >().
GetMicroSeconds()
int64_t ns3::Time::GetMicroSeconds (void) const inline
Get an approximation of the time stored in this instance in the indicated unit.
Returns
An approximate value in the indicated unit.
Definition at line 388 of file nstime.h.
References ToInteger(), and US.
Referenced by ns3::dot11s::IeBeaconTiming::BeaconIntervalToU16(), CheckT1QueueSize(), CheckT2QueueSize(), CoDelQueueDiscBasicDrop::Dequeue(), CoDelQueueDiscBasicMark::Dequeue(), LrWpanSlottedCsmacaTestCase::DoRun(), ns3::dot11s::HwmpProtocol::GetActivePathLifetime(), ns3::ApWifiMac::GetEdcaParameterSet(), ns3::NscTcpL4Protocol::gettime(), Ns3TcpInteroperabilityTestCase::Ipv4L3Tx(), Ns3TcpLossTestCase::Ipv4L3Tx(), Ns3TcpStateTestCase::Ipv4L3Tx(), PacketDequeue(), ns3::MinstrelWifiManager::PrintTable(), ns3::dot11s::HwmpProtocol::ReceivePreq(), ns3::MeshWifiInterfaceMac::SendBeacon(), ns3::dot11s::HwmpProtocol::SendProactivePreq(), ns3::dot11s::PeerLink::SetBeaconInformation(), ns3::ApWifiMac::SetBeaconInterval(), ns3::ApWifiMac::SetCfpMaxDuration(), ns3::dot11s::PeerLink::SetConfirmTimer(), ns3::dot11s::PeerLink::SetHoldingTimer(), ns3::WifiPpdu::SetPhyHeaders(), ns3::dot11s::PeerLink::SetRetryTimer(), ns3::Txop::SetTxopLimit(), ns3::MinstrelHtWifiManager::StatsDump(), ns3::dot11s::IeBeaconTiming::TimestampToU16(), ns3::MinstrelWifiManager::UpdateStats(), and ns3::PcapFileWrapper::Write().
GetMilliSeconds()
int64_t ns3::Time::GetMilliSeconds (void) const inline
Get an approximation of the time stored in this instance in the indicated unit.
Returns
An approximate value in the indicated unit.
Definition at line 384 of file nstime.h.
References MS, and ToInteger().
Referenced by ns3::aodv::RrepHeader::RrepHeader(), ns3::DefaultChannelScheduler::AssignExtendedAccess(), ns3::PieQueueDisc::CalculateP(), ns3::TcpLedbat::CongestionAvoidance(), ns3::TraceFadingLossModel::DoCalcRxPowerSpectralDensity(), ns3::PieQueueDisc::DoEnqueue(), ns3::A3RsrpHandoverAlgorithm::DoInitialize(), ns3::LteRlcAm::DoReportBufferStatus(), ns3::LteRlcTm::DoReportBufferStatus(), ns3::LteRlcUm::DoReportBufferStatus(), LteUeMeasurementsHandoverTestCase::DoRun(), LenaDataPhyErrorModelTestCase::DoRun(), LenaDlCtrlPhyErrorModelTestCase::DoRun(), ns3::TcpOptionTS::ElapsedTimeFromTsValue(), ns3::LteSpectrumPhy::EndRxData(), ns3::ChannelCoordinator::GetIntervalTime(), LteHandoverTargetTestCase::HandoverStartCallback(), ns3::TcpYeah::IncreaseWindow(), TcpVegasTest::IncreaseWindow(), ns3::TraceFadingLossModel::LoadTrace(), ChannelCoordinationTestCase::NotifyCchStartNow(), ChannelCoordinationTestCase::NotifyGuardStartNow(), ChannelCoordinationTestCase::NotifySchStartNow(), ns3::TcpOptionTS::NowToTsValue(), PingRtt(), ns3::TcpLp::PktsAcked(), ns3::TcpYeah::PktsAcked(), ns3::TcpHybla::RecalcParam(), TcpIllinoisTest::RecalcParam(), ns3::TcpIllinois::RecalcParam(), ns3::V4Ping::Receive(), ns3::LteUePhy::ReceiveLteControlMessageList(), LteUeMeasurementsPiecewiseTestCase1::RecvMeasurementReportCallback(), LteUeMeasurementsPiecewiseTestCase2::RecvMeasurementReportCallback(), LteUeMeasurementsPiecewiseTestCase3::RecvMeasurementReportCallback(), LteUeMeasurementsHandoverTestCase::RecvMeasurementReportCallback(), ns3::UanHeaderRcData::Serialize(), ns3::UanHeaderRcRts::Serialize(), ns3::UanHeaderRcCtsGlobal::Serialize(), ns3::UanHeaderRcCts::Serialize(), ns3::aodv::RrepHeader::SetHello(), ns3::aodv::RrepHeader::SetLifeTime(), ns3::ChannelCoordinator::StartChannelCoordination(), ns3::LteEnbPhy::StartSubFrame(), and ChannelCoordinationTestCase::TestIntervalAfter().
GetMinutes()
double ns3::Time::GetMinutes (void) const inline
Get an approximation of the time stored in this instance in the indicated unit.
Returns
An approximate value in the indicated unit.
Definition at line 376 of file nstime.h.
References MIN, and ToDouble().
GetNanoSeconds()
int64_t ns3::Time::GetNanoSeconds (void) const inline
Get an approximation of the time stored in this instance in the indicated unit.
Returns
An approximate value in the indicated unit.
Definition at line 392 of file nstime.h.
References NS, and ToInteger().
Referenced by ns3::AcousticModemEnergyModel::ChangeState(), ns3::CoDelGetTime(), ns3::ConvertGuardIntervalToNanoSeconds(), CobaltQueueDiscMarkTest::Dequeue(), ns3::LteRlcAm::DoReceivePdu(), ns3::LteRlcUm::DoReceivePdu(), ns3::LteRlcSm::DoReceivePdu(), ns3::LtePdcp::DoReceivePdu(), TimeSimpleTestCase::DoRun(), TimeInputOutputTestCase::DoRun(), OcbWifiMacTestCase::DoRun(), ns3::WifiPhy::EndOfMpdu(), anonymous_namespace{sample-show-progress.cc}::Hold::Event(), ns3::WifiPhy::GetPayloadDuration(), ns3::WifiPpdu::GetTxDuration(), SimulatorEventsTestCase::NowUs(), TimestampTag::Serialize(), ns3::PdcpTag::Serialize(), ns3::RlcTag::Serialize(), ns3::WifiMacHeader::SetDuration(), ns3::WifiPpdu::SetPhyHeaders(), ns3::CobaltQueueDisc::Time2CoDel(), ns3::CoDelQueueDisc::Time2CoDel(), ns3::BasicEnergyHarvester::UpdateHarvestedPower(), and ns3::PcapFileWrapper::Write().
GetPicoSeconds()
int64_t ns3::Time::GetPicoSeconds (void) const inline
Get an approximation of the time stored in this instance in the indicated unit.
Returns
An approximate value in the indicated unit.
Definition at line 396 of file nstime.h.
References PS, and ToInteger().
GetResolution()
enum Time::Unit ns3::Time::GetResolution (void) static
Returns
The current global resolution.
Definition at line 384 of file time.cc.
Referenced by ns3::DefaultTimePrinter(), and ns3::operator<<().
GetSeconds()
double ns3::Time::GetSeconds (void) const inline
Get an approximation of the time stored in this instance in the indicated unit.
Returns
An approximate value in the indicated unit.
Definition at line 380 of file nstime.h.
References S, and ToDouble().
Referenced by ns3::RttEstimator::RttEstimator(), ns3::dot11s::HwmpRtable::AddReactivePath(), ns3::AsciiPhyReceiveSinkWithContext(), ns3::AsciiPhyReceiveSinkWithoutContext(), ns3::AsciiPhyRxOkEvent(), ns3::AsciiPhyTransmitSinkWithContext(), ns3::AsciiPhyTransmitSinkWithoutContext(), ns3::AsciiPhyTxEvent(), ns3::WimaxHelper::AsciiRxEvent(), ns3::WimaxHelper::AsciiTxEvent(), ns3::RandomWalk2dOutdoorMobilityModel::AvoidBuilding(), BackoffTrace(), ns3::SQLiteOutput::Bind(), BytesInQueueTrace(), ns3::ThreeGppSpectrumPropagationLossModel::CalcBeamformingGain(), ns3::InterferenceHelper::CalculateChunkSuccessRate(), ns3::SimpleOfdmWimaxPhy::CalculateDataRate(), ns3::PieQueueDisc::CalculateP(), ns3::InterferenceHelper::CalculatePayloadChunkSuccessRate(), ns3::LiIonEnergySource::CalculateRemainingEnergy(), TcpYeahDecrementTest::CalculateSsThresh(), CalculateThroughput(), ns3::MinstrelHtWifiManager::CalculateThroughput(), ns3::LteUeRrc::CancelEnteringTrigger(), ns3::LteUeRrc::CancelLeavingTrigger(), ns3::LrWpanCsmaCa::CanProceed(), ns3::AcousticModemEnergyModel::ChangeState(), ns3::WifiRadioEnergyModel::ChangeState(), CheckQueueDiscSize(), CheckQueueSize(), CheckT1QueueSize(), CheckT2QueueSize(), ThreeGppHttpObjectTestCase::ClientRxDelayCallback(), ThreeGppHttpObjectTestCase::ClientRxRttCallback(), ns3::UanMacRcGw::ComputeAlpha(), ns3::UanMacRcGw::ComputeExpS(), ComputeSnr(), Ns2MobilityHelperTest::CourseChange(), WaypointMobilityModelNotifyTest::CourseChangeCallback(), ns3::AnimationInterface::CsmaPhyTxEndTrace(), CwndChange(), CwndTrace(), CwndTracer(), Ns3TcpLossTestCase::CwndTracer(), CwTrace(), LrWpanDataIfsTestCase::DataConfirm(), LrWpanDataIfsTestCase::DataReceived(), ns3::AsciiTraceHelper::DefaultDequeueSinkWithContext(), ns3::AsciiTraceHelper::DefaultDequeueSinkWithoutContext(), ns3::AsciiTraceHelper::DefaultDropSinkWithContext(), ns3::AsciiTraceHelper::DefaultDropSinkWithoutContext(), ns3::AsciiTraceHelper::DefaultEnqueueSinkWithContext(), ns3::AsciiTraceHelper::DefaultEnqueueSinkWithoutContext(), ns3::AsciiTraceHelper::DefaultReceiveSinkWithContext(), ns3::AsciiTraceHelper::DefaultReceiveSinkWithoutContext(), ns3::AnimationInterface::DevTxTrace(), ns3::MacStatsCalculator::DlScheduling(), ns3::TraceFadingLossModel::DoCalcRxPowerSpectralDensity(), ns3::CoDelQueueDisc::DoDequeue(), ns3::PieQueueDisc::DoDequeue(), ns3::PieQueueDisc::DoEnqueue(), ns3::SimpleOfdmWimaxPhy::DoGetFrameDurationCode(), ns3::SimpleOfdmWimaxPhy::DoGetNrBytes(), ns3::SimpleOfdmWimaxPhy::DoGetNrSymbols(), ns3::Rip::DoInitialize(), ns3::RipNg::DoInitialize(), ns3::dot11s::HwmpProtocol::DoInitialize(), ns3::MeshWifiInterfaceMac::DoInitialize(), TimeWithSignTestCase::DoRun(), TcpHyblaIncrementTest::DoRun(), TcpVenoTest::DoRun(), ns3::SimpleOfdmWimaxPhy::DoSetPhyParameters(), ns3::RandomWalk2dOutdoorMobilityModel::DoWalk(), ns3::GaussMarkovMobilityModel::DoWalk(), ns3::RandomWalk2dMobilityModel::DoWalk(), DropAtQueue(), ns3::PieQueueDisc::DropEarly(), DroppingStateTracer(), ns3::LteChunkProcessor::End(), ns3::BaseStationNetDevice::EndDlSubFrame(), ns3::BaseStationNetDevice::EndUlSubFrame(), ns3::TcpWestwood::EstimateBW(), ns3::LteChunkProcessor::EvaluateChunk(), ns3::ShannonSpectrumErrorModel::EvaluateChunk(), EveryDropTracer(), anonymous_namespace{sample-simulator.cc}::ExampleFunction(), ns3::SpectrumAnalyzer::GenerateReport(), ns3::TcpRateLinux::GenerateSample(), GenerateTraffic(), ns3::UanMacRcGw::GetExpPdk(), ns3::LrWpanCsmaCa::GetTimeToNextSlot(), ns3::SimpleDeviceEnergyModel::GetTotalEnergyConsumption(), ns3::WifiRadioEnergyModel::GetTotalEnergyConsumption(), ns3::JakesProcess::Oscillator::GetValueAt(), GoodputSampling(), anonymous_namespace{sample-simulator.cc}::MyModel::HandleEvent(), Ipv4DynamicGlobalRoutingTestCase::HandleRead(), ns3::TcpVegas::IncreaseWindow(), ns3::TcpVeno::IncreaseWindow(), ns3::TcpYeah::IncreaseWindow(), TcpYeahIncrementTest::IncreaseWindow(), InFlightTracer(), ns3::RedQueueDisc::InitializeParams(), ns3::SubscriberStationNetDevice::InitSubscriberStationNetDevice(), ns3::RraaWifiManager::InitThresholds(), ns3::RrpaaWifiManager::InitThresholds(), ns3::Ipv4L3ProtocolDropSinkWithContext(), ns3::Ipv4L3ProtocolDropSinkWithoutContext(), ns3::Ipv4L3ProtocolRxSinkWithContext(), ns3::Ipv4L3ProtocolRxSinkWithoutContext(), ns3::Ipv4L3ProtocolTxSinkWithContext(), ns3::Ipv4L3ProtocolTxSinkWithoutContext(), ns3::Ipv6L3ProtocolDropSinkWithContext(), ns3::Ipv6L3ProtocolDropSinkWithoutContext(), ns3::Ipv6L3ProtocolRxSinkWithContext(), ns3::Ipv6L3ProtocolRxSinkWithoutContext(), ns3::Ipv6L3ProtocolTxSinkWithContext(), ns3::Ipv6L3ProtocolTxSinkWithoutContext(), ns3::ArpCache::Entry::IsExpired(), LimitsTrace(), MacRxTrace(), LrWpanDataIfsTestCase::MacState(), MacTxTrace(), ns3::LrWpanMac::McpsDataRequest(), modify(), ns3::TcpSocketBase::NewAck(), NextRxTracer(), NextTxTracer(), ns3::operator*(), ns3::operator<<(), PacingRateTracer(), PacketDequeue(), PhyStateTrace(), PhyTxTrace(), ns3::TcpHtcp::PktsAcked(), ns3::Ipv4RoutingHelper::PrintArpCache(), ns3::Ipv4RoutingHelper::PrintArpCacheEvery(), PrintFairness(), IpAddressHelper::PrintIpAddresses(), PrintProgress(), PrintReceivedPacket(), PrintThroughput(), ns3::AnimationInterface::PurgePendingPackets(), ns3::LrWpanCsmaCa::RandomBackoffDelay(), anonymous_namespace{sample-simulator.cc}::RandomFunction(), ns3::RandomWalk2dOutdoorMobilityModel::Rebound(), RemainingEnergyTrace(), anonymous_namespace{sample-log-time-format.cc}::ReplacementTimePrinter(), ns3::MeshHelper::Report(), ns3::dot11s::HwmpProtocol::Report(), ns3::MeshWifiInterfaceMac::Report(), ns3::dot11s::PeerLink::Report(), ns3::flame::FlameProtocol::Report(), ns3::PhyStatsCalculator::ReportCurrentCellRsrpSinr(), ns3::PhyStatsCalculator::ReportInterference(), ns3::FlowMonitor::ReportLastRx(), ns3::PhyStatsCalculator::ReportUeSinr(), SampleEmitter::Reschedule(), NetAnimExperiment::ResetData(), Experiment::ResetData(), ns3::TcpSocketBase::ReTxTimeout(), TcpBytesInFlightTest::RTOExpired(), RtoTracer(), TcpRttEstimationTest::RttTrace(), RttTracer(), RxEvent(), RxTracer(), ns3::DhcpServer::SendAck(), ns3::TcpSocketBase::SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), ns3::TcpSocketBase::SendEmptyPacket(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), ns3::DhcpServer::SendOffer(), ns3::TcpGeneralTest::SendPacket(), ns3::Rip::SendTriggeredRouteUpdate(), ns3::RipNg::SendTriggeredRouteUpdate(), ns3::Rip::SendUnsolicitedRouteUpdate(), ns3::RipNg::SendUnsolicitedRouteUpdate(), ns3::dot11s::PeerLink::SetBeaconInformation(), ns3::SimpleDeviceEnergyModel::SetCurrentA(), ns3::ThreeGppHttpVariables::SetEmbeddedObjectGenerationDelay(), ns3::olsr::MessageHeader::Hello::SetHTime(), ns3::ThreeGppHttpVariables::SetMainObjectGenerationDelay(), ns3::ThreeGppHttpVariables::SetParsingTimeMean(), ns3::ThreeGppHttpVariables::SetReadingTimeMean(), ns3::DhcpHeader::SetTime(), NodeStatistics::SetupPhy(), ns3::TimeProbe::SetValue(), ns3::olsr::MessageHeader::SetVTime(), showPosition(), SocketPrinter(), SocketSendTrace(), SsThreshTracer(), ns3::UanMacRcGw::StartCycle(), ns3::BaseStationNetDevice::StartDlSubFrame(), Ns3TcpLossTestCase::StartFlow(), Ns3TcpStateTestCase::StartFlow(), ns3::BaseStationNetDevice::StartFrame(), ns3::BaseStationNetDevice::StartUlSubFrame(), NodeStatistics::StateCallback(), TcPacketsInQueue(), TestDeterministicByTime(), Throughput(), TraceDrop(), TraceDropsFrequency(), TraceFirstCwnd(), TraceFirstDctcp(), TraceFirstRtt(), TraceFirstThroughput(), TraceMark(), TraceMarksFrequency(), TraceN0Cwnd(), TraceN0Rtt(), TraceN0Throughput(), TraceN1Cwnd(), TraceN1Rtt(), TraceN1Throughput(), TracePingRtt(), TraceQueueDrop(), TraceQueueLength(), TraceQueueMark(), TraceSecondCwnd(), TraceSecondDctcp(), TraceSecondRtt(), TraceSecondThroughput(), ns3::TimeProbe::TraceSink(), TcpPacingTest::Tx(), TxTracer(), ns3::MacStatsCalculator::UlScheduling(), ns3::TcpCubic::Update(), ns3::ConstantVelocityHelper::Update(), ns3::TcpHtcp::UpdateAlpha(), ns3::TcpLedbat::UpdateBaseDelay(), TcpPacingTest::UpdateExpectedInterval(), ns3::BasicEnergyHarvester::UpdateHarvestedPower(), ns3::TcpSocketBase::UpdatePacingRate(), ns3::WriteAveragePowerSpectralDensityReport(), ns3::RadioBearerStatsCalculator::WriteDlResults(), ns3::RadioBearerStatsCalculator::WriteUlResults(), Ns3TcpLossTestCase::WriteUntilBufferFull(), and Ns3TcpStateTestCase::WriteUntilBufferFull().
GetTimeStep()
int64_t ns3::Time::GetTimeStep (void) const inline
Get the raw time value, in the current resolution unit.
Returns
The raw time value
Definition at line 416 of file nstime.h.
References m_data.
Referenced by ns3::LrWpanPhy::EndEd(), ns3::LrWpanPhy::EndRx(), ns3::WaveformGenerator::GenerateWaveform(), GetInteger(), ns3::Radvd::HandleRead(), ns3::Synchronizer::NanosecondToTimeStep(), ns3::DistributedSimulatorImpl::NextTs(), ns3::OmnetDataOutput::OmnetOutputCallback::OutputSingleton(), ns3::SqliteDataOutput::SqliteOutputCallback::OutputSingleton(), ns3::RealtimeSimulatorImpl::ProcessOneEvent(), ns3::DefaultSimulatorImpl::Schedule(), ns3::RealtimeSimulatorImpl::Schedule(), ns3::DistributedSimulatorImpl::Schedule(), ns3::NullMessageSimulatorImpl::Schedule(), ns3::RealtimeSimulatorImpl::ScheduleRealtimeWithContext(), ns3::DefaultSimulatorImpl::ScheduleWithContext(), ns3::RealtimeSimulatorImpl::ScheduleWithContext(), ns3::DistributedSimulatorImpl::ScheduleWithContext(), ns3::NullMessageSimulatorImpl::ScheduleWithContext(), ns3::NullMessageMpiInterface::SendNullMessage(), ns3::GrantedTimeWindowMpiInterface::SendPacket(), ns3::NullMessageMpiInterface::SendPacket(), AnnexC_TestCase::SendPacket(), ChannelAccessTestCase::SendX(), ns3::SeqTsEchoHeader::Serialize(), ns3::DelayJitterEstimationTimestampTag::Serialize(), ns3::AmpduTag::Serialize(), ns3::ThreeGppHttpHeader::SetClientTs(), ns3::ThreeGppHttpHeader::SetServerTs(), ns3::LrWpanPhy::StartRx(), ns3::DefaultSimulatorImpl::Stop(), ns3::DistributedSimulatorImpl::Stop(), ns3::NullMessageSimulatorImpl::Stop(), TimeSimpleTestCase::TestDivisionByIntegerTypes(), TimeSimpleTestCase::TestMultiplicationByIntegerTypes(), and ns3::DesMetrics::TraceWithContext().
GetYears()
double ns3::Time::GetYears (void) const inline
Get an approximation of the time stored in this instance in the indicated unit.
Returns
An approximate value in the indicated unit.
Definition at line 364 of file nstime.h.
References ToDouble(), and Y.
IsNegative()
bool ns3::Time::IsNegative (void) const inline
Exactly equivalent to t <= 0.
Returns
true if the time is negative or zero, false otherwise.
Definition at line 309 of file nstime.h.
References m_data.
Referenced by ns3::MacLow::IsWithinSizeAndTimeLimits().
IsPositive()
bool ns3::Time::IsPositive (void) const inline
Exactly equivalent to t >= 0.
Returns
true if the time is positive or zero, false otherwise.
Definition at line 317 of file nstime.h.
References m_data.
Referenced by ThreeGppHttpObjectTestCase::ThreeGppHttpObjectTestCase(), ns3::BasicEnergySource::CalculateRemainingEnergy(), ns3::WifiRadioEnergyModel::ChangeState(), ns3::MacLow::GetRemainingCfpDuration(), ns3::WifiRadioEnergyModel::GetTotalEnergyConsumption(), ns3::TcpLedbat::PktsAcked(), ns3::DefaultSimulatorImpl::Schedule(), ns3::RealtimeSimulatorImpl::Schedule(), ns3::DistributedSimulatorImpl::Schedule(), ns3::NullMessageSimulatorImpl::Schedule(), ns3::NullMessageSimulatorImpl::ScheduleWithContext(), ns3::MacLow::SendAckAfterData(), ns3::MacLow::SendBlockAckResponse(), ns3::MacLow::SendCtsAfterRts(), ns3::MacLow::SendDataAfterCts(), and ns3::MacLow::StartTransmission().
IsStrictlyNegative()
bool ns3::Time::IsStrictlyNegative (void) const inline
Exactly equivalent to t < 0.
Returns
true if the time is strictly negative, false otherwise.
Definition at line 325 of file nstime.h.
References m_data.
Referenced by ns3::QosTxop::GetTxopRemaining().
IsStrictlyPositive()
bool ns3::Time::IsStrictlyPositive (void) const inline
Exactly equivalent to t > 0.
Returns
true if the time is strictly positive, false otherwise.
Definition at line 333 of file nstime.h.
References m_data.
Referenced by ns3::WifiPhy::CalculateTxDuration(), ns3::MacLow::IsCfPeriod(), ns3::MacLow::IsWithinSizeAndTimeLimits(), ns3::WifiPhyStateHelper::LogPreviousIdleAndCcaBusyStates(), ns3::MacLow::ReceiveOk(), ns3::Ipv4L3Protocol::RemoveDuplicates(), ns3::MacLow::RxStartIndication(), ns3::MacLow::StartDataTxTimers(), ns3::WifiPhy::StartReceivePayload(), ns3::MacLow::StartTransmission(), ns3::Ipv4L3Protocol::UpdateDuplicate(), and ns3::ConstantWifiAckPolicySelector::UpdateTxParams().
IsZero()
bool ns3::Time::IsZero (void) const inline
Exactly equivalent to t == 0.
Returns
true if the time is zero, false otherwise.
Definition at line 301 of file nstime.h.
References m_data.
Referenced by ns3::InterferenceHelper::CalculateChunkSuccessRate(), ns3::InterferenceHelper::CalculatePayloadChunkSuccessRate(), ns3::ThreeGppChannelModel::ChannelMatrixNeedsUpdate(), ns3::TcpWestwood::EstimateBW(), ns3::TcpSocketBase::EstimateRtt(), ns3::ThreeGppChannelConditionModel::GetChannelCondition(), ns3::QosTxop::GetTxopFragmentSize(), ns3::WifiPhy::MaybeCcaBusyDuration(), ns3::LrWpanMac::PdDataConfirm(), ns3::TcpWestwood::PktsAcked(), ns3::TcpIllinois::PktsAcked(), ns3::TcpLp::PktsAcked(), ns3::TcpVegas::PktsAcked(), ns3::TcpVeno::PktsAcked(), ns3::TcpYeah::PktsAcked(), ns3::ThreeGppHttpClient::ReceiveEmbeddedObject(), ns3::ThreeGppHttpClient::ReceiveMainObject(), ns3::MacLow::RxStartIndication(), ns3::WifiPhy::ScheduleEndOfMpdus(), ns3::UanPdp::SumTapsFromMaxC(), ns3::UanPdp::SumTapsFromMaxNc(), and ns3::WifiPhy::SwitchMaybeToCcaBusy().
Mark()
void ns3::Time::Mark (Time *const time) static private
Record a Time instance with the MarkedTimes.
Parameters
[in] time The Time instance to record.
Definition at line 328 of file time.cc.
References g_markingTimes, GetMarkingMutex(), NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, and NS_LOG_WARN.
Referenced by Time(), and SetDefaultNsResolution().
Max()
static Time ns3::Time::Max () inline static
Maximum representable Time Not to be confused with Max(Time,Time).
Returns
the maximum representable Time.
Definition at line 283 of file nstime.h.
References Time(), and max.
Referenced by ns3::FqCoDelQueueDisc::CheckConfig(), ns3::PieQueueDisc::DoEnqueue(), ns3::TcpVegas::EnableVegas(), ns3::TcpVeno::EnableVeno(), ns3::TcpYeah::EnableYeah(), ns3::TcpHtcp::GetSsThresh(), ns3::ArpCache::Entry::GetTimeout(), ns3::CoDelQueueDisc::GetTypeId(), ns3::FqCoDelQueueDisc::GetTypeId(), ns3::PieQueueDisc::GetTypeId(), ns3::TcpVegas::IncreaseWindow(), ns3::TcpVeno::IncreaseWindow(), ns3::TcpYeah::IncreaseWindow(), ns3::MakeTimeChecker(), and ns3::TcpRateLinux::SkbDelivered().
Min()
static Time ns3::Time::Min () inline static
Minimum representable Time Not to be confused with Min(Time,Time).
Returns
the minimum representable Time.
Definition at line 274 of file nstime.h.
References Time(), and min.
Referenced by ns3::TcpCubic::CubicReset(), ns3::TcpBic::GetSsThresh(), ns3::TcpCubic::GetSsThresh(), ns3::TcpHtcp::GetSsThresh(), ns3::TcpCubic::HystartReset(), ns3::TcpCubic::HystartUpdate(), ns3::MacLow::IsWithinSizeAndTimeLimits(), ns3::MakeTimeChecker(), ns3::QosTxop::NotifyAccessGranted(), ns3::TcpCubic::PktsAcked(), ns3::MacLow::StartTransmission(), ns3::TcpBic::Update(), and ns3::TcpCubic::Update().
operator=()
Time& ns3::Time::operator= (const Time & o) inline
Assignment operator.
Parameters
[in] o Time to assign.
Returns
The Time.
Definition at line 130 of file nstime.h.
References m_data.
PeekInformation()
static struct Information* ns3::Time::PeekInformation (enum Unit timeUnit) inline static private
Get the Information record for timeUnit for the current Resolution.
Parameters
[in] timeUnit The Unit to get Information for
Returns
The Information for timeUnit
Definition at line 615 of file nstime.h.
References ns3::Time::Resolution::info, and PeekResolution().
Referenced by From(), FromInteger(), To(), and ToInteger().
PeekResolution()
static struct Resolution* ns3::Time::PeekResolution (void) inline static private
Get the current Resolution.
Returns
A pointer to the current Resolution
Definition at line 604 of file nstime.h.
References SetDefaultNsResolution().
Referenced by PeekInformation(), and SetResolution().
RoundTo()
Time ns3::Time::RoundTo (enum Unit unit) const inline
Round a Time to a specific unit.
Rounding is to nearest integer.
Returns
The Time rounded to the specific unit.
Definition at line 555 of file nstime.h.
References From(), and To().
Referenced by ns3::UanHeaderRcData::Serialize(), ns3::UanHeaderRcRts::Serialize(), ns3::UanHeaderRcCtsGlobal::Serialize(), and ns3::UanHeaderRcCts::Serialize().
SetDefaultNsResolution()
struct Time::Resolution ns3::Time::SetDefaultNsResolution (void) static private
Set the default resolution.
Returns
The Resolution object for the default resolution.
Definition at line 139 of file time.cc.
References D, FromDouble(), FS, g_markingTimes, H, Mark(), MIN, MS, sample-rng-plot::n, NS, NS_ABORT_MSG, NS_LOG_FUNCTION, PS, S, US, and Y.
Referenced by PeekResolution().
SetResolution() [1/2]
void ns3::Time::SetResolution (enum Unit resolution) static
Parameters
[in] resolution The new resolution to use
Change the global resolution used to convert all user-provided time values in Time objects and Time objects in user-expected time units.
Definition at line 223 of file time.cc.
References NS_LOG_FUNCTION, and PeekResolution().
SetResolution() [2/2]
void ns3::Time::SetResolution (enum Unit unit, struct Resolution * resolution, const bool convert = true) static private
Set the current Resolution.
Parameters
[in] unit The unit to use as the new resolution.
[in,out] resolution The Resolution record to update.
[in] convert Whether to convert existing Time objects to the new resolution.
Definition at line 232 of file time.cc.
References ConvertTimes(), ns3::Time::Information::factor, ns3::Time::Information::fromMul, ns3::Time::Resolution::info, ns3::int64x64_t::Invert(), LAST, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Time::Information::timeFrom, ns3::Time::Information::timeTo, ns3::Time::Information::toMul, ns3::Time::Resolution::unit, ns3::anonymous_namespace{time.cc}::UNIT_COEFF, and ns3::anonymous_namespace{time.cc}::UNIT_POWER.
StaticInit()
bool ns3::Time::StaticInit () static
Function to force static initialization of Time.
Returns
true on the first call
Definition at line 106 of file time.cc.
References g_markingTimes, GetMarkingMutex(), and NS_LOG_ERROR.
To()
int64x64_t ns3::Time::To (enum Unit unit) const inline
Get the Time value expressed in a particular unit.
Parameters
[in] unit The desired unit
Returns
The Time expressed in unit
Definition at line 534 of file nstime.h.
References m_data, ns3::int64x64_t::MulByInvert(), PeekInformation(), ns3::Time::Information::timeTo, and ns3::Time::Information::toMul.
Referenced by ns3::OnOffApplication::CancelEvents(), RoundTo(), and ToDouble().
ToDouble()
double ns3::Time::ToDouble (enum Unit unit) const inline
Get the Time value expressed in a particular unit.
Parameters
[in] unit The desired unit
Returns
The Time expressed in unit
Definition at line 530 of file nstime.h.
References ns3::int64x64_t::GetDouble(), and To().
Referenced by ns3::RttMeanDeviation::FloatingPointUpdate(), GetDays(), GetHours(), GetMinutes(), GetSeconds(), GetYears(), Ipv4DeduplicationTest::MakeName(), ns3::MacLow::RxStartIndication(), and SojournTimeTrace().
ToInteger()
int64_t ns3::Time::ToInteger (enum Unit unit) const inline
Get the Time value expressed in a particular unit.
Parameters
[in] unit The desired unit
Returns
The Time expressed in unit
Definition at line 516 of file nstime.h.
References ns3::Time::Information::factor, m_data, PeekInformation(), and ns3::Time::Information::toMul.
Referenced by ConvertTimes(), GetFemtoSeconds(), GetMicroSeconds(), GetMilliSeconds(), GetNanoSeconds(), and GetPicoSeconds().
Friends And Related Function Documentation
Abs
Time Abs (const Time & time) friend
Absolute value function for Time.
Parameters
[in] time The input value
Returns
The absolute value of the input value
Parameters
[in] time The Time value
Returns
The absolute value of the input.
Definition at line 1181 of file nstime.h.
Div
int64_t Div (const Time & lhs, const Time & rhs) friend
Integer quotient from dividing two Times.
This is the same as the "normal" C++ integer division, which truncates (discarding any remainder).
As usual, if ta, and tb are both Times
ta  ==  tb * Div (ta, tb) + Rem (ta, tb);
ta  ==  tb * (ta / tb).GetHigh()  + ta % tb;
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
The integer portion of lhs / rhs.
See also
Rem()
Definition at line 1132 of file nstime.h.
g_TimeStaticInit
bool g_TimeStaticInit = Time::StaticInit () related
Force static initialization order of Time in each compilation unit.
This is internal to the Time implementation.
Definition at line 822 of file nstime.h.
GetMarkingMutex()
SystemMutex & GetMarkingMutex () related
Internal:
Get mutex for critical sections around modification of Time::g_markingTimes
Returns
The static mutex to control access to Time::g_markingTimes.
Definition at line 97 of file time.cc.
Referenced by Clear(), ClearMarkedTimes(), ConvertTimes(), Mark(), and StaticInit().
Max
Time Max (const Time & timeA, const Time & timeB) friend
Max function for Time.
Parameters
[in] timeA The first value
[in] timeB The seconds value
Returns
The max of the two input values.
Parameters
[in] timeA The first value
[in] timeB The second value
Returns
The larger of the two operands.
Definition at line 1191 of file nstime.h.
Min
Time Min (const Time & timeA, const Time & timeB) friend
Min function for Time.
Parameters
[in] timeA The first value
[in] timeB The seconds value
Returns
The min of the two input values.
Parameters
[in] timeA The first value
[in] timeB The second value
Returns
The smaller of the two operands.
Definition at line 1201 of file nstime.h.
operator!=
bool operator!= (const Time & lhs, const Time & rhs) friend
Inequality operator for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
true if the two input values not are equal.
Definition at line 842 of file nstime.h.
operator%
Time operator% (const Time & lhs, const Time & rhs) friend
Remainder (modulus) from the quotient of two Times.
This is exactly the same function as Rem()
Rem (ta, tb)  ==  ta % tb;
See also
Div()
Parameters
[in] lhs The first time value
[in] rhs The second time value
Returns
The remainder of lhs / rhs.
Definition at line 1107 of file nstime.h.
operator* [1/5]
Time operator* (const int64x64_t & lhs, const Time & rhs) friend
Scale a Time by a numeric value.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
The Time scaled by the other operand.
Definition at line 959 of file nstime.h.
operator* [2/5]
Time operator* (const Time & lhs, const int64x64_t & rhs) friend
Scale a Time by a numeric value.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
The Time scaled by the other operand.
Definition at line 946 of file nstime.h.
operator* [3/5]
template<class T > std::enable_if<std::is_integral<T>::value, Time>::type operator* (const Time & lhs, T rhs) friend
Scale a Time by an integer value.
Template Parameters
T Integer data type (int, long, etc.)
Parameters
[in] lhs The Time instance to scale
[in] rhs The scale value
Returns
A new Time instance containing the scaled value
Template Parameters
T Floating point data type (float, double, etc.)
Parameters
[in] lhs The scale value
[in] rhs The Time instance to scale
Returns
A new Time instance containing the scaled value
Definition at line 975 of file nstime.h.
operator* [4/5]
template<class T > std::enable_if<std::is_floating_point<T>::value, Time>::type operator* (const Time & lhs, T rhs) friend
Scale a Time by an integer value.
Template Parameters
T Integer data type (int, long, etc.)
Parameters
[in] lhs The Time instance to scale
[in] rhs The scale value
Returns
A new Time instance containing the scaled value
Scale a Time by an integer value.
Template Parameters
T Floating point data type (float, double, etc.)
Parameters
[in] lhs The scale value
[in] rhs The Time instance to scale
Returns
A new Time instance containing the scaled value
Definition at line 975 of file nstime.h.
operator* [5/5]
template<class T > std::enable_if<std::is_arithmetic<T>::value, Time>::type operator* (T lhs, const Time & rhs) friend
Limited to is_arithmetic matches for the T argument to reduce the chances of matching some arbitrary object type.
This overload handles the case where the scale value comes before the Time value. It swaps the arguments so that the Time argument comes first and calls the appropriate overload of operator*
Template Parameters
T Arithmetic data type (int, long, float, etc.)
Parameters
[in] lhs The scale value
[in] rhs The Time instance to scale
Returns
A new Time instance containing the scaled value
Definition at line 998 of file nstime.h.
operator+
Time operator+ (const Time & lhs, const Time & rhs) friend
Addition operator for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
The sum of the two input values.
Definition at line 924 of file nstime.h.
operator+=
Time& operator+= (Time & lhs, const Time & rhs) friend
Compound addition assignment for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
The sum of the two inputs.
Definition at line 1160 of file nstime.h.
operator-
Time operator- (const Time & lhs, const Time & rhs) friend
Subtraction operator for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
The difference of the two input values.
Definition at line 934 of file nstime.h.
operator-=
Time& operator-= (Time & lhs, const Time & rhs) friend
Compound subtraction assignment for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
The difference of the two operands.
Definition at line 1171 of file nstime.h.
operator/ [1/4]
Time operator/ (const Time & lhs, const int64x64_t & rhs) friend
Scale a Time by a numeric value.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
The Time divided by the scalar operand.
Definition at line 1052 of file nstime.h.
operator/ [2/4]
int64x64_t operator/ (const Time & lhs, const Time & rhs) friend
Exact division, returning a dimensionless fixed point number.
This can be truncated to integer, or converted to double (with loss of precison). Assuming ta and tb are Times:
int64x64_t ratio = ta / tb;
int64_t i = ratio.GetHigh ();      // Get just the integer part, resulting in truncation
double ratioD = double (ratio);    // Convert to double, with loss of precision
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
The exact ratio of the two operands.
Definition at line 1038 of file nstime.h.
operator/ [3/4]
template<class T > std::enable_if<std::is_integral<T>::value, Time>::type operator/ (const Time & lhs, T rhs) friend
Divide a Time by an integer value.
Template Parameters
T Integer data type (int, long, etc.)
Parameters
[in] lhs The Time instance to scale
[in] rhs The scale value
Returns
A new Time instance containing the scaled value
Template Parameters
T Floating point data type (float, double, etc.)
Parameters
[in] lhs The Time instance to scale
[in] rhs The scale value
Returns
A new Time instance containing the scaled value
Definition at line 1070 of file nstime.h.
operator/ [4/4]
template<class T > std::enable_if<std::is_floating_point<T>::value, Time>::type operator/ (const Time & lhs, T rhs) friend
Divide a Time by an integer value.
Template Parameters
T Integer data type (int, long, etc.)
Parameters
[in] lhs The Time instance to scale
[in] rhs The scale value
Returns
A new Time instance containing the scaled value
Divide a Time by an integer value.
Template Parameters
T Floating point data type (float, double, etc.)
Parameters
[in] lhs The Time instance to scale
[in] rhs The scale value
Returns
A new Time instance containing the scaled value
Definition at line 1070 of file nstime.h.
operator< [1/2]
bool operator< (const Time & lhs, const Time & rhs) friend
Less than operator for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
true if the first input value is less than the second input value.
Definition at line 874 of file nstime.h.
operator< [2/2]
bool operator< (const Time & time, const EventId & event) friend
Compare a Time to an EventId.
This is useful when you have cached a previously scheduled event:
m_event = Schedule (...);
and later you want to know the relationship between that event and some other Time when:
if (when < m_event) ...
Parameters
[in] time The Time operand.
[in] event The EventId
Returns
true if time is before (less than) the time stamp of the EventId.
Definition at line 907 of file nstime.h.
operator<=
bool operator<= (const Time & lhs, const Time & rhs) friend
Less than or equal operator for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
true if the first input value is less than or equal to the second input value.
Definition at line 852 of file nstime.h.
operator==
bool operator== (const Time & lhs, const Time & rhs) friend
Equality operator for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
true if the two input values are equal.
Definition at line 831 of file nstime.h.
operator>
bool operator> (const Time & lhs, const Time & rhs) friend
Greater than operator for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
true if the first input value is greater than the second input value.
Definition at line 886 of file nstime.h.
operator>=
bool operator>= (const Time & lhs, const Time & rhs) friend
Greater than or equal operator for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
true if the first input value is greater than or equal to the second input value.
Definition at line 864 of file nstime.h.
Rem
Time Rem (const Time & lhs, const Time & rhs) friend
Remainder (modulus) from the quotient of two Times.
This is exactly the same function as operator%()
Rem (ta, tb)  ==  ta % tb;
See also
Div()
Parameters
[in] lhs The first time value
[in] rhs The second time value
Returns
The result of the remainder of the first input / second input value.
Definition at line 1149 of file nstime.h.
TimeStep()
Time TimeStep (uint64_t ts) related
Scheduler interface.
Note
This is internal to the Time implementation.
Parameters
[in] ts The time value, in the current unit.
Returns
A Time.
Definition at line 1348 of file nstime.h.
Member Data Documentation
g_markingTimes
Time::MarkedTimes * ns3::Time::g_markingTimes = 0 static private
Record of outstanding Time objects which will need conversion when the resolution is set.
Internal:
Use a classic static variable so we can check in Time ctors without a function call.
We'd really like to initialize this here, but we don't want to require C++0x, so we init in time.cc. To ensure that happens before first use, we add a call to StaticInit (below) to every compilation unit which includes nstime.h.
Definition at line 670 of file nstime.h.
Referenced by Time(), ~Time(), Clear(), ClearMarkedTimes(), ConvertTimes(), Mark(), SetDefaultNsResolution(), and StaticInit().
m_data
int64_t ns3::Time::m_data private
Virtual time value, in the current unit.
Definition at line 801 of file nstime.h.
Referenced by Compare(), ConvertTimes(), GetDouble(), GetTimeStep(), IsNegative(), IsPositive(), IsStrictlyNegative(), IsStrictlyPositive(), IsZero(), operator=(), To(), and ToInteger().
The documentation for this class was generated from the following files:
src/core/model/nstime.h
src/core/model/time.cc