ns-3: ns3::PacketSocketClient Class Reference
ns3::PacketSocketClient Class Reference
Network » Socket
A simple client.
#include "packet-socket-client.h"
Public Member Functions
PacketSocketClient ()
virtual ~PacketSocketClient ()
uint8_t GetPriority (void) const
Query the priority value of this socket.
void SetRemote (PacketSocketAddress addr)
set the remote address and protocol to be used
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Application
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void Send (void)
Send a packet.
void SetPriority (uint8_t priority)
Manually set the socket priority.
virtual void StartApplication (void)
Application specific startup code.
virtual void StopApplication (void)
Application specific shutdown code.
Private Attributes
Time m_interval
Packet inter-send time.
uint32_t m_maxPackets
Maximum number of packets the application will send.
PacketSocketAddress m_peerAddress
Remote peer address.
bool m_peerAddressSet
Sanity check.
uint8_t m_priority
Priority of the sent packets.
EventId m_sendEvent
Event to send the next packet.
uint32_t m_sent
Counter for sent packets.
uint32_t m_size
Size of the sent packet.
Ptr< Socket > m_socket
Socket.
TracedCallback< Ptr< const Packet >, const Address & > m_txTrace
Traced Callback: sent packets, source address.
Additional Inherited Members
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A simple client.
Sends packets using PacketSocket. It does not require (or use) IP.
Packets are sent as soon as PacketSocketClient::Start is called. The application has the same requirements as the PacketSocket for what concerns the underlying NetDevice and the Address scheme. It is meant to be used in ns-3 tests.
The application will send ‘MaxPackets’ packets, one every ‘Interval’ time. Packet size (‘PacketSize’) can be configured. Provides a "Tx" Traced Callback (transmitted packets, source address).
Note: packets larger than the NetDevice MTU will not be sent.
Config Paths
ns3::PacketSocketClient is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/ApplicationList/[i]/$ns3::PacketSocketClient"
Attributes
MaxPackets: The maximum number of packets the application will send (zero means infinite)
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 100
Flags: construct write read
Interval: The time to wait between packets
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+09ns
Flags: construct write read
PacketSize: Size of packets generated (bytes).
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 1024
Flags: construct write read
Priority: Priority assigned to the packets generated.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Initial value: 0
Flags: construct write read
Attributes defined in parent class ns3::Application
StartTime: Time at which the application will start
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
StopTime: Time at which the application will stop
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
TraceSources
Tx: A packet has been sent
Callback signature: ns3::Packet::AddressTracedCallback
Size of this type is 232 bytes (on a 64-bit architecture).
Definition at line 52 of file packet-socket-client.h.
Constructor & Destructor Documentation
PacketSocketClient()
ns3::PacketSocketClient::PacketSocketClient ()
Definition at line 76 of file packet-socket-client.cc.
References m_peerAddressSet, m_sendEvent, m_sent, m_socket, and NS_LOG_FUNCTION.
~PacketSocketClient()
ns3::PacketSocketClient::~PacketSocketClient () virtual
Definition at line 85 of file packet-socket-client.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::PacketSocketClient::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Application.
Definition at line 99 of file packet-socket-client.cc.
References ns3::Application::DoDispose(), and NS_LOG_FUNCTION.
GetPriority()
uint8_t ns3::PacketSocketClient::GetPriority (void) const
Query the priority value of this socket.
Returns
The priority value
Definition at line 116 of file packet-socket-client.cc.
References m_priority.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::PacketSocketClient::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 43 of file packet-socket-client.cc.
References GetPriority(), m_interval, m_maxPackets, m_size, m_txTrace, ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), ns3::Seconds(), ns3::TypeId::SetParent(), and SetPriority().
Send()
void ns3::PacketSocketClient::Send (void) private
Send a packet.
Definition at line 154 of file packet-socket-client.cc.
References ns3::PacketSocketAddress::ConvertFrom(), ns3::Packet::GetUid(), ns3::EventId::IsExpired(), m_interval, m_maxPackets, m_peerAddress, m_sendEvent, m_sent, m_size, m_socket, m_txTrace, ns3::Simulator::Now(), NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::Simulator::Schedule(), and ns3::Socket::Send().
Referenced by StartApplication().
SetPriority()
void ns3::PacketSocketClient::SetPriority (uint8_t priority) private
Manually set the socket priority.
Parameters
priority The socket priority (in the range 0..6)
Definition at line 106 of file packet-socket-client.cc.
References m_priority, m_socket, and ns3::Socket::SetPriority().
Referenced by GetTypeId().
SetRemote()
void ns3::PacketSocketClient::SetRemote (PacketSocketAddress addr)
set the remote address and protocol to be used
Parameters
addr remote address
Definition at line 91 of file packet-socket-client.cc.
References m_peerAddress, m_peerAddressSet, and NS_LOG_FUNCTION.
StartApplication()
void ns3::PacketSocketClient::StartApplication (void) private virtual
Application specific startup code.
The StartApplication method is called at the start time specified by Start This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 122 of file packet-socket-client.cc.
References ns3::Socket::Bind(), ns3::Socket::Connect(), ns3::Socket::CreateSocket(), ns3::Application::GetNode(), ns3::TypeId::LookupByName(), m_peerAddress, m_peerAddressSet, m_priority, m_sendEvent, m_socket, ns3::MakeNullCallback(), NS_ASSERT_MSG, NS_LOG_FUNCTION, ns3::Simulator::ScheduleNow(), Send(), ns3::Socket::SetPriority(), and ns3::Socket::SetRecvCallback().
StopApplication()
void ns3::PacketSocketClient::StopApplication (void) private virtual
Application specific shutdown code.
The StopApplication method is called at the stop time specified by Stop This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 146 of file packet-socket-client.cc.
References ns3::Simulator::Cancel(), ns3::Socket::Close(), m_sendEvent, m_socket, and NS_LOG_FUNCTION.
Member Data Documentation
m_interval
Time ns3::PacketSocketClient::m_interval private
Packet inter-send time.
Definition at line 97 of file packet-socket-client.h.
Referenced by GetTypeId(), and Send().
m_maxPackets
uint32_t ns3::PacketSocketClient::m_maxPackets private
Maximum number of packets the application will send.
Definition at line 96 of file packet-socket-client.h.
Referenced by GetTypeId(), and Send().
m_peerAddress
PacketSocketAddress ns3::PacketSocketClient::m_peerAddress private
Remote peer address.
Definition at line 103 of file packet-socket-client.h.
Referenced by Send(), SetRemote(), and StartApplication().
m_peerAddressSet
bool ns3::PacketSocketClient::m_peerAddressSet private
Sanity check.
Definition at line 104 of file packet-socket-client.h.
Referenced by PacketSocketClient(), SetRemote(), and StartApplication().
m_priority
uint8_t ns3::PacketSocketClient::m_priority private
Priority of the sent packets.
Definition at line 99 of file packet-socket-client.h.
Referenced by GetPriority(), SetPriority(), and StartApplication().
m_sendEvent
EventId ns3::PacketSocketClient::m_sendEvent private
Event to send the next packet.
Definition at line 105 of file packet-socket-client.h.
Referenced by PacketSocketClient(), Send(), StartApplication(), and StopApplication().
m_sent
uint32_t ns3::PacketSocketClient::m_sent private
Counter for sent packets.
Definition at line 101 of file packet-socket-client.h.
Referenced by PacketSocketClient(), and Send().
m_size
uint32_t ns3::PacketSocketClient::m_size private
Size of the sent packet.
Definition at line 98 of file packet-socket-client.h.
Referenced by GetTypeId(), and Send().
m_socket
Ptr<Socket> ns3::PacketSocketClient::m_socket private
Socket.
Definition at line 102 of file packet-socket-client.h.
Referenced by PacketSocketClient(), Send(), SetPriority(), StartApplication(), and StopApplication().
m_txTrace
TracedCallback<Ptr<const Packet>, const Address &> ns3::PacketSocketClient::m_txTrace private
Traced Callback: sent packets, source address.
Definition at line 108 of file packet-socket-client.h.
Referenced by GetTypeId(), and Send().
The documentation for this class was generated from the following files:
src/network/utils/packet-socket-client.h
src/network/utils/packet-socket-client.cc