ns-3: ns3::PointToPointNetDevice Class Reference
ns3::PointToPointNetDevice Class Reference
Point-To-Point Network Device
A Device for a Point to Point Network Link.
#include "point-to-point-net-device.h"
Public Member Functions
PointToPointNetDevice ()
Construct a PointToPointNetDevice.
virtual ~PointToPointNetDevice ()
Destroy a PointToPointNetDevice.
virtual void AddLinkChangeCallback (Callback< void > callback)
bool Attach (Ptr< PointToPointChannel > ch)
Attach the device to a channel.
virtual Address GetAddress (void) const
virtual Address GetBroadcast (void) const
virtual Ptr< Channel > GetChannel (void) const
virtual uint32_t GetIfIndex (void) const
virtual uint16_t GetMtu (void) const
virtual Address GetMulticast (Ipv4Address multicastGroup) const
Make and return a MAC multicast address using the provided multicast group.
virtual Address GetMulticast (Ipv6Address addr) const
Get the MAC multicast address corresponding to the IPv6 address provided.
virtual Ptr< Node > GetNode (void) const
Ptr< Queue< Packet > > GetQueue (void) const
Get a copy of the attached Queue.
virtual bool IsBridge (void) const
Return true if the net device is acting as a bridge.
virtual bool IsBroadcast (void) const
virtual bool IsLinkUp (void) const
virtual bool IsMulticast (void) const
virtual bool IsPointToPoint (void) const
Return true if the net device is on a point-to-point link.
virtual bool NeedsArp (void) const
void Receive (Ptr< Packet > p)
Receive a packet from a connected PointToPointChannel.
virtual bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)
virtual bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
virtual void SetAddress (Address address)
Set the address of this interface.
void SetDataRate (DataRate bps)
Set the Data Rate used for transmission of packets.
virtual void SetIfIndex (const uint32_t index)
void SetInterframeGap (Time t)
Set the interframe gap used to separate packets.
virtual bool SetMtu (const uint16_t mtu)
virtual void SetNode (Ptr< Node > node)
virtual void SetPromiscReceiveCallback (PromiscReceiveCallback cb)
void SetQueue (Ptr< Queue< Packet > > queue)
Attach a queue to the PointToPointNetDevice.
virtual void SetReceiveCallback (NetDevice::ReceiveCallback cb)
void SetReceiveErrorModel (Ptr< ErrorModel > em)
Attach a receive ErrorModel to the PointToPointNetDevice.
virtual bool SupportsSendFrom (void) const
Public Member Functions inherited from ns3::NetDevice
virtual ~NetDevice ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the TypeId.
Static Public Member Functions inherited from ns3::NetDevice
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
void DoMpiReceive (Ptr< Packet > p)
Handler for MPI receive event.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
enum TxMachineState { READY , BUSY }
Enumeration of the states of the transmit machine of the net device.
Private Member Functions
PointToPointNetDevice (const PointToPointNetDevice &o)
Copy constructor.
void AddHeader (Ptr< Packet > p, uint16_t protocolNumber)
Adds the necessary headers and trailers to a packet of data in order to respect the protocol implemented by the agent.
virtual void DoDispose (void)
Dispose of the object.
Address GetRemote (void) const
void NotifyLinkUp (void)
Make the link up and running.
PointToPointNetDevice & operator= (const PointToPointNetDevice &o)
Assign operator.
bool ProcessHeader (Ptr< Packet > p, uint16_t &param)
Removes, from a packet of data, all headers and trailers that relate to the protocol implemented by the agent.
void TransmitComplete (void)
Stop Sending a Packet Down the Wire and Begin the Interframe Gap.
bool TransmitStart (Ptr< Packet > p)
Start Sending a Packet Down the Wire.
Static Private Member Functions
static uint16_t EtherToPpp (uint16_t protocol)
Ethernet to PPP protocol number mapping.
static uint16_t PppToEther (uint16_t protocol)
PPP to Ethernet protocol number mapping.
Private Attributes
Mac48Address m_address
Mac48Address of this NetDevice.
DataRate m_bps
The data rate that the Net Device uses to simulate packet transmission timing.
Ptr< PointToPointChannel > m_channel
The PointToPointChannel to which this PointToPointNetDevice has been attached.
Ptr< Packet > m_currentPkt
Current packet processed.
uint32_t m_ifIndex
Index of the interface.
TracedCallback m_linkChangeCallbacks
Callback for the link change event.
bool m_linkUp
Identify if the link is up or not.
TracedCallback< Ptr< const Packet > > m_macPromiscRxTrace
The trace source fired for packets successfully received by the device immediately before being forwarded up to higher layers (at the L2/L3 transition).
TracedCallback< Ptr< const Packet > > m_macRxDropTrace
The trace source fired for packets successfully received by the device but are dropped before being forwarded up to higher layers (at the L2/L3 transition).
TracedCallback< Ptr< const Packet > > m_macRxTrace
The trace source fired for packets successfully received by the device immediately before being forwarded up to higher layers (at the L2/L3 transition).
TracedCallback< Ptr< const Packet > > m_macTxDropTrace
The trace source fired when packets coming into the "top" of the device at the L3/L2 transition are dropped before being queued for transmission.
TracedCallback< Ptr< const Packet > > m_macTxTrace
The trace source fired when packets come into the "top" of the device at the L3/L2 transition, before being queued for transmission.
uint32_t m_mtu
The Maximum Transmission Unit.
Ptr< Node > m_node
Node owning this NetDevice.
TracedCallback< Ptr< const Packet > > m_phyRxBeginTrace
The trace source fired when a packet begins the reception process from the medium – when the simulated first bit(s) arrive.
TracedCallback< Ptr< const Packet > > m_phyRxDropTrace
The trace source fired when the phy layer drops a packet it has received.
TracedCallback< Ptr< const Packet > > m_phyRxEndTrace
The trace source fired when a packet ends the reception process from the medium.
TracedCallback< Ptr< const Packet > > m_phyTxBeginTrace
The trace source fired when a packet begins the transmission process on the medium.
TracedCallback< Ptr< const Packet > > m_phyTxDropTrace
The trace source fired when the phy layer drops a packet before it tries to transmit it.
TracedCallback< Ptr< const Packet > > m_phyTxEndTrace
The trace source fired when a packet ends the transmission process on the medium.
NetDevice::PromiscReceiveCallback m_promiscCallback
Receive callback.
TracedCallback< Ptr< const Packet > > m_promiscSnifferTrace
A trace source that emulates a promiscuous mode protocol sniffer connected to the device.
Ptr< Queue< Packet > > m_queue
The Queue which this PointToPointNetDevice uses as a packet source.
Ptr< ErrorModel > m_receiveErrorModel
Error model for receive packet events.
NetDevice::ReceiveCallback m_rxCallback
Receive callback.
TracedCallback< Ptr< const Packet > > m_snifferTrace
A trace source that emulates a non-promiscuous protocol sniffer connected to the device.
Time m_tInterframeGap
The interframe gap that the Net Device uses to throttle packet transmission.
TxMachineState m_txMachineState
The state of the Net Device transmit state machine.
Static Private Attributes
static const uint16_t DEFAULT_MTU = 1500
Default MTU.
Additional Inherited Members
Public Types inherited from ns3::NetDevice
typedef void(* LinkChangeTracedCallback) (void)
TracedCallback signature for link changed event.
enum PacketType {
PACKET_HOST = 1 , NS3_PACKET_HOST = PACKET_HOST , PACKET_BROADCAST , NS3_PACKET_BROADCAST = PACKET_BROADCAST ,
PACKET_MULTICAST , NS3_PACKET_MULTICAST = PACKET_MULTICAST , PACKET_OTHERHOST , NS3_PACKET_OTHERHOST = PACKET_OTHERHOST
}
Packet types are used as they are in Linux.
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address &, const Address &, enum PacketType > PromiscReceiveCallback
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address & > ReceiveCallback
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A Device for a Point to Point Network Link.
This PointToPointNetDevice class specializes the NetDevice abstract base class. Together with a PointToPointChannel (and a peer PointToPointNetDevice), the class models, with some level of abstraction, a generic point-to-point or serial link. Key parameters or objects that can be specified for this device include a queue, data rate, and interframe transmission gap (the propagation delay is set in the PointToPointChannel).
Config Paths
ns3::PointToPointNetDevice is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::PointToPointNetDevice"
Attributes
Mtu: The MAC-level Maximum Transmission Unit
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 1500
Flags: construct write read
Address: The MAC address of this device.
Set with class: Mac48AddressValue
Underlying type: Mac48Address
Initial value: ff:ff:ff:ff:ff:ff
Flags: construct write read
DataRate: The default data rate for point to point links
Set with class: DataRateValue
Underlying type: DataRate
Initial value: 32768bps
Flags: construct write read
ReceiveErrorModel: The receiver error model used to simulate packet loss
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::ErrorModel>
Initial value: 0x0
Flags: construct write read
InterframeGap: The time to wait between packet (frame) transmissions
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
TxQueue: A queue to use as the transmit queue in the device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::Queue<Packet>>
Initial value: 0x0
Flags: construct write read
TraceSources
MacTx: Trace source indicating a packet has arrived for transmission by this device
Callback signature: ns3::Packet::TracedCallback
MacTxDrop: Trace source indicating a packet has been dropped by the device before transmission
Callback signature: ns3::Packet::TracedCallback
MacPromiscRx: A packet has been received by this device, has been passed up from the physical layer and is being forwarded up the local protocol stack. This is a promiscuous trace,
Callback signature: ns3::Packet::TracedCallback
MacRx: A packet has been received by this device, has been passed up from the physical layer and is being forwarded up the local protocol stack. This is a non-promiscuous trace,
Callback signature: ns3::Packet::TracedCallback
PhyTxBegin: Trace source indicating a packet has begun transmitting over the channel
Callback signature: ns3::Packet::TracedCallback
PhyTxEnd: Trace source indicating a packet has been completely transmitted over the channel
Callback signature: ns3::Packet::TracedCallback
PhyTxDrop: Trace source indicating a packet has been dropped by the device during transmission
Callback signature: ns3::Packet::TracedCallback
PhyRxEnd: Trace source indicating a packet has been completely received by the device
Callback signature: ns3::Packet::TracedCallback
PhyRxDrop: Trace source indicating a packet has been dropped by the device during reception
Callback signature: ns3::Packet::TracedCallback
Sniffer: Trace source simulating a non-promiscuous packet sniffer attached to the device
Callback signature: ns3::Packet::TracedCallback
PromiscSniffer: Trace source simulating a promiscuous packet sniffer attached to the device
Callback signature: ns3::Packet::TracedCallback
Size of this type is 464 bytes (on a 64-bit architecture).
Definition at line 62 of file point-to-point-net-device.h.
Member Enumeration Documentation
TxMachineState
enum ns3::PointToPointNetDevice::TxMachineState private
Enumeration of the states of the transmit machine of the net device.
Enumerator
READY
The transmitter is ready to begin transmission of a packet.
BUSY
The transmitter is busy transmitting a packet.
Definition at line 288 of file point-to-point-net-device.h.
Constructor & Destructor Documentation
PointToPointNetDevice() [1/2]
ns3::PointToPointNetDevice::PointToPointNetDevice ()
Construct a PointToPointNetDevice.
This is the constructor for the PointToPointNetDevice. It takes as a parameter a pointer to the Node to which this device is connected, as well as an optional DataRate object.
Definition at line 175 of file point-to-point-net-device.cc.
References NS_LOG_FUNCTION.
~PointToPointNetDevice()
ns3::PointToPointNetDevice::~PointToPointNetDevice () virtual
Destroy a PointToPointNetDevice.
This is the destructor for the PointToPointNetDevice.
Definition at line 185 of file point-to-point-net-device.cc.
References NS_LOG_FUNCTION.
PointToPointNetDevice() [2/2]
ns3::PointToPointNetDevice::PointToPointNetDevice (const PointToPointNetDevice & o) private
Copy constructor.
The method is private, so it is DISABLED.
Parameters
o Other NetDevice
Member Function Documentation
AddHeader()
void ns3::PointToPointNetDevice::AddHeader (Ptr< Packet > p, uint16_t protocolNumber) private
Adds the necessary headers and trailers to a packet of data in order to respect the protocol implemented by the agent.
Parameters
p packet
protocolNumber protocol number
Definition at line 191 of file point-to-point-net-device.cc.
References ns3::Packet::AddHeader(), EtherToPpp(), NS_LOG_FUNCTION, and ns3::PppHeader::SetProtocol().
Referenced by Send().
AddLinkChangeCallback()
void ns3::PointToPointNetDevice::AddLinkChangeCallback (Callback< void > callback) virtual
Parameters
callback the callback to invoke
Add a callback invoked whenever the link status changes to UP. This callback is typically used by the IP/ARP layer to flush the ARP cache and by IPv6 stack to flush NDISC cache whenever the link goes up.
Implements ns3::NetDevice.
Definition at line 442 of file point-to-point-net-device.cc.
References ns3::TracedCallback< Ts >::ConnectWithoutContext(), m_linkChangeCallbacks, and NS_LOG_FUNCTION.
Attach()
bool ns3::PointToPointNetDevice::Attach (Ptr< PointToPointChannel > ch)
Attach the device to a channel.
Parameters
ch Ptr to the channel to which this object is being attached.
Returns
true if the operation was successful (always true actually)
Definition at line 300 of file point-to-point-net-device.cc.
References m_channel, NotifyLinkUp(), and NS_LOG_FUNCTION.
DoDispose()
void ns3::PointToPointNetDevice::DoDispose (void) private virtual
Dispose of the object.
Reimplemented from ns3::Object.
Definition at line 210 of file point-to-point-net-device.cc.
References ns3::Object::DoDispose(), m_channel, m_currentPkt, m_node, m_queue, m_receiveErrorModel, and NS_LOG_FUNCTION.
DoMpiReceive()
void ns3::PointToPointNetDevice::DoMpiReceive (Ptr< Packet > p) protected
Handler for MPI receive event.
Parameters
p Packet received
Definition at line 609 of file point-to-point-net-device.cc.
References NS_LOG_FUNCTION, and Receive().
EtherToPpp()
uint16_t ns3::PointToPointNetDevice::EtherToPpp (uint16_t protocol) static private
Ethernet to PPP protocol number mapping.
Parameters
protocol An Ethernet protocol number
Returns
The corresponding PPP protocol number
Definition at line 662 of file point-to-point-net-device.cc.
References NS_ASSERT_MSG, and NS_LOG_FUNCTION_NOARGS.
Referenced by AddHeader().
GetAddress()
Address ns3::PointToPointNetDevice::GetAddress (void) const virtual
Returns
the current Address of this interface.
Implements ns3::NetDevice.
Definition at line 429 of file point-to-point-net-device.cc.
References m_address.
Referenced by Receive().
GetBroadcast()
Address ns3::PointToPointNetDevice::GetBroadcast (void) const virtual
Returns
the broadcast address supported by this netdevice.
Calling this method is invalid if IsBroadcast returns not true.
Implements ns3::NetDevice.
Definition at line 465 of file point-to-point-net-device.cc.
References NS_LOG_FUNCTION.
GetChannel()
Ptr< Channel > ns3::PointToPointNetDevice::GetChannel (void) const virtual
Returns
the channel this NetDevice is connected to. The value returned can be zero if the NetDevice is not yet connected to any channel or if the underlying NetDevice has no concept of a channel. i.e., callers must check for zero and be ready to handle it.
Implements ns3::NetDevice.
Definition at line 410 of file point-to-point-net-device.cc.
References m_channel.
GetIfIndex()
uint32_t ns3::PointToPointNetDevice::GetIfIndex (void) const virtual
Returns
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 404 of file point-to-point-net-device.cc.
References m_ifIndex.
GetMtu()
uint16_t ns3::PointToPointNetDevice::GetMtu (void) const virtual
Returns
the link-level MTU in bytes for this interface.
This value is typically used by the IP layer to perform IP fragmentation when needed.
Implements ns3::NetDevice.
Definition at line 642 of file point-to-point-net-device.cc.
References m_mtu, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetMulticast() [1/2]
Address ns3::PointToPointNetDevice::GetMulticast (Ipv4Address multicastGroup) const virtual
Make and return a MAC multicast address using the provided multicast group.
RFC 1112 says that an Ipv4 host group address is mapped to an Ethernet multicast address by placing the low-order 23-bits of the IP address into the low-order 23 bits of the Ethernet multicast address 01-00-5E-00-00-00 (hex). Similar RFCs exist for Ipv6 and Eui64 mappings. This method performs the multicast address creation function appropriate to the underlying MAC address of the device. This MAC address is encapsulated in an abstract Address to avoid dependencies on the exact MAC address format.
In the case of net devices that do not support multicast, clients are expected to test NetDevice::IsMulticast and avoid attempting to map multicast packets. Subclasses of NetDevice that do support multicasting are expected to override this method and provide an implementation appropriate to the particular device.
Parameters
multicastGroup The IP address for the multicast group destination of the packet.
Returns
The MAC multicast Address used to send packets to the provided multicast group.
Warning
Calling this method is invalid if IsMulticast returns not true.
See also
IsMulticast()
Implements ns3::NetDevice.
Definition at line 479 of file point-to-point-net-device.cc.
References NS_LOG_FUNCTION.
GetMulticast() [2/2]
Address ns3::PointToPointNetDevice::GetMulticast (Ipv6Address addr) const virtual
Get the MAC multicast address corresponding to the IPv6 address provided.
Parameters
addr IPv6 address
Returns
the MAC multicast address
Warning
Calling this method is invalid if IsMulticast returns not true.
Implements ns3::NetDevice.
Definition at line 486 of file point-to-point-net-device.cc.
References NS_LOG_FUNCTION.
GetNode()
Ptr< Node > ns3::PointToPointNetDevice::GetNode (void) const virtual
Returns
the node base class which contains this network interface.
When a subclass needs to get access to the underlying node base class to print the nodeid for example, it can invoke this method.
Implements ns3::NetDevice.
Definition at line 570 of file point-to-point-net-device.cc.
References m_node.
GetQueue()
Ptr< Queue< Packet > > ns3::PointToPointNetDevice::GetQueue (void) const
Get a copy of the attached Queue.
Returns
Ptr to the queue.
Definition at line 382 of file point-to-point-net-device.cc.
References m_queue, and NS_LOG_FUNCTION.
Referenced by ns3::PointToPointHelper::EnableAsciiInternal().
GetRemote()
Address ns3::PointToPointNetDevice::GetRemote (void) const private
Returns
the address of the remote device connected to this device through the point to point channel.
Definition at line 616 of file point-to-point-net-device.cc.
References m_channel, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by Receive().
GetTypeId()
TypeId ns3::PointToPointNetDevice::GetTypeId (void) static
Get the TypeId.
Returns
The TypeId for this class
Definition at line 39 of file point-to-point-net-device.cc.
References DEFAULT_MTU, GetMtu(), m_address, m_bps, m_macPromiscRxTrace, m_macRxDropTrace, m_macRxTrace, m_macTxDropTrace, m_macTxTrace, m_phyRxBeginTrace, m_phyRxDropTrace, m_phyRxEndTrace, m_phyTxBeginTrace, m_phyTxDropTrace, m_phyTxEndTrace, m_promiscSnifferTrace, m_queue, m_receiveErrorModel, m_snifferTrace, m_tInterframeGap, ns3::MakeDataRateAccessor(), ns3::MakeDataRateChecker(), ns3::MakeMac48AddressAccessor(), ns3::MakeMac48AddressChecker(), ns3::MakePointerAccessor(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), ns3::Seconds(), SetMtu(), and ns3::TypeId::SetParent().
IsBridge()
bool ns3::PointToPointNetDevice::IsBridge (void) const virtual
Return true if the net device is acting as a bridge.
Returns
value of m_isBridge flag
Implements ns3::NetDevice.
Definition at line 500 of file point-to-point-net-device.cc.
References NS_LOG_FUNCTION.
IsBroadcast()
bool ns3::PointToPointNetDevice::IsBroadcast (void) const virtual
Returns
true if this interface supports a broadcast address, false otherwise.
Implements ns3::NetDevice.
Definition at line 453 of file point-to-point-net-device.cc.
References NS_LOG_FUNCTION.
IsLinkUp()
bool ns3::PointToPointNetDevice::IsLinkUp (void) const virtual
Returns
true if link is up; false otherwise
Implements ns3::NetDevice.
Definition at line 435 of file point-to-point-net-device.cc.
References m_linkUp, and NS_LOG_FUNCTION.
Referenced by Send().
IsMulticast()
bool ns3::PointToPointNetDevice::IsMulticast (void) const virtual
Returns
value of m_isMulticast flag
Implements ns3::NetDevice.
Definition at line 472 of file point-to-point-net-device.cc.
References NS_LOG_FUNCTION.
IsPointToPoint()
bool ns3::PointToPointNetDevice::IsPointToPoint (void) const virtual
Return true if the net device is on a point-to-point link.
Returns
value of m_isPointToPoint flag
Implements ns3::NetDevice.
Definition at line 493 of file point-to-point-net-device.cc.
References NS_LOG_FUNCTION.
NeedsArp()
bool ns3::PointToPointNetDevice::NeedsArp (void) const virtual
Returns
true if ARP is needed, false otherwise.
Called by higher-layers to check if this NetDevice requires ARP to be used.
Implements ns3::NetDevice.
Definition at line 583 of file point-to-point-net-device.cc.
References NS_LOG_FUNCTION.
NotifyLinkUp()
void ns3::PointToPointNetDevice::NotifyLinkUp (void) private
Make the link up and running.
It calls also the linkChange callback.
Definition at line 389 of file point-to-point-net-device.cc.
References m_linkChangeCallbacks, m_linkUp, and NS_LOG_FUNCTION.
Referenced by Attach().
operator=()
PointToPointNetDevice& ns3::PointToPointNetDevice::operator= (const PointToPointNetDevice & o) private
Assign operator.
The method is private, so it is DISABLED.
Parameters
o Other NetDevice
Returns
New instance of the NetDevice
PppToEther()
uint16_t ns3::PointToPointNetDevice::PppToEther (uint16_t protocol) static private
PPP to Ethernet protocol number mapping.
Parameters
protocol A PPP protocol number
Returns
The corresponding Ethernet protocol number
Definition at line 649 of file point-to-point-net-device.cc.
References NS_ASSERT_MSG, and NS_LOG_FUNCTION_NOARGS.
Referenced by ProcessHeader().
ProcessHeader()
bool ns3::PointToPointNetDevice::ProcessHeader (Ptr< Packet > p, uint16_t & param) private
Removes, from a packet of data, all headers and trailers that relate to the protocol implemented by the agent.
Parameters
p Packet whose headers need to be processed
param An integer parameter that can be set by the function
Returns
Returns true if the packet should be forwarded up the protocol stack.
Definition at line 200 of file point-to-point-net-device.cc.
References ns3::PppHeader::GetProtocol(), NS_LOG_FUNCTION, PppToEther(), and ns3::Packet::RemoveHeader().
Referenced by Receive().
Receive()
void ns3::PointToPointNetDevice::Receive (Ptr< Packet > p)
Receive a packet from a connected PointToPointChannel.
The PointToPointNetDevice receives packets from its connected channel and forwards them up the protocol stack. This is the public method used by the channel to indicate that the last bit of a packet has arrived at the device.
Parameters
p Ptr to the received packet.
Definition at line 332 of file point-to-point-net-device.cc.
References ns3::Packet::Copy(), GetAddress(), GetRemote(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_macPromiscRxTrace, m_macRxTrace, m_phyRxDropTrace, m_phyRxEndTrace, m_promiscCallback, m_promiscSnifferTrace, m_receiveErrorModel, m_rxCallback, m_snifferTrace, NS_LOG_FUNCTION, ns3::NetDevice::PACKET_HOST, and ProcessHeader().
Referenced by DoMpiReceive(), ns3::PointToPointHelper::Install(), and ns3::PointToPointChannel::TransmitStart().
Send()
bool ns3::PointToPointNetDevice::Send (Ptr< Packet > packet, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device to the specified destination Address
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 507 of file point-to-point-net-device.cc.
References AddHeader(), ns3::Packet::GetUid(), IsLinkUp(), m_macTxDropTrace, m_macTxTrace, m_promiscSnifferTrace, m_queue, m_snifferTrace, m_txMachineState, NS_LOG_FUNCTION, NS_LOG_LOGIC, READY, and TransmitStart().
SendFrom()
bool ns3::PointToPointNetDevice::SendFrom (Ptr< Packet > packet, const Address & source, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
source source mac address (so called "MAC spoofing")
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device with the specified source and destination Addresses.
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 560 of file point-to-point-net-device.cc.
References NS_LOG_FUNCTION.
SetAddress()
void ns3::PointToPointNetDevice::SetAddress (Address address) virtual
Set the address of this interface.
Parameters
address address to set
Implements ns3::NetDevice.
Definition at line 422 of file point-to-point-net-device.cc.
References first::address, ns3::Mac48Address::ConvertFrom(), m_address, and NS_LOG_FUNCTION.
SetDataRate()
void ns3::PointToPointNetDevice::SetDataRate (DataRate bps)
Set the Data Rate used for transmission of packets.
The data rate is set in the Attach () method from the corresponding field in the channel to which the device is attached. It can be overridden using this method.
Parameters
bps the data rate at which this object operates
Definition at line 222 of file point-to-point-net-device.cc.
References m_bps, and NS_LOG_FUNCTION.
SetIfIndex()
void ns3::PointToPointNetDevice::SetIfIndex (const uint32_t index) virtual
Parameters
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 397 of file point-to-point-net-device.cc.
References m_ifIndex, and NS_LOG_FUNCTION.
SetInterframeGap()
void ns3::PointToPointNetDevice::SetInterframeGap (Time t)
Set the interframe gap used to separate packets.
The interframe gap defines the minimum space required between packets sent by this device.
Parameters
t the interframe gap time
Definition at line 229 of file point-to-point-net-device.cc.
References ns3::Time::As(), m_tInterframeGap, NS_LOG_FUNCTION, and ns3::Time::S.
SetMtu()
bool ns3::PointToPointNetDevice::SetMtu (const uint16_t mtu) virtual
Parameters
mtu MTU value, in bytes, to set for the device
Returns
whether the MTU value was within legal bounds
Override for default MTU defined on a per-type basis.
Implements ns3::NetDevice.
Definition at line 634 of file point-to-point-net-device.cc.
References m_mtu, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetNode()
void ns3::PointToPointNetDevice::SetNode (Ptr< Node > node) virtual
Parameters
node the node associated to this netdevice.
This method is called from ns3::Node::AddDevice.
Implements ns3::NetDevice.
Definition at line 576 of file point-to-point-net-device.cc.
References m_node, and NS_LOG_FUNCTION.
SetPromiscReceiveCallback()
void ns3::PointToPointNetDevice::SetPromiscReceiveCallback (PromiscReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received in promiscuous mode and must be forwarded to the higher layers.
Enables netdevice promiscuous mode and sets the callback that will handle promiscuous mode packets. Note, promiscuous mode packets means all packets, including those packets that can be sensed by the netdevice but which are intended to be received by other hosts.
Implements ns3::NetDevice.
Definition at line 596 of file point-to-point-net-device.cc.
References m_promiscCallback.
SetQueue()
void ns3::PointToPointNetDevice::SetQueue (Ptr< Queue< Packet > > queue)
Attach a queue to the PointToPointNetDevice.
The PointToPointNetDevice "owns" a queue that implements a queueing method such as DropTailQueue or RedQueue
Parameters
queue Ptr to the new queue.
Definition at line 318 of file point-to-point-net-device.cc.
References m_queue, and NS_LOG_FUNCTION.
SetReceiveCallback()
void ns3::PointToPointNetDevice::SetReceiveCallback (NetDevice::ReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received and must be forwarded to the higher layers.
Set the callback to be used to notify higher layers when a packet has been received.
Implements ns3::NetDevice.
Definition at line 590 of file point-to-point-net-device.cc.
References m_rxCallback.
SetReceiveErrorModel()
void ns3::PointToPointNetDevice::SetReceiveErrorModel (Ptr< ErrorModel > em)
Attach a receive ErrorModel to the PointToPointNetDevice.
The PointToPointNetDevice may optionally include an ErrorModel in the packet receive chain.
Parameters
em Ptr to the ErrorModel.
Definition at line 325 of file point-to-point-net-device.cc.
References m_receiveErrorModel, and NS_LOG_FUNCTION.
SupportsSendFrom()
bool ns3::PointToPointNetDevice::SupportsSendFrom (void) const virtual
Returns
true if this interface supports a bridging mode, false otherwise.
Implements ns3::NetDevice.
Definition at line 602 of file point-to-point-net-device.cc.
References NS_LOG_FUNCTION.
TransmitComplete()
void ns3::PointToPointNetDevice::TransmitComplete (void) private
Stop Sending a Packet Down the Wire and Begin the Interframe Gap.
The TransmitComplete method is used internally to finish the process of sending a packet out on the channel.
Definition at line 266 of file point-to-point-net-device.cc.
References BUSY, m_currentPkt, m_phyTxEndTrace, m_promiscSnifferTrace, m_queue, m_snifferTrace, m_txMachineState, NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, READY, and TransmitStart().
Referenced by TransmitStart().
TransmitStart()
bool ns3::PointToPointNetDevice::TransmitStart (Ptr< Packet > p) private
Start Sending a Packet Down the Wire.
The TransmitStart method is the method that is used internally in the PointToPointNetDevice to begin the process of sending a packet out on the channel. The corresponding method is called on the channel to let it know that the physical device this class represents has virtually started sending signals. An event is scheduled for the time at which the bits have been completely transmitted.
See also
PointToPointChannel::TransmitStart ()
TransmitComplete()
Parameters
p a reference to the packet to send
Returns
true if success, false on failure
Definition at line 236 of file point-to-point-net-device.cc.
References ns3::Time::As(), BUSY, ns3::DataRate::CalculateBytesTxTime(), ns3::Packet::GetSize(), ns3::Packet::GetUid(), m_bps, m_channel, m_currentPkt, m_phyTxBeginTrace, m_phyTxDropTrace, m_tInterframeGap, m_txMachineState, NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, READY, ns3::Time::S, ns3::Simulator::Schedule(), and TransmitComplete().
Referenced by Send(), and TransmitComplete().
Member Data Documentation
DEFAULT_MTU
const uint16_t ns3::PointToPointNetDevice::DEFAULT_MTU = 1500 static private
Default MTU.
Definition at line 446 of file point-to-point-net-device.h.
Referenced by GetTypeId().
m_address
Mac48Address ns3::PointToPointNetDevice::m_address private
Mac48Address of this NetDevice.
Definition at line 438 of file point-to-point-net-device.h.
Referenced by GetAddress(), GetTypeId(), and SetAddress().
m_bps
DataRate ns3::PointToPointNetDevice::m_bps private
The data rate that the Net Device uses to simulate packet transmission timing.
Definition at line 302 of file point-to-point-net-device.h.
Referenced by GetTypeId(), SetDataRate(), and TransmitStart().
m_channel
Ptr<PointToPointChannel> ns3::PointToPointNetDevice::m_channel private
The PointToPointChannel to which this PointToPointNetDevice has been attached.
Definition at line 314 of file point-to-point-net-device.h.
Referenced by Attach(), DoDispose(), GetChannel(), GetRemote(), and TransmitStart().
m_currentPkt
Ptr<Packet> ns3::PointToPointNetDevice::m_currentPkt private
Current packet processed.
Definition at line 458 of file point-to-point-net-device.h.
Referenced by DoDispose(), TransmitComplete(), and TransmitStart().
m_ifIndex
uint32_t ns3::PointToPointNetDevice::m_ifIndex private
Index of the interface.
Definition at line 442 of file point-to-point-net-device.h.
Referenced by GetIfIndex(), and SetIfIndex().
m_linkChangeCallbacks
TracedCallback ns3::PointToPointNetDevice::m_linkChangeCallbacks private
Callback for the link change event.
Definition at line 444 of file point-to-point-net-device.h.
Referenced by AddLinkChangeCallback(), and NotifyLinkUp().
m_linkUp
bool ns3::PointToPointNetDevice::m_linkUp private
Identify if the link is up or not.
Definition at line 443 of file point-to-point-net-device.h.
Referenced by IsLinkUp(), and NotifyLinkUp().
m_macPromiscRxTrace
TracedCallback<Ptr<const Packet> > ns3::PointToPointNetDevice::m_macPromiscRxTrace private
The trace source fired for packets successfully received by the device immediately before being forwarded up to higher layers (at the L2/L3 transition).
This is a promiscuous trace (which doesn't mean a lot here in the point-to-point device).
Definition at line 347 of file point-to-point-net-device.h.
Referenced by GetTypeId(), and Receive().
m_macRxDropTrace
TracedCallback<Ptr<const Packet> > ns3::PointToPointNetDevice::m_macRxDropTrace private
The trace source fired for packets successfully received by the device but are dropped before being forwarded up to higher layers (at the L2/L3 transition).
Definition at line 362 of file point-to-point-net-device.h.
Referenced by GetTypeId().
m_macRxTrace
TracedCallback<Ptr<const Packet> > ns3::PointToPointNetDevice::m_macRxTrace private
The trace source fired for packets successfully received by the device immediately before being forwarded up to higher layers (at the L2/L3 transition).
This is a non-promiscuous trace (which doesn't mean a lot here in the point-to-point device).
Definition at line 355 of file point-to-point-net-device.h.
Referenced by GetTypeId(), and Receive().
m_macTxDropTrace
TracedCallback<Ptr<const Packet> > ns3::PointToPointNetDevice::m_macTxDropTrace private
The trace source fired when packets coming into the "top" of the device at the L3/L2 transition are dropped before being queued for transmission.
Definition at line 339 of file point-to-point-net-device.h.
Referenced by GetTypeId(), and Send().
m_macTxTrace
TracedCallback<Ptr<const Packet> > ns3::PointToPointNetDevice::m_macTxTrace private
The trace source fired when packets come into the "top" of the device at the L3/L2 transition, before being queued for transmission.
Definition at line 333 of file point-to-point-net-device.h.
Referenced by GetTypeId(), and Send().
m_mtu
uint32_t ns3::PointToPointNetDevice::m_mtu private
The Maximum Transmission Unit.
This corresponds to the maximum number of bytes that can be transmitted as seen from higher layers. This corresponds to the 1500 byte MTU size often seen on IP over Ethernet.
Definition at line 456 of file point-to-point-net-device.h.
Referenced by GetMtu(), and SetMtu().
m_node
Ptr<Node> ns3::PointToPointNetDevice::m_node private
Node owning this NetDevice.
Definition at line 437 of file point-to-point-net-device.h.
Referenced by DoDispose(), GetNode(), and SetNode().
m_phyRxBeginTrace
TracedCallback<Ptr<const Packet> > ns3::PointToPointNetDevice::m_phyRxBeginTrace private
The trace source fired when a packet begins the reception process from the medium – when the simulated first bit(s) arrive.
Definition at line 386 of file point-to-point-net-device.h.
Referenced by GetTypeId().
m_phyRxDropTrace
TracedCallback<Ptr<const Packet> > ns3::PointToPointNetDevice::m_phyRxDropTrace private
The trace source fired when the phy layer drops a packet it has received.
This happens if the receiver is not enabled or the error model is active and indicates that the packet is corrupt.
Definition at line 399 of file point-to-point-net-device.h.
Referenced by GetTypeId(), and Receive().
m_phyRxEndTrace
TracedCallback<Ptr<const Packet> > ns3::PointToPointNetDevice::m_phyRxEndTrace private
The trace source fired when a packet ends the reception process from the medium.
Definition at line 392 of file point-to-point-net-device.h.
Referenced by GetTypeId(), and Receive().
m_phyTxBeginTrace
TracedCallback<Ptr<const Packet> > ns3::PointToPointNetDevice::m_phyTxBeginTrace private
The trace source fired when a packet begins the transmission process on the medium.
Definition at line 368 of file point-to-point-net-device.h.
Referenced by GetTypeId(), and TransmitStart().
m_phyTxDropTrace
TracedCallback<Ptr<const Packet> > ns3::PointToPointNetDevice::m_phyTxDropTrace private
The trace source fired when the phy layer drops a packet before it tries to transmit it.
Definition at line 380 of file point-to-point-net-device.h.
Referenced by GetTypeId(), and TransmitStart().
m_phyTxEndTrace
TracedCallback<Ptr<const Packet> > ns3::PointToPointNetDevice::m_phyTxEndTrace private
The trace source fired when a packet ends the transmission process on the medium.
Definition at line 374 of file point-to-point-net-device.h.
Referenced by GetTypeId(), and TransmitComplete().
m_promiscCallback
NetDevice::PromiscReceiveCallback ns3::PointToPointNetDevice::m_promiscCallback private
Receive callback.
Definition at line 440 of file point-to-point-net-device.h.
Referenced by Receive(), and SetPromiscReceiveCallback().
m_promiscSnifferTrace
TracedCallback<Ptr<const Packet> > ns3::PointToPointNetDevice::m_promiscSnifferTrace private
A trace source that emulates a promiscuous mode protocol sniffer connected to the device.
This trace source fire on packets destined for any host just like your average everyday packet sniffer.
On the transmit size, this trace hook will fire after a packet is dequeued from the device queue for transmission. In Linux, for example, this would correspond to the point just before a device hard_start_xmit where dev_queue_xmit_nit is called to dispatch the packet to the PF_PACKET ETH_P_ALL handlers.
On the receive side, this trace hook will fire when a packet is received, just before the receive callback is executed. In Linux, for example, this would correspond to the point at which the packet is dispatched to packet sniffers in netif_receive_skb.
Definition at line 435 of file point-to-point-net-device.h.
Referenced by GetTypeId(), Receive(), Send(), and TransmitComplete().
m_queue
Ptr<Queue<Packet> > ns3::PointToPointNetDevice::m_queue private
The Queue which this PointToPointNetDevice uses as a packet source.
Management of this Queue has been delegated to the PointToPointNetDevice and it has the responsibility for deletion.
See also
class DropTailQueue
Definition at line 322 of file point-to-point-net-device.h.
Referenced by DoDispose(), GetQueue(), GetTypeId(), Send(), SetQueue(), and TransmitComplete().
m_receiveErrorModel
Ptr<ErrorModel> ns3::PointToPointNetDevice::m_receiveErrorModel private
Error model for receive packet events.
Definition at line 327 of file point-to-point-net-device.h.
Referenced by DoDispose(), GetTypeId(), Receive(), and SetReceiveErrorModel().
m_rxCallback
NetDevice::ReceiveCallback ns3::PointToPointNetDevice::m_rxCallback private
Receive callback.
Definition at line 439 of file point-to-point-net-device.h.
Referenced by Receive(), and SetReceiveCallback().
m_snifferTrace
TracedCallback<Ptr<const Packet> > ns3::PointToPointNetDevice::m_snifferTrace private
A trace source that emulates a non-promiscuous protocol sniffer connected to the device.
Unlike your average everyday sniffer, this trace source will not fire on PACKET_OTHERHOST events.
On the transmit size, this trace hook will fire after a packet is dequeued from the device queue for transmission. In Linux, for example, this would correspond to the point just before a device hard_start_xmit where dev_queue_xmit_nit is called to dispatch the packet to the PF_PACKET ETH_P_ALL handlers.
On the receive side, this trace hook will fire when a packet is received, just before the receive callback is executed. In Linux, for example, this would correspond to the point at which the packet is dispatched to packet sniffers in netif_receive_skb.
Definition at line 417 of file point-to-point-net-device.h.
Referenced by GetTypeId(), Receive(), Send(), and TransmitComplete().
m_tInterframeGap
Time ns3::PointToPointNetDevice::m_tInterframeGap private
The interframe gap that the Net Device uses to throttle packet transmission.
Definition at line 308 of file point-to-point-net-device.h.
Referenced by GetTypeId(), SetInterframeGap(), and TransmitStart().
m_txMachineState
TxMachineState ns3::PointToPointNetDevice::m_txMachineState private
The state of the Net Device transmit state machine.
Definition at line 296 of file point-to-point-net-device.h.
Referenced by Send(), TransmitComplete(), and TransmitStart().
The documentation for this class was generated from the following files:
src/point-to-point/model/point-to-point-net-device.h
src/point-to-point/model/point-to-point-net-device.cc