ns-3: ns3::Dot11sStack Class Reference
ns3::Dot11sStack Class Reference
Mesh Device » IEEE 802.11s draft
Helper class to allow easy installation of 802.11s stack.
#include "dot11s-installer.h"
Public Member Functions
Dot11sStack ()
Create a Dot11sStack() installer helper.
~Dot11sStack ()
Destroy a Dot11sStack() installer helper.
void DoDispose ()
Break any reference cycles in the installer helper.
bool InstallStack (Ptr< MeshPointDevice > mp)
Install an 802.11s stack.
void Report (const Ptr< MeshPointDevice > mp, std::ostream &)
Iterate through the referenced devices and protocols and print their statistics.
void ResetStats (const Ptr< MeshPointDevice > mp)
Reset the statistics on the referenced devices and protocols.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::MeshStack
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Mac48Address m_root
root
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Helper class to allow easy installation of 802.11s stack.
Introspection did not find any typical Config paths.
Attributes
Root: The MAC address of root mesh point.
Set with class: Mac48AddressValue
Underlying type: Mac48Address
Initial value: ff:ff:ff:ff:ff:ff
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 40 bytes (on a 64-bit architecture).
Definition at line 32 of file dot11s-installer.h.
Constructor & Destructor Documentation
Dot11sStack()
ns3::Dot11sStack::Dot11sStack ()
Create a Dot11sStack() installer helper.
Definition at line 44 of file dot11s-installer.cc.
~Dot11sStack()
ns3::Dot11sStack::~Dot11sStack ()
Destroy a Dot11sStack() installer helper.
Definition at line 48 of file dot11s-installer.cc.
Member Function Documentation
DoDispose()
void ns3::Dot11sStack::DoDispose (void) virtual
Break any reference cycles in the installer helper.
Required for ns-3 Object support.
Reimplemented from ns3::Object.
Definition at line 52 of file dot11s-installer.cc.
GetTypeId()
TypeId ns3::Dot11sStack::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 31 of file dot11s-installer.cc.
References m_root, ns3::MakeMac48AddressAccessor(), ns3::MakeMac48AddressChecker(), and ns3::TypeId::SetParent().
InstallStack()
bool ns3::Dot11sStack::InstallStack (Ptr< MeshPointDevice > mp) virtual
Install an 802.11s stack.
Parameters
mp The Ptr<MeshPointDevice> to use when setting up the PMP.
Returns
true if successful
Implements ns3::MeshStack.
Definition at line 56 of file dot11s-installer.cc.
References ns3::dot11s::PeerManagementProtocol::GetPeers(), m_root, ns3::MakeCallback(), ns3::PeekPointer(), and ns3::dot11s::HwmpProtocol::PeerLinkStatus().
Report()
void ns3::Dot11sStack::Report (const Ptr< MeshPointDevice > mp, std::ostream & os) virtual
Iterate through the referenced devices and protocols and print their statistics.
Parameters
mp The Ptr<MeshPointDevice> to use when setting up the PMP.
os The output stream
Implements ns3::MeshStack.
Definition at line 84 of file dot11s-installer.cc.
References ns3::WifiNetDevice::GetMac(), ns3::Object::GetObject(), third::mac, and NS_ASSERT.
ResetStats()
void ns3::Dot11sStack::ResetStats (const Ptr< MeshPointDevice > mp) virtual
Reset the statistics on the referenced devices and protocols.
Parameters
mp The Ptr<MeshPointDevice> to use when setting up the PMP.
Implements ns3::MeshStack.
Definition at line 106 of file dot11s-installer.cc.
References ns3::WifiNetDevice::GetMac(), ns3::Object::GetObject(), third::mac, and NS_ASSERT.
Member Data Documentation
m_root
Mac48Address ns3::Dot11sStack::m_root private
root
Definition at line 79 of file dot11s-installer.h.
Referenced by GetTypeId(), and InstallStack().
The documentation for this class was generated from the following files:
src/mesh/helper/dot11s/dot11s-installer.h
src/mesh/helper/dot11s/dot11s-installer.cc