ns-3: ns3::MinstrelHtWifiManager Class Reference
ns3::MinstrelHtWifiManager Class Reference
Wifi Models
Implementation of Minstrel HT Rate Control Algorithm.
#include "minstrel-ht-wifi-manager.h"
Public Types
typedef void(* RateChangeTracedCallback) (const uint64_t rate, const Mac48Address remoteAddress)
TracedCallback signature for rate change events.
Public Types inherited from ns3::WifiRemoteStationManager
typedef void(* PowerChangeTracedCallback) (double oldPower, double newPower, Mac48Address remoteAddress)
TracedCallback signature for power change events.
enum ProtectionMode { RTS_CTS , CTS_TO_SELF }
ProtectionMode enumeration.
typedef void(* RateChangeTracedCallback) (DataRate oldRate, DataRate newRate, Mac48Address remoteAddress)
TracedCallback signature for rate change events.
typedef std::vector< WifiRemoteStation * > Stations
A vector of WifiRemoteStations.
typedef std::vector< WifiRemoteStationState * > StationStates
A vector of WifiRemoteStationStates.
Public Member Functions
MinstrelHtWifiManager ()
virtual ~MinstrelHtWifiManager ()
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
void SetupMac (const Ptr< WifiMac > mac)
Set up MAC associated with this device since it is the object that knows the full set of timing parameters (e.g.
void SetupPhy (const Ptr< WifiPhy > phy)
Set up PHY associated with this device since it is the object that knows the full set of transmit rates that are supported.
Public Member Functions inherited from ns3::WifiRemoteStationManager
WifiRemoteStationManager ()
virtual ~WifiRemoteStationManager ()
void AddAllSupportedMcs (Mac48Address address)
Invoked in a STA or AP to store all of the MCS supported by a destination which is also supported locally.
void AddAllSupportedModes (Mac48Address address)
Invoked in a STA or AP to store all of the modes supported by a destination which is also supported locally.
void AddBasicMcs (WifiMode mcs)
Add a given Modulation and Coding Scheme (MCS) index to the set of basic MCS.
void AddBasicMode (WifiMode mode)
Invoked in a STA upon association to store the set of rates which belong to the BSSBasicRateSet of the associated AP and which are supported locally.
void AddStationHeCapabilities (Mac48Address from, HeCapabilities heCapabilities)
Records HE capabilities of the remote station.
void AddStationHtCapabilities (Mac48Address from, HtCapabilities htCapabilities)
Records HT capabilities of the remote station.
void AddStationVhtCapabilities (Mac48Address from, VhtCapabilities vhtCapabilities)
Records VHT capabilities of the remote station.
void AddSupportedErpSlotTime (Mac48Address address, bool isShortSlotTimeSupported)
Record whether the short ERP slot time is supported by the station.
void AddSupportedMcs (Mac48Address address, WifiMode mcs)
Record the MCS index supported by the station.
void AddSupportedMode (Mac48Address address, WifiMode mode)
Invoked in a STA or AP to store the set of modes supported by a destination which is also supported locally.
void AddSupportedPhyPreamble (Mac48Address address, bool isShortPreambleSupported)
Record whether the short PHY preamble is supported by the station.
WifiMode GetBasicMcs (uint8_t i) const
Return the MCS at the given list index.
WifiMode GetBasicMode (uint8_t i) const
Return a basic mode from the set of basic modes.
uint16_t GetChannelWidthSupported (Mac48Address address) const
Return the channel width supported by the station.
WifiTxVector GetCtsToSelfTxVector (void)
Since CTS-to-self parameters are not dependent on the station, it is implemented in wifi remote station manager.
WifiTxVector GetDataTxVector (const WifiMacHeader &header)
WifiMode GetDefaultMcs (void) const
Return the default Modulation and Coding Scheme (MCS) index.
WifiMode GetDefaultMode (void) const
Return the default transmission mode.
uint8_t GetDefaultTxPowerLevel (void) const
uint32_t GetFragmentationThreshold (void) const
Return the fragmentation threshold.
uint32_t GetFragmentOffset (Mac48Address address, const WifiMacHeader *header, Ptr< const Packet > packet, uint32_t fragmentNumber)
uint32_t GetFragmentSize (Mac48Address address, const WifiMacHeader *header, Ptr< const Packet > packet, uint32_t fragmentNumber)
bool GetGreenfieldSupported (Mac48Address address) const
Return whether the station supports Greenfield or not.
bool GetGreenfieldSupported (void) const
Return whether the device has HT Greenfield support enabled.
uint16_t GetGuardInterval (void) const
Return the supported HE guard interval duration (in nanoseconds).
bool GetHeSupported (Mac48Address address) const
Return whether the station supports HE or not.
bool GetHeSupported (void) const
Return whether the device has HE capability support enabled.
bool GetHtSupported (Mac48Address address) const
Return whether the station supports HT or not.
bool GetHtSupported (void) const
Return whether the device has HT capability support enabled.
WifiRemoteStationInfo GetInfo (Mac48Address address)
bool GetLdpcSupported (Mac48Address address) const
Return whether the station supports LDPC or not.
bool GetLdpcSupported (void) const
Return whether the device has LDPC support enabled.
uint8_t GetMaxNumberOfTransmitStreams (void) const
uint8_t GetNBasicMcs (void) const
Return the number of basic MCS index.
uint8_t GetNBasicModes (void) const
Return the number of basic modes we support.
uint8_t GetNMcsSupported (Mac48Address address) const
Return the number of MCS supported by the station.
uint32_t GetNNonErpBasicModes (void) const
Return the number of non-ERP basic modes we support.
WifiMode GetNonErpBasicMode (uint8_t i) const
Return a basic mode from the set of basic modes that is not an ERP mode.
WifiMode GetNonUnicastMode (void) const
Return a mode for non-unicast packets.
uint8_t GetNumberOfAntennas (void) const
uint8_t GetNumberOfSupportedStreams (Mac48Address address) const
Return the number of spatial streams supported by the station.
bool GetPcfSupported (void) const
Return whether the device has PCF capability support enabled.
bool GetQosSupported (Mac48Address address) const
Return whether the given station is QoS capable.
WifiTxVector GetRtsTxVector (Mac48Address address)
bool GetShortGuardIntervalSupported (Mac48Address address) const
Return whether the station supports HT/VHT short guard interval.
bool GetShortGuardIntervalSupported (void) const
Return whether the device has SGI support enabled.
bool GetShortPreambleEnabled (void) const
Return whether the device uses short PHY preambles.
bool GetShortPreambleSupported (Mac48Address address) const
Return whether the station supports short PHY preamble or not.
bool GetShortSlotTimeEnabled (void) const
Return whether the device uses short slot time.
bool GetShortSlotTimeSupported (Mac48Address address) const
Return whether the station supports short ERP slot time or not.
Ptr< const HeCapabilities > GetStationHeCapabilities (Mac48Address from)
Return the HE capabilities sent by the remote station.
Ptr< const HtCapabilities > GetStationHtCapabilities (Mac48Address from)
Return the HT capabilities sent by the remote station.
Ptr< const VhtCapabilities > GetStationVhtCapabilities (Mac48Address from)
Return the VHT capabilities sent by the remote station.
bool GetUseGreenfieldProtection (void) const
Return whether protection for stations that do not support HT Greenfield format is enabled.
bool GetUseNonErpProtection (void) const
Return whether the device supports protection of non-ERP stations.
bool GetUseNonHtProtection (void) const
Return whether the device supports protection of non-HT stations.
bool GetVhtSupported (Mac48Address address) const
Return whether the station supports VHT or not.
bool GetVhtSupported (void) const
Return whether the device has VHT capability support enabled.
bool IsAssociated (Mac48Address address) const
Return whether the station associated.
bool IsBrandNew (Mac48Address address) const
Return whether the station state is brand new.
bool IsLastFragment (Mac48Address address, const WifiMacHeader *header, Ptr< const Packet > packet, uint32_t fragmentNumber)
bool IsWaitAssocTxOk (Mac48Address address) const
Return whether we are waiting for an ACK for the association response we sent.
bool NeedCtsToSelf (WifiTxVector txVector)
Return if we need to do CTS-to-self before sending a DATA.
bool NeedFragmentation (Mac48Address address, const WifiMacHeader *header, Ptr< const Packet > packet)
bool NeedRetransmission (Mac48Address address, const WifiMacHeader *header, Ptr< const Packet > packet)
bool NeedRts (const WifiMacHeader &header, uint32_t size)
void RecordDisassociated (Mac48Address address)
Records that the STA was disassociated.
void RecordGotAssocTxFailed (Mac48Address address)
Records that we missed an ACK for the association response we sent.
void RecordGotAssocTxOk (Mac48Address address)
Records that we got an ACK for the association response we sent.
void RecordWaitAssocTxOk (Mac48Address address)
Records that we are waiting for an ACK for the association response we sent.
void RemoveAllSupportedMcs (Mac48Address address)
Invoked in a STA or AP to delete all of the supported MCS by a destination.
void ReportAmpduTxStatus (Mac48Address address, uint8_t nSuccessfulMpdus, uint8_t nFailedMpdus, double rxSnr, double dataSnr, WifiTxVector dataTxVector)
Typically called per A-MPDU, either when a Block ACK was successfully received or when a BlockAckTimeout has elapsed.
void ReportDataFailed (Mac48Address address, const WifiMacHeader *header, uint32_t packetSize)
Should be invoked whenever the AckTimeout associated to a transmission attempt expires.
void ReportDataOk (Mac48Address address, const WifiMacHeader *header, double ackSnr, WifiMode ackMode, double dataSnr, WifiTxVector dataTxVector, uint32_t packetSize)
Should be invoked whenever we receive the ACK associated to a data packet we just sent.
void ReportFinalDataFailed (Mac48Address address, const WifiMacHeader *header, uint32_t packetSize)
Should be invoked after calling ReportDataFailed if NeedRetransmission returns false.
void ReportFinalRtsFailed (Mac48Address address, const WifiMacHeader *header)
Should be invoked after calling ReportRtsFailed if NeedRetransmission returns false.
void ReportRtsFailed (Mac48Address address, const WifiMacHeader *header)
Should be invoked whenever the RtsTimeout associated to a transmission attempt expires.
void ReportRtsOk (Mac48Address address, const WifiMacHeader *header, double ctsSnr, WifiMode ctsMode, double rtsSnr)
Should be invoked whenever we receive the CTS associated to an RTS we just sent.
void ReportRxOk (Mac48Address address, double rxSnr, WifiMode txMode)
void Reset (void)
Reset the station, invoked in a STA upon dis-association or in an AP upon reboot.
void SetDefaultTxPowerLevel (uint8_t txPower)
Set the default transmission power level.
void SetFragmentationThreshold (uint32_t threshold)
Sets a fragmentation threshold.
void SetMaxSlrc (uint32_t maxSlrc)
Sets the maximum STA long retry count (SLRC).
void SetMaxSsrc (uint32_t maxSsrc)
Sets the maximum STA short retry count (SSRC).
void SetPcfSupported (bool enable)
Enable or disable PCF capability support.
void SetQosSupport (Mac48Address from, bool qosSupported)
Records QoS support of the remote station.
void SetRtsCtsThreshold (uint32_t threshold)
Sets the RTS threshold.
void SetShortPreambleEnabled (bool enable)
Enable or disable short PHY preambles.
void SetShortSlotTimeEnabled (bool enable)
Enable or disable short slot time.
void SetUseGreenfieldProtection (bool enable)
Enable or disable protection for stations that do not support HT Greenfield format.
void SetUseNonErpProtection (bool enable)
Enable or disable protection for non-ERP stations.
void SetUseNonHtProtection (bool enable)
Enable or disable protection for non-HT stations.
void UpdateFragmentationThreshold (void)
Typically called to update the fragmentation threshold at the start of a new transmission.
bool UseGreenfieldForDestination (Mac48Address dest) const
bool UseLdpcForDestination (Mac48Address dest) const
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::WifiRemoteStationManager
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void AddFirstMpduTxTime (uint8_t groupId, WifiMode mode, Time t)
Save a TxTime to the vector of groups.
void AddMpduTxTime (uint8_t groupId, WifiMode mode, Time t)
Save a TxTime to the vector of groups.
double CalculateEwmsd (double oldEwmsd, double currentProb, double ewmaProb, double weight)
Perform EWMSD (Exponentially Weighted Moving Standard Deviation) calculation.
Time CalculateMpduTxDuration (Ptr< WifiPhy > phy, uint8_t streams, uint8_t sgi, uint16_t chWidth, WifiMode mode, MpduType mpduType)
Estimates the TxTime of a frame with a given mode and group (stream, guard interval and channel width).
void CalculateRetransmits (MinstrelHtWifiRemoteStation *station, uint16_t index)
Calculate the number of retransmissions to set for the index rate.
void CalculateRetransmits (MinstrelHtWifiRemoteStation *station, uint8_t groupId, uint8_t rateId)
Calculate the number of retransmissions to set for the (groupId, rateId) rate.
double CalculateThroughput (MinstrelHtWifiRemoteStation *station, uint8_t groupId, uint8_t rateId, double ewmaProb)
Return the average throughput of the MCS defined by groupId and rateId.
Time CalculateTimeUnicastPacket (Time dataTransmissionTime, uint32_t shortRetries, uint32_t longRetries)
Estimate the time to transmit the given packet with the given number of retries.
void CheckInit (MinstrelHtWifiRemoteStation *station)
Check for initializations.
uint32_t CountRetries (MinstrelHtWifiRemoteStation *station)
Count retries.
WifiRemoteStation * DoCreateStation (void) const
WifiTxVector DoGetDataTxVector (WifiRemoteStation *station)
WifiTxVector DoGetRtsTxVector (WifiRemoteStation *station)
void DoInitialize (void)
Initialize() implementation.
bool DoNeedRetransmission (WifiRemoteStation *st, Ptr< const Packet > packet, bool normally)
void DoReportAmpduTxStatus (WifiRemoteStation *station, uint8_t nSuccessfulMpdus, uint8_t nFailedMpdus, double rxSnr, double dataSnr, uint16_t dataChannelWidth, uint8_t dataNss)
Typically called per A-MPDU, either when a Block ACK was successfully received or when a BlockAckTimeout has elapsed.
void DoReportDataFailed (WifiRemoteStation *station)
This method is a pure virtual method that must be implemented by the sub-class.
void DoReportDataOk (WifiRemoteStation *station, double ackSnr, WifiMode ackMode, double dataSnr, uint16_t dataChannelWidth, uint8_t dataNss)
This method is a pure virtual method that must be implemented by the sub-class.
void DoReportFinalDataFailed (WifiRemoteStation *station)
This method is a pure virtual method that must be implemented by the sub-class.
void DoReportFinalRtsFailed (WifiRemoteStation *station)
This method is a pure virtual method that must be implemented by the sub-class.
void DoReportRtsFailed (WifiRemoteStation *station)
This method is a pure virtual method that must be implemented by the sub-class.
void DoReportRtsOk (WifiRemoteStation *station, double ctsSnr, WifiMode ctsMode, double rtsSnr)
This method is a pure virtual method that must be implemented by the sub-class.
void DoReportRxOk (WifiRemoteStation *station, double rxSnr, WifiMode txMode)
This method is a pure virtual method that must be implemented by the sub-class.
uint16_t FindRate (MinstrelHtWifiRemoteStation *station)
Find a rate to use from Minstrel Table.
Time GetFirstMpduTxTime (uint8_t groupId, WifiMode mode) const
Obtain the TxTime saved in the group information.
uint8_t GetGroupId (uint16_t index)
Return the groupId from the global index.
WifiModeList GetHtDeviceMcsList (void) const
Returns a list of only the HT MCS supported by the device.
uint8_t GetHtGroupId (uint8_t txstreams, uint8_t sgi, uint16_t chWidth)
Returns the groupId of a HT MCS with the given number of streams, if using SGI and the channel width used.
uint16_t GetIndex (uint8_t groupId, uint8_t rateId)
Returns the global index corresponding to the groupId and rateId.
uint16_t GetLowestIndex (MinstrelHtWifiRemoteStation *station)
Returns the lowest global index of the rates supported by the station.
uint16_t GetLowestIndex (MinstrelHtWifiRemoteStation *station, uint8_t groupId)
Returns the lowest global index of the rates supported by in the group.
Time GetMpduTxTime (uint8_t groupId, WifiMode mode) const
Obtain the TxTime saved in the group information.
uint16_t GetNextSample (MinstrelHtWifiRemoteStation *station)
Getting the next sample from Sample Table.
uint8_t GetRateId (uint16_t index)
For managing rates from different groups, a global index for all rates in all groups is used.
WifiModeList GetVhtDeviceMcsList (void) const
Returns a list of only the VHT MCS supported by the device.
uint8_t GetVhtGroupId (uint8_t txstreams, uint8_t sgi, uint16_t chWidth)
Returns the groupId of a VHT MCS with the given number of streams, if using SGI and the channel width used.
void InitSampleTable (MinstrelHtWifiRemoteStation *station)
Initialize Sample Table.
bool IsValidMcs (Ptr< WifiPhy > phy, uint8_t streams, uint16_t chWidth, WifiMode mode)
Check the validity of a combination of number of streams, chWidth and mode.
void PrintSampleTable (MinstrelHtWifiRemoteStation *station)
Printing Sample Table.
void PrintTable (MinstrelHtWifiRemoteStation *station)
Printing Minstrel Table.
void RateInit (MinstrelHtWifiRemoteStation *station)
Initialize Minstrel Table.
void SetBestProbabilityRate (MinstrelHtWifiRemoteStation *station, uint16_t index)
Set index rate as maxProbRate if it is better than current value.
void SetBestStationThRates (MinstrelHtWifiRemoteStation *station, uint16_t index)
Set index rate as maxTpRate or maxTp2Rate if is better than current values.
void SetNextSample (MinstrelHtWifiRemoteStation *station)
Set the next sample from Sample Table.
void StatsDump (MinstrelHtWifiRemoteStation *station, uint8_t groupId, std::ofstream &of)
Print group statistics.
void UpdatePacketCounters (MinstrelHtWifiRemoteStation *station, uint8_t nSuccessfulMpdus, uint8_t nFailedMpdus)
Update the number of sample count variables.
void UpdateRate (MinstrelHtWifiRemoteStation *station)
Update rate.
void UpdateRetry (MinstrelHtWifiRemoteStation *station)
Update the number of retries and reset accordingly.
void UpdateStats (MinstrelHtWifiRemoteStation *station)
Update the Minstrel Table.
Private Attributes
TracedValue< uint64_t > m_currentRate
Trace rate changes.
uint8_t m_ewmaLevel
Exponential weighted moving average level (or coefficient).
uint32_t m_frameLength
Frame length used for calculate modes TxTime in bytes.
Ptr< MinstrelWifiManager > m_legacyManager
Pointer to an instance of MinstrelWifiManager.
Time m_legacyUpdateStats
How frequent do we calculate the stats for legacy MinstrelWifiManager.
uint8_t m_lookAroundRate
The % to try other rates than our current rate.
MinstrelMcsGroups m_minstrelGroups
Global array for groups information.
uint8_t m_nSampleCol
Number of sample columns.
uint8_t m_numGroups
Number of groups Minstrel should consider.
uint8_t m_numRates
Number of rates per group Minstrel should consider.
bool m_printStats
If statistics table should be printed.
Ptr< UniformRandomVariable > m_uniformRandomVariable
Provides uniform random variables.
Time m_updateStats
How frequent do we calculate the stats.
bool m_useVhtOnly
If only VHT MCS should be used, instead of HT and VHT.
Additional Inherited Members
Protected Member Functions inherited from ns3::WifiRemoteStationManager
virtual void DoDispose (void)
Destructor implementation.
Mac48Address GetAddress (const WifiRemoteStation *station) const
Return the address of the station.
bool GetAggregation (const WifiRemoteStation *station) const
Return whether the given station supports A-MPDU.
uint16_t GetChannelWidth (const WifiRemoteStation *station) const
Return the channel width supported by the station.
bool GetGreenfield (const WifiRemoteStation *station) const
Return whether the station supports Greenfield or not.
uint16_t GetGuardInterval (const WifiRemoteStation *station) const
Return the HE guard interval duration supported by the station.
bool GetHeSupported (const WifiRemoteStation *station) const
Return whether the given station is HE capable.
bool GetHtSupported (const WifiRemoteStation *station) const
Return whether the given station is HT capable.
Ptr< WifiMac > GetMac (void) const
Return the WifiMac.
WifiMode GetMcsSupported (const WifiRemoteStation *station, uint8_t i) const
Return the WifiMode supported by the specified station at the specified index.
uint8_t GetNess (const WifiRemoteStation *station) const
uint8_t GetNMcsSupported (const WifiRemoteStation *station) const
Return the number of MCS supported by the given station.
uint32_t GetNNonErpSupported (const WifiRemoteStation *station) const
Return the number of non-ERP modes supported by the given station.
WifiMode GetNonErpSupported (const WifiRemoteStation *station, uint8_t i) const
Return whether non-ERP mode associated with the specified station at the specified index.
uint8_t GetNSupported (const WifiRemoteStation *station) const
Return the number of modes supported by the given station.
uint8_t GetNumberOfSupportedStreams (const WifiRemoteStation *station) const
Return the number of supported streams the station has.
Ptr< WifiPhy > GetPhy (void) const
Return the WifiPhy.
bool GetQosSupported (const WifiRemoteStation *station) const
Return whether the given station is QoS capable.
bool GetShortGuardIntervalSupported (const WifiRemoteStation *station) const
Return whether the given station supports HT/VHT short guard interval.
WifiMode GetSupported (const WifiRemoteStation *station, uint8_t i) const
Return whether mode associated with the specified station at the specified index.
bool GetVhtSupported (const WifiRemoteStation *station) const
Return whether the given station is VHT capable.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implementation of Minstrel HT Rate Control Algorithm.
Minstrel-HT is a rate adaptation mechanism for the 802.11n/ac standard based on Minstrel, and is based on the approach of probing the channel to dynamically learn about working rates that can be supported. Minstrel-HT is designed for high-latency devices that implement a Multiple Rate Retry (MRR) chain. This kind of device does not give feedback for every frame retransmission, but only when a frame was correctly transmitted (an Ack is received) or a frame transmission completely fails (all retransmission attempts fail). The MRR chain is used to advise the hardware about which rate to use when retransmitting a frame.
Minstrel-HT adapts the MCS, channel width, number of streams, and short guard interval (enabled or disabled). For keeping statistics, it arranges MCS in groups, where each group is defined by the tuple (streams, SGI, channel width). There is a vector of all groups supported by the PHY layer of the transmitter; for each group, the capabilities and the estimated duration of its rates are maintained.
Each station maintains a table of groups statistics. For each group, a flag indicates if the group is supported by the station. Different stations communicating with an AP can have different capabilities.
Stats are updated per A-MPDU when receiving AmpduTxStatus. If the number of successful or failed MPDUs is greater than zero (a BlockAck was received), the rates are also updated. If the number of successful and failed MPDUs is zero (BlockAck timeout), then the rate selected is based on the MRR chain.
On each update interval, it sets the maxThrRate, the secondmaxThrRate and the maxProbRate for the MRR chain. These rates are only used when an entire A-MPDU fails and is retried.
Differently from legacy minstrel, sampling is not done based on "lookaround ratio", but assuring all rates are sampled at least once each interval. However, it samples less often the low rates and high probability of error rates.
When this rate control is configured but non-legacy modes are not supported, Minstrel-HT uses legacy Minstrel (minstrel-wifi-manager) for rate control.
This RAA does not support HE modes yet and will error exit if the user tries to configure this RAA with a Wi-Fi MAC that supports 802.11ax or higher.
Config Paths
ns3::MinstrelHtWifiManager is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/RemoteStationManager/$ns3::MinstrelHtWifiManager"
Attributes
UpdateStatistics: The interval between updating statistics table
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +5e+07ns
Flags: construct write read
LegacyUpdateStatistics: The interval between updating statistics table (for legacy Minstrel)
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+08ns
Flags: construct write read
LookAroundRate: The percentage to try other rates (for legacy Minstrel)
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:100
Initial value: 10
Flags: construct write read
EWMA: EWMA level
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:100
Initial value: 75
Flags: construct write read
SampleColumn: The number of columns used for sampling
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Initial value: 10
Flags: construct write read
PacketLength: The packet length used for calculating mode TxTime (bytes)
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 1200
Flags: construct write read
UseVhtOnly: Use only VHT MCSs (and not HT) when VHT is available
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
PrintStats: Control the printing of the statistics table
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
Attributes defined in parent class ns3::WifiRemoteStationManager
MaxSsrc: The maximum number of retransmission attempts for any packet with size <= RtsCtsThreshold. This value will not have any effect on some rate control algorithms.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 7
Flags: construct write
MaxSlrc: The maximum number of retransmission attempts for any packet with size > RtsCtsThreshold. This value will not have any effect on some rate control algorithms.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 4
Flags: construct write
RtsCtsThreshold: If the size of the PSDU is bigger than this value, we use an RTS/CTS handshake before sending the data frame.This value will not have any effect on some rate control algorithms.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 65535
Flags: construct write
FragmentationThreshold: If the size of the PSDU is bigger than this value, we fragment it such that the size of the fragments are equal or smaller. This value does not apply when it is carried in an A-MPDU. This value will not have any effect on some rate control algorithms.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 65535
Flags: construct write read
NonUnicastMode: Wifi mode used for non-unicast transmissions.
Set with class: WifiModeValue
Underlying type: WifiMode
Initial value: Invalid-WifiMode
Flags: construct write read
DefaultTxPowerLevel: Default power level to be used for transmissions. This is the power level that is used by all those WifiManagers that do not implement TX power control.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Initial value: 0
Flags: construct write read
ErpProtectionMode: Protection mode used when non-ERP STAs are connected to an ERP AP: Rts-Cts or Cts-To-Self
Set with class: ns3::EnumValue
Underlying type:
Initial value: Cts-To-Self
Flags: construct write read
HtProtectionMode: Protection mode used when non-HT STAs are connected to a HT AP: Rts-Cts or Cts-To-Self
Set with class: ns3::EnumValue
Underlying type:
Initial value: Cts-To-Self
Flags: construct write read
TraceSources
Rate: Traced value for rate changes (b/s)
Callback signature: ns3::TracedValueCallback::Uint64
TraceSources defined in parent class ns3::WifiRemoteStationManager
MacTxRtsFailed: The transmission of a RTS by the MAC layer has failed
Callback signature: ns3::Mac48Address::TracedCallback
MacTxDataFailed: The transmission of a data packet by the MAC layer has failed
Callback signature: ns3::Mac48Address::TracedCallback
MacTxFinalRtsFailed: The transmission of a RTS has exceeded the maximum number of attempts
Callback signature: ns3::Mac48Address::TracedCallback
MacTxFinalDataFailed: The transmission of a data packet has exceeded the maximum number of attempts
Callback signature: ns3::Mac48Address::TracedCallback
Size of this type is 432 bytes (on a 64-bit architecture).
Definition at line 188 of file minstrel-ht-wifi-manager.h.
Member Typedef Documentation
RateChangeTracedCallback
typedef void(* ns3::MinstrelHtWifiManager::RateChangeTracedCallback) (const uint64_t rate, const Mac48Address remoteAddress)
TracedCallback signature for rate change events.
Parameters
[in] rate The new rate.
[in] address The remote station MAC address.
Definition at line 219 of file minstrel-ht-wifi-manager.h.
Constructor & Destructor Documentation
MinstrelHtWifiManager()
ns3::MinstrelHtWifiManager::MinstrelHtWifiManager ()
Create the legacy Minstrel manager in case HT is not supported by the device or non-HT stations want to associate.
Definition at line 130 of file minstrel-ht-wifi-manager.cc.
References m_legacyManager, m_uniformRandomVariable, and NS_LOG_FUNCTION.
~MinstrelHtWifiManager()
ns3::MinstrelHtWifiManager::~MinstrelHtWifiManager () virtual
Definition at line 144 of file minstrel-ht-wifi-manager.cc.
References m_minstrelGroups, m_numGroups, and NS_LOG_FUNCTION.
Member Function Documentation
AddFirstMpduTxTime()
void ns3::MinstrelHtWifiManager::AddFirstMpduTxTime (uint8_t groupId, WifiMode mode, Time t) private
Save a TxTime to the vector of groups.
Parameters
groupId the group ID
mode the wifi mode
t the transmit time
Definition at line 341 of file minstrel-ht-wifi-manager.cc.
References m_minstrelGroups, and NS_LOG_FUNCTION.
Referenced by DoInitialize().
AddMpduTxTime()
void ns3::MinstrelHtWifiManager::AddMpduTxTime (uint8_t groupId, WifiMode mode, Time t) private
Save a TxTime to the vector of groups.
Parameters
groupId the group ID
mode the wifi mode
t the transmit time
Definition at line 357 of file minstrel-ht-wifi-manager.cc.
References m_minstrelGroups, and NS_LOG_FUNCTION.
Referenced by DoInitialize().
AssignStreams()
int64_t ns3::MinstrelHtWifiManager::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 155 of file minstrel-ht-wifi-manager.cc.
References m_legacyManager, m_uniformRandomVariable, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
CalculateEwmsd()
double ns3::MinstrelHtWifiManager::CalculateEwmsd (double oldEwmsd, double currentProb, double ewmaProb, double weight) private
Perform EWMSD (Exponentially Weighted Moving Standard Deviation) calculation.
Parameters
oldEwmsd the old EWMSD
currentProb the current probability
ewmaProb the EWMA probability
weight the weight
Returns
the EWMSD
Definition at line 1565 of file minstrel-ht-wifi-manager.cc.
Referenced by UpdateStats().
CalculateMpduTxDuration()
Time ns3::MinstrelHtWifiManager::CalculateMpduTxDuration (Ptr< WifiPhy > phy, uint8_t streams, uint8_t sgi, uint16_t chWidth, WifiMode mode, MpduType mpduType) private
Estimates the TxTime of a frame with a given mode and group (stream, guard interval and channel width).
Parameters
phy pointer to the wifi PHY
streams the number of streams
sgi short guard interval enabled (0 or 1)
chWidth the channel width (MHz)
mode the wifi mode
mpduType the type of the MPDU
Returns
the transmit time
Definition at line 315 of file minstrel-ht-wifi-manager.cc.
References ns3::WifiPhy::CalculatePhyPreambleAndHeaderDuration(), ns3::WifiPhy::GetPayloadDuration(), m_frameLength, NS_LOG_FUNCTION, third::phy, ns3::WifiTxVector::SetChannelWidth(), ns3::WifiTxVector::SetGuardInterval(), ns3::WifiTxVector::SetMode(), ns3::WifiTxVector::SetNess(), ns3::WifiTxVector::SetNss(), ns3::WifiTxVector::SetPreambleType(), ns3::WifiTxVector::SetStbc(), and ns3::WIFI_PREAMBLE_HT_MF.
Referenced by DoInitialize().
CalculateRetransmits() [1/2]
void ns3::MinstrelHtWifiManager::CalculateRetransmits (MinstrelHtWifiRemoteStation * station, uint16_t index) private
Calculate the number of retransmissions to set for the index rate.
Parameters
station the minstrel HT wifi remote station
index the index
Definition at line 1506 of file minstrel-ht-wifi-manager.cc.
References GetGroupId(), GetRateId(), ns3::MinstrelHtWifiRemoteStation::m_groupsTable, and NS_LOG_FUNCTION.
Referenced by RateInit(), and UpdateStats().
CalculateRetransmits() [2/2]
void ns3::MinstrelHtWifiManager::CalculateRetransmits (MinstrelHtWifiRemoteStation * station, uint8_t groupId, uint8_t rateId) private
Calculate the number of retransmissions to set for the (groupId, rateId) rate.
Parameters
station the minstrel HT wifi remote station
groupId the group ID
rateId the rate ID
Definition at line 1518 of file minstrel-ht-wifi-manager.cc.
References ns3::WifiPhy::GetBlockAckTxTime(), GetFirstMpduTxTime(), ns3::WifiRemoteStationManager::GetMcsSupported(), GetMpduTxTime(), ns3::WifiRemoteStationManager::GetPhy(), ns3::WifiPhy::GetSifs(), ns3::WifiPhy::GetSlot(), ns3::MinstrelHtWifiRemoteStation::m_avgAmpduLen, ns3::MinstrelHtWifiRemoteStation::m_groupsTable, ns3::MilliSeconds(), ns3::Min(), and NS_LOG_FUNCTION.
CalculateThroughput()
double ns3::MinstrelHtWifiManager::CalculateThroughput (MinstrelHtWifiRemoteStation * station, uint8_t groupId, uint8_t rateId, double ewmaProb) private
Return the average throughput of the MCS defined by groupId and rateId.
Parameters
station the minstrel HT wifi remote station
groupId the group ID
rateId the rate ID
ewmaProb the EWMA probability
Returns
the throughput in bps
Calculating throughput. Do not account throughput if probability of success is below 10% (as done in minstrel_ht linux implementation).
For the throughput calculation, limit the probability value to 90% to account for collision related packet error rate fluctuation.
Definition at line 1274 of file minstrel-ht-wifi-manager.cc.
References ns3::Time::GetSeconds(), and ns3::MinstrelHtWifiRemoteStation::m_groupsTable.
Referenced by StatsDump(), and UpdateStats().
CalculateTimeUnicastPacket()
Time ns3::MinstrelHtWifiManager::CalculateTimeUnicastPacket (Time dataTransmissionTime, uint32_t shortRetries, uint32_t longRetries) private
Estimate the time to transmit the given packet with the given number of retries.
This function is "roughly" the function "calc_usecs_unicast_packet" in minstrel.c in the madwifi implementation.
The basic idea is that, we try to estimate the "average" time used to transmit the packet for the given number of retries while also accounting for the 802.11 congestion window change. The original code in the madwifi seems to estimate the number of backoff slots as the half of the current CW size.
There are four main parts:
wait for DIFS (sense idle channel)
Ack timeouts
Data transmission
backoffs according to CW
Parameters
dataTransmissionTime the data transmission time
shortRetries the short retries
longRetries the long retries
Returns
the unicast packet time
CheckInit()
void ns3::MinstrelHtWifiManager::CheckInit (MinstrelHtWifiRemoteStation * station) private
Check for initializations.
Parameters
station the minstrel HT wifi remote station
Check if the station supports HT. Assume that if the device do not supports HT then the station will not support HT either. We save from using another check and variable.
Definition at line 417 of file minstrel-ht-wifi-manager.cc.
References ns3::WifiRemoteStationManager::GetHtSupported(), ns3::WifiRemoteStationManager::GetNMcsSupported(), InitSampleTable(), m_ewmaLevel, m_frameLength, ns3::MinstrelWifiRemoteStation::m_initialized, ns3::MinstrelHtWifiRemoteStation::m_isHt, m_legacyManager, m_legacyUpdateStats, m_lookAroundRate, ns3::MinstrelWifiRemoteStation::m_minstrelTable, ns3::MinstrelWifiRemoteStation::m_nModes, m_nSampleCol, m_numRates, m_printStats, ns3::MinstrelWifiRemoteStation::m_sampleTable, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, and RateInit().
Referenced by DoGetDataTxVector(), DoGetRtsTxVector(), DoNeedRetransmission(), DoReportAmpduTxStatus(), DoReportDataFailed(), DoReportDataOk(), DoReportFinalDataFailed(), DoReportFinalRtsFailed(), DoReportRtsFailed(), and UpdateRate().
CountRetries()
uint32_t ns3::MinstrelHtWifiManager::CountRetries (MinstrelHtWifiRemoteStation * station) private
Count retries.
Parameters
station the minstrel HT wifi remote station
Returns
the count of retries
Definition at line 985 of file minstrel-ht-wifi-manager.cc.
References GetGroupId(), GetRateId(), ns3::MinstrelHtWifiRemoteStation::m_groupsTable, ns3::MinstrelWifiRemoteStation::m_isSampling, ns3::MinstrelWifiRemoteStation::m_maxProbRate, ns3::MinstrelWifiRemoteStation::m_maxTpRate, and ns3::MinstrelWifiRemoteStation::m_maxTpRate2.
Referenced by DoNeedRetransmission(), and DoReportAmpduTxStatus().
DoCreateStation()
WifiRemoteStation * ns3::MinstrelHtWifiManager::DoCreateStation (void) const private virtual
Returns
a new station data structure
Assume the station is HT. When correct information available it will be checked.
Implements ns3::WifiRemoteStationManager.
Definition at line 364 of file minstrel-ht-wifi-manager.cc.
References ns3::WifiRemoteStationManager::GetHtSupported(), ns3::MinstrelHtWifiRemoteStation::m_ampduLen, ns3::MinstrelHtWifiRemoteStation::m_ampduPacketCount, ns3::MinstrelHtWifiRemoteStation::m_avgAmpduLen, ns3::MinstrelWifiRemoteStation::m_col, ns3::MinstrelWifiRemoteStation::m_index, ns3::MinstrelWifiRemoteStation::m_initialized, ns3::MinstrelHtWifiRemoteStation::m_isHt, ns3::MinstrelWifiRemoteStation::m_isSampling, ns3::MinstrelWifiRemoteStation::m_longRetry, ns3::MinstrelWifiRemoteStation::m_maxProbRate, ns3::MinstrelWifiRemoteStation::m_maxTpRate, ns3::MinstrelWifiRemoteStation::m_maxTpRate2, ns3::MinstrelWifiRemoteStation::m_nextStatsUpdate, ns3::MinstrelWifiRemoteStation::m_nModes, ns3::MinstrelHtWifiRemoteStation::m_numSamplesSlow, ns3::MinstrelHtWifiRemoteStation::m_sampleCount, ns3::MinstrelWifiRemoteStation::m_sampleDeferred, ns3::MinstrelHtWifiRemoteStation::m_sampleGroup, ns3::MinstrelWifiRemoteStation::m_samplePacketsCount, ns3::MinstrelWifiRemoteStation::m_sampleRate, ns3::MinstrelHtWifiRemoteStation::m_sampleTries, ns3::MinstrelHtWifiRemoteStation::m_sampleWait, ns3::MinstrelWifiRemoteStation::m_shortRetry, ns3::MinstrelWifiRemoteStation::m_totalPacketsCount, ns3::MinstrelWifiRemoteStation::m_txrate, m_updateStats, ns3::Simulator::Now(), and NS_LOG_FUNCTION.
DoGetDataTxVector()
WifiTxVector ns3::MinstrelHtWifiManager::DoGetDataTxVector (WifiRemoteStation * station) private virtual
Parameters
station the station that we need to communicate
Returns
the TXVECTOR to use to send a packet to the station
Note: This method is called before sending a unicast packet or a fragment of a unicast packet to decide which transmission mode to use.
Implements ns3::WifiRemoteStationManager.
Definition at line 820 of file minstrel-ht-wifi-manager.cc.
References CheckInit(), ns3::McsGroup::chWidth, ns3::WifiRemoteStationManager::GetAddress(), ns3::WifiRemoteStationManager::GetAggregation(), ns3::WifiRemoteStationManager::GetChannelWidth(), ns3::GetChannelWidthForTransmission(), ns3::WifiMode::GetDataRate(), ns3::WifiRemoteStationManager::GetDefaultTxPowerLevel(), GetGroupId(), ns3::WifiRemoteStationManager::GetMcsSupported(), ns3::WifiTxVector::GetMode(), ns3::WifiMode::GetModulationClass(), ns3::WifiRemoteStationManager::GetNess(), ns3::WifiRemoteStationManager::GetNumberOfAntennas(), ns3::WifiRemoteStationManager::GetNumberOfSupportedStreams(), ns3::GetPreambleForTransmission(), GetRateId(), ns3::WifiRemoteStationManager::GetShortGuardIntervalSupported(), ns3::WifiRemoteStationManager::GetShortPreambleEnabled(), m_currentRate, ns3::MinstrelHtWifiRemoteStation::m_groupsTable, ns3::MinstrelWifiRemoteStation::m_initialized, ns3::MinstrelHtWifiRemoteStation::m_isHt, ns3::MinstrelWifiRemoteStation::m_isSampling, m_legacyManager, m_minstrelGroups, ns3::MinstrelWifiRemoteStation::m_txrate, NS_FATAL_ERROR, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::McsGroup::sgi, ns3::McsGroup::streams, and ns3::WifiRemoteStationManager::UseGreenfieldForDestination().
DoGetRtsTxVector()
WifiTxVector ns3::MinstrelHtWifiManager::DoGetRtsTxVector (WifiRemoteStation * station) private virtual
Parameters
station the station that we need to communicate
Returns
the transmission mode to use to send an RTS to the station
Note: This method is called before sending an RTS to a station to decide which transmission mode to use for the RTS.
Implements ns3::WifiRemoteStationManager.
Definition at line 873 of file minstrel-ht-wifi-manager.cc.
References CheckInit(), ns3::WifiRemoteStationManager::GetAddress(), ns3::WifiRemoteStationManager::GetAggregation(), ns3::WifiRemoteStationManager::GetBasicMode(), ns3::WifiRemoteStationManager::GetChannelWidth(), ns3::GetChannelWidthForTransmission(), ns3::WifiMode::GetDataRate(), ns3::WifiRemoteStationManager::GetDefaultTxPowerLevel(), GetGroupId(), ns3::WifiRemoteStationManager::GetMcsSupported(), ns3::WifiMode::GetModulationClass(), ns3::WifiRemoteStationManager::GetNBasicModes(), ns3::WifiMode::GetNonHtReferenceRate(), ns3::WifiRemoteStationManager::GetPhy(), ns3::GetPreambleForTransmission(), GetRateId(), ns3::WifiRemoteStationManager::GetShortPreambleEnabled(), ns3::MinstrelHtWifiRemoteStation::m_groupsTable, ns3::MinstrelWifiRemoteStation::m_initialized, ns3::MinstrelHtWifiRemoteStation::m_isHt, m_legacyManager, ns3::MinstrelWifiRemoteStation::m_txrate, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, third::phy, and ns3::WifiRemoteStationManager::UseGreenfieldForDestination().
DoInitialize()
void ns3::MinstrelHtWifiManager::DoInitialize (void) private virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Here we initialize m_minstrelGroups with all the possible groups. If a group is not supported by the device, then it is marked as not supported. Then, after all initializations are finished, we check actual support for each receiving station.
Initialize the groups array. The HT groups come first, then the VHT ones. Minstrel maintains different types of indexes:
A global continuous index, which identifies all rates within all groups, in [0, m_numGroups * m_numRates]
A groupId, which indexes a group in the array, in [0, m_numGroups]
A rateId, which identifies a rate within a group, in [0, m_numRates]
A deviceIndex, which indexes a MCS in the PHY MCS array.
A mcsIndex, which indexes a MCS in the wifi-remote-station-manager supported MCSs array.
Is SGI supported by the transmitter?
Is channel width supported by the transmitter?
Are streams supported by the transmitter?
Is SGI supported by the transmitter?
Is channel width supported by the transmitter?
Are streams supported by the transmitter?
Reimplemented from ns3::Object.
Definition at line 183 of file minstrel-ht-wifi-manager.cc.
References AddFirstMpduTxTime(), AddMpduTxTime(), CalculateMpduTxDuration(), ns3::FIRST_MPDU_IN_AGGREGATE, ns3::WifiRemoteStationManager::GetChannelWidth(), ns3::WifiRemoteStationManager::GetHeSupported(), GetHtDeviceMcsList(), GetHtGroupId(), ns3::WifiRemoteStationManager::GetHtSupported(), ns3::WifiRemoteStationManager::GetPhy(), ns3::WifiRemoteStationManager::GetShortGuardIntervalSupported(), GetVhtDeviceMcsList(), GetVhtGroupId(), ns3::WifiRemoteStationManager::GetVhtSupported(), IsValidMcs(), m_minstrelGroups, m_numGroups, m_numRates, ns3::MAX_HT_GROUP_RATES, ns3::MAX_HT_STREAM_GROUPS, ns3::MAX_HT_WIDTH, ns3::MAX_SUPPORTED_STREAMS, ns3::MAX_VHT_GROUP_RATES, ns3::MAX_VHT_STREAM_GROUPS, ns3::MAX_VHT_WIDTH, ns3::MIDDLE_MPDU_IN_AGGREGATE, NS_FATAL_ERROR, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
DoNeedRetransmission()
bool ns3::MinstrelHtWifiManager::DoNeedRetransmission (WifiRemoteStation * station, Ptr< const Packet > packet, bool normally) private virtual
Parameters
station the station that we need to communicate
packet the packet to send
normally indicates whether the normal 802.11 data retransmission mechanism would request that the data is retransmitted or not.
Returns
true if we want to resend a packet after a failed transmission attempt, false otherwise.
Note: This method is called after any unicast packet transmission (control, management, or data) has been attempted and has failed.
Reimplemented from ns3::WifiRemoteStationManager.
Definition at line 949 of file minstrel-ht-wifi-manager.cc.
References CheckInit(), CountRetries(), ns3::MinstrelWifiRemoteStation::m_initialized, ns3::MinstrelHtWifiRemoteStation::m_isHt, m_legacyManager, ns3::MinstrelWifiRemoteStation::m_longRetry, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
DoReportAmpduTxStatus()
void ns3::MinstrelHtWifiManager::DoReportAmpduTxStatus (WifiRemoteStation * station, uint8_t nSuccessfulMpdus, uint8_t nFailedMpdus, double rxSnr, double dataSnr, uint16_t dataChannelWidth, uint8_t dataNss) private virtual
Typically called per A-MPDU, either when a Block ACK was successfully received or when a BlockAckTimeout has elapsed.
This method is a virtual method that must be implemented by the sub-class intended to handle A-MPDUs. This allows different types of WifiRemoteStationManager to respond differently.
Parameters
station the station that sent the DATA to us
nSuccessfulMpdus number of successfully transmitted MPDUs. A value of 0 means that the Block ACK was missed.
nFailedMpdus number of unsuccessfully transmitted MPDUs.
rxSnr received SNR of the block ack frame itself
dataSnr data SNR reported by remote station
dataChannelWidth the channel width (in MHz) of the A-MPDU we sent
dataNss the number of spatial streams used to send the A-MPDU
Reimplemented from ns3::WifiRemoteStationManager.
Definition at line 635 of file minstrel-ht-wifi-manager.cc.
References CheckInit(), CountRetries(), FindRate(), GetGroupId(), GetRateId(), ns3::MinstrelHtWifiRemoteStation::m_ampduLen, ns3::MinstrelHtWifiRemoteStation::m_ampduPacketCount, ns3::MinstrelHtWifiRemoteStation::m_groupsTable, ns3::MinstrelWifiRemoteStation::m_initialized, ns3::MinstrelHtWifiRemoteStation::m_isHt, ns3::MinstrelWifiRemoteStation::m_isSampling, ns3::MinstrelWifiRemoteStation::m_longRetry, ns3::MinstrelWifiRemoteStation::m_nextStatsUpdate, ns3::MinstrelWifiRemoteStation::m_nModes, ns3::MinstrelWifiRemoteStation::m_sampleDeferred, ns3::MinstrelWifiRemoteStation::m_txrate, ns3::Simulator::Now(), NS_ASSERT_MSG, NS_LOG_DEBUG, NS_LOG_FUNCTION, UpdatePacketCounters(), UpdateRate(), UpdateRetry(), and UpdateStats().
DoReportDataFailed()
void ns3::MinstrelHtWifiManager::DoReportDataFailed (WifiRemoteStation * station) private virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that we failed to send DATA
Implements ns3::WifiRemoteStationManager.
Definition at line 500 of file minstrel-ht-wifi-manager.cc.
References CheckInit(), GetGroupId(), GetRateId(), ns3::MinstrelHtWifiRemoteStation::m_groupsTable, ns3::MinstrelWifiRemoteStation::m_initialized, ns3::MinstrelHtWifiRemoteStation::m_isHt, m_legacyManager, ns3::MinstrelWifiRemoteStation::m_longRetry, ns3::MinstrelWifiRemoteStation::m_txrate, NS_LOG_DEBUG, NS_LOG_FUNCTION, and UpdateRate().
DoReportDataOk()
void ns3::MinstrelHtWifiManager::DoReportDataOk (WifiRemoteStation * station, double ackSnr, WifiMode ackMode, double dataSnr, uint16_t dataChannelWidth, uint8_t dataNss) private virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that we successfully sent RTS
ackSnr the SNR of the ACK we received
ackMode the WifiMode the receiver used to send the ACK
dataSnr the SNR of the DATA we sent
dataChannelWidth the channel width (in MHz) of the DATA we sent
dataNss the number of spatial streams used to send the DATA
Implements ns3::WifiRemoteStationManager.
Definition at line 527 of file minstrel-ht-wifi-manager.cc.
References CheckInit(), FindRate(), GetGroupId(), GetRateId(), ns3::MinstrelHtWifiRemoteStation::m_groupsTable, ns3::MinstrelWifiRemoteStation::m_initialized, ns3::MinstrelHtWifiRemoteStation::m_isHt, ns3::MinstrelWifiRemoteStation::m_isSampling, m_legacyManager, ns3::MinstrelWifiRemoteStation::m_minstrelTable, ns3::MinstrelWifiRemoteStation::m_nextStatsUpdate, ns3::MinstrelWifiRemoteStation::m_nModes, ns3::MinstrelWifiRemoteStation::m_sampleDeferred, ns3::MinstrelWifiRemoteStation::m_txrate, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, UpdatePacketCounters(), UpdateRetry(), and UpdateStats().
DoReportFinalDataFailed()
void ns3::MinstrelHtWifiManager::DoReportFinalDataFailed (WifiRemoteStation * station) private virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that we failed to send DATA
Implements ns3::WifiRemoteStationManager.
Definition at line 588 of file minstrel-ht-wifi-manager.cc.
References CheckInit(), FindRate(), ns3::MinstrelWifiRemoteStation::m_initialized, ns3::MinstrelHtWifiRemoteStation::m_isHt, ns3::MinstrelWifiRemoteStation::m_isSampling, m_legacyManager, ns3::MinstrelWifiRemoteStation::m_nextStatsUpdate, ns3::MinstrelWifiRemoteStation::m_nModes, ns3::MinstrelWifiRemoteStation::m_sampleDeferred, ns3::MinstrelWifiRemoteStation::m_txrate, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, UpdatePacketCounters(), UpdateRetry(), and UpdateStats().
DoReportFinalRtsFailed()
void ns3::MinstrelHtWifiManager::DoReportFinalRtsFailed (WifiRemoteStation * station) private virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that we failed to send RTS
Implements ns3::WifiRemoteStationManager.
Definition at line 486 of file minstrel-ht-wifi-manager.cc.
References CheckInit(), ns3::MinstrelWifiRemoteStation::m_initialized, NS_LOG_DEBUG, NS_LOG_FUNCTION, and UpdateRetry().
DoReportRtsFailed()
void ns3::MinstrelHtWifiManager::DoReportRtsFailed (WifiRemoteStation * station) private virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that we failed to send RTS
Implements ns3::WifiRemoteStationManager.
Definition at line 466 of file minstrel-ht-wifi-manager.cc.
References CheckInit(), ns3::MinstrelWifiRemoteStation::m_initialized, ns3::MinstrelWifiRemoteStation::m_shortRetry, ns3::MinstrelWifiRemoteStation::m_txrate, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
DoReportRtsOk()
void ns3::MinstrelHtWifiManager::DoReportRtsOk (WifiRemoteStation * station, double ctsSnr, WifiMode ctsMode, double rtsSnr) private virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that we successfully sent RTS
ctsSnr the SNR of the CTS we received
ctsMode the WifiMode the receiver used to send the CTS
rtsSnr the SNR of the RTS we sent
Implements ns3::WifiRemoteStationManager.
Definition at line 480 of file minstrel-ht-wifi-manager.cc.
References NS_LOG_FUNCTION.
DoReportRxOk()
void ns3::MinstrelHtWifiManager::DoReportRxOk (WifiRemoteStation * station, double rxSnr, WifiMode txMode) private virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that sent the DATA to us
rxSnr the SNR of the DATA we received
txMode the WifiMode the sender used to send the DATA
Implements ns3::WifiRemoteStationManager.
Definition at line 459 of file minstrel-ht-wifi-manager.cc.
References NS_LOG_DEBUG, and NS_LOG_FUNCTION.
FindRate()
uint16_t ns3::MinstrelHtWifiManager::FindRate (MinstrelHtWifiRemoteStation * station) private
Find a rate to use from Minstrel Table.
Parameters
station the minstrel HT wifi remote station
Returns
the rate in bps
Now go through the table and find an index rate.
Sampling might add some overhead to the frame. Hence, don't use sampling for the currently used rates.
Also do not sample if the probability is already higher than 95% to avoid wasting airtime.
Make sure that lower rates get sampled only occasionally, if the link is working perfectly.
Set flag that we are currently sampling.
set the rate that we're currently sampling
Set flag that we are currently sampling.
set the rate that we're currently sampling
Continue using the best rate.
Definition at line 1053 of file minstrel-ht-wifi-manager.cc.
References ns3::HtRateInfo::ewmaProb, GetGroupId(), GetNextSample(), GetRateId(), ns3::MinstrelHtWifiRemoteStation::m_groupsTable, ns3::MinstrelWifiRemoteStation::m_isSampling, ns3::MinstrelWifiRemoteStation::m_maxProbRate, ns3::MinstrelWifiRemoteStation::m_maxTpRate, ns3::MinstrelWifiRemoteStation::m_maxTpRate2, m_minstrelGroups, ns3::MinstrelHtWifiRemoteStation::m_numSamplesSlow, ns3::MinstrelWifiRemoteStation::m_samplePacketsCount, ns3::MinstrelWifiRemoteStation::m_sampleRate, ns3::MinstrelHtWifiRemoteStation::m_sampleTries, ns3::MinstrelHtWifiRemoteStation::m_sampleWait, ns3::MinstrelWifiRemoteStation::m_totalPacketsCount, ns3::MinstrelWifiRemoteStation::m_txrate, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::HtRateInfo::numSamplesSkipped, and ns3::HtRateInfo::perfectTxTime.
Referenced by DoReportAmpduTxStatus(), DoReportDataOk(), DoReportFinalDataFailed(), and RateInit().
GetFirstMpduTxTime()
Time ns3::MinstrelHtWifiManager::GetFirstMpduTxTime (uint8_t groupId, WifiMode mode) const private
Obtain the TxTime saved in the group information.
Parameters
groupId the group ID
mode the wifi mode
Returns
the transmit time
Definition at line 332 of file minstrel-ht-wifi-manager.cc.
References m_minstrelGroups, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by CalculateRetransmits(), RateInit(), and StatsDump().
GetGroupId()
uint8_t ns3::MinstrelHtWifiManager::GetGroupId (uint16_t index) private
Return the groupId from the global index.
Parameters
index the index
Returns
the group ID
Definition at line 1739 of file minstrel-ht-wifi-manager.cc.
References m_numRates, and NS_LOG_FUNCTION.
Referenced by CalculateRetransmits(), CountRetries(), DoGetDataTxVector(), DoGetRtsTxVector(), DoReportAmpduTxStatus(), DoReportDataFailed(), DoReportDataOk(), FindRate(), SetBestProbabilityRate(), SetBestStationThRates(), and UpdateRate().
GetHtDeviceMcsList()
WifiModeList ns3::MinstrelHtWifiManager::GetHtDeviceMcsList (void) const private
Returns a list of only the HT MCS supported by the device.
Returns
the list of the HT MCS supported
Definition at line 1809 of file minstrel-ht-wifi-manager.cc.
References ns3::WifiMode::GetModulationClass(), ns3::WifiRemoteStationManager::GetPhy(), third::phy, and ns3::WIFI_MOD_CLASS_HT.
Referenced by DoInitialize().
GetHtGroupId()
uint8_t ns3::MinstrelHtWifiManager::GetHtGroupId (uint8_t txstreams, uint8_t sgi, uint16_t chWidth) private
Returns the groupId of a HT MCS with the given number of streams, if using SGI and the channel width used.
Parameters
txstreams the number of streams
sgi short guard interval enabled (0 or 1)
chWidth the channel width (MHz)
Returns
the HT group ID
Definition at line 1746 of file minstrel-ht-wifi-manager.cc.
References ns3::MAX_SUPPORTED_STREAMS, and NS_LOG_FUNCTION.
Referenced by DoInitialize().
GetIndex()
uint16_t ns3::MinstrelHtWifiManager::GetIndex (uint8_t groupId, uint8_t rateId) private
Returns the global index corresponding to the groupId and rateId.
Parameters
groupId the group ID
rateId the rate ID
Returns
the index
Definition at line 1721 of file minstrel-ht-wifi-manager.cc.
References m_numRates, and NS_LOG_FUNCTION.
Referenced by GetLowestIndex(), GetNextSample(), StatsDump(), and UpdateStats().
GetLowestIndex() [1/2]
uint16_t ns3::MinstrelHtWifiManager::GetLowestIndex (MinstrelHtWifiRemoteStation * station) private
Returns the lowest global index of the rates supported by the station.
Parameters
station the minstrel HT wifi remote station
Returns
the lowest global index
Definition at line 1760 of file minstrel-ht-wifi-manager.cc.
References GetIndex(), ns3::MinstrelHtWifiRemoteStation::m_groupsTable, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by UpdateStats().
GetLowestIndex() [2/2]
uint16_t ns3::MinstrelHtWifiManager::GetLowestIndex (MinstrelHtWifiRemoteStation * station, uint8_t groupId) private
Returns the lowest global index of the rates supported by in the group.
Parameters
station the minstrel HT wifi remote station
groupId the group ID
Returns
the lowest global index
Definition at line 1779 of file minstrel-ht-wifi-manager.cc.
References GetIndex(), ns3::MinstrelHtWifiRemoteStation::m_groupsTable, NS_ASSERT, and NS_LOG_FUNCTION.
GetMpduTxTime()
Time ns3::MinstrelHtWifiManager::GetMpduTxTime (uint8_t groupId, WifiMode mode) const private
Obtain the TxTime saved in the group information.
Parameters
groupId the group ID
mode the wifi mode
Returns
the transmit time
Definition at line 348 of file minstrel-ht-wifi-manager.cc.
References m_minstrelGroups, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by CalculateRetransmits().
GetNextSample()
uint16_t ns3::MinstrelHtWifiManager::GetNextSample (MinstrelHtWifiRemoteStation * station) private
Getting the next sample from Sample Table.
Parameters
station the wifi remote station
Returns
the next sample
Definition at line 1008 of file minstrel-ht-wifi-manager.cc.
References GetIndex(), ns3::MinstrelHtWifiRemoteStation::m_groupsTable, ns3::MinstrelHtWifiRemoteStation::m_sampleGroup, ns3::MinstrelWifiRemoteStation::m_sampleTable, NS_LOG_DEBUG, NS_LOG_FUNCTION, and SetNextSample().
Referenced by FindRate().
GetRateId()
uint8_t ns3::MinstrelHtWifiManager::GetRateId (uint16_t index) private
For managing rates from different groups, a global index for all rates in all groups is used.
The group order is fixed by BW -> SGI -> streams. Following functions convert from groupId and rateId to global index and vice versa.
Parameters
index the index
Returns
the rate ID Return the rateId inside a group, from the global index.
Parameters
index the index
Returns
the rate ID
Definition at line 1730 of file minstrel-ht-wifi-manager.cc.
References m_numRates, and NS_LOG_FUNCTION.
Referenced by CalculateRetransmits(), CountRetries(), DoGetDataTxVector(), DoGetRtsTxVector(), DoReportAmpduTxStatus(), DoReportDataFailed(), DoReportDataOk(), FindRate(), SetBestProbabilityRate(), SetBestStationThRates(), and UpdateRate().
GetTypeId()
TypeId ns3::MinstrelHtWifiManager::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 76 of file minstrel-ht-wifi-manager.cc.
References m_currentRate, m_ewmaLevel, m_frameLength, m_legacyUpdateStats, m_lookAroundRate, m_nSampleCol, m_printStats, m_updateStats, m_useVhtOnly, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), ns3::MilliSeconds(), and ns3::TypeId::SetParent().
GetVhtDeviceMcsList()
WifiModeList ns3::MinstrelHtWifiManager::GetVhtDeviceMcsList (void) const private
Returns a list of only the VHT MCS supported by the device.
Returns
the list of the VHT MCS supported
Definition at line 1793 of file minstrel-ht-wifi-manager.cc.
References ns3::WifiMode::GetModulationClass(), ns3::WifiRemoteStationManager::GetPhy(), third::phy, and ns3::WIFI_MOD_CLASS_VHT.
Referenced by DoInitialize().
GetVhtGroupId()
uint8_t ns3::MinstrelHtWifiManager::GetVhtGroupId (uint8_t txstreams, uint8_t sgi, uint16_t chWidth) private
Returns the groupId of a VHT MCS with the given number of streams, if using SGI and the channel width used.
Parameters
txstreams the number of streams
sgi short guard interval enabled (0 or 1)
chWidth the channel width (MHz)
Returns
the VHT group ID
Definition at line 1753 of file minstrel-ht-wifi-manager.cc.
References ns3::MAX_HT_STREAM_GROUPS, ns3::MAX_SUPPORTED_STREAMS, and NS_LOG_FUNCTION.
Referenced by DoInitialize().
InitSampleTable()
void ns3::MinstrelHtWifiManager::InitSampleTable (MinstrelHtWifiRemoteStation * station) private
Initialize Sample Table.
Parameters
station the minstrel HT wifi remote station
The next two lines basically tries to generate a random number between 0 and the number of available rates
Definition at line 1580 of file minstrel-ht-wifi-manager.cc.
References ns3::UniformRandomVariable::GetInteger(), ns3::MinstrelWifiRemoteStation::m_col, ns3::MinstrelWifiRemoteStation::m_index, m_nSampleCol, m_numRates, ns3::MinstrelWifiRemoteStation::m_sampleTable, m_uniformRandomVariable, and NS_LOG_FUNCTION.
Referenced by CheckInit().
IsValidMcs()
bool ns3::MinstrelHtWifiManager::IsValidMcs (Ptr< WifiPhy > phy, uint8_t streams, uint16_t chWidth, WifiMode mode) private
Check the validity of a combination of number of streams, chWidth and mode.
Parameters
phy pointer to the wifi PHY
streams the number of streams
chWidth the channel width (MHz)
mode the wifi mode
Returns
true if the combination is valid
Definition at line 304 of file minstrel-ht-wifi-manager.cc.
References ns3::WifiTxVector::IsValid(), NS_LOG_FUNCTION, third::phy, ns3::WifiTxVector::SetChannelWidth(), ns3::WifiTxVector::SetMode(), and ns3::WifiTxVector::SetNss().
Referenced by DoInitialize(), and RateInit().
PrintSampleTable()
void ns3::MinstrelHtWifiManager::PrintSampleTable (MinstrelHtWifiRemoteStation * station) private
Printing Sample Table.
Parameters
station the minstrel HT wifi remote station
PrintTable()
void ns3::MinstrelHtWifiManager::PrintTable (MinstrelHtWifiRemoteStation * station) private
Printing Minstrel Table.
Parameters
station the minstrel HT wifi remote station
Definition at line 1611 of file minstrel-ht-wifi-manager.cc.
References ns3::WifiRemoteStationState::m_address, ns3::MinstrelHtWifiRemoteStation::m_avgAmpduLen, m_numGroups, ns3::MinstrelWifiRemoteStation::m_samplePacketsCount, ns3::WifiRemoteStation::m_state, ns3::MinstrelHtWifiRemoteStation::m_statsFile, ns3::MinstrelWifiRemoteStation::m_totalPacketsCount, ns3::Max(), and StatsDump().
Referenced by UpdateStats().
RateInit()
void ns3::MinstrelHtWifiManager::RateInit (MinstrelHtWifiRemoteStation * station) private
Initialize Minstrel Table.
Parameters
station the minstrel HT wifi remote station
Initialize groups supported by the receiver.
Is VHT supported by the receiver?
If it is an HT MCS, check if VHT only is disabled
Is SGI supported by the receiver?
Is channel width supported by the receiver?
Are streams supported by the receiver?
Group supported.
Create the rate list for the group.
Use the McsValue as the index in the rate table. This way, MCSs not supported are not initialized.
If it is a VHT MCS only add to a VHT group.
Check validity of the VHT MCS
If it is a HT MCS only add to a HT group.
Check if the HT MCS corresponds to groups number of streams.
Mapping between rateId and operationalMcsSet
Select the initial sample index.
Calculate the initial high throughput rates.
Select the rate to use.
Definition at line 1424 of file minstrel-ht-wifi-manager.cc.
References CalculateRetransmits(), FindRate(), ns3::WifiRemoteStationManager::GetChannelWidth(), GetFirstMpduTxTime(), ns3::WifiRemoteStationManager::GetMcsSupported(), ns3::WifiMode::GetMcsValue(), ns3::WifiMode::GetModulationClass(), ns3::WifiRemoteStationManager::GetNumberOfSupportedStreams(), ns3::WifiRemoteStationManager::GetPhy(), ns3::WifiRemoteStationManager::GetShortGuardIntervalSupported(), ns3::WifiRemoteStationManager::GetVhtSupported(), IsValidMcs(), ns3::MinstrelHtWifiRemoteStation::m_groupsTable, m_minstrelGroups, ns3::MinstrelWifiRemoteStation::m_nModes, m_numGroups, m_numRates, ns3::MinstrelWifiRemoteStation::m_txrate, m_useVhtOnly, ns3::MAX_HT_GROUP_RATES, NS_LOG_DEBUG, NS_LOG_FUNCTION, SetNextSample(), UpdateStats(), ns3::WIFI_MOD_CLASS_HT, and ns3::WIFI_MOD_CLASS_VHT.
Referenced by CheckInit().
SetBestProbabilityRate()
void ns3::MinstrelHtWifiManager::SetBestProbabilityRate (MinstrelHtWifiRemoteStation * station, uint16_t index) private
Set index rate as maxProbRate if it is better than current value.
Parameters
station the minstrel HT wifi remote station
index the index
Definition at line 1304 of file minstrel-ht-wifi-manager.cc.
References ns3::HtRateInfo::ewmaProb, GetGroupId(), GetRateId(), ns3::MinstrelHtWifiRemoteStation::m_groupsTable, ns3::GroupInfo::m_maxProbRate, ns3::MinstrelWifiRemoteStation::m_maxProbRate, and ns3::GroupInfo::m_ratesTable.
Referenced by UpdateStats().
SetBestStationThRates()
void ns3::MinstrelHtWifiManager::SetBestStationThRates (MinstrelHtWifiRemoteStation * station, uint16_t index) private
Set index rate as maxTpRate or maxTp2Rate if is better than current values.
Parameters
station the minstrel HT wifi remote station
index the index
Definition at line 1365 of file minstrel-ht-wifi-manager.cc.
References GetGroupId(), GetRateId(), ns3::MinstrelHtWifiRemoteStation::m_groupsTable, ns3::GroupInfo::m_maxTpRate, ns3::MinstrelWifiRemoteStation::m_maxTpRate, ns3::GroupInfo::m_maxTpRate2, ns3::MinstrelWifiRemoteStation::m_maxTpRate2, and ns3::GroupInfo::m_ratesTable.
Referenced by UpdateStats().
SetNextSample()
void ns3::MinstrelHtWifiManager::SetNextSample (MinstrelHtWifiRemoteStation * station) private
Set the next sample from Sample Table.
Parameters
station the wifi remote station
Definition at line 1022 of file minstrel-ht-wifi-manager.cc.
References ns3::MinstrelHtWifiRemoteStation::m_groupsTable, m_nSampleCol, m_numGroups, m_numRates, ns3::MinstrelHtWifiRemoteStation::m_sampleGroup, ns3::MinstrelWifiRemoteStation::m_sampleTable, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by GetNextSample(), and RateInit().
SetupMac()
void ns3::MinstrelHtWifiManager::SetupMac (const Ptr< WifiMac > mac) virtual
Set up MAC associated with this device since it is the object that knows the full set of timing parameters (e.g.
IFS).
Parameters
mac the MAC of this device
Reimplemented from ns3::WifiRemoteStationManager.
Definition at line 175 of file minstrel-ht-wifi-manager.cc.
References m_legacyManager, third::mac, NS_LOG_FUNCTION, and ns3::WifiRemoteStationManager::SetupMac().
SetupPhy()
void ns3::MinstrelHtWifiManager::SetupPhy (const Ptr< WifiPhy > phy) virtual
Set up PHY associated with this device since it is the object that knows the full set of transmit rates that are supported.
Parameters
phy the PHY of this device
Reimplemented from ns3::WifiRemoteStationManager.
Definition at line 166 of file minstrel-ht-wifi-manager.cc.
References m_legacyManager, NS_LOG_FUNCTION, third::phy, and ns3::WifiRemoteStationManager::SetupPhy().
StatsDump()
void ns3::MinstrelHtWifiManager::StatsDump (MinstrelHtWifiRemoteStation * station, uint8_t groupId, std::ofstream & of) private
Print group statistics.
Parameters
station the minstrel HT wifi remote station
groupId the group ID
of the output file stream
Definition at line 1635 of file minstrel-ht-wifi-manager.cc.
References CalculateThroughput(), ns3::McsGroup::chWidth, GetFirstMpduTxTime(), GetIndex(), ns3::WifiRemoteStationManager::GetMcsSupported(), ns3::Time::GetMicroSeconds(), ns3::McsGroup::isVht, ns3::MinstrelHtWifiRemoteStation::m_groupsTable, ns3::MinstrelWifiRemoteStation::m_maxProbRate, ns3::MinstrelWifiRemoteStation::m_maxTpRate, ns3::MinstrelWifiRemoteStation::m_maxTpRate2, m_minstrelGroups, m_numRates, ns3::McsGroup::sgi, and ns3::McsGroup::streams.
Referenced by PrintTable().
UpdatePacketCounters()
void ns3::MinstrelHtWifiManager::UpdatePacketCounters (MinstrelHtWifiRemoteStation * station, uint8_t nSuccessfulMpdus, uint8_t nFailedMpdus) private
Update the number of sample count variables.
Parameters
station the wifi remote station
nSuccessfulMpdus the number of successfully received MPDUs
nFailedMpdus the number of failed MPDUs
Definition at line 796 of file minstrel-ht-wifi-manager.cc.
References ns3::MinstrelHtWifiRemoteStation::m_avgAmpduLen, ns3::MinstrelWifiRemoteStation::m_isSampling, ns3::MinstrelHtWifiRemoteStation::m_sampleCount, ns3::MinstrelWifiRemoteStation::m_samplePacketsCount, ns3::MinstrelHtWifiRemoteStation::m_sampleTries, ns3::MinstrelHtWifiRemoteStation::m_sampleWait, ns3::MinstrelWifiRemoteStation::m_totalPacketsCount, and NS_LOG_FUNCTION.
Referenced by DoReportAmpduTxStatus(), DoReportDataOk(), and DoReportFinalDataFailed().
UpdateRate()
void ns3::MinstrelHtWifiManager::UpdateRate (MinstrelHtWifiRemoteStation * station) private
Update rate.
Parameters
station the minstrel HT wifi remote station
Retry Chain table is implemented here.
FIXME Currently, NS3 does not retransmit an entire A-MPDU when BACK is missing but retransmits each MPDU until MPDUs lifetime expires (or a BACK is received). Then, there is no way to control A-MPDU retries (no call to NeedDataRetransmission). So, it is possible that the A-MPDU keeps retrying after longRetry reaches its limit.
Try | LOOKAROUND RATE | NORMAL RATE
1 | Random rate | Best throughput 2 | Next best throughput | Next best throughput 3 | Best probability | Best probability
Note: For clarity, multiple blocks of if's and else's are used Following implementation in Linux, in MinstrelHT lowest base rate is not used. Explanation can be found here: http://marc.info/?l=linux-wireless&m=144602778611966&w=2
Get the IDs for all rates.
For normal rate, we're not currently sampling random rates.
Use best throughput rate.
< There are still a few retries.
Use second best throughput rate.
Use best probability rate.
We're currently sampling random rates.
Sample rate is used only once Use the best rate.
Use the best probability rate.
Definition at line 687 of file minstrel-ht-wifi-manager.cc.
References CheckInit(), GetGroupId(), GetRateId(), ns3::MinstrelHtWifiRemoteStation::m_groupsTable, ns3::MinstrelWifiRemoteStation::m_initialized, ns3::MinstrelWifiRemoteStation::m_isSampling, ns3::MinstrelWifiRemoteStation::m_longRetry, ns3::MinstrelWifiRemoteStation::m_maxProbRate, ns3::MinstrelWifiRemoteStation::m_maxTpRate, ns3::MinstrelWifiRemoteStation::m_maxTpRate2, ns3::MinstrelWifiRemoteStation::m_txrate, NS_FATAL_ERROR, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by DoReportAmpduTxStatus(), and DoReportDataFailed().
UpdateRetry()
void ns3::MinstrelHtWifiManager::UpdateRetry (MinstrelHtWifiRemoteStation * station) private
Update the number of retries and reset accordingly.
Parameters
station the wifi remote station
Definition at line 788 of file minstrel-ht-wifi-manager.cc.
References ns3::MinstrelWifiRemoteStation::m_longRetry, ns3::MinstrelWifiRemoteStation::m_shortRetry, and NS_LOG_FUNCTION.
Referenced by DoReportAmpduTxStatus(), DoReportDataOk(), DoReportFinalDataFailed(), and DoReportFinalRtsFailed().
UpdateStats()
void ns3::MinstrelHtWifiManager::UpdateStats (MinstrelHtWifiRemoteStation * station) private
Update the Minstrel Table.
Parameters
station the minstrel HT wifi remote station
Update throughput and EWMA for each rate inside each group.
If we've attempted something.
Calculate the probability of success. Assume probability scales from 0 to 100.
Bookkeeping.
EWMA probability
Bookkeeping.
Definition at line 1158 of file minstrel-ht-wifi-manager.cc.
References CalculateEwmsd(), CalculateRetransmits(), CalculateThroughput(), GetIndex(), GetLowestIndex(), ns3::WifiRemoteStationManager::GetMcsSupported(), ns3::MinstrelHtWifiRemoteStation::m_ampduLen, ns3::MinstrelHtWifiRemoteStation::m_ampduPacketCount, ns3::MinstrelHtWifiRemoteStation::m_avgAmpduLen, m_ewmaLevel, ns3::MinstrelHtWifiRemoteStation::m_groupsTable, ns3::MinstrelWifiRemoteStation::m_maxProbRate, ns3::MinstrelWifiRemoteStation::m_maxTpRate, ns3::MinstrelWifiRemoteStation::m_maxTpRate2, ns3::MinstrelWifiRemoteStation::m_nextStatsUpdate, m_numGroups, m_numRates, ns3::MinstrelHtWifiRemoteStation::m_numSamplesSlow, m_printStats, ns3::MinstrelHtWifiRemoteStation::m_sampleCount, m_updateStats, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, PrintTable(), SetBestProbabilityRate(), and SetBestStationThRates().
Referenced by DoReportAmpduTxStatus(), DoReportDataOk(), DoReportFinalDataFailed(), and RateInit().
Member Data Documentation
m_currentRate
TracedValue<uint64_t> ns3::MinstrelHtWifiManager::m_currentRate private
Trace rate changes.
Definition at line 587 of file minstrel-ht-wifi-manager.h.
Referenced by DoGetDataTxVector(), and GetTypeId().
m_ewmaLevel
uint8_t ns3::MinstrelHtWifiManager::m_ewmaLevel private
Exponential weighted moving average level (or coefficient).
Definition at line 573 of file minstrel-ht-wifi-manager.h.
Referenced by CheckInit(), GetTypeId(), and UpdateStats().
m_frameLength
uint32_t ns3::MinstrelHtWifiManager::m_frameLength private
Frame length used for calculate modes TxTime in bytes.
Definition at line 575 of file minstrel-ht-wifi-manager.h.
Referenced by CalculateMpduTxDuration(), CheckInit(), and GetTypeId().
m_legacyManager
Ptr<MinstrelWifiManager> ns3::MinstrelHtWifiManager::m_legacyManager private
Pointer to an instance of MinstrelWifiManager.
Used when 802.11n/ac not supported.
Definition at line 583 of file minstrel-ht-wifi-manager.h.
Referenced by MinstrelHtWifiManager(), AssignStreams(), CheckInit(), DoGetDataTxVector(), DoGetRtsTxVector(), DoNeedRetransmission(), DoReportDataFailed(), DoReportDataOk(), DoReportFinalDataFailed(), SetupMac(), and SetupPhy().
m_legacyUpdateStats
Time ns3::MinstrelHtWifiManager::m_legacyUpdateStats private
How frequent do we calculate the stats for legacy MinstrelWifiManager.
Definition at line 571 of file minstrel-ht-wifi-manager.h.
Referenced by CheckInit(), and GetTypeId().
m_lookAroundRate
uint8_t ns3::MinstrelHtWifiManager::m_lookAroundRate private
The % to try other rates than our current rate.
Definition at line 572 of file minstrel-ht-wifi-manager.h.
Referenced by CheckInit(), and GetTypeId().
m_minstrelGroups
MinstrelMcsGroups ns3::MinstrelHtWifiManager::m_minstrelGroups private
Global array for groups information.
Definition at line 581 of file minstrel-ht-wifi-manager.h.
Referenced by ~MinstrelHtWifiManager(), AddFirstMpduTxTime(), AddMpduTxTime(), DoGetDataTxVector(), DoInitialize(), FindRate(), GetFirstMpduTxTime(), GetMpduTxTime(), RateInit(), and StatsDump().
m_nSampleCol
uint8_t ns3::MinstrelHtWifiManager::m_nSampleCol private
Number of sample columns.
Definition at line 574 of file minstrel-ht-wifi-manager.h.
Referenced by CheckInit(), GetTypeId(), InitSampleTable(), and SetNextSample().
m_numGroups
uint8_t ns3::MinstrelHtWifiManager::m_numGroups private
Number of groups Minstrel should consider.
Definition at line 576 of file minstrel-ht-wifi-manager.h.
Referenced by ~MinstrelHtWifiManager(), DoInitialize(), PrintTable(), RateInit(), SetNextSample(), and UpdateStats().
m_numRates
uint8_t ns3::MinstrelHtWifiManager::m_numRates private
Number of rates per group Minstrel should consider.
Definition at line 577 of file minstrel-ht-wifi-manager.h.
Referenced by CheckInit(), DoInitialize(), GetGroupId(), GetIndex(), GetRateId(), InitSampleTable(), RateInit(), SetNextSample(), StatsDump(), and UpdateStats().
m_printStats
bool ns3::MinstrelHtWifiManager::m_printStats private
If statistics table should be printed.
Definition at line 579 of file minstrel-ht-wifi-manager.h.
Referenced by CheckInit(), GetTypeId(), and UpdateStats().
m_uniformRandomVariable
Ptr<UniformRandomVariable> ns3::MinstrelHtWifiManager::m_uniformRandomVariable private
Provides uniform random variables.
Definition at line 585 of file minstrel-ht-wifi-manager.h.
Referenced by MinstrelHtWifiManager(), AssignStreams(), and InitSampleTable().
m_updateStats
Time ns3::MinstrelHtWifiManager::m_updateStats private
How frequent do we calculate the stats.
Definition at line 570 of file minstrel-ht-wifi-manager.h.
Referenced by DoCreateStation(), GetTypeId(), and UpdateStats().
m_useVhtOnly
bool ns3::MinstrelHtWifiManager::m_useVhtOnly private
If only VHT MCS should be used, instead of HT and VHT.
Definition at line 578 of file minstrel-ht-wifi-manager.h.
Referenced by GetTypeId(), and RateInit().
The documentation for this class was generated from the following files:
src/wifi/model/minstrel-ht-wifi-manager.h
src/wifi/model/minstrel-ht-wifi-manager.cc