ns-3: ns3::LteInterference Class Reference
ns3::LteInterference Class Reference
This class implements a gaussian interference model, i.e., all incoming signals are added to the total interference.
#include "lte-interference.h"
Public Member Functions
LteInterference ()
virtual ~LteInterference ()
virtual void AddInterferenceChunkProcessor (Ptr< LteChunkProcessor > p)
Add a LteChunkProcessor that will use the time-vs-frequency interference calculated by this LteInterference instance.
virtual void AddRsPowerChunkProcessor (Ptr< LteChunkProcessor > p)
Add a LteChunkProcessor that will use the time-vs-frequency power calculated by this LteInterference instance.
virtual void AddSignal (Ptr< const SpectrumValue > spd, const Time duration)
notify that a new signal is being perceived in the medium.
virtual void AddSinrChunkProcessor (Ptr< LteChunkProcessor > p)
Add a LteChunkProcessor that will use the time-vs-frequency SINR calculated by this LteInterference instance.
virtual void DoDispose ()
Destructor implementation.
virtual void EndRx ()
notify that the RX attempt has ended.
virtual void SetNoisePowerSpectralDensity (Ptr< const SpectrumValue > noisePsd)
virtual void StartRx (Ptr< const SpectrumValue > rxPsd)
Notify that the PHY is starting a RX attempt.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void ConditionallyEvaluateChunk ()
Conditionally evaluate chunk.
virtual void DoAddSignal (Ptr< const SpectrumValue > spd)
Add signal function.
virtual void DoSubtractSignal (Ptr< const SpectrumValue > spd, uint32_t signalId)
Subtract signal.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes
Ptr< SpectrumValue > m_allSignals {nullptr}
stores the spectral power density of the sum of incoming signals; does not include noise, includes the SPD of the signal being RX
std::list< Ptr< LteChunkProcessor > > m_interfChunkProcessorList
all the processor instances that need to be notified whenever a new interference chunk is calculated
Time m_lastChangeTime {Seconds(0)}
the time of the last change in m_TotalPower
uint32_t m_lastSignalId {0}
the last signal ID
uint32_t m_lastSignalIdBeforeReset {0}
the last signal ID before reset
Ptr< const SpectrumValue > m_noise {nullptr}
the noise value
bool m_receiving {false}
are we receiving?
std::list< Ptr< LteChunkProcessor > > m_rsPowerChunkProcessorList
all the processor instances that need to be notified whenever a new interference chunk is calculated
Ptr< SpectrumValue > m_rxSignal {nullptr}
stores the power spectral density of the signal whose RX is being attempted
std::list< Ptr< LteChunkProcessor > > m_sinrChunkProcessorList
all the processor instances that need to be notified whenever a new SINR chunk is calculated
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class implements a gaussian interference model, i.e., all incoming signals are added to the total interference.
Definition at line 42 of file lte-interference.h.
Constructor & Destructor Documentation
LteInterference()
ns3::LteInterference::LteInterference ()
Definition at line 33 of file lte-interference.cc.
References NS_LOG_FUNCTION.
~LteInterference()
ns3::LteInterference::~LteInterference () virtual
Definition at line 41 of file lte-interference.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddInterferenceChunkProcessor()
void ns3::LteInterference::AddInterferenceChunkProcessor (Ptr< LteChunkProcessor > p) virtual
Add a LteChunkProcessor that will use the time-vs-frequency interference calculated by this LteInterference instance.
Note that all the added LteChunkProcessors will work in parallel.
Parameters
p
Definition at line 245 of file lte-interference.cc.
References m_interfChunkProcessorList, and NS_LOG_FUNCTION.
AddRsPowerChunkProcessor()
void ns3::LteInterference::AddRsPowerChunkProcessor (Ptr< LteChunkProcessor > p) virtual
Add a LteChunkProcessor that will use the time-vs-frequency power calculated by this LteInterference instance.
Note that all the added LteChunkProcessors will work in parallel.
Parameters
p
Definition at line 231 of file lte-interference.cc.
References m_rsPowerChunkProcessorList, and NS_LOG_FUNCTION.
AddSignal()
void ns3::LteInterference::AddSignal (Ptr< const SpectrumValue > spd, const Time duration) virtual
notify that a new signal is being perceived in the medium.
This method is to be called for all incoming signal, regardless of whether they're useful signals or interferers.
Parameters
spd the power spectral density of the new signal
duration the duration of the new signal
Definition at line 135 of file lte-interference.cc.
References DoAddSignal(), DoSubtractSignal(), m_lastSignalId, m_lastSignalIdBeforeReset, NS_LOG_FUNCTION, and ns3::Simulator::Schedule().
AddSinrChunkProcessor()
void ns3::LteInterference::AddSinrChunkProcessor (Ptr< LteChunkProcessor > p) virtual
Add a LteChunkProcessor that will use the time-vs-frequency SINR calculated by this LteInterference instance.
Note that all the added LteChunkProcessors will work in parallel.
Parameters
p
Definition at line 238 of file lte-interference.cc.
References m_sinrChunkProcessorList, and NS_LOG_FUNCTION.
ConditionallyEvaluateChunk()
void ns3::LteInterference::ConditionallyEvaluateChunk () protected virtual
Conditionally evaluate chunk.
Definition at line 179 of file lte-interference.cc.
References list, m_allSignals, m_interfChunkProcessorList, m_lastChangeTime, m_noise, m_receiving, m_rsPowerChunkProcessorList, m_rxSignal, m_sinrChunkProcessorList, ns3::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by DoAddSignal(), DoSubtractSignal(), EndRx(), and SetNoisePowerSpectralDensity().
DoAddSignal()
void ns3::LteInterference::DoAddSignal (Ptr< const SpectrumValue > spd) protected virtual
Add signal function.
Parameters
spd the power spectral density of the new signal
Definition at line 154 of file lte-interference.cc.
References ConditionallyEvaluateChunk(), and NS_LOG_FUNCTION.
Referenced by AddSignal().
DoDispose()
void ns3::LteInterference::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 47 of file lte-interference.cc.
References ns3::Object::DoDispose(), m_allSignals, m_interfChunkProcessorList, m_noise, m_rsPowerChunkProcessorList, m_rxSignal, m_sinrChunkProcessorList, and NS_LOG_FUNCTION.
DoSubtractSignal()
void ns3::LteInterference::DoSubtractSignal (Ptr< const SpectrumValue > spd, uint32_t signalId) protected virtual
Subtract signal.
Parameters
spd the power spectral density of the new signal
signalId the signal ID
Definition at line 162 of file lte-interference.cc.
References ConditionallyEvaluateChunk(), m_lastSignalIdBeforeReset, NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by AddSignal().
EndRx()
void ns3::LteInterference::EndRx () virtual
notify that the RX attempt has ended.
The receiving PHY must call this method when RX ends or RX is aborted.
Definition at line 107 of file lte-interference.cc.
References ConditionallyEvaluateChunk(), list, m_interfChunkProcessorList, m_receiving, m_rsPowerChunkProcessorList, m_sinrChunkProcessorList, NS_LOG_FUNCTION, and NS_LOG_INFO.
GetTypeId()
TypeId ns3::LteInterference::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 61 of file lte-interference.cc.
References ns3::TypeId::SetParent().
SetNoisePowerSpectralDensity()
void ns3::LteInterference::SetNoisePowerSpectralDensity (Ptr< const SpectrumValue > noisePsd) virtual
Parameters
noisePsd the Noise Power Spectral Density in power units (Watt, Pascal...) per Hz.
Definition at line 212 of file lte-interference.cc.
References ConditionallyEvaluateChunk(), m_allSignals, m_lastSignalId, m_lastSignalIdBeforeReset, m_noise, m_receiving, and NS_LOG_FUNCTION.
StartRx()
void ns3::LteInterference::StartRx (Ptr< const SpectrumValue > rxPsd) virtual
Notify that the PHY is starting a RX attempt.
Parameters
rxPsd the power spectral density of the signal being RX
Definition at line 72 of file lte-interference.cc.
References list, m_interfChunkProcessorList, m_lastChangeTime, m_receiving, m_rsPowerChunkProcessorList, m_rxSignal, m_sinrChunkProcessorList, ns3::Now(), NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, and ns3::Sum().
Member Data Documentation
m_allSignals
Ptr<SpectrumValue> ns3::LteInterference::m_allSignals {nullptr} protected
stores the spectral power density of the sum of incoming signals; does not include noise, includes the SPD of the signal being RX
Definition at line 139 of file lte-interference.h.
Referenced by ConditionallyEvaluateChunk(), DoDispose(), and SetNoisePowerSpectralDensity().
m_interfChunkProcessorList
std::list<Ptr<LteChunkProcessor> > ns3::LteInterference::m_interfChunkProcessorList protected
all the processor instances that need to be notified whenever a new interference chunk is calculated
Definition at line 163 of file lte-interference.h.
Referenced by AddInterferenceChunkProcessor(), ConditionallyEvaluateChunk(), DoDispose(), EndRx(), and StartRx().
m_lastChangeTime
Time ns3::LteInterference::m_lastChangeTime {Seconds(0)} protected
the time of the last change in m_TotalPower
Definition at line 146 of file lte-interference.h.
Referenced by ConditionallyEvaluateChunk(), and StartRx().
m_lastSignalId
uint32_t ns3::LteInterference::m_lastSignalId {0} protected
the last signal ID
Definition at line 150 of file lte-interference.h.
Referenced by AddSignal(), and SetNoisePowerSpectralDensity().
m_lastSignalIdBeforeReset
uint32_t ns3::LteInterference::m_lastSignalIdBeforeReset {0} protected
the last signal ID before reset
Definition at line 151 of file lte-interference.h.
Referenced by AddSignal(), DoSubtractSignal(), and SetNoisePowerSpectralDensity().
m_noise
Ptr<const SpectrumValue> ns3::LteInterference::m_noise {nullptr} protected
the noise value
Definition at line 144 of file lte-interference.h.
Referenced by ConditionallyEvaluateChunk(), DoDispose(), and SetNoisePowerSpectralDensity().
m_receiving
bool ns3::LteInterference::m_receiving {false} protected
are we receiving?
Definition at line 132 of file lte-interference.h.
Referenced by ConditionallyEvaluateChunk(), EndRx(), SetNoisePowerSpectralDensity(), and StartRx().
m_rsPowerChunkProcessorList
std::list<Ptr<LteChunkProcessor> > ns3::LteInterference::m_rsPowerChunkProcessorList protected
all the processor instances that need to be notified whenever a new interference chunk is calculated
Definition at line 155 of file lte-interference.h.
Referenced by AddRsPowerChunkProcessor(), ConditionallyEvaluateChunk(), DoDispose(), EndRx(), and StartRx().
m_rxSignal
Ptr<SpectrumValue> ns3::LteInterference::m_rxSignal {nullptr} protected
stores the power spectral density of the signal whose RX is being attempted
Definition at line 134 of file lte-interference.h.
Referenced by ConditionallyEvaluateChunk(), DoDispose(), and StartRx().
m_sinrChunkProcessorList
std::list<Ptr<LteChunkProcessor> > ns3::LteInterference::m_sinrChunkProcessorList protected
all the processor instances that need to be notified whenever a new SINR chunk is calculated
Definition at line 159 of file lte-interference.h.
Referenced by AddSinrChunkProcessor(), ConditionallyEvaluateChunk(), DoDispose(), EndRx(), and StartRx().
The documentation for this class was generated from the following files:
src/lte/model/lte-interference.h
src/lte/model/lte-interference.cc