ns-3: ns3::UanHeaderRcAck Class Reference
ns3::UanHeaderRcAck Class Reference
UAN Models
Header used for ACK packets by protocol UanMacRc.
#include "uan-header-rc.h"
Public Member Functions
UanHeaderRcAck ()
Default constructor.
virtual ~UanHeaderRcAck ()
Destructor.
void AddNackedFrame (uint8_t frame)
NACK a frame.
virtual uint32_t Deserialize (Buffer::Iterator start)
uint8_t GetFrameNo (void) const
Get the reservation frame number being ACKed.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
const std::set< uint8_t > & GetNackedFrames (void) const
Get the set of NACK'ed frames.
uint8_t GetNoNacks (void) const
Get the number of data frames being NACKed.
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetFrameNo (uint8_t frameNo)
Set the frame number of the reservation being acknowledged.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_frameNo
Next frame number.
std::set< uint8_t > m_nackedFrames
Marker for nacked frames.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Header used for ACK packets by protocol UanMacRc.
Introspection did not find any typical Config paths.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 40 bytes (on a 64-bit architecture).
Definition at line 458 of file uan-header-rc.h.
Constructor & Destructor Documentation
UanHeaderRcAck()
ns3::UanHeaderRcAck::UanHeaderRcAck ()
Default constructor.
Definition at line 555 of file uan-header-rc.cc.
~UanHeaderRcAck()
ns3::UanHeaderRcAck::~UanHeaderRcAck () virtual
Destructor.
Definition at line 560 of file uan-header-rc.cc.
References m_nackedFrames.
Member Function Documentation
AddNackedFrame()
void ns3::UanHeaderRcAck::AddNackedFrame (uint8_t frame)
NACK a frame.
Parameters
frame The data frame number being NACKed.
Definition at line 583 of file uan-header-rc.cc.
References m_nackedFrames.
Referenced by ns3::UanMacRcGw::EndCycle().
Deserialize()
uint32_t ns3::UanHeaderRcAck::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 625 of file uan-header-rc.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_frameNo, m_nackedFrames, ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetFrameNo()
uint8_t ns3::UanHeaderRcAck::GetFrameNo (void) const
Get the reservation frame number being ACKed.
Returns
The frame number.
Definition at line 595 of file uan-header-rc.cc.
References m_frameNo.
Referenced by ns3::UanMacRc::ProcessAck().
GetInstanceTypeId()
TypeId ns3::UanHeaderRcAck::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 655 of file uan-header-rc.cc.
References GetTypeId().
GetNackedFrames()
const std::set< uint8_t > & ns3::UanHeaderRcAck::GetNackedFrames (void) const
Get the set of NACK'ed frames.
Returns
The set of NACK'ed frames.
Definition at line 589 of file uan-header-rc.cc.
References m_nackedFrames.
Referenced by ns3::UanMacRc::ProcessAck().
GetNoNacks()
uint8_t ns3::UanHeaderRcAck::GetNoNacks (void) const
Get the number of data frames being NACKed.
Returns
The number of NACKed frames.
Definition at line 601 of file uan-header-rc.cc.
References m_nackedFrames.
Referenced by GetSerializedSize(), Print(), ns3::UanMacRc::ProcessAck(), and Serialize().
GetSerializedSize()
uint32_t ns3::UanHeaderRcAck::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 607 of file uan-header-rc.cc.
References GetNoNacks().
Referenced by ns3::UanMacRcGw::UanMacRcGw().
GetTypeId()
TypeId ns3::UanHeaderRcAck::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 566 of file uan-header-rc.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::UanHeaderRcAck::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 639 of file uan-header-rc.cc.
References GetNoNacks(), m_frameNo, and m_nackedFrames.
Serialize()
void ns3::UanHeaderRcAck::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 613 of file uan-header-rc.cc.
References GetNoNacks(), m_frameNo, m_nackedFrames, and visualizer.core::start().
SetFrameNo()
void ns3::UanHeaderRcAck::SetFrameNo (uint8_t frameNo)
Set the frame number of the reservation being acknowledged.
Parameters
frameNo The frame number.
Definition at line 577 of file uan-header-rc.cc.
References m_frameNo.
Referenced by ns3::UanMacRcGw::EndCycle().
Member Data Documentation
m_frameNo
uint8_t ns3::UanHeaderRcAck::m_frameNo private
Next frame number.
Definition at line 512 of file uan-header-rc.h.
Referenced by Deserialize(), GetFrameNo(), Print(), Serialize(), and SetFrameNo().
m_nackedFrames
std::set<uint8_t> ns3::UanHeaderRcAck::m_nackedFrames private
Marker for nacked frames.
Definition at line 513 of file uan-header-rc.h.
Referenced by ~UanHeaderRcAck(), AddNackedFrame(), Deserialize(), GetNackedFrames(), GetNoNacks(), Print(), and Serialize().
The documentation for this class was generated from the following files:
src/uan/model/uan-header-rc.h
src/uan/model/uan-header-rc.cc