ns-3: ns3::UanChannel Class Reference
ns3::UanChannel Class Reference
UAN Models
Channel class used by UAN devices.
#include "uan-channel.h"
Public Types
typedef std::vector< std::pair< Ptr< UanNetDevice >, Ptr< UanTransducer > > > UanDeviceList
UanDeviceList is a standard template vector of pairs (UanNetDevice, UanTransducer)
Public Member Functions
UanChannel ()
Constructor.
virtual ~UanChannel ()
Dummy destructor, see DoDispose.
void AddDevice (Ptr< UanNetDevice > dev, Ptr< UanTransducer > trans)
Adds device to receiver list for this channel.
void Clear (void)
Clear all pointer references.
virtual Ptr< NetDevice > GetDevice (std::size_t i) const
virtual std::size_t GetNDevices (void) const
double GetNoiseDbHz (double fKhz)
Get the noise level on the channel.
void SetNoiseModel (Ptr< UanNoiseModel > noise)
Set the noise model this channel will use to determine ambient channel noise.
void SetPropagationModel (Ptr< UanPropModel > prop)
Set the propagation model this channel will use for path loss/propagation delay.
virtual void TxPacket (Ptr< UanTransducer > src, Ptr< Packet > packet, double txPowerDb, UanTxMode txmode)
Send a packet out on the channel.
Public Member Functions inherited from ns3::Channel
Channel ()
virtual ~Channel ()
uint32_t GetId (void) const
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Channel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
void SendUp (uint32_t i, Ptr< Packet > packet, double rxPowerDb, UanTxMode txMode, UanPdp pdp)
Send a packet up to the receiving UanTransducer.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes
bool m_cleared
Has Clear ever been called on the channel.
UanDeviceList m_devList
The list of devices on this channel.
Ptr< UanNoiseModel > m_noise
The noise model.
Ptr< UanPropModel > m_prop
The propagation model.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Channel class used by UAN devices.
Config Paths
ns3::UanChannel is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::UanChannel"
"/NodeList/[i]/DeviceList/[i]/$ns3::UanNetDevice/Channel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::UanChannel"
"/ChannelList/[i]/$ns3::UanChannel"
Attributes
PropagationModel: A pointer to the propagation model.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::UanPropModel>
Initial value: ns3::UanPropModelIdeal
Flags: construct write read
NoiseModel: A pointer to the model of the channel ambient noise.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::UanNoiseModel>
Initial value: ns3::UanNoiseModelDefault
Flags: construct write read
Attributes defined in parent class ns3::Channel
Id: The id (unique integer) of this Channel.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Flags: read
No TraceSources are defined for this type.
Size of this type is 80 bytes (on a 64-bit architecture).
Definition at line 45 of file uan-channel.h.
Member Typedef Documentation
UanDeviceList
typedef std::vector<std::pair<Ptr<UanNetDevice>, Ptr<UanTransducer> > > ns3::UanChannel::UanDeviceList
UanDeviceList is a standard template vector of pairs (UanNetDevice, UanTransducer)
Definition at line 52 of file uan-channel.h.
Constructor & Destructor Documentation
UanChannel()
ns3::UanChannel::UanChannel ()
Constructor.
Definition at line 67 of file uan-channel.cc.
~UanChannel()
ns3::UanChannel::~UanChannel () virtual
Dummy destructor, see DoDispose.
Definition at line 74 of file uan-channel.cc.
Member Function Documentation
AddDevice()
void ns3::UanChannel::AddDevice (Ptr< UanNetDevice > dev, Ptr< UanTransducer > trans)
Adds device to receiver list for this channel.
Parameters
dev Net Device of node.
trans Transducer of net device attached to this channel.
Definition at line 140 of file uan-channel.cc.
References m_devList, and NS_LOG_DEBUG.
Clear()
void ns3::UanChannel::Clear (void)
Clear all pointer references.
Definition at line 79 of file uan-channel.cc.
References m_cleared, m_devList, m_noise, and m_prop.
Referenced by DoDispose().
DoDispose()
void ns3::UanChannel::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 115 of file uan-channel.cc.
References Clear(), and ns3::Object::DoDispose().
GetDevice()
Ptr< NetDevice > ns3::UanChannel::GetDevice (std::size_t i) const virtual
Parameters
i index of NetDevice to retrieve
Returns
one of the NetDevices connected to this channel.
This method must be implemented by subclasses.
Implements ns3::Channel.
Definition at line 134 of file uan-channel.cc.
References m_devList.
GetNDevices()
std::size_t ns3::UanChannel::GetNDevices (void) const virtual
Returns
the number of NetDevices connected to this Channel.
This method must be implemented by subclasses.
Implements ns3::Channel.
Definition at line 128 of file uan-channel.cc.
References m_devList.
GetNoiseDbHz()
double ns3::UanChannel::GetNoiseDbHz (double fKhz)
Get the noise level on the channel.
Parameters
fKhz Frequency in kHz.
Returns
Ambient noise in dB/Hz on channel at a frequency.
Definition at line 213 of file uan-channel.cc.
References m_noise, and NS_ASSERT.
GetTypeId()
TypeId ns3::UanChannel::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 46 of file uan-channel.cc.
References m_noise, m_prop, ns3::MakePointerAccessor(), and ns3::TypeId::SetParent().
SendUp()
void ns3::UanChannel::SendUp (uint32_t i, Ptr< Packet > packet, double rxPowerDb, UanTxMode txMode, UanPdp pdp) protected
Send a packet up to the receiving UanTransducer.
Parameters
i Device number.
packet The received packet.
rxPowerDb Signal power in dB of arriving packet.
txMode Mode arriving packet is using.
pdp PDP of arriving signal.
Definition at line 205 of file uan-channel.cc.
References m_devList, and NS_LOG_DEBUG.
Referenced by TxPacket().
SetNoiseModel()
void ns3::UanChannel::SetNoiseModel (Ptr< UanNoiseModel > noise)
Set the noise model this channel will use to determine ambient channel noise.
Parameters
noise The noise model.
Definition at line 199 of file uan-channel.cc.
References m_noise, and NS_ASSERT.
SetPropagationModel()
void ns3::UanChannel::SetPropagationModel (Ptr< UanPropModel > prop)
Set the propagation model this channel will use for path loss/propagation delay.
Parameters
prop The propagation model.
Definition at line 121 of file uan-channel.cc.
References m_prop, and NS_LOG_DEBUG.
TxPacket()
void ns3::UanChannel::TxPacket (Ptr< UanTransducer > src, Ptr< Packet > packet, double txPowerDb, UanTxMode txmode) virtual
Send a packet out on the channel.
Parameters
src Transducer transmitting packet.
packet Packet to be transmitted.
txPowerDb Transmission power in dB.
txmode UanTxMode defining modulation of transmitted packet.
Definition at line 147 of file uan-channel.cc.
References ns3::Packet::Copy(), ns3::MobilityModel::GetDistanceFrom(), ns3::Object::GetObject(), m_devList, m_prop, NS_ASSERT, NS_LOG_DEBUG, ns3::Simulator::ScheduleWithContext(), and SendUp().
Member Data Documentation
m_cleared
bool ns3::UanChannel::m_cleared protected
Has Clear ever been called on the channel.
Definition at line 119 of file uan-channel.h.
Referenced by Clear().
m_devList
UanDeviceList ns3::UanChannel::m_devList protected
The list of devices on this channel.
Definition at line 115 of file uan-channel.h.
Referenced by AddDevice(), Clear(), GetDevice(), GetNDevices(), SendUp(), and TxPacket().
m_noise
Ptr<UanNoiseModel> ns3::UanChannel::m_noise protected
The noise model.
Definition at line 117 of file uan-channel.h.
Referenced by Clear(), GetNoiseDbHz(), GetTypeId(), and SetNoiseModel().
m_prop
Ptr<UanPropModel> ns3::UanChannel::m_prop protected
The propagation model.
Definition at line 116 of file uan-channel.h.
Referenced by Clear(), GetTypeId(), SetPropagationModel(), and TxPacket().
The documentation for this class was generated from the following files:
src/uan/model/uan-channel.h
src/uan/model/uan-channel.cc