ns-3: ns3::MinMaxAvgTotalCalculator< T > Class Template Reference
ns3::MinMaxAvgTotalCalculator< T > Class Template Reference
Statistics
Template class MinMaxAvgTotalCalculator.
#include "basic-data-calculators.h"
Public Member Functions
MinMaxAvgTotalCalculator ()
virtual ~MinMaxAvgTotalCalculator ()
long getCount () const
Returns the count.
double getMax () const
Returns the maximum value.
double getMean () const
Returns the mean value.
double getMin () const
Returns the minimum value.
double getSqrSum () const
Returns the sum of squares.
double getStddev () const
Returns the standard deviation.
double getSum () const
Returns the sum.
double getVariance () const
Returns the current variance.
virtual void Output (DataOutputCallback &callback) const
Outputs the data based on the provided callback.
void Reset ()
Reinitializes all variables of MinMaxAvgTotalCalculator.
void Update (const T i)
Updates all variables of MinMaxAvgTotalCalculator.
Public Member Functions inherited from ns3::DataCalculator
DataCalculator ()
virtual ~DataCalculator ()
void Disable ()
Disables DataCalculator when simulation stops.
void Enable ()
Enables DataCalculator when simulation starts.
std::string GetContext () const
Gets the DataCalculator context.
bool GetEnabled () const
Returns whether the DataCalculator is enabled.
std::string GetKey () const
Gets the DataCalculator key.
void SetContext (const std::string context)
Sets the DataCalculator context to the provided context.
void SetKey (const std::string key)
Sets the DataCalculator key to the provided key.
virtual void Start (const Time &startTime)
Starts DataCalculator at a given time in the simulation.
virtual void Stop (const Time &stopTime)
Stops DataCalculator at a given time in the simulation.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Public Member Functions inherited from ns3::StatisticalSummary
virtual ~StatisticalSummary ()
Destructor.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::DataCalculator
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes
uint32_t m_count
Count value of MinMaxAvgTotalCalculator.
T m_max
Maximum value of MinMaxAvgTotalCalculator.
double m_meanCurr
Current mean of MinMaxAvgTotalCalculator.
double m_meanPrev
Previous mean of MinMaxAvgTotalCalculator.
T m_min
Minimum value of MinMaxAvgTotalCalculator.
double m_sCurr
Current s of MinMaxAvgTotalCalculator.
double m_sPrev
Previous s of MinMaxAvgTotalCalculator.
T m_squareTotal
Sum of squares value of MinMaxAvgTotalCalculator.
T m_total
Total value of MinMaxAvgTotalCalculator.
double m_varianceCurr
Current variance of MinMaxAvgTotalCalculator.
Protected Attributes inherited from ns3::DataCalculator
std::string m_context
Context value.
bool m_enabled
Descendant classes must check & respect m_enabled!
std::string m_key
Key value.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
template<typename T = uint32_t>
class ns3::MinMaxAvgTotalCalculator< T >
Template class MinMaxAvgTotalCalculator.
Definition at line 39 of file basic-data-calculators.h.
Constructor & Destructor Documentation
MinMaxAvgTotalCalculator()
template<typename T > ns3::MinMaxAvgTotalCalculator< T >::MinMaxAvgTotalCalculator
Definition at line 130 of file basic-data-calculators.h.
References ns3::NaN.
~MinMaxAvgTotalCalculator()
template<typename T > ns3::MinMaxAvgTotalCalculator< T >::~MinMaxAvgTotalCalculator virtual
Definition at line 146 of file basic-data-calculators.h.
Member Function Documentation
DoDispose()
template<typename T > void ns3::MinMaxAvgTotalCalculator< T >::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::DataCalculator.
Reimplemented in ns3::PacketSizeMinMaxAvgTotalCalculator.
Definition at line 152 of file basic-data-calculators.h.
References ns3::DataCalculator::DoDispose().
Referenced by ns3::PacketSizeMinMaxAvgTotalCalculator::DoDispose().
getCount()
template<typename T = uint32_t> long ns3::MinMaxAvgTotalCalculator< T >::getCount () const inline virtual
Returns the count.
Returns
Count
Implements ns3::StatisticalSummary.
Definition at line 71 of file basic-data-calculators.h.
References ns3::MinMaxAvgTotalCalculator< T >::m_count.
Referenced by OneIntegerTestCase::DoRun(), FiveIntegersTestCase::DoRun(), and FiveDoublesTestCase::DoRun().
getMax()
template<typename T = uint32_t> double ns3::MinMaxAvgTotalCalculator< T >::getMax () const inline virtual
Returns the maximum value.
Returns
Max
Implements ns3::StatisticalSummary.
Definition at line 86 of file basic-data-calculators.h.
References ns3::MinMaxAvgTotalCalculator< T >::m_max.
Referenced by ThreeGppHttpObjectTestCase::DoRun(), OneIntegerTestCase::DoRun(), FiveIntegersTestCase::DoRun(), and FiveDoublesTestCase::DoRun().
getMean()
template<typename T = uint32_t> double ns3::MinMaxAvgTotalCalculator< T >::getMean () const inline virtual
Returns the mean value.
Returns
Mean
Implements ns3::StatisticalSummary.
Definition at line 91 of file basic-data-calculators.h.
References ns3::MinMaxAvgTotalCalculator< T >::m_meanCurr.
Referenced by ns3::Average< T >::Avg(), ThreeGppHttpObjectTestCase::DoRun(), OneIntegerTestCase::DoRun(), FiveIntegersTestCase::DoRun(), and FiveDoublesTestCase::DoRun().
getMin()
template<typename T = uint32_t> double ns3::MinMaxAvgTotalCalculator< T >::getMin () const inline virtual
Returns the minimum value.
Returns
Min
Implements ns3::StatisticalSummary.
Definition at line 81 of file basic-data-calculators.h.
References ns3::MinMaxAvgTotalCalculator< T >::m_min.
Referenced by ThreeGppHttpObjectTestCase::DoRun(), OneIntegerTestCase::DoRun(), FiveIntegersTestCase::DoRun(), and FiveDoublesTestCase::DoRun().
getSqrSum()
template<typename T = uint32_t> double ns3::MinMaxAvgTotalCalculator< T >::getSqrSum () const inline virtual
Returns the sum of squares.
Returns
Sum of squares
Implements ns3::StatisticalSummary.
Definition at line 106 of file basic-data-calculators.h.
References ns3::MinMaxAvgTotalCalculator< T >::m_squareTotal.
Referenced by OneIntegerTestCase::DoRun(), FiveIntegersTestCase::DoRun(), and FiveDoublesTestCase::DoRun().
getStddev()
template<typename T = uint32_t> double ns3::MinMaxAvgTotalCalculator< T >::getStddev () const inline virtual
Returns the standard deviation.
Returns
Standard deviation
Implements ns3::StatisticalSummary.
Definition at line 96 of file basic-data-calculators.h.
References ns3::MinMaxAvgTotalCalculator< T >::m_varianceCurr.
Referenced by OneIntegerTestCase::DoRun(), FiveIntegersTestCase::DoRun(), and FiveDoublesTestCase::DoRun().
getSum()
template<typename T = uint32_t> double ns3::MinMaxAvgTotalCalculator< T >::getSum () const inline virtual
Returns the sum.
Returns
Total
Implements ns3::StatisticalSummary.
Definition at line 76 of file basic-data-calculators.h.
References ns3::MinMaxAvgTotalCalculator< T >::m_total.
Referenced by OneIntegerTestCase::DoRun(), FiveIntegersTestCase::DoRun(), and FiveDoublesTestCase::DoRun().
GetTypeId()
template<typename T > TypeId ns3::MinMaxAvgTotalCalculator< T >::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 161 of file basic-data-calculators.h.
References ns3::TypeId::SetParent().
getVariance()
template<typename T = uint32_t> double ns3::MinMaxAvgTotalCalculator< T >::getVariance () const inline virtual
Returns the current variance.
Returns
Variance
Implements ns3::StatisticalSummary.
Definition at line 101 of file basic-data-calculators.h.
References ns3::MinMaxAvgTotalCalculator< T >::m_varianceCurr.
Referenced by OneIntegerTestCase::DoRun(), FiveIntegersTestCase::DoRun(), FiveDoublesTestCase::DoRun(), and ns3::Average< T >::Var().
Output()
template<typename T > void ns3::MinMaxAvgTotalCalculator< T >::Output (DataOutputCallback & callback) const virtual
Outputs the data based on the provided callback.
Parameters
callback
Implements ns3::DataCalculator.
Definition at line 253 of file basic-data-calculators.h.
References ns3::DataOutputCallback::OutputStatistic().
Reset()
template<typename T > void ns3::MinMaxAvgTotalCalculator< T >::Reset (void)
Reinitializes all variables of MinMaxAvgTotalCalculator.
Definition at line 235 of file basic-data-calculators.h.
References ns3::NaN.
Referenced by ns3::Average< T >::Reset().
Update()
template<typename T > void ns3::MinMaxAvgTotalCalculator< T >::Update (const T i)
Updates all variables of MinMaxAvgTotalCalculator.
Parameters
i value of type T to use for updating the calculator
Definition at line 175 of file basic-data-calculators.h.
Referenced by ThreeGppHttpObjectTestCase::ClientRxDelayCallback(), ThreeGppHttpObjectTestCase::ClientRxRttCallback(), OneIntegerTestCase::DoRun(), FiveIntegersTestCase::DoRun(), FiveDoublesTestCase::DoRun(), ns3::PacketSizeMinMaxAvgTotalCalculator::FrameUpdate(), ns3::PacketSizeMinMaxAvgTotalCalculator::PacketUpdate(), and ns3::Average< T >::Update().
Member Data Documentation
m_count
template<typename T = uint32_t> uint32_t ns3::MinMaxAvgTotalCalculator< T >::m_count protected
Count value of MinMaxAvgTotalCalculator.
Definition at line 111 of file basic-data-calculators.h.
Referenced by ns3::MinMaxAvgTotalCalculator< T >::getCount().
m_max
template<typename T = uint32_t> T ns3::MinMaxAvgTotalCalculator< T >::m_max protected
Maximum value of MinMaxAvgTotalCalculator.
Definition at line 116 of file basic-data-calculators.h.
Referenced by ns3::MinMaxAvgTotalCalculator< T >::getMax().
m_meanCurr
template<typename T = uint32_t> double ns3::MinMaxAvgTotalCalculator< T >::m_meanCurr protected
Current mean of MinMaxAvgTotalCalculator.
Definition at line 118 of file basic-data-calculators.h.
Referenced by ns3::MinMaxAvgTotalCalculator< T >::getMean().
m_meanPrev
template<typename T = uint32_t> double ns3::MinMaxAvgTotalCalculator< T >::m_meanPrev protected
Previous mean of MinMaxAvgTotalCalculator.
Definition at line 122 of file basic-data-calculators.h.
m_min
template<typename T = uint32_t> T ns3::MinMaxAvgTotalCalculator< T >::m_min protected
Minimum value of MinMaxAvgTotalCalculator.
Definition at line 115 of file basic-data-calculators.h.
Referenced by ns3::MinMaxAvgTotalCalculator< T >::getMin().
m_sCurr
template<typename T = uint32_t> double ns3::MinMaxAvgTotalCalculator< T >::m_sCurr protected
Current s of MinMaxAvgTotalCalculator.
Definition at line 119 of file basic-data-calculators.h.
m_sPrev
template<typename T = uint32_t> double ns3::MinMaxAvgTotalCalculator< T >::m_sPrev protected
Previous s of MinMaxAvgTotalCalculator.
Definition at line 123 of file basic-data-calculators.h.
m_squareTotal
template<typename T = uint32_t> T ns3::MinMaxAvgTotalCalculator< T >::m_squareTotal protected
Sum of squares value of MinMaxAvgTotalCalculator.
Definition at line 114 of file basic-data-calculators.h.
Referenced by ns3::MinMaxAvgTotalCalculator< T >::getSqrSum().
m_total
template<typename T = uint32_t> T ns3::MinMaxAvgTotalCalculator< T >::m_total protected
Total value of MinMaxAvgTotalCalculator.
Definition at line 113 of file basic-data-calculators.h.
Referenced by ns3::MinMaxAvgTotalCalculator< T >::getSum().
m_varianceCurr
template<typename T = uint32_t> double ns3::MinMaxAvgTotalCalculator< T >::m_varianceCurr protected
Current variance of MinMaxAvgTotalCalculator.
Definition at line 120 of file basic-data-calculators.h.
Referenced by ns3::MinMaxAvgTotalCalculator< T >::getStddev(), and ns3::MinMaxAvgTotalCalculator< T >::getVariance().
The documentation for this class was generated from the following file:
src/stats/model/basic-data-calculators.h