ns-3: WaveformGeneratorTestCase Class Reference
WaveformGeneratorTestCase Class Reference
Public Member Functions
WaveformGeneratorTestCase (double period, double dutyCycle, double stop)
virtual ~WaveformGeneratorTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void TraceWave (Ptr< const Packet > newPkt)
Private Attributes
double m_dutyCycle
int m_fails
double m_period
double m_stop
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 31 of file spectrum-waveform-generator-test.cc.
Constructor & Destructor Documentation
WaveformGeneratorTestCase()
WaveformGeneratorTestCase::WaveformGeneratorTestCase (double period, double dutyCycle, double stop)
Definition at line 56 of file spectrum-waveform-generator-test.cc.
~WaveformGeneratorTestCase()
WaveformGeneratorTestCase::~WaveformGeneratorTestCase () virtual
Definition at line 65 of file spectrum-waveform-generator-test.cc.
Member Function Documentation
DoRun()
void WaveformGeneratorTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 71 of file spectrum-waveform-generator-test.cc.
References third::channel, ns3::SpectrumChannelHelper::Create(), ns3::NetDeviceContainer::Get(), ns3::Object::GetObject(), ns3::WaveformGeneratorHelper::Install(), m_dutyCycle, m_fails, m_period, m_stop, ns3::MakeCallback(), sample-rng-plot::n, NS_TEST_ASSERT_MSG_EQ, ns3::Seconds(), ns3::WaveformGeneratorHelper::SetChannel(), ns3::SpectrumChannelHelper::SetChannel(), ns3::WaveformGeneratorHelper::SetPhyAttribute(), ns3::WaveformGeneratorHelper::SetTxPowerSpectralDensity(), ns3::ObjectBase::TraceConnectWithoutContext(), and TraceWave().
TraceWave()
void WaveformGeneratorTestCase::TraceWave (Ptr< const Packet > newPkt) private
Definition at line 48 of file spectrum-waveform-generator-test.cc.
References ns3::Now().
Referenced by DoRun().
Member Data Documentation
m_dutyCycle
double WaveformGeneratorTestCase::m_dutyCycle private
Definition at line 42 of file spectrum-waveform-generator-test.cc.
Referenced by DoRun().
m_fails
int WaveformGeneratorTestCase::m_fails private
Definition at line 44 of file spectrum-waveform-generator-test.cc.
Referenced by DoRun().
m_period
double WaveformGeneratorTestCase::m_period private
Definition at line 41 of file spectrum-waveform-generator-test.cc.
Referenced by DoRun().
m_stop
double WaveformGeneratorTestCase::m_stop private
Definition at line 43 of file spectrum-waveform-generator-test.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/spectrum/test/spectrum-waveform-generator-test.cc