ns-3: ns3::LiIonEnergySourceHelper Class Reference
ns3::LiIonEnergySourceHelper Class Reference
Energy Models
Creates a LiIonEnergySource object.
#include "li-ion-energy-source-helper.h"
Public Member Functions
LiIonEnergySourceHelper ()
~LiIonEnergySourceHelper ()
void Set (std::string name, const AttributeValue &v)
Public Member Functions inherited from ns3::EnergySourceHelper
virtual ~EnergySourceHelper ()
EnergySourceContainer Install (NodeContainer c) const
EnergySourceContainer Install (Ptr< Node > node) const
EnergySourceContainer Install (std::string nodeName) const
EnergySourceContainer InstallAll (void) const
This function installs an EnergySource on all nodes in simulation.
Private Member Functions
virtual Ptr< EnergySource > DoInstall (Ptr< Node > node) const
Private Attributes
ObjectFactory m_liIonEnergySource
Detailed Description
Creates a LiIonEnergySource object.
Definition at line 36 of file li-ion-energy-source-helper.h.
Constructor & Destructor Documentation
LiIonEnergySourceHelper()
ns3::LiIonEnergySourceHelper::LiIonEnergySourceHelper ()
Definition at line 28 of file li-ion-energy-source-helper.cc.
References m_liIonEnergySource, and ns3::ObjectFactory::SetTypeId().
~LiIonEnergySourceHelper()
ns3::LiIonEnergySourceHelper::~LiIonEnergySourceHelper ()
Definition at line 33 of file li-ion-energy-source-helper.cc.
Member Function Documentation
DoInstall()
Ptr< EnergySource > ns3::LiIonEnergySourceHelper::DoInstall (Ptr< Node > node) const private virtual
Parameters
node Pointer to node where the energy source is to be installed.
Returns
Pointer to the created EnergySource.
Child classes of EnergySourceHelper only have to implement this function, to create and aggregate an EnergySource object onto a single node. Rest of the installation process (eg. installing EnergySource on set of nodes) is implemented in the EnergySourceHelper base class.
Implements ns3::EnergySourceHelper.
Definition at line 44 of file li-ion-energy-source-helper.cc.
References ns3::ObjectFactory::Create(), m_liIonEnergySource, and NS_ASSERT.
Set()
void ns3::LiIonEnergySourceHelper::Set (std::string name, const AttributeValue & v) virtual
Parameters
name Name of attribute to set.
v Value of the attribute.
Sets one of the attributes of underlying EnergySource.
Implements ns3::EnergySourceHelper.
Definition at line 38 of file li-ion-energy-source-helper.cc.
References m_liIonEnergySource, and ns3::ObjectFactory::Set().
Member Data Documentation
m_liIonEnergySource
ObjectFactory ns3::LiIonEnergySourceHelper::m_liIonEnergySource private
Definition at line 48 of file li-ion-energy-source-helper.h.
Referenced by LiIonEnergySourceHelper(), DoInstall(), and Set().
The documentation for this class was generated from the following files:
src/energy/helper/li-ion-energy-source-helper.h
src/energy/helper/li-ion-energy-source-helper.cc