ns-3: ThreeGppV2vBuildingsChCondModelTestCase Class Reference
ThreeGppV2vBuildingsChCondModelTestCase Class Reference
Test case for the classes ThreeGppV2vUrbanChannelConditionModel, and ThreeGppV2vHighwayChannelConditionModel to test their code to deterministically determine NLOS state.
Classes
struct TestVector
Struct containing the parameters for each test.
Public Member Functions
ThreeGppV2vBuildingsChCondModelTestCase ()
Constructor.
virtual ~ThreeGppV2vBuildingsChCondModelTestCase ()
Destructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Builds the simulation scenario and perform the tests.
Private Attributes
TestVectors< TestVector > m_testVectors
array containg all the test vectors
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test case for the classes ThreeGppV2vUrbanChannelConditionModel, and ThreeGppV2vHighwayChannelConditionModel to test their code to deterministically determine NLOS state.
The test checks if the channel condition is correctly determined when a building is deployed in the scenario. Methodology from buildings-channel-condition-model-test.cc is used.
Definition at line 47 of file three-gpp-v2v-channel-condition-model-test.cc.
Constructor & Destructor Documentation
ThreeGppV2vBuildingsChCondModelTestCase()
ThreeGppV2vBuildingsChCondModelTestCase::ThreeGppV2vBuildingsChCondModelTestCase ()
Constructor.
Definition at line 80 of file three-gpp-v2v-channel-condition-model-test.cc.
~ThreeGppV2vBuildingsChCondModelTestCase()
ThreeGppV2vBuildingsChCondModelTestCase::~ThreeGppV2vBuildingsChCondModelTestCase () virtual
Destructor.
Definition at line 84 of file three-gpp-v2v-channel-condition-model-test.cc.
Member Function Documentation
DoRun()
void ThreeGppV2vBuildingsChCondModelTestCase::DoRun (void) private virtual
Builds the simulation scenario and perform the tests.
Implements ns3::TestCase.
Definition at line 88 of file three-gpp-v2v-channel-condition-model-test.cc.
References ns3::ObjectFactory::Create(), ns3::Object::GetObject(), ThreeGppV2vBuildingsChCondModelTestCase::TestVector::m_losCond, ThreeGppV2vBuildingsChCondModelTestCase::TestVector::m_positionA, ThreeGppV2vBuildingsChCondModelTestCase::TestVector::m_positionB, m_testVectors, ThreeGppV2vBuildingsChCondModelTestCase::TestVector::m_typeId, first::nodes, NS_LOG_DEBUG, NS_TEST_ASSERT_MSG_EQ, ns3::MobilityModel::SetPosition(), and ns3::ObjectFactory::SetTypeId().
Member Data Documentation
m_testVectors
TestVectors<TestVector> ThreeGppV2vBuildingsChCondModelTestCase::m_testVectors private
array containg all the test vectors
Definition at line 77 of file three-gpp-v2v-channel-condition-model-test.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/buildings/test/three-gpp-v2v-channel-condition-model-test.cc