ns-3: ns3::UniformRandomVariable Class Reference
ns3::UniformRandomVariable Class Reference
Core » Random Variables
The uniform distribution Random Number Generator (RNG).
#include "random-variable-stream.h"
Public Member Functions
UniformRandomVariable ()
Creates a uniform distribution RNG with the default range.
uint32_t GetInteger (uint32_t min, uint32_t max)
Get the next random value, as an unsigned integer in the specified range .
virtual uint32_t GetInteger (void)
Get the next random value as an integer drawn from the distribution.
double GetMax (void) const
Get the upper bound on values returned by GetValue(void).
double GetMin (void) const
Get the lower bound on randoms returned by GetValue(void).
double GetValue (double min, double max)
Get the next random value, as a double in the specified range .
virtual double GetValue (void)
Get the next random value as a double drawn from the distribution.
Public Member Functions inherited from ns3::RandomVariableStream
RandomVariableStream ()
Default constructor.
virtual ~RandomVariableStream ()
Destructor.
int64_t GetStream (void) const
Returns the stream number for the RngStream.
bool IsAntithetic (void) const
Check if antithetic values will be generated.
void SetAntithetic (bool isAntithetic)
Specify whether antithetic values should be generated.
void SetStream (int64_t stream)
Specifies the stream number for the RngStream.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::RandomVariableStream
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
double m_max
The upper bound on values that can be returned by this RNG stream.
double m_min
The lower bound on values that can be returned by this RNG stream.
Additional Inherited Members
Protected Member Functions inherited from ns3::RandomVariableStream
RngStream * Peek (void) const
Get the pointer to the underlying RngStream.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The uniform distribution Random Number Generator (RNG).
This class supports the creation of objects that return random numbers from a fixed uniform distribution. It also supports the generation of single random numbers from various uniform distributions.
The output range is for floating point values, (max excluded), and (max included) for integral values.
Example
Here is an example of how to use this class:
double min = 0.0;
double max = 10.0;
Ptr<UniformRandomVariable> x = CreateObject<UniformRandomVariable> ();
x->SetAttribute ("Min", DoubleValue (min));
x->SetAttribute ("Max", DoubleValue (max));
// The values returned by a uniformly distributed random
// variable should always be within the range
//
//     [min, max)  .
//
double value = x->GetValue ();
Antithetic Values.
Normally this RNG returns values in the interval . If an instance of this RNG is configured to return antithetic values, the actual value returned is calculated as follows:
Compute the initial random value as normal.
Compute the distance from the maximum,
Return :
Config Paths
ns3::UniformRandomVariable is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::SimpleNetDevice/ReceiveErrorModel/$ns3::RateErrorModel/RanVar/$ns3::UniformRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::SimpleNetDevice/ReceiveErrorModel/$ns3::BurstErrorModel/BurstStart/$ns3::UniformRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::SimpleNetDevice/ReceiveErrorModel/$ns3::BurstErrorModel/BurstSize/$ns3::UniformRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::SpectrumChannel/PropagationLossModel/$ns3::RandomPropagationLossModel/Variable/$ns3::UniformRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::YansWifiChannel/PropagationLossModel/$ns3::RandomPropagationLossModel/Variable/$ns3::UniformRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::YansWifiChannel/PropagationDelayModel/$ns3::RandomPropagationDelayModel/Variable/$ns3::UniformRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Phy/PostReceptionErrorModel/$ns3::RateErrorModel/RanVar/$ns3::UniformRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Phy/PostReceptionErrorModel/$ns3::BurstErrorModel/BurstStart/$ns3::UniformRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Phy/PostReceptionErrorModel/$ns3::BurstErrorModel/BurstSize/$ns3::UniformRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Mac/$ns3::RegularWifiMac/$ns3::InfrastructureWifiMac/$ns3::ApWifiMac/BeaconJitter"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Mac/$ns3::RegularWifiMac/$ns3::ApWifiMac/BeaconJitter"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Mac/$ns3::InfrastructureWifiMac/$ns3::ApWifiMac/BeaconJitter"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Mac/$ns3::ApWifiMac/BeaconJitter"
"/NodeList/[i]/DeviceList/[i]/$ns3::PointToPointNetDevice/ReceiveErrorModel/$ns3::RateErrorModel/RanVar/$ns3::UniformRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::PointToPointNetDevice/ReceiveErrorModel/$ns3::BurstErrorModel/BurstStart/$ns3::UniformRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::PointToPointNetDevice/ReceiveErrorModel/$ns3::BurstErrorModel/BurstSize/$ns3::UniformRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::CsmaNetDevice/ReceiveErrorModel/$ns3::RateErrorModel/RanVar/$ns3::UniformRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::CsmaNetDevice/ReceiveErrorModel/$ns3::BurstErrorModel/BurstStart/$ns3::UniformRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::CsmaNetDevice/ReceiveErrorModel/$ns3::BurstErrorModel/BurstSize/$ns3::UniformRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::SixLowPanNetDevice/MeshUnderJitter/$ns3::UniformRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::LrWpanNetDevice/Channel/PropagationLossModel/$ns3::RandomPropagationLossModel/Variable/$ns3::UniformRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::SpectrumChannel/PropagationLossModel/$ns3::RandomPropagationLossModel/Variable/$ns3::UniformRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::YansWifiChannel/PropagationLossModel/$ns3::RandomPropagationLossModel/Variable/$ns3::UniformRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::YansWifiChannel/PropagationDelayModel/$ns3::RandomPropagationDelayModel/Variable/$ns3::UniformRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/PhyEntities/[i]/PostReceptionErrorModel/$ns3::RateErrorModel/RanVar/$ns3::UniformRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/PhyEntities/[i]/PostReceptionErrorModel/$ns3::BurstErrorModel/BurstStart/$ns3::UniformRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/PhyEntities/[i]/PostReceptionErrorModel/$ns3::BurstErrorModel/BurstSize/$ns3::UniformRandomVariable"
"/NodeList/[i]/ApplicationList/[i]/$ns3::OnOffApplication/OnTime/$ns3::UniformRandomVariable"
"/NodeList/[i]/ApplicationList/[i]/$ns3::OnOffApplication/OffTime/$ns3::UniformRandomVariable"
"/NodeList/[i]/ApplicationList/[i]/$ns3::Radvd/AdvertisementJitter"
"/NodeList/[i]/ApplicationList/[i]/$ns3::DhcpClient/Transactions/$ns3::UniformRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::GaussMarkovMobilityModel/MeanVelocity/$ns3::UniformRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::GaussMarkovMobilityModel/MeanDirection/$ns3::UniformRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::GaussMarkovMobilityModel/MeanPitch/$ns3::UniformRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomDirection2dMobilityModel/Speed/$ns3::UniformRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomDirection2dMobilityModel/Pause/$ns3::UniformRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWalk2dMobilityModel/Direction/$ns3::UniformRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWalk2dMobilityModel/Speed/$ns3::UniformRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/Speed/$ns3::UniformRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/Pause/$ns3::UniformRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::RandomRectanglePositionAllocator/X/$ns3::UniformRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::RandomRectanglePositionAllocator/Y/$ns3::UniformRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::RandomBoxPositionAllocator/X/$ns3::UniformRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::RandomBoxPositionAllocator/Y/$ns3::UniformRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::RandomBoxPositionAllocator/Z/$ns3::UniformRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::RandomDiscPositionAllocator/Theta/$ns3::UniformRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::RandomDiscPositionAllocator/Rho/$ns3::UniformRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::OutdoorPositionAllocator/X/$ns3::UniformRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::OutdoorPositionAllocator/Y/$ns3::UniformRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::OutdoorPositionAllocator/Z/$ns3::UniformRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWalk2dOutdoorMobilityModel/Direction/$ns3::UniformRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWalk2dOutdoorMobilityModel/Speed/$ns3::UniformRandomVariable"
"/NodeList/[i]/$ns3::ArpL3Protocol/RequestJitter/$ns3::UniformRandomVariable"
"/NodeList/[i]/$ns3::Icmpv6L4Protocol/SolicitationJitter/$ns3::UniformRandomVariable"
"/NodeList/[i]/$ns3::aodv::RoutingProtocol/UniformRv"
"/ChannelList/[i]/$ns3::SpectrumChannel/PropagationLossModel/$ns3::RandomPropagationLossModel/Variable/$ns3::UniformRandomVariable"
"/ChannelList/[i]/$ns3::YansWifiChannel/PropagationLossModel/$ns3::RandomPropagationLossModel/Variable/$ns3::UniformRandomVariable"
"/ChannelList/[i]/$ns3::YansWifiChannel/PropagationDelayModel/$ns3::RandomPropagationDelayModel/Variable/$ns3::UniformRandomVariable"
Attributes
Min: The lower bound on the values returned by this RNG stream.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0
Flags: construct write read
Max: The upper bound on the values returned by this RNG stream.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 1
Flags: construct write read
Attributes defined in parent class ns3::RandomVariableStream
Stream: The stream number for this RNG stream. -1 means "allocate a stream automatically". Note that if -1 is set, Get will return -1 so that it is not possible to know which value was automatically allocated.
Set with class: ns3::IntegerValue
Underlying type: int64_t -9223372036854775808:9223372036854775807
Initial value: -1
Flags: construct write read
Antithetic: Set this RNG stream to generate antithetic values
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 72 bytes (on a 64-bit architecture).
Definition at line 234 of file random-variable-stream.h.
Constructor & Destructor Documentation
UniformRandomVariable()
ns3::UniformRandomVariable::UniformRandomVariable ()
Creates a uniform distribution RNG with the default range.
Definition at line 162 of file random-variable-stream.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
GetInteger() [1/2]
uint32_t ns3::UniformRandomVariable::GetInteger (uint32_t min, uint32_t max)
Get the next random value, as an unsigned integer in the specified range .
Note
The upper limit is included in the output range.
Parameters
[in] min Low end of the range.
[in] max High end of the range.
Returns
A random unsigned integer value.
Definition at line 193 of file random-variable-stream.cc.
References GetValue(), ns3::max(), ns3::min(), NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::LrWpanHelper::AssociateToBeaconPan(), ns3::dsr::DsrRouting::CancelPacketTimerNextHop(), ns3::aodv::RoutingProtocol::DoInitialize(), ns3::Txop::GenerateBackoff(), ns3::BriteTopologyHelper::GenerateBriteTopology(), ns3::TvSpectrumTransmitterHelper::GenerateRegionalTransmitterIndices(), ns3::BsmApplication::GenerateWaveTraffic(), ns3::ThreeGppUmaPropagationLossModel::GetBpDistance(), ns3::RandomBuildingPositionAllocator::GetNext(), ns3::RandomRoomPositionAllocator::GetNext(), ns3::TvSpectrumTransmitterHelper::GetRandomNumTransmitters(), ns3::MinstrelHtWifiManager::InitSampleTable(), ns3::MinstrelWifiManager::InitSampleTable(), ns3::Ipv4GlobalRouting::LookupGlobal(), ns3::dsr::DsrRouting::PriorityScheduler(), ns3::LteUeMac::RandomlySelectAndSendRaPreamble(), ns3::dsdv::RoutingProtocol::RecvDsdv(), ns3::aodv::RoutingProtocol::RecvRequest(), ns3::dsdv::RoutingProtocol::RouteOutput(), ns3::dsr::DsrRouting::ScheduleInterRequest(), Experiment::SelectSrcDest(), ns3::dsr::DsrRouting::Send(), ns3::aodv::RoutingProtocol::SendHello(), ns3::dsr::DsrRouting::SendPacketFromBuffer(), ns3::dsdv::RoutingProtocol::SendPacketFromQueue(), ns3::dsdv::RoutingProtocol::SendPeriodicUpdate(), ns3::aodv::RoutingProtocol::SendRequest(), ns3::aodv::RoutingProtocol::SendRerrMessage(), ns3::ThreeGppChannelModel::Shuffle(), ns3::dsdv::RoutingProtocol::Start(), and ns3::BsmApplication::StartApplication().
GetInteger() [2/2]
uint32_t ns3::UniformRandomVariable::GetInteger (void) virtual
Get the next random value as an integer drawn from the distribution.
Returns
An integer random value.
Note
The upper limit is included in the output range.
Implements ns3::RandomVariableStream.
Definition at line 207 of file random-variable-stream.cc.
References GetValue(), m_max, m_min, and NS_LOG_FUNCTION.
GetMax()
double ns3::UniformRandomVariable::GetMax (void) const
Get the upper bound on values returned by GetValue(void).
Returns
The upper bound on values from GetValue(void).
Definition at line 175 of file random-variable-stream.cc.
References m_max, and NS_LOG_FUNCTION.
GetMin()
double ns3::UniformRandomVariable::GetMin (void) const
Get the lower bound on randoms returned by GetValue(void).
Returns
The lower bound on values from GetValue(void).
Definition at line 169 of file random-variable-stream.cc.
References m_min, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::UniformRandomVariable::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 145 of file random-variable-stream.cc.
References m_max, m_min, ns3::MakeDoubleAccessor(), and ns3::TypeId::SetParent().
GetValue() [1/2]
double ns3::UniformRandomVariable::GetValue (double min, double max)
Get the next random value, as a double in the specified range .
Note
The upper limit is excluded from the output range.
Parameters
[in] min Low end of the range (included).
[in] max High end of the range (excluded).
Returns
A floating point random value.
Definition at line 182 of file random-variable-stream.cc.
References ns3::RandomVariableStream::IsAntithetic(), ns3::max(), ns3::min(), NS_LOG_FUNCTION, ns3::RandomVariableStream::Peek(), and ns3::RngStream::RandU01().
Referenced by ns3::LrWpanMac::LrWpanMac(), ns3::SteadyStateRandomWaypointMobilityModel::BeginWalk(), ns3::ThreeGppChannelModel::CalcAttenuationOfBlockage(), ns3::ThreeGppSpectrumPropagationLossModel::CalcBeamformingGain(), ns3::LrWpanPhy::CheckInterference(), RngUniformTestCase::ChiSquaredTest(), ns3::CobaltQueueDisc::CobaltShouldDrop(), ns3::ThreeGppChannelConditionModel::ComputeChannelCondition(), ns3::WifiPhy::ContinueReceiveHeader(), FemtocellBlockAllocator::Create(), ns3::TraceFadingLossModel::DoCalcRxPowerSpectralDensity(), ns3::SixLowPanNetDevice::DoFragmentation(), ns3::Rip::DoInitialize(), ns3::RipNg::DoInitialize(), ns3::dot11s::HwmpProtocol::DoInitialize(), ns3::MeshWifiInterfaceMac::DoInitialize(), ns3::ApWifiMac::DoInitialize(), ns3::RandomDirection2dMobilityModel::DoInitializePrivate(), ns3::SteadyStateRandomWaypointMobilityModel::DoInitializePrivate(), ns3::tests::OneUniformRandomVariableManyGetValueCallsTestCase::DoRun(), Ipv4DeduplicationPerformanceTest::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), LteX2HandoverTestCase::DoRun(), BufferTest::DoRun(), ns3::PieQueueDisc::DropEarly(), ns3::RedQueueDisc::DropEarly(), ns3::LteSpectrumPhy::EndRxData(), ns3::LteSpectrumPhy::EndRxDlCtrl(), ns3::UanMacCw::Enqueue(), ns3::ThreeGppV2vUrbanPropagationLossModel::GetAdditionalNlosvLoss(), ns3::Backoff::GetBackoffTime(), ns3::ThreeGppUmaPropagationLossModel::GetBpDistance(), ns3::Ipv6ExtensionFragment::GetFragments(), ns3::ThreeGppHttpVariables::GetMtuSize(), ns3::ThreeGppChannelModel::GetNewChannel(), ns3::RandomBuildingPositionAllocator::GetNext(), ns3::RandomRoomPositionAllocator::GetNext(), ns3::SameRoomPositionAllocator::GetNext(), ns3::FixedRoomPositionAllocator::GetNext(), ns3::UniformDiscPositionAllocator::GetNext(), ns3::WifiPhy::GetReceptionStatus(), ns3::Radvd::HandleRead(), DsdvManetExample::InstallApplications(), modify(), Tunnel::N3VirtualSend(), ns3::GeographicPositions::RandCartesianPointsAroundGeographicPoint(), ns3::LrWpanCsmaCa::RandomBackoffDelay(), ns3::RandomDirection2dMobilityModel::ResetDirectionAndSpeed(), RoutingExperiment::Run(), NetAnimExperiment::Run(), Experiment::Run(), ns3::RrpaaWifiManager::RunBasicAlgorithm(), ns3::UanPhyGen::RxEndEvent(), ns3::dsr::DsrRouting::ScheduleCachedReply(), ns3::Radvd::Send(), Experiment::SendMultiDestinations(), UanExperiment::SendPackets(), ns3::Rip::SendTriggeredRouteUpdate(), ns3::RipNg::SendTriggeredRouteUpdate(), ns3::Rip::SendUnsolicitedRouteUpdate(), ns3::RipNg::SendUnsolicitedRouteUpdate(), RoutingHelper::SetupRoutingMessages(), ns3::dot11s::PeerManagementProtocol::ShiftOwnBeacon(), ns3::SteadyStateRandomWaypointMobilityModel::Start(), ns3::SimpleOfdmWimaxPhy::StartReceive(), ns3::WifiPhy::StartReceivePayload(), ns3::SteadyStateRandomWaypointMobilityModel::SteadyStateBeginWalk(), ns3::AnimationInterface::UpdatePosition(), NetAnimExperiment::UpdatePositions(), and Experiment::UpdatePositions().
GetValue() [2/2]
double ns3::UniformRandomVariable::GetValue (void) virtual
Get the next random value as a double drawn from the distribution.
Returns
A floating point random value.
Note
The upper limit is excluded from the output range.
Implements ns3::RandomVariableStream.
Definition at line 201 of file random-variable-stream.cc.
References m_max, m_min, and NS_LOG_FUNCTION.
Referenced by GetInteger().
Member Data Documentation
m_max
double ns3::UniformRandomVariable::m_max private
The upper bound on values that can be returned by this RNG stream.
Definition at line 303 of file random-variable-stream.h.
Referenced by GetInteger(), GetMax(), GetTypeId(), and GetValue().
m_min
double ns3::UniformRandomVariable::m_min private
The lower bound on values that can be returned by this RNG stream.
Definition at line 300 of file random-variable-stream.h.
Referenced by GetInteger(), GetMin(), GetTypeId(), and GetValue().
The documentation for this class was generated from the following files:
src/core/model/random-variable-stream.h
src/core/model/random-variable-stream.cc