ns-3: ns3::TestUtils Class Reference
ns3::TestUtils Class Reference
LTE Models » lte module tests | Test suites
Test Utils.
Static Public Member Functions
static void LogPacketContents (Ptr< Packet > pkt)
Function to log packet contents.
template<class T >
static void LogPacketInfo (T source, std::string s)
Log packet info function.
static std::string sprintPacketContentsBin (Ptr< Packet > pkt)
Function to convert packet contents in binary format.
static std::string sprintPacketContentsHex (Ptr< Packet > pkt)
Function to convert packet contents in hex format.
Detailed Description
Test Utils.
Definition at line 44 of file test-lte-rlc-header.cc.
Member Function Documentation
LogPacketContents()
static void ns3::TestUtils::LogPacketContents (Ptr< Packet > pkt) inline static
Function to log packet contents.
Parameters
pkt the packet
Definition at line 87 of file test-lte-rlc-header.cc.
References NS_LOG_DEBUG, sprintPacketContentsBin(), and sprintPacketContentsHex().
Referenced by ns3::RlcAmStatusPduTestCase::DoRun().
LogPacketInfo()
template<class T > static void ns3::TestUtils::LogPacketInfo (T source, std::string s) inline static
Log packet info function.
Parameters
source T
s text string to log
Definition at line 100 of file test-lte-rlc-header.cc.
References NS_LOG_DEBUG.
sprintPacketContentsBin()
static std::string ns3::TestUtils::sprintPacketContentsBin (Ptr< Packet > pkt) inline static
Function to convert packet contents in binary format.
Parameters
pkt the packet
Returns
a text string
Definition at line 70 of file test-lte-rlc-header.cc.
References ns3::Packet::CopyData(), and ns3::Packet::GetSize().
Referenced by TestUtils::LogPacketContents(), and LogPacketContents().
sprintPacketContentsHex()
static std::string ns3::TestUtils::sprintPacketContentsHex (Ptr< Packet > pkt) inline static
Function to convert packet contents in hex format.
Parameters
pkt the packet
Returns
a text string
Definition at line 52 of file test-lte-rlc-header.cc.
References ns3::Packet::CopyData(), and ns3::Packet::GetSize().
Referenced by ns3::RlcAmStatusPduTestCase::DoRun(), TestUtils::LogPacketContents(), and LogPacketContents().
The documentation for this class was generated from the following file:
src/lte/test/test-lte-rlc-header.cc