ns-3: ns3::OfdmDcdChannelEncodings Class Reference
ns3::OfdmDcdChannelEncodings Class Reference
This class implements the OFDM DCD channel encodings as described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems".
#include "dl-mac-messages.h"
Public Member Functions
OfdmDcdChannelEncodings (void)
~OfdmDcdChannelEncodings (void)
Mac48Address GetBaseStationId (void) const
Get base station ID field.
uint8_t GetChannelNr (void) const
Get channel number field.
uint8_t GetFrameDurationCode (void) const
Get frame duration code field.
uint32_t GetFrameNumber (void) const
Get frame number field.
uint8_t GetRtg (void) const
Get RTG field.
uint16_t GetSize (void) const
Get size field.
uint8_t GetTtg (void) const
Get TTG field.
void SetBaseStationId (Mac48Address baseStationId)
Set base station ID field.
void SetChannelNr (uint8_t channelNr)
Set channel number field.
void SetFrameDurationCode (uint8_t frameDurationCode)
Set frame duration code field.
void SetFrameNumber (uint32_t frameNumber)
Set frame number field.
void SetRtg (uint8_t rtg)
Set RTG field.
void SetTtg (uint8_t ttg)
Set TTG field.
Public Member Functions inherited from ns3::DcdChannelEncodings
DcdChannelEncodings (void)
virtual ~DcdChannelEncodings (void)
uint16_t GetBsEirp (void) const
Get BS EIRP field.
uint16_t GetEirxPIrMax (void) const
Get EIRX IR MAX field.
uint32_t GetFrequency (void) const
Get frequency function.
uint16_t GetSize (void) const
Get size field.
Buffer::Iterator Read (Buffer::Iterator start)
Read item.
void SetBsEirp (uint16_t bs_eirp)
Set BS EIRP field.
void SetEirxPIrMax (uint16_t rss_ir_max)
Set EIRX IR MAX field.
void SetFrequency (uint32_t frequency)
Set frequency field.
Buffer::Iterator Write (Buffer::Iterator start) const
Write item.
Private Member Functions
virtual Buffer::Iterator DoRead (Buffer::Iterator start)
Read item.
virtual Buffer::Iterator DoWrite (Buffer::Iterator start) const
Write item.
Private Attributes
Mac48Address m_baseStationId
base station ID
uint8_t m_channelNr
channel number
uint8_t m_frameDurationCode
frame duration code
uint32_t m_frameNumber
frame number
uint8_t m_rtg
RTG.
uint8_t m_ttg
TTG.
Detailed Description
This class implements the OFDM DCD channel encodings as described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems".
Definition at line 132 of file dl-mac-messages.h.
Constructor & Destructor Documentation
OfdmDcdChannelEncodings()
ns3::OfdmDcdChannelEncodings::OfdmDcdChannelEncodings (void)
Definition at line 105 of file dl-mac-messages.cc.
~OfdmDcdChannelEncodings()
ns3::OfdmDcdChannelEncodings::~OfdmDcdChannelEncodings (void)
Definition at line 115 of file dl-mac-messages.cc.
Member Function Documentation
DoRead()
Buffer::Iterator ns3::OfdmDcdChannelEncodings::DoRead (Buffer::Iterator start) private virtual
Read item.
Parameters
start the iterator
Returns
the updated iterator
Implements ns3::DcdChannelEncodings.
Definition at line 211 of file dl-mac-messages.cc.
References m_baseStationId, m_channelNr, m_frameDurationCode, m_frameNumber, m_rtg, m_ttg, ns3::ReadFrom(), ns3::Buffer::Iterator::ReadU32(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
DoWrite()
Buffer::Iterator ns3::OfdmDcdChannelEncodings::DoWrite (Buffer::Iterator start) const private virtual
Write item.
Parameters
start the iterator
Returns
the updated iterator
Implements ns3::DcdChannelEncodings.
Definition at line 198 of file dl-mac-messages.cc.
References m_baseStationId, m_channelNr, m_frameDurationCode, m_frameNumber, m_rtg, m_ttg, visualizer.core::start(), ns3::WriteTo(), ns3::Buffer::Iterator::WriteU32(), and ns3::Buffer::Iterator::WriteU8().
GetBaseStationId()
Mac48Address ns3::OfdmDcdChannelEncodings::GetBaseStationId (void) const
Get base station ID field.
Returns
the base station MAC address
Definition at line 174 of file dl-mac-messages.cc.
References m_baseStationId.
GetChannelNr()
uint8_t ns3::OfdmDcdChannelEncodings::GetChannelNr (void) const
Get channel number field.
Returns
the channel number
Definition at line 156 of file dl-mac-messages.cc.
References m_channelNr.
GetFrameDurationCode()
uint8_t ns3::OfdmDcdChannelEncodings::GetFrameDurationCode (void) const
Get frame duration code field.
Returns
the frame duration code
Definition at line 180 of file dl-mac-messages.cc.
References m_frameDurationCode.
Referenced by ns3::SubscriberStationNetDevice::ProcessDcd().
GetFrameNumber()
uint32_t ns3::OfdmDcdChannelEncodings::GetFrameNumber (void) const
Get frame number field.
Returns
the frame number
Definition at line 186 of file dl-mac-messages.cc.
References m_frameNumber.
GetRtg()
uint8_t ns3::OfdmDcdChannelEncodings::GetRtg (void) const
Get RTG field.
Returns
the RTG
Definition at line 168 of file dl-mac-messages.cc.
References m_rtg.
GetSize()
uint16_t ns3::OfdmDcdChannelEncodings::GetSize (void) const
Get size field.
Returns
the size
Definition at line 192 of file dl-mac-messages.cc.
References ns3::DcdChannelEncodings::GetSize().
Referenced by ns3::Dcd::GetSerializedSize().
GetTtg()
uint8_t ns3::OfdmDcdChannelEncodings::GetTtg (void) const
Get TTG field.
Returns
the TTG
Definition at line 162 of file dl-mac-messages.cc.
References m_ttg.
SetBaseStationId()
void ns3::OfdmDcdChannelEncodings::SetBaseStationId (Mac48Address baseStationId)
Set base station ID field.
Parameters
baseStationId the base station ID
Definition at line 138 of file dl-mac-messages.cc.
References m_baseStationId.
Referenced by ns3::BaseStationNetDevice::CreateDcd().
SetChannelNr()
void ns3::OfdmDcdChannelEncodings::SetChannelNr (uint8_t channelNr)
Set channel number field.
Parameters
channelNr the channel number
Definition at line 120 of file dl-mac-messages.cc.
References m_channelNr.
Referenced by ns3::BaseStationNetDevice::CreateDcd().
SetFrameDurationCode()
void ns3::OfdmDcdChannelEncodings::SetFrameDurationCode (uint8_t frameDurationCode)
Set frame duration code field.
Parameters
frameDurationCode the frame duration code
Definition at line 144 of file dl-mac-messages.cc.
References m_frameDurationCode.
Referenced by ns3::BaseStationNetDevice::CreateDcd().
SetFrameNumber()
void ns3::OfdmDcdChannelEncodings::SetFrameNumber (uint32_t frameNumber)
Set frame number field.
Parameters
frameNumber the frame number
Definition at line 150 of file dl-mac-messages.cc.
References m_frameNumber.
Referenced by ns3::BaseStationNetDevice::CreateDcd().
SetRtg()
void ns3::OfdmDcdChannelEncodings::SetRtg (uint8_t rtg)
Set RTG field.
Parameters
rtg the RTG
Definition at line 132 of file dl-mac-messages.cc.
References m_rtg.
Referenced by ns3::BaseStationNetDevice::CreateDcd().
SetTtg()
void ns3::OfdmDcdChannelEncodings::SetTtg (uint8_t ttg)
Set TTG field.
Parameters
ttg the TTG
Definition at line 126 of file dl-mac-messages.cc.
References m_ttg.
Referenced by ns3::BaseStationNetDevice::CreateDcd().
Member Data Documentation
m_baseStationId
Mac48Address ns3::OfdmDcdChannelEncodings::m_baseStationId private
base station ID
Definition at line 225 of file dl-mac-messages.h.
Referenced by DoRead(), DoWrite(), GetBaseStationId(), and SetBaseStationId().
m_channelNr
uint8_t ns3::OfdmDcdChannelEncodings::m_channelNr private
channel number
Definition at line 221 of file dl-mac-messages.h.
Referenced by DoRead(), DoWrite(), GetChannelNr(), and SetChannelNr().
m_frameDurationCode
uint8_t ns3::OfdmDcdChannelEncodings::m_frameDurationCode private
frame duration code
Definition at line 226 of file dl-mac-messages.h.
Referenced by DoRead(), DoWrite(), GetFrameDurationCode(), and SetFrameDurationCode().
m_frameNumber
uint32_t ns3::OfdmDcdChannelEncodings::m_frameNumber private
frame number
Definition at line 227 of file dl-mac-messages.h.
Referenced by DoRead(), DoWrite(), GetFrameNumber(), and SetFrameNumber().
m_rtg
uint8_t ns3::OfdmDcdChannelEncodings::m_rtg private
RTG.
Definition at line 223 of file dl-mac-messages.h.
Referenced by DoRead(), DoWrite(), GetRtg(), and SetRtg().
m_ttg
uint8_t ns3::OfdmDcdChannelEncodings::m_ttg private
TTG.
Definition at line 222 of file dl-mac-messages.h.
Referenced by DoRead(), DoWrite(), GetTtg(), and SetTtg().
The documentation for this class was generated from the following files:
src/wimax/model/dl-mac-messages.h
src/wimax/model/dl-mac-messages.cc