ns-3: ns3::LteUeRrc Class Reference
ns3::LteUeRrc Class Reference
#include "lte-ue-rrc.h"
Classes
struct MeasValues
Represents a measurement result from a certain cell.
struct PendingTrigger_t
Represents a single triggered event from a measurement identity which reporting criteria have been fulfilled, but delayed by time-to-trigger.
struct VarMeasConfig
Includes the accumulated configuration of the measurements to be performed by the UE.
struct VarMeasReport
Represents a single measurement reporting entry., which includes information about a measurement for which the triggering conditions have been met.
Public Types
typedef void(* CellSelectionTracedCallback) (uint64_t imsi, uint16_t cellId)
TracedCallback signature for imsi, cellId and rnti events.
typedef void(* ImsiCidRntiCountTracedCallback) (uint64_t imsi, uint16_t cellId, uint16_t rnti, uint8_t count)
TracedCallback signature for imsi, cellId, rnti and counter for random access events.
typedef void(* ImsiCidRntiTracedCallback) (uint64_t imsi, uint16_t cellId, uint16_t rnti)
TracedCallback signature for imsi, cellId and rnti events.
typedef void(* MibSibHandoverTracedCallback) (uint64_t imsi, uint16_t cellId, uint16_t rnti, uint16_t otherCid)
TracedCallback signature for MIBRecieved, Sib1Received and HandoverStart events.
typedef void(* PhySyncDetectionTracedCallback) (uint64_t imsi, uint16_t rnti, uint16_t cellId, std::string type, uint16_t count)
TracedCallback signature for in-sync and out-of-sync detection events.
typedef void(* SCarrierConfiguredTracedCallback) (Ptr< LteUeRrc >, std::list< LteRrcSap::SCellToAddMod >)
TracedCallback signature for secondary carrier configuration events.
enum State {
IDLE_START = 0 , IDLE_CELL_SEARCH , IDLE_WAIT_MIB_SIB1 , IDLE_WAIT_MIB ,
IDLE_WAIT_SIB1 , IDLE_CAMPED_NORMALLY , IDLE_WAIT_SIB2 , IDLE_RANDOM_ACCESS ,
IDLE_CONNECTING , CONNECTED_NORMALLY , CONNECTED_HANDOVER , CONNECTED_PHY_PROBLEM ,
CONNECTED_REESTABLISHING , NUM_STATES
}
The states of the UE RRC entity.
typedef void(* StateTracedCallback) (uint64_t imsi, uint16_t cellId, uint16_t rnti, State oldState, State newState)
TracedCallback signature for state transition events.
Public Member Functions
LteUeRrc ()
create an RRC instance for use within an ue
virtual ~LteUeRrc ()
Destructor.
LteAsSapProvider * GetAsSapProvider ()
uint16_t GetCellId () const
uint8_t GetDlBandwidth () const
uint32_t GetDlEarfcn () const
uint64_t GetImsi (void) const
LteUeCcmRrcSapUser * GetLteCcmRrcSapUser ()
Get the Component Carrier Management SAP offered by this RRC.
LteUeCmacSapUser * GetLteUeCmacSapUser ()
This function is overloaded to maintain backward compatibility.
LteUeCmacSapUser * GetLteUeCmacSapUser (uint8_t index)
This function is overloaded to maintain backward compatibility.
LteUeCphySapUser * GetLteUeCphySapUser ()
LteUeCphySapUser * GetLteUeCphySapUser (uint8_t index)
LteUeRrcSapProvider * GetLteUeRrcSapProvider ()
uint16_t GetPreviousCellId () const
Get the previous cell id.
uint16_t GetRnti () const
State GetState () const
uint8_t GetUlBandwidth () const
uint32_t GetUlEarfcn () const
void InitializeSap (void)
Initiaize SAP.
void SetAsSapUser (LteAsSapUser *s)
Set the AS SAP user to interact with the NAS entity.
void SetImsi (uint64_t imsi)
void SetLteCcmRrcSapProvider (LteUeCcmRrcSapProvider *s)
set the Component Carrier Management SAP this RRC should interact with
void SetLteMacSapProvider (LteMacSapProvider *s)
set the MAC SAP provider.
void SetLteUeCmacSapProvider (LteUeCmacSapProvider *s)
set the CMAC SAP this RRC should interact with
void SetLteUeCmacSapProvider (LteUeCmacSapProvider *s, uint8_t index)
set the CMAC SAP this RRC should interact with
void SetLteUeCphySapProvider (LteUeCphySapProvider *s)
set the CPHY SAP this RRC should use to interact with the PHY
void SetLteUeCphySapProvider (LteUeCphySapProvider *s, uint8_t index)
set the CPHY SAP this RRC should use to interact with the PHY
void SetLteUeRrcSapUser (LteUeRrcSapUser *s)
set the RRC SAP this RRC should interact with
void SetUseRlcSm (bool val)
void StorePreviousCellId (uint16_t cellId)
Store the previous cell id.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Public Attributes
uint16_t m_numberOfComponentCarriers
The number of component carriers.
Private Types
typedef std::list< uint16_t > ConcernedCells_t
List of cell IDs which are responsible for a certain trigger.
Private Member Functions
void ApplyMeasConfig (LteRrcSap::MeasConfig mc)
Update the current measurement configuration m_varMeasConfig.
void ApplyRadioResourceConfigDedicated (LteRrcSap::RadioResourceConfigDedicated rrcd)
Apply radio resource config dedicated.
void ApplyRadioResourceConfigDedicatedSecondaryCarrier (LteRrcSap::NonCriticalExtensionConfiguration nonCec)
Apply radio resource config dedicated secondary carrier.
uint8_t Bid2Drbid (uint8_t bid)
Bid 2 DR bid.
void CancelEnteringTrigger (uint8_t measId)
Clear all the waiting triggers in m_enteringTriggerQueue which are associated with the given measurement identity.
void CancelEnteringTrigger (uint8_t measId, uint16_t cellId)
Remove a specific cell from the waiting triggers in m_enteringTriggerQueue which belong to the given measurement identity.
void CancelLeavingTrigger (uint8_t measId)
Clear all the waiting triggers in m_leavingTriggerQueue which are associated with the given measurement identity.
void CancelLeavingTrigger (uint8_t measId, uint16_t cellId)
Remove a specific cell from the waiting triggers in m_leavingTriggerQueue which belong to the given measurement identity.
void ConnectionTimeout ()
Invoked after timer T300 expires, notifying upper layers that RRC connection establishment procedure has failed.
void DisposeOldSrb1 ()
Dispose old SRB1.
void DoCompleteSetup (LteUeRrcSapProvider::CompleteSetupParameters params)
Part of the RRC protocol.
void DoConnect ()
Connect function.
void DoDisconnect ()
Disconnect function.
virtual void DoDispose (void)
Destructor implementation.
void DoForceCampedOnEnb (uint16_t cellId, uint32_t dlEarfcn)
Force camped on ENB function.
virtual void DoInitialize (void)
Initialize() implementation.
void DoNotifyInSync ()
Do notify in sync function.
void DoNotifyOutOfSync ()
Do notify out of sync function.
void DoNotifyRandomAccessFailed ()
Notify random access failed function.
void DoNotifyRandomAccessSuccessful ()
Notify random access successful function.
void DoReceivePdcpSdu (LtePdcpSapUser::ReceivePdcpSduParameters params)
Receive PDCP SDU function.
void DoRecvMasterInformationBlock (uint16_t cellId, LteRrcSap::MasterInformationBlock msg)
Receive master information block function.
void DoRecvRrcConnectionReconfiguration (LteRrcSap::RrcConnectionReconfiguration msg)
Part of the RRC protocol.
void DoRecvRrcConnectionReestablishment (LteRrcSap::RrcConnectionReestablishment msg)
Part of the RRC protocol.
void DoRecvRrcConnectionReestablishmentReject (LteRrcSap::RrcConnectionReestablishmentReject msg)
Part of the RRC protocol.
void DoRecvRrcConnectionReject (LteRrcSap::RrcConnectionReject msg)
Part of the RRC protocol.
void DoRecvRrcConnectionRelease (LteRrcSap::RrcConnectionRelease msg)
Part of the RRC protocol.
void DoRecvRrcConnectionSetup (LteRrcSap::RrcConnectionSetup msg)
Part of the RRC protocol.
void DoRecvSystemInformation (LteRrcSap::SystemInformation msg)
Part of the RRC protocol.
void DoRecvSystemInformationBlockType1 (uint16_t cellId, LteRrcSap::SystemInformationBlockType1 msg)
Receive system information block type 1 function.
void DoReportUeMeasurements (LteUeCphySapUser::UeMeasurementsParameters params)
Report UE measurements function.
void DoResetSyncIndicationCounter ()
Do reset sync indication counter function.
void DoSendData (Ptr< Packet > packet, uint8_t bid)
Send data function.
void DoSetCsgWhiteList (uint32_t csgId)
Set CSG white list function.
void DoSetNumberOfComponentCarriers (uint16_t noOfComponentCarriers)
RRC CCM SAP USER Method.
void DoSetTemporaryCellRnti (uint16_t rnti)
Set temporary cell rnti function.
void DoStartCellSelection (uint32_t dlEarfcn)
Start cell selection function.
void EvaluateCellForSelection ()
Performs cell selection evaluation to the current serving cell.
void LeaveConnectedMode ()
Leave connected mode method Resets the UE back to an appropiate state depending on the nature of cause.
void MeasurementReportTriggering (uint8_t measId)
Evaluate the reporting criteria of a measurement identity and invoke some reporting actions based on the result.
void RadioLinkFailureDetected ()
Radio link failure detected function.
void ResetRlfParams ()
Reset radio link failure parameters.
void SaveScellUeMeasurements (uint16_t cellId, double rsrp, double rsrq, bool useLayer3Filtering, uint16_t componentCarrierId)
keep the given measurement result as the latest measurement figures, to be utilised by UE RRC functions.
void SaveUeMeasurements (uint16_t cellId, double rsrp, double rsrq, bool useLayer3Filtering)
Keep the given measurement result as the latest measurement figures, to be utilised by UE RRC functions.
void SendMeasurementReport (uint8_t measId)
Produce a proper measurement report from the given measurement identity's reporting entry in m_varMeasReportList and then submit it to the serving eNodeB.
void StartConnection ()
Start connection function.
void SwitchToState (State s)
Switch the UE RRC to the given state.
void SynchronizeToStrongestCell ()
Go through the list of measurement results, choose the one with the strongest RSRP, and tell PHY to synchronize to it.
void VarMeasReportListAdd (uint8_t measId, ConcernedCells_t enteringCells)
Compose a new reporting entry of the given measurement identity, insert it into m_varMeasReportList, and set it up for submission to eNodeB.
void VarMeasReportListClear (uint8_t measId)
Remove the reporting entry of the given measurement identity from m_varMeasReportList.
void VarMeasReportListErase (uint8_t measId, ConcernedCells_t leavingCells, bool reportOnLeave)
Remove some cells from an existing reporting entry in m_varMeasReportList.
Private Attributes
std::set< uint16_t > m_acceptableCell
List of cell ID of acceptable cells for cell selection that have been detected.
LteAsSapProvider * m_asSapProvider
AS SAP provider.
LteAsSapUser * m_asSapUser
AS SAP user.
std::map< uint8_t, uint8_t > m_bid2DrbidMap
bid to DR bid map
LteUeCcmRrcSapProvider * m_ccmRrcSapProvider
Interface to the LteUeComponentCarrierManage instance.
LteUeCcmRrcSapUser * m_ccmRrcSapUser
CCM RRC SAP user.
uint16_t m_cellId
The CellId attribute.
std::vector< LteUeCmacSapProvider * > m_cmacSapProvider
UE CMac SAP provider.
std::vector< LteUeCmacSapUser * > m_cmacSapUser
UE CMac SAP user.
TracedCallback< uint64_t, uint16_t, uint16_t > m_connectionEstablishedTrace
The ConnectionEstablished trace source.
bool m_connectionPending
True if a connection request by upper layers is pending.
TracedCallback< uint64_t, uint16_t, uint16_t > m_connectionReconfigurationTrace
The ConnectionReconfiguration trace source.
EventId m_connectionTimeout
Invokes ConnectionEstablishmentTimeout() if RRC connection establishment procedure for this UE takes longer than T300.
TracedCallback< uint64_t, uint16_t, uint16_t, uint8_t > m_connectionTimeoutTrace
The ConnectionTimeout trace source.
uint8_t m_connEstFailCount
the counter to count T300 timer expiration
uint8_t m_connEstFailCountLimit
the counter value for T300 timer expiration received from the eNB
std::vector< LteUeCphySapProvider * > m_cphySapProvider
UE CPhy SAP provider.
std::vector< LteUeCphySapUser * > m_cphySapUser
UE CPhy SAP user.
uint32_t m_csgWhiteList
List of CSG ID which this UE entity has access to.
uint16_t m_dlBandwidth
Downlink bandwidth in RBs.
uint32_t m_dlEarfcn
Downlink carrier frequency.
TracedCallback< uint64_t, uint16_t, uint16_t, uint8_t > m_drbCreatedTrace
The DrbCreated trace source.
std::map< uint8_t, Ptr< LteDataRadioBearerInfo > > m_drbMap
The DataRadioBearerMap attribute.
LtePdcpSapUser * m_drbPdcpSapUser
DRB PDCP SAP user.
std::map< uint8_t, std::list< PendingTrigger_t > > m_enteringTriggerQueue
List of triggers that were raised because entering condition have been true, but are still delayed from reporting it by time-to-trigger.
TracedCallback< uint64_t, uint16_t, uint16_t > m_handoverEndErrorTrace
The HandoverEndError trace source.
TracedCallback< uint64_t, uint16_t, uint16_t > m_handoverEndOkTrace
The HandoverEndOk trace source.
TracedCallback< uint64_t, uint16_t, uint16_t, uint16_t > m_handoverStartTrace
The HandoverStart trace source.
bool m_hasReceivedMib
True if MIB was received for the current cell.
bool m_hasReceivedSib1
True if SIB1 was received for the current cell.
bool m_hasReceivedSib2
True if SIB2 was received for the current cell.
uint64_t m_imsi
The unique UE identifier.
TracedCallback< uint64_t, uint16_t > m_initialCellSelectionEndErrorTrace
The InitialCellSelectionEndError trace source.
TracedCallback< uint64_t, uint16_t > m_initialCellSelectionEndOkTrace
The InitialCellSelectionEndOk trace source.
uint8_t m_lastRrcTransactionIdentifier
last RRC transaction identifier
LteRrcSap::SystemInformationBlockType1 m_lastSib1
Stored content of the last SIB1 received.
bool m_leaveConnectedMode
true if UE NAS ask UE RRC to leave connected mode, e.g., after RLF, i.e. T310 has expired
std::map< uint8_t, std::list< PendingTrigger_t > > m_leavingTriggerQueue
List of triggers that were raised because leaving condition have been true, but are still delayed from stopping the reporting by time-to-trigger.
LteMacSapProvider * m_macSapProvider
MAC SAP provider.
TracedCallback< uint64_t, uint16_t, uint16_t, uint16_t > m_mibReceivedTrace
The MibReceived trace source.
uint8_t m_n310
The 'N310' attribute.
uint8_t m_n311
The 'N311' attribute.
uint8_t m_noOfSyncIndications
number of in-sync or out-of-sync indications coming from PHY layer
LteRrcSap::PdschConfigDedicated m_pdschConfigDedicated
the PDSCH condig dedicated
TracedCallback< uint64_t, uint16_t, uint16_t, std::string, uint8_t > m_phySyncDetectionTrace
The 'PhySyncDetection' trace source.
uint16_t m_previousCellId
the cell id of the previous cell UE was attached to
EventId m_radioLinkFailureDetected
Time limit (given by m_t310) before the radio link is considered to have failed.
TracedCallback< uint64_t, uint16_t, uint16_t > m_radioLinkFailureTrace
The 'RadioLinkFailure' trace source.
TracedCallback< uint64_t, uint16_t, uint16_t > m_randomAccessErrorTrace
The RandomAccessError trace source.
TracedCallback< uint64_t, uint16_t, uint16_t > m_randomAccessSuccessfulTrace
The RandomAccessSuccessful trace source.
uint16_t m_rnti
The C-RNTI attribute.
LteUeRrcSapProvider * m_rrcSapProvider
RRC SAP provider.
LteUeRrcSapUser * m_rrcSapUser
RRC SAP user.
TracedCallback< Ptr< LteUeRrc >, std::list< LteRrcSap::SCellToAddMod > > m_sCarrierConfiguredTrace
The SCarrierConfigured trace source.
std::list< LteRrcSap::SCellToAddMod > m_sCellToAddModList
Secondary carriers.
TracedCallback< uint64_t, uint16_t, uint16_t, uint16_t > m_sib1ReceivedTrace
The Sib1Received trace source.
TracedCallback< uint64_t, uint16_t, uint16_t > m_sib2ReceivedTrace
The Sib2Received trace source.
Ptr< LteSignalingRadioBearerInfo > m_srb0
The Srb0 attribute.
Ptr< LteSignalingRadioBearerInfo > m_srb1
The Srb1 attribute.
TracedCallback< uint64_t, uint16_t, uint16_t > m_srb1CreatedTrace
The Srb1Created trace source.
Ptr< LteSignalingRadioBearerInfo > m_srb1Old
SRB1 configuration before RRC connection reconfiguration.
State m_state
The current UE RRC state.
TracedCallback< uint64_t, uint16_t, uint16_t, State, State > m_stateTransitionTrace
The StateTransition trace source.
std::map< uint16_t, MeasValues > m_storedMeasValues
Internal storage of the latest measurement results from all detected detected cells, indexed by the cell ID where the measurement was taken from.
std::map< uint16_t, std::map< uint8_t, MeasValues > > m_storedMeasValuesPerCarrier
Stored measure values per carrier.
std::map< uint16_t, MeasValues > m_storedScellMeasValues
Internal storage of the latest measurement results from all detected detected Secondary carrier component, indexed by the carrier component ID where the measurement was taken from.
Time m_t300
The T300 attribute.
Time m_t310
The 'T310' attribute.
uint16_t m_ulBandwidth
Uplink bandwidth in RBs.
uint32_t m_ulEarfcn
Uplink carrier frequency.
bool m_useRlcSm
True if RLC SM is to be used, false if RLC UM/AM are to be used.
VarMeasConfig m_varMeasConfig
Includes the accumulated configuration of the measurements to be performed by the UE.
std::map< uint8_t, VarMeasReport > m_varMeasReportList
The list of active reporting entries, indexed by the measurement identity which triggered the reporting.
Friends
class LtePdcpSpecificLtePdcpSapUser< LteUeRrc >
allow LtePdcpSpecificLtePdcpSapUser<LteUeRrc> class friend access
class MemberLteAsSapProvider< LteUeRrc >
allow MemberLteAsSapProvider<LteUeRrc> class friend access
class MemberLteUeCcmRrcSapUser< LteUeRrc >
allow MemberLteUeCcmRrcSapUser<LteUeRrc> class friend access
class MemberLteUeCphySapUser< LteUeRrc >
allow MemberLteUeCphySapUser<LteUeRrc> class friend access
class MemberLteUeRrcSapProvider< LteUeRrc >
allow MemberLteUeRrcSapProvider<LteUeRrc> class friend access
class UeMemberLteUeCmacSapUser
allow UeMemberLteUeCmacSapUser class friend access
class UeRrcMemberLteEnbCmacSapUser
allow UeRrcMemberLteEnbCmacSapUser class friend access
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Config Paths
ns3::LteUeRrc is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteUeNetDevice/LteUeRrc"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteUeNetDevice/LteUeRrc"
Attributes
DataRadioBearerMap: List of UE RadioBearerInfo for Data Radio Bearers by LCID.
Set with class: ns3::ObjectPtrContainerValue
Underlying type: ns3::Ptr< ns3::LteDataRadioBearerInfo>
Flags: read
Srb0: SignalingRadioBearerInfo for SRB0
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::LteSignalingRadioBearerInfo>
Initial value: 0x0
Flags: construct write read
Srb1: SignalingRadioBearerInfo for SRB1
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::LteSignalingRadioBearerInfo>
Initial value: 0x0
Flags: construct write read
CellId: Serving cell identifier
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Flags: read
C-RNTI: Cell Radio Network Temporary Identifier
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Flags: read
T300: Timer for the RRC Connection Establishment procedure (i.e., the procedure is deemed as failed if it takes longer than this). Standard values: 100ms, 200ms, 300ms, 400ms, 600ms, 1000ms, 1500ms, 2000ms
Set with class: ns3::TimeValue
Underlying type: Time +1e+08ns:+2e+09ns
Initial value: +1e+08ns
Flags: construct write read
T310: Timer for detecting the Radio link failure (i.e., the radio link is deemed as failed if this timer expires). Standard values: 0ms 50ms, 100ms, 200ms, 500ms, 1000ms, 2000ms
Set with class: ns3::TimeValue
Underlying type: Time +0ns:+2e+09ns
Initial value: +1e+09ns
Flags: construct write read
N310: This specifies the maximum number of out-of-sync indications. Standard values: 1, 2, 3, 4, 6, 8, 10, 20
Set with class: ns3::UintegerValue
Underlying type: uint8_t 1:20
Initial value: 6
Flags: construct write read
N311: This specifies the maximum number of in-sync indications. Standard values: 1, 2, 3, 4, 5, 6, 8, 10
Set with class: ns3::UintegerValue
Underlying type: uint8_t 1:10
Initial value: 2
Flags: construct write read
TraceSources
MibReceived: trace fired upon reception of Master Information Block
Callback signature: ns3::LteUeRrc::MibSibHandoverTracedCallback
Sib1Received: trace fired upon reception of System Information Block Type 1
Callback signature: ns3::LteUeRrc::MibSibHandoverTracedCallback
Sib2Received: trace fired upon reception of System Information Block Type 2
Callback signature: ns3::LteUeRrc::ImsiCidRntiTracedCallback
StateTransition: trace fired upon every UE RRC state transition
Callback signature: ns3::LteUeRrc::StateTracedCallback
InitialCellSelectionEndOk: trace fired upon successful initial cell selection procedure
Callback signature: ns3::LteUeRrc::CellSelectionTracedCallback
InitialCellSelectionEndError: trace fired upon failed initial cell selection procedure
Callback signature: ns3::LteUeRrc::CellSelectionTracedCallback
RandomAccessSuccessful: trace fired upon successful completion of the random access procedure
Callback signature: ns3::LteUeRrc::ImsiCidRntiTracedCallback
RandomAccessError: trace fired upon failure of the random access procedure
Callback signature: ns3::LteUeRrc::ImsiCidRntiTracedCallback
ConnectionEstablished: trace fired upon successful RRC connection establishment
Callback signature: ns3::LteUeRrc::ImsiCidRntiTracedCallback
ConnectionTimeout: trace fired upon timeout RRC connection establishment because of T300
Callback signature: ns3::LteUeRrc::ImsiCidRntiCountTracedCallback
ConnectionReconfiguration: trace fired upon RRC connection reconfiguration
Callback signature: ns3::LteUeRrc::ImsiCidRntiTracedCallback
HandoverStart: trace fired upon start of a handover procedure
Callback signature: ns3::LteUeRrc::MibSibHandoverTracedCallback
HandoverEndOk: trace fired upon successful termination of a handover procedure
Callback signature: ns3::LteUeRrc::ImsiCidRntiTracedCallback
HandoverEndError: trace fired upon failure of a handover procedure
Callback signature: ns3::LteUeRrc::ImsiCidRntiTracedCallback
SCarrierConfigured: trace fired after configuring secondary carriers
Callback signature: ns3::LteUeRrc::SCarrierConfiguredTracedCallback
Srb1Created: trace fired after SRB1 is created
Callback signature: ns3::LteUeRrc::ImsiCidRntiTracedCallback
DrbCreated: trace fired after DRB is created
Callback signature: ns3::LteUeRrc::ImsiCidRntiLcIdTracedCallback
RadioLinkFailure: trace fired upon failure of radio link
Callback signature: ns3::LteUeRrc::ImsiCidRntiTracedCallback
PhySyncDetection: trace fired upon receiving in Sync or out of Sync indications from UE PHY
Callback signature: ns3::LteUeRrc::PhySyncDetectionTracedCallback
Size of this type is 1160 bytes (on a 64-bit architecture).
Definition at line 81 of file lte-ue-rrc.h.
Member Typedef Documentation
CellSelectionTracedCallback
typedef void(* ns3::LteUeRrc::CellSelectionTracedCallback) (uint64_t imsi, uint16_t cellId)
TracedCallback signature for imsi, cellId and rnti events.
Parameters
[in] imsi
[in] cellId
Definition at line 333 of file lte-ue-rrc.h.
ConcernedCells_t
typedef std::list<uint16_t> ns3::LteUeRrc::ConcernedCells_t private
List of cell IDs which are responsible for a certain trigger.
Definition at line 1006 of file lte-ue-rrc.h.
ImsiCidRntiCountTracedCallback
typedef void(* ns3::LteUeRrc::ImsiCidRntiCountTracedCallback) (uint64_t imsi, uint16_t cellId, uint16_t rnti, uint8_t count)
TracedCallback signature for imsi, cellId, rnti and counter for random access events.
Parameters
[in] imsi
[in] cellId
[in] rnti
[in] count
Definition at line 402 of file lte-ue-rrc.h.
ImsiCidRntiTracedCallback
typedef void(* ns3::LteUeRrc::ImsiCidRntiTracedCallback) (uint64_t imsi, uint16_t cellId, uint16_t rnti)
TracedCallback signature for imsi, cellId and rnti events.
Parameters
[in] imsi
[in] cellId
[in] rnti
Definition at line 343 of file lte-ue-rrc.h.
MibSibHandoverTracedCallback
typedef void(* ns3::LteUeRrc::MibSibHandoverTracedCallback) (uint64_t imsi, uint16_t cellId, uint16_t rnti, uint16_t otherCid)
TracedCallback signature for MIBRecieved, Sib1Received and HandoverStart events.
Parameters
[in] imsi
[in] cellId
[in] rnti
[in] otherCid
Definition at line 355 of file lte-ue-rrc.h.
PhySyncDetectionTracedCallback
typedef void(* ns3::LteUeRrc::PhySyncDetectionTracedCallback) (uint64_t imsi, uint16_t rnti, uint16_t cellId, std::string type, uint16_t count)
TracedCallback signature for in-sync and out-of-sync detection events.
Parameters
[in] imsi
[in] rnti
[in] cellId
[in] type
[in] count
Definition at line 390 of file lte-ue-rrc.h.
SCarrierConfiguredTracedCallback
typedef void(* ns3::LteUeRrc::SCarrierConfiguredTracedCallback) (Ptr< LteUeRrc >, std::list< LteRrcSap::SCellToAddMod >)
TracedCallback signature for secondary carrier configuration events.
Parameters
[in] Pointer to UE RRC
[in] List of LteRrcSap::SCellToAddMod
Definition at line 377 of file lte-ue-rrc.h.
StateTracedCallback
typedef void(* ns3::LteUeRrc::StateTracedCallback) (uint64_t imsi, uint16_t cellId, uint16_t rnti, State oldState, State newState)
TracedCallback signature for state transition events.
Parameters
[in] imsi
[in] cellId
[in] rnti
[in] oldState
[in] newState
Definition at line 367 of file lte-ue-rrc.h.
Member Enumeration Documentation
State
enum ns3::LteUeRrc::State
The states of the UE RRC entity.
Enumerator
IDLE_START
IDLE_CELL_SEARCH
IDLE_WAIT_MIB_SIB1
IDLE_WAIT_MIB
IDLE_WAIT_SIB1
IDLE_CAMPED_NORMALLY
IDLE_WAIT_SIB2
IDLE_RANDOM_ACCESS
IDLE_CONNECTING
CONNECTED_NORMALLY
CONNECTED_HANDOVER
CONNECTED_PHY_PROBLEM
CONNECTED_REESTABLISHING
NUM_STATES
Definition at line 105 of file lte-ue-rrc.h.
Constructor & Destructor Documentation
LteUeRrc()
ns3::LteUeRrc::LteUeRrc ()
create an RRC instance for use within an ue
Definition at line 134 of file lte-ue-rrc.cc.
References LtePdcpSpecificLtePdcpSapUser< LteUeRrc >, m_asSapProvider, m_ccmRrcSapUser, m_cmacSapProvider, m_cmacSapUser, m_cphySapProvider, m_cphySapUser, m_drbPdcpSapUser, m_rrcSapProvider, MemberLteAsSapProvider< LteUeRrc >, MemberLteUeCcmRrcSapUser< LteUeRrc >, MemberLteUeRrcSapProvider< LteUeRrc >, and NS_LOG_FUNCTION.
~LteUeRrc()
ns3::LteUeRrc::~LteUeRrc () virtual
Destructor.
Definition at line 168 of file lte-ue-rrc.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
ApplyMeasConfig()
void ns3::LteUeRrc::ApplyMeasConfig (LteRrcSap::MeasConfig mc) private
Update the current measurement configuration m_varMeasConfig.
Parameters
mc measurements to be performed by the UE
Implements Section 5.5.2 "Measurement configuration" of 3GPP TS 36.331. The supported subfunctions are:
Measurement object removal
Measurement object addition/ modification
Reporting configuration removal
Reporting configuration addition/ modification
Quantity configuration
Measurement identity removal
Measurement identity addition/ modification
The subfunctions that will be invoked are determined by the content of the given measurement configuration.
Note the existence of some chain reaction behaviours:
Removal of measurement object or reporting configuration also removes any impacted measurement identities.
Removal of measurement identity also removes any associated reporting entry from m_varMeasReportList.
Modification to measurement object or reporting configuration also removes any reporting entries of the impacted measurement identities from m_varMeasReportList.
Modification to quantity configuration also removes all existing reporting entries from m_varMeasReportList, regardless of measurement identity.
Some unsupported features:
List of neighbouring cells
List of black cells
CGI reporting
Periodical reporting configuration
Measurement gaps
s-Measure
Speed-dependent scaling
Warning
There is a possibility that the input argument (of type LteRrcSap::MeasConfig) may contain information in fields related to the unsupported features. In such case, the function will raise an error.
The measurement configuration given as an argument is typically provided by the serving eNodeB. It is transmitted through the RRC protocol when the UE joins the cell, e.g., by connection establishment or by incoming handover. The information inside the argument can be configured from the eNodeB side, which would then equally apply to all other UEs attached to the same eNodeB. See the LTE module's User Documentation for more information on configuring this.
See also
LteRrcSap::MeasConfig, LteUeRrc::m_varMeasReportList
Definition at line 1587 of file lte-ue-rrc.cc.
References ns3::LteUeRrc::VarMeasConfig::aRsrp, ns3::LteUeRrc::VarMeasConfig::aRsrq, ns3::LteRrcSap::ReportConfigEutra::EVENT, ns3::LteRrcSap::QuantityConfig::filterCoefficientRSRP, ns3::LteRrcSap::QuantityConfig::filterCoefficientRSRQ, ns3::LteRrcSap::MeasConfig::haveMeasGapConfig, ns3::LteRrcSap::MeasConfig::haveQuantityConfig, ns3::LteRrcSap::MeasConfig::haveSmeasure, ns3::LteRrcSap::MeasConfig::haveSpeedStatePars, m_cphySapProvider, m_enteringTriggerQueue, m_leavingTriggerQueue, m_numberOfComponentCarriers, m_varMeasConfig, m_varMeasReportList, ns3::LteUeRrc::VarMeasConfig::measIdList, ns3::LteRrcSap::MeasConfig::measIdToAddModList, ns3::LteRrcSap::MeasConfig::measIdToRemoveList, ns3::LteUeRrc::VarMeasConfig::measObjectList, ns3::LteRrcSap::MeasConfig::measObjectToAddModList, ns3::LteRrcSap::MeasConfig::measObjectToRemoveList, NS_ASSERT, NS_ASSERT_MSG, NS_FATAL_ERROR, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::LteRrcSap::ReportConfigEutra::PERIODICAL, ns3::LteRrcSap::MeasConfig::quantityConfig, ns3::LteUeRrc::VarMeasConfig::quantityConfig, ns3::LteUeRrc::VarMeasConfig::reportConfigList, ns3::LteRrcSap::MeasConfig::reportConfigToAddModList, ns3::LteRrcSap::MeasConfig::reportConfigToRemoveList, and VarMeasReportListClear().
Referenced by DoRecvRrcConnectionReconfiguration().
ApplyRadioResourceConfigDedicated()
void ns3::LteUeRrc::ApplyRadioResourceConfigDedicated (LteRrcSap::RadioResourceConfigDedicated rrcd) private
Apply radio resource config dedicated.
Parameters
rrcd LteRrcSap::RadioResourceConfigDedicated
Todo:
currently not implemented. Would need to modify drbInfo, and then propagate changes to the MAC
Definition at line 1382 of file lte-ue-rrc.cc.
References ns3::LteUeCcmRrcSapProvider::AddLc(), ns3::LteRrcSap::RlcConfig::AM, ns3::LteRrcSap::PhysicalConfigDedicated::antennaInfo, ns3::LteUeCmacSapProvider::LogicalChannelConfig::bucketSizeDurationMs, ns3::LteUeCcmRrcSapProvider::ConfigureSignalBearer(), CONNECTED_HANDOVER, ns3::LteRrcSap::ConvertPdschConfigDedicated2Double(), ns3::ObjectFactory::Create(), ns3::LteRrcSap::RadioResourceConfigDedicated::drbToAddModList, ns3::LteRrcSap::RadioResourceConfigDedicated::drbToReleaseList, ns3::LteRlc::GetLteMacSapUser(), ns3::LteRlc::GetLteRlcSapProvider(), ns3::Object::GetObject(), ns3::LteRlcAm::GetTypeId(), ns3::LteRlcUm::GetTypeId(), ns3::LteRlcSm::GetTypeId(), ns3::LteRrcSap::PhysicalConfigDedicated::haveAntennaInfoDedicated, ns3::LteRrcSap::PhysicalConfigDedicated::havePdschConfigDedicated, ns3::LteRrcSap::PhysicalConfigDedicated::haveSoundingRsUlConfigDedicated, IDLE_CONNECTING, ns3::Object::Initialize(), ns3::LteUeCmacSapProvider::LogicalChannelConfig::logicalChannelGroup, m_bid2DrbidMap, m_ccmRrcSapProvider, m_cellId, m_cmacSapProvider, m_cphySapProvider, m_drbCreatedTrace, m_drbMap, m_drbPdcpSapUser, m_imsi, m_macSapProvider, m_numberOfComponentCarriers, m_pdschConfigDedicated, m_rnti, m_rrcSapUser, m_srb0, m_srb1, m_srb1CreatedTrace, m_state, m_useRlcSm, NS_ASSERT_MSG, NS_FATAL_ERROR, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::LteRrcSap::PhysicalConfigDedicated::pdschConfigDedicated, ns3::LteRrcSap::RadioResourceConfigDedicated::physicalConfigDedicated, ns3::LteUeCmacSapProvider::LogicalChannelConfig::prioritizedBitRateKbps, ns3::LteUeCmacSapProvider::LogicalChannelConfig::priority, ns3::LteRlc::SetLcId(), ns3::LteRlc::SetLteMacSapProvider(), ns3::LteRlc::SetLteRlcSapUser(), ns3::LteRlc::SetRnti(), ns3::ObjectFactory::SetTypeId(), ns3::LteUeRrcSapUser::Setup(), ns3::LteRrcSap::PhysicalConfigDedicated::soundingRsUlConfigDedicated, ns3::LteUeRrcSapUser::SetupParameters::srb0SapProvider, ns3::LteUeRrcSapUser::SetupParameters::srb1SapProvider, ns3::LteRrcSap::RadioResourceConfigDedicated::srbToAddModList, ns3::LteRrcSap::SoundingRsUlConfigDedicated::srsConfigIndex, ns3::ToString(), ns3::LteRrcSap::AntennaInfoDedicated::transmissionMode, and ns3::LteRrcSap::RlcConfig::UM_BI_DIRECTIONAL.
Referenced by DoRecvRrcConnectionReconfiguration(), and DoRecvRrcConnectionSetup().
ApplyRadioResourceConfigDedicatedSecondaryCarrier()
void ns3::LteUeRrc::ApplyRadioResourceConfigDedicatedSecondaryCarrier (LteRrcSap::NonCriticalExtensionConfiguration nonCec) private
Apply radio resource config dedicated secondary carrier.
Parameters
nonCec LteRrcSap::NonCriticalExtensionConfiguration
Definition at line 1344 of file lte-ue-rrc.cc.
References ns3::LteRrcSap::PhysicalConfigDedicatedSCell::antennaInfo, ns3::LteRrcSap::SCellToAddMod::cellIdentification, ns3::LteRrcSap::ConvertPdschConfigDedicated2Double(), ns3::LteRrcSap::NonUlConfiguration::dlBandwidth, ns3::LteRrcSap::CellIdentification::dlCarrierFreq, m_cmacSapProvider, m_cphySapProvider, m_rnti, m_sCarrierConfiguredTrace, m_sCellToAddModList, ns3::LteRrcSap::RadioResourceConfigCommonSCell::nonUlConfiguration, NS_LOG_FUNCTION, ns3::LteRrcSap::NonUlConfiguration::pdschConfigCommon, ns3::LteRrcSap::PhysicalConfigDedicatedSCell::pdschConfigDedicated, ns3::LteRrcSap::CellIdentification::physCellId, ns3::LteRrcSap::RadioResourceConfigDedicatedSCell::physicalConfigDedicatedSCell, ns3::LteRrcSap::SCellToAddMod::radioResourceConfigCommonSCell, ns3::LteRrcSap::SCellToAddMod::radioResourceConfigDedicateSCell, ns3::LteRrcSap::PdschConfigCommon::referenceSignalPower, ns3::LteRrcSap::SCellToAddMod::sCellIndex, ns3::LteRrcSap::NonCriticalExtensionConfiguration::sCellsToAddModList, ns3::LteRrcSap::PhysicalConfigDedicatedSCell::soundingRsUlConfigDedicated, ns3::LteRrcSap::SoundingRsUlConfigDedicated::srsConfigIndex, ns3::LteRrcSap::AntennaInfoDedicated::transmissionMode, ns3::LteRrcSap::FreqInfo::ulBandwidth, ns3::LteRrcSap::FreqInfo::ulCarrierFreq, ns3::LteRrcSap::RadioResourceConfigCommonSCell::ulConfiguration, and ns3::LteRrcSap::UlConfiguration::ulFreqInfo.
Referenced by DoRecvRrcConnectionReconfiguration().
Bid2Drbid()
uint8_t ns3::LteUeRrc::Bid2Drbid (uint8_t bid) private
Bid 2 DR bid.
Parameters
bid the BID
Returns
the DR bid
Definition at line 3156 of file lte-ue-rrc.cc.
References m_bid2DrbidMap.
Referenced by DoSendData().
CancelEnteringTrigger() [1/2]
void ns3::LteUeRrc::CancelEnteringTrigger (uint8_t measId) private
Clear all the waiting triggers in m_enteringTriggerQueue which are associated with the given measurement identity.
Parameters
measId the measurement identity to be processed, must already exists in m_enteringTriggerQueue, otherwise an error would be raised
Note
The function may conclude that there is nothing to be removed. In this case, the function will simply ignore quietly.
This function is used when the entering condition of the measurement identity becomes no longer true. Therefore all the waiting triggers for this measurement identity in m_enteringTriggerQueue have become invalid and must be canceled.
See also
LteUeRrc::m_enteringTriggerQueue
Definition at line 2608 of file lte-ue-rrc.cc.
References ns3::Simulator::Cancel(), ns3::Simulator::GetDelayLeft(), ns3::Time::GetSeconds(), m_enteringTriggerQueue, NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by MeasurementReportTriggering(), VarMeasReportListAdd(), and VarMeasReportListClear().
CancelEnteringTrigger() [2/2]
void ns3::LteUeRrc::CancelEnteringTrigger (uint8_t measId, uint16_t cellId) private
Remove a specific cell from the waiting triggers in m_enteringTriggerQueue which belong to the given measurement identity.
Parameters
measId the measurement identity to be processed, must already exists in m_enteringTriggerQueue, otherwise an error would be raised
cellId the cell ID to be removed from the waiting triggers
Note
The function may conclude that there is nothing to be removed. In this case, the function will simply ignore quietly.
This function is used when a specific neighbour cell no longer fulfills the entering condition of the measurement identity. Thus the cell must be removed from all the waiting triggers for this measurement identity in m_enteringTriggerQueue.
See also
LteUeRrc::m_enteringTriggerQueue
Definition at line 2632 of file lte-ue-rrc.cc.
References ns3::Simulator::Cancel(), ns3::Simulator::GetDelayLeft(), ns3::Time::GetSeconds(), m_enteringTriggerQueue, NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
CancelLeavingTrigger() [1/2]
void ns3::LteUeRrc::CancelLeavingTrigger (uint8_t measId) private
Clear all the waiting triggers in m_leavingTriggerQueue which are associated with the given measurement identity.
Parameters
measId the measurement identity to be processed, must already exists in m_leavingTriggerQueue, otherwise an error would be raised
Note
The function may conclude that there is nothing to be removed. In this case, the function will simply ignore quietly.
This function is used when the leaving condition of the measurement identity becomes no longer true. Therefore all the waiting triggers for this measurement identity in m_leavingTriggerQueue have become invalid and must be canceled.
See also
LteUeRrc::m_leavingTriggerQueue
Definition at line 2670 of file lte-ue-rrc.cc.
References ns3::Simulator::Cancel(), ns3::Simulator::GetDelayLeft(), ns3::Time::GetSeconds(), m_leavingTriggerQueue, NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by MeasurementReportTriggering(), VarMeasReportListClear(), and VarMeasReportListErase().
CancelLeavingTrigger() [2/2]
void ns3::LteUeRrc::CancelLeavingTrigger (uint8_t measId, uint16_t cellId) private
Remove a specific cell from the waiting triggers in m_leavingTriggerQueue which belong to the given measurement identity.
Parameters
measId the measurement identity to be processed, must already exists in m_leavingTriggerQueue, otherwise an error would be raised
cellId the cell ID to be removed from the waiting triggers
Note
The function may conclude that there is nothing to be removed. In this case, the function will simply ignore quietly.
This function is used when a specific neighbour cell no longer fulfills the leaving condition of the measurement identity. Thus the cell must be removed from all the waiting triggers for this measurement identity in m_leavingTriggerQueue.
See also
LteUeRrc::m_leavingTriggerQueue
Definition at line 2694 of file lte-ue-rrc.cc.
References ns3::Simulator::Cancel(), ns3::Simulator::GetDelayLeft(), ns3::Time::GetSeconds(), m_leavingTriggerQueue, NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
ConnectionTimeout()
void ns3::LteUeRrc::ConnectionTimeout () private
Invoked after timer T300 expires, notifying upper layers that RRC connection establishment procedure has failed.
Definition at line 3118 of file lte-ue-rrc.cc.
References CONNECTED_PHY_PROBLEM, IDLE_CAMPED_NORMALLY, m_asSapUser, m_cellId, m_cmacSapProvider, m_connectionTimeoutTrace, m_connEstFailCount, m_connEstFailCountLimit, m_hasReceivedSib2, m_imsi, m_numberOfComponentCarriers, m_rnti, ns3::LteAsSapUser::NotifyConnectionFailed(), ns3::LteAsSapUser::NotifyConnectionReleased(), NS_LOG_FUNCTION, and SwitchToState().
Referenced by DoNotifyRandomAccessSuccessful().
DisposeOldSrb1()
void ns3::LteUeRrc::DisposeOldSrb1 () private
Dispose old SRB1.
Definition at line 3149 of file lte-ue-rrc.cc.
References m_srb1Old, and NS_LOG_FUNCTION.
Referenced by DoRecvRrcConnectionReconfiguration().
DoCompleteSetup()
void ns3::LteUeRrc::DoCompleteSetup (LteUeRrcSapProvider::CompleteSetupParameters params) private
Part of the RRC protocol.
Implement the LteUeRrcSapProvider::CompleteSetup interface.
Parameters
params the LteUeRrcSapProvider::CompleteSetupParameters
Definition at line 964 of file lte-ue-rrc.cc.
References m_rnti, m_srb0, m_srb1, NS_LOG_FUNCTION, ns3::LteUeRrcSapProvider::CompleteSetupParameters::srb0SapUser, and ns3::LteUeRrcSapProvider::CompleteSetupParameters::srb1SapUser.
DoConnect()
void ns3::LteUeRrc::DoConnect (void) private
Connect function.
Definition at line 803 of file lte-ue-rrc.cc.
References CONNECTED_HANDOVER, CONNECTED_NORMALLY, CONNECTED_REESTABLISHING, IDLE_CAMPED_NORMALLY, IDLE_CELL_SEARCH, IDLE_CONNECTING, IDLE_RANDOM_ACCESS, IDLE_START, IDLE_WAIT_MIB, IDLE_WAIT_MIB_SIB1, IDLE_WAIT_SIB1, IDLE_WAIT_SIB2, m_connectionPending, m_imsi, m_state, NS_FATAL_ERROR, NS_LOG_FUNCTION, NS_LOG_INFO, SwitchToState(), and ns3::ToString().
Referenced by EvaluateCellForSelection().
DoDisconnect()
void ns3::LteUeRrc::DoDisconnect () private
Disconnect function.
Definition at line 607 of file lte-ue-rrc.cc.
References CONNECTED_HANDOVER, CONNECTED_NORMALLY, CONNECTED_PHY_PROBLEM, CONNECTED_REESTABLISHING, IDLE_CAMPED_NORMALLY, IDLE_CELL_SEARCH, IDLE_CONNECTING, IDLE_START, IDLE_WAIT_MIB, IDLE_WAIT_MIB_SIB1, IDLE_WAIT_SIB1, IDLE_WAIT_SIB2, LeaveConnectedMode(), m_state, NS_FATAL_ERROR, NS_LOG_FUNCTION, NS_LOG_INFO, and ns3::ToString().
DoDispose()
void ns3::LteUeRrc::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 174 of file lte-ue-rrc.cc.
References m_asSapProvider, m_ccmRrcSapUser, m_cmacSapProvider, m_cmacSapUser, m_cphySapProvider, m_cphySapUser, m_drbMap, m_drbPdcpSapUser, m_numberOfComponentCarriers, m_rrcSapProvider, and NS_LOG_FUNCTION.
DoForceCampedOnEnb()
void ns3::LteUeRrc::DoForceCampedOnEnb (uint16_t cellId, uint32_t dlEarfcn) private
Force camped on ENB function.
Parameters
cellId the cell ID
dlEarfcn the DL EARFCN
Definition at line 758 of file lte-ue-rrc.cc.
References CONNECTED_HANDOVER, CONNECTED_NORMALLY, CONNECTED_PHY_PROBLEM, CONNECTED_REESTABLISHING, IDLE_CAMPED_NORMALLY, IDLE_CELL_SEARCH, IDLE_CONNECTING, IDLE_RANDOM_ACCESS, IDLE_START, IDLE_WAIT_MIB, IDLE_WAIT_MIB_SIB1, IDLE_WAIT_SIB1, IDLE_WAIT_SIB2, m_cellId, m_cphySapProvider, m_dlEarfcn, m_imsi, m_state, NS_FATAL_ERROR, NS_LOG_FUNCTION, NS_LOG_INFO, SwitchToState(), and ns3::ToString().
DoInitialize()
void ns3::LteUeRrc::DoInitialize (void) private virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 526 of file lte-ue-rrc.cc.
References ns3::LteUeCmacSapProvider::LogicalChannelConfig::bucketSizeDurationMs, ns3::LteUeCcmRrcSapProvider::ConfigureSignalBearer(), ns3::LteRlc::GetLteMacSapUser(), ns3::Object::GetObject(), ns3::LteUeCmacSapProvider::LogicalChannelConfig::logicalChannelGroup, m_ccmRrcSapProvider, m_cmacSapProvider, m_macSapProvider, m_rnti, m_rrcSapUser, m_srb0, NS_LOG_FUNCTION, ns3::LteUeCmacSapProvider::LogicalChannelConfig::prioritizedBitRateKbps, ns3::LteUeCmacSapProvider::LogicalChannelConfig::priority, ns3::LteRlc::SetLcId(), ns3::LteRlc::SetLteMacSapProvider(), ns3::LteRlc::SetRnti(), ns3::LteUeRrcSapUser::Setup(), ns3::LteUeRrcSapUser::SetupParameters::srb0SapProvider, and ns3::LteUeRrcSapUser::SetupParameters::srb1SapProvider.
DoNotifyInSync()
void ns3::LteUeRrc::DoNotifyInSync () private
Do notify in sync function.
Triggered upon receiving an in sync indication from UE PHY. When the count equals N311, then T310 is cancelled.
Definition at line 3301 of file lte-ue-rrc.cc.
References m_cellId, m_imsi, m_n311, m_noOfSyncIndications, m_phySyncDetectionTrace, m_rnti, NS_LOG_FUNCTION, NS_LOG_INFO, and ResetRlfParams().
DoNotifyOutOfSync()
void ns3::LteUeRrc::DoNotifyOutOfSync () private
Do notify out of sync function.
Triggered upon receiving an out of sync indication from UE PHY. When the count equals N310, then T310 is started.
Definition at line 3314 of file lte-ue-rrc.cc.
References ns3::EventId::IsRunning(), m_cellId, m_cphySapProvider, m_imsi, m_n310, m_noOfSyncIndications, m_phySyncDetectionTrace, m_radioLinkFailureDetected, m_rnti, m_t310, NS_LOG_FUNCTION, NS_LOG_INFO, RadioLinkFailureDetected(), and ns3::Simulator::Schedule().
DoNotifyRandomAccessFailed()
void ns3::LteUeRrc::DoNotifyRandomAccessFailed () private
Notify random access failed function.
Todo:
After a handover failure because of a random access failure, send an RRC Connection Re-establishment and switch to CONNECTED_REESTABLISHING state.
Definition at line 707 of file lte-ue-rrc.cc.
References CONNECTED_HANDOVER, IDLE_CAMPED_NORMALLY, IDLE_RANDOM_ACCESS, m_asSapUser, m_cellId, m_handoverEndErrorTrace, m_imsi, m_randomAccessErrorTrace, m_rnti, m_state, ns3::LteAsSapUser::NotifyConnectionFailed(), NS_FATAL_ERROR, NS_LOG_FUNCTION, SwitchToState(), and ns3::ToString().
Referenced by ns3::UeMemberLteUeCmacSapUser::NotifyRandomAccessFailed().
DoNotifyRandomAccessSuccessful()
void ns3::LteUeRrc::DoNotifyRandomAccessSuccessful () private
Notify random access successful function.
Definition at line 658 of file lte-ue-rrc.cc.
References CONNECTED_HANDOVER, CONNECTED_NORMALLY, ConnectionTimeout(), IDLE_CONNECTING, IDLE_RANDOM_ACCESS, m_cellId, m_cmacSapProvider, m_connectionTimeout, m_handoverEndOkTrace, m_imsi, m_lastRrcTransactionIdentifier, m_randomAccessSuccessfulTrace, m_rnti, m_rrcSapUser, m_state, m_t300, m_varMeasConfig, ns3::LteUeRrc::VarMeasConfig::measIdList, NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::LteRrcSap::RrcConnectionReconfigurationCompleted::rrcTransactionIdentifier, ns3::Simulator::Schedule(), ns3::LteUeRrcSapUser::SendRrcConnectionReconfigurationCompleted(), ns3::LteUeRrcSapUser::SendRrcConnectionRequest(), SwitchToState(), ns3::ToString(), ns3::LteRrcSap::RrcConnectionRequest::ueIdentity, and VarMeasReportListClear().
Referenced by ns3::UeMemberLteUeCmacSapUser::NotifyRandomAccessSuccessful().
DoReceivePdcpSdu()
void ns3::LteUeRrc::DoReceivePdcpSdu (LtePdcpSapUser::ReceivePdcpSduParameters params) private
Receive PDCP SDU function.
Parameters
params LtePdcpSapUser::ReceivePdcpSduParameters
Definition at line 641 of file lte-ue-rrc.cc.
References m_asSapUser, NS_LOG_FUNCTION, ns3::LtePdcpSapUser::ReceivePdcpSduParameters::pdcpSdu, and ns3::LteAsSapUser::RecvData().
DoRecvMasterInformationBlock()
void ns3::LteUeRrc::DoRecvMasterInformationBlock (uint16_t cellId, LteRrcSap::MasterInformationBlock msg) private
Receive master information block function.
Parameters
cellId the cell ID
msg LteRrcSap::MasterInformationBlock
Definition at line 845 of file lte-ue-rrc.cc.
References ns3::LteRrcSap::MasterInformationBlock::dlBandwidth, IDLE_CAMPED_NORMALLY, IDLE_WAIT_MIB, IDLE_WAIT_MIB_SIB1, IDLE_WAIT_SIB1, m_cellId, m_cphySapProvider, m_dlBandwidth, m_hasReceivedMib, m_imsi, m_mibReceivedTrace, m_rnti, m_state, and SwitchToState().
DoRecvRrcConnectionReconfiguration()
void ns3::LteUeRrc::DoRecvRrcConnectionReconfiguration (LteRrcSap::RrcConnectionReconfiguration msg) private
Part of the RRC protocol.
Implement the LteUeRrcSapProvider::RecvRrcConnectionReconfiguration interface.
Parameters
msg the LteRrcSap::RrcConnectionReconfiguration
Definition at line 1055 of file lte-ue-rrc.cc.
References ApplyMeasConfig(), ApplyRadioResourceConfigDedicated(), ApplyRadioResourceConfigDedicatedSecondaryCarrier(), ns3::LteRrcSap::MobilityControlInfo::carrierBandwidth, ns3::LteRrcSap::MobilityControlInfo::carrierFreq, CONNECTED_HANDOVER, CONNECTED_NORMALLY, DisposeOldSrb1(), ns3::LteRrcSap::CarrierBandwidthEutra::dlBandwidth, ns3::LteRrcSap::CarrierFreqEutra::dlCarrierFreq, ns3::LteRrcSap::MobilityControlInfo::haveCarrierBandwidth, ns3::LteRrcSap::MobilityControlInfo::haveCarrierFreq, ns3::LteRrcSap::RrcConnectionReconfiguration::haveMeasConfig, ns3::LteRrcSap::RrcConnectionReconfiguration::haveMobilityControlInfo, ns3::LteRrcSap::RrcConnectionReconfiguration::haveNonCriticalExtension, ns3::LteRrcSap::MobilityControlInfo::haveRachConfigDedicated, ns3::LteRrcSap::RrcConnectionReconfiguration::haveRadioResourceConfigDedicated, m_ccmRrcSapProvider, m_cellId, m_cmacSapProvider, m_connectionReconfigurationTrace, m_cphySapProvider, m_drbMap, m_handoverStartTrace, m_imsi, m_lastRrcTransactionIdentifier, m_numberOfComponentCarriers, m_rnti, m_rrcSapUser, m_srb0, m_srb1, m_srb1Old, m_state, ns3::LteRrcSap::RrcConnectionReconfiguration::measConfig, ns3::LteRrcSap::RrcConnectionReconfiguration::mobilityControlInfo, ns3::LteRrcSap::MobilityControlInfo::newUeIdentity, ns3::LteRrcSap::RrcConnectionReconfiguration::nonCriticalExtension, NS_ASSERT, NS_ASSERT_MSG, NS_FATAL_ERROR, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::LteRrcSap::MobilityControlInfo::rachConfigDedicated, ns3::LteRrcSap::RrcConnectionReconfiguration::radioResourceConfigDedicated, ns3::LteRrcSap::RachConfigDedicated::raPrachMaskIndex, ns3::LteRrcSap::RachConfigDedicated::raPreambleIndex, ns3::LteUeCcmRrcSapProvider::Reset(), ns3::LteRrcSap::RrcConnectionReconfiguration::rrcTransactionIdentifier, ns3::LteRrcSap::RrcConnectionReconfigurationCompleted::rrcTransactionIdentifier, ns3::Simulator::ScheduleNow(), ns3::LteUeRrcSapUser::SendRrcConnectionReconfigurationCompleted(), StorePreviousCellId(), SwitchToState(), ns3::LteRrcSap::MobilityControlInfo::targetPhysCellId, ns3::ToString(), ns3::LteRrcSap::CarrierBandwidthEutra::ulBandwidth, and ns3::LteRrcSap::CarrierFreqEutra::ulCarrierFreq.
DoRecvRrcConnectionReestablishment()
void ns3::LteUeRrc::DoRecvRrcConnectionReestablishment (LteRrcSap::RrcConnectionReestablishment msg) private
Part of the RRC protocol.
Implement the LteUeRrcSapProvider::RecvRrcConnectionReestablishment interface.
Parameters
msg LteRrcSap::RrcConnectionReestablishment
Todo:
After receiving RRC Connection Re-establishment, stop timer T301, fire a new trace source, reply with RRC Connection Re-establishment Complete, and finally switch to CONNECTED_NORMALLY state. See Section 5.3.7.5 of 3GPP TS 36.331.
Definition at line 1143 of file lte-ue-rrc.cc.
References CONNECTED_REESTABLISHING, m_rnti, m_state, NS_FATAL_ERROR, NS_LOG_FUNCTION, and ns3::ToString().
DoRecvRrcConnectionReestablishmentReject()
void ns3::LteUeRrc::DoRecvRrcConnectionReestablishmentReject (LteRrcSap::RrcConnectionReestablishmentReject msg) private
Part of the RRC protocol.
Implement the LteUeRrcSapProvider::RecvRrcConnectionReestablishmentReject interface.
Parameters
msg LteRrcSap::RrcConnectionReestablishmentReject
Todo:
After receiving RRC Connection Re-establishment Reject, stop timer T301. See Section 5.3.7.8 of 3GPP TS 36.331.
Definition at line 1167 of file lte-ue-rrc.cc.
References CONNECTED_REESTABLISHING, m_asSapUser, m_rnti, m_state, ns3::LteAsSapUser::NotifyConnectionReleased(), NS_FATAL_ERROR, NS_LOG_FUNCTION, and ns3::ToString().
DoRecvRrcConnectionReject()
void ns3::LteUeRrc::DoRecvRrcConnectionReject (LteRrcSap::RrcConnectionReject msg) private
Part of the RRC protocol.
Implement the LteUeRrcSapProvider::RecvRrcConnectionReject interface.
Parameters
msg the LteRrcSap::RrcConnectionReject
Definition at line 1196 of file lte-ue-rrc.cc.
References ns3::EventId::Cancel(), IDLE_CAMPED_NORMALLY, m_asSapUser, m_cmacSapProvider, m_connectionTimeout, m_hasReceivedSib2, m_numberOfComponentCarriers, ns3::LteAsSapUser::NotifyConnectionFailed(), NS_LOG_FUNCTION, and SwitchToState().
DoRecvRrcConnectionRelease()
void ns3::LteUeRrc::DoRecvRrcConnectionRelease (LteRrcSap::RrcConnectionRelease msg) private
Part of the RRC protocol.
Implement the LteUeRrcSapProvider::RecvRrcConnectionRelease interface.
Parameters
msg LteRrcSap::RrcConnectionRelease
Todo:
Currently not implemented, see Section 5.3.8 of 3GPP TS 36.331.
Definition at line 1189 of file lte-ue-rrc.cc.
References m_rnti, and NS_LOG_FUNCTION.
DoRecvRrcConnectionSetup()
void ns3::LteUeRrc::DoRecvRrcConnectionSetup (LteRrcSap::RrcConnectionSetup msg) private
Part of the RRC protocol.
Implement the LteUeRrcSapProvider::RecvRrcConnectionSetup interface.
Parameters
msg the LteRrcSap::RrcConnectionSetup
Definition at line 1025 of file lte-ue-rrc.cc.
References ApplyRadioResourceConfigDedicated(), ns3::EventId::Cancel(), CONNECTED_NORMALLY, IDLE_CONNECTING, m_asSapUser, m_cellId, m_cmacSapProvider, m_connectionEstablishedTrace, m_connectionTimeout, m_connEstFailCount, m_imsi, m_leaveConnectedMode, m_noOfSyncIndications, m_rnti, m_rrcSapUser, m_state, ns3::LteAsSapUser::NotifyConnectionSuccessful(), NS_ABORT_MSG_IF, NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::LteRrcSap::RrcConnectionSetup::radioResourceConfigDedicated, ns3::LteRrcSap::RrcConnectionSetup::rrcTransactionIdentifier, ns3::LteRrcSap::RrcConnectionSetupCompleted::rrcTransactionIdentifier, ns3::LteUeRrcSapUser::SendRrcConnectionSetupCompleted(), SwitchToState(), and ns3::ToString().
DoRecvSystemInformation()
void ns3::LteUeRrc::DoRecvSystemInformation (LteRrcSap::SystemInformation msg) private
Part of the RRC protocol.
Implement the LteUeRrcSapProvider::RecvSystemInformation interface.
Parameters
msg the LteRrcSap::SystemInformation
Definition at line 976 of file lte-ue-rrc.cc.
References CONNECTED_HANDOVER, CONNECTED_NORMALLY, CONNECTED_PHY_PROBLEM, CONNECTED_REESTABLISHING, ns3::LteRrcSap::TxFailParam::connEstFailCount, ns3::LteUeCmacSapProvider::RachConfig::connEstFailCount, ns3::LteRrcSap::SystemInformationBlockType2::freqInfo, ns3::LteRrcSap::SystemInformation::haveSib2, IDLE_CAMPED_NORMALLY, IDLE_CONNECTING, IDLE_RANDOM_ACCESS, IDLE_WAIT_SIB2, m_cellId, m_cmacSapProvider, m_connectionPending, m_connEstFailCountLimit, m_cphySapProvider, m_hasReceivedSib2, m_imsi, m_rnti, m_sib2ReceivedTrace, m_state, m_ulBandwidth, m_ulEarfcn, NS_ASSERT, NS_ASSERT_MSG, NS_LOG_FUNCTION, ns3::LteRrcSap::PreambleInfo::numberOfRaPreambles, ns3::LteUeCmacSapProvider::RachConfig::numberOfRaPreambles, ns3::LteRrcSap::RadioResourceConfigCommonSib::pdschConfigCommon, ns3::LteRrcSap::RachConfigCommon::preambleInfo, ns3::LteRrcSap::RaSupervisionInfo::preambleTransMax, ns3::LteUeCmacSapProvider::RachConfig::preambleTransMax, ns3::LteRrcSap::RadioResourceConfigCommonSib::rachConfigCommon, ns3::LteRrcSap::SystemInformationBlockType2::radioResourceConfigCommon, ns3::LteRrcSap::RaSupervisionInfo::raResponseWindowSize, ns3::LteUeCmacSapProvider::RachConfig::raResponseWindowSize, ns3::LteRrcSap::RachConfigCommon::raSupervisionInfo, ns3::LteRrcSap::PdschConfigCommon::referenceSignalPower, ns3::LteRrcSap::SystemInformation::sib2, StartConnection(), ns3::LteRrcSap::RachConfigCommon::txFailParam, ns3::LteRrcSap::FreqInfo::ulBandwidth, and ns3::LteRrcSap::FreqInfo::ulCarrierFreq.
DoRecvSystemInformationBlockType1()
void ns3::LteUeRrc::DoRecvSystemInformationBlockType1 (uint16_t cellId, LteRrcSap::SystemInformationBlockType1 msg) private
Receive system information block type 1 function.
Parameters
cellId the cell ID
msg LteRrcSap::SystemInformationBlockType1
Definition at line 872 of file lte-ue-rrc.cc.
References ns3::LteRrcSap::SystemInformationBlockType1::cellAccessRelatedInfo, ns3::LteRrcSap::CellAccessRelatedInfo::cellIdentity, CONNECTED_HANDOVER, CONNECTED_NORMALLY, CONNECTED_PHY_PROBLEM, CONNECTED_REESTABLISHING, EvaluateCellForSelection(), IDLE_CAMPED_NORMALLY, IDLE_CONNECTING, IDLE_RANDOM_ACCESS, IDLE_WAIT_MIB_SIB1, IDLE_WAIT_SIB1, m_cellId, m_hasReceivedSib1, m_imsi, m_lastSib1, m_rnti, m_sib1ReceivedTrace, m_state, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
DoReportUeMeasurements()
void ns3::LteUeRrc::DoReportUeMeasurements (LteUeCphySapUser::UeMeasurementsParameters params) private
Report UE measurements function.
Parameters
params LteUeCphySapUser::UeMeasurementsParameters
Definition at line 912 of file lte-ue-rrc.cc.
References CONNECTED_NORMALLY, IDLE_CELL_SEARCH, ns3::LteUeCphySapUser::UeMeasurementsParameters::m_componentCarrierId, m_state, ns3::LteUeCphySapUser::UeMeasurementsParameters::m_ueMeasurementsList, m_varMeasConfig, ns3::LteUeRrc::VarMeasConfig::measIdList, MeasurementReportTriggering(), NS_LOG_FUNCTION, SaveScellUeMeasurements(), SaveUeMeasurements(), and SynchronizeToStrongestCell().
DoResetSyncIndicationCounter()
void ns3::LteUeRrc::DoResetSyncIndicationCounter () private
Do reset sync indication counter function.
Reset the sync indication counter if the Qin or Qout condition at PHY is not fulfilled for the number of consecutive frames.
Definition at line 3334 of file lte-ue-rrc.cc.
References m_imsi, m_noOfSyncIndications, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
DoSendData()
void ns3::LteUeRrc::DoSendData (Ptr< Packet > packet, uint8_t bid) private
Send data function.
Parameters
packet the packet
bid the BID
Definition at line 581 of file lte-ue-rrc.cc.
References Bid2Drbid(), ns3::Packet::GetSize(), ns3::LtePdcpSapProvider::TransmitPdcpSduParameters::lcid, m_drbMap, m_rnti, NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::LtePdcpSapProvider::TransmitPdcpSduParameters::pdcpSdu, and ns3::LtePdcpSapProvider::TransmitPdcpSduParameters::rnti.
DoSetCsgWhiteList()
void ns3::LteUeRrc::DoSetCsgWhiteList (uint32_t csgId) private
Set CSG white list function.
Parameters
csgId CSG ID
Definition at line 740 of file lte-ue-rrc.cc.
References m_csgWhiteList, m_imsi, and NS_LOG_FUNCTION.
DoSetNumberOfComponentCarriers()
void ns3::LteUeRrc::DoSetNumberOfComponentCarriers (uint16_t noOfComponentCarriers) private
RRC CCM SAP USER Method.
Parameters
noOfComponentCarriers the number of component carriers
Definition at line 1210 of file lte-ue-rrc.cc.
References m_numberOfComponentCarriers, and NS_LOG_FUNCTION.
DoSetTemporaryCellRnti()
void ns3::LteUeRrc::DoSetTemporaryCellRnti (uint16_t rnti) private
Set temporary cell rnti function.
Parameters
rnti RNTI
Definition at line 649 of file lte-ue-rrc.cc.
References m_cphySapProvider, m_rnti, m_srb0, and NS_LOG_FUNCTION.
Referenced by ns3::UeMemberLteUeCmacSapUser::SetTemporaryCellRnti().
DoStartCellSelection()
void ns3::LteUeRrc::DoStartCellSelection (uint32_t dlEarfcn) private
Start cell selection function.
Parameters
dlEarfcn the DL EARFCN
Definition at line 747 of file lte-ue-rrc.cc.
References IDLE_CELL_SEARCH, IDLE_START, m_cphySapProvider, m_dlEarfcn, m_imsi, m_state, NS_ASSERT_MSG, NS_LOG_FUNCTION, SwitchToState(), and ns3::ToString().
Referenced by LeaveConnectedMode().
EvaluateCellForSelection()
void ns3::LteUeRrc::EvaluateCellForSelection () private
Performs cell selection evaluation to the current serving cell.
Warning
This function is a part of the initial cell selection procedure, hence must be only executed during IDLE mode and specifically during the state when the UE just received the first SIB1 message from the serving cell.
This function assumes that the required information for the evaluation procedure have been readily gathered, such as measurement results, MIB, and SIB1. Please refer to the LTE module's Design Documentation for more details on the evaluation process.
If the cell passes the evaluation, the UE will immediately camp to it. Otherwise, the UE will pick another cell and restart the cell selection procedure.
Definition at line 1263 of file lte-ue-rrc.cc.
References ns3::LteRrcSap::SystemInformationBlockType1::cellAccessRelatedInfo, ns3::LteRrcSap::CellAccessRelatedInfo::cellIdentity, ns3::LteRrcSap::SystemInformationBlockType1::cellSelectionInfo, ns3::LteRrcSap::CellAccessRelatedInfo::csgIdentity, ns3::LteRrcSap::CellAccessRelatedInfo::csgIndication, DoConnect(), IDLE_CAMPED_NORMALLY, IDLE_CELL_SEARCH, IDLE_WAIT_SIB1, ns3::EutranMeasurementMapping::IeValue2ActualQRxLevMin(), m_acceptableCell, m_cellId, m_connectionPending, m_cphySapProvider, m_csgWhiteList, m_dlBandwidth, m_dlEarfcn, m_hasReceivedMib, m_hasReceivedSib1, m_imsi, m_initialCellSelectionEndErrorTrace, m_initialCellSelectionEndOkTrace, m_lastSib1, m_state, m_storedMeasValues, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::LteRrcSap::CellSelectionInfo::qRxLevMin, SwitchToState(), SynchronizeToStrongestCell(), and ns3::ToString().
Referenced by DoRecvSystemInformationBlockType1().
GetAsSapProvider()
LteAsSapProvider * ns3::LteUeRrc::GetAsSapProvider ()
Returns
the AS SAP provider exported by this RRC
Definition at line 429 of file lte-ue-rrc.cc.
References m_asSapProvider.
GetCellId()
uint16_t ns3::LteUeRrc::GetCellId () const
Returns
the CellId of the attached Enb
Definition at line 469 of file lte-ue-rrc.cc.
References m_cellId, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetDlBandwidth()
uint8_t ns3::LteUeRrc::GetDlBandwidth () const
Returns
the downlink bandwidth in RBs
Definition at line 484 of file lte-ue-rrc.cc.
References m_dlBandwidth, and NS_LOG_FUNCTION.
GetDlEarfcn()
uint32_t ns3::LteUeRrc::GetDlEarfcn () const
Returns
the downlink carrier frequency (EARFCN)
Definition at line 491 of file lte-ue-rrc.cc.
References m_dlEarfcn.
GetImsi()
uint64_t ns3::LteUeRrc::GetImsi (void) const
Returns
imsi the unique UE identifier
Definition at line 456 of file lte-ue-rrc.cc.
References m_imsi.
GetLteCcmRrcSapUser()
LteUeCcmRrcSapUser * ns3::LteUeRrc::GetLteCcmRrcSapUser ()
Get the Component Carrier Management SAP offered by this RRC.
Returns
s the Component Carrier Management SAP User interface offered to the carrier component selection algorithm by this RRC
Definition at line 416 of file lte-ue-rrc.cc.
References m_ccmRrcSapUser, and NS_LOG_FUNCTION.
GetLteUeCmacSapUser() [1/2]
LteUeCmacSapUser * ns3::LteUeRrc::GetLteUeCmacSapUser ()
This function is overloaded to maintain backward compatibility.
Returns
s the CMAC SAP User interface offered to the MAC by this RRC
Definition at line 374 of file lte-ue-rrc.cc.
References m_cmacSapUser, and NS_LOG_FUNCTION.
GetLteUeCmacSapUser() [2/2]
LteUeCmacSapUser * ns3::LteUeRrc::GetLteUeCmacSapUser (uint8_t index)
This function is overloaded to maintain backward compatibility.
Parameters
index the index
Returns
s the CMAC SAP User interface offered to the MAC by this RRC
Definition at line 381 of file lte-ue-rrc.cc.
References m_cmacSapUser, and NS_LOG_FUNCTION.
GetLteUeCphySapUser() [1/2]
LteUeCphySapUser * ns3::LteUeRrc::GetLteUeCphySapUser ()
Returns
s the CPHY SAP User interface offered to the PHY by this RRC
Definition at line 346 of file lte-ue-rrc.cc.
References m_cphySapUser, and NS_LOG_FUNCTION.
GetLteUeCphySapUser() [2/2]
LteUeCphySapUser * ns3::LteUeRrc::GetLteUeCphySapUser (uint8_t index)
Parameters
index the index
Returns
s the CPHY SAP User interface offered to the PHY by this RRC
Definition at line 353 of file lte-ue-rrc.cc.
References m_cphySapUser, and NS_LOG_FUNCTION.
GetLteUeRrcSapProvider()
LteUeRrcSapProvider * ns3::LteUeRrc::GetLteUeRrcSapProvider ()
Returns
s the RRC SAP Provider interface offered to the MAC by this RRC
Definition at line 395 of file lte-ue-rrc.cc.
References m_rrcSapProvider, and NS_LOG_FUNCTION.
GetPreviousCellId()
uint16_t ns3::LteUeRrc::GetPreviousCellId () const
Get the previous cell id.
Returns
The cell Id of the previous cell the UE was attached to.
Definition at line 511 of file lte-ue-rrc.cc.
References m_previousCellId, and NS_LOG_FUNCTION.
GetRnti()
uint16_t ns3::LteUeRrc::GetRnti (void) const
Returns
the C-RNTI of the user
Definition at line 462 of file lte-ue-rrc.cc.
References m_rnti, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetState()
LteUeRrc::State ns3::LteUeRrc::GetState (void) const
Returns
the current state
Definition at line 504 of file lte-ue-rrc.cc.
References m_state, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::LteUeRrc::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 196 of file lte-ue-rrc.cc.
References GetCellId(), GetRnti(), m_connectionEstablishedTrace, m_connectionReconfigurationTrace, m_connectionTimeoutTrace, m_drbCreatedTrace, m_drbMap, m_handoverEndErrorTrace, m_handoverEndOkTrace, m_handoverStartTrace, m_initialCellSelectionEndErrorTrace, m_initialCellSelectionEndOkTrace, m_mibReceivedTrace, m_n310, m_n311, m_phySyncDetectionTrace, m_radioLinkFailureTrace, m_randomAccessErrorTrace, m_randomAccessSuccessfulTrace, m_sCarrierConfiguredTrace, m_sib1ReceivedTrace, m_sib2ReceivedTrace, m_srb0, m_srb1, m_srb1CreatedTrace, m_stateTransitionTrace, m_t300, m_t310, ns3::MakeObjectMapAccessor(), ns3::MakePointerAccessor(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), ns3::MilliSeconds(), and ns3::TypeId::SetParent().
GetUlBandwidth()
uint8_t ns3::LteUeRrc::GetUlBandwidth () const
Returns
the uplink bandwidth in RBs
Definition at line 477 of file lte-ue-rrc.cc.
References m_ulBandwidth, and NS_LOG_FUNCTION.
GetUlEarfcn()
uint32_t ns3::LteUeRrc::GetUlEarfcn () const
Returns
the uplink carrier frequency (EARFCN)
Definition at line 497 of file lte-ue-rrc.cc.
References m_ulEarfcn, and NS_LOG_FUNCTION.
InitializeSap()
void ns3::LteUeRrc::InitializeSap (void)
Initiaize SAP.
Definition at line 557 of file lte-ue-rrc.cc.
References m_cmacSapProvider, m_cmacSapUser, m_cphySapProvider, m_cphySapUser, m_numberOfComponentCarriers, MAX_NO_CC, and MIN_NO_CC.
LeaveConnectedMode()
void ns3::LteUeRrc::LeaveConnectedMode () private
Leave connected mode method Resets the UE back to an appropiate state depending on the nature of cause.
For example, the UE is move to the IDLE_START state upon radio link failure. At RRC, all radio bearers except SRB 0 are removed, measurement reports are cleared and the appropriate flags are reset to their default values. This method in turn triggers the reset methods of UE PHY and MAC layers.
Definition at line 3075 of file lte-ue-rrc.cc.
References DoStartCellSelection(), IDLE_START, m_bid2DrbidMap, m_ccmRrcSapProvider, m_cellId, m_cmacSapProvider, m_cphySapProvider, m_dlEarfcn, m_drbMap, m_hasReceivedMib, m_hasReceivedSib1, m_hasReceivedSib2, m_imsi, m_leaveConnectedMode, m_numberOfComponentCarriers, m_rnti, m_srb0, m_srb1, m_storedMeasValues, m_varMeasConfig, ns3::LteUeRrc::VarMeasConfig::measIdList, NS_LOG_FUNCTION, ns3::LteUeCcmRrcSapProvider::Reset(), ResetRlfParams(), StorePreviousCellId(), SwitchToState(), and VarMeasReportListClear().
Referenced by DoDisconnect().
MeasurementReportTriggering()
void ns3::LteUeRrc::MeasurementReportTriggering (uint8_t measId) private
Evaluate the reporting criteria of a measurement identity and invoke some reporting actions based on the result.
Parameters
measId the measurement identity to be evaluated
Implements Section 5.5.4.1 "Measurement report triggering - General" of 3GPP TS 36.331. This function take into use the latest measurement results and evaluate them against the entering condition and the leaving condition of the measurement identity's reporting criteria. The evaluation also take into account other defined criteria, such as hysteresis and time-to-trigger.
The entering and leaving condition to be evaluated are determined by the event type of the measurement identity's reporting criteria. As defined in LteRrcSap::ReportConfigEutra, there 5 supported events. The gore details of these events can be found in Section 5.5.4 of 3GPP TS 36.331.
An applicable entering condition (i.e., the condition evaluates to true) will insert a new reporting entry to m_varMeasReportList, so measurement reports would be produced and submitted to eNodeB. On the other hand, an applicable leaving condition will remove the related reporting entry from m_varMeasReportList, so submission of related measurement reports to eNodeB will be suspended.
Definition at line 1863 of file lte-ue-rrc.cc.
References ns3::LteRrcSap::ReportConfigEutra::a3Offset, CancelEnteringTrigger(), CancelLeavingTrigger(), ns3::LteRrcSap::ThresholdEutra::choice, ns3::LteUeRrc::PendingTrigger_t::concernedCells, ns3::LteRrcSap::ReportConfigEutra::EVENT, ns3::LteRrcSap::ReportConfigEutra::EVENT_A1, ns3::LteRrcSap::ReportConfigEutra::EVENT_A2, ns3::LteRrcSap::ReportConfigEutra::EVENT_A3, ns3::LteRrcSap::ReportConfigEutra::EVENT_A4, ns3::LteRrcSap::ReportConfigEutra::EVENT_A5, ns3::LteRrcSap::ReportConfigEutra::eventId, ns3::LteRrcSap::ReportConfigEutra::hysteresis, ns3::EutranMeasurementMapping::IeValue2ActualA3Offset(), ns3::EutranMeasurementMapping::IeValue2ActualHysteresis(), m_cellId, m_enteringTriggerQueue, m_leavingTriggerQueue, m_storedMeasValues, m_varMeasConfig, m_varMeasReportList, ns3::LteUeRrc::PendingTrigger_t::measId, ns3::LteUeRrc::VarMeasConfig::measIdList, ns3::LteUeRrc::VarMeasConfig::measObjectList, ns3::MilliSeconds(), NS_ASSERT, NS_ASSERT_MSG, NS_FATAL_ERROR, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::LteRrcSap::MeasObjectEutra::offsetFreq, ns3::LteRrcSap::ThresholdEutra::range, ns3::LteUeRrc::VarMeasConfig::reportConfigList, ns3::LteRrcSap::ReportConfigEutra::reportOnLeave, ns3::LteRrcSap::ReportConfigEutra::RSRP, ns3::EutranMeasurementMapping::RsrpRange2Dbm(), ns3::LteRrcSap::ReportConfigEutra::RSRQ, ns3::EutranMeasurementMapping::RsrqRange2Db(), ns3::Simulator::Schedule(), ns3::LteRrcSap::ReportConfigEutra::threshold1, ns3::LteRrcSap::ReportConfigEutra::threshold2, ns3::LteRrcSap::ThresholdEutra::THRESHOLD_RSRP, ns3::LteRrcSap::ThresholdEutra::THRESHOLD_RSRQ, ns3::LteUeRrc::PendingTrigger_t::timer, ns3::LteRrcSap::ReportConfigEutra::timeToTrigger, ns3::LteRrcSap::ReportConfigEutra::triggerQuantity, ns3::LteRrcSap::ReportConfigEutra::triggerType, VarMeasReportListAdd(), and VarMeasReportListErase().
Referenced by DoReportUeMeasurements().
RadioLinkFailureDetected()
void ns3::LteUeRrc::RadioLinkFailureDetected () private
Radio link failure detected function.
Upon detection of radio link failure, the UE is reverted back to idle state and the UE context at eNodeB and EPC is deleted, thus releasing the RRC connection. The eNodeB is notified in an ideal way since there is no radio link failure detection implemented at the eNodeB. If the deletion process is not synchronous, then errors occur due to triggering of assert messages.
Definition at line 3291 of file lte-ue-rrc.cc.
References CONNECTED_PHY_PROBLEM, m_asSapUser, m_cellId, m_imsi, m_radioLinkFailureTrace, m_rnti, m_rrcSapUser, ns3::LteAsSapUser::NotifyConnectionReleased(), NS_LOG_FUNCTION, ns3::LteUeRrcSapUser::SendIdealUeContextRemoveRequest(), and SwitchToState().
Referenced by DoNotifyOutOfSync().
ResetRlfParams()
void ns3::LteUeRrc::ResetRlfParams () private
Reset radio link failure parameters.
RLF timers and counters should be rest upon:
If the UE received N311 in Sync indications from the UE PHY.
If the UE receives RRCConnectionReconfiguration including the mobilityControlInfo (TS 36.331 sec 5.3.5.4)
Inside this method the UE RRC also instructs the UE PHY to reset the RLF parameters so, it can start RLF detection again.
Definition at line 3343 of file lte-ue-rrc.cc.
References ns3::EventId::Cancel(), m_cphySapProvider, m_imsi, m_noOfSyncIndications, m_radioLinkFailureDetected, and NS_LOG_FUNCTION.
Referenced by DoNotifyInSync(), and LeaveConnectedMode().
SaveScellUeMeasurements()
void ns3::LteUeRrc::SaveScellUeMeasurements (uint16_t cellId, double rsrp, double rsrq, bool useLayer3Filtering, uint16_t componentCarrierId) private
keep the given measurement result as the latest measurement figures, to be utilised by UE RRC functions.
Parameters
cellId the cell ID of the measured cell
rsrp measured RSRP value to be saved (in dBm)
rsrq measured RSRQ value to be saved (in dB)
useLayer3Filtering
componentCarrierId
Todo:
Remove the useLayer3Filtering argument
As for SaveUeMeasurements, this function aims to store the latest measurements related to the secondary component carriers. in the current implementation it saves only measurements related on the serving secondary carriers while, measurements related to the Neighbor Cell are filtered
Definition at line 3229 of file lte-ue-rrc.cc.
References ns3::LteUeRrc::VarMeasConfig::aRsrp, ns3::LteUeRrc::VarMeasConfig::aRsrq, m_cellId, m_imsi, m_state, m_storedScellMeasValues, m_varMeasConfig, ns3::Simulator::Now(), NS_ASSERT_MSG, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::LteUeRrc::MeasValues::rsrp, ns3::LteUeRrc::MeasValues::rsrq, and ns3::ToString().
Referenced by DoReportUeMeasurements().
SaveUeMeasurements()
void ns3::LteUeRrc::SaveUeMeasurements (uint16_t cellId, double rsrp, double rsrq, bool useLayer3Filtering) private
Keep the given measurement result as the latest measurement figures, to be utilised by UE RRC functions.
Parameters
cellId the cell ID of the measured cell
rsrp measured RSRP value to be saved (in dBm)
rsrq measured RSRQ value to be saved (in dB)
useLayer3Filtering
Todo:
Remove the useLayer3Filtering argument
Implements Section 5.5.3.2 "Layer 3 filtering" of 3GPP TS 36.331. Layer-3 filtering is applied to the given measurement results before saved to m_storedMeasValues. The filtering is however disabled when the UE is in IDLE mode, i.e., saving unfiltered values.
Layer-3 filtering is influenced by a filter coefficient, which determines the strength of the filtering. This coefficient is provided by the active quantity configuration in m_varMeasConfig, which is configured by the LteUeRrc::ApplyMeasConfig. Details on how the coefficient works and how to modify it can be found in LTE module's Design Documentation.
See also
LteUeRrc::m_storedMeasValues
Definition at line 1809 of file lte-ue-rrc.cc.
References ns3::LteUeRrc::VarMeasConfig::aRsrp, ns3::LteUeRrc::VarMeasConfig::aRsrq, m_cellId, m_imsi, m_state, m_storedMeasValues, m_varMeasConfig, ns3::Simulator::Now(), NS_ASSERT_MSG, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::LteUeRrc::MeasValues::rsrp, ns3::LteUeRrc::MeasValues::rsrq, and ns3::ToString().
Referenced by DoReportUeMeasurements().
SendMeasurementReport()
void ns3::LteUeRrc::SendMeasurementReport (uint8_t measId) private
Produce a proper measurement report from the given measurement identity's reporting entry in m_varMeasReportList and then submit it to the serving eNodeB.
Parameters
measId the measurement identity which report is to be submitted.
Implements Section 5.5.5 "Measurement reporting" of 3GPP TS 36.331. Producing a measurement report involves several tasks such as:
including the measurement results of the serving cell into the report;
selecting some neighbour cells which triggered the reporting (i.e., those in cellsTriggeredList) to be included in the report;
sorting the order of neighbour cells in the report by their RSRP or RSRQ measurement results (the highest comes first); and
ensuring the number of neighbour cells in the report is under the maxReportCells limit defined by the measurement identity's reporting configuration.
The RSRP and RSRQ measurement results included in the report are expressed in 3GPP-specified range format. They are converted from dBm and dB units using EutranMeasurementMapping::Dbm2RsrpRange and EutranMeasurementMapping::Db2RsrqRange functions.
Measurement report is submitted to the serving eNodeB through the RRC protocol. The LteUeRrcSapUser::SendMeasurementReport method of the UE RRC SAP facilitates this submission.
After the submission, the function will repeat itself after a certain interval. The interval length may vary from 120 ms to 60 minutes and is determined by the report interval parameter specified by the measurement identity's reporting configuration.
Definition at line 2884 of file lte-ue-rrc.cc.
References ns3::EutranMeasurementMapping::Db2RsrqRange(), ns3::EutranMeasurementMapping::Dbm2RsrpRange(), ns3::LteRrcSap::MeasResultEutra::haveCgiInfo, ns3::LteRrcSap::MeasResults::haveMeasResultNeighCells, ns3::LteRrcSap::MeasResultServFreqList::haveMeasurementResultsNeighCell, ns3::LteRrcSap::MeasResultServFreqList::haveMeasurementResultsServingSCells, ns3::LteRrcSap::MeasResultEutra::haveRsrpResult, ns3::LteRrcSap::MeasResultScell::haveRsrpResult, ns3::LteRrcSap::MeasResultEutra::haveRsrqResult, ns3::LteRrcSap::MeasResultScell::haveRsrqResult, ns3::LteRrcSap::MeasResults::haveScellsMeas, m_cellId, m_rrcSapUser, m_storedMeasValues, m_storedScellMeasValues, m_varMeasConfig, m_varMeasReportList, ns3::LteRrcSap::ReportConfigEutra::maxReportCells, ns3::LteRrcSap::MeasResults::measId, ns3::LteUeRrc::VarMeasConfig::measIdList, ns3::LteRrcSap::MeasResults::measResultListEutra, ns3::LteRrcSap::MeasurementReport::measResults, ns3::LteRrcSap::MeasResultServFreqList::measResultScell, ns3::LteRrcSap::MeasResults::measScellResultList, ns3::MilliSeconds(), ns3::LteRrcSap::ReportConfigEutra::MIN1, ns3::LteRrcSap::ReportConfigEutra::MIN12, ns3::LteRrcSap::ReportConfigEutra::MIN30, ns3::LteRrcSap::ReportConfigEutra::MIN6, ns3::LteRrcSap::ReportConfigEutra::MIN60, ns3::LteRrcSap::ReportConfigEutra::MS1024, ns3::LteRrcSap::ReportConfigEutra::MS10240, ns3::LteRrcSap::ReportConfigEutra::MS120, ns3::LteRrcSap::ReportConfigEutra::MS2048, ns3::LteRrcSap::ReportConfigEutra::MS240, ns3::LteRrcSap::ReportConfigEutra::MS480, ns3::LteRrcSap::ReportConfigEutra::MS5120, ns3::LteRrcSap::ReportConfigEutra::MS640, NS_ASSERT, NS_FATAL_ERROR, NS_LOG_ERROR, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_WARN, ns3::LteRrcSap::MeasResultEutra::physCellId, ns3::LteUeRrc::VarMeasConfig::reportConfigList, ns3::LteRrcSap::ReportConfigEutra::reportInterval, ns3::LteRrcSap::ReportConfigEutra::RSRP, ns3::LteRrcSap::MeasResultEutra::rsrpResult, ns3::LteRrcSap::MeasResultScell::rsrpResult, ns3::LteRrcSap::MeasResults::rsrpResult, ns3::LteRrcSap::ReportConfigEutra::RSRQ, ns3::LteRrcSap::MeasResultEutra::rsrqResult, ns3::LteRrcSap::MeasResultScell::rsrqResult, ns3::LteRrcSap::MeasResults::rsrqResult, ns3::Simulator::Schedule(), ns3::Seconds(), ns3::LteUeRrcSapUser::SendMeasurementReport(), ns3::LteRrcSap::MeasResultScell::servFreqId, and ns3::LteRrcSap::ReportConfigEutra::triggerQuantity.
Referenced by VarMeasReportListAdd(), and VarMeasReportListErase().
SetAsSapUser()
void ns3::LteUeRrc::SetAsSapUser (LteAsSapUser * s)
Set the AS SAP user to interact with the NAS entity.
Parameters
s the AS SAP user
Definition at line 423 of file lte-ue-rrc.cc.
References m_asSapUser.
SetImsi()
void ns3::LteUeRrc::SetImsi (uint64_t imsi)
Parameters
imsi the unique UE identifier
Definition at line 435 of file lte-ue-rrc.cc.
References m_cmacSapProvider, m_cphySapProvider, m_imsi, m_numberOfComponentCarriers, and NS_LOG_FUNCTION.
SetLteCcmRrcSapProvider()
void ns3::LteUeRrc::SetLteCcmRrcSapProvider (LteUeCcmRrcSapProvider * s)
set the Component Carrier Management SAP this RRC should interact with
Parameters
s the Component Carrier Management SAP Provider to be used by this RRC
Definition at line 409 of file lte-ue-rrc.cc.
References m_ccmRrcSapProvider, and NS_LOG_FUNCTION.
SetLteMacSapProvider()
void ns3::LteUeRrc::SetLteMacSapProvider (LteMacSapProvider * s)
set the MAC SAP provider.
The ue RRC does not use this directly, but it needs to provide it to newly created RLC instances.
Parameters
s the MAC SAP provider that will be used by all newly created RLC instances
Definition at line 402 of file lte-ue-rrc.cc.
References m_macSapProvider, and NS_LOG_FUNCTION.
SetLteUeCmacSapProvider() [1/2]
void ns3::LteUeRrc::SetLteUeCmacSapProvider (LteUeCmacSapProvider * s)
set the CMAC SAP this RRC should interact with
This function is overloaded to maintain backward compatibility
Parameters
s the CMAC SAP Provider to be used by this RRC
Definition at line 360 of file lte-ue-rrc.cc.
References m_cmacSapProvider, and NS_LOG_FUNCTION.
SetLteUeCmacSapProvider() [2/2]
void ns3::LteUeRrc::SetLteUeCmacSapProvider (LteUeCmacSapProvider * s, uint8_t index)
set the CMAC SAP this RRC should interact with
This function is overloaded to maintain backward compatibility
Parameters
s the CMAC SAP Provider to be used by this RRC
index the index
Definition at line 367 of file lte-ue-rrc.cc.
References m_cmacSapProvider, and NS_LOG_FUNCTION.
SetLteUeCphySapProvider() [1/2]
void ns3::LteUeRrc::SetLteUeCphySapProvider (LteUeCphySapProvider * s)
set the CPHY SAP this RRC should use to interact with the PHY
Parameters
s the CPHY SAP Provider
Definition at line 332 of file lte-ue-rrc.cc.
References m_cphySapProvider, and NS_LOG_FUNCTION.
SetLteUeCphySapProvider() [2/2]
void ns3::LteUeRrc::SetLteUeCphySapProvider (LteUeCphySapProvider * s, uint8_t index)
set the CPHY SAP this RRC should use to interact with the PHY
Parameters
s the CPHY SAP Provider
index the index
Definition at line 339 of file lte-ue-rrc.cc.
References m_cphySapProvider, and NS_LOG_FUNCTION.
SetLteUeRrcSapUser()
void ns3::LteUeRrc::SetLteUeRrcSapUser (LteUeRrcSapUser * s)
set the RRC SAP this RRC should interact with
Parameters
s the RRC SAP User to be used by this RRC
Definition at line 388 of file lte-ue-rrc.cc.
References m_rrcSapUser, and NS_LOG_FUNCTION.
SetUseRlcSm()
void ns3::LteUeRrc::SetUseRlcSm (bool val)
Parameters
val true if RLC SM is to be used, false if RLC UM/AM are to be used
Definition at line 518 of file lte-ue-rrc.cc.
References m_useRlcSm, and NS_LOG_FUNCTION.
StartConnection()
void ns3::LteUeRrc::StartConnection () private
Start connection function.
Definition at line 3064 of file lte-ue-rrc.cc.
References IDLE_RANDOM_ACCESS, m_cmacSapProvider, m_connectionPending, m_hasReceivedMib, m_hasReceivedSib2, m_imsi, NS_ASSERT, NS_LOG_FUNCTION, and SwitchToState().
Referenced by DoRecvSystemInformation(), and SwitchToState().
StorePreviousCellId()
void ns3::LteUeRrc::StorePreviousCellId (uint16_t cellId)
Store the previous cell id.
Parameters
cellId The cell id of the previous cell the UE was attached to
Definition at line 449 of file lte-ue-rrc.cc.
References m_previousCellId, and NS_LOG_FUNCTION.
Referenced by DoRecvRrcConnectionReconfiguration(), and LeaveConnectedMode().
SwitchToState()
void ns3::LteUeRrc::SwitchToState (State s) private
Switch the UE RRC to the given state.
Parameters
s the destination state
Definition at line 3171 of file lte-ue-rrc.cc.
References CONNECTED_HANDOVER, CONNECTED_NORMALLY, CONNECTED_PHY_PROBLEM, CONNECTED_REESTABLISHING, IDLE_CAMPED_NORMALLY, IDLE_CELL_SEARCH, IDLE_CONNECTING, IDLE_RANDOM_ACCESS, IDLE_START, IDLE_WAIT_MIB, IDLE_WAIT_MIB_SIB1, IDLE_WAIT_SIB1, IDLE_WAIT_SIB2, m_cellId, m_connectionPending, m_hasReceivedSib2, m_imsi, m_leaveConnectedMode, m_rnti, m_state, m_stateTransitionTrace, NS_ASSERT, NS_FATAL_ERROR, NS_LOG_FUNCTION, NS_LOG_INFO, StartConnection(), and ns3::ToString().
Referenced by ConnectionTimeout(), DoConnect(), DoForceCampedOnEnb(), DoNotifyRandomAccessFailed(), DoNotifyRandomAccessSuccessful(), DoRecvMasterInformationBlock(), DoRecvRrcConnectionReconfiguration(), DoRecvRrcConnectionReject(), DoRecvRrcConnectionSetup(), DoStartCellSelection(), EvaluateCellForSelection(), LeaveConnectedMode(), RadioLinkFailureDetected(), StartConnection(), and SynchronizeToStrongestCell().
SynchronizeToStrongestCell()
void ns3::LteUeRrc::SynchronizeToStrongestCell () private
Go through the list of measurement results, choose the one with the strongest RSRP, and tell PHY to synchronize to it.
Warning
This function is a part of the initial cell selection procedure, hence must be only executed during IDLE mode.
Definition at line 1219 of file lte-ue-rrc.cc.
References IDLE_CELL_SEARCH, IDLE_WAIT_MIB_SIB1, m_acceptableCell, m_cphySapProvider, m_dlEarfcn, m_state, m_storedMeasValues, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, NS_LOG_WARN, and SwitchToState().
Referenced by DoReportUeMeasurements(), and EvaluateCellForSelection().
VarMeasReportListAdd()
void ns3::LteUeRrc::VarMeasReportListAdd (uint8_t measId, ConcernedCells_t enteringCells) private
Compose a new reporting entry of the given measurement identity, insert it into m_varMeasReportList, and set it up for submission to eNodeB.
Parameters
measId the measurement identity which the new reporting entry will be based upon
enteringCells the cells which are responsible for triggering the reporting (i.e., successfully fulfilling the entering condition of the measurement identity) and will be included in the measurement report.
Note
If an existing reporting entry with the same measurement identity has already existed in m_varMeasReportList, the function will update it by adding the entering cells into the existing reporting entry.
When time-to-trigger is enabled for this measurement identity, the function will also remove the related trigger from the m_enteringTriggerQueue.
Definition at line 2732 of file lte-ue-rrc.cc.
References CancelEnteringTrigger(), m_enteringTriggerQueue, m_varMeasReportList, ns3::LteUeRrc::VarMeasReport::measId, NS_ASSERT, NS_ASSERT_MSG, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), SendMeasurementReport(), and ns3::UE_MEASUREMENT_REPORT_DELAY.
Referenced by MeasurementReportTriggering().
VarMeasReportListClear()
void ns3::LteUeRrc::VarMeasReportListClear (uint8_t measId) private
Remove the reporting entry of the given measurement identity from m_varMeasReportList.
Parameters
measId the measurement identity to be removed from m_varMeasReportList, must already exists there, otherwise an error would be raised
Any events or triggers related with this measurement identity will be canceled as well.
Definition at line 2865 of file lte-ue-rrc.cc.
References CancelEnteringTrigger(), CancelLeavingTrigger(), m_varMeasReportList, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by ApplyMeasConfig(), DoNotifyRandomAccessSuccessful(), and LeaveConnectedMode().
VarMeasReportListErase()
void ns3::LteUeRrc::VarMeasReportListErase (uint8_t measId, ConcernedCells_t leavingCells, bool reportOnLeave) private
Remove some cells from an existing reporting entry in m_varMeasReportList.
Parameters
measId the measurement identity to be removed from m_varMeasReportList, must already exists there, otherwise an error would be raised
leavingCells the cells which are about to be removed
reportOnLeave when true, will make the function send one last measurement report to eNodeB before removing it
Note
If a given cell is not found in the reporting entry, the function will quietly continue.
If the removal has removed all the cells in the reporting entry, the function will remove the reporting entry as well.
When time-to-trigger is enabled for this measurement identity, the function will also remove the related trigger from the m_leavingTriggerQueue.
Definition at line 2804 of file lte-ue-rrc.cc.
References CancelLeavingTrigger(), m_leavingTriggerQueue, m_varMeasReportList, NS_ASSERT, NS_LOG_FUNCTION, and SendMeasurementReport().
Referenced by MeasurementReportTriggering().
Friends And Related Function Documentation
LtePdcpSpecificLtePdcpSapUser< LteUeRrc >
friend class LtePdcpSpecificLtePdcpSapUser< LteUeRrc > friend
allow LtePdcpSpecificLtePdcpSapUser<LteUeRrc> class friend access
Definition at line 87 of file lte-ue-rrc.h.
Referenced by LteUeRrc().
MemberLteAsSapProvider< LteUeRrc >
friend class MemberLteAsSapProvider< LteUeRrc > friend
allow MemberLteAsSapProvider<LteUeRrc> class friend access
Definition at line 87 of file lte-ue-rrc.h.
Referenced by LteUeRrc().
MemberLteUeCcmRrcSapUser< LteUeRrc >
friend class MemberLteUeCcmRrcSapUser< LteUeRrc > friend
allow MemberLteUeCcmRrcSapUser<LteUeRrc> class friend access
Definition at line 87 of file lte-ue-rrc.h.
Referenced by LteUeRrc().
MemberLteUeCphySapUser< LteUeRrc >
friend class MemberLteUeCphySapUser< LteUeRrc > friend
allow MemberLteUeCphySapUser<LteUeRrc> class friend access
Definition at line 87 of file lte-ue-rrc.h.
MemberLteUeRrcSapProvider< LteUeRrc >
friend class MemberLteUeRrcSapProvider< LteUeRrc > friend
allow MemberLteUeRrcSapProvider<LteUeRrc> class friend access
Definition at line 87 of file lte-ue-rrc.h.
Referenced by LteUeRrc().
UeMemberLteUeCmacSapUser
friend class UeMemberLteUeCmacSapUser friend
allow UeMemberLteUeCmacSapUser class friend access
Definition at line 85 of file lte-ue-rrc.h.
UeRrcMemberLteEnbCmacSapUser
friend class UeRrcMemberLteEnbCmacSapUser friend
allow UeRrcMemberLteEnbCmacSapUser class friend access
Definition at line 87 of file lte-ue-rrc.h.
Member Data Documentation
m_acceptableCell
std::set<uint16_t> ns3::LteUeRrc::m_acceptableCell private
List of cell ID of acceptable cells for cell selection that have been detected.
Definition at line 948 of file lte-ue-rrc.h.
Referenced by EvaluateCellForSelection(), and SynchronizeToStrongestCell().
m_asSapProvider
LteAsSapProvider* ns3::LteUeRrc::m_asSapProvider private
AS SAP provider.
Definition at line 773 of file lte-ue-rrc.h.
Referenced by LteUeRrc(), DoDispose(), and GetAsSapProvider().
m_asSapUser
LteAsSapUser* ns3::LteUeRrc::m_asSapUser private
AS SAP user.
Definition at line 774 of file lte-ue-rrc.h.
Referenced by ConnectionTimeout(), DoNotifyRandomAccessFailed(), DoReceivePdcpSdu(), DoRecvRrcConnectionReestablishmentReject(), DoRecvRrcConnectionReject(), DoRecvRrcConnectionSetup(), RadioLinkFailureDetected(), and SetAsSapUser().
m_bid2DrbidMap
std::map<uint8_t, uint8_t> ns3::LteUeRrc::m_bid2DrbidMap private
bid to DR bid map
Definition at line 759 of file lte-ue-rrc.h.
Referenced by ApplyRadioResourceConfigDedicated(), Bid2Drbid(), and LeaveConnectedMode().
m_ccmRrcSapProvider
LteUeCcmRrcSapProvider* ns3::LteUeRrc::m_ccmRrcSapProvider private
Interface to the LteUeComponentCarrierManage instance.
CCM RRC SAP provider
Definition at line 779 of file lte-ue-rrc.h.
Referenced by ApplyRadioResourceConfigDedicated(), DoInitialize(), DoRecvRrcConnectionReconfiguration(), LeaveConnectedMode(), and SetLteCcmRrcSapProvider().
m_ccmRrcSapUser
LteUeCcmRrcSapUser* ns3::LteUeRrc::m_ccmRrcSapUser private
CCM RRC SAP user.
Definition at line 780 of file lte-ue-rrc.h.
Referenced by LteUeRrc(), DoDispose(), and GetLteCcmRrcSapUser().
m_cellId
uint16_t ns3::LteUeRrc::m_cellId private
The CellId attribute.
Serving cell identifier.
Definition at line 794 of file lte-ue-rrc.h.
Referenced by ApplyRadioResourceConfigDedicated(), ConnectionTimeout(), DoForceCampedOnEnb(), DoNotifyInSync(), DoNotifyOutOfSync(), DoNotifyRandomAccessFailed(), DoNotifyRandomAccessSuccessful(), DoRecvMasterInformationBlock(), DoRecvRrcConnectionReconfiguration(), DoRecvRrcConnectionSetup(), DoRecvSystemInformation(), DoRecvSystemInformationBlockType1(), EvaluateCellForSelection(), GetCellId(), LeaveConnectedMode(), MeasurementReportTriggering(), RadioLinkFailureDetected(), SaveScellUeMeasurements(), SaveUeMeasurements(), SendMeasurementReport(), and SwitchToState().
m_cmacSapProvider
std::vector<LteUeCmacSapProvider*> ns3::LteUeRrc::m_cmacSapProvider private
UE CMac SAP provider.
Definition at line 765 of file lte-ue-rrc.h.
Referenced by LteUeRrc(), ApplyRadioResourceConfigDedicated(), ApplyRadioResourceConfigDedicatedSecondaryCarrier(), ConnectionTimeout(), DoDispose(), DoInitialize(), DoNotifyRandomAccessSuccessful(), DoRecvRrcConnectionReconfiguration(), DoRecvRrcConnectionReject(), DoRecvRrcConnectionSetup(), DoRecvSystemInformation(), InitializeSap(), LeaveConnectedMode(), SetImsi(), SetLteUeCmacSapProvider(), and StartConnection().
m_cmacSapUser
std::vector<LteUeCmacSapUser*> ns3::LteUeRrc::m_cmacSapUser private
UE CMac SAP user.
Definition at line 764 of file lte-ue-rrc.h.
Referenced by LteUeRrc(), DoDispose(), GetLteUeCmacSapUser(), and InitializeSap().
m_connectionEstablishedTrace
TracedCallback<uint64_t, uint16_t, uint16_t> ns3::LteUeRrc::m_connectionEstablishedTrace private
The ConnectionEstablished trace source.
Fired upon successful RRC connection establishment. Exporting IMSI, cell ID, and RNTI.
Definition at line 879 of file lte-ue-rrc.h.
Referenced by DoRecvRrcConnectionSetup(), and GetTypeId().
m_connectionPending
bool ns3::LteUeRrc::m_connectionPending private
True if a connection request by upper layers is pending.
Definition at line 936 of file lte-ue-rrc.h.
Referenced by DoConnect(), DoRecvSystemInformation(), EvaluateCellForSelection(), StartConnection(), and SwitchToState().
m_connectionReconfigurationTrace
TracedCallback<uint64_t, uint16_t, uint16_t> ns3::LteUeRrc::m_connectionReconfigurationTrace private
The ConnectionReconfiguration trace source.
Fired upon RRC connection reconfiguration. Exporting IMSI, cell ID, and RNTI.
Definition at line 889 of file lte-ue-rrc.h.
Referenced by DoRecvRrcConnectionReconfiguration(), and GetTypeId().
m_connectionTimeout
EventId ns3::LteUeRrc::m_connectionTimeout private
Invokes ConnectionEstablishmentTimeout() if RRC connection establishment procedure for this UE takes longer than T300.
Definition at line 1235 of file lte-ue-rrc.h.
Referenced by DoNotifyRandomAccessSuccessful(), DoRecvRrcConnectionReject(), and DoRecvRrcConnectionSetup().
m_connectionTimeoutTrace
TracedCallback<uint64_t, uint16_t, uint16_t, uint8_t> ns3::LteUeRrc::m_connectionTimeoutTrace private
The ConnectionTimeout trace source.
Fired upon timeout RRC connection establishment because of T300. Exporting IMSI, cell ID, and RNTI.
Definition at line 884 of file lte-ue-rrc.h.
Referenced by ConnectionTimeout(), and GetTypeId().
m_connEstFailCount
uint8_t ns3::LteUeRrc::m_connEstFailCount private
the counter to count T300 timer expiration
Definition at line 1284 of file lte-ue-rrc.h.
Referenced by ConnectionTimeout(), and DoRecvRrcConnectionSetup().
m_connEstFailCountLimit
uint8_t ns3::LteUeRrc::m_connEstFailCountLimit private
the counter value for T300 timer expiration received from the eNB
Definition at line 1282 of file lte-ue-rrc.h.
Referenced by ConnectionTimeout(), and DoRecvSystemInformation().
m_cphySapProvider
std::vector<LteUeCphySapProvider*> ns3::LteUeRrc::m_cphySapProvider private
UE CPhy SAP provider.
Definition at line 762 of file lte-ue-rrc.h.
Referenced by LteUeRrc(), ApplyMeasConfig(), ApplyRadioResourceConfigDedicated(), ApplyRadioResourceConfigDedicatedSecondaryCarrier(), DoDispose(), DoForceCampedOnEnb(), DoNotifyOutOfSync(), DoRecvMasterInformationBlock(), DoRecvRrcConnectionReconfiguration(), DoRecvSystemInformation(), DoSetTemporaryCellRnti(), DoStartCellSelection(), EvaluateCellForSelection(), InitializeSap(), LeaveConnectedMode(), ResetRlfParams(), SetImsi(), SetLteUeCphySapProvider(), and SynchronizeToStrongestCell().
m_cphySapUser
std::vector<LteUeCphySapUser*> ns3::LteUeRrc::m_cphySapUser private
UE CPhy SAP user.
Definition at line 761 of file lte-ue-rrc.h.
Referenced by LteUeRrc(), DoDispose(), GetLteUeCphySapUser(), and InitializeSap().
m_csgWhiteList
uint32_t ns3::LteUeRrc::m_csgWhiteList private
List of CSG ID which this UE entity has access to.
Definition at line 951 of file lte-ue-rrc.h.
Referenced by DoSetCsgWhiteList(), and EvaluateCellForSelection().
m_dlBandwidth
uint16_t ns3::LteUeRrc::m_dlBandwidth private
Downlink bandwidth in RBs.
Definition at line 825 of file lte-ue-rrc.h.
Referenced by DoRecvMasterInformationBlock(), EvaluateCellForSelection(), and GetDlBandwidth().
m_dlEarfcn
uint32_t ns3::LteUeRrc::m_dlEarfcn private
Downlink carrier frequency.
Definition at line 828 of file lte-ue-rrc.h.
Referenced by DoForceCampedOnEnb(), DoStartCellSelection(), EvaluateCellForSelection(), GetDlEarfcn(), LeaveConnectedMode(), and SynchronizeToStrongestCell().
m_drbCreatedTrace
TracedCallback<uint64_t, uint16_t, uint16_t, uint8_t> ns3::LteUeRrc::m_drbCreatedTrace private
The DrbCreated trace source.
Fired when DRB is created, i.e. the RLC and PDCP entities are created for one logical channel. Exporting IMSI, cell ID, RNTI, LCID.
Definition at line 922 of file lte-ue-rrc.h.
Referenced by ApplyRadioResourceConfigDedicated(), and GetTypeId().
m_drbMap
std::map<uint8_t, Ptr<LteDataRadioBearerInfo> > ns3::LteUeRrc::m_drbMap private
The DataRadioBearerMap attribute.
List of UE RadioBearerInfo for Data Radio Bearers by LCID.
Definition at line 813 of file lte-ue-rrc.h.
Referenced by ApplyRadioResourceConfigDedicated(), DoDispose(), DoRecvRrcConnectionReconfiguration(), DoSendData(), GetTypeId(), and LeaveConnectedMode().
m_drbPdcpSapUser
LtePdcpSapUser* ns3::LteUeRrc::m_drbPdcpSapUser private
DRB PDCP SAP user.
Definition at line 771 of file lte-ue-rrc.h.
Referenced by LteUeRrc(), ApplyRadioResourceConfigDedicated(), and DoDispose().
m_enteringTriggerQueue
std::map<uint8_t, std::list<PendingTrigger_t> > ns3::LteUeRrc::m_enteringTriggerQueue private
List of triggers that were raised because entering condition have been true, but are still delayed from reporting it by time-to-trigger.
The list is indexed by the measurement identity where the trigger originates from. The enclosed event will run at the end of the time-to-trigger and insert a reporting entry to m_varMeasReportList.
Definition at line 1130 of file lte-ue-rrc.h.
Referenced by ApplyMeasConfig(), CancelEnteringTrigger(), MeasurementReportTriggering(), and VarMeasReportListAdd().
m_handoverEndErrorTrace
TracedCallback<uint64_t, uint16_t, uint16_t> ns3::LteUeRrc::m_handoverEndErrorTrace private
The HandoverEndError trace source.
Fired upon failure of a handover procedure. Exporting IMSI, cell ID, and RNTI.
Definition at line 904 of file lte-ue-rrc.h.
Referenced by DoNotifyRandomAccessFailed(), and GetTypeId().
m_handoverEndOkTrace
TracedCallback<uint64_t, uint16_t, uint16_t> ns3::LteUeRrc::m_handoverEndOkTrace private
The HandoverEndOk trace source.
Fired upon successful termination of a handover procedure. Exporting IMSI, cell ID, and RNTI.
Definition at line 899 of file lte-ue-rrc.h.
Referenced by DoNotifyRandomAccessSuccessful(), and GetTypeId().
m_handoverStartTrace
TracedCallback<uint64_t, uint16_t, uint16_t, uint16_t> ns3::LteUeRrc::m_handoverStartTrace private
The HandoverStart trace source.
Fired upon start of a handover procedure. Exporting IMSI, source cell ID, RNTI, and target cell ID.
Definition at line 894 of file lte-ue-rrc.h.
Referenced by DoRecvRrcConnectionReconfiguration(), and GetTypeId().
m_hasReceivedMib
bool ns3::LteUeRrc::m_hasReceivedMib private
True if MIB was received for the current cell.
Definition at line 938 of file lte-ue-rrc.h.
Referenced by DoRecvMasterInformationBlock(), EvaluateCellForSelection(), LeaveConnectedMode(), and StartConnection().
m_hasReceivedSib1
bool ns3::LteUeRrc::m_hasReceivedSib1 private
True if SIB1 was received for the current cell.
Definition at line 940 of file lte-ue-rrc.h.
Referenced by DoRecvSystemInformationBlockType1(), EvaluateCellForSelection(), and LeaveConnectedMode().
m_hasReceivedSib2
bool ns3::LteUeRrc::m_hasReceivedSib2 private
True if SIB2 was received for the current cell.
Definition at line 942 of file lte-ue-rrc.h.
Referenced by ConnectionTimeout(), DoRecvRrcConnectionReject(), DoRecvSystemInformation(), LeaveConnectedMode(), StartConnection(), and SwitchToState().
m_imsi
uint64_t ns3::LteUeRrc::m_imsi private
The unique UE identifier.
Definition at line 786 of file lte-ue-rrc.h.
Referenced by ApplyRadioResourceConfigDedicated(), ConnectionTimeout(), DoConnect(), DoForceCampedOnEnb(), DoNotifyInSync(), DoNotifyOutOfSync(), DoNotifyRandomAccessFailed(), DoNotifyRandomAccessSuccessful(), DoRecvMasterInformationBlock(), DoRecvRrcConnectionReconfiguration(), DoRecvRrcConnectionSetup(), DoRecvSystemInformation(), DoRecvSystemInformationBlockType1(), DoResetSyncIndicationCounter(), DoSetCsgWhiteList(), DoStartCellSelection(), EvaluateCellForSelection(), GetImsi(), LeaveConnectedMode(), RadioLinkFailureDetected(), ResetRlfParams(), SaveScellUeMeasurements(), SaveUeMeasurements(), SetImsi(), StartConnection(), and SwitchToState().
m_initialCellSelectionEndErrorTrace
TracedCallback<uint64_t, uint16_t> ns3::LteUeRrc::m_initialCellSelectionEndErrorTrace private
The InitialCellSelectionEndError trace source.
Fired upon failed initial cell selection procedure. Exporting IMSI and the cell ID under evaluation.
Definition at line 863 of file lte-ue-rrc.h.
Referenced by EvaluateCellForSelection(), and GetTypeId().
m_initialCellSelectionEndOkTrace
TracedCallback<uint64_t, uint16_t> ns3::LteUeRrc::m_initialCellSelectionEndOkTrace private
The InitialCellSelectionEndOk trace source.
Fired upon successful initial cell selection procedure. Exporting IMSI and the selected cell ID.
Definition at line 858 of file lte-ue-rrc.h.
Referenced by EvaluateCellForSelection(), and GetTypeId().
m_lastRrcTransactionIdentifier
uint8_t ns3::LteUeRrc::m_lastRrcTransactionIdentifier private
last RRC transaction identifier
Definition at line 821 of file lte-ue-rrc.h.
Referenced by DoNotifyRandomAccessSuccessful(), and DoRecvRrcConnectionReconfiguration().
m_lastSib1
LteRrcSap::SystemInformationBlockType1 ns3::LteUeRrc::m_lastSib1 private
Stored content of the last SIB1 received.
Definition at line 945 of file lte-ue-rrc.h.
Referenced by DoRecvSystemInformationBlockType1(), and EvaluateCellForSelection().
m_leaveConnectedMode
bool ns3::LteUeRrc::m_leaveConnectedMode private
true if UE NAS ask UE RRC to leave connected mode, e.g., after RLF, i.e. T310 has expired
Definition at line 1278 of file lte-ue-rrc.h.
Referenced by DoRecvRrcConnectionSetup(), LeaveConnectedMode(), and SwitchToState().
m_leavingTriggerQueue
std::map<uint8_t, std::list<PendingTrigger_t> > ns3::LteUeRrc::m_leavingTriggerQueue private
List of triggers that were raised because leaving condition have been true, but are still delayed from stopping the reporting by time-to-trigger.
The list is indexed by the measurement identity where the trigger originates from. The enclosed event will run at the end of the time-to-trigger and remove the associated reporting entry from m_varMeasReportList.
Definition at line 1142 of file lte-ue-rrc.h.
Referenced by ApplyMeasConfig(), CancelLeavingTrigger(), MeasurementReportTriggering(), and VarMeasReportListErase().
m_macSapProvider
LteMacSapProvider* ns3::LteUeRrc::m_macSapProvider private
MAC SAP provider.
Definition at line 770 of file lte-ue-rrc.h.
Referenced by ApplyRadioResourceConfigDedicated(), DoInitialize(), and SetLteMacSapProvider().
m_mibReceivedTrace
TracedCallback<uint64_t, uint16_t, uint16_t, uint16_t> ns3::LteUeRrc::m_mibReceivedTrace private
The MibReceived trace source.
Fired upon reception of Master Information Block. Exporting IMSI, the serving cell ID, RNTI, and the source cell ID.
Definition at line 836 of file lte-ue-rrc.h.
Referenced by DoRecvMasterInformationBlock(), and GetTypeId().
m_n310
uint8_t ns3::LteUeRrc::m_n310 private
The 'N310' attribute.
This specifies the maximum consecutive out-of-sync indications from lower layers.
Definition at line 1257 of file lte-ue-rrc.h.
Referenced by DoNotifyOutOfSync(), and GetTypeId().
m_n311
uint8_t ns3::LteUeRrc::m_n311 private
The 'N311' attribute.
This specifies the minimum consecutive in-sync indications from lower layers.
Definition at line 1263 of file lte-ue-rrc.h.
Referenced by DoNotifyInSync(), and GetTypeId().
m_noOfSyncIndications
uint8_t ns3::LteUeRrc::m_noOfSyncIndications private
number of in-sync or out-of-sync indications coming from PHY layer
Definition at line 1276 of file lte-ue-rrc.h.
Referenced by DoNotifyInSync(), DoNotifyOutOfSync(), DoRecvRrcConnectionSetup(), DoResetSyncIndicationCounter(), and ResetRlfParams().
m_numberOfComponentCarriers
uint16_t ns3::LteUeRrc::m_numberOfComponentCarriers
The number of component carriers.
Definition at line 1343 of file lte-ue-rrc.h.
Referenced by ApplyMeasConfig(), ApplyRadioResourceConfigDedicated(), ConnectionTimeout(), DoDispose(), DoRecvRrcConnectionReconfiguration(), DoRecvRrcConnectionReject(), DoSetNumberOfComponentCarriers(), InitializeSap(), LeaveConnectedMode(), and SetImsi().
m_pdschConfigDedicated
LteRrcSap::PdschConfigDedicated ns3::LteUeRrc::m_pdschConfigDedicated private
the PDSCH condig dedicated
Definition at line 823 of file lte-ue-rrc.h.
Referenced by ApplyRadioResourceConfigDedicated().
m_phySyncDetectionTrace
TracedCallback<uint64_t, uint16_t, uint16_t, std::string, uint8_t> ns3::LteUeRrc::m_phySyncDetectionTrace private
The 'PhySyncDetection' trace source.
Fired when UE RRC receives in-sync or out-of-sync indications from UE PHY
Definition at line 928 of file lte-ue-rrc.h.
Referenced by DoNotifyInSync(), DoNotifyOutOfSync(), and GetTypeId().
m_previousCellId
uint16_t ns3::LteUeRrc::m_previousCellId private
the cell id of the previous cell UE was attached to
Definition at line 1280 of file lte-ue-rrc.h.
Referenced by GetPreviousCellId(), and StorePreviousCellId().
m_radioLinkFailureDetected
EventId ns3::LteUeRrc::m_radioLinkFailureDetected private
Time limit (given by m_t310) before the radio link is considered to have failed.
It is set upon detecting physical layer problems i.e. upon receiving N310 consecutive out-of-sync indications from lower layers. Calling LteUeRrc::RadioLinkFailureDetected() when it expires. It is cancelled upon receiving N311 consecutive in-sync indications. Upon expiry, the UE transitions to RRC_IDLE and no RRC connection re-establishment is initiated.
Definition at line 1274 of file lte-ue-rrc.h.
Referenced by DoNotifyOutOfSync(), and ResetRlfParams().
m_radioLinkFailureTrace
TracedCallback<uint64_t, uint16_t, uint16_t> ns3::LteUeRrc::m_radioLinkFailureTrace private
The 'RadioLinkFailure' trace source.
Fired when T310 timer expires.
Definition at line 933 of file lte-ue-rrc.h.
Referenced by GetTypeId(), and RadioLinkFailureDetected().
m_randomAccessErrorTrace
TracedCallback<uint64_t, uint16_t, uint16_t> ns3::LteUeRrc::m_randomAccessErrorTrace private
The RandomAccessError trace source.
Fired upon failure of the random access procedure. Exporting IMSI, cell ID, and RNTI.
Definition at line 874 of file lte-ue-rrc.h.
Referenced by DoNotifyRandomAccessFailed(), and GetTypeId().
m_randomAccessSuccessfulTrace
TracedCallback<uint64_t, uint16_t, uint16_t> ns3::LteUeRrc::m_randomAccessSuccessfulTrace private
The RandomAccessSuccessful trace source.
Fired upon successful completion of the random access procedure. Exporting IMSI, cell ID, and RNTI.
Definition at line 869 of file lte-ue-rrc.h.
Referenced by DoNotifyRandomAccessSuccessful(), and GetTypeId().
m_rnti
uint16_t ns3::LteUeRrc::m_rnti private
The C-RNTI attribute.
Cell Radio Network Temporary Identifier.
Definition at line 790 of file lte-ue-rrc.h.
Referenced by ApplyRadioResourceConfigDedicated(), ApplyRadioResourceConfigDedicatedSecondaryCarrier(), ConnectionTimeout(), DoCompleteSetup(), DoInitialize(), DoNotifyInSync(), DoNotifyOutOfSync(), DoNotifyRandomAccessFailed(), DoNotifyRandomAccessSuccessful(), DoRecvMasterInformationBlock(), DoRecvRrcConnectionReconfiguration(), DoRecvRrcConnectionReestablishment(), DoRecvRrcConnectionReestablishmentReject(), DoRecvRrcConnectionRelease(), DoRecvRrcConnectionSetup(), DoRecvSystemInformation(), DoRecvSystemInformationBlockType1(), DoSendData(), DoSetTemporaryCellRnti(), GetRnti(), LeaveConnectedMode(), RadioLinkFailureDetected(), and SwitchToState().
m_rrcSapProvider
LteUeRrcSapProvider* ns3::LteUeRrc::m_rrcSapProvider private
RRC SAP provider.
Definition at line 768 of file lte-ue-rrc.h.
Referenced by LteUeRrc(), DoDispose(), and GetLteUeRrcSapProvider().
m_rrcSapUser
LteUeRrcSapUser* ns3::LteUeRrc::m_rrcSapUser private
RRC SAP user.
Definition at line 767 of file lte-ue-rrc.h.
Referenced by ApplyRadioResourceConfigDedicated(), DoInitialize(), DoNotifyRandomAccessSuccessful(), DoRecvRrcConnectionReconfiguration(), DoRecvRrcConnectionSetup(), RadioLinkFailureDetected(), SendMeasurementReport(), and SetLteUeRrcSapUser().
m_sCarrierConfiguredTrace
TracedCallback<Ptr<LteUeRrc>, std::list<LteRrcSap::SCellToAddMod> > ns3::LteUeRrc::m_sCarrierConfiguredTrace private
The SCarrierConfigured trace source.
Fired after the configuration of secondary carriers received through RRC Connection Reconfiguration message.
Definition at line 910 of file lte-ue-rrc.h.
Referenced by ApplyRadioResourceConfigDedicatedSecondaryCarrier(), and GetTypeId().
m_sCellToAddModList
std::list<LteRrcSap::SCellToAddMod> ns3::LteUeRrc::m_sCellToAddModList private
Secondary carriers.
Definition at line 830 of file lte-ue-rrc.h.
Referenced by ApplyRadioResourceConfigDedicatedSecondaryCarrier().
m_sib1ReceivedTrace
TracedCallback<uint64_t, uint16_t, uint16_t, uint16_t> ns3::LteUeRrc::m_sib1ReceivedTrace private
The Sib1Received trace source.
Fired upon reception of System Information Block Type 1. Exporting IMSI, the serving cell ID, RNTI, and the source cell ID.
Definition at line 842 of file lte-ue-rrc.h.
Referenced by DoRecvSystemInformationBlockType1(), and GetTypeId().
m_sib2ReceivedTrace
TracedCallback<uint64_t, uint16_t, uint16_t> ns3::LteUeRrc::m_sib2ReceivedTrace private
The Sib2Received trace source.
Fired upon reception of System Information Block Type 2. Exporting IMSI, the serving cell ID, RNTI.
Definition at line 847 of file lte-ue-rrc.h.
Referenced by DoRecvSystemInformation(), and GetTypeId().
m_srb0
Ptr<LteSignalingRadioBearerInfo> ns3::LteUeRrc::m_srb0 private
The Srb0 attribute.
SignalingRadioBearerInfo for SRB0.
Definition at line 799 of file lte-ue-rrc.h.
Referenced by ApplyRadioResourceConfigDedicated(), DoCompleteSetup(), DoInitialize(), DoRecvRrcConnectionReconfiguration(), DoSetTemporaryCellRnti(), GetTypeId(), and LeaveConnectedMode().
m_srb1
Ptr<LteSignalingRadioBearerInfo> ns3::LteUeRrc::m_srb1 private
The Srb1 attribute.
SignalingRadioBearerInfo for SRB1.
Definition at line 803 of file lte-ue-rrc.h.
Referenced by ApplyRadioResourceConfigDedicated(), DoCompleteSetup(), DoRecvRrcConnectionReconfiguration(), GetTypeId(), and LeaveConnectedMode().
m_srb1CreatedTrace
TracedCallback<uint64_t, uint16_t, uint16_t> ns3::LteUeRrc::m_srb1CreatedTrace private
The Srb1Created trace source.
Fired when SRB1 is created, i.e. the RLC and PDCP entities are created for logical channel = 1. Exporting IMSI, cell ID, and RNTI
Definition at line 916 of file lte-ue-rrc.h.
Referenced by ApplyRadioResourceConfigDedicated(), and GetTypeId().
m_srb1Old
Ptr<LteSignalingRadioBearerInfo> ns3::LteUeRrc::m_srb1Old private
SRB1 configuration before RRC connection reconfiguration.
To be deleted soon by DisposeOldSrb1().
Definition at line 808 of file lte-ue-rrc.h.
Referenced by DisposeOldSrb1(), and DoRecvRrcConnectionReconfiguration().
m_state
State ns3::LteUeRrc::m_state private
The current UE RRC state.
Definition at line 783 of file lte-ue-rrc.h.
Referenced by ApplyRadioResourceConfigDedicated(), DoConnect(), DoDisconnect(), DoForceCampedOnEnb(), DoNotifyRandomAccessFailed(), DoNotifyRandomAccessSuccessful(), DoRecvMasterInformationBlock(), DoRecvRrcConnectionReconfiguration(), DoRecvRrcConnectionReestablishment(), DoRecvRrcConnectionReestablishmentReject(), DoRecvRrcConnectionSetup(), DoRecvSystemInformation(), DoRecvSystemInformationBlockType1(), DoReportUeMeasurements(), DoStartCellSelection(), EvaluateCellForSelection(), GetState(), SaveScellUeMeasurements(), SaveUeMeasurements(), SwitchToState(), and SynchronizeToStrongestCell().
m_stateTransitionTrace
TracedCallback<uint64_t, uint16_t, uint16_t, State, State> ns3::LteUeRrc::m_stateTransitionTrace private
The StateTransition trace source.
Fired upon every UE RRC state transition. Exporting IMSI, the serving cell ID, RNTI, old state, and new state.
Definition at line 853 of file lte-ue-rrc.h.
Referenced by GetTypeId(), and SwitchToState().
m_storedMeasValues
std::map<uint16_t, MeasValues> ns3::LteUeRrc::m_storedMeasValues private
Internal storage of the latest measurement results from all detected detected cells, indexed by the cell ID where the measurement was taken from.
Each measurement result comprises of RSRP (in dBm) and RSRQ (in dB).
In IDLE mode, the measurement results are used by the initial cell selection procedure. While in CONNECTED mode, layer-3 filtering is applied to the measurement results and they are used by UE measurements function (LteUeRrc::MeasurementReportTriggering and LteUeRrc::SendMeasurementReport).
Definition at line 1084 of file lte-ue-rrc.h.
Referenced by EvaluateCellForSelection(), LeaveConnectedMode(), MeasurementReportTriggering(), SaveUeMeasurements(), SendMeasurementReport(), and SynchronizeToStrongestCell().
m_storedMeasValuesPerCarrier
std::map<uint16_t, std::map <uint8_t, MeasValues> > ns3::LteUeRrc::m_storedMeasValuesPerCarrier private
Stored measure values per carrier.
Definition at line 1089 of file lte-ue-rrc.h.
m_storedScellMeasValues
std::map<uint16_t, MeasValues> ns3::LteUeRrc::m_storedScellMeasValues private
Internal storage of the latest measurement results from all detected detected Secondary carrier component, indexed by the carrier component ID where the measurement was taken from.
Each measurement result comprises of RSRP (in dBm) and RSRQ (in dB).
In IDLE mode, the measurement results are used by the initial cell selection procedure. While in CONNECTED mode, layer-3 filtering is applied to the measurement results and they are used by UE measurements function:
LteUeRrc::MeasurementReportTriggering: in this case it is not set any measurement related to secondary carrier components since the A6 event is not implemented
LteUeRrc::SendMeasurementReport: in this case the report are sent.
Definition at line 1107 of file lte-ue-rrc.h.
Referenced by SaveScellUeMeasurements(), and SendMeasurementReport().
m_t300
Time ns3::LteUeRrc::m_t300 private
The T300 attribute.
Timer for RRC connection establishment procedure (i.e., the procedure is deemed as failed if it takes longer than this). See Section 7.3 of 3GPP TS 36.331.
Definition at line 1229 of file lte-ue-rrc.h.
Referenced by DoNotifyRandomAccessSuccessful(), and GetTypeId().
m_t310
Time ns3::LteUeRrc::m_t310 private
The 'T310' attribute.
After detecting N310 out-of-sync indications, if number of in-sync indications detected is less than N311 before this time, then the radio link is considered to have failed and the UE transitions to state CONNECTED_PHY_PROMLEM and eventually IDLE_START and UE context at eNodeB is destroyed. RRC connection re-establishment is not initiated after this time. See 3GPP TS 36.331 7.3.
Definition at line 1251 of file lte-ue-rrc.h.
Referenced by DoNotifyOutOfSync(), and GetTypeId().
m_ulBandwidth
uint16_t ns3::LteUeRrc::m_ulBandwidth private
Uplink bandwidth in RBs.
Definition at line 826 of file lte-ue-rrc.h.
Referenced by DoRecvSystemInformation(), and GetUlBandwidth().
m_ulEarfcn
uint32_t ns3::LteUeRrc::m_ulEarfcn private
Uplink carrier frequency.
Definition at line 829 of file lte-ue-rrc.h.
Referenced by DoRecvSystemInformation(), and GetUlEarfcn().
m_useRlcSm
bool ns3::LteUeRrc::m_useRlcSm private
True if RLC SM is to be used, false if RLC UM/AM are to be used.
Can be modified using SetUseRlcSm().
Definition at line 819 of file lte-ue-rrc.h.
Referenced by ApplyRadioResourceConfigDedicated(), and SetUseRlcSm().
m_varMeasConfig
VarMeasConfig ns3::LteUeRrc::m_varMeasConfig private
Includes the accumulated configuration of the measurements to be performed by the UE.
Based on 3GPP TS 36.331 section 7.1.
Definition at line 979 of file lte-ue-rrc.h.
Referenced by ApplyMeasConfig(), DoNotifyRandomAccessSuccessful(), DoReportUeMeasurements(), LeaveConnectedMode(), MeasurementReportTriggering(), SaveScellUeMeasurements(), SaveUeMeasurements(), and SendMeasurementReport().
m_varMeasReportList
std::map<uint8_t, VarMeasReport> ns3::LteUeRrc::m_varMeasReportList private
The list of active reporting entries, indexed by the measurement identity which triggered the reporting.
Includes information about measurements for which the triggering conditions have been met.
Definition at line 1001 of file lte-ue-rrc.h.
Referenced by ApplyMeasConfig(), MeasurementReportTriggering(), SendMeasurementReport(), VarMeasReportListAdd(), VarMeasReportListClear(), and VarMeasReportListErase().
The documentation for this class was generated from the following files:
src/lte/model/lte-ue-rrc.h
src/lte/model/lte-ue-rrc.cc