ns-3: LenaPssFfMacSchedulerTestCase2 Class Reference
LenaPssFfMacSchedulerTestCase2 Class Reference
LTE Models » lte module tests | Test suites
Simillar to the LenaPssFfMacSchedulerTestCase1 with the difference that UEs are places in such a way to experience different SINRs.
#include "lte-test-pss-ff-mac-scheduler.h"
Public Member Functions
LenaPssFfMacSchedulerTestCase2 (std::vector< double > dist, std::vector< uint32_t > estThrPssDl, std::vector< uint16_t > packetSize, uint16_t interval, bool errorModelEnabled)
Constructor.
virtual ~LenaPssFfMacSchedulerTestCase2 ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Static Private Member Functions
static std::string BuildNameString (uint16_t nUser, std::vector< double > dist)
Builds the test name string based on provided parameter values.
Private Attributes
std::vector< double > m_dist
the distance between nodes
bool m_errorModelEnabled
indicates whether the error model is enabled
std::vector< uint32_t > m_estThrPssDl
the DL estimated throughput PSS
uint16_t m_interval
the interval time in ms
uint16_t m_nUser
number of UE nodes
std::vector< uint16_t > m_packetSize
the packet size in bytes
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Simillar to the LenaPssFfMacSchedulerTestCase1 with the difference that UEs are places in such a way to experience different SINRs.
Test checks if the achieved throughput in such conditions has expected value.
Definition at line 89 of file lte-test-pss-ff-mac-scheduler.h.
Constructor & Destructor Documentation
LenaPssFfMacSchedulerTestCase2()
LenaPssFfMacSchedulerTestCase2::LenaPssFfMacSchedulerTestCase2 (std::vector< double > dist, std::vector< uint32_t > estThrPssDl, std::vector< uint16_t > packetSize, uint16_t interval, bool errorModelEnabled)
Constructor.
Parameters
dist the distance between nodes
estThrPssDl the estimated DL throughput PSS
packetSize the packet size
interval the interval time
errorModelEnabled if true the error model is enabled
Definition at line 501 of file lte-test-pss-ff-mac-scheduler.cc.
~LenaPssFfMacSchedulerTestCase2()
LenaPssFfMacSchedulerTestCase2::~LenaPssFfMacSchedulerTestCase2 () virtual
Definition at line 512 of file lte-test-pss-ff-mac-scheduler.cc.
Member Function Documentation
BuildNameString()
std::string LenaPssFfMacSchedulerTestCase2::BuildNameString (uint16_t nUser, std::vector< double > dist) static private
Builds the test name string based on provided parameter values.
Parameters
nUser the number of UE nodes
dist the distnace between nodes
Returns
the name string
Definition at line 488 of file lte-test-pss-ff-mac-scheduler.cc.
DoRun()
void LenaPssFfMacSchedulerTestCase2::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Check that the downlink assignment is done in a "token bank fair queue" manner
Implements ns3::TestCase.
Definition at line 517 of file lte-test-pss-ff-mac-scheduler.cc.
References ns3::LteHelper::ActivateDedicatedEpsBearer(), ns3::Ipv4AddressHelper::Assign(), ns3::NoBackhaulEpcHelper::AssignUeIpv4Address(), ns3::LteHelper::Attach(), first::clientApps, ns3::NodeContainer::Create(), ns3::TestCase::CreateTempDirFilename(), ns3::LteHelper::EnableRlcTraces(), ns3::GbrQosInformation::gbrDl, ns3::GbrQosInformation::gbrUl, ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::NodeContainer::GetN(), ns3::Object::GetObject(), ns3::NoBackhaulEpcHelper::GetPgwNode(), ns3::LteEnbNetDevice::GetPhy(), ns3::LteHelper::GetRlcStats(), ns3::Ipv4StaticRoutingHelper::GetStaticRouting(), ns3::NoBackhaulEpcHelper::GetUeDefaultGatewayAddress(), ns3::UdpClientHelper::Install(), ns3::PointToPointHelper::Install(), ns3::PacketSinkHelper::Install(), ns3::InternetStackHelper::Install(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), m_dist, m_errorModelEnabled, m_estThrPssDl, m_interval, m_nUser, m_packetSize, ns3::GbrQosInformation::mbrDl, ns3::GbrQosInformation::mbrUl, ns3::MilliSeconds(), third::mobility, NS_LOG_INFO, NS_TEST_ASSERT_MSG_EQ_TOL, ns3::Seconds(), first::serverApps, ns3::UdpClientHelper::SetAttribute(), ns3::ObjectBase::SetAttribute(), ns3::Ipv4AddressHelper::SetBase(), ns3::PointToPointHelper::SetChannelAttribute(), ns3::Config::SetDefault(), ns3::PointToPointHelper::SetDeviceAttribute(), ns3::LteHelper::SetEpcHelper(), ns3::LteHelper::SetSchedulerAttribute(), and ns3::LteHelper::SetSchedulerType().
Member Data Documentation
m_dist
std::vector<double> LenaPssFfMacSchedulerTestCase2::m_dist private
the distance between nodes
Definition at line 114 of file lte-test-pss-ff-mac-scheduler.h.
Referenced by DoRun().
m_errorModelEnabled
bool LenaPssFfMacSchedulerTestCase2::m_errorModelEnabled private
indicates whether the error model is enabled
Definition at line 118 of file lte-test-pss-ff-mac-scheduler.h.
Referenced by DoRun().
m_estThrPssDl
std::vector<uint32_t> LenaPssFfMacSchedulerTestCase2::m_estThrPssDl private
the DL estimated throughput PSS
Definition at line 117 of file lte-test-pss-ff-mac-scheduler.h.
Referenced by DoRun().
m_interval
uint16_t LenaPssFfMacSchedulerTestCase2::m_interval private
the interval time in ms
Definition at line 116 of file lte-test-pss-ff-mac-scheduler.h.
Referenced by DoRun().
m_nUser
uint16_t LenaPssFfMacSchedulerTestCase2::m_nUser private
number of UE nodes
Definition at line 113 of file lte-test-pss-ff-mac-scheduler.h.
Referenced by DoRun().
m_packetSize
std::vector<uint16_t> LenaPssFfMacSchedulerTestCase2::m_packetSize private
the packet size in bytes
Definition at line 115 of file lte-test-pss-ff-mac-scheduler.h.
Referenced by DoRun().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-pss-ff-mac-scheduler.h
src/lte/test/lte-test-pss-ff-mac-scheduler.cc