ns-3: ns3::TcpRateLinux Class Reference
ns3::TcpRateLinux Class Reference
Linux management and generation of Rate information for TCP.
#include "tcp-rate-ops.h"
Public Types
typedef void(* TcpRateSampleUpdated) (const TcpRateSample &sample)
TracedCallback signature for tcp rate sample update events.
typedef void(* TcpRateUpdated) (const TcpRateConnection &rate)
TracedCallback signature for tcp rate update events.
Public Member Functions
virtual ~TcpRateLinux () override
virtual void CalculateAppLimited (uint32_t cWnd, uint32_t in_flight, uint32_t segmentSize, const SequenceNumber32 &tailSeq, const SequenceNumber32 &nextTx, const uint32_t lostOut, const uint32_t retransOut) override
If a gap is detected between sends, it means we are app-limited.
virtual const TcpRateSample & GenerateSample (uint32_t delivered, uint32_t lost, bool is_sack_reneg, uint32_t priorInFlight, const Time &minRtt) override
Generate a TcpRateSample to feed a congestion avoidance algorithm.
virtual const TcpRateConnection & GetConnectionRate () override
virtual void SkbDelivered (TcpTxItem *skb) override
Update the Rate information after an item is received.
virtual void SkbSent (TcpTxItem *skb, bool isStartOfTransmission) override
Put the rate information inside the sent skb.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpRateOps
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
TcpRateConnection m_rate
Rate information.
TcpRateSample m_rateSample
Rate sample (continuosly updated)
TracedCallback< const TcpRateSample & > m_rateSampleTrace
Rate Sample trace.
TracedCallback< const TcpRateConnection & > m_rateTrace
Rate trace.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Linux management and generation of Rate information for TCP.
Introspection did not find any typical Config paths.
This class is inspired by what Linux is performing in tcp_rate.c
No Attributes are defined for this type.
TraceSources
TcpRateUpdated: Tcp rate information has been updated
Callback signature: ns3::TcpRateLinux::TcpRateUpdated
TcpRateSampleUpdated: Tcp rate sample has been updated
Callback signature: ns3::TcpRateLinux::TcpRateSampleUpdated
Size of this type is 208 bytes (on a 64-bit architecture).
Definition at line 179 of file tcp-rate-ops.h.
Member Typedef Documentation
TcpRateSampleUpdated
typedef void(* ns3::TcpRateLinux::TcpRateSampleUpdated) (const TcpRateSample &sample)
TracedCallback signature for tcp rate sample update events.
The callback will be fired each time the rate sample is updated.
Parameters
[in] sample The rate sample that will be passed to congestion control algorithms.
Definition at line 223 of file tcp-rate-ops.h.
TcpRateUpdated
typedef void(* ns3::TcpRateLinux::TcpRateUpdated) (const TcpRateConnection &rate)
TracedCallback signature for tcp rate update events.
The callback will be fired each time the rate is updated.
Parameters
[in] rate The rate information.
Definition at line 213 of file tcp-rate-ops.h.
Constructor & Destructor Documentation
~TcpRateLinux()
virtual ns3::TcpRateLinux::~TcpRateLinux () inline override virtual
Definition at line 188 of file tcp-rate-ops.h.
Member Function Documentation
CalculateAppLimited()
void ns3::TcpRateLinux::CalculateAppLimited (uint32_t cWnd, uint32_t in_flight, uint32_t segmentSize, const SequenceNumber32 & tailSeq, const SequenceNumber32 & nextTx, const uint32_t lostOut, const uint32_t retransOut) override virtual
If a gap is detected between sends, it means we are app-limited.
Returns
TODO What the Linux kernel is setting in tp->app_limited? https://elixir.bootlin.com/linux/latest/source/net/ipv4/tcp_rate.c#L177
Parameters
cWnd Congestion Window
in_flight In Flight size (in bytes)
segmentSize Segment size
tailSeq Tail Sequence
nextTx NextTx
lostOut Number of lost bytes
retransOut Number of retransmitted bytes
Implements ns3::TcpRateOps.
Definition at line 138 of file tcp-rate-ops.cc.
References ns3::TcpRateOps::TcpRateConnection::m_appLimited, ns3::TcpRateOps::TcpRateConnection::m_delivered, m_rate, m_rateTrace, NS_LOG_FUNCTION, and segmentSize.
Referenced by TcpRateLinuxBasicTest::SendSkb().
GenerateSample()
const TcpRateOps::TcpRateSample & ns3::TcpRateLinux::GenerateSample (uint32_t delivered, uint32_t lost, bool is_sack_reneg, uint32_t priorInFlight, const Time & minRtt) override virtual
Generate a TcpRateSample to feed a congestion avoidance algorithm.
This function will be called after an ACK (or a SACK) is received. The (S)ACK carries some implicit information, such as how many segments have been lost or delivered. These values will be this function input.
Parameters
delivered number of delivered segments (e.g., receiving a cumulative ACK means having more than 1 segment delivered) relative to the most recent (S)ACK received
lost number of segments that we detected as lost after the reception of the most recent (S)ACK
is_sack_reneg Is SACK reneged?
minRtt Minimum RTT so far
Returns
The TcpRateSample that will be used for CA
Implements ns3::TcpRateOps.
Definition at line 59 of file tcp-rate-ops.cc.
References ns3::Time::GetSeconds(), ns3::TcpRateOps::TcpRateSample::m_ackedSacked, ns3::TcpRateOps::TcpRateSample::m_ackElapsed, ns3::TcpRateOps::TcpRateConnection::m_appLimited, ns3::TcpRateOps::TcpRateSample::m_bytesLoss, ns3::TcpRateOps::TcpRateSample::m_delivered, ns3::TcpRateOps::TcpRateConnection::m_delivered, ns3::TcpRateOps::TcpRateSample::m_deliveryRate, ns3::TcpRateOps::TcpRateSample::m_interval, ns3::TcpRateOps::TcpRateSample::m_isAppLimited, ns3::TcpRateOps::TcpRateSample::m_priorDelivered, ns3::TcpRateOps::TcpRateSample::m_priorInFlight, ns3::TcpRateOps::TcpRateSample::m_priorTime, m_rate, ns3::TcpRateOps::TcpRateConnection::m_rateAppLimited, ns3::TcpRateOps::TcpRateConnection::m_rateDelivered, ns3::TcpRateOps::TcpRateConnection::m_rateInterval, m_rateSample, m_rateSampleTrace, ns3::TcpRateOps::TcpRateSample::m_sendElapsed, max, NS_LOG_FUNCTION, NS_LOG_INFO, and ns3::Seconds().
GetConnectionRate()
virtual const TcpRateConnection& ns3::TcpRateLinux::GetConnectionRate () inline override virtual
Returns
The information about the rate connection
Implements ns3::TcpRateOps.
Definition at line 201 of file tcp-rate-ops.h.
References m_rate.
GetTypeId()
TypeId ns3::TcpRateLinux::GetTypeId (void) static
Get the type ID.
Get the type ID.
Returns
the object TypeId
Definition at line 41 of file tcp-rate-ops.cc.
References m_rateSampleTrace, m_rateTrace, ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
SkbDelivered()
void ns3::TcpRateLinux::SkbDelivered (TcpTxItem * skb) override virtual
Update the Rate information after an item is received.
When an skb is sacked or acked, we fill in the rate sample with the (prior) delivery information when the skb was last transmitted.
If an ACK (s)acks multiple skbs (e.g., stretched-acks), this function is called multiple times. We favor the information from the most recently sent skb, i.e., the skb with the highest prior_delivered count.
Parameters
skb The SKB delivered ((s)ACKed)
Implements ns3::TcpRateOps.
Definition at line 164 of file tcp-rate-ops.cc.
References ns3::TcpTxItem::GetLastSent(), ns3::TcpTxItem::GetRateInformation(), ns3::TcpTxItem::GetSeqSize(), ns3::TcpRateOps::TcpRateSample::m_ackElapsed, ns3::TcpRateOps::TcpRateConnection::m_delivered, ns3::TcpTxItem::RateInformation::m_delivered, ns3::TcpRateOps::TcpRateConnection::m_deliveredTime, ns3::TcpTxItem::RateInformation::m_deliveredTime, ns3::TcpTxItem::RateInformation::m_firstSent, ns3::TcpRateOps::TcpRateConnection::m_firstSentTime, ns3::TcpRateOps::TcpRateSample::m_isAppLimited, ns3::TcpTxItem::RateInformation::m_isAppLimited, ns3::TcpRateOps::TcpRateSample::m_priorDelivered, ns3::TcpRateOps::TcpRateSample::m_priorTime, m_rate, m_rateSample, m_rateSampleTrace, m_rateTrace, ns3::TcpRateOps::TcpRateSample::m_sendElapsed, ns3::TcpRateOps::TcpRateConnection::m_txItemDelivered, ns3::Time::Max(), ns3::Simulator::Now(), and NS_LOG_FUNCTION.
Referenced by TcpRateLinuxBasicTest::SkbDelivered().
SkbSent()
void ns3::TcpRateLinux::SkbSent (TcpTxItem * skb, bool isStartOfTransmission) override virtual
Put the rate information inside the sent skb.
Snapshot the current delivery information in the skb, to generate a rate sample later when the skb is (s)acked in SkbDelivered ().
Parameters
skb The SKB sent
isStartOfTransmission true if this is a start of transmission (i.e., in_flight == 0)
Implements ns3::TcpRateOps.
Definition at line 201 of file tcp-rate-ops.cc.
References ns3::TcpTxItem::GetRateInformation(), ns3::TcpRateOps::TcpRateConnection::m_appLimited, ns3::TcpRateOps::TcpRateConnection::m_delivered, ns3::TcpTxItem::RateInformation::m_delivered, ns3::TcpRateOps::TcpRateConnection::m_deliveredTime, ns3::TcpTxItem::RateInformation::m_deliveredTime, ns3::TcpTxItem::RateInformation::m_firstSent, ns3::TcpRateOps::TcpRateConnection::m_firstSentTime, ns3::TcpTxItem::RateInformation::m_isAppLimited, m_rate, m_rateTrace, ns3::Simulator::Now(), NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by TcpRateLinuxBasicTest::SendSkb().
Member Data Documentation
m_rate
TcpRateConnection ns3::TcpRateLinux::m_rate private
Rate information.
Definition at line 227 of file tcp-rate-ops.h.
Referenced by CalculateAppLimited(), GenerateSample(), GetConnectionRate(), SkbDelivered(), and SkbSent().
m_rateSample
TcpRateSample ns3::TcpRateLinux::m_rateSample private
Rate sample (continuosly updated)
Definition at line 228 of file tcp-rate-ops.h.
Referenced by GenerateSample(), and SkbDelivered().
m_rateSampleTrace
TracedCallback<const TcpRateSample &> ns3::TcpRateLinux::m_rateSampleTrace private
Rate Sample trace.
Definition at line 231 of file tcp-rate-ops.h.
Referenced by GenerateSample(), GetTypeId(), and SkbDelivered().
m_rateTrace
TracedCallback<const TcpRateConnection &> ns3::TcpRateLinux::m_rateTrace private
Rate trace.
Definition at line 230 of file tcp-rate-ops.h.
Referenced by CalculateAppLimited(), GetTypeId(), SkbDelivered(), and SkbSent().
The documentation for this class was generated from the following files:
src/internet/model/tcp-rate-ops.h
src/internet/model/tcp-rate-ops.cc