ns-3: ns3::OhBuildingsPropagationLossModel Class Reference
ns3::OhBuildingsPropagationLossModel Class Reference
Propagation Models
this model combines the OkumuraHata model with the BuildingsPropagationLossModel
#include "oh-buildings-propagation-loss-model.h"
Public Member Functions
OhBuildingsPropagationLossModel ()
~OhBuildingsPropagationLossModel ()
virtual double GetLoss (Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Public Member Functions inherited from ns3::BuildingsPropagationLossModel
BuildingsPropagationLossModel ()
virtual double DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account only the particular PropagationLossModel.
Public Member Functions inherited from ns3::PropagationLossModel
PropagationLossModel ()
virtual ~PropagationLossModel ()
int64_t AssignStreams (int64_t stream)
If this loss model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
double CalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account all the PropagationLossModel(s) chained to the current one.
Ptr< PropagationLossModel > GetNext ()
Gets the next PropagationLossModel in the chain of loss models that act on the signal.
void SetNext (Ptr< PropagationLossModel > next)
Enables a chain of loss models to act on the signal.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::BuildingsPropagationLossModel
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::PropagationLossModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Ptr< OkumuraHataPropagationLossModel > m_okumuraHata
Additional Inherited Members
Protected Member Functions inherited from ns3::BuildingsPropagationLossModel
virtual int64_t DoAssignStreams (int64_t stream)
Subclasses must implement this; those not using random variables can return zero.
double EvaluateSigma (Ptr< MobilityBuildingInfo > a, Ptr< MobilityBuildingInfo > b) const
double ExternalWallLoss (Ptr< MobilityBuildingInfo > a) const
double GetShadowing (Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
double HeightLoss (Ptr< MobilityBuildingInfo > n) const
double InternalWallsLoss (Ptr< MobilityBuildingInfo > a, Ptr< MobilityBuildingInfo > b) const
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::BuildingsPropagationLossModel
double m_lossInternalWall
Ptr< NormalRandomVariable > m_randVariable
std::map< Ptr< MobilityModel >, std::map< Ptr< MobilityModel >, ShadowingLoss > > m_shadowingLossMap
double m_shadowingSigmaExtWalls
double m_shadowingSigmaIndoor
double m_shadowingSigmaOutdoor
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
this model combines the OkumuraHata model with the BuildingsPropagationLossModel
Warning
This model works with MobilityBuildingInfo only
Config Paths
ns3::OhBuildingsPropagationLossModel is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::SpectrumChannel/PropagationLossModel/$ns3::BuildingsPropagationLossModel/$ns3::OhBuildingsPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::SpectrumChannel/PropagationLossModel/$ns3::OhBuildingsPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::YansWifiChannel/PropagationLossModel/$ns3::BuildingsPropagationLossModel/$ns3::OhBuildingsPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::YansWifiChannel/PropagationLossModel/$ns3::OhBuildingsPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::LrWpanNetDevice/Channel/PropagationLossModel/$ns3::BuildingsPropagationLossModel/$ns3::OhBuildingsPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::LrWpanNetDevice/Channel/PropagationLossModel/$ns3::OhBuildingsPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::SpectrumChannel/PropagationLossModel/$ns3::BuildingsPropagationLossModel/$ns3::OhBuildingsPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::SpectrumChannel/PropagationLossModel/$ns3::OhBuildingsPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::YansWifiChannel/PropagationLossModel/$ns3::BuildingsPropagationLossModel/$ns3::OhBuildingsPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::YansWifiChannel/PropagationLossModel/$ns3::OhBuildingsPropagationLossModel"
"/ChannelList/[i]/$ns3::SpectrumChannel/PropagationLossModel/$ns3::BuildingsPropagationLossModel/$ns3::OhBuildingsPropagationLossModel"
"/ChannelList/[i]/$ns3::SpectrumChannel/PropagationLossModel/$ns3::OhBuildingsPropagationLossModel"
"/ChannelList/[i]/$ns3::YansWifiChannel/PropagationLossModel/$ns3::BuildingsPropagationLossModel/$ns3::OhBuildingsPropagationLossModel"
"/ChannelList/[i]/$ns3::YansWifiChannel/PropagationLossModel/$ns3::OhBuildingsPropagationLossModel"
No Attributes are defined for this type.
Attributes defined in parent class ns3::BuildingsPropagationLossModel
ShadowSigmaOutdoor: Standard deviation of the normal distribution used for calculate the shadowing for outdoor nodes
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 7
Flags: construct write read
ShadowSigmaIndoor: Standard deviation of the normal distribution used for calculate the shadowing for indoor nodes
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 8
Flags: construct write read
ShadowSigmaExtWalls: Standard deviation of the normal distribution used for calculate the shadowing due to ext walls
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 5
Flags: construct write read
InternalWallLoss: Additional loss for each internal wall [dB]
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 5
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 112 bytes (on a 64-bit architecture).
Definition at line 39 of file oh-buildings-propagation-loss-model.h.
Constructor & Destructor Documentation
OhBuildingsPropagationLossModel()
ns3::OhBuildingsPropagationLossModel::OhBuildingsPropagationLossModel ()
Definition at line 42 of file oh-buildings-propagation-loss-model.cc.
References m_okumuraHata.
~OhBuildingsPropagationLossModel()
ns3::OhBuildingsPropagationLossModel::~OhBuildingsPropagationLossModel ()
Definition at line 47 of file oh-buildings-propagation-loss-model.cc.
Member Function Documentation
GetLoss()
double ns3::OhBuildingsPropagationLossModel::GetLoss (Ptr< MobilityModel > a, Ptr< MobilityModel > b) const virtual
Parameters
a the mobility model of the source
b the mobility model of the destination
Returns
the propagation loss (in dBm)
Implements ns3::BuildingsPropagationLossModel.
Definition at line 66 of file oh-buildings-propagation-loss-model.cc.
References ns3::BuildingsPropagationLossModel::ExternalWallLoss(), ns3::Object::GetObject(), ns3::BuildingsPropagationLossModel::InternalWallsLoss(), m_okumuraHata, max, NS_ASSERT_MSG, NS_LOG_FUNCTION, and NS_LOG_INFO.
GetTypeId()
TypeId ns3::OhBuildingsPropagationLossModel::GetTypeId (void) static
Definition at line 52 of file oh-buildings-propagation-loss-model.cc.
References ns3::TypeId::SetParent().
Member Data Documentation
m_okumuraHata
Ptr<OkumuraHataPropagationLossModel> ns3::OhBuildingsPropagationLossModel::m_okumuraHata private
Definition at line 56 of file oh-buildings-propagation-loss-model.h.
Referenced by OhBuildingsPropagationLossModel(), and GetLoss().
The documentation for this class was generated from the following files:
src/buildings/model/oh-buildings-propagation-loss-model.h
src/buildings/model/oh-buildings-propagation-loss-model.cc