ns-3: ns3::NoBackhaulEpcHelper Class Reference
ns3::NoBackhaulEpcHelper Class Reference
LTE Models
Create an EPC network with PointToPoint links between the core network nodes.
#include "no-backhaul-epc-helper.h"
Public Member Functions
NoBackhaulEpcHelper ()
Constructor.
virtual ~NoBackhaulEpcHelper ()
Destructor.
virtual uint8_t ActivateEpsBearer (Ptr< NetDevice > ueLteDevice, uint64_t imsi, Ptr< EpcTft > tft, EpsBearer bearer)
Activate an EPS bearer, setting up the corresponding S1-U tunnel.
virtual void AddEnb (Ptr< Node > enbNode, Ptr< NetDevice > lteEnbNetDevice, uint16_t cellId)
Add an eNB to the EPC.
virtual void AddS1Interface (Ptr< Node > enb, Ipv4Address enbAddress, Ipv4Address sgwAddress, uint16_t cellId=0)
Add an S1 interface between an eNB and a SGW.
virtual void AddUe (Ptr< NetDevice > ueLteDevice, uint64_t imsi)
Notify the EPC of the existence of a new UE which might attach at a later time.
virtual void AddX2Interface (Ptr< Node > enbNode1, Ptr< Node > enbNode2)
Add an X2 interface between two eNB.
virtual Ipv4InterfaceContainer AssignUeIpv4Address (NetDeviceContainer ueDevices)
Assign IPv4 addresses to UE devices.
virtual Ipv6InterfaceContainer AssignUeIpv6Address (NetDeviceContainer ueDevices)
Assign IPv6 addresses to UE devices.
virtual void DoDispose ()
Destructor implementation.
TypeId GetInstanceTypeId () const
Get the most derived TypeId for this Object.
virtual Ptr< Node > GetPgwNode () const
Get the PGW node.
virtual Ptr< Node > GetSgwNode () const
Get the SGW node.
virtual Ipv4Address GetUeDefaultGatewayAddress ()
virtual Ipv6Address GetUeDefaultGatewayAddress6 ()
Public Member Functions inherited from ns3::EpcHelper
EpcHelper ()
Constructor.
virtual ~EpcHelper ()
Destructor.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::EpcHelper
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoActivateEpsBearerForUe (const Ptr< NetDevice > &ueDevice, const Ptr< EpcTft > &tft, const EpsBearer &bearer) const
DoActivateEpsBearerForUe: Schedule ActivateEpsBearer on the UE.
virtual void DoAddX2Interface (const Ptr< EpcX2 > &enb1X2, const Ptr< NetDevice > &enb1LteDev, const Ipv4Address &enb1X2Address, const Ptr< EpcX2 > &enb2X2, const Ptr< NetDevice > &enb2LteDev, const Ipv4Address &enb2X2Address) const
DoAddX2Interface: Call AddX2Interface on top of the Enb device pointers.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Attributes
uint16_t m_gtpcUdpPort
UDP port where the GTPv2-C Socket is bound, fixed by the standard as 2123.
uint16_t m_gtpuUdpPort
UDP port where the GTP-U Socket is bound, fixed by the standard as 2152.
std::map< uint64_t, Ptr< NetDevice > > m_imsiEnbDeviceMap
Map storing for each IMSI the corresponding eNB NetDevice.
Ptr< Node > m_mme
MME network element.
Ptr< EpcMmeApplication > m_mmeApp
MME application.
Ptr< Node > m_pgw
PGW network element.
Ptr< EpcPgwApplication > m_pgwApp
PGW application.
Ipv4AddressHelper m_s11Ipv4AddressHelper
Helper to assign addresses to S11 NetDevices.
DataRate m_s11LinkDataRate
The data rate to be used for the next S11 link to be created.
Time m_s11LinkDelay
The delay to be used for the next S11 link to be created.
uint16_t m_s11LinkMtu
The MTU of the next S11 link to be created.
Ipv4AddressHelper m_s5Ipv4AddressHelper
S5 interfaces.
DataRate m_s5LinkDataRate
The data rate to be used for the next S5 link to be created.
Time m_s5LinkDelay
The delay to be used for the next S5 link to be created.
uint16_t m_s5LinkMtu
The MTU of the next S5 link to be created.
Ptr< Node > m_sgw
SGW network element.
Ptr< EpcSgwApplication > m_sgwApp
SGW application.
Ptr< VirtualNetDevice > m_tunDevice
TUN device implementing tunneling of user data over GTP-U/UDP/IP.
Ipv4AddressHelper m_uePgwAddressHelper
helper to assign IPv4 addresses to UE devices as well as to the TUN device of the SGW/PGW
Ipv6AddressHelper m_uePgwAddressHelper6
helper to assign IPv6 addresses to UE devices as well as to the TUN device of the SGW/PGW
Ipv4AddressHelper m_x2Ipv4AddressHelper
helper to assign addresses to X2 NetDevices
DataRate m_x2LinkDataRate
The data rate to be used for the next X2 link to be created.
Time m_x2LinkDelay
The delay to be used for the next X2 link to be created.
bool m_x2LinkEnablePcap
Enable PCAP generation for X2 link.
uint16_t m_x2LinkMtu
The MTU of the next X2 link to be created.
std::string m_x2LinkPcapPrefix
Prefix for the PCAP file for the X2 link.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Create an EPC network with PointToPoint links between the core network nodes.
Introspection did not find any typical Config paths.
This Helper will create an EPC network topology comprising of three nodes: SGW, PGW and MME. The X2-U, X2-C, S5 and S11 interfaces are realized over PointToPoint links.
The S1 interface is not created. So, no backhaul network is built. You have to build your own backhaul network in the simulation program. Or you can use PointToPointEpcHelper or CsmaEpcHelper (instead of this NoBackhaulEpcHelper) to use reference backhaul networks.
Attributes
S5LinkDataRate: The data rate to be used for the next S5 link to be created
Set with class: DataRateValue
Underlying type: DataRate
Initial value: 10000000000bps
Flags: construct write read
S5LinkDelay: The delay to be used for the next S5 link to be created
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
S5LinkMtu: The MTU of the next S5 link to be created
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 2000
Flags: construct write read
S11LinkDataRate: The data rate to be used for the next S11 link to be created
Set with class: DataRateValue
Underlying type: DataRate
Initial value: 10000000000bps
Flags: construct write read
S11LinkDelay: The delay to be used for the next S11 link to be created
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
S11LinkMtu: The MTU of the next S11 link to be created.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 2000
Flags: construct write read
X2LinkDataRate: The data rate to be used for the next X2 link to be created
Set with class: DataRateValue
Underlying type: DataRate
Initial value: 10000000000bps
Flags: construct write read
X2LinkDelay: The delay to be used for the next X2 link to be created
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
X2LinkMtu: The MTU of the next X2 link to be created. Note that, because of some big X2 messages, you need a big MTU.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 3000
Flags: construct write read
X2LinkPcapPrefix: Prefix for Pcap generated by X2 link
Set with class: StringValue
Underlying type:
Initial value: x2
Flags: construct write read
X2LinkEnablePcap: Enable Pcap for X2 link
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 376 bytes (on a 64-bit architecture).
Definition at line 46 of file no-backhaul-epc-helper.h.
Constructor & Destructor Documentation
NoBackhaulEpcHelper()
ns3::NoBackhaulEpcHelper::NoBackhaulEpcHelper ()
Constructor.
Definition at line 49 of file no-backhaul-epc-helper.cc.
References ns3::NetDeviceContainer::Add(), ns3::Node::AddApplication(), ns3::Node::AddDevice(), ns3::Mac48Address::Allocate(), ns3::Ipv4AddressHelper::Assign(), AssignUeIpv4Address(), AssignUeIpv6Address(), ns3::Socket::Bind(), ns3::ObjectBase::ConstructSelf(), ns3::Socket::CreateSocket(), ns3::NetDeviceContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::Ipv4Address::GetAny(), ns3::Ipv4::GetNInterfaces(), ns3::Object::GetObject(), ns3::Ipv6StaticRoutingHelper::GetStaticRouting(), ns3::PointToPointHelper::Install(), ns3::InternetStackHelper::Install(), ns3::TypeId::LookupByName(), m_gtpcUdpPort, m_gtpuUdpPort, m_mme, m_mmeApp, m_pgw, m_pgwApp, m_s11Ipv4AddressHelper, m_s11LinkDataRate, m_s11LinkDelay, m_s11LinkMtu, m_s5Ipv4AddressHelper, m_s5LinkDataRate, m_s5LinkDelay, m_s5LinkMtu, m_sgw, m_sgwApp, m_tunDevice, m_uePgwAddressHelper, m_uePgwAddressHelper6, m_x2Ipv4AddressHelper, ns3::MakeCallback(), ns3::Ipv4AddressHelper::NewNetwork(), NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::EpcPgwApplication::RecvFromTunDevice(), ns3::VirtualNetDevice::SetAddress(), ns3::ObjectBase::SetAttribute(), ns3::Ipv4AddressHelper::SetBase(), ns3::Ipv6AddressHelper::SetBase(), ns3::PointToPointHelper::SetChannelAttribute(), ns3::Ipv6InterfaceContainer::SetDefaultRouteInAllNodes(), ns3::PointToPointHelper::SetDeviceAttribute(), ns3::Ipv6InterfaceContainer::SetForwarding(), and ns3::VirtualNetDevice::SetSendCallback().
~NoBackhaulEpcHelper()
ns3::NoBackhaulEpcHelper::~NoBackhaulEpcHelper () virtual
Destructor.
Definition at line 216 of file no-backhaul-epc-helper.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
ActivateEpsBearer()
uint8_t ns3::NoBackhaulEpcHelper::ActivateEpsBearer (Ptr< NetDevice > ueLteDevice, uint64_t imsi, Ptr< EpcTft > tft, EpsBearer bearer) virtual
Activate an EPS bearer, setting up the corresponding S1-U tunnel.
Parameters
ueLteDevice the Ipv4-enabled device of the UE, normally connected via the LTE radio interface
imsi the unique identifier of the UE
tft the Traffic Flow Template of the new bearer
bearer struct describing the characteristics of the EPS bearer to be activated
Returns
bearer ID
Implements ns3::EpcHelper.
Definition at line 439 of file no-backhaul-epc-helper.cc.
References DoActivateEpsBearerForUe(), ns3::Object::GetObject(), m_mmeApp, m_pgwApp, NS_ASSERT_MSG, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by EpcS1uDlTestCase::DoRun(), and EpcS1uUlTestCase::DoRun().
AddEnb()
void ns3::NoBackhaulEpcHelper::AddEnb (Ptr< Node > enbNode, Ptr< NetDevice > lteEnbNetDevice, uint16_t cellId) virtual
Add an eNB to the EPC.
Parameters
enbNode the previously created eNB node which is to be added to the EPC
lteEnbNetDevice the LteEnbNetDevice of the eNB node
cellId ID of the eNB
Implements ns3::EpcHelper.
Reimplemented in ns3::PointToPointEpcHelper, and ns3::EmuEpcHelper.
Definition at line 310 of file no-backhaul-epc-helper.cc.
References ns3::Node::AddApplication(), ns3::Object::AggregateObject(), ns3::Socket::Bind(), ns3::Socket::Connect(), ns3::Socket::CreateSocket(), ns3::Node::GetApplication(), ns3::Mac48Address::GetBroadcast(), ns3::Node::GetNApplications(), ns3::Ipv4::GetNInterfaces(), ns3::Object::GetObject(), ns3::InternetStackHelper::Install(), ns3::TypeId::LookupByName(), NS_ASSERT, NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, ns3::Ipv4L3Protocol::PROT_NUMBER, ns3::Ipv6L3Protocol::PROT_NUMBER, ns3::PacketSocketAddress::SetPhysicalAddress(), ns3::PacketSocketAddress::SetProtocol(), and ns3::PacketSocketAddress::SetSingleDevice().
Referenced by ns3::EmuEpcHelper::AddEnb(), and ns3::PointToPointEpcHelper::AddEnb().
AddS1Interface()
void ns3::NoBackhaulEpcHelper::AddS1Interface (Ptr< Node > enb, Ipv4Address enbAddress, Ipv4Address sgwAddress, uint16_t cellId = 0) virtual
Add an S1 interface between an eNB and a SGW.
Parameters
enb eNB peer of the S1 interface
enbAddress eNB IPv4 address of the S1 interface
sgwAddress SGW IPv4 address of the S1 interface
cellId cellId of the eNB
Implements ns3::EpcHelper.
Definition at line 545 of file no-backhaul-epc-helper.cc.
References ns3::Socket::Bind(), ns3::Socket::CreateSocket(), ns3::Node::GetApplication(), ns3::LteEnbNetDevice::GetCellId(), ns3::Node::GetDevice(), ns3::Object::GetObject(), ns3::TypeId::LookupByName(), m_gtpuUdpPort, m_mmeApp, m_sgwApp, NS_ASSERT, NS_ASSERT_MSG, NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by ns3::EmuEpcHelper::AddEnb(), and ns3::PointToPointEpcHelper::AddEnb().
AddUe()
void ns3::NoBackhaulEpcHelper::AddUe (Ptr< NetDevice > ueLteDevice, uint64_t imsi) virtual
Notify the EPC of the existence of a new UE which might attach at a later time.
Parameters
ueLteDevice the UE device to be attached
imsi the unique identifier of the UE
Implements ns3::EpcHelper.
Definition at line 430 of file no-backhaul-epc-helper.cc.
References m_mmeApp, m_pgwApp, and NS_LOG_FUNCTION.
Referenced by EpcS1uDlTestCase::DoRun(), and EpcS1uUlTestCase::DoRun().
AddX2Interface()
void ns3::NoBackhaulEpcHelper::AddX2Interface (Ptr< Node > enbNode1, Ptr< Node > enbNode2) virtual
Add an X2 interface between two eNB.
Parameters
enbNode1 one eNB peer of the X2 interface
enbNode2 the other eNB peer of the X2 interface
Implements ns3::EpcHelper.
Reimplemented in ns3::EmuEpcHelper.
Definition at line 364 of file no-backhaul-epc-helper.cc.
References ns3::Ipv4AddressHelper::Assign(), DoAddX2Interface(), ns3::PcapHelperForDevice::EnablePcapAll(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::Node::GetDevice(), ns3::Ipv4::GetNInterfaces(), ns3::Object::GetObject(), ns3::PointToPointHelper::Install(), m_x2Ipv4AddressHelper, m_x2LinkDataRate, m_x2LinkDelay, m_x2LinkEnablePcap, m_x2LinkMtu, m_x2LinkPcapPrefix, ns3::Ipv4AddressHelper::NewNetwork(), NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::PointToPointHelper::SetChannelAttribute(), and ns3::PointToPointHelper::SetDeviceAttribute().
AssignUeIpv4Address()
Ipv4InterfaceContainer ns3::NoBackhaulEpcHelper::AssignUeIpv4Address (NetDeviceContainer ueDevices) virtual
Assign IPv4 addresses to UE devices.
Parameters
ueDevices the set of UE devices
Returns
the interface container,
See also
Ipv4AddressHelper::Assign() which has similar semantics
Implements ns3::EpcHelper.
Definition at line 504 of file no-backhaul-epc-helper.cc.
References ns3::Ipv4AddressHelper::Assign(), and m_uePgwAddressHelper.
Referenced by NoBackhaulEpcHelper(), LteCellSelectionTestCase::DoRun(), LteRadioLinkFailureTestCase::DoRun(), LteUeMeasurementsHandoverTestCase::DoRun(), LteHandoverTargetTestCase::DoRun(), EpcS1uDlTestCase::DoRun(), EpcS1uUlTestCase::DoRun(), LenaCqaFfMacSchedulerTestCase1::DoRun(), LenaCqaFfMacSchedulerTestCase2::DoRun(), ns3::LenaDeactivateBearerTestCase::DoRun(), LenaFdTbfqFfMacSchedulerTestCase1::DoRun(), LenaFdTbfqFfMacSchedulerTestCase2::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LenaPssFfMacSchedulerTestCase1::DoRun(), LenaPssFfMacSchedulerTestCase2::DoRun(), LenaTdTbfqFfMacSchedulerTestCase1::DoRun(), LenaTdTbfqFfMacSchedulerTestCase2::DoRun(), LteEpcE2eDataTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), and LteX2HandoverTestCase::DoRun().
AssignUeIpv6Address()
Ipv6InterfaceContainer ns3::NoBackhaulEpcHelper::AssignUeIpv6Address (NetDeviceContainer ueDevices) virtual
Assign IPv6 addresses to UE devices.
Parameters
ueDevices the set of UE devices
Returns
the interface container,
See also
Ipv6AddressHelper::Assign() which has similar semantics
Implements ns3::EpcHelper.
Definition at line 510 of file no-backhaul-epc-helper.cc.
References ns3::Ipv6AddressHelper::Assign(), ns3::NetDeviceContainer::Begin(), ns3::NetDeviceContainer::End(), and m_uePgwAddressHelper6.
Referenced by NoBackhaulEpcHelper(), and LteIpv6RoutingTestCase::DoRun().
DoActivateEpsBearerForUe()
void ns3::NoBackhaulEpcHelper::DoActivateEpsBearerForUe (const Ptr< NetDevice > & ueDevice, const Ptr< EpcTft > & tft, const EpsBearer & bearer) const protected virtual
DoActivateEpsBearerForUe: Schedule ActivateEpsBearer on the UE.
Parameters
ueDevice LTE device for the UE
tft TFT
bearer Bearer
Definition at line 479 of file no-backhaul-epc-helper.cc.
References ns3::EpcUeNas::ActivateEpsBearer(), NS_LOG_FUNCTION, NS_LOG_WARN, and ns3::Simulator::ScheduleNow().
Referenced by ActivateEpsBearer().
DoAddX2Interface()
void ns3::NoBackhaulEpcHelper::DoAddX2Interface (const Ptr< EpcX2 > & enb1X2, const Ptr< NetDevice > & enb1LteDev, const Ipv4Address & enb1X2Address, const Ptr< EpcX2 > & enb2X2, const Ptr< NetDevice > & enb2LteDev, const Ipv4Address & enb2X2Address) const protected virtual
DoAddX2Interface: Call AddX2Interface on top of the Enb device pointers.
Parameters
enb1X2 EPCX2 of ENB1
enb1LteDev LTE device of ENB1
enb1X2Address Address for ENB1
enb2X2 EPCX2 of ENB2
enb2LteDev LTE device of ENB2
enb2X2Address Address for ENB2
Definition at line 402 of file no-backhaul-epc-helper.cc.
References ns3::LteEnbNetDevice::GetCellId(), ns3::LteEnbNetDevice::GetRrc(), NS_ABORT_MSG_IF, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by AddX2Interface().
DoDispose()
void ns3::NoBackhaulEpcHelper::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::EpcHelper.
Reimplemented in ns3::PointToPointEpcHelper, and ns3::EmuEpcHelper.
Definition at line 295 of file no-backhaul-epc-helper.cc.
References ns3::Object::Dispose(), m_mme, m_mmeApp, m_pgw, m_pgwApp, m_sgw, m_sgwApp, m_tunDevice, ns3::MakeNullCallback(), NS_LOG_FUNCTION, and ns3::VirtualNetDevice::SetSendCallback().
Referenced by ns3::EmuEpcHelper::DoDispose(), and ns3::PointToPointEpcHelper::DoDispose().
GetInstanceTypeId()
TypeId ns3::NoBackhaulEpcHelper::GetInstanceTypeId () const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Reimplemented from ns3::Object.
Reimplemented in ns3::PointToPointEpcHelper.
Definition at line 289 of file no-backhaul-epc-helper.cc.
References GetTypeId().
GetPgwNode()
Ptr< Node > ns3::NoBackhaulEpcHelper::GetPgwNode () const virtual
Get the PGW node.
Returns
a pointer to the PGW node The primary use intended for this method is to allow the user to configure the SGi interface of the PGW, i.e., to connect the PGW to the internet.
Implements ns3::EpcHelper.
Definition at line 498 of file no-backhaul-epc-helper.cc.
References m_pgw.
Referenced by LteCellSelectionTestCase::DoRun(), LteRadioLinkFailureTestCase::DoRun(), LteUeMeasurementsHandoverTestCase::DoRun(), LteHandoverTargetTestCase::DoRun(), EpcS1uDlTestCase::DoRun(), EpcS1uUlTestCase::DoRun(), LenaCqaFfMacSchedulerTestCase1::DoRun(), LenaCqaFfMacSchedulerTestCase2::DoRun(), ns3::LenaDeactivateBearerTestCase::DoRun(), LenaFdTbfqFfMacSchedulerTestCase1::DoRun(), LenaFdTbfqFfMacSchedulerTestCase2::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LteIpv6RoutingTestCase::DoRun(), LenaPssFfMacSchedulerTestCase1::DoRun(), LenaPssFfMacSchedulerTestCase2::DoRun(), LenaTdTbfqFfMacSchedulerTestCase1::DoRun(), LenaTdTbfqFfMacSchedulerTestCase2::DoRun(), LteEpcE2eDataTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), and LteX2HandoverTestCase::DoRun().
GetSgwNode()
Ptr< Node > ns3::NoBackhaulEpcHelper::GetSgwNode () const virtual
Get the SGW node.
Returns
a pointer to the SGW
Implements ns3::EpcHelper.
Definition at line 538 of file no-backhaul-epc-helper.cc.
References m_sgw.
Referenced by ns3::EmuEpcHelper::EmuEpcHelper(), and ns3::PointToPointEpcHelper::AddEnb().
GetTypeId()
TypeId ns3::NoBackhaulEpcHelper::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 222 of file no-backhaul-epc-helper.cc.
References m_s11LinkDataRate, m_s11LinkDelay, m_s11LinkMtu, m_s5LinkDataRate, m_s5LinkDelay, m_s5LinkMtu, m_x2LinkDataRate, m_x2LinkDelay, m_x2LinkEnablePcap, m_x2LinkMtu, m_x2LinkPcapPrefix, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeDataRateAccessor(), ns3::MakeDataRateChecker(), ns3::MakeStringAccessor(), ns3::MakeStringChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeUintegerAccessor(), NS_LOG_FUNCTION_NOARGS, ns3::Seconds(), and ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
GetUeDefaultGatewayAddress()
Ipv4Address ns3::NoBackhaulEpcHelper::GetUeDefaultGatewayAddress () virtual
Returns
the IPv4 address of the Default Gateway to be used by UEs to reach the internet
Implements ns3::EpcHelper.
Definition at line 523 of file no-backhaul-epc-helper.cc.
References ns3::Object::GetObject(), and m_pgw.
Referenced by LteCellSelectionTestCase::DoRun(), LteRadioLinkFailureTestCase::DoRun(), LteUeMeasurementsHandoverTestCase::DoRun(), LteHandoverTargetTestCase::DoRun(), EpcS1uUlTestCase::DoRun(), LenaCqaFfMacSchedulerTestCase1::DoRun(), LenaCqaFfMacSchedulerTestCase2::DoRun(), ns3::LenaDeactivateBearerTestCase::DoRun(), LenaFdTbfqFfMacSchedulerTestCase1::DoRun(), LenaFdTbfqFfMacSchedulerTestCase2::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LenaPssFfMacSchedulerTestCase1::DoRun(), LenaPssFfMacSchedulerTestCase2::DoRun(), LenaTdTbfqFfMacSchedulerTestCase1::DoRun(), LenaTdTbfqFfMacSchedulerTestCase2::DoRun(), LteEpcE2eDataTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), and LteX2HandoverTestCase::DoRun().
GetUeDefaultGatewayAddress6()
Ipv6Address ns3::NoBackhaulEpcHelper::GetUeDefaultGatewayAddress6 () virtual
Returns
the IPv6 address of the Default Gateway to be used by UEs to reach the internet
Implements ns3::EpcHelper.
Definition at line 530 of file no-backhaul-epc-helper.cc.
References ns3::Ipv6::GetAddress(), ns3::Object::GetObject(), and m_pgw.
Referenced by LteIpv6RoutingTestCase::DoRun().
Member Data Documentation
m_gtpcUdpPort
uint16_t ns3::NoBackhaulEpcHelper::m_gtpcUdpPort private
UDP port where the GTPv2-C Socket is bound, fixed by the standard as 2123.
Definition at line 181 of file no-backhaul-epc-helper.h.
Referenced by NoBackhaulEpcHelper().
m_gtpuUdpPort
uint16_t ns3::NoBackhaulEpcHelper::m_gtpuUdpPort private
UDP port where the GTP-U Socket is bound, fixed by the standard as 2152.
Definition at line 156 of file no-backhaul-epc-helper.h.
Referenced by NoBackhaulEpcHelper(), and AddS1Interface().
m_imsiEnbDeviceMap
std::map<uint64_t, Ptr<NetDevice> > ns3::NoBackhaulEpcHelper::m_imsiEnbDeviceMap private
Map storing for each IMSI the corresponding eNB NetDevice.
Definition at line 210 of file no-backhaul-epc-helper.h.
m_mme
Ptr<Node> ns3::NoBackhaulEpcHelper::m_mme private
MME network element.
Definition at line 131 of file no-backhaul-epc-helper.h.
Referenced by NoBackhaulEpcHelper(), and DoDispose().
m_mmeApp
Ptr<EpcMmeApplication> ns3::NoBackhaulEpcHelper::m_mmeApp private
MME application.
Definition at line 146 of file no-backhaul-epc-helper.h.
Referenced by NoBackhaulEpcHelper(), ActivateEpsBearer(), AddS1Interface(), AddUe(), and DoDispose().
m_pgw
Ptr<Node> ns3::NoBackhaulEpcHelper::m_pgw private
PGW network element.
Definition at line 121 of file no-backhaul-epc-helper.h.
Referenced by NoBackhaulEpcHelper(), DoDispose(), GetPgwNode(), GetUeDefaultGatewayAddress(), and GetUeDefaultGatewayAddress6().
m_pgwApp
Ptr<EpcPgwApplication> ns3::NoBackhaulEpcHelper::m_pgwApp private
PGW application.
Definition at line 141 of file no-backhaul-epc-helper.h.
Referenced by NoBackhaulEpcHelper(), ActivateEpsBearer(), AddUe(), and DoDispose().
m_s11Ipv4AddressHelper
Ipv4AddressHelper ns3::NoBackhaulEpcHelper::m_s11Ipv4AddressHelper private
Helper to assign addresses to S11 NetDevices.
Definition at line 161 of file no-backhaul-epc-helper.h.
Referenced by NoBackhaulEpcHelper().
m_s11LinkDataRate
DataRate ns3::NoBackhaulEpcHelper::m_s11LinkDataRate private
The data rate to be used for the next S11 link to be created.
Definition at line 166 of file no-backhaul-epc-helper.h.
Referenced by NoBackhaulEpcHelper(), and GetTypeId().
m_s11LinkDelay
Time ns3::NoBackhaulEpcHelper::m_s11LinkDelay private
The delay to be used for the next S11 link to be created.
Definition at line 171 of file no-backhaul-epc-helper.h.
Referenced by NoBackhaulEpcHelper(), and GetTypeId().
m_s11LinkMtu
uint16_t ns3::NoBackhaulEpcHelper::m_s11LinkMtu private
The MTU of the next S11 link to be created.
Definition at line 176 of file no-backhaul-epc-helper.h.
Referenced by NoBackhaulEpcHelper(), and GetTypeId().
m_s5Ipv4AddressHelper
Ipv4AddressHelper ns3::NoBackhaulEpcHelper::m_s5Ipv4AddressHelper private
S5 interfaces.
Helper to assign addresses to S5 NetDevices
Definition at line 190 of file no-backhaul-epc-helper.h.
Referenced by NoBackhaulEpcHelper().
m_s5LinkDataRate
DataRate ns3::NoBackhaulEpcHelper::m_s5LinkDataRate private
The data rate to be used for the next S5 link to be created.
Definition at line 195 of file no-backhaul-epc-helper.h.
Referenced by NoBackhaulEpcHelper(), and GetTypeId().
m_s5LinkDelay
Time ns3::NoBackhaulEpcHelper::m_s5LinkDelay private
The delay to be used for the next S5 link to be created.
Definition at line 200 of file no-backhaul-epc-helper.h.
Referenced by NoBackhaulEpcHelper(), and GetTypeId().
m_s5LinkMtu
uint16_t ns3::NoBackhaulEpcHelper::m_s5LinkMtu private
The MTU of the next S5 link to be created.
Definition at line 205 of file no-backhaul-epc-helper.h.
Referenced by NoBackhaulEpcHelper(), and GetTypeId().
m_sgw
Ptr<Node> ns3::NoBackhaulEpcHelper::m_sgw private
SGW network element.
Definition at line 126 of file no-backhaul-epc-helper.h.
Referenced by NoBackhaulEpcHelper(), DoDispose(), and GetSgwNode().
m_sgwApp
Ptr<EpcSgwApplication> ns3::NoBackhaulEpcHelper::m_sgwApp private
SGW application.
Definition at line 136 of file no-backhaul-epc-helper.h.
Referenced by NoBackhaulEpcHelper(), AddS1Interface(), and DoDispose().
m_tunDevice
Ptr<VirtualNetDevice> ns3::NoBackhaulEpcHelper::m_tunDevice private
TUN device implementing tunneling of user data over GTP-U/UDP/IP.
Definition at line 151 of file no-backhaul-epc-helper.h.
Referenced by NoBackhaulEpcHelper(), and DoDispose().
m_uePgwAddressHelper
Ipv4AddressHelper ns3::NoBackhaulEpcHelper::m_uePgwAddressHelper private
helper to assign IPv4 addresses to UE devices as well as to the TUN device of the SGW/PGW
Definition at line 112 of file no-backhaul-epc-helper.h.
Referenced by NoBackhaulEpcHelper(), and AssignUeIpv4Address().
m_uePgwAddressHelper6
Ipv6AddressHelper ns3::NoBackhaulEpcHelper::m_uePgwAddressHelper6 private
helper to assign IPv6 addresses to UE devices as well as to the TUN device of the SGW/PGW
Definition at line 116 of file no-backhaul-epc-helper.h.
Referenced by NoBackhaulEpcHelper(), and AssignUeIpv6Address().
m_x2Ipv4AddressHelper
Ipv4AddressHelper ns3::NoBackhaulEpcHelper::m_x2Ipv4AddressHelper private
helper to assign addresses to X2 NetDevices
Definition at line 215 of file no-backhaul-epc-helper.h.
Referenced by NoBackhaulEpcHelper(), and AddX2Interface().
m_x2LinkDataRate
DataRate ns3::NoBackhaulEpcHelper::m_x2LinkDataRate private
The data rate to be used for the next X2 link to be created.
Definition at line 220 of file no-backhaul-epc-helper.h.
Referenced by AddX2Interface(), and GetTypeId().
m_x2LinkDelay
Time ns3::NoBackhaulEpcHelper::m_x2LinkDelay private
The delay to be used for the next X2 link to be created.
Definition at line 225 of file no-backhaul-epc-helper.h.
Referenced by AddX2Interface(), and GetTypeId().
m_x2LinkEnablePcap
bool ns3::NoBackhaulEpcHelper::m_x2LinkEnablePcap private
Enable PCAP generation for X2 link.
Definition at line 236 of file no-backhaul-epc-helper.h.
Referenced by AddX2Interface(), and GetTypeId().
m_x2LinkMtu
uint16_t ns3::NoBackhaulEpcHelper::m_x2LinkMtu private
The MTU of the next X2 link to be created.
Note that, because of some big X2 messages, you need a big MTU.
Definition at line 231 of file no-backhaul-epc-helper.h.
Referenced by AddX2Interface(), and GetTypeId().
m_x2LinkPcapPrefix
std::string ns3::NoBackhaulEpcHelper::m_x2LinkPcapPrefix private
Prefix for the PCAP file for the X2 link.
Definition at line 241 of file no-backhaul-epc-helper.h.
Referenced by AddX2Interface(), and GetTypeId().
The documentation for this class was generated from the following files:
src/lte/helper/no-backhaul-epc-helper.h
src/lte/helper/no-backhaul-epc-helper.cc