ns-3: CoDelQueueDiscBasicMark Class Reference
CoDelQueueDiscBasicMark Class Reference
Traffic-control » traffic-control module tests | Test suites
Test 6: enqueue/dequeue with marks according to CoDel algorithm.
Public Member Functions
CoDelQueueDiscBasicMark (QueueSizeUnit mode)
Constructor.
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void Dequeue (Ptr< CoDelQueueDisc > queue, uint32_t modeSize, uint32_t testCase)
Dequeue function.
void DropNextTracer (uint32_t oldVal, uint32_t newVal)
Drop next tracer function.
void Enqueue (Ptr< CoDelQueueDisc > queue, uint32_t size, uint32_t nPkt, bool ecnCapable)
Enqueue function.
Private Attributes
uint32_t m_dropNextCount
count the number of times m_dropNext is recalculated
QueueSizeUnit m_mode
mode
uint32_t nPacketsBeforeFirstDrop
Number of packets in the queue before first drop.
uint32_t nPacketsBeforeFirstMark
Number of packets in the queue before first mark.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test 6: enqueue/dequeue with marks according to CoDel algorithm.
Definition at line 592 of file codel-queue-disc-test-suite.cc.
Constructor & Destructor Documentation
CoDelQueueDiscBasicMark()
CoDelQueueDiscBasicMark::CoDelQueueDiscBasicMark (QueueSizeUnit mode)
Constructor.
Parameters
mode the mode
Definition at line 630 of file codel-queue-disc-test-suite.cc.
References m_dropNextCount, and m_mode.
Member Function Documentation
Dequeue()
void CoDelQueueDiscBasicMark::Dequeue (Ptr< CoDelQueueDisc > queue, uint32_t modeSize, uint32_t testCase) private
Dequeue function.
Parameters
queue the queue disc
modeSize the mode size
testCase the test case number
Definition at line 802 of file codel-queue-disc-test-suite.cc.
References DropNextTracer(), ns3::Time::GetMicroSeconds(), m_dropNextCount, ns3::MakeCallback(), ns3::MilliSeconds(), ns3::Now(), nPacketsBeforeFirstDrop, nPacketsBeforeFirstMark, NS_TEST_ASSERT_MSG_EQ, and NS_TEST_EXPECT_MSG_EQ.
Referenced by DoRun().
DoRun()
void CoDelQueueDiscBasicMark::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 646 of file codel-queue-disc-test-suite.cc.
References ns3::BYTES, Dequeue(), Enqueue(), m_mode, ns3::MilliSeconds(), nPacketsBeforeFirstDrop, nPacketsBeforeFirstMark, NS_TEST_EXPECT_MSG_EQ, ns3::PACKETS, and pktSize.
DropNextTracer()
void CoDelQueueDiscBasicMark::DropNextTracer (uint32_t oldVal, uint32_t newVal) private
Drop next tracer function.
Parameters
oldVal the old value
newVal the new value
Definition at line 638 of file codel-queue-disc-test-suite.cc.
References m_dropNextCount, and NS_UNUSED.
Referenced by Dequeue().
Enqueue()
void CoDelQueueDiscBasicMark::Enqueue (Ptr< CoDelQueueDisc > queue, uint32_t size, uint32_t nPkt, bool ecnCapable) private
Enqueue function.
Parameters
queue the queue disc
size the size
nPkt the number of packets
ecnCapable ECN capable traffic
Definition at line 792 of file codel-queue-disc-test-suite.cc.
Referenced by DoRun().
Member Data Documentation
m_dropNextCount
uint32_t CoDelQueueDiscBasicMark::m_dropNextCount private
count the number of times m_dropNext is recalculated
Definition at line 625 of file codel-queue-disc-test-suite.cc.
Referenced by CoDelQueueDiscBasicMark(), Dequeue(), and DropNextTracer().
m_mode
QueueSizeUnit CoDelQueueDiscBasicMark::m_mode private
mode
Definition at line 624 of file codel-queue-disc-test-suite.cc.
Referenced by CoDelQueueDiscBasicMark(), and DoRun().
nPacketsBeforeFirstDrop
uint32_t CoDelQueueDiscBasicMark::nPacketsBeforeFirstDrop private
Number of packets in the queue before first drop.
Definition at line 626 of file codel-queue-disc-test-suite.cc.
Referenced by Dequeue(), and DoRun().
nPacketsBeforeFirstMark
uint32_t CoDelQueueDiscBasicMark::nPacketsBeforeFirstMark private
Number of packets in the queue before first mark.
Definition at line 627 of file codel-queue-disc-test-suite.cc.
Referenced by Dequeue(), and DoRun().
The documentation for this class was generated from the following file:
src/traffic-control/test/codel-queue-disc-test-suite.cc