ns-3: ns3::AnimationInterface::AnimXmlElement Class Reference
ns3::AnimationInterface::AnimXmlElement Class Reference
AnimXmlElement class.
Public Member Functions
AnimXmlElement (std::string tagName, bool emptyElement=true)
Constructor.
template<typename T >
void AddAttribute (std::string attribute, T value, bool xmlEscape=false)
Add attribute function.
void AppendChild (AnimXmlElement e)
Append child function.
void SetText (std::string text)
Set text function.
std::string ToString (bool autoClose=true)
Get text for the element function.
Private Attributes
std::vector< std::string > m_attributes
list of attributes
std::vector< std::string > m_children
list of children
std::string m_tagName
tag name
std::string m_text
element string
Detailed Description
AnimXmlElement class.
Definition at line 564 of file animation-interface.h.
Constructor & Destructor Documentation
AnimXmlElement()
ns3::AnimationInterface::AnimXmlElement::AnimXmlElement (std::string tagName, bool emptyElement = true)
Constructor.
Parameters
tagName tag name
emptyElement empty element?
Definition at line 2742 of file animation-interface.cc.
Member Function Documentation
AddAttribute()
template<typename T > void ns3::AnimationInterface::AnimXmlElement::AddAttribute (std::string attribute, T value, bool xmlEscape = false)
Add attribute function.
Parameters
attribute the attribute name
value the attribute value
xmlEscape true to escape
Definition at line 2750 of file animation-interface.cc.
Referenced by ns3::AnimationInterface::WriteXmlAddNodeCounter(), ns3::AnimationInterface::WriteXmlAddResource(), ns3::AnimationInterface::WriteXmlAnim(), ns3::AnimationInterface::WriteXmlIpv4Addresses(), ns3::AnimationInterface::WriteXmlIpv6Addresses(), ns3::AnimationInterface::WriteXmlLink(), ns3::AnimationInterface::WriteXmlNode(), ns3::AnimationInterface::WriteXmlNonP2pLinkProperties(), ns3::AnimationInterface::WriteXmlP(), ns3::AnimationInterface::WriteXmlPRef(), ns3::AnimationInterface::WriteXmlRouting(), ns3::AnimationInterface::WriteXmlRp(), ns3::AnimationInterface::WriteXmlUpdateBackground(), ns3::AnimationInterface::WriteXmlUpdateLink(), ns3::AnimationInterface::WriteXmlUpdateNodeColor(), ns3::AnimationInterface::WriteXmlUpdateNodeCounter(), ns3::AnimationInterface::WriteXmlUpdateNodeDescription(), ns3::AnimationInterface::WriteXmlUpdateNodeImage(), ns3::AnimationInterface::WriteXmlUpdateNodePosition(), and ns3::AnimationInterface::WriteXmlUpdateNodeSize().
AppendChild()
void ns3::AnimationInterface::AnimXmlElement::AppendChild (AnimXmlElement e)
Append child function.
Parameters
e the element to add as a child
Definition at line 2794 of file animation-interface.cc.
References ToString().
Referenced by ns3::AnimationInterface::WriteXmlIpv4Addresses(), ns3::AnimationInterface::WriteXmlIpv6Addresses(), and ns3::AnimationInterface::WriteXmlRp().
SetText()
void ns3::AnimationInterface::AnimXmlElement::SetText (std::string text)
Set text function.
Parameters
text the text for the element
Definition at line 2800 of file animation-interface.cc.
Referenced by ns3::AnimationInterface::WriteXmlIpv4Addresses(), and ns3::AnimationInterface::WriteXmlIpv6Addresses().
ToString()
std::string ns3::AnimationInterface::AnimXmlElement::ToString (bool autoClose = true)
Get text for the element function.
Parameters
autoClose auto close the element
Returns
the text
Definition at line 2806 of file animation-interface.cc.
Referenced by AppendChild(), ns3::AnimationInterface::WriteXmlAddNodeCounter(), ns3::AnimationInterface::WriteXmlAddResource(), ns3::AnimationInterface::WriteXmlAnim(), ns3::AnimationInterface::WriteXmlIpv4Addresses(), ns3::AnimationInterface::WriteXmlIpv6Addresses(), ns3::AnimationInterface::WriteXmlLink(), ns3::AnimationInterface::WriteXmlNode(), ns3::AnimationInterface::WriteXmlNonP2pLinkProperties(), ns3::AnimationInterface::WriteXmlP(), ns3::AnimationInterface::WriteXmlPRef(), ns3::AnimationInterface::WriteXmlRouting(), ns3::AnimationInterface::WriteXmlRp(), ns3::AnimationInterface::WriteXmlUpdateBackground(), ns3::AnimationInterface::WriteXmlUpdateLink(), ns3::AnimationInterface::WriteXmlUpdateNodeColor(), ns3::AnimationInterface::WriteXmlUpdateNodeCounter(), ns3::AnimationInterface::WriteXmlUpdateNodeDescription(), ns3::AnimationInterface::WriteXmlUpdateNodeImage(), ns3::AnimationInterface::WriteXmlUpdateNodePosition(), and ns3::AnimationInterface::WriteXmlUpdateNodeSize().
Member Data Documentation
m_attributes
std::vector<std::string> ns3::AnimationInterface::AnimXmlElement::m_attributes private
list of attributes
Definition at line 602 of file animation-interface.h.
m_children
std::vector<std::string> ns3::AnimationInterface::AnimXmlElement::m_children private
list of children
Definition at line 603 of file animation-interface.h.
m_tagName
std::string ns3::AnimationInterface::AnimXmlElement::m_tagName private
tag name
Definition at line 600 of file animation-interface.h.
m_text
std::string ns3::AnimationInterface::AnimXmlElement::m_text private
element string
Definition at line 601 of file animation-interface.h.
The documentation for this class was generated from the following files:
src/netanim/model/animation-interface.h
src/netanim/model/animation-interface.cc