ns-3: Bench Class Reference
Bench Class Reference
Bench class.
Public Member Functions
Bench (const uint32_t population, const uint32_t total)
constructor
void RunBench (void)
Run function.
void SetPopulation (const uint32_t population)
Set population function.
void SetRandomStream (Ptr< RandomVariableStream > stream)
Set random stream.
void SetTotal (const uint32_t total)
Set total function.
Private Member Functions
void Cb (void)
callback function
Private Attributes
uint32_t m_count
count
uint32_t m_population
population
Ptr< RandomVariableStream > m_rand
random variable
uint32_t m_total
total
Detailed Description
Bench class.
Definition at line 43 of file bench-simulator.cc.
Constructor & Destructor Documentation
Bench()
Bench::Bench (const uint32_t population, const uint32_t total) inline
constructor
Parameters
population the population
total the total
Definition at line 51 of file bench-simulator.cc.
Member Function Documentation
Cb()
void Bench::Cb (void) private
callback function
Definition at line 134 of file bench-simulator.cc.
References DEB, ns3::NanoSeconds(), ns3::Simulator::Now(), and ns3::Simulator::Schedule().
Referenced by RunBench().
RunBench()
void Bench::RunBench (void)
Run function.
Definition at line 98 of file bench-simulator.cc.
References Cb(), DEB, ns3::SystemWallClockMs::End(), g_fwidth, LOG, ns3::NanoSeconds(), ns3::Simulator::Run(), ns3::Simulator::Schedule(), and ns3::SystemWallClockMs::Start().
SetPopulation()
void Bench::SetPopulation (const uint32_t population) inline
Set population function.
Parameters
population the population
Definition at line 71 of file bench-simulator.cc.
SetRandomStream()
void Bench::SetRandomStream (Ptr< RandomVariableStream > stream) inline
Set random stream.
Parameters
stream the random variable stream
Definition at line 62 of file bench-simulator.cc.
SetTotal()
void Bench::SetTotal (const uint32_t total) inline
Set total function.
Parameters
total
Definition at line 80 of file bench-simulator.cc.
Member Data Documentation
m_count
uint32_t Bench::m_count private
count
Definition at line 94 of file bench-simulator.cc.
m_population
uint32_t Bench::m_population private
population
Definition at line 92 of file bench-simulator.cc.
m_rand
Ptr<RandomVariableStream> Bench::m_rand private
random variable
Definition at line 91 of file bench-simulator.cc.
m_total
uint32_t Bench::m_total private
total
Definition at line 93 of file bench-simulator.cc.
The documentation for this class was generated from the following file:
utils/bench-simulator.cc