ns-3: ns3::TraceFadingLossModel Class Reference
ns3::TraceFadingLossModel Class Reference
Spectrum Models
fading loss model based on precalculated fading traces
#include "trace-fading-loss-model.h"
Public Types
typedef std::pair< Ptr< const MobilityModel >, Ptr< const MobilityModel > > ChannelRealizationId_t
The couple of mobility node that form a fading channel realization.
Public Member Functions
TraceFadingLossModel ()
virtual ~TraceFadingLossModel ()
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
virtual void DoInitialize (void)
Initialize() implementation.
Public Member Functions inherited from ns3::SpectrumPropagationLossModel
SpectrumPropagationLossModel ()
virtual ~SpectrumPropagationLossModel ()
Ptr< SpectrumValue > CalcRxPowerSpectralDensity (Ptr< const SpectrumValue > txPsd, Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const
This method is to be called to calculate.
void SetNext (Ptr< SpectrumPropagationLossModel > next)
Used to chain various instances of SpectrumPropagationLossModel.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::SpectrumPropagationLossModel
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef std::vector< FadingTraceSample > FadingTrace
Vector collecting the time fading traces in the frequency domain (per RB)
typedef std::vector< double > FadingTraceSample
Vector with fading samples in time domain (for a fixed RB)
Private Member Functions
Ptr< SpectrumValue > DoCalcRxPowerSpectralDensity (Ptr< const SpectrumValue > txPsd, Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const
double GetValue (int subChannel, double speed)
Get the value for a particular sub channel and a given speed.
void LoadTrace ()
Load trace function.
void SetTraceFileName (std::string fileName)
Set the trace file name.
void SetTraceLength (Time t)
Set the trace time.
Private Attributes
uint64_t m_currentStream
the current stream
FadingTrace m_fadingTrace
fading trace
uint64_t m_lastStream
the last stream
Time m_lastWindowUpdate
time of last window update
uint8_t m_rbNum
RB number.
uint32_t m_samplesNum
number of samples
std::map< ChannelRealizationId_t, Ptr< UniformRandomVariable > > m_startVariableMap
start variable map
bool m_streamsAssigned
is streams assigned?
uint64_t m_streamSetSize
stream set size
uint8_t m_timeGranularity
time granularity
std::string m_traceFile
the trace file name
Time m_traceLength
the trace time
std::map< ChannelRealizationId_t, int > m_windowOffsetsMap
windows offsets map
Time m_windowSize
window size
Additional Inherited Members
Protected Member Functions inherited from ns3::SpectrumPropagationLossModel
virtual void DoDispose ()
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
fading loss model based on precalculated fading traces
Introspection did not find any typical Config paths.
Attributes
TraceFilename: Name of file to load a trace from.
Set with class: StringValue
Underlying type:
Initial value:
Flags: construct write
TraceLength: The total length of the fading trace (default value 10 s.)
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+10ns
Flags: construct write
SamplesNum: The number of samples the trace is made of (default 10000)
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 10000
Flags: construct write read
WindowSize: The size of the window for the fading trace (default value 0.5 s.)
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +5e+08ns
Flags: construct write read
RbNum: The number of RB the trace is made of (default 100)
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Initial value: 100
Flags: construct write read
RngStreamSetSize: The number of RNG streams reserved for the fading model. The maximum number of streams that are needed for an LTE FDD scenario is 2 * numUEs * numeNBs.
Set with class: ns3::UintegerValue
Underlying type: uint64_t 0:18446744073709551615
Initial value: 200000
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 216 bytes (on a 64-bit architecture).
Definition at line 44 of file trace-fading-loss-model.h.
Member Typedef Documentation
ChannelRealizationId_t
typedef std::pair<Ptr<const MobilityModel>, Ptr<const MobilityModel> > ns3::TraceFadingLossModel::ChannelRealizationId_t
The couple of mobility node that form a fading channel realization.
Definition at line 61 of file trace-fading-loss-model.h.
FadingTrace
typedef std::vector<FadingTraceSample> ns3::TraceFadingLossModel::FadingTrace private
Vector collecting the time fading traces in the frequency domain (per RB)
Definition at line 122 of file trace-fading-loss-model.h.
FadingTraceSample
typedef std::vector<double> ns3::TraceFadingLossModel::FadingTraceSample private
Vector with fading samples in time domain (for a fixed RB)
Definition at line 118 of file trace-fading-loss-model.h.
Constructor & Destructor Documentation
TraceFadingLossModel()
ns3::TraceFadingLossModel::TraceFadingLossModel ()
Definition at line 41 of file trace-fading-loss-model.cc.
References NS_LOG_FUNCTION, and ns3::SpectrumPropagationLossModel::SetNext().
~TraceFadingLossModel()
ns3::TraceFadingLossModel::~TraceFadingLossModel () virtual
Definition at line 49 of file trace-fading-loss-model.cc.
References m_fadingTrace, m_startVariableMap, and m_windowOffsetsMap.
Member Function Documentation
AssignStreams()
int64_t ns3::TraceFadingLossModel::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 237 of file trace-fading-loss-model.cc.
References m_currentStream, m_lastStream, m_startVariableMap, m_streamsAssigned, m_streamSetSize, NS_ASSERT, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
DoCalcRxPowerSpectralDensity()
Ptr< SpectrumValue > ns3::TraceFadingLossModel::DoCalcRxPowerSpectralDensity (Ptr< const SpectrumValue > txPsd, Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const private virtual
Parameters
txPsd set of values vs frequency representing the transmission power. See SpectrumChannel for details.
a sender mobility
b receiver mobility
Returns
set of values vs frequency representing the received power in the same units used for the txPsd parameter.
Implements ns3::SpectrumPropagationLossModel.
Definition at line 151 of file trace-fading-loss-model.cc.
References ns3::Time::GetMilliSeconds(), ns3::Time::GetSeconds(), ns3::UniformRandomVariable::GetValue(), m_currentStream, m_fadingTrace, m_lastStream, m_lastWindowUpdate, m_samplesNum, m_startVariableMap, m_streamsAssigned, m_timeGranularity, m_traceLength, m_windowOffsetsMap, m_windowSize, ns3::Simulator::Now(), NS_ASSERT, NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, ns3::ObjectBase::SetAttribute(), ns3::RandomVariableStream::SetStream(), ns3::SpectrumValue::ValuesBegin(), and ns3::SpectrumValue::ValuesEnd().
DoInitialize()
void ns3::TraceFadingLossModel::DoInitialize (void) virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 113 of file trace-fading-loss-model.cc.
References LoadTrace().
GetTypeId()
TypeId ns3::TraceFadingLossModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 58 of file trace-fading-loss-model.cc.
References m_rbNum, m_samplesNum, m_streamSetSize, m_windowSize, ns3::MakeStringAccessor(), ns3::MakeStringChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeUintegerAccessor(), ns3::Seconds(), ns3::TypeId::SetParent(), SetTraceFileName(), and SetTraceLength().
GetValue()
double ns3::TraceFadingLossModel::GetValue (int subChannel, double speed) private
Get the value for a particular sub channel and a given speed.
Parameters
subChannel the sub channel for which a value is requested
speed the relative speed of the two devices
Returns
the loss for a particular sub channel
LoadTrace()
void ns3::TraceFadingLossModel::LoadTrace () private
Load trace function.
Definition at line 120 of file trace-fading-loss-model.cc.
References ns3::Time::GetMilliSeconds(), m_fadingTrace, m_lastWindowUpdate, m_rbNum, m_samplesNum, m_timeGranularity, m_traceFile, m_traceLength, ns3::Simulator::Now(), NS_ASSERT_MSG, NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by DoInitialize().
SetTraceFileName()
void ns3::TraceFadingLossModel::SetTraceFileName (std::string fileName) private
Set the trace file name.
Parameters
fileName the trace file
Definition at line 99 of file trace-fading-loss-model.cc.
References m_traceFile, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetTraceLength()
void ns3::TraceFadingLossModel::SetTraceLength (Time t) private
Set the trace time.
Parameters
t the trace time
Definition at line 107 of file trace-fading-loss-model.cc.
References m_traceLength.
Referenced by GetTypeId().
Member Data Documentation
m_currentStream
uint64_t ns3::TraceFadingLossModel::m_currentStream mutable private
the current stream
Definition at line 137 of file trace-fading-loss-model.h.
Referenced by AssignStreams(), and DoCalcRxPowerSpectralDensity().
m_fadingTrace
FadingTrace ns3::TraceFadingLossModel::m_fadingTrace private
fading trace
Definition at line 128 of file trace-fading-loss-model.h.
Referenced by ~TraceFadingLossModel(), DoCalcRxPowerSpectralDensity(), and LoadTrace().
m_lastStream
uint64_t ns3::TraceFadingLossModel::m_lastStream mutable private
the last stream
Definition at line 138 of file trace-fading-loss-model.h.
Referenced by AssignStreams(), and DoCalcRxPowerSpectralDensity().
m_lastWindowUpdate
Time ns3::TraceFadingLossModel::m_lastWindowUpdate mutable private
time of last window update
Definition at line 135 of file trace-fading-loss-model.h.
Referenced by DoCalcRxPowerSpectralDensity(), and LoadTrace().
m_rbNum
uint8_t ns3::TraceFadingLossModel::m_rbNum private
RB number.
Definition at line 134 of file trace-fading-loss-model.h.
Referenced by GetTypeId(), and LoadTrace().
m_samplesNum
uint32_t ns3::TraceFadingLossModel::m_samplesNum private
number of samples
Definition at line 132 of file trace-fading-loss-model.h.
Referenced by DoCalcRxPowerSpectralDensity(), GetTypeId(), and LoadTrace().
m_startVariableMap
std::map<ChannelRealizationId_t, Ptr<UniformRandomVariable> > ns3::TraceFadingLossModel::m_startVariableMap mutable private
start variable map
Definition at line 113 of file trace-fading-loss-model.h.
Referenced by ~TraceFadingLossModel(), AssignStreams(), and DoCalcRxPowerSpectralDensity().
m_streamsAssigned
bool ns3::TraceFadingLossModel::m_streamsAssigned mutable private
is streams assigned?
Definition at line 140 of file trace-fading-loss-model.h.
Referenced by AssignStreams(), and DoCalcRxPowerSpectralDensity().
m_streamSetSize
uint64_t ns3::TraceFadingLossModel::m_streamSetSize private
stream set size
Definition at line 139 of file trace-fading-loss-model.h.
Referenced by AssignStreams(), and GetTypeId().
m_timeGranularity
uint8_t ns3::TraceFadingLossModel::m_timeGranularity private
time granularity
Definition at line 136 of file trace-fading-loss-model.h.
Referenced by DoCalcRxPowerSpectralDensity(), and LoadTrace().
m_traceFile
std::string ns3::TraceFadingLossModel::m_traceFile private
the trace file name
Definition at line 126 of file trace-fading-loss-model.h.
Referenced by LoadTrace(), and SetTraceFileName().
m_traceLength
Time ns3::TraceFadingLossModel::m_traceLength private
the trace time
Definition at line 131 of file trace-fading-loss-model.h.
Referenced by DoCalcRxPowerSpectralDensity(), LoadTrace(), and SetTraceLength().
m_windowOffsetsMap
std::map<ChannelRealizationId_t, int > ns3::TraceFadingLossModel::m_windowOffsetsMap mutable private
windows offsets map
Definition at line 111 of file trace-fading-loss-model.h.
Referenced by ~TraceFadingLossModel(), and DoCalcRxPowerSpectralDensity().
m_windowSize
Time ns3::TraceFadingLossModel::m_windowSize private
window size
Definition at line 133 of file trace-fading-loss-model.h.
Referenced by DoCalcRxPowerSpectralDensity(), and GetTypeId().
The documentation for this class was generated from the following files:
src/spectrum/model/trace-fading-loss-model.h
src/spectrum/model/trace-fading-loss-model.cc