ns-3: ns3::Ipv4NixVectorRouting Class Reference
ns3::Ipv4NixVectorRouting Class Reference
Nix-Vector Routing
Nix-vector routing protocol.
#include "ipv4-nix-vector-routing.h"
Classes
struct Ipv4AddressHash
Hashing for the ipv4Address class.
Public Member Functions
Ipv4NixVectorRouting ()
~Ipv4NixVectorRouting ()
void FlushGlobalNixRoutingCache (void) const
Called when run-time link topology change occurs which iterates through the node list and flushes any nix vector caches.
void SetNode (Ptr< Node > node)
Set the Node pointer of the node for which this routing protocol is to be placed.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
The Interface ID of the Global Router interface.
Static Public Member Functions inherited from ns3::Ipv4RoutingProtocol
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef std::unordered_map< Ipv4Address, ns3::Ptr< ns3::Node >, Ipv4AddressHash > Ipv4AddressToNodeMap
Mapping of IPv4 address to ns-3 node.
Private Member Functions
bool BFS (uint32_t numberOfNodes, Ptr< Node > source, Ptr< Node > dest, std::vector< Ptr< Node > > &parentVector, Ptr< NetDevice > oif)
Breadth first search algorithm.
void BuildIpv4AddressToNodeMap (void)
Build map from IPv4 Address to Node for faster lookup.
bool BuildNixVector (const std::vector< Ptr< Node > > &parentVector, uint32_t source, uint32_t dest, Ptr< NixVector > nixVector)
Recurses the parent vector, created by BFS and actually builds the nixvector.
bool BuildNixVectorLocal (Ptr< NixVector > nixVector)
Special variation of BuildNixVector for when a node is sending to itself.
void CheckCacheStateAndFlush (void) const
Flushes routing caches if required.
void DoDispose (void)
Destructor implementation.
uint32_t FindNetDeviceForNixIndex (uint32_t nodeIndex, Ipv4Address &gatewayIp)
Nix index is with respect to the neighbors.
uint32_t FindTotalNeighbors (void)
Simple iterates through the nodes net-devices and determines how many neighbors it has.
void FlushIpv4RouteCache (void) const
Flushes the cache which stores the Ipv4 route based on the destination IP.
void FlushNixCache (void) const
Flushes the cache which stores nix-vector based on destination IP.
void GetAdjacentNetDevices (Ptr< NetDevice > netDevice, Ptr< Channel > channel, NetDeviceContainer &netDeviceContainer)
Given a net-device returns all the adjacent net-devices, essentially getting the neighbors on that channel.
Ptr< Ipv4Route > GetIpv4RouteInCache (Ipv4Address address)
Checks the cache based on dest IP for the Ipv4Route.
Ptr< NixVector > GetNixVector (Ptr< Node > source, Ipv4Address dest, Ptr< NetDevice > oif)
Takes in the source node and dest IP and calls GetNodeByIp, BFS, accounting for any output interface specified, and finally BuildNixVector to return the built nix-vector.
Ptr< NixVector > GetNixVectorInCache (Ipv4Address address)
Checks the cache based on dest IP for the nix-vector.
Ptr< Node > GetNodeByIp (Ipv4Address dest)
Iterates through the node list and finds the one corresponding to the given Ipv4Address.
Ptr< BridgeNetDevice > NetDeviceIsBridged (Ptr< NetDevice > nd) const
Determine if the NetDevice is bridged.
virtual void NotifyAddAddress (uint32_t interface, Ipv4InterfaceAddress address)
virtual void NotifyInterfaceDown (uint32_t interface)
virtual void NotifyInterfaceUp (uint32_t interface)
virtual void NotifyRemoveAddress (uint32_t interface, Ipv4InterfaceAddress address)
virtual void PrintRoutingTable (Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S) const
Print the Routing Table entries.
void ResetTotalNeighbors (void)
Upon a run-time topology change caches are flushed and the total number of neighbors is reset to zero.
virtual bool RouteInput (Ptr< const Packet > p, const Ipv4Header &header, Ptr< const NetDevice > idev, UnicastForwardCallback ucb, MulticastForwardCallback mcb, LocalDeliverCallback lcb, ErrorCallback ecb)
Route an input packet (to be forwarded or locally delivered)
virtual Ptr< Ipv4Route > RouteOutput (Ptr< Packet > p, const Ipv4Header &header, Ptr< NetDevice > oif, Socket::SocketErrno &sockerr)
Query routing cache for an existing route, for an outbound packet.
virtual void SetIpv4 (Ptr< Ipv4 > ipv4)
Private Attributes
Ptr< Ipv4 > m_ipv4
IPv4 object.
Ipv4RouteMap_t m_ipv4RouteCache
Cache stores Ipv4Routes based on destination ip.
NixMap_t m_nixCache
Cache stores nix-vectors based on destination ip.
Ptr< Node > m_node
Node object.
uint32_t m_totalNeighbors
Total neighbors used for nix-vector to determine number of bits.
Static Private Attributes
static Ipv4AddressToNodeMap g_ipv4AddressToNodeMap
static bool g_isCacheDirty = false
Flag to mark when caches are dirty and need to be flushed.
Additional Inherited Members
Public Types inherited from ns3::Ipv4RoutingProtocol
typedef Callback< void, Ptr< const Packet >, const Ipv4Header &, Socket::SocketErrno > ErrorCallback
Callback for routing errors (e.g., no route found)
typedef Callback< void, Ptr< const Packet >, const Ipv4Header &, uint32_t > LocalDeliverCallback
Callback for packets to be locally delivered.
typedef Callback< void, Ptr< Ipv4MulticastRoute >, Ptr< const Packet >, const Ipv4Header & > MulticastForwardCallback
Callback for multicast packets to be forwarded.
typedef Callback< void, Ptr< Ipv4Route >, Ptr< const Packet >, const Ipv4Header & > UnicastForwardCallback
Callback for unicast packets to be forwarded.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Nix-vector routing protocol.
Config Paths
ns3::Ipv4NixVectorRouting is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::Ipv4NixVectorRouting"
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 104 bytes (on a 64-bit architecture).
Definition at line 61 of file ipv4-nix-vector-routing.h.
Member Typedef Documentation
Ipv4AddressToNodeMap
typedef std::unordered_map<Ipv4Address, ns3::Ptr<ns3::Node>, Ipv4AddressHash > ns3::Ipv4NixVectorRouting::Ipv4AddressToNodeMap private
Mapping of IPv4 address to ns-3 node.
Used to avoid linear searching of nodes/devices to find a node in GetNodeByIp() method. NIX vector routing assumes IP addresses are unique so mapping can be done without duplication.
Definition at line 278 of file ipv4-nix-vector-routing.h.
Constructor & Destructor Documentation
Ipv4NixVectorRouting()
ns3::Ipv4NixVectorRouting::Ipv4NixVectorRouting ()
Definition at line 52 of file ipv4-nix-vector-routing.cc.
References NS_LOG_FUNCTION_NOARGS.
~Ipv4NixVectorRouting()
ns3::Ipv4NixVectorRouting::~Ipv4NixVectorRouting ()
Definition at line 58 of file ipv4-nix-vector-routing.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
BFS()
bool ns3::Ipv4NixVectorRouting::BFS (uint32_t numberOfNodes, Ptr< Node > source, Ptr< Node > dest, std::vector< Ptr< Node > > & parentVector, Ptr< NetDevice > oif) private
Breadth first search algorithm.
Parameters
[in] numberOfNodes total number of nodes
[in] source Source Node
[in] dest Destination Node
[out] parentVector Parent vector for retracing routes
[in] oif specific output interface to use from source node, if not null
Returns
false if dest not found, true o.w.
Definition at line 819 of file ipv4-nix-vector-routing.cc.
References ns3::NetDeviceContainer::Begin(), third::channel, ns3::NetDeviceContainer::End(), GetAdjacentNetDevices(), ns3::Node::GetDevice(), ns3::Node::GetId(), ns3::Node::GetNDevices(), ns3::Object::GetObject(), NS_LOG_FUNCTION_NOARGS, and NS_LOG_LOGIC.
Referenced by GetNixVector().
BuildIpv4AddressToNodeMap()
void ns3::Ipv4NixVectorRouting::BuildIpv4AddressToNodeMap (void) private
Build map from IPv4 Address to Node for faster lookup.
Definition at line 352 of file ipv4-nix-vector-routing.cc.
References ns3::NodeList::Begin(), ns3::NodeList::End(), g_ipv4AddressToNodeMap, ns3::Node::GetDevice(), ns3::Node::GetId(), ns3::Ipv4InterfaceAddress::GetLocal(), ns3::Node::GetNDevices(), ns3::Object::GetObject(), NS_ABORT_MSG_IF, NS_LOG_FUNCTION_NOARGS, and NS_LOG_LOGIC.
Referenced by GetNodeByIp().
BuildNixVector()
bool ns3::Ipv4NixVectorRouting::BuildNixVector (const std::vector< Ptr< Node > > & parentVector, uint32_t source, uint32_t dest, Ptr< NixVector > nixVector) private
Recurses the parent vector, created by BFS and actually builds the nixvector.
Parameters
[in] parentVector Parent vector for retracing routes
[in] source Source Node index
[in] dest Destination Node index
[out] nixVector the NixVector to be used for routing
Returns
true on success, false otherwise.
Definition at line 239 of file ipv4-nix-vector-routing.cc.
References ns3::NixVector::AddNeighborIndex(), ns3::NetDeviceContainer::Begin(), ns3::NixVector::BitCount(), third::channel, ns3::NetDeviceContainer::End(), GetAdjacentNetDevices(), ns3::Node::GetDevice(), ns3::Node::GetId(), ns3::NetDeviceContainer::GetN(), ns3::Node::GetNDevices(), NS_LOG_FUNCTION_NOARGS, and NS_LOG_LOGIC.
Referenced by GetNixVector().
BuildNixVectorLocal()
bool ns3::Ipv4NixVectorRouting::BuildNixVectorLocal (Ptr< NixVector > nixVector) private
Special variation of BuildNixVector for when a node is sending to itself.
Parameters
[out] nixVector the NixVector to be used for routing
Returns
true on success, false otherwise.
Definition at line 212 of file ipv4-nix-vector-routing.cc.
References ns3::NixVector::AddNeighborIndex(), ns3::NixVector::BitCount(), ns3::Node::GetDevice(), ns3::Node::GetId(), ns3::Ipv4InterfaceAddress::GetLocal(), ns3::Node::GetNDevices(), m_ipv4, m_node, NS_LOG_FUNCTION_NOARGS, and NS_LOG_LOGIC.
CheckCacheStateAndFlush()
void ns3::Ipv4NixVectorRouting::CheckCacheStateAndFlush (void) const private
Flushes routing caches if required.
Definition at line 965 of file ipv4-nix-vector-routing.cc.
References FlushGlobalNixRoutingCache(), and g_isCacheDirty.
Referenced by GetIpv4RouteInCache(), GetNixVectorInCache(), PrintRoutingTable(), RouteInput(), and RouteOutput().
DoDispose()
void ns3::Ipv4NixVectorRouting::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 74 of file ipv4-nix-vector-routing.cc.
References ns3::Object::DoDispose(), m_ipv4, m_node, and NS_LOG_FUNCTION_NOARGS.
FindNetDeviceForNixIndex()
uint32_t ns3::Ipv4NixVectorRouting::FindNetDeviceForNixIndex (uint32_t nodeIndex, Ipv4Address & gatewayIp) private
Nix index is with respect to the neighbors.
The net-device index must be derived from this
Parameters
[in] nodeIndex Nix Node index
[out] gatewayIp IP address of the gateway
Returns
the index of the NetDevice in the node.
Definition at line 490 of file ipv4-nix-vector-routing.cc.
References third::channel, ns3::NetDeviceContainer::Get(), GetAdjacentNetDevices(), ns3::Node::GetDevice(), ns3::Ipv4InterfaceAddress::GetLocal(), ns3::NetDeviceContainer::GetN(), ns3::Node::GetNDevices(), ns3::Object::GetObject(), and m_node.
Referenced by RouteInput(), and RouteOutput().
FindTotalNeighbors()
uint32_t ns3::Ipv4NixVectorRouting::FindTotalNeighbors (void) private
Simple iterates through the nodes net-devices and determines how many neighbors it has.
Returns
the number of neighbors.
Definition at line 419 of file ipv4-nix-vector-routing.cc.
References third::channel, GetAdjacentNetDevices(), ns3::Node::GetDevice(), ns3::NetDeviceContainer::GetN(), ns3::Node::GetNDevices(), and m_node.
Referenced by RouteInput(), and RouteOutput().
FlushGlobalNixRoutingCache()
void ns3::Ipv4NixVectorRouting::FlushGlobalNixRoutingCache (void) const
Called when run-time link topology change occurs which iterates through the node list and flushes any nix vector caches.
Internal:
const is used here due to need to potentially flush the cache in const methods such as PrintRoutingTable. Caches are stored in mutable variables and flushed in const methods.
Definition at line 94 of file ipv4-nix-vector-routing.cc.
References ns3::NodeList::Begin(), ns3::NodeList::End(), g_ipv4AddressToNodeMap, ns3::Object::GetObject(), NS_LOG_FUNCTION_NOARGS, and NS_LOG_LOGIC.
Referenced by CheckCacheStateAndFlush().
FlushIpv4RouteCache()
void ns3::Ipv4NixVectorRouting::FlushIpv4RouteCache (void) const private
Flushes the cache which stores the Ipv4 route based on the destination IP.
Definition at line 124 of file ipv4-nix-vector-routing.cc.
References m_ipv4RouteCache, and NS_LOG_FUNCTION_NOARGS.
FlushNixCache()
void ns3::Ipv4NixVectorRouting::FlushNixCache (void) const private
Flushes the cache which stores nix-vector based on destination IP.
Definition at line 117 of file ipv4-nix-vector-routing.cc.
References m_nixCache, and NS_LOG_FUNCTION_NOARGS.
GetAdjacentNetDevices()
void ns3::Ipv4NixVectorRouting::GetAdjacentNetDevices (Ptr< NetDevice > netDevice, Ptr< Channel > channel, NetDeviceContainer & netDeviceContainer) private
Given a net-device returns all the adjacent net-devices, essentially getting the neighbors on that channel.
Parameters
[in] netDevice the NetDevice attached to the channel.
[in] channel the channel to check
[out] netDeviceContainer the NetDeviceContainer of the NetDevices in the channel.
Definition at line 312 of file ipv4-nix-vector-routing.cc.
References ns3::NetDeviceContainer::Add(), third::channel, NetDeviceIsBridged(), NS_LOG_FUNCTION_NOARGS, and NS_LOG_LOGIC.
Referenced by BFS(), BuildNixVector(), FindNetDeviceForNixIndex(), and FindTotalNeighbors().
GetIpv4RouteInCache()
Ptr< Ipv4Route > ns3::Ipv4NixVectorRouting::GetIpv4RouteInCache (Ipv4Address address) private
Checks the cache based on dest IP for the Ipv4Route.
Parameters
address Address to check
Returns
The cached route.
Definition at line 194 of file ipv4-nix-vector-routing.cc.
References first::address, CheckCacheStateAndFlush(), m_ipv4RouteCache, NS_LOG_FUNCTION_NOARGS, and NS_LOG_LOGIC.
Referenced by RouteInput(), and RouteOutput().
GetNixVector()
Ptr< NixVector > ns3::Ipv4NixVectorRouting::GetNixVector (Ptr< Node > source, Ipv4Address dest, Ptr< NetDevice > oif) private
Takes in the source node and dest IP and calls GetNodeByIp, BFS, accounting for any output interface specified, and finally BuildNixVector to return the built nix-vector.
Parameters
source Source node
dest Destination node address
oif Preferred output interface
Returns
The NixVector to be used in routing.
Internal:
Do not process packets to self (see Bug 1308)
Definition at line 131 of file ipv4-nix-vector-routing.cc.
References BFS(), BuildNixVector(), ns3::Node::GetId(), ns3::NodeList::GetNNodes(), GetNodeByIp(), NS_LOG_DEBUG, NS_LOG_ERROR, and NS_LOG_FUNCTION_NOARGS.
Referenced by RouteOutput().
GetNixVectorInCache()
Ptr< NixVector > ns3::Ipv4NixVectorRouting::GetNixVectorInCache (Ipv4Address address) private
Checks the cache based on dest IP for the nix-vector.
Parameters
address Address to check
Returns
The NixVector to be used in routing.
Definition at line 176 of file ipv4-nix-vector-routing.cc.
References first::address, CheckCacheStateAndFlush(), m_nixCache, NS_LOG_FUNCTION_NOARGS, and NS_LOG_LOGIC.
Referenced by RouteOutput().
GetNodeByIp()
Ptr< Node > ns3::Ipv4NixVectorRouting::GetNodeByIp (Ipv4Address dest) private
Iterates through the node list and finds the one corresponding to the given Ipv4Address.
Parameters
dest destination node IP
Returns
The node with the specified IP.
Definition at line 391 of file ipv4-nix-vector-routing.cc.
References BuildIpv4AddressToNodeMap(), g_ipv4AddressToNodeMap, NS_LOG_ERROR, and NS_LOG_FUNCTION_NOARGS.
Referenced by GetNixVector().
GetTypeId()
TypeId ns3::Ipv4NixVectorRouting::GetTypeId (void) static
The Interface ID of the Global Router interface.
Returns
The Interface ID
See also
Object::GetObject ()
Definition at line 42 of file ipv4-nix-vector-routing.cc.
References ns3::TypeId::SetParent().
NetDeviceIsBridged()
Ptr< BridgeNetDevice > ns3::Ipv4NixVectorRouting::NetDeviceIsBridged (Ptr< NetDevice > nd) const private
Determine if the NetDevice is bridged.
Parameters
nd the NetDevice to check
Returns
the bridging NetDevice (or null if the NetDevice is not bridged)
Definition at line 450 of file ipv4-nix-vector-routing.cc.
References ns3::Node::GetDevice(), ns3::Node::GetNDevices(), NS_ABORT_MSG_UNLESS, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by GetAdjacentNetDevices().
NotifyAddAddress()
void ns3::Ipv4NixVectorRouting::NotifyAddAddress (uint32_t interface, Ipv4InterfaceAddress address) private virtual
Parameters
interface the index of the interface we are being notified about
address a new address being added to an interface
Protocols are expected to implement this method to be notified whenever a new address is added to an interface. Typically used to add a 'network route' on an interface. Can be invoked on an up or down interface.
Implements ns3::Ipv4RoutingProtocol.
Definition at line 808 of file ipv4-nix-vector-routing.cc.
References g_isCacheDirty.
NotifyInterfaceDown()
void ns3::Ipv4NixVectorRouting::NotifyInterfaceDown (uint32_t interface) private virtual
Parameters
interface the index of the interface we are being notified about
Protocols are expected to implement this method to be notified of the state change of an interface in a node.
Implements ns3::Ipv4RoutingProtocol.
Definition at line 803 of file ipv4-nix-vector-routing.cc.
References g_isCacheDirty.
NotifyInterfaceUp()
void ns3::Ipv4NixVectorRouting::NotifyInterfaceUp (uint32_t interface) private virtual
Parameters
interface the index of the interface we are being notified about
Protocols are expected to implement this method to be notified of the state change of an interface in a node.
Implements ns3::Ipv4RoutingProtocol.
Definition at line 798 of file ipv4-nix-vector-routing.cc.
References g_isCacheDirty.
NotifyRemoveAddress()
void ns3::Ipv4NixVectorRouting::NotifyRemoveAddress (uint32_t interface, Ipv4InterfaceAddress address) private virtual
Parameters
interface the index of the interface we are being notified about
address a new address being added to an interface
Protocols are expected to implement this method to be notified whenever a new address is removed from an interface. Typically used to remove the 'network route' of an interface. Can be invoked on an up or down interface.
Implements ns3::Ipv4RoutingProtocol.
Definition at line 813 of file ipv4-nix-vector-routing.cc.
References g_isCacheDirty.
PrintRoutingTable()
void ns3::Ipv4NixVectorRouting::PrintRoutingTable (Ptr< OutputStreamWrapper > stream, Time::Unit unit = Time::S) const private virtual
Print the Routing Table entries.
Parameters
stream The ostream the Routing table is printed to
unit The time unit to be used in the report
Implements ns3::Ipv4RoutingProtocol.
Definition at line 744 of file ipv4-nix-vector-routing.cc.
References ns3::Time::As(), CheckCacheStateAndFlush(), ns3::Names::FindName(), ns3::OutputStreamWrapper::GetStream(), m_ipv4, m_ipv4RouteCache, m_nixCache, and ns3::Now().
ResetTotalNeighbors()
void ns3::Ipv4NixVectorRouting::ResetTotalNeighbors (void) private
Upon a run-time topology change caches are flushed and the total number of neighbors is reset to zero.
RouteInput()
bool ns3::Ipv4NixVectorRouting::RouteInput (Ptr< const Packet > p, const Ipv4Header & header, Ptr< const NetDevice > idev, UnicastForwardCallback ucb, MulticastForwardCallback mcb, LocalDeliverCallback lcb, ErrorCallback ecb) private virtual
Route an input packet (to be forwarded or locally delivered)
This lookup is used in the forwarding process. The packet is handed over to the Ipv4RoutingProtocol, and will get forwarded onward by one of the callbacks. The Linux equivalent is ip_route_input(). There are four valid outcomes, and a matching callbacks to handle each.
Parameters
p received packet
header input parameter used to form a search key for a route
idev Pointer to ingress network device
ucb Callback for the case in which the packet is to be forwarded as unicast
mcb Callback for the case in which the packet is to be forwarded as multicast
lcb Callback for the case in which the packet is to be locally delivered
ecb Callback to call if there is an error in forwarding
Returns
true if the Ipv4RoutingProtocol takes responsibility for forwarding or delivering the packet, false otherwise
Implements ns3::Ipv4RoutingProtocol.
Definition at line 659 of file ipv4-nix-vector-routing.cc.
References ns3::NixVector::BitCount(), CheckCacheStateAndFlush(), ns3::NixVector::ExtractNeighborIndex(), FindNetDeviceForNixIndex(), FindTotalNeighbors(), ns3::Ipv4Header::GetDestination(), ns3::Node::GetDevice(), ns3::Node::GetId(), GetIpv4RouteInCache(), ns3::Ipv4InterfaceAddress::GetLocal(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_ipv4, m_ipv4RouteCache, m_node, m_totalNeighbors, NS_ASSERT, NS_LOG_FUNCTION_NOARGS, NS_LOG_LOGIC, ns3::Ipv4Route::SetDestination(), ns3::Ipv4Route::SetGateway(), ns3::Ipv4Route::SetOutputDevice(), and ns3::Ipv4Route::SetSource().
RouteOutput()
Ptr< Ipv4Route > ns3::Ipv4NixVectorRouting::RouteOutput (Ptr< Packet > p, const Ipv4Header & header, Ptr< NetDevice > oif, Socket::SocketErrno & sockerr) private virtual
Query routing cache for an existing route, for an outbound packet.
This lookup is used by transport protocols. It does not cause any packet to be forwarded, and is synchronous. Can be used for multicast or unicast. The Linux equivalent is ip_route_output()
The header input parameter may have an uninitialized value for the source address, but the destination address should always be properly set by the caller.
Parameters
p packet to be routed. Note that this method may modify the packet. Callers may also pass in a null pointer.
header input parameter (used to form key to search for the route)
oif Output interface Netdevice. May be zero, or may be bound via socket options to a particular output interface.
sockerr Output parameter; socket errno
Returns
a code that indicates what happened in the lookup
Implements ns3::Ipv4RoutingProtocol.
Definition at line 536 of file ipv4-nix-vector-routing.cc.
References ns3::NixVector::BitCount(), CheckCacheStateAndFlush(), ns3::NixVector::Copy(), ns3::Socket::ERROR_NOROUTETOHOST, ns3::Socket::ERROR_NOTERROR, ns3::NixVector::ExtractNeighborIndex(), FindNetDeviceForNixIndex(), FindTotalNeighbors(), ns3::Ipv4Header::GetDestination(), ns3::Node::GetDevice(), GetIpv4RouteInCache(), ns3::Ipv4InterfaceAddress::GetLocal(), GetNixVector(), GetNixVectorInCache(), ns3::Ipv4Route::GetOutputDevice(), ns3::NixVector::GetRemainingBits(), m_ipv4, m_ipv4RouteCache, m_nixCache, m_node, m_totalNeighbors, NS_ASSERT_MSG, NS_LOG_DEBUG, NS_LOG_ERROR, NS_LOG_FUNCTION_NOARGS, NS_LOG_LOGIC, ns3::Ipv4Route::SetDestination(), ns3::Ipv4Route::SetGateway(), ns3::Packet::SetNixVector(), ns3::Ipv4Route::SetOutputDevice(), and ns3::Ipv4Route::SetSource().
SetIpv4()
void ns3::Ipv4NixVectorRouting::SetIpv4 (Ptr< Ipv4 > ipv4) private virtual
Parameters
ipv4 the ipv4 object this routing protocol is being associated with
Typically, invoked directly or indirectly from ns3::Ipv4::SetRoutingProtocol
Implements ns3::Ipv4RoutingProtocol.
Definition at line 64 of file ipv4-nix-vector-routing.cc.
References m_ipv4, NS_ASSERT, and NS_LOG_DEBUG.
SetNode()
void ns3::Ipv4NixVectorRouting::SetNode (Ptr< Node > node)
Set the Node pointer of the node for which this routing protocol is to be placed.
Parameters
node Node pointer
Definition at line 86 of file ipv4-nix-vector-routing.cc.
References m_node, and NS_LOG_FUNCTION_NOARGS.
Member Data Documentation
g_ipv4AddressToNodeMap
Ipv4NixVectorRouting::Ipv4AddressToNodeMap ns3::Ipv4NixVectorRouting::g_ipv4AddressToNodeMap static private
Definition at line 279 of file ipv4-nix-vector-routing.h.
Referenced by BuildIpv4AddressToNodeMap(), FlushGlobalNixRoutingCache(), and GetNodeByIp().
g_isCacheDirty
bool ns3::Ipv4NixVectorRouting::g_isCacheDirty = false static private
Flag to mark when caches are dirty and need to be flushed.
Used for lazy cleanup of caches when there are many topology changes.
Definition at line 240 of file ipv4-nix-vector-routing.h.
Referenced by CheckCacheStateAndFlush(), NotifyAddAddress(), NotifyInterfaceDown(), NotifyInterfaceUp(), and NotifyRemoveAddress().
m_ipv4
Ptr<Ipv4> ns3::Ipv4NixVectorRouting::m_ipv4 private
IPv4 object.
Definition at line 248 of file ipv4-nix-vector-routing.h.
Referenced by BuildNixVectorLocal(), DoDispose(), PrintRoutingTable(), RouteInput(), RouteOutput(), and SetIpv4().
m_ipv4RouteCache
Ipv4RouteMap_t ns3::Ipv4NixVectorRouting::m_ipv4RouteCache mutable private
Cache stores Ipv4Routes based on destination ip.
Definition at line 246 of file ipv4-nix-vector-routing.h.
Referenced by FlushIpv4RouteCache(), GetIpv4RouteInCache(), PrintRoutingTable(), RouteInput(), and RouteOutput().
m_nixCache
NixMap_t ns3::Ipv4NixVectorRouting::m_nixCache mutable private
Cache stores nix-vectors based on destination ip.
Definition at line 243 of file ipv4-nix-vector-routing.h.
Referenced by FlushNixCache(), GetNixVectorInCache(), PrintRoutingTable(), and RouteOutput().
m_node
Ptr<Node> ns3::Ipv4NixVectorRouting::m_node private
Node object.
Definition at line 249 of file ipv4-nix-vector-routing.h.
Referenced by BuildNixVectorLocal(), DoDispose(), FindNetDeviceForNixIndex(), FindTotalNeighbors(), RouteInput(), RouteOutput(), and SetNode().
m_totalNeighbors
uint32_t ns3::Ipv4NixVectorRouting::m_totalNeighbors private
Total neighbors used for nix-vector to determine number of bits.
Definition at line 252 of file ipv4-nix-vector-routing.h.
Referenced by RouteInput(), and RouteOutput().
The documentation for this class was generated from the following files:
src/nix-vector-routing/model/ipv4-nix-vector-routing.h
src/nix-vector-routing/model/ipv4-nix-vector-routing.cc