ns-3: ns3::VhtSigHeader Class Reference
ns3::VhtSigHeader Class Reference
Wifi Models
Implements the IEEE 802.11ac PHY header (VHT-SIG-A1/A2/B).
#include "wifi-phy-header.h"
Public Member Functions
VhtSigHeader ()
virtual ~VhtSigHeader ()
uint32_t Deserialize (Buffer::Iterator start)
uint16_t GetChannelWidth (void) const
Return the channel width (in MHz).
TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint8_t GetNStreams (void) const
Return the number of streams.
uint32_t GetSerializedSize (void) const
bool GetShortGuardInterval (void) const
Return the short GI field of VHT-SIG-A2.
bool GetShortGuardIntervalDisambiguation (void) const
Return the short GI NSYM disambiguation field of VHT-SIG-A2.
uint8_t GetSuMcs (void) const
Return the SU VHT MCS field of VHT-SIG-A2.
bool IsLdpcCoding (void) const
Return whether LDPC is used or not.
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetChannelWidth (uint16_t channelWidth)
Fill the channel width field of VHT-SIG-A1 (in MHz).
void SetCoding (bool ldpc)
Fill the coding field of VHT-SIG-A2.
void SetMuFlag (bool mu)
Set the Multi-User (MU) flag.
void SetNStreams (uint8_t nStreams)
Fill the number of streams field of VHT-SIG-A1.
void SetShortGuardInterval (bool sgi)
Fill the short guard interval field of VHT-SIG-A2.
void SetShortGuardIntervalDisambiguation (bool disambiguation)
Fill the short GI NSYM disambiguation field of VHT-SIG-A2.
void SetSuMcs (uint8_t mcs)
Fill the SU VHT MCS field of VHT-SIG-A2.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_bw
BW.
uint8_t m_coding
SU/MU coding (0 for BCC, 1 for LDPC)
bool m_mu
This is used to decide whether MU SIG-B should be added or not.
uint8_t m_nsts
NSTS.
uint8_t m_sgi
Short GI.
uint8_t m_sgi_disambiguation
Short GI NSYM Disambiguation.
uint8_t m_suMcs
SU VHT MCS.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implements the IEEE 802.11ac PHY header (VHT-SIG-A1/A2/B).
Introspection did not find any typical Config paths.
See section 21.3.8 in IEEE 802.11-2016.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 16 bytes (on a 64-bit architecture).
Definition at line 252 of file wifi-phy-header.h.
Constructor & Destructor Documentation
VhtSigHeader()
ns3::VhtSigHeader::VhtSigHeader ()
Definition at line 487 of file wifi-phy-header.cc.
~VhtSigHeader()
ns3::VhtSigHeader::~VhtSigHeader () virtual
Definition at line 497 of file wifi-phy-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::VhtSigHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 681 of file wifi-phy-header.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_bw, m_coding, m_mu, m_nsts, m_sgi, m_sgi_disambiguation, m_suMcs, ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU32(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetChannelWidth()
uint16_t ns3::VhtSigHeader::GetChannelWidth (void) const
Return the channel width (in MHz).
Returns
the channel width (in MHz)
Definition at line 570 of file wifi-phy-header.cc.
References m_bw.
Referenced by ns3::WifiPpdu::GetTxVector(), and Print().
GetInstanceTypeId()
TypeId ns3::VhtSigHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 513 of file wifi-phy-header.cc.
References GetTypeId().
GetNStreams()
uint8_t ns3::VhtSigHeader::GetNStreams (void) const
Return the number of streams.
Returns
the number of streams
Definition at line 598 of file wifi-phy-header.cc.
References m_nsts.
Referenced by ns3::WifiPpdu::GetTxVector().
GetSerializedSize()
uint32_t ns3::VhtSigHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 530 of file wifi-phy-header.cc.
References m_mu.
GetShortGuardInterval()
bool ns3::VhtSigHeader::GetShortGuardInterval (void) const
Return the short GI field of VHT-SIG-A2.
Returns
the short GI field of VHT-SIG-A2
Definition at line 610 of file wifi-phy-header.cc.
References m_sgi.
Referenced by ns3::WifiPpdu::GetTxDuration(), and ns3::WifiPpdu::GetTxVector().
GetShortGuardIntervalDisambiguation()
bool ns3::VhtSigHeader::GetShortGuardIntervalDisambiguation (void) const
Return the short GI NSYM disambiguation field of VHT-SIG-A2.
Returns
the short GI NSYM disambiguation field of VHT-SIG-A2
Definition at line 622 of file wifi-phy-header.cc.
References m_sgi_disambiguation.
Referenced by ns3::WifiPpdu::GetTxDuration().
GetSuMcs()
uint8_t ns3::VhtSigHeader::GetSuMcs (void) const
Return the SU VHT MCS field of VHT-SIG-A2.
Returns
the SU VHT MCS field of VHT-SIG-A2
Definition at line 648 of file wifi-phy-header.cc.
References m_suMcs.
Referenced by ns3::WifiPpdu::GetTxVector().
GetTypeId()
TypeId ns3::VhtSigHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 502 of file wifi-phy-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
IsLdpcCoding()
bool ns3::VhtSigHeader::IsLdpcCoding (void) const
Return whether LDPC is used or not.
Returns
whether LDPC is used or not
Definition at line 634 of file wifi-phy-header.cc.
References m_coding.
Referenced by ns3::WifiPpdu::GetTxVector().
Print()
void ns3::VhtSigHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 519 of file wifi-phy-header.cc.
References GetChannelWidth(), m_coding, m_mu, m_nsts, m_sgi, and m_suMcs.
Serialize()
void ns3::VhtSigHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 654 of file wifi-phy-header.cc.
References m_bw, m_coding, m_mu, m_nsts, m_sgi, m_sgi_disambiguation, m_suMcs, and visualizer.core::start().
SetChannelWidth()
void ns3::VhtSigHeader::SetChannelWidth (uint16_t channelWidth)
Fill the channel width field of VHT-SIG-A1 (in MHz).
Parameters
channelWidth the channel width (in MHz)
Definition at line 549 of file wifi-phy-header.cc.
References m_bw.
Referenced by ns3::WifiPpdu::SetPhyHeaders().
SetCoding()
void ns3::VhtSigHeader::SetCoding (bool ldpc)
Fill the coding field of VHT-SIG-A2.
Parameters
ldpc whether LDPC is used or not
Definition at line 628 of file wifi-phy-header.cc.
References m_coding.
Referenced by ns3::WifiPpdu::SetPhyHeaders().
SetMuFlag()
void ns3::VhtSigHeader::SetMuFlag (bool mu)
Set the Multi-User (MU) flag.
Parameters
mu the MU flag
Definition at line 543 of file wifi-phy-header.cc.
References m_mu.
Referenced by ns3::WifiPpdu::SetPhyHeaders().
SetNStreams()
void ns3::VhtSigHeader::SetNStreams (uint8_t nStreams)
Fill the number of streams field of VHT-SIG-A1.
Parameters
nStreams the number of streams
Definition at line 591 of file wifi-phy-header.cc.
References m_nsts, and NS_ASSERT.
Referenced by ns3::WifiPpdu::SetPhyHeaders().
SetShortGuardInterval()
void ns3::VhtSigHeader::SetShortGuardInterval (bool sgi)
Fill the short guard interval field of VHT-SIG-A2.
Parameters
sgi whether short guard interval is used or not
Definition at line 604 of file wifi-phy-header.cc.
References m_sgi.
Referenced by ns3::WifiPpdu::SetPhyHeaders().
SetShortGuardIntervalDisambiguation()
void ns3::VhtSigHeader::SetShortGuardIntervalDisambiguation (bool disambiguation)
Fill the short GI NSYM disambiguation field of VHT-SIG-A2.
Parameters
disambiguation whether short GI NSYM disambiguation is set or not
Definition at line 616 of file wifi-phy-header.cc.
References m_sgi_disambiguation.
Referenced by ns3::WifiPpdu::SetPhyHeaders().
SetSuMcs()
void ns3::VhtSigHeader::SetSuMcs (uint8_t mcs)
Fill the SU VHT MCS field of VHT-SIG-A2.
Parameters
mcs the SU VHT MCS field of VHT-SIG-A2
Definition at line 641 of file wifi-phy-header.cc.
References m_suMcs, and NS_ASSERT.
Referenced by ns3::WifiPpdu::SetPhyHeaders().
Member Data Documentation
m_bw
uint8_t ns3::VhtSigHeader::m_bw private
BW.
Definition at line 353 of file wifi-phy-header.h.
Referenced by Deserialize(), GetChannelWidth(), Serialize(), and SetChannelWidth().
m_coding
uint8_t ns3::VhtSigHeader::m_coding private
SU/MU coding (0 for BCC, 1 for LDPC)
Definition at line 359 of file wifi-phy-header.h.
Referenced by Deserialize(), IsLdpcCoding(), Print(), Serialize(), and SetCoding().
m_mu
bool ns3::VhtSigHeader::m_mu private
This is used to decide whether MU SIG-B should be added or not.
Definition at line 363 of file wifi-phy-header.h.
Referenced by Deserialize(), GetSerializedSize(), Print(), Serialize(), and SetMuFlag().
m_nsts
uint8_t ns3::VhtSigHeader::m_nsts private
NSTS.
Definition at line 354 of file wifi-phy-header.h.
Referenced by Deserialize(), GetNStreams(), Print(), Serialize(), and SetNStreams().
m_sgi
uint8_t ns3::VhtSigHeader::m_sgi private
Short GI.
Definition at line 357 of file wifi-phy-header.h.
Referenced by Deserialize(), GetShortGuardInterval(), Print(), Serialize(), and SetShortGuardInterval().
m_sgi_disambiguation
uint8_t ns3::VhtSigHeader::m_sgi_disambiguation private
Short GI NSYM Disambiguation.
Definition at line 358 of file wifi-phy-header.h.
Referenced by Deserialize(), GetShortGuardIntervalDisambiguation(), Serialize(), and SetShortGuardIntervalDisambiguation().
m_suMcs
uint8_t ns3::VhtSigHeader::m_suMcs private
SU VHT MCS.
Definition at line 360 of file wifi-phy-header.h.
Referenced by Deserialize(), GetSuMcs(), Print(), Serialize(), and SetSuMcs().
The documentation for this class was generated from the following files:
src/wifi/model/wifi-phy-header.h
src/wifi/model/wifi-phy-header.cc