ns-3: ns3::dsr::DsrPassiveBuffEntry Class Reference
ns3::dsr::DsrPassiveBuffEntry Class Reference
DSR Routing
DSR Passive Buffer Entry.
#include "dsr-passive-buff.h"
Public Member Functions
DsrPassiveBuffEntry (Ptr< const Packet > pa=0, Ipv4Address d=Ipv4Address(), Ipv4Address s=Ipv4Address(), Ipv4Address n=Ipv4Address(), uint16_t i=0, uint16_t f=0, uint8_t seg=0, Time exp=Simulator::Now(), uint8_t p=0)
Construct a DsrPassiveBuffEntry with the given parameters.
Ipv4Address GetDestination () const
Get destination address function.
Time GetExpireTime () const
Get expire time.
uint16_t GetFragmentOffset () const
Get fragment offset function.
uint16_t GetIdentification () const
Get identification function.
Ipv4Address GetNextHop () const
Get next hop address function.
Ptr< const Packet > GetPacket () const
Get packet function.
uint8_t GetProtocol () const
Get protocol.
uint8_t GetSegsLeft () const
Get segments left function.
Ipv4Address GetSource () const
Get source address function.
bool operator== (DsrPassiveBuffEntry const &o) const
Compare send buffer entries.
void SetDestination (Ipv4Address d)
Set destination address function.
void SetExpireTime (Time exp)
Set expire time.
void SetFragmentOffset (uint16_t f)
Set fragment offset function.
void SetIdentification (uint16_t i)
Set identification function.
void SetNextHop (Ipv4Address n)
Set next hop address function.
void SetPacket (Ptr< const Packet > p)
Set packet function.
void SetProtocol (uint8_t p)
Set protocol function.
void SetSegsLeft (uint8_t seg)
Set segments left.
void SetSource (Ipv4Address s)
Set surce address function.
Private Attributes
Ipv4Address m_dst
Destination address.
Time m_expire
Expire time for queue entry.
uint16_t m_fragmentOffset
Fragment offset.
uint16_t m_identification
Identification.
Ipv4Address m_nextHop
Nexthop address.
Ptr< const Packet > m_packet
Data packet.
uint8_t m_protocol
The protocol number.
uint8_t m_segsLeft
Segments left.
Ipv4Address m_source
Source address.
Detailed Description
DSR Passive Buffer Entry.
Definition at line 45 of file dsr-passive-buff.h.
Constructor & Destructor Documentation
DsrPassiveBuffEntry()
ns3::dsr::DsrPassiveBuffEntry::DsrPassiveBuffEntry (Ptr< const Packet > pa = 0, Ipv4Address d = Ipv4Address (), Ipv4Address s = Ipv4Address (), Ipv4Address n = Ipv4Address (), uint16_t i = 0, uint16_t f = 0, uint8_t seg = 0, Time exp = Simulator::Now (), uint8_t p = 0) inline
Construct a DsrPassiveBuffEntry with the given parameters.
Parameters
pa packet
d IPv4 address of the destination
s IPv4 address of the source
n IPv4 address of the next hop node
i ID
f fragment offset
seg number of segments left
exp expiration time
p protocol number
Definition at line 61 of file dsr-passive-buff.h.
Member Function Documentation
GetDestination()
Ipv4Address ns3::dsr::DsrPassiveBuffEntry::GetDestination () const inline
Get destination address function.
Returns
the destination IP address
Definition at line 106 of file dsr-passive-buff.h.
References m_dst.
Referenced by ns3::dsr::DsrPassiveBuffer::AllEqual(), ns3::dsr::DsrPassiveBuffer::Drop(), and ns3::dsr::DsrPassiveBuffer::Enqueue().
GetExpireTime()
Time ns3::dsr::DsrPassiveBuffEntry::GetExpireTime () const inline
Get expire time.
Returns
the expire time
Definition at line 210 of file dsr-passive-buff.h.
References m_expire, and ns3::Simulator::Now().
Referenced by ns3::dsr::IsExpired::operator()().
GetFragmentOffset()
uint16_t ns3::dsr::DsrPassiveBuffEntry::GetFragmentOffset () const inline
Get fragment offset function.
Returns
the fragment offset
Definition at line 170 of file dsr-passive-buff.h.
References m_fragmentOffset.
Referenced by ns3::dsr::DsrPassiveBuffer::AllEqual(), and ns3::dsr::DsrPassiveBuffer::Enqueue().
GetIdentification()
uint16_t ns3::dsr::DsrPassiveBuffEntry::GetIdentification () const inline
Get identification function.
Returns
the identification
Definition at line 154 of file dsr-passive-buff.h.
References m_identification.
Referenced by ns3::dsr::DsrPassiveBuffer::AllEqual(), and ns3::dsr::DsrPassiveBuffer::Enqueue().
GetNextHop()
Ipv4Address ns3::dsr::DsrPassiveBuffEntry::GetNextHop () const inline
Get next hop address function.
Returns
the next hop IP address
Definition at line 138 of file dsr-passive-buff.h.
References m_nextHop.
Referenced by ns3::dsr::DsrPassiveBuffer::AllEqual(), ns3::dsr::DsrPassiveBuffer::DropLink(), ns3::dsr::DsrPassiveBuffer::Enqueue(), and ns3::dsr::DsrPassiveBuffer::LinkEqual().
GetPacket()
Ptr<const Packet> ns3::dsr::DsrPassiveBuffEntry::GetPacket () const inline
Get packet function.
Returns
the current packet
Definition at line 90 of file dsr-passive-buff.h.
References m_packet.
Referenced by ns3::dsr::DsrPassiveBuffer::AllEqual(), ns3::dsr::DsrPassiveBuffer::Dequeue(), ns3::dsr::DsrPassiveBuffer::Drop(), ns3::dsr::DsrPassiveBuffer::DropLink(), and ns3::dsr::DsrPassiveBuffer::Enqueue().
GetProtocol()
uint8_t ns3::dsr::DsrPassiveBuffEntry::GetProtocol () const inline
Get protocol.
Returns
the protocol number
Definition at line 226 of file dsr-passive-buff.h.
References m_protocol.
GetSegsLeft()
uint8_t ns3::dsr::DsrPassiveBuffEntry::GetSegsLeft () const inline
Get segments left function.
Returns
the number of segments left
Definition at line 186 of file dsr-passive-buff.h.
References m_segsLeft.
Referenced by ns3::dsr::DsrPassiveBuffer::AllEqual(), and ns3::dsr::DsrPassiveBuffer::Enqueue().
GetSource()
Ipv4Address ns3::dsr::DsrPassiveBuffEntry::GetSource () const inline
Get source address function.
Returns
the source IP address
Definition at line 122 of file dsr-passive-buff.h.
References m_source.
Referenced by ns3::dsr::DsrPassiveBuffer::AllEqual(), ns3::dsr::DsrPassiveBuffer::DropLink(), ns3::dsr::DsrPassiveBuffer::Enqueue(), and ns3::dsr::DsrPassiveBuffer::LinkEqual().
operator==()
bool ns3::dsr::DsrPassiveBuffEntry::operator== (DsrPassiveBuffEntry const & o) const inline
Compare send buffer entries.
Parameters
o passive buffer entry to compare
Returns
true if equal
Definition at line 80 of file dsr-passive-buff.h.
References m_dst, m_expire, m_nextHop, m_packet, and m_source.
SetDestination()
void ns3::dsr::DsrPassiveBuffEntry::SetDestination (Ipv4Address d) inline
Set destination address function.
Parameters
d the destination IP address
Definition at line 114 of file dsr-passive-buff.h.
References m_dst.
Referenced by ns3::dsr::DsrRouting::PassiveEntryCheck().
SetExpireTime()
void ns3::dsr::DsrPassiveBuffEntry::SetExpireTime (Time exp) inline
Set expire time.
Parameters
exp the expire time
Definition at line 202 of file dsr-passive-buff.h.
References m_expire, and ns3::Simulator::Now().
Referenced by ns3::dsr::DsrPassiveBuffer::Enqueue().
SetFragmentOffset()
void ns3::dsr::DsrPassiveBuffEntry::SetFragmentOffset (uint16_t f) inline
Set fragment offset function.
Parameters
f the fragment offset
Definition at line 178 of file dsr-passive-buff.h.
References f(), and m_fragmentOffset.
Referenced by ns3::dsr::DsrRouting::PassiveEntryCheck().
SetIdentification()
void ns3::dsr::DsrPassiveBuffEntry::SetIdentification (uint16_t i) inline
Set identification function.
Parameters
i the identification
Definition at line 162 of file dsr-passive-buff.h.
References m_identification.
Referenced by ns3::dsr::DsrRouting::PassiveEntryCheck().
SetNextHop()
void ns3::dsr::DsrPassiveBuffEntry::SetNextHop (Ipv4Address n) inline
Set next hop address function.
Parameters
n the next hop address
Definition at line 146 of file dsr-passive-buff.h.
References m_nextHop, and sample-rng-plot::n.
SetPacket()
void ns3::dsr::DsrPassiveBuffEntry::SetPacket (Ptr< const Packet > p) inline
Set packet function.
Parameters
p the current packet
Definition at line 98 of file dsr-passive-buff.h.
References m_packet.
Referenced by ns3::dsr::DsrRouting::PassiveEntryCheck().
SetProtocol()
void ns3::dsr::DsrPassiveBuffEntry::SetProtocol (uint8_t p) inline
Set protocol function.
Parameters
p the protocol
Definition at line 218 of file dsr-passive-buff.h.
References m_protocol.
SetSegsLeft()
void ns3::dsr::DsrPassiveBuffEntry::SetSegsLeft (uint8_t seg) inline
Set segments left.
Parameters
seg the number of segments left
Definition at line 194 of file dsr-passive-buff.h.
References m_segsLeft.
Referenced by ns3::dsr::DsrRouting::PassiveEntryCheck().
SetSource()
void ns3::dsr::DsrPassiveBuffEntry::SetSource (Ipv4Address s) inline
Set surce address function.
Parameters
s the source IP address
Definition at line 130 of file dsr-passive-buff.h.
References m_source.
Referenced by ns3::dsr::DsrRouting::PassiveEntryCheck().
Member Data Documentation
m_dst
Ipv4Address ns3::dsr::DsrPassiveBuffEntry::m_dst private
Destination address.
Definition at line 235 of file dsr-passive-buff.h.
Referenced by GetDestination(), operator==(), and SetDestination().
m_expire
Time ns3::dsr::DsrPassiveBuffEntry::m_expire private
Expire time for queue entry.
Definition at line 247 of file dsr-passive-buff.h.
Referenced by GetExpireTime(), operator==(), and SetExpireTime().
m_fragmentOffset
uint16_t ns3::dsr::DsrPassiveBuffEntry::m_fragmentOffset private
Fragment offset.
Definition at line 243 of file dsr-passive-buff.h.
Referenced by GetFragmentOffset(), and SetFragmentOffset().
m_identification
uint16_t ns3::dsr::DsrPassiveBuffEntry::m_identification private
Identification.
Definition at line 241 of file dsr-passive-buff.h.
Referenced by GetIdentification(), and SetIdentification().
m_nextHop
Ipv4Address ns3::dsr::DsrPassiveBuffEntry::m_nextHop private
Nexthop address.
Definition at line 239 of file dsr-passive-buff.h.
Referenced by GetNextHop(), operator==(), and SetNextHop().
m_packet
Ptr<const Packet> ns3::dsr::DsrPassiveBuffEntry::m_packet private
Data packet.
Definition at line 233 of file dsr-passive-buff.h.
Referenced by GetPacket(), operator==(), and SetPacket().
m_protocol
uint8_t ns3::dsr::DsrPassiveBuffEntry::m_protocol private
The protocol number.
Definition at line 249 of file dsr-passive-buff.h.
Referenced by GetProtocol(), and SetProtocol().
m_segsLeft
uint8_t ns3::dsr::DsrPassiveBuffEntry::m_segsLeft private
Segments left.
Definition at line 245 of file dsr-passive-buff.h.
Referenced by GetSegsLeft(), and SetSegsLeft().
m_source
Ipv4Address ns3::dsr::DsrPassiveBuffEntry::m_source private
Source address.
Definition at line 237 of file dsr-passive-buff.h.
Referenced by GetSource(), operator==(), and SetSource().
The documentation for this class was generated from the following file:
src/dsr/model/dsr-passive-buff.h