ns-3: ns3::NonCommunicatingNetDevice Class Reference
ns3::NonCommunicatingNetDevice Class Reference
Spectrum Models
This class implements a device which does not communicate, in the sense that it does not interact with the above protocol stack.
#include "non-communicating-net-device.h"
Public Member Functions
NonCommunicatingNetDevice ()
virtual ~NonCommunicatingNetDevice ()
virtual void AddLinkChangeCallback (Callback< void > callback)
virtual Address GetAddress (void) const
virtual Address GetBroadcast (void) const
virtual Ptr< Channel > GetChannel (void) const
virtual uint32_t GetIfIndex (void) const
virtual uint16_t GetMtu (void) const
virtual Address GetMulticast (Ipv4Address addr) const
Make and return a MAC multicast address using the provided multicast group.
virtual Address GetMulticast (Ipv6Address addr) const
Get the MAC multicast address corresponding to the IPv6 address provided.
virtual Ptr< Node > GetNode (void) const
Ptr< Object > GetPhy () const
virtual bool IsBridge (void) const
Return true if the net device is acting as a bridge.
virtual bool IsBroadcast (void) const
virtual bool IsLinkUp (void) const
virtual bool IsMulticast (void) const
virtual bool IsPointToPoint (void) const
Return true if the net device is on a point-to-point link.
virtual bool NeedsArp (void) const
virtual bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)
virtual bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
virtual void SetAddress (Address address)
Set the address of this interface.
void SetChannel (Ptr< Channel > c)
This class doesn't talk directly with the underlying channel (a dedicated PHY class is expected to do it), however the NetDevice specification features a GetChannel() method.
virtual void SetIfIndex (const uint32_t index)
virtual bool SetMtu (const uint16_t mtu)
virtual void SetNode (Ptr< Node > node)
void SetPhy (Ptr< Object > phy)
Set the Phy object which is attached to this device.
virtual void SetPromiscReceiveCallback (PromiscReceiveCallback cb)
virtual void SetReceiveCallback (NetDevice::ReceiveCallback cb)
virtual bool SupportsSendFrom (void) const
Public Member Functions inherited from ns3::NetDevice
virtual ~NetDevice ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::NetDevice
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual void DoDispose (void)
Destructor implementation.
Private Attributes
Ptr< Channel > m_channel
Channel used by the NetDevice.
uint32_t m_ifIndex
Interface index.
Ptr< Node > m_node
node this NetDevice is associated to
Ptr< Object > m_phy
Phy object.
Additional Inherited Members
Public Types inherited from ns3::NetDevice
typedef void(* LinkChangeTracedCallback) (void)
TracedCallback signature for link changed event.
enum PacketType {
PACKET_HOST = 1 , NS3_PACKET_HOST = PACKET_HOST , PACKET_BROADCAST , NS3_PACKET_BROADCAST = PACKET_BROADCAST ,
PACKET_MULTICAST , NS3_PACKET_MULTICAST = PACKET_MULTICAST , PACKET_OTHERHOST , NS3_PACKET_OTHERHOST = PACKET_OTHERHOST
}
Packet types are used as they are in Linux.
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address &, const Address &, enum PacketType > PromiscReceiveCallback
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address & > ReceiveCallback
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class implements a device which does not communicate, in the sense that it does not interact with the above protocol stack.
The purpose of this NetDevice is to be used for devices such as microwave ovens, waveform generators and spectrum analyzers. Since the ns-3 channel API is strongly based on the presence of NetDevice class instances, it is convenient to provide a NetDevice that can be used with such non-communicating devices.
Config Paths
ns3::NonCommunicatingNetDevice is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::NonCommunicatingNetDevice"
Attributes
Phy: The PHY layer attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::Object>
Initial value: 0x0
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 64 bytes (on a 64-bit architecture).
Definition at line 53 of file non-communicating-net-device.h.
Constructor & Destructor Documentation
NonCommunicatingNetDevice()
ns3::NonCommunicatingNetDevice::NonCommunicatingNetDevice ()
Definition at line 53 of file non-communicating-net-device.cc.
References NS_LOG_FUNCTION.
~NonCommunicatingNetDevice()
ns3::NonCommunicatingNetDevice::~NonCommunicatingNetDevice () virtual
Definition at line 58 of file non-communicating-net-device.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddLinkChangeCallback()
void ns3::NonCommunicatingNetDevice::AddLinkChangeCallback (Callback< void > callback) virtual
Parameters
callback the callback to invoke
Add a callback invoked whenever the link status changes to UP. This callback is typically used by the IP/ARP layer to flush the ARP cache and by IPv6 stack to flush NDISC cache whenever the link goes up.
Implements ns3::NetDevice.
Definition at line 226 of file non-communicating-net-device.cc.
References NS_LOG_FUNCTION.
DoDispose()
void ns3::NonCommunicatingNetDevice::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 64 of file non-communicating-net-device.cc.
References ns3::Object::DoDispose(), m_channel, m_node, m_phy, and NS_LOG_FUNCTION.
GetAddress()
Address ns3::NonCommunicatingNetDevice::GetAddress (void) const virtual
Returns
the current Address of this interface.
Implements ns3::NetDevice.
Definition at line 109 of file non-communicating-net-device.cc.
References NS_LOG_FUNCTION.
GetBroadcast()
Address ns3::NonCommunicatingNetDevice::GetBroadcast (void) const virtual
Returns
the broadcast address supported by this netdevice.
Calling this method is invalid if IsBroadcast returns not true.
Implements ns3::NetDevice.
Definition at line 123 of file non-communicating-net-device.cc.
References NS_LOG_FUNCTION.
GetChannel()
Ptr< Channel > ns3::NonCommunicatingNetDevice::GetChannel (void) const virtual
Returns
the channel this NetDevice is connected to. The value returned can be zero if the NetDevice is not yet connected to any channel or if the underlying NetDevice has no concept of a channel. i.e., callers must check for zero and be ready to handle it.
Implements ns3::NetDevice.
Definition at line 204 of file non-communicating-net-device.cc.
References m_channel, and NS_LOG_FUNCTION.
GetIfIndex()
uint32_t ns3::NonCommunicatingNetDevice::GetIfIndex (void) const virtual
Returns
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 82 of file non-communicating-net-device.cc.
References m_ifIndex, and NS_LOG_FUNCTION.
GetMtu()
uint16_t ns3::NonCommunicatingNetDevice::GetMtu (void) const virtual
Returns
the link-level MTU in bytes for this interface.
This value is typically used by the IP layer to perform IP fragmentation when needed.
Implements ns3::NetDevice.
Definition at line 96 of file non-communicating-net-device.cc.
References NS_LOG_FUNCTION.
GetMulticast() [1/2]
Address ns3::NonCommunicatingNetDevice::GetMulticast (Ipv4Address multicastGroup) const virtual
Make and return a MAC multicast address using the provided multicast group.
RFC 1112 says that an Ipv4 host group address is mapped to an Ethernet multicast address by placing the low-order 23-bits of the IP address into the low-order 23 bits of the Ethernet multicast address 01-00-5E-00-00-00 (hex). Similar RFCs exist for Ipv6 and Eui64 mappings. This method performs the multicast address creation function appropriate to the underlying MAC address of the device. This MAC address is encapsulated in an abstract Address to avoid dependencies on the exact MAC address format.
In the case of net devices that do not support multicast, clients are expected to test NetDevice::IsMulticast and avoid attempting to map multicast packets. Subclasses of NetDevice that do support multicasting are expected to override this method and provide an implementation appropriate to the particular device.
Parameters
multicastGroup The IP address for the multicast group destination of the packet.
Returns
The MAC multicast Address used to send packets to the provided multicast group.
Warning
Calling this method is invalid if IsMulticast returns not true.
See also
IsMulticast()
Implements ns3::NetDevice.
Definition at line 137 of file non-communicating-net-device.cc.
References NS_LOG_FUNCTION.
GetMulticast() [2/2]
Address ns3::NonCommunicatingNetDevice::GetMulticast (Ipv6Address addr) const virtual
Get the MAC multicast address corresponding to the IPv6 address provided.
Parameters
addr IPv6 address
Returns
the MAC multicast address
Warning
Calling this method is invalid if IsMulticast returns not true.
Implements ns3::NetDevice.
Definition at line 144 of file non-communicating-net-device.cc.
References NS_LOG_FUNCTION.
GetNode()
Ptr< Node > ns3::NonCommunicatingNetDevice::GetNode (void) const virtual
Returns
the node base class which contains this network interface.
When a subclass needs to get access to the underlying node base class to print the nodeid for example, it can invoke this method.
Implements ns3::NetDevice.
Definition at line 166 of file non-communicating-net-device.cc.
References m_node, and NS_LOG_FUNCTION.
GetPhy()
Ptr< Object > ns3::NonCommunicatingNetDevice::GetPhy (void) const
Returns
a reference to the PHY object embedded in this NetDevice.
Definition at line 189 of file non-communicating-net-device.cc.
References m_phy, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::NonCommunicatingNetDevice::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 38 of file non-communicating-net-device.cc.
References GetPhy(), ns3::MakePointerAccessor(), ns3::TypeId::SetParent(), and SetPhy().
IsBridge()
bool ns3::NonCommunicatingNetDevice::IsBridge (void) const virtual
Return true if the net device is acting as a bridge.
Returns
value of m_isBridge flag
Implements ns3::NetDevice.
Definition at line 158 of file non-communicating-net-device.cc.
References NS_LOG_FUNCTION.
IsBroadcast()
bool ns3::NonCommunicatingNetDevice::IsBroadcast (void) const virtual
Returns
true if this interface supports a broadcast address, false otherwise.
Implements ns3::NetDevice.
Definition at line 116 of file non-communicating-net-device.cc.
References NS_LOG_FUNCTION.
IsLinkUp()
bool ns3::NonCommunicatingNetDevice::IsLinkUp (void) const virtual
Returns
true if link is up; false otherwise
Implements ns3::NetDevice.
Definition at line 219 of file non-communicating-net-device.cc.
References NS_LOG_FUNCTION.
IsMulticast()
bool ns3::NonCommunicatingNetDevice::IsMulticast (void) const virtual
Returns
value of m_isMulticast flag
Implements ns3::NetDevice.
Definition at line 130 of file non-communicating-net-device.cc.
References NS_LOG_FUNCTION.
IsPointToPoint()
bool ns3::NonCommunicatingNetDevice::IsPointToPoint (void) const virtual
Return true if the net device is on a point-to-point link.
Returns
value of m_isPointToPoint flag
Implements ns3::NetDevice.
Definition at line 151 of file non-communicating-net-device.cc.
References NS_LOG_FUNCTION.
NeedsArp()
bool ns3::NonCommunicatingNetDevice::NeedsArp (void) const virtual
Returns
true if ARP is needed, false otherwise.
Called by higher-layers to check if this NetDevice requires ARP to be used.
Implements ns3::NetDevice.
Definition at line 212 of file non-communicating-net-device.cc.
References NS_LOG_FUNCTION.
Send()
bool ns3::NonCommunicatingNetDevice::Send (Ptr< Packet > packet, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device to the specified destination Address
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 252 of file non-communicating-net-device.cc.
References NS_LOG_FUNCTION.
SendFrom()
bool ns3::NonCommunicatingNetDevice::SendFrom (Ptr< Packet > packet, const Address & source, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
source source mac address (so called "MAC spoofing")
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device with the specified source and destination Addresses.
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 259 of file non-communicating-net-device.cc.
References NS_LOG_FUNCTION.
SetAddress()
void ns3::NonCommunicatingNetDevice::SetAddress (Address address) virtual
Set the address of this interface.
Parameters
address address to set
Implements ns3::NetDevice.
Definition at line 103 of file non-communicating-net-device.cc.
References NS_LOG_FUNCTION.
SetChannel()
void ns3::NonCommunicatingNetDevice::SetChannel (Ptr< Channel > c)
This class doesn't talk directly with the underlying channel (a dedicated PHY class is expected to do it), however the NetDevice specification features a GetChannel() method.
This method here is therefore provide to allow NonCommunicatingNetDevice::GetChannel() to have something meaningful to return.
Parameters
c the underlying channel
Definition at line 197 of file non-communicating-net-device.cc.
References m_channel, and NS_LOG_FUNCTION.
SetIfIndex()
void ns3::NonCommunicatingNetDevice::SetIfIndex (const uint32_t index) virtual
Parameters
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 75 of file non-communicating-net-device.cc.
References m_ifIndex, and NS_LOG_FUNCTION.
SetMtu()
bool ns3::NonCommunicatingNetDevice::SetMtu (const uint16_t mtu) virtual
Parameters
mtu MTU value, in bytes, to set for the device
Returns
whether the MTU value was within legal bounds
Override for default MTU defined on a per-type basis.
Implements ns3::NetDevice.
Definition at line 89 of file non-communicating-net-device.cc.
References NS_LOG_FUNCTION.
SetNode()
void ns3::NonCommunicatingNetDevice::SetNode (Ptr< Node > node) virtual
Parameters
node the node associated to this netdevice.
This method is called from ns3::Node::AddDevice.
Implements ns3::NetDevice.
Definition at line 173 of file non-communicating-net-device.cc.
References m_node, and NS_LOG_FUNCTION.
SetPhy()
void ns3::NonCommunicatingNetDevice::SetPhy (Ptr< Object > phy)
Set the Phy object which is attached to this device.
This object is needed so that we can set/get attributes and connect to trace sources of the PHY from the net device.
Parameters
phy the Phy object embedded within this device.
Definition at line 181 of file non-communicating-net-device.cc.
References m_phy, NS_LOG_FUNCTION, and third::phy.
Referenced by GetTypeId().
SetPromiscReceiveCallback()
void ns3::NonCommunicatingNetDevice::SetPromiscReceiveCallback (PromiscReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received in promiscuous mode and must be forwarded to the higher layers.
Enables netdevice promiscuous mode and sets the callback that will handle promiscuous mode packets. Note, promiscuous mode packets means all packets, including those packets that can be sensed by the netdevice but which are intended to be received by other hosts.
Implements ns3::NetDevice.
Definition at line 238 of file non-communicating-net-device.cc.
References NS_LOG_FUNCTION.
SetReceiveCallback()
void ns3::NonCommunicatingNetDevice::SetReceiveCallback (NetDevice::ReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received and must be forwarded to the higher layers.
Set the callback to be used to notify higher layers when a packet has been received.
Implements ns3::NetDevice.
Definition at line 232 of file non-communicating-net-device.cc.
References NS_LOG_FUNCTION.
SupportsSendFrom()
bool ns3::NonCommunicatingNetDevice::SupportsSendFrom (void) const virtual
Returns
true if this interface supports a bridging mode, false otherwise.
Implements ns3::NetDevice.
Definition at line 244 of file non-communicating-net-device.cc.
References NS_LOG_FUNCTION.
Member Data Documentation
m_channel
Ptr<Channel> ns3::NonCommunicatingNetDevice::m_channel private
Channel used by the NetDevice.
Definition at line 130 of file non-communicating-net-device.h.
Referenced by DoDispose(), GetChannel(), and SetChannel().
m_ifIndex
uint32_t ns3::NonCommunicatingNetDevice::m_ifIndex private
Interface index.
Definition at line 131 of file non-communicating-net-device.h.
Referenced by GetIfIndex(), and SetIfIndex().
m_node
Ptr<Node> ns3::NonCommunicatingNetDevice::m_node private
node this NetDevice is associated to
Definition at line 129 of file non-communicating-net-device.h.
Referenced by DoDispose(), GetNode(), and SetNode().
m_phy
Ptr<Object> ns3::NonCommunicatingNetDevice::m_phy private
Phy object.
Definition at line 132 of file non-communicating-net-device.h.
Referenced by DoDispose(), GetPhy(), and SetPhy().
The documentation for this class was generated from the following files:
src/spectrum/model/non-communicating-net-device.h
src/spectrum/model/non-communicating-net-device.cc