ns-3: ns3::Ipv4Address Class Reference
ns3::Ipv4Address Class Reference
Network » Address
Ipv4 addresses are stored in host order in this class.
#include "ipv4-address.h"
Public Member Functions
Ipv4Address ()
Ipv4Address (char const *address)
Constructs an Ipv4Address by parsing a the input C-string.
Ipv4Address (uint32_t address)
input address is in host order.
Ipv4Address CombineMask (Ipv4Mask const &mask) const
Combine this address with a network mask.
uint32_t Get (void) const
Get the host-order 32-bit IP address.
Ipv4Address GetSubnetDirectedBroadcast (Ipv4Mask const &mask) const
Generate subnet-directed broadcast address corresponding to mask.
bool IsAny (void) const
bool IsBroadcast (void) const
NS_DEPRECATED_3_31 bool IsEqual (const Ipv4Address &other) const
Comparison operation between two Ipv4Addresses.
bool IsInitialized (void) const
bool IsLocalhost (void) const
bool IsLocalMulticast (void) const
bool IsMulticast (void) const
bool IsSubnetDirectedBroadcast (Ipv4Mask const &mask) const
Generate subnet-directed broadcast address corresponding to mask.
operator Address () const
Convert an instance of this class to a polymorphic Address instance.
void Print (std::ostream &os) const
Print this address to the given output stream.
void Serialize (uint8_t buf[4]) const
Serialize this address to a 4-byte buffer.
void Set (char const *address)
Sets an Ipv4Address by parsing a the input C-string.
void Set (uint32_t address)
input address is in host order.
Static Public Member Functions
static Ipv4Address ConvertFrom (const Address &address)
static Ipv4Address Deserialize (const uint8_t buf[4])
static Ipv4Address GetAny (void)
static Ipv4Address GetBroadcast (void)
static Ipv4Address GetLoopback (void)
static Ipv4Address GetZero (void)
static bool IsMatchingType (const Address &address)
Private Member Functions
Address ConvertTo (void) const
Convert to an Address type.
Static Private Member Functions
static uint8_t GetType (void)
Get the underlying address type (automatically assigned).
Private Attributes
uint32_t m_address
IPv4 address.
bool m_initialized
IPv4 address has been explicitly initialized to a valid value.
Friends
bool operator!= (Ipv4Address const &a, Ipv4Address const &b)
Not equal to operator.
bool operator< (Ipv4Address const &a, Ipv4Address const &b)
Less than to operator.
bool operator== (Ipv4Address const &a, Ipv4Address const &b)
Equal to operator.
Detailed Description
Ipv4 addresses are stored in host order in this class.
See also
Ipv4Address Attribute
Definition at line 41 of file ipv4-address.h.
Constructor & Destructor Documentation
Ipv4Address() [1/3]
ns3::Ipv4Address::Ipv4Address ()
Definition at line 202 of file ipv4-address.cc.
References NS_LOG_FUNCTION.
Referenced by CombineMask(), and GetSubnetDirectedBroadcast().
Ipv4Address() [2/3]
ns3::Ipv4Address::Ipv4Address (uint32_t address) explicit
input address is in host order.
Parameters
address The host order 32-bit address
Definition at line 207 of file ipv4-address.cc.
References first::address, m_address, m_initialized, and NS_LOG_FUNCTION.
Ipv4Address() [3/3]
ns3::Ipv4Address::Ipv4Address (char const * address)
Constructs an Ipv4Address by parsing a the input C-string.
Input address is in format: hhh.xxx.xxx.lll where h is the high byte and l the low byte
Parameters
address C-string containing the address as described above
Definition at line 213 of file ipv4-address.cc.
References first::address, ns3::AsciiToIpv4Host(), m_address, m_initialized, and NS_LOG_FUNCTION.
Member Function Documentation
CombineMask()
Ipv4Address ns3::Ipv4Address::CombineMask (Ipv4Mask const & mask) const
Combine this address with a network mask.
This method returns an IPv4 address that is this address combined (bitwise and) with a network mask, yielding an IPv4 network address.
Parameters
mask a network mask
Returns
the address combined with the mask
Definition at line 242 of file ipv4-address.cc.
References Ipv4Address(), Get(), ns3::Ipv4Mask::Get(), and NS_LOG_FUNCTION.
Referenced by ns3::IpcsClassifierRecord::CheckMatchDstAddr(), ns3::IpcsClassifierRecord::CheckMatchSrcAddr(), ns3::Rip::DoSendRouteUpdate(), ns3::Rip::HandleRequests(), ns3::Rip::HandleResponses(), ns3::Ipv4AddressGeneratorImpl::IsNetworkAllocated(), ns3::Ipv4L3Protocol::LocalDeliver(), ns3::Ipv4EndPointDemux::Lookup(), ns3::GlobalRouter::ProcessBridgedBroadcastLink(), ns3::GlobalRouter::ProcessSingleBroadcastLink(), ns3::Ipv4L3Protocol::SelectSourceAddress(), ns3::Ipv4L3Protocol::Send(), ns3::GlobalRouteManagerImpl::SPFAddASExternal(), ns3::GlobalRouteManagerImpl::SPFIntraAddStub(), and ns3::GlobalRouteManagerImpl::SPFIntraAddTransit().
ConvertFrom()
Ipv4Address ns3::Ipv4Address::ConvertFrom (const Address & address) static
Parameters
address a polymorphic address
Returns
a new Ipv4Address from the polymorphic address
This function performs a type check and asserts if the type of the input address is not compatible with an Ipv4Address.
Definition at line 377 of file ipv4-address.cc.
References first::address, Deserialize(), GetType(), NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::UdpSocketImpl::DoSend(), ns3::UdpSocketImpl::GetPeerName(), ns3::ThreeGppHttpClient::OpenConnection(), ns3::PbbAddressBlockIpv4::PrintAddress(), ns3::PbbMessageIpv4::PrintOriginatorAddress(), ns3::UdpClient::Send(), ns3::UdpEchoClient::Send(), ns3::TcpL4Protocol::SendPacket(), ns3::UdpTraceClient::SendPacket(), ns3::PbbAddressBlockIpv4::SerializeAddress(), ns3::PbbMessageIpv4::SerializeOriginatorAddress(), ns3::ThreeGppHttpServer::StartApplication(), ns3::UdpClient::StartApplication(), ns3::UdpEchoClient::StartApplication(), and ns3::UdpTraceClient::StartApplication().
ConvertTo()
Address ns3::Ipv4Address::ConvertTo (void) const private
Convert to an Address type.
Returns
the Address corresponding to this object.
Definition at line 368 of file ipv4-address.cc.
References GetType(), NS_LOG_FUNCTION, and Serialize().
Deserialize()
Ipv4Address ns3::Ipv4Address::Deserialize (const uint8_t buf[4]) static
Parameters
buf buffer to read address from
Returns
an Ipv4Address
The input address is expected to be in network byte order format.
Definition at line 329 of file ipv4-address.cc.
References m_address, m_initialized, and NS_LOG_FUNCTION.
Referenced by ns3::NscTcpSocketImpl::CompleteFork(), ns3::NscTcpSocketImpl::ConnectionSucceeded(), ns3::InetSocketAddress::ConvertFrom(), ConvertFrom(), ns3::dsr::DsrOptionRreqHeader::Deserialize(), ns3::dsr::DsrOptionRrepHeader::Deserialize(), ns3::dsr::DsrOptionSRHeader::Deserialize(), ns3::Ipv4FlowProbeTag::Deserialize(), ns3::Ipv4PacketInfoTag::Deserialize(), ns3::PbbAddressBlockIpv4::DeserializeAddress(), ns3::PbbMessageIpv4::DeserializeOriginatorAddress(), and ns3::Ipv6Address::GetIpv4MappedAddress().
Get()
uint32_t ns3::Ipv4Address::Get (void) const
Get the host-order 32-bit IP address.
Returns
the host-order 32-bit IP address
Definition at line 221 of file ipv4-address.cc.
References m_address, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4InterfaceAddress::Ipv4InterfaceAddress(), ns3::DhcpServer::AddStaticDhcpEntry(), ns3::Ipv4L3Protocol::BuildHeader(), ns3::EpcTftClassifier::Classify(), CombineMask(), ns3::Ipv4L3Protocol::DecreaseIdentification(), SwitchFlowTableTestCase::DoRun(), GetSubnetDirectedBroadcast(), ns3::Ipv4AddressGeneratorImpl::Init(), ns3::Ipv4AddressGeneratorImpl::InitAddress(), ns3::DhcpHelper::InstallDhcpServer(), ns3::DhcpHelper::InstallFixedAddress(), ns3::Ipv4Mask::IsMatch(), IsSubnetDirectedBroadcast(), ns3::DhcpServer::NetHandler(), ns3::PacketSink::AddressHash::operator()(), ns3::Ipv4L3Protocol::ProcessFragment(), ns3::DhcpClient::Request(), ns3::Ipv4Header::Serialize(), ns3::RipRte::Serialize(), ns3::olsr::MessageHeader::Serialize(), ns3::GtpcIes::SerializeFteid(), ns3::Ipv4AddressHelper::SetBase(), ns3::GlobalRouteManagerImpl::SPFIntraAddStub(), ns3::DhcpServer::StartApplication(), and ns3::WriteTo().
GetAny()
Ipv4Address ns3::Ipv4Address::GetAny (void) static
Returns
the 0.0.0.0 address
Definition at line 402 of file ipv4-address.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::DhcpClient::DhcpClient(), ns3::Ipv4RawSocketImpl::Ipv4RawSocketImpl(), ns3::NoBackhaulEpcHelper::NoBackhaulEpcHelper(), Tunnel::Tunnel(), ns3::Ipv4EndPointDemux::Allocate(), ns3::Ipv4RawSocketImpl::Bind(), ns3::NscTcpSocketImpl::Bind(), ns3::TcpSocketBase::Bind(), ns3::UdpSocketImpl::Bind(), BuildAppsTest(), ns3::olsr::Bug780Test::CreateNodes(), ns3::olsr::RoutingProtocol::DoInitialize(), ns3::TcpGeneralTest::DoRun(), ns3::LenaDeactivateBearerTestCase::DoRun(), ns3::Rip::DoSendRouteUpdate(), ns3::UdpSocketImpl::DoSendTo(), experiment(), ns3::Ipv4RawSocketImpl::ForwardUp(), ns3::Ipv4RawSocketImpl::GetPeerName(), ns3::Rip::HandleRequests(), InstallPacketSink(), ns3::Ipv4L3Protocol::IpMulticastForward(), ns3::Ipv4EndPointDemux::Lookup(), ns3::dsdv::RoutingProtocol::NotifyAddAddress(), ns3::dsdv::RoutingProtocol::NotifyInterfaceUp(), ns3::dsdv::RoutingProtocol::NotifyRemoveAddress(), Experiment::Run(), RunSimulation(), ns3::Ipv4L3Protocol::Send(), ns3::Rip::SendRouteRequest(), ns3::Ipv4RawSocketImpl::SendTo(), ns3::Ipv4EndPointDemux::SimpleLookup(), ns3::UdpEchoServer::StartApplication(), ns3::UdpServer::StartApplication(), ns3::DhcpClient::StartApplication(), ns3::DhcpServer::StartApplication(), ns3::V4Ping::StartApplication(), ns3::V4TraceRoute::StartApplication(), and ns3::BsmApplication::StartApplication().
GetBroadcast()
Ipv4Address ns3::Ipv4Address::GetBroadcast (void) static
Returns
the 255.255.255.255 address
Definition at line 409 of file ipv4-address.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::ArpL3Protocol::SendArpRequest(), and ns3::aodv::RoutingProtocol::SendRerrMessage().
GetLoopback()
Ipv4Address ns3::Ipv4Address::GetLoopback (void) static
Returns
the 127.0.0.1 address
Definition at line 416 of file ipv4-address.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Ipv4InterfaceAddress::Ipv4InterfaceAddress(), ns3::aodv::LoopbackTestCase::DoRun(), ns3::Ipv4L3Protocol::RemoveAddress(), RunSimulation(), ns3::aodv::LoopbackTestCase::SendData(), ns3::aodv::RoutingProtocol::SetIpv4(), ns3::dsdv::RoutingProtocol::SetIpv4(), and ns3::Ipv4L3Protocol::SetupLoopback().
GetSubnetDirectedBroadcast()
Ipv4Address ns3::Ipv4Address::GetSubnetDirectedBroadcast (Ipv4Mask const & mask) const
Generate subnet-directed broadcast address corresponding to mask.
The subnet-directed broadcast address has the host bits set to all ones. If this method is called with a mask of 255.255.255.255, (i.e., the address is a /32 address), the program will assert, since there is no subnet associated with a /32 address.
Parameters
mask a network mask
Returns
a broadcast address for the subnet.
Definition at line 249 of file ipv4-address.cc.
References Ipv4Address(), Get(), ns3::Ipv4Mask::GetInverse(), ns3::Ipv4Mask::GetOnes(), NS_ASSERT_MSG, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4FlowProbe::DropLogger(), and ns3::olsr::RoutingProtocol::SendPacket().
GetType()
uint8_t ns3::Ipv4Address::GetType (void) static private
Get the underlying address type (automatically assigned).
Returns
the address type
Definition at line 387 of file ipv4-address.cc.
References NS_LOG_FUNCTION_NOARGS, and ns3::Address::Register().
Referenced by ConvertFrom(), ConvertTo(), and IsMatchingType().
GetZero()
Ipv4Address ns3::Ipv4Address::GetZero (void) static
Returns
the 0.0.0.0 address
Definition at line 395 of file ipv4-address.cc.
References NS_LOG_FUNCTION_NOARGS, and zero.
Referenced by ns3::TapFdNetDeviceHelper::TapFdNetDeviceHelper(), ns3::Ipv4RoutingTableEntry::CreateDefaultRoute(), ns3::TapFdNetDeviceHelper::CreateFileDescriptor(), ns3::Ipv4FlowClassifier::FindFlow(), ns3::TcpSocketBase::GetSockName(), ns3::UdpSocketImpl::GetSockName(), ns3::Ipv4RoutingTableEntry::IsDefault(), ns3::Ipv4RoutingTableEntry::IsGateway(), ns3::Rip::Lookup(), ns3::Ipv4StaticRouting::LookupStatic(), ns3::TcpSocketBase::RecvFrom(), and ns3::GlobalRouteManagerImpl::SPFNexthopCalculation().
IsAny()
bool ns3::Ipv4Address::IsAny (void) const
Returns
true if address is 0.0.0.0; false otherwise
Definition at line 280 of file ipv4-address.cc.
References m_address, and NS_LOG_FUNCTION.
Referenced by ns3::Rip::Lookup(), ns3::Ipv4L3Protocol::Send(), and ns3::Ipv4L3Protocol::SendRealOut().
IsBroadcast()
bool ns3::Ipv4Address::IsBroadcast (void) const
Returns
true if address is 255.255.255.255; false otherwise
Definition at line 294 of file ipv4-address.cc.
References m_address, and NS_LOG_FUNCTION.
Referenced by ns3::TapBridge::CreateTap(), ns3::UdpSocketImpl::DoSendTo(), ns3::Ipv4L3Protocol::IpForward(), ns3::Ipv4L3Protocol::IsUnicast(), ns3::Ipv4L3Protocol::LocalDeliver(), ns3::dsr::DsrRouteCache::RebuildBestRouteTable(), ns3::aodv::RoutingProtocol::RouteInput(), ns3::dsdv::RoutingProtocol::RouteInput(), ns3::Rip::RouteInput(), ns3::Ipv4Interface::Send(), and ns3::Ipv4L3Protocol::Send().
IsEqual()
NS_DEPRECATED_3_31 bool ns3::Ipv4Address::IsEqual (const Ipv4Address & other) const inline
Comparison operation between two Ipv4Addresses.
Deprecated:
Use the == operator (same functionality)
Parameters
other address to which to compare this address
Returns
True if the addresses are equal. False otherwise.
Definition at line 88 of file ipv4-address.h.
References m_address.
IsInitialized()
bool ns3::Ipv4Address::IsInitialized (void) const
Returns
true if address is initialized (i.e., set to something), false otherwise
Definition at line 273 of file ipv4-address.cc.
References m_initialized, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4L3Protocol::Send().
IsLocalhost()
bool ns3::Ipv4Address::IsLocalhost (void) const
Returns
true if address is 127.0.0.1; false otherwise
Definition at line 287 of file ipv4-address.cc.
References m_address, and NS_LOG_FUNCTION.
IsLocalMulticast()
bool ns3::Ipv4Address::IsLocalMulticast (void) const
Returns
true only if address is in local multicast address scope, 224.0.0.0/24
Definition at line 312 of file ipv4-address.cc.
References m_address, and NS_LOG_FUNCTION.
Referenced by ns3::Rip::Lookup(), ns3::Ipv4StaticRouting::LookupStatic(), and ns3::Ipv4L3Protocol::Send().
IsMatchingType()
bool ns3::Ipv4Address::IsMatchingType (const Address & address) static
Parameters
address an address to compare type with
Returns
true if the type of the address stored internally is compatible with the type of the input address, false otherwise.
Definition at line 357 of file ipv4-address.cc.
References first::address, GetType(), and NS_LOG_FUNCTION.
Referenced by ns3::TcpHeader::CalculateHeaderChecksum(), ns3::UdpHeader::CalculateHeaderChecksum(), ns3::UdpSocketImpl::DoSend(), ns3::UdpSocketImpl::GetPeerName(), ns3::ThreeGppHttpClient::OpenConnection(), ns3::UdpClient::Send(), ns3::UdpEchoClient::Send(), ns3::TcpL4Protocol::SendPacket(), ns3::UdpTraceClient::SendPacket(), ns3::ThreeGppHttpServer::StartApplication(), ns3::UdpClient::StartApplication(), ns3::UdpEchoClient::StartApplication(), and ns3::UdpTraceClient::StartApplication().
IsMulticast()
bool ns3::Ipv4Address::IsMulticast (void) const
Returns
true only if address is in the range 224.0.0.0 - 239.255.255.255
Definition at line 301 of file ipv4-address.cc.
References m_address, and NS_LOG_FUNCTION.
Referenced by ns3::dsr::DsrOptionRerr::DoSendError(), ns3::UdpSocketImpl::DoSendTo(), ns3::Ipv4L3Protocol::IpForward(), ns3::addressUtils::IsMulticast(), ns3::Ipv4L3Protocol::IsUnicast(), ns3::Ipv4L3Protocol::LocalDeliver(), ns3::dsr::DsrOptionSR::Process(), ns3::Ipv4L3Protocol::Receive(), ns3::aodv::RoutingProtocol::RouteInput(), ns3::dsdv::RoutingProtocol::RouteInput(), ns3::Ipv4ListRouting::RouteInput(), ns3::Ipv4StaticRouting::RouteInput(), ns3::Rip::RouteInput(), ns3::Ipv4GlobalRouting::RouteOutput(), ns3::Ipv4StaticRouting::RouteOutput(), ns3::Rip::RouteOutput(), and ns3::Ipv4Interface::Send().
IsSubnetDirectedBroadcast()
bool ns3::Ipv4Address::IsSubnetDirectedBroadcast (Ipv4Mask const & mask) const
Generate subnet-directed broadcast address corresponding to mask.
The subnet-directed broadcast address has the host bits set to all ones. If this method is called with a mask of 255.255.255.255, (i.e., the address is a /32 address), the program will assert, since there is no subnet associated with a /32 address.
Parameters
mask a network mask
Returns
true if the address, when combined with the input mask, has all of its host bits set to one
Definition at line 260 of file ipv4-address.cc.
References Get(), ns3::Ipv4Mask::GetInverse(), ns3::Ipv4Mask::GetOnes(), and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4L3Protocol::IsUnicast(), ns3::Ipv4L3Protocol::LocalDeliver(), ns3::Ipv4Interface::Send(), and ns3::Ipv4L3Protocol::Send().
operator Address()
ns3::Ipv4Address::operator Address () const
Convert an instance of this class to a polymorphic Address instance.
Returns
a new Address instance
Definition at line 362 of file ipv4-address.cc.
Print()
void ns3::Ipv4Address::Print (std::ostream & os) const
Print this address to the given output stream.
The print format is in the typical "192.168.1.1"
Parameters
os The output stream to which this Ipv4Address is printed
Definition at line 347 of file ipv4-address.cc.
References m_address, and NS_LOG_FUNCTION.
Referenced by ns3::NscTcpL4Protocol::AddInterface(), ns3::NscTcpSocketImpl::Connect(), ns3::PbbAddressBlockIpv4::PrintAddress(), and ns3::PbbMessageIpv4::PrintOriginatorAddress().
Serialize()
void ns3::Ipv4Address::Serialize (uint8_t buf[4]) const
Serialize this address to a 4-byte buffer.
Parameters
buf output buffer to which this address gets overwritten with this Ipv4Address
Definition at line 320 of file ipv4-address.cc.
References m_address, and NS_LOG_FUNCTION.
Referenced by ns3::InetSocketAddress::ConvertTo(), ConvertTo(), ns3::Mac48Address::GetMulticast(), ns3::ArpQueueDiscItem::Hash(), ns3::Ipv4QueueDiscItem::Hash(), ns3::Ipv6Address::MakeIpv4MappedAddress(), ns3::Ipv4FlowProbeTag::Serialize(), ns3::Ipv4PacketInfoTag::Serialize(), ns3::PbbAddressBlockIpv4::SerializeAddress(), and ns3::PbbMessageIpv4::SerializeOriginatorAddress().
Set() [1/2]
void ns3::Ipv4Address::Set (char const * address)
Sets an Ipv4Address by parsing a the input C-string.
Input address is in format: hhh.xxx.xxx.lll where h is the high byte and l the low byte
Parameters
address C-string containing the address as described above
Definition at line 234 of file ipv4-address.cc.
References first::address, ns3::AsciiToIpv4Host(), m_address, m_initialized, and NS_LOG_FUNCTION.
Set() [2/2]
void ns3::Ipv4Address::Set (uint32_t address)
input address is in host order.
Parameters
address The host order 32-bit address
Definition at line 227 of file ipv4-address.cc.
References first::address, m_address, m_initialized, and NS_LOG_FUNCTION.
Referenced by EpcTftClassifierTestSuite::EpcTftClassifierTestSuite(), ns3::GlobalRouter::GlobalRouter(), ns3::Ipv4Header::Deserialize(), ns3::RipRte::Deserialize(), ns3::GtpcIes::DeserializeFteid(), ns3::GlobalRouter::ProcessBridgedBroadcastLink(), ns3::GlobalRouter::ProcessSingleBroadcastLink(), and ns3::ReadFrom().
Friends And Related Function Documentation
operator!=
bool operator!= (Ipv4Address const & a, Ipv4Address const & b) friend
Not equal to operator.
Parameters
a the first operand.
b the first operand.
Returns
true if the operands are not equal.
Parameters
a the first operand
b the first operand
Returns
true if the operands are not equal
Definition at line 417 of file ipv4-address.h.
operator<
bool operator< (Ipv4Address const & a, Ipv4Address const & b) friend
Less than to operator.
Parameters
a the first operand.
b the first operand.
Returns
true if the first operand is less than the second.
Parameters
a the first operand
b the first operand
Returns
true if the operand a is less than operand b
Definition at line 428 of file ipv4-address.h.
operator==
bool operator== (Ipv4Address const & a, Ipv4Address const & b) friend
Equal to operator.
Parameters
a the first operand.
b the first operand.
Returns
true if the operands are equal.
Parameters
a the first operand
b the first operand
Returns
true if the operands are equal
Definition at line 406 of file ipv4-address.h.
Member Data Documentation
m_address
uint32_t ns3::Ipv4Address::m_address private
IPv4 address.
Definition at line 227 of file ipv4-address.h.
Referenced by Ipv4Address(), Deserialize(), Get(), IsAny(), IsBroadcast(), IsEqual(), IsLocalhost(), IsLocalMulticast(), IsMulticast(), Print(), Serialize(), and Set().
m_initialized
bool ns3::Ipv4Address::m_initialized private
IPv4 address has been explicitly initialized to a valid value.
Definition at line 228 of file ipv4-address.h.
Referenced by Ipv4Address(), Deserialize(), IsInitialized(), and Set().
The documentation for this class was generated from the following files:
src/network/utils/ipv4-address.h
src/network/utils/ipv4-address.cc