ns-3: ns3::dsdv::QueueEntry Class Reference
ns3::dsdv::QueueEntry Class Reference
DSDV Routing
DSDV Queue Entry.
#include "dsdv-packet-queue.h"
Public Types
typedef Ipv4RoutingProtocol::ErrorCallback ErrorCallback
Error callback function typedef.
typedef Ipv4RoutingProtocol::UnicastForwardCallback UnicastForwardCallback
Unicast forward call back function typedef.
Public Member Functions
QueueEntry (Ptr< const Packet > pa=0, Ipv4Header const &h=Ipv4Header(), UnicastForwardCallback ucb=UnicastForwardCallback(), ErrorCallback ecb=ErrorCallback())
c-tor
ErrorCallback GetErrorCallback () const
Get error callback function.
Time GetExpireTime () const
Get expire time.
Ipv4Header GetIpv4Header () const
Get IP header.
Ptr< const Packet > GetPacket () const
Get packet.
UnicastForwardCallback GetUnicastForwardCallback () const
Get unicast forward callback function.
bool operator== (QueueEntry const &o) const
Compare queue entries.
void SetErrorCallback (ErrorCallback ecb)
Set error callback function.
void SetExpireTime (Time exp)
Set expire time.
void SetIpv4Header (Ipv4Header h)
Set IP header.
void SetPacket (Ptr< const Packet > p)
Set packet.
void SetUnicastForwardCallback (UnicastForwardCallback ucb)
Set unicast forward callback function.
Private Attributes
ErrorCallback m_ecb
Error callback.
Time m_expire
Expire time for queue entry.
Ipv4Header m_header
IP header.
Ptr< const Packet > m_packet
Data packet.
UnicastForwardCallback m_ucb
Unicast forward callback.
Detailed Description
DSDV Queue Entry.
Definition at line 45 of file dsdv-packet-queue.h.
Member Typedef Documentation
ErrorCallback
typedef Ipv4RoutingProtocol::ErrorCallback ns3::dsdv::QueueEntry::ErrorCallback
Error callback function typedef.
Definition at line 51 of file dsdv-packet-queue.h.
UnicastForwardCallback
typedef Ipv4RoutingProtocol::UnicastForwardCallback ns3::dsdv::QueueEntry::UnicastForwardCallback
Unicast forward call back function typedef.
Definition at line 49 of file dsdv-packet-queue.h.
Constructor & Destructor Documentation
QueueEntry()
ns3::dsdv::QueueEntry::QueueEntry (Ptr< const Packet > pa = 0, Ipv4Header const & h = Ipv4Header (), UnicastForwardCallback ucb = UnicastForwardCallback (), ErrorCallback ecb = ErrorCallback ()) inline
c-tor
Parameters
pa the packet to create the entry
h the Ipv4Header
ucb the UnicastForwardCallback function
ecb the ErrorCallback function
Definition at line 60 of file dsdv-packet-queue.h.
Member Function Documentation
GetErrorCallback()
ErrorCallback ns3::dsdv::QueueEntry::GetErrorCallback () const inline
Get error callback function.
Returns
the error callback
Definition at line 102 of file dsdv-packet-queue.h.
References m_ecb.
GetExpireTime()
Time ns3::dsdv::QueueEntry::GetExpireTime () const inline
Get expire time.
Returns
the expire time
Definition at line 158 of file dsdv-packet-queue.h.
References m_expire, and ns3::Simulator::Now().
Referenced by ns3::dsdv::IsExpired::operator()().
GetIpv4Header()
Ipv4Header ns3::dsdv::QueueEntry::GetIpv4Header () const inline
Get IP header.
Returns
the IPv4 header
Definition at line 134 of file dsdv-packet-queue.h.
References m_header.
Referenced by ns3::dsdv::PacketQueue::Drop(), ns3::dsdv::PacketQueue::Enqueue(), and ns3::dsdv::RoutingProtocol::SendPacketFromQueue().
GetPacket()
Ptr<const Packet> ns3::dsdv::QueueEntry::GetPacket () const inline
Get packet.
Returns
the current packet
Definition at line 118 of file dsdv-packet-queue.h.
References m_packet.
Referenced by ns3::dsdv::PacketQueue::Drop(), ns3::dsdv::PacketQueue::Enqueue(), and ns3::dsdv::RoutingProtocol::SendPacketFromQueue().
GetUnicastForwardCallback()
UnicastForwardCallback ns3::dsdv::QueueEntry::GetUnicastForwardCallback () const inline
Get unicast forward callback function.
Returns
the unicast forward callback
Definition at line 86 of file dsdv-packet-queue.h.
References m_ucb.
Referenced by ns3::dsdv::RoutingProtocol::SendPacketFromQueue().
operator==()
bool ns3::dsdv::QueueEntry::operator== (QueueEntry const & o) const inline
Compare queue entries.
Parameters
o QueueEntry to compare
Returns
true if equal
Definition at line 76 of file dsdv-packet-queue.h.
References ns3::Ipv4Header::GetDestination(), m_expire, m_header, and m_packet.
SetErrorCallback()
void ns3::dsdv::QueueEntry::SetErrorCallback (ErrorCallback ecb) inline
Set error callback function.
Parameters
ecb the error callback
Definition at line 110 of file dsdv-packet-queue.h.
References m_ecb.
SetExpireTime()
void ns3::dsdv::QueueEntry::SetExpireTime (Time exp) inline
Set expire time.
Parameters
exp
Definition at line 150 of file dsdv-packet-queue.h.
References m_expire, and ns3::Simulator::Now().
Referenced by ns3::dsdv::PacketQueue::Enqueue().
SetIpv4Header()
void ns3::dsdv::QueueEntry::SetIpv4Header (Ipv4Header h) inline
Set IP header.
Parameters
h The IPv4 header
Definition at line 142 of file dsdv-packet-queue.h.
References m_header.
SetPacket()
void ns3::dsdv::QueueEntry::SetPacket (Ptr< const Packet > p) inline
Set packet.
Parameters
p The current packet
Definition at line 126 of file dsdv-packet-queue.h.
References m_packet.
SetUnicastForwardCallback()
void ns3::dsdv::QueueEntry::SetUnicastForwardCallback (UnicastForwardCallback ucb) inline
Set unicast forward callback function.
Parameters
ucb the unicast forward callback
Definition at line 94 of file dsdv-packet-queue.h.
References m_ucb.
Member Data Documentation
m_ecb
ErrorCallback ns3::dsdv::QueueEntry::m_ecb private
Error callback.
Definition at line 171 of file dsdv-packet-queue.h.
Referenced by GetErrorCallback(), and SetErrorCallback().
m_expire
Time ns3::dsdv::QueueEntry::m_expire private
Expire time for queue entry.
Definition at line 173 of file dsdv-packet-queue.h.
Referenced by GetExpireTime(), operator==(), and SetExpireTime().
m_header
Ipv4Header ns3::dsdv::QueueEntry::m_header private
IP header.
Definition at line 167 of file dsdv-packet-queue.h.
Referenced by GetIpv4Header(), operator==(), and SetIpv4Header().
m_packet
Ptr<const Packet> ns3::dsdv::QueueEntry::m_packet private
Data packet.
Definition at line 165 of file dsdv-packet-queue.h.
Referenced by GetPacket(), operator==(), and SetPacket().
m_ucb
UnicastForwardCallback ns3::dsdv::QueueEntry::m_ucb private
Unicast forward callback.
Definition at line 169 of file dsdv-packet-queue.h.
Referenced by GetUnicastForwardCallback(), and SetUnicastForwardCallback().
The documentation for this class was generated from the following file:
src/dsdv/model/dsdv-packet-queue.h