ns-3: ns3::GaussMarkovMobilityModel Class Reference
ns3::GaussMarkovMobilityModel Class Reference
Mobility
Gauss-Markov mobility model.
#include "gauss-markov-mobility-model.h"
Public Member Functions
GaussMarkovMobilityModel ()
Public Member Functions inherited from ns3::MobilityModel
MobilityModel ()
virtual ~MobilityModel ()=0
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
double GetDistanceFrom (Ptr< const MobilityModel > position) const
Vector GetPosition (void) const
double GetRelativeSpeed (Ptr< const MobilityModel > other) const
Vector GetVelocity (void) const
void SetPosition (const Vector &position)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type with the TypeId system.
Static Public Member Functions inherited from ns3::MobilityModel
static TypeId GetTypeId (void)
Register this type with the TypeId system.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual int64_t DoAssignStreams (int64_t)
The default implementation does nothing but return the passed-in parameter.
virtual void DoDispose (void)
Destructor implementation.
virtual Vector DoGetPosition (void) const
virtual Vector DoGetVelocity (void) const
virtual void DoSetPosition (const Vector &position)
void DoWalk (Time timeLeft)
Perform a walk operation.
void Start (void)
Initialize the model and calculate new velocity, direction, and pitch.
Private Attributes
double m_alpha
tunable constant in the model
Box m_bounds
bounding box
double m_Direction
current direction
EventId m_event
event id of scheduled start
ConstantVelocityHelper m_helper
constant velocity helper
double m_meanDirection
current mean direction
double m_meanPitch
current mean pitch
double m_meanVelocity
current mean velocity
Ptr< NormalRandomVariable > m_normalDirection
Gaussian rv for next direction value.
Ptr< NormalRandomVariable > m_normalPitch
Gaussian rv for next pitch.
Ptr< NormalRandomVariable > m_normalVelocity
Gaussian rv used to for next velocity.
double m_Pitch
current pitch
Ptr< RandomVariableStream > m_rndMeanDirection
rv used to assign avg direction
Ptr< RandomVariableStream > m_rndMeanPitch
rv used to assign avg.
Ptr< RandomVariableStream > m_rndMeanVelocity
rv used to assign avg velocity
Time m_timeStep
duraiton after which direction and speed should change
double m_Velocity
current velocity
Additional Inherited Members
Public Types inherited from ns3::MobilityModel
typedef void(* TracedCallback) (Ptr< const MobilityModel > model)
TracedCallback signature.
Protected Member Functions inherited from ns3::MobilityModel
void NotifyCourseChange (void) const
Must be invoked by subclasses when the course of the position changes to notify course change listeners.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Gauss-Markov mobility model.
This is a 3D version of the Gauss-Markov mobility model described in [1]. Unlike the other mobility models in ns-3, which are memoryless, the Gauss Markov model has both memory and variability. The tunable alpha parameter determines the how much memory and randomness you want to model. Each object starts with a specific velocity, direction (radians), and pitch angle (radians) equivalent to the mean velocity, direction, and pitch. At each timestep, a new velocity, direction, and pitch angle are generated based upon the previous value, the mean value, and a gaussian random variable. This version is suited for simple airplane flight, where direction, velocity, and pitch are the key variables. The motion field is limited by a 3D bounding box (called "box") which is a 3D version of the "rectangle" field that is used in 2-dimensional ns-3 mobility models.
Here is an example of how to implement the model and set the initial node positions:
MobilityHelper mobility;
mobility.SetMobilityModel ("ns3::GaussMarkovMobilityModel",
  "Bounds", BoxValue (Box (0, 150000, 0, 150000, 0, 10000)),
  "TimeStep", TimeValue (Seconds (0.5)),
  "Alpha", DoubleValue (0.85),
  "MeanVelocity", StringValue ("ns3::UniformRandomVariable[Min=800|Max=1200]"),
  "MeanDirection", StringValue ("ns3::UniformRandomVariable[Min=0|Max=6.283185307]"),
  "MeanPitch", StringValue ("ns3::UniformRandomVariable[Min=0.05|Max=0.05]"),
  "NormalVelocity", StringValue ("ns3::NormalRandomVariable[Mean=0.0|Variance=0.0|Bound=0.0]"),
  "NormalDirection", StringValue ("ns3::NormalRandomVariable[Mean=0.0|Variance=0.2|Bound=0.4]"),
  "NormalPitch", StringValue ("ns3::NormalRandomVariable[Mean=0.0|Variance=0.02|Bound=0.04]"));
mobility.SetPositionAllocator ("ns3::RandomBoxPositionAllocator",
  "X", StringValue ("ns3::UniformRandomVariable[Min=0|Max=150000]"),
  "Y", StringValue ("ns3::UniformRandomVariable[Min=0|Max=150000]"),
  "Z", StringValue ("ns3::UniformRandomVariable[Min=0|Max=10000]"));
mobility.Install (wifiStaNodes);
[1] Tracy Camp, Jeff Boleng, Vanessa Davies, "A Survey of Mobility Models for Ad Hoc Network Research", Wireless Communications and Mobile Computing, Wiley, vol.2 iss.5, September 2002, pp.483-502
Config Paths
ns3::GaussMarkovMobilityModel is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::MobilityModel/$ns3::GaussMarkovMobilityModel"
Attributes
Bounds: Bounds of the area to cruise.
Set with class: BoxValue
Underlying type: Box
Initial value: -100|100|-100|100|0|100
Flags: construct write read
TimeStep: Change current direction and speed after moving for this time.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+09ns
Flags: construct write read
Alpha: A constant representing the tunable parameter in the Gauss-Markov model.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 1
Flags: construct write read
MeanVelocity: A random variable used to assign the average velocity.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::RandomVariableStream>
Initial value: ns3::UniformRandomVariable[Min=0.0|Max=1.0]
Flags: construct write read
MeanDirection: A random variable used to assign the average direction.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::RandomVariableStream>
Initial value: ns3::UniformRandomVariable[Min=0.0|Max=6.283185307]
Flags: construct write read
MeanPitch: A random variable used to assign the average pitch.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::RandomVariableStream>
Initial value: ns3::ConstantRandomVariable[Constant=0.0]
Flags: construct write read
NormalVelocity: A gaussian random variable used to calculate the next velocity value.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::NormalRandomVariable>
Initial value: ns3::NormalRandomVariable[Mean=0.0|Variance=1.0|Bound=10.0]
Flags: construct write read
NormalDirection: A gaussian random variable used to calculate the next direction value.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::NormalRandomVariable>
Initial value: ns3::NormalRandomVariable[Mean=0.0|Variance=1.0|Bound=10.0]
Flags: construct write read
NormalPitch: A gaussian random variable used to calculate the next pitch value.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::NormalRandomVariable>
Initial value: ns3::NormalRandomVariable[Mean=0.0|Variance=1.0|Bound=10.0]
Flags: construct write read
Attributes defined in parent class ns3::MobilityModel
Position: The current position of the mobility model.
Set with class: Vector3DValue
Underlying type: Vector3D
Flags: write read
Velocity: The current velocity of the mobility model.
Set with class: Vector3DValue
Underlying type: Vector3D
Flags: read
No TraceSources are defined for this type.
TraceSources defined in parent class ns3::MobilityModel
CourseChange: The value of the position and/or velocity vector changed
Callback signature: ns3::MobilityModel::TracedCallback
Size of this type is 304 bytes (on a 64-bit architecture).
Definition at line 80 of file gauss-markov-mobility-model.h.
Constructor & Destructor Documentation
GaussMarkovMobilityModel()
ns3::GaussMarkovMobilityModel::GaussMarkovMobilityModel ()
Definition at line 88 of file gauss-markov-mobility-model.cc.
References m_event, m_helper, m_meanDirection, m_meanPitch, m_meanVelocity, ns3::Simulator::ScheduleNow(), Start(), and ns3::ConstantVelocityHelper::Unpause().
Member Function Documentation
DoAssignStreams()
int64_t ns3::GaussMarkovMobilityModel::DoAssignStreams (int64_t start) private virtual
The default implementation does nothing but return the passed-in parameter.
Subclasses using random variables are expected to override this.
Parameters
start starting stream index
Returns
the number of streams used
Reimplemented from ns3::MobilityModel.
Definition at line 222 of file gauss-markov-mobility-model.cc.
References m_normalDirection, m_normalPitch, m_normalVelocity, m_rndMeanDirection, m_rndMeanPitch, m_rndMeanVelocity, and ns3::RandomVariableStream::SetStream().
DoDispose()
void ns3::GaussMarkovMobilityModel::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 196 of file gauss-markov-mobility-model.cc.
References ns3::Object::DoDispose().
DoGetPosition()
Vector ns3::GaussMarkovMobilityModel::DoGetPosition (void) const private virtual
Returns
the current position.
Concrete subclasses of this base class must implement this method.
Implements ns3::MobilityModel.
Definition at line 203 of file gauss-markov-mobility-model.cc.
References ns3::ConstantVelocityHelper::GetCurrentPosition(), m_helper, and ns3::ConstantVelocityHelper::Update().
DoGetVelocity()
Vector ns3::GaussMarkovMobilityModel::DoGetVelocity (void) const private virtual
Returns
the current velocity.
Concrete subclasses of this base class must implement this method.
Implements ns3::MobilityModel.
Definition at line 216 of file gauss-markov-mobility-model.cc.
References ns3::ConstantVelocityHelper::GetVelocity(), and m_helper.
DoSetPosition()
void ns3::GaussMarkovMobilityModel::DoSetPosition (const Vector & position) private virtual
Parameters
position the position to set.
Concrete subclasses of this base class must implement this method.
Implements ns3::MobilityModel.
Definition at line 209 of file gauss-markov-mobility-model.cc.
References ns3::EventId::Cancel(), m_event, m_helper, ns3::Simulator::ScheduleNow(), ns3::ConstantVelocityHelper::SetPosition(), and Start().
DoWalk()
void ns3::GaussMarkovMobilityModel::DoWalk (Time timeLeft) private
Perform a walk operation.
Parameters
timeLeft time until Start method is called again
Definition at line 149 of file gauss-markov-mobility-model.cc.
References ns3::ConstantVelocityHelper::GetCurrentPosition(), ns3::Time::GetSeconds(), ns3::ConstantVelocityHelper::GetVelocity(), ns3::Box::IsInside(), m_bounds, m_Direction, m_event, m_helper, m_meanDirection, m_meanPitch, m_Pitch, ns3::MobilityModel::NotifyCourseChange(), ns3::Simulator::Schedule(), ns3::Seconds(), ns3::ConstantVelocityHelper::SetVelocity(), Start(), ns3::ConstantVelocityHelper::Unpause(), ns3::ConstantVelocityHelper::UpdateWithBounds(), ns3::Box::xMax, ns3::Box::xMin, ns3::Box::yMax, ns3::Box::yMin, ns3::Box::zMax, and ns3::Box::zMin.
Referenced by Start().
GetTypeId()
TypeId ns3::GaussMarkovMobilityModel::GetTypeId (void) static
Register this type with the TypeId system.
Returns
the object TypeId
Definition at line 33 of file gauss-markov-mobility-model.cc.
References m_alpha, m_bounds, m_normalDirection, m_normalPitch, m_normalVelocity, m_rndMeanDirection, m_rndMeanPitch, m_rndMeanVelocity, m_timeStep, ns3::MakeBoxAccessor(), ns3::MakeBoxChecker(), ns3::MakeDoubleAccessor(), ns3::MakePointerAccessor(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::Seconds(), and ns3::TypeId::SetParent().
Start()
void ns3::GaussMarkovMobilityModel::Start (void) private
Initialize the model and calculate new velocity, direction, and pitch.
Definition at line 98 of file gauss-markov-mobility-model.cc.
References DoWalk(), ns3::RandomVariableStream::GetValue(), m_alpha, m_Direction, m_helper, m_meanDirection, m_meanPitch, m_meanVelocity, m_normalDirection, m_normalPitch, m_normalVelocity, m_Pitch, m_rndMeanDirection, m_rndMeanPitch, m_rndMeanVelocity, m_timeStep, m_Velocity, ns3::ConstantVelocityHelper::SetVelocity(), ns3::ConstantVelocityHelper::Unpause(), and ns3::ConstantVelocityHelper::Update().
Referenced by GaussMarkovMobilityModel(), DoSetPosition(), and DoWalk().
Member Data Documentation
m_alpha
double ns3::GaussMarkovMobilityModel::m_alpha private
tunable constant in the model
Definition at line 106 of file gauss-markov-mobility-model.h.
Referenced by GetTypeId(), and Start().
m_bounds
Box ns3::GaussMarkovMobilityModel::m_bounds private
bounding box
Definition at line 120 of file gauss-markov-mobility-model.h.
Referenced by DoWalk(), and GetTypeId().
m_Direction
double ns3::GaussMarkovMobilityModel::m_Direction private
current direction
Definition at line 111 of file gauss-markov-mobility-model.h.
Referenced by DoWalk(), and Start().
m_event
EventId ns3::GaussMarkovMobilityModel::m_event private
event id of scheduled start
Definition at line 119 of file gauss-markov-mobility-model.h.
Referenced by GaussMarkovMobilityModel(), DoSetPosition(), and DoWalk().
m_helper
ConstantVelocityHelper ns3::GaussMarkovMobilityModel::m_helper private
constant velocity helper
Definition at line 104 of file gauss-markov-mobility-model.h.
Referenced by GaussMarkovMobilityModel(), DoGetPosition(), DoGetVelocity(), DoSetPosition(), DoWalk(), and Start().
m_meanDirection
double ns3::GaussMarkovMobilityModel::m_meanDirection private
current mean direction
Definition at line 108 of file gauss-markov-mobility-model.h.
Referenced by GaussMarkovMobilityModel(), DoWalk(), and Start().
m_meanPitch
double ns3::GaussMarkovMobilityModel::m_meanPitch private
current mean pitch
Definition at line 109 of file gauss-markov-mobility-model.h.
Referenced by GaussMarkovMobilityModel(), DoWalk(), and Start().
m_meanVelocity
double ns3::GaussMarkovMobilityModel::m_meanVelocity private
current mean velocity
Definition at line 107 of file gauss-markov-mobility-model.h.
Referenced by GaussMarkovMobilityModel(), and Start().
m_normalDirection
Ptr<NormalRandomVariable> ns3::GaussMarkovMobilityModel::m_normalDirection private
Gaussian rv for next direction value.
Definition at line 116 of file gauss-markov-mobility-model.h.
Referenced by DoAssignStreams(), GetTypeId(), and Start().
m_normalPitch
Ptr<NormalRandomVariable> ns3::GaussMarkovMobilityModel::m_normalPitch private
Gaussian rv for next pitch.
Definition at line 118 of file gauss-markov-mobility-model.h.
Referenced by DoAssignStreams(), GetTypeId(), and Start().
m_normalVelocity
Ptr<NormalRandomVariable> ns3::GaussMarkovMobilityModel::m_normalVelocity private
Gaussian rv used to for next velocity.
Definition at line 114 of file gauss-markov-mobility-model.h.
Referenced by DoAssignStreams(), GetTypeId(), and Start().
m_Pitch
double ns3::GaussMarkovMobilityModel::m_Pitch private
current pitch
Definition at line 112 of file gauss-markov-mobility-model.h.
Referenced by DoWalk(), and Start().
m_rndMeanDirection
Ptr<RandomVariableStream> ns3::GaussMarkovMobilityModel::m_rndMeanDirection private
rv used to assign avg direction
Definition at line 115 of file gauss-markov-mobility-model.h.
Referenced by DoAssignStreams(), GetTypeId(), and Start().
m_rndMeanPitch
Ptr<RandomVariableStream> ns3::GaussMarkovMobilityModel::m_rndMeanPitch private
rv used to assign avg.
pitch
Definition at line 117 of file gauss-markov-mobility-model.h.
Referenced by DoAssignStreams(), GetTypeId(), and Start().
m_rndMeanVelocity
Ptr<RandomVariableStream> ns3::GaussMarkovMobilityModel::m_rndMeanVelocity private
rv used to assign avg velocity
Definition at line 113 of file gauss-markov-mobility-model.h.
Referenced by DoAssignStreams(), GetTypeId(), and Start().
m_timeStep
Time ns3::GaussMarkovMobilityModel::m_timeStep private
duraiton after which direction and speed should change
Definition at line 105 of file gauss-markov-mobility-model.h.
Referenced by GetTypeId(), and Start().
m_Velocity
double ns3::GaussMarkovMobilityModel::m_Velocity private
current velocity
Definition at line 110 of file gauss-markov-mobility-model.h.
Referenced by Start().
The documentation for this class was generated from the following files:
src/mobility/model/gauss-markov-mobility-model.h
src/mobility/model/gauss-markov-mobility-model.cc