ns-3: ns3::Icmpv6OptionRedirected Class Reference
ns3::Icmpv6OptionRedirected Class Reference
Internet » IPv6 classes and sub-modules » ICMPv6 protocol and associated headers.
ICMPv6 redirected option.
#include "icmpv6-header.h"
Public Member Functions
Icmpv6OptionRedirected ()
Constructor.
virtual ~Icmpv6OptionRedirected ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
Ptr< Packet > GetPacket () const
Get the redirected packet.
virtual uint32_t GetSerializedSize () const
Get the serialized size.
virtual void Print (std::ostream &os) const
Print information.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetPacket (Ptr< Packet > packet)
Set the redirected packet.
Public Member Functions inherited from ns3::Icmpv6OptionHeader
Icmpv6OptionHeader ()
Constructor.
virtual ~Icmpv6OptionHeader ()
Destructor.
uint8_t GetLength () const
Get the length of the option in 8 bytes unit.
uint8_t GetType () const
Get the type of the option.
void SetLength (uint8_t len)
Set the length of the option.
void SetType (uint8_t type)
Set the type of the option.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the UID of this class.
Static Public Member Functions inherited from ns3::Icmpv6OptionHeader
static TypeId GetTypeId ()
Get the UID of this class.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Ptr< Packet > m_packet
The redirected packet.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
ICMPv6 redirected option.
Introspection did not find any typical Config paths.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 24 bytes (on a 64-bit architecture).
Definition at line 1724 of file icmpv6-header.h.
Constructor & Destructor Documentation
Icmpv6OptionRedirected()
ns3::Icmpv6OptionRedirected::Icmpv6OptionRedirected ()
Constructor.
Definition at line 1940 of file icmpv6-header.cc.
References ns3::Icmpv6Header::ICMPV6_OPT_REDIRECTED, NS_LOG_FUNCTION, and ns3::Icmpv6OptionHeader::SetType().
~Icmpv6OptionRedirected()
ns3::Icmpv6OptionRedirected::~Icmpv6OptionRedirected () virtual
Destructor.
Definition at line 1947 of file icmpv6-header.cc.
References m_packet, and NS_LOG_FUNCTION.
Member Function Documentation
Deserialize()
uint32_t ns3::Icmpv6OptionRedirected::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start start offset
Returns
length of packet
Reimplemented from ns3::Icmpv6OptionHeader.
Definition at line 1997 of file icmpv6-header.cc.
References ns3::Icmpv6OptionHeader::GetLength(), GetSerializedSize(), m_packet, NS_LOG_FUNCTION, ns3::Buffer::Iterator::Read(), ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU32(), ns3::Buffer::Iterator::ReadU8(), ns3::Icmpv6OptionHeader::SetLength(), ns3::Icmpv6OptionHeader::SetType(), and visualizer.core::start().
GetInstanceTypeId()
TypeId ns3::Icmpv6OptionRedirected::GetInstanceTypeId (void) const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::Icmpv6OptionHeader.
Definition at line 1934 of file icmpv6-header.cc.
References GetTypeId(), and NS_LOG_FUNCTION.
GetPacket()
Ptr< Packet > ns3::Icmpv6OptionRedirected::GetPacket () const
Get the redirected packet.
Returns
the redirected packet
Definition at line 1953 of file icmpv6-header.cc.
References m_packet, and NS_LOG_FUNCTION.
GetSerializedSize()
uint32_t ns3::Icmpv6OptionRedirected::GetSerializedSize (void) const virtual
Get the serialized size.
Returns
serialized size
Reimplemented from ns3::Icmpv6OptionHeader.
Definition at line 1973 of file icmpv6-header.cc.
References ns3::Packet::GetSize(), m_packet, and NS_LOG_FUNCTION.
Referenced by Deserialize().
GetTypeId()
TypeId ns3::Icmpv6OptionRedirected::GetTypeId (void) static
Get the UID of this class.
Returns
UID
Definition at line 1924 of file icmpv6-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::Icmpv6OptionRedirected::Print (std::ostream & os) const virtual
Print information.
Parameters
os output stream
Reimplemented from ns3::Icmpv6OptionHeader.
Definition at line 1967 of file icmpv6-header.cc.
References ns3::Icmpv6OptionHeader::GetLength(), ns3::Icmpv6OptionHeader::GetType(), and NS_LOG_FUNCTION.
Serialize()
void ns3::Icmpv6OptionRedirected::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start start offset
Reimplemented from ns3::Icmpv6OptionHeader.
Definition at line 1979 of file icmpv6-header.cc.
References ns3::Packet::CopyData(), ns3::Icmpv6OptionHeader::GetLength(), ns3::Packet::GetSize(), ns3::Icmpv6OptionHeader::GetType(), m_packet, NS_LOG_FUNCTION, visualizer.core::start(), ns3::Buffer::Iterator::Write(), ns3::Buffer::Iterator::WriteU16(), ns3::Buffer::Iterator::WriteU32(), and ns3::Buffer::Iterator::WriteU8().
SetPacket()
void ns3::Icmpv6OptionRedirected::SetPacket (Ptr< Packet > packet)
Set the redirected packet.
Parameters
packet the redirected packet
Definition at line 1959 of file icmpv6-header.cc.
References ns3::Packet::GetSize(), m_packet, NS_ASSERT, NS_LOG_FUNCTION, and ns3::Icmpv6OptionHeader::SetLength().
Referenced by ns3::Icmpv6L4Protocol::SendRedirection().
Member Data Documentation
m_packet
Ptr<Packet> ns3::Icmpv6OptionRedirected::m_packet private
The redirected packet.
Definition at line 1790 of file icmpv6-header.h.
Referenced by ~Icmpv6OptionRedirected(), Deserialize(), GetPacket(), GetSerializedSize(), Serialize(), and SetPacket().
The documentation for this class was generated from the following files:
src/internet/model/icmpv6-header.h
src/internet/model/icmpv6-header.cc