ns-3: ns3::dsr::DsrOptionAckReqHeader Class Reference
ns3::dsr::DsrOptionAckReqHeader Class Reference
DSR Routing
Acknowledgement Request (ACK_RREQ) Message Format.
#include "dsr-option-header.h"
Public Member Functions
DsrOptionAckReqHeader ()
Constructor.
virtual ~DsrOptionAckReqHeader ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
uint16_t GetAckId () const
Set the Ack request id number.
virtual Alignment GetAlignment () const
Get the Alignment requirement of this option header.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
virtual uint32_t GetSerializedSize () const
Get the serialized size of the packet.
virtual void Print (std::ostream &os) const
Print some information about the packet.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetAckId (uint16_t identification)
Set the Ack request id number.
Public Member Functions inherited from ns3::dsr::DsrOptionHeader
DsrOptionHeader ()
Constructor.
virtual ~DsrOptionHeader ()
Destructor.
uint8_t GetLength () const
Get the option length.
uint8_t GetType () const
Get the type of the option.
void SetLength (uint8_t length)
Set the option length.
void SetType (uint8_t type)
Set the type of the option.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::dsr::DsrOptionHeader
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint16_t m_identification
The identification field.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Acknowledgement Request (ACK_RREQ) Message Format.
Introspection did not find any typical Config paths.
Header of Dsr Option ack request.
 |      0        |      1        |      2        |      3        |
 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |  Option Type |  Opt Data Len |         Identification         |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 56 bytes (on a 64-bit architecture).
Definition at line 1166 of file dsr-option-header.h.
Constructor & Destructor Documentation
DsrOptionAckReqHeader()
ns3::dsr::DsrOptionAckReqHeader::DsrOptionAckReqHeader ()
Constructor.
Definition at line 1048 of file dsr-option-header.cc.
References ns3::dsr::DsrOptionHeader::SetLength(), and ns3::dsr::DsrOptionHeader::SetType().
~DsrOptionAckReqHeader()
ns3::dsr::DsrOptionAckReqHeader::~DsrOptionAckReqHeader () virtual
Destructor.
Definition at line 1056 of file dsr-option-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::dsr::DsrOptionAckReqHeader::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start Buffer iterator
Returns
size of the packet
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 1090 of file dsr-option-header.cc.
References GetSerializedSize(), m_identification, ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU8(), ns3::dsr::DsrOptionHeader::SetLength(), ns3::dsr::DsrOptionHeader::SetType(), and visualizer.core::start().
GetAckId()
uint16_t ns3::dsr::DsrOptionAckReqHeader::GetAckId () const
Set the Ack request id number.
Returns
request id number
Definition at line 1065 of file dsr-option-header.cc.
References m_identification.
Referenced by DsrAckReqHeaderTest::DoRun(), and ns3::dsr::DsrOptionSR::Process().
GetAlignment()
DsrOptionHeader::Alignment ns3::dsr::DsrOptionAckReqHeader::GetAlignment () const virtual
Get the Alignment requirement of this option header.
Returns
The required alignment
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 1101 of file dsr-option-header.cc.
GetInstanceTypeId()
TypeId ns3::dsr::DsrOptionAckReqHeader::GetInstanceTypeId (void) const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 1043 of file dsr-option-header.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::dsr::DsrOptionAckReqHeader::GetSerializedSize (void) const virtual
Get the serialized size of the packet.
Returns
size
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 1076 of file dsr-option-header.cc.
Referenced by Deserialize(), and ns3::dsr::DsrOptionAckReq::Process().
GetTypeId()
TypeId ns3::dsr::DsrOptionAckReqHeader::GetTypeId (void) static
Get the type identificator.
Returns
type identificator
Definition at line 1033 of file dsr-option-header.cc.
References ns3::TypeId::AddConstructor().
Referenced by GetInstanceTypeId().
Print()
void ns3::dsr::DsrOptionAckReqHeader::Print (std::ostream & os) const virtual
Print some information about the packet.
Parameters
os output stream
Returns
info about this packet
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 1070 of file dsr-option-header.cc.
References ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrOptionHeader::GetType(), and m_identification.
Serialize()
void ns3::dsr::DsrOptionAckReqHeader::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start Buffer iterator
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 1081 of file dsr-option-header.cc.
References ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrOptionHeader::GetType(), m_identification, visualizer.core::start(), ns3::Buffer::Iterator::WriteU16(), and ns3::Buffer::Iterator::WriteU8().
SetAckId()
void ns3::dsr::DsrOptionAckReqHeader::SetAckId (uint16_t identification)
Set the Ack request id number.
Parameters
identification the identification number
Definition at line 1060 of file dsr-option-header.cc.
References m_identification.
Referenced by ns3::dsr::DsrRouting::AddAckReqHeader(), and DsrAckReqHeaderTest::DoRun().
Member Data Documentation
m_identification
uint16_t ns3::dsr::DsrOptionAckReqHeader::m_identification private
The identification field.
Definition at line 1229 of file dsr-option-header.h.
Referenced by Deserialize(), GetAckId(), Print(), Serialize(), and SetAckId().
The documentation for this class was generated from the following files:
src/dsr/model/dsr-option-header.h
src/dsr/model/dsr-option-header.cc