ns-3: TcpTxBufferTestCase Class Reference
TcpTxBufferTestCase Class Reference
Test suites
The TcpTxBuffer Test.
Public Member Functions
TcpTxBufferTestCase ()
Constructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
virtual void DoTeardown (void)
Implementation to do any local setup required for this TestCase.
uint32_t GetRWnd (void) const
Callback to provide a value of receiver window.
void TestIsLost ()
Test if a segment is really set as lost.
void TestMergeItemsWhenGetTransmittedSegment ()
Test the logic of merging items in GetTransmittedSegment() which is triggered by CopyFromSequence()
void TestNewBlock ()
Test the generation of an unsent block.
void TestNextSeg ()
Test the generation of the "next" block.
void TestTransmittedBlock ()
Test the generation of a previously sent block.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
The TcpTxBuffer Test.
Definition at line 35 of file tcp-tx-buffer-test.cc.
Constructor & Destructor Documentation
TcpTxBufferTestCase()
TcpTxBufferTestCase::TcpTxBufferTestCase ()
Constructor.
Definition at line 60 of file tcp-tx-buffer-test.cc.
Member Function Documentation
DoRun()
void TcpTxBufferTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 66 of file tcp-tx-buffer-test.cc.
References ns3::Seconds(), TestIsLost(), TestMergeItemsWhenGetTransmittedSegment(), TestNewBlock(), TestNextSeg(), and TestTransmittedBlock().
DoTeardown()
void TcpTxBufferTestCase::DoTeardown (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test teardown
Reimplemented from ns3::TestCase.
Definition at line 391 of file tcp-tx-buffer-test.cc.
GetRWnd()
uint32_t TcpTxBufferTestCase::GetRWnd (void) const private
Callback to provide a value of receiver window.
Definition at line 154 of file tcp-tx-buffer-test.cc.
References max.
Referenced by TestIsLost(), TestNewBlock(), and TestNextSeg().
TestIsLost()
void TcpTxBufferTestCase::TestIsLost () private
Test if a segment is really set as lost.
Definition at line 106 of file tcp-tx-buffer-test.cc.
References GetRWnd(), ns3::MakeCallback(), and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
TestMergeItemsWhenGetTransmittedSegment()
void TcpTxBufferTestCase::TestMergeItemsWhenGetTransmittedSegment () private
Test the logic of merging items in GetTransmittedSegment() which is triggered by CopyFromSequence()
Definition at line 368 of file tcp-tx-buffer-test.cc.
References ns3::TcpTxBuffer::Add(), ns3::TcpTxBuffer::CopyFromSequence(), ns3::TcpTxBuffer::MarkHeadAsLost(), ns3::TcpTxBuffer::SetHeadSequence(), and ns3::TcpTxBuffer::SetSegmentSize().
Referenced by DoRun().
TestNewBlock()
void TcpTxBufferTestCase::TestNewBlock () private
Test the generation of an unsent block.
Definition at line 297 of file tcp-tx-buffer-test.cc.
References GetRWnd(), ns3::Packet::GetSize(), ns3::MakeCallback(), and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
TestNextSeg()
void TcpTxBufferTestCase::TestNextSeg () private
Test the generation of the "next" block.
Definition at line 161 of file tcp-tx-buffer-test.cc.
References GetRWnd(), ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::GetValue(), ns3::MakeCallback(), NS_TEST_ASSERT_MSG_EQ, and segmentSize.
Referenced by DoRun().
TestTransmittedBlock()
void TcpTxBufferTestCase::TestTransmittedBlock () private
Test the generation of a previously sent block.
Definition at line 386 of file tcp-tx-buffer-test.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/internet/test/tcp-tx-buffer-test.cc