ns-3: ns3::TcpHeader Class Reference
ns3::TcpHeader Class Reference
Internet » TCP
Header for the Transmission Control Protocol.
#include "tcp-header.h"
Public Types
enum Flags_t {
NONE = 0 , FIN = 1 , SYN = 2 , RST = 4 ,
PSH = 8 , ACK = 16 , URG = 32 , ECE = 64 ,
CWR = 128
}
TCP flag field values.
typedef std::list< Ptr< const TcpOption > > TcpOptionList
List of TcpOption.
Public Member Functions
TcpHeader ()
virtual ~TcpHeader ()
bool AppendOption (Ptr< const TcpOption > option)
Append an option to the TCP header.
virtual uint32_t Deserialize (Buffer::Iterator start)
void EnableChecksums (void)
Enable checksum calculation for TCP.
SequenceNumber32 GetAckNumber () const
Get the ACK number.
uint16_t GetDestinationPort () const
Get the destination port.
uint8_t GetFlags () const
Get the flags.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint8_t GetLength () const
Get the length in words.
uint8_t GetMaxOptionLength () const
Get maximum option length.
Ptr< const TcpOption > GetOption (uint8_t kind) const
Get the option specified.
uint8_t GetOptionLength () const
Get the total length of appended options.
const TcpOptionList & GetOptionList (void) const
Get the list of option in this header.
SequenceNumber32 GetSequenceNumber () const
Get the sequence number.
virtual uint32_t GetSerializedSize (void) const
uint16_t GetSourcePort () const
Get the source port.
uint16_t GetUrgentPointer () const
Get the urgent pointer.
uint16_t GetWindowSize () const
Get the window size.
bool HasOption (uint8_t kind) const
Check if the header has the option specified.
void InitializeChecksum (const Address &source, const Address &destination, uint8_t protocol)
Initialize the TCP checksum.
void InitializeChecksum (const Ipv4Address &source, const Ipv4Address &destination, uint8_t protocol)
Initialize the TCP checksum.
void InitializeChecksum (const Ipv6Address &source, const Ipv6Address &destination, uint8_t protocol)
Initialize the TCP checksum.
bool IsChecksumOk (void) const
Is the TCP checksum correct ?
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetAckNumber (SequenceNumber32 ackNumber)
Set the ACK number.
void SetDestinationPort (uint16_t port)
Set the destination port.
void SetFlags (uint8_t flags)
Set flags of the header.
void SetSequenceNumber (SequenceNumber32 sequenceNumber)
Set the sequence Number.
void SetSourcePort (uint16_t port)
Set the source port.
void SetUrgentPointer (uint16_t urgentPointer)
Set the urgent pointer.
void SetWindowSize (uint16_t windowSize)
Set the window size.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static std::string FlagsToString (uint8_t flags, const std::string &delimiter="|")
Converts an integer into a human readable list of Tcp flags.
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
uint16_t CalculateHeaderChecksum (uint16_t size) const
Calculate the header checksum.
uint8_t CalculateHeaderLength () const
Calculates the header length (in words)
Private Attributes
SequenceNumber32 m_ackNumber
ACK number.
bool m_calcChecksum
Flag to calculate checksum.
Address m_destination
Destination IP address.
uint16_t m_destinationPort
Destination port.
uint8_t m_flags
Flags (really a uint6_t)
bool m_goodChecksum
Flag to indicate that checksum is correct.
uint8_t m_length
Length (really a uint4_t) in words.
TcpOptionList m_options
TcpOption present in the header.
uint8_t m_optionsLen
Tcp options length.
uint8_t m_protocol
Protocol number.
SequenceNumber32 m_sequenceNumber
Sequence number.
Address m_source
Source IP address.
uint16_t m_sourcePort
Source port.
uint16_t m_urgentPointer
Urgent pointer.
uint16_t m_windowSize
Window size.
Static Private Attributes
static const uint8_t m_maxOptionsLen = 40
Maximum options length.
Friends
std::ostream & operator<< (std::ostream &os, TcpHeader const &tc)
Print a TCP header into an output stream.
bool operator== (const TcpHeader &lhs, const TcpHeader &rhs)
Comparison operator.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Header for the Transmission Control Protocol.
Introspection did not find any typical Config paths.
This class has fields corresponding to those in a network TCP header (port numbers, sequence and acknowledgement numbers, flags, etc) as well as methods for serialization to and deserialization from a byte buffer.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 112 bytes (on a 64-bit architecture).
Definition at line 44 of file tcp-header.h.
Member Typedef Documentation
TcpOptionList
typedef std::list< Ptr<const TcpOption> > ns3::TcpHeader::TcpOptionList
List of TcpOption.
Definition at line 50 of file tcp-header.h.
Member Enumeration Documentation
Flags_t
enum ns3::TcpHeader::Flags_t
TCP flag field values.
Enumerator
NONE
No flags.
FIN
FIN.
SYN
SYN.
RST
Reset.
PSH
Push.
ACK
Ack.
URG
Urgent.
ECE
ECE.
CWR
CWR.
Definition at line 279 of file tcp-header.h.
Constructor & Destructor Documentation
TcpHeader()
ns3::TcpHeader::TcpHeader ()
Definition at line 35 of file tcp-header.cc.
~TcpHeader()
ns3::TcpHeader::~TcpHeader () virtual
Definition at line 50 of file tcp-header.cc.
Member Function Documentation
AppendOption()
bool ns3::TcpHeader::AppendOption (Ptr< const TcpOption > option)
Append an option to the TCP header.
Parameters
option The option to append
Returns
true if option has been appended, false otherwise
Definition at line 463 of file tcp-header.cc.
References ns3::TcpOption::END, ns3::TcpOption::GetKind(), ns3::TcpOption::GetSerializedSize(), ns3::TcpOption::IsKindKnown(), m_length, m_maxOptionsLen, m_options, m_optionsLen, and NS_LOG_WARN.
Referenced by ns3::TcpSocketBase::AddOptionSack(), ns3::TcpSocketBase::AddOptionSackPermitted(), ns3::TcpSocketBase::AddOptionTimestamp(), ns3::TcpSocketBase::AddOptionWScale(), TcpHeaderWithRFC793OptionTestCase::CheckCorrectDeserialize(), TcpHeaderWithRFC793OptionTestCase::CheckNoPadding(), and TcpHeaderWithRFC793OptionTestCase::OneOptionAtTime().
CalculateHeaderChecksum()
uint16_t ns3::TcpHeader::CalculateHeaderChecksum (uint16_t size) const private
Calculate the header checksum.
Parameters
size packet size
Returns
the checksum
Definition at line 221 of file tcp-header.cc.
References ns3::Buffer::AddAtStart(), ns3::Buffer::Begin(), ns3::Buffer::Iterator::CalculateIpChecksum(), ns3::Ipv4Address::IsMatchingType(), m_destination, m_protocol, m_source, ns3::Address::MAX_SIZE, ns3::WriteTo(), ns3::Buffer::Iterator::WriteU16(), and ns3::Buffer::Iterator::WriteU8().
Referenced by Deserialize(), and Serialize().
CalculateHeaderLength()
uint8_t ns3::TcpHeader::CalculateHeaderLength () const private
Calculates the header length (in words)
Given the standard size of the header, the method checks for options and calculates the real length (in words).
Returns
header length in 4-byte words
Definition at line 445 of file tcp-header.cc.
References m_options.
Referenced by Deserialize(), and GetSerializedSize().
Deserialize()
uint32_t ns3::TcpHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 360 of file tcp-header.cc.
References CalculateHeaderChecksum(), CalculateHeaderLength(), ns3::Buffer::Iterator::CalculateIpChecksum(), ns3::TcpOption::CreateOption(), ns3::TcpOption::END, GetSerializedSize(), ns3::TcpOption::IsKindKnown(), m_ackNumber, m_calcChecksum, m_destinationPort, m_flags, m_goodChecksum, m_length, m_maxOptionsLen, m_options, m_optionsLen, m_sequenceNumber, m_sourcePort, m_urgentPointer, m_windowSize, ns3::Buffer::Iterator::Next(), NS_LOG_ERROR, NS_LOG_WARN, ns3::Buffer::Iterator::PeekU8(), ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadNtohU32(), visualizer.core::start(), and ns3::TcpOption::UNKNOWN.
Referenced by TcpHeaderWithRFC793OptionTestCase::CheckCorrectDeserialize(), TcpHeaderGetSetTestCase::DoRun(), and TcpHeaderWithRFC793OptionTestCase::OneOptionAtTime().
EnableChecksums()
void ns3::TcpHeader::EnableChecksums (void)
Enable checksum calculation for TCP.
Todo:
currently has no effect
Definition at line 83 of file tcp-header.cc.
References m_calcChecksum.
Referenced by ns3::TcpL4Protocol::SendPacketV4(), and ns3::TcpL4Protocol::SendPacketV6().
FlagsToString()
std::string ns3::TcpHeader::FlagsToString (uint8_t flags, const std::string & delimiter = "|") static
Converts an integer into a human readable list of Tcp flags.
Parameters
flags Bitfield of TCP flags to convert to a readable string
delimiter String to insert between flags
FIN=0x1, SYN=0x2, RST=0x4, PSH=0x8, ACK=0x10, URG=0x20, ECE=0x40, CWR=0x80 TcpHeader::FlagsToString (0x1) should return the following string; "FIN"
TcpHeader::FlagsToString (0xff) should return the following string; "FIN|SYN|RST|PSH|ACK|URG|ECE|CWR";
Returns
the generated string
Definition at line 55 of file tcp-header.cc.
Referenced by Print(), ns3::TcpSocketBase::ProcessClosing(), ns3::TcpSocketBase::ProcessEstablished(), ns3::TcpSocketBase::ProcessLastAck(), ns3::TcpSocketBase::ProcessSynRcvd(), ns3::TcpSocketBase::ProcessSynSent(), ns3::TcpSocketBase::ProcessWait(), ns3::TcpL4Protocol::SendPacketV4(), and ns3::TcpL4Protocol::SendPacketV6().
GetAckNumber()
SequenceNumber32 ns3::TcpHeader::GetAckNumber () const
Get the ACK number.
Returns
the ACK number for this TcpHeader
Definition at line 149 of file tcp-header.cc.
References m_ackNumber.
Referenced by ns3::TcpSocketBase::DoForwardUp(), TcpHeaderGetSetTestCase::DoRun(), ns3::TcpSocketBase::EstimateRtt(), ns3::TcpL4Protocol::NoEndPointsFound(), TcpFastRetrTest::ProcessedAck(), ns3::TcpSocketBase::ProcessEstablished(), ns3::TcpSocketBase::ProcessSynRcvd(), ns3::TcpSocketBase::ProcessSynSent(), ns3::TcpSocketBase::ProcessWait(), TcpFastRetrTest::RcvAck(), ns3::TcpSocketBase::ReceivedAck(), TcpBytesInFlightTest::Rx(), TcpPktsAckedOpenTest::Rx(), TcpRateLinuxWithSocketsTest::Rx(), TcpRttEstimationTest::Rx(), TcpSlowStartNormalTest::Rx(), ns3::TcpSocketBase::SendEmptyPacket(), ns3::TcpL4Protocol::SendPacketV4(), ns3::TcpL4Protocol::SendPacketV6(), TcpFastRetrTest::Tx(), TcpRttEstimationTest::Tx(), and ns3::TcpSocketBase::UpdateWindowSize().
GetDestinationPort()
uint16_t ns3::TcpHeader::GetDestinationPort () const
Get the destination port.
Returns
the destination port for this TcpHeader
Definition at line 137 of file tcp-header.cc.
References m_destinationPort.
Referenced by ns3::IpcsClassifier::Classify(), ns3::EpcTftClassifier::Classify(), ns3::TcpSocketBase::DoForwardUp(), TcpHeaderGetSetTestCase::DoRun(), ns3::Ipv4QueueDiscItem::Hash(), ns3::Ipv6QueueDiscItem::Hash(), and ns3::TcpL4Protocol::NoEndPointsFound().
GetFlags()
uint8_t ns3::TcpHeader::GetFlags () const
Get the flags.
Returns
the flags for this TcpHeader
Definition at line 173 of file tcp-header.cc.
References m_flags.
Referenced by ns3::TcpSocketBase::AddOptionSackPermitted(), ns3::TcpSocketBase::AddOptionWScale(), ns3::TcpSocketBase::CompleteFork(), ns3::TcpSocketBase::DoForwardUp(), TcpHeaderGetSetTestCase::DoRun(), ns3::TcpL4Protocol::NoEndPointsFound(), ns3::TcpSocketBase::ProcessClosing(), TcpZeroWindowTest::ProcessedAck(), ns3::TcpSocketBase::ProcessEstablished(), ns3::TcpSocketBase::ProcessLastAck(), ns3::TcpSocketBase::ProcessListen(), ns3::TcpSocketBase::ProcessSynRcvd(), ns3::TcpSocketBase::ProcessSynSent(), ns3::TcpSocketBase::ProcessWait(), ns3::TcpSocketBase::ReceivedAck(), ns3::TcpSocketBase::ReceivedData(), TcpBytesInFlightTest::Rx(), TcpDctcpCodePointsTest::Rx(), ns3::TcpEcnTest::Rx(), TcpPacingTest::Rx(), TcpPktsAckedOpenTest::Rx(), TcpRateLinuxWithSocketsTest::Rx(), TcpZeroWindowTest::Rx(), ns3::TcpL4Protocol::SendPacketV4(), ns3::TcpL4Protocol::SendPacketV6(), ns3::TcpFlagErrorModel::ShouldDrop(), TcpFastRetrTest::Tx(), TcpTimeRtoTest::Tx(), TcpRttEstimationTest::Tx(), SackPermittedTestCase::Tx(), TimestampTestCase::Tx(), WScalingTestCase::Tx(), and TcpZeroWindowTest::Tx().
GetInstanceTypeId()
TypeId ns3::TcpHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 281 of file tcp-header.cc.
References GetTypeId().
GetLength()
uint8_t ns3::TcpHeader::GetLength () const
Get the length in words.
A word is 4 bytes; without Tcp Options, header is 5 words (20 bytes). With options, it can reach up to 15 words (60 bytes).
Returns
the length of this TcpHeader
Definition at line 155 of file tcp-header.cc.
References m_length.
Referenced by TcpHeaderWithRFC793OptionTestCase::CheckNoPadding(), TcpHeaderGetSetTestCase::DoRun(), TcpHeaderWithRFC793OptionTestCase::OneOptionAtTime(), and Serialize().
GetMaxOptionLength()
uint8_t ns3::TcpHeader::GetMaxOptionLength () const
Get maximum option length.
Returns
the maximum option length
Definition at line 167 of file tcp-header.cc.
References m_maxOptionsLen.
Referenced by ns3::TcpSocketBase::AddOptionSack().
GetOption()
Ptr< const TcpOption > ns3::TcpHeader::GetOption (uint8_t kind) const
Get the option specified.
Parameters
kind the option to retrieve
Returns
Whether the header contains a specific kind of option, or 0
Definition at line 495 of file tcp-header.cc.
References m_options.
Referenced by ns3::TcpSocketBase::DoForwardUp(), and ns3::TcpSocketBase::EstimateRtt().
GetOptionLength()
uint8_t ns3::TcpHeader::GetOptionLength () const
Get the total length of appended options.
Returns
the total length of options appended to this TcpHeader
Definition at line 161 of file tcp-header.cc.
References m_optionsLen.
Referenced by ns3::TcpSocketBase::AddOptionSack(), and TcpHeaderWithRFC793OptionTestCase::OneOptionAtTime().
GetOptionList()
const TcpHeader::TcpOptionList & ns3::TcpHeader::GetOptionList (void) const
Get the list of option in this header.
Returns
a const reference to the option list
Definition at line 489 of file tcp-header.cc.
References m_options.
Referenced by ns3::TcpSocketBase::ReadOptions().
GetSequenceNumber()
SequenceNumber32 ns3::TcpHeader::GetSequenceNumber (void) const
Get the sequence number.
Returns
the sequence number for this TcpHeader
Definition at line 143 of file tcp-header.cc.
References m_sequenceNumber.
Referenced by ns3::TcpRxBuffer::Add(), ns3::TcpSocketBase::CompleteFork(), ns3::TcpSocketBase::DoForwardUp(), TcpHeaderGetSetTestCase::DoRun(), ns3::TcpSocketBase::ForwardUp(), ns3::TcpSocketBase::ForwardUp6(), ns3::TcpL4Protocol::NoEndPointsFound(), ns3::TcpSocketBase::PeerClose(), TcpBytesInFlightTest::PktDropped(), TcpFastRetrTest::PktDropped(), TcpRateLinuxWithSocketsTest::PktDropped(), ns3::TcpSocketBase::ProcessClosing(), ns3::TcpSocketBase::ProcessLastAck(), ns3::TcpSocketBase::ProcessSynRcvd(), ns3::TcpSocketBase::ProcessSynSent(), ns3::TcpSocketBase::ProcessWait(), ns3::TcpSocketBase::ReceivedData(), TcpFastRetrTest::Rx(), TcpRttEstimationTest::Rx(), ns3::TcpL4Protocol::SendPacketV4(), ns3::TcpL4Protocol::SendPacketV6(), ns3::TcpSeqErrorModel::ShouldDrop(), TcpBytesInFlightTest::Tx(), TcpFastRetrTest::Tx(), TcpTimeRtoTest::Tx(), TcpRttEstimationTest::Tx(), TcpZeroWindowTest::Tx(), and ns3::TcpSocketBase::UpdateWindowSize().
GetSerializedSize()
uint32_t ns3::TcpHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 309 of file tcp-header.cc.
References CalculateHeaderLength().
Referenced by TcpHeaderWithRFC793OptionTestCase::CheckNoPadding(), Deserialize(), TcpHeaderGetSetTestCase::DoRun(), and TcpHeaderWithRFC793OptionTestCase::OneOptionAtTime().
GetSourcePort()
uint16_t ns3::TcpHeader::GetSourcePort () const
Get the source port.
Returns
The source port for this TcpHeader
Definition at line 131 of file tcp-header.cc.
References m_sourcePort.
Referenced by ns3::IpcsClassifier::Classify(), ns3::EpcTftClassifier::Classify(), ns3::TcpSocketBase::DoForwardUp(), TcpHeaderGetSetTestCase::DoRun(), ns3::Ipv4QueueDiscItem::Hash(), ns3::Ipv6QueueDiscItem::Hash(), and ns3::TcpL4Protocol::NoEndPointsFound().
GetTypeId()
TypeId ns3::TcpHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 270 of file tcp-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
GetUrgentPointer()
uint16_t ns3::TcpHeader::GetUrgentPointer () const
Get the urgent pointer.
Returns
the urgent pointer for this TcpHeader
Definition at line 185 of file tcp-header.cc.
References m_urgentPointer.
Referenced by TcpHeaderGetSetTestCase::DoRun().
GetWindowSize()
uint16_t ns3::TcpHeader::GetWindowSize () const
Get the window size.
Returns
the window size for this TcpHeader
Definition at line 179 of file tcp-header.cc.
References m_windowSize.
Referenced by ns3::TcpSocketBase::DoForwardUp(), TcpHeaderGetSetTestCase::DoRun(), TcpZeroWindowTest::Rx(), WScalingTestCase::Tx(), TcpZeroWindowTest::Tx(), and ns3::TcpSocketBase::UpdateWindowSize().
HasOption()
bool ns3::TcpHeader::HasOption (uint8_t kind) const
Check if the header has the option specified.
Parameters
kind Option to check for
Returns
true if the header has the option, false otherwise
Definition at line 511 of file tcp-header.cc.
References m_options.
Referenced by TcpHeaderWithRFC793OptionTestCase::CheckCorrectDeserialize(), ns3::TcpSocketBase::DoForwardUp(), ns3::TcpSocketBase::EstimateRtt(), TcpHeaderWithRFC793OptionTestCase::OneOptionAtTime(), SackPermittedTestCase::Tx(), TimestampTestCase::Tx(), and WScalingTestCase::Tx().
InitializeChecksum() [1/3]
void ns3::TcpHeader::InitializeChecksum (const Address & source, const Address & destination, uint8_t protocol)
Initialize the TCP checksum.
If you want to use tcp checksums, you should call this method prior to adding the header to a packet.
Parameters
source the IP source to use in the underlying IP packet.
destination the IP destination to use in the underlying IP packet.
protocol the protocol number to use in the underlying IP packet.
Definition at line 211 of file tcp-header.cc.
References m_destination, m_protocol, and m_source.
InitializeChecksum() [2/3]
void ns3::TcpHeader::InitializeChecksum (const Ipv4Address & source, const Ipv4Address & destination, uint8_t protocol)
Initialize the TCP checksum.
If you want to use tcp checksums, you should call this method prior to adding the header to a packet.
Parameters
source the IP source to use in the underlying IP packet.
destination the IP destination to use in the underlying IP packet.
protocol the protocol number to use in the underlying IP packet.
Definition at line 191 of file tcp-header.cc.
References m_destination, m_protocol, and m_source.
Referenced by ns3::TcpL4Protocol::SendPacketV4(), and ns3::TcpL4Protocol::SendPacketV6().
InitializeChecksum() [3/3]
void ns3::TcpHeader::InitializeChecksum (const Ipv6Address & source, const Ipv6Address & destination, uint8_t protocol)
Initialize the TCP checksum.
If you want to use tcp checksums, you should call this method prior to adding the header to a packet.
Parameters
source the IP source to use in the underlying IP packet.
destination the IP destination to use in the underlying IP packet.
protocol the protocol number to use in the underlying IP packet.
Definition at line 201 of file tcp-header.cc.
References m_destination, m_protocol, and m_source.
IsChecksumOk()
bool ns3::TcpHeader::IsChecksumOk (void) const
Is the TCP checksum correct ?
Returns
true if the checksum is correct, false otherwise.
Definition at line 264 of file tcp-header.cc.
References m_goodChecksum.
Print()
void ns3::TcpHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 287 of file tcp-header.cc.
References FlagsToString(), m_ackNumber, m_destinationPort, m_flags, m_options, m_sequenceNumber, m_sourcePort, and m_windowSize.
Serialize()
void ns3::TcpHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 315 of file tcp-header.cc.
References CalculateHeaderChecksum(), ns3::Buffer::Iterator::CalculateIpChecksum(), ns3::TcpOption::END, GetLength(), ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::GetValue(), m_ackNumber, m_calcChecksum, m_destinationPort, m_flags, m_options, m_sequenceNumber, m_sourcePort, m_urgentPointer, m_windowSize, ns3::Buffer::Iterator::Next(), visualizer.core::start(), ns3::Buffer::Iterator::WriteHtonU16(), ns3::Buffer::Iterator::WriteHtonU32(), ns3::Buffer::Iterator::WriteU16(), and ns3::Buffer::Iterator::WriteU8().
Referenced by TcpHeaderWithRFC793OptionTestCase::CheckCorrectDeserialize(), TcpHeaderWithRFC793OptionTestCase::CheckNoPadding(), TcpHeaderGetSetTestCase::DoRun(), and TcpHeaderWithRFC793OptionTestCase::OneOptionAtTime().
SetAckNumber()
void ns3::TcpHeader::SetAckNumber (SequenceNumber32 ackNumber)
Set the ACK number.
Parameters
ackNumber the ACK number for this TcpHeader
Definition at line 107 of file tcp-header.cc.
References m_ackNumber.
Referenced by ns3::TcpSocketBase::DoForwardUp(), TcpHeaderGetSetTestCase::DoRun(), ns3::TcpL4Protocol::NoEndPointsFound(), ns3::TcpSocketBase::PersistTimeout(), ns3::TcpSocketBase::SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), ns3::TcpSocketBase::SendEmptyPacket(), and ns3::TcpSocketSmallAcks::SendEmptyPacket().
SetDestinationPort()
void ns3::TcpHeader::SetDestinationPort (uint16_t port)
Set the destination port.
Parameters
port the destination port for this TcpHeader
Definition at line 95 of file tcp-header.cc.
References m_destinationPort, and port.
Referenced by ns3::TcpSocketBase::DoForwardUp(), TcpHeaderGetSetTestCase::DoRun(), FqCoDelQueueDiscTCPFlowsSeparation::DoRun(), ns3::TcpL4Protocol::NoEndPointsFound(), ns3::TcpSocketBase::PersistTimeout(), ns3::TcpSocketBase::SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), ns3::TcpSocketBase::SendEmptyPacket(), and ns3::TcpSocketSmallAcks::SendEmptyPacket().
SetFlags()
void ns3::TcpHeader::SetFlags (uint8_t flags)
Set flags of the header.
Parameters
flags the flags for this TcpHeader
Definition at line 113 of file tcp-header.cc.
References m_flags.
Referenced by ns3::TcpSocketBase::DoForwardUp(), TcpHeaderGetSetTestCase::DoRun(), ns3::TcpL4Protocol::NoEndPointsFound(), ns3::TcpSocketBase::SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), ns3::TcpSocketBase::SendEmptyPacket(), and ns3::TcpSocketSmallAcks::SendEmptyPacket().
SetSequenceNumber()
void ns3::TcpHeader::SetSequenceNumber (SequenceNumber32 sequenceNumber)
Set the sequence Number.
Parameters
sequenceNumber the sequence number for this TcpHeader
Definition at line 101 of file tcp-header.cc.
References m_sequenceNumber.
Referenced by ns3::TcpSocketBase::DoForwardUp(), TcpHeaderGetSetTestCase::DoRun(), ns3::TcpL4Protocol::NoEndPointsFound(), ns3::TcpSocketBase::PersistTimeout(), ns3::TcpSocketBase::SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), ns3::TcpSocketBase::SendEmptyPacket(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), and TcpRxBufferTestCase::TestUpdateSACKList().
SetSourcePort()
void ns3::TcpHeader::SetSourcePort (uint16_t port)
Set the source port.
Parameters
port The source port for this TcpHeader
Definition at line 89 of file tcp-header.cc.
References m_sourcePort, and port.
Referenced by ns3::TcpSocketBase::DoForwardUp(), TcpHeaderGetSetTestCase::DoRun(), FqCoDelQueueDiscTCPFlowsSeparation::DoRun(), ns3::TcpL4Protocol::NoEndPointsFound(), ns3::TcpSocketBase::PersistTimeout(), ns3::TcpSocketBase::SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), ns3::TcpSocketBase::SendEmptyPacket(), and ns3::TcpSocketSmallAcks::SendEmptyPacket().
SetUrgentPointer()
void ns3::TcpHeader::SetUrgentPointer (uint16_t urgentPointer)
Set the urgent pointer.
Parameters
urgentPointer the urgent pointer for this TcpHeader
Definition at line 125 of file tcp-header.cc.
References m_urgentPointer.
Referenced by TcpHeaderGetSetTestCase::DoRun().
SetWindowSize()
void ns3::TcpHeader::SetWindowSize (uint16_t windowSize)
Set the window size.
Parameters
windowSize the window size for this TcpHeader
Definition at line 119 of file tcp-header.cc.
References m_windowSize.
Referenced by ns3::TcpSocketBase::DoForwardUp(), TcpHeaderGetSetTestCase::DoRun(), ns3::TcpSocketBase::PersistTimeout(), ns3::TcpSocketBase::SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), ns3::TcpSocketBase::SendEmptyPacket(), and ns3::TcpSocketSmallAcks::SendEmptyPacket().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, TcpHeader const & tc) friend
Print a TCP header into an output stream.
Parameters
os output stream
tc TCP header to print
Returns
The ostream passed as first argument
Definition at line 540 of file tcp-header.cc.
operator==
bool operator== (const TcpHeader & lhs, const TcpHeader & rhs) friend
Comparison operator.
Parameters
lhs left operand
rhs right operand
Returns
true if the operands are equal
Definition at line 527 of file tcp-header.cc.
Member Data Documentation
m_ackNumber
SequenceNumber32 ns3::TcpHeader::m_ackNumber private
ACK number.
Definition at line 338 of file tcp-header.h.
Referenced by Deserialize(), GetAckNumber(), Print(), Serialize(), and SetAckNumber().
m_calcChecksum
bool ns3::TcpHeader::m_calcChecksum private
Flag to calculate checksum.
Definition at line 348 of file tcp-header.h.
Referenced by Deserialize(), EnableChecksums(), and Serialize().
m_destination
Address ns3::TcpHeader::m_destination private
Destination IP address.
Definition at line 345 of file tcp-header.h.
Referenced by CalculateHeaderChecksum(), and InitializeChecksum().
m_destinationPort
uint16_t ns3::TcpHeader::m_destinationPort private
Destination port.
Definition at line 336 of file tcp-header.h.
Referenced by Deserialize(), GetDestinationPort(), Print(), Serialize(), and SetDestinationPort().
m_flags
uint8_t ns3::TcpHeader::m_flags private
Flags (really a uint6_t)
Definition at line 340 of file tcp-header.h.
Referenced by Deserialize(), GetFlags(), Print(), Serialize(), and SetFlags().
m_goodChecksum
bool ns3::TcpHeader::m_goodChecksum private
Flag to indicate that checksum is correct.
Definition at line 349 of file tcp-header.h.
Referenced by Deserialize(), and IsChecksumOk().
m_length
uint8_t ns3::TcpHeader::m_length private
Length (really a uint4_t) in words.
Definition at line 339 of file tcp-header.h.
Referenced by AppendOption(), Deserialize(), and GetLength().
m_maxOptionsLen
const uint8_t ns3::TcpHeader::m_maxOptionsLen = 40 static private
Maximum options length.
Definition at line 351 of file tcp-header.h.
Referenced by AppendOption(), Deserialize(), and GetMaxOptionLength().
m_options
TcpOptionList ns3::TcpHeader::m_options private
TcpOption present in the header.
Definition at line 352 of file tcp-header.h.
Referenced by AppendOption(), CalculateHeaderLength(), Deserialize(), GetOption(), GetOptionList(), HasOption(), Print(), and Serialize().
m_optionsLen
uint8_t ns3::TcpHeader::m_optionsLen private
Tcp options length.
Definition at line 353 of file tcp-header.h.
Referenced by AppendOption(), Deserialize(), and GetOptionLength().
m_protocol
uint8_t ns3::TcpHeader::m_protocol private
Protocol number.
Definition at line 346 of file tcp-header.h.
Referenced by CalculateHeaderChecksum(), and InitializeChecksum().
m_sequenceNumber
SequenceNumber32 ns3::TcpHeader::m_sequenceNumber private
Sequence number.
Definition at line 337 of file tcp-header.h.
Referenced by Deserialize(), GetSequenceNumber(), Print(), Serialize(), and SetSequenceNumber().
m_source
Address ns3::TcpHeader::m_source private
Source IP address.
Definition at line 344 of file tcp-header.h.
Referenced by CalculateHeaderChecksum(), and InitializeChecksum().
m_sourcePort
uint16_t ns3::TcpHeader::m_sourcePort private
Source port.
Definition at line 335 of file tcp-header.h.
Referenced by Deserialize(), GetSourcePort(), Print(), Serialize(), and SetSourcePort().
m_urgentPointer
uint16_t ns3::TcpHeader::m_urgentPointer private
Urgent pointer.
Definition at line 342 of file tcp-header.h.
Referenced by Deserialize(), GetUrgentPointer(), Serialize(), and SetUrgentPointer().
m_windowSize
uint16_t ns3::TcpHeader::m_windowSize private
Window size.
Definition at line 341 of file tcp-header.h.
Referenced by Deserialize(), GetWindowSize(), Print(), Serialize(), and SetWindowSize().
The documentation for this class was generated from the following files:
src/internet/model/tcp-header.h
src/internet/model/tcp-header.cc