ns-3: ns3::Icmpv6L4Protocol Class Reference
ns3::Icmpv6L4Protocol Class Reference
Internet » IPv6 classes and sub-modules » ICMPv6 protocol and associated headers.
An implementation of the ICMPv6 protocol.
#include "icmpv6-l4-protocol.h"
Public Member Functions
Icmpv6L4Protocol ()
Constructor.
virtual ~Icmpv6L4Protocol ()
Destructor.
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
virtual Ptr< NdiscCache > CreateCache (Ptr< NetDevice > device, Ptr< Ipv6Interface > interface)
Create a neighbor cache.
void DelayedSendMessage (Ptr< Packet > packet, Ipv6Address src, Ipv6Address dst, uint8_t ttl)
Helper function used during delayed solicitation.
void DoDAD (Ipv6Address target, Ptr< Ipv6Interface > interface)
Do the Duplication Address Detection (DAD).
NdiscCache::Ipv6PayloadHeaderPair ForgeEchoRequest (Ipv6Address src, Ipv6Address dst, uint16_t id, uint16_t seq, Ptr< Packet > data)
Forge an Echo Request.
NdiscCache::Ipv6PayloadHeaderPair ForgeNA (Ipv6Address src, Ipv6Address dst, Address *hardwareAddress, uint8_t flags)
Forge a Neighbor Advertisement.
NdiscCache::Ipv6PayloadHeaderPair ForgeNS (Ipv6Address src, Ipv6Address dst, Ipv6Address target, Address hardwareAddress)
Forge a Neighbor Solicitation.
NdiscCache::Ipv6PayloadHeaderPair ForgeRS (Ipv6Address src, Ipv6Address dst, Address hardwareAddress)
Forge a Router Solicitation.
void FunctionDadTimeout (Ipv6Interface *interface, Ipv6Address addr)
Function called when DAD timeout.
Time GetDelayFirstProbe () const
Neighbor Discovery node constants : delay for the first probe.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint8_t GetMaxMulticastSolicit () const
Neighbor Discovery node constants: max multicast solicitations.
uint8_t GetMaxUnicastSolicit () const
Neighbor Discovery node constants: max unicast solicitations.
Ptr< Node > GetNode ()
Get the node.
virtual int GetProtocolNumber () const
Get the protocol number.
Time GetReachableTime () const
Neighbor Discovery node constants: reachable time.
Time GetRetransmissionTime () const
Neighbor Discovery node constants: retransmission timer.
virtual int GetVersion () const
Get the version of the protocol.
bool IsAlwaysDad () const
Is the node must do DAD.
bool Lookup (Ipv6Address dst, Ptr< NetDevice > device, Ptr< NdiscCache > cache, Address *hardwareDestination)
Lookup in the ND cache for the IPv6 address.
bool Lookup (Ptr< Packet > p, const Ipv6Header &ipHeader, Ipv6Address dst, Ptr< NetDevice > device, Ptr< NdiscCache > cache, Address *hardwareDestination)
Lookup in the ND cache for the IPv6 address (similar as ARP protocol).
void NotifyNewAggregate ()
This method is called by AggregateObject and completes the aggregation by setting the node in the ICMPv6 stack and adding ICMPv6 factory to IPv6 stack connected to the node.
virtual enum IpL4Protocol::RxStatus Receive (Ptr< Packet > p, Ipv4Header const &header, Ptr< Ipv4Interface > interface)
Receive method.
virtual enum IpL4Protocol::RxStatus Receive (Ptr< Packet > p, Ipv6Header const &header, Ptr< Ipv6Interface > interface)
Receive method.
void SendEchoReply (Ipv6Address src, Ipv6Address dst, uint16_t id, uint16_t seq, Ptr< Packet > data)
Send a Echo Reply.
void SendErrorDestinationUnreachable (Ptr< Packet > malformedPacket, Ipv6Address dst, uint8_t code)
Send an error Destination Unreachable.
void SendErrorParameterError (Ptr< Packet > malformedPacket, Ipv6Address dst, uint8_t code, uint32_t ptr)
Send an error Parameter Error.
void SendErrorTimeExceeded (Ptr< Packet > malformedPacket, Ipv6Address dst, uint8_t code)
Send an error Time Exceeded.
void SendErrorTooBig (Ptr< Packet > malformedPacket, Ipv6Address dst, uint32_t mtu)
Send an error Too Big.
void SendMessage (Ptr< Packet > packet, Ipv6Address dst, Icmpv6Header &icmpv6Hdr, uint8_t ttl)
Send a packet via ICMPv6.
void SendMessage (Ptr< Packet > packet, Ipv6Address src, Ipv6Address dst, uint8_t ttl)
Send a packet via ICMPv6, note that packet already contains ICMPv6 header.
void SendNA (Ipv6Address src, Ipv6Address dst, Address *hardwareAddress, uint8_t flags)
Send a Neighbor Adverstisement.
virtual void SendNS (Ipv6Address src, Ipv6Address dst, Ipv6Address target, Address hardwareAddress)
Send a Neighbor Solicitation.
void SendRedirection (Ptr< Packet > redirectedPacket, Ipv6Address src, Ipv6Address dst, Ipv6Address redirTarget, Ipv6Address redirDestination, Address redirHardwareTarget)
Send an ICMPv6 Redirection.
void SendRS (Ipv6Address src, Ipv6Address dst, Address hardwareAddress)
Send a Router Solicitation.
void SetNode (Ptr< Node > node)
Set the node.
Public Member Functions inherited from ns3::IpL4Protocol
virtual ~IpL4Protocol ()
virtual void ReceiveIcmp (Ipv4Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo, Ipv4Address payloadSource, Ipv4Address payloadDestination, const uint8_t payload[8])
Called from lower-level layers to send the ICMP packet up in the stack.
virtual void ReceiveIcmp (Ipv6Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo, Ipv6Address payloadSource, Ipv6Address payloadDestination, const uint8_t payload[8])
Called from lower-level layers to send the ICMPv6 packet up in the stack.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static uint16_t GetStaticProtocolNumber ()
Get ICMPv6 protocol number.
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::IpL4Protocol
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static const uint8_t PROT_NUMBER = 58
ICMPv6 protocol number (58).
Protected Types
typedef std::list< Ptr< NdiscCache > > CacheList
container of NdiscCaches
Protected Member Functions
virtual void DoDispose ()
Dispose this object.
Ptr< NdiscCache > FindCache (Ptr< NetDevice > device)
Get the cache corresponding to the device.
void Forward (Ipv6Address source, Icmpv6Header icmp, uint32_t info, Ipv6Header ipHeader, const uint8_t payload[8])
Notify an ICMPv6 reception to upper layers (if requested).
virtual IpL4Protocol::DownTargetCallback GetDownTarget (void) const
This method allows a caller to get the current down target callback set for this L4 protocol (IPv4 case)
virtual IpL4Protocol::DownTargetCallback6 GetDownTarget6 (void) const
This method allows a caller to get the current down target callback set for this L4 protocol (IPv6 case)
void HandleDestinationUnreachable (Ptr< Packet > p, Ipv6Address const &src, Ipv6Address const &dst, Ptr< Ipv6Interface > interface)
Receive Destination Unreachable method.
void HandleEchoRequest (Ptr< Packet > p, Ipv6Address const &src, Ipv6Address const &dst, Ptr< Ipv6Interface > interface)
Receive Echo Request method.
void HandleNA (Ptr< Packet > p, Ipv6Address const &src, Ipv6Address const &dst, Ptr< Ipv6Interface > interface)
Receive Neighbor Advertisement method.
void HandleNS (Ptr< Packet > p, Ipv6Address const &src, Ipv6Address const &dst, Ptr< Ipv6Interface > interface)
Receive Neighbor Solicitation method.
void HandlePacketTooBig (Ptr< Packet > p, Ipv6Address const &src, Ipv6Address const &dst, Ptr< Ipv6Interface > interface)
Receive Packet Too Big method.
void HandleParameterError (Ptr< Packet > p, Ipv6Address const &src, Ipv6Address const &dst, Ptr< Ipv6Interface > interface)
Receive Parameter Error method.
void HandleRA (Ptr< Packet > p, Ipv6Address const &src, Ipv6Address const &dst, Ptr< Ipv6Interface > interface)
Receive Router Advertisement method.
void HandleRedirection (Ptr< Packet > p, Ipv6Address const &src, Ipv6Address const &dst, Ptr< Ipv6Interface > interface)
Receive Redirection method.
void HandleRS (Ptr< Packet > p, Ipv6Address const &src, Ipv6Address const &dst, Ptr< Ipv6Interface > interface)
Receive Router Solicitation method.
void HandleTimeExceeded (Ptr< Packet > p, Ipv6Address const &src, Ipv6Address const &dst, Ptr< Ipv6Interface > interface)
Receive Time Exceeded method.
void ReceiveLLA (Icmpv6OptionLinkLayerAddress lla, Ipv6Address const &src, Ipv6Address const &dst, Ptr< Ipv6Interface > interface)
Link layer address option processing.
virtual void SetDownTarget (IpL4Protocol::DownTargetCallback cb)
This method allows a caller to set the current down target callback set for this L4 protocol (IPv4 case)
virtual void SetDownTarget6 (IpL4Protocol::DownTargetCallback6 cb)
This method allows a caller to set the current down target callback set for this L4 protocol (IPv6 case)
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes
bool m_alwaysDad
Always do DAD ?
CacheList m_cacheList
A list of cache by device.
Private Attributes
Time m_delayFirstProbe
Neighbor Discovery node constants: delay for the first probe.
IpL4Protocol::DownTargetCallback6 m_downTarget
callback to Ipv6::Send
uint8_t m_maxMulticastSolicit
Neighbor Discovery node constants: max multicast solicitations.
uint8_t m_maxUnicastSolicit
Neighbor Discovery node constants: max unicast solicitations.
Ptr< Node > m_node
The node.
Time m_reachableTime
Neighbor Discovery node constants: reachable time.
Time m_retransmissionTime
Neighbor Discovery node constants: retransmission timer.
Ptr< RandomVariableStream > m_solicitationJitter
Random jitter before sending solicitations.
Additional Inherited Members
Public Types inherited from ns3::IpL4Protocol
typedef Callback< void, Ptr< Packet >, Ipv4Address, Ipv4Address, uint8_t, Ptr< Ipv4Route > > DownTargetCallback
callback to send packets over IPv4
typedef Callback< void, Ptr< Packet >, Ipv6Address, Ipv6Address, uint8_t, Ptr< Ipv6Route > > DownTargetCallback6
callback to send packets over IPv6
enum RxStatus { RX_OK , RX_CSUM_FAILED , RX_ENDPOINT_CLOSED , RX_ENDPOINT_UNREACH }
Rx status codes.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
An implementation of the ICMPv6 protocol.
Config Paths
ns3::Icmpv6L4Protocol is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::Icmpv6L4Protocol"
Attributes
DAD: Always do DAD check.
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
SolicitationJitter: The jitter in ms a node is allowed to wait before sending any solicitation. Some jitter aims to prevent collisions. By default, the model will wait for a duration in ms defined by a uniform random-variable between 0 and SolicitationJitter
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::RandomVariableStream>
Initial value: ns3::UniformRandomVariable[Min=0.0|Max=10.0]
Flags: construct write read
MaxMulticastSolicit: Neighbor Discovery node constants: max multicast solicitations.
Set with class: ns3::IntegerValue
Underlying type: uint8_t 0:255
Initial value: 3
Flags: construct write read
MaxUnicastSolicit: Neighbor Discovery node constants: max unicast solicitations.
Set with class: ns3::IntegerValue
Underlying type: uint8_t 0:255
Initial value: 3
Flags: construct write read
ReachableTime: Neighbor Discovery node constants: reachable time.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +3e+10ns
Flags: construct write read
RetransmissionTime: Neighbor Discovery node constants: retransmission timer.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+09ns
Flags: construct write read
DelayFirstProbe: Neighbor Discovery node constants: delay for the first probe.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +5e+09ns
Flags: construct write read
Attributes defined in parent class ns3::IpL4Protocol
ProtocolNumber: The IP protocol number.
Set with class: ns3::IntegerValue
Underlying type: int32_t 0:255
Flags: read
No TraceSources are defined for this type.
Size of this type is 112 bytes (on a 64-bit architecture).
Definition at line 52 of file icmpv6-l4-protocol.h.
Member Typedef Documentation
CacheList
typedef std::list<Ptr<NdiscCache> > ns3::Icmpv6L4Protocol::CacheList protected
container of NdiscCaches
Definition at line 390 of file icmpv6-l4-protocol.h.
Constructor & Destructor Documentation
Icmpv6L4Protocol()
ns3::Icmpv6L4Protocol::Icmpv6L4Protocol ()
Constructor.
Definition at line 107 of file icmpv6-l4-protocol.cc.
References NS_LOG_FUNCTION.
~Icmpv6L4Protocol()
ns3::Icmpv6L4Protocol::~Icmpv6L4Protocol () virtual
Destructor.
Definition at line 113 of file icmpv6-l4-protocol.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AssignStreams()
int64_t ns3::Icmpv6L4Protocol::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 134 of file icmpv6-l4-protocol.cc.
References m_solicitationJitter, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
CreateCache()
Ptr< NdiscCache > ns3::Icmpv6L4Protocol::CreateCache (Ptr< NetDevice > device, Ptr< Ipv6Interface > interface) virtual
Create a neighbor cache.
Parameters
device thet NetDevice
interface the IPv6 interface
Returns
a smart pointer of NdCache or 0 if problem
Definition at line 1291 of file icmpv6-l4-protocol.cc.
References ns3::NdiscCache::Flush(), m_cacheList, ns3::MakeCallback(), NS_LOG_FUNCTION, and ns3::NdiscCache::SetDevice().
DelayedSendMessage()
void ns3::Icmpv6L4Protocol::DelayedSendMessage (Ptr< Packet > packet, Ipv6Address src, Ipv6Address dst, uint8_t ttl)
Helper function used during delayed solicitation.
Calls SendMessage internally
Parameters
packet the packet to send which contains ICMPv6 header
src source address
dst destination address
ttl next hop limit
Definition at line 923 of file icmpv6-l4-protocol.cc.
References NS_LOG_FUNCTION, and SendMessage().
Referenced by SendNS(), and SendRS().
DoDAD()
void ns3::Icmpv6L4Protocol::DoDAD (Ipv6Address target, Ptr< Ipv6Interface > interface)
Do the Duplication Address Detection (DAD).
It consists in sending a NS with our IPv6 as target. If we received a NA with matched target address, we could not use the address, else the address pass from TENTATIVE to PERMANENT.
Parameters
target target address
interface interface
Todo:
disable multicast loopback to prevent NS probing to be received by the sender
Definition at line 197 of file icmpv6-l4-protocol.cc.
References ForgeNS(), ns3::Ipv6Interface::GetDevice(), ns3::Object::GetObject(), ns3::RandomVariableStream::GetValue(), m_alwaysDad, m_node, m_solicitationJitter, ns3::Ipv6Address::MakeSolicitedAddress(), ns3::MilliSeconds(), NS_ASSERT, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), ns3::Ipv6Interface::Send(), and ns3::Ipv6Interface::SetNsDadUid().
Referenced by ns3::Ipv6Interface::AddAddress().
DoDispose()
void ns3::Icmpv6L4Protocol::DoDispose (void) protected virtual
Dispose this object.
Reimplemented from ns3::Object.
Definition at line 118 of file icmpv6-l4-protocol.cc.
References ns3::Object::Dispose(), ns3::Object::DoDispose(), m_cacheList, m_downTarget, m_node, NS_LOG_FUNCTION, and ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::Nullify().
FindCache()
Ptr< NdiscCache > ns3::Icmpv6L4Protocol::FindCache (Ptr< NetDevice > device) protected
Get the cache corresponding to the device.
Parameters
device the device
Returns
the NdiscCache associated with the device
Definition at line 1274 of file icmpv6-l4-protocol.cc.
References m_cacheList, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
Referenced by HandleNA(), HandleNS(), HandleRedirection(), HandleRS(), Lookup(), and ReceiveLLA().
ForgeEchoRequest()
NdiscCache::Ipv6PayloadHeaderPair ns3::Icmpv6L4Protocol::ForgeEchoRequest (Ipv6Address src, Ipv6Address dst, uint16_t id, uint16_t seq, Ptr< Packet > data)
Forge an Echo Request.
Parameters
src source address
dst destination address
id ID of the packet
seq sequence number
data the data
Returns
Echo Request packet (with IPv6 header)
Definition at line 607 of file icmpv6-l4-protocol.cc.
References ns3::Packet::AddHeader(), ns3::Icmpv6Header::CalculatePseudoHeaderChecksum(), data, ns3::Icmpv6Echo::GetSerializedSize(), ns3::Packet::GetSize(), NS_LOG_FUNCTION, PROT_NUMBER, ns3::Ipv6Header::SetDestinationAddress(), ns3::Ipv6Header::SetHopLimit(), ns3::Icmpv6Echo::SetId(), ns3::Ipv6Header::SetNextHeader(), ns3::Ipv6Header::SetPayloadLength(), ns3::Icmpv6Echo::SetSeq(), and ns3::Ipv6Header::SetSourceAddress().
ForgeNA()
NdiscCache::Ipv6PayloadHeaderPair ns3::Icmpv6L4Protocol::ForgeNA (Ipv6Address src, Ipv6Address dst, Address * hardwareAddress, uint8_t flags)
Forge a Neighbor Advertisement.
Parameters
src source IPv6 address
dst destination IPv6 address
hardwareAddress our mac address
flags flags (bitfield => R (4), S (2), O (1))
Returns
NA packet (with IPv6 header)
Definition at line 1211 of file icmpv6-l4-protocol.cc.
References ns3::Packet::AddHeader(), ns3::Icmpv6Header::CalculatePseudoHeaderChecksum(), ns3::Ipv6Address::GetAny(), ns3::Icmpv6NA::GetSerializedSize(), ns3::Packet::GetSize(), NS_LOG_FUNCTION, NS_LOG_LOGIC, PROT_NUMBER, ns3::Ipv6Header::SetDestinationAddress(), ns3::Icmpv6NA::SetFlagO(), ns3::Icmpv6NA::SetFlagR(), ns3::Icmpv6NA::SetFlagS(), ns3::Ipv6Header::SetHopLimit(), ns3::Icmpv6NA::SetIpv6Target(), ns3::Ipv6Header::SetNextHeader(), ns3::Ipv6Header::SetPayloadLength(), and ns3::Ipv6Header::SetSourceAddress().
Referenced by HandleNS().
ForgeNS()
NdiscCache::Ipv6PayloadHeaderPair ns3::Icmpv6L4Protocol::ForgeNS (Ipv6Address src, Ipv6Address dst, Ipv6Address target, Address hardwareAddress)
Forge a Neighbor Solicitation.
Parameters
src source IPv6 address
dst destination IPv6 address
target target IPv6 address
hardwareAddress our mac address
Returns
NS packet (with IPv6 header)
Definition at line 1251 of file icmpv6-l4-protocol.cc.
References ns3::Packet::AddHeader(), ns3::Icmpv6Header::CalculatePseudoHeaderChecksum(), ns3::Icmpv6NS::GetSerializedSize(), ns3::Packet::GetSize(), NS_LOG_FUNCTION, NS_LOG_LOGIC, PROT_NUMBER, ns3::Ipv6Header::SetDestinationAddress(), ns3::Ipv6Header::SetHopLimit(), ns3::Ipv6Header::SetNextHeader(), ns3::Ipv6Header::SetPayloadLength(), and ns3::Ipv6Header::SetSourceAddress().
Referenced by DoDAD().
ForgeRS()
NdiscCache::Ipv6PayloadHeaderPair ns3::Icmpv6L4Protocol::ForgeRS (Ipv6Address src, Ipv6Address dst, Address hardwareAddress)
Forge a Router Solicitation.
Parameters
src source IPv6 address
dst destination IPv6 address
hardwareAddress our mac address
Returns
RS packet (with IPv6 header)
Definition at line 584 of file icmpv6-l4-protocol.cc.
References ns3::Packet::AddHeader(), ns3::Icmpv6Header::CalculatePseudoHeaderChecksum(), ns3::Icmpv6RS::GetSerializedSize(), ns3::Packet::GetSize(), NS_LOG_FUNCTION, NS_LOG_LOGIC, PROT_NUMBER, ns3::Ipv6Header::SetDestinationAddress(), ns3::Ipv6Header::SetHopLimit(), ns3::Ipv6Header::SetNextHeader(), ns3::Ipv6Header::SetPayloadLength(), and ns3::Ipv6Header::SetSourceAddress().
Forward()
void ns3::Icmpv6L4Protocol::Forward (Ipv6Address source, Icmpv6Header icmp, uint32_t info, Ipv6Header ipHeader, const uint8_t payload[8]) protected
Notify an ICMPv6 reception to upper layers (if requested).
Parameters
source the ICMP source
icmp the ICMP header
info information about the ICMP
ipHeader the IP header carried by the ICMP
payload the data carried by the ICMP
Todo:
assuming the ICMP is carrying a extensionless IP packet
Definition at line 286 of file icmpv6-l4-protocol.cc.
References ns3::Icmpv6Header::GetCode(), ns3::Ipv6Header::GetDestinationAddress(), ns3::Ipv6Header::GetHopLimit(), ns3::Ipv6Header::GetNextHeader(), ns3::Object::GetObject(), ns3::Ipv6Header::GetSourceAddress(), ns3::Icmpv6Header::GetType(), m_node, NS_LOG_FUNCTION, PROT_NUMBER, and ns3::IpL4Protocol::ReceiveIcmp().
Referenced by HandleDestinationUnreachable(), HandlePacketTooBig(), HandleParameterError(), and HandleTimeExceeded().
FunctionDadTimeout()
void ns3::Icmpv6L4Protocol::FunctionDadTimeout (Ipv6Interface * interface, Ipv6Address addr)
Function called when DAD timeout.
Parameters
icmpv6 Icmpv6L4Protocol instance
interface the interface
addr the IPv6 address
Definition at line 1409 of file icmpv6-l4-protocol.cc.
References ns3::Ipv6InterfaceAddress::GetAddress(), ns3::Ipv6Interface::GetAddress(), ns3::Ipv6Address::GetAllRoutersMulticast(), ns3::Ipv6Interface::GetDevice(), ns3::Ipv6Interface::GetNAddresses(), ns3::Object::GetObject(), ns3::Ipv6InterfaceAddress::GetState(), ns3::Ipv6InterfaceAddress::INVALID, ns3::Ipv6Address::IsLinkLocal(), m_node, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Ipv6InterfaceAddress::PREFERRED, ns3::Simulator::Schedule(), ns3::Seconds(), SendRS(), and ns3::Ipv6Interface::SetState().
Referenced by ns3::Ipv6Interface::AddAddress().
GetDelayFirstProbe()
Time ns3::Icmpv6L4Protocol::GetDelayFirstProbe () const
Neighbor Discovery node constants : delay for the first probe.
Returns
The time before a first probe for an Neighbor cache entry.
Definition at line 1514 of file icmpv6-l4-protocol.cc.
References m_delayFirstProbe.
GetDownTarget()
IpL4Protocol::DownTargetCallback ns3::Icmpv6L4Protocol::GetDownTarget (void) const protected virtual
This method allows a caller to get the current down target callback set for this L4 protocol (IPv4 case)
Returns
current Callback for the L4 protocol
Implements ns3::IpL4Protocol.
Definition at line 1476 of file icmpv6-l4-protocol.cc.
References NS_LOG_FUNCTION.
GetDownTarget6()
IpL4Protocol::DownTargetCallback6 ns3::Icmpv6L4Protocol::GetDownTarget6 (void) const protected virtual
This method allows a caller to get the current down target callback set for this L4 protocol (IPv6 case)
Returns
current Callback for the L4 protocol
Implements ns3::IpL4Protocol.
Definition at line 1483 of file icmpv6-l4-protocol.cc.
References m_downTarget, and NS_LOG_FUNCTION.
GetInstanceTypeId()
TypeId ns3::Icmpv6L4Protocol::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Reimplemented from ns3::Object.
Definition at line 101 of file icmpv6-l4-protocol.cc.
References GetTypeId(), and NS_LOG_FUNCTION.
GetMaxMulticastSolicit()
uint8_t ns3::Icmpv6L4Protocol::GetMaxMulticastSolicit () const
Neighbor Discovery node constants: max multicast solicitations.
Returns
The max multicast solicitations number.
Definition at line 1490 of file icmpv6-l4-protocol.cc.
References m_maxMulticastSolicit.
GetMaxUnicastSolicit()
uint8_t ns3::Icmpv6L4Protocol::GetMaxUnicastSolicit () const
Neighbor Discovery node constants: max unicast solicitations.
Returns
The max unicast solicitations number.
Definition at line 1496 of file icmpv6-l4-protocol.cc.
References m_maxUnicastSolicit.
GetNode()
Ptr< Node > ns3::Icmpv6L4Protocol::GetNode (void)
Get the node.
Returns
node
Definition at line 167 of file icmpv6-l4-protocol.cc.
References m_node, and NS_LOG_FUNCTION.
GetProtocolNumber()
int ns3::Icmpv6L4Protocol::GetProtocolNumber (void) const virtual
Get the protocol number.
Returns
protocol number
Implements ns3::IpL4Protocol.
Definition at line 179 of file icmpv6-l4-protocol.cc.
References NS_LOG_FUNCTION, and PROT_NUMBER.
GetReachableTime()
Time ns3::Icmpv6L4Protocol::GetReachableTime () const
Neighbor Discovery node constants: reachable time.
Returns
The Reachable time for an Neighbor cache entry.
Definition at line 1502 of file icmpv6-l4-protocol.cc.
References m_reachableTime.
GetRetransmissionTime()
Time ns3::Icmpv6L4Protocol::GetRetransmissionTime () const
Neighbor Discovery node constants: retransmission timer.
Returns
The Retransmission time for an Neighbor cache entry probe.
Definition at line 1508 of file icmpv6-l4-protocol.cc.
References m_retransmissionTime.
GetStaticProtocolNumber()
uint16_t ns3::Icmpv6L4Protocol::GetStaticProtocolNumber (void) static
Get ICMPv6 protocol number.
Returns
protocol number
Definition at line 173 of file icmpv6-l4-protocol.cc.
References NS_LOG_FUNCTION_NOARGS, and PROT_NUMBER.
Referenced by ns3::Ipv6Interface::AddAddress(), ns3::Ipv6Interface::DoSetup(), ns3::Ipv6RawSocketImpl::ForwardUp(), ns3::Ipv6L3Protocol::GetIcmpv6(), ns3::Ipv6Interface::Send(), and ns3::Ipv6RawSocketImpl::SendTo().
GetTypeId()
TypeId ns3::Icmpv6L4Protocol::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 63 of file icmpv6-l4-protocol.cc.
References m_alwaysDad, m_delayFirstProbe, m_maxMulticastSolicit, m_maxUnicastSolicit, m_reachableTime, m_retransmissionTime, m_solicitationJitter, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeIntegerAccessor(), ns3::MakePointerAccessor(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::Seconds(), and ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
GetVersion()
int ns3::Icmpv6L4Protocol::GetVersion () const virtual
Get the version of the protocol.
Returns
version
Definition at line 185 of file icmpv6-l4-protocol.cc.
References NS_LOG_FUNCTION.
HandleDestinationUnreachable()
void ns3::Icmpv6L4Protocol::HandleDestinationUnreachable (Ptr< Packet > p, Ipv6Address const & src, Ipv6Address const & dst, Ptr< Ipv6Interface > interface) protected
Receive Destination Unreachable method.
Parameters
p the packet
src source address
dst destination address
interface the interface from which the packet is coming
Definition at line 840 of file icmpv6-l4-protocol.cc.
References ns3::Packet::Copy(), ns3::Packet::CopyData(), Forward(), ns3::Icmpv6Header::GetCode(), ns3::Icmpv6DestinationUnreachable::GetPacket(), ns3::Ipv6Header::GetSerializedSize(), ns3::Packet::GetSize(), NS_LOG_FUNCTION, and ns3::Packet::RemoveHeader().
HandleEchoRequest()
void ns3::Icmpv6L4Protocol::HandleEchoRequest (Ptr< Packet > p, Ipv6Address const & src, Ipv6Address const & dst, Ptr< Ipv6Interface > interface) protected
Receive Echo Request method.
Parameters
p the packet
src source address
dst destination address
interface the interface from which the packet is coming
Definition at line 309 of file icmpv6-l4-protocol.cc.
References ns3::Packet::CopyData(), ns3::Ipv6InterfaceAddress::GetAddress(), ns3::Icmpv6Echo::GetId(), ns3::Ipv6Interface::GetLinkLocalAddress(), ns3::Icmpv6Echo::GetSeq(), ns3::Packet::GetSize(), ns3::Ipv6Address::IsMulticast(), NS_LOG_FUNCTION, ns3::Packet::RemoveHeader(), and SendEchoReply().
HandleNA()
void ns3::Icmpv6L4Protocol::HandleNA (Ptr< Packet > p, Ipv6Address const & src, Ipv6Address const & dst, Ptr< Ipv6Interface > interface) protected
Receive Neighbor Advertisement method.
Parameters
p the packet
src source address
dst destination address
interface the interface from which the packet is coming
Definition at line 629 of file icmpv6-l4-protocol.cc.
References ns3::NdiscCache::Entry::ClearWaitingPacket(), ns3::Packet::CopyData(), FindCache(), ns3::Icmpv6OptionLinkLayerAddress::GetAddress(), ns3::Ipv6InterfaceAddress::GetAddress(), ns3::Ipv6Interface::GetAddress(), ns3::Ipv6Interface::GetDevice(), ns3::Icmpv6NA::GetFlagO(), ns3::Icmpv6NA::GetFlagR(), ns3::Icmpv6NA::GetFlagS(), ns3::NdiscCache::GetInterface(), ns3::Icmpv6NA::GetIpv6Target(), ns3::NdiscCache::Entry::GetMacAddress(), ns3::Ipv6Interface::GetNAddresses(), ns3::Ipv6InterfaceAddress::GetState(), ns3::Icmpv6Header::ICMPV6_OPT_LINK_LAYER_TARGET, ns3::Ipv6InterfaceAddress::INVALID, ns3::NdiscCache::Entry::IsIncomplete(), ns3::NdiscCache::Entry::IsPermanent(), ns3::NdiscCache::Entry::IsProbe(), ns3::NdiscCache::Entry::IsReachable(), ns3::NdiscCache::Lookup(), ns3::NdiscCache::Entry::MarkReachable(), ns3::NdiscCache::Entry::MarkStale(), NS_LOG_FUNCTION, ns3::Packet::RemoveHeader(), ns3::Ipv6Interface::Send(), ns3::NdiscCache::Entry::SetMacAddress(), ns3::NdiscCache::Entry::SetRouter(), ns3::Ipv6Interface::SetState(), ns3::NdiscCache::Entry::StartReachableTimer(), ns3::NdiscCache::Entry::StopNudTimer(), ns3::Ipv6InterfaceAddress::TENTATIVE, and ns3::Ipv6InterfaceAddress::TENTATIVE_OPTIMISTIC.
HandleNS()
void ns3::Icmpv6L4Protocol::HandleNS (Ptr< Packet > p, Ipv6Address const & src, Ipv6Address const & dst, Ptr< Ipv6Interface > interface) protected
Receive Neighbor Solicitation method.
Parameters
p the packet
src source address
dst destination address
interface the interface from which the packet is coming
Definition at line 488 of file icmpv6-l4-protocol.cc.
References ns3::NdiscCache::Add(), ns3::Packet::CopyData(), FindCache(), ForgeNA(), ns3::Icmpv6OptionLinkLayerAddress::GetAddress(), ns3::Ipv6InterfaceAddress::GetAddress(), ns3::Ipv6Interface::GetAddress(), ns3::Ipv6Address::GetAllNodesMulticast(), ns3::Ipv6Address::GetAny(), ns3::Ipv6Interface::GetDevice(), ns3::Icmpv6NS::GetIpv6Target(), ns3::Ipv6Interface::GetLinkLocalAddress(), ns3::NdiscCache::Entry::GetMacAddress(), ns3::Ipv6Interface::GetNAddresses(), ns3::Ipv6InterfaceAddress::GetNsDadUid(), ns3::Object::GetObject(), ns3::Packet::GetUid(), ns3::Icmpv6Header::ICMPV6_OPT_LINK_LAYER_SOURCE, ns3::Ipv6Address::IsAny(), ns3::Ipv6Address::IsLinkLocal(), ns3::NdiscCache::Lookup(), m_node, ns3::NdiscCache::Entry::MarkStale(), NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Packet::RemoveHeader(), ns3::Ipv6Interface::Send(), and ns3::NdiscCache::Entry::SetRouter().
HandlePacketTooBig()
void ns3::Icmpv6L4Protocol::HandlePacketTooBig (Ptr< Packet > p, Ipv6Address const & src, Ipv6Address const & dst, Ptr< Ipv6Interface > interface) protected
Receive Packet Too Big method.
Parameters
p the packet
src source address
dst destination address
interface the interface from which the packet is coming
Definition at line 875 of file icmpv6-l4-protocol.cc.
References ns3::Packet::Copy(), ns3::Packet::CopyData(), Forward(), ns3::Ipv6Header::GetDestinationAddress(), ns3::Icmpv6TooBig::GetMtu(), ns3::Object::GetObject(), ns3::Icmpv6TooBig::GetPacket(), m_node, NS_LOG_FUNCTION, and ns3::Packet::RemoveHeader().
HandleParameterError()
void ns3::Icmpv6L4Protocol::HandleParameterError (Ptr< Packet > p, Ipv6Address const & src, Ipv6Address const & dst, Ptr< Ipv6Interface > interface) protected
Receive Parameter Error method.
Parameters
p the packet
src source address
dst destination address
interface the interface from which the packet is coming
Definition at line 895 of file icmpv6-l4-protocol.cc.
References ns3::Packet::Copy(), ns3::Packet::CopyData(), Forward(), ns3::Icmpv6Header::GetCode(), ns3::Icmpv6ParameterError::GetPacket(), NS_LOG_FUNCTION, and ns3::Packet::RemoveHeader().
HandleRA()
void ns3::Icmpv6L4Protocol::HandleRA (Ptr< Packet > p, Ipv6Address const & src, Ipv6Address const & dst, Ptr< Ipv6Interface > interface) protected
Receive Router Advertisement method.
Parameters
p the packet
src source address
dst destination address
interface the interface from which the packet is coming
Todo:
case of multiple prefix on single interface
Definition at line 325 of file icmpv6-l4-protocol.cc.
References ns3::Packet::Copy(), ns3::Packet::CopyData(), ns3::Ipv6Interface::GetDevice(), ns3::Icmpv6RA::GetLifeTime(), ns3::Object::GetObject(), ns3::Ipv6Address::GetZero(), ns3::Icmpv6Header::ICMPV6_OPT_LINK_LAYER_SOURCE, ns3::Icmpv6Header::ICMPV6_OPT_MTU, ns3::Icmpv6Header::ICMPV6_OPT_PREFIX, m_node, NS_LOG_FUNCTION, ReceiveLLA(), and ns3::Packet::RemoveHeader().
HandleRedirection()
void ns3::Icmpv6L4Protocol::HandleRedirection (Ptr< Packet > p, Ipv6Address const & src, Ipv6Address const & dst, Ptr< Ipv6Interface > interface) protected
Receive Redirection method.
Parameters
p the packet
src source address
dst destination address
interface the interface from which the packet is coming
Definition at line 768 of file icmpv6-l4-protocol.cc.
References ns3::NdiscCache::Add(), ns3::Packet::Copy(), ns3::Packet::CopyData(), FindCache(), ns3::Icmpv6OptionLinkLayerAddress::GetAddress(), ns3::Icmpv6Redirection::GetDestination(), ns3::Ipv6Interface::GetDevice(), ns3::NdiscCache::Entry::GetMacAddress(), ns3::Object::GetObject(), ns3::Icmpv6Redirection::GetTarget(), ns3::Icmpv6Header::ICMPV6_OPT_LINK_LAYER_TARGET, ns3::NdiscCache::Entry::IsIncomplete(), ns3::NdiscCache::Lookup(), m_node, ns3::NdiscCache::Entry::MarkStale(), NS_LOG_FUNCTION, ns3::Packet::RemoveHeader(), ns3::NdiscCache::Entry::SetMacAddress(), and ns3::NdiscCache::Entry::SetRouter().
HandleRS()
void ns3::Icmpv6L4Protocol::HandleRS (Ptr< Packet > p, Ipv6Address const & src, Ipv6Address const & dst, Ptr< Ipv6Interface > interface) protected
Receive Router Solicitation method.
Parameters
p the packet
src source address
dst destination address
interface the interface from which the packet is coming
Definition at line 449 of file icmpv6-l4-protocol.cc.
References ns3::NdiscCache::Add(), ns3::Packet::CopyData(), FindCache(), ns3::Icmpv6OptionLinkLayerAddress::GetAddress(), ns3::Ipv6Address::GetAny(), ns3::Ipv6Interface::GetDevice(), ns3::NdiscCache::Entry::GetMacAddress(), ns3::Object::GetObject(), ns3::Icmpv6Header::ICMPV6_OPT_LINK_LAYER_SOURCE, ns3::NdiscCache::Lookup(), m_node, ns3::NdiscCache::Entry::MarkStale(), NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Packet::RemoveHeader(), and ns3::NdiscCache::Entry::SetRouter().
HandleTimeExceeded()
void ns3::Icmpv6L4Protocol::HandleTimeExceeded (Ptr< Packet > p, Ipv6Address const & src, Ipv6Address const & dst, Ptr< Ipv6Interface > interface) protected
Receive Time Exceeded method.
Parameters
p the packet
src source address
dst destination address
interface the interface from which the packet is coming
Definition at line 859 of file icmpv6-l4-protocol.cc.
References ns3::Packet::Copy(), ns3::Packet::CopyData(), Forward(), ns3::Icmpv6Header::GetCode(), ns3::Icmpv6TimeExceeded::GetPacket(), NS_LOG_FUNCTION, and ns3::Packet::RemoveHeader().
IsAlwaysDad()
bool ns3::Icmpv6L4Protocol::IsAlwaysDad () const
Is the node must do DAD.
Returns
true if node has to do DAD.
Definition at line 191 of file icmpv6-l4-protocol.cc.
References m_alwaysDad, and NS_LOG_FUNCTION.
Lookup() [1/2]
bool ns3::Icmpv6L4Protocol::Lookup (Ipv6Address dst, Ptr< NetDevice > device, Ptr< NdiscCache > cache, Address * hardwareDestination)
Lookup in the ND cache for the IPv6 address.
Note
Unlike other Lookup method, it does not send NS request!
Parameters
dst destination address
device device
cache the neighbor cache
hardwareDestination hardware address
Returns
true if the address is in the ND cache, the hardwareDestination is updated.
Definition at line 1303 of file icmpv6-l4-protocol.cc.
References FindCache(), ns3::NdiscCache::Entry::GetMacAddress(), ns3::NdiscCache::Entry::IsDelay(), ns3::NdiscCache::Entry::IsPermanent(), ns3::NdiscCache::Entry::IsReachable(), ns3::NdiscCache::Entry::IsStale(), ns3::NdiscCache::Lookup(), ns3::NdiscCache::Entry::MarkDelay(), NS_LOG_FUNCTION, and ns3::NdiscCache::Entry::StartDelayTimer().
Lookup() [2/2]
bool ns3::Icmpv6L4Protocol::Lookup (Ptr< Packet > p, const Ipv6Header & ipHeader, Ipv6Address dst, Ptr< NetDevice > device, Ptr< NdiscCache > cache, Address * hardwareDestination)
Lookup in the ND cache for the IPv6 address (similar as ARP protocol).
It also send NS request to target and store the waiting packet.
Parameters
p the packet
ipHeader IPv6 header
dst destination address
device device
cache the neighbor cache
hardwareDestination hardware address
Returns
true if the address is in the ND cache, the hardwareDestination is updated.
Definition at line 1334 of file icmpv6-l4-protocol.cc.
References ns3::NdiscCache::Add(), ns3::NdiscCache::Entry::AddWaitingPacket(), FindCache(), ns3::Ipv6InterfaceAddress::GetAddress(), ns3::Ipv6Interface::GetAddressMatchingDestination(), ns3::NdiscCache::GetDevice(), ns3::NdiscCache::GetInterface(), ns3::Ipv6Interface::GetLinkLocalAddress(), ns3::NdiscCache::Entry::GetMacAddress(), ns3::Ipv6Interface::GetNAddresses(), ns3::NdiscCache::Entry::IsDelay(), ns3::Ipv6Address::IsLinkLocal(), ns3::NdiscCache::Entry::IsPermanent(), ns3::NdiscCache::Entry::IsReachable(), ns3::NdiscCache::Entry::IsStale(), ns3::NdiscCache::Lookup(), ns3::Ipv6Address::MakeSolicitedAddress(), ns3::NdiscCache::Entry::MarkDelay(), ns3::NdiscCache::Entry::MarkIncomplete(), NS_LOG_FUNCTION, ns3::NdiscCache::Remove(), SendNS(), ns3::NdiscCache::Entry::SetRouter(), ns3::NdiscCache::Entry::StartDelayTimer(), and ns3::NdiscCache::Entry::StartRetransmitTimer().
NotifyNewAggregate()
void ns3::Icmpv6L4Protocol::NotifyNewAggregate (void) virtual
This method is called by AggregateObject and completes the aggregation by setting the node in the ICMPv6 stack and adding ICMPv6 factory to IPv6 stack connected to the node.
Reimplemented from ns3::Object.
Definition at line 141 of file icmpv6-l4-protocol.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_downTarget, m_node, ns3::MakeCallback(), ns3::Object::NotifyNewAggregate(), NS_LOG_FUNCTION, ns3::Ipv6::Send(), SetDownTarget6(), and SetNode().
Receive() [1/2]
enum IpL4Protocol::RxStatus ns3::Icmpv6L4Protocol::Receive (Ptr< Packet > p, Ipv4Header const & header, Ptr< Ipv4Interface > interface) virtual
Receive method.
Parameters
p the packet
header the IPv4 header
interface the interface from which the packet is coming
Returns
the receive status
Implements ns3::IpL4Protocol.
Definition at line 197 of file icmpv6-l4-protocol.cc.
Receive() [2/2]
enum IpL4Protocol::RxStatus ns3::Icmpv6L4Protocol::Receive (Ptr< Packet > p, Ipv6Header const & header, Ptr< Ipv6Interface > interface) virtual
Receive method.
Parameters
p the packet
header the IPv6 header
interface the interface from which the packet is coming
Returns
the receive status
Todo:
implement request / reply consistency check.
Implements ns3::IpL4Protocol.
Definition at line 197 of file icmpv6-l4-protocol.cc.
ReceiveLLA()
void ns3::Icmpv6L4Protocol::ReceiveLLA (Icmpv6OptionLinkLayerAddress lla, Ipv6Address const & src, Ipv6Address const & dst, Ptr< Ipv6Interface > interface) protected
Link layer address option processing.
Parameters
lla LLA option
src source address
dst destination address
interface the interface from which the packet is coming
Definition at line 384 of file icmpv6-l4-protocol.cc.
References ns3::NdiscCache::Add(), ns3::NdiscCache::Entry::ClearWaitingPacket(), FindCache(), ns3::Icmpv6OptionLinkLayerAddress::GetAddress(), ns3::Ipv6Interface::GetDevice(), ns3::NdiscCache::GetInterface(), ns3::NdiscCache::Entry::GetMacAddress(), ns3::NdiscCache::Entry::IsIncomplete(), ns3::NdiscCache::Entry::IsPermanent(), ns3::NdiscCache::Entry::IsProbe(), ns3::NdiscCache::Entry::IsReachable(), ns3::NdiscCache::Lookup(), ns3::NdiscCache::Entry::MarkReachable(), ns3::NdiscCache::Entry::MarkStale(), NS_LOG_FUNCTION, ns3::Ipv6Interface::Send(), ns3::NdiscCache::Entry::SetMacAddress(), ns3::NdiscCache::Entry::SetRouter(), ns3::NdiscCache::Entry::StartReachableTimer(), and ns3::NdiscCache::Entry::StopNudTimer().
Referenced by HandleRA().
SendEchoReply()
void ns3::Icmpv6L4Protocol::SendEchoReply (Ipv6Address src, Ipv6Address dst, uint16_t id, uint16_t seq, Ptr< Packet > data)
Send a Echo Reply.
Parameters
src source IPv6 address
dst destination IPv6 address
id id of the packet
seq sequence number
data auxiliary data
Definition at line 990 of file icmpv6-l4-protocol.cc.
References ns3::Packet::AddHeader(), ns3::Icmpv6Header::CalculatePseudoHeaderChecksum(), data, ns3::Icmpv6Echo::GetSerializedSize(), ns3::Packet::GetSize(), NS_LOG_FUNCTION, PROT_NUMBER, SendMessage(), ns3::Icmpv6Echo::SetId(), and ns3::Icmpv6Echo::SetSeq().
Referenced by HandleEchoRequest().
SendErrorDestinationUnreachable()
void ns3::Icmpv6L4Protocol::SendErrorDestinationUnreachable (Ptr< Packet > malformedPacket, Ipv6Address dst, uint8_t code)
Send an error Destination Unreachable.
Parameters
malformedPacket the malformed packet
dst destination IPv6 address
code code of the error
Definition at line 1062 of file icmpv6-l4-protocol.cc.
References ns3::Packet::CreateFragment(), ns3::Packet::GetSize(), NS_LOG_FUNCTION, NS_LOG_LOGIC, SendMessage(), ns3::Icmpv6Header::SetCode(), and ns3::Icmpv6DestinationUnreachable::SetPacket().
SendErrorParameterError()
void ns3::Icmpv6L4Protocol::SendErrorParameterError (Ptr< Packet > malformedPacket, Ipv6Address dst, uint8_t code, uint32_t ptr)
Send an error Parameter Error.
Parameters
malformedPacket the malformed packet
dst destination IPv6 address
code code of the error
ptr byte of p where the error is located
Definition at line 1135 of file icmpv6-l4-protocol.cc.
References ns3::Packet::CreateFragment(), ns3::Packet::GetSize(), NS_LOG_FUNCTION, NS_LOG_LOGIC, SendMessage(), ns3::Icmpv6Header::SetCode(), ns3::Icmpv6ParameterError::SetPacket(), and ns3::Icmpv6ParameterError::SetPtr().
SendErrorTimeExceeded()
void ns3::Icmpv6L4Protocol::SendErrorTimeExceeded (Ptr< Packet > malformedPacket, Ipv6Address dst, uint8_t code)
Send an error Time Exceeded.
Parameters
malformedPacket the malformed packet
dst destination IPv6 address
code code of the error
Definition at line 1111 of file icmpv6-l4-protocol.cc.
References ns3::Packet::CreateFragment(), ns3::Packet::GetSize(), NS_LOG_FUNCTION, NS_LOG_LOGIC, SendMessage(), ns3::Icmpv6Header::SetCode(), and ns3::Icmpv6TimeExceeded::SetPacket().
SendErrorTooBig()
void ns3::Icmpv6L4Protocol::SendErrorTooBig (Ptr< Packet > malformedPacket, Ipv6Address dst, uint32_t mtu)
Send an error Too Big.
Parameters
malformedPacket the malformed packet
dst destination IPv6 address
mtu the mtu
Definition at line 1086 of file icmpv6-l4-protocol.cc.
References ns3::Packet::CreateFragment(), ns3::Packet::GetSize(), NS_LOG_FUNCTION, NS_LOG_LOGIC, SendMessage(), ns3::Icmpv6Header::SetCode(), ns3::Icmpv6TooBig::SetMtu(), and ns3::Icmpv6TooBig::SetPacket().
SendMessage() [1/2]
void ns3::Icmpv6L4Protocol::SendMessage (Ptr< Packet > packet, Ipv6Address dst, Icmpv6Header & icmpv6Hdr, uint8_t ttl)
Send a packet via ICMPv6.
Parameters
packet the packet to send
dst destination address
icmpv6Hdr ICMPv6 header (needed to calculate checksum after source address is determined by routing stuff
ttl next hop limit
Definition at line 929 of file icmpv6-l4-protocol.cc.
References ns3::Packet::AddHeader(), ns3::Packet::AddPacketTag(), ns3::Icmpv6Header::CalculatePseudoHeaderChecksum(), ns3::Object::GetObject(), ns3::Icmpv6Header::GetSerializedSize(), ns3::Packet::GetSize(), m_downTarget, m_node, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, NS_LOG_WARN, PROT_NUMBER, ns3::Ipv6Header::SetDestinationAddress(), and ns3::SocketIpv6HopLimitTag::SetHopLimit().
SendMessage() [2/2]
void ns3::Icmpv6L4Protocol::SendMessage (Ptr< Packet > packet, Ipv6Address src, Ipv6Address dst, uint8_t ttl)
Send a packet via ICMPv6, note that packet already contains ICMPv6 header.
Parameters
packet the packet to send which contains ICMPv6 header
src source address
dst destination address
ttl next hop limit
Definition at line 911 of file icmpv6-l4-protocol.cc.
References ns3::Packet::AddPacketTag(), ns3::Object::GetObject(), m_downTarget, m_node, NS_ASSERT, NS_LOG_FUNCTION, and PROT_NUMBER.
Referenced by DelayedSendMessage(), SendEchoReply(), SendErrorDestinationUnreachable(), SendErrorParameterError(), SendErrorTimeExceeded(), SendErrorTooBig(), SendNA(), SendNS(), SendRedirection(), and SendRS().
SendNA()
void ns3::Icmpv6L4Protocol::SendNA (Ipv6Address src, Ipv6Address dst, Address * hardwareAddress, uint8_t flags)
Send a Neighbor Adverstisement.
Parameters
src source IPv6 address
dst destination IPv6 address
hardwareAddress our MAC address
flags to set (4 = flag R, 2 = flag S, 3 = flag O)
Definition at line 960 of file icmpv6-l4-protocol.cc.
References ns3::Packet::AddHeader(), ns3::Icmpv6Header::CalculatePseudoHeaderChecksum(), ns3::Ipv6Address::GetAny(), ns3::Icmpv6NA::GetSerializedSize(), ns3::Packet::GetSize(), NS_LOG_FUNCTION, NS_LOG_LOGIC, PROT_NUMBER, SendMessage(), ns3::Icmpv6NA::SetFlagO(), ns3::Icmpv6NA::SetFlagR(), ns3::Icmpv6NA::SetFlagS(), and ns3::Icmpv6NA::SetIpv6Target().
SendNS()
void ns3::Icmpv6L4Protocol::SendNS (Ipv6Address src, Ipv6Address dst, Ipv6Address target, Address hardwareAddress) virtual
Send a Neighbor Solicitation.
Parameters
src source IPv6 address
dst destination IPv6 address
target target IPv6 address
hardwareAddress our mac address
Definition at line 1004 of file icmpv6-l4-protocol.cc.
References ns3::Packet::AddHeader(), ns3::Icmpv6Header::CalculatePseudoHeaderChecksum(), DelayedSendMessage(), ns3::Ipv6Address::GetAllNodesMulticast(), ns3::Ipv6Address::GetAny(), ns3::Icmpv6NS::GetSerializedSize(), ns3::Packet::GetSize(), ns3::RandomVariableStream::GetValue(), ns3::Ipv6Address::IsMulticast(), m_solicitationJitter, ns3::MilliSeconds(), NS_LOG_FUNCTION, NS_LOG_LOGIC, PROT_NUMBER, ns3::Simulator::Schedule(), and SendMessage().
Referenced by Lookup().
SendRedirection()
void ns3::Icmpv6L4Protocol::SendRedirection (Ptr< Packet > redirectedPacket, Ipv6Address src, Ipv6Address dst, Ipv6Address redirTarget, Ipv6Address redirDestination, Address redirHardwareTarget)
Send an ICMPv6 Redirection.
Parameters
redirectedPacket the redirected packet
src IPv6 address to send the redirect from
dst IPv6 address to send the redirect to
redirTarget IPv6 target address for Icmpv6Redirection
redirDestination IPv6 destination address for Icmpv6Redirection
redirHardwareTarget L2 target address for Icmpv6OptionRdirected
Definition at line 1160 of file icmpv6-l4-protocol.cc.
References ns3::Packet::AddAtEnd(), ns3::Packet::AddHeader(), ns3::Icmpv6Header::CalculatePseudoHeaderChecksum(), ns3::Packet::CreateFragment(), ns3::Address::GetLength(), ns3::Icmpv6Redirection::GetSerializedSize(), ns3::Icmpv6OptionLinkLayerAddress::GetSerializedSize(), ns3::Packet::GetSize(), NS_LOG_FUNCTION, NS_LOG_LOGIC, PROT_NUMBER, SendMessage(), ns3::Icmpv6OptionLinkLayerAddress::SetAddress(), ns3::Icmpv6Redirection::SetDestination(), ns3::Icmpv6OptionRedirected::SetPacket(), and ns3::Icmpv6Redirection::SetTarget().
SendRS()
void ns3::Icmpv6L4Protocol::SendRS (Ipv6Address src, Ipv6Address dst, Address hardwareAddress)
Send a Router Solicitation.
Parameters
src link-local source address
dst destination address (usually ff02::2 i.e all-routers)
hardwareAddress link-layer address (SHOULD be included if src is not ::)
Definition at line 1034 of file icmpv6-l4-protocol.cc.
References ns3::Packet::AddHeader(), ns3::Icmpv6Header::CalculatePseudoHeaderChecksum(), DelayedSendMessage(), ns3::Ipv6Address::GetAny(), ns3::Icmpv6RS::GetSerializedSize(), ns3::Packet::GetSize(), ns3::RandomVariableStream::GetValue(), ns3::Ipv6Address::IsMulticast(), m_solicitationJitter, ns3::MilliSeconds(), NS_LOG_FUNCTION, NS_LOG_LOGIC, PROT_NUMBER, ns3::Simulator::Schedule(), and SendMessage().
Referenced by FunctionDadTimeout().
SetDownTarget()
void ns3::Icmpv6L4Protocol::SetDownTarget (IpL4Protocol::DownTargetCallback cb) protected virtual
This method allows a caller to set the current down target callback set for this L4 protocol (IPv4 case)
Parameters
cb current Callback for the L4 protocol
Implements ns3::IpL4Protocol.
Definition at line 1463 of file icmpv6-l4-protocol.cc.
References NS_LOG_FUNCTION.
SetDownTarget6()
void ns3::Icmpv6L4Protocol::SetDownTarget6 (IpL4Protocol::DownTargetCallback6 cb) protected virtual
This method allows a caller to set the current down target callback set for this L4 protocol (IPv6 case)
Parameters
cb current Callback for the L4 protocol
Implements ns3::IpL4Protocol.
Definition at line 1469 of file icmpv6-l4-protocol.cc.
References m_downTarget, and NS_LOG_FUNCTION.
Referenced by NotifyNewAggregate().
SetNode()
void ns3::Icmpv6L4Protocol::SetNode (Ptr< Node > node)
Set the node.
Parameters
node the node to set
Definition at line 161 of file icmpv6-l4-protocol.cc.
References m_node, and NS_LOG_FUNCTION.
Referenced by NotifyNewAggregate().
Member Data Documentation
m_alwaysDad
bool ns3::Icmpv6L4Protocol::m_alwaysDad protected
Always do DAD ?
Definition at line 520 of file icmpv6-l4-protocol.h.
Referenced by DoDAD(), GetTypeId(), and IsAlwaysDad().
m_cacheList
CacheList ns3::Icmpv6L4Protocol::m_cacheList protected
A list of cache by device.
Definition at line 525 of file icmpv6-l4-protocol.h.
Referenced by CreateCache(), DoDispose(), and FindCache().
m_delayFirstProbe
Time ns3::Icmpv6L4Protocol::m_delayFirstProbe private
Neighbor Discovery node constants: delay for the first probe.
Definition at line 551 of file icmpv6-l4-protocol.h.
Referenced by GetDelayFirstProbe(), and GetTypeId().
m_downTarget
IpL4Protocol::DownTargetCallback6 ns3::Icmpv6L4Protocol::m_downTarget private
callback to Ipv6::Send
Definition at line 563 of file icmpv6-l4-protocol.h.
Referenced by DoDispose(), GetDownTarget6(), NotifyNewAggregate(), SendMessage(), and SetDownTarget6().
m_maxMulticastSolicit
uint8_t ns3::Icmpv6L4Protocol::m_maxMulticastSolicit private
Neighbor Discovery node constants: max multicast solicitations.
Definition at line 531 of file icmpv6-l4-protocol.h.
Referenced by GetMaxMulticastSolicit(), and GetTypeId().
m_maxUnicastSolicit
uint8_t ns3::Icmpv6L4Protocol::m_maxUnicastSolicit private
Neighbor Discovery node constants: max unicast solicitations.
Definition at line 536 of file icmpv6-l4-protocol.h.
Referenced by GetMaxUnicastSolicit(), and GetTypeId().
m_node
Ptr<Node> ns3::Icmpv6L4Protocol::m_node private
The node.
Definition at line 556 of file icmpv6-l4-protocol.h.
Referenced by DoDAD(), DoDispose(), Forward(), FunctionDadTimeout(), GetNode(), HandleNS(), HandlePacketTooBig(), HandleRA(), HandleRedirection(), HandleRS(), NotifyNewAggregate(), SendMessage(), and SetNode().
m_reachableTime
Time ns3::Icmpv6L4Protocol::m_reachableTime private
Neighbor Discovery node constants: reachable time.
Definition at line 541 of file icmpv6-l4-protocol.h.
Referenced by GetReachableTime(), and GetTypeId().
m_retransmissionTime
Time ns3::Icmpv6L4Protocol::m_retransmissionTime private
Neighbor Discovery node constants: retransmission timer.
Definition at line 546 of file icmpv6-l4-protocol.h.
Referenced by GetRetransmissionTime(), and GetTypeId().
m_solicitationJitter
Ptr<RandomVariableStream> ns3::Icmpv6L4Protocol::m_solicitationJitter private
Random jitter before sending solicitations.
Definition at line 561 of file icmpv6-l4-protocol.h.
Referenced by AssignStreams(), DoDAD(), GetTypeId(), SendNS(), and SendRS().
PROT_NUMBER
const uint8_t ns3::Icmpv6L4Protocol::PROT_NUMBER = 58 static
ICMPv6 protocol number (58).
Definition at line 65 of file icmpv6-l4-protocol.h.
Referenced by ForgeEchoRequest(), ForgeNA(), ForgeNS(), ForgeRS(), Forward(), GetProtocolNumber(), GetStaticProtocolNumber(), SendEchoReply(), SendMessage(), SendNA(), SendNS(), SendRedirection(), and SendRS().
The documentation for this class was generated from the following files:
src/internet/model/icmpv6-l4-protocol.h
src/internet/model/icmpv6-l4-protocol.cc