ns-3: ns3::Ipv4Route Class Reference
ns3::Ipv4Route Class Reference
Internet » IPv4 Routing Protocols.
IPv4 route cache entry (similar to Linux struct rtable)
#include "ipv4-route.h"
Public Member Functions
Ipv4Route ()
Ipv4Address GetDestination (void) const
Ipv4Address GetGateway (void) const
Ptr< NetDevice > GetOutputDevice (void) const
Ipv4Address GetSource (void) const
void SetDestination (Ipv4Address dest)
void SetGateway (Ipv4Address gw)
void SetOutputDevice (Ptr< NetDevice > outputDevice)
Equivalent in Linux to dst_entry.dev.
void SetSource (Ipv4Address src)
Public Member Functions inherited from ns3::SimpleRefCount< Ipv4Route >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
Ipv4Address m_dest
Destination address.
Ipv4Address m_gateway
Gateway address.
Ptr< NetDevice > m_outputDevice
Output device.
Ipv4Address m_source
Source address.
Detailed Description
IPv4 route cache entry (similar to Linux struct rtable)
This is a reference counted object. In the future, we will add other entries from struct dst_entry, struct rtable, and struct dst_ops as needed.
Definition at line 41 of file ipv4-route.h.
Constructor & Destructor Documentation
Ipv4Route()
ns3::Ipv4Route::Ipv4Route ()
Definition at line 29 of file ipv4-route.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
GetDestination()
Ipv4Address ns3::Ipv4Route::GetDestination (void) const
Returns
Destination Ipv4Address of the route
Definition at line 42 of file ipv4-route.cc.
References m_dest, and NS_LOG_FUNCTION.
Referenced by ns3::aodv::AodvRtableEntryTest::DoRun(), ns3::aodv::RoutingTableEntry::GetDestination(), ns3::dsdv::RoutingTableEntry::GetDestination(), ns3::dsdv::RoutingProtocol::LookForQueuedPackets(), ns3::Rip::Lookup(), ns3::operator<<(), ns3::dsdv::RoutingTableEntry::operator==(), ns3::aodv::RoutingTableEntry::operator==(), ns3::aodv::RoutingTableEntry::Print(), ns3::dsdv::RoutingTableEntry::Print(), ns3::aodv::RoutingProtocol::RouteOutput(), ns3::dsdv::RoutingProtocol::RouteOutput(), and ns3::olsr::RoutingProtocol::RouteOutput().
GetGateway()
Ipv4Address ns3::Ipv4Route::GetGateway (void) const
Returns
Ipv4Address of the gateway (next hop)
Definition at line 70 of file ipv4-route.cc.
References m_gateway, and NS_LOG_FUNCTION.
Referenced by ns3::aodv::RoutingProtocol::Forwarding(), ns3::aodv::RoutingTableEntry::GetNextHop(), ns3::dsdv::RoutingTableEntry::GetNextHop(), ns3::Rip::Lookup(), ns3::Ipv4StaticRouting::LookupStatic(), ns3::operator<<(), ns3::aodv::RoutingTableEntry::Print(), ns3::dsdv::RoutingTableEntry::Print(), ns3::AnimationInterface::RecursiveIpv4RoutePathSearch(), ns3::aodv::RoutingProtocol::RouteOutput(), ns3::olsr::RoutingProtocol::RouteOutput(), ns3::Ipv4L3Protocol::Send(), ns3::Ipv4L3Protocol::SendRealOut(), and ns3::AnimationInterface::TrackIpv4RoutePaths().
GetOutputDevice()
Ptr< NetDevice > ns3::Ipv4Route::GetOutputDevice (void) const
Returns
pointer to NetDevice for outgoing packets
Definition at line 84 of file ipv4-route.cc.
References m_outputDevice, and NS_LOG_FUNCTION.
Referenced by ns3::UdpSocketImpl::DoSendTo(), ns3::aodv::RoutingTableEntry::GetOutputDevice(), ns3::dsdv::RoutingTableEntry::GetOutputDevice(), ns3::aodv::RoutingProtocol::RouteOutput(), ns3::dsdv::RoutingProtocol::RouteOutput(), ns3::Ipv4NixVectorRouting::RouteOutput(), ns3::olsr::RoutingProtocol::RouteOutput(), ns3::aodv::RoutingProtocol::SendPacketFromQueue(), ns3::dsdv::RoutingProtocol::SendPacketFromQueue(), and ns3::Ipv4L3Protocol::SendRealOut().
GetSource()
Ipv4Address ns3::Ipv4Route::GetSource (void) const
Returns
Source Ipv4Address of the route
Definition at line 56 of file ipv4-route.cc.
References m_source, and NS_LOG_FUNCTION.
Referenced by ns3::UdpSocketImpl::DoSendTo(), ns3::aodv::RoutingProtocol::Forwarding(), ns3::dsdv::RoutingProtocol::LookForQueuedPackets(), ns3::aodv::RoutingProtocol::LoopbackRoute(), ns3::dsdv::RoutingProtocol::LoopbackRoute(), ns3::operator<<(), ns3::aodv::RoutingProtocol::RouteOutput(), ns3::dsdv::RoutingProtocol::RouteOutput(), ns3::olsr::RoutingProtocol::RouteOutput(), ns3::dsdv::RoutingProtocol::Send(), ns3::Icmpv4L4Protocol::SendMessage(), ns3::aodv::RoutingProtocol::SendPacketFromQueue(), ns3::dsdv::RoutingProtocol::SendPacketFromQueue(), ns3::Ipv4RawSocketImpl::SendTo(), and ns3::TcpSocketBase::SetupEndpoint().
SetDestination()
void ns3::Ipv4Route::SetDestination (Ipv4Address dest)
Parameters
dest Destination Ipv4Address
Definition at line 35 of file ipv4-route.cc.
References m_dest, and NS_LOG_FUNCTION.
Referenced by ns3::aodv::RoutingTableEntry::RoutingTableEntry(), ns3::dsdv::RoutingTableEntry::RoutingTableEntry(), ns3::Ipv4L3Protocol::IpMulticastForward(), ns3::Rip::Lookup(), ns3::Ipv4GlobalRouting::LookupGlobal(), ns3::Ipv4StaticRouting::LookupStatic(), ns3::aodv::RoutingProtocol::LoopbackRoute(), ns3::dsdv::RoutingProtocol::LoopbackRoute(), ns3::Ipv4NixVectorRouting::RouteInput(), ns3::olsr::RoutingProtocol::RouteInput(), ns3::Ipv4NixVectorRouting::RouteOutput(), ns3::olsr::RoutingProtocol::RouteOutput(), ns3::Ipv4L3Protocol::Send(), ns3::Ipv4RawSocketImpl::SendTo(), ns3::dsr::DsrOptions::SetRoute(), and ns3::dsr::DsrRouting::SetRoute().
SetGateway()
void ns3::Ipv4Route::SetGateway (Ipv4Address gw)
Parameters
gw Gateway (next hop) Ipv4Address
Definition at line 63 of file ipv4-route.cc.
References m_gateway, and NS_LOG_FUNCTION.
Referenced by ns3::aodv::RoutingTableEntry::RoutingTableEntry(), ns3::dsdv::RoutingTableEntry::RoutingTableEntry(), ns3::Ipv4L3Protocol::IpMulticastForward(), ns3::Rip::Lookup(), ns3::Ipv4GlobalRouting::LookupGlobal(), ns3::Ipv4StaticRouting::LookupStatic(), ns3::aodv::RoutingProtocol::LoopbackRoute(), ns3::dsdv::RoutingProtocol::LoopbackRoute(), ns3::Ipv4NixVectorRouting::RouteInput(), ns3::olsr::RoutingProtocol::RouteInput(), ns3::Ipv4NixVectorRouting::RouteOutput(), ns3::olsr::RoutingProtocol::RouteOutput(), ns3::Ipv4L3Protocol::Send(), ns3::aodv::RoutingTableEntry::SetNextHop(), ns3::dsdv::RoutingTableEntry::SetNextHop(), ns3::dsr::DsrOptions::SetRoute(), and ns3::dsr::DsrRouting::SetRoute().
SetOutputDevice()
void ns3::Ipv4Route::SetOutputDevice (Ptr< NetDevice > outputDevice)
Equivalent in Linux to dst_entry.dev.
Parameters
outputDevice pointer to NetDevice for outgoing packets
Definition at line 77 of file ipv4-route.cc.
References m_outputDevice, and NS_LOG_FUNCTION.
Referenced by ns3::aodv::RoutingTableEntry::RoutingTableEntry(), ns3::dsdv::RoutingTableEntry::RoutingTableEntry(), ns3::dsr::DsrRouting::CheckSendBuffer(), ns3::dsr::DsrRouting::ForwardErrPacket(), ns3::Ipv4L3Protocol::IpMulticastForward(), ns3::Rip::Lookup(), ns3::Ipv4GlobalRouting::LookupGlobal(), ns3::Ipv4StaticRouting::LookupStatic(), ns3::aodv::RoutingProtocol::LoopbackRoute(), ns3::dsdv::RoutingProtocol::LoopbackRoute(), ns3::dsr::DsrRouting::Receive(), ns3::Ipv4NixVectorRouting::RouteInput(), ns3::olsr::RoutingProtocol::RouteInput(), ns3::Ipv4NixVectorRouting::RouteOutput(), ns3::olsr::RoutingProtocol::RouteOutput(), ns3::dsr::DsrRouting::SalvagePacket(), ns3::Ipv4L3Protocol::Send(), ns3::dsr::DsrRouting::SendPacket(), ns3::dsr::DsrRouting::SendPacketFromBuffer(), ns3::dsr::DsrRouting::SendReply(), ns3::Ipv4RawSocketImpl::SendTo(), ns3::dsr::DsrRouting::SendUnreachError(), ns3::aodv::RoutingTableEntry::SetOutputDevice(), and ns3::dsdv::RoutingTableEntry::SetOutputDevice().
SetSource()
void ns3::Ipv4Route::SetSource (Ipv4Address src)
Parameters
src Source Ipv4Address
Definition at line 49 of file ipv4-route.cc.
References m_source, and NS_LOG_FUNCTION.
Referenced by ns3::aodv::RoutingTableEntry::RoutingTableEntry(), ns3::dsdv::RoutingTableEntry::RoutingTableEntry(), ns3::Ipv4L3Protocol::IpMulticastForward(), ns3::Rip::Lookup(), ns3::Ipv4GlobalRouting::LookupGlobal(), ns3::Ipv4StaticRouting::LookupStatic(), ns3::aodv::RoutingProtocol::LoopbackRoute(), ns3::dsdv::RoutingProtocol::LoopbackRoute(), ns3::Ipv4NixVectorRouting::RouteInput(), ns3::olsr::RoutingProtocol::RouteInput(), ns3::Ipv4NixVectorRouting::RouteOutput(), ns3::olsr::RoutingProtocol::RouteOutput(), ns3::Ipv4L3Protocol::Send(), ns3::Ipv4RawSocketImpl::SendTo(), ns3::dsr::DsrOptions::SetRoute(), and ns3::dsr::DsrRouting::SetRoute().
Member Data Documentation
m_dest
Ipv4Address ns3::Ipv4Route::m_dest private
Destination address.
Definition at line 91 of file ipv4-route.h.
Referenced by GetDestination(), and SetDestination().
m_gateway
Ipv4Address ns3::Ipv4Route::m_gateway private
Gateway address.
Definition at line 93 of file ipv4-route.h.
Referenced by GetGateway(), and SetGateway().
m_outputDevice
Ptr<NetDevice> ns3::Ipv4Route::m_outputDevice private
Output device.
Definition at line 94 of file ipv4-route.h.
Referenced by GetOutputDevice(), and SetOutputDevice().
m_source
Ipv4Address ns3::Ipv4Route::m_source private
Source address.
Definition at line 92 of file ipv4-route.h.
Referenced by GetSource(), and SetSource().
The documentation for this class was generated from the following files:
src/internet/model/ipv4-route.h
src/internet/model/ipv4-route.cc