ns-3: ns3::Wifi80211pHelper Class Reference
ns3::Wifi80211pHelper Class Reference
WAVE module
helps to create wifi 802.11p objects of WifiNetDevice class
#include "wifi-80211p-helper.h"
Public Member Functions
Wifi80211pHelper ()
virtual ~Wifi80211pHelper ()
virtual NetDeviceContainer Install (const WifiPhyHelper &phy, const WifiMacHelper &macHelper, NodeContainer c) const
virtual void SetStandard (enum WifiStandard standard)
virtual NS_DEPRECATED_3_32 void SetStandard (WifiPhyStandard standard)
Public Member Functions inherited from ns3::WifiHelper
WifiHelper ()
Create a Wifi helper in an empty state: all its parameters must be set before calling ns3::WifiHelper::Install.
virtual ~WifiHelper ()
int64_t AssignStreams (NetDeviceContainer c, int64_t stream)
Assign a fixed random variable stream number to the random variables used by the PHY and MAC aspects of the Wifi models.
virtual NetDeviceContainer Install (const WifiPhyHelper &phy, const WifiMacHelper &mac, NodeContainer::Iterator first, NodeContainer::Iterator last) const
virtual NetDeviceContainer Install (const WifiPhyHelper &phy, const WifiMacHelper &mac, Ptr< Node > node) const
virtual NetDeviceContainer Install (const WifiPhyHelper &phy, const WifiMacHelper &mac, std::string nodeName) const
void SetAckPolicySelectorForAc (AcIndex ac, std::string type, std::string n0="", const AttributeValue &v0=EmptyAttributeValue(), std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue(), std::string n6="", const AttributeValue &v6=EmptyAttributeValue(), std::string n7="", const AttributeValue &v7=EmptyAttributeValue())
void SetObssPdAlgorithm (std::string type, std::string n0="", const AttributeValue &v0=EmptyAttributeValue(), std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue(), std::string n6="", const AttributeValue &v6=EmptyAttributeValue(), std::string n7="", const AttributeValue &v7=EmptyAttributeValue())
void SetRemoteStationManager (std::string type, std::string n0="", const AttributeValue &v0=EmptyAttributeValue(), std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue(), std::string n6="", const AttributeValue &v6=EmptyAttributeValue(), std::string n7="", const AttributeValue &v7=EmptyAttributeValue())
void SetSelectQueueCallback (SelectQueueCallback f)
Static Public Member Functions
static Wifi80211pHelper Default (void)
static void EnableLogComponents (void)
Helper to enable all WifiNetDevice log components with one statement.
Static Public Member Functions inherited from ns3::WifiHelper
static void EnableLogComponents (void)
Helper to enable all WifiNetDevice log components with one statement.
Additional Inherited Members
Public Types inherited from ns3::WifiHelper
typedef std::function< std::size_t(Ptr< QueueItem >)> SelectQueueCallback
Callback invoked to determine the MAC queue selected for a given packet.
Protected Attributes inherited from ns3::WifiHelper
ObjectFactory m_ackPolicySelector [4]
ack policy selector for all ACs
ObjectFactory m_obssPdAlgorithm
OBSS_PD algorithm.
SelectQueueCallback m_selectQueueCallback
select queue callback
WifiStandard m_standard
wifi standard
ObjectFactory m_stationManager
station manager
Detailed Description
helps to create wifi 802.11p objects of WifiNetDevice class
This class can help to create a large set of similar wifi 802.11p objects and to configure a large set of their attributes during creation.
Definition at line 40 of file wifi-80211p-helper.h.
Constructor & Destructor Documentation
Wifi80211pHelper()
ns3::Wifi80211pHelper::Wifi80211pHelper ()
Definition at line 33 of file wifi-80211p-helper.cc.
~Wifi80211pHelper()
ns3::Wifi80211pHelper::~Wifi80211pHelper () virtual
Definition at line 37 of file wifi-80211p-helper.cc.
Member Function Documentation
Default()
Wifi80211pHelper ns3::Wifi80211pHelper::Default (void) static
Returns
a new Wifi80211pHelper in a default state
The default state is defined as being an OcbWifiMac MAC layer with constant rate OfdmRate6MbpsBW10MHz and both objects using their default attribute values.
Definition at line 42 of file wifi-80211p-helper.cc.
References ns3::WifiHelper::SetRemoteStationManager(), SetStandard(), and ns3::WIFI_STANDARD_80211p.
EnableLogComponents()
void ns3::Wifi80211pHelper::EnableLogComponents (void) static
Helper to enable all WifiNetDevice log components with one statement.
Definition at line 81 of file wifi-80211p-helper.cc.
References ns3::WifiHelper::EnableLogComponents(), ns3::LOG_LEVEL_ALL, and ns3::LogComponentEnable().
Referenced by VanetRoutingExperiment::SetupAdhocDevices().
Install()
NetDeviceContainer ns3::Wifi80211pHelper::Install (const WifiPhyHelper & phy, const WifiMacHelper & macHelper, NodeContainer c) const virtual
Parameters
phy the PHY helper to create PHY objects
macHelper the MAC helper to create MAC objects
c the set of nodes on which a wifi device must be created
Returns
a device container which contains all the devices created by this method.
Reimplemented from ns3::WifiHelper.
Definition at line 90 of file wifi-80211p-helper.cc.
References ns3::WifiHelper::Install(), NS_FATAL_ERROR, and NS_UNUSED.
Referenced by OcbWifiMacTestCase::ConfigureOcbMode(), and VanetRoutingExperiment::SetupAdhocDevices().
SetStandard() [1/2]
void ns3::Wifi80211pHelper::SetStandard (enum WifiStandard standard) virtual
Parameters
standard the phy standard to configure during installation
Users can only configure 802.11p with 10MHz or 5 MHz channel bandwidth. The default 802.11p standard uses 10MHz.
Reimplemented from ns3::WifiHelper.
Definition at line 54 of file wifi-80211p-helper.cc.
References NS_FATAL_ERROR, ns3::WifiHelper::SetStandard(), and ns3::WIFI_STANDARD_80211p.
Referenced by Default().
SetStandard() [2/2]
void ns3::Wifi80211pHelper::SetStandard (WifiPhyStandard standard) virtual
Parameters
standard the phy standard to configure during installation
Users can only configure 802.11p with 10MHz or 5 MHz channel bandwidth. The default 802.11p standard uses 10MHz.
Deprecated:
This method will go away in a future release of ns-3.
Reimplemented from ns3::WifiHelper.
Definition at line 68 of file wifi-80211p-helper.cc.
References NS_FATAL_ERROR, ns3::WifiHelper::SetStandard(), ns3::WIFI_PHY_STANDARD_80211_10MHZ, ns3::WIFI_PHY_STANDARD_80211a, and ns3::WIFI_STANDARD_80211p.
The documentation for this class was generated from the following files:
src/wave/helper/wifi-80211p-helper.h
src/wave/helper/wifi-80211p-helper.cc