ns-3: ns3::MsduAggregator Class Reference
ns3::MsduAggregator Class Reference
Wifi Models
Aggregator used to construct A-MSDUs.
#include "msdu-aggregator.h"
Public Types
typedef std::list< std::pair< Ptr< const Packet >, AmsduSubframeHeader > > DeaggregatedMsdus
DeaggregatedMsdus typedef.
typedef std::list< std::pair< Ptr< const Packet >, AmsduSubframeHeader > >::const_iterator DeaggregatedMsdusCI
DeaggregatedMsdusCI typedef.
typedef std::map< AcIndex, Ptr< QosTxop > > EdcaQueues
EDCA queues typedef.
Public Member Functions
MsduAggregator ()
virtual ~MsduAggregator ()
uint16_t GetMaxAmsduSize (Mac48Address recipient, uint8_t tid, WifiModulationClass modulation) const
Determine the maximum size for an A-MSDU of the given TID that can be sent to the given receiver when using the given modulation class.
Ptr< WifiMacQueueItem > GetNextAmsdu (Mac48Address recipient, uint8_t tid, WifiTxVector txVector, uint32_t ampduSize=0, Time ppduDurationLimit=Time::Min()) const
Dequeue MSDUs to be transmitted to a given station and belonging to a given TID from the corresponding EDCA queue and aggregate them to form an A-MSDU that meets the following constraints:
void SetEdcaQueues (EdcaQueues map)
Set the map of EDCA queues.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static uint8_t CalculatePadding (uint16_t amsduSize)
Calculate how much padding must be added to the end of an A-MSDU of the given size if a new MSDU is added.
static DeaggregatedMsdus Deaggregate (Ptr< Packet > aggregatedPacket)
static uint16_t GetSizeIfAggregated (uint16_t msduSize, uint16_t amsduSize)
Compute the size of the A-MSDU resulting from the aggregation of an MSDU of size msduSize and an A-MSDU of size amsduSize.
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
EdcaQueues m_edca
the map of EDCA queues
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Aggregator used to construct A-MSDUs.
Introspection did not find any typical Config paths.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 56 bytes (on a 64-bit architecture).
Definition at line 42 of file msdu-aggregator.h.
Member Typedef Documentation
DeaggregatedMsdus
typedef std::list<std::pair<Ptr<const Packet>, AmsduSubframeHeader> > ns3::MsduAggregator::DeaggregatedMsdus
DeaggregatedMsdus typedef.
Definition at line 46 of file msdu-aggregator.h.
DeaggregatedMsdusCI
typedef std::list<std::pair<Ptr<const Packet>, AmsduSubframeHeader> >::const_iterator ns3::MsduAggregator::DeaggregatedMsdusCI
DeaggregatedMsdusCI typedef.
Definition at line 48 of file msdu-aggregator.h.
EdcaQueues
typedef std::map<AcIndex, Ptr<QosTxop> > ns3::MsduAggregator::EdcaQueues
EDCA queues typedef.
Definition at line 50 of file msdu-aggregator.h.
Constructor & Destructor Documentation
MsduAggregator()
ns3::MsduAggregator::MsduAggregator ()
Definition at line 55 of file msdu-aggregator.cc.
~MsduAggregator()
ns3::MsduAggregator::~MsduAggregator () virtual
Definition at line 59 of file msdu-aggregator.cc.
Member Function Documentation
CalculatePadding()
uint8_t ns3::MsduAggregator::CalculatePadding (uint16_t amsduSize) static
Calculate how much padding must be added to the end of an A-MSDU of the given size if a new MSDU is added.
Each A-MSDU subframe is padded so that its length is multiple of 4 octets.
Parameters
amsduSize the size of the A-MSDU
Returns
the number of octets required for padding
Definition at line 181 of file msdu-aggregator.cc.
Referenced by ns3::WifiMacQueueItem::DoAggregate(), and GetSizeIfAggregated().
Deaggregate()
MsduAggregator::DeaggregatedMsdus ns3::MsduAggregator::Deaggregate (Ptr< Packet > aggregatedPacket) static
Parameters
aggregatedPacket the aggregated packet.
Returns
DeaggregatedMsdus.
Definition at line 275 of file msdu-aggregator.cc.
References ns3::Packet::CreateFragment(), ns3::AmsduSubframeHeader::GetLength(), ns3::Packet::GetSize(), NS_LOG_FUNCTION_NOARGS, NS_LOG_INFO, ns3::Packet::RemoveAtStart(), and ns3::Packet::RemoveHeader().
Referenced by ns3::WifiMacQueueItem::WifiMacQueueItem().
GetMaxAmsduSize()
uint16_t ns3::MsduAggregator::GetMaxAmsduSize (Mac48Address recipient, uint8_t tid, WifiModulationClass modulation) const
Determine the maximum size for an A-MSDU of the given TID that can be sent to the given receiver when using the given modulation class.
Parameters
recipient the receiver station address.
tid the TID.
modulation the modulation class.
Returns
the maximum A-MSDU size in bytes.
Definition at line 187 of file msdu-aggregator.cc.
References ns3::AC_BE, ns3::AC_BK, ns3::AC_VI, ns3::AC_VO, ns3::UintegerValue::Get(), ns3::Txop::GetLow(), ns3::WifiNetDevice::GetMac(), ns3::WifiNetDevice::GetRemoteStationManager(), ns3::WifiRemoteStationManager::GetStationHtCapabilities(), ns3::WifiRemoteStationManager::GetStationVhtCapabilities(), m_edca, min, NS_ABORT_MSG, NS_ABORT_MSG_IF, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::QosUtilsMapTidToAc(), ns3::WIFI_MOD_CLASS_HT, and ns3::WIFI_MOD_CLASS_VHT.
Referenced by GetNextAmsdu().
GetNextAmsdu()
Ptr< WifiMacQueueItem > ns3::MsduAggregator::GetNextAmsdu (Mac48Address recipient, uint8_t tid, WifiTxVector txVector, uint32_t ampduSize = 0, Time ppduDurationLimit = Time::Min ()) const
Dequeue MSDUs to be transmitted to a given station and belonging to a given TID from the corresponding EDCA queue and aggregate them to form an A-MSDU that meets the following constraints:
the A-MSDU size does not exceed the maximum A-MSDU size as determined for the modulation class indicated by the given TxVector
the size of the A-MPDU resulting from the aggregation of the MPDU in which the A-MSDU will be embedded and an existing A-MPDU of the given size (possibly null) does not exceed the maximum A-MPDU size as determined for the modulation class indicated by the given TxVector
the time to transmit the resulting PPDU, according to the given TxVector, does not exceed both the maximum PPDU duration allowed by the corresponding modulation class (if any) and the given PPDU duration limit (if distinct from Time::Min ())
If it is not possible to aggregate at least two MSDUs, no MSDU is dequeued from the EDCA queue and a null pointer is returned.
Parameters
recipient the receiver station address.
tid the TID.
txVector the TxVector used to transmit the frame
ampduSize the size of the existing A-MPDU in bytes
ppduDurationLimit the limit on the PPDU duration
Returns
the resulting A-MSDU, if aggregation is possible, 0 otherwise.
Definition at line 79 of file msdu-aggregator.cc.
References ns3::Copy(), ns3::Txop::GetLow(), GetMaxAmsduSize(), ns3::WifiTxVector::GetMode(), ns3::WifiMode::GetModulationClass(), GetSizeIfAggregated(), ns3::Txop::GetWifiMacQueue(), ns3::Mac48Address::IsGroup(), m_edca, NS_ABORT_MSG_IF, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::QosUtilsMapTidToAc(), and ns3::WIFI_MAC_FCS_LENGTH.
GetSizeIfAggregated()
uint16_t ns3::MsduAggregator::GetSizeIfAggregated (uint16_t msduSize, uint16_t amsduSize) static
Compute the size of the A-MSDU resulting from the aggregation of an MSDU of size msduSize and an A-MSDU of size amsduSize.
Note that only the basic A-MSDU subframe format (section 9.3.2.2.2 of IEEE 802.11-2016) is supported.
Parameters
msduSize the MSDU size in bytes.
amsduSize the A-MSDU size in bytes.
Returns
the size of the resulting A-MSDU in bytes.
Definition at line 70 of file msdu-aggregator.cc.
References CalculatePadding(), and NS_LOG_FUNCTION.
Referenced by GetNextAmsdu().
GetTypeId()
TypeId ns3::MsduAggregator::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 45 of file msdu-aggregator.cc.
References ns3::TypeId::SetParent().
SetEdcaQueues()
void ns3::MsduAggregator::SetEdcaQueues (EdcaQueues map)
Set the map of EDCA queues.
Parameters
map the map of EDCA queues.
Definition at line 64 of file msdu-aggregator.cc.
References m_edca.
Member Data Documentation
m_edca
EdcaQueues ns3::MsduAggregator::m_edca private
the map of EDCA queues
Definition at line 143 of file msdu-aggregator.h.
Referenced by GetMaxAmsduSize(), GetNextAmsdu(), and SetEdcaQueues().
The documentation for this class was generated from the following files:
src/wifi/model/msdu-aggregator.h
src/wifi/model/msdu-aggregator.cc