ns-3: ns3::WifiPsdu Class Reference
ns3::WifiPsdu Class Reference
Wifi Models
WifiPsdu stores an MPDU, S-MPDU or A-MPDU, by keeping header(s) and payload(s) separate for each constituent MPDU.
#include "wifi-psdu.h"
Public Member Functions
WifiPsdu (Ptr< const Packet > p, const WifiMacHeader &header)
Create a PSDU storing an MPDU.
WifiPsdu (Ptr< const WifiMacQueueItem > mpdu, bool isSingle)
Create a PSDU storing an MPDU or S-MPDU.
WifiPsdu (Ptr< WifiMacQueueItem > mpdu, bool isSingle)
Create a PSDU storing an MPDU or S-MPDU.
WifiPsdu (std::vector< Ptr< WifiMacQueueItem >> mpduList)
Create a PSDU storing an S-MPDU or A-MPDU.
virtual ~WifiPsdu ()
std::vector< Ptr< WifiMacQueueItem > >::iterator begin (void)
Return an iterator to the first MPDU.
std::vector< Ptr< WifiMacQueueItem > >::const_iterator begin (void) const
Return a const iterator to the first MPDU.
std::vector< Ptr< WifiMacQueueItem > >::iterator end (void)
Return an iterator to past-the-last MPDU.
std::vector< Ptr< WifiMacQueueItem > >::const_iterator end (void) const
Return a const iterator to past-the-last MPDU.
WifiMacHeader::QosAckPolicy GetAckPolicyForTid (uint8_t tid) const
Get the QoS Ack Policy of the QoS Data frames included in the PSDU that have the given TID.
Mac48Address GetAddr1 (void) const
Get the Receiver Address (RA), which is common to all the MPDUs.
Mac48Address GetAddr2 (void) const
Get the Transmitter Address (TA), which is common to all the MPDUs.
Ptr< Packet > GetAmpduSubframe (std::size_t i) const
Get a copy of the i-th A-MPDU subframe (includes subframe header, MPDU, and possibly padding)
std::size_t GetAmpduSubframeSize (std::size_t i) const
Return the size of the i-th A-MPDU subframe.
Time GetDuration (void) const
Get the duration from the Duration/ID field, which is common to all the MPDUs.
WifiMacHeader & GetHeader (std::size_t i)
Get the header of the i-th MPDU.
const WifiMacHeader & GetHeader (std::size_t i) const
Get the header of the i-th MPDU.
uint16_t GetMaxDistFromStartingSeq (uint16_t startingSeq) const
Get the maximum distance between the sequence number of any QoS Data frame included in this PSDU that is not an old frame and the given starting sequence number.
std::size_t GetNMpdus (void) const
Return the number of MPDUs constituting the PSDU.
Ptr< const Packet > GetPacket (void) const
Get the PSDU as a single packet.
Ptr< const Packet > GetPayload (std::size_t i) const
Get the payload of the i-th MPDU.
uint32_t GetSize (void) const
Return the size of the PSDU in bytes.
std::set< uint8_t > GetTids (void) const
Get the set of TIDs of the QoS Data frames included in the PSDU.
Time GetTimeStamp (std::size_t i) const
Get the timestamp of the i-th MPDU.
bool IsAggregate (void) const
Return true if the PSDU is an S-MPDU or A-MPDU.
bool IsSingle (void) const
Return true if the PSDU is an S-MPDU.
void Print (std::ostream &os) const
Print the PSDU contents.
void SetAckPolicyForTid (uint8_t tid, WifiMacHeader::QosAckPolicy policy)
Set the QoS Ack Policy of the QoS Data frames included in the PSDU that have the given TID to the given policy.
void SetDuration (Time duration)
Set the Duration/ID field on all the MPDUs.
Public Member Functions inherited from ns3::SimpleRefCount< WifiPsdu >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
bool m_isSingle
true for an S-MPDU
std::vector< Ptr< WifiMacQueueItem > > m_mpduList
list of constituent MPDUs
uint32_t m_size
the size of the PSDU in bytes
Detailed Description
WifiPsdu stores an MPDU, S-MPDU or A-MPDU, by keeping header(s) and payload(s) separate for each constituent MPDU.
Definition at line 40 of file wifi-psdu.h.
Constructor & Destructor Documentation
WifiPsdu() [1/4]
ns3::WifiPsdu::WifiPsdu (Ptr< const Packet > p, const WifiMacHeader & header)
Create a PSDU storing an MPDU.
Typically used for control and management frames that do not have to keep an associated lifetime and are not stored in an S-MPDU.
Parameters
p the payload of the MPDU.
header the Wifi MAC header of the MPDU.
Definition at line 33 of file wifi-psdu.cc.
References ns3::WifiMacHeader::GetSerializedSize(), m_mpduList, m_size, and ns3::WIFI_MAC_FCS_LENGTH.
WifiPsdu() [2/4]
ns3::WifiPsdu::WifiPsdu (Ptr< WifiMacQueueItem > mpdu, bool isSingle)
Create a PSDU storing an MPDU or S-MPDU.
Typically used for QoS data frames that have to keep an associated lifetime.
Parameters
mpdu the MPDU.
isSingle true for an S-MPDU
Definition at line 40 of file wifi-psdu.cc.
References m_mpduList, and m_size.
WifiPsdu() [3/4]
ns3::WifiPsdu::WifiPsdu (Ptr< const WifiMacQueueItem > mpdu, bool isSingle)
Create a PSDU storing an MPDU or S-MPDU.
Typically used for QoS data frames that have to keep an associated lifetime.
Parameters
mpdu the MPDU.
isSingle true for an S-MPDU
WifiPsdu() [4/4]
ns3::WifiPsdu::WifiPsdu (std::vector< Ptr< WifiMacQueueItem >> mpduList)
Create a PSDU storing an S-MPDU or A-MPDU.
Parameters
mpduList the list of constituent MPDUs.
Definition at line 57 of file wifi-psdu.cc.
References ns3::MpduAggregator::GetSizeIfAggregated(), m_mpduList, m_size, and NS_ABORT_MSG_IF.
~WifiPsdu()
ns3::WifiPsdu::~WifiPsdu () virtual
Definition at line 70 of file wifi-psdu.cc.
Member Function Documentation
begin() [1/2]
std::vector< Ptr< WifiMacQueueItem > >::iterator ns3::WifiPsdu::begin (void)
Return an iterator to the first MPDU.
Returns
an iterator to the first MPDU.
Definition at line 331 of file wifi-psdu.cc.
References m_mpduList.
begin() [2/2]
std::vector< Ptr< WifiMacQueueItem > >::const_iterator ns3::WifiPsdu::begin (void) const
Return a const iterator to the first MPDU.
Returns
a const iterator to the first MPDU.
Definition at line 325 of file wifi-psdu.cc.
References m_mpduList.
Referenced by ns3::MacLow::ForwardDown(), and ns3::WifiPhy::ScheduleEndOfMpdus().
end() [1/2]
std::vector< Ptr< WifiMacQueueItem > >::iterator ns3::WifiPsdu::end (void)
Return an iterator to past-the-last MPDU.
Returns
an iterator to past-the-last MPDU.
Definition at line 343 of file wifi-psdu.cc.
References m_mpduList.
Referenced by grid.TimelinesRenderer::draw_events(), and grid.TimelinesRenderer::draw_ranges().
end() [2/2]
std::vector< Ptr< WifiMacQueueItem > >::const_iterator ns3::WifiPsdu::end (void) const
Return a const iterator to past-the-last MPDU.
Returns
a const iterator to past-the-last MPDU.
Definition at line 337 of file wifi-psdu.cc.
References m_mpduList.
Referenced by grid.TimelinesRenderer::draw_events(), grid.TimelinesRenderer::draw_ranges(), and ns3::WifiPhy::ScheduleEndOfMpdus().
GetAckPolicyForTid()
WifiMacHeader::QosAckPolicy ns3::WifiPsdu::GetAckPolicyForTid (uint8_t tid) const
Get the QoS Ack Policy of the QoS Data frames included in the PSDU that have the given TID.
Also, check that all the QoS Data frames having the given TID have the same QoS Ack Policy. Do not call this method if there is no QoS Date frame in the PSDU.
Parameters
tid the given TID
Returns
the QoS Ack Policy common to all QoS Data frames having the given TID.
Definition at line 180 of file wifi-psdu.cc.
References m_mpduList, NS_ABORT_MSG, NS_ABORT_MSG_IF, and NS_LOG_FUNCTION.
GetAddr1()
Mac48Address ns3::WifiPsdu::GetAddr1 (void) const
Get the Receiver Address (RA), which is common to all the MPDUs.
Returns
the Receiver Address.
Definition at line 111 of file wifi-psdu.cc.
References m_mpduList, and NS_ABORT_MSG.
GetAddr2()
Mac48Address ns3::WifiPsdu::GetAddr2 (void) const
Get the Transmitter Address (TA), which is common to all the MPDUs.
Returns
the Transmitter Address.
Definition at line 126 of file wifi-psdu.cc.
References m_mpduList, and NS_ABORT_MSG.
GetAmpduSubframe()
Ptr< Packet > ns3::WifiPsdu::GetAmpduSubframe (std::size_t i) const
Get a copy of the i-th A-MPDU subframe (includes subframe header, MPDU, and possibly padding)
Returns
the i-th A-MPDU subframe.
Definition at line 290 of file wifi-psdu.cc.
References ns3::Packet::AddAtEnd(), ns3::Packet::AddHeader(), ns3::MpduAggregator::GetAmpduSubframeHeader(), GetAmpduSubframeSize(), ns3::Packet::GetSize(), m_isSingle, m_mpduList, and NS_ASSERT.
Referenced by ns3::WifiPhy::NotifyMonitorSniffRx(), and ns3::WifiPhy::NotifyMonitorSniffTx().
GetAmpduSubframeSize()
std::size_t ns3::WifiPsdu::GetAmpduSubframeSize (std::size_t i) const
Return the size of the i-th A-MPDU subframe.
Returns
the size of the i-th A-MPDU subframe.
Definition at line 306 of file wifi-psdu.cc.
References ns3::MpduAggregator::CalculatePadding(), m_mpduList, and NS_ASSERT.
Referenced by GetAmpduSubframe(), and ns3::WifiPhy::ScheduleEndOfMpdus().
GetDuration()
Time ns3::WifiPsdu::GetDuration (void) const
Get the duration from the Duration/ID field, which is common to all the MPDUs.
Returns
the duration from the Duration/ID field.
Definition at line 141 of file wifi-psdu.cc.
References m_mpduList, and NS_ABORT_MSG.
GetHeader() [1/2]
WifiMacHeader & ns3::WifiPsdu::GetHeader (std::size_t i)
Get the header of the i-th MPDU.
Parameters
i index in the list of MPDUs
Returns
the header of the i-th MPDU.
Definition at line 272 of file wifi-psdu.cc.
References m_mpduList.
GetHeader() [2/2]
const WifiMacHeader & ns3::WifiPsdu::GetHeader (std::size_t i) const
Get the header of the i-th MPDU.
Parameters
i index in the list of MPDUs
Returns
the header of the i-th MPDU.
Definition at line 266 of file wifi-psdu.cc.
References m_mpduList.
GetMaxDistFromStartingSeq()
uint16_t ns3::WifiPsdu::GetMaxDistFromStartingSeq (uint16_t startingSeq) const
Get the maximum distance between the sequence number of any QoS Data frame included in this PSDU that is not an old frame and the given starting sequence number.
If this PSDU does not contain any QoS Data frame that is not an old frame, an invalid distance (4096) is returned.
Parameters
startingSeq the given starting sequence number.
Returns
the maximum distance between the sequence numbers included in the PSDU and the given starting sequence number
Definition at line 227 of file wifi-psdu.cc.
References m_mpduList, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::QosUtilsIsOldPacket(), and ns3::SEQNO_SPACE_SIZE.
GetNMpdus()
std::size_t ns3::WifiPsdu::GetNMpdus (void) const
Return the number of MPDUs constituting the PSDU.
Returns
the number of MPDUs constituting the PSDU.
Definition at line 319 of file wifi-psdu.cc.
References m_mpduList.
Referenced by ns3::WifiPhy::EndReceive(), ns3::MacLow::ForwardDown(), ns3::WifiPhy::NotifyMonitorSniffRx(), ns3::WifiPhy::NotifyMonitorSniffTx(), Print(), ns3::WifiPhy::ScheduleEndOfMpdus(), and ns3::WifiPhy::StartReceivePayload().
GetPacket()
Ptr< const Packet > ns3::WifiPsdu::GetPacket (void) const
Get the PSDU as a single packet.
Returns
the PSDU.
Definition at line 87 of file wifi-psdu.cc.
References ns3::Packet::AddHeader(), ns3::AddWifiMacTrailer(), ns3::MpduAggregator::Aggregate(), m_isSingle, and m_mpduList.
Referenced by ns3::WifiPhy::GetReceptionStatus(), ns3::WifiPhy::NotifyMonitorSniffRx(), and ns3::WifiPhy::NotifyMonitorSniffTx().
GetPayload()
Ptr< const Packet > ns3::WifiPsdu::GetPayload (std::size_t i) const
Get the payload of the i-th MPDU.
Parameters
i index in the list of MPDUs
Returns
the payload of the i-th MPDU.
Definition at line 278 of file wifi-psdu.cc.
References m_mpduList.
GetSize()
uint32_t ns3::WifiPsdu::GetSize (void) const
Return the size of the PSDU in bytes.
Returns
the size of the PSDU.
Definition at line 260 of file wifi-psdu.cc.
References m_size.
Referenced by ns3::MacLow::ForwardDown(), and ns3::WifiPhy::GetReceptionStatus().
GetTids()
std::set< uint8_t > ns3::WifiPsdu::GetTids (void) const
Get the set of TIDs of the QoS Data frames included in the PSDU.
Note that only single-TID A-MPDUs are currently supported, hence the returned set contains at most one TID value.
Returns
the set of TIDs of the QoS Data frames included in the PSDU.
Definition at line 166 of file wifi-psdu.cc.
References m_mpduList.
GetTimeStamp()
Time ns3::WifiPsdu::GetTimeStamp (std::size_t i) const
Get the timestamp of the i-th MPDU.
Parameters
i index in the list of MPDUs
Returns
the timestamp of the i-th MPDU.
Definition at line 284 of file wifi-psdu.cc.
References m_mpduList.
IsAggregate()
bool ns3::WifiPsdu::IsAggregate (void) const
Return true if the PSDU is an S-MPDU or A-MPDU.
Returns
true if the PSDU is an S-MPDU or A-MPDU.
Definition at line 81 of file wifi-psdu.cc.
References m_isSingle, and m_mpduList.
Referenced by ns3::MacLow::ForwardDown(), ns3::WifiPhy::NotifyMonitorSniffRx(), ns3::WifiPhy::NotifyMonitorSniffTx(), and Print().
IsSingle()
bool ns3::WifiPsdu::IsSingle (void) const
Return true if the PSDU is an S-MPDU.
Returns
true if the PSDU is an S-MPDU.
Definition at line 75 of file wifi-psdu.cc.
References m_isSingle.
Referenced by ns3::MacLow::ForwardDown(), ns3::WifiPhy::NotifyMonitorSniffRx(), and ns3::WifiPhy::NotifyMonitorSniffTx().
Print()
void ns3::WifiPsdu::Print (std::ostream & os) const
Print the PSDU contents.
Parameters
os output stream in which the data should be printed.
Definition at line 349 of file wifi-psdu.cc.
References GetNMpdus(), IsAggregate(), m_isSingle, m_mpduList, and m_size.
Referenced by ns3::operator<<().
SetAckPolicyForTid()
void ns3::WifiPsdu::SetAckPolicyForTid (uint8_t tid, WifiMacHeader::QosAckPolicy policy)
Set the QoS Ack Policy of the QoS Data frames included in the PSDU that have the given TID to the given policy.
Parameters
tid the given TID
policy the given QoS Ack policy
Definition at line 214 of file wifi-psdu.cc.
References m_mpduList, and NS_LOG_FUNCTION.
SetDuration()
void ns3::WifiPsdu::SetDuration (Time duration)
Set the Duration/ID field on all the MPDUs.
Parameters
duration the value for the Duration/ID field.
Definition at line 156 of file wifi-psdu.cc.
References m_mpduList, and NS_LOG_FUNCTION.
Member Data Documentation
m_isSingle
bool ns3::WifiPsdu::m_isSingle private
true for an S-MPDU
Definition at line 253 of file wifi-psdu.h.
Referenced by GetAmpduSubframe(), GetPacket(), IsAggregate(), IsSingle(), and Print().
m_mpduList
std::vector<Ptr<WifiMacQueueItem> > ns3::WifiPsdu::m_mpduList private
list of constituent MPDUs
Definition at line 254 of file wifi-psdu.h.
Referenced by WifiPsdu(), begin(), end(), GetAckPolicyForTid(), GetAddr1(), GetAddr2(), GetAmpduSubframe(), GetAmpduSubframeSize(), GetDuration(), GetHeader(), GetMaxDistFromStartingSeq(), GetNMpdus(), GetPacket(), GetPayload(), GetTids(), GetTimeStamp(), IsAggregate(), Print(), SetAckPolicyForTid(), and SetDuration().
m_size
uint32_t ns3::WifiPsdu::m_size private
the size of the PSDU in bytes
Definition at line 255 of file wifi-psdu.h.
Referenced by WifiPsdu(), GetSize(), and Print().
The documentation for this class was generated from the following files:
src/wifi/model/wifi-psdu.h
src/wifi/model/wifi-psdu.cc