ns-3: ns3::SpectrumInterference Class Reference
ns3::SpectrumInterference Class Reference
Spectrum Models
This class implements a gaussian interference model, i.e., all incoming signals are added to the total interference.
#include "spectrum-interference.h"
Public Member Functions
SpectrumInterference ()
virtual ~SpectrumInterference ()
void AbortRx ()
Notify that the PHY has aborted RX.
void AddSignal (Ptr< const SpectrumValue > spd, const Time duration)
Notify that a new signal is being perceived in the medium.
bool EndRx ()
Notify that the RX attempt has ended.
void SetErrorModel (Ptr< SpectrumErrorModel > e)
Set the SpectrumErrorModel to be used.
void SetNoisePowerSpectralDensity (Ptr< const SpectrumValue > noisePsd)
Set the Noise Power Spectral Density.
void StartRx (Ptr< const Packet > p, Ptr< const SpectrumValue > rxPsd)
Notify that the PHY is starting a RX attempt.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
void DoDispose ()
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void ConditionallyEvaluateChunk ()
Evaluate a Chunk, depending on the Rx status and the last update time.
void DoAddSignal (Ptr< const SpectrumValue > spd)
Adds a signal perceived in the medium.
void DoSubtractSignal (Ptr< const SpectrumValue > spd)
Removes a signal perceived in the medium.
Private Attributes
Ptr< SpectrumValue > m_allSignals
Stores the spectral power density of the sum of incoming signals; does not include noise, includes the SPD of the signal being RX.
Ptr< SpectrumErrorModel > m_errorModel
Error model.
Time m_lastChangeTime
the time of the last change in m_TotalPower
Ptr< const SpectrumValue > m_noise
Noise spectral power density.
bool m_receiving
True if in Rx status.
Ptr< const SpectrumValue > m_rxSignal
Stores the power spectral density of the signal whose RX is being attempted.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class implements a gaussian interference model, i.e., all incoming signals are added to the total interference.
Definition at line 46 of file spectrum-interference.h.
Constructor & Destructor Documentation
SpectrumInterference()
ns3::SpectrumInterference::SpectrumInterference ()
Definition at line 33 of file spectrum-interference.cc.
References NS_LOG_FUNCTION.
~SpectrumInterference()
ns3::SpectrumInterference::~SpectrumInterference () virtual
Definition at line 43 of file spectrum-interference.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AbortRx()
void ns3::SpectrumInterference::AbortRx ()
Notify that the PHY has aborted RX.
Definition at line 81 of file spectrum-interference.cc.
References m_receiving.
Referenced by ns3::HalfDuplexIdealPhy::AbortRx().
AddSignal()
void ns3::SpectrumInterference::AddSignal (Ptr< const SpectrumValue > spd, const Time duration)
Notify that a new signal is being perceived in the medium.
This method is to be called for all incoming signal, regardless of whether they're useful signals or interferers.
Parameters
spd the power spectral density of the new signal
duration the duration of the new signal
Definition at line 97 of file spectrum-interference.cc.
References DoAddSignal(), DoSubtractSignal(), NS_LOG_FUNCTION, and ns3::Simulator::Schedule().
Referenced by ns3::HalfDuplexIdealPhy::StartRx().
ConditionallyEvaluateChunk()
void ns3::SpectrumInterference::ConditionallyEvaluateChunk () private
Evaluate a Chunk, depending on the Rx status and the last update time.
Definition at line 125 of file spectrum-interference.cc.
References m_errorModel, m_lastChangeTime, m_receiving, ns3::Now(), NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by DoAddSignal(), DoSubtractSignal(), and EndRx().
DoAddSignal()
void ns3::SpectrumInterference::DoAddSignal (Ptr< const SpectrumValue > spd) private
Adds a signal perceived in the medium.
Parameters
spd the power spectral density of the new signal
Definition at line 106 of file spectrum-interference.cc.
References ConditionallyEvaluateChunk(), m_lastChangeTime, ns3::Now(), and NS_LOG_FUNCTION.
Referenced by AddSignal().
DoDispose()
void ns3::SpectrumInterference::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 60 of file spectrum-interference.cc.
References ns3::Object::DoDispose(), m_allSignals, m_errorModel, m_noise, m_rxSignal, and NS_LOG_FUNCTION.
DoSubtractSignal()
void ns3::SpectrumInterference::DoSubtractSignal (Ptr< const SpectrumValue > spd) private
Removes a signal perceived in the medium.
Parameters
spd the power spectral density of the new signal
Definition at line 115 of file spectrum-interference.cc.
References ConditionallyEvaluateChunk(), m_lastChangeTime, ns3::Now(), and NS_LOG_FUNCTION.
Referenced by AddSignal().
EndRx()
bool ns3::SpectrumInterference::EndRx ()
Notify that the RX attempt has ended.
The receiving PHY must call this method upon RX end in order to: 1) know if RX was successful or not 2) free up resources that might eventually be used for the calculation of interference. Note that for this reason this method must also be called when RX is aborted.
Returns
true if RX was successful, false otherwise
Definition at line 87 of file spectrum-interference.cc.
References ConditionallyEvaluateChunk(), m_errorModel, m_receiving, and NS_LOG_FUNCTION.
Referenced by ns3::HalfDuplexIdealPhy::EndRx(), and SpectrumInterferenceTestCase::RetrieveTestResult().
GetTypeId()
TypeId ns3::SpectrumInterference::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 49 of file spectrum-interference.cc.
References ns3::TypeId::SetParent().
SetErrorModel()
void ns3::SpectrumInterference::SetErrorModel (Ptr< SpectrumErrorModel > e)
Set the SpectrumErrorModel to be used.
Parameters
e the error model
Definition at line 154 of file spectrum-interference.cc.
References m_errorModel, and NS_LOG_FUNCTION.
Referenced by ns3::HalfDuplexIdealPhy::HalfDuplexIdealPhy(), and SpectrumInterferenceTestCase::DoRun().
SetNoisePowerSpectralDensity()
void ns3::SpectrumInterference::SetNoisePowerSpectralDensity (Ptr< const SpectrumValue > noisePsd)
Set the Noise Power Spectral Density.
Parameters
noisePsd the Noise Power Spectral Density in power units (Watt, Pascal...) per Hz.
Definition at line 142 of file spectrum-interference.cc.
References m_allSignals, m_noise, and NS_LOG_FUNCTION.
Referenced by SpectrumInterferenceTestCase::DoRun(), and ns3::HalfDuplexIdealPhy::SetNoisePowerSpectralDensity().
StartRx()
void ns3::SpectrumInterference::StartRx (Ptr< const Packet > p, Ptr< const SpectrumValue > rxPsd)
Notify that the PHY is starting a RX attempt.
Parameters
p the packet corresponding to the signal being RX
rxPsd the power spectral density of the signal being RX
Definition at line 71 of file spectrum-interference.cc.
References m_errorModel, m_lastChangeTime, m_receiving, m_rxSignal, ns3::Now(), and NS_LOG_FUNCTION.
Referenced by ns3::HalfDuplexIdealPhy::StartRx().
Member Data Documentation
m_allSignals
Ptr<SpectrumValue> ns3::SpectrumInterference::m_allSignals private
Stores the spectral power density of the sum of incoming signals; does not include noise, includes the SPD of the signal being RX.
Definition at line 142 of file spectrum-interference.h.
Referenced by DoDispose(), and SetNoisePowerSpectralDensity().
m_errorModel
Ptr<SpectrumErrorModel> ns3::SpectrumInterference::m_errorModel private
Error model.
Definition at line 148 of file spectrum-interference.h.
Referenced by ConditionallyEvaluateChunk(), DoDispose(), EndRx(), SetErrorModel(), and StartRx().
m_lastChangeTime
Time ns3::SpectrumInterference::m_lastChangeTime private
the time of the last change in m_TotalPower
Definition at line 146 of file spectrum-interference.h.
Referenced by ConditionallyEvaluateChunk(), DoAddSignal(), DoSubtractSignal(), and StartRx().
m_noise
Ptr<const SpectrumValue> ns3::SpectrumInterference::m_noise private
Noise spectral power density.
Definition at line 144 of file spectrum-interference.h.
Referenced by DoDispose(), and SetNoisePowerSpectralDensity().
m_receiving
bool ns3::SpectrumInterference::m_receiving private
True if in Rx status.
Definition at line 131 of file spectrum-interference.h.
Referenced by AbortRx(), ConditionallyEvaluateChunk(), EndRx(), and StartRx().
m_rxSignal
Ptr<const SpectrumValue> ns3::SpectrumInterference::m_rxSignal private
Stores the power spectral density of the signal whose RX is being attempted.
Definition at line 136 of file spectrum-interference.h.
Referenced by DoDispose(), and StartRx().
The documentation for this class was generated from the following files:
src/spectrum/model/spectrum-interference.h
src/spectrum/model/spectrum-interference.cc