ns-3: ns3::SystemWallClockMs Class Reference
ns3::SystemWallClockMs Class Reference
Core » System Services
Measure elapsed wall clock time in milliseconds.
#include "system-wall-clock-ms.h"
Public Member Functions
SystemWallClockMs ()
~SystemWallClockMs ()
int64_t End (void)
Stop measuring the time since Start() was called.
int64_t GetElapsedReal (void) const
int64_t GetElapsedSystem (void) const
int64_t GetElapsedUser (void) const
void Start (void)
Start a measure.
Private Attributes
class SystemWallClockMsPrivate * m_priv
The implementation.
Detailed Description
Measure elapsed wall clock time in milliseconds.
Definition at line 53 of file system-wall-clock-ms.h.
Constructor & Destructor Documentation
SystemWallClockMs()
ns3::SystemWallClockMs::SystemWallClockMs ()
Definition at line 146 of file unix-system-wall-clock-ms.cc.
References NS_LOG_FUNCTION.
~SystemWallClockMs()
ns3::SystemWallClockMs::~SystemWallClockMs ()
Definition at line 152 of file unix-system-wall-clock-ms.cc.
References m_priv, and NS_LOG_FUNCTION.
Member Function Documentation
End()
int64_t ns3::SystemWallClockMs::End (void)
Stop measuring the time since Start() was called.
Returns
the measured elapsed wall clock time (in milliseconds) since Start() was invoked.
It is possible to start a new measurement with Start() after this method returns.
Returns int64_t to avoid dependency on clock_t in ns-3 code.
Definition at line 167 of file unix-system-wall-clock-ms.cc.
References ns3::SystemWallClockMsPrivate::End(), m_priv, and NS_LOG_FUNCTION.
Referenced by ns3::ShowProgress::CheckProgress(), Bench::RunBench(), and runBenchOneIteration().
GetElapsedReal()
int64_t ns3::SystemWallClockMs::GetElapsedReal (void) const
Returns
the measured elapsed wall clock time (in milliseconds) since Start() was invoked.
Returns int64_t to avoid dependency on clock_t in ns-3 code.
Definition at line 174 of file unix-system-wall-clock-ms.cc.
References ns3::SystemWallClockMsPrivate::GetElapsedReal(), m_priv, and NS_LOG_FUNCTION.
GetElapsedSystem()
int64_t ns3::SystemWallClockMs::GetElapsedSystem (void) const
Returns
the measured elapsed 'system' wall clock time (in milliseconds) since Start() was invoked.
Returns int64_t to avoid dependency on clock_t in ns-3 code.
Definition at line 188 of file unix-system-wall-clock-ms.cc.
References ns3::SystemWallClockMsPrivate::GetElapsedSystem(), m_priv, and NS_LOG_FUNCTION.
GetElapsedUser()
int64_t ns3::SystemWallClockMs::GetElapsedUser (void) const
Returns
the measured elapsed 'user' wall clock time (in milliseconds) since Start() was invoked.
Returns int64_t to avoid dependency on clock_t in ns-3 code.
Definition at line 181 of file unix-system-wall-clock-ms.cc.
References ns3::SystemWallClockMsPrivate::GetElapsedUser(), m_priv, and NS_LOG_FUNCTION.
Start()
void ns3::SystemWallClockMs::Start (void)
Start a measure.
Definition at line 160 of file unix-system-wall-clock-ms.cc.
References m_priv, NS_LOG_FUNCTION, and ns3::SystemWallClockMsPrivate::Start().
Referenced by ns3::TestCase::Run(), Bench::RunBench(), runBenchOneIteration(), and ns3::ShowProgress::ScheduleCheckProgress().
Member Data Documentation
m_priv
class SystemWallClockMsPrivate* ns3::SystemWallClockMs::m_priv private
The implementation.
Definition at line 98 of file system-wall-clock-ms.h.
Referenced by ~SystemWallClockMs(), End(), GetElapsedReal(), GetElapsedSystem(), GetElapsedUser(), and Start().
The documentation for this class was generated from the following files:
src/core/model/system-wall-clock-ms.h
src/core/model/unix-system-wall-clock-ms.cc
src/core/model/win32-system-wall-clock-ms.cc