ns-3: ns3::CalendarScheduler Class Reference
ns3::CalendarScheduler Class Reference
Core » Scheduler and Events
a calendar queue event scheduler
#include "calendar-scheduler.h"
Public Member Functions
CalendarScheduler ()
Constructor.
virtual ~CalendarScheduler ()
Destructor.
virtual void Insert (const Scheduler::Event &ev)
Insert a new Event in the schedule.
virtual bool IsEmpty (void) const
Test if the schedule is empty.
virtual Scheduler::Event PeekNext (void) const
Get a pointer to the next event.
virtual void Remove (const Scheduler::Event &ev)
Remove a specific event from the event list.
virtual Scheduler::Event RemoveNext (void)
Remove the earliest event from the event list.
Public Member Functions inherited from ns3::Scheduler
virtual ~Scheduler ()=0
Destructor.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Scheduler
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef std::list< Scheduler::Event > Bucket
Calendar bucket type: a list of Events.
Private Member Functions
uint64_t CalculateNewWidth (void)
Compute the new bucket size, based on up to the first 25 entries.
void DoInsert (const Scheduler::Event &ev)
Insert a new event in to the correct bucket.
Scheduler::Event DoRemoveNext (void)
Remove the earliest event.
void DoResize (uint32_t newSize, uint64_t newWidth)
Resize the number of buckets and width.
uint32_t Hash (uint64_t key) const
Hash the dimensionless time to a bucket.
void Init (uint32_t nBuckets, uint64_t width, uint64_t startPrio)
Initialize the calendar queue.
void PrintInfo (void)
Print the configuration and bucket size distribution.
void Resize (uint32_t newSize)
Resize to a new number of buckets, with automatically computed width.
void ResizeDown (void)
Halve the number of buckets if necessary.
void ResizeUp (void)
Double the number of buckets if necessary.
void SetReverse (bool reverse)
Set the insertion order.
Private Attributes
Bucket * m_buckets
Array of buckets.
uint64_t m_bucketTop
Priority at the top of the bucket from which last event was dequeued.
uint32_t m_lastBucket
Bucket index from which the last event was dequeued.
uint64_t m_lastPrio
The priority of the last event removed.
uint32_t m_nBuckets
Number of buckets in the array.
uint32_t m_qSize
Number of events in queue.
bool m_reverse = false
Bucket ordering.
uint64_t m_width
Duration of a bucket, in dimensionless time units.
Scheduler::Event &(* NextEvent)(Bucket &bucket)
Get the next event from the bucket, according to m_reverse.
bool(* Order)(const EventKey &newEvent, const EventKey &it)
Ordering function to identify the insertion point, according to m_reverse.
void(* Pop)(Bucket &)
Pop the next event from the bucket, according to m_reverse.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
a calendar queue event scheduler
Introspection did not find any typical Config paths.
This event scheduler is a direct implementation of the algorithm known as a calendar queue, first published in 1988 in "Calendar Queues: A Fast O(1) Priority Queue Implementation for the Simulation Event Set Problem" by Randy Brown. There are many refinements published later but this class implements the original algorithm (to the best of my knowledge).
This class uses a vector of buckets; each bucket covers a uniform time span. The bucket index for an event with timestamp ts is (ts / m_width) % m_nBuckets. This class automatically adjusts the number of buckets to keep the average occupancy around 2. Buckets themselves are implemented as a std::list<>, and events are kept sorted withing the buckets.
Time Complexity
Operation Amortized Time Reason
Insert() ~Constant Ordering within bucket; possible resize
IsEmpty() Constant Explicit queue size
PeekNext() ~Constant Search buckets
Remove() ~Constant Search within bucket; possible resize
RemoveNext() ~Constant Search buckets; possible resize
Memory Complexity
Category Memory Reason
Overhead 2 x sizeof (*) + size_t
(24 bytes) std::list
Per Event 2 x sizeof (*) std::list
Note
This queue is much slower than I expected (much slower than the std::map queue) and this seems to be because the original resizing policy is horribly bad. This is most likely the reason why there have been so many variations published which all slightly tweak the resizing heuristics to obtain a better distribution of events across buckets.
While inserion sort is not discussed in the original article, its implementation appears to dramatically affect performance. The default implementation sorts buckets in increasing (chronological) order. The alternative, sorting buckets in decreasing order, was adopted in NS-2 because they observed that new events were more likely to be later than already scheduled events. In this case sorting buckets in reverse chronological order reduces enqueue time.
Attributes
Reverse: Store events in reverse chronological order
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct
No TraceSources are defined for this type.
Size of this type is 120 bytes (on a 64-bit architecture).
Definition at line 92 of file calendar-scheduler.h.
Member Typedef Documentation
Bucket
typedef std::list<Scheduler::Event> ns3::CalendarScheduler::Bucket private
Calendar bucket type: a list of Events.
Definition at line 170 of file calendar-scheduler.h.
Constructor & Destructor Documentation
CalendarScheduler()
ns3::CalendarScheduler::CalendarScheduler ()
Constructor.
Definition at line 61 of file calendar-scheduler.cc.
References Init(), m_qSize, and NS_LOG_FUNCTION.
~CalendarScheduler()
ns3::CalendarScheduler::~CalendarScheduler () virtual
Destructor.
Definition at line 67 of file calendar-scheduler.cc.
References m_buckets, and NS_LOG_FUNCTION.
Member Function Documentation
CalculateNewWidth()
uint64_t ns3::CalendarScheduler::CalculateNewWidth (void) private
Compute the new bucket size, based on up to the first 25 entries.
Returns
The new width.
Definition at line 324 of file calendar-scheduler.cc.
References DoInsert(), DoRemoveNext(), m_bucketTop, m_lastBucket, m_lastPrio, m_qSize, max, and NS_LOG_FUNCTION.
Referenced by Resize().
DoInsert()
void ns3::CalendarScheduler::DoInsert (const Scheduler::Event & ev) private
Insert a new event in to the correct bucket.
Parameters
[in] ev The new Event.
Definition at line 146 of file calendar-scheduler.cc.
References Hash(), ns3::Scheduler::Event::key, m_buckets, ns3::Scheduler::EventKey::m_ts, ns3::Scheduler::EventKey::m_uid, NS_LOG_FUNCTION, NS_LOG_LOGIC, and Order.
Referenced by CalculateNewWidth(), DoResize(), and Insert().
DoRemoveNext()
Scheduler::Event ns3::CalendarScheduler::DoRemoveNext (void) private
Remove the earliest event.
Returns
The earliest event.
Definition at line 216 of file calendar-scheduler.cc.
References Hash(), IsEmpty(), ns3::Scheduler::Event::key, m_buckets, m_bucketTop, ns3::Scheduler::EventKey::m_context, m_lastBucket, m_lastPrio, m_nBuckets, ns3::Scheduler::EventKey::m_ts, ns3::Scheduler::EventKey::m_uid, m_width, NextEvent, NS_ASSERT, NS_LOG_FUNCTION, and Pop.
Referenced by CalculateNewWidth(), and RemoveNext().
DoResize()
void ns3::CalendarScheduler::DoResize (uint32_t newSize, uint64_t newWidth) private
Resize the number of buckets and width.
Parameters
[in] newSize The number of buckets.
[in] newWidth The size of the new buckets.
Definition at line 403 of file calendar-scheduler.cc.
References DoInsert(), Init(), m_buckets, m_lastPrio, m_nBuckets, and NS_LOG_FUNCTION.
Referenced by Resize().
GetTypeId()
TypeId ns3::CalendarScheduler::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 45 of file calendar-scheduler.cc.
References ns3::TypeId::ATTR_CONSTRUCT, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::TypeId::SetParent(), and SetReverse().
Hash()
uint32_t ns3::CalendarScheduler::Hash (uint64_t key) const inline private
Hash the dimensionless time to a bucket.
Parameters
[in] key The dimensionless time.
Returns
The bucket index.
Definition at line 137 of file calendar-scheduler.cc.
References m_nBuckets, m_width, and NS_LOG_FUNCTION.
Referenced by DoInsert(), DoRemoveNext(), Init(), and Remove().
Init()
void ns3::CalendarScheduler::Init (uint32_t nBuckets, uint64_t width, uint64_t startPrio) private
Initialize the calendar queue.
Parameters
[in] nBuckets The number of buckets.
[in] width The bucket size, in dimensionless time units.
[in] startPrio The starting time.
Definition at line 111 of file calendar-scheduler.cc.
References Hash(), m_buckets, m_bucketTop, m_lastBucket, m_lastPrio, m_nBuckets, m_width, and NS_LOG_FUNCTION.
Referenced by CalendarScheduler(), and DoResize().
Insert()
void ns3::CalendarScheduler::Insert (const Scheduler::Event & ev) virtual
Insert a new Event in the schedule.
Parameters
[in] ev Event to store in the event list
Implements ns3::Scheduler.
Definition at line 167 of file calendar-scheduler.cc.
References DoInsert(), m_qSize, NS_LOG_FUNCTION, and ResizeUp().
IsEmpty()
bool ns3::CalendarScheduler::IsEmpty (void) const virtual
Test if the schedule is empty.
Returns
true if the event list is empty and false otherwise.
Implements ns3::Scheduler.
Definition at line 175 of file calendar-scheduler.cc.
References m_qSize, and NS_LOG_FUNCTION.
Referenced by DoRemoveNext(), PeekNext(), Remove(), and RemoveNext().
PeekNext()
Scheduler::Event ns3::CalendarScheduler::PeekNext (void) const virtual
Get a pointer to the next event.
This method cannot be invoked if the list is empty.
Returns
A pointer to the next earliest event. The caller takes ownership of the returned pointer.
Implements ns3::Scheduler.
Definition at line 181 of file calendar-scheduler.cc.
References ns3::Scheduler::Event::impl, IsEmpty(), ns3::Scheduler::Event::key, m_buckets, m_bucketTop, ns3::Scheduler::EventKey::m_context, m_lastBucket, m_nBuckets, ns3::Scheduler::EventKey::m_ts, ns3::Scheduler::EventKey::m_uid, m_width, NextEvent, NS_ASSERT, and NS_LOG_FUNCTION.
PrintInfo()
void ns3::CalendarScheduler::PrintInfo (void) private
Print the configuration and bucket size distribution.
Definition at line 124 of file calendar-scheduler.cc.
References m_buckets, m_nBuckets, m_width, and NS_LOG_FUNCTION.
Remove()
void ns3::CalendarScheduler::Remove (const Scheduler::Event & ev) virtual
Remove a specific event from the event list.
This method cannot be invoked if the list is empty.
Parameters
[in] ev The event to remove
Implements ns3::Scheduler.
Definition at line 278 of file calendar-scheduler.cc.
References Hash(), ns3::Scheduler::Event::impl, IsEmpty(), ns3::Scheduler::Event::key, m_buckets, m_qSize, ns3::Scheduler::EventKey::m_ts, ns3::Scheduler::EventKey::m_uid, NS_ASSERT, NS_LOG_FUNCTION, and ResizeDown().
RemoveNext()
Scheduler::Event ns3::CalendarScheduler::RemoveNext (void) virtual
Remove the earliest event from the event list.
This method cannot be invoked if the list is empty.
Returns
The Event.
Implements ns3::Scheduler.
Definition at line 263 of file calendar-scheduler.cc.
References DoRemoveNext(), IsEmpty(), ns3::Scheduler::Event::key, m_bucketTop, m_lastBucket, m_qSize, ns3::Scheduler::EventKey::m_ts, ns3::Scheduler::EventKey::m_uid, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, and ResizeDown().
Resize()
void ns3::CalendarScheduler::Resize (uint32_t newSize) private
Resize to a new number of buckets, with automatically computed width.
Parameters
[in] newSize The new number of buckets.
Definition at line 422 of file calendar-scheduler.cc.
References CalculateNewWidth(), DoResize(), and NS_LOG_FUNCTION.
Referenced by ResizeDown(), and ResizeUp().
ResizeDown()
void ns3::CalendarScheduler::ResizeDown (void) private
Halve the number of buckets if necessary.
Definition at line 313 of file calendar-scheduler.cc.
References m_nBuckets, m_qSize, NS_LOG_FUNCTION, and Resize().
Referenced by Remove(), and RemoveNext().
ResizeUp()
void ns3::CalendarScheduler::ResizeUp (void) private
Double the number of buckets if necessary.
Definition at line 302 of file calendar-scheduler.cc.
References m_nBuckets, m_qSize, NS_LOG_FUNCTION, and Resize().
Referenced by Insert().
SetReverse()
void ns3::CalendarScheduler::SetReverse (bool reverse) private
Set the insertion order.
This can only be used at construction, as invoked by the Attribute Reverse.
Parameters
[in] reverse If true, store events in decreasing time stamp order.
Definition at line 74 of file calendar-scheduler.cc.
References m_reverse, NextEvent, NS_LOG_FUNCTION, Order, and Pop.
Referenced by GetTypeId().
Member Data Documentation
m_buckets
Bucket* ns3::CalendarScheduler::m_buckets private
Array of buckets.
Definition at line 173 of file calendar-scheduler.h.
Referenced by ~CalendarScheduler(), DoInsert(), DoRemoveNext(), DoResize(), Init(), PeekNext(), PrintInfo(), and Remove().
m_bucketTop
uint64_t ns3::CalendarScheduler::m_bucketTop private
Priority at the top of the bucket from which last event was dequeued.
Definition at line 181 of file calendar-scheduler.h.
Referenced by CalculateNewWidth(), DoRemoveNext(), Init(), PeekNext(), and RemoveNext().
m_lastBucket
uint32_t ns3::CalendarScheduler::m_lastBucket private
Bucket index from which the last event was dequeued.
Definition at line 179 of file calendar-scheduler.h.
Referenced by CalculateNewWidth(), DoRemoveNext(), Init(), PeekNext(), and RemoveNext().
m_lastPrio
uint64_t ns3::CalendarScheduler::m_lastPrio private
The priority of the last event removed.
Definition at line 183 of file calendar-scheduler.h.
Referenced by CalculateNewWidth(), DoRemoveNext(), DoResize(), and Init().
m_nBuckets
uint32_t ns3::CalendarScheduler::m_nBuckets private
Number of buckets in the array.
Definition at line 175 of file calendar-scheduler.h.
Referenced by DoRemoveNext(), DoResize(), Hash(), Init(), PeekNext(), PrintInfo(), ResizeDown(), and ResizeUp().
m_qSize
uint32_t ns3::CalendarScheduler::m_qSize private
Number of events in queue.
Definition at line 185 of file calendar-scheduler.h.
Referenced by CalendarScheduler(), CalculateNewWidth(), Insert(), IsEmpty(), Remove(), RemoveNext(), ResizeDown(), and ResizeUp().
m_reverse
bool ns3::CalendarScheduler::m_reverse = false private
Bucket ordering.
If false (default), store events in increasing time stamp order. If true, store events in decreasing time stamp order.
Definition at line 220 of file calendar-scheduler.h.
Referenced by SetReverse().
m_width
uint64_t ns3::CalendarScheduler::m_width private
Duration of a bucket, in dimensionless time units.
Definition at line 177 of file calendar-scheduler.h.
Referenced by DoRemoveNext(), Hash(), Init(), PeekNext(), and PrintInfo().
NextEvent
Scheduler::Event&(* ns3::CalendarScheduler::NextEvent) (Bucket &bucket) private
Get the next event from the bucket, according to m_reverse.
Parameters
[in] bucket The bucket to draw from.
Returns
The next event from the bucket.
Definition at line 202 of file calendar-scheduler.h.
Referenced by DoRemoveNext(), PeekNext(), and SetReverse().
Order
bool(* ns3::CalendarScheduler::Order) (const EventKey &newEvent, const EventKey &it) private
Ordering function to identify the insertion point, according to m_reverse.
Parameters
[in] newEvent The new event being inserted.
[in] it The current position in the bucket being examined.
Returns
true if the newEvent belongs before \it.
Definition at line 209 of file calendar-scheduler.h.
Referenced by DoInsert(), and SetReverse().
Pop
void(* ns3::CalendarScheduler::Pop) (Bucket &) private
Pop the next event from the bucket, according to m_reverse.
Parameters
[in] bucket The bucket to pop from.
Definition at line 214 of file calendar-scheduler.h.
Referenced by DoRemoveNext(), and SetReverse().
The documentation for this class was generated from the following files:
src/core/model/calendar-scheduler.h
src/core/model/calendar-scheduler.cc