ns-3: ns3::V4PingHelper Class Reference
ns3::V4PingHelper Class Reference
Internet Applications » V4Ping
Create a IPv4 ping application and associate it to a node.
#include "v4ping-helper.h"
Public Member Functions
V4PingHelper (Ipv4Address remote)
Create a V4PingHelper which is used to make life easier for people wanting to use ping Applications.
ApplicationContainer Install (NodeContainer nodes) const
Install a Ping application on each Node in the provided NodeContainer.
ApplicationContainer Install (Ptr< Node > node) const
Install a Ping application on the provided Node.
ApplicationContainer Install (std::string nodeName) const
Install a Ping application on the provided Node.
void SetAttribute (std::string name, const AttributeValue &value)
Configure ping applications attribute.
Private Member Functions
Ptr< Application > InstallPriv (Ptr< Node > node) const
Do the actual application installation in the node.
Private Attributes
ObjectFactory m_factory
Object factory.
Detailed Description
Create a IPv4 ping application and associate it to a node.
This class creates one or multiple instances of ns3::V4Ping and associates it/them to one/multiple node(s).
Definition at line 37 of file v4ping-helper.h.
Constructor & Destructor Documentation
V4PingHelper()
ns3::V4PingHelper::V4PingHelper (Ipv4Address remote)
Create a V4PingHelper which is used to make life easier for people wanting to use ping Applications.
Parameters
remote The address which should be pinged
Definition at line 27 of file v4ping-helper.cc.
References m_factory, ns3::ObjectFactory::Set(), and ns3::ObjectFactory::SetTypeId().
Member Function Documentation
Install() [1/3]
ApplicationContainer ns3::V4PingHelper::Install (NodeContainer nodes) const
Install a Ping application on each Node in the provided NodeContainer.
Parameters
nodes The NodeContainer containing all of the nodes to get a V4Ping application.
Returns
A list of Ping applications, one for each input node
Definition at line 53 of file v4ping-helper.cc.
References ns3::ApplicationContainer::Add(), ns3::NodeContainer::Begin(), ns3::NodeContainer::End(), and InstallPriv().
Referenced by CsmaPingTestCase::DoRun(), and AodvExample::InstallApplications().
Install() [2/3]
ApplicationContainer ns3::V4PingHelper::Install (Ptr< Node > node) const
Install a Ping application on the provided Node.
The Node is specified directly by a Ptr<Node>
Parameters
node The node to install the V4PingApplication on.
Returns
An ApplicationContainer holding the Ping application created.
Definition at line 40 of file v4ping-helper.cc.
References InstallPriv().
Install() [3/3]
ApplicationContainer ns3::V4PingHelper::Install (std::string nodeName) const
Install a Ping application on the provided Node.
The Node is specified by a string that must have previously been associated with a Node using the Object Name Service.
Parameters
nodeName The node to install the V4PingApplication on.
Returns
An ApplicationContainer holding the Ping application created.
Definition at line 46 of file v4ping-helper.cc.
References InstallPriv().
InstallPriv()
Ptr< Application > ns3::V4PingHelper::InstallPriv (Ptr< Node > node) const private
Do the actual application installation in the node.
Parameters
node the node
Returns
a Smart pointer to the installed application
Definition at line 65 of file v4ping-helper.cc.
References ns3::Node::AddApplication(), ns3::ObjectFactory::Create(), and m_factory.
Referenced by Install().
SetAttribute()
void ns3::V4PingHelper::SetAttribute (std::string name, const AttributeValue & value)
Configure ping applications attribute.
Parameters
name attribute's name
value attribute's value
Definition at line 34 of file v4ping-helper.cc.
References m_factory, and ns3::ObjectFactory::Set().
Referenced by AodvExample::InstallApplications().
Member Data Documentation
m_factory
ObjectFactory ns3::V4PingHelper::m_factory private
Object factory.
Definition at line 93 of file v4ping-helper.h.
Referenced by V4PingHelper(), InstallPriv(), and SetAttribute().
The documentation for this class was generated from the following files:
src/internet-apps/helper/v4ping-helper.h
src/internet-apps/helper/v4ping-helper.cc