ns-3: ns3::Building Class Reference
ns3::Building Class Reference
Mobility
a 3d building block
#include "building.h"
Public Types
enum BuildingType_t { Residential , Office , Commercial }
enum ExtWallsType_t { Wood , ConcreteWithWindows , ConcreteWithoutWindows , StoneBlocks }
Public Member Functions
Building ()
Create a zero-sized building located at coordinates (0.0,0.0,0.0) and with 1 floors and 1 room.
Building (double xMin, double xMax, double yMin, double yMax, double zMin, double zMax)
Construct a simple building with 1 room and 1 floor.
virtual ~Building ()
Destructor.
virtual void DoDispose ()
Destructor implementation.
Box GetBoundaries () const
BuildingType_t GetBuildingType () const
ExtWallsType_t GetExtWallsType () const
uint16_t GetFloor (Vector position) const
uint32_t GetId (void) const
uint16_t GetNFloors () const
uint16_t GetNRoomsX () const
uint16_t GetNRoomsY () const
uint16_t GetRoomX (Vector position) const
uint16_t GetRoomY (Vector position) const
bool IsInside (Vector position) const
bool IsIntersect (const Vector &l1, const Vector &l2) const
Checks if a line-segment between position l1 and position l2 intersects a building.
void SetBoundaries (Box box)
Set the boundaries of the building.
void SetBuildingType (Building::BuildingType_t t)
void SetExtWallsType (Building::ExtWallsType_t t)
void SetNFloors (uint16_t nfloors)
void SetNRoomsX (uint16_t nroomx)
void SetNRoomsY (uint16_t nroomy)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Box m_buildingBounds
uint32_t m_buildingId
BuildingType_t m_buildingType
ExtWallsType_t m_externalWalls
uint16_t m_floors
number of floors, must be greater than 0, and 1 means only one floor (i.e., groundfloor)
uint16_t m_roomsX
uint16_t m_roomsY
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
a 3d building block
Introspection did not find any typical Config paths.
Attributes
NRoomsX: The number of rooms in the X axis.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 1
Flags: construct write read
NRoomsY: The number of rooms in the Y axis.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 1
Flags: construct write read
NFloors: The number of floors of this building.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 1
Flags: construct write read
Id: The id (unique integer) of this Building.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Flags: read
Boundaries: The boundaries of this Building as a value of type ns3::Box
Set with class: BoxValue
Underlying type: Box
Initial value: 0|0|0|0|0|0
Flags: construct write read
Type: The type of building
Set with class: ns3::EnumValue
Underlying type:
Initial value: Residential
Flags: construct write read
ExternalWallsType: The type of material of which the external walls are made
Set with class: ns3::EnumValue
Underlying type:
Initial value: ConcreteWithWindows
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 104 bytes (on a 64-bit architecture).
Definition at line 37 of file building.h.
Member Enumeration Documentation
BuildingType_t
enum ns3::Building::BuildingType_t
Enumerator
Residential
Office
Commercial
Definition at line 46 of file building.h.
ExtWallsType_t
enum ns3::Building::ExtWallsType_t
Enumerator
Wood
ConcreteWithWindows
ConcreteWithoutWindows
StoneBlocks
Definition at line 50 of file building.h.
Constructor & Destructor Documentation
Building() [1/2]
ns3::Building::Building (double xMin, double xMax, double yMin, double yMax, double zMin, double zMax)
Construct a simple building with 1 room and 1 floor.
Parameters
xMin x coordinates of left boundary.
xMax x coordinates of right boundary.
yMin y coordinates of bottom boundary.
yMax y coordinates of top boundary.
zMin z coordinates of down boundary.
zMax z coordinates of up boundary.
Definition at line 84 of file building.cc.
References NS_FATAL_ERROR.
Building() [2/2]
ns3::Building::Building ()
Create a zero-sized building located at coordinates (0.0,0.0,0.0) and with 1 floors and 1 room.
Definition at line 114 of file building.cc.
References ns3::BuildingList::Add(), m_buildingId, and NS_LOG_FUNCTION.
~Building()
ns3::Building::~Building () virtual
Destructor.
Definition at line 120 of file building.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::Building::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 126 of file building.cc.
References NS_LOG_FUNCTION.
GetBoundaries()
Box ns3::Building::GetBoundaries () const
Returns
the boundaries of the building
Definition at line 181 of file building.cc.
References m_buildingBounds, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetBuildingType()
Building::BuildingType_t ns3::Building::GetBuildingType () const
Returns
the type of building
Definition at line 188 of file building.cc.
References m_buildingType.
Referenced by GetTypeId().
GetExtWallsType()
Building::ExtWallsType_t ns3::Building::GetExtWallsType () const
Returns
the type of external walls of the building
Definition at line 194 of file building.cc.
References m_externalWalls.
Referenced by GetTypeId().
GetFloor()
uint16_t ns3::Building::GetFloor (Vector position) const
Parameters
position a position inside the building
Returns
the floor where the position falls
Definition at line 267 of file building.cc.
References IsInside(), m_buildingBounds, m_floors, sample-rng-plot::n, NS_ASSERT, NS_LOG_LOGIC, ns3::Box::zMax, and ns3::Box::zMin.
GetId()
uint32_t ns3::Building::GetId (void) const
Returns
the unique id of this Building. This unique id happens to be also the index of the Building into the BuildingList.
Definition at line 132 of file building.cc.
References m_buildingId, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetNFloors()
uint16_t ns3::Building::GetNFloors () const
Returns
the number of floors of the building
Definition at line 200 of file building.cc.
References m_floors.
Referenced by GetTypeId().
GetNRoomsX()
uint16_t ns3::Building::GetNRoomsX () const
Returns
the number of rooms along the x-axis of the building
Definition at line 206 of file building.cc.
References m_roomsX.
Referenced by GetTypeId().
GetNRoomsY()
uint16_t ns3::Building::GetNRoomsY () const
Returns
the number of rooms along the y-axis
Definition at line 212 of file building.cc.
References m_roomsY.
Referenced by GetTypeId().
GetRoomX()
uint16_t ns3::Building::GetRoomX (Vector position) const
Parameters
position a position inside the building
Returns
the number of the room along the X axis where the position falls
Definition at line 225 of file building.cc.
References IsInside(), m_buildingBounds, m_roomsX, sample-rng-plot::n, NS_ASSERT, NS_LOG_LOGIC, sample-rng-plot::x, ns3::Box::xMax, and ns3::Box::xMin.
GetRoomY()
uint16_t ns3::Building::GetRoomY (Vector position) const
Parameters
position a position inside the building
Returns
the number of the room along the Y axis where the position falls
Definition at line 246 of file building.cc.
References IsInside(), m_buildingBounds, m_roomsY, sample-rng-plot::n, NS_ASSERT, NS_LOG_LOGIC, ns3::Box::yMax, and ns3::Box::yMin.
GetTypeId()
TypeId ns3::Building::GetTypeId (void) static
Definition at line 39 of file building.cc.
References Commercial, ConcreteWithoutWindows, ConcreteWithWindows, GetBoundaries(), GetBuildingType(), GetExtWallsType(), GetId(), GetNFloors(), GetNRoomsX(), GetNRoomsY(), ns3::MakeBoxAccessor(), ns3::MakeBoxChecker(), ns3::MakeEnumAccessor(), ns3::MakeEnumChecker(), ns3::MakeUintegerAccessor(), Office, Residential, SetBoundaries(), SetBuildingType(), SetExtWallsType(), SetNFloors(), SetNRoomsX(), SetNRoomsY(), ns3::TypeId::SetParent(), StoneBlocks, and Wood.
IsInside()
bool ns3::Building::IsInside (Vector position) const
Parameters
position some position
Returns
true if the position fall inside the building, false otherwise
Definition at line 218 of file building.cc.
References ns3::Box::IsInside(), and m_buildingBounds.
Referenced by GetFloor(), GetRoomX(), and GetRoomY().
IsIntersect()
bool ns3::Building::IsIntersect (const Vector & l1, const Vector & l2) const
Checks if a line-segment between position l1 and position l2 intersects a building.
Parameters
l1 position
l2 position
Returns
true if there is a intersection, false otherwise
Definition at line 288 of file building.cc.
References ns3::Box::IsIntersect(), and m_buildingBounds.
SetBoundaries()
void ns3::Building::SetBoundaries (Box box)
Set the boundaries of the building.
Parameters
box the Box defining the boundaries of the building
Definition at line 139 of file building.cc.
References m_buildingBounds, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetBuildingType()
void ns3::Building::SetBuildingType (Building::BuildingType_t t)
Parameters
t the type of building (i.e., Residential, Office, Commercial)
This method allows to set building type (default is Residential)
Definition at line 146 of file building.cc.
References m_buildingType, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetExtWallsType()
void ns3::Building::SetExtWallsType (Building::ExtWallsType_t t)
Parameters
t the type of external walls (i.e., Wood, ConcreteWithWindows, ConcreteWithoutWindows and StoneBlocks), used for evaluating the loss due to the penetration of external walls in outdoor <-> indoor comm.
This method allows to set external walls type (default is Residential)
Definition at line 153 of file building.cc.
References m_externalWalls, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetNFloors()
void ns3::Building::SetNFloors (uint16_t nfloors)
Parameters
nfloors the number of floors in the building
This method allows to set the number of floors in the building (default is 1)
Definition at line 160 of file building.cc.
References m_floors, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetNRoomsX()
void ns3::Building::SetNRoomsX (uint16_t nroomx)
Parameters
nroomx the number of rooms along the x axis
This method allows to set the number of rooms along the x-axis
Definition at line 167 of file building.cc.
References m_roomsX, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetNRoomsY()
void ns3::Building::SetNRoomsY (uint16_t nroomy)
Parameters
nroomy the number of floors in the building
This method allows to set the number of rooms along the y-axis
Definition at line 174 of file building.cc.
References m_roomsY, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
Member Data Documentation
m_buildingBounds
Box ns3::Building::m_buildingBounds private
Definition at line 218 of file building.h.
Referenced by GetBoundaries(), GetFloor(), GetRoomX(), GetRoomY(), IsInside(), IsIntersect(), and SetBoundaries().
m_buildingId
uint32_t ns3::Building::m_buildingId private
Definition at line 228 of file building.h.
Referenced by Building(), and GetId().
m_buildingType
BuildingType_t ns3::Building::m_buildingType private
Definition at line 229 of file building.h.
Referenced by GetBuildingType(), and SetBuildingType().
m_externalWalls
ExtWallsType_t ns3::Building::m_externalWalls private
Definition at line 230 of file building.h.
Referenced by GetExtWallsType(), and SetExtWallsType().
m_floors
uint16_t ns3::Building::m_floors private
number of floors, must be greater than 0, and 1 means only one floor (i.e., groundfloor)
Definition at line 224 of file building.h.
Referenced by GetFloor(), GetNFloors(), and SetNFloors().
m_roomsX
uint16_t ns3::Building::m_roomsX private
Definition at line 225 of file building.h.
Referenced by GetNRoomsX(), GetRoomX(), and SetNRoomsX().
m_roomsY
uint16_t ns3::Building::m_roomsY private
Definition at line 226 of file building.h.
Referenced by GetNRoomsY(), GetRoomY(), and SetNRoomsY().
The documentation for this class was generated from the following files:
src/buildings/model/building.h
src/buildings/model/building.cc