ns-3: ns3::ThreeGppHttpClientHelper Class Reference
ns3::ThreeGppHttpClientHelper Class Reference
Applications
Helper to make it easier to instantiate an ThreeGppHttpClient on a set of nodes.
#include "three-gpp-http-helper.h"
Public Member Functions
ThreeGppHttpClientHelper (const Address &address)
Create a ThreeGppHttpClientHelper to make it easier to work with ThreeGppHttpClient applications.
ApplicationContainer Install (const std::string &nodeName) const
Install a ThreeGppHttpClient on each node of the input container configured with all the attributes set with SetAttribute().
ApplicationContainer Install (NodeContainer c) const
Install a ThreeGppHttpClient on each node of the input container configured with all the attributes set with SetAttribute().
ApplicationContainer Install (Ptr< Node > node) const
Install a ThreeGppHttpClient on each node of the input container configured with all the attributes set with SetAttribute().
void SetAttribute (const std::string &name, const AttributeValue &value)
Helper function used to set the underlying application attributes, but not the socket attributes.
Private Member Functions
Ptr< Application > InstallPriv (Ptr< Node > node) const
Private Attributes
ObjectFactory m_factory
Used to instantiate an ThreeGppHttpClient instance.
Detailed Description
Helper to make it easier to instantiate an ThreeGppHttpClient on a set of nodes.
Definition at line 42 of file three-gpp-http-helper.h.
Constructor & Destructor Documentation
ThreeGppHttpClientHelper()
ns3::ThreeGppHttpClientHelper::ThreeGppHttpClientHelper (const Address & address)
Create a ThreeGppHttpClientHelper to make it easier to work with ThreeGppHttpClient applications.
Parameters
address The address of the remote server node to send traffic to.
Definition at line 35 of file three-gpp-http-helper.cc.
References first::address, m_factory, ns3::ObjectFactory::Set(), and ns3::ObjectFactory::SetTypeId().
Member Function Documentation
Install() [1/3]
ApplicationContainer ns3::ThreeGppHttpClientHelper::Install (const std::string & nodeName) const
Install a ThreeGppHttpClient on each node of the input container configured with all the attributes set with SetAttribute().
Parameters
nodeName The name of the node on which an ThreeGppHttpClient will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 55 of file three-gpp-http-helper.cc.
References InstallPriv().
Install() [2/3]
ApplicationContainer ns3::ThreeGppHttpClientHelper::Install (NodeContainer c) const
Install a ThreeGppHttpClient on each node of the input container configured with all the attributes set with SetAttribute().
Parameters
c NodeContainer of the set of nodes on which an ThreeGppHttpClient will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 62 of file three-gpp-http-helper.cc.
References ns3::ApplicationContainer::Add(), ns3::NodeContainer::Begin(), ns3::NodeContainer::End(), and InstallPriv().
Referenced by ThreeGppHttpObjectTestCase::DoRun().
Install() [3/3]
ApplicationContainer ns3::ThreeGppHttpClientHelper::Install (Ptr< Node > node) const
Install a ThreeGppHttpClient on each node of the input container configured with all the attributes set with SetAttribute().
Parameters
node The node on which an ThreeGppHttpClient will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 49 of file three-gpp-http-helper.cc.
References InstallPriv().
InstallPriv()
Ptr< Application > ns3::ThreeGppHttpClientHelper::InstallPriv (Ptr< Node > node) const private
Internal:
Install a ThreeGppHttpClient on the node configured with all the attributes set with SetAttribute().
Parameters
node The node on which an ThreeGppHttpClient will be installed.
Returns
Ptr to the application installed.
Definition at line 74 of file three-gpp-http-helper.cc.
References ns3::Node::AddApplication(), ns3::ObjectFactory::Create(), and m_factory.
Referenced by Install().
SetAttribute()
void ns3::ThreeGppHttpClientHelper::SetAttribute (const std::string & name, const AttributeValue & value)
Helper function used to set the underlying application attributes, but not the socket attributes.
Parameters
name The name of the application attribute to set.
value The value of the application attribute to set.
Definition at line 42 of file three-gpp-http-helper.cc.
References m_factory, and ns3::ObjectFactory::Set().
Member Data Documentation
m_factory
ObjectFactory ns3::ThreeGppHttpClientHelper::m_factory private
Used to instantiate an ThreeGppHttpClient instance.
Definition at line 98 of file three-gpp-http-helper.h.
Referenced by ThreeGppHttpClientHelper(), InstallPriv(), and SetAttribute().
The documentation for this class was generated from the following files:
src/applications/helper/three-gpp-http-helper.h
src/applications/helper/three-gpp-http-helper.cc