ns-3: ns3::OutdoorPositionAllocator Class Reference
ns3::OutdoorPositionAllocator Class Reference
allocate outdoor positions
#include "building-position-allocator.h"
Public Member Functions
OutdoorPositionAllocator ()
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
virtual Vector GetNext (void) const
void SetX (Ptr< RandomVariableStream > x)
Set the random variable stream object that generates x-positions.
void SetY (Ptr< RandomVariableStream > y)
Set the random variable stream object that generates y-positions.
void SetZ (Ptr< RandomVariableStream > z)
Set the random variable stream object that generates z-positions.
Public Member Functions inherited from ns3::PositionAllocator
PositionAllocator ()
virtual ~PositionAllocator ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::PositionAllocator
static TypeId GetTypeId (void)
Register this type with the TypeId system.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint32_t m_maxAttempts
maximum number of attempts before giving up
Ptr< RandomVariableStream > m_x
pointer to x's random variable stream
Ptr< RandomVariableStream > m_y
pointer to y's random variable stream
Ptr< RandomVariableStream > m_z
pointer to z's random variable stream
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
allocate outdoor positions
Allocate positions outside of existing buildings using rejection sampling. This class extracts a random position in a box defined by the three RandomVariableStreams for the X, Y and Z dimensions (similarly to RandomBoxPositionAllocator), until a position is found that is outdoors with respect to all of the buildings in the scenario, or a maximum number of attempts is reached. The RandomVariableStream and the maximum number of attempts can be set using attributes. If the maximum number of attempts is reached, then the simulation aborts due to failure of properly positioning the node.
Config Paths
ns3::OutdoorPositionAllocator is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::OutdoorPositionAllocator"
Attributes
X: A random variable which represents the x coordinate of a position in a random box.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::RandomVariableStream>
Initial value: ns3::UniformRandomVariable[Min=0.0|Max=1.0]
Flags: construct write read
Y: A random variable which represents the y coordinate of a position in a random box.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::RandomVariableStream>
Initial value: ns3::UniformRandomVariable[Min=0.0|Max=1.0]
Flags: construct write read
Z: A random variable which represents the z coordinate of a position in a random box.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::RandomVariableStream>
Initial value: ns3::UniformRandomVariable[Min=0.0|Max=1.0]
Flags: construct write read
MaxAttempts: Maximum number of attempts for the rejection sampling before giving up.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 1000
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 64 bytes (on a 64-bit architecture).
Definition at line 84 of file building-position-allocator.h.
Constructor & Destructor Documentation
OutdoorPositionAllocator()
ns3::OutdoorPositionAllocator::OutdoorPositionAllocator ()
Definition at line 112 of file building-position-allocator.cc.
Member Function Documentation
AssignStreams()
int64_t ns3::OutdoorPositionAllocator::AssignStreams (int64_t stream) virtual
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Implements ns3::PositionAllocator.
Definition at line 216 of file building-position-allocator.cc.
References m_x, m_y, m_z, and ns3::RandomVariableStream::SetStream().
GetNext()
Vector ns3::OutdoorPositionAllocator::GetNext (void) const virtual
Returns
the next chosen position.
This method must be implement in subclasses.
Implements ns3::PositionAllocator.
Definition at line 165 of file building-position-allocator.cc.
References ns3::BuildingList::Begin(), ns3::BuildingList::End(), ns3::BuildingList::GetNBuildings(), ns3::RandomVariableStream::GetValue(), m_maxAttempts, m_x, m_y, m_z, NS_ABORT_MSG_IF, NS_LOG_INFO, and sample-rng-plot::x.
GetTypeId()
TypeId ns3::OutdoorPositionAllocator::GetTypeId (void) static
Definition at line 117 of file building-position-allocator.cc.
References m_maxAttempts, m_x, m_y, m_z, ns3::MakePointerAccessor(), ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
SetX()
void ns3::OutdoorPositionAllocator::SetX (Ptr< RandomVariableStream > x)
Set the random variable stream object that generates x-positions.
Parameters
x pointer to a RandomVariableStream object
Definition at line 149 of file building-position-allocator.cc.
References m_x, and sample-rng-plot::x.
SetY()
void ns3::OutdoorPositionAllocator::SetY (Ptr< RandomVariableStream > y)
Set the random variable stream object that generates y-positions.
Parameters
y pointer to a RandomVariableStream object
Definition at line 154 of file building-position-allocator.cc.
References m_y.
SetZ()
void ns3::OutdoorPositionAllocator::SetZ (Ptr< RandomVariableStream > z)
Set the random variable stream object that generates z-positions.
Parameters
z pointer to a RandomVariableStream object
Definition at line 159 of file building-position-allocator.cc.
References m_z.
Member Data Documentation
m_maxAttempts
uint32_t ns3::OutdoorPositionAllocator::m_maxAttempts private
maximum number of attempts before giving up
Definition at line 126 of file building-position-allocator.h.
Referenced by GetNext(), and GetTypeId().
m_x
Ptr<RandomVariableStream> ns3::OutdoorPositionAllocator::m_x private
pointer to x's random variable stream
Definition at line 122 of file building-position-allocator.h.
Referenced by AssignStreams(), GetNext(), GetTypeId(), and SetX().
m_y
Ptr<RandomVariableStream> ns3::OutdoorPositionAllocator::m_y private
pointer to y's random variable stream
Definition at line 123 of file building-position-allocator.h.
Referenced by AssignStreams(), GetNext(), GetTypeId(), and SetY().
m_z
Ptr<RandomVariableStream> ns3::OutdoorPositionAllocator::m_z private
pointer to z's random variable stream
Definition at line 124 of file building-position-allocator.h.
Referenced by AssignStreams(), GetNext(), GetTypeId(), and SetZ().
The documentation for this class was generated from the following files:
src/buildings/helper/building-position-allocator.h
src/buildings/helper/building-position-allocator.cc