ns-3: SpectrumWifiPhyFilterTest Class Reference
SpectrumWifiPhyFilterTest Class Reference
Wifi Models » wifi module tests | Test suites
Spectrum Wifi Phy Filter Test.
Public Member Functions
SpectrumWifiPhyFilterTest ()
SpectrumWifiPhyFilterTest (std::string name)
Constructor.
virtual ~SpectrumWifiPhyFilterTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
virtual void DoSetup (void)
Implementation to do any local setup required for this TestCase.
void RunOne ()
Run one function.
void RxCallback (Ptr< const Packet > p, RxPowerWattPerChannelBand rxPowersW)
Callback triggered when a packet is received by the PHYs.
void SendPpdu (void)
Send PPDU function.
Private Attributes
uint16_t m_rxChannelWidth
RX channel width (MHz)
Ptr< ExtSpectrumWifiPhy > m_rxPhy
RX PHY.
uint16_t m_txChannelWidth
TX channel width (MHz)
Ptr< ExtSpectrumWifiPhy > m_txPhy
TX PHY.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Spectrum Wifi Phy Filter Test.
Definition at line 324 of file spectrum-wifi-phy-test.cc.
Constructor & Destructor Documentation
SpectrumWifiPhyFilterTest() [1/2]
SpectrumWifiPhyFilterTest::SpectrumWifiPhyFilterTest ()
Definition at line 365 of file spectrum-wifi-phy-test.cc.
SpectrumWifiPhyFilterTest() [2/2]
SpectrumWifiPhyFilterTest::SpectrumWifiPhyFilterTest (std::string name)
Constructor.
Parameters
name reference name
Definition at line 372 of file spectrum-wifi-phy-test.cc.
~SpectrumWifiPhyFilterTest()
SpectrumWifiPhyFilterTest::~SpectrumWifiPhyFilterTest () virtual
Definition at line 391 of file spectrum-wifi-phy-test.cc.
References m_rxPhy, and m_txPhy.
Member Function Documentation
DoRun()
void SpectrumWifiPhyFilterTest::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 561 of file spectrum-wifi-phy-test.cc.
References m_rxChannelWidth, m_txChannelWidth, and RunOne().
DoSetup()
void SpectrumWifiPhyFilterTest::DoSetup (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test setup before DoRun is invoked.
Reimplemented from ns3::TestCase.
Definition at line 470 of file spectrum-wifi-phy-test.cc.
References ns3::Node::AddDevice(), ns3::Object::AggregateObject(), ns3::SpectrumWifiPhy::ConfigureStandardAndBand(), ns3::SpectrumWifiPhy::CreateWifiSpectrumPhyInterface(), m_rxPhy, m_txPhy, ns3::MakeCallback(), RxCallback(), ns3::SpectrumWifiPhy::SetChannel(), ns3::WifiPhy::SetDevice(), ns3::WifiPhy::SetErrorRateModel(), ns3::WifiPhy::SetMobility(), ns3::WifiNetDevice::SetPhy(), ns3::ObjectBase::TraceConnectWithoutContext(), ns3::WIFI_PHY_BAND_5GHZ, and ns3::WIFI_PHY_STANDARD_80211ax.
RunOne()
void SpectrumWifiPhyFilterTest::RunOne (void) private
Run one function.
Definition at line 513 of file spectrum-wifi-phy-test.cc.
References m_rxChannelWidth, m_rxPhy, m_txChannelWidth, m_txPhy, ns3::Seconds(), SendPpdu(), ns3::SpectrumWifiPhy::SetChannelWidth(), and ns3::SpectrumWifiPhy::SetFrequency().
Referenced by DoRun().
RxCallback()
void SpectrumWifiPhyFilterTest::RxCallback (Ptr< const Packet > p, RxPowerWattPerChannelBand rxPowersW) private
Callback triggered when a packet is received by the PHYs.
Parameters
context the context
p the received packet
rxPowersW the received power per channel band in watts
Definition at line 398 of file spectrum-wifi-phy-test.cc.
References ns3::SpectrumWifiPhy::GetBand(), m_rxChannelWidth, m_rxPhy, m_txChannelWidth, max, min, NS_LOG_INFO, NS_TEST_ASSERT_MSG_EQ, ns3::RatioToDb(), and ns3::WToDbm().
Referenced by DoSetup().
SendPpdu()
void SpectrumWifiPhyFilterTest::SendPpdu (void) private
Send PPDU function.
Definition at line 378 of file spectrum-wifi-phy-test.cc.
References m_txChannelWidth, m_txPhy, ns3::WifiPhy::Send(), ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetQosTid(), ns3::WifiMacHeader::SetSequenceNumber(), ns3::WifiMacHeader::SetType(), SU_STA_ID, ns3::WIFI_MAC_QOSDATA, and ns3::WIFI_PREAMBLE_HE_SU.
Referenced by RunOne().
Member Data Documentation
m_rxChannelWidth
uint16_t SpectrumWifiPhyFilterTest::m_rxChannelWidth private
RX channel width (MHz)
Definition at line 362 of file spectrum-wifi-phy-test.cc.
Referenced by DoRun(), RunOne(), and RxCallback().
m_rxPhy
Ptr<ExtSpectrumWifiPhy> SpectrumWifiPhyFilterTest::m_rxPhy private
RX PHY.
Definition at line 359 of file spectrum-wifi-phy-test.cc.
Referenced by ~SpectrumWifiPhyFilterTest(), DoSetup(), RunOne(), and RxCallback().
m_txChannelWidth
uint16_t SpectrumWifiPhyFilterTest::m_txChannelWidth private
TX channel width (MHz)
Definition at line 361 of file spectrum-wifi-phy-test.cc.
Referenced by DoRun(), RunOne(), RxCallback(), and SendPpdu().
m_txPhy
Ptr<ExtSpectrumWifiPhy> SpectrumWifiPhyFilterTest::m_txPhy private
TX PHY.
Definition at line 358 of file spectrum-wifi-phy-test.cc.
Referenced by ~SpectrumWifiPhyFilterTest(), DoSetup(), RunOne(), and SendPpdu().
The documentation for this class was generated from the following file:
src/wifi/test/spectrum-wifi-phy-test.cc