ns-3: LteUplinkPowerControlTestCase Class Reference
LteUplinkPowerControlTestCase Class Reference
LTE Models » lte module tests | Test suites
Lte Uplink Power Control Test Case.
#include "lte-test-uplink-power-control.h"
Public Member Functions
LteUplinkPowerControlTestCase (std::string name)
Constructor.
virtual ~LteUplinkPowerControlTestCase ()
void PucchTxPowerTrace (uint16_t cellId, uint16_t rnti, double txPower)
PUCCH transmit power trace funcction.
void PuschTxPowerTrace (uint16_t cellId, uint16_t rnti, double txPower)
PUSCH transmit power trace funcction.
void SetTpcConfiguration (uint32_t tpc, uint32_t tpcNum, double expectedPuschTxPower, double expectedPucchTxPower, double expectedSrsTxPower)
Set TPC configuration funcction.
void SrsTxPowerTrace (uint16_t cellId, uint16_t rnti, double txPower)
SRS transmit power trace funcction.
void TeleportUe (uint32_t x, uint32_t y, double expectedPuschTxPower, double expectedPucchTxPower, double expectedSrsTxPower)
Teleport UE funcction.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Protected Attributes
bool m_accumulatedMode
indicates whether accumulated mode is being used
double m_expectedPucchTxPower
expected PUCCH transmit power
double m_expectedPuschTxPower
expected PUSCH transmit power
double m_expectedSrsTxPower
expected SRS transmit power
Ptr< LteFfrSimple > m_ffrSimple
FFR simple.
Time m_teleportTime
teleport time
Ptr< MobilityModel > m_ueMobility
UE mobility model.
Ptr< LteUePowerControl > m_ueUpc
UE power control.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Detailed Description
Lte Uplink Power Control Test Case.
Definition at line 50 of file lte-test-uplink-power-control.h.
Constructor & Destructor Documentation
LteUplinkPowerControlTestCase()
LteUplinkPowerControlTestCase::LteUplinkPowerControlTestCase (std::string name)
Constructor.
Parameters
name the reference name
Definition at line 96 of file lte-test-uplink-power-control.cc.
References NS_LOG_INFO.
~LteUplinkPowerControlTestCase()
LteUplinkPowerControlTestCase::~LteUplinkPowerControlTestCase () virtual
Definition at line 102 of file lte-test-uplink-power-control.cc.
Member Function Documentation
DoRun()
void LteUplinkPowerControlTestCase::DoRun (void) protected virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Reimplemented in LteUplinkClosedLoopPowerControlAccumulatedModeTestCase, LteUplinkClosedLoopPowerControlAbsoluteModeTestCase, and LteUplinkOpenLoopPowerControlTestCase.
Definition at line 177 of file lte-test-uplink-power-control.cc.
PucchTxPowerTrace()
void LteUplinkPowerControlTestCase::PucchTxPowerTrace (uint16_t cellId, uint16_t rnti, double txPower)
PUCCH transmit power trace funcction.
Parameters
cellId the cell ID
rnti the RNTI
txPower the transmit power
Definition at line 150 of file lte-test-uplink-power-control.cc.
References m_expectedPucchTxPower, m_teleportTime, ns3::MilliSeconds(), ns3::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and NS_TEST_ASSERT_MSG_EQ_TOL.
Referenced by PucchTxPowerNofitication().
PuschTxPowerTrace()
void LteUplinkPowerControlTestCase::PuschTxPowerTrace (uint16_t cellId, uint16_t rnti, double txPower)
PUSCH transmit power trace funcction.
Parameters
cellId the cell ID
rnti the RNTI
txPower the transmit power
Definition at line 137 of file lte-test-uplink-power-control.cc.
References m_expectedPuschTxPower, m_teleportTime, ns3::MilliSeconds(), ns3::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and NS_TEST_ASSERT_MSG_EQ_TOL.
Referenced by PuschTxPowerNofitication().
SetTpcConfiguration()
void LteUplinkPowerControlTestCase::SetTpcConfiguration (uint32_t tpc, uint32_t tpcNum, double expectedPuschTxPower, double expectedPucchTxPower, double expectedSrsTxPower)
Set TPC configuration funcction.
Parameters
tpc the TPC
tpcNum the TPC number
expectedPuschTxPower the expected PUSCH transmit power
expectedPucchTxPower the expected PUCCH transmit power
expectedSrsTxPower the expected SRS transmit power
Definition at line 122 of file lte-test-uplink-power-control.cc.
References m_accumulatedMode, m_expectedPucchTxPower, m_expectedPuschTxPower, m_expectedSrsTxPower, m_ffrSimple, m_teleportTime, ns3::Now(), NS_LOG_FUNCTION, and ns3::LteFfrSimple::SetTpc().
Referenced by LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), and LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun().
SrsTxPowerTrace()
void LteUplinkPowerControlTestCase::SrsTxPowerTrace (uint16_t cellId, uint16_t rnti, double txPower)
SRS transmit power trace funcction.
Parameters
cellId the cell ID
rnti the RNTI
txPower the transmit power
Definition at line 164 of file lte-test-uplink-power-control.cc.
References m_expectedSrsTxPower, m_teleportTime, ns3::MilliSeconds(), ns3::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and NS_TEST_ASSERT_MSG_EQ_TOL.
Referenced by SrsTxPowerNofitication().
TeleportUe()
void LteUplinkPowerControlTestCase::TeleportUe (uint32_t x, uint32_t y, double expectedPuschTxPower, double expectedPucchTxPower, double expectedSrsTxPower)
Teleport UE funcction.
Parameters
x the X position
y the Y position
expectedPuschTxPower the expected PUSCH transmit power
expectedPucchTxPower the expected PUCCH transmit power
expectedSrsTxPower the expected SRS transmit power
Definition at line 107 of file lte-test-uplink-power-control.cc.
References m_expectedPucchTxPower, m_expectedPuschTxPower, m_expectedSrsTxPower, m_teleportTime, m_ueMobility, ns3::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::MobilityModel::SetPosition(), and sample-rng-plot::x.
Referenced by LteUplinkOpenLoopPowerControlTestCase::DoRun().
Member Data Documentation
m_accumulatedMode
bool LteUplinkPowerControlTestCase::m_accumulatedMode protected
indicates whether accumulated mode is being used
Definition at line 121 of file lte-test-uplink-power-control.h.
Referenced by LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun(), and SetTpcConfiguration().
m_expectedPucchTxPower
double LteUplinkPowerControlTestCase::m_expectedPucchTxPower protected
expected PUCCH transmit power
Definition at line 117 of file lte-test-uplink-power-control.h.
Referenced by PucchTxPowerTrace(), SetTpcConfiguration(), and TeleportUe().
m_expectedPuschTxPower
double LteUplinkPowerControlTestCase::m_expectedPuschTxPower protected
expected PUSCH transmit power
Definition at line 116 of file lte-test-uplink-power-control.h.
Referenced by PuschTxPowerTrace(), SetTpcConfiguration(), and TeleportUe().
m_expectedSrsTxPower
double LteUplinkPowerControlTestCase::m_expectedSrsTxPower protected
expected SRS transmit power
Definition at line 118 of file lte-test-uplink-power-control.h.
Referenced by SetTpcConfiguration(), SrsTxPowerTrace(), and TeleportUe().
m_ffrSimple
Ptr<LteFfrSimple> LteUplinkPowerControlTestCase::m_ffrSimple protected
FFR simple.
Definition at line 123 of file lte-test-uplink-power-control.h.
Referenced by LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun(), and SetTpcConfiguration().
m_teleportTime
Time LteUplinkPowerControlTestCase::m_teleportTime protected
teleport time
Definition at line 114 of file lte-test-uplink-power-control.h.
Referenced by PucchTxPowerTrace(), PuschTxPowerTrace(), SetTpcConfiguration(), SrsTxPowerTrace(), and TeleportUe().
m_ueMobility
Ptr<MobilityModel> LteUplinkPowerControlTestCase::m_ueMobility protected
UE mobility model.
Definition at line 113 of file lte-test-uplink-power-control.h.
Referenced by LteUplinkOpenLoopPowerControlTestCase::DoRun(), LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun(), and TeleportUe().
m_ueUpc
Ptr<LteUePowerControl> LteUplinkPowerControlTestCase::m_ueUpc protected
UE power control.
Definition at line 120 of file lte-test-uplink-power-control.h.
Referenced by LteUplinkOpenLoopPowerControlTestCase::DoRun(), LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), and LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-uplink-power-control.h
src/lte/test/lte-test-uplink-power-control.cc