ns-3: ns3::olsr::OlsrState Class Reference
ns3::olsr::OlsrState Class Reference
OLSR Routing
This class encapsulates all data structures needed for maintaining internal state of an OLSR node.
#include "olsr-state.h"
Public Member Functions
OlsrState ()
void EraseAssociation (const Association &tuple)
Erases an association.
void EraseAssociationTuple (const AssociationTuple &tuple)
Erases a known association tuple.
void EraseDuplicateTuple (const DuplicateTuple &tuple)
Erases a duplicate tuple.
void EraseIfaceAssocTuple (const IfaceAssocTuple &tuple)
Erases a interface association tuple.
void EraseLinkTuple (const LinkTuple &tuple)
Erases a link tuple.
void EraseMprSelectorTuple (const MprSelectorTuple &tuple)
Erases a MPR selector tuple.
void EraseMprSelectorTuples (const Ipv4Address &mainAddr)
Erases all MPR selector tuples belonging to the same address.
void EraseNeighborTuple (const Ipv4Address &mainAddr)
Erases a neighbor tuple.
void EraseNeighborTuple (const NeighborTuple &neighborTuple)
Erases a neighbor tuple.
void EraseOlderTopologyTuples (const Ipv4Address &lastAddr, uint16_t ansn)
Erases a topology tuple.
void EraseTopologyTuple (const TopologyTuple &tuple)
Erases a topology tuple.
void EraseTwoHopNeighborTuple (const TwoHopNeighborTuple &tuple)
Erases a 2-hop neighbor tuple.
void EraseTwoHopNeighborTuples (const Ipv4Address &neighbor)
Erases the 2-hop neighbor tuples with the same 1-hop neighbor.
void EraseTwoHopNeighborTuples (const Ipv4Address &neighbor, const Ipv4Address &twoHopNeighbor)
Erases the 2-hop neighbor tuples with matching predicates.
AssociationTuple * FindAssociationTuple (const Ipv4Address &gatewayAddr, const Ipv4Address &networkAddr, const Ipv4Mask &netmask)
Finds an association tuple.
DuplicateTuple * FindDuplicateTuple (const Ipv4Address &address, uint16_t sequenceNumber)
Finds a duplicate tuple.
IfaceAssocTuple * FindIfaceAssocTuple (const Ipv4Address &ifaceAddr)
Finds a interface association tuple.
const IfaceAssocTuple * FindIfaceAssocTuple (const Ipv4Address &ifaceAddr) const
Finds a interface association tuple.
LinkTuple * FindLinkTuple (const Ipv4Address &ifaceAddr)
Finds a link tuple.
bool FindMprAddress (const Ipv4Address &address)
Checks if there's an MPR with a specific address.
MprSelectorTuple * FindMprSelectorTuple (const Ipv4Address &mainAddr)
Finds a MPR selector tuple.
std::vector< Ipv4Address > FindNeighborInterfaces (const Ipv4Address &neighborMainAddr) const
Returns a vector of all interfaces of a given neighbor, with the exception of the "main" one.
NeighborTuple * FindNeighborTuple (const Ipv4Address &mainAddr)
Finds a neighbor tuple.
NeighborTuple * FindNeighborTuple (const Ipv4Address &mainAddr, uint8_t willingness)
Finds a neighbor tuple.
TopologyTuple * FindNewerTopologyTuple (const Ipv4Address &lastAddr, uint16_t ansn)
Finds a topology tuple.
LinkTuple * FindSymLinkTuple (const Ipv4Address &ifaceAddr, Time time)
Finds a symmetrical link tuple.
const NeighborTuple * FindSymNeighborTuple (const Ipv4Address &mainAddr) const
Finds a symmetrical neighbor tuple.
TopologyTuple * FindTopologyTuple (const Ipv4Address &destAddr, const Ipv4Address &lastAddr)
Finds a topology tuple.
TwoHopNeighborTuple * FindTwoHopNeighborTuple (const Ipv4Address &neighbor, const Ipv4Address &twoHopNeighbor)
Finds a 2-hop neighbor tuple.
const Associations & GetAssociations () const
Gets the association set the node has.
const AssociationSet & GetAssociationSet () const
Gets the association set known to the node.
const IfaceAssocSet & GetIfaceAssocSet () const
Gets the interface association set.
IfaceAssocSet & GetIfaceAssocSetMutable ()
Gets a mutable reference to the interface association set.
const LinkSet & GetLinks () const
Gets the Link set.
const MprSelectorSet & GetMprSelectors () const
Gets the MPR selectors.
MprSet GetMprSet () const
Gets the MPR set.
NeighborSet & GetNeighbors ()
Gets the neighbor set.
const NeighborSet & GetNeighbors () const
Gets the neighbor set.
const TopologySet & GetTopologySet () const
Gets the topology set.
TwoHopNeighborSet & GetTwoHopNeighbors ()
Gets the 2-hop neighbor set.
const TwoHopNeighborSet & GetTwoHopNeighbors () const
Gets the 2-hop neighbor set.
void InsertAssociation (const Association &tuple)
Inserts an association tuple.
void InsertAssociationTuple (const AssociationTuple &tuple)
Inserts a known association tuple.
void InsertDuplicateTuple (const DuplicateTuple &tuple)
Inserts a duplicate tuple.
void InsertIfaceAssocTuple (const IfaceAssocTuple &tuple)
Inserts a interface association tuple.
LinkTuple & InsertLinkTuple (const LinkTuple &tuple)
Inserts a link tuple.
void InsertMprSelectorTuple (const MprSelectorTuple &tuple)
Inserts a MPR selector tuple.
void InsertNeighborTuple (const NeighborTuple &tuple)
Inserts a neighbor tuple.
void InsertTopologyTuple (const TopologyTuple &tuple)
Inserts a topology tuple.
void InsertTwoHopNeighborTuple (const TwoHopNeighborTuple &tuple)
Inserts a 2-hop neighbor tuple.
std::string PrintMprSelectorSet () const
Prints the MPR selector sets.
void SetMprSet (MprSet mprSet)
Sets the MPR set to the one specified.
Protected Attributes
Associations m_associations
The node's local Host Network Associations that will be advertised using HNA messages.
AssociationSet m_associationSet
Association Set (RFC 3626, section12.2).
DuplicateSet m_duplicateSet
Duplicate Set (RFC 3626, section 3.4).
IfaceAssocSet m_ifaceAssocSet
Interface Association Set (RFC 3626, section 4.1).
LinkSet m_linkSet
Link Set (RFC 3626, section 4.2.1).
MprSelectorSet m_mprSelectorSet
MPR Selector Set (RFC 3626, section 4.3.4).
MprSet m_mprSet
MPR Set (RFC 3626, section 4.3.3).
NeighborSet m_neighborSet
Neighbor Set (RFC 3626, section 4.3.1).
TopologySet m_topologySet
Topology Set (RFC 3626, section 4.4).
TwoHopNeighborSet m_twoHopNeighborSet
2-hop Neighbor Set (RFC 3626, section 4.3.2).
Detailed Description
This class encapsulates all data structures needed for maintaining internal state of an OLSR node.
Definition at line 34 of file olsr-state.h.
Constructor & Destructor Documentation
OlsrState()
ns3::olsr::OlsrState::OlsrState () inline
Definition at line 51 of file olsr-state.h.
Member Function Documentation
EraseAssociation()
void ns3::olsr::OlsrState::EraseAssociation (const Association & tuple)
Erases an association.
Parameters
tuple The tuple to erase.
Definition at line 555 of file olsr-state.cc.
References m_associations.
Referenced by ns3::olsr::RoutingProtocol::RemoveHostNetworkAssociation().
EraseAssociationTuple()
void ns3::olsr::OlsrState::EraseAssociationTuple (const AssociationTuple & tuple)
Erases a known association tuple.
Parameters
tuple The tuple to erase.
Definition at line 535 of file olsr-state.cc.
References m_associationSet.
Referenced by ns3::olsr::RoutingProtocol::RemoveAssociationTuple().
EraseDuplicateTuple()
void ns3::olsr::OlsrState::EraseDuplicateTuple (const DuplicateTuple & tuple)
Erases a duplicate tuple.
Parameters
tuple The tuple to erase.
Definition at line 308 of file olsr-state.cc.
References m_duplicateSet.
Referenced by ns3::olsr::RoutingProtocol::RemoveDuplicateTuple().
EraseIfaceAssocTuple()
void ns3::olsr::OlsrState::EraseIfaceAssocTuple (const IfaceAssocTuple & tuple)
Erases a interface association tuple.
Parameters
tuple The tuple to erase.
Definition at line 484 of file olsr-state.cc.
References m_ifaceAssocSet.
Referenced by ns3::olsr::RoutingProtocol::RemoveIfaceAssocTuple().
EraseLinkTuple()
void ns3::olsr::OlsrState::EraseLinkTuple (const LinkTuple & tuple)
Erases a link tuple.
Parameters
tuple The tuple to erase.
Definition at line 365 of file olsr-state.cc.
References m_linkSet.
Referenced by ns3::olsr::RoutingProtocol::RemoveLinkTuple().
EraseMprSelectorTuple()
void ns3::olsr::OlsrState::EraseMprSelectorTuple (const MprSelectorTuple & tuple)
Erases a MPR selector tuple.
Parameters
tuple The MPR selector tuple.
Definition at line 52 of file olsr-state.cc.
References m_mprSelectorSet.
Referenced by ns3::olsr::RoutingProtocol::RemoveMprSelectorTuple().
EraseMprSelectorTuples()
void ns3::olsr::OlsrState::EraseMprSelectorTuples (const Ipv4Address & mainAddr)
Erases all MPR selector tuples belonging to the same address.
Parameters
mainAddr The MPR selector main address.
Definition at line 66 of file olsr-state.cc.
References m_mprSelectorSet.
Referenced by ns3::olsr::RoutingProtocol::NeighborLoss().
EraseNeighborTuple() [1/2]
void ns3::olsr::OlsrState::EraseNeighborTuple (const Ipv4Address & mainAddr)
Erases a neighbor tuple.
Parameters
mainAddr The neighbor tuple main address.
Definition at line 168 of file olsr-state.cc.
References m_neighborSet.
EraseNeighborTuple() [2/2]
void ns3::olsr::OlsrState::EraseNeighborTuple (const NeighborTuple & neighborTuple)
Erases a neighbor tuple.
Parameters
neighborTuple The neighbor tuple.
Definition at line 154 of file olsr-state.cc.
References m_neighborSet.
Referenced by ns3::olsr::RoutingProtocol::RemoveLinkTuple(), and ns3::olsr::RoutingProtocol::RemoveNeighborTuple().
EraseOlderTopologyTuples()
void ns3::olsr::OlsrState::EraseOlderTopologyTuples (const Ipv4Address & lastAddr, uint16_t ansn)
Erases a topology tuple.
Parameters
lastAddr The address of the node previous to the destination.
ansn The Advertised Neighbor Sequence Number.
Definition at line 431 of file olsr-state.cc.
References m_topologySet.
Referenced by ns3::olsr::RoutingProtocol::ProcessTc().
EraseTopologyTuple()
void ns3::olsr::OlsrState::EraseTopologyTuple (const TopologyTuple & tuple)
Erases a topology tuple.
Parameters
tuple The tuple to erase.
Definition at line 417 of file olsr-state.cc.
References m_topologySet.
Referenced by ns3::olsr::RoutingProtocol::RemoveTopologyTuple().
EraseTwoHopNeighborTuple()
void ns3::olsr::OlsrState::EraseTwoHopNeighborTuple (const TwoHopNeighborTuple & tuple)
Erases a 2-hop neighbor tuple.
Parameters
tuple The 2-hop neighbor tuple.
Definition at line 216 of file olsr-state.cc.
References m_twoHopNeighborSet.
Referenced by ns3::olsr::RoutingProtocol::RemoveTwoHopNeighborTuple().
EraseTwoHopNeighborTuples() [1/2]
void ns3::olsr::OlsrState::EraseTwoHopNeighborTuples (const Ipv4Address & neighbor)
Erases the 2-hop neighbor tuples with the same 1-hop neighbor.
Parameters
neighbor The neighbor address.
Definition at line 249 of file olsr-state.cc.
References m_twoHopNeighborSet.
Referenced by ns3::olsr::RoutingProtocol::NeighborLoss(), and ns3::olsr::RoutingProtocol::PopulateTwoHopNeighborSet().
EraseTwoHopNeighborTuples() [2/2]
void ns3::olsr::OlsrState::EraseTwoHopNeighborTuples (const Ipv4Address & neighbor, const Ipv4Address & twoHopNeighbor)
Erases the 2-hop neighbor tuples with matching predicates.
Parameters
neighbor The neighbor address.
twoHopNeighbor The 2-hop neighbor main address.
Definition at line 230 of file olsr-state.cc.
References m_twoHopNeighborSet.
FindAssociationTuple()
AssociationTuple * ns3::olsr::OlsrState::FindAssociationTuple (const Ipv4Address & gatewayAddr, const Ipv4Address & networkAddr, const Ipv4Mask & netmask)
Finds an association tuple.
Parameters
gatewayAddr The gateway address.
networkAddr The network address.
netmask The network mask.
Returns
The association tuple, or a null pointer if no match.
Definition at line 521 of file olsr-state.cc.
References m_associationSet.
Referenced by ns3::olsr::RoutingProtocol::AssociationTupleTimerExpire(), and ns3::olsr::RoutingProtocol::ProcessHna().
FindDuplicateTuple()
DuplicateTuple * ns3::olsr::OlsrState::FindDuplicateTuple (const Ipv4Address & address, uint16_t sequenceNumber)
Finds a duplicate tuple.
Parameters
address The duplicate tuple address.
sequenceNumber The duplicate tuple sequence number.
Returns
The duplicate tuple, or a null pointer if no match.
Definition at line 294 of file olsr-state.cc.
References m_duplicateSet.
Referenced by ns3::olsr::RoutingProtocol::DupTupleTimerExpire(), and ns3::olsr::RoutingProtocol::RecvOlsr().
FindIfaceAssocTuple() [1/2]
IfaceAssocTuple * ns3::olsr::OlsrState::FindIfaceAssocTuple (const Ipv4Address & ifaceAddr)
Finds a interface association tuple.
Parameters
ifaceAddr The interface address.
Returns
The interface association tuple, or a null pointer if no match.
Definition at line 456 of file olsr-state.cc.
References m_ifaceAssocSet.
Referenced by ns3::olsr::RoutingProtocol::GetMainAddress(), and ns3::olsr::RoutingProtocol::IfaceAssocTupleTimerExpire().
FindIfaceAssocTuple() [2/2]
const IfaceAssocTuple * ns3::olsr::OlsrState::FindIfaceAssocTuple (const Ipv4Address & ifaceAddr) const
Finds a interface association tuple.
Parameters
ifaceAddr The interface address.
Returns
The interface association tuple, or a null pointer if no match.
Definition at line 470 of file olsr-state.cc.
References m_ifaceAssocSet.
FindLinkTuple()
LinkTuple * ns3::olsr::OlsrState::FindLinkTuple (const Ipv4Address & ifaceAddr)
Finds a link tuple.
Parameters
ifaceAddr The interface address of the link.
Returns
The link tuple, or a null pointer if no match.
Definition at line 330 of file olsr-state.cc.
References m_linkSet.
Referenced by ns3::olsr::RoutingProtocol::LinkSensing(), and ns3::olsr::RoutingProtocol::LinkTupleTimerExpire().
FindMprAddress()
bool ns3::olsr::OlsrState::FindMprAddress (const Ipv4Address & address)
Checks if there's an MPR with a specific address.
Parameters
address The address to test.
Returns
True if a MPR with the specified address exists.
Definition at line 274 of file olsr-state.cc.
References m_mprSet.
Referenced by ns3::olsr::RoutingProtocol::SendHello().
FindMprSelectorTuple()
MprSelectorTuple * ns3::olsr::OlsrState::FindMprSelectorTuple (const Ipv4Address & mainAddr)
Finds a MPR selector tuple.
Parameters
mainAddr The MPR selector main address.
Returns
The MPR selector, if found. Else it returns a null pointer.
Definition at line 38 of file olsr-state.cc.
References m_mprSelectorSet.
Referenced by ns3::olsr::RoutingProtocol::ForwardDefault(), ns3::olsr::RoutingProtocol::MprSelTupleTimerExpire(), and ns3::olsr::RoutingProtocol::PopulateMprSelectorSet().
FindNeighborInterfaces()
std::vector< Ipv4Address > ns3::olsr::OlsrState::FindNeighborInterfaces (const Ipv4Address & neighborMainAddr) const
Returns a vector of all interfaces of a given neighbor, with the exception of the "main" one.
Parameters
neighborMainAddr The neighbor main address
Returns
A container of the neighbor addresses (excluding the main one).
Definition at line 504 of file olsr-state.cc.
References m_ifaceAssocSet.
Referenced by ns3::olsr::RoutingProtocol::SendHello().
FindNeighborTuple() [1/2]
NeighborTuple * ns3::olsr::OlsrState::FindNeighborTuple (const Ipv4Address & mainAddr)
Finds a neighbor tuple.
Parameters
mainAddr The neighbor tuple main address.
Returns
The neighbor tuple, if found. Else it returns a null pointer.
Definition at line 112 of file olsr-state.cc.
References m_neighborSet.
Referenced by ns3::olsr::RoutingProtocol::Degree(), ns3::olsr::RoutingProtocol::LinkTupleUpdated(), and ns3::olsr::RoutingProtocol::PopulateNeighborSet().
FindNeighborTuple() [2/2]
NeighborTuple * ns3::olsr::OlsrState::FindNeighborTuple (const Ipv4Address & mainAddr, uint8_t willingness)
Finds a neighbor tuple.
Parameters
mainAddr The neighbor tuple main address.
willingness The neighbor willingness.
Returns
The neighbor tuple, if found. Else it returns a null pointer.
Definition at line 140 of file olsr-state.cc.
References m_neighborSet.
FindNewerTopologyTuple()
TopologyTuple * ns3::olsr::OlsrState::FindNewerTopologyTuple (const Ipv4Address & lastAddr, uint16_t ansn)
Finds a topology tuple.
Parameters
lastAddr The address of the node previous to the destination.
ansn The Advertised Neighbor Sequence Number.
Returns
The topology tuple, or a null pointer if no match.
Definition at line 403 of file olsr-state.cc.
References m_topologySet.
Referenced by ns3::olsr::RoutingProtocol::ProcessTc().
FindSymLinkTuple()
LinkTuple * ns3::olsr::OlsrState::FindSymLinkTuple (const Ipv4Address & ifaceAddr, Time time)
Finds a symmetrical link tuple.
Parameters
ifaceAddr The interface address of the link.
time The time at which the link should be considered symmetrical.
Returns
The link tuple, or a null pointer if no match.
Definition at line 344 of file olsr-state.cc.
References m_linkSet.
Referenced by ns3::olsr::RoutingProtocol::ForwardDefault(), ns3::olsr::RoutingProtocol::ProcessHna(), ns3::olsr::RoutingProtocol::ProcessMid(), and ns3::olsr::RoutingProtocol::ProcessTc().
FindSymNeighborTuple()
const NeighborTuple * ns3::olsr::OlsrState::FindSymNeighborTuple (const Ipv4Address & mainAddr) const
Finds a symmetrical neighbor tuple.
Parameters
mainAddr The neighbor tuple main address.
Returns
The neighbor tuple, if found. Else it returns a null pointer.
Definition at line 126 of file olsr-state.cc.
References m_neighborSet, and ns3::olsr::NeighborTuple::STATUS_SYM.
Referenced by ns3::olsr::RoutingProtocol::RoutingTableComputation().
FindTopologyTuple()
TopologyTuple * ns3::olsr::OlsrState::FindTopologyTuple (const Ipv4Address & destAddr, const Ipv4Address & lastAddr)
Finds a topology tuple.
Parameters
destAddr The destination address.
lastAddr The address of the node previous to the destination.
Returns
The topology tuple, or a null pointer if no match.
Definition at line 388 of file olsr-state.cc.
References m_topologySet.
Referenced by ns3::olsr::RoutingProtocol::ProcessTc(), and ns3::olsr::RoutingProtocol::TopologyTupleTimerExpire().
FindTwoHopNeighborTuple()
TwoHopNeighborTuple * ns3::olsr::OlsrState::FindTwoHopNeighborTuple (const Ipv4Address & neighbor, const Ipv4Address & twoHopNeighbor)
Finds a 2-hop neighbor tuple.
Parameters
neighbor The neighbor main address.
twoHopNeighbor The 2-hop neighbor main address.
Returns
The 2-hop neighbor tuple, if found. Else it returns a null pointer.
Definition at line 200 of file olsr-state.cc.
References m_twoHopNeighborSet.
Referenced by ns3::olsr::RoutingProtocol::Nb2hopTupleTimerExpire(), and ns3::olsr::RoutingProtocol::PopulateTwoHopNeighborSet().
GetAssociations()
const Associations& ns3::olsr::OlsrState::GetAssociations () const inline
Gets the association set the node has.
Returns
The association set the node has.
Definition at line 385 of file olsr-state.h.
References m_associations.
Referenced by ns3::olsr::RoutingProtocol::AddHostNetworkAssociation(), ns3::olsr::RoutingProtocol::HnaTimerExpire(), ns3::olsr::RoutingProtocol::RoutingTableComputation(), ns3::olsr::RoutingProtocol::SendHna(), and ns3::olsr::RoutingProtocol::SetRoutingTableAssociation().
GetAssociationSet()
const AssociationSet& ns3::olsr::OlsrState::GetAssociationSet () const inline
Gets the association set known to the node.
Returns
The association set known to the node.
Definition at line 376 of file olsr-state.h.
References m_associationSet.
Referenced by ns3::olsr::RoutingProtocol::RoutingTableComputation().
GetIfaceAssocSet()
const IfaceAssocSet& ns3::olsr::OlsrState::GetIfaceAssocSet () const inline
Gets the interface association set.
Returns
The interface association set.
Definition at line 335 of file olsr-state.h.
References m_ifaceAssocSet.
Referenced by ns3::olsr::RoutingProtocol::RoutingTableComputation().
GetIfaceAssocSetMutable()
IfaceAssocSet& ns3::olsr::OlsrState::GetIfaceAssocSetMutable () inline
Gets a mutable reference to the interface association set.
Returns
The interface association set.
Definition at line 343 of file olsr-state.h.
References m_ifaceAssocSet.
Referenced by ns3::olsr::RoutingProtocol::ProcessMid().
GetLinks()
const LinkSet& ns3::olsr::OlsrState::GetLinks () const inline
Gets the Link set.
Returns
The Link set.
Definition at line 256 of file olsr-state.h.
References m_linkSet.
Referenced by ns3::olsr::RoutingProtocol::LinkTupleUpdated(), ns3::olsr::RoutingProtocol::PopulateTwoHopNeighborSet(), ns3::olsr::RoutingProtocol::ProcessHello(), ns3::olsr::RoutingProtocol::RoutingTableComputation(), and ns3::olsr::RoutingProtocol::SendHello().
GetMprSelectors()
const MprSelectorSet& ns3::olsr::OlsrState::GetMprSelectors (void) const inline
Gets the MPR selectors.
Returns
The MPR selectors.
Definition at line 61 of file olsr-state.h.
References m_mprSelectorSet.
Referenced by ns3::olsr::RoutingProtocol::GetMprSelectors(), ns3::olsr::RoutingProtocol::SendTc(), and ns3::olsr::RoutingProtocol::TcTimerExpire().
GetMprSet()
MprSet ns3::olsr::OlsrState::GetMprSet (void) const
Gets the MPR set.
Returns
The MPR set.
Definition at line 286 of file olsr-state.cc.
References m_mprSet.
Referenced by ns3::olsr::RoutingProtocol::GetMprSet().
GetNeighbors() [1/2]
NeighborSet& ns3::olsr::OlsrState::GetNeighbors (void) inline
Gets the neighbor set.
Returns
The neighbor set.
Definition at line 111 of file olsr-state.h.
References m_neighborSet.
GetNeighbors() [2/2]
const NeighborSet& ns3::olsr::OlsrState::GetNeighbors (void) const inline
Gets the neighbor set.
Returns
The neighbor set.
Definition at line 103 of file olsr-state.h.
References m_neighborSet.
Referenced by ns3::olsr::RoutingProtocol::Dump(), ns3::olsr::RoutingProtocol::GetNeighbors(), ns3::olsr::RoutingProtocol::MprComputation(), ns3::olsr::RoutingProtocol::ProcessHello(), ns3::olsr::RoutingProtocol::ProcessMid(), ns3::olsr::RoutingProtocol::RoutingTableComputation(), and ns3::olsr::RoutingProtocol::SendHello().
GetTopologySet()
const TopologySet& ns3::olsr::OlsrState::GetTopologySet (void) const inline
Gets the topology set.
Returns
The topology set.
Definition at line 291 of file olsr-state.h.
References m_topologySet.
Referenced by ns3::olsr::RoutingProtocol::GetTopologySet(), ns3::olsr::RoutingProtocol::ProcessTc(), and ns3::olsr::RoutingProtocol::RoutingTableComputation().
GetTwoHopNeighbors() [1/2]
TwoHopNeighborSet& ns3::olsr::OlsrState::GetTwoHopNeighbors (void) inline
Gets the 2-hop neighbor set.
Returns
The 2-hop neighbor set.
Definition at line 170 of file olsr-state.h.
References m_twoHopNeighborSet.
GetTwoHopNeighbors() [2/2]
const TwoHopNeighborSet& ns3::olsr::OlsrState::GetTwoHopNeighbors (void) const inline
Gets the 2-hop neighbor set.
Returns
The 2-hop neighbor set.
Definition at line 162 of file olsr-state.h.
References m_twoHopNeighborSet.
Referenced by ns3::olsr::RoutingProtocol::Degree(), ns3::olsr::RoutingProtocol::Dump(), ns3::olsr::RoutingProtocol::GetTwoHopNeighbors(), ns3::olsr::RoutingProtocol::MprComputation(), ns3::olsr::RoutingProtocol::ProcessHello(), ns3::olsr::RoutingProtocol::ProcessMid(), and ns3::olsr::RoutingProtocol::RoutingTableComputation().
InsertAssociation()
void ns3::olsr::OlsrState::InsertAssociation (const Association & tuple)
Inserts an association tuple.
Parameters
tuple The tuple to insert.
Definition at line 569 of file olsr-state.cc.
References m_associations.
Referenced by ns3::olsr::RoutingProtocol::AddHostNetworkAssociation().
InsertAssociationTuple()
void ns3::olsr::OlsrState::InsertAssociationTuple (const AssociationTuple & tuple)
Inserts a known association tuple.
Parameters
tuple The tuple to insert.
Definition at line 549 of file olsr-state.cc.
References m_associationSet.
Referenced by ns3::olsr::RoutingProtocol::AddAssociationTuple().
InsertDuplicateTuple()
void ns3::olsr::OlsrState::InsertDuplicateTuple (const DuplicateTuple & tuple)
Inserts a duplicate tuple.
Parameters
tuple The tuple to insert.
Definition at line 322 of file olsr-state.cc.
References m_duplicateSet.
Referenced by ns3::olsr::RoutingProtocol::AddDuplicateTuple().
InsertIfaceAssocTuple()
void ns3::olsr::OlsrState::InsertIfaceAssocTuple (const IfaceAssocTuple & tuple)
Inserts a interface association tuple.
Parameters
tuple The tuple to insert.
Definition at line 498 of file olsr-state.cc.
References m_ifaceAssocSet.
Referenced by ns3::olsr::RoutingProtocol::AddIfaceAssocTuple().
InsertLinkTuple()
LinkTuple & ns3::olsr::OlsrState::InsertLinkTuple (const LinkTuple & tuple)
Inserts a link tuple.
Parameters
tuple The tuple to insert.
Returns
A reference to the inserted tuple.
Definition at line 379 of file olsr-state.cc.
References m_linkSet.
Referenced by ns3::olsr::RoutingProtocol::LinkSensing().
InsertMprSelectorTuple()
void ns3::olsr::OlsrState::InsertMprSelectorTuple (const MprSelectorTuple & tuple)
Inserts a MPR selector tuple.
Parameters
tuple The MPR selector tuple.
Definition at line 83 of file olsr-state.cc.
References m_mprSelectorSet.
Referenced by ns3::olsr::RoutingProtocol::AddMprSelectorTuple().
InsertNeighborTuple()
void ns3::olsr::OlsrState::InsertNeighborTuple (const NeighborTuple & tuple)
Inserts a neighbor tuple.
Parameters
tuple The neighbor tuple.
Definition at line 182 of file olsr-state.cc.
References m_neighborSet, and ns3::olsr::NeighborTuple::neighborMainAddr.
Referenced by ns3::olsr::RoutingProtocol::AddNeighborTuple().
InsertTopologyTuple()
void ns3::olsr::OlsrState::InsertTopologyTuple (const TopologyTuple & tuple)
Inserts a topology tuple.
Parameters
tuple The tuple to insert.
Definition at line 448 of file olsr-state.cc.
References m_topologySet.
Referenced by ns3::olsr::RoutingProtocol::AddTopologyTuple().
InsertTwoHopNeighborTuple()
void ns3::olsr::OlsrState::InsertTwoHopNeighborTuple (const TwoHopNeighborTuple & tuple)
Inserts a 2-hop neighbor tuple.
Parameters
tuple The 2-hop neighbor tuple.
Definition at line 266 of file olsr-state.cc.
References m_twoHopNeighborSet.
Referenced by ns3::olsr::RoutingProtocol::AddTwoHopNeighborTuple().
PrintMprSelectorSet()
std::string ns3::olsr::OlsrState::PrintMprSelectorSet () const
Prints the MPR selector sets.
Returns
a string with the output data.
Definition at line 89 of file olsr-state.cc.
References m_mprSelectorSet.
Referenced by ns3::olsr::RoutingProtocol::PopulateMprSelectorSet().
SetMprSet()
void ns3::olsr::OlsrState::SetMprSet (MprSet mprSet)
Sets the MPR set to the one specified.
Parameters
mprSet The new MPR set.
Definition at line 281 of file olsr-state.cc.
References m_mprSet.
Referenced by ns3::olsr::RoutingProtocol::MprComputation().
Member Data Documentation
m_associations
Associations ns3::olsr::OlsrState::m_associations protected
The node's local Host Network Associations that will be advertised using HNA messages.
Definition at line 48 of file olsr-state.h.
Referenced by EraseAssociation(), GetAssociations(), and InsertAssociation().
m_associationSet
AssociationSet ns3::olsr::OlsrState::m_associationSet protected
Association Set (RFC 3626, section12.2).
Associations obtained from HNA messages generated by other nodes.
Definition at line 47 of file olsr-state.h.
Referenced by EraseAssociationTuple(), FindAssociationTuple(), GetAssociationSet(), and InsertAssociationTuple().
m_duplicateSet
DuplicateSet ns3::olsr::OlsrState::m_duplicateSet protected
Duplicate Set (RFC 3626, section 3.4).
Definition at line 45 of file olsr-state.h.
Referenced by EraseDuplicateTuple(), FindDuplicateTuple(), and InsertDuplicateTuple().
m_ifaceAssocSet
IfaceAssocSet ns3::olsr::OlsrState::m_ifaceAssocSet protected
Interface Association Set (RFC 3626, section 4.1).
Definition at line 46 of file olsr-state.h.
Referenced by EraseIfaceAssocTuple(), FindIfaceAssocTuple(), FindNeighborInterfaces(), GetIfaceAssocSet(), GetIfaceAssocSetMutable(), and InsertIfaceAssocTuple().
m_linkSet
LinkSet ns3::olsr::OlsrState::m_linkSet protected
Link Set (RFC 3626, section 4.2.1).
Definition at line 39 of file olsr-state.h.
Referenced by EraseLinkTuple(), FindLinkTuple(), FindSymLinkTuple(), GetLinks(), and InsertLinkTuple().
m_mprSelectorSet
MprSelectorSet ns3::olsr::OlsrState::m_mprSelectorSet protected
MPR Selector Set (RFC 3626, section 4.3.4).
Definition at line 44 of file olsr-state.h.
Referenced by EraseMprSelectorTuple(), EraseMprSelectorTuples(), FindMprSelectorTuple(), GetMprSelectors(), InsertMprSelectorTuple(), and PrintMprSelectorSet().
m_mprSet
MprSet ns3::olsr::OlsrState::m_mprSet protected
MPR Set (RFC 3626, section 4.3.3).
Definition at line 43 of file olsr-state.h.
Referenced by FindMprAddress(), GetMprSet(), and SetMprSet().
m_neighborSet
NeighborSet ns3::olsr::OlsrState::m_neighborSet protected
Neighbor Set (RFC 3626, section 4.3.1).
Definition at line 40 of file olsr-state.h.
Referenced by EraseNeighborTuple(), FindNeighborTuple(), FindSymNeighborTuple(), GetNeighbors(), and InsertNeighborTuple().
m_topologySet
TopologySet ns3::olsr::OlsrState::m_topologySet protected
Topology Set (RFC 3626, section 4.4).
Definition at line 42 of file olsr-state.h.
Referenced by EraseOlderTopologyTuples(), EraseTopologyTuple(), FindNewerTopologyTuple(), FindTopologyTuple(), GetTopologySet(), and InsertTopologyTuple().
m_twoHopNeighborSet
TwoHopNeighborSet ns3::olsr::OlsrState::m_twoHopNeighborSet protected
2-hop Neighbor Set (RFC 3626, section 4.3.2).
Definition at line 41 of file olsr-state.h.
Referenced by EraseTwoHopNeighborTuple(), EraseTwoHopNeighborTuples(), FindTwoHopNeighborTuple(), GetTwoHopNeighbors(), and InsertTwoHopNeighborTuple().
The documentation for this class was generated from the following files:
src/olsr/model/olsr-state.h
src/olsr/model/olsr-state.cc