ns-3: ns3::TcpDctcp Class Reference
ns3::TcpDctcp Class Reference
Internet » TCP
An implementation of DCTCP.
#include "tcp-dctcp.h"
Public Types
typedef void(* CongestionEstimateTracedCallback) (uint32_t bytesAcked, uint32_t bytesMarked, double alpha)
TracedCallback signature for DCTCP update of congestion state.
Public Member Functions
TcpDctcp ()
Create an unbound tcp socket.
TcpDctcp (const TcpDctcp &sock)
Copy constructor.
virtual ~TcpDctcp (void)
Destructor.
virtual void CwndEvent (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCAEvent_t event)
Trigger events/calculations on occurrence of congestion window event.
virtual Ptr< TcpCongestionOps > Fork ()
Copy the congestion control algorithm across sockets.
virtual std::string GetName () const
Get the name of the congestion control algorithm.
virtual uint32_t GetSsThresh (Ptr< const TcpSocketState > tcb, uint32_t bytesInFlight)
Get the slow start threshold after a loss event.
virtual void Init (Ptr< TcpSocketState > tcb)
Set configuration required by congestion control algorithm, This method will force DctcpEcn mode and will force usage of either ECT(0) or ECT(1) (depending on the 'UseEct0' attribute), despite any other configuration in the base classes.
virtual void PktsAcked (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked, const Time &rtt)
Timing information on received ACK.
Public Member Functions inherited from ns3::TcpLinuxReno
TcpLinuxReno ()
TcpLinuxReno (const TcpLinuxReno &sock)
Copy constructor.
~TcpLinuxReno ()
std::string GetName () const
Get the name of the congestion control algorithm.
virtual void IncreaseWindow (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
Congestion avoidance algorithm implementation.
Public Member Functions inherited from ns3::TcpCongestionOps
TcpCongestionOps ()
TcpCongestionOps (const TcpCongestionOps &other)
Copy constructor.
virtual ~TcpCongestionOps ()
virtual void CongControl (Ptr< TcpSocketState > tcb, const TcpRateOps::TcpRateConnection &rc, const TcpRateOps::TcpRateSample &rs)
Called when packets are delivered to update cwnd and pacing rate.
virtual void CongestionStateSet (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCongState_t newState)
Trigger events/calculations specific to a congestion state.
virtual bool HasCongControl () const
Returns true when Congestion Control Algorithm implements CongControl.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpLinuxReno
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpCongestionOps
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void CeState0to1 (Ptr< TcpSocketState > tcb)
Changes state of m_ceState to true.
void CeState1to0 (Ptr< TcpSocketState > tcb)
Changes state of m_ceState to false.
void InitializeDctcpAlpha (double alpha)
Initialize the value of m_alpha.
void Reset (Ptr< TcpSocketState > tcb)
Resets the value of m_ackedBytesEcn, m_ackedBytesTotal and m_nextSeq.
void UpdateAckReserved (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCAEvent_t event)
Updates the value of m_delayedAckReserved.
Private Attributes
uint32_t m_ackedBytesEcn
Number of acked bytes which are marked.
uint32_t m_ackedBytesTotal
Total number of acked bytes.
double m_alpha
Parameter used to estimate the amount of network congestion.
bool m_ceState
DCTCP Congestion Experienced state.
bool m_delayedAckReserved
Delayed Ack state.
double m_g
Estimation gain.
bool m_initialized
Whether DCTCP has been initialized.
SequenceNumber32 m_nextSeq
TCP sequence number threshold for beginning a new observation window.
bool m_nextSeqFlag
Variable used in setting the value of m_nextSeq for first time.
SequenceNumber32 m_priorRcvNxt
Sequence number of the first missing byte in data.
bool m_priorRcvNxtFlag
Variable used in setting the value of m_priorRcvNxt for first time.
TracedCallback< uint32_t, uint32_t, double > m_traceCongestionEstimate
Callback pointer for congestion state update.
bool m_useEct0
Use ECT(0) for ECN codepoint.
Additional Inherited Members
Protected Member Functions inherited from ns3::TcpLinuxReno
virtual void CongestionAvoidance (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
virtual uint32_t SlowStart (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
An implementation of DCTCP.
This model implements all of the endpoint capabilities mentioned in the DCTCP SIGCOMM paper.
Config Paths
ns3::TcpDctcp is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::TcpL4Protocol/SocketList/[i]/CongestionOps/$ns3::TcpLinuxReno/$ns3::TcpDctcp"
"/NodeList/[i]/$ns3::TcpL4Protocol/SocketList/[i]/CongestionOps/$ns3::TcpDctcp"
Attributes
DctcpShiftG: Parameter G for updating dctcp_alpha
Set with class: ns3::DoubleValue
Underlying type: double 0:1
Initial value: 0.0625
Flags: construct write read
DctcpAlphaOnInit: Initial alpha value
Set with class: ns3::DoubleValue
Underlying type: double 0:1
Initial value: 1
Flags: construct write
UseEct0: Use ECT(0) for ECN codepoint, if false use ECT(1)
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
TraceSources
CongestionEstimate: Update sender-side congestion estimate state
Callback signature: ns3::TcpDctcp::CongestionEstimateTracedCallback
Size of this type is 104 bytes (on a 64-bit architecture).
Definition at line 38 of file tcp-dctcp.h.
Member Typedef Documentation
CongestionEstimateTracedCallback
typedef void(* ns3::TcpDctcp::CongestionEstimateTracedCallback) (uint32_t bytesAcked, uint32_t bytesMarked, double alpha)
TracedCallback signature for DCTCP update of congestion state.
Parameters
[in] bytesAcked Bytes acked in this observation window
[in] bytesMarked Bytes marked in this observation window
[in] alpha New alpha (congestion estimate) value
Definition at line 83 of file tcp-dctcp.h.
Constructor & Destructor Documentation
TcpDctcp() [1/2]
ns3::TcpDctcp::TcpDctcp ()
Create an unbound tcp socket.
Definition at line 67 of file tcp-dctcp.cc.
References NS_LOG_FUNCTION.
TcpDctcp() [2/2]
ns3::TcpDctcp::TcpDctcp (const TcpDctcp & sock)
Copy constructor.
Parameters
sock the object to copy
Definition at line 82 of file tcp-dctcp.cc.
References NS_LOG_FUNCTION.
~TcpDctcp()
ns3::TcpDctcp::~TcpDctcp (void) virtual
Destructor.
Definition at line 100 of file tcp-dctcp.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CeState0to1()
void ns3::TcpDctcp::CeState0to1 (Ptr< TcpSocketState > tcb) private
Changes state of m_ceState to true.
Parameters
tcb internal congestion state
Definition at line 178 of file tcp-dctcp.cc.
References ns3::TcpHeader::ACK, ns3::TcpSocketState::ECN_CE_RCVD, m_ceState, m_delayedAckReserved, ns3::TcpSocketState::m_ecnState, m_priorRcvNxt, m_priorRcvNxtFlag, ns3::TcpSocketState::m_rxBuffer, ns3::TcpSocketState::m_sendEmptyPacketCallback, and NS_LOG_FUNCTION.
Referenced by CwndEvent().
CeState1to0()
void ns3::TcpDctcp::CeState1to0 (Ptr< TcpSocketState > tcb) private
Changes state of m_ceState to false.
Parameters
tcb internal congestion state
Definition at line 205 of file tcp-dctcp.cc.
References ns3::TcpHeader::ACK, ns3::TcpHeader::ECE, ns3::TcpSocketState::ECN_CE_RCVD, ns3::TcpSocketState::ECN_IDLE, ns3::TcpSocketState::ECN_SENDING_ECE, m_ceState, m_delayedAckReserved, ns3::TcpSocketState::m_ecnState, m_priorRcvNxt, m_priorRcvNxtFlag, ns3::TcpSocketState::m_rxBuffer, ns3::TcpSocketState::m_sendEmptyPacketCallback, and NS_LOG_FUNCTION.
Referenced by CwndEvent().
CwndEvent()
void ns3::TcpDctcp::CwndEvent (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCAEvent_t event) virtual
Trigger events/calculations on occurrence of congestion window event.
This function mimics the function cwnd_event in Linux. The function is called in case of congestion window events.
Parameters
tcb internal congestion state
event the event which triggered this function
Reimplemented from ns3::TcpCongestionOps.
Definition at line 261 of file tcp-dctcp.cc.
References ns3::TcpSocketState::CA_EVENT_DELAYED_ACK, ns3::TcpSocketState::CA_EVENT_ECN_IS_CE, ns3::TcpSocketState::CA_EVENT_ECN_NO_CE, ns3::TcpSocketState::CA_EVENT_NON_DELAYED_ACK, CeState0to1(), CeState1to0(), NS_LOG_FUNCTION, and UpdateAckReserved().
Fork()
Ptr< TcpCongestionOps > ns3::TcpDctcp::Fork () virtual
Copy the congestion control algorithm across sockets.
Returns
a pointer of the copied object
Reimplemented from ns3::TcpLinuxReno.
Definition at line 105 of file tcp-dctcp.cc.
References NS_LOG_FUNCTION.
GetName()
std::string ns3::TcpDctcp::GetName () const virtual
Get the name of the congestion control algorithm.
Returns
A string identifying the name
Implements ns3::TcpCongestionOps.
Definition at line 62 of file tcp-dctcp.cc.
GetSsThresh()
uint32_t ns3::TcpDctcp::GetSsThresh (Ptr< const TcpSocketState > tcb, uint32_t bytesInFlight) virtual
Get the slow start threshold after a loss event.
Is guaranteed that the congestion control state (TcpAckState_t) is changed BEFORE the invocation of this method. The implementator should return the slow start threshold (and not change it directly) because, in the future, the TCP implementation may require to instantly recover from a loss event (e.g. when there is a network with an high reordering factor).
Parameters
tcb internal congestion state
bytesInFlight total bytes in flight
Returns
Slow start threshold
Reimplemented from ns3::TcpLinuxReno.
Definition at line 126 of file tcp-dctcp.cc.
References m_alpha, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::TcpDctcp::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 33 of file tcp-dctcp.cc.
References InitializeDctcpAlpha(), m_g, m_traceCongestionEstimate, m_useEct0, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeDoubleAccessor(), ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
Init()
void ns3::TcpDctcp::Init (Ptr< TcpSocketState > tcb) virtual
Set configuration required by congestion control algorithm, This method will force DctcpEcn mode and will force usage of either ECT(0) or ECT(1) (depending on the 'UseEct0' attribute), despite any other configuration in the base classes.
Parameters
tcb internal congestion state
Reimplemented from ns3::TcpCongestionOps.
Definition at line 112 of file tcp-dctcp.cc.
References ns3::TcpSocketState::DctcpEcn, ns3::TcpSocketState::Ect0, ns3::TcpSocketState::Ect1, ns3::TcpSocketState::m_ecnMode, ns3::TcpSocketState::m_ectCodePoint, m_initialized, ns3::TcpSocketState::m_useEcn, m_useEct0, NS_LOG_FUNCTION, NS_LOG_INFO, and ns3::TcpSocketState::On.
InitializeDctcpAlpha()
void ns3::TcpDctcp::InitializeDctcpAlpha (double alpha) private
Initialize the value of m_alpha.
Parameters
alpha DCTCP alpha parameter
Definition at line 161 of file tcp-dctcp.cc.
References sample-rng-plot::alpha, m_alpha, m_initialized, NS_ABORT_MSG_IF, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
PktsAcked()
void ns3::TcpDctcp::PktsAcked (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked, const Time & rtt) virtual
Timing information on received ACK.
The function is called every time an ACK is received (only one time also for cumulative ACKs) and contains timing information. It is optional (congestion controls need not implement it) and the default implementation does nothing.
Parameters
tcb internal congestion state
segmentsAcked count of segments acked
rtt last rtt
Reimplemented from ns3::TcpCongestionOps.
Definition at line 133 of file tcp-dctcp.cc.
References ns3::TcpSocketState::ECN_ECE_RCVD, m_ackedBytesEcn, m_ackedBytesTotal, m_alpha, ns3::TcpSocketState::m_ecnState, m_g, ns3::TcpSocketState::m_lastAckedSeq, m_nextSeq, m_nextSeqFlag, ns3::TcpSocketState::m_nextTxSequence, ns3::TcpSocketState::m_segmentSize, m_traceCongestionEstimate, NS_LOG_FUNCTION, NS_LOG_INFO, and Reset().
Reset()
void ns3::TcpDctcp::Reset (Ptr< TcpSocketState > tcb) private
Resets the value of m_ackedBytesEcn, m_ackedBytesTotal and m_nextSeq.
Parameters
tcb internal congestion state
Definition at line 169 of file tcp-dctcp.cc.
References m_ackedBytesEcn, m_ackedBytesTotal, m_nextSeq, ns3::TcpSocketState::m_nextTxSequence, and NS_LOG_FUNCTION.
Referenced by PktsAcked().
UpdateAckReserved()
void ns3::TcpDctcp::UpdateAckReserved (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCAEvent_t event) private
Updates the value of m_delayedAckReserved.
Parameters
tcb internal congestion state
event the congestion window event
Definition at line 236 of file tcp-dctcp.cc.
References ns3::TcpSocketState::CA_EVENT_DELAYED_ACK, ns3::TcpSocketState::CA_EVENT_NON_DELAYED_ACK, m_delayedAckReserved, and NS_LOG_FUNCTION.
Referenced by CwndEvent().
Member Data Documentation
m_ackedBytesEcn
uint32_t ns3::TcpDctcp::m_ackedBytesEcn private
Number of acked bytes which are marked.
Definition at line 131 of file tcp-dctcp.h.
Referenced by PktsAcked(), and Reset().
m_ackedBytesTotal
uint32_t ns3::TcpDctcp::m_ackedBytesTotal private
Total number of acked bytes.
Definition at line 132 of file tcp-dctcp.h.
Referenced by PktsAcked(), and Reset().
m_alpha
double ns3::TcpDctcp::m_alpha private
Parameter used to estimate the amount of network congestion.
Definition at line 135 of file tcp-dctcp.h.
Referenced by GetSsThresh(), InitializeDctcpAlpha(), and PktsAcked().
m_ceState
bool ns3::TcpDctcp::m_ceState private
DCTCP Congestion Experienced state.
Definition at line 138 of file tcp-dctcp.h.
Referenced by CeState0to1(), and CeState1to0().
m_delayedAckReserved
bool ns3::TcpDctcp::m_delayedAckReserved private
Delayed Ack state.
Definition at line 139 of file tcp-dctcp.h.
Referenced by CeState0to1(), CeState1to0(), and UpdateAckReserved().
m_g
double ns3::TcpDctcp::m_g private
Estimation gain.
Definition at line 140 of file tcp-dctcp.h.
Referenced by GetTypeId(), and PktsAcked().
m_initialized
bool ns3::TcpDctcp::m_initialized private
Whether DCTCP has been initialized.
Definition at line 142 of file tcp-dctcp.h.
Referenced by Init(), and InitializeDctcpAlpha().
m_nextSeq
SequenceNumber32 ns3::TcpDctcp::m_nextSeq private
TCP sequence number threshold for beginning a new observation window.
Definition at line 136 of file tcp-dctcp.h.
Referenced by PktsAcked(), and Reset().
m_nextSeqFlag
bool ns3::TcpDctcp::m_nextSeqFlag private
Variable used in setting the value of m_nextSeq for first time.
Definition at line 137 of file tcp-dctcp.h.
Referenced by PktsAcked().
m_priorRcvNxt
SequenceNumber32 ns3::TcpDctcp::m_priorRcvNxt private
Sequence number of the first missing byte in data.
Definition at line 133 of file tcp-dctcp.h.
Referenced by CeState0to1(), and CeState1to0().
m_priorRcvNxtFlag
bool ns3::TcpDctcp::m_priorRcvNxtFlag private
Variable used in setting the value of m_priorRcvNxt for first time.
Definition at line 134 of file tcp-dctcp.h.
Referenced by CeState0to1(), and CeState1to0().
m_traceCongestionEstimate
TracedCallback<uint32_t, uint32_t, double> ns3::TcpDctcp::m_traceCongestionEstimate private
Callback pointer for congestion state update.
Definition at line 146 of file tcp-dctcp.h.
Referenced by GetTypeId(), and PktsAcked().
m_useEct0
bool ns3::TcpDctcp::m_useEct0 private
Use ECT(0) for ECN codepoint.
Definition at line 141 of file tcp-dctcp.h.
Referenced by GetTypeId(), and Init().
The documentation for this class was generated from the following files:
src/internet/model/tcp-dctcp.h
src/internet/model/tcp-dctcp.cc