ns-3: ns3::Txop Class Reference
ns3::Txop Class Reference
Wifi Models
Handle packet fragmentation and retransmissions for data and management frames.
#include "txop.h"
Public Types
typedef Callback< void, Ptr< const Packet > > TxDropped
typedef for a callback to invoke when a packet is dropped.
typedef Callback< void, const WifiMacHeader & > TxFailed
typedef for a callback to invoke when a packet transmission was failed.
typedef Callback< void, const WifiMacHeader & > TxOk
typedef for a callback to invoke when a packet transmission was completed successfully.
Public Member Functions
Txop ()
virtual ~Txop ()
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
virtual void Cancel (void)
Cancel the transmission.
bool CanStartNextPolling (void) const
Check if the next PCF transmission can fit in the remaining CFP duration.
virtual void EndTxNoAck (void)
Event handler when a transmission that does not require an Ack has completed.
uint8_t GetAifsn (void) const
Return the number of slots that make up an AIFS.
Ptr< MacLow > GetLow (void) const
Return the MacLow associated with this Txop.
uint32_t GetMaxCw (void) const
Return the maximum contention window size.
uint32_t GetMinCw (void) const
Return the minimum contention window size.
Time GetTxopLimit (void) const
Return the TXOP limit.
virtual Time GetTxopRemaining (void) const
Return the remaining duration in the current TXOP.
Ptr< WifiMacQueue > GetWifiMacQueue () const
Return the packet queue associated with this Txop.
virtual void GotAck (void)
Event handler when an Ack is received.
virtual void GotBlockAck (const CtrlBAckResponseHeader *blockAck, Mac48Address recipient, double rxSnr, double dataSnr, WifiTxVector dataTxVector)
Event handler when a BlockAck is received.
void GotCfEnd (void)
Event handler when a CF-END frame is received.
virtual bool IsAccessRequested (void) const
virtual bool IsQosTxop () const
Check for QoS TXOP.
virtual void MissedAck (void)
Event handler when an Ack is missed.
virtual void MissedBlockAck (uint8_t nMpdus)
Event handler when a BlockAck timeout has occurred.
void MissedCfPollResponse (bool expectedCfAck)
Event handler when a response to a CF-POLL frame is missed.
virtual void MissedCts (void)
Event handler when a CTS timeout has occurred.
virtual void NotifyChannelSwitching (void)
When a channel switching occurs, enqueued packets are removed.
virtual void NotifyOff (void)
When off operation occurs, the queue gets cleaned up.
virtual void NotifyOn (void)
When on operation occurs, channel access will be started.
virtual void NotifySleep (void)
When sleep operation occurs, if there is a pending packet transmission, it will be reinserted to the front of the queue.
virtual void NotifyWakeUp (void)
When wake up operation occurs, channel access will be restarted.
virtual void Queue (Ptr< Packet > packet, const WifiMacHeader &hdr)
void SendCfFrame (WifiMacType frameType, Mac48Address addr)
Sends CF frame to STA with address addr.
void SetAifsn (uint8_t aifsn)
Set the number of slots that make up an AIFS.
void SetChannelAccessManager (const Ptr< ChannelAccessManager > manager)
Set ChannelAccessManager this Txop is associated to.
void SetMacLow (const Ptr< MacLow > low)
Set MacLow associated with this Txop.
void SetMaxCw (uint32_t maxCw)
Set the maximum contention window size.
void SetMinCw (uint32_t minCw)
Set the minimum contention window size.
void SetTxDroppedCallback (TxDropped callback)
void SetTxFailedCallback (TxFailed callback)
void SetTxMiddle (const Ptr< MacTxMiddle > txMiddle)
Set MacTxMiddle this Txop is associated to.
void SetTxOkCallback (TxOk callback)
void SetTxopLimit (Time txopLimit)
Set the TXOP limit.
virtual void SetWifiRemoteStationManager (const Ptr< WifiRemoteStationManager > remoteManager)
Set WifiRemoteStationsManager this Txop is associated to.
void StartBackoffNow (uint32_t nSlots)
virtual void StartNextFragment (void)
Start transmission for the next fragment.
virtual void StartNextPacket (void)
Start transmission for the next packet if allowed by the TxopLimit.
virtual void TerminateTxop (void)
Update backoff and restart access if needed.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void GenerateBackoff (void)
Generate a new backoff now.
uint32_t GetBackoffSlots (void) const
Return the current number of backoff slots.
Time GetBackoffStart (void) const
Return the time when the backoff procedure started.
uint32_t GetCw (void) const
virtual uint32_t GetFragmentOffset (void) const
Calculate the offset for the current fragment.
virtual Ptr< Packet > GetFragmentPacket (WifiMacHeader *hdr)
Get the next fragment from the packet with appropriate Wifi header for the fragment.
virtual uint32_t GetFragmentSize (void) const
Calculate the size of the current fragment.
virtual uint32_t GetNextFragmentSize (void) const
Calculate the size of the next fragment.
virtual bool HasFramesToTransmit (void)
Check if the Txop has frames to transmit.
virtual bool IsLastFragment (void) const
Check if the current fragment is the last fragment.
bool NeedDataRetransmission (Ptr< const Packet > packet, const WifiMacHeader &hdr)
Check if Data should be re-transmitted if Ack was missed.
virtual bool NeedFragmentation (void) const
Check if the current packet should be fragmented.
bool NeedRtsRetransmission (Ptr< const Packet > packet, const WifiMacHeader &hdr)
Check if RTS should be re-transmitted if CTS was missed.
void NextFragment (void)
Continue to the next fragment.
virtual void NotifyAccessGranted (void)
Notify the Txop that access has been granted.
virtual void NotifyAccessRequested (void)
Notify that access request has been received.
virtual void NotifyInternalCollision (void)
Notify the Txop that internal collision has occurred.
void ResetCw (void)
Update the value of the CW variable to take into account a transmission success or a transmission abort (stop transmission of a packet after the maximum number of retransmissions has been reached).
virtual void RestartAccessIfNeeded (void)
Restart access request if needed.
virtual void StartAccessIfNeeded (void)
Request access from Txop if needed.
void TxDroppedPacket (Ptr< const WifiMacQueueItem > item)
Pass the packet included in the wifi MAC queue item to the packet dropped callback.
void UpdateBackoffSlotsNow (uint32_t nSlots, Time backoffUpdateBound)
Update backoff slots that nSlots has passed.
void UpdateFailedCw (void)
Update the value of the CW variable to take into account a transmission failure.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes
bool m_accessRequested
flag whether channel access is already requested
uint8_t m_aifsn
the AIFSN
uint32_t m_backoff
the current backoff
uint32_t m_backoffSlots
the number of backoff slots
Time m_backoffStart
the backoffStart variable is used to keep track of the time at which a backoff was started or the time at which the backoff counter was last updated.
TracedCallback< uint32_t > m_backoffTrace
backoff trace value
Ptr< ChannelAccessManager > m_channelAccessManager
the channel access manager
WifiMacHeader m_currentHdr
the current header
Ptr< const Packet > m_currentPacket
the current packet
MacLowTransmissionParameters m_currentParams
current transmission parameters
uint32_t m_cw
the current contention window
uint32_t m_cwMax
the maximum contention window
uint32_t m_cwMin
the minimum contention window
TracedValue< uint32_t > m_cwTrace
CW trace value.
uint8_t m_fragmentNumber
the fragment number
Ptr< MacLow > m_low
the MacLow
Ptr< WifiMacQueue > m_queue
the wifi MAC queue
Ptr< UniformRandomVariable > m_rng
the random stream
Ptr< WifiRemoteStationManager > m_stationManager
the wifi remote station manager
TxDropped m_txDroppedCallback
the packet dropped callback
TxFailed m_txFailedCallback
the transmit failed callback
Ptr< MacTxMiddle > m_txMiddle
the MacTxMiddle
TxOk m_txOkCallback
the transmit OK callback
Time m_txopLimit
the TXOP limit time
Friends
class ChannelAccessManager
< ChannelAccessManager associated class
class MacLowTransmissionListener
allow MacLowTransmissionListener class access
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Handle packet fragmentation and retransmissions for data and management frames.
This class implements the packet fragmentation and retransmission policy for data and management frames. It uses the ns3::MacLow and ns3::ChannelAccessManager helper classes to respectively send packets and decide when to send them. Packets are stored in a ns3::WifiMacQueue until they can be sent.
The policy currently implemented uses a simple fragmentation threshold: any packet bigger than this threshold is fragmented in fragments whose size is smaller than the threshold.
The retransmission policy is also very simple: every packet is retransmitted until it is either successfully transmitted or it has been retransmitted up until the SSRC or SLRC thresholds.
The RTS/CTS policy is similar to the fragmentation policy: when a packet is bigger than a threshold, the RTS/CTS protocol is used.
Config Paths
ns3::Txop is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Mac/$ns3::RegularWifiMac/Txop"
Attributes
MinCw: The minimum value of the contention window.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 15
Flags: construct write read
MaxCw: The maximum value of the contention window.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 1023
Flags: construct write read
Aifsn: The AIFSN: the default value conforms to non-QOS.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Initial value: 2
Flags: construct write read
TxopLimit: The TXOP limit: the default value conforms to non-QoS.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
Queue: The WifiMacQueue object
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::WifiMacQueue>
Flags: read
TraceSources
BackoffTrace: Trace source for backoff values
Callback signature: ns3::TracedCallback::Uint32Callback
CwTrace: Trace source for contention window values
Callback signature: ns3::TracedValueCallback::Uint32
Size of this type is 296 bytes (on a 64-bit architecture).
Definition at line 66 of file txop.h.
Member Typedef Documentation
TxDropped
typedef Callback<void, Ptr<const Packet> > ns3::Txop::TxDropped
typedef for a callback to invoke when a packet is dropped.
Definition at line 95 of file txop.h.
TxFailed
typedef Callback<void, const WifiMacHeader&> ns3::Txop::TxFailed
typedef for a callback to invoke when a packet transmission was failed.
Definition at line 90 of file txop.h.
TxOk
typedef Callback<void, const WifiMacHeader&> ns3::Txop::TxOk
typedef for a callback to invoke when a packet transmission was completed successfully.
Definition at line 85 of file txop.h.
Constructor & Destructor Documentation
Txop()
ns3::Txop::Txop ()
Definition at line 86 of file txop.cc.
References m_queue, m_rng, and NS_LOG_FUNCTION.
~Txop()
ns3::Txop::~Txop () virtual
Definition at line 102 of file txop.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AssignStreams()
int64_t ns3::Txop::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use.
Returns
the number of stream indices assigned by this model.
Definition at line 332 of file txop.cc.
References m_rng, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
Referenced by ns3::MeshHelper::AssignStreams(), ns3::WaveHelper::AssignStreams(), ns3::WifiHelper::AssignStreams(), and AssignWifiRandomStreams().
Cancel()
void ns3::Txop::Cancel (void) virtual
Cancel the transmission.
Definition at line 760 of file txop.cc.
References NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by ns3::MacLow::CancelAllEvents().
CanStartNextPolling()
bool ns3::Txop::CanStartNextPolling (void) const
Check if the next PCF transmission can fit in the remaining CFP duration.
Returns
true if the next PCF transmission can fit in the remaining CFP duration, false otherwise
Definition at line 855 of file txop.cc.
References GetLow(), ns3::ChannelAccessManager::IsBusy(), and m_channelAccessManager.
Referenced by ns3::ApWifiMac::SendNextCfFrame().
DoDispose()
void ns3::Txop::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Reimplemented in ns3::QosTxop.
Definition at line 108 of file txop.cc.
References m_channelAccessManager, m_low, m_queue, m_rng, m_stationManager, m_txMiddle, and NS_LOG_FUNCTION.
Referenced by ns3::QosTxop::DoDispose().
DoInitialize()
void ns3::Txop::DoInitialize (void) protected virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Reimplemented in ns3::QosTxop.
Definition at line 372 of file txop.cc.
References GenerateBackoff(), GetCw(), m_cwTrace, NS_LOG_FUNCTION, and ResetCw().
EndTxNoAck()
void ns3::Txop::EndTxNoAck (void) virtual
Event handler when a transmission that does not require an Ack has completed.
Reimplemented in ns3::QosTxop.
Definition at line 767 of file txop.cc.
References GenerateBackoff(), GetCw(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_currentHdr, m_currentPacket, m_cwTrace, m_txOkCallback, NS_LOG_DEBUG, NS_LOG_FUNCTION, ResetCw(), and StartAccessIfNeeded().
Referenced by ns3::MacLow::EndTxNoAck().
GenerateBackoff()
void ns3::Txop::GenerateBackoff (void) protected virtual
Generate a new backoff now.
Definition at line 553 of file txop.cc.
References GetCw(), ns3::UniformRandomVariable::GetInteger(), m_backoff, m_backoffTrace, m_rng, NS_LOG_FUNCTION, and StartBackoffNow().
Referenced by ns3::QosTxop::AddBaResponseTimeout(), ns3::QosTxop::DoInitialize(), DoInitialize(), EndTxNoAck(), GotAck(), ns3::QosTxop::MissedAck(), MissedAck(), ns3::QosTxop::MissedBlockAck(), MissedCts(), ns3::QosTxop::NotifyInternalCollision(), NotifyInternalCollision(), ns3::QosTxop::NotifyMissedCts(), Queue(), and ns3::QosTxop::TerminateTxop().
GetAifsn()
uint8_t ns3::Txop::GetAifsn (void) const
Return the number of slots that make up an AIFS.
Returns
the number of slots that make up an AIFS.
Definition at line 297 of file txop.cc.
References m_aifsn.
Referenced by ns3::ChannelAccessManager::GetBackoffStartFor(), ns3::ApWifiMac::GetEdcaParameterSet(), GetTypeId(), ns3::ChannelAccessManager::NeedBackoffUponAccess(), and ns3::ChannelAccessManager::RequestAccess().
GetBackoffSlots()
uint32_t ns3::Txop::GetBackoffSlots (void) const protected
Return the current number of backoff slots.
Returns
the current number of backoff slots
Definition at line 233 of file txop.cc.
References m_backoffSlots.
Referenced by ns3::ChannelAccessManager::DoGrantDcfAccess(), ns3::ChannelAccessManager::GetBackoffEndFor(), and ns3::ChannelAccessManager::NeedBackoffUponAccess().
GetBackoffStart()
Time ns3::Txop::GetBackoffStart (void) const protected
Return the time when the backoff procedure started.
Returns
the time when the backoff procedure started
Definition at line 239 of file txop.cc.
References m_backoffStart.
Referenced by ns3::ChannelAccessManager::GetBackoffStartFor(), and ns3::ChannelAccessManager::RequestAccess().
GetCw()
uint32_t ns3::Txop::GetCw (void) const protected
Returns
the current value of the CW variable. The initial value is minCW.
Definition at line 212 of file txop.cc.
References m_cw.
Referenced by ns3::QosTxop::DoInitialize(), DoInitialize(), EndTxNoAck(), GenerateBackoff(), GotAck(), ns3::QosTxop::MissedAck(), MissedAck(), ns3::QosTxop::MissedBlockAck(), MissedCts(), ns3::QosTxop::NotifyMissedCts(), SetMaxCw(), and SetMinCw().
GetFragmentOffset()
uint32_t ns3::Txop::GetFragmentOffset (void) const protected virtual
Calculate the offset for the current fragment.
Returns
the offset for the current fragment in bytes.
Reimplemented in ns3::QosTxop.
Definition at line 434 of file txop.cc.
References ns3::WifiMacHeader::GetAddr1(), ns3::WifiRemoteStationManager::GetFragmentOffset(), m_currentHdr, m_currentPacket, m_fragmentNumber, m_stationManager, and NS_LOG_FUNCTION.
Referenced by GetFragmentPacket().
GetFragmentPacket()
Ptr< Packet > ns3::Txop::GetFragmentPacket (WifiMacHeader * hdr) protected virtual
Get the next fragment from the packet with appropriate Wifi header for the fragment.
Parameters
hdr Wi-Fi header.
Returns
the fragment with the current fragment number.
Reimplemented in ns3::QosTxop.
Definition at line 442 of file txop.cc.
References GetFragmentOffset(), GetFragmentSize(), IsLastFragment(), m_currentHdr, m_currentPacket, m_fragmentNumber, NS_LOG_FUNCTION, ns3::WifiMacHeader::SetFragmentNumber(), ns3::WifiMacHeader::SetMoreFragments(), and ns3::WifiMacHeader::SetNoMoreFragments().
Referenced by NotifyAccessGranted(), and StartNextFragment().
GetFragmentSize()
uint32_t ns3::Txop::GetFragmentSize (void) const protected virtual
Calculate the size of the current fragment.
Returns
the size of the current fragment in bytes.
Reimplemented in ns3::QosTxop.
Definition at line 410 of file txop.cc.
References ns3::WifiMacHeader::GetAddr1(), ns3::WifiRemoteStationManager::GetFragmentSize(), m_currentHdr, m_currentPacket, m_fragmentNumber, m_stationManager, and NS_LOG_FUNCTION.
Referenced by GetFragmentPacket().
GetLow()
Ptr< MacLow > ns3::Txop::GetLow (void) const
Return the MacLow associated with this Txop.
Returns
the associated MacLow
Definition at line 366 of file txop.cc.
References m_low.
Referenced by CanStartNextPolling(), AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), PreservePacketsInAmpdus::DoRun(), HeAggregationTest::DoRunSubTest(), ns3::MpduAggregator::GetMaxAmpduSize(), ns3::MsduAggregator::GetMaxAmsduSize(), ns3::MsduAggregator::GetNextAmsdu(), ns3::QosTxop::GetTxopFragmentSize(), ns3::ChannelAccessManager::NeedBackoffUponAccess(), ns3::QosTxop::NeedFragmentation(), NotifyAccessGranted(), ns3::QosTxop::SetupBlockAckIfNeeded(), StartNextFragment(), and ns3::QosTxop::StartNextPacket().
GetMaxCw()
uint32_t ns3::Txop::GetMaxCw (void) const
Return the maximum contention window size.
Returns
the maximum contention window size.
Definition at line 291 of file txop.cc.
References m_cwMax.
Referenced by ns3::ApWifiMac::GetEdcaParameterSet(), and GetTypeId().
GetMinCw()
uint32_t ns3::Txop::GetMinCw (void) const
Return the minimum contention window size.
Returns
the minimum contention window size.
Definition at line 285 of file txop.cc.
References m_cwMin.
Referenced by ns3::ApWifiMac::GetEdcaParameterSet(), and GetTypeId().
GetNextFragmentSize()
uint32_t ns3::Txop::GetNextFragmentSize (void) const protected virtual
Calculate the size of the next fragment.
Returns
the size of the next fragment in bytes.
Reimplemented in ns3::QosTxop.
Definition at line 426 of file txop.cc.
References ns3::WifiMacHeader::GetAddr1(), ns3::WifiRemoteStationManager::GetFragmentSize(), m_currentHdr, m_currentPacket, m_fragmentNumber, m_stationManager, and NS_LOG_FUNCTION.
Referenced by NotifyAccessGranted(), and StartNextFragment().
GetTxopLimit()
Time ns3::Txop::GetTxopLimit (void) const
Return the TXOP limit.
Returns
the TXOP limit.
Definition at line 303 of file txop.cc.
References m_txopLimit.
Referenced by TwoLevelAggregationTest::DoRun(), ns3::ApWifiMac::GetEdcaParameterSet(), ns3::QosTxop::GetTxopFragmentSize(), ns3::QosTxop::GetTxopRemaining(), GetTypeId(), ns3::QosTxop::IsTxopFragmentation(), ns3::QosTxop::NeedFragmentation(), ns3::QosTxop::NotifyAccessGranted(), ns3::MacLow::ReceiveOk(), ns3::MacLow::StartDataTxTimers(), ns3::QosTxop::StartNextPacket(), ns3::MacLow::StartTransmission(), ns3::QosTxop::TerminateTxop(), and ns3::ConstantWifiAckPolicySelector::UpdateTxParams().
GetTxopRemaining()
Time ns3::Txop::GetTxopRemaining (void) const virtual
Return the remaining duration in the current TXOP.
Returns
the remaining duration in the current TXOP.
Reimplemented in ns3::QosTxop.
Definition at line 885 of file txop.cc.
References NS_LOG_WARN, and ns3::Seconds().
Referenced by ns3::MacLow::ReceiveOk(), ns3::MacLow::StartDataTxTimers(), and ns3::MacLow::StartTransmission().
GetTypeId()
TypeId ns3::Txop::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 44 of file txop.cc.
References GetAifsn(), GetMaxCw(), GetMinCw(), GetTxopLimit(), GetWifiMacQueue(), m_backoffTrace, m_cwTrace, ns3::MakePointerAccessor(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), ns3::MilliSeconds(), SetAifsn(), SetMaxCw(), SetMinCw(), ns3::TypeId::SetParent(), and SetTxopLimit().
GetWifiMacQueue()
Ptr< WifiMacQueue > ns3::Txop::GetWifiMacQueue () const
Return the packet queue associated with this Txop.
Returns
the associated WifiMacQueue
Definition at line 179 of file txop.cc.
References m_queue, and NS_LOG_FUNCTION.
Referenced by AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), HeAggregationTest::DoRunSubTest(), ns3::MsduAggregator::GetNextAmsdu(), and GetTypeId().
GotAck()
void ns3::Txop::GotAck (void) virtual
Event handler when an Ack is received.
Reimplemented in ns3::QosTxop.
Definition at line 638 of file txop.cc.
References GenerateBackoff(), GetCw(), IsLastFragment(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_currentHdr, m_currentPacket, m_cwTrace, m_txOkCallback, NeedFragmentation(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ResetCw(), and RestartAccessIfNeeded().
Referenced by ns3::MacLow::ReceiveOk().
GotBlockAck()
void ns3::Txop::GotBlockAck (const CtrlBAckResponseHeader * blockAck, Mac48Address recipient, double rxSnr, double dataSnr, WifiTxVector dataTxVector) virtual
Event handler when a BlockAck is received.
Parameters
blockAck BlockAck header.
recipient address of the recipient.
rxSnr SNR of the BlockAck itself in linear scale.
dataSnr reported data SNR from the peer in linear scale.
dataTxVector TXVECTOR used to send the Data.
Reimplemented in ns3::QosTxop.
Definition at line 873 of file txop.cc.
References NS_LOG_WARN.
Referenced by ns3::MacLow::ReceiveOk().
GotCfEnd()
void ns3::Txop::GotCfEnd (void)
Event handler when a CF-END frame is received.
Definition at line 698 of file txop.cc.
References m_currentPacket, NS_LOG_FUNCTION, RestartAccessIfNeeded(), and StartAccessIfNeeded().
Referenced by ns3::MacLow::ReceiveOk().
HasFramesToTransmit()
bool ns3::Txop::HasFramesToTransmit (void) protected virtual
Check if the Txop has frames to transmit.
Returns
true if the Txop has frames to transmit.
Reimplemented in ns3::QosTxop.
Definition at line 309 of file txop.cc.
References m_currentPacket, m_queue, and NS_LOG_FUNCTION.
Referenced by ns3::ChannelAccessManager::NeedBackoffUponAccess().
IsAccessRequested()
bool ns3::Txop::IsAccessRequested (void) const virtual
Returns
true if access has been requested for this function and has not been granted already, false otherwise.
Definition at line 463 of file txop.cc.
References m_accessRequested.
Referenced by ns3::ChannelAccessManager::DoGrantDcfAccess(), ns3::ChannelAccessManager::RequestAccess(), ns3::QosTxop::RestartAccessIfNeeded(), RestartAccessIfNeeded(), ns3::QosTxop::StartAccessIfNeeded(), and StartAccessIfNeeded().
IsLastFragment()
bool ns3::Txop::IsLastFragment (void) const protected virtual
Check if the current fragment is the last fragment.
Returns
true if the current fragment is the last fragment, false otherwise.
Reimplemented in ns3::QosTxop.
Definition at line 418 of file txop.cc.
References ns3::WifiMacHeader::GetAddr1(), ns3::WifiRemoteStationManager::IsLastFragment(), m_currentHdr, m_currentPacket, m_fragmentNumber, m_stationManager, and NS_LOG_FUNCTION.
Referenced by GetFragmentPacket(), GotAck(), NotifyAccessGranted(), and StartNextFragment().
IsQosTxop()
bool ns3::Txop::IsQosTxop (void) const virtual
Check for QoS TXOP.
Returns
true if QoS TXOP.
Reimplemented in ns3::QosTxop.
Definition at line 861 of file txop.cc.
Referenced by ns3::ChannelAccessManager::NeedBackoffUponAccess(), ns3::MacLow::ReceiveOk(), ns3::ChannelAccessManager::RequestAccess(), and ns3::MacLow::StartDataTxTimers().
MissedAck()
void ns3::Txop::MissedAck (void) virtual
Event handler when an Ack is missed.
Reimplemented in ns3::QosTxop.
Definition at line 666 of file txop.cc.
References GenerateBackoff(), ns3::WifiMacHeader::GetAddr1(), GetCw(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_currentHdr, m_currentPacket, m_cwTrace, m_stationManager, m_txFailedCallback, NeedDataRetransmission(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::WifiRemoteStationManager::ReportDataFailed(), ns3::WifiRemoteStationManager::ReportFinalDataFailed(), ResetCw(), RestartAccessIfNeeded(), ns3::WifiMacHeader::SetRetry(), and UpdateFailedCw().
Referenced by ns3::MacLow::NormalAckTimeout(), ns3::MacLow::ReceiveError(), and ns3::MacLow::ReceiveOk().
MissedBlockAck()
void ns3::Txop::MissedBlockAck (uint8_t nMpdus) virtual
Event handler when a BlockAck timeout has occurred.
Parameters
nMpdus the number of MPDUs sent in the A-MPDU transmission that results in a BlockAck timeout.
Reimplemented in ns3::QosTxop.
Definition at line 879 of file txop.cc.
References NS_LOG_WARN.
Referenced by ns3::MacLow::BlockAckTimeout().
MissedCfPollResponse()
void ns3::Txop::MissedCfPollResponse (bool expectedCfAck)
Event handler when a response to a CF-POLL frame is missed.
Parameters
expectedCfAck flag to indicate whether a CF-Ack was expected in the response.
Definition at line 712 of file txop.cc.
References ns3::WifiMacHeader::GetAddr1(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_currentHdr, m_currentPacket, m_stationManager, m_txFailedCallback, NeedDataRetransmission(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::WifiRemoteStationManager::ReportFinalDataFailed(), and ns3::WifiMacHeader::SetRetry().
Referenced by ns3::MacLow::CfPollTimeout(), and ns3::MacLow::ReceiveError().
MissedCts()
void ns3::Txop::MissedCts (void) virtual
Event handler when a CTS timeout has occurred.
Definition at line 611 of file txop.cc.
References GenerateBackoff(), ns3::WifiMacHeader::GetAddr1(), GetCw(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_currentHdr, m_currentPacket, m_cwTrace, m_stationManager, m_txFailedCallback, NeedRtsRetransmission(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::WifiRemoteStationManager::ReportFinalRtsFailed(), ResetCw(), RestartAccessIfNeeded(), and UpdateFailedCw().
Referenced by ns3::MacLow::CtsTimeout().
NeedDataRetransmission()
bool ns3::Txop::NeedDataRetransmission (Ptr< const Packet > packet, const WifiMacHeader & hdr) protected
Check if Data should be re-transmitted if Ack was missed.
Parameters
packet current packet being transmitted.
hdr current header being transmitted.
Returns
true if Data should be re-transmitted, false otherwise.
Definition at line 388 of file txop.cc.
References ns3::WifiMacHeader::GetAddr1(), m_stationManager, ns3::WifiRemoteStationManager::NeedRetransmission(), and NS_LOG_FUNCTION.
Referenced by ns3::QosTxop::MissedAck(), MissedAck(), ns3::QosTxop::MissedBlockAck(), MissedCfPollResponse(), ns3::QosTxop::NotifyInternalCollision(), and SendCfFrame().
NeedFragmentation()
bool ns3::Txop::NeedFragmentation (void) const protected virtual
Check if the current packet should be fragmented.
Returns
true if the current packet should be fragmented, false otherwise
Reimplemented in ns3::QosTxop.
Definition at line 395 of file txop.cc.
References ns3::WifiMacHeader::GetAddr1(), m_currentHdr, m_currentPacket, m_stationManager, ns3::WifiRemoteStationManager::NeedFragmentation(), and NS_LOG_FUNCTION.
Referenced by GotAck(), and NotifyAccessGranted().
NeedRtsRetransmission()
bool ns3::Txop::NeedRtsRetransmission (Ptr< const Packet > packet, const WifiMacHeader & hdr) protected
Check if RTS should be re-transmitted if CTS was missed.
Parameters
packet current packet being transmitted.
hdr current header being transmitted.
Returns
true if RTS should be re-transmitted, false otherwise.
Definition at line 381 of file txop.cc.
References ns3::WifiMacHeader::GetAddr1(), m_stationManager, ns3::WifiRemoteStationManager::NeedRetransmission(), and NS_LOG_FUNCTION.
Referenced by MissedCts(), ns3::QosTxop::NotifyInternalCollision(), and ns3::QosTxop::NotifyMissedCts().
NextFragment()
void ns3::Txop::NextFragment (void) protected
Continue to the next fragment.
This method simply increments the internal variable that keep track of the current fragment number.
Definition at line 403 of file txop.cc.
References m_fragmentNumber, and NS_LOG_FUNCTION.
Referenced by StartNextFragment().
NotifyAccessGranted()
void ns3::Txop::NotifyAccessGranted (void) protected virtual
Notify the Txop that access has been granted.
Reimplemented in ns3::QosTxop.
Definition at line 476 of file txop.cc.
References ns3::MacLowTransmissionParameters::DisableAck(), ns3::MacLowTransmissionParameters::DisableNextData(), ns3::MacLowTransmissionParameters::DisableRts(), ns3::MacLowTransmissionParameters::EnableAck(), ns3::MacLowTransmissionParameters::EnableNextData(), ns3::MacLowTransmissionParameters::EnableRts(), ns3::WifiMacHeader::GetAddr1(), GetFragmentPacket(), GetLow(), GetNextFragmentSize(), ns3::WifiMacHeader::GetSequenceControl(), ns3::Packet::GetSize(), ns3::WifiMacHeader::GetSize(), ns3::Mac48Address::IsGroup(), IsLastFragment(), m_accessRequested, m_currentHdr, m_currentPacket, m_currentParams, m_fragmentNumber, m_low, m_queue, m_stationManager, m_txMiddle, NeedFragmentation(), ns3::WifiRemoteStationManager::NeedRts(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::WifiMacHeader::SetFragmentNumber(), ns3::WifiMacHeader::SetNoMoreFragments(), ns3::WifiMacHeader::SetNoRetry(), ns3::WifiMacHeader::SetSequenceNumber(), ns3::WifiRemoteStationManager::UpdateFragmentationThreshold(), and ns3::WIFI_MAC_FCS_LENGTH.
Referenced by ns3::ChannelAccessManager::DoGrantDcfAccess(), and ns3::ChannelAccessManager::DoGrantPcfAccess().
NotifyAccessRequested()
void ns3::Txop::NotifyAccessRequested (void) protected virtual
Notify that access request has been received.
Definition at line 469 of file txop.cc.
References m_accessRequested, and NS_LOG_FUNCTION.
Referenced by ns3::ChannelAccessManager::RequestAccess().
NotifyChannelSwitching()
void ns3::Txop::NotifyChannelSwitching (void) virtual
When a channel switching occurs, enqueued packets are removed.
Definition at line 570 of file txop.cc.
References m_currentPacket, m_queue, and NS_LOG_FUNCTION.
Referenced by ns3::OcbWifiMac::CancleTx().
NotifyInternalCollision()
void ns3::Txop::NotifyInternalCollision (void) protected virtual
Notify the Txop that internal collision has occurred.
Reimplemented in ns3::QosTxop.
Definition at line 562 of file txop.cc.
References GenerateBackoff(), NS_LOG_FUNCTION, and RestartAccessIfNeeded().
NotifyOff()
void ns3::Txop::NotifyOff (void) virtual
When off operation occurs, the queue gets cleaned up.
Definition at line 589 of file txop.cc.
References m_currentPacket, m_queue, and NS_LOG_FUNCTION.
NotifyOn()
void ns3::Txop::NotifyOn (void) virtual
When on operation occurs, channel access will be started.
Definition at line 604 of file txop.cc.
References NS_LOG_FUNCTION, and StartAccessIfNeeded().
NotifySleep()
void ns3::Txop::NotifySleep (void) virtual
When sleep operation occurs, if there is a pending packet transmission, it will be reinserted to the front of the queue.
Definition at line 578 of file txop.cc.
References m_currentHdr, m_currentPacket, m_queue, and NS_LOG_FUNCTION.
NotifyWakeUp()
void ns3::Txop::NotifyWakeUp (void) virtual
When wake up operation occurs, channel access will be restarted.
Definition at line 597 of file txop.cc.
References NS_LOG_FUNCTION, and RestartAccessIfNeeded().
Queue()
void ns3::Txop::Queue (Ptr< Packet > packet, const WifiMacHeader & hdr) virtual
Parameters
packet packet to send.
hdr header of packet to send.
Store the packet in the internal queue until it can be sent safely.
Definition at line 317 of file txop.cc.
References GenerateBackoff(), m_channelAccessManager, m_queue, ns3::ChannelAccessManager::NeedBackoffUponAccess(), NS_LOG_FUNCTION, ns3::Packet::RemovePacketTag(), and StartAccessIfNeeded().
Referenced by ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::StaWifiMac::Enqueue(), ns3::ApWifiMac::ForwardDown(), ns3::StaWifiMac::SendAssociationRequest(), ns3::ApWifiMac::SendAssocResp(), ns3::MeshWifiInterfaceMac::SendBeacon(), ns3::ApWifiMac::SendOneBeacon(), ns3::StaWifiMac::SendProbeRequest(), ns3::ApWifiMac::SendProbeResp(), and ns3::OcbWifiMac::SendVsc().
ResetCw()
void ns3::Txop::ResetCw (void) protected
Update the value of the CW variable to take into account a transmission success or a transmission abort (stop transmission of a packet after the maximum number of retransmissions has been reached).
By default, this resets the CW variable to minCW.
Definition at line 218 of file txop.cc.
References m_cw, m_cwMin, and NS_LOG_FUNCTION.
Referenced by ns3::QosTxop::DoInitialize(), DoInitialize(), ns3::QosTxop::EndTxNoAck(), EndTxNoAck(), ns3::QosTxop::GotAck(), GotAck(), ns3::QosTxop::GotBlockAck(), ns3::QosTxop::MissedAck(), MissedAck(), ns3::QosTxop::MissedBlockAck(), MissedCts(), ns3::QosTxop::NotifyInternalCollision(), ns3::QosTxop::NotifyMissedCts(), SetMaxCw(), and SetMinCw().
RestartAccessIfNeeded()
void ns3::Txop::RestartAccessIfNeeded (void) protected virtual
Restart access request if needed.
Reimplemented in ns3::QosTxop.
Definition at line 340 of file txop.cc.
References IsAccessRequested(), m_channelAccessManager, m_currentPacket, m_low, m_queue, NS_LOG_FUNCTION, and ns3::ChannelAccessManager::RequestAccess().
Referenced by GotAck(), GotCfEnd(), MissedAck(), MissedCts(), NotifyInternalCollision(), and NotifyWakeUp().
SendCfFrame()
void ns3::Txop::SendCfFrame (WifiMacType frameType, Mac48Address addr)
Sends CF frame to STA with address addr.
Parameters
frameType the type of frame to be transmitted.
addr address of the recipient.
Definition at line 783 of file txop.cc.
References ns3::WifiMacHeader::GetAddr1(), m_channelAccessManager, m_currentHdr, m_currentPacket, m_low, m_queue, m_stationManager, m_txMiddle, NeedDataRetransmission(), NS_ASSERT, NS_LOG_FUNCTION, ns3::WifiRemoteStationManager::ReportFinalDataFailed(), ns3::ChannelAccessManager::RequestAccess(), ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetAddr2(), ns3::WifiMacHeader::SetAddr3(), ns3::WifiMacHeader::SetDsFrom(), ns3::WifiMacHeader::SetDsNotFrom(), ns3::WifiMacHeader::SetDsNotTo(), ns3::WifiMacHeader::SetDsTo(), ns3::WifiMacHeader::SetFragmentNumber(), ns3::WifiMacHeader::SetNoMoreFragments(), ns3::WifiMacHeader::SetNoRetry(), ns3::WifiMacHeader::SetRetry(), ns3::WifiMacHeader::SetSequenceNumber(), ns3::WifiMacHeader::SetType(), ns3::WIFI_MAC_CTL_END, ns3::WIFI_MAC_DATA, ns3::WIFI_MAC_DATA_CFPOLL, ns3::WIFI_MAC_DATA_NULL, and ns3::WIFI_MAC_DATA_NULL_CFPOLL.
Referenced by ns3::ApWifiMac::SendCfEnd(), ns3::ApWifiMac::SendCfPoll(), and ns3::StaWifiMac::SendCfPollResponse().
SetAifsn()
void ns3::Txop::SetAifsn (uint8_t aifsn)
Set the number of slots that make up an AIFS.
Parameters
aifsn the number of slots that make up an AIFS.
Definition at line 270 of file txop.cc.
References m_aifsn, and NS_LOG_FUNCTION.
Referenced by ns3::ApWifiMac::ApWifiMac(), ns3::WifiMac::ConfigureDcf(), ns3::OcbWifiMac::ConfigureEdca(), ns3::MeshWifiInterfaceMac::ConfigureStandard(), GetTypeId(), and ns3::StaWifiMac::SetEdcaParameters().
SetChannelAccessManager()
void ns3::Txop::SetChannelAccessManager (const Ptr< ChannelAccessManager > manager)
Set ChannelAccessManager this Txop is associated to.
Parameters
manager ChannelAccessManager to associate.
Definition at line 120 of file txop.cc.
References ns3::ChannelAccessManager::Add(), m_channelAccessManager, and NS_LOG_FUNCTION.
Referenced by ns3::ApWifiMac::ApWifiMac(), ns3::RegularWifiMac::RegularWifiMac(), and ns3::RegularWifiMac::SetupEdcaQueue().
SetMacLow()
void ns3::Txop::SetMacLow (const Ptr< MacLow > low)
Set MacLow associated with this Txop.
Parameters
low MacLow to associate.
Definition at line 134 of file txop.cc.
References m_low, and NS_LOG_FUNCTION.
Referenced by ns3::ApWifiMac::ApWifiMac(), ns3::RegularWifiMac::RegularWifiMac(), ns3::OcbWifiMac::EnableForWave(), and ns3::RegularWifiMac::SetupEdcaQueue().
SetMaxCw()
void ns3::Txop::SetMaxCw (uint32_t maxCw)
Set the maximum contention window size.
Parameters
maxCw the maximum contention window size.
Definition at line 199 of file txop.cc.
References GetCw(), m_cwMax, m_cwTrace, NS_LOG_FUNCTION, and ResetCw().
Referenced by ns3::ApWifiMac::ApWifiMac(), ns3::WifiMac::ConfigureDcf(), ns3::OcbWifiMac::ConfigureEdca(), ns3::MeshWifiInterfaceMac::ConfigureStandard(), GetTypeId(), and ns3::StaWifiMac::SetEdcaParameters().
SetMinCw()
void ns3::Txop::SetMinCw (uint32_t minCw)
Set the minimum contention window size.
Parameters
minCw the minimum contention window size.
Definition at line 186 of file txop.cc.
References GetCw(), m_cwMin, m_cwTrace, NS_LOG_FUNCTION, and ResetCw().
Referenced by ns3::ApWifiMac::ApWifiMac(), ns3::WifiMac::ConfigureDcf(), ns3::OcbWifiMac::ConfigureEdca(), ns3::MeshWifiInterfaceMac::ConfigureStandard(), GetTypeId(), and ns3::StaWifiMac::SetEdcaParameters().
SetTxDroppedCallback()
void ns3::Txop::SetTxDroppedCallback (TxDropped callback)
Parameters
callback the callback to invoke when a packet is dropped.
Definition at line 162 of file txop.cc.
References m_queue, m_txDroppedCallback, ns3::MakeCallback(), NS_LOG_FUNCTION, and TxDroppedPacket().
Referenced by ns3::RegularWifiMac::RegularWifiMac(), and ns3::RegularWifiMac::SetupEdcaQueue().
SetTxFailedCallback()
void ns3::Txop::SetTxFailedCallback (TxFailed callback)
Parameters
callback the callback to invoke when a packet transmission was completed unsuccessfully.
Definition at line 155 of file txop.cc.
References m_txFailedCallback, and NS_LOG_FUNCTION.
Referenced by ns3::RegularWifiMac::RegularWifiMac(), and ns3::RegularWifiMac::SetupEdcaQueue().
SetTxMiddle()
void ns3::Txop::SetTxMiddle (const Ptr< MacTxMiddle > txMiddle)
Set MacTxMiddle this Txop is associated to.
Parameters
txMiddle MacTxMiddle to associate.
Definition at line 127 of file txop.cc.
References m_txMiddle, and NS_LOG_FUNCTION.
Referenced by ns3::ApWifiMac::ApWifiMac(), ns3::RegularWifiMac::RegularWifiMac(), and ns3::RegularWifiMac::SetupEdcaQueue().
SetTxOkCallback()
void ns3::Txop::SetTxOkCallback (TxOk callback)
Parameters
callback the callback to invoke when a packet transmission was completed successfully.
Definition at line 148 of file txop.cc.
References m_txOkCallback, and NS_LOG_FUNCTION.
Referenced by ns3::ApWifiMac::ApWifiMac(), ns3::RegularWifiMac::RegularWifiMac(), and ns3::RegularWifiMac::SetupEdcaQueue().
SetTxopLimit()
void ns3::Txop::SetTxopLimit (Time txopLimit)
Set the TXOP limit.
Parameters
txopLimit the TXOP limit. Value zero corresponds to default Txop.
Definition at line 277 of file txop.cc.
References ns3::Time::GetMicroSeconds(), m_txopLimit, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
Referenced by ns3::WifiMac::ConfigureDcf(), GetTypeId(), Experiment::Run(), and ns3::StaWifiMac::SetEdcaParameters().
SetWifiRemoteStationManager()
void ns3::Txop::SetWifiRemoteStationManager (const Ptr< WifiRemoteStationManager > remoteManager) virtual
Set WifiRemoteStationsManager this Txop is associated to.
Parameters
remoteManager WifiRemoteStationManager to associate.
Reimplemented in ns3::QosTxop.
Definition at line 141 of file txop.cc.
References m_stationManager, and NS_LOG_FUNCTION.
Referenced by ns3::QosTxop::SetWifiRemoteStationManager(), ns3::ApWifiMac::SetWifiRemoteStationManager(), and ns3::RegularWifiMac::SetWifiRemoteStationManager().
StartAccessIfNeeded()
void ns3::Txop::StartAccessIfNeeded (void) protected virtual
Request access from Txop if needed.
Reimplemented in ns3::QosTxop.
Definition at line 353 of file txop.cc.
References IsAccessRequested(), m_channelAccessManager, m_currentPacket, m_low, m_queue, NS_LOG_FUNCTION, and ns3::ChannelAccessManager::RequestAccess().
Referenced by EndTxNoAck(), GotCfEnd(), NotifyOn(), and Queue().
StartBackoffNow()
void ns3::Txop::StartBackoffNow (uint32_t nSlots)
Parameters
nSlots the number of slots of the backoff.
Start a backoff by initializing the backoff counter to the number of slots specified.
Definition at line 254 of file txop.cc.
References m_backoffSlots, m_backoffStart, ns3::Simulator::Now(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by GenerateBackoff().
StartNextFragment()
void ns3::Txop::StartNextFragment (void) virtual
Start transmission for the next fragment.
This is called for fragment only.
Definition at line 738 of file txop.cc.
References ns3::MacLowTransmissionParameters::DisableNextData(), ns3::MacLowTransmissionParameters::DisableRts(), ns3::MacLowTransmissionParameters::EnableAck(), ns3::MacLowTransmissionParameters::EnableNextData(), GetFragmentPacket(), GetLow(), GetNextFragmentSize(), IsLastFragment(), m_currentParams, NextFragment(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by ns3::MacLow::WaitIfsAfterEndTxFragment().
StartNextPacket()
void ns3::Txop::StartNextPacket (void) virtual
Start transmission for the next packet if allowed by the TxopLimit.
Reimplemented in ns3::QosTxop.
Definition at line 867 of file txop.cc.
References NS_LOG_WARN.
Referenced by ns3::MacLow::WaitIfsAfterEndTxPacket().
TerminateTxop()
void ns3::Txop::TerminateTxop (void) virtual
Update backoff and restart access if needed.
Reimplemented in ns3::QosTxop.
Definition at line 892 of file txop.cc.
References NS_LOG_WARN.
Referenced by ns3::MacLow::ReceiveOk().
TxDroppedPacket()
void ns3::Txop::TxDroppedPacket (Ptr< const WifiMacQueueItem > item) protected
Pass the packet included in the wifi MAC queue item to the packet dropped callback.
Parameters
item the wifi MAC queue item.
Definition at line 170 of file txop.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), and m_txDroppedCallback.
Referenced by SetTxDroppedCallback().
UpdateBackoffSlotsNow()
void ns3::Txop::UpdateBackoffSlotsNow (uint32_t nSlots, Time backoffUpdateBound) protected
Update backoff slots that nSlots has passed.
Parameters
nSlots the number of slots to decrement
backoffUpdateBound the time at which backoff should start
Definition at line 245 of file txop.cc.
References m_backoffSlots, m_backoffStart, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by ns3::ChannelAccessManager::NeedBackoffUponAccess(), and ns3::ChannelAccessManager::RequestAccess().
UpdateFailedCw()
void ns3::Txop::UpdateFailedCw (void) protected
Update the value of the CW variable to take into account a transmission failure.
By default, this triggers a doubling of CW (capped by maxCW).
Definition at line 225 of file txop.cc.
References m_cw, m_cwMax, min, and NS_LOG_FUNCTION.
Referenced by ns3::QosTxop::MissedAck(), MissedAck(), ns3::QosTxop::MissedBlockAck(), MissedCts(), ns3::QosTxop::NotifyInternalCollision(), and ns3::QosTxop::NotifyMissedCts().
Friends And Related Function Documentation
ChannelAccessManager
friend class ChannelAccessManager friend
< ChannelAccessManager associated class
Definition at line 355 of file txop.h.
MacLowTransmissionListener
friend class MacLowTransmissionListener friend
allow MacLowTransmissionListener class access
Definition at line 70 of file txop.h.
Member Data Documentation
m_accessRequested
bool ns3::Txop::m_accessRequested protected
flag whether channel access is already requested
Definition at line 519 of file txop.h.
Referenced by IsAccessRequested(), ns3::QosTxop::NotifyAccessGranted(), NotifyAccessGranted(), and NotifyAccessRequested().
m_aifsn
uint8_t ns3::Txop::m_aifsn protected
the AIFSN
Definition at line 528 of file txop.h.
Referenced by GetAifsn(), and SetAifsn().
m_backoff
uint32_t ns3::Txop::m_backoff protected
the current backoff
Definition at line 518 of file txop.h.
Referenced by GenerateBackoff().
m_backoffSlots
uint32_t ns3::Txop::m_backoffSlots protected
the number of backoff slots
Definition at line 520 of file txop.h.
Referenced by GetBackoffSlots(), StartBackoffNow(), and UpdateBackoffSlotsNow().
m_backoffStart
Time ns3::Txop::m_backoffStart protected
the backoffStart variable is used to keep track of the time at which a backoff was started or the time at which the backoff counter was last updated.
Definition at line 526 of file txop.h.
Referenced by GetBackoffStart(), StartBackoffNow(), and UpdateBackoffSlotsNow().
m_backoffTrace
TracedCallback<uint32_t> ns3::Txop::m_backoffTrace protected
backoff trace value
Definition at line 535 of file txop.h.
Referenced by GenerateBackoff(), and GetTypeId().
m_channelAccessManager
Ptr<ChannelAccessManager> ns3::Txop::m_channelAccessManager protected
the channel access manager
Definition at line 505 of file txop.h.
Referenced by CanStartNextPolling(), DoDispose(), Queue(), ns3::QosTxop::RestartAccessIfNeeded(), RestartAccessIfNeeded(), SendCfFrame(), SetChannelAccessManager(), ns3::QosTxop::StartAccessIfNeeded(), and StartAccessIfNeeded().
m_currentHdr
WifiMacHeader ns3::Txop::m_currentHdr protected
the current header
Definition at line 532 of file txop.h.
Referenced by ns3::QosTxop::BaTxFailed(), ns3::QosTxop::BaTxOk(), AmpduAggregationTest::DoRun(), EndTxNoAck(), ns3::QosTxop::GetFragmentOffset(), GetFragmentOffset(), ns3::QosTxop::GetFragmentPacket(), GetFragmentPacket(), ns3::QosTxop::GetFragmentSize(), GetFragmentSize(), ns3::QosTxop::GetNextFragmentSize(), GetNextFragmentSize(), ns3::QosTxop::GetTxopFragmentSize(), ns3::QosTxop::GotAck(), GotAck(), ns3::QosTxop::GotAddBaResponse(), ns3::QosTxop::GotBlockAck(), ns3::QosTxop::IsLastFragment(), IsLastFragment(), ns3::QosTxop::IsTxopFragmentation(), ns3::QosTxop::MissedAck(), MissedAck(), ns3::QosTxop::MissedBlockAck(), MissedCfPollResponse(), MissedCts(), ns3::QosTxop::NeedBarRetransmission(), ns3::QosTxop::NeedFragmentation(), NeedFragmentation(), ns3::QosTxop::NotifyAccessGranted(), NotifyAccessGranted(), ns3::QosTxop::NotifyInternalCollision(), ns3::QosTxop::NotifyMissedCts(), NotifySleep(), ns3::QosTxop::RestartAccessIfNeeded(), ns3::QosTxop::SendAddBaRequest(), SendCfFrame(), ns3::QosTxop::SetupBlockAckIfNeeded(), ns3::QosTxop::StartNextPacket(), and ns3::QosTxop::UpdateCurrentPacket().
m_currentPacket
Ptr<const Packet> ns3::Txop::m_currentPacket protected
the current packet
Definition at line 531 of file txop.h.
Referenced by AmpduAggregationTest::DoRun(), ns3::QosTxop::EndTxNoAck(), EndTxNoAck(), ns3::QosTxop::GetFragmentOffset(), GetFragmentOffset(), ns3::QosTxop::GetFragmentPacket(), GetFragmentPacket(), ns3::QosTxop::GetFragmentSize(), GetFragmentSize(), ns3::QosTxop::GetNextFragmentSize(), GetNextFragmentSize(), ns3::QosTxop::GetNextTxopFragmentSize(), ns3::QosTxop::GetNTxopFragment(), ns3::QosTxop::GetTxopFragmentOffset(), ns3::QosTxop::GetTxopFragmentSize(), ns3::QosTxop::GotAck(), GotAck(), ns3::QosTxop::GotAddBaResponse(), ns3::QosTxop::GotBlockAck(), GotCfEnd(), ns3::QosTxop::HasFramesToTransmit(), HasFramesToTransmit(), ns3::QosTxop::IsLastFragment(), IsLastFragment(), ns3::QosTxop::IsTxopFragmentation(), ns3::QosTxop::MissedAck(), MissedAck(), ns3::QosTxop::MissedBlockAck(), MissedCfPollResponse(), MissedCts(), ns3::QosTxop::NeedBarRetransmission(), ns3::QosTxop::NeedFragmentation(), NeedFragmentation(), ns3::QosTxop::NotifyAccessGranted(), NotifyAccessGranted(), NotifyChannelSwitching(), ns3::QosTxop::NotifyInternalCollision(), ns3::QosTxop::NotifyMissedCts(), NotifyOff(), NotifySleep(), ns3::QosTxop::RestartAccessIfNeeded(), RestartAccessIfNeeded(), ns3::QosTxop::SendAddBaRequest(), SendCfFrame(), ns3::QosTxop::StartAccessIfNeeded(), StartAccessIfNeeded(), ns3::QosTxop::StartNextPacket(), and ns3::QosTxop::UpdateCurrentPacket().
m_currentParams
MacLowTransmissionParameters ns3::Txop::m_currentParams protected
current transmission parameters
Definition at line 533 of file txop.h.
Referenced by ns3::QosTxop::GetTxopFragmentSize(), ns3::QosTxop::GotAck(), ns3::QosTxop::NeedFragmentation(), ns3::QosTxop::NotifyAccessGranted(), NotifyAccessGranted(), ns3::QosTxop::SendAddBaRequest(), StartNextFragment(), and ns3::QosTxop::StartNextPacket().
m_cw
uint32_t ns3::Txop::m_cw protected
the current contention window
Definition at line 517 of file txop.h.
Referenced by GetCw(), ResetCw(), and UpdateFailedCw().
m_cwMax
uint32_t ns3::Txop::m_cwMax protected
the maximum contention window
Definition at line 516 of file txop.h.
Referenced by GetMaxCw(), SetMaxCw(), and UpdateFailedCw().
m_cwMin
uint32_t ns3::Txop::m_cwMin protected
the minimum contention window
Definition at line 515 of file txop.h.
Referenced by GetMinCw(), ResetCw(), and SetMinCw().
m_cwTrace
TracedValue<uint32_t> ns3::Txop::m_cwTrace protected
CW trace value.
Definition at line 536 of file txop.h.
Referenced by ns3::QosTxop::DoInitialize(), DoInitialize(), EndTxNoAck(), GetTypeId(), GotAck(), ns3::QosTxop::MissedAck(), MissedAck(), ns3::QosTxop::MissedBlockAck(), MissedCts(), ns3::QosTxop::NotifyMissedCts(), SetMaxCw(), and SetMinCw().
m_fragmentNumber
uint8_t ns3::Txop::m_fragmentNumber protected
the fragment number
Definition at line 534 of file txop.h.
Referenced by ns3::QosTxop::GetFragmentOffset(), GetFragmentOffset(), ns3::QosTxop::GetFragmentPacket(), GetFragmentPacket(), ns3::QosTxop::GetFragmentSize(), GetFragmentSize(), ns3::QosTxop::GetNextFragmentSize(), GetNextFragmentSize(), ns3::QosTxop::IsLastFragment(), IsLastFragment(), NextFragment(), ns3::QosTxop::NotifyAccessGranted(), NotifyAccessGranted(), and ns3::QosTxop::StartNextPacket().
m_low
Ptr<MacLow> ns3::Txop::m_low protected
the MacLow
Definition at line 511 of file txop.h.
Referenced by ns3::QosTxop::CompleteConfig(), ns3::QosTxop::DequeuePeekedFrame(), DoDispose(), GetLow(), ns3::QosTxop::GetTransmissionParameters(), ns3::QosTxop::GotAck(), ns3::QosTxop::NotifyAccessGranted(), NotifyAccessGranted(), ns3::QosTxop::PrepareBlockAckRequest(), RestartAccessIfNeeded(), ns3::QosTxop::SendAddBaRequest(), SendCfFrame(), ns3::QosTxop::SendDelbaFrame(), SetMacLow(), StartAccessIfNeeded(), and ns3::QosTxop::StartNextPacket().
m_queue
Ptr<WifiMacQueue> ns3::Txop::m_queue protected
the wifi MAC queue
Definition at line 509 of file txop.h.
Referenced by ns3::QosTxop::QosTxop(), Txop(), ns3::QosTxop::DequeuePeekedFrame(), DoDispose(), GetWifiMacQueue(), ns3::QosTxop::HasFramesToTransmit(), HasFramesToTransmit(), ns3::QosTxop::NotifyAccessGranted(), NotifyAccessGranted(), NotifyChannelSwitching(), ns3::QosTxop::NotifyInternalCollision(), NotifyOff(), NotifySleep(), ns3::QosTxop::PeekNextFrame(), ns3::QosTxop::PushFront(), Queue(), ns3::QosTxop::RestartAccessIfNeeded(), RestartAccessIfNeeded(), SendCfFrame(), SetTxDroppedCallback(), ns3::QosTxop::SetupBlockAckIfNeeded(), ns3::QosTxop::StartAccessIfNeeded(), and StartAccessIfNeeded().
m_rng
Ptr<UniformRandomVariable> ns3::Txop::m_rng protected
the random stream
Definition at line 513 of file txop.h.
Referenced by Txop(), AssignStreams(), DoDispose(), and GenerateBackoff().
m_stationManager
Ptr<WifiRemoteStationManager> ns3::Txop::m_stationManager protected
the wifi remote station manager
Definition at line 512 of file txop.h.
Referenced by DoDispose(), ns3::QosTxop::GetFragmentOffset(), GetFragmentOffset(), ns3::QosTxop::GetFragmentSize(), GetFragmentSize(), ns3::QosTxop::GetNextFragmentSize(), GetNextFragmentSize(), ns3::QosTxop::GetTransmissionParameters(), ns3::QosTxop::IsLastFragment(), IsLastFragment(), ns3::QosTxop::IsTxopFragmentation(), ns3::QosTxop::MissedAck(), MissedAck(), ns3::QosTxop::MissedBlockAck(), MissedCfPollResponse(), MissedCts(), NeedDataRetransmission(), ns3::QosTxop::NeedFragmentation(), NeedFragmentation(), NeedRtsRetransmission(), ns3::QosTxop::NotifyAccessGranted(), NotifyAccessGranted(), ns3::QosTxop::NotifyInternalCollision(), ns3::QosTxop::NotifyMissedCts(), ns3::QosTxop::RestartAccessIfNeeded(), ns3::QosTxop::SendAddBaRequest(), SendCfFrame(), ns3::QosTxop::SetupBlockAckIfNeeded(), ns3::QosTxop::SetWifiRemoteStationManager(), SetWifiRemoteStationManager(), ns3::QosTxop::StartAccessIfNeeded(), and ns3::QosTxop::StartNextPacket().
m_txDroppedCallback
TxDropped ns3::Txop::m_txDroppedCallback protected
the packet dropped callback
Definition at line 508 of file txop.h.
Referenced by SetTxDroppedCallback(), and TxDroppedPacket().
m_txFailedCallback
TxFailed ns3::Txop::m_txFailedCallback protected
the transmit failed callback
Definition at line 507 of file txop.h.
Referenced by ns3::QosTxop::BaTxFailed(), ns3::QosTxop::MissedAck(), MissedAck(), ns3::QosTxop::MissedBlockAck(), MissedCfPollResponse(), MissedCts(), ns3::QosTxop::NotifyInternalCollision(), ns3::QosTxop::NotifyMissedCts(), and SetTxFailedCallback().
m_txMiddle
Ptr<MacTxMiddle> ns3::Txop::m_txMiddle protected
the MacTxMiddle
Definition at line 510 of file txop.h.
Referenced by ns3::QosTxop::CompleteConfig(), ns3::QosTxop::DequeuePeekedFrame(), DoDispose(), ns3::QosTxop::GetNextSequenceNumberFor(), NotifyAccessGranted(), ns3::QosTxop::PeekNextFrame(), ns3::QosTxop::PeekNextSequenceNumberFor(), ns3::QosTxop::SendAddBaRequest(), SendCfFrame(), SetTxMiddle(), and ns3::QosTxop::SetupBlockAckIfNeeded().
m_txOkCallback
TxOk ns3::Txop::m_txOkCallback protected
the transmit OK callback
Definition at line 506 of file txop.h.
Referenced by ns3::QosTxop::BaTxOk(), EndTxNoAck(), ns3::QosTxop::GotAck(), GotAck(), ns3::QosTxop::GotBlockAck(), and SetTxOkCallback().
m_txopLimit
Time ns3::Txop::m_txopLimit protected
the TXOP limit time
Definition at line 529 of file txop.h.
Referenced by GetTxopLimit(), and SetTxopLimit().
The documentation for this class was generated from the following files:
src/wifi/model/txop.h
src/wifi/model/txop.cc