ns-3: ns3::NetDeviceQueueLock Class Reference
ns3::NetDeviceQueueLock Class Reference
File Descriptor Network Device
Network device transmission queue with lock.
#include "netmap-net-device.h"
Public Member Functions
NetDeviceQueueLock ()
virtual ~NetDeviceQueueLock ()
virtual bool IsStopped (void) const
Get the status of the device transmission queue.
virtual void NotifyQueuedBytes (uint32_t bytes)
Called by the netdevice to report the number of bytes queued to the device queue.
virtual void NotifyTransmittedBytes (uint32_t bytes)
Called by the netdevice to report the number of bytes it is going to transmit.
virtual void Start (void)
Called by the device to start this device transmission queue.
virtual void Stop (void)
Called by the device to stop this device transmission queue.
virtual void Wake (void)
Called by the device to wake the queue disc associated with this device transmission queue.
Public Member Functions inherited from ns3::NetDeviceQueue
NetDeviceQueue ()
virtual ~NetDeviceQueue ()
template<typename QueueType >
void ConnectQueueTraces (Ptr< QueueType > queue)
Connect the traced callbacks of a queue to the methods providing support for flow control and dynamic queue limits.
Ptr< QueueLimits > GetQueueLimits ()
Get queue limits to this queue.
void NotifyAggregatedObject (Ptr< NetDeviceQueueInterface > ndqi)
Notify this NetDeviceQueue that the NetDeviceQueueInterface was aggregated to an object.
template<typename QueueType >
void PacketDequeued (QueueType *queue, Ptr< const typename QueueType::ItemType > item)
Perform the actions required by flow control and dynamic queue limits when a packet is dequeued (or dropped after dequeue) from the queue of a netdevice.
template<typename QueueType >
void PacketDiscarded (QueueType *queue, Ptr< const typename QueueType::ItemType > item)
Perform the actions required by flow control and dynamic queue limits when a packet is dropped before being enqueued in the queue of a netdevice (which likely indicates that the queue is full)
template<typename QueueType >
void PacketEnqueued (QueueType *queue, Ptr< const typename QueueType::ItemType > item)
Perform the actions required by flow control and dynamic queue limits when a packet is enqueued in the queue of a netdevice.
void ResetQueueLimits ()
Reset queue limits state.
void SetQueueLimits (Ptr< QueueLimits > ql)
Set queue limits to this queue.
virtual void SetWakeCallback (WakeCallback cb)
Set the wake callback.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::NetDeviceQueue
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
std::mutex m_mutex
Mutex to serialize the operations performed on the queue.
Additional Inherited Members
Public Types inherited from ns3::NetDeviceQueue
typedef Callback< void > WakeCallback
Callback invoked by netdevices to wake upper layers.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Network device transmission queue with lock.
This class stores information about a single transmission queue of a network device that is exposed to queue discs. This class extends the NetDeviceQueue base class by introducing a lock for methods which require mutual exclusion on data access in emulation.
Definition at line 44 of file netmap-net-device.h.
Constructor & Destructor Documentation
NetDeviceQueueLock()
ns3::NetDeviceQueueLock::NetDeviceQueueLock ()
Definition at line 41 of file netmap-net-device.cc.
~NetDeviceQueueLock()
ns3::NetDeviceQueueLock::~NetDeviceQueueLock () virtual
Definition at line 44 of file netmap-net-device.cc.
Member Function Documentation
GetTypeId()
TypeId ns3::NetDeviceQueueLock::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 32 of file netmap-net-device.cc.
References ns3::TypeId::SetParent().
Referenced by ns3::NetmapNetDeviceHelper::InstallPriv().
IsStopped()
bool ns3::NetDeviceQueueLock::IsStopped (void) const virtual
Get the status of the device transmission queue.
Returns
true if the device transmission queue is stopped.
Called by queue discs to enquire about the status of a given transmission queue. This is the analogous to the netif_xmit_stopped function of the Linux kernel.
Reimplemented from ns3::NetDeviceQueue.
Definition at line 48 of file netmap-net-device.cc.
References ns3::NetDeviceQueue::IsStopped(), and m_mutex.
NotifyQueuedBytes()
void ns3::NetDeviceQueueLock::NotifyQueuedBytes (uint32_t bytes) virtual
Called by the netdevice to report the number of bytes queued to the device queue.
Parameters
bytes number of bytes queued to the device queue
Reimplemented from ns3::NetDeviceQueue.
Definition at line 81 of file netmap-net-device.cc.
References m_mutex, and ns3::NetDeviceQueue::NotifyQueuedBytes().
NotifyTransmittedBytes()
void ns3::NetDeviceQueueLock::NotifyTransmittedBytes (uint32_t bytes) virtual
Called by the netdevice to report the number of bytes it is going to transmit.
Parameters
bytes number of bytes the device is going to transmit
Reimplemented from ns3::NetDeviceQueue.
Definition at line 89 of file netmap-net-device.cc.
References m_mutex, and ns3::NetDeviceQueue::NotifyTransmittedBytes().
Start()
void ns3::NetDeviceQueueLock::Start (void) virtual
Called by the device to start this device transmission queue.
This is the analogous to the netif_tx_start_queue function of the Linux kernel.
Reimplemented from ns3::NetDeviceQueue.
Definition at line 57 of file netmap-net-device.cc.
References m_mutex, and ns3::NetDeviceQueue::Start().
Stop()
void ns3::NetDeviceQueueLock::Stop (void) virtual
Called by the device to stop this device transmission queue.
This is the analogous to the netif_tx_stop_queue function of the Linux kernel.
Reimplemented from ns3::NetDeviceQueue.
Definition at line 65 of file netmap-net-device.cc.
References m_mutex, and ns3::NetDeviceQueue::Stop().
Wake()
void ns3::NetDeviceQueueLock::Wake (void) virtual
Called by the device to wake the queue disc associated with this device transmission queue.
This is done by invoking the wake callback. This is the analogous to the netif_tx_wake_queue function of the Linux kernel.
Reimplemented from ns3::NetDeviceQueue.
Definition at line 73 of file netmap-net-device.cc.
References m_mutex, and ns3::NetDeviceQueue::Wake().
Member Data Documentation
m_mutex
std::mutex ns3::NetDeviceQueueLock::m_mutex mutable private
Mutex to serialize the operations performed on the queue.
Definition at line 97 of file netmap-net-device.h.
Referenced by IsStopped(), NotifyQueuedBytes(), NotifyTransmittedBytes(), Start(), Stop(), and Wake().
The documentation for this class was generated from the following files:
src/fd-net-device/model/netmap-net-device.h
src/fd-net-device/model/netmap-net-device.cc