ns-3: ns3::dsdv::RoutingTable Class Reference
ns3::dsdv::RoutingTable Class Reference
DSDV Routing
The Routing table used by DSDV protocol.
#include "dsdv-rtable.h"
Public Member Functions
RoutingTable ()
c-tor
bool AddIpv4Event (Ipv4Address address, EventId id)
Add an event for a destination address so that the update to for that destination is sent after the event is completed.
bool AddRoute (RoutingTableEntry &r)
Add routing table entry if it doesn't yet exist in routing table.
bool AnyRunningEvent (Ipv4Address address)
Force delete an update waiting for settling time to complete as a better update to same destination was received.
void Clear ()
Delete all entries from routing table.
void DeleteAllRoutesFromInterface (Ipv4InterfaceAddress iface)
Delete all route from interface with address iface.
bool DeleteIpv4Event (Ipv4Address address)
Clear up the entry from the map after the event is completed.
bool DeleteRoute (Ipv4Address dst)
Delete routing table entry with destination address dst, if it exists.
bool ForceDeleteIpv4Event (Ipv4Address address)
Force delete an update waiting for settling time to complete as a better update to same destination was received.
EventId GetEventId (Ipv4Address address)
Get the EcentId associated with that address.
Time Getholddowntime () const
Get hold down time (time until an invalid route may be deleted)
void GetListOfAllRoutes (std::map< Ipv4Address, RoutingTableEntry > &allRoutes)
Lookup list of all addresses in the routing table.
void GetListOfDestinationWithNextHop (Ipv4Address nxtHp, std::map< Ipv4Address, RoutingTableEntry > &dstList)
Lookup list of addresses for which nxtHp is the next Hop address.
bool LookupRoute (Ipv4Address dst, RoutingTableEntry &rt)
Lookup routing table entry with destination address dst.
bool LookupRoute (Ipv4Address id, RoutingTableEntry &rt, bool forRouteInput)
Lookup routing table entry with destination address dst.
void Print (Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S) const
Print routing table.
void Purge (std::map< Ipv4Address, RoutingTableEntry > &removedAddresses)
Delete all outdated entries if Lifetime is expired.
uint32_t RoutingTableSize ()
Provides the number of routes present in that nodes routing table.
void Setholddowntime (Time t)
Set hold down time (time until an invalid route may be deleted)
bool Update (RoutingTableEntry &rt)
Updating the routing Table with routing table entry rt.
Private Attributes
Time m_holddownTime
hold down time of an expired route
std::map< Ipv4Address, RoutingTableEntry > m_ipv4AddressEntry
an entry in the routing table.
std::map< Ipv4Address, EventId > m_ipv4Events
an entry in the event table.
Detailed Description
The Routing table used by DSDV protocol.
Definition at line 319 of file dsdv-rtable.h.
Constructor & Destructor Documentation
RoutingTable()
ns3::dsdv::RoutingTable::RoutingTable ()
c-tor
Definition at line 67 of file dsdv-rtable.cc.
Member Function Documentation
AddIpv4Event()
bool ns3::dsdv::RoutingTable::AddIpv4Event (Ipv4Address address, EventId id)
Add an event for a destination address so that the update to for that destination is sent after the event is completed.
Parameters
address destination address for which this event is running.
id unique eventid that was generated.
Returns
true on success
Definition at line 264 of file dsdv-rtable.cc.
References first::address, and m_ipv4Events.
Referenced by ns3::dsdv::RoutingProtocol::RecvDsdv().
AddRoute()
bool ns3::dsdv::RoutingTable::AddRoute (RoutingTableEntry & r)
Add routing table entry if it doesn't yet exist in routing table.
Parameters
r routing table entry
Returns
true in success
Definition at line 128 of file dsdv-rtable.cc.
References ns3::dsdv::RoutingTableEntry::GetDestination(), and m_ipv4AddressEntry.
Referenced by DsdvTableTestCase::DoRun(), ns3::dsdv::RoutingProtocol::NotifyAddAddress(), ns3::dsdv::RoutingProtocol::NotifyInterfaceUp(), ns3::dsdv::RoutingProtocol::RecvDsdv(), ns3::dsdv::RoutingProtocol::RouteOutput(), and ns3::dsdv::RoutingProtocol::SetIpv4().
AnyRunningEvent()
bool ns3::dsdv::RoutingTable::AnyRunningEvent (Ipv4Address address)
Force delete an update waiting for settling time to complete as a better update to same destination was received.
Parameters
address destination address for which this event is running.
Returns
true on success
Definition at line 272 of file dsdv-rtable.cc.
References first::address, ns3::EventId::IsRunning(), and m_ipv4Events.
Referenced by ns3::dsdv::RoutingProtocol::MergeTriggerPeriodicUpdates(), ns3::dsdv::RoutingProtocol::RecvDsdv(), and ns3::dsdv::RoutingProtocol::SendTriggeredUpdate().
Clear()
void ns3::dsdv::RoutingTable::Clear (void) inline
Delete all entries from routing table.
Definition at line 383 of file dsdv-rtable.h.
References m_ipv4AddressEntry.
Referenced by ns3::dsdv::RoutingProtocol::NotifyInterfaceDown().
DeleteAllRoutesFromInterface()
void ns3::dsdv::RoutingTable::DeleteAllRoutesFromInterface (Ipv4InterfaceAddress iface)
Delete all route from interface with address iface.
Parameters
iface the interface
Definition at line 148 of file dsdv-rtable.cc.
References m_ipv4AddressEntry.
Referenced by ns3::dsdv::RoutingProtocol::NotifyInterfaceDown().
DeleteIpv4Event()
bool ns3::dsdv::RoutingTable::DeleteIpv4Event (Ipv4Address address)
Clear up the entry from the map after the event is completed.
Parameters
address destination address for which this event is running.
Returns
true on success
Definition at line 311 of file dsdv-rtable.cc.
References first::address, ns3::EventId::IsExpired(), ns3::EventId::IsRunning(), and m_ipv4Events.
Referenced by ns3::dsdv::RoutingProtocol::SendTriggeredUpdate().
DeleteRoute()
bool ns3::dsdv::RoutingTable::DeleteRoute (Ipv4Address dst)
Delete routing table entry with destination address dst, if it exists.
Parameters
dst destination address
Returns
true on success
Definition at line 111 of file dsdv-rtable.cc.
References m_ipv4AddressEntry.
Referenced by ns3::dsdv::RoutingProtocol::MergeTriggerPeriodicUpdates(), ns3::dsdv::RoutingProtocol::RecvDsdv(), and ns3::dsdv::RoutingProtocol::SendTriggeredUpdate().
ForceDeleteIpv4Event()
bool ns3::dsdv::RoutingTable::ForceDeleteIpv4Event (Ipv4Address address)
Force delete an update waiting for settling time to complete as a better update to same destination was received.
Parameters
address destination address for which this event is running.
Returns
true on finding out that an event is already running for that destination address.
Definition at line 296 of file dsdv-rtable.cc.
References first::address, ns3::Simulator::Cancel(), and m_ipv4Events.
Referenced by ns3::dsdv::RoutingProtocol::RecvDsdv().
GetEventId()
EventId ns3::dsdv::RoutingTable::GetEventId (Ipv4Address address)
Get the EcentId associated with that address.
Parameters
address destination address for which this event is running.
Returns
EventId on finding out an event is associated else return NULL.
Definition at line 338 of file dsdv-rtable.cc.
References first::address, and m_ipv4Events.
Referenced by ns3::dsdv::RoutingProtocol::SendTriggeredUpdate().
Getholddowntime()
Time ns3::dsdv::RoutingTable::Getholddowntime () const inline
Get hold down time (time until an invalid route may be deleted)
Returns
the hold down time
Definition at line 449 of file dsdv-rtable.h.
References m_holddownTime.
GetListOfAllRoutes()
void ns3::dsdv::RoutingTable::GetListOfAllRoutes (std::map< Ipv4Address, RoutingTableEntry > & allRoutes)
Lookup list of all addresses in the routing table.
Parameters
allRoutes is the list that will hold all these addresses present in the nodes routing table
Definition at line 170 of file dsdv-rtable.cc.
References m_ipv4AddressEntry, and ns3::dsdv::VALID.
Referenced by ns3::dsdv::RoutingProtocol::LookForQueuedPackets(), ns3::dsdv::RoutingProtocol::MergeTriggerPeriodicUpdates(), ns3::dsdv::RoutingProtocol::RecvDsdv(), ns3::dsdv::RoutingProtocol::SendPeriodicUpdate(), and ns3::dsdv::RoutingProtocol::SendTriggeredUpdate().
GetListOfDestinationWithNextHop()
void ns3::dsdv::RoutingTable::GetListOfDestinationWithNextHop (Ipv4Address nxtHp, std::map< Ipv4Address, RoutingTableEntry > & dstList)
Lookup list of addresses for which nxtHp is the next Hop address.
Parameters
nxtHp nexthop's address for which we want the list of destinations
dstList is the list that will hold all these destination addresses
Definition at line 183 of file dsdv-rtable.cc.
References m_ipv4AddressEntry.
Referenced by ns3::dsdv::RoutingProtocol::RecvDsdv().
LookupRoute() [1/2]
bool ns3::dsdv::RoutingTable::LookupRoute (Ipv4Address dst, RoutingTableEntry & rt)
Lookup routing table entry with destination address dst.
Parameters
dst destination address
rt entry with destination address dst, if exists
Returns
true on success
Definition at line 72 of file dsdv-rtable.cc.
References m_ipv4AddressEntry.
Referenced by DsdvTableTestCase::DoRun(), ns3::dsdv::RoutingProtocol::GetSettlingTime(), ns3::dsdv::RoutingProtocol::LookForQueuedPackets(), ns3::dsdv::RoutingProtocol::RecvDsdv(), ns3::dsdv::RoutingProtocol::RouteInput(), ns3::dsdv::RoutingProtocol::RouteOutput(), ns3::dsdv::RoutingProtocol::SendPeriodicUpdate(), and ns3::dsdv::RoutingProtocol::SendTriggeredUpdate().
LookupRoute() [2/2]
bool ns3::dsdv::RoutingTable::LookupRoute (Ipv4Address id, RoutingTableEntry & rt, bool forRouteInput)
Lookup routing table entry with destination address dst.
Parameters
id destination address
rt entry with destination address dst, if exists
forRouteInput for routing input
Returns
true on success
Definition at line 89 of file dsdv-rtable.cc.
References m_ipv4AddressEntry.
Print()
void ns3::dsdv::RoutingTable::Print (Ptr< OutputStreamWrapper > stream, Time::Unit unit = Time::S) const
Print routing table.
Parameters
stream the output stream
Definition at line 252 of file dsdv-rtable.cc.
References ns3::OutputStreamWrapper::GetStream(), and m_ipv4AddressEntry.
Referenced by ns3::dsdv::RoutingProtocol::PrintRoutingTable().
Purge()
void ns3::dsdv::RoutingTable::Purge (std::map< Ipv4Address, RoutingTableEntry > & removedAddresses)
Delete all outdated entries if Lifetime is expired.
Parameters
removedAddresses is the list of addresses to purge
Todo:
Need to decide when to invalidate a route
Definition at line 208 of file dsdv-rtable.cc.
References m_holddownTime, and m_ipv4AddressEntry.
Referenced by ns3::dsdv::RoutingProtocol::RouteOutput(), and ns3::dsdv::RoutingProtocol::SendPeriodicUpdate().
RoutingTableSize()
uint32_t ns3::dsdv::RoutingTable::RoutingTableSize ()
Provides the number of routes present in that nodes routing table.
Returns
the number of routes
Definition at line 122 of file dsdv-rtable.cc.
References m_ipv4AddressEntry.
Referenced by DsdvTableTestCase::DoRun().
Setholddowntime()
void ns3::dsdv::RoutingTable::Setholddowntime (Time t) inline
Set hold down time (time until an invalid route may be deleted)
Parameters
t the hold down time
Definition at line 457 of file dsdv-rtable.h.
References m_holddownTime.
Referenced by ns3::dsdv::RoutingProtocol::Start().
Update()
bool ns3::dsdv::RoutingTable::Update (RoutingTableEntry & rt)
Updating the routing Table with routing table entry rt.
Parameters
rt routing table entry
Returns
true on success
Definition at line 136 of file dsdv-rtable.cc.
References ns3::dsdv::RoutingTableEntry::GetDestination(), and m_ipv4AddressEntry.
Referenced by ns3::dsdv::RoutingProtocol::MergeTriggerPeriodicUpdates(), ns3::dsdv::RoutingProtocol::RecvDsdv(), ns3::dsdv::RoutingProtocol::SendPeriodicUpdate(), and ns3::dsdv::RoutingProtocol::SendTriggeredUpdate().
Member Data Documentation
m_holddownTime
Time ns3::dsdv::RoutingTable::m_holddownTime private
hold down time of an expired route
Definition at line 469 of file dsdv-rtable.h.
Referenced by Getholddowntime(), Purge(), and Setholddowntime().
m_ipv4AddressEntry
std::map<Ipv4Address, RoutingTableEntry> ns3::dsdv::RoutingTable::m_ipv4AddressEntry private
an entry in the routing table.
Definition at line 465 of file dsdv-rtable.h.
Referenced by AddRoute(), Clear(), DeleteAllRoutesFromInterface(), DeleteRoute(), GetListOfAllRoutes(), GetListOfDestinationWithNextHop(), LookupRoute(), Print(), Purge(), RoutingTableSize(), and Update().
m_ipv4Events
std::map<Ipv4Address, EventId> ns3::dsdv::RoutingTable::m_ipv4Events private
an entry in the event table.
Definition at line 467 of file dsdv-rtable.h.
Referenced by AddIpv4Event(), AnyRunningEvent(), DeleteIpv4Event(), ForceDeleteIpv4Event(), and GetEventId().
The documentation for this class was generated from the following files:
src/dsdv/model/dsdv-rtable.h
src/dsdv/model/dsdv-rtable.cc