ns-3: ns3::TopologyReader Class Reference
ns3::TopologyReader Class Reference abstract
Topology Input Readers
Interface for input file readers management.
#include "topology-reader.h"
Classes
class Link
Inner class holding the details about a link between two nodes.
Public Types
typedef std::list< Link >::const_iterator ConstLinksIterator
Constant iterator to the list of the links.
Public Member Functions
TopologyReader ()
virtual ~TopologyReader ()
void AddLink (Link link)
Adds a link to the topology.
std::string GetFileName (void) const
Returns the input file name.
ConstLinksIterator LinksBegin (void) const
Returns an iterator to the the first link in this block.
bool LinksEmpty (void) const
Checks if the block contains any links.
ConstLinksIterator LinksEnd (void) const
Returns an iterator to the the last link in this block.
int LinksSize (void) const
Returns the number of links in this block.
virtual NodeContainer Read (void)=0
Main topology reading function.
void SetFileName (const std::string &fileName)
Sets the input file name.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
TopologyReader (const TopologyReader &)
Copy constructor.
TopologyReader & operator= (const TopologyReader &)
Copy constructor.
Private Attributes
std::string m_fileName
The name of the input file.
std::list< Link > m_linksList
The container of the links between the nodes.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Interface for input file readers management.
Introspection did not find any typical Config paths.
This interface perform the shared tasks among all possible input file readers. Each different file format is handled by its own topology reader.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 80 bytes (on a 64-bit architecture).
Definition at line 50 of file topology-reader.h.
Member Typedef Documentation
ConstLinksIterator
typedef std::list< Link >::const_iterator ns3::TopologyReader::ConstLinksIterator
Constant iterator to the list of the links.
Definition at line 141 of file topology-reader.h.
Constructor & Destructor Documentation
TopologyReader() [1/2]
ns3::TopologyReader::TopologyReader ()
Definition at line 47 of file topology-reader.cc.
References NS_LOG_FUNCTION.
~TopologyReader()
ns3::TopologyReader::~TopologyReader () virtual
Definition at line 52 of file topology-reader.cc.
References NS_LOG_FUNCTION.
TopologyReader() [2/2]
ns3::TopologyReader::TopologyReader (const TopologyReader &) private
Copy constructor.
Defined and unimplemented to avoid misuse.
Member Function Documentation
AddLink()
void ns3::TopologyReader::AddLink (Link link)
Adds a link to the topology.
Parameters
link [in] The link to be added.
Definition at line 96 of file topology-reader.cc.
References m_linksList.
Referenced by ns3::RocketfuelTopologyReader::GenerateFromMapsFile(), ns3::RocketfuelTopologyReader::GenerateFromWeightsFile(), ns3::InetTopologyReader::Read(), and ns3::OrbisTopologyReader::Read().
GetFileName()
std::string ns3::TopologyReader::GetFileName (void) const
Returns the input file name.
Returns
The input file name.
Definition at line 64 of file topology-reader.cc.
References m_fileName.
Referenced by ns3::InetTopologyReader::Read(), ns3::OrbisTopologyReader::Read(), and ns3::RocketfuelTopologyReader::Read().
GetTypeId()
TypeId ns3::TopologyReader::GetTypeId (void) static
Get the type ID.
Returns
The object TypeId.
Definition at line 38 of file topology-reader.cc.
References ns3::TypeId::SetParent().
LinksBegin()
TopologyReader::ConstLinksIterator ns3::TopologyReader::LinksBegin (void) const
Returns an iterator to the the first link in this block.
Returns
A const iterator to the first link in this block.
Definition at line 72 of file topology-reader.cc.
References m_linksList.
Referenced by ns3::RocketfuelTopologyReader::GenerateFromWeightsFile().
LinksEmpty()
bool ns3::TopologyReader::LinksEmpty (void) const
Checks if the block contains any links.
Returns
True if there are no links in this block, false otherwise.
Definition at line 90 of file topology-reader.cc.
References m_linksList.
LinksEnd()
TopologyReader::ConstLinksIterator ns3::TopologyReader::LinksEnd (void) const
Returns an iterator to the the last link in this block.
Returns
A const iterator to the last link in this block.
Definition at line 78 of file topology-reader.cc.
References m_linksList.
Referenced by ns3::RocketfuelTopologyReader::GenerateFromWeightsFile().
LinksSize()
int ns3::TopologyReader::LinksSize (void) const
Returns the number of links in this block.
Returns
The number of links in this block.
Definition at line 84 of file topology-reader.cc.
References m_linksList.
operator=()
TopologyReader& ns3::TopologyReader::operator= (const TopologyReader &) private
Copy constructor.
Defined and unimplemented to avoid misuse.
Returns
Read()
virtual NodeContainer ns3::TopologyReader::Read (void) pure virtual
Main topology reading function.
The data is parsed and the results are returned in the passed lists. The rationale behind this choice is to allow non-progressive node IDs in the topology files, as well as to separate the topology reader from the choices about actual IP number assignment and kind of links between nodes.
Returns
The container of the nodes created (or null if there was an error).
Implemented in ns3::RocketfuelTopologyReader, ns3::OrbisTopologyReader, and ns3::InetTopologyReader.
SetFileName()
void ns3::TopologyReader::SetFileName (const std::string & fileName)
Sets the input file name.
Parameters
[in] fileName The input file name.
Definition at line 58 of file topology-reader.cc.
References m_fileName.
Member Data Documentation
m_fileName
std::string ns3::TopologyReader::m_fileName private
The name of the input file.
Definition at line 226 of file topology-reader.h.
Referenced by GetFileName(), and SetFileName().
m_linksList
std::list<Link> ns3::TopologyReader::m_linksList private
The container of the links between the nodes.
Definition at line 231 of file topology-reader.h.
Referenced by AddLink(), LinksBegin(), LinksEmpty(), LinksEnd(), and LinksSize().
The documentation for this class was generated from the following files:
src/topology-read/model/topology-reader.h
src/topology-read/model/topology-reader.cc