ns-3: ns3::CallbackImpl< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 > Class Template Reference
ns3::CallbackImpl< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 > Class Template Reference abstract
Core » Callbacks » Callback Implementation
The unqualified CallbackImpl class.
#include "callback.h"
Public Member Functions
virtual ~CallbackImpl ()
virtual std::string GetTypeid (void) const
Get the name of this object type.
virtual R operator() (T1, T2, T3, T4, T5, T6, T7, T8, T9)=0
Public Member Functions inherited from ns3::CallbackImplBase
virtual ~CallbackImplBase ()
Virtual destructor.
virtual bool IsEqual (Ptr< const CallbackImplBase > other) const =0
Equality test.
Public Member Functions inherited from ns3::SimpleRefCount< CallbackImplBase >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Static Public Member Functions
static std::string DoGetTypeid (void)
Get the name of this object type.
Additional Inherited Members
Static Protected Member Functions inherited from ns3::CallbackImplBase
static std::string Demangle (const std::string &mangled)
template<typename T >
static std::string GetCppTypeid (void)
Helper to get the C++ typeid as a string.
Detailed Description
template<typename R, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9>
class ns3::CallbackImpl< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >
The unqualified CallbackImpl class.
CallbackImpl class with nine arguments.
Template Parameters
R [explicit] The return type of the Callback. The remaining template arguments are the types of any arguments to the Callback.
Definition at line 398 of file callback.h.
Constructor & Destructor Documentation
~CallbackImpl()
template<typename R , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 > virtual ns3::CallbackImpl< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::~CallbackImpl () inline virtual
Definition at line 401 of file callback.h.
Member Function Documentation
DoGetTypeid()
template<typename R , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 > static std::string ns3::CallbackImpl< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::DoGetTypeid (void) inline static
Get the name of this object type.
Returns
The object type as a string.
Definition at line 409 of file callback.h.
Referenced by ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::DoAssign(), ns3::CallbackImpl< R, empty, empty, empty, empty, empty, empty, empty, empty, empty >::GetTypeid(), ns3::CallbackImpl< R, T1, empty, empty, empty, empty, empty, empty, empty, empty >::GetTypeid(), ns3::CallbackImpl< R, T1, T2, empty, empty, empty, empty, empty, empty, empty >::GetTypeid(), ns3::CallbackImpl< R, T1, T2, T3, empty, empty, empty, empty, empty, empty >::GetTypeid(), ns3::CallbackImpl< R, T1, T2, T3, T4, empty, empty, empty, empty, empty >::GetTypeid(), ns3::CallbackImpl< R, T1, T2, T3, T4, T5, empty, empty, empty, empty >::GetTypeid(), ns3::CallbackImpl< R, T1, T2, T3, T4, T5, T6, empty, empty, empty >::GetTypeid(), ns3::CallbackImpl< R, T1, T2, T3, T4, T5, T6, T7, empty, empty >::GetTypeid(), ns3::CallbackImpl< R, T1, T2, T3, T4, T5, T6, T7, T8, empty >::GetTypeid(), and ns3::CallbackImpl< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::GetTypeid().
GetTypeid()
template<typename R , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 > virtual std::string ns3::CallbackImpl< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::GetTypeid (void) const inline virtual
Get the name of this object type.
Returns
The object type as a string.
Implements ns3::CallbackImplBase.
Definition at line 404 of file callback.h.
References ns3::CallbackImpl< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::DoGetTypeid().
operator()()
template<typename R , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 > virtual R ns3::CallbackImpl< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::operator() (T1 , T2 , T3 , T4 , T5 , T6 , T7 , T8 , T9) pure virtual
Returns
Callback value
Implemented in ns3::MemPtrCallbackImpl< OBJ_PTR, MEM_PTR, R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >, and ns3::FunctorCallbackImpl< T, R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >.
The documentation for this class was generated from the following file:
src/core/model/callback.h