ns-3: ns3::WifiRadioEnergyModelPhyListener Class Reference
ns3::WifiRadioEnergyModelPhyListener Class Reference
Energy Models
A WifiPhy listener class for notifying the WifiRadioEnergyModel of Wifi radio state change.
#include "wifi-radio-energy-model.h"
Public Types
typedef Callback< void, double > UpdateTxCurrentCallback
Callback type for updating the transmit current based on the nominal TX power.
Public Member Functions
WifiRadioEnergyModelPhyListener ()
virtual ~WifiRadioEnergyModelPhyListener ()
void NotifyMaybeCcaBusyStart (Time duration)
void NotifyOff (void)
Defined in ns3::WifiPhyListener.
void NotifyOn (void)
Defined in ns3::WifiPhyListener.
void NotifyRxEndError (void)
Switches the WifiRadioEnergyModel back to IDLE state.
void NotifyRxEndOk (void)
Switches the WifiRadioEnergyModel back to IDLE state.
void NotifyRxStart (Time duration)
Switches the WifiRadioEnergyModel to RX state.
void NotifySleep (void)
Defined in ns3::WifiPhyListener.
void NotifySwitchingStart (Time duration)
void NotifyTxStart (Time duration, double txPowerDbm)
Switches the WifiRadioEnergyModel to TX state and switches back to IDLE after TX duration.
void NotifyWakeup (void)
Defined in ns3::WifiPhyListener.
void SetChangeStateCallback (DeviceEnergyModel::ChangeStateCallback callback)
Sets the change state callback.
void SetUpdateTxCurrentCallback (UpdateTxCurrentCallback callback)
Sets the update TX current callback.
Public Member Functions inherited from ns3::WifiPhyListener
virtual ~WifiPhyListener ()
Private Member Functions
void SwitchToIdle (void)
A helper function that makes scheduling m_changeStateCallback possible.
Private Attributes
DeviceEnergyModel::ChangeStateCallback m_changeStateCallback
Change state callback used to notify the WifiRadioEnergyModel of a state change.
EventId m_switchToIdleEvent
switch to idle event
UpdateTxCurrentCallback m_updateTxCurrentCallback
Callback used to update the TX current stored in WifiRadioEnergyModel based on the nominal TX power used to transmit the current frame.
Detailed Description
A WifiPhy listener class for notifying the WifiRadioEnergyModel of Wifi radio state change.
Definition at line 42 of file wifi-radio-energy-model.h.
Member Typedef Documentation
UpdateTxCurrentCallback
typedef Callback<void, double> ns3::WifiRadioEnergyModelPhyListener::UpdateTxCurrentCallback
Callback type for updating the transmit current based on the nominal TX power.
Definition at line 48 of file wifi-radio-energy-model.h.
Constructor & Destructor Documentation
WifiRadioEnergyModelPhyListener()
ns3::WifiRadioEnergyModelPhyListener::WifiRadioEnergyModelPhyListener ()
Definition at line 462 of file wifi-radio-energy-model.cc.
References m_changeStateCallback, m_updateTxCurrentCallback, NS_LOG_FUNCTION, and ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::Nullify().
~WifiRadioEnergyModelPhyListener()
ns3::WifiRadioEnergyModelPhyListener::~WifiRadioEnergyModelPhyListener () virtual
Definition at line 469 of file wifi-radio-energy-model.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
NotifyMaybeCcaBusyStart()
void ns3::WifiRadioEnergyModelPhyListener::NotifyMaybeCcaBusyStart (Time duration) virtual
Parameters
duration the expected busy duration.
Defined in ns3::WifiPhyListener
Implements ns3::WifiPhyListener.
Definition at line 544 of file wifi-radio-energy-model.cc.
References ns3::EventId::Cancel(), CCA_BUSY, ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_changeStateCallback, m_switchToIdleEvent, NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), and SwitchToIdle().
NotifyOff()
void ns3::WifiRadioEnergyModelPhyListener::NotifyOff (void) virtual
Defined in ns3::WifiPhyListener.
Implements ns3::WifiPhyListener.
Definition at line 595 of file wifi-radio-energy-model.cc.
References ns3::EventId::Cancel(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_changeStateCallback, m_switchToIdleEvent, NS_FATAL_ERROR, NS_LOG_FUNCTION, and OFF.
NotifyOn()
void ns3::WifiRadioEnergyModelPhyListener::NotifyOn (void) virtual
Defined in ns3::WifiPhyListener.
Implements ns3::WifiPhyListener.
Definition at line 607 of file wifi-radio-energy-model.cc.
References IDLE, ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_changeStateCallback, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
NotifyRxEndError()
void ns3::WifiRadioEnergyModelPhyListener::NotifyRxEndError (void) virtual
Switches the WifiRadioEnergyModel back to IDLE state.
Defined in ns3::WifiPhyListener
Note that for the WifiRadioEnergyModel, the behavior of the function is the same as NotifyRxEndOk.
Implements ns3::WifiPhyListener.
Definition at line 514 of file wifi-radio-energy-model.cc.
References IDLE, ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_changeStateCallback, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
NotifyRxEndOk()
void ns3::WifiRadioEnergyModelPhyListener::NotifyRxEndOk (void) virtual
Switches the WifiRadioEnergyModel back to IDLE state.
Defined in ns3::WifiPhyListener
Note that for the WifiRadioEnergyModel, the behavior of the function is the same as NotifyRxEndError.
Implements ns3::WifiPhyListener.
Definition at line 503 of file wifi-radio-energy-model.cc.
References IDLE, ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_changeStateCallback, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
NotifyRxStart()
void ns3::WifiRadioEnergyModelPhyListener::NotifyRxStart (Time duration) virtual
Switches the WifiRadioEnergyModel to RX state.
Parameters
duration the expected duration of the packet reception.
Defined in ns3::WifiPhyListener
Implements ns3::WifiPhyListener.
Definition at line 491 of file wifi-radio-energy-model.cc.
References ns3::EventId::Cancel(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_changeStateCallback, m_switchToIdleEvent, NS_FATAL_ERROR, NS_LOG_FUNCTION, and RX.
NotifySleep()
void ns3::WifiRadioEnergyModelPhyListener::NotifySleep (void) virtual
Defined in ns3::WifiPhyListener.
Implements ns3::WifiPhyListener.
Definition at line 572 of file wifi-radio-energy-model.cc.
References ns3::EventId::Cancel(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_changeStateCallback, m_switchToIdleEvent, NS_FATAL_ERROR, NS_LOG_FUNCTION, and SLEEP.
NotifySwitchingStart()
void ns3::WifiRadioEnergyModelPhyListener::NotifySwitchingStart (Time duration) virtual
Parameters
duration the expected channel switching duration.
Defined in ns3::WifiPhyListener
Implements ns3::WifiPhyListener.
Definition at line 558 of file wifi-radio-energy-model.cc.
References ns3::EventId::Cancel(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_changeStateCallback, m_switchToIdleEvent, NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), SWITCHING, and SwitchToIdle().
NotifyTxStart()
void ns3::WifiRadioEnergyModelPhyListener::NotifyTxStart (Time duration, double txPowerDbm) virtual
Switches the WifiRadioEnergyModel to TX state and switches back to IDLE after TX duration.
Parameters
duration the expected transmission duration.
txPowerDbm the nominal TX power in dBm
Defined in ns3::WifiPhyListener
Implements ns3::WifiPhyListener.
Definition at line 525 of file wifi-radio-energy-model.cc.
References ns3::EventId::Cancel(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_changeStateCallback, m_switchToIdleEvent, m_updateTxCurrentCallback, NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), SwitchToIdle(), and TX.
NotifyWakeup()
void ns3::WifiRadioEnergyModelPhyListener::NotifyWakeup (void) virtual
Defined in ns3::WifiPhyListener.
Implements ns3::WifiPhyListener.
Definition at line 584 of file wifi-radio-energy-model.cc.
References IDLE, ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_changeStateCallback, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
SetChangeStateCallback()
void ns3::WifiRadioEnergyModelPhyListener::SetChangeStateCallback (DeviceEnergyModel::ChangeStateCallback callback)
Sets the change state callback.
Used by helper class.
Parameters
callback Change state callback.
Definition at line 475 of file wifi-radio-energy-model.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_changeStateCallback, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::WifiRadioEnergyModel::WifiRadioEnergyModel().
SetUpdateTxCurrentCallback()
void ns3::WifiRadioEnergyModelPhyListener::SetUpdateTxCurrentCallback (UpdateTxCurrentCallback callback)
Sets the update TX current callback.
Parameters
callback Update TX current callback.
Definition at line 483 of file wifi-radio-energy-model.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_updateTxCurrentCallback, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::WifiRadioEnergyModel::WifiRadioEnergyModel().
SwitchToIdle()
void ns3::WifiRadioEnergyModelPhyListener::SwitchToIdle (void) private
A helper function that makes scheduling m_changeStateCallback possible.
Definition at line 618 of file wifi-radio-energy-model.cc.
References IDLE, ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_changeStateCallback, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
Referenced by NotifyMaybeCcaBusyStart(), NotifySwitchingStart(), and NotifyTxStart().
Member Data Documentation
m_changeStateCallback
DeviceEnergyModel::ChangeStateCallback ns3::WifiRadioEnergyModelPhyListener::m_changeStateCallback private
Change state callback used to notify the WifiRadioEnergyModel of a state change.
Definition at line 152 of file wifi-radio-energy-model.h.
Referenced by WifiRadioEnergyModelPhyListener(), NotifyMaybeCcaBusyStart(), NotifyOff(), NotifyOn(), NotifyRxEndError(), NotifyRxEndOk(), NotifyRxStart(), NotifySleep(), NotifySwitchingStart(), NotifyTxStart(), NotifyWakeup(), SetChangeStateCallback(), and SwitchToIdle().
m_switchToIdleEvent
EventId ns3::WifiRadioEnergyModelPhyListener::m_switchToIdleEvent private
switch to idle event
Definition at line 160 of file wifi-radio-energy-model.h.
Referenced by NotifyMaybeCcaBusyStart(), NotifyOff(), NotifyRxStart(), NotifySleep(), NotifySwitchingStart(), and NotifyTxStart().
m_updateTxCurrentCallback
UpdateTxCurrentCallback ns3::WifiRadioEnergyModelPhyListener::m_updateTxCurrentCallback private
Callback used to update the TX current stored in WifiRadioEnergyModel based on the nominal TX power used to transmit the current frame.
Definition at line 158 of file wifi-radio-energy-model.h.
Referenced by WifiRadioEnergyModelPhyListener(), NotifyTxStart(), and SetUpdateTxCurrentCallback().
The documentation for this class was generated from the following files:
src/wifi/model/wifi-radio-energy-model.h
src/wifi/model/wifi-radio-energy-model.cc