ns-3: ns3::WimaxConnection Class Reference
ns3::WimaxConnection Class Reference
WiMAX Models
Class to represent WiMAX connections.
#include "wimax-connection.h"
Public Types
typedef std::list< Ptr< const Packet > > FragmentsQueue
Definition of Fragments Queue data type.
Public Member Functions
WimaxConnection (Cid cid, enum Cid::Type type)
Constructor.
~WimaxConnection (void)
void ClearFragmentsQueue (void)
delete all enqueued fragments
Ptr< Packet > Dequeue (MacHeaderType::HeaderType packetType, uint32_t availableByte)
dequeue a packet from the queue of the connection Dequeue the first packet in the queue if its size is lower than availableByte, the first availableByte of the first packet otherwise
Ptr< Packet > Dequeue (MacHeaderType::HeaderType packetType=MacHeaderType::HEADER_TYPE_GENERIC)
dequeue a packet from the queue of the connection
bool Enqueue (Ptr< Packet > packet, const MacHeaderType &hdrType, const GenericMacHeader &hdr)
enqueue a packet in the queue of the connection
void FragmentEnqueue (Ptr< const Packet > fragment)
enqueue a received packet (that is a fragment) into the fragments queue
Cid GetCid (void) const
Get CID function.
const FragmentsQueue GetFragmentsQueue (void) const
get a queue of received fragments
Ptr< WimaxMacQueue > GetQueue (void) const
uint8_t GetSchedulingType (void) const
ServiceFlow * GetServiceFlow (void) const
enum Cid::Type GetType (void) const
Get type function.
std::string GetTypeStr (void) const
Get type string.
bool HasPackets (MacHeaderType::HeaderType packetType) const
bool HasPackets (void) const
void SetServiceFlow (ServiceFlow *serviceFlow)
set the service flow associated to this connection
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual void DoDispose (void)
Destructor implementation.
Private Attributes
Cid m_cid
CID.
enum Cid::Type m_cidType
CID type.
FragmentsQueue m_fragmentsQueue
fragments queue
Ptr< WimaxMacQueue > m_queue
queue
ServiceFlow * m_serviceFlow
service flow
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Class to represent WiMAX connections.
Config Paths
ns3::WimaxConnection is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WimaxNetDevice/InitialRangingConnection"
"/NodeList/[i]/DeviceList/[i]/$ns3::WimaxNetDevice/BroadcastConnection"
"/NodeList/[i]/DeviceList/[i]/$ns3::WimaxNetDevice/$ns3::SubscriberStationNetDevice/BasicConnection"
"/NodeList/[i]/DeviceList/[i]/$ns3::WimaxNetDevice/$ns3::SubscriberStationNetDevice/PrimaryConnection"
"/NodeList/[i]/DeviceList/[i]/$ns3::SubscriberStationNetDevice/BasicConnection"
"/NodeList/[i]/DeviceList/[i]/$ns3::SubscriberStationNetDevice/PrimaryConnection"
Attributes
Type: Connection type
Set with class: ns3::EnumValue
Underlying type:
Flags: read
TxQueue: Transmit queue
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::WimaxMacQueue>
Flags: read
No TraceSources are defined for this type.
Size of this type is 80 bytes (on a 64-bit architecture).
Definition at line 42 of file wimax-connection.h.
Member Typedef Documentation
FragmentsQueue
typedef std::list<Ptr<const Packet> > ns3::WimaxConnection::FragmentsQueue
Definition of Fragments Queue data type.
Definition at line 132 of file wimax-connection.h.
Constructor & Destructor Documentation
WimaxConnection()
ns3::WimaxConnection::WimaxConnection (Cid cid, enum Cid::Type type)
Constructor.
Parameters
cid connection ID
type CID type
Definition at line 67 of file wimax-connection.cc.
~WimaxConnection()
ns3::WimaxConnection::~WimaxConnection (void)
Definition at line 75 of file wimax-connection.cc.
Member Function Documentation
ClearFragmentsQueue()
void ns3::WimaxConnection::ClearFragmentsQueue (void)
delete all enqueued fragments
Definition at line 197 of file wimax-connection.cc.
References m_fragmentsQueue.
Referenced by Ns3WimaxFragmentationTestCase::DoRun().
Dequeue() [1/2]
Ptr< Packet > ns3::WimaxConnection::Dequeue (MacHeaderType::HeaderType packetType, uint32_t availableByte)
dequeue a packet from the queue of the connection Dequeue the first packet in the queue if its size is lower than availableByte, the first availableByte of the first packet otherwise
Parameters
packetType the type of the packet to dequeue
availableByte the number of available bytes
Returns
packet dequeued
Definition at line 136 of file wimax-connection.cc.
References m_queue.
Dequeue() [2/2]
Ptr< Packet > ns3::WimaxConnection::Dequeue (MacHeaderType::HeaderType packetType = MacHeaderType::HEADER_TYPE_GENERIC)
dequeue a packet from the queue of the connection
Parameters
packetType the type of the packet to dequeue
Returns
packet dequeued
Definition at line 130 of file wimax-connection.cc.
References m_queue.
Referenced by Ns3WimaxFragmentationTestCase::DoRun().
DoDispose()
void ns3::WimaxConnection::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 80 of file wimax-connection.cc.
References m_queue.
Enqueue()
bool ns3::WimaxConnection::Enqueue (Ptr< Packet > packet, const MacHeaderType & hdrType, const GenericMacHeader & hdr)
enqueue a packet in the queue of the connection
Parameters
packet the packet to be enqueued
hdrType the header type of the packet
hdr the header of the packet
Returns
true if successful
Definition at line 123 of file wimax-connection.cc.
References m_queue.
Referenced by Ns3WimaxFragmentationTestCase::DoRun().
FragmentEnqueue()
void ns3::WimaxConnection::FragmentEnqueue (Ptr< const Packet > fragment)
enqueue a received packet (that is a fragment) into the fragments queue
Parameters
fragment received fragment
Definition at line 191 of file wimax-connection.cc.
References m_fragmentsQueue.
Referenced by Ns3WimaxFragmentationTestCase::DoRun().
GetCid()
Cid ns3::WimaxConnection::GetCid (void) const
Get CID function.
Returns
the CID
Definition at line 87 of file wimax-connection.cc.
References m_cid.
Referenced by Ns3WimaxFragmentationTestCase::DoRun().
GetFragmentsQueue()
const WimaxConnection::FragmentsQueue ns3::WimaxConnection::GetFragmentsQueue (void) const
get a queue of received fragments
Returns
the fragments queue
Definition at line 185 of file wimax-connection.cc.
References m_fragmentsQueue.
Referenced by Ns3WimaxFragmentationTestCase::DoRun().
GetQueue()
Ptr< WimaxMacQueue > ns3::WimaxConnection::GetQueue (void) const
Returns
the queue of the connection
Definition at line 99 of file wimax-connection.cc.
References m_queue.
Referenced by Ns3WimaxFragmentationTestCase::DoRun(), and GetTypeId().
GetSchedulingType()
uint8_t ns3::WimaxConnection::GetSchedulingType (void) const
Returns
the scheduling type of this connection
Definition at line 117 of file wimax-connection.cc.
References ns3::ServiceFlow::GetSchedulingType(), and m_serviceFlow.
GetServiceFlow()
ServiceFlow * ns3::WimaxConnection::GetServiceFlow (void) const
Returns
the service flow associated to this connection
Definition at line 111 of file wimax-connection.cc.
References m_serviceFlow.
GetType()
enum Cid::Type ns3::WimaxConnection::GetType (void) const
Get type function.
Returns
the type
Definition at line 87 of file wimax-connection.cc.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::WimaxConnection::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 32 of file wimax-connection.cc.
References ns3::Cid::BASIC, ns3::Cid::BROADCAST, GetQueue(), GetType(), ns3::Cid::INITIAL_RANGING, ns3::MakeEnumAccessor(), ns3::MakeEnumChecker(), ns3::MakePointerAccessor(), ns3::Cid::MULTICAST, ns3::Cid::PADDING, ns3::Cid::PRIMARY, ns3::TypeId::SetParent(), and ns3::Cid::TRANSPORT.
GetTypeStr()
std::string ns3::WimaxConnection::GetTypeStr (void) const
Get type string.
Returns
the type string
Definition at line 154 of file wimax-connection.cc.
References ns3::Cid::BASIC, ns3::Cid::BROADCAST, ns3::Cid::INITIAL_RANGING, m_cidType, ns3::Cid::MULTICAST, NS_FATAL_ERROR, ns3::Cid::PRIMARY, and ns3::Cid::TRANSPORT.
HasPackets() [1/2]
bool ns3::WimaxConnection::HasPackets (MacHeaderType::HeaderType packetType) const
Returns
true if the connection has at least one packet of type packetType in its queue, false otherwise
Parameters
packetType type of packet to check in the queue
Returns
true if packets available
Definition at line 148 of file wimax-connection.cc.
References m_queue.
HasPackets() [2/2]
bool ns3::WimaxConnection::HasPackets (void) const
Returns
true if the connection has at least one packet in its queue, false otherwise
Definition at line 142 of file wimax-connection.cc.
References m_queue.
SetServiceFlow()
void ns3::WimaxConnection::SetServiceFlow (ServiceFlow * serviceFlow)
set the service flow associated to this connection
Parameters
serviceFlow The service flow to be associated to this connection
Definition at line 105 of file wimax-connection.cc.
References m_serviceFlow.
Member Data Documentation
m_cid
Cid ns3::WimaxConnection::m_cid private
CID.
Definition at line 151 of file wimax-connection.h.
Referenced by GetCid().
m_cidType
enum Cid::Type ns3::WimaxConnection::m_cidType private
CID type.
Definition at line 151 of file wimax-connection.h.
Referenced by GetTypeStr().
m_fragmentsQueue
FragmentsQueue ns3::WimaxConnection::m_fragmentsQueue private
fragments queue
Definition at line 157 of file wimax-connection.h.
Referenced by ClearFragmentsQueue(), FragmentEnqueue(), and GetFragmentsQueue().
m_queue
Ptr<WimaxMacQueue> ns3::WimaxConnection::m_queue private
queue
Definition at line 153 of file wimax-connection.h.
Referenced by Dequeue(), DoDispose(), Enqueue(), GetQueue(), and HasPackets().
m_serviceFlow
ServiceFlow* ns3::WimaxConnection::m_serviceFlow private
service flow
Definition at line 154 of file wimax-connection.h.
Referenced by GetSchedulingType(), GetServiceFlow(), and SetServiceFlow().
The documentation for this class was generated from the following files:
src/wimax/model/wimax-connection.h
src/wimax/model/wimax-connection.cc