ns-3: ns3::LrWpanHelper Class Reference
ns3::LrWpanHelper Class Reference
LR-WPAN models
helps to manage and create IEEE 802.15.4 NetDevice objects
#include "lr-wpan-helper.h"
Public Member Functions
LrWpanHelper (bool useMultiModelSpectrumChannel)
Create a LrWpan helper in an empty state with either a SingleModelSpectrumChannel or a MultiModelSpectrumChannel.
LrWpanHelper (void)
Create a LrWpan helper in an empty state.
virtual ~LrWpanHelper (void)
void AddMobility (Ptr< LrWpanPhy > phy, Ptr< MobilityModel > m)
Add mobility model to a physical device.
int64_t AssignStreams (NetDeviceContainer c, int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
void AssociateToBeaconPan (NetDeviceContainer c, uint16_t panId, Mac16Address coor, uint8_t bcnOrd, uint8_t sfrmOrd)
Associate the nodes to the same PAN and initiate beacon enabled mode.
void AssociateToPan (NetDeviceContainer c, uint16_t panId)
Associate the nodes to the same PAN.
void EnableLogComponents (void)
Helper to enable all LrWpan log components with one statement.
Ptr< SpectrumChannel > GetChannel (void)
Get the channel associated to this helper.
NetDeviceContainer Install (NodeContainer c)
Install a LrWpanNetDevice and the associated structures (e.g., channel) in the nodes.
void SetChannel (Ptr< SpectrumChannel > channel)
Set the channel associated to this helper.
void SetChannel (std::string channelName)
Set the channel associated to this helper.
Public Member Functions inherited from ns3::PcapHelperForDevice
PcapHelperForDevice ()
Construct a PcapHelperForDevice.
virtual ~PcapHelperForDevice ()
Destroy a PcapHelperForDevice.
void EnablePcap (std::string prefix, NetDeviceContainer d, bool promiscuous=false)
Enable pcap output on each device in the container which is of the appropriate type.
void EnablePcap (std::string prefix, NodeContainer n, bool promiscuous=false)
Enable pcap output on each device (which is of the appropriate type) in the nodes provided in the container.
void EnablePcap (std::string prefix, Ptr< NetDevice > nd, bool promiscuous=false, bool explicitFilename=false)
Enable pcap output the indicated net device.
void EnablePcap (std::string prefix, std::string ndName, bool promiscuous=false, bool explicitFilename=false)
Enable pcap output the indicated net device using a device previously named using the ns-3 object name service.
void EnablePcap (std::string prefix, uint32_t nodeid, uint32_t deviceid, bool promiscuous=false)
Enable pcap output on the device specified by a global node-id (of a previously created node) and associated device-id.
void EnablePcapAll (std::string prefix, bool promiscuous=false)
Enable pcap output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
Public Member Functions inherited from ns3::AsciiTraceHelperForDevice
AsciiTraceHelperForDevice ()
Construct an AsciiTraceHelperForDevice.
virtual ~AsciiTraceHelperForDevice ()
Destroy an AsciiTraceHelperForDevice.
void EnableAscii (Ptr< OutputStreamWrapper > stream, NetDeviceContainer d)
Enable ascii trace output on each device in the container which is of the appropriate type.
void EnableAscii (Ptr< OutputStreamWrapper > stream, NodeContainer n)
Enable ascii trace output on each device (which is of the appropriate type) in the nodes provided in the container.
void EnableAscii (Ptr< OutputStreamWrapper > stream, Ptr< NetDevice > nd)
Enable ascii trace output on the indicated net device.
void EnableAscii (Ptr< OutputStreamWrapper > stream, std::string ndName)
Enable ascii trace output the indicated net device using a device previously named using the ns-3 object name service.
void EnableAscii (Ptr< OutputStreamWrapper > stream, uint32_t nodeid, uint32_t deviceid)
Enable ascii trace output on the device specified by a global node-id (of a previously created node) and associated device-id.
void EnableAscii (std::string prefix, NetDeviceContainer d)
Enable ascii trace output on each device in the container which is of the appropriate type.
void EnableAscii (std::string prefix, NodeContainer n)
Enable ascii trace output on each device (which is of the appropriate type) in the nodes provided in the container.
void EnableAscii (std::string prefix, Ptr< NetDevice > nd, bool explicitFilename=false)
Enable ascii trace output on the indicated net device.
void EnableAscii (std::string prefix, std::string ndName, bool explicitFilename=false)
Enable ascii trace output the indicated net device using a device previously named using the ns-3 object name service.
void EnableAscii (std::string prefix, uint32_t nodeid, uint32_t deviceid, bool explicitFilename)
Enable ascii trace output on the device specified by a global node-id (of a previously created node) and associated device-id.
void EnableAsciiAll (Ptr< OutputStreamWrapper > stream)
Enable ascii trace output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
void EnableAsciiAll (std::string prefix)
Enable ascii trace output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
Static Public Member Functions
static std::string LrWpanMacStatePrinter (LrWpanMacState e)
Transform the LrWpanMacState enumeration into a printable string.
static std::string LrWpanPhyEnumerationPrinter (LrWpanPhyEnumeration e)
Transform the LrWpanPhyEnumeration enumeration into a printable string.
Private Member Functions
LrWpanHelper (LrWpanHelper const &)
Copy constructor - defined and not implemented.
virtual void EnableAsciiInternal (Ptr< OutputStreamWrapper > stream, std::string prefix, Ptr< NetDevice > nd, bool explicitFilename)
Enable ascii trace output on the indicated net device.
virtual void EnablePcapInternal (std::string prefix, Ptr< NetDevice > nd, bool promiscuous, bool explicitFilename)
Enable pcap output on the indicated net device.
LrWpanHelper & operator= (LrWpanHelper const &)
Copy constructor - defined and not implemented.
Private Attributes
Ptr< SpectrumChannel > m_channel
channel to be used for the devices
Detailed Description
helps to manage and create IEEE 802.15.4 NetDevice objects
This class can help to create IEEE 802.15.4 NetDevice objects and to configure their attributes during creation. It also contains additional helper functions used by client code.
Only one channel is created, and all devices attached to it. If multiple channels are needed, multiple helper objects must be used, or else the channel object must be replaced.
Definition at line 49 of file lr-wpan-helper.h.
Constructor & Destructor Documentation
LrWpanHelper() [1/3]
ns3::LrWpanHelper::LrWpanHelper (void)
Create a LrWpan helper in an empty state.
By default, a SingleModelSpectrumChannel is created, with a LogDistancePropagationLossModel and a ConstantSpeedPropagationDelayModel.
To change the channel type, loss model, or delay model, the Get/Set Channel methods may be used.
Definition at line 66 of file lr-wpan-helper.cc.
References m_channel.
LrWpanHelper() [2/3]
ns3::LrWpanHelper::LrWpanHelper (bool useMultiModelSpectrumChannel)
Create a LrWpan helper in an empty state with either a SingleModelSpectrumChannel or a MultiModelSpectrumChannel.
Parameters
useMultiModelSpectrumChannel use a MultiModelSpectrumChannel if true, a SingleModelSpectrumChannel otherwise
A LogDistancePropagationLossModel and a ConstantSpeedPropagationDelayModel are added to the channel.
Definition at line 77 of file lr-wpan-helper.cc.
References m_channel.
~LrWpanHelper()
ns3::LrWpanHelper::~LrWpanHelper (void) virtual
Definition at line 94 of file lr-wpan-helper.cc.
References m_channel.
LrWpanHelper() [3/3]
ns3::LrWpanHelper::LrWpanHelper (LrWpanHelper const &) private
Copy constructor - defined and not implemented.
Member Function Documentation
AddMobility()
void ns3::LrWpanHelper::AddMobility (Ptr< LrWpanPhy > phy, Ptr< MobilityModel > m)
Add mobility model to a physical device.
Parameters
phy the physical device
m the mobility model
Definition at line 170 of file lr-wpan-helper.cc.
References third::phy.
AssignStreams()
int64_t ns3::LrWpanHelper::AssignStreams (NetDeviceContainer c, int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams that have been assigned. The Install() method should have previously been called by the user.
Parameters
c NetDeviceContainer of the set of net devices for which the CsmaNetDevice should be modified to use a fixed stream
stream first stream index to use
Returns
the number of stream indices assigned by this helper
Definition at line 216 of file lr-wpan-helper.cc.
References ns3::LrWpanNetDevice::AssignStreams(), ns3::NetDeviceContainer::Begin(), and ns3::NetDeviceContainer::End().
AssociateToBeaconPan()
void ns3::LrWpanHelper::AssociateToBeaconPan (NetDeviceContainer c, uint16_t panId, Mac16Address coor, uint8_t bcnOrd, uint8_t sfrmOrd)
Associate the nodes to the same PAN and initiate beacon enabled mode.
Parameters
c a set of nodes
panID the PAN id
coor the address of the PAN coordinator
bcnOrd indicates the interval between beacons. The value must be an int between 0 and 14.
sfrmOrd indicates the length of the superframe. The value must be an int between 0 and 14 and less or equal to the bcnOrd
Definition at line 258 of file lr-wpan-helper.cc.
References first::address, ns3::NetDeviceContainer::Begin(), first::devices, ns3::NetDeviceContainer::End(), ns3::UniformRandomVariable::GetInteger(), ns3::LrWpanNetDevice::GetMac(), ns3::MlmeStartRequestParams::m_bcnOrd, ns3::MlmeStartRequestParams::m_panCoor, ns3::MlmeStartRequestParams::m_PanId, ns3::MlmeStartRequestParams::m_sfrmOrd, ns3::MilliSeconds(), ns3::LrWpanMac::MlmeStartRequest(), NS_LOG_DEBUG, and ns3::Simulator::Schedule().
AssociateToPan()
void ns3::LrWpanHelper::AssociateToPan (NetDeviceContainer c, uint16_t panId)
Associate the nodes to the same PAN.
Parameters
c a set of nodes
panId the PAN Id
Definition at line 233 of file lr-wpan-helper.cc.
References first::address, ns3::NetDeviceContainer::Begin(), first::devices, ns3::NetDeviceContainer::End(), and ns3::LrWpanNetDevice::GetMac().
EnableAsciiInternal()
void ns3::LrWpanHelper::EnableAsciiInternal (Ptr< OutputStreamWrapper > stream, std::string prefix, Ptr< NetDevice > nd, bool explicitFilename) private virtual
Enable ascii trace output on the indicated net device.
NetDevice-specific implementation mechanism for hooking the trace and writing to the trace file.
Parameters
stream The output stream object to use when logging ascii traces.
prefix Filename prefix to use for ascii trace files.
nd Net device for which you want to enable tracing.
explicitFilename Treat the prefix as an explicit filename if true
Implements ns3::AsciiTraceHelperForDevice.
Definition at line 373 of file lr-wpan-helper.cc.
References ns3::AsciiLrWpanMacTransmitSinkWithContext(), ns3::AsciiLrWpanMacTransmitSinkWithoutContext(), ns3::AsciiTraceHelper::CreateFileStream(), ns3::AsciiTraceHelper::DefaultDequeueSinkWithContext(), ns3::AsciiTraceHelper::DefaultDropSinkWithContext(), ns3::AsciiTraceHelper::DefaultEnqueueSinkWithContext(), ns3::AsciiTraceHelper::DefaultReceiveSinkWithContext(), ns3::Packet::EnablePrinting(), ns3::AsciiTraceHelper::GetFilenameFromDevice(), ns3::LrWpanNetDevice::GetMac(), ns3::AsciiTraceHelper::HookDefaultDequeueSinkWithoutContext(), ns3::AsciiTraceHelper::HookDefaultDropSinkWithoutContext(), ns3::AsciiTraceHelper::HookDefaultEnqueueSinkWithoutContext(), ns3::AsciiTraceHelper::HookDefaultReceiveSinkWithoutContext(), ns3::MakeBoundCallback(), and NS_LOG_INFO.
EnableLogComponents()
void ns3::LrWpanHelper::EnableLogComponents (void)
Helper to enable all LrWpan log components with one statement.
Definition at line 101 of file lr-wpan-helper.cc.
References ns3::LOG_LEVEL_ALL, ns3::LOG_PREFIX_FUNC, ns3::LOG_PREFIX_TIME, ns3::LogComponentEnable(), and ns3::LogComponentEnableAll().
EnablePcapInternal()
void ns3::LrWpanHelper::EnablePcapInternal (std::string prefix, Ptr< NetDevice > nd, bool promiscuous, bool explicitFilename) private virtual
Enable pcap output on the indicated net device.
NetDevice-specific implementation mechanism for hooking the trace and writing to the trace file.
Parameters
prefix Filename prefix to use for pcap files.
nd Net device for which you want to enable tracing.
promiscuous If true capture all possible packets available at the device.
explicitFilename Treat the prefix as an explicit filename if true
Implements ns3::PcapHelperForDevice.
Definition at line 326 of file lr-wpan-helper.cc.
References ns3::PcapHelper::CreateFile(), ns3::PcapHelper::DLT_IEEE802_15_4, create-module::file, ns3::PcapHelper::GetFilenameFromDevice(), ns3::LrWpanNetDevice::GetMac(), ns3::MakeBoundCallback(), NS_LOG_FUNCTION, NS_LOG_INFO, and ns3::PcapSniffLrWpan().
GetChannel()
Ptr< SpectrumChannel > ns3::LrWpanHelper::GetChannel (void)
Get the channel associated to this helper.
Returns
the channel
Definition at line 196 of file lr-wpan-helper.cc.
References m_channel.
Install()
NetDeviceContainer ns3::LrWpanHelper::Install (NodeContainer c)
Install a LrWpanNetDevice and the associated structures (e.g., channel) in the nodes.
Parameters
c a set of nodes
Returns
A container holding the added net devices.
Definition at line 176 of file lr-wpan-helper.cc.
References ns3::Node::AddDevice(), ns3::NodeContainer::Begin(), first::devices, ns3::NodeContainer::End(), m_channel, ns3::LrWpanNetDevice::SetChannel(), and ns3::LrWpanNetDevice::SetNode().
LrWpanMacStatePrinter()
std::string ns3::LrWpanHelper::LrWpanMacStatePrinter (LrWpanMacState e) static
Transform the LrWpanMacState enumeration into a printable string.
Parameters
e the LrWpanMacState
Returns
a string
Definition at line 152 of file lr-wpan-helper.cc.
References ns3::CHANNEL_ACCESS_FAILURE, ns3::CHANNEL_IDLE, ns3::MAC_IDLE, and ns3::SET_PHY_TX_ON.
LrWpanPhyEnumerationPrinter()
std::string ns3::LrWpanHelper::LrWpanPhyEnumerationPrinter (LrWpanPhyEnumeration e) static
Transform the LrWpanPhyEnumeration enumeration into a printable string.
Parameters
e the LrWpanPhyEnumeration
Returns
a string
Definition at line 116 of file lr-wpan-helper.cc.
References ns3::IEEE_802_15_4_PHY_BUSY, ns3::IEEE_802_15_4_PHY_BUSY_RX, ns3::IEEE_802_15_4_PHY_BUSY_TX, ns3::IEEE_802_15_4_PHY_FORCE_TRX_OFF, ns3::IEEE_802_15_4_PHY_IDLE, ns3::IEEE_802_15_4_PHY_INVALID_PARAMETER, ns3::IEEE_802_15_4_PHY_READ_ONLY, ns3::IEEE_802_15_4_PHY_RX_ON, ns3::IEEE_802_15_4_PHY_SUCCESS, ns3::IEEE_802_15_4_PHY_TRX_OFF, ns3::IEEE_802_15_4_PHY_TX_ON, ns3::IEEE_802_15_4_PHY_UNSPECIFIED, and ns3::IEEE_802_15_4_PHY_UNSUPPORTED_ATTRIBUTE.
Referenced by StateChangeNotification().
operator=()
LrWpanHelper& ns3::LrWpanHelper::operator= (LrWpanHelper const &) private
Copy constructor - defined and not implemented.
Returns
SetChannel() [1/2]
void ns3::LrWpanHelper::SetChannel (Ptr< SpectrumChannel > channel)
Set the channel associated to this helper.
Parameters
channel the channel
Definition at line 202 of file lr-wpan-helper.cc.
References third::channel, and m_channel.
SetChannel() [2/2]
void ns3::LrWpanHelper::SetChannel (std::string channelName)
Set the channel associated to this helper.
Parameters
channelName the channel name
Definition at line 208 of file lr-wpan-helper.cc.
References third::channel, and m_channel.
Member Data Documentation
m_channel
Ptr<SpectrumChannel> ns3::LrWpanHelper::m_channel private
channel to be used for the devices
Definition at line 201 of file lr-wpan-helper.h.
Referenced by LrWpanHelper(), ~LrWpanHelper(), GetChannel(), Install(), and SetChannel().
The documentation for this class was generated from the following files:
src/lr-wpan/helper/lr-wpan-helper.h
src/lr-wpan/helper/lr-wpan-helper.cc