ns-3: ns3::Uinteger16Probe Class Reference
ns3::Uinteger16Probe Class Reference
Statistics » Probes
This class is designed to probe an underlying ns3 TraceSource exporting an uint16_t.
#include "uinteger-16-probe.h"
Public Member Functions
Uinteger16Probe ()
virtual ~Uinteger16Probe ()
virtual bool ConnectByObject (std::string traceSource, Ptr< Object > obj)
connect to a trace source attribute provided by a given object
virtual void ConnectByPath (std::string path)
connect to a trace source provided by a config path
uint16_t GetValue (void) const
void SetValue (uint16_t value)
Public Member Functions inherited from ns3::Probe
Probe ()
virtual ~Probe ()
virtual bool IsEnabled (void) const
Public Member Functions inherited from ns3::DataCollectionObject
DataCollectionObject ()
virtual ~DataCollectionObject ()
void Disable (void)
Unset the status of an individual object.
void Enable (void)
Set the status of an individual object.
std::string GetName (void) const
Get the object's name.
void SetName (std::string name)
Set the object's name. All spaces are replaced by underscores.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
static void SetValueByPath (std::string path, uint16_t value)
Set a probe value by its name in the Config system.
Static Public Member Functions inherited from ns3::Probe
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::DataCollectionObject
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void TraceSink (uint16_t oldData, uint16_t newData)
Method to connect to an underlying ns3::TraceSource of type uint16_t.
Private Attributes
TracedValue< uint16_t > m_output
Output trace source.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Probe
Time m_start
Time when logging starts.
Time m_stop
Time when logging stops.
Protected Attributes inherited from ns3::DataCollectionObject
bool m_enabled
Object's activation state.
std::string m_name
Name of the object within the data collection framework.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class is designed to probe an underlying ns3 TraceSource exporting an uint16_t.
Introspection did not find any typical Config paths.
This probe exports a trace source "Output" of type uint16_t. The Output trace source emits a value when either the trace source emits a new value, or when SetValue () is called.
The current value of the probe can be polled with the GetValue () method.
No Attributes are defined for this type.
Attributes defined in parent class ns3::Probe
Start: Time data collection starts
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
Stop: Time when data collection stops. The special time value of 0 disables this attribute
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
Attributes defined in parent class ns3::DataCollectionObject
Name: Object's name
Set with class: StringValue
Underlying type:
Initial value: unnamed
Flags: construct write read
Enabled: Object's enabled status
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
TraceSources
Output: The uint16_t that serves as output for this probe
Callback signature: ns3::TracedValueCallback::Uint16
Size of this type is 104 bytes (on a 64-bit architecture).
Definition at line 43 of file uinteger-16-probe.h.
Constructor & Destructor Documentation
Uinteger16Probe()
ns3::Uinteger16Probe::Uinteger16Probe ()
Definition at line 51 of file uinteger-16-probe.cc.
References m_output, and NS_LOG_FUNCTION.
~Uinteger16Probe()
ns3::Uinteger16Probe::~Uinteger16Probe () virtual
Definition at line 57 of file uinteger-16-probe.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
ConnectByObject()
bool ns3::Uinteger16Probe::ConnectByObject (std::string traceSource, Ptr< Object > obj) virtual
connect to a trace source attribute provided by a given object
Parameters
traceSource the name of the attribute TraceSource to connect to
obj ns3::Object to connect to
Returns
true if the trace source was successfully connected
Implements ns3::Probe.
Definition at line 85 of file uinteger-16-probe.cc.
References ns3::Names::FindPath(), ns3::MakeCallback(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::ObjectBase::TraceConnectWithoutContext(), and TraceSink().
ConnectByPath()
void ns3::Uinteger16Probe::ConnectByPath (std::string path) virtual
connect to a trace source provided by a config path
Parameters
path Config path to bind to
Note, if an invalid path is provided, the probe will not be connected to anything.
Implements ns3::Probe.
Definition at line 94 of file uinteger-16-probe.cc.
References ns3::Config::ConnectWithoutContext(), ns3::MakeCallback(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and TraceSink().
GetTypeId()
TypeId ns3::Uinteger16Probe::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 37 of file uinteger-16-probe.cc.
References m_output, ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
GetValue()
uint16_t ns3::Uinteger16Probe::GetValue (void) const
Returns
the most recent value
Definition at line 63 of file uinteger-16-probe.cc.
References m_output, and NS_LOG_FUNCTION.
SetValue()
void ns3::Uinteger16Probe::SetValue (uint16_t value)
Parameters
value set the traced uint16_t to a new value
Definition at line 69 of file uinteger-16-probe.cc.
References m_output, and NS_LOG_FUNCTION.
SetValueByPath()
void ns3::Uinteger16Probe::SetValueByPath (std::string path, uint16_t value) static
Set a probe value by its name in the Config system.
Parameters
path Config path to access the probe
value set the traced uint16_t to a new value
Definition at line 76 of file uinteger-16-probe.cc.
References NS_ASSERT_MSG, and NS_LOG_FUNCTION.
TraceSink()
void ns3::Uinteger16Probe::TraceSink (uint16_t oldData, uint16_t newData) private
Method to connect to an underlying ns3::TraceSource of type uint16_t.
Parameters
oldData previous value of the uint16_t
newData new value of the uint16_t
Definition at line 102 of file uinteger-16-probe.cc.
References ns3::Probe::IsEnabled(), m_output, and NS_LOG_FUNCTION.
Referenced by ConnectByObject(), and ConnectByPath().
Member Data Documentation
m_output
TracedValue<uint16_t> ns3::Uinteger16Probe::m_output private
Output trace source.
Definition at line 100 of file uinteger-16-probe.h.
Referenced by Uinteger16Probe(), GetTypeId(), GetValue(), SetValue(), and TraceSink().
The documentation for this class was generated from the following files:
src/stats/model/uinteger-16-probe.h
src/stats/model/uinteger-16-probe.cc