ns-3: ns3::ModelTypeidCreator Class Reference
ns3::ModelTypeidCreator Class Reference
Configuration Store/Load
ModelTypeIdCreator class.
#include "model-typeid-creator.h"
Public Member Functions
ModelTypeidCreator ()
void Build (GtkTreeStore *treestore)
This method will iterate on typeIds having default attributes and create a model for them, this model will be used by the view.
Public Member Functions inherited from ns3::AttributeDefaultIterator
virtual ~AttributeDefaultIterator ()=0
void Iterate (void)
This function will go through all the TypeIds and get only the attributes which are explicit values (not vectors or pointer or arrays) and apply StartVisitTypeId and VisitAttribute on the attributes in one TypeId.
Private Member Functions
void Add (ModelTypeid *node)
Adds a treestore iterator to m_treestore model.
virtual void EndVisitTypeId (void)
Remove the last gtk tree iterator.
void Remove (void)
Removes the last GtkTreeIterator from m_iters.
virtual void StartVisitTypeId (std::string name)
Add a node for the new TypeId object.
virtual void VisitAttribute (TypeId tid, std::string name, std::string defaultValue, uint32_t index)
This method will add a ModelTypeid to the GtkTreeIterator.
Private Attributes
std::vector< GtkTreeIter * > m_iters
This contains a vector of iterators used to build the TreeStore.
GtkTreeStore * m_treestore
this is the TreeStore model corresponding to the view
Detailed Description
ModelTypeIdCreator class.
Definition at line 62 of file model-typeid-creator.h.
Constructor & Destructor Documentation
ModelTypeidCreator()
ns3::ModelTypeidCreator::ModelTypeidCreator ()
Definition at line 23 of file model-typeid-creator.cc.
Member Function Documentation
Add()
void ns3::ModelTypeidCreator::Add (ModelTypeid * node) private
Adds a treestore iterator to m_treestore model.
Definition at line 37 of file model-typeid-creator.cc.
References ns3::COL_TYPEID, m_iters, and m_treestore.
Referenced by StartVisitTypeId(), and VisitAttribute().
Build()
void ns3::ModelTypeidCreator::Build (GtkTreeStore * treestore)
This method will iterate on typeIds having default attributes and create a model for them, this model will be used by the view.
Definition at line 28 of file model-typeid-creator.cc.
References ns3::AttributeDefaultIterator::Iterate(), m_iters, m_treestore, and NS_ASSERT.
Referenced by ns3::GtkConfigStore::ConfigureDefaults().
EndVisitTypeId()
void ns3::ModelTypeidCreator::EndVisitTypeId (void) private virtual
Remove the last gtk tree iterator.
Reimplemented from ns3::AttributeDefaultIterator.
Definition at line 77 of file model-typeid-creator.cc.
References Remove().
Remove()
void ns3::ModelTypeidCreator::Remove (void) private
Removes the last GtkTreeIterator from m_iters.
Definition at line 47 of file model-typeid-creator.cc.
References m_iters.
Referenced by EndVisitTypeId(), and VisitAttribute().
StartVisitTypeId()
void ns3::ModelTypeidCreator::StartVisitTypeId (std::string name) private virtual
Add a node for the new TypeId object.
Reimplemented from ns3::AttributeDefaultIterator.
Definition at line 68 of file model-typeid-creator.cc.
References Add(), ns3::TypeId::LookupByName(), ns3::ModelTypeid::NODE_TYPEID, ns3::ModelTypeid::tid, and ns3::ModelTypeid::type.
VisitAttribute()
void ns3::ModelTypeidCreator::VisitAttribute (TypeId tid, std::string name, std::string defaultValue, uint32_t index) private virtual
This method will add a ModelTypeid to the GtkTreeIterator.
Reimplemented from ns3::AttributeDefaultIterator.
Definition at line 55 of file model-typeid-creator.cc.
References Add(), ns3::ModelTypeid::defaultValue, ns3::ModelTypeid::index, ns3::ModelTypeid::name, ns3::ModelTypeid::NODE_ATTRIBUTE, Remove(), ns3::ModelTypeid::tid, and ns3::ModelTypeid::type.
Member Data Documentation
m_iters
std::vector<GtkTreeIter *> ns3::ModelTypeidCreator::m_iters private
This contains a vector of iterators used to build the TreeStore.
Definition at line 95 of file model-typeid-creator.h.
Referenced by Add(), Build(), and Remove().
m_treestore
GtkTreeStore* ns3::ModelTypeidCreator::m_treestore private
this is the TreeStore model corresponding to the view
Definition at line 93 of file model-typeid-creator.h.
Referenced by Add(), and Build().
The documentation for this class was generated from the following files:
src/config-store/model/model-typeid-creator.h
src/config-store/model/model-typeid-creator.cc