ns-3: LrWpanEdTestCase Class Reference
LrWpanEdTestCase Class Reference
LR-WPAN models » LrWpan module tests | Test suites
LrWpan Energy Detection Test.
Public Member Functions
LrWpanEdTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void PlmeEdConfirm (LrWpanPhyEnumeration status, uint8_t level)
Function called when PlmeEdConfirm is hit.
Private Attributes
uint8_t m_level
ED level.
LrWpanPhyEnumeration m_status
PHY status.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
LrWpan Energy Detection Test.
Definition at line 45 of file lr-wpan-ed-test.cc.
Constructor & Destructor Documentation
LrWpanEdTestCase()
LrWpanEdTestCase::LrWpanEdTestCase ()
Definition at line 64 of file lr-wpan-ed-test.cc.
References ns3::IEEE_802_15_4_PHY_UNSPECIFIED, m_level, and m_status.
Member Function Documentation
DoRun()
void LrWpanEdTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 80 of file lr-wpan-ed-test.cc.
References ns3::Node::AddDevice(), ns3::LrWpanNetDevice::AssignStreams(), third::channel, ns3::LrWpanNetDevice::GetMac(), ns3::LrWpanNetDevice::GetPhy(), ns3::IEEE_802_15_4_PHY_SUCCESS, ns3::IEEE_802_15_4_PHY_TX_ON, ns3::IEEE_802_15_4_PHY_UNSPECIFIED, ns3::McpsDataRequestParams::m_dstAddr, ns3::McpsDataRequestParams::m_dstAddrMode, ns3::McpsDataRequestParams::m_dstPanId, m_level, ns3::McpsDataRequestParams::m_msduHandle, ns3::McpsDataRequestParams::m_srcAddrMode, m_status, ns3::McpsDataRequestParams::m_txOptions, ns3::MakeCallback(), NS_TEST_EXPECT_MSG_EQ, PlmeEdConfirm(), ns3::Seconds(), ns3::LrWpanNetDevice::SetAddress(), ns3::LrWpanNetDevice::SetChannel(), ns3::SHORT_ADDR, and ns3::TX_OPTION_NONE.
PlmeEdConfirm()
void LrWpanEdTestCase::PlmeEdConfirm (LrWpanPhyEnumeration status, uint8_t level) private
Function called when PlmeEdConfirm is hit.
Parameters
status The PHY status.
level The ED level.
Definition at line 72 of file lr-wpan-ed-test.cc.
References m_level, m_status, and NS_LOG_UNCOND.
Referenced by DoRun().
Member Data Documentation
m_level
uint8_t LrWpanEdTestCase::m_level private
ED level.
Definition at line 61 of file lr-wpan-ed-test.cc.
Referenced by LrWpanEdTestCase(), DoRun(), and PlmeEdConfirm().
m_status
LrWpanPhyEnumeration LrWpanEdTestCase::m_status private
PHY status.
Definition at line 60 of file lr-wpan-ed-test.cc.
Referenced by LrWpanEdTestCase(), DoRun(), and PlmeEdConfirm().
The documentation for this class was generated from the following file:
src/lr-wpan/test/lr-wpan-ed-test.cc