ns-3: Ipv4DynamicGlobalRoutingTestCase Class Reference
Ipv4DynamicGlobalRoutingTestCase Class Reference
Internet » internet module tests | Test suites
IPv4 Dynamic GlobalRouting test.
Public Member Functions
Ipv4DynamicGlobalRoutingTestCase ()
virtual ~Ipv4DynamicGlobalRoutingTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void HandleRead (Ptr< Socket > socket)
Handle an incoming packet.
void SendData (uint8_t index)
Send some data.
void ShutDownSock (uint8_t index)
Shutdown a socket.
Private Attributes
uint16_t m_count
Number of packets received.
DataRate m_dataRate
Data rate.
std::vector< uint8_t > m_firstInterface
Packets received on the 1st interface at a given time.
uint16_t m_packetSize
Packet size.
std::vector< uint8_t > m_secondInterface
Packets received on the 2nd interface at a given time.
std::vector< std::pair< Ptr< Socket >, bool > > m_sendSocks
Sending sockets.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
IPv4 Dynamic GlobalRouting test.
Definition at line 832 of file ipv4-global-routing-test-suite.cc.
Constructor & Destructor Documentation
Ipv4DynamicGlobalRoutingTestCase()
Ipv4DynamicGlobalRoutingTestCase::Ipv4DynamicGlobalRoutingTestCase ()
Definition at line 867 of file ipv4-global-routing-test-suite.cc.
References m_dataRate, m_firstInterface, m_packetSize, and m_secondInterface.
~Ipv4DynamicGlobalRoutingTestCase()
Ipv4DynamicGlobalRoutingTestCase::~Ipv4DynamicGlobalRoutingTestCase () virtual
Definition at line 876 of file ipv4-global-routing-test-suite.cc.
References m_sendSocks.
Member Function Documentation
DoRun()
void Ipv4DynamicGlobalRoutingTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 963 of file ipv4-global-routing-test-suite.cc.
References ns3::Ipv4AddressHelper::Assign(), ns3::Socket::Bind(), ns3::NodeContainer::Create(), ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::Object::GetObject(), HandleRead(), ns3::SimpleNetDeviceHelper::Install(), ns3::InternetStackHelper::Install(), ns3::Socket::Listen(), m_count, m_firstInterface, m_secondInterface, m_sendSocks, ns3::MakeCallback(), n0n2, n1n2, NS_TEST_ASSERT_MSG_EQ, port, ns3::Seconds(), SendData(), ns3::Ipv4AddressHelper::SetBase(), ns3::Config::SetDefault(), ns3::SimpleNetDeviceHelper::SetNetDevicePointToPointMode(), ns3::Socket::SetRecvCallback(), ns3::Socket::SetRecvPktInfo(), SetUp(), ns3::Socket::ShutdownSend(), and ShutDownSock().
HandleRead()
void Ipv4DynamicGlobalRoutingTestCase::HandleRead (Ptr< Socket > socket) private
Handle an incoming packet.
Parameters
socket The input socket.
Definition at line 892 of file ipv4-global-routing-test-suite.cc.
References ns3::Ipv4PacketInfoTag::GetRecvIf(), ns3::Time::GetSeconds(), ns3::Packet::GetSize(), m_count, m_firstInterface, m_secondInterface, ns3::Now(), ns3::Packet::PeekPacketTag(), and ns3::Socket::RecvFrom().
Referenced by DoRun().
SendData()
void Ipv4DynamicGlobalRoutingTestCase::SendData (uint8_t index) private
Send some data.
Parameters
index Index of the socket to use.
Definition at line 922 of file ipv4-global-routing-test-suite.cc.
References ns3::DataRate::GetBitRate(), m_dataRate, m_packetSize, m_sendSocks, and ns3::MicroSeconds().
Referenced by DoRun().
ShutDownSock()
void Ipv4DynamicGlobalRoutingTestCase::ShutDownSock (uint8_t index) private
Shutdown a socket.
Parameters
index Index of the socket to close.
Definition at line 936 of file ipv4-global-routing-test-suite.cc.
References m_sendSocks.
Referenced by DoRun().
Member Data Documentation
m_count
uint16_t Ipv4DynamicGlobalRoutingTestCase::m_count private
Number of packets received.
Definition at line 858 of file ipv4-global-routing-test-suite.cc.
Referenced by DoRun(), and HandleRead().
m_dataRate
DataRate Ipv4DynamicGlobalRoutingTestCase::m_dataRate private
Data rate.
Definition at line 860 of file ipv4-global-routing-test-suite.cc.
Referenced by Ipv4DynamicGlobalRoutingTestCase(), and SendData().
m_firstInterface
std::vector<uint8_t> Ipv4DynamicGlobalRoutingTestCase::m_firstInterface private
Packets received on the 1st interface at a given time.
Definition at line 862 of file ipv4-global-routing-test-suite.cc.
Referenced by Ipv4DynamicGlobalRoutingTestCase(), DoRun(), and HandleRead().
m_packetSize
uint16_t Ipv4DynamicGlobalRoutingTestCase::m_packetSize private
Packet size.
Definition at line 861 of file ipv4-global-routing-test-suite.cc.
Referenced by Ipv4DynamicGlobalRoutingTestCase(), and SendData().
m_secondInterface
std::vector<uint8_t> Ipv4DynamicGlobalRoutingTestCase::m_secondInterface private
Packets received on the 2nd interface at a given time.
Definition at line 863 of file ipv4-global-routing-test-suite.cc.
Referenced by Ipv4DynamicGlobalRoutingTestCase(), DoRun(), and HandleRead().
m_sendSocks
std::vector<std::pair<Ptr<Socket>, bool> > Ipv4DynamicGlobalRoutingTestCase::m_sendSocks private
Sending sockets.
Definition at line 859 of file ipv4-global-routing-test-suite.cc.
Referenced by ~Ipv4DynamicGlobalRoutingTestCase(), DoRun(), SendData(), and ShutDownSock().
The documentation for this class was generated from the following file:
src/internet/test/ipv4-global-routing-test-suite.cc