ns-3: ns3::SeqTsEchoHeader Class Reference
ns3::SeqTsEchoHeader Class Reference
Applications
Packet header to carry sequence number and two timestamps.
#include "seq-ts-echo-header.h"
Public Member Functions
SeqTsEchoHeader ()
constructor
virtual uint32_t Deserialize (Buffer::Iterator start) override
virtual TypeId GetInstanceTypeId (void) const override
Get the most derived TypeId for this Object.
uint32_t GetSeq (void) const
virtual uint32_t GetSerializedSize (void) const override
Time GetTsEchoReply (void) const
Time GetTsValue (void) const
virtual void Print (std::ostream &os) const override
virtual void Serialize (Buffer::Iterator start) const override
void SetSeq (uint32_t seq)
void SetTsEchoReply (Time ts)
Upon SeqTsEchoHeader reception, the host answers via echoing back the received timestamp.
void SetTsValue (Time ts)
Set the sender's time value.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint32_t m_seq
Sequence number.
Time m_tsEchoReply
Receiver's timestamp.
Time m_tsValue
Sender's timestamp.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Packet header to carry sequence number and two timestamps.
Introspection did not find any typical Config paths.
The header is made of a 32bits sequence number followed by two 64bits time stamps (Transmit and Receive).
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 32 bytes (on a 64-bit architecture).
Definition at line 37 of file seq-ts-echo-header.h.
Constructor & Destructor Documentation
SeqTsEchoHeader()
ns3::SeqTsEchoHeader::SeqTsEchoHeader ()
constructor
Definition at line 34 of file seq-ts-echo-header.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Deserialize()
uint32_t ns3::SeqTsEchoHeader::Deserialize (Buffer::Iterator start) override virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 126 of file seq-ts-echo-header.cc.
References GetSerializedSize(), m_seq, m_tsEchoReply, m_tsValue, NS_LOG_FUNCTION, ns3::Buffer::Iterator::ReadNtohU32(), ns3::Buffer::Iterator::ReadNtohU64(), and visualizer.core::start().
GetInstanceTypeId()
TypeId ns3::SeqTsEchoHeader::GetInstanceTypeId (void) const override virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 96 of file seq-ts-echo-header.cc.
References GetTypeId().
GetSeq()
uint32_t ns3::SeqTsEchoHeader::GetSeq (void) const
Returns
the sequence number
Definition at line 50 of file seq-ts-echo-header.cc.
References m_seq, and NS_LOG_FUNCTION.
GetSerializedSize()
uint32_t ns3::SeqTsEchoHeader::GetSerializedSize (void) const override virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 109 of file seq-ts-echo-header.cc.
References NS_LOG_FUNCTION.
Referenced by Deserialize().
GetTsEchoReply()
Time ns3::SeqTsEchoHeader::GetTsEchoReply (void) const
Returns
A time value echoing the received timestamp
Definition at line 78 of file seq-ts-echo-header.cc.
References m_tsEchoReply, and NS_LOG_FUNCTION.
GetTsValue()
Time ns3::SeqTsEchoHeader::GetTsValue (void) const
Returns
A time value set by the sender
Definition at line 64 of file seq-ts-echo-header.cc.
References m_tsValue, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::SeqTsEchoHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 85 of file seq-ts-echo-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::SeqTsEchoHeader::Print (std::ostream & os) const override virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 102 of file seq-ts-echo-header.cc.
References ns3::Time::As(), m_seq, m_tsEchoReply, m_tsValue, NS_LOG_FUNCTION, and ns3::Time::S.
Serialize()
void ns3::SeqTsEchoHeader::Serialize (Buffer::Iterator start) const override virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 116 of file seq-ts-echo-header.cc.
References ns3::Time::GetTimeStep(), m_seq, m_tsEchoReply, m_tsValue, NS_LOG_FUNCTION, visualizer.core::start(), ns3::Buffer::Iterator::WriteHtonU32(), and ns3::Buffer::Iterator::WriteHtonU64().
SetSeq()
void ns3::SeqTsEchoHeader::SetSeq (uint32_t seq)
Parameters
seq the sequence number
Definition at line 43 of file seq-ts-echo-header.cc.
References m_seq, and NS_LOG_FUNCTION.
SetTsEchoReply()
void ns3::SeqTsEchoHeader::SetTsEchoReply (Time ts)
Upon SeqTsEchoHeader reception, the host answers via echoing back the received timestamp.
Parameters
ts received timestamp. If not called, will contain 0
Definition at line 71 of file seq-ts-echo-header.cc.
References m_tsEchoReply, and NS_LOG_FUNCTION.
SetTsValue()
void ns3::SeqTsEchoHeader::SetTsValue (Time ts)
Set the sender's time value.
Parameters
ts Time value to set
Definition at line 57 of file seq-ts-echo-header.cc.
References m_tsValue, and NS_LOG_FUNCTION.
Member Data Documentation
m_seq
uint32_t ns3::SeqTsEchoHeader::m_seq private
Sequence number.
Definition at line 92 of file seq-ts-echo-header.h.
Referenced by Deserialize(), GetSeq(), Print(), Serialize(), and SetSeq().
m_tsEchoReply
Time ns3::SeqTsEchoHeader::m_tsEchoReply private
Receiver's timestamp.
Definition at line 94 of file seq-ts-echo-header.h.
Referenced by Deserialize(), GetTsEchoReply(), Print(), Serialize(), and SetTsEchoReply().
m_tsValue
Time ns3::SeqTsEchoHeader::m_tsValue private
Sender's timestamp.
Definition at line 93 of file seq-ts-echo-header.h.
Referenced by Deserialize(), GetTsValue(), Print(), Serialize(), and SetTsValue().
The documentation for this class was generated from the following files:
src/applications/model/seq-ts-echo-header.h
src/applications/model/seq-ts-echo-header.cc