ns-3: ns3::dot11s::HwmpProtocolMac Class Reference
ns3::dot11s::HwmpProtocolMac Class Reference
Mesh Device » IEEE 802.11s draft
Interface MAC plugin for HWMP – 802.11s routing protocol.
#include "hwmp-protocol-mac.h"
Classes
struct MyPerr
MyPerr structure.
struct Statistics
Statistics structure.
Public Member Functions
HwmpProtocolMac (uint32_t ifIndex, Ptr< HwmpProtocol > protocol)
Constructor.
~HwmpProtocolMac ()
Public Member Functions inherited from ns3::MeshWifiInterfaceMacPlugin
virtual ~MeshWifiInterfaceMacPlugin ()
This is for subclasses.
Public Member Functions inherited from ns3::SimpleRefCount< MeshWifiInterfaceMacPlugin >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
my PREQ and PREQ timer:
EventId m_preqTimer
std::vector< IePreq > m_myPreq
PERR timer and stored path error
EventId m_perrTimer
PERR.
MyPerr m_myPerr
PERR.
Inherited from MAC plugin
class HwmpProtocol
allow HwmpProtocol class friend access
void SetParent (Ptr< MeshWifiInterfaceMac > parent)
allow HwmpProtocol class friend access
bool Receive (Ptr< Packet > packet, const WifiMacHeader &header)
allow HwmpProtocol class friend access
bool UpdateOutcomingFrame (Ptr< Packet > packet, WifiMacHeader &header, Mac48Address from, Mac48Address to)
allow HwmpProtocol class friend access
void UpdateBeacon (MeshWifiBeacon &beacon) const
Update beacon is empty, because HWMP does not know anything about beacons.
int64_t AssignStreams (int64_t stream)
allow HwmpProtocol class friend access
static WifiActionHeader GetWifiActionHeader ()
Interaction with HWMP:
Ptr< MeshWifiInterfaceMac > m_parent
parent
uint32_t m_ifIndex
IF index.
Ptr< HwmpProtocol > m_protocol
protocol
void SendPreq (IePreq preq)
Send PREQ function.
void SendPreq (std::vector< IePreq > preq)
Send PREQ function.
void SendPrep (IePrep prep, Mac48Address receiver)
Send PREP function.
void ForwardPerr (std::vector< HwmpProtocol::FailedDestination > destinations, std::vector< Mac48Address > receivers)
Forward a path error.
void InitiatePerr (std::vector< HwmpProtocol::FailedDestination > destinations, std::vector< Mac48Address > receivers)
initiate my own path error
void RequestDestination (Mac48Address dest, uint32_t originator_seqno, uint32_t dst_seqno)
Request a destination.
void SendMyPreq ()
Sends one PREQ when PreqMinInterval after last PREQ expires (if any PREQ exists in rhe queue)
void SendMyPerr ()
Send PERR function.
uint32_t GetLinkMetric (Mac48Address peerAddress) const
uint16_t GetChannelId () const
Get the channel ID.
void Report (std::ostream &os) const
Report statistics.
void ResetStats ()
Reset statistics.
Statistics:
Statistics m_stats
statistics
bool ReceiveData (Ptr< Packet > packet, const WifiMacHeader &header)
Receive data frame.
bool ReceiveAction (Ptr< Packet > packet, const WifiMacHeader &header)
Receive action management frame.
Detailed Description
Interface MAC plugin for HWMP – 802.11s routing protocol.
Definition at line 44 of file hwmp-protocol-mac.h.
Constructor & Destructor Documentation
HwmpProtocolMac()
ns3::dot11s::HwmpProtocolMac::HwmpProtocolMac (uint32_t ifIndex, Ptr< HwmpProtocol > protocol)
Constructor.
Parameters
ifIndex interface index
protocol pointer to HWMP protocol instance
Definition at line 40 of file hwmp-protocol-mac.cc.
References NS_LOG_FUNCTION.
~HwmpProtocolMac()
ns3::dot11s::HwmpProtocolMac::~HwmpProtocolMac ()
Definition at line 45 of file hwmp-protocol-mac.cc.
Member Function Documentation
AssignStreams()
int64_t ns3::dot11s::HwmpProtocolMac::AssignStreams (int64_t stream) virtual
allow HwmpProtocol class friend access
Implements ns3::MeshWifiInterfaceMacPlugin.
Definition at line 495 of file hwmp-protocol-mac.cc.
References m_protocol.
ForwardPerr()
void ns3::dot11s::HwmpProtocolMac::ForwardPerr (std::vector< HwmpProtocol::FailedDestination > destinations, std::vector< Mac48Address > receivers) private
Forward a path error.
Parameters
destinations vector of failed destinations
receivers vector of receivers
Definition at line 330 of file hwmp-protocol-mac.cc.
References ns3::Packet::AddHeader(), ns3::WifiInformationElementVector::AddInformationElement(), first::address, ns3::Mac48Address::GetBroadcast(), ns3::Packet::GetSize(), GetWifiActionHeader(), m_parent, m_protocol, m_stats, NS_LOG_FUNCTION, ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetAddr2(), ns3::WifiMacHeader::SetAddr3(), ns3::WifiMacHeader::SetDsNotFrom(), ns3::WifiMacHeader::SetDsNotTo(), ns3::WifiMacHeader::SetType(), ns3::dot11s::HwmpProtocolMac::Statistics::txMgt, ns3::dot11s::HwmpProtocolMac::Statistics::txMgtBytes, ns3::dot11s::HwmpProtocolMac::Statistics::txPerr, and ns3::WIFI_MAC_MGT_ACTION.
Referenced by SendMyPerr().
GetChannelId()
uint16_t ns3::dot11s::HwmpProtocolMac::GetChannelId () const private
Get the channel ID.
Returns
the channel ID
Definition at line 451 of file hwmp-protocol-mac.cc.
References m_parent.
GetLinkMetric()
uint32_t ns3::dot11s::HwmpProtocolMac::GetLinkMetric (Mac48Address peerAddress) const private
Parameters
peerAddress peer address
Returns
metric to HWMP protocol, needed only by metrics to add peer as routing entry
Definition at line 446 of file hwmp-protocol-mac.cc.
References m_parent.
GetWifiActionHeader()
WifiActionHeader ns3::dot11s::HwmpProtocolMac::GetWifiActionHeader () static private
Returns
a path selection action header
Definition at line 217 of file hwmp-protocol-mac.cc.
References ns3::WifiActionHeader::MESH, ns3::WifiActionHeader::ActionValue::meshAction, ns3::WifiActionHeader::PATH_SELECTION, and ns3::WifiActionHeader::SetAction().
Referenced by ForwardPerr(), SendPrep(), and SendPreq().
InitiatePerr()
void ns3::dot11s::HwmpProtocolMac::InitiatePerr (std::vector< HwmpProtocol::FailedDestination > destinations, std::vector< Mac48Address > receivers) private
initiate my own path error
Parameters
destinations vector of failed destinations
receivers vector of receivers
Definition at line 384 of file hwmp-protocol-mac.cc.
References ns3::dot11s::HwmpProtocolMac::MyPerr::destinations, m_myPerr, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::dot11s::HwmpProtocolMac::MyPerr::receivers, and SendMyPerr().
Receive()
bool ns3::dot11s::HwmpProtocolMac::Receive (Ptr< Packet > packet, const WifiMacHeader & header) virtual
allow HwmpProtocol class friend access
Implements ns3::MeshWifiInterfaceMacPlugin.
Definition at line 172 of file hwmp-protocol-mac.cc.
References ns3::WifiMacHeader::IsAction(), ns3::WifiMacHeader::IsData(), NS_LOG_FUNCTION, ReceiveAction(), and ReceiveData().
ReceiveAction()
bool ns3::dot11s::HwmpProtocolMac::ReceiveAction (Ptr< Packet > packet, const WifiMacHeader & header) private
Receive action management frame.
Parameters
packet
header
Returns
true if a packet was received
Definition at line 98 of file hwmp-protocol-mac.cc.
References ns3::WifiInformationElementVector::Begin(), ns3::WifiInformationElementVector::End(), ns3::WifiMacHeader::GetAddr2(), ns3::WifiMacHeader::GetAddr3(), ns3::WifiActionHeader::GetCategory(), ns3::Packet::GetSize(), IE_PERR, IE_PREP, IE_PREQ, IE_RANN, m_ifIndex, m_parent, m_protocol, m_stats, ns3::WifiActionHeader::MESH, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_WARN, ns3::Packet::RemoveHeader(), ns3::dot11s::HwmpProtocolMac::Statistics::rxMgt, ns3::dot11s::HwmpProtocolMac::Statistics::rxMgtBytes, ns3::dot11s::HwmpProtocolMac::Statistics::rxPerr, ns3::dot11s::HwmpProtocolMac::Statistics::rxPrep, and ns3::dot11s::HwmpProtocolMac::Statistics::rxPreq.
Referenced by Receive().
ReceiveData()
bool ns3::dot11s::HwmpProtocolMac::ReceiveData (Ptr< Packet > packet, const WifiMacHeader & header) private
Receive data frame.
Parameters
packet
header
Returns
true if a packet was received
Todo:
address extension
Definition at line 56 of file hwmp-protocol-mac.cc.
References ns3::Packet::AddPacketTag(), ns3::WifiMacHeader::GetAddr3(), ns3::WifiMacHeader::GetAddr4(), ns3::dot11s::MeshHeader::GetAddressExt(), ns3::Mac48Address::GetBroadcast(), ns3::dot11s::MeshHeader::GetMeshSeqno(), ns3::dot11s::MeshHeader::GetMeshTtl(), ns3::Packet::GetSize(), ns3::WifiMacHeader::IsData(), m_protocol, m_stats, NS_ASSERT, NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::Packet::PeekPacketTag(), ns3::Packet::RemoveHeader(), ns3::dot11s::HwmpProtocolMac::Statistics::rxData, ns3::dot11s::HwmpProtocolMac::Statistics::rxDataBytes, ns3::dot11s::HwmpTag::SetSeqno(), and ns3::dot11s::HwmpTag::SetTtl().
Referenced by Receive().
Report()
void ns3::dot11s::HwmpProtocolMac::Report (std::ostream & os) const private
Report statistics.
Parameters
os The output stream on which to report
Definition at line 480 of file hwmp-protocol-mac.cc.
References m_parent, m_stats, and ns3::dot11s::HwmpProtocolMac::Statistics::Print().
RequestDestination()
void ns3::dot11s::HwmpProtocolMac::RequestDestination (Mac48Address dest, uint32_t originator_seqno, uint32_t dst_seqno) private
Request a destination.
If cannot send PREQ immediately, add a destination to existing PREQ generated by me and stored in PREQ queue
Parameters
dest is the destination to be resolved
originator_seqno is a sequence number that shall be preq originator sequenece number
dst_seqno is a sequence number taken from routing table
Definition at line 264 of file hwmp-protocol-mac.cc.
References ns3::dot11s::IePreq::AddDestinationAddressElement(), m_myPreq, m_protocol, NS_ASSERT, NS_LOG_FUNCTION, SendMyPreq(), ns3::dot11s::IePreq::SetHopcount(), ns3::dot11s::IePreq::SetLifetime(), ns3::dot11s::IePreq::SetOriginatorAddress(), ns3::dot11s::IePreq::SetOriginatorSeqNumber(), ns3::dot11s::IePreq::SetPreqID(), and ns3::dot11s::IePreq::SetTTL().
ResetStats()
void ns3::dot11s::HwmpProtocolMac::ResetStats () private
Reset statistics.
Definition at line 488 of file hwmp-protocol-mac.cc.
References m_stats, and NS_LOG_FUNCTION.
SendMyPerr()
void ns3::dot11s::HwmpProtocolMac::SendMyPerr () private
Send PERR function.
Definition at line 433 of file hwmp-protocol-mac.cc.
References ns3::dot11s::HwmpProtocolMac::MyPerr::destinations, ForwardPerr(), ns3::EventId::IsRunning(), m_myPerr, m_perrTimer, m_protocol, NS_LOG_FUNCTION, ns3::dot11s::HwmpProtocolMac::MyPerr::receivers, and ns3::Simulator::Schedule().
Referenced by InitiatePerr().
SendMyPreq()
void ns3::dot11s::HwmpProtocolMac::SendMyPreq () private
Sends one PREQ when PreqMinInterval after last PREQ expires (if any PREQ exists in rhe queue)
Definition at line 288 of file hwmp-protocol-mac.cc.
References ns3::EventId::IsRunning(), m_myPreq, m_preqTimer, m_protocol, NS_ASSERT, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), and SendPreq().
Referenced by RequestDestination().
SendPrep()
void ns3::dot11s::HwmpProtocolMac::SendPrep (IePrep prep, Mac48Address receiver) private
Send PREP function.
Parameters
prep the PREP information element
receiver the MAC address of the receiver
Definition at line 306 of file hwmp-protocol-mac.cc.
References ns3::Packet::AddHeader(), ns3::WifiInformationElementVector::AddInformationElement(), ns3::Packet::GetSize(), GetWifiActionHeader(), m_parent, m_protocol, m_stats, NS_LOG_FUNCTION, ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetAddr2(), ns3::WifiMacHeader::SetAddr3(), ns3::WifiMacHeader::SetDsNotFrom(), ns3::WifiMacHeader::SetDsNotTo(), ns3::WifiMacHeader::SetType(), ns3::dot11s::HwmpProtocolMac::Statistics::txMgt, ns3::dot11s::HwmpProtocolMac::Statistics::txMgtBytes, ns3::dot11s::HwmpProtocolMac::Statistics::txPrep, and ns3::WIFI_MAC_MGT_ACTION.
SendPreq() [1/2]
void ns3::dot11s::HwmpProtocolMac::SendPreq (IePreq preq) private
Send PREQ function.
Parameters
preq the PREQ
Definition at line 226 of file hwmp-protocol-mac.cc.
References NS_LOG_FUNCTION.
Referenced by SendMyPreq().
SendPreq() [2/2]
void ns3::dot11s::HwmpProtocolMac::SendPreq (std::vector< IePreq > preq) private
Send PREQ function.
Parameters
preq vector of PREQ information elements
Definition at line 234 of file hwmp-protocol-mac.cc.
References ns3::Packet::AddHeader(), ns3::WifiInformationElementVector::AddInformationElement(), ns3::Packet::GetSize(), GetWifiActionHeader(), m_ifIndex, m_parent, m_protocol, m_stats, NS_LOG_FUNCTION, ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetAddr2(), ns3::WifiMacHeader::SetAddr3(), ns3::WifiMacHeader::SetDsNotFrom(), ns3::WifiMacHeader::SetDsNotTo(), ns3::WifiMacHeader::SetType(), ns3::dot11s::HwmpProtocolMac::Statistics::txMgt, ns3::dot11s::HwmpProtocolMac::Statistics::txMgtBytes, ns3::dot11s::HwmpProtocolMac::Statistics::txPreq, and ns3::WIFI_MAC_MGT_ACTION.
SetParent()
void ns3::dot11s::HwmpProtocolMac::SetParent (Ptr< MeshWifiInterfaceMac > parent) virtual
allow HwmpProtocol class friend access
Implements ns3::MeshWifiInterfaceMacPlugin.
Definition at line 49 of file hwmp-protocol-mac.cc.
References m_parent, and NS_LOG_FUNCTION.
UpdateBeacon()
void ns3::dot11s::HwmpProtocolMac::UpdateBeacon (MeshWifiBeacon & beacon) const inline virtual
Update beacon is empty, because HWMP does not know anything about beacons.
Implements ns3::MeshWifiInterfaceMacPlugin.
Definition at line 61 of file hwmp-protocol-mac.h.
UpdateOutcomingFrame()
bool ns3::dot11s::HwmpProtocolMac::UpdateOutcomingFrame (Ptr< Packet > packet, WifiMacHeader & header, Mac48Address from, Mac48Address to) virtual
allow HwmpProtocol class friend access
Implements ns3::MeshWifiInterfaceMacPlugin.
Definition at line 192 of file hwmp-protocol-mac.cc.
References ns3::Packet::AddHeader(), ns3::dot11s::HwmpTag::GetAddress(), ns3::dot11s::HwmpTag::GetSeqno(), ns3::Packet::GetSize(), ns3::dot11s::HwmpTag::GetTtl(), ns3::WifiMacHeader::IsData(), m_stats, NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::Packet::RemovePacketTag(), ns3::WifiMacHeader::SetAddr1(), ns3::dot11s::MeshHeader::SetMeshSeqno(), ns3::dot11s::MeshHeader::SetMeshTtl(), ns3::WifiMacHeader::SetQosMeshControlPresent(), ns3::dot11s::HwmpProtocolMac::Statistics::txData, and ns3::dot11s::HwmpProtocolMac::Statistics::txDataBytes.
Friends And Related Function Documentation
HwmpProtocol
friend class HwmpProtocol friend
allow HwmpProtocol class friend access
Definition at line 67 of file hwmp-protocol-mac.h.
Member Data Documentation
m_ifIndex
uint32_t ns3::dot11s::HwmpProtocolMac::m_ifIndex private
IF index.
Definition at line 135 of file hwmp-protocol-mac.h.
Referenced by ReceiveAction(), and SendPreq().
m_myPerr
MyPerr ns3::dot11s::HwmpProtocolMac::m_myPerr private
PERR.
Definition at line 151 of file hwmp-protocol-mac.h.
Referenced by InitiatePerr(), and SendMyPerr().
m_myPreq
std::vector<IePreq> ns3::dot11s::HwmpProtocolMac::m_myPreq private
Definition at line 141 of file hwmp-protocol-mac.h.
Referenced by RequestDestination(), and SendMyPreq().
m_parent
Ptr<MeshWifiInterfaceMac> ns3::dot11s::HwmpProtocolMac::m_parent private
parent
Definition at line 134 of file hwmp-protocol-mac.h.
Referenced by ForwardPerr(), GetChannelId(), GetLinkMetric(), ReceiveAction(), Report(), SendPrep(), SendPreq(), and SetParent().
m_perrTimer
EventId ns3::dot11s::HwmpProtocolMac::m_perrTimer private
PERR.
Definition at line 145 of file hwmp-protocol-mac.h.
Referenced by SendMyPerr().
m_preqTimer
EventId ns3::dot11s::HwmpProtocolMac::m_preqTimer private
Definition at line 140 of file hwmp-protocol-mac.h.
Referenced by SendMyPreq().
m_protocol
Ptr<HwmpProtocol> ns3::dot11s::HwmpProtocolMac::m_protocol private
protocol
Definition at line 136 of file hwmp-protocol-mac.h.
Referenced by AssignStreams(), ForwardPerr(), ReceiveAction(), ReceiveData(), RequestDestination(), SendMyPerr(), SendMyPreq(), SendPrep(), and SendPreq().
m_stats
Statistics ns3::dot11s::HwmpProtocolMac::m_stats private
statistics
Definition at line 178 of file hwmp-protocol-mac.h.
Referenced by ForwardPerr(), ReceiveAction(), ReceiveData(), Report(), ResetStats(), SendPrep(), SendPreq(), and UpdateOutcomingFrame().
The documentation for this class was generated from the following files:
src/mesh/model/dot11s/hwmp-protocol-mac.h
src/mesh/model/dot11s/hwmp-protocol-mac.cc