ns-3: ns3::UanPhyPerUmodem Class Reference
ns3::UanPhyPerUmodem Class Reference
UAN Models
Packet error rate calculation assuming WHOI Micromodem-like PHY (FH-FSK)
#include "uan-phy-gen.h"
Public Member Functions
UanPhyPerUmodem ()
Constructor.
virtual ~UanPhyPerUmodem ()
Destructor.
virtual double CalcPer (Ptr< Packet > pkt, double sinrDb, UanTxMode mode)
Calculate the packet error probability based on SINR at the receiver and a tx mode.
Public Member Functions inherited from ns3::UanPhyPer
virtual void Clear (void)
Clear all pointer references.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::UanPhyPer
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
double NChooseK (uint32_t n, uint32_t k)
Binomial coefficient.
Additional Inherited Members
Protected Member Functions inherited from ns3::UanPhyPer
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Packet error rate calculation assuming WHOI Micromodem-like PHY (FH-FSK)
Calculates PER assuming rate 1/2 convolutional code with constraint length 9 with soft decision viterbi decoding and a CRC capable of correcting 1 bit error.
Config Paths
ns3::UanPhyPerUmodem is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::UanNetDevice/Phy/$ns3::UanPhyGen/PerModel/$ns3::UanPhyPerUmodem"
"/NodeList/[i]/DeviceList/[i]/$ns3::UanNetDevice/Phy/$ns3::UanPhyDual/PerModelPhy1/$ns3::UanPhyPerUmodem"
"/NodeList/[i]/DeviceList/[i]/$ns3::UanNetDevice/Phy/$ns3::UanPhyDual/PerModelPhy2/$ns3::UanPhyPerUmodem"
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 32 bytes (on a 64-bit architecture).
Definition at line 74 of file uan-phy-gen.h.
Constructor & Destructor Documentation
UanPhyPerUmodem()
ns3::UanPhyPerUmodem::UanPhyPerUmodem ()
Constructor.
Definition at line 388 of file uan-phy-gen.cc.
~UanPhyPerUmodem()
ns3::UanPhyPerUmodem::~UanPhyPerUmodem () virtual
Destructor.
Definition at line 392 of file uan-phy-gen.cc.
Member Function Documentation
CalcPer()
double ns3::UanPhyPerUmodem::CalcPer (Ptr< Packet > pkt, double sinrDb, UanTxMode mode) virtual
Calculate the packet error probability based on SINR at the receiver and a tx mode.
This implementation uses calculations for binary FSK modulation coded by a rate 1/2 convolutional code with constraint length = 9 and a viterbi decoder and finally a CRC capable of correcting one bit error. These equations can be found in the book, Digital Communications, by Proakis (any version I think).
Parameters
pkt Packet which is under consideration.
sinrDb SINR at receiver.
mode TX mode used to transmit packet.
Returns
Probability of packet error.
Implements ns3::UanPhyPer.
Definition at line 428 of file uan-phy-gen.cc.
References ns3::UanTxMode::FSK, ns3::UanTxMode::GetConstellationSize(), ns3::UanTxMode::GetModType(), ns3::Packet::GetSize(), NChooseK(), and NS_FATAL_ERROR.
GetTypeId()
TypeId ns3::UanPhyPerUmodem::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 397 of file uan-phy-gen.cc.
References ns3::TypeId::SetParent().
NChooseK()
double ns3::UanPhyPerUmodem::NChooseK (uint32_t n, uint32_t k) private
Binomial coefficient.
Parameters
n Pool size.
k Number of draws.
Returns
Binomial coefficient n choose k.
Definition at line 408 of file uan-phy-gen.cc.
References max, min, and sample-rng-plot::n.
Referenced by CalcPer().
The documentation for this class was generated from the following files:
src/uan/model/uan-phy-gen.h
src/uan/model/uan-phy-gen.cc