ns-3: ns3::dot11s::PeerLinkOpenStart Class Reference
ns3::dot11s::PeerLinkOpenStart Class Reference
Mesh Device » IEEE 802.11s draft
802.11s Peer link open management frame
#include "peer-link-frame.h"
Classes
struct PlinkOpenStartFields
fields:
Public Member Functions
PeerLinkOpenStart ()
virtual uint32_t Deserialize (Buffer::Iterator start)
PlinkOpenStartFields GetFields () const
Get peer link open start fields.
virtual TypeId GetInstanceTypeId () const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize () const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetPlinkOpenStart (PlinkOpenStartFields fields)
Set peer link open start fields.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
PeerLinkOpenStart (const PeerLinkOpenStart &peer)
constructor
PeerLinkOpenStart & operator= (const PeerLinkOpenStart &peer)
assignment operator
Private Attributes
uint16_t m_capability
capability
IeConfiguration m_config
config
IeMeshId m_meshId
mesh ID
SupportedRates m_rates
rates
Friends
bool operator== (const PeerLinkOpenStart &a, const PeerLinkOpenStart &b)
equality operator
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
802.11s Peer link open management frame
Introspection did not find any typical Config paths.
Peer link open start frame includes the following:
Capability
Supported rates
Mesh ID of mesh
Configuration
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 184 bytes (on a 64-bit architecture).
Definition at line 44 of file peer-link-frame.h.
Constructor & Destructor Documentation
PeerLinkOpenStart() [1/2]
ns3::dot11s::PeerLinkOpenStart::PeerLinkOpenStart ()
Definition at line 31 of file peer-link-frame.cc.
PeerLinkOpenStart() [2/2]
ns3::dot11s::PeerLinkOpenStart::PeerLinkOpenStart (const PeerLinkOpenStart & peer) private
constructor
Parameters
peer the peer link open start
Member Function Documentation
Deserialize()
uint32_t ns3::dot11s::PeerLinkOpenStart::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 103 of file peer-link-frame.cc.
References ns3::WifiInformationElement::Deserialize(), ns3::WifiInformationElement::DeserializeIfPresent(), ns3::dot11s::IeConfiguration::DeserializeInformationField(), ns3::dot11s::IeMeshId::DeserializeInformationField(), ns3::dot11s::IeConfiguration::ElementId(), ns3::dot11s::IeMeshId::ElementId(), ns3::SupportedRates::extended, ns3::Buffer::Iterator::GetDistanceFrom(), ns3::dot11s::IeConfiguration::GetInformationFieldSize(), ns3::dot11s::IeMeshId::GetInformationFieldSize(), m_capability, m_config, m_meshId, m_rates, ns3::Buffer::Iterator::Next(), NS_FATAL_ERROR, ns3::Buffer::Iterator::ReadLsbtohU16(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetFields()
PeerLinkOpenStart::PlinkOpenStartFields ns3::dot11s::PeerLinkOpenStart::GetFields () const
Get peer link open start fields.
Returns
PlinkOpenStartFields
Todo:
protocol version:
Definition at line 45 of file peer-link-frame.cc.
References ns3::dot11s::PeerLinkOpenStart::PlinkOpenStartFields::capability, ns3::dot11s::PeerLinkOpenStart::PlinkOpenStartFields::config, m_capability, m_config, m_meshId, m_rates, ns3::dot11s::PeerLinkOpenStart::PlinkOpenStartFields::meshId, and ns3::dot11s::PeerLinkOpenStart::PlinkOpenStartFields::rates.
Referenced by ns3::dot11s::PeerManagementProtocolMac::Receive().
GetInstanceTypeId()
TypeId ns3::dot11s::PeerLinkOpenStart::GetInstanceTypeId () const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 67 of file peer-link-frame.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::dot11s::PeerLinkOpenStart::GetSerializedSize () const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 81 of file peer-link-frame.cc.
References ns3::SupportedRates::extended, ns3::dot11s::IeConfiguration::GetInformationFieldSize(), ns3::dot11s::IeMeshId::GetInformationFieldSize(), ns3::ExtendedSupportedRatesIE::GetSerializedSize(), ns3::WifiInformationElement::GetSerializedSize(), m_config, m_meshId, and m_rates.
GetTypeId()
TypeId ns3::dot11s::PeerLinkOpenStart::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 57 of file peer-link-frame.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
operator=()
PeerLinkOpenStart& ns3::dot11s::PeerLinkOpenStart::operator= (const PeerLinkOpenStart & peer) private
assignment operator
Parameters
peer the peer link open start
Returns
the assigned value
Print()
void ns3::dot11s::PeerLinkOpenStart::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 72 of file peer-link-frame.cc.
References m_capability, m_config, m_meshId, m_rates, ns3::dot11s::IeConfiguration::Print(), and ns3::dot11s::IeMeshId::Print().
Serialize()
void ns3::dot11s::PeerLinkOpenStart::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 92 of file peer-link-frame.cc.
References ns3::SupportedRates::extended, m_capability, m_config, m_meshId, m_rates, ns3::WifiInformationElement::Serialize(), ns3::ExtendedSupportedRatesIE::Serialize(), visualizer.core::start(), and ns3::Buffer::Iterator::WriteHtolsbU16().
SetPlinkOpenStart()
void ns3::dot11s::PeerLinkOpenStart::SetPlinkOpenStart (PeerLinkOpenStart::PlinkOpenStartFields fields)
Set peer link open start fields.
Parameters
fields PlinkOpenStartFields to set
Definition at line 37 of file peer-link-frame.cc.
References ns3::dot11s::PeerLinkOpenStart::PlinkOpenStartFields::capability, ns3::dot11s::PeerLinkOpenStart::PlinkOpenStartFields::config, m_capability, m_config, m_meshId, m_rates, ns3::dot11s::PeerLinkOpenStart::PlinkOpenStartFields::meshId, and ns3::dot11s::PeerLinkOpenStart::PlinkOpenStartFields::rates.
Referenced by PeerLinkFrameStartTest::DoRun(), and ns3::dot11s::PeerManagementProtocolMac::SendPeerLinkManagementFrame().
Friends And Related Function Documentation
operator==
bool operator== (const PeerLinkOpenStart & a, const PeerLinkOpenStart & b) friend
equality operator
Parameters
a lhs
b rhs
Returns
true if equal
Definition at line 130 of file peer-link-frame.cc.
Member Data Documentation
m_capability
uint16_t ns3::dot11s::PeerLinkOpenStart::m_capability private
capability
Definition at line 81 of file peer-link-frame.h.
Referenced by Deserialize(), GetFields(), Print(), Serialize(), and SetPlinkOpenStart().
m_config
IeConfiguration ns3::dot11s::PeerLinkOpenStart::m_config private
config
Definition at line 84 of file peer-link-frame.h.
Referenced by Deserialize(), GetFields(), GetSerializedSize(), Print(), Serialize(), and SetPlinkOpenStart().
m_meshId
IeMeshId ns3::dot11s::PeerLinkOpenStart::m_meshId private
mesh ID
Definition at line 83 of file peer-link-frame.h.
Referenced by Deserialize(), GetFields(), GetSerializedSize(), Print(), Serialize(), and SetPlinkOpenStart().
m_rates
SupportedRates ns3::dot11s::PeerLinkOpenStart::m_rates private
rates
Definition at line 82 of file peer-link-frame.h.
Referenced by Deserialize(), GetFields(), GetSerializedSize(), Print(), Serialize(), and SetPlinkOpenStart().
The documentation for this class was generated from the following files:
src/mesh/model/dot11s/peer-link-frame.h
src/mesh/model/dot11s/peer-link-frame.cc