ns-3: ns3::Ipv6ExtensionHopByHop Class Reference
ns3::Ipv6ExtensionHopByHop Class Reference
Internet » IPv6 classes and sub-modules » IPV6 Header extension system.
IPv6 Extension "Hop By Hop".
#include "ipv6-extension.h"
Public Member Functions
Ipv6ExtensionHopByHop ()
Constructor.
~Ipv6ExtensionHopByHop ()
Destructor.
virtual uint8_t GetExtensionNumber () const
Get the extension number.
virtual uint8_t Process (Ptr< Packet > &packet, uint8_t offset, Ipv6Header const &ipv6Header, Ipv6Address dst, uint8_t *nextHeader, bool &stopProcessing, bool &isDropped, Ipv6L3Protocol::DropReason &dropReason)
Process method Called from Ipv6L3Protocol::Receive.
Public Member Functions inherited from ns3::Ipv6Extension
Ipv6Extension ()
Constructor.
virtual ~Ipv6Extension ()
Destructor.
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Ptr< Node > GetNode () const
Get the node.
virtual uint8_t ProcessOptions (Ptr< Packet > &packet, uint8_t offset, uint8_t length, Ipv6Header const &ipv6Header, Ipv6Address dst, uint8_t *nextHeader, bool &stopProcessing, bool &isDropped, Ipv6L3Protocol::DropReason &dropReason)
Process options Called by implementing classes to process the options.
void SetNode (Ptr< Node > node)
Set the node.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Ipv6Extension
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static const uint8_t EXT_NUMBER = 0
Hop-by-hop extension number.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Ipv6Extension
Ptr< UniformRandomVariable > m_uvar
Provides uniform random variables.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
IPv6 Extension "Hop By Hop".
Introspection did not find any typical Config paths.
No Attributes are defined for this type.
Attributes defined in parent class ns3::Ipv6Extension
ExtensionNumber: The IPv6 extension number.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Flags: read
No TraceSources are defined for this type.
Size of this type is 48 bytes (on a 64-bit architecture).
Definition at line 169 of file ipv6-extension.h.
Constructor & Destructor Documentation
Ipv6ExtensionHopByHop()
ns3::Ipv6ExtensionHopByHop::Ipv6ExtensionHopByHop ()
Constructor.
Definition at line 197 of file ipv6-extension.cc.
~Ipv6ExtensionHopByHop()
ns3::Ipv6ExtensionHopByHop::~Ipv6ExtensionHopByHop ()
Destructor.
Definition at line 201 of file ipv6-extension.cc.
Member Function Documentation
GetExtensionNumber()
uint8_t ns3::Ipv6ExtensionHopByHop::GetExtensionNumber () const virtual
Get the extension number.
Returns
extension number
Implements ns3::Ipv6Extension.
Definition at line 205 of file ipv6-extension.cc.
References EXT_NUMBER.
GetTypeId()
TypeId ns3::Ipv6ExtensionHopByHop::GetTypeId (void) static
Get the type identificator.
Returns
type identificator
Definition at line 187 of file ipv6-extension.cc.
References ns3::TypeId::SetParent().
Process()
uint8_t ns3::Ipv6ExtensionHopByHop::Process (Ptr< Packet > & packet, uint8_t offset, Ipv6Header const & ipv6Header, Ipv6Address dst, uint8_t * nextHeader, bool & stopProcessing, bool & isDropped, Ipv6L3Protocol::DropReason & dropReason) virtual
Process method Called from Ipv6L3Protocol::Receive.
Parameters
packet the packet
offset the offset of the extension to process
ipv6Header the IPv6 header of packet received
dst destination address of the packet received (i.e. us)
nextHeader the next header
stopProcessing true if the packet must not be further processed
isDropped true if the packet must be dropped
dropReason dropping reason
Returns
the size processed
Implements ns3::Ipv6Extension.
Definition at line 210 of file ipv6-extension.cc.
References ns3::Packet::Copy(), ns3::Ipv6ExtensionHeader::GetLength(), ns3::Ipv6ExtensionHeader::GetNextHeader(), ns3::OptionField::GetOptionsOffset(), NS_LOG_FUNCTION, ns3::Ipv6Extension::ProcessOptions(), ns3::Packet::RemoveAtStart(), and ns3::Packet::RemoveHeader().
Member Data Documentation
EXT_NUMBER
const uint8_t ns3::Ipv6ExtensionHopByHop::EXT_NUMBER = 0 static
Hop-by-hop extension number.
Definition at line 175 of file ipv6-extension.h.
Referenced by GetExtensionNumber().
The documentation for this class was generated from the following files:
src/internet/model/ipv6-extension.h
src/internet/model/ipv6-extension.cc