ns-3: ns3::aodv::IdCache Class Reference
ns3::aodv::IdCache Class Reference
AODV Routing
Unique packets identification cache used for simple duplicate detection.
#include "aodv-id-cache.h"
Classes
struct IsExpired
IsExpired structure.
struct UniqueId
Unique packet ID.
Public Member Functions
IdCache (Time lifetime)
constructor
Time GetLifeTime () const
Return lifetime for existing entries in cache.
uint32_t GetSize ()
bool IsDuplicate (Ipv4Address addr, uint32_t id)
Check that entry (addr, id) exists in cache.
void Purge ()
Remove all expired entries.
void SetLifetime (Time lifetime)
Set lifetime for future added entries.
Private Attributes
std::vector< UniqueId > m_idCache
Already seen IDs.
Time m_lifetime
Default lifetime for ID records.
Detailed Description
Unique packets identification cache used for simple duplicate detection.
Definition at line 43 of file aodv-id-cache.h.
Constructor & Destructor Documentation
IdCache()
ns3::aodv::IdCache::IdCache (Time lifetime) inline
constructor
Parameters
lifetime the lifetime for added entries
Definition at line 50 of file aodv-id-cache.h.
Member Function Documentation
GetLifeTime()
Time ns3::aodv::IdCache::GetLifeTime () const inline
Return lifetime for existing entries in cache.
Returns
thhe lifetime
Definition at line 78 of file aodv-id-cache.h.
References m_lifetime.
Referenced by ns3::aodv::IdCacheTest::DoRun(), and ns3::aodv::DuplicatePacketDetection::GetLifetime().
GetSize()
uint32_t ns3::aodv::IdCache::GetSize ()
Returns
number of entries in cache
Definition at line 60 of file aodv-id-cache.cc.
References m_idCache, and Purge().
Referenced by ns3::aodv::IdCacheTest::CheckTimeout1(), ns3::aodv::IdCacheTest::CheckTimeout2(), ns3::aodv::IdCacheTest::CheckTimeout3(), and ns3::aodv::IdCacheTest::DoRun().
IsDuplicate()
bool ns3::aodv::IdCache::IsDuplicate (Ipv4Address addr, uint32_t id)
Check that entry (addr, id) exists in cache.
Add entry, if it doesn't exist.
Parameters
addr the IP address
id the cache entry ID
Returns
true if the pair exists
Definition at line 34 of file aodv-id-cache.cc.
References m_idCache, m_lifetime, ns3::Simulator::Now(), and Purge().
Referenced by ns3::aodv::IdCacheTest::DoRun(), ns3::aodv::DuplicatePacketDetection::IsDuplicate(), ns3::aodv::RoutingProtocol::RecvRequest(), and ns3::aodv::RoutingProtocol::SendRequest().
Purge()
void ns3::aodv::IdCache::Purge ()
Remove all expired entries.
Definition at line 53 of file aodv-id-cache.cc.
References m_idCache.
Referenced by GetSize(), and IsDuplicate().
SetLifetime()
void ns3::aodv::IdCache::SetLifetime (Time lifetime) inline
Set lifetime for future added entries.
Parameters
lifetime the lifetime for entries
Definition at line 70 of file aodv-id-cache.h.
References m_lifetime.
Referenced by ns3::aodv::IdCacheTest::DoRun(), and ns3::aodv::DuplicatePacketDetection::SetLifetime().
Member Data Documentation
m_idCache
std::vector<UniqueId> ns3::aodv::IdCache::m_idCache private
Already seen IDs.
Definition at line 110 of file aodv-id-cache.h.
Referenced by GetSize(), IsDuplicate(), and Purge().
m_lifetime
Time ns3::aodv::IdCache::m_lifetime private
Default lifetime for ID records.
Definition at line 112 of file aodv-id-cache.h.
Referenced by GetLifeTime(), IsDuplicate(), and SetLifetime().
The documentation for this class was generated from the following files:
src/aodv/model/aodv-id-cache.h
src/aodv/model/aodv-id-cache.cc