ns-3: ns3::UanHeaderRcCtsGlobal Class Reference
ns3::UanHeaderRcCtsGlobal Class Reference
UAN Models
Cycle broadcast information.
#include "uan-header-rc.h"
Public Member Functions
UanHeaderRcCtsGlobal ()
Default constructor.
UanHeaderRcCtsGlobal (Time wt, Time ts, uint16_t rate, uint16_t retryRate)
Constructor.
~UanHeaderRcCtsGlobal ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint16_t GetRateNum (void) const
Get the data rate number.
uint16_t GetRetryRate (void) const
Get the retry rate number.
virtual uint32_t GetSerializedSize (void) const
Time GetTxTimeStamp (void) const
Get the CTS transmit timestamp.
Time GetWindowTime (void) const
Get the window time (time duration following blocking time to allow RTS transmissions).
virtual void Print (std::ostream &os) const
void Print (std::ostream &os, Time::Unit unit) const
Specialized Print with Time::Unit declared.
virtual void Serialize (Buffer::Iterator start) const
void SetRateNum (uint16_t rate)
Set the rate number corresponding to data rate of current cycle.
void SetRetryRate (uint16_t rate)
Set the retry rate number for the current cycle.
void SetTxTimeStamp (Time timeStamp)
Set the CTS timestamp.
void SetWindowTime (Time t)
Set the window time (time duration following blocking time to allow RTS transmissions).
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint16_t m_rateNum
Rate number.
uint16_t m_retryRate
Retry rate.
Time m_timeStampTx
Timestamp.
Time m_winTime
Window time.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Cycle broadcast information.
Introspection did not find any typical Config paths.
This includes the rate number, retry rate and window time.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 32 bytes (on a 64-bit architecture).
Definition at line 238 of file uan-header-rc.h.
Constructor & Destructor Documentation
UanHeaderRcCtsGlobal() [1/2]
ns3::UanHeaderRcCtsGlobal::UanHeaderRcCtsGlobal ()
Default constructor.
Definition at line 278 of file uan-header-rc.cc.
UanHeaderRcCtsGlobal() [2/2]
ns3::UanHeaderRcCtsGlobal::UanHeaderRcCtsGlobal (Time wt, Time ts, uint16_t rate, uint16_t retryRate)
Constructor.
Parameters
wt Window time.
ts Timestamp.
rate Rate number.
retryRate Retry rate value.
Definition at line 286 of file uan-header-rc.cc.
~UanHeaderRcCtsGlobal()
ns3::UanHeaderRcCtsGlobal::~UanHeaderRcCtsGlobal ()
Destructor.
Definition at line 296 of file uan-header-rc.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::UanHeaderRcCtsGlobal::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 377 of file uan-header-rc.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_rateNum, m_retryRate, m_timeStampTx, m_winTime, ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU32(), ns3::Seconds(), and visualizer.core::start().
GetInstanceTypeId()
TypeId ns3::UanHeaderRcCtsGlobal::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 401 of file uan-header-rc.cc.
References GetTypeId().
GetRateNum()
uint16_t ns3::UanHeaderRcCtsGlobal::GetRateNum (void) const
Get the data rate number.
Returns
The rate number.
Definition at line 357 of file uan-header-rc.cc.
References m_rateNum.
Referenced by ns3::UanMacRc::ReceiveOkFromPhy().
GetRetryRate()
uint16_t ns3::UanHeaderRcCtsGlobal::GetRetryRate (void) const
Get the retry rate number.
Returns
The retry rate number.
Definition at line 351 of file uan-header-rc.cc.
References m_retryRate.
Referenced by ns3::UanMacRc::ReceiveOkFromPhy().
GetSerializedSize()
uint32_t ns3::UanHeaderRcCtsGlobal::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 362 of file uan-header-rc.cc.
Referenced by ns3::UanMacRc::UanMacRc(), and ns3::UanMacRcGw::UanMacRcGw().
GetTxTimeStamp()
Time ns3::UanHeaderRcCtsGlobal::GetTxTimeStamp (void) const
Get the CTS transmit timestamp.
Returns
The timestamp.
Definition at line 345 of file uan-header-rc.cc.
References m_timeStampTx.
Referenced by ns3::UanMacRc::ScheduleData().
GetTypeId()
TypeId ns3::UanHeaderRcCtsGlobal::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 302 of file uan-header-rc.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
GetWindowTime()
Time ns3::UanHeaderRcCtsGlobal::GetWindowTime (void) const
Get the window time (time duration following blocking time to allow RTS transmissions).
Returns
The window time.
Definition at line 339 of file uan-header-rc.cc.
References m_winTime.
Referenced by ns3::UanMacRc::ReceiveOkFromPhy().
Print() [1/2]
void ns3::UanHeaderRcCtsGlobal::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 395 of file uan-header-rc.cc.
References Print(), and ns3::Time::S.
Print() [2/2]
void ns3::UanHeaderRcCtsGlobal::Print (std::ostream & os, Time::Unit unit) const
Specialized Print with Time::Unit declared.
Parameters
os ostream.
unit Time unit.
Definition at line 389 of file uan-header-rc.cc.
References ns3::Time::As(), m_rateNum, m_retryRate, m_timeStampTx, m_winTime, and ns3::Time::S.
Referenced by Print().
Serialize()
void ns3::UanHeaderRcCtsGlobal::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 368 of file uan-header-rc.cc.
References ns3::Time::GetMilliSeconds(), m_rateNum, m_retryRate, m_timeStampTx, m_winTime, ns3::Time::MS, ns3::Time::RoundTo(), and visualizer.core::start().
SetRateNum()
void ns3::UanHeaderRcCtsGlobal::SetRateNum (uint16_t rate)
Set the rate number corresponding to data rate of current cycle.
Parameters
rate The rate number.
Definition at line 315 of file uan-header-rc.cc.
References m_rateNum.
Referenced by ns3::UanMacRcGw::StartCycle().
SetRetryRate()
void ns3::UanHeaderRcCtsGlobal::SetRetryRate (uint16_t rate)
Set the retry rate number for the current cycle.
Parameters
rate The retry rate number
Definition at line 321 of file uan-header-rc.cc.
References m_retryRate.
Referenced by ns3::UanMacRcGw::StartCycle().
SetTxTimeStamp()
void ns3::UanHeaderRcCtsGlobal::SetTxTimeStamp (Time timeStamp)
Set the CTS timestamp.
Parameters
timeStamp The time of CTS transmission.
Definition at line 333 of file uan-header-rc.cc.
References m_timeStampTx.
Referenced by ns3::UanMacRcGw::StartCycle().
SetWindowTime()
void ns3::UanHeaderRcCtsGlobal::SetWindowTime (Time t)
Set the window time (time duration following blocking time to allow RTS transmissions).
Parameters
t The window time.
Definition at line 327 of file uan-header-rc.cc.
References m_winTime.
Referenced by ns3::UanMacRcGw::StartCycle().
Member Data Documentation
m_rateNum
uint16_t ns3::UanHeaderRcCtsGlobal::m_rateNum private
Rate number.
Definition at line 330 of file uan-header-rc.h.
Referenced by Deserialize(), GetRateNum(), Print(), Serialize(), and SetRateNum().
m_retryRate
uint16_t ns3::UanHeaderRcCtsGlobal::m_retryRate private
Retry rate.
Definition at line 329 of file uan-header-rc.h.
Referenced by Deserialize(), GetRetryRate(), Print(), Serialize(), and SetRetryRate().
m_timeStampTx
Time ns3::UanHeaderRcCtsGlobal::m_timeStampTx private
Timestamp.
Definition at line 327 of file uan-header-rc.h.
Referenced by Deserialize(), GetTxTimeStamp(), Print(), Serialize(), and SetTxTimeStamp().
m_winTime
Time ns3::UanHeaderRcCtsGlobal::m_winTime private
Window time.
Definition at line 328 of file uan-header-rc.h.
Referenced by Deserialize(), GetWindowTime(), Print(), Serialize(), and SetWindowTime().
The documentation for this class was generated from the following files:
src/uan/model/uan-header-rc.h
src/uan/model/uan-header-rc.cc