ns-3: ns3::LrWpanCsmaCa Class Reference
ns3::LrWpanCsmaCa Class Reference
LR-WPAN models
This class is a helper for the LrWpanMac to manage the Csma/CA state machine according to IEEE 802.15.4-2006, section 7.5.1.4.
#include "lr-wpan-csmaca.h"
Public Member Functions
LrWpanCsmaCa (void)
Default constructor.
virtual ~LrWpanCsmaCa (void)
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
void Cancel (void)
Cancel CSMA-CA algorithm.
void CanProceed (void)
In the slotted CSMA-CA, after random backoff, determine if the remaining CSMA-CA operation can proceed, i.e.
void DeferCsmaTimeout (void)
The CSMA algorithm call this function at the end of the CAP to return the MAC state back to to IDLE after a transmission was deferred due to the lack of time in the CAP.
bool GetBatteryLifeExtension (void)
Get the value of the Battery Life Extension.
Ptr< LrWpanMac > GetMac (void) const
Get the MAC to which this CSMA/CA implementation is attached to.
uint8_t GetMacMaxBE (void) const
Get the maximum backoff exponent value.
uint8_t GetMacMaxCSMABackoffs (void) const
Get the maximum number of backoffs.
uint8_t GetMacMinBE (void) const
Get the minimum backoff exponent value.
uint8_t GetNB (void)
Get the number of CSMA retries.
Time GetTimeToNextSlot (void) const
Locates the time to the next backoff period boundary in the SUPERFRAME and returns the amount of time left to this moment.
uint64_t GetUnitBackoffPeriod (void) const
Get the number of symbols forming the basic time period used by the CSMA-CA algorithm.
bool IsSlottedCsmaCa (void) const
Check if the slotted CSMA/CA version is being used.
bool IsUnSlottedCsmaCa (void) const
Check if the unslotted CSMA/CA version is being used.
void PlmeCcaConfirm (LrWpanPhyEnumeration status)
IEEE 802.15.4-2006 section 6.2.2.2 PLME-CCA.confirm status.
void RandomBackoffDelay (void)
In step 2 of the CSMA-CA, perform a random backoff in the range of 0 to 2^BE -1.
void RequestCCA (void)
Request the Phy to perform CCA (Step 3)
void SetBatteryLifeExtension (bool batteryLifeExtension)
Set the value of the Battery Life Extension.
void SetLrWpanMacStateCallback (LrWpanMacStateCallback macState)
Set the callback function to the MAC.
void SetLrWpanMacTransCostCallback (LrWpanMacTransCostCallback trans)
Set the callback function to report a transaction cost in slotted CSMA-CA.
void SetMac (Ptr< LrWpanMac > mac)
Set the MAC to which this CSMA/CA implementation is attached to.
void SetMacMaxBE (uint8_t macMaxBE)
Set the maximum backoff exponent value.
void SetMacMaxCSMABackoffs (uint8_t macMaxCSMABackoffs)
Set the maximum number of backoffs.
void SetMacMinBE (uint8_t macMinBE)
Set the minimum backoff exponent value.
void SetSlottedCsmaCa (void)
Configure for the use of the slotted CSMA/CA version.
void SetUnitBackoffPeriod (uint64_t unitBackoffPeriod)
Set the number of symbols forming the basic time period used by the CSMA-CA algorithm.
void SetUnSlottedCsmaCa (void)
Configure for the use of the unslotted CSMA/CA version.
void Start (void)
Start CSMA-CA algorithm (step 1), initialize NB, BE for both slotted and unslotted CSMA-CA.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
LrWpanCsmaCa (LrWpanCsmaCa const &)
Copy constructor - defined and not implemented.
virtual void DoDispose (void)
Destructor implementation.
Time GetTimeLeftInCap ()
Get the time left in the CAP portion of the Outgoing or Incoming superframe.
LrWpanCsmaCa & operator= (LrWpanCsmaCa const &)
Copy constructor - defined and not implemented.
Private Attributes
uint64_t m_aUnitBackoffPeriod
Number of symbols per CSMA/CA time unit, default 20 symbols.
uint8_t m_BE
Backoff exponent.
EventId m_canProceedEvent
Scheduler event for checking if we can complete the transmission before the end of the CAP.
bool m_ccaRequestRunning
Flag indicating that the PHY is currently running a CCA.
bool m_coorDest
Indicates whether the CSMA procedure is targeted for a message to be sent to the coordinator.
uint8_t m_CW
Contention window length (used in slotted ver only).
EventId m_endCapEvent
Scheduler event for the end of the current CAP.
bool m_isSlotted
Beacon-enabled slotted or nonbeacon-enabled unslotted CSMA-CA.
LrWpanMacStateCallback m_lrWpanMacStateCallback
The callback to inform the configured MAC of the CSMA/CA result.
LrWpanMacTransCostCallback m_lrWpanMacTransCostCallback
The callback to inform the cost of a transaction in slotted CSMA-CA.
Ptr< LrWpanMac > m_mac
The MAC instance for which this CSMA/CA implemenation is configured.
bool m_macBattLifeExt
Battery Life Extension.
uint8_t m_macMaxBE
Maximum backoff exponent.
uint8_t m_macMaxCSMABackoffs
Maximum number of backoffs.
uint8_t m_macMinBE
Minimum backoff exponent.
uint8_t m_NB
Number of backoffs for the current transmission.
Ptr< UniformRandomVariable > m_random
Uniform random variable stream.
EventId m_randomBackoffEvent
Scheduler event for the start of the next random backoff/slot.
uint64_t m_randomBackoffPeriodsLeft
Count the number of remaining random backoff periods left to delay.
EventId m_requestCcaEvent
Scheduler event when to start the CCA after a random backoff.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class is a helper for the LrWpanMac to manage the Csma/CA state machine according to IEEE 802.15.4-2006, section 7.5.1.4.
Introspection did not find any typical Config paths.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 200 bytes (on a 64-bit architecture).
Definition at line 56 of file lr-wpan-csmaca.h.
Constructor & Destructor Documentation
LrWpanCsmaCa() [1/2]
ns3::LrWpanCsmaCa::LrWpanCsmaCa (void)
Default constructor.
Definition at line 51 of file lr-wpan-csmaca.cc.
References m_aUnitBackoffPeriod, m_BE, m_ccaRequestRunning, m_coorDest, m_CW, m_isSlotted, m_macBattLifeExt, m_macMaxBE, m_macMaxCSMABackoffs, m_macMinBE, m_NB, m_random, and m_randomBackoffPeriodsLeft.
~LrWpanCsmaCa()
ns3::LrWpanCsmaCa::~LrWpanCsmaCa (void) virtual
Definition at line 70 of file lr-wpan-csmaca.cc.
References m_mac.
LrWpanCsmaCa() [2/2]
ns3::LrWpanCsmaCa::LrWpanCsmaCa (LrWpanCsmaCa const &) private
Copy constructor - defined and not implemented.
Member Function Documentation
AssignStreams()
int64_t ns3::LrWpanCsmaCa::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 572 of file lr-wpan-csmaca.cc.
References m_random, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
Cancel()
void ns3::LrWpanCsmaCa::Cancel (void)
Cancel CSMA-CA algorithm.
Definition at line 284 of file lr-wpan-csmaca.cc.
References ns3::EventId::Cancel(), m_canProceedEvent, m_randomBackoffEvent, and m_requestCcaEvent.
Referenced by DoDispose().
CanProceed()
void ns3::LrWpanCsmaCa::CanProceed (void)
In the slotted CSMA-CA, after random backoff, determine if the remaining CSMA-CA operation can proceed, i.e.
can the entire transactions can be transmitted before the end of the CAP. This step is performed between step 2 and 3. This step is NOT performed for the unslotted CSMA-CA. If it can proceed function RequestCCA() is called.
Definition at line 389 of file lr-wpan-csmaca.cc.
References ns3::Time::As(), DeferCsmaTimeout(), ns3::Time::GetSeconds(), GetTimeLeftInCap(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_CW, m_endCapEvent, m_lrWpanMacTransCostCallback, m_mac, m_randomBackoffPeriodsLeft, m_requestCcaEvent, NS_LOG_DEBUG, NS_LOG_FUNCTION, RequestCCA(), ns3::Time::S, ns3::Simulator::Schedule(), ns3::Simulator::ScheduleNow(), and ns3::Seconds().
Referenced by RandomBackoffDelay().
DeferCsmaTimeout()
void ns3::LrWpanCsmaCa::DeferCsmaTimeout (void)
The CSMA algorithm call this function at the end of the CAP to return the MAC state back to to IDLE after a transmission was deferred due to the lack of time in the CAP.
Definition at line 473 of file lr-wpan-csmaca.cc.
References m_lrWpanMacStateCallback, ns3::MAC_CSMA_DEFERRED, and NS_LOG_FUNCTION.
Referenced by CanProceed(), and RandomBackoffDelay().
DoDispose()
void ns3::LrWpanCsmaCa::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 76 of file lr-wpan-csmaca.cc.
References Cancel(), m_lrWpanMacStateCallback, m_lrWpanMacTransCostCallback, and m_mac.
GetBatteryLifeExtension()
bool ns3::LrWpanCsmaCa::GetBatteryLifeExtension (void)
Get the value of the Battery Life Extension.
Returns
true or false to Battery Life Extension support
Definition at line 586 of file lr-wpan-csmaca.cc.
References m_macBattLifeExt.
GetMac()
Ptr< LrWpanMac > ns3::LrWpanCsmaCa::GetMac (void) const
Get the MAC to which this CSMA/CA implementation is attached to.
Returns
the used MAC
Definition at line 92 of file lr-wpan-csmaca.cc.
References m_mac.
GetMacMaxBE()
uint8_t ns3::LrWpanCsmaCa::GetMacMaxBE (void) const
Get the maximum backoff exponent value.
See IEEE 802.15.4-2006, section 7.4.2, Table 86.
Returns
the maximum backoff exponent value
Definition at line 147 of file lr-wpan-csmaca.cc.
References m_macMaxBE, and NS_LOG_FUNCTION.
GetMacMaxCSMABackoffs()
uint8_t ns3::LrWpanCsmaCa::GetMacMaxCSMABackoffs (void) const
Get the maximum number of backoffs.
See IEEE 802.15.4-2006, section 7.4.2, Table 86.
Returns
the maximum number of backoffs
Definition at line 161 of file lr-wpan-csmaca.cc.
References m_macMaxCSMABackoffs, and NS_LOG_FUNCTION.
GetMacMinBE()
uint8_t ns3::LrWpanCsmaCa::GetMacMinBE (void) const
Get the minimum backoff exponent value.
See IEEE 802.15.4-2006, section 7.4.2, Table 86.
Returns
the minimum backoff exponent value
Definition at line 133 of file lr-wpan-csmaca.cc.
References m_macMinBE, and NS_LOG_FUNCTION.
GetNB()
uint8_t ns3::LrWpanCsmaCa::GetNB (void)
Get the number of CSMA retries.
Returns
the number of CSMA retries
Definition at line 580 of file lr-wpan-csmaca.cc.
References m_NB.
GetTimeLeftInCap()
Time ns3::LrWpanCsmaCa::GetTimeLeftInCap () private
Get the time left in the CAP portion of the Outgoing or Incoming superframe.
Returns
the time left in the CAP
Definition at line 354 of file lr-wpan-csmaca.cc.
References m_coorDest, m_mac, ns3::Simulator::Now(), and ns3::Seconds().
Referenced by CanProceed(), and RandomBackoffDelay().
GetTimeToNextSlot()
Time ns3::LrWpanCsmaCa::GetTimeToNextSlot (void) const
Locates the time to the next backoff period boundary in the SUPERFRAME and returns the amount of time left to this moment.
Returns
time offset to the next slot
Definition at line 183 of file lr-wpan-csmaca.cc.
References ns3::Time::As(), ns3::Time::GetSeconds(), m_aUnitBackoffPeriod, m_coorDest, m_mac, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_UNUSED, ns3::Time::S, and ns3::Seconds().
Referenced by Start().
GetTypeId()
TypeId ns3::LrWpanCsmaCa::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 41 of file lr-wpan-csmaca.cc.
References ns3::TypeId::SetParent().
GetUnitBackoffPeriod()
uint64_t ns3::LrWpanCsmaCa::GetUnitBackoffPeriod (void) const
Get the number of symbols forming the basic time period used by the CSMA-CA algorithm.
See IEEE 802.15.4-2006, section 7.4.1, Table 85.
Returns
the period length in symbols
Definition at line 175 of file lr-wpan-csmaca.cc.
References m_aUnitBackoffPeriod, and NS_LOG_FUNCTION.
Referenced by RandomBackoffDelay().
IsSlottedCsmaCa()
bool ns3::LrWpanCsmaCa::IsSlottedCsmaCa (void) const
Check if the slotted CSMA/CA version is being used.
Returns
true, if slotted CSMA/CA is used, false otherwise.
Definition at line 112 of file lr-wpan-csmaca.cc.
References m_isSlotted, and NS_LOG_FUNCTION.
Referenced by PlmeCcaConfirm(), and Start().
IsUnSlottedCsmaCa()
bool ns3::LrWpanCsmaCa::IsUnSlottedCsmaCa (void) const
Check if the unslotted CSMA/CA version is being used.
Returns
true, if unslotted CSMA/CA is used, false otherwise.
Definition at line 119 of file lr-wpan-csmaca.cc.
References m_isSlotted, and NS_LOG_FUNCTION.
Referenced by RandomBackoffDelay().
operator=()
LrWpanCsmaCa& ns3::LrWpanCsmaCa::operator= (LrWpanCsmaCa const &) private
Copy constructor - defined and not implemented.
Returns
PlmeCcaConfirm()
void ns3::LrWpanCsmaCa::PlmeCcaConfirm (LrWpanPhyEnumeration status)
IEEE 802.15.4-2006 section 6.2.2.2 PLME-CCA.confirm status.
Parameters
status TRX_OFF, BUSY or IDLE
When Phy has completed CCA, it calls back here which in turn execute the final steps of the CSMA-CA algorithm. It checks to see if the Channel is idle, if so check the Contention window before permitting transmission (step 5). If channel is busy, either backoff and perform CCA again or treat as channel access failure (step 4).
Definition at line 480 of file lr-wpan-csmaca.cc.
References ns3::CHANNEL_ACCESS_FAILURE, ns3::CHANNEL_IDLE, ns3::IEEE_802_15_4_PHY_IDLE, ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), IsSlottedCsmaCa(), m_BE, m_ccaRequestRunning, m_CW, m_lrWpanMacStateCallback, m_macMaxBE, m_macMaxCSMABackoffs, m_NB, m_randomBackoffEvent, m_requestCcaEvent, min, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, RandomBackoffDelay(), RequestCCA(), and ns3::Simulator::ScheduleNow().
Referenced by ns3::LrWpanNetDevice::CompleteConfig().
RandomBackoffDelay()
void ns3::LrWpanCsmaCa::RandomBackoffDelay (void)
In step 2 of the CSMA-CA, perform a random backoff in the range of 0 to 2^BE -1.
Definition at line 294 of file lr-wpan-csmaca.cc.
References ns3::Time::As(), CanProceed(), DeferCsmaTimeout(), ns3::Time::GetSeconds(), GetTimeLeftInCap(), GetUnitBackoffPeriod(), ns3::UniformRandomVariable::GetValue(), IsUnSlottedCsmaCa(), m_aUnitBackoffPeriod, m_BE, m_canProceedEvent, m_endCapEvent, m_mac, m_random, m_randomBackoffPeriodsLeft, m_requestCcaEvent, NS_LOG_DEBUG, NS_LOG_FUNCTION, RequestCCA(), ns3::Time::S, ns3::Simulator::Schedule(), and ns3::Seconds().
Referenced by PlmeCcaConfirm(), and Start().
RequestCCA()
void ns3::LrWpanCsmaCa::RequestCCA (void)
Request the Phy to perform CCA (Step 3)
Definition at line 465 of file lr-wpan-csmaca.cc.
References m_ccaRequestRunning, m_mac, and NS_LOG_FUNCTION.
Referenced by CanProceed(), PlmeCcaConfirm(), and RandomBackoffDelay().
SetBatteryLifeExtension()
void ns3::LrWpanCsmaCa::SetBatteryLifeExtension (bool batteryLifeExtension)
Set the value of the Battery Life Extension.
Parameters
batteryLifeExtension the Battery Life Extension value active or inactive
Definition at line 565 of file lr-wpan-csmaca.cc.
References m_macBattLifeExt.
SetLrWpanMacStateCallback()
void ns3::LrWpanCsmaCa::SetLrWpanMacStateCallback (LrWpanMacStateCallback macState)
Set the callback function to the MAC.
Used at the end of a Channel Assessment, as part of the interconnections between the CSMA-CA and the MAC. The callback lets MAC know a channel is either idle or busy.
Parameters
macState the mac state callback
Definition at line 558 of file lr-wpan-csmaca.cc.
References m_lrWpanMacStateCallback, and NS_LOG_FUNCTION.
SetLrWpanMacTransCostCallback()
void ns3::LrWpanCsmaCa::SetLrWpanMacTransCostCallback (LrWpanMacTransCostCallback trans)
Set the callback function to report a transaction cost in slotted CSMA-CA.
The callback is triggered in CanProceed() after calculating the transaction cost (2 CCA checks,transmission cost, turnAroundTime, ifs) in the boundary of an Active Period.
Parameters
trans the transaction cost callback
Definition at line 550 of file lr-wpan-csmaca.cc.
References m_lrWpanMacTransCostCallback, and NS_LOG_FUNCTION.
SetMac()
void ns3::LrWpanCsmaCa::SetMac (Ptr< LrWpanMac > mac)
Set the MAC to which this CSMA/CA implementation is attached to.
Parameters
mac the used MAC
Definition at line 86 of file lr-wpan-csmaca.cc.
References m_mac, and third::mac.
SetMacMaxBE()
void ns3::LrWpanCsmaCa::SetMacMaxBE (uint8_t macMaxBE)
Set the maximum backoff exponent value.
See IEEE 802.15.4-2006, section 7.4.2, Table 86.
Parameters
macMaxBE the maximum backoff exponent value
Definition at line 140 of file lr-wpan-csmaca.cc.
References m_macMinBE, and NS_LOG_FUNCTION.
SetMacMaxCSMABackoffs()
void ns3::LrWpanCsmaCa::SetMacMaxCSMABackoffs (uint8_t macMaxCSMABackoffs)
Set the maximum number of backoffs.
See IEEE 802.15.4-2006, section 7.4.2, Table 86.
Parameters
macMaxCSMABackoffs the maximum number of backoffs
Definition at line 154 of file lr-wpan-csmaca.cc.
References m_macMaxCSMABackoffs, and NS_LOG_FUNCTION.
SetMacMinBE()
void ns3::LrWpanCsmaCa::SetMacMinBE (uint8_t macMinBE)
Set the minimum backoff exponent value.
See IEEE 802.15.4-2006, section 7.4.2, Table 86.
Parameters
macMinBE the minimum backoff exponent value
Definition at line 126 of file lr-wpan-csmaca.cc.
References m_macMinBE, and NS_LOG_FUNCTION.
SetSlottedCsmaCa()
void ns3::LrWpanCsmaCa::SetSlottedCsmaCa (void)
Configure for the use of the slotted CSMA/CA version.
Definition at line 98 of file lr-wpan-csmaca.cc.
References m_isSlotted, and NS_LOG_FUNCTION.
SetUnitBackoffPeriod()
void ns3::LrWpanCsmaCa::SetUnitBackoffPeriod (uint64_t unitBackoffPeriod)
Set the number of symbols forming the basic time period used by the CSMA-CA algorithm.
See IEEE 802.15.4-2006, section 7.4.1, Table 85.
Parameters
unitBackoffPeriod the period length in symbols
Definition at line 168 of file lr-wpan-csmaca.cc.
References m_aUnitBackoffPeriod, and NS_LOG_FUNCTION.
SetUnSlottedCsmaCa()
void ns3::LrWpanCsmaCa::SetUnSlottedCsmaCa (void)
Configure for the use of the unslotted CSMA/CA version.
Definition at line 105 of file lr-wpan-csmaca.cc.
References m_isSlotted, and NS_LOG_FUNCTION.
Start()
void ns3::LrWpanCsmaCa::Start (void)
Start CSMA-CA algorithm (step 1), initialize NB, BE for both slotted and unslotted CSMA-CA.
For slotted CSMA-CA initializes CW and starts the backoff slot count.
Definition at line 243 of file lr-wpan-csmaca.cc.
References GetTimeToNextSlot(), IsSlottedCsmaCa(), m_BE, m_coorDest, m_CW, m_mac, m_macBattLifeExt, m_macMinBE, m_NB, m_randomBackoffEvent, min, NS_LOG_FUNCTION, RandomBackoffDelay(), ns3::Simulator::Schedule(), and ns3::Simulator::ScheduleNow().
Member Data Documentation
m_aUnitBackoffPeriod
uint64_t ns3::LrWpanCsmaCa::m_aUnitBackoffPeriod private
Number of symbols per CSMA/CA time unit, default 20 symbols.
Definition at line 320 of file lr-wpan-csmaca.h.
Referenced by LrWpanCsmaCa(), GetTimeToNextSlot(), GetUnitBackoffPeriod(), RandomBackoffDelay(), and SetUnitBackoffPeriod().
m_BE
uint8_t ns3::LrWpanCsmaCa::m_BE private
Backoff exponent.
Definition at line 300 of file lr-wpan-csmaca.h.
Referenced by LrWpanCsmaCa(), PlmeCcaConfirm(), RandomBackoffDelay(), and Start().
m_canProceedEvent
EventId ns3::LrWpanCsmaCa::m_canProceedEvent private
Scheduler event for checking if we can complete the transmission before the end of the CAP.
Definition at line 345 of file lr-wpan-csmaca.h.
Referenced by Cancel(), and RandomBackoffDelay().
m_ccaRequestRunning
bool ns3::LrWpanCsmaCa::m_ccaRequestRunning private
Flag indicating that the PHY is currently running a CCA.
Used to prevent reporting the channel status to the MAC while canceling the CSMA algorithm.
Definition at line 350 of file lr-wpan-csmaca.h.
Referenced by LrWpanCsmaCa(), PlmeCcaConfirm(), and RequestCCA().
m_coorDest
bool ns3::LrWpanCsmaCa::m_coorDest private
Indicates whether the CSMA procedure is targeted for a message to be sent to the coordinator.
Used to run slotted CSMA/CA on the incoming or outgoing superframe according to the target.
Definition at line 356 of file lr-wpan-csmaca.h.
Referenced by LrWpanCsmaCa(), GetTimeLeftInCap(), GetTimeToNextSlot(), and Start().
m_CW
uint8_t ns3::LrWpanCsmaCa::m_CW private
Contention window length (used in slotted ver only).
Definition at line 296 of file lr-wpan-csmaca.h.
Referenced by LrWpanCsmaCa(), CanProceed(), PlmeCcaConfirm(), and Start().
m_endCapEvent
EventId ns3::LrWpanCsmaCa::m_endCapEvent private
Scheduler event for the end of the current CAP.
Definition at line 336 of file lr-wpan-csmaca.h.
Referenced by CanProceed(), and RandomBackoffDelay().
m_isSlotted
bool ns3::LrWpanCsmaCa::m_isSlotted private
Beacon-enabled slotted or nonbeacon-enabled unslotted CSMA-CA.
Definition at line 284 of file lr-wpan-csmaca.h.
Referenced by LrWpanCsmaCa(), IsSlottedCsmaCa(), IsUnSlottedCsmaCa(), SetSlottedCsmaCa(), and SetUnSlottedCsmaCa().
m_lrWpanMacStateCallback
LrWpanMacStateCallback ns3::LrWpanCsmaCa::m_lrWpanMacStateCallback private
The callback to inform the configured MAC of the CSMA/CA result.
Definition at line 280 of file lr-wpan-csmaca.h.
Referenced by DeferCsmaTimeout(), DoDispose(), PlmeCcaConfirm(), and SetLrWpanMacStateCallback().
m_lrWpanMacTransCostCallback
LrWpanMacTransCostCallback ns3::LrWpanCsmaCa::m_lrWpanMacTransCostCallback private
The callback to inform the cost of a transaction in slotted CSMA-CA.
Definition at line 276 of file lr-wpan-csmaca.h.
Referenced by CanProceed(), DoDispose(), and SetLrWpanMacTransCostCallback().
m_mac
Ptr<LrWpanMac> ns3::LrWpanCsmaCa::m_mac private
The MAC instance for which this CSMA/CA implemenation is configured.
Definition at line 288 of file lr-wpan-csmaca.h.
Referenced by ~LrWpanCsmaCa(), CanProceed(), DoDispose(), GetMac(), GetTimeLeftInCap(), GetTimeToNextSlot(), RandomBackoffDelay(), RequestCCA(), SetMac(), and Start().
m_macBattLifeExt
bool ns3::LrWpanCsmaCa::m_macBattLifeExt private
Battery Life Extension.
Definition at line 304 of file lr-wpan-csmaca.h.
Referenced by LrWpanCsmaCa(), GetBatteryLifeExtension(), SetBatteryLifeExtension(), and Start().
m_macMaxBE
uint8_t ns3::LrWpanCsmaCa::m_macMaxBE private
Maximum backoff exponent.
3 - 8, default 5
Definition at line 312 of file lr-wpan-csmaca.h.
Referenced by LrWpanCsmaCa(), GetMacMaxBE(), and PlmeCcaConfirm().
m_macMaxCSMABackoffs
uint8_t ns3::LrWpanCsmaCa::m_macMaxCSMABackoffs private
Maximum number of backoffs.
0 - 5, default 4
Definition at line 316 of file lr-wpan-csmaca.h.
Referenced by LrWpanCsmaCa(), GetMacMaxCSMABackoffs(), PlmeCcaConfirm(), and SetMacMaxCSMABackoffs().
m_macMinBE
uint8_t ns3::LrWpanCsmaCa::m_macMinBE private
Minimum backoff exponent.
0 - macMaxBE, default 3
Definition at line 308 of file lr-wpan-csmaca.h.
Referenced by LrWpanCsmaCa(), GetMacMinBE(), SetMacMaxBE(), SetMacMinBE(), and Start().
m_NB
uint8_t ns3::LrWpanCsmaCa::m_NB private
Number of backoffs for the current transmission.
Definition at line 292 of file lr-wpan-csmaca.h.
Referenced by LrWpanCsmaCa(), GetNB(), PlmeCcaConfirm(), and Start().
m_random
Ptr<UniformRandomVariable> ns3::LrWpanCsmaCa::m_random private
Uniform random variable stream.
Definition at line 328 of file lr-wpan-csmaca.h.
Referenced by LrWpanCsmaCa(), AssignStreams(), and RandomBackoffDelay().
m_randomBackoffEvent
EventId ns3::LrWpanCsmaCa::m_randomBackoffEvent private
Scheduler event for the start of the next random backoff/slot.
Definition at line 332 of file lr-wpan-csmaca.h.
Referenced by Cancel(), PlmeCcaConfirm(), and Start().
m_randomBackoffPeriodsLeft
uint64_t ns3::LrWpanCsmaCa::m_randomBackoffPeriodsLeft private
Count the number of remaining random backoff periods left to delay.
Definition at line 324 of file lr-wpan-csmaca.h.
Referenced by LrWpanCsmaCa(), CanProceed(), and RandomBackoffDelay().
m_requestCcaEvent
EventId ns3::LrWpanCsmaCa::m_requestCcaEvent private
Scheduler event when to start the CCA after a random backoff.
Definition at line 340 of file lr-wpan-csmaca.h.
Referenced by Cancel(), CanProceed(), PlmeCcaConfirm(), and RandomBackoffDelay().
The documentation for this class was generated from the following files:
src/lr-wpan/model/lr-wpan-csmaca.h
src/lr-wpan/model/lr-wpan-csmaca.cc