ns-3: ns3::BSScheduler Class Reference
ns3::BSScheduler Class Reference abstract
WiMAX Models
#include "bs-scheduler.h"
Public Member Functions
BSScheduler ()
BSScheduler (Ptr< BaseStationNetDevice > bs)
Constructor.
~BSScheduler (void)
virtual void AddDownlinkBurst (Ptr< const WimaxConnection > connection, uint8_t diuc, WimaxPhy::ModulationType modulationType, Ptr< PacketBurst > burst)=0
This function adds a downlink burst to the list of downlink bursts scheduled for the next downlink sub-frame.
bool CheckForFragmentation (Ptr< WimaxConnection > connection, int availableSymbols, WimaxPhy::ModulationType modulationType)
Check if the packet fragmentation is possible for transport connection.
virtual Ptr< PacketBurst > CreateUgsBurst (ServiceFlow *serviceFlow, WimaxPhy::ModulationType modulationType, uint32_t availableSymbols)=0
Creates a downlink UGS burst.
virtual Ptr< BaseStationNetDevice > GetBs (void)
Get the base station.
virtual std::list< std::pair< OfdmDlMapIe *, Ptr< PacketBurst > > > * GetDownlinkBursts (void) const =0
This function returns all the downlink bursts scheduled for the next downlink sub-frame.
virtual void Schedule (void)=0
the scheduling function for the downlink subframe.
virtual bool SelectConnection (Ptr< WimaxConnection > &connection)=0
Selects a connection from the list of connections having packets to be sent .
virtual void SetBs (Ptr< BaseStationNetDevice > bs)
Set the base station.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Ptr< BaseStationNetDevice > m_bs
base station
std::list< std::pair< OfdmDlMapIe *, Ptr< PacketBurst > > > * m_downlinkBursts
down link bursts
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Config Paths
ns3::BSScheduler is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WimaxNetDevice/$ns3::BaseStationNetDevice/BSScheduler"
"/NodeList/[i]/DeviceList/[i]/$ns3::WimaxNetDevice/$ns3::BaseStationNetDevice/Scheduler"
"/NodeList/[i]/DeviceList/[i]/$ns3::BaseStationNetDevice/BSScheduler"
"/NodeList/[i]/DeviceList/[i]/$ns3::BaseStationNetDevice/Scheduler"
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 48 bytes (on a 64-bit architecture).
Definition at line 43 of file bs-scheduler.h.
Constructor & Destructor Documentation
BSScheduler() [1/2]
ns3::BSScheduler::BSScheduler ()
Definition at line 55 of file bs-scheduler.cc.
BSScheduler() [2/2]
ns3::BSScheduler::BSScheduler (Ptr< BaseStationNetDevice > bs)
Constructor.
Parameters
bs base station device
Definition at line 62 of file bs-scheduler.cc.
~BSScheduler()
ns3::BSScheduler::~BSScheduler (void)
Definition at line 68 of file bs-scheduler.cc.
References m_downlinkBursts, and SetBs().
Member Function Documentation
AddDownlinkBurst()
virtual void ns3::BSScheduler::AddDownlinkBurst (Ptr< const WimaxConnection > connection, uint8_t diuc, WimaxPhy::ModulationType modulationType, Ptr< PacketBurst > burst) pure virtual
This function adds a downlink burst to the list of downlink bursts scheduled for the next downlink sub-frame.
Parameters
connection a pointer to connection in which the burst will be sent
diuc downlink iuc
modulationType the modulation type of the burst
burst the downlink burst to add to the downlink sub frame
Implemented in ns3::BSSchedulerSimple, and ns3::BSSchedulerRtps.
CheckForFragmentation()
bool ns3::BSScheduler::CheckForFragmentation (Ptr< WimaxConnection > connection, int availableSymbols, WimaxPhy::ModulationType modulationType)
Check if the packet fragmentation is possible for transport connection.
Parameters
connection the downlink connection
availableSymbols maximum number of OFDM symbols to be used by the burst
modulationType the modulation type to be used for the burst
Returns
false if packet fragmentation is not possible, true otherwise
Definition at line 95 of file bs-scheduler.cc.
References GetBs(), ns3::MacHeaderType::HEADER_TYPE_GENERIC, NS_LOG_INFO, and ns3::Cid::TRANSPORT.
Referenced by ns3::BSSchedulerRtps::BSSchedulerBasicConnection(), ns3::BSSchedulerRtps::BSSchedulerBroadcastConnection(), ns3::BSSchedulerRtps::BSSchedulerInitialRangingConnection(), ns3::BSSchedulerRtps::BSSchedulerPrimaryConnection(), ns3::BSSchedulerRtps::BSSchedulerRTPSConnection(), ns3::BSSchedulerRtps::CreateUgsBurst(), ns3::BSSchedulerSimple::CreateUgsBurst(), and ns3::BSSchedulerSimple::Schedule().
CreateUgsBurst()
virtual Ptr<PacketBurst> ns3::BSScheduler::CreateUgsBurst (ServiceFlow * serviceFlow, WimaxPhy::ModulationType modulationType, uint32_t availableSymbols) pure virtual
Creates a downlink UGS burst.
Parameters
serviceFlow the service flow of the burst
modulationType the modulation type to be used for the burst
availableSymbols maximum number of OFDM symbols to be used by the burst
Returns
a Burst (list of packets)
Implemented in ns3::BSSchedulerSimple, and ns3::BSSchedulerRtps.
GetBs()
Ptr< BaseStationNetDevice > ns3::BSScheduler::GetBs (void) virtual
Get the base station.
Returns
the base station net device
Definition at line 89 of file bs-scheduler.cc.
References m_bs.
Referenced by ns3::BSSchedulerRtps::BSSchedulerBasicConnection(), ns3::BSSchedulerRtps::BSSchedulerBEConnection(), ns3::BSSchedulerRtps::BSSchedulerBroadcastConnection(), ns3::BSSchedulerRtps::BSSchedulerInitialRangingConnection(), ns3::BSSchedulerRtps::BSSchedulerNRTPSConnection(), ns3::BSSchedulerRtps::BSSchedulerPrimaryConnection(), ns3::BSSchedulerRtps::BSSchedulerRTPSConnection(), ns3::BSSchedulerRtps::BSSchedulerUGSConnection(), CheckForFragmentation(), ns3::BSSchedulerRtps::CreateUgsBurst(), ns3::BSSchedulerSimple::CreateUgsBurst(), ns3::BSSchedulerRtps::Schedule(), ns3::BSSchedulerSimple::Schedule(), and ns3::BSSchedulerSimple::SelectConnection().
GetDownlinkBursts()
virtual std::list<std::pair<OfdmDlMapIe*, Ptr<PacketBurst> > >* ns3::BSScheduler::GetDownlinkBursts (void) const pure virtual
This function returns all the downlink bursts scheduled for the next downlink sub-frame.
Returns
all the downlink bursts scheduled for the next downlink sub-frame
Implemented in ns3::BSSchedulerSimple, and ns3::BSSchedulerRtps.
GetTypeId()
TypeId ns3::BSScheduler::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 45 of file bs-scheduler.cc.
References ns3::TypeId::SetParent().
Schedule()
virtual void ns3::BSScheduler::Schedule (void) pure virtual
the scheduling function for the downlink subframe.
Implemented in ns3::BSSchedulerSimple, and ns3::BSSchedulerRtps.
SelectConnection()
virtual bool ns3::BSScheduler::SelectConnection (Ptr< WimaxConnection > & connection) pure virtual
Selects a connection from the list of connections having packets to be sent .
Parameters
connection will point to a connection that have packets to be sent
Returns
false if no connection has packets to be sent, true otherwise
Implemented in ns3::BSSchedulerSimple, and ns3::BSSchedulerRtps.
SetBs()
void ns3::BSScheduler::SetBs (Ptr< BaseStationNetDevice > bs) virtual
Set the base station.
Parameters
bs the base station net device
Definition at line 84 of file bs-scheduler.cc.
References m_bs.
Referenced by ns3::BSSchedulerRtps::BSSchedulerRtps(), ns3::BSSchedulerSimple::BSSchedulerSimple(), ~BSScheduler(), ns3::BSSchedulerRtps::~BSSchedulerRtps(), and ns3::BSSchedulerSimple::~BSSchedulerSimple().
Member Data Documentation
m_bs
Ptr<BaseStationNetDevice> ns3::BSScheduler::m_bs private
base station
Definition at line 125 of file bs-scheduler.h.
Referenced by GetBs(), and SetBs().
m_downlinkBursts
std::list<std::pair<OfdmDlMapIe*, Ptr<PacketBurst> > >* ns3::BSScheduler::m_downlinkBursts private
down link bursts
Definition at line 126 of file bs-scheduler.h.
Referenced by ~BSScheduler().
The documentation for this class was generated from the following files:
src/wimax/model/bs-scheduler.h
src/wimax/model/bs-scheduler.cc