ns-3: ns3::Ipv4NixVectorHelper Class Reference
ns3::Ipv4NixVectorHelper Class Reference
Nix-Vector Routing
Helper class that adds Nix-vector routing to nodes.
#include "ipv4-nix-vector-helper.h"
Public Member Functions
Ipv4NixVectorHelper ()
Construct an Ipv4NixVectorHelper to make life easier while adding Nix-vector routing to nodes.
Ipv4NixVectorHelper (const Ipv4NixVectorHelper &)
Construct an Ipv4NixVectorHelper from another previously initialized instance (Copy Constructor).
Ipv4NixVectorHelper * Copy (void) const
virtual Ptr< Ipv4RoutingProtocol > Create (Ptr< Node > node) const
Public Member Functions inherited from ns3::Ipv4RoutingHelper
virtual ~Ipv4RoutingHelper ()
Private Member Functions
Ipv4NixVectorHelper & operator= (const Ipv4NixVectorHelper &)
Assignment operator declared private and not implemented to disallow assignment and prevent the compiler from happily inserting its own.
Private Attributes
ObjectFactory m_agentFactory
Object factory.
Additional Inherited Members
Static Public Member Functions inherited from ns3::Ipv4RoutingHelper
template<class T >
static Ptr< T > GetRouting (Ptr< Ipv4RoutingProtocol > protocol)
Request a specified routing protocol <T> from Ipv4RoutingProtocol protocol.
static void PrintNeighborCacheAllAt (Time printTime, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the neighbor cache of all nodes at a particular time.
static void PrintNeighborCacheAllEvery (Time printInterval, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the neighbor cache of all nodes at regular intervals specified by user.
static void PrintNeighborCacheAt (Time printTime, Ptr< Node > node, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the neighbor cache of a node at a particular time.
static void PrintNeighborCacheEvery (Time printInterval, Ptr< Node > node, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the neighbor cache of a node at regular intervals specified by user.
static void PrintRoutingTableAllAt (Time printTime, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of all nodes at a particular time.
static void PrintRoutingTableAllEvery (Time printInterval, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of all nodes at regular intervals specified by user.
static void PrintRoutingTableAt (Time printTime, Ptr< Node > node, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of a node at a particular time.
static void PrintRoutingTableEvery (Time printInterval, Ptr< Node > node, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of a node at regular intervals specified by user.
Detailed Description
Helper class that adds Nix-vector routing to nodes.
This class is expected to be used in conjunction with ns3::InternetStackHelper::SetRoutingHelper
Definition at line 38 of file ipv4-nix-vector-helper.h.
Constructor & Destructor Documentation
Ipv4NixVectorHelper() [1/2]
ns3::Ipv4NixVectorHelper::Ipv4NixVectorHelper ()
Construct an Ipv4NixVectorHelper to make life easier while adding Nix-vector routing to nodes.
Definition at line 26 of file ipv4-nix-vector-helper.cc.
References m_agentFactory, and ns3::ObjectFactory::SetTypeId().
Referenced by Copy().
Ipv4NixVectorHelper() [2/2]
ns3::Ipv4NixVectorHelper::Ipv4NixVectorHelper (const Ipv4NixVectorHelper & o)
Construct an Ipv4NixVectorHelper from another previously initialized instance (Copy Constructor).
Definition at line 31 of file ipv4-nix-vector-helper.cc.
Member Function Documentation
Copy()
Ipv4NixVectorHelper * ns3::Ipv4NixVectorHelper::Copy (void) const virtual
Returns
pointer to clone of this Ipv4NixVectorHelper
This method is mainly for internal use by the other helpers; clients are expected to free the dynamic memory allocated by this method
Implements ns3::Ipv4RoutingHelper.
Definition at line 37 of file ipv4-nix-vector-helper.cc.
References Ipv4NixVectorHelper().
Create()
Ptr< Ipv4RoutingProtocol > ns3::Ipv4NixVectorHelper::Create (Ptr< Node > node) const virtual
Parameters
node the node on which the routing protocol will run
Returns
a newly-created routing protocol
This method will be called by ns3::InternetStackHelper::Install
Implements ns3::Ipv4RoutingHelper.
Definition at line 43 of file ipv4-nix-vector-helper.cc.
References ns3::Object::AggregateObject(), ns3::ObjectFactory::Create(), and m_agentFactory.
operator=()
Ipv4NixVectorHelper& ns3::Ipv4NixVectorHelper::operator= (const Ipv4NixVectorHelper &) private
Assignment operator declared private and not implemented to disallow assignment and prevent the compiler from happily inserting its own.
Returns
Nothing useful.
Member Data Documentation
m_agentFactory
ObjectFactory ns3::Ipv4NixVectorHelper::m_agentFactory private
Object factory.
Definition at line 77 of file ipv4-nix-vector-helper.h.
Referenced by Ipv4NixVectorHelper(), and Create().
The documentation for this class was generated from the following files:
src/nix-vector-routing/helper/ipv4-nix-vector-helper.h
src/nix-vector-routing/helper/ipv4-nix-vector-helper.cc