ns-3: ns3::WifiTxVector Class Reference
ns3::WifiTxVector Class Reference
This class mimics the TXVECTOR which is to be passed to the PHY in order to define the parameters which are to be used for a transmission.
#include "wifi-tx-vector.h"
Public Types
typedef std::map< uint16_t, HeMuUserInfo > HeMuUserInfoMap
map of HE MU specific user info paramters indexed by STA-ID
Public Member Functions
WifiTxVector ()
WifiTxVector (const WifiTxVector &txVector)
Copy constructor.
WifiTxVector (WifiMode mode, uint8_t powerLevel, WifiPreamble preamble, uint16_t guardInterval, uint8_t nTx, uint8_t nss, uint8_t ness, uint16_t channelWidth, bool aggregation, bool stbc=false, bool ldpc=false, uint8_t bssColor=0)
Create a TXVECTOR with the given parameters.
~WifiTxVector ()
uint8_t GetBssColor (void) const
Get the BSS color.
uint16_t GetChannelWidth (void) const
uint16_t GetGuardInterval (void) const
HeMuUserInfo GetHeMuUserInfo (uint16_t staId) const
Get the HE MU user-specific transmission information for the given STA-ID.
const HeMuUserInfoMap & GetHeMuUserInfoMap (void) const
Get the map HE MU user-specific transmission information indexed by STA-ID.
WifiMode GetMode (uint16_t staId=SU_STA_ID) const
If this TX vector is associated with an SU PPDU, return the selected payload transmission mode.
bool GetModeInitialized (void) const
uint8_t GetNess (void) const
uint8_t GetNss (uint16_t staId=SU_STA_ID) const
If this TX vector is associated with an SU PPDU, return the number of spatial streams.
uint8_t GetNssMax (void) const
uint8_t GetNTx (void) const
WifiPreamble GetPreambleType (void) const
HeRu::RuSpec GetRu (uint16_t staId) const
Get the RU specification for the STA-ID.
uint8_t GetTxPowerLevel (void) const
bool IsAggregation (void) const
Checks whether the PSDU contains A-MPDU.
bool IsLdpc (void) const
Check if LDPC FEC coding is used or not.
bool IsStbc (void) const
Check if STBC is used or not.
bool IsValid (void) const
The standard disallows certain combinations of WifiMode, number of spatial streams, and channel widths.
void SetAggregation (bool aggregation)
Sets if PSDU contains A-MPDU.
void SetBssColor (uint8_t color)
Set the BSS color.
void SetChannelWidth (uint16_t channelWidth)
Sets the selected channelWidth (in MHz)
void SetGuardInterval (uint16_t guardInterval)
Sets the guard interval duration (in nanoseconds)
void SetHeMuUserInfo (uint16_t staId, HeMuUserInfo userInfo)
Set the HE MU user-specific transmission information for the given STA-ID.
void SetLdpc (bool ldpc)
Sets if LDPC FEC coding is being used.
void SetMode (WifiMode mode)
Sets the selected payload transmission mode.
void SetMode (WifiMode mode, uint16_t staId)
Sets the selected payload transmission mode for a given STA ID (for HE MU only)
void SetNess (uint8_t ness)
Sets the Ness number.
void SetNss (uint8_t nss)
Sets the number of Nss.
void SetNss (uint8_t nss, uint16_t staId)
Sets the number of Nss for HE MU.
void SetNTx (uint8_t nTx)
Sets the number of TX antennas.
void SetPreambleType (WifiPreamble preamble)
Sets the preamble type.
void SetRu (HeRu::RuSpec ru, uint16_t staId)
Set the RU specification for the STA-ID.
void SetStbc (bool stbc)
Sets if STBC is being used.
void SetTxPowerLevel (uint8_t powerlevel)
Sets the selected transmission power level.
Private Attributes
bool m_aggregation
Flag whether the PSDU contains A-MPDU.
uint8_t m_bssColor
BSS color.
uint16_t m_channelWidth
channel width in MHz
uint16_t m_guardInterval
guard interval duration in nanoseconds
bool m_ldpc
LDPC FEC coding if true, BCC otherwise.
WifiMode m_mode
The DATARATE parameter in Table 15-4.
bool m_modeInitialized
Internal initialization flag.
HeMuUserInfoMap m_muUserInfos
HE MU specific per-user information indexed by station ID (STA-ID) corresponding to the 11 LSBs of the AID of the recipient STA This list shall be used only for HE MU.
uint8_t m_ness
number of spatial streams in beamforming
uint8_t m_nss
number of spatial streams
uint8_t m_nTx
number of TX antennas
WifiPreamble m_preamble
preamble
bool m_stbc
STBC used or not.
uint8_t m_txPowerLevel
The TXPWR_LEVEL parameter in Table 15-4.
Detailed Description
This class mimics the TXVECTOR which is to be passed to the PHY in order to define the parameters which are to be used for a transmission.
See IEEE 802.11-2016 16.2.5 "Transmit PHY", and also 8.3.4.1 "PHY SAP peer-to-peer service primitive parameters".
If this class is constructed with the constructor that takes no arguments, then the client must explicitly set the mode and transmit power level parameters before using them. Default member initializers are provided for the other parameters, to conform to a non-MIMO/long guard configuration, although these may also be explicitly set after object construction.
When used in a infrastructure context, WifiTxVector values should be drawn from WifiRemoteStationManager parameters since rate adaptation is responsible for picking the mode, number of streams, etc., but in the case in which there is no such manager (e.g. mesh), the client still needs to initialize at least the mode and transmit power level appropriately.
Note
the above reference is valid for the DSSS PHY only (clause 16). TXVECTOR is defined also for the other PHYs, however they don't include the TXPWRLVL explicitly in the TXVECTOR. This is somewhat strange, since all PHYs actually have a PMD_TXPWRLVL.request primitive. We decide to include the power level in WifiTxVector for all PHYs, since it serves better our purposes, and furthermore it seems close to the way real devices work (e.g., madwifi).
Definition at line 70 of file wifi-tx-vector.h.
Member Typedef Documentation
HeMuUserInfoMap
typedef std::map<uint16_t , HeMuUserInfo > ns3::WifiTxVector::HeMuUserInfoMap
map of HE MU specific user info paramters indexed by STA-ID
Definition at line 74 of file wifi-tx-vector.h.
Constructor & Destructor Documentation
WifiTxVector() [1/3]
ns3::WifiTxVector::WifiTxVector ()
Definition at line 27 of file wifi-tx-vector.cc.
~WifiTxVector()
ns3::WifiTxVector::~WifiTxVector ()
Definition at line 95 of file wifi-tx-vector.cc.
References m_muUserInfos.
WifiTxVector() [2/3]
ns3::WifiTxVector::WifiTxVector (WifiMode mode, uint8_t powerLevel, WifiPreamble preamble, uint16_t guardInterval, uint8_t nTx, uint8_t nss, uint8_t ness, uint16_t channelWidth, bool aggregation, bool stbc = false, bool ldpc = false, uint8_t bssColor = 0)
Create a TXVECTOR with the given parameters.
Parameters
mode WifiMode
powerLevel transmission power level
preamble preamble type
guardInterval the guard interval duration in nanoseconds
nTx the number of TX antennas
nss the number of spatial STBC streams (NSS)
ness the number of extension spatial streams (NESS)
channelWidth the channel width in MHz
aggregation enable or disable MPDU aggregation
stbc enable or disable STBC
ldpc enable or disable LDPC (BCC is used otherwise)
bssColor the BSS color
Definition at line 42 of file wifi-tx-vector.cc.
WifiTxVector() [3/3]
ns3::WifiTxVector::WifiTxVector (const WifiTxVector & txVector)
Copy constructor.
Parameters
txVector the TXVECTOR to copy
Definition at line 70 of file wifi-tx-vector.cc.
References m_muUserInfos.
Member Function Documentation
GetBssColor()
uint8_t ns3::WifiTxVector::GetBssColor (void) const
Get the BSS color.
Returns
the BSS color
Definition at line 297 of file wifi-tx-vector.cc.
References m_bssColor.
Referenced by ns3::WifiPhyHelper::GetRadiotapHeader(), and ns3::WifiPpdu::SetPhyHeaders().
GetChannelWidth()
uint16_t ns3::WifiTxVector::GetChannelWidth (void) const
Returns
the channel width (in MHz)
Definition at line 135 of file wifi-tx-vector.cc.
References m_channelWidth.
Referenced by ns3::IdealWifiManager::AddSnrThreshold(), ns3::InterferenceHelper::CalculateChunkSuccessRate(), ns3::InterferenceHelper::CalculateHtPhyHeaderPer(), ns3::InterferenceHelper::CalculateNonHtPhyHeaderPer(), ns3::YansErrorRateModel::DoGetChunkSuccessRate(), ns3::IdealWifiManager::DoGetDataTxVector(), WifiErrorRateModelsTestCaseMimo::DoRun(), ns3::WifiPhy::EndOfMpdu(), ns3::WifiPhy::EndReceive(), ns3::SpectrumWifiPhy::GetCenterFrequencyForChannelWidth(), ns3::WifiMode::GetDataRate(), ns3::WaveMacLow::GetDataTxVector(), ns3::WifiPhy::GetPayloadDuration(), ns3::WifiPhy::GetPhyHeaderDuration(), ns3::WifiPhy::GetPhyHeaderMode(), ns3::WifiPhy::GetPhyPreambleDuration(), ns3::WifiMode::GetPhyRate(), ns3::WifiPhyHelper::GetRadiotapHeader(), ns3::WifiPhy::GetRuBand(), ns3::operator<<(), ns3::WifiRemoteStationManager::ReportAmpduTxStatus(), ns3::WifiRemoteStationManager::ReportDataOk(), ns3::WifiPhy::StartReceivePayload(), ns3::SpectrumWifiPhy::StartTx(), Bug2843TestCase::StoreDistinctTuple(), PowerRateAdaptationTest::TestAparf(), PowerRateAdaptationTest::TestParf(), and PowerRateAdaptationTest::TestRrpaa().
GetGuardInterval()
uint16_t ns3::WifiTxVector::GetGuardInterval (void) const
Returns
the guard interval duration (in nanoseconds)
Definition at line 141 of file wifi-tx-vector.cc.
References m_guardInterval.
Referenced by ns3::IdealWifiManager::DoGetDataTxVector(), ns3::WifiMode::GetDataRate(), ns3::WifiPhy::GetPayloadDuration(), ns3::WifiMode::GetPhyRate(), ns3::WifiPhyHelper::GetRadiotapHeader(), ns3::WifiPpdu::GetTxDuration(), ns3::operator<<(), ns3::WifiPpdu::SetPhyHeaders(), and PowerRateAdaptationTest::TestRrpaa().
GetHeMuUserInfo()
HeMuUserInfo ns3::WifiTxVector::GetHeMuUserInfo (uint16_t staId) const
Get the HE MU user-specific transmission information for the given STA-ID.
This is applicable only for HE MU.
Parameters
staId the station ID
Returns
the HE MU user-specific transmission information for the given STA-ID
Definition at line 355 of file wifi-tx-vector.cc.
References m_muUserInfos, m_preamble, NS_ABORT_MSG_IF, and ns3::WIFI_PREAMBLE_HE_MU.
Referenced by ns3::WifiPhyHelper::GetRadiotapHeader().
GetHeMuUserInfoMap()
const WifiTxVector::HeMuUserInfoMap & ns3::WifiTxVector::GetHeMuUserInfoMap (void) const
Get the map HE MU user-specific transmission information indexed by STA-ID.
This is applicable only for HE MU.
Returns
the map of HE MU user-specific information indexed by STA-ID
Definition at line 372 of file wifi-tx-vector.cc.
References m_muUserInfos, m_preamble, NS_ABORT_MSG_IF, and ns3::WIFI_PREAMBLE_HE_MU.
Referenced by ns3::WifiPpdu::WifiPpdu(), ns3::WifiPhy::CalculateTxDuration(), ns3::operator<<(), and ns3::WifiPhy::StartReceivePayload().
GetMode()
WifiMode ns3::WifiTxVector::GetMode (uint16_t staId = SU_STA_ID) const
If this TX vector is associated with an SU PPDU, return the selected payload transmission mode.
If this TX vector is associated with an MU PPDU, return the transmission mode (MCS) selected for the transmission to the station identified by the given STA-ID.
Parameters
staId the station ID for HE MU
Returns
the selected payload transmission mode
Definition at line 107 of file wifi-tx-vector.cc.
References m_mode, m_modeInitialized, m_muUserInfos, m_preamble, NS_ABORT_MSG_IF, NS_ASSERT, NS_FATAL_ERROR, ns3::WIFI_PREAMBLE_HE_MU, and ns3::WIFI_PREAMBLE_HE_TB.
Referenced by ns3::IdealWifiManager::AddSnrThreshold(), ns3::InterferenceHelper::CalculatePayloadChunkSuccessRate(), ns3::InterferenceHelper::CalculatePayloadPer(), ns3::ErrorRateModel::CalculateSnr(), TxDurationTest::CheckHeMuTxDuration(), IdealRateManagerMimoTest::CheckLastSelectedMode(), ns3::YansErrorRateModel::DoGetChunkSuccessRate(), ns3::MinstrelHtWifiManager::DoGetDataTxVector(), ns3::MacLow::ForwardDown(), ns3::MacLow::GetAckDuration(), ns3::MacLow::GetCtsDuration(), ns3::WifiRemoteStationManager::GetDataTxVector(), ns3::WaveMacLow::GetDataTxVector(), ns3::MpduAggregator::GetNextAmpdu(), ns3::MsduAggregator::GetNextAmsdu(), ns3::WifiPhy::GetPayloadDuration(), ns3::WifiPhy::GetPhyHeaderDuration(), ns3::WifiPhy::GetPhyHeaderMode(), ns3::WifiPhy::GetPhyPreambleDuration(), ns3::WifiPhyHelper::GetRadiotapHeader(), ns3::MacLow::GetResponseDuration(), ns3::MacLow::IsWithinSizeAndTimeLimits(), ns3::WifiRemoteStationManager::NeedCtsToSelf(), ns3::WifiRemoteStationManager::NeedRts(), ns3::operator<<(), ns3::MacLow::ReceiveOk(), ns3::MacLow::SendBlockAckAfterAmpdu(), ns3::MacLow::SendCtsAfterRts(), ns3::MacLow::SendDataPacket(), ns3::WifiPpdu::SetPhyHeaders(), ns3::MacLow::StartDataTxTimers(), ns3::WifiPhy::StartReceivePayload(), ns3::MacLow::StartTransmission(), Bug2843TestCase::StoreDistinctTuple(), ns3::WifiPhyStateHelper::SwitchFromRxEndOk(), ns3::WifiPhyStateHelper::SwitchToTx(), PowerRateAdaptationTest::TestAparf(), PowerRateAdaptationTest::TestParf(), PowerRateAdaptationTest::TestRrpaa(), IdealRateManagerChannelWidthTest::TxCallback(), and Issue169TestCase::TxCallback().
GetModeInitialized()
bool ns3::WifiTxVector::GetModeInitialized (void) const
Returns
whether mode has been initialized
Definition at line 101 of file wifi-tx-vector.cc.
References m_modeInitialized.
Referenced by IsValid(), and ns3::WifiPhy::StartReceivePreamble().
GetNess()
uint8_t ns3::WifiTxVector::GetNess (void) const
Returns
the number of extended spatial streams
Definition at line 183 of file wifi-tx-vector.cc.
References m_ness.
Referenced by ns3::WifiPhy::GetPhyTrainingSymbolDuration(), ns3::WifiPhyHelper::GetRadiotapHeader(), and ns3::operator<<().
GetNss()
uint8_t ns3::WifiTxVector::GetNss (uint16_t staId = SU_STA_ID) const
If this TX vector is associated with an SU PPDU, return the number of spatial streams.
If this TX vector is associated with an MU PPDU, return the number of spatial streams for the transmission to the station identified by the given STA-ID.
Parameters
staId the station ID for HE MU
Returns
the number of spatial streams
Definition at line 153 of file wifi-tx-vector.cc.
References m_muUserInfos, m_nss, m_preamble, NS_ABORT_MSG_IF, NS_ASSERT, ns3::WIFI_PREAMBLE_HE_MU, and ns3::WIFI_PREAMBLE_HE_TB.
Referenced by ns3::InterferenceHelper::CalculatePayloadChunkSuccessRate(), ns3::InterferenceHelper::CalculatePayloadPer(), TxDurationTest::CheckHeMuTxDuration(), IdealRateManagerMimoTest::CheckLastSelectedNss(), ns3::IdealWifiManager::DoGetDataTxVector(), WifiErrorRateModelsTestCaseMimo::DoRun(), ns3::WifiPhy::EndOfMpdu(), ns3::WifiPhy::EndReceive(), ns3::WifiMode::GetDataRate(), ns3::WifiPhy::GetPayloadDuration(), ns3::WifiMode::GetPhyRate(), ns3::WifiPhyHelper::GetRadiotapHeader(), ns3::operator<<(), ns3::WifiRemoteStationManager::ReportAmpduTxStatus(), ns3::WifiRemoteStationManager::ReportDataOk(), and ns3::WifiPpdu::SetPhyHeaders().
GetNssMax()
uint8_t ns3::WifiTxVector::GetNssMax (void) const
Returns
the maximum number of Nss (namely if HE MU)
Definition at line 165 of file wifi-tx-vector.cc.
References m_muUserInfos, m_nss, m_preamble, ns3::WIFI_PREAMBLE_HE_MU, and ns3::WIFI_PREAMBLE_HE_TB.
Referenced by ns3::WifiPhy::GetPhyTrainingSymbolDuration(), ns3::WifiPhy::GetTxPowerForTransmission(), ns3::WifiPhy::Send(), and ns3::WifiPhy::StartReceivePayload().
GetNTx()
uint8_t ns3::WifiTxVector::GetNTx (void) const
Returns
the number of TX antennas
Definition at line 147 of file wifi-tx-vector.cc.
References m_nTx.
Referenced by ns3::operator<<().
GetPreambleType()
WifiPreamble ns3::WifiTxVector::GetPreambleType (void) const
Returns
the preamble type
Definition at line 129 of file wifi-tx-vector.cc.
References m_preamble.
Referenced by ns3::HigherLayerTxVectorTag::HigherLayerTxVectorTag(), ns3::InterferenceHelper::CalculateHtPhyHeaderPer(), ns3::InterferenceHelper::CalculateNonHtPhyHeaderPer(), ns3::InterferenceHelper::CalculatePayloadPer(), ns3::WifiPhy::CalculatePhyPreambleAndHeaderDuration(), ns3::WifiPhy::CalculateTxDuration(), ns3::WifiPhy::EndReceive(), ns3::MacLow::ForwardDown(), ns3::WifiMode::GetDataRate(), ns3::WaveMacLow::GetDataTxVector(), ns3::WifiPhy::GetPhyHeaderDuration(), ns3::WifiPhy::GetPhyHeaderMode(), ns3::WifiPhy::GetPhyPreambleDuration(), ns3::WifiPhy::GetPhyTrainingSymbolDuration(), ns3::WifiPhyHelper::GetRadiotapHeader(), ns3::WifiPhy::GetReceptionStatus(), ns3::WifiPhy::GetRuBand(), ns3::MacLow::IsWithinSizeAndTimeLimits(), ns3::operator<<(), ns3::WifiPhy::StartReceiveHeader(), ns3::WifiPhy::StartReceivePayload(), ns3::WifiPhyStateHelper::SwitchFromRxEndOk(), and ns3::WifiPhyStateHelper::SwitchToTx().
GetRu()
HeRu::RuSpec ns3::WifiTxVector::GetRu (uint16_t staId) const
Get the RU specification for the STA-ID.
This is applicable only for HE MU.
Parameters
staId the station ID
Returns
the RU specification for the STA-ID
Definition at line 339 of file wifi-tx-vector.cc.
References m_muUserInfos, m_preamble, NS_ABORT_MSG_IF, and ns3::WIFI_PREAMBLE_HE_MU.
Referenced by ns3::WifiPhy::EndReceive(), ns3::WifiMode::GetDataRate(), ns3::WifiPhy::GetReceptionStatus(), and ns3::WifiPhy::GetRuBand().
GetTxPowerLevel()
uint8_t ns3::WifiTxVector::GetTxPowerLevel (void) const
Returns
the transmission power level
Definition at line 123 of file wifi-tx-vector.cc.
References m_txPowerLevel.
Referenced by ns3::WaveMacLow::GetDataTxVector(), ns3::WifiPhy::GetTxPowerForTransmission(), ns3::operator<<(), ns3::WifiPhy::Send(), ns3::YansWifiPhy::StartTx(), ns3::WifiPhyStateHelper::SwitchToTx(), PowerRateAdaptationTest::TestAparf(), PowerRateAdaptationTest::TestParf(), and PowerRateAdaptationTest::TestRrpaa().
IsAggregation()
bool ns3::WifiTxVector::IsAggregation (void) const
Checks whether the PSDU contains A-MPDU.
Returns
true if this PSDU has A-MPDU aggregation, false otherwise.
Definition at line 189 of file wifi-tx-vector.cc.
References m_aggregation.
Referenced by ns3::MacLow::DeaggregateAmpduAndReceive(), ns3::WifiPhyHelper::GetRadiotapHeader(), ns3::WifiPhy::NotifyMonitorSniffRx(), ns3::WifiPhy::NotifyMonitorSniffTx(), ns3::operator<<(), and ns3::WifiPpdu::SetPhyHeaders().
IsLdpc()
bool ns3::WifiTxVector::IsLdpc (void) const
Check if LDPC FEC coding is used or not.
Returns
true if LDPC is used, false if BCC is used
Definition at line 201 of file wifi-tx-vector.cc.
References m_ldpc.
Referenced by ns3::TableBasedErrorRateModel::DoGetChunkSuccessRate(), ns3::operator<<(), and ns3::WifiPpdu::SetPhyHeaders().
IsStbc()
bool ns3::WifiTxVector::IsStbc (void) const
Check if STBC is used or not.
Returns
true if STBC is used, false otherwise
Definition at line 195 of file wifi-tx-vector.cc.
References m_stbc.
Referenced by ns3::WifiPhy::GetPayloadDuration(), ns3::WifiPhyHelper::GetRadiotapHeader(), and ns3::operator<<().
IsValid()
bool ns3::WifiTxVector::IsValid (void) const
The standard disallows certain combinations of WifiMode, number of spatial streams, and channel widths.
This method can be used to check whether this WifiTxVector contains an invalid combination.
Returns
true if the WifiTxVector parameters are allowed by the standard
Definition at line 303 of file wifi-tx-vector.cc.
References GetModeInitialized(), ns3::WifiMode::GetUniqueName(), m_channelWidth, m_mode, and m_nss.
Referenced by ns3::IdealWifiManager::DoGetDataTxVector(), ns3::MinstrelHtWifiManager::IsValidMcs(), ns3::operator<<(), and ns3::WifiPpdu::SetPhyHeaders().
SetAggregation()
void ns3::WifiTxVector::SetAggregation (bool aggregation)
Sets if PSDU contains A-MPDU.
Parameters
aggregation whether the PSDU contains A-MPDU or not.
Definition at line 273 of file wifi-tx-vector.cc.
References m_aggregation.
Referenced by ns3::MacLow::ForwardDown(), and ns3::WifiPpdu::GetTxVector().
SetBssColor()
void ns3::WifiTxVector::SetBssColor (uint8_t color)
Set the BSS color.
Parameters
color the BSS color
Definition at line 291 of file wifi-tx-vector.cc.
References m_bssColor.
Referenced by ns3::WifiRemoteStationManager::GetDataTxVector(), and ns3::WifiPpdu::GetTxVector().
SetChannelWidth()
void ns3::WifiTxVector::SetChannelWidth (uint16_t channelWidth)
Sets the selected channelWidth (in MHz)
Parameters
channelWidth the channel width (in MHz)
Definition at line 235 of file wifi-tx-vector.cc.
References m_channelWidth.
Referenced by ns3::IdealWifiManager::BuildSnrThresholds(), ns3::MinstrelHtWifiManager::CalculateMpduTxDuration(), TxDurationTest::CheckHeMuTxDuration(), TxDurationTest::CheckPayloadDuration(), TxDurationTest::CheckTxDuration(), ns3::IdealWifiManager::DoGetDataTxVector(), ns3::IdealWifiManager::DoGetRtsTxVector(), WifiErrorRateModelsTestCaseMimo::DoRun(), ns3::VsaManager::DoSendVsa(), ns3::MacLow::GetAckTxVector(), ns3::MacLow::GetBlockAckTxVector(), ns3::MacLow::GetCtsTxVector(), ns3::WifiRemoteStationManager::GetDataTxVector(), ns3::WaveMacLow::GetDataTxVector(), ns3::WifiRemoteStationManager::GetRtsTxVector(), ns3::WifiPpdu::GetTxVector(), ns3::MinstrelHtWifiManager::IsValidMcs(), InterferenceExperiment::SendA(), InterferenceExperiment::SendB(), ns3::WaveNetDevice::SendX(), and NodeStatistics::SetupPhy().
SetGuardInterval()
void ns3::WifiTxVector::SetGuardInterval (uint16_t guardInterval)
Sets the guard interval duration (in nanoseconds)
Parameters
guardInterval the guard interval duration (in nanoseconds)
Definition at line 241 of file wifi-tx-vector.cc.
References m_guardInterval.
Referenced by ns3::IdealWifiManager::BuildSnrThresholds(), ns3::MinstrelHtWifiManager::CalculateMpduTxDuration(), TxDurationTest::CheckHeMuTxDuration(), TxDurationTest::CheckPayloadDuration(), TxDurationTest::CheckTxDuration(), ns3::IdealWifiManager::DoGetDataTxVector(), ns3::MacLow::GetAckTxVector(), ns3::MacLow::GetBlockAckTxVector(), ns3::MacLow::GetCtsTxVector(), ns3::WifiRemoteStationManager::GetDataTxVector(), ns3::WifiRemoteStationManager::GetRtsTxVector(), and ns3::WifiPpdu::GetTxVector().
SetHeMuUserInfo()
void ns3::WifiTxVector::SetHeMuUserInfo (uint16_t staId, HeMuUserInfo userInfo)
Set the HE MU user-specific transmission information for the given STA-ID.
This is applicable only for HE MU.
Parameters
staId the station ID
userInfo the HE MU user-specific transmission information
Definition at line 362 of file wifi-tx-vector.cc.
References ns3::WifiMode::GetModulationClass(), m_modeInitialized, m_muUserInfos, m_preamble, ns3::HeMuUserInfo::mcs, NS_ABORT_MSG_IF, ns3::WIFI_MOD_CLASS_HE, and ns3::WIFI_PREAMBLE_HE_MU.
Referenced by TxDurationTest::CheckHeMuTxDuration(), and ns3::WifiPpdu::GetTxVector().
SetLdpc()
void ns3::WifiTxVector::SetLdpc (bool ldpc)
Sets if LDPC FEC coding is being used.
Parameters
ldpc enable or disable LDPC
Definition at line 285 of file wifi-tx-vector.cc.
References m_ldpc.
Referenced by ns3::WifiRemoteStationManager::GetDataTxVector(), and ns3::WifiPpdu::GetTxVector().
SetMode() [1/2]
void ns3::WifiTxVector::SetMode (WifiMode mode)
Sets the selected payload transmission mode.
Parameters
mode the payload WifiMode
Definition at line 207 of file wifi-tx-vector.cc.
References m_mode, and m_modeInitialized.
Referenced by ns3::IdealWifiManager::BuildSnrThresholds(), ns3::dot11s::AirtimeLinkMetricCalculator::CalculateMetric(), ns3::MinstrelHtWifiManager::CalculateMpduTxDuration(), TxDurationTest::CheckPayloadDuration(), TxDurationTest::CheckTxDuration(), ns3::IdealWifiManager::DoGetDataTxVector(), ns3::IdealWifiManager::DoGetRtsTxVector(), WifiErrorRateModelsTestCaseMimo::DoRun(), TableBasedErrorRateTestCase::DoRun(), ns3::VsaManager::DoSendVsa(), ns3::MacLow::GetAckTxVector(), ns3::MacLow::GetBlockAckTxVector(), ns3::MacLow::GetCtsTxVector(), ns3::WifiRemoteStationManager::GetDataTxVector(), ns3::WaveMacLow::GetDataTxVector(), ns3::WifiRemoteStationManager::GetRtsTxVector(), ns3::WifiPpdu::GetTxVector(), ns3::MinstrelHtWifiManager::IsValidMcs(), ns3::WaveNetDevice::Send(), PsrExperiment::Send(), CollisionExperiment::SendA(), InterferenceExperiment::SendA(), CollisionExperiment::SendB(), InterferenceExperiment::SendB(), TestDlOfdmaPhyTransmission::SendMuPpdu(), ns3::WaveNetDevice::SendX(), ns3::MinstrelWifiManager::SetupPhy(), ns3::RraaWifiManager::SetupPhy(), ns3::RrpaaWifiManager::SetupPhy(), and NodeStatistics::SetupPhy().
SetMode() [2/2]
void ns3::WifiTxVector::SetMode (WifiMode mode, uint16_t staId)
Sets the selected payload transmission mode for a given STA ID (for HE MU only)
Parameters
mode
staId the station ID for HE MU
Definition at line 214 of file wifi-tx-vector.cc.
References m_modeInitialized, m_muUserInfos, m_preamble, NS_ABORT_MSG_IF, and ns3::WIFI_PREAMBLE_HE_MU.
SetNess()
void ns3::WifiTxVector::SetNess (uint8_t ness)
Sets the Ness number.
Parameters
ness the number of extended spatial streams
Definition at line 267 of file wifi-tx-vector.cc.
References m_ness.
Referenced by ns3::MinstrelHtWifiManager::CalculateMpduTxDuration(), TxDurationTest::CheckHeMuTxDuration(), TxDurationTest::CheckPayloadDuration(), TxDurationTest::CheckTxDuration(), ns3::WifiRemoteStationManager::GetDataTxVector(), and ns3::WifiRemoteStationManager::GetRtsTxVector().
SetNss() [1/2]
void ns3::WifiTxVector::SetNss (uint8_t nss)
Sets the number of Nss.
Parameters
nss the number of spatial streams
Definition at line 253 of file wifi-tx-vector.cc.
References m_nss.
Referenced by ns3::IdealWifiManager::BuildSnrThresholds(), ns3::MinstrelHtWifiManager::CalculateMpduTxDuration(), TxDurationTest::CheckPayloadDuration(), TxDurationTest::CheckTxDuration(), ns3::IdealWifiManager::DoGetDataTxVector(), ns3::IdealWifiManager::DoGetRtsTxVector(), WifiErrorRateModelsTestCaseMimo::DoRun(), ns3::MacLow::GetAckTxVector(), ns3::MacLow::GetBlockAckTxVector(), ns3::MacLow::GetCtsTxVector(), ns3::WifiRemoteStationManager::GetDataTxVector(), ns3::WifiRemoteStationManager::GetRtsTxVector(), ns3::WifiPpdu::GetTxVector(), ns3::MinstrelHtWifiManager::IsValidMcs(), and TestDlOfdmaPhyTransmission::SendMuPpdu().
SetNss() [2/2]
void ns3::WifiTxVector::SetNss (uint8_t nss, uint16_t staId)
Sets the number of Nss for HE MU.
Parameters
nss the number of spatial streams
staId the station ID for HE MU
Definition at line 259 of file wifi-tx-vector.cc.
References m_muUserInfos, m_preamble, NS_ABORT_MSG_IF, and ns3::WIFI_PREAMBLE_HE_MU.
SetNTx()
void ns3::WifiTxVector::SetNTx (uint8_t nTx)
Sets the number of TX antennas.
Parameters
nTx the number of TX antennas
Definition at line 247 of file wifi-tx-vector.cc.
References m_nTx.
Referenced by WifiErrorRateModelsTestCaseMimo::DoRun(), ns3::WifiRemoteStationManager::GetDataTxVector(), and ns3::WifiRemoteStationManager::GetRtsTxVector().
SetPreambleType()
void ns3::WifiTxVector::SetPreambleType (WifiPreamble preamble)
Sets the preamble type.
Parameters
preamble the preamble type
Definition at line 229 of file wifi-tx-vector.cc.
References m_preamble.
Referenced by ns3::dot11s::AirtimeLinkMetricCalculator::CalculateMetric(), ns3::MinstrelHtWifiManager::CalculateMpduTxDuration(), TxDurationTest::CheckHeMuTxDuration(), TxDurationTest::CheckPayloadDuration(), TxDurationTest::CheckTxDuration(), ns3::VsaManager::DoSendVsa(), ns3::MacLow::GetAckTxVector(), ns3::MacLow::GetBlockAckTxVector(), ns3::MacLow::GetCtsTxVector(), ns3::WifiRemoteStationManager::GetDataTxVector(), ns3::WaveMacLow::GetDataTxVector(), ns3::WifiRemoteStationManager::GetRtsTxVector(), ns3::WifiPpdu::GetTxVector(), ns3::WaveNetDevice::Send(), PsrExperiment::Send(), CollisionExperiment::SendA(), InterferenceExperiment::SendA(), CollisionExperiment::SendB(), InterferenceExperiment::SendB(), ns3::WaveNetDevice::SendX(), ns3::MinstrelWifiManager::SetupPhy(), ns3::RraaWifiManager::SetupPhy(), ns3::RrpaaWifiManager::SetupPhy(), and NodeStatistics::SetupPhy().
SetRu()
void ns3::WifiTxVector::SetRu (HeRu::RuSpec ru, uint16_t staId)
Set the RU specification for the STA-ID.
This is applicable only for HE MU.
Parameters
ru the RU specification
staId the station ID
Definition at line 347 of file wifi-tx-vector.cc.
References m_muUserInfos, m_preamble, NS_ABORT_MSG_IF, and ns3::WIFI_PREAMBLE_HE_MU.
Referenced by TestDlOfdmaPhyTransmission::SendMuPpdu().
SetStbc()
void ns3::WifiTxVector::SetStbc (bool stbc)
Sets if STBC is being used.
Parameters
stbc enable or disable STBC
Definition at line 279 of file wifi-tx-vector.cc.
References m_stbc.
Referenced by ns3::MinstrelHtWifiManager::CalculateMpduTxDuration(), TxDurationTest::CheckHeMuTxDuration(), TxDurationTest::CheckPayloadDuration(), and TxDurationTest::CheckTxDuration().
SetTxPowerLevel()
void ns3::WifiTxVector::SetTxPowerLevel (uint8_t powerlevel)
Sets the selected transmission power level.
Parameters
powerlevel the transmission power level
Definition at line 223 of file wifi-tx-vector.cc.
References m_txPowerLevel.
Referenced by WifiErrorRateModelsTestCaseMimo::DoRun(), ns3::VsaManager::DoSendVsa(), ns3::MacLow::GetAckTxVector(), ns3::MacLow::GetBlockAckTxVector(), ns3::MacLow::GetCtsTxVector(), ns3::WifiRemoteStationManager::GetDataTxVector(), ns3::WaveMacLow::GetDataTxVector(), ns3::WifiRemoteStationManager::GetRtsTxVector(), ns3::WifiPpdu::GetTxVector(), ns3::WaveNetDevice::Send(), PsrExperiment::Send(), CollisionExperiment::SendA(), InterferenceExperiment::SendA(), CollisionExperiment::SendB(), InterferenceExperiment::SendB(), and ns3::WaveNetDevice::SendX().
Member Data Documentation
m_aggregation
bool ns3::WifiTxVector::m_aggregation private
Flag whether the PSDU contains A-MPDU.
Definition at line 337 of file wifi-tx-vector.h.
Referenced by IsAggregation(), and SetAggregation().
m_bssColor
uint8_t ns3::WifiTxVector::m_bssColor private
BSS color.
Definition at line 340 of file wifi-tx-vector.h.
Referenced by GetBssColor(), and SetBssColor().
m_channelWidth
uint16_t ns3::WifiTxVector::m_channelWidth private
channel width in MHz
Definition at line 332 of file wifi-tx-vector.h.
Referenced by GetChannelWidth(), IsValid(), and SetChannelWidth().
m_guardInterval
uint16_t ns3::WifiTxVector::m_guardInterval private
guard interval duration in nanoseconds
Definition at line 333 of file wifi-tx-vector.h.
Referenced by GetGuardInterval(), and SetGuardInterval().
m_ldpc
bool ns3::WifiTxVector::m_ldpc private
LDPC FEC coding if true, BCC otherwise.
Definition at line 339 of file wifi-tx-vector.h.
Referenced by IsLdpc(), and SetLdpc().
m_mode
WifiMode ns3::WifiTxVector::m_mode private
The DATARATE parameter in Table 15-4.
It is the value that will be passed to PMD_RATE.request
Definition at line 325 of file wifi-tx-vector.h.
Referenced by GetMode(), IsValid(), and SetMode().
m_modeInitialized
bool ns3::WifiTxVector::m_modeInitialized private
Internal initialization flag.
Definition at line 342 of file wifi-tx-vector.h.
Referenced by GetMode(), GetModeInitialized(), SetHeMuUserInfo(), and SetMode().
m_muUserInfos
HeMuUserInfoMap ns3::WifiTxVector::m_muUserInfos private
HE MU specific per-user information indexed by station ID (STA-ID) corresponding to the 11 LSBs of the AID of the recipient STA This list shall be used only for HE MU.
Definition at line 345 of file wifi-tx-vector.h.
Referenced by WifiTxVector(), ~WifiTxVector(), GetHeMuUserInfo(), GetHeMuUserInfoMap(), GetMode(), GetNss(), GetNssMax(), GetRu(), SetHeMuUserInfo(), SetMode(), SetNss(), and SetRu().
m_ness
uint8_t ns3::WifiTxVector::m_ness private
number of spatial streams in beamforming
Definition at line 336 of file wifi-tx-vector.h.
Referenced by GetNess(), and SetNess().
m_nss
uint8_t ns3::WifiTxVector::m_nss private
number of spatial streams
Definition at line 335 of file wifi-tx-vector.h.
Referenced by GetNss(), GetNssMax(), IsValid(), and SetNss().
m_nTx
uint8_t ns3::WifiTxVector::m_nTx private
number of TX antennas
Definition at line 334 of file wifi-tx-vector.h.
Referenced by GetNTx(), and SetNTx().
m_preamble
WifiPreamble ns3::WifiTxVector::m_preamble private
preamble
Definition at line 331 of file wifi-tx-vector.h.
Referenced by GetHeMuUserInfo(), GetHeMuUserInfoMap(), GetMode(), GetNss(), GetNssMax(), GetPreambleType(), GetRu(), SetHeMuUserInfo(), SetMode(), SetNss(), SetPreambleType(), and SetRu().
m_stbc
bool ns3::WifiTxVector::m_stbc private
STBC used or not.
Definition at line 338 of file wifi-tx-vector.h.
Referenced by IsStbc(), and SetStbc().
m_txPowerLevel
uint8_t ns3::WifiTxVector::m_txPowerLevel private
The TXPWR_LEVEL parameter in Table 15-4.
It is the value that will be passed to PMD_TXPWRLVL.request
Definition at line 328 of file wifi-tx-vector.h.
Referenced by GetTxPowerLevel(), and SetTxPowerLevel().
The documentation for this class was generated from the following files:
src/wifi/model/wifi-tx-vector.h
src/wifi/model/wifi-tx-vector.cc