ns-3: ns3::PacketSinkHelper Class Reference
ns3::PacketSinkHelper Class Reference
Applications » PacketSink
A helper to make it easier to instantiate an ns3::PacketSinkApplication on a set of nodes.
#include "packet-sink-helper.h"
Public Member Functions
PacketSinkHelper (std::string protocol, Address address)
Create a PacketSinkHelper to make it easier to work with PacketSinkApplications.
ApplicationContainer Install (NodeContainer c) const
Install an ns3::PacketSinkApplication on each node of the input container configured with all the attributes set with SetAttribute.
ApplicationContainer Install (Ptr< Node > node) const
Install an ns3::PacketSinkApplication on each node of the input container configured with all the attributes set with SetAttribute.
ApplicationContainer Install (std::string nodeName) const
Install an ns3::PacketSinkApplication on each node of the input container configured with all the attributes set with SetAttribute.
void SetAttribute (std::string name, const AttributeValue &value)
Helper function used to set the underlying application attributes.
Private Member Functions
Ptr< Application > InstallPriv (Ptr< Node > node) const
Install an ns3::PacketSink on the node configured with all the attributes set with SetAttribute.
Private Attributes
ObjectFactory m_factory
Object factory.
Detailed Description
A helper to make it easier to instantiate an ns3::PacketSinkApplication on a set of nodes.
Definition at line 35 of file packet-sink-helper.h.
Constructor & Destructor Documentation
PacketSinkHelper()
ns3::PacketSinkHelper::PacketSinkHelper (std::string protocol, Address address)
Create a PacketSinkHelper to make it easier to work with PacketSinkApplications.
Parameters
protocol the name of the protocol to use to receive traffic This string identifies the socket factory type used to create sockets for the applications. A typical value would be ns3::TcpSocketFactory.
address the address of the sink,
Definition at line 28 of file packet-sink-helper.cc.
References first::address, m_factory, ns3::ObjectFactory::Set(), and ns3::ObjectFactory::SetTypeId().
Member Function Documentation
Install() [1/3]
ApplicationContainer ns3::PacketSinkHelper::Install (NodeContainer c) const
Install an ns3::PacketSinkApplication on each node of the input container configured with all the attributes set with SetAttribute.
Parameters
c NodeContainer of the set of nodes on which a PacketSinkApplication will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 55 of file packet-sink-helper.cc.
References ns3::ApplicationContainer::Add(), ns3::NodeContainer::Begin(), ns3::NodeContainer::End(), and InstallPriv().
Referenced by BuildAppsTest(), LteRadioLinkFailureTestCase::DoRun(), BulkSendBasicTestCase::DoRun(), BulkSendSeqTsSizeTestCase::DoRun(), BriteTopologyFunctionTestCase::DoRun(), EpcS1uDlTestCase::DoRun(), EpcS1uUlTestCase::DoRun(), LenaCqaFfMacSchedulerTestCase1::DoRun(), LenaCqaFfMacSchedulerTestCase2::DoRun(), ns3::LenaDeactivateBearerTestCase::DoRun(), LenaFdTbfqFfMacSchedulerTestCase1::DoRun(), LenaFdTbfqFfMacSchedulerTestCase2::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LenaPssFfMacSchedulerTestCase1::DoRun(), LenaPssFfMacSchedulerTestCase2::DoRun(), LenaTdTbfqFfMacSchedulerTestCase1::DoRun(), LenaTdTbfqFfMacSchedulerTestCase2::DoRun(), LteEpcE2eDataTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), LteX2HandoverTestCase::DoRun(), CsmaStarTestCase::DoRun(), Ns3TcpCwndTestCase1::DoRun(), Ns3TcpInteroperabilityTestCase::DoRun(), WifiAcMappingTest::DoRun(), WifiMsduAggregatorThroughputTest::DoRun(), experiment(), and Experiment::Run().
Install() [2/3]
ApplicationContainer ns3::PacketSinkHelper::Install (Ptr< Node > node) const
Install an ns3::PacketSinkApplication on each node of the input container configured with all the attributes set with SetAttribute.
Parameters
node The node on which a PacketSinkApplication will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 42 of file packet-sink-helper.cc.
References InstallPriv().
Install() [3/3]
ApplicationContainer ns3::PacketSinkHelper::Install (std::string nodeName) const
Install an ns3::PacketSinkApplication on each node of the input container configured with all the attributes set with SetAttribute.
Parameters
nodeName The name of the node on which a PacketSinkApplication will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 48 of file packet-sink-helper.cc.
References InstallPriv().
InstallPriv()
Ptr< Application > ns3::PacketSinkHelper::InstallPriv (Ptr< Node > node) const private
Install an ns3::PacketSink on the node configured with all the attributes set with SetAttribute.
Parameters
node The node on which an PacketSink will be installed.
Returns
Ptr to the application installed.
Definition at line 67 of file packet-sink-helper.cc.
References ns3::Node::AddApplication(), ns3::ObjectFactory::Create(), and m_factory.
Referenced by Install().
SetAttribute()
void ns3::PacketSinkHelper::SetAttribute (std::string name, const AttributeValue & value)
Helper function used to set the underlying application attributes.
Parameters
name the name of the application attribute to set
value the value of the application attribute to set
Definition at line 36 of file packet-sink-helper.cc.
References m_factory, and ns3::ObjectFactory::Set().
Referenced by BulkSendSeqTsSizeTestCase::DoRun(), and experiment().
Member Data Documentation
m_factory
ObjectFactory ns3::PacketSinkHelper::m_factory private
Object factory.
Definition at line 95 of file packet-sink-helper.h.
Referenced by PacketSinkHelper(), InstallPriv(), and SetAttribute().
The documentation for this class was generated from the following files:
src/applications/helper/packet-sink-helper.h
src/applications/helper/packet-sink-helper.cc