ns-3: ns3::TbfQueueDisc Class Reference
ns3::TbfQueueDisc Class Reference
Traffic-control
A TBF packet queue disc.
#include "tbf-queue-disc.h"
Public Member Functions
TbfQueueDisc ()
TbfQueueDisc Constructor.
virtual ~TbfQueueDisc ()
Destructor.
uint32_t GetBurst (void) const
Get the size of the first bucket in bytes.
uint32_t GetFirstBucketTokens (void) const
Get the current number of tokens inside the first bucket in bytes.
uint32_t GetMtu (void) const
Get the size of the second bucket in bytes.
DataRate GetPeakRate (void) const
Get the rate of the tokens entering the second bucket.
DataRate GetRate (void) const
Get the rate of the tokens entering the first bucket.
uint32_t GetSecondBucketTokens (void) const
Get the current number of tokens inside the second bucket in bytes.
void SetBurst (uint32_t burst)
Set the size of the first bucket in bytes.
void SetMtu (uint32_t mtu)
Set the size of the second bucket in bytes.
void SetPeakRate (DataRate peakRate)
Set the rate of the tokens entering the second bucket.
void SetRate (DataRate rate)
Set the rate of the tokens entering the first bucket.
Public Member Functions inherited from ns3::QueueDisc
QueueDisc (QueueDiscSizePolicy policy, QueueSizeUnit unit)
Constructor.
QueueDisc (QueueDiscSizePolicy policy=QueueDiscSizePolicy::SINGLE_INTERNAL_QUEUE)
Constructor.
virtual ~QueueDisc ()
void AddInternalQueue (Ptr< InternalQueue > queue)
Add an internal queue to the tail of the list of queues.
void AddPacketFilter (Ptr< PacketFilter > filter)
Add a packet filter to the tail of the list of filters used to classify packets.
void AddQueueDiscClass (Ptr< QueueDiscClass > qdClass)
Add a queue disc class to the tail of the list of classes.
int32_t Classify (Ptr< QueueDiscItem > item)
Classify a packet by calling the packet filters, one at a time, until either a filter able to classify the packet is found or all the filters have been processed.
Ptr< QueueDiscItem > Dequeue (void)
Extract from the queue disc the packet that has been dequeued by calling Peek, if any, or call the private DoDequeue method (which must be implemented by derived classes) to dequeue a packet, otherwise.
bool Enqueue (Ptr< QueueDiscItem > item)
Pass a packet to store to the queue discipline.
QueueSize GetCurrentSize (void)
Get the current size of the queue disc in bytes, if operating in bytes mode, or packets, otherwise.
Ptr< InternalQueue > GetInternalQueue (std::size_t i) const
Get the i-th internal queue.
QueueSize GetMaxSize (void) const
Get the maximum size of the queue disc.
uint32_t GetNBytes (void) const
Get the amount of bytes stored by the queue disc.
Ptr< NetDeviceQueueInterface > GetNetDeviceQueueInterface (void) const
std::size_t GetNInternalQueues (void) const
Get the number of internal queues.
std::size_t GetNPacketFilters (void) const
Get the number of packet filters.
uint32_t GetNPackets (void) const
Get the number of packets stored by the queue disc.
std::size_t GetNQueueDiscClasses (void) const
Get the number of queue disc classes.
Ptr< PacketFilter > GetPacketFilter (std::size_t i) const
Get the i-th packet filter.
Ptr< QueueDiscClass > GetQueueDiscClass (std::size_t i) const
Get the i-th queue disc class.
virtual uint32_t GetQuota (void) const
Get the maximum number of dequeue operations following a packet enqueue.
SendCallback GetSendCallback (void) const
const Stats & GetStats (void)
Retrieve all the collected statistics.
virtual WakeMode GetWakeMode (void) const
When setting up the wake callbacks on the netdevice queues, it is necessary to determine which queue disc (the root queue disc or one of its children) should be activated when the netdevice wakes one of its transmission queues.
Ptr< const QueueDiscItem > Peek (void)
Get a copy of the next packet the queue discipline will extract.
void Run (void)
Modelled after the Linux function __qdisc_run (net/sched/sch_generic.c) Dequeues multiple packets, until a quota is exceeded or sending a packet to the device failed.
bool SetMaxSize (QueueSize size)
Set the maximum size of the queue disc.
void SetNetDeviceQueueInterface (Ptr< NetDeviceQueueInterface > ndqi)
virtual void SetQuota (const uint32_t quota)
Set the maximum number of dequeue operations following a packet enqueue.
void SetSendCallback (SendCallback func)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::QueueDisc
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Dispose of the object.
Protected Member Functions inherited from ns3::QueueDisc
void DoInitialize (void)
Check whether the configuration is correct and initialize parameters.
void DropAfterDequeue (Ptr< const QueueDiscItem > item, const char *reason)
Perform the actions required when the queue disc is notified of a packet dropped after dequeue.
void DropBeforeEnqueue (Ptr< const QueueDiscItem > item, const char *reason)
Perform the actions required when the queue disc is notified of a packet dropped before enqueue.
bool Mark (Ptr< QueueDiscItem > item, const char *reason)
Marks the given packet and, if successful, updates the counters associated with the given reason.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
virtual bool CheckConfig (void)
Check whether the current configuration is correct.
virtual Ptr< QueueDiscItem > DoDequeue (void)
This function actually extracts a packet from the queue disc.
virtual bool DoEnqueue (Ptr< QueueDiscItem > item)
This function actually enqueues a packet into the queue disc.
virtual void InitializeParams (void)
Initialize parameters (if any) before the first packet is enqueued.
Private Attributes
TracedValue< uint32_t > m_btokens
Current number of tokens in first bucket.
uint32_t m_burst
Size of first bucket in bytes.
EventId m_id
EventId of the scheduled queue waking event when enough tokens are available.
uint32_t m_mtu
Size of second bucket in bytes.
DataRate m_peakRate
Rate at which tokens enter the second bucket.
TracedValue< uint32_t > m_ptokens
Current number of tokens in second bucket.
DataRate m_rate
Rate at which tokens enter the first bucket.
Time m_timeCheckPoint
Time check-point.
Additional Inherited Members
Public Types inherited from ns3::QueueDisc
typedef Queue< QueueDiscItem > InternalQueue
Internal queues store QueueDiscItem objects.
typedef std::function< void(Ptr< QueueDiscItem >)> SendCallback
Callback invoked to send a packet to the receiving object when Run is called.
enum WakeMode { WAKE_ROOT = 0x00 , WAKE_CHILD = 0x01 }
Used to determine whether the queue disc itself or its children must be activated when a netdevice wakes a transmission queue.
Static Public Attributes inherited from ns3::QueueDisc
static constexpr const char * CHILD_QUEUE_DISC_DROP = "(Dropped by child queue disc) "
Packet dropped by a child queue disc.
static constexpr const char * CHILD_QUEUE_DISC_MARK = "(Marked by child queue disc) "
Packet marked by a child queue disc.
static constexpr const char * INTERNAL_QUEUE_DROP = "Dropped by internal queue"
Packet dropped by an internal queue.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A TBF packet queue disc.
Introspection did not find any typical Config paths.
Attributes
MaxSize: The max queue size
Set with class: QueueSizeValue
Underlying type: QueueSize
Initial value: 1000p
Flags: construct write read
Burst: Size of the first bucket in bytes
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 125000
Flags: construct write
Mtu: Size of the second bucket in bytes. If null, it is initialized to the MTU of the receiving NetDevice (if any)
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 0
Flags: construct write
Rate: Rate at which tokens enter the first bucket in bps or Bps.
Set with class: DataRateValue
Underlying type: DataRate
Initial value: 1000000bps
Flags: construct write
PeakRate: Rate at which tokens enter the second bucket in bps or Bps.If null, there is no second bucket
Set with class: DataRateValue
Underlying type: DataRate
Initial value: 0bps
Flags: construct write
Attributes defined in parent class ns3::QueueDisc
Quota: The maximum number of packets dequeued in a qdisc run
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 64
Flags: construct write read
InternalQueueList: The list of internal queues.
Set with class: ns3::ObjectPtrContainerValue
Underlying type: ns3::Ptr< ns3::Queue<QueueDiscItem>>
Flags: read
PacketFilterList: The list of packet filters.
Set with class: ns3::ObjectPtrContainerValue
Underlying type: ns3::Ptr< ns3::PacketFilter>
Flags: read
QueueDiscClassList: The list of queue disc classes.
Set with class: ns3::ObjectPtrContainerValue
Underlying type: ns3::Ptr< ns3::QueueDiscClass>
Flags: read
TraceSources
TokensInFirstBucket: Number of First Bucket Tokens in bytes
Callback signature: ns3::TracedValueCallback::Uint32
TokensInSecondBucket: Number of Second Bucket Tokens in bytes
Callback signature: ns3::TracedValueCallback::Uint32
TraceSources defined in parent class ns3::QueueDisc
Enqueue: Enqueue a packet in the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
Dequeue: Dequeue a packet from the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
Requeue: Requeue a packet in the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
Drop: Drop a packet stored in the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
DropBeforeEnqueue: Drop a packet before enqueue
Callback signature: ns3::QueueDiscItem::TracedCallback
DropAfterDequeue: Drop a packet after dequeue
Callback signature: ns3::QueueDiscItem::TracedCallback
Mark: Mark a packet stored in the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
PacketsInQueue: Number of packets currently stored in the queue disc
Callback signature: ns3::TracedValueCallback::Uint32
BytesInQueue: Number of bytes currently stored in the queue disc
Callback signature: ns3::TracedValueCallback::Uint32
SojournTime: Sojourn time of the last packet dequeued from the queue disc
Callback signature: ns3::Time::TracedCallback
Size of this type is 1168 bytes (on a 64-bit architecture).
Definition at line 48 of file tbf-queue-disc.h.
Constructor & Destructor Documentation
TbfQueueDisc()
ns3::TbfQueueDisc::TbfQueueDisc ()
TbfQueueDisc Constructor.
Create a TBF queue disc
Definition at line 93 of file tbf-queue-disc.cc.
References NS_LOG_FUNCTION.
~TbfQueueDisc()
ns3::TbfQueueDisc::~TbfQueueDisc () virtual
Destructor.
Destructor
Definition at line 99 of file tbf-queue-disc.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CheckConfig()
bool ns3::TbfQueueDisc::CheckConfig (void) private virtual
Check whether the current configuration is correct.
Default objects (such as internal queues) might be created by this method to ensure the configuration is correct. This method is automatically called at simulation initialization time, and it is called before the InitializeParams () method. It is appropriate to promote parameter initialization to this method if it aids in checking for correct configuration.
See also
QueueDisc::InitializeParams
Returns
true if the configuration is correct, false otherwise
Implements ns3::QueueDisc.
Definition at line 273 of file tbf-queue-disc.cc.
References ns3::QueueDisc::AddQueueDiscClass(), ns3::ObjectFactory::Create(), ns3::QueueDisc::GetMaxSize(), ns3::QueueDisc::GetNetDeviceQueueInterface(), ns3::QueueDisc::GetNInternalQueues(), ns3::QueueDisc::GetNPacketFilters(), ns3::QueueDisc::GetNQueueDiscClasses(), ns3::Object::Initialize(), m_burst, m_mtu, m_peakRate, m_rate, NS_LOG_ERROR, NS_LOG_FUNCTION, NS_LOG_WARN, ns3::QueueDisc::SetMaxSize(), and ns3::ObjectFactory::SetTypeId().
DoDequeue()
Ptr< QueueDiscItem > ns3::TbfQueueDisc::DoDequeue (void) private virtual
This function actually extracts a packet from the queue disc.
Returns
0 if the operation was not successful; the item otherwise.
Implements ns3::QueueDisc.
Definition at line 197 of file tbf-queue-disc.cc.
References ns3::DataRate::CalculateBytesTxTime(), ns3::DataRate::GetBitRate(), ns3::QueueDisc::GetNBytes(), ns3::QueueDisc::GetNPackets(), ns3::QueueDisc::GetQueueDiscClass(), ns3::EventId::IsExpired(), m_btokens, m_burst, m_id, m_mtu, m_peakRate, m_ptokens, m_rate, m_timeCheckPoint, max, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, pktSize, ns3::QueueDisc::Run(), and ns3::Simulator::Schedule().
DoDispose()
void ns3::TbfQueueDisc::DoDispose (void) protected virtual
Dispose of the object.
Reimplemented from ns3::QueueDisc.
Definition at line 105 of file tbf-queue-disc.cc.
References ns3::QueueDisc::DoDispose(), and NS_LOG_FUNCTION.
DoEnqueue()
bool ns3::TbfQueueDisc::DoEnqueue (Ptr< QueueDiscItem > item) private virtual
This function actually enqueues a packet into the queue disc.
Parameters
item item to enqueue
Returns
True if the operation was successful; false otherwise
Implements ns3::QueueDisc.
Definition at line 182 of file tbf-queue-disc.cc.
References ns3::QueueDisc::GetNBytes(), ns3::QueueDisc::GetNPackets(), ns3::QueueDisc::GetQueueDiscClass(), NS_LOG_FUNCTION, and NS_LOG_LOGIC.
GetBurst()
uint32_t ns3::TbfQueueDisc::GetBurst (void) const
Get the size of the first bucket in bytes.
Returns
The size of the first bucket in bytes.
Definition at line 119 of file tbf-queue-disc.cc.
References m_burst, and NS_LOG_FUNCTION.
GetFirstBucketTokens()
uint32_t ns3::TbfQueueDisc::GetFirstBucketTokens (void) const
Get the current number of tokens inside the first bucket in bytes.
Returns
The number of first bucket tokens in bytes.
Definition at line 168 of file tbf-queue-disc.cc.
References m_btokens, and NS_LOG_FUNCTION.
GetMtu()
uint32_t ns3::TbfQueueDisc::GetMtu (void) const
Get the size of the second bucket in bytes.
Returns
The size of the second bucket in bytes.
Definition at line 133 of file tbf-queue-disc.cc.
References m_mtu, and NS_LOG_FUNCTION.
GetPeakRate()
DataRate ns3::TbfQueueDisc::GetPeakRate (void) const
Get the rate of the tokens entering the second bucket.
Returns
The rate of second bucket tokens.
Definition at line 161 of file tbf-queue-disc.cc.
References m_peakRate, and NS_LOG_FUNCTION.
GetRate()
DataRate ns3::TbfQueueDisc::GetRate (void) const
Get the rate of the tokens entering the first bucket.
Returns
The rate of first bucket tokens.
Definition at line 147 of file tbf-queue-disc.cc.
References m_rate, and NS_LOG_FUNCTION.
GetSecondBucketTokens()
uint32_t ns3::TbfQueueDisc::GetSecondBucketTokens (void) const
Get the current number of tokens inside the second bucket in bytes.
Returns
The number of second bucket tokens in bytes.
Definition at line 175 of file tbf-queue-disc.cc.
References m_ptokens, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::TbfQueueDisc::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 46 of file tbf-queue-disc.cc.
References ns3::QueueDisc::GetMaxSize(), m_btokens, m_ptokens, ns3::MakeDataRateAccessor(), ns3::MakeDataRateChecker(), ns3::MakeQueueSizeAccessor(), ns3::MakeQueueSizeChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), SetBurst(), ns3::QueueDisc::SetMaxSize(), SetMtu(), ns3::TypeId::SetParent(), SetPeakRate(), and SetRate().
InitializeParams()
void ns3::TbfQueueDisc::InitializeParams (void) private virtual
Initialize parameters (if any) before the first packet is enqueued.
This method is automatically called at simulation initialization time, after the CheckConfig() method has been called.
See also
QueueDisc::CheckConfig
Implements ns3::QueueDisc.
Definition at line 350 of file tbf-queue-disc.cc.
References m_btokens, m_burst, m_id, m_mtu, m_ptokens, m_timeCheckPoint, NS_LOG_FUNCTION, and ns3::Seconds().
SetBurst()
void ns3::TbfQueueDisc::SetBurst (uint32_t burst)
Set the size of the first bucket in bytes.
Parameters
burst The size of first bucket in bytes.
Definition at line 112 of file tbf-queue-disc.cc.
References m_burst, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetMtu()
void ns3::TbfQueueDisc::SetMtu (uint32_t mtu)
Set the size of the second bucket in bytes.
Parameters
mtu The size of second bucket in bytes.
Definition at line 126 of file tbf-queue-disc.cc.
References m_mtu, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetPeakRate()
void ns3::TbfQueueDisc::SetPeakRate (DataRate peakRate)
Set the rate of the tokens entering the second bucket.
Parameters
peakRate The rate of second bucket tokens.
Definition at line 154 of file tbf-queue-disc.cc.
References m_peakRate, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetRate()
void ns3::TbfQueueDisc::SetRate (DataRate rate)
Set the rate of the tokens entering the first bucket.
Parameters
rate The rate of first bucket tokens.
Definition at line 140 of file tbf-queue-disc.cc.
References m_rate, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
Member Data Documentation
m_btokens
TracedValue<uint32_t> ns3::TbfQueueDisc::m_btokens private
Current number of tokens in first bucket.
Definition at line 162 of file tbf-queue-disc.h.
Referenced by DoDequeue(), GetFirstBucketTokens(), GetTypeId(), and InitializeParams().
m_burst
uint32_t ns3::TbfQueueDisc::m_burst private
Size of first bucket in bytes.
Definition at line 156 of file tbf-queue-disc.h.
Referenced by CheckConfig(), DoDequeue(), GetBurst(), InitializeParams(), and SetBurst().
m_id
EventId ns3::TbfQueueDisc::m_id private
EventId of the scheduled queue waking event when enough tokens are available.
Definition at line 165 of file tbf-queue-disc.h.
Referenced by DoDequeue(), and InitializeParams().
m_mtu
uint32_t ns3::TbfQueueDisc::m_mtu private
Size of second bucket in bytes.
Definition at line 157 of file tbf-queue-disc.h.
Referenced by CheckConfig(), DoDequeue(), GetMtu(), InitializeParams(), and SetMtu().
m_peakRate
DataRate ns3::TbfQueueDisc::m_peakRate private
Rate at which tokens enter the second bucket.
Definition at line 159 of file tbf-queue-disc.h.
Referenced by CheckConfig(), DoDequeue(), GetPeakRate(), and SetPeakRate().
m_ptokens
TracedValue<uint32_t> ns3::TbfQueueDisc::m_ptokens private
Current number of tokens in second bucket.
Definition at line 163 of file tbf-queue-disc.h.
Referenced by DoDequeue(), GetSecondBucketTokens(), GetTypeId(), and InitializeParams().
m_rate
DataRate ns3::TbfQueueDisc::m_rate private
Rate at which tokens enter the first bucket.
Definition at line 158 of file tbf-queue-disc.h.
Referenced by CheckConfig(), DoDequeue(), GetRate(), and SetRate().
m_timeCheckPoint
Time ns3::TbfQueueDisc::m_timeCheckPoint private
Time check-point.
Definition at line 164 of file tbf-queue-disc.h.
Referenced by DoDequeue(), and InitializeParams().
The documentation for this class was generated from the following files:
src/traffic-control/model/tbf-queue-disc.h
src/traffic-control/model/tbf-queue-disc.cc