ns-3: ns3::SinkTracer Class Reference
ns3::SinkTracer Class Reference
#include "mpi-test-fixtures.h"
Static Public Member Functions
static std::string FormatAddress (const ns3::Address address)
Get the source address and port, as a formatted string.
static int GetLineCount (void)
Get current line count and increment.
static int GetWorldRank (void)
Get the MPI rank in the world communicator.
static int GetWorldSize (void)
Get the MPI size of the world communicator.
static void Init (void)
PacketSink receive trace callback.
static void SinkTrace (const ns3::Ptr< const ns3::Packet > packet, const ns3::Address &srcAddress, const ns3::Address &destAddress)
PacketSink receive trace callback.
static void Verify (unsigned long expectedCount)
Verify the sink trace count observed matches the expected count.
Static Private Attributes
static unsigned long m_line = 0
static unsigned long m_sinkCount = 0
static int m_worldRank = -1
static int m_worldSize = -1
Detailed Description
Definition at line 75 of file mpi-test-fixtures.h.
Member Function Documentation
FormatAddress()
std::string ns3::SinkTracer::FormatAddress (const ns3::Address address) static
Get the source address and port, as a formatted string.
Parameters
[in] address The ns3::Address.
Returns
A string with the formatted address and port number.
Definition at line 80 of file mpi-test-fixtures.cc.
References first::address, ns3::Inet6SocketAddress::ConvertFrom(), ns3::InetSocketAddress::ConvertFrom(), ns3::InetSocketAddress::GetIpv4(), ns3::Inet6SocketAddress::GetIpv6(), ns3::InetSocketAddress::GetPort(), ns3::Inet6SocketAddress::GetPort(), ns3::Inet6SocketAddress::IsMatchingType(), and ns3::InetSocketAddress::IsMatchingType().
GetLineCount()
static int ns3::SinkTracer::GetLineCount (void) inline static
Get current line count and increment.
Definition at line 131 of file mpi-test-fixtures.h.
References m_line.
GetWorldRank()
static int ns3::SinkTracer::GetWorldRank (void) inline static
Get the MPI rank in the world communicator.
Returns
MPI world rank.
Definition at line 112 of file mpi-test-fixtures.h.
References m_worldRank.
Referenced by ReportRank().
GetWorldSize()
static int ns3::SinkTracer::GetWorldSize (void) inline static
Get the MPI size of the world communicator.
Returns
MPI world size.
Definition at line 122 of file mpi-test-fixtures.h.
References m_worldSize.
Referenced by ReportRank().
Init()
void ns3::SinkTracer::Init (void) static
PacketSink receive trace callback.
Parameters
[in] packet The packet.
[in] srcAddress The source address.
[in] destAddress The destination address.
Definition at line 40 of file mpi-test-fixtures.cc.
References m_line, m_sinkCount, m_worldRank, and m_worldSize.
SinkTrace()
void ns3::SinkTracer::SinkTrace (const ns3::Ptr< const ns3::Packet > packet, const ns3::Address & srcAddress, const ns3::Address & destAddress) static
PacketSink receive trace callback.
Parameters
[in] packet The packet.
[in] srcAddress The source address.
[in] destAddress The destination address.
Definition at line 50 of file mpi-test-fixtures.cc.
References m_sinkCount.
Verify()
void ns3::SinkTracer::Verify (unsigned long expectedCount) static
Verify the sink trace count observed matches the expected count.
Prints message to std::cout indicating success or fail.
Definition at line 58 of file mpi-test-fixtures.cc.
References m_sinkCount, and RANK0COUT.
Member Data Documentation
m_line
unsigned long ns3::SinkTracer::m_line = 0 static private
Definition at line 138 of file mpi-test-fixtures.h.
Referenced by GetLineCount(), and Init().
m_sinkCount
unsigned long ns3::SinkTracer::m_sinkCount = 0 static private
Definition at line 137 of file mpi-test-fixtures.h.
Referenced by Init(), SinkTrace(), and Verify().
m_worldRank
int ns3::SinkTracer::m_worldRank = -1 static private
Definition at line 139 of file mpi-test-fixtures.h.
Referenced by GetWorldRank(), and Init().
m_worldSize
int ns3::SinkTracer::m_worldSize = -1 static private
Definition at line 140 of file mpi-test-fixtures.h.
Referenced by GetWorldSize(), and Init().
The documentation for this class was generated from the following files:
src/mpi/examples/mpi-test-fixtures.h
src/mpi/examples/mpi-test-fixtures.cc