ns-3: ns3::Ipv4Interface Class Reference
ns3::Ipv4Interface Class Reference
Internet » IPv4 classes and sub-modules
The IPv4 representation of a network interface.
#include "ipv4-interface.h"
Public Member Functions
Ipv4Interface ()
By default, Ipv4 interface are created in the "down" state with no IP addresses.
virtual ~Ipv4Interface ()
bool AddAddress (Ipv4InterfaceAddress address)
Ipv4InterfaceAddress GetAddress (uint32_t index) const
Ptr< ArpCache > GetArpCache () const
Ptr< NetDevice > GetDevice (void) const
uint16_t GetMetric (void) const
uint32_t GetNAddresses (void) const
bool IsDown (void) const
bool IsForwarding (void) const
bool IsUp (void) const
These are IP interface states and may be distinct from NetDevice states, such as found in real implementations (where the device may be down but IP interface state is still up).
Ipv4InterfaceAddress RemoveAddress (Ipv4Address address)
Remove the given Ipv4 address from the interface.
Ipv4InterfaceAddress RemoveAddress (uint32_t index)
void Send (Ptr< Packet > p, const Ipv4Header &hdr, Ipv4Address dest)
void SetArpCache (Ptr< ArpCache > arpCache)
Set ARP cache used by this interface.
void SetDevice (Ptr< NetDevice > device)
Set the NetDevice.
void SetDown (void)
Disable this interface.
void SetForwarding (bool val)
void SetMetric (uint16_t metric)
void SetNode (Ptr< Node > node)
Set node associated with interface.
void SetTrafficControl (Ptr< TrafficControlLayer > tc)
Set the TrafficControlLayer.
void SetUp (void)
Enable this interface.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
typedef std::list< Ipv4InterfaceAddress > Ipv4InterfaceAddressList
Container for the Ipv4InterfaceAddresses.
typedef std::list< Ipv4InterfaceAddress >::const_iterator Ipv4InterfaceAddressListCI
Container Iterator for the Ipv4InterfaceAddresses.
typedef std::list< Ipv4InterfaceAddress >::iterator Ipv4InterfaceAddressListI
Const Container Iterator for the Ipv4InterfaceAddresses.
Private Member Functions
Ipv4Interface (const Ipv4Interface &o)
Copy constructor.
void DoSetup (void)
Initialize interface.
Ipv4Interface & operator= (const Ipv4Interface &o)
Assignment operator.
Private Attributes
Ptr< ArpCache > m_cache
ARP cache.
Ptr< NetDevice > m_device
The associated NetDevice.
bool m_forwarding
Forwarding state.
Ipv4InterfaceAddressList m_ifaddrs
Address list.
bool m_ifup
The state of this interface.
uint16_t m_metric
Interface metric.
Ptr< Node > m_node
The associated node.
Ptr< TrafficControlLayer > m_tc
The associated TrafficControlLayer.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The IPv4 representation of a network interface.
This class roughly corresponds to the struct in_device of Linux; the main purpose is to provide address-family specific information (addresses) about an interface.
By default, Ipv4 interface are created in the "down" state no IP addresses. Before becoming usable, the user must add an address of some type and invoke Setup on them.
Config Paths
ns3::Ipv4Interface is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::Ipv4L3Protocol/InterfaceList/[i]"
Attributes
ArpCache: The arp cache for this ipv4 interface
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::ArpCache>
Initial value: 0x0
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 88 bytes (on a 64-bit architecture).
Definition at line 53 of file ipv4-interface.h.
Member Typedef Documentation
Ipv4InterfaceAddressList
typedef std::list<Ipv4InterfaceAddress> ns3::Ipv4Interface::Ipv4InterfaceAddressList private
Container for the Ipv4InterfaceAddresses.
Definition at line 220 of file ipv4-interface.h.
Ipv4InterfaceAddressListCI
typedef std::list<Ipv4InterfaceAddress>::const_iterator ns3::Ipv4Interface::Ipv4InterfaceAddressListCI private
Container Iterator for the Ipv4InterfaceAddresses.
Definition at line 225 of file ipv4-interface.h.
Ipv4InterfaceAddressListI
typedef std::list<Ipv4InterfaceAddress>::iterator ns3::Ipv4Interface::Ipv4InterfaceAddressListI private
Const Container Iterator for the Ipv4InterfaceAddresses.
Definition at line 230 of file ipv4-interface.h.
Constructor & Destructor Documentation
Ipv4Interface() [1/2]
ns3::Ipv4Interface::Ipv4Interface ()
By default, Ipv4 interface are created in the "down" state with no IP addresses.
Before becoming usable, the user must invoke SetUp on them once an Ipv4 address and mask have been set.
Definition at line 63 of file ipv4-interface.cc.
References NS_LOG_FUNCTION.
~Ipv4Interface()
ns3::Ipv4Interface::~Ipv4Interface () virtual
Definition at line 75 of file ipv4-interface.cc.
References NS_LOG_FUNCTION.
Ipv4Interface() [2/2]
ns3::Ipv4Interface::Ipv4Interface (const Ipv4Interface & o) private
Copy constructor.
Parameters
o object to copy
Defined and unimplemented to avoid misuse
Member Function Documentation
AddAddress()
bool ns3::Ipv4Interface::AddAddress (Ipv4InterfaceAddress address)
Parameters
address The Ipv4InterfaceAddress to add to the interface
Returns
true if succeeded
Definition at line 309 of file ipv4-interface.cc.
References m_ifaddrs, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4L3Protocol::AddAddress().
DoDispose()
void ns3::Ipv4Interface::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 81 of file ipv4-interface.cc.
References ns3::Object::DoDispose(), m_cache, m_device, m_node, m_tc, and NS_LOG_FUNCTION.
DoSetup()
void ns3::Ipv4Interface::DoSetup (void) private
Initialize interface.
Definition at line 115 of file ipv4-interface.cc.
References ns3::Object::GetObject(), m_cache, m_device, m_node, and NS_LOG_FUNCTION.
Referenced by SetDevice(), and SetNode().
GetAddress()
Ipv4InterfaceAddress ns3::Ipv4Interface::GetAddress (uint32_t index) const
Parameters
index Index of Ipv4InterfaceAddress to return
Returns
The Ipv4InterfaceAddress address whose index is i
Definition at line 317 of file ipv4-interface.cc.
References m_ifaddrs, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4L3Protocol::GetAddress(), ns3::Ipv4EndPointDemux::Lookup(), ns3::ArpL3Protocol::Receive(), and ns3::Ipv4L3Protocol::Send().
GetArpCache()
Ptr< ArpCache > ns3::Ipv4Interface::GetArpCache () const
Returns
ARP cache used by this interface
Definition at line 159 of file ipv4-interface.cc.
References m_cache, and NS_LOG_FUNCTION.
Referenced by GetTypeId(), and ns3::Ipv4L3Protocol::Receive().
GetDevice()
Ptr< NetDevice > ns3::Ipv4Interface::GetDevice (void) const
Returns
the underlying NetDevice. This method cannot return zero.
Definition at line 131 of file ipv4-interface.cc.
References m_device, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4L3Protocol::AddIpv4Interface(), ns3::Ipv4RawSocketImpl::ForwardUp(), ns3::UdpSocketImpl::ForwardUp(), ns3::Ipv4L3Protocol::GetMtu(), ns3::Ipv4L3Protocol::GetNetDevice(), ns3::Ipv4EndPointDemux::Lookup(), ns3::Ipv4L3Protocol::Send(), and ns3::Ipv4L3Protocol::SendRealOut().
GetMetric()
uint16_t ns3::Ipv4Interface::GetMetric (void) const
Returns
configured routing metric (cost) of this interface
Note: This is synonymous to the Metric value that ifconfig prints out. It is used by ns-3 global routing, but other routing daemons may choose to ignore it.
Definition at line 145 of file ipv4-interface.cc.
References m_metric, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4L3Protocol::GetMetric().
GetNAddresses()
uint32_t ns3::Ipv4Interface::GetNAddresses (void) const
Returns
the number of Ipv4InterfaceAddress stored on this interface
Definition at line 302 of file ipv4-interface.cc.
References m_ifaddrs, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4L3Protocol::GetNAddresses(), ns3::Ipv4EndPointDemux::Lookup(), and ns3::Ipv4L3Protocol::Send().
GetTypeId()
TypeId ns3::Ipv4Interface::GetTypeId (void) static
Get the type ID.
Returns
type ID
Definition at line 42 of file ipv4-interface.cc.
References GetArpCache(), ns3::MakePointerAccessor(), SetArpCache(), and ns3::TypeId::SetParent().
IsDown()
bool ns3::Ipv4Interface::IsDown (void) const
Returns
true if this interface is disabled, false otherwise.
Definition at line 178 of file ipv4-interface.cc.
References m_ifup, and NS_LOG_FUNCTION.
IsForwarding()
bool ns3::Ipv4Interface::IsForwarding (void) const
Returns
true if this interface is enabled for IP forwarding of input datagrams
Definition at line 199 of file ipv4-interface.cc.
References m_forwarding, and NS_LOG_FUNCTION.
IsUp()
bool ns3::Ipv4Interface::IsUp (void) const
These are IP interface states and may be distinct from NetDevice states, such as found in real implementations (where the device may be down but IP interface state is still up).
Returns
true if this interface is enabled, false otherwise.
Definition at line 171 of file ipv4-interface.cc.
References m_ifup, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4L3Protocol::IsUp(), ns3::Ipv4L3Protocol::Receive(), Send(), and ns3::Ipv4L3Protocol::SendRealOut().
operator=()
Ipv4Interface& ns3::Ipv4Interface::operator= (const Ipv4Interface & o) private
Assignment operator.
Parameters
o object to copy
Returns
the copied object
Defined and unimplemented to avoid misuse
RemoveAddress() [1/2]
Ipv4InterfaceAddress ns3::Ipv4Interface::RemoveAddress (Ipv4Address address)
Remove the given Ipv4 address from the interface.
Parameters
address The Ipv4 address to remove
Returns
The removed Ipv4 interface address
The null interface address if the interface did not contain the address or if loopback address was passed as argument
Definition at line 367 of file ipv4-interface.cc.
References first::address, m_ifaddrs, NS_LOG_FUNCTION, and NS_LOG_WARN.
RemoveAddress() [2/2]
Ipv4InterfaceAddress ns3::Ipv4Interface::RemoveAddress (uint32_t index)
Parameters
index Index of Ipv4InterfaceAddress to remove
Returns
The Ipv4InterfaceAddress address whose index is index
Definition at line 341 of file ipv4-interface.cc.
References m_ifaddrs, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
Send()
void ns3::Ipv4Interface::Send (Ptr< Packet > p, const Ipv4Header & hdr, Ipv4Address dest)
Parameters
p packet to send
hdr IPv4 header
dest next hop address of packet.
This method will eventually call the private SendTo method which must be implemented by subclasses.
Todo:
additional checks needed here (such as whether multicast goes to loopback)?
Definition at line 213 of file ipv4-interface.cc.
References ns3::Packet::AddHeader(), ns3::Object::GetObject(), ns3::Ipv4Address::IsBroadcast(), ns3::Ipv4Address::IsMulticast(), ns3::Ipv4Address::IsSubnetDirectedBroadcast(), IsUp(), m_cache, m_device, m_ifaddrs, m_node, m_tc, NS_ASSERT, NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::NetDevice::PACKET_HOST, and ns3::Ipv4L3Protocol::PROT_NUMBER.
Referenced by ns3::ArpL3Protocol::Receive(), and ns3::Ipv4L3Protocol::SendRealOut().
SetArpCache()
void ns3::Ipv4Interface::SetArpCache (Ptr< ArpCache > arpCache)
Set ARP cache used by this interface.
Parameters
arpCache the ARP cache
Definition at line 152 of file ipv4-interface.cc.
References m_cache, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetDevice()
void ns3::Ipv4Interface::SetDevice (Ptr< NetDevice > device)
Set the NetDevice.
Parameters
device NetDevice
Definition at line 100 of file ipv4-interface.cc.
References DoSetup(), m_device, and NS_LOG_FUNCTION.
SetDown()
void ns3::Ipv4Interface::SetDown (void)
Disable this interface.
Definition at line 192 of file ipv4-interface.cc.
References m_ifup, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4L3Protocol::SetDown().
SetForwarding()
void ns3::Ipv4Interface::SetForwarding (bool val)
Parameters
val Whether to enable or disable IP forwarding for input datagrams
Definition at line 206 of file ipv4-interface.cc.
References m_forwarding, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4L3Protocol::SetForwarding().
SetMetric()
void ns3::Ipv4Interface::SetMetric (uint16_t metric)
Parameters
metric configured routing metric (cost) of this interface
Note: This is synonymous to the Metric value that ifconfig prints out. It is used by ns-3 global routing, but other routing daemons choose to ignore it.
Definition at line 138 of file ipv4-interface.cc.
References m_metric, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4L3Protocol::SetMetric().
SetNode()
void ns3::Ipv4Interface::SetNode (Ptr< Node > node)
Set node associated with interface.
Parameters
node node
Definition at line 92 of file ipv4-interface.cc.
References DoSetup(), m_node, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4L3Protocol::AddInterface().
SetTrafficControl()
void ns3::Ipv4Interface::SetTrafficControl (Ptr< TrafficControlLayer > tc)
Set the TrafficControlLayer.
Parameters
tc TrafficControlLayer object
Definition at line 108 of file ipv4-interface.cc.
References m_tc, and NS_LOG_FUNCTION.
SetUp()
void ns3::Ipv4Interface::SetUp (void)
Enable this interface.
Definition at line 185 of file ipv4-interface.cc.
References m_ifup, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4L3Protocol::SetUp().
Member Data Documentation
m_cache
Ptr<ArpCache> ns3::Ipv4Interface::m_cache private
ARP cache.
Definition at line 241 of file ipv4-interface.h.
Referenced by DoDispose(), DoSetup(), GetArpCache(), Send(), and SetArpCache().
m_device
Ptr<NetDevice> ns3::Ipv4Interface::m_device private
The associated NetDevice.
Definition at line 239 of file ipv4-interface.h.
Referenced by DoDispose(), DoSetup(), GetDevice(), Send(), and SetDevice().
m_forwarding
bool ns3::Ipv4Interface::m_forwarding private
Forwarding state.
Definition at line 235 of file ipv4-interface.h.
Referenced by IsForwarding(), and SetForwarding().
m_ifaddrs
Ipv4InterfaceAddressList ns3::Ipv4Interface::m_ifaddrs private
Address list.
Definition at line 237 of file ipv4-interface.h.
Referenced by AddAddress(), GetAddress(), GetNAddresses(), RemoveAddress(), and Send().
m_ifup
bool ns3::Ipv4Interface::m_ifup private
The state of this interface.
Definition at line 234 of file ipv4-interface.h.
Referenced by IsDown(), IsUp(), SetDown(), and SetUp().
m_metric
uint16_t ns3::Ipv4Interface::m_metric private
Interface metric.
Definition at line 236 of file ipv4-interface.h.
Referenced by GetMetric(), and SetMetric().
m_node
Ptr<Node> ns3::Ipv4Interface::m_node private
The associated node.
Definition at line 238 of file ipv4-interface.h.
Referenced by DoDispose(), DoSetup(), Send(), and SetNode().
m_tc
Ptr<TrafficControlLayer> ns3::Ipv4Interface::m_tc private
The associated TrafficControlLayer.
Definition at line 240 of file ipv4-interface.h.
Referenced by DoDispose(), Send(), and SetTrafficControl().
The documentation for this class was generated from the following files:
src/internet/model/ipv4-interface.h
src/internet/model/ipv4-interface.cc