ns-3: ns3::Ipv4GlobalRoutingHelper Class Reference
ns3::Ipv4GlobalRoutingHelper Class Reference
Internet » IPv4 Helper classes
Helper class that adds ns3::Ipv4GlobalRouting objects.
#include "ipv4-global-routing-helper.h"
Public Member Functions
Ipv4GlobalRoutingHelper ()
Construct a GlobalRoutingHelper to make life easier for managing global routing tasks.
Ipv4GlobalRoutingHelper (const Ipv4GlobalRoutingHelper &)
Construct a GlobalRoutingHelper from another previously initialized instance (Copy Constructor).
Ipv4GlobalRoutingHelper * Copy (void) const
virtual Ptr< Ipv4RoutingProtocol > Create (Ptr< Node > node) const
Public Member Functions inherited from ns3::Ipv4RoutingHelper
virtual ~Ipv4RoutingHelper ()
Static Public Member Functions
static void PopulateRoutingTables (void)
Build a routing database and initialize the routing tables of the nodes in the simulation.
static void RecomputeRoutingTables (void)
Remove all routes that were previously installed in a prior call to either PopulateRoutingTables() or RecomputeRoutingTables(), and add a new set of routes.
Static Public Member Functions inherited from ns3::Ipv4RoutingHelper
template<class T >
static Ptr< T > GetRouting (Ptr< Ipv4RoutingProtocol > protocol)
Request a specified routing protocol <T> from Ipv4RoutingProtocol protocol.
static void PrintNeighborCacheAllAt (Time printTime, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the neighbor cache of all nodes at a particular time.
static void PrintNeighborCacheAllEvery (Time printInterval, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the neighbor cache of all nodes at regular intervals specified by user.
static void PrintNeighborCacheAt (Time printTime, Ptr< Node > node, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the neighbor cache of a node at a particular time.
static void PrintNeighborCacheEvery (Time printInterval, Ptr< Node > node, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the neighbor cache of a node at regular intervals specified by user.
static void PrintRoutingTableAllAt (Time printTime, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of all nodes at a particular time.
static void PrintRoutingTableAllEvery (Time printInterval, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of all nodes at regular intervals specified by user.
static void PrintRoutingTableAt (Time printTime, Ptr< Node > node, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of a node at a particular time.
static void PrintRoutingTableEvery (Time printInterval, Ptr< Node > node, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of a node at regular intervals specified by user.
Private Member Functions
Ipv4GlobalRoutingHelper & operator= (const Ipv4GlobalRoutingHelper &)
Assignment operator declared private and not implemented to disallow assignment and prevent the compiler from happily inserting its own.
Detailed Description
Helper class that adds ns3::Ipv4GlobalRouting objects.
Definition at line 33 of file ipv4-global-routing-helper.h.
Constructor & Destructor Documentation
Ipv4GlobalRoutingHelper() [1/2]
ns3::Ipv4GlobalRoutingHelper::Ipv4GlobalRoutingHelper ()
Construct a GlobalRoutingHelper to make life easier for managing global routing tasks.
Definition at line 30 of file ipv4-global-routing-helper.cc.
Referenced by Copy().
Ipv4GlobalRoutingHelper() [2/2]
ns3::Ipv4GlobalRoutingHelper::Ipv4GlobalRoutingHelper (const Ipv4GlobalRoutingHelper & o)
Construct a GlobalRoutingHelper from another previously initialized instance (Copy Constructor).
Definition at line 34 of file ipv4-global-routing-helper.cc.
Member Function Documentation
Copy()
Ipv4GlobalRoutingHelper * ns3::Ipv4GlobalRoutingHelper::Copy (void) const virtual
Returns
pointer to clone of this Ipv4GlobalRoutingHelper
This method is mainly for internal use by the other helpers; clients are expected to free the dynamic memory allocated by this method
Implements ns3::Ipv4RoutingHelper.
Definition at line 39 of file ipv4-global-routing-helper.cc.
References Ipv4GlobalRoutingHelper().
Create()
Ptr< Ipv4RoutingProtocol > ns3::Ipv4GlobalRoutingHelper::Create (Ptr< Node > node) const virtual
Parameters
node the node on which the routing protocol will run
Returns
a newly-created routing protocol
This method will be called by ns3::InternetStackHelper::Install
Implements ns3::Ipv4RoutingHelper.
Definition at line 45 of file ipv4-global-routing-helper.cc.
References ns3::Object::AggregateObject(), ns3::Node::GetId(), and NS_LOG_LOGIC.
operator=()
Ipv4GlobalRoutingHelper& ns3::Ipv4GlobalRoutingHelper::operator= (const Ipv4GlobalRoutingHelper &) private
Assignment operator declared private and not implemented to disallow assignment and prevent the compiler from happily inserting its own.
Returns
PopulateRoutingTables()
void ns3::Ipv4GlobalRoutingHelper::PopulateRoutingTables (void) static
Build a routing database and initialize the routing tables of the nodes in the simulation.
Makes all nodes in the simulation into routers.
All this function does is call the functions BuildGlobalRoutingDatabase () and InitializeRoutes ().
Definition at line 61 of file ipv4-global-routing-helper.cc.
References ns3::GlobalRouteManager::BuildGlobalRoutingDatabase(), and ns3::GlobalRouteManager::InitializeRoutes().
Referenced by experiment().
RecomputeRoutingTables()
void ns3::Ipv4GlobalRoutingHelper::RecomputeRoutingTables (void) static
Remove all routes that were previously installed in a prior call to either PopulateRoutingTables() or RecomputeRoutingTables(), and add a new set of routes.
This method does not change the set of nodes over which GlobalRouting is being used, but it will dynamically update its representation of the global topology before recomputing routes. Users must first call PopulateRoutingTables() and then may subsequently call RecomputeRoutingTables() at any later time in the simulation.
Definition at line 67 of file ipv4-global-routing-helper.cc.
References ns3::GlobalRouteManager::BuildGlobalRoutingDatabase(), ns3::GlobalRouteManager::DeleteGlobalRoutes(), and ns3::GlobalRouteManager::InitializeRoutes().
The documentation for this class was generated from the following files:
src/internet/helper/ipv4-global-routing-helper.h
src/internet/helper/ipv4-global-routing-helper.cc