ns-3: ns3::LiIonEnergySource Class Reference
ns3::LiIonEnergySource Class Reference
Energy Models
Model a generic Lithium Ion Battery basing on [1][2].
#include "li-ion-energy-source.h"
Public Member Functions
LiIonEnergySource ()
virtual ~LiIonEnergySource ()
virtual void DecreaseRemainingEnergy (double energyJ)
virtual double GetEnergyFraction (void)
Time GetEnergyUpdateInterval (void) const
virtual double GetInitialEnergy (void) const
virtual double GetRemainingEnergy (void)
virtual double GetSupplyVoltage (void) const
virtual void IncreaseRemainingEnergy (double energyJ)
void SetEnergyUpdateInterval (Time interval)
void SetInitialEnergy (double initialEnergyJ)
void SetInitialSupplyVoltage (double supplyVoltageV)
virtual void UpdateEnergySource (void)
Implements UpdateEnergySource.
Public Member Functions inherited from ns3::EnergySource
EnergySource ()
virtual ~EnergySource ()
void AppendDeviceEnergyModel (Ptr< DeviceEnergyModel > deviceEnergyModelPtr)
void ConnectEnergyHarvester (Ptr< EnergyHarvester > energyHarvesterPtr)
void DisposeDeviceModels (void)
Calls Dispose () method of the device energy models.
DeviceEnergyModelContainer FindDeviceEnergyModels (std::string name)
DeviceEnergyModelContainer FindDeviceEnergyModels (TypeId tid)
Ptr< Node > GetNode (void) const
void InitializeDeviceModels (void)
Calls Start () method of the device energy models.
void SetNode (Ptr< Node > node)
Sets pointer to node containing this EnergySource.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::EnergySource
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void CalculateRemainingEnergy (void)
Calculates remaining energy.
void DoDispose (void)
All child's implementation must call BreakDeviceEnergyModelRefCycle to ensure reference cycles to DeviceEnergyModel objects are broken.
void DoInitialize (void)
Initialize() implementation.
double GetVoltage (double current) const
void HandleEnergyDrainedEvent (void)
Handles the remaining energy going to zero event.
Private Attributes
double m_drainedCapacity
double m_eExp
double m_eFull
EventId m_energyUpdateEvent
Time m_energyUpdateInterval
double m_eNom
double m_initialEnergyJ
double m_internalResistance
Time m_lastUpdateTime
double m_lowBatteryTh
double m_minVoltTh
double m_qExp
double m_qNom
double m_qRated
TracedValue< double > m_remainingEnergyJ
double m_supplyVoltageV
double m_typCurrent
Additional Inherited Members
Protected Member Functions inherited from ns3::EnergySource
void BreakDeviceEnergyModelRefCycle (void)
This function is called to break reference cycle between EnergySource and DeviceEnergyModel.
double CalculateTotalCurrent (void)
void NotifyEnergyChanged (void)
This function notifies all DeviceEnergyModel of energy changed event.
void NotifyEnergyDrained (void)
This function notifies all DeviceEnergyModel of energy depletion event.
void NotifyEnergyRecharged (void)
This function notifies all DeviceEnergyModel of energy recharged event.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Model a generic Lithium Ion Battery basing on [1][2].
Introspection did not find any typical Config paths.
The model can be fitted to any type of Li-Ion Battery, simply changing the model parameters. The default values are fitted for the Panasonic CGR18650DA Li-Ion Battery [3].
The energy is drained as defined from the EnergySource interface but, this class consider the non-linear behaviour of Li-Ion cell. Each time energy is drained from the cell, the class evaluates the discharge curve to get the actual cell's voltage, accordingly to State of Charge (SOC) and current's drain.
If the actual voltage of the cell goes below the minimum threshold voltage, the cell is considered depleted and the energy drained event fired up.
The model requires several parameters to approximates the discharge curves:
IntialCellVoltage, maximum voltage of the fully charged cell
NominalCellVoltage, nominal cell's voltage, is used to determine the end of the nominal zone.
ExpCellVoltage, cell's voltage at the end of the exponential zone
RatedCapacity, rated capacity of the cell, in Ah
NomCapacity, cell's capacity at the end of the nominal zone, in Ah
ExpCapacity, cell's capacity at the end of the exponential zone, in Ah
InternalResistance, internal resistance of the cell, in Ohms
TypCurrent, typical discharge current value, used during the fitting process, in Ah
ThresholdVoltage, minimum threshold voltage below which the cell is considered depleted
For a complete reference of the energy source model and model's fitting please refer to UAN Framework page and Li-Ion model fitting page.
References: [1] C. M. Shepherd, "Design of Primary and Secondary Cells - Part 3. Battery discharge equation," U.S. Naval Research Laboratory, 1963 [2] Tremblay, O.; Dessaint, L.-A.; Dekkiche, A.-I., "A Generic Battery Model for the Dynamic Simulation of Hybrid Electric Vehicles," Ecole de Technologie Superieure, Universite du Quebec, 2007 [3] http://www.panasonic.com/industrial/includes/pdf/Panasonic_LiIon_CGR18650DA.pdf
Attributes
LiIonEnergySourceInitialEnergyJ: Initial energy stored in basic energy source.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 31752
Flags: construct write read
LiIonEnergyLowBatteryThreshold: Low battery threshold for LiIon energy source.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0.1
Flags: construct write read
InitialCellVoltage: Initial (maximum) voltage of the cell (fully charged).
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 4.05
Flags: construct write read
NominalCellVoltage: Nominal voltage of the cell.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 3.6
Flags: construct write read
ExpCellVoltage: Cell voltage at the end of the exponential zone.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 3.6
Flags: construct write read
RatedCapacity: Rated capacity of the cell.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 2.45
Flags: construct write read
NomCapacity: Cell capacity at the end of the nominal zone.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 1.1
Flags: construct write read
ExpCapacity: Cell Capacity at the end of the exponential zone.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 1.2
Flags: construct write read
InternalResistance: Internal resistance of the cell
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0.083
Flags: construct write read
TypCurrent: Typical discharge current used to fit the curves
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 2.33
Flags: construct write read
ThresholdVoltage: Minimum threshold voltage to consider the battery depleted.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 3.3
Flags: construct write read
PeriodicEnergyUpdateInterval: Time between two consecutive periodic energy updates.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+09ns
Flags: construct write read
TraceSources
RemainingEnergy: Remaining energy at BasicEnergySource.
Callback signature: ns3::TracedValueCallback::Double
Size of this type is 264 bytes (on a 64-bit architecture).
Definition at line 72 of file li-ion-energy-source.h.
Constructor & Destructor Documentation
LiIonEnergySource()
ns3::LiIonEnergySource::LiIonEnergySource ()
Definition at line 114 of file li-ion-energy-source.cc.
References NS_LOG_FUNCTION.
~LiIonEnergySource()
ns3::LiIonEnergySource::~LiIonEnergySource () virtual
Definition at line 121 of file li-ion-energy-source.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CalculateRemainingEnergy()
void ns3::LiIonEnergySource::CalculateRemainingEnergy (void) private
Calculates remaining energy.
This function uses the total current from all device models to calculate the amount of energy to decrease. The energy to decrease is given by: energy to decrease = total current * supply voltage * time duration This function subtracts the calculated energy to decrease from remaining energy.
Definition at line 271 of file li-ion-energy-source.cc.
References ns3::EnergySource::CalculateTotalCurrent(), ns3::Time::GetSeconds(), GetVoltage(), m_drainedCapacity, m_lastUpdateTime, m_remainingEnergyJ, m_supplyVoltageV, ns3::Simulator::Now(), NS_ASSERT, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by UpdateEnergySource().
DecreaseRemainingEnergy()
void ns3::LiIonEnergySource::DecreaseRemainingEnergy (double energyJ) virtual
Parameters
energyJ Amount of energy (in Joules) to decrease from energy source.
Implements DecreaseRemainingEnergy.
Definition at line 191 of file li-ion-energy-source.cc.
References HandleEnergyDrainedEvent(), m_minVoltTh, m_remainingEnergyJ, m_supplyVoltageV, NS_ASSERT, and NS_LOG_FUNCTION.
DoDispose()
void ns3::LiIonEnergySource::DoDispose (void) private virtual
All child's implementation must call BreakDeviceEnergyModelRefCycle to ensure reference cycles to DeviceEnergyModel objects are broken.
Defined in ns3::Object
Reimplemented from ns3::EnergySource.
Definition at line 253 of file li-ion-energy-source.cc.
References ns3::EnergySource::BreakDeviceEnergyModelRefCycle(), and NS_LOG_FUNCTION.
DoInitialize()
void ns3::LiIonEnergySource::DoInitialize (void) private virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 246 of file li-ion-energy-source.cc.
References NS_LOG_FUNCTION, and UpdateEnergySource().
GetEnergyFraction()
double ns3::LiIonEnergySource::GetEnergyFraction (void) virtual
Returns
Energy fraction.
Implements GetEnergyFraction.
Implements ns3::EnergySource.
Definition at line 182 of file li-ion-energy-source.cc.
References m_initialEnergyJ, m_remainingEnergyJ, NS_LOG_FUNCTION, and UpdateEnergySource().
GetEnergyUpdateInterval()
Time ns3::LiIonEnergySource::GetEnergyUpdateInterval (void) const
Returns
The interval between each energy update.
Definition at line 166 of file li-ion-energy-source.cc.
References m_energyUpdateInterval, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetInitialEnergy()
double ns3::LiIonEnergySource::GetInitialEnergy (void) const virtual
Returns
Initial energy stored in energy source, in Joules.
Implements GetInitialEnergy.
Implements ns3::EnergySource.
Definition at line 137 of file li-ion-energy-source.cc.
References m_initialEnergyJ, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetRemainingEnergy()
double ns3::LiIonEnergySource::GetRemainingEnergy (void) virtual
Returns
Remaining energy in energy source, in Joules
Implements GetRemainingEnergy.
Implements ns3::EnergySource.
Definition at line 173 of file li-ion-energy-source.cc.
References m_remainingEnergyJ, NS_LOG_FUNCTION, and UpdateEnergySource().
GetSupplyVoltage()
double ns3::LiIonEnergySource::GetSupplyVoltage (void) const virtual
Returns
Supply voltage at the energy source.
Implements GetSupplyVoltage.
Implements ns3::EnergySource.
Definition at line 152 of file li-ion-energy-source.cc.
References m_supplyVoltageV, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::LiIonEnergySource::GetTypeId (void) static
Definition at line 37 of file li-ion-energy-source.cc.
References GetEnergyUpdateInterval(), GetInitialEnergy(), GetSupplyVoltage(), m_eExp, m_eNom, m_internalResistance, m_lowBatteryTh, m_minVoltTh, m_qExp, m_qNom, m_qRated, m_remainingEnergyJ, m_typCurrent, ns3::MakeDoubleAccessor(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::Seconds(), SetEnergyUpdateInterval(), SetInitialEnergy(), SetInitialSupplyVoltage(), and ns3::TypeId::SetParent().
GetVoltage()
double ns3::LiIonEnergySource::GetVoltage (double current) const private
Parameters
current the actual discharge current value.
Get the cell voltage in function of the discharge current. It consider different discharge curves for different discharge currents and the remaining energy of the cell.
Definition at line 296 of file li-ion-energy-source.cc.
References E, m_drainedCapacity, m_eExp, m_eFull, m_eNom, m_internalResistance, m_qExp, m_qNom, m_qRated, m_typCurrent, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by CalculateRemainingEnergy().
HandleEnergyDrainedEvent()
void ns3::LiIonEnergySource::HandleEnergyDrainedEvent (void) private
Handles the remaining energy going to zero event.
This function notifies all the energy models aggregated to the node about the energy being depleted. Each energy model is then responsible for its own handler.
Definition at line 261 of file li-ion-energy-source.cc.
References ns3::EnergySource::GetNode(), ns3::EnergySource::NotifyEnergyDrained(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by DecreaseRemainingEnergy(), and UpdateEnergySource().
IncreaseRemainingEnergy()
void ns3::LiIonEnergySource::IncreaseRemainingEnergy (double energyJ) virtual
Parameters
energyJ Amount of energy (in Joules) to increase from energy source.
Implements IncreaseRemainingEnergy.
Definition at line 205 of file li-ion-energy-source.cc.
References m_remainingEnergyJ, NS_ASSERT, and NS_LOG_FUNCTION.
SetEnergyUpdateInterval()
void ns3::LiIonEnergySource::SetEnergyUpdateInterval (Time interval)
Parameters
interval Energy update interval.
This function sets the interval between each energy update.
Definition at line 159 of file li-ion-energy-source.cc.
References m_energyUpdateInterval, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetInitialEnergy()
void ns3::LiIonEnergySource::SetInitialEnergy (double initialEnergyJ)
Parameters
initialEnergyJ Initial energy, in Joules
Implements SetInitialEnergy. Note that initial energy is assumed to be set before simulation starts and is set only once per simulation.
Definition at line 127 of file li-ion-energy-source.cc.
References m_initialEnergyJ, m_remainingEnergyJ, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetInitialSupplyVoltage()
void ns3::LiIonEnergySource::SetInitialSupplyVoltage (double supplyVoltageV)
Parameters
supplyVoltageV Initial Supply voltage at the energy source, in Volts.
Sets the initial supply voltage of the energy source. To be called only once.
Definition at line 144 of file li-ion-energy-source.cc.
References m_eFull, m_supplyVoltageV, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
UpdateEnergySource()
void ns3::LiIonEnergySource::UpdateEnergySource (void) virtual
Implements UpdateEnergySource.
Implements ns3::EnergySource.
Definition at line 213 of file li-ion-energy-source.cc.
References CalculateRemainingEnergy(), ns3::EventId::Cancel(), ns3::EnergySource::GetNode(), HandleEnergyDrainedEvent(), ns3::Simulator::IsFinished(), m_energyUpdateEvent, m_energyUpdateInterval, m_initialEnergyJ, m_lastUpdateTime, m_lowBatteryTh, m_remainingEnergyJ, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::Simulator::Schedule().
Referenced by DoInitialize(), GetEnergyFraction(), and GetRemainingEnergy().
Member Data Documentation
m_drainedCapacity
double ns3::LiIonEnergySource::m_drainedCapacity private
Definition at line 186 of file li-ion-energy-source.h.
Referenced by CalculateRemainingEnergy(), and GetVoltage().
m_eExp
double ns3::LiIonEnergySource::m_eExp private
Definition at line 194 of file li-ion-energy-source.h.
Referenced by GetTypeId(), and GetVoltage().
m_eFull
double ns3::LiIonEnergySource::m_eFull private
Definition at line 192 of file li-ion-energy-source.h.
Referenced by GetVoltage(), and SetInitialSupplyVoltage().
m_energyUpdateEvent
EventId ns3::LiIonEnergySource::m_energyUpdateEvent private
Definition at line 189 of file li-ion-energy-source.h.
Referenced by UpdateEnergySource().
m_energyUpdateInterval
Time ns3::LiIonEnergySource::m_energyUpdateInterval private
Definition at line 191 of file li-ion-energy-source.h.
Referenced by GetEnergyUpdateInterval(), SetEnergyUpdateInterval(), and UpdateEnergySource().
m_eNom
double ns3::LiIonEnergySource::m_eNom private
Definition at line 193 of file li-ion-energy-source.h.
Referenced by GetTypeId(), and GetVoltage().
m_initialEnergyJ
double ns3::LiIonEnergySource::m_initialEnergyJ private
Definition at line 184 of file li-ion-energy-source.h.
Referenced by GetEnergyFraction(), GetInitialEnergy(), SetInitialEnergy(), and UpdateEnergySource().
m_internalResistance
double ns3::LiIonEnergySource::m_internalResistance private
Definition at line 195 of file li-ion-energy-source.h.
Referenced by GetTypeId(), and GetVoltage().
m_lastUpdateTime
Time ns3::LiIonEnergySource::m_lastUpdateTime private
Definition at line 190 of file li-ion-energy-source.h.
Referenced by CalculateRemainingEnergy(), and UpdateEnergySource().
m_lowBatteryTh
double ns3::LiIonEnergySource::m_lowBatteryTh private
Definition at line 188 of file li-ion-energy-source.h.
Referenced by GetTypeId(), and UpdateEnergySource().
m_minVoltTh
double ns3::LiIonEnergySource::m_minVoltTh private
Definition at line 200 of file li-ion-energy-source.h.
Referenced by DecreaseRemainingEnergy(), and GetTypeId().
m_qExp
double ns3::LiIonEnergySource::m_qExp private
Definition at line 198 of file li-ion-energy-source.h.
Referenced by GetTypeId(), and GetVoltage().
m_qNom
double ns3::LiIonEnergySource::m_qNom private
Definition at line 197 of file li-ion-energy-source.h.
Referenced by GetTypeId(), and GetVoltage().
m_qRated
double ns3::LiIonEnergySource::m_qRated private
Definition at line 196 of file li-ion-energy-source.h.
Referenced by GetTypeId(), and GetVoltage().
m_remainingEnergyJ
TracedValue<double> ns3::LiIonEnergySource::m_remainingEnergyJ private
Definition at line 185 of file li-ion-energy-source.h.
Referenced by CalculateRemainingEnergy(), DecreaseRemainingEnergy(), GetEnergyFraction(), GetRemainingEnergy(), GetTypeId(), IncreaseRemainingEnergy(), SetInitialEnergy(), and UpdateEnergySource().
m_supplyVoltageV
double ns3::LiIonEnergySource::m_supplyVoltageV private
Definition at line 187 of file li-ion-energy-source.h.
Referenced by CalculateRemainingEnergy(), DecreaseRemainingEnergy(), GetSupplyVoltage(), and SetInitialSupplyVoltage().
m_typCurrent
double ns3::LiIonEnergySource::m_typCurrent private
Definition at line 199 of file li-ion-energy-source.h.
Referenced by GetTypeId(), and GetVoltage().
The documentation for this class was generated from the following files:
src/energy/model/li-ion-energy-source.h
src/energy/model/li-ion-energy-source.cc