ns-3: ns3::NamesPriv Class Reference
ns3::NamesPriv Class Reference
Core » Configuration
The singleton root Names object.
Public Member Functions
NamesPriv ()
Constructor.
~NamesPriv ()
Destructor.
bool Add (Ptr< Object > context, std::string name, Ptr< Object > object)
Internal implementation for Names::Add(Ptr<Object>,std::string,Ptr<Object>)
bool Add (std::string name, Ptr< Object > object)
Internal implementation for Names::Add(std::string,Ptr<Object>)
bool Add (std::string path, std::string name, Ptr< Object > object)
Internal implementation for Names::Add(std::string,std::string,Ptr<Object>)
void Clear (void)
Internal implementation for Names::Clear()
Ptr< Object > Find (Ptr< Object > context, std::string name)
Internal implementation for ns3::Names::Find(Ptr<Object>,std::string)
Ptr< Object > Find (std::string path)
Internal implementation for ns3::Names::Find(std::string)
Ptr< Object > Find (std::string path, std::string name)
Internal implementation for ns3::Names::Find(std::string,std::string)
std::string FindName (Ptr< Object > object)
Internal implementation for Names::FindName()
std::string FindPath (Ptr< Object > object)
Internal implementation of Names::FindPath()
bool Rename (Ptr< Object > context, std::string oldname, std::string newname)
Internal implementation for Names::Rename(Ptr<Object>,std::string,std::string)
bool Rename (std::string oldpath, std::string newname)
Internal implementation for Names::Rename(std::string,std::string)
bool Rename (std::string path, std::string oldname, std::string newname)
Internal implementation for Names::Rename(std::string,std::string,std::string)
Private Member Functions
bool IsDuplicateName (NameNode *node, std::string name)
Check if a name already exists as a child of a NameNode.
NameNode * IsNamed (Ptr< Object > object)
Check if an object has a name.
Private Attributes
std::map< Ptr< Object >, NameNode * > m_objectMap
Map from object pointers to their NameNodes.
NameNode m_root
The root NameNode.
Additional Inherited Members
Static Public Member Functions inherited from ns3::Singleton< NamesPriv >
static NamesPriv * Get (void)
Get a pointer to the singleton instance.
Detailed Description
The singleton root Names object.
Definition at line 119 of file names.cc.
Constructor & Destructor Documentation
NamesPriv()
ns3::NamesPriv::NamesPriv ()
Constructor.
Definition at line 276 of file names.cc.
References ns3::NameNode::m_name, ns3::NameNode::m_object, ns3::NameNode::m_parent, m_root, and NS_LOG_FUNCTION.
~NamesPriv()
ns3::NamesPriv::~NamesPriv ()
Destructor.
Definition at line 285 of file names.cc.
References Clear(), ns3::NameNode::m_name, m_root, and NS_LOG_FUNCTION.
Member Function Documentation
Add() [1/3]
bool ns3::NamesPriv::Add (Ptr< Object > context, std::string name, Ptr< Object > object)
Internal implementation for Names::Add(Ptr<Object>,std::string,Ptr<Object>)
Parameters
[in] context A smart pointer to an object that is used in place of the path under which you want this new name to be defined.
[in] name The name of the object you want to associate.
[in] object A smart pointer to the object itself.
Returns
true if the object was named successfully.
Definition at line 388 of file names.cc.
References IsDuplicateName(), IsNamed(), ns3::NameNode::m_nameMap, m_objectMap, m_root, NS_ASSERT_MSG, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Add() [2/3]
bool ns3::NamesPriv::Add (std::string name, Ptr< Object > object)
Internal implementation for Names::Add(std::string,Ptr<Object>)
Parameters
[in] name The name of the object you want to associate; which may be prepended with a path to that object.
[in] object A smart pointer to the object itself.
Returns
true if the object was named successfully.
Definition at line 315 of file names.cc.
References NS_ASSERT_MSG, and NS_LOG_FUNCTION.
Referenced by ns3::Names::Add(), and Add().
Add() [3/3]
bool ns3::NamesPriv::Add (std::string path, std::string name, Ptr< Object > object)
Internal implementation for Names::Add(std::string,std::string,Ptr<Object>)
Parameters
[in] path A path name describing a previously named object under which you want this new name to be defined.
[in] name The name of the object you want to associate.
[in] object A smart pointer to the object itself.
Returns
true if the object was named successfully.
Definition at line 377 of file names.cc.
References Add(), Find(), and NS_LOG_FUNCTION.
Clear()
void ns3::NamesPriv::Clear (void)
Internal implementation for Names::Clear()
Definition at line 293 of file names.cc.
References ns3::NameNode::m_name, ns3::NameNode::m_nameMap, ns3::NameNode::m_object, m_objectMap, ns3::NameNode::m_parent, m_root, and NS_LOG_FUNCTION.
Referenced by ~NamesPriv(), and ns3::Names::Clear().
Find() [1/3]
Ptr< Object > ns3::NamesPriv::Find (Ptr< Object > context, std::string name)
Internal implementation for ns3::Names::Find(Ptr<Object>,std::string)
Parameters
[in] context A smart pointer to an object that is used in place of the path under which you want this new name to be defined.
[in] name A string containing a name to search for.
Returns
A smart pointer to the named object converted to the requested type.
Definition at line 697 of file names.cc.
References IsNamed(), ns3::NameNode::m_nameMap, m_root, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Find() [2/3]
Ptr< Object > ns3::NamesPriv::Find (std::string path)
Internal implementation for ns3::Names::Find(std::string)
Parameters
[in] path A string containing a name space path used to locate the object.
Returns
A smart pointer to the named object converted to the requested type.
Definition at line 591 of file names.cc.
References ns3::NameNode::m_nameMap, m_root, NS_ASSERT_MSG, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by Add(), Find(), ns3::Names::FindInternal(), and Rename().
Find() [3/3]
Ptr< Object > ns3::NamesPriv::Find (std::string path, std::string name)
Internal implementation for ns3::Names::Find(std::string,std::string)
Parameters
[in] path A path name describing a previously named object under which you want to look for the specified name.
[in] name A string containing a name to search for.
Returns
A smart pointer to the named object converted to the requested type.
Definition at line 685 of file names.cc.
References Find(), and NS_LOG_FUNCTION.
FindName()
std::string ns3::NamesPriv::FindName (Ptr< Object > object)
Internal implementation for Names::FindName()
Parameters
[in] object A smart pointer to an object for which you want to find its name.
Returns
A string containing the name of the object if found, otherwise the empty string.
Definition at line 545 of file names.cc.
References m_objectMap, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by ns3::Names::FindName().
FindPath()
std::string ns3::NamesPriv::FindPath (Ptr< Object > object)
Internal implementation of Names::FindPath()
Parameters
[in] object A smart pointer to an object for which you want to find its fullname.
Returns
A string containing the name path of the object, otherwise the empty string.
Definition at line 563 of file names.cc.
References ns3::NameNode::m_name, m_objectMap, ns3::NameNode::m_parent, NS_ASSERT_MSG, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by ns3::Names::FindPath().
IsDuplicateName()
bool ns3::NamesPriv::IsDuplicateName (NameNode * node, std::string name) private
Check if a name already exists as a child of a NameNode.
Parameters
[in] node The node to search.
[in] name The name to search for.
Returns
true if name already exists as a child of node.
Definition at line 750 of file names.cc.
References ns3::NameNode::m_nameMap, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by Add(), and Rename().
IsNamed()
NameNode * ns3::NamesPriv::IsNamed (Ptr< Object > object) private
Check if an object has a name.
Parameters
[in] object The object to check.
Returns
The corresponding NameNode, if it exists.
Definition at line 732 of file names.cc.
References m_objectMap, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by Add(), Find(), and Rename().
Rename() [1/3]
bool ns3::NamesPriv::Rename (Ptr< Object > context, std::string oldname, std::string newname)
Internal implementation for Names::Rename(Ptr<Object>,std::string,std::string)
Parameters
[in] context A smart pointer to an object that is used in place of the path under which you want this new name to be defined.
[in] oldname The current shortname of the object you want to change.
[in] newname The new shortname of the object you want to change.
Returns
true if the object was renamed successfully.
Definition at line 498 of file names.cc.
References IsDuplicateName(), IsNamed(), ns3::NameNode::m_name, ns3::NameNode::m_nameMap, m_root, NS_ASSERT_MSG, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Rename() [2/3]
bool ns3::NamesPriv::Rename (std::string oldpath, std::string newname)
Internal implementation for Names::Rename(std::string,std::string)
Parameters
[in] oldpath The current path name to the object you want to change.
[in] newname The new name of the object you want to change.
Returns
true if the object was renamed successfully.
Definition at line 423 of file names.cc.
References NS_ASSERT_MSG, and NS_LOG_FUNCTION.
Referenced by ns3::Names::Rename(), and Rename().
Rename() [3/3]
bool ns3::NamesPriv::Rename (std::string path, std::string oldname, std::string newname)
Internal implementation for Names::Rename(std::string,std::string,std::string)
Parameters
[in] path A path name describing a previously named object under which you want this name change to occur (cf. directory).
[in] oldname The currently defined name of the object.
[in] newname The new name you want the object to have.
Returns
true if the object was renamed successfully.
Definition at line 487 of file names.cc.
References Find(), NS_LOG_FUNCTION, and Rename().
Member Data Documentation
m_objectMap
std::map<Ptr<Object>, NameNode *> ns3::NamesPriv::m_objectMap private
Map from object pointers to their NameNodes.
Definition at line 273 of file names.cc.
Referenced by Add(), Clear(), FindName(), FindPath(), and IsNamed().
m_root
NameNode ns3::NamesPriv::m_root private
The root NameNode.
Definition at line 270 of file names.cc.
Referenced by NamesPriv(), ~NamesPriv(), Add(), Clear(), Find(), and Rename().
The documentation for this class was generated from the following file:
src/core/model/names.cc