ns-3: ns3::SeqTsHeader Class Reference
ns3::SeqTsHeader Class Reference
Applications
Packet header to carry sequence number and timestamp.
#include "seq-ts-header.h"
Public Member Functions
SeqTsHeader ()
virtual uint32_t Deserialize (Buffer::Iterator start)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint32_t GetSeq (void) const
virtual uint32_t GetSerializedSize (void) const
Time GetTs (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetSeq (uint32_t seq)
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint32_t m_seq
Sequence number.
uint64_t m_ts
Timestamp.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Packet header to carry sequence number and timestamp.
Introspection did not find any typical Config paths.
The header is used as a payload in applications (typically UDP) to convey a 32 bit sequence number followed by a 64 bit timestamp (12 bytes total).
The timestamp is not set explicitly but automatically set to the simulation time upon creation.
If you need space for an application data unit size field (e.g. for stream-based protocols like TCP), use ns3::SeqTsSizeHeader.
See also
ns3::SeqTsSizeHeader
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 24 bytes (on a 64-bit architecture).
Definition at line 44 of file seq-ts-header.h.
Constructor & Destructor Documentation
SeqTsHeader()
ns3::SeqTsHeader::SeqTsHeader ()
Definition at line 33 of file seq-ts-header.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Deserialize()
uint32_t ns3::SeqTsHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Reimplemented in ns3::SeqTsSizeHeader.
Definition at line 97 of file seq-ts-header.cc.
References GetSerializedSize(), m_seq, m_ts, NS_LOG_FUNCTION, ns3::Buffer::Iterator::ReadNtohU32(), ns3::Buffer::Iterator::ReadNtohU64(), and visualizer.core::start().
GetInstanceTypeId()
TypeId ns3::SeqTsHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Reimplemented in ns3::SeqTsSizeHeader.
Definition at line 71 of file seq-ts-header.cc.
References GetTypeId().
GetSeq()
uint32_t ns3::SeqTsHeader::GetSeq (void) const
Returns
the sequence number
Definition at line 47 of file seq-ts-header.cc.
References m_seq, and NS_LOG_FUNCTION.
Referenced by ns3::UdpServer::HandleRead(), WaveNetDeviceExample::Receive(), BulkSendSeqTsSizeTestCase::ReceiveRx(), and BulkSendSeqTsSizeTestCase::SendTx().
GetSerializedSize()
uint32_t ns3::SeqTsHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Reimplemented in ns3::SeqTsSizeHeader.
Definition at line 82 of file seq-ts-header.cc.
References NS_LOG_FUNCTION.
Referenced by Deserialize(), and ns3::SeqTsSizeHeader::GetSerializedSize().
GetTs()
Time ns3::SeqTsHeader::GetTs (void) const
Returns
the time stamp
Definition at line 54 of file seq-ts-header.cc.
References m_ts, and NS_LOG_FUNCTION.
Referenced by ns3::UdpServer::HandleRead(), WaveNetDeviceExample::Receive(), BulkSendSeqTsSizeTestCase::ReceiveRx(), and BulkSendSeqTsSizeTestCase::SendTx().
GetTypeId()
TypeId ns3::SeqTsHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 61 of file seq-ts-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::SeqTsHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Reimplemented in ns3::SeqTsSizeHeader.
Definition at line 76 of file seq-ts-header.cc.
References m_seq, m_ts, NS_LOG_FUNCTION, and ns3::Time::S.
Referenced by ns3::SeqTsSizeHeader::Print().
Serialize()
void ns3::SeqTsHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Reimplemented in ns3::SeqTsSizeHeader.
Definition at line 89 of file seq-ts-header.cc.
References m_seq, m_ts, NS_LOG_FUNCTION, visualizer.core::start(), ns3::Buffer::Iterator::WriteHtonU32(), and ns3::Buffer::Iterator::WriteHtonU64().
Referenced by ns3::SeqTsSizeHeader::Serialize().
SetSeq()
void ns3::SeqTsHeader::SetSeq (uint32_t seq)
Parameters
seq the sequence number
Definition at line 41 of file seq-ts-header.cc.
References m_seq, and NS_LOG_FUNCTION.
Referenced by ns3::UdpClient::Send(), EpsBearerTagUdpClient::Send(), ns3::BulkSendApplication::SendData(), WaveNetDeviceExample::SendIpPacket(), WaveNetDeviceExample::SendOneWsmpPacket(), ns3::OnOffApplication::SendPacket(), and ns3::UdpTraceClient::SendPacket().
Member Data Documentation
m_seq
uint32_t ns3::SeqTsHeader::m_seq private
Sequence number.
Definition at line 75 of file seq-ts-header.h.
Referenced by Deserialize(), GetSeq(), Print(), Serialize(), and SetSeq().
m_ts
uint64_t ns3::SeqTsHeader::m_ts private
Timestamp.
Definition at line 76 of file seq-ts-header.h.
Referenced by Deserialize(), GetTs(), Print(), and Serialize().
The documentation for this class was generated from the following files:
src/applications/model/seq-ts-header.h
src/applications/model/seq-ts-header.cc