ns-3: ns3::Ipv6PacketInfoTag Class Reference
ns3::Ipv6PacketInfoTag Class Reference
Internet » IPv6 classes and sub-modules
This class implements a tag that carries socket ancillary data to the socket interface.
#include "ipv6-packet-info-tag.h"
Public Member Functions
Ipv6PacketInfoTag ()
virtual void Deserialize (TagBuffer i)
Ipv6Address GetAddress (void) const
Get the tag's address.
uint8_t GetHoplimit (void) const
Get the tag's Hop Limit.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint32_t GetRecvIf (void) const
Get the tag's receiving interface.
virtual uint32_t GetSerializedSize (void) const
uint8_t GetTrafficClass (void) const
Get the tag's Traffic Class.
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer i) const
void SetAddress (Ipv6Address addr)
Set the tag's address.
void SetHoplimit (uint8_t ttl)
Set the tag's Hop Limit.
void SetRecvIf (uint32_t ifindex)
Set the tag's receiving interface.
void SetTrafficClass (uint8_t tclass)
Set the tag's Traffic Class.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Ipv6Address m_addr
the packet address (src or dst)
uint8_t m_hoplimit
the Hop Limit
uint8_t m_ifindex
the Interface index
uint8_t m_tclass
the Traffic Class
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class implements a tag that carries socket ancillary data to the socket interface.
This is used like socket option of IP_PKTINFO/IPV6_PKTINFO in RFC 3542
See also SocketIpv6TclassTag and SocketIpv6HopLimitTag
This tag in the send direction is presently not enabled but we would accept a patch along those lines in the future. To include the nexthop in the send direction would increase the size of the tag beyond 20 bytes, so in that case, we recommend that an additional tag be used to carry the IPv6 next hop address.
Definition at line 48 of file ipv6-packet-info-tag.h.
Constructor & Destructor Documentation
Ipv6PacketInfoTag()
ns3::Ipv6PacketInfoTag::Ipv6PacketInfoTag ()
Definition at line 28 of file ipv6-packet-info-tag.cc.
Member Function Documentation
Deserialize()
void ns3::Ipv6PacketInfoTag::Deserialize (TagBuffer i) virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 120 of file ipv6-packet-info-tag.cc.
References ns3::Ipv6Address::Deserialize(), m_addr, m_hoplimit, m_ifindex, m_tclass, ns3::TagBuffer::Read(), and ns3::TagBuffer::ReadU8().
GetAddress()
Ipv6Address ns3::Ipv6PacketInfoTag::GetAddress (void) const
Get the tag's address.
Returns
the address
Definition at line 43 of file ipv6-packet-info-tag.cc.
References m_addr.
GetHoplimit()
uint8_t ns3::Ipv6PacketInfoTag::GetHoplimit (void) const
Get the tag's Hop Limit.
Returns
the Hop Limit
Definition at line 67 of file ipv6-packet-info-tag.cc.
References m_hoplimit.
GetInstanceTypeId()
TypeId ns3::Ipv6PacketInfoTag::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 96 of file ipv6-packet-info-tag.cc.
References GetTypeId().
GetRecvIf()
uint32_t ns3::Ipv6PacketInfoTag::GetRecvIf (void) const
Get the tag's receiving interface.
Returns
the interface index
Definition at line 55 of file ipv6-packet-info-tag.cc.
References m_ifindex.
Referenced by ns3::Radvd::HandleRead(), and ns3::RipNg::Receive().
GetSerializedSize()
uint32_t ns3::Ipv6PacketInfoTag::GetSerializedSize (void) const virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 102 of file ipv6-packet-info-tag.cc.
GetTrafficClass()
uint8_t ns3::Ipv6PacketInfoTag::GetTrafficClass (void) const
Get the tag's Traffic Class.
Returns
the Traffic Class
Definition at line 79 of file ipv6-packet-info-tag.cc.
References m_tclass.
GetTypeId()
TypeId ns3::Ipv6PacketInfoTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 86 of file ipv6-packet-info-tag.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::Ipv6PacketInfoTag::Print (std::ostream & os) const virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 130 of file ipv6-packet-info-tag.cc.
References m_addr, m_hoplimit, m_ifindex, and m_tclass.
Serialize()
void ns3::Ipv6PacketInfoTag::Serialize (TagBuffer i) const virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 110 of file ipv6-packet-info-tag.cc.
References m_addr, m_hoplimit, m_ifindex, m_tclass, ns3::Ipv6Address::Serialize(), ns3::TagBuffer::Write(), and ns3::TagBuffer::WriteU8().
SetAddress()
void ns3::Ipv6PacketInfoTag::SetAddress (Ipv6Address addr)
Set the tag's address.
Parameters
addr the address
Definition at line 37 of file ipv6-packet-info-tag.cc.
References m_addr.
Referenced by ns3::Ipv6RawSocketImpl::ForwardUp(), and ns3::UdpSocketImpl::ForwardUp6().
SetHoplimit()
void ns3::Ipv6PacketInfoTag::SetHoplimit (uint8_t ttl)
Set the tag's Hop Limit.
Parameters
ttl the hop limit
Definition at line 61 of file ipv6-packet-info-tag.cc.
References m_hoplimit.
Referenced by ns3::Ipv6RawSocketImpl::ForwardUp(), and ns3::UdpSocketImpl::ForwardUp6().
SetRecvIf()
void ns3::Ipv6PacketInfoTag::SetRecvIf (uint32_t ifindex)
Set the tag's receiving interface.
Parameters
ifindex the interface index
Definition at line 49 of file ipv6-packet-info-tag.cc.
References m_ifindex.
Referenced by ns3::Ipv6RawSocketImpl::ForwardUp(), and ns3::UdpSocketImpl::ForwardUp6().
SetTrafficClass()
void ns3::Ipv6PacketInfoTag::SetTrafficClass (uint8_t tclass)
Set the tag's Traffic Class.
Parameters
tclass the Traffic Class
Definition at line 73 of file ipv6-packet-info-tag.cc.
References m_tclass.
Referenced by ns3::Ipv6RawSocketImpl::ForwardUp(), and ns3::UdpSocketImpl::ForwardUp6().
Member Data Documentation
m_addr
Ipv6Address ns3::Ipv6PacketInfoTag::m_addr private
the packet address (src or dst)
Definition at line 138 of file ipv6-packet-info-tag.h.
Referenced by Deserialize(), GetAddress(), Print(), Serialize(), and SetAddress().
m_hoplimit
uint8_t ns3::Ipv6PacketInfoTag::m_hoplimit private
the Hop Limit
Definition at line 140 of file ipv6-packet-info-tag.h.
Referenced by Deserialize(), GetHoplimit(), Print(), Serialize(), and SetHoplimit().
m_ifindex
uint8_t ns3::Ipv6PacketInfoTag::m_ifindex private
the Interface index
Definition at line 139 of file ipv6-packet-info-tag.h.
Referenced by Deserialize(), GetRecvIf(), Print(), Serialize(), and SetRecvIf().
m_tclass
uint8_t ns3::Ipv6PacketInfoTag::m_tclass private
the Traffic Class
Definition at line 141 of file ipv6-packet-info-tag.h.
Referenced by Deserialize(), GetTrafficClass(), Print(), Serialize(), and SetTrafficClass().
The documentation for this class was generated from the following files:
src/internet/model/ipv6-packet-info-tag.h
src/internet/model/ipv6-packet-info-tag.cc