ns-3: ns3::DistributedSimulatorImpl Class Reference
ns3::DistributedSimulatorImpl Class Reference
Core » Simulator | MPI Distributed Simulation
Distributed simulator implementation using lookahead.
#include "distributed-simulator-impl.h"
Public Member Functions
DistributedSimulatorImpl ()
Default constructor.
~DistributedSimulatorImpl ()
Destructor.
virtual void BoundLookAhead (const Time lookAhead)
Add additional bound to lookahead constraints.
virtual void Cancel (const EventId &id)
Set the cancel bit on this event: the event's associated function will not be invoked when it expires.
virtual void Destroy ()
Execute the events scheduled with ScheduleDestroy().
virtual uint32_t GetContext (void) const
Get the current simulation context.
virtual Time GetDelayLeft (const EventId &id) const
Get the remaining time until this event will execute.
virtual uint64_t GetEventCount (void) const
Get the number of events executed.
virtual Time GetMaximumSimulationTime (void) const
Get the maximum representable simulation time.
virtual uint32_t GetSystemId (void) const
Get the system id of this simulator.
virtual bool IsExpired (const EventId &id) const
Check if an event has already run or been cancelled.
virtual bool IsFinished (void) const
Check if the simulation should finish.
virtual Time Now (void) const
Return the current simulation virtual time.
virtual void Remove (const EventId &id)
Remove an event from the event list.
virtual void Run (void)
Run the simulation.
virtual EventId Schedule (Time const &delay, EventImpl *event)
Schedule a future event execution (in the same context).
virtual EventId ScheduleDestroy (EventImpl *event)
Schedule an event to run at the end of the simulation, after the Stop() time or condition has been reached.
virtual EventId ScheduleNow (EventImpl *event)
Schedule an event to run at the current virtual time.
virtual void ScheduleWithContext (uint32_t context, Time const &delay, EventImpl *event)
Schedule a future event execution (in a different context).
virtual void SetScheduler (ObjectFactory schedulerFactory)
Set the Scheduler to be used to manage the event list.
virtual void Stop (Time const &delay)
Schedule the time delay until the Simulator should stop.
virtual void Stop (void)
Tell the Simulator the calling event should be the last one executed.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::SimulatorImpl
static TypeId GetTypeId (void)
Get the registered TypeId for this class.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef std::list< EventId > DestroyEvents
Container type for the events to run at Simulator::Destroy().
Private Member Functions
void CalculateLookAhead (void)
Calculate lookahead constraint based on network latency.
virtual void DoDispose (void)
Destructor implementation.
bool IsLocalFinished (void) const
Check if this rank is finished.
Time Next (void) const
Get the time of the next event, as returned by NextTs().
uint64_t NextTs (void) const
Get the timestep of the next event.
void ProcessOneEvent (void)
Process the next event.
Private Attributes
uint32_t m_currentContext
Execution context of the current event.
uint64_t m_currentTs
Timestamp of the current event.
uint32_t m_currentUid
Unique id of the current event.
DestroyEvents m_destroyEvents
The container of events to run at Destroy()
uint64_t m_eventCount
The event count.
Ptr< Scheduler > m_events
The event priority queue.
bool m_globalFinished
Are all parallel instances completed.
Time m_grantedTime
End of current window.
uint32_t m_myId
MPI rank.
LbtsMessage * m_pLBTS
Container for Lbts messages, one per rank.
bool m_stop
Flag calling for the end of the simulation.
uint32_t m_systemCount
MPI communicator size.
uint32_t m_uid
Next event unique id.
int m_unscheduledEvents
Number of events that have been inserted but not yet scheduled, not counting the "destroy" events; this is used for validation.
Static Private Attributes
static Time m_lookAhead = Time::Max()
Current window size.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Distributed simulator implementation using lookahead.
Definition at line 107 of file distributed-simulator-impl.h.
Member Typedef Documentation
DestroyEvents
typedef std::list<EventId> ns3::DistributedSimulatorImpl::DestroyEvents private
Container type for the events to run at Simulator::Destroy().
Definition at line 196 of file distributed-simulator-impl.h.
Constructor & Destructor Documentation
DistributedSimulatorImpl()
ns3::DistributedSimulatorImpl::DistributedSimulatorImpl ()
Default constructor.
Definition at line 100 of file distributed-simulator-impl.cc.
References ns3::MpiInterface::GetSize(), ns3::MpiInterface::GetSystemId(), m_currentContext, m_currentTs, m_currentUid, m_eventCount, m_events, m_globalFinished, m_grantedTime, m_myId, m_pLBTS, m_stop, m_systemCount, m_uid, m_unscheduledEvents, ns3::Simulator::NO_CONTEXT, NS_LOG_FUNCTION, and ns3::Seconds().
~DistributedSimulatorImpl()
ns3::DistributedSimulatorImpl::~DistributedSimulatorImpl ()
Destructor.
Definition at line 127 of file distributed-simulator-impl.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
BoundLookAhead()
void ns3::DistributedSimulatorImpl::BoundLookAhead (const Time lookAhead) virtual
Add additional bound to lookahead constraints.
This may be used if there are additional constraints on lookahead in addition to the minimum inter rank latency time. For example when running ns-3 in a co-simulation setting the other simulators may have tighter lookahead constraints.
The method may be invoked more than once, the minimum time will be used to constrain lookahead.
Parameters
[in] lookAhead The maximum lookahead; must be > 0.
Definition at line 279 of file distributed-simulator-impl.cc.
References m_lookAhead, ns3::Min(), NS_LOG_FUNCTION, and NS_LOG_WARN.
CalculateLookAhead()
void ns3::DistributedSimulatorImpl::CalculateLookAhead (void) private
Calculate lookahead constraint based on network latency.
The smallest cross-rank PointToPoint channel delay imposes a constraint on the conservative PDES time window. The user may impose additional constraints on lookahead using the ConstrainLookAhead() method.
Definition at line 168 of file distributed-simulator-impl.cc.
References ns3::NodeContainer::Begin(), third::channel, ns3::NodeContainer::End(), ns3::TimeValue::Get(), ns3::MpiInterface::GetCommunicator(), ns3::NodeContainer::GetGlobal(), ns3::Time::GetInteger(), GetMaximumSimulationTime(), ns3::MpiInterface::GetSize(), ns3::MpiInterface::GetSystemId(), ns3::Node::GetSystemId(), m_grantedTime, m_lookAhead, NS_LOG_FUNCTION, and ns3::Seconds().
Referenced by Run().
Cancel()
void ns3::DistributedSimulatorImpl::Cancel (const EventId & id) virtual
Set the cancel bit on this event: the event's associated function will not be invoked when it expires.
This method has the same visible effect as the ns3::Simulator::Remove method but its algorithmic complexity is much lower: it has O(1) complexity. This method has the exact same semantics as ns3::EventId::Cancel. Note that it is not possible to cancel events which were scheduled for the "destroy" time. Doing so will result in a program error (crash).
Parameters
[in] id the event to cancel
Implements ns3::SimulatorImpl.
Definition at line 587 of file distributed-simulator-impl.cc.
References IsExpired().
Destroy()
void ns3::DistributedSimulatorImpl::Destroy () virtual
Execute the events scheduled with ScheduleDestroy().
This method is typically invoked at the end of a simulation to avoid false-positive reports by a leak checker. After this method has been invoked, it is actually possible to restart a new simulation with a set of calls to Simulator::Run, Simulator::Schedule and Simulator::ScheduleWithContext.
Implements ns3::SimulatorImpl.
Definition at line 148 of file distributed-simulator-impl.cc.
References ns3::MpiInterface::Destroy(), m_destroyEvents, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
DoDispose()
void ns3::DistributedSimulatorImpl::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 133 of file distributed-simulator-impl.cc.
References ns3::Object::DoDispose(), ns3::Scheduler::Event::impl, m_events, m_pLBTS, NS_LOG_FUNCTION, and ns3::SimpleRefCount< T, PARENT, DELETER >::Unref().
GetContext()
uint32_t ns3::DistributedSimulatorImpl::GetContext (void) const virtual
Get the current simulation context.
The simulation context is the ns-3 notion of a Logical Process. Events in a single context should only modify state associated with that context. Events for objects in other contexts should be scheduled with ScheduleWithContext() to track the context switches. In other words, events in different contexts should be mutually thread safe, by not modify overlapping model state.
In circumstances where the context can't be determined, such as during object initialization, the enum value NO_CONTEXT should be used.
Returns
The current simulation context
Implements ns3::SimulatorImpl.
Definition at line 638 of file distributed-simulator-impl.cc.
References m_currentContext.
Referenced by Schedule(), and ScheduleNow().
GetDelayLeft()
Time ns3::DistributedSimulatorImpl::GetDelayLeft (const EventId & id) const virtual
Get the remaining time until this event will execute.
Parameters
[in] id The event id to analyse.
Returns
The delay left until the input event id expires. if the event is not running, this method returns zero.
Implements ns3::SimulatorImpl.
Definition at line 541 of file distributed-simulator-impl.cc.
References IsExpired(), and m_currentTs.
GetEventCount()
uint64_t ns3::DistributedSimulatorImpl::GetEventCount (void) const virtual
Get the number of events executed.
Returns
The total number of events executed.
Implements ns3::SimulatorImpl.
Definition at line 644 of file distributed-simulator-impl.cc.
References m_eventCount.
GetMaximumSimulationTime()
Time ns3::DistributedSimulatorImpl::GetMaximumSimulationTime (void) const virtual
Get the maximum representable simulation time.
Returns
The maximum simulation time at which an event can be scheduled.
The returned value will always be bigger than or equal to Simulator::Now.
Todo:
I am fairly certain other compilers use other non-standard post-fixes to indicate 64 bit constants.
Implements ns3::SimulatorImpl.
Definition at line 630 of file distributed-simulator-impl.cc.
Referenced by CalculateLookAhead(), NextTs(), and Run().
GetSystemId()
uint32_t ns3::DistributedSimulatorImpl::GetSystemId (void) const virtual
Get the system id of this simulator.
The system id is the identifier for this simulator instance in a distributed simulation. For MPI this is the MPI rank.
Returns
The system id for this simulator.
Implements ns3::SimulatorImpl.
Definition at line 448 of file distributed-simulator-impl.cc.
References m_myId.
GetTypeId()
TypeId ns3::DistributedSimulatorImpl::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 90 of file distributed-simulator-impl.cc.
References ns3::TypeId::SetParent().
IsExpired()
bool ns3::DistributedSimulatorImpl::IsExpired (const EventId & id) const virtual
Check if an event has already run or been cancelled.
This method has O(1) complexity. Note that it is not possible to test for the expiration of events which were scheduled for the "destroy" time. Doing so will result in a program error (crash). An event is said to "expire" when it starts being scheduled which means that if the code executed by the event calls this function, it will get true.
Parameters
[in] id The event to test for expiration.
Returns
true if the event has expired, false otherwise.
Implements ns3::SimulatorImpl.
Definition at line 596 of file distributed-simulator-impl.cc.
References m_currentTs, m_currentUid, and m_destroyEvents.
Referenced by Cancel(), GetDelayLeft(), and Remove().
IsFinished()
bool ns3::DistributedSimulatorImpl::IsFinished (void) const virtual
Check if the simulation should finish.
Reasons to finish are because there are no more events lefts to be scheduled, or if simulation time has already reached the "stop time" (see Simulator::Stop()).
Returns
true if no more events or stop time reached.
Implements ns3::SimulatorImpl.
Definition at line 330 of file distributed-simulator-impl.cc.
References m_globalFinished.
IsLocalFinished()
bool ns3::DistributedSimulatorImpl::IsLocalFinished (void) const private
Check if this rank is finished.
It's finished when there are no more events or stop has been requested.
Returns
true when this rank is finished.
Definition at line 336 of file distributed-simulator-impl.cc.
References m_events, and m_stop.
Referenced by NextTs(), and Run().
Next()
Time ns3::DistributedSimulatorImpl::Next (void) const private
Get the time of the next event, as returned by NextTs().
Returns
The next event time stamp.
Definition at line 358 of file distributed-simulator-impl.cc.
References NextTs().
Referenced by Run().
NextTs()
uint64_t ns3::DistributedSimulatorImpl::NextTs (void) const private
Get the timestep of the next event.
If there are no more events the timestep is infinity.
Returns
The next event timestep.
Definition at line 342 of file distributed-simulator-impl.cc.
References GetMaximumSimulationTime(), ns3::Time::GetTimeStep(), IsLocalFinished(), ns3::Scheduler::Event::key, m_events, and ns3::Scheduler::EventKey::m_ts.
Referenced by Next().
Now()
Time ns3::DistributedSimulatorImpl::Now (void) const virtual
Return the current simulation virtual time.
Returns
The current virtual time.
Implements ns3::SimulatorImpl.
Definition at line 535 of file distributed-simulator-impl.cc.
References m_currentTs.
ProcessOneEvent()
void ns3::DistributedSimulatorImpl::ProcessOneEvent (void) private
Process the next event.
Definition at line 311 of file distributed-simulator-impl.cc.
References ns3::Scheduler::Event::impl, ns3::EventImpl::Invoke(), ns3::Scheduler::Event::key, ns3::Scheduler::EventKey::m_context, m_currentContext, m_currentTs, m_currentUid, m_eventCount, m_events, ns3::Scheduler::EventKey::m_ts, ns3::Scheduler::EventKey::m_uid, m_unscheduledEvents, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, and ns3::SimpleRefCount< T, PARENT, DELETER >::Unref().
Referenced by Run().
Remove()
void ns3::DistributedSimulatorImpl::Remove (const EventId & id) virtual
Remove an event from the event list.
This method has the same visible effect as the ns3::EventId::Cancel method but its algorithmic complexity is much higher: it has often O(log(n)) complexity, sometimes O(n), sometimes worse. Note that it is not possible to remove events which were scheduled for the "destroy" time. Doing so will result in a program error (crash).
Parameters
[in] id The event to remove from the list of scheduled events.
Implements ns3::SimulatorImpl.
Definition at line 554 of file distributed-simulator-impl.cc.
References ns3::Scheduler::Event::impl, IsExpired(), m_destroyEvents, m_events, and m_unscheduledEvents.
Run()
void ns3::DistributedSimulatorImpl::Run (void) virtual
Run the simulation.
The simulation will run until one of:
No events are present anymore
The user called Simulator::Stop
The user called Simulator::Stop with a stop time and the expiration time of the next event to be processed is greater than or equal to the stop time.
Implements ns3::SimulatorImpl.
Definition at line 364 of file distributed-simulator-impl.cc.
References CalculateLookAhead(), ns3::MpiInterface::GetCommunicator(), GetMaximumSimulationTime(), ns3::LbtsMessage::GetRxCount(), ns3::GrantedTimeWindowMpiInterface::GetRxCount(), ns3::LbtsMessage::GetSmallestTime(), ns3::LbtsMessage::GetTxCount(), ns3::GrantedTimeWindowMpiInterface::GetTxCount(), ns3::LbtsMessage::IsFinished(), IsLocalFinished(), m_events, m_globalFinished, m_grantedTime, m_lookAhead, m_myId, m_pLBTS, m_stop, m_systemCount, m_unscheduledEvents, Next(), NS_ASSERT, NS_LOG_FUNCTION, ProcessOneEvent(), ns3::GrantedTimeWindowMpiInterface::ReceiveMessages(), and ns3::GrantedTimeWindowMpiInterface::TestSendComplete().
Schedule()
EventId ns3::DistributedSimulatorImpl::Schedule (Time const & delay, EventImpl * event) virtual
Schedule a future event execution (in the same context).
Parameters
[in] delay Delay until the event expires.
[in] event The event to schedule.
Returns
A unique identifier for the newly-scheduled event.
Implements ns3::SimulatorImpl.
Definition at line 473 of file distributed-simulator-impl.cc.
References GetContext(), ns3::Time::GetTimeStep(), ns3::Scheduler::Event::impl, ns3::Time::IsPositive(), ns3::Scheduler::Event::key, ns3::Scheduler::EventKey::m_context, m_currentTs, m_events, ns3::Scheduler::EventKey::m_ts, ns3::Scheduler::EventKey::m_uid, m_uid, m_unscheduledEvents, NS_ASSERT, and NS_LOG_FUNCTION.
ScheduleDestroy()
EventId ns3::DistributedSimulatorImpl::ScheduleDestroy (EventImpl * event) virtual
Schedule an event to run at the end of the simulation, after the Stop() time or condition has been reached.
Parameters
[in] event The event to schedule.
Returns
A unique identifier for the newly-scheduled event.
Implements ns3::SimulatorImpl.
Definition at line 524 of file distributed-simulator-impl.cc.
References m_currentTs, m_destroyEvents, m_uid, and NS_LOG_FUNCTION.
ScheduleNow()
EventId ns3::DistributedSimulatorImpl::ScheduleNow (EventImpl * event) virtual
Schedule an event to run at the current virtual time.
Parameters
[in] event The event to schedule.
Returns
A unique identifier for the newly-scheduled event.
Implements ns3::SimulatorImpl.
Definition at line 508 of file distributed-simulator-impl.cc.
References GetContext(), ns3::Scheduler::Event::impl, ns3::Scheduler::Event::key, ns3::Scheduler::EventKey::m_context, m_currentTs, m_events, ns3::Scheduler::EventKey::m_ts, ns3::Scheduler::EventKey::m_uid, m_uid, m_unscheduledEvents, and NS_LOG_FUNCTION.
ScheduleWithContext()
void ns3::DistributedSimulatorImpl::ScheduleWithContext (uint32_t context, Time const & delay, EventImpl * event) virtual
Schedule a future event execution (in a different context).
This method is thread-safe: it can be called from any thread.
Parameters
[in] delay Delay until the event expires.
[in] context Event context.
[in] event The event to schedule.
Returns
A unique identifier for the newly-scheduled event.
Implements ns3::SimulatorImpl.
Definition at line 493 of file distributed-simulator-impl.cc.
References ns3::Time::GetTimeStep(), ns3::Scheduler::Event::impl, ns3::Scheduler::Event::key, ns3::Scheduler::EventKey::m_context, m_currentTs, m_events, ns3::Scheduler::EventKey::m_ts, ns3::Scheduler::EventKey::m_uid, m_uid, m_unscheduledEvents, and NS_LOG_FUNCTION.
SetScheduler()
void ns3::DistributedSimulatorImpl::SetScheduler (ObjectFactory schedulerFactory) virtual
Set the Scheduler to be used to manage the event list.
Parameters
[in] schedulerFactory A new event scheduler factory.
The event scheduler can be set at any time: the events scheduled in the previous scheduler will be transferred to the new scheduler before we start to use it.
Implements ns3::SimulatorImpl.
Definition at line 293 of file distributed-simulator-impl.cc.
References ns3::ObjectFactory::Create(), m_events, and NS_LOG_FUNCTION.
Stop() [1/2]
void ns3::DistributedSimulatorImpl::Stop (Time const & delay) virtual
Schedule the time delay until the Simulator should stop.
Force the Simulator::Run method to return to the caller when the expiration time of the next event to be processed is greater than or equal to the stop time. The stop time is relative to the current simulation time.
Parameters
[in] delay The stop time, relative to the current time.
Implements ns3::SimulatorImpl.
Definition at line 462 of file distributed-simulator-impl.cc.
References ns3::Time::GetTimeStep(), NS_LOG_FUNCTION, ns3::Simulator::Schedule(), and ns3::Simulator::Stop().
Stop() [2/2]
void ns3::DistributedSimulatorImpl::Stop (void) virtual
Tell the Simulator the calling event should be the last one executed.
If a running event invokes this method, it will be the last event executed by the Simulator::Run method before returning to the caller.
Implements ns3::SimulatorImpl.
Definition at line 454 of file distributed-simulator-impl.cc.
References m_stop, and NS_LOG_FUNCTION.
Member Data Documentation
m_currentContext
uint32_t ns3::DistributedSimulatorImpl::m_currentContext private
Execution context of the current event.
Definition at line 214 of file distributed-simulator-impl.h.
Referenced by DistributedSimulatorImpl(), GetContext(), and ProcessOneEvent().
m_currentTs
uint64_t ns3::DistributedSimulatorImpl::m_currentTs private
Timestamp of the current event.
Definition at line 212 of file distributed-simulator-impl.h.
Referenced by DistributedSimulatorImpl(), GetDelayLeft(), IsExpired(), Now(), ProcessOneEvent(), Schedule(), ScheduleDestroy(), ScheduleNow(), and ScheduleWithContext().
m_currentUid
uint32_t ns3::DistributedSimulatorImpl::m_currentUid private
Unique id of the current event.
Definition at line 210 of file distributed-simulator-impl.h.
Referenced by DistributedSimulatorImpl(), IsExpired(), and ProcessOneEvent().
m_destroyEvents
DestroyEvents ns3::DistributedSimulatorImpl::m_destroyEvents private
The container of events to run at Destroy()
Definition at line 199 of file distributed-simulator-impl.h.
Referenced by Destroy(), IsExpired(), Remove(), and ScheduleDestroy().
m_eventCount
uint64_t ns3::DistributedSimulatorImpl::m_eventCount private
The event count.
Definition at line 216 of file distributed-simulator-impl.h.
Referenced by DistributedSimulatorImpl(), GetEventCount(), and ProcessOneEvent().
m_events
Ptr<Scheduler> ns3::DistributedSimulatorImpl::m_events private
The event priority queue.
Definition at line 205 of file distributed-simulator-impl.h.
Referenced by DistributedSimulatorImpl(), DoDispose(), IsLocalFinished(), NextTs(), ProcessOneEvent(), Remove(), Run(), Schedule(), ScheduleNow(), ScheduleWithContext(), and SetScheduler().
m_globalFinished
bool ns3::DistributedSimulatorImpl::m_globalFinished private
Are all parallel instances completed.
Definition at line 203 of file distributed-simulator-impl.h.
Referenced by DistributedSimulatorImpl(), IsFinished(), and Run().
m_grantedTime
Time ns3::DistributedSimulatorImpl::m_grantedTime private
End of current window.
Definition at line 230 of file distributed-simulator-impl.h.
Referenced by DistributedSimulatorImpl(), CalculateLookAhead(), and Run().
m_lookAhead
Time ns3::DistributedSimulatorImpl::m_lookAhead = Time::Max() static private
Current window size.
Initialize m_lookAhead to maximum, it will be constrained by user supplied time via BoundLookAhead and the minimum latency network between ranks.
Definition at line 231 of file distributed-simulator-impl.h.
Referenced by BoundLookAhead(), CalculateLookAhead(), and Run().
m_myId
uint32_t ns3::DistributedSimulatorImpl::m_myId private
MPI rank.
Definition at line 228 of file distributed-simulator-impl.h.
Referenced by DistributedSimulatorImpl(), GetSystemId(), and Run().
m_pLBTS
LbtsMessage* ns3::DistributedSimulatorImpl::m_pLBTS private
Container for Lbts messages, one per rank.
Allocated once we know how many systems there are.
Definition at line 227 of file distributed-simulator-impl.h.
Referenced by DistributedSimulatorImpl(), DoDispose(), and Run().
m_stop
bool ns3::DistributedSimulatorImpl::m_stop private
Flag calling for the end of the simulation.
Definition at line 201 of file distributed-simulator-impl.h.
Referenced by DistributedSimulatorImpl(), IsLocalFinished(), Run(), and Stop().
m_systemCount
uint32_t ns3::DistributedSimulatorImpl::m_systemCount private
MPI communicator size.
Definition at line 229 of file distributed-simulator-impl.h.
Referenced by DistributedSimulatorImpl(), and Run().
m_uid
uint32_t ns3::DistributedSimulatorImpl::m_uid private
Next event unique id.
Definition at line 208 of file distributed-simulator-impl.h.
Referenced by DistributedSimulatorImpl(), Schedule(), ScheduleDestroy(), ScheduleNow(), and ScheduleWithContext().
m_unscheduledEvents
int ns3::DistributedSimulatorImpl::m_unscheduledEvents private
Number of events that have been inserted but not yet scheduled, not counting the "destroy" events; this is used for validation.
Definition at line 221 of file distributed-simulator-impl.h.
Referenced by DistributedSimulatorImpl(), ProcessOneEvent(), Remove(), Run(), Schedule(), ScheduleNow(), and ScheduleWithContext().
The documentation for this class was generated from the following files:
src/mpi/model/distributed-simulator-impl.h
src/mpi/model/distributed-simulator-impl.cc