ns-3: ns3::flame::FlameProtocol Class Reference
ns3::flame::FlameProtocol Class Reference
Mesh Device » FLAME
FLAME routing protocol.
#include "flame-protocol.h"
Classes
struct Statistics
Statistics structure.
Public Member Functions
FlameProtocol ()
~FlameProtocol ()
void DoDispose ()
Destructor implementation.
Mac48Address GetAddress ()
Get address of this instance.
bool Install (Ptr< MeshPointDevice >)
Install FLAME on given mesh point.
bool RemoveRoutingStuff (uint32_t fromIface, const Mac48Address source, const Mac48Address destination, Ptr< Packet > packet, uint16_t &protocolType)
Cleanup flame headers!
void Report (std::ostream &os) const
Statistics.
bool RequestRoute (uint32_t sourceIface, const Mac48Address source, const Mac48Address destination, Ptr< const Packet > packet, uint16_t protocolType, RouteReplyCallback routeReply)
Route request, inherited from MeshL2RoutingProtocol.
void ResetStats ()
Reset statistics function.
Public Member Functions inherited from ns3::MeshL2RoutingProtocol
virtual ~MeshL2RoutingProtocol ()
virtual D-tor for subclasses
Ptr< MeshPointDevice > GetMeshPoint () const
Each mesh protocol must be installed on the mesh point to work.
void SetMeshPoint (Ptr< MeshPointDevice > mp)
Set host mesh point, analog of SetNode (...) methods for upper layer protocols.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::MeshL2RoutingProtocol
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
FlameProtocol (const FlameProtocol &)
type conversion operator
bool HandleDataFrame (uint16_t seqno, Mac48Address source, const FlameHeader flameHdr, Mac48Address receiver, uint32_t fromIface)
Handles a packet: adds a routing information and drops packets by TTL or Seqno.
FlameProtocol & operator= (const FlameProtocol &flame)
assignment operator
Private Attributes
Broadcast timers:
Time m_broadcastInterval
Max Cost value (or TTL, because cost is actually hopcount)
Time m_lastBroadcast
Max Cost value (or TTL, because cost is actually hopcount)
uint8_t m_maxCost
Max Cost value (or TTL, because cost is actually hopcount)
uint16_t m_myLastSeqno
Sequence number:
Ptr< FlameRtable > m_rtable
Routing table:
Statistics m_stats
statistics
Static Private Attributes
static const uint16_t FLAME_PROTOCOL = 0x4040
LLC protocol number reserved by flame.
Information about MeshPointDeviceaddress, plugins
typedef std::map< uint32_t, Ptr< FlameProtocolMac > > FlamePluginMap
interfaces
FlamePluginMap m_interfaces
interfaces
Mac48Address m_address
address
Additional Inherited Members
Public Types inherited from ns3::MeshL2RoutingProtocol
typedef Callback< void, bool, Ptr< Packet >, Mac48Address, Mac48Address, uint16_t, uint32_t > RouteReplyCallback
Callback to be invoked when route discovery procedure is completed.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::MeshL2RoutingProtocol
Ptr< MeshPointDevice > m_mp
Host mesh point.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
FLAME routing protocol.
Config Paths
ns3::flame::FlameProtocol is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::MeshPointDevice/RoutingProtocol/$ns3::flame::FlameProtocol"
Attributes
BroadcastInterval: How often we must send broadcast packets
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +5e+09ns
Flags: construct write read
MaxCost: Cost threshold after which packet will be dropped
Set with class: ns3::UintegerValue
Underlying type: uint8_t 3:255
Initial value: 32
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 120 bytes (on a 64-bit architecture).
Definition at line 88 of file flame-protocol.h.
Member Typedef Documentation
FlamePluginMap
typedef std::map<uint32_t, Ptr<FlameProtocolMac> > ns3::flame::FlameProtocol::FlamePluginMap private
interfaces
Definition at line 175 of file flame-protocol.h.
Constructor & Destructor Documentation
FlameProtocol() [1/2]
ns3::flame::FlameProtocol::FlameProtocol ()
Definition at line 135 of file flame-protocol.cc.
~FlameProtocol()
ns3::flame::FlameProtocol::~FlameProtocol ()
Definition at line 140 of file flame-protocol.cc.
FlameProtocol() [2/2]
ns3::flame::FlameProtocol::FlameProtocol (const FlameProtocol &) private
type conversion operator
Member Function Documentation
DoDispose()
void ns3::flame::FlameProtocol::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 144 of file flame-protocol.cc.
References m_interfaces, ns3::MeshL2RoutingProtocol::m_mp, and m_rtable.
GetAddress()
Mac48Address ns3::flame::FlameProtocol::GetAddress (void)
Get address of this instance.
Returns
the MAC address
Definition at line 326 of file flame-protocol.cc.
References m_address.
Referenced by HandleDataFrame(), RemoveRoutingStuff(), and RequestRoute().
GetTypeId()
TypeId ns3::flame::FlameProtocol::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 112 of file flame-protocol.cc.
References m_broadcastInterval, m_maxCost, ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeUintegerAccessor(), ns3::Seconds(), and ns3::TypeId::SetParent().
HandleDataFrame()
bool ns3::flame::FlameProtocol::HandleDataFrame (uint16_t seqno, Mac48Address source, const FlameHeader flameHdr, Mac48Address receiver, uint32_t fromIface) private
Handles a packet: adds a routing information and drops packets by TTL or Seqno.
Parameters
seqno
source
flameHdr
receiver
fromIface
Returns
true if packet shall be dropped
Definition at line 331 of file flame-protocol.cc.
References ns3::flame::FlameRtable::AddPath(), ns3::flame::FlameProtocol::Statistics::droppedTtl, GetAddress(), ns3::Mac48Address::GetBroadcast(), ns3::flame::FlameHeader::GetCost(), ns3::flame::FlameHeader::GetSeqno(), ns3::flame::FlameRtable::Lookup(), m_maxCost, m_rtable, m_stats, ns3::flame::FlameRtable::LookupResult::retransmitter, ns3::flame::FlameRtable::LookupResult::seqnum, and ns3::flame::FlameProtocol::Statistics::totalDropped.
Referenced by RemoveRoutingStuff(), and RequestRoute().
Install()
bool ns3::flame::FlameProtocol::Install (Ptr< MeshPointDevice > mp)
Install FLAME on given mesh point.
Returns
true if successful
Installing protocol causes installation of its interface MAC plugins.
Also MP aggregates all installed protocols, FLAME protocol can be accessed via MeshPointDevice::GetObject<flame::FlameProtocol>();
Definition at line 296 of file flame-protocol.cc.
References ns3::Mac48Address::ConvertFrom(), ns3::WifiNetDevice::GetIfIndex(), ns3::WifiNetDevice::GetMac(), ns3::Object::GetObject(), first::interfaces, m_address, m_interfaces, ns3::MeshL2RoutingProtocol::m_mp, and third::mac.
operator=()
FlameProtocol& ns3::flame::FlameProtocol::operator= (const FlameProtocol & flame) private
assignment operator
Parameters
flame the object to assign
Returns
the assigned value
RemoveRoutingStuff()
bool ns3::flame::FlameProtocol::RemoveRoutingStuff (uint32_t fromIface, const Mac48Address source, const Mac48Address destination, Ptr< Packet > packet, uint16_t & protocolType) virtual
Cleanup flame headers!
Parameters
fromIface the from interface
source the source address
destination the destination address
packet the packet
protocolType the protocol type
Returns
if the route removed
Implements ns3::MeshL2RoutingProtocol.
Definition at line 262 of file flame-protocol.cc.
References FLAME_PROTOCOL, GetAddress(), ns3::Mac48Address::GetBroadcast(), ns3::flame::FlameHeader::GetProtocol(), ns3::flame::FlameHeader::GetSeqno(), HandleDataFrame(), m_broadcastInterval, m_lastBroadcast, ns3::MeshL2RoutingProtocol::m_mp, ns3::Simulator::Now(), NS_ASSERT, NS_FATAL_ERROR, NS_LOG_DEBUG, ns3::Packet::RemoveHeader(), ns3::Packet::RemovePacketTag(), ns3::Seconds(), and ns3::flame::FlameTag::transmitter.
Report()
void ns3::flame::FlameProtocol::Report (std::ostream & os) const
Statistics.
Parameters
os the output stream
Definition at line 368 of file flame-protocol.cc.
References ns3::Time::GetSeconds(), m_address, m_broadcastInterval, m_interfaces, m_maxCost, m_stats, and ns3::flame::FlameProtocol::Statistics::Print().
RequestRoute()
bool ns3::flame::FlameProtocol::RequestRoute (uint32_t sourceIface, const Mac48Address source, const Mac48Address destination, Ptr< const Packet > packet, uint16_t protocolType, RouteReplyCallback routeReply) virtual
Route request, inherited from MeshL2RoutingProtocol.
Parameters
sourceIface the source interface
source the source address
destination the destination address
packet the packet to route
protocolType the protocol type
routeReply the route reply
Returns
if route exists
Implements ns3::MeshL2RoutingProtocol.
Definition at line 151 of file flame-protocol.cc.
References ns3::flame::FlameHeader::AddCost(), ns3::Packet::AddHeader(), ns3::Packet::AddPacketTag(), FLAME_PROTOCOL, GetAddress(), ns3::Mac48Address::GetBroadcast(), ns3::flame::FlameHeader::GetSeqno(), ns3::Packet::GetSize(), HandleDataFrame(), ns3::flame::FlameRtable::LookupResult::ifIndex, ns3::flame::FlameRtable::INTERFACE_ANY, ns3::flame::FlameRtable::Lookup(), m_broadcastInterval, m_lastBroadcast, ns3::MeshL2RoutingProtocol::m_mp, m_myLastSeqno, m_rtable, m_stats, ns3::Simulator::Now(), NS_ASSERT, NS_FATAL_ERROR, NS_LOG_DEBUG, ns3::Packet::PeekPacketTag(), ns3::flame::FlameTag::receiver, ns3::Packet::RemoveHeader(), ns3::Packet::RemovePacketTag(), ns3::flame::FlameRtable::LookupResult::retransmitter, ns3::flame::FlameHeader::SetOrigDst(), ns3::flame::FlameHeader::SetOrigSrc(), ns3::flame::FlameHeader::SetProtocol(), ns3::flame::FlameHeader::SetSeqno(), ns3::flame::FlameProtocol::Statistics::totalDropped, ns3::flame::FlameTag::transmitter, ns3::flame::FlameProtocol::Statistics::txBroadcast, ns3::flame::FlameProtocol::Statistics::txBytes, and ns3::flame::FlameProtocol::Statistics::txUnicast.
ResetStats()
void ns3::flame::FlameProtocol::ResetStats ()
Reset statistics function.
Definition at line 382 of file flame-protocol.cc.
References m_interfaces, and m_stats.
Member Data Documentation
FLAME_PROTOCOL
const uint16_t ns3::flame::FlameProtocol::FLAME_PROTOCOL = 0x4040 static private
LLC protocol number reserved by flame.
Definition at line 159 of file flame-protocol.h.
Referenced by RemoveRoutingStuff(), and RequestRoute().
m_address
Mac48Address ns3::flame::FlameProtocol::m_address private
address
Definition at line 177 of file flame-protocol.h.
Referenced by GetAddress(), Install(), and Report().
m_broadcastInterval
Time ns3::flame::FlameProtocol::m_broadcastInterval private
Max Cost value (or TTL, because cost is actually hopcount)
Definition at line 183 of file flame-protocol.h.
Referenced by GetTypeId(), RemoveRoutingStuff(), Report(), and RequestRoute().
m_interfaces
FlamePluginMap ns3::flame::FlameProtocol::m_interfaces private
interfaces
Definition at line 176 of file flame-protocol.h.
Referenced by DoDispose(), Install(), Report(), and ResetStats().
m_lastBroadcast
Time ns3::flame::FlameProtocol::m_lastBroadcast private
Max Cost value (or TTL, because cost is actually hopcount)
Definition at line 184 of file flame-protocol.h.
Referenced by RemoveRoutingStuff(), and RequestRoute().
m_maxCost
uint8_t ns3::flame::FlameProtocol::m_maxCost private
Max Cost value (or TTL, because cost is actually hopcount)
Definition at line 187 of file flame-protocol.h.
Referenced by GetTypeId(), HandleDataFrame(), and Report().
m_myLastSeqno
uint16_t ns3::flame::FlameProtocol::m_myLastSeqno private
Sequence number:
Definition at line 189 of file flame-protocol.h.
Referenced by RequestRoute().
m_rtable
Ptr<FlameRtable> ns3::flame::FlameProtocol::m_rtable private
Routing table:
Definition at line 191 of file flame-protocol.h.
Referenced by DoDispose(), HandleDataFrame(), and RequestRoute().
m_stats
Statistics ns3::flame::FlameProtocol::m_stats private
statistics
Definition at line 208 of file flame-protocol.h.
Referenced by HandleDataFrame(), Report(), RequestRoute(), and ResetStats().
The documentation for this class was generated from the following files:
src/mesh/model/flame/flame-protocol.h
src/mesh/model/flame/flame-protocol.cc