ns-3: ns3::LteRlcTm Class Reference
ns3::LteRlcTm Class Reference
LTE RLC Transparent Mode (TM), see 3GPP TS 36.322.
#include "lte-rlc-tm.h"
Classes
struct TxPdu
Store an incoming (from layer above us) PDU, waiting to transmit it.
Public Member Functions
LteRlcTm ()
virtual ~LteRlcTm ()
virtual void DoDispose ()
Destructor implementation.
virtual void DoNotifyHarqDeliveryFailure ()
Notify HARQ deliver failure.
virtual void DoNotifyTxOpportunity (LteMacSapUser::TxOpportunityParameters txOpParams)
MAC SAP.
virtual void DoReceivePdu (LteMacSapUser::ReceivePduParameters rxPduParams)
Receive PDU function.
virtual void DoTransmitPdcpPdu (Ptr< Packet > p)
RLC SAP.
Public Member Functions inherited from ns3::LteRlc
LteRlc ()
virtual ~LteRlc ()
LteMacSapUser * GetLteMacSapUser ()
LteRlcSapProvider * GetLteRlcSapProvider ()
void SetLcId (uint8_t lcId)
void SetLteMacSapProvider (LteMacSapProvider *s)
void SetLteRlcSapUser (LteRlcSapUser *s)
void SetRnti (uint16_t rnti)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::LteRlc
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void DoReportBufferStatus ()
Report buffer status.
void ExpireRbsTimer (void)
Expire RBS timer function.
Private Attributes
uint32_t m_maxTxBufferSize
maximum transmit buffer size
EventId m_rbsTimer
RBS timer.
std::vector< TxPdu > m_txBuffer
Transmission buffer.
uint32_t m_txBufferSize
transmit buffer size
Additional Inherited Members
Public Types inherited from ns3::LteRlc
typedef void(* NotifyTxTracedCallback) (uint16_t rnti, uint8_t lcid, uint32_t bytes)
TracedCallback signature for NotifyTxOpportunity events.
typedef void(* ReceiveTracedCallback) (uint16_t rnti, uint8_t lcid, uint32_t bytes, uint64_t delay)
TracedCallback signature for.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::LteRlc
uint8_t m_lcid
LCID.
LteMacSapProvider * m_macSapProvider
MAC SAP provider.
LteMacSapUser * m_macSapUser
MAC SAP user.
LteRlcSapProvider * m_rlcSapProvider
RLC SAP provider.
LteRlcSapUser * m_rlcSapUser
RLC SAP user.
uint16_t m_rnti
RNTI.
TracedCallback< uint16_t, uint8_t, uint32_t, uint64_t > m_rxPdu
Used to inform of a PDU reception from the MAC SAP user.
TracedCallback< uint16_t, uint8_t, uint32_t > m_txPdu
Used to inform of a PDU delivery to the MAC SAP provider.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
LTE RLC Transparent Mode (TM), see 3GPP TS 36.322.
Please note that, as in TM it is not possible to add any header, the delay measurements gathered from the trace source "RxPDU" of LteRlc are invalid (they will be always 0)
Config Paths
ns3::LteRlcTm is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteEnbNetDevice/LteEnbRrc/UeMap/[i]/DataRadioBearerMap/[i]/LteRlc/$ns3::LteRlcTm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteEnbNetDevice/LteEnbRrc/UeMap/[i]/Srb0/LteRlc/$ns3::LteRlcTm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteEnbNetDevice/LteEnbRrc/UeMap/[i]/Srb1/LteRlc/$ns3::LteRlcTm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteUeNetDevice/LteUeRrc/DataRadioBearerMap/[i]/LteRlc/$ns3::LteRlcTm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteUeNetDevice/LteUeRrc/Srb0/LteRlc/$ns3::LteRlcTm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteUeNetDevice/LteUeRrc/Srb1/LteRlc/$ns3::LteRlcTm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteEnbNetDevice/LteEnbRrc/UeMap/[i]/DataRadioBearerMap/[i]/LteRlc/$ns3::LteRlcTm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteEnbNetDevice/LteEnbRrc/UeMap/[i]/Srb0/LteRlc/$ns3::LteRlcTm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteEnbNetDevice/LteEnbRrc/UeMap/[i]/Srb1/LteRlc/$ns3::LteRlcTm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteUeNetDevice/LteUeRrc/DataRadioBearerMap/[i]/LteRlc/$ns3::LteRlcTm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteUeNetDevice/LteUeRrc/Srb0/LteRlc/$ns3::LteRlcTm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteUeNetDevice/LteUeRrc/Srb1/LteRlc/$ns3::LteRlcTm"
Attributes
MaxTxBufferSize: Maximum Size of the Transmission Buffer (in Bytes)
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 2097152
Flags: construct write read
No TraceSources are defined for this type.
TraceSources defined in parent class ns3::LteRlc
TxPDU: PDU transmission notified to the MAC.
Callback signature: ns3::LteRlc::NotifyTxTracedCallback
RxPDU: PDU received.
Callback signature: ns3::LteRlc::ReceiveTracedCallback
Size of this type is 176 bytes (on a 64-bit architecture).
Definition at line 39 of file lte-rlc-tm.h.
Constructor & Destructor Documentation
LteRlcTm()
ns3::LteRlcTm::LteRlcTm ()
Definition at line 33 of file lte-rlc-tm.cc.
References NS_LOG_FUNCTION.
~LteRlcTm()
ns3::LteRlcTm::~LteRlcTm () virtual
Definition at line 40 of file lte-rlc-tm.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::LteRlcTm::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::LteRlc.
Definition at line 62 of file lte-rlc-tm.cc.
References ns3::EventId::Cancel(), ns3::LteRlc::DoDispose(), m_rbsTimer, m_txBuffer, and NS_LOG_FUNCTION.
DoNotifyHarqDeliveryFailure()
void ns3::LteRlcTm::DoNotifyHarqDeliveryFailure () virtual
Notify HARQ deliver failure.
Implements ns3::LteRlc.
Definition at line 158 of file lte-rlc-tm.cc.
References NS_LOG_FUNCTION.
DoNotifyTxOpportunity()
void ns3::LteRlcTm::DoNotifyTxOpportunity (LteMacSapUser::TxOpportunityParameters txOpParams) virtual
MAC SAP.
Parameters
txOpParams the LteMacSapUser::TxOpportunityParameters
Implements ns3::LteRlc.
Definition at line 109 of file lte-rlc-tm.cc.
References ns3::LteMacSapUser::TxOpportunityParameters::bytes, ns3::EventId::Cancel(), ns3::LteMacSapProvider::TransmitPduParameters::componentCarrierId, ns3::LteMacSapUser::TxOpportunityParameters::componentCarrierId, ExpireRbsTimer(), ns3::Packet::GetSize(), ns3::LteMacSapUser::TxOpportunityParameters::harqId, ns3::LteMacSapProvider::TransmitPduParameters::harqProcessId, ns3::LteMacSapProvider::TransmitPduParameters::layer, ns3::LteMacSapUser::TxOpportunityParameters::layer, ns3::LteMacSapProvider::TransmitPduParameters::lcid, ns3::LteRlc::m_lcid, ns3::LteRlc::m_macSapProvider, m_rbsTimer, ns3::LteRlc::m_rnti, m_txBuffer, m_txBufferSize, ns3::LteRlc::m_txPdu, ns3::MilliSeconds(), NS_LOG_FUNCTION, NS_LOG_LOGIC, NS_LOG_WARN, ns3::LteMacSapProvider::TransmitPduParameters::pdu, ns3::LteMacSapProvider::TransmitPduParameters::rnti, ns3::Simulator::Schedule(), and ns3::LteMacSapProvider::TransmitPdu().
DoReceivePdu()
void ns3::LteRlcTm::DoReceivePdu (LteMacSapUser::ReceivePduParameters params) virtual
Receive PDU function.
Parameters
params the LteMacSapUser::ReceivePduParameters
Implements ns3::LteRlc.
Definition at line 164 of file lte-rlc-tm.cc.
References ns3::Packet::GetSize(), ns3::LteRlc::m_lcid, ns3::LteRlc::m_rlcSapUser, ns3::LteRlc::m_rnti, ns3::LteRlc::m_rxPdu, NS_LOG_FUNCTION, ns3::LteMacSapUser::ReceivePduParameters::p, and ns3::LteRlcSapUser::ReceivePdcpPdu().
DoReportBufferStatus()
void ns3::LteRlcTm::DoReportBufferStatus (void) private
Report buffer status.
Definition at line 180 of file lte-rlc-tm.cc.
References ns3::Time::GetMilliSeconds(), ns3::LteMacSapProvider::ReportBufferStatusParameters::lcid, ns3::LteRlc::m_lcid, ns3::LteRlc::m_macSapProvider, ns3::LteRlc::m_rnti, m_txBuffer, m_txBufferSize, ns3::Simulator::Now(), NS_LOG_LOGIC, ns3::LteMacSapProvider::ReportBufferStatus(), ns3::LteMacSapProvider::ReportBufferStatusParameters::retxQueueHolDelay, ns3::LteMacSapProvider::ReportBufferStatusParameters::retxQueueSize, ns3::LteMacSapProvider::ReportBufferStatusParameters::rnti, ns3::LteMacSapProvider::ReportBufferStatusParameters::statusPduSize, ns3::LteMacSapProvider::ReportBufferStatusParameters::txQueueHolDelay, and ns3::LteMacSapProvider::ReportBufferStatusParameters::txQueueSize.
Referenced by DoTransmitPdcpPdu(), and ExpireRbsTimer().
DoTransmitPdcpPdu()
void ns3::LteRlcTm::DoTransmitPdcpPdu (Ptr< Packet > p) virtual
RLC SAP.
Parameters
p packet
Report Buffer Status
Implements ns3::LteRlc.
Definition at line 77 of file lte-rlc-tm.cc.
References ns3::EventId::Cancel(), DoReportBufferStatus(), ns3::Packet::GetSize(), ns3::LteRlc::m_lcid, m_maxTxBufferSize, m_rbsTimer, ns3::LteRlc::m_rnti, m_txBuffer, m_txBufferSize, ns3::Simulator::Now(), NS_LOG_FUNCTION, and NS_LOG_LOGIC.
ExpireRbsTimer()
void ns3::LteRlcTm::ExpireRbsTimer (void) private
Expire RBS timer function.
Definition at line 206 of file lte-rlc-tm.cc.
References DoReportBufferStatus(), m_rbsTimer, m_txBuffer, ns3::MilliSeconds(), NS_LOG_LOGIC, and ns3::Simulator::Schedule().
Referenced by DoNotifyTxOpportunity().
GetTypeId()
TypeId ns3::LteRlcTm::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 46 of file lte-rlc-tm.cc.
References m_maxTxBufferSize, ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
Member Data Documentation
m_maxTxBufferSize
uint32_t ns3::LteRlcTm::m_maxTxBufferSize private
maximum transmit buffer size
Definition at line 100 of file lte-rlc-tm.h.
Referenced by DoTransmitPdcpPdu(), and GetTypeId().
m_rbsTimer
EventId ns3::LteRlcTm::m_rbsTimer private
RBS timer.
Definition at line 103 of file lte-rlc-tm.h.
Referenced by DoDispose(), DoNotifyTxOpportunity(), DoTransmitPdcpPdu(), and ExpireRbsTimer().
m_txBuffer
std::vector< TxPdu > ns3::LteRlcTm::m_txBuffer private
Transmission buffer.
Definition at line 98 of file lte-rlc-tm.h.
Referenced by DoDispose(), DoNotifyTxOpportunity(), DoReportBufferStatus(), DoTransmitPdcpPdu(), and ExpireRbsTimer().
m_txBufferSize
uint32_t ns3::LteRlcTm::m_txBufferSize private
transmit buffer size
Definition at line 101 of file lte-rlc-tm.h.
Referenced by DoNotifyTxOpportunity(), DoReportBufferStatus(), and DoTransmitPdcpPdu().
The documentation for this class was generated from the following files:
src/lte/model/lte-rlc-tm.h
src/lte/model/lte-rlc-tm.cc