ns-3: LteHandoverDelayTestCase Class Reference
LteHandoverDelayTestCase Class Reference
LTE Models » lte module tests | Test suites
Verifying that the time needed for handover is under a specified threshold.
Public Member Functions
LteHandoverDelayTestCase (uint8_t numberOfComponentCarriers, bool useIdealRrc, Time handoverTime, Time delayThreshold, Time simulationDuration)
Constructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void EnbHandoverEndOkCallback (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
ENB handover end OK callback function.
void EnbHandoverStartCallback (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti, uint16_t targetCellId)
ENB handover start callback function.
void UeHandoverEndOkCallback (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
UE handover end OK callback function.
void UeHandoverStartCallback (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti, uint16_t targetCellId)
UE handover start callback function.
Private Attributes
Time m_delayThreshold
the delay threshold
Time m_enbHandoverStart
ENB handover start time.
Time m_handoverTime
handover time
uint8_t m_numberOfComponentCarriers
Number of component carriers.
Time m_simulationDuration
the simulation duration
Time m_ueHandoverStart
UE handover start time.
bool m_useIdealRrc
use ideal RRC?
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Verifying that the time needed for handover is under a specified threshold.
Definition at line 60 of file test-lte-handover-delay.cc.
Constructor & Destructor Documentation
LteHandoverDelayTestCase()
LteHandoverDelayTestCase::LteHandoverDelayTestCase (uint8_t numberOfComponentCarriers, bool useIdealRrc, Time handoverTime, Time delayThreshold, Time simulationDuration) inline
Constructor.
Parameters
numberOfComponentCarriers number of component carriers
useIdealRrc if true, use the ideal RRC
handoverTime the time of handover
delayThreshold the delay threshold
simulationDuration duration of the simulation
Definition at line 72 of file test-lte-handover-delay.cc.
Member Function Documentation
DoRun()
void LteHandoverDelayTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 138 of file test-lte-handover-delay.cc.
References ns3::Config::Connect(), ns3::NodeContainer::Create(), ns3::Simulator::Destroy(), EnbHandoverEndOkCallback(), EnbHandoverStartCallback(), ns3::MobilityHelper::Install(), ns3::InternetStackHelper::Install(), ns3::MakeCallback(), NS_LOG_INFO, ns3::Simulator::Run(), ns3::Time::S, ns3::MobilityHelper::SetMobilityModel(), ns3::MobilityHelper::SetPositionAllocator(), ns3::Simulator::Stop(), UeHandoverEndOkCallback(), and UeHandoverStartCallback().
EnbHandoverEndOkCallback()
void LteHandoverDelayTestCase::EnbHandoverEndOkCallback (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti) private
ENB handover end OK callback function.
Parameters
context the context string
imsi the IMSI
cellid the cell ID
rnti the RNTI
Definition at line 256 of file test-lte-handover-delay.cc.
References ns3::Time::As(), ns3::Simulator::Now(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_TEST_ASSERT_MSG_LT, ns3::Time::S, and ns3::Seconds().
Referenced by DoRun().
EnbHandoverStartCallback()
void LteHandoverDelayTestCase::EnbHandoverStartCallback (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti, uint16_t targetCellId) private
ENB handover start callback function.
Parameters
context the context string
imsi the IMSI
cellid the cell ID
rnti the RNTI
targetCellId the target cell ID
Definition at line 248 of file test-lte-handover-delay.cc.
References ns3::Simulator::Now(), and NS_LOG_FUNCTION.
Referenced by DoRun().
UeHandoverEndOkCallback()
void LteHandoverDelayTestCase::UeHandoverEndOkCallback (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti) private
UE handover end OK callback function.
Parameters
context the context string
imsi the IMSI
cellid the cell ID
rnti the RNTI
Definition at line 232 of file test-lte-handover-delay.cc.
References ns3::Time::As(), ns3::Simulator::Now(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_TEST_ASSERT_MSG_LT, ns3::Time::S, and ns3::Seconds().
Referenced by DoRun().
UeHandoverStartCallback()
void LteHandoverDelayTestCase::UeHandoverStartCallback (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti, uint16_t targetCellId) private
UE handover start callback function.
Parameters
context the context string
imsi the IMSI
cellid the cell ID
rnti the RNTI
targetCellId the target cell ID
Definition at line 224 of file test-lte-handover-delay.cc.
References ns3::Simulator::Now(), and NS_LOG_FUNCTION.
Referenced by DoRun().
Member Data Documentation
m_delayThreshold
Time LteHandoverDelayTestCase::m_delayThreshold private
the delay threshold
Definition at line 129 of file test-lte-handover-delay.cc.
m_enbHandoverStart
Time LteHandoverDelayTestCase::m_enbHandoverStart private
ENB handover start time.
Definition at line 133 of file test-lte-handover-delay.cc.
m_handoverTime
Time LteHandoverDelayTestCase::m_handoverTime private
handover time
Definition at line 128 of file test-lte-handover-delay.cc.
m_numberOfComponentCarriers
uint8_t LteHandoverDelayTestCase::m_numberOfComponentCarriers private
Number of component carriers.
Definition at line 126 of file test-lte-handover-delay.cc.
m_simulationDuration
Time LteHandoverDelayTestCase::m_simulationDuration private
the simulation duration
Definition at line 130 of file test-lte-handover-delay.cc.
m_ueHandoverStart
Time LteHandoverDelayTestCase::m_ueHandoverStart private
UE handover start time.
Definition at line 132 of file test-lte-handover-delay.cc.
m_useIdealRrc
bool LteHandoverDelayTestCase::m_useIdealRrc private
use ideal RRC?
Definition at line 127 of file test-lte-handover-delay.cc.
The documentation for this class was generated from the following file:
src/lte/test/test-lte-handover-delay.cc