ns-3: PacketTest Class Reference
PacketTest Class Reference
Network » Network module unit tests | Test suites
Packet unit tests.
Public Member Functions
PacketTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void DoCheck (Ptr< const Packet > p, const char *file, int line, uint32_t n,...)
Checks the packet.
void DoCheckData (Ptr< const Packet > p, const char *file, int line, uint32_t n,...)
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Packet unit tests.
Definition at line 437 of file packet-test-suite.cc.
Constructor & Destructor Documentation
PacketTest()
PacketTest::PacketTest ()
Definition at line 456 of file packet-test-suite.cc.
Member Function Documentation
DoCheck()
void PacketTest::DoCheck (Ptr< const Packet > p, const char * file, int line, uint32_t n, ...) private
Checks the packet.
Parameters
p The packet
file The file name
line The line number
n The number of variable arguments
... The variable arguments
Definition at line 461 of file packet-test-suite.cc.
References create-module::file, ns3::TypeId::GetConstructor(), ns3::ByteTagIterator::Item::GetEnd(), ns3::TypeId::GetName(), ns3::ByteTagIterator::Item::GetStart(), ns3::ByteTagIterator::Item::GetTag(), ns3::ByteTagIterator::Item::GetTypeId(), ns3::ByteTagIterator::HasNext(), sample-rng-plot::n, ns3::ByteTagIterator::Next(), NS_TEST_EXPECT_MSG_EQ, NS_TEST_EXPECT_MSG_EQ_INTERNAL, NS_TEST_EXPECT_MSG_NE, and visualizer.core::start().
DoCheckData()
void PacketTest::DoCheckData (Ptr< const Packet > p, const char * file, int line, uint32_t n, ...) private
Definition at line 498 of file packet-test-suite.cc.
References data, create-module::file, ns3::TypeId::GetConstructor(), ns3::ByteTagIterator::Item::GetEnd(), ns3::TypeId::GetName(), ns3::ByteTagIterator::Item::GetStart(), ns3::ByteTagIterator::Item::GetTag(), ns3::ByteTagIterator::Item::GetTypeId(), ns3::ByteTagIterator::HasNext(), sample-rng-plot::n, ns3::ByteTagIterator::Next(), NS_TEST_EXPECT_MSG_EQ, NS_TEST_EXPECT_MSG_EQ_INTERNAL, NS_TEST_EXPECT_MSG_NE, and visualizer.core::start().
DoRun()
void PacketTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Internal:
See Bug 572
Implements ns3::TestCase.
Definition at line 537 of file packet-test-suite.cc.
References ns3::Packet::AddAtEnd(), ns3::Packet::AddByteTag(), ns3::Packet::AddHeader(), ns3::Packet::AddPacketTag(), ns3::Packet::AddPaddingAtEnd(), ns3::Packet::AddTrailer(), CHECK, CHECK_DATA, ns3::Packet::CopyData(), E, E_DATA, ns3::Packet::GetSerializedSize(), ns3::Packet::GetSize(), NS_TEST_EXPECT_MSG_EQ, ns3::Packet::PeekPacketTag(), ns3::Packet::RemoveAllPacketTags(), ns3::Packet::RemoveAtEnd(), ns3::Packet::RemoveAtStart(), ns3::Packet::RemoveHeader(), ns3::Packet::RemovePacketTag(), ns3::Packet::RemoveTrailer(), and ns3::Packet::Serialize().
The documentation for this class was generated from the following file:
src/network/test/packet-test-suite.cc