ns-3: ns3::RipNgRte Class Reference
ns3::RipNgRte Class Reference
Internet » IPv6 Routing Protocols. » RIPng
RipNg Routing Table Entry (RTE) - see RFC 2080
#include "ripng-header.h"
Public Member Functions
RipNgRte (void)
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
virtual TypeId GetInstanceTypeId (void) const
Return the instance type identifier.
Ipv6Address GetPrefix (void) const
Get the prefix.
uint8_t GetPrefixLen (void) const
Get the prefix length.
uint8_t GetRouteMetric (void) const
Get the route metric.
uint16_t GetRouteTag (void) const
Get the route tag.
virtual uint32_t GetSerializedSize (void) const
Get the serialized size of the packet.
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetPrefix (Ipv6Address prefix)
Set the prefix.
void SetPrefixLen (uint8_t prefixLen)
Set the prefix length.
void SetRouteMetric (uint8_t routeMetric)
Set the route metric.
void SetRouteTag (uint16_t routeTag)
Set the route tag.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_metric
route metric
Ipv6Address m_prefix
prefix
uint8_t m_prefixLen
prefix length
uint16_t m_tag
route tag
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
RipNg Routing Table Entry (RTE) - see RFC 2080
Introspection did not find any typical Config paths.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 32 bytes (on a 64-bit architecture).
Definition at line 38 of file ripng-header.h.
Constructor & Destructor Documentation
RipNgRte()
ns3::RipNgRte::RipNgRte (void)
Definition at line 31 of file ripng-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::RipNgRte::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start Buffer iterator
Returns
size of the packet
Implements ns3::Header.
Definition at line 72 of file ripng-header.cc.
References GetSerializedSize(), m_metric, m_prefix, m_prefixLen, m_tag, ns3::Buffer::Iterator::Read(), ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadU8(), and ns3::Ipv6Address::Set().
Referenced by ns3::RipNgHeader::Deserialize().
GetInstanceTypeId()
TypeId ns3::RipNgRte::GetInstanceTypeId (void) const virtual
Return the instance type identifier.
Returns
instance type ID
Implements ns3::ObjectBase.
Definition at line 45 of file ripng-header.cc.
References GetTypeId().
GetPrefix()
Ipv6Address ns3::RipNgRte::GetPrefix (void) const
Get the prefix.
Returns
the prefix
Definition at line 90 of file ripng-header.cc.
References m_prefix.
GetPrefixLen()
uint8_t ns3::RipNgRte::GetPrefixLen (void) const
Get the prefix length.
Returns
the prefix length
Definition at line 100 of file ripng-header.cc.
References m_prefixLen.
GetRouteMetric()
uint8_t ns3::RipNgRte::GetRouteMetric (void) const
Get the route metric.
Returns
the route metric
Definition at line 120 of file ripng-header.cc.
References m_metric.
GetRouteTag()
uint16_t ns3::RipNgRte::GetRouteTag (void) const
Get the route tag.
Returns
the route tag
Definition at line 110 of file ripng-header.cc.
References m_tag.
GetSerializedSize()
uint32_t ns3::RipNgRte::GetSerializedSize (void) const virtual
Get the serialized size of the packet.
Returns
size
Implements ns3::Header.
Definition at line 55 of file ripng-header.cc.
Referenced by Deserialize(), ns3::RipNg::DoSendRouteUpdate(), ns3::RipNgHeader::GetSerializedSize(), and ns3::RipNg::HandleRequests().
GetTypeId()
TypeId ns3::RipNgRte::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 36 of file ripng-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::RipNgRte::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 50 of file ripng-header.cc.
References m_metric, m_prefix, m_prefixLen, and m_tag.
Referenced by ns3::operator<<().
Serialize()
void ns3::RipNgRte::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start Buffer iterator
Implements ns3::Header.
Definition at line 60 of file ripng-header.cc.
References m_metric, m_prefix, m_prefixLen, m_tag, ns3::Ipv6Address::Serialize(), ns3::Buffer::Iterator::Write(), ns3::Buffer::Iterator::WriteHtonU16(), and ns3::Buffer::Iterator::WriteU8().
SetPrefix()
void ns3::RipNgRte::SetPrefix (Ipv6Address prefix)
Set the prefix.
Parameters
prefix the prefix
Definition at line 85 of file ripng-header.cc.
References m_prefix.
Referenced by ns3::RipNg::DoSendRouteUpdate(), ns3::RipNg::HandleRequests(), and ns3::RipNg::SendRouteRequest().
SetPrefixLen()
void ns3::RipNgRte::SetPrefixLen (uint8_t prefixLen)
Set the prefix length.
Parameters
prefixLen the prefix length
Definition at line 95 of file ripng-header.cc.
References m_prefixLen.
Referenced by ns3::RipNg::DoSendRouteUpdate(), ns3::RipNg::HandleRequests(), and ns3::RipNg::SendRouteRequest().
SetRouteMetric()
void ns3::RipNgRte::SetRouteMetric (uint8_t routeMetric)
Set the route metric.
Parameters
routeMetric the route metric
Definition at line 115 of file ripng-header.cc.
References m_metric.
Referenced by ns3::RipNg::DoSendRouteUpdate(), ns3::RipNg::HandleRequests(), and ns3::RipNg::SendRouteRequest().
SetRouteTag()
void ns3::RipNgRte::SetRouteTag (uint16_t routeTag)
Set the route tag.
Parameters
routeTag the route tag
Definition at line 105 of file ripng-header.cc.
References m_tag.
Referenced by ns3::RipNg::DoSendRouteUpdate(), and ns3::RipNg::HandleRequests().
Member Data Documentation
m_metric
uint8_t ns3::RipNgRte::m_metric private
route metric
Definition at line 129 of file ripng-header.h.
Referenced by Deserialize(), GetRouteMetric(), Print(), Serialize(), and SetRouteMetric().
m_prefix
Ipv6Address ns3::RipNgRte::m_prefix private
prefix
Definition at line 126 of file ripng-header.h.
Referenced by Deserialize(), GetPrefix(), Print(), Serialize(), and SetPrefix().
m_prefixLen
uint8_t ns3::RipNgRte::m_prefixLen private
prefix length
Definition at line 128 of file ripng-header.h.
Referenced by Deserialize(), GetPrefixLen(), Print(), Serialize(), and SetPrefixLen().
m_tag
uint16_t ns3::RipNgRte::m_tag private
route tag
Definition at line 127 of file ripng-header.h.
Referenced by Deserialize(), GetRouteTag(), Print(), Serialize(), and SetRouteTag().
The documentation for this class was generated from the following files:
src/internet/model/ripng-header.h
src/internet/model/ripng-header.cc