ns-3: ns3::Ipv6L3Protocol Class Reference
ns3::Ipv6L3Protocol Class Reference
Internet » IPv6 classes and sub-modules
IPv6 layer implementation.
#include "ipv6-l3-protocol.h"
Public Types
enum DropReason {
DROP_TTL_EXPIRED = 1 , DROP_NO_ROUTE , DROP_INTERFACE_DOWN , DROP_ROUTE_ERROR ,
DROP_UNKNOWN_PROTOCOL , DROP_UNKNOWN_OPTION , DROP_MALFORMED_HEADER , DROP_FRAGMENT_TIMEOUT
}
Reason why a packet has been dropped.
typedef void(* DropTracedCallback) (const Ipv6Header &header, Ptr< const Packet > packet, DropReason reason, Ptr< Ipv6 > ipv6, uint32_t interface)
TracedCallback signature for packet drop events.
typedef void(* SentTracedCallback) (const Ipv6Header &header, Ptr< const Packet > packet, uint32_t interface)
TracedCallback signature for packet sent, forwarded or local-delivered events.
typedef void(* TxRxTracedCallback) (Ptr< const Packet > packet, Ptr< Ipv6 > ipv6, uint32_t interface)
TracedCallback signature for packet transmission or reception events.
Public Member Functions
Ipv6L3Protocol ()
Constructor.
virtual ~Ipv6L3Protocol ()
Destructor.
bool AddAddress (uint32_t i, Ipv6InterfaceAddress address)
Add an address on interface.
void AddAutoconfiguredAddress (uint32_t interface, Ipv6Address network, Ipv6Prefix mask, uint8_t flags, uint32_t validTime, uint32_t preferredTime, Ipv6Address defaultRouter=Ipv6Address::GetZero())
Add an autoconfigured address with RA information.
uint32_t AddInterface (Ptr< NetDevice > device)
Add IPv6 interface for a device.
void AddMulticastAddress (Ipv6Address address)
Adds a multicast address to the list of addresses to pass to local deliver.
void AddMulticastAddress (Ipv6Address address, uint32_t interface)
Adds a multicast address to the list of addresses to pass to local deliver.
Ptr< Socket > CreateRawSocket ()
Create raw IPv6 socket.
void DeleteRawSocket (Ptr< Socket > socket)
Remove raw IPv6 socket.
Ipv6InterfaceAddress GetAddress (uint32_t interfaceIndex, uint32_t addressIndex) const
Get an address.
Ptr< Icmpv6L4Protocol > GetIcmpv6 () const
Get ICMPv6 protocol.
Ptr< Ipv6Interface > GetInterface (uint32_t i) const
Get an interface.
int32_t GetInterfaceForAddress (Ipv6Address addr) const
Get interface index which has specified IPv6 address.
int32_t GetInterfaceForDevice (Ptr< const NetDevice > device) const
Get interface index which is on a specified net device.
int32_t GetInterfaceForPrefix (Ipv6Address addr, Ipv6Prefix mask) const
Get interface index which match specified address/prefix.
uint16_t GetMetric (uint32_t i) const
Get metric for an interface.
uint16_t GetMtu (uint32_t i) const
Get MTU for an interface.
uint32_t GetNAddresses (uint32_t interface) const
Get number of address for an interface.
Ptr< NetDevice > GetNetDevice (uint32_t i)
Get device by index.
uint32_t GetNInterfaces () const
Get current number of interface on this stack.
virtual Ptr< IpL4Protocol > GetProtocol (int protocolNumber) const
Get L4 protocol by protocol number.
virtual Ptr< IpL4Protocol > GetProtocol (int protocolNumber, int32_t interfaceIndex) const
Get L4 protocol by protocol number for the specified interface.
Ptr< Ipv6RoutingProtocol > GetRoutingProtocol () const
Get current routing protocol used.
virtual void Insert (Ptr< IpL4Protocol > protocol)
Add a L4 protocol.
virtual void Insert (Ptr< IpL4Protocol > protocol, uint32_t interfaceIndex)
Add a L4 protocol to a specific interface.
bool IsForwarding (uint32_t i) const
Is interface allows forwarding ?
bool IsRegisteredMulticastAddress (Ipv6Address address) const
Checks if the address has been registered.
bool IsRegisteredMulticastAddress (Ipv6Address address, uint32_t interface) const
Checks if the address has been registered for a specific interface.
bool IsUp (uint32_t i) const
Is specified interface up ?
void Receive (Ptr< NetDevice > device, Ptr< const Packet > p, uint16_t protocol, const Address &from, const Address &to, NetDevice::PacketType packetType)
Receive method when a packet arrive in the stack.
virtual void RegisterExtensions ()
Register the IPv6 Extensions.
virtual void RegisterOptions ()
Register the IPv6 Options.
virtual void Remove (Ptr< IpL4Protocol > protocol)
Remove a L4 protocol.
virtual void Remove (Ptr< IpL4Protocol > protocol, uint32_t interfaceIndex)
Remove a L4 protocol from a specific interface.
bool RemoveAddress (uint32_t interfaceIndex, Ipv6Address address)
Remove a specified Ipv6 address from an interface.
bool RemoveAddress (uint32_t interfaceIndex, uint32_t addressIndex)
Remove an address from an interface.
void RemoveAutoconfiguredAddress (uint32_t interface, Ipv6Address network, Ipv6Prefix mask, Ipv6Address defaultRouter)
Remove an autoconfigured address.
void RemoveMulticastAddress (Ipv6Address address)
Removes a multicast address from the list of addresses to pass to local deliver.
void RemoveMulticastAddress (Ipv6Address address, uint32_t interface)
Removes a multicast address from the list of addresses to pass to local deliver.
virtual void ReportDrop (Ipv6Header ipHeader, Ptr< Packet > p, DropReason dropReason)
Report a packet drop.
virtual void Send (Ptr< Packet > packet, Ipv6Address source, Ipv6Address destination, uint8_t protocol, Ptr< Ipv6Route > route)
Higher-level layers call this method to send a packet down the stack to the MAC and PHY layers.
void SetDefaultTclass (uint8_t tclass)
Set the default TCLASS.
void SetDefaultTtl (uint8_t ttl)
Set the default TTL.
void SetDown (uint32_t i)
set an interface down.
void SetForwarding (uint32_t i, bool val)
Enable or disable forwarding on interface.
void SetMetric (uint32_t i, uint16_t metric)
Set metric for an interface.
void SetNode (Ptr< Node > node)
Set node associated with this stack.
virtual void SetPmtu (Ipv6Address dst, uint32_t pmtu)
Set the Path MTU for the specified IPv6 destination address.
void SetRoutingProtocol (Ptr< Ipv6RoutingProtocol > routingProtocol)
Set routing protocol for this stack.
void SetUp (uint32_t i)
Set an interface up.
Ipv6Address SourceAddressSelection (uint32_t interface, Ipv6Address dest)
Choose the source address to use with destination address.
Public Member Functions inherited from ns3::Ipv6
Ipv6 ()
Constructor.
virtual ~Ipv6 ()
Destructor.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID of this class.
Static Public Member Functions inherited from ns3::Ipv6
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static const uint16_t PROT_NUMBER = 0x86DD
The protocol number for IPv6 (0x86DD).
Static Public Attributes inherited from ns3::Ipv6
static const uint32_t IF_ANY = 0xffffffff
Any interface magic number.
Protected Member Functions
virtual void DoDispose ()
Dispose object.
virtual void NotifyNewAggregate ()
Notify other components connected to the node that a new stack member is now connected.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
typedef std::list< Ptr< Ipv6AutoconfiguredPrefix > > Ipv6AutoconfiguredPrefixList
Container of the IPv6 Autoconfigured addresses.
typedef std::list< Ptr< Ipv6AutoconfiguredPrefix > >::iterator Ipv6AutoconfiguredPrefixListI
Iterator of the container of the IPv6 Autoconfigured addresses.
typedef std::vector< Ptr< Ipv6Interface > > Ipv6InterfaceList
Container of the IPv6 Interfaces.
typedef std::map< Ptr< const NetDevice >, uint32_t > Ipv6InterfaceReverseContainer
Container of NetDevices registered to IPv6 and their interface indexes.
typedef std::map< Ipv6RegisteredMulticastAddressKey_t, uint32_t > Ipv6RegisteredMulticastAddress_t
Container of the IPv6 multicast addresses.
typedef std::map< Ipv6RegisteredMulticastAddressKey_t, uint32_t >::const_iterator Ipv6RegisteredMulticastAddressCIter_t
Container Const Iterator of the IPv6 multicast addresses.
typedef std::map< Ipv6RegisteredMulticastAddressKey_t, uint32_t >::iterator Ipv6RegisteredMulticastAddressIter_t
Container Iterator of the IPv6 multicast addresses.
typedef std::pair< Ipv6Address, uint64_t > Ipv6RegisteredMulticastAddressKey_t
IPv6 multicast addresses / interface key.
typedef std::map< Ipv6Address, uint32_t > Ipv6RegisteredMulticastAddressNoInterface_t
Container of the IPv6 multicast addresses.
typedef std::map< Ipv6Address, uint32_t >::const_iterator Ipv6RegisteredMulticastAddressNoInterfaceCIter_t
Container Const Iterator of the IPv6 multicast addresses.
typedef std::map< Ipv6Address, uint32_t >::iterator Ipv6RegisteredMulticastAddressNoInterfaceIter_t
Container Iterator of the IPv6 multicast addresses.
typedef std::map< L4ListKey_t, Ptr< IpL4Protocol > > L4List_t
Container of the IPv6 L4 instances.
typedef std::pair< int, int32_t > L4ListKey_t
Container of the IPv6 L4 keys: protocol number, interface index.
typedef std::list< Ptr< Ipv6RawSocketImpl > > SocketList
Container of the IPv6 Raw Sockets.
Private Member Functions
Ipv6L3Protocol (const Ipv6L3Protocol &)
Copy constructor.
uint32_t AddIpv6Interface (Ptr< Ipv6Interface > interface)
Add an IPv6 interface to the stack.
Ipv6Header BuildHeader (Ipv6Address src, Ipv6Address dst, uint8_t protocol, uint16_t payloadSize, uint8_t hopLimit, uint8_t tclass)
Construct an IPv6 header.
void CallTxTrace (const Ipv6Header &ipHeader, Ptr< Packet > packet, Ptr< Ipv6 > ipv6, uint32_t interface)
Make a copy of the packet, add the header and invoke the TX trace callback.
virtual bool GetIpForward () const
Get IPv6 forwarding state.
virtual bool GetMtuDiscover (void) const
Get IPv6 MTU discover state.
virtual bool GetSendIcmpv6Redirect () const
Get the ICMPv6 Redirect sending state.
void IpForward (Ptr< const NetDevice > idev, Ptr< Ipv6Route > rtentry, Ptr< const Packet > p, const Ipv6Header &header)
Forward a packet.
void IpMulticastForward (Ptr< const NetDevice > idev, Ptr< Ipv6MulticastRoute > mrtentry, Ptr< const Packet > p, const Ipv6Header &header)
Forward a multicast packet.
void LocalDeliver (Ptr< const Packet > p, Ipv6Header const &ip, uint32_t iif)
Deliver a packet.
Ipv6L3Protocol & operator= (const Ipv6L3Protocol &)
Copy constructor.
void RouteInputError (Ptr< const Packet > p, const Ipv6Header &ipHeader, Socket::SocketErrno sockErrno)
Fallback when no route is found.
void SendRealOut (Ptr< Ipv6Route > route, Ptr< Packet > packet, Ipv6Header const &ipHeader)
Send packet with route.
virtual void SetIpForward (bool forward)
Set IPv6 forwarding state.
virtual void SetMtuDiscover (bool mtuDiscover)
Set IPv6 MTU discover state.
virtual void SetSendIcmpv6Redirect (bool sendIcmpv6Redirect)
Set the ICMPv6 Redirect sending state.
void SetupLoopback ()
Setup loopback interface.
Private Attributes
uint8_t m_defaultTclass
Default TCLASS for outgoing packets.
uint8_t m_defaultTtl
Default TTL for outgoing packets.
TracedCallback< const Ipv6Header &, Ptr< const Packet >, DropReason, Ptr< Ipv6 >, uint32_t > m_dropTrace
Callback to trace drop packets.
Ipv6InterfaceList m_interfaces
List of IPv6 interfaces.
bool m_ipForward
Forwarding packets (i.e.
TracedCallback< const Ipv6Header &, Ptr< const Packet >, uint32_t > m_localDeliverTrace
Trace of locally delivered packets.
bool m_mtuDiscover
MTU Discover (i.e.
Ipv6RegisteredMulticastAddress_t m_multicastAddresses
List of multicast IP addresses of interest, divided per interface.
Ipv6RegisteredMulticastAddressNoInterface_t m_multicastAddressesNoInterface
List of multicast IP addresses of interest for all the interfaces.
uint32_t m_nInterfaces
Number of IPv6 interfaces managed by the stack.
Ptr< Node > m_node
Node attached to stack.
Ptr< Ipv6PmtuCache > m_pmtuCache
Path MTU Cache.
Ipv6AutoconfiguredPrefixList m_prefixes
List of IPv6 prefix received from RA.
L4List_t m_protocols
List of transport protocol.
Ipv6InterfaceReverseContainer m_reverseInterfacesContainer
Container of NetDevice / Interface index associations.
Ptr< Ipv6RoutingProtocol > m_routingProtocol
Routing protocol.
TracedCallback< Ptr< const Packet >, Ptr< Ipv6 >, uint32_t > m_rxTrace
Callback to trace RX (reception) packets.
bool m_sendIcmpv6Redirect
Allow ICMPv6 Redirect sending state.
TracedCallback< const Ipv6Header &, Ptr< const Packet >, uint32_t > m_sendOutgoingTrace
Trace of sent packets.
SocketList m_sockets
List of IPv6 raw sockets.
bool m_strongEndSystemModel
Rejects packets directed to an interface with wrong address (RFC 1222).
TracedCallback< Ptr< const Packet >, Ptr< Ipv6 >, uint32_t > m_txTrace
Callback to trace TX (transmission) packets.
TracedCallback< const Ipv6Header &, Ptr< const Packet >, uint32_t > m_unicastForwardTrace
Trace of unicast forwarded packets.
Friends
class ::Ipv6L3ProtocolTestCase
Ipv6L3ProtocolTestCase test case.
Related Functions
(Note that these are not member functions.)
class Ipv6ExtensionLooseRouting
Ipv6ExtensionLooseRouting.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
IPv6 layer implementation.
This class contains two distinct groups of trace sources. The trace sources 'Rx' and 'Tx' are called, respectively, immediately after receiving from the NetDevice and immediately before sending to a NetDevice for transmitting a packet. These are low level trace sources that include the Ipv6Header already serialized into the packet. In contrast, the Drop, SendOutgoing, UnicastForward, and LocalDeliver trace sources are slightly higher-level and pass around the Ipv6Header as an explicit parameter and not as part of the packet.
Config Paths
ns3::Ipv6L3Protocol is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::Ipv6L3Protocol"
Attributes
DefaultTtl: The TTL value set by default on all outgoing packets generated on this node.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Initial value: 64
Flags: construct write read
DefaultTclass: The TCLASS value set by default on all outgoing packets generated on this node.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Initial value: 0
Flags: construct write read
InterfaceList: The set of IPv6 interfaces associated to this IPv6 stack.
Set with class: ns3::ObjectPtrContainerValue
Underlying type: ns3::Ptr< ns3::Ipv6Interface>
Flags: read
SendIcmpv6Redirect: Send the ICMPv6 Redirect when appropriate.
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
StrongEndSystemModel: Reject packets for an address not configured on the interface they're coming from (RFC1222).
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
Attributes defined in parent class ns3::Ipv6
IpForward: Globally enable or disable IP forwarding for all current and future IPv6 devices.
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
MtuDiscover: If disabled, every interface will have its MTU set to 1280 bytes.
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
TraceSources
Tx: Send IPv6 packet to outgoing interface.
Callback signature: ns3::Ipv6L3Protocol::TxRxTracedCallback
Rx: Receive IPv6 packet from incoming interface.
Callback signature: ns3::Ipv6L3Protocol::TxRxTracedCallback
Drop: Drop IPv6 packet
Callback signature: ns3::Ipv6L3Protocol::DropTracedCallback
SendOutgoing: A newly-generated packet by this node is about to be queued for transmission
Callback signature: ns3::Ipv6L3Protocol::SentTracedCallback
UnicastForward: A unicast IPv6 packet was received by this node and is being forwarded to another node
Callback signature: ns3::Ipv6L3Protocol::SentTracedCallback
LocalDeliver: An IPv6 packet was received by/for this node, and it is being forward up the stack
Callback signature: ns3::Ipv6L3Protocol::SentTracedCallback
Size of this type is 392 bytes (on a 64-bit architecture).
Definition at line 62 of file ipv6-l3-protocol.h.
Member Typedef Documentation
DropTracedCallback
typedef void(* ns3::Ipv6L3Protocol::DropTracedCallback) (const Ipv6Header &header, Ptr< const Packet > packet, DropReason reason, Ptr< Ipv6 > ipv6, uint32_t interface)
TracedCallback signature for packet drop events.
Parameters
[in] header The Ipv6Header.
[in] packet The packet.
[in] reason The reason the packet was dropped.
[in] ipv6
[in] interface
Deprecated:
The non-const Ptr<Ipv6> argument is deprecated and will be changed to Ptr<const Ipv6> in a future release.
Definition at line 405 of file ipv6-l3-protocol.h.
Ipv6AutoconfiguredPrefixList
typedef std::list< Ptr<Ipv6AutoconfiguredPrefix> > ns3::Ipv6L3Protocol::Ipv6AutoconfiguredPrefixList private
Container of the IPv6 Autoconfigured addresses.
Definition at line 504 of file ipv6-l3-protocol.h.
Ipv6AutoconfiguredPrefixListI
typedef std::list< Ptr<Ipv6AutoconfiguredPrefix> >::iterator ns3::Ipv6L3Protocol::Ipv6AutoconfiguredPrefixListI private
Iterator of the container of the IPv6 Autoconfigured addresses.
Definition at line 509 of file ipv6-l3-protocol.h.
Ipv6InterfaceList
typedef std::vector<Ptr<Ipv6Interface> > ns3::Ipv6L3Protocol::Ipv6InterfaceList private
Container of the IPv6 Interfaces.
Definition at line 479 of file ipv6-l3-protocol.h.
Ipv6InterfaceReverseContainer
typedef std::map<Ptr<const NetDevice>, uint32_t > ns3::Ipv6L3Protocol::Ipv6InterfaceReverseContainer private
Container of NetDevices registered to IPv6 and their interface indexes.
Definition at line 484 of file ipv6-l3-protocol.h.
Ipv6RegisteredMulticastAddress_t
typedef std::map<Ipv6RegisteredMulticastAddressKey_t, uint32_t> ns3::Ipv6L3Protocol::Ipv6RegisteredMulticastAddress_t private
Container of the IPv6 multicast addresses.
Definition at line 752 of file ipv6-l3-protocol.h.
Ipv6RegisteredMulticastAddressCIter_t
typedef std::map<Ipv6RegisteredMulticastAddressKey_t, uint32_t>::const_iterator ns3::Ipv6L3Protocol::Ipv6RegisteredMulticastAddressCIter_t private
Container Const Iterator of the IPv6 multicast addresses.
Definition at line 762 of file ipv6-l3-protocol.h.
Ipv6RegisteredMulticastAddressIter_t
typedef std::map<Ipv6RegisteredMulticastAddressKey_t, uint32_t>::iterator ns3::Ipv6L3Protocol::Ipv6RegisteredMulticastAddressIter_t private
Container Iterator of the IPv6 multicast addresses.
Definition at line 757 of file ipv6-l3-protocol.h.
Ipv6RegisteredMulticastAddressKey_t
typedef std::pair<Ipv6Address, uint64_t> ns3::Ipv6L3Protocol::Ipv6RegisteredMulticastAddressKey_t private
IPv6 multicast addresses / interface key.
Definition at line 747 of file ipv6-l3-protocol.h.
Ipv6RegisteredMulticastAddressNoInterface_t
typedef std::map<Ipv6Address, uint32_t> ns3::Ipv6L3Protocol::Ipv6RegisteredMulticastAddressNoInterface_t private
Container of the IPv6 multicast addresses.
Definition at line 767 of file ipv6-l3-protocol.h.
Ipv6RegisteredMulticastAddressNoInterfaceCIter_t
typedef std::map<Ipv6Address, uint32_t>::const_iterator ns3::Ipv6L3Protocol::Ipv6RegisteredMulticastAddressNoInterfaceCIter_t private
Container Const Iterator of the IPv6 multicast addresses.
Definition at line 777 of file ipv6-l3-protocol.h.
Ipv6RegisteredMulticastAddressNoInterfaceIter_t
typedef std::map<Ipv6Address, uint32_t>::iterator ns3::Ipv6L3Protocol::Ipv6RegisteredMulticastAddressNoInterfaceIter_t private
Container Iterator of the IPv6 multicast addresses.
Definition at line 772 of file ipv6-l3-protocol.h.
L4List_t
typedef std::map<L4ListKey_t, Ptr<IpL4Protocol> > ns3::Ipv6L3Protocol::L4List_t private
Container of the IPv6 L4 instances.
Definition at line 499 of file ipv6-l3-protocol.h.
L4ListKey_t
typedef std::pair<int, int32_t> ns3::Ipv6L3Protocol::L4ListKey_t private
Container of the IPv6 L4 keys: protocol number, interface index.
Definition at line 494 of file ipv6-l3-protocol.h.
SentTracedCallback
typedef void(* ns3::Ipv6L3Protocol::SentTracedCallback) (const Ipv6Header &header, Ptr< const Packet > packet, uint32_t interface)
TracedCallback signature for packet sent, forwarded or local-delivered events.
Parameters
[in] header The Ipv6Header.
[in] packet The packet.
[in] interface
Definition at line 378 of file ipv6-l3-protocol.h.
SocketList
typedef std::list<Ptr<Ipv6RawSocketImpl> > ns3::Ipv6L3Protocol::SocketList private
Container of the IPv6 Raw Sockets.
Definition at line 489 of file ipv6-l3-protocol.h.
TxRxTracedCallback
typedef void(* ns3::Ipv6L3Protocol::TxRxTracedCallback) (Ptr< const Packet > packet, Ptr< Ipv6 > ipv6, uint32_t interface)
TracedCallback signature for packet transmission or reception events.
Parameters
[in] header The Ipv6Header.
[in] packet The packet.
[in] ipv6
[in] interface
Deprecated:
The non-const Ptr<Ipv6> argument is deprecated and will be changed to Ptr<const Ipv6> in a future release.
Definition at line 391 of file ipv6-l3-protocol.h.
Member Enumeration Documentation
DropReason
enum ns3::Ipv6L3Protocol::DropReason
Reason why a packet has been dropped.
Enumerator
DROP_TTL_EXPIRED
Packet TTL has expired.
DROP_NO_ROUTE
No route to host.
DROP_INTERFACE_DOWN
Interface is down so can not send packet.
DROP_ROUTE_ERROR
Route error.
DROP_UNKNOWN_PROTOCOL
Unknown L4 protocol.
DROP_UNKNOWN_OPTION
Unknown option.
DROP_MALFORMED_HEADER
Malformed header.
DROP_FRAGMENT_TIMEOUT
Fragment timeout.
Definition at line 80 of file ipv6-l3-protocol.h.
Constructor & Destructor Documentation
Ipv6L3Protocol() [1/2]
ns3::Ipv6L3Protocol::Ipv6L3Protocol ()
Constructor.
Definition at line 126 of file ipv6-l3-protocol.cc.
References ns3::Object::AggregateObject(), m_pmtuCache, and NS_LOG_FUNCTION.
~Ipv6L3Protocol()
ns3::Ipv6L3Protocol::~Ipv6L3Protocol () virtual
Destructor.
Definition at line 136 of file ipv6-l3-protocol.cc.
References NS_LOG_FUNCTION.
Ipv6L3Protocol() [2/2]
ns3::Ipv6L3Protocol::Ipv6L3Protocol (const Ipv6L3Protocol &) private
Copy constructor.
Defined but not implemented to avoid misuse
Member Function Documentation
AddAddress()
bool ns3::Ipv6L3Protocol::AddAddress (uint32_t i, Ipv6InterfaceAddress address) virtual
Add an address on interface.
Parameters
i interface index
address to add
Returns
true if the operation succeeded
Implements ns3::Ipv6.
Definition at line 379 of file ipv6-l3-protocol.cc.
References ns3::Ipv6Interface::AddAddress(), first::address, m_routingProtocol, and NS_LOG_FUNCTION.
Referenced by AddAutoconfiguredAddress().
AddAutoconfiguredAddress()
void ns3::Ipv6L3Protocol::AddAutoconfiguredAddress (uint32_t interface, Ipv6Address network, Ipv6Prefix mask, uint8_t flags, uint32_t validTime, uint32_t preferredTime, Ipv6Address defaultRouter = Ipv6Address::GetZero ())
Add an autoconfigured address with RA information.
Parameters
interface interface index
network network prefix
mask network mask
flags flags of the prefix information option (home agent, ...)
validTime valid time of the prefix
preferredTime preferred time of the prefix
defaultRouter default router address
Definition at line 306 of file ipv6-l3-protocol.cc.
References AddAddress(), first::address, ns3::Ipv6Address::GetAny(), ns3::Ipv6Interface::GetDevice(), GetInterface(), GetRoutingProtocol(), ns3::Ipv6Address::IsAny(), m_node, m_prefixes, ns3::Ipv6Address::MakeAutoconfiguredAddress(), NS_LOG_FUNCTION, NS_LOG_INFO, and ns3::Ipv6AutoconfiguredPrefix::StartPreferredTimer().
AddInterface()
uint32_t ns3::Ipv6L3Protocol::AddInterface (Ptr< NetDevice > device) virtual
Add IPv6 interface for a device.
Parameters
device net device
Returns
interface index
Implements ns3::Ipv6.
Definition at line 195 of file ipv6-l3-protocol.cc.
References AddIpv6Interface(), ns3::CreateObject(), ns3::Object::GetObject(), m_ipForward, m_node, ns3::MakeCallback(), NS_ASSERT, NS_LOG_FUNCTION, PROT_NUMBER, Receive(), ns3::TrafficControlLayer::Receive(), and ns3::Node::RegisterProtocolHandler().
AddIpv6Interface()
uint32_t ns3::Ipv6L3Protocol::AddIpv6Interface (Ptr< Ipv6Interface > interface) private
Add an IPv6 interface to the stack.
Parameters
interface interface to add
Returns
index of newly added interface
Definition at line 217 of file ipv6-l3-protocol.cc.
References ns3::Ipv6Interface::GetDevice(), m_interfaces, m_nInterfaces, m_reverseInterfacesContainer, and NS_LOG_FUNCTION.
Referenced by AddInterface(), and SetupLoopback().
AddMulticastAddress() [1/2]
void ns3::Ipv6L3Protocol::AddMulticastAddress (Ipv6Address address)
Adds a multicast address to the list of addresses to pass to local deliver.
Parameters
address the address.
Definition at line 1520 of file ipv6-l3-protocol.cc.
References first::address, m_multicastAddressesNoInterface, NS_LOG_FUNCTION, and NS_LOG_WARN.
AddMulticastAddress() [2/2]
void ns3::Ipv6L3Protocol::AddMulticastAddress (Ipv6Address address, uint32_t interface)
Adds a multicast address to the list of addresses to pass to local deliver.
Parameters
address the address.
interface the incoming interface.
Definition at line 1506 of file ipv6-l3-protocol.cc.
References first::address, m_multicastAddresses, NS_LOG_FUNCTION, and NS_LOG_WARN.
BuildHeader()
Ipv6Header ns3::Ipv6L3Protocol::BuildHeader (Ipv6Address src, Ipv6Address dst, uint8_t protocol, uint16_t payloadSize, uint8_t hopLimit, uint8_t tclass) private
Construct an IPv6 header.
Parameters
src source IPv6 address
dst destination IPv6 address
protocol L4 protocol
payloadSize payload size
hopLimit Hop limit
tclass Tclass
Returns
newly created IPv6 header
Definition at line 1432 of file ipv6-l3-protocol.cc.
References NS_LOG_FUNCTION, ns3::Ipv6Header::SetDestinationAddress(), ns3::Ipv6Header::SetHopLimit(), ns3::Ipv6Header::SetNextHeader(), ns3::Ipv6Header::SetPayloadLength(), ns3::Ipv6Header::SetSourceAddress(), and ns3::Ipv6Header::SetTrafficClass().
Referenced by Send().
CallTxTrace()
void ns3::Ipv6L3Protocol::CallTxTrace (const Ipv6Header & ipHeader, Ptr< Packet > packet, Ptr< Ipv6 > ipv6, uint32_t interface) private
Make a copy of the packet, add the header and invoke the TX trace callback.
Parameters
ipHeader the IP header that will be added to the packet
packet the packet
ipv6 the Ipv6 protocol
interface the interface index
Note: If the TracedCallback API ever is extended, we could consider to check for connected functions before adding the header
Definition at line 1061 of file ipv6-l3-protocol.cc.
References ns3::Packet::AddHeader(), ns3::Packet::Copy(), and m_txTrace.
Referenced by SendRealOut().
CreateRawSocket()
Ptr< Socket > ns3::Ipv6L3Protocol::CreateRawSocket (void)
Create raw IPv6 socket.
Returns
newly raw socket
Definition at line 774 of file ipv6-l3-protocol.cc.
References m_node, m_sockets, NS_LOG_FUNCTION, and ns3::Ipv6RawSocketImpl::SetNode().
DeleteRawSocket()
void ns3::Ipv6L3Protocol::DeleteRawSocket (Ptr< Socket > socket)
Remove raw IPv6 socket.
Parameters
socket socket to remove
Definition at line 783 of file ipv6-l3-protocol.cc.
References m_sockets, and NS_LOG_FUNCTION.
DoDispose()
void ns3::Ipv6L3Protocol::DoDispose (void) protected virtual
Dispose object.
Reimplemented from ns3::Object.
Definition at line 141 of file ipv6-l3-protocol.cc.
References ns3::Object::DoDispose(), m_interfaces, m_node, m_pmtuCache, m_prefixes, m_protocols, m_reverseInterfacesContainer, m_routingProtocol, m_sockets, and NS_LOG_FUNCTION.
GetAddress()
Ipv6InterfaceAddress ns3::Ipv6L3Protocol::GetAddress (uint32_t interfaceIndex, uint32_t addressIndex) const virtual
Get an address.
Parameters
interfaceIndex interface index
addressIndex address index on the interface
Returns
Ipv6InterfaceAddress or assert if not found
Implements ns3::Ipv6.
Definition at line 399 of file ipv6-l3-protocol.cc.
References ns3::Ipv6Interface::GetAddress(), and NS_LOG_FUNCTION.
Referenced by Receive(), UanExperiment::SendPackets(), and SendRealOut().
GetIcmpv6()
Ptr< Icmpv6L4Protocol > ns3::Ipv6L3Protocol::GetIcmpv6 () const
Get ICMPv6 protocol.
Returns
Icmpv6L4Protocol pointer
Definition at line 797 of file ipv6-l3-protocol.cc.
References ns3::Object::GetObject(), GetProtocol(), ns3::Icmpv6L4Protocol::GetStaticProtocolNumber(), and NS_LOG_FUNCTION.
Referenced by IpForward(), LocalDeliver(), RouteInputError(), and SendRealOut().
GetInterface()
Ptr< Ipv6Interface > ns3::Ipv6L3Protocol::GetInterface (uint32_t i) const
Get an interface.
Parameters
i interface index
Returns
IPv6 interface pointer
Definition at line 228 of file ipv6-l3-protocol.cc.
References m_interfaces, and NS_LOG_FUNCTION.
Referenced by AddAutoconfiguredAddress(), GetNetDevice(), IpForward(), LocalDeliver(), RemoveAutoconfiguredAddress(), and SendRealOut().
GetInterfaceForAddress()
int32_t ns3::Ipv6L3Protocol::GetInterfaceForAddress (Ipv6Address addr) const virtual
Get interface index which has specified IPv6 address.
Parameters
addr IPv6 address
Returns
interface index or -1 if not found
Implements ns3::Ipv6.
Definition at line 245 of file ipv6-l3-protocol.cc.
References first::address, m_interfaces, ns3::max(), and NS_LOG_FUNCTION.
Referenced by Send().
GetInterfaceForDevice()
int32_t ns3::Ipv6L3Protocol::GetInterfaceForDevice (Ptr< const NetDevice > device) const virtual
Get interface index which is on a specified net device.
Parameters
device net device
Returns
the interface index
Implements ns3::Ipv6.
Definition at line 293 of file ipv6-l3-protocol.cc.
References m_reverseInterfacesContainer, and NS_LOG_FUNCTION.
Referenced by IpForward(), Receive(), and Send().
GetInterfaceForPrefix()
int32_t ns3::Ipv6L3Protocol::GetInterfaceForPrefix (Ipv6Address addr, Ipv6Prefix mask) const virtual
Get interface index which match specified address/prefix.
Parameters
addr IPv6 address
mask IPv6 prefix (mask)
Returns
interface index or -1 if not found
Implements ns3::Ipv6.
Definition at line 267 of file ipv6-l3-protocol.cc.
References first::address, m_interfaces, and NS_LOG_FUNCTION.
GetIpForward()
bool ns3::Ipv6L3Protocol::GetIpForward (void) const private virtual
Get IPv6 forwarding state.
Returns
forwarding state (enabled or not)
Implements ns3::Ipv6.
Definition at line 629 of file ipv6-l3-protocol.cc.
References m_ipForward, and NS_LOG_FUNCTION.
GetMetric()
uint16_t ns3::Ipv6L3Protocol::GetMetric (uint32_t i) const virtual
Get metric for an interface.
Parameters
i index
Returns
metric
Implements ns3::Ipv6.
Definition at line 453 of file ipv6-l3-protocol.cc.
References ns3::Ipv6Interface::GetMetric(), and NS_LOG_FUNCTION.
GetMtu()
uint16_t ns3::Ipv6L3Protocol::GetMtu (uint32_t i) const virtual
Get MTU for an interface.
Parameters
i index
Returns
MTU
Implements ns3::Ipv6.
Definition at line 460 of file ipv6-l3-protocol.cc.
References ns3::Ipv6Interface::GetDevice(), IPV6_MIN_MTU, m_mtuDiscover, and NS_LOG_FUNCTION.
GetMtuDiscover()
bool ns3::Ipv6L3Protocol::GetMtuDiscover (void) const private virtual
Get IPv6 MTU discover state.
Returns
MTU discover state (enabled or not)
Implements ns3::Ipv6.
Definition at line 641 of file ipv6-l3-protocol.cc.
References m_mtuDiscover, and NS_LOG_FUNCTION.
GetNAddresses()
uint32_t ns3::Ipv6L3Protocol::GetNAddresses (uint32_t interface) const virtual
Get number of address for an interface.
Parameters
interface interface index
Returns
number of address
Implements ns3::Ipv6.
Definition at line 392 of file ipv6-l3-protocol.cc.
References ns3::Ipv6Interface::GetNAddresses(), and NS_LOG_FUNCTION.
Referenced by Receive(), SendRealOut(), and SourceAddressSelection().
GetNetDevice()
Ptr< NetDevice > ns3::Ipv6L3Protocol::GetNetDevice (uint32_t i) virtual
Get device by index.
Parameters
i device index on this stack
Returns
NetDevice pointer
Implements ns3::Ipv6.
Definition at line 287 of file ipv6-l3-protocol.cc.
References ns3::Ipv6Interface::GetDevice(), GetInterface(), and NS_LOG_FUNCTION.
Referenced by IpMulticastForward(), and Send().
GetNInterfaces()
uint32_t ns3::Ipv6L3Protocol::GetNInterfaces (void) const virtual
Get current number of interface on this stack.
Returns
number of interface registered
Implements ns3::Ipv6.
Definition at line 239 of file ipv6-l3-protocol.cc.
References m_nInterfaces, and NS_LOG_FUNCTION.
Referenced by Receive(), and SendRealOut().
GetProtocol() [1/2]
Ptr< IpL4Protocol > ns3::Ipv6L3Protocol::GetProtocol (int protocolNumber) const virtual
Get L4 protocol by protocol number.
Parameters
protocolNumber protocol number
Returns
corresponding IpL4Protocol or 0 if not found
Implements ns3::Ipv6.
Definition at line 740 of file ipv6-l3-protocol.cc.
References NS_LOG_FUNCTION.
Referenced by GetIcmpv6(), and LocalDeliver().
GetProtocol() [2/2]
Ptr< IpL4Protocol > ns3::Ipv6L3Protocol::GetProtocol (int protocolNumber, int32_t interfaceIndex) const virtual
Get L4 protocol by protocol number for the specified interface.
Parameters
protocolNumber protocol number
interfaceIndex interface index, -1 means "any" interface.
Returns
corresponding IpL4Protocol or 0 if not found
Implements ns3::Ipv6.
Definition at line 747 of file ipv6-l3-protocol.cc.
References m_protocols, and NS_LOG_FUNCTION.
GetRoutingProtocol()
Ptr< Ipv6RoutingProtocol > ns3::Ipv6L3Protocol::GetRoutingProtocol (void) const virtual
Get current routing protocol used.
Returns
routing protocol
Implements ns3::Ipv6.
Definition at line 189 of file ipv6-l3-protocol.cc.
References m_routingProtocol, and NS_LOG_FUNCTION.
Referenced by AddAutoconfiguredAddress(), and RemoveAutoconfiguredAddress().
GetSendIcmpv6Redirect()
bool ns3::Ipv6L3Protocol::GetSendIcmpv6Redirect () const private virtual
Get the ICMPv6 Redirect sending state.
Returns
ICMPv6 Redirect sending state (enabled or not)
Definition at line 653 of file ipv6-l3-protocol.cc.
References m_sendIcmpv6Redirect, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::Ipv6L3Protocol::GetTypeId (void) static
Get the type ID of this class.
Returns
type ID
Definition at line 60 of file ipv6-l3-protocol.cc.
References GetSendIcmpv6Redirect(), m_defaultTclass, m_defaultTtl, m_dropTrace, m_interfaces, m_localDeliverTrace, m_rxTrace, m_sendOutgoingTrace, m_strongEndSystemModel, m_txTrace, m_unicastForwardTrace, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeObjectVectorAccessor(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), ns3::TypeId::SetParent(), and SetSendIcmpv6Redirect().
Insert() [1/2]
void ns3::Ipv6L3Protocol::Insert (Ptr< IpL4Protocol > protocol) virtual
Add a L4 protocol.
Parameters
protocol L4 protocol
Implements ns3::Ipv6.
Definition at line 685 of file ipv6-l3-protocol.cc.
References ns3::IpL4Protocol::GetProtocolNumber(), m_protocols, NS_LOG_FUNCTION, and NS_LOG_WARN.
Insert() [2/2]
void ns3::Ipv6L3Protocol::Insert (Ptr< IpL4Protocol > protocol, uint32_t interfaceIndex) virtual
Add a L4 protocol to a specific interface.
This may be called multiple times for multiple interfaces for the same protocol. To insert for all interfaces, use the separate Insert (Ptr<IpL4Protocol> protocol) method.
Setting a protocol on a specific interface will overwrite the previously bound protocol.
Parameters
protocol L4 protocol.
interfaceIndex interface index.
Implements ns3::Ipv6.
Definition at line 696 of file ipv6-l3-protocol.cc.
References ns3::IpL4Protocol::GetProtocolNumber(), m_protocols, NS_LOG_FUNCTION, and NS_LOG_WARN.
IpForward()
void ns3::Ipv6L3Protocol::IpForward (Ptr< const NetDevice > idev, Ptr< Ipv6Route > rtentry, Ptr< const Packet > p, const Ipv6Header & header) private
Forward a packet.
Parameters
idev Pointer to ingress network device
rtentry route
p packet to forward
header IPv6 header to add to the packet
Definition at line 1189 of file ipv6-l3-protocol.cc.
References ns3::Packet::AddHeader(), DROP_ROUTE_ERROR, DROP_TTL_EXPIRED, ns3::Ipv6InterfaceAddress::GetAddress(), ns3::Ipv6Header::GetDestinationAddress(), ns3::Ipv6Header::GetHopLimit(), GetIcmpv6(), ns3::Node::GetId(), GetInterface(), GetInterfaceForDevice(), ns3::Ipv6Interface::GetLinkLocalAddress(), ns3::Object::GetObject(), ns3::Ipv6Header::GetSourceAddress(), ns3::Icmpv6Header::ICMPV6_HOPLIMIT, ns3::Ipv6Address::IsAny(), ns3::Ipv6Address::IsDocumentation(), ns3::Ipv6Address::IsLinkLocal(), ns3::Ipv6Address::IsMulticast(), m_dropTrace, m_node, m_sendIcmpv6Redirect, m_unicastForwardTrace, NS_LOG_FUNCTION, NS_LOG_LOGIC, NS_LOG_WARN, ns3::Packet::RemovePacketTag(), SendRealOut(), and ns3::Ipv6Header::SetHopLimit().
Referenced by Receive().
IpMulticastForward()
void ns3::Ipv6L3Protocol::IpMulticastForward (Ptr< const NetDevice > idev, Ptr< Ipv6MulticastRoute > mrtentry, Ptr< const Packet > p, const Ipv6Header & header) private
Forward a multicast packet.
Parameters
idev Pointer to ingress network device
mrtentry route
p packet to forward
header IPv6 header to add to the packet
Definition at line 1273 of file ipv6-l3-protocol.cc.
References DROP_TTL_EXPIRED, ns3::Ipv6Address::GetAny(), ns3::Ipv6Header::GetDestinationAddress(), ns3::Ipv6Header::GetHopLimit(), ns3::Node::GetId(), GetNetDevice(), ns3::Object::GetObject(), ns3::Ipv6Header::GetSourceAddress(), m_dropTrace, m_node, NS_LOG_FUNCTION, NS_LOG_LOGIC, NS_LOG_WARN, SendRealOut(), and ns3::Ipv6Header::SetHopLimit().
Referenced by Receive().
IsForwarding()
bool ns3::Ipv6L3Protocol::IsForwarding (uint32_t i) const virtual
Is interface allows forwarding ?
Parameters
i interface index
Returns
true if the interface is forwarding
Implements ns3::Ipv6.
Definition at line 563 of file ipv6-l3-protocol.cc.
References NS_LOG_FUNCTION, and NS_LOG_LOGIC.
IsRegisteredMulticastAddress() [1/2]
bool ns3::Ipv6L3Protocol::IsRegisteredMulticastAddress (Ipv6Address address) const
Checks if the address has been registered.
Parameters
address the address.
Returns
true if the address is registered.
Definition at line 1571 of file ipv6-l3-protocol.cc.
References first::address, m_multicastAddressesNoInterface, and NS_LOG_FUNCTION.
Referenced by Receive().
IsRegisteredMulticastAddress() [2/2]
bool ns3::Ipv6L3Protocol::IsRegisteredMulticastAddress (Ipv6Address address, uint32_t interface) const
Checks if the address has been registered for a specific interface.
Parameters
address the address.
interface the incoming interface.
Returns
true if the address is registered.
Definition at line 1557 of file ipv6-l3-protocol.cc.
References first::address, m_multicastAddresses, and NS_LOG_FUNCTION.
IsUp()
bool ns3::Ipv6L3Protocol::IsUp (uint32_t i) const virtual
Is specified interface up ?
Parameters
i interface index
Returns
true if the interface is up
Implements ns3::Ipv6.
Definition at line 481 of file ipv6-l3-protocol.cc.
References ns3::Ipv6Interface::IsUp(), and NS_LOG_FUNCTION.
LocalDeliver()
void ns3::Ipv6L3Protocol::LocalDeliver (Ptr< const Packet > p, Ipv6Header const & ip, uint32_t iif) private
Deliver a packet.
Parameters
p packet delivered
ip IPv6 header
iif input interface packet was received
Definition at line 1305 of file ipv6-l3-protocol.cc.
References ns3::Packet::AddHeader(), ns3::Packet::Copy(), ns3::Packet::CopyData(), DROP_UNKNOWN_PROTOCOL, ns3::Ipv6Header::GetDestinationAddress(), GetIcmpv6(), GetInterface(), ns3::Ipv6Header::GetNextHeader(), ns3::Object::GetObject(), GetProtocol(), ns3::Ipv6Header::GetSerializedSize(), ns3::Ipv6Header::GetSourceAddress(), ns3::Icmpv6Header::ICMPV6_PORT_UNREACHABLE, ns3::Icmpv6Header::ICMPV6_UNKNOWN_NEXT_HEADER, ns3::Ipv6Header::IPV6_EXT_FRAGMENTATION, ns3::Ipv6Header::IPV6_EXT_HOP_BY_HOP, ns3::Ipv6Address::IsMulticast(), m_dropTrace, m_localDeliverTrace, m_node, NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, NS_LOG_WARN, ns3::IpL4Protocol::Receive(), ns3::Packet::RemoveAtStart(), ns3::IpL4Protocol::RX_CSUM_FAILED, ns3::IpL4Protocol::RX_ENDPOINT_CLOSED, ns3::IpL4Protocol::RX_ENDPOINT_UNREACH, and ns3::IpL4Protocol::RX_OK.
Referenced by Receive().
NotifyNewAggregate()
void ns3::Ipv6L3Protocol::NotifyNewAggregate (void) protected virtual
Notify other components connected to the node that a new stack member is now connected.
This will be used to notify Layer 3 protocol of layer 4 protocol stack to connect them together.
Reimplemented from ns3::Object.
Definition at line 659 of file ipv6-l3-protocol.cc.
References m_node, ns3::Object::NotifyNewAggregate(), NS_LOG_FUNCTION, and SetNode().
operator=()
Ipv6L3Protocol& ns3::Ipv6L3Protocol::operator= (const Ipv6L3Protocol &) private
Copy constructor.
Defined but not implemented to avoid misuse
Returns
the copied object
Receive()
void ns3::Ipv6L3Protocol::Receive (Ptr< NetDevice > device, Ptr< const Packet > p, uint16_t protocol, const Address & from, const Address & to, NetDevice::PacketType packetType)
Receive method when a packet arrive in the stack.
This method removes IPv6 header and forward up to L4 protocol.
Parameters
device network device
p the packet
protocol next header value
from address of the correspondent
to address of the destination
packetType type of the packet
Definition at line 907 of file ipv6-l3-protocol.cc.
References DROP_INTERFACE_DOWN, ns3::Ipv6RawSocketImpl::ForwardUp(), ns3::Ipv6InterfaceAddress::GetAddress(), GetAddress(), ns3::Ipv6Header::GetDestinationAddress(), ns3::Node::GetId(), GetInterfaceForDevice(), GetNAddresses(), ns3::Ipv6Header::GetNextHeader(), GetNInterfaces(), ns3::Object::GetObject(), ns3::Ipv6Header::GetPayloadLength(), ns3::Packet::GetSize(), ns3::Ipv6Header::GetSourceAddress(), IpForward(), IpMulticastForward(), ns3::Ipv6Header::IPV6_EXT_HOP_BY_HOP, ns3::Ipv6Address::IsAllNodesMulticast(), ns3::Ipv6Address::IsAllRoutersMulticast(), ns3::Ipv6Address::IsMulticast(), IsRegisteredMulticastAddress(), LocalDeliver(), ns3::NdiscCache::Lookup(), ns3::NdiscCache::LookupInverse(), m_dropTrace, m_interfaces, m_node, m_routingProtocol, m_rxTrace, m_sockets, m_strongEndSystemModel, ns3::MakeCallback(), NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, NS_LOG_WARN, ns3::Packet::RemoveAtEnd(), ns3::Packet::RemoveHeader(), RouteInputError(), and ns3::NdiscCache::Entry::UpdateReachableTimer().
Referenced by AddInterface(), and SetupLoopback().
RegisterExtensions()
void ns3::Ipv6L3Protocol::RegisterExtensions () virtual
Register the IPv6 Extensions.
Implements ns3::Ipv6.
Definition at line 1446 of file ipv6-l3-protocol.cc.
References ns3::Object::AggregateObject(), m_node, and ns3::Ipv6Extension::SetNode().
RegisterOptions()
void ns3::Ipv6L3Protocol::RegisterOptions () virtual
Register the IPv6 Options.
Implements ns3::Ipv6.
Definition at line 1479 of file ipv6-l3-protocol.cc.
References ns3::Object::AggregateObject(), and m_node.
Remove() [1/2]
void ns3::Ipv6L3Protocol::Remove (Ptr< IpL4Protocol > protocol) virtual
Remove a L4 protocol.
Parameters
protocol L4 protocol to remove.
Implements ns3::Ipv6.
Definition at line 708 of file ipv6-l3-protocol.cc.
References ns3::IpL4Protocol::GetProtocolNumber(), m_protocols, NS_LOG_FUNCTION, and NS_LOG_WARN.
Remove() [2/2]
void ns3::Ipv6L3Protocol::Remove (Ptr< IpL4Protocol > protocol, uint32_t interfaceIndex) virtual
Remove a L4 protocol from a specific interface.
Parameters
protocol L4 protocol to remove.
interfaceIndex interface index.
Implements ns3::Ipv6.
Definition at line 724 of file ipv6-l3-protocol.cc.
References ns3::IpL4Protocol::GetProtocolNumber(), m_protocols, NS_LOG_FUNCTION, and NS_LOG_WARN.
RemoveAddress() [1/2]
bool ns3::Ipv6L3Protocol::RemoveAddress (uint32_t interfaceIndex, Ipv6Address address) virtual
Remove a specified Ipv6 address from an interface.
Parameters
interfaceIndex interface index
address Ipv6Address to be removed from the interface
Returns
true if the operation succeeded
Implements ns3::Ipv6.
Definition at line 424 of file ipv6-l3-protocol.cc.
References first::address, ns3::Ipv6Address::GetLoopback(), m_routingProtocol, NS_LOG_FUNCTION, and NS_LOG_WARN.
RemoveAddress() [2/2]
bool ns3::Ipv6L3Protocol::RemoveAddress (uint32_t interfaceIndex, uint32_t addressIndex) virtual
Remove an address from an interface.
Parameters
interfaceIndex interface index
addressIndex address index on the interface
Returns
true if the operation succeeded
Implements ns3::Ipv6.
Definition at line 406 of file ipv6-l3-protocol.cc.
References first::address, m_routingProtocol, and NS_LOG_FUNCTION.
Referenced by RemoveAutoconfiguredAddress().
RemoveAutoconfiguredAddress()
void ns3::Ipv6L3Protocol::RemoveAutoconfiguredAddress (uint32_t interface, Ipv6Address network, Ipv6Prefix mask, Ipv6Address defaultRouter)
Remove an autoconfigured address.
Typically it is used when an autoconfigured address expires.
Parameters
interface interface index
network network prefix
mask network mask
defaultRouter gateway
Definition at line 348 of file ipv6-l3-protocol.cc.
References ns3::Ipv6InterfaceAddress::GetAddress(), ns3::Ipv6Interface::GetAddress(), ns3::Ipv6Address::GetAny(), ns3::Ipv6Interface::GetDevice(), GetInterface(), ns3::Ipv6Interface::GetNAddresses(), GetRoutingProtocol(), m_prefixes, ns3::Ipv6Address::MakeAutoconfiguredAddress(), NS_LOG_FUNCTION, and RemoveAddress().
RemoveMulticastAddress() [1/2]
void ns3::Ipv6L3Protocol::RemoveMulticastAddress (Ipv6Address address)
Removes a multicast address from the list of addresses to pass to local deliver.
Parameters
address the address.
Definition at line 1546 of file ipv6-l3-protocol.cc.
References first::address, m_multicastAddressesNoInterface, and NS_LOG_FUNCTION.
RemoveMulticastAddress() [2/2]
void ns3::Ipv6L3Protocol::RemoveMulticastAddress (Ipv6Address address, uint32_t interface)
Removes a multicast address from the list of addresses to pass to local deliver.
Parameters
address the address.
interface the incoming interface.
Definition at line 1533 of file ipv6-l3-protocol.cc.
References first::address, m_multicastAddresses, and NS_LOG_FUNCTION.
ReportDrop()
void ns3::Ipv6L3Protocol::ReportDrop (Ipv6Header ipHeader, Ptr< Packet > p, DropReason dropReason) virtual
Report a packet drop.
This function is used by Fragment Timeout handling to signal a fragment drop.
Parameters
ipHeader the IPv6 header of dropped packet
p the packet (if available)
dropReason the drop reason
Definition at line 1501 of file ipv6-l3-protocol.cc.
References ns3::Object::GetObject(), m_dropTrace, and m_node.
RouteInputError()
void ns3::Ipv6L3Protocol::RouteInputError (Ptr< const Packet > p, const Ipv6Header & ipHeader, Socket::SocketErrno sockErrno) private
Fallback when no route is found.
Parameters
p packet
ipHeader IPv6 header
sockErrno error number
Definition at line 1417 of file ipv6-l3-protocol.cc.
References ns3::Packet::AddHeader(), DROP_ROUTE_ERROR, ns3::Ipv6Header::GetDestinationAddress(), GetIcmpv6(), ns3::Object::GetObject(), ns3::Ipv6Header::GetSourceAddress(), ns3::Icmpv6Header::ICMPV6_NO_ROUTE, ns3::Ipv6Address::IsMulticast(), m_dropTrace, m_node, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by Receive().
Send()
void ns3::Ipv6L3Protocol::Send (Ptr< Packet > packet, Ipv6Address source, Ipv6Address destination, uint8_t protocol, Ptr< Ipv6Route > route) virtual
Higher-level layers call this method to send a packet down the stack to the MAC and PHY layers.
Parameters
packet packet to send
source source address of packet
destination address of packet
protocol number of packet
route route to take
Implements ns3::Ipv6.
Definition at line 824 of file ipv6-l3-protocol.cc.
References BuildHeader(), DROP_NO_ROUTE, ns3::SocketIpv6HopLimitTag::GetHopLimit(), GetInterfaceForAddress(), GetInterfaceForDevice(), GetNetDevice(), ns3::Object::GetObject(), ns3::Packet::GetSize(), ns3::SocketIpv6TclassTag::GetTclass(), ns3::Ipv6Address::GetZero(), ns3::Ipv6Address::IsLinkLocal(), ns3::Ipv6Address::IsLinkLocalMulticast(), m_defaultTclass, m_defaultTtl, m_dropTrace, m_node, m_routingProtocol, m_sendOutgoingTrace, NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, NS_LOG_WARN, ns3::Packet::RemovePacketTag(), and SendRealOut().
SendRealOut()
void ns3::Ipv6L3Protocol::SendRealOut (Ptr< Ipv6Route > route, Ptr< Packet > packet, Ipv6Header const & ipHeader) private
Send packet with route.
Parameters
route route
packet packet to send
ipHeader IPv6 header to add to the packet
Definition at line 1069 of file ipv6-l3-protocol.cc.
References ns3::Packet::AddHeader(), CallTxTrace(), DROP_INTERFACE_DOWN, ns3::Ipv6InterfaceAddress::GetAddress(), GetAddress(), ns3::Ipv6Address::GetAny(), ns3::Ipv6Header::GetDestinationAddress(), GetIcmpv6(), GetInterface(), GetNAddresses(), GetNInterfaces(), ns3::Object::GetObject(), ns3::Packet::GetSize(), ns3::Ipv6Header::GetSourceAddress(), ns3::Ipv6Header::IPV6_EXT_FRAGMENTATION, ns3::Ipv6Interface::IsUp(), m_dropTrace, m_node, m_pmtuCache, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::PeekPointer(), and ns3::Ipv6Interface::Send().
Referenced by IpForward(), IpMulticastForward(), and Send().
SetDefaultTclass()
void ns3::Ipv6L3Protocol::SetDefaultTclass (uint8_t tclass)
Set the default TCLASS.
Parameters
tclass TCLASS to set
Definition at line 818 of file ipv6-l3-protocol.cc.
References m_defaultTclass, and NS_LOG_FUNCTION.
SetDefaultTtl()
void ns3::Ipv6L3Protocol::SetDefaultTtl (uint8_t ttl)
Set the default TTL.
Parameters
ttl TTL to set
Definition at line 812 of file ipv6-l3-protocol.cc.
References m_defaultTtl, and NS_LOG_FUNCTION.
SetDown()
void ns3::Ipv6L3Protocol::SetDown (uint32_t i) virtual
set an interface down.
Parameters
i interface index
Implements ns3::Ipv6.
Definition at line 513 of file ipv6-l3-protocol.cc.
References m_routingProtocol, NS_LOG_FUNCTION, and ns3::Ipv6Interface::SetDown().
SetForwarding()
void ns3::Ipv6L3Protocol::SetForwarding (uint32_t i, bool val) virtual
Enable or disable forwarding on interface.
Parameters
i interface index
val true = enable forwarding, false = disable
Implements ns3::Ipv6.
Definition at line 572 of file ipv6-l3-protocol.cc.
References NS_LOG_FUNCTION, and ns3::Ipv6Interface::SetForwarding().
SetIpForward()
void ns3::Ipv6L3Protocol::SetIpForward (bool forward) private virtual
Set IPv6 forwarding state.
Parameters
forward IPv6 forwarding enabled or not
Implements ns3::Ipv6.
Definition at line 618 of file ipv6-l3-protocol.cc.
References m_interfaces, m_ipForward, and NS_LOG_FUNCTION.
SetMetric()
void ns3::Ipv6L3Protocol::SetMetric (uint32_t i, uint16_t metric) virtual
Set metric for an interface.
Parameters
i index
metric
Implements ns3::Ipv6.
Definition at line 446 of file ipv6-l3-protocol.cc.
References NS_LOG_FUNCTION, and ns3::Ipv6Interface::SetMetric().
SetMtuDiscover()
void ns3::Ipv6L3Protocol::SetMtuDiscover (bool mtuDiscover) private virtual
Set IPv6 MTU discover state.
Parameters
mtuDiscover IPv6 MTU discover enabled or not
Implements ns3::Ipv6.
Definition at line 635 of file ipv6-l3-protocol.cc.
References m_mtuDiscover, and NS_LOG_FUNCTION.
SetNode()
void ns3::Ipv6L3Protocol::SetNode (Ptr< Node > node)
Set node associated with this stack.
Parameters
node node to set
Definition at line 677 of file ipv6-l3-protocol.cc.
References m_node, NS_LOG_FUNCTION, and SetupLoopback().
Referenced by NotifyNewAggregate().
SetPmtu()
void ns3::Ipv6L3Protocol::SetPmtu (Ipv6Address dst, uint32_t pmtu) virtual
Set the Path MTU for the specified IPv6 destination address.
Parameters
dst Ipv6 destination address
pmtu the Path MTU
Implements ns3::Ipv6.
Definition at line 474 of file ipv6-l3-protocol.cc.
References m_pmtuCache, and NS_LOG_FUNCTION.
SetRoutingProtocol()
void ns3::Ipv6L3Protocol::SetRoutingProtocol (Ptr< Ipv6RoutingProtocol > routingProtocol) virtual
Set routing protocol for this stack.
Parameters
routingProtocol IPv6 routing protocol to set
Implements ns3::Ipv6.
Definition at line 182 of file ipv6-l3-protocol.cc.
References m_routingProtocol, and NS_LOG_FUNCTION.
SetSendIcmpv6Redirect()
void ns3::Ipv6L3Protocol::SetSendIcmpv6Redirect (bool sendIcmpv6Redirect) private virtual
Set the ICMPv6 Redirect sending state.
Parameters
sendIcmpv6Redirect ICMPv6 Redirect sending enabled or not
Definition at line 647 of file ipv6-l3-protocol.cc.
References m_sendIcmpv6Redirect, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetUp()
void ns3::Ipv6L3Protocol::SetUp (uint32_t i) virtual
Set an interface up.
Parameters
i interface index
Implements ns3::Ipv6.
Definition at line 488 of file ipv6-l3-protocol.cc.
References m_routingProtocol, NS_LOG_FUNCTION, NS_LOG_LOGIC, and ns3::Ipv6Interface::SetUp().
SetupLoopback()
void ns3::Ipv6L3Protocol::SetupLoopback (void) private
Setup loopback interface.
Definition at line 526 of file ipv6-l3-protocol.cc.
References ns3::Node::AddDevice(), AddIpv6Interface(), ns3::CreateObject(), ns3::Node::GetDevice(), ns3::Ipv6Address::GetLoopback(), ns3::Node::GetNDevices(), m_node, m_routingProtocol, ns3::MakeCallback(), NS_LOG_FUNCTION, PROT_NUMBER, Receive(), and ns3::Node::RegisterProtocolHandler().
Referenced by SetNode().
SourceAddressSelection()
Ipv6Address ns3::Ipv6L3Protocol::SourceAddressSelection (uint32_t interface, Ipv6Address dest) virtual
Choose the source address to use with destination address.
Parameters
interface interface index
dest IPv6 destination address
Returns
IPv6 source address to use
Implements ns3::Ipv6.
Definition at line 579 of file ipv6-l3-protocol.cc.
References GetNAddresses(), ns3::Ipv6Address::IsLinkLocal(), ns3::Ipv6Address::IsLinkLocalMulticast(), and NS_LOG_FUNCTION.
Friends And Related Function Documentation
::Ipv6L3ProtocolTestCase
friend class ::Ipv6L3ProtocolTestCase friend
Ipv6L3ProtocolTestCase test case.
Definition at line 469 of file ipv6-l3-protocol.h.
Ipv6ExtensionLooseRouting
friend class Ipv6ExtensionLooseRouting friend
Ipv6ExtensionLooseRouting.
Definition at line 474 of file ipv6-l3-protocol.h.
Member Data Documentation
m_defaultTclass
uint8_t ns3::Ipv6L3Protocol::m_defaultTclass private
Default TCLASS for outgoing packets.
Definition at line 717 of file ipv6-l3-protocol.h.
Referenced by GetTypeId(), Send(), and SetDefaultTclass().
m_defaultTtl
uint8_t ns3::Ipv6L3Protocol::m_defaultTtl private
Default TTL for outgoing packets.
Definition at line 712 of file ipv6-l3-protocol.h.
Referenced by GetTypeId(), Send(), and SetDefaultTtl().
m_dropTrace
TracedCallback<const Ipv6Header &, Ptr<const Packet>, DropReason, Ptr<Ipv6>, uint32_t> ns3::Ipv6L3Protocol::m_dropTrace private
Callback to trace drop packets.
Deprecated:
The non-const Ptr<Ipv6> argument is deprecated and will be changed to Ptr<const Ipv6> in a future release.
Definition at line 542 of file ipv6-l3-protocol.h.
Referenced by GetTypeId(), IpForward(), IpMulticastForward(), LocalDeliver(), Receive(), ReportDrop(), RouteInputError(), Send(), and SendRealOut().
m_interfaces
Ipv6InterfaceList ns3::Ipv6L3Protocol::m_interfaces private
List of IPv6 interfaces.
Definition at line 697 of file ipv6-l3-protocol.h.
Referenced by AddIpv6Interface(), DoDispose(), GetInterface(), GetInterfaceForAddress(), GetInterfaceForPrefix(), GetTypeId(), Receive(), and SetIpForward().
m_ipForward
bool ns3::Ipv6L3Protocol::m_ipForward private
Forwarding packets (i.e.
router mode) state.
Definition at line 677 of file ipv6-l3-protocol.h.
Referenced by AddInterface(), GetIpForward(), and SetIpForward().
m_localDeliverTrace
TracedCallback<const Ipv6Header &, Ptr<const Packet>, uint32_t> ns3::Ipv6L3Protocol::m_localDeliverTrace private
Trace of locally delivered packets.
Definition at line 549 of file ipv6-l3-protocol.h.
Referenced by GetTypeId(), and LocalDeliver().
m_mtuDiscover
bool ns3::Ipv6L3Protocol::m_mtuDiscover private
MTU Discover (i.e.
Path MTU) state.
Definition at line 682 of file ipv6-l3-protocol.h.
Referenced by GetMtu(), GetMtuDiscover(), and SetMtuDiscover().
m_multicastAddresses
Ipv6RegisteredMulticastAddress_t ns3::Ipv6L3Protocol::m_multicastAddresses private
List of multicast IP addresses of interest, divided per interface.
Definition at line 782 of file ipv6-l3-protocol.h.
Referenced by AddMulticastAddress(), IsRegisteredMulticastAddress(), and RemoveMulticastAddress().
m_multicastAddressesNoInterface
Ipv6RegisteredMulticastAddressNoInterface_t ns3::Ipv6L3Protocol::m_multicastAddressesNoInterface private
List of multicast IP addresses of interest for all the interfaces.
Definition at line 787 of file ipv6-l3-protocol.h.
Referenced by AddMulticastAddress(), IsRegisteredMulticastAddress(), and RemoveMulticastAddress().
m_nInterfaces
uint32_t ns3::Ipv6L3Protocol::m_nInterfaces private
Number of IPv6 interfaces managed by the stack.
Definition at line 707 of file ipv6-l3-protocol.h.
Referenced by AddIpv6Interface(), and GetNInterfaces().
m_node
Ptr<Node> ns3::Ipv6L3Protocol::m_node private
Node attached to stack.
Definition at line 672 of file ipv6-l3-protocol.h.
Referenced by AddAutoconfiguredAddress(), AddInterface(), CreateRawSocket(), DoDispose(), IpForward(), IpMulticastForward(), LocalDeliver(), NotifyNewAggregate(), Receive(), RegisterExtensions(), RegisterOptions(), ReportDrop(), RouteInputError(), Send(), SendRealOut(), SetNode(), and SetupLoopback().
m_pmtuCache
Ptr<Ipv6PmtuCache> ns3::Ipv6L3Protocol::m_pmtuCache private
Path MTU Cache.
Definition at line 687 of file ipv6-l3-protocol.h.
Referenced by Ipv6L3Protocol(), DoDispose(), SendRealOut(), and SetPmtu().
m_prefixes
Ipv6AutoconfiguredPrefixList ns3::Ipv6L3Protocol::m_prefixes private
List of IPv6 prefix received from RA.
Definition at line 737 of file ipv6-l3-protocol.h.
Referenced by AddAutoconfiguredAddress(), DoDispose(), and RemoveAutoconfiguredAddress().
m_protocols
L4List_t ns3::Ipv6L3Protocol::m_protocols private
List of transport protocol.
Definition at line 692 of file ipv6-l3-protocol.h.
Referenced by DoDispose(), GetProtocol(), Insert(), and Remove().
m_reverseInterfacesContainer
Ipv6InterfaceReverseContainer ns3::Ipv6L3Protocol::m_reverseInterfacesContainer private
Container of NetDevice / Interface index associations.
Definition at line 702 of file ipv6-l3-protocol.h.
Referenced by AddIpv6Interface(), DoDispose(), and GetInterfaceForDevice().
m_routingProtocol
Ptr<Ipv6RoutingProtocol> ns3::Ipv6L3Protocol::m_routingProtocol private
Routing protocol.
Definition at line 727 of file ipv6-l3-protocol.h.
Referenced by AddAddress(), DoDispose(), GetRoutingProtocol(), Receive(), RemoveAddress(), Send(), SetDown(), SetRoutingProtocol(), SetUp(), and SetupLoopback().
m_rxTrace
TracedCallback<Ptr<const Packet>, Ptr<Ipv6>, uint32_t> ns3::Ipv6L3Protocol::m_rxTrace private
Callback to trace RX (reception) packets.
Deprecated:
The non-const Ptr<Ipv6> argument is deprecated and will be changed to Ptr<const Ipv6> in a future release.
Definition at line 535 of file ipv6-l3-protocol.h.
Referenced by GetTypeId(), and Receive().
m_sendIcmpv6Redirect
bool ns3::Ipv6L3Protocol::m_sendIcmpv6Redirect private
Allow ICMPv6 Redirect sending state.
Definition at line 742 of file ipv6-l3-protocol.h.
Referenced by GetSendIcmpv6Redirect(), IpForward(), and SetSendIcmpv6Redirect().
m_sendOutgoingTrace
TracedCallback<const Ipv6Header &, Ptr<const Packet>, uint32_t> ns3::Ipv6L3Protocol::m_sendOutgoingTrace private
Trace of sent packets.
Definition at line 545 of file ipv6-l3-protocol.h.
Referenced by GetTypeId(), and Send().
m_sockets
SocketList ns3::Ipv6L3Protocol::m_sockets private
List of IPv6 raw sockets.
Definition at line 732 of file ipv6-l3-protocol.h.
Referenced by CreateRawSocket(), DeleteRawSocket(), DoDispose(), and Receive().
m_strongEndSystemModel
bool ns3::Ipv6L3Protocol::m_strongEndSystemModel private
Rejects packets directed to an interface with wrong address (RFC 1222).
Definition at line 722 of file ipv6-l3-protocol.h.
Referenced by GetTypeId(), and Receive().
m_txTrace
TracedCallback<Ptr<const Packet>, Ptr<Ipv6>, uint32_t> ns3::Ipv6L3Protocol::m_txTrace private
Callback to trace TX (transmission) packets.
Deprecated:
The non-const Ptr<Ipv6> argument is deprecated and will be changed to Ptr<const Ipv6> in a future release.
Definition at line 528 of file ipv6-l3-protocol.h.
Referenced by CallTxTrace(), and GetTypeId().
m_unicastForwardTrace
TracedCallback<const Ipv6Header &, Ptr<const Packet>, uint32_t> ns3::Ipv6L3Protocol::m_unicastForwardTrace private
Trace of unicast forwarded packets.
Definition at line 547 of file ipv6-l3-protocol.h.
Referenced by GetTypeId(), and IpForward().
PROT_NUMBER
const uint16_t ns3::Ipv6L3Protocol::PROT_NUMBER = 0x86DD static
The protocol number for IPv6 (0x86DD).
Definition at line 74 of file ipv6-l3-protocol.h.
Referenced by ns3::NoBackhaulEpcHelper::AddEnb(), AddInterface(), ns3::EpcTftClassifier::Classify(), ns3::NdiscCache::Entry::FunctionDelayTimeout(), ns3::NdiscCache::Entry::FunctionProbeTimeout(), ns3::LteNetDevice::Receive(), ns3::SixLowPanNetDevice::ReceiveFromDevice(), ns3::EpcPgwApplication::RecvFromTunDevice(), ns3::Ipv6Interface::Send(), ns3::LteEnbNetDevice::Send(), ns3::LteUeNetDevice::Send(), and SetupLoopback().
The documentation for this class was generated from the following files:
src/internet/model/ipv6-l3-protocol.h
src/internet/model/ipv6-l3-protocol.cc