ns-3: ns3::LteHexGridEnbTopologyHelper Class Reference
ns3::LteHexGridEnbTopologyHelper Class Reference
LTE Models
This helper class allows to easily create a topology with eNBs grouped in three-sector sites laid out on an hexagonal grid.
#include "lte-hex-grid-enb-topology-helper.h"
Public Member Functions
LteHexGridEnbTopologyHelper (void)
virtual ~LteHexGridEnbTopologyHelper (void)
virtual void DoDispose (void)
Destructor implementation.
void SetLteHelper (Ptr< LteHelper > h)
Set the LteHelper to be used to actually create the EnbNetDevices.
NetDeviceContainer SetPositionAndInstallEnbDevice (NodeContainer c)
Position the nodes on a hex grid and install the corresponding EnbNetDevices with antenna boresight configured properly.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
double m_d
The distance [m] between nearby sites.
uint32_t m_gridWidth
The number of sites in even rows (odd rows will have one additional site)
Ptr< LteHelper > m_lteHelper
Pointer to LteHelper object.
double m_offset
The offset [m] in the position for the node of each sector with respect to the center of the three-sector site.
uint32_t m_siteHeight
The height [m] of each site.
double m_xMin
The x coordinate where the hex grid starts.
double m_yMin
The y coordinate where the hex grid starts.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This helper class allows to easily create a topology with eNBs grouped in three-sector sites laid out on an hexagonal grid.
Introspection did not find any typical Config paths.
The layout is done row-wise.
Attributes
InterSiteDistance: The distance [m] between nearby sites
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 500
Flags: construct write read
SectorOffset: The offset [m] in the position for the node of each sector with respect to the center of the three-sector site
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0.5
Flags: construct write read
SiteHeight: The height [m] of each site
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 30
Flags: construct write read
MinX: The x coordinate where the hex grid starts.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0
Flags: construct write read
MinY: The y coordinate where the hex grid starts.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0
Flags: construct write read
GridWidth: The number of sites in even rows (odd rows will have one additional site).
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 1
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 80 bytes (on a 64-bit architecture).
Definition at line 36 of file lte-hex-grid-enb-topology-helper.h.
Constructor & Destructor Documentation
LteHexGridEnbTopologyHelper()
ns3::LteHexGridEnbTopologyHelper::LteHexGridEnbTopologyHelper (void)
Definition at line 37 of file lte-hex-grid-enb-topology-helper.cc.
References NS_LOG_FUNCTION.
~LteHexGridEnbTopologyHelper()
ns3::LteHexGridEnbTopologyHelper::~LteHexGridEnbTopologyHelper (void) virtual
Definition at line 42 of file lte-hex-grid-enb-topology-helper.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::LteHexGridEnbTopologyHelper::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 87 of file lte-hex-grid-enb-topology-helper.cc.
References ns3::Object::DoDispose(), and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::LteHexGridEnbTopologyHelper::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 47 of file lte-hex-grid-enb-topology-helper.cc.
References m_d, m_gridWidth, m_offset, m_siteHeight, m_xMin, m_yMin, ns3::MakeDoubleAccessor(), ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
SetLteHelper()
void ns3::LteHexGridEnbTopologyHelper::SetLteHelper (Ptr< LteHelper > h)
Set the LteHelper to be used to actually create the EnbNetDevices.
Note
if no EpcHelper is ever set, then LteHexGridEnbTopologyHelper will default to creating an LTE-only simulation with no EPC, using LteRlcSm as the RLC model, and without supporting any IP networking. In other words, it will be a radio-level simulation involving only LTE PHY and MAC and the FF Scheduler, with a saturation traffic model for the RLC.
Parameters
h a pointer to the EpcHelper to be used
Definition at line 95 of file lte-hex-grid-enb-topology-helper.cc.
References m_lteHelper, and NS_LOG_FUNCTION.
SetPositionAndInstallEnbDevice()
NetDeviceContainer ns3::LteHexGridEnbTopologyHelper::SetPositionAndInstallEnbDevice (NodeContainer c)
Position the nodes on a hex grid and install the corresponding EnbNetDevices with antenna boresight configured properly.
Parameters
c the node container where the devices are to be installed
Returns
the NetDeviceContainer with the newly created devices
Definition at line 102 of file lte-hex-grid-enb-topology-helper.cc.
References ns3::NetDeviceContainer::Add(), ns3::NodeContainer::Get(), ns3::NodeContainer::GetN(), ns3::Object::GetObject(), ns3::LteHelper::InstallEnbDevice(), m_d, m_gridWidth, m_lteHelper, m_offset, m_siteHeight, m_xMin, m_yMin, sample-rng-plot::n, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::LteHelper::SetEnbAntennaModelAttribute(), ns3::LteHelper::SetFfrAlgorithmAttribute(), ns3::MobilityModel::SetPosition(), and sample-rng-plot::x.
Member Data Documentation
m_d
double ns3::LteHexGridEnbTopologyHelper::m_d private
The distance [m] between nearby sites.
Definition at line 89 of file lte-hex-grid-enb-topology-helper.h.
Referenced by GetTypeId(), and SetPositionAndInstallEnbDevice().
m_gridWidth
uint32_t ns3::LteHexGridEnbTopologyHelper::m_gridWidth private
The number of sites in even rows (odd rows will have one additional site)
Definition at line 105 of file lte-hex-grid-enb-topology-helper.h.
Referenced by GetTypeId(), and SetPositionAndInstallEnbDevice().
m_lteHelper
Ptr<LteHelper> ns3::LteHexGridEnbTopologyHelper::m_lteHelper private
Pointer to LteHelper object.
Definition at line 78 of file lte-hex-grid-enb-topology-helper.h.
Referenced by SetLteHelper(), and SetPositionAndInstallEnbDevice().
m_offset
double ns3::LteHexGridEnbTopologyHelper::m_offset private
The offset [m] in the position for the node of each sector with respect to the center of the three-sector site.
Definition at line 84 of file lte-hex-grid-enb-topology-helper.h.
Referenced by GetTypeId(), and SetPositionAndInstallEnbDevice().
m_siteHeight
uint32_t ns3::LteHexGridEnbTopologyHelper::m_siteHeight private
The height [m] of each site.
Definition at line 110 of file lte-hex-grid-enb-topology-helper.h.
Referenced by GetTypeId(), and SetPositionAndInstallEnbDevice().
m_xMin
double ns3::LteHexGridEnbTopologyHelper::m_xMin private
The x coordinate where the hex grid starts.
Definition at line 94 of file lte-hex-grid-enb-topology-helper.h.
Referenced by GetTypeId(), and SetPositionAndInstallEnbDevice().
m_yMin
double ns3::LteHexGridEnbTopologyHelper::m_yMin private
The y coordinate where the hex grid starts.
Definition at line 99 of file lte-hex-grid-enb-topology-helper.h.
Referenced by GetTypeId(), and SetPositionAndInstallEnbDevice().
The documentation for this class was generated from the following files:
src/lte/helper/lte-hex-grid-enb-topology-helper.h
src/lte/helper/lte-hex-grid-enb-topology-helper.cc