ns-3: ns3::Ipv6OptionHeader Class Reference
ns3::Ipv6OptionHeader Class Reference
Internet » IPv6 classes and sub-modules » IPV6 Header extension system.
Header for IPv6 Option.
#include "ipv6-option-header.h"
Classes
struct Alignment
represents the alignment requirements of an option header
Public Member Functions
Ipv6OptionHeader ()
Constructor.
virtual ~Ipv6OptionHeader ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
virtual Alignment GetAlignment () const
Get the Alignment requirement of this option header.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
uint8_t GetLength () const
Get the option length.
virtual uint32_t GetSerializedSize () const
Get the serialized size of the packet.
uint8_t GetType () const
Get the type of the option.
virtual void Print (std::ostream &os) const
Print some information about the packet.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetLength (uint8_t length)
Set the option length.
void SetType (uint8_t type)
Set the type of the option.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Buffer m_data
The anonymous data of this option.
uint8_t m_length
The option length.
uint8_t m_type
The type of the option.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Header for IPv6 Option.
Introspection did not find any typical Config paths.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 48 bytes (on a 64-bit architecture).
Definition at line 36 of file ipv6-option-header.h.
Constructor & Destructor Documentation
Ipv6OptionHeader()
ns3::Ipv6OptionHeader::Ipv6OptionHeader ()
Constructor.
Definition at line 48 of file ipv6-option-header.cc.
~Ipv6OptionHeader()
ns3::Ipv6OptionHeader::~Ipv6OptionHeader () virtual
Destructor.
Definition at line 54 of file ipv6-option-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::Ipv6OptionHeader::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start Buffer iterator
Returns
size of the packet
Implements ns3::Header.
Reimplemented in ns3::Ipv6OptionRouterAlertHeader, ns3::Ipv6OptionJumbogramHeader, ns3::Ipv6OptionPadnHeader, and ns3::Ipv6OptionPad1Header.
Definition at line 98 of file ipv6-option-header.cc.
References ns3::Buffer::AddAtEnd(), ns3::Buffer::Begin(), GetSerializedSize(), m_data, m_length, m_type, ns3::Buffer::Iterator::Next(), ns3::Buffer::Iterator::ReadU8(), visualizer.core::start(), and ns3::Buffer::Iterator::Write().
GetAlignment()
Ipv6OptionHeader::Alignment ns3::Ipv6OptionHeader::GetAlignment () const virtual
Get the Alignment requirement of this option header.
Returns
The required alignment
Subclasses should only implement this method, if special alignment is required. Default is no alignment (1n+0).
Reimplemented in OptionWithAlignmentHeader, ns3::Ipv6OptionRouterAlertHeader, and ns3::Ipv6OptionJumbogramHeader.
Definition at line 115 of file ipv6-option-header.cc.
Referenced by ns3::OptionField::AddOption().
GetInstanceTypeId()
TypeId ns3::Ipv6OptionHeader::GetInstanceTypeId (void) const virtual
Get the instance type ID.
Returns
instance type ID
Implements ns3::ObjectBase.
Reimplemented in ns3::Ipv6OptionRouterAlertHeader, ns3::Ipv6OptionJumbogramHeader, ns3::Ipv6OptionPadnHeader, and ns3::Ipv6OptionPad1Header.
Definition at line 43 of file ipv6-option-header.cc.
References GetTypeId().
GetLength()
uint8_t ns3::Ipv6OptionHeader::GetLength () const
Get the option length.
Returns
the option length
Definition at line 73 of file ipv6-option-header.cc.
References m_length.
Referenced by ns3::Ipv6OptionPadnHeader::GetSerializedSize(), ns3::Ipv6OptionJumbogramHeader::GetSerializedSize(), ns3::Ipv6OptionRouterAlertHeader::GetSerializedSize(), ns3::Ipv6OptionPadnHeader::Print(), ns3::Ipv6OptionJumbogramHeader::Print(), ns3::Ipv6OptionRouterAlertHeader::Print(), ns3::Ipv6OptionPadnHeader::Serialize(), ns3::Ipv6OptionJumbogramHeader::Serialize(), and ns3::Ipv6OptionRouterAlertHeader::Serialize().
GetSerializedSize()
uint32_t ns3::Ipv6OptionHeader::GetSerializedSize (void) const virtual
Get the serialized size of the packet.
Returns
size
Implements ns3::Header.
Reimplemented in OptionWithAlignmentHeader, OptionWithoutAlignmentHeader, ns3::Ipv6OptionRouterAlertHeader, ns3::Ipv6OptionJumbogramHeader, ns3::Ipv6OptionPadnHeader, and ns3::Ipv6OptionPad1Header.
Definition at line 83 of file ipv6-option-header.cc.
References m_length.
Referenced by ns3::OptionField::AddOption(), and Deserialize().
GetType()
uint8_t ns3::Ipv6OptionHeader::GetType (void) const
Get the type of the option.
Returns
the type of the option
Definition at line 63 of file ipv6-option-header.cc.
References m_type.
Referenced by TestOptionWithAlignment::DoRun(), TestFulfilledAlignment::DoRun(), ns3::Ipv6OptionPad1Header::Print(), ns3::Ipv6OptionPadnHeader::Print(), ns3::Ipv6OptionJumbogramHeader::Print(), ns3::Ipv6OptionRouterAlertHeader::Print(), ns3::Ipv6OptionPad1Header::Serialize(), ns3::Ipv6OptionPadnHeader::Serialize(), ns3::Ipv6OptionJumbogramHeader::Serialize(), and ns3::Ipv6OptionRouterAlertHeader::Serialize().
GetTypeId()
TypeId ns3::Ipv6OptionHeader::GetTypeId (void) static
Get the type identificator.
Returns
type identificator
Definition at line 33 of file ipv6-option-header.cc.
References ns3::TypeId::AddConstructor().
Referenced by GetInstanceTypeId().
Print()
void ns3::Ipv6OptionHeader::Print (std::ostream & os) const virtual
Print some information about the packet.
Parameters
os output stream
Returns
info about this packet
Implements ns3::Header.
Reimplemented in ns3::Ipv6OptionRouterAlertHeader, ns3::Ipv6OptionJumbogramHeader, ns3::Ipv6OptionPadnHeader, and ns3::Ipv6OptionPad1Header.
Definition at line 78 of file ipv6-option-header.cc.
References m_type.
Serialize()
void ns3::Ipv6OptionHeader::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start Buffer iterator
Implements ns3::Header.
Reimplemented in OptionWithAlignmentHeader, OptionWithoutAlignmentHeader, ns3::Ipv6OptionRouterAlertHeader, ns3::Ipv6OptionJumbogramHeader, ns3::Ipv6OptionPadnHeader, and ns3::Ipv6OptionPad1Header.
Definition at line 88 of file ipv6-option-header.cc.
References ns3::Buffer::Begin(), ns3::Buffer::End(), m_data, m_length, m_type, visualizer.core::start(), ns3::Buffer::Iterator::Write(), and ns3::Buffer::Iterator::WriteU8().
Referenced by ns3::OptionField::AddOption().
SetLength()
void ns3::Ipv6OptionHeader::SetLength (uint8_t length)
Set the option length.
Parameters
length the option length
Definition at line 68 of file ipv6-option-header.cc.
References m_length.
Referenced by ns3::Ipv6OptionJumbogramHeader::Ipv6OptionJumbogramHeader(), ns3::Ipv6OptionPadnHeader::Ipv6OptionPadnHeader(), ns3::Ipv6OptionRouterAlertHeader::Ipv6OptionRouterAlertHeader(), ns3::Ipv6OptionPadnHeader::Deserialize(), ns3::Ipv6OptionJumbogramHeader::Deserialize(), and ns3::Ipv6OptionRouterAlertHeader::Deserialize().
SetType()
void ns3::Ipv6OptionHeader::SetType (uint8_t type)
Set the type of the option.
Parameters
type the type of the option
Definition at line 58 of file ipv6-option-header.cc.
References m_type.
Referenced by ns3::Ipv6OptionJumbogramHeader::Ipv6OptionJumbogramHeader(), ns3::Ipv6OptionPad1Header::Ipv6OptionPad1Header(), ns3::Ipv6OptionPadnHeader::Ipv6OptionPadnHeader(), ns3::Ipv6OptionRouterAlertHeader::Ipv6OptionRouterAlertHeader(), ns3::Ipv6OptionPad1Header::Deserialize(), ns3::Ipv6OptionPadnHeader::Deserialize(), ns3::Ipv6OptionJumbogramHeader::Deserialize(), and ns3::Ipv6OptionRouterAlertHeader::Deserialize().
Member Data Documentation
m_data
Buffer ns3::Ipv6OptionHeader::m_data private
The anonymous data of this option.
Definition at line 148 of file ipv6-option-header.h.
Referenced by Deserialize(), and Serialize().
m_length
uint8_t ns3::Ipv6OptionHeader::m_length private
The option length.
Definition at line 143 of file ipv6-option-header.h.
Referenced by Deserialize(), GetLength(), GetSerializedSize(), Serialize(), and SetLength().
m_type
uint8_t ns3::Ipv6OptionHeader::m_type private
The type of the option.
Definition at line 138 of file ipv6-option-header.h.
Referenced by Deserialize(), GetType(), Print(), Serialize(), and SetType().
The documentation for this class was generated from the following files:
src/internet/model/ipv6-option-header.h
src/internet/model/ipv6-option-header.cc