ns-3: ns3::WifiRemoteStationManager Class Reference
ns3::WifiRemoteStationManager Class Reference abstract
Wifi Models
hold a list of per-remote-station state.
#include "wifi-remote-station-manager.h"
Public Types
typedef void(* PowerChangeTracedCallback) (double oldPower, double newPower, Mac48Address remoteAddress)
TracedCallback signature for power change events.
enum ProtectionMode { RTS_CTS , CTS_TO_SELF }
ProtectionMode enumeration.
typedef void(* RateChangeTracedCallback) (DataRate oldRate, DataRate newRate, Mac48Address remoteAddress)
TracedCallback signature for rate change events.
typedef std::vector< WifiRemoteStation * > Stations
A vector of WifiRemoteStations.
typedef std::vector< WifiRemoteStationState * > StationStates
A vector of WifiRemoteStationStates.
Public Member Functions
WifiRemoteStationManager ()
virtual ~WifiRemoteStationManager ()
void AddAllSupportedMcs (Mac48Address address)
Invoked in a STA or AP to store all of the MCS supported by a destination which is also supported locally.
void AddAllSupportedModes (Mac48Address address)
Invoked in a STA or AP to store all of the modes supported by a destination which is also supported locally.
void AddBasicMcs (WifiMode mcs)
Add a given Modulation and Coding Scheme (MCS) index to the set of basic MCS.
void AddBasicMode (WifiMode mode)
Invoked in a STA upon association to store the set of rates which belong to the BSSBasicRateSet of the associated AP and which are supported locally.
void AddStationHeCapabilities (Mac48Address from, HeCapabilities heCapabilities)
Records HE capabilities of the remote station.
void AddStationHtCapabilities (Mac48Address from, HtCapabilities htCapabilities)
Records HT capabilities of the remote station.
void AddStationVhtCapabilities (Mac48Address from, VhtCapabilities vhtCapabilities)
Records VHT capabilities of the remote station.
void AddSupportedErpSlotTime (Mac48Address address, bool isShortSlotTimeSupported)
Record whether the short ERP slot time is supported by the station.
void AddSupportedMcs (Mac48Address address, WifiMode mcs)
Record the MCS index supported by the station.
void AddSupportedMode (Mac48Address address, WifiMode mode)
Invoked in a STA or AP to store the set of modes supported by a destination which is also supported locally.
void AddSupportedPhyPreamble (Mac48Address address, bool isShortPreambleSupported)
Record whether the short PHY preamble is supported by the station.
WifiMode GetBasicMcs (uint8_t i) const
Return the MCS at the given list index.
WifiMode GetBasicMode (uint8_t i) const
Return a basic mode from the set of basic modes.
uint16_t GetChannelWidthSupported (Mac48Address address) const
Return the channel width supported by the station.
WifiTxVector GetCtsToSelfTxVector (void)
Since CTS-to-self parameters are not dependent on the station, it is implemented in wifi remote station manager.
WifiTxVector GetDataTxVector (const WifiMacHeader &header)
WifiMode GetDefaultMcs (void) const
Return the default Modulation and Coding Scheme (MCS) index.
WifiMode GetDefaultMode (void) const
Return the default transmission mode.
uint8_t GetDefaultTxPowerLevel (void) const
uint32_t GetFragmentationThreshold (void) const
Return the fragmentation threshold.
uint32_t GetFragmentOffset (Mac48Address address, const WifiMacHeader *header, Ptr< const Packet > packet, uint32_t fragmentNumber)
uint32_t GetFragmentSize (Mac48Address address, const WifiMacHeader *header, Ptr< const Packet > packet, uint32_t fragmentNumber)
bool GetGreenfieldSupported (Mac48Address address) const
Return whether the station supports Greenfield or not.
bool GetGreenfieldSupported (void) const
Return whether the device has HT Greenfield support enabled.
uint16_t GetGuardInterval (void) const
Return the supported HE guard interval duration (in nanoseconds).
bool GetHeSupported (Mac48Address address) const
Return whether the station supports HE or not.
bool GetHeSupported (void) const
Return whether the device has HE capability support enabled.
bool GetHtSupported (Mac48Address address) const
Return whether the station supports HT or not.
bool GetHtSupported (void) const
Return whether the device has HT capability support enabled.
WifiRemoteStationInfo GetInfo (Mac48Address address)
bool GetLdpcSupported (Mac48Address address) const
Return whether the station supports LDPC or not.
bool GetLdpcSupported (void) const
Return whether the device has LDPC support enabled.
uint8_t GetMaxNumberOfTransmitStreams (void) const
uint8_t GetNBasicMcs (void) const
Return the number of basic MCS index.
uint8_t GetNBasicModes (void) const
Return the number of basic modes we support.
uint8_t GetNMcsSupported (Mac48Address address) const
Return the number of MCS supported by the station.
uint32_t GetNNonErpBasicModes (void) const
Return the number of non-ERP basic modes we support.
WifiMode GetNonErpBasicMode (uint8_t i) const
Return a basic mode from the set of basic modes that is not an ERP mode.
WifiMode GetNonUnicastMode (void) const
Return a mode for non-unicast packets.
uint8_t GetNumberOfAntennas (void) const
uint8_t GetNumberOfSupportedStreams (Mac48Address address) const
Return the number of spatial streams supported by the station.
bool GetPcfSupported (void) const
Return whether the device has PCF capability support enabled.
bool GetQosSupported (Mac48Address address) const
Return whether the given station is QoS capable.
WifiTxVector GetRtsTxVector (Mac48Address address)
bool GetShortGuardIntervalSupported (Mac48Address address) const
Return whether the station supports HT/VHT short guard interval.
bool GetShortGuardIntervalSupported (void) const
Return whether the device has SGI support enabled.
bool GetShortPreambleEnabled (void) const
Return whether the device uses short PHY preambles.
bool GetShortPreambleSupported (Mac48Address address) const
Return whether the station supports short PHY preamble or not.
bool GetShortSlotTimeEnabled (void) const
Return whether the device uses short slot time.
bool GetShortSlotTimeSupported (Mac48Address address) const
Return whether the station supports short ERP slot time or not.
Ptr< const HeCapabilities > GetStationHeCapabilities (Mac48Address from)
Return the HE capabilities sent by the remote station.
Ptr< const HtCapabilities > GetStationHtCapabilities (Mac48Address from)
Return the HT capabilities sent by the remote station.
Ptr< const VhtCapabilities > GetStationVhtCapabilities (Mac48Address from)
Return the VHT capabilities sent by the remote station.
bool GetUseGreenfieldProtection (void) const
Return whether protection for stations that do not support HT Greenfield format is enabled.
bool GetUseNonErpProtection (void) const
Return whether the device supports protection of non-ERP stations.
bool GetUseNonHtProtection (void) const
Return whether the device supports protection of non-HT stations.
bool GetVhtSupported (Mac48Address address) const
Return whether the station supports VHT or not.
bool GetVhtSupported (void) const
Return whether the device has VHT capability support enabled.
bool IsAssociated (Mac48Address address) const
Return whether the station associated.
bool IsBrandNew (Mac48Address address) const
Return whether the station state is brand new.
bool IsLastFragment (Mac48Address address, const WifiMacHeader *header, Ptr< const Packet > packet, uint32_t fragmentNumber)
bool IsWaitAssocTxOk (Mac48Address address) const
Return whether we are waiting for an ACK for the association response we sent.
bool NeedCtsToSelf (WifiTxVector txVector)
Return if we need to do CTS-to-self before sending a DATA.
bool NeedFragmentation (Mac48Address address, const WifiMacHeader *header, Ptr< const Packet > packet)
bool NeedRetransmission (Mac48Address address, const WifiMacHeader *header, Ptr< const Packet > packet)
bool NeedRts (const WifiMacHeader &header, uint32_t size)
void RecordDisassociated (Mac48Address address)
Records that the STA was disassociated.
void RecordGotAssocTxFailed (Mac48Address address)
Records that we missed an ACK for the association response we sent.
void RecordGotAssocTxOk (Mac48Address address)
Records that we got an ACK for the association response we sent.
void RecordWaitAssocTxOk (Mac48Address address)
Records that we are waiting for an ACK for the association response we sent.
void RemoveAllSupportedMcs (Mac48Address address)
Invoked in a STA or AP to delete all of the supported MCS by a destination.
void ReportAmpduTxStatus (Mac48Address address, uint8_t nSuccessfulMpdus, uint8_t nFailedMpdus, double rxSnr, double dataSnr, WifiTxVector dataTxVector)
Typically called per A-MPDU, either when a Block ACK was successfully received or when a BlockAckTimeout has elapsed.
void ReportDataFailed (Mac48Address address, const WifiMacHeader *header, uint32_t packetSize)
Should be invoked whenever the AckTimeout associated to a transmission attempt expires.
void ReportDataOk (Mac48Address address, const WifiMacHeader *header, double ackSnr, WifiMode ackMode, double dataSnr, WifiTxVector dataTxVector, uint32_t packetSize)
Should be invoked whenever we receive the ACK associated to a data packet we just sent.
void ReportFinalDataFailed (Mac48Address address, const WifiMacHeader *header, uint32_t packetSize)
Should be invoked after calling ReportDataFailed if NeedRetransmission returns false.
void ReportFinalRtsFailed (Mac48Address address, const WifiMacHeader *header)
Should be invoked after calling ReportRtsFailed if NeedRetransmission returns false.
void ReportRtsFailed (Mac48Address address, const WifiMacHeader *header)
Should be invoked whenever the RtsTimeout associated to a transmission attempt expires.
void ReportRtsOk (Mac48Address address, const WifiMacHeader *header, double ctsSnr, WifiMode ctsMode, double rtsSnr)
Should be invoked whenever we receive the CTS associated to an RTS we just sent.
void ReportRxOk (Mac48Address address, double rxSnr, WifiMode txMode)
void Reset (void)
Reset the station, invoked in a STA upon dis-association or in an AP upon reboot.
void SetDefaultTxPowerLevel (uint8_t txPower)
Set the default transmission power level.
void SetFragmentationThreshold (uint32_t threshold)
Sets a fragmentation threshold.
void SetMaxSlrc (uint32_t maxSlrc)
Sets the maximum STA long retry count (SLRC).
void SetMaxSsrc (uint32_t maxSsrc)
Sets the maximum STA short retry count (SSRC).
void SetPcfSupported (bool enable)
Enable or disable PCF capability support.
void SetQosSupport (Mac48Address from, bool qosSupported)
Records QoS support of the remote station.
void SetRtsCtsThreshold (uint32_t threshold)
Sets the RTS threshold.
void SetShortPreambleEnabled (bool enable)
Enable or disable short PHY preambles.
void SetShortSlotTimeEnabled (bool enable)
Enable or disable short slot time.
virtual void SetupMac (const Ptr< WifiMac > mac)
Set up MAC associated with this device since it is the object that knows the full set of timing parameters (e.g.
virtual void SetupPhy (const Ptr< WifiPhy > phy)
Set up PHY associated with this device since it is the object that knows the full set of transmit rates that are supported.
void SetUseGreenfieldProtection (bool enable)
Enable or disable protection for stations that do not support HT Greenfield format.
void SetUseNonErpProtection (bool enable)
Enable or disable protection for non-ERP stations.
void SetUseNonHtProtection (bool enable)
Enable or disable protection for non-HT stations.
void UpdateFragmentationThreshold (void)
Typically called to update the fragmentation threshold at the start of a new transmission.
bool UseGreenfieldForDestination (Mac48Address dest) const
bool UseLdpcForDestination (Mac48Address dest) const
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Mac48Address GetAddress (const WifiRemoteStation *station) const
Return the address of the station.
bool GetAggregation (const WifiRemoteStation *station) const
Return whether the given station supports A-MPDU.
uint16_t GetChannelWidth (const WifiRemoteStation *station) const
Return the channel width supported by the station.
bool GetGreenfield (const WifiRemoteStation *station) const
Return whether the station supports Greenfield or not.
uint16_t GetGuardInterval (const WifiRemoteStation *station) const
Return the HE guard interval duration supported by the station.
bool GetHeSupported (const WifiRemoteStation *station) const
Return whether the given station is HE capable.
bool GetHtSupported (const WifiRemoteStation *station) const
Return whether the given station is HT capable.
Ptr< WifiMac > GetMac (void) const
Return the WifiMac.
WifiMode GetMcsSupported (const WifiRemoteStation *station, uint8_t i) const
Return the WifiMode supported by the specified station at the specified index.
uint8_t GetNess (const WifiRemoteStation *station) const
uint8_t GetNMcsSupported (const WifiRemoteStation *station) const
Return the number of MCS supported by the given station.
uint32_t GetNNonErpSupported (const WifiRemoteStation *station) const
Return the number of non-ERP modes supported by the given station.
WifiMode GetNonErpSupported (const WifiRemoteStation *station, uint8_t i) const
Return whether non-ERP mode associated with the specified station at the specified index.
uint8_t GetNSupported (const WifiRemoteStation *station) const
Return the number of modes supported by the given station.
uint8_t GetNumberOfSupportedStreams (const WifiRemoteStation *station) const
Return the number of supported streams the station has.
Ptr< WifiPhy > GetPhy (void) const
Return the WifiPhy.
bool GetQosSupported (const WifiRemoteStation *station) const
Return whether the given station is QoS capable.
bool GetShortGuardIntervalSupported (const WifiRemoteStation *station) const
Return whether the given station supports HT/VHT short guard interval.
WifiMode GetSupported (const WifiRemoteStation *station, uint8_t i) const
Return whether mode associated with the specified station at the specified index.
bool GetVhtSupported (const WifiRemoteStation *station) const
Return whether the given station is VHT capable.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
virtual WifiRemoteStation * DoCreateStation (void) const =0
virtual WifiTxVector DoGetDataTxVector (WifiRemoteStation *station)=0
uint32_t DoGetFragmentationThreshold (void) const
Return the current fragmentation threshold.
virtual WifiTxVector DoGetRtsTxVector (WifiRemoteStation *station)=0
virtual bool DoNeedFragmentation (WifiRemoteStation *station, Ptr< const Packet > packet, bool normally)
virtual bool DoNeedRetransmission (WifiRemoteStation *station, Ptr< const Packet > packet, bool normally)
virtual bool DoNeedRts (WifiRemoteStation *station, uint32_t size, bool normally)
virtual void DoReportAmpduTxStatus (WifiRemoteStation *station, uint8_t nSuccessfulMpdus, uint8_t nFailedMpdus, double rxSnr, double dataSnr, uint16_t dataChannelWidth, uint8_t dataNss)
Typically called per A-MPDU, either when a Block ACK was successfully received or when a BlockAckTimeout has elapsed.
virtual void DoReportDataFailed (WifiRemoteStation *station)=0
This method is a pure virtual method that must be implemented by the sub-class.
virtual void DoReportDataOk (WifiRemoteStation *station, double ackSnr, WifiMode ackMode, double dataSnr, uint16_t dataChannelWidth, uint8_t dataNss)=0
This method is a pure virtual method that must be implemented by the sub-class.
virtual void DoReportFinalDataFailed (WifiRemoteStation *station)=0
This method is a pure virtual method that must be implemented by the sub-class.
virtual void DoReportFinalRtsFailed (WifiRemoteStation *station)=0
This method is a pure virtual method that must be implemented by the sub-class.
virtual void DoReportRtsFailed (WifiRemoteStation *station)=0
This method is a pure virtual method that must be implemented by the sub-class.
virtual void DoReportRtsOk (WifiRemoteStation *station, double ctsSnr, WifiMode ctsMode, double rtsSnr)=0
This method is a pure virtual method that must be implemented by the sub-class.
virtual void DoReportRxOk (WifiRemoteStation *station, double rxSnr, WifiMode txMode)=0
This method is a pure virtual method that must be implemented by the sub-class.
void DoSetFragmentationThreshold (uint32_t threshold)
Actually sets the fragmentation threshold, it also checks the validity of the given threshold.
uint32_t GetNFragments (const WifiMacHeader *header, Ptr< const Packet > packet)
Return the number of fragments needed for the given packet.
WifiRemoteStation * Lookup (Mac48Address address) const
Return the station associated with the given address.
WifiRemoteStationState * LookupState (Mac48Address address) const
Return the state of the station associated with the given address.
Private Attributes
WifiModeList m_bssBasicMcsSet
basic MCS set
WifiModeList m_bssBasicRateSet
This member is the list of WifiMode objects that comprise the BSSBasicRateSet parameter.
WifiMode m_defaultTxMcs
The default transmission modulation-coding scheme (MCS)
WifiMode m_defaultTxMode
The default transmission mode.
uint8_t m_defaultTxPowerLevel
Default transmission power level.
ProtectionMode m_erpProtectionMode
Protection mode for ERP stations when non-ERP stations are detected.
uint32_t m_fragmentationThreshold
Current threshold for fragmentation.
ProtectionMode m_htProtectionMode
Protection mode for HT stations when non-HT stations are detected.
TracedCallback< Mac48Address > m_macTxDataFailed
The trace source fired when the transmission of a single data packet has failed.
TracedCallback< Mac48Address > m_macTxFinalDataFailed
The trace source fired when the transmission of a data packet has exceeded the maximum number of attempts.
TracedCallback< Mac48Address > m_macTxFinalRtsFailed
The trace source fired when the transmission of a RTS has exceeded the maximum number of attempts.
TracedCallback< Mac48Address > m_macTxRtsFailed
The trace source fired when the transmission of a single RTS has failed.
uint32_t m_maxSlrc
Maximum STA long retry count (SLRC)
uint32_t m_maxSsrc
Maximum STA short retry count (SSRC)
uint32_t m_nextFragmentationThreshold
Threshold for fragmentation that will be used for the next transmission.
WifiMode m_nonUnicastMode
Transmission mode for non-unicast Data frames.
bool m_pcfSupported
Flag if PCF capability is supported.
uint32_t m_rtsCtsThreshold
Threshold for RTS/CTS.
bool m_shortPreambleEnabled
flag if short PHY preamble is enabled
bool m_shortSlotTimeEnabled
flag if short slot time is enabled
std::array< uint32_t, AC_BE_NQOS > m_slrc
long retry count per AC
std::array< uint32_t, AC_BE_NQOS > m_ssrc
short retry count per AC
StationStates m_states
States of known stations.
Stations m_stations
Information for each known stations.
bool m_useGreenfieldProtection
flag if protection for stations that do not support HT Greenfield format is enabled
bool m_useNonErpProtection
flag if protection for non-ERP stations against ERP transmissions is enabled
bool m_useNonHtProtection
flag if protection for non-HT stations against HT transmissions is enabled
Ptr< WifiMac > m_wifiMac
This is a pointer to the WifiMac associated with this WifiRemoteStationManager that is set on call to WifiRemoteStationManager::SetupMac().
Ptr< WifiPhy > m_wifiPhy
This is a pointer to the WifiPhy associated with this WifiRemoteStationManager that is set on call to WifiRemoteStationManager::SetupPhy().
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
hold a list of per-remote-station state.
See also
ns3::WifiRemoteStation.
Config Paths
ns3::WifiRemoteStationManager is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/RemoteStationManager"
Attributes
MaxSsrc: The maximum number of retransmission attempts for any packet with size <= RtsCtsThreshold. This value will not have any effect on some rate control algorithms.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 7
Flags: construct write
MaxSlrc: The maximum number of retransmission attempts for any packet with size > RtsCtsThreshold. This value will not have any effect on some rate control algorithms.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 4
Flags: construct write
RtsCtsThreshold: If the size of the PSDU is bigger than this value, we use an RTS/CTS handshake before sending the data frame.This value will not have any effect on some rate control algorithms.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 65535
Flags: construct write
FragmentationThreshold: If the size of the PSDU is bigger than this value, we fragment it such that the size of the fragments are equal or smaller. This value does not apply when it is carried in an A-MPDU. This value will not have any effect on some rate control algorithms.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 65535
Flags: construct write read
NonUnicastMode: Wifi mode used for non-unicast transmissions.
Set with class: WifiModeValue
Underlying type: WifiMode
Initial value: Invalid-WifiMode
Flags: construct write read
DefaultTxPowerLevel: Default power level to be used for transmissions. This is the power level that is used by all those WifiManagers that do not implement TX power control.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Initial value: 0
Flags: construct write read
ErpProtectionMode: Protection mode used when non-ERP STAs are connected to an ERP AP: Rts-Cts or Cts-To-Self
Set with class: ns3::EnumValue
Underlying type:
Initial value: Cts-To-Self
Flags: construct write read
HtProtectionMode: Protection mode used when non-HT STAs are connected to a HT AP: Rts-Cts or Cts-To-Self
Set with class: ns3::EnumValue
Underlying type:
Initial value: Cts-To-Self
Flags: construct write read
TraceSources
MacTxRtsFailed: The transmission of a RTS by the MAC layer has failed
Callback signature: ns3::Mac48Address::TracedCallback
MacTxDataFailed: The transmission of a data packet by the MAC layer has failed
Callback signature: ns3::Mac48Address::TracedCallback
MacTxFinalRtsFailed: The transmission of a RTS has exceeded the maximum number of attempts
Callback signature: ns3::Mac48Address::TracedCallback
MacTxFinalDataFailed: The transmission of a data packet has exceeded the maximum number of attempts
Callback signature: ns3::Mac48Address::TracedCallback
Size of this type is 328 bytes (on a 64-bit architecture).
Definition at line 112 of file wifi-remote-station-manager.h.
Member Typedef Documentation
PowerChangeTracedCallback
typedef void(* ns3::WifiRemoteStationManager::PowerChangeTracedCallback) (double oldPower, double newPower, Mac48Address remoteAddress)
TracedCallback signature for power change events.
Parameters
[in] oldPower The previous power (in dBm).
[in] newPower The new power (in dBm).
[in] address The remote station MAC address.
Definition at line 886 of file wifi-remote-station-manager.h.
RateChangeTracedCallback
typedef void(* ns3::WifiRemoteStationManager::RateChangeTracedCallback) (DataRate oldRate, DataRate newRate, Mac48Address remoteAddress)
TracedCallback signature for rate change events.
Parameters
[in] oldRate The previous data rate.
[in] newRate The new data rate.
[in] address The remote station MAC address.
Definition at line 895 of file wifi-remote-station-manager.h.
Stations
typedef std::vector<WifiRemoteStation *> ns3::WifiRemoteStationManager::Stations
A vector of WifiRemoteStations.
Definition at line 134 of file wifi-remote-station-manager.h.
StationStates
typedef std::vector<WifiRemoteStationState *> ns3::WifiRemoteStationManager::StationStates
A vector of WifiRemoteStationStates.
Definition at line 138 of file wifi-remote-station-manager.h.
Member Enumeration Documentation
ProtectionMode
enum ns3::WifiRemoteStationManager::ProtectionMode
ProtectionMode enumeration.
Enumerator
RTS_CTS
CTS_TO_SELF
Definition at line 125 of file wifi-remote-station-manager.h.
Constructor & Destructor Documentation
WifiRemoteStationManager()
ns3::WifiRemoteStationManager::WifiRemoteStationManager ()
Definition at line 117 of file wifi-remote-station-manager.cc.
References NS_LOG_FUNCTION.
~WifiRemoteStationManager()
ns3::WifiRemoteStationManager::~WifiRemoteStationManager () virtual
Definition at line 128 of file wifi-remote-station-manager.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddAllSupportedMcs()
void ns3::WifiRemoteStationManager::AddAllSupportedMcs (Mac48Address address)
Invoked in a STA or AP to store all of the MCS supported by a destination which is also supported locally.
Parameters
address the address of the station being recorded
Definition at line 389 of file wifi-remote-station-manager.cc.
References first::address, ns3::WifiPhy::GetMcs(), ns3::WifiPhy::GetNMcs(), LookupState(), ns3::WifiRemoteStationState::m_operationalMcsSet, m_wifiPhy, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::OcbWifiMac::Receive(), and ns3::AdhocWifiMac::Receive().
AddAllSupportedModes()
void ns3::WifiRemoteStationManager::AddAllSupportedModes (Mac48Address address)
Invoked in a STA or AP to store all of the modes supported by a destination which is also supported locally.
The set of supported modes includes the BSSBasicRateSet.
Parameters
address the address of the station being recorded
Definition at line 372 of file wifi-remote-station-manager.cc.
References AddBasicMode(), first::address, ns3::WifiPhy::GetMode(), ns3::WifiPhy::GetNModes(), ns3::WifiMode::IsMandatory(), LookupState(), ns3::WifiRemoteStationState::m_operationalRateSet, m_wifiPhy, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::OcbWifiMac::Receive(), and ns3::AdhocWifiMac::Receive().
AddBasicMcs()
void ns3::WifiRemoteStationManager::AddBasicMcs (WifiMode mcs)
Add a given Modulation and Coding Scheme (MCS) index to the set of basic MCS.
Parameters
mcs the WifiMode to be added to the basic MCS set
Definition at line 1359 of file wifi-remote-station-manager.cc.
References GetBasicMcs(), ns3::WifiMode::GetMcsValue(), GetNBasicMcs(), m_bssBasicMcsSet, and NS_LOG_FUNCTION.
AddBasicMode()
void ns3::WifiRemoteStationManager::AddBasicMode (WifiMode mode)
Invoked in a STA upon association to store the set of rates which belong to the BSSBasicRateSet of the associated AP and which are supported locally.
Invoked in an AP to configure the BSSBasicRateSet.
Parameters
mode the WifiMode to be added to the basic mode set
Definition at line 1288 of file wifi-remote-station-manager.cc.
References GetBasicMode(), ns3::WifiMode::GetModulationClass(), GetNBasicModes(), m_bssBasicRateSet, NS_FATAL_ERROR, NS_LOG_FUNCTION, and ns3::WIFI_MOD_CLASS_HT.
Referenced by AddAllSupportedModes(), ns3::ApWifiMac::GetSupportedRates(), ns3::MeshWifiInterfaceMac::Receive(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromProbeResp().
AddStationHeCapabilities()
void ns3::WifiRemoteStationManager::AddStationHeCapabilities (Mac48Address from, HeCapabilities heCapabilities)
Records HE capabilities of the remote station.
Parameters
from the address of the station being recorded
heCapabilities the HE capabilities of the station
Definition at line 1145 of file wifi-remote-station-manager.cc.
References AddSupportedMcs(), ns3::HeCapabilities::GetChannelWidthSet(), ns3::HeCapabilities::GetHeLtfAndGiForHePpdus(), ns3::HeCapabilities::GetHighestMcsSupported(), ns3::HeCapabilities::GetHighestNssSupported(), ns3::WifiPhy::GetMaxSupportedTxSpatialStreams(), ns3::WifiPhy::GetMcs(), ns3::WifiMode::GetModulationClass(), ns3::WifiPhy::GetNMcs(), ns3::WifiPhy::GetPhyBand(), LookupState(), ns3::WifiRemoteStationState::m_channelWidth, ns3::WifiRemoteStationState::m_guardInterval, ns3::WifiRemoteStationState::m_heCapabilities, m_wifiPhy, NS_LOG_FUNCTION, SetQosSupport(), ns3::WIFI_MOD_CLASS_HE, ns3::WIFI_PHY_BAND_2_4GHZ, ns3::WIFI_PHY_BAND_5GHZ, and ns3::WIFI_PHY_BAND_6GHZ.
Referenced by HeAggregationTest::DoRunSubTest(), ns3::AdhocWifiMac::Enqueue(), ns3::AdhocWifiMac::Receive(), ns3::ApWifiMac::Receive(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
AddStationHtCapabilities()
void ns3::WifiRemoteStationManager::AddStationHtCapabilities (Mac48Address from, HtCapabilities htCapabilities)
Records HT capabilities of the remote station.
Parameters
from the address of the station being recorded
htCapabilities the HT capabilities of the station
Definition at line 1083 of file wifi-remote-station-manager.cc.
References AddSupportedMcs(), ns3::WifiPhy::GetMcs(), ns3::WifiMode::GetMcsValue(), ns3::WifiMode::GetModulationClass(), ns3::WifiPhy::GetNMcs(), ns3::HtCapabilities::GetSupportedChannelWidth(), ns3::HtCapabilities::IsSupportedMcs(), LookupState(), ns3::WifiRemoteStationState::m_channelWidth, ns3::WifiRemoteStationState::m_htCapabilities, m_wifiPhy, NS_LOG_FUNCTION, SetQosSupport(), and ns3::WIFI_MOD_CLASS_HT.
Referenced by AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::OcbWifiMac::Receive(), ns3::AdhocWifiMac::Receive(), ns3::ApWifiMac::Receive(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
AddStationVhtCapabilities()
void ns3::WifiRemoteStationManager::AddStationVhtCapabilities (Mac48Address from, VhtCapabilities vhtCapabilities)
Records VHT capabilities of the remote station.
Parameters
from the address of the station being recorded
vhtCapabilities the VHT capabilities of the station
Definition at line 1110 of file wifi-remote-station-manager.cc.
References AddSupportedMcs(), ns3::WifiPhy::GetChannelWidth(), ns3::WifiPhy::GetMaxSupportedTxSpatialStreams(), ns3::WifiPhy::GetMcs(), ns3::WifiMode::GetMcsValue(), ns3::WifiMode::GetModulationClass(), ns3::WifiPhy::GetNMcs(), ns3::VhtCapabilities::GetSupportedChannelWidthSet(), ns3::VhtCapabilities::IsSupportedMcs(), LookupState(), ns3::WifiRemoteStationState::m_channelWidth, ns3::WifiRemoteStationState::m_vhtCapabilities, m_wifiPhy, NS_LOG_FUNCTION, and ns3::WIFI_MOD_CLASS_VHT.
Referenced by ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::OcbWifiMac::Receive(), ns3::AdhocWifiMac::Receive(), ns3::ApWifiMac::Receive(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
AddSupportedErpSlotTime()
void ns3::WifiRemoteStationManager::AddSupportedErpSlotTime (Mac48Address address, bool isShortSlotTimeSupported)
Record whether the short ERP slot time is supported by the station.
Parameters
address the address of the station
isShortSlotTimeSupported whether or not short ERP slot time is supported by the station
Definition at line 346 of file wifi-remote-station-manager.cc.
References first::address, LookupState(), ns3::WifiRemoteStationState::m_shortSlotTime, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::ApWifiMac::Receive().
AddSupportedMcs()
void ns3::WifiRemoteStationManager::AddSupportedMcs (Mac48Address address, WifiMode mcs)
Record the MCS index supported by the station.
Parameters
address the address of the station
mcs the WifiMode supported by the station
Definition at line 411 of file wifi-remote-station-manager.cc.
References first::address, LookupState(), ns3::WifiRemoteStationState::m_operationalMcsSet, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by AddStationHeCapabilities(), AddStationHtCapabilities(), AddStationVhtCapabilities(), ns3::ApWifiMac::Receive(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
AddSupportedMode()
void ns3::WifiRemoteStationManager::AddSupportedMode (Mac48Address address, WifiMode mode)
Invoked in a STA or AP to store the set of modes supported by a destination which is also supported locally.
The set of supported modes includes the BSSBasicRateSet.
Parameters
address the address of the station being recorded
mode the WifiMode supports by the station
Definition at line 355 of file wifi-remote-station-manager.cc.
References first::address, LookupState(), ns3::WifiRemoteStationState::m_operationalRateSet, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::MeshWifiInterfaceMac::ForwardDown(), ns3::MeshWifiInterfaceMac::Receive(), ns3::ApWifiMac::Receive(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), ns3::StaWifiMac::UpdateApInfoFromBeacon(), and ns3::StaWifiMac::UpdateApInfoFromProbeResp().
AddSupportedPhyPreamble()
void ns3::WifiRemoteStationManager::AddSupportedPhyPreamble (Mac48Address address, bool isShortPreambleSupported)
Record whether the short PHY preamble is supported by the station.
Parameters
address the address of the station
isShortPreambleSupported whether or not short PHY preamble is supported by the station
Definition at line 337 of file wifi-remote-station-manager.cc.
References first::address, LookupState(), ns3::WifiRemoteStationState::m_shortPreamble, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::ApWifiMac::Receive().
DoCreateStation()
virtual WifiRemoteStation* ns3::WifiRemoteStationManager::DoCreateStation (void) const private pure virtual
Returns
a new station data structure
Implemented in ns3::RrpaaWifiManager, ns3::RraaWifiManager, ns3::ParfWifiManager, ns3::OnoeWifiManager, ns3::MinstrelWifiManager, ns3::MinstrelHtWifiManager, ns3::IdealWifiManager, ns3::ConstantRateWifiManager, ns3::CaraWifiManager, ns3::ArfWifiManager, ns3::AparfWifiManager, ns3::AmrrWifiManager, ns3::AarfcdWifiManager, and ns3::AarfWifiManager.
Referenced by Lookup().
DoDispose()
void ns3::WifiRemoteStationManager::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 134 of file wifi-remote-station-manager.cc.
References NS_LOG_FUNCTION, and Reset().
DoGetDataTxVector()
virtual WifiTxVector ns3::WifiRemoteStationManager::DoGetDataTxVector (WifiRemoteStation * station) private pure virtual
Parameters
station the station that we need to communicate
Returns
the TXVECTOR to use to send a packet to the station
Note: This method is called before sending a unicast packet or a fragment of a unicast packet to decide which transmission mode to use.
Implemented in ns3::RrpaaWifiManager, ns3::RraaWifiManager, ns3::ParfWifiManager, ns3::OnoeWifiManager, ns3::MinstrelWifiManager, ns3::MinstrelHtWifiManager, ns3::IdealWifiManager, ns3::ConstantRateWifiManager, ns3::CaraWifiManager, ns3::ArfWifiManager, ns3::AparfWifiManager, ns3::AmrrWifiManager, ns3::AarfcdWifiManager, and ns3::AarfWifiManager.
Referenced by GetDataTxVector().
DoGetFragmentationThreshold()
uint32_t ns3::WifiRemoteStationManager::DoGetFragmentationThreshold (void) const private
Return the current fragmentation threshold.
Returns
the fragmentation threshold
Definition at line 939 of file wifi-remote-station-manager.cc.
References m_fragmentationThreshold.
Referenced by GetFragmentationThreshold(), and GetTypeId().
DoGetRtsTxVector()
virtual WifiTxVector ns3::WifiRemoteStationManager::DoGetRtsTxVector (WifiRemoteStation * station) private pure virtual
Parameters
station the station that we need to communicate
Returns
the transmission mode to use to send an RTS to the station
Note: This method is called before sending an RTS to a station to decide which transmission mode to use for the RTS.
Implemented in ns3::RrpaaWifiManager, ns3::RraaWifiManager, ns3::ParfWifiManager, ns3::OnoeWifiManager, ns3::MinstrelWifiManager, ns3::MinstrelHtWifiManager, ns3::IdealWifiManager, ns3::ConstantRateWifiManager, ns3::CaraWifiManager, ns3::ArfWifiManager, ns3::AparfWifiManager, ns3::AmrrWifiManager, ns3::AarfcdWifiManager, and ns3::AarfWifiManager.
Referenced by GetRtsTxVector().
DoNeedFragmentation()
bool ns3::WifiRemoteStationManager::DoNeedFragmentation (WifiRemoteStation * station, Ptr< const Packet > packet, bool normally) private virtual
Parameters
station the station that we need to communicate
packet the packet to send
normally indicates whether the normal 802.11 data fragmentation mechanism would request that the data packet is fragmented or not.
Returns
true if this packet should be fragmented, false otherwise.
Note: This method is called before sending a unicast packet.
Definition at line 1420 of file wifi-remote-station-manager.cc.
Referenced by NeedFragmentation().
DoNeedRetransmission()
bool ns3::WifiRemoteStationManager::DoNeedRetransmission (WifiRemoteStation * station, Ptr< const Packet > packet, bool normally) private virtual
Parameters
station the station that we need to communicate
packet the packet to send
normally indicates whether the normal 802.11 data retransmission mechanism would request that the data is retransmitted or not.
Returns
true if we want to resend a packet after a failed transmission attempt, false otherwise.
Note: This method is called after any unicast packet transmission (control, management, or data) has been attempted and has failed.
Reimplemented in ns3::MinstrelWifiManager, and ns3::MinstrelHtWifiManager.
Definition at line 1413 of file wifi-remote-station-manager.cc.
Referenced by NeedRetransmission().
DoNeedRts()
bool ns3::WifiRemoteStationManager::DoNeedRts (WifiRemoteStation * station, uint32_t size, bool normally) private virtual
Parameters
station the station that we need to communicate
size the size of the frame to send in bytes
normally indicates whether the normal 802.11 RTS enable mechanism would request that the RTS is sent or not.
Returns
true if we want to use an RTS/CTS handshake for this frame before sending it, false otherwise.
Note: This method is called before a unicast packet is sent on the medium.
Reimplemented in ns3::CaraWifiManager, ns3::AarfcdWifiManager, ns3::RrpaaWifiManager, and ns3::RraaWifiManager.
Definition at line 1406 of file wifi-remote-station-manager.cc.
Referenced by NeedRts().
DoReportAmpduTxStatus()
void ns3::WifiRemoteStationManager::DoReportAmpduTxStatus (WifiRemoteStation * station, uint8_t nSuccessfulMpdus, uint8_t nFailedMpdus, double rxSnr, double dataSnr, uint16_t dataChannelWidth, uint8_t dataNss) private virtual
Typically called per A-MPDU, either when a Block ACK was successfully received or when a BlockAckTimeout has elapsed.
This method is a virtual method that must be implemented by the sub-class intended to handle A-MPDUs. This allows different types of WifiRemoteStationManager to respond differently.
Parameters
station the station that sent the DATA to us
nSuccessfulMpdus number of successfully transmitted MPDUs. A value of 0 means that the Block ACK was missed.
nFailedMpdus number of unsuccessfully transmitted MPDUs.
rxSnr received SNR of the block ack frame itself
dataSnr data SNR reported by remote station
dataChannelWidth the channel width (in MHz) of the A-MPDU we sent
dataNss the number of spatial streams used to send the A-MPDU
Reimplemented in ns3::MinstrelHtWifiManager, and ns3::IdealWifiManager.
Definition at line 1427 of file wifi-remote-station-manager.cc.
References NS_LOG_DEBUG.
Referenced by ReportAmpduTxStatus().
DoReportDataFailed()
virtual void ns3::WifiRemoteStationManager::DoReportDataFailed (WifiRemoteStation * station) private pure virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that we failed to send DATA
Implemented in ns3::RrpaaWifiManager, ns3::RraaWifiManager, ns3::ParfWifiManager, ns3::OnoeWifiManager, ns3::MinstrelWifiManager, ns3::MinstrelHtWifiManager, ns3::IdealWifiManager, ns3::ConstantRateWifiManager, ns3::CaraWifiManager, ns3::ArfWifiManager, ns3::AparfWifiManager, ns3::AmrrWifiManager, ns3::AarfcdWifiManager, and ns3::AarfWifiManager.
Referenced by ReportDataFailed().
DoReportDataOk()
virtual void ns3::WifiRemoteStationManager::DoReportDataOk (WifiRemoteStation * station, double ackSnr, WifiMode ackMode, double dataSnr, uint16_t dataChannelWidth, uint8_t dataNss) private pure virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that we successfully sent RTS
ackSnr the SNR of the ACK we received
ackMode the WifiMode the receiver used to send the ACK
dataSnr the SNR of the DATA we sent
dataChannelWidth the channel width (in MHz) of the DATA we sent
dataNss the number of spatial streams used to send the DATA
Implemented in ns3::RrpaaWifiManager, ns3::RraaWifiManager, ns3::ParfWifiManager, ns3::OnoeWifiManager, ns3::MinstrelWifiManager, ns3::MinstrelHtWifiManager, ns3::IdealWifiManager, ns3::ConstantRateWifiManager, ns3::CaraWifiManager, ns3::ArfWifiManager, ns3::AparfWifiManager, ns3::AmrrWifiManager, ns3::AarfcdWifiManager, and ns3::AarfWifiManager.
Referenced by ReportDataOk().
DoReportFinalDataFailed()
virtual void ns3::WifiRemoteStationManager::DoReportFinalDataFailed (WifiRemoteStation * station) private pure virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that we failed to send DATA
Implemented in ns3::RrpaaWifiManager, ns3::RraaWifiManager, ns3::ParfWifiManager, ns3::OnoeWifiManager, ns3::MinstrelWifiManager, ns3::MinstrelHtWifiManager, ns3::IdealWifiManager, ns3::ConstantRateWifiManager, ns3::CaraWifiManager, ns3::ArfWifiManager, ns3::AparfWifiManager, ns3::AmrrWifiManager, ns3::AarfcdWifiManager, and ns3::AarfWifiManager.
Referenced by ReportFinalDataFailed().
DoReportFinalRtsFailed()
virtual void ns3::WifiRemoteStationManager::DoReportFinalRtsFailed (WifiRemoteStation * station) private pure virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that we failed to send RTS
Implemented in ns3::RrpaaWifiManager, ns3::RraaWifiManager, ns3::ParfWifiManager, ns3::OnoeWifiManager, ns3::MinstrelWifiManager, ns3::MinstrelHtWifiManager, ns3::IdealWifiManager, ns3::ConstantRateWifiManager, ns3::CaraWifiManager, ns3::ArfWifiManager, ns3::AparfWifiManager, ns3::AmrrWifiManager, ns3::AarfcdWifiManager, and ns3::AarfWifiManager.
Referenced by ReportFinalRtsFailed().
DoReportRtsFailed()
virtual void ns3::WifiRemoteStationManager::DoReportRtsFailed (WifiRemoteStation * station) private pure virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that we failed to send RTS
Implemented in ns3::RrpaaWifiManager, ns3::RraaWifiManager, ns3::ParfWifiManager, ns3::OnoeWifiManager, ns3::MinstrelWifiManager, ns3::MinstrelHtWifiManager, ns3::IdealWifiManager, ns3::ConstantRateWifiManager, ns3::CaraWifiManager, ns3::ArfWifiManager, ns3::AparfWifiManager, ns3::AmrrWifiManager, ns3::AarfcdWifiManager, and ns3::AarfWifiManager.
Referenced by ReportRtsFailed().
DoReportRtsOk()
virtual void ns3::WifiRemoteStationManager::DoReportRtsOk (WifiRemoteStation * station, double ctsSnr, WifiMode ctsMode, double rtsSnr) private pure virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that we successfully sent RTS
ctsSnr the SNR of the CTS we received
ctsMode the WifiMode the receiver used to send the CTS
rtsSnr the SNR of the RTS we sent
Implemented in ns3::RrpaaWifiManager, ns3::RraaWifiManager, ns3::ParfWifiManager, ns3::OnoeWifiManager, ns3::MinstrelWifiManager, ns3::MinstrelHtWifiManager, ns3::IdealWifiManager, ns3::ConstantRateWifiManager, ns3::CaraWifiManager, ns3::ArfWifiManager, ns3::AparfWifiManager, ns3::AmrrWifiManager, ns3::AarfcdWifiManager, and ns3::AarfWifiManager.
Referenced by ReportRtsOk().
DoReportRxOk()
virtual void ns3::WifiRemoteStationManager::DoReportRxOk (WifiRemoteStation * station, double rxSnr, WifiMode txMode) private pure virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that sent the DATA to us
rxSnr the SNR of the DATA we received
txMode the WifiMode the sender used to send the DATA
Implemented in ns3::RrpaaWifiManager, ns3::RraaWifiManager, ns3::ParfWifiManager, ns3::OnoeWifiManager, ns3::MinstrelWifiManager, ns3::MinstrelHtWifiManager, ns3::IdealWifiManager, ns3::ConstantRateWifiManager, ns3::CaraWifiManager, ns3::ArfWifiManager, ns3::AparfWifiManager, ns3::AmrrWifiManager, ns3::AarfcdWifiManager, and ns3::AarfWifiManager.
Referenced by ReportRxOk().
DoSetFragmentationThreshold()
void ns3::WifiRemoteStationManager::DoSetFragmentationThreshold (uint32_t threshold) private
Actually sets the fragmentation threshold, it also checks the validity of the given threshold.
Parameters
threshold the fragmentation threshold
Definition at line 903 of file wifi-remote-station-manager.cc.
References m_nextFragmentationThreshold, NS_LOG_FUNCTION, and NS_LOG_WARN.
Referenced by GetTypeId(), and SetFragmentationThreshold().
GetAddress()
Mac48Address ns3::WifiRemoteStationManager::GetAddress (const WifiRemoteStation * station) const protected
Return the address of the station.
Parameters
station the station being queried
Returns
the address of the station
Definition at line 1475 of file wifi-remote-station-manager.cc.
References ns3::WifiRemoteStationState::m_address, and ns3::WifiRemoteStation::m_state.
Referenced by ns3::AarfWifiManager::DoGetDataTxVector(), ns3::AarfcdWifiManager::DoGetDataTxVector(), ns3::AmrrWifiManager::DoGetDataTxVector(), ns3::AparfWifiManager::DoGetDataTxVector(), ns3::ArfWifiManager::DoGetDataTxVector(), ns3::CaraWifiManager::DoGetDataTxVector(), ns3::ConstantRateWifiManager::DoGetDataTxVector(), ns3::IdealWifiManager::DoGetDataTxVector(), ns3::MinstrelHtWifiManager::DoGetDataTxVector(), ns3::OnoeWifiManager::DoGetDataTxVector(), ns3::ParfWifiManager::DoGetDataTxVector(), ns3::RraaWifiManager::DoGetDataTxVector(), ns3::RrpaaWifiManager::DoGetDataTxVector(), ns3::AarfWifiManager::DoGetRtsTxVector(), ns3::AarfcdWifiManager::DoGetRtsTxVector(), ns3::AmrrWifiManager::DoGetRtsTxVector(), ns3::AparfWifiManager::DoGetRtsTxVector(), ns3::ArfWifiManager::DoGetRtsTxVector(), ns3::CaraWifiManager::DoGetRtsTxVector(), ns3::ConstantRateWifiManager::DoGetRtsTxVector(), ns3::IdealWifiManager::DoGetRtsTxVector(), ns3::MinstrelHtWifiManager::DoGetRtsTxVector(), ns3::OnoeWifiManager::DoGetRtsTxVector(), ns3::ParfWifiManager::DoGetRtsTxVector(), ns3::RraaWifiManager::DoGetRtsTxVector(), ns3::RrpaaWifiManager::DoGetRtsTxVector(), ns3::MinstrelWifiManager::GetDataTxVector(), and ns3::MinstrelWifiManager::GetRtsTxVector().
GetAggregation()
bool ns3::WifiRemoteStationManager::GetAggregation (const WifiRemoteStation * station) const protected
Return whether the given station supports A-MPDU.
Parameters
station the station being queried
Returns
true if the station supports MPDU aggregation, false otherwise
Definition at line 1517 of file wifi-remote-station-manager.cc.
References ns3::WifiRemoteStationState::m_aggregation, and ns3::WifiRemoteStation::m_state.
Referenced by ns3::AarfWifiManager::DoGetDataTxVector(), ns3::AarfcdWifiManager::DoGetDataTxVector(), ns3::AmrrWifiManager::DoGetDataTxVector(), ns3::AparfWifiManager::DoGetDataTxVector(), ns3::ArfWifiManager::DoGetDataTxVector(), ns3::CaraWifiManager::DoGetDataTxVector(), ns3::ConstantRateWifiManager::DoGetDataTxVector(), ns3::IdealWifiManager::DoGetDataTxVector(), ns3::MinstrelHtWifiManager::DoGetDataTxVector(), ns3::OnoeWifiManager::DoGetDataTxVector(), ns3::ParfWifiManager::DoGetDataTxVector(), ns3::RraaWifiManager::DoGetDataTxVector(), ns3::RrpaaWifiManager::DoGetDataTxVector(), ns3::AarfWifiManager::DoGetRtsTxVector(), ns3::AarfcdWifiManager::DoGetRtsTxVector(), ns3::AmrrWifiManager::DoGetRtsTxVector(), ns3::AparfWifiManager::DoGetRtsTxVector(), ns3::ArfWifiManager::DoGetRtsTxVector(), ns3::CaraWifiManager::DoGetRtsTxVector(), ns3::ConstantRateWifiManager::DoGetRtsTxVector(), ns3::IdealWifiManager::DoGetRtsTxVector(), ns3::MinstrelHtWifiManager::DoGetRtsTxVector(), ns3::OnoeWifiManager::DoGetRtsTxVector(), ns3::ParfWifiManager::DoGetRtsTxVector(), ns3::RraaWifiManager::DoGetRtsTxVector(), ns3::RrpaaWifiManager::DoGetRtsTxVector(), ns3::MinstrelWifiManager::GetDataTxVector(), and ns3::MinstrelWifiManager::GetRtsTxVector().
GetBasicMcs()
WifiMode ns3::WifiRemoteStationManager::GetBasicMcs (uint8_t i) const
Return the MCS at the given list index.
Parameters
i the position in the list
Returns
the basic MCS at the given list index
Definition at line 1379 of file wifi-remote-station-manager.cc.
References GetNBasicMcs(), m_bssBasicMcsSet, and NS_ASSERT.
Referenced by AddBasicMcs(), ns3::MacLow::GetControlAnswerMode(), and ns3::ApWifiMac::Receive().
GetBasicMode()
WifiMode ns3::WifiRemoteStationManager::GetBasicMode (uint8_t i) const
Return a basic mode from the set of basic modes.
Parameters
i index of the basic mode in the basic mode set
Returns
the basic mode at the given index
Definition at line 1312 of file wifi-remote-station-manager.cc.
References GetNBasicModes(), m_bssBasicRateSet, and NS_ASSERT.
Referenced by AddBasicMode(), ns3::MeshWifiInterfaceMac::CheckSupportedRates(), ns3::IdealWifiManager::DoGetRtsTxVector(), ns3::MinstrelHtWifiManager::DoGetRtsTxVector(), ns3::MacLow::GetControlAnswerMode(), GetDataTxVector(), GetNonUnicastMode(), ns3::MeshWifiInterfaceMac::GetSupportedRates(), ns3::ApWifiMac::GetSupportedRates(), and ns3::ApWifiMac::Receive().
GetChannelWidth()
uint16_t ns3::WifiRemoteStationManager::GetChannelWidth (const WifiRemoteStation * station) const protected
Return the channel width supported by the station.
Parameters
station the station being queried
Returns
the channel width (in MHz) supported by the station
Definition at line 1481 of file wifi-remote-station-manager.cc.
References ns3::WifiRemoteStationState::m_channelWidth, and ns3::WifiRemoteStation::m_state.
Referenced by ns3::AparfWifiManager::CheckInit(), ns3::ParfWifiManager::CheckInit(), ns3::RrpaaWifiManager::CheckInit(), ns3::AarfWifiManager::DoGetDataTxVector(), ns3::AarfcdWifiManager::DoGetDataTxVector(), ns3::AmrrWifiManager::DoGetDataTxVector(), ns3::AparfWifiManager::DoGetDataTxVector(), ns3::ArfWifiManager::DoGetDataTxVector(), ns3::CaraWifiManager::DoGetDataTxVector(), ns3::ConstantRateWifiManager::DoGetDataTxVector(), ns3::IdealWifiManager::DoGetDataTxVector(), ns3::MinstrelHtWifiManager::DoGetDataTxVector(), ns3::OnoeWifiManager::DoGetDataTxVector(), ns3::ParfWifiManager::DoGetDataTxVector(), ns3::RraaWifiManager::DoGetDataTxVector(), ns3::RrpaaWifiManager::DoGetDataTxVector(), ns3::AarfWifiManager::DoGetRtsTxVector(), ns3::AarfcdWifiManager::DoGetRtsTxVector(), ns3::AmrrWifiManager::DoGetRtsTxVector(), ns3::AparfWifiManager::DoGetRtsTxVector(), ns3::ArfWifiManager::DoGetRtsTxVector(), ns3::CaraWifiManager::DoGetRtsTxVector(), ns3::ConstantRateWifiManager::DoGetRtsTxVector(), ns3::MinstrelHtWifiManager::DoGetRtsTxVector(), ns3::OnoeWifiManager::DoGetRtsTxVector(), ns3::ParfWifiManager::DoGetRtsTxVector(), ns3::RraaWifiManager::DoGetRtsTxVector(), ns3::RrpaaWifiManager::DoGetRtsTxVector(), ns3::MinstrelHtWifiManager::DoInitialize(), ns3::MinstrelWifiManager::GetDataTxVector(), ns3::MinstrelWifiManager::GetRtsTxVector(), and ns3::MinstrelHtWifiManager::RateInit().
GetChannelWidthSupported()
uint16_t ns3::WifiRemoteStationManager::GetChannelWidthSupported (Mac48Address address) const
Return the channel width supported by the station.
Parameters
address the address of the station
Returns
the channel width supported by the station
Definition at line 1604 of file wifi-remote-station-manager.cc.
References first::address, LookupState(), and ns3::WifiRemoteStationState::m_channelWidth.
Referenced by ns3::ApWifiMac::GetHtOperation(), and ns3::ApWifiMac::GetVhtOperationalChannelWidth().
GetCtsToSelfTxVector()
WifiTxVector ns3::WifiRemoteStationManager::GetCtsToSelfTxVector (void)
Since CTS-to-self parameters are not dependent on the station, it is implemented in wifi remote station manager.
Returns
the transmission mode to use to send the CTS-to-self prior to the transmission of the data packet itself.
Definition at line 558 of file wifi-remote-station-manager.cc.
References ns3::ConvertGuardIntervalToNanoSeconds(), ns3::WifiPhy::GetChannelWidth(), ns3::GetChannelWidthForTransmission(), GetDefaultMode(), GetDefaultTxPowerLevel(), ns3::WifiPhy::GetDevice(), GetMaxNumberOfTransmitStreams(), ns3::WifiMode::GetModulationClass(), GetNumberOfAntennas(), m_wifiPhy, ns3::WIFI_MOD_CLASS_HE, ns3::WIFI_MOD_CLASS_HT, ns3::WIFI_MOD_CLASS_VHT, ns3::WIFI_PREAMBLE_HE_SU, ns3::WIFI_PREAMBLE_HT_MF, ns3::WIFI_PREAMBLE_LONG, and ns3::WIFI_PREAMBLE_VHT_SU.
GetDataTxVector()
WifiTxVector ns3::WifiRemoteStationManager::GetDataTxVector (const WifiMacHeader & header)
Parameters
header MAC header
Returns
the TXVECTOR to use to send this packet
Definition at line 504 of file wifi-remote-station-manager.cc.
References first::address, ns3::ConvertGuardIntervalToNanoSeconds(), DoGetDataTxVector(), ns3::UintegerValue::Get(), ns3::WifiMacHeader::GetAddr1(), GetBasicMode(), ns3::WifiPhy::GetChannelWidth(), ns3::GetChannelWidthForTransmission(), GetDefaultMode(), ns3::WifiPhy::GetDevice(), ns3::WifiNetDevice::GetHeConfiguration(), ns3::WifiTxVector::GetMode(), ns3::WifiMode::GetModulationClass(), GetNBasicModes(), GetNonUnicastMode(), ns3::GetPreambleForTransmission(), GetShortPreambleEnabled(), ns3::WifiMacHeader::IsMgt(), Lookup(), m_defaultTxPowerLevel, m_wifiPhy, NS_LOG_FUNCTION, ns3::WifiTxVector::SetBssColor(), ns3::WifiTxVector::SetChannelWidth(), ns3::WifiTxVector::SetGuardInterval(), ns3::WifiTxVector::SetLdpc(), ns3::WifiTxVector::SetMode(), ns3::WifiTxVector::SetNess(), ns3::WifiTxVector::SetNss(), ns3::WifiTxVector::SetNTx(), ns3::WifiTxVector::SetPreambleType(), ns3::WifiTxVector::SetTxPowerLevel(), UseGreenfieldForDestination(), UseLdpcForDestination(), and ns3::WIFI_MOD_CLASS_HT.
Referenced by ns3::MacLow::GetDataTxVector(), NeedRts(), PowerRateAdaptationTest::TestAparf(), PowerRateAdaptationTest::TestParf(), and PowerRateAdaptationTest::TestRrpaa().
GetDefaultMcs()
WifiMode ns3::WifiRemoteStationManager::GetDefaultMcs (void) const
Return the default Modulation and Coding Scheme (MCS) index.
Returns
the default WifiMode
Definition at line 1262 of file wifi-remote-station-manager.cc.
References m_defaultTxMcs.
Referenced by ns3::MacLow::GetControlAnswerMode(), and LookupState().
GetDefaultMode()
WifiMode ns3::WifiRemoteStationManager::GetDefaultMode (void) const
Return the default transmission mode.
Returns
WifiMode the default transmission mode
Definition at line 1256 of file wifi-remote-station-manager.cc.
References m_defaultTxMode.
Referenced by ns3::IdealWifiManager::DoGetDataTxVector(), ns3::IdealWifiManager::DoGetRtsTxVector(), ns3::MacLow::GetControlAnswerMode(), GetCtsToSelfTxVector(), GetDataTxVector(), GetNonUnicastMode(), LookupState(), and ns3::IdealWifiManager::Reset().
GetDefaultTxPowerLevel()
uint8_t ns3::WifiRemoteStationManager::GetDefaultTxPowerLevel (void) const
Returns
the default transmission power
Definition at line 1012 of file wifi-remote-station-manager.cc.
References m_defaultTxPowerLevel.
Referenced by ns3::AarfWifiManager::DoGetDataTxVector(), ns3::AarfcdWifiManager::DoGetDataTxVector(), ns3::AmrrWifiManager::DoGetDataTxVector(), ns3::ArfWifiManager::DoGetDataTxVector(), ns3::CaraWifiManager::DoGetDataTxVector(), ns3::ConstantRateWifiManager::DoGetDataTxVector(), ns3::IdealWifiManager::DoGetDataTxVector(), ns3::MinstrelHtWifiManager::DoGetDataTxVector(), ns3::OnoeWifiManager::DoGetDataTxVector(), ns3::RraaWifiManager::DoGetDataTxVector(), ns3::AarfWifiManager::DoGetRtsTxVector(), ns3::AarfcdWifiManager::DoGetRtsTxVector(), ns3::AmrrWifiManager::DoGetRtsTxVector(), ns3::AparfWifiManager::DoGetRtsTxVector(), ns3::ArfWifiManager::DoGetRtsTxVector(), ns3::CaraWifiManager::DoGetRtsTxVector(), ns3::ConstantRateWifiManager::DoGetRtsTxVector(), ns3::IdealWifiManager::DoGetRtsTxVector(), ns3::MinstrelHtWifiManager::DoGetRtsTxVector(), ns3::OnoeWifiManager::DoGetRtsTxVector(), ns3::ParfWifiManager::DoGetRtsTxVector(), ns3::RraaWifiManager::DoGetRtsTxVector(), ns3::RrpaaWifiManager::DoGetRtsTxVector(), ns3::MacLow::GetAckTxVector(), ns3::MacLow::GetBlockAckTxVector(), GetCtsToSelfTxVector(), ns3::MacLow::GetCtsTxVector(), ns3::MinstrelWifiManager::GetDataTxVector(), and ns3::MinstrelWifiManager::GetRtsTxVector().
GetFragmentationThreshold()
uint32_t ns3::WifiRemoteStationManager::GetFragmentationThreshold (void) const
Return the fragmentation threshold.
Returns
the fragmentation threshold
Definition at line 331 of file wifi-remote-station-manager.cc.
References DoGetFragmentationThreshold().
Referenced by GetFragmentOffset(), GetFragmentSize(), GetNFragments(), and NeedFragmentation().
GetFragmentOffset()
uint32_t ns3::WifiRemoteStationManager::GetFragmentOffset (Mac48Address address, const WifiMacHeader * header, Ptr< const Packet > packet, uint32_t fragmentNumber)
Parameters
address remote address
header MAC header
packet the packet to send
fragmentNumber the fragment index of the next fragment to send (starts at zero).
Returns
the offset within the original packet where this fragment starts.
Definition at line 989 of file wifi-remote-station-manager.cc.
References first::address, GetFragmentationThreshold(), GetNFragments(), ns3::WifiMacHeader::GetSize(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::WIFI_MAC_FCS_LENGTH.
Referenced by ns3::QosTxop::GetFragmentOffset(), and ns3::Txop::GetFragmentOffset().
GetFragmentSize()
uint32_t ns3::WifiRemoteStationManager::GetFragmentSize (Mac48Address address, const WifiMacHeader * header, Ptr< const Packet > packet, uint32_t fragmentNumber)
Parameters
address remote address
header MAC header
packet the packet to send
fragmentNumber the fragment index of the next fragment to send (starts at zero).
Returns
the size of the corresponding fragment.
Definition at line 961 of file wifi-remote-station-manager.cc.
References first::address, GetFragmentationThreshold(), GetNFragments(), ns3::WifiMacHeader::GetSize(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::WIFI_MAC_FCS_LENGTH.
Referenced by ns3::QosTxop::GetFragmentSize(), ns3::Txop::GetFragmentSize(), ns3::QosTxop::GetNextFragmentSize(), ns3::Txop::GetNextFragmentSize(), and ns3::QosTxop::IsTxopFragmentation().
GetGreenfield()
bool ns3::WifiRemoteStationManager::GetGreenfield (const WifiRemoteStation * station) const protected
Return whether the station supports Greenfield or not.
Parameters
station the station being queried
Returns
true if Greenfield is supported by the station, false otherwise
Definition at line 1505 of file wifi-remote-station-manager.cc.
References ns3::WifiRemoteStationState::m_htCapabilities, and ns3::WifiRemoteStation::m_state.
GetGreenfieldSupported() [1/2]
bool ns3::WifiRemoteStationManager::GetGreenfieldSupported (Mac48Address address) const
Return whether the station supports Greenfield or not.
Parameters
address the address of the station
Returns
true if Greenfield is supported by the station, false otherwise
Definition at line 1222 of file wifi-remote-station-manager.cc.
References first::address, LookupState(), and ns3::WifiRemoteStationState::m_htCapabilities.
GetGreenfieldSupported() [2/2]
bool ns3::WifiRemoteStationManager::GetGreenfieldSupported (void) const
Return whether the device has HT Greenfield support enabled.
Returns
true if HT Grenfield support is enabled, false otherwise
Definition at line 272 of file wifi-remote-station-manager.cc.
References ns3::WifiPhy::GetDevice(), ns3::WifiNetDevice::GetHtConfiguration(), GetHtSupported(), m_wifiPhy, and NS_ASSERT.
Referenced by ns3::ApWifiMac::IsNonGfHtStasPresent(), and UseGreenfieldForDestination().
GetGuardInterval() [1/2]
uint16_t ns3::WifiRemoteStationManager::GetGuardInterval (const WifiRemoteStation * station) const protected
Return the HE guard interval duration supported by the station.
Parameters
station the station being queried
Returns
the HE guard interval duration (in nanoseconds) supported by the station
Definition at line 1499 of file wifi-remote-station-manager.cc.
References ns3::WifiRemoteStationState::m_guardInterval, and ns3::WifiRemoteStation::m_state.
GetGuardInterval() [2/2]
uint16_t ns3::WifiRemoteStationManager::GetGuardInterval (void) const
Return the supported HE guard interval duration (in nanoseconds).
Returns
the supported HE guard interval duration (in nanoseconds)
Definition at line 317 of file wifi-remote-station-manager.cc.
References ns3::WifiPhy::GetDevice(), ns3::WifiNetDevice::GetHeConfiguration(), GetHeSupported(), m_wifiPhy, and NS_ASSERT.
Referenced by ns3::IdealWifiManager::BuildSnrThresholds(), ns3::ConstantRateWifiManager::DoGetDataTxVector(), ns3::IdealWifiManager::DoGetDataTxVector(), ns3::ConstantRateWifiManager::DoGetRtsTxVector(), and LookupState().
GetHeSupported() [1/3]
bool ns3::WifiRemoteStationManager::GetHeSupported (const WifiRemoteStation * station) const protected
Return whether the given station is HE capable.
Parameters
station the station being queried
Returns
true if the station has HE capabilities, false otherwise
Definition at line 1577 of file wifi-remote-station-manager.cc.
References ns3::WifiRemoteStationState::m_heCapabilities, and ns3::WifiRemoteStation::m_state.
GetHeSupported() [2/3]
bool ns3::WifiRemoteStationManager::GetHeSupported (Mac48Address address) const
Return whether the station supports HE or not.
Parameters
address the address of the station
Returns
true if HE is supported by the station, false otherwise
Definition at line 1652 of file wifi-remote-station-manager.cc.
References first::address, and LookupState().
GetHeSupported() [3/3]
bool ns3::WifiRemoteStationManager::GetHeSupported (void) const
Return whether the device has HE capability support enabled.
Returns
true if HE capability support is enabled, false otherwise
Definition at line 248 of file wifi-remote-station-manager.cc.
References ns3::WifiPhy::GetDevice(), ns3::WifiNetDevice::GetHeConfiguration(), and m_wifiPhy.
Referenced by ns3::IdealWifiManager::DoGetDataTxVector(), ns3::AarfWifiManager::DoInitialize(), ns3::AarfcdWifiManager::DoInitialize(), ns3::AmrrWifiManager::DoInitialize(), ns3::AparfWifiManager::DoInitialize(), ns3::ArfWifiManager::DoInitialize(), ns3::CaraWifiManager::DoInitialize(), ns3::MinstrelHtWifiManager::DoInitialize(), ns3::MinstrelWifiManager::DoInitialize(), ns3::OnoeWifiManager::DoInitialize(), ns3::ParfWifiManager::DoInitialize(), ns3::RraaWifiManager::DoInitialize(), ns3::RrpaaWifiManager::DoInitialize(), GetGuardInterval(), ns3::ApWifiMac::GetHeOperation(), ns3::QosTxop::NeedFragmentation(), ns3::MacLow::ReceiveMpdu(), ns3::MacLow::SendBlockAckAfterBlockAckRequest(), and ns3::QosTxop::SetupBlockAckIfNeeded().
GetHtSupported() [1/3]
bool ns3::WifiRemoteStationManager::GetHtSupported (const WifiRemoteStation * station) const protected
Return whether the given station is HT capable.
Parameters
station the station being queried
Returns
true if the station has HT capabilities, false otherwise
Definition at line 1565 of file wifi-remote-station-manager.cc.
References ns3::WifiRemoteStationState::m_htCapabilities, and ns3::WifiRemoteStation::m_state.
GetHtSupported() [2/3]
bool ns3::WifiRemoteStationManager::GetHtSupported (Mac48Address address) const
Return whether the station supports HT or not.
Parameters
address the address of the station
Returns
true if HT is supported by the station, false otherwise
Definition at line 1640 of file wifi-remote-station-manager.cc.
References first::address, and LookupState().
GetHtSupported() [3/3]
bool ns3::WifiRemoteStationManager::GetHtSupported (void) const
Return whether the device has HT capability support enabled.
Returns
true if HT capability support is enabled, false otherwise
Definition at line 224 of file wifi-remote-station-manager.cc.
References ns3::WifiPhy::GetDevice(), ns3::WifiNetDevice::GetHtConfiguration(), and m_wifiPhy.
Referenced by ns3::IdealWifiManager::BuildSnrThresholds(), ns3::MinstrelHtWifiManager::CheckInit(), ns3::BlockAckManager::CreateAgreement(), ns3::MinstrelHtWifiManager::DoCreateStation(), ns3::IdealWifiManager::DoGetDataTxVector(), ns3::AarfWifiManager::DoInitialize(), ns3::AarfcdWifiManager::DoInitialize(), ns3::AmrrWifiManager::DoInitialize(), ns3::AparfWifiManager::DoInitialize(), ns3::ArfWifiManager::DoInitialize(), ns3::CaraWifiManager::DoInitialize(), ns3::MinstrelHtWifiManager::DoInitialize(), ns3::MinstrelWifiManager::DoInitialize(), ns3::OnoeWifiManager::DoInitialize(), ns3::ParfWifiManager::DoInitialize(), ns3::RraaWifiManager::DoInitialize(), ns3::RrpaaWifiManager::DoInitialize(), ns3::MacLow::GetControlAnswerMode(), GetGreenfieldSupported(), ns3::ApWifiMac::GetHtOperation(), GetLdpcSupported(), GetShortGuardIntervalSupported(), NeedCtsToSelf(), ns3::QosTxop::NeedFragmentation(), ns3::MacLow::ReceiveMpdu(), ns3::MacLow::SendBlockAckAfterBlockAckRequest(), and SetupPhy().
GetInfo()
WifiRemoteStationInfo ns3::WifiRemoteStationManager::GetInfo (Mac48Address address)
Parameters
address of the remote station
Returns
information regarding the remote station associated with the given address
Definition at line 1018 of file wifi-remote-station-manager.cc.
References first::address, LookupState(), and ns3::WifiRemoteStationState::m_info.
GetLdpcSupported() [1/2]
bool ns3::WifiRemoteStationManager::GetLdpcSupported (Mac48Address address) const
Return whether the station supports LDPC or not.
Parameters
address the address of the station
Returns
true if LDPC is supported by the station, false otherwise
Definition at line 1234 of file wifi-remote-station-manager.cc.
References first::address, LookupState(), ns3::WifiRemoteStationState::m_heCapabilities, ns3::WifiRemoteStationState::m_htCapabilities, and ns3::WifiRemoteStationState::m_vhtCapabilities.
GetLdpcSupported() [2/2]
bool ns3::WifiRemoteStationManager::GetLdpcSupported (void) const
Return whether the device has LDPC support enabled.
Returns
true if LDPC support is enabled, false otherwise
Definition at line 288 of file wifi-remote-station-manager.cc.
References ns3::WifiPhy::GetDevice(), ns3::WifiNetDevice::GetHtConfiguration(), GetHtSupported(), m_wifiPhy, and NS_ASSERT.
Referenced by UseLdpcForDestination().
GetMac()
Ptr< WifiMac > ns3::WifiRemoteStationManager::GetMac (void) const protected
Return the WifiMac.
Returns
a pointer to the WifiMac
Definition at line 1547 of file wifi-remote-station-manager.cc.
References m_wifiMac.
GetMaxNumberOfTransmitStreams()
uint8_t ns3::WifiRemoteStationManager::GetMaxNumberOfTransmitStreams (void) const
Returns
the maximum number of spatial streams supported by the PHY layer
Definition at line 1670 of file wifi-remote-station-manager.cc.
References ns3::WifiPhy::GetMaxSupportedTxSpatialStreams(), and m_wifiPhy.
Referenced by ns3::ConstantRateWifiManager::DoGetDataTxVector(), ns3::IdealWifiManager::DoGetDataTxVector(), and GetCtsToSelfTxVector().
GetMcsSupported()
WifiMode ns3::WifiRemoteStationManager::GetMcsSupported (const WifiRemoteStation * station, uint8_t i) const protected
Return the WifiMode supported by the specified station at the specified index.
Parameters
station the station being queried
i the index
Returns
the WifiMode at the given index of the specified station
Definition at line 1440 of file wifi-remote-station-manager.cc.
References GetNMcsSupported(), ns3::WifiRemoteStationState::m_operationalMcsSet, ns3::WifiRemoteStation::m_state, and NS_ASSERT.
Referenced by ns3::MinstrelHtWifiManager::CalculateRetransmits(), ns3::IdealWifiManager::DoGetDataTxVector(), ns3::MinstrelHtWifiManager::DoGetDataTxVector(), ns3::MinstrelHtWifiManager::DoGetRtsTxVector(), ns3::MinstrelHtWifiManager::RateInit(), ns3::MinstrelHtWifiManager::StatsDump(), and ns3::MinstrelHtWifiManager::UpdateStats().
GetNBasicMcs()
uint8_t ns3::WifiRemoteStationManager::GetNBasicMcs (void) const
Return the number of basic MCS index.
Returns
the number of basic MCS index
Definition at line 1373 of file wifi-remote-station-manager.cc.
References m_bssBasicMcsSet.
Referenced by AddBasicMcs(), GetBasicMcs(), ns3::MacLow::GetControlAnswerMode(), and ns3::ApWifiMac::Receive().
GetNBasicModes()
uint8_t ns3::WifiRemoteStationManager::GetNBasicModes (void) const
Return the number of basic modes we support.
Returns
the number of basic modes we support
Definition at line 1306 of file wifi-remote-station-manager.cc.
References m_bssBasicRateSet.
Referenced by AddBasicMode(), ns3::MeshWifiInterfaceMac::CheckSupportedRates(), ns3::IdealWifiManager::DoGetRtsTxVector(), ns3::MinstrelHtWifiManager::DoGetRtsTxVector(), GetBasicMode(), ns3::MacLow::GetControlAnswerMode(), GetDataTxVector(), GetNonUnicastMode(), ns3::MeshWifiInterfaceMac::GetSupportedRates(), ns3::ApWifiMac::GetSupportedRates(), and ns3::ApWifiMac::Receive().
GetNess()
uint8_t ns3::WifiRemoteStationManager::GetNess (const WifiRemoteStation * station) const protected
Returns
the number of Ness the station has.
Parameters
station the station being queried
Returns
the number of Ness the station has
Definition at line 1535 of file wifi-remote-station-manager.cc.
References ns3::WifiRemoteStationState::m_ness, and ns3::WifiRemoteStation::m_state.
Referenced by ns3::MinstrelHtWifiManager::DoGetDataTxVector().
GetNFragments()
uint32_t ns3::WifiRemoteStationManager::GetNFragments (const WifiMacHeader * header, Ptr< const Packet > packet) private
Return the number of fragments needed for the given packet.
Parameters
header MAC header
packet the packet to be fragmented
Returns
the number of fragments needed
Definition at line 945 of file wifi-remote-station-manager.cc.
References GetFragmentationThreshold(), ns3::WifiMacHeader::GetSize(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::WIFI_MAC_FCS_LENGTH.
Referenced by GetFragmentOffset(), GetFragmentSize(), and IsLastFragment().
GetNMcsSupported() [1/2]
uint8_t ns3::WifiRemoteStationManager::GetNMcsSupported (const WifiRemoteStation * station) const protected
Return the number of MCS supported by the given station.
Parameters
station the station being queried
Returns
the number of MCS supported by the given station
Definition at line 1583 of file wifi-remote-station-manager.cc.
References ns3::WifiRemoteStationState::m_operationalMcsSet, and ns3::WifiRemoteStation::m_state.
GetNMcsSupported() [2/2]
uint8_t ns3::WifiRemoteStationManager::GetNMcsSupported (Mac48Address address) const
Return the number of MCS supported by the station.
Parameters
address the address of the station
Returns
the number of MCS supported by the station
Definition at line 1634 of file wifi-remote-station-manager.cc.
References first::address, LookupState(), and ns3::WifiRemoteStationState::m_operationalMcsSet.
Referenced by ns3::MinstrelHtWifiManager::CheckInit(), ns3::IdealWifiManager::DoGetDataTxVector(), ns3::ApWifiMac::GetHtOperation(), and GetMcsSupported().
GetNNonErpBasicModes()
uint32_t ns3::WifiRemoteStationManager::GetNNonErpBasicModes (void) const
Return the number of non-ERP basic modes we support.
Returns
the number of basic modes we support
Definition at line 1319 of file wifi-remote-station-manager.cc.
References m_bssBasicRateSet, and ns3::WIFI_MOD_CLASS_ERP_OFDM.
Referenced by GetNonErpBasicMode().
GetNNonErpSupported()
uint32_t ns3::WifiRemoteStationManager::GetNNonErpSupported (const WifiRemoteStation * station) const protected
Return the number of non-ERP modes supported by the given station.
Parameters
station the station being queried
Returns
the number of non-ERP modes supported by the given station
Definition at line 1589 of file wifi-remote-station-manager.cc.
References ns3::WifiRemoteStationState::m_operationalRateSet, ns3::WifiRemoteStation::m_state, and ns3::WIFI_MOD_CLASS_ERP_OFDM.
Referenced by GetNonErpSupported().
GetNonErpBasicMode()
WifiMode ns3::WifiRemoteStationManager::GetNonErpBasicMode (uint8_t i) const
Return a basic mode from the set of basic modes that is not an ERP mode.
Parameters
i index of the basic mode in the basic mode set
Returns
the basic mode at the given index
Definition at line 1334 of file wifi-remote-station-manager.cc.
References GetNNonErpBasicModes(), m_bssBasicRateSet, NS_ASSERT, and ns3::WIFI_MOD_CLASS_ERP_OFDM.
GetNonErpSupported()
WifiMode ns3::WifiRemoteStationManager::GetNonErpSupported (const WifiRemoteStation * station, uint8_t i) const protected
Return whether non-ERP mode associated with the specified station at the specified index.
Parameters
station the station being queried
i the index
Returns
WifiMode at the given index of the specified station
Definition at line 1447 of file wifi-remote-station-manager.cc.
References GetNNonErpSupported(), ns3::WifiRemoteStationState::m_operationalRateSet, ns3::WifiRemoteStation::m_state, NS_ASSERT, and ns3::WIFI_MOD_CLASS_ERP_OFDM.
Referenced by ns3::AarfWifiManager::DoGetRtsTxVector(), ns3::AarfcdWifiManager::DoGetRtsTxVector(), ns3::AmrrWifiManager::DoGetRtsTxVector(), ns3::AparfWifiManager::DoGetRtsTxVector(), ns3::ArfWifiManager::DoGetRtsTxVector(), ns3::CaraWifiManager::DoGetRtsTxVector(), ns3::OnoeWifiManager::DoGetRtsTxVector(), ns3::ParfWifiManager::DoGetRtsTxVector(), ns3::RraaWifiManager::DoGetRtsTxVector(), ns3::RrpaaWifiManager::DoGetRtsTxVector(), and ns3::MinstrelWifiManager::GetRtsTxVector().
GetNonUnicastMode()
WifiMode ns3::WifiRemoteStationManager::GetNonUnicastMode (void) const
Return a mode for non-unicast packets.
Returns
WifiMode for non-unicast packets
Definition at line 1386 of file wifi-remote-station-manager.cc.
References GetBasicMode(), GetDefaultMode(), GetNBasicModes(), and m_nonUnicastMode.
Referenced by GetDataTxVector(), and GetRtsTxVector().
GetNSupported()
uint8_t ns3::WifiRemoteStationManager::GetNSupported (const WifiRemoteStation * station) const protected
Return the number of modes supported by the given station.
Parameters
station the station being queried
Returns
the number of modes supported by the given station
Definition at line 1553 of file wifi-remote-station-manager.cc.
References ns3::WifiRemoteStationState::m_operationalRateSet, and ns3::WifiRemoteStation::m_state.
Referenced by ns3::AparfWifiManager::CheckInit(), ns3::MinstrelWifiManager::CheckInit(), ns3::ParfWifiManager::CheckInit(), ns3::RraaWifiManager::CheckInit(), ns3::RrpaaWifiManager::CheckInit(), ns3::AmrrWifiManager::DoGetDataTxVector(), ns3::IdealWifiManager::DoGetDataTxVector(), ns3::OnoeWifiManager::DoGetDataTxVector(), ns3::AarfWifiManager::DoReportDataOk(), ns3::AarfcdWifiManager::DoReportDataOk(), ns3::CaraWifiManager::DoReportDataOk(), GetSupported(), ns3::AmrrWifiManager::IncreaseRate(), ns3::AmrrWifiManager::IsMaxRate(), ns3::AmrrWifiManager::UpdateMode(), and ns3::OnoeWifiManager::UpdateMode().
GetNumberOfAntennas()
uint8_t ns3::WifiRemoteStationManager::GetNumberOfAntennas (void) const
Returns
the number of antennas supported by the PHY layer
Definition at line 1664 of file wifi-remote-station-manager.cc.
References ns3::WifiPhy::GetNumberOfAntennas(), and m_wifiPhy.
Referenced by ns3::ConstantRateWifiManager::DoGetDataTxVector(), ns3::IdealWifiManager::DoGetDataTxVector(), ns3::MinstrelHtWifiManager::DoGetDataTxVector(), ns3::IdealWifiManager::DoGetRtsTxVector(), and GetCtsToSelfTxVector().
GetNumberOfSupportedStreams() [1/2]
uint8_t ns3::WifiRemoteStationManager::GetNumberOfSupportedStreams (const WifiRemoteStation * station) const protected
Return the number of supported streams the station has.
Parameters
station the station being queried
Returns
the number of supported streams the station has
Definition at line 1523 of file wifi-remote-station-manager.cc.
References ns3::WifiRemoteStationState::m_htCapabilities, and ns3::WifiRemoteStation::m_state.
GetNumberOfSupportedStreams() [2/2]
uint8_t ns3::WifiRemoteStationManager::GetNumberOfSupportedStreams (Mac48Address address) const
Return the number of spatial streams supported by the station.
Parameters
address the address of the station
Returns
the number of spatial streams supported by the station
Definition at line 1622 of file wifi-remote-station-manager.cc.
References first::address, LookupState(), and ns3::WifiRemoteStationState::m_htCapabilities.
Referenced by ns3::ConstantRateWifiManager::DoGetDataTxVector(), ns3::IdealWifiManager::DoGetDataTxVector(), ns3::MinstrelHtWifiManager::DoGetDataTxVector(), ns3::ApWifiMac::GetHeOperation(), ns3::ApWifiMac::GetHtOperation(), ns3::ApWifiMac::GetVhtOperation(), and ns3::MinstrelHtWifiManager::RateInit().
GetPcfSupported()
bool ns3::WifiRemoteStationManager::GetPcfSupported (void) const
Return whether the device has PCF capability support enabled.
Returns
true if PCF capability support is enabled, false otherwise
Definition at line 266 of file wifi-remote-station-manager.cc.
References m_pcfSupported.
Referenced by ns3::MacLow::EndTxNoAck(), ns3::MacLow::ForwardDown(), and ns3::MacLow::IsCfPeriod().
GetPhy()
Ptr< WifiPhy > ns3::WifiRemoteStationManager::GetPhy (void) const protected
Return the WifiPhy.
Returns
a pointer to the WifiPhy
Definition at line 1541 of file wifi-remote-station-manager.cc.
References m_wifiPhy.
Referenced by ns3::IdealWifiManager::BuildSnrThresholds(), ns3::MinstrelHtWifiManager::CalculateRetransmits(), ns3::MinstrelWifiManager::CalculateTimeUnicastPacket(), ns3::AparfWifiManager::CheckInit(), ns3::ParfWifiManager::CheckInit(), ns3::RrpaaWifiManager::CheckInit(), ns3::AparfWifiManager::DoGetDataTxVector(), ns3::IdealWifiManager::DoGetDataTxVector(), ns3::ParfWifiManager::DoGetDataTxVector(), ns3::RrpaaWifiManager::DoGetDataTxVector(), ns3::MinstrelHtWifiManager::DoGetRtsTxVector(), ns3::MinstrelHtWifiManager::DoInitialize(), ns3::IdealWifiManager::DoReportRtsOk(), ns3::MinstrelHtWifiManager::GetHtDeviceMcsList(), ns3::MinstrelHtWifiManager::GetVhtDeviceMcsList(), and ns3::MinstrelHtWifiManager::RateInit().
GetQosSupported() [1/2]
bool ns3::WifiRemoteStationManager::GetQosSupported (const WifiRemoteStation * station) const protected
Return whether the given station is QoS capable.
Parameters
station the station being queried
Returns
true if the station has QoS capabilities, false otherwise
Definition at line 1559 of file wifi-remote-station-manager.cc.
References ns3::WifiRemoteStationState::m_qosSupported, and ns3::WifiRemoteStation::m_state.
GetQosSupported() [2/2]
bool ns3::WifiRemoteStationManager::GetQosSupported (Mac48Address address) const
Return whether the given station is QoS capable.
Parameters
address the address of the station
Returns
true if the station has QoS capabilities, false otherwise
Definition at line 440 of file wifi-remote-station-manager.cc.
References first::address, LookupState(), and ns3::WifiRemoteStationState::m_qosSupported.
Referenced by ns3::QosTxop::NotifyAccessGranted(), and ns3::QosTxop::StartNextPacket().
GetRtsTxVector()
WifiTxVector ns3::WifiRemoteStationManager::GetRtsTxVector (Mac48Address address)
Parameters
address remote address
Returns
the TXVECTOR to use to send the RTS prior to the transmission of the data packet itself.
Definition at line 591 of file wifi-remote-station-manager.cc.
References first::address, ns3::ConvertGuardIntervalToNanoSeconds(), DoGetRtsTxVector(), ns3::WifiPhy::GetChannelWidth(), ns3::GetChannelWidthForTransmission(), ns3::WifiPhy::GetDevice(), ns3::WifiMode::GetModulationClass(), GetNonUnicastMode(), ns3::GetPreambleForTransmission(), GetShortPreambleEnabled(), Lookup(), m_defaultTxPowerLevel, m_wifiPhy, NS_LOG_FUNCTION, ns3::WifiTxVector::SetChannelWidth(), ns3::WifiTxVector::SetGuardInterval(), ns3::WifiTxVector::SetMode(), ns3::WifiTxVector::SetNess(), ns3::WifiTxVector::SetNss(), ns3::WifiTxVector::SetNTx(), ns3::WifiTxVector::SetPreambleType(), ns3::WifiTxVector::SetTxPowerLevel(), and UseGreenfieldForDestination().
Referenced by ns3::MacLow::GetRtsTxVector().
GetShortGuardIntervalSupported() [1/3]
bool ns3::WifiRemoteStationManager::GetShortGuardIntervalSupported (const WifiRemoteStation * station) const protected
Return whether the given station supports HT/VHT short guard interval.
Parameters
station the station being queried
Returns
true if the station supports HT/VHT short guard interval, false otherwise
Definition at line 1487 of file wifi-remote-station-manager.cc.
References ns3::WifiRemoteStationState::m_htCapabilities, and ns3::WifiRemoteStation::m_state.
GetShortGuardIntervalSupported() [2/3]
bool ns3::WifiRemoteStationManager::GetShortGuardIntervalSupported (Mac48Address address) const
Return whether the station supports HT/VHT short guard interval.
Parameters
address the address of the station
Returns
true if the station supports HT/VHT short guard interval, false otherwise
Definition at line 1610 of file wifi-remote-station-manager.cc.
References first::address, LookupState(), and ns3::WifiRemoteStationState::m_htCapabilities.
GetShortGuardIntervalSupported() [3/3]
bool ns3::WifiRemoteStationManager::GetShortGuardIntervalSupported (void) const
Return whether the device has SGI support enabled.
Returns
true if SGI support is enabled, false otherwise
Definition at line 301 of file wifi-remote-station-manager.cc.
References ns3::WifiPhy::GetDevice(), ns3::WifiNetDevice::GetHtConfiguration(), GetHtSupported(), m_wifiPhy, and NS_ASSERT.
Referenced by ns3::IdealWifiManager::BuildSnrThresholds(), ns3::ConstantRateWifiManager::DoGetDataTxVector(), ns3::IdealWifiManager::DoGetDataTxVector(), ns3::MinstrelHtWifiManager::DoGetDataTxVector(), ns3::ConstantRateWifiManager::DoGetRtsTxVector(), ns3::MinstrelHtWifiManager::DoInitialize(), ns3::ApWifiMac::GetHtOperation(), and ns3::MinstrelHtWifiManager::RateInit().
GetShortPreambleEnabled()
bool ns3::WifiRemoteStationManager::GetShortPreambleEnabled (void) const
Return whether the device uses short PHY preambles.
Returns
true if short PHY preambles are enabled, false otherwise
Definition at line 218 of file wifi-remote-station-manager.cc.
References m_shortPreambleEnabled.
Referenced by ns3::AarfWifiManager::DoGetDataTxVector(), ns3::AarfcdWifiManager::DoGetDataTxVector(), ns3::AmrrWifiManager::DoGetDataTxVector(), ns3::AparfWifiManager::DoGetDataTxVector(), ns3::ArfWifiManager::DoGetDataTxVector(), ns3::CaraWifiManager::DoGetDataTxVector(), ns3::ConstantRateWifiManager::DoGetDataTxVector(), ns3::IdealWifiManager::DoGetDataTxVector(), ns3::MinstrelHtWifiManager::DoGetDataTxVector(), ns3::OnoeWifiManager::DoGetDataTxVector(), ns3::ParfWifiManager::DoGetDataTxVector(), ns3::RraaWifiManager::DoGetDataTxVector(), ns3::RrpaaWifiManager::DoGetDataTxVector(), ns3::AarfWifiManager::DoGetRtsTxVector(), ns3::AarfcdWifiManager::DoGetRtsTxVector(), ns3::AmrrWifiManager::DoGetRtsTxVector(), ns3::AparfWifiManager::DoGetRtsTxVector(), ns3::ArfWifiManager::DoGetRtsTxVector(), ns3::CaraWifiManager::DoGetRtsTxVector(), ns3::ConstantRateWifiManager::DoGetRtsTxVector(), ns3::IdealWifiManager::DoGetRtsTxVector(), ns3::MinstrelHtWifiManager::DoGetRtsTxVector(), ns3::OnoeWifiManager::DoGetRtsTxVector(), ns3::ParfWifiManager::DoGetRtsTxVector(), ns3::RraaWifiManager::DoGetRtsTxVector(), ns3::RrpaaWifiManager::DoGetRtsTxVector(), ns3::MacLow::GetAckTxVector(), ns3::MacLow::GetBlockAckTxVector(), ns3::MacLow::GetCtsTxVector(), GetDataTxVector(), ns3::MinstrelWifiManager::GetDataTxVector(), GetRtsTxVector(), and ns3::MinstrelWifiManager::GetRtsTxVector().
GetShortPreambleSupported()
bool ns3::WifiRemoteStationManager::GetShortPreambleSupported (Mac48Address address) const
Return whether the station supports short PHY preamble or not.
Parameters
address the address of the station
Returns
true if short PHY preamble is supported by the station, false otherwise
Definition at line 428 of file wifi-remote-station-manager.cc.
References first::address, LookupState(), and ns3::WifiRemoteStationState::m_shortPreamble.
Referenced by ns3::ApWifiMac::GetShortPreambleEnabled().
GetShortSlotTimeEnabled()
bool ns3::WifiRemoteStationManager::GetShortSlotTimeEnabled (void) const
Return whether the device uses short slot time.
Returns
true if short slot time is enabled, false otherwise
Definition at line 212 of file wifi-remote-station-manager.cc.
References m_shortSlotTimeEnabled.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromProbeResp().
GetShortSlotTimeSupported()
bool ns3::WifiRemoteStationManager::GetShortSlotTimeSupported (Mac48Address address) const
Return whether the station supports short ERP slot time or not.
Parameters
address the address of the station
Returns
true if short ERP slot time is supported by the station, false otherwise
Definition at line 434 of file wifi-remote-station-manager.cc.
References first::address, LookupState(), and ns3::WifiRemoteStationState::m_shortSlotTime.
Referenced by ns3::ApWifiMac::GetShortSlotTimeEnabled().
GetStationHeCapabilities()
Ptr< const HeCapabilities > ns3::WifiRemoteStationManager::GetStationHeCapabilities (Mac48Address from)
Return the HE capabilities sent by the remote station.
Parameters
from the address of the remote station
Returns
the HE capabilities sent by the remote station
Definition at line 1216 of file wifi-remote-station-manager.cc.
References LookupState(), and ns3::WifiRemoteStationState::m_heCapabilities.
Referenced by ns3::MpduAggregator::GetMaxAmpduSize().
GetStationHtCapabilities()
Ptr< const HtCapabilities > ns3::WifiRemoteStationManager::GetStationHtCapabilities (Mac48Address from)
Return the HT capabilities sent by the remote station.
Parameters
from the address of the remote station
Returns
the HT capabilities sent by the remote station
Definition at line 1204 of file wifi-remote-station-manager.cc.
References LookupState(), and ns3::WifiRemoteStationState::m_htCapabilities.
Referenced by ns3::MpduAggregator::GetMaxAmpduSize(), and ns3::MsduAggregator::GetMaxAmsduSize().
GetStationVhtCapabilities()
Ptr< const VhtCapabilities > ns3::WifiRemoteStationManager::GetStationVhtCapabilities (Mac48Address from)
Return the VHT capabilities sent by the remote station.
Parameters
from the address of the remote station
Returns
the VHT capabilities sent by the remote station
Definition at line 1210 of file wifi-remote-station-manager.cc.
References LookupState(), and ns3::WifiRemoteStationState::m_vhtCapabilities.
Referenced by ns3::MpduAggregator::GetMaxAmpduSize(), and ns3::MsduAggregator::GetMaxAmsduSize().
GetSupported()
WifiMode ns3::WifiRemoteStationManager::GetSupported (const WifiRemoteStation * station, uint8_t i) const protected
Return whether mode associated with the specified station at the specified index.
Parameters
station the station being queried
i the index
Returns
WifiMode at the given index of the specified station
Definition at line 1433 of file wifi-remote-station-manager.cc.
References GetNSupported(), ns3::WifiRemoteStationState::m_operationalRateSet, ns3::WifiRemoteStation::m_state, and NS_ASSERT.
Referenced by ns3::AparfWifiManager::CheckInit(), ns3::ParfWifiManager::CheckInit(), ns3::RrpaaWifiManager::CheckInit(), ns3::AarfWifiManager::DoGetDataTxVector(), ns3::AarfcdWifiManager::DoGetDataTxVector(), ns3::AmrrWifiManager::DoGetDataTxVector(), ns3::AparfWifiManager::DoGetDataTxVector(), ns3::ArfWifiManager::DoGetDataTxVector(), ns3::CaraWifiManager::DoGetDataTxVector(), ns3::IdealWifiManager::DoGetDataTxVector(), ns3::OnoeWifiManager::DoGetDataTxVector(), ns3::ParfWifiManager::DoGetDataTxVector(), ns3::RraaWifiManager::DoGetDataTxVector(), ns3::RrpaaWifiManager::DoGetDataTxVector(), ns3::AarfWifiManager::DoGetRtsTxVector(), ns3::AarfcdWifiManager::DoGetRtsTxVector(), ns3::AmrrWifiManager::DoGetRtsTxVector(), ns3::AparfWifiManager::DoGetRtsTxVector(), ns3::ArfWifiManager::DoGetRtsTxVector(), ns3::CaraWifiManager::DoGetRtsTxVector(), ns3::OnoeWifiManager::DoGetRtsTxVector(), ns3::ParfWifiManager::DoGetRtsTxVector(), ns3::RraaWifiManager::DoGetRtsTxVector(), ns3::RrpaaWifiManager::DoGetRtsTxVector(), ns3::MinstrelWifiManager::FindRate(), ns3::MinstrelWifiManager::GetDataTxVector(), ns3::MinstrelWifiManager::GetRtsTxVector(), ns3::RraaWifiManager::GetThresholds(), ns3::RrpaaWifiManager::GetThresholds(), ns3::RraaWifiManager::InitThresholds(), ns3::RrpaaWifiManager::InitThresholds(), ns3::MinstrelWifiManager::PrintTable(), ns3::MinstrelWifiManager::RateInit(), and ns3::MinstrelWifiManager::UpdateStats().
GetTypeId()
TypeId ns3::WifiRemoteStationManager::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 43 of file wifi-remote-station-manager.cc.
References CTS_TO_SELF, DoGetFragmentationThreshold(), DoSetFragmentationThreshold(), m_defaultTxPowerLevel, m_erpProtectionMode, m_htProtectionMode, m_macTxDataFailed, m_macTxFinalDataFailed, m_macTxFinalRtsFailed, m_macTxRtsFailed, m_nonUnicastMode, ns3::MakeEnumAccessor(), ns3::MakeEnumChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), ns3::MakeWifiModeAccessor(), ns3::MakeWifiModeChecker(), RTS_CTS, SetMaxSlrc(), SetMaxSsrc(), ns3::TypeId::SetParent(), and SetRtsCtsThreshold().
GetUseGreenfieldProtection()
bool ns3::WifiRemoteStationManager::GetUseGreenfieldProtection (void) const
Return whether protection for stations that do not support HT Greenfield format is enabled.
Returns
true if protection for stations that do not support HT Greenfield is enabled, false otherwise
Definition at line 859 of file wifi-remote-station-manager.cc.
References m_useGreenfieldProtection.
Referenced by UseGreenfieldForDestination().
GetUseNonErpProtection()
bool ns3::WifiRemoteStationManager::GetUseNonErpProtection (void) const
Return whether the device supports protection of non-ERP stations.
Returns
true if protection for non-ERP stations is enabled, false otherwise
Definition at line 833 of file wifi-remote-station-manager.cc.
References m_useNonErpProtection.
Referenced by ns3::AarfWifiManager::DoGetRtsTxVector(), ns3::AarfcdWifiManager::DoGetRtsTxVector(), ns3::AmrrWifiManager::DoGetRtsTxVector(), ns3::AparfWifiManager::DoGetRtsTxVector(), ns3::ArfWifiManager::DoGetRtsTxVector(), ns3::CaraWifiManager::DoGetRtsTxVector(), ns3::OnoeWifiManager::DoGetRtsTxVector(), ns3::ParfWifiManager::DoGetRtsTxVector(), ns3::RraaWifiManager::DoGetRtsTxVector(), ns3::RrpaaWifiManager::DoGetRtsTxVector(), ns3::MinstrelWifiManager::GetRtsTxVector(), and ns3::MacLow::StartTransmission().
GetUseNonHtProtection()
bool ns3::WifiRemoteStationManager::GetUseNonHtProtection (void) const
Return whether the device supports protection of non-HT stations.
Returns
true if protection for non-HT stations is enabled, false otherwise
Definition at line 846 of file wifi-remote-station-manager.cc.
References m_useNonHtProtection.
GetVhtSupported() [1/3]
bool ns3::WifiRemoteStationManager::GetVhtSupported (const WifiRemoteStation * station) const protected
Return whether the given station is VHT capable.
Parameters
station the station being queried
Returns
true if the station has VHT capabilities, false otherwise
Definition at line 1571 of file wifi-remote-station-manager.cc.
References ns3::WifiRemoteStation::m_state, and ns3::WifiRemoteStationState::m_vhtCapabilities.
GetVhtSupported() [2/3]
bool ns3::WifiRemoteStationManager::GetVhtSupported (Mac48Address address) const
Return whether the station supports VHT or not.
Parameters
address the address of the station
Returns
true if VHT is supported by the station, false otherwise
Definition at line 1646 of file wifi-remote-station-manager.cc.
References first::address, and LookupState().
GetVhtSupported() [3/3]
bool ns3::WifiRemoteStationManager::GetVhtSupported (void) const
Return whether the device has VHT capability support enabled.
Returns
true if VHT capability support is enabled, false otherwise
Definition at line 236 of file wifi-remote-station-manager.cc.
References ns3::WifiPhy::GetDevice(), ns3::WifiNetDevice::GetVhtConfiguration(), and m_wifiPhy.
Referenced by ns3::IdealWifiManager::DoGetDataTxVector(), ns3::AarfWifiManager::DoInitialize(), ns3::AarfcdWifiManager::DoInitialize(), ns3::AmrrWifiManager::DoInitialize(), ns3::AparfWifiManager::DoInitialize(), ns3::ArfWifiManager::DoInitialize(), ns3::CaraWifiManager::DoInitialize(), ns3::MinstrelHtWifiManager::DoInitialize(), ns3::MinstrelWifiManager::DoInitialize(), ns3::OnoeWifiManager::DoInitialize(), ns3::ParfWifiManager::DoInitialize(), ns3::RraaWifiManager::DoInitialize(), ns3::RrpaaWifiManager::DoInitialize(), ns3::ApWifiMac::GetVhtOperation(), ns3::ApWifiMac::GetVhtOperationalChannelWidth(), ns3::QosTxop::NeedFragmentation(), ns3::MinstrelHtWifiManager::RateInit(), ns3::MacLow::ReceiveMpdu(), ns3::MacLow::SendBlockAckAfterBlockAckRequest(), and ns3::QosTxop::SetupBlockAckIfNeeded().
IsAssociated()
bool ns3::WifiRemoteStationManager::IsAssociated (Mac48Address address) const
Return whether the station associated.
Parameters
address the address of the station
Returns
true if the station is associated, false otherwise
Definition at line 456 of file wifi-remote-station-manager.cc.
References first::address, ns3::WifiRemoteStationState::GOT_ASSOC_TX_OK, LookupState(), and ns3::WifiRemoteStationState::m_state.
Referenced by ns3::ApWifiMac::Enqueue(), and ns3::ApWifiMac::Receive().
IsBrandNew()
bool ns3::WifiRemoteStationManager::IsBrandNew (Mac48Address address) const
Return whether the station state is brand new.
Parameters
address the address of the station
Returns
true if the state of the station is brand new, false otherwise
Definition at line 446 of file wifi-remote-station-manager.cc.
References first::address, ns3::WifiRemoteStationState::BRAND_NEW, LookupState(), and ns3::WifiRemoteStationState::m_state.
Referenced by ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::MeshWifiInterfaceMac::ForwardDown(), ns3::OcbWifiMac::Receive(), and ns3::AdhocWifiMac::Receive().
IsLastFragment()
bool ns3::WifiRemoteStationManager::IsLastFragment (Mac48Address address, const WifiMacHeader * header, Ptr< const Packet > packet, uint32_t fragmentNumber)
Parameters
address remote address
header MAC header
packet the packet to send
fragmentNumber the fragment index of the next fragment to send (starts at zero).
Returns
true if this is the last fragment, false otherwise.
Definition at line 1001 of file wifi-remote-station-manager.cc.
References first::address, GetNFragments(), NS_ASSERT, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by ns3::QosTxop::IsLastFragment(), and ns3::Txop::IsLastFragment().
IsWaitAssocTxOk()
bool ns3::WifiRemoteStationManager::IsWaitAssocTxOk (Mac48Address address) const
Return whether we are waiting for an ACK for the association response we sent.
Parameters
address the address of the station
Returns
true if the station is associated, false otherwise
Definition at line 466 of file wifi-remote-station-manager.cc.
References first::address, LookupState(), ns3::WifiRemoteStationState::m_state, and ns3::WifiRemoteStationState::WAIT_ASSOC_TX_OK.
Referenced by ns3::ApWifiMac::TxFailed(), and ns3::ApWifiMac::TxOk().
Lookup()
WifiRemoteStation * ns3::WifiRemoteStationManager::Lookup (Mac48Address address) const private
Return the station associated with the given address.
Parameters
address the address of the station
Returns
WifiRemoteStation corresponding to the address
Definition at line 1055 of file wifi-remote-station-manager.cc.
References first::address, DoCreateStation(), LookupState(), ns3::WifiRemoteStation::m_state, m_stations, and NS_LOG_FUNCTION.
Referenced by GetDataTxVector(), GetRtsTxVector(), NeedFragmentation(), NeedRetransmission(), NeedRts(), ReportAmpduTxStatus(), ReportDataFailed(), ReportDataOk(), ReportFinalDataFailed(), ReportFinalRtsFailed(), ReportRtsFailed(), ReportRtsOk(), and ReportRxOk().
LookupState()
WifiRemoteStationState * ns3::WifiRemoteStationManager::LookupState (Mac48Address address) const private
Return the state of the station associated with the given address.
Parameters
address the address of the station
Returns
WifiRemoteStationState corresponding to the address
Definition at line 1025 of file wifi-remote-station-manager.cc.
References first::address, ns3::WifiRemoteStationState::BRAND_NEW, ns3::WifiPhy::GetChannelWidth(), GetDefaultMcs(), GetDefaultMode(), GetGuardInterval(), ns3::WifiRemoteStationState::m_address, ns3::WifiRemoteStationState::m_aggregation, ns3::WifiRemoteStationState::m_channelWidth, ns3::WifiRemoteStationState::m_guardInterval, ns3::WifiRemoteStationState::m_heCapabilities, ns3::WifiRemoteStationState::m_htCapabilities, ns3::WifiRemoteStationState::m_ness, ns3::WifiRemoteStationState::m_operationalMcsSet, ns3::WifiRemoteStationState::m_operationalRateSet, ns3::WifiRemoteStationState::m_qosSupported, ns3::WifiRemoteStationState::m_state, m_states, ns3::WifiRemoteStationState::m_vhtCapabilities, m_wifiPhy, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by AddAllSupportedMcs(), AddAllSupportedModes(), AddStationHeCapabilities(), AddStationHtCapabilities(), AddStationVhtCapabilities(), AddSupportedErpSlotTime(), AddSupportedMcs(), AddSupportedMode(), AddSupportedPhyPreamble(), GetChannelWidthSupported(), GetGreenfieldSupported(), GetHeSupported(), GetHtSupported(), GetInfo(), GetLdpcSupported(), GetNMcsSupported(), GetNumberOfSupportedStreams(), GetQosSupported(), GetShortGuardIntervalSupported(), GetShortPreambleSupported(), GetShortSlotTimeSupported(), GetStationHeCapabilities(), GetStationHtCapabilities(), GetStationVhtCapabilities(), GetVhtSupported(), IsAssociated(), IsBrandNew(), IsWaitAssocTxOk(), Lookup(), RecordDisassociated(), RecordGotAssocTxFailed(), RecordGotAssocTxOk(), RecordWaitAssocTxOk(), RemoveAllSupportedMcs(), and SetQosSupport().
NeedCtsToSelf()
bool ns3::WifiRemoteStationManager::NeedCtsToSelf (WifiTxVector txVector)
Return if we need to do CTS-to-self before sending a DATA.
Parameters
txVector the TXVECTOR of the packet to be sent
Returns
true if CTS-to-self is needed, false otherwise
Definition at line 773 of file wifi-remote-station-manager.cc.
References CTS_TO_SELF, GetHtSupported(), ns3::WifiTxVector::GetMode(), ns3::WifiMode::GetModulationClass(), m_bssBasicMcsSet, m_bssBasicRateSet, m_erpProtectionMode, m_htProtectionMode, m_useNonErpProtection, m_useNonHtProtection, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::WIFI_MOD_CLASS_ERP_OFDM, ns3::WIFI_MOD_CLASS_HE, ns3::WIFI_MOD_CLASS_HT, and ns3::WIFI_MOD_CLASS_VHT.
Referenced by ns3::MacLow::NeedCtsToSelf().
NeedFragmentation()
bool ns3::WifiRemoteStationManager::NeedFragmentation (Mac48Address address, const WifiMacHeader * header, Ptr< const Packet > packet)
Parameters
address remote address
header MAC header
packet the packet to send
Returns
true if this packet should be fragmented, false otherwise.
Definition at line 889 of file wifi-remote-station-manager.cc.
References first::address, DoNeedFragmentation(), GetFragmentationThreshold(), ns3::WifiMacHeader::GetSize(), Lookup(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::WIFI_MAC_FCS_LENGTH.
Referenced by ns3::QosTxop::IsTxopFragmentation(), ns3::QosTxop::NeedFragmentation(), and ns3::Txop::NeedFragmentation().
NeedRetransmission()
bool ns3::WifiRemoteStationManager::NeedRetransmission (Mac48Address address, const WifiMacHeader * header, Ptr< const Packet > packet)
Parameters
address remote address
header MAC header
packet the packet to send
Returns
true if we want to resend a packet after a failed transmission attempt, false otherwise.
Definition at line 865 of file wifi-remote-station-manager.cc.
References first::address, DoNeedRetransmission(), ns3::WifiMacHeader::GetQosTid(), ns3::WifiMacHeader::GetSize(), ns3::WifiMacHeader::IsQosData(), Lookup(), m_maxSlrc, m_maxSsrc, m_rtsCtsThreshold, m_slrc, m_ssrc, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::QosUtilsMapTidToAc(), and ns3::WIFI_MAC_FCS_LENGTH.
Referenced by ns3::Txop::NeedDataRetransmission(), and ns3::Txop::NeedRtsRetransmission().
NeedRts()
bool ns3::WifiRemoteStationManager::NeedRts (const WifiMacHeader & header, uint32_t size)
Parameters
header MAC header
size the size of the frame to send in bytes
Returns
true if we want to use an RTS/CTS handshake for this frame before sending it, false otherwise.
Definition at line 739 of file wifi-remote-station-manager.cc.
References first::address, DoNeedRts(), ns3::WifiMacHeader::GetAddr1(), GetDataTxVector(), ns3::WifiTxVector::GetMode(), ns3::WifiMode::GetModulationClass(), Lookup(), m_erpProtectionMode, m_htProtectionMode, m_rtsCtsThreshold, m_useNonErpProtection, m_useNonHtProtection, NS_LOG_DEBUG, NS_LOG_FUNCTION, RTS_CTS, ns3::WIFI_MOD_CLASS_ERP_OFDM, ns3::WIFI_MOD_CLASS_HE, ns3::WIFI_MOD_CLASS_HT, and ns3::WIFI_MOD_CLASS_VHT.
Referenced by ns3::QosTxop::GetTransmissionParameters(), ns3::Txop::NotifyAccessGranted(), ns3::QosTxop::RestartAccessIfNeeded(), and ns3::QosTxop::StartAccessIfNeeded().
RecordDisassociated()
void ns3::WifiRemoteStationManager::RecordDisassociated (Mac48Address address)
Records that the STA was disassociated.
Parameters
address the address of the station
Definition at line 497 of file wifi-remote-station-manager.cc.
References first::address, ns3::WifiRemoteStationState::DISASSOC, LookupState(), ns3::WifiRemoteStationState::m_state, and NS_ASSERT.
Referenced by ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::MeshWifiInterfaceMac::ForwardDown(), ns3::OcbWifiMac::Receive(), ns3::AdhocWifiMac::Receive(), and ns3::ApWifiMac::Receive().
RecordGotAssocTxFailed()
void ns3::WifiRemoteStationManager::RecordGotAssocTxFailed (Mac48Address address)
Records that we missed an ACK for the association response we sent.
Parameters
address the address of the station
Definition at line 490 of file wifi-remote-station-manager.cc.
References first::address, ns3::WifiRemoteStationState::DISASSOC, LookupState(), ns3::WifiRemoteStationState::m_state, and NS_ASSERT.
Referenced by ns3::ApWifiMac::TxFailed().
RecordGotAssocTxOk()
void ns3::WifiRemoteStationManager::RecordGotAssocTxOk (Mac48Address address)
Records that we got an ACK for the association response we sent.
Parameters
address the address of the station
Definition at line 483 of file wifi-remote-station-manager.cc.
References first::address, ns3::WifiRemoteStationState::GOT_ASSOC_TX_OK, LookupState(), ns3::WifiRemoteStationState::m_state, and NS_ASSERT.
Referenced by ns3::ApWifiMac::TxOk().
RecordWaitAssocTxOk()
void ns3::WifiRemoteStationManager::RecordWaitAssocTxOk (Mac48Address address)
Records that we are waiting for an ACK for the association response we sent.
Parameters
address the address of the station
Definition at line 476 of file wifi-remote-station-manager.cc.
References first::address, LookupState(), ns3::WifiRemoteStationState::m_state, NS_ASSERT, and ns3::WifiRemoteStationState::WAIT_ASSOC_TX_OK.
Referenced by ns3::ApWifiMac::Receive().
RemoveAllSupportedMcs()
void ns3::WifiRemoteStationManager::RemoveAllSupportedMcs (Mac48Address address)
Invoked in a STA or AP to delete all of the supported MCS by a destination.
Parameters
address the address of the station being recorded
Definition at line 402 of file wifi-remote-station-manager.cc.
References first::address, LookupState(), ns3::WifiRemoteStationState::m_operationalMcsSet, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
ReportAmpduTxStatus()
void ns3::WifiRemoteStationManager::ReportAmpduTxStatus (Mac48Address address, uint8_t nSuccessfulMpdus, uint8_t nFailedMpdus, double rxSnr, double dataSnr, WifiTxVector dataTxVector)
Typically called per A-MPDU, either when a Block ACK was successfully received or when a BlockAckTimeout has elapsed.
Parameters
address the address of the receiver
nSuccessfulMpdus number of successfully transmitted MPDUs A value of 0 means that the Block ACK was missed.
nFailedMpdus number of unsuccessfully transmitted MPDUs
rxSnr received SNR of the block ack frame itself
dataSnr data SNR reported by remote station
dataTxVector the TXVECTOR of the MPDUs we sent
Definition at line 725 of file wifi-remote-station-manager.cc.
References first::address, DoReportAmpduTxStatus(), ns3::WifiTxVector::GetChannelWidth(), ns3::WifiTxVector::GetNss(), Lookup(), m_macTxDataFailed, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::QosTxop::MissedBlockAck(), and ns3::BlockAckManager::NotifyGotBlockAck().
ReportDataFailed()
void ns3::WifiRemoteStationManager::ReportDataFailed (Mac48Address address, const WifiMacHeader * header, uint32_t packetSize)
Should be invoked whenever the AckTimeout associated to a transmission attempt expires.
Parameters
address the address of the receiver
header MAC header of the DATA packet
packetSize the size of the DATA packet
Definition at line 623 of file wifi-remote-station-manager.cc.
References first::address, DoReportDataFailed(), ns3::WifiMacHeader::GetQosTid(), ns3::WifiMacHeader::GetSize(), ns3::WifiMacHeader::IsQosData(), Lookup(), m_macTxDataFailed, m_rtsCtsThreshold, m_slrc, m_ssrc, NS_ASSERT, NS_LOG_FUNCTION, packetSize, ns3::QosUtilsMapTidToAc(), and ns3::WIFI_MAC_FCS_LENGTH.
Referenced by ns3::QosTxop::MissedAck(), ns3::Txop::MissedAck(), ns3::QosTxop::MissedBlockAck(), ns3::QosTxop::NotifyInternalCollision(), PowerRateAdaptationTest::TestAparf(), PowerRateAdaptationTest::TestParf(), and PowerRateAdaptationTest::TestRrpaa().
ReportDataOk()
void ns3::WifiRemoteStationManager::ReportDataOk (Mac48Address address, const WifiMacHeader * header, double ackSnr, WifiMode ackMode, double dataSnr, WifiTxVector dataTxVector, uint32_t packetSize)
Should be invoked whenever we receive the ACK associated to a data packet we just sent.
Parameters
address the address of the receiver
header MAC header of the DATA packet
ackSnr the SNR of the ACK we received
ackMode the WifiMode the receiver used to send the ACK
dataSnr the SNR of the DATA we sent
dataTxVector the TXVECTOR of the DATA we sent
packetSize the size of the DATA packet
Definition at line 656 of file wifi-remote-station-manager.cc.
References first::address, DoReportDataOk(), ns3::WifiTxVector::GetChannelWidth(), ns3::WifiTxVector::GetNss(), ns3::WifiMacHeader::GetQosTid(), ns3::WifiMacHeader::GetSize(), ns3::WifiMacHeader::IsQosData(), Lookup(), ns3::WifiRemoteStationState::m_info, m_rtsCtsThreshold, m_slrc, m_ssrc, ns3::WifiRemoteStation::m_state, ns3::WifiRemoteStationInfo::NotifyTxSuccess(), NS_ASSERT, NS_LOG_FUNCTION, packetSize, ns3::QosUtilsMapTidToAc(), and ns3::WIFI_MAC_FCS_LENGTH.
Referenced by ns3::MacLow::ReceiveOk(), PowerRateAdaptationTest::TestAparf(), PowerRateAdaptationTest::TestParf(), and PowerRateAdaptationTest::TestRrpaa().
ReportFinalDataFailed()
void ns3::WifiRemoteStationManager::ReportFinalDataFailed (Mac48Address address, const WifiMacHeader * header, uint32_t packetSize)
Should be invoked after calling ReportDataFailed if NeedRetransmission returns false.
Parameters
address the address of the receiver
header MAC header of the DATA packet
packetSize the size of the DATA packet
Definition at line 692 of file wifi-remote-station-manager.cc.
References first::address, DoReportFinalDataFailed(), ns3::WifiMacHeader::GetQosTid(), ns3::WifiMacHeader::GetSize(), ns3::WifiMacHeader::IsQosData(), Lookup(), ns3::WifiRemoteStationState::m_info, m_macTxFinalDataFailed, m_rtsCtsThreshold, m_slrc, m_ssrc, ns3::WifiRemoteStation::m_state, ns3::WifiRemoteStationInfo::NotifyTxFailed(), NS_ASSERT, NS_LOG_FUNCTION, packetSize, ns3::QosUtilsMapTidToAc(), and ns3::WIFI_MAC_FCS_LENGTH.
Referenced by ns3::QosTxop::MissedAck(), ns3::Txop::MissedAck(), ns3::QosTxop::MissedBlockAck(), ns3::Txop::MissedCfPollResponse(), ns3::QosTxop::NotifyInternalCollision(), and ns3::Txop::SendCfFrame().
ReportFinalRtsFailed()
void ns3::WifiRemoteStationManager::ReportFinalRtsFailed (Mac48Address address, const WifiMacHeader * header)
Should be invoked after calling ReportRtsFailed if NeedRetransmission returns false.
Parameters
address the address of the receiver
header MAC header of the DATA packet
Definition at line 679 of file wifi-remote-station-manager.cc.
References first::address, DoReportFinalRtsFailed(), ns3::WifiMacHeader::GetQosTid(), ns3::WifiMacHeader::IsQosData(), Lookup(), ns3::WifiRemoteStationState::m_info, m_macTxFinalRtsFailed, m_ssrc, ns3::WifiRemoteStation::m_state, ns3::WifiRemoteStationInfo::NotifyTxFailed(), NS_ASSERT, NS_LOG_FUNCTION, and ns3::QosUtilsMapTidToAc().
Referenced by ns3::Txop::MissedCts(), ns3::QosTxop::NotifyInternalCollision(), and ns3::QosTxop::NotifyMissedCts().
ReportRtsFailed()
void ns3::WifiRemoteStationManager::ReportRtsFailed (Mac48Address address, const WifiMacHeader * header)
Should be invoked whenever the RtsTimeout associated to a transmission attempt expires.
Parameters
address the address of the receiver
header MAC header of the DATA packet
Definition at line 612 of file wifi-remote-station-manager.cc.
References first::address, DoReportRtsFailed(), ns3::WifiMacHeader::GetQosTid(), ns3::WifiMacHeader::IsQosData(), Lookup(), m_macTxRtsFailed, m_ssrc, NS_ASSERT, NS_LOG_FUNCTION, and ns3::QosUtilsMapTidToAc().
Referenced by ns3::MacLow::CtsTimeout(), and ns3::QosTxop::NotifyInternalCollision().
ReportRtsOk()
void ns3::WifiRemoteStationManager::ReportRtsOk (Mac48Address address, const WifiMacHeader * header, double ctsSnr, WifiMode ctsMode, double rtsSnr)
Should be invoked whenever we receive the CTS associated to an RTS we just sent.
Note that we also get the SNR of the RTS we sent since the receiver put a SnrTag in the CTS.
Parameters
address the address of the receiver
header MAC header of the DATA packet
ctsSnr the SNR of the CTS we received
ctsMode the WifiMode the receiver used to send the CTS
rtsSnr the SNR of the RTS we sent
Definition at line 643 of file wifi-remote-station-manager.cc.
References first::address, DoReportRtsOk(), ns3::WifiMacHeader::GetQosTid(), ns3::WifiMacHeader::IsQosData(), Lookup(), ns3::WifiRemoteStationState::m_info, m_ssrc, ns3::WifiRemoteStation::m_state, ns3::WifiRemoteStationInfo::NotifyTxSuccess(), NS_ASSERT, NS_LOG_FUNCTION, and ns3::QosUtilsMapTidToAc().
Referenced by ns3::MacLow::ReceiveOk().
ReportRxOk()
void ns3::WifiRemoteStationManager::ReportRxOk (Mac48Address address, double rxSnr, WifiMode txMode)
Parameters
address remote address
rxSnr the SNR of the packet received
txMode the transmission mode used for the packet received
Should be invoked whenever a packet is successfully received.
Definition at line 714 of file wifi-remote-station-manager.cc.
References first::address, DoReportRxOk(), Lookup(), and NS_LOG_FUNCTION.
Referenced by ns3::MacLow::ReceiveOk().
Reset()
void ns3::WifiRemoteStationManager::Reset (void)
Reset the station, invoked in a STA upon dis-association or in an AP upon reboot.
Definition at line 1268 of file wifi-remote-station-manager.cc.
References m_bssBasicMcsSet, m_bssBasicRateSet, m_slrc, m_ssrc, m_states, m_stations, and NS_LOG_FUNCTION.
Referenced by ns3::IdealWifiManager::DoCreateStation(), DoDispose(), ns3::IdealWifiManager::DoReportFinalDataFailed(), ns3::IdealWifiManager::DoReportFinalRtsFailed(), ns3::MacLow::NotifySwitchingStartNow(), SetupMac(), and SetupPhy().
SetDefaultTxPowerLevel()
void ns3::WifiRemoteStationManager::SetDefaultTxPowerLevel (uint8_t txPower)
Set the default transmission power level.
Parameters
txPower the default transmission power level
Definition at line 1658 of file wifi-remote-station-manager.cc.
References m_defaultTxPowerLevel.
SetFragmentationThreshold()
void ns3::WifiRemoteStationManager::SetFragmentationThreshold (uint32_t threshold)
Sets a fragmentation threshold.
The method calls a private method DoSetFragmentationThreshold that checks the validity of the value given.
Parameters
threshold the fragmentation threshold
Definition at line 191 of file wifi-remote-station-manager.cc.
References DoSetFragmentationThreshold(), and NS_LOG_FUNCTION.
SetMaxSlrc()
void ns3::WifiRemoteStationManager::SetMaxSlrc (uint32_t maxSlrc)
Sets the maximum STA long retry count (SLRC).
Parameters
maxSlrc the maximum SLRC
Definition at line 177 of file wifi-remote-station-manager.cc.
References m_maxSlrc, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetMaxSsrc()
void ns3::WifiRemoteStationManager::SetMaxSsrc (uint32_t maxSsrc)
Sets the maximum STA short retry count (SSRC).
Parameters
maxSsrc the maximum SSRC
Definition at line 170 of file wifi-remote-station-manager.cc.
References m_maxSsrc, and NS_LOG_FUNCTION.
Referenced by AmpduAggregationTest::DoRun(), and GetTypeId().
SetPcfSupported()
void ns3::WifiRemoteStationManager::SetPcfSupported (bool enable)
Enable or disable PCF capability support.
Parameters
enable enable or disable PCF capability support
Definition at line 260 of file wifi-remote-station-manager.cc.
References m_pcfSupported.
Referenced by ns3::InfrastructureWifiMac::SetPcfSupported(), ns3::ApWifiMac::SetWifiRemoteStationManager(), and ns3::StaWifiMac::SetWifiRemoteStationManager().
SetQosSupport()
void ns3::WifiRemoteStationManager::SetQosSupport (Mac48Address from, bool qosSupported)
Records QoS support of the remote station.
Parameters
from the address of the station being recorded
qosSupported whether the station supports QoS
Definition at line 1074 of file wifi-remote-station-manager.cc.
References LookupState(), ns3::WifiRemoteStationState::m_qosSupported, and NS_LOG_FUNCTION.
Referenced by AddStationHeCapabilities(), AddStationHtCapabilities(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
SetRtsCtsThreshold()
void ns3::WifiRemoteStationManager::SetRtsCtsThreshold (uint32_t threshold)
Sets the RTS threshold.
Parameters
threshold the RTS threshold
Definition at line 184 of file wifi-remote-station-manager.cc.
References m_rtsCtsThreshold, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetShortPreambleEnabled()
void ns3::WifiRemoteStationManager::SetShortPreambleEnabled (bool enable)
Enable or disable short PHY preambles.
Parameters
enable enable or disable short PHY preambles
Definition at line 198 of file wifi-remote-station-manager.cc.
References m_shortPreambleEnabled, and NS_LOG_FUNCTION.
Referenced by ns3::ApWifiMac::SendOneBeacon(), ns3::ApWifiMac::SendProbeResp(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), ns3::StaWifiMac::UpdateApInfoFromBeacon(), and ns3::StaWifiMac::UpdateApInfoFromProbeResp().
SetShortSlotTimeEnabled()
void ns3::WifiRemoteStationManager::SetShortSlotTimeEnabled (bool enable)
Enable or disable short slot time.
Parameters
enable enable or disable short slot time
Definition at line 205 of file wifi-remote-station-manager.cc.
References m_shortSlotTimeEnabled, and NS_LOG_FUNCTION.
Referenced by ns3::ApWifiMac::SendOneBeacon(), ns3::ApWifiMac::SendProbeResp(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), ns3::StaWifiMac::UpdateApInfoFromBeacon(), and ns3::StaWifiMac::UpdateApInfoFromProbeResp().
SetupMac()
void ns3::WifiRemoteStationManager::SetupMac (const Ptr< WifiMac > mac) virtual
Set up MAC associated with this device since it is the object that knows the full set of timing parameters (e.g.
IFS).
Parameters
mac the MAC of this device
Reimplemented in ns3::RrpaaWifiManager, ns3::RraaWifiManager, ns3::MinstrelWifiManager, and ns3::MinstrelHtWifiManager.
Definition at line 160 of file wifi-remote-station-manager.cc.
References m_wifiMac, third::mac, NS_LOG_FUNCTION, and Reset().
Referenced by ns3::WifiNetDevice::CompleteConfig(), ns3::MinstrelHtWifiManager::SetupMac(), ns3::MinstrelWifiManager::SetupMac(), ns3::RraaWifiManager::SetupMac(), and ns3::RrpaaWifiManager::SetupMac().
SetupPhy()
void ns3::WifiRemoteStationManager::SetupPhy (const Ptr< WifiPhy > phy) virtual
Set up PHY associated with this device since it is the object that knows the full set of transmit rates that are supported.
Parameters
phy the PHY of this device
Reimplemented in ns3::RrpaaWifiManager, ns3::RraaWifiManager, ns3::ParfWifiManager, ns3::MinstrelWifiManager, ns3::MinstrelHtWifiManager, ns3::IdealWifiManager, and ns3::AparfWifiManager.
Definition at line 141 of file wifi-remote-station-manager.cc.
References GetHtSupported(), ns3::WifiMode::IsMandatory(), m_defaultTxMcs, m_defaultTxMode, m_wifiPhy, NS_ASSERT, NS_LOG_FUNCTION, third::phy, and Reset().
Referenced by ns3::WifiNetDevice::CompleteConfig(), ns3::WaveNetDevice::DoInitialize(), AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), HeAggregationTest::DoRunSubTest(), ns3::AparfWifiManager::SetupPhy(), ns3::IdealWifiManager::SetupPhy(), ns3::MinstrelHtWifiManager::SetupPhy(), ns3::MinstrelWifiManager::SetupPhy(), ns3::ParfWifiManager::SetupPhy(), ns3::RraaWifiManager::SetupPhy(), and ns3::RrpaaWifiManager::SetupPhy().
SetUseGreenfieldProtection()
void ns3::WifiRemoteStationManager::SetUseGreenfieldProtection (bool enable)
Enable or disable protection for stations that do not support HT Greenfield format.
Parameters
enable enable or disable protection for stations that do not support HT Greenfield format
Definition at line 852 of file wifi-remote-station-manager.cc.
References m_useGreenfieldProtection, and NS_LOG_FUNCTION.
Referenced by ns3::ApWifiMac::IsNonGfHtStasPresent(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
SetUseNonErpProtection()
void ns3::WifiRemoteStationManager::SetUseNonErpProtection (bool enable)
Enable or disable protection for non-ERP stations.
Parameters
enable enable or disable protection for non-ERP stations
Definition at line 826 of file wifi-remote-station-manager.cc.
References m_useNonErpProtection, and NS_LOG_FUNCTION.
Referenced by ns3::ApWifiMac::GetUseNonErpProtection(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
SetUseNonHtProtection()
void ns3::WifiRemoteStationManager::SetUseNonHtProtection (bool enable)
Enable or disable protection for non-HT stations.
Parameters
enable enable or disable protection for non-HT stations
Definition at line 839 of file wifi-remote-station-manager.cc.
References m_useNonHtProtection, and NS_LOG_FUNCTION.
UpdateFragmentationThreshold()
void ns3::WifiRemoteStationManager::UpdateFragmentationThreshold (void)
Typically called to update the fragmentation threshold at the start of a new transmission.
This avoid that the fragmentation threshold gets changed during a transmission (see bug 730).
Definition at line 933 of file wifi-remote-station-manager.cc.
References m_fragmentationThreshold, and m_nextFragmentationThreshold.
Referenced by ns3::QosTxop::NotifyAccessGranted(), ns3::Txop::NotifyAccessGranted(), ns3::QosTxop::SendAddBaRequest(), and ns3::QosTxop::StartNextPacket().
UseGreenfieldForDestination()
bool ns3::WifiRemoteStationManager::UseGreenfieldForDestination (Mac48Address dest) const
Returns
whether HT greenfield should be used for a given destination address.
Parameters
dest the destination address
Returns
whether HT greenfield should be used for a given destination address
Definition at line 1676 of file wifi-remote-station-manager.cc.
References GetGreenfieldSupported(), and GetUseGreenfieldProtection().
Referenced by ns3::AarfWifiManager::DoGetDataTxVector(), ns3::AarfcdWifiManager::DoGetDataTxVector(), ns3::AmrrWifiManager::DoGetDataTxVector(), ns3::AparfWifiManager::DoGetDataTxVector(), ns3::ArfWifiManager::DoGetDataTxVector(), ns3::CaraWifiManager::DoGetDataTxVector(), ns3::ConstantRateWifiManager::DoGetDataTxVector(), ns3::IdealWifiManager::DoGetDataTxVector(), ns3::MinstrelHtWifiManager::DoGetDataTxVector(), ns3::OnoeWifiManager::DoGetDataTxVector(), ns3::ParfWifiManager::DoGetDataTxVector(), ns3::RraaWifiManager::DoGetDataTxVector(), ns3::RrpaaWifiManager::DoGetDataTxVector(), ns3::AarfWifiManager::DoGetRtsTxVector(), ns3::AarfcdWifiManager::DoGetRtsTxVector(), ns3::AmrrWifiManager::DoGetRtsTxVector(), ns3::AparfWifiManager::DoGetRtsTxVector(), ns3::ArfWifiManager::DoGetRtsTxVector(), ns3::CaraWifiManager::DoGetRtsTxVector(), ns3::ConstantRateWifiManager::DoGetRtsTxVector(), ns3::IdealWifiManager::DoGetRtsTxVector(), ns3::MinstrelHtWifiManager::DoGetRtsTxVector(), ns3::OnoeWifiManager::DoGetRtsTxVector(), ns3::ParfWifiManager::DoGetRtsTxVector(), ns3::RraaWifiManager::DoGetRtsTxVector(), ns3::RrpaaWifiManager::DoGetRtsTxVector(), ns3::MacLow::GetAckTxVector(), ns3::MacLow::GetBlockAckTxVector(), ns3::MacLow::GetCtsTxVector(), GetDataTxVector(), ns3::MinstrelWifiManager::GetDataTxVector(), GetRtsTxVector(), and ns3::MinstrelWifiManager::GetRtsTxVector().
UseLdpcForDestination()
bool ns3::WifiRemoteStationManager::UseLdpcForDestination (Mac48Address dest) const
Returns
whether LDPC should be used for a given destination address.
Parameters
dest the destination address
Returns
whether LDPC should be used for a given destination address
Definition at line 1682 of file wifi-remote-station-manager.cc.
References GetLdpcSupported().
Referenced by GetDataTxVector().
Member Data Documentation
m_bssBasicMcsSet
WifiModeList ns3::WifiRemoteStationManager::m_bssBasicMcsSet private
basic MCS set
Definition at line 1280 of file wifi-remote-station-manager.h.
Referenced by AddBasicMcs(), GetBasicMcs(), GetNBasicMcs(), NeedCtsToSelf(), and Reset().
m_bssBasicRateSet
WifiModeList ns3::WifiRemoteStationManager::m_bssBasicRateSet private
This member is the list of WifiMode objects that comprise the BSSBasicRateSet parameter.
This list is constructed through calls to WifiRemoteStationManager::AddBasicMode(), and an API that allows external access to it is available through WifiRemoteStationManager::GetNBasicModes() and WifiRemoteStationManager::GetBasicMode(). basic rate set
Definition at line 1279 of file wifi-remote-station-manager.h.
Referenced by AddBasicMode(), GetBasicMode(), GetNBasicModes(), GetNNonErpBasicModes(), GetNonErpBasicMode(), NeedCtsToSelf(), and Reset().
m_defaultTxMcs
WifiMode ns3::WifiRemoteStationManager::m_defaultTxMcs private
The default transmission modulation-coding scheme (MCS)
Definition at line 1286 of file wifi-remote-station-manager.h.
Referenced by GetDefaultMcs(), and SetupPhy().
m_defaultTxMode
WifiMode ns3::WifiRemoteStationManager::m_defaultTxMode private
The default transmission mode.
Definition at line 1285 of file wifi-remote-station-manager.h.
Referenced by GetDefaultMode(), and SetupPhy().
m_defaultTxPowerLevel
uint8_t ns3::WifiRemoteStationManager::m_defaultTxPowerLevel private
Default transmission power level.
Definition at line 1294 of file wifi-remote-station-manager.h.
Referenced by GetDataTxVector(), GetDefaultTxPowerLevel(), GetRtsTxVector(), GetTypeId(), and SetDefaultTxPowerLevel().
m_erpProtectionMode
ProtectionMode ns3::WifiRemoteStationManager::m_erpProtectionMode private
Protection mode for ERP stations when non-ERP stations are detected.
Definition at line 1301 of file wifi-remote-station-manager.h.
Referenced by GetTypeId(), NeedCtsToSelf(), and NeedRts().
m_fragmentationThreshold
uint32_t ns3::WifiRemoteStationManager::m_fragmentationThreshold private
Current threshold for fragmentation.
Definition at line 1292 of file wifi-remote-station-manager.h.
Referenced by DoGetFragmentationThreshold(), and UpdateFragmentationThreshold().
m_htProtectionMode
ProtectionMode ns3::WifiRemoteStationManager::m_htProtectionMode private
Protection mode for HT stations when non-HT stations are detected.
Definition at line 1302 of file wifi-remote-station-manager.h.
Referenced by GetTypeId(), NeedCtsToSelf(), and NeedRts().
m_macTxDataFailed
TracedCallback<Mac48Address> ns3::WifiRemoteStationManager::m_macTxDataFailed private
The trace source fired when the transmission of a single data packet has failed.
Definition at line 1314 of file wifi-remote-station-manager.h.
Referenced by GetTypeId(), ReportAmpduTxStatus(), and ReportDataFailed().
m_macTxFinalDataFailed
TracedCallback<Mac48Address> ns3::WifiRemoteStationManager::m_macTxFinalDataFailed private
The trace source fired when the transmission of a data packet has exceeded the maximum number of attempts.
Definition at line 1324 of file wifi-remote-station-manager.h.
Referenced by GetTypeId(), and ReportFinalDataFailed().
m_macTxFinalRtsFailed
TracedCallback<Mac48Address> ns3::WifiRemoteStationManager::m_macTxFinalRtsFailed private
The trace source fired when the transmission of a RTS has exceeded the maximum number of attempts.
Definition at line 1319 of file wifi-remote-station-manager.h.
Referenced by GetTypeId(), and ReportFinalRtsFailed().
m_macTxRtsFailed
TracedCallback<Mac48Address> ns3::WifiRemoteStationManager::m_macTxRtsFailed private
The trace source fired when the transmission of a single RTS has failed.
Definition at line 1310 of file wifi-remote-station-manager.h.
Referenced by GetTypeId(), and ReportRtsFailed().
m_maxSlrc
uint32_t ns3::WifiRemoteStationManager::m_maxSlrc private
Maximum STA long retry count (SLRC)
Definition at line 1290 of file wifi-remote-station-manager.h.
Referenced by NeedRetransmission(), and SetMaxSlrc().
m_maxSsrc
uint32_t ns3::WifiRemoteStationManager::m_maxSsrc private
Maximum STA short retry count (SSRC)
Definition at line 1289 of file wifi-remote-station-manager.h.
Referenced by NeedRetransmission(), and SetMaxSsrc().
m_nextFragmentationThreshold
uint32_t ns3::WifiRemoteStationManager::m_nextFragmentationThreshold private
Threshold for fragmentation that will be used for the next transmission.
Definition at line 1293 of file wifi-remote-station-manager.h.
Referenced by DoSetFragmentationThreshold(), and UpdateFragmentationThreshold().
m_nonUnicastMode
WifiMode ns3::WifiRemoteStationManager::m_nonUnicastMode private
Transmission mode for non-unicast Data frames.
Definition at line 1295 of file wifi-remote-station-manager.h.
Referenced by GetNonUnicastMode(), and GetTypeId().
m_pcfSupported
bool ns3::WifiRemoteStationManager::m_pcfSupported private
Flag if PCF capability is supported.
Definition at line 1288 of file wifi-remote-station-manager.h.
Referenced by GetPcfSupported(), and SetPcfSupported().
m_rtsCtsThreshold
uint32_t ns3::WifiRemoteStationManager::m_rtsCtsThreshold private
Threshold for RTS/CTS.
Definition at line 1291 of file wifi-remote-station-manager.h.
Referenced by NeedRetransmission(), NeedRts(), ReportDataFailed(), ReportDataOk(), ReportFinalDataFailed(), and SetRtsCtsThreshold().
m_shortPreambleEnabled
bool ns3::WifiRemoteStationManager::m_shortPreambleEnabled private
flag if short PHY preamble is enabled
Definition at line 1299 of file wifi-remote-station-manager.h.
Referenced by GetShortPreambleEnabled(), and SetShortPreambleEnabled().
m_shortSlotTimeEnabled
bool ns3::WifiRemoteStationManager::m_shortSlotTimeEnabled private
flag if short slot time is enabled
Definition at line 1300 of file wifi-remote-station-manager.h.
Referenced by GetShortSlotTimeEnabled(), and SetShortSlotTimeEnabled().
m_slrc
std::array<uint32_t, AC_BE_NQOS> ns3::WifiRemoteStationManager::m_slrc private
long retry count per AC
Definition at line 1305 of file wifi-remote-station-manager.h.
Referenced by NeedRetransmission(), ReportDataFailed(), ReportDataOk(), ReportFinalDataFailed(), and Reset().
m_ssrc
std::array<uint32_t, AC_BE_NQOS> ns3::WifiRemoteStationManager::m_ssrc private
short retry count per AC
Definition at line 1304 of file wifi-remote-station-manager.h.
Referenced by NeedRetransmission(), ReportDataFailed(), ReportDataOk(), ReportFinalDataFailed(), ReportFinalRtsFailed(), ReportRtsFailed(), ReportRtsOk(), and Reset().
m_states
StationStates ns3::WifiRemoteStationManager::m_states private
States of known stations.
Definition at line 1282 of file wifi-remote-station-manager.h.
Referenced by LookupState(), and Reset().
m_stations
Stations ns3::WifiRemoteStationManager::m_stations private
Information for each known stations.
Definition at line 1283 of file wifi-remote-station-manager.h.
Referenced by Lookup(), and Reset().
m_useGreenfieldProtection
bool ns3::WifiRemoteStationManager::m_useGreenfieldProtection private
flag if protection for stations that do not support HT Greenfield format is enabled
Definition at line 1298 of file wifi-remote-station-manager.h.
Referenced by GetUseGreenfieldProtection(), and SetUseGreenfieldProtection().
m_useNonErpProtection
bool ns3::WifiRemoteStationManager::m_useNonErpProtection private
flag if protection for non-ERP stations against ERP transmissions is enabled
Definition at line 1296 of file wifi-remote-station-manager.h.
Referenced by GetUseNonErpProtection(), NeedCtsToSelf(), NeedRts(), and SetUseNonErpProtection().
m_useNonHtProtection
bool ns3::WifiRemoteStationManager::m_useNonHtProtection private
flag if protection for non-HT stations against HT transmissions is enabled
Definition at line 1297 of file wifi-remote-station-manager.h.
Referenced by GetUseNonHtProtection(), NeedCtsToSelf(), NeedRts(), and SetUseNonHtProtection().
m_wifiMac
Ptr<WifiMac> ns3::WifiRemoteStationManager::m_wifiMac private
This is a pointer to the WifiMac associated with this WifiRemoteStationManager that is set on call to WifiRemoteStationManager::SetupMac().
Through this pointer the station manager can determine MAC characteristics, such as the interframe spaces.
Definition at line 1269 of file wifi-remote-station-manager.h.
Referenced by GetMac(), and SetupMac().
m_wifiPhy
Ptr<WifiPhy> ns3::WifiRemoteStationManager::m_wifiPhy private
This is a pointer to the WifiPhy associated with this WifiRemoteStationManager that is set on call to WifiRemoteStationManager::SetupPhy().
Through this pointer the station manager can determine PHY characteristics, such as the set of all transmission rates that may be supported (the "DeviceRateSet").
Definition at line 1261 of file wifi-remote-station-manager.h.
Referenced by AddAllSupportedMcs(), AddAllSupportedModes(), AddStationHeCapabilities(), AddStationHtCapabilities(), AddStationVhtCapabilities(), GetCtsToSelfTxVector(), GetDataTxVector(), GetGreenfieldSupported(), GetGuardInterval(), GetHeSupported(), GetHtSupported(), GetLdpcSupported(), GetMaxNumberOfTransmitStreams(), GetNumberOfAntennas(), GetPhy(), GetRtsTxVector(), GetShortGuardIntervalSupported(), GetVhtSupported(), LookupState(), and SetupPhy().
The documentation for this class was generated from the following files:
src/wifi/model/wifi-remote-station-manager.h
src/wifi/model/wifi-remote-station-manager.cc