ns-3: ns3::WaveHelper Class Reference
ns3::WaveHelper Class Reference
WAVE module
helps to create WaveNetDevice objects
#include "wave-helper.h"
Public Member Functions
WaveHelper ()
virtual ~WaveHelper ()
int64_t AssignStreams (NetDeviceContainer c, int64_t stream)
Assign a fixed random variable stream number to the random variables used by the Phy and Mac aspects of the WAVE models.
void CreateMacForChannel (std::vector< uint32_t > channelNumbers)
void CreatePhys (uint32_t phys)
virtual NetDeviceContainer Install (const WifiPhyHelper &phy, const WifiMacHelper &mac, NodeContainer c) const
virtual NetDeviceContainer Install (const WifiPhyHelper &phy, const WifiMacHelper &mac, Ptr< Node > node) const
virtual NetDeviceContainer Install (const WifiPhyHelper &phy, const WifiMacHelper &mac, std::string nodeName) const
void SetAckPolicySelectorForAc (AcIndex ac, std::string type, std::string n0="", const AttributeValue &v0=EmptyAttributeValue(), std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue(), std::string n6="", const AttributeValue &v6=EmptyAttributeValue(), std::string n7="", const AttributeValue &v7=EmptyAttributeValue())
void SetChannelScheduler (std::string type, std::string n0="", const AttributeValue &v0=EmptyAttributeValue(), std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue(), std::string n6="", const AttributeValue &v6=EmptyAttributeValue(), std::string n7="", const AttributeValue &v7=EmptyAttributeValue())
void SetRemoteStationManager (std::string type, std::string n0="", const AttributeValue &v0=EmptyAttributeValue(), std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue(), std::string n6="", const AttributeValue &v6=EmptyAttributeValue(), std::string n7="", const AttributeValue &v7=EmptyAttributeValue())
Static Public Member Functions
static WaveHelper Default (void)
static void EnableLogComponents (void)
Helper to enable all WaveNetDevice log components with one statement.
Protected Attributes
ObjectFactory m_ackPolicySelector [4]
ack policy selector for all ACs
ObjectFactory m_channelScheduler
channel scheduler
std::vector< uint32_t > m_macsForChannelNumber
MACs for channel number.
uint32_t m_physNumber
Phy number.
ObjectFactory m_stationManager
station manager
Detailed Description
helps to create WaveNetDevice objects
This class can help to create a large set of similar WaveNetDevice objects and to configure a large set of their attributes during creation.
Generally WaveHelper with default configuration will create devices with 7 MAC entities,1 PHY entity and a multiple-channel scheduler for to deal with these entities.
If users can make sure on which channel this WAVE device will work, they can set specific channel numbers to save resources of unused channels as below: WaveHelper helper = WaveHelper::Default (); uint32_t channels[] = {CCH, SCH1}; std::vector<uint32_t> channelsVector (channels, channels + 2); helper.helper.CreateMacForChannel (channelsVector);
If users can create other channel scheduler such as "AnotherScheduler" which can assign channel access in the context of more PHY entities, they can use this helper to create WAVE devices as below: WaveHelper helper = WaveHelper::Default (); helper.helper.CreateMacForChannel (ChannelManager::GetWaveChannels ()); helper.CreatePhys (2); // or other number which should be less than 7 helper.SetChannelScheduler ("ns3::AnotherScheduler"); helper.SetRemoteStationManager ("ns3::ConstantRateWifiManager"); // or other rate control algorithms
Definition at line 112 of file wave-helper.h.
Constructor & Destructor Documentation
WaveHelper()
ns3::WaveHelper::WaveHelper ()
Definition at line 261 of file wave-helper.cc.
~WaveHelper()
ns3::WaveHelper::~WaveHelper () virtual
Definition at line 265 of file wave-helper.cc.
Member Function Documentation
AssignStreams()
int64_t ns3::WaveHelper::AssignStreams (NetDeviceContainer c, int64_t stream)
Assign a fixed random variable stream number to the random variables used by the Phy and Mac aspects of the WAVE models.
Each device in container c has fixed stream numbers assigned to its random variables. The Wifi channel (e.g. propagation loss model) is excluded. Return the number of streams (possibly zero) that have been assigned. The Install() method should have previously been called by the user.
Parameters
c NetDeviceContainer of the set of net devices for which the WaveNetDevice should be modified to use fixed streams
stream first stream index to use
Returns
the number of stream indices assigned by this helper
Definition at line 499 of file wave-helper.cc.
References ns3::Txop::AssignStreams(), ns3::NetDeviceContainer::Begin(), ns3::NetDeviceContainer::End(), ns3::PointerValue::Get(), ns3::WaveNetDevice::GetMacs(), and ns3::WaveNetDevice::GetPhys().
CreateMacForChannel()
void ns3::WaveHelper::CreateMacForChannel (std::vector< uint32_t > channelNumbers)
Parameters
channelNumbers the MAC entities will be created to support these channels for multiple channel operation.
Definition at line 289 of file wave-helper.cc.
References ns3::ChannelManager::IsWaveChannel(), m_macsForChannelNumber, and NS_FATAL_ERROR.
Referenced by Default().
CreatePhys()
void ns3::WaveHelper::CreatePhys (uint32_t phys)
Parameters
phys the number of PHY entity which will be created for multiple channel operation.
Definition at line 306 of file wave-helper.cc.
References ns3::ChannelManager::GetNumberOfWaveChannels(), m_physNumber, and NS_FATAL_ERROR.
Referenced by Default().
Default()
WaveHelper ns3::WaveHelper::Default (void) static
Returns
a new WaveHelper in a default state
The default state is defined as being seven OcbWifiMac MAC entities with an ConstantRate rate control algorithm, one WifiPhy entity and a default multiple-channel scheduler DefaultChannelScheduler for assigning channel access with these created entities.
Definition at line 270 of file wave-helper.cc.
References ns3::AC_BE, ns3::AC_BK, ns3::AC_VI, ns3::AC_VO, CreateMacForChannel(), CreatePhys(), ns3::ChannelManager::GetWaveChannels(), SetAckPolicySelectorForAc(), SetChannelScheduler(), and SetRemoteStationManager().
Referenced by WaveNetDeviceExample::CreateWaveNodes().
EnableLogComponents()
void ns3::WaveHelper::EnableLogComponents (void) static
Helper to enable all WaveNetDevice log components with one statement.
Definition at line 482 of file wave-helper.cc.
References ns3::WifiHelper::EnableLogComponents(), ns3::LOG_LEVEL_ALL, and ns3::LogComponentEnable().
Referenced by VanetRoutingExperiment::SetupAdhocDevices().
Install() [1/3]
NetDeviceContainer ns3::WaveHelper::Install (const WifiPhyHelper & phy, const WifiMacHelper & mac, NodeContainer c) const virtual
Parameters
phy the PHY helper to create PHY objects
mac the MAC helper to create MAC objects
c the set of nodes on which a wifi device must be created
Returns
a device container which contains all the devices created by this method.
Definition at line 389 of file wave-helper.cc.
References ns3::AC_BE, ns3::AC_BK, ns3::AC_VI, ns3::AC_VO, ns3::Node::AddDevice(), ns3::WaveNetDevice::AddMac(), ns3::WaveNetDevice::AddPhy(), ns3::Mac48Address::Allocate(), ns3::NodeContainer::Begin(), ns3::OcbWifiMac::ConfigureStandard(), ns3::WifiMacHelper::Create(), ns3::WifiPhyHelper::Create(), ns3::ObjectFactory::Create(), first::devices, ns3::OcbWifiMac::EnableForWave(), ns3::NodeContainer::End(), ns3::BooleanValue::Get(), ns3::PointerValue::Get(), ns3::ObjectBase::GetAttributeFailSafe(), ns3::ChannelManager::GetCch(), m_ackPolicySelector, m_channelScheduler, m_macsForChannelNumber, m_physNumber, m_stationManager, NS_FATAL_ERROR, NS_UNUSED, third::phy, ns3::WaveNetDevice::SetAddress(), ns3::WaveNetDevice::SetChannelCoordinator(), ns3::WaveNetDevice::SetChannelManager(), ns3::WaveNetDevice::SetChannelScheduler(), ns3::WaveNetDevice::SetVsaManager(), ns3::RegularWifiMac::SetWifiRemoteStationManager(), ns3::WIFI_PHY_BAND_5GHZ, ns3::WIFI_PHY_STANDARD_80211p, and ns3::WIFI_STANDARD_80211p.
Referenced by WaveNetDeviceExample::CreateWaveNodes(), TestCaseHelper::CreatWaveDevice(), Install(), and VanetRoutingExperiment::SetupAdhocDevices().
Install() [2/3]
NetDeviceContainer ns3::WaveHelper::Install (const WifiPhyHelper & phy, const WifiMacHelper & mac, Ptr< Node > node) const virtual
Parameters
phy the PHY helper to create PHY objects
mac the MAC helper to create MAC objects
node the node on which a wifi device must be created
Returns
a device container which contains all the devices created by this method.
Definition at line 469 of file wave-helper.cc.
References Install(), third::mac, and third::phy.
Install() [3/3]
NetDeviceContainer ns3::WaveHelper::Install (const WifiPhyHelper & phy, const WifiMacHelper & mac, std::string nodeName) const virtual
Parameters
phy the PHY helper to create PHY objects
mac the MAC helper to create MAC objects
nodeName the name of node on which a wifi device must be created
Returns
a device container which contains all the devices created by this method.
Definition at line 475 of file wave-helper.cc.
References Install(), third::mac, and third::phy.
SetAckPolicySelectorForAc()
void ns3::WaveHelper::SetAckPolicySelectorForAc (AcIndex ac, std::string type, std::string n0 = "", const AttributeValue & v0 = EmptyAttributeValue (), std::string n1 = "", const AttributeValue & v1 = EmptyAttributeValue (), std::string n2 = "", const AttributeValue & v2 = EmptyAttributeValue (), std::string n3 = "", const AttributeValue & v3 = EmptyAttributeValue (), std::string n4 = "", const AttributeValue & v4 = EmptyAttributeValue (), std::string n5 = "", const AttributeValue & v5 = EmptyAttributeValue (), std::string n6 = "", const AttributeValue & v6 = EmptyAttributeValue (), std::string n7 = "", const AttributeValue & v7 = EmptyAttributeValue ())
Parameters
ac the Access Category to attach the ack policy selector to.
type the type of ns3::WifiAckPolicySelector to create.
n0 the name of the attribute to set
v0 the value of the attribute to set
n1 the name of the attribute to set
v1 the value of the attribute to set
n2 the name of the attribute to set
v2 the value of the attribute to set
n3 the name of the attribute to set
v3 the value of the attribute to set
n4 the name of the attribute to set
v4 the value of the attribute to set
n5 the name of the attribute to set
v5 the value of the attribute to set
n6 the name of the attribute to set
v6 the value of the attribute to set
n7 the name of the attribute to set
v7 the value of the attribute to set
All the attributes specified in this method should exist in the requested ack policy selector.
Definition at line 343 of file wave-helper.cc.
References m_ackPolicySelector, ns3::ObjectFactory::Set(), and ns3::ObjectFactory::SetTypeId().
Referenced by Default().
SetChannelScheduler()
void ns3::WaveHelper::SetChannelScheduler (std::string type, std::string n0 = "", const AttributeValue & v0 = EmptyAttributeValue (), std::string n1 = "", const AttributeValue & v1 = EmptyAttributeValue (), std::string n2 = "", const AttributeValue & v2 = EmptyAttributeValue (), std::string n3 = "", const AttributeValue & v3 = EmptyAttributeValue (), std::string n4 = "", const AttributeValue & v4 = EmptyAttributeValue (), std::string n5 = "", const AttributeValue & v5 = EmptyAttributeValue (), std::string n6 = "", const AttributeValue & v6 = EmptyAttributeValue (), std::string n7 = "", const AttributeValue & v7 = EmptyAttributeValue ())
Parameters
type the type of ns3::ChannelScheduler to create.
n0 the name of the attribute to set
v0 the value of the attribute to set
n1 the name of the attribute to set
v1 the value of the attribute to set
n2 the name of the attribute to set
v2 the value of the attribute to set
n3 the name of the attribute to set
v3 the value of the attribute to set
n4 the name of the attribute to set
v4 the value of the attribute to set
n5 the name of the attribute to set
v5 the value of the attribute to set
n6 the name of the attribute to set
v6 the value of the attribute to set
n7 the name of the attribute to set
v7 the value of the attribute to set
All the attributes specified in this method should exist in the requested channel scheduler.
Definition at line 366 of file wave-helper.cc.
References m_channelScheduler, ns3::ObjectFactory::Set(), and ns3::ObjectFactory::SetTypeId().
Referenced by Default().
SetRemoteStationManager()
void ns3::WaveHelper::SetRemoteStationManager (std::string type, std::string n0 = "", const AttributeValue & v0 = EmptyAttributeValue (), std::string n1 = "", const AttributeValue & v1 = EmptyAttributeValue (), std::string n2 = "", const AttributeValue & v2 = EmptyAttributeValue (), std::string n3 = "", const AttributeValue & v3 = EmptyAttributeValue (), std::string n4 = "", const AttributeValue & v4 = EmptyAttributeValue (), std::string n5 = "", const AttributeValue & v5 = EmptyAttributeValue (), std::string n6 = "", const AttributeValue & v6 = EmptyAttributeValue (), std::string n7 = "", const AttributeValue & v7 = EmptyAttributeValue ())
Parameters
type the type of ns3::WifiRemoteStationManager to create.
n0 the name of the attribute to set
v0 the value of the attribute to set
n1 the name of the attribute to set
v1 the value of the attribute to set
n2 the name of the attribute to set
v2 the value of the attribute to set
n3 the name of the attribute to set
v3 the value of the attribute to set
n4 the name of the attribute to set
v4 the value of the attribute to set
n5 the name of the attribute to set
v5 the value of the attribute to set
n6 the name of the attribute to set
v6 the value of the attribute to set
n7 the name of the attribute to set
v7 the value of the attribute to set
All the attributes specified in this method should exist in the requested station manager.
Definition at line 320 of file wave-helper.cc.
References m_stationManager, ns3::ObjectFactory::Set(), and ns3::ObjectFactory::SetTypeId().
Referenced by Default(), and VanetRoutingExperiment::SetupAdhocDevices().
Member Data Documentation
m_ackPolicySelector
ObjectFactory ns3::WaveHelper::m_ackPolicySelector[4] protected
ack policy selector for all ACs
Definition at line 280 of file wave-helper.h.
Referenced by Install(), and SetAckPolicySelectorForAc().
m_channelScheduler
ObjectFactory ns3::WaveHelper::m_channelScheduler protected
channel scheduler
Definition at line 281 of file wave-helper.h.
Referenced by Install(), and SetChannelScheduler().
m_macsForChannelNumber
std::vector<uint32_t> ns3::WaveHelper::m_macsForChannelNumber protected
MACs for channel number.
Definition at line 282 of file wave-helper.h.
Referenced by CreateMacForChannel(), and Install().
m_physNumber
uint32_t ns3::WaveHelper::m_physNumber protected
Phy number.
Definition at line 283 of file wave-helper.h.
Referenced by CreatePhys(), and Install().
m_stationManager
ObjectFactory ns3::WaveHelper::m_stationManager protected
station manager
Definition at line 279 of file wave-helper.h.
Referenced by Install(), and SetRemoteStationManager().
The documentation for this class was generated from the following files:
src/wave/helper/wave-helper.h
src/wave/helper/wave-helper.cc