ns-3: ns3::PointToPointRemoteChannel Class Reference
ns3::PointToPointRemoteChannel Class Reference
Point-To-Point Network Device
A Remote Point-To-Point Channel.
#include "point-to-point-remote-channel.h"
Public Member Functions
PointToPointRemoteChannel ()
Constructor.
~PointToPointRemoteChannel ()
Deconstructor.
virtual bool TransmitStart (Ptr< const Packet > p, Ptr< PointToPointNetDevice > src, Time txTime)
Transmit the packet.
Public Member Functions inherited from ns3::PointToPointChannel
PointToPointChannel ()
Create a PointToPointChannel.
void Attach (Ptr< PointToPointNetDevice > device)
Attach a given netdevice to this channel.
virtual Ptr< NetDevice > GetDevice (std::size_t i) const
Get NetDevice corresponding to index i on this channel.
virtual std::size_t GetNDevices (void) const
Get number of devices on this channel.
Ptr< PointToPointNetDevice > GetPointToPointDevice (std::size_t i) const
Get PointToPointNetDevice corresponding to index i on this channel.
Public Member Functions inherited from ns3::Channel
Channel ()
virtual ~Channel ()
uint32_t GetId (void) const
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the TypeId.
Static Public Member Functions inherited from ns3::PointToPointChannel
static TypeId GetTypeId (void)
Get the TypeId.
Static Public Member Functions inherited from ns3::Channel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Protected Types inherited from ns3::PointToPointChannel
typedef void(* TxRxAnimationCallback) (Ptr< const Packet > packet, Ptr< NetDevice > txDevice, Ptr< NetDevice > rxDevice, Time duration, Time lastBitTime)
TracedCallback signature for packet transmission animation events.
Protected Member Functions inherited from ns3::PointToPointChannel
Time GetDelay (void) const
Get the delay associated with this channel.
Ptr< PointToPointNetDevice > GetDestination (uint32_t i) const
Get the net-device destination.
Ptr< PointToPointNetDevice > GetSource (uint32_t i) const
Get the net-device source.
bool IsInitialized (void) const
Check to make sure the link is initialized.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A Remote Point-To-Point Channel.
This object connects two point-to-point net devices where at least one is not local to this simulator object. It simply override the transmit method and uses an MPI Send operation instead.
Definition at line 41 of file point-to-point-remote-channel.h.
Constructor & Destructor Documentation
PointToPointRemoteChannel()
ns3::PointToPointRemoteChannel::PointToPointRemoteChannel ()
Constructor.
Definition at line 47 of file point-to-point-remote-channel.cc.
~PointToPointRemoteChannel()
ns3::PointToPointRemoteChannel::~PointToPointRemoteChannel ()
Deconstructor.
Definition at line 52 of file point-to-point-remote-channel.cc.
Member Function Documentation
GetTypeId()
TypeId ns3::PointToPointRemoteChannel::GetTypeId (void) static
Get the TypeId.
Returns
The TypeId for this class
Definition at line 37 of file point-to-point-remote-channel.cc.
References ns3::TypeId::SetParent().
TransmitStart()
bool ns3::PointToPointRemoteChannel::TransmitStart (Ptr< const Packet > p, Ptr< PointToPointNetDevice > src, Time txTime) virtual
Transmit the packet.
Parameters
p Packet to transmit
src Source PointToPointNetDevice
txTime Transmit time to apply
Returns
true if successful (currently always true)
Reimplemented from ns3::PointToPointChannel.
Definition at line 57 of file point-to-point-remote-channel.cc.
References ns3::PointToPointChannel::GetDelay(), ns3::PointToPointChannel::GetDestination(), ns3::PointToPointChannel::GetSource(), ns3::PointToPointChannel::IsInitialized(), ns3::Simulator::Now(), NS_LOG_FUNCTION, NS_LOG_LOGIC, and ns3::MpiInterface::SendPacket().
The documentation for this class was generated from the following files:
src/point-to-point/model/point-to-point-remote-channel.h
src/point-to-point/model/point-to-point-remote-channel.cc