ns-3: ns3::ObssPdAlgorithm Class Reference
ns3::ObssPdAlgorithm Class Reference abstract
Wifi Models
OBSS PD algorithm interface.
#include "obss-pd-algorithm.h"
Public Types
typedef void(* ResetTracedCallback) (uint8_t bssColor, double rssiDbm, bool powerRestricted, double txPowerMaxDbmSiso, double txPowerMaxDbmMimo)
TracedCallback signature for OBSS_PD reset events.
Public Member Functions
virtual void ConnectWifiNetDevice (const Ptr< WifiNetDevice > device)
Connect the WifiNetDevice and setup eventual callbacks.
virtual void ReceiveHeSig (HePreambleParameters params)=0
void ResetPhy (HePreambleParameters params)
Reset PHY to IDLE.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes
Ptr< WifiNetDevice > m_device
Pointer to the WifiNetDevice.
double m_obssPdLevel
Current OBSS PD level (dBm)
Private Attributes
double m_obssPdLevelMax
Maximum OBSS PD level (dBm)
double m_obssPdLevelMin
Minimum OBSS PD level (dBm)
TracedCallback< uint8_t, double, bool, double, double > m_resetEvent
TracedCallback signature for PHY reset events.
double m_txPowerRefMimo
MIMO reference TX power level (dBm)
double m_txPowerRefSiso
SISO reference TX power level (dBm)
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
OBSS PD algorithm interface.
Introspection did not find any typical Config paths.
This object provides the interface for all OBSS_PD algorithms and is designed to be subclassed.
OBSS_PD stands for Overlapping Basic Service Set Preamble-Detection. OBSS_PD is an 802.11ax feature that allows a STA, under specific conditions, to ignore an inter-BSS PPDU.
Attributes
ObssPdLevel: The current OBSS PD level (dBm).
Set with class: ns3::DoubleValue
Underlying type: double -101:-62
Initial value: -82
Flags: construct write read
ObssPdLevelMin: Minimum value (dBm) of OBSS PD level.
Set with class: ns3::DoubleValue
Underlying type: double -101:-62
Initial value: -82
Flags: construct write read
ObssPdLevelMax: Maximum value (dBm) of OBSS PD level.
Set with class: ns3::DoubleValue
Underlying type: double -101:-62
Initial value: -62
Flags: construct write read
TxPowerRefSiso: The SISO reference TX power level (dBm).
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 21
Flags: construct write read
TxPowerRefMimo: The MIMO reference TX power level (dBm).
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 25
Flags: construct write read
TraceSources
Reset: Trace CCA Reset event
Callback signature: ns3::ObssPdAlgorithm::ResetTracedCallback
Size of this type is 104 bytes (on a 64-bit architecture).
Definition at line 45 of file obss-pd-algorithm.h.
Member Typedef Documentation
ResetTracedCallback
typedef void(* ns3::ObssPdAlgorithm::ResetTracedCallback) (uint8_t bssColor, double rssiDbm, bool powerRestricted, double txPowerMaxDbmSiso, double txPowerMaxDbmMimo)
TracedCallback signature for OBSS_PD reset events.
Parameters
[in] bssColor The BSS color of frame triggering the reset
[in] rssiDbm The RSSI (dBm) of frame triggering the reset
[in] powerRestricted Whether a TX power restriction is triggered
[in] txPowerMaxDbmSiso The SISO TX power restricted level (dBm)
[in] txPowerMaxDbmMimo The MIMO TX power restricted level (dBm)
Definition at line 83 of file obss-pd-algorithm.h.
Member Function Documentation
ConnectWifiNetDevice()
void ns3::ObssPdAlgorithm::ConnectWifiNetDevice (const Ptr< WifiNetDevice > device) virtual
Connect the WifiNetDevice and setup eventual callbacks.
Parameters
device the WifiNetDevice
Reimplemented in ns3::ConstantObssPdAlgorithm.
Definition at line 80 of file obss-pd-algorithm.cc.
References m_device, and NS_LOG_FUNCTION.
Referenced by ns3::ConstantObssPdAlgorithm::ConnectWifiNetDevice().
DoDispose()
void ns3::ObssPdAlgorithm::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 73 of file obss-pd-algorithm.cc.
References m_device, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::ObssPdAlgorithm::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 35 of file obss-pd-algorithm.cc.
References m_obssPdLevel, m_obssPdLevelMax, m_obssPdLevelMin, m_resetEvent, m_txPowerRefMimo, m_txPowerRefSiso, ns3::MakeDoubleAccessor(), ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
ReceiveHeSig()
virtual void ns3::ObssPdAlgorithm::ReceiveHeSig (HePreambleParameters params) pure virtual
Parameters
params the HE SIG parameters
Evaluate the receipt of HE SIG.
Implemented in ns3::ConstantObssPdAlgorithm.
ResetPhy()
void ns3::ObssPdAlgorithm::ResetPhy (HePreambleParameters params)
Reset PHY to IDLE.
Parameters
params HePreambleParameters causing PHY reset
Definition at line 87 of file obss-pd-algorithm.cc.
References ns3::HePreambleParameters::bssColor, ns3::UintegerValue::Get(), ns3::WifiNetDevice::GetHeConfiguration(), ns3::WifiNetDevice::GetPhy(), m_device, m_obssPdLevel, m_obssPdLevelMax, m_obssPdLevelMin, m_resetEvent, m_txPowerRefMimo, m_txPowerRefSiso, NS_ASSERT, NS_LOG_DEBUG, third::phy, ns3::HePreambleParameters::rssiW, and ns3::WToDbm().
Referenced by ns3::ConstantObssPdAlgorithm::ReceiveHeSig().
Member Data Documentation
m_device
Ptr<WifiNetDevice> ns3::ObssPdAlgorithm::m_device protected
Pointer to the WifiNetDevice.
Definition at line 88 of file obss-pd-algorithm.h.
Referenced by ConnectWifiNetDevice(), DoDispose(), ns3::ConstantObssPdAlgorithm::ReceiveHeSig(), and ResetPhy().
m_obssPdLevel
double ns3::ObssPdAlgorithm::m_obssPdLevel protected
Current OBSS PD level (dBm)
Definition at line 89 of file obss-pd-algorithm.h.
Referenced by GetTypeId(), ns3::ConstantObssPdAlgorithm::ReceiveHeSig(), and ResetPhy().
m_obssPdLevelMax
double ns3::ObssPdAlgorithm::m_obssPdLevelMax private
Maximum OBSS PD level (dBm)
Definition at line 94 of file obss-pd-algorithm.h.
Referenced by GetTypeId(), and ResetPhy().
m_obssPdLevelMin
double ns3::ObssPdAlgorithm::m_obssPdLevelMin private
Minimum OBSS PD level (dBm)
Definition at line 93 of file obss-pd-algorithm.h.
Referenced by GetTypeId(), and ResetPhy().
m_resetEvent
TracedCallback<uint8_t, double, bool, double, double> ns3::ObssPdAlgorithm::m_resetEvent private
TracedCallback signature for PHY reset events.
Definition at line 101 of file obss-pd-algorithm.h.
Referenced by GetTypeId(), and ResetPhy().
m_txPowerRefMimo
double ns3::ObssPdAlgorithm::m_txPowerRefMimo private
MIMO reference TX power level (dBm)
Definition at line 96 of file obss-pd-algorithm.h.
Referenced by GetTypeId(), and ResetPhy().
m_txPowerRefSiso
double ns3::ObssPdAlgorithm::m_txPowerRefSiso private
SISO reference TX power level (dBm)
Definition at line 95 of file obss-pd-algorithm.h.
Referenced by GetTypeId(), and ResetPhy().
The documentation for this class was generated from the following files:
src/wifi/model/obss-pd-algorithm.h
src/wifi/model/obss-pd-algorithm.cc