ns-3: ns3::ConstantRandomVariable Class Reference
ns3::ConstantRandomVariable Class Reference
Core » Random Variables
The Random Number Generator (RNG) that returns a constant.
#include "random-variable-stream.h"
Public Member Functions
ConstantRandomVariable ()
Creates a constant RNG with the default constant value.
double GetConstant (void) const
Get the constant value returned by this RNG stream.
uint32_t GetInteger (uint32_t constant)
Get the next random value, as an integer equal to the argument.
virtual uint32_t GetInteger (void)
Get the next random value as an integer drawn from the distribution.
double GetValue (double constant)
Get the next random value, as a double equal to the argument.
virtual double GetValue (void)
Get the next random value as a double drawn from the distribution.
Public Member Functions inherited from ns3::RandomVariableStream
RandomVariableStream ()
Default constructor.
virtual ~RandomVariableStream ()
Destructor.
int64_t GetStream (void) const
Returns the stream number for the RngStream.
bool IsAntithetic (void) const
Check if antithetic values will be generated.
void SetAntithetic (bool isAntithetic)
Specify whether antithetic values should be generated.
void SetStream (int64_t stream)
Specifies the stream number for the RngStream.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::RandomVariableStream
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
double m_constant
The constant value returned by this RNG stream.
Additional Inherited Members
Protected Member Functions inherited from ns3::RandomVariableStream
RngStream * Peek (void) const
Get the pointer to the underlying RngStream.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The Random Number Generator (RNG) that returns a constant.
This RNG returns the same value for every sample.
Antithetic Values.
This RNG ignores the antithetic setting.
Config Paths
ns3::ConstantRandomVariable is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::SimpleNetDevice/ReceiveErrorModel/$ns3::RateErrorModel/RanVar/$ns3::ConstantRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::SimpleNetDevice/ReceiveErrorModel/$ns3::BurstErrorModel/BurstStart/$ns3::ConstantRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::SimpleNetDevice/ReceiveErrorModel/$ns3::BurstErrorModel/BurstSize/$ns3::ConstantRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::SpectrumChannel/PropagationLossModel/$ns3::RandomPropagationLossModel/Variable/$ns3::ConstantRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::YansWifiChannel/PropagationLossModel/$ns3::RandomPropagationLossModel/Variable/$ns3::ConstantRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::YansWifiChannel/PropagationDelayModel/$ns3::RandomPropagationDelayModel/Variable/$ns3::ConstantRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Phy/PostReceptionErrorModel/$ns3::RateErrorModel/RanVar/$ns3::ConstantRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Phy/PostReceptionErrorModel/$ns3::BurstErrorModel/BurstStart/$ns3::ConstantRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Phy/PostReceptionErrorModel/$ns3::BurstErrorModel/BurstSize/$ns3::ConstantRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::PointToPointNetDevice/ReceiveErrorModel/$ns3::RateErrorModel/RanVar/$ns3::ConstantRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::PointToPointNetDevice/ReceiveErrorModel/$ns3::BurstErrorModel/BurstStart/$ns3::ConstantRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::PointToPointNetDevice/ReceiveErrorModel/$ns3::BurstErrorModel/BurstSize/$ns3::ConstantRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::CsmaNetDevice/ReceiveErrorModel/$ns3::RateErrorModel/RanVar/$ns3::ConstantRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::CsmaNetDevice/ReceiveErrorModel/$ns3::BurstErrorModel/BurstStart/$ns3::ConstantRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::CsmaNetDevice/ReceiveErrorModel/$ns3::BurstErrorModel/BurstSize/$ns3::ConstantRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::SixLowPanNetDevice/MeshUnderJitter/$ns3::ConstantRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::LrWpanNetDevice/Channel/PropagationLossModel/$ns3::RandomPropagationLossModel/Variable/$ns3::ConstantRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::SpectrumChannel/PropagationLossModel/$ns3::RandomPropagationLossModel/Variable/$ns3::ConstantRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::YansWifiChannel/PropagationLossModel/$ns3::RandomPropagationLossModel/Variable/$ns3::ConstantRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::YansWifiChannel/PropagationDelayModel/$ns3::RandomPropagationDelayModel/Variable/$ns3::ConstantRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/PhyEntities/[i]/PostReceptionErrorModel/$ns3::RateErrorModel/RanVar/$ns3::ConstantRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/PhyEntities/[i]/PostReceptionErrorModel/$ns3::BurstErrorModel/BurstStart/$ns3::ConstantRandomVariable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/PhyEntities/[i]/PostReceptionErrorModel/$ns3::BurstErrorModel/BurstSize/$ns3::ConstantRandomVariable"
"/NodeList/[i]/ApplicationList/[i]/$ns3::OnOffApplication/OnTime/$ns3::ConstantRandomVariable"
"/NodeList/[i]/ApplicationList/[i]/$ns3::OnOffApplication/OffTime/$ns3::ConstantRandomVariable"
"/NodeList/[i]/ApplicationList/[i]/$ns3::DhcpClient/Transactions/$ns3::ConstantRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::GaussMarkovMobilityModel/MeanVelocity/$ns3::ConstantRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::GaussMarkovMobilityModel/MeanDirection/$ns3::ConstantRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::GaussMarkovMobilityModel/MeanPitch/$ns3::ConstantRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomDirection2dMobilityModel/Speed/$ns3::ConstantRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomDirection2dMobilityModel/Pause/$ns3::ConstantRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWalk2dMobilityModel/Direction/$ns3::ConstantRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWalk2dMobilityModel/Speed/$ns3::ConstantRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/Speed/$ns3::ConstantRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/Pause/$ns3::ConstantRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::RandomRectanglePositionAllocator/X/$ns3::ConstantRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::RandomRectanglePositionAllocator/Y/$ns3::ConstantRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::RandomBoxPositionAllocator/X/$ns3::ConstantRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::RandomBoxPositionAllocator/Y/$ns3::ConstantRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::RandomBoxPositionAllocator/Z/$ns3::ConstantRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::RandomDiscPositionAllocator/Theta/$ns3::ConstantRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::RandomDiscPositionAllocator/Rho/$ns3::ConstantRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::OutdoorPositionAllocator/X/$ns3::ConstantRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::OutdoorPositionAllocator/Y/$ns3::ConstantRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::OutdoorPositionAllocator/Z/$ns3::ConstantRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWalk2dOutdoorMobilityModel/Direction/$ns3::ConstantRandomVariable"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWalk2dOutdoorMobilityModel/Speed/$ns3::ConstantRandomVariable"
"/NodeList/[i]/$ns3::ArpL3Protocol/RequestJitter/$ns3::ConstantRandomVariable"
"/NodeList/[i]/$ns3::Icmpv6L4Protocol/SolicitationJitter/$ns3::ConstantRandomVariable"
"/ChannelList/[i]/$ns3::SpectrumChannel/PropagationLossModel/$ns3::RandomPropagationLossModel/Variable/$ns3::ConstantRandomVariable"
"/ChannelList/[i]/$ns3::YansWifiChannel/PropagationLossModel/$ns3::RandomPropagationLossModel/Variable/$ns3::ConstantRandomVariable"
"/ChannelList/[i]/$ns3::YansWifiChannel/PropagationDelayModel/$ns3::RandomPropagationDelayModel/Variable/$ns3::ConstantRandomVariable"
Attributes
Constant: The constant value returned by this RNG stream.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0
Flags: construct write read
Attributes defined in parent class ns3::RandomVariableStream
Stream: The stream number for this RNG stream. -1 means "allocate a stream automatically". Note that if -1 is set, Get will return -1 so that it is not possible to know which value was automatically allocated.
Set with class: ns3::IntegerValue
Underlying type: int64_t -9223372036854775808:9223372036854775807
Initial value: -1
Flags: construct write read
Antithetic: Set this RNG stream to generate antithetic values
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 64 bytes (on a 64-bit architecture).
Definition at line 318 of file random-variable-stream.h.
Constructor & Destructor Documentation
ConstantRandomVariable()
ns3::ConstantRandomVariable::ConstantRandomVariable ()
Creates a constant RNG with the default constant value.
Definition at line 229 of file random-variable-stream.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
GetConstant()
double ns3::ConstantRandomVariable::GetConstant (void) const
Get the constant value returned by this RNG stream.
Returns
The constant value.
Definition at line 236 of file random-variable-stream.cc.
References m_constant, and NS_LOG_FUNCTION.
GetInteger() [1/2]
uint32_t ns3::ConstantRandomVariable::GetInteger (uint32_t constant)
Get the next random value, as an integer equal to the argument.
Parameters
[in] constant The value to return.
Returns
The integer argument.
Definition at line 249 of file random-variable-stream.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::ThreeGppHttpVariables::GetRequestSize().
GetInteger() [2/2]
uint32_t ns3::ConstantRandomVariable::GetInteger (void) virtual
Get the next random value as an integer drawn from the distribution.
Returns
An integer random value.
Implements ns3::RandomVariableStream.
Definition at line 262 of file random-variable-stream.cc.
References GetValue(), m_constant, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::ConstantRandomVariable::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 216 of file random-variable-stream.cc.
References m_constant, ns3::MakeDoubleAccessor(), and ns3::TypeId::SetParent().
GetValue() [1/2]
double ns3::ConstantRandomVariable::GetValue (double constant)
Get the next random value, as a double equal to the argument.
Parameters
[in] constant The value to return.
Returns
The floating point argument.
Definition at line 243 of file random-variable-stream.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::test::RandomVariable::ConstantTestCase::DoRun(), ns3::ThreeGppHttpVariables::GetEmbeddedObjectGenerationDelay(), and ns3::ThreeGppHttpVariables::GetMainObjectGenerationDelay().
GetValue() [2/2]
double ns3::ConstantRandomVariable::GetValue (void) virtual
Get the next random value as a double drawn from the distribution.
Returns
A floating point random value.
Implements ns3::RandomVariableStream.
Definition at line 256 of file random-variable-stream.cc.
References m_constant, and NS_LOG_FUNCTION.
Referenced by GetInteger().
Member Data Documentation
m_constant
double ns3::ConstantRandomVariable::m_constant private
The constant value returned by this RNG stream.
Definition at line 359 of file random-variable-stream.h.
Referenced by GetConstant(), GetInteger(), GetTypeId(), and GetValue().
The documentation for this class was generated from the following files:
src/core/model/random-variable-stream.h
src/core/model/random-variable-stream.cc