ns-3: ns3::BaseStationNetDevice Class Reference
ns3::BaseStationNetDevice Class Reference
WiMAX Models
#include "bs-net-device.h"
Public Types
enum MacPreamble { SHORT_PREAMBLE = 1 , LONG_PREAMBLE }
MacPreamble enumeration.
enum State { BS_STATE_DL_SUB_FRAME , BS_STATE_UL_SUB_FRAME , BS_STATE_TTG , BS_STATE_RTG }
State enumeration.
Public Types inherited from ns3::WimaxNetDevice
enum Direction { DIRECTION_DOWNLINK , DIRECTION_UPLINK }
Direction enumeration.
enum RangingStatus { RANGING_STATUS_EXPIRED , RANGING_STATUS_CONTINUE , RANGING_STATUS_ABORT , RANGING_STATUS_SUCCESS }
RangingStatus enumeration.
typedef void(* TxRxTracedCallback) (Ptr< const Packet > packet, const Mac48Address &mac)
TracedCallback signature for packet and Mac48Address.
Public Types inherited from ns3::NetDevice
typedef void(* LinkChangeTracedCallback) (void)
TracedCallback signature for link changed event.
enum PacketType {
PACKET_HOST = 1 , NS3_PACKET_HOST = PACKET_HOST , PACKET_BROADCAST , NS3_PACKET_BROADCAST = PACKET_BROADCAST ,
PACKET_MULTICAST , NS3_PACKET_MULTICAST = PACKET_MULTICAST , PACKET_OTHERHOST , NS3_PACKET_OTHERHOST = PACKET_OTHERHOST
}
Packet types are used as they are in Linux.
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address &, const Address &, enum PacketType > PromiscReceiveCallback
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address & > ReceiveCallback
Public Member Functions
BaseStationNetDevice (Ptr< Node > node, Ptr< WimaxPhy > phy)
Constructor.
BaseStationNetDevice (Ptr< Node > node, Ptr< WimaxPhy > phy, Ptr< UplinkScheduler > uplinkScheduler, Ptr< BSScheduler > bsScheduler)
Constructor.
BaseStationNetDevice (void)
~BaseStationNetDevice (void)
bool Enqueue (Ptr< Packet > packet, const MacHeaderType &hdrType, Ptr< WimaxConnection > connection)
Enqueue a packet into a connection queue.
Ptr< IpcsClassifier > GetBsClassifier (void) const
Ptr< BSScheduler > GetBSScheduler (void) const
uint8_t GetBwReqOppSize (void) const
Ptr< WimaxConnection > GetConnection (Cid cid)
Time GetDcdInterval (void) const
Time GetDlSubframeStartTime (void) const
Time GetInitialRangingInterval (void) const
Time GetIntervalT8 (void) const
Ptr< BSLinkManager > GetLinkManager (void) const
uint8_t GetMaxInvitedRangRetries (void) const
uint8_t GetMaxRangingCorrectionRetries (void) const
uint32_t GetNrDcdSent (void) const
uint32_t GetNrDlSymbols (void) const
uint32_t GetNrUcdSent (void) const
uint32_t GetNrUlSymbols (void) const
Time GetPsDuration (void) const
uint8_t GetRangingOppNumber (void) const
uint8_t GetRangReqOppSize (void) const
Ptr< BsServiceFlowManager > GetServiceFlowManager (void) const
Ptr< SSManager > GetSSManager (void) const
Time GetSymbolDuration (void) const
Time GetUcdInterval (void) const
Time GetUlSubframeStartTime (void) const
Ptr< UplinkScheduler > GetUplinkScheduler (void) const
void InitBaseStationNetDevice (void)
initializes the BS net device and sets its parameters to the default values
void MarkRangingOppStart (Time rangingOppStartTime)
Mark ranging opp start.
void MarkUplinkAllocations (void)
Mark uplink allocations.
void SetBsClassifier (Ptr< IpcsClassifier > classifier)
void SetBSScheduler (Ptr< BSScheduler > bsSchedule)
void SetBwReqOppSize (uint8_t bwReqOppSize)
void SetDcdInterval (Time dcdInterval)
void SetInitialRangingInterval (Time initialRangInterval)
void SetIntervalT8 (Time interval)
void SetLinkManager (Ptr< BSLinkManager > linkManager)
void SetMaxInvitedRangRetries (uint8_t maxInvitedRangRetries)
void SetMaxRangingCorrectionRetries (uint8_t maxRangCorrectionRetries)
void SetNrDlSymbols (uint32_t dlSymbols)
void SetNrUlSymbols (uint32_t ulSymbols)
void SetRangReqOppSize (uint8_t rangReqOppSize)
void SetServiceFlowManager (Ptr< BsServiceFlowManager >)
Set service flow manager.
void SetSSManager (Ptr< SSManager > ssManager)
void SetUcdInterval (Time ucdInterval)
void SetUplinkScheduler (Ptr< UplinkScheduler > ulScheduler)
void Start (void)
Start device.
void Stop (void)
Stop device.
Public Member Functions inherited from ns3::WimaxNetDevice
WimaxNetDevice (void)
virtual ~WimaxNetDevice (void)
virtual void AddLinkChangeCallback (Callback< void > callback)
Add link change callback function.
void Attach (Ptr< WimaxChannel > channel)
Attach device to channel.
void CreateDefaultConnections (void)
Creates the initial ranging and broadcast connections.
void ForwardDown (Ptr< PacketBurst > burst, WimaxPhy::ModulationType modulationType)
Forward a packet down the stack.
void ForwardUp (Ptr< Packet > packet, const Mac48Address &source, const Mac48Address &dest)
Forward a packet to the next layer above the device.
virtual Address GetAddress (void) const
Get address of the device.
Ptr< BandwidthManager > GetBandwidthManager (void) const
Get the bandwidth manager on the device.
virtual Address GetBroadcast (void) const
Get broadcast address.
Ptr< WimaxConnection > GetBroadcastConnection (void) const
Get the broadcast connection.
Ptr< BurstProfileManager > GetBurstProfileManager (void) const
Get the burst profile manager.
uint64_t GetChannel (uint8_t index) const
Get the channel object by index.
virtual Ptr< Channel > GetChannel (void) const
Get the channel.
Ptr< ConnectionManager > GetConnectionManager (void) const
Get the connection manager of the device.
Dcd GetCurrentDcd (void) const
Get the current DCD.
Ucd GetCurrentUcd (void) const
Get the current UCD.
virtual uint32_t GetIfIndex (void) const
Get interface index.
Ptr< WimaxConnection > GetInitialRangingConnection (void) const
Get the initial ranging connection.
Mac48Address GetMacAddress (void) const
Get the MAC address.
virtual uint16_t GetMtu (void) const
Get MTU of the device.
virtual Address GetMulticast (Ipv4Address multicastGroup) const
Make and return a MAC multicast address using the provided multicast group.
virtual Address GetMulticast (Ipv6Address addr) const
Get the MAC multicast address corresponding to the IPv6 address provided.
virtual Address GetMulticast (void) const
Get multicast address.
virtual std::string GetName (void) const
Get device name.
virtual Ptr< Node > GetNode (void) const
Get node pointer.
uint32_t GetNrFrames (void) const
Get the number of frames.
Ptr< WimaxPhy > GetPhy (void) const
Get the physical layer object.
virtual Ptr< Channel > GetPhyChannel (void) const
Get the channel (this method is redundant with GetChannel())
NetDevice::PromiscReceiveCallback GetPromiscReceiveCallback (void)
Get promiscious receive callback function.
uint16_t GetRtg (void) const
Get receive/transmit transition gap.
uint8_t GetState (void) const
Get the device state.
uint16_t GetTtg (void) const
Get transmission/receive transition gap.
virtual bool IsBridge (void) const
Return true if the net device is acting as a bridge.
virtual bool IsBroadcast (void) const
Check if broadcast enabled.
virtual bool IsLinkUp (void) const
Check if link is up.
virtual bool IsMulticast (void) const
Check if multicast enabled.
virtual bool IsPointToPoint (void) const
Check if device is a point-to-point device.
bool IsPromisc (void)
Check if device is promiscious.
virtual Address MakeMulticastAddress (Ipv4Address multicastGroup) const
Make multicast address.
virtual bool NeedsArp (void) const
Check if device needs ARP.
void NotifyPromiscTrace (Ptr< Packet > p)
Notify promiscious trace of a packet arrival.
virtual bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)
Send function.
virtual bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
Send a packet.
virtual void SetAddress (Address address)
Set address of the device.
void SetBandwidthManager (Ptr< BandwidthManager > bandwidthManager)
Set the bandwidth manager on the device.
void SetBurstProfileManager (Ptr< BurstProfileManager > burstProfileManager)
Set the burst profile manager.
void SetChannel (Ptr< WimaxChannel > wimaxChannel)
Set the channel object.
virtual void SetConnectionManager (Ptr< ConnectionManager > connectionManager)
Set the connection manager of the device.
void SetCurrentDcd (Dcd dcd)
Set the current DCD.
void SetCurrentUcd (Ucd ucd)
Set the current UCD.
virtual void SetIfIndex (const uint32_t index)
Set interface index.
virtual void SetLinkChangeCallback (Callback< void > callback)
Set link change callback function.
void SetMacAddress (Mac48Address address)
Set the MAC address.
virtual bool SetMtu (const uint16_t mtu)
Set MTU value for the device.
virtual void SetName (const std::string name)
Set device name.
virtual void SetNode (Ptr< Node > node)
Set node pointer.
void SetNrFrames (uint32_t nrFrames)
Set the number of frames.
void SetPhy (Ptr< WimaxPhy > phy)
Set the physical layer object.
virtual void SetPromiscReceiveCallback (PromiscReceiveCallback cb)
Set promiscious receive callback function.
virtual void SetReceiveCallback (NetDevice::ReceiveCallback cb)
Set receive callback function.
void SetReceiveCallback (void)
Set receive callback function.
void SetRtg (uint16_t rtg)
Set receive/transmit transition gap.
void SetState (uint8_t state)
Set the device state.
void SetTtg (uint16_t ttg)
Set transmission/receive transition gap.
virtual bool SupportsSendFrom (void) const
Check if device supports the SendFrom method.
Public Member Functions inherited from ns3::NetDevice
virtual ~NetDevice ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::WimaxNetDevice
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::NetDevice
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
Ptr< Packet > CreateDcd (void)
Create DCD.
void CreateDescriptorMessages (bool sendDcd, bool sendUcd)
creates the channel descriptor MAC management messages DCD and UCD
Ptr< Packet > CreateDlMap (void)
Create DL map.
void CreateMapMessages (void)
creates the MAC management messages DL-MAP and UL-MAP
Ptr< Packet > CreateUcd (void)
Create UCD.
Ptr< Packet > CreateUlMap (void)
Create UL map.
virtual void DoDispose (void)
Destructor implementation.
void DoReceive (Ptr< Packet > packet)
Receive packet.
bool DoSend (Ptr< Packet > packet, const Mac48Address &source, const Mac48Address &dest, uint16_t protocolNumber)
Send packet.
void EndDlSubFrame (void)
End DL subframe function.
void EndFrame (void)
End frame function.
void EndUlSubFrame (void)
End UL subframe function.
void MarkUplinkAllocationEnd (Time allocationEndTime, Cid cid, uint8_t uiuc)
Mark uplink allocation end.
void MarkUplinkAllocationStart (Time allocationStartTime)
Mark uplink allocation start.
void RangingOppStart (void)
Ranging opp start.
void SendBursts (void)
Send burst function.
void SetDlBurstProfiles (Dcd *dcd)
Send DL burst profiles.
void SetUlBurstProfiles (Ucd *ucd)
Send UL burst profiles.
void StartDlSubFrame (void)
Start DL subframe function.
void StartFrame (void)
Start frame function.
void StartUlSubFrame (void)
Start UL subframe function.
void UplinkAllocationEnd (Cid cid, uint8_t uiuc)
Uplink allocation end.
void UplinkAllocationStart (void)
Uplink allocation start.
Private Attributes
uint32_t m_allocationStartTime
allocation start time
Ptr< IpcsClassifier > m_bsClassifier
the base station classifier
TracedCallback< Ptr< const Packet > > m_bsPromiscRxTrace
The trace source fired for packets successfully received by the device immediately before being forwarded up to higher layers (at the L2/L3 transition).
TracedCallback< Ptr< const Packet > > m_bsRxDropTrace
The trace source fired when packets coming into the "top" of the device are dropped at the MAC layer during reception.
TracedCallback< Ptr< const Packet > > m_bsRxTrace
The trace source fired for packets successfully received by the device immediately before being forwarded up to higher layers (at the L2/L3 transition).
TracedCallback< Ptr< const Packet > > m_bsTxDropTrace
The trace source fired when packets coming into the "top" of the device are dropped at the MAC layer during transmission.
TracedCallback< Ptr< const Packet > > m_bsTxTrace
The trace source fired when packets come into the "top" of the device at the L3/L2 transition, before being queued for transmission.
uint8_t m_bwReqOppSize
in symbols
CidFactory * m_cidFactory
the CID factory
uint32_t m_dcdConfigChangeCount
DCD config change count.
Time m_dcdInterval
in seconds
Time m_dlSubframeStartTime
DL subframe start time.
uint32_t m_framesSinceLastDcd
frames since last DCD
uint32_t m_framesSinceLastUcd
frames since last UCD
Time m_initialRangInterval
in seconds
Time m_intervalT8
in milliseconds, wait for DSA/DSC Acknowledge timeout
Ptr< BSLinkManager > m_linkManager
the link manager
uint8_t m_maxInvitedRangRetries
maximum invited range retries
uint8_t m_maxRangCorrectionRetries
maximum range correction retries
uint32_t m_nrDcdSent
number DCD sent
uint16_t m_nrDlAllocations
number DL allocations
uint32_t m_nrDlFrames
number DL frames
uint32_t m_nrDlMapSent
number DL map sent
uint32_t m_nrDlSymbols
number of DL symbols
uint16_t m_nrSsRegistered
number SS registered
uint32_t m_nrUcdSent
number UCD sent
uint16_t m_nrUlAllocations
number UL allocations
uint32_t m_nrUlFrames
number UL frames
uint32_t m_nrUlMapSent
number UL map sent
uint32_t m_nrUlSymbols
number of UL symbols
Time m_psDuration
ps duration
uint8_t m_rangingOppNumber
current ranging TO number
uint8_t m_rangReqOppSize
in symbols
Ptr< BSScheduler > m_scheduler
the base station scheduler
Ptr< BsServiceFlowManager > m_serviceFlowManager
the service flow manager
Ptr< SSManager > m_ssManager
the SS manager
Time m_symbolDuration
symbol duration
TracedCallback< Ptr< const Packet >, Mac48Address, Cid > m_traceBSRx
the base station receive trace callback
uint32_t m_ucdConfigChangeCount
UCD config change count.
Time m_ucdInterval
in seconds
uint8_t m_ulAllocationNumber
to see UL burst number
Time m_ulSubframeStartTime
UL subframe start time.
Ptr< UplinkScheduler > m_uplinkScheduler
the uplink scheduler
Additional Inherited Members
Public Attributes inherited from ns3::WimaxNetDevice
TracedCallback< Ptr< const Packet >, const Mac48Address & > m_traceRx
TracedCallback< Ptr< const Packet >, const Mac48Address & > m_traceTx
Static Public Attributes inherited from ns3::WimaxNetDevice
static uint8_t m_direction = ~0
downlink or uplink
static Time m_frameStartTime = Seconds (0)
temp, to determine the frame start time at SS side, shall actually be determined by frame start preamble
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Config Paths
ns3::BaseStationNetDevice is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WimaxNetDevice/$ns3::BaseStationNetDevice"
"/NodeList/[i]/DeviceList/[i]/$ns3::BaseStationNetDevice"
Attributes
BSScheduler: Downlink Scheduler for BS
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::BSScheduler>
Initial value: 0x0
Flags: construct write read
InitialRangInterval: Time between Initial Ranging regions assigned by the BS. Maximum is 2s
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +5e+07ns
Flags: construct write read
DcdInterval: Time between transmission of DCD messages. Maximum value is 10s.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +3e+09ns
Flags: construct write read
UcdInterval: Time between transmission of UCD messages. Maximum value is 10s.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +3e+09ns
Flags: construct write read
IntervalT8: Wait for DSA/DSC Acknowledge timeout. Maximum 300ms.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +5e+07ns
Flags: construct write read
RangReqOppSize: The ranging opportunity size in symbols
Set with class: ns3::UintegerValue
Underlying type: uint8_t 1:256
Initial value: 8
Flags: construct write read
BwReqOppSize: The bandwidth request opportunity size in symbols
Set with class: ns3::UintegerValue
Underlying type: uint8_t 1:256
Initial value: 2
Flags: construct write read
MaxRangCorrectionRetries: Number of retries on contention Ranging Requests
Set with class: ns3::UintegerValue
Underlying type: uint8_t 1:16
Initial value: 16
Flags: construct write read
SSManager: The ss manager attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::SSManager>
Initial value: 0x0
Flags: construct write read
Scheduler: The BS scheduler attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::BSScheduler>
Initial value: 0x0
Flags: construct write read
LinkManager: The link manager attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::BSLinkManager>
Initial value: 0x0
Flags: construct write read
UplinkScheduler: The uplink scheduler attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::UplinkScheduler>
Initial value: 0x0
Flags: construct write read
BsIpcsPacketClassifier: The uplink IP packet classifier attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::IpcsClassifier>
Initial value: 0x0
Flags: construct write read
ServiceFlowManager: The service flow manager attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::ServiceFlowManager>
Initial value: 0x0
Flags: construct write read
Attributes defined in parent class ns3::WimaxNetDevice
Mtu: The MAC-level Maximum Transmission Unit
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:1500
Initial value: 1400
Flags: construct write read
Phy: The PHY layer attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::WimaxPhy>
Initial value: 0x0
Flags: construct write read
Channel: The channel attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::WimaxChannel>
Initial value: 0x0
Flags: construct write read
RTG: receive/transmit transition gap.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:120
Initial value: 0
Flags: construct write read
TTG: transmit/receive transition gap.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:120
Initial value: 0
Flags: construct write read
ConnectionManager: The connection manager attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::ConnectionManager>
Initial value: 0x0
Flags: construct write read
BurstProfileManager: The burst profile manager attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::BurstProfileManager>
Initial value: 0x0
Flags: construct write read
BandwidthManager: The bandwidth manager attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::BandwidthManager>
Initial value: 0x0
Flags: construct write read
InitialRangingConnection: Initial ranging connection
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::WimaxConnection>
Initial value: 0x0
Flags: construct write read
BroadcastConnection: Broadcast connection
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::WimaxConnection>
Initial value: 0x0
Flags: construct write read
TraceSources
BSTx: A packet has been received from higher layers and is being processed in preparation for queueing for transmission.
Callback signature: ns3::Packet::TracedCallback
BSTxDrop: A packet has been dropped in the MAC layer before being queued for transmission.
Callback signature: ns3::Packet::TracedCallback
BSPromiscRx: A packet has been received by this device, has been passed up from the physical layer and is being forwarded up the local protocol stack. This is a promiscuous trace,
Callback signature: ns3::Packet::TracedCallback
BSRx: A packet has been received by this device, has been passed up from the physical layer and is being forwarded up the local protocol stack. This is a non-promiscuous trace,
Callback signature: ns3::Packet::TracedCallback
BSRxDrop: A packet has been dropped in the MAC layer after it has been passed up from the physical layer.
Callback signature: ns3::Packet::TracedCallback
TraceSources defined in parent class ns3::WimaxNetDevice
Rx: Receive trace
Callback signature: ns3::WimaxNetDevice::TxRxTracedCallback
Tx: Transmit trace
Callback signature: ns3::WimaxNetDevice::TxRxTracedCallback
Size of this type is 752 bytes (on a 64-bit architecture).
Definition at line 50 of file bs-net-device.h.
Member Enumeration Documentation
MacPreamble
enum ns3::BaseStationNetDevice::MacPreamble
MacPreamble enumeration.
Enumerator
SHORT_PREAMBLE
LONG_PREAMBLE
Definition at line 63 of file bs-net-device.h.
State
enum ns3::BaseStationNetDevice::State
State enumeration.
Enumerator
BS_STATE_DL_SUB_FRAME
BS_STATE_UL_SUB_FRAME
BS_STATE_TTG
BS_STATE_RTG
Definition at line 54 of file bs-net-device.h.
Constructor & Destructor Documentation
BaseStationNetDevice() [1/3]
ns3::BaseStationNetDevice::BaseStationNetDevice (void)
Definition at line 190 of file bs-net-device.cc.
References InitBaseStationNetDevice().
BaseStationNetDevice() [2/3]
ns3::BaseStationNetDevice::BaseStationNetDevice (Ptr< Node > node, Ptr< WimaxPhy > phy)
Constructor.
Parameters
node the node
phy the wimax phy
Definition at line 237 of file bs-net-device.cc.
References InitBaseStationNetDevice(), ns3::WimaxNetDevice::SetNode(), and ns3::WimaxNetDevice::SetPhy().
BaseStationNetDevice() [3/3]
ns3::BaseStationNetDevice::BaseStationNetDevice (Ptr< Node > node, Ptr< WimaxPhy > phy, Ptr< UplinkScheduler > uplinkScheduler, Ptr< BSScheduler > bsScheduler)
Constructor.
Parameters
node the node
phy the wimax phy
uplinkScheduler uplink scheduler
bsScheduler bs scheduler
Definition at line 244 of file bs-net-device.cc.
References InitBaseStationNetDevice(), m_scheduler, m_uplinkScheduler, ns3::WimaxNetDevice::SetNode(), and ns3::WimaxNetDevice::SetPhy().
~BaseStationNetDevice()
ns3::BaseStationNetDevice::~BaseStationNetDevice (void)
Definition at line 256 of file bs-net-device.cc.
Member Function Documentation
CreateDcd()
Ptr< Packet > ns3::BaseStationNetDevice::CreateDcd (void) private
Create DCD.
Returns
packet
Definition at line 1036 of file bs-net-device.cc.
References ns3::Packet::AddHeader(), ns3::WimaxNetDevice::GetMacAddress(), ns3::WimaxNetDevice::GetNrFrames(), ns3::WimaxNetDevice::GetPhy(), ns3::WimaxNetDevice::GetRtg(), ns3::WimaxNetDevice::GetTtg(), m_dcdConfigChangeCount, ns3::ManagementMessageType::MESSAGE_TYPE_DCD, ns3::OfdmDcdChannelEncodings::SetBaseStationId(), ns3::DcdChannelEncodings::SetBsEirp(), ns3::Dcd::SetChannelEncodings(), ns3::OfdmDcdChannelEncodings::SetChannelNr(), ns3::Dcd::SetConfigurationChangeCount(), ns3::WimaxNetDevice::SetCurrentDcd(), SetDlBurstProfiles(), ns3::DcdChannelEncodings::SetEirxPIrMax(), ns3::OfdmDcdChannelEncodings::SetFrameDurationCode(), ns3::OfdmDcdChannelEncodings::SetFrameNumber(), ns3::DcdChannelEncodings::SetFrequency(), ns3::OfdmDcdChannelEncodings::SetRtg(), and ns3::OfdmDcdChannelEncodings::SetTtg().
Referenced by CreateDescriptorMessages().
CreateDescriptorMessages()
void ns3::BaseStationNetDevice::CreateDescriptorMessages (bool sendDcd, bool sendUcd) private
creates the channel descriptor MAC management messages DCD and UCD
Parameters
sendDcd true if send DCD
sendUcd true if send UCD
Definition at line 925 of file bs-net-device.cc.
References CreateDcd(), CreateUcd(), Enqueue(), ns3::WimaxNetDevice::GetBroadcastConnection(), m_framesSinceLastDcd, m_framesSinceLastUcd, m_nrDcdSent, and m_nrUcdSent.
Referenced by CreateMapMessages().
CreateDlMap()
Ptr< Packet > ns3::BaseStationNetDevice::CreateDlMap (void) private
Create DL map.
Returns
packet
Definition at line 1001 of file bs-net-device.cc.
References ns3::DlMap::AddDlMapElement(), ns3::Packet::AddHeader(), ns3::OfdmDlBurstProfile::DIUC_END_OF_MAP, ns3::WimaxNetDevice::GetMacAddress(), ns3::Cid::InitialRanging(), list, m_dcdConfigChangeCount, m_nrDlAllocations, m_scheduler, ns3::ManagementMessageType::MESSAGE_TYPE_DL_MAP, ns3::DlMap::SetBaseStationId(), ns3::OfdmDlMapIe::SetCid(), ns3::DlMap::SetDcdCount(), ns3::OfdmDlMapIe::SetDiuc(), ns3::OfdmDlMapIe::SetPreamblePresent(), and ns3::OfdmDlMapIe::SetStartTime().
Referenced by CreateMapMessages().
CreateMapMessages()
void ns3::BaseStationNetDevice::CreateMapMessages (void) private
creates the MAC management messages DL-MAP and UL-MAP
Definition at line 881 of file bs-net-device.cc.
References CreateDescriptorMessages(), CreateDlMap(), CreateUlMap(), Enqueue(), ns3::WimaxNetDevice::GetBroadcastConnection(), m_dcdConfigChangeCount, m_nrDlMapSent, m_nrSsRegistered, m_nrUlMapSent, m_ssManager, m_ucdConfigChangeCount, and m_uplinkScheduler.
Referenced by StartDlSubFrame().
CreateUcd()
Ptr< Packet > ns3::BaseStationNetDevice::CreateUcd (void) private
Create UCD.
Returns
packet
Definition at line 1090 of file bs-net-device.cc.
References ns3::Packet::AddHeader(), ns3::WimaxNetDevice::GetPhy(), m_bwReqOppSize, m_rangReqOppSize, m_ucdConfigChangeCount, ns3::ManagementMessageType::MESSAGE_TYPE_UCD, ns3::UcdChannelEncodings::SetBwReqOppSize(), ns3::Ucd::SetChannelEncodings(), ns3::Ucd::SetConfigurationChangeCount(), ns3::WimaxNetDevice::SetCurrentUcd(), ns3::UcdChannelEncodings::SetFrequency(), ns3::Ucd::SetRangingBackoffEnd(), ns3::Ucd::SetRangingBackoffStart(), ns3::UcdChannelEncodings::SetRangReqOppSize(), ns3::Ucd::SetRequestBackoffEnd(), ns3::Ucd::SetRequestBackoffStart(), ns3::OfdmUcdChannelEncodings::SetSbchnlFocContCodes(), ns3::OfdmUcdChannelEncodings::SetSbchnlReqRegionFullParams(), and SetUlBurstProfiles().
Referenced by CreateDescriptorMessages().
CreateUlMap()
Ptr< Packet > ns3::BaseStationNetDevice::CreateUlMap (void) private
Create UL map.
Returns
packet
Definition at line 1064 of file bs-net-device.cc.
References ns3::Packet::AddHeader(), ns3::UlMap::AddUlMapElement(), m_nrUlAllocations, m_rangingOppNumber, m_ucdConfigChangeCount, m_ulAllocationNumber, m_uplinkScheduler, ns3::ManagementMessageType::MESSAGE_TYPE_UL_MAP, ns3::UlMap::SetAllocationStartTime(), and ns3::UlMap::SetUcdCount().
Referenced by CreateMapMessages().
DoDispose()
void ns3::BaseStationNetDevice::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::WimaxNetDevice.
Definition at line 261 of file bs-net-device.cc.
References ns3::WimaxNetDevice::DoDispose(), m_bsClassifier, m_cidFactory, m_linkManager, m_scheduler, m_serviceFlowManager, m_ssManager, and m_uplinkScheduler.
DoReceive()
void ns3::BaseStationNetDevice::DoReceive (Ptr< Packet > packet) private virtual
Receive packet.
Parameters
packet to send
Implements ns3::WimaxNetDevice.
Definition at line 676 of file bs-net-device.cc.
References ns3::Packet::AddAtEnd(), ns3::Packet::AddHeader(), ns3::Simulator::Cancel(), ns3::GenericMacHeader::check_hcs(), ns3::BandwidthRequestHeader::check_hcs(), ns3::Packet::Copy(), ns3::WimaxNetDevice::ForwardUp(), ns3::WimaxNetDevice::GetBandwidthManager(), ns3::GenericMacHeader::GetCid(), ns3::BandwidthRequestHeader::GetCid(), GetConnection(), ns3::WimaxNetDevice::GetConnectionManager(), ns3::FragmentationSubheader::GetFc(), ns3::GenericMacHeader::GetHt(), ns3::BandwidthRequestHeader::GetHt(), GetServiceFlowManager(), ns3::Packet::GetSize(), ns3::ManagementMessageType::GetType(), ns3::GenericMacHeader::GetType(), ns3::MacHeaderType::HEADER_TYPE_BANDWIDTH, ns3::MacHeaderType::HEADER_TYPE_GENERIC, ns3::CidFactory::IsBasic(), ns3::Cid::IsBroadcast(), ns3::Cid::IsInitialRanging(), ns3::CidFactory::IsPrimary(), list, m_bsRxDropTrace, m_bsRxTrace, m_cidFactory, m_linkManager, m_ssManager, m_traceBSRx, ns3::ManagementMessageType::MESSAGE_TYPE_DSA_ACK, ns3::ManagementMessageType::MESSAGE_TYPE_DSA_REQ, ns3::ManagementMessageType::MESSAGE_TYPE_DSA_RSP, ns3::ManagementMessageType::MESSAGE_TYPE_REG_REQ, ns3::ManagementMessageType::MESSAGE_TYPE_REG_RSP, ns3::ManagementMessageType::MESSAGE_TYPE_RNG_REQ, ns3::ManagementMessageType::MESSAGE_TYPE_RNG_RSP, NS_ASSERT_MSG, NS_FATAL_ERROR, NS_LOG_INFO, and ns3::Packet::RemoveHeader().
DoSend()
bool ns3::BaseStationNetDevice::DoSend (Ptr< Packet > packet, const Mac48Address & source, const Mac48Address & dest, uint16_t protocolNumber) private virtual
Send packet.
Parameters
packet to send
source MAC address
dest destination MAC address
protocolNumber protocol number
Returns
true if successful
Implements ns3::WimaxNetDevice.
Definition at line 610 of file bs-net-device.cc.
References Enqueue(), ns3::ServiceFlow::GetConnection(), ns3::ServiceFlow::GetIsEnabled(), GetServiceFlowManager(), ns3::Packet::GetSize(), m_bsClassifier, m_bsTxDropTrace, m_bsTxTrace, NS_LOG_INFO, ns3::ServiceFlow::SF_DIRECTION_DOWN, and ns3::ServiceFlow::SF_TYPE_ALL.
EndDlSubFrame()
void ns3::BaseStationNetDevice::EndDlSubFrame (void) private
End DL subframe function.
Definition at line 573 of file bs-net-device.cc.
References BS_STATE_TTG, ns3::Time::GetSeconds(), ns3::WimaxNetDevice::GetTtg(), m_nrDlFrames, m_psDuration, ns3::Simulator::Schedule(), ns3::Seconds(), ns3::WimaxNetDevice::SetState(), and StartUlSubFrame().
Referenced by StartDlSubFrame().
EndFrame()
void ns3::BaseStationNetDevice::EndFrame (void) private
End frame function.
Definition at line 604 of file bs-net-device.cc.
References StartFrame().
Referenced by EndUlSubFrame().
EndUlSubFrame()
void ns3::BaseStationNetDevice::EndUlSubFrame (void) private
End UL subframe function.
Definition at line 596 of file bs-net-device.cc.
References BS_STATE_RTG, EndFrame(), ns3::WimaxNetDevice::GetRtg(), ns3::Time::GetSeconds(), m_nrUlFrames, m_psDuration, ns3::Simulator::Schedule(), ns3::Seconds(), and ns3::WimaxNetDevice::SetState().
Referenced by StartUlSubFrame().
Enqueue()
bool ns3::BaseStationNetDevice::Enqueue (Ptr< Packet > packet, const MacHeaderType & hdrType, Ptr< WimaxConnection > connection) virtual
Enqueue a packet into a connection queue.
Parameters
packet the packet to be enqueued
hdrType the mac header type to be appended to the packet
connection the connection to be used
Returns
true if successful
Implements ns3::WimaxNetDevice.
Definition at line 662 of file bs-net-device.cc.
References ns3::GenericMacHeader::GetSerializedSize(), ns3::Packet::GetSize(), NS_ASSERT_MSG, ns3::GenericMacHeader::SetCid(), and ns3::GenericMacHeader::SetLen().
Referenced by CreateDescriptorMessages(), CreateMapMessages(), and DoSend().
GetBsClassifier()
Ptr< IpcsClassifier > ns3::BaseStationNetDevice::GetBsClassifier (void) const
Returns
a pointer to the classifier installed on the BS
Definition at line 285 of file bs-net-device.cc.
References m_bsClassifier.
Referenced by GetTypeId().
GetBSScheduler()
Ptr< BSScheduler > ns3::BaseStationNetDevice::GetBSScheduler (void) const
Returns
The BS scheduler installed on the BS
Definition at line 494 of file bs-net-device.cc.
References m_scheduler.
Referenced by GetTypeId().
GetBwReqOppSize()
uint8_t ns3::BaseStationNetDevice::GetBwReqOppSize (void) const
Returns
The bandwidth request opportunity size in symbols
Definition at line 381 of file bs-net-device.cc.
References m_bwReqOppSize.
Referenced by GetTypeId().
GetConnection()
Ptr< WimaxConnection > ns3::BaseStationNetDevice::GetConnection (Cid cid)
Parameters
cid connection ID
Returns
a pointer to the connection
Definition at line 1150 of file bs-net-device.cc.
References ns3::WimaxNetDevice::GetBroadcastConnection(), ns3::WimaxNetDevice::GetConnectionManager(), ns3::WimaxNetDevice::GetInitialRangingConnection(), ns3::Cid::IsBroadcast(), ns3::Cid::IsInitialRanging(), and NS_ASSERT_MSG.
Referenced by DoReceive().
GetDcdInterval()
Time ns3::BaseStationNetDevice::GetDcdInterval (void) const
Returns
the Time between transmission of DCD messages
Definition at line 309 of file bs-net-device.cc.
References m_dcdInterval.
Referenced by GetTypeId().
GetDlSubframeStartTime()
Time ns3::BaseStationNetDevice::GetDlSubframeStartTime (void) const
Returns
the DL subframe start time
Definition at line 423 of file bs-net-device.cc.
References m_dlSubframeStartTime.
GetInitialRangingInterval()
Time ns3::BaseStationNetDevice::GetInitialRangingInterval (void) const
Returns
Time between initial ranging regions assigned by the BS
Definition at line 297 of file bs-net-device.cc.
References m_initialRangInterval.
Referenced by GetTypeId().
GetIntervalT8()
Time ns3::BaseStationNetDevice::GetIntervalT8 (void) const
Returns
the Wait for DSA/DSC Acknowledge timeout
Definition at line 333 of file bs-net-device.cc.
References m_intervalT8.
Referenced by GetTypeId().
GetLinkManager()
Ptr< BSLinkManager > ns3::BaseStationNetDevice::GetLinkManager (void) const
Returns
a pointer to the link manager installed on the BS
Definition at line 477 of file bs-net-device.cc.
References m_linkManager.
Referenced by GetTypeId().
GetMaxInvitedRangRetries()
uint8_t ns3::BaseStationNetDevice::GetMaxInvitedRangRetries (void) const
Returns
the number of retries on contention Ranging
Definition at line 357 of file bs-net-device.cc.
References m_maxInvitedRangRetries.
GetMaxRangingCorrectionRetries()
uint8_t ns3::BaseStationNetDevice::GetMaxRangingCorrectionRetries (void) const
Returns
the number of retries on contention Ranging Requests
Definition at line 345 of file bs-net-device.cc.
References m_maxRangCorrectionRetries.
Referenced by GetTypeId().
GetNrDcdSent()
uint32_t ns3::BaseStationNetDevice::GetNrDcdSent (void) const
Returns
the number dcd messages already sent
Definition at line 411 of file bs-net-device.cc.
References m_nrDcdSent.
GetNrDlSymbols()
uint32_t ns3::BaseStationNetDevice::GetNrDlSymbols (void) const
Returns
the number of symbols in the downlink sub-frame
Definition at line 393 of file bs-net-device.cc.
References m_nrDlSymbols.
GetNrUcdSent()
uint32_t ns3::BaseStationNetDevice::GetNrUcdSent (void) const
Returns
the number ucd messages already sent
Definition at line 417 of file bs-net-device.cc.
References m_nrUcdSent.
GetNrUlSymbols()
uint32_t ns3::BaseStationNetDevice::GetNrUlSymbols (void) const
Returns
the number of symbols in the uplink sub-frame
Definition at line 405 of file bs-net-device.cc.
References m_nrUlSymbols.
GetPsDuration()
Time ns3::BaseStationNetDevice::GetPsDuration (void) const
Returns
PS duration
Definition at line 500 of file bs-net-device.cc.
References m_psDuration.
GetRangingOppNumber()
uint8_t ns3::BaseStationNetDevice::GetRangingOppNumber (void) const
Returns
the ranging opp number
Definition at line 435 of file bs-net-device.cc.
References m_rangingOppNumber.
GetRangReqOppSize()
uint8_t ns3::BaseStationNetDevice::GetRangReqOppSize (void) const
Returns
The ranging opportunity size in symbols
Definition at line 369 of file bs-net-device.cc.
References m_rangReqOppSize.
Referenced by GetTypeId().
GetServiceFlowManager()
Ptr< BsServiceFlowManager > ns3::BaseStationNetDevice::GetServiceFlowManager (void) const
Returns
service flow manager
Definition at line 453 of file bs-net-device.cc.
References m_serviceFlowManager.
Referenced by DoReceive(), DoSend(), and GetTypeId().
GetSSManager()
Ptr< SSManager > ns3::BaseStationNetDevice::GetSSManager (void) const
Returns
a pointer to the SS manager
Definition at line 441 of file bs-net-device.cc.
References m_ssManager.
Referenced by GetTypeId().
GetSymbolDuration()
Time ns3::BaseStationNetDevice::GetSymbolDuration (void) const
Returns
symbol duration
Definition at line 506 of file bs-net-device.cc.
References m_symbolDuration.
GetTypeId()
TypeId ns3::BaseStationNetDevice::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 54 of file bs-net-device.cc.
References GetBsClassifier(), GetBSScheduler(), GetBwReqOppSize(), GetDcdInterval(), GetInitialRangingInterval(), GetIntervalT8(), GetLinkManager(), GetMaxRangingCorrectionRetries(), GetRangReqOppSize(), GetServiceFlowManager(), GetSSManager(), GetUcdInterval(), GetUplinkScheduler(), m_bsPromiscRxTrace, m_bsRxDropTrace, m_bsRxTrace, m_bsTxDropTrace, m_bsTxTrace, m_scheduler, ns3::MakePointerAccessor(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), ns3::Seconds(), SetBsClassifier(), SetBSScheduler(), SetBwReqOppSize(), SetDcdInterval(), SetInitialRangingInterval(), SetIntervalT8(), SetLinkManager(), SetMaxRangingCorrectionRetries(), ns3::TypeId::SetParent(), SetRangReqOppSize(), SetServiceFlowManager(), SetSSManager(), SetUcdInterval(), and SetUplinkScheduler().
GetUcdInterval()
Time ns3::BaseStationNetDevice::GetUcdInterval (void) const
Returns
Time between transmission of UCD messages
Definition at line 321 of file bs-net-device.cc.
References m_ucdInterval.
Referenced by GetTypeId().
GetUlSubframeStartTime()
Time ns3::BaseStationNetDevice::GetUlSubframeStartTime (void) const
Returns
the UL subframe start time
Definition at line 429 of file bs-net-device.cc.
References m_ulSubframeStartTime.
GetUplinkScheduler()
Ptr< UplinkScheduler > ns3::BaseStationNetDevice::GetUplinkScheduler (void) const
Returns
a pointer to the uplink scheduler installed on the device
Definition at line 465 of file bs-net-device.cc.
References m_uplinkScheduler.
Referenced by GetTypeId().
InitBaseStationNetDevice()
void ns3::BaseStationNetDevice::InitBaseStationNetDevice (void)
initializes the BS net device and sets its parameters to the default values
Definition at line 196 of file bs-net-device.cc.
References m_allocationStartTime, m_bsClassifier, m_bwReqOppSize, m_cidFactory, m_dcdConfigChangeCount, m_dcdInterval, m_dlSubframeStartTime, m_framesSinceLastDcd, m_framesSinceLastUcd, m_initialRangInterval, m_intervalT8, m_linkManager, m_maxInvitedRangRetries, m_maxRangCorrectionRetries, m_nrDcdSent, m_nrDlAllocations, m_nrDlFrames, m_nrDlMapSent, m_nrDlSymbols, m_nrSsRegistered, m_nrUcdSent, m_nrUlAllocations, m_nrUlFrames, m_nrUlMapSent, m_nrUlSymbols, m_psDuration, m_rangingOppNumber, m_rangReqOppSize, m_serviceFlowManager, m_ssManager, m_symbolDuration, m_ucdConfigChangeCount, m_ucdInterval, m_ulAllocationNumber, m_ulSubframeStartTime, ns3::MilliSeconds(), and ns3::Seconds().
Referenced by BaseStationNetDevice().
MarkRangingOppStart()
void ns3::BaseStationNetDevice::MarkRangingOppStart (Time rangingOppStartTime)
Mark ranging opp start.
Parameters
rangingOppStartTime start time
Definition at line 1225 of file bs-net-device.cc.
References RangingOppStart(), and ns3::Simulator::Schedule().
MarkUplinkAllocationEnd()
void ns3::BaseStationNetDevice::MarkUplinkAllocationEnd (Time allocationEndTime, Cid cid, uint8_t uiuc) private
Mark uplink allocation end.
Parameters
allocationEndTime allocation end time
cid connection ID
uiuc
Definition at line 1198 of file bs-net-device.cc.
References ns3::Simulator::Schedule(), and UplinkAllocationEnd().
Referenced by MarkUplinkAllocations().
MarkUplinkAllocations()
void ns3::BaseStationNetDevice::MarkUplinkAllocations (void)
Mark uplink allocations.
Definition at line 1171 of file bs-net-device.cc.
References ns3::OfdmUlMapIe::GetCid(), ns3::OfdmUlMapIe::GetDuration(), ns3::OfdmUlMapIe::GetStartTime(), ns3::OfdmUlMapIe::GetUiuc(), m_symbolDuration, m_uplinkScheduler, MarkUplinkAllocationEnd(), MarkUplinkAllocationStart(), and ns3::OfdmUlBurstProfile::UIUC_END_OF_MAP.
Referenced by StartUlSubFrame().
MarkUplinkAllocationStart()
void ns3::BaseStationNetDevice::MarkUplinkAllocationStart (Time allocationStartTime) private
Mark uplink allocation start.
Parameters
allocationStartTime allocation start time
Definition at line 1192 of file bs-net-device.cc.
References ns3::Simulator::Schedule(), and UplinkAllocationStart().
Referenced by MarkUplinkAllocations().
RangingOppStart()
void ns3::BaseStationNetDevice::RangingOppStart (void) private
Ranging opp start.
Definition at line 1231 of file bs-net-device.cc.
References m_rangingOppNumber, ns3::Simulator::Now(), NS_LOG_DEBUG, and ns3::Time::S.
Referenced by MarkRangingOppStart().
SendBursts()
void ns3::BaseStationNetDevice::SendBursts (void) private
Send burst function.
Definition at line 959 of file bs-net-device.cc.
References ns3::WimaxNetDevice::DIRECTION_DOWNLINK, ns3::WimaxNetDevice::ForwardDown(), ns3::WimaxNetDevice::GetBroadcastConnection(), ns3::WimaxNetDevice::GetBurstProfileManager(), ns3::OfdmDlMapIe::GetCid(), ns3::OfdmDlMapIe::GetDiuc(), ns3::WimaxNetDevice::GetInitialRangingConnection(), ns3::WimaxNetDevice::GetPhy(), m_scheduler, m_serviceFlowManager, ns3::WimaxPhy::MODULATION_TYPE_BPSK_12, ns3::Simulator::Schedule(), and ns3::Seconds().
Referenced by StartDlSubFrame().
SetBsClassifier()
void ns3::BaseStationNetDevice::SetBsClassifier (Ptr< IpcsClassifier > classifier)
Parameters
classifier a classifier to be installed on the BS
Definition at line 279 of file bs-net-device.cc.
References m_bsClassifier.
Referenced by GetTypeId().
SetBSScheduler()
void ns3::BaseStationNetDevice::SetBSScheduler (Ptr< BSScheduler > bsSchedule)
Parameters
bsSchedule the downlink scheduler to be installed on the BS
Definition at line 489 of file bs-net-device.cc.
References m_scheduler.
Referenced by GetTypeId().
SetBwReqOppSize()
void ns3::BaseStationNetDevice::SetBwReqOppSize (uint8_t bwReqOppSize)
Parameters
bwReqOppSize The bandwidth request opportunity size in symbols
Definition at line 375 of file bs-net-device.cc.
References m_bwReqOppSize.
Referenced by GetTypeId().
SetDcdInterval()
void ns3::BaseStationNetDevice::SetDcdInterval (Time dcdInterval)
Parameters
dcdInterval Time between transmission of DCD messages
Definition at line 303 of file bs-net-device.cc.
References m_dcdInterval.
Referenced by GetTypeId().
SetDlBurstProfiles()
void ns3::BaseStationNetDevice::SetDlBurstProfiles (Dcd * dcd) private
Send DL burst profiles.
Parameters
dcd burst profile
Definition at line 1120 of file bs-net-device.cc.
References ns3::Dcd::AddDlBurstProfile(), ns3::WimaxNetDevice::GetBurstProfileManager(), ns3::OfdmDlBurstProfile::SetDiuc(), ns3::OfdmDlBurstProfile::SetFecCodeType(), ns3::OfdmDlBurstProfile::SetLength(), and ns3::OfdmDlBurstProfile::SetType().
Referenced by CreateDcd().
SetInitialRangingInterval()
void ns3::BaseStationNetDevice::SetInitialRangingInterval (Time initialRangInterval)
Parameters
initialRangInterval Time between initial ranging regions assigned by the BS
Definition at line 291 of file bs-net-device.cc.
References m_initialRangInterval.
Referenced by GetTypeId().
SetIntervalT8()
void ns3::BaseStationNetDevice::SetIntervalT8 (Time interval)
Parameters
interval the Wait for DSA/DSC Acknowledge timeout
Definition at line 327 of file bs-net-device.cc.
References m_intervalT8.
Referenced by GetTypeId().
SetLinkManager()
void ns3::BaseStationNetDevice::SetLinkManager (Ptr< BSLinkManager > linkManager)
Parameters
linkManager The link manager installed on the BS
Definition at line 483 of file bs-net-device.cc.
References m_linkManager.
Referenced by GetTypeId().
SetMaxInvitedRangRetries()
void ns3::BaseStationNetDevice::SetMaxInvitedRangRetries (uint8_t maxInvitedRangRetries)
Parameters
maxInvitedRangRetries the number of retries on contention Ranging
Definition at line 351 of file bs-net-device.cc.
References m_maxInvitedRangRetries.
SetMaxRangingCorrectionRetries()
void ns3::BaseStationNetDevice::SetMaxRangingCorrectionRetries (uint8_t maxRangCorrectionRetries)
Parameters
maxRangCorrectionRetries the number of retries on contention Ranging Requests
Definition at line 339 of file bs-net-device.cc.
References m_maxRangCorrectionRetries.
Referenced by GetTypeId().
SetNrDlSymbols()
void ns3::BaseStationNetDevice::SetNrDlSymbols (uint32_t dlSymbols)
Parameters
dlSymbols the number of symbols in the downlink sub-frame
Definition at line 387 of file bs-net-device.cc.
References m_nrDlSymbols.
Referenced by StartFrame().
SetNrUlSymbols()
void ns3::BaseStationNetDevice::SetNrUlSymbols (uint32_t ulSymbols)
Parameters
ulSymbols the number of symbols in the uplink sub-frame
Definition at line 399 of file bs-net-device.cc.
References m_nrUlSymbols.
Referenced by StartFrame().
SetRangReqOppSize()
void ns3::BaseStationNetDevice::SetRangReqOppSize (uint8_t rangReqOppSize)
Parameters
rangReqOppSize The ranging opportunity size in symbols
Definition at line 363 of file bs-net-device.cc.
References m_rangReqOppSize.
Referenced by GetTypeId().
SetServiceFlowManager()
void ns3::BaseStationNetDevice::SetServiceFlowManager (Ptr< BsServiceFlowManager > sfm)
Set service flow manager.
Definition at line 459 of file bs-net-device.cc.
References m_serviceFlowManager.
Referenced by GetTypeId().
SetSSManager()
void ns3::BaseStationNetDevice::SetSSManager (Ptr< SSManager > ssManager)
Parameters
ssManager the SS manager to be installed on the BS
Definition at line 447 of file bs-net-device.cc.
References m_ssManager.
Referenced by GetTypeId().
SetUcdInterval()
void ns3::BaseStationNetDevice::SetUcdInterval (Time ucdInterval)
Parameters
ucdInterval the Time between transmission of UCD messages
Definition at line 315 of file bs-net-device.cc.
References m_ucdInterval.
Referenced by GetTypeId().
SetUlBurstProfiles()
void ns3::BaseStationNetDevice::SetUlBurstProfiles (Ucd * ucd) private
Send UL burst profiles.
Parameters
ucd burst profile
Definition at line 1134 of file bs-net-device.cc.
References ns3::Ucd::AddUlBurstProfile(), ns3::WimaxNetDevice::GetBurstProfileManager(), ns3::OfdmUlBurstProfile::SetFecCodeType(), ns3::OfdmUlBurstProfile::SetLength(), ns3::OfdmUlBurstProfile::SetType(), and ns3::OfdmUlBurstProfile::SetUiuc().
Referenced by CreateUcd().
SetUplinkScheduler()
void ns3::BaseStationNetDevice::SetUplinkScheduler (Ptr< UplinkScheduler > ulScheduler)
Parameters
ulScheduler the ulScheduler to be isnstalled on the BS
Definition at line 471 of file bs-net-device.cc.
References m_uplinkScheduler.
Referenced by GetTypeId().
Start()
void ns3::BaseStationNetDevice::Start (void) virtual
Start device.
Implements ns3::WimaxNetDevice.
Definition at line 512 of file bs-net-device.cc.
References ns3::WimaxNetDevice::CreateDefaultConnections(), ns3::WimaxNetDevice::GetBandwidthManager(), ns3::WimaxNetDevice::GetConnectionManager(), ns3::WimaxNetDevice::GetPhy(), ns3::WimaxNetDevice::GetRtg(), ns3::WimaxNetDevice::GetTtg(), m_bwReqOppSize, m_cidFactory, m_linkManager, m_psDuration, m_symbolDuration, m_uplinkScheduler, ns3::Simulator::ScheduleNow(), ns3::WimaxNetDevice::SetReceiveCallback(), ns3::WimaxNetDevice::SetRtg(), ns3::WimaxNetDevice::SetTtg(), and StartFrame().
StartDlSubFrame()
void ns3::BaseStationNetDevice::StartDlSubFrame (void) private
Start DL subframe function.
Definition at line 554 of file bs-net-device.cc.
References ns3::Time::As(), BS_STATE_DL_SUB_FRAME, CreateMapMessages(), ns3::WimaxNetDevice::DIRECTION_DOWNLINK, EndDlSubFrame(), ns3::WimaxNetDevice::GetNrFrames(), ns3::Time::GetSeconds(), ns3::WimaxNetDevice::m_direction, m_dlSubframeStartTime, ns3::WimaxNetDevice::m_frameStartTime, m_nrDlSymbols, m_scheduler, m_symbolDuration, m_uplinkScheduler, ns3::Simulator::Now(), NS_LOG_DEBUG, ns3::Time::S, ns3::Simulator::Schedule(), ns3::Seconds(), SendBursts(), ns3::WimaxNetDevice::SetNrFrames(), and ns3::WimaxNetDevice::SetState().
Referenced by StartFrame().
StartFrame()
void ns3::BaseStationNetDevice::StartFrame (void) private
Start frame function.
Definition at line 539 of file bs-net-device.cc.
References ns3::WimaxNetDevice::GetNrFrames(), ns3::WimaxNetDevice::GetPhy(), ns3::WimaxNetDevice::GetRtg(), ns3::Time::GetSeconds(), ns3::WimaxNetDevice::GetTtg(), ns3::WimaxNetDevice::m_frameStartTime, m_psDuration, m_symbolDuration, ns3::Simulator::Now(), NS_LOG_INFO, SetNrDlSymbols(), SetNrUlSymbols(), and StartDlSubFrame().
Referenced by EndFrame(), and Start().
StartUlSubFrame()
void ns3::BaseStationNetDevice::StartUlSubFrame (void) private
Start UL subframe function.
Definition at line 581 of file bs-net-device.cc.
References ns3::Time::As(), BS_STATE_UL_SUB_FRAME, ns3::WimaxNetDevice::DIRECTION_UPLINK, EndUlSubFrame(), ns3::Time::GetSeconds(), ns3::WimaxNetDevice::m_direction, m_nrUlSymbols, m_symbolDuration, m_ulSubframeStartTime, MarkUplinkAllocations(), ns3::Simulator::Now(), NS_LOG_INFO, ns3::Time::S, ns3::Simulator::Schedule(), ns3::Seconds(), and ns3::WimaxNetDevice::SetState().
Referenced by EndDlSubFrame().
Stop()
void ns3::BaseStationNetDevice::Stop (void) virtual
Stop device.
Implements ns3::WimaxNetDevice.
Definition at line 534 of file bs-net-device.cc.
UplinkAllocationEnd()
void ns3::BaseStationNetDevice::UplinkAllocationEnd (Cid cid, uint8_t uiuc) private
Uplink allocation end.
Parameters
cid connection ID
uiuc
Definition at line 1214 of file bs-net-device.cc.
References ns3::CidFactory::IsBasic(), m_cidFactory, m_linkManager, m_ulAllocationNumber, ns3::Simulator::Now(), NS_LOG_DEBUG, and ns3::Time::S.
Referenced by MarkUplinkAllocationEnd().
UplinkAllocationStart()
void ns3::BaseStationNetDevice::UplinkAllocationStart (void) private
Uplink allocation start.
Definition at line 1204 of file bs-net-device.cc.
References m_ulAllocationNumber, ns3::Simulator::Now(), NS_LOG_DEBUG, and ns3::Time::S.
Referenced by MarkUplinkAllocationStart().
Member Data Documentation
m_allocationStartTime
uint32_t ns3::BaseStationNetDevice::m_allocationStartTime private
allocation start time
Definition at line 445 of file bs-net-device.h.
Referenced by InitBaseStationNetDevice().
m_bsClassifier
Ptr<IpcsClassifier> ns3::BaseStationNetDevice::m_bsClassifier private
the base station classifier
Definition at line 451 of file bs-net-device.h.
Referenced by DoDispose(), DoSend(), GetBsClassifier(), InitBaseStationNetDevice(), and SetBsClassifier().
m_bsPromiscRxTrace
TracedCallback<Ptr<const Packet> > ns3::BaseStationNetDevice::m_bsPromiscRxTrace private
The trace source fired for packets successfully received by the device immediately before being forwarded up to higher layers (at the L2/L3 transition).
This is a promiscuous trace.
See also
class CallBackTraceSource base station promiscious receive trace Callbacks
Definition at line 482 of file bs-net-device.h.
Referenced by GetTypeId().
m_bsRxDropTrace
TracedCallback<Ptr<const Packet> > ns3::BaseStationNetDevice::m_bsRxDropTrace private
The trace source fired when packets coming into the "top" of the device are dropped at the MAC layer during reception.
See also
class CallBackTraceSource base station receive drop trace Callbacks
Definition at line 499 of file bs-net-device.h.
Referenced by DoReceive(), and GetTypeId().
m_bsRxTrace
TracedCallback<Ptr<const Packet> > ns3::BaseStationNetDevice::m_bsRxTrace private
The trace source fired for packets successfully received by the device immediately before being forwarded up to higher layers (at the L2/L3 transition).
This is a non- promiscuous trace.
See also
class CallBackTraceSource base station receive trace Callbacks
Definition at line 491 of file bs-net-device.h.
Referenced by DoReceive(), and GetTypeId().
m_bsTxDropTrace
TracedCallback<Ptr<const Packet> > ns3::BaseStationNetDevice::m_bsTxDropTrace private
The trace source fired when packets coming into the "top" of the device are dropped at the MAC layer during transmission.
See also
class CallBackTraceSource base station transmit drop trace Callbacks
Definition at line 473 of file bs-net-device.h.
Referenced by DoSend(), and GetTypeId().
m_bsTxTrace
TracedCallback<Ptr<const Packet> > ns3::BaseStationNetDevice::m_bsTxTrace private
The trace source fired when packets come into the "top" of the device at the L3/L2 transition, before being queued for transmission.
See also
class CallBackTraceSource the base station transmit trace Callbacks
Definition at line 465 of file bs-net-device.h.
Referenced by DoSend(), and GetTypeId().
m_bwReqOppSize
uint8_t ns3::BaseStationNetDevice::m_bwReqOppSize private
in symbols
Definition at line 409 of file bs-net-device.h.
Referenced by CreateUcd(), GetBwReqOppSize(), InitBaseStationNetDevice(), SetBwReqOppSize(), and Start().
m_cidFactory
CidFactory* ns3::BaseStationNetDevice::m_cidFactory private
the CID factory
Definition at line 443 of file bs-net-device.h.
Referenced by DoDispose(), DoReceive(), InitBaseStationNetDevice(), Start(), and UplinkAllocationEnd().
m_dcdConfigChangeCount
uint32_t ns3::BaseStationNetDevice::m_dcdConfigChangeCount private
DCD config change count.
Definition at line 421 of file bs-net-device.h.
Referenced by CreateDcd(), CreateDlMap(), CreateMapMessages(), and InitBaseStationNetDevice().
m_dcdInterval
Time ns3::BaseStationNetDevice::m_dcdInterval private
in seconds
Definition at line 402 of file bs-net-device.h.
Referenced by GetDcdInterval(), InitBaseStationNetDevice(), and SetDcdInterval().
m_dlSubframeStartTime
Time ns3::BaseStationNetDevice::m_dlSubframeStartTime private
DL subframe start time.
Definition at line 437 of file bs-net-device.h.
Referenced by GetDlSubframeStartTime(), InitBaseStationNetDevice(), and StartDlSubFrame().
m_framesSinceLastDcd
uint32_t ns3::BaseStationNetDevice::m_framesSinceLastDcd private
frames since last DCD
Definition at line 424 of file bs-net-device.h.
Referenced by CreateDescriptorMessages(), and InitBaseStationNetDevice().
m_framesSinceLastUcd
uint32_t ns3::BaseStationNetDevice::m_framesSinceLastUcd private
frames since last UCD
Definition at line 425 of file bs-net-device.h.
Referenced by CreateDescriptorMessages(), and InitBaseStationNetDevice().
m_initialRangInterval
Time ns3::BaseStationNetDevice::m_initialRangInterval private
in seconds
Definition at line 401 of file bs-net-device.h.
Referenced by GetInitialRangingInterval(), InitBaseStationNetDevice(), and SetInitialRangingInterval().
m_intervalT8
Time ns3::BaseStationNetDevice::m_intervalT8 private
in milliseconds, wait for DSA/DSC Acknowledge timeout
Definition at line 404 of file bs-net-device.h.
Referenced by GetIntervalT8(), InitBaseStationNetDevice(), and SetIntervalT8().
m_linkManager
Ptr<BSLinkManager> ns3::BaseStationNetDevice::m_linkManager private
the link manager
Definition at line 450 of file bs-net-device.h.
Referenced by DoDispose(), DoReceive(), GetLinkManager(), InitBaseStationNetDevice(), SetLinkManager(), Start(), and UplinkAllocationEnd().
m_maxInvitedRangRetries
uint8_t ns3::BaseStationNetDevice::m_maxInvitedRangRetries private
maximum invited range retries
Definition at line 407 of file bs-net-device.h.
Referenced by GetMaxInvitedRangRetries(), InitBaseStationNetDevice(), and SetMaxInvitedRangRetries().
m_maxRangCorrectionRetries
uint8_t ns3::BaseStationNetDevice::m_maxRangCorrectionRetries private
maximum range correction retries
Definition at line 406 of file bs-net-device.h.
Referenced by GetMaxRangingCorrectionRetries(), InitBaseStationNetDevice(), and SetMaxRangingCorrectionRetries().
m_nrDcdSent
uint32_t ns3::BaseStationNetDevice::m_nrDcdSent private
number DCD sent
Definition at line 418 of file bs-net-device.h.
Referenced by CreateDescriptorMessages(), GetNrDcdSent(), and InitBaseStationNetDevice().
m_nrDlAllocations
uint16_t ns3::BaseStationNetDevice::m_nrDlAllocations private
number DL allocations
Definition at line 434 of file bs-net-device.h.
Referenced by CreateDlMap(), and InitBaseStationNetDevice().
m_nrDlFrames
uint32_t ns3::BaseStationNetDevice::m_nrDlFrames private
number DL frames
Definition at line 428 of file bs-net-device.h.
Referenced by EndDlSubFrame(), and InitBaseStationNetDevice().
m_nrDlMapSent
uint32_t ns3::BaseStationNetDevice::m_nrDlMapSent private
number DL map sent
Definition at line 415 of file bs-net-device.h.
Referenced by CreateMapMessages(), and InitBaseStationNetDevice().
m_nrDlSymbols
uint32_t ns3::BaseStationNetDevice::m_nrDlSymbols private
number of DL symbols
Definition at line 411 of file bs-net-device.h.
Referenced by GetNrDlSymbols(), InitBaseStationNetDevice(), SetNrDlSymbols(), and StartDlSubFrame().
m_nrSsRegistered
uint16_t ns3::BaseStationNetDevice::m_nrSsRegistered private
number SS registered
Definition at line 432 of file bs-net-device.h.
Referenced by CreateMapMessages(), and InitBaseStationNetDevice().
m_nrUcdSent
uint32_t ns3::BaseStationNetDevice::m_nrUcdSent private
number UCD sent
Definition at line 419 of file bs-net-device.h.
Referenced by CreateDescriptorMessages(), GetNrUcdSent(), and InitBaseStationNetDevice().
m_nrUlAllocations
uint16_t ns3::BaseStationNetDevice::m_nrUlAllocations private
number UL allocations
Definition at line 435 of file bs-net-device.h.
Referenced by CreateUlMap(), and InitBaseStationNetDevice().
m_nrUlFrames
uint32_t ns3::BaseStationNetDevice::m_nrUlFrames private
number UL frames
Definition at line 429 of file bs-net-device.h.
Referenced by EndUlSubFrame(), and InitBaseStationNetDevice().
m_nrUlMapSent
uint32_t ns3::BaseStationNetDevice::m_nrUlMapSent private
number UL map sent
Definition at line 416 of file bs-net-device.h.
Referenced by CreateMapMessages(), and InitBaseStationNetDevice().
m_nrUlSymbols
uint32_t ns3::BaseStationNetDevice::m_nrUlSymbols private
number of UL symbols
Definition at line 412 of file bs-net-device.h.
Referenced by GetNrUlSymbols(), InitBaseStationNetDevice(), SetNrUlSymbols(), and StartUlSubFrame().
m_psDuration
Time ns3::BaseStationNetDevice::m_psDuration private
ps duration
Definition at line 454 of file bs-net-device.h.
Referenced by EndDlSubFrame(), EndUlSubFrame(), GetPsDuration(), InitBaseStationNetDevice(), Start(), and StartFrame().
m_rangingOppNumber
uint8_t ns3::BaseStationNetDevice::m_rangingOppNumber private
current ranging TO number
Definition at line 441 of file bs-net-device.h.
Referenced by CreateUlMap(), GetRangingOppNumber(), InitBaseStationNetDevice(), and RangingOppStart().
m_rangReqOppSize
uint8_t ns3::BaseStationNetDevice::m_rangReqOppSize private
in symbols
Definition at line 408 of file bs-net-device.h.
Referenced by CreateUcd(), GetRangReqOppSize(), InitBaseStationNetDevice(), and SetRangReqOppSize().
m_scheduler
Ptr<BSScheduler> ns3::BaseStationNetDevice::m_scheduler private
the base station scheduler
Definition at line 449 of file bs-net-device.h.
Referenced by BaseStationNetDevice(), CreateDlMap(), DoDispose(), GetBSScheduler(), GetTypeId(), SendBursts(), SetBSScheduler(), and StartDlSubFrame().
m_serviceFlowManager
Ptr<BsServiceFlowManager> ns3::BaseStationNetDevice::m_serviceFlowManager private
the service flow manager
Definition at line 452 of file bs-net-device.h.
Referenced by DoDispose(), GetServiceFlowManager(), InitBaseStationNetDevice(), SendBursts(), and SetServiceFlowManager().
m_ssManager
Ptr<SSManager> ns3::BaseStationNetDevice::m_ssManager private
the SS manager
Definition at line 447 of file bs-net-device.h.
Referenced by CreateMapMessages(), DoDispose(), DoReceive(), GetSSManager(), InitBaseStationNetDevice(), and SetSSManager().
m_symbolDuration
Time ns3::BaseStationNetDevice::m_symbolDuration private
symbol duration
Definition at line 455 of file bs-net-device.h.
Referenced by GetSymbolDuration(), InitBaseStationNetDevice(), MarkUplinkAllocations(), Start(), StartDlSubFrame(), StartFrame(), and StartUlSubFrame().
m_traceBSRx
TracedCallback<Ptr<const Packet>, Mac48Address, Cid> ns3::BaseStationNetDevice::m_traceBSRx private
the base station receive trace callback
Definition at line 457 of file bs-net-device.h.
Referenced by DoReceive().
m_ucdConfigChangeCount
uint32_t ns3::BaseStationNetDevice::m_ucdConfigChangeCount private
UCD config change count.
Definition at line 422 of file bs-net-device.h.
Referenced by CreateMapMessages(), CreateUcd(), CreateUlMap(), and InitBaseStationNetDevice().
m_ucdInterval
Time ns3::BaseStationNetDevice::m_ucdInterval private
in seconds
Definition at line 403 of file bs-net-device.h.
Referenced by GetUcdInterval(), InitBaseStationNetDevice(), and SetUcdInterval().
m_ulAllocationNumber
uint8_t ns3::BaseStationNetDevice::m_ulAllocationNumber private
to see UL burst number
Definition at line 440 of file bs-net-device.h.
Referenced by CreateUlMap(), InitBaseStationNetDevice(), UplinkAllocationEnd(), and UplinkAllocationStart().
m_ulSubframeStartTime
Time ns3::BaseStationNetDevice::m_ulSubframeStartTime private
UL subframe start time.
Definition at line 438 of file bs-net-device.h.
Referenced by GetUlSubframeStartTime(), InitBaseStationNetDevice(), and StartUlSubFrame().
m_uplinkScheduler
Ptr<UplinkScheduler> ns3::BaseStationNetDevice::m_uplinkScheduler private
the uplink scheduler
Definition at line 448 of file bs-net-device.h.
Referenced by BaseStationNetDevice(), CreateMapMessages(), CreateUlMap(), DoDispose(), GetUplinkScheduler(), MarkUplinkAllocations(), SetUplinkScheduler(), Start(), and StartDlSubFrame().
The documentation for this class was generated from the following files:
src/wimax/model/bs-net-device.h
src/wimax/model/bs-net-device.cc