ns-3: ns3::ArpCache::Entry Class Reference
ns3::ArpCache::Entry Class Reference
A record that that holds information about an ArpCache entry.
#include "arp-cache.h"
Public Member Functions
Entry (ArpCache *arp)
Constructor.
void ClearPendingPacket (void)
Clear the pending packet list.
void ClearRetries (void)
Zero the counter of number of retries for an entry.
Ipv4PayloadHeaderPair DequeuePending (void)
Ipv4Address GetIpv4Address (void) const
Address GetMacAddress (void) const
uint32_t GetRetries (void) const
void IncrementRetries (void)
Increment the counter of number of retries for an entry.
bool IsAlive (void)
bool IsDead (void)
bool IsExpired (void) const
bool IsPermanent (void)
bool IsWaitReply (void)
void MarkAlive (Address macAddress)
void MarkDead (void)
Changes the state of this entry to dead.
void MarkPermanent (void)
Changes the state of this entry to Permanent.
void MarkWaitReply (Ipv4PayloadHeaderPair waiting)
void SetIpv4Address (Ipv4Address destination)
void SetMacAddress (Address macAddress)
void UpdateSeen (void)
Update the entry when seeing a packet.
bool UpdateWaitReply (Ipv4PayloadHeaderPair waiting)
Private Types
enum ArpCacheEntryState_e { ALIVE , WAIT_REPLY , DEAD , PERMANENT }
ARP cache entry states.
Private Member Functions
Time GetTimeout (void) const
Returns the entry timeout.
Private Attributes
ArpCache * m_arp
pointer to the ARP cache owning the entry
Ipv4Address m_ipv4Address
entry's IP address
Time m_lastSeen
last moment a packet from that address has been seen
Address m_macAddress
entry's MAC address
std::list< Ipv4PayloadHeaderPair > m_pending
list of pending packets for the entry's IP
uint32_t m_retries
rerty counter
ArpCacheEntryState_e m_state
state of the entry
Detailed Description
A record that that holds information about an ArpCache entry.
Definition at line 188 of file arp-cache.h.
Member Enumeration Documentation
ArpCacheEntryState_e
enum ns3::ArpCache::Entry::ArpCacheEntryState_e private
ARP cache entry states.
Enumerator
ALIVE
WAIT_REPLY
DEAD
PERMANENT
Definition at line 290 of file arp-cache.h.
Constructor & Destructor Documentation
Entry()
ns3::ArpCache::Entry::Entry (ArpCache * arp)
Constructor.
Parameters
arp The ArpCache this entry belongs to
Definition at line 359 of file arp-cache.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
ClearPendingPacket()
void ns3::ArpCache::Entry::ClearPendingPacket (void)
Clear the pending packet list.
Definition at line 526 of file arp-cache.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::ArpCache::Remove().
ClearRetries()
void ns3::ArpCache::Entry::ClearRetries (void)
Zero the counter of number of retries for an entry.
Definition at line 551 of file arp-cache.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::ArpCache::HandleWaitReplyTimeout().
DequeuePending()
ArpCache::Ipv4PayloadHeaderPair ns3::ArpCache::Entry::DequeuePending (void)
Returns
0 is no packet is pending, the next packet to send if packets are pending.
Definition at line 510 of file arp-cache.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::ArpCache::HandleWaitReplyTimeout(), and ns3::ArpL3Protocol::Receive().
GetIpv4Address()
Ipv4Address ns3::ArpCache::Entry::GetIpv4Address (void) const
Returns
The Ipv4Address for this entry
Definition at line 466 of file arp-cache.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::ArpCache::HandleWaitReplyTimeout().
GetMacAddress()
Address ns3::ArpCache::Entry::GetMacAddress (void) const
Returns
The MacAddress of this entry
Definition at line 454 of file arp-cache.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::ArpL3Protocol::Lookup(), ns3::ArpCache::LookupInverse(), ns3::aodv::Neighbors::LookupMacAddress(), and ns3::dsr::DsrRouteCache::LookupMacAddress().
GetRetries()
uint32_t ns3::ArpCache::Entry::GetRetries (void) const
Returns
number of retries that have been sent for an ArpRequest in WaitReply state.
Definition at line 538 of file arp-cache.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::ArpCache::HandleWaitReplyTimeout().
GetTimeout()
Time ns3::ArpCache::Entry::GetTimeout (void) const private
Returns the entry timeout.
Returns
the entry timeout
Definition at line 478 of file arp-cache.cc.
References ALIVE, DEAD, ns3::Time::Max(), NS_ASSERT, NS_LOG_FUNCTION, PERMANENT, ns3::Seconds(), and WAIT_REPLY.
IncrementRetries()
void ns3::ArpCache::Entry::IncrementRetries (void)
Increment the counter of number of retries for an entry.
Definition at line 544 of file arp-cache.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::ArpCache::HandleWaitReplyTimeout().
IsAlive()
bool ns3::ArpCache::Entry::IsAlive (void)
Returns
True if the state of this entry is alive; false otherwise.
Definition at line 375 of file arp-cache.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::ArpL3Protocol::Lookup(), ns3::aodv::Neighbors::LookupMacAddress(), ns3::dsr::DsrRouteCache::LookupMacAddress(), and ns3::Ipv4L3Protocol::Receive().
IsDead()
bool ns3::ArpCache::Entry::IsDead (void)
Returns
True if the state of this entry is dead; false otherwise.
Definition at line 369 of file arp-cache.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::ArpL3Protocol::Lookup().
IsExpired()
bool ns3::ArpCache::Entry::IsExpired (void) const
Returns
True if this entry has timed out; false otherwise.
This function returns true if the time elapsed strictly exceeds the timeout value (i.e., is not less than or equal to the timeout).
Definition at line 497 of file arp-cache.cc.
References ns3::Time::GetSeconds(), ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and timeout.
Referenced by ns3::ArpL3Protocol::Lookup(), ns3::aodv::Neighbors::LookupMacAddress(), and ns3::dsr::DsrRouteCache::LookupMacAddress().
IsPermanent()
bool ns3::ArpCache::Entry::IsPermanent (void)
Returns
True if the state of this entry is permanent; false otherwise.
Definition at line 387 of file arp-cache.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::aodv::Neighbors::LookupMacAddress(), and ns3::dsr::DsrRouteCache::LookupMacAddress().
IsWaitReply()
bool ns3::ArpCache::Entry::IsWaitReply (void)
Returns
True if the state of this entry is wait_reply; false otherwise.
Definition at line 381 of file arp-cache.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::ArpCache::HandleWaitReplyTimeout(), ns3::ArpL3Protocol::Lookup(), and ns3::ArpL3Protocol::Receive().
MarkAlive()
void ns3::ArpCache::Entry::MarkAlive (Address macAddress)
Parameters
macAddress
Definition at line 404 of file arp-cache.cc.
References NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::ArpL3Protocol::Receive().
MarkDead()
void ns3::ArpCache::Entry::MarkDead (void)
Changes the state of this entry to dead.
Definition at line 395 of file arp-cache.cc.
References NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::ArpCache::HandleWaitReplyTimeout().
MarkPermanent()
void ns3::ArpCache::Entry::MarkPermanent (void)
Changes the state of this entry to Permanent.
The entry must have a valid MacAddress.
Definition at line 414 of file arp-cache.cc.
References NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by EpcS1uUlTestCase::DoRun().
MarkWaitReply()
void ns3::ArpCache::Entry::MarkWaitReply (Ipv4PayloadHeaderPair waiting)
Parameters
waiting
Definition at line 440 of file arp-cache.cc.
References NS_ASSERT, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
Referenced by ns3::ArpL3Protocol::Lookup().
SetIpv4Address()
void ns3::ArpCache::Entry::SetIpv4Address (Ipv4Address destination)
Parameters
destination The Ipv4Address for this entry
Definition at line 472 of file arp-cache.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::ArpCache::Add().
SetMacAddress()
void ns3::ArpCache::Entry::SetMacAddress (Address macAddress)
Parameters
macAddress The MacAddress for this entry
Definition at line 460 of file arp-cache.cc.
References NS_LOG_FUNCTION.
Referenced by EpcS1uUlTestCase::DoRun().
UpdateSeen()
void ns3::ArpCache::Entry::UpdateSeen (void)
Update the entry when seeing a packet.
Definition at line 532 of file arp-cache.cc.
References ns3::Simulator::Now(), and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4L3Protocol::Receive().
UpdateWaitReply()
bool ns3::ArpCache::Entry::UpdateWaitReply (Ipv4PayloadHeaderPair waiting)
Parameters
waiting
Returns
Definition at line 424 of file arp-cache.cc.
References NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::ArpL3Protocol::Lookup().
Member Data Documentation
m_arp
ArpCache* ns3::ArpCache::Entry::m_arp private
pointer to the ARP cache owning the entry
Definition at line 303 of file arp-cache.h.
m_ipv4Address
Ipv4Address ns3::ArpCache::Entry::m_ipv4Address private
entry's IP address
Definition at line 307 of file arp-cache.h.
m_lastSeen
Time ns3::ArpCache::Entry::m_lastSeen private
last moment a packet from that address has been seen
Definition at line 305 of file arp-cache.h.
m_macAddress
Address ns3::ArpCache::Entry::m_macAddress private
entry's MAC address
Definition at line 306 of file arp-cache.h.
m_pending
std::list<Ipv4PayloadHeaderPair> ns3::ArpCache::Entry::m_pending private
list of pending packets for the entry's IP
Definition at line 308 of file arp-cache.h.
m_retries
uint32_t ns3::ArpCache::Entry::m_retries private
rerty counter
Definition at line 309 of file arp-cache.h.
m_state
ArpCacheEntryState_e ns3::ArpCache::Entry::m_state private
state of the entry
Definition at line 304 of file arp-cache.h.
The documentation for this class was generated from the following files:
src/internet/model/arp-cache.h
src/internet/model/arp-cache.cc