ns-3: ns3::StaWifiMac Class Reference
ns3::StaWifiMac Class Reference
Wifi Models
The Wifi MAC high model for a non-AP STA in a BSS.
#include "sta-wifi-mac.h"
Public Member Functions
StaWifiMac ()
virtual ~StaWifiMac ()
void Enqueue (Ptr< Packet > packet, Mac48Address to)
uint16_t GetAssociationId (void) const
Return the association ID.
bool IsAssociated (void) const
Return whether we are associated with an AP.
void SetWifiPhy (const Ptr< WifiPhy > phy)
void SetWifiRemoteStationManager (const Ptr< WifiRemoteStationManager > stationManager)
Set up WifiRemoteStationManager associated with this StaWifiMac.
Public Member Functions inherited from ns3::InfrastructureWifiMac
InfrastructureWifiMac ()
virtual ~InfrastructureWifiMac ()
bool GetPcfSupported () const
Return whether the device supports PCF.
void SetPcfSupported (bool enable)
Enable or disable PCF support for the device.
void SetQosSupported (bool enable)
Enable or disable QoS support for the device.
Public Member Functions inherited from ns3::RegularWifiMac
RegularWifiMac ()
virtual ~RegularWifiMac ()
void ConfigureStandard (WifiStandard standard)
virtual void Enqueue (Ptr< Packet > packet, Mac48Address to, Mac48Address from)
Mac48Address GetAddress (void) const
Mac48Address GetBssid (void) const
ExtendedCapabilities GetExtendedCapabilities (void) const
Return the extended capabilities of the device.
HeCapabilities GetHeCapabilities (void) const
Return the HE capabilities of the device.
HtCapabilities GetHtCapabilities (void) const
Return the HT capabilities of the device.
bool GetShortSlotTimeSupported (void) const
Ssid GetSsid (void) const
VhtCapabilities GetVhtCapabilities (void) const
Return the VHT capabilities of the device.
Ptr< WifiPhy > GetWifiPhy (void) const
Ptr< WifiRemoteStationManager > GetWifiRemoteStationManager (void) const
void ResetWifiPhy (void)
Remove currently attached WifiPhy device from this MAC.
void SetAddress (Mac48Address address)
void SetBssid (Mac48Address bssid)
void SetCtsToSelfSupported (bool enable)
Enable or disable CTS-to-self feature.
void SetForwardUpCallback (ForwardUpCallback upCallback)
void SetLinkDownCallback (Callback< void > linkDown)
void SetLinkUpCallback (Callback< void > linkUp)
void SetPromisc (void)
Sets the interface in promiscuous mode.
void SetShortSlotTimeSupported (bool enable)
Enable or disable short slot time feature.
void SetSsid (Ssid ssid)
virtual bool SupportsSendFrom (void) const
Public Member Functions inherited from ns3::WifiMac
Ptr< NetDevice > GetDevice (void) const
Return the device this PHY is associated with.
Ptr< HeConfiguration > GetHeConfiguration (void) const
Ptr< HtConfiguration > GetHtConfiguration (void) const
Ptr< VhtConfiguration > GetVhtConfiguration (void) const
void NotifyPromiscRx (Ptr< const Packet > packet)
void NotifyRx (Ptr< const Packet > packet)
void NotifyRxDrop (Ptr< const Packet > packet)
void NotifyTx (Ptr< const Packet > packet)
void NotifyTxDrop (Ptr< const Packet > packet)
void SetDevice (const Ptr< NetDevice > device)
Sets the device this PHY is associated with.
virtual void SetForwardUpCallback (Callback< void, Ptr< const Packet >, Mac48Address, Mac48Address > upCallback)=0
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::InfrastructureWifiMac
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::RegularWifiMac
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::WifiMac
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
enum MacState {
ASSOCIATED , WAIT_BEACON , WAIT_PROBE_RESP , WAIT_ASSOC_RESP ,
UNASSOCIATED , REFUSED
}
The current MAC state of the STA.
Private Member Functions
void AssocRequestTimeout (void)
This method is called after the association timeout occurred.
void DoInitialize (void)
Initialize() implementation.
bool GetActiveProbing (void) const
Return whether active probing is enabled.
CapabilityInformation GetCapabilities (void) const
Return the Capability information of the current STA.
SupportedRates GetSupportedRates (void) const
Return an instance of SupportedRates that contains all rates that we support including HT rates.
bool IsWaitAssocResp (void) const
Return whether we are waiting for an association response from an AP.
void MissedBeacons (void)
This method is called after we have not received a beacon from the AP.
void PhyCapabilitiesChanged (void)
Indicate that PHY capabilities have changed.
void Receive (Ptr< WifiMacQueueItem > mpdu)
Handle a received packet.
void RestartBeaconWatchdog (Time delay)
Restarts the beacon timer.
void ScanningTimeout (void)
This method is called after wait beacon timeout or wait probe request timeout has occurred.
void SendAssociationRequest (bool isReassoc)
Forward an association or reassociation request packet to the DCF.
void SendCfPollResponse (void)
Forward a CF-Poll response packet to the CFP queue.
void SendProbeRequest (void)
Forward a probe request packet to the DCF.
void SetActiveProbing (bool enable)
Enable or disable active probing.
void SetEdcaParameters (AcIndex ac, uint32_t cwMin, uint32_t cwMax, uint8_t aifsn, Time txopLimit)
Set the EDCA parameters.
void SetState (MacState value)
Set the current MAC state.
void StartScanning (void)
Start the scanning process which trigger active or passive scanning based on the active probing flag.
void TryToEnsureAssociated (void)
Try to ensure that we are associated with an AP by taking an appropriate action depending on the current association status.
void UpdateApInfoFromAssocResp (MgtAssocResponseHeader assocResp, Mac48Address apAddr)
Update AP's information from association response.
void UpdateApInfoFromBeacon (MgtBeaconHeader beacon, Mac48Address apAddr, Mac48Address bssid)
Update associated AP's information from beacon.
void UpdateApInfoFromProbeResp (MgtProbeResponseHeader probeResp, Mac48Address apAddr, Mac48Address bssid)
Update AP's information from probe response.
void UpdateCandidateApList (ApInfo newApInfo)
Update list of candidate AP to associate.
Private Attributes
bool m_activeProbing
active probing
uint16_t m_aid
Association AID.
TracedCallback< Mac48Address > m_assocLogger
association logger
EventId m_assocRequestEvent
association request event
Time m_assocRequestTimeout
association request timeout
TracedCallback< Time > m_beaconArrival
beacon arrival logger
EventId m_beaconWatchdog
beacon watchdog
Time m_beaconWatchdogEnd
beacon watchdog end
std::vector< ApInfo > m_candidateAps
list of candidate APs to associate to
TracedCallback< Mac48Address > m_deAssocLogger
disassociation logger
uint32_t m_maxMissedBeacons
maximum missed beacons
EventId m_probeRequestEvent
probe request event
Time m_probeRequestTimeout
probe request timeout
MacState m_state
MAC state.
EventId m_waitBeaconEvent
wait beacon event
Time m_waitBeaconTimeout
wait beacon timeout
Friends
class ::AmpduAggregationTest
Allow test cases to access private members.
class ::HeAggregationTest
Allow test cases to access private members.
class ::TwoLevelAggregationTest
Allow test cases to access private members.
Additional Inherited Members
Public Types inherited from ns3::RegularWifiMac
typedef Callback< void, Ptr< const Packet >, Mac48Address, Mac48Address > ForwardUpCallback
This type defines the callback of a higher layer that a WifiMac(-derived) object invokes to pass a packet up the stack.
Protected Types inherited from ns3::RegularWifiMac
typedef std::map< AcIndex, Ptr< QosTxop > > EdcaQueues
This type defines a mapping between an Access Category index, and a pointer to the corresponding channel access function.
Protected Member Functions inherited from ns3::RegularWifiMac
void ConfigureContentionWindow (uint32_t cwMin, uint32_t cwMax)
virtual void DeaggregateAmsduAndForward (Ptr< WifiMacQueueItem > mpdu)
This method can be called to de-aggregate an A-MSDU and forward the constituent packets up the stack.
virtual void DoDispose ()
Destructor implementation.
void ForwardUp (Ptr< const Packet > packet, Mac48Address from, Mac48Address to)
Forward the packet up to the device.
Ptr< QosTxop > GetBEQueue (void) const
Accessor for the AC_BE channel access function.
Ptr< QosTxop > GetBKQueue (void) const
Accessor for the AC_BK channel access function.
bool GetDsssSupported () const
Return whether the device supports DSSS.
bool GetErpSupported () const
Return whether the device supports ERP.
bool GetHeSupported () const
Return whether the device supports HE.
bool GetHtSupported () const
Return whether the device supports HT.
bool GetQosSupported () const
Return whether the device supports QoS.
Ptr< Txop > GetTxop (void) const
Accessor for the DCF object.
bool GetVhtSupported () const
Return whether the device supports VHT.
Ptr< QosTxop > GetVIQueue (void) const
Accessor for the AC_VI channel access function.
Ptr< QosTxop > GetVOQueue (void) const
Accessor for the AC_VO channel access function.
void SendAddBaResponse (const MgtAddBaRequestHeader *reqHdr, Mac48Address originator)
This method can be called to accept a received ADDBA Request.
void SetDsssSupported (bool enable)
Enable or disable DSSS support for the device.
void SetErpSupported (bool enable)
Enable or disable ERP support for the device.
void SetTypeOfStation (TypeOfStation type)
This method is invoked by a subclass to specify what type of station it is implementing.
virtual void TxFailed (const WifiMacHeader &hdr)
The packet we sent was successfully received by the receiver (i.e.
virtual void TxOk (const WifiMacHeader &hdr)
The packet we sent was successfully received by the receiver (i.e.
Protected Member Functions inherited from ns3::WifiMac
void ConfigureDcf (Ptr< Txop > dcf, uint32_t cwmin, uint32_t cwmax, bool isDsss, AcIndex ac)
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::RegularWifiMac
Ptr< ChannelAccessManager > m_channelAccessManager
channel access manager
EdcaQueues m_edca
This is a map from Access Category index to the corresponding channel access function.
ForwardUpCallback m_forwardUp
Callback to forward packet up the stack.
Callback< void > m_linkDown
Callback when a link is down.
Callback< void > m_linkUp
Callback when a link is up.
Ptr< MacLow > m_low
MacLow (RTS, CTS, Data, Ack etc.)
Ptr< WifiPhy > m_phy
Wifi PHY.
Ptr< MacRxMiddle > m_rxMiddle
RX middle (defragmentation etc.)
Ssid m_ssid
Service Set ID (SSID)
Ptr< WifiRemoteStationManager > m_stationManager
Remote station manager (rate control, RTS/CTS/fragmentation thresholds etc.)
Ptr< MacTxMiddle > m_txMiddle
TX middle (aggregation etc.)
Ptr< Txop > m_txop
This holds a pointer to the TXOP instance for this WifiMac - used for transmission of frames to non-QoS peers.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The Wifi MAC high model for a non-AP STA in a BSS.
The state machine is as follows:
---------       --------------                                         -----------
| Start |       | Associated | <-------------------------        ----> | Refused |
---------       --------------                           |      /      -----------
   |              |   /------------------------------\   |     /
   \              v   v                              |   v    /
    \    ----------------     ---------------     -----------------------------
     \-> | Unassociated | --> | Wait Beacon | --> | Wait Association Response |
         ----------------     ---------------     -----------------------------
               \                  ^     ^ |              ^    ^ |
                \                 |     | |              |    | |
                 \                v      -               /     -
                  \    -----------------------          /
                   \-> | Wait Probe Response | --------/
                       -----------------------
                               ^ |
                               | |
                                -
Notes:
The state 'Start' is not included in MacState and only used for illustration purpose.
The Unassociated state is a transient state before STA starts the scanning procedure which moves it into either Wait Beacon or Wait Probe Response, based on whether passive or active scanning is selected.
In Wait Beacon and Wait Probe Response, STA is gathering beacon or probe response packets from APs, resulted in a list of candidate AP. After the respective timeout, it then tries to associate to the best AP (i.e., best SNR). STA will switch between the two states and restart the scanning procedure if SetActiveProbing() called.
In the case when AP responded to STA's association request with a refusal, STA will try to associate to the next best AP until the list of candidate AP is exhausted which sends STA to Refused state.
Note that this behavior is not currently tested since ns-3 does not implement association refusal at present.
The transition from Wait Association Response to Unassociated occurs if an association request fails without explicit refusal (i.e., the AP fails to respond).
The transition from Associated to Wait Association Response occurs when STA's PHY capabilities changed. In this state, STA tries to reassociate with the previously associated AP.
The transition from Associated to Unassociated occurs if the number of missed beacons exceeds the threshold.
Config Paths
ns3::StaWifiMac is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Mac/$ns3::RegularWifiMac/$ns3::InfrastructureWifiMac/$ns3::StaWifiMac"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Mac/$ns3::RegularWifiMac/$ns3::StaWifiMac"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Mac/$ns3::InfrastructureWifiMac/$ns3::StaWifiMac"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Mac/$ns3::StaWifiMac"
Attributes
ProbeRequestTimeout: The duration to actively probe the channel.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +5e+07ns
Flags: construct write read
WaitBeaconTimeout: The duration to dwell on a channel while passively scanning for beacon
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1.2e+08ns
Flags: construct write read
AssocRequestTimeout: The interval between two consecutive association request attempts.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +5e+08ns
Flags: construct write read
MaxMissedBeacons: Number of beacons which much be consecutively missed before we attempt to restart association.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 10
Flags: construct write read
ActiveProbing: If true, we send probe requests. If false, we don't.NOTE: if more than one STA in your simulation is using active probing, you should enable it at a different simulation time for each STA, otherwise all the STAs will start sending probes at the same time resulting in collisions. See bug 1060 for more info.
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
Attributes defined in parent class ns3::InfrastructureWifiMac
PcfSupported: This Boolean attribute is set to enable PCF support at this STA
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
Attributes defined in parent class ns3::RegularWifiMac
QosSupported: This Boolean attribute is set to enable 802.11e/WMM-style QoS support at this STA.
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
CtsToSelfSupported: Use CTS to Self when using a rate that is not in the basic rate set.
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write
VO_MaxAmsduSize: Maximum length in bytes of an A-MSDU for AC_VO access class (capped to 7935 for HT PPDUs and 11398 for VHT/HE PPDUs). Value 0 means A-MSDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:11398
Initial value: 0
Flags: construct write read
VI_MaxAmsduSize: Maximum length in bytes of an A-MSDU for AC_VI access class (capped to 7935 for HT PPDUs and 11398 for VHT/HE PPDUs). Value 0 means A-MSDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:11398
Initial value: 0
Flags: construct write read
BE_MaxAmsduSize: Maximum length in bytes of an A-MSDU for AC_BE access class (capped to 7935 for HT PPDUs and 11398 for VHT/HE PPDUs). Value 0 means A-MSDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:11398
Initial value: 0
Flags: construct write read
BK_MaxAmsduSize: Maximum length in bytes of an A-MSDU for AC_BK access class (capped to 7935 for HT PPDUs and 11398 for VHT/HE PPDUs). Value 0 means A-MSDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:11398
Initial value: 0
Flags: construct write read
VO_MaxAmpduSize: Maximum length in bytes of an A-MPDU for AC_VO access class (capped to 65535 for HT PPDUs, 1048575 for VHT PPDUs, and 8388607 for HE PPDUs). Value 0 means A-MPDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 0
Flags: construct write read
VI_MaxAmpduSize: Maximum length in bytes of an A-MPDU for AC_VI access class (capped to 65535 for HT PPDUs, 1048575 for VHT PPDUs, and 8388607 for HE PPDUs). Value 0 means A-MPDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 65535
Flags: construct write read
BE_MaxAmpduSize: Maximum length in bytes of an A-MPDU for AC_BE access class (capped to 65535 for HT PPDUs, 1048575 for VHT PPDUs, and 8388607 for HE PPDUs). Value 0 means A-MPDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 65535
Flags: construct write read
BK_MaxAmpduSize: Maximum length in bytes of an A-MPDU for AC_BK access class (capped to 65535 for HT PPDUs, 1048575 for VHT PPDUs, and 8388607 for HE PPDUs). Value 0 means A-MPDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 0
Flags: construct write read
VO_BlockAckThreshold: If number of packets in VO queue reaches this value, block ack mechanism is used. If this value is 0, block ack is never used.When A-MPDU is enabled, block ack mechanism is used regardless of this value.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:64
Initial value: 0
Flags: construct write
VI_BlockAckThreshold: If number of packets in VI queue reaches this value, block ack mechanism is used. If this value is 0, block ack is never used.When A-MPDU is enabled, block ack mechanism is used regardless of this value.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:64
Initial value: 0
Flags: construct write
BE_BlockAckThreshold: If number of packets in BE queue reaches this value, block ack mechanism is used. If this value is 0, block ack is never used.When A-MPDU is enabled, block ack mechanism is used regardless of this value.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:64
Initial value: 0
Flags: construct write
BK_BlockAckThreshold: If number of packets in BK queue reaches this value, block ack mechanism is used. If this value is 0, block ack is never used.When A-MPDU is enabled, block ack mechanism is used regardless of this value.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:64
Initial value: 0
Flags: construct write
VO_BlockAckInactivityTimeout: Represents max time (blocks of 1024 microseconds) allowed for block ackinactivity for AC_VO. If this value isn't equal to 0 a timer start after that ablock ack setup is completed and will be reset every time that a block ackframe is received. If this value is 0, block ack inactivity timeout won't be used.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 0
Flags: construct write
VI_BlockAckInactivityTimeout: Represents max time (blocks of 1024 microseconds) allowed for block ackinactivity for AC_VI. If this value isn't equal to 0 a timer start after that ablock ack setup is completed and will be reset every time that a block ackframe is received. If this value is 0, block ack inactivity timeout won't be used.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 0
Flags: construct write
BE_BlockAckInactivityTimeout: Represents max time (blocks of 1024 microseconds) allowed for block ackinactivity for AC_BE. If this value isn't equal to 0 a timer start after that ablock ack setup is completed and will be reset every time that a block ackframe is received. If this value is 0, block ack inactivity timeout won't be used.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 0
Flags: construct write
BK_BlockAckInactivityTimeout: Represents max time (blocks of 1024 microseconds) allowed for block ackinactivity for AC_BK. If this value isn't equal to 0 a timer start after that ablock ack setup is completed and will be reset every time that a block ackframe is received. If this value is 0, block ack inactivity timeout won't be used.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 0
Flags: construct write
ShortSlotTimeSupported: Whether or not short slot time is supported (only used by ERP APs or STAs).
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
Txop: The Txop object.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::Txop>
Flags: read
VO_Txop: Queue that manages packets belonging to AC_VO access class.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::QosTxop>
Flags: read
VI_Txop: Queue that manages packets belonging to AC_VI access class.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::QosTxop>
Flags: read
BE_Txop: Queue that manages packets belonging to AC_BE access class.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::QosTxop>
Flags: read
BK_Txop: Queue that manages packets belonging to AC_BK access class.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::QosTxop>
Flags: read
Attributes defined in parent class ns3::WifiMac
Ssid: The ssid we want to belong to.
Set with class: SsidValue
Underlying type: Ssid
Initial value: default
Flags: construct write read
TraceSources
Assoc: Associated with an access point.
Callback signature: ns3::Mac48Address::TracedCallback
DeAssoc: Association with an access point lost.
Callback signature: ns3::Mac48Address::TracedCallback
BeaconArrival: Time of beacons arrival from associated AP
Callback signature: ns3::Time::TracedCallback
TraceSources defined in parent class ns3::RegularWifiMac
TxOkHeader: The header of successfully transmitted packet.
Callback signature: ns3::WifiMacHeader::TracedCallback
TxErrHeader: The header of unsuccessfully transmitted packet.
Callback signature: ns3::WifiMacHeader::TracedCallback
TraceSources defined in parent class ns3::WifiMac
MacTx: A packet has been received from higher layers and is being processed in preparation for queueing for transmission.
Callback signature: ns3::Packet::TracedCallback
MacTxDrop: A packet has been dropped in the MAC layer before transmission.
Callback signature: ns3::Packet::TracedCallback
MacPromiscRx: A packet has been received by this device, has been passed up from the physical layer and is being forwarded up the local protocol stack. This is a promiscuous trace.
Callback signature: ns3::Packet::TracedCallback
MacRx: A packet has been received by this device, has been passed up from the physical layer and is being forwarded up the local protocol stack. This is a non-promiscuous trace.
Callback signature: ns3::Packet::TracedCallback
MacRxDrop: A packet has been dropped in the MAC layer after it has been passed up from the physical layer.
Callback signature: ns3::Packet::TracedCallback
Size of this type is 640 bytes (on a 64-bit architecture).
Definition at line 106 of file sta-wifi-mac.h.
Member Enumeration Documentation
MacState
enum ns3::StaWifiMac::MacState private
The current MAC state of the STA.
Enumerator
ASSOCIATED
WAIT_BEACON
WAIT_PROBE_RESP
WAIT_ASSOC_RESP
UNASSOCIATED
REFUSED
Definition at line 164 of file sta-wifi-mac.h.
Constructor & Destructor Documentation
StaWifiMac()
ns3::StaWifiMac::StaWifiMac ()
Definition at line 89 of file sta-wifi-mac.cc.
References NS_LOG_FUNCTION, ns3::RegularWifiMac::SetTypeOfStation(), and ns3::STA.
~StaWifiMac()
ns3::StaWifiMac::~StaWifiMac () virtual
Definition at line 111 of file sta-wifi-mac.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AssocRequestTimeout()
void ns3::StaWifiMac::AssocRequestTimeout (void) private
This method is called after the association timeout occurred.
We switch the state to WAIT_ASSOC_RESP and re-send an association request.
Definition at line 383 of file sta-wifi-mac.cc.
References NS_LOG_FUNCTION, SendAssociationRequest(), SetState(), and WAIT_ASSOC_RESP.
Referenced by SendAssociationRequest().
DoInitialize()
void ns3::StaWifiMac::DoInitialize (void) private virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::RegularWifiMac.
Definition at line 105 of file sta-wifi-mac.cc.
References NS_LOG_FUNCTION, and StartScanning().
Enqueue()
void ns3::StaWifiMac::Enqueue (Ptr< Packet > packet, Mac48Address to) virtual
Parameters
packet the packet to send.
to the address to which the packet should be sent.
The packet should be enqueued in a TX queue, and should be dequeued as soon as the channel access function determines that access is granted to this MAC.
Implements ns3::InfrastructureWifiMac.
Definition at line 435 of file sta-wifi-mac.cc.
References ns3::RegularWifiMac::GetBssid(), ns3::RegularWifiMac::GetQosSupported(), IsAssociated(), ns3::RegularWifiMac::m_edca, ns3::RegularWifiMac::m_low, ns3::RegularWifiMac::m_txop, ns3::WifiMacHeader::NORMAL_ACK, ns3::WifiMac::NotifyTxDrop(), NS_ASSERT, NS_LOG_FUNCTION, ns3::QosUtilsGetTidForPacket(), ns3::QosUtilsMapTidToAc(), ns3::Txop::Queue(), ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetAddr2(), ns3::WifiMacHeader::SetAddr3(), ns3::WifiMacHeader::SetDsNotFrom(), ns3::WifiMacHeader::SetDsTo(), ns3::WifiMacHeader::SetNoOrder(), ns3::WifiMacHeader::SetQosAckPolicy(), ns3::WifiMacHeader::SetQosNoAmsdu(), ns3::WifiMacHeader::SetQosNoEosp(), ns3::WifiMacHeader::SetQosTid(), ns3::WifiMacHeader::SetQosTxopLimit(), ns3::WifiMacHeader::SetType(), TryToEnsureAssociated(), ns3::WIFI_MAC_DATA, and ns3::WIFI_MAC_QOSDATA.
GetActiveProbing()
bool ns3::StaWifiMac::GetActiveProbing (void) const private
Return whether active probing is enabled.
Returns
true if active probing is enabled, false otherwise
Definition at line 136 of file sta-wifi-mac.cc.
References m_activeProbing.
Referenced by GetTypeId(), and StartScanning().
GetAssociationId()
uint16_t ns3::StaWifiMac::GetAssociationId (void) const
Return the association ID.
Returns
the association ID
Definition at line 117 of file sta-wifi-mac.cc.
References IsAssociated(), m_aid, and NS_ASSERT_MSG.
GetCapabilities()
CapabilityInformation ns3::StaWifiMac::GetCapabilities (void) const private
Return the Capability information of the current STA.
Returns
the Capability information that we support
Definition at line 1116 of file sta-wifi-mac.cc.
References ns3::RegularWifiMac::GetErpSupported(), ns3::InfrastructureWifiMac::GetPcfSupported(), ns3::WifiPhy::GetShortPhyPreambleSupported(), ns3::RegularWifiMac::GetShortSlotTimeSupported(), ns3::RegularWifiMac::m_phy, ns3::CapabilityInformation::SetCfPollable(), ns3::CapabilityInformation::SetShortPreamble(), and ns3::CapabilityInformation::SetShortSlotTime().
Referenced by SendAssociationRequest().
GetSupportedRates()
SupportedRates ns3::StaWifiMac::GetSupportedRates (void) const private
Return an instance of SupportedRates that contains all rates that we support including HT rates.
Returns
SupportedRates all rates that we support
Definition at line 1095 of file sta-wifi-mac.cc.
References ns3::SupportedRates::AddBssMembershipSelectorRate(), ns3::SupportedRates::AddSupportedRate(), ns3::WifiPhy::GetBssMembershipSelector(), ns3::WifiPhy::GetChannelWidth(), ns3::WifiMode::GetDataRate(), ns3::RegularWifiMac::GetHtSupported(), ns3::WifiPhy::GetMode(), ns3::WifiPhy::GetNBssMembershipSelectors(), ns3::WifiPhy::GetNModes(), ns3::RegularWifiMac::m_phy, and NS_LOG_DEBUG.
Referenced by SendAssociationRequest(), and SendProbeRequest().
GetTypeId()
TypeId ns3::StaWifiMac::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 42 of file sta-wifi-mac.cc.
References GetActiveProbing(), m_assocLogger, m_assocRequestTimeout, m_beaconArrival, m_deAssocLogger, m_maxMissedBeacons, m_probeRequestTimeout, m_waitBeaconTimeout, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), ns3::MilliSeconds(), ns3::Seconds(), SetActiveProbing(), and ns3::TypeId::SetParent().
IsAssociated()
bool ns3::StaWifiMac::IsAssociated (void) const
Return whether we are associated with an AP.
Returns
true if we are associated with an AP, false otherwise
Definition at line 423 of file sta-wifi-mac.cc.
References ASSOCIATED, and m_state.
Referenced by Enqueue(), GetAssociationId(), PhyCapabilitiesChanged(), and Receive().
IsWaitAssocResp()
bool ns3::StaWifiMac::IsWaitAssocResp (void) const private
Return whether we are waiting for an association response from an AP.
Returns
true if we are waiting for an association response from an AP, false otherwise
Definition at line 429 of file sta-wifi-mac.cc.
References m_state, and WAIT_ASSOC_RESP.
Referenced by Receive().
MissedBeacons()
void ns3::StaWifiMac::MissedBeacons (void) private
This method is called after we have not received a beacon from the AP.
Definition at line 391 of file sta-wifi-mac.cc.
References ns3::EventId::Cancel(), ns3::EventId::IsRunning(), m_beaconWatchdog, m_beaconWatchdogEnd, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), SetState(), TryToEnsureAssociated(), and UNASSOCIATED.
Referenced by RestartBeaconWatchdog().
PhyCapabilitiesChanged()
void ns3::StaWifiMac::PhyCapabilitiesChanged (void) private
Indicate that PHY capabilities have changed.
Definition at line 1155 of file sta-wifi-mac.cc.
References IsAssociated(), NS_LOG_DEBUG, NS_LOG_FUNCTION, SendAssociationRequest(), SetState(), and WAIT_ASSOC_RESP.
Referenced by SetWifiPhy().
Receive()
void ns3::StaWifiMac::Receive (Ptr< WifiMacQueueItem > mpdu) private virtual
Handle a received packet.
Parameters
mpdu the received MPDU
Reimplemented from ns3::RegularWifiMac.
Definition at line 505 of file sta-wifi-mac.cc.
References ASSOCIATED, ns3::EventId::Cancel(), ns3::RegularWifiMac::DeaggregateAmsduAndForward(), ns3::RegularWifiMac::ForwardUp(), ns3::SnrTag::Get(), ns3::WifiMacHeader::GetAddr1(), ns3::WifiMacHeader::GetAddr2(), ns3::WifiMacHeader::GetAddr3(), ns3::RegularWifiMac::GetAddress(), ns3::MgtAssocResponseHeader::GetAssociationId(), ns3::MgtProbeResponseHeader::GetBeaconIntervalUs(), ns3::RegularWifiMac::GetBssid(), ns3::WifiPhy::GetBssMembershipSelector(), ns3::MgtProbeResponseHeader::GetCapabilities(), ns3::MgtProbeResponseHeader::GetCfParameterSet(), ns3::CfParameterSet::GetCFPCount(), ns3::CfParameterSet::GetCFPDurRemainingUs(), ns3::CfParameterSet::GetCFPMaxDurationUs(), ns3::WifiPhy::GetNBssMembershipSelectors(), ns3::InfrastructureWifiMac::GetPcfSupported(), ns3::MgtProbeResponseHeader::GetSsid(), ns3::RegularWifiMac::GetSsid(), ns3::MgtAssocResponseHeader::GetStatusCode(), ns3::MgtProbeResponseHeader::GetSupportedRates(), ns3::WifiMacHeader::HasData(), IsAssociated(), ns3::WifiMacHeader::IsAssocReq(), ns3::WifiMacHeader::IsAssocResp(), ns3::WifiMacHeader::IsBeacon(), ns3::SupportedRates::IsBssMembershipSelectorRate(), ns3::WifiMacHeader::IsCfPoll(), ns3::WifiMacHeader::IsCtl(), ns3::WifiMacHeader::IsData(), ns3::Ssid::IsEqual(), ns3::CapabilityInformation::IsEss(), ns3::WifiMacHeader::IsFromDs(), ns3::Mac48Address::IsGroup(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), ns3::WifiMacHeader::IsProbeReq(), ns3::WifiMacHeader::IsProbeResp(), ns3::WifiMacHeader::IsQosAmsdu(), ns3::WifiMacHeader::IsQosData(), ns3::WifiMacHeader::IsReassocReq(), ns3::WifiMacHeader::IsReassocResp(), ns3::EventId::IsRunning(), ns3::StatusCode::IsSuccess(), ns3::WifiMacHeader::IsToDs(), IsWaitAssocResp(), ns3::ApInfo::m_activeProbing, m_aid, ns3::ApInfo::m_apAddr, m_assocRequestEvent, ns3::ApInfo::m_beacon, m_beaconArrival, ns3::ApInfo::m_bssid, m_candidateAps, ns3::RegularWifiMac::m_linkUp, ns3::RegularWifiMac::m_low, m_maxMissedBeacons, ns3::RegularWifiMac::m_phy, ns3::ApInfo::m_probeResp, ns3::ApInfo::m_snr, m_state, ns3::MicroSeconds(), ns3::WifiMac::NotifyRxDrop(), ns3::Simulator::Now(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::RegularWifiMac::Receive(), REFUSED, ns3::Packet::RemoveHeader(), ns3::Packet::RemovePacketTag(), RestartBeaconWatchdog(), ScanningTimeout(), SendCfPollResponse(), SetState(), UpdateApInfoFromAssocResp(), UpdateApInfoFromBeacon(), UpdateCandidateApList(), WAIT_ASSOC_RESP, WAIT_BEACON, and WAIT_PROBE_RESP.
RestartBeaconWatchdog()
void ns3::StaWifiMac::RestartBeaconWatchdog (Time delay) private
Restarts the beacon timer.
Parameters
delay the delay before the watchdog fires
Definition at line 410 of file sta-wifi-mac.cc.
References ns3::Simulator::GetDelayLeft(), ns3::EventId::IsExpired(), m_beaconWatchdog, m_beaconWatchdogEnd, max, MissedBeacons(), ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::Simulator::Schedule().
Referenced by Receive(), and ScanningTimeout().
ScanningTimeout()
void ns3::StaWifiMac::ScanningTimeout (void) private
This method is called after wait beacon timeout or wait probe request timeout has occurred.
This will trigger association process from beacons or probe responses gathered while scanning.
Definition at line 350 of file sta-wifi-mac.cc.
References ns3::MgtProbeResponseHeader::GetBeaconIntervalUs(), ns3::ApInfo::m_activeProbing, ns3::ApInfo::m_apAddr, ns3::ApInfo::m_beacon, ns3::ApInfo::m_bssid, m_candidateAps, m_maxMissedBeacons, ns3::ApInfo::m_probeResp, ns3::MicroSeconds(), NS_LOG_DEBUG, NS_LOG_FUNCTION, RestartBeaconWatchdog(), SendAssociationRequest(), SetState(), StartScanning(), UpdateApInfoFromBeacon(), UpdateApInfoFromProbeResp(), and WAIT_ASSOC_RESP.
Referenced by Receive(), and StartScanning().
SendAssociationRequest()
void ns3::StaWifiMac::SendAssociationRequest (bool isReassoc) private
Forward an association or reassociation request packet to the DCF.
The standard is not clear on the correct queue for management frames if QoS is supported. We always use the DCF.
Parameters
isReassoc flag whether it is a reassociation request
Definition at line 195 of file sta-wifi-mac.cc.
References ns3::Packet::AddHeader(), AssocRequestTimeout(), ns3::EventId::Cancel(), ns3::RegularWifiMac::GetAddress(), ns3::RegularWifiMac::GetBssid(), GetCapabilities(), ns3::RegularWifiMac::GetExtendedCapabilities(), ns3::RegularWifiMac::GetHeCapabilities(), ns3::RegularWifiMac::GetHeSupported(), ns3::RegularWifiMac::GetHtCapabilities(), ns3::RegularWifiMac::GetHtSupported(), ns3::RegularWifiMac::GetSsid(), GetSupportedRates(), ns3::RegularWifiMac::GetVhtCapabilities(), ns3::RegularWifiMac::GetVhtSupported(), ns3::EventId::IsRunning(), m_assocRequestEvent, m_assocRequestTimeout, ns3::RegularWifiMac::m_txop, NS_LOG_FUNCTION, ns3::Txop::Queue(), ns3::Simulator::Schedule(), ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetAddr2(), ns3::WifiMacHeader::SetAddr3(), ns3::MgtAssocRequestHeader::SetCapabilities(), ns3::MgtReassocRequestHeader::SetCapabilities(), ns3::MgtReassocRequestHeader::SetCurrentApAddress(), ns3::WifiMacHeader::SetDsNotFrom(), ns3::WifiMacHeader::SetDsNotTo(), ns3::MgtAssocRequestHeader::SetExtendedCapabilities(), ns3::MgtReassocRequestHeader::SetExtendedCapabilities(), ns3::MgtAssocRequestHeader::SetHeCapabilities(), ns3::MgtReassocRequestHeader::SetHeCapabilities(), ns3::MgtAssocRequestHeader::SetHtCapabilities(), ns3::MgtReassocRequestHeader::SetHtCapabilities(), ns3::MgtAssocRequestHeader::SetListenInterval(), ns3::MgtReassocRequestHeader::SetListenInterval(), ns3::MgtAssocRequestHeader::SetSsid(), ns3::MgtReassocRequestHeader::SetSsid(), ns3::MgtAssocRequestHeader::SetSupportedRates(), ns3::MgtReassocRequestHeader::SetSupportedRates(), ns3::WifiMacHeader::SetType(), ns3::MgtAssocRequestHeader::SetVhtCapabilities(), ns3::MgtReassocRequestHeader::SetVhtCapabilities(), ns3::WIFI_MAC_MGT_ASSOCIATION_REQUEST, and ns3::WIFI_MAC_MGT_REASSOCIATION_REQUEST.
Referenced by AssocRequestTimeout(), PhyCapabilitiesChanged(), and ScanningTimeout().
SendCfPollResponse()
void ns3::StaWifiMac::SendCfPollResponse (void) private
Forward a CF-Poll response packet to the CFP queue.
Definition at line 267 of file sta-wifi-mac.cc.
References ns3::RegularWifiMac::GetBssid(), ns3::InfrastructureWifiMac::GetPcfSupported(), ns3::RegularWifiMac::m_txop, NS_ASSERT, NS_LOG_FUNCTION, ns3::Txop::SendCfFrame(), and ns3::WIFI_MAC_DATA_NULL.
Referenced by Receive().
SendProbeRequest()
void ns3::StaWifiMac::SendProbeRequest (void) private
Forward a probe request packet to the DCF.
The standard is not clear on the correct queue for management frames if QoS is supported. We always use the DCF.
Definition at line 158 of file sta-wifi-mac.cc.
References ns3::Packet::AddHeader(), ns3::RegularWifiMac::GetAddress(), ns3::Mac48Address::GetBroadcast(), ns3::RegularWifiMac::GetExtendedCapabilities(), ns3::RegularWifiMac::GetHeCapabilities(), ns3::RegularWifiMac::GetHeSupported(), ns3::RegularWifiMac::GetHtCapabilities(), ns3::RegularWifiMac::GetHtSupported(), ns3::RegularWifiMac::GetSsid(), GetSupportedRates(), ns3::RegularWifiMac::GetVhtCapabilities(), ns3::RegularWifiMac::GetVhtSupported(), ns3::RegularWifiMac::m_txop, NS_LOG_FUNCTION, ns3::Txop::Queue(), ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetAddr2(), ns3::WifiMacHeader::SetAddr3(), ns3::WifiMacHeader::SetDsNotFrom(), ns3::WifiMacHeader::SetDsNotTo(), ns3::MgtProbeRequestHeader::SetExtendedCapabilities(), ns3::MgtProbeRequestHeader::SetHeCapabilities(), ns3::MgtProbeRequestHeader::SetHtCapabilities(), ns3::MgtProbeRequestHeader::SetSsid(), ns3::MgtProbeRequestHeader::SetSupportedRates(), ns3::WifiMacHeader::SetType(), ns3::MgtProbeRequestHeader::SetVhtCapabilities(), and ns3::WIFI_MAC_MGT_PROBE_REQUEST.
Referenced by StartScanning().
SetActiveProbing()
void ns3::StaWifiMac::SetActiveProbing (bool enable) private
Enable or disable active probing.
Parameters
enable enable or disable active probing
Definition at line 124 of file sta-wifi-mac.cc.
References m_activeProbing, m_state, NS_LOG_DEBUG, NS_LOG_FUNCTION, StartScanning(), WAIT_BEACON, and WAIT_PROBE_RESP.
Referenced by GetTypeId().
SetEdcaParameters()
void ns3::StaWifiMac::SetEdcaParameters (AcIndex ac, uint32_t cwMin, uint32_t cwMax, uint8_t aifsn, Time txopLimit) private
Set the EDCA parameters.
Parameters
ac the access class
cwMin the minimum contention window size
cwMax the maximum contention window size
aifsn the number of slots that make up an AIFS
txopLimit the TXOP limit
Definition at line 1145 of file sta-wifi-mac.cc.
References ns3::RegularWifiMac::m_edca, ns3::Txop::SetAifsn(), ns3::Txop::SetMaxCw(), ns3::Txop::SetMinCw(), and ns3::Txop::SetTxopLimit().
Referenced by UpdateApInfoFromAssocResp(), and UpdateApInfoFromBeacon().
SetState()
void ns3::StaWifiMac::SetState (MacState value) private
Set the current MAC state.
Parameters
value the new state
Definition at line 1129 of file sta-wifi-mac.cc.
References ASSOCIATED, ns3::RegularWifiMac::GetBssid(), m_assocLogger, m_deAssocLogger, and m_state.
Referenced by AssocRequestTimeout(), MissedBeacons(), PhyCapabilitiesChanged(), Receive(), ScanningTimeout(), and StartScanning().
SetWifiPhy()
void ns3::StaWifiMac::SetWifiPhy (const Ptr< WifiPhy > phy) virtual
Parameters
phy the physical layer attached to this MAC.
Reimplemented from ns3::RegularWifiMac.
Definition at line 142 of file sta-wifi-mac.cc.
References ns3::RegularWifiMac::m_phy, ns3::MakeCallback(), NS_LOG_FUNCTION, third::phy, PhyCapabilitiesChanged(), ns3::WifiPhy::SetCapabilitiesChangedCallback(), and ns3::RegularWifiMac::SetWifiPhy().
Referenced by AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), and HeAggregationTest::DoRunSubTest().
SetWifiRemoteStationManager()
void ns3::StaWifiMac::SetWifiRemoteStationManager (const Ptr< WifiRemoteStationManager > stationManager) virtual
Set up WifiRemoteStationManager associated with this StaWifiMac.
Parameters
stationManager the station manager attached to this MAC.
Reimplemented from ns3::RegularWifiMac.
Definition at line 150 of file sta-wifi-mac.cc.
References ns3::InfrastructureWifiMac::GetPcfSupported(), ns3::RegularWifiMac::m_stationManager, NS_LOG_FUNCTION, ns3::WifiRemoteStationManager::SetPcfSupported(), and ns3::RegularWifiMac::SetWifiRemoteStationManager().
Referenced by AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), and HeAggregationTest::DoRunSubTest().
StartScanning()
void ns3::StaWifiMac::StartScanning (void) private
Start the scanning process which trigger active or passive scanning based on the active probing flag.
Definition at line 320 of file sta-wifi-mac.cc.
References ns3::EventId::Cancel(), GetActiveProbing(), ns3::EventId::IsRunning(), m_candidateAps, m_probeRequestEvent, m_probeRequestTimeout, m_waitBeaconEvent, m_waitBeaconTimeout, NS_LOG_FUNCTION, ScanningTimeout(), ns3::Simulator::Schedule(), SendProbeRequest(), SetState(), WAIT_BEACON, and WAIT_PROBE_RESP.
Referenced by DoInitialize(), ScanningTimeout(), SetActiveProbing(), and TryToEnsureAssociated().
TryToEnsureAssociated()
void ns3::StaWifiMac::TryToEnsureAssociated (void) private
Try to ensure that we are associated with an AP by taking an appropriate action depending on the current association status.
Definition at line 275 of file sta-wifi-mac.cc.
References ASSOCIATED, ns3::RegularWifiMac::m_linkDown, m_state, NS_LOG_FUNCTION, REFUSED, StartScanning(), UNASSOCIATED, WAIT_ASSOC_RESP, WAIT_BEACON, and WAIT_PROBE_RESP.
Referenced by Enqueue(), and MissedBeacons().
UpdateApInfoFromAssocResp()
void ns3::StaWifiMac::UpdateApInfoFromAssocResp (MgtAssocResponseHeader assocResp, Mac48Address apAddr) private
Update AP's information from association response.
Parameters
assocResp the association response header
apAddr MAC address of the AP
Definition at line 937 of file sta-wifi-mac.cc.
References ns3::AC_BE, ns3::AC_BK, ns3::AC_VI, ns3::AC_VO, ns3::WifiRemoteStationManager::AddBasicMode(), ns3::WifiRemoteStationManager::AddStationHeCapabilities(), ns3::WifiRemoteStationManager::AddStationHtCapabilities(), ns3::WifiRemoteStationManager::AddStationVhtCapabilities(), ns3::WifiRemoteStationManager::AddSupportedMcs(), ns3::WifiRemoteStationManager::AddSupportedMode(), ns3::RegularWifiMac::ConfigureContentionWindow(), ns3::ErpInformation::GetBarkerPreambleMode(), ns3::EdcaParameterSet::GetBeAifsn(), ns3::EdcaParameterSet::GetBeCWmax(), ns3::EdcaParameterSet::GetBeCWmin(), ns3::EdcaParameterSet::GetBeTxopLimit(), ns3::EdcaParameterSet::GetBkAifsn(), ns3::EdcaParameterSet::GetBkCWmax(), ns3::EdcaParameterSet::GetBkCWmin(), ns3::EdcaParameterSet::GetBkTxopLimit(), ns3::HeOperation::GetBssColor(), ns3::MgtAssocResponseHeader::GetCapabilities(), ns3::WifiPhy::GetChannelWidth(), ns3::WifiMode::GetDataRate(), ns3::MgtAssocResponseHeader::GetEdcaParameterSet(), ns3::MgtAssocResponseHeader::GetErpInformation(), ns3::RegularWifiMac::GetErpSupported(), ns3::MgtAssocResponseHeader::GetExtendedCapabilities(), ns3::MgtAssocResponseHeader::GetHeCapabilities(), ns3::WifiMac::GetHeConfiguration(), ns3::MgtAssocResponseHeader::GetHeOperation(), ns3::RegularWifiMac::GetHeSupported(), ns3::MgtAssocResponseHeader::GetHtCapabilities(), ns3::MgtAssocResponseHeader::GetHtOperation(), ns3::RegularWifiMac::GetHtSupported(), ns3::WifiPhy::GetMcs(), ns3::WifiMode::GetMcsValue(), ns3::WifiPhy::GetMode(), ns3::WifiMode::GetModulationClass(), ns3::WifiPhy::GetNMcs(), ns3::WifiPhy::GetNModes(), ns3::HtOperation::GetNonGfHtStasPresent(), ns3::RegularWifiMac::GetQosSupported(), ns3::VhtCapabilities::GetRxHighestSupportedLgiDataRate(), ns3::WifiRemoteStationManager::GetShortSlotTimeEnabled(), ns3::HeCapabilities::GetSupportedMcsAndNss(), ns3::MgtAssocResponseHeader::GetSupportedRates(), ns3::MgtAssocResponseHeader::GetVhtCapabilities(), ns3::MgtAssocResponseHeader::GetVhtOperation(), ns3::RegularWifiMac::GetVhtSupported(), ns3::EdcaParameterSet::GetViAifsn(), ns3::EdcaParameterSet::GetViCWmax(), ns3::EdcaParameterSet::GetViCWmin(), ns3::EdcaParameterSet::GetViTxopLimit(), ns3::EdcaParameterSet::GetVoAifsn(), ns3::EdcaParameterSet::GetVoCWmax(), ns3::EdcaParameterSet::GetVoCWmin(), ns3::EdcaParameterSet::GetVoTxopLimit(), ns3::SupportedRates::IsBasicRate(), ns3::EdcaParameterSet::IsQosSupported(), ns3::CapabilityInformation::IsShortPreamble(), ns3::CapabilityInformation::IsShortSlotTime(), ns3::HtCapabilities::IsSupportedMcs(), ns3::SupportedRates::IsSupportedRate(), ns3::HeCapabilities::IsSupportedRxMcs(), ns3::VhtCapabilities::IsSupportedRxMcs(), ns3::RegularWifiMac::m_phy, ns3::RegularWifiMac::m_stationManager, ns3::MicroSeconds(), NS_LOG_FUNCTION, ns3::WifiRemoteStationManager::RemoveAllSupportedMcs(), SetEdcaParameters(), ns3::WifiRemoteStationManager::SetQosSupport(), ns3::WifiRemoteStationManager::SetShortPreambleEnabled(), ns3::WifiRemoteStationManager::SetShortSlotTimeEnabled(), ns3::WifiPhy::SetSlot(), ns3::WifiRemoteStationManager::SetUseGreenfieldProtection(), ns3::WIFI_MOD_CLASS_ERP_OFDM, ns3::WIFI_MOD_CLASS_HE, ns3::WIFI_MOD_CLASS_HT, and ns3::WIFI_MOD_CLASS_VHT.
Referenced by Receive().
UpdateApInfoFromBeacon()
void ns3::StaWifiMac::UpdateApInfoFromBeacon (MgtBeaconHeader beacon, Mac48Address apAddr, Mac48Address bssid) private
Update associated AP's information from beacon.
If STA is not associated, this information will used for the association process.
Parameters
beacon the beacon header
apAddr MAC address of the AP
bssid MAC address of BSSID
Definition at line 749 of file sta-wifi-mac.cc.
References ns3::AC_BE, ns3::AC_BK, ns3::AC_VI, ns3::AC_VO, ns3::WifiRemoteStationManager::AddStationHeCapabilities(), ns3::WifiRemoteStationManager::AddStationHtCapabilities(), ns3::WifiRemoteStationManager::AddStationVhtCapabilities(), ns3::WifiRemoteStationManager::AddSupportedMcs(), ns3::WifiRemoteStationManager::AddSupportedMode(), ns3::ErpInformation::GetBarkerPreambleMode(), ns3::EdcaParameterSet::GetBeAifsn(), ns3::EdcaParameterSet::GetBeCWmax(), ns3::EdcaParameterSet::GetBeCWmin(), ns3::EdcaParameterSet::GetBeTxopLimit(), ns3::EdcaParameterSet::GetBkAifsn(), ns3::EdcaParameterSet::GetBkCWmax(), ns3::EdcaParameterSet::GetBkCWmin(), ns3::EdcaParameterSet::GetBkTxopLimit(), ns3::MgtProbeResponseHeader::GetCapabilities(), ns3::WifiPhy::GetChannelWidth(), ns3::WifiMode::GetDataRate(), ns3::MgtProbeResponseHeader::GetEdcaParameterSet(), ns3::MgtProbeResponseHeader::GetErpInformation(), ns3::RegularWifiMac::GetErpSupported(), ns3::MgtProbeResponseHeader::GetExtendedCapabilities(), ns3::MgtProbeResponseHeader::GetHeCapabilities(), ns3::MgtProbeResponseHeader::GetHeOperation(), ns3::RegularWifiMac::GetHeSupported(), ns3::MgtProbeResponseHeader::GetHtCapabilities(), ns3::MgtProbeResponseHeader::GetHtOperation(), ns3::RegularWifiMac::GetHtSupported(), ns3::WifiPhy::GetMcs(), ns3::WifiMode::GetMcsValue(), ns3::WifiPhy::GetMode(), ns3::WifiMode::GetModulationClass(), ns3::WifiPhy::GetNMcs(), ns3::WifiPhy::GetNModes(), ns3::HtOperation::GetNonGfHtStasPresent(), ns3::RegularWifiMac::GetQosSupported(), ns3::VhtCapabilities::GetRxHighestSupportedLgiDataRate(), ns3::HeCapabilities::GetSupportedMcsAndNss(), ns3::MgtProbeResponseHeader::GetSupportedRates(), ns3::ErpInformation::GetUseProtection(), ns3::MgtProbeResponseHeader::GetVhtCapabilities(), ns3::MgtProbeResponseHeader::GetVhtOperation(), ns3::RegularWifiMac::GetVhtSupported(), ns3::EdcaParameterSet::GetViAifsn(), ns3::EdcaParameterSet::GetViCWmax(), ns3::EdcaParameterSet::GetViCWmin(), ns3::EdcaParameterSet::GetViTxopLimit(), ns3::EdcaParameterSet::GetVoAifsn(), ns3::EdcaParameterSet::GetVoCWmax(), ns3::EdcaParameterSet::GetVoCWmin(), ns3::EdcaParameterSet::GetVoTxopLimit(), ns3::EdcaParameterSet::IsQosSupported(), ns3::CapabilityInformation::IsShortPreamble(), ns3::CapabilityInformation::IsShortSlotTime(), ns3::HtCapabilities::IsSupportedMcs(), ns3::SupportedRates::IsSupportedRate(), ns3::HeCapabilities::IsSupportedRxMcs(), ns3::VhtCapabilities::IsSupportedRxMcs(), ns3::RegularWifiMac::m_phy, ns3::RegularWifiMac::m_stationManager, ns3::MicroSeconds(), NS_LOG_FUNCTION, ns3::WifiRemoteStationManager::RemoveAllSupportedMcs(), ns3::RegularWifiMac::SetBssid(), SetEdcaParameters(), ns3::WifiRemoteStationManager::SetQosSupport(), ns3::WifiRemoteStationManager::SetShortPreambleEnabled(), ns3::WifiRemoteStationManager::SetShortSlotTimeEnabled(), ns3::WifiPhy::SetSlot(), ns3::WifiRemoteStationManager::SetUseGreenfieldProtection(), ns3::WifiRemoteStationManager::SetUseNonErpProtection(), ns3::WIFI_MOD_CLASS_HE, and ns3::WIFI_MOD_CLASS_VHT.
Referenced by Receive(), and ScanningTimeout().
UpdateApInfoFromProbeResp()
void ns3::StaWifiMac::UpdateApInfoFromProbeResp (MgtProbeResponseHeader probeResp, Mac48Address apAddr, Mac48Address bssid) private
Update AP's information from probe response.
This information is required for the association process.
Parameters
probeResp the probe response header
apAddr MAC address of the AP
bssid MAC address of BSSID
Definition at line 868 of file sta-wifi-mac.cc.
References ns3::WifiRemoteStationManager::AddBasicMode(), ns3::WifiRemoteStationManager::AddSupportedMode(), ns3::RegularWifiMac::ConfigureContentionWindow(), ns3::ErpInformation::GetBarkerPreambleMode(), ns3::WifiPhy::GetBssMembershipSelector(), ns3::MgtProbeResponseHeader::GetCapabilities(), ns3::WifiPhy::GetChannelWidth(), ns3::WifiMode::GetDataRate(), ns3::MgtProbeResponseHeader::GetErpInformation(), ns3::RegularWifiMac::GetErpSupported(), ns3::WifiPhy::GetMode(), ns3::WifiMode::GetModulationClass(), ns3::WifiPhy::GetNBssMembershipSelectors(), ns3::WifiPhy::GetNModes(), ns3::WifiRemoteStationManager::GetShortSlotTimeEnabled(), ns3::MgtProbeResponseHeader::GetSupportedRates(), ns3::SupportedRates::IsBasicRate(), ns3::SupportedRates::IsBssMembershipSelectorRate(), ns3::CapabilityInformation::IsShortPreamble(), ns3::CapabilityInformation::IsShortSlotTime(), ns3::SupportedRates::IsSupportedRate(), ns3::RegularWifiMac::m_phy, ns3::RegularWifiMac::m_stationManager, ns3::MicroSeconds(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::RegularWifiMac::SetBssid(), ns3::WifiRemoteStationManager::SetShortPreambleEnabled(), ns3::WifiRemoteStationManager::SetShortSlotTimeEnabled(), ns3::WifiPhy::SetSlot(), and ns3::WIFI_MOD_CLASS_ERP_OFDM.
Referenced by ScanningTimeout().
UpdateCandidateApList()
void ns3::StaWifiMac::UpdateCandidateApList (ApInfo newApInfo) private
Update list of candidate AP to associate.
The list should contain ApInfo sorted from best to worst SNR, with no duplicate.
Parameters
newApInfo the new ApInfo to be inserted
Definition at line 723 of file sta-wifi-mac.cc.
References ns3::ApInfo::m_activeProbing, ns3::ApInfo::m_apAddr, ns3::ApInfo::m_beacon, ns3::ApInfo::m_bssid, m_candidateAps, ns3::ApInfo::m_probeResp, ns3::ApInfo::m_snr, and NS_LOG_FUNCTION.
Referenced by Receive().
Friends And Related Function Documentation
::AmpduAggregationTest
friend class ::AmpduAggregationTest friend
Allow test cases to access private members.
Definition at line 112 of file sta-wifi-mac.h.
::HeAggregationTest
friend class ::HeAggregationTest friend
Allow test cases to access private members.
Definition at line 114 of file sta-wifi-mac.h.
::TwoLevelAggregationTest
friend class ::TwoLevelAggregationTest friend
Allow test cases to access private members.
Definition at line 110 of file sta-wifi-mac.h.
Member Data Documentation
m_activeProbing
bool ns3::StaWifiMac::m_activeProbing private
active probing
Definition at line 329 of file sta-wifi-mac.h.
Referenced by GetActiveProbing(), and SetActiveProbing().
m_aid
uint16_t ns3::StaWifiMac::m_aid private
Association AID.
Definition at line 319 of file sta-wifi-mac.h.
Referenced by GetAssociationId(), and Receive().
m_assocLogger
TracedCallback<Mac48Address> ns3::StaWifiMac::m_assocLogger private
association logger
Definition at line 336 of file sta-wifi-mac.h.
Referenced by GetTypeId(), and SetState().
m_assocRequestEvent
EventId ns3::StaWifiMac::m_assocRequestEvent private
association request event
Definition at line 325 of file sta-wifi-mac.h.
Referenced by Receive(), and SendAssociationRequest().
m_assocRequestTimeout
Time ns3::StaWifiMac::m_assocRequestTimeout private
association request timeout
Definition at line 322 of file sta-wifi-mac.h.
Referenced by GetTypeId(), and SendAssociationRequest().
m_beaconArrival
TracedCallback<Time> ns3::StaWifiMac::m_beaconArrival private
beacon arrival logger
Definition at line 338 of file sta-wifi-mac.h.
Referenced by GetTypeId(), and Receive().
m_beaconWatchdog
EventId ns3::StaWifiMac::m_beaconWatchdog private
beacon watchdog
Definition at line 326 of file sta-wifi-mac.h.
Referenced by MissedBeacons(), and RestartBeaconWatchdog().
m_beaconWatchdogEnd
Time ns3::StaWifiMac::m_beaconWatchdogEnd private
beacon watchdog end
Definition at line 327 of file sta-wifi-mac.h.
Referenced by MissedBeacons(), and RestartBeaconWatchdog().
m_candidateAps
std::vector<ApInfo> ns3::StaWifiMac::m_candidateAps private
list of candidate APs to associate to
Definition at line 330 of file sta-wifi-mac.h.
Referenced by Receive(), ScanningTimeout(), StartScanning(), and UpdateCandidateApList().
m_deAssocLogger
TracedCallback<Mac48Address> ns3::StaWifiMac::m_deAssocLogger private
disassociation logger
Definition at line 337 of file sta-wifi-mac.h.
Referenced by GetTypeId(), and SetState().
m_maxMissedBeacons
uint32_t ns3::StaWifiMac::m_maxMissedBeacons private
maximum missed beacons
Definition at line 328 of file sta-wifi-mac.h.
Referenced by GetTypeId(), Receive(), and ScanningTimeout().
m_probeRequestEvent
EventId ns3::StaWifiMac::m_probeRequestEvent private
probe request event
Definition at line 324 of file sta-wifi-mac.h.
Referenced by StartScanning().
m_probeRequestTimeout
Time ns3::StaWifiMac::m_probeRequestTimeout private
probe request timeout
Definition at line 321 of file sta-wifi-mac.h.
Referenced by GetTypeId(), and StartScanning().
m_state
MacState ns3::StaWifiMac::m_state private
MAC state.
Definition at line 318 of file sta-wifi-mac.h.
Referenced by IsAssociated(), IsWaitAssocResp(), Receive(), SetActiveProbing(), SetState(), and TryToEnsureAssociated().
m_waitBeaconEvent
EventId ns3::StaWifiMac::m_waitBeaconEvent private
wait beacon event
Definition at line 323 of file sta-wifi-mac.h.
Referenced by StartScanning().
m_waitBeaconTimeout
Time ns3::StaWifiMac::m_waitBeaconTimeout private
wait beacon timeout
Definition at line 320 of file sta-wifi-mac.h.
Referenced by GetTypeId(), and StartScanning().
The documentation for this class was generated from the following files:
src/wifi/model/sta-wifi-mac.h
src/wifi/model/sta-wifi-mac.cc