ns-3: ns3::MeshWifiInterfaceMac Class Reference
ns3::MeshWifiInterfaceMac Class Reference
Mesh Device
Basic MAC of mesh point Wi-Fi interface.
#include "mesh-wifi-interface-mac.h"
Classes
struct Statistics
Statistics:
Public Member Functions
MeshWifiInterfaceMac ()
C-tor.
virtual ~MeshWifiInterfaceMac ()
D-tor.
virtual void Enqueue (Ptr< Packet > packet, Mac48Address to)
virtual void Enqueue (Ptr< Packet > packet, Mac48Address to, Mac48Address from)
virtual void SetLinkUpCallback (Callback< void > linkUp)
virtual bool SupportsSendFrom () const
Each mesh point interface must know the mesh point address
void SetMeshPointAddress (Mac48Address)
Mac48Address GetMeshPointAddress () const
Beacons
void SetRandomStartDelay (Time interval)
Set maximum initial random delay before first beacon.
void SetBeaconInterval (Time interval)
Set interval between two successive beacons.
Time GetBeaconInterval () const
Time GetTbtt () const
Next beacon frame time.
void ShiftTbtt (Time shift)
Shift TBTT.
void InstallPlugin (Ptr< MeshWifiInterfaceMacPlugin > plugin)
Install plugin.
uint16_t GetFrequencyChannel () const
Current channel Id.
void SwitchFrequencyChannel (uint16_t new_id)
Switch frequency channel.
void SendManagementFrame (Ptr< Packet > frame, const WifiMacHeader &hdr)
To be used by plugins sending management frames.
bool CheckSupportedRates (SupportedRates rates) const
Check supported rates.
SupportedRates GetSupportedRates () const
Public Member Functions inherited from ns3::RegularWifiMac
RegularWifiMac ()
virtual ~RegularWifiMac ()
void ConfigureStandard (WifiStandard standard)
Mac48Address GetAddress (void) const
Mac48Address GetBssid (void) const
ExtendedCapabilities GetExtendedCapabilities (void) const
Return the extended capabilities of the device.
HeCapabilities GetHeCapabilities (void) const
Return the HE capabilities of the device.
HtCapabilities GetHtCapabilities (void) const
Return the HT capabilities of the device.
bool GetShortSlotTimeSupported (void) const
Ssid GetSsid (void) const
VhtCapabilities GetVhtCapabilities (void) const
Return the VHT capabilities of the device.
Ptr< WifiPhy > GetWifiPhy (void) const
Ptr< WifiRemoteStationManager > GetWifiRemoteStationManager (void) const
void ResetWifiPhy (void)
Remove currently attached WifiPhy device from this MAC.
void SetAddress (Mac48Address address)
void SetBssid (Mac48Address bssid)
void SetCtsToSelfSupported (bool enable)
Enable or disable CTS-to-self feature.
void SetForwardUpCallback (ForwardUpCallback upCallback)
void SetLinkDownCallback (Callback< void > linkDown)
void SetLinkUpCallback (Callback< void > linkUp)
void SetPromisc (void)
Sets the interface in promiscuous mode.
void SetShortSlotTimeSupported (bool enable)
Enable or disable short slot time feature.
void SetSsid (Ssid ssid)
virtual void SetWifiPhy (const Ptr< WifiPhy > phy)
virtual void SetWifiRemoteStationManager (const Ptr< WifiRemoteStationManager > stationManager)
Public Member Functions inherited from ns3::WifiMac
Ptr< NetDevice > GetDevice (void) const
Return the device this PHY is associated with.
Ptr< HeConfiguration > GetHeConfiguration (void) const
Ptr< HtConfiguration > GetHtConfiguration (void) const
Ptr< VhtConfiguration > GetVhtConfiguration (void) const
void NotifyPromiscRx (Ptr< const Packet > packet)
void NotifyRx (Ptr< const Packet > packet)
void NotifyRxDrop (Ptr< const Packet > packet)
void NotifyTx (Ptr< const Packet > packet)
void NotifyTxDrop (Ptr< const Packet > packet)
void SetDevice (const Ptr< NetDevice > device)
Sets the device this PHY is associated with.
virtual void SetForwardUpCallback (Callback< void, Ptr< const Packet >, Mac48Address, Mac48Address > upCallback)=0
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::RegularWifiMac
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::WifiMac
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Mesh timing intervals
bool m_beaconEnable
whether beaconing is enabled
Time m_beaconInterval
Beaconing interval.
Time m_randomStart
Maximum delay before first beacon.
Time m_tbtt
Time for the next frame.
Mac48Address m_mpAddress
Mesh point address.
EventId m_beaconSendEvent
"Timer" for the next beacon
PluginList m_plugins
List of all installed plugins.
Callback< uint32_t, Mac48Address, Ptr< MeshWifiInterfaceMac > > m_linkMetricCallback
linkMetricCallback
Statistics m_stats
statistics
WifiStandard m_standard
Current standard: needed to configure metric.
Ptr< UniformRandomVariable > m_coefficient
Add randomness to beacon generation.
Metric Calculation routines:
typedef std::vector< Ptr< MeshWifiInterfaceMacPlugin > > PluginList
PluginList typedef.
void SetLinkMetricCallback (Callback< uint32_t, Mac48Address, Ptr< MeshWifiInterfaceMac > > cb)
PluginList typedef.
uint32_t GetLinkMetric (Mac48Address peerAddress)
PluginList typedef.
void Report (std::ostream &) const
Statistics:
void ResetStats ()
Reset statistics.
void SetBeaconGeneration (bool enable)
Enable/disable beacons.
virtual void ConfigureStandard (enum WifiStandard standard)
Finish configuration based on the WifiStandard being provided.
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
void Receive (Ptr< WifiMacQueueItem > mpdu)
Frame receive handler.
void ForwardDown (Ptr< Packet > packet, Mac48Address from, Mac48Address to)
Send frame.
void SendBeacon ()
Send beacon.
void ScheduleNextBeacon ()
Schedule next beacon.
bool GetBeaconGeneration () const
Get current beaconing status.
virtual void DoDispose ()
Real d-tor.
virtual void DoInitialize ()
PluginList typedef.
Additional Inherited Members
Public Types inherited from ns3::RegularWifiMac
typedef Callback< void, Ptr< const Packet >, Mac48Address, Mac48Address > ForwardUpCallback
This type defines the callback of a higher layer that a WifiMac(-derived) object invokes to pass a packet up the stack.
Protected Types inherited from ns3::RegularWifiMac
typedef std::map< AcIndex, Ptr< QosTxop > > EdcaQueues
This type defines a mapping between an Access Category index, and a pointer to the corresponding channel access function.
Protected Member Functions inherited from ns3::RegularWifiMac
void ConfigureContentionWindow (uint32_t cwMin, uint32_t cwMax)
virtual void DeaggregateAmsduAndForward (Ptr< WifiMacQueueItem > mpdu)
This method can be called to de-aggregate an A-MSDU and forward the constituent packets up the stack.
void ForwardUp (Ptr< const Packet > packet, Mac48Address from, Mac48Address to)
Forward the packet up to the device.
Ptr< QosTxop > GetBEQueue (void) const
Accessor for the AC_BE channel access function.
Ptr< QosTxop > GetBKQueue (void) const
Accessor for the AC_BK channel access function.
bool GetDsssSupported () const
Return whether the device supports DSSS.
bool GetErpSupported () const
Return whether the device supports ERP.
bool GetHeSupported () const
Return whether the device supports HE.
bool GetHtSupported () const
Return whether the device supports HT.
bool GetQosSupported () const
Return whether the device supports QoS.
Ptr< Txop > GetTxop (void) const
Accessor for the DCF object.
bool GetVhtSupported () const
Return whether the device supports VHT.
Ptr< QosTxop > GetVIQueue (void) const
Accessor for the AC_VI channel access function.
Ptr< QosTxop > GetVOQueue (void) const
Accessor for the AC_VO channel access function.
void SendAddBaResponse (const MgtAddBaRequestHeader *reqHdr, Mac48Address originator)
This method can be called to accept a received ADDBA Request.
void SetDsssSupported (bool enable)
Enable or disable DSSS support for the device.
void SetErpSupported (bool enable)
Enable or disable ERP support for the device.
virtual void SetQosSupported (bool enable)
Enable or disable QoS support for the device.
void SetTypeOfStation (TypeOfStation type)
This method is invoked by a subclass to specify what type of station it is implementing.
virtual void TxFailed (const WifiMacHeader &hdr)
The packet we sent was successfully received by the receiver (i.e.
virtual void TxOk (const WifiMacHeader &hdr)
The packet we sent was successfully received by the receiver (i.e.
Protected Member Functions inherited from ns3::WifiMac
void ConfigureDcf (Ptr< Txop > dcf, uint32_t cwmin, uint32_t cwmax, bool isDsss, AcIndex ac)
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::RegularWifiMac
Ptr< ChannelAccessManager > m_channelAccessManager
channel access manager
EdcaQueues m_edca
This is a map from Access Category index to the corresponding channel access function.
ForwardUpCallback m_forwardUp
Callback to forward packet up the stack.
Callback< void > m_linkDown
Callback when a link is down.
Callback< void > m_linkUp
Callback when a link is up.
Ptr< MacLow > m_low
MacLow (RTS, CTS, Data, Ack etc.)
Ptr< WifiPhy > m_phy
Wifi PHY.
Ptr< MacRxMiddle > m_rxMiddle
RX middle (defragmentation etc.)
Ssid m_ssid
Service Set ID (SSID)
Ptr< WifiRemoteStationManager > m_stationManager
Remote station manager (rate control, RTS/CTS/fragmentation thresholds etc.)
Ptr< MacTxMiddle > m_txMiddle
TX middle (aggregation etc.)
Ptr< Txop > m_txop
This holds a pointer to the TXOP instance for this WifiMac - used for transmission of frames to non-QoS peers.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Basic MAC of mesh point Wi-Fi interface.
Its function is extendable through plugins mechanism.
Now only three output queues are used:
beacons (PIFS and no backoff),
background traffic,
management and priority traffic.
Config Paths
ns3::MeshWifiInterfaceMac is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Mac/$ns3::RegularWifiMac/$ns3::MeshWifiInterfaceMac"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Mac/$ns3::MeshWifiInterfaceMac"
Attributes
BeaconInterval: Beacon Interval
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +5e+08ns
Flags: construct write read
RandomStart: Window when beacon generating starts (uniform random) in seconds
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +5e+08ns
Flags: construct write read
BeaconGeneration: Enable/Disable Beaconing.
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
Attributes defined in parent class ns3::RegularWifiMac
QosSupported: This Boolean attribute is set to enable 802.11e/WMM-style QoS support at this STA.
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
CtsToSelfSupported: Use CTS to Self when using a rate that is not in the basic rate set.
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write
VO_MaxAmsduSize: Maximum length in bytes of an A-MSDU for AC_VO access class (capped to 7935 for HT PPDUs and 11398 for VHT/HE PPDUs). Value 0 means A-MSDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:11398
Initial value: 0
Flags: construct write read
VI_MaxAmsduSize: Maximum length in bytes of an A-MSDU for AC_VI access class (capped to 7935 for HT PPDUs and 11398 for VHT/HE PPDUs). Value 0 means A-MSDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:11398
Initial value: 0
Flags: construct write read
BE_MaxAmsduSize: Maximum length in bytes of an A-MSDU for AC_BE access class (capped to 7935 for HT PPDUs and 11398 for VHT/HE PPDUs). Value 0 means A-MSDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:11398
Initial value: 0
Flags: construct write read
BK_MaxAmsduSize: Maximum length in bytes of an A-MSDU for AC_BK access class (capped to 7935 for HT PPDUs and 11398 for VHT/HE PPDUs). Value 0 means A-MSDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:11398
Initial value: 0
Flags: construct write read
VO_MaxAmpduSize: Maximum length in bytes of an A-MPDU for AC_VO access class (capped to 65535 for HT PPDUs, 1048575 for VHT PPDUs, and 8388607 for HE PPDUs). Value 0 means A-MPDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 0
Flags: construct write read
VI_MaxAmpduSize: Maximum length in bytes of an A-MPDU for AC_VI access class (capped to 65535 for HT PPDUs, 1048575 for VHT PPDUs, and 8388607 for HE PPDUs). Value 0 means A-MPDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 65535
Flags: construct write read
BE_MaxAmpduSize: Maximum length in bytes of an A-MPDU for AC_BE access class (capped to 65535 for HT PPDUs, 1048575 for VHT PPDUs, and 8388607 for HE PPDUs). Value 0 means A-MPDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 65535
Flags: construct write read
BK_MaxAmpduSize: Maximum length in bytes of an A-MPDU for AC_BK access class (capped to 65535 for HT PPDUs, 1048575 for VHT PPDUs, and 8388607 for HE PPDUs). Value 0 means A-MPDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 0
Flags: construct write read
VO_BlockAckThreshold: If number of packets in VO queue reaches this value, block ack mechanism is used. If this value is 0, block ack is never used.When A-MPDU is enabled, block ack mechanism is used regardless of this value.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:64
Initial value: 0
Flags: construct write
VI_BlockAckThreshold: If number of packets in VI queue reaches this value, block ack mechanism is used. If this value is 0, block ack is never used.When A-MPDU is enabled, block ack mechanism is used regardless of this value.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:64
Initial value: 0
Flags: construct write
BE_BlockAckThreshold: If number of packets in BE queue reaches this value, block ack mechanism is used. If this value is 0, block ack is never used.When A-MPDU is enabled, block ack mechanism is used regardless of this value.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:64
Initial value: 0
Flags: construct write
BK_BlockAckThreshold: If number of packets in BK queue reaches this value, block ack mechanism is used. If this value is 0, block ack is never used.When A-MPDU is enabled, block ack mechanism is used regardless of this value.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:64
Initial value: 0
Flags: construct write
VO_BlockAckInactivityTimeout: Represents max time (blocks of 1024 microseconds) allowed for block ackinactivity for AC_VO. If this value isn't equal to 0 a timer start after that ablock ack setup is completed and will be reset every time that a block ackframe is received. If this value is 0, block ack inactivity timeout won't be used.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 0
Flags: construct write
VI_BlockAckInactivityTimeout: Represents max time (blocks of 1024 microseconds) allowed for block ackinactivity for AC_VI. If this value isn't equal to 0 a timer start after that ablock ack setup is completed and will be reset every time that a block ackframe is received. If this value is 0, block ack inactivity timeout won't be used.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 0
Flags: construct write
BE_BlockAckInactivityTimeout: Represents max time (blocks of 1024 microseconds) allowed for block ackinactivity for AC_BE. If this value isn't equal to 0 a timer start after that ablock ack setup is completed and will be reset every time that a block ackframe is received. If this value is 0, block ack inactivity timeout won't be used.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 0
Flags: construct write
BK_BlockAckInactivityTimeout: Represents max time (blocks of 1024 microseconds) allowed for block ackinactivity for AC_BK. If this value isn't equal to 0 a timer start after that ablock ack setup is completed and will be reset every time that a block ackframe is received. If this value is 0, block ack inactivity timeout won't be used.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 0
Flags: construct write
ShortSlotTimeSupported: Whether or not short slot time is supported (only used by ERP APs or STAs).
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
Txop: The Txop object.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::Txop>
Flags: read
VO_Txop: Queue that manages packets belonging to AC_VO access class.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::QosTxop>
Flags: read
VI_Txop: Queue that manages packets belonging to AC_VI access class.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::QosTxop>
Flags: read
BE_Txop: Queue that manages packets belonging to AC_BE access class.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::QosTxop>
Flags: read
BK_Txop: Queue that manages packets belonging to AC_BK access class.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::QosTxop>
Flags: read
Attributes defined in parent class ns3::WifiMac
Ssid: The ssid we want to belong to.
Set with class: SsidValue
Underlying type: Ssid
Initial value: default
Flags: construct write read
No TraceSources are defined for this type.
TraceSources defined in parent class ns3::RegularWifiMac
TxOkHeader: The header of successfully transmitted packet.
Callback signature: ns3::WifiMacHeader::TracedCallback
TxErrHeader: The header of unsuccessfully transmitted packet.
Callback signature: ns3::WifiMacHeader::TracedCallback
TraceSources defined in parent class ns3::WifiMac
MacTx: A packet has been received from higher layers and is being processed in preparation for queueing for transmission.
Callback signature: ns3::Packet::TracedCallback
MacTxDrop: A packet has been dropped in the MAC layer before transmission.
Callback signature: ns3::Packet::TracedCallback
MacPromiscRx: A packet has been received by this device, has been passed up from the physical layer and is being forwarded up the local protocol stack. This is a promiscuous trace.
Callback signature: ns3::Packet::TracedCallback
MacRx: A packet has been received by this device, has been passed up from the physical layer and is being forwarded up the local protocol stack. This is a non-promiscuous trace.
Callback signature: ns3::Packet::TracedCallback
MacRxDrop: A packet has been dropped in the MAC layer after it has been passed up from the physical layer.
Callback signature: ns3::Packet::TracedCallback
Size of this type is 520 bytes (on a 64-bit architecture).
Definition at line 50 of file mesh-wifi-interface-mac.h.
Member Typedef Documentation
PluginList
typedef std::vector<Ptr<MeshWifiInterfaceMacPlugin> > ns3::MeshWifiInterfaceMac::PluginList private
PluginList typedef.
Definition at line 202 of file mesh-wifi-interface-mac.h.
Constructor & Destructor Documentation
MeshWifiInterfaceMac()
ns3::MeshWifiInterfaceMac::MeshWifiInterfaceMac ()
C-tor.
Definition at line 75 of file mesh-wifi-interface-mac.cc.
References m_coefficient, ns3::MESH, NS_LOG_FUNCTION, and ns3::RegularWifiMac::SetTypeOfStation().
~MeshWifiInterfaceMac()
ns3::MeshWifiInterfaceMac::~MeshWifiInterfaceMac () virtual
D-tor.
Definition at line 84 of file mesh-wifi-interface-mac.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AssignStreams()
int64_t ns3::MeshWifiInterfaceMac::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 149 of file mesh-wifi-interface-mac.cc.
References m_coefficient, m_plugins, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
CheckSupportedRates()
bool ns3::MeshWifiInterfaceMac::CheckSupportedRates (SupportedRates rates) const
Check supported rates.
Parameters
rates
Returns
true if rates are supported
Definition at line 322 of file mesh-wifi-interface-mac.cc.
References ns3::ConvertGuardIntervalToNanoSeconds(), ns3::WifiRemoteStationManager::GetBasicMode(), ns3::WifiPhy::GetChannelWidth(), ns3::WifiMode::GetDataRate(), ns3::WifiPhy::GetDevice(), ns3::WifiRemoteStationManager::GetNBasicModes(), ns3::SupportedRates::IsSupportedRate(), ns3::RegularWifiMac::m_phy, and ns3::RegularWifiMac::m_stationManager.
ConfigureStandard()
void ns3::MeshWifiInterfaceMac::ConfigureStandard (enum WifiStandard standard) virtual
Finish configuration based on the WifiStandard being provided.
Parameters
standard the WifiStandard being configured
Implements ns3::WifiMac.
Definition at line 543 of file mesh-wifi-interface-mac.cc.
References ns3::RegularWifiMac::ConfigureStandard(), m_standard, ns3::RegularWifiMac::m_txop, ns3::Txop::SetAifsn(), ns3::Txop::SetMaxCw(), and ns3::Txop::SetMinCw().
DoDispose()
void ns3::MeshWifiInterfaceMac::DoDispose (void) private virtual
Real d-tor.
Reimplemented from ns3::RegularWifiMac.
Definition at line 120 of file mesh-wifi-interface-mac.cc.
References ns3::EventId::Cancel(), ns3::RegularWifiMac::DoDispose(), m_beaconSendEvent, m_plugins, and NS_LOG_FUNCTION.
DoInitialize()
void ns3::MeshWifiInterfaceMac::DoInitialize (void) private virtual
PluginList typedef.
Reimplemented from ns3::RegularWifiMac.
Definition at line 129 of file mesh-wifi-interface-mac.cc.
References ns3::EventId::Cancel(), ns3::Time::GetSeconds(), ns3::UniformRandomVariable::GetValue(), ns3::EventId::IsRunning(), m_beaconEnable, m_beaconSendEvent, m_coefficient, m_randomStart, m_tbtt, ns3::Simulator::Now(), NS_ASSERT, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), ns3::Seconds(), SendBeacon(), and ns3::ObjectBase::SetAttribute().
Enqueue() [1/2]
void ns3::MeshWifiInterfaceMac::Enqueue (Ptr< Packet > packet, Mac48Address to) virtual
Parameters
packet the packet to send.
to the address to which the packet should be sent.
The packet should be enqueued in a TX queue, and should be dequeued as soon as the DCF function determines that access it granted to this MAC.
Implements ns3::RegularWifiMac.
Definition at line 98 of file mesh-wifi-interface-mac.cc.
References ForwardDown(), ns3::RegularWifiMac::m_low, and NS_LOG_FUNCTION.
Enqueue() [2/2]
void ns3::MeshWifiInterfaceMac::Enqueue (Ptr< Packet > packet, Mac48Address to, Mac48Address from) virtual
Parameters
packet the packet to send.
to the address to which the packet should be sent.
from the address from which the packet should be sent.
The packet should be enqueued in a TX queue, and should be dequeued as soon as the DCF function determines that access it granted to this MAC. The extra parameter "from" allows this device to operate in a bridged mode, forwarding received frames without altering the source address.
Reimplemented from ns3::RegularWifiMac.
Definition at line 92 of file mesh-wifi-interface-mac.cc.
References ForwardDown(), and NS_LOG_FUNCTION.
ForwardDown()
void ns3::MeshWifiInterfaceMac::ForwardDown (Ptr< Packet > packet, Mac48Address from, Mac48Address to) private
Send frame.
Frame is supposed to be tagged by routing information.
Parameters
packet the packet to forward
from the from address
to the to address
Definition at line 207 of file mesh-wifi-interface-mac.cc.
References ns3::AC_BE, ns3::WifiRemoteStationManager::AddSupportedMode(), ns3::WifiMacHeader::GetAddr1(), ns3::RegularWifiMac::GetAddress(), ns3::WifiPhy::GetMode(), ns3::WifiPhy::GetNModes(), ns3::SocketPriorityTag::GetPriority(), ns3::Packet::GetSize(), ns3::WifiRemoteStationManager::IsBrandNew(), ns3::RegularWifiMac::m_edca, ns3::RegularWifiMac::m_phy, m_plugins, ns3::RegularWifiMac::m_stationManager, m_stats, ns3::WifiMacHeader::NORMAL_ACK, NS_ASSERT, ns3::QosUtilsMapTidToAc(), ns3::WifiRemoteStationManager::RecordDisassociated(), ns3::Packet::RemovePacketTag(), ns3::MeshWifiInterfaceMac::Statistics::sentBytes, ns3::MeshWifiInterfaceMac::Statistics::sentFrames, ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetAddr2(), ns3::WifiMacHeader::SetAddr3(), ns3::WifiMacHeader::SetAddr4(), ns3::WifiMacHeader::SetDsFrom(), ns3::WifiMacHeader::SetDsTo(), ns3::WifiMacHeader::SetQosAckPolicy(), ns3::WifiMacHeader::SetQosNoAmsdu(), ns3::WifiMacHeader::SetQosNoEosp(), ns3::WifiMacHeader::SetQosTid(), ns3::WifiMacHeader::SetQosTxopLimit(), ns3::WifiMacHeader::SetType(), and ns3::WIFI_MAC_QOSDATA.
Referenced by Enqueue().
GetBeaconGeneration()
bool ns3::MeshWifiInterfaceMac::GetBeaconGeneration () const private
Get current beaconing status.
Returns
true if beacon active
Definition at line 362 of file mesh-wifi-interface-mac.cc.
References ns3::EventId::IsRunning(), and m_beaconSendEvent.
Referenced by GetTypeId().
GetBeaconInterval()
Time ns3::MeshWifiInterfaceMac::GetBeaconInterval () const
Returns
interval between two beacons
Definition at line 351 of file mesh-wifi-interface-mac.cc.
References m_beaconInterval.
Referenced by Report(), and ScheduleNextBeacon().
GetFrequencyChannel()
uint16_t ns3::MeshWifiInterfaceMac::GetFrequencyChannel () const
Current channel Id.
Returns
the frequency channel
Definition at line 176 of file mesh-wifi-interface-mac.cc.
References ns3::WifiPhy::GetChannelNumber(), ns3::RegularWifiMac::m_phy, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by Report().
GetLinkMetric()
uint32_t ns3::MeshWifiInterfaceMac::GetLinkMetric (Mac48Address peerAddress)
PluginList typedef.
Definition at line 482 of file mesh-wifi-interface-mac.cc.
References m_linkMetricCallback.
GetMeshPointAddress()
Mac48Address ns3::MeshWifiInterfaceMac::GetMeshPointAddress () const
Definition at line 502 of file mesh-wifi-interface-mac.cc.
References m_mpAddress.
Referenced by SendBeacon().
GetSupportedRates()
SupportedRates ns3::MeshWifiInterfaceMac::GetSupportedRates () const
Returns
list of supported bitrates
Definition at line 301 of file mesh-wifi-interface-mac.cc.
References ns3::SupportedRates::AddSupportedRate(), ns3::ConvertGuardIntervalToNanoSeconds(), ns3::WifiRemoteStationManager::GetBasicMode(), ns3::WifiPhy::GetChannelWidth(), ns3::WifiMode::GetDataRate(), ns3::WifiPhy::GetDevice(), ns3::WifiPhy::GetMode(), ns3::WifiRemoteStationManager::GetNBasicModes(), ns3::WifiPhy::GetNModes(), ns3::RegularWifiMac::m_phy, ns3::RegularWifiMac::m_stationManager, and ns3::SupportedRates::SetBasicRate().
Referenced by SendBeacon().
GetTbtt()
Time ns3::MeshWifiInterfaceMac::GetTbtt () const
Next beacon frame time.
Returns
TBTT time
This is supposed to be used by any entity managing beacon collision avoidance (e.g. Peer management protocol in 802.11s)
Definition at line 367 of file mesh-wifi-interface-mac.cc.
References m_tbtt.
Referenced by ShiftTbtt().
GetTypeId()
TypeId ns3::MeshWifiInterfaceMac::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 44 of file mesh-wifi-interface-mac.cc.
References GetBeaconGeneration(), m_beaconInterval, m_randomStart, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::Seconds(), SetBeaconGeneration(), and ns3::TypeId::SetParent().
InstallPlugin()
void ns3::MeshWifiInterfaceMac::InstallPlugin (Ptr< MeshWifiInterfaceMacPlugin > plugin)
Install plugin.
Parameters
plugin
Todo:
return unique ID to allow user to unregister plugins
Definition at line 165 of file mesh-wifi-interface-mac.cc.
References m_plugins, NS_LOG_FUNCTION, and ns3::MeshWifiInterfaceMacPlugin::SetParent().
Receive()
void ns3::MeshWifiInterfaceMac::Receive (Ptr< WifiMacQueueItem > mpdu) private virtual
Frame receive handler.
Parameters
mpdu the received MPDU
Reimplemented from ns3::RegularWifiMac.
Definition at line 410 of file mesh-wifi-interface-mac.cc.
References ns3::WifiRemoteStationManager::AddBasicMode(), ns3::WifiRemoteStationManager::AddSupportedMode(), ns3::ConvertGuardIntervalToNanoSeconds(), ns3::RegularWifiMac::ForwardUp(), ns3::WifiMacHeader::GetAddr1(), ns3::WifiMacHeader::GetAddr2(), ns3::WifiMacHeader::GetAddr3(), ns3::WifiMacHeader::GetAddr4(), ns3::RegularWifiMac::GetAddress(), ns3::Mac48Address::GetBroadcast(), ns3::WifiPhy::GetChannelWidth(), ns3::WifiMode::GetDataRate(), ns3::WifiPhy::GetDevice(), ns3::WifiPhy::GetMode(), ns3::WifiPhy::GetNModes(), ns3::WifiMacHeader::GetQosTid(), ns3::Packet::GetSize(), ns3::MgtProbeResponseHeader::GetSsid(), ns3::RegularWifiMac::GetSsid(), ns3::MgtProbeResponseHeader::GetSupportedRates(), ns3::SupportedRates::IsBasicRate(), ns3::WifiMacHeader::IsBeacon(), ns3::WifiMacHeader::IsData(), ns3::Ssid::IsEqual(), ns3::WifiMacHeader::IsQosData(), ns3::SupportedRates::IsSupportedRate(), ns3::RegularWifiMac::m_phy, m_plugins, ns3::RegularWifiMac::m_stationManager, m_stats, ns3::Simulator::Now(), NS_LOG_DEBUG, ns3::Packet::PeekHeader(), ns3::MeshWifiInterfaceMac::Statistics::recvBeacons, ns3::MeshWifiInterfaceMac::Statistics::recvBytes, ns3::MeshWifiInterfaceMac::Statistics::recvFrames, ns3::Packet::ReplacePacketTag(), and ns3::SocketPriorityTag::SetPriority().
Report()
void ns3::MeshWifiInterfaceMac::Report (std::ostream & os) const
Statistics:
Definition at line 527 of file mesh-wifi-interface-mac.cc.
References ns3::RegularWifiMac::GetAddress(), GetBeaconInterval(), GetFrequencyChannel(), ns3::Time::GetSeconds(), m_stats, and ns3::MeshWifiInterfaceMac::Statistics::Print().
ResetStats()
void ns3::MeshWifiInterfaceMac::ResetStats ()
Reset statistics.
Definition at line 537 of file mesh-wifi-interface-mac.cc.
References m_stats.
ScheduleNextBeacon()
void ns3::MeshWifiInterfaceMac::ScheduleNextBeacon () private
Schedule next beacon.
Definition at line 384 of file mesh-wifi-interface-mac.cc.
References GetBeaconInterval(), m_beaconSendEvent, m_tbtt, ns3::Simulator::Schedule(), and SendBeacon().
Referenced by SendBeacon().
SendBeacon()
void ns3::MeshWifiInterfaceMac::SendBeacon () private
Send beacon.
Definition at line 390 of file mesh-wifi-interface-mac.cc.
References ns3::MeshWifiBeacon::CreateHeader(), ns3::MeshWifiBeacon::CreatePacket(), ns3::RegularWifiMac::GetAddress(), GetMeshPointAddress(), ns3::Time::GetMicroSeconds(), ns3::RegularWifiMac::GetSsid(), GetSupportedRates(), ns3::EventId::IsRunning(), m_beaconInterval, m_beaconSendEvent, m_plugins, ns3::RegularWifiMac::m_txop, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Txop::Queue(), and ScheduleNextBeacon().
Referenced by DoInitialize(), ScheduleNextBeacon(), and ShiftTbtt().
SendManagementFrame()
void ns3::MeshWifiInterfaceMac::SendManagementFrame (Ptr< Packet > frame, const WifiMacHeader & hdr)
To be used by plugins sending management frames.
Parameters
frame the management frame
hdr the wifi MAC header
Definition at line 265 of file mesh-wifi-interface-mac.cc.
References ns3::AC_BK, ns3::AC_VO, ns3::WifiMacHeader::GetAddr1(), ns3::Mac48Address::GetBroadcast(), ns3::Packet::GetSize(), ns3::RegularWifiMac::m_edca, m_plugins, m_stats, NS_FATAL_ERROR, ns3::MeshWifiInterfaceMac::Statistics::sentBytes, and ns3::MeshWifiInterfaceMac::Statistics::sentFrames.
SetBeaconGeneration()
void ns3::MeshWifiInterfaceMac::SetBeaconGeneration (bool enable)
Enable/disable beacons.
Parameters
enable enable / disable flag
Definition at line 356 of file mesh-wifi-interface-mac.cc.
References m_beaconEnable, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetBeaconInterval()
void ns3::MeshWifiInterfaceMac::SetBeaconInterval (Time interval)
Set interval between two successive beacons.
Definition at line 345 of file mesh-wifi-interface-mac.cc.
References m_beaconInterval, and NS_LOG_FUNCTION.
SetLinkMetricCallback()
void ns3::MeshWifiInterfaceMac::SetLinkMetricCallback (Callback< uint32_t, Mac48Address, Ptr< MeshWifiInterfaceMac > > cb)
PluginList typedef.
Definition at line 492 of file mesh-wifi-interface-mac.cc.
References m_linkMetricCallback.
SetLinkUpCallback()
void ns3::MeshWifiInterfaceMac::SetLinkUpCallback (Callback< void > linkUp) virtual
Parameters
linkUp the callback to invoke when the link becomes up.
Implements ns3::WifiMac.
Definition at line 109 of file mesh-wifi-interface-mac.cc.
References NS_LOG_FUNCTION, and ns3::RegularWifiMac::SetLinkUpCallback().
SetMeshPointAddress()
void ns3::MeshWifiInterfaceMac::SetMeshPointAddress (Mac48Address a)
Definition at line 497 of file mesh-wifi-interface-mac.cc.
References m_mpAddress.
SetRandomStartDelay()
void ns3::MeshWifiInterfaceMac::SetRandomStartDelay (Time interval)
Set maximum initial random delay before first beacon.
Definition at line 339 of file mesh-wifi-interface-mac.cc.
References m_randomStart, and NS_LOG_FUNCTION.
ShiftTbtt()
void ns3::MeshWifiInterfaceMac::ShiftTbtt (Time shift)
Shift TBTT.
Parameters
shift This is supposed to be used by any entity managing beacon collision avoidance (e.g. Peer management protocol in 802.11s)
Attention
User of ShiftTbtt () must take care to not shift it to the past.
Definition at line 372 of file mesh-wifi-interface-mac.cc.
References ns3::Simulator::Cancel(), GetTbtt(), m_beaconSendEvent, m_tbtt, ns3::Simulator::Now(), NS_ASSERT, ns3::Simulator::Schedule(), and SendBeacon().
SupportsSendFrom()
bool ns3::MeshWifiInterfaceMac::SupportsSendFrom () const virtual
Returns
if this MAC supports sending from arbitrary address.
The interface may or may not support sending from arbitrary address. This function returns true if sending from arbitrary address is supported, false otherwise.
Reimplemented from ns3::RegularWifiMac.
Definition at line 104 of file mesh-wifi-interface-mac.cc.
SwitchFrequencyChannel()
void ns3::MeshWifiInterfaceMac::SwitchFrequencyChannel (uint16_t new_id)
Switch frequency channel.
Parameters
new_id
Todo:
Correct channel switching is:
Interface down, e.g. to stop packets from layer 3
Wait before all output queues will be empty
Switch PHY channel
Interface up
Now we use dirty channel switch – just change frequency
Definition at line 184 of file mesh-wifi-interface-mac.cc.
References ns3::RegularWifiMac::m_channelAccessManager, ns3::RegularWifiMac::m_phy, ns3::ChannelAccessManager::NotifyNavResetNow(), NS_ASSERT, NS_LOG_FUNCTION, ns3::Seconds(), and ns3::WifiPhy::SetChannelNumber().
Member Data Documentation
m_beaconEnable
bool ns3::MeshWifiInterfaceMac::m_beaconEnable private
whether beaconing is enabled
Definition at line 209 of file mesh-wifi-interface-mac.h.
Referenced by DoInitialize(), and SetBeaconGeneration().
m_beaconInterval
Time ns3::MeshWifiInterfaceMac::m_beaconInterval private
Beaconing interval.
Definition at line 211 of file mesh-wifi-interface-mac.h.
Referenced by GetBeaconInterval(), GetTypeId(), SendBeacon(), and SetBeaconInterval().
m_beaconSendEvent
EventId ns3::MeshWifiInterfaceMac::m_beaconSendEvent private
"Timer" for the next beacon
Definition at line 222 of file mesh-wifi-interface-mac.h.
Referenced by DoDispose(), DoInitialize(), GetBeaconGeneration(), ScheduleNextBeacon(), SendBeacon(), and ShiftTbtt().
m_coefficient
Ptr<UniformRandomVariable> ns3::MeshWifiInterfaceMac::m_coefficient private
Add randomness to beacon generation.
Definition at line 249 of file mesh-wifi-interface-mac.h.
Referenced by MeshWifiInterfaceMac(), AssignStreams(), and DoInitialize().
m_linkMetricCallback
Callback<uint32_t, Mac48Address, Ptr<MeshWifiInterfaceMac> > ns3::MeshWifiInterfaceMac::m_linkMetricCallback private
linkMetricCallback
Definition at line 225 of file mesh-wifi-interface-mac.h.
Referenced by GetLinkMetric(), and SetLinkMetricCallback().
m_mpAddress
Mac48Address ns3::MeshWifiInterfaceMac::m_mpAddress private
Mesh point address.
Definition at line 219 of file mesh-wifi-interface-mac.h.
Referenced by GetMeshPointAddress(), and SetMeshPointAddress().
m_plugins
PluginList ns3::MeshWifiInterfaceMac::m_plugins private
List of all installed plugins.
Definition at line 224 of file mesh-wifi-interface-mac.h.
Referenced by AssignStreams(), DoDispose(), ForwardDown(), InstallPlugin(), Receive(), SendBeacon(), and SendManagementFrame().
m_randomStart
Time ns3::MeshWifiInterfaceMac::m_randomStart private
Maximum delay before first beacon.
Definition at line 213 of file mesh-wifi-interface-mac.h.
Referenced by DoInitialize(), GetTypeId(), and SetRandomStartDelay().
m_standard
WifiStandard ns3::MeshWifiInterfaceMac::m_standard private
Current standard: needed to configure metric.
Definition at line 246 of file mesh-wifi-interface-mac.h.
Referenced by ConfigureStandard().
m_stats
Statistics ns3::MeshWifiInterfaceMac::m_stats private
statistics
Definition at line 243 of file mesh-wifi-interface-mac.h.
Referenced by ForwardDown(), Receive(), Report(), ResetStats(), and SendManagementFrame().
m_tbtt
Time ns3::MeshWifiInterfaceMac::m_tbtt private
Time for the next frame.
Definition at line 215 of file mesh-wifi-interface-mac.h.
Referenced by DoInitialize(), GetTbtt(), ScheduleNextBeacon(), and ShiftTbtt().
The documentation for this class was generated from the following files:
src/mesh/model/mesh-wifi-interface-mac.h
src/mesh/model/mesh-wifi-interface-mac.cc