ns-3: ns3::CobaltQueueDisc Class Reference
ns3::CobaltQueueDisc Class Reference
Traffic-control
Cobalt packet queue disc.
#include "cobalt-queue-disc.h"
Public Member Functions
CobaltQueueDisc ()
CobaltQueueDisc Constructor.
virtual ~CobaltQueueDisc ()
Destructor.
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
int64_t GetDropNext (void)
Get the time for next packet drop while in the dropping state.
Time GetInterval (void)
Get the interval.
double GetPdrop ()
Get the drop probability of Blue.
Time GetTarget (void)
Get the target queue delay.
int64_t Time2CoDel (Time t)
Return the unsigned 32-bit integer representation of the input Time object.
Public Member Functions inherited from ns3::QueueDisc
QueueDisc (QueueDiscSizePolicy policy, QueueSizeUnit unit)
Constructor.
QueueDisc (QueueDiscSizePolicy policy=QueueDiscSizePolicy::SINGLE_INTERNAL_QUEUE)
Constructor.
virtual ~QueueDisc ()
void AddInternalQueue (Ptr< InternalQueue > queue)
Add an internal queue to the tail of the list of queues.
void AddPacketFilter (Ptr< PacketFilter > filter)
Add a packet filter to the tail of the list of filters used to classify packets.
void AddQueueDiscClass (Ptr< QueueDiscClass > qdClass)
Add a queue disc class to the tail of the list of classes.
int32_t Classify (Ptr< QueueDiscItem > item)
Classify a packet by calling the packet filters, one at a time, until either a filter able to classify the packet is found or all the filters have been processed.
Ptr< QueueDiscItem > Dequeue (void)
Extract from the queue disc the packet that has been dequeued by calling Peek, if any, or call the private DoDequeue method (which must be implemented by derived classes) to dequeue a packet, otherwise.
bool Enqueue (Ptr< QueueDiscItem > item)
Pass a packet to store to the queue discipline.
QueueSize GetCurrentSize (void)
Get the current size of the queue disc in bytes, if operating in bytes mode, or packets, otherwise.
Ptr< InternalQueue > GetInternalQueue (std::size_t i) const
Get the i-th internal queue.
QueueSize GetMaxSize (void) const
Get the maximum size of the queue disc.
uint32_t GetNBytes (void) const
Get the amount of bytes stored by the queue disc.
Ptr< NetDeviceQueueInterface > GetNetDeviceQueueInterface (void) const
std::size_t GetNInternalQueues (void) const
Get the number of internal queues.
std::size_t GetNPacketFilters (void) const
Get the number of packet filters.
uint32_t GetNPackets (void) const
Get the number of packets stored by the queue disc.
std::size_t GetNQueueDiscClasses (void) const
Get the number of queue disc classes.
Ptr< PacketFilter > GetPacketFilter (std::size_t i) const
Get the i-th packet filter.
Ptr< QueueDiscClass > GetQueueDiscClass (std::size_t i) const
Get the i-th queue disc class.
virtual uint32_t GetQuota (void) const
Get the maximum number of dequeue operations following a packet enqueue.
SendCallback GetSendCallback (void) const
const Stats & GetStats (void)
Retrieve all the collected statistics.
virtual WakeMode GetWakeMode (void) const
When setting up the wake callbacks on the netdevice queues, it is necessary to determine which queue disc (the root queue disc or one of its children) should be activated when the netdevice wakes one of its transmission queues.
Ptr< const QueueDiscItem > Peek (void)
Get a copy of the next packet the queue discipline will extract.
void Run (void)
Modelled after the Linux function __qdisc_run (net/sched/sch_generic.c) Dequeues multiple packets, until a quota is exceeded or sending a packet to the device failed.
bool SetMaxSize (QueueSize size)
Set the maximum size of the queue disc.
void SetNetDeviceQueueInterface (Ptr< NetDeviceQueueInterface > ndqi)
virtual void SetQuota (const uint32_t quota)
Set the maximum number of dequeue operations following a packet enqueue.
void SetSendCallback (SendCallback func)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::QueueDisc
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static constexpr const char * FORCED_MARK = "forcedMark"
forced marks by Codel on ECN-enabled
static constexpr const char * OVERLIMIT_DROP = "Overlimit drop"
Overlimit dropped packet.
static constexpr const char * TARGET_EXCEEDED_DROP = "Target exceeded drop"
Sojourn time above target.
Static Public Attributes inherited from ns3::QueueDisc
static constexpr const char * CHILD_QUEUE_DISC_DROP = "(Dropped by child queue disc) "
Packet dropped by a child queue disc.
static constexpr const char * CHILD_QUEUE_DISC_MARK = "(Marked by child queue disc) "
Packet marked by a child queue disc.
static constexpr const char * INTERNAL_QUEUE_DROP = "Dropped by internal queue"
Packet dropped by an internal queue.
Protected Member Functions
virtual void DoDispose (void)
Dispose of the object.
Protected Member Functions inherited from ns3::QueueDisc
void DoInitialize (void)
Check whether the configuration is correct and initialize parameters.
void DropAfterDequeue (Ptr< const QueueDiscItem > item, const char *reason)
Perform the actions required when the queue disc is notified of a packet dropped after dequeue.
void DropBeforeEnqueue (Ptr< const QueueDiscItem > item, const char *reason)
Perform the actions required when the queue disc is notified of a packet dropped before enqueue.
bool Mark (Ptr< QueueDiscItem > item, const char *reason)
Marks the given packet and, if successful, updates the counters associated with the given reason.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void CacheInit (void)
There is a big difference in timing between the accurate values placed in the cache and the approximations given by a single Newton step for small count values, particularly when stepping from count 1 to 2 or vice versa.
virtual bool CheckConfig (void)
Check whether the current configuration is correct.
void CobaltQueueEmpty (int64_t now)
Called when the queue becomes empty to alter the drop probabilities of Blue.
void CobaltQueueFull (int64_t now)
Called when the queue becomes full to alter the drop probabilities of Blue.
bool CobaltShouldDrop (Ptr< QueueDiscItem > item, int64_t now)
Called to decide whether the current packet should be dropped based on decisions taken by Blue and Codel working parallely Returns true if the packet should be dropped, false otherwise.
bool CoDelTimeAfter (int64_t a, int64_t b)
Check if CoDel time a is successive to b.
bool CoDelTimeAfterEq (int64_t a, int64_t b)
Check if CoDel time a is successive or equal to b.
int64_t ControlLaw (int64_t t)
Determine the time for next drop CoDel control law is t + m_interval/sqrt(m_count).
virtual Ptr< QueueDiscItem > DoDequeue (void)
This function actually extracts a packet from the queue disc.
virtual bool DoEnqueue (Ptr< QueueDiscItem > item)
This function actually enqueues a packet into the queue disc.
virtual Ptr< const QueueDiscItem > DoPeek (void)
Return a copy of the next packet the queue disc will extract.
virtual void InitializeParams (void)
Initialize the queue parameters.
void InvSqrt (void)
void NewtonStep (void)
Calculate the reciprocal square root of m_count by using Newton's method http://en.wikipedia.org/wiki/Methods_of_computing_square_roots#Iterative_methods_for_reciprocal_square_roots m_recInvSqrt (new) = (m_recInvSqrt (old) / 2) * (3 - m_count * m_recInvSqrt^2)
Private Attributes
TracedValue< uint32_t > m_count
Number of packets dropped since entering drop state.
double m_decrement
decrement value for marking probability
TracedValue< int64_t > m_dropNext
Time to drop next packet.
TracedValue< bool > m_dropping
True if in dropping state.
double m_increment
increment value for marking probability
Time m_interval
100 ms sliding minimum time window width
uint32_t m_lastUpdateTimeBlue
Blue's last update time for drop probability.
double m_Pdrop
Drop Probability.
uint32_t m_recInvSqrt
Reciprocal inverse square root.
uint32_t m_recInvSqrtCache [REC_INV_SQRT_CACHE] = {0}
Cache to maintain some initial values of InvSqrt.
Stats m_stats
Cobalt statistics.
Time m_target
5 ms target queue delay
bool m_useEcn
True if ECN is used (packets are marked instead of being dropped)
Ptr< UniformRandomVariable > m_uv
Rng stream.
Additional Inherited Members
Public Types inherited from ns3::QueueDisc
typedef Queue< QueueDiscItem > InternalQueue
Internal queues store QueueDiscItem objects.
typedef std::function< void(Ptr< QueueDiscItem >)> SendCallback
Callback invoked to send a packet to the receiving object when Run is called.
enum WakeMode { WAKE_ROOT = 0x00 , WAKE_CHILD = 0x01 }
Used to determine whether the queue disc itself or its children must be activated when a netdevice wakes a transmission queue.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Cobalt packet queue disc.
Introspection did not find any typical Config paths.
Cobalt uses CoDel and BLUE algorithms in parallel, in order to obtain the best features of each. CoDel is excellent on flows which respond to congestion signals in a TCP-like way. BLUE is far more effective on unresponsive flows.
Attributes
MaxSize: The maximum number of packets/bytes accepted by this queue disc.
Set with class: QueueSizeValue
Underlying type: QueueSize
Initial value: 1500000B
Flags: construct write read
Interval: The Cobalt algorithm interval
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: 100ms
Flags: construct write read
Target: The Cobalt algorithm target queue delay
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: 5ms
Flags: construct write read
UseEcn: True to use ECN (packets are marked instead of being dropped)
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
Pdrop: Marking Probability
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0
Flags: construct write read
Increment: Pdrop increment value
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0.00390625
Flags: construct write read
Decrement: Pdrop decrement Value
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0.000244141
Flags: construct write read
Attributes defined in parent class ns3::QueueDisc
Quota: The maximum number of packets dequeued in a qdisc run
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 64
Flags: construct write read
InternalQueueList: The list of internal queues.
Set with class: ns3::ObjectPtrContainerValue
Underlying type: ns3::Ptr< ns3::Queue<QueueDiscItem>>
Flags: read
PacketFilterList: The list of packet filters.
Set with class: ns3::ObjectPtrContainerValue
Underlying type: ns3::Ptr< ns3::PacketFilter>
Flags: read
QueueDiscClassList: The list of queue disc classes.
Set with class: ns3::ObjectPtrContainerValue
Underlying type: ns3::Ptr< ns3::QueueDiscClass>
Flags: read
TraceSources
Count: Cobalt count
Callback signature: ns3::TracedValueCallback::Uint32
DropState: Dropping state
Callback signature: ns3::TracedValueCallback::Bool
DropNext: Time until next packet drop
Callback signature: ns3::TracedValueCallback::Uint32
TraceSources defined in parent class ns3::QueueDisc
Enqueue: Enqueue a packet in the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
Dequeue: Dequeue a packet from the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
Requeue: Requeue a packet in the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
Drop: Drop a packet stored in the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
DropBeforeEnqueue: Drop a packet before enqueue
Callback signature: ns3::QueueDiscItem::TracedCallback
DropAfterDequeue: Drop a packet after dequeue
Callback signature: ns3::QueueDiscItem::TracedCallback
Mark: Mark a packet stored in the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
PacketsInQueue: Number of packets currently stored in the queue disc
Callback signature: ns3::TracedValueCallback::Uint32
BytesInQueue: Number of bytes currently stored in the queue disc
Callback signature: ns3::TracedValueCallback::Uint32
SojournTime: Sojourn time of the last packet dequeued from the queue disc
Callback signature: ns3::Time::TracedCallback
Size of this type is 1552 bytes (on a 64-bit architecture).
Definition at line 59 of file cobalt-queue-disc.h.
Constructor & Destructor Documentation
CobaltQueueDisc()
ns3::CobaltQueueDisc::CobaltQueueDisc ()
CobaltQueueDisc Constructor.
Create a Cobalt queue disc
Definition at line 139 of file cobalt-queue-disc.cc.
References InitializeParams(), m_uv, and NS_LOG_FUNCTION.
~CobaltQueueDisc()
ns3::CobaltQueueDisc::~CobaltQueueDisc () virtual
Destructor.
Destructor
Definition at line 152 of file cobalt-queue-disc.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AssignStreams()
int64_t ns3::CobaltQueueDisc::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 158 of file cobalt-queue-disc.cc.
References m_uv, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
CacheInit()
void ns3::CobaltQueueDisc::CacheInit (void) private
There is a big difference in timing between the accurate values placed in the cache and the approximations given by a single Newton step for small count values, particularly when stepping from count 1 to 2 or vice versa.
Above 16, a single Newton step gives sufficient accuracy in either direction, given the precision stored.
The magnitude of the error when stepping up to count 2 is such as to give the value that should have been produced at count 4.
Definition at line 229 of file cobalt-queue-disc.cc.
References m_count, m_recInvSqrt, m_recInvSqrtCache, NewtonStep(), and REC_INV_SQRT_CACHE.
Referenced by InitializeParams().
CheckConfig()
bool ns3::CobaltQueueDisc::CheckConfig (void) private virtual
Check whether the current configuration is correct.
Default objects (such as internal queues) might be created by this method to ensure the configuration is correct. This method is automatically called at simulation initialization time, and it is called before the InitializeParams () method. It is appropriate to promote parameter initialization to this method if it aids in checking for correct configuration.
See also
QueueDisc::InitializeParams
Returns
true if the configuration is correct, false otherwise
Implements ns3::QueueDisc.
Definition at line 291 of file cobalt-queue-disc.cc.
References ns3::QueueDisc::AddInternalQueue(), ns3::CreateObjectWithAttributes(), ns3::QueueDisc::GetMaxSize(), ns3::QueueDisc::GetNInternalQueues(), ns3::QueueDisc::GetNPacketFilters(), ns3::QueueDisc::GetNQueueDiscClasses(), NS_LOG_ERROR, and NS_LOG_FUNCTION.
CobaltQueueEmpty()
void ns3::CobaltQueueDisc::CobaltQueueEmpty (int64_t now) private
Called when the queue becomes empty to alter the drop probabilities of Blue.
Definition at line 408 of file cobalt-queue-disc.cc.
References CoDelTimeAfter(), CoDelTimeAfterEq(), ControlLaw(), InvSqrt(), m_count, m_decrement, m_dropNext, m_dropping, m_lastUpdateTimeBlue, m_Pdrop, m_target, ns3::max(), NS_LOG_FUNCTION, and Time2CoDel().
Referenced by DoDequeue().
CobaltQueueFull()
void ns3::CobaltQueueDisc::CobaltQueueFull (int64_t now) private
Called when the queue becomes full to alter the drop probabilities of Blue.
Definition at line 389 of file cobalt-queue-disc.cc.
References CoDelTimeAfter(), m_count, m_dropNext, m_dropping, m_increment, m_lastUpdateTimeBlue, m_Pdrop, m_target, ns3::min(), NS_LOG_FUNCTION, NS_LOG_LOGIC, and Time2CoDel().
Referenced by DoEnqueue().
CobaltShouldDrop()
bool ns3::CobaltQueueDisc::CobaltShouldDrop (Ptr< QueueDiscItem > item, int64_t now) private
Called to decide whether the current packet should be dropped based on decisions taken by Blue and Codel working parallely Returns true if the packet should be dropped, false otherwise.
Definition at line 427 of file cobalt-queue-disc.cc.
References ns3::Time::As(), CoDelTimeAfter(), ControlLaw(), FORCED_MARK, ns3::UniformRandomVariable::GetValue(), InvSqrt(), m_count, m_dropNext, m_dropping, m_interval, m_Pdrop, m_target, m_useEcn, m_uv, ns3::QueueDisc::Mark(), ns3::max(), ns3::Simulator::Now(), NS_LOG_FUNCTION, NS_LOG_INFO, ns3::Time::S, and Time2CoDel().
Referenced by DoDequeue().
CoDelTimeAfter()
bool ns3::CobaltQueueDisc::CoDelTimeAfter (int64_t a, int64_t b) private
Check if CoDel time a is successive to b.
Parameters
a left operand
b right operand
Returns
true if a is greater than b
Definition at line 180 of file cobalt-queue-disc.cc.
Referenced by CobaltQueueEmpty(), CobaltQueueFull(), and CobaltShouldDrop().
CoDelTimeAfterEq()
bool ns3::CobaltQueueDisc::CoDelTimeAfterEq (int64_t a, int64_t b) private
Check if CoDel time a is successive or equal to b.
Parameters
a left operand
b right operand
Returns
true if a is greater than or equal to b
Definition at line 186 of file cobalt-queue-disc.cc.
Referenced by CobaltQueueEmpty().
ControlLaw()
int64_t ns3::CobaltQueueDisc::ControlLaw (int64_t t) private
Determine the time for next drop CoDel control law is t + m_interval/sqrt(m_count).
Here, we use m_recInvSqrt calculated by Newton's method in NewtonStep() to avoid both sqrt() and divide operations
Parameters
t Current next drop time
Returns
The new next drop time:
Definition at line 258 of file cobalt-queue-disc.cc.
References m_interval, m_recInvSqrt, NS_LOG_FUNCTION, ns3::ReciprocalDivide(), and Time2CoDel().
Referenced by CobaltQueueEmpty(), and CobaltShouldDrop().
DoDequeue()
Ptr< QueueDiscItem > ns3::CobaltQueueDisc::DoDequeue (void) private virtual
This function actually extracts a packet from the queue disc.
Returns
0 if the operation was not successful; the item otherwise.
Implements ns3::QueueDisc.
Definition at line 349 of file cobalt-queue-disc.cc.
References CobaltQueueEmpty(), CobaltShouldDrop(), ns3::CoDelGetTime(), ns3::QueueDisc::DropAfterDequeue(), ns3::QueueDisc::GetInternalQueue(), ns3::QueueDisc::GetNBytes(), ns3::QueueDisc::GetNPackets(), m_dropping, NS_LOG_FUNCTION, NS_LOG_LOGIC, and TARGET_EXCEEDED_DROP.
DoDispose()
void ns3::CobaltQueueDisc::DoDispose (void) protected virtual
Dispose of the object.
Reimplemented from ns3::QueueDisc.
Definition at line 265 of file cobalt-queue-disc.cc.
References ns3::QueueDisc::DoDispose(), m_uv, and NS_LOG_FUNCTION.
DoEnqueue()
bool ns3::CobaltQueueDisc::DoEnqueue (Ptr< QueueDiscItem > item) private virtual
This function actually enqueues a packet into the queue disc.
Parameters
item item to enqueue
Returns
True if the operation was successful; false otherwise
Implements ns3::QueueDisc.
Definition at line 323 of file cobalt-queue-disc.cc.
References CobaltQueueFull(), ns3::CoDelGetTime(), ns3::QueueDisc::DropBeforeEnqueue(), ns3::QueueDisc::GetCurrentSize(), ns3::QueueDisc::GetInternalQueue(), ns3::QueueDisc::GetMaxSize(), ns3::QueueDisc::GetNBytes(), ns3::QueueDisc::GetNPackets(), NS_LOG_FUNCTION, NS_LOG_LOGIC, and OVERLIMIT_DROP.
DoPeek()
Ptr< const QueueDiscItem > ns3::CobaltQueueDisc::DoPeek (void) private virtual
Return a copy of the next packet the queue disc will extract.
The implementation of this method is based on the qdisc_peek_dequeued function of the Linux kernel, which dequeues a packet and retains it in the queue disc as a requeued packet. The packet is not traced as requeued, nor is the total count of requeued packets increased. The packet is still considered to be part of the queue disc and the dequeue trace is fired when Dequeue is called and the packet is actually extracted from the queue disc.
This approach is especially recommended for queue discs for which it is not obvious what is the next packet that will be dequeued (e.g., queue discs having multiple internal queues or child queue discs or queue discs that drop packets after dequeue). Subclasses can however provide their own implementation of this method that overrides the default one.
Returns
0 if the operation was not successful; the packet otherwise.
Reimplemented from ns3::QueueDisc.
Definition at line 273 of file cobalt-queue-disc.cc.
References ns3::QueueDisc::GetInternalQueue(), ns3::QueueDisc::GetNBytes(), ns3::QueueDisc::GetNPackets(), NS_LOG_FUNCTION, and NS_LOG_LOGIC.
GetDropNext()
int64_t ns3::CobaltQueueDisc::GetDropNext (void)
Get the time for next packet drop while in the dropping state.
Returns
The time for next packet drop
Definition at line 210 of file cobalt-queue-disc.cc.
References m_dropNext.
GetInterval()
Time ns3::CobaltQueueDisc::GetInterval (void)
Get the interval.
Returns
The interval
Definition at line 204 of file cobalt-queue-disc.cc.
References m_interval.
GetPdrop()
double ns3::CobaltQueueDisc::GetPdrop ()
Get the drop probability of Blue.
Returns
The current value of Blue's drop probability
Definition at line 147 of file cobalt-queue-disc.cc.
References m_Pdrop.
GetTarget()
Time ns3::CobaltQueueDisc::GetTarget (void)
Get the target queue delay.
Returns
The target queue delay
Definition at line 198 of file cobalt-queue-disc.cc.
References m_target.
GetTypeId()
TypeId ns3::CobaltQueueDisc::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 45 of file cobalt-queue-disc.cc.
References ns3::BYTES, DEFAULT_COBALT_LIMIT, ns3::QueueDisc::GetMaxSize(), m_count, m_decrement, m_dropNext, m_dropping, m_increment, m_interval, m_Pdrop, m_target, m_useEcn, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeDoubleAccessor(), ns3::MakeQueueSizeAccessor(), ns3::MakeQueueSizeChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::QueueDisc::SetMaxSize(), and ns3::TypeId::SetParent().
InitializeParams()
void ns3::CobaltQueueDisc::InitializeParams (void) private virtual
Initialize the queue parameters.
Implements ns3::QueueDisc.
Definition at line 166 of file cobalt-queue-disc.cc.
References CacheInit(), m_count, m_dropNext, m_dropping, m_lastUpdateTimeBlue, m_recInvSqrt, m_recInvSqrtCache, and NS_LOG_FUNCTION.
Referenced by CobaltQueueDisc().
InvSqrt()
void ns3::CobaltQueueDisc::InvSqrt (void) private
Definition at line 245 of file cobalt-queue-disc.cc.
References m_count, m_recInvSqrt, m_recInvSqrtCache, NewtonStep(), and REC_INV_SQRT_CACHE.
Referenced by CobaltQueueEmpty(), and CobaltShouldDrop().
NewtonStep()
void ns3::CobaltQueueDisc::NewtonStep (void) private
Calculate the reciprocal square root of m_count by using Newton's method http://en.wikipedia.org/wiki/Methods_of_computing_square_roots#Iterative_methods_for_reciprocal_square_roots m_recInvSqrt (new) = (m_recInvSqrt (old) / 2) * (3 - m_count * m_recInvSqrt^2)
Definition at line 216 of file cobalt-queue-disc.cc.
References m_count, m_recInvSqrt, and NS_LOG_FUNCTION.
Referenced by CacheInit(), and InvSqrt().
Time2CoDel()
int64_t ns3::CobaltQueueDisc::Time2CoDel (Time t)
Return the unsigned 32-bit integer representation of the input Time object.
Units are microseconds
Parameters
t the input Time Object
Returns
the unsigned 32-bit integer representation
Definition at line 192 of file cobalt-queue-disc.cc.
References ns3::Time::GetNanoSeconds().
Referenced by CobaltQueueEmpty(), CobaltQueueFull(), CobaltShouldDrop(), and ControlLaw().
Member Data Documentation
FORCED_MARK
constexpr const char* ns3::CobaltQueueDisc::FORCED_MARK = "forcedMark" static constexpr
forced marks by Codel on ECN-enabled
Definition at line 105 of file cobalt-queue-disc.h.
Referenced by CobaltShouldDrop().
m_count
TracedValue<uint32_t> ns3::CobaltQueueDisc::m_count private
Number of packets dropped since entering drop state.
Definition at line 220 of file cobalt-queue-disc.h.
Referenced by CacheInit(), CobaltQueueEmpty(), CobaltQueueFull(), CobaltShouldDrop(), GetTypeId(), InitializeParams(), InvSqrt(), and NewtonStep().
m_decrement
double ns3::CobaltQueueDisc::m_decrement private
decrement value for marking probability
Definition at line 238 of file cobalt-queue-disc.h.
Referenced by CobaltQueueEmpty(), and GetTypeId().
m_dropNext
TracedValue<int64_t> ns3::CobaltQueueDisc::m_dropNext private
Time to drop next packet.
Definition at line 221 of file cobalt-queue-disc.h.
Referenced by CobaltQueueEmpty(), CobaltQueueFull(), CobaltShouldDrop(), GetDropNext(), GetTypeId(), and InitializeParams().
m_dropping
TracedValue<bool> ns3::CobaltQueueDisc::m_dropping private
True if in dropping state.
Definition at line 222 of file cobalt-queue-disc.h.
Referenced by CobaltQueueEmpty(), CobaltQueueFull(), CobaltShouldDrop(), DoDequeue(), GetTypeId(), and InitializeParams().
m_increment
double ns3::CobaltQueueDisc::m_increment private
increment value for marking probability
Definition at line 237 of file cobalt-queue-disc.h.
Referenced by CobaltQueueFull(), and GetTypeId().
m_interval
Time ns3::CobaltQueueDisc::m_interval private
100 ms sliding minimum time window width
Definition at line 227 of file cobalt-queue-disc.h.
Referenced by CobaltShouldDrop(), ControlLaw(), GetInterval(), and GetTypeId().
m_lastUpdateTimeBlue
uint32_t ns3::CobaltQueueDisc::m_lastUpdateTimeBlue private
Blue's last update time for drop probability.
Definition at line 234 of file cobalt-queue-disc.h.
Referenced by CobaltQueueEmpty(), CobaltQueueFull(), and InitializeParams().
m_Pdrop
double ns3::CobaltQueueDisc::m_Pdrop private
Drop Probability.
Definition at line 239 of file cobalt-queue-disc.h.
Referenced by CobaltQueueEmpty(), CobaltQueueFull(), CobaltShouldDrop(), GetPdrop(), and GetTypeId().
m_recInvSqrt
uint32_t ns3::CobaltQueueDisc::m_recInvSqrt private
Reciprocal inverse square root.
Definition at line 223 of file cobalt-queue-disc.h.
Referenced by CacheInit(), ControlLaw(), InitializeParams(), InvSqrt(), and NewtonStep().
m_recInvSqrtCache
uint32_t ns3::CobaltQueueDisc::m_recInvSqrtCache[REC_INV_SQRT_CACHE] = {0} private
Cache to maintain some initial values of InvSqrt.
Definition at line 224 of file cobalt-queue-disc.h.
Referenced by CacheInit(), InitializeParams(), and InvSqrt().
m_stats
Stats ns3::CobaltQueueDisc::m_stats private
Cobalt statistics.
Definition at line 216 of file cobalt-queue-disc.h.
m_target
Time ns3::CobaltQueueDisc::m_target private
5 ms target queue delay
Definition at line 228 of file cobalt-queue-disc.h.
Referenced by CobaltQueueEmpty(), CobaltQueueFull(), CobaltShouldDrop(), GetTarget(), and GetTypeId().
m_useEcn
bool ns3::CobaltQueueDisc::m_useEcn private
True if ECN is used (packets are marked instead of being dropped)
Definition at line 229 of file cobalt-queue-disc.h.
Referenced by CobaltShouldDrop(), and GetTypeId().
m_uv
Ptr<UniformRandomVariable> ns3::CobaltQueueDisc::m_uv private
Rng stream.
Definition at line 233 of file cobalt-queue-disc.h.
Referenced by CobaltQueueDisc(), AssignStreams(), CobaltShouldDrop(), and DoDispose().
OVERLIMIT_DROP
constexpr const char* ns3::CobaltQueueDisc::OVERLIMIT_DROP = "Overlimit drop" static constexpr
Overlimit dropped packet.
Definition at line 104 of file cobalt-queue-disc.h.
Referenced by DoEnqueue().
TARGET_EXCEEDED_DROP
constexpr const char* ns3::CobaltQueueDisc::TARGET_EXCEEDED_DROP = "Target exceeded drop" static constexpr
Sojourn time above target.
Definition at line 103 of file cobalt-queue-disc.h.
Referenced by DoDequeue().
The documentation for this class was generated from the following files:
src/traffic-control/model/cobalt-queue-disc.h
src/traffic-control/model/cobalt-queue-disc.cc