ns-3: ns3::PointToPointChannel Class Reference
ns3::PointToPointChannel Class Reference
Point-To-Point Network Device
Simple Point To Point Channel.
#include "point-to-point-channel.h"
Classes
class Link
Wire model for the PointToPointChannel.
Public Member Functions
PointToPointChannel ()
Create a PointToPointChannel.
void Attach (Ptr< PointToPointNetDevice > device)
Attach a given netdevice to this channel.
virtual Ptr< NetDevice > GetDevice (std::size_t i) const
Get NetDevice corresponding to index i on this channel.
virtual std::size_t GetNDevices (void) const
Get number of devices on this channel.
Ptr< PointToPointNetDevice > GetPointToPointDevice (std::size_t i) const
Get PointToPointNetDevice corresponding to index i on this channel.
virtual bool TransmitStart (Ptr< const Packet > p, Ptr< PointToPointNetDevice > src, Time txTime)
Transmit a packet over this channel.
Public Member Functions inherited from ns3::Channel
Channel ()
virtual ~Channel ()
uint32_t GetId (void) const
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the TypeId.
Static Public Member Functions inherited from ns3::Channel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Types
typedef void(* TxRxAnimationCallback) (Ptr< const Packet > packet, Ptr< NetDevice > txDevice, Ptr< NetDevice > rxDevice, Time duration, Time lastBitTime)
TracedCallback signature for packet transmission animation events.
Protected Member Functions
Time GetDelay (void) const
Get the delay associated with this channel.
Ptr< PointToPointNetDevice > GetDestination (uint32_t i) const
Get the net-device destination.
Ptr< PointToPointNetDevice > GetSource (uint32_t i) const
Get the net-device source.
bool IsInitialized (void) const
Check to make sure the link is initialized.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
enum WireState { INITIALIZING , IDLE , TRANSMITTING , PROPAGATING }
Wire states.
Private Attributes
Time m_delay
Propagation delay.
Link m_link [N_DEVICES]
Link model.
std::size_t m_nDevices
Devices of this channel.
TracedCallback< Ptr< const Packet >, Ptr< NetDevice >, Ptr< NetDevice >, Time, Time > m_txrxPointToPoint
The trace source for the packet transmission animation events that the device can fire.
Static Private Attributes
static const std::size_t N_DEVICES = 2
Each point to point link has exactly two net devices.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Simple Point To Point Channel.
This class represents a very simple point to point channel. Think full duplex RS-232 or RS-422 with null modem and no handshaking. There is no multi-drop capability on this channel – there can be a maximum of two point-to-point net devices connected.
There are two "wires" in the channel. The first device connected gets the [0] wire to transmit on. The second device gets the [1] wire. There is a state (IDLE, TRANSMITTING) associated with each wire.
See also
Attach
TransmitStart
Config Paths
ns3::PointToPointChannel is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::PointToPointChannel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::PointToPointChannel"
"/ChannelList/[i]/$ns3::PointToPointChannel"
Attributes
Delay: Propagation delay through the channel
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
Attributes defined in parent class ns3::Channel
Id: The id (unique integer) of this Channel.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Flags: read
TraceSources
TxRxPointToPoint: Trace source indicating transmission of packet from the PointToPointChannel, used by the Animation interface.
Callback signature: ns3::PointToPointChannel::TxRxAnimationCallback
Size of this type is 120 bytes (on a 64-bit architecture).
Definition at line 50 of file point-to-point-channel.h.
Member Typedef Documentation
TxRxAnimationCallback
typedef void(* ns3::PointToPointChannel::TxRxAnimationCallback) (Ptr< const Packet > packet, Ptr< NetDevice > txDevice, Ptr< NetDevice > rxDevice, Time duration, Time lastBitTime) protected
TracedCallback signature for packet transmission animation events.
Parameters
[in] packet The packet being transmitted.
[in] txDevice the TransmitTing NetDevice.
[in] rxDevice the Receiving NetDevice.
[in] duration The amount of time to transmit the packet.
[in] lastBitTime Last bit receive time (relative to now)
Deprecated:
The non-const Ptr<NetDevice> argument is deprecated and will be changed to Ptr<const NetDevice> in a future release.
Definition at line 143 of file point-to-point-channel.h.
Member Enumeration Documentation
WireState
enum ns3::PointToPointChannel::WireState private
Wire states.
Enumerator
INITIALIZING
Initializing state.
IDLE
Idle state (no transmission from NetDevice)
TRANSMITTING
Transmitting state (data being transmitted from NetDevice.
PROPAGATING
Propagating state (data is being propagated in the channel.
Definition at line 176 of file point-to-point-channel.h.
Constructor & Destructor Documentation
PointToPointChannel()
ns3::PointToPointChannel::PointToPointChannel ()
Create a PointToPointChannel.
By default, you get a channel that has an "infinitely" fast transmission speed and zero delay.
Definition at line 56 of file point-to-point-channel.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
Attach()
void ns3::PointToPointChannel::Attach (Ptr< PointToPointNetDevice > device)
Attach a given netdevice to this channel.
Parameters
device pointer to the netdevice to attach to the channel
Definition at line 66 of file point-to-point-channel.cc.
References IDLE, ns3::PointToPointChannel::Link::m_dst, m_link, m_nDevices, ns3::PointToPointChannel::Link::m_src, ns3::PointToPointChannel::Link::m_state, N_DEVICES, NS_ASSERT, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
GetDelay()
Time ns3::PointToPointChannel::GetDelay (void) const protected
Get the delay associated with this channel.
Returns
Time delay
Definition at line 132 of file point-to-point-channel.cc.
References m_delay.
Referenced by ns3::PointToPointRemoteChannel::TransmitStart().
GetDestination()
Ptr< PointToPointNetDevice > ns3::PointToPointChannel::GetDestination (uint32_t i) const protected
Get the net-device destination.
Parameters
i the link requested
Returns
Ptr to PointToPointNetDevice destination for the specified link
Definition at line 144 of file point-to-point-channel.cc.
References ns3::PointToPointChannel::Link::m_dst, and m_link.
Referenced by ns3::PointToPointRemoteChannel::TransmitStart().
GetDevice()
Ptr< NetDevice > ns3::PointToPointChannel::GetDevice (std::size_t i) const virtual
Get NetDevice corresponding to index i on this channel.
Parameters
i Index number of the device requested
Returns
Ptr to NetDevice requested
Implements ns3::Channel.
Definition at line 125 of file point-to-point-channel.cc.
References GetPointToPointDevice(), and NS_LOG_FUNCTION_NOARGS.
GetNDevices()
std::size_t ns3::PointToPointChannel::GetNDevices (void) const virtual
Get number of devices on this channel.
Returns
number of devices on this channel
Implements ns3::Channel.
Definition at line 110 of file point-to-point-channel.cc.
References m_nDevices, and NS_LOG_FUNCTION_NOARGS.
GetPointToPointDevice()
Ptr< PointToPointNetDevice > ns3::PointToPointChannel::GetPointToPointDevice (std::size_t i) const
Get PointToPointNetDevice corresponding to index i on this channel.
Parameters
i Index number of the device requested
Returns
Ptr to PointToPointNetDevice requested
Definition at line 117 of file point-to-point-channel.cc.
References m_link, ns3::PointToPointChannel::Link::m_src, NS_ASSERT, and NS_LOG_FUNCTION_NOARGS.
Referenced by GetDevice().
GetSource()
Ptr< PointToPointNetDevice > ns3::PointToPointChannel::GetSource (uint32_t i) const protected
Get the net-device source.
Parameters
i the link requested
Returns
Ptr to PointToPointNetDevice source for the specified link
Definition at line 138 of file point-to-point-channel.cc.
References m_link, and ns3::PointToPointChannel::Link::m_src.
Referenced by ns3::PointToPointRemoteChannel::TransmitStart().
GetTypeId()
TypeId ns3::PointToPointChannel::GetTypeId (void) static
Get the TypeId.
Returns
The TypeId for this class
Definition at line 33 of file point-to-point-channel.cc.
References m_delay, m_txrxPointToPoint, ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::Seconds(), and ns3::TypeId::SetParent().
IsInitialized()
bool ns3::PointToPointChannel::IsInitialized (void) const protected
Check to make sure the link is initialized.
Returns
true if initialized, asserts otherwise
Definition at line 150 of file point-to-point-channel.cc.
References INITIALIZING, m_link, and NS_ASSERT.
Referenced by ns3::PointToPointRemoteChannel::TransmitStart().
TransmitStart()
bool ns3::PointToPointChannel::TransmitStart (Ptr< const Packet > p, Ptr< PointToPointNetDevice > src, Time txTime) virtual
Transmit a packet over this channel.
Parameters
p Packet to transmit
src Source PointToPointNetDevice
txTime Transmit time to apply
Returns
true if successful (currently always true)
Reimplemented in ns3::PointToPointRemoteChannel.
Definition at line 87 of file point-to-point-channel.cc.
References INITIALIZING, m_delay, ns3::PointToPointChannel::Link::m_dst, m_link, ns3::PointToPointChannel::Link::m_src, m_txrxPointToPoint, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::PointToPointNetDevice::Receive(), and ns3::Simulator::ScheduleWithContext().
Member Data Documentation
m_delay
Time ns3::PointToPointChannel::m_delay private
Propagation delay.
Definition at line 152 of file point-to-point-channel.h.
Referenced by GetDelay(), GetTypeId(), and TransmitStart().
m_link
Link ns3::PointToPointChannel::m_link[N_DEVICES] private
Link model.
Definition at line 204 of file point-to-point-channel.h.
Referenced by Attach(), GetDestination(), GetPointToPointDevice(), GetSource(), IsInitialized(), and TransmitStart().
m_nDevices
std::size_t ns3::PointToPointChannel::m_nDevices private
Devices of this channel.
Definition at line 153 of file point-to-point-channel.h.
Referenced by Attach(), and GetNDevices().
m_txrxPointToPoint
TracedCallback<Ptr<const Packet>, Ptr<NetDevice>, Ptr<NetDevice>, Time, Time > ns3::PointToPointChannel::m_txrxPointToPoint private
The trace source for the packet transmission animation events that the device can fire.
Arguments to the callback are the packet, transmitting net device, receiving net device, transmission time and packet receipt time.
See also
class CallBackTraceSource
Deprecated:
The non-const Ptr<NetDevice> argument is deprecated and will be changed to Ptr<const NetDevice> in a future release.
Definition at line 171 of file point-to-point-channel.h.
Referenced by GetTypeId(), and TransmitStart().
N_DEVICES
const std::size_t ns3::PointToPointChannel::N_DEVICES = 2 static private
Each point to point link has exactly two net devices.
Definition at line 150 of file point-to-point-channel.h.
Referenced by Attach().
The documentation for this class was generated from the following files:
src/point-to-point/model/point-to-point-channel.h
src/point-to-point/model/point-to-point-channel.cc