ns-3: ns3::EnergySourceContainer Class Reference
ns3::EnergySourceContainer Class Reference
Energy Models
Holds a vector of ns3::EnergySource pointers.
#include "energy-source-container.h"
Public Types
typedef std::vector< Ptr< EnergySource > >::const_iterator Iterator
Public Member Functions
EnergySourceContainer ()
Creates an empty EnergySourceContainer.
EnergySourceContainer (const EnergySourceContainer &a, const EnergySourceContainer &b)
EnergySourceContainer (Ptr< EnergySource > source)
EnergySourceContainer (std::string sourceName)
~EnergySourceContainer ()
void Add (EnergySourceContainer container)
void Add (Ptr< EnergySource > source)
Append a single Ptr<EnergySource> to the end of this container.
void Add (std::string sourceName)
Append a single Ptr<EnergySource> referred to by its object name to the end of this container.
Iterator Begin (void) const
Get an iterator which refers to the first EnergySource pointer in the container.
Iterator End (void) const
Get an iterator which refers to the last EnergySource pointer in the container.
Ptr< EnergySource > Get (uint32_t i) const
Get the i-th Ptr<EnergySource> stored in this container.
uint32_t GetN (void) const
Get the number of Ptr<EnergySource> stored in this container.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Calls Object::Start () for all EnergySource objects.
Private Attributes
std::vector< Ptr< EnergySource > > m_sources
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Holds a vector of ns3::EnergySource pointers.
EnergySourceHelper returns a list of EnergySource pointers installed onto a node. Users can use this list to access EnergySource objects to obtain total energy consumption on a node easily.
See also
NetDeviceContainer
Config Paths
ns3::EnergySourceContainer is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::EnergySourceContainer"
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 56 bytes (on a 64-bit architecture).
Definition at line 44 of file energy-source-container.h.
Member Typedef Documentation
Iterator
typedef std::vector< Ptr<EnergySource> >::const_iterator ns3::EnergySourceContainer::Iterator
Definition at line 47 of file energy-source-container.h.
Constructor & Destructor Documentation
EnergySourceContainer() [1/4]
ns3::EnergySourceContainer::EnergySourceContainer ()
Creates an empty EnergySourceContainer.
Definition at line 41 of file energy-source-container.cc.
~EnergySourceContainer()
ns3::EnergySourceContainer::~EnergySourceContainer ()
Definition at line 45 of file energy-source-container.cc.
EnergySourceContainer() [2/4]
ns3::EnergySourceContainer::EnergySourceContainer (Ptr< EnergySource > source)
Parameters
source Pointer to an EnergySource.
Creates an EnergySourceContianer with exactly one EnergySource previously instantiated.
Definition at line 49 of file energy-source-container.cc.
References m_sources, and NS_ASSERT.
EnergySourceContainer() [3/4]
ns3::EnergySourceContainer::EnergySourceContainer (std::string sourceName)
Parameters
sourceName Name of EnergySource.
Creates an EnergySourceContainer with exactly one EnergySource previously instantiated and assigned a name using the Object name service. This EnergySource is specified by its assigned name.
Definition at line 55 of file energy-source-container.cc.
References m_sources, and NS_ASSERT.
EnergySourceContainer() [4/4]
ns3::EnergySourceContainer::EnergySourceContainer (const EnergySourceContainer & a, const EnergySourceContainer & b)
Parameters
a A EnergySourceContainer.
b Another EnergySourceContainer.
Creates an EnergySourceContainer by concatenating EnergySourceContainer b to EnergySourceContainer a.
Note
Can be used to concatenate 2 Ptr<EnergySource> directly. C++ will be calling EnergySourceContainer constructor with Ptr<EnergySource> first.
Definition at line 62 of file energy-source-container.cc.
References Add().
Member Function Documentation
Add() [1/3]
void ns3::EnergySourceContainer::Add (EnergySourceContainer container)
Parameters
container Another EnergySourceContainer to append.
Appends the contents of another EnergySourceContainer to the end of this EnergySourceContainer.
Definition at line 94 of file energy-source-container.cc.
References Begin(), End(), and m_sources.
Referenced by EnergySourceContainer(), ns3::EnergySourceHelper::Install(), and UanExperiment::SetupCommunications().
Add() [2/3]
void ns3::EnergySourceContainer::Add (Ptr< EnergySource > source)
Append a single Ptr<EnergySource> to the end of this container.
Parameters
source Pointer to an EnergySource.
Definition at line 103 of file energy-source-container.cc.
References m_sources, and NS_ASSERT.
Add() [3/3]
void ns3::EnergySourceContainer::Add (std::string sourceName)
Append a single Ptr<EnergySource> referred to by its object name to the end of this container.
Parameters
sourceName Name of EnergySource object.
Definition at line 110 of file energy-source-container.cc.
References m_sources, and NS_ASSERT.
Begin()
EnergySourceContainer::Iterator ns3::EnergySourceContainer::Begin (void) const
Get an iterator which refers to the first EnergySource pointer in the container.
Returns
An iterator which refers to the first EnergySource in container.
EnergySources can be retrieved from the container in two ways. First, directly by an index into the container, and second, using an iterator. This method is used in the iterator method and is typically used in a for-loop to run through the EnergySources.
EnergySourceContainer::Iterator i;
for (i = container.Begin (); i != container.End (); ++i)
  {
    (*i)->method ();  // some EnergySource method
  }
Definition at line 70 of file energy-source-container.cc.
References m_sources.
Referenced by Add(), ns3::EnergyHarvesterHelper::Install(), ns3::DeviceEnergyModelHelper::Install(), and UanExperiment::SetupCommunications().
DoDispose()
void ns3::EnergySourceContainer::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 122 of file energy-source-container.cc.
References m_sources.
DoInitialize()
void ns3::EnergySourceContainer::DoInitialize (void) private virtual
Calls Object::Start () for all EnergySource objects.
Reimplemented from ns3::Object.
Definition at line 135 of file energy-source-container.cc.
References m_sources.
End()
EnergySourceContainer::Iterator ns3::EnergySourceContainer::End (void) const
Get an iterator which refers to the last EnergySource pointer in the container.
Returns
An iterator which refers to the last EnergySource in container.
EnergySources can be retrieved from the container in two ways. First, directly by an index into the container, and second, using an iterator. This method is used in the iterator method and is typically used in a for-loop to run through the EnergySources.
EnergySourceContainer::Iterator i;
for (i = container.Begin (); i != container.End (); ++i)
  {
    (*i)->method ();  // some EnergySource method
  }
Definition at line 76 of file energy-source-container.cc.
References m_sources.
Referenced by Add(), and ns3::EnergyHarvesterHelper::Install().
Get()
Ptr< EnergySource > ns3::EnergySourceContainer::Get (uint32_t i) const
Get the i-th Ptr<EnergySource> stored in this container.
Parameters
i Index of the requested Ptr<EnergySource>.
Returns
The requested Ptr<EnergySource>.
Definition at line 88 of file energy-source-container.cc.
References m_sources.
Referenced by BatteryLifetimeTest::ConstantLoadTest(), UanExperiment::SetupCommunications(), and BatteryLifetimeTest::VariableLoadTest().
GetN()
uint32_t ns3::EnergySourceContainer::GetN (void) const
Get the number of Ptr<EnergySource> stored in this container.
Returns
The number of Ptr<EnergySource> stored in this container.
Definition at line 82 of file energy-source-container.cc.
References m_sources.
Referenced by ns3::DeviceEnergyModelHelper::Install().
GetTypeId()
TypeId ns3::EnergySourceContainer::GetTypeId (void) static
Definition at line 31 of file energy-source-container.cc.
References ns3::TypeId::SetParent().
Member Data Documentation
m_sources
std::vector< Ptr<EnergySource> > ns3::EnergySourceContainer::m_sources private
Definition at line 176 of file energy-source-container.h.
Referenced by EnergySourceContainer(), Add(), Begin(), DoDispose(), DoInitialize(), End(), Get(), and GetN().
The documentation for this class was generated from the following files:
src/energy/helper/energy-source-container.h
src/energy/helper/energy-source-container.cc