ns-3: ns3::dsr::DsrMaintainBuffEntry Class Reference
ns3::dsr::DsrMaintainBuffEntry Class Reference
DSR Routing
DSR Maintain Buffer Entry.
#include "dsr-maintain-buff.h"
Public Member Functions
DsrMaintainBuffEntry (Ptr< const Packet > pa=0, Ipv4Address us=Ipv4Address(), Ipv4Address n=Ipv4Address(), Ipv4Address s=Ipv4Address(), Ipv4Address dst=Ipv4Address(), uint16_t ackId=0, uint8_t segs=0, Time exp=Simulator::Now())
Construct a DsrMaintainBuffEntry with the given parameters.
uint16_t GetAckId () const
Get acknowledge ID.
Ipv4Address GetDst () const
Get destination address.
Time GetExpireTime () const
Get expiration time.
Ipv4Address GetNextHop () const
Get next hop of entry.
Ipv4Address GetOurAdd () const
Get local address of entry.
Ptr< const Packet > GetPacket () const
Get packet.
uint8_t GetSegsLeft () const
Get segments left.
Ipv4Address GetSrc () const
Get source address.
void SetAckId (uint16_t ackId)
Set acknowledge ID.
void SetDst (Ipv4Address n)
Set destination address.
void SetExpireTime (Time exp)
Set expiration time.
void SetNextHop (Ipv4Address n)
Set next hop of entry.
void SetOurAdd (Ipv4Address us)
Set local address of entry.
void SetPacket (Ptr< const Packet > p)
Set packet.
void SetSegsLeft (uint8_t segs)
Set segments left.
void SetSrc (Ipv4Address s)
Set source address.
Private Attributes
uint16_t m_ackId
The data ack id.
Ipv4Address m_dst
The destination address.
Time m_expire
Expire time for queue entry.
Ipv4Address m_nextHop
Next hop Ip address.
Ipv4Address m_ourAdd
Our own ip address.
Ptr< const Packet > m_packet
Data packet.
uint8_t m_segsLeft
The segments left field.
Ipv4Address m_src
The source address.
Detailed Description
DSR Maintain Buffer Entry.
Definition at line 212 of file dsr-maintain-buff.h.
Constructor & Destructor Documentation
DsrMaintainBuffEntry()
ns3::dsr::DsrMaintainBuffEntry::DsrMaintainBuffEntry (Ptr< const Packet > pa = 0, Ipv4Address us = Ipv4Address (), Ipv4Address n = Ipv4Address (), Ipv4Address s = Ipv4Address (), Ipv4Address dst = Ipv4Address (), uint16_t ackId = 0, uint8_t segs = 0, Time exp = Simulator::Now ()) inline
Construct a DsrMaintainBuffEntry with the given parameters.
Parameters
pa packet
us our IPv4 address
n next hop IPv4 address
s IPv4 address of the source
dst IPv4 address of the destination
ackId ACK ID
segs number of segments left
exp expiration time
Definition at line 227 of file dsr-maintain-buff.h.
Member Function Documentation
GetAckId()
uint16_t ns3::dsr::DsrMaintainBuffEntry::GetAckId () const inline
Get acknowledge ID.
Returns
the acknowledge ID
Definition at line 326 of file dsr-maintain-buff.h.
References m_ackId.
Referenced by ns3::dsr::DsrMaintainBuffer::AllEqual(), ns3::dsr::DsrRouting::CancelNetworkPacketTimer(), ns3::dsr::DsrRouting::CheckSendBuffer(), ns3::dsr::DsrMaintainBuffer::Enqueue(), ns3::dsr::DsrRouting::ForwardPacket(), ns3::dsr::DsrMaintainBuffer::NetworkEqual(), ns3::dsr::DsrRouting::NetworkScheduleTimerExpire(), ns3::dsr::DsrRouting::PacketNewRoute(), ns3::dsr::DsrMaintainBuffer::PromiscEqual(), ns3::dsr::DsrRouting::ScheduleNetworkPacketRetry(), ns3::dsr::DsrRouting::Send(), and ns3::dsr::DsrRouting::SendPacketFromBuffer().
GetDst()
Ipv4Address ns3::dsr::DsrMaintainBuffEntry::GetDst () const inline
Get destination address.
Returns
the destination IP address
Definition at line 294 of file dsr-maintain-buff.h.
References m_dst.
Referenced by ns3::dsr::DsrMaintainBuffer::AllEqual(), ns3::dsr::DsrRouting::CancelLinkPacketTimer(), ns3::dsr::DsrRouting::CancelNetworkPacketTimer(), ns3::dsr::DsrRouting::CancelPacketTimerNextHop(), ns3::dsr::DsrRouting::CancelPassivePacketTimer(), ns3::dsr::DsrRouting::CheckSendBuffer(), ns3::dsr::DsrMaintainBuffer::Enqueue(), ns3::dsr::DsrRouting::ForwardPacket(), ns3::dsr::DsrMaintainBuffer::LinkEqual(), ns3::dsr::DsrRouting::LinkScheduleTimerExpire(), ns3::dsr::DsrMaintainBuffer::NetworkEqual(), ns3::dsr::DsrRouting::NetworkScheduleTimerExpire(), ns3::dsr::DsrRouting::PacketNewRoute(), ns3::dsr::DsrRouting::PassiveScheduleTimerExpire(), ns3::dsr::DsrMaintainBuffer::PromiscEqual(), ns3::dsr::DsrRouting::ScheduleLinkPacketRetry(), ns3::dsr::DsrRouting::ScheduleNetworkPacketRetry(), ns3::dsr::DsrRouting::SchedulePassivePacketRetry(), ns3::dsr::DsrRouting::Send(), and ns3::dsr::DsrRouting::SendPacketFromBuffer().
GetExpireTime()
Time ns3::dsr::DsrMaintainBuffEntry::GetExpireTime () const inline
Get expiration time.
Returns
the expiration time
Definition at line 366 of file dsr-maintain-buff.h.
References m_expire, and ns3::Simulator::Now().
Referenced by ns3::dsr::IsExpired::operator()().
GetNextHop()
Ipv4Address ns3::dsr::DsrMaintainBuffEntry::GetNextHop () const inline
Get next hop of entry.
Returns
the IP address for the next hop
Definition at line 278 of file dsr-maintain-buff.h.
References m_nextHop.
Referenced by ns3::dsr::DsrMaintainBuffer::AllEqual(), ns3::dsr::DsrRouting::CancelLinkPacketTimer(), ns3::dsr::DsrRouting::CancelNetworkPacketTimer(), ns3::dsr::DsrRouting::CheckSendBuffer(), ns3::dsr::DsrMaintainBuffer::Enqueue(), ns3::dsr::DsrRouting::ForwardPacket(), ns3::dsr::DsrMaintainBuffer::LinkEqual(), ns3::dsr::DsrRouting::LinkScheduleTimerExpire(), ns3::dsr::DsrMaintainBuffer::NetworkEqual(), ns3::dsr::DsrRouting::NetworkScheduleTimerExpire(), ns3::dsr::DsrRouting::PacketNewRoute(), ns3::dsr::DsrRouting::PassiveScheduleTimerExpire(), ns3::dsr::DsrRouting::ScheduleLinkPacketRetry(), ns3::dsr::DsrRouting::ScheduleNetworkPacketRetry(), ns3::dsr::DsrRouting::SchedulePassivePacketRetry(), ns3::dsr::DsrRouting::Send(), and ns3::dsr::DsrRouting::SendPacketFromBuffer().
GetOurAdd()
Ipv4Address ns3::dsr::DsrMaintainBuffEntry::GetOurAdd () const inline
Get local address of entry.
Returns
the local IP address
Definition at line 262 of file dsr-maintain-buff.h.
References m_ourAdd.
Referenced by ns3::dsr::DsrMaintainBuffer::AllEqual(), ns3::dsr::DsrRouting::CancelLinkPacketTimer(), ns3::dsr::DsrRouting::CancelNetworkPacketTimer(), ns3::dsr::DsrRouting::CheckSendBuffer(), ns3::dsr::DsrMaintainBuffer::Enqueue(), ns3::dsr::DsrRouting::ForwardPacket(), ns3::dsr::DsrMaintainBuffer::LinkEqual(), ns3::dsr::DsrRouting::LinkScheduleTimerExpire(), ns3::dsr::DsrMaintainBuffer::NetworkEqual(), ns3::dsr::DsrRouting::NetworkScheduleTimerExpire(), ns3::dsr::DsrRouting::PacketNewRoute(), ns3::dsr::DsrRouting::ScheduleLinkPacketRetry(), ns3::dsr::DsrRouting::ScheduleNetworkPacketRetry(), ns3::dsr::DsrRouting::Send(), and ns3::dsr::DsrRouting::SendPacketFromBuffer().
GetPacket()
Ptr<const Packet> ns3::dsr::DsrMaintainBuffEntry::GetPacket () const inline
Get packet.
Returns
the current packet
Definition at line 246 of file dsr-maintain-buff.h.
References m_packet.
Referenced by ns3::dsr::DsrRouting::CancelPacketTimerNextHop(), ns3::dsr::DsrMaintainBuffer::Dequeue(), ns3::dsr::DsrRouting::LinkScheduleTimerExpire(), ns3::dsr::DsrRouting::NetworkScheduleTimerExpire(), ns3::dsr::DsrRouting::PassiveScheduleTimerExpire(), ns3::dsr::DsrRouting::ScheduleLinkPacketRetry(), ns3::dsr::DsrRouting::ScheduleNetworkPacketRetry(), and ns3::dsr::DsrRouting::SchedulePassivePacketRetry().
GetSegsLeft()
uint8_t ns3::dsr::DsrMaintainBuffEntry::GetSegsLeft () const inline
Get segments left.
Returns
the number of segments left
Definition at line 342 of file dsr-maintain-buff.h.
References m_segsLeft.
Referenced by ns3::dsr::DsrMaintainBuffer::AllEqual(), ns3::dsr::DsrRouting::CancelNetworkPacketTimer(), ns3::dsr::DsrRouting::CancelPassivePacketTimer(), ns3::dsr::DsrRouting::CheckSendBuffer(), ns3::dsr::DsrMaintainBuffer::Enqueue(), ns3::dsr::DsrRouting::ForwardPacket(), ns3::dsr::DsrRouting::PacketNewRoute(), ns3::dsr::DsrRouting::PassiveScheduleTimerExpire(), ns3::dsr::DsrMaintainBuffer::PromiscEqual(), ns3::dsr::DsrRouting::SchedulePassivePacketRetry(), ns3::dsr::DsrRouting::Send(), and ns3::dsr::DsrRouting::SendPacketFromBuffer().
GetSrc()
Ipv4Address ns3::dsr::DsrMaintainBuffEntry::GetSrc () const inline
Get source address.
Returns
the source IP address
Definition at line 310 of file dsr-maintain-buff.h.
References m_src.
Referenced by ns3::dsr::DsrMaintainBuffer::AllEqual(), ns3::dsr::DsrRouting::CancelLinkPacketTimer(), ns3::dsr::DsrRouting::CancelNetworkPacketTimer(), ns3::dsr::DsrRouting::CancelPacketTimerNextHop(), ns3::dsr::DsrRouting::CancelPassivePacketTimer(), ns3::dsr::DsrRouting::CheckSendBuffer(), ns3::dsr::DsrMaintainBuffer::Enqueue(), ns3::dsr::DsrRouting::ForwardPacket(), ns3::dsr::DsrMaintainBuffer::LinkEqual(), ns3::dsr::DsrRouting::LinkScheduleTimerExpire(), ns3::dsr::DsrMaintainBuffer::NetworkEqual(), ns3::dsr::DsrRouting::NetworkScheduleTimerExpire(), ns3::dsr::DsrRouting::PacketNewRoute(), ns3::dsr::DsrRouting::PassiveScheduleTimerExpire(), ns3::dsr::DsrMaintainBuffer::PromiscEqual(), ns3::dsr::DsrRouting::ScheduleLinkPacketRetry(), ns3::dsr::DsrRouting::ScheduleNetworkPacketRetry(), ns3::dsr::DsrRouting::SchedulePassivePacketRetry(), ns3::dsr::DsrRouting::Send(), and ns3::dsr::DsrRouting::SendPacketFromBuffer().
SetAckId()
void ns3::dsr::DsrMaintainBuffEntry::SetAckId (uint16_t ackId) inline
Set acknowledge ID.
Parameters
ackId the acknowledge ID
Definition at line 334 of file dsr-maintain-buff.h.
References m_ackId.
Referenced by ns3::dsr::DsrRouting::CancelPassiveTimer(), ns3::dsr::DsrRouting::PassiveEntryCheck(), and ns3::dsr::DsrRouting::ScheduleNetworkPacketRetry().
SetDst()
void ns3::dsr::DsrMaintainBuffEntry::SetDst (Ipv4Address n) inline
Set destination address.
Parameters
n the destination IP address
Definition at line 302 of file dsr-maintain-buff.h.
References m_dst, and sample-rng-plot::n.
Referenced by ns3::dsr::DsrRouting::CancelPassiveTimer(), ns3::dsr::DsrRouting::PassiveEntryCheck(), and ns3::dsr::DsrRouting::PromiscReceive().
SetExpireTime()
void ns3::dsr::DsrMaintainBuffEntry::SetExpireTime (Time exp) inline
Set expiration time.
Parameters
exp the expire time
Definition at line 358 of file dsr-maintain-buff.h.
References m_expire, and ns3::Simulator::Now().
Referenced by ns3::dsr::DsrMaintainBuffer::Enqueue(), and ns3::dsr::DsrRouting::ScheduleNetworkPacketRetry().
SetNextHop()
void ns3::dsr::DsrMaintainBuffEntry::SetNextHop (Ipv4Address n) inline
Set next hop of entry.
Parameters
n the next hop IP address
Definition at line 286 of file dsr-maintain-buff.h.
References m_nextHop, and sample-rng-plot::n.
Referenced by ns3::dsr::DsrRouting::PromiscReceive().
SetOurAdd()
void ns3::dsr::DsrMaintainBuffEntry::SetOurAdd (Ipv4Address us) inline
Set local address of entry.
Parameters
us the local IP address
Definition at line 270 of file dsr-maintain-buff.h.
References m_ourAdd.
Referenced by ns3::dsr::DsrRouting::PromiscReceive().
SetPacket()
void ns3::dsr::DsrMaintainBuffEntry::SetPacket (Ptr< const Packet > p) inline
Set packet.
Parameters
p the current packet
Definition at line 254 of file dsr-maintain-buff.h.
References m_packet.
Referenced by ns3::dsr::DsrRouting::CancelPassiveTimer(), ns3::dsr::DsrRouting::PassiveEntryCheck(), ns3::dsr::DsrRouting::PromiscReceive(), and ns3::dsr::DsrRouting::ScheduleNetworkPacketRetry().
SetSegsLeft()
void ns3::dsr::DsrMaintainBuffEntry::SetSegsLeft (uint8_t segs) inline
Set segments left.
Parameters
segs the number of segments left
Definition at line 350 of file dsr-maintain-buff.h.
References m_segsLeft.
Referenced by ns3::dsr::DsrRouting::CancelPassiveTimer(), and ns3::dsr::DsrRouting::PassiveEntryCheck().
SetSrc()
void ns3::dsr::DsrMaintainBuffEntry::SetSrc (Ipv4Address s) inline
Set source address.
Parameters
s the source IP address
Definition at line 318 of file dsr-maintain-buff.h.
References m_src.
Referenced by ns3::dsr::DsrRouting::CancelPassiveTimer(), ns3::dsr::DsrRouting::PassiveEntryCheck(), and ns3::dsr::DsrRouting::PromiscReceive().
Member Data Documentation
m_ackId
uint16_t ns3::dsr::DsrMaintainBuffEntry::m_ackId private
The data ack id.
Definition at line 383 of file dsr-maintain-buff.h.
Referenced by GetAckId(), and SetAckId().
m_dst
Ipv4Address ns3::dsr::DsrMaintainBuffEntry::m_dst private
The destination address.
Definition at line 381 of file dsr-maintain-buff.h.
Referenced by GetDst(), and SetDst().
m_expire
Time ns3::dsr::DsrMaintainBuffEntry::m_expire private
Expire time for queue entry.
Definition at line 387 of file dsr-maintain-buff.h.
Referenced by GetExpireTime(), and SetExpireTime().
m_nextHop
Ipv4Address ns3::dsr::DsrMaintainBuffEntry::m_nextHop private
Next hop Ip address.
Definition at line 377 of file dsr-maintain-buff.h.
Referenced by GetNextHop(), and SetNextHop().
m_ourAdd
Ipv4Address ns3::dsr::DsrMaintainBuffEntry::m_ourAdd private
Our own ip address.
Definition at line 375 of file dsr-maintain-buff.h.
Referenced by GetOurAdd(), and SetOurAdd().
m_packet
Ptr<const Packet> ns3::dsr::DsrMaintainBuffEntry::m_packet private
Data packet.
Definition at line 373 of file dsr-maintain-buff.h.
Referenced by GetPacket(), and SetPacket().
m_segsLeft
uint8_t ns3::dsr::DsrMaintainBuffEntry::m_segsLeft private
The segments left field.
Definition at line 385 of file dsr-maintain-buff.h.
Referenced by GetSegsLeft(), and SetSegsLeft().
m_src
Ipv4Address ns3::dsr::DsrMaintainBuffEntry::m_src private
The source address.
Definition at line 379 of file dsr-maintain-buff.h.
Referenced by GetSrc(), and SetSrc().
The documentation for this class was generated from the following file:
src/dsr/model/dsr-maintain-buff.h