ns-3: ns3::AnimByteTag Class Reference
ns3::AnimByteTag Class Reference
Network Animation
Byte tag using by Anim to uniquely identify packets.
#include "animation-interface.h"
Public Member Functions
virtual void Deserialize (TagBuffer i)
Deserialize function.
uint64_t Get (void) const
Get Uid in tag.
virtual TypeId GetInstanceTypeId (void) const
Get Instance Type Id.
virtual uint32_t GetSerializedSize (void) const
Get Serialized Size.
virtual void Print (std::ostream &os) const
Print tag info.
virtual void Serialize (TagBuffer i) const
Serialize function.
void Set (uint64_t AnimUid)
Set global Uid in tag.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get Type Id.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint64_t m_AnimUid
the UID
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Byte tag using by Anim to uniquely identify packets.
When Anim receives a Tx Notification we tag the packet with a unique global uint64_t identifier before recording Tx information When Anim receives Rx notifications the tag is used to retrieve Tx information recorded earlier
Definition at line 1499 of file animation-interface.h.
Member Function Documentation
Deserialize()
void ns3::AnimByteTag::Deserialize (TagBuffer i) virtual
Deserialize function.
Parameters
i Tag Buffer
Implements ns3::Tag.
Definition at line 2888 of file animation-interface.cc.
References ns3::TagBuffer::ReadU64().
Get()
uint64_t ns3::AnimByteTag::Get (void) const
Get Uid in tag.
Returns
Uid in tag
Definition at line 2906 of file animation-interface.cc.
Referenced by ns3::AnimationInterface::GetAnimUidFromPacket().
GetInstanceTypeId()
TypeId ns3::AnimByteTag::GetInstanceTypeId (void) const virtual
Get Instance Type Id.
Returns
Type Id
Implements ns3::ObjectBase.
Definition at line 2870 of file animation-interface.cc.
Referenced by ns3::AnimationInterface::GetAnimUidFromPacket().
GetSerializedSize()
uint32_t ns3::AnimByteTag::GetSerializedSize (void) const virtual
Get Serialized Size.
Returns
Serialized Size (i.e size of uint64_t)
Implements ns3::Tag.
Definition at line 2876 of file animation-interface.cc.
GetTypeId()
TypeId ns3::AnimByteTag::GetTypeId (void) static
Get Type Id.
Returns
Type Id
Definition at line 2859 of file animation-interface.cc.
References ns3::TypeId::SetParent().
Print()
void ns3::AnimByteTag::Print (std::ostream & os) const virtual
Print tag info.
Parameters
os Reference of ostream object
Implements ns3::Tag.
Definition at line 2894 of file animation-interface.cc.
Serialize()
void ns3::AnimByteTag::Serialize (TagBuffer i) const virtual
Serialize function.
Parameters
i Tag Buffer
Implements ns3::Tag.
Definition at line 2882 of file animation-interface.cc.
References ns3::TagBuffer::WriteU64().
Set()
void ns3::AnimByteTag::Set (uint64_t AnimUid)
Set global Uid in tag.
Parameters
AnimUid global Uid
Definition at line 2900 of file animation-interface.cc.
Referenced by ns3::AnimationInterface::AddByteTag().
Member Data Documentation
m_AnimUid
uint64_t ns3::AnimByteTag::m_AnimUid private
the UID
Definition at line 1559 of file animation-interface.h.
The documentation for this class was generated from the following files:
src/netanim/model/animation-interface.h
src/netanim/model/animation-interface.cc