ns-3: ns3::EpcUeNas Class Reference
ns3::EpcUeNas Class Reference
#include "epc-ue-nas.h"
Classes
struct BearerToBeActivated
BearerToBeActivated structure.
Public Types
enum State {
OFF = 0 , ATTACHING , IDLE_REGISTERED , CONNECTING_TO_EPC ,
ACTIVE , NUM_STATES
}
Definition of NAS states as per "LTE - From theory to practice", Section 3.2.3.2 "Connection Establishment and Release".
typedef void(* StateTracedCallback) (const State oldState, const State newState)
TracedCallback signature for state change events.
Public Member Functions
EpcUeNas ()
Constructor.
virtual ~EpcUeNas ()
Destructor.
void ActivateEpsBearer (EpsBearer bearer, Ptr< EpcTft > tft)
Activate an EPS bearer.
void Connect ()
Causes NAS to tell AS to go to ACTIVE state.
void Connect (uint16_t cellId, uint32_t dlEarfcn)
Causes NAS to tell AS to camp to a specific cell and go to ACTIVE state.
void Disconnect ()
instruct the NAS to disconnect
virtual void DoDispose (void)
Destructor implementation.
LteAsSapUser * GetAsSapUser ()
uint32_t GetCsgId () const
State GetState () const
bool Send (Ptr< Packet > p, uint16_t protocolNumber)
Enqueue an IP packet on the proper bearer for uplink transmission.
void SetAsSapProvider (LteAsSapProvider *s)
Set the AS SAP provider to interact with the NAS entity.
void SetCsgId (uint32_t csgId)
void SetDevice (Ptr< NetDevice > dev)
void SetForwardUpCallback (Callback< void, Ptr< Packet > > cb)
set the callback used to forward data packets up the stack
void SetImsi (uint64_t imsi)
void StartCellSelection (uint32_t dlEarfcn)
Causes NAS to tell AS to find a suitable cell and camp to it.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void DoActivateEpsBearer (EpsBearer bearer, Ptr< EpcTft > tft)
Activate EPS Bearer.
void DoNotifyConnectionFailed ()
Notify connection failed.
void DoNotifyConnectionReleased ()
Notify connection released.
void DoNotifyConnectionSuccessful ()
Notify successful connection.
void DoRecvData (Ptr< Packet > packet)
Receive data.
void SwitchToState (State s)
Switch the UE RRC to the given state.
Private Attributes
LteAsSapProvider * m_asSapProvider
LTE SAP provider.
LteAsSapUser * m_asSapUser
LTE SAP user.
std::list< BearerToBeActivated > m_bearersToBeActivatedList
bearers to be activated list
std::list< BearerToBeActivated > m_bearersToBeActivatedListForReconnection
bearers to be activated list maintained and to be used for reconnecting an out-of-sync UE
uint8_t m_bidCounter
bid counter
uint32_t m_csgId
Closed Subscriber Group identity.
Ptr< NetDevice > m_device
The UE NetDevice.
Callback< void, Ptr< Packet > > m_forwardUpCallback
upward callback
uint64_t m_imsi
The unique UE identifier.
State m_state
The current UE NAS state.
TracedCallback< State, State > m_stateTransitionCallback
The StateTransition trace source.
EpcTftClassifier m_tftClassifier
tft classifier
Friends
class MemberLteAsSapUser< EpcUeNas >
allow MemberLteAsSapUser<EpcUeNas> class friend access
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Config Paths
ns3::EpcUeNas is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteUeNetDevice/EpcUeNas"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteUeNetDevice/EpcUeNas"
No Attributes are defined for this type.
TraceSources
StateTransition: fired upon every UE NAS state transition
Callback signature: ns3::EpcUeNas::StateTracedCallback
Size of this type is 216 bytes (on a 64-bit architecture).
Definition at line 34 of file epc-ue-nas.h.
Member Typedef Documentation
StateTracedCallback
typedef void(* ns3::EpcUeNas::StateTracedCallback) (const State oldState, const State newState)
TracedCallback signature for state change events.
Parameters
[in] oldState The old State.
[in] newState the new State.
Definition at line 183 of file epc-ue-nas.h.
Member Enumeration Documentation
State
enum ns3::EpcUeNas::State
Definition of NAS states as per "LTE - From theory to practice", Section 3.2.3.2 "Connection Establishment and Release".
Enumerator
OFF
ATTACHING
IDLE_REGISTERED
CONNECTING_TO_EPC
ACTIVE
NUM_STATES
Definition at line 162 of file epc-ue-nas.h.
Constructor & Destructor Documentation
EpcUeNas()
ns3::EpcUeNas::EpcUeNas ()
Constructor.
Definition at line 60 of file epc-ue-nas.cc.
References m_asSapUser, MemberLteAsSapUser< EpcUeNas >, and NS_LOG_FUNCTION.
~EpcUeNas()
ns3::EpcUeNas::~EpcUeNas () virtual
Destructor.
Definition at line 71 of file epc-ue-nas.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
ActivateEpsBearer()
void ns3::EpcUeNas::ActivateEpsBearer (EpsBearer bearer, Ptr< EpcTft > tft)
Activate an EPS bearer.
Parameters
bearer the characteristics of the bearer to be created
tft the TFT identifying the traffic that will go on this bearer
Definition at line 187 of file epc-ue-nas.cc.
References ACTIVE, ns3::EpcUeNas::BearerToBeActivated::bearer, m_bearersToBeActivatedList, m_bearersToBeActivatedListForReconnection, m_state, NS_FATAL_ERROR, NS_LOG_FUNCTION, and ns3::EpcUeNas::BearerToBeActivated::tft.
Referenced by ns3::NoBackhaulEpcHelper::DoActivateEpsBearerForUe().
Connect() [1/2]
void ns3::EpcUeNas::Connect ()
Causes NAS to tell AS to go to ACTIVE state.
The end result is equivalent with EMM Registered + ECM Connected states.
Definition at line 156 of file epc-ue-nas.cc.
References ns3::LteAsSapProvider::Connect(), m_asSapProvider, and NS_LOG_FUNCTION.
Connect() [2/2]
void ns3::EpcUeNas::Connect (uint16_t cellId, uint32_t dlEarfcn)
Causes NAS to tell AS to camp to a specific cell and go to ACTIVE state.
Parameters
cellId the id of the eNB to camp on
dlEarfcn the DL frequency of the eNB
The end result is equivalent with EMM Registered + ECM Connected states. Since RRC Idle Mode cell selection is not supported yet, we force the UE RRC to be camped on a specific eNB.
Definition at line 165 of file epc-ue-nas.cc.
References ns3::LteAsSapProvider::Connect(), ns3::LteAsSapProvider::ForceCampedOnEnb(), m_asSapProvider, and NS_LOG_FUNCTION.
Disconnect()
void ns3::EpcUeNas::Disconnect ()
instruct the NAS to disconnect
Definition at line 178 of file epc-ue-nas.cc.
References ns3::LteAsSapProvider::Disconnect(), m_asSapProvider, NS_LOG_FUNCTION, OFF, and SwitchToState().
Referenced by DoNotifyConnectionReleased().
DoActivateEpsBearer()
void ns3::EpcUeNas::DoActivateEpsBearer (EpsBearer bearer, Ptr< EpcTft > tft) private
Activate EPS Bearer.
Parameters
bearer the EPS bearer
tft the EPC TFT
Definition at line 278 of file epc-ue-nas.cc.
References ns3::EpcTftClassifier::Add(), m_bidCounter, m_tftClassifier, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
Referenced by SwitchToState().
DoDispose()
void ns3::EpcUeNas::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 77 of file epc-ue-nas.cc.
References m_asSapUser, and NS_LOG_FUNCTION.
DoNotifyConnectionFailed()
void ns3::EpcUeNas::DoNotifyConnectionFailed () private
Notify connection failed.
Definition at line 246 of file epc-ue-nas.cc.
References ns3::LteAsSapProvider::Connect(), m_asSapProvider, NS_LOG_FUNCTION, and ns3::Simulator::ScheduleNow().
DoNotifyConnectionReleased()
void ns3::EpcUeNas::DoNotifyConnectionReleased () private
Notify connection released.
Definition at line 262 of file epc-ue-nas.cc.
References ns3::EpcTftClassifier::Delete(), Disconnect(), m_bearersToBeActivatedList, m_bearersToBeActivatedListForReconnection, m_bidCounter, m_tftClassifier, and NS_LOG_FUNCTION.
DoNotifyConnectionSuccessful()
void ns3::EpcUeNas::DoNotifyConnectionSuccessful () private
Notify successful connection.
Definition at line 238 of file epc-ue-nas.cc.
References ACTIVE, NS_LOG_FUNCTION, and SwitchToState().
DoRecvData()
void ns3::EpcUeNas::DoRecvData (Ptr< Packet > packet) private
Receive data.
Parameters
packet the packet
Definition at line 255 of file epc-ue-nas.cc.
References m_forwardUpCallback, and NS_LOG_FUNCTION.
GetAsSapUser()
LteAsSapUser * ns3::EpcUeNas::GetAsSapUser ()
Returns
the AS SAP user exported by this RRC
Definition at line 135 of file epc-ue-nas.cc.
References m_asSapUser, and NS_LOG_FUNCTION.
GetCsgId()
uint32_t ns3::EpcUeNas::GetCsgId () const
Returns
csgId Closed Subscriber Group identity
Definition at line 121 of file epc-ue-nas.cc.
References m_csgId, and NS_LOG_FUNCTION.
GetState()
EpcUeNas::State ns3::EpcUeNas::GetState (void) const
Returns
The current state
Definition at line 287 of file epc-ue-nas.cc.
References m_state, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::EpcUeNas::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 84 of file epc-ue-nas.cc.
References m_stateTransitionCallback, ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
Send()
bool ns3::EpcUeNas::Send (Ptr< Packet > p, uint16_t protocolNumber)
Enqueue an IP packet on the proper bearer for uplink transmission.
Parameters
p the packet
protocolNumber the protocol number of the packet
Returns
true if successful, false if an error occurred
Definition at line 207 of file epc-ue-nas.cc.
References ACTIVE, ns3::EpcTftClassifier::Classify(), m_asSapProvider, m_state, m_tftClassifier, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_WARN, ns3::LteAsSapProvider::SendData(), and ns3::EpcTft::UPLINK.
SetAsSapProvider()
void ns3::EpcUeNas::SetAsSapProvider (LteAsSapProvider * s)
Set the AS SAP provider to interact with the NAS entity.
Parameters
s the AS SAP provider
Definition at line 128 of file epc-ue-nas.cc.
References m_asSapProvider, and NS_LOG_FUNCTION.
SetCsgId()
void ns3::EpcUeNas::SetCsgId (uint32_t csgId)
Parameters
csgId Closed Subscriber Group identity
Definition at line 113 of file epc-ue-nas.cc.
References m_asSapProvider, m_csgId, NS_LOG_FUNCTION, and ns3::LteAsSapProvider::SetCsgWhiteList().
SetDevice()
void ns3::EpcUeNas::SetDevice (Ptr< NetDevice > dev)
Parameters
dev the UE NetDevice
Definition at line 99 of file epc-ue-nas.cc.
References m_device, and NS_LOG_FUNCTION.
SetForwardUpCallback()
void ns3::EpcUeNas::SetForwardUpCallback (Callback< void, Ptr< Packet > > cb)
set the callback used to forward data packets up the stack
Parameters
cb the callback
Definition at line 142 of file epc-ue-nas.cc.
References m_forwardUpCallback, and NS_LOG_FUNCTION.
SetImsi()
void ns3::EpcUeNas::SetImsi (uint64_t imsi)
Parameters
imsi the unique UE identifier
Definition at line 106 of file epc-ue-nas.cc.
References m_imsi, and NS_LOG_FUNCTION.
StartCellSelection()
void ns3::EpcUeNas::StartCellSelection (uint32_t dlEarfcn)
Causes NAS to tell AS to find a suitable cell and camp to it.
Parameters
dlEarfcn the DL frequency of the eNB
Definition at line 149 of file epc-ue-nas.cc.
References m_asSapProvider, NS_LOG_FUNCTION, and ns3::LteAsSapProvider::StartCellSelection().
SwitchToState()
void ns3::EpcUeNas::SwitchToState (State s) private
Switch the UE RRC to the given state.
Parameters
s the destination state
Definition at line 294 of file epc-ue-nas.cc.
References ACTIVE, DoActivateEpsBearer(), m_bearersToBeActivatedList, m_imsi, m_state, m_stateTransitionCallback, NS_LOG_FUNCTION, NS_LOG_INFO, and ns3::ToString().
Referenced by Disconnect(), and DoNotifyConnectionSuccessful().
Friends And Related Function Documentation
MemberLteAsSapUser< EpcUeNas >
friend class MemberLteAsSapUser< EpcUeNas > friend
allow MemberLteAsSapUser<EpcUeNas> class friend access
Definition at line 1 of file epc-ue-nas.h.
Referenced by EpcUeNas().
Member Data Documentation
m_asSapProvider
LteAsSapProvider* ns3::EpcUeNas::m_asSapProvider private
LTE SAP provider.
Definition at line 234 of file epc-ue-nas.h.
Referenced by Connect(), Disconnect(), DoNotifyConnectionFailed(), Send(), SetAsSapProvider(), SetCsgId(), and StartCellSelection().
m_asSapUser
LteAsSapUser* ns3::EpcUeNas::m_asSapUser private
LTE SAP user.
Definition at line 236 of file epc-ue-nas.h.
Referenced by EpcUeNas(), DoDispose(), and GetAsSapUser().
m_bearersToBeActivatedList
std::list<BearerToBeActivated> ns3::EpcUeNas::m_bearersToBeActivatedList private
bearers to be activated list
Definition at line 250 of file epc-ue-nas.h.
Referenced by ActivateEpsBearer(), DoNotifyConnectionReleased(), and SwitchToState().
m_bearersToBeActivatedListForReconnection
std::list<BearerToBeActivated> ns3::EpcUeNas::m_bearersToBeActivatedListForReconnection private
bearers to be activated list maintained and to be used for reconnecting an out-of-sync UE
Definition at line 257 of file epc-ue-nas.h.
Referenced by ActivateEpsBearer(), and DoNotifyConnectionReleased().
m_bidCounter
uint8_t ns3::EpcUeNas::m_bidCounter private
bid counter
Definition at line 238 of file epc-ue-nas.h.
Referenced by DoActivateEpsBearer(), and DoNotifyConnectionReleased().
m_csgId
uint32_t ns3::EpcUeNas::m_csgId private
Closed Subscriber Group identity.
Definition at line 231 of file epc-ue-nas.h.
Referenced by GetCsgId(), and SetCsgId().
m_device
Ptr<NetDevice> ns3::EpcUeNas::m_device private
The UE NetDevice.
Definition at line 225 of file epc-ue-nas.h.
Referenced by SetDevice().
m_forwardUpCallback
Callback<void, Ptr<Packet> > ns3::EpcUeNas::m_forwardUpCallback private
upward callback
Definition at line 241 of file epc-ue-nas.h.
Referenced by DoRecvData(), and SetForwardUpCallback().
m_imsi
uint64_t ns3::EpcUeNas::m_imsi private
The unique UE identifier.
Definition at line 228 of file epc-ue-nas.h.
Referenced by SetImsi(), and SwitchToState().
m_state
State ns3::EpcUeNas::m_state private
The current UE NAS state.
Definition at line 215 of file epc-ue-nas.h.
Referenced by ActivateEpsBearer(), GetState(), Send(), and SwitchToState().
m_stateTransitionCallback
TracedCallback<State, State> ns3::EpcUeNas::m_stateTransitionCallback private
The StateTransition trace source.
Fired upon every UE NAS state transition. Exporting old state and new state.
Todo:
This should be a TracedValue
Definition at line 222 of file epc-ue-nas.h.
Referenced by GetTypeId(), and SwitchToState().
m_tftClassifier
EpcTftClassifier ns3::EpcUeNas::m_tftClassifier private
tft classifier
Definition at line 239 of file epc-ue-nas.h.
Referenced by DoActivateEpsBearer(), DoNotifyConnectionReleased(), and Send().
The documentation for this class was generated from the following files:
src/lte/model/epc-ue-nas.h
src/lte/model/epc-ue-nas.cc