ns-3: ns3::dsdv::RoutingProtocol Class Reference
ns3::dsdv::RoutingProtocol Class Reference
DSDV Routing
DSDV routing protocol.
#include "dsdv-routing-protocol.h"
Public Member Functions
RoutingProtocol ()
c-tor
virtual ~RoutingProtocol ()
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
virtual void DoDispose ()
Destructor implementation.
bool GetEnableBufferFlag () const
Get enable buffer flag.
bool GetEnableRAFlag () const
Get enable route aggregation (RA) flag.
bool GetWSTFlag () const
Get weighted settling time (WST) flag.
virtual void NotifyAddAddress (uint32_t interface, Ipv4InterfaceAddress address)
virtual void NotifyInterfaceDown (uint32_t interface)
virtual void NotifyInterfaceUp (uint32_t interface)
virtual void NotifyRemoveAddress (uint32_t interface, Ipv4InterfaceAddress address)
virtual void PrintRoutingTable (Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S) const
Print the Routing Table entries.
bool RouteInput (Ptr< const Packet > p, const Ipv4Header &header, Ptr< const NetDevice > idev, UnicastForwardCallback ucb, MulticastForwardCallback mcb, LocalDeliverCallback lcb, ErrorCallback ecb)
Route input packet.
Ptr< Ipv4Route > RouteOutput (Ptr< Packet > p, const Ipv4Header &header, Ptr< NetDevice > oif, Socket::SocketErrno &sockerr)
Query routing cache for an existing route, for an outbound packet.
void SetEnableBufferFlag (bool f)
Set enable buffer flag.
void SetEnableRAFlag (bool f)
Set enable route aggregation (RA) flag.
virtual void SetIpv4 (Ptr< Ipv4 > ipv4)
void SetWSTFlag (bool f)
Set weighted settling time (WST) flag.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Ipv4RoutingProtocol
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static const uint32_t DSDV_PORT = 269
UDP Port for DSDV control traffic.
Private Member Functions
void DeferredRouteOutput (Ptr< const Packet > p, const Ipv4Header &header, UnicastForwardCallback ucb, ErrorCallback ecb)
Queue packet until we find a route.
void Drop (Ptr< const Packet >, const Ipv4Header &, Socket::SocketErrno)
Notify that packet is dropped for some reason.
Ptr< Socket > FindSocketWithInterfaceAddress (Ipv4InterfaceAddress iface) const
Find socket with local interface address iface.
Time GetSettlingTime (Ipv4Address dst)
Get settlingTime for a destination.
void LookForQueuedPackets (void)
Look for any queued packets to send them out.
Ptr< Ipv4Route > LoopbackRoute (const Ipv4Header &header, Ptr< NetDevice > oif) const
Create loopback route for given header.
void MergeTriggerPeriodicUpdates ()
Merge periodic updates.
void RecvDsdv (Ptr< Socket > socket)
Receive and process dsdv control packet.
void Send (Ptr< Ipv4Route >, Ptr< const Packet >, const Ipv4Header &)
Send packet.
void SendPacketFromQueue (Ipv4Address dst, Ptr< Ipv4Route > route)
Send packet from queue.
void SendPeriodicUpdate ()
Broadcasts the entire routing table for every PeriodicUpdateInterval.
void SendTriggeredUpdate ()
Sends trigger update from a node.
void Start ()
Start protocol operation.
Private Attributes
bool EnableBuffering
Flag that is used to enable or disable buffering.
bool EnableRouteAggregation
This is a flag to enable route aggregation.
bool EnableWST
Flag that is used to enable or disable Weighted Settling Time.
uint32_t Holdtimes
Holdtimes is the multiplicative factor of PeriodicUpdateInterval for which the node waits since the last update before flushing a route from the routing table.
RoutingTable m_advRoutingTable
Advertised Routing table for the node.
ErrorCallback m_ecb
Error callback for own packets.
Ptr< Ipv4 > m_ipv4
IP protocol.
Ptr< NetDevice > m_lo
Loopback device used to defer route requests until a route is found.
Ipv4Address m_mainAddress
Nodes IP address.
uint32_t m_maxQueuedPacketsPerDst
The maximum number of packets that we allow per destination to buffer.
uint32_t m_maxQueueLen
The maximum number of packets that we allow a routing protocol to buffer.
Time m_maxQueueTime
The maximum period of time that a routing protocol is allowed to buffer a packet for.
Time m_periodicUpdateInterval
PeriodicUpdateInterval specifies the periodic time interval between which the a node broadcasts its entire routing table.
Timer m_periodicUpdateTimer
Timer to trigger periodic updates from a node.
PacketQueue m_queue
A "drop front on full" queue used by the routing layer to buffer packets to which it does not have a route.
Time m_routeAggregationTime
Parameter that holds the route aggregation time interval.
RoutingTable m_routingTable
Main Routing table for the node.
UnicastForwardCallback m_scb
Unicast callback for own packets.
Time m_settlingTime
SettlingTime specifies the time for which a node waits before propagating an update.
std::map< Ptr< Socket >, Ipv4InterfaceAddress > m_socketAddresses
Raw socket per each IP interface, map socket -> iface address (IP + mask)
Timer m_triggeredExpireTimer
Timer used by the trigger updates in case of Weighted Settling Time is used.
Ptr< UniformRandomVariable > m_uniformRandomVariable
Provides uniform random variables.
double m_weightedFactor
This is the wighted factor to determine the weighted settling time.
Additional Inherited Members
Public Types inherited from ns3::Ipv4RoutingProtocol
typedef Callback< void, Ptr< const Packet >, const Ipv4Header &, Socket::SocketErrno > ErrorCallback
Callback for routing errors (e.g., no route found)
typedef Callback< void, Ptr< const Packet >, const Ipv4Header &, uint32_t > LocalDeliverCallback
Callback for packets to be locally delivered.
typedef Callback< void, Ptr< Ipv4MulticastRoute >, Ptr< const Packet >, const Ipv4Header & > MulticastForwardCallback
Callback for multicast packets to be forwarded.
typedef Callback< void, Ptr< Ipv4Route >, Ptr< const Packet >, const Ipv4Header & > UnicastForwardCallback
Callback for unicast packets to be forwarded.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
DSDV routing protocol.
Config Paths
ns3::dsdv::RoutingProtocol is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::dsdv::RoutingProtocol"
Attributes
PeriodicUpdateInterval: Periodic interval between exchange of full routing tables among nodes.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1.5e+10ns
Flags: construct write read
SettlingTime: Minimum time an update is to be stored in adv table before sending outin case of change in metric (in seconds)
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +5e+09ns
Flags: construct write read
MaxQueueLen: Maximum number of packets that we allow a routing protocol to buffer.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 500
Flags: construct write read
MaxQueuedPacketsPerDst: Maximum number of packets that we allow per destination to buffer.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 5
Flags: construct write read
MaxQueueTime: Maximum time packets can be queued (in seconds)
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +3e+10ns
Flags: construct write read
EnableBuffering: Enables buffering of data packets if no route to destination is available
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
EnableWST: Enables Weighted Settling Time for the updates before advertising
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
Holdtimes: Times the forwarding Interval to purge the route.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 3
Flags: construct write read
WeightedFactor: WeightedFactor for the settling time if Weighted Settling Time is enabled
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0.875
Flags: construct write read
EnableRouteAggregation: Enables Weighted Settling Time for the updates before advertising
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
RouteAggregationTime: Time to aggregate updates before sending them out (in seconds)
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+09ns
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 432 bytes (on a 64-bit architecture).
Definition at line 53 of file dsdv-routing-protocol.h.
Constructor & Destructor Documentation
RoutingProtocol()
ns3::dsdv::RoutingProtocol::RoutingProtocol ()
c-tor
Definition at line 213 of file dsdv-routing-protocol.cc.
References m_uniformRandomVariable.
~RoutingProtocol()
ns3::dsdv::RoutingProtocol::~RoutingProtocol () virtual
Definition at line 222 of file dsdv-routing-protocol.cc.
Member Function Documentation
AssignStreams()
int64_t ns3::dsdv::RoutingProtocol::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 206 of file dsdv-routing-protocol.cc.
References m_uniformRandomVariable, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
DeferredRouteOutput()
void ns3::dsdv::RoutingProtocol::DeferredRouteOutput (Ptr< const Packet > p, const Ipv4Header & header, UnicastForwardCallback ucb, ErrorCallback ecb) private
Queue packet until we find a route.
Parameters
p the packet to route
header the Ipv4Header
ucb the UnicastForwardCallback function
ecb the ErrorCallback function
Definition at line 358 of file dsdv-routing-protocol.cc.
References ns3::dsdv::PacketQueue::Enqueue(), m_queue, NS_ASSERT, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by RouteInput().
DoDispose()
void ns3::dsdv::RoutingProtocol::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 227 of file dsdv-routing-protocol.cc.
References ns3::Object::DoDispose(), m_ipv4, and m_socketAddresses.
Drop()
void ns3::dsdv::RoutingProtocol::Drop (Ptr< const Packet > packet, const Ipv4Header & header, Socket::SocketErrno err) private
Notify that packet is dropped for some reason.
Definition at line 1109 of file dsdv-routing-protocol.cc.
References ns3::Ipv4Header::GetDestination(), m_mainAddress, and NS_LOG_DEBUG.
Referenced by Start().
FindSocketWithInterfaceAddress()
Ptr< Socket > ns3::dsdv::RoutingProtocol::FindSocketWithInterfaceAddress (Ipv4InterfaceAddress iface) const private
Find socket with local interface address iface.
Parameters
iface the interface
Returns
the socket
Definition at line 1081 of file dsdv-routing-protocol.cc.
References m_socketAddresses.
Referenced by NotifyAddAddress(), NotifyInterfaceDown(), and NotifyRemoveAddress().
GetEnableBufferFlag()
bool ns3::dsdv::RoutingProtocol::GetEnableBufferFlag () const
Get enable buffer flag.
Returns
the enable buffer flag
Definition at line 180 of file dsdv-routing-protocol.cc.
References EnableBuffering.
Referenced by GetTypeId().
GetEnableRAFlag()
bool ns3::dsdv::RoutingProtocol::GetEnableRAFlag () const
Get enable route aggregation (RA) flag.
Returns
the enable route aggregation (RA) flag
Definition at line 200 of file dsdv-routing-protocol.cc.
References EnableRouteAggregation.
Referenced by GetTypeId().
GetSettlingTime()
Time ns3::dsdv::RoutingProtocol::GetSettlingTime (Ipv4Address dst) private
Get settlingTime for a destination.
Parameters
dst - destination address
Returns
settlingTime for the destination if found
Definition at line 1185 of file dsdv-routing-protocol.cc.
References first::address, ns3::Time::As(), EnableWST, ns3::dsdv::RoutingTableEntry::GetLifeTime(), ns3::dsdv::RoutingTableEntry::GetSettlingTime(), ns3::dsdv::RoutingTable::LookupRoute(), m_routingTable, m_weightedFactor, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Time::S, and ns3::Seconds().
Referenced by RecvDsdv().
GetTypeId()
TypeId ns3::dsdv::RoutingProtocol::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 117 of file dsdv-routing-protocol.cc.
References GetEnableBufferFlag(), GetEnableRAFlag(), GetWSTFlag(), Holdtimes, m_maxQueuedPacketsPerDst, m_maxQueueLen, m_maxQueueTime, m_periodicUpdateInterval, m_routeAggregationTime, m_settlingTime, m_weightedFactor, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeDoubleAccessor(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeUintegerAccessor(), ns3::Seconds(), SetEnableBufferFlag(), SetEnableRAFlag(), ns3::TypeId::SetParent(), and SetWSTFlag().
GetWSTFlag()
bool ns3::dsdv::RoutingProtocol::GetWSTFlag () const
Get weighted settling time (WST) flag.
Returns
the weighted settling time (WST) flag
Definition at line 190 of file dsdv-routing-protocol.cc.
References EnableWST.
Referenced by GetTypeId().
LookForQueuedPackets()
void ns3::dsdv::RoutingProtocol::LookForQueuedPackets (void) private
Look for any queued packets to send them out.
Definition at line 1118 of file dsdv-routing-protocol.cc.
References ns3::dsdv::PacketQueue::Find(), ns3::dsdv::RoutingTableEntry::GetDestination(), ns3::Ipv4Route::GetDestination(), ns3::dsdv::RoutingTableEntry::GetHop(), ns3::dsdv::RoutingTable::GetListOfAllRoutes(), ns3::dsdv::RoutingTableEntry::GetNextHop(), ns3::dsdv::RoutingTableEntry::GetRoute(), ns3::Ipv4Route::GetSource(), ns3::dsdv::RoutingTable::LookupRoute(), m_queue, m_routingTable, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, and SendPacketFromQueue().
Referenced by RouteOutput().
LoopbackRoute()
Ptr< Ipv4Route > ns3::dsdv::RoutingProtocol::LoopbackRoute (const Ipv4Header & header, Ptr< NetDevice > oif) const private
Create loopback route for given header.
Parameters
header the IP header
oif the device
Returns
the route
Definition at line 508 of file dsdv-routing-protocol.cc.
References ns3::Ipv4Header::GetDestination(), ns3::Ipv4Route::GetSource(), m_ipv4, m_lo, m_socketAddresses, NS_ASSERT, NS_ASSERT_MSG, ns3::Ipv4Route::SetDestination(), ns3::Ipv4Route::SetGateway(), ns3::Ipv4Route::SetOutputDevice(), and ns3::Ipv4Route::SetSource().
Referenced by RouteOutput().
MergeTriggerPeriodicUpdates()
void ns3::dsdv::RoutingProtocol::MergeTriggerPeriodicUpdates () private
Merge periodic updates.
Definition at line 1211 of file dsdv-routing-protocol.cc.
References ns3::dsdv::RoutingTable::AnyRunningEvent(), ns3::dsdv::RoutingTable::DeleteRoute(), ns3::dsdv::RoutingTableEntry::GetDestination(), ns3::dsdv::RoutingTableEntry::GetEntriesChanged(), ns3::dsdv::RoutingTable::GetListOfAllRoutes(), ns3::dsdv::RoutingTableEntry::GetSeqNo(), m_advRoutingTable, m_routingTable, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::dsdv::RoutingTableEntry::SetEntriesChanged(), ns3::dsdv::RoutingTableEntry::SetFlag(), ns3::dsdv::RoutingTable::Update(), and ns3::dsdv::VALID.
Referenced by SendPeriodicUpdate().
NotifyAddAddress()
void ns3::dsdv::RoutingProtocol::NotifyAddAddress (uint32_t interface, Ipv4InterfaceAddress address) virtual
Parameters
interface the index of the interface we are being notified about
address a new address being added to an interface
Protocols are expected to implement this method to be notified whenever a new address is added to an interface. Typically used to add a 'network route' on an interface. Can be invoked on an up or down interface.
Implements ns3::Ipv4RoutingProtocol.
Definition at line 1024 of file dsdv-routing-protocol.cc.
References first::address, ns3::dsdv::RoutingTable::AddRoute(), ns3::Socket::Bind(), ns3::Socket::BindToNetDevice(), ns3::Socket::CreateSocket(), DSDV_PORT, FindSocketWithInterfaceAddress(), ns3::Ipv4Address::GetAny(), ns3::Ipv4InterfaceAddress::GetBroadcast(), ns3::Ipv4InterfaceAddress::GetLocal(), ns3::Simulator::GetMaximumSimulationTime(), ns3::UdpSocketFactory::GetTypeId(), m_ipv4, m_routingTable, m_socketAddresses, ns3::MakeCallback(), NS_ASSERT, NS_LOG_FUNCTION, RecvDsdv(), ns3::Socket::SetAllowBroadcast(), and ns3::Socket::SetRecvCallback().
NotifyInterfaceDown()
void ns3::dsdv::RoutingProtocol::NotifyInterfaceDown (uint32_t interface) virtual
Parameters
interface the index of the interface we are being notified about
Protocols are expected to implement this method to be notified of the state change of an interface in a node.
Implements ns3::Ipv4RoutingProtocol.
Definition at line 1005 of file dsdv-routing-protocol.cc.
References ns3::dsdv::RoutingTable::Clear(), ns3::Socket::Close(), ns3::dsdv::RoutingTable::DeleteAllRoutesFromInterface(), FindSocketWithInterfaceAddress(), m_advRoutingTable, m_ipv4, m_routingTable, m_socketAddresses, NS_ASSERT, and NS_LOG_LOGIC.
NotifyInterfaceUp()
void ns3::dsdv::RoutingProtocol::NotifyInterfaceUp (uint32_t interface) virtual
Parameters
interface the index of the interface we are being notified about
Protocols are expected to implement this method to be notified of the state change of an interface in a node.
Implements ns3::Ipv4RoutingProtocol.
Definition at line 973 of file dsdv-routing-protocol.cc.
References ns3::dsdv::RoutingTable::AddRoute(), ns3::Socket::Bind(), ns3::Socket::BindToNetDevice(), ns3::Socket::CreateSocket(), DSDV_PORT, ns3::Ipv4Address::GetAny(), ns3::Simulator::GetMaximumSimulationTime(), ns3::UdpSocketFactory::GetTypeId(), m_ipv4, m_mainAddress, m_routingTable, m_socketAddresses, ns3::MakeCallback(), NS_ASSERT, NS_LOG_FUNCTION, RecvDsdv(), ns3::Socket::SetAllowBroadcast(), ns3::ObjectBase::SetAttribute(), and ns3::Socket::SetRecvCallback().
NotifyRemoveAddress()
void ns3::dsdv::RoutingProtocol::NotifyRemoveAddress (uint32_t interface, Ipv4InterfaceAddress address) virtual
Parameters
interface the index of the interface we are being notified about
address a new address being added to an interface
Protocols are expected to implement this method to be notified whenever a new address is removed from an interface. Typically used to remove the 'network route' of an interface. Can be invoked on an up or down interface.
Implements ns3::Ipv4RoutingProtocol.
Definition at line 1057 of file dsdv-routing-protocol.cc.
References first::address, ns3::Socket::Bind(), ns3::Socket::CreateSocket(), DSDV_PORT, FindSocketWithInterfaceAddress(), ns3::Ipv4Address::GetAny(), ns3::UdpSocketFactory::GetTypeId(), m_ipv4, m_socketAddresses, ns3::MakeCallback(), NS_ASSERT, RecvDsdv(), ns3::Socket::SetAllowBroadcast(), and ns3::Socket::SetRecvCallback().
PrintRoutingTable()
void ns3::dsdv::RoutingProtocol::PrintRoutingTable (Ptr< OutputStreamWrapper > stream, Time::Unit unit = Time::S) const virtual
Print the Routing Table entries.
Parameters
stream The ostream the Routing table is printed to
unit The time unit to be used in the report
Implements ns3::Ipv4RoutingProtocol.
Definition at line 240 of file dsdv-routing-protocol.cc.
References ns3::Time::As(), ns3::OutputStreamWrapper::GetStream(), m_ipv4, m_routingTable, ns3::Now(), and ns3::dsdv::RoutingTable::Print().
RecvDsdv()
void ns3::dsdv::RoutingProtocol::RecvDsdv (Ptr< Socket > socket) private
Receive and process dsdv control packet.
Parameters
socket the socket for receiving dsdv control packets
Definition at line 556 of file dsdv-routing-protocol.cc.
References ns3::dsdv::RoutingTable::AddIpv4Event(), ns3::dsdv::RoutingTable::AddRoute(), ns3::dsdv::RoutingTable::AnyRunningEvent(), ns3::Time::As(), ns3::InetSocketAddress::ConvertFrom(), ns3::dsdv::RoutingTable::DeleteRoute(), EnableRouteAggregation, ns3::dsdv::RoutingTable::ForceDeleteIpv4Event(), ns3::Timer::GetDelayLeft(), ns3::dsdv::DsdvHeader::GetDst(), ns3::dsdv::DsdvHeader::GetDstSeqno(), ns3::dsdv::RoutingTableEntry::GetHop(), ns3::dsdv::DsdvHeader::GetHopCount(), ns3::UniformRandomVariable::GetInteger(), ns3::InetSocketAddress::GetIpv4(), ns3::dsdv::RoutingTable::GetListOfAllRoutes(), ns3::dsdv::RoutingTable::GetListOfDestinationWithNextHop(), ns3::dsdv::RoutingTableEntry::GetNextHop(), ns3::dsdv::RoutingTableEntry::GetSeqNo(), GetSettlingTime(), ns3::Packet::GetSize(), ns3::EventId::GetUid(), ns3::Packet::GetUid(), ns3::dsdv::RoutingTable::LookupRoute(), m_advRoutingTable, m_ipv4, m_mainAddress, m_periodicUpdateTimer, m_routeAggregationTime, m_routingTable, m_settlingTime, m_socketAddresses, m_uniformRandomVariable, ns3::MicroSeconds(), ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, packetSize, ns3::Socket::RecvFrom(), ns3::Packet::RemoveHeader(), ns3::Time::S, ns3::Simulator::Schedule(), SendTriggeredUpdate(), ns3::dsdv::RoutingTableEntry::SetEntriesChanged(), ns3::dsdv::RoutingTableEntry::SetFlag(), ns3::dsdv::RoutingTableEntry::SetHop(), ns3::dsdv::RoutingTableEntry::SetLifeTime(), ns3::dsdv::RoutingTableEntry::SetNextHop(), ns3::dsdv::RoutingTableEntry::SetSeqNo(), ns3::dsdv::RoutingTableEntry::SetSettlingTime(), ns3::dsdv::RoutingTable::Update(), and ns3::dsdv::VALID.
Referenced by NotifyAddAddress(), NotifyInterfaceUp(), and NotifyRemoveAddress().
RouteInput()
bool ns3::dsdv::RoutingProtocol::RouteInput (Ptr< const Packet > p, const Ipv4Header & header, Ptr< const NetDevice > idev, UnicastForwardCallback ucb, MulticastForwardCallback mcb, LocalDeliverCallback lcb, ErrorCallback ecb) virtual
Route input packet.
Parameters
p The packet
header The IPv4 header
idev The device
ucb The unicast forward callback
mcb The multicast forward callback
lcb The local deliver callback
ecb The error callback
Returns
true if successful
Implements ns3::Ipv4RoutingProtocol.
Definition at line 374 of file dsdv-routing-protocol.cc.
References DeferredRouteOutput(), EnableBuffering, ns3::Socket::ERROR_NOROUTETOHOST, ns3::NetDevice::GetAddress(), ns3::Ipv4InterfaceAddress::GetBroadcast(), ns3::Ipv4Header::GetDestination(), ns3::Ipv4InterfaceAddress::GetLocal(), ns3::dsdv::RoutingTableEntry::GetNextHop(), ns3::dsdv::RoutingTableEntry::GetRoute(), ns3::Ipv4Header::GetSource(), ns3::Ipv4Header::GetTtl(), ns3::Ipv4Address::IsBroadcast(), ns3::Ipv4Address::IsMulticast(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), ns3::dsdv::RoutingTable::LookupRoute(), m_ipv4, m_lo, m_mainAddress, m_routingTable, m_socketAddresses, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_ERROR, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
RouteOutput()
Ptr< Ipv4Route > ns3::dsdv::RoutingProtocol::RouteOutput (Ptr< Packet > p, const Ipv4Header & header, Ptr< NetDevice > oif, Socket::SocketErrno & sockerr) virtual
Query routing cache for an existing route, for an outbound packet.
This lookup is used by transport protocols. It does not cause any packet to be forwarded, and is synchronous. Can be used for multicast or unicast. The Linux equivalent is ip_route_output()
The header input parameter may have an uninitialized value for the source address, but the destination address should always be properly set by the caller.
Parameters
p packet to be routed. Note that this method may modify the packet. Callers may also pass in a null pointer.
header input parameter (used to form key to search for the route)
oif Output interface Netdevice. May be zero, or may be bound via socket options to a particular output interface.
sockerr Output parameter; socket errno
Returns
a code that indicates what happened in the lookup
Implements ns3::Ipv4RoutingProtocol.
Definition at line 266 of file dsdv-routing-protocol.cc.
References ns3::Packet::AddPacketTag(), ns3::dsdv::RoutingTable::AddRoute(), EnableBuffering, ns3::Socket::ERROR_NOROUTETOHOST, ns3::Socket::ERROR_NOTERROR, ns3::Ipv4Header::GetDestination(), ns3::Ipv4Route::GetDestination(), ns3::dsdv::RoutingTableEntry::GetHop(), ns3::UniformRandomVariable::GetInteger(), ns3::dsdv::RoutingTableEntry::GetNextHop(), ns3::Ipv4Route::GetOutputDevice(), ns3::dsdv::RoutingTableEntry::GetRoute(), ns3::Packet::GetSize(), ns3::Ipv4Route::GetSource(), ns3::Packet::GetUid(), LookForQueuedPackets(), ns3::dsdv::RoutingTable::LookupRoute(), LoopbackRoute(), m_advRoutingTable, m_ipv4, m_routingTable, m_socketAddresses, m_uniformRandomVariable, ns3::MicroSeconds(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Packet::PeekPacketTag(), ns3::dsdv::RoutingTable::Purge(), ns3::Simulator::Schedule(), and SendTriggeredUpdate().
Send()
void ns3::dsdv::RoutingProtocol::Send (Ptr< Ipv4Route > route, Ptr< const Packet > packet, const Ipv4Header & header) private
Send packet.
Definition at line 1098 of file dsdv-routing-protocol.cc.
References ns3::Ipv4Header::GetDestination(), ns3::Ipv4Header::GetProtocol(), ns3::Ipv4Route::GetSource(), m_ipv4, and NS_ASSERT.
Referenced by Start().
SendPacketFromQueue()
void ns3::dsdv::RoutingProtocol::SendPacketFromQueue (Ipv4Address dst, Ptr< Ipv4Route > route) private
Send packet from queue.
Parameters
dst - destination address to which we are sending the packet to
route - route identified for this packet
Definition at line 1154 of file dsdv-routing-protocol.cc.
References ns3::dsdv::PacketQueue::Dequeue(), ns3::dsdv::PacketQueue::Find(), ns3::UniformRandomVariable::GetInteger(), ns3::dsdv::QueueEntry::GetIpv4Header(), ns3::Ipv4Route::GetOutputDevice(), ns3::dsdv::QueueEntry::GetPacket(), ns3::dsdv::PacketQueue::GetSize(), ns3::Ipv4Route::GetSource(), ns3::Ipv4Header::GetTtl(), ns3::dsdv::QueueEntry::GetUnicastForwardCallback(), m_ipv4, m_mainAddress, m_queue, m_uniformRandomVariable, ns3::MilliSeconds(), NS_LOG_DEBUG, ns3::dsdv::DeferredRouteOutputTag::oif, ns3::Packet::RemovePacketTag(), ns3::Simulator::Schedule(), ns3::Ipv4Header::SetSource(), and ns3::Ipv4Header::SetTtl().
Referenced by LookForQueuedPackets().
SendPeriodicUpdate()
void ns3::dsdv::RoutingProtocol::SendPeriodicUpdate () private
Broadcasts the entire routing table for every PeriodicUpdateInterval.
Definition at line 874 of file dsdv-routing-protocol.cc.
References ns3::Packet::AddHeader(), DSDV_PORT, ns3::Ipv4InterfaceAddress::GetBroadcast(), ns3::dsdv::DsdvHeader::GetDst(), ns3::dsdv::DsdvHeader::GetDstSeqno(), ns3::dsdv::DsdvHeader::GetHopCount(), ns3::UniformRandomVariable::GetInteger(), ns3::dsdv::RoutingTable::GetListOfAllRoutes(), ns3::Ipv4InterfaceAddress::GetMask(), ns3::Ipv4Mask::GetOnes(), ns3::Packet::GetUid(), ns3::dsdv::RoutingTable::LookupRoute(), m_ipv4, m_mainAddress, m_periodicUpdateInterval, m_periodicUpdateTimer, m_routingTable, m_socketAddresses, m_uniformRandomVariable, MergeTriggerPeriodicUpdates(), ns3::MicroSeconds(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::dsdv::RoutingTable::Purge(), ns3::Time::S, ns3::Timer::Schedule(), ns3::Socket::Send(), ns3::Socket::SendTo(), ns3::dsdv::DsdvHeader::SetDst(), ns3::dsdv::DsdvHeader::SetDstSeqno(), ns3::dsdv::DsdvHeader::SetHopCount(), ns3::dsdv::RoutingTableEntry::SetSeqNo(), and ns3::dsdv::RoutingTable::Update().
Referenced by Start().
SendTriggeredUpdate()
void ns3::dsdv::RoutingProtocol::SendTriggeredUpdate () private
Sends trigger update from a node.
Definition at line 800 of file dsdv-routing-protocol.cc.
References ns3::Packet::AddHeader(), ns3::dsdv::RoutingTable::AnyRunningEvent(), ns3::dsdv::RoutingTable::DeleteIpv4Event(), ns3::dsdv::RoutingTable::DeleteRoute(), DSDV_PORT, ns3::Ipv4InterfaceAddress::GetBroadcast(), ns3::dsdv::RoutingTableEntry::GetDestination(), ns3::dsdv::DsdvHeader::GetDst(), ns3::dsdv::RoutingTable::GetEventId(), ns3::dsdv::RoutingTableEntry::GetHop(), ns3::dsdv::RoutingTable::GetListOfAllRoutes(), ns3::Ipv4InterfaceAddress::GetMask(), ns3::Ipv4Mask::GetOnes(), ns3::dsdv::RoutingTableEntry::GetSeqNo(), ns3::Packet::GetSize(), ns3::Packet::GetUid(), ns3::dsdv::RoutingTable::LookupRoute(), m_advRoutingTable, m_ipv4, m_mainAddress, m_routingTable, m_socketAddresses, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Socket::SendTo(), ns3::dsdv::DsdvHeader::SetDst(), ns3::dsdv::DsdvHeader::SetDstSeqno(), ns3::dsdv::RoutingTableEntry::SetEntriesChanged(), ns3::dsdv::RoutingTableEntry::SetFlag(), ns3::dsdv::DsdvHeader::SetHopCount(), ns3::dsdv::RoutingTable::Update(), and ns3::dsdv::VALID.
Referenced by RecvDsdv(), and RouteOutput().
SetEnableBufferFlag()
void ns3::dsdv::RoutingProtocol::SetEnableBufferFlag (bool f)
Set enable buffer flag.
Parameters
f The enable buffer flag
Definition at line 175 of file dsdv-routing-protocol.cc.
References EnableBuffering, and f().
Referenced by GetTypeId().
SetEnableRAFlag()
void ns3::dsdv::RoutingProtocol::SetEnableRAFlag (bool f)
Set enable route aggregation (RA) flag.
Parameters
f the enable route aggregation (RA) flag
Definition at line 195 of file dsdv-routing-protocol.cc.
References EnableRouteAggregation, and f().
Referenced by GetTypeId().
SetIpv4()
void ns3::dsdv::RoutingProtocol::SetIpv4 (Ptr< Ipv4 > ipv4) virtual
Parameters
ipv4 the ipv4 object this routing protocol is being associated with
Typically, invoked directly or indirectly from ns3::Ipv4::SetRoutingProtocol
Implements ns3::Ipv4RoutingProtocol.
Definition at line 948 of file dsdv-routing-protocol.cc.
References ns3::dsdv::RoutingTable::AddRoute(), ns3::Ipv4Address::GetLoopback(), ns3::Simulator::GetMaximumSimulationTime(), ns3::dsdv::INVALID, m_ipv4, m_lo, m_routingTable, NS_ASSERT, ns3::Simulator::ScheduleNow(), ns3::dsdv::RoutingTableEntry::SetEntriesChanged(), ns3::dsdv::RoutingTableEntry::SetFlag(), and Start().
SetWSTFlag()
void ns3::dsdv::RoutingProtocol::SetWSTFlag (bool f)
Set weighted settling time (WST) flag.
Parameters
f the weighted settling time (WST) flag
Definition at line 185 of file dsdv-routing-protocol.cc.
References EnableWST, and f().
Referenced by GetTypeId().
Start()
void ns3::dsdv::RoutingProtocol::Start (void) private
Start protocol operation.
Definition at line 252 of file dsdv-routing-protocol.cc.
References Drop(), ns3::UniformRandomVariable::GetInteger(), Holdtimes, m_advRoutingTable, m_ecb, m_maxQueuedPacketsPerDst, m_maxQueueLen, m_maxQueueTime, m_periodicUpdateInterval, m_periodicUpdateTimer, m_queue, m_routingTable, m_scb, m_uniformRandomVariable, ns3::MakeCallback(), ns3::MicroSeconds(), ns3::Timer::Schedule(), Send(), SendPeriodicUpdate(), ns3::Timer::SetFunction(), ns3::dsdv::RoutingTable::Setholddowntime(), ns3::dsdv::PacketQueue::SetMaxPacketsPerDst(), ns3::dsdv::PacketQueue::SetMaxQueueLen(), and ns3::dsdv::PacketQueue::SetQueueTimeout().
Referenced by SetIpv4().
Member Data Documentation
DSDV_PORT
const uint32_t ns3::dsdv::RoutingProtocol::DSDV_PORT = 269 static
UDP Port for DSDV control traffic.
Definition at line 61 of file dsdv-routing-protocol.h.
Referenced by NotifyAddAddress(), NotifyInterfaceUp(), NotifyRemoveAddress(), SendPeriodicUpdate(), and SendTriggeredUpdate().
EnableBuffering
bool ns3::dsdv::RoutingProtocol::EnableBuffering private
Flag that is used to enable or disable buffering.
Definition at line 167 of file dsdv-routing-protocol.h.
Referenced by GetEnableBufferFlag(), RouteInput(), RouteOutput(), and SetEnableBufferFlag().
EnableRouteAggregation
bool ns3::dsdv::RoutingProtocol::EnableRouteAggregation private
This is a flag to enable route aggregation.
Route aggregation will aggregate all routes for 'RouteAggregationTime' from the time an update is received by a node and sends them as a single update .
Definition at line 174 of file dsdv-routing-protocol.h.
Referenced by GetEnableRAFlag(), RecvDsdv(), and SetEnableRAFlag().
EnableWST
bool ns3::dsdv::RoutingProtocol::EnableWST private
Flag that is used to enable or disable Weighted Settling Time.
Definition at line 169 of file dsdv-routing-protocol.h.
Referenced by GetSettlingTime(), GetWSTFlag(), and SetWSTFlag().
Holdtimes
uint32_t ns3::dsdv::RoutingProtocol::Holdtimes private
Holdtimes is the multiplicative factor of PeriodicUpdateInterval for which the node waits since the last update before flushing a route from the routing table.
If PeriodicUpdateInterval is 8s and Holdtimes is 3, the node waits for 24s since the last update to flush this route from its routing table.
Definition at line 139 of file dsdv-routing-protocol.h.
Referenced by GetTypeId(), and Start().
m_advRoutingTable
RoutingTable ns3::dsdv::RoutingProtocol::m_advRoutingTable private
Advertised Routing table for the node.
Definition at line 157 of file dsdv-routing-protocol.h.
Referenced by MergeTriggerPeriodicUpdates(), NotifyInterfaceDown(), RecvDsdv(), RouteOutput(), SendTriggeredUpdate(), and Start().
m_ecb
ErrorCallback ns3::dsdv::RoutingProtocol::m_ecb private
Error callback for own packets.
Definition at line 180 of file dsdv-routing-protocol.h.
Referenced by Start().
m_ipv4
Ptr<Ipv4> ns3::dsdv::RoutingProtocol::m_ipv4 private
IP protocol.
Definition at line 149 of file dsdv-routing-protocol.h.
Referenced by DoDispose(), LoopbackRoute(), NotifyAddAddress(), NotifyInterfaceDown(), NotifyInterfaceUp(), NotifyRemoveAddress(), PrintRoutingTable(), RecvDsdv(), RouteInput(), RouteOutput(), Send(), SendPacketFromQueue(), SendPeriodicUpdate(), SendTriggeredUpdate(), and SetIpv4().
m_lo
Ptr<NetDevice> ns3::dsdv::RoutingProtocol::m_lo private
Loopback device used to defer route requests until a route is found.
Definition at line 153 of file dsdv-routing-protocol.h.
Referenced by LoopbackRoute(), RouteInput(), and SetIpv4().
m_mainAddress
Ipv4Address ns3::dsdv::RoutingProtocol::m_mainAddress private
Nodes IP address.
Definition at line 147 of file dsdv-routing-protocol.h.
Referenced by Drop(), NotifyInterfaceUp(), RecvDsdv(), RouteInput(), SendPacketFromQueue(), SendPeriodicUpdate(), and SendTriggeredUpdate().
m_maxQueuedPacketsPerDst
uint32_t ns3::dsdv::RoutingProtocol::m_maxQueuedPacketsPerDst private
The maximum number of packets that we allow per destination to buffer.
Definition at line 161 of file dsdv-routing-protocol.h.
Referenced by GetTypeId(), and Start().
m_maxQueueLen
uint32_t ns3::dsdv::RoutingProtocol::m_maxQueueLen private
The maximum number of packets that we allow a routing protocol to buffer.
Definition at line 159 of file dsdv-routing-protocol.h.
Referenced by GetTypeId(), and Start().
m_maxQueueTime
Time ns3::dsdv::RoutingProtocol::m_maxQueueTime private
The maximum period of time that a routing protocol is allowed to buffer a packet for.
Definition at line 163 of file dsdv-routing-protocol.h.
Referenced by GetTypeId(), and Start().
m_periodicUpdateInterval
Time ns3::dsdv::RoutingProtocol::m_periodicUpdateInterval private
PeriodicUpdateInterval specifies the periodic time interval between which the a node broadcasts its entire routing table.
Definition at line 142 of file dsdv-routing-protocol.h.
Referenced by GetTypeId(), SendPeriodicUpdate(), and Start().
m_periodicUpdateTimer
Timer ns3::dsdv::RoutingProtocol::m_periodicUpdateTimer private
Timer to trigger periodic updates from a node.
Definition at line 252 of file dsdv-routing-protocol.h.
Referenced by RecvDsdv(), SendPeriodicUpdate(), and Start().
m_queue
PacketQueue ns3::dsdv::RoutingProtocol::m_queue private
A "drop front on full" queue used by the routing layer to buffer packets to which it does not have a route.
Definition at line 165 of file dsdv-routing-protocol.h.
Referenced by DeferredRouteOutput(), LookForQueuedPackets(), SendPacketFromQueue(), and Start().
m_routeAggregationTime
Time ns3::dsdv::RoutingProtocol::m_routeAggregationTime private
Parameter that holds the route aggregation time interval.
Definition at line 176 of file dsdv-routing-protocol.h.
Referenced by GetTypeId(), and RecvDsdv().
m_routingTable
RoutingTable ns3::dsdv::RoutingProtocol::m_routingTable private
Main Routing table for the node.
Definition at line 155 of file dsdv-routing-protocol.h.
Referenced by GetSettlingTime(), LookForQueuedPackets(), MergeTriggerPeriodicUpdates(), NotifyAddAddress(), NotifyInterfaceDown(), NotifyInterfaceUp(), PrintRoutingTable(), RecvDsdv(), RouteInput(), RouteOutput(), SendPeriodicUpdate(), SendTriggeredUpdate(), SetIpv4(), and Start().
m_scb
UnicastForwardCallback ns3::dsdv::RoutingProtocol::m_scb private
Unicast callback for own packets.
Definition at line 178 of file dsdv-routing-protocol.h.
Referenced by Start().
m_settlingTime
Time ns3::dsdv::RoutingProtocol::m_settlingTime private
SettlingTime specifies the time for which a node waits before propagating an update.
It waits for this time interval in hope of receiving an update with a better metric.
Definition at line 145 of file dsdv-routing-protocol.h.
Referenced by GetTypeId(), and RecvDsdv().
m_socketAddresses
std::map<Ptr<Socket>, Ipv4InterfaceAddress> ns3::dsdv::RoutingProtocol::m_socketAddresses private
Raw socket per each IP interface, map socket -> iface address (IP + mask)
Definition at line 151 of file dsdv-routing-protocol.h.
Referenced by DoDispose(), FindSocketWithInterfaceAddress(), LoopbackRoute(), NotifyAddAddress(), NotifyInterfaceDown(), NotifyInterfaceUp(), NotifyRemoveAddress(), RecvDsdv(), RouteInput(), RouteOutput(), SendPeriodicUpdate(), and SendTriggeredUpdate().
m_triggeredExpireTimer
Timer ns3::dsdv::RoutingProtocol::m_triggeredExpireTimer private
Timer used by the trigger updates in case of Weighted Settling Time is used.
Definition at line 254 of file dsdv-routing-protocol.h.
m_uniformRandomVariable
Ptr<UniformRandomVariable> ns3::dsdv::RoutingProtocol::m_uniformRandomVariable private
Provides uniform random variables.
Definition at line 257 of file dsdv-routing-protocol.h.
Referenced by RoutingProtocol(), AssignStreams(), RecvDsdv(), RouteOutput(), SendPacketFromQueue(), SendPeriodicUpdate(), and Start().
m_weightedFactor
double ns3::dsdv::RoutingProtocol::m_weightedFactor private
This is the wighted factor to determine the weighted settling time.
Definition at line 171 of file dsdv-routing-protocol.h.
Referenced by GetSettlingTime(), and GetTypeId().
The documentation for this class was generated from the following files:
src/dsdv/model/dsdv-routing-protocol.h
src/dsdv/model/dsdv-routing-protocol.cc