ns-3: Experiment Class Reference
Experiment Class Reference
UAN Models
Helper class for UAN CW MAC example.
#include "uan-cw-example.h"
Public Member Functions
Experiment ()
Experiment ()
Experiment ()
Experiment ()
Experiment ()
Default constructor.
Experiment ()
Default constructor.
Experiment ()
Experiment (std::string name)
Experiment (std::string name)
Experiment (std::string name)
bool CommandSetup (int argc, char **argv)
void CreateDualModes (uint32_t fc)
Create m_numRates matching control and data modes.
UanTxMode CreateMode (uint32_t kass, uint32_t fc, bool upperblock, std::string name)
Create a UanTxMode.
std::string GetOutputFileName ()
std::string GetRateManager ()
std::string GetRtsThreshold ()
uint32_t GetScenario ()
void IncrementCw (uint32_t cw)
Compute average throughput for a set of runs, then increment CW.
bool IsMobility ()
bool IsRouting ()
void ReceivePacket (Ptr< Socket > socket)
Receive all available packets from a socket.
void ReceivePacket (Ptr< Socket > socket)
Callback to receive a packet.
void ResetData ()
Save the throughput from a single run.
Gnuplot2dDataset Run (const WifiHelper &wifi, const YansWifiPhyHelper &wifiPhy, const WifiMacHelper &wifiMac, const YansWifiChannelHelper &wifiChannel)
uint32_t Run (const WifiHelper &wifi, const YansWifiPhyHelper &wifiPhy, const WifiMacHelper &wifiMac, const YansWifiChannelHelper &wifiChannel)
Gnuplot2dDataset Run (const WifiHelper &wifi, const YansWifiPhyHelper &wifiPhy, const WifiMacHelper &wifiMac, const YansWifiChannelHelper &wifiChannel, const MobilityHelper &mobility)
int Run (const WifiHelper &wifi, const YansWifiPhyHelper &wifiPhy, const WifiMacHelper &wifiMac, const YansWifiChannelHelper &wifiChannel, uint32_t trialNumber, uint32_t networkSize, double duration, bool pcap, bool infra)
double Run (Parameters params)
Gnuplot2dDataset Run (UanHelper &uan)
Run an experiment across a range of congestion window values.
uint32_t Run (uint32_t param)
Run a parametrized experiment.
void UpdatePositions (NodeContainer &nodes)
Assign new random positions to a set of nodes.
Public Attributes
std::string m_asciitracefile
Name for ascii trace file, default uan-cw-example.asc.
uint32_t m_avgs
Number of topologies to test for each cw point.
std::string m_bhCfgFile
(Unused)
double m_boundary
Size of boundary in meters.
UanModesList m_controlModes
List of UanTxModes used for control channels.
uint32_t m_cwMax
Max CW to simulate.
uint32_t m_cwMin
Min CW to simulate.
uint32_t m_cwStep
CW step size, default 10.
Gnuplot2dDataset m_data
Container for the simulation data.
UanModesList m_dataModes
List of UanTxModes used for data channels.
uint32_t m_dataRate
DataRate in bps.
double m_depth
Depth of transmitting and sink nodes.
bool m_doNode
1 for do max nodes simulation (invalidates AMin and AMax values).
std::string m_gnudatfile
Name for GNU Plot output, default uan-cw-example.gpl.
std::string m_gnuplotfile
Filename for GnuPlot.
uint32_t m_maxRange
Maximum range between gateway and acoustic node.
uint32_t m_numNodes
Number of transmitting nodes.
uint32_t m_numRates
Number of divided rates ((NumberRates+1)TotalRate should be 0).
uint32_t m_packetSize
Generated packet size in bytes.
uint32_t m_pktSize
Packet size in bytes.
Time m_sifs
SIFS time duration.
uint32_t m_simMax
Maximum parameter to test.
uint32_t m_simMin
Minimum parameter to test.
uint32_t m_simStep
Amount to increment param per trial.
Time m_simTime
Simulation run time, default 1000 s.
Time m_slotTime
Slot time duration.
std::vector< double > m_throughputs
Throughput for each run.
uint32_t m_totalRate
Total channel capacity.
Private Member Functions
void AdvancePosition (Ptr< Node > node)
void ApplicationSetup (Ptr< Node > client, Ptr< Node > server, double start, double stop)
void AssignNeighbors (NodeContainer c)
Take the grid map, divide it into 4 quadrants Assign all nodes from each quadrant to a specific container.
void CheckThroughput ()
NodeContainer GenerateNeighbors (NodeContainer c, uint32_t senderId)
Generate 1-hop and 2-hop neighbors of a node in grid topology.
void GenerateTraffic (Ptr< Socket > socket, uint32_t pktSize, uint32_t pktCount, Time pktInterval)
Vector GetPosition (Ptr< Node > node)
Vector GetPosition (Ptr< Node > node)
void ReceivePacket (Ptr< Socket > socket)
void ReceivePacket (Ptr< Socket > socket)
void ReceivePacket (Ptr< Socket > socket)
void SelectSrcDest (NodeContainer c)
Sources and destinations are randomly selected such that a node may be the source for multiple destinations and a node maybe a destination for multiple sources.
void SendMultiDestinations (Ptr< Node > sender, NodeContainer c)
A sender node will set up a flow to each of the its neighbors in its quadrant randomly.
void SetPosition (Ptr< Node > node, Vector position)
void SetPosition (Ptr< Node > node, Vector position)
Ptr< Socket > SetupPacketReceive (Ptr< Node > node)
Ptr< Socket > SetupPacketReceive (Ptr< Node > node)
Ptr< Socket > SetupPacketReceive (Ptr< Node > node)
Private Attributes
uint32_t bytesTotal
NodeContainer containerA
NodeContainer containerB
NodeContainer containerC
NodeContainer containerD
bool enableFlowMon
bool enableMobility
bool enablePcap
bool enableRouting
bool enableTracing
double expMean
uint32_t gridSize
uint32_t m_bytesTotal
Total bytes received.
Gnuplot2dDataset m_output
uint32_t m_pktsTotal
uint32_t nodeDistance
std::string outputFileName
uint32_t packetSize
uint32_t port
std::string rateManager
std::string rtsThreshold
double samplingPeriod
uint32_t scenario
double totalTime
Detailed Description
Helper class for UAN CW MAC example.
Container for the parameters describing a single experiment.
An experiment measures the average throughput for a series of CW values.
See also
uan-cw-example.cc
An experiment samples a range of parameter values. The parameter controls the number of nodes (if m_doNode is true), or the UanMacRcGw MaxReservations attribute.
See also
uan-rc-example.cc
Definition at line 40 of file wifi-adhoc.cc.
Constructor & Destructor Documentation
Experiment() [1/10]
Experiment::Experiment ()
Definition at line 58 of file wifi-adhoc.cc.
Experiment() [2/10]
Experiment::Experiment (std::string name)
Definition at line 62 of file wifi-adhoc.cc.
References m_output, and ns3::Gnuplot2dDataset::SetStyle().
Experiment() [3/10]
Experiment::Experiment ()
Experiment() [4/10]
Experiment::Experiment (std::string name)
Experiment() [5/10]
Experiment::Experiment ()
Experiment() [6/10]
Experiment::Experiment ()
Experiment() [7/10]
Experiment::Experiment (std::string name)
Experiment() [8/10]
Experiment::Experiment ()
Default constructor.
Experiment() [9/10]
Experiment::Experiment ()
Default constructor.
Experiment() [10/10]
Experiment::Experiment ()
Member Function Documentation
AdvancePosition()
void Experiment::AdvancePosition (Ptr< Node > node) private
Definition at line 83 of file wifi-adhoc.cc.
References ns3::Gnuplot2dDataset::Add(), GetPosition(), m_bytesTotal, m_output, ns3::Seconds(), and SetPosition().
Referenced by Run().
ApplicationSetup()
void Experiment::ApplicationSetup (Ptr< Node > client, Ptr< Node > server, double start, double stop) private
Definition at line 375 of file wifi-multirate.cc.
References ns3::Object::GetObject(), ns3::OnOffHelper::Install(), NS_LOG_DEBUG, packetSize, port, PrintPosition(), ns3::Seconds(), ns3::OnOffHelper::SetAttribute(), ns3::OnOffHelper::SetConstantRate(), SetupPacketReceive(), sink, visualizer.core::start(), ns3::ApplicationContainer::Start(), and ns3::ApplicationContainer::Stop().
Referenced by Run(), SelectSrcDest(), and SendMultiDestinations().
AssignNeighbors()
void Experiment::AssignNeighbors (NodeContainer c) private
Take the grid map, divide it into 4 quadrants Assign all nodes from each quadrant to a specific container.
Definition at line 216 of file wifi-multirate.cc.
References ns3::NodeContainer::Add(), containerA, containerB, containerC, containerD, ns3::NodeContainer::Get(), ns3::NodeContainer::GetN(), and gridSize.
Referenced by Run().
CheckThroughput()
void Experiment::CheckThroughput () private
Definition at line 199 of file wifi-multirate.cc.
References ns3::Gnuplot2dDataset::Add(), bytesTotal, m_output, ns3::Now(), samplingPeriod, and ns3::Seconds().
Referenced by Run().
CommandSetup()
bool Experiment::CommandSetup (int argc, char ** argv)
Definition at line 554 of file wifi-multirate.cc.
References second::cmd, enableMobility, enableRouting, outputFileName, packetSize, rateManager, rtsThreshold, samplingPeriod, scenario, and totalTime.
CreateDualModes()
void Experiment::CreateDualModes (uint32_t fc)
Create m_numRates matching control and data modes.
Parameters
fc Mode center frequency offset.
Definition at line 132 of file uan-rc-example.cc.
References ns3::UanModesList::AppendMode(), CreateMode(), m_controlModes, m_dataModes, and m_numRates.
CreateMode()
UanTxMode Experiment::CreateMode (uint32_t kass, uint32_t fc, bool upperblock, std::string name)
Create a UanTxMode.
The mode physical rate is set equal to m_totalRate. The data rate and bandwidth are set to
The center frequency is set to
where the upper sign is taken if upperblock is true.
Parameters
kass Fraction of total bandwidth assigned to mode.
fc Mode center frequency offset.
upperblock Sign choice in setting the center frequency.
name Mode name.
Returns
The new mode.
Definition at line 98 of file uan-rc-example.cc.
References m_numRates, and m_totalRate.
Referenced by CreateDualModes().
GenerateNeighbors()
NodeContainer Experiment::GenerateNeighbors (NodeContainer c, uint32_t senderId) private
Generate 1-hop and 2-hop neighbors of a node in grid topology.
Definition at line 257 of file wifi-multirate.cc.
References ns3::NodeContainer::Add(), and ns3::NodeContainer::Get().
Referenced by Run().
GenerateTraffic()
void Experiment::GenerateTraffic (Ptr< Socket > socket, uint32_t pktSize, uint32_t pktCount, Time pktInterval) private
Definition at line 103 of file wifi-clear-channel-cmu.cc.
References ns3::Socket::Close(), pktSize, and ns3::Socket::Send().
GetOutputFileName()
std::string Experiment::GetOutputFileName () inline
Definition at line 103 of file wifi-multirate.cc.
Referenced by Run().
GetPosition() [1/2]
Vector Experiment::GetPosition (Ptr< Node > node) private
Definition at line 76 of file wifi-adhoc.cc.
References ns3::Object::GetObject(), and third::mobility.
Referenced by AdvancePosition().
GetPosition() [2/2]
Vector Experiment::GetPosition (Ptr< Node > node) private
GetRateManager()
std::string Experiment::GetRateManager () inline
Definition at line 107 of file wifi-multirate.cc.
GetRtsThreshold()
std::string Experiment::GetRtsThreshold () inline
Definition at line 99 of file wifi-multirate.cc.
GetScenario()
uint32_t Experiment::GetScenario () inline
Definition at line 94 of file wifi-multirate.cc.
IncrementCw()
void Experiment::IncrementCw (uint32_t cw)
Compute average throughput for a set of runs, then increment CW.
Parameters
cw CW value for completed runs.
Definition at line 86 of file uan-cw-example.cc.
References ns3::Gnuplot2dDataset::Add(), m_avgs, m_cwStep, m_data, m_throughputs, NS_ASSERT, NS_LOG_DEBUG, and ns3::Config::Set().
Referenced by Run().
IsMobility()
bool Experiment::IsMobility () inline
Definition at line 89 of file wifi-multirate.cc.
IsRouting()
bool Experiment::IsRouting () inline
Definition at line 85 of file wifi-multirate.cc.
ReceivePacket() [1/5]
void Experiment::ReceivePacket (Ptr< Socket > socket) private
Definition at line 99 of file wifi-adhoc.cc.
References ns3::Packet::GetSize(), m_bytesTotal, and ns3::Socket::Recv().
Referenced by Run(), and SetupPacketReceive().
ReceivePacket() [2/5]
void Experiment::ReceivePacket (Ptr< Socket > socket) private
ReceivePacket() [3/5]
void Experiment::ReceivePacket (Ptr< Socket > socket) private
ReceivePacket() [4/5]
void Experiment::ReceivePacket (Ptr< Socket > socket)
Receive all available packets from a socket.
Parameters
socket The receive socket.
ReceivePacket() [5/5]
void Experiment::ReceivePacket (Ptr< Socket > socket)
Callback to receive a packet.
Parameters
socket The socket receiving packets.
ResetData()
void Experiment::ResetData ()
Save the throughput from a single run.
Definition at line 78 of file uan-cw-example.cc.
References ns3::Time::GetSeconds(), m_bytesTotal, m_simTime, m_throughputs, ns3::Now(), and NS_LOG_DEBUG.
Referenced by Run().
Run() [1/7]
uint32_t Experiment::Run (const WifiHelper & wifi, const YansWifiPhyHelper & wifiPhy, const WifiMacHelper & wifiMac, const YansWifiChannelHelper & wifiChannel)
Definition at line 119 of file wifi-adhoc.cc.
References AdvancePosition(), ns3::NodeContainer::Create(), ns3::YansWifiChannelHelper::Create(), first::devices, ns3::NodeContainer::Get(), ns3::OnOffHelper::Install(), ns3::PacketSocketHelper::Install(), m_bytesTotal, m_output, third::mac, third::mobility, third::phy, ns3::Seconds(), ns3::OnOffHelper::SetAttribute(), ns3::OnOffHelper::SetConstantRate(), ns3::PacketSocketAddress::SetPhysicalAddress(), ns3::PacketSocketAddress::SetProtocol(), ns3::PacketSocketAddress::SetSingleDevice(), SetupPacketReceive(), ns3::ApplicationContainer::Start(), ns3::ApplicationContainer::Stop(), and third::wifi.
Run() [2/7]
uint32_t Experiment::Run (const WifiHelper & wifi, const YansWifiPhyHelper & wifiPhy, const WifiMacHelper & wifiMac, const YansWifiChannelHelper & wifiChannel)
Run() [3/7]
Gnuplot2dDataset Experiment::Run (const WifiHelper & wifi, const YansWifiPhyHelper & wifiPhy, const WifiMacHelper & wifiMac, const YansWifiChannelHelper & wifiChannel, const MobilityHelper & mobility)
Definition at line 399 of file wifi-multirate.cc.
References first::address, ApplicationSetup(), AssignNeighbors(), CheckThroughput(), containerA, containerB, containerC, containerD, ns3::NodeContainer::Create(), ns3::YansWifiChannelHelper::Create(), ns3::AsciiTraceHelper::CreateFileStream(), first::devices, enableFlowMon, enableMobility, enablePcap, enableRouting, enableTracing, GenerateNeighbors(), ns3::NodeContainer::Get(), GetOutputFileName(), gridSize, ns3::MobilityHelper::Install(), ns3::InternetStackHelper::Install(), ns3::FlowMonitorHelper::InstallAll(), list, m_output, third::mac, third::mobility, nodeDistance, NS_LOG_DEBUG, third::phy, scenario, ns3::Seconds(), SelectSrcDest(), SendMultiDestinations(), ns3::FlowMonitorHelper::SerializeToXmlFile(), ns3::MobilityHelper::SetMobilityModel(), ns3::MobilityHelper::SetPositionAllocator(), ns3::InternetStackHelper::SetRoutingHelper(), totalTime, and third::wifi.
Run() [4/7]
int Experiment::Run (const WifiHelper & wifi, const YansWifiPhyHelper & wifiPhy, const WifiMacHelper & wifiMac, const YansWifiChannelHelper & wifiChannel, uint32_t trialNumber, uint32_t networkSize, double duration, bool pcap, bool infra)
Definition at line 701 of file wifi-bianchi.cc.
References ns3::Node::AddApplication(), AssociationLog(), BackoffTrace(), backoffTraceFile, ns3::Config::Connect(), ns3::NodeContainer::Create(), ns3::YansWifiChannelHelper::Create(), CwTrace(), cwTraceFile, ns3::Simulator::Destroy(), first::devices, DisassociationLog(), ns3::WifiPhyHelper::DLT_IEEE802_11_RADIO, ns3::NodeContainer::Get(), ns3::NodeContainer::GetN(), ns3::PacketSocketHelper::Install(), third::mac, MacRxTrace(), macRxTraceFile, MacTxTrace(), macTxTraceFile, ns3::MakeCallback(), max, ns3::MicroSeconds(), ns3::MilliSeconds(), third::mobility, NS_LOG_DEBUG, third::phy, PhyRxDoneTrace(), PhyRxDropTrace(), PhyRxErrorTrace(), PhyRxOkTrace(), PhyRxPayloadTrace(), PhyRxTrace(), PhyTxDoneTrace(), PhyTxTrace(), phyTxTraceFile, PI, pktSize, RestartCalc(), ns3::Simulator::Run(), ns3::Simulator::Schedule(), ns3::Seconds(), ns3::PacketSocketAddress::SetPhysicalAddress(), ns3::PacketSocketAddress::SetProtocol(), ns3::PacketSocketAddress::SetSingleDevice(), SocketSendTrace(), socketSendTraceFile, third::ssid, visualizer.core::start(), startTime, ns3::Simulator::Stop(), TracePacketReception(), tracing, and third::wifi.
Run() [5/7]
double Experiment::Run (Parameters params)
Definition at line 102 of file wifi-mixed-network.cc.
References first::address, Parameters::apSupportsGreenfield, Parameters::apType, Parameters::bHasTraffic, third::channel, first::clientApps, ns3::NodeContainer::Create(), ns3::YansWifiChannelHelper::Default(), ns3::Simulator::Destroy(), ns3::WifiPhyHelper::DLT_IEEE802_11_RADIO, Parameters::enableErpProtection, Parameters::enableShortPhyPreamble, Parameters::enableShortSlotTime, Parameters::erpProtectionMode, ns3::ApplicationContainer::Get(), ns3::NodeContainer::Get(), ns3::PointerValue::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::Ipv4Address::GetAny(), ns3::Node::GetDevice(), ns3::WifiNetDevice::GetHtConfiguration(), ns3::WifiNetDevice::GetMac(), Parameters::gHasTraffic, ns3::UdpServerHelper::Install(), ns3::UdpClientHelper::Install(), ns3::OnOffHelper::Install(), ns3::PacketSinkHelper::Install(), Parameters::isUdp, third::mac, ns3::MicroSeconds(), third::mobility, Parameters::nGreenfieldHasTraffic, Parameters::nNonGreenfieldHasTraffic, Parameters::nWifiB, Parameters::nWifiG, Parameters::nWifiNGreenfield, Parameters::nWifiNNonGreenfield, Parameters::payloadSize, third::phy, port, ns3::Simulator::Run(), ns3::Seconds(), ns3::Config::Set(), ns3::OnOffHelper::SetAttribute(), ns3::UdpClientHelper::SetAttribute(), ns3::Config::SetDefault(), ns3::Txop::SetTxopLimit(), Parameters::simulationTime, third::ssid, first::stack, ns3::ApplicationContainer::Start(), ns3::ApplicationContainer::Stop(), ns3::Simulator::Stop(), Parameters::testName, third::wifi, ns3::WIFI_STANDARD_80211b, ns3::WIFI_STANDARD_80211g, ns3::WIFI_STANDARD_80211n_2_4GHZ, and third::wifiApNode.
Run() [6/7]
Gnuplot2dDataset Experiment::Run (UanHelper & uan)
Run an experiment across a range of congestion window values.
Parameters
uan The Uan stack helper to configure nodes in the model.
Returns
The data set of CW values and measured throughput
Definition at line 132 of file uan-cw-example.cc.
References ns3::Object::AggregateObject(), ns3::Socket::Bind(), third::channel, ns3::NodeContainer::Create(), first::devices, ns3::UanHelper::EnableAsciiAll(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::NetDeviceContainer::GetN(), ns3::NodeContainer::GetN(), ns3::Object::GetObject(), ns3::MobilityModel::GetPosition(), ns3::UniformRandomVariable::GetValue(), IncrementCw(), ns3::OnOffHelper::Install(), ns3::UanHelper::Install(), ns3::PacketSocketHelper::Install(), m_asciitracefile, m_avgs, m_boundary, m_bytesTotal, m_cwMax, m_cwMin, m_cwStep, m_data, m_dataRate, m_depth, m_numNodes, m_packetSize, m_simTime, m_slotTime, ns3::MakeCallback(), min, third::mobility, NS_FATAL_ERROR, NS_LOG_DEBUG, ReceivePacket(), ResetData(), ns3::Seconds(), ns3::OnOffHelper::SetAttribute(), ns3::UanHelper::SetMac(), ns3::PacketSocketAddress::SetPhysicalAddress(), ns3::PacketSocketAddress::SetProtocol(), ns3::Socket::SetRecvCallback(), ns3::PacketSocketAddress::SetSingleDevice(), sink, ns3::ApplicationContainer::Start(), ns3::ApplicationContainer::Stop(), UpdatePositions(), and sample-rng-plot::x.
Run() [7/7]
uint32_t Experiment::Run (uint32_t param)
Run a parametrized experiment.
The parameter sets either the number of nodes (if m_doNode is true) or the "a" parameter, which controls the UanMacRcGw MaxReservations attribute.
Parameters
param The parameter value.
Returns
The total number of bytes delivered.
Definition at line 147 of file uan-rc-example.cc.
References ns3::Socket::Bind(), first::devices, ns3::NetDeviceContainer::Get(), ns3::UniformRandomVariable::GetValue(), ns3::OnOffHelper::Install(), ns3::UanHelper::Install(), ns3::PacketSocketHelper::Install(), m_bytesTotal, m_controlModes, m_dataModes, m_doNode, m_maxRange, m_numNodes, m_numRates, m_pktSize, m_sifs, m_simTime, m_totalRate, ns3::MakeCallback(), third::mobility, first::nodes, ReceivePacket(), ns3::Seconds(), ns3::OnOffHelper::SetAttribute(), ns3::UanHelper::SetMac(), ns3::UanHelper::SetPhy(), ns3::PacketSocketAddress::SetPhysicalAddress(), ns3::PacketSocketAddress::SetProtocol(), ns3::Socket::SetRecvCallback(), ns3::PacketSocketAddress::SetSingleDevice(), sink, ns3::ApplicationContainer::Start(), ns3::ApplicationContainer::Stop(), and sample-rng-plot::x.
SelectSrcDest()
void Experiment::SelectSrcDest (NodeContainer c) private
Sources and destinations are randomly selected such that a node may be the source for multiple destinations and a node maybe a destination for multiple sources.
Definition at line 279 of file wifi-multirate.cc.
References ApplicationSetup(), ns3::NodeContainer::Get(), ns3::UniformRandomVariable::GetInteger(), ns3::NodeContainer::GetN(), ns3::ObjectBase::SetAttribute(), and totalTime.
Referenced by Run().
SendMultiDestinations()
void Experiment::SendMultiDestinations (Ptr< Node > sender, NodeContainer c) private
A sender node will set up a flow to each of the its neighbors in its quadrant randomly.
All the flows are exponentially distributed
Definition at line 302 of file wifi-multirate.cc.
References ApplicationSetup(), expMean, ns3::NodeContainer::Get(), ns3::Node::GetId(), ns3::NodeContainer::GetN(), ns3::ExponentialRandomVariable::GetValue(), ns3::UniformRandomVariable::GetValue(), NS_LOG_DEBUG, ns3::ObjectBase::SetAttribute(), visualizer.core::start(), and totalTime.
Referenced by Run().
SetPosition() [1/2]
void Experiment::SetPosition (Ptr< Node > node, Vector position) private
Definition at line 69 of file wifi-adhoc.cc.
References ns3::Object::GetObject(), and third::mobility.
Referenced by AdvancePosition().
SetPosition() [2/2]
void Experiment::SetPosition (Ptr< Node > node, Vector position) private
SetupPacketReceive() [1/3]
Ptr< Socket > Experiment::SetupPacketReceive (Ptr< Node > node) private
Definition at line 109 of file wifi-adhoc.cc.
References ns3::MakeCallback(), ReceivePacket(), and sink.
Referenced by ApplicationSetup(), and Run().
SetupPacketReceive() [2/3]
Ptr<Socket> Experiment::SetupPacketReceive (Ptr< Node > node) private
SetupPacketReceive() [3/3]
Ptr<Socket> Experiment::SetupPacketReceive (Ptr< Node > node) private
UpdatePositions()
void Experiment::UpdatePositions (NodeContainer & nodes)
Assign new random positions to a set of nodes.
New positions are randomly assigned within the bounding box.
Parameters
nodes The nodes to reposition.
Definition at line 106 of file uan-cw-example.cc.
References ns3::Object::GetObject(), ns3::UniformRandomVariable::GetValue(), m_boundary, first::nodes, ns3::Now(), NS_LOG_DEBUG, and ns3::MobilityModel::SetPosition().
Referenced by Run().
Member Data Documentation
bytesTotal
uint32_t Experiment::bytesTotal private
Definition at line 129 of file wifi-multirate.cc.
Referenced by CheckThroughput().
containerA
NodeContainer Experiment::containerA private
Definition at line 142 of file wifi-multirate.cc.
Referenced by AssignNeighbors(), and Run().
containerB
NodeContainer Experiment::containerB private
Definition at line 142 of file wifi-multirate.cc.
Referenced by AssignNeighbors(), and Run().
containerC
NodeContainer Experiment::containerC private
Definition at line 142 of file wifi-multirate.cc.
Referenced by AssignNeighbors(), and Run().
containerD
NodeContainer Experiment::containerD private
Definition at line 142 of file wifi-multirate.cc.
Referenced by AssignNeighbors(), and Run().
enableFlowMon
bool Experiment::enableFlowMon private
Definition at line 138 of file wifi-multirate.cc.
Referenced by Run().
enableMobility
bool Experiment::enableMobility private
Definition at line 140 of file wifi-multirate.cc.
Referenced by CommandSetup(), and Run().
enablePcap
bool Experiment::enablePcap private
Definition at line 136 of file wifi-multirate.cc.
Referenced by Run().
enableRouting
bool Experiment::enableRouting private
Definition at line 139 of file wifi-multirate.cc.
Referenced by CommandSetup(), and Run().
enableTracing
bool Experiment::enableTracing private
Definition at line 137 of file wifi-multirate.cc.
Referenced by Run().
expMean
double Experiment::expMean private
Definition at line 126 of file wifi-multirate.cc.
Referenced by SendMultiDestinations().
gridSize
uint32_t Experiment::gridSize private
Definition at line 131 of file wifi-multirate.cc.
Referenced by AssignNeighbors(), and Run().
m_asciitracefile
std::string Experiment::m_asciitracefile
Name for ascii trace file, default uan-cw-example.asc.
Definition at line 85 of file uan-cw-example.h.
Referenced by Run().
m_avgs
uint32_t Experiment::m_avgs
Number of topologies to test for each cw point.
Definition at line 79 of file uan-cw-example.h.
Referenced by IncrementCw(), and Run().
m_bhCfgFile
std::string Experiment::m_bhCfgFile
(Unused)
Definition at line 86 of file uan-cw-example.h.
m_boundary
double Experiment::m_boundary
Size of boundary in meters.
Definition at line 73 of file uan-cw-example.h.
Referenced by Run(), and UpdatePositions().
m_bytesTotal
uint32_t Experiment::m_bytesTotal private
Total bytes received.
Total number of bytes received in a simulation run.
Definition at line 54 of file wifi-adhoc.cc.
Referenced by AdvancePosition(), ReceivePacket(), ResetData(), and Run().
m_controlModes
UanModesList Experiment::m_controlModes
List of UanTxModes used for control channels.
Definition at line 62 of file uan-rc-example.h.
Referenced by CreateDualModes(), and Run().
m_cwMax
uint32_t Experiment::m_cwMax
Max CW to simulate.
Definition at line 77 of file uan-cw-example.h.
Referenced by Run().
m_cwMin
uint32_t Experiment::m_cwMin
Min CW to simulate.
Definition at line 76 of file uan-cw-example.h.
Referenced by Run().
m_cwStep
uint32_t Experiment::m_cwStep
CW step size, default 10.
Definition at line 78 of file uan-cw-example.h.
Referenced by IncrementCw(), and Run().
m_data
Gnuplot2dDataset Experiment::m_data
Container for the simulation data.
Definition at line 88 of file uan-cw-example.h.
Referenced by IncrementCw(), and Run().
m_dataModes
UanModesList Experiment::m_dataModes
List of UanTxModes used for data channels.
Definition at line 61 of file uan-rc-example.h.
Referenced by CreateDualModes(), and Run().
m_dataRate
uint32_t Experiment::m_dataRate
DataRate in bps.
Definition at line 71 of file uan-cw-example.h.
Referenced by Run().
m_depth
double Experiment::m_depth
Depth of transmitting and sink nodes.
Definition at line 72 of file uan-cw-example.h.
Referenced by Run().
m_doNode
bool Experiment::m_doNode
1 for do max nodes simulation (invalidates AMin and AMax values).
Definition at line 53 of file uan-rc-example.h.
Referenced by Run().
m_gnudatfile
std::string Experiment::m_gnudatfile
Name for GNU Plot output, default uan-cw-example.gpl.
Definition at line 84 of file uan-cw-example.h.
m_gnuplotfile
std::string Experiment::m_gnuplotfile
Filename for GnuPlot.
Definition at line 57 of file uan-rc-example.h.
m_maxRange
uint32_t Experiment::m_maxRange
Maximum range between gateway and acoustic node.
Definition at line 50 of file uan-rc-example.h.
Referenced by Run().
m_numNodes
uint32_t Experiment::m_numNodes
Number of transmitting nodes.
Number of nodes (invalid for m_doNode true).
Definition at line 70 of file uan-cw-example.h.
Referenced by Run().
m_numRates
uint32_t Experiment::m_numRates
Number of divided rates ((NumberRates+1)TotalRate should be 0).
Definition at line 48 of file uan-rc-example.h.
Referenced by CreateDualModes(), CreateMode(), and Run().
m_output
Gnuplot2dDataset Experiment::m_output private
Definition at line 55 of file wifi-adhoc.cc.
Referenced by Experiment(), AdvancePosition(), CheckThroughput(), and Run().
m_packetSize
uint32_t Experiment::m_packetSize
Generated packet size in bytes.
Definition at line 74 of file uan-cw-example.h.
Referenced by Run().
m_pktSize
uint32_t Experiment::m_pktSize
Packet size in bytes.
Definition at line 52 of file uan-rc-example.h.
Referenced by Run().
m_pktsTotal
uint32_t Experiment::m_pktsTotal private
Definition at line 53 of file wifi-clear-channel-cmu.cc.
m_sifs
Time Experiment::m_sifs
SIFS time duration.
Definition at line 54 of file uan-rc-example.h.
Referenced by Run().
m_simMax
uint32_t Experiment::m_simMax
Maximum parameter to test.
Definition at line 46 of file uan-rc-example.h.
m_simMin
uint32_t Experiment::m_simMin
Minimum parameter to test.
Definition at line 45 of file uan-rc-example.h.
m_simStep
uint32_t Experiment::m_simStep
Amount to increment param per trial.
Definition at line 47 of file uan-rc-example.h.
m_simTime
Time Experiment::m_simTime
Simulation run time, default 1000 s.
Simulation time per trial.
Definition at line 82 of file uan-cw-example.h.
Referenced by ResetData(), and Run().
m_slotTime
Time Experiment::m_slotTime
Slot time duration.
Definition at line 81 of file uan-cw-example.h.
Referenced by Run().
m_throughputs
std::vector<double> Experiment::m_throughputs
Throughput for each run.
Definition at line 89 of file uan-cw-example.h.
Referenced by IncrementCw(), and ResetData().
m_totalRate
uint32_t Experiment::m_totalRate
Total channel capacity.
Definition at line 49 of file uan-rc-example.h.
Referenced by CreateMode(), and Run().
nodeDistance
uint32_t Experiment::nodeDistance private
Definition at line 132 of file wifi-multirate.cc.
Referenced by Run().
outputFileName
std::string Experiment::outputFileName private
Definition at line 143 of file wifi-multirate.cc.
Referenced by CommandSetup().
packetSize
uint32_t Experiment::packetSize private
Definition at line 130 of file wifi-multirate.cc.
Referenced by ApplicationSetup(), and CommandSetup().
port
uint32_t Experiment::port private
Definition at line 133 of file wifi-multirate.cc.
Referenced by ApplicationSetup().
rateManager
std::string Experiment::rateManager private
Definition at line 143 of file wifi-multirate.cc.
Referenced by CommandSetup().
rtsThreshold
std::string Experiment::rtsThreshold private
Definition at line 143 of file wifi-multirate.cc.
Referenced by CommandSetup().
samplingPeriod
double Experiment::samplingPeriod private
Definition at line 127 of file wifi-multirate.cc.
Referenced by CheckThroughput(), and CommandSetup().
scenario
uint32_t Experiment::scenario private
Definition at line 134 of file wifi-multirate.cc.
Referenced by CommandSetup(), and Run().
totalTime
double Experiment::totalTime private
Definition at line 125 of file wifi-multirate.cc.
Referenced by CommandSetup(), Run(), SelectSrcDest(), and SendMultiDestinations().
The documentation for this class was generated from the following files:
examples/wireless/wifi-adhoc.cc
examples/wireless/wifi-clear-channel-cmu.cc
examples/wireless/wifi-multirate.cc
src/uan/examples/uan-cw-example.h
src/uan/examples/uan-rc-example.h
examples/wireless/wifi-mixed-network.cc
src/wifi/examples/wifi-bianchi.cc
src/uan/examples/uan-cw-example.cc
src/uan/examples/uan-rc-example.cc