ns-3: InterferenceHelperSequenceTest Class Reference
InterferenceHelperSequenceTest Class Reference
See Bug 991
Public Member Functions
InterferenceHelperSequenceTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
Ptr< Node > CreateOne (Vector pos, Ptr< YansWifiChannel > channel)
Create one function.
void SendOnePacket (Ptr< WifiNetDevice > dev)
Send one packet function.
void SwitchCh (Ptr< WifiNetDevice > dev)
Switch channel function.
Private Attributes
ObjectFactory m_mac
MAC.
ObjectFactory m_manager
manager
ObjectFactory m_propDelay
propagation delay
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
See Bug 991
Definition at line 249 of file wifi-test.cc.
Constructor & Destructor Documentation
InterferenceHelperSequenceTest()
InterferenceHelperSequenceTest::InterferenceHelperSequenceTest ()
Definition at line 281 of file wifi-test.cc.
Member Function Documentation
CreateOne()
Ptr< Node > InterferenceHelperSequenceTest::CreateOne (Vector pos, Ptr< YansWifiChannel > channel) private
Create one function.
Parameters
pos the position
channel the wifi channel
Returns
the node
Definition at line 301 of file wifi-test.cc.
References ns3::Node::AddDevice(), ns3::Object::AggregateObject(), third::channel, ns3::ObjectFactory::Create(), m_mac, m_manager, third::mac, third::mobility, third::phy, ns3::WifiNetDevice::SetMac(), ns3::WifiNetDevice::SetPhy(), ns3::WifiNetDevice::SetRemoteStationManager(), ns3::WIFI_PHY_BAND_5GHZ, ns3::WIFI_PHY_STANDARD_80211a, and ns3::WIFI_STANDARD_80211a.
Referenced by DoRun().
DoRun()
void InterferenceHelperSequenceTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 331 of file wifi-test.cc.
References third::channel, ns3::ObjectFactory::Create(), CreateOne(), ns3::Node::GetDevice(), ns3::Object::GetObject(), m_mac, m_manager, m_propDelay, ns3::Seconds(), SendOnePacket(), ns3::ObjectFactory::SetTypeId(), and SwitchCh().
SendOnePacket()
void InterferenceHelperSequenceTest::SendOnePacket (Ptr< WifiNetDevice > dev) private
Send one packet function.
Parameters
dev the device
Definition at line 287 of file wifi-test.cc.
References ns3::WifiNetDevice::GetBroadcast(), and ns3::WifiNetDevice::Send().
Referenced by DoRun().
SwitchCh()
void InterferenceHelperSequenceTest::SwitchCh (Ptr< WifiNetDevice > dev) private
Switch channel function.
Parameters
dev the device
Definition at line 294 of file wifi-test.cc.
References ns3::WifiNetDevice::GetPhy(), and ns3::WifiPhy::SetChannelNumber().
Referenced by DoRun().
Member Data Documentation
m_mac
ObjectFactory InterferenceHelperSequenceTest::m_mac private
MAC.
Definition at line 277 of file wifi-test.cc.
Referenced by CreateOne(), and DoRun().
m_manager
ObjectFactory InterferenceHelperSequenceTest::m_manager private
manager
Definition at line 276 of file wifi-test.cc.
Referenced by CreateOne(), and DoRun().
m_propDelay
ObjectFactory InterferenceHelperSequenceTest::m_propDelay private
propagation delay
Definition at line 278 of file wifi-test.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/wifi/test/wifi-test.cc