ns-3: ns3::OfdmSendParams Class Reference
ns3::OfdmSendParams Class Reference
OfdmSendParams class.
#include "send-params.h"
Public Member Functions
OfdmSendParams (Ptr< PacketBurst > burst, uint8_t modulationType, uint8_t direction)
Constructor.
~OfdmSendParams ()
Ptr< PacketBurst > GetBurst () const
uint8_t GetDirection () const
uint8_t GetModulationType () const
Public Member Functions inherited from ns3::SendParams
SendParams ()
virtual ~SendParams ()
Private Attributes
Ptr< PacketBurst > m_burst
packet burst
uint8_t m_direction
direction
uint8_t m_modulationType
modulation type
Detailed Description
OfdmSendParams class.
Definition at line 67 of file send-params.h.
Constructor & Destructor Documentation
OfdmSendParams()
ns3::OfdmSendParams::OfdmSendParams (Ptr< PacketBurst > burst, uint8_t modulationType, uint8_t direction)
Constructor.
Parameters
burst packet burst object
modulationType modulation type
direction the direction
Definition at line 36 of file send-params.cc.
~OfdmSendParams()
ns3::OfdmSendParams::~OfdmSendParams ()
Definition at line 45 of file send-params.cc.
Member Function Documentation
GetBurst()
Ptr<PacketBurst> ns3::OfdmSendParams::GetBurst (void) const inline
Returns
the packet burst
Definition at line 82 of file send-params.h.
References m_burst.
Referenced by ns3::SimpleOfdmWimaxPhy::Send().
GetDirection()
uint8_t ns3::OfdmSendParams::GetDirection () const inline
Returns
the direction
Definition at line 98 of file send-params.h.
References m_direction.
Referenced by ns3::SimpleOfdmWimaxPhy::Send().
GetModulationType()
uint8_t ns3::OfdmSendParams::GetModulationType () const inline
Returns
the modulation type
Definition at line 90 of file send-params.h.
References m_modulationType.
Referenced by ns3::SimpleOfdmWimaxPhy::Send().
Member Data Documentation
m_burst
Ptr<PacketBurst> ns3::OfdmSendParams::m_burst private
packet burst
Definition at line 104 of file send-params.h.
Referenced by GetBurst().
m_direction
uint8_t ns3::OfdmSendParams::m_direction private
direction
Definition at line 106 of file send-params.h.
Referenced by GetDirection().
m_modulationType
uint8_t ns3::OfdmSendParams::m_modulationType private
modulation type
Definition at line 105 of file send-params.h.
Referenced by GetModulationType().
The documentation for this class was generated from the following files:
src/wimax/model/send-params.h
src/wimax/model/send-params.cc