ns-3: ns3::UanPhyDual Class Reference
ns3::UanPhyDual Class Reference
UAN Models
Two channel Phy.
#include "uan-phy-dual.h"
Public Member Functions
UanPhyDual ()
Constructor.
virtual ~UanPhyDual ()
Dummy destructor.
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
virtual void Clear (void)
Clear all pointer references.
virtual void EnergyDepletionHandler (void)
Handle the energy depletion event.
virtual void EnergyRechargeHandler (void)
Handle the energy recharge event.
virtual double GetCcaThresholdDb (void)
Get the CCA threshold signal strength required to detect channel busy.
double GetCcaThresholdPhy1 (void) const
Get the CCA threshold signal strength required to detect channel busy.
double GetCcaThresholdPhy2 (void) const
Get the CCA threshold signal strength required to detect channel busy.
virtual Ptr< UanChannel > GetChannel (void) const
Get the attached channel.
virtual Ptr< UanNetDevice > GetDevice (void) const
Get the device hosting this Phy.
virtual UanTxMode GetMode (uint32_t n)
Get a specific transmission mode.
UanModesList GetModesPhy1 (void) const
Get the list of available modes.
UanModesList GetModesPhy2 (void) const
Get the list of available modes.
virtual uint32_t GetNModes (void)
Get the number of transmission modes supported by this Phy.
Ptr< Packet > GetPacketRx (void) const
Get the packet currently being received.
Ptr< UanPhyPer > GetPerModelPhy1 (void) const
Get the error probability model.
Ptr< UanPhyPer > GetPerModelPhy2 (void) const
Get the error probability model.
Ptr< Packet > GetPhy1PacketRx (void) const
Get the packet currently being received.
Ptr< Packet > GetPhy2PacketRx (void) const
Get the packet currently being received.
virtual double GetRxThresholdDb (void)
Get the minimum received signal strength required to receive a packet without errors.
Ptr< UanPhyCalcSinr > GetSinrModelPhy1 (void) const
Get the SINR calculator.
Ptr< UanPhyCalcSinr > GetSinrModelPhy2 (void) const
Get the SINR calculator.
virtual Ptr< UanTransducer > GetTransducer (void)
Get the attached transducer.
virtual double GetTxPowerDb (void)
Get the current transmit power, in dB.
double GetTxPowerDbPhy1 (void) const
Get the current transmit power, in dB.
double GetTxPowerDbPhy2 (void) const
Get the current transmit power, in dB.
bool IsPhy1Idle (void)
bool IsPhy1Rx (void)
bool IsPhy1Tx (void)
bool IsPhy2Idle (void)
bool IsPhy2Rx (void)
bool IsPhy2Tx (void)
virtual bool IsStateBusy (void)
virtual bool IsStateCcaBusy (void)
virtual bool IsStateIdle (void)
virtual bool IsStateRx (void)
virtual bool IsStateSleep (void)
virtual bool IsStateTx (void)
virtual void NotifyIntChange (void)
Called when there has been a change in the amount of interference this node is experiencing from other transmissions.
virtual void NotifyTransStartTx (Ptr< Packet > packet, double txPowerDb, UanTxMode txMode)
Called when a transmission is beginning on the attached transducer.
virtual void RegisterListener (UanPhyListener *listener)
Register a UanPhyListener to be notified of common UanPhy events.
virtual void SendPacket (Ptr< Packet > pkt, uint32_t modeNum)
Send a packet using a specific transmission mode.
virtual void SetCcaThresholdDb (double thresh)
Set the threshold for detecting channel busy.
void SetCcaThresholdPhy1 (double thresh)
Set the threshold for detecting channel busy.
void SetCcaThresholdPhy2 (double thresh)
Set the threshold for detecting channel busy.
virtual void SetChannel (Ptr< UanChannel > channel)
Attach to a channel.
virtual void SetDevice (Ptr< UanNetDevice > device)
Set the device hosting this Phy.
virtual void SetEnergyModelCallback (DeviceEnergyModel::ChangeStateCallback callback)
Set the DeviceEnergyModel callback for UanPhy device.
virtual void SetMac (Ptr< UanMac > mac)
Set the MAC forwarding messages to this Phy.
void SetModesPhy1 (UanModesList modes)
Set the available modes.
void SetModesPhy2 (UanModesList modes)
Set the available modes.
void SetPerModelPhy1 (Ptr< UanPhyPer > per)
Set the error probability model.
void SetPerModelPhy2 (Ptr< UanPhyPer > per)
Set the error probability model.
virtual void SetReceiveErrorCallback (RxErrCallback cb)
Set the callback to be used when a packet is received with errors.
virtual void SetReceiveOkCallback (RxOkCallback cb)
Set the callback to be used when a packet is received without error.
virtual void SetRxThresholdDb (double thresh)
Set the minimum SINR threshold to receive a packet without errors.
void SetSinrModelPhy1 (Ptr< UanPhyCalcSinr > calcSinr)
Set the SINR calculator.
void SetSinrModelPhy2 (Ptr< UanPhyCalcSinr > calcSinr)
Set the SINR calculator.
virtual void SetSleepMode (bool sleep)
Set the Phy SLEEP mode.
virtual void SetTransducer (Ptr< UanTransducer > trans)
Attach a transducer to this Phy.
virtual void SetTxPowerDb (double txpwr)
Set the transmit power.
void SetTxPowerDbPhy1 (double txpwr)
Set the transmit power.
void SetTxPowerDbPhy2 (double txpwr)
Set the transmit power.
virtual void StartRxPacket (Ptr< Packet > pkt, double rxPowerDb, UanTxMode txMode, UanPdp pdp)
Packet arriving from channel: i.e.
Public Member Functions inherited from ns3::UanPhy
void NotifyRxBegin (Ptr< const Packet > packet)
Called when the Phy begins to receive a packet.
void NotifyRxDrop (Ptr< const Packet > packet)
Called when the Phy drops a packet.
void NotifyRxEnd (Ptr< const Packet > packet)
Called when a packet is received without error.
void NotifyTxBegin (Ptr< const Packet > packet)
Called when the transducer begins transmitting a packet.
void NotifyTxDrop (Ptr< const Packet > packet)
Called when the transducer attempts to transmit a new packet while already transmitting a prior packet.
void NotifyTxEnd (Ptr< const Packet > packet)
Called when the transducer finishes transmitting a packet.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Register this type.
Static Public Member Functions inherited from ns3::UanPhy
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose ()
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void RxErrFromSubPhy (Ptr< Packet > pkt, double sinr)
Handle callback and logger for packets received with error.
void RxOkFromSubPhy (Ptr< Packet > pkt, double sinr, UanTxMode mode)
Handle callback and logger for packets received without error.
Private Attributes
Ptr< UanPhy > m_phy1
First Phy layer.
Ptr< UanPhy > m_phy2
Second Phy layer.
RxErrCallback m_recErrCb
Callback when packet received with errors.
RxOkCallback m_recOkCb
Callback when packet received without errors.
ns3::TracedCallback< Ptr< const Packet >, double, UanTxMode > m_rxErrLogger
A packet was received unsuccessfully.
ns3::TracedCallback< Ptr< const Packet >, double, UanTxMode > m_rxOkLogger
A packet was received successfully.
ns3::TracedCallback< Ptr< const Packet >, double, UanTxMode > m_txLogger
A packet was sent from this Phy.
Additional Inherited Members
Public Types inherited from ns3::UanPhy
typedef Callback< void, Ptr< Packet >, double > RxErrCallback
Packet receive error callback function type.
typedef Callback< void, Ptr< Packet >, double, UanTxMode > RxOkCallback
Packet received successfully callback function type.
enum State {
IDLE , CCABUSY , RX , TX ,
SLEEP , DISABLED
}
Enum defining possible Phy states.
typedef void(* TracedCallback) (Ptr< const Packet > pkt, double sinr, UanTxMode mode)
TracedCallback signature for UanPhy packet send/receive events.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Two channel Phy.
A class that wraps two generic UAN Phy layers (UanPhyGen) into a single PHY. This is used to simulate two receivers (and transmitters) that use the same front end hardware. When attached to a UanTransducerHd, this results in a net device able to transmit on one or two channels simultaneously or receive on one or two channels simultaneously but that cannot transmit and receive simultaneously.
Many of the standard PHY functions here become ambiguous. In most cases information for "Phy1" are returned.
Config Paths
ns3::UanPhyDual is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::UanNetDevice/Phy/$ns3::UanPhyDual"
Attributes
CcaThresholdPhy1: Aggregate energy of incoming signals to move to CCA Busy state dB of Phy1.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 10
Flags: construct write read
CcaThresholdPhy2: Aggregate energy of incoming signals to move to CCA Busy state dB of Phy2.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 10
Flags: construct write read
TxPowerPhy1: Transmission output power in dB of Phy1.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 190
Flags: construct write read
TxPowerPhy2: Transmission output power in dB of Phy2.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 190
Flags: construct write read
SupportedModesPhy1: List of modes supported by Phy1.
Set with class: UanModesListValue
Underlying type: UanModesList
Initial value: 3|0|1|1|
Flags: construct write read
SupportedModesPhy2: List of modes supported by Phy2.
Set with class: UanModesListValue
Underlying type: UanModesList
Initial value: 3|0|1|1|
Flags: construct write read
PerModelPhy1: Functor to calculate PER based on SINR and TxMode for Phy1.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::UanPhyPer>
Initial value: ns3::UanPhyPerGenDefault
Flags: construct write read
PerModelPhy2: Functor to calculate PER based on SINR and TxMode for Phy2.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::UanPhyPer>
Initial value: ns3::UanPhyPerGenDefault
Flags: construct write read
SinrModelPhy1: Functor to calculate SINR based on pkt arrivals and modes for Phy1.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::UanPhyCalcSinr>
Initial value: ns3::UanPhyCalcSinrDual
Flags: construct write read
SinrModelPhy2: Functor to calculate SINR based on pkt arrivals and modes for Phy2.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::UanPhyCalcSinr>
Initial value: ns3::UanPhyCalcSinrDual
Flags: construct write read
TraceSources
RxOk: A packet was received successfully.
Callback signature: ns3::UanPhy::TracedCallback
RxError: A packet was received unsuccessfully.
Callback signature: ns3::UanPhy::TracedCallback
Tx: Packet transmission beginning.
Callback signature: ns3::UanPhy::TracedCallback
TraceSources defined in parent class ns3::UanPhy
PhyTxBegin: Trace source indicating a packet has begun transmitting over the channel medium.
Callback signature: ns3::Packet::TracedCallback
PhyTxEnd: Trace source indicating a packet has been completely transmitted over the channel.
Callback signature: ns3::Packet::TracedCallback
PhyTxDrop: Trace source indicating a packet has been dropped by the device during transmission.
Callback signature: ns3::Packet::TracedCallback
PhyRxBegin: Trace source indicating a packet has begun being received from the channel medium by the device.
Callback signature: ns3::Packet::TracedCallback
PhyRxEnd: Trace source indicating a packet has been completely received from the channel medium by the device.
Callback signature: ns3::Packet::TracedCallback
PhyRxDrop: Trace source indicating a packet has been dropped by the device during reception.
Callback signature: ns3::Packet::TracedCallback
Size of this type is 280 bytes (on a 64-bit architecture).
Definition at line 81 of file uan-phy-dual.h.
Constructor & Destructor Documentation
UanPhyDual()
ns3::UanPhyDual::UanPhyDual ()
Constructor.
Definition at line 118 of file uan-phy-dual.cc.
References m_phy1, m_phy2, m_recErrCb, and m_recOkCb.
~UanPhyDual()
ns3::UanPhyDual::~UanPhyDual () virtual
Dummy destructor.
See also
DoDispose
Definition at line 133 of file uan-phy-dual.cc.
Member Function Documentation
AssignStreams()
int64_t ns3::UanPhyDual::AssignStreams (int64_t stream) virtual
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream First stream index to use.
Returns
The number of stream indices assigned by this model.
Implements ns3::UanPhy.
Definition at line 636 of file uan-phy-dual.cc.
References NS_LOG_FUNCTION.
Clear()
void ns3::UanPhyDual::Clear (void) virtual
Clear all pointer references.
Implements ns3::UanPhy.
Definition at line 138 of file uan-phy-dual.cc.
References m_phy1, and m_phy2.
Referenced by DoDispose().
DoDispose()
void ns3::UanPhyDual::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 152 of file uan-phy-dual.cc.
References Clear(), and ns3::Object::DoDispose().
EnergyDepletionHandler()
void ns3::UanPhyDual::EnergyDepletionHandler (void) virtual
Handle the energy depletion event.
Implements ns3::UanPhy.
Definition at line 240 of file uan-phy-dual.cc.
References NS_LOG_DEBUG.
EnergyRechargeHandler()
void ns3::UanPhyDual::EnergyRechargeHandler (void) virtual
Handle the energy recharge event.
Implements ns3::UanPhy.
Definition at line 246 of file uan-phy-dual.cc.
References NS_LOG_DEBUG.
GetCcaThresholdDb()
double ns3::UanPhyDual::GetCcaThresholdDb (void) virtual
Get the CCA threshold signal strength required to detect channel busy.
Returns
The CCA threshold signal strength in dB.
Implements ns3::UanPhy.
Definition at line 366 of file uan-phy-dual.cc.
References m_phy1, and NS_LOG_WARN.
GetCcaThresholdPhy1()
double ns3::UanPhyDual::GetCcaThresholdPhy1 (void) const
Get the CCA threshold signal strength required to detect channel busy.
Returns
The CCA threshold signal strength in dB.
Definition at line 372 of file uan-phy-dual.cc.
References m_phy1.
Referenced by GetTypeId().
GetCcaThresholdPhy2()
double ns3::UanPhyDual::GetCcaThresholdPhy2 (void) const
Get the CCA threshold signal strength required to detect channel busy.
Returns
The CCA threshold signal strength in dB.
Definition at line 377 of file uan-phy-dual.cc.
References m_phy2.
Referenced by GetTypeId().
GetChannel()
Ptr< UanChannel > ns3::UanPhyDual::GetChannel (void) const virtual
Get the attached channel.
Returns
The channel.
Implements ns3::UanPhy.
Definition at line 459 of file uan-phy-dual.cc.
References m_phy1.
GetDevice()
Ptr< UanNetDevice > ns3::UanPhyDual::GetDevice (void) const virtual
Get the device hosting this Phy.
Returns
The net device.
Implements ns3::UanPhy.
Definition at line 464 of file uan-phy-dual.cc.
References m_phy1.
GetMode()
UanTxMode ns3::UanPhyDual::GetMode (uint32_t n) virtual
Get a specific transmission mode.
Parameters
n The mode number.
Returns
The mode.
Implements ns3::UanPhy.
Definition at line 516 of file uan-phy-dual.cc.
References GetNModes(), m_phy1, m_phy2, and sample-rng-plot::n.
GetModesPhy1()
UanModesList ns3::UanPhyDual::GetModesPhy1 (void) const
Get the list of available modes.
Returns
The mode list.
Definition at line 529 of file uan-phy-dual.cc.
References ns3::UanModesListValue::Get(), and m_phy1.
Referenced by GetTypeId().
GetModesPhy2()
UanModesList ns3::UanPhyDual::GetModesPhy2 (void) const
Get the list of available modes.
Returns
The mode list.
Definition at line 538 of file uan-phy-dual.cc.
References ns3::UanModesListValue::Get(), and m_phy2.
Referenced by GetTypeId().
GetNModes()
uint32_t ns3::UanPhyDual::GetNModes (void) virtual
Get the number of transmission modes supported by this Phy.
Returns
The number modes.
Implements ns3::UanPhy.
Definition at line 511 of file uan-phy-dual.cc.
References m_phy1, and m_phy2.
Referenced by GetMode(), and SendPacket().
GetPacketRx()
Ptr< Packet > ns3::UanPhyDual::GetPacketRx (void) const virtual
Get the packet currently being received.
Warning
Returns non-valid pointer if IsStateRx == false.
Returns
The packet.
Implements ns3::UanPhy.
Definition at line 629 of file uan-phy-dual.cc.
References NS_FATAL_ERROR.
GetPerModelPhy1()
Ptr< UanPhyPer > ns3::UanPhyDual::GetPerModelPhy1 (void) const
Get the error probability model.
Returns
The error model.
Definition at line 558 of file uan-phy-dual.cc.
References m_phy1.
Referenced by GetTypeId().
GetPerModelPhy2()
Ptr< UanPhyPer > ns3::UanPhyDual::GetPerModelPhy2 (void) const
Get the error probability model.
Returns
The error model.
Definition at line 566 of file uan-phy-dual.cc.
References m_phy2.
Referenced by GetTypeId().
GetPhy1PacketRx()
Ptr< Packet > ns3::UanPhyDual::GetPhy1PacketRx (void) const
Get the packet currently being received.
Warning
Returns non-valid pointer if IsStateRx == false.
Returns
The packet.
Definition at line 412 of file uan-phy-dual.cc.
References m_phy1.
GetPhy2PacketRx()
Ptr< Packet > ns3::UanPhyDual::GetPhy2PacketRx (void) const
Get the packet currently being received.
Warning
Returns non-valid pointer if IsStateRx == false.
Returns
The packet.
Definition at line 418 of file uan-phy-dual.cc.
References m_phy2.
GetRxThresholdDb()
double ns3::UanPhyDual::GetRxThresholdDb (void) virtual
Get the minimum received signal strength required to receive a packet without errors.
Returns
The minimum required signal strength, in dB.
Implements ns3::UanPhy.
Definition at line 360 of file uan-phy-dual.cc.
References m_phy1.
GetSinrModelPhy1()
Ptr< UanPhyCalcSinr > ns3::UanPhyDual::GetSinrModelPhy1 (void) const
Get the SINR calculator.
Returns
The SINR calculator.
Definition at line 586 of file uan-phy-dual.cc.
References m_phy1.
Referenced by GetTypeId().
GetSinrModelPhy2()
Ptr< UanPhyCalcSinr > ns3::UanPhyDual::GetSinrModelPhy2 (void) const
Get the SINR calculator.
Returns
The SINR calculator.
Definition at line 594 of file uan-phy-dual.cc.
References m_phy2.
Referenced by GetTypeId().
GetTransducer()
Ptr< UanTransducer > ns3::UanPhyDual::GetTransducer (void) virtual
Get the attached transducer.
Returns
The transducer.
Implements ns3::UanPhy.
Definition at line 505 of file uan-phy-dual.cc.
References m_phy1, and NS_LOG_WARN.
GetTxPowerDb()
double ns3::UanPhyDual::GetTxPowerDb (void) virtual
Get the current transmit power, in dB.
Returns
The transmit power.
Implements ns3::UanPhy.
Definition at line 341 of file uan-phy-dual.cc.
References m_phy1, and NS_LOG_WARN.
GetTxPowerDbPhy1()
double ns3::UanPhyDual::GetTxPowerDbPhy1 (void) const
Get the current transmit power, in dB.
Returns
The transmit power.
Definition at line 348 of file uan-phy-dual.cc.
References m_phy1.
Referenced by GetTypeId().
GetTxPowerDbPhy2()
double ns3::UanPhyDual::GetTxPowerDbPhy2 (void) const
Get the current transmit power, in dB.
Returns
The transmit power.
Definition at line 354 of file uan-phy-dual.cc.
References m_phy2.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::UanPhyDual::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 159 of file uan-phy-dual.cc.
References GetCcaThresholdPhy1(), GetCcaThresholdPhy2(), ns3::UanPhyGen::GetDefaultModes(), GetModesPhy1(), GetModesPhy2(), GetPerModelPhy1(), GetPerModelPhy2(), GetSinrModelPhy1(), GetSinrModelPhy2(), GetTxPowerDbPhy1(), GetTxPowerDbPhy2(), m_rxErrLogger, m_rxOkLogger, m_txLogger, ns3::MakeDoubleAccessor(), ns3::MakePointerAccessor(), ns3::MakeTraceSourceAccessor(), ns3::MakeUanModesListAccessor(), ns3::MakeUanModesListChecker(), SetCcaThresholdPhy1(), SetCcaThresholdPhy2(), SetModesPhy1(), SetModesPhy2(), ns3::TypeId::SetParent(), SetPerModelPhy1(), SetPerModelPhy2(), SetSinrModelPhy1(), SetSinrModelPhy2(), SetTxPowerDbPhy1(), and SetTxPowerDbPhy2().
IsPhy1Idle()
bool ns3::UanPhyDual::IsPhy1Idle (void)
Returns
True if Phy is in IDLE state.
Definition at line 383 of file uan-phy-dual.cc.
References m_phy1.
IsPhy1Rx()
bool ns3::UanPhyDual::IsPhy1Rx (void)
Returns
True if Phy is currently in receive mode.
Definition at line 394 of file uan-phy-dual.cc.
References m_phy1.
IsPhy1Tx()
bool ns3::UanPhyDual::IsPhy1Tx (void)
Returns
True if Phy is busy transmitting.
Definition at line 406 of file uan-phy-dual.cc.
References m_phy1.
IsPhy2Idle()
bool ns3::UanPhyDual::IsPhy2Idle (void)
Returns
True if Phy is in IDLE state.
Definition at line 388 of file uan-phy-dual.cc.
References m_phy2.
IsPhy2Rx()
bool ns3::UanPhyDual::IsPhy2Rx (void)
Returns
True if Phy is currently in receive mode.
Definition at line 400 of file uan-phy-dual.cc.
References m_phy2.
IsPhy2Tx()
bool ns3::UanPhyDual::IsPhy2Tx (void)
Returns
True if Phy is busy transmitting.
Definition at line 424 of file uan-phy-dual.cc.
References m_phy2.
IsStateBusy()
bool ns3::UanPhyDual::IsStateBusy (void) virtual
Returns
True if Phy is neither IDLE nor SLEEP.
Implements ns3::UanPhy.
Definition at line 439 of file uan-phy-dual.cc.
References IsStateIdle(), and IsStateSleep().
IsStateCcaBusy()
bool ns3::UanPhyDual::IsStateCcaBusy (void) virtual
Returns
True if Phy is in CCABUSY state.
Implements ns3::UanPhy.
Definition at line 454 of file uan-phy-dual.cc.
References m_phy1, and m_phy2.
IsStateIdle()
bool ns3::UanPhyDual::IsStateIdle (void) virtual
Returns
True if Phy is in IDLE state.
Implements ns3::UanPhy.
Definition at line 434 of file uan-phy-dual.cc.
References m_phy1, and m_phy2.
Referenced by IsStateBusy().
IsStateRx()
bool ns3::UanPhyDual::IsStateRx (void) virtual
Returns
True if Phy is currently in receive mode.
Implements ns3::UanPhy.
Definition at line 444 of file uan-phy-dual.cc.
References m_phy1, and m_phy2.
IsStateSleep()
bool ns3::UanPhyDual::IsStateSleep (void) virtual
Returns
True if Phy is in SLEEP state.
Implements ns3::UanPhy.
Definition at line 429 of file uan-phy-dual.cc.
References m_phy1, and m_phy2.
Referenced by IsStateBusy().
IsStateTx()
bool ns3::UanPhyDual::IsStateTx (void) virtual
Returns
True if Phy is busy transmitting.
Implements ns3::UanPhy.
Definition at line 449 of file uan-phy-dual.cc.
References m_phy1, and m_phy2.
NotifyIntChange()
void ns3::UanPhyDual::NotifyIntChange (void) virtual
Called when there has been a change in the amount of interference this node is experiencing from other transmissions.
Implements ns3::UanPhy.
Definition at line 492 of file uan-phy-dual.cc.
References m_phy1, and m_phy2.
NotifyTransStartTx()
void ns3::UanPhyDual::NotifyTransStartTx (Ptr< Packet > packet, double txPowerDb, UanTxMode txMode) virtual
Called when a transmission is beginning on the attached transducer.
Parameters
packet Packet that is beginning transmission.
txPowerDb Transmit power of packet.
txMode Transmission mode of packet.
Implements ns3::UanPhy.
Definition at line 487 of file uan-phy-dual.cc.
References NS_UNUSED.
RegisterListener()
void ns3::UanPhyDual::RegisterListener (UanPhyListener * listener) virtual
Register a UanPhyListener to be notified of common UanPhy events.
Parameters
listener New listener to register.
Note
You may receive duplicate messages as underneath there are two generic phys here. Each will notify of state changes independently.
Implements ns3::UanPhy.
Definition at line 269 of file uan-phy-dual.cc.
References m_phy1, and m_phy2.
RxErrFromSubPhy()
void ns3::UanPhyDual::RxErrFromSubPhy (Ptr< Packet > pkt, double sinr) private
Handle callback and logger for packets received with error.
Parameters
pkt The packet.
sinr The SINR.
Definition at line 622 of file uan-phy-dual.cc.
References m_phy1, m_recErrCb, and m_rxErrLogger.
RxOkFromSubPhy()
void ns3::UanPhyDual::RxOkFromSubPhy (Ptr< Packet > pkt, double sinr, UanTxMode mode) private
Handle callback and logger for packets received without error.
Parameters
pkt The packet.
sinr The SINR.
mode The channel mode.
Definition at line 614 of file uan-phy-dual.cc.
References m_recOkCb, m_rxOkLogger, ns3::Now(), NS_LOG_DEBUG, and ns3::Time::S.
SendPacket()
void ns3::UanPhyDual::SendPacket (Ptr< Packet > pkt, uint32_t modeNum) virtual
Send a packet using a specific transmission mode.
Parameters
pkt Packet to transmit.
modeNum Index of mode in SupportedModes list to use for transmission.
Implements ns3::UanPhy.
Definition at line 252 of file uan-phy-dual.cc.
References GetNModes(), m_phy1, m_phy2, m_txLogger, ns3::Now(), NS_LOG_DEBUG, and ns3::Time::S.
SetCcaThresholdDb()
void ns3::UanPhyDual::SetCcaThresholdDb (double thresh) virtual
Set the threshold for detecting channel busy.
Parameters
thresh Signal power threshold at receiver.
Implements ns3::UanPhy.
Definition at line 322 of file uan-phy-dual.cc.
References m_phy1, and m_phy2.
SetCcaThresholdPhy1()
void ns3::UanPhyDual::SetCcaThresholdPhy1 (double thresh)
Set the threshold for detecting channel busy.
Parameters
thresh Signal power threshold at receiver.
Definition at line 329 of file uan-phy-dual.cc.
References m_phy1.
Referenced by GetTypeId().
SetCcaThresholdPhy2()
void ns3::UanPhyDual::SetCcaThresholdPhy2 (double thresh)
Set the threshold for detecting channel busy.
Parameters
thresh Signal power threshold at receiver.
Definition at line 334 of file uan-phy-dual.cc.
References m_phy2.
Referenced by GetTypeId().
SetChannel()
void ns3::UanPhyDual::SetChannel (Ptr< UanChannel > channel) virtual
Attach to a channel.
Parameters
channel The channel to attach to.
Implements ns3::UanPhy.
Definition at line 469 of file uan-phy-dual.cc.
References third::channel, m_phy1, and m_phy2.
SetDevice()
void ns3::UanPhyDual::SetDevice (Ptr< UanNetDevice > device) virtual
Set the device hosting this Phy.
Parameters
device The device.
Implements ns3::UanPhy.
Definition at line 475 of file uan-phy-dual.cc.
References m_phy1, and m_phy2.
SetEnergyModelCallback()
void ns3::UanPhyDual::SetEnergyModelCallback (DeviceEnergyModel::ChangeStateCallback callback) virtual
Set the DeviceEnergyModel callback for UanPhy device.
Parameters
callback The DeviceEnergyModel change state callback.
Implements ns3::UanPhy.
Definition at line 234 of file uan-phy-dual.cc.
References NS_LOG_DEBUG.
SetMac()
void ns3::UanPhyDual::SetMac (Ptr< UanMac > mac) virtual
Set the MAC forwarding messages to this Phy.
Parameters
mac The MAC.
Implements ns3::UanPhy.
Definition at line 481 of file uan-phy-dual.cc.
References m_phy1, m_phy2, and third::mac.
SetModesPhy1()
void ns3::UanPhyDual::SetModesPhy1 (UanModesList modes)
Set the available modes.
Parameters
modes List of modes.
Definition at line 546 of file uan-phy-dual.cc.
References m_phy1.
Referenced by GetTypeId().
SetModesPhy2()
void ns3::UanPhyDual::SetModesPhy2 (UanModesList modes)
Set the available modes.
Parameters
modes List of modes.
Definition at line 552 of file uan-phy-dual.cc.
References m_phy2.
Referenced by GetTypeId().
SetPerModelPhy1()
void ns3::UanPhyDual::SetPerModelPhy1 (Ptr< UanPhyPer > per)
Set the error probability model.
Parameters
per The error model.
Definition at line 574 of file uan-phy-dual.cc.
References m_phy1.
Referenced by GetTypeId().
SetPerModelPhy2()
void ns3::UanPhyDual::SetPerModelPhy2 (Ptr< UanPhyPer > per)
Set the error probability model.
Parameters
per The error model.
Definition at line 580 of file uan-phy-dual.cc.
References m_phy2.
Referenced by GetTypeId().
SetReceiveErrorCallback()
void ns3::UanPhyDual::SetReceiveErrorCallback (RxErrCallback cb) virtual
Set the callback to be used when a packet is received with errors.
Parameters
cb The callback.
Implements ns3::UanPhy.
Definition at line 290 of file uan-phy-dual.cc.
References m_phy1, and m_phy2.
SetReceiveOkCallback()
void ns3::UanPhyDual::SetReceiveOkCallback (RxOkCallback cb) virtual
Set the callback to be used when a packet is received without error.
Parameters
cb The callback.
Implements ns3::UanPhy.
Definition at line 283 of file uan-phy-dual.cc.
References m_phy1, and m_phy2.
SetRxThresholdDb()
void ns3::UanPhyDual::SetRxThresholdDb (double thresh) virtual
Set the minimum SINR threshold to receive a packet without errors.
Deprecated:
See UanPhyPer.
Parameters
thresh Threshold SINR for proper reception in dB re 1 uPa.
Implements ns3::UanPhy.
Definition at line 316 of file uan-phy-dual.cc.
References m_phy1, and m_phy2.
SetSinrModelPhy1()
void ns3::UanPhyDual::SetSinrModelPhy1 (Ptr< UanPhyCalcSinr > calcSinr)
Set the SINR calculator.
Parameters
calcSinr The SINR calculator.
Definition at line 602 of file uan-phy-dual.cc.
References m_phy1.
Referenced by GetTypeId().
SetSinrModelPhy2()
void ns3::UanPhyDual::SetSinrModelPhy2 (Ptr< UanPhyCalcSinr > calcSinr)
Set the SINR calculator.
Parameters
calcSinr The SINR calculator.
Definition at line 608 of file uan-phy-dual.cc.
References m_phy2.
Referenced by GetTypeId().
SetSleepMode()
virtual void ns3::UanPhyDual::SetSleepMode (bool sleep) inline virtual
Set the Phy SLEEP mode.
Parameters
sleep SLEEP on or off.
Todo:
This method has to be implemented
Implements ns3::UanPhy.
Definition at line 138 of file uan-phy-dual.h.
References NS_UNUSED.
SetTransducer()
void ns3::UanPhyDual::SetTransducer (Ptr< UanTransducer > trans) virtual
Attach a transducer to this Phy.
Parameters
trans The transducer.
Implements ns3::UanPhy.
Definition at line 499 of file uan-phy-dual.cc.
References m_phy1, and m_phy2.
SetTxPowerDb()
void ns3::UanPhyDual::SetTxPowerDb (double txpwr) virtual
Set the transmit power.
Parameters
txpwr Final output transmission power, in dB.
Implements ns3::UanPhy.
Definition at line 298 of file uan-phy-dual.cc.
References m_phy1, and m_phy2.
SetTxPowerDbPhy1()
void ns3::UanPhyDual::SetTxPowerDbPhy1 (double txpwr)
Set the transmit power.
Parameters
txpwr Final output transmission power, in dB.
Definition at line 305 of file uan-phy-dual.cc.
References m_phy1.
Referenced by GetTypeId().
SetTxPowerDbPhy2()
void ns3::UanPhyDual::SetTxPowerDbPhy2 (double txpwr)
Set the transmit power.
Parameters
txpwr Final output transmission power, in dB.
Definition at line 310 of file uan-phy-dual.cc.
References m_phy2.
Referenced by GetTypeId().
StartRxPacket()
void ns3::UanPhyDual::StartRxPacket (Ptr< Packet > pkt, double rxPowerDb, UanTxMode txMode, UanPdp pdp) virtual
Packet arriving from channel: i.e.
leading bit of packet has arrived.
Parameters
pkt Packet which is arriving.
rxPowerDb Signal power of incoming packet in dB re 1 uPa.
txMode Transmission mode defining modulation of incoming packet.
pdp Power delay profile of incoming packet.
Implements ns3::UanPhy.
Definition at line 276 of file uan-phy-dual.cc.
References NS_UNUSED.
Member Data Documentation
m_phy1
Ptr<UanPhy> ns3::UanPhyDual::m_phy1 private
First Phy layer.
Definition at line 243 of file uan-phy-dual.h.
Referenced by UanPhyDual(), Clear(), GetCcaThresholdDb(), GetCcaThresholdPhy1(), GetChannel(), GetDevice(), GetMode(), GetModesPhy1(), GetNModes(), GetPerModelPhy1(), GetPhy1PacketRx(), GetRxThresholdDb(), GetSinrModelPhy1(), GetTransducer(), GetTxPowerDb(), GetTxPowerDbPhy1(), IsPhy1Idle(), IsPhy1Rx(), IsPhy1Tx(), IsStateCcaBusy(), IsStateIdle(), IsStateRx(), IsStateSleep(), IsStateTx(), NotifyIntChange(), RegisterListener(), RxErrFromSubPhy(), SendPacket(), SetCcaThresholdDb(), SetCcaThresholdPhy1(), SetChannel(), SetDevice(), SetMac(), SetModesPhy1(), SetPerModelPhy1(), SetReceiveErrorCallback(), SetReceiveOkCallback(), SetRxThresholdDb(), SetSinrModelPhy1(), SetTransducer(), SetTxPowerDb(), and SetTxPowerDbPhy1().
m_phy2
Ptr<UanPhy> ns3::UanPhyDual::m_phy2 private
Second Phy layer.
Definition at line 245 of file uan-phy-dual.h.
Referenced by UanPhyDual(), Clear(), GetCcaThresholdPhy2(), GetMode(), GetModesPhy2(), GetNModes(), GetPerModelPhy2(), GetPhy2PacketRx(), GetSinrModelPhy2(), GetTxPowerDbPhy2(), IsPhy2Idle(), IsPhy2Rx(), IsPhy2Tx(), IsStateCcaBusy(), IsStateIdle(), IsStateRx(), IsStateSleep(), IsStateTx(), NotifyIntChange(), RegisterListener(), SendPacket(), SetCcaThresholdDb(), SetCcaThresholdPhy2(), SetChannel(), SetDevice(), SetMac(), SetModesPhy2(), SetPerModelPhy2(), SetReceiveErrorCallback(), SetReceiveOkCallback(), SetRxThresholdDb(), SetSinrModelPhy2(), SetTransducer(), SetTxPowerDb(), and SetTxPowerDbPhy2().
m_recErrCb
RxErrCallback ns3::UanPhyDual::m_recErrCb private
Callback when packet received with errors.
Definition at line 256 of file uan-phy-dual.h.
Referenced by UanPhyDual(), and RxErrFromSubPhy().
m_recOkCb
RxOkCallback ns3::UanPhyDual::m_recOkCb private
Callback when packet received without errors.
Definition at line 254 of file uan-phy-dual.h.
Referenced by UanPhyDual(), and RxOkFromSubPhy().
m_rxErrLogger
ns3::TracedCallback<Ptr<const Packet>, double, UanTxMode > ns3::UanPhyDual::m_rxErrLogger private
A packet was received unsuccessfully.
Definition at line 250 of file uan-phy-dual.h.
Referenced by GetTypeId(), and RxErrFromSubPhy().
m_rxOkLogger
ns3::TracedCallback<Ptr<const Packet>, double, UanTxMode > ns3::UanPhyDual::m_rxOkLogger private
A packet was received successfully.
Definition at line 248 of file uan-phy-dual.h.
Referenced by GetTypeId(), and RxOkFromSubPhy().
m_txLogger
ns3::TracedCallback<Ptr<const Packet>, double, UanTxMode > ns3::UanPhyDual::m_txLogger private
A packet was sent from this Phy.
Definition at line 252 of file uan-phy-dual.h.
Referenced by GetTypeId(), and SendPacket().
The documentation for this class was generated from the following files:
src/uan/model/uan-phy-dual.h
src/uan/model/uan-phy-dual.cc