ns-3: ns3::BasicEnergyHarvester Class Reference
ns3::BasicEnergyHarvester Class Reference
Energy Models
BasicEnergyHarvester increases remaining energy stored in an associated Energy Source.
#include "basic-energy-harvester.h"
Public Member Functions
BasicEnergyHarvester ()
BasicEnergyHarvester (Time updateInterval)
virtual ~BasicEnergyHarvester ()
int64_t AssignStreams (int64_t stream)
Time GetHarvestedPowerUpdateInterval (void) const
void SetHarvestedPowerUpdateInterval (Time updateInterval)
Public Member Functions inherited from ns3::EnergyHarvester
EnergyHarvester ()
virtual ~EnergyHarvester ()
Ptr< EnergySource > GetEnergySource (void) const
Ptr< Node > GetNode (void) const
double GetPower (void) const
void SetEnergySource (Ptr< EnergySource > source)
void SetNode (Ptr< Node > node)
Sets pointer to node containing this EnergyHarvester.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::EnergyHarvester
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void CalculateHarvestedPower (void)
Calculates harvested Power.
void DoDispose (void)
Defined in ns3::Object.
virtual double DoGetPower (void) const
void DoInitialize (void)
Defined in ns3::Object.
void UpdateHarvestedPower (void)
This function is called every m_energyHarvestingUpdateInterval in order to update the amount of power that will be provided by the harvester in the next interval.
Private Attributes
EventId m_energyHarvestingUpdateEvent
Ptr< RandomVariableStream > m_harvestablePower
TracedValue< double > m_harvestedPower
Time m_harvestedPowerUpdateInterval
Time m_lastHarvestingUpdateTime
TracedValue< double > m_totalEnergyHarvestedJ
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
BasicEnergyHarvester increases remaining energy stored in an associated Energy Source.
Introspection did not find any typical Config paths.
The BasicEnergyHarvester implements a simple model in which the amount of power provided by the harvester varies over time according to a customizable generic random variable and time update intervals.
Unit of power is chosen as Watt since energy models typically calculate energy as (time in seconds * power in Watt).
Attributes
PeriodicHarvestedPowerUpdateInterval: Time between two consecutive periodic updates of the harvested power. By default, the value is updated every 1 s
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+09ns
Flags: construct write read
HarvestablePower: The harvestable power [Watts] that the energy harvester is allowed to harvest. By default, the model will allow to harvest an amount of power defined by a uniformly distributed random variable in 0 and 2.0 Watts
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::RandomVariableStream>
Initial value: ns3::UniformRandomVariable[Min=0.0|Max=2.0]
Flags: construct write read
TraceSources
HarvestedPower: Harvested power by the BasicEnergyHarvester.
Callback signature: ns3::TracedValueCallback::Double
TotalEnergyHarvested: Total energy harvested by the harvester.
Callback signature: ns3::TracedValueCallback::Double
Size of this type is 160 bytes (on a 64-bit architecture).
Definition at line 48 of file basic-energy-harvester.h.
Constructor & Destructor Documentation
BasicEnergyHarvester() [1/2]
ns3::BasicEnergyHarvester::BasicEnergyHarvester ()
Definition at line 67 of file basic-energy-harvester.cc.
References NS_LOG_FUNCTION.
BasicEnergyHarvester() [2/2]
ns3::BasicEnergyHarvester::BasicEnergyHarvester (Time updateInterval)
Parameters
updateInterval Energy harvesting update interval.
BasicEnergyHarvester constructor function that sets the interval between each update of the value of the power harvested by this energy harvester.
Definition at line 72 of file basic-energy-harvester.cc.
References m_harvestedPowerUpdateInterval, and NS_LOG_FUNCTION.
~BasicEnergyHarvester()
ns3::BasicEnergyHarvester::~BasicEnergyHarvester () virtual
Definition at line 78 of file basic-energy-harvester.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AssignStreams()
int64_t ns3::BasicEnergyHarvester::AssignStreams (int64_t stream)
Parameters
stream Random variable stream number.
Returns
The number of stream indices assigned by this model.
This function sets the stream number to be used by the random variable that determines the amount of power that can be harvested by this energy harvester.
Definition at line 84 of file basic-energy-harvester.cc.
References m_harvestablePower, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
CalculateHarvestedPower()
void ns3::BasicEnergyHarvester::CalculateHarvestedPower (void) private
Calculates harvested Power.
Definition at line 166 of file basic-energy-harvester.cc.
References ns3::RandomVariableStream::GetValue(), m_harvestablePower, m_harvestedPower, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::Time::S.
Referenced by UpdateHarvestedPower().
DoDispose()
void ns3::BasicEnergyHarvester::DoDispose (void) private virtual
Defined in ns3::Object.
Reimplemented from ns3::EnergyHarvester.
Definition at line 160 of file basic-energy-harvester.cc.
References NS_LOG_FUNCTION.
DoGetPower()
double ns3::BasicEnergyHarvester::DoGetPower (void) const private virtual
Returns
m_harvestedPower The power currently provided by the Basic Energy Harvester. Implements DoGetPower defined in EnergyHarvester.
Reimplemented from ns3::EnergyHarvester.
Definition at line 177 of file basic-energy-harvester.cc.
References m_harvestedPower, and NS_LOG_FUNCTION.
DoInitialize()
void ns3::BasicEnergyHarvester::DoInitialize (void) private virtual
Defined in ns3::Object.
Reimplemented from ns3::Object.
Definition at line 150 of file basic-energy-harvester.cc.
References m_lastHarvestingUpdateTime, ns3::Simulator::Now(), NS_LOG_FUNCTION, and UpdateHarvestedPower().
GetHarvestedPowerUpdateInterval()
Time ns3::BasicEnergyHarvester::GetHarvestedPowerUpdateInterval (void) const
Returns
The interval between each update of the harvested power.
This function returns the interval between each update of the value of the power harvested by this energy harvester.
Definition at line 99 of file basic-energy-harvester.cc.
References m_harvestedPowerUpdateInterval, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::BasicEnergyHarvester::GetTypeId (void) static
Definition at line 38 of file basic-energy-harvester.cc.
References GetHarvestedPowerUpdateInterval(), m_harvestablePower, m_harvestedPower, m_totalEnergyHarvestedJ, ns3::MakePointerAccessor(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::Seconds(), SetHarvestedPowerUpdateInterval(), and ns3::TypeId::SetParent().
SetHarvestedPowerUpdateInterval()
void ns3::BasicEnergyHarvester::SetHarvestedPowerUpdateInterval (Time updateInterval)
Parameters
updateInterval Energy harvesting update interval.
This function sets the interval between each update of the value of the power harvested by this energy harvester.
Definition at line 92 of file basic-energy-harvester.cc.
References m_harvestedPowerUpdateInterval, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
UpdateHarvestedPower()
void ns3::BasicEnergyHarvester::UpdateHarvestedPower (void) private
This function is called every m_energyHarvestingUpdateInterval in order to update the amount of power that will be provided by the harvester in the next interval.
Definition at line 110 of file basic-energy-harvester.cc.
References CalculateHarvestedPower(), ns3::EventId::Cancel(), ns3::EnergyHarvester::GetEnergySource(), ns3::Time::GetNanoSeconds(), ns3::EnergyHarvester::GetNode(), ns3::Time::GetSeconds(), ns3::Simulator::IsFinished(), m_energyHarvestingUpdateEvent, m_harvestedPower, m_harvestedPowerUpdateInterval, m_lastHarvestingUpdateTime, m_totalEnergyHarvestedJ, ns3::Simulator::Now(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Time::S, and ns3::Simulator::Schedule().
Referenced by DoInitialize().
Member Data Documentation
m_energyHarvestingUpdateEvent
EventId ns3::BasicEnergyHarvester::m_energyHarvestingUpdateEvent private
Definition at line 123 of file basic-energy-harvester.h.
Referenced by UpdateHarvestedPower().
m_harvestablePower
Ptr<RandomVariableStream> ns3::BasicEnergyHarvester::m_harvestablePower private
Definition at line 118 of file basic-energy-harvester.h.
Referenced by AssignStreams(), CalculateHarvestedPower(), and GetTypeId().
m_harvestedPower
TracedValue<double> ns3::BasicEnergyHarvester::m_harvestedPower private
Definition at line 120 of file basic-energy-harvester.h.
Referenced by CalculateHarvestedPower(), DoGetPower(), GetTypeId(), and UpdateHarvestedPower().
m_harvestedPowerUpdateInterval
Time ns3::BasicEnergyHarvester::m_harvestedPowerUpdateInterval private
Definition at line 125 of file basic-energy-harvester.h.
Referenced by BasicEnergyHarvester(), GetHarvestedPowerUpdateInterval(), SetHarvestedPowerUpdateInterval(), and UpdateHarvestedPower().
m_lastHarvestingUpdateTime
Time ns3::BasicEnergyHarvester::m_lastHarvestingUpdateTime private
Definition at line 124 of file basic-energy-harvester.h.
Referenced by DoInitialize(), and UpdateHarvestedPower().
m_totalEnergyHarvestedJ
TracedValue<double> ns3::BasicEnergyHarvester::m_totalEnergyHarvestedJ private
Definition at line 121 of file basic-energy-harvester.h.
Referenced by GetTypeId(), and UpdateHarvestedPower().
The documentation for this class was generated from the following files:
src/energy/model/basic-energy-harvester.h
src/energy/model/basic-energy-harvester.cc