ns-3: ns3::ChannelList Class Reference
ns3::ChannelList Class Reference
Network
the list of simulation channels.
#include "channel-list.h"
Public Types
typedef std::vector< Ptr< Channel > >::const_iterator Iterator
Channel container iterator.
Static Public Member Functions
static uint32_t Add (Ptr< Channel > channel)
static Iterator Begin (void)
static Iterator End (void)
static Ptr< Channel > GetChannel (uint32_t n)
static uint32_t GetNChannels (void)
Detailed Description
the list of simulation channels.
Every Channel created is automatically added to this list.
Definition at line 38 of file channel-list.h.
Member Typedef Documentation
Iterator
typedef std::vector< Ptr<Channel> >::const_iterator ns3::ChannelList::Iterator
Channel container iterator.
Definition at line 42 of file channel-list.h.
Member Function Documentation
Add()
uint32_t ns3::ChannelList::Add (Ptr< Channel > channel) static
Parameters
channel channel to add
Returns
index of channel in list.
This method is called automatically from Channel::Channel so the user has little reason to call it himself.
Definition at line 214 of file channel-list.cc.
References third::channel, ns3::ChannelListPriv::Get(), and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Channel::Channel().
Begin()
ChannelList::Iterator ns3::ChannelList::Begin (void) static
Returns
a C++ iterator located at the beginning of this list.
Definition at line 221 of file channel-list.cc.
References ns3::ChannelListPriv::Get(), and NS_LOG_FUNCTION_NOARGS.
End()
ChannelList::Iterator ns3::ChannelList::End (void) static
Returns
a C++ iterator located at the end of this list.
Definition at line 228 of file channel-list.cc.
References ns3::ChannelListPriv::Get(), and NS_LOG_FUNCTION_NOARGS.
GetChannel()
Ptr< Channel > ns3::ChannelList::GetChannel (uint32_t n) static
Parameters
n index of requested channel.
Returns
the Channel associated to index n.
Definition at line 235 of file channel-list.cc.
References ns3::ChannelListPriv::Get(), sample-rng-plot::n, and NS_LOG_FUNCTION.
GetNChannels()
uint32_t ns3::ChannelList::GetNChannels (void) static
Returns
the number of channels currently in the list.
Definition at line 242 of file channel-list.cc.
References ns3::ChannelListPriv::Get(), and NS_LOG_FUNCTION_NOARGS.
The documentation for this class was generated from the following files:
src/network/model/channel-list.h
src/network/model/channel-list.cc