ns-3: ns3::Ipv4Mask Class Reference
ns3::Ipv4Mask Class Reference
Network » Address
a class to represent an Ipv4 address mask
#include "ipv4-address.h"
Public Member Functions
Ipv4Mask ()
Will initialize to a garbage value (0x66666666)
Ipv4Mask (char const *mask)
Ipv4Mask (uint32_t mask)
uint32_t Get (void) const
Get the host-order 32-bit IP mask.
uint32_t GetInverse (void) const
Return the inverse mask in host order.
uint16_t GetPrefixLength (void) const
NS_DEPRECATED_3_31 bool IsEqual (Ipv4Mask other) const
bool IsMatch (Ipv4Address a, Ipv4Address b) const
void Print (std::ostream &os) const
Print this mask to the given output stream.
void Set (uint32_t mask)
input mask is in host order.
Static Public Member Functions
static Ipv4Mask GetLoopback (void)
static Ipv4Mask GetOnes (void)
static Ipv4Mask GetZero (void)
Private Attributes
uint32_t m_mask
IP mask.
Friends
bool operator!= (Ipv4Mask const &a, Ipv4Mask const &b)
Not equal to operator.
bool operator== (Ipv4Mask const &a, Ipv4Mask const &b)
Equal to operator.
Detailed Description
a class to represent an Ipv4 address mask
The constructor takes arguments according to a few formats. Ipv4Mask ("255.255.255.255"), Ipv4Mask ("/32"), and Ipv4Mask (0xffffffff) are all equivalent.
See also
Ipv4Mask Attribute
Definition at line 269 of file ipv4-address.h.
Constructor & Destructor Documentation
Ipv4Mask() [1/3]
ns3::Ipv4Mask::Ipv4Mask ()
Will initialize to a garbage value (0x66666666)
Definition at line 78 of file ipv4-address.cc.
References NS_LOG_FUNCTION.
Referenced by GetLoopback(), GetOnes(), and GetZero().
Ipv4Mask() [2/3]
ns3::Ipv4Mask::Ipv4Mask (uint32_t mask)
Parameters
mask bitwise integer representation of the mask
For example, the integer input 0xffffff00 yields a 24-bit mask
Definition at line 84 of file ipv4-address.cc.
References NS_LOG_FUNCTION.
Ipv4Mask() [3/3]
ns3::Ipv4Mask::Ipv4Mask (char const * mask)
Parameters
mask String constant either in "255.255.255.0" or "/24" format
Definition at line 90 of file ipv4-address.cc.
References ASCII_SLASH, ns3::AsciiToIpv4Host(), m_mask, NS_ASSERT, and NS_LOG_FUNCTION.
Member Function Documentation
Get()
uint32_t ns3::Ipv4Mask::Get (void) const
Get the host-order 32-bit IP mask.
Returns
the host-order 32-bit IP mask
Definition at line 135 of file ipv4-address.cc.
References m_mask, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4InterfaceAddress::Ipv4InterfaceAddress(), ns3::Ipv4Address::CombineMask(), ns3::Ipv4AddressGeneratorImpl::Init(), ns3::Ipv4AddressGeneratorImpl::MaskToIndex(), ns3::GlobalRouter::ProcessBridgedBroadcastLink(), ns3::GlobalRouter::ProcessPointToPointLink(), ns3::GlobalRouter::ProcessSingleBroadcastLink(), ns3::DhcpServer::SendOffer(), ns3::RipRte::Serialize(), and ns3::Ipv4AddressHelper::SetBase().
GetInverse()
uint32_t ns3::Ipv4Mask::GetInverse (void) const
Return the inverse mask in host order.
Returns
The inverse mask
Definition at line 147 of file ipv4-address.cc.
References m_mask, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4Address::GetSubnetDirectedBroadcast(), and ns3::Ipv4Address::IsSubnetDirectedBroadcast().
GetLoopback()
Ipv4Mask ns3::Ipv4Mask::GetLoopback (void) static
Returns
the 255.0.0.0 mask corresponding to a typical loopback address
Definition at line 165 of file ipv4-address.cc.
References Ipv4Mask(), and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Ipv4L3Protocol::SetupLoopback().
GetOnes()
Ipv4Mask ns3::Ipv4Mask::GetOnes (void) static
Returns
the 255.255.255.255 mask
Definition at line 179 of file ipv4-address.cc.
References Ipv4Mask(), and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Ipv4StaticRouting::AddHostRouteTo(), ns3::TapBridge::CreateTap(), ns3::Ipv4Address::GetSubnetDirectedBroadcast(), ns3::Ipv4RoutingTableEntry::IsHost(), ns3::Ipv4Address::IsSubnetDirectedBroadcast(), ns3::Ipv4StaticRouting::NotifyInterfaceUp(), ns3::aodv::RoutingProtocol::RecvRequest(), ns3::aodv::RoutingProtocol::SendHello(), ns3::dsdv::RoutingProtocol::SendPeriodicUpdate(), ns3::aodv::RoutingProtocol::SendRequest(), ns3::aodv::RoutingProtocol::SendRerrMessage(), ns3::aodv::RoutingProtocol::SendRerrWhenNoRouteToForward(), and ns3::dsdv::RoutingProtocol::SendTriggeredUpdate().
GetPrefixLength()
uint16_t ns3::Ipv4Mask::GetPrefixLength (void) const
Returns
the prefix length of mask (the yy in x.x.x.x/yy notation)
Definition at line 187 of file ipv4-address.cc.
References m_mask, and NS_LOG_FUNCTION.
Referenced by ns3::PlanetLabFdNetDeviceHelper::CreateFileDescriptor(), ns3::Ipv4StaticRouting::GetDefaultRoute(), ns3::Ipv4EndPointDemux::Lookup(), ns3::Rip::Lookup(), ns3::Ipv4StaticRouting::LookupStatic(), ns3::RipRte::Print(), ns3::GlobalRouter::ProcessBridgedBroadcastLink(), and ns3::GlobalRouter::ProcessSingleBroadcastLink().
GetZero()
Ipv4Mask ns3::Ipv4Mask::GetZero (void) static
Returns
the 0.0.0.0 mask
Definition at line 172 of file ipv4-address.cc.
References Ipv4Mask(), NS_LOG_FUNCTION_NOARGS, and zero.
Referenced by ns3::TapFdNetDeviceHelper::TapFdNetDeviceHelper(), ns3::Rip::AddDefaultRouteTo(), ns3::Ipv4RoutingTableEntry::CreateDefaultRoute(), ns3::TapFdNetDeviceHelper::CreateFileDescriptor(), ns3::Rip::DoSendRouteUpdate(), ns3::Rip::HandleRequests(), ns3::Rip::SendRouteRequest(), and ns3::Ipv4StaticRouting::SetDefaultRoute().
IsEqual()
bool ns3::Ipv4Mask::IsEqual (Ipv4Mask other) const
Deprecated:
Use the == operator (same functionality)
Parameters
other a mask to compare
Returns
true if the mask equals the mask passed as input parameter
Definition at line 113 of file ipv4-address.cc.
References m_mask, and NS_LOG_FUNCTION.
IsMatch()
bool ns3::Ipv4Mask::IsMatch (Ipv4Address a, Ipv4Address b) const
Parameters
a first address to compare
b second address to compare
Returns
true if both addresses are equal in their masked bits, corresponding to this mask
Definition at line 124 of file ipv4-address.cc.
References ns3::Ipv4Address::Get(), m_mask, and NS_LOG_FUNCTION.
Referenced by ns3::Rip::Lookup(), ns3::Ipv4GlobalRouting::LookupGlobal(), and ns3::Ipv4StaticRouting::LookupStatic().
Print()
void ns3::Ipv4Mask::Print (std::ostream & os) const
Print this mask to the given output stream.
The print format is in the typical "255.255.255.0"
Parameters
os The output stream to which this Ipv4Address is printed
Definition at line 154 of file ipv4-address.cc.
References m_mask, and NS_LOG_FUNCTION.
Referenced by ns3::NscTcpL4Protocol::AddInterface(), and ns3::operator<<().
Set()
void ns3::Ipv4Mask::Set (uint32_t mask)
input mask is in host order.
Parameters
mask The host order 32-bit mask
Definition at line 141 of file ipv4-address.cc.
References m_mask, and NS_LOG_FUNCTION.
Referenced by EpcTftClassifierTestSuite::EpcTftClassifierTestSuite(), and ns3::RipRte::Deserialize().
Friends And Related Function Documentation
operator!=
bool operator!= (Ipv4Mask const & a, Ipv4Mask const & b) friend
Not equal to operator.
Parameters
a the first operand.
b the first operand.
Returns
true if the operands are not equal.
Parameters
a the first operand
b the first operand
Returns
true if the operands are not equal
Definition at line 467 of file ipv4-address.h.
operator==
bool operator== (Ipv4Mask const & a, Ipv4Mask const & b) friend
Equal to operator.
Parameters
a the first operand.
b the first operand.
Returns
true if the operands are equal.
Parameters
a the first operand
b the first operand
Returns
true if the operands are equal
Definition at line 455 of file ipv4-address.h.
Member Data Documentation
m_mask
uint32_t ns3::Ipv4Mask::m_mask private
IP mask.
Definition at line 360 of file ipv4-address.h.
Referenced by Ipv4Mask(), Get(), GetInverse(), GetPrefixLength(), IsEqual(), IsMatch(), Print(), and Set().
The documentation for this class was generated from the following files:
src/network/utils/ipv4-address.h
src/network/utils/ipv4-address.cc