ns-3: ns3::NetmapNetDeviceHelper Class Reference
ns3::NetmapNetDeviceHelper Class Reference
File Descriptor Network Device
build a set of FdNetDevice objects attached to a physical network interface
#include "netmap-net-device-helper.h"
Public Member Functions
NetmapNetDeviceHelper ()
virtual ~NetmapNetDeviceHelper ()
std::string GetDeviceName (void)
Get the device name of this device.
void SetDeviceName (std::string deviceName)
Set the device name of this device.
Public Member Functions inherited from ns3::FdNetDeviceHelper
FdNetDeviceHelper ()
Construct a FdNetDeviceHelper.
virtual ~FdNetDeviceHelper ()
virtual NetDeviceContainer Install (const NodeContainer &c) const
This method creates a FdNetDevice and associates it to a node.
virtual NetDeviceContainer Install (Ptr< Node > node) const
This method creates a FdNetDevice and associates it to a node.
virtual NetDeviceContainer Install (std::string name) const
This method creates a FdNetDevice and associates it to a node.
void SetAttribute (std::string n1, const AttributeValue &v1)
void SetTypeId (std::string type)
Set the TypeId of the Objects to be created by this helper.
Public Member Functions inherited from ns3::PcapHelperForDevice
PcapHelperForDevice ()
Construct a PcapHelperForDevice.
virtual ~PcapHelperForDevice ()
Destroy a PcapHelperForDevice.
void EnablePcap (std::string prefix, NetDeviceContainer d, bool promiscuous=false)
Enable pcap output on each device in the container which is of the appropriate type.
void EnablePcap (std::string prefix, NodeContainer n, bool promiscuous=false)
Enable pcap output on each device (which is of the appropriate type) in the nodes provided in the container.
void EnablePcap (std::string prefix, Ptr< NetDevice > nd, bool promiscuous=false, bool explicitFilename=false)
Enable pcap output the indicated net device.
void EnablePcap (std::string prefix, std::string ndName, bool promiscuous=false, bool explicitFilename=false)
Enable pcap output the indicated net device using a device previously named using the ns-3 object name service.
void EnablePcap (std::string prefix, uint32_t nodeid, uint32_t deviceid, bool promiscuous=false)
Enable pcap output on the device specified by a global node-id (of a previously created node) and associated device-id.
void EnablePcapAll (std::string prefix, bool promiscuous=false)
Enable pcap output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
Public Member Functions inherited from ns3::AsciiTraceHelperForDevice
AsciiTraceHelperForDevice ()
Construct an AsciiTraceHelperForDevice.
virtual ~AsciiTraceHelperForDevice ()
Destroy an AsciiTraceHelperForDevice.
void EnableAscii (Ptr< OutputStreamWrapper > stream, NetDeviceContainer d)
Enable ascii trace output on each device in the container which is of the appropriate type.
void EnableAscii (Ptr< OutputStreamWrapper > stream, NodeContainer n)
Enable ascii trace output on each device (which is of the appropriate type) in the nodes provided in the container.
void EnableAscii (Ptr< OutputStreamWrapper > stream, Ptr< NetDevice > nd)
Enable ascii trace output on the indicated net device.
void EnableAscii (Ptr< OutputStreamWrapper > stream, std::string ndName)
Enable ascii trace output the indicated net device using a device previously named using the ns-3 object name service.
void EnableAscii (Ptr< OutputStreamWrapper > stream, uint32_t nodeid, uint32_t deviceid)
Enable ascii trace output on the device specified by a global node-id (of a previously created node) and associated device-id.
void EnableAscii (std::string prefix, NetDeviceContainer d)
Enable ascii trace output on each device in the container which is of the appropriate type.
void EnableAscii (std::string prefix, NodeContainer n)
Enable ascii trace output on each device (which is of the appropriate type) in the nodes provided in the container.
void EnableAscii (std::string prefix, Ptr< NetDevice > nd, bool explicitFilename=false)
Enable ascii trace output on the indicated net device.
void EnableAscii (std::string prefix, std::string ndName, bool explicitFilename=false)
Enable ascii trace output the indicated net device using a device previously named using the ns-3 object name service.
void EnableAscii (std::string prefix, uint32_t nodeid, uint32_t deviceid, bool explicitFilename)
Enable ascii trace output on the device specified by a global node-id (of a previously created node) and associated device-id.
void EnableAsciiAll (Ptr< OutputStreamWrapper > stream)
Enable ascii trace output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
void EnableAsciiAll (std::string prefix)
Enable ascii trace output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
Protected Member Functions
virtual int CreateFileDescriptor (void) const
Call out to a separate process running as suid root in order to get a raw socket.
Ptr< NetDevice > InstallPriv (Ptr< Node > node) const
This method creates an ns3::FdNetDevice attached to a physical network interface.
virtual void SetDeviceAttributes (Ptr< FdNetDevice > device) const
Sets device flags and MTU.
void SwitchInNetmapMode (int fd, Ptr< NetmapNetDevice > device) const
Switch the fd in netmap mode.
Protected Attributes
std::string m_deviceName
The unix/linux name of the underlying device (e.g., eth0)
Detailed Description
build a set of FdNetDevice objects attached to a physical network interface
Definition at line 44 of file netmap-net-device-helper.h.
Constructor & Destructor Documentation
NetmapNetDeviceHelper()
ns3::NetmapNetDeviceHelper::NetmapNetDeviceHelper ()
Definition at line 67 of file netmap-net-device-helper.cc.
References m_deviceName, and ns3::FdNetDeviceHelper::SetTypeId().
~NetmapNetDeviceHelper()
virtual ns3::NetmapNetDeviceHelper::~NetmapNetDeviceHelper () inline virtual
Definition at line 49 of file netmap-net-device-helper.h.
Member Function Documentation
CreateFileDescriptor()
int ns3::NetmapNetDeviceHelper::CreateFileDescriptor (void) const protected virtual
Call out to a separate process running as suid root in order to get a raw socket.
We do this to avoid having the entire simulation running as root.
Returns
the rawSocket number
Definition at line 199 of file netmap-net-device-helper.cc.
References ns3::BufferToString(), EMU_MAGIC, NS_ASSERT_MSG, NS_FATAL_ERROR, NS_LOG_DEBUG, NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by InstallPriv().
GetDeviceName()
std::string ns3::NetmapNetDeviceHelper::GetDeviceName (void)
Get the device name of this device.
Returns
The device name of this device.
Definition at line 74 of file netmap-net-device-helper.cc.
References m_deviceName.
InstallPriv()
Ptr< NetDevice > ns3::NetmapNetDeviceHelper::InstallPriv (Ptr< Node > node) const protected virtual
This method creates an ns3::FdNetDevice attached to a physical network interface.
Parameters
node The node to install the device in
Returns
A container holding the added net device.
Reimplemented from ns3::FdNetDeviceHelper.
Definition at line 86 of file netmap-net-device-helper.cc.
References CreateFileDescriptor(), ns3::NetDeviceQueueLock::GetTypeId(), ns3::FdNetDeviceHelper::InstallPriv(), SetDeviceAttributes(), and SwitchInNetmapMode().
SetDeviceAttributes()
void ns3::NetmapNetDeviceHelper::SetDeviceAttributes (Ptr< FdNetDevice > device) const protected virtual
Sets device flags and MTU.
Parameters
device the FdNetDevice
Definition at line 109 of file netmap-net-device-helper.cc.
References m_deviceName, NS_FATAL_ERROR, NS_LOG_DEBUG, and NS_LOG_LOGIC.
Referenced by InstallPriv().
SetDeviceName()
void ns3::NetmapNetDeviceHelper::SetDeviceName (std::string deviceName)
Set the device name of this device.
Parameters
deviceName The device name of this device.
Definition at line 80 of file netmap-net-device-helper.cc.
References m_deviceName.
SwitchInNetmapMode()
void ns3::NetmapNetDeviceHelper::SwitchInNetmapMode (int fd, Ptr< NetmapNetDevice > device) const protected
Switch the fd in netmap mode.
Parameters
fd the file descriptor
device the NetmapNetDevice
Definition at line 422 of file netmap-net-device-helper.cc.
References m_deviceName, NS_ASSERT, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
Referenced by InstallPriv().
Member Data Documentation
m_deviceName
std::string ns3::NetmapNetDeviceHelper::m_deviceName protected
The unix/linux name of the underlying device (e.g., eth0)
Definition at line 94 of file netmap-net-device-helper.h.
Referenced by NetmapNetDeviceHelper(), GetDeviceName(), SetDeviceAttributes(), SetDeviceName(), and SwitchInNetmapMode().
The documentation for this class was generated from the following files:
src/fd-net-device/helper/netmap-net-device-helper.h
src/fd-net-device/helper/netmap-net-device-helper.cc