ns-3: ThreeGppV2vHighwayPropagationLossModelTestCase Class Reference
ThreeGppV2vHighwayPropagationLossModelTestCase Class Reference
Test case for the class ThreeGppV2vHighwayPropagationLossModel.
Classes
struct TestVector
Struct containing the parameters for each test.
Public Member Functions
ThreeGppV2vHighwayPropagationLossModelTestCase ()
Constructor.
virtual ~ThreeGppV2vHighwayPropagationLossModelTestCase ()
Destructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Build the simulation scenario and run the tests.
Private Attributes
TestVectors< TestVector > m_testVectors
array containing all the test vectors
double m_tolerance
tolerance
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test case for the class ThreeGppV2vHighwayPropagationLossModel.
It computes the pathloss between two nodes and compares it with the value obtained using the formula in 3GPP TR 37.885 Table 6.2.1-1 for v2v communications (sidelink).
Note that 3GPP TR 37.885 defines 3 different channel states for vehicular environments: LOS, NLOS and NLOSv, the latter representing the case in which the LOS path is blocked by other vehicles in the scenario. However, for computing the pathloss, only two states are considered: LOS/NLOSv or NLOS (see TR 37.885 Section 6.2.1). In case of NLOSv, an additional vehicle blockage loss may be added, according to a log-normal random variable. Here, we test both conditions: LOS/NLOSv (without vehicle blockage loss) and NLOS.
Definition at line 828 of file three-gpp-propagation-loss-model-test-suite.cc.
Constructor & Destructor Documentation
ThreeGppV2vHighwayPropagationLossModelTestCase()
ThreeGppV2vHighwayPropagationLossModelTestCase::ThreeGppV2vHighwayPropagationLossModelTestCase ()
Constructor.
Definition at line 863 of file three-gpp-propagation-loss-model-test-suite.cc.
~ThreeGppV2vHighwayPropagationLossModelTestCase()
ThreeGppV2vHighwayPropagationLossModelTestCase::~ThreeGppV2vHighwayPropagationLossModelTestCase () virtual
Destructor.
Definition at line 870 of file three-gpp-propagation-loss-model-test-suite.cc.
Member Function Documentation
DoRun()
void ThreeGppV2vHighwayPropagationLossModelTestCase::DoRun (void) private virtual
Build the simulation scenario and run the tests.
Implements ns3::TestCase.
Definition at line 875 of file three-gpp-propagation-loss-model-test-suite.cc.
References ns3::PropagationLossModel::CalcRxPower(), ThreeGppV2vHighwayPropagationLossModelTestCase::TestVector::m_distance, ThreeGppV2vHighwayPropagationLossModelTestCase::TestVector::m_frequency, ThreeGppV2vHighwayPropagationLossModelTestCase::TestVector::m_isLos, ThreeGppV2vHighwayPropagationLossModelTestCase::TestVector::m_pr, ThreeGppV2vHighwayPropagationLossModelTestCase::TestVector::m_pt, m_testVectors, m_tolerance, first::nodes, NS_TEST_EXPECT_MSG_EQ_TOL, ns3::ObjectBase::SetAttribute(), ns3::ThreeGppPropagationLossModel::SetChannelConditionModel(), and ns3::MobilityModel::SetPosition().
Member Data Documentation
m_testVectors
TestVectors<TestVector> ThreeGppV2vHighwayPropagationLossModelTestCase::m_testVectors private
array containing all the test vectors
Definition at line 859 of file three-gpp-propagation-loss-model-test-suite.cc.
Referenced by DoRun().
m_tolerance
double ThreeGppV2vHighwayPropagationLossModelTestCase::m_tolerance private
tolerance
Definition at line 860 of file three-gpp-propagation-loss-model-test-suite.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/propagation/test/three-gpp-propagation-loss-model-test-suite.cc