ns-3: ns3::Ipv6ExtensionFragment Class Reference
ns3::Ipv6ExtensionFragment Class Reference
Internet » IPv6 classes and sub-modules » IPV6 Header extension system.
IPv6 Extension Fragment.
#include "ipv6-extension.h"
Classes
class Fragments
This class stores the fragments of a packet waiting to be rebuilt.
Public Types
typedef std::pair< Ptr< Packet >, Ipv6Header > Ipv6PayloadHeaderPair
Pair of a packet and an Ipv6 header.
Public Member Functions
Ipv6ExtensionFragment ()
Constructor.
~Ipv6ExtensionFragment ()
Destructor.
virtual uint8_t GetExtensionNumber () const
Get the extension number.
void GetFragments (Ptr< Packet > packet, Ipv6Header ipv6Header, uint32_t fragmentSize, std::list< Ipv6PayloadHeaderPair > &listFragments)
Fragment a packet.
virtual uint8_t Process (Ptr< Packet > &packet, uint8_t offset, Ipv6Header const &ipv6Header, Ipv6Address dst, uint8_t *nextHeader, bool &stopProcessing, bool &isDropped, Ipv6L3Protocol::DropReason &dropReason)
Process method Called from Ipv6L3Protocol::Receive.
Public Member Functions inherited from ns3::Ipv6Extension
Ipv6Extension ()
Constructor.
virtual ~Ipv6Extension ()
Destructor.
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Ptr< Node > GetNode () const
Get the node.
virtual uint8_t ProcessOptions (Ptr< Packet > &packet, uint8_t offset, uint8_t length, Ipv6Header const &ipv6Header, Ipv6Address dst, uint8_t *nextHeader, bool &stopProcessing, bool &isDropped, Ipv6L3Protocol::DropReason &dropReason)
Process options Called by implementing classes to process the options.
void SetNode (Ptr< Node > node)
Set the node.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Ipv6Extension
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static const uint8_t EXT_NUMBER = 44
Fragmentation extension number.
Protected Member Functions
virtual void DoDispose ()
Dispose this object.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
typedef std::pair< Ipv6Address, uint32_t > FragmentKey_t
Key identifying a fragmented packet.
typedef std::list< std::tuple< Time, FragmentKey_t, Ipv6Header > > FragmentsTimeoutsList_t
Container for fragment timeouts.
typedef std::list< std::tuple< Time, FragmentKey_t, Ipv6Header > >::iterator FragmentsTimeoutsListI_t
Container Iterator for fragment timeouts.
typedef std::map< FragmentKey_t, Ptr< Fragments > > MapFragments_t
Container for the packet fragments.
Private Member Functions
void CancelTimeout ()
Cancel the timeout event.
Ptr< Packet > GetPartialPacket () const
Get the packet parts so far received.
void HandleFragmentsTimeout (FragmentKey_t key, Ipv6Header ipHeader)
Process the timeout for packet fragments.
void HandleTimeout (void)
Handles a fragmented packet timeout.
FragmentsTimeoutsListI_t SetTimeout (FragmentKey_t key, Ipv6Header ipHeader)
Set a new timeout "event" for a fragmented packet.
void SetTimeoutEventId (EventId event)
Set the Timeout EventId.
Private Attributes
Time m_fragmentExpirationTimeout
Expiration timeout.
MapFragments_t m_fragments
The hash of fragmented packets.
EventId m_timeoutEvent
Event for the next scheduled timeout.
FragmentsTimeoutsList_t m_timeoutEventList
Timeout "events" container.
Additional Inherited Members
Protected Attributes inherited from ns3::Ipv6Extension
Ptr< UniformRandomVariable > m_uvar
Provides uniform random variables.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
IPv6 Extension Fragment.
Introspection did not find any typical Config paths.
Attributes
FragmentExpirationTimeout: When this timeout expires, the fragments will be cleared from the buffer.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +6e+10ns
Flags: construct write read
Attributes defined in parent class ns3::Ipv6Extension
ExtensionNumber: The IPv6 extension number.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Flags: read
No TraceSources are defined for this type.
Size of this type is 128 bytes (on a 64-bit architecture).
Definition at line 259 of file ipv6-extension.h.
Member Typedef Documentation
FragmentKey_t
typedef std::pair<Ipv6Address, uint32_t> ns3::Ipv6ExtensionFragment::FragmentKey_t private
Key identifying a fragmented packet.
Definition at line 324 of file ipv6-extension.h.
FragmentsTimeoutsList_t
typedef std::list< std::tuple <Time, FragmentKey_t, Ipv6Header > > ns3::Ipv6ExtensionFragment::FragmentsTimeoutsList_t private
Container for fragment timeouts.
Definition at line 329 of file ipv6-extension.h.
FragmentsTimeoutsListI_t
typedef std::list< std::tuple <Time, FragmentKey_t, Ipv6Header > >::iterator ns3::Ipv6ExtensionFragment::FragmentsTimeoutsListI_t private
Container Iterator for fragment timeouts.
Definition at line 333 of file ipv6-extension.h.
Ipv6PayloadHeaderPair
typedef std::pair<Ptr<Packet>, Ipv6Header> ns3::Ipv6ExtensionFragment::Ipv6PayloadHeaderPair
Pair of a packet and an Ipv6 header.
Definition at line 301 of file ipv6-extension.h.
MapFragments_t
typedef std::map<FragmentKey_t, Ptr<Fragments> > ns3::Ipv6ExtensionFragment::MapFragments_t private
Container for the packet fragments.
Definition at line 446 of file ipv6-extension.h.
Constructor & Destructor Documentation
Ipv6ExtensionFragment()
ns3::Ipv6ExtensionFragment::Ipv6ExtensionFragment ()
Constructor.
Definition at line 315 of file ipv6-extension.cc.
~Ipv6ExtensionFragment()
ns3::Ipv6ExtensionFragment::~Ipv6ExtensionFragment ()
Destructor.
Definition at line 319 of file ipv6-extension.cc.
Member Function Documentation
CancelTimeout()
void ns3::Ipv6ExtensionFragment::CancelTimeout () private
Cancel the timeout event.
DoDispose()
void ns3::Ipv6ExtensionFragment::DoDispose (void) protected virtual
Dispose this object.
Reimplemented from ns3::Object.
Definition at line 323 of file ipv6-extension.cc.
References ns3::EventId::Cancel(), ns3::Object::DoDispose(), ns3::EventId::IsRunning(), m_fragments, m_timeoutEvent, m_timeoutEventList, and NS_LOG_FUNCTION.
GetExtensionNumber()
uint8_t ns3::Ipv6ExtensionFragment::GetExtensionNumber () const virtual
Get the extension number.
Returns
extension number
Implements ns3::Ipv6Extension.
Definition at line 341 of file ipv6-extension.cc.
References EXT_NUMBER.
GetFragments()
void ns3::Ipv6ExtensionFragment::GetFragments (Ptr< Packet > packet, Ipv6Header ipv6Header, uint32_t fragmentSize, std::list< Ipv6PayloadHeaderPair > & listFragments)
Fragment a packet.
Parameters
packet the packet.
ipv6Header the IPv6 header.
fragmentSize the maximal size of the fragment (unfragmentable part + fragmentation header + fragmentable part).
listFragments the list of fragments.
Definition at line 419 of file ipv6-extension.cc.
References ns3::Packet::AddHeader(), ns3::Packet::Copy(), ns3::Packet::CopyData(), ns3::Packet::CreateFragment(), ns3::Ipv6ExtensionHeader::GetLength(), ns3::Ipv6ExtensionHeader::GetNextHeader(), ns3::Ipv6Header::GetNextHeader(), ns3::Ipv6Extension::GetNode(), ns3::Object::GetObject(), ns3::Ipv6ExtensionFragmentHeader::GetSerializedSize(), ns3::Ipv6Header::GetSerializedSize(), ns3::Packet::GetSize(), ns3::UniformRandomVariable::GetValue(), ns3::Ipv6Header::IPV6_EXT_DESTINATION, ns3::Ipv6Header::IPV6_EXT_FRAGMENTATION, ns3::Ipv6Header::IPV6_EXT_HOP_BY_HOP, ns3::Ipv6Header::IPV6_EXT_ROUTING, list, ns3::Ipv6Extension::m_uvar, NS_ASSERT, NS_LOG_FUNCTION, ns3::Packet::Print(), ns3::Packet::RemoveHeader(), ns3::Ipv6ExtensionFragmentHeader::SetIdentification(), ns3::Ipv6ExtensionFragmentHeader::SetMoreFragment(), ns3::Ipv6Header::SetNextHeader(), ns3::Ipv6ExtensionHeader::SetNextHeader(), ns3::Ipv6ExtensionLooseRoutingHeader::SetNumberAddress(), ns3::Ipv6ExtensionFragmentHeader::SetOffset(), and ns3::Ipv6Header::SetPayloadLength().
GetPartialPacket()
Ptr<Packet> ns3::Ipv6ExtensionFragment::GetPartialPacket () const private
Get the packet parts so far received.
Returns
the partial packet
GetTypeId()
TypeId ns3::Ipv6ExtensionFragment::GetTypeId (void) static
Get the type identificator.
Returns
type identificator
Definition at line 299 of file ipv6-extension.cc.
References m_fragmentExpirationTimeout, ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::Seconds(), and ns3::TypeId::SetParent().
HandleFragmentsTimeout()
void ns3::Ipv6ExtensionFragment::HandleFragmentsTimeout (FragmentKey_t key, Ipv6Header ipHeader) private
Process the timeout for packet fragments.
Parameters
key representing the packet fragments
ipHeader the IP header of the original packet
Definition at line 593 of file ipv6-extension.cc.
References ns3::Packet::AddHeader(), ns3::Packet::Copy(), ns3::Ipv6L3Protocol::DROP_FRAGMENT_TIMEOUT, ns3::Ipv6Extension::GetNode(), ns3::Object::GetObject(), ns3::Ipv6ExtensionFragment::Fragments::GetPartialPacket(), ns3::Packet::GetSize(), ns3::Ipv6Header::GetSourceAddress(), ns3::Icmpv6Header::ICMPV6_FRAGTIME, m_fragments, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
Referenced by HandleTimeout().
HandleTimeout()
void ns3::Ipv6ExtensionFragment::HandleTimeout (void) private
Handles a fragmented packet timeout.
Definition at line 638 of file ipv6-extension.cc.
References HandleFragmentsTimeout(), m_timeoutEvent, m_timeoutEventList, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::Simulator::Schedule().
Referenced by SetTimeout().
Process()
uint8_t ns3::Ipv6ExtensionFragment::Process (Ptr< Packet > & packet, uint8_t offset, Ipv6Header const & ipv6Header, Ipv6Address dst, uint8_t * nextHeader, bool & stopProcessing, bool & isDropped, Ipv6L3Protocol::DropReason & dropReason) virtual
Process method Called from Ipv6L3Protocol::Receive.
Parameters
packet the packet
offset the offset of the extension to process
ipv6Header the IPv6 header of packet received
dst destination address of the packet received (i.e. us)
nextHeader the next header
stopProcessing true if the packet must not be further processed
isDropped true if the packet must be dropped
dropReason dropping reason
Returns
the size processed
Implements ns3::Ipv6Extension.
Definition at line 346 of file ipv6-extension.cc.
References ns3::Ipv6ExtensionFragment::Fragments::AddFragment(), ns3::Packet::Copy(), ns3::Ipv6ExtensionFragmentHeader::GetIdentification(), ns3::Ipv6ExtensionFragmentHeader::GetMoreFragment(), ns3::Ipv6ExtensionHeader::GetNextHeader(), ns3::Ipv6ExtensionFragmentHeader::GetOffset(), ns3::Ipv6ExtensionFragment::Fragments::GetPacket(), ns3::Packet::GetSize(), ns3::Ipv6Header::GetSourceAddress(), ns3::Ipv6ExtensionFragment::Fragments::GetTimeoutIter(), ns3::Ipv6ExtensionFragment::Fragments::IsEntire(), m_fragments, m_timeoutEventList, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Packet::RemoveAtEnd(), ns3::Packet::RemoveAtStart(), ns3::Packet::RemoveHeader(), ns3::Ipv6Header::SetNextHeader(), SetTimeout(), ns3::Ipv6ExtensionFragment::Fragments::SetTimeoutIter(), and ns3::Ipv6ExtensionFragment::Fragments::SetUnfragmentablePart().
SetTimeout()
Ipv6ExtensionFragment::FragmentsTimeoutsListI_t ns3::Ipv6ExtensionFragment::SetTimeout (FragmentKey_t key, Ipv6Header ipHeader) private
Set a new timeout "event" for a fragmented packet.
Parameters
key the fragment identification
ipHeader the IPv6 header of the fragmented packet
Returns
an iterator to the inserted "event"
Definition at line 622 of file ipv6-extension.cc.
References HandleTimeout(), m_fragmentExpirationTimeout, m_timeoutEvent, m_timeoutEventList, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::Simulator::Schedule().
Referenced by Process().
SetTimeoutEventId()
void ns3::Ipv6ExtensionFragment::SetTimeoutEventId (EventId event) private
Set the Timeout EventId.
Parameters
event The event.
Member Data Documentation
EXT_NUMBER
const uint8_t ns3::Ipv6ExtensionFragment::EXT_NUMBER = 44 static
Fragmentation extension number.
Definition at line 265 of file ipv6-extension.h.
Referenced by ns3::InternetStackHelper::AssignStreams(), GetExtensionNumber(), ns3::Ipv6ExtensionRouting::GetExtensionNumber(), ns3::Ipv6ExtensionESP::GetExtensionNumber(), and ns3::Ipv6ExtensionAH::GetExtensionNumber().
m_fragmentExpirationTimeout
Time ns3::Ipv6ExtensionFragment::m_fragmentExpirationTimeout private
Expiration timeout.
Definition at line 468 of file ipv6-extension.h.
Referenced by GetTypeId(), and SetTimeout().
m_fragments
MapFragments_t ns3::Ipv6ExtensionFragment::m_fragments private
The hash of fragmented packets.
Definition at line 451 of file ipv6-extension.h.
Referenced by DoDispose(), HandleFragmentsTimeout(), and Process().
m_timeoutEvent
EventId ns3::Ipv6ExtensionFragment::m_timeoutEvent private
Event for the next scheduled timeout.
Definition at line 467 of file ipv6-extension.h.
Referenced by DoDispose(), HandleTimeout(), and SetTimeout().
m_timeoutEventList
FragmentsTimeoutsList_t ns3::Ipv6ExtensionFragment::m_timeoutEventList private
Timeout "events" container.
Definition at line 466 of file ipv6-extension.h.
Referenced by DoDispose(), HandleTimeout(), Process(), and SetTimeout().
The documentation for this class was generated from the following files:
src/internet/model/ipv6-extension.h
src/internet/model/ipv6-extension.cc