ns-3: ns3::BasicEnergyHarvesterHelper Class Reference
ns3::BasicEnergyHarvesterHelper Class Reference
Energy Models
Creates a BasicEnergyHarvester object.
#include "basic-energy-harvester-helper.h"
Public Member Functions
BasicEnergyHarvesterHelper ()
~BasicEnergyHarvesterHelper ()
void Set (std::string name, const AttributeValue &v)
Public Member Functions inherited from ns3::EnergyHarvesterHelper
virtual ~EnergyHarvesterHelper ()
EnergyHarvesterContainer Install (EnergySourceContainer sourceContainer) const
EnergyHarvesterContainer Install (Ptr< EnergySource > source) const
EnergyHarvesterContainer Install (std::string sourceName) const
Private Member Functions
virtual Ptr< EnergyHarvester > DoInstall (Ptr< EnergySource > source) const
Private Attributes
ObjectFactory m_basicEnergyHarvester
Detailed Description
Creates a BasicEnergyHarvester object.
Definition at line 35 of file basic-energy-harvester-helper.h.
Constructor & Destructor Documentation
BasicEnergyHarvesterHelper()
ns3::BasicEnergyHarvesterHelper::BasicEnergyHarvesterHelper ()
Definition at line 27 of file basic-energy-harvester-helper.cc.
References m_basicEnergyHarvester, and ns3::ObjectFactory::SetTypeId().
~BasicEnergyHarvesterHelper()
ns3::BasicEnergyHarvesterHelper::~BasicEnergyHarvesterHelper ()
Definition at line 32 of file basic-energy-harvester-helper.cc.
Member Function Documentation
DoInstall()
Ptr< EnergyHarvester > ns3::BasicEnergyHarvesterHelper::DoInstall (Ptr< EnergySource > source) const private virtual
Parameters
node Pointer to node where the energy harvester is to be installed.
Returns
Pointer to the created EnergyHarvester.
Child classes of EnergyHarvesterHelper only have to implement this function, to create and aggregate an EnergyHarvester object onto a single node. Rest of the installation process (eg. installing EnergyHarvester on set of nodes) is implemented in the EnergyHarvesterHelper base class.
Implements ns3::EnergyHarvesterHelper.
Definition at line 43 of file basic-energy-harvester-helper.cc.
References ns3::ObjectFactory::Create(), m_basicEnergyHarvester, and NS_ASSERT.
Set()
void ns3::BasicEnergyHarvesterHelper::Set (std::string name, const AttributeValue & v) virtual
Parameters
name Name of attribute to set.
v Value of the attribute.
Sets one of the attributes of underlying EnergyHarvester.
Implements ns3::EnergyHarvesterHelper.
Definition at line 37 of file basic-energy-harvester-helper.cc.
References m_basicEnergyHarvester, and ns3::ObjectFactory::Set().
Member Data Documentation
m_basicEnergyHarvester
ObjectFactory ns3::BasicEnergyHarvesterHelper::m_basicEnergyHarvester private
Definition at line 47 of file basic-energy-harvester-helper.h.
Referenced by BasicEnergyHarvesterHelper(), DoInstall(), and Set().
The documentation for this class was generated from the following files:
src/energy/helper/basic-energy-harvester-helper.h
src/energy/helper/basic-energy-harvester-helper.cc