ns-3: ns3::BulkSendHelper Class Reference
ns3::BulkSendHelper Class Reference
Applications » BulkSendApplication
A helper to make it easier to instantiate an ns3::BulkSendApplication on a set of nodes.
#include "bulk-send-helper.h"
Public Member Functions
BulkSendHelper (std::string protocol, Address address)
Create an BulkSendHelper to make it easier to work with BulkSendApplications.
ApplicationContainer Install (NodeContainer c) const
Install an ns3::BulkSendApplication on each node of the input container configured with all the attributes set with SetAttribute.
ApplicationContainer Install (Ptr< Node > node) const
Install an ns3::BulkSendApplication on the node configured with all the attributes set with SetAttribute.
ApplicationContainer Install (std::string nodeName) const
Install an ns3::BulkSendApplication on the node configured with all the attributes set with SetAttribute.
void SetAttribute (std::string name, const AttributeValue &value)
Helper function used to set the underlying application attributes, not the socket attributes.
Private Member Functions
Ptr< Application > InstallPriv (Ptr< Node > node) const
Install an ns3::BulkSendApplication on the node configured with all the attributes set with SetAttribute.
Private Attributes
ObjectFactory m_factory
Object factory.
Detailed Description
A helper to make it easier to instantiate an ns3::BulkSendApplication on a set of nodes.
Definition at line 42 of file bulk-send-helper.h.
Constructor & Destructor Documentation
BulkSendHelper()
ns3::BulkSendHelper::BulkSendHelper (std::string protocol, Address address)
Create an BulkSendHelper to make it easier to work with BulkSendApplications.
Parameters
protocol the name of the protocol to use to send traffic by the applications. This string identifies the socket factory type used to create sockets for the applications. A typical value would be ns3::UdpSocketFactory.
address the address of the remote node to send traffic to.
Definition at line 31 of file bulk-send-helper.cc.
References first::address, m_factory, ns3::ObjectFactory::Set(), and ns3::ObjectFactory::SetTypeId().
Member Function Documentation
Install() [1/3]
ApplicationContainer ns3::BulkSendHelper::Install (NodeContainer c) const
Install an ns3::BulkSendApplication on each node of the input container configured with all the attributes set with SetAttribute.
Parameters
c NodeContainer of the set of nodes on which an BulkSendApplication will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 58 of file bulk-send-helper.cc.
References ns3::ApplicationContainer::Add(), ns3::NodeContainer::Begin(), ns3::NodeContainer::End(), and InstallPriv().
Referenced by CreateBulkFlow(), BulkSendBasicTestCase::DoRun(), BulkSendSeqTsSizeTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), experiment(), and InstallBulkSend().
Install() [2/3]
ApplicationContainer ns3::BulkSendHelper::Install (Ptr< Node > node) const
Install an ns3::BulkSendApplication on the node configured with all the attributes set with SetAttribute.
Parameters
node The node on which an BulkSendApplication will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 45 of file bulk-send-helper.cc.
References InstallPriv().
Install() [3/3]
ApplicationContainer ns3::BulkSendHelper::Install (std::string nodeName) const
Install an ns3::BulkSendApplication on the node configured with all the attributes set with SetAttribute.
Parameters
nodeName The node on which an BulkSendApplication will be installed.
Returns
Container of Ptr to the applications installed.
Definition at line 51 of file bulk-send-helper.cc.
References InstallPriv().
InstallPriv()
Ptr< Application > ns3::BulkSendHelper::InstallPriv (Ptr< Node > node) const private
Install an ns3::BulkSendApplication on the node configured with all the attributes set with SetAttribute.
Parameters
node The node on which an BulkSendApplication will be installed.
Returns
Ptr to the application installed.
Definition at line 70 of file bulk-send-helper.cc.
References ns3::Node::AddApplication(), ns3::ObjectFactory::Create(), and m_factory.
Referenced by Install().
SetAttribute()
void ns3::BulkSendHelper::SetAttribute (std::string name, const AttributeValue & value)
Helper function used to set the underlying application attributes, not the socket attributes.
Parameters
name the name of the application attribute to set
value the value of the application attribute to set
Definition at line 39 of file bulk-send-helper.cc.
References m_factory, and ns3::ObjectFactory::Set().
Referenced by CreateBulkFlow(), BulkSendBasicTestCase::DoRun(), BulkSendSeqTsSizeTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), experiment(), and InstallBulkSend().
Member Data Documentation
m_factory
ObjectFactory ns3::BulkSendHelper::m_factory private
Object factory.
Definition at line 104 of file bulk-send-helper.h.
Referenced by BulkSendHelper(), InstallPriv(), and SetAttribute().
The documentation for this class was generated from the following files:
src/applications/helper/bulk-send-helper.h
src/applications/helper/bulk-send-helper.cc