ns-3: ns3::RandomVariableStream Class Reference
ns3::RandomVariableStream Class Reference abstract
Core » Random Variables
The basic uniform Random Number Generator (RNG).
#include "random-variable-stream.h"
Public Member Functions
RandomVariableStream ()
Default constructor.
virtual ~RandomVariableStream ()
Destructor.
virtual uint32_t GetInteger (void)=0
Get the next random value as an integer drawn from the distribution.
int64_t GetStream (void) const
Returns the stream number for the RngStream.
virtual double GetValue (void)=0
Get the next random value as a double drawn from the distribution.
bool IsAntithetic (void) const
Check if antithetic values will be generated.
void SetAntithetic (bool isAntithetic)
Specify whether antithetic values should be generated.
void SetStream (int64_t stream)
Specifies the stream number for the RngStream.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
RngStream * Peek (void) const
Get the pointer to the underlying RngStream.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
RandomVariableStream (const RandomVariableStream &o)
Copy constructor.
RandomVariableStream & operator= (const RandomVariableStream &o)
Assignment operator.
Private Attributes
bool m_isAntithetic
Indicates if antithetic values should be generated by this RNG stream.
RngStream * m_rng
Pointer to the underlying RngStream.
int64_t m_stream
The stream number for the RngStream.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The basic uniform Random Number Generator (RNG).
Note
The underlying random number generation method used by ns-3 is the RngStream code by Pierre L'Ecuyer at the University of Montreal.
ns-3 has a rich set of random number generators that allow stream numbers to be set deterministically if desired. Class RandomVariableStream defines the base class functionality required for all such random number generators.
By default, the underlying generator is seeded all the time with the same seed value and run number coming from the ns3::GlobalValue RngSeed and RngRun. Also by default, the stream number value for the underlying RngStream is automatically allocated.
Instances can be configured to return "antithetic" values. See the documentation for the specific distributions to see how this modifies the returned values.
Config Paths
ns3::RandomVariableStream is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::SimpleNetDevice/ReceiveErrorModel/$ns3::RateErrorModel/RanVar"
"/NodeList/[i]/DeviceList/[i]/$ns3::SimpleNetDevice/ReceiveErrorModel/$ns3::BurstErrorModel/BurstStart"
"/NodeList/[i]/DeviceList/[i]/$ns3::SimpleNetDevice/ReceiveErrorModel/$ns3::BurstErrorModel/BurstSize"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::SpectrumChannel/PropagationLossModel/$ns3::RandomPropagationLossModel/Variable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::YansWifiChannel/PropagationLossModel/$ns3::RandomPropagationLossModel/Variable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::YansWifiChannel/PropagationDelayModel/$ns3::RandomPropagationDelayModel/Variable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Phy/PostReceptionErrorModel/$ns3::RateErrorModel/RanVar"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Phy/PostReceptionErrorModel/$ns3::BurstErrorModel/BurstStart"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Phy/PostReceptionErrorModel/$ns3::BurstErrorModel/BurstSize"
"/NodeList/[i]/DeviceList/[i]/$ns3::PointToPointNetDevice/ReceiveErrorModel/$ns3::RateErrorModel/RanVar"
"/NodeList/[i]/DeviceList/[i]/$ns3::PointToPointNetDevice/ReceiveErrorModel/$ns3::BurstErrorModel/BurstStart"
"/NodeList/[i]/DeviceList/[i]/$ns3::PointToPointNetDevice/ReceiveErrorModel/$ns3::BurstErrorModel/BurstSize"
"/NodeList/[i]/DeviceList/[i]/$ns3::CsmaNetDevice/ReceiveErrorModel/$ns3::RateErrorModel/RanVar"
"/NodeList/[i]/DeviceList/[i]/$ns3::CsmaNetDevice/ReceiveErrorModel/$ns3::BurstErrorModel/BurstStart"
"/NodeList/[i]/DeviceList/[i]/$ns3::CsmaNetDevice/ReceiveErrorModel/$ns3::BurstErrorModel/BurstSize"
"/NodeList/[i]/DeviceList/[i]/$ns3::SixLowPanNetDevice/MeshUnderJitter"
"/NodeList/[i]/DeviceList/[i]/$ns3::LrWpanNetDevice/Channel/PropagationLossModel/$ns3::RandomPropagationLossModel/Variable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::SpectrumChannel/PropagationLossModel/$ns3::RandomPropagationLossModel/Variable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::YansWifiChannel/PropagationLossModel/$ns3::RandomPropagationLossModel/Variable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::YansWifiChannel/PropagationDelayModel/$ns3::RandomPropagationDelayModel/Variable"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/PhyEntities/[i]/PostReceptionErrorModel/$ns3::RateErrorModel/RanVar"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/PhyEntities/[i]/PostReceptionErrorModel/$ns3::BurstErrorModel/BurstStart"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/PhyEntities/[i]/PostReceptionErrorModel/$ns3::BurstErrorModel/BurstSize"
"/NodeList/[i]/ApplicationList/[i]/$ns3::OnOffApplication/OnTime"
"/NodeList/[i]/ApplicationList/[i]/$ns3::OnOffApplication/OffTime"
"/NodeList/[i]/ApplicationList/[i]/$ns3::DhcpClient/Transactions"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::GaussMarkovMobilityModel/MeanVelocity"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::GaussMarkovMobilityModel/MeanDirection"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::GaussMarkovMobilityModel/MeanPitch"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomDirection2dMobilityModel/Speed"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomDirection2dMobilityModel/Pause"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWalk2dMobilityModel/Direction"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWalk2dMobilityModel/Speed"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/Speed"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/Pause"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::RandomRectanglePositionAllocator/X"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::RandomRectanglePositionAllocator/Y"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::RandomBoxPositionAllocator/X"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::RandomBoxPositionAllocator/Y"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::RandomBoxPositionAllocator/Z"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::RandomDiscPositionAllocator/Theta"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::RandomDiscPositionAllocator/Rho"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::OutdoorPositionAllocator/X"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::OutdoorPositionAllocator/Y"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWaypointMobilityModel/PositionAllocator/$ns3::OutdoorPositionAllocator/Z"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWalk2dOutdoorMobilityModel/Direction"
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWalk2dOutdoorMobilityModel/Speed"
"/NodeList/[i]/$ns3::ArpL3Protocol/RequestJitter"
"/NodeList/[i]/$ns3::Icmpv6L4Protocol/SolicitationJitter"
"/ChannelList/[i]/$ns3::SpectrumChannel/PropagationLossModel/$ns3::RandomPropagationLossModel/Variable"
"/ChannelList/[i]/$ns3::YansWifiChannel/PropagationLossModel/$ns3::RandomPropagationLossModel/Variable"
"/ChannelList/[i]/$ns3::YansWifiChannel/PropagationDelayModel/$ns3::RandomPropagationDelayModel/Variable"
Attributes
Stream: The stream number for this RNG stream. -1 means "allocate a stream automatically". Note that if -1 is set, Get will return -1 so that it is not possible to know which value was automatically allocated.
Set with class: ns3::IntegerValue
Underlying type: int64_t -9223372036854775808:9223372036854775807
Initial value: -1
Flags: construct write read
Antithetic: Set this RNG stream to generate antithetic values
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 56 bytes (on a 64-bit architecture).
Definition at line 97 of file random-variable-stream.h.
Constructor & Destructor Documentation
RandomVariableStream() [1/2]
ns3::RandomVariableStream::RandomVariableStream ()
Default constructor.
Definition at line 76 of file random-variable-stream.cc.
References NS_LOG_FUNCTION.
~RandomVariableStream()
ns3::RandomVariableStream::~RandomVariableStream () virtual
Destructor.
Definition at line 81 of file random-variable-stream.cc.
References m_rng, and NS_LOG_FUNCTION.
RandomVariableStream() [2/2]
ns3::RandomVariableStream::RandomVariableStream (const RandomVariableStream & o) private
Copy constructor.
These objects are not copyable.
Parameters
[in] o The RandomVariableStream to copy in construction.
Internal:
Theoretically, it is possible to give them good copy semantics but not enough time to iron out the details.
Member Function Documentation
GetInteger()
virtual uint32_t ns3::RandomVariableStream::GetInteger (void) pure virtual
Get the next random value as an integer drawn from the distribution.
Returns
An integer random value.
Implemented in ns3::EmpiricalRandomVariable, ns3::DeterministicRandomVariable, ns3::ZetaRandomVariable, ns3::ZipfRandomVariable, ns3::TriangularRandomVariable, ns3::ErlangRandomVariable, ns3::GammaRandomVariable, ns3::LogNormalRandomVariable, ns3::NormalRandomVariable, ns3::WeibullRandomVariable, ns3::ParetoRandomVariable, ns3::ExponentialRandomVariable, ns3::SequentialRandomVariable, ns3::ConstantRandomVariable, and ns3::UniformRandomVariable.
Referenced by ns3::BurstErrorModel::DoCorrupt().
GetStream()
int64_t ns3::RandomVariableStream::GetStream (void) const
Returns the stream number for the RngStream.
Returns
The stream number for the RngStream. -1 means this stream was allocated automatically.
Definition at line 129 of file random-variable-stream.cc.
References m_stream, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::RandomVariableStream::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 54 of file random-variable-stream.cc.
References GetStream(), IsAntithetic(), ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeIntegerAccessor(), SetAntithetic(), ns3::TypeId::SetParent(), and SetStream().
GetValue()
virtual double ns3::RandomVariableStream::GetValue (void) pure virtual
Get the next random value as a double drawn from the distribution.
Returns
A floating point random value.
Implemented in ns3::EmpiricalRandomVariable, ns3::DeterministicRandomVariable, ns3::ZetaRandomVariable, ns3::ZipfRandomVariable, ns3::TriangularRandomVariable, ns3::ErlangRandomVariable, ns3::GammaRandomVariable, ns3::LogNormalRandomVariable, ns3::NormalRandomVariable, ns3::WeibullRandomVariable, ns3::ParetoRandomVariable, ns3::ExponentialRandomVariable, ns3::SequentialRandomVariable, ns3::ConstantRandomVariable, and ns3::UniformRandomVariable.
Referenced by ns3::RandomWalk2dOutdoorMobilityModel::AvoidBuilding(), ns3::RandomDirection2dMobilityModel::BeginPause(), ns3::RandomWaypointMobilityModel::BeginWalk(), ns3::DhcpClient::Boot(), ns3::BasicEnergyHarvester::CalculateHarvestedPower(), ns3::RandomPropagationLossModel::DoCalcRxPower(), ns3::BurstErrorModel::DoCorrupt(), ns3::RateErrorModel::DoCorruptBit(), ns3::RateErrorModel::DoCorruptByte(), ns3::RateErrorModel::DoCorruptPkt(), ns3::Icmpv6L4Protocol::DoDAD(), ns3::RandomWalk2dOutdoorMobilityModel::DoInitializePrivate(), ns3::RandomWalk2dMobilityModel::DoInitializePrivate(), ns3::RandomWaypointMobilityModel::DoInitializePrivate(), ns3::RandomPropagationDelayModel::GetDelay(), ns3::OutdoorPositionAllocator::GetNext(), ns3::RandomRectanglePositionAllocator::GetNext(), ns3::RandomBoxPositionAllocator::GetNext(), ns3::RandomDiscPositionAllocator::GetNext(), ns3::SequentialRandomVariable::GetValue(), ns3::ArpL3Protocol::Lookup(), ns3::SixLowPanNetDevice::ReceiveFromDevice(), ns3::DhcpClient::Request(), ns3::OnOffApplication::ScheduleStartEvent(), ns3::OnOffApplication::ScheduleStopEvent(), ns3::Icmpv6L4Protocol::SendNS(), ns3::Icmpv6L4Protocol::SendRS(), ns3::RandomDirection2dMobilityModel::SetDirectionAndSpeed(), ns3::GaussMarkovMobilityModel::Start(), and ns3::ApplicationContainer::StartWithJitter().
IsAntithetic()
bool ns3::RandomVariableStream::IsAntithetic (void) const
Check if antithetic values will be generated.
Returns
true if antithetic values will be generated.
Definition at line 94 of file random-variable-stream.cc.
References m_isAntithetic, and NS_LOG_FUNCTION.
Referenced by ns3::ErlangRandomVariable::GetExponentialValue(), ns3::GammaRandomVariable::GetNormalValue(), GetTypeId(), ns3::GammaRandomVariable::GetValue(), ns3::ExponentialRandomVariable::GetValue(), ns3::TriangularRandomVariable::GetValue(), ns3::NormalRandomVariable::GetValue(), ns3::UniformRandomVariable::GetValue(), ns3::LogNormalRandomVariable::GetValue(), ns3::ParetoRandomVariable::GetValue(), ns3::WeibullRandomVariable::GetValue(), ns3::ZipfRandomVariable::GetValue(), and ns3::EmpiricalRandomVariable::PreSample().
operator=()
RandomVariableStream& ns3::RandomVariableStream::operator= (const RandomVariableStream & o) private
Assignment operator.
These objects can't be copied by assignment.
Parameters
[in] o The RandomVariableStream to copy.
Returns
lvalue RandomVariableStream.
Internal:
Theoretically, it is possible to give them good copy semantics but not enough time to iron out the details.
Peek()
RngStream * ns3::RandomVariableStream::Peek (void) const protected
Get the pointer to the underlying RngStream.
Returns
The underlying RngStream
Definition at line 136 of file random-variable-stream.cc.
References m_rng, and NS_LOG_FUNCTION.
Referenced by ns3::ErlangRandomVariable::GetExponentialValue(), ns3::GammaRandomVariable::GetNormalValue(), ns3::GammaRandomVariable::GetValue(), ns3::ExponentialRandomVariable::GetValue(), ns3::TriangularRandomVariable::GetValue(), ns3::NormalRandomVariable::GetValue(), ns3::UniformRandomVariable::GetValue(), ns3::LogNormalRandomVariable::GetValue(), ns3::ParetoRandomVariable::GetValue(), ns3::WeibullRandomVariable::GetValue(), ns3::ZipfRandomVariable::GetValue(), and ns3::EmpiricalRandomVariable::PreSample().
SetAntithetic()
void ns3::RandomVariableStream::SetAntithetic (bool isAntithetic)
Specify whether antithetic values should be generated.
Parameters
[in] isAntithetic If true antithetic value will be generated.
Definition at line 88 of file random-variable-stream.cc.
References m_isAntithetic, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetStream()
void ns3::RandomVariableStream::SetStream (int64_t stream)
Specifies the stream number for the RngStream.
Parameters
[in] stream The stream number for the RngStream. -1 means "allocate a stream number automatically".
Definition at line 100 of file random-variable-stream.cc.
References ns3::RngSeedManager::GetNextStreamIndex(), ns3::RngSeedManager::GetRun(), ns3::RngSeedManager::GetSeed(), m_rng, m_stream, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by RandCartAroundGeoTestSuite::RandCartAroundGeoTestSuite(), ns3::aodv::RoutingProtocol::AssignStreams(), ns3::OnOffApplication::AssignStreams(), ns3::ThreeGppHttpVariables::AssignStreams(), ns3::RandomBuildingPositionAllocator::AssignStreams(), ns3::OutdoorPositionAllocator::AssignStreams(), ns3::RandomRoomPositionAllocator::AssignStreams(), ns3::Backoff::AssignStreams(), ns3::dsdv::RoutingProtocol::AssignStreams(), ns3::dsr::DsrRouting::AssignStreams(), ns3::BasicEnergyHarvester::AssignStreams(), ns3::DhcpClient::AssignStreams(), ns3::Radvd::AssignStreams(), ns3::ArpL3Protocol::AssignStreams(), ns3::Icmpv6L4Protocol::AssignStreams(), ns3::Ipv4GlobalRouting::AssignStreams(), ns3::Ipv6Extension::AssignStreams(), ns3::Rip::AssignStreams(), ns3::RipNg::AssignStreams(), ns3::LrWpanCsmaCa::AssignStreams(), ns3::LrWpanPhy::AssignStreams(), ns3::LteSpectrumPhy::AssignStreams(), ns3::LteUeMac::AssignStreams(), ns3::dot11s::HwmpProtocol::AssignStreams(), ns3::dot11s::PeerManagementProtocol::AssignStreams(), ns3::MeshWifiInterfaceMac::AssignStreams(), ns3::RandomRectanglePositionAllocator::AssignStreams(), ns3::RandomBoxPositionAllocator::AssignStreams(), ns3::RandomDiscPositionAllocator::AssignStreams(), ns3::UniformDiscPositionAllocator::AssignStreams(), ns3::RateErrorModel::AssignStreams(), ns3::BurstErrorModel::AssignStreams(), ns3::olsr::RoutingProtocol::AssignStreams(), ns3::SixLowPanNetDevice::AssignStreams(), ns3::ThreeGppChannelModel::AssignStreams(), ns3::CobaltQueueDisc::AssignStreams(), ns3::PieQueueDisc::AssignStreams(), ns3::RedQueueDisc::AssignStreams(), ns3::UanMacCw::AssignStreams(), ns3::UanMacRc::AssignStreams(), ns3::UanPhyGen::AssignStreams(), ns3::ApWifiMac::AssignStreams(), ns3::MinstrelHtWifiManager::AssignStreams(), ns3::MinstrelWifiManager::AssignStreams(), ns3::RrpaaWifiManager::AssignStreams(), ns3::Txop::AssignStreams(), ns3::WifiPhy::AssignStreams(), ns3::SimpleOfdmWimaxPhy::AssignStreams(), ns3::ThreeGppChannelConditionModel::AssignStreams(), ns3::BsmApplication::AssignStreams(), ns3::TvSpectrumTransmitterHelper::AssignStreams(), ns3::BriteTopologyHelper::AssignStreams(), ns3::SameRoomPositionAllocator::AssignStreams(), ns3::FixedRoomPositionAllocator::AssignStreams(), ns3::RandomVariableStreamHelper::AssignStreams(), ns3::JakesPropagationLossModel::DoAssignStreams(), ns3::RandomPropagationDelayModel::DoAssignStreams(), ns3::RandomPropagationLossModel::DoAssignStreams(), ns3::ThreeGppUmaPropagationLossModel::DoAssignStreams(), ns3::RandomWalk2dOutdoorMobilityModel::DoAssignStreams(), ns3::GaussMarkovMobilityModel::DoAssignStreams(), ns3::RandomDirection2dMobilityModel::DoAssignStreams(), ns3::RandomWalk2dMobilityModel::DoAssignStreams(), ns3::RandomWaypointMobilityModel::DoAssignStreams(), ns3::SteadyStateRandomWaypointMobilityModel::DoAssignStreams(), ns3::TraceFadingLossModel::DoCalcRxPowerSpectralDensity(), LteX2HandoverMeasuresTestCase::DoRun(), LteX2HandoverTestCase::DoRun(), ErrorModelSimple::DoRun(), BurstErrorModelSimple::DoRun(), GetTypeId(), and RoutingHelper::SetupRoutingMessages().
Member Data Documentation
m_isAntithetic
bool ns3::RandomVariableStream::m_isAntithetic private
Indicates if antithetic values should be generated by this RNG stream.
Definition at line 185 of file random-variable-stream.h.
Referenced by IsAntithetic(), and SetAntithetic().
m_rng
RngStream* ns3::RandomVariableStream::m_rng private
Pointer to the underlying RngStream.
Definition at line 182 of file random-variable-stream.h.
Referenced by ~RandomVariableStream(), Peek(), and SetStream().
m_stream
int64_t ns3::RandomVariableStream::m_stream private
The stream number for the RngStream.
Definition at line 188 of file random-variable-stream.h.
Referenced by GetStream(), and SetStream().
The documentation for this class was generated from the following files:
src/core/model/random-variable-stream.h
src/core/model/random-variable-stream.cc