ns-3: ns3::VectorTlvValue Class Reference
ns3::VectorTlvValue Class Reference abstract
WiMAX Models
this class is used to implement a vector of values in one tlv value field
#include "wimax-tlv.h"
Public Types
typedef std::vector< Tlv * >::const_iterator Iterator
TLV vector iterator typedef.
Public Member Functions
VectorTlvValue (void)
~VectorTlvValue (void)
void Add (const Tlv &val)
Add a TLV.
Iterator Begin () const
Begin iterator.
virtual VectorTlvValue * Copy (void) const =0
Copy.
virtual uint32_t Deserialize (Buffer::Iterator start, uint64_t valueLength)=0
Deserialize from a buffer.
Iterator End () const
End iterator.
virtual uint32_t GetSerializedSize (void) const
Get serialized size in bytes.
virtual void Serialize (Buffer::Iterator start) const
Serialize to a buffer.
Public Member Functions inherited from ns3::TlvValue
virtual ~TlvValue ()
Private Attributes
std::vector< Tlv * > * m_tlvList
tlv list
Detailed Description
this class is used to implement a vector of values in one tlv value field
Definition at line 289 of file wimax-tlv.h.
Member Typedef Documentation
Iterator
typedef std::vector<Tlv*>::const_iterator ns3::VectorTlvValue::Iterator
TLV vector iterator typedef.
Definition at line 293 of file wimax-tlv.h.
Constructor & Destructor Documentation
VectorTlvValue()
ns3::VectorTlvValue::VectorTlvValue (void)
Definition at line 235 of file wimax-tlv.cc.
References m_tlvList.
~VectorTlvValue()
ns3::VectorTlvValue::~VectorTlvValue (void)
Definition at line 240 of file wimax-tlv.cc.
References m_tlvList.
Member Function Documentation
Add()
void ns3::VectorTlvValue::Add (const Tlv & val)
Add a TLV.
Parameters
val the TLV value
Definition at line 284 of file wimax-tlv.cc.
References ns3::Tlv::Copy(), and m_tlvList.
Referenced by ns3::SfVectorTlvValue::Copy(), ns3::CsParamVectorTlvValue::Copy(), ns3::ClassificationRuleVectorTlvValue::Copy(), ns3::SfVectorTlvValue::Deserialize(), ns3::CsParamVectorTlvValue::Deserialize(), ns3::ClassificationRuleVectorTlvValue::Deserialize(), Ns3WimaxCsParamTlvTestCase::DoRun(), ns3::CsParameters::ToTlv(), ns3::IpcsClassifierRecord::ToTlv(), and ns3::ServiceFlow::ToTlv().
Begin()
VectorTlvValue::Iterator ns3::VectorTlvValue::Begin (void) const
Begin iterator.
Returns
the beginning element
Definition at line 272 of file wimax-tlv.cc.
References m_tlvList.
Referenced by ns3::CsParameters::CsParameters(), ns3::IpcsClassifierRecord::IpcsClassifierRecord(), ns3::ServiceFlow::ServiceFlow(), ns3::SfVectorTlvValue::Copy(), ns3::CsParamVectorTlvValue::Copy(), ns3::ClassificationRuleVectorTlvValue::Copy(), and Ns3WimaxCsParamTlvTestCase::DoRun().
Copy()
virtual VectorTlvValue* ns3::VectorTlvValue::Copy (void) const pure virtual
Copy.
Returns
the vector TLV value
Implements ns3::TlvValue.
Implemented in ns3::ClassificationRuleVectorTlvValue, ns3::CsParamVectorTlvValue, and ns3::SfVectorTlvValue.
Deserialize()
virtual uint32_t ns3::VectorTlvValue::Deserialize (Buffer::Iterator start, uint64_t valueLen) pure virtual
Deserialize from a buffer.
Parameters
start the iterator
valueLen the maximum length of the value
Returns
the
Implements ns3::TlvValue.
Implemented in ns3::ClassificationRuleVectorTlvValue, ns3::CsParamVectorTlvValue, and ns3::SfVectorTlvValue.
End()
VectorTlvValue::Iterator ns3::VectorTlvValue::End (void) const
End iterator.
Returns
the ending element
Definition at line 278 of file wimax-tlv.cc.
References m_tlvList.
Referenced by ns3::CsParameters::CsParameters(), ns3::IpcsClassifierRecord::IpcsClassifierRecord(), ns3::ServiceFlow::ServiceFlow(), ns3::SfVectorTlvValue::Copy(), ns3::CsParamVectorTlvValue::Copy(), ns3::ClassificationRuleVectorTlvValue::Copy(), and Ns3WimaxCsParamTlvTestCase::DoRun().
GetSerializedSize()
uint32_t ns3::VectorTlvValue::GetSerializedSize (void) const virtual
Get serialized size in bytes.
Returns
the serialized size
Implements ns3::TlvValue.
Definition at line 251 of file wimax-tlv.cc.
References m_tlvList.
Referenced by ns3::CsParamVectorTlvValue::Deserialize(), Ns3WimaxCsParamTlvTestCase::DoRun(), ns3::CsParameters::ToTlv(), ns3::IpcsClassifierRecord::ToTlv(), and ns3::ServiceFlow::ToTlv().
Serialize()
void ns3::VectorTlvValue::Serialize (Buffer::Iterator start) const virtual
Serialize to a buffer.
Parameters
start the iterator
Implements ns3::TlvValue.
Definition at line 262 of file wimax-tlv.cc.
References m_tlvList, and ns3::Buffer::Iterator::Next().
Member Data Documentation
m_tlvList
std::vector<Tlv*>* ns3::VectorTlvValue::m_tlvList private
tlv list
Definition at line 320 of file wimax-tlv.h.
Referenced by VectorTlvValue(), ~VectorTlvValue(), Add(), Begin(), End(), GetSerializedSize(), and Serialize().
The documentation for this class was generated from the following files:
src/wimax/model/wimax-tlv.h
src/wimax/model/wimax-tlv.cc