ns-3: ns3::ConstantObssPdAlgorithm Class Reference
ns3::ConstantObssPdAlgorithm Class Reference
Wifi Models
Constant OBSS PD algorithm.
#include "constant-obss-pd-algorithm.h"
Public Member Functions
ConstantObssPdAlgorithm ()
void ConnectWifiNetDevice (const Ptr< WifiNetDevice > device)
Connect the WifiNetDevice and setup eventual callbacks.
void ReceiveHeSig (HePreambleParameters params)
Public Member Functions inherited from ns3::ObssPdAlgorithm
void ResetPhy (HePreambleParameters params)
Reset PHY to IDLE.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObssPdAlgorithm
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Public Types inherited from ns3::ObssPdAlgorithm
typedef void(* ResetTracedCallback) (uint8_t bssColor, double rssiDbm, bool powerRestricted, double txPowerMaxDbmSiso, double txPowerMaxDbmMimo)
TracedCallback signature for OBSS_PD reset events.
Protected Member Functions inherited from ns3::ObssPdAlgorithm
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::ObssPdAlgorithm
Ptr< WifiNetDevice > m_device
Pointer to the WifiNetDevice.
double m_obssPdLevel
Current OBSS PD level (dBm)
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Constant OBSS PD algorithm.
Introspection did not find any typical Config paths.
This constant OBSS_PD algorithm is a simple OBSS_PD algorithm which evaluates if a receiving signal should be accepted or rejected based on a constant threshold.
Once a HE preamble and its header have been received by the PHY, the ReceiveHeSig method is triggered. The algorithm then checks whether this is an OBSS frame by comparing its own BSS color with the BSS color of the received preamble. If this is an OBSS frame, it compares the received RSSI with its configured OBSS_PD level value. The PHY then gets reset to IDLE state in case the received RSSI is lower than that constant OBSS PD level value, and is informed about TX power restrictions that might be applied to the next transmission.
No Attributes are defined for this type.
Attributes defined in parent class ns3::ObssPdAlgorithm
ObssPdLevel: The current OBSS PD level (dBm).
Set with class: ns3::DoubleValue
Underlying type: double -101:-62
Initial value: -82
Flags: construct write read
ObssPdLevelMin: Minimum value (dBm) of OBSS PD level.
Set with class: ns3::DoubleValue
Underlying type: double -101:-62
Initial value: -82
Flags: construct write read
ObssPdLevelMax: Maximum value (dBm) of OBSS PD level.
Set with class: ns3::DoubleValue
Underlying type: double -101:-62
Initial value: -62
Flags: construct write read
TxPowerRefSiso: The SISO reference TX power level (dBm).
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 21
Flags: construct write read
TxPowerRefMimo: The MIMO reference TX power level (dBm).
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 25
Flags: construct write read
No TraceSources are defined for this type.
TraceSources defined in parent class ns3::ObssPdAlgorithm
Reset: Trace CCA Reset event
Callback signature: ns3::ObssPdAlgorithm::ResetTracedCallback
Size of this type is 104 bytes (on a 64-bit architecture).
Definition at line 42 of file constant-obss-pd-algorithm.h.
Constructor & Destructor Documentation
ConstantObssPdAlgorithm()
ns3::ConstantObssPdAlgorithm::ConstantObssPdAlgorithm ()
Definition at line 38 of file constant-obss-pd-algorithm.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
ConnectWifiNetDevice()
void ns3::ConstantObssPdAlgorithm::ConnectWifiNetDevice (const Ptr< WifiNetDevice > device) virtual
Connect the WifiNetDevice and setup eventual callbacks.
Parameters
device the WifiNetDevice
Reimplemented from ns3::ObssPdAlgorithm.
Definition at line 56 of file constant-obss-pd-algorithm.cc.
References ns3::ObssPdAlgorithm::ConnectWifiNetDevice(), ns3::WifiNetDevice::GetPhy(), ns3::MakeCallback(), third::phy, and ReceiveHeSig().
GetTypeId()
TypeId ns3::ConstantObssPdAlgorithm::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 45 of file constant-obss-pd-algorithm.cc.
References ns3::TypeId::SetParent().
ReceiveHeSig()
void ns3::ConstantObssPdAlgorithm::ReceiveHeSig (HePreambleParameters params) virtual
Parameters
params the HE SIG parameters
Evaluate the receipt of HE SIG.
Implements ns3::ObssPdAlgorithm.
Definition at line 64 of file constant-obss-pd-algorithm.cc.
References ns3::HePreambleParameters::bssColor, ns3::UintegerValue::Get(), ns3::WifiNetDevice::GetHeConfiguration(), ns3::WifiNetDevice::GetMac(), ns3::ObssPdAlgorithm::m_device, ns3::ObssPdAlgorithm::m_obssPdLevel, third::mac, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::ObssPdAlgorithm::ResetPhy(), ns3::HePreambleParameters::rssiW, and ns3::WToDbm().
Referenced by ConnectWifiNetDevice().
The documentation for this class was generated from the following files:
src/wifi/model/constant-obss-pd-algorithm.h
src/wifi/model/constant-obss-pd-algorithm.cc