ns-3: ns3::PacketMetadata Class Reference
ns3::PacketMetadata Class Reference
Network » Packet
Handle packet metadata about packet headers and trailers.
#include "packet-metadata.h"
Classes
struct Data
Data structure.
class DataFreeList
Class to hold all the metadata.
struct ExtraItem
ExtraItem structure.
struct Item
structure describing a packet metadata item
class ItemIterator
Iterator class for metadata items.
struct SmallItem
SmallItem structure.
Public Member Functions
PacketMetadata (PacketMetadata const &o)
Copy constructor.
PacketMetadata (uint64_t uid, uint32_t size)
Constructor.
~PacketMetadata ()
void AddAtEnd (PacketMetadata const &o)
Add a metadata at the metadata start.
void AddHeader (Header const &header, uint32_t size)
Add an header.
void AddPaddingAtEnd (uint32_t end)
Add some padding at the end.
void AddTrailer (Trailer const &trailer, uint32_t size)
Add a trailer.
ItemIterator BeginItem (Buffer buffer) const
Initialize the item iterator to the buffer begin.
PacketMetadata CreateFragment (uint32_t start, uint32_t end) const
Creates a fragment.
uint32_t Deserialize (const uint8_t *buffer, uint32_t size)
Deserialization from raw uint8_t*.
uint32_t GetSerializedSize (void) const
Get the metadata serialized size.
uint64_t GetUid (void) const
Get the packet Uid.
PacketMetadata & operator= (PacketMetadata const &o)
Basic assignment.
void RemoveAtEnd (uint32_t end)
Remove a chunk of metadata at the metadata end.
void RemoveAtStart (uint32_t start)
Remove a chunk of metadata at the metadata start.
void RemoveHeader (Header const &header, uint32_t size)
Remove an header.
void RemoveTrailer (Trailer const &trailer, uint32_t size)
Remove a trailer.
uint32_t Serialize (uint8_t *buffer, uint32_t maxSize) const
Serialization to raw uint8_t*.
Static Public Member Functions
static void Enable (void)
Enable the packet metadata.
static void EnableChecking (void)
Enable the packet metadata checking.
Private Member Functions
PacketMetadata ()
friend DataFreeList::~DataFreeList ()
uint16_t AddBig (uint32_t head, uint32_t tail, const PacketMetadata::SmallItem *item, const PacketMetadata::ExtraItem *extraItem)
Add a "Big" Item (a SmallItem plus an ExtraItem)
uint16_t AddSmall (const PacketMetadata::SmallItem *item)
Add a SmallItem.
void Append16 (uint16_t value, uint8_t *buffer)
Append a 16-bit value to the buffer.
void Append32 (uint32_t value, uint8_t *buffer)
Append a 32-bit value to the buffer.
void AppendValue (uint32_t value, uint8_t *buffer)
Append a value to the buffer.
void AppendValueExtra (uint32_t value, uint8_t *buffer)
Append a value to the buffer - extra.
void DoAddHeader (uint32_t uid, uint32_t size)
Add an header.
uint32_t GetTotalSize (void) const
Get the total size used by the metadata.
uint32_t GetUleb128Size (uint32_t value) const
Get the ULEB128 (Unsigned Little Endian Base 128) size.
bool IsPointerOk (uint16_t pointer) const
Check if the position is valid.
bool IsSharedPointerOk (uint16_t pointer) const
Check if the position is valid.
bool IsStateOk (void) const
Check if the metadata state is ok.
uint32_t ReadItems (uint16_t current, struct PacketMetadata::SmallItem *item, struct PacketMetadata::ExtraItem *extraItem) const
Read items.
uint32_t ReadUleb128 (const uint8_t **pBuffer) const
Read a ULEB128 (Unsigned Little Endian Base 128) coded number.
void ReplaceTail (PacketMetadata::SmallItem *item, PacketMetadata::ExtraItem *extraItem, uint32_t available)
Replace the tail.
void Reserve (uint32_t n)
Reserve space.
void ReserveCopy (uint32_t n)
Reserve space and make a metadata copy.
void UpdateHead (uint16_t written)
Update the head.
void UpdateTail (uint16_t written)
Update the tail.
Static Private Member Functions
static uint8_t * AddToRaw (const uint8_t *data, uint32_t dataSize, uint8_t *start, uint8_t *current, uint32_t maxSize)
Helper for the raw serialization.
static uint8_t * AddToRawU16 (const uint16_t &data, uint8_t *start, uint8_t *current, uint32_t maxSize)
Helper for the raw serialization.
static uint8_t * AddToRawU32 (const uint32_t &data, uint8_t *start, uint8_t *current, uint32_t maxSize)
Helper for the raw serialization.
static uint8_t * AddToRawU64 (const uint64_t &data, uint8_t *start, uint8_t *current, uint32_t maxSize)
Helper for the raw serialization.
static uint8_t * AddToRawU8 (const uint8_t &data, uint8_t *start, uint8_t *current, uint32_t maxSize)
Helper for the raw serialization.
static struct PacketMetadata::Data * Allocate (uint32_t n)
Allocate a buffer data storage.
static struct PacketMetadata::Data * Create (uint32_t size)
Create a buffer data storage.
static void Deallocate (struct PacketMetadata::Data *data)
Deallocate the buffer memory.
static uint8_t * ReadFromRawU16 (uint16_t &data, const uint8_t *start, const uint8_t *current, uint32_t maxSize)
Helper for the raw deserialization.
static uint8_t * ReadFromRawU32 (uint32_t &data, const uint8_t *start, const uint8_t *current, uint32_t maxSize)
Helper for the raw deserialization.
static uint8_t * ReadFromRawU64 (uint64_t &data, const uint8_t *start, const uint8_t *current, uint32_t maxSize)
Helper for the raw deserialization.
static uint8_t * ReadFromRawU8 (uint8_t &data, const uint8_t *start, const uint8_t *current, uint32_t maxSize)
Helper for the raw deserialization.
static void Recycle (struct PacketMetadata::Data *data)
Recycle the buffer memory.
Private Attributes
struct Data * m_data
Metadata storage.
uint16_t m_head
list head
uint64_t m_packetUid
packet Uid
uint16_t m_tail
list tail
uint16_t m_used
used portion
Static Private Attributes
static uint16_t m_chunkUid = 0
Chunk Uid.
static bool m_enable = false
Enable the packet metadata.
static bool m_enableChecking = false
Enable the packet metadata checking.
static DataFreeList m_freeList
the metadata data storage
static uint32_t m_maxSize = 0
maximum metadata size
static bool m_metadataSkipped = false
Set to true when adding metadata to a packet is skipped because m_enable is false; used to detect enabling of metadata in the middle of a simulation, which isn't allowed.
Friends
class ItemIterator
Friend class.
Detailed Description
Handle packet metadata about packet headers and trailers.
This class is used by the Packet class to record every operation performed on the packet's buffer. This class also provides an implementation of the Packet::Print methods which uses the metadata to analyse the content of the packet's buffer.
To achieve this, this class maintains a linked list of so-called "items", each of which represents a header or a trailer, or payload, or a fragment of any of these. Each item contains a "next" and a "prev" field which point to the next and previous entries in the linked list. The PacketMetadata class maintains a pair of pointers to the head and the tail of the linked list.
Each entry in the list also maintains:
its native size (the size it had when it was first added to the packet)
its type: identifies what kind of header, what kind of trailer, if it is payload or not
the uid of the packet to which it was first added
the start and end of the area represented by a fragment if it is one.
This linked list is flattened in a byte buffer stored in struct PacketMetadata::Data. Each entry of the linked list is identified by an offset which identifies the first byte of the entry from the start of the data buffer. The size of this data buffer is 2^16-1 bytes maximum which somewhat limits the number of entries which can be stored in this linked list but it is quite unlikely to hit this limit in practice.
Each item of the linked list is a variable-sized byte buffer made of a number of fields. Some of these fields are stored as fixed-size 32 bit integers, others as fixed-size 16 bit integers, and some others as variable-size 32-bit integers. The variable-size 32 bit integers are stored using the uleb128 encoding.
Definition at line 78 of file packet-metadata.h.
Constructor & Destructor Documentation
PacketMetadata() [1/3]
ns3::PacketMetadata::PacketMetadata (uint64_t uid, uint32_t size) inline
Constructor.
Parameters
uid packet uid
size size of the header
Definition at line 694 of file packet-metadata.h.
References DoAddHeader(), ns3::PacketMetadata::Data::m_data, and m_data.
PacketMetadata() [2/3]
ns3::PacketMetadata::PacketMetadata (PacketMetadata const & o) inline
Copy constructor.
Parameters
o the object to copy
Definition at line 707 of file packet-metadata.h.
References ns3::PacketMetadata::Data::m_count, m_data, max, and NS_ASSERT.
~PacketMetadata()
ns3::PacketMetadata::~PacketMetadata () inline
Definition at line 740 of file packet-metadata.h.
References ns3::PacketMetadata::Data::m_count, m_data, NS_ASSERT, and Recycle().
DataFreeList::~DataFreeList()
ns3::PacketMetadata::DataFreeList::~DataFreeList () private
PacketMetadata() [3/3]
ns3::PacketMetadata::PacketMetadata () private
Member Function Documentation
AddAtEnd()
void ns3::PacketMetadata::AddAtEnd (PacketMetadata const & o)
Add a metadata at the metadata start.
Parameters
o the metadata to add
Definition at line 801 of file packet-metadata.cc.
References AddBig(), ns3::PacketMetadata::SmallItem::chunkUid, IsStateOk(), m_enable, m_head, m_metadataSkipped, m_tail, ns3::PacketMetadata::SmallItem::next, NS_ASSERT, NS_LOG_FUNCTION, ReadItems(), ReplaceTail(), ns3::PacketMetadata::SmallItem::size, ns3::PacketMetadata::SmallItem::typeUid, and UpdateTail().
Referenced by ns3::Packet::AddAtEnd().
AddBig()
uint16_t ns3::PacketMetadata::AddBig (uint32_t head, uint32_t tail, const PacketMetadata::SmallItem * item, const PacketMetadata::ExtraItem * extraItem) private
Add a "Big" Item (a SmallItem plus an ExtraItem)
Parameters
head the head
tail the tail
item the SmallItem to add
extraItem the ExtraItem to add
Returns
added size
Definition at line 403 of file packet-metadata.cc.
References Append16(), Append32(), AppendValue(), ns3::PacketMetadata::SmallItem::chunkUid, ns3::PacketMetadata::ExtraItem::fragmentEnd, ns3::PacketMetadata::ExtraItem::fragmentStart, GetUleb128Size(), ns3::PacketMetadata::Data::m_count, ns3::PacketMetadata::Data::m_data, m_data, ns3::PacketMetadata::Data::m_dirtyEnd, m_head, ns3::PacketMetadata::Data::m_size, m_used, sample-rng-plot::n, ns3::PacketMetadata::SmallItem::next, NS_ASSERT, NS_LOG_FUNCTION, ns3::PacketMetadata::ExtraItem::packetUid, ns3::PacketMetadata::SmallItem::prev, ReserveCopy(), ns3::PacketMetadata::SmallItem::size, and ns3::PacketMetadata::SmallItem::typeUid.
Referenced by AddAtEnd(), Deserialize(), RemoveAtEnd(), RemoveAtStart(), and ReplaceTail().
AddHeader()
void ns3::PacketMetadata::AddHeader (Header const & header, uint32_t size)
Add an header.
Parameters
header header to add
size header serialized size
Definition at line 654 of file packet-metadata.cc.
References DoAddHeader(), ns3::ObjectBase::GetInstanceTypeId(), ns3::TypeId::GetUid(), IsStateOk(), NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::Packet::AddHeader().
AddPaddingAtEnd()
void ns3::PacketMetadata::AddPaddingAtEnd (uint32_t end)
Add some padding at the end.
Parameters
end size of padding
Definition at line 879 of file packet-metadata.cc.
References m_enable, m_metadataSkipped, and NS_LOG_FUNCTION.
Referenced by ns3::Packet::AddPaddingAtEnd().
AddSmall()
uint16_t ns3::PacketMetadata::AddSmall (const PacketMetadata::SmallItem * item) inline private
Add a SmallItem.
Parameters
item the SmallItem to add
Returns
added size
Definition at line 374 of file packet-metadata.cc.
References Append16(), AppendValue(), ns3::PacketMetadata::SmallItem::chunkUid, GetUleb128Size(), ns3::PacketMetadata::Data::m_count, ns3::PacketMetadata::Data::m_data, m_data, ns3::PacketMetadata::Data::m_dirtyEnd, m_head, ns3::PacketMetadata::Data::m_size, m_used, sample-rng-plot::n, ns3::PacketMetadata::SmallItem::next, NS_ASSERT, NS_LOG_FUNCTION, ns3::PacketMetadata::SmallItem::prev, ReserveCopy(), ns3::PacketMetadata::SmallItem::size, and ns3::PacketMetadata::SmallItem::typeUid.
Referenced by AddTrailer(), and DoAddHeader().
AddToRaw()
uint8_t * ns3::PacketMetadata::AddToRaw (const uint8_t * data, uint32_t dataSize, uint8_t * start, uint8_t * current, uint32_t maxSize) static private
Helper for the raw serialization.
Parameters
data the buffer to write to
dataSize the data size to write to
start start index
current current index
maxSize maximum size
Returns
updated current index
Definition at line 1404 of file packet-metadata.cc.
References data, NS_LOG_FUNCTION, and visualizer.core::start().
Referenced by Serialize().
AddToRawU16()
uint8_t * ns3::PacketMetadata::AddToRawU16 (const uint16_t & data, uint8_t * start, uint8_t * current, uint32_t maxSize) static private
Helper for the raw serialization.
Parameters
data the buffer to write to
start start index
current current index
maxSize maximum size
Returns
updated current index
Definition at line 1356 of file packet-metadata.cc.
References data, NS_LOG_FUNCTION, and visualizer.core::start().
Referenced by Serialize().
AddToRawU32()
uint8_t * ns3::PacketMetadata::AddToRawU32 (const uint32_t & data, uint8_t * start, uint8_t * current, uint32_t maxSize) static private
Helper for the raw serialization.
Parameters
data the buffer to write to
start start index
current current index
maxSize maximum size
Returns
updated current index
Definition at line 1372 of file packet-metadata.cc.
References data, NS_LOG_FUNCTION, and visualizer.core::start().
Referenced by Serialize().
AddToRawU64()
uint8_t * ns3::PacketMetadata::AddToRawU64 (const uint64_t & data, uint8_t * start, uint8_t * current, uint32_t maxSize) static private
Helper for the raw serialization.
Parameters
data the buffer to write to
start start index
current current index
maxSize maximum size
Returns
updated current index
Definition at line 1388 of file packet-metadata.cc.
References data, NS_LOG_FUNCTION, and visualizer.core::start().
Referenced by Serialize().
AddToRawU8()
uint8_t * ns3::PacketMetadata::AddToRawU8 (const uint8_t & data, uint8_t * start, uint8_t * current, uint32_t maxSize) static private
Helper for the raw serialization.
Parameters
data the buffer to write to
start start index
current current index
maxSize maximum size
Returns
updated current index
Definition at line 1340 of file packet-metadata.cc.
References data, NS_LOG_FUNCTION, and visualizer.core::start().
Referenced by Serialize().
AddTrailer()
void ns3::PacketMetadata::AddTrailer (Trailer const & trailer, uint32_t size)
Add a trailer.
Parameters
trailer trailer to add
size trailer serialized size
Definition at line 731 of file packet-metadata.cc.
References AddSmall(), ns3::PacketMetadata::SmallItem::chunkUid, ns3::ObjectBase::GetInstanceTypeId(), ns3::TypeId::GetUid(), IsStateOk(), m_chunkUid, m_enable, m_metadataSkipped, m_tail, ns3::PacketMetadata::SmallItem::next, NS_ASSERT, NS_LOG_FUNCTION, ns3::PacketMetadata::SmallItem::prev, ns3::PacketMetadata::SmallItem::size, ns3::PacketMetadata::SmallItem::typeUid, and UpdateTail().
Referenced by ns3::Packet::AddTrailer().
Allocate()
struct PacketMetadata::Data * ns3::PacketMetadata::Allocate (uint32_t n) static private
Allocate a buffer data storage.
Parameters
n the storage size to create
Returns
a pointer to the allocated buffer storage
Definition at line 618 of file packet-metadata.cc.
References data, sample-rng-plot::n, NS_LOG_FUNCTION, and PACKET_METADATA_DATA_M_DATA_SIZE.
Referenced by Create().
Append16()
void ns3::PacketMetadata::Append16 (uint16_t value, uint8_t * buffer) inline private
Append a 16-bit value to the buffer.
Parameters
value the value to add
buffer the buffer to write to
Definition at line 237 of file packet-metadata.cc.
References NS_LOG_FUNCTION.
Referenced by AddBig(), AddSmall(), ReplaceTail(), ReserveCopy(), UpdateHead(), and UpdateTail().
Append32()
void ns3::PacketMetadata::Append32 (uint32_t value, uint8_t * buffer) inline private
Append a 32-bit value to the buffer.
Parameters
value the value to add
buffer the buffer to write to
Definition at line 245 of file packet-metadata.cc.
References NS_LOG_FUNCTION.
Referenced by AddBig(), and ReplaceTail().
AppendValue()
void ns3::PacketMetadata::AppendValue (uint32_t value, uint8_t * buffer) inline private
Append a value to the buffer.
Parameters
value the value to add
buffer the buffer to write to
Definition at line 301 of file packet-metadata.cc.
References AppendValueExtra(), and NS_LOG_FUNCTION.
Referenced by AddBig(), AddSmall(), and ReplaceTail().
AppendValueExtra()
void ns3::PacketMetadata::AppendValueExtra (uint32_t value, uint8_t * buffer) private
Append a value to the buffer - extra.
This function is called by AppendValue
Parameters
value the value to add
buffer the buffer to write to
Definition at line 255 of file packet-metadata.cc.
References NS_LOG_FUNCTION.
Referenced by AppendValue().
BeginItem()
PacketMetadata::ItemIterator ns3::PacketMetadata::BeginItem (Buffer buffer) const
Initialize the item iterator to the buffer begin.
Parameters
buffer buffer to initialize.
Returns
the buffer iterator.
Definition at line 1046 of file packet-metadata.cc.
References ItemIterator, and NS_LOG_FUNCTION.
Referenced by ns3::Packet::BeginItem(), and ns3::Packet::Print().
Create()
struct PacketMetadata::Data * ns3::PacketMetadata::Create (uint32_t size) static private
Create a buffer data storage.
Parameters
size the storage size to create
Returns
a pointer to the created buffer storage
Definition at line 570 of file packet-metadata.cc.
References Allocate(), data, Deallocate(), m_freeList, m_maxSize, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by ReserveCopy().
CreateFragment()
PacketMetadata ns3::PacketMetadata::CreateFragment (uint32_t start, uint32_t end) const
Creates a fragment.
Parameters
start the amount of stuff to remove from the start
end the amount of stuff to remove from the end
Returns
the fragment's metadata
Calling this method is equivalent to calling RemoveAtStart (start) and then, RemoveAtEnd (end).
Definition at line 644 of file packet-metadata.cc.
References NS_LOG_FUNCTION, RemoveAtEnd(), RemoveAtStart(), and visualizer.core::start().
Referenced by ns3::Packet::CreateFragment().
Deallocate()
void ns3::PacketMetadata::Deallocate (struct PacketMetadata::Data * data) static private
Deallocate the buffer memory.
Parameters
data the buffer data storage
Definition at line 635 of file packet-metadata.cc.
References data, and NS_LOG_FUNCTION.
Referenced by ns3::PacketMetadata::DataFreeList::~DataFreeList(), Create(), and Recycle().
Deserialize()
uint32_t ns3::PacketMetadata::Deserialize (const uint8_t * buffer, uint32_t size)
Deserialization from raw uint8_t*.
Parameters
buffer the buffer to deserialize from
size the size
Returns
1 on success, 0 on failure
Definition at line 1279 of file packet-metadata.cc.
References AddBig(), ns3::PacketMetadata::SmallItem::chunkUid, ns3::PacketMetadata::ExtraItem::fragmentEnd, ns3::PacketMetadata::ExtraItem::fragmentStart, ns3::TypeId::GetUid(), ns3::TypeId::LookupByName(), m_packetUid, m_tail, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::PacketMetadata::ExtraItem::packetUid, ReadFromRawU16(), ReadFromRawU32(), ReadFromRawU64(), ReadFromRawU8(), ns3::PacketMetadata::SmallItem::size, visualizer.core::start(), ns3::PacketMetadata::SmallItem::typeUid, and UpdateTail().
Referenced by ns3::Packet::Deserialize().
DoAddHeader()
void ns3::PacketMetadata::DoAddHeader (uint32_t uid, uint32_t size) private
Add an header.
Parameters
uid header's uid to add
size header serialized size
Definition at line 663 of file packet-metadata.cc.
References AddSmall(), ns3::PacketMetadata::SmallItem::chunkUid, m_chunkUid, m_enable, m_head, m_metadataSkipped, ns3::PacketMetadata::SmallItem::next, NS_LOG_FUNCTION, ns3::PacketMetadata::SmallItem::prev, ns3::PacketMetadata::SmallItem::size, ns3::PacketMetadata::SmallItem::typeUid, and UpdateHead().
Referenced by PacketMetadata(), and AddHeader().
Enable()
void ns3::PacketMetadata::Enable (void) static
Enable the packet metadata.
Definition at line 52 of file packet-metadata.cc.
References m_enable, m_metadataSkipped, NS_ASSERT_MSG, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::VisualSimulatorImpl::VisualSimulatorImpl(), EpcTftClassifierTestCase::DoRun(), EnableChecking(), and ns3::Packet::EnablePrinting().
EnableChecking()
void ns3::PacketMetadata::EnableChecking (void) static
Enable the packet metadata checking.
Definition at line 66 of file packet-metadata.cc.
References Enable(), m_enableChecking, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Packet::EnableChecking().
GetSerializedSize()
uint32_t ns3::PacketMetadata::GetSerializedSize (void) const
Get the metadata serialized size.
Returns
the seralized size
Definition at line 1133 of file packet-metadata.cc.
References ns3::TypeId::GetName(), m_enable, m_head, m_tail, ns3::PacketMetadata::SmallItem::next, NS_ASSERT, NS_LOG_FUNCTION, ReadItems(), ns3::TypeId::SetUid(), and ns3::PacketMetadata::SmallItem::typeUid.
Referenced by ns3::Packet::GetSerializedSize(), and ns3::Packet::Serialize().
GetTotalSize()
uint32_t ns3::PacketMetadata::GetTotalSize (void) const private
Get the total size used by the metadata.
Returns
the metadata used size
Definition at line 1017 of file packet-metadata.cc.
References m_head, m_tail, ns3::PacketMetadata::SmallItem::next, NS_ASSERT, NS_LOG_FUNCTION, and ReadItems().
GetUid()
uint64_t ns3::PacketMetadata::GetUid (void) const
Get the packet Uid.
Returns
the packet Uid
Definition at line 1040 of file packet-metadata.cc.
References m_packetUid, and NS_LOG_FUNCTION.
Referenced by ns3::Packet::GetUid().
GetUleb128Size()
uint32_t ns3::PacketMetadata::GetUleb128Size (uint32_t value) const inline private
Get the ULEB128 (Unsigned Little Endian Base 128) size.
Parameters
value the value
Returns
the value's ULEB128 size
Definition at line 165 of file packet-metadata.cc.
References NS_LOG_FUNCTION.
Referenced by AddBig(), AddSmall(), and ReplaceTail().
IsPointerOk()
bool ns3::PacketMetadata::IsPointerOk (uint16_t pointer) const private
Check if the position is valid.
Parameters
pointer the position to check
Returns
true if the position is valid
Definition at line 125 of file packet-metadata.cc.
References m_used, and NS_LOG_FUNCTION.
Referenced by IsStateOk().
IsSharedPointerOk()
bool ns3::PacketMetadata::IsSharedPointerOk (uint16_t pointer) const private
Check if the position is valid.
Parameters
pointer the position to check
Returns
true if the position is valid
Definition at line 118 of file packet-metadata.cc.
References m_data, ns3::PacketMetadata::Data::m_size, and NS_LOG_FUNCTION.
Referenced by IsStateOk().
IsStateOk()
bool ns3::PacketMetadata::IsStateOk (void) const private
Check if the metadata state is ok.
Returns
true if the internal state is ok
Definition at line 133 of file packet-metadata.cc.
References IsPointerOk(), IsSharedPointerOk(), m_data, m_head, ns3::PacketMetadata::Data::m_size, m_tail, m_used, ns3::PacketMetadata::SmallItem::next, NS_LOG_FUNCTION, ns3::PacketMetadata::SmallItem::prev, and ReadItems().
Referenced by AddAtEnd(), AddHeader(), AddTrailer(), RemoveAtEnd(), RemoveAtStart(), RemoveHeader(), and RemoveTrailer().
operator=()
PacketMetadata & ns3::PacketMetadata::operator= (PacketMetadata const & o) inline
Basic assignment.
Parameters
o the object to copy
Returns
a copied object
Definition at line 719 of file packet-metadata.h.
References ns3::PacketMetadata::Data::m_count, m_data, m_head, m_packetUid, m_tail, m_used, NS_ASSERT, and Recycle().
ReadFromRawU16()
uint8_t * ns3::PacketMetadata::ReadFromRawU16 (uint16_t & data, const uint8_t * start, const uint8_t * current, uint32_t maxSize) static private
Helper for the raw deserialization.
Parameters
data the buffer to read from
start start index
current current index
maxSize maximum size
Returns
updated current index
Definition at line 1437 of file packet-metadata.cc.
References data, NS_LOG_FUNCTION, and visualizer.core::start().
Referenced by Deserialize().
ReadFromRawU32()
uint8_t * ns3::PacketMetadata::ReadFromRawU32 (uint32_t & data, const uint8_t * start, const uint8_t * current, uint32_t maxSize) static private
Helper for the raw deserialization.
Parameters
data the buffer to read from
start start index
current current index
maxSize maximum size
Returns
updated current index
Definition at line 1453 of file packet-metadata.cc.
References data, NS_LOG_FUNCTION, and visualizer.core::start().
Referenced by Deserialize().
ReadFromRawU64()
uint8_t * ns3::PacketMetadata::ReadFromRawU64 (uint64_t & data, const uint8_t * start, const uint8_t * current, uint32_t maxSize) static private
Helper for the raw deserialization.
Parameters
data the buffer to read from
start start index
current current index
maxSize maximum size
Returns
updated current index
Definition at line 1469 of file packet-metadata.cc.
References data, NS_LOG_FUNCTION, and visualizer.core::start().
Referenced by Deserialize().
ReadFromRawU8()
uint8_t * ns3::PacketMetadata::ReadFromRawU8 (uint8_t & data, const uint8_t * start, const uint8_t * current, uint32_t maxSize) static private
Helper for the raw deserialization.
Parameters
data the buffer to read from
start start index
current current index
maxSize maximum size
Returns
updated current index
Definition at line 1421 of file packet-metadata.cc.
References data, NS_LOG_FUNCTION, and visualizer.core::start().
Referenced by Deserialize().
ReadItems()
uint32_t ns3::PacketMetadata::ReadItems (uint16_t current, struct PacketMetadata::SmallItem * item, struct PacketMetadata::ExtraItem * extraItem) const private
Read items.
Parameters
current the offset we should start reading the data from
item pointer to where we should store the data to return to the caller
extraItem pointer to where we should store the data to return to the caller
Returns
the number of bytes read.
Definition at line 528 of file packet-metadata.cc.
References ns3::PacketMetadata::SmallItem::chunkUid, ns3::PacketMetadata::ExtraItem::fragmentEnd, ns3::PacketMetadata::ExtraItem::fragmentStart, ns3::PacketMetadata::Data::m_data, m_data, m_packetUid, ns3::PacketMetadata::Data::m_size, ns3::PacketMetadata::SmallItem::next, NS_ASSERT, NS_LOG_FUNCTION, ns3::PacketMetadata::ExtraItem::packetUid, ns3::PacketMetadata::SmallItem::prev, ReadUleb128(), ns3::PacketMetadata::SmallItem::size, and ns3::PacketMetadata::SmallItem::typeUid.
Referenced by AddAtEnd(), GetSerializedSize(), GetTotalSize(), IsStateOk(), RemoveAtEnd(), RemoveAtStart(), RemoveHeader(), RemoveTrailer(), ReplaceTail(), and Serialize().
ReadUleb128()
uint32_t ns3::PacketMetadata::ReadUleb128 (const uint8_t ** pBuffer) const private
Read a ULEB128 (Unsigned Little Endian Base 128) coded number.
Parameters
pBuffer the buffer to read from
Returns
the value
Definition at line 187 of file packet-metadata.cc.
References NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ReadItems().
Recycle()
void ns3::PacketMetadata::Recycle (struct PacketMetadata::Data * data) static private
Recycle the buffer memory.
Parameters
data the buffer data storage
Definition at line 596 of file packet-metadata.cc.
References data, Deallocate(), m_enable, m_freeList, m_maxSize, NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by ~PacketMetadata(), operator=(), and ReserveCopy().
RemoveAtEnd()
void ns3::PacketMetadata::RemoveAtEnd (uint32_t end)
Remove a chunk of metadata at the metadata end.
Parameters
end the size of metadata to remove
Definition at line 952 of file packet-metadata.cc.
References AddBig(), IsStateOk(), m_data, m_enable, m_head, m_metadataSkipped, m_packetUid, m_tail, NS_ASSERT, NS_LOG_FUNCTION, ns3::PacketMetadata::SmallItem::prev, ReadItems(), ns3::PacketMetadata::SmallItem::size, and UpdateHead().
Referenced by CreateFragment(), and ns3::Packet::RemoveAtEnd().
RemoveAtStart()
void ns3::PacketMetadata::RemoveAtStart (uint32_t start)
Remove a chunk of metadata at the metadata start.
Parameters
start the size of metadata to remove
Definition at line 889 of file packet-metadata.cc.
References AddBig(), IsStateOk(), m_data, m_enable, m_head, m_metadataSkipped, m_packetUid, m_tail, ns3::PacketMetadata::SmallItem::next, NS_ASSERT, NS_LOG_FUNCTION, ReadItems(), ns3::PacketMetadata::SmallItem::size, visualizer.core::start(), and UpdateTail().
Referenced by CreateFragment(), and ns3::Packet::RemoveAtStart().
RemoveHeader()
void ns3::PacketMetadata::RemoveHeader (Header const & header, uint32_t size)
Remove an header.
Parameters
header header to remove
size header serialized size
Definition at line 683 of file packet-metadata.cc.
References ns3::PacketMetadata::ExtraItem::fragmentEnd, ns3::PacketMetadata::ExtraItem::fragmentStart, ns3::ObjectBase::GetInstanceTypeId(), ns3::TypeId::GetUid(), IsStateOk(), m_enable, m_enableChecking, m_head, m_metadataSkipped, m_tail, m_used, ns3::PacketMetadata::SmallItem::next, NS_ASSERT, NS_FATAL_ERROR, NS_LOG_FUNCTION, ReadItems(), ns3::PacketMetadata::SmallItem::size, and ns3::PacketMetadata::SmallItem::typeUid.
Referenced by ns3::Packet::RemoveHeader().
RemoveTrailer()
void ns3::PacketMetadata::RemoveTrailer (Trailer const & trailer, uint32_t size)
Remove a trailer.
Parameters
trailer trailer to remove
size trailer serialized size
Definition at line 753 of file packet-metadata.cc.
References ns3::PacketMetadata::ExtraItem::fragmentEnd, ns3::PacketMetadata::ExtraItem::fragmentStart, ns3::ObjectBase::GetInstanceTypeId(), ns3::TypeId::GetUid(), IsStateOk(), m_enable, m_enableChecking, m_head, m_metadataSkipped, m_tail, m_used, NS_ASSERT, NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::PacketMetadata::SmallItem::prev, ReadItems(), ns3::PacketMetadata::SmallItem::size, and ns3::PacketMetadata::SmallItem::typeUid.
Referenced by ns3::Packet::RemoveTrailer().
ReplaceTail()
void ns3::PacketMetadata::ReplaceTail (PacketMetadata::SmallItem * item, PacketMetadata::ExtraItem * extraItem, uint32_t available) private
Replace the tail.
Parameters
item the item data to write
extraItem the extra item data to write
available the number of bytes which can be written without having to rewrite the buffer entirely.
Definition at line 450 of file packet-metadata.cc.
References AddBig(), Append16(), Append32(), AppendValue(), ns3::PacketMetadata::SmallItem::chunkUid, ns3::PacketMetadata::ExtraItem::fragmentEnd, ns3::PacketMetadata::ExtraItem::fragmentStart, GetUleb128Size(), ns3::PacketMetadata::Data::m_count, ns3::PacketMetadata::Data::m_data, m_data, ns3::PacketMetadata::Data::m_dirtyEnd, m_head, m_packetUid, ns3::PacketMetadata::Data::m_size, m_tail, m_used, max, sample-rng-plot::n, ns3::PacketMetadata::SmallItem::next, NS_ASSERT, NS_LOG_FUNCTION, ns3::PacketMetadata::ExtraItem::packetUid, ns3::PacketMetadata::SmallItem::prev, ReadItems(), ns3::PacketMetadata::SmallItem::size, ns3::PacketMetadata::SmallItem::typeUid, and UpdateTail().
Referenced by AddAtEnd().
Reserve()
void ns3::PacketMetadata::Reserve (uint32_t n) inline private
Reserve space.
Parameters
n space to reserve
Definition at line 99 of file packet-metadata.cc.
References ns3::PacketMetadata::Data::m_count, m_data, ns3::PacketMetadata::Data::m_dirtyEnd, m_head, ns3::PacketMetadata::Data::m_size, m_used, NS_ASSERT, NS_LOG_FUNCTION, and ReserveCopy().
ReserveCopy()
void ns3::PacketMetadata::ReserveCopy (uint32_t n) private
Reserve space and make a metadata copy.
Parameters
n space to reserve
Definition at line 74 of file packet-metadata.cc.
References Append16(), Create(), ns3::PacketMetadata::Data::m_count, ns3::PacketMetadata::Data::m_data, m_data, ns3::PacketMetadata::Data::m_dirtyEnd, m_head, m_tail, m_used, NS_ASSERT, NS_LOG_FUNCTION, Recycle(), and visualizer.core::start().
Referenced by AddBig(), AddSmall(), and Reserve().
Serialize()
uint32_t ns3::PacketMetadata::Serialize (uint8_t * buffer, uint32_t maxSize) const
Serialization to raw uint8_t*.
Parameters
buffer the buffer to serialize to
maxSize the maximum serialization size
Returns
1 on success, 0 on failure
Definition at line 1178 of file packet-metadata.cc.
References AddToRaw(), AddToRawU16(), AddToRawU32(), AddToRawU64(), AddToRawU8(), ns3::PacketMetadata::SmallItem::chunkUid, ns3::PacketMetadata::ExtraItem::fragmentEnd, ns3::PacketMetadata::ExtraItem::fragmentStart, ns3::TypeId::GetName(), m_head, m_packetUid, m_tail, ns3::PacketMetadata::SmallItem::next, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::PacketMetadata::ExtraItem::packetUid, ReadItems(), ns3::TypeId::SetUid(), ns3::PacketMetadata::SmallItem::size, visualizer.core::start(), and ns3::PacketMetadata::SmallItem::typeUid.
Referenced by ns3::Packet::Serialize().
UpdateHead()
void ns3::PacketMetadata::UpdateHead (uint16_t written) inline private
Update the head.
Parameters
written the used bytes
Definition at line 348 of file packet-metadata.cc.
References Append16(), ns3::PacketMetadata::Data::m_data, m_data, ns3::PacketMetadata::Data::m_dirtyEnd, m_head, m_tail, m_used, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by DoAddHeader(), and RemoveAtEnd().
UpdateTail()
void ns3::PacketMetadata::UpdateTail (uint16_t written) inline private
Update the tail.
Parameters
written the used bytes
Definition at line 321 of file packet-metadata.cc.
References Append16(), ns3::PacketMetadata::Data::m_data, m_data, ns3::PacketMetadata::Data::m_dirtyEnd, m_head, m_tail, m_used, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by AddAtEnd(), AddTrailer(), Deserialize(), RemoveAtStart(), and ReplaceTail().
Friends And Related Function Documentation
ItemIterator
friend class ItemIterator friend
Friend class.
Definition at line 508 of file packet-metadata.h.
Referenced by BeginItem().
Member Data Documentation
m_chunkUid
uint16_t ns3::PacketMetadata::m_chunkUid = 0 static private
Chunk Uid.
Definition at line 676 of file packet-metadata.h.
Referenced by AddTrailer(), and DoAddHeader().
m_data
struct Data* ns3::PacketMetadata::m_data private
Metadata storage.
Definition at line 678 of file packet-metadata.h.
Referenced by PacketMetadata(), ~PacketMetadata(), AddBig(), AddSmall(), IsSharedPointerOk(), IsStateOk(), operator=(), ReadItems(), RemoveAtEnd(), RemoveAtStart(), ReplaceTail(), Reserve(), ReserveCopy(), UpdateHead(), and UpdateTail().
m_enable
bool ns3::PacketMetadata::m_enable = false static private
Enable the packet metadata.
Definition at line 665 of file packet-metadata.h.
Referenced by ns3::PacketMetadata::DataFreeList::~DataFreeList(), AddAtEnd(), AddPaddingAtEnd(), AddTrailer(), DoAddHeader(), Enable(), GetSerializedSize(), Recycle(), RemoveAtEnd(), RemoveAtStart(), RemoveHeader(), and RemoveTrailer().
m_enableChecking
bool ns3::PacketMetadata::m_enableChecking = false static private
Enable the packet metadata checking.
Definition at line 666 of file packet-metadata.h.
Referenced by EnableChecking(), RemoveHeader(), and RemoveTrailer().
m_freeList
PacketMetadata::DataFreeList ns3::PacketMetadata::m_freeList static private
the metadata data storage
Definition at line 664 of file packet-metadata.h.
Referenced by Create(), and Recycle().
m_head
uint16_t ns3::PacketMetadata::m_head private
list head
Definition at line 684 of file packet-metadata.h.
Referenced by AddAtEnd(), AddBig(), AddSmall(), DoAddHeader(), GetSerializedSize(), GetTotalSize(), IsStateOk(), operator=(), RemoveAtEnd(), RemoveAtStart(), RemoveHeader(), RemoveTrailer(), ReplaceTail(), Reserve(), ReserveCopy(), Serialize(), UpdateHead(), and UpdateTail().
m_maxSize
uint32_t ns3::PacketMetadata::m_maxSize = 0 static private
maximum metadata size
Definition at line 675 of file packet-metadata.h.
Referenced by Create(), and Recycle().
m_metadataSkipped
bool ns3::PacketMetadata::m_metadataSkipped = false static private
Set to true when adding metadata to a packet is skipped because m_enable is false; used to detect enabling of metadata in the middle of a simulation, which isn't allowed.
Definition at line 673 of file packet-metadata.h.
Referenced by AddAtEnd(), AddPaddingAtEnd(), AddTrailer(), DoAddHeader(), Enable(), RemoveAtEnd(), RemoveAtStart(), RemoveHeader(), and RemoveTrailer().
m_packetUid
uint64_t ns3::PacketMetadata::m_packetUid private
packet Uid
Definition at line 687 of file packet-metadata.h.
Referenced by Deserialize(), GetUid(), operator=(), ReadItems(), RemoveAtEnd(), RemoveAtStart(), ReplaceTail(), and Serialize().
m_tail
uint16_t ns3::PacketMetadata::m_tail private
list tail
Definition at line 685 of file packet-metadata.h.
Referenced by AddAtEnd(), AddTrailer(), Deserialize(), GetSerializedSize(), GetTotalSize(), IsStateOk(), operator=(), RemoveAtEnd(), RemoveAtStart(), RemoveHeader(), RemoveTrailer(), ReplaceTail(), ReserveCopy(), Serialize(), UpdateHead(), and UpdateTail().
m_used
uint16_t ns3::PacketMetadata::m_used private
used portion
Definition at line 686 of file packet-metadata.h.
Referenced by AddBig(), AddSmall(), IsPointerOk(), IsStateOk(), operator=(), RemoveHeader(), RemoveTrailer(), ReplaceTail(), Reserve(), ReserveCopy(), UpdateHead(), and UpdateTail().
The documentation for this class was generated from the following files:
src/network/model/packet-metadata.h
src/network/model/packet-metadata.cc