ns-3: ns3::UplinkSchedulerMBQoS Class Reference
ns3::UplinkSchedulerMBQoS Class Reference
WiMAX Models
This class implements a Migration-based Quality of Service uplink scheduler(MBQoS).
#include "bs-uplink-scheduler-mbqos.h"
Public Member Functions
UplinkSchedulerMBQoS ()
UplinkSchedulerMBQoS (Time time)
Constructor.
~UplinkSchedulerMBQoS (void)
void AddUplinkAllocation (OfdmUlMapIe &ulMapIe, const uint32_t &allocationSize, uint32_t &symbolsToAllocation, uint32_t &availableSymbols)
Add uplink allocation.
void AllocateInitialRangingInterval (uint32_t &symbolsToAllocation, uint32_t &availableSymbols)
Allocate initial ranging interval.
uint32_t CalculateAllocationStartTime (void)
Calculate allocation start time.
void CheckDeadline (uint32_t &availableSymbols)
Check deadline from jobs. Migrate requests if necessary.
void CheckMinimumBandwidth (uint32_t &availableSymbols)
Check if Minimum bandwidth is guarantee. Migrate requests if necessary.
uint32_t CountSymbolsJobs (Ptr< UlJob > job)
uint32_t CountSymbolsQueue (std::list< Ptr< UlJob > > jobs)
Ptr< UlJob > CreateUlJob (SSRecord *ssRecord, enum ServiceFlow::SchedulingType schedType, ReqType reqType)
Ptr< UlJob > DequeueJob (UlJob::JobPriority priority)
Dequeue a job from a priority queue.
Time DetermineDeadline (ServiceFlow *serviceFlow)
Calculates deadline of a request.
void EnqueueJob (UlJob::JobPriority priority, Ptr< UlJob > job)
Enqueue a job in a priority queue.
void GetChannelDescriptorsToUpdate (bool &updateDcd, bool &updateUcd, bool &sendDcd, bool &sendUcd)
Determines if channel descriptors sent in the current frame are required to be updated.
uint32_t GetPendingSize (ServiceFlow *serviceFlow)
std::list< OfdmUlMapIe > GetUplinkAllocations (void) const
Get uplink allocations.
void InitOnce (void)
This method is called once to initialize window.
void OnSetRequestedBandwidth (ServiceFlowRecord *sfr)
Set requested bandwidth.
void ProcessBandwidthRequest (const BandwidthRequestHeader &bwRequestHdr)
Process bandwidth request function.
void Schedule (void)
Schedule function.
void ServiceBandwidthRequests (const SSRecord *ssRecord, enum ServiceFlow::SchedulingType schedulingType, OfdmUlMapIe &ulMapIe, const WimaxPhy::ModulationType modulationType, uint32_t &symbolsToAllocation, uint32_t &availableSymbols)
Service bandwidth requests.
bool ServiceBandwidthRequests (ServiceFlow *serviceFlow, enum ServiceFlow::SchedulingType schedulingType, OfdmUlMapIe &ulMapIe, const WimaxPhy::ModulationType modulationType, uint32_t &symbolsToAllocation, uint32_t &availableSymbols)
Service bandwidth requests.
bool ServiceBandwidthRequestsBytes (ServiceFlow *serviceFlow, enum ServiceFlow::SchedulingType schedulingType, OfdmUlMapIe &ulMapIe, const WimaxPhy::ModulationType modulationType, uint32_t &symbolsToAllocation, uint32_t &availableSymbols, uint32_t allocationSizeBytes)
Service bandwidth requests bytes.
void ServiceUnsolicitedGrants (const SSRecord *ssRecord, enum ServiceFlow::SchedulingType schedulingType, OfdmUlMapIe &ulMapIe, const WimaxPhy::ModulationType modulationType, uint32_t &symbolsToAllocation, uint32_t &availableSymbols)
Service unsolicited grants.
void SetupServiceFlow (SSRecord *ssRecord, ServiceFlow *serviceFlow)
Setup service flow.
void UplinkSchedWindowTimer (void)
Reset the current window.
Public Member Functions inherited from ns3::UplinkScheduler
UplinkScheduler (Ptr< BaseStationNetDevice > bs)
Constructor.
UplinkScheduler (void)
virtual ~UplinkScheduler (void)
virtual Ptr< BaseStationNetDevice > GetBs (void)
virtual Time GetDcdTimeStamp (void) const
virtual bool GetIsInvIrIntrvlAllocated (void) const
virtual bool GetIsIrIntrvlAllocated (void) const
virtual uint8_t GetNrIrOppsAllocated (void) const
virtual Time GetTimeStampIrInterval (void)
virtual Time GetUcdTimeStamp (void) const
virtual void SetBs (Ptr< BaseStationNetDevice > bs)
Set base station device.
virtual void SetDcdTimeStamp (Time dcdTimeStamp)
Set DCD timestamp.
virtual void SetIsInvIrIntrvlAllocated (bool isInvIrIntrvlAllocated)
Set if the Inv IR interval is allocated.
virtual void SetIsIrIntrvlAllocated (bool isIrIntrvlAllocated)
Set if the IR interval is allocated.
virtual void SetNrIrOppsAllocated (uint8_t nrIrOppsAllocated)
Set the number of IR opps allocated.
virtual void SetTimeStampIrInterval (Time timeStampIrInterval)
Set timestamp IR interval.
virtual void SetUcdTimeStamp (Time ucdTimeStamp)
Set UCD timestamp.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::UplinkScheduler
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
std::list< OfdmUlMapIe > m_uplinkAllocations
uplink allocations
std::list< Ptr< UlJob > > m_uplinkJobs_high
uplink jobs high priority
std::list< Ptr< UlJob > > m_uplinkJobs_inter
uplink jobs intermedite priority
std::list< Ptr< UlJob > > m_uplinkJobs_low
uplink jobs low priority
Time m_windowInterval
windows interval
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class implements a Migration-based Quality of Service uplink scheduler(MBQoS).
This uplink scheduler uses three queues, the low priority queue, the intermediate queue and the high priority queue. The scheduler serves the requests in strict priority order from the high priority queue to the low priority queue. The low priority queue stores the bandwidth requests of the BE service flow. The intermediate queue holds bandwidth requests sent by rtPS and by nrtPS connections. rtPS and nrtPS requests can migrate to the high priority queue to guarantee that their QoS requirements are met. Besides the requests migrated from the intermediate queue, the high priority queue stores periodic grants and unicast request opportunities that must be scheduled in the following frame. To guarantee the maximum delay requirement, the BS assigns a deadline to each rtPS bandwidth request in the intermediate queue. The minimum bandwidth requirement of both rtPS and nrtPS connections is guaranteed over a window of duration T . Implementation of uplink scheduler: Freitag, J.; da Fonseca, N.L.S., "Uplink Scheduling with Quality of Service in IEEE 802.16 Networks," Global Telecommunications Conference, 2007. GLOBECOM '07. IEEE , vol., no., pp.2503-2508, 26-30 Nov. 2007 URL: http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=4411386&isnumber=4410910
Config Paths
ns3::UplinkSchedulerMBQoS is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WimaxNetDevice/$ns3::BaseStationNetDevice/UplinkScheduler/$ns3::UplinkSchedulerMBQoS"
"/NodeList/[i]/DeviceList/[i]/$ns3::BaseStationNetDevice/UplinkScheduler/$ns3::UplinkSchedulerMBQoS"
Attributes
WindowInterval: The time to wait to reset window
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+09ns
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 200 bytes (on a 64-bit architecture).
Definition at line 69 of file bs-uplink-scheduler-mbqos.h.
Constructor & Destructor Documentation
UplinkSchedulerMBQoS() [1/2]
ns3::UplinkSchedulerMBQoS::UplinkSchedulerMBQoS ()
Definition at line 38 of file bs-uplink-scheduler-mbqos.cc.
UplinkSchedulerMBQoS() [2/2]
ns3::UplinkSchedulerMBQoS::UplinkSchedulerMBQoS (Time time)
Constructor.
Parameters
time the time
Definition at line 42 of file bs-uplink-scheduler-mbqos.cc.
~UplinkSchedulerMBQoS()
ns3::UplinkSchedulerMBQoS::~UplinkSchedulerMBQoS (void)
Definition at line 48 of file bs-uplink-scheduler-mbqos.cc.
References m_uplinkAllocations, and ns3::UplinkScheduler::SetBs().
Member Function Documentation
AddUplinkAllocation()
void ns3::UplinkSchedulerMBQoS::AddUplinkAllocation (OfdmUlMapIe & ulMapIe, const uint32_t & allocationSize, uint32_t & symbolsToAllocation, uint32_t & availableSymbols) virtual
Add uplink allocation.
Parameters
ulMapIe the UL map IE
allocationSize the allocation size
symbolsToAllocation the symbols to allocation
availableSymbols the available symbols
Implements ns3::UplinkScheduler.
Definition at line 149 of file bs-uplink-scheduler-mbqos.cc.
References m_uplinkAllocations, ns3::OfdmUlMapIe::SetDuration(), and ns3::OfdmUlMapIe::SetStartTime().
Referenced by AllocateInitialRangingInterval(), Schedule(), ServiceBandwidthRequests(), ServiceBandwidthRequestsBytes(), and ServiceUnsolicitedGrants().
AllocateInitialRangingInterval()
void ns3::UplinkSchedulerMBQoS::AllocateInitialRangingInterval (uint32_t & symbolsToAllocation, uint32_t & availableSymbols) virtual
Allocate initial ranging interval.
Parameters
symbolsToAllocation the symbols to allocation
availableSymbols the available symbols
Implements ns3::UplinkScheduler.
Definition at line 968 of file bs-uplink-scheduler-mbqos.cc.
References AddUplinkAllocation(), CalculateAllocationStartTime(), ns3::UplinkScheduler::GetBs(), ns3::UplinkScheduler::GetNrIrOppsAllocated(), ns3::UplinkScheduler::GetTimeStampIrInterval(), ns3::Simulator::Now(), NS_LOG_DEBUG, ns3::Seconds(), ns3::OfdmUlMapIe::SetCid(), ns3::UplinkScheduler::SetIsIrIntrvlAllocated(), ns3::UplinkScheduler::SetNrIrOppsAllocated(), ns3::OfdmUlMapIe::SetStartTime(), ns3::UplinkScheduler::SetTimeStampIrInterval(), ns3::OfdmUlMapIe::SetUiuc(), and ns3::OfdmUlBurstProfile::UIUC_INITIAL_RANGING.
Referenced by Schedule().
CalculateAllocationStartTime()
uint32_t ns3::UplinkSchedulerMBQoS::CalculateAllocationStartTime (void) virtual
Calculate allocation start time.
Returns
the allocation start time
Implements ns3::UplinkScheduler.
Definition at line 143 of file bs-uplink-scheduler-mbqos.cc.
References ns3::UplinkScheduler::GetBs().
Referenced by AllocateInitialRangingInterval().
CheckDeadline()
void ns3::UplinkSchedulerMBQoS::CheckDeadline (uint32_t & availableSymbols)
Check deadline from jobs. Migrate requests if necessary.
Parameters
availableSymbols available symbols in the uplink frame
This method verifies for each rtPS request whether it should be migrated to the high priority queue or not. The conditions for migration are: request deadline expires in the frame following the next one, and the amount of bandwidth requested is less than or equal to the amount of available bytes in the next uplink frame.
Definition at line 649 of file bs-uplink-scheduler-mbqos.cc.
References EnqueueJob(), ns3::UplinkScheduler::GetBs(), ns3::UlJob::HIGH, m_uplinkJobs_inter, ns3::Simulator::Now(), NS_LOG_DEBUG, ns3::Time::S, and ns3::ServiceFlow::SF_TYPE_RTPS.
Referenced by Schedule().
CheckMinimumBandwidth()
void ns3::UplinkSchedulerMBQoS::CheckMinimumBandwidth (uint32_t & availableSymbols)
Check if Minimum bandwidth is guarantee. Migrate requests if necessary.
Parameters
availableSymbols available symbols in the uplink frame.
This method first calculate a priority value for each request in the intermediate queue. Then, sorts the intermediate queue according to the priority values. Finally, while there is available bandwidth, the scheduler migrate the requests to the high priority queue.
Definition at line 737 of file bs-uplink-scheduler-mbqos.cc.
References CountSymbolsJobs(), EnqueueJob(), ns3::ServiceFlowRecord::GetBacklogged(), ns3::ServiceFlowRecord::GetBackloggedTemp(), ns3::UplinkScheduler::GetBs(), ns3::ServiceFlowRecord::GetBwSinceLastExpiry(), ns3::ServiceFlowRecord::GetGrantedBandwidth(), ns3::ServiceFlowRecord::GetGrantedBandwidthTemp(), ns3::ServiceFlow::GetMinReservedTrafficRate(), ns3::ServiceFlow::GetRecord(), ns3::ServiceFlowRecord::GetRequestedBandwidth(), ns3::ServiceFlow::GetSchedulingType(), ns3::ServiceFlow::GetSduSize(), ns3::SSRecord::GetServiceFlows(), ns3::UlJob::HIGH, list, m_uplinkJobs_inter, ns3::ServiceFlowRecord::SetBackloggedTemp(), ns3::ServiceFlowRecord::SetGrantedBandwidthTemp(), ns3::ServiceFlow::SF_TYPE_ALL, ns3::ServiceFlow::SF_TYPE_NRTPS, and ns3::ServiceFlow::SF_TYPE_RTPS.
Referenced by Schedule().
CountSymbolsJobs()
uint32_t ns3::UplinkSchedulerMBQoS::CountSymbolsJobs (Ptr< UlJob > job)
Parameters
job job
Returns
the symbols count
Count the amount of symbols of a job.
Definition at line 571 of file bs-uplink-scheduler-mbqos.cc.
References ns3::UplinkScheduler::GetBs(), ns3::ServiceFlowRecord::GetGrantedBandwidth(), ns3::ServiceFlowRecord::GetGrantTimeStamp(), ns3::SSRecord::GetModulationType(), ns3::ServiceFlow::GetRecord(), ns3::ServiceFlowRecord::GetRequestedBandwidth(), ns3::ServiceFlow::GetSduSize(), ns3::ServiceFlow::GetUnsolicitedPollingInterval(), ns3::Simulator::Now(), and ns3::UNICAST_POLLING.
Referenced by CheckMinimumBandwidth(), and CountSymbolsQueue().
CountSymbolsQueue()
uint32_t ns3::UplinkSchedulerMBQoS::CountSymbolsQueue (std::list< Ptr< UlJob > > jobs)
Parameters
jobs List of jobs
Returns
the symbols count
Sum the amount of symbols of each job of a queue
Definition at line 546 of file bs-uplink-scheduler-mbqos.cc.
References CountSymbolsJobs(), and list.
Referenced by Schedule().
CreateUlJob()
Ptr< UlJob > ns3::UplinkSchedulerMBQoS::CreateUlJob (SSRecord * ssRecord, enum ServiceFlow::SchedulingType schedType, ReqType reqType)
Parameters
ssRecord Subscriber station record
schedType Service flow type
reqType Type of packet
Returns
Ptr<UlJob>
Create and fill information of a job.
Definition at line 560 of file bs-uplink-scheduler-mbqos.cc.
References ns3::SSRecord::GetServiceFlows().
Referenced by Schedule().
DequeueJob()
Ptr< UlJob > ns3::UplinkSchedulerMBQoS::DequeueJob (UlJob::JobPriority priority)
Dequeue a job from a priority queue.
Parameters
priority Priority of queue
Returns
Ptr<UlJob>
Definition at line 628 of file bs-uplink-scheduler-mbqos.cc.
References ns3::UlJob::HIGH, ns3::UlJob::INTERMEDIATE, ns3::UlJob::LOW, m_uplinkJobs_high, m_uplinkJobs_inter, and m_uplinkJobs_low.
DetermineDeadline()
Time ns3::UplinkSchedulerMBQoS::DetermineDeadline (ServiceFlow * serviceFlow)
Calculates deadline of a request.
Parameters
serviceFlow Service flow of connection
Returns
Time
Definition at line 1146 of file bs-uplink-scheduler-mbqos.cc.
References ns3::ServiceFlowRecord::GetLastGrantTime(), ns3::ServiceFlow::GetMaximumLatency(), ns3::ServiceFlow::GetRecord(), and ns3::MilliSeconds().
Referenced by ProcessBandwidthRequest().
EnqueueJob()
void ns3::UplinkSchedulerMBQoS::EnqueueJob (UlJob::JobPriority priority, Ptr< UlJob > job)
Enqueue a job in a priority queue.
Parameters
priority Priority of queue
job job information
Definition at line 612 of file bs-uplink-scheduler-mbqos.cc.
References ns3::UlJob::HIGH, ns3::UlJob::INTERMEDIATE, ns3::UlJob::LOW, m_uplinkJobs_high, m_uplinkJobs_inter, and m_uplinkJobs_low.
Referenced by CheckDeadline(), CheckMinimumBandwidth(), ProcessBandwidthRequest(), and Schedule().
GetChannelDescriptorsToUpdate()
void ns3::UplinkSchedulerMBQoS::GetChannelDescriptorsToUpdate (bool & updateDcd, bool & updateUcd, bool & sendDcd, bool & sendUcd) virtual
Determines if channel descriptors sent in the current frame are required to be updated.
Parameters
updateDcd update DCD if true
updateUcd update UCD if true
sendDcd send DCD if true
sendUcd send UCD if true
Implements ns3::UplinkScheduler.
Definition at line 84 of file bs-uplink-scheduler-mbqos.cc.
References ns3::UplinkScheduler::GetBs(), ns3::UplinkScheduler::GetDcdTimeStamp(), ns3::UplinkScheduler::GetUcdTimeStamp(), ns3::Simulator::Now(), ns3::UplinkScheduler::SetDcdTimeStamp(), and ns3::UplinkScheduler::SetUcdTimeStamp().
GetPendingSize()
uint32_t ns3::UplinkSchedulerMBQoS::GetPendingSize (ServiceFlow * serviceFlow)
Parameters
serviceFlow ServiceFlow
Returns
Ptr<UlJob>
Get pending size.
Definition at line 1059 of file bs-uplink-scheduler-mbqos.cc.
References list, and m_uplinkJobs_inter.
Referenced by ProcessBandwidthRequest().
GetTypeId()
TypeId ns3::UplinkSchedulerMBQoS::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 55 of file bs-uplink-scheduler-mbqos.cc.
References m_windowInterval, ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::Seconds(), and ns3::TypeId::SetParent().
GetUplinkAllocations()
std::list< OfdmUlMapIe > ns3::UplinkSchedulerMBQoS::GetUplinkAllocations (void) const virtual
Get uplink allocations.
Returns
std::list<OfdmUlMapIe>
Reimplemented from ns3::UplinkScheduler.
Definition at line 78 of file bs-uplink-scheduler-mbqos.cc.
References m_uplinkAllocations.
InitOnce()
void ns3::UplinkSchedulerMBQoS::InitOnce (void) virtual
This method is called once to initialize window.
Implements ns3::UplinkScheduler.
Definition at line 72 of file bs-uplink-scheduler-mbqos.cc.
References UplinkSchedWindowTimer().
OnSetRequestedBandwidth()
void ns3::UplinkSchedulerMBQoS::OnSetRequestedBandwidth (ServiceFlowRecord * sfr) virtual
Set requested bandwidth.
Parameters
sfr the service flow record
Implements ns3::UplinkScheduler.
Definition at line 1155 of file bs-uplink-scheduler-mbqos.cc.
ProcessBandwidthRequest()
void ns3::UplinkSchedulerMBQoS::ProcessBandwidthRequest (const BandwidthRequestHeader & bwRequestHdr) virtual
Process bandwidth request function.
Parameters
bwRequestHdr
Implements ns3::UplinkScheduler.
Definition at line 1081 of file bs-uplink-scheduler-mbqos.cc.
References ns3::Time::As(), ns3::DATA, DetermineDeadline(), EnqueueJob(), ns3::BandwidthRequestHeader::GetBr(), ns3::UplinkScheduler::GetBs(), ns3::BandwidthRequestHeader::GetCid(), ns3::SSRecord::GetMacAddress(), GetPendingSize(), ns3::ServiceFlow::GetSchedulingType(), ns3::UlJob::INTERMEDIATE, ns3::UlJob::LOW, ns3::Simulator::Now(), NS_LOG_DEBUG, ns3::Time::S, ns3::ServiceFlow::SF_TYPE_BE, ns3::ServiceFlow::SF_TYPE_NRTPS, and ns3::ServiceFlow::SF_TYPE_RTPS.
Schedule()
void ns3::UplinkSchedulerMBQoS::Schedule (void) virtual
Schedule function.
Implements ns3::UplinkScheduler.
Definition at line 218 of file bs-uplink-scheduler-mbqos.cc.
References AddUplinkAllocation(), AllocateInitialRangingInterval(), CheckDeadline(), CheckMinimumBandwidth(), CountSymbolsQueue(), CreateUlJob(), ns3::DATA, ns3::WimaxNetDevice::DIRECTION_UPLINK, EnqueueJob(), ns3::SSRecord::GetAreServiceFlowsAllocated(), ns3::SSRecord::GetBasicCid(), ns3::UplinkScheduler::GetBs(), ns3::SSRecord::GetHasServiceFlowBe(), ns3::SSRecord::GetHasServiceFlowNrtps(), ns3::SSRecord::GetHasServiceFlowRtps(), ns3::SSRecord::GetHasServiceFlowUgs(), ns3::SSRecord::GetIsBroadcastSS(), ns3::SSRecord::GetModulationType(), ns3::SSRecord::GetPollForRanging(), ns3::SSRecord::GetRangingStatus(), ns3::SSRecord::GetServiceFlows(), ns3::UlJob::HIGH, m_uplinkAllocations, m_uplinkJobs_high, m_uplinkJobs_inter, m_uplinkJobs_low, ns3::MilliSeconds(), ns3::Simulator::Now(), NS_FATAL_ERROR, NS_LOG_DEBUG, ns3::WimaxNetDevice::RANGING_STATUS_CONTINUE, ns3::WimaxNetDevice::RANGING_STATUS_SUCCESS, ns3::Time::S, ServiceBandwidthRequests(), ServiceBandwidthRequestsBytes(), ServiceUnsolicitedGrants(), ns3::OfdmUlMapIe::SetCid(), ns3::OfdmUlMapIe::SetDuration(), ns3::UplinkScheduler::SetIsInvIrIntrvlAllocated(), ns3::UplinkScheduler::SetIsIrIntrvlAllocated(), ns3::OfdmUlMapIe::SetStartTime(), ns3::OfdmUlMapIe::SetUiuc(), ns3::ServiceFlow::SF_TYPE_BE, ns3::ServiceFlow::SF_TYPE_NRTPS, ns3::ServiceFlow::SF_TYPE_RTPS, ns3::ServiceFlow::SF_TYPE_UGS, ns3::OfdmUlBurstProfile::UIUC_END_OF_MAP, ns3::OfdmUlBurstProfile::UIUC_INITIAL_RANGING, and ns3::UNICAST_POLLING.
ServiceBandwidthRequests() [1/2]
void ns3::UplinkSchedulerMBQoS::ServiceBandwidthRequests (const SSRecord * ssRecord, enum ServiceFlow::SchedulingType schedulingType, OfdmUlMapIe & ulMapIe, const WimaxPhy::ModulationType modulationType, uint32_t & symbolsToAllocation, uint32_t & availableSymbols) virtual
Service bandwidth requests.
Parameters
ssRecord the SS record
schedulingType the scheduling type
ulMapIe the UL map IE
modulationType the modulation type
symbolsToAllocation the symbols to allocation
availableSymbols the available symbols
Implements ns3::UplinkScheduler.
Definition at line 882 of file bs-uplink-scheduler-mbqos.cc.
References ns3::SSRecord::GetServiceFlows().
Referenced by Schedule().
ServiceBandwidthRequests() [2/2]
bool ns3::UplinkSchedulerMBQoS::ServiceBandwidthRequests (ServiceFlow * serviceFlow, enum ServiceFlow::SchedulingType schedulingType, OfdmUlMapIe & ulMapIe, const WimaxPhy::ModulationType modulationType, uint32_t & symbolsToAllocation, uint32_t & availableSymbols) virtual
Service bandwidth requests.
Parameters
serviceFlow the service flow
schedulingType the scheduling type
ulMapIe the UL map IE
modulationType the modulation type
symbolsToAllocation the symbols to allocation
availableSymbols the available symbols
Returns
true if successful
Implements ns3::UplinkScheduler.
Definition at line 906 of file bs-uplink-scheduler-mbqos.cc.
References AddUplinkAllocation(), ns3::ServiceFlowRecord::GetBacklogged(), ns3::UplinkScheduler::GetBs(), ns3::ServiceFlow::GetConnection(), ns3::ServiceFlowRecord::GetGrantedBandwidth(), ns3::ServiceFlow::GetRecord(), ns3::ServiceFlowRecord::GetRequestedBandwidth(), ns3::ServiceFlow::GetSchedulingTypeStr(), ns3::ServiceFlow::GetSduSize(), ns3::ServiceFlow::GetSfid(), ns3::ServiceFlowRecord::IncreaseBacklogged(), ns3::Simulator::Now(), NS_LOG_DEBUG, ns3::ServiceFlowRecord::SetBacklogged(), ns3::ServiceFlowRecord::SetBwSinceLastExpiry(), ns3::ServiceFlowRecord::SetLastGrantTime(), and ns3::ServiceFlowRecord::UpdateGrantedBandwidth().
ServiceBandwidthRequestsBytes()
bool ns3::UplinkSchedulerMBQoS::ServiceBandwidthRequestsBytes (ServiceFlow * serviceFlow, enum ServiceFlow::SchedulingType schedulingType, OfdmUlMapIe & ulMapIe, const WimaxPhy::ModulationType modulationType, uint32_t & symbolsToAllocation, uint32_t & availableSymbols, uint32_t allocationSizeBytes)
Service bandwidth requests bytes.
Parameters
serviceFlow the service flow
schedulingType the scheduling type
ulMapIe the UL map IE
modulationType the modulation type
symbolsToAllocation the symbols to allocation
availableSymbols the available symbols
allocationSizeBytes the allocation size in bytes
Returns
true if successful
Definition at line 494 of file bs-uplink-scheduler-mbqos.cc.
References AddUplinkAllocation(), ns3::UplinkScheduler::GetBs(), ns3::ServiceFlow::GetConnection(), ns3::ServiceFlow::GetRecord(), ns3::ServiceFlowRecord::GetRequestedBandwidth(), ns3::ServiceFlow::GetSchedulingTypeStr(), ns3::ServiceFlow::GetSfid(), ns3::Simulator::Now(), NS_LOG_DEBUG, ns3::Time::S, ns3::ServiceFlowRecord::UpdateBwSinceLastExpiry(), ns3::ServiceFlowRecord::UpdateGrantedBandwidth(), ns3::ServiceFlowRecord::UpdateGrantedBandwidthTemp(), and ns3::ServiceFlowRecord::UpdateRequestedBandwidth().
Referenced by Schedule().
ServiceUnsolicitedGrants()
void ns3::UplinkSchedulerMBQoS::ServiceUnsolicitedGrants (const SSRecord * ssRecord, enum ServiceFlow::SchedulingType schedulingType, OfdmUlMapIe & ulMapIe, const WimaxPhy::ModulationType modulationType, uint32_t & symbolsToAllocation, uint32_t & availableSymbols) virtual
Service unsolicited grants.
Parameters
ssRecord the SS record
schedulingType the scheduling type
ulMapIe the UL map IE
modulationType the modulation type
symbolsToAllocation the symbols to allocation
availableSymbols the available symbols
Implements ns3::UplinkScheduler.
Definition at line 823 of file bs-uplink-scheduler-mbqos.cc.
References AddUplinkAllocation(), ns3::UplinkScheduler::GetBs(), ns3::ServiceFlow::GetConnection(), ns3::ServiceFlow::GetRecord(), ns3::ServiceFlow::GetSchedulingType(), ns3::ServiceFlow::GetSchedulingTypeStr(), ns3::SSRecord::GetServiceFlows(), ns3::ServiceFlow::GetSfid(), ns3::OfdmUlMapIe::GetUiuc(), ns3::Simulator::Now(), NS_LOG_DEBUG, ns3::ServiceFlowRecord::SetLastGrantTime(), ns3::OfdmUlMapIe::SetStartTime(), ns3::OfdmUlMapIe::SetUiuc(), ns3::ServiceFlow::SF_TYPE_UGS, and ns3::OfdmUlBurstProfile::UIUC_REQ_REGION_FULL.
Referenced by Schedule().
SetupServiceFlow()
void ns3::UplinkSchedulerMBQoS::SetupServiceFlow (SSRecord * ssRecord, ServiceFlow * serviceFlow) virtual
Setup service flow.
Parameters
ssRecord the SS record
serviceFlow the service flow
Implements ns3::UplinkScheduler.
Definition at line 1002 of file bs-uplink-scheduler-mbqos.cc.
References ns3::UplinkScheduler::GetBs(), ns3::ServiceFlow::GetIsMulticast(), ns3::ServiceFlow::GetMinReservedTrafficRate(), ns3::ServiceFlow::GetModulation(), ns3::SSRecord::GetModulationType(), ns3::ServiceFlow::GetRecord(), ns3::ServiceFlow::GetSchedulingType(), ns3::ServiceFlow::GetToleratedJitter(), NS_FATAL_ERROR, ns3::ServiceFlowRecord::SetGrantSize(), ns3::ServiceFlow::SetUnsolicitedGrantInterval(), ns3::ServiceFlow::SetUnsolicitedPollingInterval(), ns3::ServiceFlow::SF_TYPE_BE, ns3::ServiceFlow::SF_TYPE_NRTPS, ns3::ServiceFlow::SF_TYPE_RTPS, and ns3::ServiceFlow::SF_TYPE_UGS.
UplinkSchedWindowTimer()
void ns3::UplinkSchedulerMBQoS::UplinkSchedWindowTimer (void)
Reset the current window.
According to a configured time, reset the window.
Definition at line 162 of file bs-uplink-scheduler-mbqos.cc.
References ns3::ServiceFlowRecord::GetBacklogged(), ns3::UplinkScheduler::GetBs(), ns3::ServiceFlowRecord::GetBwSinceLastExpiry(), ns3::ServiceFlow::GetMinReservedTrafficRate(), ns3::ServiceFlow::GetRecord(), ns3::ServiceFlow::GetSchedulingType(), ns3::SSRecord::GetServiceFlows(), ns3::LOG_DEBUG, m_windowInterval, ns3::Simulator::Now(), NS_LOG, ns3::Time::S, ns3::Simulator::Schedule(), ns3::ServiceFlowRecord::SetBwSinceLastExpiry(), ns3::ServiceFlow::SF_TYPE_ALL, ns3::ServiceFlow::SF_TYPE_NRTPS, ns3::ServiceFlow::SF_TYPE_RTPS, and ns3::ServiceFlowRecord::UpdateBwSinceLastExpiry().
Referenced by InitOnce().
Member Data Documentation
m_uplinkAllocations
std::list<OfdmUlMapIe> ns3::UplinkSchedulerMBQoS::m_uplinkAllocations private
uplink allocations
Definition at line 302 of file bs-uplink-scheduler-mbqos.h.
Referenced by ~UplinkSchedulerMBQoS(), AddUplinkAllocation(), GetUplinkAllocations(), and Schedule().
m_uplinkJobs_high
std::list<Ptr<UlJob> > ns3::UplinkSchedulerMBQoS::m_uplinkJobs_high private
uplink jobs high priority
Definition at line 305 of file bs-uplink-scheduler-mbqos.h.
Referenced by DequeueJob(), EnqueueJob(), and Schedule().
m_uplinkJobs_inter
std::list<Ptr<UlJob> > ns3::UplinkSchedulerMBQoS::m_uplinkJobs_inter private
uplink jobs intermedite priority
Definition at line 306 of file bs-uplink-scheduler-mbqos.h.
Referenced by CheckDeadline(), CheckMinimumBandwidth(), DequeueJob(), EnqueueJob(), GetPendingSize(), and Schedule().
m_uplinkJobs_low
std::list<Ptr<UlJob> > ns3::UplinkSchedulerMBQoS::m_uplinkJobs_low private
uplink jobs low priority
Definition at line 307 of file bs-uplink-scheduler-mbqos.h.
Referenced by DequeueJob(), EnqueueJob(), and Schedule().
m_windowInterval
Time ns3::UplinkSchedulerMBQoS::m_windowInterval private
windows interval
Definition at line 310 of file bs-uplink-scheduler-mbqos.h.
Referenced by GetTypeId(), and UplinkSchedWindowTimer().
The documentation for this class was generated from the following files:
src/wimax/model/bs-uplink-scheduler-mbqos.h
src/wimax/model/bs-uplink-scheduler-mbqos.cc