ns-3: TimerTemplateTestCase Class Reference
TimerTemplateTestCase Class Reference
Public Member Functions
TimerTemplateTestCase ()
void baz2i (int, int)
void baz3i (int, int, int)
void baz4i (int, int, int, int)
void baz5i (int, int, int, int, int)
void baz6i (int, int, int, int, int, int)
void bazcip (const int *)
void bazcir (const int &)
void bazi (int)
void bazip (int *)
void bazir (int &)
virtual void DoRun (void)
Implementation to actually run this TestCase.
virtual void DoTeardown (void)
Implementation to do any local setup required for this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 85 of file timer-test-suite.cc.
Constructor & Destructor Documentation
TimerTemplateTestCase()
TimerTemplateTestCase::TimerTemplateTestCase ()
Definition at line 106 of file timer-test-suite.cc.
Member Function Documentation
baz2i()
void TimerTemplateTestCase::baz2i (int , int) inline
Definition at line 94 of file timer-test-suite.cc.
Referenced by DoRun().
baz3i()
void TimerTemplateTestCase::baz3i (int , int , int) inline
Definition at line 95 of file timer-test-suite.cc.
Referenced by DoRun().
baz4i()
void TimerTemplateTestCase::baz4i (int , int , int , int) inline
Definition at line 96 of file timer-test-suite.cc.
Referenced by DoRun().
baz5i()
void TimerTemplateTestCase::baz5i (int , int , int , int , int) inline
Definition at line 97 of file timer-test-suite.cc.
Referenced by DoRun().
baz6i()
void TimerTemplateTestCase::baz6i (int , int , int , int , int , int) inline
Definition at line 98 of file timer-test-suite.cc.
bazcip()
void TimerTemplateTestCase::bazcip (const int *) inline
Definition at line 102 of file timer-test-suite.cc.
bazcir()
void TimerTemplateTestCase::bazcir (const int &) inline
Definition at line 99 of file timer-test-suite.cc.
Referenced by DoRun().
bazi()
void TimerTemplateTestCase::bazi (int) inline
Definition at line 93 of file timer-test-suite.cc.
Referenced by DoRun().
bazip()
void TimerTemplateTestCase::bazip (int *) inline
Definition at line 101 of file timer-test-suite.cc.
bazir()
void TimerTemplateTestCase::bazir (int &) inline
Definition at line 100 of file timer-test-suite.cc.
Referenced by DoRun().
DoRun()
void TimerTemplateTestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 111 of file timer-test-suite.cc.
References anonymous_namespace{timer-test-suite.cc}::bar2i(), anonymous_namespace{timer-test-suite.cc}::bar3i(), anonymous_namespace{timer-test-suite.cc}::bar4i(), anonymous_namespace{timer-test-suite.cc}::bar5i(), anonymous_namespace{timer-test-suite.cc}::barcir(), anonymous_namespace{timer-test-suite.cc}::bari(), anonymous_namespace{timer-test-suite.cc}::barir(), baz2i(), baz3i(), baz4i(), baz5i(), bazcir(), bazi(), bazir(), ns3::Timer::Schedule(), ns3::Seconds(), ns3::Timer::SetArguments(), ns3::Timer::SetDelay(), and ns3::Timer::SetFunction().
DoTeardown()
void TimerTemplateTestCase::DoTeardown (void) virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test teardown
Reimplemented from ns3::TestCase.
Definition at line 176 of file timer-test-suite.cc.
The documentation for this class was generated from the following file:
src/core/test/timer-test-suite.cc