ns-3: LteEnbAntennaTestCase Class Reference
LteEnbAntennaTestCase Class Reference
LTE Models » lte module tests | Test suites
Tests that the propagation model and the antenna parameters are generate the correct values.
Public Member Functions
LteEnbAntennaTestCase ()
LteEnbAntennaTestCase (double orientationDegrees, double beamwidthDegrees, double x, double y, double antennaGainDb)
Constructor.
virtual ~LteEnbAntennaTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Static Public Member Functions
static std::string BuildNameString (double orientationDegrees, double beamwidthDegrees, double x, double y)
Build name string.
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
double m_antennaGainDb
antenna gain in dB
double m_beamwidthDegrees
antenna beamwidth in degrees
double m_orientationDegrees
antenna orientation in degrees
double m_x
x position of the UE
double m_y
y position of the UE
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Tests that the propagation model and the antenna parameters are generate the correct values.
Different test cases are created by specifying different antenna configurations and it is tested if for the given information the pathloss value is as expected.
Definition at line 57 of file test-lte-antenna.cc.
Constructor & Destructor Documentation
LteEnbAntennaTestCase() [1/2]
LteEnbAntennaTestCase::LteEnbAntennaTestCase (double orientationDegrees, double beamwidthDegrees, double x, double y, double antennaGainDb)
Constructor.
Parameters
orientationDegrees the orientation in degrees
beamwidthDegrees the beam width in degrees
x position of UE
y position of UE
antennaGainDb the antenna gain in dB
Definition at line 106 of file test-lte-antenna.cc.
References NS_LOG_FUNCTION.
LteEnbAntennaTestCase() [2/2]
LteEnbAntennaTestCase::LteEnbAntennaTestCase ()
~LteEnbAntennaTestCase()
LteEnbAntennaTestCase::~LteEnbAntennaTestCase () virtual
Definition at line 117 of file test-lte-antenna.cc.
Member Function Documentation
BuildNameString()
std::string LteEnbAntennaTestCase::BuildNameString (double orientationDegrees, double beamwidthDegrees, double x, double y) static
Build name string.
Parameters
orientationDegrees the orientation in degrees
beamwidthDegrees the beam width in degrees
x position of UE
y position of UE
Returns
the name string
Definition at line 95 of file test-lte-antenna.cc.
References sample-rng-plot::x.
DoRun()
void LteEnbAntennaTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 122 of file test-lte-antenna.cc.
References ns3::LteHelper::ActivateDataRadioBearer(), ns3::LteHelper::Attach(), ns3::Config::Connect(), ns3::NodeContainer::Create(), ns3::NetDeviceContainer::Get(), ns3::Object::GetObject(), ns3::LteGlobalPathlossDatabase::GetPathloss(), ns3::LteSpectrumValueCatcher::GetValue(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), m_antennaGainDb, m_beamwidthDegrees, m_orientationDegrees, m_x, m_y, ns3::MakeCallback(), third::mobility, NS_TEST_ASSERT_MSG_EQ_TOL, ns3::Config::Reset(), ns3::Seconds(), ns3::ObjectBase::SetAttribute(), ns3::Config::SetDefault(), ns3::LteHelper::SetEnbAntennaModelAttribute(), ns3::LteHelper::SetEnbAntennaModelType(), ns3::LteHelper::SetPathlossModelAttribute(), ns3::LteHelper::SetSchedulerAttribute(), and ns3::LteHelper::SetSchedulerType().
Member Data Documentation
m_antennaGainDb
double LteEnbAntennaTestCase::m_antennaGainDb private
antenna gain in dB
Definition at line 89 of file test-lte-antenna.cc.
Referenced by DoRun().
m_beamwidthDegrees
double LteEnbAntennaTestCase::m_beamwidthDegrees private
antenna beamwidth in degrees
Definition at line 86 of file test-lte-antenna.cc.
Referenced by DoRun().
m_orientationDegrees
double LteEnbAntennaTestCase::m_orientationDegrees private
antenna orientation in degrees
Definition at line 85 of file test-lte-antenna.cc.
Referenced by DoRun().
m_x
double LteEnbAntennaTestCase::m_x private
x position of the UE
Definition at line 87 of file test-lte-antenna.cc.
Referenced by DoRun().
m_y
double LteEnbAntennaTestCase::m_y private
y position of the UE
Definition at line 88 of file test-lte-antenna.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/lte/test/test-lte-antenna.cc