ns-3: ns3::ThreeGppChannelModel Class Reference
ns3::ThreeGppChannelModel Class Reference
Spectrum Models
Channel Matrix Generation following 3GPP TR 38.901.
#include "three-gpp-channel-model.h"
Classes
struct ParamsTable
Data structure that stores the parameters of 3GPP TR 38.901, Table 7.5-6, for a certain scenario.
struct ThreeGppChannelMatrix
Extends the struct ChannelMatrix by including information that are used within the class ThreeGppChannelModel.
Public Member Functions
ThreeGppChannelModel ()
Constructor.
~ThreeGppChannelModel ()
Destructor.
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
void DoDispose () override
Destructor implementation.
Ptr< const ChannelMatrix > GetChannel (Ptr< const MobilityModel > aMob, Ptr< const MobilityModel > bMob, Ptr< const ThreeGppAntennaArrayModel > aAntenna, Ptr< const ThreeGppAntennaArrayModel > bAntenna) override
Looks for the channel matrix associated to the aMob and bMob pair in m_channelMap.
Ptr< ChannelConditionModel > GetChannelConditionModel () const
Get the associated channel condition model.
double GetFrequency (void) const
Returns the center frequency.
std::string GetScenario (void) const
Returns the propagation scenario.
void SetChannelConditionModel (Ptr< ChannelConditionModel > model)
Set the channel condition model.
void SetFrequency (double f)
Sets the center frequency of the model.
void SetScenario (const std::string &scenario)
Sets the propagation scenario.
Public Member Functions inherited from ns3::MatrixBasedChannelModel
virtual ~MatrixBasedChannelModel ()
Destructor for MatrixBasedChannelModel.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::MatrixBasedChannelModel
static constexpr uint32_t GetKey (uint32_t x1, uint32_t x2)
Calculate the channel key using the Cantor function.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
DoubleVector CalcAttenuationOfBlockage (Ptr< ThreeGppChannelMatrix > params, const DoubleVector &clusterAOA, const DoubleVector &clusterZOA) const
Applies the blockage model A described in 3GPP TR 38.901.
bool ChannelMatrixNeedsUpdate (Ptr< const ThreeGppChannelMatrix > channelMatrix, Ptr< const ChannelCondition > channelCondition) const
Check if the channel matrix has to be updated.
Ptr< ThreeGppChannelMatrix > GetNewChannel (Vector locUT, Ptr< const ChannelCondition > channelCondition, Ptr< const ThreeGppAntennaArrayModel > sAntenna, Ptr< const ThreeGppAntennaArrayModel > uAntenna, Angles &uAngle, Angles &sAngle, double dis2D, double hBS, double hUT) const
Compute the channel matrix between two devices using the procedure described in 3GPP TR 38.901.
virtual Ptr< const ParamsTable > GetThreeGppTable (Ptr< const ChannelCondition > channelCondition, double hBS, double hUT, double distance2D) const
Get the parameters needed to apply the channel generation procedure.
void Shuffle (double *first, double *last) const
Shuffle the elements of a simple sequence container of type double.
Private Attributes
bool m_blockage
enables the blockage model A
double m_blockerSpeed
the blocker speed
Ptr< ChannelConditionModel > m_channelConditionModel
the channel condition model
std::unordered_map< uint32_t, Ptr< ThreeGppChannelMatrix > > m_channelMap
map containing the channel realizations
double m_frequency
the operating frequency
Ptr< NormalRandomVariable > m_normalRv
normal random variable
uint16_t m_numNonSelfBlocking
number of non-self-blocking regions
bool m_portraitMode
true if potrait mode, false if landscape
std::string m_scenario
the 3GPP scenario
Ptr< UniformRandomVariable > m_uniformRv
uniform random variable
Ptr< UniformRandomVariable > m_uniformRvShuffle
uniform random variable used to shuffle array in GetNewChannel
Time m_updatePeriod
the channel update period
Static Private Attributes
static const uint8_t PHI_INDEX = 0
index of the PHI value in the m_nonSelfBlocking array
static const uint8_t R_INDEX = 4
index of the R value in the m_nonSelfBlocking array
static const uint8_t THETA_INDEX = 2
index of the THETA value in the m_nonSelfBlocking array
static const uint8_t X_INDEX = 1
index of the X value in the m_nonSelfBlocking array
static const uint8_t Y_INDEX = 3
index of the Y value in the m_nonSelfBlocking array
Additional Inherited Members
Public Types inherited from ns3::MatrixBasedChannelModel
typedef std::vector< ThreeGppAntennaArrayModel::ComplexVector > Complex2DVector
type definition for complex matrices
typedef std::vector< Complex2DVector > Complex3DVector
type definition for complex 3D matrices
typedef std::vector< DoubleVector > Double2DVector
type definition for matrices of doubles
typedef std::vector< Double2DVector > Double3DVector
type definition for 3D matrices of doubles
typedef std::vector< double > DoubleVector
type definition for vectors of doubles
Static Public Attributes inherited from ns3::MatrixBasedChannelModel
static const uint8_t AOA_INDEX = 0
index of the AOA value in the m_angle array
static const uint8_t AOD_INDEX = 2
index of the AOD value in the m_angle array
static const uint8_t ZOA_INDEX = 1
index of the ZOA value in the m_angle array
static const uint8_t ZOD_INDEX = 3
index of the ZOD value in the m_angle array
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Channel Matrix Generation following 3GPP TR 38.901.
Introspection did not find any typical Config paths.
The class implements the channel matrix generation procedure described in 3GPP TR 38.901.
See also
GetChannel
Attributes
Frequency: The operating Frequency in Hz
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 5e+08
Flags: construct write read
Scenario: The 3GPP scenario (RMa, UMa, UMi-StreetCanyon, InH-OfficeOpen, InH-OfficeMixed)
Set with class: StringValue
Underlying type:
Initial value: UMa
Flags: construct write read
ChannelConditionModel: Pointer to the channel condition model
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::ChannelConditionModel>
Initial value: 0x0
Flags: construct write read
UpdatePeriod: Specify the channel coherence time
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
Blockage: Enable blockage model A (sec 7.6.4.1)
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
NumNonselfBlocking: number of non-self-blocking regions
Set with class: ns3::IntegerValue
Underlying type: uint16_t 0:65535
Initial value: 4
Flags: construct write read
PortraitMode: true for portrait mode, false for landscape mode
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
BlockerSpeed: The speed of moving blockers, the unit is m/s
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 1
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 160 bytes (on a 64-bit architecture).
Definition at line 48 of file three-gpp-channel-model.h.
Constructor & Destructor Documentation
ThreeGppChannelModel()
ns3::ThreeGppChannelModel::ThreeGppChannelModel ()
Constructor.
Definition at line 163 of file three-gpp-channel-model.cc.
References m_normalRv, m_uniformRv, m_uniformRvShuffle, and NS_LOG_FUNCTION.
~ThreeGppChannelModel()
ns3::ThreeGppChannelModel::~ThreeGppChannelModel ()
Destructor.
Definition at line 174 of file three-gpp-channel-model.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AssignStreams()
int64_t ns3::ThreeGppChannelModel::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 2050 of file three-gpp-channel-model.cc.
References m_normalRv, m_uniformRv, m_uniformRvShuffle, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
CalcAttenuationOfBlockage()
MatrixBasedChannelModel::DoubleVector ns3::ThreeGppChannelModel::CalcAttenuationOfBlockage (Ptr< ThreeGppChannelMatrix > params, const DoubleVector & clusterAOA, const DoubleVector & clusterZOA) const private
Applies the blockage model A described in 3GPP TR 38.901.
Parameters
params the channel matrix
clusterAOA vector containing the azimuth angle of arrival for each cluster
clusterZOA vector containing the zenith angle of arrival for each cluster
Returns
vector containing the power attenuation for each cluster
Definition at line 1820 of file three-gpp-channel-model.cc.
References ns3::UniformRandomVariable::GetValue(), m_blockerSpeed, m_frequency, m_normalRv, m_numNonSelfBlocking, m_portraitMode, m_scenario, m_uniformRv, ns3::Now(), NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_INFO, PHI_INDEX, R_INDEX, THETA_INDEX, X_INDEX, and Y_INDEX.
Referenced by GetNewChannel().
ChannelMatrixNeedsUpdate()
bool ns3::ThreeGppChannelModel::ChannelMatrixNeedsUpdate (Ptr< const ThreeGppChannelMatrix > channelMatrix, Ptr< const ChannelCondition > channelCondition) const private
Check if the channel matrix has to be updated.
Parameters
channelMatrix channel matrix
channelCondition the channel condition
Returns
true if the channel matrix has to be updated, false otherwise
Definition at line 947 of file three-gpp-channel-model.cc.
References ns3::Time::IsZero(), m_updatePeriod, ns3::Now(), ns3::Simulator::Now(), ns3::Time::NS, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by GetChannel().
DoDispose()
void ns3::ThreeGppChannelModel::DoDispose (void) override virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 180 of file three-gpp-channel-model.cc.
References m_channelConditionModel, and m_channelMap.
GetChannel()
Ptr< const MatrixBasedChannelModel::ChannelMatrix > ns3::ThreeGppChannelModel::GetChannel (Ptr< const MobilityModel > aMob, Ptr< const MobilityModel > bMob, Ptr< const ThreeGppAntennaArrayModel > aAntenna, Ptr< const ThreeGppAntennaArrayModel > bAntenna) override virtual
Looks for the channel matrix associated to the aMob and bMob pair in m_channelMap.
If found, it checks if it has to be updated. If not found or if it has to be updated, it generates a new uncorrelated channel matrix using the method GetNewChannel and updates m_channelMap.
Parameters
aMob mobility model of the a device
bMob mobility model of the b device
aAntenna antenna of the a device
bAntenna antenna of the b device
Returns
the channel matrix
Implements ns3::MatrixBasedChannelModel.
Definition at line 971 of file three-gpp-channel-model.cc.
References ChannelMatrixNeedsUpdate(), ns3::Node::GetId(), ns3::MatrixBasedChannelModel::GetKey(), GetNewChannel(), m_channelConditionModel, m_channelMap, max, min, NS_LOG_DEBUG, NS_LOG_FUNCTION, and sample-rng-plot::x.
GetChannelConditionModel()
Ptr< ChannelConditionModel > ns3::ThreeGppChannelModel::GetChannelConditionModel (void) const
Get the associated channel condition model.
Returns
a pointer to the ChannelConditionModel object
Definition at line 251 of file three-gpp-channel-model.cc.
References m_channelConditionModel, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetFrequency()
double ns3::ThreeGppChannelModel::GetFrequency (void) const
Returns the center frequency.
Returns
the center frequency in Hz
Definition at line 266 of file three-gpp-channel-model.cc.
References m_frequency, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetNewChannel()
Ptr< ThreeGppChannelModel::ThreeGppChannelMatrix > ns3::ThreeGppChannelModel::GetNewChannel (Vector locUT, Ptr< const ChannelCondition > channelCondition, Ptr< const ThreeGppAntennaArrayModel > sAntenna, Ptr< const ThreeGppAntennaArrayModel > uAntenna, Angles & uAngle, Angles & sAngle, double dis2D, double hBS, double hUT) const private
Compute the channel matrix between two devices using the procedure described in 3GPP TR 38.901.
Parameters
locUT the location of the UT
channelCondition the channel condition
sAntenna the s node antenna array
uAntenna the u node antenna array
uAngle the u node angle
sAngle the s node angle
dis2D the 2D distance between tx and rx
hBS the height of the BS
hUT the height of the UT
Returns
the channel realization
Definition at line 1040 of file three-gpp-channel-model.cc.
References CalcAttenuationOfBlockage(), GetThreeGppTable(), ns3::UniformRandomVariable::GetValue(), m_blockage, m_frequency, m_normalRv, m_uniformRv, ns3::max(), min, ns3::min(), ns3::Simulator::Now(), NS_ASSERT, NS_ASSERT_MSG, NS_FATAL_ERROR, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::offSetAlpha, ns3::Angles::phi, Shuffle(), and ns3::Angles::theta.
Referenced by GetChannel().
GetScenario()
std::string ns3::ThreeGppChannelModel::GetScenario (void) const
Returns the propagation scenario.
Returns
the propagation scenario
Definition at line 285 of file three-gpp-channel-model.cc.
References m_scenario, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetThreeGppTable()
Ptr< const ThreeGppChannelModel::ParamsTable > ns3::ThreeGppChannelModel::GetThreeGppTable (Ptr< const ChannelCondition > channelCondition, double hBS, double hUT, double distance2D) const private virtual
Get the parameters needed to apply the channel generation procedure.
Parameters
channelCondition the channel condition
hBS the height of the BS
hUT the height of the UT
distance2D the 2D distance between tx and rx
Returns
the parameters table
Definition at line 292 of file three-gpp-channel-model.cc.
References m_frequency, m_scenario, max, NS_ASSERT_MSG, NS_FATAL_ERROR, NS_LOG_FUNCTION, NS_LOG_WARN, ns3::sqrtC_office_LOS, ns3::sqrtC_office_NLOS, ns3::sqrtC_RMa_LOS, ns3::sqrtC_RMa_NLOS, ns3::sqrtC_RMa_O2I, ns3::sqrtC_UMa_LOS, ns3::sqrtC_UMa_NLOS, ns3::sqrtC_UMa_O2I, ns3::sqrtC_UMi_LOS, ns3::sqrtC_UMi_NLOS, and ns3::sqrtC_UMi_O2I.
Referenced by GetNewChannel().
GetTypeId()
TypeId ns3::ThreeGppChannelModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 188 of file three-gpp-channel-model.cc.
References GetChannelConditionModel(), GetFrequency(), GetScenario(), m_blockage, m_blockerSpeed, m_numNonSelfBlocking, m_portraitMode, m_updatePeriod, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeDoubleAccessor(), ns3::MakeIntegerAccessor(), ns3::MakePointerAccessor(), ns3::MakeStringAccessor(), ns3::MakeStringChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MilliSeconds(), SetChannelConditionModel(), SetFrequency(), ns3::TypeId::SetParent(), and SetScenario().
SetChannelConditionModel()
void ns3::ThreeGppChannelModel::SetChannelConditionModel (Ptr< ChannelConditionModel > model)
Set the channel condition model.
Parameters
a pointer to the ChannelConditionModel object
Definition at line 244 of file three-gpp-channel-model.cc.
References m_channelConditionModel, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetFrequency()
void ns3::ThreeGppChannelModel::SetFrequency (double f)
Sets the center frequency of the model.
Parameters
f the center frequency in Hz
Definition at line 258 of file three-gpp-channel-model.cc.
References f(), m_frequency, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetScenario()
void ns3::ThreeGppChannelModel::SetScenario (const std::string & scenario)
Sets the propagation scenario.
Parameters
scenario the propagation scenario
Definition at line 273 of file three-gpp-channel-model.cc.
References m_scenario, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
Shuffle()
void ns3::ThreeGppChannelModel::Shuffle (double * first, double * last) const private
Shuffle the elements of a simple sequence container of type double.
Parameters
first Pointer to the first element among the elements to be shuffled
last Pointer to the last element among the elements to be shuffled
Definition at line 2041 of file three-gpp-channel-model.cc.
References ns3::UniformRandomVariable::GetInteger(), and m_uniformRvShuffle.
Referenced by GetNewChannel().
Member Data Documentation
m_blockage
bool ns3::ThreeGppChannelModel::m_blockage private
enables the blockage model A
Definition at line 254 of file three-gpp-channel-model.h.
Referenced by GetNewChannel(), and GetTypeId().
m_blockerSpeed
double ns3::ThreeGppChannelModel::m_blockerSpeed private
the blocker speed
Definition at line 257 of file three-gpp-channel-model.h.
Referenced by CalcAttenuationOfBlockage(), and GetTypeId().
m_channelConditionModel
Ptr<ChannelConditionModel> ns3::ThreeGppChannelModel::m_channelConditionModel private
the channel condition model
Definition at line 248 of file three-gpp-channel-model.h.
Referenced by DoDispose(), GetChannel(), GetChannelConditionModel(), and SetChannelConditionModel().
m_channelMap
std::unordered_map<uint32_t, Ptr<ThreeGppChannelMatrix> > ns3::ThreeGppChannelModel::m_channelMap private
map containing the channel realizations
Definition at line 244 of file three-gpp-channel-model.h.
Referenced by DoDispose(), and GetChannel().
m_frequency
double ns3::ThreeGppChannelModel::m_frequency private
the operating frequency
Definition at line 246 of file three-gpp-channel-model.h.
Referenced by CalcAttenuationOfBlockage(), GetFrequency(), GetNewChannel(), GetThreeGppTable(), and SetFrequency().
m_normalRv
Ptr<NormalRandomVariable> ns3::ThreeGppChannelModel::m_normalRv private
normal random variable
Definition at line 250 of file three-gpp-channel-model.h.
Referenced by ThreeGppChannelModel(), AssignStreams(), CalcAttenuationOfBlockage(), and GetNewChannel().
m_numNonSelfBlocking
uint16_t ns3::ThreeGppChannelModel::m_numNonSelfBlocking private
number of non-self-blocking regions
Definition at line 255 of file three-gpp-channel-model.h.
Referenced by CalcAttenuationOfBlockage(), and GetTypeId().
m_portraitMode
bool ns3::ThreeGppChannelModel::m_portraitMode private
true if potrait mode, false if landscape
Definition at line 256 of file three-gpp-channel-model.h.
Referenced by CalcAttenuationOfBlockage(), and GetTypeId().
m_scenario
std::string ns3::ThreeGppChannelModel::m_scenario private
the 3GPP scenario
Definition at line 247 of file three-gpp-channel-model.h.
Referenced by CalcAttenuationOfBlockage(), GetScenario(), GetThreeGppTable(), and SetScenario().
m_uniformRv
Ptr<UniformRandomVariable> ns3::ThreeGppChannelModel::m_uniformRv private
uniform random variable
Definition at line 249 of file three-gpp-channel-model.h.
Referenced by ThreeGppChannelModel(), AssignStreams(), CalcAttenuationOfBlockage(), and GetNewChannel().
m_uniformRvShuffle
Ptr<UniformRandomVariable> ns3::ThreeGppChannelModel::m_uniformRvShuffle private
uniform random variable used to shuffle array in GetNewChannel
Definition at line 251 of file three-gpp-channel-model.h.
Referenced by ThreeGppChannelModel(), AssignStreams(), and Shuffle().
m_updatePeriod
Time ns3::ThreeGppChannelModel::m_updatePeriod private
the channel update period
Definition at line 245 of file three-gpp-channel-model.h.
Referenced by ChannelMatrixNeedsUpdate(), and GetTypeId().
PHI_INDEX
const uint8_t ns3::ThreeGppChannelModel::PHI_INDEX = 0 static private
index of the PHI value in the m_nonSelfBlocking array
Definition at line 259 of file three-gpp-channel-model.h.
Referenced by CalcAttenuationOfBlockage().
R_INDEX
const uint8_t ns3::ThreeGppChannelModel::R_INDEX = 4 static private
index of the R value in the m_nonSelfBlocking array
Definition at line 263 of file three-gpp-channel-model.h.
Referenced by CalcAttenuationOfBlockage().
THETA_INDEX
const uint8_t ns3::ThreeGppChannelModel::THETA_INDEX = 2 static private
index of the THETA value in the m_nonSelfBlocking array
Definition at line 261 of file three-gpp-channel-model.h.
Referenced by CalcAttenuationOfBlockage().
X_INDEX
const uint8_t ns3::ThreeGppChannelModel::X_INDEX = 1 static private
index of the X value in the m_nonSelfBlocking array
Definition at line 260 of file three-gpp-channel-model.h.
Referenced by CalcAttenuationOfBlockage().
Y_INDEX
const uint8_t ns3::ThreeGppChannelModel::Y_INDEX = 3 static private
index of the Y value in the m_nonSelfBlocking array
Definition at line 262 of file three-gpp-channel-model.h.
Referenced by CalcAttenuationOfBlockage().
The documentation for this class was generated from the following files:
src/spectrum/model/three-gpp-channel-model.h
src/spectrum/model/three-gpp-channel-model.cc