ns-3: ns3::dsr::DsrOptionHeader Class Reference
ns3::dsr::DsrOptionHeader Class Reference
Header for Dsr Options.
#include "dsr-option-header.h"
Classes
struct Alignment
represents the alignment requirements of an option header
Public Member Functions
DsrOptionHeader ()
Constructor.
virtual ~DsrOptionHeader ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
virtual Alignment GetAlignment () const
Get the Alignment requirement of this option header.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
uint8_t GetLength () const
Get the option length.
virtual uint32_t GetSerializedSize () const
Get the serialized size of the packet.
uint8_t GetType () const
Get the type of the option.
virtual void Print (std::ostream &os) const
Print some information about the packet.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetLength (uint8_t length)
Set the option length.
void SetType (uint8_t type)
Set the type of the option.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Buffer m_data
The anonymous data of this option.
uint8_t m_length
The option length.
uint8_t m_type
The type of the option.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Header for Dsr Options.
Introspection did not find any typical Config paths.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 48 bytes (on a 64-bit architecture).
Definition at line 50 of file dsr-option-header.h.
Constructor & Destructor Documentation
DsrOptionHeader()
ns3::dsr::DsrOptionHeader::DsrOptionHeader ()
Constructor.
Definition at line 64 of file dsr-option-header.cc.
~DsrOptionHeader()
ns3::dsr::DsrOptionHeader::~DsrOptionHeader () virtual
Destructor.
Definition at line 70 of file dsr-option-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::dsr::DsrOptionHeader::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start Buffer iterator
Returns
size of the packet
Implements ns3::Header.
Reimplemented in ns3::dsr::DsrOptionAckHeader, ns3::dsr::DsrOptionAckReqHeader, ns3::dsr::DsrOptionRerrUnsupportHeader, ns3::dsr::DsrOptionRerrUnreachHeader, ns3::dsr::DsrOptionRerrHeader, ns3::dsr::DsrOptionSRHeader, ns3::dsr::DsrOptionRrepHeader, ns3::dsr::DsrOptionRreqHeader, ns3::dsr::DsrOptionPadnHeader, and ns3::dsr::DsrOptionPad1Header.
Definition at line 113 of file dsr-option-header.cc.
References ns3::Buffer::AddAtEnd(), ns3::Buffer::Begin(), GetSerializedSize(), m_data, m_length, m_type, ns3::Buffer::Iterator::Next(), ns3::Buffer::Iterator::ReadU8(), visualizer.core::start(), and ns3::Buffer::Iterator::Write().
GetAlignment()
DsrOptionHeader::Alignment ns3::dsr::DsrOptionHeader::GetAlignment () const virtual
Get the Alignment requirement of this option header.
Returns
The required alignment
Subclasses should only implement this method, if special alignment is required. Default is no alignment (1n+0).
Reimplemented in ns3::dsr::DsrOptionAckHeader, ns3::dsr::DsrOptionAckReqHeader, ns3::dsr::DsrOptionRerrUnsupportHeader, ns3::dsr::DsrOptionRerrUnreachHeader, ns3::dsr::DsrOptionRerrHeader, ns3::dsr::DsrOptionSRHeader, ns3::dsr::DsrOptionRrepHeader, and ns3::dsr::DsrOptionRreqHeader.
Definition at line 130 of file dsr-option-header.cc.
Referenced by ns3::dsr::DsrOptionField::AddDsrOption().
GetInstanceTypeId()
TypeId ns3::dsr::DsrOptionHeader::GetInstanceTypeId (void) const virtual
Get the instance type ID.
Returns
instance type ID
Implements ns3::ObjectBase.
Reimplemented in ns3::dsr::DsrOptionAckHeader, ns3::dsr::DsrOptionAckReqHeader, ns3::dsr::DsrOptionRerrUnsupportHeader, ns3::dsr::DsrOptionRerrUnreachHeader, ns3::dsr::DsrOptionRerrHeader, ns3::dsr::DsrOptionSRHeader, ns3::dsr::DsrOptionRrepHeader, ns3::dsr::DsrOptionRreqHeader, ns3::dsr::DsrOptionPadnHeader, and ns3::dsr::DsrOptionPad1Header.
Definition at line 59 of file dsr-option-header.cc.
References GetTypeId().
GetLength()
uint8_t ns3::dsr::DsrOptionHeader::GetLength () const
Get the option length.
Returns
the option length
Definition at line 89 of file dsr-option-header.cc.
References m_length.
Referenced by ns3::dsr::DsrRouting::AddAckReqHeader(), ns3::dsr::DsrRouting::CheckSendBuffer(), ns3::dsr::DsrOptionRerr::DoSendError(), ns3::dsr::DsrRouting::ForwardErrPacket(), ns3::dsr::DsrRouting::ForwardPacket(), ns3::dsr::DsrOptionPadnHeader::GetSerializedSize(), ns3::dsr::DsrRouting::PacketNewRoute(), ns3::dsr::DsrOptionPadnHeader::Print(), ns3::dsr::DsrOptionRreqHeader::Print(), ns3::dsr::DsrOptionRrepHeader::Print(), ns3::dsr::DsrOptionSRHeader::Print(), ns3::dsr::DsrOptionRerrHeader::Print(), ns3::dsr::DsrOptionRerrUnreachHeader::Print(), ns3::dsr::DsrOptionRerrUnsupportHeader::Print(), ns3::dsr::DsrOptionAckReqHeader::Print(), ns3::dsr::DsrOptionAckHeader::Print(), ns3::dsr::DsrOptionRreq::Process(), ns3::dsr::DsrOptionRrep::Process(), ns3::dsr::DsrOptionSR::Process(), ns3::dsr::DsrRouting::Receive(), ns3::dsr::DsrRouting::SalvagePacket(), ns3::dsr::DsrRouting::Send(), ns3::dsr::DsrRouting::SendErrorRequest(), ns3::dsr::DsrRouting::SendGratuitousReply(), ns3::dsr::DsrRouting::SendInitialRequest(), ns3::dsr::DsrRouting::SendPacketFromBuffer(), ns3::dsr::DsrRouting::SendUnreachError(), ns3::dsr::DsrOptionPadnHeader::Serialize(), ns3::dsr::DsrOptionRreqHeader::Serialize(), ns3::dsr::DsrOptionRrepHeader::Serialize(), ns3::dsr::DsrOptionSRHeader::Serialize(), ns3::dsr::DsrOptionRerrHeader::Serialize(), ns3::dsr::DsrOptionRerrUnreachHeader::Serialize(), ns3::dsr::DsrOptionRerrUnsupportHeader::Serialize(), ns3::dsr::DsrOptionAckReqHeader::Serialize(), and ns3::dsr::DsrOptionAckHeader::Serialize().
GetSerializedSize()
uint32_t ns3::dsr::DsrOptionHeader::GetSerializedSize (void) const virtual
Get the serialized size of the packet.
Returns
size
Implements ns3::Header.
Reimplemented in ns3::dsr::DsrOptionAckHeader, ns3::dsr::DsrOptionAckReqHeader, ns3::dsr::DsrOptionRerrUnsupportHeader, ns3::dsr::DsrOptionRerrUnreachHeader, ns3::dsr::DsrOptionRerrHeader, ns3::dsr::DsrOptionSRHeader, ns3::dsr::DsrOptionRrepHeader, ns3::dsr::DsrOptionRreqHeader, ns3::dsr::DsrOptionPadnHeader, and ns3::dsr::DsrOptionPad1Header.
Definition at line 99 of file dsr-option-header.cc.
References m_length.
Referenced by ns3::dsr::DsrOptionField::AddDsrOption(), and Deserialize().
GetType()
uint8_t ns3::dsr::DsrOptionHeader::GetType () const
Get the type of the option.
Returns
the type of the option
Definition at line 79 of file dsr-option-header.cc.
References m_type.
Referenced by DsrFsHeaderTest::DoRun(), ns3::dsr::DsrOptionPad1Header::Print(), ns3::dsr::DsrOptionPadnHeader::Print(), ns3::dsr::DsrOptionRreqHeader::Print(), ns3::dsr::DsrOptionRrepHeader::Print(), ns3::dsr::DsrOptionSRHeader::Print(), ns3::dsr::DsrOptionRerrHeader::Print(), ns3::dsr::DsrOptionRerrUnreachHeader::Print(), ns3::dsr::DsrOptionRerrUnsupportHeader::Print(), ns3::dsr::DsrOptionAckReqHeader::Print(), ns3::dsr::DsrOptionAckHeader::Print(), ns3::dsr::DsrOptionPad1Header::Serialize(), ns3::dsr::DsrOptionPadnHeader::Serialize(), ns3::dsr::DsrOptionRreqHeader::Serialize(), ns3::dsr::DsrOptionRrepHeader::Serialize(), ns3::dsr::DsrOptionSRHeader::Serialize(), ns3::dsr::DsrOptionRerrHeader::Serialize(), ns3::dsr::DsrOptionRerrUnreachHeader::Serialize(), ns3::dsr::DsrOptionRerrUnsupportHeader::Serialize(), ns3::dsr::DsrOptionAckReqHeader::Serialize(), and ns3::dsr::DsrOptionAckHeader::Serialize().
GetTypeId()
TypeId ns3::dsr::DsrOptionHeader::GetTypeId (void) static
Get the type identificator.
Returns
type identificator
Definition at line 49 of file dsr-option-header.cc.
References ns3::TypeId::AddConstructor().
Referenced by GetInstanceTypeId().
Print()
void ns3::dsr::DsrOptionHeader::Print (std::ostream & os) const virtual
Print some information about the packet.
Parameters
os output stream
Returns
info about this packet
Implements ns3::Header.
Reimplemented in ns3::dsr::DsrOptionAckHeader, ns3::dsr::DsrOptionAckReqHeader, ns3::dsr::DsrOptionRerrUnsupportHeader, ns3::dsr::DsrOptionRerrUnreachHeader, ns3::dsr::DsrOptionRerrHeader, ns3::dsr::DsrOptionSRHeader, ns3::dsr::DsrOptionRrepHeader, ns3::dsr::DsrOptionRreqHeader, ns3::dsr::DsrOptionPadnHeader, and ns3::dsr::DsrOptionPad1Header.
Definition at line 94 of file dsr-option-header.cc.
References m_length, and m_type.
Serialize()
void ns3::dsr::DsrOptionHeader::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start Buffer iterator
Implements ns3::Header.
Reimplemented in ns3::dsr::DsrOptionAckHeader, ns3::dsr::DsrOptionAckReqHeader, ns3::dsr::DsrOptionRerrUnsupportHeader, ns3::dsr::DsrOptionRerrUnreachHeader, ns3::dsr::DsrOptionRerrHeader, ns3::dsr::DsrOptionSRHeader, ns3::dsr::DsrOptionRrepHeader, ns3::dsr::DsrOptionRreqHeader, ns3::dsr::DsrOptionPadnHeader, and ns3::dsr::DsrOptionPad1Header.
Definition at line 104 of file dsr-option-header.cc.
References ns3::Buffer::Begin(), ns3::Buffer::End(), m_data, m_length, m_type, visualizer.core::start(), ns3::Buffer::Iterator::Write(), and ns3::Buffer::Iterator::WriteU8().
Referenced by ns3::dsr::DsrOptionField::AddDsrOption().
SetLength()
void ns3::dsr::DsrOptionHeader::SetLength (uint8_t length)
Set the option length.
Parameters
length the option length
Definition at line 84 of file dsr-option-header.cc.
References m_length.
Referenced by ns3::dsr::DsrOptionAckHeader::DsrOptionAckHeader(), ns3::dsr::DsrOptionAckReqHeader::DsrOptionAckReqHeader(), ns3::dsr::DsrOptionPadnHeader::DsrOptionPadnHeader(), ns3::dsr::DsrOptionRerrHeader::DsrOptionRerrHeader(), ns3::dsr::DsrOptionRerrUnreachHeader::DsrOptionRerrUnreachHeader(), ns3::dsr::DsrOptionRerrUnsupportHeader::DsrOptionRerrUnsupportHeader(), ns3::dsr::DsrOptionRrepHeader::DsrOptionRrepHeader(), ns3::dsr::DsrOptionRreqHeader::DsrOptionRreqHeader(), ns3::dsr::DsrOptionSRHeader::DsrOptionSRHeader(), ns3::dsr::DsrOptionRreqHeader::AddNodeAddress(), ns3::dsr::DsrOptionPadnHeader::Deserialize(), ns3::dsr::DsrOptionRreqHeader::Deserialize(), ns3::dsr::DsrOptionRrepHeader::Deserialize(), ns3::dsr::DsrOptionSRHeader::Deserialize(), ns3::dsr::DsrOptionRerrHeader::Deserialize(), ns3::dsr::DsrOptionRerrUnreachHeader::Deserialize(), ns3::dsr::DsrOptionRerrUnsupportHeader::Deserialize(), ns3::dsr::DsrOptionAckReqHeader::Deserialize(), ns3::dsr::DsrOptionAckHeader::Deserialize(), ns3::dsr::DsrOptionRreqHeader::SetNodesAddress(), ns3::dsr::DsrOptionRrepHeader::SetNodesAddress(), and ns3::dsr::DsrOptionSRHeader::SetNodesAddress().
SetType()
void ns3::dsr::DsrOptionHeader::SetType (uint8_t type)
Set the type of the option.
Parameters
type the type of the option
Definition at line 74 of file dsr-option-header.cc.
References m_type.
Referenced by ns3::dsr::DsrOptionAckHeader::DsrOptionAckHeader(), ns3::dsr::DsrOptionAckReqHeader::DsrOptionAckReqHeader(), ns3::dsr::DsrOptionPad1Header::DsrOptionPad1Header(), ns3::dsr::DsrOptionPadnHeader::DsrOptionPadnHeader(), ns3::dsr::DsrOptionRerrHeader::DsrOptionRerrHeader(), ns3::dsr::DsrOptionRerrUnreachHeader::DsrOptionRerrUnreachHeader(), ns3::dsr::DsrOptionRerrUnsupportHeader::DsrOptionRerrUnsupportHeader(), ns3::dsr::DsrOptionRrepHeader::DsrOptionRrepHeader(), ns3::dsr::DsrOptionRreqHeader::DsrOptionRreqHeader(), ns3::dsr::DsrOptionSRHeader::DsrOptionSRHeader(), ns3::dsr::DsrOptionPad1Header::Deserialize(), ns3::dsr::DsrOptionPadnHeader::Deserialize(), ns3::dsr::DsrOptionRreqHeader::Deserialize(), ns3::dsr::DsrOptionRrepHeader::Deserialize(), ns3::dsr::DsrOptionSRHeader::Deserialize(), ns3::dsr::DsrOptionRerrHeader::Deserialize(), ns3::dsr::DsrOptionRerrUnreachHeader::Deserialize(), ns3::dsr::DsrOptionRerrUnsupportHeader::Deserialize(), ns3::dsr::DsrOptionAckReqHeader::Deserialize(), and ns3::dsr::DsrOptionAckHeader::Deserialize().
Member Data Documentation
m_data
Buffer ns3::dsr::DsrOptionHeader::m_data private
The anonymous data of this option.
Definition at line 143 of file dsr-option-header.h.
Referenced by Deserialize(), and Serialize().
m_length
uint8_t ns3::dsr::DsrOptionHeader::m_length private
The option length.
Definition at line 139 of file dsr-option-header.h.
Referenced by Deserialize(), GetLength(), GetSerializedSize(), Print(), Serialize(), and SetLength().
m_type
uint8_t ns3::dsr::DsrOptionHeader::m_type private
The type of the option.
Definition at line 135 of file dsr-option-header.h.
Referenced by Deserialize(), GetType(), Print(), Serialize(), and SetType().
The documentation for this class was generated from the following files:
src/dsr/model/dsr-option-header.h
src/dsr/model/dsr-option-header.cc