ns-3: ns3::LrWpanNetDevice Class Reference
ns3::LrWpanNetDevice Class Reference
LR-WPAN models
Network layer to device interface.
#include "lr-wpan-net-device.h"
Public Types
enum PseudoMacAddressMode_e { RFC4944 , RFC6282 }
How the pseudo-MAC address is built from the short address (XXXX) and the PanId (YYYY).
Public Types inherited from ns3::NetDevice
typedef void(* LinkChangeTracedCallback) (void)
TracedCallback signature for link changed event.
enum PacketType {
PACKET_HOST = 1 , NS3_PACKET_HOST = PACKET_HOST , PACKET_BROADCAST , NS3_PACKET_BROADCAST = PACKET_BROADCAST ,
PACKET_MULTICAST , NS3_PACKET_MULTICAST = PACKET_MULTICAST , PACKET_OTHERHOST , NS3_PACKET_OTHERHOST = PACKET_OTHERHOST
}
Packet types are used as they are in Linux.
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address &, const Address &, enum PacketType > PromiscReceiveCallback
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address & > ReceiveCallback
Public Member Functions
LrWpanNetDevice (void)
virtual ~LrWpanNetDevice (void)
virtual void AddLinkChangeCallback (Callback< void > callback)
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
virtual Address GetAddress (void) const
This method indirects to LrWpanMac::SetShortAddress ()
virtual Address GetBroadcast (void) const
virtual Ptr< Channel > GetChannel (void) const
Ptr< LrWpanCsmaCa > GetCsmaCa (void) const
Get the CSMA/CA implementation used by this NetDevice.
virtual uint32_t GetIfIndex (void) const
Ptr< LrWpanMac > GetMac (void) const
Get the MAC used by this NetDevice.
virtual uint16_t GetMtu (void) const
virtual Address GetMulticast (Ipv4Address multicastGroup) const
Make and return a MAC multicast address using the provided multicast group.
virtual Address GetMulticast (Ipv6Address addr) const
Get the MAC multicast address corresponding to the IPv6 address provided.
virtual Ptr< Node > GetNode (void) const
Ptr< LrWpanPhy > GetPhy (void) const
Get the PHY used by this NetDevice.
virtual bool IsBridge (void) const
Return true if the net device is acting as a bridge.
virtual bool IsBroadcast (void) const
virtual bool IsLinkUp (void) const
virtual bool IsMulticast (void) const
virtual bool IsPointToPoint (void) const
Return true if the net device is on a point-to-point link.
void McpsDataIndication (McpsDataIndicationParams params, Ptr< Packet > pkt)
The callback used by the MAC to hand over incoming packets to the NetDevice.
virtual bool NeedsArp (void) const
virtual bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)
virtual bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
virtual void SetAddress (Address address)
This method indirects to LrWpanMac::SetShortAddress ()
void SetChannel (Ptr< SpectrumChannel > channel)
Set the channel to which the NetDevice, and therefore the PHY, should be attached to.
void SetCsmaCa (Ptr< LrWpanCsmaCa > csmaca)
Set the CSMA/CA implementation to be used by the MAC and this NetDevice.
virtual void SetIfIndex (const uint32_t index)
void SetMac (Ptr< LrWpanMac > mac)
Set the MAC to be used by this NetDevice.
virtual bool SetMtu (const uint16_t mtu)
virtual void SetNode (Ptr< Node > node)
void SetPhy (Ptr< LrWpanPhy > phy)
Set the PHY to be used by the MAC and this NetDevice.
virtual void SetPromiscReceiveCallback (PromiscReceiveCallback cb)
virtual void SetReceiveCallback (NetDevice::ReceiveCallback cb)
virtual bool SupportsSendFrom (void) const
Public Member Functions inherited from ns3::NetDevice
virtual ~NetDevice ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::NetDevice
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
Mac48Address BuildPseudoMacAddress (uint16_t panId, Mac16Address shortAddr) const
Builds a "pseudo 48-bit address" from the PanId and Short Address The form is PanId : 0x0 : 0x0 : ShortAddress.
void CompleteConfig (void)
Configure PHY, MAC and CSMA/CA.
virtual void DoDispose (void)
Destructor implementation.
Ptr< SpectrumChannel > DoGetChannel (void) const
Attribute accessor method for the "Channel" attribute.
virtual void DoInitialize (void)
Initialize() implementation.
void LinkDown (void)
Mark NetDevice link as down.
void LinkUp (void)
Mark NetDevice link as up.
Private Attributes
bool m_configComplete
True if MAC, PHY and CSMA/CA where successfully configured and the NetDevice is ready for being used.
Ptr< LrWpanCsmaCa > m_csmaca
The CSMA/CA implementation for this NetDevice.
uint32_t m_ifIndex
The interface index of this NetDevice.
TracedCallback m_linkChanges
Trace source for link up/down changes.
bool m_linkUp
Is the link/device currently up and running?
Ptr< LrWpanMac > m_mac
The MAC for this NetDevice.
Ptr< Node > m_node
The node associated with this NetDevice.
Ptr< LrWpanPhy > m_phy
The PHY for this NetDevice.
PseudoMacAddressMode_e m_pseudoMacMode
How the pseudo MAC address is created.
ReceiveCallback m_receiveCallback
Upper layer callback used for notification of new data packet arrivals.
bool m_useAcks
Configure the NetDevice to request MAC layer acknowledgments when sending packets using the Send() API.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Network layer to device interface.
The ns3::NetDevice includes IP-specific API such as GetMulticast(), Send() and SendTo() methods, which do not map well the the 802.15.4 MAC MCPS DataRequest primitive. So, the basic design is to provide, as much as makes sense, the class ns3::NetDevice API, but rely on the user accessing the LrWpanMac pointer to make 802.15.4-specific API calls. As such, this is really just an encapsulating class.
Config Paths
ns3::LrWpanNetDevice is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::LrWpanNetDevice"
Attributes
Channel: The channel attached to this device
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::SpectrumChannel>
Flags: read
Phy: The PHY layer attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::LrWpanPhy>
Initial value: 0x0
Flags: construct write read
Mac: The MAC layer attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::LrWpanMac>
Initial value: 0x0
Flags: construct write read
UseAcks: Request acknowledgments for data frames.
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
PseudoMacAddressMode: Build the pseudo-MAC Address according to RFC 4944 or RFC 6282 (default: RFC 6282).
Set with class: ns3::EnumValue
Underlying type:
Initial value: RFC 6282 (don't use PanId)
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 112 bytes (on a 64-bit architecture).
Definition at line 49 of file lr-wpan-net-device.h.
Member Enumeration Documentation
PseudoMacAddressMode_e
enum ns3::LrWpanNetDevice::PseudoMacAddressMode_e
How the pseudo-MAC address is built from the short address (XXXX) and the PanId (YYYY).
See RFC 4944 and RFC 6282.
Enumerator
RFC4944
YYYY:0000:XXXX (with U/L bit set to local)
RFC6282
0200:0000:XXXX
Definition at line 68 of file lr-wpan-net-device.h.
Constructor & Destructor Documentation
LrWpanNetDevice()
ns3::LrWpanNetDevice::LrWpanNetDevice (void)
Definition at line 77 of file lr-wpan-net-device.cc.
References CompleteConfig(), m_csmaca, m_mac, m_phy, and NS_LOG_FUNCTION.
~LrWpanNetDevice()
ns3::LrWpanNetDevice::~LrWpanNetDevice (void) virtual
Definition at line 87 of file lr-wpan-net-device.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddLinkChangeCallback()
void ns3::LrWpanNetDevice::AddLinkChangeCallback (Callback< void > callback) virtual
Parameters
callback the callback to invoke
Add a callback invoked whenever the link status changes to UP. This callback is typically used by the IP/ARP layer to flush the ARP cache and by IPv6 stack to flush NDISC cache whenever the link goes up.
Implements ns3::NetDevice.
Definition at line 324 of file lr-wpan-net-device.cc.
References ns3::TracedCallback< Ts >::ConnectWithoutContext(), m_linkChanges, and NS_LOG_FUNCTION.
AssignStreams()
int64_t ns3::LrWpanNetDevice::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 531 of file lr-wpan-net-device.cc.
References m_csmaca, m_phy, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by ns3::LrWpanHelper::AssignStreams(), LrWpanAckTestCase::DoRun(), LrWpanCcaTestCase::DoRun(), LrWpanEdTestCase::DoRun(), and LrWpanErrorDistanceTestCase::DoRun().
BuildPseudoMacAddress()
Mac48Address ns3::LrWpanNetDevice::BuildPseudoMacAddress (uint16_t panId, Mac16Address shortAddr) const private
Builds a "pseudo 48-bit address" from the PanId and Short Address The form is PanId : 0x0 : 0x0 : ShortAddress.
The address follows RFC 4944, section 6, and it is used to build an Interface ID.
The Interface ID should have its U/L bit is set to zero, to indicate that this interface ID is not globally unique. However, the U/L bit flipping is performed when the IPv6 address is created.
As a consequence, here we set it to 1.
Parameters
panId The PanID
shortMac The Short MAC address
Returns
a Pseudo-Mac48Adress
Definition at line 501 of file lr-wpan-net-device.cc.
References ns3::Mac48Address::CopyFrom(), ns3::Mac16Address::CopyTo(), m_pseudoMacMode, NS_LOG_FUNCTION, and RFC4944.
Referenced by GetAddress(), GetBroadcast(), GetMulticast(), and McpsDataIndication().
CompleteConfig()
void ns3::LrWpanNetDevice::CompleteConfig (void) private
Configure PHY, MAC and CSMA/CA.
Definition at line 120 of file lr-wpan-net-device.cc.
References ns3::Object::GetObject(), m_configComplete, m_csmaca, m_mac, m_node, m_phy, ns3::MakeCallback(), McpsDataIndication(), third::mobility, NS_LOG_FUNCTION, NS_LOG_WARN, ns3::LrWpanMac::PdDataConfirm(), ns3::LrWpanMac::PdDataIndication(), ns3::LrWpanCsmaCa::PlmeCcaConfirm(), ns3::LrWpanMac::PlmeEdConfirm(), ns3::LrWpanMac::PlmeGetAttributeConfirm(), ns3::LrWpanMac::PlmeSetAttributeConfirm(), ns3::LrWpanMac::PlmeSetTRXStateConfirm(), and ns3::LrWpanMac::SetLrWpanMacState().
Referenced by LrWpanNetDevice(), SetChannel(), SetCsmaCa(), SetMac(), SetNode(), and SetPhy().
DoDispose()
void ns3::LrWpanNetDevice::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 94 of file lr-wpan-net-device.cc.
References ns3::Object::DoDispose(), m_csmaca, m_mac, m_node, m_phy, and NS_LOG_FUNCTION.
DoGetChannel()
Ptr< SpectrumChannel > ns3::LrWpanNetDevice::DoGetChannel (void) const private
Attribute accessor method for the "Channel" attribute.
Returns
the channel to which this NetDevice is attached
Definition at line 249 of file lr-wpan-net-device.cc.
References m_phy, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
DoInitialize()
void ns3::LrWpanNetDevice::DoInitialize (void) private virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 110 of file lr-wpan-net-device.cc.
References ns3::Object::DoInitialize(), m_mac, m_phy, and NS_LOG_FUNCTION.
GetAddress()
Address ns3::LrWpanNetDevice::GetAddress (void) const virtual
This method indirects to LrWpanMac::SetShortAddress ()
Returns
The short address.
Implements ns3::NetDevice.
Definition at line 284 of file lr-wpan-net-device.cc.
References BuildPseudoMacAddress(), m_mac, and NS_LOG_FUNCTION.
GetBroadcast()
Address ns3::LrWpanNetDevice::GetBroadcast (void) const virtual
Returns
the broadcast address supported by this netdevice.
Calling this method is invalid if IsBroadcast returns not true.
Implements ns3::NetDevice.
Definition at line 338 of file lr-wpan-net-device.cc.
References BuildPseudoMacAddress(), ns3::Mac16Address::GetBroadcast(), m_mac, and NS_LOG_FUNCTION.
GetChannel()
Ptr< Channel > ns3::LrWpanNetDevice::GetChannel (void) const virtual
Returns
the channel this NetDevice is connected to. The value returned can be zero if the NetDevice is not yet connected to any channel or if the underlying NetDevice has no concept of a channel. i.e., callers must check for zero and be ready to handle it.
Implements ns3::NetDevice.
Definition at line 226 of file lr-wpan-net-device.cc.
References m_phy, and NS_LOG_FUNCTION.
GetCsmaCa()
Ptr< LrWpanCsmaCa > ns3::LrWpanNetDevice::GetCsmaCa (void) const
Get the CSMA/CA implementation used by this NetDevice.
Returns
the CSMA/CA implementation object
Definition at line 206 of file lr-wpan-net-device.cc.
References m_csmaca, and NS_LOG_FUNCTION.
Referenced by LrWpanCcaTestCase::DoRun(), LrWpanCollisionTestCase::DoRun(), and LrWpanSlottedCsmacaTestCase::DoRun().
GetIfIndex()
uint32_t ns3::LrWpanNetDevice::GetIfIndex (void) const virtual
Returns
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 219 of file lr-wpan-net-device.cc.
References m_ifIndex, and NS_LOG_FUNCTION.
GetMac()
Ptr< LrWpanMac > ns3::LrWpanNetDevice::GetMac (void) const
Get the MAC used by this NetDevice.
Returns
the MAC object
Definition at line 192 of file lr-wpan-net-device.cc.
References m_mac.
Referenced by ns3::LrWpanHelper::AssociateToBeaconPan(), ns3::LrWpanHelper::AssociateToPan(), LrWpanAckTestCase::DataIndicationDev1(), LrWpanAckTestCase::DoRun(), LrWpanCcaTestCase::DoRun(), LrWpanCollisionTestCase::DoRun(), LrWpanEdTestCase::DoRun(), LrWpanErrorDistanceTestCase::DoRun(), LrWpanDataIfsTestCase::DoRun(), LrWpanSlottedCsmacaTestCase::DoRun(), ns3::LrWpanHelper::EnableAsciiInternal(), ns3::LrWpanHelper::EnablePcapInternal(), GetTypeId(), ns3::AnimationInterface::LrWpanPhyTxBeginTrace(), LrWpanCcaTestCase::PhyRxBegin(), LrWpanCcaTestCase::PhyRxDrop(), LrWpanCcaTestCase::PhyRxEnd(), LrWpanCcaTestCase::PhyTxBegin(), LrWpanCcaTestCase::PhyTxEnd(), and LrWpanCcaTestCase::PlmeCcaConfirm().
GetMtu()
uint16_t ns3::LrWpanNetDevice::GetMtu (void) const virtual
Returns
the link-level MTU in bytes for this interface.
This value is typically used by the IP layer to perform IP fragmentation when needed.
Implements ns3::NetDevice.
Definition at line 306 of file lr-wpan-net-device.cc.
References NS_LOG_FUNCTION.
Referenced by Send().
GetMulticast() [1/2]
Address ns3::LrWpanNetDevice::GetMulticast (Ipv4Address multicastGroup) const virtual
Make and return a MAC multicast address using the provided multicast group.
RFC 1112 says that an Ipv4 host group address is mapped to an Ethernet multicast address by placing the low-order 23-bits of the IP address into the low-order 23 bits of the Ethernet multicast address 01-00-5E-00-00-00 (hex). Similar RFCs exist for Ipv6 and Eui64 mappings. This method performs the multicast address creation function appropriate to the underlying MAC address of the device. This MAC address is encapsulated in an abstract Address to avoid dependencies on the exact MAC address format.
In the case of net devices that do not support multicast, clients are expected to test NetDevice::IsMulticast and avoid attempting to map multicast packets. Subclasses of NetDevice that do support multicasting are expected to override this method and provide an implementation appropriate to the particular device.
Parameters
multicastGroup The IP address for the multicast group destination of the packet.
Returns
The MAC multicast Address used to send packets to the provided multicast group.
Warning
Calling this method is invalid if IsMulticast returns not true.
See also
IsMulticast()
Implements ns3::NetDevice.
Definition at line 355 of file lr-wpan-net-device.cc.
References NS_ABORT_MSG.
GetMulticast() [2/2]
Address ns3::LrWpanNetDevice::GetMulticast (Ipv6Address addr) const virtual
Get the MAC multicast address corresponding to the IPv6 address provided.
Parameters
addr IPv6 address
Returns
the MAC multicast address
Warning
Calling this method is invalid if IsMulticast returns not true.
Implements ns3::NetDevice.
Definition at line 362 of file lr-wpan-net-device.cc.
References BuildPseudoMacAddress(), ns3::Mac16Address::GetMulticast(), m_mac, and NS_LOG_FUNCTION.
GetNode()
Ptr< Node > ns3::LrWpanNetDevice::GetNode (void) const virtual
Returns
the node base class which contains this network interface.
When a subclass needs to get access to the underlying node base class to print the nodeid for example, it can invoke this method.
Implements ns3::NetDevice.
Definition at line 438 of file lr-wpan-net-device.cc.
References m_node, and NS_LOG_FUNCTION.
GetPhy()
Ptr< LrWpanPhy > ns3::LrWpanNetDevice::GetPhy (void) const
Get the PHY used by this NetDevice.
Returns
the PHY object
Definition at line 199 of file lr-wpan-net-device.cc.
References m_phy, and NS_LOG_FUNCTION.
Referenced by LrWpanAckTestCase::DoRun(), LrWpanCcaTestCase::DoRun(), LrWpanCollisionTestCase::DoRun(), LrWpanEdTestCase::DoRun(), LrWpanErrorDistanceTestCase::DoRun(), LrWpanDataIfsTestCase::DoRun(), LrWpanSlottedCsmacaTestCase::DoRun(), GetTypeId(), and LrWpanCcaTestCase::PhyRxEnd().
GetTypeId()
TypeId ns3::LrWpanNetDevice::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 44 of file lr-wpan-net-device.cc.
References DoGetChannel(), GetMac(), GetPhy(), m_pseudoMacMode, m_useAcks, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeEnumAccessor(), ns3::MakeEnumChecker(), ns3::MakePointerAccessor(), RFC4944, RFC6282, SetMac(), ns3::TypeId::SetParent(), and SetPhy().
IsBridge()
bool ns3::LrWpanNetDevice::IsBridge (void) const virtual
Return true if the net device is acting as a bridge.
Returns
value of m_isBridge flag
Implements ns3::NetDevice.
Definition at line 372 of file lr-wpan-net-device.cc.
References NS_LOG_FUNCTION.
IsBroadcast()
bool ns3::LrWpanNetDevice::IsBroadcast (void) const virtual
Returns
true if this interface supports a broadcast address, false otherwise.
Implements ns3::NetDevice.
Definition at line 331 of file lr-wpan-net-device.cc.
References NS_LOG_FUNCTION.
IsLinkUp()
bool ns3::LrWpanNetDevice::IsLinkUp (void) const virtual
Returns
true if link is up; false otherwise
Implements ns3::NetDevice.
Definition at line 317 of file lr-wpan-net-device.cc.
References m_linkUp, m_phy, and NS_LOG_FUNCTION.
IsMulticast()
bool ns3::LrWpanNetDevice::IsMulticast (void) const virtual
Returns
value of m_isMulticast flag
Implements ns3::NetDevice.
Definition at line 348 of file lr-wpan-net-device.cc.
References NS_LOG_FUNCTION.
IsPointToPoint()
bool ns3::LrWpanNetDevice::IsPointToPoint (void) const virtual
Return true if the net device is on a point-to-point link.
Returns
value of m_isPointToPoint flag
Implements ns3::NetDevice.
Definition at line 379 of file lr-wpan-net-device.cc.
References NS_LOG_FUNCTION.
LinkDown()
void ns3::LrWpanNetDevice::LinkDown (void) private
Mark NetDevice link as down.
Definition at line 241 of file lr-wpan-net-device.cc.
References m_linkChanges, m_linkUp, and NS_LOG_FUNCTION.
LinkUp()
void ns3::LrWpanNetDevice::LinkUp (void) private
Mark NetDevice link as up.
Definition at line 233 of file lr-wpan-net-device.cc.
References m_linkChanges, m_linkUp, and NS_LOG_FUNCTION.
McpsDataIndication()
void ns3::LrWpanNetDevice::McpsDataIndication (McpsDataIndicationParams params, Ptr< Packet > pkt)
The callback used by the MAC to hand over incoming packets to the NetDevice.
This callback will in turn use the ReceiveCallback set by SetReceiveCallback() to notify upper layers.
Parameters
params 802.15.4 specific parameters, including source and destination addresses
pkt the packet do be delivered
Definition at line 478 of file lr-wpan-net-device.cc.
References BuildPseudoMacAddress(), ns3::McpsDataIndicationParams::m_dstAddrMode, m_receiveCallback, ns3::McpsDataIndicationParams::m_srcAddr, ns3::McpsDataIndicationParams::m_srcExtAddr, ns3::McpsDataIndicationParams::m_srcPanId, NS_LOG_FUNCTION, and ns3::SHORT_ADDR.
Referenced by CompleteConfig().
NeedsArp()
bool ns3::LrWpanNetDevice::NeedsArp (void) const virtual
Returns
true if ARP is needed, false otherwise.
Called by higher-layers to check if this NetDevice requires ARP to be used.
Implements ns3::NetDevice.
Definition at line 453 of file lr-wpan-net-device.cc.
References NS_LOG_FUNCTION.
Send()
bool ns3::LrWpanNetDevice::Send (Ptr< Packet > packet, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device to the specified destination Address
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 386 of file lr-wpan-net-device.cc.
References ns3::Mac16Address::ConvertFrom(), ns3::Mac16Address::CopyFrom(), ns3::Address::CopyTo(), GetMtu(), ns3::Packet::GetSize(), ns3::Mac48Address::IsMatchingType(), ns3::McpsDataRequestParams::m_dstAddr, ns3::McpsDataRequestParams::m_dstAddrMode, ns3::McpsDataRequestParams::m_dstPanId, m_mac, ns3::McpsDataRequestParams::m_msduHandle, ns3::McpsDataRequestParams::m_srcAddrMode, ns3::McpsDataRequestParams::m_txOptions, m_useAcks, NS_LOG_ERROR, NS_LOG_FUNCTION, ns3::SHORT_ADDR, and ns3::TX_OPTION_ACK.
SendFrom()
bool ns3::LrWpanNetDevice::SendFrom (Ptr< Packet > packet, const Address & source, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
source source mac address (so called "MAC spoofing")
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device with the specified source and destination Addresses.
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 430 of file lr-wpan-net-device.cc.
References NS_ABORT_MSG.
SetAddress()
void ns3::LrWpanNetDevice::SetAddress (Address address) virtual
This method indirects to LrWpanMac::SetShortAddress ()
Parameters
address The short address.
Implements ns3::NetDevice.
Definition at line 256 of file lr-wpan-net-device.cc.
References first::address, ns3::Mac16Address::ConvertFrom(), ns3::Mac48Address::ConvertFrom(), ns3::Mac16Address::CopyFrom(), ns3::Mac48Address::CopyTo(), ns3::Mac16Address::IsMatchingType(), ns3::Mac48Address::IsMatchingType(), m_mac, NS_ABORT_MSG, and NS_LOG_FUNCTION.
Referenced by LrWpanAckTestCase::DoRun(), LrWpanCcaTestCase::DoRun(), LrWpanCollisionTestCase::DoRun(), LrWpanEdTestCase::DoRun(), LrWpanErrorDistanceTestCase::DoRun(), LrWpanDataIfsTestCase::DoRun(), and LrWpanSlottedCsmacaTestCase::DoRun().
SetChannel()
void ns3::LrWpanNetDevice::SetChannel (Ptr< SpectrumChannel > channel)
Set the channel to which the NetDevice, and therefore the PHY, should be attached to.
Parameters
channel the channel to be used
Definition at line 183 of file lr-wpan-net-device.cc.
References third::channel, CompleteConfig(), m_phy, and NS_LOG_FUNCTION.
Referenced by LrWpanAckTestCase::DoRun(), LrWpanCcaTestCase::DoRun(), LrWpanCollisionTestCase::DoRun(), LrWpanEdTestCase::DoRun(), LrWpanErrorDistanceTestCase::DoRun(), LrWpanDataIfsTestCase::DoRun(), LrWpanSlottedCsmacaTestCase::DoRun(), and ns3::LrWpanHelper::Install().
SetCsmaCa()
void ns3::LrWpanNetDevice::SetCsmaCa (Ptr< LrWpanCsmaCa > csmaca)
Set the CSMA/CA implementation to be used by the MAC and this NetDevice.
Parameters
csmaca the CSMA/CA implementation to be used
Definition at line 175 of file lr-wpan-net-device.cc.
References CompleteConfig(), m_csmaca, and NS_LOG_FUNCTION.
SetIfIndex()
void ns3::LrWpanNetDevice::SetIfIndex (const uint32_t index) virtual
Parameters
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 212 of file lr-wpan-net-device.cc.
References m_ifIndex, and NS_LOG_FUNCTION.
SetMac()
void ns3::LrWpanNetDevice::SetMac (Ptr< LrWpanMac > mac)
Set the MAC to be used by this NetDevice.
Parameters
mac the MAC to be used
Definition at line 159 of file lr-wpan-net-device.cc.
References CompleteConfig(), m_mac, third::mac, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetMtu()
bool ns3::LrWpanNetDevice::SetMtu (const uint16_t mtu) virtual
Parameters
mtu MTU value, in bytes, to set for the device
Returns
whether the MTU value was within legal bounds
Override for default MTU defined on a per-type basis.
Implements ns3::NetDevice.
Definition at line 299 of file lr-wpan-net-device.cc.
References NS_ABORT_MSG.
SetNode()
void ns3::LrWpanNetDevice::SetNode (Ptr< Node > node) virtual
Parameters
node the node associated to this netdevice.
This method is called from ns3::Node::AddDevice.
Implements ns3::NetDevice.
Definition at line 445 of file lr-wpan-net-device.cc.
References CompleteConfig(), m_node, and NS_LOG_FUNCTION.
Referenced by ns3::LrWpanHelper::Install().
SetPhy()
void ns3::LrWpanNetDevice::SetPhy (Ptr< LrWpanPhy > phy)
Set the PHY to be used by the MAC and this NetDevice.
Parameters
phy the PHY to be used
Definition at line 167 of file lr-wpan-net-device.cc.
References CompleteConfig(), m_phy, NS_LOG_FUNCTION, and third::phy.
Referenced by GetTypeId().
SetPromiscReceiveCallback()
void ns3::LrWpanNetDevice::SetPromiscReceiveCallback (PromiscReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received in promiscuous mode and must be forwarded to the higher layers.
Enables netdevice promiscuous mode and sets the callback that will handle promiscuous mode packets. Note, promiscuous mode packets means all packets, including those packets that can be sensed by the netdevice but which are intended to be received by other hosts.
Implements ns3::NetDevice.
Definition at line 467 of file lr-wpan-net-device.cc.
References NS_LOG_WARN.
SetReceiveCallback()
void ns3::LrWpanNetDevice::SetReceiveCallback (NetDevice::ReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received and must be forwarded to the higher layers.
Set the callback to be used to notify higher layers when a packet has been received.
Implements ns3::NetDevice.
Definition at line 460 of file lr-wpan-net-device.cc.
References m_receiveCallback, and NS_LOG_FUNCTION.
SupportsSendFrom()
bool ns3::LrWpanNetDevice::SupportsSendFrom (void) const virtual
Returns
true if this interface supports a bridging mode, false otherwise.
Implements ns3::NetDevice.
Definition at line 494 of file lr-wpan-net-device.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Data Documentation
m_configComplete
bool ns3::LrWpanNetDevice::m_configComplete private
True if MAC, PHY and CSMA/CA where successfully configured and the NetDevice is ready for being used.
Definition at line 247 of file lr-wpan-net-device.h.
Referenced by CompleteConfig().
m_csmaca
Ptr<LrWpanCsmaCa> ns3::LrWpanNetDevice::m_csmaca private
The CSMA/CA implementation for this NetDevice.
Definition at line 236 of file lr-wpan-net-device.h.
Referenced by LrWpanNetDevice(), AssignStreams(), CompleteConfig(), DoDispose(), GetCsmaCa(), and SetCsmaCa().
m_ifIndex
uint32_t ns3::LrWpanNetDevice::m_ifIndex private
The interface index of this NetDevice.
Definition at line 263 of file lr-wpan-net-device.h.
Referenced by GetIfIndex(), and SetIfIndex().
m_linkChanges
TracedCallback ns3::LrWpanNetDevice::m_linkChanges private
Trace source for link up/down changes.
Definition at line 268 of file lr-wpan-net-device.h.
Referenced by AddLinkChangeCallback(), LinkDown(), and LinkUp().
m_linkUp
bool ns3::LrWpanNetDevice::m_linkUp private
Is the link/device currently up and running?
Definition at line 258 of file lr-wpan-net-device.h.
Referenced by IsLinkUp(), LinkDown(), and LinkUp().
m_mac
Ptr<LrWpanMac> ns3::LrWpanNetDevice::m_mac private
The MAC for this NetDevice.
Definition at line 226 of file lr-wpan-net-device.h.
Referenced by LrWpanNetDevice(), CompleteConfig(), DoDispose(), DoInitialize(), GetAddress(), GetBroadcast(), GetMac(), GetMulticast(), Send(), SetAddress(), and SetMac().
m_node
Ptr<Node> ns3::LrWpanNetDevice::m_node private
The node associated with this NetDevice.
Definition at line 241 of file lr-wpan-net-device.h.
Referenced by CompleteConfig(), DoDispose(), GetNode(), and SetNode().
m_phy
Ptr<LrWpanPhy> ns3::LrWpanNetDevice::m_phy private
The PHY for this NetDevice.
Definition at line 231 of file lr-wpan-net-device.h.
Referenced by LrWpanNetDevice(), AssignStreams(), CompleteConfig(), DoDispose(), DoGetChannel(), DoInitialize(), GetChannel(), GetPhy(), IsLinkUp(), SetChannel(), and SetPhy().
m_pseudoMacMode
PseudoMacAddressMode_e ns3::LrWpanNetDevice::m_pseudoMacMode private
How the pseudo MAC address is created.
According to RFC 4944 the psudo-MAC is YYYY:0000:XXXX (with U/L bit set to local) According to RFC 6282 the psudo-MAC is 0200:0000:XXXX
Definition at line 281 of file lr-wpan-net-device.h.
Referenced by BuildPseudoMacAddress(), and GetTypeId().
m_receiveCallback
ReceiveCallback ns3::LrWpanNetDevice::m_receiveCallback private
Upper layer callback used for notification of new data packet arrivals.
Definition at line 273 of file lr-wpan-net-device.h.
Referenced by McpsDataIndication(), and SetReceiveCallback().
m_useAcks
bool ns3::LrWpanNetDevice::m_useAcks private
Configure the NetDevice to request MAC layer acknowledgments when sending packets using the Send() API.
Definition at line 253 of file lr-wpan-net-device.h.
Referenced by GetTypeId(), and Send().
The documentation for this class was generated from the following files:
src/lr-wpan/model/lr-wpan-net-device.h
src/lr-wpan/model/lr-wpan-net-device.cc