ns-3: ns3::SimpleOfdmWimaxChannel Class Reference
ns3::SimpleOfdmWimaxChannel Class Reference
WiMAX Models
SimpleOfdmWimaxChannel class.
#include "simple-ofdm-wimax-channel.h"
Public Types
enum PropModel { RANDOM_PROPAGATION , FRIIS_PROPAGATION , LOG_DISTANCE_PROPAGATION , COST231_PROPAGATION }
PropModel enumeration.
Public Member Functions
SimpleOfdmWimaxChannel (PropModel propModel)
Creates a channel and sets the propagation model.
SimpleOfdmWimaxChannel (void)
~SimpleOfdmWimaxChannel (void)
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
void Send (Time BlockTime, uint32_t burstSize, Ptr< WimaxPhy > phy, bool isFirstBlock, bool isLastBlock, uint64_t frequency, WimaxPhy::ModulationType modulationType, uint8_t direction, double txPowerDbm, Ptr< PacketBurst > burst)
Sends a dummy fec block to all connected physical devices.
void SetPropagationModel (PropModel propModel)
sets the propagation model
Public Member Functions inherited from ns3::WimaxChannel
WimaxChannel (void)
virtual ~WimaxChannel (void)
void Attach (Ptr< WimaxPhy > phy)
attach the channel to a physical layer of a device
Ptr< NetDevice > GetDevice (std::size_t i) const
std::size_t GetNDevices (void) const
Public Member Functions inherited from ns3::Channel
Channel ()
virtual ~Channel ()
uint32_t GetId (void) const
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::WimaxChannel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Channel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void DoAttach (Ptr< WimaxPhy > phy)
Attach functiion.
Ptr< NetDevice > DoGetDevice (std::size_t i) const
Get device function.
std::size_t DoGetNDevices (void) const
Get number of devices function.
void EndSendDummyBlock (Ptr< SimpleOfdmWimaxPhy > rxphy, simpleOfdmSendParam *param)
End send dummy block function.
Private Attributes
Ptr< PropagationLossModel > m_loss
loss
std::list< Ptr< SimpleOfdmWimaxPhy > > m_phyList
phy list
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
SimpleOfdmWimaxChannel class.
Definition at line 42 of file simple-ofdm-wimax-channel.h.
Member Enumeration Documentation
PropModel
enum ns3::SimpleOfdmWimaxChannel::PropModel
PropModel enumeration.
Enumerator
RANDOM_PROPAGATION
FRIIS_PROPAGATION
LOG_DISTANCE_PROPAGATION
COST231_PROPAGATION
Definition at line 49 of file simple-ofdm-wimax-channel.h.
Constructor & Destructor Documentation
SimpleOfdmWimaxChannel() [1/2]
ns3::SimpleOfdmWimaxChannel::SimpleOfdmWimaxChannel (void)
Definition at line 43 of file simple-ofdm-wimax-channel.cc.
References m_loss.
~SimpleOfdmWimaxChannel()
ns3::SimpleOfdmWimaxChannel::~SimpleOfdmWimaxChannel (void)
Definition at line 48 of file simple-ofdm-wimax-channel.cc.
References m_phyList.
SimpleOfdmWimaxChannel() [2/2]
ns3::SimpleOfdmWimaxChannel::SimpleOfdmWimaxChannel (PropModel propModel)
Creates a channel and sets the propagation model.
Parameters
propModel the propagation model to use
Definition at line 65 of file simple-ofdm-wimax-channel.cc.
References COST231_PROPAGATION, FRIIS_PROPAGATION, LOG_DISTANCE_PROPAGATION, m_loss, and RANDOM_PROPAGATION.
Member Function Documentation
AssignStreams()
int64_t ns3::SimpleOfdmWimaxChannel::AssignStreams (int64_t stream) virtual
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Implements ns3::WimaxChannel.
Definition at line 220 of file simple-ofdm-wimax-channel.cc.
References m_phyList.
DoAttach()
void ns3::SimpleOfdmWimaxChannel::DoAttach (Ptr< WimaxPhy > phy) private virtual
Attach functiion.
Parameters
phy the phy layer
Implements ns3::WimaxChannel.
Definition at line 118 of file simple-ofdm-wimax-channel.cc.
References m_phyList, and third::phy.
DoGetDevice()
Ptr< NetDevice > ns3::SimpleOfdmWimaxChannel::DoGetDevice (std::size_t i) const private virtual
Get device function.
Parameters
i the device index
Returns
the device
Implements ns3::WimaxChannel.
Definition at line 131 of file simple-ofdm-wimax-channel.cc.
References list, m_phyList, and NS_FATAL_ERROR.
DoGetNDevices()
std::size_t ns3::SimpleOfdmWimaxChannel::DoGetNDevices (void) const private virtual
Get number of devices function.
Returns
the number of devices
Implements ns3::WimaxChannel.
Definition at line 125 of file simple-ofdm-wimax-channel.cc.
References m_phyList.
EndSendDummyBlock()
void ns3::SimpleOfdmWimaxChannel::EndSendDummyBlock (Ptr< SimpleOfdmWimaxPhy > rxphy, simpleOfdmSendParam * param) private
End send dummy block function.
Parameters
rxphy the Ptr<SimpleOfdmWimaxPhy>
param the simpleOfdmSendParam *
Definition at line 207 of file simple-ofdm-wimax-channel.cc.
References ns3::simpleOfdmSendParam::GetBurst(), ns3::simpleOfdmSendParam::GetBurstSize(), ns3::simpleOfdmSendParam::GetDirection(), ns3::simpleOfdmSendParam::GetFrequency(), ns3::simpleOfdmSendParam::GetIsFirstBlock(), ns3::simpleOfdmSendParam::GetModulationType(), and ns3::simpleOfdmSendParam::GetRxPowerDbm().
Referenced by Send().
GetTypeId()
TypeId ns3::SimpleOfdmWimaxChannel::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 55 of file simple-ofdm-wimax-channel.cc.
References ns3::TypeId::SetParent().
Send()
void ns3::SimpleOfdmWimaxChannel::Send (Time BlockTime, uint32_t burstSize, Ptr< WimaxPhy > phy, bool isFirstBlock, bool isLastBlock, uint64_t frequency, WimaxPhy::ModulationType modulationType, uint8_t direction, double txPowerDbm, Ptr< PacketBurst > burst)
Sends a dummy fec block to all connected physical devices.
Parameters
BlockTime the time needed to send the block
burstSize the size of the burst
phy the sender device
isFirstBlock true if this block is the first one, false otherwise
isLastBlock true if this block is the last one, false otherwise
frequency the frequency on which the block is sent
modulationType the modulation used to send the fec block
direction uplink or downlink
txPowerDbm the transmission power
burst the packet burst to send
Definition at line 148 of file simple-ofdm-wimax-channel.cc.
References ns3::PropagationLossModel::CalcRxPower(), EndSendDummyBlock(), ns3::MobilityModel::GetDistanceFrom(), ns3::Object::GetObject(), list, m_loss, m_phyList, third::phy, ns3::Simulator::ScheduleWithContext(), and ns3::Seconds().
SetPropagationModel()
void ns3::SimpleOfdmWimaxChannel::SetPropagationModel (PropModel propModel)
sets the propagation model
Parameters
propModel the propagation model to used
Definition at line 91 of file simple-ofdm-wimax-channel.cc.
References COST231_PROPAGATION, FRIIS_PROPAGATION, LOG_DISTANCE_PROPAGATION, m_loss, and RANDOM_PROPAGATION.
Member Data Documentation
m_loss
Ptr<PropagationLossModel> ns3::SimpleOfdmWimaxChannel::m_loss private
loss
Definition at line 127 of file simple-ofdm-wimax-channel.h.
Referenced by SimpleOfdmWimaxChannel(), Send(), and SetPropagationModel().
m_phyList
std::list<Ptr<SimpleOfdmWimaxPhy> > ns3::SimpleOfdmWimaxChannel::m_phyList private
phy list
Definition at line 109 of file simple-ofdm-wimax-channel.h.
Referenced by ~SimpleOfdmWimaxChannel(), AssignStreams(), DoAttach(), DoGetDevice(), DoGetNDevices(), and Send().
The documentation for this class was generated from the following files:
src/wimax/model/simple-ofdm-wimax-channel.h
src/wimax/model/simple-ofdm-wimax-channel.cc