ns-3: ns3::LteUeCphySapUser Class Reference
ns3::LteUeCphySapUser Class Reference abstract
Service Access Point (SAP) offered by the UE PHY to the UE RRC for control purposes.
#include "lte-ue-cphy-sap.h"
Classes
struct UeMeasurementsElement
Parameters of the ReportUeMeasurements primitive: RSRP [dBm] and RSRQ [dB] See section 5.1.1 and 5.1.3 of TS 36.214.
struct UeMeasurementsParameters
UeMeasurementsParameters structure.
Public Member Functions
virtual ~LteUeCphySapUser ()
destructor
virtual void NotifyInSync ()=0
Send an in sync indication to UE RRC.
virtual void NotifyOutOfSync ()=0
Send an out of sync indication to UE RRC.
virtual void RecvMasterInformationBlock (uint16_t cellId, LteRrcSap::MasterInformationBlock mib)=0
Relay an MIB message from the PHY entity to the RRC layer.
virtual void RecvSystemInformationBlockType1 (uint16_t cellId, LteRrcSap::SystemInformationBlockType1 sib1)=0
Relay an SIB1 message from the PHY entity to the RRC layer.
virtual void ReportUeMeasurements (UeMeasurementsParameters params)=0
Send a report of RSRP and RSRQ values perceived from PSS by the PHY entity (after applying layer-1 filtering) to the RRC layer.
virtual void ResetSyncIndicationCounter ()=0
Reset the sync indication counter.
Detailed Description
Service Access Point (SAP) offered by the UE PHY to the UE RRC for control purposes.
This is the CPHY SAP User, i.e., the part of the SAP that contains the RRC methods called by the PHY
Definition at line 208 of file lte-ue-cphy-sap.h.
Constructor & Destructor Documentation
~LteUeCphySapUser()
ns3::LteUeCphySapUser::~LteUeCphySapUser () virtual
destructor
Definition at line 29 of file lte-ue-cphy-sap.cc.
Member Function Documentation
NotifyInSync()
virtual void ns3::LteUeCphySapUser::NotifyInSync () pure virtual
Send an in sync indication to UE RRC.
When the number of in-sync indications are equal to N311, RRC stops the T310 timer.
Implemented in ns3::MemberLteUeCphySapUser< C >.
Referenced by ns3::LteUePhy::RlfDetection().
NotifyOutOfSync()
virtual void ns3::LteUeCphySapUser::NotifyOutOfSync () pure virtual
Send an out of sync indication to UE RRC.
When the number of out-of-sync indications are equal to N310, RRC starts the T310 timer.
Implemented in ns3::MemberLteUeCphySapUser< C >.
Referenced by ns3::LteUePhy::RlfDetection().
RecvMasterInformationBlock()
virtual void ns3::LteUeCphySapUser::RecvMasterInformationBlock (uint16_t cellId, LteRrcSap::MasterInformationBlock mib) pure virtual
Relay an MIB message from the PHY entity to the RRC layer.
This function is typically called after PHY receives an MIB message over the BCH.
Parameters
cellId the ID of the eNodeB where the message originates from
mib the Master Information Block message.
Implemented in ns3::MemberLteUeCphySapUser< C >.
Referenced by ns3::LteUePhy::ReceiveLteControlMessageList().
RecvSystemInformationBlockType1()
virtual void ns3::LteUeCphySapUser::RecvSystemInformationBlockType1 (uint16_t cellId, LteRrcSap::SystemInformationBlockType1 sib1) pure virtual
Relay an SIB1 message from the PHY entity to the RRC layer.
This function is typically called after PHY receives an SIB1 message over the BCH.
Parameters
cellId the ID of the eNodeB where the message originates from
sib1 the System Information Block Type 1 message
Implemented in ns3::MemberLteUeCphySapUser< C >.
Referenced by ns3::LteUePhy::ReceiveLteControlMessageList().
ReportUeMeasurements()
virtual void ns3::LteUeCphySapUser::ReportUeMeasurements (UeMeasurementsParameters params) pure virtual
Send a report of RSRP and RSRQ values perceived from PSS by the PHY entity (after applying layer-1 filtering) to the RRC layer.
Parameters
params the structure containing a vector of cellId, RSRP and RSRQ
Implemented in ns3::MemberLteUeCphySapUser< C >.
Referenced by ns3::LteUePhy::ReportUeMeasurements().
ResetSyncIndicationCounter()
virtual void ns3::LteUeCphySapUser::ResetSyncIndicationCounter () pure virtual
Reset the sync indication counter.
Resets the sync indication counter of RRC if the Qin or Qout condition is not fulfilled for the number of consecutive frames.
Implemented in ns3::MemberLteUeCphySapUser< C >.
Referenced by ns3::LteUePhy::RlfDetection().
The documentation for this class was generated from the following files:
src/lte/model/lte-ue-cphy-sap.h
src/lte/model/lte-ue-cphy-sap.cc