ns-3: ns3::dsr::DsrOptionSRHeader Class Reference
ns3::dsr::DsrOptionSRHeader Class Reference
DSR Routing
Source Route (SR) Message Format.
#include "dsr-option-header.h"
Public Types
typedef void(* TracedCallback) (const DsrOptionSRHeader &header)
TracedCallback signature for DsrOptionSrHeader.
Public Member Functions
DsrOptionSRHeader ()
Constructor.
virtual ~DsrOptionSRHeader ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
virtual Alignment GetAlignment () const
Get the Alignment requirement of this option header.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
Ipv4Address GetNodeAddress (uint8_t index) const
Get a Node IPv4 Address.
uint8_t GetNodeListSize () const
Get the node list size which is the number of ip address of the route.
std::vector< Ipv4Address > GetNodesAddress () const
Get the vector of ipv4 address.
uint8_t GetSalvage () const
Get the salvage value for a packet.
uint8_t GetSegmentsLeft () const
Get the number of segments left to send.
virtual uint32_t GetSerializedSize () const
Get the serialized size of the packet.
virtual void Print (std::ostream &os) const
Print some information about the packet.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetNodeAddress (uint8_t index, Ipv4Address addr)
Set a Node IPv4 Address.
void SetNodesAddress (std::vector< Ipv4Address > ipv4Address)
Set the vector of ipv4 address.
void SetNumberAddress (uint8_t n)
Set the number of ipv4 address.
void SetSalvage (uint8_t salvage)
Set the salvage value for a packet.
void SetSegmentsLeft (uint8_t segmentsLeft)
Set the number of segments left to send.
Public Member Functions inherited from ns3::dsr::DsrOptionHeader
DsrOptionHeader ()
Constructor.
virtual ~DsrOptionHeader ()
Destructor.
uint8_t GetLength () const
Get the option length.
uint8_t GetType () const
Get the type of the option.
void SetLength (uint8_t length)
Set the option length.
void SetType (uint8_t type)
Set the type of the option.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::dsr::DsrOptionHeader
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef std::vector< Ipv4Address > VectorIpv4Address_t
A vector of IPv4 Address.
Private Attributes
Ipv4Address m_address
The ip address header deserilize to.
VectorIpv4Address_t m_ipv4Address
The vector of Nodes' IPv4 Address.
uint8_t m_salvage
Number of savlage times for a packet.
uint8_t m_segmentsLeft
Number of left segments.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Source Route (SR) Message Format.
Introspection did not find any typical Config paths.
Header of Dsr Option Source Route.
 |      0        |      1        |      2        |      3        |
 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |  Option Type |  Opt Data Len |F|L|Reservd|Salvage|  Segs Left |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                            Address[1]                         |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                            Address[2]                         |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                               ...                             |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                            Address[n]                         |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 88 bytes (on a 64-bit architecture).
Definition at line 570 of file dsr-option-header.h.
Member Typedef Documentation
TracedCallback
typedef void(* ns3::dsr::DsrOptionSRHeader::TracedCallback) (const DsrOptionSRHeader &header)
TracedCallback signature for DsrOptionSrHeader.
Parameters
[in] header The DsrOptionsSRHeader
Definition at line 676 of file dsr-option-header.h.
VectorIpv4Address_t
typedef std::vector<Ipv4Address> ns3::dsr::DsrOptionSRHeader::VectorIpv4Address_t private
A vector of IPv4 Address.
Definition at line 694 of file dsr-option-header.h.
Constructor & Destructor Documentation
DsrOptionSRHeader()
ns3::dsr::DsrOptionSRHeader::DsrOptionSRHeader ()
Constructor.
Definition at line 536 of file dsr-option-header.cc.
References m_ipv4Address, ns3::dsr::DsrOptionHeader::SetLength(), and ns3::dsr::DsrOptionHeader::SetType().
~DsrOptionSRHeader()
ns3::dsr::DsrOptionSRHeader::~DsrOptionSRHeader () virtual
Destructor.
Definition at line 544 of file dsr-option-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::dsr::DsrOptionSRHeader::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start Buffer iterator
Returns
size of the packet
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 634 of file dsr-option-header.cc.
References ns3::Ipv4Address::Deserialize(), GetSerializedSize(), m_address, m_ipv4Address, m_salvage, m_segmentsLeft, ns3::Buffer::Iterator::Read(), ns3::Buffer::Iterator::ReadU8(), ns3::dsr::DsrOptionHeader::SetLength(), SetNodeAddress(), ns3::dsr::DsrOptionHeader::SetType(), and visualizer.core::start().
GetAlignment()
DsrOptionHeader::Alignment ns3::dsr::DsrOptionSRHeader::GetAlignment () const virtual
Get the Alignment requirement of this option header.
Returns
The required alignment
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 656 of file dsr-option-header.cc.
GetInstanceTypeId()
TypeId ns3::dsr::DsrOptionSRHeader::GetInstanceTypeId (void) const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 531 of file dsr-option-header.cc.
References GetTypeId().
GetNodeAddress()
Ipv4Address ns3::dsr::DsrOptionSRHeader::GetNodeAddress (uint8_t index) const
Get a Node IPv4 Address.
Parameters
index the index of the IPv4 Address
Returns
the router IPv4 Address
Definition at line 590 of file dsr-option-header.cc.
References m_ipv4Address.
Referenced by DsrSRHeaderTest::DoRun(), ns3::dsr::DsrOptionRerr::DoSendError(), and ns3::dsr::DsrOptionSR::Process().
GetNodeListSize()
uint8_t ns3::dsr::DsrOptionSRHeader::GetNodeListSize () const
Get the node list size which is the number of ip address of the route.
Returns
the node list size
Definition at line 595 of file dsr-option-header.cc.
References m_ipv4Address.
GetNodesAddress()
std::vector< Ipv4Address > ns3::dsr::DsrOptionSRHeader::GetNodesAddress () const
Get the vector of ipv4 address.
Returns
the vector of ipv4 address
Definition at line 580 of file dsr-option-header.cc.
References m_ipv4Address.
Referenced by ns3::dsr::DsrRouting::CancelPacketTimerNextHop(), ns3::dsr::DsrOptionRerr::DoSendError(), ns3::dsr::DsrOptionSR::Process(), and ns3::dsr::DsrRouting::SendPacketFromBuffer().
GetSalvage()
uint8_t ns3::dsr::DsrOptionSRHeader::GetSalvage () const
Get the salvage value for a packet.
Returns
The salvage value of the packet
Definition at line 563 of file dsr-option-header.cc.
References m_salvage.
Referenced by ns3::dsr::DsrRouting::CancelPacketTimerNextHop(), DsrSRHeaderTest::DoRun(), ns3::dsr::DsrOptionRerr::DoSendError(), ns3::dsr::DsrOptionSR::Process(), and ns3::dsr::DsrRouting::SalvagePacket().
GetSegmentsLeft()
uint8_t ns3::dsr::DsrOptionSRHeader::GetSegmentsLeft () const
Get the number of segments left to send.
Returns
The segments left
Definition at line 553 of file dsr-option-header.cc.
References m_segmentsLeft.
Referenced by DsrSRHeaderTest::DoRun(), ns3::dsr::DsrOptionRerr::DoSendError(), ns3::dsr::DsrRouting::ForwardPacket(), and ns3::dsr::DsrOptionSR::Process().
GetSerializedSize()
uint32_t ns3::dsr::DsrOptionSRHeader::GetSerializedSize (void) const virtual
Get the serialized size of the packet.
Returns
size
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 612 of file dsr-option-header.cc.
References m_ipv4Address.
Referenced by Deserialize(), ns3::dsr::DsrOptionRerr::DoSendError(), and ns3::dsr::DsrOptionSR::Process().
GetTypeId()
TypeId ns3::dsr::DsrOptionSRHeader::GetTypeId (void) static
Get the type identificator.
Returns
type identificator
Definition at line 521 of file dsr-option-header.cc.
References ns3::TypeId::AddConstructor().
Referenced by GetInstanceTypeId().
Print()
void ns3::dsr::DsrOptionSRHeader::Print (std::ostream & os) const virtual
Print some information about the packet.
Parameters
os output stream
Returns
info about this packet
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 600 of file dsr-option-header.cc.
References ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrOptionHeader::GetType(), and m_ipv4Address.
Referenced by ns3::dsr::operator<<().
Serialize()
void ns3::dsr::DsrOptionSRHeader::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start Buffer iterator
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 617 of file dsr-option-header.cc.
References ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrOptionHeader::GetType(), m_ipv4Address, m_salvage, m_segmentsLeft, visualizer.core::start(), ns3::Buffer::Iterator::Write(), and ns3::Buffer::Iterator::WriteU8().
SetNodeAddress()
void ns3::dsr::DsrOptionSRHeader::SetNodeAddress (uint8_t index, Ipv4Address addr)
Set a Node IPv4 Address.
Parameters
index the index of the IPv4 Address
addr the new IPv4 Address
Definition at line 585 of file dsr-option-header.cc.
References m_ipv4Address.
Referenced by Deserialize().
SetNodesAddress()
void ns3::dsr::DsrOptionSRHeader::SetNodesAddress (std::vector< Ipv4Address > ipv4Address)
Set the vector of ipv4 address.
Parameters
ipv4Address the vector of ipv4 address
Definition at line 574 of file dsr-option-header.cc.
References m_ipv4Address, and ns3::dsr::DsrOptionHeader::SetLength().
Referenced by ns3::dsr::DsrRouting::CheckSendBuffer(), DsrSRHeaderTest::DoRun(), ns3::dsr::DsrOptionRerr::DoSendError(), ns3::dsr::DsrRouting::PacketNewRoute(), ns3::dsr::DsrOptionRreq::Process(), ns3::dsr::DsrOptionRrep::Process(), ns3::dsr::DsrOptionSR::Process(), ns3::dsr::DsrRouting::RouteRequestTimerExpire(), ns3::dsr::DsrRouting::SalvagePacket(), ns3::dsr::DsrRouting::Send(), ns3::dsr::DsrRouting::SendErrorRequest(), and ns3::dsr::DsrRouting::SendUnreachError().
SetNumberAddress()
void ns3::dsr::DsrOptionSRHeader::SetNumberAddress (uint8_t n)
Set the number of ipv4 address.
Parameters
n the number of ipv4' address
Definition at line 568 of file dsr-option-header.cc.
References m_ipv4Address, and sample-rng-plot::n.
Referenced by ns3::dsr::DsrRouting::AddAckReqHeader(), ns3::dsr::DsrRouting::CancelPacketTimerNextHop(), DsrSRHeaderTest::DoRun(), ns3::dsr::DsrOptionRerr::DoSendError(), ns3::dsr::DsrOptionSR::Process(), and ns3::dsr::DsrRouting::SalvagePacket().
SetSalvage()
void ns3::dsr::DsrOptionSRHeader::SetSalvage (uint8_t salvage)
Set the salvage value for a packet.
Parameters
salvage The salvage value of the packet
Definition at line 558 of file dsr-option-header.cc.
References m_salvage.
Referenced by ns3::dsr::DsrRouting::CheckSendBuffer(), DsrSRHeaderTest::DoRun(), ns3::dsr::DsrOptionRerr::DoSendError(), ns3::dsr::DsrRouting::PacketNewRoute(), ns3::dsr::DsrOptionRreq::Process(), ns3::dsr::DsrOptionRrep::Process(), ns3::dsr::DsrOptionSR::Process(), ns3::dsr::DsrRouting::RouteRequestTimerExpire(), ns3::dsr::DsrRouting::SalvagePacket(), ns3::dsr::DsrRouting::Send(), and ns3::dsr::DsrRouting::SendErrorRequest().
SetSegmentsLeft()
void ns3::dsr::DsrOptionSRHeader::SetSegmentsLeft (uint8_t segmentsLeft)
Set the number of segments left to send.
Parameters
segmentsLeft The segments left
Definition at line 548 of file dsr-option-header.cc.
References m_segmentsLeft.
Referenced by ns3::dsr::DsrRouting::CheckSendBuffer(), DsrSRHeaderTest::DoRun(), ns3::dsr::DsrOptionRerr::DoSendError(), ns3::dsr::DsrRouting::PacketNewRoute(), ns3::dsr::DsrOptionRreq::Process(), ns3::dsr::DsrOptionRrep::Process(), ns3::dsr::DsrOptionSR::Process(), ns3::dsr::DsrRouting::RouteRequestTimerExpire(), ns3::dsr::DsrRouting::SalvagePacket(), ns3::dsr::DsrRouting::Send(), ns3::dsr::DsrRouting::SendErrorRequest(), and ns3::dsr::DsrRouting::SendUnreachError().
Member Data Documentation
m_address
Ipv4Address ns3::dsr::DsrOptionSRHeader::m_address private
The ip address header deserilize to.
Definition at line 682 of file dsr-option-header.h.
Referenced by Deserialize().
m_ipv4Address
VectorIpv4Address_t ns3::dsr::DsrOptionSRHeader::m_ipv4Address private
The vector of Nodes' IPv4 Address.
Definition at line 698 of file dsr-option-header.h.
Referenced by DsrOptionSRHeader(), Deserialize(), GetNodeAddress(), GetNodeListSize(), GetNodesAddress(), GetSerializedSize(), Print(), Serialize(), SetNodeAddress(), SetNodesAddress(), and SetNumberAddress().
m_salvage
uint8_t ns3::dsr::DsrOptionSRHeader::m_salvage private
Number of savlage times for a packet.
Definition at line 690 of file dsr-option-header.h.
Referenced by Deserialize(), GetSalvage(), Serialize(), and SetSalvage().
m_segmentsLeft
uint8_t ns3::dsr::DsrOptionSRHeader::m_segmentsLeft private
Number of left segments.
Definition at line 686 of file dsr-option-header.h.
Referenced by Deserialize(), GetSegmentsLeft(), Serialize(), and SetSegmentsLeft().
The documentation for this class was generated from the following files:
src/dsr/model/dsr-option-header.h
src/dsr/model/dsr-option-header.cc