ns-3: ns3::YansWifiPhy Class Reference
ns3::YansWifiPhy Class Reference
Wifi Models
802.11 PHY layer model
#include "yans-wifi-phy.h"
Public Member Functions
YansWifiPhy ()
virtual ~YansWifiPhy ()
virtual Ptr< Channel > GetChannel (void) const
Return the Channel this WifiPhy is connected to.
void SetChannel (const Ptr< YansWifiChannel > channel)
Set the YansWifiChannel this YansWifiPhy is to be connected to.
void StartTx (Ptr< WifiPpdu > ppdu)
Public Member Functions inherited from ns3::WifiPhy
WifiPhy ()
virtual ~WifiPhy ()
void AddSupportedChannelWidth (uint16_t width)
virtual int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
double CalculateSnr (WifiTxVector txVector, double ber) const
virtual void ConfigureStandardAndBand (WifiPhyStandard standard, WifiPhyBand band)
Configure the PHY-level parameters for different Wi-Fi standard.
void ContinueReceiveHeader (Ptr< Event > event)
Continue receiving the PHY header of a PPDU (i.e.
bool DefineChannelNumber (uint8_t channelNumber, WifiPhyBand band, WifiPhyStandard standard, uint16_t frequency, uint16_t channelWidth)
Add a channel definition to the WifiPhy.
void EndReceive (Ptr< Event > event)
The last symbol of the PPDU has arrived.
void EndReceiveInterBss (void)
For HE receptions only, check and possibly modify the transmit power restriction state at the end of PPDU reception.
Time GetAckTxTime (void) const
Return the estimated Ack TX time for this PHY.
Time GetBlockAckTxTime (void) const
Return the estimated BlockAck TX time for this PHY.
uint8_t GetBssMembershipSelector (uint8_t selector) const
The WifiPhy::BssMembershipSelector() method is used (e.g., by a WifiRemoteStationManager) to determine the set of transmission/reception modes that this WifiPhy(-derived class) can support - a set of WifiMode objects which we call the BssMembershipSelectorSet, and which is stored as WifiPhy::m_bssMembershipSelectorSet.
double GetCcaEdThreshold (void) const
Return the CCA threshold (dBm).
uint8_t GetChannelNumber (void) const
Return current channel number.
Time GetChannelSwitchDelay (void) const
uint16_t GetChannelWidth (void) const
Time GetDelayUntilIdle (void)
Ptr< NetDevice > GetDevice (void) const
Return the device this PHY is associated with.
uint16_t GetFrequency (void) const
Time GetLastRxEndTime (void) const
Return the end time of the last received packet.
Time GetLastRxStartTime (void) const
Return the start time of the last received packet.
uint8_t GetMaxSupportedRxSpatialStreams (void) const
uint8_t GetMaxSupportedTxSpatialStreams (void) const
WifiMode GetMcs (uint8_t mcs) const
The WifiPhy::GetMcs() method is used (e.g., by a WifiRemoteStationManager) to determine the set of transmission/reception MCS indexes that this WifiPhy(-derived class) can support - a set of MCS indexes which we call the DeviceMcsSet, and which is stored as WifiPhy::m_deviceMcsSet.
WifiMode GetMcs (WifiModulationClass modulation, uint8_t mcs) const
Get the WifiMode object corresponding to the given MCS of the given modulation class.
Ptr< MobilityModel > GetMobility (void) const
Return the mobility model this PHY is associated with.
WifiMode GetMode (uint8_t mode) const
The WifiPhy::GetNModes() and WifiPhy::GetMode() methods are used (e.g., by a WifiRemoteStationManager) to determine the set of transmission/reception modes that this WifiPhy(-derived class) can support - a set of WifiMode objects which we call the DeviceRateSet, and which is stored as WifiPhy::m_deviceRateSet.
uint8_t GetNBssMembershipSelectors (void) const
The WifiPhy::NBssMembershipSelectors() method is used (e.g., by a WifiRemoteStationManager) to determine the set of transmission/reception modes that this WifiPhy(-derived class) can support - a set of WifiMode objects which we call the BssMembershipSelectorSet, and which is stored as WifiPhy::m_bssMembershipSelectorSet.
uint8_t GetNMcs (void) const
The WifiPhy::GetNMcs() method is used (e.g., by a WifiRemoteStationManager) to determine the set of transmission/reception MCS indexes that this WifiPhy(-derived class) can support - a set of MCS indexes which we call the DeviceMcsSet, and which is stored as WifiPhy::m_deviceMcsSet.
uint8_t GetNModes (void) const
The WifiPhy::GetNModes() and WifiPhy::GetMode() methods are used (e.g., by a WifiRemoteStationManager) to determine the set of transmission/reception modes that this WifiPhy(-derived class) can support - a set of WifiMode objects which we call the DeviceRateSet, and which is stored as WifiPhy::m_deviceRateSet.
uint8_t GetNTxPower (void) const
Return the number of available transmission power levels.
uint8_t GetNumberOfAntennas (void) const
WifiPhyBand GetPhyBand (void) const
Get the configured Wi-Fi band.
WifiPhyStandard GetPhyStandard (void) const
Get the configured Wi-Fi standard.
Time GetPifs (void) const
Return the PCF Interframe Space (PIFS) for this PHY.
double GetPowerDbm (uint8_t power) const
Get the power of the given power level in dBm.
double GetRxGain (void) const
Return the reception gain (dB).
double GetRxSensitivity (void) const
Return the receive sensitivity threshold (dBm).
bool GetShortPhyPreambleSupported (void) const
Return whether short PHY preamble is supported.
Time GetSifs (void) const
Return the Short Interframe Space (SIFS) for this PHY.
Time GetSlot (void) const
Return the slot duration for this PHY.
Ptr< WifiPhyStateHelper > GetState (void) const
Return the WifiPhyStateHelper of this PHY.
std::vector< uint16_t > GetSupportedChannelWidthSet (void) const
double GetTxGain (void) const
Return the transmission gain (dB).
double GetTxPowerEnd (void) const
Return the maximum available transmission power level (dBm).
double GetTxPowerForTransmission (WifiTxVector txVector) const
Compute the transmit power (in dBm) for the next transmission.
double GetTxPowerStart (void) const
Return the minimum available transmission power level (dBm).
bool IsMcsSupported (WifiMode mcs) const
Check if the given WifiMode is supported by the PHY.
bool IsMcsSupported (WifiModulationClass mc, uint8_t mcs) const
Check if the given MCS of the given modulation class is supported by the PHY.
bool IsModeSupported (WifiMode mode) const
Check if the given WifiMode is supported by the PHY.
bool IsStateCcaBusy (void) const
bool IsStateIdle (void) const
bool IsStateOff (void) const
bool IsStateRx (void) const
bool IsStateSleep (void) const
bool IsStateSwitching (void) const
bool IsStateTx (void) const
void NotifyChannelAccessRequested (void)
Notify the PHY that an access to the channel was requested.
void NotifyEndOfHePreamble (HePreambleParameters params)
Public method used to fire a EndOfHePreamble trace once both HE SIG fields have been received, as well as training fields.
void NotifyMonitorSniffRx (Ptr< const WifiPsdu > psdu, uint16_t channelFreqMhz, WifiTxVector txVector, SignalNoiseDbm signalNoise, std::vector< bool > statusPerMpdu, uint16_t staId=SU_STA_ID)
Public method used to fire a MonitorSniffer trace for a wifi PSDU being received.
void NotifyMonitorSniffTx (Ptr< const WifiPsdu > psdu, uint16_t channelFreqMhz, WifiTxVector txVector, uint16_t staId=SU_STA_ID)
Public method used to fire a MonitorSniffer trace for a wifi PSDU being transmitted.
void NotifyRxBegin (Ptr< const WifiPsdu > psdu, RxPowerWattPerChannelBand rxPowersW)
Public method used to fire a PhyRxBegin trace.
void NotifyRxDrop (Ptr< const WifiPsdu > psdu, WifiPhyRxfailureReason reason)
Public method used to fire a PhyRxDrop trace.
void NotifyRxEnd (Ptr< const WifiPsdu > psdu)
Public method used to fire a PhyRxEnd trace.
void NotifyTxBegin (WifiConstPsduMap psdus, double txPowerW)
Public method used to fire a PhyTxBegin trace.
void NotifyTxDrop (Ptr< const WifiPsdu > psdu)
Public method used to fire a PhyTxDrop trace.
void NotifyTxEnd (WifiConstPsduMap psdus)
Public method used to fire a PhyTxEnd trace.
void RegisterListener (WifiPhyListener *listener)
void ResetCca (bool powerRestricted, double txPowerMaxSiso=0, double txPowerMaxMimo=0)
Reset PHY to IDLE, with some potential TX power restrictions for the next transmission.
void ResetReceive (Ptr< Event > event)
Reset PHY at the end of the packet under reception after it has failed the PHY header.
void ResumeFromOff (void)
Resume from off mode.
void ResumeFromSleep (void)
Resume from sleep mode.
void Send (Ptr< const WifiPsdu > psdu, WifiTxVector txVector)
void Send (WifiConstPsduMap psdus, WifiTxVector txVector)
void SetCapabilitiesChangedCallback (Callback< void > callback)
void SetCcaEdThreshold (double threshold)
Sets the CCA threshold (dBm).
virtual void SetChannelNumber (uint8_t id)
Set channel number.
virtual void SetChannelWidth (uint16_t channelWidth)
void SetDevice (const Ptr< NetDevice > device)
Sets the device this PHY is associated with.
void SetErrorRateModel (const Ptr< ErrorRateModel > rate)
Sets the error rate model.
void SetFrameCaptureModel (const Ptr< FrameCaptureModel > frameCaptureModel)
Sets the frame capture model.
virtual void SetFrequency (uint16_t freq)
void SetMaxSupportedRxSpatialStreams (uint8_t streams)
void SetMaxSupportedTxSpatialStreams (uint8_t streams)
void SetMobility (const Ptr< MobilityModel > mobility)
assign a mobility model to this device
void SetNTxPower (uint8_t n)
Sets the number of transmission power levels available between the minimum level and the maximum level.
void SetNumberOfAntennas (uint8_t antennas)
void SetOffMode (void)
Put in off mode.
void SetPifs (Time pifs)
Set the PCF Interframe Space (PIFS) for this PHY.
void SetPostReceptionErrorModel (const Ptr< ErrorModel > em)
Attach a receive ErrorModel to the WifiPhy.
void SetPreambleDetectionModel (const Ptr< PreambleDetectionModel > preambleDetectionModel)
Sets the preamble detection model.
void SetReceiveErrorCallback (RxErrorCallback callback)
void SetReceiveOkCallback (RxOkCallback callback)
void SetRxGain (double gain)
Sets the reception gain (dB).
void SetRxNoiseFigure (double noiseFigureDb)
Sets the RX loss (dB) in the Signal-to-Noise-Ratio due to non-idealities in the receiver.
void SetRxSensitivity (double threshold)
Sets the receive sensitivity threshold (dBm).
void SetShortPhyPreambleSupported (bool preamble)
Enable or disable short PHY preamble.
void SetSifs (Time sifs)
Set the Short Interframe Space (SIFS) for this PHY.
void SetSleepMode (void)
Put in sleep mode.
void SetSlot (Time slot)
Set the slot duration for this PHY.
void SetTxGain (double gain)
Sets the transmission gain (dB).
void SetTxPowerEnd (double end)
Sets the maximum available transmission power level (dBm).
void SetTxPowerStart (double start)
Sets the minimum available transmission power level (dBm).
void SetWifiRadioEnergyModel (const Ptr< WifiRadioEnergyModel > wifiRadioEnergyModel)
Sets the wifi radio energy model.
void StartReceiveHeader (Ptr< Event > event)
Start receiving the PHY header of a PPDU (i.e.
void StartReceivePayload (Ptr< Event > event)
Start receiving the PSDU (i.e.
void StartReceivePreamble (Ptr< WifiPpdu > ppdu, RxPowerWattPerChannelBand rxPowersW)
Start receiving the PHY preamble of a PPDU (i.e.
void UnregisterListener (WifiPhyListener *listener)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::WifiPhy
static Time CalculatePhyPreambleAndHeaderDuration (WifiTxVector txVector)
static Time CalculateTxDuration (uint32_t size, WifiTxVector txVector, WifiPhyBand band, uint16_t staId=SU_STA_ID)
static Time CalculateTxDuration (WifiConstPsduMap psduMap, WifiTxVector txVector, WifiPhyBand band)
static WifiMode GetDsssRate11Mbps ()
Return a WifiMode for DSSS at 11Mbps.
static WifiMode GetDsssRate1Mbps ()
Return a WifiMode for DSSS at 1Mbps.
static WifiMode GetDsssRate2Mbps ()
Return a WifiMode for DSSS at 2Mbps.
static WifiMode GetDsssRate5_5Mbps ()
Return a WifiMode for DSSS at 5.5Mbps.
static WifiMode GetErpOfdmRate12Mbps ()
Return a WifiMode for ERP-OFDM at 12Mbps.
static WifiMode GetErpOfdmRate18Mbps ()
Return a WifiMode for ERP-OFDM at 18Mbps.
static WifiMode GetErpOfdmRate24Mbps ()
Return a WifiMode for ERP-OFDM at 24Mbps.
static WifiMode GetErpOfdmRate36Mbps ()
Return a WifiMode for ERP-OFDM at 36Mbps.
static WifiMode GetErpOfdmRate48Mbps ()
Return a WifiMode for ERP-OFDM at 48Mbps.
static WifiMode GetErpOfdmRate54Mbps ()
Return a WifiMode for ERP-OFDM at 54Mbps.
static WifiMode GetErpOfdmRate6Mbps ()
Return a WifiMode for ERP-OFDM at 6Mbps.
static WifiMode GetErpOfdmRate9Mbps ()
Return a WifiMode for ERP-OFDM at 9Mbps.
static WifiMode GetHeMcs (uint8_t mcs)
Get the WifiMode object corresponding to the given MCS of the HE modulation class.
static WifiMode GetHeMcs0 ()
Return MCS 0 from HE MCS values.
static WifiMode GetHeMcs1 ()
Return MCS 1 from HE MCS values.
static WifiMode GetHeMcs10 ()
Return MCS 10 from HE MCS values.
static WifiMode GetHeMcs11 ()
Return MCS 11 from HE MCS values.
static WifiMode GetHeMcs2 ()
Return MCS 2 from HE MCS values.
static WifiMode GetHeMcs3 ()
Return MCS 3 from HE MCS values.
static WifiMode GetHeMcs4 ()
Return MCS 4 from HE MCS values.
static WifiMode GetHeMcs5 ()
Return MCS 5 from HE MCS values.
static WifiMode GetHeMcs6 ()
Return MCS 6 from HE MCS values.
static WifiMode GetHeMcs7 ()
Return MCS 7 from HE MCS values.
static WifiMode GetHeMcs8 ()
Return MCS 8 from HE MCS values.
static WifiMode GetHeMcs9 ()
Return MCS 9 from HE MCS values.
static WifiMode GetHePhyHeaderMode ()
static WifiMode GetHtMcs (uint8_t mcs)
Get the WifiMode object corresponding to the given MCS of the HT modulation class.
static WifiMode GetHtMcs0 ()
Return MCS 0 from HT MCS values.
static WifiMode GetHtMcs1 ()
Return MCS 1 from HT MCS values.
static WifiMode GetHtMcs10 ()
Return MCS 10 from HT MCS values.
static WifiMode GetHtMcs11 ()
Return MCS 11 from HT MCS values.
static WifiMode GetHtMcs12 ()
Return MCS 12 from HT MCS values.
static WifiMode GetHtMcs13 ()
Return MCS 13 from HT MCS values.
static WifiMode GetHtMcs14 ()
Return MCS 14 from HT MCS values.
static WifiMode GetHtMcs15 ()
Return MCS 15 from HT MCS values.
static WifiMode GetHtMcs16 ()
Return MCS 16 from HT MCS values.
static WifiMode GetHtMcs17 ()
Return MCS 17 from HT MCS values.
static WifiMode GetHtMcs18 ()
Return MCS 18 from HT MCS values.
static WifiMode GetHtMcs19 ()
Return MCS 19 from HT MCS values.
static WifiMode GetHtMcs2 ()
Return MCS 2 from HT MCS values.
static WifiMode GetHtMcs20 ()
Return MCS 20 from HT MCS values.
static WifiMode GetHtMcs21 ()
Return MCS 21 from HT MCS values.
static WifiMode GetHtMcs22 ()
Return MCS 22 from HT MCS values.
static WifiMode GetHtMcs23 ()
Return MCS 23 from HT MCS values.
static WifiMode GetHtMcs24 ()
Return MCS 24 from HT MCS values.
static WifiMode GetHtMcs25 ()
Return MCS 25 from HT MCS values.
static WifiMode GetHtMcs26 ()
Return MCS 26 from HT MCS values.
static WifiMode GetHtMcs27 ()
Return MCS 27 from HT MCS values.
static WifiMode GetHtMcs28 ()
Return MCS 28 from HT MCS values.
static WifiMode GetHtMcs29 ()
Return MCS 29 from HT MCS values.
static WifiMode GetHtMcs3 ()
Return MCS 3 from HT MCS values.
static WifiMode GetHtMcs30 ()
Return MCS 30 from HT MCS values.
static WifiMode GetHtMcs31 ()
Return MCS 31 from HT MCS values.
static WifiMode GetHtMcs4 ()
Return MCS 4 from HT MCS values.
static WifiMode GetHtMcs5 ()
Return MCS 5 from HT MCS values.
static WifiMode GetHtMcs6 ()
Return MCS 6 from HT MCS values.
static WifiMode GetHtMcs7 ()
Return MCS 7 from HT MCS values.
static WifiMode GetHtMcs8 ()
Return MCS 8 from HT MCS values.
static WifiMode GetHtMcs9 ()
Return MCS 9 from HT MCS values.
static WifiMode GetHtPhyHeaderMode ()
static WifiMode GetOfdmRate12Mbps ()
Return a WifiMode for OFDM at 12Mbps.
static WifiMode GetOfdmRate12MbpsBW10MHz ()
Return a WifiMode for OFDM at 12Mbps with 10MHz channel spacing.
static WifiMode GetOfdmRate12MbpsBW5MHz ()
Return a WifiMode for OFDM at 12Mbps with 5MHz channel spacing.
static WifiMode GetOfdmRate13_5MbpsBW5MHz ()
Return a WifiMode for OFDM at 13.5Mbps with 5MHz channel spacing.
static WifiMode GetOfdmRate18Mbps ()
Return a WifiMode for OFDM at 18Mbps.
static WifiMode GetOfdmRate18MbpsBW10MHz ()
Return a WifiMode for OFDM at 18Mbps with 10MHz channel spacing.
static WifiMode GetOfdmRate1_5MbpsBW5MHz ()
Return a WifiMode for OFDM at 1.5Mbps with 5MHz channel spacing.
static WifiMode GetOfdmRate24Mbps ()
Return a WifiMode for OFDM at 24Mbps.
static WifiMode GetOfdmRate24MbpsBW10MHz ()
Return a WifiMode for OFDM at 24Mbps with 10MHz channel spacing.
static WifiMode GetOfdmRate27MbpsBW10MHz ()
Return a WifiMode for OFDM at 27Mbps with 10MHz channel spacing.
static WifiMode GetOfdmRate2_25MbpsBW5MHz ()
Return a WifiMode for OFDM at 2.25Mbps with 5MHz channel spacing.
static WifiMode GetOfdmRate36Mbps ()
Return a WifiMode for OFDM at 36Mbps.
static WifiMode GetOfdmRate3MbpsBW10MHz ()
Return a WifiMode for OFDM at 3Mbps with 10MHz channel spacing.
static WifiMode GetOfdmRate3MbpsBW5MHz ()
Return a WifiMode for OFDM at 3Mbps with 5MHz channel spacing.
static WifiMode GetOfdmRate48Mbps ()
Return a WifiMode for OFDM at 48Mbps.
static WifiMode GetOfdmRate4_5MbpsBW10MHz ()
Return a WifiMode for OFDM at 4.5Mbps with 10MHz channel spacing.
static WifiMode GetOfdmRate4_5MbpsBW5MHz ()
Return a WifiMode for OFDM at 4.5Mbps with 5MHz channel spacing.
static WifiMode GetOfdmRate54Mbps ()
Return a WifiMode for OFDM at 54Mbps.
static WifiMode GetOfdmRate6Mbps ()
Return a WifiMode for OFDM at 6Mbps.
static WifiMode GetOfdmRate6MbpsBW10MHz ()
Return a WifiMode for OFDM at 6Mbps with 10MHz channel spacing.
static WifiMode GetOfdmRate6MbpsBW5MHz ()
Return a WifiMode for OFDM at 6Mbps with 5MHz channel spacing.
static WifiMode GetOfdmRate9Mbps ()
Return a WifiMode for OFDM at 9Mbps.
static WifiMode GetOfdmRate9MbpsBW10MHz ()
Return a WifiMode for OFDM at 9Mbps with 10MHz channel spacing.
static WifiMode GetOfdmRate9MbpsBW5MHz ()
Return a WifiMode for OFDM at 9Mbps with 5MHz channel spacing.
static Time GetPayloadDuration (uint32_t size, WifiTxVector txVector, WifiPhyBand band, MpduType mpdutype, bool incFlag, uint32_t &totalAmpduSize, double &totalAmpduNumSymbols, uint16_t staId)
static Time GetPayloadDuration (uint32_t size, WifiTxVector txVector, WifiPhyBand band, MpduType mpdutype=NORMAL_MPDU, uint16_t staId=SU_STA_ID)
static Time GetPhyHeaderDuration (WifiTxVector txVector)
static WifiMode GetPhyHeaderMode (WifiTxVector txVector)
static Time GetPhyHtSigHeaderDuration (WifiPreamble preamble)
static Time GetPhyPreambleDuration (WifiTxVector txVector)
static Time GetPhySigA1Duration (WifiPreamble preamble)
static Time GetPhySigA2Duration (WifiPreamble preamble)
static Time GetPhySigBDuration (WifiPreamble preamble)
static Time GetPhyTrainingSymbolDuration (WifiTxVector txVector)
static Time GetPreambleDetectionDuration (void)
static Time GetStartOfPacketDuration (WifiTxVector txVector)
static TypeId GetTypeId (void)
Get the type ID.
static WifiMode GetVhtMcs (uint8_t mcs)
Get the WifiMode object corresponding to the given MCS of the VHT modulation class.
static WifiMode GetVhtMcs0 ()
Return MCS 0 from VHT MCS values.
static WifiMode GetVhtMcs1 ()
Return MCS 1 from VHT MCS values.
static WifiMode GetVhtMcs2 ()
Return MCS 2 from VHT MCS values.
static WifiMode GetVhtMcs3 ()
Return MCS 3 from VHT MCS values.
static WifiMode GetVhtMcs4 ()
Return MCS 4 from VHT MCS values.
static WifiMode GetVhtMcs5 ()
Return MCS 5 from VHT MCS values.
static WifiMode GetVhtMcs6 ()
Return MCS 6 from VHT MCS values.
static WifiMode GetVhtMcs7 ()
Return MCS 7 from VHT MCS values.
static WifiMode GetVhtMcs8 ()
Return MCS 8 from VHT MCS values.
static WifiMode GetVhtMcs9 ()
Return MCS 9 from VHT MCS values.
static WifiMode GetVhtPhyHeaderMode ()
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::WifiPhy
virtual WifiSpectrumBand ConvertHeRuSubcarriers (uint16_t channelWidth, HeRu::SubcarrierRange range) const
bool DoChannelSwitch (uint8_t id)
The default implementation does nothing and returns true.
bool DoFrequencySwitch (uint16_t frequency)
The default implementation does nothing and returns true.
virtual void DoInitialize (void)
Initialize() implementation.
virtual WifiSpectrumBand GetBand (uint16_t bandWidth, uint8_t bandIndex=0)
Get the start band index and the stop band index for a given band.
virtual uint16_t GetStaId (void) const
Return the STA ID that has been assigned to the station this PHY belongs to.
void SwitchMaybeToCcaBusy (void)
Check if PHY state should move to CCA busy state based on current state of interference tracker.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Attributes
Ptr< YansWifiChannel > m_channel
YansWifiChannel that this YansWifiPhy is connected to.
Additional Inherited Members
Public Types inherited from ns3::WifiPhy
typedef std::pair< uint8_t, WifiPhyBand > ChannelNumberBandPair
A pair of a channel number and a WifiPhyBand.
typedef std::pair< ChannelNumberBandPair, WifiPhyStandard > ChannelNumberStandardPair
A pair of a ChannelNumberBandPair and a WifiPhyStandard.
typedef void(* EndOfHePreambleCallback) (HePreambleParameters params)
TracedCallback signature for end of HE-SIG-A events.
typedef std::pair< uint16_t, uint16_t > FrequencyWidthPair
A pair of a center frequency (MHz) and a channel width (MHz)
typedef void(* MonitorSnifferRxCallback) (Ptr< const Packet > packet, uint16_t channelFreqMhz, WifiTxVector txVector, MpduInfo aMpdu, SignalNoiseDbm signalNoise, uint16_t staId)
TracedCallback signature for monitor mode receive events.
typedef void(* MonitorSnifferTxCallback) (const Ptr< const Packet > packet, uint16_t channelFreqMhz, WifiTxVector txVector, MpduInfo aMpdu, uint16_t staId)
TracedCallback signature for monitor mode transmit events.
typedef void(* PhyRxPayloadBeginTracedCallback) (WifiTxVector txVector, Time psduDuration)
TracedCallback signature for start of PSDU reception events.
typedef void(* PsduTxBeginCallback) (WifiConstPsduMap psduMap, WifiTxVector txVector, double txPowerW)
TracedCallback signature for PSDU transmit events.
Protected Attributes inherited from ns3::WifiPhy
EventId m_endPhyRxEvent
the end of PHY receive event
EventId m_endPreambleDetectionEvent
the end of preamble detection event
EventId m_endRxEvent
the end of receive event
EventId m_endTxEvent
the end of transmit event
InterferenceHelper m_interference
Pointer to InterferenceHelper.
Ptr< UniformRandomVariable > m_random
Provides uniform random variables.
uint32_t m_rxMpduReferenceNumber
A-MPDU reference number to identify all received subframes belonging to the same received A-MPDU.
Ptr< WifiPhyStateHelper > m_state
Pointer to WifiPhyStateHelper.
uint32_t m_txMpduReferenceNumber
A-MPDU reference number to identify all transmitted subframes belonging to the same received A-MPDU.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
802.11 PHY layer model
This PHY implements a model of 802.11a. The model implemented here is based on the model described in "Yet Another Network Simulator", (http://cutebugs.net/files/wns2-yans.pdf).
This PHY model depends on a channel loss and delay model as provided by the ns3::PropagationLossModel and ns3::PropagationDelayModel classes, both of which are members of the ns3::YansWifiChannel class.
Config Paths
ns3::YansWifiPhy is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Phy/$ns3::YansWifiPhy"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/PhyEntities/[i]/$ns3::YansWifiPhy"
No Attributes are defined for this type.
Attributes defined in parent class ns3::WifiPhy
Frequency: The operating center frequency (MHz)
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 0
Flags: construct write read
ChannelWidth: Whether 5MHz, 10MHz, 20MHz, 22MHz, 40MHz, 80 MHz or 160 MHz.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 5:160
Initial value: 20
Flags: construct write read
ChannelNumber: If set to non-zero defined value, will control Frequency and ChannelWidth assignment
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:233
Initial value: 0
Flags: construct write read
RxSensitivity: The energy of a received signal should be higher than this threshold (dBm) for the PHY to detect the signal.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: -101
Flags: construct write read
CcaEdThreshold: The energy of a non Wi-Fi received signal should be higher than this threshold (dBm) to allow the PHY layer to declare CCA BUSY state. This check is performed on the 20 MHz primary channel only.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: -62
Flags: construct write read
TxGain: Transmission gain (dB).
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0
Flags: construct write read
RxGain: Reception gain (dB).
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0
Flags: construct write read
TxPowerLevels: Number of transmission power levels available between TxPowerStart and TxPowerEnd included.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Initial value: 1
Flags: construct write read
TxPowerEnd: Maximum available transmission level (dBm).
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 16.0206
Flags: construct write read
TxPowerStart: Minimum available transmission level (dBm).
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 16.0206
Flags: construct write read
RxNoiseFigure: Loss (dB) in the Signal-to-Noise-Ratio due to non-idealities in the receiver. According to Wikipedia (http://en.wikipedia.org/wiki/Noise_figure), this is "the difference in decibels (dB) between the noise output of the actual receiver to the noise output of an ideal receiver with the same overall gain and bandwidth when the receivers are connected to sources at the standard noise temperature T0 (usually 290 K)".
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 7
Flags: construct write
State: The state of the PHY layer.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::WifiPhyStateHelper>
Initial value: 0x0
Flags: construct write read
ChannelSwitchDelay: Delay between two short frames transmitted on different frequencies.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +250000ns
Flags: construct write read
Antennas: The number of antennas on the device.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 1:8
Initial value: 1
Flags: construct write read
MaxSupportedTxSpatialStreams: The maximum number of supported TX spatial streams.This parameter is only valuable for 802.11n/ac/ax STAs and APs.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 1:8
Initial value: 1
Flags: construct write read
MaxSupportedRxSpatialStreams: The maximum number of supported RX spatial streams.This parameter is only valuable for 802.11n/ac/ax STAs and APs.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 1:8
Initial value: 1
Flags: construct write read
ShortPlcpPreambleSupported: Whether or not short PHY preamble is supported.This parameter is only valuable for 802.11b STAs and APs.Note: 802.11g APs and STAs always support short PHY preamble.
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
FrameCaptureModel: Ptr to an object that implements the frame capture model
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::FrameCaptureModel>
Initial value: 0x0
Flags: construct write read
PreambleDetectionModel: Ptr to an object that implements the preamble detection model
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::PreambleDetectionModel>
Initial value: 0x0
Flags: construct write read
PostReceptionErrorModel: An optional packet error model can be added to the receive packet process after any propagation-based (SNR-based) error models have been applied. Typically this is used to force specific packet drops, for testing purposes.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::ErrorModel>
Initial value: 0x0
Flags: construct write read
Sifs: The duration of the Short Interframe Space. NOTE that the default value is overwritten by the value defined by the standard; if you want to set this attribute, you have to do it after that the PHY object is initialized.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
Slot: The duration of a slot. NOTE that the default value is overwritten by the value defined by the standard; if you want to set this attribute, you have to do it after that the PHY object is initialized.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
Pifs: The duration of the PCF Interframe Space. NOTE that the default value is overwritten by the value defined by the standard; if you want to set this attribute, you have to do it after that the PHY object is initialized.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
No TraceSources are defined for this type.
TraceSources defined in parent class ns3::WifiPhy
PhyTxBegin: Trace source indicating a packet has begun transmitting over the channel medium
Callback signature: ns3::Packet::TracedCallback
PhyTxPsduBegin: Trace source indicating a PSDU has begun transmitting over the channel medium
Callback signature: ns3::WifiPhy::PsduTxBeginCallback
PhyTxEnd: Trace source indicating a packet has been completely transmitted over the channel.
Callback signature: ns3::Packet::TracedCallback
PhyTxDrop: Trace source indicating a packet has been dropped by the device during transmission
Callback signature: ns3::Packet::TracedCallback
PhyRxBegin: Trace source indicating a packet has begun being received from the channel medium by the device
Callback signature: ns3::Packet::TracedCallback
PhyRxPayloadBegin: Trace source indicating the reception of the payload of a PPDU has begun
Callback signature: ns3::WifiPhy::PhyRxPayloadBeginTracedCallback
PhyRxEnd: Trace source indicating a packet has been completely received from the channel medium by the device
Callback signature: ns3::Packet::TracedCallback
PhyRxDrop: Trace source indicating a packet has been dropped by the device during reception
Callback signature: ns3::Packet::TracedCallback
MonitorSnifferRx: Trace source simulating a wifi device in monitor mode sniffing all received frames
Callback signature: ns3::WifiPhy::MonitorSnifferRxTracedCallback
MonitorSnifferTx: Trace source simulating the capability of a wifi device in monitor mode to sniff all frames being transmitted
Callback signature: ns3::WifiPhy::MonitorSnifferTxTracedCallback
EndOfHePreamble: Trace source indicating the end of the 802.11ax preamble (after training fields)
Callback signature: ns3::WifiPhy::EndOfHePreambleTracedCallback
Size of this type is 896 bytes (on a 64-bit architecture).
Definition at line 48 of file yans-wifi-phy.h.
Constructor & Destructor Documentation
YansWifiPhy()
ns3::YansWifiPhy::YansWifiPhy ()
Definition at line 45 of file yans-wifi-phy.cc.
References ns3::InterferenceHelper::AddBand(), ns3::WifiPhy::m_interference, and NS_LOG_FUNCTION.
~YansWifiPhy()
ns3::YansWifiPhy::~YansWifiPhy () virtual
Definition at line 55 of file yans-wifi-phy.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::YansWifiPhy::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::WifiPhy.
Definition at line 61 of file yans-wifi-phy.cc.
References ns3::WifiPhy::DoDispose(), m_channel, and NS_LOG_FUNCTION.
GetChannel()
Ptr< Channel > ns3::YansWifiPhy::GetChannel (void) const virtual
Return the Channel this WifiPhy is connected to.
Returns
the Channel this WifiPhy is connected to
Implements ns3::WifiPhy.
Definition at line 69 of file yans-wifi-phy.cc.
References m_channel.
GetTypeId()
TypeId ns3::YansWifiPhy::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 35 of file yans-wifi-phy.cc.
References ns3::TypeId::SetParent().
SetChannel()
void ns3::YansWifiPhy::SetChannel (const Ptr< YansWifiChannel > channel)
Set the YansWifiChannel this YansWifiPhy is to be connected to.
Parameters
channel the YansWifiChannel this YansWifiPhy is to be connected to
Definition at line 75 of file yans-wifi-phy.cc.
References third::channel, m_channel, and NS_LOG_FUNCTION.
Referenced by DcfImmediateAccessBroadcastTestCase::DoRun(), and Bug2831TestCase::DoRun().
StartTx()
void ns3::YansWifiPhy::StartTx (Ptr< WifiPpdu > ppdu) virtual
Parameters
ppdu the PPDU to send
Implements ns3::WifiPhy.
Definition at line 83 of file yans-wifi-phy.cc.
References ns3::WifiPhy::GetPowerDbm(), ns3::WifiPhy::GetTxGain(), ns3::WifiPhy::GetTxPowerForTransmission(), ns3::WifiTxVector::GetTxPowerLevel(), m_channel, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Member Data Documentation
m_channel
Ptr<YansWifiChannel> ns3::YansWifiPhy::m_channel private
YansWifiChannel that this YansWifiPhy is connected to.
Definition at line 77 of file yans-wifi-phy.h.
Referenced by DoDispose(), GetChannel(), SetChannel(), and StartTx().
The documentation for this class was generated from the following files:
src/wifi/model/yans-wifi-phy.h
src/wifi/model/yans-wifi-phy.cc