ns-3: ns3::Asn1Header Class Reference
ns3::Asn1Header Class Reference abstract
This class has the purpose to encode Information Elements according to ASN.1 syntax, as defined in ITU-T X-691.
#include "lte-asn1-header.h"
Public Member Functions
Asn1Header ()
virtual ~Asn1Header ()
virtual uint32_t Deserialize (Buffer::Iterator bIterator)=0
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint32_t GetSerializedSize (void) const
virtual void PreSerialize (void) const =0
This function serializes class attributes to m_serializationResult local Buffer.
virtual void Print (std::ostream &os) const =0
void Serialize (Buffer::Iterator bIterator) const
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
Buffer::Iterator DeserializeBitset (std::bitset< 8 > *data, Buffer::Iterator bIterator)
Deserialize a bitset.
template<int N>
Buffer::Iterator DeserializeBitset (std::bitset< N > *data, Buffer::Iterator bIterator)
Deserialize a bitset.
Buffer::Iterator DeserializeBitstring (std::bitset< 1 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 10 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 16 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 2 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 27 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 28 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 32 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 8 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
template<int N>
Buffer::Iterator DeserializeBitstring (std::bitset< N > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBoolean (bool *value, Buffer::Iterator bIterator)
Deserialize a boolean.
Buffer::Iterator DeserializeChoice (int numOptions, bool isExtensionMarkerPresent, int *selectedOption, Buffer::Iterator bIterator)
Deserialize a Choice (set of options)
Buffer::Iterator DeserializeEnum (int numElems, int *selectedElem, Buffer::Iterator bIterator)
Deserialize an Enum.
Buffer::Iterator DeserializeInteger (int *n, int nmin, int nmax, Buffer::Iterator bIterator)
Deserialize an integer.
Buffer::Iterator DeserializeNull (Buffer::Iterator bIterator)
Deserialize nothing (null op)
Buffer::Iterator DeserializeSequence (std::bitset< 0 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 1 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 10 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 11 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 2 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 3 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 4 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 5 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 6 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 7 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 9 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
template<int N>
Buffer::Iterator DeserializeSequence (std::bitset< N > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequenceOf (int *numElems, int nMax, int nMin, Buffer::Iterator bIterator)
Deserialize a Sequence.
void FinalizeSerialization () const
Finalizes an in progress serialization.
template<int N>
void SerializeBitset (std::bitset< N > data) const
Serialize a bitset.
void SerializeBitstring (std::bitset< 1 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 10 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 16 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 2 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 27 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 28 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 32 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 8 > bitstring) const
Serialize a bitstring.
template<int N>
void SerializeBitstring (std::bitset< N > bitstring) const
Serialize a bitstring.
void SerializeBoolean (bool value) const
Serialize a bool.
void SerializeChoice (int numOptions, int selectedOption, bool isExtensionMarkerPresent) const
Serialize a Choice (set of options)
void SerializeEnum (int numElems, int selectedElem) const
Serialize an Enum.
void SerializeInteger (int n, int nmin, int nmax) const
Serialize an Integer.
void SerializeNull () const
Serialize nothing (null op)
void SerializeSequence (std::bitset< 0 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 1 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 10 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 11 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 2 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 3 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 4 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 5 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 6 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 7 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 9 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
template<int N>
void SerializeSequence (std::bitset< N > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequenceOf (int numElems, int nMax, int nMin) const
Serialize a Sequence.
void WriteOctet (uint8_t octet) const
Function to write in m_serializationResult, after resizing its size.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes
bool m_isDataSerialized
true if data is serialized
uint8_t m_numSerializationPendingBits
number of pending bits
uint8_t m_serializationPendingBits
pending bits
Buffer m_serializationResult
serialization result
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class has the purpose to encode Information Elements according to ASN.1 syntax, as defined in ITU-T X-691.
Introspection did not find any typical Config paths.
IMPORTANT: The encoding is done following the UNALIGNED variant.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 48 bytes (on a 64-bit architecture).
Definition at line 36 of file lte-asn1-header.h.
Constructor & Destructor Documentation
Asn1Header()
ns3::Asn1Header::Asn1Header ()
Definition at line 50 of file lte-asn1-header.cc.
References m_isDataSerialized, m_numSerializationPendingBits, and m_serializationPendingBits.
~Asn1Header()
ns3::Asn1Header::~Asn1Header () virtual
Definition at line 57 of file lte-asn1-header.cc.
Member Function Documentation
Deserialize()
virtual uint32_t ns3::Asn1Header::Deserialize (Buffer::Iterator start) pure virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Implemented in ns3::RrcAsn1Header, ns3::MeasurementReportHeader, ns3::RrcConnectionRejectHeader, ns3::RrcConnectionReleaseHeader, ns3::RrcConnectionReestablishmentRejectHeader, ns3::RrcConnectionReestablishmentCompleteHeader, ns3::RrcConnectionReestablishmentHeader, ns3::RrcConnectionReestablishmentRequestHeader, ns3::HandoverPreparationInfoHeader, ns3::RrcConnectionReconfigurationHeader, ns3::RrcConnectionReconfigurationCompleteHeader, ns3::RrcConnectionSetupCompleteHeader, ns3::RrcConnectionSetupHeader, ns3::RrcConnectionRequestHeader, ns3::RrcDlCcchMessage, ns3::RrcUlCcchMessage, ns3::RrcDlDcchMessage, and ns3::RrcUlDcchMessage.
DeserializeBitset() [1/2]
Buffer::Iterator ns3::Asn1Header::DeserializeBitset (std::bitset< 8 > * data, Buffer::Iterator bIterator) protected
Deserialize a bitset.
Parameters
data buffer to store the result
bIterator buffer iterator
Returns
the modified buffer iterator
DeserializeBitset() [2/2]
template<int N> Buffer::Iterator ns3::Asn1Header::DeserializeBitset (std::bitset< N > * data, Buffer::Iterator bIterator) protected
Deserialize a bitset.
Parameters
data buffer to store the result
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 428 of file lte-asn1-header.cc.
References data, m_numSerializationPendingBits, m_serializationPendingBits, and ns3::Buffer::Iterator::ReadU8().
DeserializeBitstring() [1/9]
Buffer::Iterator ns3::Asn1Header::DeserializeBitstring (std::bitset< 1 > * bitstring, Buffer::Iterator bIterator) protected
Deserialize a bitstring.
Parameters
bitstring buffer to store the result
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 486 of file lte-asn1-header.cc.
References data.
DeserializeBitstring() [2/9]
Buffer::Iterator ns3::Asn1Header::DeserializeBitstring (std::bitset< 10 > * bitstring, Buffer::Iterator bIterator) protected
Deserialize a bitstring.
Parameters
bitstring buffer to store the result
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 501 of file lte-asn1-header.cc.
References data.
DeserializeBitstring() [3/9]
Buffer::Iterator ns3::Asn1Header::DeserializeBitstring (std::bitset< 16 > * bitstring, Buffer::Iterator bIterator) protected
Deserialize a bitstring.
Parameters
bitstring buffer to store the result
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 506 of file lte-asn1-header.cc.
References data.
DeserializeBitstring() [4/9]
Buffer::Iterator ns3::Asn1Header::DeserializeBitstring (std::bitset< 2 > * bitstring, Buffer::Iterator bIterator) protected
Deserialize a bitstring.
Parameters
bitstring buffer to store the result
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 491 of file lte-asn1-header.cc.
References data.
DeserializeBitstring() [5/9]
Buffer::Iterator ns3::Asn1Header::DeserializeBitstring (std::bitset< 27 > * bitstring, Buffer::Iterator bIterator) protected
Deserialize a bitstring.
Parameters
bitstring buffer to store the result
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 511 of file lte-asn1-header.cc.
References data.
DeserializeBitstring() [6/9]
Buffer::Iterator ns3::Asn1Header::DeserializeBitstring (std::bitset< 28 > * bitstring, Buffer::Iterator bIterator) protected
Deserialize a bitstring.
Parameters
bitstring buffer to store the result
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 516 of file lte-asn1-header.cc.
References data.
DeserializeBitstring() [7/9]
Buffer::Iterator ns3::Asn1Header::DeserializeBitstring (std::bitset< 32 > * bitstring, Buffer::Iterator bIterator) protected
Deserialize a bitstring.
Parameters
bitstring buffer to store the result
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 521 of file lte-asn1-header.cc.
References data.
DeserializeBitstring() [8/9]
Buffer::Iterator ns3::Asn1Header::DeserializeBitstring (std::bitset< 8 > * bitstring, Buffer::Iterator bIterator) protected
Deserialize a bitstring.
Parameters
bitstring buffer to store the result
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 496 of file lte-asn1-header.cc.
References data.
DeserializeBitstring() [9/9]
template<int N> Buffer::Iterator ns3::Asn1Header::DeserializeBitstring (std::bitset< N > * bitstring, Buffer::Iterator bIterator) protected
Deserialize a bitstring.
Parameters
bitstring buffer to store the result
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 481 of file lte-asn1-header.cc.
References data.
Referenced by ns3::RrcConnectionRequestHeader::Deserialize(), ns3::RrcConnectionReconfigurationHeader::Deserialize(), ns3::HandoverPreparationInfoHeader::Deserialize(), ns3::RrcConnectionReestablishmentRequestHeader::Deserialize(), ns3::RrcAsn1Header::DeserializeMeasConfig(), ns3::RrcAsn1Header::DeserializeMeasResults(), and ns3::RrcAsn1Header::DeserializeSystemInformationBlockType1().
DeserializeBoolean()
Buffer::Iterator ns3::Asn1Header::DeserializeBoolean (bool * value, Buffer::Iterator bIterator) protected
Deserialize a boolean.
Parameters
value buffer to store the result
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 526 of file lte-asn1-header.cc.
Referenced by DeserializeChoice(), ns3::RrcAsn1Header::DeserializeMeasConfig(), ns3::RrcAsn1Header::DeserializePhysicalConfigDedicated(), ns3::RrcAsn1Header::DeserializePhysicalConfigDedicatedSCell(), ns3::RrcAsn1Header::DeserializeRadioResourceConfigCommon(), ns3::RrcAsn1Header::DeserializeRadioResourceConfigCommonSib(), DeserializeSequence(), and ns3::RrcAsn1Header::DeserializeSystemInformationBlockType1().
DeserializeChoice()
Buffer::Iterator ns3::Asn1Header::DeserializeChoice (int numOptions, bool isExtensionMarkerPresent, int * selectedOption, Buffer::Iterator bIterator) protected
Deserialize a Choice (set of options)
Parameters
numOptions number of options
isExtensionMarkerPresent true if extension mark is present
selectedOption buffer to store the result
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 668 of file lte-asn1-header.cc.
References DeserializeBoolean(), and DeserializeInteger().
Referenced by ns3::RrcConnectionRequestHeader::Deserialize(), ns3::RrcConnectionSetupHeader::Deserialize(), ns3::RrcConnectionSetupCompleteHeader::Deserialize(), ns3::RrcConnectionReconfigurationCompleteHeader::Deserialize(), ns3::RrcConnectionReconfigurationHeader::Deserialize(), ns3::HandoverPreparationInfoHeader::Deserialize(), ns3::RrcConnectionReestablishmentRequestHeader::Deserialize(), ns3::RrcConnectionReestablishmentHeader::Deserialize(), ns3::RrcConnectionReestablishmentCompleteHeader::Deserialize(), ns3::RrcConnectionReestablishmentRejectHeader::Deserialize(), ns3::RrcConnectionReleaseHeader::Deserialize(), ns3::RrcConnectionRejectHeader::Deserialize(), ns3::MeasurementReportHeader::Deserialize(), ns3::RrcDlCcchMessage::DeserializeDlCcchMessage(), ns3::RrcDlDcchMessage::DeserializeDlDcchMessage(), ns3::RrcAsn1Header::DeserializeDrbToAddModList(), ns3::RrcAsn1Header::DeserializeMeasConfig(), ns3::RrcAsn1Header::DeserializeMeasResults(), ns3::RrcAsn1Header::DeserializePhysicalConfigDedicated(), ns3::RrcAsn1Header::DeserializePhysicalConfigDedicatedSCell(), ns3::RrcAsn1Header::DeserializeRadioResourceConfigCommonSib(), ns3::RrcAsn1Header::DeserializeSrbToAddModList(), ns3::RrcAsn1Header::DeserializeThresholdEutra(), ns3::RrcUlCcchMessage::DeserializeUlCcchMessage(), and ns3::RrcUlDcchMessage::DeserializeUlDcchMessage().
DeserializeEnum()
Buffer::Iterator ns3::Asn1Header::DeserializeEnum (int numElems, int * selectedElem, Buffer::Iterator bIterator) protected
Deserialize an Enum.
Parameters
numElems number of elements in the enum
selectedElem buffer to store the result
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 678 of file lte-asn1-header.cc.
References DeserializeInteger().
Referenced by ns3::RrcConnectionRequestHeader::Deserialize(), ns3::RrcConnectionReconfigurationHeader::Deserialize(), ns3::HandoverPreparationInfoHeader::Deserialize(), ns3::RrcConnectionReestablishmentRequestHeader::Deserialize(), ns3::RrcConnectionReleaseHeader::Deserialize(), ns3::RrcAsn1Header::DeserializeDrbToAddModList(), ns3::RrcAsn1Header::DeserializeLogicalChannelConfig(), ns3::RrcAsn1Header::DeserializeMeasConfig(), ns3::RrcAsn1Header::DeserializePhysicalConfigDedicated(), ns3::RrcAsn1Header::DeserializePhysicalConfigDedicatedSCell(), ns3::RrcAsn1Header::DeserializePlmnIdentity(), ns3::RrcAsn1Header::DeserializeQoffsetRange(), ns3::RrcAsn1Header::DeserializeRachConfigCommon(), ns3::RrcAsn1Header::DeserializeRadioResourceConfigCommon(), ns3::RrcAsn1Header::DeserializeRadioResourceConfigCommonSib(), ns3::RrcAsn1Header::DeserializeSystemInformationBlockType1(), and ns3::RrcAsn1Header::DeserializeSystemInformationBlockType2().
DeserializeInteger()
Buffer::Iterator ns3::Asn1Header::DeserializeInteger (int * n, int nmin, int nmax, Buffer::Iterator bIterator) protected
Deserialize an integer.
Parameters
n buffer to store the result
nmin min value to serialize
nmax max value to serialize
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 534 of file lte-asn1-header.cc.
References sample-rng-plot::n.
Referenced by ns3::RrcConnectionSetupHeader::Deserialize(), ns3::RrcConnectionSetupCompleteHeader::Deserialize(), ns3::RrcConnectionReconfigurationCompleteHeader::Deserialize(), ns3::RrcConnectionReconfigurationHeader::Deserialize(), ns3::HandoverPreparationInfoHeader::Deserialize(), ns3::RrcConnectionReestablishmentRequestHeader::Deserialize(), ns3::RrcConnectionReestablishmentHeader::Deserialize(), ns3::RrcConnectionReestablishmentCompleteHeader::Deserialize(), ns3::RrcConnectionReleaseHeader::Deserialize(), ns3::RrcConnectionRejectHeader::Deserialize(), ns3::RrcAsn1Header::DeserializeCellIdentification(), DeserializeChoice(), ns3::RrcAsn1Header::DeserializeDrbToAddModList(), DeserializeEnum(), ns3::RrcAsn1Header::DeserializeLogicalChannelConfig(), ns3::RrcAsn1Header::DeserializeMeasConfig(), ns3::RrcAsn1Header::DeserializeMeasResults(), ns3::RrcAsn1Header::DeserializeNonCriticalExtensionConfig(), ns3::RrcAsn1Header::DeserializePhysicalConfigDedicated(), ns3::RrcAsn1Header::DeserializePhysicalConfigDedicatedSCell(), ns3::RrcAsn1Header::DeserializePlmnIdentity(), ns3::RrcAsn1Header::DeserializeRachConfigCommon(), ns3::RrcAsn1Header::DeserializeRadioResourceConfigCommon(), ns3::RrcAsn1Header::DeserializeRadioResourceConfigCommonSCell(), ns3::RrcAsn1Header::DeserializeRadioResourceConfigCommonSib(), ns3::RrcAsn1Header::DeserializeRadioResourceConfigDedicated(), DeserializeSequenceOf(), ns3::RrcAsn1Header::DeserializeSrbToAddModList(), ns3::RrcAsn1Header::DeserializeSystemInformationBlockType1(), ns3::RrcAsn1Header::DeserializeSystemInformationBlockType2(), and ns3::RrcAsn1Header::DeserializeThresholdEutra().
DeserializeNull()
Buffer::Iterator ns3::Asn1Header::DeserializeNull (Buffer::Iterator bIterator) protected
Deserialize nothing (null op)
Parameters
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 750 of file lte-asn1-header.cc.
Referenced by ns3::RrcConnectionSetupHeader::Deserialize(), ns3::RrcConnectionSetupCompleteHeader::Deserialize(), ns3::RrcConnectionReconfigurationHeader::Deserialize(), ns3::HandoverPreparationInfoHeader::Deserialize(), ns3::RrcConnectionReestablishmentHeader::Deserialize(), ns3::RrcConnectionReleaseHeader::Deserialize(), ns3::RrcConnectionRejectHeader::Deserialize(), ns3::MeasurementReportHeader::Deserialize(), ns3::RrcAsn1Header::DeserializeMeasConfig(), ns3::RrcAsn1Header::DeserializePhysicalConfigDedicated(), ns3::RrcAsn1Header::DeserializePhysicalConfigDedicatedSCell(), ns3::RrcAsn1Header::DeserializeRadioResourceConfigCommonSib(), and ns3::RrcAsn1Header::DeserializeSrbToAddModList().
DeserializeSequence() [1/12]
Buffer::Iterator ns3::Asn1Header::DeserializeSequence (std::bitset< 0 > * optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator) protected
Deserialize a sequence.
Parameters
optionalOrDefaultMask buffer to store the result
isExtensionMarkerPresent true if Extension Marker is present
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 695 of file lte-asn1-header.cc.
DeserializeSequence() [2/12]
Buffer::Iterator ns3::Asn1Header::DeserializeSequence (std::bitset< 1 > * optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator) protected
Deserialize a sequence.
Parameters
optionalOrDefaultMask buffer to store the result
isExtensionMarkerPresent true if Extension Marker is present
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 700 of file lte-asn1-header.cc.
DeserializeSequence() [3/12]
Buffer::Iterator ns3::Asn1Header::DeserializeSequence (std::bitset< 10 > * optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator) protected
Deserialize a sequence.
Parameters
optionalOrDefaultMask buffer to store the result
isExtensionMarkerPresent true if Extension Marker is present
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 740 of file lte-asn1-header.cc.
DeserializeSequence() [4/12]
Buffer::Iterator ns3::Asn1Header::DeserializeSequence (std::bitset< 11 > * optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator) protected
Deserialize a sequence.
Parameters
optionalOrDefaultMask buffer to store the result
isExtensionMarkerPresent true if Extension Marker is present
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 745 of file lte-asn1-header.cc.
DeserializeSequence() [5/12]
Buffer::Iterator ns3::Asn1Header::DeserializeSequence (std::bitset< 2 > * optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator) protected
Deserialize a sequence.
Parameters
optionalOrDefaultMask buffer to store the result
isExtensionMarkerPresent true if Extension Marker is present
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 705 of file lte-asn1-header.cc.
DeserializeSequence() [6/12]
Buffer::Iterator ns3::Asn1Header::DeserializeSequence (std::bitset< 3 > * optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator) protected
Deserialize a sequence.
Parameters
optionalOrDefaultMask buffer to store the result
isExtensionMarkerPresent true if Extension Marker is present
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 710 of file lte-asn1-header.cc.
DeserializeSequence() [7/12]
Buffer::Iterator ns3::Asn1Header::DeserializeSequence (std::bitset< 4 > * optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator) protected
Deserialize a sequence.
Parameters
optionalOrDefaultMask buffer to store the result
isExtensionMarkerPresent true if Extension Marker is present
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 715 of file lte-asn1-header.cc.
DeserializeSequence() [8/12]
Buffer::Iterator ns3::Asn1Header::DeserializeSequence (std::bitset< 5 > * optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator) protected
Deserialize a sequence.
Parameters
optionalOrDefaultMask buffer to store the result
isExtensionMarkerPresent true if Extension Marker is present
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 720 of file lte-asn1-header.cc.
DeserializeSequence() [9/12]
Buffer::Iterator ns3::Asn1Header::DeserializeSequence (std::bitset< 6 > * optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator) protected
Deserialize a sequence.
Parameters
optionalOrDefaultMask buffer to store the result
isExtensionMarkerPresent true if Extension Marker is present
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 725 of file lte-asn1-header.cc.
DeserializeSequence() [10/12]
Buffer::Iterator ns3::Asn1Header::DeserializeSequence (std::bitset< 7 > * optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator) protected
Deserialize a sequence.
Parameters
optionalOrDefaultMask buffer to store the result
isExtensionMarkerPresent true if Extension Marker is present
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 730 of file lte-asn1-header.cc.
DeserializeSequence() [11/12]
Buffer::Iterator ns3::Asn1Header::DeserializeSequence (std::bitset< 9 > * optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator) protected
Deserialize a sequence.
Parameters
optionalOrDefaultMask buffer to store the result
isExtensionMarkerPresent true if Extension Marker is present
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 735 of file lte-asn1-header.cc.
DeserializeSequence() [12/12]
template<int N> Buffer::Iterator ns3::Asn1Header::DeserializeSequence (std::bitset< N > * optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator) protected
Deserialize a sequence.
Parameters
optionalOrDefaultMask buffer to store the result
isExtensionMarkerPresent true if Extension Marker is present
bIterator buffer iterator
Returns
the modified buffer iterator Deserialize a sequence
Parameters
optionalOrDefaultMask buffer to store the result
isExtensionMarkerPresent true if Extension Marker is present
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 684 of file lte-asn1-header.cc.
References DeserializeBoolean().
Referenced by ns3::RrcConnectionRequestHeader::Deserialize(), ns3::RrcConnectionSetupHeader::Deserialize(), ns3::RrcConnectionSetupCompleteHeader::Deserialize(), ns3::RrcConnectionReconfigurationCompleteHeader::Deserialize(), ns3::RrcConnectionReconfigurationHeader::Deserialize(), ns3::HandoverPreparationInfoHeader::Deserialize(), ns3::RrcConnectionReestablishmentRequestHeader::Deserialize(), ns3::RrcConnectionReestablishmentHeader::Deserialize(), ns3::RrcConnectionReestablishmentCompleteHeader::Deserialize(), ns3::RrcConnectionReestablishmentRejectHeader::Deserialize(), ns3::RrcConnectionReleaseHeader::Deserialize(), ns3::RrcConnectionRejectHeader::Deserialize(), ns3::MeasurementReportHeader::Deserialize(), ns3::RrcAsn1Header::DeserializeCellIdentification(), ns3::RrcDlCcchMessage::DeserializeDlCcchMessage(), ns3::RrcDlDcchMessage::DeserializeDlDcchMessage(), ns3::RrcAsn1Header::DeserializeDrbToAddModList(), ns3::RrcAsn1Header::DeserializeLogicalChannelConfig(), ns3::RrcAsn1Header::DeserializeMeasConfig(), ns3::RrcAsn1Header::DeserializeMeasResults(), ns3::RrcAsn1Header::DeserializeNonCriticalExtensionConfig(), ns3::RrcAsn1Header::DeserializePhysicalConfigDedicated(), ns3::RrcAsn1Header::DeserializePhysicalConfigDedicatedSCell(), ns3::RrcAsn1Header::DeserializePlmnIdentity(), ns3::RrcAsn1Header::DeserializeRachConfigCommon(), ns3::RrcAsn1Header::DeserializeRadioResourceConfigCommon(), ns3::RrcAsn1Header::DeserializeRadioResourceConfigCommonSCell(), ns3::RrcAsn1Header::DeserializeRadioResourceConfigCommonSib(), ns3::RrcAsn1Header::DeserializeRadioResourceConfigDedicated(), ns3::RrcAsn1Header::DeserializeRadioResourceConfigDedicatedSCell(), ns3::RrcAsn1Header::DeserializeSrbToAddModList(), ns3::RrcAsn1Header::DeserializeSystemInformationBlockType1(), ns3::RrcAsn1Header::DeserializeSystemInformationBlockType2(), ns3::RrcUlCcchMessage::DeserializeUlCcchMessage(), and ns3::RrcUlDcchMessage::DeserializeUlDcchMessage().
DeserializeSequenceOf()
Buffer::Iterator ns3::Asn1Header::DeserializeSequenceOf (int * numElems, int nMax, int nMin, Buffer::Iterator bIterator) protected
Deserialize a Sequence.
Parameters
numElems buffer to store the result
nMax max value to serialize
nMin min value to serialize
bIterator buffer iterator
Returns
the modified buffer iterator
Definition at line 755 of file lte-asn1-header.cc.
References DeserializeInteger().
Referenced by ns3::HandoverPreparationInfoHeader::Deserialize(), ns3::RrcAsn1Header::DeserializeDrbToAddModList(), ns3::RrcAsn1Header::DeserializeMeasConfig(), ns3::RrcAsn1Header::DeserializeMeasResults(), ns3::RrcAsn1Header::DeserializeNonCriticalExtensionConfig(), ns3::RrcAsn1Header::DeserializePlmnIdentity(), ns3::RrcAsn1Header::DeserializeRadioResourceConfigDedicated(), ns3::RrcAsn1Header::DeserializeSrbToAddModList(), and ns3::RrcAsn1Header::DeserializeSystemInformationBlockType1().
FinalizeSerialization()
void ns3::Asn1Header::FinalizeSerialization () const protected
Finalizes an in progress serialization.
Definition at line 417 of file lte-asn1-header.cc.
References m_isDataSerialized, m_numSerializationPendingBits, and m_serializationPendingBits.
Referenced by ns3::RrcConnectionRequestHeader::PreSerialize(), ns3::RrcConnectionSetupHeader::PreSerialize(), ns3::RrcConnectionSetupCompleteHeader::PreSerialize(), ns3::RrcConnectionReconfigurationCompleteHeader::PreSerialize(), ns3::RrcConnectionReconfigurationHeader::PreSerialize(), ns3::HandoverPreparationInfoHeader::PreSerialize(), ns3::RrcConnectionReestablishmentRequestHeader::PreSerialize(), ns3::RrcConnectionReestablishmentHeader::PreSerialize(), ns3::RrcConnectionReestablishmentCompleteHeader::PreSerialize(), ns3::RrcConnectionReestablishmentRejectHeader::PreSerialize(), ns3::RrcConnectionReleaseHeader::PreSerialize(), ns3::RrcConnectionRejectHeader::PreSerialize(), and ns3::MeasurementReportHeader::PreSerialize().
GetInstanceTypeId()
TypeId ns3::Asn1Header::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Reimplemented in ns3::RrcAsn1Header.
Definition at line 45 of file lte-asn1-header.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::Asn1Header::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 62 of file lte-asn1-header.cc.
References ns3::Buffer::GetSize(), m_isDataSerialized, m_serializationResult, and PreSerialize().
Referenced by ns3::RrcConnectionRequestHeader::Deserialize(), ns3::RrcConnectionSetupHeader::Deserialize(), ns3::RrcConnectionSetupCompleteHeader::Deserialize(), ns3::RrcConnectionReconfigurationCompleteHeader::Deserialize(), ns3::RrcConnectionReconfigurationHeader::Deserialize(), ns3::HandoverPreparationInfoHeader::Deserialize(), ns3::RrcConnectionReestablishmentRequestHeader::Deserialize(), ns3::RrcConnectionReestablishmentHeader::Deserialize(), ns3::RrcConnectionReestablishmentCompleteHeader::Deserialize(), ns3::RrcConnectionReestablishmentRejectHeader::Deserialize(), ns3::RrcConnectionReleaseHeader::Deserialize(), ns3::RrcConnectionRejectHeader::Deserialize(), and ns3::MeasurementReportHeader::Deserialize().
GetTypeId()
TypeId ns3::Asn1Header::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 35 of file lte-asn1-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
PreSerialize()
virtual void ns3::Asn1Header::PreSerialize (void) const pure virtual
This function serializes class attributes to m_serializationResult local Buffer.
As ASN1 encoding produces a bitstream that does not have a fixed length, this function is needed to store the result, so its length can be retrieved with Header::GetSerializedSize() function. This method is pure virtual in this class (needs to be implemented in child classes) as the meaningful information elements are in the subclasses.
Implemented in ns3::RrcAsn1Header, ns3::MeasurementReportHeader, ns3::RrcConnectionRejectHeader, ns3::RrcConnectionReleaseHeader, ns3::RrcConnectionReestablishmentRejectHeader, ns3::RrcConnectionReestablishmentCompleteHeader, ns3::RrcConnectionReestablishmentHeader, ns3::RrcConnectionReestablishmentRequestHeader, ns3::HandoverPreparationInfoHeader, ns3::RrcConnectionReconfigurationHeader, ns3::RrcConnectionReconfigurationCompleteHeader, ns3::RrcConnectionSetupCompleteHeader, ns3::RrcConnectionSetupHeader, ns3::RrcConnectionRequestHeader, ns3::RrcDlCcchMessage, ns3::RrcUlCcchMessage, ns3::RrcDlDcchMessage, and ns3::RrcUlDcchMessage.
Referenced by GetSerializedSize(), and Serialize().
Print()
virtual void ns3::Asn1Header::Print (std::ostream & os) const pure virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Implemented in ns3::MeasurementReportHeader, ns3::RrcConnectionRejectHeader, ns3::RrcConnectionReleaseHeader, ns3::RrcConnectionReestablishmentRejectHeader, ns3::RrcConnectionReestablishmentCompleteHeader, ns3::RrcConnectionReestablishmentHeader, ns3::RrcConnectionReestablishmentRequestHeader, ns3::HandoverPreparationInfoHeader, ns3::RrcConnectionReconfigurationHeader, ns3::RrcConnectionReconfigurationCompleteHeader, ns3::RrcConnectionSetupCompleteHeader, ns3::RrcConnectionSetupHeader, ns3::RrcConnectionRequestHeader, ns3::RrcDlCcchMessage, ns3::RrcUlCcchMessage, ns3::RrcDlDcchMessage, ns3::RrcUlDcchMessage, and ns3::RrcAsn1Header.
Serialize()
void ns3::Asn1Header::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 71 of file lte-asn1-header.cc.
References ns3::Buffer::Begin(), ns3::Buffer::End(), m_isDataSerialized, m_serializationResult, PreSerialize(), and ns3::Buffer::Iterator::Write().
SerializeBitset()
template<int N> void ns3::Asn1Header::SerializeBitset (std::bitset< N > data) const protected
Serialize a bitset.
Parameters
data data to serialize
Definition at line 89 of file lte-asn1-header.cc.
References data, m_numSerializationPendingBits, m_serializationPendingBits, and WriteOctet().
SerializeBitstring() [1/9]
void ns3::Asn1Header::SerializeBitstring (std::bitset< 1 > bitstring) const protected
Serialize a bitstring.
Parameters
bitstring bitstring to serialize
Definition at line 179 of file lte-asn1-header.cc.
References data.
SerializeBitstring() [2/9]
void ns3::Asn1Header::SerializeBitstring (std::bitset< 10 > bitstring) const protected
Serialize a bitstring.
Parameters
bitstring bitstring to serialize
Definition at line 194 of file lte-asn1-header.cc.
References data.
SerializeBitstring() [3/9]
void ns3::Asn1Header::SerializeBitstring (std::bitset< 16 > bitstring) const protected
Serialize a bitstring.
Parameters
bitstring bitstring to serialize
Definition at line 199 of file lte-asn1-header.cc.
References data.
SerializeBitstring() [4/9]
void ns3::Asn1Header::SerializeBitstring (std::bitset< 2 > bitstring) const protected
Serialize a bitstring.
Parameters
bitstring bitstring to serialize
Definition at line 184 of file lte-asn1-header.cc.
References data.
SerializeBitstring() [5/9]
void ns3::Asn1Header::SerializeBitstring (std::bitset< 27 > bitstring) const protected
Serialize a bitstring.
Parameters
bitstring bitstring to serialize
Definition at line 204 of file lte-asn1-header.cc.
References data.
SerializeBitstring() [6/9]
void ns3::Asn1Header::SerializeBitstring (std::bitset< 28 > bitstring) const protected
Serialize a bitstring.
Parameters
bitstring bitstring to serialize
Definition at line 209 of file lte-asn1-header.cc.
References data.
SerializeBitstring() [7/9]
void ns3::Asn1Header::SerializeBitstring (std::bitset< 32 > bitstring) const protected
Serialize a bitstring.
Parameters
bitstring bitstring to serialize
Definition at line 214 of file lte-asn1-header.cc.
References data.
SerializeBitstring() [8/9]
void ns3::Asn1Header::SerializeBitstring (std::bitset< 8 > bitstring) const protected
Serialize a bitstring.
Parameters
bitstring bitstring to serialize
Definition at line 189 of file lte-asn1-header.cc.
References data.
SerializeBitstring() [9/9]
template<int N> void ns3::Asn1Header::SerializeBitstring (std::bitset< N > bitstring) const protected
Serialize a bitstring.
Parameters
bitstring bitstring to serialize
Definition at line 173 of file lte-asn1-header.cc.
References data.
Referenced by ns3::RrcConnectionRequestHeader::PreSerialize(), ns3::RrcConnectionReconfigurationHeader::PreSerialize(), ns3::HandoverPreparationInfoHeader::PreSerialize(), ns3::RrcConnectionReestablishmentRequestHeader::PreSerialize(), ns3::RrcAsn1Header::SerializeMeasConfig(), ns3::RrcAsn1Header::SerializeMeasResults(), and ns3::RrcAsn1Header::SerializeSystemInformationBlockType1().
SerializeBoolean()
void ns3::Asn1Header::SerializeBoolean (bool value) const protected
Serialize a bool.
Parameters
value value to serialize
Definition at line 219 of file lte-asn1-header.cc.
Referenced by SerializeChoice(), ns3::RrcAsn1Header::SerializeMeasConfig(), ns3::RrcAsn1Header::SerializePhysicalConfigDedicated(), ns3::RrcAsn1Header::SerializePhysicalConfigDedicatedSCell(), ns3::RrcAsn1Header::SerializeRadioResourceConfigCommon(), ns3::RrcAsn1Header::SerializeRadioResourceConfigCommonSib(), SerializeSequence(), and ns3::RrcAsn1Header::SerializeSystemInformationBlockType1().
SerializeChoice()
void ns3::Asn1Header::SerializeChoice (int numOptions, int selectedOption, bool isExtensionMarkerPresent) const protected
Serialize a Choice (set of options)
Parameters
numOptions number of options
selectedOption selected option
isExtensionMarkerPresent true if extension mark is present
Definition at line 305 of file lte-asn1-header.cc.
References SerializeBoolean(), and SerializeInteger().
Referenced by ns3::RrcConnectionRequestHeader::PreSerialize(), ns3::RrcConnectionSetupHeader::PreSerialize(), ns3::RrcConnectionSetupCompleteHeader::PreSerialize(), ns3::RrcConnectionReconfigurationCompleteHeader::PreSerialize(), ns3::RrcConnectionReconfigurationHeader::PreSerialize(), ns3::HandoverPreparationInfoHeader::PreSerialize(), ns3::RrcConnectionReestablishmentRequestHeader::PreSerialize(), ns3::RrcConnectionReestablishmentHeader::PreSerialize(), ns3::RrcConnectionReestablishmentCompleteHeader::PreSerialize(), ns3::RrcConnectionReestablishmentRejectHeader::PreSerialize(), ns3::RrcConnectionReleaseHeader::PreSerialize(), ns3::RrcConnectionRejectHeader::PreSerialize(), ns3::MeasurementReportHeader::PreSerialize(), ns3::RrcDlCcchMessage::SerializeDlCcchMessage(), ns3::RrcDlDcchMessage::SerializeDlDcchMessage(), ns3::RrcAsn1Header::SerializeDrbToAddModList(), ns3::RrcAsn1Header::SerializeMeasConfig(), ns3::RrcAsn1Header::SerializeMeasResults(), ns3::RrcAsn1Header::SerializePhysicalConfigDedicated(), ns3::RrcAsn1Header::SerializePhysicalConfigDedicatedSCell(), ns3::RrcAsn1Header::SerializeRadioResourceConfigCommonSib(), ns3::RrcAsn1Header::SerializeSrbToAddModList(), ns3::RrcAsn1Header::SerializeThresholdEutra(), ns3::RrcUlCcchMessage::SerializeUlCcchMessage(), and ns3::RrcUlDcchMessage::SerializeUlDcchMessage().
SerializeEnum()
void ns3::Asn1Header::SerializeEnum (int numElems, int selectedElem) const protected
Serialize an Enum.
Parameters
numElems number of elements in the enum
selectedElem selected element
Definition at line 299 of file lte-asn1-header.cc.
References SerializeInteger().
Referenced by ns3::RrcConnectionRequestHeader::PreSerialize(), ns3::RrcConnectionReconfigurationHeader::PreSerialize(), ns3::HandoverPreparationInfoHeader::PreSerialize(), ns3::RrcConnectionReestablishmentRequestHeader::PreSerialize(), ns3::RrcConnectionReleaseHeader::PreSerialize(), ns3::RrcAsn1Header::SerializeDrbToAddModList(), ns3::RrcAsn1Header::SerializeLogicalChannelConfig(), ns3::RrcAsn1Header::SerializeMeasConfig(), ns3::RrcAsn1Header::SerializePhysicalConfigDedicated(), ns3::RrcAsn1Header::SerializePhysicalConfigDedicatedSCell(), ns3::RrcAsn1Header::SerializePlmnIdentity(), ns3::RrcAsn1Header::SerializeQoffsetRange(), ns3::RrcAsn1Header::SerializeRachConfigCommon(), ns3::RrcAsn1Header::SerializeRadioResourceConfigCommon(), ns3::RrcAsn1Header::SerializeRadioResourceConfigCommonSib(), ns3::RrcAsn1Header::SerializeSystemInformationBlockType1(), and ns3::RrcAsn1Header::SerializeSystemInformationBlockType2().
SerializeInteger()
void ns3::Asn1Header::SerializeInteger (int n, int nmin, int nmax) const protected
Serialize an Integer.
Parameters
n value to serialize
nmin min value to serialize
nmax max value to serialize
Definition at line 322 of file lte-asn1-header.cc.
References sample-rng-plot::n, and NS_ASSERT_MSG.
Referenced by ns3::RrcConnectionSetupHeader::PreSerialize(), ns3::RrcConnectionSetupCompleteHeader::PreSerialize(), ns3::RrcConnectionReconfigurationCompleteHeader::PreSerialize(), ns3::RrcConnectionReconfigurationHeader::PreSerialize(), ns3::HandoverPreparationInfoHeader::PreSerialize(), ns3::RrcConnectionReestablishmentRequestHeader::PreSerialize(), ns3::RrcConnectionReestablishmentHeader::PreSerialize(), ns3::RrcConnectionReestablishmentCompleteHeader::PreSerialize(), ns3::RrcConnectionReleaseHeader::PreSerialize(), ns3::RrcConnectionRejectHeader::PreSerialize(), SerializeChoice(), ns3::RrcAsn1Header::SerializeDrbToAddModList(), SerializeEnum(), ns3::RrcAsn1Header::SerializeLogicalChannelConfig(), ns3::RrcAsn1Header::SerializeMeasConfig(), ns3::RrcAsn1Header::SerializeMeasResults(), ns3::RrcAsn1Header::SerializeNonCriticalExtensionConfiguration(), ns3::RrcAsn1Header::SerializePhysicalConfigDedicated(), ns3::RrcAsn1Header::SerializePhysicalConfigDedicatedSCell(), ns3::RrcAsn1Header::SerializePlmnIdentity(), ns3::RrcAsn1Header::SerializeRachConfigCommon(), ns3::RrcAsn1Header::SerializeRadioResourceConfigCommon(), ns3::RrcAsn1Header::SerializeRadioResourceConfigCommonSCell(), ns3::RrcAsn1Header::SerializeRadioResourceConfigCommonSib(), ns3::RrcAsn1Header::SerializeRadioResourceConfigDedicated(), SerializeSequenceOf(), ns3::RrcAsn1Header::SerializeSrbToAddModList(), ns3::RrcAsn1Header::SerializeSystemInformationBlockType1(), ns3::RrcAsn1Header::SerializeSystemInformationBlockType2(), and ns3::RrcAsn1Header::SerializeThresholdEutra().
SerializeNull()
void ns3::Asn1Header::SerializeNull () const protected
Serialize nothing (null op)
Definition at line 411 of file lte-asn1-header.cc.
Referenced by ns3::RrcConnectionSetupCompleteHeader::PreSerialize(), ns3::RrcAsn1Header::SerializeMeasConfig(), ns3::RrcAsn1Header::SerializePhysicalConfigDedicated(), ns3::RrcAsn1Header::SerializePhysicalConfigDedicatedSCell(), and ns3::RrcAsn1Header::SerializeRadioResourceConfigCommonSib().
SerializeSequence() [1/12]
void ns3::Asn1Header::SerializeSequence (std::bitset< 0 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const protected
Serialize a sequence.
Parameters
optionalOrDefaultMask Mask to serialize
isExtensionMarkerPresent true if Extension Marker is present
Definition at line 238 of file lte-asn1-header.cc.
SerializeSequence() [2/12]
void ns3::Asn1Header::SerializeSequence (std::bitset< 1 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const protected
Serialize a sequence.
Parameters
optionalOrDefaultMask Mask to serialize
isExtensionMarkerPresent true if Extension Marker is present
Definition at line 243 of file lte-asn1-header.cc.
SerializeSequence() [3/12]
void ns3::Asn1Header::SerializeSequence (std::bitset< 10 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const protected
Serialize a sequence.
Parameters
optionalOrDefaultMask Mask to serialize
isExtensionMarkerPresent true if Extension Marker is present
Definition at line 283 of file lte-asn1-header.cc.
SerializeSequence() [4/12]
void ns3::Asn1Header::SerializeSequence (std::bitset< 11 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const protected
Serialize a sequence.
Parameters
optionalOrDefaultMask Mask to serialize
isExtensionMarkerPresent true if Extension Marker is present
Definition at line 288 of file lte-asn1-header.cc.
SerializeSequence() [5/12]
void ns3::Asn1Header::SerializeSequence (std::bitset< 2 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const protected
Serialize a sequence.
Parameters
optionalOrDefaultMask Mask to serialize
isExtensionMarkerPresent true if Extension Marker is present
Definition at line 248 of file lte-asn1-header.cc.
SerializeSequence() [6/12]
void ns3::Asn1Header::SerializeSequence (std::bitset< 3 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const protected
Serialize a sequence.
Parameters
optionalOrDefaultMask Mask to serialize
isExtensionMarkerPresent true if Extension Marker is present
Definition at line 253 of file lte-asn1-header.cc.
SerializeSequence() [7/12]
void ns3::Asn1Header::SerializeSequence (std::bitset< 4 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const protected
Serialize a sequence.
Parameters
optionalOrDefaultMask Mask to serialize
isExtensionMarkerPresent true if Extension Marker is present
Definition at line 258 of file lte-asn1-header.cc.
SerializeSequence() [8/12]
void ns3::Asn1Header::SerializeSequence (std::bitset< 5 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const protected
Serialize a sequence.
Parameters
optionalOrDefaultMask Mask to serialize
isExtensionMarkerPresent true if Extension Marker is present
Definition at line 263 of file lte-asn1-header.cc.
SerializeSequence() [9/12]
void ns3::Asn1Header::SerializeSequence (std::bitset< 6 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const protected
Serialize a sequence.
Parameters
optionalOrDefaultMask Mask to serialize
isExtensionMarkerPresent true if Extension Marker is present
Definition at line 268 of file lte-asn1-header.cc.
SerializeSequence() [10/12]
void ns3::Asn1Header::SerializeSequence (std::bitset< 7 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const protected
Serialize a sequence.
Parameters
optionalOrDefaultMask Mask to serialize
isExtensionMarkerPresent true if Extension Marker is present
Definition at line 273 of file lte-asn1-header.cc.
SerializeSequence() [11/12]
void ns3::Asn1Header::SerializeSequence (std::bitset< 9 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const protected
Serialize a sequence.
Parameters
optionalOrDefaultMask Mask to serialize
isExtensionMarkerPresent true if Extension Marker is present
Definition at line 278 of file lte-asn1-header.cc.
SerializeSequence() [12/12]
template<int N> void ns3::Asn1Header::SerializeSequence (std::bitset< N > optionalOrDefaultMask, bool isExtensionMarkerPresent) const protected
Serialize a sequence.
Parameters
optionalOrDefaultMask Mask to serialize
isExtensionMarkerPresent true if Extension Marker is present
Definition at line 228 of file lte-asn1-header.cc.
References SerializeBoolean().
Referenced by ns3::RrcConnectionRequestHeader::PreSerialize(), ns3::RrcConnectionSetupHeader::PreSerialize(), ns3::RrcConnectionSetupCompleteHeader::PreSerialize(), ns3::RrcConnectionReconfigurationCompleteHeader::PreSerialize(), ns3::RrcConnectionReconfigurationHeader::PreSerialize(), ns3::HandoverPreparationInfoHeader::PreSerialize(), ns3::RrcConnectionReestablishmentRequestHeader::PreSerialize(), ns3::RrcConnectionReestablishmentHeader::PreSerialize(), ns3::RrcConnectionReestablishmentCompleteHeader::PreSerialize(), ns3::RrcConnectionReestablishmentRejectHeader::PreSerialize(), ns3::RrcConnectionReleaseHeader::PreSerialize(), ns3::RrcConnectionRejectHeader::PreSerialize(), ns3::MeasurementReportHeader::PreSerialize(), ns3::RrcDlCcchMessage::SerializeDlCcchMessage(), ns3::RrcDlDcchMessage::SerializeDlDcchMessage(), ns3::RrcAsn1Header::SerializeDrbToAddModList(), ns3::RrcAsn1Header::SerializeLogicalChannelConfig(), ns3::RrcAsn1Header::SerializeMeasConfig(), ns3::RrcAsn1Header::SerializeMeasResults(), ns3::RrcAsn1Header::SerializeNonCriticalExtensionConfiguration(), ns3::RrcAsn1Header::SerializePhysicalConfigDedicated(), ns3::RrcAsn1Header::SerializePhysicalConfigDedicatedSCell(), ns3::RrcAsn1Header::SerializePlmnIdentity(), ns3::RrcAsn1Header::SerializeRachConfigCommon(), ns3::RrcAsn1Header::SerializeRadioResourceConfigCommon(), ns3::RrcAsn1Header::SerializeRadioResourceConfigCommonSCell(), ns3::RrcAsn1Header::SerializeRadioResourceConfigCommonSib(), ns3::RrcAsn1Header::SerializeRadioResourceConfigDedicated(), ns3::RrcAsn1Header::SerializeRadioResourceDedicatedSCell(), ns3::RrcAsn1Header::SerializeSrbToAddModList(), ns3::RrcAsn1Header::SerializeSystemInformationBlockType1(), ns3::RrcAsn1Header::SerializeSystemInformationBlockType2(), ns3::RrcUlCcchMessage::SerializeUlCcchMessage(), and ns3::RrcUlDcchMessage::SerializeUlDcchMessage().
SerializeSequenceOf()
void ns3::Asn1Header::SerializeSequenceOf (int numElems, int nMax, int nMin) const protected
Serialize a Sequence.
Parameters
numElems element number to serialize
nMax max value to serialize
nMin min value to serialize
Definition at line 293 of file lte-asn1-header.cc.
References SerializeInteger().
Referenced by ns3::HandoverPreparationInfoHeader::PreSerialize(), ns3::RrcAsn1Header::SerializeDrbToAddModList(), ns3::RrcAsn1Header::SerializeMeasConfig(), ns3::RrcAsn1Header::SerializeMeasResults(), ns3::RrcAsn1Header::SerializeNonCriticalExtensionConfiguration(), ns3::RrcAsn1Header::SerializePlmnIdentity(), ns3::RrcAsn1Header::SerializeRadioResourceConfigDedicated(), ns3::RrcAsn1Header::SerializeSrbToAddModList(), and ns3::RrcAsn1Header::SerializeSystemInformationBlockType1().
WriteOctet()
void ns3::Asn1Header::WriteOctet (uint8_t octet) const protected
Function to write in m_serializationResult, after resizing its size.
Parameters
octet bits to write
Definition at line 80 of file lte-asn1-header.cc.
References ns3::Buffer::AddAtEnd(), ns3::Buffer::End(), m_serializationResult, ns3::Buffer::Iterator::Prev(), and ns3::Buffer::Iterator::WriteU8().
Referenced by SerializeBitset().
Member Data Documentation
m_isDataSerialized
bool ns3::Asn1Header::m_isDataSerialized mutable protected
true if data is serialized
Definition at line 70 of file lte-asn1-header.h.
Referenced by Asn1Header(), FinalizeSerialization(), GetSerializedSize(), Serialize(), ns3::HandoverPreparationInfoHeader::SetMessage(), ns3::MeasurementReportHeader::SetMessage(), ns3::RrcConnectionReconfigurationHeader::SetMessage(), ns3::RrcConnectionReconfigurationCompleteHeader::SetMessage(), ns3::RrcConnectionReestablishmentHeader::SetMessage(), ns3::RrcConnectionReestablishmentCompleteHeader::SetMessage(), ns3::RrcConnectionReestablishmentRejectHeader::SetMessage(), ns3::RrcConnectionReestablishmentRequestHeader::SetMessage(), ns3::RrcConnectionRejectHeader::SetMessage(), ns3::RrcConnectionReleaseHeader::SetMessage(), ns3::RrcConnectionRequestHeader::SetMessage(), ns3::RrcConnectionSetupHeader::SetMessage(), and ns3::RrcConnectionSetupCompleteHeader::SetMessage().
m_numSerializationPendingBits
uint8_t ns3::Asn1Header::m_numSerializationPendingBits mutable protected
number of pending bits
Definition at line 69 of file lte-asn1-header.h.
Referenced by Asn1Header(), DeserializeBitset(), FinalizeSerialization(), and SerializeBitset().
m_serializationPendingBits
uint8_t ns3::Asn1Header::m_serializationPendingBits mutable protected
pending bits
Definition at line 68 of file lte-asn1-header.h.
Referenced by Asn1Header(), DeserializeBitset(), FinalizeSerialization(), and SerializeBitset().
m_serializationResult
Buffer ns3::Asn1Header::m_serializationResult mutable protected
serialization result
Definition at line 71 of file lte-asn1-header.h.
Referenced by GetSerializedSize(), ns3::RrcConnectionRequestHeader::PreSerialize(), ns3::RrcConnectionSetupHeader::PreSerialize(), ns3::RrcConnectionSetupCompleteHeader::PreSerialize(), ns3::RrcConnectionReconfigurationCompleteHeader::PreSerialize(), ns3::RrcConnectionReconfigurationHeader::PreSerialize(), ns3::HandoverPreparationInfoHeader::PreSerialize(), ns3::RrcConnectionReestablishmentRequestHeader::PreSerialize(), ns3::RrcConnectionReestablishmentHeader::PreSerialize(), ns3::RrcConnectionReestablishmentCompleteHeader::PreSerialize(), ns3::RrcConnectionReestablishmentRejectHeader::PreSerialize(), ns3::RrcConnectionReleaseHeader::PreSerialize(), ns3::RrcConnectionRejectHeader::PreSerialize(), ns3::MeasurementReportHeader::PreSerialize(), Serialize(), and WriteOctet().
The documentation for this class was generated from the following files:
src/lte/model/lte-asn1-header.h
src/lte/model/lte-asn1-header.cc