ns-3: ns3::AlohaNoackNetDevice Class Reference
ns3::AlohaNoackNetDevice Class Reference
Spectrum Models
This devices implements the following features:
#include "aloha-noack-net-device.h"
Public Types
enum State { IDLE , TX , RX }
State of the NetDevice.
Public Types inherited from ns3::NetDevice
typedef void(* LinkChangeTracedCallback) (void)
TracedCallback signature for link changed event.
enum PacketType {
PACKET_HOST = 1 , NS3_PACKET_HOST = PACKET_HOST , PACKET_BROADCAST , NS3_PACKET_BROADCAST = PACKET_BROADCAST ,
PACKET_MULTICAST , NS3_PACKET_MULTICAST = PACKET_MULTICAST , PACKET_OTHERHOST , NS3_PACKET_OTHERHOST = PACKET_OTHERHOST
}
Packet types are used as they are in Linux.
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address &, const Address &, enum PacketType > PromiscReceiveCallback
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address & > ReceiveCallback
Public Member Functions
AlohaNoackNetDevice ()
virtual ~AlohaNoackNetDevice ()
virtual void AddLinkChangeCallback (Callback< void > callback)
virtual Address GetAddress (void) const
virtual Address GetBroadcast (void) const
virtual Ptr< Channel > GetChannel (void) const
virtual uint32_t GetIfIndex (void) const
virtual uint16_t GetMtu (void) const
virtual Address GetMulticast (Ipv4Address addr) const
Make and return a MAC multicast address using the provided multicast group.
virtual Address GetMulticast (Ipv6Address addr) const
Get the MAC multicast address corresponding to the IPv6 address provided.
virtual Ptr< Node > GetNode (void) const
Ptr< Object > GetPhy () const
virtual bool IsBridge (void) const
Return true if the net device is acting as a bridge.
virtual bool IsBroadcast (void) const
virtual bool IsLinkUp (void) const
virtual bool IsMulticast (void) const
virtual bool IsPointToPoint (void) const
Return true if the net device is on a point-to-point link.
virtual bool NeedsArp (void) const
void NotifyReceptionEndError ()
Notify the MAC that the PHY finished a reception with an error.
void NotifyReceptionEndOk (Ptr< Packet > p)
Notify the MAC that the PHY finished a reception successfully.
void NotifyReceptionStart ()
Notify the MAC that the PHY has started a reception.
void NotifyTransmissionEnd (Ptr< const Packet >)
Notify the MAC that the PHY has finished a previously started transmission.
virtual bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)
virtual bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
virtual void SetAddress (Address address)
Set the address of this interface.
void SetChannel (Ptr< Channel > c)
This class doesn't talk directly with the underlying channel (a dedicated PHY class is expected to do it), however the NetDevice specification features a GetChannel() method.
void SetGenericPhyTxStartCallback (GenericPhyTxStartCallback c)
set the callback used to instruct the lower layer to start a TX
virtual void SetIfIndex (const uint32_t index)
virtual bool SetMtu (const uint16_t mtu)
virtual void SetNode (Ptr< Node > node)
void SetPhy (Ptr< Object > phy)
Set the Phy object which is attached to this device.
virtual void SetPromiscReceiveCallback (PromiscReceiveCallback cb)
virtual void SetQueue (Ptr< Queue< Packet > > queue)
set the queue which is going to be used by this device
virtual void SetReceiveCallback (NetDevice::ReceiveCallback cb)
virtual bool SupportsSendFrom (void) const
Public Member Functions inherited from ns3::NetDevice
virtual ~NetDevice ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::NetDevice
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual void DoDispose (void)
Destructor implementation.
void NotifyGuardIntervalEnd ()
Notification of Guard Interval end.
void StartTransmission ()
start the transmission of a packet by contacting the PHY layer
Private Attributes
Mac48Address m_address
MAC address.
Ptr< Channel > m_channel
Channel.
Ptr< Packet > m_currentPkt
Current packet.
uint32_t m_ifIndex
Interface index.
TracedCallback m_linkChangeCallbacks
List of callbacks to fire if the link changes state (up or down).
bool m_linkUp
true if the link is up
TracedCallback< Ptr< const Packet > > m_macPromiscRxTrace
Promiscuous Rx trace.
TracedCallback< Ptr< const Packet > > m_macRxTrace
Rx trace.
TracedCallback< Ptr< const Packet > > m_macTxDropTrace
Tx Drop trace.
TracedCallback< Ptr< const Packet > > m_macTxTrace
Tx trace.
uint32_t m_mtu
NetDevice MTU.
Ptr< Node > m_node
Node owning this NetDevice.
Ptr< Object > m_phy
PHY object.
GenericPhyTxStartCallback m_phyMacTxStartCallback
Tx Start callback.
NetDevice::PromiscReceiveCallback m_promiscRxCallback
Promiscuous Rx callback.
Ptr< Queue< Packet > > m_queue
packet queue
NetDevice::ReceiveCallback m_rxCallback
Rx callback.
State m_state
State of the NetDevice.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This devices implements the following features:
layer 3 protocol multiplexing
MAC addressing
Aloha MAC:
packets transmitted as soon as possible
a new packet is queued if previous one is still being transmitted
no acknowledgements, hence no retransmissions
can support any PHY layer compatible with the API defined in generic-phy.h
Config Paths
ns3::AlohaNoackNetDevice is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::AlohaNoackNetDevice"
Attributes
Address: The MAC address of this device.
Set with class: Mac48AddressValue
Underlying type: Mac48Address
Initial value: 12:34:56:78:90:12
Flags: construct write read
Queue: packets being transmitted get queued here
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::Queue<Packet>>
Initial value: 0x0
Flags: construct write read
Mtu: The Maximum Transmission Unit
Set with class: ns3::UintegerValue
Underlying type: uint16_t 1:65535
Initial value: 1500
Flags: construct write read
Phy: The PHY layer attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::Object>
Initial value: 0x0
Flags: construct write read
TraceSources
MacTx: Trace source indicating a packet has arrived for transmission by this device
Callback signature: ns3::Packet::TracedCallback
MacTxDrop: Trace source indicating a packet has been dropped by the device before transmission
Callback signature: ns3::Packet::TracedCallback
MacPromiscRx: A packet has been received by this device, has been passed up from the physical layer and is being forwarded up the local protocol stack. This is a promiscuous trace,
Callback signature: ns3::Packet::TracedCallback
MacRx: A packet has been received by this device, has been passed up from the physical layer and is being forwarded up the local protocol stack. This is a non-promiscuous trace,
Callback signature: ns3::Packet::TracedCallback
Size of this type is 240 bytes (on a 64-bit architecture).
Definition at line 59 of file aloha-noack-net-device.h.
Member Enumeration Documentation
State
enum ns3::AlohaNoackNetDevice::State
State of the NetDevice.
Enumerator
IDLE
Idle state.
TX
Transmitting state.
RX
Receiving state.
Definition at line 65 of file aloha-noack-net-device.h.
Constructor & Destructor Documentation
AlohaNoackNetDevice()
ns3::AlohaNoackNetDevice::AlohaNoackNetDevice ()
Definition at line 119 of file aloha-noack-net-device.cc.
References NS_LOG_FUNCTION.
~AlohaNoackNetDevice()
ns3::AlohaNoackNetDevice::~AlohaNoackNetDevice () virtual
Definition at line 125 of file aloha-noack-net-device.cc.
References m_queue, and NS_LOG_FUNCTION.
Member Function Documentation
AddLinkChangeCallback()
void ns3::AlohaNoackNetDevice::AddLinkChangeCallback (Callback< void > callback) virtual
Parameters
callback the callback to invoke
Add a callback invoked whenever the link status changes to UP. This callback is typically used by the IP/ARP layer to flush the ARP cache and by IPv6 stack to flush NDISC cache whenever the link goes up.
Implements ns3::NetDevice.
Definition at line 312 of file aloha-noack-net-device.cc.
References ns3::TracedCallback< Ts >::ConnectWithoutContext(), m_linkChangeCallbacks, and NS_LOG_FUNCTION.
DoDispose()
void ns3::AlohaNoackNetDevice::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 132 of file aloha-noack-net-device.cc.
References ns3::Object::DoDispose(), m_channel, m_currentPkt, m_node, m_phy, m_phyMacTxStartCallback, m_queue, and NS_LOG_FUNCTION.
GetAddress()
Address ns3::AlohaNoackNetDevice::GetAddress (void) const virtual
Returns
the current Address of this interface.
Implements ns3::NetDevice.
Definition at line 191 of file aloha-noack-net-device.cc.
References m_address, and NS_LOG_FUNCTION.
GetBroadcast()
Address ns3::AlohaNoackNetDevice::GetBroadcast (void) const virtual
Returns
the broadcast address supported by this netdevice.
Calling this method is invalid if IsBroadcast returns not true.
Implements ns3::NetDevice.
Definition at line 205 of file aloha-noack-net-device.cc.
References NS_LOG_FUNCTION.
GetChannel()
Ptr< Channel > ns3::AlohaNoackNetDevice::GetChannel (void) const virtual
Returns
the channel this NetDevice is connected to. The value returned can be zero if the NetDevice is not yet connected to any channel or if the underlying NetDevice has no concept of a channel. i.e., callers must check for zero and be ready to handle it.
Implements ns3::NetDevice.
Definition at line 290 of file aloha-noack-net-device.cc.
References m_channel, and NS_LOG_FUNCTION.
GetIfIndex()
uint32_t ns3::AlohaNoackNetDevice::GetIfIndex (void) const virtual
Returns
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 153 of file aloha-noack-net-device.cc.
References m_ifIndex, and NS_LOG_FUNCTION.
GetMtu()
uint16_t ns3::AlohaNoackNetDevice::GetMtu (void) const virtual
Returns
the link-level MTU in bytes for this interface.
This value is typically used by the IP layer to perform IP fragmentation when needed.
Implements ns3::NetDevice.
Definition at line 168 of file aloha-noack-net-device.cc.
References m_mtu, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetMulticast() [1/2]
Address ns3::AlohaNoackNetDevice::GetMulticast (Ipv4Address multicastGroup) const virtual
Make and return a MAC multicast address using the provided multicast group.
RFC 1112 says that an Ipv4 host group address is mapped to an Ethernet multicast address by placing the low-order 23-bits of the IP address into the low-order 23 bits of the Ethernet multicast address 01-00-5E-00-00-00 (hex). Similar RFCs exist for Ipv6 and Eui64 mappings. This method performs the multicast address creation function appropriate to the underlying MAC address of the device. This MAC address is encapsulated in an abstract Address to avoid dependencies on the exact MAC address format.
In the case of net devices that do not support multicast, clients are expected to test NetDevice::IsMulticast and avoid attempting to map multicast packets. Subclasses of NetDevice that do support multicasting are expected to override this method and provide an implementation appropriate to the particular device.
Parameters
multicastGroup The IP address for the multicast group destination of the packet.
Returns
The MAC multicast Address used to send packets to the provided multicast group.
Warning
Calling this method is invalid if IsMulticast returns not true.
See also
IsMulticast()
Implements ns3::NetDevice.
Definition at line 219 of file aloha-noack-net-device.cc.
References ns3::Mac48Address::GetMulticast(), and NS_LOG_FUNCTION.
GetMulticast() [2/2]
Address ns3::AlohaNoackNetDevice::GetMulticast (Ipv6Address addr) const virtual
Get the MAC multicast address corresponding to the IPv6 address provided.
Parameters
addr IPv6 address
Returns
the MAC multicast address
Warning
Calling this method is invalid if IsMulticast returns not true.
Implements ns3::NetDevice.
Definition at line 227 of file aloha-noack-net-device.cc.
References ns3::Mac48Address::GetMulticast(), and NS_LOG_FUNCTION.
GetNode()
Ptr< Node > ns3::AlohaNoackNetDevice::GetNode (void) const virtual
Returns
the node base class which contains this network interface.
When a subclass needs to get access to the underlying node base class to print the nodeid for example, it can invoke this method.
Implements ns3::NetDevice.
Definition at line 251 of file aloha-noack-net-device.cc.
References m_node, and NS_LOG_FUNCTION.
GetPhy()
Ptr< Object > ns3::AlohaNoackNetDevice::GetPhy (void) const
Returns
a reference to the PHY object embedded in this NetDevice.
Definition at line 274 of file aloha-noack-net-device.cc.
References m_phy, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::AlohaNoackNetDevice::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 65 of file aloha-noack-net-device.cc.
References GetMtu(), GetPhy(), m_address, m_macPromiscRxTrace, m_macRxTrace, m_macTxDropTrace, m_macTxTrace, m_queue, ns3::MakeMac48AddressAccessor(), ns3::MakeMac48AddressChecker(), ns3::MakePointerAccessor(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), SetMtu(), ns3::TypeId::SetParent(), and SetPhy().
IsBridge()
bool ns3::AlohaNoackNetDevice::IsBridge (void) const virtual
Return true if the net device is acting as a bridge.
Returns
value of m_isBridge flag
Implements ns3::NetDevice.
Definition at line 243 of file aloha-noack-net-device.cc.
References NS_LOG_FUNCTION.
IsBroadcast()
bool ns3::AlohaNoackNetDevice::IsBroadcast (void) const virtual
Returns
true if this interface supports a broadcast address, false otherwise.
Implements ns3::NetDevice.
Definition at line 198 of file aloha-noack-net-device.cc.
References NS_LOG_FUNCTION.
IsLinkUp()
bool ns3::AlohaNoackNetDevice::IsLinkUp (void) const virtual
Returns
true if link is up; false otherwise
Implements ns3::NetDevice.
Definition at line 305 of file aloha-noack-net-device.cc.
References m_linkUp, and NS_LOG_FUNCTION.
IsMulticast()
bool ns3::AlohaNoackNetDevice::IsMulticast (void) const virtual
Returns
value of m_isMulticast flag
Implements ns3::NetDevice.
Definition at line 212 of file aloha-noack-net-device.cc.
References NS_LOG_FUNCTION.
IsPointToPoint()
bool ns3::AlohaNoackNetDevice::IsPointToPoint (void) const virtual
Return true if the net device is on a point-to-point link.
Returns
value of m_isPointToPoint flag
Implements ns3::NetDevice.
Definition at line 236 of file aloha-noack-net-device.cc.
References NS_LOG_FUNCTION.
NeedsArp()
bool ns3::AlohaNoackNetDevice::NeedsArp (void) const virtual
Returns
true if ARP is needed, false otherwise.
Called by higher-layers to check if this NetDevice requires ARP to be used.
Implements ns3::NetDevice.
Definition at line 298 of file aloha-noack-net-device.cc.
References NS_LOG_FUNCTION.
NotifyGuardIntervalEnd()
void ns3::AlohaNoackNetDevice::NotifyGuardIntervalEnd () private
Notification of Guard Interval end.
NotifyReceptionEndError()
void ns3::AlohaNoackNetDevice::NotifyReceptionEndError ()
Notify the MAC that the PHY finished a reception with an error.
Definition at line 455 of file aloha-noack-net-device.cc.
References NS_LOG_FUNCTION.
NotifyReceptionEndOk()
void ns3::AlohaNoackNetDevice::NotifyReceptionEndOk (Ptr< Packet > p)
Notify the MAC that the PHY finished a reception successfully.
Parameters
p the received packet
Definition at line 465 of file aloha-noack-net-device.cc.
References ns3::Packet::Copy(), ns3::AlohaNoackMacHeader::GetDestination(), ns3::AlohaNoackMacHeader::GetSource(), ns3::LlcSnapHeader::GetType(), ns3::Mac48Address::IsBroadcast(), ns3::Mac48Address::IsGroup(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_address, m_promiscRxCallback, m_rxCallback, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::NetDevice::PACKET_BROADCAST, ns3::NetDevice::PACKET_HOST, ns3::NetDevice::PACKET_MULTICAST, ns3::NetDevice::PACKET_OTHERHOST, and ns3::Packet::RemoveHeader().
Referenced by ns3::AdhocAlohaNoackIdealPhyHelper::Install().
NotifyReceptionStart()
void ns3::AlohaNoackNetDevice::NotifyReceptionStart ()
Notify the MAC that the PHY has started a reception.
Definition at line 447 of file aloha-noack-net-device.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::AdhocAlohaNoackIdealPhyHelper::Install().
NotifyTransmissionEnd()
void ns3::AlohaNoackNetDevice::NotifyTransmissionEnd (Ptr< const Packet >)
Notify the MAC that the PHY has finished a previously started transmission.
Definition at line 429 of file aloha-noack-net-device.cc.
References IDLE, m_currentPkt, m_queue, m_state, NS_ASSERT, NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Simulator::ScheduleNow(), StartTransmission(), and TX.
Referenced by ns3::AdhocAlohaNoackIdealPhyHelper::Install().
Send()
bool ns3::AlohaNoackNetDevice::Send (Ptr< Packet > packet, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device to the specified destination Address
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 341 of file aloha-noack-net-device.cc.
References m_address, NS_LOG_FUNCTION, and SendFrom().
SendFrom()
bool ns3::AlohaNoackNetDevice::SendFrom (Ptr< Packet > packet, const Address & source, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
source source mac address (so called "MAC spoofing")
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device with the specified source and destination Addresses.
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 348 of file aloha-noack-net-device.cc.
References ns3::Packet::AddHeader(), ns3::Mac48Address::ConvertFrom(), IDLE, m_currentPkt, m_macTxDropTrace, m_macTxTrace, m_queue, m_state, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::AlohaNoackMacHeader::SetDestination(), ns3::AlohaNoackMacHeader::SetSource(), ns3::LlcSnapHeader::SetType(), and StartTransmission().
Referenced by Send().
SetAddress()
void ns3::AlohaNoackNetDevice::SetAddress (Address address) virtual
Set the address of this interface.
Parameters
address address to set
Implements ns3::NetDevice.
Definition at line 184 of file aloha-noack-net-device.cc.
References first::address, ns3::Mac48Address::ConvertFrom(), m_address, and NS_LOG_FUNCTION.
SetChannel()
void ns3::AlohaNoackNetDevice::SetChannel (Ptr< Channel > c)
This class doesn't talk directly with the underlying channel (a dedicated PHY class is expected to do it), however the NetDevice specification features a GetChannel() method.
This method here is therefore provide to allow AlohaNoackNetDevice::GetChannel() to have something meaningful to return.
Parameters
c the underlying channel
Definition at line 282 of file aloha-noack-net-device.cc.
References m_channel, and NS_LOG_FUNCTION.
SetGenericPhyTxStartCallback()
void ns3::AlohaNoackNetDevice::SetGenericPhyTxStartCallback (GenericPhyTxStartCallback c)
set the callback used to instruct the lower layer to start a TX
Parameters
c
Definition at line 402 of file aloha-noack-net-device.cc.
References m_phyMacTxStartCallback, and NS_LOG_FUNCTION.
SetIfIndex()
void ns3::AlohaNoackNetDevice::SetIfIndex (const uint32_t index) virtual
Parameters
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 146 of file aloha-noack-net-device.cc.
References m_ifIndex, and NS_LOG_FUNCTION.
SetMtu()
bool ns3::AlohaNoackNetDevice::SetMtu (const uint16_t mtu) virtual
Parameters
mtu MTU value, in bytes, to set for the device
Returns
whether the MTU value was within legal bounds
Override for default MTU defined on a per-type basis.
Implements ns3::NetDevice.
Definition at line 160 of file aloha-noack-net-device.cc.
References m_mtu, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetNode()
void ns3::AlohaNoackNetDevice::SetNode (Ptr< Node > node) virtual
Parameters
node the node associated to this netdevice.
This method is called from ns3::Node::AddDevice.
Implements ns3::NetDevice.
Definition at line 258 of file aloha-noack-net-device.cc.
References m_node, and NS_LOG_FUNCTION.
SetPhy()
void ns3::AlohaNoackNetDevice::SetPhy (Ptr< Object > phy)
Set the Phy object which is attached to this device.
This object is needed so that we can set/get attributes and connect to trace sources of the PHY from the net device.
Parameters
phy the Phy object attached to the device. Note that the API between the PHY and the above (this NetDevice which also implements the MAC) is implemented entirely by callbacks, so we do not require that the PHY inherits by any specific class.
Definition at line 266 of file aloha-noack-net-device.cc.
References m_phy, NS_LOG_FUNCTION, and third::phy.
Referenced by GetTypeId().
SetPromiscReceiveCallback()
void ns3::AlohaNoackNetDevice::SetPromiscReceiveCallback (PromiscReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received in promiscuous mode and must be forwarded to the higher layers.
Enables netdevice promiscuous mode and sets the callback that will handle promiscuous mode packets. Note, promiscuous mode packets means all packets, including those packets that can be sensed by the netdevice but which are intended to be received by other hosts.
Implements ns3::NetDevice.
Definition at line 326 of file aloha-noack-net-device.cc.
References m_promiscRxCallback, and NS_LOG_FUNCTION.
SetQueue()
void ns3::AlohaNoackNetDevice::SetQueue (Ptr< Queue< Packet > > queue) virtual
set the queue which is going to be used by this device
Parameters
queue
Definition at line 176 of file aloha-noack-net-device.cc.
References m_queue, and NS_LOG_FUNCTION.
SetReceiveCallback()
void ns3::AlohaNoackNetDevice::SetReceiveCallback (NetDevice::ReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received and must be forwarded to the higher layers.
Set the callback to be used to notify higher layers when a packet has been received.
Implements ns3::NetDevice.
Definition at line 319 of file aloha-noack-net-device.cc.
References m_rxCallback, and NS_LOG_FUNCTION.
StartTransmission()
void ns3::AlohaNoackNetDevice::StartTransmission (void) private
start the transmission of a packet by contacting the PHY layer
Definition at line 409 of file aloha-noack-net-device.cc.
References IDLE, m_currentPkt, m_phyMacTxStartCallback, m_state, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_WARN, and TX.
Referenced by NotifyTransmissionEnd(), and SendFrom().
SupportsSendFrom()
bool ns3::AlohaNoackNetDevice::SupportsSendFrom (void) const virtual
Returns
true if this interface supports a bridging mode, false otherwise.
Implements ns3::NetDevice.
Definition at line 333 of file aloha-noack-net-device.cc.
References NS_LOG_FUNCTION.
Member Data Documentation
m_address
Mac48Address ns3::AlohaNoackNetDevice::m_address private
MAC address.
Definition at line 209 of file aloha-noack-net-device.h.
Referenced by GetAddress(), GetTypeId(), NotifyReceptionEndOk(), Send(), and SetAddress().
m_channel
Ptr<Channel> ns3::AlohaNoackNetDevice::m_channel private
Channel.
Definition at line 207 of file aloha-noack-net-device.h.
Referenced by DoDispose(), GetChannel(), and SetChannel().
m_currentPkt
Ptr<Packet> ns3::AlohaNoackNetDevice::m_currentPkt private
Current packet.
Definition at line 227 of file aloha-noack-net-device.h.
Referenced by DoDispose(), NotifyTransmissionEnd(), SendFrom(), and StartTransmission().
m_ifIndex
uint32_t ns3::AlohaNoackNetDevice::m_ifIndex private
Interface index.
Definition at line 222 of file aloha-noack-net-device.h.
Referenced by GetIfIndex(), and SetIfIndex().
m_linkChangeCallbacks
TracedCallback ns3::AlohaNoackNetDevice::m_linkChangeCallbacks private
List of callbacks to fire if the link changes state (up or down).
Definition at line 219 of file aloha-noack-net-device.h.
Referenced by AddLinkChangeCallback().
m_linkUp
bool ns3::AlohaNoackNetDevice::m_linkUp private
true if the link is up
Definition at line 224 of file aloha-noack-net-device.h.
Referenced by IsLinkUp().
m_macPromiscRxTrace
TracedCallback<Ptr<const Packet> > ns3::AlohaNoackNetDevice::m_macPromiscRxTrace private
Promiscuous Rx trace.
Definition at line 203 of file aloha-noack-net-device.h.
Referenced by GetTypeId().
m_macRxTrace
TracedCallback<Ptr<const Packet> > ns3::AlohaNoackNetDevice::m_macRxTrace private
Rx trace.
Definition at line 204 of file aloha-noack-net-device.h.
Referenced by GetTypeId().
m_macTxDropTrace
TracedCallback<Ptr<const Packet> > ns3::AlohaNoackNetDevice::m_macTxDropTrace private
Tx Drop trace.
Definition at line 202 of file aloha-noack-net-device.h.
Referenced by GetTypeId(), and SendFrom().
m_macTxTrace
TracedCallback<Ptr<const Packet> > ns3::AlohaNoackNetDevice::m_macTxTrace private
Tx trace.
Definition at line 201 of file aloha-noack-net-device.h.
Referenced by GetTypeId(), and SendFrom().
m_mtu
uint32_t ns3::AlohaNoackNetDevice::m_mtu mutable private
NetDevice MTU.
Definition at line 223 of file aloha-noack-net-device.h.
Referenced by GetMtu(), and SetMtu().
m_node
Ptr<Node> ns3::AlohaNoackNetDevice::m_node private
Node owning this NetDevice.
Definition at line 206 of file aloha-noack-net-device.h.
Referenced by DoDispose(), GetNode(), and SetNode().
m_phy
Ptr<Object> ns3::AlohaNoackNetDevice::m_phy private
PHY object.
Definition at line 228 of file aloha-noack-net-device.h.
Referenced by DoDispose(), GetPhy(), and SetPhy().
m_phyMacTxStartCallback
GenericPhyTxStartCallback ns3::AlohaNoackNetDevice::m_phyMacTxStartCallback private
Tx Start callback.
Definition at line 214 of file aloha-noack-net-device.h.
Referenced by DoDispose(), SetGenericPhyTxStartCallback(), and StartTransmission().
m_promiscRxCallback
NetDevice::PromiscReceiveCallback ns3::AlohaNoackNetDevice::m_promiscRxCallback private
Promiscuous Rx callback.
Definition at line 212 of file aloha-noack-net-device.h.
Referenced by NotifyReceptionEndOk(), and SetPromiscReceiveCallback().
m_queue
Ptr<Queue<Packet> > ns3::AlohaNoackNetDevice::m_queue private
packet queue
Definition at line 199 of file aloha-noack-net-device.h.
Referenced by ~AlohaNoackNetDevice(), DoDispose(), GetTypeId(), NotifyTransmissionEnd(), SendFrom(), and SetQueue().
m_rxCallback
NetDevice::ReceiveCallback ns3::AlohaNoackNetDevice::m_rxCallback private
Rx callback.
Definition at line 211 of file aloha-noack-net-device.h.
Referenced by NotifyReceptionEndOk(), and SetReceiveCallback().
m_state
State ns3::AlohaNoackNetDevice::m_state private
State of the NetDevice.
Definition at line 226 of file aloha-noack-net-device.h.
Referenced by NotifyTransmissionEnd(), SendFrom(), and StartTransmission().
The documentation for this class was generated from the following files:
src/spectrum/model/aloha-noack-net-device.h
src/spectrum/model/aloha-noack-net-device.cc