ns-3: ns3::test::RandomVariable::NormalAntitheticTestCase Class Reference
ns3::test::RandomVariable::NormalAntitheticTestCase Class Reference
Test case for antithetic normal distribution random variable stream generator.
Public Member Functions
NormalAntitheticTestCase ()
double ChiSquaredTest (Ptr< RandomVariableStream > rng) const
Compute the chi square value from a random variable.
Public Member Functions inherited from ns3::test::RandomVariable::TestCaseBase
TestCaseBase (std::string name)
Constructor.
double Average (Ptr< RandomVariableStream > rng) const
Compute the average of a random variable.
double ChiSquared (gsl_histogram *h, const std::vector< double > &expected, Ptr< RandomVariableStream > rng) const
Compute the chi squared value of a sampled distribution compared to the expected distribution.
double ChiSquaredsAverage (const RngGeneratorBase *generator, std::size_t nRuns) const
Average the chi squared value over some number of runs, each run with a new instance of the random number generator.
void SetTestSuiteSeed (void)
Set the seed used for this test suite.
std::vector< double > UniformHistogramBins (gsl_histogram *h, double start, double end, bool underflow=true, bool overflow=true) const
Configure a GSL histogram with uniform bins, with optional under/over-flow bins.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Static Private Attributes
static constexpr double TOLERANCE {5}
Tolerance for testing rng values against expectation, in rms.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Static Public Attributes inherited from ns3::test::RandomVariable::TestCaseBase
static const uint32_t N_BINS {50}
Number of bins for sampling the distributions.
static const uint32_t N_MEASUREMENTS {1000000}
Number of samples to draw when populating the distributions.
static const uint32_t N_RUNS {5}
Number of retry attempts to pass a chi-square test.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test case for antithetic normal distribution random variable stream generator.
Definition at line 721 of file random-variable-stream-test-suite.cc.
Constructor & Destructor Documentation
NormalAntitheticTestCase()
ns3::test::RandomVariable::NormalAntitheticTestCase::NormalAntitheticTestCase ()
Definition at line 738 of file random-variable-stream-test-suite.cc.
Member Function Documentation
ChiSquaredTest()
double ns3::test::RandomVariable::NormalAntitheticTestCase::ChiSquaredTest (Ptr< RandomVariableStream > rng) const virtual
Compute the chi square value from a random variable.
This function sets up the binning and expected distribution needed to actually compute the chi squared value, which should be done by a call to ChiSquared.
This is the point of customization expected to be implemented in derived classes with the appropriate histogram binning and expected distribution. For example
SomeRngTestCase::ChiSquaredTest (Ptr<RandomVariableStream> rng) const { gsl_histogram * h = gsl_histogram_alloc (N_BINS); auto range = UniformHistogramBins (h, -4., 4.); std::vector<double> expected (N_BINS); // Populated expected for (std::size_t i = 0; i < N_BINS; ++i) { expected[i] = ...; expected[i] *= N_MEASUREMENTS; } double chiSquared = ChiSquared (h, expected, rng); gsl_histogram_free (h); return chiSquared; }
Parameters
[in] rng The random number generator to test.
Returns
The chi squared value.
Reimplemented from ns3::test::RandomVariable::TestCaseBase.
Definition at line 743 of file random-variable-stream-test-suite.cc.
References ns3::test::RandomVariable::TestCaseBase::ChiSquared(), ns3::test::RandomVariable::TestCaseBase::N_BINS, ns3::test::RandomVariable::TestCaseBase::N_MEASUREMENTS, sample-rng-plot::rng, and ns3::test::RandomVariable::TestCaseBase::UniformHistogramBins().
DoRun()
void ns3::test::RandomVariable::NormalAntitheticTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 768 of file random-variable-stream-test-suite.cc.
References ns3::test::RandomVariable::TestCaseBase::Average(), ns3::test::RandomVariable::TestCaseBase::ChiSquaredsAverage(), ns3::test::RandomVariable::TestCaseBase::N_BINS, ns3::test::RandomVariable::TestCaseBase::N_MEASUREMENTS, ns3::test::RandomVariable::TestCaseBase::N_RUNS, NS_LOG_FUNCTION, NS_TEST_ASSERT_MSG_EQ_TOL, NS_TEST_ASSERT_MSG_LT, ns3::test::RandomVariable::TestCaseBase::SetTestSuiteSeed(), TOLERANCE, and sample-rng-plot::x.
Member Data Documentation
TOLERANCE
constexpr double ns3::test::RandomVariable::NormalAntitheticTestCase::TOLERANCE {5} static constexpr private
Tolerance for testing rng values against expectation, in rms.
Definition at line 735 of file random-variable-stream-test-suite.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/core/test/random-variable-stream-test-suite.cc