ns-3: ns3::StatusCode Class Reference
ns3::StatusCode Class Reference
Status code for association response.
#include "status-code.h"
Public Member Functions
StatusCode ()
Buffer::Iterator Deserialize (Buffer::Iterator start)
uint32_t GetSerializedSize (void) const
bool IsSuccess (void) const
Return whether the status code is success.
Buffer::Iterator Serialize (Buffer::Iterator start) const
void SetFailure (void)
Set success bit to 1 (failure).
void SetSuccess (void)
Set success bit to 0 (success).
Private Attributes
uint16_t m_code
status code
Detailed Description
Status code for association response.
Definition at line 31 of file status-code.h.
Constructor & Destructor Documentation
StatusCode()
ns3::StatusCode::StatusCode ()
Definition at line 25 of file status-code.cc.
Member Function Documentation
Deserialize()
Buffer::Iterator ns3::StatusCode::Deserialize (Buffer::Iterator start)
Parameters
start an iterator which points to where the status code should be read.
Returns
the number of bytes read.
This method is used to re-create a status code from the byte buffer. The data read is expected to match bit-for-bit the representation of this header in real networks.
Definition at line 61 of file status-code.cc.
References m_code, and visualizer.core::start().
Referenced by ns3::MgtAssocResponseHeader::Deserialize(), and ns3::MgtAddBaResponseHeader::Deserialize().
GetSerializedSize()
uint32_t ns3::StatusCode::GetSerializedSize (void) const
Returns
the expected size of the status code.
This method should return the number of bytes which are needed to store the status code data by Serialize.
Definition at line 48 of file status-code.cc.
Referenced by ns3::MgtAssocResponseHeader::GetSerializedSize(), and ns3::MgtAddBaResponseHeader::GetSerializedSize().
IsSuccess()
bool ns3::StatusCode::IsSuccess (void) const
Return whether the status code is success.
Returns
true if success, false otherwise
Definition at line 42 of file status-code.cc.
References m_code.
Referenced by ns3::QosTxop::GotAddBaResponse(), ns3::operator<<(), and ns3::StaWifiMac::Receive().
Serialize()
Buffer::Iterator ns3::StatusCode::Serialize (Buffer::Iterator start) const
Parameters
start an iterator which points to where the status code should be written
Returns
Buffer::Iterator
This method is used to store a status code into the byte buffer. The data written is expected to match bit-for-bit the representation of this header in a real network.
Definition at line 54 of file status-code.cc.
References m_code, and visualizer.core::start().
Referenced by ns3::MgtAssocResponseHeader::Serialize(), and ns3::MgtAddBaResponseHeader::Serialize().
SetFailure()
void ns3::StatusCode::SetFailure (void)
Set success bit to 1 (failure).
Definition at line 36 of file status-code.cc.
References m_code.
Referenced by ns3::ApWifiMac::SendAssocResp().
SetSuccess()
void ns3::StatusCode::SetSuccess (void)
Set success bit to 0 (success).
Definition at line 30 of file status-code.cc.
References m_code.
Referenced by ns3::RegularWifiMac::SendAddBaResponse(), and ns3::ApWifiMac::SendAssocResp().
Member Data Documentation
m_code
uint16_t ns3::StatusCode::m_code private
status code
Definition at line 82 of file status-code.h.
Referenced by Deserialize(), IsSuccess(), Serialize(), SetFailure(), and SetSuccess().
The documentation for this class was generated from the following files:
src/wifi/model/status-code.h
src/wifi/model/status-code.cc