ns-3: ns3::ObjectPtrContainerValue Class Reference
ns3::ObjectPtrContainerValue Class Reference
ObjectPtrContainer Attribute
Container for a set of ns3::Object pointers.
#include "object-ptr-container.h"
Public Types
typedef std::map< std::size_t, Ptr< Object > >::const_iterator Iterator
Iterator type for traversing this container.
Public Member Functions
ObjectPtrContainerValue ()
Default constructor.
Iterator Begin (void) const
Get an iterator to the first Object.
virtual Ptr< AttributeValue > Copy (void) const
Get a copy of this container.
virtual bool DeserializeFromString (std::string value, Ptr< const AttributeChecker > checker)
Deserialize from a string.
Iterator End (void) const
Get an iterator to the past-the-end Object.
Ptr< Object > Get (std::size_t i) const
Get a specific Object.
std::size_t GetN (void) const
Get the number of Objects.
virtual std::string SerializeToString (Ptr< const AttributeChecker > checker) const
Serialize each of the Object pointers to a string.
Public Member Functions inherited from ns3::AttributeValue
AttributeValue ()
virtual ~AttributeValue ()
Public Member Functions inherited from ns3::SimpleRefCount< AttributeValue >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
std::map< std::size_t, Ptr< Object > > m_objects
The container implementation.
Friends
class ObjectPtrContainerAccessor
ObjectPtrContainerAccessor::Get() needs access.
Detailed Description
Container for a set of ns3::Object pointers.
AttributeValue implementation for ObjectPtrContainer.
This class it used to get attribute access to an array of ns3::Object pointers.
See also
AttributeValue
Definition at line 45 of file object-ptr-container.h.
Member Typedef Documentation
Iterator
typedef std::map<std::size_t, Ptr<Object> >::const_iterator ns3::ObjectPtrContainerValue::Iterator
Iterator type for traversing this container.
Definition at line 49 of file object-ptr-container.h.
Constructor & Destructor Documentation
ObjectPtrContainerValue()
ObjectPtrContainer ns3::ObjectPtrContainerValue::ObjectPtrContainerValue (void)
Default constructor.
Definition at line 33 of file object-ptr-container.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Begin()
ObjectPtrContainerValue::Iterator ns3::ObjectPtrContainerValue::Begin (void) const
Get an iterator to the first Object.
Returns
An iterator to the first Object.
Definition at line 39 of file object-ptr-container.cc.
References m_objects, and NS_LOG_FUNCTION.
Referenced by LteRadioLinkFailureTestCase::CheckConnected(), LteRrcConnectionEstablishmentTestCase::CheckConnected(), LteX2HandoverMeasuresTestCase::CheckConnected(), LteX2HandoverTestCase::CheckConnected(), ns3::Config::Resolver::DoArrayResolve(), ns3::AttributeIterator::DoIterate(), and SerializeToString().
Copy()
Ptr< AttributeValue > ns3::ObjectPtrContainerValue::Copy (void) const virtual
Get a copy of this container.
Returns
A copy of this container.
Implements ns3::AttributeValue.
Definition at line 70 of file object-ptr-container.cc.
References NS_LOG_FUNCTION.
DeserializeFromString()
bool ns3::ObjectPtrContainerValue::DeserializeFromString (std::string value, Ptr< const AttributeChecker > checker) virtual
Deserialize from a string.
(Not implemented; raises a fatal error.)
Parameters
[in] value The serialized string form.
[in] checker The checker to use.
Returns
true.
Implements ns3::AttributeValue.
Definition at line 92 of file object-ptr-container.cc.
References NS_FATAL_ERROR, and NS_LOG_FUNCTION.
End()
ObjectPtrContainerValue::Iterator ns3::ObjectPtrContainerValue::End (void) const
Get an iterator to the past-the-end Object.
Returns
An iterator to the past-the-end Object.
Definition at line 45 of file object-ptr-container.cc.
References m_objects, and NS_LOG_FUNCTION.
Referenced by LteRadioLinkFailureTestCase::CheckConnected(), LteRrcConnectionEstablishmentTestCase::CheckConnected(), LteX2HandoverMeasuresTestCase::CheckConnected(), LteX2HandoverTestCase::CheckConnected(), ns3::Config::Resolver::DoArrayResolve(), ns3::AttributeIterator::DoIterate(), and SerializeToString().
Get()
ObjectPtrContainer ns3::ObjectPtrContainerValue::Get (std::size_t i) const
Get a specific Object.
Parameters
[in] i The index of the requested object.
Returns
The requested object
The ObjectPtrContainer value.
Definition at line 57 of file object-ptr-container.cc.
References m_objects, and NS_LOG_FUNCTION.
Referenced by ObjectVectorAttributeTestCase::DoRun(), and ObjectMapAttributeTestCase::DoRun().
GetN()
std::size_t ns3::ObjectPtrContainerValue::GetN (void) const
Get the number of Objects.
Returns
The number of objects.
Definition at line 51 of file object-ptr-container.cc.
References m_objects, and NS_LOG_FUNCTION.
Referenced by LteRadioLinkFailureTestCase::CheckConnected(), LteRrcConnectionEstablishmentTestCase::CheckConnected(), LteX2HandoverMeasuresTestCase::CheckConnected(), LteX2HandoverTestCase::CheckConnected(), ObjectVectorAttributeTestCase::DoRun(), and ObjectMapAttributeTestCase::DoRun().
SerializeToString()
std::string ns3::ObjectPtrContainerValue::SerializeToString (Ptr< const AttributeChecker > checker) const virtual
Serialize each of the Object pointers to a string.
Note this serializes the Ptr values, not the Objects themselves.
Parameters
[in] checker The checker to use (currently not used.)
Returns
The string form of the Objects.
Implements ns3::AttributeValue.
Definition at line 76 of file object-ptr-container.cc.
References Begin(), End(), and NS_LOG_FUNCTION.
Friends And Related Function Documentation
ObjectPtrContainerAccessor
friend class ObjectPtrContainerAccessor friend
ObjectPtrContainerAccessor::Get() needs access.
Definition at line 106 of file object-ptr-container.h.
Member Data Documentation
m_objects
std::map<std::size_t, Ptr<Object> > ns3::ObjectPtrContainerValue::m_objects private
The container implementation.
Definition at line 108 of file object-ptr-container.h.
Referenced by Begin(), End(), ns3::ObjectPtrContainerAccessor::Get(), Get(), and GetN().
The documentation for this class was generated from the following files:
src/core/model/object-ptr-container.h
src/core/model/object-ptr-container.cc
doc/introspected-doxygen.h