ns-3: ns3::MeshWifiBeacon Class Reference
ns3::MeshWifiBeacon Class Reference
Beacon is beacon header + list of arbitrary information elements.
#include "mesh-wifi-beacon.h"
Public Member Functions
MeshWifiBeacon (Ssid ssid, SupportedRates rates, uint64_t us)
C-tor.
void AddInformationElement (Ptr< WifiInformationElement > ie)
Add information element.
MgtBeaconHeader BeaconHeader () const
Read standard Wifi beacon header.
WifiMacHeader CreateHeader (Mac48Address address, Mac48Address mpAddress)
Create Wifi header for beacon frame.
Ptr< Packet > CreatePacket ()
Create frame = { beacon header + all information elements sorted by ElementId () }.
Time GetBeaconInterval () const
Returns the beacon interval of Wifi beacon.
Private Attributes
MeshInformationElementVector m_elements
List of information elements added.
MgtBeaconHeader m_header
Beacon header.
Detailed Description
Beacon is beacon header + list of arbitrary information elements.
It is supposed that distinct mesh protocols can use beacons to transport their own information elements.
Definition at line 40 of file mesh-wifi-beacon.h.
Constructor & Destructor Documentation
MeshWifiBeacon()
ns3::MeshWifiBeacon::MeshWifiBeacon (Ssid ssid, SupportedRates rates, uint64_t us)
C-tor.
Parameters
ssid is SSID for beacon header
rates is a set of supported rates
us beacon interval in microseconds
Definition at line 27 of file mesh-wifi-beacon.cc.
References m_header, ns3::MgtProbeResponseHeader::SetBeaconIntervalUs(), ns3::MgtProbeResponseHeader::SetSsid(), ns3::MgtProbeResponseHeader::SetSupportedRates(), and third::ssid.
Member Function Documentation
AddInformationElement()
void ns3::MeshWifiBeacon::AddInformationElement (Ptr< WifiInformationElement > ie)
Add information element.
Parameters
ie the Wifi information element
Definition at line 35 of file mesh-wifi-beacon.cc.
References ns3::WifiInformationElementVector::AddInformationElement(), and m_elements.
Referenced by ns3::dot11s::PeerManagementProtocolMac::UpdateBeacon().
BeaconHeader()
MgtBeaconHeader ns3::MeshWifiBeacon::BeaconHeader () const inline
Read standard Wifi beacon header.
Returns
the management beacon header
Definition at line 56 of file mesh-wifi-beacon.h.
References m_header.
Referenced by CreatePacket().
CreateHeader()
WifiMacHeader ns3::MeshWifiBeacon::CreateHeader (Mac48Address address, Mac48Address mpAddress)
Create Wifi header for beacon frame.
Parameters
address is sender address
mpAddress is mesh point address
Returns
the WifiMacHeader
Definition at line 56 of file mesh-wifi-beacon.cc.
References first::address, ns3::Mac48Address::GetBroadcast(), ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetAddr2(), ns3::WifiMacHeader::SetAddr3(), ns3::WifiMacHeader::SetDsNotFrom(), ns3::WifiMacHeader::SetDsNotTo(), ns3::WifiMacHeader::SetType(), and ns3::WIFI_MAC_MGT_BEACON.
Referenced by ns3::MeshWifiInterfaceMac::SendBeacon().
CreatePacket()
Ptr< Packet > ns3::MeshWifiBeacon::CreatePacket ()
Create frame = { beacon header + all information elements sorted by ElementId () }.
Returns
the frame
Definition at line 47 of file mesh-wifi-beacon.cc.
References ns3::Packet::AddHeader(), BeaconHeader(), and m_elements.
Referenced by ns3::MeshWifiInterfaceMac::SendBeacon().
GetBeaconInterval()
Time ns3::MeshWifiBeacon::GetBeaconInterval () const
Returns the beacon interval of Wifi beacon.
Returns
the beacon interval time
Definition at line 41 of file mesh-wifi-beacon.cc.
References ns3::MgtProbeResponseHeader::GetBeaconIntervalUs(), m_header, and ns3::MicroSeconds().
Referenced by ns3::dot11s::PeerManagementProtocolMac::UpdateBeacon().
Member Data Documentation
m_elements
MeshInformationElementVector ns3::MeshWifiBeacon::m_elements private
List of information elements added.
Definition at line 89 of file mesh-wifi-beacon.h.
Referenced by AddInformationElement(), and CreatePacket().
m_header
MgtBeaconHeader ns3::MeshWifiBeacon::m_header private
Beacon header.
Definition at line 87 of file mesh-wifi-beacon.h.
Referenced by MeshWifiBeacon(), BeaconHeader(), and GetBeaconInterval().
The documentation for this class was generated from the following files:
src/mesh/model/mesh-wifi-beacon.h
src/mesh/model/mesh-wifi-beacon.cc