ns-3: ns3::Ipv6StaticRouting Class Reference
ns3::Ipv6StaticRouting Class Reference
Internet » IPv6 Routing Protocols.
Static routing protocol for IP version 6 stacks.
#include "ipv6-static-routing.h"
Public Member Functions
Ipv6StaticRouting ()
virtual ~Ipv6StaticRouting ()
void AddHostRouteTo (Ipv6Address dest, Ipv6Address nextHop, uint32_t interface, Ipv6Address prefixToUse=Ipv6Address("::"), uint32_t metric=0)
Add route to host.
void AddHostRouteTo (Ipv6Address dest, uint32_t interface, uint32_t metric=0)
Add route to host.
void AddMulticastRoute (Ipv6Address origin, Ipv6Address group, uint32_t inputInterface, std::vector< uint32_t > outputInterfaces)
Add a multicast route for a given multicast source and group.
void AddNetworkRouteTo (Ipv6Address network, Ipv6Prefix networkPrefix, Ipv6Address nextHop, uint32_t interface, Ipv6Address prefixToUse, uint32_t metric=0)
Add route to network.
void AddNetworkRouteTo (Ipv6Address network, Ipv6Prefix networkPrefix, Ipv6Address nextHop, uint32_t interface, uint32_t metric=0)
Add route to network.
void AddNetworkRouteTo (Ipv6Address network, Ipv6Prefix networkPrefix, uint32_t interface, uint32_t metric=0)
Add route to network.
Ipv6RoutingTableEntry GetDefaultRoute ()
Get the default route.
uint32_t GetMetric (uint32_t index) const
Get a metric for route from the static unicast routing table.
Ipv6MulticastRoutingTableEntry GetMulticastRoute (uint32_t i) const
Get the specified multicast route.
uint32_t GetNMulticastRoutes () const
Get the number of entries in the multicast routing table.
uint32_t GetNRoutes () const
Get the number or entries in the routing table.
Ipv6RoutingTableEntry GetRoute (uint32_t i) const
Get a specified route.
bool HasNetworkDest (Ipv6Address dest, uint32_t interfaceIndex)
If the destination is already present in network destination list.
virtual void NotifyAddAddress (uint32_t interface, Ipv6InterfaceAddress address)
Notify when specified interface add an address.
virtual void NotifyAddRoute (Ipv6Address dst, Ipv6Prefix mask, Ipv6Address nextHop, uint32_t interface, Ipv6Address prefixToUse=Ipv6Address::GetZero())
Notify a new route.
virtual void NotifyInterfaceDown (uint32_t interface)
Notify when specified interface goes DOWN.
virtual void NotifyInterfaceUp (uint32_t interface)
Notify when specified interface goes UP.
virtual void NotifyRemoveAddress (uint32_t interface, Ipv6InterfaceAddress address)
Notify when specified interface add an address.
virtual void NotifyRemoveRoute (Ipv6Address dst, Ipv6Prefix mask, Ipv6Address nextHop, uint32_t interface, Ipv6Address prefixToUse=Ipv6Address::GetZero())
Notify route removing.
virtual void PrintRoutingTable (Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S) const
Print the Routing Table entries.
bool RemoveMulticastRoute (Ipv6Address origin, Ipv6Address group, uint32_t inputInterface)
Remove a static multicast route.
void RemoveMulticastRoute (uint32_t i)
Remove a multicast route.
void RemoveRoute (Ipv6Address network, Ipv6Prefix prefix, uint32_t ifIndex, Ipv6Address prefixToUse)
Remove a route from the routing table.
void RemoveRoute (uint32_t i)
Remove a route from the routing table.
virtual bool RouteInput (Ptr< const Packet > p, const Ipv6Header &header, Ptr< const NetDevice > idev, UnicastForwardCallback ucb, MulticastForwardCallback mcb, LocalDeliverCallback lcb, ErrorCallback ecb)
Route an input packet (to be forwarded or locally delivered)
virtual Ptr< Ipv6Route > RouteOutput (Ptr< Packet > p, const Ipv6Header &header, Ptr< NetDevice > oif, Socket::SocketErrno &sockerr)
Query routing cache for an existing route, for an outbound packet.
void SetDefaultMulticastRoute (uint32_t outputInterface)
Set the default multicast route.
void SetDefaultRoute (Ipv6Address nextHop, uint32_t interface, Ipv6Address prefixToUse=Ipv6Address("::"), uint32_t metric=0)
Set the default route.
virtual void SetIpv6 (Ptr< Ipv6 > ipv6)
Typically, invoked directly or indirectly from ns3::Ipv6::SetRoutingProtocol.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
The interface Id associated with this class.
Static Public Member Functions inherited from ns3::Ipv6RoutingProtocol
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose ()
Dispose this object.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
typedef std::list< Ipv6MulticastRoutingTableEntry * > MulticastRoutes
Container for the multicast routes.
typedef std::list< Ipv6MulticastRoutingTableEntry * >::const_iterator MulticastRoutesCI
Const Iterator for container for the multicast routes.
typedef std::list< Ipv6MulticastRoutingTableEntry * >::iterator MulticastRoutesI
Iterator for container for the multicast routes.
typedef std::list< std::pair< Ipv6RoutingTableEntry *, uint32_t > > NetworkRoutes
Container for the network routes.
typedef std::list< std::pair< Ipv6RoutingTableEntry *, uint32_t > >::const_iterator NetworkRoutesCI
Const Iterator for container for the network routes.
typedef std::list< std::pair< Ipv6RoutingTableEntry *, uint32_t > >::iterator NetworkRoutesI
Iterator for container for the network routes.
Private Member Functions
Ptr< Ipv6Route > LookupStatic (Ipv6Address dest, Ptr< NetDevice >=0)
Lookup in the forwarding table for destination.
Ptr< Ipv6MulticastRoute > LookupStatic (Ipv6Address origin, Ipv6Address group, uint32_t ifIndex)
Lookup in the multicast forwarding table for destination.
Private Attributes
Ptr< Ipv6 > m_ipv6
Ipv6 reference.
MulticastRoutes m_multicastRoutes
the forwarding table for multicast.
NetworkRoutes m_networkRoutes
the forwarding table for network.
Additional Inherited Members
Public Types inherited from ns3::Ipv6RoutingProtocol
typedef Callback< void, Ptr< const Packet >, const Ipv6Header &, Socket::SocketErrno > ErrorCallback
Callback for routing errors (e.g., no route found)
typedef Callback< void, Ptr< const Packet >, const Ipv6Header &, uint32_t > LocalDeliverCallback
Callback for packets to be locally delivered.
typedef Callback< void, Ptr< const NetDevice >, Ptr< Ipv6MulticastRoute >, Ptr< const Packet >, const Ipv6Header & > MulticastForwardCallback
Callback for multicast packets to be forwarded.
typedef Callback< void, Ptr< const NetDevice >, Ptr< Ipv6Route >, Ptr< const Packet >, const Ipv6Header & > UnicastForwardCallback
Callback for unicast packets to be forwarded.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Static routing protocol for IP version 6 stacks.
Introspection did not find any typical Config paths.
This class provides a basic set of methods for inserting static unicast and multicast routes into the Ipv6 routing system. This particular protocol is designed to be inserted into an Ipv6ListRouting protocol but can be used also as a standalone protocol.
The Ipv6StaticRouting class inherits from the abstract base class Ipv6RoutingProtocol that defines the interface methods that a routing protocol must support.
See also
Ipv6RoutingProtocol
Ipv6ListRouting
Ipv6ListRouting::AddRoutingProtocol
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 88 bytes (on a 64-bit architecture).
Definition at line 63 of file ipv6-static-routing.h.
Member Typedef Documentation
MulticastRoutes
typedef std::list<Ipv6MulticastRoutingTableEntry *> ns3::Ipv6StaticRouting::MulticastRoutes private
Container for the multicast routes.
Definition at line 259 of file ipv6-static-routing.h.
MulticastRoutesCI
typedef std::list<Ipv6MulticastRoutingTableEntry *>::const_iterator ns3::Ipv6StaticRouting::MulticastRoutesCI private
Const Iterator for container for the multicast routes.
Definition at line 262 of file ipv6-static-routing.h.
MulticastRoutesI
typedef std::list<Ipv6MulticastRoutingTableEntry *>::iterator ns3::Ipv6StaticRouting::MulticastRoutesI private
Iterator for container for the multicast routes.
Definition at line 265 of file ipv6-static-routing.h.
NetworkRoutes
typedef std::list<std::pair <Ipv6RoutingTableEntry *, uint32_t> > ns3::Ipv6StaticRouting::NetworkRoutes private
Container for the network routes.
Definition at line 250 of file ipv6-static-routing.h.
NetworkRoutesCI
typedef std::list<std::pair <Ipv6RoutingTableEntry *, uint32_t> >::const_iterator ns3::Ipv6StaticRouting::NetworkRoutesCI private
Const Iterator for container for the network routes.
Definition at line 253 of file ipv6-static-routing.h.
NetworkRoutesI
typedef std::list<std::pair <Ipv6RoutingTableEntry *, uint32_t> >::iterator ns3::Ipv6StaticRouting::NetworkRoutesI private
Iterator for container for the network routes.
Definition at line 256 of file ipv6-static-routing.h.
Constructor & Destructor Documentation
Ipv6StaticRouting()
ns3::Ipv6StaticRouting::Ipv6StaticRouting ()
Definition at line 49 of file ipv6-static-routing.cc.
References NS_LOG_FUNCTION.
~Ipv6StaticRouting()
ns3::Ipv6StaticRouting::~Ipv6StaticRouting () virtual
Definition at line 55 of file ipv6-static-routing.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddHostRouteTo() [1/2]
void ns3::Ipv6StaticRouting::AddHostRouteTo (Ipv6Address dest, Ipv6Address nextHop, uint32_t interface, Ipv6Address prefixToUse = Ipv6Address ("::"), uint32_t metric = 0)
Add route to host.
Parameters
dest destination address
nextHop next hop address to route the packet.
interface interface index
prefixToUse prefix that should be used for source address for this destination
metric metric of route in case of multiple routes to same destination
Definition at line 132 of file ipv6-static-routing.cc.
References AddNetworkRouteTo(), ns3::Ipv6Prefix::GetOnes(), ns3::Ipv6Address::IsLinkLocal(), NS_LOG_FUNCTION, and NS_LOG_WARN.
Referenced by NotifyInterfaceUp().
AddHostRouteTo() [2/2]
void ns3::Ipv6StaticRouting::AddHostRouteTo (Ipv6Address dest, uint32_t interface, uint32_t metric = 0)
Add route to host.
Parameters
dest destination address.
interface interface index
metric metric of route in case of multiple routes to same destination
Definition at line 143 of file ipv6-static-routing.cc.
References AddNetworkRouteTo(), ns3::Ipv6Prefix::GetOnes(), and NS_LOG_FUNCTION.
AddMulticastRoute()
void ns3::Ipv6StaticRouting::AddMulticastRoute (Ipv6Address origin, Ipv6Address group, uint32_t inputInterface, std::vector< uint32_t > outputInterfaces)
Add a multicast route for a given multicast source and group.
Parameters
origin IPv6 address of the source
group the multicast group address.
inputInterface the interface index
outputInterfaces the list of output interface indices over which the packet should be sent (excluding the inputInterface).
Definition at line 184 of file ipv6-static-routing.cc.
References ns3::Ipv6MulticastRoutingTableEntry::CreateMulticastRoute(), m_multicastRoutes, and NS_LOG_FUNCTION.
AddNetworkRouteTo() [1/3]
void ns3::Ipv6StaticRouting::AddNetworkRouteTo (Ipv6Address network, Ipv6Prefix networkPrefix, Ipv6Address nextHop, uint32_t interface, Ipv6Address prefixToUse, uint32_t metric = 0)
Add route to network.
Parameters
network network address
networkPrefix network prefix*
nextHop next hop address to route the packet.
interface interface index
prefixToUse prefix that should be used for source address for this destination
metric metric of route in case of multiple routes to same destination
Definition at line 157 of file ipv6-static-routing.cc.
References ns3::Ipv6RoutingTableEntry::CreateNetworkRouteTo(), ns3::Ipv6Address::IsLinkLocal(), m_networkRoutes, NS_LOG_FUNCTION, and NS_LOG_WARN.
AddNetworkRouteTo() [2/3]
void ns3::Ipv6StaticRouting::AddNetworkRouteTo (Ipv6Address network, Ipv6Prefix networkPrefix, Ipv6Address nextHop, uint32_t interface, uint32_t metric = 0)
Add route to network.
Parameters
network network address
networkPrefix network prefix*
nextHop next hop address to route the packet
interface interface index
metric metric of route in case of multiple routes to same destination
Definition at line 149 of file ipv6-static-routing.cc.
References ns3::Ipv6RoutingTableEntry::CreateNetworkRouteTo(), m_networkRoutes, and NS_LOG_FUNCTION.
Referenced by AddHostRouteTo(), NotifyAddAddress(), NotifyAddRoute(), NotifyInterfaceUp(), and SetDefaultRoute().
AddNetworkRouteTo() [3/3]
void ns3::Ipv6StaticRouting::AddNetworkRouteTo (Ipv6Address network, Ipv6Prefix networkPrefix, uint32_t interface, uint32_t metric = 0)
Add route to network.
Parameters
network network address
networkPrefix network prefix
interface interface index
metric metric of route in case of multiple routes to same destination
Definition at line 170 of file ipv6-static-routing.cc.
References ns3::Ipv6RoutingTableEntry::CreateNetworkRouteTo(), m_networkRoutes, and NS_LOG_FUNCTION.
DoDispose()
void ns3::Ipv6StaticRouting::DoDispose (void) protected virtual
Dispose this object.
Reimplemented from ns3::Object.
Definition at line 374 of file ipv6-static-routing.cc.
References ns3::Object::DoDispose(), m_ipv6, m_multicastRoutes, m_networkRoutes, and NS_LOG_FUNCTION.
GetDefaultRoute()
Ipv6RoutingTableEntry ns3::Ipv6StaticRouting::GetDefaultRoute (void)
Get the default route.
If multiple default routes exist, the one with lowest metric is returned.
Returns
default Ipv6Route
Definition at line 448 of file ipv6-static-routing.cc.
References ns3::Ipv6RoutingTableEntry::GetDestNetwork(), ns3::Ipv6RoutingTableEntry::GetDestNetworkPrefix(), ns3::Ipv6Prefix::GetPrefixLength(), m_networkRoutes, and NS_LOG_FUNCTION.
GetMetric()
uint32_t ns3::Ipv6StaticRouting::GetMetric (uint32_t index) const
Get a metric for route from the static unicast routing table.
Parameters
index The index (into the routing table) of the route to retrieve.
Returns
If route is set, the metric is returned. If not, an infinity metric (0xffffffff) is returned
Definition at line 504 of file ipv6-static-routing.cc.
References m_networkRoutes, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by PrintRoutingTable().
GetMulticastRoute()
Ipv6MulticastRoutingTableEntry ns3::Ipv6StaticRouting::GetMulticastRoute (uint32_t i) const
Get the specified multicast route.
Parameters
i index
Returns
the route whose index is i
Definition at line 208 of file ipv6-static-routing.cc.
References m_multicastRoutes, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
GetNMulticastRoutes()
uint32_t ns3::Ipv6StaticRouting::GetNMulticastRoutes (void) const
Get the number of entries in the multicast routing table.
Returns
number of entries
Definition at line 202 of file ipv6-static-routing.cc.
References m_multicastRoutes, and NS_LOG_FUNCTION.
GetNRoutes()
uint32_t ns3::Ipv6StaticRouting::GetNRoutes (void) const
Get the number or entries in the routing table.
Returns
number of entries
Definition at line 443 of file ipv6-static-routing.cc.
References m_networkRoutes.
Referenced by PrintRoutingTable().
GetRoute()
Ipv6RoutingTableEntry ns3::Ipv6StaticRouting::GetRoute (uint32_t i) const
Get a specified route.
Parameters
i index
Returns
the route whose index is i
Definition at line 486 of file ipv6-static-routing.cc.
References m_networkRoutes, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by PrintRoutingTable().
GetTypeId()
TypeId ns3::Ipv6StaticRouting::GetTypeId (void) static
The interface Id associated with this class.
Returns
type identifier
Definition at line 39 of file ipv6-static-routing.cc.
References ns3::TypeId::SetParent().
HasNetworkDest()
bool ns3::Ipv6StaticRouting::HasNetworkDest (Ipv6Address dest, uint32_t interfaceIndex)
If the destination is already present in network destination list.
Parameters
dest destination address
interfaceIndex interface index
Returns
true if dest is already in list, false otherwise
Definition at line 263 of file ipv6-static-routing.cc.
References ns3::Ipv6RoutingTableEntry::GetDestNetwork(), ns3::Ipv6RoutingTableEntry::GetDestNetworkPrefix(), ns3::Ipv6RoutingTableEntry::GetInterface(), ns3::Ipv6Prefix::IsMatch(), m_networkRoutes, and NS_LOG_FUNCTION.
LookupStatic() [1/2]
Ptr< Ipv6Route > ns3::Ipv6StaticRouting::LookupStatic (Ipv6Address dest, Ptr< NetDevice > interface = 0) private
Lookup in the forwarding table for destination.
Parameters
dest destination address
interface output interface if any (put 0 otherwise)
Returns
Ipv6Route to route the packet to reach dest address
Definition at line 284 of file ipv6-static-routing.cc.
References ns3::Ipv6RoutingTableEntry::GetDest(), ns3::Ipv6RoutingTableEntry::GetDestNetwork(), ns3::Ipv6RoutingTableEntry::GetDestNetworkPrefix(), ns3::Ipv6RoutingTableEntry::GetGateway(), ns3::Ipv6RoutingTableEntry::GetInterface(), ns3::Ipv6Prefix::GetPrefixLength(), ns3::Ipv6RoutingTableEntry::GetPrefixToUse(), ns3::Ipv6Address::GetZero(), ns3::Ipv6Address::IsAny(), ns3::Ipv6Address::IsLinkLocalMulticast(), ns3::Ipv6Prefix::IsMatch(), m_ipv6, m_networkRoutes, NS_ASSERT_MSG, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by RouteInput(), and RouteOutput().
LookupStatic() [2/2]
Ptr< Ipv6MulticastRoute > ns3::Ipv6StaticRouting::LookupStatic (Ipv6Address origin, Ipv6Address group, uint32_t ifIndex) private
Lookup in the multicast forwarding table for destination.
Parameters
origin source address
group group multicast address
ifIndex interface index
Returns
Ipv6MulticastRoute to route the packet to reach dest address
Definition at line 394 of file ipv6-static-routing.cc.
References ns3::Ipv6MulticastRoutingTableEntry::GetGroup(), ns3::Ipv6MulticastRoutingTableEntry::GetInputInterface(), ns3::Ipv6MulticastRoutingTableEntry::GetNOutputInterfaces(), ns3::Ipv6MulticastRoutingTableEntry::GetOrigin(), ns3::Ipv6MulticastRoutingTableEntry::GetOutputInterface(), ns3::Ipv6::IF_ANY, m_multicastRoutes, ns3::Ipv6MulticastRoute::MAX_TTL, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
NotifyAddAddress()
void ns3::Ipv6StaticRouting::NotifyAddAddress (uint32_t interface, Ipv6InterfaceAddress address) virtual
Notify when specified interface add an address.
Protocols are expected to implement this method to be notified whenever a new address is added to an interface. Typically used to add a 'network route' on an interface. Can be invoked on an up or down interface.
Parameters
interface the index of the interface we are being notified about
address a new address being added to an interface
Implements ns3::Ipv6RoutingProtocol.
Definition at line 685 of file ipv6-static-routing.cc.
References AddNetworkRouteTo(), first::address, and m_ipv6.
NotifyAddRoute()
void ns3::Ipv6StaticRouting::NotifyAddRoute (Ipv6Address dst, Ipv6Prefix mask, Ipv6Address nextHop, uint32_t interface, Ipv6Address prefixToUse = Ipv6Address::GetZero()) virtual
Notify a new route.
Typically this is used to add another route from IPv6 stack (i.e. ICMPv6 redirect case, ...).
Parameters
dst destination address
mask destination mask
nextHop nextHop for this destination
interface output interface
prefixToUse prefix to use as source with this route
Implements ns3::Ipv6RoutingProtocol.
Definition at line 730 of file ipv6-static-routing.cc.
References AddNetworkRouteTo(), ns3::Ipv6Address::GetZero(), NS_LOG_INFO, and SetDefaultRoute().
NotifyInterfaceDown()
void ns3::Ipv6StaticRouting::NotifyInterfaceDown (uint32_t interface) virtual
Notify when specified interface goes DOWN.
Protocols are expected to implement this method to be notified of the state change of an interface in a node.
Parameters
interface the index of the interface we are being notified about
Implements ns3::Ipv6RoutingProtocol.
Definition at line 666 of file ipv6-static-routing.cc.
References m_networkRoutes, and NS_LOG_FUNCTION.
Referenced by SetIpv6().
NotifyInterfaceUp()
void ns3::Ipv6StaticRouting::NotifyInterfaceUp (uint32_t interface) virtual
Notify when specified interface goes UP.
Protocols are expected to implement this method to be notified of the state change of an interface in a node.
Parameters
interface the index of the interface we are being notified about
Implements ns3::Ipv6RoutingProtocol.
Definition at line 645 of file ipv6-static-routing.cc.
References AddHostRouteTo(), AddNetworkRouteTo(), and m_ipv6.
Referenced by SetIpv6().
NotifyRemoveAddress()
void ns3::Ipv6StaticRouting::NotifyRemoveAddress (uint32_t interface, Ipv6InterfaceAddress address) virtual
Notify when specified interface add an address.
Protocols are expected to implement this method to be notified whenever a new address is removed from an interface. Typically used to remove the 'network route' of an interface. Can be invoked on an up or down interface.
Parameters
interface the index of the interface we are being notified about
address a new address being added to an interface
Implements ns3::Ipv6RoutingProtocol.
Definition at line 701 of file ipv6-static-routing.cc.
References first::address, m_ipv6, and m_networkRoutes.
NotifyRemoveRoute()
void ns3::Ipv6StaticRouting::NotifyRemoveRoute (Ipv6Address dst, Ipv6Prefix mask, Ipv6Address nextHop, uint32_t interface, Ipv6Address prefixToUse = Ipv6Address::GetZero()) virtual
Notify route removing.
Parameters
dst destination address
mask destination mask
nextHop nextHop for this destination
interface output interface
prefixToUse prefix to use as source with this route
Implements ns3::Ipv6RoutingProtocol.
Definition at line 751 of file ipv6-static-routing.cc.
References ns3::Ipv6RoutingTableEntry::GetDestNetwork(), ns3::Ipv6RoutingTableEntry::GetDestNetworkPrefix(), ns3::Ipv6RoutingTableEntry::GetInterface(), ns3::Ipv6Address::GetZero(), m_networkRoutes, NS_LOG_FUNCTION, and RemoveRoute().
PrintRoutingTable()
void ns3::Ipv6StaticRouting::PrintRoutingTable (Ptr< OutputStreamWrapper > stream, Time::Unit unit = Time::S) const virtual
Print the Routing Table entries.
Parameters
stream The ostream the Routing table is printed to
unit The time unit to be used in the report
Implements ns3::Ipv6RoutingProtocol.
Definition at line 82 of file ipv6-static-routing.cc.
References ns3::Time::As(), ns3::Names::FindName(), ns3::Ipv6RoutingTableEntry::GetDest(), ns3::Ipv6RoutingTableEntry::GetDestNetworkPrefix(), ns3::Ipv6RoutingTableEntry::GetGateway(), ns3::Ipv6RoutingTableEntry::GetInterface(), GetMetric(), GetNRoutes(), ns3::Ipv6Prefix::GetPrefixLength(), GetRoute(), ns3::OutputStreamWrapper::GetStream(), ns3::Ipv6RoutingTableEntry::IsGateway(), ns3::Ipv6RoutingTableEntry::IsHost(), m_ipv6, ns3::Now(), and NS_LOG_FUNCTION.
RemoveMulticastRoute() [1/2]
bool ns3::Ipv6StaticRouting::RemoveMulticastRoute (Ipv6Address origin, Ipv6Address group, uint32_t inputInterface)
Remove a static multicast route.
Parameters
origin IPv6 address of the source
group the multicast group address.
inputInterface the input interface index
Returns
true on success
Definition at line 228 of file ipv6-static-routing.cc.
References ns3::Ipv6MulticastRoutingTableEntry::GetGroup(), ns3::Ipv6MulticastRoutingTableEntry::GetInputInterface(), ns3::Ipv6MulticastRoutingTableEntry::GetOrigin(), m_multicastRoutes, and NS_LOG_FUNCTION.
RemoveMulticastRoute() [2/2]
void ns3::Ipv6StaticRouting::RemoveMulticastRoute (uint32_t i)
Remove a multicast route.
Parameters
i index of route to remove
Definition at line 246 of file ipv6-static-routing.cc.
References m_multicastRoutes, and NS_LOG_FUNCTION.
RemoveRoute() [1/2]
void ns3::Ipv6StaticRouting::RemoveRoute (Ipv6Address network, Ipv6Prefix prefix, uint32_t ifIndex, Ipv6Address prefixToUse)
Remove a route from the routing table.
Parameters
network IPv6 network
prefix IPv6 prefix
ifIndex interface index
prefixToUse IPv6 prefix to use with this route (multihoming)
Definition at line 540 of file ipv6-static-routing.cc.
References ns3::Ipv6RoutingTableEntry::GetDest(), ns3::Ipv6RoutingTableEntry::GetInterface(), ns3::Ipv6RoutingTableEntry::GetPrefixToUse(), m_networkRoutes, and NS_LOG_FUNCTION.
RemoveRoute() [2/2]
void ns3::Ipv6StaticRouting::RemoveRoute (uint32_t i)
Remove a route from the routing table.
Parameters
i index
Definition at line 522 of file ipv6-static-routing.cc.
References m_networkRoutes, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by NotifyRemoveRoute().
RouteInput()
bool ns3::Ipv6StaticRouting::RouteInput (Ptr< const Packet > p, const Ipv6Header & header, Ptr< const NetDevice > idev, UnicastForwardCallback ucb, MulticastForwardCallback mcb, LocalDeliverCallback lcb, ErrorCallback ecb) virtual
Route an input packet (to be forwarded or locally delivered)
This lookup is used in the forwarding process. The packet is handed over to the Ipv6RoutingProtocol, and will get forwarded onward by one of the callbacks. The Linux equivalent is ip_route_input (). There are four valid outcomes, and a matching callbacks to handle each.
Parameters
p received packet
header input parameter used to form a search key for a route
idev Pointer to ingress network device
ucb Callback for the case in which the packet is to be forwarded as unicast
mcb Callback for the case in which the packet is to be forwarded as multicast
lcb Callback for the case in which the packet is to be locally delivered
ecb Callback to call if there is an error in forwarding
Returns
true if the Ipv6RoutingProtocol takes responsibility for forwarding or delivering the packet, false otherwise
Implements ns3::Ipv6RoutingProtocol.
Definition at line 586 of file ipv6-static-routing.cc.
References ns3::Socket::ERROR_NOROUTETOHOST, ns3::Ipv6Header::GetDestinationAddress(), ns3::Ipv6Header::GetSourceAddress(), ns3::Ipv6Address::IsMulticast(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), LookupStatic(), m_ipv6, NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
RouteOutput()
Ptr< Ipv6Route > ns3::Ipv6StaticRouting::RouteOutput (Ptr< Packet > p, const Ipv6Header & header, Ptr< NetDevice > oif, Socket::SocketErrno & sockerr) virtual
Query routing cache for an existing route, for an outbound packet.
This lookup is used by transport protocols. It does not cause any packet to be forwarded, and is synchronous. Can be used for multicast or unicast. The Linux equivalent is ip_route_output ()
Parameters
p packet to be routed. Note that this method may modify the packet. Callers may also pass in a null pointer.
header input parameter (used to form key to search for the route)
oif Output interface device. May be zero, or may be bound via socket options to a particular output interface.
sockerr Output parameter; socket errno
Returns
a code that indicates what happened in the lookup
Implements ns3::Ipv6RoutingProtocol.
Definition at line 557 of file ipv6-static-routing.cc.
References ns3::Socket::ERROR_NOROUTETOHOST, ns3::Socket::ERROR_NOTERROR, ns3::Ipv6Header::GetDestinationAddress(), ns3::Ipv6Address::IsMulticast(), LookupStatic(), NS_LOG_FUNCTION, and NS_LOG_LOGIC.
SetDefaultMulticastRoute()
void ns3::Ipv6StaticRouting::SetDefaultMulticastRoute (uint32_t outputInterface)
Set the default multicast route.
Parameters
outputInterface default output interface
Definition at line 192 of file ipv6-static-routing.cc.
References ns3::Ipv6RoutingTableEntry::CreateNetworkRouteTo(), m_networkRoutes, and NS_LOG_FUNCTION.
SetDefaultRoute()
void ns3::Ipv6StaticRouting::SetDefaultRoute (Ipv6Address nextHop, uint32_t interface, Ipv6Address prefixToUse = Ipv6Address ("::"), uint32_t metric = 0)
Set the default route.
Parameters
nextHop next hop address to route the packet
interface interface index
prefixToUse prefix to use (i.e for multihoming)
metric metric of route in case of multiple routes to same destination
Definition at line 178 of file ipv6-static-routing.cc.
References AddNetworkRouteTo(), ns3::Ipv6Prefix::GetZero(), and NS_LOG_FUNCTION.
Referenced by NotifyAddRoute().
SetIpv6()
void ns3::Ipv6StaticRouting::SetIpv6 (Ptr< Ipv6 > ipv6) virtual
Typically, invoked directly or indirectly from ns3::Ipv6::SetRoutingProtocol.
Parameters
ipv6 the ipv6 object this routing protocol is being associated with
Implements ns3::Ipv6RoutingProtocol.
Definition at line 60 of file ipv6-static-routing.cc.
References m_ipv6, NotifyInterfaceDown(), NotifyInterfaceUp(), NS_ASSERT, and NS_LOG_FUNCTION.
Member Data Documentation
m_ipv6
Ptr<Ipv6> ns3::Ipv6StaticRouting::m_ipv6 private
Ipv6 reference.
Definition at line 297 of file ipv6-static-routing.h.
Referenced by DoDispose(), LookupStatic(), NotifyAddAddress(), NotifyInterfaceUp(), NotifyRemoveAddress(), PrintRoutingTable(), RouteInput(), and SetIpv6().
m_multicastRoutes
MulticastRoutes ns3::Ipv6StaticRouting::m_multicastRoutes private
the forwarding table for multicast.
Definition at line 292 of file ipv6-static-routing.h.
Referenced by AddMulticastRoute(), DoDispose(), GetMulticastRoute(), GetNMulticastRoutes(), LookupStatic(), and RemoveMulticastRoute().
m_networkRoutes
NetworkRoutes ns3::Ipv6StaticRouting::m_networkRoutes private
the forwarding table for network.
Definition at line 287 of file ipv6-static-routing.h.
Referenced by AddNetworkRouteTo(), DoDispose(), GetDefaultRoute(), GetMetric(), GetNRoutes(), GetRoute(), HasNetworkDest(), LookupStatic(), NotifyInterfaceDown(), NotifyRemoveAddress(), NotifyRemoveRoute(), RemoveRoute(), and SetDefaultMulticastRoute().
The documentation for this class was generated from the following files:
src/internet/model/ipv6-static-routing.h
src/internet/model/ipv6-static-routing.cc