ns-3: ns3::SimpleNetDevice Class Reference
ns3::SimpleNetDevice Class Reference
Network » Network Device
This device assumes 48-bit mac addressing; there is also the possibility to add an ErrorModel if you want to force losses on the device.
#include "simple-net-device.h"
Public Member Functions
SimpleNetDevice ()
virtual void AddLinkChangeCallback (Callback< void > callback)
virtual Address GetAddress (void) const
virtual Address GetBroadcast (void) const
virtual Ptr< Channel > GetChannel (void) const
virtual uint32_t GetIfIndex (void) const
virtual uint16_t GetMtu (void) const
virtual Address GetMulticast (Ipv4Address multicastGroup) const
Make and return a MAC multicast address using the provided multicast group.
virtual Address GetMulticast (Ipv6Address addr) const
Get the MAC multicast address corresponding to the IPv6 address provided.
virtual Ptr< Node > GetNode (void) const
Ptr< Queue< Packet > > GetQueue (void) const
Get a copy of the attached Queue.
virtual bool IsBridge (void) const
Return true if the net device is acting as a bridge.
virtual bool IsBroadcast (void) const
virtual bool IsLinkUp (void) const
virtual bool IsMulticast (void) const
virtual bool IsPointToPoint (void) const
Return true if the net device is on a point-to-point link.
virtual bool NeedsArp (void) const
void Receive (Ptr< Packet > packet, uint16_t protocol, Mac48Address to, Mac48Address from)
Receive a packet from a connected SimpleChannel.
virtual bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)
virtual bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
virtual void SetAddress (Address address)
Set the address of this interface.
void SetChannel (Ptr< SimpleChannel > channel)
Attach a channel to this net device.
virtual void SetIfIndex (const uint32_t index)
virtual bool SetMtu (const uint16_t mtu)
virtual void SetNode (Ptr< Node > node)
virtual void SetPromiscReceiveCallback (PromiscReceiveCallback cb)
void SetQueue (Ptr< Queue< Packet > > queue)
Attach a queue to the SimpleNetDevice.
virtual void SetReceiveCallback (NetDevice::ReceiveCallback cb)
void SetReceiveErrorModel (Ptr< ErrorModel > em)
Attach a receive ErrorModel to the SimpleNetDevice.
virtual bool SupportsSendFrom (void) const
Public Member Functions inherited from ns3::NetDevice
virtual ~NetDevice ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::NetDevice
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void FinishTransmission (Ptr< Packet > packet)
The FinishTransmission method is used internally to finish the process of sending a packet out on the channel.
void StartTransmission (void)
The StartTransmission method is used internally to start the process of sending a packet out on the channel, by scheduling the FinishTransmission method at a time corresponding to the transmission delay of the packet.
Private Attributes
EventId FinishTransmissionEvent
the Tx Complete event
Mac48Address m_address
MAC address.
DataRate m_bps
The device nominal Data rate.
Ptr< SimpleChannel > m_channel
the channel the device is connected to
uint32_t m_ifIndex
Interface index.
TracedCallback m_linkChangeCallbacks
List of callbacks to fire if the link changes state (up or down).
bool m_linkUp
Flag indicating whether or not the link is up.
uint16_t m_mtu
MTU.
Ptr< Node > m_node
Node this netDevice is associated to.
TracedCallback< Ptr< const Packet > > m_phyRxDropTrace
The trace source fired when the phy layer drops a packet it has received due to the error model being active.
bool m_pointToPointMode
Flag indicating whether or not the NetDevice is a Point to Point model.
NetDevice::PromiscReceiveCallback m_promiscCallback
Promiscuous receive callback.
Ptr< Queue< Packet > > m_queue
The Queue for outgoing packets.
Ptr< ErrorModel > m_receiveErrorModel
Receive error model.
NetDevice::ReceiveCallback m_rxCallback
Receive callback.
Additional Inherited Members
Public Types inherited from ns3::NetDevice
typedef void(* LinkChangeTracedCallback) (void)
TracedCallback signature for link changed event.
enum PacketType {
PACKET_HOST = 1 , NS3_PACKET_HOST = PACKET_HOST , PACKET_BROADCAST , NS3_PACKET_BROADCAST = PACKET_BROADCAST ,
PACKET_MULTICAST , NS3_PACKET_MULTICAST = PACKET_MULTICAST , PACKET_OTHERHOST , NS3_PACKET_OTHERHOST = PACKET_OTHERHOST
}
Packet types are used as they are in Linux.
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address &, const Address &, enum PacketType > PromiscReceiveCallback
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address & > ReceiveCallback
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This device assumes 48-bit mac addressing; there is also the possibility to add an ErrorModel if you want to force losses on the device.
The device can be installed on a node through the SimpleNetDeviceHelper. In case of manual creation, the user is responsible for assigning an unique address to the device.
By default the device is in Broadcast mode, with infinite bandwidth.
simple net device for simple things and testing
Config Paths
ns3::SimpleNetDevice is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::SimpleNetDevice"
Attributes
ReceiveErrorModel: The receiver error model used to simulate packet loss
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::ErrorModel>
Initial value: 0x0
Flags: construct write read
PointToPointMode: The device is configured in Point to Point mode
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
TxQueue: A queue to use as the transmit queue in the device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::Queue<Packet>>
Initial value: ns3::DropTailQueue<Packet>
Flags: construct write read
DataRate: The default data rate for point to point links. Zero means infinite
Set with class: DataRateValue
Underlying type: DataRate
Initial value: 0bps
Flags: construct write read
TraceSources
PhyRxDrop: Trace source indicating a packet has been dropped by the device during reception
Callback signature: ns3::Packet::TracedCallback
Size of this type is 184 bytes (on a 64-bit architecture).
Definition at line 54 of file simple-net-device.h.
Constructor & Destructor Documentation
SimpleNetDevice()
ns3::SimpleNetDevice::SimpleNetDevice ()
Definition at line 222 of file simple-net-device.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddLinkChangeCallback()
void ns3::SimpleNetDevice::AddLinkChangeCallback (Callback< void > callback) virtual
Parameters
callback the callback to invoke
Add a callback invoked whenever the link status changes to UP. This callback is typically used by the IP/ARP layer to flush the ARP cache and by IPv6 stack to flush NDISC cache whenever the link goes up.
Implements ns3::NetDevice.
Definition at line 357 of file simple-net-device.cc.
References ns3::TracedCallback< Ts >::ConnectWithoutContext(), m_linkChangeCallbacks, and NS_LOG_FUNCTION.
DoDispose()
void ns3::SimpleNetDevice::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Reimplemented in ns3::LteSimpleNetDevice.
Definition at line 536 of file simple-net-device.cc.
References ns3::EventId::Cancel(), ns3::Object::DoDispose(), FinishTransmissionEvent, ns3::EventId::IsRunning(), m_channel, m_node, m_queue, m_receiveErrorModel, and NS_LOG_FUNCTION.
Referenced by ns3::LteSimpleNetDevice::DoDispose().
FinishTransmission()
void ns3::SimpleNetDevice::FinishTransmission (Ptr< Packet > packet) private
The FinishTransmission method is used internally to finish the process of sending a packet out on the channel.
Parameters
packet The packet to send on the channel
Definition at line 488 of file simple-net-device.cc.
References ns3::SimpleTag::GetDst(), ns3::SimpleTag::GetProto(), ns3::SimpleTag::GetSrc(), m_channel, NS_LOG_FUNCTION, ns3::Packet::RemovePacketTag(), and StartTransmission().
Referenced by StartTransmission().
GetAddress()
Address ns3::SimpleNetDevice::GetAddress (void) const virtual
Returns
the current Address of this interface.
Implements ns3::NetDevice.
Definition at line 329 of file simple-net-device.cc.
References m_address, and NS_LOG_FUNCTION.
GetBroadcast()
Address ns3::SimpleNetDevice::GetBroadcast (void) const virtual
Returns
the broadcast address supported by this netdevice.
Calling this method is invalid if IsBroadcast returns not true.
Implements ns3::NetDevice.
Definition at line 373 of file simple-net-device.cc.
References NS_LOG_FUNCTION.
GetChannel()
Ptr< Channel > ns3::SimpleNetDevice::GetChannel (void) const virtual
Returns
the channel this NetDevice is connected to. The value returned can be zero if the NetDevice is not yet connected to any channel or if the underlying NetDevice has no concept of a channel. i.e., callers must check for zero and be ready to handle it.
Implements ns3::NetDevice.
Definition at line 317 of file simple-net-device.cc.
References m_channel, and NS_LOG_FUNCTION.
GetIfIndex()
uint32_t ns3::SimpleNetDevice::GetIfIndex (void) const virtual
Returns
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 311 of file simple-net-device.cc.
References m_ifIndex, and NS_LOG_FUNCTION.
GetMtu()
uint16_t ns3::SimpleNetDevice::GetMtu (void) const virtual
Returns
the link-level MTU in bytes for this interface.
This value is typically used by the IP layer to perform IP fragmentation when needed.
Implements ns3::NetDevice.
Definition at line 345 of file simple-net-device.cc.
References m_mtu, and NS_LOG_FUNCTION.
Referenced by SendFrom().
GetMulticast() [1/2]
Address ns3::SimpleNetDevice::GetMulticast (Ipv4Address multicastGroup) const virtual
Make and return a MAC multicast address using the provided multicast group.
RFC 1112 says that an Ipv4 host group address is mapped to an Ethernet multicast address by placing the low-order 23-bits of the IP address into the low-order 23 bits of the Ethernet multicast address 01-00-5E-00-00-00 (hex). Similar RFCs exist for Ipv6 and Eui64 mappings. This method performs the multicast address creation function appropriate to the underlying MAC address of the device. This MAC address is encapsulated in an abstract Address to avoid dependencies on the exact MAC address format.
In the case of net devices that do not support multicast, clients are expected to test NetDevice::IsMulticast and avoid attempting to map multicast packets. Subclasses of NetDevice that do support multicasting are expected to override this method and provide an implementation appropriate to the particular device.
Parameters
multicastGroup The IP address for the multicast group destination of the packet.
Returns
The MAC multicast Address used to send packets to the provided multicast group.
Warning
Calling this method is invalid if IsMulticast returns not true.
See also
IsMulticast()
Implements ns3::NetDevice.
Definition at line 389 of file simple-net-device.cc.
References ns3::Mac48Address::GetMulticast(), and NS_LOG_FUNCTION.
GetMulticast() [2/2]
Address ns3::SimpleNetDevice::GetMulticast (Ipv6Address addr) const virtual
Get the MAC multicast address corresponding to the IPv6 address provided.
Parameters
addr IPv6 address
Returns
the MAC multicast address
Warning
Calling this method is invalid if IsMulticast returns not true.
Implements ns3::NetDevice.
Definition at line 395 of file simple-net-device.cc.
References ns3::Mac48Address::GetMulticast(), and NS_LOG_FUNCTION.
GetNode()
Ptr< Node > ns3::SimpleNetDevice::GetNode (void) const virtual
Returns
the node base class which contains this network interface.
When a subclass needs to get access to the underlying node base class to print the nodeid for example, it can invoke this method.
Implements ns3::NetDevice.
Definition at line 507 of file simple-net-device.cc.
References m_node, and NS_LOG_FUNCTION.
GetQueue()
Ptr< Queue< Packet > > ns3::SimpleNetDevice::GetQueue (void) const
Get a copy of the attached Queue.
Returns
Ptr to the queue.
Definition at line 284 of file simple-net-device.cc.
References m_queue, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::SimpleNetDevice::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 187 of file simple-net-device.cc.
References m_bps, m_phyRxDropTrace, m_pointToPointMode, m_queue, m_receiveErrorModel, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeDataRateAccessor(), ns3::MakeDataRateChecker(), ns3::MakePointerAccessor(), ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
IsBridge()
bool ns3::SimpleNetDevice::IsBridge (void) const virtual
Return true if the net device is acting as a bridge.
Returns
value of m_isBridge flag
Implements ns3::NetDevice.
Definition at line 413 of file simple-net-device.cc.
References NS_LOG_FUNCTION.
IsBroadcast()
bool ns3::SimpleNetDevice::IsBroadcast (void) const virtual
Returns
true if this interface supports a broadcast address, false otherwise.
Implements ns3::NetDevice.
Definition at line 363 of file simple-net-device.cc.
References m_pointToPointMode, and NS_LOG_FUNCTION.
IsLinkUp()
bool ns3::SimpleNetDevice::IsLinkUp (void) const virtual
Returns
true if link is up; false otherwise
Implements ns3::NetDevice.
Definition at line 351 of file simple-net-device.cc.
References m_linkUp, and NS_LOG_FUNCTION.
IsMulticast()
bool ns3::SimpleNetDevice::IsMulticast (void) const virtual
Returns
value of m_isMulticast flag
Implements ns3::NetDevice.
Definition at line 379 of file simple-net-device.cc.
References m_pointToPointMode, and NS_LOG_FUNCTION.
IsPointToPoint()
bool ns3::SimpleNetDevice::IsPointToPoint (void) const virtual
Return true if the net device is on a point-to-point link.
Returns
value of m_isPointToPoint flag
Implements ns3::NetDevice.
Definition at line 402 of file simple-net-device.cc.
References m_pointToPointMode, and NS_LOG_FUNCTION.
NeedsArp()
bool ns3::SimpleNetDevice::NeedsArp (void) const virtual
Returns
true if ARP is needed, false otherwise.
Called by higher-layers to check if this NetDevice requires ARP to be used.
Implements ns3::NetDevice.
Definition at line 519 of file simple-net-device.cc.
References m_pointToPointMode, and NS_LOG_FUNCTION.
Receive()
void ns3::SimpleNetDevice::Receive (Ptr< Packet > packet, uint16_t protocol, Mac48Address to, Mac48Address from)
Receive a packet from a connected SimpleChannel.
The SimpleNetDevice receives packets from its connected channel and then forwards them by calling its rx callback method
Parameters
packet Packet received on the channel
protocol protocol number
to address packet should be sent to
from address packet was sent from
Definition at line 233 of file simple-net-device.cc.
References ns3::Mac48Address::IsBroadcast(), ns3::Mac48Address::IsGroup(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_address, m_phyRxDropTrace, m_promiscCallback, m_receiveErrorModel, m_rxCallback, NS_LOG_FUNCTION, ns3::NetDevice::PACKET_BROADCAST, ns3::NetDevice::PACKET_HOST, ns3::NetDevice::PACKET_MULTICAST, and ns3::NetDevice::PACKET_OTHERHOST.
Referenced by ns3::ErrorChannel::Send(), and ns3::SimpleChannel::Send().
Send()
bool ns3::SimpleNetDevice::Send (Ptr< Packet > packet, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device to the specified destination Address
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Reimplemented in ns3::LteSimpleNetDevice.
Definition at line 420 of file simple-net-device.cc.
References m_address, NS_LOG_FUNCTION, and SendFrom().
Referenced by ns3::LteSimpleNetDevice::Send().
SendFrom()
bool ns3::SimpleNetDevice::SendFrom (Ptr< Packet > packet, const Address & source, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
source source mac address (so called "MAC spoofing")
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device with the specified source and destination Addresses.
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 428 of file simple-net-device.cc.
References ns3::Packet::AddPacketTag(), ns3::Mac48Address::ConvertFrom(), FinishTransmissionEvent, GetMtu(), ns3::Packet::GetSize(), ns3::EventId::IsRunning(), m_queue, NS_LOG_FUNCTION, ns3::SimpleTag::SetDst(), ns3::SimpleTag::SetProto(), ns3::SimpleTag::SetSrc(), and StartTransmission().
Referenced by Send().
SetAddress()
void ns3::SimpleNetDevice::SetAddress (Address address) virtual
Set the address of this interface.
Parameters
address address to set
Implements ns3::NetDevice.
Definition at line 323 of file simple-net-device.cc.
References first::address, ns3::Mac48Address::ConvertFrom(), m_address, and NS_LOG_FUNCTION.
SetChannel()
void ns3::SimpleNetDevice::SetChannel (Ptr< SimpleChannel > channel)
Attach a channel to this net device.
This will be the channel the net device sends on
Parameters
channel channel to assign to this net device
Definition at line 274 of file simple-net-device.cc.
References third::channel, m_channel, m_linkChangeCallbacks, m_linkUp, and NS_LOG_FUNCTION.
SetIfIndex()
void ns3::SimpleNetDevice::SetIfIndex (const uint32_t index) virtual
Parameters
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 305 of file simple-net-device.cc.
References m_ifIndex, and NS_LOG_FUNCTION.
SetMtu()
bool ns3::SimpleNetDevice::SetMtu (const uint16_t mtu) virtual
Parameters
mtu MTU value, in bytes, to set for the device
Returns
whether the MTU value was within legal bounds
Override for default MTU defined on a per-type basis.
Implements ns3::NetDevice.
Definition at line 338 of file simple-net-device.cc.
References m_mtu, and NS_LOG_FUNCTION.
SetNode()
void ns3::SimpleNetDevice::SetNode (Ptr< Node > node) virtual
Parameters
node the node associated to this netdevice.
This method is called from ns3::Node::AddDevice.
Implements ns3::NetDevice.
Definition at line 513 of file simple-net-device.cc.
References m_node, and NS_LOG_FUNCTION.
Referenced by ns3::LteSimpleNetDevice::LteSimpleNetDevice().
SetPromiscReceiveCallback()
void ns3::SimpleNetDevice::SetPromiscReceiveCallback (PromiscReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received in promiscuous mode and must be forwarded to the higher layers.
Enables netdevice promiscuous mode and sets the callback that will handle promiscuous mode packets. Note, promiscuous mode packets means all packets, including those packets that can be sensed by the netdevice but which are intended to be received by other hosts.
Implements ns3::NetDevice.
Definition at line 552 of file simple-net-device.cc.
References m_promiscCallback, and NS_LOG_FUNCTION.
SetQueue()
void ns3::SimpleNetDevice::SetQueue (Ptr< Queue< Packet > > queue)
Attach a queue to the SimpleNetDevice.
Parameters
queue Ptr to the new queue.
Definition at line 291 of file simple-net-device.cc.
References m_queue, and NS_LOG_FUNCTION.
SetReceiveCallback()
void ns3::SimpleNetDevice::SetReceiveCallback (NetDevice::ReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received and must be forwarded to the higher layers.
Set the callback to be used to notify higher layers when a packet has been received.
Implements ns3::NetDevice.
Definition at line 529 of file simple-net-device.cc.
References m_rxCallback, and NS_LOG_FUNCTION.
SetReceiveErrorModel()
void ns3::SimpleNetDevice::SetReceiveErrorModel (Ptr< ErrorModel > em)
Attach a receive ErrorModel to the SimpleNetDevice.
The SimpleNetDevice may optionally include an ErrorModel in the packet receive chain.
See also
ErrorModel
Parameters
em Ptr to the ErrorModel.
Definition at line 298 of file simple-net-device.cc.
References m_receiveErrorModel, and NS_LOG_FUNCTION.
StartTransmission()
void ns3::SimpleNetDevice::StartTransmission (void) private
The StartTransmission method is used internally to start the process of sending a packet out on the channel, by scheduling the FinishTransmission method at a time corresponding to the transmission delay of the packet.
SimpleChannel will deliver the packet to the far end(s) of the link as soon as Send is called (or after its fixed delay, if one is configured). So we have to handle the rate of the link here, which we do by scheduling FinishTransmission (packetSize / linkRate) time in the future. While that event is running, the transmit path of this NetDevice is busy, so we can't send other packets.
SimpleChannel doesn't have a locking mechanism, and doesn't check for collisions, so there's nothing we need to do with the channel until the transmission has "completed" from the perspective of this NetDevice.
Definition at line 459 of file simple-net-device.cc.
References ns3::DataRate::CalculateBytesTxTime(), FinishTransmission(), FinishTransmissionEvent, ns3::Packet::GetSize(), ns3::EventId::IsRunning(), m_bps, m_queue, NS_ASSERT_MSG, and ns3::Simulator::Schedule().
Referenced by FinishTransmission(), and SendFrom().
SupportsSendFrom()
bool ns3::SimpleNetDevice::SupportsSendFrom (void) const virtual
Returns
true if this interface supports a bridging mode, false otherwise.
Implements ns3::NetDevice.
Definition at line 559 of file simple-net-device.cc.
References NS_LOG_FUNCTION.
Member Data Documentation
FinishTransmissionEvent
EventId ns3::SimpleNetDevice::FinishTransmissionEvent private
the Tx Complete event
Definition at line 186 of file simple-net-device.h.
Referenced by DoDispose(), SendFrom(), and StartTransmission().
m_address
Mac48Address ns3::SimpleNetDevice::m_address private
MAC address.
Definition at line 148 of file simple-net-device.h.
Referenced by GetAddress(), Receive(), Send(), and SetAddress().
m_bps
DataRate ns3::SimpleNetDevice::m_bps private
The device nominal Data rate.
Zero means infinite
Definition at line 185 of file simple-net-device.h.
Referenced by GetTypeId(), and StartTransmission().
m_channel
Ptr<SimpleChannel> ns3::SimpleNetDevice::m_channel private
the channel the device is connected to
Definition at line 142 of file simple-net-device.h.
Referenced by DoDispose(), FinishTransmission(), GetChannel(), and SetChannel().
m_ifIndex
uint32_t ns3::SimpleNetDevice::m_ifIndex private
Interface index.
Definition at line 147 of file simple-net-device.h.
Referenced by GetIfIndex(), and SetIfIndex().
m_linkChangeCallbacks
TracedCallback ns3::SimpleNetDevice::m_linkChangeCallbacks private
List of callbacks to fire if the link changes state (up or down).
Definition at line 191 of file simple-net-device.h.
Referenced by AddLinkChangeCallback(), and SetChannel().
m_linkUp
bool ns3::SimpleNetDevice::m_linkUp private
Flag indicating whether or not the link is up.
Definition at line 176 of file simple-net-device.h.
Referenced by IsLinkUp(), and SetChannel().
m_mtu
uint16_t ns3::SimpleNetDevice::m_mtu private
MTU.
Definition at line 146 of file simple-net-device.h.
Referenced by GetMtu(), and SetMtu().
m_node
Ptr<Node> ns3::SimpleNetDevice::m_node private
Node this netDevice is associated to.
Definition at line 145 of file simple-net-device.h.
Referenced by DoDispose(), GetNode(), and SetNode().
m_phyRxDropTrace
TracedCallback<Ptr<const Packet> > ns3::SimpleNetDevice::m_phyRxDropTrace private
The trace source fired when the phy layer drops a packet it has received due to the error model being active.
Although SimpleNetDevice doesn't really have a Phy model, we choose this trace source name for alignment with other trace sources.
See also
class CallBackTraceSource
Definition at line 159 of file simple-net-device.h.
Referenced by GetTypeId(), and Receive().
m_pointToPointMode
bool ns3::SimpleNetDevice::m_pointToPointMode private
Flag indicating whether or not the NetDevice is a Point to Point model.
Enabling this will disable Broadcast and Arp.
Definition at line 182 of file simple-net-device.h.
Referenced by GetTypeId(), IsBroadcast(), IsMulticast(), IsPointToPoint(), and NeedsArp().
m_promiscCallback
NetDevice::PromiscReceiveCallback ns3::SimpleNetDevice::m_promiscCallback private
Promiscuous receive callback.
Definition at line 144 of file simple-net-device.h.
Referenced by Receive(), and SetPromiscReceiveCallback().
m_queue
Ptr<Queue<Packet> > ns3::SimpleNetDevice::m_queue private
The Queue for outgoing packets.
Definition at line 184 of file simple-net-device.h.
Referenced by DoDispose(), GetQueue(), GetTypeId(), SendFrom(), SetQueue(), and StartTransmission().
m_receiveErrorModel
Ptr<ErrorModel> ns3::SimpleNetDevice::m_receiveErrorModel private
Receive error model.
Definition at line 149 of file simple-net-device.h.
Referenced by DoDispose(), GetTypeId(), Receive(), and SetReceiveErrorModel().
m_rxCallback
NetDevice::ReceiveCallback ns3::SimpleNetDevice::m_rxCallback private
Receive callback.
Definition at line 143 of file simple-net-device.h.
Referenced by Receive(), and SetReceiveCallback().
The documentation for this class was generated from the following files:
src/network/utils/simple-net-device.h
src/network/utils/simple-net-device.cc