ns-3: ns3::UanHeaderRcCts Class Reference
ns3::UanHeaderRcCts Class Reference
UAN Models
CTS header.
#include "uan-header-rc.h"
Public Member Functions
UanHeaderRcCts ()
Default constructor.
UanHeaderRcCts (uint8_t frameNo, uint8_t retryNo, Time rtsTs, Time delay, Mac8Address addr)
Constructor.
virtual ~UanHeaderRcCts ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Mac8Address GetAddress (void) const
Get the destination address, for scheduling info.
Time GetDelayToTx (void) const
Get the time delay from TX time of CTS packet until arrival of first data frame.
uint8_t GetFrameNo (void) const
Get the frame number of the RTS being cleared.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint8_t GetRetryNo (void) const
Get the retry number of the RTS packet being cleared.
Time GetRtsTimeStamp (void) const
Get the receive time of the RTS being cleared.
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
void Print (std::ostream &os, Time::Unit unit) const
Specialized Print with Time::Unit declared.
virtual void Serialize (Buffer::Iterator start) const
void SetAddress (Mac8Address addr)
Set the destination address, for scheduling info.
void SetDelayToTx (Time delay)
Set the time delay from CTS transmission to first data frame arrival.
void SetFrameNo (uint8_t frameNo)
Set the RTS frame number being cleared.
void SetRetryNo (uint8_t no)
Set the retry number of the RTS frame being cleared.
void SetRtsTimeStamp (Time timeStamp)
Set the timestamp for RTS reception.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Mac8Address m_address
Destination of CTS packet.
Time m_delay
Delay until transmission.
uint8_t m_frameNo
Reservation frame number being cleared.
uint8_t m_retryNo
Retry number of received RTS packet.
Time m_timeStampRts
RX time of RTS packet at gateway.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
CTS header.
Introspection did not find any typical Config paths.
Includes RTS RX time, CTS TX time, delay until TX, RTS blocking period, RTS tx period, rate #, and retry rate #
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 56 bytes (on a 64-bit architecture).
Definition at line 342 of file uan-header-rc.h.
Constructor & Destructor Documentation
UanHeaderRcCts() [1/2]
ns3::UanHeaderRcCts::UanHeaderRcCts ()
Default constructor.
Definition at line 406 of file uan-header-rc.cc.
UanHeaderRcCts() [2/2]
ns3::UanHeaderRcCts::UanHeaderRcCts (uint8_t frameNo, uint8_t retryNo, Time rtsTs, Time delay, Mac8Address addr)
Constructor.
Parameters
frameNo Reservation frame # being cleared.
retryNo Retry # of received RTS packet.
rtsTs RX time of RTS packet at gateway.
delay Delay until transmission.
addr Destination of CTS packet.
Note
Times are serialized, with ms precision, into 32 bit fields.
Definition at line 417 of file uan-header-rc.cc.
~UanHeaderRcCts()
ns3::UanHeaderRcCts::~UanHeaderRcCts () virtual
Destructor.
Definition at line 428 of file uan-header-rc.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::UanHeaderRcCts::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 525 of file uan-header-rc.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_address, m_delay, m_frameNo, m_retryNo, m_timeStampRts, ns3::Buffer::Iterator::ReadU32(), ns3::Buffer::Iterator::ReadU8(), ns3::Seconds(), and visualizer.core::start().
GetAddress()
Mac8Address ns3::UanHeaderRcCts::GetAddress (void) const
Get the destination address, for scheduling info.
Returns
The destination address.
Definition at line 500 of file uan-header-rc.cc.
References m_address.
Referenced by ns3::UanMacRc::ReceiveOkFromPhy().
GetDelayToTx()
Time ns3::UanHeaderRcCts::GetDelayToTx (void) const
Get the time delay from TX time of CTS packet until arrival of first data frame.
Returns
The delay time.
Definition at line 488 of file uan-header-rc.cc.
References m_delay.
Referenced by ns3::UanMacRc::ScheduleData().
GetFrameNo()
uint8_t ns3::UanHeaderRcCts::GetFrameNo (void) const
Get the frame number of the RTS being cleared.
Returns
The frame number.
Definition at line 476 of file uan-header-rc.cc.
References m_frameNo.
Referenced by ns3::UanMacRc::ScheduleData().
GetInstanceTypeId()
TypeId ns3::UanHeaderRcCts::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 550 of file uan-header-rc.cc.
References GetTypeId().
GetRetryNo()
uint8_t ns3::UanHeaderRcCts::GetRetryNo (void) const
Get the retry number of the RTS packet being cleared.
Returns
The retry number
Definition at line 494 of file uan-header-rc.cc.
References m_retryNo.
GetRtsTimeStamp()
Time ns3::UanHeaderRcCts::GetRtsTimeStamp (void) const
Get the receive time of the RTS being cleared.
Returns
The RX time.
Definition at line 482 of file uan-header-rc.cc.
References m_timeStampRts.
GetSerializedSize()
uint32_t ns3::UanHeaderRcCts::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 506 of file uan-header-rc.cc.
Referenced by ns3::UanMacRc::UanMacRc(), and ns3::UanMacRcGw::UanMacRcGw().
GetTypeId()
TypeId ns3::UanHeaderRcCts::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 434 of file uan-header-rc.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print() [1/2]
void ns3::UanHeaderRcCts::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 544 of file uan-header-rc.cc.
References Print(), and ns3::Time::S.
Print() [2/2]
void ns3::UanHeaderRcCts::Print (std::ostream & os, Time::Unit unit) const
Specialized Print with Time::Unit declared.
Parameters
os ostream.
unit Time unit.
Definition at line 538 of file uan-header-rc.cc.
References ns3::Time::As(), m_address, m_delay, m_frameNo, m_retryNo, and m_timeStampRts.
Referenced by Print().
Serialize()
void ns3::UanHeaderRcCts::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 513 of file uan-header-rc.cc.
References first::address, ns3::Mac8Address::CopyTo(), ns3::Time::GetMilliSeconds(), m_address, m_delay, m_frameNo, m_retryNo, m_timeStampRts, ns3::Time::MS, ns3::Time::RoundTo(), and visualizer.core::start().
SetAddress()
void ns3::UanHeaderRcCts::SetAddress (Mac8Address addr)
Set the destination address, for scheduling info.
Parameters
addr The destination address.
Definition at line 471 of file uan-header-rc.cc.
References m_address.
Referenced by ns3::UanMacRc::ReceiveOkFromPhy(), and ns3::UanMacRcGw::StartCycle().
SetDelayToTx()
void ns3::UanHeaderRcCts::SetDelayToTx (Time delay)
Set the time delay from CTS transmission to first data frame arrival.
Parameters
delay The delay time.
Definition at line 459 of file uan-header-rc.cc.
References m_delay.
Referenced by ns3::UanMacRcGw::StartCycle().
SetFrameNo()
void ns3::UanHeaderRcCts::SetFrameNo (uint8_t frameNo)
Set the RTS frame number being cleared.
Parameters
frameNo The frame number.
Definition at line 446 of file uan-header-rc.cc.
References m_frameNo.
Referenced by ns3::UanMacRcGw::StartCycle().
SetRetryNo()
void ns3::UanHeaderRcCts::SetRetryNo (uint8_t no)
Set the retry number of the RTS frame being cleared.
Parameters
no The retry number.
Definition at line 465 of file uan-header-rc.cc.
References m_retryNo.
Referenced by ns3::UanMacRcGw::StartCycle().
SetRtsTimeStamp()
void ns3::UanHeaderRcCts::SetRtsTimeStamp (Time timeStamp)
Set the timestamp for RTS reception.
Parameters
timeStamp The timestamp.
Definition at line 452 of file uan-header-rc.cc.
References m_timeStampRts.
Referenced by ns3::UanMacRcGw::StartCycle().
Member Data Documentation
m_address
Mac8Address ns3::UanHeaderRcCts::m_address private
Destination of CTS packet.
Definition at line 449 of file uan-header-rc.h.
Referenced by Deserialize(), GetAddress(), Print(), Serialize(), and SetAddress().
m_delay
Time ns3::UanHeaderRcCts::m_delay private
Delay until transmission.
Definition at line 448 of file uan-header-rc.h.
Referenced by Deserialize(), GetDelayToTx(), Print(), Serialize(), and SetDelayToTx().
m_frameNo
uint8_t ns3::UanHeaderRcCts::m_frameNo private
Reservation frame number being cleared.
Definition at line 445 of file uan-header-rc.h.
Referenced by Deserialize(), GetFrameNo(), Print(), Serialize(), and SetFrameNo().
m_retryNo
uint8_t ns3::UanHeaderRcCts::m_retryNo private
Retry number of received RTS packet.
Definition at line 447 of file uan-header-rc.h.
Referenced by Deserialize(), GetRetryNo(), Print(), Serialize(), and SetRetryNo().
m_timeStampRts
Time ns3::UanHeaderRcCts::m_timeStampRts private
RX time of RTS packet at gateway.
Definition at line 446 of file uan-header-rc.h.
Referenced by Deserialize(), GetRtsTimeStamp(), Print(), Serialize(), and SetRtsTimeStamp().
The documentation for this class was generated from the following files:
src/uan/model/uan-header-rc.h
src/uan/model/uan-header-rc.cc