ns-3: ns3::DynamicQueueLimits Class Reference
ns3::DynamicQueueLimits Class Reference
Network
DynamicQueueLimits would be used in conjunction with a producer/consumer type queue (possibly a netdevice queue).
#include "dynamic-queue-limits.h"
Public Member Functions
DynamicQueueLimits ()
virtual ~DynamicQueueLimits ()
virtual int32_t Available () const
Available is called from NotifyTransmittedBytes to calculate the number of bytes that can be passed again to the NetDevice.
virtual void Completed (uint32_t count)
Record number of completed bytes and recalculate the limit.
virtual void Queued (uint32_t count)
Record the number of bytes queued.
virtual void Reset ()
Reset queue limits state.
Public Member Functions inherited from ns3::QueueLimits
virtual ~QueueLimits ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::QueueLimits
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
int32_t Posdiff (int32_t a, int32_t b)
Calculates the difference between the two operators and returns the number if positive, zero otherwise.
Private Attributes
uint32_t m_adjLimit {0}
limit + num_completed
uint32_t m_lastObjCnt {0}
Count at last queuing.
TracedValue< uint32_t > m_limit
Current limit.
uint32_t m_lowestSlack {std::numeric_limits<uint32_t>::max ()}
Lowest slack found.
uint32_t m_maxLimit
Max limit.
uint32_t m_minLimit
Minimum limit.
uint32_t m_numCompleted {0}
Total ever completed.
uint32_t m_numQueued {0}
Total ever queued.
uint32_t m_prevLastObjCnt {0}
Previous queuing cnt.
uint32_t m_prevNumQueued {0}
Previous queue total.
uint32_t m_prevOvlimit {0}
Previous over limit.
Time m_slackHoldTime
Time to measure slack.
Time m_slackStartTime {Seconds (0)}
Time slacks seen.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
DynamicQueueLimits would be used in conjunction with a producer/consumer type queue (possibly a netdevice queue).
Introspection did not find any typical Config paths.
Such a queue would have these general properties:
1) Objects are queued up to some limit specified as number of objects. 2) Periodically a completion process executes which retires consumed objects. 3) Starvation occurs when limit has been reached, all queued data has actually been consumed, but completion processing has not yet run so queuing new data is blocked. 4) Minimizing the amount of queued data is desirable.
The goal of DynamicQueueLimits is to calculate the limit as the minimum number of objects needed to prevent starvation.
The primary functions of DynamicQueueLimits are: Completed - called at completion time to indicate how many objects were retired from the queue Available - returns how many objects are available to be queued based on the object limit and how many objects are already enqueued Queued - called when objects are enqueued to record number of objects
Attributes
HoldTime: The DQL algorithm hold time
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: 1s
Flags: construct write read
MaxLimit: Maximum limit
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:1879048192
Initial value: 1879048192
Flags: construct write read
MinLimit: Minimum limit
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 0
Flags: construct write read
TraceSources
Limit: Limit value calculated by DQL
Callback signature: ns3::TracedValueCallback::Uint32
Size of this type is 120 bytes (on a 64-bit architecture).
Definition at line 63 of file dynamic-queue-limits.h.
Constructor & Destructor Documentation
DynamicQueueLimits()
ns3::DynamicQueueLimits::DynamicQueueLimits ()
Definition at line 74 of file dynamic-queue-limits.cc.
References NS_LOG_FUNCTION, and Reset().
~DynamicQueueLimits()
ns3::DynamicQueueLimits::~DynamicQueueLimits () virtual
Definition at line 80 of file dynamic-queue-limits.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Available()
int32_t ns3::DynamicQueueLimits::Available () const virtual
Available is called from NotifyTransmittedBytes to calculate the number of bytes that can be passed again to the NetDevice.
A negative value means that no packets can be passed to the NetDevice. In this case, NotifyTransmittedBytes stops the transmission queue.
Returns how many bytes can be queued
Returns
the number of bytes that can be queued
Implements ns3::QueueLimits.
Definition at line 206 of file dynamic-queue-limits.cc.
References m_adjLimit, m_numQueued, and NS_LOG_FUNCTION.
Completed()
void ns3::DynamicQueueLimits::Completed (uint32_t count) virtual
Record number of completed bytes and recalculate the limit.
Parameters
count the number of completed bytes
Implements ns3::QueueLimits.
Definition at line 102 of file dynamic-queue-limits.cc.
References m_adjLimit, m_lastObjCnt, m_limit, m_lowestSlack, m_maxLimit, m_minLimit, m_numCompleted, m_numQueued, m_prevLastObjCnt, m_prevNumQueued, m_prevOvlimit, m_slackHoldTime, m_slackStartTime, max, min, ns3::Simulator::Now(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, Posdiff(), and UINTMAX.
GetTypeId()
TypeId ns3::DynamicQueueLimits::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 44 of file dynamic-queue-limits.cc.
References DQL_MAX_LIMIT, m_limit, m_maxLimit, m_minLimit, m_slackHoldTime, ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
Posdiff()
int32_t ns3::DynamicQueueLimits::Posdiff (int32_t a, int32_t b) private
Calculates the difference between the two operators and returns the number if positive, zero otherwise.
Parameters
a First operator.
b Second operator.
Returns
the difference between a and b if positive, zero otherwise.
Definition at line 223 of file dynamic-queue-limits.cc.
References max, and NS_LOG_FUNCTION.
Referenced by Completed().
Queued()
void ns3::DynamicQueueLimits::Queued (uint32_t count) virtual
Record the number of bytes queued.
Parameters
count the number of bytes queued
Implements ns3::QueueLimits.
Definition at line 213 of file dynamic-queue-limits.cc.
References DQL_MAX_OBJECT, m_lastObjCnt, m_numQueued, NS_ASSERT, and NS_LOG_FUNCTION.
Reset()
void ns3::DynamicQueueLimits::Reset () virtual
Reset queue limits state.
Implements ns3::QueueLimits.
Definition at line 86 of file dynamic-queue-limits.cc.
References m_lastObjCnt, m_limit, m_lowestSlack, m_numCompleted, m_numQueued, m_prevLastObjCnt, m_prevNumQueued, m_prevOvlimit, m_slackStartTime, ns3::Simulator::Now(), NS_LOG_FUNCTION, and UINTMAX.
Referenced by DynamicQueueLimits().
Member Data Documentation
m_adjLimit
uint32_t ns3::DynamicQueueLimits::m_adjLimit {0} private
limit + num_completed
Definition at line 91 of file dynamic-queue-limits.h.
Referenced by Available(), and Completed().
m_lastObjCnt
uint32_t ns3::DynamicQueueLimits::m_lastObjCnt {0} private
Count at last queuing.
Definition at line 92 of file dynamic-queue-limits.h.
Referenced by Completed(), Queued(), and Reset().
m_limit
TracedValue<uint32_t> ns3::DynamicQueueLimits::m_limit private
Current limit.
Definition at line 95 of file dynamic-queue-limits.h.
Referenced by Completed(), GetTypeId(), and Reset().
m_lowestSlack
uint32_t ns3::DynamicQueueLimits::m_lowestSlack {std::numeric_limits<uint32_t>::max ()} private
Lowest slack found.
Definition at line 102 of file dynamic-queue-limits.h.
Referenced by Completed(), and Reset().
m_maxLimit
uint32_t ns3::DynamicQueueLimits::m_maxLimit private
Max limit.
Definition at line 106 of file dynamic-queue-limits.h.
Referenced by Completed(), and GetTypeId().
m_minLimit
uint32_t ns3::DynamicQueueLimits::m_minLimit private
Minimum limit.
Definition at line 107 of file dynamic-queue-limits.h.
Referenced by Completed(), and GetTypeId().
m_numCompleted
uint32_t ns3::DynamicQueueLimits::m_numCompleted {0} private
Total ever completed.
Definition at line 96 of file dynamic-queue-limits.h.
Referenced by Completed(), and Reset().
m_numQueued
uint32_t ns3::DynamicQueueLimits::m_numQueued {0} private
Total ever queued.
Definition at line 90 of file dynamic-queue-limits.h.
Referenced by Available(), Completed(), Queued(), and Reset().
m_prevLastObjCnt
uint32_t ns3::DynamicQueueLimits::m_prevLastObjCnt {0} private
Previous queuing cnt.
Definition at line 100 of file dynamic-queue-limits.h.
Referenced by Completed(), and Reset().
m_prevNumQueued
uint32_t ns3::DynamicQueueLimits::m_prevNumQueued {0} private
Previous queue total.
Definition at line 99 of file dynamic-queue-limits.h.
Referenced by Completed(), and Reset().
m_prevOvlimit
uint32_t ns3::DynamicQueueLimits::m_prevOvlimit {0} private
Previous over limit.
Definition at line 98 of file dynamic-queue-limits.h.
Referenced by Completed(), and Reset().
m_slackHoldTime
Time ns3::DynamicQueueLimits::m_slackHoldTime private
Time to measure slack.
Definition at line 108 of file dynamic-queue-limits.h.
Referenced by Completed(), and GetTypeId().
m_slackStartTime
Time ns3::DynamicQueueLimits::m_slackStartTime {Seconds (0)} private
Time slacks seen.
Definition at line 103 of file dynamic-queue-limits.h.
Referenced by Completed(), and Reset().
The documentation for this class was generated from the following files:
src/network/utils/dynamic-queue-limits.h
src/network/utils/dynamic-queue-limits.cc