ns-3: ns3::Trailer Class Reference
ns3::Trailer Class Reference abstract
Network » Packet
Protocol trailer serialization and deserialization.
#include "trailer.h"
Public Member Functions
virtual ~Trailer ()
virtual uint32_t Deserialize (Buffer::Iterator end)=0
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
virtual uint32_t GetSerializedSize (void) const =0
virtual void Print (std::ostream &os) const =0
virtual void Serialize (Buffer::Iterator start) const =0
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
virtual TypeId GetInstanceTypeId (void) const =0
Get the most derived TypeId for this Object.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Protocol trailer serialization and deserialization.
Introspection did not find any typical Config paths.
Every Protocol trailer which needs to be inserted or removed from a Packet instance must derive from this base class and implement the pure virtual methods defined here.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 8 bytes (on a 64-bit architecture).
Definition at line 40 of file trailer.h.
Constructor & Destructor Documentation
~Trailer()
ns3::Trailer::~Trailer () virtual
Definition at line 30 of file trailer.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Deserialize() [1/2]
virtual uint32_t ns3::Trailer::Deserialize (Buffer::Iterator end) pure virtual
Parameters
end an iterator which points to the end of the buffer where the trailer should be read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveTrailer to re-create a trailer from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this trailer in real networks. The input iterator points to the end of the area where the data shall be written. This method is thus expected to call Buffer::Iterator::Prev prior to actually reading any data.
Implements ns3::Chunk.
Implemented in ns3::WifiMacTrailer, anonymous_namespace{packet-metadata-test.cc}::HistoryTrailer< N >, ns3::LrWpanMacTrailer, anonymous_namespace{packet-test-suite.cc}::ATestTrailer< N >, and ns3::EthernetTrailer.
Referenced by Deserialize(), ns3::Packet::PeekTrailer(), and ns3::Packet::RemoveTrailer().
Deserialize() [2/2]
uint32_t ns3::Trailer::Deserialize (Buffer::Iterator start, Buffer::Iterator end) virtual
Parameters
start an iterator which points to the start of the buffer where the trailer should be read from.
end an iterator which points to the end of the buffer where the trailer should be read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveTrailer to re-create a trailer from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this trailer in real networks. The input iterator end points to the end of the area where the data shall be written.
This variant should be provided by any variable-sized trailer subclass (i.e. if GetSerializedSize () does not return a constant).
Reimplemented from ns3::Chunk.
Definition at line 48 of file trailer.cc.
References Deserialize().
GetSerializedSize()
virtual uint32_t ns3::Trailer::GetSerializedSize (void) const pure virtual
Returns
the expected size of the trailer.
This method is used by Packet::AddTrailer to store a trailer into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full trailer data by Serialize.
Implemented in ns3::WifiMacTrailer, ns3::EthernetTrailer, anonymous_namespace{packet-test-suite.cc}::ATestTrailer< N >, anonymous_namespace{packet-metadata-test.cc}::HistoryTrailer< N >, and ns3::LrWpanMacTrailer.
Referenced by ns3::Packet::AddTrailer().
GetTypeId()
TypeId ns3::Trailer::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 36 of file trailer.cc.
References ns3::TypeId::SetParent().
Referenced by ns3::PacketMetadata::ItemIterator::Next().
Print()
virtual void ns3::Trailer::Print (std::ostream & os) const pure virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a trailer as ascii data to a c++ output stream. Although the trailer is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Chunk.
Implemented in ns3::WifiMacTrailer, ns3::EthernetTrailer, anonymous_namespace{packet-test-suite.cc}::ATestTrailer< N >, anonymous_namespace{packet-metadata-test.cc}::HistoryTrailer< N >, and ns3::LrWpanMacTrailer.
Referenced by ns3::operator<<().
Serialize()
virtual void ns3::Trailer::Serialize (Buffer::Iterator start) const pure virtual
Parameters
start an iterator which points to where the trailer should be written.
This method is used by Packet::AddTrailer to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this trailer in real networks. The input iterator points to the end of the area where the data shall be written. This method is thus expected to call Buffer::Iterator::Prev prior to actually writing any data.
Implemented in ns3::WifiMacTrailer, anonymous_namespace{packet-metadata-test.cc}::HistoryTrailer< N >, ns3::LrWpanMacTrailer, anonymous_namespace{packet-test-suite.cc}::ATestTrailer< N >, and ns3::EthernetTrailer.
Referenced by ns3::Packet::AddTrailer().
The documentation for this class was generated from the following files:
src/network/model/trailer.h
src/network/model/trailer.cc