ns-3: ns3::dsr::DsrErrorBuffEntry Class Reference
ns3::dsr::DsrErrorBuffEntry Class Reference
DSR Routing
DSR Error Buffer Entry.
#include "dsr-errorbuff.h"
Public Member Functions
DsrErrorBuffEntry (Ptr< const Packet > pa=0, Ipv4Address d=Ipv4Address(), Ipv4Address s=Ipv4Address(), Ipv4Address n=Ipv4Address(), Time exp=Simulator::Now(), uint8_t p=0)
Create an DsrErrorBuffEntry with the given parameters.
Ipv4Address GetDestination () const
Get destination address.
Time GetExpireTime () const
Get expire time.
Ipv4Address GetNextHop () const
Get next hop.
Ptr< const Packet > GetPacket () const
Get packet from entry.
uint8_t GetProtocol () const
Get protocol number.
Ipv4Address GetSource () const
Get source address.
bool operator== (DsrErrorBuffEntry const &o) const
Compare send buffer entries.
void SetDestination (Ipv4Address d)
Set destination address.
void SetExpireTime (Time exp)
Set expire time.
void SetNextHop (Ipv4Address n)
Set next hop.
void SetPacket (Ptr< const Packet > p)
Set packet for entry.
void SetProtocol (uint8_t p)
Set protocol number.
void SetSource (Ipv4Address s)
Set source address.
Private Attributes
Ipv4Address m_dst
Destination address.
Time m_expire
Expire time for queue entry.
Ipv4Address m_nextHop
Nexthop address.
Ptr< const Packet > m_packet
Data packet.
uint8_t m_protocol
The protocol number.
Ipv4Address m_source
Source address.
Detailed Description
DSR Error Buffer Entry.
Definition at line 45 of file dsr-errorbuff.h.
Constructor & Destructor Documentation
DsrErrorBuffEntry()
ns3::dsr::DsrErrorBuffEntry::DsrErrorBuffEntry (Ptr< const Packet > pa = 0, Ipv4Address d = Ipv4Address (), Ipv4Address s = Ipv4Address (), Ipv4Address n = Ipv4Address (), Time exp = Simulator::Now (), uint8_t p = 0) inline
Create an DsrErrorBuffEntry with the given parameters.
Parameters
pa packet
d IPv4 address of the destination
s IPv4 address of the source
n IPv4 address of the next hop
exp expiration time
p protocol number
Definition at line 58 of file dsr-errorbuff.h.
Member Function Documentation
GetDestination()
Ipv4Address ns3::dsr::DsrErrorBuffEntry::GetDestination () const inline
Get destination address.
Returns
the destination IPv4 address
Definition at line 99 of file dsr-errorbuff.h.
References m_dst.
Referenced by ns3::dsr::DsrErrorBuffer::Drop(), and ns3::dsr::DsrErrorBuffer::Enqueue().
GetExpireTime()
Time ns3::dsr::DsrErrorBuffEntry::GetExpireTime () const inline
Get expire time.
Returns
the expire time
Definition at line 155 of file dsr-errorbuff.h.
References m_expire, and ns3::Simulator::Now().
Referenced by ns3::dsr::IsExpired::operator()().
GetNextHop()
Ipv4Address ns3::dsr::DsrErrorBuffEntry::GetNextHop () const inline
Get next hop.
Returns
the next hop address
Definition at line 131 of file dsr-errorbuff.h.
References m_nextHop.
Referenced by ns3::dsr::DsrErrorBuffer::DropLink(), and ns3::dsr::DsrErrorBuffer::Enqueue().
GetPacket()
Ptr<const Packet> ns3::dsr::DsrErrorBuffEntry::GetPacket () const inline
Get packet from entry.
Returns
the packet
Definition at line 83 of file dsr-errorbuff.h.
References m_packet.
Referenced by ns3::dsr::DsrErrorBuffer::Dequeue(), ns3::dsr::DsrErrorBuffer::Drop(), ns3::dsr::DsrErrorBuffer::DropLink(), ns3::dsr::DsrErrorBuffer::Enqueue(), and ns3::dsr::DsrRouting::SendPacketFromBuffer().
GetProtocol()
uint8_t ns3::dsr::DsrErrorBuffEntry::GetProtocol () const inline
Get protocol number.
Returns
the protocol number
Definition at line 171 of file dsr-errorbuff.h.
References m_protocol.
GetSource()
Ipv4Address ns3::dsr::DsrErrorBuffEntry::GetSource () const inline
Get source address.
Returns
the source IPv4 address
Definition at line 115 of file dsr-errorbuff.h.
References m_source.
Referenced by ns3::dsr::DsrErrorBuffer::DropLink(), and ns3::dsr::DsrErrorBuffer::Enqueue().
operator==()
bool ns3::dsr::DsrErrorBuffEntry::operator== (DsrErrorBuffEntry const & o) const inline
Compare send buffer entries.
Parameters
o another DsrErrorBuffEntry
Returns
true if equal
Definition at line 73 of file dsr-errorbuff.h.
References m_dst, m_expire, m_nextHop, m_packet, and m_source.
SetDestination()
void ns3::dsr::DsrErrorBuffEntry::SetDestination (Ipv4Address d) inline
Set destination address.
Parameters
d the destination IPv4 address
Definition at line 107 of file dsr-errorbuff.h.
References m_dst.
SetExpireTime()
void ns3::dsr::DsrErrorBuffEntry::SetExpireTime (Time exp) inline
Set expire time.
Parameters
exp the expire time
Definition at line 147 of file dsr-errorbuff.h.
References m_expire, and ns3::Simulator::Now().
Referenced by ns3::dsr::DsrErrorBuffer::Enqueue().
SetNextHop()
void ns3::dsr::DsrErrorBuffEntry::SetNextHop (Ipv4Address n) inline
Set next hop.
Parameters
n the next hop IPv4 address
Definition at line 139 of file dsr-errorbuff.h.
References m_nextHop, and sample-rng-plot::n.
SetPacket()
void ns3::dsr::DsrErrorBuffEntry::SetPacket (Ptr< const Packet > p) inline
Set packet for entry.
Parameters
p the packet
Definition at line 91 of file dsr-errorbuff.h.
References m_packet.
SetProtocol()
void ns3::dsr::DsrErrorBuffEntry::SetProtocol (uint8_t p) inline
Set protocol number.
Parameters
p the protocol number
Definition at line 163 of file dsr-errorbuff.h.
References m_protocol.
SetSource()
void ns3::dsr::DsrErrorBuffEntry::SetSource (Ipv4Address s) inline
Set source address.
Parameters
s the source IPv4 address
Definition at line 123 of file dsr-errorbuff.h.
References m_source.
Member Data Documentation
m_dst
Ipv4Address ns3::dsr::DsrErrorBuffEntry::m_dst private
Destination address.
destination address
Definition at line 180 of file dsr-errorbuff.h.
Referenced by GetDestination(), operator==(), and SetDestination().
m_expire
Time ns3::dsr::DsrErrorBuffEntry::m_expire private
Expire time for queue entry.
expiration time
Definition at line 186 of file dsr-errorbuff.h.
Referenced by GetExpireTime(), operator==(), and SetExpireTime().
m_nextHop
Ipv4Address ns3::dsr::DsrErrorBuffEntry::m_nextHop private
Nexthop address.
next hop
Definition at line 184 of file dsr-errorbuff.h.
Referenced by GetNextHop(), operator==(), and SetNextHop().
m_packet
Ptr<const Packet> ns3::dsr::DsrErrorBuffEntry::m_packet private
Data packet.
the packet
Definition at line 178 of file dsr-errorbuff.h.
Referenced by GetPacket(), operator==(), and SetPacket().
m_protocol
uint8_t ns3::dsr::DsrErrorBuffEntry::m_protocol private
The protocol number.
Definition at line 188 of file dsr-errorbuff.h.
Referenced by GetProtocol(), and SetProtocol().
m_source
Ipv4Address ns3::dsr::DsrErrorBuffEntry::m_source private
Source address.
source address
Definition at line 182 of file dsr-errorbuff.h.
Referenced by GetSource(), operator==(), and SetSource().
The documentation for this class was generated from the following file:
src/dsr/model/dsr-errorbuff.h