ns-3: ns3::Ipv6ExtensionFragment::Fragments Class Reference
ns3::Ipv6ExtensionFragment::Fragments Class Reference
Internet » IPv6 classes and sub-modules » IPV6 Header extension system.
This class stores the fragments of a packet waiting to be rebuilt.
Public Member Functions
Fragments ()
Constructor.
~Fragments ()
Destructor.
void AddFragment (Ptr< Packet > fragment, uint16_t fragmentOffset, bool moreFragment)
Add a fragment.
Ptr< Packet > GetPacket () const
Get the entire packet.
Ptr< Packet > GetPartialPacket () const
Get the packet parts so far received.
FragmentsTimeoutsListI_t GetTimeoutIter ()
Get the Timeout iterator.
bool IsEntire () const
If all fragments have been added.
void SetTimeoutIter (FragmentsTimeoutsListI_t iter)
Set the Timeout iterator.
void SetUnfragmentablePart (Ptr< Packet > unfragmentablePart)
Set the unfragmentable part of the packet.
Public Member Functions inherited from ns3::SimpleRefCount< Fragments >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
bool m_moreFragment
If other fragments will be sent.
std::list< std::pair< Ptr< Packet >, uint16_t > > m_packetFragments
The current fragments.
FragmentsTimeoutsListI_t m_timeoutIter
Timeout iterator to "event" handler.
Ptr< Packet > m_unfragmentable
The unfragmentable part.
Detailed Description
This class stores the fragments of a packet waiting to be rebuilt.
Definition at line 340 of file ipv6-extension.h.
Constructor & Destructor Documentation
Fragments()
ns3::Ipv6ExtensionFragment::Fragments::Fragments ()
Constructor.
Definition at line 670 of file ipv6-extension.cc.
~Fragments()
ns3::Ipv6ExtensionFragment::Fragments::~Fragments ()
Destructor.
Definition at line 675 of file ipv6-extension.cc.
Member Function Documentation
AddFragment()
void ns3::Ipv6ExtensionFragment::Fragments::AddFragment (Ptr< Packet > fragment, uint16_t fragmentOffset, bool moreFragment)
Add a fragment.
Parameters
fragment the fragment
fragmentOffset the offset of the fragment
moreFragment the bit "More Fragment"
Definition at line 679 of file ipv6-extension.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::Ipv6ExtensionFragment::Process().
GetPacket()
Ptr< Packet > ns3::Ipv6ExtensionFragment::Fragments::GetPacket () const
Get the entire packet.
Returns
the entire packet
Definition at line 729 of file ipv6-extension.cc.
References ns3::Packet::AddAtEnd(), ns3::Packet::Copy(), and list.
Referenced by ns3::Ipv6ExtensionFragment::Process().
GetPartialPacket()
Ptr< Packet > ns3::Ipv6ExtensionFragment::Fragments::GetPartialPacket () const
Get the packet parts so far received.
Returns
the partial packet
Definition at line 741 of file ipv6-extension.cc.
References ns3::Packet::AddAtEnd(), ns3::Packet::Copy(), and list.
Referenced by ns3::Ipv6ExtensionFragment::HandleFragmentsTimeout().
GetTimeoutIter()
Ipv6ExtensionFragment::FragmentsTimeoutsListI_t ns3::Ipv6ExtensionFragment::Fragments::GetTimeoutIter ()
Get the Timeout iterator.
Returns
The iterator.
Definition at line 776 of file ipv6-extension.cc.
Referenced by ns3::Ipv6ExtensionFragment::Process().
IsEntire()
bool ns3::Ipv6ExtensionFragment::Fragments::IsEntire () const
If all fragments have been added.
Returns
true if the packet is entire
Definition at line 706 of file ipv6-extension.cc.
References list.
Referenced by ns3::Ipv6ExtensionFragment::Process().
SetTimeoutIter()
void ns3::Ipv6ExtensionFragment::Fragments::SetTimeoutIter (FragmentsTimeoutsListI_t iter)
Set the Timeout iterator.
Parameters
iter The iterator.
Definition at line 769 of file ipv6-extension.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::Ipv6ExtensionFragment::Process().
SetUnfragmentablePart()
void ns3::Ipv6ExtensionFragment::Fragments::SetUnfragmentablePart (Ptr< Packet > unfragmentablePart)
Set the unfragmentable part of the packet.
Parameters
unfragmentablePart the unfragmentable part
Definition at line 700 of file ipv6-extension.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::Ipv6ExtensionFragment::Process().
Member Data Documentation
m_moreFragment
bool ns3::Ipv6ExtensionFragment::Fragments::m_moreFragment private
If other fragments will be sent.
Definition at line 401 of file ipv6-extension.h.
m_packetFragments
std::list<std::pair<Ptr<Packet>, uint16_t> > ns3::Ipv6ExtensionFragment::Fragments::m_packetFragments private
The current fragments.
Definition at line 406 of file ipv6-extension.h.
m_timeoutIter
FragmentsTimeoutsListI_t ns3::Ipv6ExtensionFragment::Fragments::m_timeoutIter private
Timeout iterator to "event" handler.
Definition at line 416 of file ipv6-extension.h.
m_unfragmentable
Ptr<Packet> ns3::Ipv6ExtensionFragment::Fragments::m_unfragmentable private
The unfragmentable part.
Definition at line 411 of file ipv6-extension.h.
The documentation for this class was generated from the following files:
src/internet/model/ipv6-extension.h
src/internet/model/ipv6-extension.cc