ns-3: ns3::BridgeNetDevice Class Reference
ns3::BridgeNetDevice Class Reference
Bridge Network Device
a virtual net device that bridges multiple LAN segments
#include "bridge-net-device.h"
Classes
struct LearnedState
Structure holding the status of an address.
Public Member Functions
BridgeNetDevice ()
virtual ~BridgeNetDevice ()
void AddBridgePort (Ptr< NetDevice > bridgePort)
Add a 'port' to a bridge device.
virtual void AddLinkChangeCallback (Callback< void > callback)
virtual Address GetAddress (void) const
Ptr< NetDevice > GetBridgePort (uint32_t n) const
Gets the n-th bridged port.
virtual Address GetBroadcast (void) const
virtual Ptr< Channel > GetChannel (void) const
virtual uint32_t GetIfIndex (void) const
virtual uint16_t GetMtu (void) const
virtual Address GetMulticast (Ipv4Address multicastGroup) const
Make and return a MAC multicast address using the provided multicast group.
virtual Address GetMulticast (Ipv6Address addr) const
Get the MAC multicast address corresponding to the IPv6 address provided.
uint32_t GetNBridgePorts (void) const
Gets the number of bridged 'ports', i.e., the NetDevices currently bridged.
virtual Ptr< Node > GetNode (void) const
virtual bool IsBridge (void) const
Return true if the net device is acting as a bridge.
virtual bool IsBroadcast (void) const
virtual bool IsLinkUp (void) const
virtual bool IsMulticast (void) const
virtual bool IsPointToPoint (void) const
Return true if the net device is on a point-to-point link.
virtual bool NeedsArp (void) const
virtual bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)
virtual bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
virtual void SetAddress (Address address)
Set the address of this interface.
virtual void SetIfIndex (const uint32_t index)
virtual bool SetMtu (const uint16_t mtu)
virtual void SetNode (Ptr< Node > node)
virtual void SetPromiscReceiveCallback (NetDevice::PromiscReceiveCallback cb)
virtual void SetReceiveCallback (NetDevice::ReceiveCallback cb)
virtual bool SupportsSendFrom () const
Public Member Functions inherited from ns3::NetDevice
virtual ~NetDevice ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::NetDevice
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
void ForwardBroadcast (Ptr< NetDevice > incomingPort, Ptr< const Packet > packet, uint16_t protocol, Mac48Address src, Mac48Address dst)
Forwards a broadcast or a multicast packet.
void ForwardUnicast (Ptr< NetDevice > incomingPort, Ptr< const Packet > packet, uint16_t protocol, Mac48Address src, Mac48Address dst)
Forwards a unicast packet.
Ptr< NetDevice > GetLearnedState (Mac48Address source)
Gets the port associated to a source address.
void Learn (Mac48Address source, Ptr< NetDevice > port)
Learns the port a MAC address is sending from.
void ReceiveFromDevice (Ptr< NetDevice > device, Ptr< const Packet > packet, uint16_t protocol, Address const &source, Address const &destination, PacketType packetType)
Receives a packet from one bridged port.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
BridgeNetDevice (const BridgeNetDevice &)
Copy constructor.
BridgeNetDevice & operator= (const BridgeNetDevice &)
Copy constructor.
Private Attributes
Mac48Address m_address
MAC address of the NetDevice.
Ptr< BridgeChannel > m_channel
virtual bridged channel
bool m_enableLearning
true if the bridge will learn the node status
Time m_expirationTime
time it takes for learned MAC state to expire
uint32_t m_ifIndex
Interface index.
std::map< Mac48Address, LearnedState > m_learnState
Container for known address statuses.
uint16_t m_mtu
MTU of the bridged NetDevice.
Ptr< Node > m_node
node owning this NetDevice
std::vector< Ptr< NetDevice > > m_ports
bridged ports
NetDevice::PromiscReceiveCallback m_promiscRxCallback
promiscuous receive callback
NetDevice::ReceiveCallback m_rxCallback
receive callback
Additional Inherited Members
Public Types inherited from ns3::NetDevice
typedef void(* LinkChangeTracedCallback) (void)
TracedCallback signature for link changed event.
enum PacketType {
PACKET_HOST = 1 , NS3_PACKET_HOST = PACKET_HOST , PACKET_BROADCAST , NS3_PACKET_BROADCAST = PACKET_BROADCAST ,
PACKET_MULTICAST , NS3_PACKET_MULTICAST = PACKET_MULTICAST , PACKET_OTHERHOST , NS3_PACKET_OTHERHOST = PACKET_OTHERHOST
}
Packet types are used as they are in Linux.
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address &, const Address &, enum PacketType > PromiscReceiveCallback
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address & > ReceiveCallback
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
a virtual net device that bridges multiple LAN segments
Config Paths
ns3::BridgeNetDevice is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::BridgeNetDevice"
Attributes
Mtu: The MAC-level Maximum Transmission Unit
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 1500
Flags: construct write read
EnableLearning: Enable the learning mode of the Learning Bridge
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
ExpirationTime: Time it takes for learned MAC state entry to expire.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +3e+11ns
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 136 bytes (on a 64-bit architecture).
Definition at line 71 of file bridge-net-device.h.
Constructor & Destructor Documentation
BridgeNetDevice() [1/2]
ns3::BridgeNetDevice::BridgeNetDevice ()
Definition at line 67 of file bridge-net-device.cc.
References m_channel, and NS_LOG_FUNCTION_NOARGS.
~BridgeNetDevice()
ns3::BridgeNetDevice::~BridgeNetDevice () virtual
Definition at line 75 of file bridge-net-device.cc.
References NS_LOG_FUNCTION_NOARGS.
BridgeNetDevice() [2/2]
ns3::BridgeNetDevice::BridgeNetDevice (const BridgeNetDevice &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Member Function Documentation
AddBridgePort()
void ns3::BridgeNetDevice::AddBridgePort (Ptr< NetDevice > bridgePort)
Add a 'port' to a bridge device.
Parameters
bridgePort the NetDevice to add
This method adds a new bridge port to a BridgeNetDevice, so that the new bridge port NetDevice becomes part of the bridge and L2 frames start being forwarded to/from this NetDevice.
Parameters
bridgePort NetDevice
Attention
The netdevice that is being added as bridge port must not have an IP address. In order to add IP connectivity to a bridging node you must enable IP on the BridgeNetDevice itself, never on its port netdevices.
Definition at line 250 of file bridge-net-device.cc.
References ns3::Mac48Address::ConvertFrom(), ns3::Mac48Address::IsMatchingType(), m_address, m_channel, m_node, m_ports, ns3::MakeCallback(), NS_ASSERT, NS_FATAL_ERROR, NS_LOG_DEBUG, NS_LOG_FUNCTION_NOARGS, ReceiveFromDevice(), and ns3::Node::RegisterProtocolHandler().
AddLinkChangeCallback()
void ns3::BridgeNetDevice::AddLinkChangeCallback (Callback< void > callback) virtual
Parameters
callback the callback to invoke
Add a callback invoked whenever the link status changes to UP. This callback is typically used by the IP/ARP layer to flush the ARP cache and by IPv6 stack to flush NDISC cache whenever the link goes up.
Implements ns3::NetDevice.
Definition at line 334 of file bridge-net-device.cc.
DoDispose()
void ns3::BridgeNetDevice::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 81 of file bridge-net-device.cc.
References ns3::Object::DoDispose(), m_channel, m_node, m_ports, and NS_LOG_FUNCTION_NOARGS.
ForwardBroadcast()
void ns3::BridgeNetDevice::ForwardBroadcast (Ptr< NetDevice > incomingPort, Ptr< const Packet > packet, uint16_t protocol, Mac48Address src, Mac48Address dst) protected
Forwards a broadcast or a multicast packet.
Parameters
incomingPort the packet incoming port
packet the packet
protocol the packet protocol (e.g., Ethertype)
src the packet source
dst the packet destination
Definition at line 175 of file bridge-net-device.cc.
References Learn(), m_ports, NS_LOG_DEBUG, NS_LOG_FUNCTION_NOARGS, NS_LOG_LOGIC, and port.
Referenced by ReceiveFromDevice().
ForwardUnicast()
void ns3::BridgeNetDevice::ForwardUnicast (Ptr< NetDevice > incomingPort, Ptr< const Packet > packet, uint16_t protocol, Mac48Address src, Mac48Address dst) protected
Forwards a unicast packet.
Parameters
incomingPort the packet incoming port
packet the packet
protocol the packet protocol (e.g., Ethertype)
src the packet source
dst the packet destination
Definition at line 140 of file bridge-net-device.cc.
References GetLearnedState(), Learn(), m_ports, NS_LOG_DEBUG, NS_LOG_FUNCTION_NOARGS, NS_LOG_LOGIC, and port.
Referenced by ReceiveFromDevice().
GetAddress()
Address ns3::BridgeNetDevice::GetAddress (void) const virtual
Returns
the current Address of this interface.
Implements ns3::NetDevice.
Definition at line 303 of file bridge-net-device.cc.
References m_address, and NS_LOG_FUNCTION_NOARGS.
GetBridgePort()
Ptr< NetDevice > ns3::BridgeNetDevice::GetBridgePort (uint32_t n) const
Gets the n-th bridged port.
Parameters
n the port index
Returns
the n-th bridged NetDevice
Definition at line 243 of file bridge-net-device.cc.
References m_ports, sample-rng-plot::n, and NS_LOG_FUNCTION_NOARGS.
GetBroadcast()
Address ns3::BridgeNetDevice::GetBroadcast (void) const virtual
Returns
the broadcast address supported by this netdevice.
Calling this method is invalid if IsBroadcast returns not true.
Implements ns3::NetDevice.
Definition at line 347 of file bridge-net-device.cc.
References NS_LOG_FUNCTION_NOARGS.
GetChannel()
Ptr< Channel > ns3::BridgeNetDevice::GetChannel (void) const virtual
Returns
the channel this NetDevice is connected to. The value returned can be zero if the NetDevice is not yet connected to any channel or if the underlying NetDevice has no concept of a channel. i.e., callers must check for zero and be ready to handle it.
Implements ns3::NetDevice.
Definition at line 289 of file bridge-net-device.cc.
References m_channel, and NS_LOG_FUNCTION_NOARGS.
GetIfIndex()
uint32_t ns3::BridgeNetDevice::GetIfIndex (void) const virtual
Returns
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 282 of file bridge-net-device.cc.
References m_ifIndex, and NS_LOG_FUNCTION_NOARGS.
GetLearnedState()
Ptr< NetDevice > ns3::BridgeNetDevice::GetLearnedState (Mac48Address source) protected
Gets the port associated to a source address.
Parameters
source the source address
Returns
the port the source is associated to, or NULL if no association is known.
Definition at line 210 of file bridge-net-device.cc.
References ns3::BridgeNetDevice::LearnedState::associatedPort, ns3::BridgeNetDevice::LearnedState::expirationTime, m_enableLearning, m_learnState, ns3::Simulator::Now(), and NS_LOG_FUNCTION_NOARGS.
Referenced by ForwardUnicast(), and SendFrom().
GetMtu()
uint16_t ns3::BridgeNetDevice::GetMtu (void) const virtual
Returns
the link-level MTU in bytes for this interface.
This value is typically used by the IP layer to perform IP fragmentation when needed.
Implements ns3::NetDevice.
Definition at line 318 of file bridge-net-device.cc.
References m_mtu, and NS_LOG_FUNCTION_NOARGS.
Referenced by GetTypeId().
GetMulticast() [1/2]
Address ns3::BridgeNetDevice::GetMulticast (Ipv4Address multicastGroup) const virtual
Make and return a MAC multicast address using the provided multicast group.
RFC 1112 says that an Ipv4 host group address is mapped to an Ethernet multicast address by placing the low-order 23-bits of the IP address into the low-order 23 bits of the Ethernet multicast address 01-00-5E-00-00-00 (hex). Similar RFCs exist for Ipv6 and Eui64 mappings. This method performs the multicast address creation function appropriate to the underlying MAC address of the device. This MAC address is encapsulated in an abstract Address to avoid dependencies on the exact MAC address format.
In the case of net devices that do not support multicast, clients are expected to test NetDevice::IsMulticast and avoid attempting to map multicast packets. Subclasses of NetDevice that do support multicasting are expected to override this method and provide an implementation appropriate to the particular device.
Parameters
multicastGroup The IP address for the multicast group destination of the packet.
Returns
The MAC multicast Address used to send packets to the provided multicast group.
Warning
Calling this method is invalid if IsMulticast returns not true.
See also
IsMulticast()
Implements ns3::NetDevice.
Definition at line 361 of file bridge-net-device.cc.
References ns3::Mac48Address::GetMulticast(), and NS_LOG_FUNCTION.
GetMulticast() [2/2]
Address ns3::BridgeNetDevice::GetMulticast (Ipv6Address addr) const virtual
Get the MAC multicast address corresponding to the IPv6 address provided.
Parameters
addr IPv6 address
Returns
the MAC multicast address
Warning
Calling this method is invalid if IsMulticast returns not true.
Implements ns3::NetDevice.
Definition at line 468 of file bridge-net-device.cc.
References ns3::Mac48Address::GetMulticast(), and NS_LOG_FUNCTION.
GetNBridgePorts()
uint32_t ns3::BridgeNetDevice::GetNBridgePorts (void) const
Gets the number of bridged 'ports', i.e., the NetDevices currently bridged.
Returns
the number of bridged ports.
Definition at line 235 of file bridge-net-device.cc.
References m_ports, and NS_LOG_FUNCTION_NOARGS.
GetNode()
Ptr< Node > ns3::BridgeNetDevice::GetNode (void) const virtual
Returns
the node base class which contains this network interface.
When a subclass needs to get access to the underlying node base class to print the nodeid for example, it can invoke this method.
Implements ns3::NetDevice.
Definition at line 424 of file bridge-net-device.cc.
References m_node, and NS_LOG_FUNCTION_NOARGS.
GetTypeId()
TypeId ns3::BridgeNetDevice::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 41 of file bridge-net-device.cc.
References GetMtu(), m_enableLearning, m_expirationTime, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeUintegerAccessor(), ns3::Seconds(), SetMtu(), and ns3::TypeId::SetParent().
IsBridge()
bool ns3::BridgeNetDevice::IsBridge (void) const virtual
Return true if the net device is acting as a bridge.
Returns
value of m_isBridge flag
Implements ns3::NetDevice.
Definition at line 377 of file bridge-net-device.cc.
References NS_LOG_FUNCTION_NOARGS.
IsBroadcast()
bool ns3::BridgeNetDevice::IsBroadcast (void) const virtual
Returns
true if this interface supports a broadcast address, false otherwise.
Implements ns3::NetDevice.
Definition at line 339 of file bridge-net-device.cc.
References NS_LOG_FUNCTION_NOARGS.
IsLinkUp()
bool ns3::BridgeNetDevice::IsLinkUp (void) const virtual
Returns
true if link is up; false otherwise
Implements ns3::NetDevice.
Definition at line 326 of file bridge-net-device.cc.
References NS_LOG_FUNCTION_NOARGS.
IsMulticast()
bool ns3::BridgeNetDevice::IsMulticast (void) const virtual
Returns
value of m_isMulticast flag
Implements ns3::NetDevice.
Definition at line 354 of file bridge-net-device.cc.
References NS_LOG_FUNCTION_NOARGS.
IsPointToPoint()
bool ns3::BridgeNetDevice::IsPointToPoint (void) const virtual
Return true if the net device is on a point-to-point link.
Returns
value of m_isPointToPoint flag
Implements ns3::NetDevice.
Definition at line 370 of file bridge-net-device.cc.
References NS_LOG_FUNCTION_NOARGS.
Learn()
void ns3::BridgeNetDevice::Learn (Mac48Address source, Ptr< NetDevice > port) protected
Learns the port a MAC address is sending from.
Parameters
source source address
port the port the source is sending from
Definition at line 199 of file bridge-net-device.cc.
References ns3::BridgeNetDevice::LearnedState::associatedPort, ns3::BridgeNetDevice::LearnedState::expirationTime, m_enableLearning, m_expirationTime, m_learnState, ns3::Simulator::Now(), NS_LOG_FUNCTION_NOARGS, and port.
Referenced by ForwardBroadcast(), ForwardUnicast(), and ReceiveFromDevice().
NeedsArp()
bool ns3::BridgeNetDevice::NeedsArp (void) const virtual
Returns
true if ARP is needed, false otherwise.
Called by higher-layers to check if this NetDevice requires ARP to be used.
Implements ns3::NetDevice.
Definition at line 440 of file bridge-net-device.cc.
References NS_LOG_FUNCTION_NOARGS.
operator=()
BridgeNetDevice& ns3::BridgeNetDevice::operator= (const BridgeNetDevice &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Returns
ReceiveFromDevice()
void ns3::BridgeNetDevice::ReceiveFromDevice (Ptr< NetDevice > device, Ptr< const Packet > packet, uint16_t protocol, Address const & source, Address const & destination, PacketType packetType) protected
Receives a packet from one bridged port.
Parameters
device the originating port
packet the received packet
protocol the packet protocol (e.g., Ethertype)
source the packet source
destination the packet destination
packetType the packet type (e.g., host, broadcast, etc.)
Definition at line 95 of file bridge-net-device.cc.
References ns3::Mac48Address::ConvertFrom(), ForwardBroadcast(), ForwardUnicast(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), Learn(), m_address, m_promiscRxCallback, m_rxCallback, NS_LOG_DEBUG, NS_LOG_FUNCTION_NOARGS, ns3::NetDevice::PACKET_BROADCAST, ns3::NetDevice::PACKET_HOST, ns3::NetDevice::PACKET_MULTICAST, and ns3::NetDevice::PACKET_OTHERHOST.
Referenced by AddBridgePort().
Send()
bool ns3::BridgeNetDevice::Send (Ptr< Packet > packet, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device to the specified destination Address
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 385 of file bridge-net-device.cc.
References m_address, NS_LOG_FUNCTION_NOARGS, and SendFrom().
SendFrom()
bool ns3::BridgeNetDevice::SendFrom (Ptr< Packet > packet, const Address & source, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
source source mac address (so called "MAC spoofing")
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device with the specified source and destination Addresses.
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 392 of file bridge-net-device.cc.
References ns3::Mac48Address::ConvertFrom(), ns3::Packet::Copy(), GetLearnedState(), ns3::Mac48Address::IsGroup(), m_ports, NS_LOG_FUNCTION_NOARGS, and port.
Referenced by Send().
SetAddress()
void ns3::BridgeNetDevice::SetAddress (Address address) virtual
Set the address of this interface.
Parameters
address address to set
Implements ns3::NetDevice.
Definition at line 296 of file bridge-net-device.cc.
References first::address, ns3::Mac48Address::ConvertFrom(), m_address, and NS_LOG_FUNCTION_NOARGS.
SetIfIndex()
void ns3::BridgeNetDevice::SetIfIndex (const uint32_t index) virtual
Parameters
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 275 of file bridge-net-device.cc.
References m_ifIndex, and NS_LOG_FUNCTION_NOARGS.
SetMtu()
bool ns3::BridgeNetDevice::SetMtu (const uint16_t mtu) virtual
Parameters
mtu MTU value, in bytes, to set for the device
Returns
whether the MTU value was within legal bounds
Override for default MTU defined on a per-type basis.
Implements ns3::NetDevice.
Definition at line 310 of file bridge-net-device.cc.
References m_mtu, and NS_LOG_FUNCTION_NOARGS.
Referenced by GetTypeId().
SetNode()
void ns3::BridgeNetDevice::SetNode (Ptr< Node > node) virtual
Parameters
node the node associated to this netdevice.
This method is called from ns3::Node::AddDevice.
Implements ns3::NetDevice.
Definition at line 432 of file bridge-net-device.cc.
References m_node, and NS_LOG_FUNCTION_NOARGS.
SetPromiscReceiveCallback()
void ns3::BridgeNetDevice::SetPromiscReceiveCallback (NetDevice::PromiscReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received in promiscuous mode and must be forwarded to the higher layers.
Enables netdevice promiscuous mode and sets the callback that will handle promiscuous mode packets. Note, promiscuous mode packets means all packets, including those packets that can be sensed by the netdevice but which are intended to be received by other hosts.
Implements ns3::NetDevice.
Definition at line 455 of file bridge-net-device.cc.
References m_promiscRxCallback, and NS_LOG_FUNCTION_NOARGS.
SetReceiveCallback()
void ns3::BridgeNetDevice::SetReceiveCallback (NetDevice::ReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received and must be forwarded to the higher layers.
Set the callback to be used to notify higher layers when a packet has been received.
Implements ns3::NetDevice.
Definition at line 448 of file bridge-net-device.cc.
References m_rxCallback, and NS_LOG_FUNCTION_NOARGS.
SupportsSendFrom()
bool ns3::BridgeNetDevice::SupportsSendFrom () const virtual
Returns
true if this interface supports a bridging mode, false otherwise.
Implements ns3::NetDevice.
Definition at line 462 of file bridge-net-device.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Data Documentation
m_address
Mac48Address ns3::BridgeNetDevice::m_address private
MAC address of the NetDevice.
Definition at line 208 of file bridge-net-device.h.
Referenced by AddBridgePort(), GetAddress(), ReceiveFromDevice(), Send(), and SetAddress().
m_channel
Ptr<BridgeChannel> ns3::BridgeNetDevice::m_channel private
virtual bridged channel
Definition at line 222 of file bridge-net-device.h.
Referenced by BridgeNetDevice(), AddBridgePort(), DoDispose(), and GetChannel().
m_enableLearning
bool ns3::BridgeNetDevice::m_enableLearning private
true if the bridge will learn the node status
Definition at line 226 of file bridge-net-device.h.
Referenced by GetLearnedState(), GetTypeId(), and Learn().
m_expirationTime
Time ns3::BridgeNetDevice::m_expirationTime private
time it takes for learned MAC state to expire
Definition at line 209 of file bridge-net-device.h.
Referenced by GetTypeId(), and Learn().
m_ifIndex
uint32_t ns3::BridgeNetDevice::m_ifIndex private
Interface index.
Definition at line 224 of file bridge-net-device.h.
Referenced by GetIfIndex(), and SetIfIndex().
m_learnState
std::map<Mac48Address, LearnedState> ns3::BridgeNetDevice::m_learnState private
Container for known address statuses.
Definition at line 220 of file bridge-net-device.h.
Referenced by GetLearnedState(), and Learn().
m_mtu
uint16_t ns3::BridgeNetDevice::m_mtu private
MTU of the bridged NetDevice.
Definition at line 225 of file bridge-net-device.h.
Referenced by GetMtu(), and SetMtu().
m_node
Ptr<Node> ns3::BridgeNetDevice::m_node private
node owning this NetDevice
Definition at line 221 of file bridge-net-device.h.
Referenced by AddBridgePort(), DoDispose(), GetNode(), and SetNode().
m_ports
std::vector< Ptr<NetDevice> > ns3::BridgeNetDevice::m_ports private
bridged ports
Definition at line 223 of file bridge-net-device.h.
Referenced by AddBridgePort(), DoDispose(), ForwardBroadcast(), ForwardUnicast(), GetBridgePort(), GetNBridgePorts(), and SendFrom().
m_promiscRxCallback
NetDevice::PromiscReceiveCallback ns3::BridgeNetDevice::m_promiscRxCallback private
promiscuous receive callback
Definition at line 206 of file bridge-net-device.h.
Referenced by ReceiveFromDevice(), and SetPromiscReceiveCallback().
m_rxCallback
NetDevice::ReceiveCallback ns3::BridgeNetDevice::m_rxCallback private
receive callback
Definition at line 205 of file bridge-net-device.h.
Referenced by ReceiveFromDevice(), and SetReceiveCallback().
The documentation for this class was generated from the following files:
src/bridge/model/bridge-net-device.h
src/bridge/model/bridge-net-device.cc