ns-3: ns3::RipNg Class Reference
ns3::RipNg Class Reference
Internet » IPv6 Routing Protocols. » RIPng
RIPng Routing Protocol, defined in RFC 2080.
#include "ripng.h"
Public Types
enum SplitHorizonType_e { NO_SPLIT_HORIZON , SPLIT_HORIZON , POISON_REVERSE }
Split Horizon strategy type.
Public Types inherited from ns3::Ipv6RoutingProtocol
typedef Callback< void, Ptr< const Packet >, const Ipv6Header &, Socket::SocketErrno > ErrorCallback
Callback for routing errors (e.g., no route found)
typedef Callback< void, Ptr< const Packet >, const Ipv6Header &, uint32_t > LocalDeliverCallback
Callback for packets to be locally delivered.
typedef Callback< void, Ptr< const NetDevice >, Ptr< Ipv6MulticastRoute >, Ptr< const Packet >, const Ipv6Header & > MulticastForwardCallback
Callback for multicast packets to be forwarded.
typedef Callback< void, Ptr< const NetDevice >, Ptr< Ipv6Route >, Ptr< const Packet >, const Ipv6Header & > UnicastForwardCallback
Callback for unicast packets to be forwarded.
Public Member Functions
RipNg ()
virtual ~RipNg ()
void AddDefaultRouteTo (Ipv6Address nextHop, uint32_t interface)
Add a default route to the router through the nextHop located on interface.
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
std::set< uint32_t > GetInterfaceExclusions () const
Get the set of interface excluded from the protocol.
uint8_t GetInterfaceMetric (uint32_t interface) const
Get the metric for an interface.
virtual void NotifyAddAddress (uint32_t interface, Ipv6InterfaceAddress address)
Notify when specified interface add an address.
virtual void NotifyAddRoute (Ipv6Address dst, Ipv6Prefix mask, Ipv6Address nextHop, uint32_t interface, Ipv6Address prefixToUse=Ipv6Address::GetZero())
Notify a new route.
virtual void NotifyInterfaceDown (uint32_t interface)
Notify when specified interface goes DOWN.
virtual void NotifyInterfaceUp (uint32_t interface)
Notify when specified interface goes UP.
virtual void NotifyRemoveAddress (uint32_t interface, Ipv6InterfaceAddress address)
Notify when specified interface add an address.
virtual void NotifyRemoveRoute (Ipv6Address dst, Ipv6Prefix mask, Ipv6Address nextHop, uint32_t interface, Ipv6Address prefixToUse=Ipv6Address::GetZero())
Notify route removing.
virtual void PrintRoutingTable (Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S) const
Print the Routing Table entries.
bool RouteInput (Ptr< const Packet > p, const Ipv6Header &header, Ptr< const NetDevice > idev, UnicastForwardCallback ucb, MulticastForwardCallback mcb, LocalDeliverCallback lcb, ErrorCallback ecb)
Route an input packet (to be forwarded or locally delivered)
Ptr< Ipv6Route > RouteOutput (Ptr< Packet > p, const Ipv6Header &header, Ptr< NetDevice > oif, Socket::SocketErrno &sockerr)
Query routing cache for an existing route, for an outbound packet.
void SetInterfaceExclusions (std::set< uint32_t > exceptions)
Set the set of interface excluded from the protocol.
void SetInterfaceMetric (uint32_t interface, uint8_t metric)
Set the metric for an interface.
virtual void SetIpv6 (Ptr< Ipv6 > ipv6)
Typically, invoked directly or indirectly from ns3::Ipv6::SetRoutingProtocol.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Ipv6RoutingProtocol
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose ()
Dispose this object.
void DoInitialize ()
Start protocol operation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
typedef std::list< std::pair< RipNgRoutingTableEntry *, EventId > > Routes
Container for the network routes - pair RipNgRoutingTableEntry *, EventId (update event)
typedef std::list< std::pair< RipNgRoutingTableEntry *, EventId > >::const_iterator RoutesCI
Const Iterator for container for the network routes.
typedef std::list< std::pair< RipNgRoutingTableEntry *, EventId > >::iterator RoutesI
Iterator for container for the network routes.
typedef std::map< Ptr< Socket >, uint32_t > SocketList
Socket list type.
typedef std::map< Ptr< Socket >, uint32_t >::const_iterator SocketListCI
Socket list type const iterator.
typedef std::map< Ptr< Socket >, uint32_t >::iterator SocketListI
Socket list type iterator.
Private Member Functions
void AddNetworkRouteTo (Ipv6Address network, Ipv6Prefix networkPrefix, Ipv6Address nextHop, uint32_t interface, Ipv6Address prefixToUse)
Add route to network.
void AddNetworkRouteTo (Ipv6Address network, Ipv6Prefix networkPrefix, uint32_t interface)
Add route to network.
void DeleteRoute (RipNgRoutingTableEntry *route)
Delete a route.
void DoSendRouteUpdate (bool periodic)
Send Routing Updates on all interfaces.
void HandleRequests (RipNgHeader hdr, Ipv6Address senderAddress, uint16_t senderPort, uint32_t incomingInterface, uint8_t hopLimit)
Handle RIPng requests.
void HandleResponses (RipNgHeader hdr, Ipv6Address senderAddress, uint32_t incomingInterface, uint8_t hopLimit)
Handle RIPng responses.
void InvalidateRoute (RipNgRoutingTableEntry *route)
Invalidate a route.
Ptr< Ipv6Route > Lookup (Ipv6Address dest, Ptr< NetDevice >=0)
Lookup in the forwarding table for destination.
void Receive (Ptr< Socket > socket)
Receive RIPng packets.
void RecvMulticastRipng (Ptr< Socket > socket)
Receive and process multicast packet.
void RecvUnicastRipng (Ptr< Socket > socket)
Receive and process unicast packet.
void SendRouteRequest ()
Send Routing Request on all interfaces.
void SendTriggeredRouteUpdate ()
Send Triggered Routing Updates on all interfaces.
void SendUnsolicitedRouteUpdate (void)
Send Unsolicited Routing Updates on all interfaces.
Private Attributes
Time m_garbageCollectionDelay
Delay before deleting an INVALID route.
bool m_initialized
flag to allow socket's late-creation.
std::set< uint32_t > m_interfaceExclusions
Set of excluded interfaces.
std::map< uint32_t, uint8_t > m_interfaceMetrics
Map of interface metrics.
Ptr< Ipv6 > m_ipv6
IPv6 reference.
uint8_t m_linkDown
Link down value.
Time m_maxTriggeredUpdateDelay
Max cooldown delay after a Triggered Update.
Time m_minTriggeredUpdateDelay
Min cooldown delay after a Triggered Update.
Ptr< Socket > m_multicastRecvSocket
multicast receive socket
EventId m_nextTriggeredUpdate
Next Triggered Update event.
EventId m_nextUnsolicitedUpdate
Next Unsolicited Update event.
Ptr< UniformRandomVariable > m_rng
Rng stream.
Routes m_routes
the forwarding table for network.
SplitHorizonType_e m_splitHorizonStrategy
Split Horizon strategy.
Time m_startupDelay
Random delay before protocol startup.
Time m_timeoutDelay
Delay before invalidating a route.
SocketList m_unicastSocketList
list of sockets for unicast messages (socket, interface index)
Time m_unsolicitedUpdate
time between two Unsolicited Routing Updates
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
RIPng Routing Protocol, defined in RFC 2080.
Config Paths
ns3::RipNg is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::RipNg"
Attributes
UnsolicitedRoutingUpdate: The time between two Unsolicited Routing Updates.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +3e+10ns
Flags: construct write read
StartupDelay: Maximum random delay for protocol startup (send route requests).
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+09ns
Flags: construct write read
TimeoutDelay: The delay to invalidate a route.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1.8e+11ns
Flags: construct write read
GarbageCollectionDelay: The delay to delete an expired route.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1.2e+11ns
Flags: construct write read
MinTriggeredCooldown: Min cooldown delay after a Triggered Update.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+09ns
Flags: construct write read
MaxTriggeredCooldown: Max cooldown delay after a Triggered Update.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +5e+09ns
Flags: construct write read
SplitHorizon: Split Horizon strategy.
Set with class: ns3::EnumValue
Underlying type:
Initial value: PoisonReverse
Flags: construct write read
LinkDownValue: Value for link down in count to infinity.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Initial value: 16
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 256 bytes (on a 64-bit architecture).
Definition at line 174 of file ripng.h.
Member Typedef Documentation
Routes
typedef std::list<std::pair <RipNgRoutingTableEntry *, EventId> > ns3::RipNg::Routes private
Container for the network routes - pair RipNgRoutingTableEntry *, EventId (update event)
Definition at line 273 of file ripng.h.
RoutesCI
typedef std::list<std::pair <RipNgRoutingTableEntry *, EventId> >::const_iterator ns3::RipNg::RoutesCI private
Const Iterator for container for the network routes.
Definition at line 276 of file ripng.h.
RoutesI
typedef std::list<std::pair <RipNgRoutingTableEntry *, EventId> >::iterator ns3::RipNg::RoutesI private
Iterator for container for the network routes.
Definition at line 279 of file ripng.h.
SocketList
typedef std::map< Ptr<Socket>, uint32_t> ns3::RipNg::SocketList private
Socket list type.
Definition at line 392 of file ripng.h.
SocketListCI
typedef std::map<Ptr<Socket>, uint32_t>::const_iterator ns3::RipNg::SocketListCI private
Socket list type const iterator.
Definition at line 396 of file ripng.h.
SocketListI
typedef std::map<Ptr<Socket>, uint32_t>::iterator ns3::RipNg::SocketListI private
Socket list type iterator.
Definition at line 394 of file ripng.h.
Member Enumeration Documentation
SplitHorizonType_e
enum ns3::RipNg::SplitHorizonType_e
Split Horizon strategy type.
See RFC 2080.
Enumerator
NO_SPLIT_HORIZON
No Split Horizon.
SPLIT_HORIZON
Split Horizon.
POISON_REVERSE
Poison Reverse Split Horizon.
Definition at line 207 of file ripng.h.
Constructor & Destructor Documentation
RipNg()
ns3::RipNg::RipNg ()
Definition at line 47 of file ripng.cc.
References m_rng.
~RipNg()
ns3::RipNg::~RipNg () virtual
Definition at line 53 of file ripng.cc.
Member Function Documentation
AddDefaultRouteTo()
void ns3::RipNg::AddDefaultRouteTo (Ipv6Address nextHop, uint32_t interface)
Add a default route to the router through the nextHop located on interface.
The default route is usually installed manually, or it is the result of some "other" routing protocol (e.g., BGP).
Parameters
nextHop the next hop
interface the interface
Definition at line 1271 of file ripng.cc.
References AddNetworkRouteTo(), ns3::Ipv6Prefix::GetZero(), and NS_LOG_FUNCTION.
AddNetworkRouteTo() [1/2]
void ns3::RipNg::AddNetworkRouteTo (Ipv6Address network, Ipv6Prefix networkPrefix, Ipv6Address nextHop, uint32_t interface, Ipv6Address prefixToUse) private
Add route to network.
Parameters
network network address
networkPrefix network prefix
nextHop next hop address to route the packet.
interface interface index
prefixToUse prefix that should be used for source address for this destination
Definition at line 636 of file ripng.cc.
References ns3::Ipv6Address::IsLinkLocal(), m_routes, NS_LOG_FUNCTION, NS_LOG_WARN, ns3::RipNgRoutingTableEntry::RIPNG_VALID, ns3::RipNgRoutingTableEntry::SetRouteChanged(), ns3::RipNgRoutingTableEntry::SetRouteMetric(), and ns3::RipNgRoutingTableEntry::SetRouteStatus().
Referenced by AddDefaultRouteTo(), NotifyAddAddress(), and NotifyInterfaceUp().
AddNetworkRouteTo() [2/2]
void ns3::RipNg::AddNetworkRouteTo (Ipv6Address network, Ipv6Prefix networkPrefix, uint32_t interface) private
Add route to network.
Parameters
network network address
networkPrefix network prefix
interface interface index
Definition at line 653 of file ripng.cc.
References m_routes, NS_LOG_FUNCTION, ns3::RipNgRoutingTableEntry::RIPNG_VALID, ns3::RipNgRoutingTableEntry::SetRouteChanged(), ns3::RipNgRoutingTableEntry::SetRouteMetric(), and ns3::RipNgRoutingTableEntry::SetRouteStatus().
AssignStreams()
int64_t ns3::RipNg::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 102 of file ripng.cc.
References m_rng, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
DeleteRoute()
void ns3::RipNg::DeleteRoute (RipNgRoutingTableEntry * route) private
Delete a route.
Parameters
route the route to be removed
Definition at line 687 of file ripng.cc.
References m_routes, NS_ABORT_MSG, and NS_LOG_FUNCTION.
Referenced by InvalidateRoute().
DoDispose()
void ns3::RipNg::DoDispose (void) protected virtual
Dispose this object.
Reimplemented from ns3::Object.
Definition at line 528 of file ripng.cc.
References ns3::EventId::Cancel(), ns3::Socket::Close(), ns3::Object::DoDispose(), m_ipv6, m_multicastRecvSocket, m_nextTriggeredUpdate, m_nextUnsolicitedUpdate, m_routes, m_unicastSocketList, and NS_LOG_FUNCTION.
DoInitialize()
void ns3::RipNg::DoInitialize (void) protected virtual
Start protocol operation.
Reimplemented from ns3::Object.
Definition at line 110 of file ripng.cc.
References first::address, ns3::Socket::Bind(), ns3::Socket::BindToNetDevice(), ns3::Socket::CreateSocket(), ns3::Object::DoInitialize(), DoSendRouteUpdate(), ns3::Time::GetSeconds(), ns3::UniformRandomVariable::GetValue(), ns3::Ipv6InterfaceAddress::GLOBAL, ns3::Ipv6InterfaceAddress::LINKLOCAL, ns3::TypeId::LookupByName(), m_initialized, m_interfaceExclusions, m_ipv6, m_maxTriggeredUpdateDelay, m_minTriggeredUpdateDelay, m_multicastRecvSocket, m_nextTriggeredUpdate, m_nextUnsolicitedUpdate, m_rng, m_startupDelay, m_unicastSocketList, m_unsolicitedUpdate, ns3::MakeCallback(), NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, Receive(), RIPNG_ALL_NODE, RIPNG_PORT, ns3::Simulator::Schedule(), ns3::Seconds(), SendRouteRequest(), SendUnsolicitedRouteUpdate(), ns3::Socket::SetIpv6RecvHopLimit(), ns3::Socket::SetRecvCallback(), and ns3::Socket::SetRecvPktInfo().
DoSendRouteUpdate()
void ns3::RipNg::DoSendRouteUpdate (bool periodic) private
Send Routing Updates on all interfaces.
Parameters
periodic true for periodic update, else triggered.
Definition at line 1079 of file ripng.cc.
References ns3::Packet::AddHeader(), ns3::Packet::AddPacketTag(), ns3::RipNgHeader::AddRte(), ns3::RipNgHeader::ClearRtes(), ns3::Ipv6Address::GetAny(), ns3::RipNgHeader::GetRteNumber(), ns3::Ipv6InterfaceAddress::GetScope(), ns3::Ipv6Header::GetSerializedSize(), ns3::RipNgRte::GetSerializedSize(), ns3::RipNgHeader::GetSerializedSize(), ns3::UdpHeader::GetSerializedSize(), ns3::Ipv6Prefix::GetZero(), ns3::Ipv6InterfaceAddress::GLOBAL, m_interfaceExclusions, m_ipv6, m_linkDown, m_routes, m_splitHorizonStrategy, m_unicastSocketList, NS_LOG_DEBUG, NS_LOG_FUNCTION, POISON_REVERSE, ns3::Packet::RemoveHeader(), ns3::RipNgHeader::RESPONSE, RIPNG_ALL_NODE, RIPNG_PORT, ns3::RipNgHeader::SetCommand(), ns3::SocketIpv6HopLimitTag::SetHopLimit(), ns3::RipNgRte::SetPrefix(), ns3::RipNgRte::SetPrefixLen(), ns3::RipNgRte::SetRouteMetric(), ns3::RipNgRte::SetRouteTag(), and SPLIT_HORIZON.
Referenced by DoInitialize(), SendTriggeredRouteUpdate(), and SendUnsolicitedRouteUpdate().
GetInterfaceExclusions()
std::set< uint32_t > ns3::RipNg::GetInterfaceExclusions () const
Get the set of interface excluded from the protocol.
Returns
the set of excluded interfaces
Definition at line 1204 of file ripng.cc.
References m_interfaceExclusions.
GetInterfaceMetric()
uint8_t ns3::RipNg::GetInterfaceMetric (uint32_t interface) const
Get the metric for an interface.
Parameters
interface the interface
Returns
the interface metric
Definition at line 1216 of file ripng.cc.
References m_interfaceMetrics, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::RipNg::GetTypeId (void) static
Get the type ID.
Returns
type ID
Definition at line 58 of file ripng.cc.
References m_garbageCollectionDelay, m_linkDown, m_maxTriggeredUpdateDelay, m_minTriggeredUpdateDelay, m_splitHorizonStrategy, m_startupDelay, m_timeoutDelay, m_unsolicitedUpdate, ns3::MakeEnumAccessor(), ns3::MakeEnumChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeUintegerAccessor(), NO_SPLIT_HORIZON, POISON_REVERSE, ns3::Seconds(), ns3::TypeId::SetParent(), and SPLIT_HORIZON.
HandleRequests()
void ns3::RipNg::HandleRequests (RipNgHeader hdr, Ipv6Address senderAddress, uint16_t senderPort, uint32_t incomingInterface, uint8_t hopLimit) private
Handle RIPng requests.
Parameters
hdr message header (including RTEs)
senderAddress sender address
senderPort sender port
incomingInterface incoming interface
hopLimit packet's hop limit
Definition at line 758 of file ripng.cc.
References ns3::Packet::AddHeader(), ns3::Packet::AddPacketTag(), ns3::RipNgHeader::AddRte(), ns3::RipNgHeader::ClearRtes(), ns3::Ipv6Address::CombinePrefix(), ns3::Ipv6Address::GetAny(), ns3::RipNgHeader::GetRteList(), ns3::RipNgHeader::GetRteNumber(), ns3::Ipv6InterfaceAddress::GetScope(), ns3::Ipv6Header::GetSerializedSize(), ns3::RipNgRte::GetSerializedSize(), ns3::RipNgHeader::GetSerializedSize(), ns3::UdpHeader::GetSerializedSize(), ns3::Ipv6Prefix::GetZero(), ns3::Ipv6InterfaceAddress::GLOBAL, ns3::Ipv6Address::IsLinkLocal(), m_interfaceExclusions, m_ipv6, m_linkDown, m_multicastRecvSocket, m_routes, m_splitHorizonStrategy, m_unicastSocketList, NS_ASSERT_MSG, NS_LOG_DEBUG, NS_LOG_FUNCTION, POISON_REVERSE, ns3::Packet::RemoveHeader(), ns3::Packet::RemovePacketTag(), ns3::RipNgHeader::RESPONSE, RIPNG_PORT, ns3::RipNgRoutingTableEntry::RIPNG_VALID, ns3::Socket::SendTo(), ns3::RipNgHeader::SetCommand(), ns3::SocketIpv6HopLimitTag::SetHopLimit(), ns3::RipNgRte::SetPrefix(), ns3::RipNgRte::SetPrefixLen(), ns3::RipNgRte::SetRouteMetric(), ns3::RipNgRte::SetRouteTag(), and SPLIT_HORIZON.
Referenced by Receive().
HandleResponses()
void ns3::RipNg::HandleResponses (RipNgHeader hdr, Ipv6Address senderAddress, uint32_t incomingInterface, uint8_t hopLimit) private
Handle RIPng responses.
Parameters
hdr message header (including RTEs)
senderAddress sender address
incomingInterface incoming interface
hopLimit packet's hop limit
Definition at line 923 of file ripng.cc.
References ns3::Ipv6Address::CombinePrefix(), ns3::Ipv6Address::GetAny(), ns3::Simulator::GetDelayLeft(), ns3::RipNgHeader::GetRteList(), InvalidateRoute(), ns3::Ipv6Address::IsLinkLocal(), m_interfaceExclusions, m_interfaceMetrics, m_linkDown, m_routes, m_timeoutDelay, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::RipNgRoutingTableEntry::RIPNG_VALID, ns3::Simulator::Schedule(), SendTriggeredRouteUpdate(), ns3::RipNgRoutingTableEntry::SetRouteChanged(), ns3::RipNgRoutingTableEntry::SetRouteMetric(), ns3::RipNgRoutingTableEntry::SetRouteStatus(), and ns3::RipNgRoutingTableEntry::SetRouteTag().
Referenced by Receive().
InvalidateRoute()
void ns3::RipNg::InvalidateRoute (RipNgRoutingTableEntry * route) private
Invalidate a route.
Parameters
route the route to be removed
Definition at line 665 of file ripng.cc.
References DeleteRoute(), m_garbageCollectionDelay, m_linkDown, m_routes, NS_ABORT_MSG, NS_LOG_FUNCTION, ns3::RipNgRoutingTableEntry::RIPNG_INVALID, ns3::Simulator::Schedule(), ns3::RipNgRoutingTableEntry::SetRouteChanged(), ns3::RipNgRoutingTableEntry::SetRouteMetric(), and ns3::RipNgRoutingTableEntry::SetRouteStatus().
Referenced by HandleResponses(), NotifyInterfaceDown(), and NotifyRemoveAddress().
Lookup()
Ptr< Ipv6Route > ns3::RipNg::Lookup (Ipv6Address dest, Ptr< NetDevice > interface = 0) private
Lookup in the forwarding table for destination.
Parameters
dest destination address
interface output interface if any (put 0 otherwise)
Returns
Ipv6Route to route the packet to reach dest address
Definition at line 558 of file ripng.cc.
References ns3::Ipv6RoutingTableEntry::GetDest(), ns3::Ipv6RoutingTableEntry::GetDestNetwork(), ns3::Ipv6RoutingTableEntry::GetDestNetworkPrefix(), ns3::Ipv6RoutingTableEntry::GetGateway(), ns3::Ipv6RoutingTableEntry::GetInterface(), ns3::Ipv6Prefix::GetPrefixLength(), ns3::Ipv6RoutingTableEntry::GetPrefixToUse(), ns3::RipNgRoutingTableEntry::GetRouteStatus(), ns3::Ipv6Address::GetZero(), ns3::Ipv6Address::IsAny(), ns3::Ipv6Address::IsLinkLocalMulticast(), ns3::Ipv6Prefix::IsMatch(), m_ipv6, m_routes, NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, and ns3::RipNgRoutingTableEntry::RIPNG_VALID.
Referenced by RouteInput(), and RouteOutput().
NotifyAddAddress()
void ns3::RipNg::NotifyAddAddress (uint32_t interface, Ipv6InterfaceAddress address) virtual
Notify when specified interface add an address.
Protocols are expected to implement this method to be notified whenever a new address is added to an interface. Typically used to add a 'network route' on an interface. Can be invoked on an up or down interface.
Parameters
interface the index of the interface we are being notified about
address a new address being added to an interface
Implements ns3::Ipv6RoutingProtocol.
Definition at line 376 of file ripng.cc.
References AddNetworkRouteTo(), first::address, ns3::Ipv6InterfaceAddress::GLOBAL, m_interfaceExclusions, m_ipv6, NS_LOG_FUNCTION, and SendTriggeredRouteUpdate().
NotifyAddRoute()
void ns3::RipNg::NotifyAddRoute (Ipv6Address dst, Ipv6Prefix mask, Ipv6Address nextHop, uint32_t interface, Ipv6Address prefixToUse = Ipv6Address::GetZero()) virtual
Notify a new route.
Typically this is used to add another route from IPv6 stack (i.e. ICMPv6 redirect case, ...).
Parameters
dst destination address
mask destination mask
nextHop nextHop for this destination
interface output interface
prefixToUse prefix to use as source with this route
Implements ns3::Ipv6RoutingProtocol.
Definition at line 438 of file ripng.cc.
References NS_LOG_INFO.
NotifyInterfaceDown()
void ns3::RipNg::NotifyInterfaceDown (uint32_t interface) virtual
Notify when specified interface goes DOWN.
Protocols are expected to implement this method to be notified of the state change of an interface in a node.
Parameters
interface the index of the interface we are being notified about
Implements ns3::Ipv6RoutingProtocol.
Definition at line 345 of file ripng.cc.
References InvalidateRoute(), m_interfaceExclusions, m_routes, m_unicastSocketList, NS_LOG_FUNCTION, NS_LOG_INFO, and SendTriggeredRouteUpdate().
Referenced by SetIpv6().
NotifyInterfaceUp()
void ns3::RipNg::NotifyInterfaceUp (uint32_t interface) virtual
Notify when specified interface goes UP.
Protocols are expected to implement this method to be notified of the state change of an interface in a node.
Parameters
interface the index of the interface we are being notified about
Implements ns3::Ipv6RoutingProtocol.
Definition at line 268 of file ripng.cc.
References AddNetworkRouteTo(), first::address, ns3::Socket::Bind(), ns3::Socket::BindToNetDevice(), ns3::Socket::CreateSocket(), ns3::Ipv6InterfaceAddress::GLOBAL, ns3::Ipv6InterfaceAddress::LINKLOCAL, ns3::TypeId::LookupByName(), m_initialized, m_interfaceExclusions, m_ipv6, m_multicastRecvSocket, m_unicastSocketList, ns3::MakeCallback(), NS_LOG_FUNCTION, NS_LOG_LOGIC, Receive(), RIPNG_ALL_NODE, RIPNG_PORT, SendTriggeredRouteUpdate(), ns3::Socket::SetIpv6RecvHopLimit(), ns3::Socket::SetRecvCallback(), and ns3::Socket::SetRecvPktInfo().
Referenced by SetIpv6().
NotifyRemoveAddress()
void ns3::RipNg::NotifyRemoveAddress (uint32_t interface, Ipv6InterfaceAddress address) virtual
Notify when specified interface add an address.
Protocols are expected to implement this method to be notified whenever a new address is removed from an interface. Typically used to remove the 'network route' of an interface. Can be invoked on an up or down interface.
Parameters
interface the index of the interface we are being notified about
address a new address being added to an interface
Implements ns3::Ipv6RoutingProtocol.
Definition at line 401 of file ripng.cc.
References first::address, ns3::Ipv6InterfaceAddress::GLOBAL, InvalidateRoute(), m_interfaceExclusions, m_ipv6, m_routes, NS_LOG_FUNCTION, and SendTriggeredRouteUpdate().
NotifyRemoveRoute()
void ns3::RipNg::NotifyRemoveRoute (Ipv6Address dst, Ipv6Prefix mask, Ipv6Address nextHop, uint32_t interface, Ipv6Address prefixToUse = Ipv6Address::GetZero()) virtual
Notify route removing.
Parameters
dst destination address
mask destination mask
nextHop nextHop for this destination
interface output interface
prefixToUse prefix to use as source with this route
Implements ns3::Ipv6RoutingProtocol.
Definition at line 444 of file ripng.cc.
References NS_LOG_FUNCTION.
PrintRoutingTable()
void ns3::RipNg::PrintRoutingTable (Ptr< OutputStreamWrapper > stream, Time::Unit unit = Time::S) const virtual
Print the Routing Table entries.
Parameters
stream The ostream the Routing table is printed to
unit The time unit to be used in the report
Implements ns3::Ipv6RoutingProtocol.
Definition at line 471 of file ripng.cc.
References ns3::Time::As(), ns3::Names::FindName(), ns3::Ipv6RoutingTableEntry::GetDest(), ns3::Ipv6RoutingTableEntry::GetDestNetworkPrefix(), ns3::Ipv6RoutingTableEntry::GetGateway(), ns3::Ipv6RoutingTableEntry::GetInterface(), ns3::Ipv6Prefix::GetPrefixLength(), ns3::RipNgRoutingTableEntry::GetRouteMetric(), ns3::RipNgRoutingTableEntry::GetRouteStatus(), ns3::OutputStreamWrapper::GetStream(), ns3::Ipv6RoutingTableEntry::IsGateway(), ns3::Ipv6RoutingTableEntry::IsHost(), m_ipv6, m_routes, ns3::Now(), NS_LOG_FUNCTION, and ns3::RipNgRoutingTableEntry::RIPNG_VALID.
Receive()
void ns3::RipNg::Receive (Ptr< Socket > socket) private
Receive RIPng packets.
Parameters
socket the socket the packet was received to.
Definition at line 704 of file ripng.cc.
References ns3::Inet6SocketAddress::ConvertFrom(), ns3::RipNgHeader::GetCommand(), ns3::Node::GetDevice(), ns3::SocketIpv6HopLimitTag::GetHopLimit(), ns3::Inet6SocketAddress::GetIpv6(), ns3::Inet6SocketAddress::GetPort(), ns3::Ipv6PacketInfoTag::GetRecvIf(), HandleRequests(), HandleResponses(), m_ipv6, NS_ABORT_MSG, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, ns3::Socket::RecvFrom(), ns3::Packet::RemoveHeader(), ns3::Packet::RemovePacketTag(), ns3::RipNgHeader::REQUEST, and ns3::RipNgHeader::RESPONSE.
Referenced by DoInitialize(), and NotifyInterfaceUp().
RecvMulticastRipng()
void ns3::RipNg::RecvMulticastRipng (Ptr< Socket > socket) private
Receive and process multicast packet.
Parameters
socket socket where packet is arrived
RecvUnicastRipng()
void ns3::RipNg::RecvUnicastRipng (Ptr< Socket > socket) private
Receive and process unicast packet.
Parameters
socket socket where packet is arrived
RouteInput()
bool ns3::RipNg::RouteInput (Ptr< const Packet > p, const Ipv6Header & header, Ptr< const NetDevice > idev, UnicastForwardCallback ucb, MulticastForwardCallback mcb, LocalDeliverCallback lcb, ErrorCallback ecb) virtual
Route an input packet (to be forwarded or locally delivered)
This lookup is used in the forwarding process. The packet is handed over to the Ipv6RoutingProtocol, and will get forwarded onward by one of the callbacks. The Linux equivalent is ip_route_input (). There are four valid outcomes, and a matching callbacks to handle each.
Parameters
p received packet
header input parameter used to form a search key for a route
idev Pointer to ingress network device
ucb Callback for the case in which the packet is to be forwarded as unicast
mcb Callback for the case in which the packet is to be forwarded as multicast
lcb Callback for the case in which the packet is to be locally delivered
ecb Callback to call if there is an error in forwarding
Returns
true if the Ipv6RoutingProtocol takes responsibility for forwarding or delivering the packet, false otherwise
Implements ns3::Ipv6RoutingProtocol.
Definition at line 212 of file ripng.cc.
References ns3::Socket::ERROR_NOROUTETOHOST, ns3::Ipv6Header::GetDestinationAddress(), ns3::Ipv6Header::GetSourceAddress(), ns3::Ipv6Address::IsLinkLocal(), ns3::Ipv6Address::IsMulticast(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), Lookup(), m_ipv6, NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
RouteOutput()
Ptr< Ipv6Route > ns3::RipNg::RouteOutput (Ptr< Packet > p, const Ipv6Header & header, Ptr< NetDevice > oif, Socket::SocketErrno & sockerr) virtual
Query routing cache for an existing route, for an outbound packet.
This lookup is used by transport protocols. It does not cause any packet to be forwarded, and is synchronous. Can be used for multicast or unicast. The Linux equivalent is ip_route_output ()
Parameters
p packet to be routed. Note that this method may modify the packet. Callers may also pass in a null pointer.
header input parameter (used to form key to search for the route)
oif Output interface device. May be zero, or may be bound via socket options to a particular output interface.
sockerr Output parameter; socket errno
Returns
a code that indicates what happened in the lookup
Implements ns3::Ipv6RoutingProtocol.
Definition at line 182 of file ripng.cc.
References ns3::Socket::ERROR_NOROUTETOHOST, ns3::Socket::ERROR_NOTERROR, ns3::Ipv6Header::GetDestinationAddress(), ns3::Ipv6Address::IsMulticast(), Lookup(), NS_LOG_FUNCTION, and NS_LOG_LOGIC.
SendRouteRequest()
void ns3::RipNg::SendRouteRequest () private
Send Routing Request on all interfaces.
Definition at line 1238 of file ripng.cc.
References ns3::Packet::AddHeader(), ns3::Packet::AddPacketTag(), ns3::RipNgHeader::AddRte(), ns3::Ipv6Address::GetAny(), m_interfaceExclusions, m_linkDown, m_unicastSocketList, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Packet::RemovePacketTag(), ns3::RipNgHeader::REQUEST, RIPNG_ALL_NODE, RIPNG_PORT, ns3::RipNgHeader::SetCommand(), ns3::SocketIpv6HopLimitTag::SetHopLimit(), ns3::RipNgRte::SetPrefix(), ns3::RipNgRte::SetPrefixLen(), and ns3::RipNgRte::SetRouteMetric().
Referenced by DoInitialize().
SendTriggeredRouteUpdate()
void ns3::RipNg::SendTriggeredRouteUpdate () private
Send Triggered Routing Updates on all interfaces.
Definition at line 1159 of file ripng.cc.
References DoSendRouteUpdate(), ns3::Time::GetSeconds(), ns3::UniformRandomVariable::GetValue(), ns3::EventId::IsRunning(), m_maxTriggeredUpdateDelay, m_minTriggeredUpdateDelay, m_nextTriggeredUpdate, m_rng, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Simulator::Schedule(), and ns3::Seconds().
Referenced by HandleResponses(), NotifyAddAddress(), NotifyInterfaceDown(), NotifyInterfaceUp(), and NotifyRemoveAddress().
SendUnsolicitedRouteUpdate()
void ns3::RipNg::SendUnsolicitedRouteUpdate (void) private
Send Unsolicited Routing Updates on all interfaces.
Definition at line 1189 of file ripng.cc.
References ns3::EventId::Cancel(), DoSendRouteUpdate(), ns3::Time::GetSeconds(), ns3::UniformRandomVariable::GetValue(), ns3::EventId::IsRunning(), m_nextTriggeredUpdate, m_nextUnsolicitedUpdate, m_rng, m_unsolicitedUpdate, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), and ns3::Seconds().
Referenced by DoInitialize().
SetInterfaceExclusions()
void ns3::RipNg::SetInterfaceExclusions (std::set< uint32_t > exceptions)
Set the set of interface excluded from the protocol.
Parameters
exceptions the set of excluded interfaces
Definition at line 1209 of file ripng.cc.
References m_interfaceExclusions, and NS_LOG_FUNCTION.
SetInterfaceMetric()
void ns3::RipNg::SetInterfaceMetric (uint32_t interface, uint8_t metric)
Set the metric for an interface.
Parameters
interface the interface
metric the interface metric
Definition at line 1228 of file ripng.cc.
References m_interfaceMetrics, m_linkDown, and NS_LOG_FUNCTION.
SetIpv6()
void ns3::RipNg::SetIpv6 (Ptr< Ipv6 > ipv6) virtual
Typically, invoked directly or indirectly from ns3::Ipv6::SetRoutingProtocol.
Parameters
ipv6 the ipv6 object this routing protocol is being associated with
Implements ns3::Ipv6RoutingProtocol.
Definition at line 450 of file ripng.cc.
References m_ipv6, NotifyInterfaceDown(), NotifyInterfaceUp(), NS_ASSERT, and NS_LOG_FUNCTION.
Member Data Documentation
m_garbageCollectionDelay
Time ns3::RipNg::m_garbageCollectionDelay private
Delay before deleting an INVALID route.
Definition at line 387 of file ripng.h.
Referenced by GetTypeId(), and InvalidateRoute().
m_initialized
bool ns3::RipNg::m_initialized private
flag to allow socket's late-creation.
Definition at line 411 of file ripng.h.
Referenced by DoInitialize(), and NotifyInterfaceUp().
m_interfaceExclusions
std::set<uint32_t> ns3::RipNg::m_interfaceExclusions private
Set of excluded interfaces.
Definition at line 406 of file ripng.h.
Referenced by DoInitialize(), DoSendRouteUpdate(), GetInterfaceExclusions(), HandleRequests(), HandleResponses(), NotifyAddAddress(), NotifyInterfaceDown(), NotifyInterfaceUp(), NotifyRemoveAddress(), SendRouteRequest(), and SetInterfaceExclusions().
m_interfaceMetrics
std::map<uint32_t, uint8_t> ns3::RipNg::m_interfaceMetrics private
Map of interface metrics.
Definition at line 407 of file ripng.h.
Referenced by GetInterfaceMetric(), HandleResponses(), and SetInterfaceMetric().
m_ipv6
Ptr<Ipv6> ns3::RipNg::m_ipv6 private
IPv6 reference.
Definition at line 381 of file ripng.h.
Referenced by DoDispose(), DoInitialize(), DoSendRouteUpdate(), HandleRequests(), Lookup(), NotifyAddAddress(), NotifyInterfaceUp(), NotifyRemoveAddress(), PrintRoutingTable(), Receive(), RouteInput(), and SetIpv6().
m_linkDown
uint8_t ns3::RipNg::m_linkDown private
Link down value.
Definition at line 412 of file ripng.h.
Referenced by DoSendRouteUpdate(), GetTypeId(), HandleRequests(), HandleResponses(), InvalidateRoute(), SendRouteRequest(), and SetInterfaceMetric().
m_maxTriggeredUpdateDelay
Time ns3::RipNg::m_maxTriggeredUpdateDelay private
Max cooldown delay after a Triggered Update.
Definition at line 384 of file ripng.h.
Referenced by DoInitialize(), GetTypeId(), and SendTriggeredRouteUpdate().
m_minTriggeredUpdateDelay
Time ns3::RipNg::m_minTriggeredUpdateDelay private
Min cooldown delay after a Triggered Update.
Definition at line 383 of file ripng.h.
Referenced by DoInitialize(), GetTypeId(), and SendTriggeredRouteUpdate().
m_multicastRecvSocket
Ptr<Socket> ns3::RipNg::m_multicastRecvSocket private
multicast receive socket
Definition at line 399 of file ripng.h.
Referenced by DoDispose(), DoInitialize(), HandleRequests(), and NotifyInterfaceUp().
m_nextTriggeredUpdate
EventId ns3::RipNg::m_nextTriggeredUpdate private
Next Triggered Update event.
Definition at line 402 of file ripng.h.
Referenced by DoDispose(), DoInitialize(), SendTriggeredRouteUpdate(), and SendUnsolicitedRouteUpdate().
m_nextUnsolicitedUpdate
EventId ns3::RipNg::m_nextUnsolicitedUpdate private
Next Unsolicited Update event.
Definition at line 401 of file ripng.h.
Referenced by DoDispose(), DoInitialize(), and SendUnsolicitedRouteUpdate().
m_rng
Ptr<UniformRandomVariable> ns3::RipNg::m_rng private
Rng stream.
Definition at line 404 of file ripng.h.
Referenced by RipNg(), AssignStreams(), DoInitialize(), SendTriggeredRouteUpdate(), and SendUnsolicitedRouteUpdate().
m_routes
Routes ns3::RipNg::m_routes private
the forwarding table for network.
Definition at line 380 of file ripng.h.
Referenced by AddNetworkRouteTo(), DeleteRoute(), DoDispose(), DoSendRouteUpdate(), HandleRequests(), HandleResponses(), InvalidateRoute(), Lookup(), NotifyInterfaceDown(), NotifyRemoveAddress(), and PrintRoutingTable().
m_splitHorizonStrategy
SplitHorizonType_e ns3::RipNg::m_splitHorizonStrategy private
Split Horizon strategy.
Definition at line 409 of file ripng.h.
Referenced by DoSendRouteUpdate(), GetTypeId(), and HandleRequests().
m_startupDelay
Time ns3::RipNg::m_startupDelay private
Random delay before protocol startup.
Definition at line 382 of file ripng.h.
Referenced by DoInitialize(), and GetTypeId().
m_timeoutDelay
Time ns3::RipNg::m_timeoutDelay private
Delay before invalidating a route.
Definition at line 386 of file ripng.h.
Referenced by GetTypeId(), and HandleResponses().
m_unicastSocketList
SocketList ns3::RipNg::m_unicastSocketList private
list of sockets for unicast messages (socket, interface index)
Definition at line 398 of file ripng.h.
Referenced by DoDispose(), DoInitialize(), DoSendRouteUpdate(), HandleRequests(), NotifyInterfaceDown(), NotifyInterfaceUp(), and SendRouteRequest().
m_unsolicitedUpdate
Time ns3::RipNg::m_unsolicitedUpdate private
time between two Unsolicited Routing Updates
Definition at line 385 of file ripng.h.
Referenced by DoInitialize(), GetTypeId(), and SendUnsolicitedRouteUpdate().
The documentation for this class was generated from the following files:
src/internet/model/ripng.h
src/internet/model/ripng.cc