ns-3: ns3::TcpPrrRecovery Class Reference
ns3::TcpPrrRecovery Class Reference
Internet » TCP » Recovery Algorithms.
An implementation of PRR.
#include "tcp-prr-recovery.h"
Public Types
enum ReductionBound_t { CRB , SSRB }
Reduction Bound variant (CRB or SSRB)
Public Member Functions
TcpPrrRecovery (const TcpPrrRecovery &sock)
Copy constructor.
TcpPrrRecovery (void)
Create an unbound tcp socket.
virtual ~TcpPrrRecovery (void) override
virtual void DoRecovery (Ptr< TcpSocketState > tcb, uint32_t deliveredBytes) override
Performs recovery based on the recovery algorithm.
virtual void EnterRecovery (Ptr< TcpSocketState > tcb, uint32_t dupAckCount, uint32_t unAckDataCount, uint32_t deliveredBytes) override
Performs variable initialization at the start of recovery.
virtual void ExitRecovery (Ptr< TcpSocketState > tcb) override
Performs cwnd adjustments at the end of recovery.
virtual Ptr< TcpRecoveryOps > Fork () override
Copy the recovery algorithm across socket.
std::string GetName () const override
Get the name of the recovery algorithm.
virtual void UpdateBytesSent (uint32_t bytesSent) override
Keeps track of bytes sent during recovery phase.
Public Member Functions inherited from ns3::TcpClassicRecovery
TcpClassicRecovery ()
Constructor.
TcpClassicRecovery (const TcpClassicRecovery &recovery)
Copy constructor.
virtual ~TcpClassicRecovery () override
Constructor.
Public Member Functions inherited from ns3::TcpRecoveryOps
TcpRecoveryOps ()
Constructor.
TcpRecoveryOps (const TcpRecoveryOps &other)
Copy constructor.
virtual ~TcpRecoveryOps ()
Deconstructor.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpClassicRecovery
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpRecoveryOps
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint32_t m_prrDelivered {0}
total bytes delivered during recovery phase
uint32_t m_prrOut {0}
total bytes sent during recovery phase
uint32_t m_recoveryFlightSize {0}
value of bytesInFlight at the start of recovery phase
ReductionBound_t m_reductionBoundMode {SSRB}
mode of Reduction Bound to be used
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
An implementation of PRR.
Introspection did not find any typical Config paths.
PRR is an algorithm that determines TCP's sending rate in fast recovery. PRR avoids excessive window reductions and aims for the actual congestion window size at the end of recovery to be as close as possible to the window determined by the congestion control algorithm. PRR also improves accuracy of the amount of data sent during loss recovery.
Attributes
ReductionBound: Type of Reduction Bound
Set with class: ns3::EnumValue
Underlying type:
Initial value: SSRB
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 48 bytes (on a 64-bit architecture).
Definition at line 42 of file tcp-prr-recovery.h.
Member Enumeration Documentation
ReductionBound_t
enum ns3::TcpPrrRecovery::ReductionBound_t
Reduction Bound variant (CRB or SSRB)
Enumerator
CRB
Conservative Reduction Bound.
SSRB
Slow Start Reduction Bound.
Definition at line 67 of file tcp-prr-recovery.h.
Constructor & Destructor Documentation
TcpPrrRecovery() [1/2]
ns3::TcpPrrRecovery::TcpPrrRecovery (void)
Create an unbound tcp socket.
Definition at line 50 of file tcp-prr-recovery.cc.
References NS_LOG_FUNCTION.
TcpPrrRecovery() [2/2]
ns3::TcpPrrRecovery::TcpPrrRecovery (const TcpPrrRecovery & sock)
Copy constructor.
Parameters
sock the object to copy
Definition at line 56 of file tcp-prr-recovery.cc.
References NS_LOG_FUNCTION.
~TcpPrrRecovery()
ns3::TcpPrrRecovery::~TcpPrrRecovery (void) override virtual
Definition at line 66 of file tcp-prr-recovery.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoRecovery()
void ns3::TcpPrrRecovery::DoRecovery (Ptr< TcpSocketState > tcb, uint32_t deliveredBytes) override virtual
Performs recovery based on the recovery algorithm.
The function is called on arrival of every ack when TcpSocketState is set to CA_RECOVERY. It performs the necessary cwnd changes as per the recovery algorithm.
Parameters
tcb internal congestion state
deliveredBytes bytes (S)ACKed in the last (S)ACK
Reimplemented from ns3::TcpClassicRecovery.
Definition at line 86 of file tcp-prr-recovery.cc.
References CRB, ns3::TcpSocketState::m_bytesInFlight, ns3::TcpSocketState::m_cWnd, ns3::TcpSocketState::m_cWndInfl, ns3::TcpSocketState::m_isRetransDataAcked, m_prrDelivered, m_prrOut, m_recoveryFlightSize, m_reductionBoundMode, ns3::TcpSocketState::m_segmentSize, ns3::TcpSocketState::m_ssThresh, max, min, NS_LOG_FUNCTION, and SSRB.
Referenced by EnterRecovery().
EnterRecovery()
void ns3::TcpPrrRecovery::EnterRecovery (Ptr< TcpSocketState > tcb, uint32_t dupAckCount, uint32_t unAckDataCount, uint32_t deliveredBytes) override virtual
Performs variable initialization at the start of recovery.
The function is called when the TcpSocketState is changed to CA_RECOVERY.
Parameters
tcb internal congestion state
dupAckCount duplicate acknowldgement count
unAckDataCount total bytes of data unacknowledged
deliveredBytes bytes (S)ACKed in the last (S)ACK
Reimplemented from ns3::TcpClassicRecovery.
Definition at line 72 of file tcp-prr-recovery.cc.
References DoRecovery(), m_prrDelivered, m_prrOut, m_recoveryFlightSize, NS_LOG_FUNCTION, and NS_UNUSED.
ExitRecovery()
void ns3::TcpPrrRecovery::ExitRecovery (Ptr< TcpSocketState > tcb) override virtual
Performs cwnd adjustments at the end of recovery.
The function is called when the TcpSocketState is changed from CA_RECOVERY.
Parameters
tcb internal congestion state
isSackEnabled
Reimplemented from ns3::TcpClassicRecovery.
Definition at line 124 of file tcp-prr-recovery.cc.
References ns3::TcpSocketState::m_cWnd, ns3::TcpSocketState::m_cWndInfl, and NS_LOG_FUNCTION.
Fork()
Ptr< TcpRecoveryOps > ns3::TcpPrrRecovery::Fork () override virtual
Copy the recovery algorithm across socket.
Returns
a pointer of the copied object
Reimplemented from ns3::TcpClassicRecovery.
Definition at line 138 of file tcp-prr-recovery.cc.
GetName()
std::string ns3::TcpPrrRecovery::GetName () const override virtual
Get the name of the recovery algorithm.
Returns
A string identifying the name
Reimplemented from ns3::TcpClassicRecovery.
Definition at line 144 of file tcp-prr-recovery.cc.
GetTypeId()
TypeId ns3::TcpPrrRecovery::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 35 of file tcp-prr-recovery.cc.
References CRB, m_reductionBoundMode, ns3::MakeEnumAccessor(), ns3::MakeEnumChecker(), ns3::TypeId::SetParent(), and SSRB.
Referenced by ns3::TcpL4Protocol::GetTypeId().
UpdateBytesSent()
void ns3::TcpPrrRecovery::UpdateBytesSent (uint32_t bytesSent) override virtual
Keeps track of bytes sent during recovery phase.
The function is called whenever a data packet is sent during recovery phase (optional).
Parameters
bytesSent bytes sent
Reimplemented from ns3::TcpRecoveryOps.
Definition at line 131 of file tcp-prr-recovery.cc.
References m_prrOut, and NS_LOG_FUNCTION.
Member Data Documentation
m_prrDelivered
uint32_t ns3::TcpPrrRecovery::m_prrDelivered {0} private
total bytes delivered during recovery phase
Definition at line 87 of file tcp-prr-recovery.h.
Referenced by DoRecovery(), and EnterRecovery().
m_prrOut
uint32_t ns3::TcpPrrRecovery::m_prrOut {0} private
total bytes sent during recovery phase
Definition at line 88 of file tcp-prr-recovery.h.
Referenced by DoRecovery(), EnterRecovery(), and UpdateBytesSent().
m_recoveryFlightSize
uint32_t ns3::TcpPrrRecovery::m_recoveryFlightSize {0} private
value of bytesInFlight at the start of recovery phase
Definition at line 89 of file tcp-prr-recovery.h.
Referenced by DoRecovery(), and EnterRecovery().
m_reductionBoundMode
ReductionBound_t ns3::TcpPrrRecovery::m_reductionBoundMode {SSRB} private
mode of Reduction Bound to be used
Definition at line 90 of file tcp-prr-recovery.h.
Referenced by DoRecovery(), and GetTypeId().
The documentation for this class was generated from the following files:
src/internet/model/tcp-prr-recovery.h
src/internet/model/tcp-prr-recovery.cc