ns-3: LteUeMeasurementsPiecewiseTestCase3 Class Reference
LteUeMeasurementsPiecewiseTestCase3 Class Reference
LTE Models » lte module tests | Test suites
Testing UE measurements in LTE with simulation of 3 eNodeB and 1 UE in piecewise configuration and 240 ms report interval.
#include "lte-test-ue-measurements.h"
Public Member Functions
LteUeMeasurementsPiecewiseTestCase3 (std::string name, LteRrcSap::ReportConfigEutra config, std::vector< Time > expectedTime)
Constructor.
virtual ~LteUeMeasurementsPiecewiseTestCase3 ()
void RecvMeasurementReportCallback (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti, LteRrcSap::MeasurementReport report)
Triggers when eNodeB receives measurement report from UE, then perform verification on it.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun ()
Setup the simulation with the intended UE measurement reporting configuration, run it, and connect the RecvMeasurementReportCallback function to the LteUeRrc::RecvMeasurementReport trace source.
virtual void DoTeardown ()
Runs at the end of the simulation, verifying that all expected measurement reports have been examined.
void TeleportEnbNear ()
Teleport the eNb near function.
Private Attributes
LteRrcSap::ReportConfigEutra m_config
The active report triggering configuration.
Ptr< MobilityModel > m_enbMobility
the mobility model
uint8_t m_expectedMeasId
The measurement identity being tested.
std::vector< Time > m_expectedTime
The list of expected time when measurement reports are received by eNodeB.
std::vector< Time >::iterator m_itExpectedTime
Pointer to the element of m_expectedTime which is expected to occur next in the simulation.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Testing UE measurements in LTE with simulation of 3 eNodeB and 1 UE in piecewise configuration and 240 ms report interval.
This test is to cover a corner case using event A4, which is not covered by LteUeMeasurementsPiecewiseTestCase1 and LteUeMeasurementsPiecewiseTestCase2. In this case, we test that the UE measurements at eNB are arriving 240 ms apart. Please note, the scenario simulated is engineered to specifically test the corner case in which whenever a new neighbour fulfils the entry condition for event A4, the UE RRC calls VarMeasReportListAdd method to include the new cell id in cellsTriggeredList, and then it schedules the SendMeasurementReport for periodic reporting. However, if the UE has already started the periodic reporting, scheduling the SendMeasurementReport method again causes following buggy behaviors:
It generates an intermediate measurement event, which then leads to parallel intermediate measurement reports from a UE to its eNB.
The old EvenId is overwritten by the new EventId stored in VarMeasReportList. This makes us lose control over the old EventId and it is impossible to cancel its events later on.
These buggy behaviors generated an issue reported in https://gitlab.com/nsnam/ns-3-dev/-/issues/224, where a UE try to send measurement reports after the RLF, even though all the measurement events are properly cancelled upon detecting RLF.
The correct behaviour should be that if a UE has already started the periodic reporting, and once a new neighbour fulfils the entry condition, we just need to add its cell id in cellsTriggeredList, without scheduling a new periodic event.
Definition at line 448 of file lte-test-ue-measurements.h.
Constructor & Destructor Documentation
LteUeMeasurementsPiecewiseTestCase3()
LteUeMeasurementsPiecewiseTestCase3::LteUeMeasurementsPiecewiseTestCase3 (std::string name, LteRrcSap::ReportConfigEutra config, std::vector< Time > expectedTime)
Constructor.
Parameters
name the reference name
config LteRrcSap::ReportConfigEutra
expectedTime the expected time
Definition at line 1403 of file lte-test-ue-measurements.cc.
References m_expectedMeasId, m_expectedTime, m_itExpectedTime, max, and NS_LOG_INFO.
~LteUeMeasurementsPiecewiseTestCase3()
LteUeMeasurementsPiecewiseTestCase3::~LteUeMeasurementsPiecewiseTestCase3 () virtual
Definition at line 1417 of file lte-test-ue-measurements.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoRun()
void LteUeMeasurementsPiecewiseTestCase3::DoRun (void) private virtual
Setup the simulation with the intended UE measurement reporting configuration, run it, and connect the RecvMeasurementReportCallback function to the LteUeRrc::RecvMeasurementReport trace source.
Implements ns3::TestCase.
Definition at line 1423 of file lte-test-ue-measurements.cc.
References ns3::LteHelper::ActivateDataRadioBearer(), ns3::LteHelper::Attach(), ns3::Config::Connect(), ns3::NodeContainer::Create(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::TestCase::GetName(), ns3::Object::GetObject(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), m_config, m_enbMobility, m_expectedMeasId, ns3::MakeCallback(), ns3::MilliSeconds(), third::mobility, NS_LOG_INFO, RecvMeasurementReportCallback(), ns3::Seconds(), ns3::ObjectBase::SetAttribute(), ns3::Config::SetDefault(), ns3::LteHelper::SetSchedulerAttribute(), ns3::LteHelper::SetSchedulerType(), and TeleportEnbNear().
DoTeardown()
void LteUeMeasurementsPiecewiseTestCase3::DoTeardown (void) private virtual
Runs at the end of the simulation, verifying that all expected measurement reports have been examined.
Reimplemented from ns3::TestCase.
Definition at line 1519 of file lte-test-ue-measurements.cc.
References m_expectedTime, m_itExpectedTime, NS_LOG_FUNCTION, and NS_TEST_ASSERT_MSG_EQ.
RecvMeasurementReportCallback()
void LteUeMeasurementsPiecewiseTestCase3::RecvMeasurementReportCallback (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti, LteRrcSap::MeasurementReport report)
Triggers when eNodeB receives measurement report from UE, then perform verification on it.
The trigger is set up beforehand by connecting to the LteUeRrc::RecvMeasurementReport trace source.
Verification consists of checking whether the report carries the right value of RSRP or not, and whether it occurs at the expected time or not.
Parameters
context the context
imsi the IMSI
cellId the cell ID
rnti the RNTI
report LteRrcSap::MeasurementReport
Definition at line 1528 of file lte-test-ue-measurements.cc.
References ns3::Time::GetMilliSeconds(), ns3::LteRrcSap::MeasResults::haveMeasResultNeighCells, m_expectedMeasId, m_expectedTime, m_itExpectedTime, ns3::LteRrcSap::MeasResults::measId, ns3::LteRrcSap::MeasResults::measResultListEutra, ns3::LteRrcSap::MeasurementReport::measResults, ns3::Now(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_TEST_ASSERT_MSG_EQ, ns3::LteRrcSap::MeasResults::rsrpResult, and ns3::LteRrcSap::MeasResults::rsrqResult.
Referenced by DoRun().
TeleportEnbNear()
void LteUeMeasurementsPiecewiseTestCase3::TeleportEnbNear () private
Teleport the eNb near function.
Definition at line 1599 of file lte-test-ue-measurements.cc.
References m_enbMobility, NS_LOG_FUNCTION, and ns3::MobilityModel::SetPosition().
Referenced by DoRun().
Member Data Documentation
m_config
LteRrcSap::ReportConfigEutra LteUeMeasurementsPiecewiseTestCase3::m_config private
The active report triggering configuration.
Definition at line 506 of file lte-test-ue-measurements.h.
Referenced by DoRun().
m_enbMobility
Ptr<MobilityModel> LteUeMeasurementsPiecewiseTestCase3::m_enbMobility private
the mobility model
Definition at line 527 of file lte-test-ue-measurements.h.
Referenced by DoRun(), and TeleportEnbNear().
m_expectedMeasId
uint8_t LteUeMeasurementsPiecewiseTestCase3::m_expectedMeasId private
The measurement identity being tested.
Measurement reports with different measurement identity (e.g. from handover algorithm) will be ignored.
Definition at line 525 of file lte-test-ue-measurements.h.
Referenced by LteUeMeasurementsPiecewiseTestCase3(), DoRun(), and RecvMeasurementReportCallback().
m_expectedTime
std::vector<Time> LteUeMeasurementsPiecewiseTestCase3::m_expectedTime private
The list of expected time when measurement reports are received by eNodeB.
Definition at line 512 of file lte-test-ue-measurements.h.
Referenced by LteUeMeasurementsPiecewiseTestCase3(), DoTeardown(), and RecvMeasurementReportCallback().
m_itExpectedTime
std::vector<Time>::iterator LteUeMeasurementsPiecewiseTestCase3::m_itExpectedTime private
Pointer to the element of m_expectedTime which is expected to occur next in the simulation.
Definition at line 518 of file lte-test-ue-measurements.h.
Referenced by LteUeMeasurementsPiecewiseTestCase3(), DoTeardown(), and RecvMeasurementReportCallback().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-ue-measurements.h
src/lte/test/lte-test-ue-measurements.cc