ns-3: ns3::MgtReassocRequestHeader Class Reference
ns3::MgtReassocRequestHeader Class Reference
Wifi Models
Implement the header for management frames of type reassociation request.
#include "mgt-headers.h"
Public Member Functions
MgtReassocRequestHeader ()
~MgtReassocRequestHeader ()
uint32_t Deserialize (Buffer::Iterator start)
CapabilityInformation GetCapabilities (void) const
Return the Capability information.
ExtendedCapabilities GetExtendedCapabilities (void) const
Return the extended capabilities.
HeCapabilities GetHeCapabilities (void) const
Return the HE capabilities.
HtCapabilities GetHtCapabilities (void) const
Return the HT capabilities.
TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint16_t GetListenInterval (void) const
Return the listen interval.
uint32_t GetSerializedSize (void) const
Ssid GetSsid (void) const
Return the Service Set Identifier (SSID).
SupportedRates GetSupportedRates (void) const
Return the supported rates.
VhtCapabilities GetVhtCapabilities (void) const
Return the VHT capabilities.
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetCapabilities (CapabilityInformation capabilities)
Set the Capability information.
void SetCurrentApAddress (Mac48Address currentApAddr)
Set the address of the current access point.
void SetExtendedCapabilities (ExtendedCapabilities extendedCapabilities)
Set the Extended Capabilities.
void SetHeCapabilities (HeCapabilities heCapabilities)
Set the HE capabilities.
void SetHtCapabilities (HtCapabilities htCapabilities)
Set the HT capabilities.
void SetListenInterval (uint16_t interval)
Set the listen interval.
void SetSsid (Ssid ssid)
Set the Service Set Identifier (SSID).
void SetSupportedRates (SupportedRates rates)
Set the supported rates.
void SetVhtCapabilities (VhtCapabilities vhtCapabilities)
Set the VHT capabilities.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
CapabilityInformation m_capability
Capability information.
Mac48Address m_currentApAddr
Address of the current access point.
ExtendedCapabilities m_extendedCapability
Extended capabilities.
HeCapabilities m_heCapability
HE capabilities.
HtCapabilities m_htCapability
HT capabilities.
uint16_t m_listenInterval
listen interval
SupportedRates m_rates
List of supported rates.
Ssid m_ssid
Service Set ID (SSID)
VhtCapabilities m_vhtCapability
VHT capabilities.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implement the header for management frames of type reassociation request.
Introspection did not find any typical Config paths.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 624 bytes (on a 64-bit architecture).
Definition at line 180 of file mgt-headers.h.
Constructor & Destructor Documentation
MgtReassocRequestHeader()
ns3::MgtReassocRequestHeader::MgtReassocRequestHeader ()
Definition at line 707 of file mgt-headers.cc.
~MgtReassocRequestHeader()
ns3::MgtReassocRequestHeader::~MgtReassocRequestHeader ()
Definition at line 712 of file mgt-headers.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::MgtReassocRequestHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 881 of file mgt-headers.cc.
References ns3::WifiInformationElement::Deserialize(), ns3::CapabilityInformation::Deserialize(), ns3::WifiInformationElement::DeserializeIfPresent(), ns3::SupportedRates::extended, ns3::Buffer::Iterator::GetDistanceFrom(), m_capability, m_currentApAddr, m_extendedCapability, m_heCapability, m_htCapability, m_listenInterval, m_rates, m_ssid, m_vhtCapability, ns3::ReadFrom(), ns3::Buffer::Iterator::ReadLsbtohU16(), and visualizer.core::start().
GetCapabilities()
CapabilityInformation ns3::MgtReassocRequestHeader::GetCapabilities (void) const
Return the Capability information.
Returns
Capability information
Definition at line 741 of file mgt-headers.cc.
References m_capability.
Referenced by ns3::ApWifiMac::Receive().
GetExtendedCapabilities()
ExtendedCapabilities ns3::MgtReassocRequestHeader::GetExtendedCapabilities (void) const
Return the extended capabilities.
Returns
the extended capabilities
Definition at line 753 of file mgt-headers.cc.
References m_extendedCapability.
Referenced by ns3::ApWifiMac::Receive().
GetHeCapabilities()
HeCapabilities ns3::MgtReassocRequestHeader::GetHeCapabilities (void) const
Return the HE capabilities.
Returns
HE capabilities
Definition at line 789 of file mgt-headers.cc.
References m_heCapability.
Referenced by ns3::ApWifiMac::Receive().
GetHtCapabilities()
HtCapabilities ns3::MgtReassocRequestHeader::GetHtCapabilities (void) const
Return the HT capabilities.
Returns
HT capabilities
Definition at line 765 of file mgt-headers.cc.
References m_htCapability.
Referenced by ns3::ApWifiMac::Receive().
GetInstanceTypeId()
TypeId ns3::MgtReassocRequestHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 830 of file mgt-headers.cc.
References GetTypeId().
GetListenInterval()
uint16_t ns3::MgtReassocRequestHeader::GetListenInterval (void) const
Return the listen interval.
Returns
the listen interval
Definition at line 807 of file mgt-headers.cc.
References m_listenInterval.
GetSerializedSize()
uint32_t ns3::MgtReassocRequestHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 836 of file mgt-headers.cc.
References ns3::SupportedRates::extended, ns3::ExtendedCapabilities::GetSerializedSize(), ns3::HeCapabilities::GetSerializedSize(), ns3::HtCapabilities::GetSerializedSize(), ns3::ExtendedSupportedRatesIE::GetSerializedSize(), ns3::VhtCapabilities::GetSerializedSize(), ns3::WifiInformationElement::GetSerializedSize(), ns3::CapabilityInformation::GetSerializedSize(), m_capability, m_extendedCapability, m_heCapability, m_htCapability, m_rates, m_ssid, and m_vhtCapability.
GetSsid()
Ssid ns3::MgtReassocRequestHeader::GetSsid (void) const
Return the Service Set Identifier (SSID).
Returns
SSID
Definition at line 795 of file mgt-headers.cc.
References m_ssid.
GetSupportedRates()
SupportedRates ns3::MgtReassocRequestHeader::GetSupportedRates (void) const
Return the supported rates.
Returns
the supported rates
Definition at line 801 of file mgt-headers.cc.
References m_rates.
Referenced by ns3::ApWifiMac::Receive().
GetTypeId()
TypeId ns3::MgtReassocRequestHeader::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 819 of file mgt-headers.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
GetVhtCapabilities()
VhtCapabilities ns3::MgtReassocRequestHeader::GetVhtCapabilities (void) const
Return the VHT capabilities.
Returns
VHT capabilities
Definition at line 777 of file mgt-headers.cc.
References m_vhtCapability.
Referenced by ns3::ApWifiMac::Receive().
Print()
void ns3::MgtReassocRequestHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 853 of file mgt-headers.cc.
References m_currentApAddr, m_extendedCapability, m_heCapability, m_htCapability, m_rates, m_ssid, and m_vhtCapability.
Serialize()
void ns3::MgtReassocRequestHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 865 of file mgt-headers.cc.
References ns3::SupportedRates::extended, m_capability, m_currentApAddr, m_extendedCapability, m_heCapability, m_htCapability, m_listenInterval, m_rates, m_ssid, m_vhtCapability, ns3::WifiInformationElement::Serialize(), ns3::CapabilityInformation::Serialize(), ns3::ExtendedCapabilities::Serialize(), ns3::HeCapabilities::Serialize(), ns3::HtCapabilities::Serialize(), ns3::ExtendedSupportedRatesIE::Serialize(), ns3::VhtCapabilities::Serialize(), visualizer.core::start(), ns3::Buffer::Iterator::WriteHtolsbU16(), and ns3::WriteTo().
SetCapabilities()
void ns3::MgtReassocRequestHeader::SetCapabilities (CapabilityInformation capabilities)
Set the Capability information.
Parameters
capabilities Capability information
Definition at line 735 of file mgt-headers.cc.
References m_capability.
Referenced by ns3::StaWifiMac::SendAssociationRequest().
SetCurrentApAddress()
void ns3::MgtReassocRequestHeader::SetCurrentApAddress (Mac48Address currentApAddr)
Set the address of the current access point.
Parameters
currentApAddr address of the current access point
Definition at line 813 of file mgt-headers.cc.
References m_currentApAddr.
Referenced by ns3::StaWifiMac::SendAssociationRequest().
SetExtendedCapabilities()
void ns3::MgtReassocRequestHeader::SetExtendedCapabilities (ExtendedCapabilities extendedCapabilities)
Set the Extended Capabilities.
Parameters
extendedCapabilities the Extended Capabilities
Definition at line 747 of file mgt-headers.cc.
References m_extendedCapability.
Referenced by ns3::StaWifiMac::SendAssociationRequest().
SetHeCapabilities()
void ns3::MgtReassocRequestHeader::SetHeCapabilities (HeCapabilities heCapabilities)
Set the HE capabilities.
Parameters
heCapabilities HE capabilities
Definition at line 783 of file mgt-headers.cc.
References m_heCapability.
Referenced by ns3::StaWifiMac::SendAssociationRequest().
SetHtCapabilities()
void ns3::MgtReassocRequestHeader::SetHtCapabilities (HtCapabilities htCapabilities)
Set the HT capabilities.
Parameters
htCapabilities HT capabilities
Definition at line 759 of file mgt-headers.cc.
References m_htCapability.
Referenced by ns3::StaWifiMac::SendAssociationRequest().
SetListenInterval()
void ns3::MgtReassocRequestHeader::SetListenInterval (uint16_t interval)
Set the listen interval.
Parameters
interval the listen interval
Definition at line 729 of file mgt-headers.cc.
References m_listenInterval.
Referenced by ns3::StaWifiMac::SendAssociationRequest().
SetSsid()
void ns3::MgtReassocRequestHeader::SetSsid (Ssid ssid)
Set the Service Set Identifier (SSID).
Parameters
ssid SSID
Definition at line 717 of file mgt-headers.cc.
References m_ssid, and third::ssid.
Referenced by ns3::StaWifiMac::SendAssociationRequest().
SetSupportedRates()
void ns3::MgtReassocRequestHeader::SetSupportedRates (SupportedRates rates)
Set the supported rates.
Parameters
rates the supported rates
Definition at line 723 of file mgt-headers.cc.
References m_rates.
Referenced by ns3::StaWifiMac::SendAssociationRequest().
SetVhtCapabilities()
void ns3::MgtReassocRequestHeader::SetVhtCapabilities (VhtCapabilities vhtCapabilities)
Set the VHT capabilities.
Parameters
vhtCapabilities VHT capabilities
Definition at line 771 of file mgt-headers.cc.
References m_vhtCapability.
Referenced by ns3::StaWifiMac::SendAssociationRequest().
Member Data Documentation
m_capability
CapabilityInformation ns3::MgtReassocRequestHeader::m_capability private
Capability information.
Definition at line 305 of file mgt-headers.h.
Referenced by Deserialize(), GetCapabilities(), GetSerializedSize(), Serialize(), and SetCapabilities().
m_currentApAddr
Mac48Address ns3::MgtReassocRequestHeader::m_currentApAddr private
Address of the current access point.
Definition at line 302 of file mgt-headers.h.
Referenced by Deserialize(), Print(), Serialize(), and SetCurrentApAddress().
m_extendedCapability
ExtendedCapabilities ns3::MgtReassocRequestHeader::m_extendedCapability private
Extended capabilities.
Definition at line 306 of file mgt-headers.h.
Referenced by Deserialize(), GetExtendedCapabilities(), GetSerializedSize(), Print(), Serialize(), and SetExtendedCapabilities().
m_heCapability
HeCapabilities ns3::MgtReassocRequestHeader::m_heCapability private
HE capabilities.
Definition at line 309 of file mgt-headers.h.
Referenced by Deserialize(), GetHeCapabilities(), GetSerializedSize(), Print(), Serialize(), and SetHeCapabilities().
m_htCapability
HtCapabilities ns3::MgtReassocRequestHeader::m_htCapability private
HT capabilities.
Definition at line 307 of file mgt-headers.h.
Referenced by Deserialize(), GetHtCapabilities(), GetSerializedSize(), Print(), Serialize(), and SetHtCapabilities().
m_listenInterval
uint16_t ns3::MgtReassocRequestHeader::m_listenInterval private
listen interval
Definition at line 310 of file mgt-headers.h.
Referenced by Deserialize(), GetListenInterval(), Serialize(), and SetListenInterval().
m_rates
SupportedRates ns3::MgtReassocRequestHeader::m_rates private
List of supported rates.
Definition at line 304 of file mgt-headers.h.
Referenced by Deserialize(), GetSerializedSize(), GetSupportedRates(), Print(), Serialize(), and SetSupportedRates().
m_ssid
Ssid ns3::MgtReassocRequestHeader::m_ssid private
Service Set ID (SSID)
Definition at line 303 of file mgt-headers.h.
Referenced by Deserialize(), GetSerializedSize(), GetSsid(), Print(), Serialize(), and SetSsid().
m_vhtCapability
VhtCapabilities ns3::MgtReassocRequestHeader::m_vhtCapability private
VHT capabilities.
Definition at line 308 of file mgt-headers.h.
Referenced by Deserialize(), GetSerializedSize(), GetVhtCapabilities(), Print(), Serialize(), and SetVhtCapabilities().
The documentation for this class was generated from the following files:
src/wifi/model/mgt-headers.h
src/wifi/model/mgt-headers.cc