ns-3: ns3::TcpWestwood Class Reference
ns3::TcpWestwood Class Reference
Internet » TCP » Congestion Control Algorithms.
An implementation of TCP Westwood and Westwood+.
#include "tcp-westwood.h"
Public Types
enum FilterType { NONE , TUSTIN }
Filter type (None or Tustin)
enum ProtocolType { WESTWOOD , WESTWOODPLUS }
Protocol variant (Westwood or Westwood+)
Public Member Functions
TcpWestwood (const TcpWestwood &sock)
Copy constructor.
TcpWestwood (void)
virtual ~TcpWestwood (void)
virtual Ptr< TcpCongestionOps > Fork ()
Copy the congestion control algorithm across sockets.
virtual uint32_t GetSsThresh (Ptr< const TcpSocketState > tcb, uint32_t bytesInFlight)
Get the slow start threshold after a loss event.
virtual void PktsAcked (Ptr< TcpSocketState > tcb, uint32_t packetsAcked, const Time &rtt)
Timing information on received ACK.
Public Member Functions inherited from ns3::TcpNewReno
TcpNewReno ()
TcpNewReno (const TcpNewReno &sock)
Copy constructor.
~TcpNewReno ()
std::string GetName () const
Get the name of the congestion control algorithm.
virtual void IncreaseWindow (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
Try to increase the cWnd following the NewReno specification.
Public Member Functions inherited from ns3::TcpCongestionOps
TcpCongestionOps ()
TcpCongestionOps (const TcpCongestionOps &other)
Copy constructor.
virtual ~TcpCongestionOps ()
virtual void CongControl (Ptr< TcpSocketState > tcb, const TcpRateOps::TcpRateConnection &rc, const TcpRateOps::TcpRateSample &rs)
Called when packets are delivered to update cwnd and pacing rate.
virtual void CongestionStateSet (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCongState_t newState)
Trigger events/calculations specific to a congestion state.
virtual void CwndEvent (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCAEvent_t event)
Trigger events/calculations on occurrence of congestion window event.
virtual bool HasCongControl () const
Returns true when Congestion Control Algorithm implements CongControl.
virtual void Init (Ptr< TcpSocketState > tcb)
Set configuration required by congestion control algorithm.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpNewReno
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpCongestionOps
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Attributes
uint32_t m_ackedSegments
The number of segments ACKed between RTTs.
EventId m_bwEstimateEvent
The BW estimation event for Westwood+.
TracedValue< double > m_currentBW
Current value of the estimated BW.
enum FilterType m_fType
0 for none, 1 for Tustin
bool m_IsCount
Start keeping track of m_ackedSegments for Westwood+ if TRUE.
double m_lastBW
Last bandwidth sample after being filtered.
double m_lastSampleBW
Last bandwidth sample.
enum ProtocolType m_pType
0 for Westwood, 1 for Westwood+
Private Member Functions
void EstimateBW (const Time &rtt, Ptr< TcpSocketState > tcb)
Estimate the network's bandwidth.
void UpdateAckedSegments (int acked)
Update the total number of acknowledged packets during the current RTT.
Additional Inherited Members
Protected Member Functions inherited from ns3::TcpNewReno
virtual void CongestionAvoidance (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
NewReno congestion avoidance.
virtual uint32_t SlowStart (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
Tcp NewReno slow start algorithm.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
An implementation of TCP Westwood and Westwood+.
Westwood and Westwood+ employ the AIAD (Additive Increase/Adaptive Decrease) congestion control paradigm. When a congestion episode happens, instead of halving the cwnd, these protocols try to estimate the network's bandwidth and use the estimated value to adjust the cwnd. While Westwood performs the bandwidth sampling every ACK reception, Westwood+ samples the bandwidth every RTT.
The two main methods in the implementation are the CountAck (const TCPHeader&) and the EstimateBW (int, const, Time). The CountAck method calculates the number of acknowledged segments on the receipt of an ACK. The EstimateBW estimates the bandwidth based on the value returned by CountAck and the sampling interval (last ACK inter-arrival time for Westwood and last RTT for Westwood+).
Config Paths
ns3::TcpWestwood is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::TcpL4Protocol/SocketList/[i]/CongestionOps/$ns3::TcpNewReno/$ns3::TcpWestwood"
"/NodeList/[i]/$ns3::TcpL4Protocol/SocketList/[i]/CongestionOps/$ns3::TcpWestwood"
Attributes
FilterType: Use this to choose no filter or Tustin's approximation filter
Set with class: ns3::EnumValue
Underlying type:
Initial value: Tustin
Flags: construct write read
ProtocolType: Use this to let the code run as Westwood or WestwoodPlus
Set with class: ns3::EnumValue
Underlying type:
Initial value: Westwood
Flags: construct write read
TraceSources
EstimatedBW: The estimated bandwidth
Callback signature: ns3::TracedValueCallback::Double
Size of this type is 120 bytes (on a 64-bit architecture).
Definition at line 67 of file tcp-westwood.h.
Member Enumeration Documentation
FilterType
enum ns3::TcpWestwood::FilterType
Filter type (None or Tustin)
Enumerator
NONE
TUSTIN
Definition at line 96 of file tcp-westwood.h.
ProtocolType
enum ns3::TcpWestwood::ProtocolType
Protocol variant (Westwood or Westwood+)
Enumerator
WESTWOOD
WESTWOODPLUS
Definition at line 87 of file tcp-westwood.h.
Constructor & Destructor Documentation
TcpWestwood() [1/2]
ns3::TcpWestwood::TcpWestwood (void)
Definition at line 67 of file tcp-westwood.cc.
References NS_LOG_FUNCTION.
TcpWestwood() [2/2]
ns3::TcpWestwood::TcpWestwood (const TcpWestwood & sock)
Copy constructor.
Parameters
sock the object to copy
Definition at line 78 of file tcp-westwood.cc.
References NS_LOG_FUNCTION, and NS_LOG_LOGIC.
~TcpWestwood()
ns3::TcpWestwood::~TcpWestwood (void) virtual
Definition at line 91 of file tcp-westwood.cc.
Member Function Documentation
EstimateBW()
void ns3::TcpWestwood::EstimateBW (const Time & rtt, Ptr< TcpSocketState > tcb) private
Estimate the network's bandwidth.
Parameters
[in] rtt the RTT estimation.
[in] tcb the socket state.
Definition at line 126 of file tcp-westwood.cc.
References sample-rng-plot::alpha, ns3::Time::GetSeconds(), ns3::Time::IsZero(), m_ackedSegments, m_currentBW, m_fType, m_IsCount, m_lastBW, m_lastSampleBW, m_pType, ns3::TcpSocketState::m_segmentSize, NONE, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, TUSTIN, and WESTWOODPLUS.
Referenced by PktsAcked().
Fork()
Ptr< TcpCongestionOps > ns3::TcpWestwood::Fork () virtual
Copy the congestion control algorithm across sockets.
Returns
a pointer of the copied object
Reimplemented from ns3::TcpNewReno.
Definition at line 174 of file tcp-westwood.cc.
GetSsThresh()
uint32_t ns3::TcpWestwood::GetSsThresh (Ptr< const TcpSocketState > tcb, uint32_t bytesInFlight) virtual
Get the slow start threshold after a loss event.
Is guaranteed that the congestion control state (TcpAckState_t) is changed BEFORE the invocation of this method. The implementator should return the slow start threshold (and not change it directly) because, in the future, the TCP implementation may require to instantly recover from a loss event (e.g. when there is a network with an high reordering factor).
Parameters
tcb internal congestion state
bytesInFlight total bytes in flight
Returns
Slow start threshold
Reimplemented from ns3::TcpNewReno.
Definition at line 161 of file tcp-westwood.cc.
References m_currentBW, max, NS_LOG_LOGIC, and NS_UNUSED.
GetTypeId()
TypeId ns3::TcpWestwood::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 47 of file tcp-westwood.cc.
References m_currentBW, m_fType, m_pType, ns3::MakeEnumAccessor(), ns3::MakeEnumChecker(), ns3::MakeTraceSourceAccessor(), NONE, ns3::TypeId::SetParent(), TUSTIN, WESTWOOD, and WESTWOODPLUS.
PktsAcked()
void ns3::TcpWestwood::PktsAcked (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked, const Time & rtt) virtual
Timing information on received ACK.
The function is called every time an ACK is received (only one time also for cumulative ACKs) and contains timing information. It is optional (congestion controls need not implement it) and the default implementation does nothing.
Parameters
tcb internal congestion state
segmentsAcked count of segments acked
rtt last rtt
Reimplemented from ns3::TcpCongestionOps.
Definition at line 96 of file tcp-westwood.cc.
References ns3::EventId::Cancel(), EstimateBW(), ns3::Time::IsZero(), m_ackedSegments, m_bwEstimateEvent, m_IsCount, m_pType, NS_LOG_FUNCTION, NS_LOG_WARN, ns3::Simulator::Schedule(), WESTWOOD, and WESTWOODPLUS.
UpdateAckedSegments()
void ns3::TcpWestwood::UpdateAckedSegments (int acked) private
Update the total number of acknowledged packets during the current RTT.
Parameters
[in] acked the number of packets the currently received ACK acknowledges
Member Data Documentation
m_ackedSegments
uint32_t ns3::TcpWestwood::m_ackedSegments protected
The number of segments ACKed between RTTs.
Definition at line 133 of file tcp-westwood.h.
Referenced by EstimateBW(), and PktsAcked().
m_bwEstimateEvent
EventId ns3::TcpWestwood::m_bwEstimateEvent protected
The BW estimation event for Westwood+.
Definition at line 135 of file tcp-westwood.h.
Referenced by PktsAcked().
m_currentBW
TracedValue<double> ns3::TcpWestwood::m_currentBW protected
Current value of the estimated BW.
Definition at line 127 of file tcp-westwood.h.
Referenced by EstimateBW(), GetSsThresh(), and GetTypeId().
m_fType
enum FilterType ns3::TcpWestwood::m_fType protected
0 for none, 1 for Tustin
Definition at line 129 of file tcp-westwood.h.
Referenced by EstimateBW(), and GetTypeId().
m_IsCount
bool ns3::TcpWestwood::m_IsCount protected
Start keeping track of m_ackedSegments for Westwood+ if TRUE.
Definition at line 134 of file tcp-westwood.h.
Referenced by EstimateBW(), and PktsAcked().
m_lastBW
double ns3::TcpWestwood::m_lastBW protected
Last bandwidth sample after being filtered.
Definition at line 129 of file tcp-westwood.h.
Referenced by EstimateBW().
m_lastSampleBW
double ns3::TcpWestwood::m_lastSampleBW protected
Last bandwidth sample.
Definition at line 128 of file tcp-westwood.h.
Referenced by EstimateBW().
m_pType
enum ProtocolType ns3::TcpWestwood::m_pType protected
0 for Westwood, 1 for Westwood+
Definition at line 129 of file tcp-westwood.h.
Referenced by EstimateBW(), GetTypeId(), and PktsAcked().
The documentation for this class was generated from the following files:
src/internet/model/tcp-westwood.h
src/internet/model/tcp-westwood.cc