ns-3: ns3::V4Ping Class Reference
ns3::V4Ping Class Reference
Internet Applications » V4Ping
an application which sends one ICMP ECHO request, waits for a REPLYs and reports the calculated RTT.
#include "v4ping.h"
Public Member Functions
V4Ping ()
create a pinger applications
virtual ~V4Ping ()
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual void DoDispose (void)
Destructor implementation.
uint32_t GetApplicationId (void) const
Return the application ID in the node.
void Read32 (const uint8_t *buffer, uint32_t &data)
Writes data from a little-endian formatted buffer to data.
void Receive (Ptr< Socket > socket)
Receive an ICMP Echo.
void Send ()
Send one Ping (ICMP ECHO) to the destination.
virtual void StartApplication (void)
Application specific startup code.
virtual void StopApplication (void)
Application specific shutdown code.
void Write32 (uint8_t *buffer, const uint32_t data)
Writes data to buffer in little-endian format.
Private Attributes
Average< double > m_avgRtt
Average rtt is ms.
Time m_interval
Wait interval seconds between sending each packet.
EventId m_next
Next packet will be sent.
uint32_t m_recv
received packets counter
Ipv4Address m_remote
Remote address.
std::map< uint16_t, Time > m_sent
All sent but not answered packets. Map icmp seqno -> when sent.
uint16_t m_seq
ICMP ECHO sequence number.
uint32_t m_size
Specifies the number of data bytes to be sent.
Ptr< Socket > m_socket
The socket we send packets from.
Time m_started
Start time to report total ping time.
TracedCallback< Time > m_traceRtt
TracedCallback for RTT measured by ICMP ECHOs.
bool m_verbose
produce ping-style output if true
Additional Inherited Members
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Protected Member Functions inherited from ns3::Application
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
an application which sends one ICMP ECHO request, waits for a REPLYs and reports the calculated RTT.
Note: The RTT calculated is reported through a trace source.
Config Paths
ns3::V4Ping is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/ApplicationList/[i]/$ns3::V4Ping"
Attributes
Remote: The address of the machine we want to ping.
Set with class: Ipv4AddressValue
Underlying type: Ipv4Address
Initial value: 102.102.102.102
Flags: construct write read
Verbose: Produce usual output.
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
Interval: Wait interval seconds between sending each packet.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+09ns
Flags: construct write read
Size: The number of data bytes to be sent, real packet will be 8 (ICMP) + 20 (IP) bytes longer.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 16:4294967295
Initial value: 56
Flags: construct write read
Attributes defined in parent class ns3::Application
StartTime: Time at which the application will start
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
StopTime: Time at which the application will stop
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
TraceSources
Rtt: The rtt calculated by the ping.
Callback signature: ns3::Time::TracedCallback
Size of this type is 472 bytes (on a 64-bit architecture).
Definition at line 41 of file v4ping.h.
Constructor & Destructor Documentation
V4Ping()
ns3::V4Ping::V4Ping ()
create a pinger applications
Definition at line 68 of file v4ping.cc.
References NS_LOG_FUNCTION.
~V4Ping()
ns3::V4Ping::~V4Ping () virtual
Definition at line 78 of file v4ping.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::V4Ping::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Application.
Definition at line 84 of file v4ping.cc.
References ns3::Application::DoDispose(), ns3::EventId::IsRunning(), m_next, m_socket, NS_LOG_FUNCTION, and StopApplication().
GetApplicationId()
uint32_t ns3::V4Ping::GetApplicationId (void) const private
Return the application ID in the node.
Returns
the application id
Definition at line 98 of file v4ping.cc.
References ns3::Node::GetApplication(), ns3::Node::GetNApplications(), ns3::Application::GetNode(), NS_ASSERT_MSG, and NS_LOG_FUNCTION.
Referenced by Receive(), and Send().
GetTypeId()
TypeId ns3::V4Ping::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 36 of file v4ping.cc.
References m_interval, m_remote, m_size, m_traceRtt, m_verbose, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeIpv4AddressAccessor(), ns3::MakeIpv4AddressChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), ns3::Seconds(), and ns3::TypeId::SetParent().
Read32()
void ns3::V4Ping::Read32 (const uint8_t * buffer, uint32_t & data) private
Writes data from a little-endian formatted buffer to data.
Parameters
buffer the buffer to read from
data the read data
Definition at line 190 of file v4ping.cc.
References data, and NS_LOG_FUNCTION.
Referenced by Receive().
Receive()
void ns3::V4Ping::Receive (Ptr< Socket > socket) private
Receive an ICMP Echo.
Parameters
socket the receiving socket
This function is called by lower layers through a callback.
Definition at line 114 of file v4ping.cc.
References ns3::Time::As(), ns3::InetSocketAddress::ConvertFrom(), GetApplicationId(), ns3::Icmpv4Echo::GetData(), ns3::Icmpv4Echo::GetDataSize(), ns3::Icmpv4Echo::GetIdentifier(), ns3::InetSocketAddress::GetIpv4(), ns3::Time::GetMilliSeconds(), ns3::Application::GetNode(), ns3::InetSocketAddress::GetPort(), ns3::Ipv4Header::GetProtocol(), ns3::Socket::GetRxAvailable(), ns3::Icmpv4Echo::GetSequenceNumber(), ns3::Packet::GetSize(), ns3::Ipv4Header::GetTtl(), ns3::Icmpv4Header::GetType(), ns3::Icmpv4Header::ICMPV4_ECHO_REPLY, ns3::InetSocketAddress::IsMatchingType(), m_avgRtt, m_recv, m_sent, m_size, m_socket, m_traceRtt, m_verbose, ns3::Time::MS, ns3::Simulator::Now(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, Read32(), ns3::Socket::RecvFrom(), ns3::Packet::RemoveHeader(), and ns3::Average< T >::Update().
Referenced by StartApplication().
Send()
void ns3::V4Ping::Send (void) private
Send one Ping (ICMP ECHO) to the destination.
Definition at line 197 of file v4ping.cc.
References ns3::Packet::AddHeader(), ns3::Node::ChecksumEnabled(), data, ns3::Icmpv4Header::EnableChecksum(), GetApplicationId(), ns3::Node::GetId(), ns3::Application::GetNode(), ns3::Icmpv4Header::ICMPV4_ECHO, m_interval, m_next, m_sent, m_seq, m_size, m_socket, ns3::Simulator::Now(), NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::Simulator::Schedule(), ns3::Socket::Send(), ns3::Icmpv4Header::SetCode(), ns3::Icmpv4Echo::SetData(), ns3::Icmpv4Echo::SetIdentifier(), ns3::Icmpv4Echo::SetSequenceNumber(), ns3::Icmpv4Header::SetType(), and Write32().
Referenced by StartApplication().
StartApplication()
void ns3::V4Ping::StartApplication (void) private virtual
Application specific startup code.
The StartApplication method is called at the start time specified by Start This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 242 of file v4ping.cc.
References ns3::Socket::Bind(), ns3::Socket::Connect(), ns3::Socket::CreateSocket(), ns3::Ipv4Address::GetAny(), ns3::Application::GetNode(), ns3::TypeId::LookupByName(), m_remote, m_size, m_socket, m_started, m_verbose, ns3::MakeCallback(), ns3::Simulator::Now(), NS_ASSERT, NS_LOG_FUNCTION, Receive(), Send(), ns3::ObjectBase::SetAttribute(), and ns3::Socket::SetRecvCallback().
StopApplication()
void ns3::V4Ping::StopApplication (void) private virtual
Application specific shutdown code.
The StopApplication method is called at the stop time specified by Stop This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 267 of file v4ping.cc.
References ns3::Average< T >::Avg(), ns3::EventId::Cancel(), ns3::Socket::Close(), ns3::Average< T >::Count(), ns3::EventId::IsRunning(), m_avgRtt, m_next, m_recv, m_remote, m_seq, m_socket, m_started, m_verbose, ns3::Average< T >::Max(), ns3::Average< T >::Min(), ns3::Time::MS, ns3::Simulator::Now(), NS_LOG_FUNCTION, and ns3::Average< T >::Stddev().
Referenced by DoDispose().
Write32()
void ns3::V4Ping::Write32 (uint8_t * buffer, const uint32_t data) private
Writes data to buffer in little-endian format.
Least significant byte of data is at lowest buffer address
Parameters
buffer the buffer to write to
data the data to write
Definition at line 179 of file v4ping.cc.
References data, and NS_LOG_FUNCTION.
Referenced by Send().
Member Data Documentation
m_avgRtt
Average<double> ns3::V4Ping::m_avgRtt private
Average rtt is ms.
Definition at line 117 of file v4ping.h.
Referenced by Receive(), and StopApplication().
m_interval
Time ns3::V4Ping::m_interval private
Wait interval seconds between sending each packet.
Definition at line 98 of file v4ping.h.
Referenced by GetTypeId(), and Send().
m_next
EventId ns3::V4Ping::m_next private
Next packet will be sent.
Definition at line 119 of file v4ping.h.
Referenced by DoDispose(), Send(), and StopApplication().
m_recv
uint32_t ns3::V4Ping::m_recv private
received packets counter
Definition at line 113 of file v4ping.h.
Referenced by Receive(), and StopApplication().
m_remote
Ipv4Address ns3::V4Ping::m_remote private
Remote address.
Definition at line 96 of file v4ping.h.
Referenced by GetTypeId(), StartApplication(), and StopApplication().
m_sent
std::map<uint16_t, Time> ns3::V4Ping::m_sent private
All sent but not answered packets. Map icmp seqno -> when sent.
Definition at line 121 of file v4ping.h.
Referenced by Receive(), and Send().
m_seq
uint16_t ns3::V4Ping::m_seq private
ICMP ECHO sequence number.
Definition at line 107 of file v4ping.h.
Referenced by Send(), and StopApplication().
m_size
uint32_t ns3::V4Ping::m_size private
Specifies the number of data bytes to be sent.
The default is 56, which translates into 64 ICMP data bytes when combined with the 8 bytes of ICMP header data.
Definition at line 103 of file v4ping.h.
Referenced by GetTypeId(), Receive(), Send(), and StartApplication().
m_socket
Ptr<Socket> ns3::V4Ping::m_socket private
The socket we send packets from.
Definition at line 105 of file v4ping.h.
Referenced by DoDispose(), Receive(), Send(), StartApplication(), and StopApplication().
m_started
Time ns3::V4Ping::m_started private
Start time to report total ping time.
Definition at line 115 of file v4ping.h.
Referenced by StartApplication(), and StopApplication().
m_traceRtt
TracedCallback<Time> ns3::V4Ping::m_traceRtt private
TracedCallback for RTT measured by ICMP ECHOs.
Definition at line 109 of file v4ping.h.
Referenced by GetTypeId(), and Receive().
m_verbose
bool ns3::V4Ping::m_verbose private
produce ping-style output if true
Definition at line 111 of file v4ping.h.
Referenced by GetTypeId(), Receive(), StartApplication(), and StopApplication().
The documentation for this class was generated from the following files:
src/internet-apps/model/v4ping.h
src/internet-apps/model/v4ping.cc