ns-3: PacketTagListTest Class Reference
PacketTagListTest Class Reference
Network » Network module unit tests | Test suites
Packet Tag list unit tests.
Public Member Functions
PacketTagListTest ()
virtual ~PacketTagListTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
int AddRemoveTime (const bool verbose=false)
Prints the remove time.
void CheckRef (const PacketTagList &ref, ATestTagBase &t, const char *msg, bool miss=false)
Checks against a reference PacketTagList.
void CheckRefList (const PacketTagList &ref, const char *msg, int miss=0)
Checks against a reference PacketTagList.
void DoRun (void)
Implementation to actually run this TestCase.
int RemoveTime (const PacketTagList &ref, ATestTagBase &t, const char *msg=0)
Prints the remove time.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Packet Tag list unit tests.
Definition at line 863 of file packet-test-suite.cc.
Constructor & Destructor Documentation
PacketTagListTest()
PacketTagListTest::PacketTagListTest ()
Definition at line 910 of file packet-test-suite.cc.
~PacketTagListTest()
PacketTagListTest::~PacketTagListTest () virtual
Definition at line 915 of file packet-test-suite.cc.
Member Function Documentation
AddRemoveTime()
int PacketTagListTest::AddRemoveTime (const bool verbose = false) private
Prints the remove time.
Parameters
verbose prints on cout if verbose is true.
Returns
the ticks to remove the tags.
Definition at line 989 of file packet-test-suite.cc.
References ns3::PacketTagList::Add(), ns3::TestCase::GetName(), ns3::PacketTagList::Remove(), visualizer.core::start(), and verbose.
Referenced by DoRun().
CheckRef()
void PacketTagListTest::CheckRef (const PacketTagList & ref, ATestTagBase & t, const char * msg, bool miss = false) private
Checks against a reference PacketTagList.
Parameters
ref Reference
t List to test
msg Message
miss Expected miss/hit
Definition at line 920 of file packet-test-suite.cc.
References NS_TEST_EXPECT_MSG_EQ, and ns3::PacketTagList::Peek().
Referenced by CheckRefList(), and DoRun().
CheckRefList()
void PacketTagListTest::CheckRefList (const PacketTagList & ref, const char * msg, int miss = 0) private
Checks against a reference PacketTagList.
Parameters
ref Reference
msg Message
miss Expected miss/hit
Definition at line 952 of file packet-test-suite.cc.
References CheckRef(), and MAKE_TEST_TAGS.
Referenced by DoRun().
DoRun()
void PacketTagListTest::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 1011 of file packet-test-suite.cc.
References ns3::PacketTagList::Add(), AddRemoveTime(), CheckRef(), CheckRefList(), ns3::TestCase::GetName(), MAKE_TEST_TAGS, max, NS_TEST_EXPECT_MSG_EQ, ns3::PacketTagList::Peek(), ns3::PacketTagList::Remove(), RemoveCheck, RemoveTime(), and ReplaceCheck.
RemoveTime()
int PacketTagListTest::RemoveTime (const PacketTagList & ref, ATestTagBase & t, const char * msg = 0) private
Prints the remove time.
Parameters
ref Reference.
t List to test.
msg Message - prints on cout if msg is not null.
Returns
the ticks to remove the tags.
Definition at line 967 of file packet-test-suite.cc.
References ns3::TestCase::GetName(), and visualizer.core::start().
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/network/test/packet-test-suite.cc