ns-3: SimulatorTemplateTestCase Class Reference
SimulatorTemplateTestCase Class Reference
Public Member Functions
SimulatorTemplateTestCase ()
void Ref (void) const
void Unref (void) const
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void bar0 (void)
void bar0c (void) const
void bar1 (int)
void bar1c (int) const
void bar2 (int, int)
void bar2c (int, int) const
void bar3 (int, int, int)
void bar3c (int, int, int) const
void bar4 (int, int, int, int)
void bar4c (int, int, int, int) const
void bar5 (int, int, int, int, int)
void bar5c (int, int, int, int, int) const
void baz1 (int &)
void baz1c (int &) const
void baz2 (int &, int &)
void baz2c (int &, int &) const
void baz3 (int &, int &, int &)
void baz3c (int &, int &, int &) const
void baz4 (int &, int &, int &, int &)
void baz4c (int &, int &, int &, int &) const
void baz5 (int &, int &, int &, int &, int &)
void baz5c (int &, int &, int &, int &, int &) const
void cbaz1 (const int &)
void cbaz1c (const int &) const
void cbaz2 (const int &, const int &)
void cbaz2c (const int &, const int &) const
void cbaz3 (const int &, const int &, const int &)
void cbaz3c (const int &, const int &, const int &) const
void cbaz4 (const int &, const int &, const int &, const int &)
void cbaz4c (const int &, const int &, const int &, const int &) const
void cbaz5 (const int &, const int &, const int &, const int &, const int &)
void cbaz5c (const int &, const int &, const int &, const int &, const int &) const
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 173 of file simulator-test-suite.cc.
Constructor & Destructor Documentation
SimulatorTemplateTestCase()
SimulatorTemplateTestCase::SimulatorTemplateTestCase ()
Definition at line 257 of file simulator-test-suite.cc.
Member Function Documentation
bar0()
void SimulatorTemplateTestCase::bar0 (void) inline private
Definition at line 187 of file simulator-test-suite.cc.
Referenced by DoRun().
bar0c()
void SimulatorTemplateTestCase::bar0c (void) const inline private
Definition at line 204 of file simulator-test-suite.cc.
Referenced by DoRun().
bar1()
void SimulatorTemplateTestCase::bar1 (int) inline private
Definition at line 188 of file simulator-test-suite.cc.
Referenced by DoRun().
bar1c()
void SimulatorTemplateTestCase::bar1c (int) const inline private
Definition at line 205 of file simulator-test-suite.cc.
Referenced by DoRun().
bar2()
void SimulatorTemplateTestCase::bar2 (int , int) inline private
Definition at line 189 of file simulator-test-suite.cc.
Referenced by DoRun().
bar2c()
void SimulatorTemplateTestCase::bar2c (int , int) const inline private
Definition at line 206 of file simulator-test-suite.cc.
Referenced by DoRun().
bar3()
void SimulatorTemplateTestCase::bar3 (int , int , int) inline private
Definition at line 190 of file simulator-test-suite.cc.
Referenced by DoRun().
bar3c()
void SimulatorTemplateTestCase::bar3c (int , int , int) const inline private
Definition at line 207 of file simulator-test-suite.cc.
Referenced by DoRun().
bar4()
void SimulatorTemplateTestCase::bar4 (int , int , int , int) inline private
Definition at line 191 of file simulator-test-suite.cc.
Referenced by DoRun().
bar4c()
void SimulatorTemplateTestCase::bar4c (int , int , int , int) const inline private
Definition at line 208 of file simulator-test-suite.cc.
Referenced by DoRun().
bar5()
void SimulatorTemplateTestCase::bar5 (int , int , int , int , int) inline private
Definition at line 192 of file simulator-test-suite.cc.
Referenced by DoRun().
bar5c()
void SimulatorTemplateTestCase::bar5c (int , int , int , int , int) const inline private
Definition at line 209 of file simulator-test-suite.cc.
Referenced by DoRun().
baz1()
void SimulatorTemplateTestCase::baz1 (int &) inline private
Definition at line 193 of file simulator-test-suite.cc.
Referenced by DoRun().
baz1c()
void SimulatorTemplateTestCase::baz1c (int &) const inline private
Definition at line 210 of file simulator-test-suite.cc.
Referenced by DoRun().
baz2()
void SimulatorTemplateTestCase::baz2 (int & , int &) inline private
Definition at line 194 of file simulator-test-suite.cc.
Referenced by DoRun().
baz2c()
void SimulatorTemplateTestCase::baz2c (int & , int &) const inline private
Definition at line 211 of file simulator-test-suite.cc.
Referenced by DoRun().
baz3()
void SimulatorTemplateTestCase::baz3 (int & , int & , int &) inline private
Definition at line 195 of file simulator-test-suite.cc.
Referenced by DoRun().
baz3c()
void SimulatorTemplateTestCase::baz3c (int & , int & , int &) const inline private
Definition at line 212 of file simulator-test-suite.cc.
Referenced by DoRun().
baz4()
void SimulatorTemplateTestCase::baz4 (int & , int & , int & , int &) inline private
Definition at line 196 of file simulator-test-suite.cc.
Referenced by DoRun().
baz4c()
void SimulatorTemplateTestCase::baz4c (int & , int & , int & , int &) const inline private
Definition at line 213 of file simulator-test-suite.cc.
Referenced by DoRun().
baz5()
void SimulatorTemplateTestCase::baz5 (int & , int & , int & , int & , int &) inline private
Definition at line 197 of file simulator-test-suite.cc.
Referenced by DoRun().
baz5c()
void SimulatorTemplateTestCase::baz5c (int & , int & , int & , int & , int &) const inline private
Definition at line 214 of file simulator-test-suite.cc.
Referenced by DoRun().
cbaz1()
void SimulatorTemplateTestCase::cbaz1 (const int &) inline private
Definition at line 198 of file simulator-test-suite.cc.
Referenced by DoRun().
cbaz1c()
void SimulatorTemplateTestCase::cbaz1c (const int &) const inline private
Definition at line 215 of file simulator-test-suite.cc.
Referenced by DoRun().
cbaz2()
void SimulatorTemplateTestCase::cbaz2 (const int & , const int &) inline private
Definition at line 199 of file simulator-test-suite.cc.
Referenced by DoRun().
cbaz2c()
void SimulatorTemplateTestCase::cbaz2c (const int & , const int &) const inline private
Definition at line 216 of file simulator-test-suite.cc.
Referenced by DoRun().
cbaz3()
void SimulatorTemplateTestCase::cbaz3 (const int & , const int & , const int &) inline private
Definition at line 200 of file simulator-test-suite.cc.
Referenced by DoRun().
cbaz3c()
void SimulatorTemplateTestCase::cbaz3c (const int & , const int & , const int &) const inline private
Definition at line 217 of file simulator-test-suite.cc.
Referenced by DoRun().
cbaz4()
void SimulatorTemplateTestCase::cbaz4 (const int & , const int & , const int & , const int &) inline private
Definition at line 201 of file simulator-test-suite.cc.
Referenced by DoRun().
cbaz4c()
void SimulatorTemplateTestCase::cbaz4c (const int & , const int & , const int & , const int &) const inline private
Definition at line 218 of file simulator-test-suite.cc.
Referenced by DoRun().
cbaz5()
void SimulatorTemplateTestCase::cbaz5 (const int & , const int & , const int & , const int & , const int &) inline private
Definition at line 202 of file simulator-test-suite.cc.
Referenced by DoRun().
cbaz5c()
void SimulatorTemplateTestCase::cbaz5c (const int & , const int & , const int & , const int & , const int &) const inline private
Definition at line 219 of file simulator-test-suite.cc.
Referenced by DoRun().
DoRun()
void SimulatorTemplateTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 261 of file simulator-test-suite.cc.
References bar0(), bar0c(), bar1(), bar1c(), bar2(), bar2c(), bar3(), bar3c(), bar4(), bar4c(), bar5(), bar5c(), baz1(), baz1c(), baz2(), baz2c(), baz3(), baz3c(), baz4(), baz4c(), baz5(), baz5c(), ber1(), ber2(), ber3(), ber4(), ber5(), cbaz1(), cbaz1c(), cbaz2(), cbaz2c(), cbaz3(), cbaz3c(), cbaz4(), cbaz4c(), cbaz5(), cbaz5c(), cber1(), cber2(), cber3(), cber4(), cber5(), foo0(), foo1(), foo2(), foo3(), foo4(), foo5(), and ns3::Seconds().
Ref()
void SimulatorTemplateTestCase::Ref (void) const inline
Definition at line 178 of file simulator-test-suite.cc.
Unref()
void SimulatorTemplateTestCase::Unref (void) const inline
Definition at line 180 of file simulator-test-suite.cc.
The documentation for this class was generated from the following file:
src/core/test/simulator-test-suite.cc