ns-3: ns3::TimeSeriesAdaptor Class Reference
ns3::TimeSeriesAdaptor Class Reference
Statistics » Data Aggregators
Takes probed values of different types and outputs the current time plus the value with both converted to doubles.
#include "time-series-adaptor.h"
Public Types
typedef void(* OutputTracedCallback) (const double now, const double data)
TracedCallback signature for output trace.
Public Member Functions
TimeSeriesAdaptor ()
virtual ~TimeSeriesAdaptor ()
void TraceSinkBoolean (bool oldData, bool newData)
Trace sink for receiving data from bool valued trace sources.
void TraceSinkDouble (double oldData, double newData)
Trace sink for receiving data from double valued trace sources.
void TraceSinkUinteger16 (uint16_t oldData, uint16_t newData)
Trace sink for receiving data from uint16_t valued trace sources.
void TraceSinkUinteger32 (uint32_t oldData, uint32_t newData)
Trace sink for receiving data from uint32_t valued trace sources.
void TraceSinkUinteger8 (uint8_t oldData, uint8_t newData)
Trace sink for receiving data from uint8_t valued trace sources.
Public Member Functions inherited from ns3::DataCollectionObject
DataCollectionObject ()
virtual ~DataCollectionObject ()
void Disable (void)
Unset the status of an individual object.
void Enable (void)
Set the status of an individual object.
std::string GetName (void) const
Get the object's name.
virtual bool IsEnabled (void) const
Check the status of an individual object.
void SetName (std::string name)
Set the object's name. All spaces are replaced by underscores.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::DataCollectionObject
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
TracedCallback< double, double > m_output
output trace
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::DataCollectionObject
bool m_enabled
Object's activation state.
std::string m_name
Name of the object within the data collection framework.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Takes probed values of different types and outputs the current time plus the value with both converted to doubles.
Introspection did not find any typical Config paths.
The role of the TimeSeriesAdaptor class is that of an adaptor class, to take raw-valued probe data of different types, and output a tuple of two double values. The first is a timestamp which may be set to different resolutions (e.g. Seconds, Milliseconds, etc.) in the future, but which presently is hardcoded to Seconds. The second is the conversion of a non-double value to a double value (possibly with loss of precision).
It should be noted that time series adaptors convert Simulation Time objects to double values in its output.
No Attributes are defined for this type.
Attributes defined in parent class ns3::DataCollectionObject
Name: Object's name
Set with class: StringValue
Underlying type:
Initial value: unnamed
Flags: construct write read
Enabled: Object's enabled status
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
TraceSources
Output: The current simulation time versus the current value converted to a double
Callback signature: ns3::TimeSeriesAdaptor::OutputTracedCallback
Size of this type is 80 bytes (on a 64-bit architecture).
Definition at line 48 of file time-series-adaptor.h.
Member Typedef Documentation
OutputTracedCallback
typedef void(* ns3::TimeSeriesAdaptor::OutputTracedCallback) (const double now, const double data)
TracedCallback signature for output trace.
Parameters
[in] now The current time, in seconds.
[in] data The new data value.
Definition at line 121 of file time-series-adaptor.h.
Constructor & Destructor Documentation
TimeSeriesAdaptor()
ns3::TimeSeriesAdaptor::TimeSeriesAdaptor ()
Definition at line 52 of file time-series-adaptor.cc.
References NS_LOG_FUNCTION.
~TimeSeriesAdaptor()
ns3::TimeSeriesAdaptor::~TimeSeriesAdaptor () virtual
Definition at line 57 of file time-series-adaptor.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
GetTypeId()
TypeId ns3::TimeSeriesAdaptor::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 37 of file time-series-adaptor.cc.
References m_output, ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
TraceSinkBoolean()
void ns3::TimeSeriesAdaptor::TraceSinkBoolean (bool oldData, bool newData)
Trace sink for receiving data from bool valued trace sources.
Parameters
oldData the original value.
newData the new value.
This method serves as a trace sink to bool valued trace sources.
Definition at line 79 of file time-series-adaptor.cc.
References NS_LOG_FUNCTION, and TraceSinkDouble().
Referenced by ns3::FileHelper::ConnectProbeToAggregator(), and ns3::GnuplotHelper::ConnectProbeToAggregator().
TraceSinkDouble()
void ns3::TimeSeriesAdaptor::TraceSinkDouble (double oldData, double newData)
Trace sink for receiving data from double valued trace sources.
Parameters
oldData the original value.
newData the new value.
This method serves as a trace sink to double valued trace sources.
Definition at line 63 of file time-series-adaptor.cc.
References ns3::DataCollectionObject::IsEnabled(), m_output, ns3::Simulator::Now(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by ns3::FileHelper::ConnectProbeToAggregator(), ns3::GnuplotHelper::ConnectProbeToAggregator(), TraceSinkBoolean(), TraceSinkUinteger16(), TraceSinkUinteger32(), and TraceSinkUinteger8().
TraceSinkUinteger16()
void ns3::TimeSeriesAdaptor::TraceSinkUinteger16 (uint16_t oldData, uint16_t newData)
Trace sink for receiving data from uint16_t valued trace sources.
Parameters
oldData the original value.
newData the new value.
This method serves as a trace sink to uint16_t valued trace sources.
Definition at line 97 of file time-series-adaptor.cc.
References NS_LOG_FUNCTION, and TraceSinkDouble().
Referenced by ns3::FileHelper::ConnectProbeToAggregator(), and ns3::GnuplotHelper::ConnectProbeToAggregator().
TraceSinkUinteger32()
void ns3::TimeSeriesAdaptor::TraceSinkUinteger32 (uint32_t oldData, uint32_t newData)
Trace sink for receiving data from uint32_t valued trace sources.
Parameters
oldData the original value.
newData the new value.
This method serves as a trace sink to uint32_t valued trace sources.
Definition at line 106 of file time-series-adaptor.cc.
References NS_LOG_FUNCTION, and TraceSinkDouble().
Referenced by ns3::FileHelper::ConnectProbeToAggregator(), and ns3::GnuplotHelper::ConnectProbeToAggregator().
TraceSinkUinteger8()
void ns3::TimeSeriesAdaptor::TraceSinkUinteger8 (uint8_t oldData, uint8_t newData)
Trace sink for receiving data from uint8_t valued trace sources.
Parameters
oldData the original value.
newData the new value.
This method serves as a trace sink to uint8_t valued trace sources.
Definition at line 88 of file time-series-adaptor.cc.
References NS_LOG_FUNCTION, and TraceSinkDouble().
Referenced by ns3::FileHelper::ConnectProbeToAggregator(), and ns3::GnuplotHelper::ConnectProbeToAggregator().
Member Data Documentation
m_output
TracedCallback<double, double> ns3::TimeSeriesAdaptor::m_output private
output trace
Definition at line 124 of file time-series-adaptor.h.
Referenced by GetTypeId(), and TraceSinkDouble().
The documentation for this class was generated from the following files:
src/stats/model/time-series-adaptor.h
src/stats/model/time-series-adaptor.cc