ns-3: ns3::Ping6 Class Reference
ns3::Ping6 Class Reference
Internet Applications » Ping6
A ping6 application.
#include "ping6.h"
Public Member Functions
Ping6 ()
Constructor.
virtual ~Ping6 ()
Destructor.
void SetIfIndex (uint32_t ifIndex)
Set the out interface index.
void SetLocal (Ipv6Address ipv6)
Set the local address.
void SetRemote (Ipv6Address ipv6)
Set the remote peer.
void SetRouters (std::vector< Ipv6Address > routers)
Set routers for routing type 0 (loose routing).
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose ()
Dispose this object;.
Protected Member Functions inherited from ns3::Application
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void HandleRead (Ptr< Socket > socket)
Receive method.
void ScheduleTransmit (Time dt)
Schedule sending a packet.
void Send ()
Send a packet.
virtual void StartApplication ()
Start the application.
virtual void StopApplication ()
Stop the application.
Private Attributes
Ipv6Address m_address
Peer IPv6 address.
uint32_t m_count
Number of "Echo request" packets that will be sent.
uint32_t m_ifIndex
Out interface (i.e.
Time m_interval
Intervall between packets sent.
Ipv6Address m_localAddress
Local address.
Ipv6Address m_peerAddress
Peer address.
std::vector< Ipv6Address > m_routers
Routers addresses for routing type 0.
EventId m_sendEvent
Event ID.
uint32_t m_sent
Number of packets sent.
uint16_t m_seq
Sequence number.
uint32_t m_size
Size of the packet.
Ptr< Socket > m_socket
Local socket.
Additional Inherited Members
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A ping6 application.
Config Paths
ns3::Ping6 is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/ApplicationList/[i]/$ns3::Ping6"
Attributes
MaxPackets: The maximum number of packets the application will send
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 100
Flags: construct write read
Interval: The time to wait between packets
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+09ns
Flags: construct write read
RemoteIpv6: The Ipv6Address of the outbound packets
Set with class: Ipv6AddressValue
Underlying type: Ipv6Address
Initial value: ::
Flags: construct write read
LocalIpv6: Local Ipv6Address of the sender
Set with class: Ipv6AddressValue
Underlying type: Ipv6Address
Initial value: ::
Flags: construct write read
PacketSize: Size of packets generated
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 100
Flags: construct write read
Attributes defined in parent class ns3::Application
StartTime: Time at which the application will start
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
StopTime: Time at which the application will stop
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 256 bytes (on a 64-bit architecture).
Definition at line 42 of file ping6.h.
Constructor & Destructor Documentation
Ping6()
ns3::Ping6::Ping6 ()
Constructor.
Definition at line 79 of file ping6.cc.
References m_sendEvent, m_sent, m_seq, m_socket, and NS_LOG_FUNCTION.
~Ping6()
ns3::Ping6::~Ping6 () virtual
Destructor.
Definition at line 88 of file ping6.cc.
References m_socket, and NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::Ping6::DoDispose (void) protected virtual
Dispose this object;.
Reimplemented from ns3::Application.
Definition at line 94 of file ping6.cc.
References ns3::Application::DoDispose(), and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::Ping6::GetTypeId (void) static
Get the type ID.
Returns
type ID
Definition at line 44 of file ping6.cc.
References m_count, m_interval, m_localAddress, m_peerAddress, m_size, ns3::MakeIpv6AddressAccessor(), ns3::MakeIpv6AddressChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeUintegerAccessor(), ns3::Seconds(), and ns3::TypeId::SetParent().
Referenced by ns3::Ping6Helper::Ping6Helper().
HandleRead()
void ns3::Ping6::HandleRead (Ptr< Socket > socket) private
Receive method.
Parameters
socket socket that receive a packet
Definition at line 242 of file ping6.cc.
References first::address, ns3::Inet6SocketAddress::ConvertFrom(), ns3::Packet::CopyData(), ns3::Ipv6Header::GetHopLimit(), ns3::Icmpv6Echo::GetId(), ns3::Icmpv6Echo::GetSeq(), ns3::Packet::GetSize(), ns3::Icmpv6Header::ICMPV6_ECHO_REPLY, ns3::Icmpv6Header::ICMPV6_ERROR_DESTINATION_UNREACHABLE, ns3::Icmpv6Header::ICMPV6_ERROR_TIME_EXCEEDED, ns3::Inet6SocketAddress::IsMatchingType(), NS_LOG_FUNCTION, NS_LOG_INFO, ns3::Socket::RecvFrom(), and ns3::Packet::RemoveHeader().
Referenced by StartApplication().
ScheduleTransmit()
void ns3::Ping6::ScheduleTransmit (Time dt) private
Schedule sending a packet.
Parameters
dt interval between packet
Definition at line 148 of file ping6.cc.
References m_sendEvent, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), and Send().
Referenced by Send(), and StartApplication().
Send()
void ns3::Ping6::Send (void) private
Send a packet.
Definition at line 159 of file ping6.cc.
References ns3::Packet::AddHeader(), ns3::Socket::Bind(), data, ns3::Ipv6InterfaceAddress::GetAddress(), ns3::Application::GetNode(), ns3::Object::GetObject(), ns3::Packet::GetSize(), ns3::Ipv6Header::IPV6_EXT_ROUTING, ns3::Ipv6Header::IPV6_ICMPV6, ns3::EventId::IsExpired(), ns3::Ipv6InterfaceAddress::IsInSameSubnet(), m_count, m_ifIndex, m_interval, m_localAddress, m_peerAddress, m_routers, m_sendEvent, m_sent, m_seq, m_size, m_socket, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_WARN, ScheduleTransmit(), ns3::Socket::SendTo(), ns3::ObjectBase::SetAttribute(), ns3::Icmpv6Echo::SetId(), ns3::Ipv6ExtensionHeader::SetNextHeader(), ns3::Ipv6ExtensionLooseRoutingHeader::SetRoutersAddress(), ns3::Ipv6ExtensionRoutingHeader::SetSegmentsLeft(), ns3::Icmpv6Echo::SetSeq(), and ns3::Ipv6ExtensionRoutingHeader::SetTypeRouting().
Referenced by ScheduleTransmit().
SetIfIndex()
void ns3::Ping6::SetIfIndex (uint32_t ifIndex)
Set the out interface index.
This is to send to link-local (unicast or multicast) address when a node has multiple interfaces.
Parameters
ifIndex interface index
Definition at line 143 of file ping6.cc.
References m_ifIndex.
SetLocal()
void ns3::Ping6::SetLocal (Ipv6Address ipv6)
Set the local address.
Parameters
ipv6 the local IPv6 address
Definition at line 119 of file ping6.cc.
References m_localAddress, and NS_LOG_FUNCTION.
SetRemote()
void ns3::Ping6::SetRemote (Ipv6Address ipv6)
Set the remote peer.
Parameters
ipv6 IPv6 address of the peer
Definition at line 125 of file ping6.cc.
References m_peerAddress, and NS_LOG_FUNCTION.
SetRouters()
void ns3::Ping6::SetRouters (std::vector< Ipv6Address > routers)
Set routers for routing type 0 (loose routing).
Parameters
routers routers addresses
Definition at line 154 of file ping6.cc.
References m_routers.
StartApplication()
void ns3::Ping6::StartApplication (void) private virtual
Start the application.
Reimplemented from ns3::Application.
Definition at line 100 of file ping6.cc.
References ns3::Socket::Bind(), ns3::Socket::CreateSocket(), ns3::Application::GetNode(), HandleRead(), ns3::Ipv6Header::IPV6_ICMPV6, ns3::TypeId::LookupByName(), m_localAddress, m_socket, ns3::MakeCallback(), NS_ASSERT, NS_LOG_FUNCTION, ScheduleTransmit(), ns3::Seconds(), ns3::ObjectBase::SetAttribute(), and ns3::Socket::SetRecvCallback().
StopApplication()
void ns3::Ping6::StopApplication (void) private virtual
Stop the application.
Reimplemented from ns3::Application.
Definition at line 131 of file ping6.cc.
References ns3::Simulator::Cancel(), m_sendEvent, m_socket, ns3::MakeNullCallback(), NS_LOG_FUNCTION, and ns3::Socket::SetRecvCallback().
Member Data Documentation
m_address
Ipv6Address ns3::Ping6::m_address private
Peer IPv6 address.
Definition at line 124 of file ping6.h.
m_count
uint32_t ns3::Ping6::m_count private
Number of "Echo request" packets that will be sent.
Definition at line 129 of file ping6.h.
Referenced by GetTypeId(), and Send().
m_ifIndex
uint32_t ns3::Ping6::m_ifIndex private
Out interface (i.e.
for link-local communication).
Definition at line 174 of file ping6.h.
Referenced by Send(), and SetIfIndex().
m_interval
Time ns3::Ping6::m_interval private
Intervall between packets sent.
Definition at line 144 of file ping6.h.
Referenced by GetTypeId(), and Send().
m_localAddress
Ipv6Address ns3::Ping6::m_localAddress private
Local address.
Definition at line 149 of file ping6.h.
Referenced by GetTypeId(), Send(), SetLocal(), and StartApplication().
m_peerAddress
Ipv6Address ns3::Ping6::m_peerAddress private
Peer address.
Definition at line 154 of file ping6.h.
Referenced by GetTypeId(), Send(), and SetRemote().
m_routers
std::vector<Ipv6Address> ns3::Ping6::m_routers private
Routers addresses for routing type 0.
Definition at line 179 of file ping6.h.
Referenced by Send(), and SetRouters().
m_sendEvent
EventId ns3::Ping6::m_sendEvent private
Event ID.
Definition at line 169 of file ping6.h.
Referenced by Ping6(), ScheduleTransmit(), Send(), and StopApplication().
m_sent
uint32_t ns3::Ping6::m_sent private
Number of packets sent.
Definition at line 134 of file ping6.h.
Referenced by Ping6(), and Send().
m_seq
uint16_t ns3::Ping6::m_seq private
Sequence number.
Definition at line 164 of file ping6.h.
Referenced by Ping6(), and Send().
m_size
uint32_t ns3::Ping6::m_size private
Size of the packet.
Definition at line 139 of file ping6.h.
Referenced by GetTypeId(), and Send().
m_socket
Ptr<Socket> ns3::Ping6::m_socket private
Local socket.
Definition at line 159 of file ping6.h.
Referenced by Ping6(), ~Ping6(), Send(), StartApplication(), and StopApplication().
The documentation for this class was generated from the following files:
src/internet-apps/model/ping6.h
src/internet-apps/model/ping6.cc