ns-3: ns3::ClassificationRuleVectorTlvValue Class Reference
ns3::ClassificationRuleVectorTlvValue Class Reference
WiMAX Models
this class implements the classifier descriptor as a tlv vector
#include "wimax-tlv.h"
Public Types
enum ClassificationRuleTlvType {
Priority = 1 , ToS = 2 , Protocol = 3 , IP_src = 4 ,
IP_dst = 5 , Port_src = 6 , Port_dst = 7 , Index = 14
}
ClassificationRuleTlvType enumeration.
Public Types inherited from ns3::VectorTlvValue
typedef std::vector< Tlv * >::const_iterator Iterator
TLV vector iterator typedef.
Public Member Functions
ClassificationRuleVectorTlvValue ()
virtual ClassificationRuleVectorTlvValue * Copy (void) const
Copy.
virtual uint32_t Deserialize (Buffer::Iterator start, uint64_t valueLength)
Deserialize from a buffer.
Public Member Functions inherited from ns3::VectorTlvValue
VectorTlvValue (void)
~VectorTlvValue (void)
void Add (const Tlv &val)
Add a TLV.
Iterator Begin () const
Begin iterator.
Iterator End () const
End iterator.
virtual uint32_t GetSerializedSize (void) const
Get serialized size in bytes.
virtual void Serialize (Buffer::Iterator start) const
Serialize to a buffer.
Public Member Functions inherited from ns3::TlvValue
virtual ~TlvValue ()
Detailed Description
this class implements the classifier descriptor as a tlv vector
Definition at line 397 of file wimax-tlv.h.
Member Enumeration Documentation
ClassificationRuleTlvType
enum ns3::ClassificationRuleVectorTlvValue::ClassificationRuleTlvType
ClassificationRuleTlvType enumeration.
Enumerator
Priority
ToS
Protocol
IP_src
IP_dst
Port_src
Port_dst
Index
Definition at line 401 of file wimax-tlv.h.
Constructor & Destructor Documentation
ClassificationRuleVectorTlvValue()
ns3::ClassificationRuleVectorTlvValue::ClassificationRuleVectorTlvValue ()
Definition at line 713 of file wimax-tlv.cc.
Referenced by Copy().
Member Function Documentation
Copy()
ClassificationRuleVectorTlvValue * ns3::ClassificationRuleVectorTlvValue::Copy (void) const virtual
Copy.
Returns
the vector TLV value
Implements ns3::VectorTlvValue.
Definition at line 719 of file wimax-tlv.cc.
References ClassificationRuleVectorTlvValue(), ns3::VectorTlvValue::Add(), ns3::VectorTlvValue::Begin(), and ns3::VectorTlvValue::End().
Deserialize()
uint32_t ns3::ClassificationRuleVectorTlvValue::Deserialize (Buffer::Iterator start, uint64_t valueLen) virtual
Deserialize from a buffer.
Parameters
start the iterator
valueLen the maximum length of the value
Returns
the
Implements ns3::VectorTlvValue.
Definition at line 730 of file wimax-tlv.cc.
References ns3::VectorTlvValue::Add(), ns3::U8TlvValue::Deserialize(), ns3::U16TlvValue::Deserialize(), ns3::TosTlvValue::Deserialize(), ns3::PortRangeTlvValue::Deserialize(), ns3::ProtocolTlvValue::Deserialize(), ns3::Ipv4AddressTlvValue::Deserialize(), ns3::TosTlvValue::GetSerializedSize(), ns3::PortRangeTlvValue::GetSerializedSize(), ns3::ProtocolTlvValue::GetSerializedSize(), ns3::Ipv4AddressTlvValue::GetSerializedSize(), Index, IP_dst, IP_src, ns3::Buffer::Iterator::Next(), Port_dst, Port_src, Priority, Protocol, ns3::Buffer::Iterator::ReadU8(), ToS, and WIMAX_TLV_EXTENDED_LENGTH_MASK.
Referenced by ns3::CsParamVectorTlvValue::Deserialize().
The documentation for this class was generated from the following files:
src/wimax/model/wimax-tlv.h
src/wimax/model/wimax-tlv.cc