ns-3: ns3::PyViz Class Reference
ns3::PyViz Class Reference
Visualizer
helper class to be used by the visualizer
#include "pyviz.h"
Classes
struct LastPacketsSample
LastPacketsSample structure.
struct NetDeviceStatistics
NetDeviceStatistics structure.
struct NodeStatistics
NodeStatistics structure.
struct PacketCaptureOptions
PacketCaptureOptions structure.
struct PacketDropSample
PacketDropSample structure.
struct PacketSample
PacketSample structure.
struct RxPacketSample
RxPacketSample structure.
struct TransmissionSample
TransmissionSample structure.
struct TransmissionSampleKey
TransmissionSampleKey structure.
struct TransmissionSampleValue
TransmissionSampleValue structure.
struct TxPacketSample
TxPacketSample structure.
struct TxRecordValue
TxRecordValue structure.
Public Types
enum PacketCaptureMode { PACKET_CAPTURE_DISABLED =1 , PACKET_CAPTURE_FILTER_HEADERS_OR , PACKET_CAPTURE_FILTER_HEADERS_AND }
PacketCaptureMode enumeration.
typedef std::vector< PacketDropSample > PacketDropSampleList
PacketDropSampleList typedef.
typedef std::vector< TransmissionSample > TransmissionSampleList
TransmissionSampleList typedef.
Public Member Functions
PyViz ()
~PyViz ()
LastPacketsSample GetLastPackets (uint32_t nodeId) const
Get last packets function.
std::vector< NodeStatistics > GetNodesStatistics () const
Get node statistics.
PacketDropSampleList GetPacketDropSamples () const
Get packet drop samples.
std::vector< std::string > GetPauseMessages () const
Get pause message function.
TransmissionSampleList GetTransmissionSamples () const
Get transmission samples.
void RegisterCsmaLikeDevice (std::string const &deviceTypeName)
Register CSMA like device function.
void RegisterDropTracePath (std::string const &tracePath)
Register drop trace path function.
void RegisterPointToPointLikeDevice (std::string const &deviceTypeName)
Register point to point like device function.
void RegisterWifiLikeDevice (std::string const &deviceTypeName)
Register WIFI like device function.
void SetNodesOfInterest (std::set< uint32_t > nodes)
Set nodes of interest function.
void SetPacketCaptureOptions (uint32_t nodeId, PacketCaptureOptions options)
Set packet capture options function.
void SimulatorRunUntil (Time time)
Run simulation until a given (simulated, absolute) time is reached.
Static Public Member Functions
static void LineClipping (double boundsX1, double boundsY1, double boundsX2, double boundsY2, double &lineX1, double &lineY1, double &lineX2, double &lineY2)
don't break this line or pybindgen will not be able to pick up the above annotation :(
static void Pause (std::string const &message)
Pause function.
Private Types
typedef std::pair< Ptr< Channel >, uint32_t > TxRecordKey
TxRecordKey typedef.
Private Member Functions
void CallbackStopSimulation ()
stop simulation callback function
void DoPause (std::string const &message)
Do pause function.
NetDeviceStatistics & FindNetDeviceStatistics (int node, int interface)
Findnet device statistics function.
bool GetPacketCaptureOptions (uint32_t nodeId, const PacketCaptureOptions **outOptions) const
Get packet capture options function.
void TraceDevQueueDrop (std::string context, Ptr< const Packet > packet)
queue drop trace callback function
void TraceIpv4Drop (std::string context, ns3::Ipv4Header const &hdr, Ptr< const Packet > packet, ns3::Ipv4L3Protocol::DropReason reason, Ptr< Ipv4 > dummy_ipv4, uint32_t interface)
ipv4 drop trace callback function
void TraceNetDevPromiscRxCsma (std::string context, Ptr< const Packet > packet)
CSMA promiscious receive function.
void TraceNetDevRxCommon (std::string const &context, Ptr< const Packet > packet, Mac48Address const &source)
network receive common trace callback function
void TraceNetDevRxCsma (std::string context, Ptr< const Packet > packet)
CSMA receive trace callback function.
void TraceNetDevRxLte (std::string context, Ptr< const Packet > packet, Mac48Address const &source)
LTE receive trace callback function.
void TraceNetDevRxPointToPoint (std::string context, Ptr< const Packet > packet)
Point to point receive trace callback function.
void TraceNetDevRxWifi (std::string context, Ptr< const Packet > packet)
WIFI receive trace callback function.
void TraceNetDevRxWimax (std::string context, Ptr< const Packet > packet, Mac48Address const &source)
WIMax transmit trace callback function.
void TraceNetDevTxCommon (std::string const &context, Ptr< const Packet > packet, Mac48Address const &destination)
network transmit common trace callback function
void TraceNetDevTxCsma (std::string context, Ptr< const Packet > packet)
CSMA transmit trace callback function.
void TraceNetDevTxLte (std::string context, Ptr< const Packet > packet, Mac48Address const &destination)
LTE transmit trace callback function.
void TraceNetDevTxPointToPoint (std::string context, Ptr< const Packet > packet)
Point to point transmit trace calllback function.
void TraceNetDevTxWifi (std::string context, Ptr< const Packet > packet)
WIFI transmit trace callback function.
void TraceNetDevTxWimax (std::string context, Ptr< const Packet > packet, Mac48Address const &destination)
WIMax transmit trace callback function.
Static Private Member Functions
static bool FilterPacket (Ptr< const Packet > packet, const PacketCaptureOptions &options)
Filter packet function.
Private Attributes
std::map< uint32_t, LastPacketsSample > m_lastPackets
last packets
std::set< uint32_t > m_nodesOfInterest
list of node IDs whose transmissions will be monitored
std::map< uint32_t, std::vector< NetDeviceStatistics > > m_nodesStatistics
node statsitics
std::map< uint32_t, PacketCaptureOptions > m_packetCaptureOptions
packet capture options
std::map< Ptr< Node >, uint32_t > m_packetDrops
packt drops
std::map< uint32_t, Time > m_packetsOfInterest
list of packet UIDs that will be monitored
std::vector< std::string > m_pauseMessages
pause message
Time m_runUntil
run until time
bool m_stop
stop?
std::map< TransmissionSampleKey, TransmissionSampleValue > m_transmissionSamples
transmission samples
std::map< TxRecordKey, TxRecordValue > m_txRecords
transmit records
Detailed Description
helper class to be used by the visualizer
Internal:
This class is not meant to be used by simulations. It is only meant to be used by the visualizer tool (PyViz). The only reason it is public is because Python bindings for it are needed, otherwise it should be considered private.
Definition at line 51 of file pyviz.h.
Member Typedef Documentation
PacketDropSampleList
typedef std::vector<PacketDropSample> ns3::PyViz::PacketDropSampleList
PacketDropSampleList typedef.
Definition at line 117 of file pyviz.h.
TransmissionSampleList
typedef std::vector<TransmissionSample> ns3::PyViz::TransmissionSampleList
TransmissionSampleList typedef.
Definition at line 104 of file pyviz.h.
TxRecordKey
typedef std::pair<Ptr<Channel>, uint32_t> ns3::PyViz::TxRecordKey private
TxRecordKey typedef.
Definition at line 236 of file pyviz.h.
Member Enumeration Documentation
PacketCaptureMode
enum ns3::PyViz::PacketCaptureMode
PacketCaptureMode enumeration.
Enumerator
PACKET_CAPTURE_DISABLED
PACKET_CAPTURE_FILTER_HEADERS_OR
PACKET_CAPTURE_FILTER_HEADERS_AND
Definition at line 190 of file pyviz.h.
Constructor & Destructor Documentation
PyViz()
ns3::PyViz::PyViz ()
Definition at line 131 of file pyviz.cc.
References ns3::Config::ConnectFailSafe(), ns3::g_visualizer, ns3::MakeCallback(), NS_ASSERT, NS_LOG_FUNCTION_NOARGS, TraceDevQueueDrop(), TraceIpv4Drop(), TraceNetDevPromiscRxCsma(), TraceNetDevRxCsma(), TraceNetDevRxLte(), TraceNetDevRxPointToPoint(), TraceNetDevRxWifi(), TraceNetDevRxWimax(), TraceNetDevTxCsma(), TraceNetDevTxLte(), TraceNetDevTxPointToPoint(), TraceNetDevTxWifi(), and TraceNetDevTxWimax().
~PyViz()
ns3::PyViz::~PyViz ()
Definition at line 245 of file pyviz.cc.
References ns3::g_visualizer, NS_ASSERT, and NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
CallbackStopSimulation()
void ns3::PyViz::CallbackStopSimulation () private
stop simulation callback function
Definition at line 277 of file pyviz.cc.
References m_runUntil, m_stop, ns3::Simulator::Now(), NS_LOG_FUNCTION_NOARGS, ns3::Seconds(), and ns3::Simulator::Stop().
Referenced by SimulatorRunUntil().
DoPause()
void ns3::PyViz::DoPause (std::string const & message) private
Do pause function.
Parameters
message the pause message
Definition at line 253 of file pyviz.cc.
References ns3::g_visualizer, m_pauseMessages, m_stop, ns3::Simulator::Now(), NS_LOG_LOGIC, and ns3::Time::S.
Referenced by Pause().
FilterPacket()
bool ns3::PyViz::FilterPacket (Ptr< const Packet > packet, const PacketCaptureOptions & options) static private
Filter packet function.
Parameters
packet the packet
options the capture options
Returns
true if successful
Definition at line 419 of file pyviz.cc.
References ns3::PacketMetadata::ItemIterator::HasNext(), ns3::PyViz::PacketCaptureOptions::headers, ns3::PyViz::PacketCaptureOptions::mode, ns3::PacketMetadata::ItemIterator::Next(), NS_FATAL_ERROR, PACKET_CAPTURE_DISABLED, PACKET_CAPTURE_FILTER_HEADERS_AND, PACKET_CAPTURE_FILTER_HEADERS_OR, and ns3::PacketMetadata::Item::tid.
Referenced by TraceDevQueueDrop(), TraceNetDevRxCommon(), and TraceNetDevTxCommon().
FindNetDeviceStatistics()
PyViz::NetDeviceStatistics & ns3::PyViz::FindNetDeviceStatistics (int node, int interface) inline private
Findnet device statistics function.
Parameters
node the node
interface the interface number
Returns
the device statistics
Definition at line 388 of file pyviz.cc.
References ns3::NodeList::GetNode(), and m_nodesStatistics.
Referenced by TraceNetDevRxCommon(), and TraceNetDevTxCommon().
GetLastPackets()
PyViz::LastPacketsSample ns3::PyViz::GetLastPackets (uint32_t nodeId) const
Get last packets function.
Parameters
nodeId the node ID
Returns
the last packets
Definition at line 926 of file pyviz.cc.
References m_lastPackets, and NS_LOG_DEBUG.
GetNodesStatistics()
std::vector< PyViz::NodeStatistics > ns3::PyViz::GetNodesStatistics () const
Get node statistics.
Returns
the node statistics
Definition at line 912 of file pyviz.cc.
References m_nodesStatistics.
GetPacketCaptureOptions()
bool ns3::PyViz::GetPacketCaptureOptions (uint32_t nodeId, const PacketCaptureOptions ** outOptions) const private
Get packet capture options function.
Parameters
nodeId the node ID
outOptions the packet capture options
Returns
true if successful
Definition at line 405 of file pyviz.cc.
References m_packetCaptureOptions.
Referenced by TraceDevQueueDrop(), TraceNetDevRxCommon(), and TraceNetDevTxCommon().
GetPacketDropSamples()
PyViz::PacketDropSampleList ns3::PyViz::GetPacketDropSamples () const
Get packet drop samples.
Returns
the packet drop sample list
Definition at line 885 of file pyviz.cc.
References ns3::PyViz::PacketDropSample::bytes, ns3::Node::GetId(), list, m_packetDrops, NS_LOG_DEBUG, and ns3::PyViz::PacketDropSample::transmitter.
GetPauseMessages()
std::vector< std::string > ns3::PyViz::GetPauseMessages () const
Get pause message function.
Returns
the pause message
Definition at line 268 of file pyviz.cc.
References ns3::g_visualizer, m_pauseMessages, ns3::Simulator::Now(), NS_LOG_LOGIC, and ns3::Time::S.
GetTransmissionSamples()
PyViz::TransmissionSampleList ns3::PyViz::GetTransmissionSamples () const
Get transmission samples.
Returns
the transmission sample list
Definition at line 862 of file pyviz.cc.
References ns3::PyViz::TransmissionSample::bytes, ns3::PyViz::TransmissionSample::channel, ns3::Node::GetId(), list, m_transmissionSamples, NS_LOG_DEBUG, ns3::PyViz::TransmissionSample::receiver, and ns3::PyViz::TransmissionSample::transmitter.
LineClipping()
void ns3::PyViz::LineClipping (double boundsX1, double boundsY1, double boundsX2, double boundsY2, double & lineX1, double & lineY1, double & lineX2, double & lineY2) static
don't break this line or pybindgen will not be able to pick up the above annotation :(
Definition at line 1475 of file pyviz.cc.
Pause()
void ns3::PyViz::Pause (std::string const & message) static
Pause function.
Parameters
message the pause message
Definition at line 261 of file pyviz.cc.
References DoPause(), ns3::g_visualizer, and NS_ASSERT.
RegisterCsmaLikeDevice()
void ns3::PyViz::RegisterCsmaLikeDevice (std::string const & deviceTypeName)
Register CSMA like device function.
Parameters
deviceTypeName the device type name
Definition at line 184 of file pyviz.cc.
References ns3::Config::Connect(), ns3::TypeId::LookupByName(), ns3::MakeCallback(), TraceNetDevPromiscRxCsma(), TraceNetDevRxCsma(), and TraceNetDevTxCsma().
RegisterDropTracePath()
void ns3::PyViz::RegisterDropTracePath (std::string const & tracePath)
Register drop trace path function.
Parameters
tracePath the path to trace
Definition at line 240 of file pyviz.cc.
References ns3::Config::Connect(), ns3::MakeCallback(), and TraceDevQueueDrop().
RegisterPointToPointLikeDevice()
void ns3::PyViz::RegisterPointToPointLikeDevice (std::string const & deviceTypeName)
Register point to point like device function.
Parameters
deviceTypeName the device type name
Definition at line 216 of file pyviz.cc.
References ns3::Config::Connect(), ns3::TypeId::LookupByName(), ns3::MakeCallback(), TraceNetDevRxPointToPoint(), and TraceNetDevTxPointToPoint().
RegisterWifiLikeDevice()
void ns3::PyViz::RegisterWifiLikeDevice (std::string const & deviceTypeName)
Register WIFI like device function.
Parameters
deviceTypeName the device type name
Definition at line 202 of file pyviz.cc.
References ns3::Config::Connect(), ns3::TypeId::LookupByName(), ns3::MakeCallback(), TraceNetDevRxWifi(), and TraceNetDevTxWifi().
SetNodesOfInterest()
void ns3::PyViz::SetNodesOfInterest (std::set< uint32_t > nodes)
Set nodes of interest function.
Parameters
nodes the collection of nodes
Definition at line 906 of file pyviz.cc.
References m_nodesOfInterest, and first::nodes.
SetPacketCaptureOptions()
void ns3::PyViz::SetPacketCaptureOptions (uint32_t nodeId, PacketCaptureOptions options)
Set packet capture options function.
Parameters
nodeId the node ID
options the capture options
Definition at line 230 of file pyviz.cc.
References ns3::PyViz::PacketCaptureOptions::headers, m_packetCaptureOptions, ns3::PyViz::PacketCaptureOptions::mode, NS_LOG_DEBUG, and ns3::PyViz::PacketCaptureOptions::numLastPackets.
SimulatorRunUntil()
void ns3::PyViz::SimulatorRunUntil (Time time)
Run simulation until a given (simulated, absolute) time is reached.
Parameters
time the run time
Definition at line 288 of file pyviz.cc.
References CallbackStopSimulation(), ns3::Simulator::GetImplementation(), m_packetDrops, m_packetsOfInterest, m_pauseMessages, m_runUntil, m_stop, m_transmissionSamples, m_txRecords, ns3::Simulator::NO_CONTEXT, ns3::Simulator::Now(), NS_LOG_LOGIC, ns3::Simulator::ScheduleWithContext(), and ns3::Seconds().
TraceDevQueueDrop()
void ns3::PyViz::TraceDevQueueDrop (std::string context, Ptr< const Packet > packet) private
queue drop trace callback function
Parameters
context the context
packet the packet
Definition at line 470 of file pyviz.cc.
References ns3::PyViz::PacketSample::device, FilterPacket(), ns3::NodeList::GetNode(), GetPacketCaptureOptions(), ns3::PyViz::LastPacketsSample::lastDroppedPackets, m_lastPackets, m_nodesOfInterest, m_packetDrops, m_packetsOfInterest, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::PyViz::PacketCaptureOptions::numLastPackets, ns3::PyViz::PacketSample::packet, PathSplit(), and ns3::PyViz::PacketSample::time.
Referenced by PyViz(), RegisterDropTracePath(), and TraceIpv4Drop().
TraceIpv4Drop()
void ns3::PyViz::TraceIpv4Drop (std::string context, ns3::Ipv4Header const & hdr, Ptr< const Packet > packet, ns3::Ipv4L3Protocol::DropReason reason, Ptr< Ipv4 > dummy_ipv4, uint32_t interface) private
ipv4 drop trace callback function
Parameters
context the context
hdr the header
packet the packet
reason the drop reason
dummy_ipv4
interface the interface
Definition at line 516 of file pyviz.cc.
References ns3::Packet::AddHeader(), and TraceDevQueueDrop().
Referenced by PyViz().
TraceNetDevPromiscRxCsma()
void ns3::PyViz::TraceNetDevPromiscRxCsma (std::string context, Ptr< const Packet > packet) private
CSMA promiscious receive function.
Parameters
context the context
packet the packet
Definition at line 816 of file pyviz.cc.
References ns3::EthernetHeader::GetDestination(), NS_ABORT_IF, ns3::NetDevice::PACKET_OTHERHOST, and TraceNetDevRxCommon().
Referenced by PyViz(), and RegisterCsmaLikeDevice().
TraceNetDevRxCommon()
void ns3::PyViz::TraceNetDevRxCommon (std::string const & context, Ptr< const Packet > packet, Mac48Address const & source) private
network receive common trace callback function
Parameters
context the context
packet the packet
source the source MAC address
Definition at line 649 of file pyviz.cc.
References ns3::PyViz::TransmissionSampleValue::bytes, third::channel, ns3::PyViz::PacketSample::device, FilterPacket(), FindNetDeviceStatistics(), ns3::PyViz::RxPacketSample::from, ns3::Node::GetDevice(), ns3::Node::GetId(), ns3::NodeList::GetNode(), GetPacketCaptureOptions(), ns3::PyViz::LastPacketsSample::lastReceivedPackets, ns3::LOG_DEBUG, m_lastPackets, ns3::PyVizPacketTag::m_packetId, m_packetsOfInterest, m_transmissionSamples, m_txRecords, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_WARN, ns3::PyViz::PacketCaptureOptions::numLastPackets, ns3::PyViz::PacketSample::packet, PathSplit(), ns3::PyViz::NetDeviceStatistics::receivedBytes, ns3::PyViz::NetDeviceStatistics::receivedPackets, ns3::PyViz::TransmissionSampleKey::receiver, ns3::PyViz::TxRecordValue::srcNode, ns3::PyViz::PacketSample::time, and ns3::PyViz::TransmissionSampleKey::transmitter.
Referenced by TraceNetDevPromiscRxCsma(), TraceNetDevRxCsma(), TraceNetDevRxLte(), TraceNetDevRxPointToPoint(), TraceNetDevRxWifi(), and TraceNetDevRxWimax().
TraceNetDevRxCsma()
void ns3::PyViz::TraceNetDevRxCsma (std::string context, Ptr< const Packet > packet) private
CSMA receive trace callback function.
Parameters
context the context
packet the packet
Definition at line 802 of file pyviz.cc.
References ns3::EthernetHeader::GetSource(), NS_ABORT_IF, and TraceNetDevRxCommon().
Referenced by PyViz(), and RegisterCsmaLikeDevice().
TraceNetDevRxLte()
void ns3::PyViz::TraceNetDevRxLte (std::string context, Ptr< const Packet > packet, Mac48Address const & source) private
LTE receive trace callback function.
Parameters
context the context
packet the packet
source the MAC address of the source
Definition at line 853 of file pyviz.cc.
References NS_LOG_FUNCTION, and TraceNetDevRxCommon().
Referenced by PyViz().
TraceNetDevRxPointToPoint()
void ns3::PyViz::TraceNetDevRxPointToPoint (std::string context, Ptr< const Packet > packet) private
Point to point receive trace callback function.
Parameters
context the context
packet the packet
Definition at line 810 of file pyviz.cc.
References TraceNetDevRxCommon().
Referenced by PyViz(), and RegisterPointToPointLikeDevice().
TraceNetDevRxWifi()
void ns3::PyViz::TraceNetDevRxWifi (std::string context, Ptr< const Packet > packet) private
WIFI receive trace callback function.
Parameters
context the context
packet the packet
Definition at line 763 of file pyviz.cc.
References ns3::WifiMacHeader::GetAddr2(), ns3::WifiMacHeader::GetAddr3(), ns3::WifiMacHeader::GetAddr4(), ns3::WifiMacHeader::IsFromDs(), ns3::WifiMacHeader::IsToDs(), NS_ABORT_IF, NS_LOG_FUNCTION, and TraceNetDevRxCommon().
Referenced by PyViz(), and RegisterWifiLikeDevice().
TraceNetDevRxWimax()
void ns3::PyViz::TraceNetDevRxWimax (std::string context, Ptr< const Packet > packet, Mac48Address const & source) private
WIMax transmit trace callback function.
Parameters
context the context
packet the packet
source the source MAC address
Definition at line 839 of file pyviz.cc.
References NS_LOG_FUNCTION, and TraceNetDevRxCommon().
Referenced by PyViz().
TraceNetDevTxCommon()
void ns3::PyViz::TraceNetDevTxCommon (std::string const & context, Ptr< const Packet > packet, Mac48Address const & destination) private
network transmit common trace callback function
Parameters
context the context
packet the packet
destination the destination MAC address
Definition at line 528 of file pyviz.cc.
References ns3::PyViz::PacketSample::device, FilterPacket(), FindNetDeviceStatistics(), ns3::Node::GetDevice(), ns3::NodeList::GetNode(), GetPacketCaptureOptions(), ns3::PyViz::TxRecordValue::isBroadcast, ns3::PyViz::LastPacketsSample::lastTransmittedPackets, m_lastPackets, m_nodesOfInterest, ns3::PyVizPacketTag::m_packetId, m_packetsOfInterest, m_txRecords, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::PyViz::PacketCaptureOptions::numLastPackets, ns3::PyViz::PacketSample::packet, PathSplit(), ns3::PyViz::PacketSample::time, ns3::PyViz::TxPacketSample::to, ns3::PyViz::NetDeviceStatistics::transmittedBytes, and ns3::PyViz::NetDeviceStatistics::transmittedPackets.
Referenced by TraceNetDevTxCsma(), TraceNetDevTxLte(), TraceNetDevTxPointToPoint(), TraceNetDevTxWifi(), and TraceNetDevTxWimax().
TraceNetDevTxCsma()
void ns3::PyViz::TraceNetDevTxCsma (std::string context, Ptr< const Packet > packet) private
CSMA transmit trace callback function.
Parameters
context the context
packet the packet
Definition at line 630 of file pyviz.cc.
References ns3::EthernetHeader::GetDestination(), NS_ABORT_IF, and TraceNetDevTxCommon().
Referenced by PyViz(), and RegisterCsmaLikeDevice().
TraceNetDevTxLte()
void ns3::PyViz::TraceNetDevTxLte (std::string context, Ptr< const Packet > packet, Mac48Address const & destination) private
LTE transmit trace callback function.
Parameters
context the context
packet the packet
destination the destination MAC address
Definition at line 846 of file pyviz.cc.
References NS_LOG_FUNCTION, and TraceNetDevTxCommon().
Referenced by PyViz().
TraceNetDevTxPointToPoint()
void ns3::PyViz::TraceNetDevTxPointToPoint (std::string context, Ptr< const Packet > packet) private
Point to point transmit trace calllback function.
Parameters
context the context
packet the packet
Definition at line 638 of file pyviz.cc.
References TraceNetDevTxCommon().
Referenced by PyViz(), and RegisterPointToPointLikeDevice().
TraceNetDevTxWifi()
void ns3::PyViz::TraceNetDevTxWifi (std::string context, Ptr< const Packet > packet) private
WIFI transmit trace callback function.
Parameters
context the context
packet the packet
Definition at line 594 of file pyviz.cc.
References ns3::WifiMacHeader::GetAddr1(), ns3::WifiMacHeader::GetAddr3(), ns3::WifiMacHeader::IsFromDs(), ns3::WifiMacHeader::IsToDs(), NS_ABORT_IF, NS_LOG_FUNCTION, and TraceNetDevTxCommon().
Referenced by PyViz(), and RegisterWifiLikeDevice().
TraceNetDevTxWimax()
void ns3::PyViz::TraceNetDevTxWimax (std::string context, Ptr< const Packet > packet, Mac48Address const & destination) private
WIMax transmit trace callback function.
Parameters
context the context
packet the packet
destination the destination MAC address
Definition at line 832 of file pyviz.cc.
References NS_LOG_FUNCTION, and TraceNetDevTxCommon().
Referenced by PyViz().
Member Data Documentation
m_lastPackets
std::map<uint32_t, LastPacketsSample> ns3::PyViz::m_lastPackets private
last packets
Definition at line 282 of file pyviz.h.
Referenced by GetLastPackets(), TraceDevQueueDrop(), TraceNetDevRxCommon(), and TraceNetDevTxCommon().
m_nodesOfInterest
std::set<uint32_t> ns3::PyViz::m_nodesOfInterest private
list of node IDs whose transmissions will be monitored
Definition at line 280 of file pyviz.h.
Referenced by SetNodesOfInterest(), TraceDevQueueDrop(), and TraceNetDevTxCommon().
m_nodesStatistics
std::map<uint32_t, std::vector<NetDeviceStatistics> > ns3::PyViz::m_nodesStatistics private
node statsitics
Definition at line 283 of file pyviz.h.
Referenced by FindNetDeviceStatistics(), and GetNodesStatistics().
m_packetCaptureOptions
std::map<uint32_t, PacketCaptureOptions> ns3::PyViz::m_packetCaptureOptions private
packet capture options
Definition at line 275 of file pyviz.h.
Referenced by GetPacketCaptureOptions(), and SetPacketCaptureOptions().
m_packetDrops
std::map<Ptr<Node>, uint32_t> ns3::PyViz::m_packetDrops private
packt drops
Definition at line 279 of file pyviz.h.
Referenced by GetPacketDropSamples(), SimulatorRunUntil(), and TraceDevQueueDrop().
m_packetsOfInterest
std::map<uint32_t, Time> ns3::PyViz::m_packetsOfInterest private
list of packet UIDs that will be monitored
Definition at line 281 of file pyviz.h.
Referenced by SimulatorRunUntil(), TraceDevQueueDrop(), TraceNetDevRxCommon(), and TraceNetDevTxCommon().
m_pauseMessages
std::vector<std::string> ns3::PyViz::m_pauseMessages private
pause message
Definition at line 276 of file pyviz.h.
Referenced by DoPause(), GetPauseMessages(), and SimulatorRunUntil().
m_runUntil
Time ns3::PyViz::m_runUntil private
run until time
Definition at line 409 of file pyviz.h.
Referenced by CallbackStopSimulation(), and SimulatorRunUntil().
m_stop
bool ns3::PyViz::m_stop private
stop?
Definition at line 408 of file pyviz.h.
Referenced by CallbackStopSimulation(), DoPause(), and SimulatorRunUntil().
m_transmissionSamples
std::map<TransmissionSampleKey, TransmissionSampleValue> ns3::PyViz::m_transmissionSamples private
transmission samples
Definition at line 278 of file pyviz.h.
Referenced by GetTransmissionSamples(), SimulatorRunUntil(), and TraceNetDevRxCommon().
m_txRecords
std::map<TxRecordKey, TxRecordValue> ns3::PyViz::m_txRecords private
transmit records
Definition at line 277 of file pyviz.h.
Referenced by SimulatorRunUntil(), TraceNetDevRxCommon(), and TraceNetDevTxCommon().
The documentation for this class was generated from the following files:
src/visualizer/model/pyviz.h
src/visualizer/model/pyviz.cc