ns-3: ns3::WaveNetDevice Class Reference
ns3::WaveNetDevice Class Reference
WAVE module
This class holds together multiple, ns3::WifiPhy, and ns3::OcbWifiMac (including ns3::WifiRemoteStationManager).
#include "wave-net-device.h"
Public Types
typedef Callback< bool, Ptr< const Packet >, const Address &, uint32_t, uint32_t > WaveVsaCallback
Public Types inherited from ns3::NetDevice
typedef void(* LinkChangeTracedCallback) (void)
TracedCallback signature for link changed event.
enum PacketType {
PACKET_HOST = 1 , NS3_PACKET_HOST = PACKET_HOST , PACKET_BROADCAST , NS3_PACKET_BROADCAST = PACKET_BROADCAST ,
PACKET_MULTICAST , NS3_PACKET_MULTICAST = PACKET_MULTICAST , PACKET_OTHERHOST , NS3_PACKET_OTHERHOST = PACKET_OTHERHOST
}
Packet types are used as they are in Linux.
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address &, const Address &, enum PacketType > PromiscReceiveCallback
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address & > ReceiveCallback
Public Member Functions
WaveNetDevice (void)
virtual ~WaveNetDevice (void)
virtual void AddLinkChangeCallback (Callback< void > callback)
void AddMac (uint32_t channelNumber, Ptr< OcbWifiMac > mac)
void AddPhy (Ptr< WifiPhy > phy)
void CancelTx (uint32_t channelNumber, enum AcIndex ac)
void ChangeAddress (Address newAddress)
bool DeleteTxProfile (uint32_t channelNumber)
virtual Address GetAddress (void) const
virtual Address GetBroadcast (void) const
virtual Ptr< Channel > GetChannel (void) const
Ptr< ChannelCoordinator > GetChannelCoordinator (void) const
Ptr< ChannelManager > GetChannelManager (void) const
Ptr< ChannelScheduler > GetChannelScheduler (void) const
virtual uint32_t GetIfIndex (void) const
Ptr< OcbWifiMac > GetMac (uint32_t channelNumber) const
std::map< uint32_t, Ptr< OcbWifiMac > > GetMacs (void) const
virtual uint16_t GetMtu (void) const
virtual Address GetMulticast (Ipv4Address multicastGroup) const
Make and return a MAC multicast address using the provided multicast group.
virtual Address GetMulticast (Ipv6Address addr) const
Get the MAC multicast address corresponding to the IPv6 address provided.
virtual Ptr< Node > GetNode (void) const
Ptr< WifiPhy > GetPhy (uint32_t index) const
std::vector< Ptr< WifiPhy > > GetPhys (void) const
Ptr< VsaManager > GetVsaManager (void) const
virtual bool IsBridge (void) const
Return true if the net device is acting as a bridge.
virtual bool IsBroadcast (void) const
virtual bool IsLinkUp (void) const
virtual bool IsMulticast (void) const
virtual bool IsPointToPoint (void) const
Return true if the net device is on a point-to-point link.
virtual bool NeedsArp (void) const
bool RegisterTxProfile (const TxProfile &txprofile)
virtual bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)
virtual bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
bool SendX (Ptr< Packet > packet, const Address &dest, uint32_t protocol, const TxInfo &txInfo)
virtual void SetAddress (Address address)
Set the address of this interface.
void SetChannelCoordinator (Ptr< ChannelCoordinator > channelCoordinator)
void SetChannelManager (Ptr< ChannelManager > channelManager)
void SetChannelScheduler (Ptr< ChannelScheduler > channelScheduler)
virtual void SetIfIndex (const uint32_t index)
virtual bool SetMtu (const uint16_t mtu)
virtual void SetNode (Ptr< Node > node)
virtual void SetPromiscReceiveCallback (PromiscReceiveCallback cb)
virtual void SetReceiveCallback (NetDevice::ReceiveCallback cb)
void SetVsaManager (Ptr< VsaManager > vsaManager)
void SetWaveVsaCallback (WaveVsaCallback vsaCallback)
bool StartSch (const SchInfo &schInfo)
bool StartVsa (const VsaInfo &vsaInfo)
bool StopSch (uint32_t channelNumber)
bool StopVsa (uint32_t channelNumber)
virtual bool SupportsSendFrom (void) const
Public Member Functions inherited from ns3::WifiNetDevice
WifiNetDevice ()
virtual ~WifiNetDevice ()
void AddLinkChangeCallback (Callback< void > callback)
Address GetAddress (void) const
Address GetBroadcast (void) const
Ptr< Channel > GetChannel (void) const
Ptr< HeConfiguration > GetHeConfiguration (void) const
Ptr< HtConfiguration > GetHtConfiguration (void) const
uint32_t GetIfIndex (void) const
Ptr< WifiMac > GetMac (void) const
uint16_t GetMtu (void) const
Address GetMulticast (Ipv4Address multicastGroup) const
Make and return a MAC multicast address using the provided multicast group.
Address GetMulticast (Ipv6Address addr) const
Get the MAC multicast address corresponding to the IPv6 address provided.
Ptr< Node > GetNode (void) const
Ptr< WifiPhy > GetPhy (void) const
Ptr< WifiRemoteStationManager > GetRemoteStationManager (void) const
Ptr< VhtConfiguration > GetVhtConfiguration (void) const
bool IsBridge (void) const
Return true if the net device is acting as a bridge.
bool IsBroadcast (void) const
bool IsLinkUp (void) const
bool IsMulticast (void) const
bool IsPointToPoint (void) const
Return true if the net device is on a point-to-point link.
bool NeedsArp (void) const
bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)
bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
void SetAddress (Address address)
Set the address of this interface.
void SetHeConfiguration (Ptr< HeConfiguration > heConfiguration)
void SetHtConfiguration (Ptr< HtConfiguration > htConfiguration)
void SetIfIndex (const uint32_t index)
void SetMac (const Ptr< WifiMac > mac)
bool SetMtu (const uint16_t mtu)
void SetNode (const Ptr< Node > node)
void SetPhy (const Ptr< WifiPhy > phy)
void SetPromiscReceiveCallback (PromiscReceiveCallback cb)
void SetReceiveCallback (NetDevice::ReceiveCallback cb)
void SetRemoteStationManager (const Ptr< WifiRemoteStationManager > manager)
void SetVhtConfiguration (Ptr< VhtConfiguration > vhtConfiguration)
bool SupportsSendFrom (void) const
Public Member Functions inherited from ns3::NetDevice
virtual ~NetDevice ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::WifiNetDevice
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::NetDevice
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef std::map< uint32_t, Ptr< OcbWifiMac > > MacEntities
MacEntities typedef.
typedef std::map< uint32_t, Ptr< OcbWifiMac > >::const_iterator MacEntitiesI
MacEntities iterator typedef.
typedef std::vector< Ptr< WifiPhy > > PhyEntities
PhyEntities typedef.
typedef std::vector< Ptr< WifiPhy > >::const_iterator PhyEntitiesI
PhyEntities iterator typedef.
Private Member Functions
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
void ForwardUp (Ptr< const Packet > packet, Mac48Address from, Mac48Address to)
Receive a packet from the lower layer and pass the packet up the stack.
bool IsAvailableChannel (uint32_t channelNumber) const
Private Attributes
TracedCallback< Address, Address > m_addressChange
Ptr< ChannelCoordinator > m_channelCoordinator
the channel coordinator
Ptr< ChannelManager > m_channelManager
the channel manager
Ptr< ChannelScheduler > m_channelScheduler
the channel scheduler
NetDevice::ReceiveCallback m_forwardUp
forward up receive callback
uint32_t m_ifIndex
IF index.
MacEntities m_macEntities
MAC entities.
uint16_t m_mtu
MTU.
Ptr< Node > m_node
the node
PhyEntities m_phyEntities
Phy entities.
NetDevice::PromiscReceiveCallback m_promiscRx
promiscious receive callback
TxProfile * m_txProfile
transmit profile
Ptr< VsaManager > m_vsaManager
the VSA manager
Static Private Attributes
static const uint16_t IPv4_PROT_NUMBER = 0x0800
IP v4 Protocol number.
static const uint16_t IPv6_PROT_NUMBER = 0x86DD
IP v6 Protocol number.
static const uint16_t MAX_MSDU_SIZE = 2304
This value conforms to the 802.11 specification.
Additional Inherited Members
Protected Member Functions inherited from ns3::WifiNetDevice
void DoDispose (void)
Destructor implementation.
void DoInitialize (void)
Initialize() implementation.
void ForwardUp (Ptr< const Packet > packet, Mac48Address from, Mac48Address to)
Receive a packet from the lower layer and pass the packet up the stack.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class holds together multiple, ns3::WifiPhy, and ns3::OcbWifiMac (including ns3::WifiRemoteStationManager).
Besides that, to support multiple channel operation this class also holds ns3::ChannelScheduler, ns3::ChannelManager, ns3::ChannelCoordinator and ns3::VsaManager.
these primitives specified in the standard will not be implemented because of limited use in simulation: void StartTimingAdvertisement (); void StopTimingAdvertisement (); UtcTime GetUtcTime (); void SetUtcTime ();
Config Paths
ns3::WaveNetDevice is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice"
Attributes
Mtu: The MAC-level Maximum Transmission Unit
Set with class: ns3::UintegerValue
Underlying type: uint16_t 1:2296
Initial value: 2296
Flags: construct write read
Channel: The channel attached to this device
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::Channel>
Flags: read
PhyEntities: The PHY entities attached to this device.
Set with class: ns3::ObjectPtrContainerValue
Underlying type: ns3::Ptr< ns3::WifiPhy>
Flags: read
MacEntities: The MAC layer attached to this device.
Set with class: ns3::ObjectPtrContainerValue
Underlying type: ns3::Ptr< ns3::OcbWifiMac>
Flags: read
ChannelScheduler: The channel scheduler attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::ChannelScheduler>
Initial value: 0x0
Flags: construct write read
ChannelManager: The channel manager attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::ChannelManager>
Initial value: 0x0
Flags: construct write read
ChannelCoordinator: The channel coordinator attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::ChannelCoordinator>
Initial value: 0x0
Flags: construct write read
VsaManager: The VSA manager attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::VsaManager>
Initial value: 0x0
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 336 bytes (on a 64-bit architecture).
Definition at line 160 of file wave-net-device.h.
Member Typedef Documentation
MacEntities
typedef std::map<uint32_t, Ptr<OcbWifiMac> > ns3::WaveNetDevice::MacEntities private
MacEntities typedef.
Definition at line 382 of file wave-net-device.h.
MacEntitiesI
typedef std::map<uint32_t, Ptr<OcbWifiMac> >::const_iterator ns3::WaveNetDevice::MacEntitiesI private
MacEntities iterator typedef.
Definition at line 384 of file wave-net-device.h.
PhyEntities
typedef std::vector<Ptr<WifiPhy> > ns3::WaveNetDevice::PhyEntities private
PhyEntities typedef.
Definition at line 387 of file wave-net-device.h.
PhyEntitiesI
typedef std::vector<Ptr<WifiPhy> >::const_iterator ns3::WaveNetDevice::PhyEntitiesI private
PhyEntities iterator typedef.
Definition at line 389 of file wave-net-device.h.
WaveVsaCallback
typedef Callback<bool, Ptr<const Packet>,const Address &, uint32_t, uint32_t> ns3::WaveNetDevice::WaveVsaCallback
Parameters
packet the packet is Vendor Specific Action frame.
address the address of the MAC from which the management frame was received.
managementID identify the originator of the data. Values are specified in IEEE P1609.0 with range 0-15.
channelNumber the channel on which the frame was received.
Returns
true if the callback could handle the packet successfully, false otherwise.
Definition at line 263 of file wave-net-device.h.
Constructor & Destructor Documentation
WaveNetDevice()
ns3::WaveNetDevice::WaveNetDevice (void)
Definition at line 86 of file wave-net-device.cc.
References NS_LOG_FUNCTION.
~WaveNetDevice()
ns3::WaveNetDevice::~WaveNetDevice (void) virtual
Definition at line 92 of file wave-net-device.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddLinkChangeCallback()
void ns3::WaveNetDevice::AddLinkChangeCallback (Callback< void > callback) virtual
Parameters
callback the callback to invoke
Add a callback invoked whenever the link status changes to UP. This callback is typically used by the IP/ARP layer to flush the ARP cache and by IPv6 stack to flush NDISC cache whenever the link goes up.
Implements ns3::NetDevice.
Definition at line 558 of file wave-net-device.cc.
References NS_LOG_WARN.
AddMac()
void ns3::WaveNetDevice::AddMac (uint32_t channelNumber, Ptr< OcbWifiMac > mac)
Parameters
channelNumber the specific channel
mac add a new available MAC entity for specific channel
Definition at line 176 of file wave-net-device.cc.
References ns3::ChannelManager::IsWaveChannel(), m_macEntities, third::mac, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
Referenced by ns3::WaveHelper::Install().
AddPhy()
void ns3::WaveNetDevice::AddPhy (Ptr< WifiPhy > phy)
Parameters
phy add a new available PHY entity
Definition at line 209 of file wave-net-device.cc.
References m_phyEntities, NS_FATAL_ERROR, NS_LOG_FUNCTION, and third::phy.
Referenced by ns3::WaveHelper::Install().
CancelTx()
void ns3::WaveNetDevice::CancelTx (uint32_t channelNumber, enum AcIndex ac)
Parameters
channelNumber the specific channel number
ac the specific access category
Cancel all transmissions with the particular category and channel number.
Definition at line 454 of file wave-net-device.cc.
References ns3::WifiNetDevice::GetMac(), IsAvailableChannel(), and third::mac.
ChangeAddress()
void ns3::WaveNetDevice::ChangeAddress (Address newAddress)
Parameters
newAddress an immediate MAC-layer address change is required
This method is similar with SetAddress method, but SetAddress is suggested for initializing a device, while this method is preferred for changing address and a addressChange TracedCallback will be called.
Definition at line 435 of file wave-net-device.cc.
References GetAddress(), m_addressChange, m_macEntities, NS_LOG_FUNCTION, and SetAddress().
DeleteTxProfile()
bool ns3::WaveNetDevice::DeleteTxProfile (uint32_t channelNumber)
Parameters
channelNumber the specific channel number delete a registered transmitter profile in the MLME after the associated IP-based data transfer is complete
Returns
whether the tx profile is unregistered successfully
Definition at line 349 of file wave-net-device.cc.
References ns3::TxProfile::channelNumber, IsAvailableChannel(), m_txProfile, and NS_LOG_FUNCTION.
Referenced by WaveNetDeviceExample::SendIpExample().
DoDispose()
void ns3::WaveNetDevice::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 98 of file wave-net-device.cc.
References ns3::Object::Dispose(), ns3::Object::DoDispose(), m_channelCoordinator, m_channelManager, m_channelScheduler, m_macEntities, m_phyEntities, m_txProfile, m_vsaManager, third::mac, NS_LOG_FUNCTION, and third::phy.
DoInitialize()
void ns3::WaveNetDevice::DoInitialize (void) private virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 133 of file wave-net-device.cc.
References ns3::Object::DoInitialize(), ForwardUp(), ns3::Object::Initialize(), m_channelCoordinator, m_channelManager, m_channelScheduler, m_macEntities, m_phyEntities, m_vsaManager, third::mac, ns3::MakeCallback(), NS_FATAL_ERROR, NS_LOG_FUNCTION, third::phy, and ns3::WifiRemoteStationManager::SetupPhy().
ForwardUp()
void ns3::WaveNetDevice::ForwardUp (Ptr< const Packet > packet, Mac48Address from, Mac48Address to) private
Receive a packet from the lower layer and pass the packet up the stack.
Parameters
packet
from
to
Definition at line 679 of file wave-net-device.cc.
References CCH, GetAddress(), ns3::WifiNetDevice::GetMac(), ns3::LlcSnapHeader::GetType(), ns3::Mac48Address::IsBroadcast(), ns3::Mac48Address::IsGroup(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_forwardUp, m_promiscRx, third::mac, NS_LOG_FUNCTION, ns3::NetDevice::PACKET_BROADCAST, ns3::NetDevice::PACKET_HOST, ns3::NetDevice::PACKET_MULTICAST, ns3::NetDevice::PACKET_OTHERHOST, and ns3::Packet::RemoveHeader().
Referenced by DoInitialize().
GetAddress()
Address ns3::WaveNetDevice::GetAddress (void) const virtual
Returns
the current Address of this interface.
Implements ns3::NetDevice.
Definition at line 530 of file wave-net-device.cc.
References CCH, and ns3::WifiNetDevice::GetMac().
Referenced by ChangeAddress(), ForwardUp(), WaveNetDeviceExample::SendIpPacket(), and AnnexC_TestCase::SendPacket().
GetBroadcast()
Address ns3::WaveNetDevice::GetBroadcast (void) const virtual
Returns
the broadcast address supported by this netdevice.
Calling this method is invalid if IsBroadcast returns not true.
Implements ns3::NetDevice.
Definition at line 568 of file wave-net-device.cc.
References ns3::Mac48Address::GetBroadcast().
GetChannel()
Ptr< Channel > ns3::WaveNetDevice::GetChannel (void) const virtual
Returns
the channel this NetDevice is connected to. The value returned can be zero if the NetDevice is not yet connected to any channel or if the underlying NetDevice has no concept of a channel. i.e., callers must check for zero and be ready to handle it.
Implements ns3::NetDevice.
Definition at line 516 of file wave-net-device.cc.
References ns3::WifiPhy::GetChannel(), ns3::WifiNetDevice::GetPhy(), m_phyEntities, and NS_ASSERT.
Referenced by GetTypeId().
GetChannelCoordinator()
Ptr< ChannelCoordinator > ns3::WaveNetDevice::GetChannelCoordinator (void) const
Returns
current channel coordinator for multiple channel operation
Definition at line 490 of file wave-net-device.cc.
References m_channelCoordinator.
Referenced by ns3::VsaManager::DoSendVsa(), ns3::DefaultChannelScheduler::GetAssignedAccessType(), GetTypeId(), and ns3::WaveMacLow::SetWaveNetDevice().
GetChannelManager()
Ptr< ChannelManager > ns3::WaveNetDevice::GetChannelManager (void) const
Returns
currentc channel manager for multiple channel operation
Definition at line 470 of file wave-net-device.cc.
References m_channelManager.
Referenced by ns3::VsaManager::DoSendVsa(), and GetTypeId().
GetChannelScheduler()
Ptr< ChannelScheduler > ns3::WaveNetDevice::GetChannelScheduler (void) const
Returns
current channel scheduler for multiple channel operation
Definition at line 480 of file wave-net-device.cc.
References m_channelScheduler.
Referenced by ns3::VsaManager::DoSendVsa(), GetTypeId(), ns3::WaveMacLow::SetWaveNetDevice(), ChannelAccessTestCase::TestAlternatingAfter(), ChannelAccessTestCase::TestContinuousAfter(), and ChannelAccessTestCase::TestExtendedAfter().
GetIfIndex()
uint32_t ns3::WaveNetDevice::GetIfIndex (void) const virtual
Returns
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 511 of file wave-net-device.cc.
References m_ifIndex.
GetMac()
Ptr< OcbWifiMac > ns3::WaveNetDevice::GetMac (uint32_t channelNumber) const
Parameters
channelNumber the specific channel number
Returns
corresponding MAC entity
Definition at line 190 of file wave-net-device.cc.
References m_macEntities, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
Referenced by ns3::DefaultChannelScheduler::AssignDefaultCchAccess(), ns3::VsaManager::DoSendVsa(), ns3::DefaultChannelScheduler::NotifyGuardSlotStart(), ns3::ChannelScheduler::StartSch(), and ns3::DefaultChannelScheduler::SwitchToNextChannel().
GetMacs()
std::map< uint32_t, Ptr< OcbWifiMac > > ns3::WaveNetDevice::GetMacs (void) const
Returns
all inserted MAC entities.
Definition at line 202 of file wave-net-device.cc.
References m_macEntities, and NS_LOG_FUNCTION.
Referenced by ns3::WaveHelper::AssignStreams(), and ns3::VsaManager::DoInitialize().
GetMtu()
uint16_t ns3::WaveNetDevice::GetMtu (void) const virtual
Returns
the link-level MTU in bytes for this interface.
This value is typically used by the IP layer to perform IP fragmentation when needed.
Implements ns3::NetDevice.
Definition at line 545 of file wave-net-device.cc.
References m_mtu.
Referenced by GetTypeId().
GetMulticast() [1/2]
Address ns3::WaveNetDevice::GetMulticast (Ipv4Address multicastGroup) const virtual
Make and return a MAC multicast address using the provided multicast group.
RFC 1112 says that an Ipv4 host group address is mapped to an Ethernet multicast address by placing the low-order 23-bits of the IP address into the low-order 23 bits of the Ethernet multicast address 01-00-5E-00-00-00 (hex). Similar RFCs exist for Ipv6 and Eui64 mappings. This method performs the multicast address creation function appropriate to the underlying MAC address of the device. This MAC address is encapsulated in an abstract Address to avoid dependencies on the exact MAC address format.
In the case of net devices that do not support multicast, clients are expected to test NetDevice::IsMulticast and avoid attempting to map multicast packets. Subclasses of NetDevice that do support multicasting are expected to override this method and provide an implementation appropriate to the particular device.
Parameters
multicastGroup The IP address for the multicast group destination of the packet.
Returns
The MAC multicast Address used to send packets to the provided multicast group.
Warning
Calling this method is invalid if IsMulticast returns not true.
See also
IsMulticast()
Implements ns3::NetDevice.
Definition at line 578 of file wave-net-device.cc.
References ns3::Mac48Address::GetMulticast().
GetMulticast() [2/2]
Address ns3::WaveNetDevice::GetMulticast (Ipv6Address addr) const virtual
Get the MAC multicast address corresponding to the IPv6 address provided.
Parameters
addr IPv6 address
Returns
the MAC multicast address
Warning
Calling this method is invalid if IsMulticast returns not true.
Implements ns3::NetDevice.
Definition at line 582 of file wave-net-device.cc.
References ns3::Mac48Address::GetMulticast().
GetNode()
Ptr< Node > ns3::WaveNetDevice::GetNode (void) const virtual
Returns
the node base class which contains this network interface.
When a subclass needs to get access to the underlying node base class to print the nodeid for example, it can invoke this method.
Implements ns3::NetDevice.
Definition at line 639 of file wave-net-device.cc.
References m_node.
GetPhy()
Ptr< WifiPhy > ns3::WaveNetDevice::GetPhy (uint32_t index) const
Parameters
index the index of PHY entity
Returns
corresponding PHY entity
Definition at line 219 of file wave-net-device.cc.
References m_phyEntities, and NS_LOG_FUNCTION.
Referenced by ns3::DefaultChannelScheduler::GetAssignedAccessType().
GetPhys()
std::vector< Ptr< WifiPhy > > ns3::WaveNetDevice::GetPhys (void) const
Returns
all inserted PHY entities.
Definition at line 226 of file wave-net-device.cc.
References m_phyEntities, and NS_LOG_FUNCTION.
Referenced by ns3::WaveHelper::AssignStreams(), ns3::YansWavePhyHelper::EnablePcapInternal(), and ns3::DefaultChannelScheduler::GetAssignedAccessType().
GetTypeId()
TypeId ns3::WaveNetDevice::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 39 of file wave-net-device.cc.
References GetChannel(), GetChannelCoordinator(), GetChannelManager(), GetChannelScheduler(), GetMtu(), GetVsaManager(), ns3::LLC_SNAP_HEADER_LENGTH, m_macEntities, m_phyEntities, ns3::MakeObjectMapAccessor(), ns3::MakeObjectVectorAccessor(), ns3::MakePointerAccessor(), ns3::MakeUintegerAccessor(), MAX_MSDU_SIZE, SetChannelCoordinator(), SetChannelManager(), SetChannelScheduler(), SetMtu(), ns3::TypeId::SetParent(), and SetVsaManager().
GetVsaManager()
Ptr< VsaManager > ns3::WaveNetDevice::GetVsaManager (void) const
Returns
current VSA manager for multiple channel operation
Definition at line 500 of file wave-net-device.cc.
References m_vsaManager.
Referenced by GetTypeId().
IsAvailableChannel()
bool ns3::WaveNetDevice::IsAvailableChannel (uint32_t channelNumber) const private
Parameters
channelNumber the specific channel
Returns
whether this channel is valid and available for use
Definition at line 663 of file wave-net-device.cc.
References ns3::ChannelManager::IsWaveChannel(), m_macEntities, and NS_LOG_DEBUG.
Referenced by CancelTx(), DeleteTxProfile(), RegisterTxProfile(), SendX(), StartSch(), StartVsa(), StopSch(), and StopVsa().
IsBridge()
bool ns3::WaveNetDevice::IsBridge (void) const virtual
Return true if the net device is acting as a bridge.
Returns
value of m_isBridge flag
Implements ns3::NetDevice.
Definition at line 592 of file wave-net-device.cc.
IsBroadcast()
bool ns3::WaveNetDevice::IsBroadcast (void) const virtual
Returns
true if this interface supports a broadcast address, false otherwise.
Implements ns3::NetDevice.
Definition at line 563 of file wave-net-device.cc.
IsLinkUp()
bool ns3::WaveNetDevice::IsLinkUp (void) const virtual
Returns
true if link is up; false otherwise
Implements ns3::NetDevice.
Definition at line 550 of file wave-net-device.cc.
IsMulticast()
bool ns3::WaveNetDevice::IsMulticast (void) const virtual
Returns
value of m_isMulticast flag
Implements ns3::NetDevice.
Definition at line 573 of file wave-net-device.cc.
IsPointToPoint()
bool ns3::WaveNetDevice::IsPointToPoint (void) const virtual
Return true if the net device is on a point-to-point link.
Returns
value of m_isPointToPoint flag
Implements ns3::NetDevice.
Definition at line 587 of file wave-net-device.cc.
NeedsArp()
bool ns3::WaveNetDevice::NeedsArp (void) const virtual
Returns
true if ARP is needed, false otherwise.
Called by higher-layers to check if this NetDevice requires ARP to be used.
Implements ns3::NetDevice.
Definition at line 649 of file wave-net-device.cc.
RegisterTxProfile()
bool ns3::WaveNetDevice::RegisterTxProfile (const TxProfile & txprofile)
Parameters
txprofile transmit profile for IP-based data register a transmitter profile in the MLME before the associated IP-based data transfer starts.
Returns
whether the tx profile is registered successfully
note: This method should be called before WaveNetDevice::Send method
Definition at line 304 of file wave-net-device.cc.
References CCH, ns3::TxProfile::channelNumber, ns3::TxProfile::dataRate, ns3::WifiMode::GetUniqueName(), IsAvailableChannel(), m_phyEntities, m_txProfile, NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::TxProfile::txPowerLevel.
Referenced by WaveNetDeviceExample::SendIpExample().
Send()
bool ns3::WaveNetDevice::Send (Ptr< Packet > packet, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Returns
whether the Send operation succeeded
Normally this method is called by 1609.3 standard to send IP-based packets, however high layers can also send packets in other types except IP-based packets in CCH.
Implements ns3::NetDevice.
Definition at line 598 of file wave-net-device.cc.
References ns3::TxProfile::adaptable, ns3::Packet::AddHeader(), ns3::Packet::AddPacketTag(), ns3::TxProfile::channelNumber, ns3::Mac48Address::ConvertFrom(), ns3::TxProfile::dataRate, ns3::WifiNetDevice::GetMac(), m_channelScheduler, m_txProfile, third::mac, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::TxProfile::preamble, ns3::WifiTxVector::SetMode(), ns3::WifiTxVector::SetPreambleType(), ns3::WifiTxVector::SetTxPowerLevel(), ns3::LlcSnapHeader::SetType(), and ns3::TxProfile::txPowerLevel.
Referenced by ChannelRoutingTestCase::SendIp(), and WaveNetDeviceExample::SendIpPacket().
SendFrom()
bool ns3::WaveNetDevice::SendFrom (Ptr< Packet > packet, const Address & source, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
source source mac address (so called "MAC spoofing")
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device with the specified source and destination Addresses.
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 723 of file wave-net-device.cc.
References NS_LOG_FUNCTION.
SendX()
bool ns3::WaveNetDevice::SendX (Ptr< Packet > packet, const Address & dest, uint32_t protocol, const TxInfo & txInfo)
Parameters
packet packet sent from above down to Network Device
dest mac address of the destination (already resolved)
protocol identifies the type of payload contained in the packet. Used to call the right L3Protocol when the packet is received.
txInfo WSMP or other packets parameters for sending
Returns
whether the SendX operation succeeded
Normally this method is called by 1609.3 standard to send WSMP packets, however high layers can also send packets in other types except IP-based packets in CCH.
Definition at line 371 of file wave-net-device.cc.
References ns3::Packet::AddHeader(), ns3::Packet::AddPacketTag(), CCH, ns3::TxInfo::channelNumber, ns3::Mac48Address::ConvertFrom(), ns3::TxInfo::dataRate, ns3::WifiNetDevice::GetMac(), IPv4_PROT_NUMBER, IPv6_PROT_NUMBER, IsAvailableChannel(), m_channelScheduler, m_phyEntities, third::mac, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::TxInfo::preamble, ns3::TxInfo::priority, ns3::Packet::ReplacePacketTag(), ns3::WifiTxVector::SetChannelWidth(), ns3::WifiTxVector::SetMode(), ns3::WifiTxVector::SetPreambleType(), ns3::SocketPriorityTag::SetPriority(), ns3::WifiTxVector::SetTxPowerLevel(), ns3::LlcSnapHeader::SetType(), and ns3::TxInfo::txPowerLevel.
Referenced by WaveNetDeviceExample::SendOneWsmpPacket(), AnnexC_TestCase::SendPacket(), ChannelRoutingTestCase::SendWsmp(), and ChannelAccessTestCase::SendX().
SetAddress()
void ns3::WaveNetDevice::SetAddress (Address address) virtual
Set the address of this interface.
Parameters
address address to set
Implements ns3::NetDevice.
Definition at line 522 of file wave-net-device.cc.
References first::address, ns3::Mac48Address::ConvertFrom(), and m_macEntities.
Referenced by ChangeAddress(), and ns3::WaveHelper::Install().
SetChannelCoordinator()
void ns3::WaveNetDevice::SetChannelCoordinator (Ptr< ChannelCoordinator > channelCoordinator)
Parameters
channelCoordinator the channel coordinator for multiple channel operation
Definition at line 485 of file wave-net-device.cc.
References m_channelCoordinator.
Referenced by GetTypeId(), and ns3::WaveHelper::Install().
SetChannelManager()
void ns3::WaveNetDevice::SetChannelManager (Ptr< ChannelManager > channelManager)
Parameters
channelManager the channel manager for multiple channel operation
Definition at line 465 of file wave-net-device.cc.
References m_channelManager.
Referenced by GetTypeId(), and ns3::WaveHelper::Install().
SetChannelScheduler()
void ns3::WaveNetDevice::SetChannelScheduler (Ptr< ChannelScheduler > channelScheduler)
Parameters
channelScheduler the channel scheduler for multiple channel operation
Definition at line 475 of file wave-net-device.cc.
References m_channelScheduler.
Referenced by GetTypeId(), and ns3::WaveHelper::Install().
SetIfIndex()
void ns3::WaveNetDevice::SetIfIndex (const uint32_t index) virtual
Parameters
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 506 of file wave-net-device.cc.
References m_ifIndex.
SetMtu()
bool ns3::WaveNetDevice::SetMtu (const uint16_t mtu) virtual
Parameters
mtu MTU value, in bytes, to set for the device
Returns
whether the MTU value was within legal bounds
Override for default MTU defined on a per-type basis.
Implements ns3::NetDevice.
Definition at line 535 of file wave-net-device.cc.
References ns3::LLC_SNAP_HEADER_LENGTH, m_mtu, and MAX_MSDU_SIZE.
Referenced by GetTypeId().
SetNode()
void ns3::WaveNetDevice::SetNode (Ptr< Node > node) virtual
Parameters
node the node associated to this netdevice.
This method is called from ns3::Node::AddDevice.
Implements ns3::NetDevice.
Definition at line 644 of file wave-net-device.cc.
References m_node.
SetPromiscReceiveCallback()
void ns3::WaveNetDevice::SetPromiscReceiveCallback (PromiscReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received in promiscuous mode and must be forwarded to the higher layers.
Enables netdevice promiscuous mode and sets the callback that will handle promiscuous mode packets. Note, promiscuous mode packets means all packets, including those packets that can be sensed by the netdevice but which are intended to be received by other hosts.
Implements ns3::NetDevice.
Definition at line 730 of file wave-net-device.cc.
References m_macEntities, and m_promiscRx.
SetReceiveCallback()
void ns3::WaveNetDevice::SetReceiveCallback (NetDevice::ReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received and must be forwarded to the higher layers.
Set the callback to be used to notify higher layers when a packet has been received.
Implements ns3::NetDevice.
Definition at line 657 of file wave-net-device.cc.
References m_forwardUp.
Referenced by WaveNetDeviceExample::CreateWaveNodes(), ChannelAccessTestCase::DoRun(), and AnnexC_TestCase::DoRun().
SetVsaManager()
void ns3::WaveNetDevice::SetVsaManager (Ptr< VsaManager > vsaManager)
Parameters
vsaManager the VSA manager for multiple channel operation
Definition at line 495 of file wave-net-device.cc.
References m_vsaManager.
Referenced by GetTypeId(), and ns3::WaveHelper::Install().
SetWaveVsaCallback()
void ns3::WaveNetDevice::SetWaveVsaCallback (WaveVsaCallback vsaCallback)
Parameters
vsaCallback the VSA receive callback for 1609 management information
Definition at line 275 of file wave-net-device.cc.
References m_vsaManager, and NS_LOG_FUNCTION.
Referenced by WaveNetDeviceExample::CreateWaveNodes().
StartSch()
bool ns3::WaveNetDevice::StartSch (const SchInfo & schInfo)
Parameters
schInfo the parameters about how to start SCH service
Returns
whether channel access is assigned successfully
Definition at line 282 of file wave-net-device.cc.
References ns3::SchInfo::channelNumber, IsAvailableChannel(), m_channelScheduler, and NS_LOG_FUNCTION.
Referenced by WaveNetDeviceExample::SendIpExample(), WaveNetDeviceExample::SendWsaExample(), WaveNetDeviceExample::SendWsmpExample(), ChannelAccessTestCase::TestAlternating(), ChannelAccessTestCase::TestContinuous(), and ChannelAccessTestCase::TestExtended().
StartVsa()
bool ns3::WaveNetDevice::StartVsa (const VsaInfo & vsaInfo)
Parameters
vsaInfo the parameters about how to send VSA frame
Returns
whether the request for VSA transmission is completed
Definition at line 233 of file wave-net-device.cc.
References ns3::VsaInfo::channelNumber, IsAvailableChannel(), ns3::OrganizationIdentifier::IsNull(), m_channelScheduler, m_vsaManager, ns3::VsaInfo::managementId, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::VsaInfo::oi, and ns3::VsaInfo::vsc.
Referenced by ChannelRoutingTestCase::SendWsa(), and WaveNetDeviceExample::SendWsaExample().
StopSch()
bool ns3::WaveNetDevice::StopSch (uint32_t channelNumber)
Parameters
channelNumber the channel which access resource will be released.
Returns
whether channel access is released successfully
Definition at line 293 of file wave-net-device.cc.
References IsAvailableChannel(), m_channelScheduler, and NS_LOG_FUNCTION.
Referenced by WaveNetDeviceExample::SendIpExample(), WaveNetDeviceExample::SendWsaExample(), and WaveNetDeviceExample::SendWsmpExample().
StopVsa()
bool ns3::WaveNetDevice::StopVsa (uint32_t channelNumber)
Parameters
channelNumber the channel on which VSA transmit event will be canceled.
Returns
whether the request for stopping VSA transmission is completed
Definition at line 263 of file wave-net-device.cc.
References IsAvailableChannel(), m_vsaManager, and NS_LOG_FUNCTION.
Referenced by WaveNetDeviceExample::SendWsaExample().
SupportsSendFrom()
bool ns3::WaveNetDevice::SupportsSendFrom (void) const virtual
Returns
true if this interface supports a bridging mode, false otherwise.
Implements ns3::NetDevice.
Definition at line 740 of file wave-net-device.cc.
References CCH, and ns3::WifiNetDevice::GetMac().
Member Data Documentation
IPv4_PROT_NUMBER
const uint16_t ns3::WaveNetDevice::IPv4_PROT_NUMBER = 0x0800 static private
IP v4 Protocol number.
Definition at line 360 of file wave-net-device.h.
Referenced by SendX().
IPv6_PROT_NUMBER
const uint16_t ns3::WaveNetDevice::IPv6_PROT_NUMBER = 0x86DD static private
IP v6 Protocol number.
Definition at line 362 of file wave-net-device.h.
Referenced by SendX().
m_addressChange
TracedCallback<Address, Address> ns3::WaveNetDevice::m_addressChange private
Todo:
The Address arguments should be passed by const reference, since they are large.
Definition at line 401 of file wave-net-device.h.
Referenced by ChangeAddress().
m_channelCoordinator
Ptr<ChannelCoordinator> ns3::WaveNetDevice::m_channelCoordinator private
the channel coordinator
Definition at line 394 of file wave-net-device.h.
Referenced by DoDispose(), DoInitialize(), GetChannelCoordinator(), and SetChannelCoordinator().
m_channelManager
Ptr<ChannelManager> ns3::WaveNetDevice::m_channelManager private
the channel manager
Definition at line 392 of file wave-net-device.h.
Referenced by DoDispose(), DoInitialize(), GetChannelManager(), and SetChannelManager().
m_channelScheduler
Ptr<ChannelScheduler> ns3::WaveNetDevice::m_channelScheduler private
the channel scheduler
Definition at line 393 of file wave-net-device.h.
Referenced by DoDispose(), DoInitialize(), GetChannelScheduler(), Send(), SendX(), SetChannelScheduler(), StartSch(), StartVsa(), and StopSch().
m_forwardUp
NetDevice::ReceiveCallback ns3::WaveNetDevice::m_forwardUp private
forward up receive callback
Definition at line 405 of file wave-net-device.h.
Referenced by ForwardUp(), and SetReceiveCallback().
m_ifIndex
uint32_t ns3::WaveNetDevice::m_ifIndex private
IF index.
Definition at line 407 of file wave-net-device.h.
Referenced by GetIfIndex(), and SetIfIndex().
m_macEntities
MacEntities ns3::WaveNetDevice::m_macEntities private
MAC entities.
Definition at line 385 of file wave-net-device.h.
Referenced by AddMac(), ChangeAddress(), DoDispose(), DoInitialize(), GetMac(), GetMacs(), GetTypeId(), IsAvailableChannel(), SetAddress(), and SetPromiscReceiveCallback().
m_mtu
uint16_t ns3::WaveNetDevice::m_mtu mutable private
MTU.
Definition at line 408 of file wave-net-device.h.
Referenced by GetMtu(), and SetMtu().
m_node
Ptr<Node> ns3::WaveNetDevice::m_node private
the node
Definition at line 404 of file wave-net-device.h.
Referenced by GetNode(), and SetNode().
m_phyEntities
PhyEntities ns3::WaveNetDevice::m_phyEntities private
Phy entities.
Definition at line 390 of file wave-net-device.h.
Referenced by AddPhy(), DoDispose(), DoInitialize(), GetChannel(), GetPhy(), GetPhys(), GetTypeId(), RegisterTxProfile(), and SendX().
m_promiscRx
NetDevice::PromiscReceiveCallback ns3::WaveNetDevice::m_promiscRx private
promiscious receive callback
Definition at line 406 of file wave-net-device.h.
Referenced by ForwardUp(), and SetPromiscReceiveCallback().
m_txProfile
TxProfile* ns3::WaveNetDevice::m_txProfile private
transmit profile
Definition at line 396 of file wave-net-device.h.
Referenced by DeleteTxProfile(), DoDispose(), RegisterTxProfile(), and Send().
m_vsaManager
Ptr<VsaManager> ns3::WaveNetDevice::m_vsaManager private
the VSA manager
Definition at line 395 of file wave-net-device.h.
Referenced by DoDispose(), DoInitialize(), GetVsaManager(), SetVsaManager(), SetWaveVsaCallback(), StartVsa(), and StopVsa().
MAX_MSDU_SIZE
const uint16_t ns3::WaveNetDevice::MAX_MSDU_SIZE = 2304 static private
This value conforms to the 802.11 specification.
Definition at line 357 of file wave-net-device.h.
Referenced by GetTypeId(), and SetMtu().
The documentation for this class was generated from the following files:
src/wave/model/wave-net-device.h
src/wave/model/wave-net-device.cc