ns-3: ns3::SimpleDeviceEnergyModel Class Reference
ns3::SimpleDeviceEnergyModel Class Reference
Energy Models
A simple device energy model where current drain can be set by the user.
#include "simple-device-energy-model.h"
Public Member Functions
SimpleDeviceEnergyModel ()
virtual ~SimpleDeviceEnergyModel ()
virtual void ChangeState (int newState)
virtual Ptr< Node > GetNode (void) const
Gets pointer to node.
virtual double GetTotalEnergyConsumption (void) const
virtual void HandleEnergyChanged (void)
Handles energy changed.
virtual void HandleEnergyDepletion (void)
Handles energy depletion.
virtual void HandleEnergyRecharged (void)
Handles energy recharged.
void SetCurrentA (double current)
virtual void SetEnergySource (Ptr< EnergySource > source)
Sets pointer to EnergySouce installed on node.
virtual void SetNode (Ptr< Node > node)
Sets pointer to node.
Public Member Functions inherited from ns3::DeviceEnergyModel
DeviceEnergyModel ()
virtual ~DeviceEnergyModel ()
double GetCurrentA (void) const
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::DeviceEnergyModel
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void DoDispose (void)
Destructor implementation.
virtual double DoGetCurrentA (void) const
Private Attributes
double m_actualCurrentA
Time m_lastUpdateTime
Ptr< Node > m_node
Ptr< EnergySource > m_source
TracedValue< double > m_totalEnergyConsumption
Additional Inherited Members
Public Types inherited from ns3::DeviceEnergyModel
typedef Callback< void, int > ChangeStateCallback
Callback type for ChangeState function.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A simple device energy model where current drain can be set by the user.
Introspection did not find any typical Config paths.
It is supposed to be used as a testing model for energy sources.
No Attributes are defined for this type.
TraceSources
TotalEnergyConsumption: Total energy consumption of the radio device.
Callback signature: ns3::TracedValueCallback::Double
Size of this type is 96 bytes (on a 64-bit architecture).
Definition at line 38 of file simple-device-energy-model.h.
Constructor & Destructor Documentation
SimpleDeviceEnergyModel()
ns3::SimpleDeviceEnergyModel::SimpleDeviceEnergyModel ()
Definition at line 48 of file simple-device-energy-model.cc.
References m_actualCurrentA, m_lastUpdateTime, m_source, NS_LOG_FUNCTION, and ns3::Seconds().
~SimpleDeviceEnergyModel()
ns3::SimpleDeviceEnergyModel::~SimpleDeviceEnergyModel () virtual
Definition at line 56 of file simple-device-energy-model.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
ChangeState()
virtual void ns3::SimpleDeviceEnergyModel::ChangeState (int newState) inline virtual
Parameters
newState New state the device is in.
Not implemented
Implements ns3::DeviceEnergyModel.
Definition at line 84 of file simple-device-energy-model.h.
DoDispose()
void ns3::SimpleDeviceEnergyModel::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 120 of file simple-device-energy-model.cc.
References m_source, and NS_LOG_FUNCTION.
DoGetCurrentA()
double ns3::SimpleDeviceEnergyModel::DoGetCurrentA (void) const private virtual
Returns
Current draw of device, at current state.
Implements DeviceEnergyModel::GetCurrentA.
Reimplemented from ns3::DeviceEnergyModel.
Definition at line 127 of file simple-device-energy-model.cc.
References m_actualCurrentA, and NS_LOG_FUNCTION.
GetNode()
Ptr< Node > ns3::SimpleDeviceEnergyModel::GetNode (void) const virtual
Gets pointer to node.
Returns
Pointer to node.
Implements DeviceEnergyModel::GetNode.
Definition at line 78 of file simple-device-energy-model.cc.
References m_node, and NS_LOG_FUNCTION.
GetTotalEnergyConsumption()
double ns3::SimpleDeviceEnergyModel::GetTotalEnergyConsumption (void) const virtual
Returns
Total energy consumption of the vehicle.
Implements DeviceEnergyModel::GetTotalEnergyConsumption.
Implements ns3::DeviceEnergyModel.
Definition at line 85 of file simple-device-energy-model.cc.
References ns3::Time::GetSeconds(), m_actualCurrentA, m_lastUpdateTime, m_source, m_totalEnergyConsumption, ns3::Simulator::Now(), and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::SimpleDeviceEnergyModel::GetTypeId (void) static
Definition at line 34 of file simple-device-energy-model.cc.
References m_totalEnergyConsumption, ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
HandleEnergyChanged()
virtual void ns3::SimpleDeviceEnergyModel::HandleEnergyChanged (void) inline virtual
Handles energy changed.
Not implemented
Implements ns3::DeviceEnergyModel.
Definition at line 111 of file simple-device-energy-model.h.
HandleEnergyDepletion()
virtual void ns3::SimpleDeviceEnergyModel::HandleEnergyDepletion (void) inline virtual
Handles energy depletion.
Not implemented
Implements ns3::DeviceEnergyModel.
Definition at line 93 of file simple-device-energy-model.h.
HandleEnergyRecharged()
virtual void ns3::SimpleDeviceEnergyModel::HandleEnergyRecharged (void) inline virtual
Handles energy recharged.
Not implemented
Implements ns3::DeviceEnergyModel.
Definition at line 102 of file simple-device-energy-model.h.
SetCurrentA()
void ns3::SimpleDeviceEnergyModel::SetCurrentA (double current)
Parameters
current the current draw of device.
Set the actual current draw of the device.
Definition at line 100 of file simple-device-energy-model.cc.
References ns3::Time::GetSeconds(), m_actualCurrentA, m_lastUpdateTime, m_source, m_totalEnergyConsumption, ns3::Simulator::Now(), and NS_LOG_FUNCTION.
Referenced by LiIonEnergyTestCase::DoRun(), and AnimationRemainingEnergyTestCase::PrepareNetwork().
SetEnergySource()
void ns3::SimpleDeviceEnergyModel::SetEnergySource (Ptr< EnergySource > source) virtual
Sets pointer to EnergySouce installed on node.
Parameters
source Pointer to EnergySource installed on node.
Implements DeviceEnergyModel::SetEnergySource.
Implements ns3::DeviceEnergyModel.
Definition at line 62 of file simple-device-energy-model.cc.
References m_source, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by LiIonEnergyTestCase::DoRun(), and AnimationRemainingEnergyTestCase::PrepareNetwork().
SetNode()
void ns3::SimpleDeviceEnergyModel::SetNode (Ptr< Node > node) virtual
Sets pointer to node.
Parameters
node Pointer to node.
Implements DeviceEnergyModel::SetNode.
Definition at line 70 of file simple-device-energy-model.cc.
References m_node, NS_ASSERT, and NS_LOG_FUNCTION.
Member Data Documentation
m_actualCurrentA
double ns3::SimpleDeviceEnergyModel::m_actualCurrentA private
Definition at line 132 of file simple-device-energy-model.h.
Referenced by SimpleDeviceEnergyModel(), DoGetCurrentA(), GetTotalEnergyConsumption(), and SetCurrentA().
m_lastUpdateTime
Time ns3::SimpleDeviceEnergyModel::m_lastUpdateTime private
Definition at line 131 of file simple-device-energy-model.h.
Referenced by SimpleDeviceEnergyModel(), GetTotalEnergyConsumption(), and SetCurrentA().
m_node
Ptr<Node> ns3::SimpleDeviceEnergyModel::m_node private
Definition at line 134 of file simple-device-energy-model.h.
Referenced by GetNode(), and SetNode().
m_source
Ptr<EnergySource> ns3::SimpleDeviceEnergyModel::m_source private
Definition at line 133 of file simple-device-energy-model.h.
Referenced by SimpleDeviceEnergyModel(), DoDispose(), GetTotalEnergyConsumption(), SetCurrentA(), and SetEnergySource().
m_totalEnergyConsumption
TracedValue<double> ns3::SimpleDeviceEnergyModel::m_totalEnergyConsumption private
Definition at line 135 of file simple-device-energy-model.h.
Referenced by GetTotalEnergyConsumption(), GetTypeId(), and SetCurrentA().
The documentation for this class was generated from the following files:
src/energy/model/simple-device-energy-model.h
src/energy/model/simple-device-energy-model.cc