ns-3: ns3::RegularWifiMac Class Reference
ns3::RegularWifiMac Class Reference abstract
Wifi Models
base class for all MAC-level wifi objects.
#include "regular-wifi-mac.h"
Public Types
typedef Callback< void, Ptr< const Packet >, Mac48Address, Mac48Address > ForwardUpCallback
This type defines the callback of a higher layer that a WifiMac(-derived) object invokes to pass a packet up the stack.
Public Member Functions
RegularWifiMac ()
virtual ~RegularWifiMac ()
void ConfigureStandard (WifiStandard standard)
virtual void Enqueue (Ptr< Packet > packet, Mac48Address to)=0
virtual void Enqueue (Ptr< Packet > packet, Mac48Address to, Mac48Address from)
Mac48Address GetAddress (void) const
Mac48Address GetBssid (void) const
ExtendedCapabilities GetExtendedCapabilities (void) const
Return the extended capabilities of the device.
HeCapabilities GetHeCapabilities (void) const
Return the HE capabilities of the device.
HtCapabilities GetHtCapabilities (void) const
Return the HT capabilities of the device.
bool GetShortSlotTimeSupported (void) const
Ssid GetSsid (void) const
VhtCapabilities GetVhtCapabilities (void) const
Return the VHT capabilities of the device.
Ptr< WifiPhy > GetWifiPhy (void) const
Ptr< WifiRemoteStationManager > GetWifiRemoteStationManager (void) const
void ResetWifiPhy (void)
Remove currently attached WifiPhy device from this MAC.
void SetAddress (Mac48Address address)
void SetBssid (Mac48Address bssid)
void SetCtsToSelfSupported (bool enable)
Enable or disable CTS-to-self feature.
void SetForwardUpCallback (ForwardUpCallback upCallback)
void SetLinkDownCallback (Callback< void > linkDown)
void SetLinkUpCallback (Callback< void > linkUp)
void SetPromisc (void)
Sets the interface in promiscuous mode.
void SetShortSlotTimeSupported (bool enable)
Enable or disable short slot time feature.
void SetSsid (Ssid ssid)
virtual void SetWifiPhy (const Ptr< WifiPhy > phy)
virtual void SetWifiRemoteStationManager (const Ptr< WifiRemoteStationManager > stationManager)
virtual bool SupportsSendFrom (void) const
Public Member Functions inherited from ns3::WifiMac
Ptr< NetDevice > GetDevice (void) const
Return the device this PHY is associated with.
Ptr< HeConfiguration > GetHeConfiguration (void) const
Ptr< HtConfiguration > GetHtConfiguration (void) const
Ptr< VhtConfiguration > GetVhtConfiguration (void) const
void NotifyPromiscRx (Ptr< const Packet > packet)
void NotifyRx (Ptr< const Packet > packet)
void NotifyRxDrop (Ptr< const Packet > packet)
void NotifyTx (Ptr< const Packet > packet)
void NotifyTxDrop (Ptr< const Packet > packet)
void SetDevice (const Ptr< NetDevice > device)
Sets the device this PHY is associated with.
virtual void SetForwardUpCallback (Callback< void, Ptr< const Packet >, Mac48Address, Mac48Address > upCallback)=0
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::WifiMac
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Types
typedef std::map< AcIndex, Ptr< QosTxop > > EdcaQueues
This type defines a mapping between an Access Category index, and a pointer to the corresponding channel access function.
Protected Member Functions
void ConfigureContentionWindow (uint32_t cwMin, uint32_t cwMax)
virtual void DeaggregateAmsduAndForward (Ptr< WifiMacQueueItem > mpdu)
This method can be called to de-aggregate an A-MSDU and forward the constituent packets up the stack.
virtual void DoDispose ()
Destructor implementation.
virtual void DoInitialize ()
Initialize() implementation.
void ForwardUp (Ptr< const Packet > packet, Mac48Address from, Mac48Address to)
Forward the packet up to the device.
Ptr< QosTxop > GetBEQueue (void) const
Accessor for the AC_BE channel access function.
Ptr< QosTxop > GetBKQueue (void) const
Accessor for the AC_BK channel access function.
bool GetDsssSupported () const
Return whether the device supports DSSS.
bool GetErpSupported () const
Return whether the device supports ERP.
bool GetHeSupported () const
Return whether the device supports HE.
bool GetHtSupported () const
Return whether the device supports HT.
bool GetQosSupported () const
Return whether the device supports QoS.
Ptr< Txop > GetTxop (void) const
Accessor for the DCF object.
bool GetVhtSupported () const
Return whether the device supports VHT.
Ptr< QosTxop > GetVIQueue (void) const
Accessor for the AC_VI channel access function.
Ptr< QosTxop > GetVOQueue (void) const
Accessor for the AC_VO channel access function.
virtual void Receive (Ptr< WifiMacQueueItem > mpdu)
This method acts as the MacRxMiddle receive callback and is invoked to notify us that a frame has been received.
void SendAddBaResponse (const MgtAddBaRequestHeader *reqHdr, Mac48Address originator)
This method can be called to accept a received ADDBA Request.
void SetDsssSupported (bool enable)
Enable or disable DSSS support for the device.
void SetErpSupported (bool enable)
Enable or disable ERP support for the device.
virtual void SetQosSupported (bool enable)
Enable or disable QoS support for the device.
void SetTypeOfStation (TypeOfStation type)
This method is invoked by a subclass to specify what type of station it is implementing.
virtual void TxFailed (const WifiMacHeader &hdr)
The packet we sent was successfully received by the receiver (i.e.
virtual void TxOk (const WifiMacHeader &hdr)
The packet we sent was successfully received by the receiver (i.e.
Protected Member Functions inherited from ns3::WifiMac
void ConfigureDcf (Ptr< Txop > dcf, uint32_t cwmin, uint32_t cwmax, bool isDsss, AcIndex ac)
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes
Ptr< ChannelAccessManager > m_channelAccessManager
channel access manager
EdcaQueues m_edca
This is a map from Access Category index to the corresponding channel access function.
ForwardUpCallback m_forwardUp
Callback to forward packet up the stack.
Callback< void > m_linkDown
Callback when a link is down.
Callback< void > m_linkUp
Callback when a link is up.
Ptr< MacLow > m_low
MacLow (RTS, CTS, Data, Ack etc.)
Ptr< WifiPhy > m_phy
Wifi PHY.
Ptr< MacRxMiddle > m_rxMiddle
RX middle (defragmentation etc.)
Ssid m_ssid
Service Set ID (SSID)
Ptr< WifiRemoteStationManager > m_stationManager
Remote station manager (rate control, RTS/CTS/fragmentation thresholds etc.)
Ptr< MacTxMiddle > m_txMiddle
TX middle (aggregation etc.)
Ptr< Txop > m_txop
This holds a pointer to the TXOP instance for this WifiMac - used for transmission of frames to non-QoS peers.
Private Member Functions
RegularWifiMac (const RegularWifiMac &)
type conversion operator
void DisableAggregation (void)
Disable aggregation function.
void EnableAggregation (void)
Enable aggregation function.
RegularWifiMac & operator= (const RegularWifiMac &mac)
assignment operator
void SetBeBlockAckInactivityTimeout (uint16_t timeout)
Set BE block ack inactivity timeout.
void SetBeBlockAckThreshold (uint8_t threshold)
Set the block ack threshold for AC_BE.
void SetBkBlockAckInactivityTimeout (uint16_t timeout)
Set BK block ack inactivity timeout.
void SetBkBlockAckThreshold (uint8_t threshold)
Set the block ack threshold for AC_BK.
void SetupEdcaQueue (AcIndex ac)
This method is a private utility invoked to configure the channel access function for the specified Access Category.
void SetViBlockAckInactivityTimeout (uint16_t timeout)
Set VI block ack inactivity timeout.
void SetViBlockAckThreshold (uint8_t threshold)
Set the block ack threshold for AC_VI.
void SetVoBlockAckInactivityTimeout (uint16_t timeout)
Set VO block ack inactivity timeout.
void SetVoBlockAckThreshold (uint8_t threshold)
Set the block ack threshold for AC_VO.
Private Attributes
uint32_t m_beMaxAmpduSize
maximum A-MPDU size for AC_BE (in bytes)
uint16_t m_beMaxAmsduSize
maximum A-MSDU size for AC_BE (in bytes)
uint32_t m_bkMaxAmpduSize
maximum A-MPDU size for AC_BK (in bytes)
uint16_t m_bkMaxAmsduSize
maximum A-MSDU size for AC_BK (in bytes)
bool m_dsssSupported
This Boolean is set true iff this WifiMac is to model 802.11b.
bool m_erpSupported
This Boolean is set true iff this WifiMac is to model 802.11g.
bool m_qosSupported
This Boolean is set true iff this WifiMac is to model 802.11e/WMM style Quality of Service.
bool m_shortSlotTimeSupported
flag whether short slot time is supported
TracedCallback< const WifiMacHeader & > m_txErrCallback
transmit error callback
TracedCallback< const WifiMacHeader & > m_txOkCallback
transmit OK callback
uint32_t m_viMaxAmpduSize
maximum A-MPDU size for AC_VI (in bytes)
uint16_t m_viMaxAmsduSize
maximum A-MSDU size for AC_VI (in bytes)
uint32_t m_voMaxAmpduSize
maximum A-MPDU size for AC_VO (in bytes)
uint16_t m_voMaxAmsduSize
maximum A-MSDU size for AC_VO (in bytes)
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
base class for all MAC-level wifi objects.
This class encapsulates all the low-level MAC functionality and all the high-level MAC functionality (association/disassociation state machines).
Config Paths
ns3::RegularWifiMac is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Mac/$ns3::RegularWifiMac"
Attributes
QosSupported: This Boolean attribute is set to enable 802.11e/WMM-style QoS support at this STA.
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
CtsToSelfSupported: Use CTS to Self when using a rate that is not in the basic rate set.
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write
VO_MaxAmsduSize: Maximum length in bytes of an A-MSDU for AC_VO access class (capped to 7935 for HT PPDUs and 11398 for VHT/HE PPDUs). Value 0 means A-MSDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:11398
Initial value: 0
Flags: construct write read
VI_MaxAmsduSize: Maximum length in bytes of an A-MSDU for AC_VI access class (capped to 7935 for HT PPDUs and 11398 for VHT/HE PPDUs). Value 0 means A-MSDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:11398
Initial value: 0
Flags: construct write read
BE_MaxAmsduSize: Maximum length in bytes of an A-MSDU for AC_BE access class (capped to 7935 for HT PPDUs and 11398 for VHT/HE PPDUs). Value 0 means A-MSDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:11398
Initial value: 0
Flags: construct write read
BK_MaxAmsduSize: Maximum length in bytes of an A-MSDU for AC_BK access class (capped to 7935 for HT PPDUs and 11398 for VHT/HE PPDUs). Value 0 means A-MSDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:11398
Initial value: 0
Flags: construct write read
VO_MaxAmpduSize: Maximum length in bytes of an A-MPDU for AC_VO access class (capped to 65535 for HT PPDUs, 1048575 for VHT PPDUs, and 8388607 for HE PPDUs). Value 0 means A-MPDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 0
Flags: construct write read
VI_MaxAmpduSize: Maximum length in bytes of an A-MPDU for AC_VI access class (capped to 65535 for HT PPDUs, 1048575 for VHT PPDUs, and 8388607 for HE PPDUs). Value 0 means A-MPDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 65535
Flags: construct write read
BE_MaxAmpduSize: Maximum length in bytes of an A-MPDU for AC_BE access class (capped to 65535 for HT PPDUs, 1048575 for VHT PPDUs, and 8388607 for HE PPDUs). Value 0 means A-MPDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 65535
Flags: construct write read
BK_MaxAmpduSize: Maximum length in bytes of an A-MPDU for AC_BK access class (capped to 65535 for HT PPDUs, 1048575 for VHT PPDUs, and 8388607 for HE PPDUs). Value 0 means A-MPDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 0
Flags: construct write read
VO_BlockAckThreshold: If number of packets in VO queue reaches this value, block ack mechanism is used. If this value is 0, block ack is never used.When A-MPDU is enabled, block ack mechanism is used regardless of this value.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:64
Initial value: 0
Flags: construct write
VI_BlockAckThreshold: If number of packets in VI queue reaches this value, block ack mechanism is used. If this value is 0, block ack is never used.When A-MPDU is enabled, block ack mechanism is used regardless of this value.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:64
Initial value: 0
Flags: construct write
BE_BlockAckThreshold: If number of packets in BE queue reaches this value, block ack mechanism is used. If this value is 0, block ack is never used.When A-MPDU is enabled, block ack mechanism is used regardless of this value.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:64
Initial value: 0
Flags: construct write
BK_BlockAckThreshold: If number of packets in BK queue reaches this value, block ack mechanism is used. If this value is 0, block ack is never used.When A-MPDU is enabled, block ack mechanism is used regardless of this value.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:64
Initial value: 0
Flags: construct write
VO_BlockAckInactivityTimeout: Represents max time (blocks of 1024 microseconds) allowed for block ackinactivity for AC_VO. If this value isn't equal to 0 a timer start after that ablock ack setup is completed and will be reset every time that a block ackframe is received. If this value is 0, block ack inactivity timeout won't be used.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 0
Flags: construct write
VI_BlockAckInactivityTimeout: Represents max time (blocks of 1024 microseconds) allowed for block ackinactivity for AC_VI. If this value isn't equal to 0 a timer start after that ablock ack setup is completed and will be reset every time that a block ackframe is received. If this value is 0, block ack inactivity timeout won't be used.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 0
Flags: construct write
BE_BlockAckInactivityTimeout: Represents max time (blocks of 1024 microseconds) allowed for block ackinactivity for AC_BE. If this value isn't equal to 0 a timer start after that ablock ack setup is completed and will be reset every time that a block ackframe is received. If this value is 0, block ack inactivity timeout won't be used.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 0
Flags: construct write
BK_BlockAckInactivityTimeout: Represents max time (blocks of 1024 microseconds) allowed for block ackinactivity for AC_BK. If this value isn't equal to 0 a timer start after that ablock ack setup is completed and will be reset every time that a block ackframe is received. If this value is 0, block ack inactivity timeout won't be used.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 0
Flags: construct write
ShortSlotTimeSupported: Whether or not short slot time is supported (only used by ERP APs or STAs).
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
Txop: The Txop object.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::Txop>
Flags: read
VO_Txop: Queue that manages packets belonging to AC_VO access class.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::QosTxop>
Flags: read
VI_Txop: Queue that manages packets belonging to AC_VI access class.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::QosTxop>
Flags: read
BE_Txop: Queue that manages packets belonging to AC_BE access class.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::QosTxop>
Flags: read
BK_Txop: Queue that manages packets belonging to AC_BK access class.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::QosTxop>
Flags: read
Attributes defined in parent class ns3::WifiMac
Ssid: The ssid we want to belong to.
Set with class: SsidValue
Underlying type: Ssid
Initial value: default
Flags: construct write read
TraceSources
TxOkHeader: The header of successfully transmitted packet.
Callback signature: ns3::WifiMacHeader::TracedCallback
TxErrHeader: The header of unsuccessfully transmitted packet.
Callback signature: ns3::WifiMacHeader::TracedCallback
TraceSources defined in parent class ns3::WifiMac
MacTx: A packet has been received from higher layers and is being processed in preparation for queueing for transmission.
Callback signature: ns3::Packet::TracedCallback
MacTxDrop: A packet has been dropped in the MAC layer before transmission.
Callback signature: ns3::Packet::TracedCallback
MacPromiscRx: A packet has been received by this device, has been passed up from the physical layer and is being forwarded up the local protocol stack. This is a promiscuous trace.
Callback signature: ns3::Packet::TracedCallback
MacRx: A packet has been received by this device, has been passed up from the physical layer and is being forwarded up the local protocol stack. This is a non-promiscuous trace.
Callback signature: ns3::Packet::TracedCallback
MacRxDrop: A packet has been dropped in the MAC layer after it has been passed up from the physical layer.
Callback signature: ns3::Packet::TracedCallback
Size of this type is 400 bytes (on a 64-bit architecture).
Definition at line 44 of file regular-wifi-mac.h.
Member Typedef Documentation
EdcaQueues
typedef std::map<AcIndex, Ptr<QosTxop> > ns3::RegularWifiMac::EdcaQueues protected
This type defines a mapping between an Access Category index, and a pointer to the corresponding channel access function.
Definition at line 155 of file regular-wifi-mac.h.
ForwardUpCallback
typedef Callback<void, Ptr<const Packet>, Mac48Address, Mac48Address> ns3::RegularWifiMac::ForwardUpCallback
This type defines the callback of a higher layer that a WifiMac(-derived) object invokes to pass a packet up the stack.
Parameters
packet the packet that has been received.
from the MAC address of the device that sent the packet.
to the MAC address of the device that the packet is destined for.
Definition at line 81 of file regular-wifi-mac.h.
Constructor & Destructor Documentation
RegularWifiMac() [1/2]
ns3::RegularWifiMac::RegularWifiMac ()
Definition at line 46 of file regular-wifi-mac.cc.
References ns3::AC_BE, ns3::AC_BK, ns3::AC_VI, ns3::AC_VO, m_channelAccessManager, m_low, m_rxMiddle, m_txMiddle, m_txop, ns3::MakeCallback(), ns3::WifiMac::NotifyTxDrop(), NS_LOG_FUNCTION, ns3::MacRxMiddle::Receive(), Receive(), ns3::Txop::SetChannelAccessManager(), ns3::Txop::SetMacLow(), ns3::Txop::SetTxDroppedCallback(), ns3::Txop::SetTxFailedCallback(), ns3::Txop::SetTxMiddle(), ns3::Txop::SetTxOkCallback(), SetupEdcaQueue(), ns3::ChannelAccessManager::SetupLow(), TxFailed(), and TxOk().
~RegularWifiMac()
ns3::RegularWifiMac::~RegularWifiMac () virtual
Definition at line 81 of file regular-wifi-mac.cc.
References NS_LOG_FUNCTION.
RegularWifiMac() [2/2]
ns3::RegularWifiMac::RegularWifiMac (const RegularWifiMac &) private
type conversion operator
Member Function Documentation
ConfigureContentionWindow()
void ns3::RegularWifiMac::ConfigureContentionWindow (uint32_t cwMin, uint32_t cwMax) protected
Parameters
cwMin the minimum contention window size
cwMax the maximum contention window size
This method is called to set the minimum and the maximum contention window size.
Definition at line 1086 of file regular-wifi-mac.cc.
References ns3::AC_BE_NQOS, ns3::WifiMac::ConfigureDcf(), m_dsssSupported, m_edca, m_erpSupported, and m_txop.
Referenced by ConfigureStandard(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromProbeResp().
ConfigureStandard()
void ns3::RegularWifiMac::ConfigureStandard (WifiStandard standard) virtual
Parameters
standard the wifi standard to be configured
This method completes the configuration process for a requested PHY standard. Subclasses should implement this method to configure their DCF queues according to the requested standard.
Implements ns3::WifiMac.
Definition at line 1041 of file regular-wifi-mac.cc.
References ConfigureContentionWindow(), EnableAggregation(), NS_FATAL_ERROR, NS_LOG_FUNCTION, SetDsssSupported(), SetErpSupported(), SetQosSupported(), ns3::WIFI_STANDARD_80211a, ns3::WIFI_STANDARD_80211ac, ns3::WIFI_STANDARD_80211ax_2_4GHZ, ns3::WIFI_STANDARD_80211ax_5GHZ, ns3::WIFI_STANDARD_80211ax_6GHZ, ns3::WIFI_STANDARD_80211b, ns3::WIFI_STANDARD_80211g, ns3::WIFI_STANDARD_80211n_2_4GHZ, ns3::WIFI_STANDARD_80211n_5GHZ, ns3::WIFI_STANDARD_80211p, and ns3::WIFI_STANDARD_holland.
Referenced by ns3::MeshWifiInterfaceMac::ConfigureStandard(), AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), and HeAggregationTest::DoRunSubTest().
DeaggregateAmsduAndForward()
void ns3::RegularWifiMac::DeaggregateAmsduAndForward (Ptr< WifiMacQueueItem > mpdu) protected virtual
This method can be called to de-aggregate an A-MSDU and forward the constituent packets up the stack.
Parameters
mpdu the MPDU containing the A-MSDU.
Reimplemented in ns3::ApWifiMac.
Definition at line 793 of file regular-wifi-mac.cc.
References ForwardUp(), NS_LOG_FUNCTION, and ns3::PeekPointer().
Referenced by ns3::OcbWifiMac::Receive(), ns3::AdhocWifiMac::Receive(), and ns3::StaWifiMac::Receive().
DisableAggregation()
void ns3::RegularWifiMac::DisableAggregation (void) private
Disable aggregation function.
Definition at line 1133 of file regular-wifi-mac.cc.
References m_low, and NS_LOG_FUNCTION.
DoDispose()
void ns3::RegularWifiMac::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::WifiMac.
Reimplemented in ns3::ApWifiMac, and ns3::MeshWifiInterfaceMac.
Definition at line 99 of file regular-wifi-mac.cc.
References ns3::Object::Dispose(), ns3::WifiMac::DoDispose(), m_channelAccessManager, m_edca, m_low, m_phy, m_rxMiddle, m_stationManager, m_txMiddle, m_txop, and NS_LOG_FUNCTION.
Referenced by ns3::MeshWifiInterfaceMac::DoDispose(), and ns3::ApWifiMac::DoDispose().
DoInitialize()
void ns3::RegularWifiMac::DoInitialize (void) protected virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Reimplemented in ns3::StaWifiMac, ns3::ApWifiMac, and ns3::MeshWifiInterfaceMac.
Definition at line 87 of file regular-wifi-mac.cc.
References ns3::Object::Initialize(), m_edca, m_txop, and NS_LOG_FUNCTION.
Referenced by ns3::ApWifiMac::DoInitialize().
EnableAggregation()
void ns3::RegularWifiMac::EnableAggregation (void) private
Enable aggregation function.
Definition at line 1115 of file regular-wifi-mac.cc.
References m_edca, m_low, and NS_LOG_FUNCTION.
Referenced by ConfigureStandard().
Enqueue() [1/2]
virtual void ns3::RegularWifiMac::Enqueue (Ptr< Packet > packet, Mac48Address to) pure virtual
Parameters
packet the packet to send.
to the address to which the packet should be sent.
The packet should be enqueued in a TX queue, and should be dequeued as soon as the DCF function determines that access it granted to this MAC.
Implements ns3::WifiMac.
Implemented in ns3::InfrastructureWifiMac, ns3::StaWifiMac, ns3::ApWifiMac, ns3::AdhocWifiMac, ns3::OcbWifiMac, and ns3::MeshWifiInterfaceMac.
Enqueue() [2/2]
void ns3::RegularWifiMac::Enqueue (Ptr< Packet > packet, Mac48Address to, Mac48Address from) virtual
Parameters
packet the packet to send.
to the address to which the packet should be sent.
from the address from which the packet should be sent.
The packet should be enqueued in a TX queue, and should be dequeued as soon as the DCF function determines that access it granted to this MAC. The extra parameter "from" allows this device to operate in a bridged mode, forwarding received frames without altering the source address.
Implements ns3::WifiMac.
Reimplemented in ns3::ApWifiMac, and ns3::MeshWifiInterfaceMac.
Definition at line 668 of file regular-wifi-mac.cc.
References GetAddress(), and NS_FATAL_ERROR.
ForwardUp()
void ns3::RegularWifiMac::ForwardUp (Ptr< const Packet > packet, Mac48Address from, Mac48Address to) protected
Forward the packet up to the device.
Parameters
packet the packet that we are forwarding up to the device
from the address of the source
to the address of the destination
Definition at line 686 of file regular-wifi-mac.cc.
References m_forwardUp, and NS_LOG_FUNCTION.
Referenced by ns3::ApWifiMac::DeaggregateAmsduAndForward(), DeaggregateAmsduAndForward(), ns3::MeshWifiInterfaceMac::Receive(), ns3::OcbWifiMac::Receive(), ns3::AdhocWifiMac::Receive(), ns3::ApWifiMac::Receive(), and ns3::StaWifiMac::Receive().
GetAddress()
Mac48Address ns3::RegularWifiMac::GetAddress (void) const virtual
Returns
the MAC address associated to this MAC layer.
Implements ns3::WifiMac.
Definition at line 617 of file regular-wifi-mac.cc.
References m_low.
Referenced by ns3::ApWifiMac::DeaggregateAmsduAndForward(), ns3::ApWifiMac::DoInitialize(), ns3::OcbWifiMac::Enqueue(), Enqueue(), ns3::MeshWifiInterfaceMac::ForwardDown(), ns3::ApWifiMac::ForwardDown(), ns3::MeshWifiInterfaceMac::Receive(), ns3::OcbWifiMac::Receive(), ns3::ApWifiMac::Receive(), Receive(), ns3::StaWifiMac::Receive(), ns3::MeshWifiInterfaceMac::Report(), SendAddBaResponse(), ns3::StaWifiMac::SendAssociationRequest(), ns3::ApWifiMac::SendAssocResp(), ns3::MeshWifiInterfaceMac::SendBeacon(), ns3::ApWifiMac::SendOneBeacon(), ns3::StaWifiMac::SendProbeRequest(), ns3::ApWifiMac::SendProbeResp(), and ns3::OcbWifiMac::SendVsc().
GetBEQueue()
Ptr< QosTxop > ns3::RegularWifiMac::GetBEQueue (void) const protected
Accessor for the AC_BE channel access function.
Returns
a smart pointer to QosTxop
Definition at line 472 of file regular-wifi-mac.cc.
References ns3::AC_BE, and m_edca.
Referenced by ns3::OcbWifiMac::ConfigureEdca(), AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), HeAggregationTest::DoRunSubTest(), GetTypeId(), SetBeBlockAckInactivityTimeout(), and SetBeBlockAckThreshold().
GetBKQueue()
Ptr< QosTxop > ns3::RegularWifiMac::GetBKQueue (void) const protected
Accessor for the AC_BK channel access function.
Returns
a smart pointer to QosTxop
Definition at line 478 of file regular-wifi-mac.cc.
References ns3::AC_BK, and m_edca.
Referenced by ns3::OcbWifiMac::ConfigureEdca(), GetTypeId(), SetBkBlockAckInactivityTimeout(), and SetBkBlockAckThreshold().
GetBssid()
Mac48Address ns3::RegularWifiMac::GetBssid (void) const virtual
Returns
the BSSID of the network this device belongs to.
Implements ns3::WifiMac.
Definition at line 643 of file regular-wifi-mac.cc.
References m_low.
Referenced by ns3::AdhocWifiMac::Enqueue(), ns3::StaWifiMac::Enqueue(), ns3::StaWifiMac::Receive(), SendAddBaResponse(), ns3::StaWifiMac::SendAssociationRequest(), ns3::StaWifiMac::SendCfPollResponse(), and ns3::StaWifiMac::SetState().
GetDsssSupported()
bool ns3::RegularWifiMac::GetDsssSupported () const protected
Return whether the device supports DSSS.
Returns
true if DSSS is supported, false otherwise
Definition at line 597 of file regular-wifi-mac.cc.
References m_dsssSupported.
Referenced by ns3::ApWifiMac::GetDsssParameterSet(), ns3::ApWifiMac::SendOneBeacon(), and ns3::ApWifiMac::SendProbeResp().
GetErpSupported()
bool ns3::RegularWifiMac::GetErpSupported () const protected
Return whether the device supports ERP.
Returns
true if ERP is supported, false otherwise
Definition at line 573 of file regular-wifi-mac.cc.
References m_erpSupported.
Referenced by ns3::StaWifiMac::GetCapabilities(), ns3::ApWifiMac::GetErpInformation(), ns3::ApWifiMac::GetShortPreambleEnabled(), ns3::ApWifiMac::GetShortSlotTimeEnabled(), ns3::ApWifiMac::SendAssocResp(), ns3::ApWifiMac::SendOneBeacon(), ns3::ApWifiMac::SendProbeResp(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), ns3::StaWifiMac::UpdateApInfoFromBeacon(), and ns3::StaWifiMac::UpdateApInfoFromProbeResp().
GetExtendedCapabilities()
ExtendedCapabilities ns3::RegularWifiMac::GetExtendedCapabilities (void) const
Return the extended capabilities of the device.
Returns
the extended capabilities that we support
Definition at line 147 of file regular-wifi-mac.cc.
References GetHtSupported(), GetVhtSupported(), NS_LOG_FUNCTION, ns3::ExtendedCapabilities::SetHtSupported(), and ns3::ExtendedCapabilities::SetVhtSupported().
Referenced by ns3::StaWifiMac::SendAssociationRequest(), ns3::ApWifiMac::SendAssocResp(), ns3::ApWifiMac::SendOneBeacon(), ns3::StaWifiMac::SendProbeRequest(), and ns3::ApWifiMac::SendProbeResp().
GetHeCapabilities()
HeCapabilities ns3::RegularWifiMac::GetHeCapabilities (void) const
Return the HE capabilities of the device.
Returns
the HE capabilities that we support
Definition at line 307 of file regular-wifi-mac.cc.
References ns3::WifiPhy::GetChannelWidth(), ns3::WifiMac::GetHeConfiguration(), GetHeSupported(), ns3::WifiMac::GetHtConfiguration(), ns3::WifiPhy::GetMaxSupportedTxSpatialStreams(), ns3::WifiPhy::GetMcs(), ns3::WifiMode::GetMcsValue(), ns3::WifiMode::GetModulationClass(), ns3::WifiPhy::GetNMcs(), ns3::WifiPhy::GetPhyBand(), m_beMaxAmpduSize, m_bkMaxAmpduSize, m_phy, m_viMaxAmpduSize, m_voMaxAmpduSize, max, min, ns3::NanoSeconds(), NS_LOG_FUNCTION, ns3::HeCapabilities::SetChannelWidthSet(), ns3::HeCapabilities::SetHeLtfAndGiForHePpdus(), ns3::HeCapabilities::SetHeSupported(), ns3::HeCapabilities::SetHighestMcsSupported(), ns3::HeCapabilities::SetHighestNssSupported(), ns3::HeCapabilities::SetLdpcCodingInPayload(), ns3::HeCapabilities::SetMaxAmpduLength(), ns3::WIFI_MOD_CLASS_HE, ns3::WIFI_PHY_BAND_2_4GHZ, ns3::WIFI_PHY_BAND_5GHZ, and ns3::WIFI_PHY_BAND_6GHZ.
Referenced by ns3::AdhocWifiMac::Enqueue(), ns3::AdhocWifiMac::Receive(), ns3::StaWifiMac::SendAssociationRequest(), ns3::ApWifiMac::SendAssocResp(), ns3::ApWifiMac::SendOneBeacon(), ns3::StaWifiMac::SendProbeRequest(), and ns3::ApWifiMac::SendProbeResp().
GetHeSupported()
bool ns3::RegularWifiMac::GetHeSupported () const protected
Return whether the device supports HE.
Returns
true if HE is supported, false otherwise
Definition at line 563 of file regular-wifi-mac.cc.
References ns3::WifiMac::GetHeConfiguration().
Referenced by ns3::AdhocWifiMac::Enqueue(), GetHeCapabilities(), ns3::ApWifiMac::GetHeOperation(), ns3::AdhocWifiMac::Receive(), ns3::ApWifiMac::Receive(), ns3::StaWifiMac::SendAssociationRequest(), ns3::ApWifiMac::SendAssocResp(), ns3::ApWifiMac::SendOneBeacon(), ns3::StaWifiMac::SendProbeRequest(), ns3::ApWifiMac::SendProbeResp(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetHtCapabilities()
HtCapabilities ns3::RegularWifiMac::GetHtCapabilities (void) const
Return the HT capabilities of the device.
Returns
the HT capabilities that we support
Definition at line 158 of file regular-wifi-mac.cc.
References ns3::WifiPhy::GetChannelWidth(), ns3::WifiMode::GetDataRate(), ns3::WifiMac::GetHtConfiguration(), GetHtSupported(), ns3::WifiPhy::GetMaxSupportedTxSpatialStreams(), ns3::WifiPhy::GetMcs(), ns3::WifiMode::GetMcsValue(), ns3::WifiMode::GetModulationClass(), ns3::WifiPhy::GetNMcs(), m_beMaxAmpduSize, m_beMaxAmsduSize, m_bkMaxAmpduSize, m_bkMaxAmsduSize, m_phy, m_viMaxAmpduSize, m_viMaxAmsduSize, m_voMaxAmpduSize, m_voMaxAmsduSize, max, min, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::HtCapabilities::SetGreenfield(), ns3::HtCapabilities::SetHtSupported(), ns3::HtCapabilities::SetLdpc(), ns3::HtCapabilities::SetLSigProtectionSupport(), ns3::HtCapabilities::SetMaxAmpduLength(), ns3::HtCapabilities::SetMaxAmsduLength(), ns3::HtCapabilities::SetRxHighestSupportedDataRate(), ns3::HtCapabilities::SetRxMcsBitmask(), ns3::HtCapabilities::SetShortGuardInterval20(), ns3::HtCapabilities::SetShortGuardInterval40(), ns3::HtCapabilities::SetSupportedChannelWidth(), ns3::HtCapabilities::SetTxMaxNSpatialStreams(), ns3::HtCapabilities::SetTxMcsSetDefined(), ns3::HtCapabilities::SetTxRxMcsSetUnequal(), ns3::HtCapabilities::SetTxUnequalModulation(), and ns3::WIFI_MOD_CLASS_HT.
Referenced by ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::OcbWifiMac::Receive(), ns3::AdhocWifiMac::Receive(), ns3::StaWifiMac::SendAssociationRequest(), ns3::ApWifiMac::SendAssocResp(), ns3::ApWifiMac::SendOneBeacon(), ns3::StaWifiMac::SendProbeRequest(), and ns3::ApWifiMac::SendProbeResp().
GetHtSupported()
bool ns3::RegularWifiMac::GetHtSupported () const protected
Return whether the device supports HT.
Returns
true if HT is supported, false otherwise
Definition at line 543 of file regular-wifi-mac.cc.
References ns3::WifiMac::GetHtConfiguration().
Referenced by ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), GetExtendedCapabilities(), GetHtCapabilities(), ns3::ApWifiMac::GetHtOperation(), ns3::ApWifiMac::GetSupportedRates(), ns3::StaWifiMac::GetSupportedRates(), ns3::OcbWifiMac::Receive(), ns3::AdhocWifiMac::Receive(), ns3::ApWifiMac::Receive(), ns3::StaWifiMac::SendAssociationRequest(), ns3::ApWifiMac::SendAssocResp(), ns3::ApWifiMac::SendOneBeacon(), ns3::StaWifiMac::SendProbeRequest(), ns3::ApWifiMac::SendProbeResp(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetQosSupported()
bool ns3::RegularWifiMac::GetQosSupported () const protected
Return whether the device supports QoS.
Returns
true if QoS is supported, false otherwise
Definition at line 537 of file regular-wifi-mac.cc.
References m_qosSupported.
Referenced by ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::StaWifiMac::Enqueue(), ns3::ApWifiMac::ForwardDown(), ns3::ApWifiMac::GetEdcaParameterSet(), GetTypeId(), ns3::ApWifiMac::SendAssocResp(), ns3::ApWifiMac::SendOneBeacon(), ns3::ApWifiMac::SendProbeResp(), ns3::OcbWifiMac::SendVsc(), ns3::InfrastructureWifiMac::SetPcfSupported(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetShortSlotTimeSupported()
bool ns3::RegularWifiMac::GetShortSlotTimeSupported (void) const virtual
Returns
whether the device supports short slot time capability.
Implements ns3::WifiMac.
Definition at line 662 of file regular-wifi-mac.cc.
References m_shortSlotTimeSupported.
Referenced by ns3::StaWifiMac::GetCapabilities(), ns3::ApWifiMac::GetShortSlotTimeEnabled(), and GetTypeId().
GetSsid()
Ssid ns3::RegularWifiMac::GetSsid (void) const virtual
Returns
the SSID which this MAC layer is going to try to stay in.
Implements ns3::WifiMac.
Definition at line 630 of file regular-wifi-mac.cc.
References m_ssid.
Referenced by ns3::OcbWifiMac::GetSsid(), ns3::MeshWifiInterfaceMac::Receive(), ns3::ApWifiMac::Receive(), ns3::StaWifiMac::Receive(), ns3::StaWifiMac::SendAssociationRequest(), ns3::MeshWifiInterfaceMac::SendBeacon(), ns3::ApWifiMac::SendOneBeacon(), ns3::StaWifiMac::SendProbeRequest(), and ns3::ApWifiMac::SendProbeResp().
GetTxop()
Ptr< Txop > ns3::RegularWifiMac::GetTxop (void) const protected
Accessor for the DCF object.
Returns
a smart pointer to Txop
Definition at line 454 of file regular-wifi-mac.cc.
References m_txop.
Referenced by ns3::OcbWifiMac::ConfigureEdca(), and GetTypeId().
GetTypeId()
TypeId ns3::RegularWifiMac::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 865 of file regular-wifi-mac.cc.
References GetBEQueue(), GetBKQueue(), GetQosSupported(), GetShortSlotTimeSupported(), GetTxop(), GetVIQueue(), GetVOQueue(), m_beMaxAmpduSize, m_beMaxAmsduSize, m_bkMaxAmpduSize, m_bkMaxAmsduSize, m_txErrCallback, m_txOkCallback, m_viMaxAmpduSize, m_viMaxAmsduSize, m_voMaxAmpduSize, m_voMaxAmsduSize, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakePointerAccessor(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), SetBeBlockAckInactivityTimeout(), SetBeBlockAckThreshold(), SetBkBlockAckInactivityTimeout(), SetBkBlockAckThreshold(), SetCtsToSelfSupported(), ns3::TypeId::SetParent(), SetQosSupported(), SetShortSlotTimeSupported(), SetViBlockAckInactivityTimeout(), SetViBlockAckThreshold(), SetVoBlockAckInactivityTimeout(), and SetVoBlockAckThreshold().
GetVhtCapabilities()
VhtCapabilities ns3::RegularWifiMac::GetVhtCapabilities (void) const
Return the VHT capabilities of the device.
Returns
the VHT capabilities that we support
Definition at line 221 of file regular-wifi-mac.cc.
References ns3::WifiPhy::GetChannelWidth(), ns3::WifiMode::GetDataRate(), ns3::WifiMac::GetHtConfiguration(), ns3::WifiPhy::GetMaxSupportedRxSpatialStreams(), ns3::WifiPhy::GetMaxSupportedTxSpatialStreams(), ns3::WifiPhy::GetMcs(), ns3::WifiMode::GetMcsValue(), ns3::WifiMode::GetModulationClass(), ns3::WifiPhy::GetNMcs(), ns3::WifiMac::GetVhtConfiguration(), GetVhtSupported(), ns3::WifiMode::IsAllowed(), m_beMaxAmpduSize, m_beMaxAmsduSize, m_bkMaxAmpduSize, m_bkMaxAmsduSize, m_phy, m_viMaxAmpduSize, m_viMaxAmsduSize, m_voMaxAmpduSize, m_voMaxAmsduSize, max, min, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::VhtCapabilities::SetMaxAmpduLength(), ns3::VhtCapabilities::SetMaxMpduLength(), ns3::VhtCapabilities::SetRxHighestSupportedLgiDataRate(), ns3::VhtCapabilities::SetRxLdpc(), ns3::VhtCapabilities::SetRxMcsMap(), ns3::VhtCapabilities::SetRxStbc(), ns3::VhtCapabilities::SetShortGuardIntervalFor160Mhz(), ns3::VhtCapabilities::SetShortGuardIntervalFor80Mhz(), ns3::VhtCapabilities::SetSupportedChannelWidthSet(), ns3::VhtCapabilities::SetTxHighestSupportedLgiDataRate(), ns3::VhtCapabilities::SetTxMcsMap(), ns3::VhtCapabilities::SetTxStbc(), ns3::VhtCapabilities::SetVhtSupported(), and ns3::WIFI_MOD_CLASS_VHT.
Referenced by ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::OcbWifiMac::Receive(), ns3::AdhocWifiMac::Receive(), ns3::StaWifiMac::SendAssociationRequest(), ns3::ApWifiMac::SendAssocResp(), ns3::ApWifiMac::SendOneBeacon(), ns3::StaWifiMac::SendProbeRequest(), and ns3::ApWifiMac::SendProbeResp().
GetVhtSupported()
bool ns3::RegularWifiMac::GetVhtSupported () const protected
Return whether the device supports VHT.
Returns
true if VHT is supported, false otherwise
Definition at line 553 of file regular-wifi-mac.cc.
References ns3::WifiMac::GetVhtConfiguration().
Referenced by ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), GetExtendedCapabilities(), GetVhtCapabilities(), ns3::ApWifiMac::GetVhtOperation(), ns3::OcbWifiMac::Receive(), ns3::AdhocWifiMac::Receive(), ns3::ApWifiMac::Receive(), ns3::StaWifiMac::SendAssociationRequest(), ns3::ApWifiMac::SendAssocResp(), ns3::ApWifiMac::SendOneBeacon(), ns3::StaWifiMac::SendProbeRequest(), ns3::ApWifiMac::SendProbeResp(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetVIQueue()
Ptr< QosTxop > ns3::RegularWifiMac::GetVIQueue (void) const protected
Accessor for the AC_VI channel access function.
Returns
a smart pointer to QosTxop
Definition at line 466 of file regular-wifi-mac.cc.
References ns3::AC_VI, and m_edca.
Referenced by ns3::OcbWifiMac::ConfigureEdca(), TwoLevelAggregationTest::DoRun(), GetTypeId(), SetViBlockAckInactivityTimeout(), and SetViBlockAckThreshold().
GetVOQueue()
Ptr< QosTxop > ns3::RegularWifiMac::GetVOQueue (void) const protected
Accessor for the AC_VO channel access function.
Returns
a smart pointer to QosTxop
Definition at line 460 of file regular-wifi-mac.cc.
References ns3::AC_VO, and m_edca.
Referenced by ns3::OcbWifiMac::ConfigureEdca(), GetTypeId(), SetVoBlockAckInactivityTimeout(), and SetVoBlockAckThreshold().
GetWifiPhy()
Ptr< WifiPhy > ns3::RegularWifiMac::GetWifiPhy (void) const virtual
Returns
the physical layer attached to this MAC
Implements ns3::WifiMac.
Definition at line 493 of file regular-wifi-mac.cc.
References m_phy, and NS_LOG_FUNCTION.
GetWifiRemoteStationManager()
Ptr< WifiRemoteStationManager > ns3::RegularWifiMac::GetWifiRemoteStationManager (void) const virtual
Returns
the station manager attached to this MAC.
Implements ns3::WifiMac.
Definition at line 141 of file regular-wifi-mac.cc.
References m_stationManager.
operator=()
RegularWifiMac& ns3::RegularWifiMac::operator= (const RegularWifiMac & mac) private
assignment operator
Parameters
mac the RegularWifiMac to assign
Returns
the assigned value
Receive()
void ns3::RegularWifiMac::Receive (Ptr< WifiMacQueueItem > mpdu) protected virtual
This method acts as the MacRxMiddle receive callback and is invoked to notify us that a frame has been received.
The implementation is intended to capture logic that is going to be common to all (or most) derived classes. Specifically, handling of Block Ack management frames is dealt with here.
This method will need, however, to be overridden by derived classes so that they can perform their data handling before invoking the base version.
Parameters
mpdu the MPDU that has been received.
Reimplemented in ns3::StaWifiMac, ns3::ApWifiMac, ns3::AdhocWifiMac, ns3::OcbWifiMac, and ns3::MeshWifiInterfaceMac.
Definition at line 693 of file regular-wifi-mac.cc.
References ns3::WifiActionHeader::BLOCK_ACK, ns3::WifiActionHeader::BLOCK_ACK_ADDBA_REQUEST, ns3::WifiActionHeader::BLOCK_ACK_ADDBA_RESPONSE, ns3::WifiActionHeader::BLOCK_ACK_DELBA, ns3::WifiActionHeader::ActionValue::blockAck, ns3::WifiActionHeader::GetAction(), ns3::WifiMacHeader::GetAddr1(), ns3::WifiMacHeader::GetAddr2(), GetAddress(), ns3::WifiActionHeader::GetCategory(), ns3::MgtAddBaResponseHeader::GetTid(), ns3::MgtDelBaHeader::GetTid(), ns3::WifiMacHeader::GetType(), ns3::WifiMacHeader::IsAction(), ns3::MgtDelBaHeader::IsByOriginator(), ns3::WifiMacHeader::IsMgt(), m_edca, m_low, m_qosSupported, NS_ASSERT, NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::QosUtilsMapTidToAc(), ns3::Packet::RemoveHeader(), and SendAddBaResponse().
Referenced by RegularWifiMac(), ns3::OcbWifiMac::Receive(), ns3::AdhocWifiMac::Receive(), ns3::ApWifiMac::Receive(), and ns3::StaWifiMac::Receive().
ResetWifiPhy()
void ns3::RegularWifiMac::ResetWifiPhy (void) virtual
Remove currently attached WifiPhy device from this MAC.
Implements ns3::WifiMac.
Definition at line 500 of file regular-wifi-mac.cc.
References m_channelAccessManager, m_low, m_phy, NS_LOG_FUNCTION, and ns3::ChannelAccessManager::RemovePhyListener().
Referenced by ns3::DefaultChannelScheduler::SwitchToNextChannel().
SendAddBaResponse()
void ns3::RegularWifiMac::SendAddBaResponse (const MgtAddBaRequestHeader * reqHdr, Mac48Address originator) protected
This method can be called to accept a received ADDBA Request.
An ADDBA Response will be constructed and queued for transmission.
Parameters
reqHdr a pointer to the received ADDBA Request header.
originator the MAC address of the originator.
Definition at line 804 of file regular-wifi-mac.cc.
References ns3::Packet::AddHeader(), ns3::WifiActionHeader::BLOCK_ACK, ns3::WifiActionHeader::BLOCK_ACK_ADDBA_RESPONSE, ns3::WifiActionHeader::ActionValue::blockAck, GetAddress(), GetBssid(), ns3::WifiMac::GetHeConfiguration(), ns3::MgtAddBaRequestHeader::GetStartingSequence(), ns3::MgtAddBaRequestHeader::GetTid(), ns3::MgtAddBaRequestHeader::GetTimeout(), ns3::MgtAddBaRequestHeader::IsAmsduSupported(), ns3::MgtAddBaRequestHeader::IsImmediateBlockAck(), m_edca, m_low, NS_LOG_FUNCTION, ns3::QosUtilsMapTidToAc(), ns3::WifiActionHeader::SetAction(), ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetAddr2(), ns3::WifiMacHeader::SetAddr3(), ns3::MgtAddBaResponseHeader::SetAmsduSupport(), ns3::MgtAddBaResponseHeader::SetBufferSize(), ns3::MgtAddBaResponseHeader::SetDelayedBlockAck(), ns3::WifiMacHeader::SetDsNotFrom(), ns3::WifiMacHeader::SetDsNotTo(), ns3::MgtAddBaResponseHeader::SetImmediateBlockAck(), ns3::MgtAddBaResponseHeader::SetStatusCode(), ns3::StatusCode::SetSuccess(), ns3::MgtAddBaResponseHeader::SetTid(), ns3::MgtAddBaResponseHeader::SetTimeout(), ns3::WifiMacHeader::SetType(), and ns3::WIFI_MAC_MGT_ACTION.
Referenced by Receive().
SetAddress()
void ns3::RegularWifiMac::SetAddress (Mac48Address address) virtual
Parameters
address the current address of this MAC layer.
Implements ns3::WifiMac.
Definition at line 610 of file regular-wifi-mac.cc.
References first::address, m_low, and NS_LOG_FUNCTION.
Referenced by AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), HeAggregationTest::DoRunSubTest(), ns3::AdhocWifiMac::SetAddress(), and ns3::ApWifiMac::SetAddress().
SetBeBlockAckInactivityTimeout()
void ns3::RegularWifiMac::SetBeBlockAckInactivityTimeout (uint16_t timeout) private
Set BE block ack inactivity timeout.
Parameters
timeout the BE block ack inactivity timeout.
Definition at line 408 of file regular-wifi-mac.cc.
References GetBEQueue(), NS_LOG_FUNCTION, ns3::QosTxop::SetBlockAckInactivityTimeout(), and timeout.
Referenced by GetTypeId().
SetBeBlockAckThreshold()
void ns3::RegularWifiMac::SetBeBlockAckThreshold (uint8_t threshold) private
Set the block ack threshold for AC_BE.
Parameters
threshold the block ack threshold for AC_BE.
Definition at line 380 of file regular-wifi-mac.cc.
References GetBEQueue(), NS_LOG_FUNCTION, and ns3::QosTxop::SetBlockAckThreshold().
Referenced by GetTypeId().
SetBkBlockAckInactivityTimeout()
void ns3::RegularWifiMac::SetBkBlockAckInactivityTimeout (uint16_t timeout) private
Set BK block ack inactivity timeout.
Parameters
timeout the BK block ack inactivity timeout.
Definition at line 415 of file regular-wifi-mac.cc.
References GetBKQueue(), NS_LOG_FUNCTION, ns3::QosTxop::SetBlockAckInactivityTimeout(), and timeout.
Referenced by GetTypeId().
SetBkBlockAckThreshold()
void ns3::RegularWifiMac::SetBkBlockAckThreshold (uint8_t threshold) private
Set the block ack threshold for AC_BK.
Parameters
threshold the block ack threshold for AC_BK.
Definition at line 387 of file regular-wifi-mac.cc.
References GetBKQueue(), NS_LOG_FUNCTION, and ns3::QosTxop::SetBlockAckThreshold().
Referenced by GetTypeId().
SetBssid()
void ns3::RegularWifiMac::SetBssid (Mac48Address bssid)
Parameters
bssid the BSSID of the network that this device belongs to.
Definition at line 636 of file regular-wifi-mac.cc.
References m_low, and NS_LOG_FUNCTION.
Referenced by ns3::OcbWifiMac::OcbWifiMac(), ns3::AdhocWifiMac::SetAddress(), ns3::ApWifiMac::SetAddress(), ns3::StaWifiMac::UpdateApInfoFromBeacon(), and ns3::StaWifiMac::UpdateApInfoFromProbeResp().
SetCtsToSelfSupported()
void ns3::RegularWifiMac::SetCtsToSelfSupported (bool enable)
Enable or disable CTS-to-self feature.
Parameters
enable true if CTS-to-self is to be supported, false otherwise
Definition at line 603 of file regular-wifi-mac.cc.
References m_low, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetDsssSupported()
void ns3::RegularWifiMac::SetDsssSupported (bool enable) protected
Enable or disable DSSS support for the device.
Parameters
enable whether DSSS is supported
Definition at line 590 of file regular-wifi-mac.cc.
References m_dsssSupported, and NS_LOG_FUNCTION.
Referenced by ConfigureStandard(), and SetErpSupported().
SetErpSupported()
void ns3::RegularWifiMac::SetErpSupported (bool enable) protected
Enable or disable ERP support for the device.
Parameters
enable whether ERP is supported
Definition at line 579 of file regular-wifi-mac.cc.
References m_erpSupported, NS_LOG_FUNCTION, and SetDsssSupported().
Referenced by ConfigureStandard().
SetForwardUpCallback()
void ns3::RegularWifiMac::SetForwardUpCallback (ForwardUpCallback upCallback)
Definition at line 509 of file regular-wifi-mac.cc.
References m_forwardUp, and NS_LOG_FUNCTION.
SetLinkDownCallback()
void ns3::RegularWifiMac::SetLinkDownCallback (Callback< void > linkDown) virtual
Parameters
linkDown the callback to invoke when the link becomes down.
Implements ns3::WifiMac.
Definition at line 523 of file regular-wifi-mac.cc.
References m_linkDown, and NS_LOG_FUNCTION.
Referenced by ns3::OcbWifiMac::SetLinkDownCallback().
SetLinkUpCallback()
void ns3::RegularWifiMac::SetLinkUpCallback (Callback< void > linkUp) virtual
Parameters
linkUp the callback to invoke when the link becomes up.
Implements ns3::WifiMac.
Definition at line 516 of file regular-wifi-mac.cc.
References m_linkUp, and NS_LOG_FUNCTION.
Referenced by ns3::MeshWifiInterfaceMac::SetLinkUpCallback(), ns3::OcbWifiMac::SetLinkUpCallback(), ns3::AdhocWifiMac::SetLinkUpCallback(), and ns3::ApWifiMac::SetLinkUpCallback().
SetPromisc()
void ns3::RegularWifiMac::SetPromisc (void) virtual
Sets the interface in promiscuous mode.
Enables promiscuous mode on the interface. Note that any further filtering on the incoming frame path may affect the overall behavior.
Implements ns3::WifiMac.
Definition at line 649 of file regular-wifi-mac.cc.
References m_low.
SetQosSupported()
void ns3::RegularWifiMac::SetQosSupported (bool enable) protected virtual
Enable or disable QoS support for the device.
Parameters
enable whether QoS is supported
Reimplemented in ns3::InfrastructureWifiMac.
Definition at line 530 of file regular-wifi-mac.cc.
References m_qosSupported, and NS_LOG_FUNCTION.
Referenced by ConfigureStandard(), GetTypeId(), and ns3::InfrastructureWifiMac::SetQosSupported().
SetShortSlotTimeSupported()
void ns3::RegularWifiMac::SetShortSlotTimeSupported (bool enable) virtual
Enable or disable short slot time feature.
Parameters
enable true if short slot time is to be supported, false otherwise
Implements ns3::WifiMac.
Definition at line 655 of file regular-wifi-mac.cc.
References m_shortSlotTimeSupported, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetSsid()
void ns3::RegularWifiMac::SetSsid (Ssid ssid) virtual
Parameters
ssid the current SSID of this MAC layer.
Implements ns3::WifiMac.
Definition at line 623 of file regular-wifi-mac.cc.
References m_ssid, NS_LOG_FUNCTION, and third::ssid.
SetTypeOfStation()
void ns3::RegularWifiMac::SetTypeOfStation (TypeOfStation type) protected
This method is invoked by a subclass to specify what type of station it is implementing.
This is something that the channel access functions (instantiated within this class as QosTxop's) need to know.
Parameters
type the type of station.
Definition at line 444 of file regular-wifi-mac.cc.
References m_edca, and NS_LOG_FUNCTION.
Referenced by ns3::AdhocWifiMac::AdhocWifiMac(), ns3::ApWifiMac::ApWifiMac(), ns3::MeshWifiInterfaceMac::MeshWifiInterfaceMac(), ns3::OcbWifiMac::OcbWifiMac(), and ns3::StaWifiMac::StaWifiMac().
SetupEdcaQueue()
void ns3::RegularWifiMac::SetupEdcaQueue (AcIndex ac) private
This method is a private utility invoked to configure the channel access function for the specified Access Category.
Parameters
ac the Access Category of the queue to initialise.
Definition at line 422 of file regular-wifi-mac.cc.
References ns3::QosTxop::CompleteConfig(), m_channelAccessManager, m_edca, m_low, m_txMiddle, ns3::MakeCallback(), ns3::WifiMac::NotifyTxDrop(), NS_ASSERT, NS_LOG_FUNCTION, ns3::QosTxop::SetAccessCategory(), ns3::Txop::SetChannelAccessManager(), ns3::Txop::SetMacLow(), ns3::Txop::SetTxDroppedCallback(), ns3::Txop::SetTxFailedCallback(), ns3::Txop::SetTxMiddle(), ns3::Txop::SetTxOkCallback(), TxFailed(), and TxOk().
Referenced by RegularWifiMac().
SetViBlockAckInactivityTimeout()
void ns3::RegularWifiMac::SetViBlockAckInactivityTimeout (uint16_t timeout) private
Set VI block ack inactivity timeout.
Parameters
timeout the VI block ack inactivity timeout.
Definition at line 401 of file regular-wifi-mac.cc.
References GetVIQueue(), NS_LOG_FUNCTION, ns3::QosTxop::SetBlockAckInactivityTimeout(), and timeout.
Referenced by GetTypeId().
SetViBlockAckThreshold()
void ns3::RegularWifiMac::SetViBlockAckThreshold (uint8_t threshold) private
Set the block ack threshold for AC_VI.
Parameters
threshold the block ack threshold for AC_VI.
Definition at line 373 of file regular-wifi-mac.cc.
References GetVIQueue(), NS_LOG_FUNCTION, and ns3::QosTxop::SetBlockAckThreshold().
Referenced by GetTypeId().
SetVoBlockAckInactivityTimeout()
void ns3::RegularWifiMac::SetVoBlockAckInactivityTimeout (uint16_t timeout) private
Set VO block ack inactivity timeout.
Parameters
timeout the VO block ack inactivity timeout.
Definition at line 394 of file regular-wifi-mac.cc.
References GetVOQueue(), NS_LOG_FUNCTION, ns3::QosTxop::SetBlockAckInactivityTimeout(), and timeout.
Referenced by GetTypeId().
SetVoBlockAckThreshold()
void ns3::RegularWifiMac::SetVoBlockAckThreshold (uint8_t threshold) private
Set the block ack threshold for AC_VO.
Parameters
threshold the block ack threshold for AC_VO.
Definition at line 366 of file regular-wifi-mac.cc.
References GetVOQueue(), NS_LOG_FUNCTION, and ns3::QosTxop::SetBlockAckThreshold().
Referenced by GetTypeId().
SetWifiPhy()
void ns3::RegularWifiMac::SetWifiPhy (const Ptr< WifiPhy > phy) virtual
Parameters
phy the physical layer attached to this MAC.
Implements ns3::WifiMac.
Reimplemented in ns3::StaWifiMac.
Definition at line 484 of file regular-wifi-mac.cc.
References m_channelAccessManager, m_low, m_phy, NS_LOG_FUNCTION, third::phy, and ns3::ChannelAccessManager::SetupPhyListener().
Referenced by ns3::DefaultChannelScheduler::AssignDefaultCchAccess(), ns3::StaWifiMac::SetWifiPhy(), and ns3::DefaultChannelScheduler::SwitchToNextChannel().
SetWifiRemoteStationManager()
void ns3::RegularWifiMac::SetWifiRemoteStationManager (const Ptr< WifiRemoteStationManager > stationManager) virtual
Parameters
stationManager the station manager attached to this MAC.
Implements ns3::WifiMac.
Reimplemented in ns3::StaWifiMac, and ns3::ApWifiMac.
Definition at line 128 of file regular-wifi-mac.cc.
References m_edca, m_low, m_stationManager, m_txop, NS_LOG_FUNCTION, and ns3::Txop::SetWifiRemoteStationManager().
Referenced by ns3::WaveHelper::Install(), ns3::ApWifiMac::SetWifiRemoteStationManager(), and ns3::StaWifiMac::SetWifiRemoteStationManager().
SupportsSendFrom()
bool ns3::RegularWifiMac::SupportsSendFrom (void) const virtual
Returns
if this MAC supports sending from arbitrary address.
The interface may or may not support sending from arbitrary address. This function returns true if sending from arbitrary address is supported, false otherwise.
Implements ns3::WifiMac.
Reimplemented in ns3::ApWifiMac, and ns3::MeshWifiInterfaceMac.
Definition at line 680 of file regular-wifi-mac.cc.
TxFailed()
void ns3::RegularWifiMac::TxFailed (const WifiMacHeader & hdr) protected virtual
The packet we sent was successfully received by the receiver (i.e.
we did not receive an Ack from the receiver).
Parameters
hdr the header of the packet that we failed to sent
Reimplemented in ns3::ApWifiMac.
Definition at line 1108 of file regular-wifi-mac.cc.
References m_txErrCallback, and NS_LOG_FUNCTION.
Referenced by RegularWifiMac(), SetupEdcaQueue(), and ns3::ApWifiMac::TxFailed().
TxOk()
void ns3::RegularWifiMac::TxOk (const WifiMacHeader & hdr) protected virtual
The packet we sent was successfully received by the receiver (i.e.
we received an Ack from the receiver).
Parameters
hdr the header of the packet that we successfully sent
Reimplemented in ns3::ApWifiMac.
Definition at line 1101 of file regular-wifi-mac.cc.
References m_txOkCallback, and NS_LOG_FUNCTION.
Referenced by RegularWifiMac(), SetupEdcaQueue(), and ns3::ApWifiMac::TxOk().
Member Data Documentation
m_beMaxAmpduSize
uint32_t ns3::RegularWifiMac::m_beMaxAmpduSize private
maximum A-MPDU size for AC_BE (in bytes)
Definition at line 434 of file regular-wifi-mac.h.
Referenced by GetHeCapabilities(), GetHtCapabilities(), GetTypeId(), and GetVhtCapabilities().
m_beMaxAmsduSize
uint16_t ns3::RegularWifiMac::m_beMaxAmsduSize private
maximum A-MSDU size for AC_BE (in bytes)
Definition at line 429 of file regular-wifi-mac.h.
Referenced by GetHtCapabilities(), GetTypeId(), and GetVhtCapabilities().
m_bkMaxAmpduSize
uint32_t ns3::RegularWifiMac::m_bkMaxAmpduSize private
maximum A-MPDU size for AC_BK (in bytes)
Definition at line 435 of file regular-wifi-mac.h.
Referenced by GetHeCapabilities(), GetHtCapabilities(), GetTypeId(), and GetVhtCapabilities().
m_bkMaxAmsduSize
uint16_t ns3::RegularWifiMac::m_bkMaxAmsduSize private
maximum A-MSDU size for AC_BK (in bytes)
Definition at line 430 of file regular-wifi-mac.h.
Referenced by GetHtCapabilities(), GetTypeId(), and GetVhtCapabilities().
m_channelAccessManager
Ptr<ChannelAccessManager> ns3::RegularWifiMac::m_channelAccessManager protected
channel access manager
Definition at line 138 of file regular-wifi-mac.h.
Referenced by ns3::ApWifiMac::ApWifiMac(), RegularWifiMac(), DoDispose(), ns3::OcbWifiMac::EnableForWave(), ns3::OcbWifiMac::MakeVirtualBusy(), ns3::OcbWifiMac::Reset(), ResetWifiPhy(), ns3::OcbWifiMac::Resume(), SetupEdcaQueue(), SetWifiPhy(), ns3::OcbWifiMac::Suspend(), and ns3::MeshWifiInterfaceMac::SwitchFrequencyChannel().
m_dsssSupported
bool ns3::RegularWifiMac::m_dsssSupported private
This Boolean is set true iff this WifiMac is to model 802.11b.
It is exposed through the attribute system.
Definition at line 420 of file regular-wifi-mac.h.
Referenced by ConfigureContentionWindow(), GetDsssSupported(), and SetDsssSupported().
m_edca
EdcaQueues ns3::RegularWifiMac::m_edca protected
This is a map from Access Category index to the corresponding channel access function.
Definition at line 159 of file regular-wifi-mac.h.
Referenced by ns3::OcbWifiMac::CancleTx(), ConfigureContentionWindow(), DoDispose(), DoInitialize(), EnableAggregation(), ns3::OcbWifiMac::EnableForWave(), ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::StaWifiMac::Enqueue(), ns3::MeshWifiInterfaceMac::ForwardDown(), ns3::ApWifiMac::ForwardDown(), GetBEQueue(), GetBKQueue(), ns3::ApWifiMac::GetEdcaParameterSet(), GetVIQueue(), GetVOQueue(), Receive(), SendAddBaResponse(), ns3::MeshWifiInterfaceMac::SendManagementFrame(), ns3::OcbWifiMac::SendVsc(), ns3::StaWifiMac::SetEdcaParameters(), SetTypeOfStation(), SetupEdcaQueue(), and SetWifiRemoteStationManager().
m_erpSupported
bool ns3::RegularWifiMac::m_erpSupported private
This Boolean is set true iff this WifiMac is to model 802.11g.
It is exposed through the attribute system.
Definition at line 415 of file regular-wifi-mac.h.
Referenced by ConfigureContentionWindow(), GetErpSupported(), and SetErpSupported().
m_forwardUp
ForwardUpCallback ns3::RegularWifiMac::m_forwardUp protected
Callback to forward packet up the stack.
Definition at line 143 of file regular-wifi-mac.h.
Referenced by ForwardUp(), and SetForwardUpCallback().
m_linkDown
Callback<void> ns3::RegularWifiMac::m_linkDown protected
Callback when a link is down.
Definition at line 145 of file regular-wifi-mac.h.
Referenced by SetLinkDownCallback(), and ns3::StaWifiMac::TryToEnsureAssociated().
m_linkUp
Callback<void> ns3::RegularWifiMac::m_linkUp protected
Callback when a link is up.
Definition at line 144 of file regular-wifi-mac.h.
Referenced by ns3::StaWifiMac::Receive(), and SetLinkUpCallback().
m_low
Ptr<MacLow> ns3::RegularWifiMac::m_low protected
MacLow (RTS, CTS, Data, Ack etc.)
Definition at line 137 of file regular-wifi-mac.h.
Referenced by ns3::ApWifiMac::ApWifiMac(), RegularWifiMac(), DisableAggregation(), DoDispose(), EnableAggregation(), ns3::OcbWifiMac::EnableForWave(), ns3::MeshWifiInterfaceMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::ApWifiMac::Enqueue(), ns3::StaWifiMac::Enqueue(), GetAddress(), ns3::ApWifiMac::GetBeaconInterval(), GetBssid(), ns3::ApWifiMac::GetCfpMaxDuration(), Receive(), ns3::StaWifiMac::Receive(), ns3::OcbWifiMac::Reset(), ResetWifiPhy(), SendAddBaResponse(), ns3::ApWifiMac::SendNextCfFrame(), SetAddress(), ns3::ApWifiMac::SetBeaconInterval(), SetBssid(), ns3::ApWifiMac::SetCfpMaxDuration(), SetCtsToSelfSupported(), SetPromisc(), SetupEdcaQueue(), SetWifiPhy(), SetWifiRemoteStationManager(), and ns3::OcbWifiMac::Suspend().
m_phy
Ptr<WifiPhy> ns3::RegularWifiMac::m_phy protected
Wifi PHY.
Definition at line 139 of file regular-wifi-mac.h.
Referenced by ns3::MeshWifiInterfaceMac::CheckSupportedRates(), DoDispose(), ns3::MeshWifiInterfaceMac::ForwardDown(), ns3::StaWifiMac::GetCapabilities(), ns3::ApWifiMac::GetDsssParameterSet(), ns3::MeshWifiInterfaceMac::GetFrequencyChannel(), GetHeCapabilities(), ns3::ApWifiMac::GetHeOperation(), GetHtCapabilities(), ns3::ApWifiMac::GetHtOperation(), ns3::ApWifiMac::GetShortPreambleEnabled(), ns3::MeshWifiInterfaceMac::GetSupportedRates(), ns3::ApWifiMac::GetSupportedRates(), ns3::StaWifiMac::GetSupportedRates(), GetVhtCapabilities(), ns3::ApWifiMac::GetVhtOperation(), ns3::ApWifiMac::GetVhtOperationalChannelWidth(), GetWifiPhy(), ns3::MeshWifiInterfaceMac::Receive(), ns3::ApWifiMac::Receive(), ns3::StaWifiMac::Receive(), ResetWifiPhy(), ns3::ApWifiMac::SendOneBeacon(), SetWifiPhy(), ns3::StaWifiMac::SetWifiPhy(), ns3::MeshWifiInterfaceMac::SwitchFrequencyChannel(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), ns3::StaWifiMac::UpdateApInfoFromBeacon(), and ns3::StaWifiMac::UpdateApInfoFromProbeResp().
m_qosSupported
bool ns3::RegularWifiMac::m_qosSupported private
This Boolean is set true iff this WifiMac is to model 802.11e/WMM style Quality of Service.
It is exposed through the attribute system.
At the moment, this flag is the sole selection between QoS and non-QoS operation for the STA (whether IBSS, AP, or non-AP). Ultimately, we will want a QoS-enabled STA to be able to fall back to non-QoS operation with a non-QoS peer. This'll require further intelligence - i.e., per-association QoS state. Having a big switch seems like a good intermediate stage, however.
Definition at line 410 of file regular-wifi-mac.h.
Referenced by GetQosSupported(), Receive(), and SetQosSupported().
m_rxMiddle
Ptr<MacRxMiddle> ns3::RegularWifiMac::m_rxMiddle protected
RX middle (defragmentation etc.)
Definition at line 135 of file regular-wifi-mac.h.
Referenced by ns3::ApWifiMac::ApWifiMac(), RegularWifiMac(), DoDispose(), and ns3::OcbWifiMac::EnableForWave().
m_shortSlotTimeSupported
bool ns3::RegularWifiMac::m_shortSlotTimeSupported private
flag whether short slot time is supported
Definition at line 440 of file regular-wifi-mac.h.
Referenced by GetShortSlotTimeSupported(), and SetShortSlotTimeSupported().
m_ssid
Ssid ns3::RegularWifiMac::m_ssid protected
Service Set ID (SSID)
Definition at line 147 of file regular-wifi-mac.h.
Referenced by GetSsid(), and SetSsid().
m_stationManager
Ptr<WifiRemoteStationManager> ns3::RegularWifiMac::m_stationManager protected
Remote station manager (rate control, RTS/CTS/fragmentation thresholds etc.)
Definition at line 141 of file regular-wifi-mac.h.
Referenced by ns3::MeshWifiInterfaceMac::CheckSupportedRates(), DoDispose(), ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::ApWifiMac::Enqueue(), ns3::MeshWifiInterfaceMac::ForwardDown(), ns3::ApWifiMac::GetHeOperation(), ns3::ApWifiMac::GetHtOperation(), ns3::ApWifiMac::GetShortPreambleEnabled(), ns3::ApWifiMac::GetShortSlotTimeEnabled(), ns3::MeshWifiInterfaceMac::GetSupportedRates(), ns3::ApWifiMac::GetSupportedRates(), ns3::ApWifiMac::GetUseNonErpProtection(), ns3::ApWifiMac::GetVhtOperation(), ns3::ApWifiMac::GetVhtOperationalChannelWidth(), GetWifiRemoteStationManager(), ns3::ApWifiMac::IsNonGfHtStasPresent(), ns3::MeshWifiInterfaceMac::Receive(), ns3::OcbWifiMac::Receive(), ns3::AdhocWifiMac::Receive(), ns3::ApWifiMac::Receive(), ns3::ApWifiMac::SendOneBeacon(), ns3::ApWifiMac::SendProbeResp(), ns3::InfrastructureWifiMac::SetPcfSupported(), ns3::ApWifiMac::SetWifiRemoteStationManager(), SetWifiRemoteStationManager(), ns3::StaWifiMac::SetWifiRemoteStationManager(), ns3::ApWifiMac::TxFailed(), ns3::ApWifiMac::TxOk(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), ns3::StaWifiMac::UpdateApInfoFromBeacon(), and ns3::StaWifiMac::UpdateApInfoFromProbeResp().
m_txErrCallback
TracedCallback<const WifiMacHeader &> ns3::RegularWifiMac::m_txErrCallback private
transmit error callback
Definition at line 438 of file regular-wifi-mac.h.
Referenced by GetTypeId(), and TxFailed().
m_txMiddle
Ptr<MacTxMiddle> ns3::RegularWifiMac::m_txMiddle protected
TX middle (aggregation etc.)
Definition at line 136 of file regular-wifi-mac.h.
Referenced by ns3::ApWifiMac::ApWifiMac(), RegularWifiMac(), DoDispose(), AmpduAggregationTest::DoRun(), HeAggregationTest::DoRunSubTest(), and SetupEdcaQueue().
m_txOkCallback
TracedCallback<const WifiMacHeader &> ns3::RegularWifiMac::m_txOkCallback private
transmit OK callback
Definition at line 437 of file regular-wifi-mac.h.
Referenced by GetTypeId(), and TxOk().
m_txop
Ptr<Txop> ns3::RegularWifiMac::m_txop protected
This holds a pointer to the TXOP instance for this WifiMac - used for transmission of frames to non-QoS peers.
Definition at line 151 of file regular-wifi-mac.h.
Referenced by RegularWifiMac(), ConfigureContentionWindow(), ns3::MeshWifiInterfaceMac::ConfigureStandard(), DoDispose(), DoInitialize(), ns3::OcbWifiMac::EnableForWave(), ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::StaWifiMac::Enqueue(), ns3::ApWifiMac::ForwardDown(), GetTxop(), ns3::StaWifiMac::SendAssociationRequest(), ns3::ApWifiMac::SendAssocResp(), ns3::MeshWifiInterfaceMac::SendBeacon(), ns3::ApWifiMac::SendCfEnd(), ns3::ApWifiMac::SendCfPoll(), ns3::StaWifiMac::SendCfPollResponse(), ns3::ApWifiMac::SendNextCfFrame(), ns3::StaWifiMac::SendProbeRequest(), ns3::ApWifiMac::SendProbeResp(), ns3::OcbWifiMac::SendVsc(), and SetWifiRemoteStationManager().
m_viMaxAmpduSize
uint32_t ns3::RegularWifiMac::m_viMaxAmpduSize private
maximum A-MPDU size for AC_VI (in bytes)
Definition at line 433 of file regular-wifi-mac.h.
Referenced by GetHeCapabilities(), GetHtCapabilities(), GetTypeId(), and GetVhtCapabilities().
m_viMaxAmsduSize
uint16_t ns3::RegularWifiMac::m_viMaxAmsduSize private
maximum A-MSDU size for AC_VI (in bytes)
Definition at line 428 of file regular-wifi-mac.h.
Referenced by GetHtCapabilities(), GetTypeId(), and GetVhtCapabilities().
m_voMaxAmpduSize
uint32_t ns3::RegularWifiMac::m_voMaxAmpduSize private
maximum A-MPDU size for AC_VO (in bytes)
Definition at line 432 of file regular-wifi-mac.h.
Referenced by GetHeCapabilities(), GetHtCapabilities(), GetTypeId(), and GetVhtCapabilities().
m_voMaxAmsduSize
uint16_t ns3::RegularWifiMac::m_voMaxAmsduSize private
maximum A-MSDU size for AC_VO (in bytes)
Definition at line 427 of file regular-wifi-mac.h.
Referenced by GetHtCapabilities(), GetTypeId(), and GetVhtCapabilities().
The documentation for this class was generated from the following files:
src/wifi/model/regular-wifi-mac.h
src/wifi/model/regular-wifi-mac.cc