ns-3: ns3::LteRlcSm Class Reference
ns3::LteRlcSm Class Reference
LTE_RLC Saturation Mode (SM): simulation-specific mode used for experiments that do not need to consider the layers above the LTE_RLC.
#include "lte-rlc.h"
Public Member Functions
LteRlcSm ()
virtual ~LteRlcSm ()
virtual void DoDispose ()
Destructor implementation.
virtual void DoInitialize ()
Initialize() implementation.
virtual void DoNotifyHarqDeliveryFailure ()
Notify HARQ delivery failure.
virtual void DoNotifyTxOpportunity (LteMacSapUser::TxOpportunityParameters txOpParams)
Notify transmit opportunity.
virtual void DoReceivePdu (LteMacSapUser::ReceivePduParameters rxPduParams)
Receive PDU function.
virtual void DoTransmitPdcpPdu (Ptr< Packet > p)
Transmit PDCP PDU.
Public Member Functions inherited from ns3::LteRlc
LteRlc ()
virtual ~LteRlc ()
LteMacSapUser * GetLteMacSapUser ()
LteRlcSapProvider * GetLteRlcSapProvider ()
void SetLcId (uint8_t lcId)
void SetLteMacSapProvider (LteMacSapProvider *s)
void SetLteRlcSapUser (LteRlcSapUser *s)
void SetRnti (uint16_t rnti)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::LteRlc
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void ReportBufferStatus ()
Report buffer status.
Additional Inherited Members
Public Types inherited from ns3::LteRlc
typedef void(* NotifyTxTracedCallback) (uint16_t rnti, uint8_t lcid, uint32_t bytes)
TracedCallback signature for NotifyTxOpportunity events.
typedef void(* ReceiveTracedCallback) (uint16_t rnti, uint8_t lcid, uint32_t bytes, uint64_t delay)
TracedCallback signature for.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::LteRlc
uint8_t m_lcid
LCID.
LteMacSapProvider * m_macSapProvider
MAC SAP provider.
LteMacSapUser * m_macSapUser
MAC SAP user.
LteRlcSapProvider * m_rlcSapProvider
RLC SAP provider.
LteRlcSapUser * m_rlcSapUser
RLC SAP user.
uint16_t m_rnti
RNTI.
TracedCallback< uint16_t, uint8_t, uint32_t, uint64_t > m_rxPdu
Used to inform of a PDU reception from the MAC SAP user.
TracedCallback< uint16_t, uint8_t, uint32_t > m_txPdu
Used to inform of a PDU delivery to the MAC SAP provider.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
LTE_RLC Saturation Mode (SM): simulation-specific mode used for experiments that do not need to consider the layers above the LTE_RLC.
The LTE_RLC SM, unlike the standard LTE_RLC modes, it does not provide data delivery services to upper layers; rather, it just generates a new LTE_RLC PDU whenever the MAC notifies a transmission opportunity.
Config Paths
ns3::LteRlcSm is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteEnbNetDevice/LteEnbRrc/UeMap/[i]/DataRadioBearerMap/[i]/LteRlc/$ns3::LteRlcSm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteEnbNetDevice/LteEnbRrc/UeMap/[i]/Srb0/LteRlc/$ns3::LteRlcSm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteEnbNetDevice/LteEnbRrc/UeMap/[i]/Srb1/LteRlc/$ns3::LteRlcSm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteUeNetDevice/LteUeRrc/DataRadioBearerMap/[i]/LteRlc/$ns3::LteRlcSm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteUeNetDevice/LteUeRrc/Srb0/LteRlc/$ns3::LteRlcSm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteUeNetDevice/LteUeRrc/Srb1/LteRlc/$ns3::LteRlcSm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteEnbNetDevice/LteEnbRrc/UeMap/[i]/DataRadioBearerMap/[i]/LteRlc/$ns3::LteRlcSm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteEnbNetDevice/LteEnbRrc/UeMap/[i]/Srb0/LteRlc/$ns3::LteRlcSm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteEnbNetDevice/LteEnbRrc/UeMap/[i]/Srb1/LteRlc/$ns3::LteRlcSm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteUeNetDevice/LteUeRrc/DataRadioBearerMap/[i]/LteRlc/$ns3::LteRlcSm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteUeNetDevice/LteUeRrc/Srb0/LteRlc/$ns3::LteRlcSm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteUeNetDevice/LteUeRrc/Srb1/LteRlc/$ns3::LteRlcSm"
No Attributes are defined for this type.
No TraceSources are defined for this type.
TraceSources defined in parent class ns3::LteRlc
TxPDU: PDU transmission notified to the MAC.
Callback signature: ns3::LteRlc::NotifyTxTracedCallback
RxPDU: PDU received.
Callback signature: ns3::LteRlc::ReceiveTracedCallback
Size of this type is 120 bytes (on a 64-bit architecture).
Definition at line 192 of file lte-rlc.h.
Constructor & Destructor Documentation
LteRlcSm()
ns3::LteRlcSm::LteRlcSm ()
Definition at line 175 of file lte-rlc.cc.
References NS_LOG_FUNCTION.
~LteRlcSm()
ns3::LteRlcSm::~LteRlcSm () virtual
Definition at line 180 of file lte-rlc.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::LteRlcSm::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::LteRlc.
Definition at line 204 of file lte-rlc.cc.
References ns3::LteRlc::DoDispose(), and NS_LOG_FUNCTION.
DoInitialize()
void ns3::LteRlcSm::DoInitialize (void) virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 197 of file lte-rlc.cc.
References NS_LOG_FUNCTION, and ReportBufferStatus().
DoNotifyHarqDeliveryFailure()
void ns3::LteRlcSm::DoNotifyHarqDeliveryFailure () virtual
Notify HARQ delivery failure.
Implements ns3::LteRlc.
Definition at line 265 of file lte-rlc.cc.
References NS_LOG_FUNCTION.
DoNotifyTxOpportunity()
void ns3::LteRlcSm::DoNotifyTxOpportunity (LteMacSapUser::TxOpportunityParameters params) virtual
Notify transmit opportunity.
Parameters
params LteMacSapUser::TxOpportunityParameters
For RLC SM, the packets are not passed to the upper layers, therefore, in the absence of an header we can safely byte tag the entire packet.
Implements ns3::LteRlc.
Definition at line 234 of file lte-rlc.cc.
References ns3::Packet::AddByteTag(), ns3::LteMacSapUser::TxOpportunityParameters::bytes, ns3::LteMacSapProvider::TransmitPduParameters::componentCarrierId, ns3::LteMacSapUser::TxOpportunityParameters::componentCarrierId, ns3::Packet::GetSize(), ns3::LteMacSapUser::TxOpportunityParameters::harqId, ns3::LteMacSapProvider::TransmitPduParameters::harqProcessId, ns3::LteMacSapProvider::TransmitPduParameters::layer, ns3::LteMacSapUser::TxOpportunityParameters::layer, ns3::LteMacSapProvider::TransmitPduParameters::lcid, ns3::LteRlc::m_lcid, ns3::LteRlc::m_macSapProvider, ns3::LteRlc::m_rnti, ns3::LteRlc::m_txPdu, ns3::Simulator::Now(), NS_ABORT_MSG_UNLESS, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::LteMacSapProvider::TransmitPduParameters::pdu, ReportBufferStatus(), ns3::LteMacSapProvider::TransmitPduParameters::rnti, and ns3::LteMacSapProvider::TransmitPdu().
DoReceivePdu()
void ns3::LteRlcSm::DoReceivePdu (LteMacSapUser::ReceivePduParameters params) virtual
Receive PDU function.
Parameters
params the LteMacSapUser::ReceivePduParameters
Implements ns3::LteRlc.
Definition at line 217 of file lte-rlc.cc.
References ns3::Time::As(), ns3::Packet::FindFirstMatchingByteTag(), ns3::Time::GetNanoSeconds(), ns3::RlcTag::GetSenderTimestamp(), ns3::Packet::GetSize(), ns3::LteRlc::m_lcid, ns3::LteRlc::m_rnti, ns3::LteRlc::m_rxPdu, ns3::Simulator::Now(), ns3::Time::NS, NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, and ns3::LteMacSapUser::ReceivePduParameters::p.
DoTransmitPdcpPdu()
void ns3::LteRlcSm::DoTransmitPdcpPdu (Ptr< Packet > p) virtual
Transmit PDCP PDU.
Todo:
MRE What is the sense to duplicate all the interfaces here???
Parameters
p packet
Implements ns3::LteRlc.
Definition at line 211 of file lte-rlc.cc.
References NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::LteRlcSm::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 186 of file lte-rlc.cc.
References ns3::TypeId::SetParent().
Referenced by ns3::LteUeRrc::ApplyRadioResourceConfigDedicated(), ns3::LteEnbRrc::GetRlcType(), and ns3::UeManager::SetupDataRadioBearer().
ReportBufferStatus()
void ns3::LteRlcSm::ReportBufferStatus () private
Report buffer status.
Definition at line 271 of file lte-rlc.cc.
References ns3::LteMacSapProvider::ReportBufferStatusParameters::lcid, ns3::LteRlc::m_lcid, ns3::LteRlc::m_macSapProvider, ns3::LteRlc::m_rnti, NS_LOG_FUNCTION, ns3::LteMacSapProvider::ReportBufferStatus(), ns3::LteMacSapProvider::ReportBufferStatusParameters::retxQueueHolDelay, ns3::LteMacSapProvider::ReportBufferStatusParameters::retxQueueSize, ns3::LteMacSapProvider::ReportBufferStatusParameters::rnti, ns3::LteMacSapProvider::ReportBufferStatusParameters::statusPduSize, ns3::LteMacSapProvider::ReportBufferStatusParameters::txQueueHolDelay, and ns3::LteMacSapProvider::ReportBufferStatusParameters::txQueueSize.
Referenced by DoInitialize(), and DoNotifyTxOpportunity().
The documentation for this class was generated from the following files:
src/lte/model/lte-rlc.h
src/lte/model/lte-rlc.cc