ns-3: LrWpanAckTestCase Class Reference
LrWpanAckTestCase Class Reference
LR-WPAN models » LrWpan module tests | Test suites
LrWpan ACK Test.
Public Types
enum TestMode_e { EXTENDED_ADDRESS_UNICAST , SHORT_ADDRESS_UNICAST , SHORT_ADDRESS_MULTICAST , SHORT_ADDRESS_BROADCAST }
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Public Member Functions
LrWpanAckTestCase (const char *const prefix, TestMode_e mode)
Create test case.
void DataConfirmDev0 (McpsDataConfirmParams params)
Function called when DataConfirm is hit on dev0.
void DataConfirmDev1 (McpsDataConfirmParams params)
Function called when DataConfirm is hit on dev1.
void DataIndicationDev0 (McpsDataIndicationParams params, Ptr< Packet > p)
Function called when DataIndication is hit on dev0.
void DataIndicationDev1 (McpsDataIndicationParams params, Ptr< Packet > p)
Function called when DataIndication is hit on dev1.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
Ptr< LrWpanNetDevice > m_dev0
1st LrWpanNetDevice.
Ptr< LrWpanNetDevice > m_dev1
2nd LrWpanNetDevice.
TestMode_e m_mode
Test mode.
std::string m_prefix
Filename prefix.
Time m_replyArrivalTime
Reply arrival time.
Time m_replySentTime
Reply successfully sent time.
Time m_replyTime
Reply time.
Time m_requestSentTime
Request successfully sent time.
Time m_requestTime
Request time.
Additional Inherited Members
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
LrWpan ACK Test.
Definition at line 55 of file lr-wpan-ack-test.cc.
Member Enumeration Documentation
TestMode_e
enum LrWpanAckTestCase::TestMode_e
Enumerator
EXTENDED_ADDRESS_UNICAST
SHORT_ADDRESS_UNICAST
SHORT_ADDRESS_MULTICAST
SHORT_ADDRESS_BROADCAST
Definition at line 59 of file lr-wpan-ack-test.cc.
Constructor & Destructor Documentation
LrWpanAckTestCase()
LrWpanAckTestCase::LrWpanAckTestCase (const char *const prefix, TestMode_e mode)
Create test case.
Parameters
prefix Unique file names prefix
mode Test mode
Definition at line 116 of file lr-wpan-ack-test.cc.
References m_mode, m_prefix, m_replyArrivalTime, m_replySentTime, m_replyTime, m_requestSentTime, m_requestTime, and ns3::Seconds().
Member Function Documentation
DataConfirmDev0()
void LrWpanAckTestCase::DataConfirmDev0 (McpsDataConfirmParams params)
Function called when DataConfirm is hit on dev0.
Parameters
testCase The TestCase.
params The MCPS params.
Definition at line 160 of file lr-wpan-ack-test.cc.
References m_requestSentTime, and ns3::Now().
Referenced by DoRun().
DataConfirmDev1()
void LrWpanAckTestCase::DataConfirmDev1 (McpsDataConfirmParams params)
Function called when DataConfirm is hit on dev1.
Parameters
testCase The TestCase.
params The MCPS params.
Definition at line 166 of file lr-wpan-ack-test.cc.
References m_replySentTime, and ns3::Now().
Referenced by DoRun().
DataIndicationDev0()
void LrWpanAckTestCase::DataIndicationDev0 (McpsDataIndicationParams params, Ptr< Packet > p)
Function called when DataIndication is hit on dev0.
Parameters
testCase The TestCase.
params The MCPS params.
p the packet.
Definition at line 129 of file lr-wpan-ack-test.cc.
References m_replyArrivalTime, and ns3::Now().
Referenced by DoRun().
DataIndicationDev1()
void LrWpanAckTestCase::DataIndicationDev1 (McpsDataIndicationParams params, Ptr< Packet > p)
Function called when DataIndication is hit on dev1.
Parameters
testCase The TestCase.
params The MCPS params.
p the packet.
Definition at line 135 of file lr-wpan-ack-test.cc.
References ns3::EXT_ADDR, EXTENDED_ADDRESS_UNICAST, ns3::LrWpanNetDevice::GetMac(), m_dev1, ns3::McpsDataRequestParams::m_dstAddr, ns3::McpsDataRequestParams::m_dstAddrMode, ns3::McpsDataRequestParams::m_dstExtAddr, ns3::McpsDataRequestParams::m_dstPanId, m_mode, ns3::McpsDataRequestParams::m_msduHandle, m_replyTime, ns3::McpsDataRequestParams::m_srcAddrMode, ns3::McpsDataRequestParams::m_txOptions, ns3::Now(), ns3::SHORT_ADDR, and ns3::TX_OPTION_NONE.
Referenced by DoRun().
DoRun()
void LrWpanAckTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 172 of file lr-wpan-ack-test.cc.
References ns3::Node::AddDevice(), ns3::LrWpanNetDevice::AssignStreams(), third::channel, ns3::TestCase::CreateTempDirFilename(), DataConfirmDev0(), DataConfirmDev1(), DataIndicationDev0(), DataIndicationDev1(), ns3::AsciiTraceHelperForDevice::EnableAscii(), ns3::EXT_ADDR, EXTENDED_ADDRESS_UNICAST, ns3::LrWpanNetDevice::GetMac(), ns3::LrWpanNetDevice::GetPhy(), m_dev0, m_dev1, ns3::McpsDataRequestParams::m_dstAddr, ns3::McpsDataRequestParams::m_dstAddrMode, ns3::McpsDataRequestParams::m_dstExtAddr, ns3::McpsDataRequestParams::m_dstPanId, m_mode, ns3::McpsDataRequestParams::m_msduHandle, m_prefix, m_replyArrivalTime, m_replySentTime, m_replyTime, m_requestSentTime, m_requestTime, ns3::McpsDataRequestParams::m_srcAddrMode, ns3::McpsDataRequestParams::m_txOptions, ns3::MakeCallback(), ns3::Now(), NS_TEST_EXPECT_MSG_EQ, NS_TEST_EXPECT_MSG_GT, NS_TEST_EXPECT_MSG_LT, ns3::LrWpanNetDevice::SetAddress(), ns3::LrWpanNetDevice::SetChannel(), ns3::SHORT_ADDR, SHORT_ADDRESS_BROADCAST, SHORT_ADDRESS_MULTICAST, SHORT_ADDRESS_UNICAST, and ns3::TX_OPTION_ACK.
Member Data Documentation
m_dev0
Ptr<LrWpanNetDevice> LrWpanAckTestCase::m_dev0 private
1st LrWpanNetDevice.
Definition at line 112 of file lr-wpan-ack-test.cc.
Referenced by DoRun().
m_dev1
Ptr<LrWpanNetDevice> LrWpanAckTestCase::m_dev1 private
2nd LrWpanNetDevice.
Definition at line 113 of file lr-wpan-ack-test.cc.
Referenced by DataIndicationDev1(), and DoRun().
m_mode
TestMode_e LrWpanAckTestCase::m_mode private
Test mode.
Definition at line 111 of file lr-wpan-ack-test.cc.
Referenced by LrWpanAckTestCase(), DataIndicationDev1(), and DoRun().
m_prefix
std::string LrWpanAckTestCase::m_prefix private
Filename prefix.
Definition at line 105 of file lr-wpan-ack-test.cc.
Referenced by LrWpanAckTestCase(), and DoRun().
m_replyArrivalTime
Time LrWpanAckTestCase::m_replyArrivalTime private
Reply arrival time.
Definition at line 110 of file lr-wpan-ack-test.cc.
Referenced by LrWpanAckTestCase(), DataIndicationDev0(), and DoRun().
m_replySentTime
Time LrWpanAckTestCase::m_replySentTime private
Reply successfully sent time.
Definition at line 109 of file lr-wpan-ack-test.cc.
Referenced by LrWpanAckTestCase(), DataConfirmDev1(), and DoRun().
m_replyTime
Time LrWpanAckTestCase::m_replyTime private
Reply time.
Definition at line 108 of file lr-wpan-ack-test.cc.
Referenced by LrWpanAckTestCase(), DataIndicationDev1(), and DoRun().
m_requestSentTime
Time LrWpanAckTestCase::m_requestSentTime private
Request successfully sent time.
Definition at line 107 of file lr-wpan-ack-test.cc.
Referenced by LrWpanAckTestCase(), DataConfirmDev0(), and DoRun().
m_requestTime
Time LrWpanAckTestCase::m_requestTime private
Request time.
Definition at line 106 of file lr-wpan-ack-test.cc.
Referenced by LrWpanAckTestCase(), and DoRun().
The documentation for this class was generated from the following file:
src/lr-wpan/test/lr-wpan-ack-test.cc