ns-3: ns3::CsParamVectorTlvValue Class Reference
ns3::CsParamVectorTlvValue Class Reference
WiMAX Models
this class implements the convergence sub-layer descriptor as a tlv vector
#include "wimax-tlv.h"
Public Types
enum Type { Classifier_DSC_Action = 1 , Packet_Classification_Rule = 3 }
Type enumeration.
Public Types inherited from ns3::VectorTlvValue
typedef std::vector< Tlv * >::const_iterator Iterator
TLV vector iterator typedef.
Public Member Functions
CsParamVectorTlvValue ()
virtual CsParamVectorTlvValue * Copy (void) const
Copy.
virtual uint32_t Deserialize (Buffer::Iterator start, uint64_t valueLength)
Deserialize from a buffer.
Public Member Functions inherited from ns3::VectorTlvValue
VectorTlvValue (void)
~VectorTlvValue (void)
void Add (const Tlv &val)
Add a TLV.
Iterator Begin () const
Begin iterator.
Iterator End () const
End iterator.
virtual uint32_t GetSerializedSize (void) const
Get serialized size in bytes.
virtual void Serialize (Buffer::Iterator start) const
Serialize to a buffer.
Public Member Functions inherited from ns3::TlvValue
virtual ~TlvValue ()
Detailed Description
this class implements the convergence sub-layer descriptor as a tlv vector
Definition at line 376 of file wimax-tlv.h.
Member Enumeration Documentation
Type
enum ns3::CsParamVectorTlvValue::Type
Type enumeration.
Enumerator
Classifier_DSC_Action
Packet_Classification_Rule
Definition at line 380 of file wimax-tlv.h.
Constructor & Destructor Documentation
CsParamVectorTlvValue()
ns3::CsParamVectorTlvValue::CsParamVectorTlvValue ()
Definition at line 696 of file wimax-tlv.cc.
Referenced by Copy().
Member Function Documentation
Copy()
CsParamVectorTlvValue * ns3::CsParamVectorTlvValue::Copy (void) const virtual
Copy.
Returns
the vector TLV value
Implements ns3::VectorTlvValue.
Definition at line 702 of file wimax-tlv.cc.
References CsParamVectorTlvValue(), ns3::VectorTlvValue::Add(), ns3::VectorTlvValue::Begin(), and ns3::VectorTlvValue::End().
Deserialize()
uint32_t ns3::CsParamVectorTlvValue::Deserialize (Buffer::Iterator start, uint64_t valueLen) virtual
Deserialize from a buffer.
Parameters
start the iterator
valueLen the maximum length of the value
Returns
the
Implements ns3::VectorTlvValue.
Definition at line 648 of file wimax-tlv.cc.
References ns3::VectorTlvValue::Add(), Classifier_DSC_Action, ns3::U8TlvValue::Deserialize(), ns3::ClassificationRuleVectorTlvValue::Deserialize(), ns3::VectorTlvValue::GetSerializedSize(), ns3::Buffer::Iterator::Next(), Packet_Classification_Rule, ns3::Buffer::Iterator::ReadU8(), and WIMAX_TLV_EXTENDED_LENGTH_MASK.
Referenced by ns3::SfVectorTlvValue::Deserialize().
The documentation for this class was generated from the following files:
src/wimax/model/wimax-tlv.h
src/wimax/model/wimax-tlv.cc