ns-3: IdealRateManagerMimoTest Class Reference
IdealRateManagerMimoTest Class Reference
Test to validate that Ideal rate manager properly selects TXVECTOR in scenarios where MIMO is used.
Public Member Functions
IdealRateManagerMimoTest ()
virtual ~IdealRateManagerMimoTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CheckLastSelectedMode (WifiMode expectedMode)
Check if the selected WifiMode is correct.
void CheckLastSelectedNss (uint8_t expectedNss)
Check if the selected Nss is correct.
void SendPacket (Ptr< NetDevice > sourceDevice, Address &destination)
Triggers the transmission of a 1000 Byte-long data packet from the source device.
void SetApMimoSettings (uint8_t antennas, uint8_t maxStreams)
Change the configured MIMO settings for AP node.
void SetStaMimoSettings (uint8_t antennas, uint8_t maxStreams)
Change the configured MIMO settings for STA node.
void TxCallback (std::string context, WifiConstPsduMap psdus, WifiTxVector txVector, double txPowerW)
Callback that indicates a PSDU is being transmitted.
Private Attributes
WifiTxVector m_txVector
Store the last TXVECTOR used to transmit Data.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test to validate that Ideal rate manager properly selects TXVECTOR in scenarios where MIMO is used.
The test consider both balanced and unbalanced MIMO settings, and verify ideal picks the correct number of spatial streams and the correct MCS, taking into account potential diversity in AWGN channels when the number of antenna at the receiver is higher than the number of spatial streams used for the transmission.
Definition at line 2690 of file wifi-test.cc.
Constructor & Destructor Documentation
IdealRateManagerMimoTest()
IdealRateManagerMimoTest::IdealRateManagerMimoTest ()
Definition at line 2740 of file wifi-test.cc.
~IdealRateManagerMimoTest()
IdealRateManagerMimoTest::~IdealRateManagerMimoTest () virtual
Definition at line 2745 of file wifi-test.cc.
Member Function Documentation
CheckLastSelectedMode()
void IdealRateManagerMimoTest::CheckLastSelectedMode (WifiMode expectedMode) private
Check if the selected WifiMode is correct.
Parameters
expectedMode the expected WifiMode
Definition at line 2788 of file wifi-test.cc.
References ns3::WifiTxVector::GetMode(), m_txVector, and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
CheckLastSelectedNss()
void IdealRateManagerMimoTest::CheckLastSelectedNss (uint8_t expectedNss) private
Check if the selected Nss is correct.
Parameters
expectedNss the expected Nss
Definition at line 2782 of file wifi-test.cc.
References ns3::WifiTxVector::GetNss(), m_txVector, and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
DoRun()
void IdealRateManagerMimoTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 2794 of file wifi-test.cc.
References third::channel, CheckLastSelectedMode(), CheckLastSelectedNss(), ns3::Config::Connect(), ns3::NodeContainer::Create(), ns3::NetDeviceContainer::Get(), third::mac, ns3::MakeCallback(), third::mobility, third::phy, ns3::Seconds(), SendPacket(), SetApMimoSettings(), SetStaMimoSettings(), TxCallback(), third::wifi, ns3::WIFI_STANDARD_80211ac, and third::wifiApNode.
SendPacket()
void IdealRateManagerMimoTest::SendPacket (Ptr< NetDevice > sourceDevice, Address & destination) private
Triggers the transmission of a 1000 Byte-long data packet from the source device.
Parameters
sourceDevice pointer to the source NetDevice
destination address of the destination device
Definition at line 2766 of file wifi-test.cc.
Referenced by DoRun().
SetApMimoSettings()
void IdealRateManagerMimoTest::SetApMimoSettings (uint8_t antennas, uint8_t maxStreams) private
Change the configured MIMO settings for AP node.
Parameters
antennas the number of active antennas
maxStreams the maximum number of allowed spatial streams
Definition at line 2750 of file wifi-test.cc.
References ns3::Config::Set().
Referenced by DoRun().
SetStaMimoSettings()
void IdealRateManagerMimoTest::SetStaMimoSettings (uint8_t antennas, uint8_t maxStreams) private
Change the configured MIMO settings for STA node.
Parameters
antennas the number of active antennas
maxStreams the maximum number of allowed spatial streams
Definition at line 2758 of file wifi-test.cc.
References ns3::Config::Set().
Referenced by DoRun().
TxCallback()
void IdealRateManagerMimoTest::TxCallback (std::string context, WifiConstPsduMap psdus, WifiTxVector txVector, double txPowerW) private
Callback that indicates a PSDU is being transmitted.
Parameters
context the context
psduMap the PSDU map to transmit
txVector the TX vector
txPowerW the TX power (W)
Definition at line 2773 of file wifi-test.cc.
References m_txVector.
Referenced by DoRun().
Member Data Documentation
m_txVector
WifiTxVector IdealRateManagerMimoTest::m_txVector private
Store the last TXVECTOR used to transmit Data.
Definition at line 2737 of file wifi-test.cc.
Referenced by CheckLastSelectedMode(), CheckLastSelectedNss(), and TxCallback().
The documentation for this class was generated from the following file:
src/wifi/test/wifi-test.cc