ns-3: ns3::dsr::DsrOptionRreq Class Reference
ns3::dsr::DsrOptionRreq Class Reference
Dsr Option Rreq.
#include "dsr-options.h"
Public Member Functions
DsrOptionRreq ()
Constructor.
virtual ~DsrOptionRreq ()
Destructor.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
virtual uint8_t GetOptionNumber () const
Get the option number.
virtual uint8_t Process (Ptr< Packet > packet, Ptr< Packet > dsrP, Ipv4Address ipv4Address, Ipv4Address source, Ipv4Header const &ipv4Header, uint8_t protocol, bool &isPromisc, Ipv4Address promiscSource)
Process method.
Public Member Functions inherited from ns3::dsr::DsrOptions
DsrOptions ()
Constructor.
virtual ~DsrOptions ()
Destructor.
bool CheckDuplicates (Ipv4Address ipv4Address, std::vector< Ipv4Address > &vec)
Check if the route already contains the node ip address.
bool ContainAddressAfter (Ipv4Address ipv4Address, Ipv4Address destAddress, std::vector< Ipv4Address > &nodeList)
Search for the ipv4 address in the node list.
std::vector< Ipv4Address > CutRoute (Ipv4Address ipv4Address, std::vector< Ipv4Address > &nodeList)
Cut the route from ipv4Address to the end of the route vector.
uint32_t GetIDfromIP (Ipv4Address address)
Get the node id with Ipv4Address.
Ptr< Node > GetNode () const
Get the node.
Ptr< Node > GetNodeWithAddress (Ipv4Address ipv4Address)
Get the node object with Ipv4Address.
bool IfDuplicates (std::vector< Ipv4Address > &vec, std::vector< Ipv4Address > &vec2)
Check if the two vectors contain duplicate or not.
void PrintVector (std::vector< Ipv4Address > &vec)
Print out the elements in the route vector.
void RemoveDuplicates (std::vector< Ipv4Address > &vec)
Remove the duplicates from the route.
bool ReverseRoutes (std::vector< Ipv4Address > &vec)
Reverse the routes.
Ipv4Address ReverseSearchNextHop (Ipv4Address ipv4Address, std::vector< Ipv4Address > &vec)
Reverse search for the next hop in the route.
Ipv4Address ReverseSearchNextTwoHop (Ipv4Address ipv4Address, std::vector< Ipv4Address > &vec)
Reverse search for the next two hop in the route.
void ScheduleReply (Ptr< Packet > &packet, std::vector< Ipv4Address > &nodeList, Ipv4Address &source, Ipv4Address &destination)
Schedule the intermediate node route request broadcast.
Ipv4Address SearchNextHop (Ipv4Address ipv4Address, std::vector< Ipv4Address > &vec)
Search for the next hop in the route.
void SetNode (Ptr< Node > node)
Set the node.
virtual Ptr< Ipv4Route > SetRoute (Ipv4Address nextHop, Ipv4Address srcAddress)
Set the route to use for data packets, used by the option headers when sending data/control packets.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::dsr::DsrOptions
static TypeId GetTypeId (void)
Get the type identificator.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static const uint8_t OPT_NUMBER = 1
Rreq option number.
Private Attributes
Ptr< Ipv4 > m_ipv4
The ipv4.
Ptr< dsr::DsrRouteCache > m_routeCache
The route cache.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::dsr::DsrOptions
Time ActiveRouteTimeout
The active route timeout value.
Ipv4Address Broadcast
The broadcast IP address.
TracedCallback< Ptr< const Packet > > m_dropTrace
Drop trace callback.
std::vector< Ipv4Address > m_finalRoute
The vector of final Ipv4 address.
Ptr< Ipv4 > m_ipv4
The ipv4.
std::vector< Ipv4Address > m_ipv4Address
The vector of Ipv4 address.
Ptr< Ipv4Route > m_ipv4Route
The ipv4 route.
Ptr< dsr::DsrRouteCache > m_routeCache
The route cache table.
Ptr< dsr::DsrRreqTable > m_rreqTable
The route request table.
TracedCallback< const DsrOptionSRHeader & > m_rxPacketTrace
The receive trace back, only triggered when final destination receive data packet.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Dsr Option Rreq.
Introspection did not find any typical Config paths.
No Attributes are defined for this type.
Attributes defined in parent class ns3::dsr::DsrOptions
OptionNumber: The Dsr option number.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Flags: read
No TraceSources are defined for this type.
TraceSources defined in parent class ns3::dsr::DsrOptions
Drop: Packet dropped.
Callback signature: ns3::Packet::TracedCallback
Rx: Receive DSR packet.
Callback signature: ns3::dsr::DsrOptionSRHeader::TracedCallback
Size of this type is 200 bytes (on a 64-bit architecture).
Definition at line 328 of file dsr-options.h.
Constructor & Destructor Documentation
DsrOptionRreq()
ns3::dsr::DsrOptionRreq::DsrOptionRreq ()
Constructor.
Definition at line 478 of file dsr-options.cc.
References NS_LOG_FUNCTION_NOARGS.
~DsrOptionRreq()
ns3::dsr::DsrOptionRreq::~DsrOptionRreq () virtual
Destructor.
Definition at line 483 of file dsr-options.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
GetInstanceTypeId()
TypeId ns3::dsr::DsrOptionRreq::GetInstanceTypeId (void) const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::Object.
Definition at line 473 of file dsr-options.cc.
References GetTypeId().
GetOptionNumber()
uint8_t ns3::dsr::DsrOptionRreq::GetOptionNumber () const virtual
Get the option number.
Returns
option number
Implements ns3::dsr::DsrOptions.
Definition at line 488 of file dsr-options.cc.
References NS_LOG_FUNCTION_NOARGS, and OPT_NUMBER.
GetTypeId()
TypeId ns3::dsr::DsrOptionRreq::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 463 of file dsr-options.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Process()
uint8_t ns3::dsr::DsrOptionRreq::Process (Ptr< Packet > packet, Ptr< Packet > dsrP, Ipv4Address ipv4Address, Ipv4Address source, Ipv4Header const & ipv4Header, uint8_t protocol, bool & isPromisc, Ipv4Address promiscSource) virtual
Process method.
Called from DsrRouting::Receive.
Parameters
packet the packet
dsrP the clean packet with payload
ipv4Address the IPv4 address
source IPv4 address of the source
ipv4Header the IPv4 header of packet received
protocol the protocol number of the up layer
isPromisc if the packet must be dropped
promiscSource IPv4 address
Returns
the processed size
TODO has changed the srcAddress to source, should not matter either way, check later
TODO !!!!!!!!!!!!!! Think about this part, we just added the route, probability no need to increase stability now?????
push back the intermediate node address from the source to this node
push back the route vector we found in our route cache to destination, including this node's address
Implements ns3::dsr::DsrOptions.
Definition at line 495 of file dsr-options.cc.
References ns3::dsr::DsrOptions::ActiveRouteTimeout, ns3::dsr::DsrOptionField::AddDsrOption(), ns3::Packet::AddHeader(), ns3::Packet::AddPacketTag(), ns3::dsr::DsrOptions::CheckDuplicates(), ns3::Packet::Copy(), ns3::Packet::CopyData(), ns3::dsr::DsrOptionRerrUnreachHeader::GetErrorDst(), ns3::dsr::DsrOptionRerrUnreachHeader::GetErrorSrc(), ns3::dsr::DsrOptionRreqHeader::GetId(), ns3::dsr::DsrOptions::GetIDfromIP(), ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrOptionRreqHeader::GetNodesAddresses(), ns3::dsr::DsrOptions::GetNodeWithAddress(), ns3::Object::GetObject(), ns3::dsr::DsrOptionRerrUnreachHeader::GetSalvage(), ns3::dsr::DsrOptionRreqHeader::GetSerializedSize(), ns3::Packet::GetSize(), ns3::Ipv4Header::GetSource(), ns3::dsr::DsrOptionRreqHeader::GetTarget(), ns3::Ipv4Header::GetTtl(), ns3::dsr::DsrOptionRerrUnreachHeader::GetUnreachNode(), ns3::dsr::DsrRouteCacheEntry::GetVector(), ns3::dsr::DsrOptions::IfDuplicates(), ns3::dsr::DsrOptions::m_dropTrace, ns3::dsr::DsrOptions::m_finalRoute, ns3::dsr::DsrOptions::m_ipv4Route, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::dsr::DsrOptions::PrintVector(), ns3::dsr::DsrOptions::ReverseRoutes(), ns3::dsr::DsrOptions::ReverseSearchNextHop(), ns3::dsr::DsrOptions::SearchNextHop(), ns3::dsr::DsrFsHeader::SetDestId(), ns3::dsr::DsrOptionRerrUnreachHeader::SetErrorDst(), ns3::dsr::DsrOptionRerrUnreachHeader::SetErrorSrc(), ns3::dsr::DsrOptionRerrHeader::SetErrorType(), ns3::dsr::DsrFsHeader::SetMessageType(), ns3::dsr::DsrFsHeader::SetNextHeader(), ns3::dsr::DsrOptionRreqHeader::SetNodesAddress(), ns3::dsr::DsrOptionRrepHeader::SetNodesAddress(), ns3::dsr::DsrOptionSRHeader::SetNodesAddress(), ns3::dsr::DsrOptionRreqHeader::SetNumberAddress(), ns3::dsr::DsrFsHeader::SetPayloadLength(), ns3::dsr::DsrOptions::SetRoute(), ns3::dsr::DsrOptionSRHeader::SetSalvage(), ns3::dsr::DsrOptionRerrUnreachHeader::SetSalvage(), ns3::dsr::DsrOptionSRHeader::SetSegmentsLeft(), ns3::dsr::DsrFsHeader::SetSourceId(), ns3::SocketIpTtlTag::SetTtl(), and ns3::dsr::DsrOptionRerrUnreachHeader::SetUnreachNode().
Member Data Documentation
m_ipv4
Ptr<Ipv4> ns3::dsr::DsrOptionRreq::m_ipv4 private
The ipv4.
Definition at line 366 of file dsr-options.h.
m_routeCache
Ptr<dsr::DsrRouteCache> ns3::dsr::DsrOptionRreq::m_routeCache private
The route cache.
Definition at line 362 of file dsr-options.h.
OPT_NUMBER
const uint8_t ns3::dsr::DsrOptionRreq::OPT_NUMBER = 1 static
Rreq option number.
Definition at line 334 of file dsr-options.h.
Referenced by GetOptionNumber().
The documentation for this class was generated from the following files:
src/dsr/model/dsr-options.h
src/dsr/model/dsr-options.cc