ns-3: ns3::TcpGeneralTest Class Reference
ns3::TcpGeneralTest Class Reference
Internet » internet module tests | Test suites
General infrastructure for TCP testing.
#include "tcp-general-test.h"
Public Types
enum SocketWho { SENDER , RECEIVER }
Used as parameter of methods, specifies on what node the caller is interested (e.g.
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Public Member Functions
TcpGeneralTest (const std::string &desc)
TcpGeneralTest constructor.
~TcpGeneralTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Member Functions
virtual void AfterRTOExpired (const Ptr< const TcpSocketState > tcb, SocketWho who)
Rto has expired.
virtual void BeforeRTOExpired (const Ptr< const TcpSocketState > tcb, SocketWho who)
Rto has expired.
virtual void BytesInFlightTrace (uint32_t oldValue, uint32_t newValue)
Bytes in flight changes.
virtual void ConfigureEnvironment (void)
Change the configuration of the environment.
virtual void ConfigureProperties (void)
Change the configuration of the socket properties.
virtual void CongStateTrace (const TcpSocketState::TcpCongState_t oldValue, const TcpSocketState::TcpCongState_t newValue)
State on Ack state machine changes.
virtual Ptr< SimpleChannel > CreateChannel ()
Create and return the channel installed between the two socket.
virtual Ptr< ErrorModel > CreateReceiverErrorModel ()
Create and return the error model to install in the receiver node.
virtual Ptr< TcpSocketMsgBase > CreateReceiverSocket (Ptr< Node > node)
Create and install the socket to install on the receiver.
virtual Ptr< ErrorModel > CreateSenderErrorModel ()
Create and return the error model to install in the sender node.
virtual Ptr< TcpSocketMsgBase > CreateSenderSocket (Ptr< Node > node)
Create and install the socket to install on the sender.
virtual Ptr< TcpSocketMsgBase > CreateSocket (Ptr< Node > node, TypeId socketType, TypeId congControl)
Create a socket.
virtual Ptr< TcpSocketMsgBase > CreateSocket (Ptr< Node > node, TypeId socketType, TypeId congControl, TypeId recoveryAlgorithm)
Create a socket.
virtual void CWndInflTrace (uint32_t oldValue, uint32_t newValue)
Tracks the inflated congestion window changes.
virtual void CWndTrace (uint32_t oldValue, uint32_t newValue)
Tracks the congestion window changes.
virtual void DataSent (uint32_t size, SocketWho who)
Notifying application for sent data.
void DoConnect ()
Scheduled at 0.0, SENDER starts the connection to RECEIVER.
virtual void DoRun (void)
Execute the tcp test.
virtual void DoTeardown (void)
Teardown the TCP test.
virtual void ErrorClose (SocketWho who)
Socket closed with an error.
virtual void FinalChecks ()
Performs the (eventual) final checks through test asserts.
Time GetClockGranularity (SocketWho who)
Get the clock granularity attribute.
Time GetConnTimeout (SocketWho who)
Get the retransmission time for the SYN segments.
uint32_t GetDelAckCount (SocketWho who)
Get the number of delayed ack (if present)
Time GetDelAckTimeout (SocketWho who)
Get the timeout of delayed ack (if present)
uint32_t GetDupAckCount (SocketWho who)
Get the number of dupack received.
SequenceNumber32 GetHighestTxMark (SocketWho who)
Get the highest tx mark of the node specified.
uint32_t GetInitialCwnd (SocketWho who)
Get the initial congestion window.
uint32_t GetInitialSsThresh (SocketWho who)
Get the initial slow start threshold.
Time GetMinRto (SocketWho who)
Get the minimum RTO attribute.
uint32_t GetMtu () const
Get the MTU of the environment.
EventId GetPersistentEvent (SocketWho who)
Get the persistent event of the selected socket.
Time GetPersistentTimeout (SocketWho who)
Get the persistent timeout of the selected socket.
uint32_t GetPktCount () const
Get the number of application packets.
Time GetPktInterval () const
Get the interval to wait for each packet sent down from application to TCP.
uint32_t GetPktSize () const
Get the application packet size.
Time GetPropagationDelay () const
Get the channel Propagation Delay.
Ptr< TcpSocketMsgBase > GetReceiverSocket ()
Get the pointer to a previously created receiver socket.
uint32_t GetReTxThreshold (SocketWho who)
Get the retransmission threshold.
Time GetRto (SocketWho who)
Get the retransmission time.
Ptr< RttEstimator > GetRttEstimator (SocketWho who)
Get the Rtt estimator of the socket.
uint32_t GetRWnd (SocketWho who)
Get the rWnd of the selected socket.
Ptr< TcpRxBuffer > GetRxBuffer (SocketWho who)
Get the Rx buffer from selected socket.
uint32_t GetSegSize (SocketWho who)
Get the segment size of the node specified.
Ptr< TcpSocketMsgBase > GetSenderSocket ()
Get the pointer to a previously created sender socket.
Time GetStartTime () const
Get the data start time.
Ptr< TcpSocketState > GetTcb (SocketWho who)
Get the TCB from selected socket.
TcpSocket::TcpStates_t GetTcpState (SocketWho who)
Get the state of the TCP state machine.
Ptr< TcpTxBuffer > GetTxBuffer (SocketWho who)
Get the Tx buffer from selected socket.
virtual void HighestTxSeqTrace (SequenceNumber32 oldValue, SequenceNumber32 newValue)
Highest tx seq changes.
virtual void NextTxSeqTrace (SequenceNumber32 oldValue, SequenceNumber32 newValue)
Next tx seq changes.
virtual void NormalClose (SocketWho who)
Socket closed normally.
virtual void PhyDrop (SocketWho who)
Link drop.
virtual void ProcessedAck (const Ptr< const TcpSocketState > tcb, const TcpHeader &h, SocketWho who)
Processed ack.
virtual void QueueDrop (SocketWho who)
Drop on the queue.
virtual void RateSampleUpdatedTrace (const TcpRateLinux::TcpRateSample &sample)
Track the rate sample value of TcpRateLinux.
virtual void RateUpdatedTrace (const TcpRateLinux::TcpRateConnection &rate)
Track the rate value of TcpRateLinux.
virtual void RcvAck (const Ptr< const TcpSocketState > tcb, const TcpHeader &h, SocketWho who)
Received ack.
virtual void ReceivePacket (Ptr< Socket > socket)
Packet received.
virtual void RtoTrace (Time oldValue, Time newValue)
RTO changes.
virtual void RttTrace (Time oldTime, Time newTime)
Rtt changes.
virtual void Rx (const Ptr< const Packet > p, const TcpHeader &h, SocketWho who)
Packet received from IP layer.
void SendPacket (Ptr< Socket > socket, uint32_t pktSize, uint32_t pktCount, Time pktInterval)
Send packets to other endpoint.
void SetAppPktCount (uint32_t pktCount)
Set app packet count.
void SetAppPktInterval (Time pktInterval)
Interval between app-generated packet.
void SetAppPktSize (uint32_t pktSize)
Set app packet size.
void SetCongestionControl (TypeId congControl)
Congestion control of the sender socket.
void SetDelAckMaxCount (SocketWho who, uint32_t count)
Forcefully set the delayed acknowledgement count.
void SetInitialCwnd (SocketWho who, uint32_t initialCwnd)
Forcefully set the initial cwnd.
void SetInitialSsThresh (SocketWho who, uint32_t initialSsThresh)
Forcefully set the initial ssthresh.
void SetMTU (uint32_t mtu)
MTU of the bottleneck link.
void SetPaceInitialWindow (SocketWho who, bool paceWindow)
Enable or disable pacing of the initial window.
void SetPacingStatus (SocketWho who, bool pacing)
Enable or disable pacing in the TCP socket.
void SetPropagationDelay (Time propDelay)
Propagation delay of the bottleneck link.
void SetRcvBufSize (SocketWho who, uint32_t size)
Forcefully set a defined size for rx buffer.
void SetRecoveryAlgorithm (TypeId reccovery)
recovery algorithm of the sender socket
void SetSegmentSize (SocketWho who, uint32_t segmentSize)
Forcefully set the segment size.
void SetTransmitStart (Time startTime)
Set the initial time at which the application sends the first data packet.
void SetUseEcn (SocketWho who, TcpSocketState::UseEcn_t useEcn)
Forcefully set the ECN mode of use.
virtual void SsThreshTrace (uint32_t oldValue, uint32_t newValue)
Slow start threshold changes.
virtual void Tx (const Ptr< const Packet > p, const TcpHeader &h, SocketWho who)
Packet transmitted down to IP layer.
virtual void UpdatedRttHistory (const SequenceNumber32 &seq, uint32_t sz, bool isRetransmission, SocketWho who)
Updated the Rtt history.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Protected Attributes
TypeId m_congControlTypeId
Congestion control.
TypeId m_recoveryTypeId
Recovery.
Private Member Functions
void AfterRetransmitCb (const Ptr< const TcpSocketState > tcb, const Ptr< const TcpSocketBase > tcp)
Invoked after a retransmit event.
void BeforeRetransmitCb (const Ptr< const TcpSocketState > tcb, const Ptr< const TcpSocketBase > tcp)
Invoked before a retransmit event.
void DataSentCb (Ptr< Socket > socket, uint32_t size)
Data sent Callback.
void ErrorCloseCb (Ptr< Socket > socket)
Error Close Callback.
void ForkCb (Ptr< TcpSocketMsgBase > tcp)
Fork Callback.
void HandleAccept (Ptr< Socket > socket, const Address &from)
Handle an accept connection.
void NormalCloseCb (Ptr< Socket > socket)
Normal Close Callback.
void PhyDropCb (std::string context, Ptr< const Packet > p)
Drop at Phy layer Callback.
void ProcessedAckCb (Ptr< const Packet > p, const TcpHeader &h, Ptr< const TcpSocketBase > tcp)
ACK processed Callback.
void QueueDropCb (std::string context, Ptr< const Packet > p)
Queue Drop Callback.
void RcvAckCb (Ptr< const Packet > p, const TcpHeader &h, Ptr< const TcpSocketBase > tcp)
Receive ACK Callback.
void RtoExpiredCb (const Ptr< const TcpSocketState > tcb, const Ptr< const TcpSocketBase > tcp)
RTO expired Callback.
void RxPacketCb (const Ptr< const Packet > p, const TcpHeader &h, const Ptr< const TcpSocketBase > tcp)
Rx packet Callback.
void TxPacketCb (const Ptr< const Packet > p, const TcpHeader &h, const Ptr< const TcpSocketBase > tcp)
Tx packet Callback.
void UpdateRttHistoryCb (Ptr< const TcpSocketBase > tcp, const SequenceNumber32 &seq, uint32_t sz, bool isRetransmission)
Update RTT with new data.
Private Attributes
Time m_interPacketInterval
Time between sending application packet down to tcp socket.
uint32_t m_mtu
MTU of the environment.
uint32_t m_pktCount
Count of the application packet.
uint32_t m_pktSize
Size of the application packet.
Time m_propagationDelay
Propagation delay of the channel.
Ptr< TcpSocketMsgBase > m_receiverSocket
Pointer to receiver socket.
InetSocketAddress m_remoteAddr
Remote peer address.
Ptr< TcpSocketMsgBase > m_senderSocket
Pointer to sender socket.
Time m_startTime
Data transmission time.
Detailed Description
General infrastructure for TCP testing.
The class provides a simple setup for a connection testing. Implement or modify the virtual methods in order to install a specified channel, a specified socket and a specified error model on this simulation. Default values are a null error model, and as a channel a SimpleChannel with the propagation delay set through the constructor.
Check DoRun documentation for more information on the environment setup.
Apart from setting up the environment for testing, subclassing permits also to track and check what is happening inside the two connected sockets. Thanks to TcpSocketMsgBase, there are many information provided to children:
Tracing of states inside the state machines (TCP and ACK ones, through functions CongStateTrace and TcpStateTrace)
cWnd tracing (through CWndTrace)
Socket closing: error state, or normal state (NormalClose and ErrorClose)
Packet drop, inside queue or over the link (QueueDrop, PhyDrop)
Ack received (RcvAck) and Ack processed (ProcessedAck). The first is used to signal that an ACK has been received; after the processing of it, the Second is called
A packet is transmitted to IP layer or received from IP layer (Tx and Rx)
The RTO expires (RTOExpired)
The default version of such methods is empty; implement their behavior differently, based on what you want to test. Default is empty to avoid the need to implement useless pure virtual function.
If you need values from TcpSocketBase, thanks to the friend relationship between this class and TcpSocketBase itself you can get it. Remember that friendship isn't passed by inheritance, so the way to go is to write a Getters (like GetSegSize) and call it in the subclass.
See also
DoRun
TcpSocketMsgBase
Definition at line 256 of file tcp-general-test.h.
Member Enumeration Documentation
SocketWho
enum ns3::TcpGeneralTest::SocketWho
Used as parameter of methods, specifies on what node the caller is interested (e.g.
GetSegSize).
Enumerator
SENDER
Sender node.
RECEIVER
Receiver node.
Definition at line 274 of file tcp-general-test.h.
Constructor & Destructor Documentation
TcpGeneralTest()
TcpGeneralTest::TcpGeneralTest (const std::string & desc)
TcpGeneralTest constructor.
Please use the method ConfigureEnvironment () to configure other parameters than the test description.
Parameters
desc description of the test
Definition at line 42 of file tcp-general-test.cc.
References NS_LOG_FUNCTION.
~TcpGeneralTest()
TcpGeneralTest::~TcpGeneralTest ()
Definition at line 51 of file tcp-general-test.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
AfterRetransmitCb()
void TcpGeneralTest::AfterRetransmitCb (const Ptr< const TcpSocketState > tcb, const Ptr< const TcpSocketBase > tcp) private
Invoked after a retransmit event.
Parameters
tcb Transmission control block.
tcp The TCP socket.
Definition at line 407 of file tcp-general-test.cc.
References AfterRTOExpired(), m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by DoRun().
AfterRTOExpired()
virtual void ns3::TcpGeneralTest::AfterRTOExpired (const Ptr< const TcpSocketState > tcb, SocketWho who) inline protected virtual
Rto has expired.
Parameters
tcb Transmission control block
who where the RTO has expired (SENDER or RECEIVER)
Reimplemented in TcpTimeRtoTest, TcpSsThreshRtoTest, TcpRtoTest, and TcpFastRetrTest.
Definition at line 928 of file tcp-general-test.h.
References NS_UNUSED.
Referenced by AfterRetransmitCb().
BeforeRetransmitCb()
void TcpGeneralTest::BeforeRetransmitCb (const Ptr< const TcpSocketState > tcb, const Ptr< const TcpSocketBase > tcp) private
Invoked before a retransmit event.
Parameters
tcb Transmission control block.
tcp The TCP socket.
Definition at line 425 of file tcp-general-test.cc.
References BeforeRTOExpired(), m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by DoRun().
BeforeRTOExpired()
virtual void ns3::TcpGeneralTest::BeforeRTOExpired (const Ptr< const TcpSocketState > tcb, SocketWho who) inline protected virtual
Rto has expired.
Parameters
tcb Transmission control block
who where the RTO has expired (SENDER or RECEIVER)
Reimplemented in TcpSsThreshRtoTest, and TcpBytesInFlightTest.
Definition at line 940 of file tcp-general-test.h.
References NS_UNUSED.
Referenced by BeforeRetransmitCb().
BytesInFlightTrace()
virtual void ns3::TcpGeneralTest::BytesInFlightTrace (uint32_t oldValue, uint32_t newValue) inline protected virtual
Bytes in flight changes.
This applies only for sender socket.
Parameters
oldValue old value
newValue new value
Reimplemented in TcpSsThreshRtoTest, TcpRateLinuxWithSocketsTest, TcpPacingTest, and TcpBytesInFlightTest.
Definition at line 766 of file tcp-general-test.h.
References NS_UNUSED.
Referenced by DoRun().
ConfigureEnvironment()
void TcpGeneralTest::ConfigureEnvironment (void) protected virtual
Change the configuration of the environment.
Reimplemented in TcpLargeTransferLossTest, TcpZeroWindowTest, TcpSlowStartNormalTest, TcpRttEstimationTest, TcpTimeRtoTest, TcpSsThreshRtoTest, TcpRtoTest, TcpRateLinuxWithSocketsTest, TcpPktsAckedOpenTest, TcpPacingTest, TcpLinuxRenoCongAvoidTest, TcpLinuxRenoSSTest, TcpFastRetrTest, TcpDctcpCodePointsTest, TcpDataSentCbTestCase, TcpNewRenoCongAvoidNormalTest, TcpBytesInFlightTest, TcpAdvWindowOnLossTest, and TcpAdvertisedWindowTest.
Definition at line 100 of file tcp-general-test.cc.
References m_congControlTypeId, m_recoveryTypeId, ns3::MilliSeconds(), NS_LOG_FUNCTION, ns3::Seconds(), SetAppPktCount(), SetAppPktInterval(), SetAppPktSize(), SetCongestionControl(), SetMTU(), SetPropagationDelay(), SetRecoveryAlgorithm(), and SetTransmitStart().
Referenced by TcpDataSentCbTestCase::ConfigureEnvironment(), and DoRun().
ConfigureProperties()
void TcpGeneralTest::ConfigureProperties (void) protected virtual
Change the configuration of the socket properties.
Reimplemented in TcpLargeTransferLossTest, TcpZeroWindowTest, TcpSlowStartNormalTest, TcpRtoTest, TcpPacingTest, TcpLinuxRenoCongAvoidTest, TcpLinuxRenoSSTest, TcpFastRetrTest, ns3::TcpEcnTest, TcpDctcpCodePointsTest, TcpNewRenoCongAvoidNormalTest, and ns3::TcpCloseWithLossTestCase.
Definition at line 115 of file tcp-general-test.cc.
References NS_LOG_FUNCTION, RECEIVER, SENDER, SetInitialCwnd(), SetInitialSsThresh(), and SetSegmentSize().
Referenced by ns3::TcpCloseWithLossTestCase::ConfigureProperties(), ns3::TcpEcnTest::ConfigureProperties(), and DoRun().
CongStateTrace()
virtual void ns3::TcpGeneralTest::CongStateTrace (const TcpSocketState::TcpCongState_t oldValue, const TcpSocketState::TcpCongState_t newValue) inline protected virtual
State on Ack state machine changes.
Parameters
oldValue old value
newValue new value
Reimplemented in TcpLargeTransferLossTest, and TcpFastRetrTest.
Definition at line 699 of file tcp-general-test.h.
References NS_UNUSED.
Referenced by DoRun().
CreateChannel()
Ptr< SimpleChannel > TcpGeneralTest::CreateChannel () protected virtual
Create and return the channel installed between the two socket.
Returns
A SimpleChannel subclass
Definition at line 268 of file tcp-general-test.cc.
References m_propagationDelay.
Referenced by DoRun().
CreateReceiverErrorModel()
Ptr< ErrorModel > TcpGeneralTest::CreateReceiverErrorModel () protected virtual
Create and return the error model to install in the receiver node.
Returns
receiver error model
Reimplemented in TcpRttEstimationWithLossTest, TcpTimeRtoTest, TcpSsThreshRtoTest, TcpRateLinuxWithSocketsTest, TcpLargeTransferLossTest, TcpFastRetrTest, ns3::TcpCloseWithLossTestCase, TcpBytesInFlightTest, TcpAdvWindowOnLossTest, and TcpAdvertisedWindowTest.
Definition at line 318 of file tcp-general-test.cc.
Referenced by DoRun().
CreateReceiverSocket()
Ptr< TcpSocketMsgBase > TcpGeneralTest::CreateReceiverSocket (Ptr< Node > node) protected virtual
Create and install the socket to install on the receiver.
Parameters
node receiver node pointer
Returns
the socket to be installed in the receiver
Reimplemented in TcpZeroWindowTest, WScalingTestCase, TimestampTestCase, TcpSlowStartAttackerTest, SackPermittedTestCase, TcpRttEstimationTest, TcpDctcpCodePointsTest, TcpDataSentCbTestCase, TcpAdvWindowOnLossTest, and TcpAdvertisedWindowTest.
Definition at line 330 of file tcp-general-test.cc.
References CreateSocket(), ns3::TcpSocketMsgBase::GetTypeId(), m_congControlTypeId, and m_recoveryTypeId.
Referenced by DoRun().
CreateSenderErrorModel()
Ptr< ErrorModel > TcpGeneralTest::CreateSenderErrorModel () protected virtual
Create and return the error model to install in the sender node.
Returns
sender error model
Reimplemented in TcpFastRetrTest.
Definition at line 312 of file tcp-general-test.cc.
Referenced by DoRun().
CreateSenderSocket()
Ptr< TcpSocketMsgBase > TcpGeneralTest::CreateSenderSocket (Ptr< Node > node) protected virtual
Create and install the socket to install on the sender.
Parameters
node sender node pointer
Returns
the socket to be installed in the sender
Reimplemented in WScalingTestCase, TimestampTestCase, SackPermittedTestCase, TcpRttEstimationTest, TcpTimeRtoTest, TcpSsThreshRtoTest, TcpRtoTest, TcpRateLinuxWithSocketsTest, TcpPktsAckedOpenTest, TcpFastRetrTest, ns3::TcpEcnTest, TcpDctcpCodePointsTest, and TcpAdvWindowOnLossTest.
Definition at line 324 of file tcp-general-test.cc.
References CreateSocket(), ns3::TcpSocketMsgBase::GetTypeId(), m_congControlTypeId, and m_recoveryTypeId.
Referenced by ns3::TcpEcnTest::CreateSenderSocket(), and DoRun().
CreateSocket() [1/2]
Ptr< TcpSocketMsgBase > TcpGeneralTest::CreateSocket (Ptr< Node > node, TypeId socketType, TypeId congControl) protected virtual
Create a socket.
Parameters
node associated node
socketType Type of the TCP socket
congControl congestion control
Returns
a pointer to the newer created socket
Definition at line 278 of file tcp-general-test.cc.
References m_recoveryTypeId.
Referenced by TcpAdvertisedWindowTest::CreateReceiverSocket(), TcpAdvWindowOnLossTest::CreateReceiverSocket(), CreateReceiverSocket(), TcpSlowStartAttackerTest::CreateReceiverSocket(), TcpDctcpCodePointsTest::CreateSenderSocket(), ns3::TcpEcnTest::CreateSenderSocket(), and CreateSenderSocket().
CreateSocket() [2/2]
Ptr< TcpSocketMsgBase > TcpGeneralTest::CreateSocket (Ptr< Node > node, TypeId socketType, TypeId congControl, TypeId recoveryAlgorithm) protected virtual
Create a socket.
Parameters
node associated node
socketType Type of the TCP socket
congControl congestion control
recoveryAlgorithm recovery algorithm
Returns
a pointer to the newer created socket
Definition at line 285 of file tcp-general-test.cc.
References ns3::ObjectFactory::Create(), ns3::Object::GetObject(), ns3::RttMeanDeviation::GetTypeId(), and ns3::ObjectFactory::SetTypeId().
CWndInflTrace()
virtual void ns3::TcpGeneralTest::CWndInflTrace (uint32_t oldValue, uint32_t newValue) inline protected virtual
Tracks the inflated congestion window changes.
Parameters
oldValue old value
newValue new value
Definition at line 724 of file tcp-general-test.h.
References NS_UNUSED.
Referenced by DoRun().
CWndTrace()
virtual void ns3::TcpGeneralTest::CWndTrace (uint32_t oldValue, uint32_t newValue) inline protected virtual
Tracks the congestion window changes.
Parameters
oldValue old value
newValue new value
Reimplemented in TcpSlowStartNormalTest, TcpPacingTest, TcpLinuxRenoCongAvoidTest, TcpLinuxRenoSSTest, ns3::TcpEcnTest, and TcpNewRenoCongAvoidNormalTest.
Definition at line 712 of file tcp-general-test.h.
References NS_UNUSED.
Referenced by DoRun().
DataSent()
virtual void ns3::TcpGeneralTest::DataSent (uint32_t size, SocketWho who) inline protected virtual
Notifying application for sent data.
Parameters
size the amount of bytes transmitted
who where the RTO has expired (SENDER or RECEIVER)
Reimplemented in TcpDataSentCbTestCase.
Definition at line 968 of file tcp-general-test.h.
References NS_UNUSED.
Referenced by DataSentCb().
DataSentCb()
void TcpGeneralTest::DataSentCb (Ptr< Socket > socket, uint32_t size) private
Data sent Callback.
Parameters
socket The socket.
size The data size.
Definition at line 443 of file tcp-general-test.cc.
References DataSent(), ns3::Socket::GetNode(), m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by DoRun().
DoConnect()
void TcpGeneralTest::DoConnect (void) protected
Scheduled at 0.0, SENDER starts the connection to RECEIVER.
Definition at line 251 of file tcp-general-test.cc.
References m_remoteAddr, m_senderSocket, and NS_LOG_INFO.
Referenced by DoRun().
DoRun()
void TcpGeneralTest::DoRun (void) protected virtual
Execute the tcp test.
As environment, two socket are connected through a SimpleChannel. Each device has an MTU of 1500 bytes, and the application starts to send packet at 10s of simulated time, through SendPacket.
If you need to change parameters of the environment, please inherit an implement the method ConfigureEnvironment (); that will be called at the beginning of this method. To configure Socket parameters (i.e. parameters that should be applied after socket have been created) use ConfigureProperties.
Please do not use any Config:: statements.
See also
ConfigureEnvironment
Implements ns3::TestCase.
Definition at line 125 of file tcp-general-test.cc.
References AfterRetransmitCb(), ns3::Ipv4AddressHelper::Assign(), BeforeRetransmitCb(), BytesInFlightTrace(), third::channel, ConfigureEnvironment(), ConfigureProperties(), CongStateTrace(), CreateChannel(), CreateReceiverErrorModel(), CreateReceiverSocket(), CreateSenderErrorModel(), CreateSenderSocket(), CWndInflTrace(), CWndTrace(), DataSentCb(), DoConnect(), ns3::Packet::EnablePrinting(), ErrorCloseCb(), ForkCb(), ns3::NetDeviceContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::Ipv4Address::GetAny(), HandleAccept(), HighestTxSeqTrace(), ns3::SimpleNetDeviceHelper::Install(), ns3::InternetStackHelper::Install(), m_interPacketInterval, m_mtu, m_pktCount, m_pktSize, m_receiverSocket, m_remoteAddr, m_senderSocket, m_startTime, ns3::MakeCallback(), ns3::MakeNullCallback(), NextTxSeqTrace(), first::nodes, NormalCloseCb(), NS_LOG_INFO, PhyDropCb(), ProcessedAckCb(), QueueDropCb(), RateSampleUpdatedTrace(), RateUpdatedTrace(), RcvAckCb(), ReceivePacket(), RtoTrace(), RttTrace(), ns3::Simulator::Run(), RxPacketCb(), ns3::Simulator::Schedule(), ns3::Simulator::ScheduleWithContext(), ns3::Seconds(), SendPacket(), ns3::Ipv4AddressHelper::SetBase(), ns3::SimpleNetDeviceHelper::SetNetDevicePointToPointMode(), SsThreshTrace(), TxPacketCb(), and UpdateRttHistoryCb().
DoTeardown()
void TcpGeneralTest::DoTeardown (void) protected virtual
Teardown the TCP test.
Reimplemented from ns3::TestCase.
Reimplemented in TcpLinuxRenoCongAvoidTest, and TcpLinuxRenoSSTest.
Definition at line 91 of file tcp-general-test.cc.
References ns3::Simulator::Destroy(), FinalChecks(), and NS_LOG_INFO.
ErrorClose()
virtual void ns3::TcpGeneralTest::ErrorClose (SocketWho who) inline protected virtual
Socket closed with an error.
Parameters
who the socket closed (SENDER or RECEIVER)
Todo:
indicate the error
Reimplemented in TcpTimeRtoTest.
Definition at line 846 of file tcp-general-test.h.
References NS_UNUSED.
Referenced by ErrorCloseCb().
ErrorCloseCb()
void TcpGeneralTest::ErrorCloseCb (Ptr< Socket > socket) private
Error Close Callback.
Parameters
socket The socket.
Definition at line 460 of file tcp-general-test.cc.
References ErrorClose(), ns3::Socket::GetNode(), m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by DoRun(), and HandleAccept().
FinalChecks()
virtual void ns3::TcpGeneralTest::FinalChecks (void) inline protected virtual
Performs the (eventual) final checks through test asserts.
Reimplemented in TcpLargeTransferLossTest, TcpZeroWindowTest, TcpRttEstimationTest, TcpTimeRtoTest, TcpRtoTest, TcpRateLinuxWithSocketsTest, TcpPktsAckedOpenTest, TcpFastRetrTest, TcpDataSentCbTestCase, ns3::TcpCloseWithLossTestCase, and TcpBytesInFlightTest.
Definition at line 977 of file tcp-general-test.h.
Referenced by DoTeardown().
ForkCb()
void TcpGeneralTest::ForkCb (Ptr< TcpSocketMsgBase > tcp) private
Fork Callback.
Parameters
tcp The TCP socket.
Definition at line 561 of file tcp-general-test.cc.
References m_receiverSocket, and NS_LOG_FUNCTION.
Referenced by DoRun().
GetClockGranularity()
Time TcpGeneralTest::GetClockGranularity (SocketWho who) protected
Get the clock granularity attribute.
Parameters
who node to get the parameter from
Returns
clock granularity
Definition at line 762 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by TcpTimeRtoTest::Tx().
GetConnTimeout()
Time TcpGeneralTest::GetConnTimeout (SocketWho who) protected
Get the retransmission time for the SYN segments.
Parameters
who node to get the parameter from
Returns
SYN segments RTO time
Definition at line 728 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by TcpTimeRtoTest::Tx().
GetDelAckCount()
uint32_t TcpGeneralTest::GetDelAckCount (SocketWho who) protected
Get the number of delayed ack (if present)
Parameters
who node to get the parameter from
Returns
number of ack we will wait before sending an ACK
Definition at line 603 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by TcpFastRetrTest::Tx().
GetDelAckTimeout()
Time TcpGeneralTest::GetDelAckTimeout (SocketWho who) protected
Get the timeout of delayed ack (if present)
Parameters
who node to get the parameter from
Returns
time we will wait before sending an ACK
Definition at line 620 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
GetDupAckCount()
uint32_t TcpGeneralTest::GetDupAckCount (SocketWho who) protected
Get the number of dupack received.
Parameters
who node to get the parameter from
Returns
number of dupack
Definition at line 586 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by TcpFastRetrTest::CongStateTrace(), TcpFastRetrTest::ProcessedAck(), and TcpFastRetrTest::RcvAck().
GetHighestTxMark()
SequenceNumber32 TcpGeneralTest::GetHighestTxMark (SocketWho who) protected
Get the highest tx mark of the node specified.
Parameters
who node to get the parameter from
Returns
mark of the specified node
Definition at line 654 of file tcp-general-test.cc.
References GetTcb(), and ns3::TcpSocketState::m_highTxMark.
GetInitialCwnd()
uint32_t TcpGeneralTest::GetInitialCwnd (SocketWho who) protected
Get the initial congestion window.
Parameters
who node to get the parameter from
Returns
initial cwnd
Definition at line 660 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
GetInitialSsThresh()
uint32_t TcpGeneralTest::GetInitialSsThresh (SocketWho who) protected
Get the initial slow start threshold.
Parameters
who node to get the parameter from
Returns
initial slow start threshold
Definition at line 677 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by TcpLinuxRenoSSTest::CWndTrace(), and TcpSlowStartNormalTest::CWndTrace().
GetMinRto()
Time TcpGeneralTest::GetMinRto (SocketWho who) protected
Get the minimum RTO attribute.
Parameters
who node to get the parameter from
Returns
minimum RTO time
Definition at line 711 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by TcpTimeRtoTest::Tx().
GetMtu()
uint32_t ns3::TcpGeneralTest::GetMtu (void) const inline protected
Get the MTU of the environment.
Returns
MTU of the environment
Definition at line 1003 of file tcp-general-test.h.
References m_mtu.
GetPersistentEvent()
EventId TcpGeneralTest::GetPersistentEvent (SocketWho who) protected
Get the persistent event of the selected socket.
Parameters
who socket where check the parameter
Returns
the persistent event in the selected socket
Definition at line 815 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by TcpZeroWindowTest::ProcessedAck().
GetPersistentTimeout()
Time TcpGeneralTest::GetPersistentTimeout (SocketWho who) protected
Get the persistent timeout of the selected socket.
Parameters
who socket where check the parameter
Returns
the persistent timeout in the selected socket
Definition at line 833 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
GetPktCount()
uint32_t ns3::TcpGeneralTest::GetPktCount () const inline protected
Get the number of application packets.
Returns
count of application packets to be generated
Definition at line 1021 of file tcp-general-test.h.
References m_pktCount.
GetPktInterval()
Time ns3::TcpGeneralTest::GetPktInterval () const inline protected
Get the interval to wait for each packet sent down from application to TCP.
Returns
interval between packet
Definition at line 1031 of file tcp-general-test.h.
References m_interPacketInterval.
GetPktSize()
uint32_t ns3::TcpGeneralTest::GetPktSize () const inline protected
Get the application packet size.
Returns
application packet size
Definition at line 1012 of file tcp-general-test.h.
References m_pktSize.
GetPropagationDelay()
Time ns3::TcpGeneralTest::GetPropagationDelay () const inline protected
Get the channel Propagation Delay.
Returns
propagation delay of the channel
Definition at line 985 of file tcp-general-test.h.
References m_propagationDelay.
Referenced by TcpPacingTest::UpdateExpectedInterval().
GetReceiverSocket()
Ptr<TcpSocketMsgBase> ns3::TcpGeneralTest::GetReceiverSocket () inline protected
Get the pointer to a previously created receiver socket.
Returns
ptr to receiver socket or 0
Definition at line 352 of file tcp-general-test.h.
References m_receiverSocket.
Referenced by ns3::TcpCloseWithLossTestCase::ConfigureProperties().
GetReTxThreshold()
uint32_t TcpGeneralTest::GetReTxThreshold (SocketWho who) protected
Get the retransmission threshold.
Parameters
who node to get the parameter from
Returns
retransmission threshold
Definition at line 569 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by TcpFastRetrTest::CongStateTrace(), TcpFastRetrTest::ProcessedAck(), and TcpFastRetrTest::RcvAck().
GetRto()
Time TcpGeneralTest::GetRto (SocketWho who) protected
Get the retransmission time.
Parameters
who node to get the parameter from
Returns
calculated RTO time
Definition at line 694 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by TcpTimeRtoTest::AfterRTOExpired(), and TcpTimeRtoTest::Tx().
GetRttEstimator()
Ptr< RttEstimator > TcpGeneralTest::GetRttEstimator (SocketWho who) protected
Get the Rtt estimator of the socket.
Parameters
who node to get the parameter from
Returns
Rtt estimator
Definition at line 745 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by TcpTimeRtoTest::Tx(), and TcpRttEstimationTest::Tx().
GetRWnd()
uint32_t TcpGeneralTest::GetRWnd (SocketWho who) protected
Get the rWnd of the selected socket.
Parameters
who socket where check the parameter
Returns
the received advertised window
Definition at line 797 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
GetRxBuffer()
Ptr< TcpRxBuffer > TcpGeneralTest::GetRxBuffer (SocketWho who) protected
Get the Rx buffer from selected socket.
Parameters
who socket where get the TCB
Returns
the rx buffer
Definition at line 869 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by WScalingTestCase::Tx().
GetSegSize()
uint32_t TcpGeneralTest::GetSegSize (SocketWho who) protected
Get the segment size of the node specified.
Parameters
who node to get the parameter from
Returns
segment size of the specified node
Definition at line 637 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by TcpNewRenoCongAvoidNormalTest::Check(), TcpLinuxRenoSSTest::CWndTrace(), TcpSlowStartNormalTest::CWndTrace(), TcpPktsAckedOpenTest::FinalChecks(), TcpBytesInFlightTest::Rx(), TcpFastRetrTest::Rx(), TcpSlowStartNormalTest::Rx(), TcpFastRetrTest::Tx(), and TcpSlowStartNormalTest::Tx().
GetSenderSocket()
Ptr<TcpSocketMsgBase> ns3::TcpGeneralTest::GetSenderSocket () inline protected
Get the pointer to a previously created sender socket.
Returns
ptr to sender socket or 0
Definition at line 343 of file tcp-general-test.h.
References m_senderSocket.
Referenced by TcpSsThreshRtoTest::AfterRTOExpired(), TcpBytesInFlightTest::BeforeRTOExpired(), ns3::TcpCloseWithLossTestCase::BytesAvailable(), and ns3::TcpCloseWithLossTestCase::ConfigureProperties().
GetStartTime()
Time ns3::TcpGeneralTest::GetStartTime () const inline protected
Get the data start time.
Returns
start time of data packets
Definition at line 994 of file tcp-general-test.h.
References m_startTime.
GetTcb()
Ptr< TcpSocketState > TcpGeneralTest::GetTcb (SocketWho who) protected
Get the TCB from selected socket.
Parameters
who socket where get the TCB
Returns
the transmission control block
Definition at line 851 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by GetHighestTxMark(), and TcpZeroWindowTest::Tx().
GetTcpState()
TcpSocket::TcpStates_t TcpGeneralTest::GetTcpState (SocketWho who) protected
Get the state of the TCP state machine.
Parameters
who socket where check the parameter
Returns
the state of the socket
Definition at line 779 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
GetTxBuffer()
Ptr< TcpTxBuffer > TcpGeneralTest::GetTxBuffer (SocketWho who) protected
Get the Tx buffer from selected socket.
Parameters
who socket where get the TCB
Returns
the tx buffer
Definition at line 887 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
HandleAccept()
void TcpGeneralTest::HandleAccept (Ptr< Socket > socket, const Address & from) private
Handle an accept connection.
Parameters
socket The socket.
from The sender.
Definition at line 258 of file tcp-general-test.cc.
References ErrorCloseCb(), ns3::MakeCallback(), NormalCloseCb(), ReceivePacket(), ns3::Socket::SetCloseCallbacks(), and ns3::Socket::SetRecvCallback().
Referenced by DoRun().
HighestTxSeqTrace()
virtual void ns3::TcpGeneralTest::HighestTxSeqTrace (SequenceNumber32 oldValue, SequenceNumber32 newValue) inline protected virtual
Highest tx seq changes.
This applies only for sender socket.
Parameters
oldValue old value
newValue new value
Definition at line 808 of file tcp-general-test.h.
References NS_UNUSED.
Referenced by DoRun().
NextTxSeqTrace()
virtual void ns3::TcpGeneralTest::NextTxSeqTrace (SequenceNumber32 oldValue, SequenceNumber32 newValue) inline protected virtual
Next tx seq changes.
This applies only for sender socket.
Parameters
oldValue old value
newValue new value
Definition at line 794 of file tcp-general-test.h.
References NS_UNUSED.
Referenced by DoRun().
NormalClose()
virtual void ns3::TcpGeneralTest::NormalClose (SocketWho who) inline protected virtual
Socket closed normally.
Parameters
who the socket closed (SENDER or RECEIVER)
Reimplemented in TcpZeroWindowTest, TcpPacingTest, TcpNewRenoCongAvoidNormalTest, and ns3::TcpCloseWithLossTestCase.
Definition at line 836 of file tcp-general-test.h.
References NS_UNUSED.
Referenced by NormalCloseCb().
NormalCloseCb()
void TcpGeneralTest::NormalCloseCb (Ptr< Socket > socket) private
Normal Close Callback.
Parameters
socket The socket.
Definition at line 371 of file tcp-general-test.cc.
References ns3::Socket::GetNode(), m_receiverSocket, m_senderSocket, NormalClose(), NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by DoRun(), and HandleAccept().
PhyDrop()
virtual void ns3::TcpGeneralTest::PhyDrop (SocketWho who) inline protected virtual
Link drop.
Parameters
who where the drop occurred (SENDER or RECEIVER)
Reimplemented in TcpSlowStartNormalTest, TcpPacingTest, TcpLinuxRenoCongAvoidTest, TcpLinuxRenoSSTest, and TcpNewRenoCongAvoidNormalTest.
Definition at line 865 of file tcp-general-test.h.
References NS_UNUSED.
Referenced by PhyDropCb().
PhyDropCb()
void TcpGeneralTest::PhyDropCb (std::string context, Ptr< const Packet > p) private
Drop at Phy layer Callback.
Parameters
context The context.
p The packet.
Definition at line 353 of file tcp-general-test.cc.
References NS_FATAL_ERROR, NS_UNUSED, PhyDrop(), RECEIVER, and SENDER.
Referenced by DoRun().
ProcessedAck()
virtual void ns3::TcpGeneralTest::ProcessedAck (const Ptr< const TcpSocketState > tcb, const TcpHeader & h, SocketWho who) inline protected virtual
Processed ack.
Invoked after the processing of the ACK
Parameters
tcb Transmission Control Block
h the header of segment
who the socket which has processed the ACK (SENDER or RECEIVER)
Reimplemented in TcpZeroWindowTest, TcpRtoTest, and TcpFastRetrTest.
Definition at line 896 of file tcp-general-test.h.
References NS_UNUSED.
Referenced by ProcessedAckCb().
ProcessedAckCb()
void TcpGeneralTest::ProcessedAckCb (Ptr< const Packet > p, const TcpHeader & h, Ptr< const TcpSocketBase > tcp) private
ACK processed Callback.
Parameters
p The packet.
h TCP header.
tcp The TCP socket.
Definition at line 543 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, ProcessedAck(), RECEIVER, and SENDER.
Referenced by DoRun().
QueueDrop()
virtual void ns3::TcpGeneralTest::QueueDrop (SocketWho who) inline protected virtual
Drop on the queue.
Parameters
who where the drop occurred (SENDER or RECEIVER)
Reimplemented in TcpSlowStartNormalTest, TcpPacingTest, TcpLinuxRenoCongAvoidTest, TcpLinuxRenoSSTest, and TcpNewRenoCongAvoidNormalTest.
Definition at line 856 of file tcp-general-test.h.
References NS_UNUSED.
Referenced by QueueDropCb().
QueueDropCb()
void TcpGeneralTest::QueueDropCb (std::string context, Ptr< const Packet > p) private
Queue Drop Callback.
Parameters
context The context.
p The packet.
Definition at line 336 of file tcp-general-test.cc.
References NS_FATAL_ERROR, QueueDrop(), RECEIVER, and SENDER.
Referenced by DoRun().
RateSampleUpdatedTrace()
virtual void ns3::TcpGeneralTest::RateSampleUpdatedTrace (const TcpRateLinux::TcpRateSample & sample) inline protected virtual
Track the rate sample value of TcpRateLinux.
Parameters
sample updated value of TcpRateSample.
Definition at line 827 of file tcp-general-test.h.
References NS_UNUSED.
Referenced by DoRun().
RateUpdatedTrace()
virtual void ns3::TcpGeneralTest::RateUpdatedTrace (const TcpRateLinux::TcpRateConnection & rate) inline protected virtual
Track the rate value of TcpRateLinux.
Parameters
rate updated value of TcpRate.
Definition at line 818 of file tcp-general-test.h.
References NS_UNUSED.
Referenced by DoRun().
RcvAck()
virtual void ns3::TcpGeneralTest::RcvAck (const Ptr< const TcpSocketState > tcb, const TcpHeader & h, SocketWho who) inline protected virtual
Received ack.
Invoked when an ACK is received (no processing is done yet)
Parameters
tcb Transmission Control Block
h the header of segment
who the socket which has received the ACK (SENDER or RECEIVER)
Reimplemented in TcpRtoTest, and TcpFastRetrTest.
Definition at line 879 of file tcp-general-test.h.
References NS_UNUSED.
Referenced by RcvAckCb().
RcvAckCb()
void TcpGeneralTest::RcvAckCb (Ptr< const Packet > p, const TcpHeader & h, Ptr< const TcpSocketBase > tcp) private
Receive ACK Callback.
Parameters
p The packet.
h TCP header.
tcp The TCP socket.
Definition at line 489 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RcvAck(), RECEIVER, and SENDER.
Referenced by DoRun().
ReceivePacket()
void TcpGeneralTest::ReceivePacket (Ptr< Socket > socket) protected virtual
Packet received.
The method processes the packet (application-layer)
Parameters
socket socket which has received the packet
Definition at line 57 of file tcp-general-test.cc.
References ns3::Packet::GetSize(), NS_LOG_FUNCTION, and ns3::Socket::RecvFrom().
Referenced by DoRun(), and HandleAccept().
RtoExpiredCb()
void ns3::TcpGeneralTest::RtoExpiredCb (const Ptr< const TcpSocketState > tcb, const Ptr< const TcpSocketBase > tcp) private
RTO expired Callback.
Parameters
tcb Transmission control block.
tcp The TCP socket.
RtoTrace()
virtual void ns3::TcpGeneralTest::RtoTrace (Time oldValue, Time newValue) inline protected virtual
RTO changes.
This applies only for sender socket.
Parameters
oldValue old value
newValue new value
Definition at line 780 of file tcp-general-test.h.
References NS_UNUSED.
Referenced by DoRun().
RttTrace()
virtual void ns3::TcpGeneralTest::RttTrace (Time oldTime, Time newTime) inline protected virtual
Rtt changes.
This applies only for sender socket.
Parameters
oldTime old value
newTime new value
Reimplemented in TcpRttEstimationTest, and TcpPacingTest.
Definition at line 738 of file tcp-general-test.h.
References NS_UNUSED.
Referenced by DoRun().
Rx()
void TcpGeneralTest::Rx (const Ptr< const Packet > p, const TcpHeader & h, SocketWho who) protected virtual
Packet received from IP layer.
Parameters
p packet
h header
who the socket which has received the packet (SENDER or RECEIVER)
Reimplemented in TcpZeroWindowTest, TimestampTestCase, TcpSlowStartNormalTest, TcpRttEstimationTest, TcpRateLinuxWithSocketsTest, TcpPktsAckedOpenTest, TcpPacingTest, TcpLargeTransferLossTest, TcpLinuxRenoCongAvoidTest, TcpLinuxRenoSSTest, TcpFastRetrTest, ns3::TcpEcnTest, TcpDctcpCodePointsTest, ns3::TcpCloseWithLossTestCase, and TcpBytesInFlightTest.
Definition at line 483 of file tcp-general-test.cc.
References NS_LOG_FUNCTION.
Referenced by RxPacketCb().
RxPacketCb()
void TcpGeneralTest::RxPacketCb (const Ptr< const Packet > p, const TcpHeader & h, const Ptr< const TcpSocketBase > tcp) private
Rx packet Callback.
Parameters
p The packet.
h TCP header.
tcp The TCP socket.
Definition at line 525 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, Rx(), and SENDER.
Referenced by DoRun().
SendPacket()
void TcpGeneralTest::SendPacket (Ptr< Socket > socket, uint32_t pktSize, uint32_t pktCount, Time pktInterval) protected
Send packets to other endpoint.
Parameters
socket Socket
pktSize size of the packet
pktCount number of packets to send
pktInterval interval between packet (application-level)
Definition at line 73 of file tcp-general-test.cc.
References ns3::Socket::Close(), ns3::Time::GetSeconds(), NS_LOG_FUNCTION, pktSize, ns3::Simulator::Schedule(), and ns3::Socket::Send().
Referenced by DoRun().
SetAppPktCount()
void ns3::TcpGeneralTest::SetAppPktCount (uint32_t pktCount) inline protected
Set app packet count.
The application will generate this count of packets.
Parameters
pktCount count of packets to generate
Definition at line 650 of file tcp-general-test.h.
References m_pktCount.
Referenced by TcpAdvertisedWindowTest::ConfigureEnvironment(), TcpAdvWindowOnLossTest::ConfigureEnvironment(), TcpBytesInFlightTest::ConfigureEnvironment(), TcpNewRenoCongAvoidNormalTest::ConfigureEnvironment(), TcpFastRetrTest::ConfigureEnvironment(), TcpLinuxRenoSSTest::ConfigureEnvironment(), TcpLinuxRenoCongAvoidTest::ConfigureEnvironment(), TcpPacingTest::ConfigureEnvironment(), TcpPktsAckedOpenTest::ConfigureEnvironment(), TcpRateLinuxWithSocketsTest::ConfigureEnvironment(), TcpRtoTest::ConfigureEnvironment(), TcpSsThreshRtoTest::ConfigureEnvironment(), TcpTimeRtoTest::ConfigureEnvironment(), TcpRttEstimationTest::ConfigureEnvironment(), TcpSlowStartNormalTest::ConfigureEnvironment(), TcpZeroWindowTest::ConfigureEnvironment(), ConfigureEnvironment(), TcpLargeTransferLossTest::ConfigureEnvironment(), and ns3::TcpCloseWithLossTestCase::ConfigureProperties().
SetAppPktInterval()
void ns3::TcpGeneralTest::SetAppPktInterval (Time pktInterval) inline protected
Interval between app-generated packet.
Parameters
pktInterval interval
Definition at line 657 of file tcp-general-test.h.
References m_interPacketInterval.
Referenced by TcpPacingTest::ConfigureEnvironment(), TcpSsThreshRtoTest::ConfigureEnvironment(), ConfigureEnvironment(), TcpLargeTransferLossTest::ConfigureEnvironment(), and ns3::TcpCloseWithLossTestCase::ConfigureProperties().
SetAppPktSize()
void ns3::TcpGeneralTest::SetAppPktSize (uint32_t pktSize) inline protected
Set app packet size.
The application will generate packet of this size.
Parameters
pktSize size of the packet
Definition at line 641 of file tcp-general-test.h.
References m_pktSize, and pktSize.
Referenced by TcpAdvertisedWindowTest::ConfigureEnvironment(), TcpAdvWindowOnLossTest::ConfigureEnvironment(), TcpNewRenoCongAvoidNormalTest::ConfigureEnvironment(), TcpLinuxRenoSSTest::ConfigureEnvironment(), TcpLinuxRenoCongAvoidTest::ConfigureEnvironment(), TcpPacingTest::ConfigureEnvironment(), TcpSlowStartNormalTest::ConfigureEnvironment(), ConfigureEnvironment(), TcpLargeTransferLossTest::ConfigureEnvironment(), and ns3::TcpCloseWithLossTestCase::ConfigureProperties().
SetCongestionControl()
void ns3::TcpGeneralTest::SetCongestionControl (TypeId congControl) inline protected
Congestion control of the sender socket.
Parameters
congControl typeid of the congestion control algorithm
Definition at line 678 of file tcp-general-test.h.
References m_congControlTypeId.
Referenced by ConfigureEnvironment().
SetDelAckMaxCount()
void TcpGeneralTest::SetDelAckMaxCount (SocketWho who, uint32_t count) protected
Forcefully set the delayed acknowledgement count.
Parameters
who socket to force
count value of delayed ACKs
Definition at line 955 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by TcpLinuxRenoSSTest::ConfigureProperties(), TcpLinuxRenoCongAvoidTest::ConfigureProperties(), and TcpPacingTest::ConfigureProperties().
SetInitialCwnd()
void TcpGeneralTest::SetInitialCwnd (SocketWho who, uint32_t initialCwnd) protected
Forcefully set the initial cwnd.
Parameters
who socket to force
initialCwnd size of the initial cwnd (segments)
Definition at line 939 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by ns3::TcpCloseWithLossTestCase::ConfigureProperties(), TcpLinuxRenoSSTest::ConfigureProperties(), TcpLinuxRenoCongAvoidTest::ConfigureProperties(), TcpPacingTest::ConfigureProperties(), TcpZeroWindowTest::ConfigureProperties(), and ConfigureProperties().
SetInitialSsThresh()
void TcpGeneralTest::SetInitialSsThresh (SocketWho who, uint32_t initialSsThresh) protected
Forcefully set the initial ssthresh.
Parameters
who socket to force
initialSsThresh Initial slow start threshold (bytes)
Definition at line 1022 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by TcpNewRenoCongAvoidNormalTest::ConfigureProperties(), TcpFastRetrTest::ConfigureProperties(), TcpLinuxRenoCongAvoidTest::ConfigureProperties(), TcpPacingTest::ConfigureProperties(), TcpRtoTest::ConfigureProperties(), TcpSlowStartNormalTest::ConfigureProperties(), and ConfigureProperties().
SetMTU()
void ns3::TcpGeneralTest::SetMTU (uint32_t mtu) inline protected
MTU of the bottleneck link.
Parameters
mtu MTU
Definition at line 692 of file tcp-general-test.h.
References m_mtu.
Referenced by TcpNewRenoCongAvoidNormalTest::ConfigureEnvironment(), TcpLinuxRenoCongAvoidTest::ConfigureEnvironment(), TcpPacingTest::ConfigureEnvironment(), TcpPktsAckedOpenTest::ConfigureEnvironment(), TcpRttEstimationTest::ConfigureEnvironment(), TcpZeroWindowTest::ConfigureEnvironment(), ConfigureEnvironment(), and ns3::TcpCloseWithLossTestCase::ConfigureProperties().
SetPaceInitialWindow()
void TcpGeneralTest::SetPaceInitialWindow (SocketWho who, bool paceWindow) protected
Enable or disable pacing of the initial window.
Parameters
who socket
pacing Boolean to enable or disable pacing of initial window
Definition at line 1005 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by TcpPacingTest::ConfigureProperties().
SetPacingStatus()
void TcpGeneralTest::SetPacingStatus (SocketWho who, bool pacing) protected
Enable or disable pacing in the TCP socket.
Parameters
who socket
pacing Boolean to enable or disable pacing
Definition at line 988 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by TcpPacingTest::ConfigureProperties().
SetPropagationDelay()
void ns3::TcpGeneralTest::SetPropagationDelay (Time propDelay) inline protected
Propagation delay of the bottleneck link.
Parameters
propDelay propagation delay
Definition at line 664 of file tcp-general-test.h.
References m_propagationDelay.
Referenced by TcpAdvertisedWindowTest::ConfigureEnvironment(), TcpAdvWindowOnLossTest::ConfigureEnvironment(), TcpBytesInFlightTest::ConfigureEnvironment(), TcpLinuxRenoSSTest::ConfigureEnvironment(), TcpPacingTest::ConfigureEnvironment(), TcpRateLinuxWithSocketsTest::ConfigureEnvironment(), TcpSsThreshRtoTest::ConfigureEnvironment(), TcpRttEstimationTest::ConfigureEnvironment(), TcpZeroWindowTest::ConfigureEnvironment(), ConfigureEnvironment(), and TcpLargeTransferLossTest::ConfigureEnvironment().
SetRcvBufSize()
void TcpGeneralTest::SetRcvBufSize (SocketWho who, uint32_t size) protected
Forcefully set a defined size for rx buffer.
Parameters
who socket to force
size size of the rx buffer
Definition at line 905 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by TcpZeroWindowTest::IncreaseBufSize().
SetRecoveryAlgorithm()
void ns3::TcpGeneralTest::SetRecoveryAlgorithm (TypeId reccovery) inline protected
recovery algorithm of the sender socket
Parameters
recovery typeid of the recovery algorithm
Definition at line 685 of file tcp-general-test.h.
References m_recoveryTypeId.
Referenced by ConfigureEnvironment().
SetSegmentSize()
void TcpGeneralTest::SetSegmentSize (SocketWho who, uint32_t segmentSize) protected
Forcefully set the segment size.
Parameters
who socket to force
segmentSize segmentSize
Definition at line 922 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, segmentSize, and SENDER.
Referenced by ns3::TcpCloseWithLossTestCase::ConfigureProperties(), TcpNewRenoCongAvoidNormalTest::ConfigureProperties(), TcpLinuxRenoSSTest::ConfigureProperties(), TcpLinuxRenoCongAvoidTest::ConfigureProperties(), TcpPacingTest::ConfigureProperties(), TcpSlowStartNormalTest::ConfigureProperties(), ConfigureProperties(), and TcpLargeTransferLossTest::ConfigureProperties().
SetTransmitStart()
void ns3::TcpGeneralTest::SetTransmitStart (Time startTime) inline protected
Set the initial time at which the application sends the first data packet.
Parameters
startTime start time
Definition at line 671 of file tcp-general-test.h.
References m_startTime, and startTime.
Referenced by TcpAdvertisedWindowTest::ConfigureEnvironment(), TcpAdvWindowOnLossTest::ConfigureEnvironment(), TcpBytesInFlightTest::ConfigureEnvironment(), TcpPacingTest::ConfigureEnvironment(), TcpRateLinuxWithSocketsTest::ConfigureEnvironment(), TcpRttEstimationTest::ConfigureEnvironment(), TcpZeroWindowTest::ConfigureEnvironment(), ConfigureEnvironment(), and TcpLargeTransferLossTest::ConfigureEnvironment().
SetUseEcn()
void TcpGeneralTest::SetUseEcn (SocketWho who, TcpSocketState::UseEcn_t useEcn) protected
Forcefully set the ECN mode of use.
Parameters
who socket to force
useEcn Value representing the mode of ECN usage requested
Definition at line 971 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, and SENDER.
Referenced by TcpDctcpCodePointsTest::ConfigureProperties(), and ns3::TcpEcnTest::ConfigureProperties().
SsThreshTrace()
virtual void ns3::TcpGeneralTest::SsThreshTrace (uint32_t oldValue, uint32_t newValue) inline protected virtual
Slow start threshold changes.
This applies only for sender socket.
Parameters
oldValue old value
newValue new value
Reimplemented in TcpSsThreshRtoTest.
Definition at line 752 of file tcp-general-test.h.
References NS_UNUSED.
Referenced by DoRun().
Tx()
void TcpGeneralTest::Tx (const Ptr< const Packet > p, const TcpHeader & h, SocketWho who) protected virtual
Packet transmitted down to IP layer.
Parameters
p packet
h header
who the socket which has received the packet (SENDER or RECEIVER)
Reimplemented in TcpZeroWindowTest, WScalingTestCase, TimestampTestCase, TcpSlowStartNormalTest, SackPermittedTestCase, TcpRttEstimationTest, TcpTimeRtoTest, TcpPacingTest, TcpLargeTransferLossTest, TcpLinuxRenoCongAvoidTest, TcpLinuxRenoSSTest, TcpFastRetrTest, ns3::TcpEcnTest, TcpDctcpCodePointsTest, ns3::TcpCloseWithLossTestCase, and TcpBytesInFlightTest.
Definition at line 477 of file tcp-general-test.cc.
References NS_LOG_FUNCTION.
Referenced by TxPacketCb().
TxPacketCb()
void TcpGeneralTest::TxPacketCb (const Ptr< const Packet > p, const TcpHeader & h, const Ptr< const TcpSocketBase > tcp) private
Tx packet Callback.
Parameters
p The packet.
h TCP header.
tcp The TCP socket.
Definition at line 507 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, SENDER, and Tx().
Referenced by DoRun().
UpdatedRttHistory()
virtual void ns3::TcpGeneralTest::UpdatedRttHistory (const SequenceNumber32 & seq, uint32_t sz, bool isRetransmission, SocketWho who) inline protected virtual
Updated the Rtt history.
Parameters
seq Sequence inserted
sz size
isRetransmission self-explanatory
who where the rtt history was updated
Reimplemented in TcpRttEstimationTest.
Definition at line 953 of file tcp-general-test.h.
References NS_UNUSED.
Referenced by UpdateRttHistoryCb().
UpdateRttHistoryCb()
void TcpGeneralTest::UpdateRttHistoryCb (Ptr< const TcpSocketBase > tcp, const SequenceNumber32 & seq, uint32_t sz, bool isRetransmission) private
Update RTT with new data.
Parameters
tcp The TCP socket.
seq The sequence number.
sz The segment size.
isRetransmission True if packet is a retransmission.
Definition at line 388 of file tcp-general-test.cc.
References m_receiverSocket, m_senderSocket, NS_FATAL_ERROR, RECEIVER, SENDER, and UpdatedRttHistory().
Referenced by DoRun().
Member Data Documentation
m_congControlTypeId
TypeId ns3::TcpGeneralTest::m_congControlTypeId protected
Congestion control.
Definition at line 1036 of file tcp-general-test.h.
Referenced by TcpFastRetrTest::TcpFastRetrTest(), TcpLinuxRenoCongAvoidTest::TcpLinuxRenoCongAvoidTest(), TcpLinuxRenoSSTest::TcpLinuxRenoSSTest(), TcpNewRenoCongAvoidNormalTest::TcpNewRenoCongAvoidNormalTest(), TcpPacingTest::TcpPacingTest(), TcpRtoTest::TcpRtoTest(), TcpSlowStartNormalTest::TcpSlowStartNormalTest(), TcpSsThreshRtoTest::TcpSsThreshRtoTest(), TcpTimeRtoTest::TcpTimeRtoTest(), ConfigureEnvironment(), TcpAdvertisedWindowTest::CreateReceiverSocket(), TcpAdvWindowOnLossTest::CreateReceiverSocket(), CreateReceiverSocket(), TcpSlowStartAttackerTest::CreateReceiverSocket(), ns3::TcpEcnTest::CreateSenderSocket(), CreateSenderSocket(), and SetCongestionControl().
m_interPacketInterval
Time ns3::TcpGeneralTest::m_interPacketInterval private
Time between sending application packet down to tcp socket.
Definition at line 1049 of file tcp-general-test.h.
Referenced by DoRun(), GetPktInterval(), and SetAppPktInterval().
m_mtu
uint32_t ns3::TcpGeneralTest::m_mtu private
MTU of the environment.
Definition at line 1045 of file tcp-general-test.h.
Referenced by DoRun(), GetMtu(), and SetMTU().
m_pktCount
uint32_t ns3::TcpGeneralTest::m_pktCount private
Count of the application packet.
Definition at line 1048 of file tcp-general-test.h.
Referenced by DoRun(), GetPktCount(), and SetAppPktCount().
m_pktSize
uint32_t ns3::TcpGeneralTest::m_pktSize private
Size of the application packet.
Definition at line 1047 of file tcp-general-test.h.
Referenced by DoRun(), GetPktSize(), and SetAppPktSize().
m_propagationDelay
Time ns3::TcpGeneralTest::m_propagationDelay private
Propagation delay of the channel.
Definition at line 1042 of file tcp-general-test.h.
Referenced by CreateChannel(), GetPropagationDelay(), and SetPropagationDelay().
m_receiverSocket
Ptr<TcpSocketMsgBase> ns3::TcpGeneralTest::m_receiverSocket private
Pointer to receiver socket.
Definition at line 1052 of file tcp-general-test.h.
Referenced by AfterRetransmitCb(), BeforeRetransmitCb(), DataSentCb(), DoRun(), ErrorCloseCb(), ForkCb(), GetClockGranularity(), GetConnTimeout(), GetDelAckCount(), GetDelAckTimeout(), GetDupAckCount(), GetInitialCwnd(), GetInitialSsThresh(), GetMinRto(), GetPersistentEvent(), GetPersistentTimeout(), GetReceiverSocket(), GetReTxThreshold(), GetRto(), GetRttEstimator(), GetRWnd(), GetRxBuffer(), GetSegSize(), GetTcb(), GetTcpState(), GetTxBuffer(), NormalCloseCb(), ProcessedAckCb(), RcvAckCb(), RxPacketCb(), SetDelAckMaxCount(), SetInitialCwnd(), SetInitialSsThresh(), SetPaceInitialWindow(), SetPacingStatus(), SetRcvBufSize(), SetSegmentSize(), SetUseEcn(), TxPacketCb(), and UpdateRttHistoryCb().
m_recoveryTypeId
TypeId ns3::TcpGeneralTest::m_recoveryTypeId protected
Recovery.
Definition at line 1037 of file tcp-general-test.h.
Referenced by ConfigureEnvironment(), CreateReceiverSocket(), CreateSenderSocket(), CreateSocket(), and SetRecoveryAlgorithm().
m_remoteAddr
InetSocketAddress ns3::TcpGeneralTest::m_remoteAddr private
Remote peer address.
Definition at line 1162 of file tcp-general-test.h.
Referenced by DoConnect(), and DoRun().
m_senderSocket
Ptr<TcpSocketMsgBase> ns3::TcpGeneralTest::m_senderSocket private
Pointer to sender socket.
Definition at line 1051 of file tcp-general-test.h.
Referenced by AfterRetransmitCb(), BeforeRetransmitCb(), DataSentCb(), DoConnect(), DoRun(), ErrorCloseCb(), GetClockGranularity(), GetConnTimeout(), GetDelAckCount(), GetDelAckTimeout(), GetDupAckCount(), GetInitialCwnd(), GetInitialSsThresh(), GetMinRto(), GetPersistentEvent(), GetPersistentTimeout(), GetReTxThreshold(), GetRto(), GetRttEstimator(), GetRWnd(), GetRxBuffer(), GetSegSize(), GetSenderSocket(), GetTcb(), GetTcpState(), GetTxBuffer(), NormalCloseCb(), ProcessedAckCb(), RcvAckCb(), RxPacketCb(), SetDelAckMaxCount(), SetInitialCwnd(), SetInitialSsThresh(), SetPaceInitialWindow(), SetPacingStatus(), SetRcvBufSize(), SetSegmentSize(), SetUseEcn(), TxPacketCb(), and UpdateRttHistoryCb().
m_startTime
Time ns3::TcpGeneralTest::m_startTime private
Data transmission time.
Definition at line 1044 of file tcp-general-test.h.
Referenced by DoRun(), GetStartTime(), and SetTransmitStart().
The documentation for this class was generated from the following files:
src/internet/test/tcp-general-test.h
src/internet/test/tcp-general-test.cc