ns-3: ns3::LteRlcAm Class Reference
ns3::LteRlcAm Class Reference
LTE RLC Acknowledged Mode (AM), see 3GPP TS 36.322.
#include "lte-rlc-am.h"
Classes
struct PduBuffer
PduBuffer structure.
struct RetxPdu
RetxPdu structure.
struct TxPdu
Store an incoming (from layer above us) PDU, waiting to transmit it.
Public Member Functions
LteRlcAm ()
virtual ~LteRlcAm ()
virtual void DoDispose ()
Destructor implementation.
virtual void DoNotifyHarqDeliveryFailure ()
Notify HARQ delivery failure.
virtual void DoNotifyTxOpportunity (LteMacSapUser::TxOpportunityParameters txOpParams)
MAC SAP.
virtual void DoReceivePdu (LteMacSapUser::ReceivePduParameters rxPduParams)
Receive PDU function.
virtual void DoTransmitPdcpPdu (Ptr< Packet > p)
RLC SAP.
Public Member Functions inherited from ns3::LteRlc
LteRlc ()
virtual ~LteRlc ()
LteMacSapUser * GetLteMacSapUser ()
LteRlcSapProvider * GetLteRlcSapProvider ()
void SetLcId (uint8_t lcId)
void SetLteMacSapProvider (LteMacSapProvider *s)
void SetLteRlcSapUser (LteRlcSapUser *s)
void SetRnti (uint16_t rnti)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::LteRlc
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
enum ReassemblingState_t { NONE = 0 , WAITING_S0_FULL = 1 , WAITING_SI_SF = 2 }
SDU Reassembling state.
Private Member Functions
void DoReportBufferStatus ()
Report buffer status.
void ExpirePollRetransmitTimer (void)
Expire poll retransmitter.
void ExpireRbsTimer (void)
Expire RBS timer.
void ExpireReorderingTimer (void)
This method will schedule a timeout at WaitReplyTimeout interval in the future, unless a timer is already running for the cache, in which case this method does nothing.
void ExpireStatusProhibitTimer (void)
method called when the T_status_prohibit timer expires
bool IsInsideReceivingWindow (SequenceNumber10 seqNumber)
method called when the T_status_prohibit timer expires
void ReassembleAndDeliver (Ptr< Packet > packet)
Reassemble and deliver.
Private Attributes
uint32_t m_byteWithoutPoll
byte without poll
Ptr< Packet > m_controlPduBuffer
Control PDU buffer (just one PDU)
SequenceNumber10 m_expectedSeqNumber
Expected Sequence Number.
Ptr< Packet > m_keepS0
keep S0
uint16_t m_maxRetxThreshold
Configurable parameters.
uint32_t m_pduWithoutPoll
Counters.
uint16_t m_pollByte
poll byte
uint16_t m_pollPdu
poll PDU
EventId m_pollRetransmitTimer
Timers.
bool m_pollRetransmitTimerJustExpired
poll retransmit timer just expired?
Time m_pollRetransmitTimerValue
poll retransmit time value
SequenceNumber10 m_pollSn
POLL_SN.
EventId m_rbsTimer
RBS timer.
Time m_rbsTimerValue
RBS timer value.
ReassemblingState_t m_reassemblingState
reassembling state
EventId m_reorderingTimer
reordering timer
Time m_reorderingTimerValue
reordering timer value
std::vector< RetxPdu > m_retxBuffer
Buffer for PDUs considered for retransmission.
uint32_t m_retxBufferSize
retransmit buffer size
std::map< uint16_t, PduBuffer > m_rxonBuffer
Reception buffer.
std::list< Ptr< Packet > > m_sdusBuffer
List of SDUs in a packet (PDU)
uint32_t m_statusPduBufferSize
status PDU buffer size
bool m_statusPduRequested
status PDU requested
EventId m_statusProhibitTimer
status prohibit timer
Time m_statusProhibitTimerValue
status prohibit timer value
std::vector< RetxPdu > m_txedBuffer
Buffer for transmitted and retransmitted PDUs that have not been acked but are not considered for retransmission
uint32_t m_txedBufferSize
transmit ed buffer size
std::vector< TxPdu > m_txonBuffer
Transmission buffer.
uint32_t m_txonBufferSize
transmit on buffer size
bool m_txOpportunityForRetxAlwaysBigEnough
transmit opportunity for retransmit?
SequenceNumber10 m_vrH
VR(H)
SequenceNumber10 m_vrMr
VR(MR)
SequenceNumber10 m_vrMs
VR(MS)
SequenceNumber10 m_vrR
VR(R)
SequenceNumber10 m_vrX
VR(X)
SequenceNumber10 m_vtA
State variables.
SequenceNumber10 m_vtMs
VT(MS)
SequenceNumber10 m_vtS
VT(S)
uint16_t m_windowSize
Constants.
Additional Inherited Members
Public Types inherited from ns3::LteRlc
typedef void(* NotifyTxTracedCallback) (uint16_t rnti, uint8_t lcid, uint32_t bytes)
TracedCallback signature for NotifyTxOpportunity events.
typedef void(* ReceiveTracedCallback) (uint16_t rnti, uint8_t lcid, uint32_t bytes, uint64_t delay)
TracedCallback signature for.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::LteRlc
uint8_t m_lcid
LCID.
LteMacSapProvider * m_macSapProvider
MAC SAP provider.
LteMacSapUser * m_macSapUser
MAC SAP user.
LteRlcSapProvider * m_rlcSapProvider
RLC SAP provider.
LteRlcSapUser * m_rlcSapUser
RLC SAP user.
uint16_t m_rnti
RNTI.
TracedCallback< uint16_t, uint8_t, uint32_t, uint64_t > m_rxPdu
Used to inform of a PDU reception from the MAC SAP user.
TracedCallback< uint16_t, uint8_t, uint32_t > m_txPdu
Used to inform of a PDU delivery to the MAC SAP provider.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
LTE RLC Acknowledged Mode (AM), see 3GPP TS 36.322.
Config Paths
ns3::LteRlcAm is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteEnbNetDevice/LteEnbRrc/UeMap/[i]/DataRadioBearerMap/[i]/LteRlc/$ns3::LteRlcAm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteEnbNetDevice/LteEnbRrc/UeMap/[i]/Srb0/LteRlc/$ns3::LteRlcAm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteEnbNetDevice/LteEnbRrc/UeMap/[i]/Srb1/LteRlc/$ns3::LteRlcAm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteUeNetDevice/LteUeRrc/DataRadioBearerMap/[i]/LteRlc/$ns3::LteRlcAm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteUeNetDevice/LteUeRrc/Srb0/LteRlc/$ns3::LteRlcAm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteUeNetDevice/LteUeRrc/Srb1/LteRlc/$ns3::LteRlcAm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteEnbNetDevice/LteEnbRrc/UeMap/[i]/DataRadioBearerMap/[i]/LteRlc/$ns3::LteRlcAm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteEnbNetDevice/LteEnbRrc/UeMap/[i]/Srb0/LteRlc/$ns3::LteRlcAm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteEnbNetDevice/LteEnbRrc/UeMap/[i]/Srb1/LteRlc/$ns3::LteRlcAm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteUeNetDevice/LteUeRrc/DataRadioBearerMap/[i]/LteRlc/$ns3::LteRlcAm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteUeNetDevice/LteUeRrc/Srb0/LteRlc/$ns3::LteRlcAm"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteUeNetDevice/LteUeRrc/Srb1/LteRlc/$ns3::LteRlcAm"
Attributes
PollRetransmitTimer: Value of the t-PollRetransmit timer (See section 7.3 of 3GPP TS 36.322)
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +2e+07ns
Flags: construct write read
ReorderingTimer: Value of the t-Reordering timer (See section 7.3 of 3GPP TS 36.322)
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+07ns
Flags: construct write read
StatusProhibitTimer: Value of the t-StatusProhibit timer (See section 7.3 of 3GPP TS 36.322)
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+07ns
Flags: construct write read
ReportBufferStatusTimer: How much to wait to issue a new Report Buffer Status since the last time a new SDU was received
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +2e+07ns
Flags: construct write read
TxOpportunityForRetxAlwaysBigEnough: If true, always pretend that the size of a TxOpportunity is big enough for retransmission. If false (default and realistic behavior), no retx is performed unless the corresponding TxOpportunity is big enough.
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
No TraceSources are defined for this type.
TraceSources defined in parent class ns3::LteRlc
TxPDU: PDU transmission notified to the MAC.
Callback signature: ns3::LteRlc::NotifyTxTracedCallback
RxPDU: PDU received.
Callback signature: ns3::LteRlc::ReceiveTracedCallback
Size of this type is 480 bytes (on a 64-bit architecture).
Definition at line 36 of file lte-rlc-am.h.
Member Enumeration Documentation
ReassemblingState_t
enum ns3::LteRlcAm::ReassemblingState_t private
SDU Reassembling state.
Enumerator
NONE
WAITING_S0_FULL
WAITING_SI_SF
Definition at line 223 of file lte-rlc-am.h.
Constructor & Destructor Documentation
LteRlcAm()
ns3::LteRlcAm::LteRlcAm ()
Definition at line 38 of file lte-rlc-am.cc.
References m_byteWithoutPoll, m_expectedSeqNumber, m_maxRetxThreshold, m_pduWithoutPoll, m_pollByte, m_pollPdu, m_pollRetransmitTimerJustExpired, m_pollSn, m_reassemblingState, m_retxBuffer, m_retxBufferSize, m_statusPduBufferSize, m_statusPduRequested, m_txedBuffer, m_txedBufferSize, m_txonBufferSize, m_vrH, m_vrMr, m_vrMs, m_vrR, m_vrX, m_vtA, m_vtMs, m_vtS, m_windowSize, NS_LOG_FUNCTION, and WAITING_S0_FULL.
~LteRlcAm()
ns3::LteRlcAm::~LteRlcAm () virtual
Definition at line 82 of file lte-rlc-am.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::LteRlcAm::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::LteRlc.
Definition at line 128 of file lte-rlc-am.cc.
References ns3::EventId::Cancel(), ns3::LteRlc::DoDispose(), m_controlPduBuffer, m_keepS0, m_pollRetransmitTimer, m_rbsTimer, m_reorderingTimer, m_retxBuffer, m_retxBufferSize, m_rxonBuffer, m_sdusBuffer, m_statusProhibitTimer, m_txedBuffer, m_txedBufferSize, m_txonBuffer, m_txonBufferSize, and NS_LOG_FUNCTION.
DoNotifyHarqDeliveryFailure()
void ns3::LteRlcAm::DoNotifyHarqDeliveryFailure () virtual
Notify HARQ delivery failure.
Implements ns3::LteRlc.
Definition at line 748 of file lte-rlc-am.cc.
References NS_LOG_FUNCTION.
DoNotifyTxOpportunity()
void ns3::LteRlcAm::DoNotifyTxOpportunity (LteMacSapUser::TxOpportunityParameters txOpParams) virtual
MAC SAP.
Parameters
txOpParams the LteMacSapUser::TxOpportunityParameters
Implements ns3::LteRlc.
Definition at line 184 of file lte-rlc-am.cc.
References ns3::Packet::AddAtEnd(), ns3::Packet::AddByteTag(), ns3::Packet::AddHeader(), ns3::Packet::AddPacketTag(), ns3::LteMacSapUser::TxOpportunityParameters::bytes, ns3::EventId::Cancel(), ns3::LteMacSapProvider::TransmitPduParameters::componentCarrierId, ns3::LteMacSapUser::TxOpportunityParameters::componentCarrierId, ns3::Packet::Copy(), ns3::Packet::CreateFragment(), ns3::LteRlcAmHeader::DATA_FIELD_FOLLOWS, ns3::LteRlcAmHeader::E_LI_FIELDS_FOLLOWS, ExpirePollRetransmitTimer(), ExpireStatusProhibitTimer(), ns3::LteRlcAmHeader::FIRST_BYTE, ns3::LteRlcSduStatusTag::FIRST_SEGMENT, ns3::LteRlcSduStatusTag::FULL_SDU, ns3::LteRlcAmHeader::GetSequenceNumber(), ns3::LteRlcAmHeader::GetSerializedSize(), ns3::Packet::GetSize(), ns3::LteRlcSduStatusTag::GetStatus(), ns3::SequenceNumber10::GetValue(), ns3::LteMacSapUser::TxOpportunityParameters::harqId, ns3::LteMacSapProvider::TransmitPduParameters::harqProcessId, ns3::EventId::IsRunning(), ns3::LteRlcAmHeader::LAST_BYTE, ns3::LteRlcAmHeader::LAST_PDU_SEGMENT, ns3::LteRlcSduStatusTag::LAST_SEGMENT, ns3::LteMacSapProvider::TransmitPduParameters::layer, ns3::LteMacSapUser::TxOpportunityParameters::layer, ns3::LteMacSapProvider::TransmitPduParameters::lcid, m_byteWithoutPoll, ns3::LteRlc::m_lcid, ns3::LteRlc::m_macSapProvider, m_maxRetxThreshold, m_pduWithoutPoll, m_pollByte, m_pollPdu, m_pollRetransmitTimer, m_pollRetransmitTimerJustExpired, m_pollRetransmitTimerValue, m_pollSn, m_retxBuffer, m_retxBufferSize, ns3::LteRlc::m_rnti, m_rxonBuffer, m_statusPduBufferSize, m_statusPduRequested, m_statusProhibitTimer, m_statusProhibitTimerValue, m_txedBuffer, m_txedBufferSize, m_txonBuffer, m_txonBufferSize, m_txOpportunityForRetxAlwaysBigEnough, ns3::LteRlc::m_txPdu, m_vrMs, m_vrR, m_vtA, m_vtMs, m_vtS, ns3::LteRlcSduStatusTag::MIDDLE_SEGMENT, ns3::MilliSeconds(), min, ns3::LteRlcAmHeader::NO_FIRST_BYTE, ns3::LteRlcAmHeader::NO_LAST_BYTE, ns3::Simulator::Now(), NS_ASSERT, NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, ns3::LteRlcAmHeader::OneMoreNackWouldFitIn(), ns3::LteMacSapProvider::TransmitPduParameters::pdu, ns3::LteRlcAmHeader::PDU, ns3::LteRlcAmHeader::PushExtensionBit(), ns3::LteRlcAmHeader::PushLengthIndicator(), ns3::LteRlcAmHeader::PushNack(), ns3::Packet::RemoveAtStart(), ns3::Packet::RemoveHeader(), ns3::Packet::RemovePacketTag(), ns3::LteMacSapProvider::TransmitPduParameters::rnti, ns3::Simulator::Schedule(), ns3::LteRlcAmHeader::SetAckSn(), ns3::LteRlcAmHeader::SetControlPdu(), ns3::LteRlcAmHeader::SetDataPdu(), ns3::LteRlcAmHeader::SetFramingInfo(), ns3::LteRlcAmHeader::SetLastSegmentFlag(), ns3::SequenceNumber10::SetModulusBase(), ns3::LteRlcAmHeader::SetPollingBit(), ns3::LteRlcAmHeader::SetResegmentationFlag(), ns3::LteRlcAmHeader::SetSegmentOffset(), ns3::RlcTag::SetSenderTimestamp(), ns3::LteRlcAmHeader::SetSequenceNumber(), ns3::LteRlcSduStatusTag::SetStatus(), ns3::LteRlcAmHeader::STATUS_PDU, ns3::LteRlcAmHeader::STATUS_REPORT_IS_REQUESTED, ns3::LteRlcAmHeader::STATUS_REPORT_NOT_REQUESTED, and ns3::LteMacSapProvider::TransmitPdu().
DoReceivePdu()
void ns3::LteRlcAm::DoReceivePdu (LteMacSapUser::ReceivePduParameters params) virtual
Receive PDU function.
Parameters
params the LteMacSapUser::ReceivePduParameters
Todo:
stop and reset the t-Reordering
Implements ns3::LteRlc.
Definition at line 755 of file lte-rlc-am.cc.
References ns3::EventId::Cancel(), DoReportBufferStatus(), ExpireReorderingTimer(), ns3::Packet::FindFirstMatchingByteTag(), ns3::LteRlcAmHeader::GetAckSn(), ns3::Time::GetNanoSeconds(), ns3::LteRlcAmHeader::GetPollingBit(), ns3::LteRlcAmHeader::GetResegmentationFlag(), ns3::RlcTag::GetSenderTimestamp(), ns3::LteRlcAmHeader::GetSequenceNumber(), ns3::Packet::GetSize(), ns3::SequenceNumber10::GetValue(), ns3::LteRlcAmHeader::IsControlPdu(), ns3::LteRlcAmHeader::IsDataPdu(), IsInsideReceivingWindow(), ns3::LteRlcAmHeader::IsNackPresent(), ns3::EventId::IsRunning(), ns3::LteRlc::m_lcid, m_pollRetransmitTimer, m_pollSn, m_reorderingTimer, m_reorderingTimerValue, m_retxBuffer, m_retxBufferSize, ns3::LteRlc::m_rnti, m_rxonBuffer, ns3::LteRlc::m_rxPdu, m_statusPduBufferSize, m_statusPduRequested, m_statusProhibitTimer, m_txedBuffer, m_txedBufferSize, m_vrH, m_vrMr, m_vrMs, m_vrR, m_vrX, m_vtA, m_vtMs, m_vtS, m_windowSize, ns3::MilliSeconds(), ns3::Simulator::Now(), NS_ASSERT, NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, NS_LOG_WARN, ns3::LteMacSapUser::ReceivePduParameters::p, ns3::LteRlcAmHeader::PDU, ns3::Packet::PeekHeader(), ReassembleAndDeliver(), ns3::Simulator::Schedule(), ns3::LteRlcAmHeader::SEGMENT, ns3::SequenceNumber10::SetModulusBase(), and ns3::LteRlcAmHeader::STATUS_REPORT_IS_REQUESTED.
DoReportBufferStatus()
void ns3::LteRlcAm::DoReportBufferStatus (void) private
Report buffer status.
Definition at line 1574 of file lte-rlc-am.cc.
References ns3::Time::GetMilliSeconds(), ns3::SequenceNumber10::GetValue(), ns3::EventId::IsRunning(), ns3::LteMacSapProvider::ReportBufferStatusParameters::lcid, ns3::LteRlc::m_lcid, ns3::LteRlc::m_macSapProvider, m_retxBuffer, m_retxBufferSize, ns3::LteRlc::m_rnti, m_statusPduBufferSize, m_statusPduRequested, m_statusProhibitTimer, m_txedBuffer, m_txedBufferSize, m_txonBuffer, m_txonBufferSize, m_vtA, m_vtS, ns3::Simulator::Now(), NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, ns3::LteMacSapProvider::ReportBufferStatus(), ns3::LteMacSapProvider::ReportBufferStatusParameters::retxQueueHolDelay, ns3::LteMacSapProvider::ReportBufferStatusParameters::retxQueueSize, ns3::LteMacSapProvider::ReportBufferStatusParameters::rnti, ns3::Seconds(), ns3::LteMacSapProvider::ReportBufferStatusParameters::statusPduSize, ns3::LteMacSapProvider::ReportBufferStatusParameters::txQueueHolDelay, and ns3::LteMacSapProvider::ReportBufferStatusParameters::txQueueSize.
Referenced by DoReceivePdu(), DoTransmitPdcpPdu(), ExpirePollRetransmitTimer(), and ExpireRbsTimer().
DoTransmitPdcpPdu()
void ns3::LteRlcAm::DoTransmitPdcpPdu (Ptr< Packet > p) virtual
RLC SAP.
Parameters
p packet
Store PDCP PDU
Report Buffer Status
Implements ns3::LteRlc.
Definition at line 156 of file lte-rlc-am.cc.
References ns3::Packet::AddPacketTag(), ns3::EventId::Cancel(), DoReportBufferStatus(), ExpireRbsTimer(), ns3::LteRlcSduStatusTag::FULL_SDU, ns3::Packet::GetSize(), ns3::LteRlc::m_lcid, m_rbsTimer, m_rbsTimerValue, ns3::LteRlc::m_rnti, m_txonBuffer, m_txonBufferSize, ns3::Simulator::Now(), NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Simulator::Schedule(), and ns3::LteRlcSduStatusTag::SetStatus().
ExpirePollRetransmitTimer()
void ns3::LteRlcAm::ExpirePollRetransmitTimer (void) private
Expire poll retransmitter.
Definition at line 1687 of file lte-rlc-am.cc.
References DoReportBufferStatus(), ns3::SequenceNumber10::GetValue(), m_pollRetransmitTimerJustExpired, m_retxBuffer, m_retxBufferSize, m_statusPduRequested, m_txedBuffer, m_txedBufferSize, m_txonBufferSize, m_vtA, m_vtMs, m_vtS, ns3::MilliSeconds(), NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_INFO, and NS_LOG_LOGIC.
Referenced by DoNotifyTxOpportunity().
ExpireRbsTimer()
void ns3::LteRlcAm::ExpireRbsTimer (void) private
Expire RBS timer.
Definition at line 1738 of file lte-rlc-am.cc.
References DoReportBufferStatus(), m_rbsTimer, m_rbsTimerValue, m_retxBufferSize, m_txedBufferSize, m_txonBufferSize, NS_LOG_LOGIC, and ns3::Simulator::Schedule().
Referenced by DoTransmitPdcpPdu().
ExpireReorderingTimer()
void ns3::LteRlcAm::ExpireReorderingTimer (void) private
This method will schedule a timeout at WaitReplyTimeout interval in the future, unless a timer is already running for the cache, in which case this method does nothing.
Definition at line 1645 of file lte-rlc-am.cc.
References ns3::SequenceNumber10::GetValue(), m_reorderingTimer, m_reorderingTimerValue, m_rxonBuffer, m_statusPduRequested, m_vrH, m_vrMs, m_vrX, NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, and ns3::Simulator::Schedule().
Referenced by DoReceivePdu().
ExpireStatusProhibitTimer()
void ns3::LteRlcAm::ExpireStatusProhibitTimer (void) private
method called when the T_status_prohibit timer expires
Definition at line 1732 of file lte-rlc-am.cc.
References NS_LOG_FUNCTION.
Referenced by DoNotifyTxOpportunity().
GetTypeId()
TypeId ns3::LteRlcAm::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 88 of file lte-rlc-am.cc.
References m_pollRetransmitTimerValue, m_rbsTimerValue, m_reorderingTimerValue, m_statusProhibitTimerValue, m_txOpportunityForRetxAlwaysBigEnough, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MilliSeconds(), and ns3::TypeId::SetParent().
Referenced by ns3::LteUeRrc::ApplyRadioResourceConfigDedicated(), ns3::LteEnbRrc::GetRlcType(), and ns3::UeManager::SetupDataRadioBearer().
IsInsideReceivingWindow()
bool ns3::LteRlcAm::IsInsideReceivingWindow (SequenceNumber10 seqNumber) private
method called when the T_status_prohibit timer expires
Parameters
seqNumber SequenceNumber10
Returns
true is inside receivign window
Definition at line 1126 of file lte-rlc-am.cc.
References m_vrMr, m_vrR, NS_LOG_FUNCTION, NS_LOG_LOGIC, and ns3::SequenceNumber10::SetModulusBase().
Referenced by DoReceivePdu().
ReassembleAndDeliver()
void ns3::LteRlcAm::ReassembleAndDeliver (Ptr< Packet > packet) private
Reassemble and deliver.
Parameters
packet the packet
Todo:
What to do in this case? Discard packet and continue? Or Assert?
Deliver one or multiple PDUs
Deliver full PDUs
Keep S0
ERROR: Transition not possible
Deliver (Kept)S0 + SN
Deliver zero, one or multiple PDUs
Keep SI
Deliver (Kept)S0 + SN
Deliver zero, one or multiple PDUs
Keep S0
ERROR: Transition not possible
Deliver one or multiple PDUs
Deliver full PDUs
Keep S0
Discard SN
Deliver zero, one or multiple PDUs
Discard SI or SN
Deliver zero, one or multiple PDUs
Keep S0
ERROR: Transition not possible
Discard S0
Deliver one or multiple PDUs
Discard S0
Deliver zero, one or multiple PDUs
Keep S0
Discard S0
Discard SI or SN
Deliver zero, one or multiple PDUs
Discard S0
Discard SI or SN
Deliver zero, one or multiple PDUs
Keep S0
ERROR: Transition not possible
Definition at line 1150 of file lte-rlc-am.cc.
References ns3::Packet::AddAtEnd(), ns3::Packet::CreateFragment(), ns3::Packet::FindFirstMatchingByteTag(), ns3::LteRlcAmHeader::FIRST_BYTE, ns3::LteRlcAmHeader::GetFramingInfo(), ns3::LteRlcAmHeader::GetSequenceNumber(), ns3::Packet::GetSize(), ns3::LteRlcAmHeader::LAST_BYTE, m_expectedSeqNumber, m_keepS0, m_reassemblingState, ns3::LteRlc::m_rlcSapUser, m_sdusBuffer, ns3::LteRlcAmHeader::NO_FIRST_BYTE, ns3::LteRlcAmHeader::NO_LAST_BYTE, NS_ASSERT, NS_LOG_LOGIC, ns3::LteRlcAmHeader::PopExtensionBit(), ns3::LteRlcAmHeader::PopLengthIndicator(), ns3::LteRlcSapUser::ReceivePdcpPdu(), ns3::Packet::RemoveAtStart(), ns3::Packet::RemoveHeader(), WAITING_S0_FULL, and WAITING_SI_SF.
Referenced by DoReceivePdu().
Member Data Documentation
m_byteWithoutPoll
uint32_t ns3::LteRlcAm::m_byteWithoutPoll private
byte without poll
Definition at line 191 of file lte-rlc-am.h.
Referenced by LteRlcAm(), and DoNotifyTxOpportunity().
m_controlPduBuffer
Ptr<Packet> ns3::LteRlcAm::m_controlPduBuffer private
Control PDU buffer (just one PDU)
Definition at line 164 of file lte-rlc-am.h.
Referenced by DoDispose().
m_expectedSeqNumber
SequenceNumber10 ns3::LteRlcAm::m_expectedSeqNumber private
Expected Sequence Number.
Definition at line 232 of file lte-rlc-am.h.
Referenced by LteRlcAm(), and ReassembleAndDeliver().
m_keepS0
Ptr<Packet> ns3::LteRlcAm::m_keepS0 private
keep S0
Definition at line 227 of file lte-rlc-am.h.
Referenced by DoDispose(), and ReassembleAndDeliver().
m_maxRetxThreshold
uint16_t ns3::LteRlcAm::m_maxRetxThreshold private
Configurable parameters.
See section 7.4 in TS 36.322
Todo:
How these parameters are configured???
Definition at line 213 of file lte-rlc-am.h.
Referenced by LteRlcAm(), and DoNotifyTxOpportunity().
m_pduWithoutPoll
uint32_t ns3::LteRlcAm::m_pduWithoutPoll private
Counters.
See section 7.1 in TS 36.322 PDU without poll
Definition at line 190 of file lte-rlc-am.h.
Referenced by LteRlcAm(), and DoNotifyTxOpportunity().
m_pollByte
uint16_t ns3::LteRlcAm::m_pollByte private
poll byte
Definition at line 215 of file lte-rlc-am.h.
Referenced by LteRlcAm(), and DoNotifyTxOpportunity().
m_pollPdu
uint16_t ns3::LteRlcAm::m_pollPdu private
poll PDU
Definition at line 214 of file lte-rlc-am.h.
Referenced by LteRlcAm(), and DoNotifyTxOpportunity().
m_pollRetransmitTimer
EventId ns3::LteRlcAm::m_pollRetransmitTimer private
Timers.
See section 7.3 in TS 36.322 poll retransmit timer
Definition at line 201 of file lte-rlc-am.h.
Referenced by DoDispose(), DoNotifyTxOpportunity(), and DoReceivePdu().
m_pollRetransmitTimerJustExpired
bool ns3::LteRlcAm::m_pollRetransmitTimerJustExpired private
poll retransmit timer just expired?
Definition at line 218 of file lte-rlc-am.h.
Referenced by LteRlcAm(), DoNotifyTxOpportunity(), and ExpirePollRetransmitTimer().
m_pollRetransmitTimerValue
Time ns3::LteRlcAm::m_pollRetransmitTimerValue private
poll retransmit time value
Definition at line 202 of file lte-rlc-am.h.
Referenced by DoNotifyTxOpportunity(), and GetTypeId().
m_pollSn
SequenceNumber10 ns3::LteRlcAm::m_pollSn private
POLL_SN.
Definition at line 178 of file lte-rlc-am.h.
Referenced by LteRlcAm(), DoNotifyTxOpportunity(), and DoReceivePdu().
m_rbsTimer
EventId ns3::LteRlcAm::m_rbsTimer private
RBS timer.
Definition at line 207 of file lte-rlc-am.h.
Referenced by DoDispose(), DoTransmitPdcpPdu(), and ExpireRbsTimer().
m_rbsTimerValue
Time ns3::LteRlcAm::m_rbsTimerValue private
RBS timer value.
Definition at line 208 of file lte-rlc-am.h.
Referenced by DoTransmitPdcpPdu(), ExpireRbsTimer(), and GetTypeId().
m_reassemblingState
ReassemblingState_t ns3::LteRlcAm::m_reassemblingState private
reassembling state
Definition at line 226 of file lte-rlc-am.h.
Referenced by LteRlcAm(), and ReassembleAndDeliver().
m_reorderingTimer
EventId ns3::LteRlcAm::m_reorderingTimer private
reordering timer
Definition at line 203 of file lte-rlc-am.h.
Referenced by DoDispose(), DoReceivePdu(), and ExpireReorderingTimer().
m_reorderingTimerValue
Time ns3::LteRlcAm::m_reorderingTimerValue private
reordering timer value
Definition at line 204 of file lte-rlc-am.h.
Referenced by DoReceivePdu(), ExpireReorderingTimer(), and GetTypeId().
m_retxBuffer
std::vector<RetxPdu> ns3::LteRlcAm::m_retxBuffer private
Buffer for PDUs considered for retransmission.
Definition at line 144 of file lte-rlc-am.h.
Referenced by LteRlcAm(), DoDispose(), DoNotifyTxOpportunity(), DoReceivePdu(), DoReportBufferStatus(), and ExpirePollRetransmitTimer().
m_retxBufferSize
uint32_t ns3::LteRlcAm::m_retxBufferSize private
retransmit buffer size
Definition at line 147 of file lte-rlc-am.h.
Referenced by LteRlcAm(), DoDispose(), DoNotifyTxOpportunity(), DoReceivePdu(), DoReportBufferStatus(), ExpirePollRetransmitTimer(), and ExpireRbsTimer().
m_rxonBuffer
std::map<uint16_t, PduBuffer > ns3::LteRlcAm::m_rxonBuffer private
Reception buffer.
Definition at line 162 of file lte-rlc-am.h.
Referenced by DoDispose(), DoNotifyTxOpportunity(), DoReceivePdu(), and ExpireReorderingTimer().
m_sdusBuffer
std::list< Ptr<Packet> > ns3::LteRlcAm::m_sdusBuffer private
List of SDUs in a packet (PDU)
Definition at line 169 of file lte-rlc-am.h.
Referenced by DoDispose(), and ReassembleAndDeliver().
m_statusPduBufferSize
uint32_t ns3::LteRlcAm::m_statusPduBufferSize private
status PDU buffer size
Definition at line 151 of file lte-rlc-am.h.
Referenced by LteRlcAm(), DoNotifyTxOpportunity(), DoReceivePdu(), and DoReportBufferStatus().
m_statusPduRequested
bool ns3::LteRlcAm::m_statusPduRequested private
status PDU requested
Definition at line 150 of file lte-rlc-am.h.
Referenced by LteRlcAm(), DoNotifyTxOpportunity(), DoReceivePdu(), DoReportBufferStatus(), ExpirePollRetransmitTimer(), and ExpireReorderingTimer().
m_statusProhibitTimer
EventId ns3::LteRlcAm::m_statusProhibitTimer private
status prohibit timer
Definition at line 205 of file lte-rlc-am.h.
Referenced by DoDispose(), DoNotifyTxOpportunity(), DoReceivePdu(), and DoReportBufferStatus().
m_statusProhibitTimerValue
Time ns3::LteRlcAm::m_statusProhibitTimerValue private
status prohibit timer value
Definition at line 206 of file lte-rlc-am.h.
Referenced by DoNotifyTxOpportunity(), and GetTypeId().
m_txedBuffer
std::vector<RetxPdu> ns3::LteRlcAm::m_txedBuffer private
Buffer for transmitted and retransmitted PDUs that have not been acked but are not considered for retransmission
Definition at line 141 of file lte-rlc-am.h.
Referenced by LteRlcAm(), DoDispose(), DoNotifyTxOpportunity(), DoReceivePdu(), DoReportBufferStatus(), and ExpirePollRetransmitTimer().
m_txedBufferSize
uint32_t ns3::LteRlcAm::m_txedBufferSize private
transmit ed buffer size
Definition at line 148 of file lte-rlc-am.h.
Referenced by LteRlcAm(), DoDispose(), DoNotifyTxOpportunity(), DoReceivePdu(), DoReportBufferStatus(), ExpirePollRetransmitTimer(), and ExpireRbsTimer().
m_txonBuffer
std::vector< TxPdu > ns3::LteRlcAm::m_txonBuffer private
Transmission buffer.
Definition at line 131 of file lte-rlc-am.h.
Referenced by DoDispose(), DoNotifyTxOpportunity(), DoReportBufferStatus(), and DoTransmitPdcpPdu().
m_txonBufferSize
uint32_t ns3::LteRlcAm::m_txonBufferSize private
transmit on buffer size
Definition at line 146 of file lte-rlc-am.h.
Referenced by LteRlcAm(), DoDispose(), DoNotifyTxOpportunity(), DoReportBufferStatus(), DoTransmitPdcpPdu(), ExpirePollRetransmitTimer(), and ExpireRbsTimer().
m_txOpportunityForRetxAlwaysBigEnough
bool ns3::LteRlcAm::m_txOpportunityForRetxAlwaysBigEnough private
transmit opportunity for retransmit?
Definition at line 217 of file lte-rlc-am.h.
Referenced by DoNotifyTxOpportunity(), and GetTypeId().
m_vrH
SequenceNumber10 ns3::LteRlcAm::m_vrH private
VR(H)
Definition at line 185 of file lte-rlc-am.h.
Referenced by LteRlcAm(), DoReceivePdu(), and ExpireReorderingTimer().
m_vrMr
SequenceNumber10 ns3::LteRlcAm::m_vrMr private
VR(MR)
Definition at line 182 of file lte-rlc-am.h.
Referenced by LteRlcAm(), DoReceivePdu(), and IsInsideReceivingWindow().
m_vrMs
SequenceNumber10 ns3::LteRlcAm::m_vrMs private
VR(MS)
Definition at line 184 of file lte-rlc-am.h.
Referenced by LteRlcAm(), DoNotifyTxOpportunity(), DoReceivePdu(), and ExpireReorderingTimer().
m_vrR
SequenceNumber10 ns3::LteRlcAm::m_vrR private
VR(R)
Definition at line 181 of file lte-rlc-am.h.
Referenced by LteRlcAm(), DoNotifyTxOpportunity(), DoReceivePdu(), and IsInsideReceivingWindow().
m_vrX
SequenceNumber10 ns3::LteRlcAm::m_vrX private
VR(X)
Definition at line 183 of file lte-rlc-am.h.
Referenced by LteRlcAm(), DoReceivePdu(), and ExpireReorderingTimer().
m_vtA
SequenceNumber10 ns3::LteRlcAm::m_vtA private
State variables.
See section 7.1 in TS 36.322 VT(A)
Definition at line 175 of file lte-rlc-am.h.
Referenced by LteRlcAm(), DoNotifyTxOpportunity(), DoReceivePdu(), DoReportBufferStatus(), and ExpirePollRetransmitTimer().
m_vtMs
SequenceNumber10 ns3::LteRlcAm::m_vtMs private
VT(MS)
Definition at line 176 of file lte-rlc-am.h.
Referenced by LteRlcAm(), DoNotifyTxOpportunity(), DoReceivePdu(), and ExpirePollRetransmitTimer().
m_vtS
SequenceNumber10 ns3::LteRlcAm::m_vtS private
VT(S)
Definition at line 177 of file lte-rlc-am.h.
Referenced by LteRlcAm(), DoNotifyTxOpportunity(), DoReceivePdu(), DoReportBufferStatus(), and ExpirePollRetransmitTimer().
m_windowSize
uint16_t ns3::LteRlcAm::m_windowSize private
Constants.
See section 7.2 in TS 36.322
Definition at line 196 of file lte-rlc-am.h.
Referenced by LteRlcAm(), and DoReceivePdu().
The documentation for this class was generated from the following files:
src/lte/model/lte-rlc-am.h
src/lte/model/lte-rlc-am.cc