ns-3: ns3::FqCoDelQueueDisc Class Reference
ns3::FqCoDelQueueDisc Class Reference
Traffic-control
A FqCoDel packet queue disc.
#include "fq-codel-queue-disc.h"
Public Member Functions
FqCoDelQueueDisc ()
FqCoDelQueueDisc constructor.
virtual ~FqCoDelQueueDisc ()
uint32_t GetQuantum (void) const
Get the quantum value.
void SetQuantum (uint32_t quantum)
Set the quantum value.
Public Member Functions inherited from ns3::QueueDisc
QueueDisc (QueueDiscSizePolicy policy, QueueSizeUnit unit)
Constructor.
QueueDisc (QueueDiscSizePolicy policy=QueueDiscSizePolicy::SINGLE_INTERNAL_QUEUE)
Constructor.
virtual ~QueueDisc ()
void AddInternalQueue (Ptr< InternalQueue > queue)
Add an internal queue to the tail of the list of queues.
void AddPacketFilter (Ptr< PacketFilter > filter)
Add a packet filter to the tail of the list of filters used to classify packets.
void AddQueueDiscClass (Ptr< QueueDiscClass > qdClass)
Add a queue disc class to the tail of the list of classes.
int32_t Classify (Ptr< QueueDiscItem > item)
Classify a packet by calling the packet filters, one at a time, until either a filter able to classify the packet is found or all the filters have been processed.
Ptr< QueueDiscItem > Dequeue (void)
Extract from the queue disc the packet that has been dequeued by calling Peek, if any, or call the private DoDequeue method (which must be implemented by derived classes) to dequeue a packet, otherwise.
bool Enqueue (Ptr< QueueDiscItem > item)
Pass a packet to store to the queue discipline.
QueueSize GetCurrentSize (void)
Get the current size of the queue disc in bytes, if operating in bytes mode, or packets, otherwise.
Ptr< InternalQueue > GetInternalQueue (std::size_t i) const
Get the i-th internal queue.
QueueSize GetMaxSize (void) const
Get the maximum size of the queue disc.
uint32_t GetNBytes (void) const
Get the amount of bytes stored by the queue disc.
Ptr< NetDeviceQueueInterface > GetNetDeviceQueueInterface (void) const
std::size_t GetNInternalQueues (void) const
Get the number of internal queues.
std::size_t GetNPacketFilters (void) const
Get the number of packet filters.
uint32_t GetNPackets (void) const
Get the number of packets stored by the queue disc.
std::size_t GetNQueueDiscClasses (void) const
Get the number of queue disc classes.
Ptr< PacketFilter > GetPacketFilter (std::size_t i) const
Get the i-th packet filter.
Ptr< QueueDiscClass > GetQueueDiscClass (std::size_t i) const
Get the i-th queue disc class.
virtual uint32_t GetQuota (void) const
Get the maximum number of dequeue operations following a packet enqueue.
SendCallback GetSendCallback (void) const
const Stats & GetStats (void)
Retrieve all the collected statistics.
virtual WakeMode GetWakeMode (void) const
When setting up the wake callbacks on the netdevice queues, it is necessary to determine which queue disc (the root queue disc or one of its children) should be activated when the netdevice wakes one of its transmission queues.
Ptr< const QueueDiscItem > Peek (void)
Get a copy of the next packet the queue discipline will extract.
void Run (void)
Modelled after the Linux function __qdisc_run (net/sched/sch_generic.c) Dequeues multiple packets, until a quota is exceeded or sending a packet to the device failed.
bool SetMaxSize (QueueSize size)
Set the maximum size of the queue disc.
void SetNetDeviceQueueInterface (Ptr< NetDeviceQueueInterface > ndqi)
virtual void SetQuota (const uint32_t quota)
Set the maximum number of dequeue operations following a packet enqueue.
void SetSendCallback (SendCallback func)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::QueueDisc
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static constexpr const char * OVERLIMIT_DROP = "Overlimit drop"
Overlimit dropped packets.
static constexpr const char * UNCLASSIFIED_DROP = "Unclassified drop"
No packet filter able to classify packet.
Static Public Attributes inherited from ns3::QueueDisc
static constexpr const char * CHILD_QUEUE_DISC_DROP = "(Dropped by child queue disc) "
Packet dropped by a child queue disc.
static constexpr const char * CHILD_QUEUE_DISC_MARK = "(Marked by child queue disc) "
Packet marked by a child queue disc.
static constexpr const char * INTERNAL_QUEUE_DROP = "Dropped by internal queue"
Packet dropped by an internal queue.
Private Member Functions
virtual bool CheckConfig (void)
Check whether the current configuration is correct.
virtual Ptr< QueueDiscItem > DoDequeue (void)
This function actually extracts a packet from the queue disc.
virtual bool DoEnqueue (Ptr< QueueDiscItem > item)
This function actually enqueues a packet into the queue disc.
uint32_t FqCoDelDrop (void)
Drop a packet from the head of the queue with the largest current byte count.
virtual void InitializeParams (void)
Initialize parameters (if any) before the first packet is enqueued.
uint32_t SetAssociativeHash (uint32_t flowHash)
Compute the index of the queue for the flow having the given flowHash, according to the set associative hash approach.
Private Attributes
Time m_ceThreshold
Threshold above which to CE mark.
uint32_t m_dropBatchSize
Max number of packets dropped from the fat flow.
bool m_enableSetAssociativeHash
whether to enable set associative hash
ObjectFactory m_flowFactory
Factory to create a new flow.
uint32_t m_flows
Number of flow queues.
std::map< uint32_t, uint32_t > m_flowsIndices
Map with the index of class for each flow.
std::string m_interval
CoDel interval attribute.
std::list< Ptr< FqCoDelFlow > > m_newFlows
The list of new flows.
std::list< Ptr< FqCoDelFlow > > m_oldFlows
The list of old flows.
uint32_t m_perturbation
hash perturbation value
uint32_t m_quantum
Deficit assigned to flows at each round.
ObjectFactory m_queueDiscFactory
Factory to create a new queue.
uint32_t m_setWays
size of a set of queues (used by set associative hash)
std::map< uint32_t, uint32_t > m_tags
Tags used by set associative hash.
std::string m_target
CoDel target attribute.
bool m_useEcn
True if ECN is used (packets are marked instead of being dropped)
bool m_useL4s
True if L4S is used (ECT1 packets are marked at CE threshold)
Additional Inherited Members
Public Types inherited from ns3::QueueDisc
typedef Queue< QueueDiscItem > InternalQueue
Internal queues store QueueDiscItem objects.
typedef std::function< void(Ptr< QueueDiscItem >)> SendCallback
Callback invoked to send a packet to the receiving object when Run is called.
enum WakeMode { WAKE_ROOT = 0x00 , WAKE_CHILD = 0x01 }
Used to determine whether the queue disc itself or its children must be activated when a netdevice wakes a transmission queue.
Protected Member Functions inherited from ns3::QueueDisc
virtual void DoDispose (void)
Dispose of the object.
void DoInitialize (void)
Check whether the configuration is correct and initialize parameters.
void DropAfterDequeue (Ptr< const QueueDiscItem > item, const char *reason)
Perform the actions required when the queue disc is notified of a packet dropped after dequeue.
void DropBeforeEnqueue (Ptr< const QueueDiscItem > item, const char *reason)
Perform the actions required when the queue disc is notified of a packet dropped before enqueue.
bool Mark (Ptr< QueueDiscItem > item, const char *reason)
Marks the given packet and, if successful, updates the counters associated with the given reason.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A FqCoDel packet queue disc.
Introspection did not find any typical Config paths.
Attributes
UseEcn: True to use ECN (packets are marked instead of being dropped)
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
Interval: The CoDel algorithm interval for each FQCoDel queue
Set with class: StringValue
Underlying type:
Initial value: 100ms
Flags: construct write read
Target: The CoDel algorithm target queue delay for each FQCoDel queue
Set with class: StringValue
Underlying type:
Initial value: 5ms
Flags: construct write read
MaxSize: The maximum number of packets accepted by this queue disc
Set with class: QueueSizeValue
Underlying type: QueueSize
Initial value: 10240p
Flags: construct write read
Flows: The number of queues into which the incoming packets are classified
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 1024
Flags: construct write read
DropBatchSize: The maximum number of packets dropped from the fat flow
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 64
Flags: construct write read
Perturbation: The salt used as an additional input to the hash function used to classify packets
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 0
Flags: construct write read
CeThreshold: The FqCoDel CE threshold for marking packets
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +9.22337e+18ns
Flags: construct write read
EnableSetAssociativeHash: Enable/Disable Set Associative Hash
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
SetWays: The size of a set of queues (used by set associative hash)
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 8
Flags: construct write read
UseL4s: True to use L4S (only ECT1 packets are marked at CE threshold)
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
Attributes defined in parent class ns3::QueueDisc
Quota: The maximum number of packets dequeued in a qdisc run
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 64
Flags: construct write read
InternalQueueList: The list of internal queues.
Set with class: ns3::ObjectPtrContainerValue
Underlying type: ns3::Ptr< ns3::Queue<QueueDiscItem>>
Flags: read
PacketFilterList: The list of packet filters.
Set with class: ns3::ObjectPtrContainerValue
Underlying type: ns3::Ptr< ns3::PacketFilter>
Flags: read
QueueDiscClassList: The list of queue disc classes.
Set with class: ns3::ObjectPtrContainerValue
Underlying type: ns3::Ptr< ns3::QueueDiscClass>
Flags: read
No TraceSources are defined for this type.
TraceSources defined in parent class ns3::QueueDisc
Enqueue: Enqueue a packet in the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
Dequeue: Dequeue a packet from the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
Requeue: Requeue a packet in the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
Drop: Drop a packet stored in the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
DropBeforeEnqueue: Drop a packet before enqueue
Callback signature: ns3::QueueDiscItem::TracedCallback
DropAfterDequeue: Drop a packet after dequeue
Callback signature: ns3::QueueDiscItem::TracedCallback
Mark: Mark a packet stored in the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
PacketsInQueue: Number of packets currently stored in the queue disc
Callback signature: ns3::TracedValueCallback::Uint32
BytesInQueue: Number of bytes currently stored in the queue disc
Callback signature: ns3::TracedValueCallback::Uint32
SojournTime: Sojourn time of the last packet dequeued from the queue disc
Callback signature: ns3::Time::TracedCallback
Size of this type is 1296 bytes (on a 64-bit architecture).
Definition at line 112 of file fq-codel-queue-disc.h.
Constructor & Destructor Documentation
FqCoDelQueueDisc()
ns3::FqCoDelQueueDisc::FqCoDelQueueDisc ()
FqCoDelQueueDisc constructor.
Definition at line 175 of file fq-codel-queue-disc.cc.
References NS_LOG_FUNCTION.
~FqCoDelQueueDisc()
ns3::FqCoDelQueueDisc::~FqCoDelQueueDisc () virtual
Definition at line 182 of file fq-codel-queue-disc.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CheckConfig()
bool ns3::FqCoDelQueueDisc::CheckConfig (void) private virtual
Check whether the current configuration is correct.
Default objects (such as internal queues) might be created by this method to ensure the configuration is correct. This method is automatically called at simulation initialization time, and it is called before the InitializeParams () method. It is appropriate to promote parameter initialization to this method if it aids in checking for correct configuration.
See also
QueueDisc::InitializeParams
Returns
true if the configuration is correct, false otherwise
Implements ns3::QueueDisc.
Definition at line 395 of file fq-codel-queue-disc.cc.
References ns3::QueueDisc::GetNetDeviceQueueInterface(), ns3::QueueDisc::GetNInternalQueues(), ns3::QueueDisc::GetNQueueDiscClasses(), m_ceThreshold, m_enableSetAssociativeHash, m_flows, m_quantum, m_setWays, m_useEcn, m_useL4s, ns3::Time::Max(), NS_ABORT_MSG_IF, NS_LOG_DEBUG, NS_LOG_ERROR, NS_LOG_FUNCTION, and NS_LOG_WARN.
DoDequeue()
Ptr< QueueDiscItem > ns3::FqCoDelQueueDisc::DoDequeue (void) private virtual
This function actually extracts a packet from the queue disc.
Returns
0 if the operation was not successful; the item otherwise.
Implements ns3::QueueDisc.
Definition at line 312 of file fq-codel-queue-disc.cc.
References ns3::FqCoDelFlow::INACTIVE, m_newFlows, m_oldFlows, m_quantum, NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::FqCoDelFlow::OLD_FLOW.
DoEnqueue()
bool ns3::FqCoDelQueueDisc::DoEnqueue (Ptr< QueueDiscItem > item) private virtual
This function actually enqueues a packet into the queue disc.
Parameters
item item to enqueue
Returns
True if the operation was successful; false otherwise
Implements ns3::QueueDisc.
Definition at line 230 of file fq-codel-queue-disc.cc.
References ns3::QueueDisc::AddQueueDiscClass(), ns3::QueueDisc::Classify(), ns3::ObjectFactory::Create(), ns3::QueueDisc::DropBeforeEnqueue(), FqCoDelDrop(), ns3::QueueDisc::GetCurrentSize(), ns3::QueueDisc::GetMaxSize(), ns3::QueueDisc::GetNPacketFilters(), ns3::QueueDisc::GetNQueueDiscClasses(), ns3::QueueDisc::GetQueueDiscClass(), ns3::FqCoDelFlow::INACTIVE, m_ceThreshold, m_enableSetAssociativeHash, m_flowFactory, m_flows, m_flowsIndices, m_newFlows, m_perturbation, m_quantum, m_queueDiscFactory, m_useEcn, m_useL4s, ns3::FqCoDelFlow::NEW_FLOW, NS_LOG_DEBUG, NS_LOG_ERROR, NS_LOG_FUNCTION, ns3::PacketFilter::PF_NO_MATCH, SetAssociativeHash(), ns3::ObjectBase::SetAttribute(), and UNCLASSIFIED_DROP.
FqCoDelDrop()
uint32_t ns3::FqCoDelQueueDisc::FqCoDelDrop (void) private
Drop a packet from the head of the queue with the largest current byte count.
Returns
the index of the queue with the largest current byte count
Definition at line 463 of file fq-codel-queue-disc.cc.
References ns3::QueueDisc::DropAfterDequeue(), ns3::QueueDisc::GetInternalQueue(), ns3::QueueDisc::GetNBytes(), ns3::QueueDisc::GetNQueueDiscClasses(), ns3::QueueDisc::GetQueueDiscClass(), m_dropBatchSize, NS_LOG_DEBUG, NS_LOG_FUNCTION, and OVERLIMIT_DROP.
Referenced by DoEnqueue().
GetQuantum()
uint32_t ns3::FqCoDelQueueDisc::GetQuantum (void) const
Get the quantum value.
Returns
The number of bytes each queue gets to dequeue on each round of the scheduling algorithm
Definition at line 195 of file fq-codel-queue-disc.cc.
References m_quantum.
GetTypeId()
TypeId ns3::FqCoDelQueueDisc::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 109 of file fq-codel-queue-disc.cc.
References ns3::QueueDisc::GetMaxSize(), m_ceThreshold, m_dropBatchSize, m_enableSetAssociativeHash, m_flows, m_interval, m_perturbation, m_setWays, m_target, m_useEcn, m_useL4s, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeQueueSizeAccessor(), ns3::MakeQueueSizeChecker(), ns3::MakeStringAccessor(), ns3::MakeStringChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeUintegerAccessor(), ns3::Time::Max(), ns3::QueueDisc::SetMaxSize(), and ns3::TypeId::SetParent().
InitializeParams()
void ns3::FqCoDelQueueDisc::InitializeParams (void) private virtual
Initialize parameters (if any) before the first packet is enqueued.
This method is automatically called at simulation initialization time, after the CheckConfig() method has been called.
See also
QueueDisc::CheckConfig
Implements ns3::QueueDisc.
Definition at line 450 of file fq-codel-queue-disc.cc.
References ns3::QueueDisc::GetMaxSize(), m_flowFactory, m_interval, m_queueDiscFactory, m_target, NS_LOG_FUNCTION, ns3::ObjectFactory::Set(), and ns3::ObjectFactory::SetTypeId().
SetAssociativeHash()
uint32_t ns3::FqCoDelQueueDisc::SetAssociativeHash (uint32_t flowHash) private
Compute the index of the queue for the flow having the given flowHash, according to the set associative hash approach.
Parameters
flowHash the hash of the flow 5-tuple
Returns
the index of the queue for the given flow
Definition at line 201 of file fq-codel-queue-disc.cc.
References ns3::QueueDisc::GetQueueDiscClass(), ns3::FqCoDelFlow::INACTIVE, m_flows, m_flowsIndices, m_setWays, m_tags, and NS_LOG_FUNCTION.
Referenced by DoEnqueue().
SetQuantum()
void ns3::FqCoDelQueueDisc::SetQuantum (uint32_t quantum)
Set the quantum value.
Parameters
quantum The number of bytes each queue gets to dequeue on each round of the scheduling algorithm
Definition at line 188 of file fq-codel-queue-disc.cc.
References m_quantum, and NS_LOG_FUNCTION.
Member Data Documentation
m_ceThreshold
Time ns3::FqCoDelQueueDisc::m_ceThreshold private
Threshold above which to CE mark.
Definition at line 173 of file fq-codel-queue-disc.h.
Referenced by CheckConfig(), DoEnqueue(), and GetTypeId().
m_dropBatchSize
uint32_t ns3::FqCoDelQueueDisc::m_dropBatchSize private
Max number of packets dropped from the fat flow.
Definition at line 171 of file fq-codel-queue-disc.h.
Referenced by FqCoDelDrop(), and GetTypeId().
m_enableSetAssociativeHash
bool ns3::FqCoDelQueueDisc::m_enableSetAssociativeHash private
whether to enable set associative hash
Definition at line 174 of file fq-codel-queue-disc.h.
Referenced by CheckConfig(), DoEnqueue(), and GetTypeId().
m_flowFactory
ObjectFactory ns3::FqCoDelQueueDisc::m_flowFactory private
Factory to create a new flow.
Definition at line 183 of file fq-codel-queue-disc.h.
Referenced by DoEnqueue(), and InitializeParams().
m_flows
uint32_t ns3::FqCoDelQueueDisc::m_flows private
Number of flow queues.
Definition at line 169 of file fq-codel-queue-disc.h.
Referenced by CheckConfig(), DoEnqueue(), GetTypeId(), and SetAssociativeHash().
m_flowsIndices
std::map<uint32_t, uint32_t> ns3::FqCoDelQueueDisc::m_flowsIndices private
Map with the index of class for each flow.
Definition at line 180 of file fq-codel-queue-disc.h.
Referenced by DoEnqueue(), and SetAssociativeHash().
m_interval
std::string ns3::FqCoDelQueueDisc::m_interval private
CoDel interval attribute.
Definition at line 166 of file fq-codel-queue-disc.h.
Referenced by GetTypeId(), and InitializeParams().
m_newFlows
std::list<Ptr<FqCoDelFlow> > ns3::FqCoDelQueueDisc::m_newFlows private
The list of new flows.
Definition at line 177 of file fq-codel-queue-disc.h.
Referenced by DoDequeue(), and DoEnqueue().
m_oldFlows
std::list<Ptr<FqCoDelFlow> > ns3::FqCoDelQueueDisc::m_oldFlows private
The list of old flows.
Definition at line 178 of file fq-codel-queue-disc.h.
Referenced by DoDequeue().
m_perturbation
uint32_t ns3::FqCoDelQueueDisc::m_perturbation private
hash perturbation value
Definition at line 172 of file fq-codel-queue-disc.h.
Referenced by DoEnqueue(), and GetTypeId().
m_quantum
uint32_t ns3::FqCoDelQueueDisc::m_quantum private
Deficit assigned to flows at each round.
Definition at line 168 of file fq-codel-queue-disc.h.
Referenced by CheckConfig(), DoDequeue(), DoEnqueue(), GetQuantum(), and SetQuantum().
m_queueDiscFactory
ObjectFactory ns3::FqCoDelQueueDisc::m_queueDiscFactory private
Factory to create a new queue.
Definition at line 184 of file fq-codel-queue-disc.h.
Referenced by DoEnqueue(), and InitializeParams().
m_setWays
uint32_t ns3::FqCoDelQueueDisc::m_setWays private
size of a set of queues (used by set associative hash)
Definition at line 170 of file fq-codel-queue-disc.h.
Referenced by CheckConfig(), GetTypeId(), and SetAssociativeHash().
m_tags
std::map<uint32_t, uint32_t> ns3::FqCoDelQueueDisc::m_tags private
Tags used by set associative hash.
Definition at line 181 of file fq-codel-queue-disc.h.
Referenced by SetAssociativeHash().
m_target
std::string ns3::FqCoDelQueueDisc::m_target private
CoDel target attribute.
Definition at line 167 of file fq-codel-queue-disc.h.
Referenced by GetTypeId(), and InitializeParams().
m_useEcn
bool ns3::FqCoDelQueueDisc::m_useEcn private
True if ECN is used (packets are marked instead of being dropped)
Definition at line 156 of file fq-codel-queue-disc.h.
Referenced by CheckConfig(), DoEnqueue(), and GetTypeId().
m_useL4s
bool ns3::FqCoDelQueueDisc::m_useL4s private
True if L4S is used (ECT1 packets are marked at CE threshold)
Definition at line 175 of file fq-codel-queue-disc.h.
Referenced by CheckConfig(), DoEnqueue(), and GetTypeId().
OVERLIMIT_DROP
constexpr const char* ns3::FqCoDelQueueDisc::OVERLIMIT_DROP = "Overlimit drop" static constexpr
Overlimit dropped packets.
Definition at line 142 of file fq-codel-queue-disc.h.
Referenced by FqCoDelDrop().
UNCLASSIFIED_DROP
constexpr const char* ns3::FqCoDelQueueDisc::UNCLASSIFIED_DROP = "Unclassified drop" static constexpr
No packet filter able to classify packet.
Definition at line 141 of file fq-codel-queue-disc.h.
Referenced by DoEnqueue().
The documentation for this class was generated from the following files:
src/traffic-control/model/fq-codel-queue-disc.h
src/traffic-control/model/fq-codel-queue-disc.cc