ns-3: ns3::Hash::Example::Collider Class Reference
ns3::Hash::Example::Collider Class Reference
Keep track of collisions.
Public Types
enum Bits { Bits32 , Bits64 }
The size of hash function being tested.
Public Member Functions
Collider (const std::string name, Hasher hash, const enum Bits bits)
Constructor.
bool Add (const std::string phrase)
Add a string to the Collider.
std::string GetName () const
void Report () const
Print the collisions found.
Public Attributes
Hasher m_hash
The hash.
std::string m_name
Name of this hash.
Private Types
typedef std::vector< std::pair< uint64_t, std::string > > collision_t
Collision map of subsequent instances.
typedef std::map< uint64_t, std::string > hashdict_t
Hashed dictionary of first instance of each hash.
Private Member Functions
uint64_t GetHash (const std::string phrase)
Get the appropriate hash value.
Private Attributes
enum Bits m_bits
Hash function.
collision_t m_coll
The list of collisions.
hashdict_t m_dict
The dictionary map, indexed by hash.
Detailed Description
Keep track of collisions.
Definition at line 120 of file hash-example.cc.
Member Typedef Documentation
collision_t
typedef std::vector< std::pair<uint64_t, std::string> > ns3::Hash::Example::Collider::collision_t private
Collision map of subsequent instances.
Definition at line 260 of file hash-example.cc.
hashdict_t
typedef std::map<uint64_t, std::string> ns3::Hash::Example::Collider::hashdict_t private
Hashed dictionary of first instance of each hash.
Definition at line 254 of file hash-example.cc.
Member Enumeration Documentation
Bits
enum ns3::Hash::Example::Collider::Bits
The size of hash function being tested.
Enumerator
Bits32
Use 32-bit hash function.
Bits64
Use 64-bit hash function.
Definition at line 128 of file hash-example.cc.
Constructor & Destructor Documentation
Collider()
ns3::Hash::Example::Collider::Collider (const std::string name, Hasher hash, const enum Bits bits) inline
Constructor.
Parameters
[in] name Hash function name.
[in] hash Hash function.
[in] bits Which hash length to use.
Definition at line 141 of file hash-example.cc.
Member Function Documentation
Add()
bool ns3::Hash::Example::Collider::Add (const std::string phrase) inline
Add a string to the Collider.
Parameters
[in] phrase The string to add.
Returns
true If this was a new string.
Definition at line 153 of file hash-example.cc.
References GetHash(), m_coll, and m_dict.
GetHash()
uint64_t ns3::Hash::Example::Collider::GetHash (const std::string phrase) inline private
Get the appropriate hash value.
Parameters
[in] phrase The string to hash.
Returns
The hash value, using the number of bits set in the constructor.
Definition at line 234 of file hash-example.cc.
References Bits32, ns3::Hasher::clear(), ns3::Hasher::GetHash32(), ns3::Hasher::GetHash64(), m_bits, and m_hash.
Referenced by Add().
GetName()
std::string ns3::Hash::Example::Collider::GetName (void) const inline
Returns
The hash name, including the length.
Definition at line 190 of file hash-example.cc.
References Bits32, Bits64, m_bits, and m_name.
Referenced by Report(), and ns3::Hash::Example::Dictionary::TimeOne().
Report()
void ns3::Hash::Example::Collider::Report () const inline
Print the collisions found.
Definition at line 206 of file hash-example.cc.
References GetName(), m_coll, and m_dict.
Member Data Documentation
m_bits
enum Bits ns3::Hash::Example::Collider::m_bits private
Hash function.
Definition at line 234 of file hash-example.cc.
Referenced by GetHash(), and GetName().
m_coll
collision_t ns3::Hash::Example::Collider::m_coll private
The list of collisions.
Definition at line 263 of file hash-example.cc.
Referenced by Add(), and Report().
m_dict
hashdict_t ns3::Hash::Example::Collider::m_dict private
The dictionary map, indexed by hash.
Definition at line 257 of file hash-example.cc.
Referenced by Add(), and Report().
m_hash
Hasher ns3::Hash::Example::Collider::m_hash
The hash.
Definition at line 125 of file hash-example.cc.
Referenced by GetHash(), and ns3::Hash::Example::Dictionary::TimeOne().
m_name
std::string ns3::Hash::Example::Collider::m_name
Name of this hash.
Definition at line 124 of file hash-example.cc.
Referenced by GetName().
The documentation for this class was generated from the following file:
src/core/examples/hash-example.cc