ns-3: LteUeMeasurementsTestCase Class Reference
LteUeMeasurementsTestCase Class Reference
LTE Models » lte module tests | Test suites
Test that UE measurements calculation works properly in a scenario with 2 eNodeBs and 2UEs.
#include "lte-test-ue-measurements.h"
Public Member Functions
LteUeMeasurementsTestCase (std::string name, double d1, double d2, double rsrpDbmUe1, double rsrpDbmUe2, double rsrqDbUe1, double rsrqDbUe2)
Constructor.
virtual ~LteUeMeasurementsTestCase ()
void RecvMeasurementReport (uint64_t imsi, uint16_t cellId, uint16_t rnti, LteRrcSap::MeasurementReport meas)
Reeive measurement report function.
void ReportUeMeasurements (uint16_t rnti, uint16_t cellId, double rsrp, double rsrq, bool servingCell)
Report UE measurements function.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
double m_d1
distance between UE and ENB node pair
double m_d2
distance between UE and other ENB node
double m_rsrpDbmUeNeighborCell
RSRP in dBm UE 2.
double m_rsrpDbmUeServingCell
RSRP in dBm UE 1.
double m_rsrqDbUeNeighborCell
RSRQ in dBm UE 2.
double m_rsrqDbUeServingCell
RSRQ in dBm UE 1.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test that UE measurements calculation works properly in a scenario with 2 eNodeBs and 2UEs.
Test that RSRP and RSRQ of the serving cell and of the neighbor cell correspond to the reference values.
Definition at line 69 of file lte-test-ue-measurements.h.
Constructor & Destructor Documentation
LteUeMeasurementsTestCase()
LteUeMeasurementsTestCase::LteUeMeasurementsTestCase (std::string name, double d1, double d2, double rsrpDbmUe1, double rsrpDbmUe2, double rsrqDbUe1, double rsrqDbUe2)
Constructor.
Parameters
name the reference name
d1 distance between UE and ENB node pair
d2 distance between UE and other ENB node
rsrpDbmUe1 RSRP in dBm UE 1
rsrpDbmUe2 RSRP in dBm UE 2
rsrqDbUe1 RSRQ in dBm UE 1
rsrqDbUe2 RSRQ in dBm UE 2
Definition at line 114 of file lte-test-ue-measurements.cc.
References NS_LOG_INFO.
~LteUeMeasurementsTestCase()
LteUeMeasurementsTestCase::~LteUeMeasurementsTestCase () virtual
Definition at line 131 of file lte-test-ue-measurements.cc.
Member Function Documentation
DoRun()
void LteUeMeasurementsTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 135 of file lte-test-ue-measurements.cc.
References ns3::LteHelper::ActivateDataRadioBearer(), ns3::LteHelper::Attach(), ns3::Config::Connect(), ns3::NodeContainer::Create(), ns3::NetDeviceContainer::Get(), ns3::TestCase::GetName(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), m_d1, m_d2, ns3::MakeBoundCallback(), third::mobility, NS_LOG_INFO, RecvMeasurementReportCallback(), ReportUeMeasurementsCallback(), ns3::Seconds(), ns3::ObjectBase::SetAttribute(), ns3::Config::SetDefault(), ns3::LteHelper::SetSchedulerAttribute(), and ns3::LteHelper::SetSchedulerType().
RecvMeasurementReport()
void LteUeMeasurementsTestCase::RecvMeasurementReport (uint64_t imsi, uint16_t cellId, uint16_t rnti, LteRrcSap::MeasurementReport meas)
Reeive measurement report function.
Parameters
imsi the IMSI
cellId the cell ID
rnti the RNTI
meas LteRrcSap::MeasurementReport
Definition at line 242 of file lte-test-ue-measurements.cc.
References m_rsrpDbmUeNeighborCell, m_rsrpDbmUeServingCell, m_rsrqDbUeNeighborCell, m_rsrqDbUeServingCell, ns3::LteRrcSap::MeasurementReport::measResults, ns3::MilliSeconds(), ns3::Now(), NS_LOG_DEBUG, NS_TEST_ASSERT_MSG_EQ, ns3::LteRrcSap::MeasResults::rsrpResult, and ns3::LteRrcSap::MeasResults::rsrqResult.
Referenced by RecvMeasurementReportCallback().
ReportUeMeasurements()
void LteUeMeasurementsTestCase::ReportUeMeasurements (uint16_t rnti, uint16_t cellId, double rsrp, double rsrq, bool servingCell)
Report UE measurements function.
Parameters
rnti the RNTI
cellId the cell ID
rsrp the RSRP
rsrq the RSRQ
servingCell the serving cell
Definition at line 219 of file lte-test-ue-measurements.cc.
References m_rsrpDbmUeNeighborCell, m_rsrpDbmUeServingCell, m_rsrqDbUeNeighborCell, m_rsrqDbUeServingCell, ns3::MilliSeconds(), ns3::Now(), NS_LOG_DEBUG, and NS_TEST_ASSERT_MSG_EQ_TOL.
Referenced by ReportUeMeasurementsCallback().
Member Data Documentation
m_d1
double LteUeMeasurementsTestCase::m_d1 private
distance between UE and ENB node pair
Definition at line 108 of file lte-test-ue-measurements.h.
Referenced by DoRun().
m_d2
double LteUeMeasurementsTestCase::m_d2 private
distance between UE and other ENB node
Definition at line 109 of file lte-test-ue-measurements.h.
Referenced by DoRun().
m_rsrpDbmUeNeighborCell
double LteUeMeasurementsTestCase::m_rsrpDbmUeNeighborCell private
RSRP in dBm UE 2.
Definition at line 111 of file lte-test-ue-measurements.h.
Referenced by RecvMeasurementReport(), and ReportUeMeasurements().
m_rsrpDbmUeServingCell
double LteUeMeasurementsTestCase::m_rsrpDbmUeServingCell private
RSRP in dBm UE 1.
Definition at line 110 of file lte-test-ue-measurements.h.
Referenced by RecvMeasurementReport(), and ReportUeMeasurements().
m_rsrqDbUeNeighborCell
double LteUeMeasurementsTestCase::m_rsrqDbUeNeighborCell private
RSRQ in dBm UE 2.
Definition at line 113 of file lte-test-ue-measurements.h.
Referenced by RecvMeasurementReport(), and ReportUeMeasurements().
m_rsrqDbUeServingCell
double LteUeMeasurementsTestCase::m_rsrqDbUeServingCell private
RSRQ in dBm UE 1.
Definition at line 112 of file lte-test-ue-measurements.h.
Referenced by RecvMeasurementReport(), and ReportUeMeasurements().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-ue-measurements.h
src/lte/test/lte-test-ue-measurements.cc