ns-3: ns3::ApWifiMac Class Reference
ns3::ApWifiMac Class Reference
Wifi Models
Wi-Fi AP state machine.
#include "ap-wifi-mac.h"
Public Member Functions
ApWifiMac ()
virtual ~ApWifiMac ()
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
void Enqueue (Ptr< Packet > packet, Mac48Address to)
void Enqueue (Ptr< Packet > packet, Mac48Address to, Mac48Address from)
Time GetBeaconInterval (void) const
Time GetCfpMaxDuration (void) const
bool GetShortPreambleEnabled (void) const
Determine whether short preamble should be enabled or not in the BSS.
bool GetShortSlotTimeEnabled (void) const
Determine whether short slot time should be enabled or not in the BSS.
uint16_t GetVhtOperationalChannelWidth (void) const
Determine the VHT operational channel width (in MHz).
bool IsNonGfHtStasPresent (void) const
Determine whether non-Greenfield HT stations are present or not.
void SetAddress (Mac48Address address)
void SetBeaconInterval (Time interval)
void SetCfpMaxDuration (Time duration)
void SetLinkUpCallback (Callback< void > linkUp)
void SetWifiRemoteStationManager (const Ptr< WifiRemoteStationManager > stationManager)
bool SupportsSendFrom (void) const
Public Member Functions inherited from ns3::InfrastructureWifiMac
InfrastructureWifiMac ()
virtual ~InfrastructureWifiMac ()
bool GetPcfSupported () const
Return whether the device supports PCF.
void SetPcfSupported (bool enable)
Enable or disable PCF support for the device.
void SetQosSupported (bool enable)
Enable or disable QoS support for the device.
Public Member Functions inherited from ns3::RegularWifiMac
RegularWifiMac ()
virtual ~RegularWifiMac ()
void ConfigureStandard (WifiStandard standard)
Mac48Address GetAddress (void) const
Mac48Address GetBssid (void) const
ExtendedCapabilities GetExtendedCapabilities (void) const
Return the extended capabilities of the device.
HeCapabilities GetHeCapabilities (void) const
Return the HE capabilities of the device.
HtCapabilities GetHtCapabilities (void) const
Return the HT capabilities of the device.
bool GetShortSlotTimeSupported (void) const
Ssid GetSsid (void) const
VhtCapabilities GetVhtCapabilities (void) const
Return the VHT capabilities of the device.
Ptr< WifiPhy > GetWifiPhy (void) const
Ptr< WifiRemoteStationManager > GetWifiRemoteStationManager (void) const
void ResetWifiPhy (void)
Remove currently attached WifiPhy device from this MAC.
void SetAddress (Mac48Address address)
void SetBssid (Mac48Address bssid)
void SetCtsToSelfSupported (bool enable)
Enable or disable CTS-to-self feature.
void SetForwardUpCallback (ForwardUpCallback upCallback)
void SetLinkDownCallback (Callback< void > linkDown)
void SetLinkUpCallback (Callback< void > linkUp)
void SetPromisc (void)
Sets the interface in promiscuous mode.
void SetShortSlotTimeSupported (bool enable)
Enable or disable short slot time feature.
void SetSsid (Ssid ssid)
virtual void SetWifiPhy (const Ptr< WifiPhy > phy)
Public Member Functions inherited from ns3::WifiMac
Ptr< NetDevice > GetDevice (void) const
Return the device this PHY is associated with.
Ptr< HeConfiguration > GetHeConfiguration (void) const
Ptr< HtConfiguration > GetHtConfiguration (void) const
Ptr< VhtConfiguration > GetVhtConfiguration (void) const
void NotifyPromiscRx (Ptr< const Packet > packet)
void NotifyRx (Ptr< const Packet > packet)
void NotifyRxDrop (Ptr< const Packet > packet)
void NotifyTx (Ptr< const Packet > packet)
void NotifyTxDrop (Ptr< const Packet > packet)
void SetDevice (const Ptr< NetDevice > device)
Sets the device this PHY is associated with.
virtual void SetForwardUpCallback (Callback< void, Ptr< const Packet >, Mac48Address, Mac48Address > upCallback)=0
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::InfrastructureWifiMac
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::RegularWifiMac
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::WifiMac
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void DeaggregateAmsduAndForward (Ptr< WifiMacQueueItem > mpdu)
This method is called to de-aggregate an A-MSDU and forward the constituent packets up the stack.
void DoDispose (void)
Destructor implementation.
void DoInitialize (void)
Initialize() implementation.
void ForwardDown (Ptr< Packet > packet, Mac48Address from, Mac48Address to)
Forward the packet down to DCF/EDCAF (enqueue the packet).
void ForwardDown (Ptr< Packet > packet, Mac48Address from, Mac48Address to, uint8_t tid)
Forward the packet down to DCF/EDCAF (enqueue the packet).
CapabilityInformation GetCapabilities (void) const
Return the Capability information of the current AP.
CfParameterSet GetCfParameterSet (void) const
Return the CF parameter set of the current AP.
DsssParameterSet GetDsssParameterSet (void) const
Return the DSSS Parameter Set that we support.
EdcaParameterSet GetEdcaParameterSet (void) const
Return the EDCA Parameter Set of the current AP.
ErpInformation GetErpInformation (void) const
Return the ERP information of the current AP.
HeOperation GetHeOperation (void) const
Return the HE operation of the current AP.
HtOperation GetHtOperation (void) const
Return the HT operation of the current AP.
uint16_t GetNextAssociationId (void)
SupportedRates GetSupportedRates (void) const
Return an instance of SupportedRates that contains all rates that we support including HT rates.
bool GetUseNonErpProtection (void) const
Return whether protection for non-ERP stations is used in the BSS.
VhtOperation GetVhtOperation (void) const
Return the VHT operation of the current AP.
void IncrementPollingListIterator (void)
Increment the PCF polling list iterator to indicate that the next polling station can be polled.
void Receive (Ptr< WifiMacQueueItem > mpdu)
This method acts as the MacRxMiddle receive callback and is invoked to notify us that a frame has been received.
void SendAssocResp (Mac48Address to, bool success, bool isReassoc)
Forward an association or a reassociation response packet to the DCF.
void SendCfEnd (void)
Send a CF-End packet.
void SendCfPoll (void)
Send a CF-Poll packet to the next polling STA.
void SendNextCfFrame (void)
Determine what is the next PCF frame and trigger its transmission.
void SendOneBeacon (void)
Forward a beacon packet to the beacon special DCF.
void SendProbeResp (Mac48Address to)
Forward a probe response packet to the DCF.
void SetBeaconGeneration (bool enable)
Enable or disable beacon generation of the AP.
void TxFailed (const WifiMacHeader &hdr)
The packet we sent was successfully received by the receiver (i.e.
void TxOk (const WifiMacHeader &hdr)
The packet we sent was successfully received by the receiver (i.e.
Private Attributes
EventId m_beaconEvent
Event to generate one beacon.
Ptr< UniformRandomVariable > m_beaconJitter
UniformRandomVariable used to randomize the time of the first beacon.
Ptr< Txop > m_beaconTxop
Dedicated Txop for beacons.
EventId m_cfpEvent
Event to generate one PCF frame.
std::list< Mac48Address > m_cfPollingList
List of all PCF stations currently associated to the AP.
bool m_enableBeaconGeneration
Flag whether beacons are being generated.
bool m_enableBeaconJitter
Flag whether the first beacon should be generated at random time.
bool m_enableNonErpProtection
Flag whether protection mechanism is used or not when non-ERP STAs are present within the BSS.
std::list< Mac48Address >::iterator m_itCfPollingList
Iterator to the list of all PCF stations currently associated to the AP.
std::list< Mac48Address > m_nonErpStations
List of all non-ERP stations currently associated to the AP.
std::list< Mac48Address > m_nonHtStations
List of all non-HT stations currently associated to the AP.
std::map< uint16_t, Mac48Address > m_staList
Map of all stations currently associated to the AP with their association ID.
Additional Inherited Members
Public Types inherited from ns3::RegularWifiMac
typedef Callback< void, Ptr< const Packet >, Mac48Address, Mac48Address > ForwardUpCallback
This type defines the callback of a higher layer that a WifiMac(-derived) object invokes to pass a packet up the stack.
Protected Types inherited from ns3::RegularWifiMac
typedef std::map< AcIndex, Ptr< QosTxop > > EdcaQueues
This type defines a mapping between an Access Category index, and a pointer to the corresponding channel access function.
Protected Member Functions inherited from ns3::RegularWifiMac
void ConfigureContentionWindow (uint32_t cwMin, uint32_t cwMax)
void ForwardUp (Ptr< const Packet > packet, Mac48Address from, Mac48Address to)
Forward the packet up to the device.
Ptr< QosTxop > GetBEQueue (void) const
Accessor for the AC_BE channel access function.
Ptr< QosTxop > GetBKQueue (void) const
Accessor for the AC_BK channel access function.
bool GetDsssSupported () const
Return whether the device supports DSSS.
bool GetErpSupported () const
Return whether the device supports ERP.
bool GetHeSupported () const
Return whether the device supports HE.
bool GetHtSupported () const
Return whether the device supports HT.
bool GetQosSupported () const
Return whether the device supports QoS.
Ptr< Txop > GetTxop (void) const
Accessor for the DCF object.
bool GetVhtSupported () const
Return whether the device supports VHT.
Ptr< QosTxop > GetVIQueue (void) const
Accessor for the AC_VI channel access function.
Ptr< QosTxop > GetVOQueue (void) const
Accessor for the AC_VO channel access function.
void SendAddBaResponse (const MgtAddBaRequestHeader *reqHdr, Mac48Address originator)
This method can be called to accept a received ADDBA Request.
void SetDsssSupported (bool enable)
Enable or disable DSSS support for the device.
void SetErpSupported (bool enable)
Enable or disable ERP support for the device.
void SetTypeOfStation (TypeOfStation type)
This method is invoked by a subclass to specify what type of station it is implementing.
Protected Member Functions inherited from ns3::WifiMac
void ConfigureDcf (Ptr< Txop > dcf, uint32_t cwmin, uint32_t cwmax, bool isDsss, AcIndex ac)
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::RegularWifiMac
Ptr< ChannelAccessManager > m_channelAccessManager
channel access manager
EdcaQueues m_edca
This is a map from Access Category index to the corresponding channel access function.
ForwardUpCallback m_forwardUp
Callback to forward packet up the stack.
Callback< void > m_linkDown
Callback when a link is down.
Callback< void > m_linkUp
Callback when a link is up.
Ptr< MacLow > m_low
MacLow (RTS, CTS, Data, Ack etc.)
Ptr< WifiPhy > m_phy
Wifi PHY.
Ptr< MacRxMiddle > m_rxMiddle
RX middle (defragmentation etc.)
Ssid m_ssid
Service Set ID (SSID)
Ptr< WifiRemoteStationManager > m_stationManager
Remote station manager (rate control, RTS/CTS/fragmentation thresholds etc.)
Ptr< MacTxMiddle > m_txMiddle
TX middle (aggregation etc.)
Ptr< Txop > m_txop
This holds a pointer to the TXOP instance for this WifiMac - used for transmission of frames to non-QoS peers.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Wi-Fi AP state machine.
Handle association, dis-association and authentication, of STAs within an infrastructure BSS.
Config Paths
ns3::ApWifiMac is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Mac/$ns3::RegularWifiMac/$ns3::InfrastructureWifiMac/$ns3::ApWifiMac"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Mac/$ns3::RegularWifiMac/$ns3::ApWifiMac"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Mac/$ns3::InfrastructureWifiMac/$ns3::ApWifiMac"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Mac/$ns3::ApWifiMac"
Attributes
BeaconInterval: Delay between two beacons
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1.024e+08ns
Flags: construct write read
CfpMaxDuration: The maximum size of the CFP (used when AP supports PCF)
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +5.12e+07ns
Flags: construct write read
BeaconJitter: A uniform random variable to cause the initial beacon starting time (after simulation time 0) to be distributed between 0 and the BeaconInterval.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::UniformRandomVariable>
Initial value: ns3::UniformRandomVariable
Flags: construct write read
EnableBeaconJitter: If beacons are enabled, whether to jitter the initial send event.
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
BeaconGeneration: Whether or not beacons are generated.
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write
EnableNonErpProtection: Whether or not protection mechanism should be used when non-ERP STAs are present within the BSS.This parameter is only used when ERP is supported by the AP.
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
Attributes defined in parent class ns3::InfrastructureWifiMac
PcfSupported: This Boolean attribute is set to enable PCF support at this STA
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
Attributes defined in parent class ns3::RegularWifiMac
QosSupported: This Boolean attribute is set to enable 802.11e/WMM-style QoS support at this STA.
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
CtsToSelfSupported: Use CTS to Self when using a rate that is not in the basic rate set.
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write
VO_MaxAmsduSize: Maximum length in bytes of an A-MSDU for AC_VO access class (capped to 7935 for HT PPDUs and 11398 for VHT/HE PPDUs). Value 0 means A-MSDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:11398
Initial value: 0
Flags: construct write read
VI_MaxAmsduSize: Maximum length in bytes of an A-MSDU for AC_VI access class (capped to 7935 for HT PPDUs and 11398 for VHT/HE PPDUs). Value 0 means A-MSDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:11398
Initial value: 0
Flags: construct write read
BE_MaxAmsduSize: Maximum length in bytes of an A-MSDU for AC_BE access class (capped to 7935 for HT PPDUs and 11398 for VHT/HE PPDUs). Value 0 means A-MSDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:11398
Initial value: 0
Flags: construct write read
BK_MaxAmsduSize: Maximum length in bytes of an A-MSDU for AC_BK access class (capped to 7935 for HT PPDUs and 11398 for VHT/HE PPDUs). Value 0 means A-MSDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:11398
Initial value: 0
Flags: construct write read
VO_MaxAmpduSize: Maximum length in bytes of an A-MPDU for AC_VO access class (capped to 65535 for HT PPDUs, 1048575 for VHT PPDUs, and 8388607 for HE PPDUs). Value 0 means A-MPDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 0
Flags: construct write read
VI_MaxAmpduSize: Maximum length in bytes of an A-MPDU for AC_VI access class (capped to 65535 for HT PPDUs, 1048575 for VHT PPDUs, and 8388607 for HE PPDUs). Value 0 means A-MPDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 65535
Flags: construct write read
BE_MaxAmpduSize: Maximum length in bytes of an A-MPDU for AC_BE access class (capped to 65535 for HT PPDUs, 1048575 for VHT PPDUs, and 8388607 for HE PPDUs). Value 0 means A-MPDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 65535
Flags: construct write read
BK_MaxAmpduSize: Maximum length in bytes of an A-MPDU for AC_BK access class (capped to 65535 for HT PPDUs, 1048575 for VHT PPDUs, and 8388607 for HE PPDUs). Value 0 means A-MPDU aggregation is disabled for that AC.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 0
Flags: construct write read
VO_BlockAckThreshold: If number of packets in VO queue reaches this value, block ack mechanism is used. If this value is 0, block ack is never used.When A-MPDU is enabled, block ack mechanism is used regardless of this value.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:64
Initial value: 0
Flags: construct write
VI_BlockAckThreshold: If number of packets in VI queue reaches this value, block ack mechanism is used. If this value is 0, block ack is never used.When A-MPDU is enabled, block ack mechanism is used regardless of this value.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:64
Initial value: 0
Flags: construct write
BE_BlockAckThreshold: If number of packets in BE queue reaches this value, block ack mechanism is used. If this value is 0, block ack is never used.When A-MPDU is enabled, block ack mechanism is used regardless of this value.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:64
Initial value: 0
Flags: construct write
BK_BlockAckThreshold: If number of packets in BK queue reaches this value, block ack mechanism is used. If this value is 0, block ack is never used.When A-MPDU is enabled, block ack mechanism is used regardless of this value.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:64
Initial value: 0
Flags: construct write
VO_BlockAckInactivityTimeout: Represents max time (blocks of 1024 microseconds) allowed for block ackinactivity for AC_VO. If this value isn't equal to 0 a timer start after that ablock ack setup is completed and will be reset every time that a block ackframe is received. If this value is 0, block ack inactivity timeout won't be used.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 0
Flags: construct write
VI_BlockAckInactivityTimeout: Represents max time (blocks of 1024 microseconds) allowed for block ackinactivity for AC_VI. If this value isn't equal to 0 a timer start after that ablock ack setup is completed and will be reset every time that a block ackframe is received. If this value is 0, block ack inactivity timeout won't be used.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 0
Flags: construct write
BE_BlockAckInactivityTimeout: Represents max time (blocks of 1024 microseconds) allowed for block ackinactivity for AC_BE. If this value isn't equal to 0 a timer start after that ablock ack setup is completed and will be reset every time that a block ackframe is received. If this value is 0, block ack inactivity timeout won't be used.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 0
Flags: construct write
BK_BlockAckInactivityTimeout: Represents max time (blocks of 1024 microseconds) allowed for block ackinactivity for AC_BK. If this value isn't equal to 0 a timer start after that ablock ack setup is completed and will be reset every time that a block ackframe is received. If this value is 0, block ack inactivity timeout won't be used.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 0
Flags: construct write
ShortSlotTimeSupported: Whether or not short slot time is supported (only used by ERP APs or STAs).
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
Txop: The Txop object.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::Txop>
Flags: read
VO_Txop: Queue that manages packets belonging to AC_VO access class.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::QosTxop>
Flags: read
VI_Txop: Queue that manages packets belonging to AC_VI access class.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::QosTxop>
Flags: read
BE_Txop: Queue that manages packets belonging to AC_BE access class.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::QosTxop>
Flags: read
BK_Txop: Queue that manages packets belonging to AC_BK access class.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::QosTxop>
Flags: read
Attributes defined in parent class ns3::WifiMac
Ssid: The ssid we want to belong to.
Set with class: SsidValue
Underlying type: Ssid
Initial value: default
Flags: construct write read
No TraceSources are defined for this type.
TraceSources defined in parent class ns3::RegularWifiMac
TxOkHeader: The header of successfully transmitted packet.
Callback signature: ns3::WifiMacHeader::TracedCallback
TxErrHeader: The header of unsuccessfully transmitted packet.
Callback signature: ns3::WifiMacHeader::TracedCallback
TraceSources defined in parent class ns3::WifiMac
MacTx: A packet has been received from higher layers and is being processed in preparation for queueing for transmission.
Callback signature: ns3::Packet::TracedCallback
MacTxDrop: A packet has been dropped in the MAC layer before transmission.
Callback signature: ns3::Packet::TracedCallback
MacPromiscRx: A packet has been received by this device, has been passed up from the physical layer and is being forwarded up the local protocol stack. This is a promiscuous trace.
Callback signature: ns3::Packet::TracedCallback
MacRx: A packet has been received by this device, has been passed up from the physical layer and is being forwarded up the local protocol stack. This is a non-promiscuous trace.
Callback signature: ns3::Packet::TracedCallback
MacRxDrop: A packet has been dropped in the MAC layer after it has been passed up from the physical layer.
Callback signature: ns3::Packet::TracedCallback
Size of this type is 592 bytes (on a 64-bit architecture).
Definition at line 47 of file ap-wifi-mac.h.
Constructor & Destructor Documentation
ApWifiMac()
ns3::ApWifiMac::ApWifiMac ()
Definition at line 90 of file ap-wifi-mac.cc.
References ns3::AP, m_beaconTxop, m_cfPollingList, ns3::RegularWifiMac::m_channelAccessManager, m_itCfPollingList, ns3::RegularWifiMac::m_low, ns3::RegularWifiMac::m_rxMiddle, ns3::RegularWifiMac::m_txMiddle, ns3::MakeCallback(), NS_LOG_FUNCTION, SendNextCfFrame(), ns3::Txop::SetAifsn(), ns3::Txop::SetChannelAccessManager(), ns3::Txop::SetMacLow(), ns3::Txop::SetMaxCw(), ns3::Txop::SetMinCw(), ns3::Txop::SetTxMiddle(), ns3::Txop::SetTxOkCallback(), ns3::RegularWifiMac::SetTypeOfStation(), and TxOk().
~ApWifiMac()
ns3::ApWifiMac::~ApWifiMac () virtual
Definition at line 110 of file ap-wifi-mac.cc.
References m_cfPollingList, m_nonErpStations, m_nonHtStations, m_staList, and NS_LOG_FUNCTION.
Member Function Documentation
AssignStreams()
int64_t ns3::ApWifiMac::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 218 of file ap-wifi-mac.cc.
References m_beaconJitter, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
DeaggregateAmsduAndForward()
void ns3::ApWifiMac::DeaggregateAmsduAndForward (Ptr< WifiMacQueueItem > mpdu) private virtual
This method is called to de-aggregate an A-MSDU and forward the constituent packets up the stack.
We override the WifiMac version here because, as an AP, we also need to think about redistributing to other associated STAs.
Parameters
mpdu the MPDU containing the A-MSDU.
Reimplemented from ns3::RegularWifiMac.
Definition at line 1540 of file ap-wifi-mac.cc.
References ForwardDown(), ns3::RegularWifiMac::ForwardUp(), ns3::RegularWifiMac::GetAddress(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::PeekPointer().
Referenced by Receive().
DoDispose()
void ns3::ApWifiMac::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::RegularWifiMac.
Definition at line 120 of file ap-wifi-mac.cc.
References ns3::EventId::Cancel(), ns3::Object::Dispose(), ns3::RegularWifiMac::DoDispose(), m_beaconEvent, m_beaconTxop, m_cfpEvent, m_enableBeaconGeneration, and NS_LOG_FUNCTION.
DoInitialize()
void ns3::ApWifiMac::DoInitialize (void) private virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::RegularWifiMac.
Definition at line 1561 of file ap-wifi-mac.cc.
References ns3::EventId::Cancel(), ns3::RegularWifiMac::DoInitialize(), ns3::RegularWifiMac::GetAddress(), GetBeaconInterval(), ns3::UniformRandomVariable::GetValue(), ns3::Object::Initialize(), m_beaconEvent, m_beaconJitter, m_beaconTxop, m_enableBeaconGeneration, m_enableBeaconJitter, ns3::MicroSeconds(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), ns3::Simulator::ScheduleNow(), and SendOneBeacon().
Enqueue() [1/2]
void ns3::ApWifiMac::Enqueue (Ptr< Packet > packet, Mac48Address to) virtual
Parameters
packet the packet to send.
to the address to which the packet should be sent.
The packet should be enqueued in a TX queue, and should be dequeued as soon as the channel access function determines that access is granted to this MAC.
Implements ns3::InfrastructureWifiMac.
Definition at line 387 of file ap-wifi-mac.cc.
References ns3::RegularWifiMac::m_low, and NS_LOG_FUNCTION.
Enqueue() [2/2]
void ns3::ApWifiMac::Enqueue (Ptr< Packet > packet, Mac48Address to, Mac48Address from) virtual
Parameters
packet the packet to send.
to the address to which the packet should be sent.
from the address from which the packet should be sent.
The packet should be enqueued in a TX queue, and should be dequeued as soon as the DCF function determines that access it granted to this MAC. The extra parameter "from" allows this device to operate in a bridged mode, forwarding received frames without altering the source address.
Reimplemented from ns3::RegularWifiMac.
Definition at line 373 of file ap-wifi-mac.cc.
References ForwardDown(), ns3::WifiRemoteStationManager::IsAssociated(), ns3::Mac48Address::IsGroup(), ns3::RegularWifiMac::m_stationManager, ns3::WifiMac::NotifyTxDrop(), and NS_LOG_FUNCTION.
ForwardDown() [1/2]
void ns3::ApWifiMac::ForwardDown (Ptr< Packet > packet, Mac48Address from, Mac48Address to) private
Forward the packet down to DCF/EDCAF (enqueue the packet).
This method is a wrapper for ForwardDown with traffic id.
Parameters
packet the packet we are forwarding to DCF/EDCAF
from the address to be used for Address 3 field in the header
to the address to be used for Address 1 field in the header
Definition at line 297 of file ap-wifi-mac.cc.
References ns3::RegularWifiMac::GetQosSupported(), NS_LOG_FUNCTION, and ns3::QosUtilsGetTidForPacket().
Referenced by DeaggregateAmsduAndForward(), Enqueue(), and Receive().
ForwardDown() [2/2]
void ns3::ApWifiMac::ForwardDown (Ptr< Packet > packet, Mac48Address from, Mac48Address to, uint8_t tid) private
Forward the packet down to DCF/EDCAF (enqueue the packet).
Parameters
packet the packet we are forwarding to DCF/EDCAF
from the address to be used for Address 3 field in the header
to the address to be used for Address 1 field in the header
tid the traffic id for the packet
Definition at line 323 of file ap-wifi-mac.cc.
References ns3::RegularWifiMac::GetAddress(), ns3::RegularWifiMac::GetQosSupported(), ns3::RegularWifiMac::m_edca, ns3::RegularWifiMac::m_txop, ns3::WifiMacHeader::NORMAL_ACK, NS_ASSERT, NS_LOG_FUNCTION, ns3::QosUtilsMapTidToAc(), ns3::Txop::Queue(), ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetAddr2(), ns3::WifiMacHeader::SetAddr3(), ns3::WifiMacHeader::SetDsFrom(), ns3::WifiMacHeader::SetDsNotTo(), ns3::WifiMacHeader::SetNoOrder(), ns3::WifiMacHeader::SetQosAckPolicy(), ns3::WifiMacHeader::SetQosNoAmsdu(), ns3::WifiMacHeader::SetQosNoEosp(), ns3::WifiMacHeader::SetQosTid(), ns3::WifiMacHeader::SetQosTxopLimit(), ns3::WifiMacHeader::SetType(), ns3::WIFI_MAC_DATA, and ns3::WIFI_MAC_QOSDATA.
GetBeaconInterval()
Time ns3::ApWifiMac::GetBeaconInterval (void) const
Returns
the interval between two beacon transmissions.
Definition at line 157 of file ap-wifi-mac.cc.
References ns3::RegularWifiMac::m_low, and NS_LOG_FUNCTION.
Referenced by DoInitialize(), GetTypeId(), SendOneBeacon(), and SendProbeResp().
GetCapabilities()
CapabilityInformation ns3::ApWifiMac::GetCapabilities (void) const private
Return the Capability information of the current AP.
Returns
the Capability information that we support
Definition at line 461 of file ap-wifi-mac.cc.
References ns3::InfrastructureWifiMac::GetPcfSupported(), GetShortPreambleEnabled(), GetShortSlotTimeEnabled(), NS_LOG_FUNCTION, ns3::CapabilityInformation::SetCfPollable(), ns3::CapabilityInformation::SetEss(), ns3::CapabilityInformation::SetShortPreamble(), and ns3::CapabilityInformation::SetShortSlotTime().
Referenced by SendAssocResp(), SendOneBeacon(), and SendProbeResp().
GetCfParameterSet()
CfParameterSet ns3::ApWifiMac::GetCfParameterSet (void) const private
Return the CF parameter set of the current AP.
Returns
the CF parameter set that we support
Definition at line 546 of file ap-wifi-mac.cc.
References GetCfpMaxDuration(), ns3::InfrastructureWifiMac::GetPcfSupported(), m_cfPollingList, ns3::CfParameterSet::SetCFPCount(), ns3::CfParameterSet::SetCFPDurRemainingUs(), ns3::CfParameterSet::SetCFPMaxDurationUs(), ns3::CfParameterSet::SetCFPPeriod(), and ns3::CfParameterSet::SetPcfSupported().
Referenced by SendOneBeacon().
GetCfpMaxDuration()
Time ns3::ApWifiMac::GetCfpMaxDuration (void) const
Returns
the maximum duration for the CF period.
Definition at line 164 of file ap-wifi-mac.cc.
References ns3::RegularWifiMac::m_low, and NS_LOG_FUNCTION.
Referenced by GetCfParameterSet(), and GetTypeId().
GetDsssParameterSet()
DsssParameterSet ns3::ApWifiMac::GetDsssParameterSet (void) const private
Return the DSSS Parameter Set that we support.
Returns
the DSSS Parameter Set that we support
Definition at line 448 of file ap-wifi-mac.cc.
References ns3::WifiPhy::GetChannelNumber(), ns3::RegularWifiMac::GetDsssSupported(), ns3::RegularWifiMac::m_phy, NS_LOG_FUNCTION, ns3::DsssParameterSet::SetCurrentChannel(), and ns3::DsssParameterSet::SetDsssSupported().
Referenced by SendOneBeacon(), and SendProbeResp().
GetEdcaParameterSet()
EdcaParameterSet ns3::ApWifiMac::GetEdcaParameterSet (void) const private
Return the EDCA Parameter Set of the current AP.
Returns
the EDCA Parameter Set that we support
Definition at line 498 of file ap-wifi-mac.cc.
References ns3::AC_BE, ns3::AC_BK, ns3::AC_VI, ns3::AC_VO, ns3::Txop::GetAifsn(), ns3::Txop::GetMaxCw(), ns3::Time::GetMicroSeconds(), ns3::Txop::GetMinCw(), ns3::RegularWifiMac::GetQosSupported(), ns3::Txop::GetTxopLimit(), ns3::RegularWifiMac::m_edca, NS_LOG_FUNCTION, ns3::EdcaParameterSet::SetBeAci(), ns3::EdcaParameterSet::SetBeAifsn(), ns3::EdcaParameterSet::SetBeCWmax(), ns3::EdcaParameterSet::SetBeCWmin(), ns3::EdcaParameterSet::SetBeTxopLimit(), ns3::EdcaParameterSet::SetBkAci(), ns3::EdcaParameterSet::SetBkAifsn(), ns3::EdcaParameterSet::SetBkCWmax(), ns3::EdcaParameterSet::SetBkCWmin(), ns3::EdcaParameterSet::SetBkTxopLimit(), ns3::EdcaParameterSet::SetQosInfo(), ns3::EdcaParameterSet::SetQosSupported(), ns3::EdcaParameterSet::SetViAci(), ns3::EdcaParameterSet::SetViAifsn(), ns3::EdcaParameterSet::SetViCWmax(), ns3::EdcaParameterSet::SetViCWmin(), ns3::EdcaParameterSet::SetViTxopLimit(), ns3::EdcaParameterSet::SetVoAci(), ns3::EdcaParameterSet::SetVoAifsn(), ns3::EdcaParameterSet::SetVoCWmax(), ns3::EdcaParameterSet::SetVoCWmin(), and ns3::EdcaParameterSet::SetVoTxopLimit().
Referenced by SendAssocResp(), SendOneBeacon(), and SendProbeResp().
GetErpInformation()
ErpInformation ns3::ApWifiMac::GetErpInformation (void) const private
Return the ERP information of the current AP.
Returns
the ERP information that we support
Definition at line 476 of file ap-wifi-mac.cc.
References ns3::RegularWifiMac::GetErpSupported(), GetShortPreambleEnabled(), GetUseNonErpProtection(), m_nonErpStations, NS_LOG_FUNCTION, ns3::ErpInformation::SetBarkerPreambleMode(), ns3::ErpInformation::SetErpSupported(), ns3::ErpInformation::SetNonErpPresent(), and ns3::ErpInformation::SetUseProtection().
Referenced by SendAssocResp(), SendOneBeacon(), and SendProbeResp().
GetHeOperation()
HeOperation ns3::ApWifiMac::GetHeOperation (void) const private
Return the HE operation of the current AP.
Returns
the HE operation that we support
Definition at line 697 of file ap-wifi-mac.cc.
References ns3::UintegerValue::Get(), ns3::WifiMac::GetHeConfiguration(), ns3::RegularWifiMac::GetHeSupported(), ns3::WifiRemoteStationManager::GetHeSupported(), ns3::WifiPhy::GetMaxSupportedRxSpatialStreams(), ns3::WifiRemoteStationManager::GetNumberOfSupportedStreams(), ns3::RegularWifiMac::m_phy, m_staList, ns3::RegularWifiMac::m_stationManager, NS_LOG_FUNCTION, ns3::HeOperation::SetBssColor(), ns3::HeOperation::SetHeSupported(), and ns3::HeOperation::SetMaxHeMcsPerNss().
Referenced by SendAssocResp(), SendOneBeacon(), and SendProbeResp().
GetHtOperation()
HtOperation ns3::ApWifiMac::GetHtOperation (void) const private
Return the HT operation of the current AP.
Returns
the HT operation that we support
Definition at line 561 of file ap-wifi-mac.cc.
References ns3::WifiPhy::GetChannelNumber(), ns3::WifiPhy::GetChannelWidth(), ns3::WifiRemoteStationManager::GetChannelWidthSupported(), ns3::WifiMode::GetDataRate(), ns3::WifiMac::GetHtConfiguration(), ns3::RegularWifiMac::GetHtSupported(), ns3::WifiRemoteStationManager::GetHtSupported(), ns3::WifiPhy::GetMaxSupportedTxSpatialStreams(), ns3::WifiPhy::GetMcs(), ns3::WifiMode::GetMcsValue(), ns3::WifiMode::GetModulationClass(), ns3::WifiPhy::GetNMcs(), ns3::WifiRemoteStationManager::GetNMcsSupported(), ns3::WifiRemoteStationManager::GetNumberOfSupportedStreams(), ns3::WifiRemoteStationManager::GetShortGuardIntervalSupported(), IsNonGfHtStasPresent(), m_nonHtStations, ns3::RegularWifiMac::m_phy, m_staList, ns3::RegularWifiMac::m_stationManager, min, ns3::MIXED_MODE_PROTECTION, ns3::NO_PROTECTION, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::HtOperation::SetDualBeacon(), ns3::HtOperation::SetDualCtsProtection(), ns3::HtOperation::SetHtProtection(), ns3::HtOperation::SetHtSupported(), ns3::HtOperation::SetLSigTxopProtectionFullSupport(), ns3::HtOperation::SetNonGfHtStasPresent(), ns3::HtOperation::SetObssNonHtStasPresent(), ns3::HtOperation::SetPcoActive(), ns3::HtOperation::SetPhase(), ns3::HtOperation::SetPrimaryChannel(), ns3::HtOperation::SetRifsMode(), ns3::HtOperation::SetRxHighestSupportedDataRate(), ns3::HtOperation::SetRxMcsBitmask(), ns3::HtOperation::SetSecondaryChannelOffset(), ns3::HtOperation::SetStaChannelWidth(), ns3::HtOperation::SetStbcBeacon(), ns3::HtOperation::SetTxMaxNSpatialStreams(), ns3::HtOperation::SetTxMcsSetDefined(), ns3::HtOperation::SetTxRxMcsSetUnequal(), ns3::HtOperation::SetTxUnequalModulation(), and ns3::WIFI_MOD_CLASS_HT.
Referenced by SendAssocResp(), SendOneBeacon(), and SendProbeResp().
GetNextAssociationId()
uint16_t ns3::ApWifiMac::GetNextAssociationId (void) private
Returns
the next Association ID to be allocated by the AP
Definition at line 1592 of file ap-wifi-mac.cc.
References m_staList, and NS_FATAL_ERROR.
Referenced by SendAssocResp().
GetShortPreambleEnabled()
bool ns3::ApWifiMac::GetShortPreambleEnabled (void) const
Determine whether short preamble should be enabled or not in the BSS.
Typically, true is returned only when the AP and all associated stations support short PHY preamble.
Returns
whether short preamble should be enabled or not in the BSS.
Definition at line 247 of file ap-wifi-mac.cc.
References ns3::RegularWifiMac::GetErpSupported(), ns3::WifiPhy::GetShortPhyPreambleSupported(), ns3::WifiRemoteStationManager::GetShortPreambleSupported(), m_nonErpStations, ns3::RegularWifiMac::m_phy, and ns3::RegularWifiMac::m_stationManager.
Referenced by GetCapabilities(), GetErpInformation(), SendOneBeacon(), and SendProbeResp().
GetShortSlotTimeEnabled()
bool ns3::ApWifiMac::GetShortSlotTimeEnabled (void) const
Determine whether short slot time should be enabled or not in the BSS.
Typically, true is returned only when there is no non-ERP stations associated to the AP, and that short slot time is supported by the AP and by all other ERP stations that are associated to the AP. Otherwise, false is returned.
Returns
whether short slot time should be enabled or not in the BSS.
Definition at line 226 of file ap-wifi-mac.cc.
References ns3::RegularWifiMac::GetErpSupported(), ns3::WifiRemoteStationManager::GetShortSlotTimeSupported(), ns3::RegularWifiMac::GetShortSlotTimeSupported(), m_nonErpStations, m_staList, and ns3::RegularWifiMac::m_stationManager.
Referenced by GetCapabilities(), SendOneBeacon(), and SendProbeResp().
GetSupportedRates()
SupportedRates ns3::ApWifiMac::GetSupportedRates (void) const private
Return an instance of SupportedRates that contains all rates that we support including HT rates.
Returns
SupportedRates all rates that we support
Definition at line 404 of file ap-wifi-mac.cc.
References ns3::WifiRemoteStationManager::AddBasicMode(), ns3::SupportedRates::AddBssMembershipSelectorRate(), ns3::SupportedRates::AddSupportedRate(), ns3::WifiRemoteStationManager::GetBasicMode(), ns3::WifiPhy::GetBssMembershipSelector(), ns3::WifiPhy::GetChannelWidth(), ns3::WifiMode::GetDataRate(), ns3::RegularWifiMac::GetHtSupported(), ns3::WifiPhy::GetMode(), ns3::WifiMode::GetModulationClass(), ns3::WifiRemoteStationManager::GetNBasicModes(), ns3::WifiPhy::GetNBssMembershipSelectors(), ns3::WifiPhy::GetNModes(), ns3::WifiMode::GetUniqueName(), ns3::WifiMode::IsMandatory(), ns3::RegularWifiMac::m_phy, ns3::RegularWifiMac::m_stationManager, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::SupportedRates::SetBasicRate(), and ns3::WIFI_MOD_CLASS_HR_DSSS.
Referenced by SendAssocResp(), SendOneBeacon(), and SendProbeResp().
GetTypeId()
TypeId ns3::ApWifiMac::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 48 of file ap-wifi-mac.cc.
References GetBeaconInterval(), GetCfpMaxDuration(), m_beaconJitter, m_enableBeaconJitter, m_enableNonErpProtection, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakePointerAccessor(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MicroSeconds(), SetBeaconGeneration(), SetBeaconInterval(), SetCfpMaxDuration(), and ns3::TypeId::SetParent().
GetUseNonErpProtection()
bool ns3::ApWifiMac::GetUseNonErpProtection (void) const private
Return whether protection for non-ERP stations is used in the BSS.
Returns
true if protection for non-ERP stations is used in the BSS, false otherwise
Definition at line 1584 of file ap-wifi-mac.cc.
References m_enableNonErpProtection, m_nonErpStations, ns3::RegularWifiMac::m_stationManager, and ns3::WifiRemoteStationManager::SetUseNonErpProtection().
Referenced by GetErpInformation().
GetVhtOperation()
VhtOperation ns3::ApWifiMac::GetVhtOperation (void) const private
Return the VHT operation of the current AP.
Returns
the VHT operation that we support
Definition at line 656 of file ap-wifi-mac.cc.
References ns3::WifiPhy::GetMaxSupportedRxSpatialStreams(), ns3::WifiRemoteStationManager::GetNumberOfSupportedStreams(), GetVhtOperationalChannelWidth(), ns3::RegularWifiMac::GetVhtSupported(), ns3::WifiRemoteStationManager::GetVhtSupported(), ns3::RegularWifiMac::m_phy, m_staList, ns3::RegularWifiMac::m_stationManager, NS_LOG_FUNCTION, ns3::VhtOperation::SetChannelWidth(), ns3::VhtOperation::SetMaxVhtMcsPerNss(), and ns3::VhtOperation::SetVhtSupported().
Referenced by SendAssocResp(), SendOneBeacon(), and SendProbeResp().
GetVhtOperationalChannelWidth()
uint16_t ns3::ApWifiMac::GetVhtOperationalChannelWidth (void) const
Determine the VHT operational channel width (in MHz).
Returns
the VHT operational channel width (in MHz).
Definition at line 280 of file ap-wifi-mac.cc.
References ns3::WifiPhy::GetChannelWidth(), ns3::WifiRemoteStationManager::GetChannelWidthSupported(), ns3::WifiRemoteStationManager::GetVhtSupported(), ns3::RegularWifiMac::m_phy, m_staList, and ns3::RegularWifiMac::m_stationManager.
Referenced by GetVhtOperation().
IncrementPollingListIterator()
void ns3::ApWifiMac::IncrementPollingListIterator (void) private
Increment the PCF polling list iterator to indicate that the next polling station can be polled.
Definition at line 1607 of file ap-wifi-mac.cc.
References m_cfPollingList, m_itCfPollingList, and NS_LOG_FUNCTION.
Referenced by Receive(), TxFailed(), and TxOk().
IsNonGfHtStasPresent()
bool ns3::ApWifiMac::IsNonGfHtStasPresent (void) const
Determine whether non-Greenfield HT stations are present or not.
Returns
whether non-Greenfield HT stations are present or not.
Definition at line 264 of file ap-wifi-mac.cc.
References ns3::WifiRemoteStationManager::GetGreenfieldSupported(), m_staList, ns3::RegularWifiMac::m_stationManager, and ns3::WifiRemoteStationManager::SetUseGreenfieldProtection().
Referenced by GetHtOperation().
Receive()
void ns3::ApWifiMac::Receive (Ptr< WifiMacQueueItem > mpdu) private virtual
This method acts as the MacRxMiddle receive callback and is invoked to notify us that a frame has been received.
The implementation is intended to capture logic that is going to be common to all (or most) derived classes. Specifically, handling of Block Ack management frames is dealt with here.
This method will need, however, to be overridden by derived classes so that they can perform their data handling before invoking the base version.
Parameters
mpdu the MPDU that has been received.
Reimplemented from ns3::RegularWifiMac.
Definition at line 1016 of file ap-wifi-mac.cc.
References ns3::WifiRemoteStationManager::AddStationHeCapabilities(), ns3::WifiRemoteStationManager::AddStationHtCapabilities(), ns3::WifiRemoteStationManager::AddStationVhtCapabilities(), ns3::WifiRemoteStationManager::AddSupportedErpSlotTime(), ns3::WifiRemoteStationManager::AddSupportedMcs(), ns3::WifiRemoteStationManager::AddSupportedMode(), ns3::WifiRemoteStationManager::AddSupportedPhyPreamble(), DeaggregateAmsduAndForward(), ForwardDown(), ns3::RegularWifiMac::ForwardUp(), ns3::WifiMacHeader::GetAddr1(), ns3::WifiMacHeader::GetAddr2(), ns3::WifiMacHeader::GetAddr3(), ns3::RegularWifiMac::GetAddress(), ns3::WifiRemoteStationManager::GetBasicMcs(), ns3::WifiRemoteStationManager::GetBasicMode(), ns3::MgtAssocRequestHeader::GetCapabilities(), ns3::MgtReassocRequestHeader::GetCapabilities(), ns3::WifiPhy::GetChannelWidth(), ns3::WifiMode::GetDataRate(), ns3::MgtAssocRequestHeader::GetExtendedCapabilities(), ns3::MgtReassocRequestHeader::GetExtendedCapabilities(), ns3::MgtAssocRequestHeader::GetHeCapabilities(), ns3::MgtReassocRequestHeader::GetHeCapabilities(), ns3::RegularWifiMac::GetHeSupported(), ns3::MgtAssocRequestHeader::GetHtCapabilities(), ns3::MgtReassocRequestHeader::GetHtCapabilities(), ns3::RegularWifiMac::GetHtSupported(), ns3::WifiPhy::GetMcs(), ns3::WifiMode::GetMcsValue(), ns3::WifiPhy::GetMode(), ns3::WifiMode::GetModulationClass(), ns3::WifiRemoteStationManager::GetNBasicMcs(), ns3::WifiRemoteStationManager::GetNBasicModes(), ns3::WifiPhy::GetNMcs(), ns3::WifiPhy::GetNModes(), ns3::InfrastructureWifiMac::GetPcfSupported(), ns3::WifiMacHeader::GetQosTid(), ns3::VhtCapabilities::GetRxHighestSupportedLgiDataRate(), ns3::MgtProbeRequestHeader::GetSsid(), ns3::RegularWifiMac::GetSsid(), ns3::HeCapabilities::GetSupportedMcsAndNss(), ns3::MgtAssocRequestHeader::GetSupportedRates(), ns3::MgtReassocRequestHeader::GetSupportedRates(), ns3::MgtAssocRequestHeader::GetVhtCapabilities(), ns3::MgtReassocRequestHeader::GetVhtCapabilities(), ns3::VhtCapabilities::GetVhtCapabilitiesInfo(), ns3::RegularWifiMac::GetVhtSupported(), ns3::WifiMacHeader::HasData(), IncrementPollingListIterator(), ns3::WifiRemoteStationManager::IsAssociated(), ns3::WifiMacHeader::IsAssocReq(), ns3::Mac48Address::IsBroadcast(), ns3::CapabilityInformation::IsCfPollable(), ns3::WifiMacHeader::IsData(), ns3::WifiMacHeader::IsDisassociation(), ns3::WifiMacHeader::IsFromDs(), ns3::Mac48Address::IsGroup(), ns3::WifiMacHeader::IsMgt(), ns3::WifiMacHeader::IsProbeReq(), ns3::WifiMacHeader::IsQosAmsdu(), ns3::WifiMacHeader::IsQosData(), ns3::WifiMacHeader::IsReassocReq(), ns3::CapabilityInformation::IsShortPreamble(), ns3::CapabilityInformation::IsShortSlotTime(), ns3::HtCapabilities::IsSupportedMcs(), ns3::SupportedRates::IsSupportedRate(), ns3::HeCapabilities::IsSupportedTxMcs(), ns3::VhtCapabilities::IsSupportedTxMcs(), ns3::WifiMacHeader::IsToDs(), m_cfPollingList, m_itCfPollingList, m_nonErpStations, m_nonHtStations, ns3::RegularWifiMac::m_phy, m_staList, ns3::RegularWifiMac::m_stationManager, ns3::WifiMac::NotifyRxDrop(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::RegularWifiMac::Receive(), ns3::WifiRemoteStationManager::RecordDisassociated(), ns3::WifiRemoteStationManager::RecordWaitAssocTxOk(), SendAssocResp(), SendProbeResp(), third::ssid, ns3::WIFI_MOD_CLASS_DSSS, ns3::WIFI_MOD_CLASS_ERP_OFDM, ns3::WIFI_MOD_CLASS_HE, ns3::WIFI_MOD_CLASS_HR_DSSS, ns3::WIFI_MOD_CLASS_OFDM, and ns3::WIFI_MOD_CLASS_VHT.
SendAssocResp()
void ns3::ApWifiMac::SendAssocResp (Mac48Address to, bool success, bool isReassoc) private
Forward an association or a reassociation response packet to the DCF.
The standard is not clear on the correct queue for management frames if QoS is supported. We always use the DCF.
Parameters
to the address of the STA we are sending an association response to
success indicates whether the association was successful or not
isReassoc indicates whether it is a reassociation response
Definition at line 783 of file ap-wifi-mac.cc.
References ns3::Packet::AddHeader(), ns3::RegularWifiMac::GetAddress(), GetCapabilities(), GetEdcaParameterSet(), GetErpInformation(), ns3::RegularWifiMac::GetErpSupported(), ns3::RegularWifiMac::GetExtendedCapabilities(), ns3::RegularWifiMac::GetHeCapabilities(), GetHeOperation(), ns3::RegularWifiMac::GetHeSupported(), ns3::RegularWifiMac::GetHtCapabilities(), GetHtOperation(), ns3::RegularWifiMac::GetHtSupported(), GetNextAssociationId(), ns3::RegularWifiMac::GetQosSupported(), GetSupportedRates(), ns3::RegularWifiMac::GetVhtCapabilities(), GetVhtOperation(), ns3::RegularWifiMac::GetVhtSupported(), m_staList, ns3::RegularWifiMac::m_txop, NS_LOG_FUNCTION, ns3::Txop::Queue(), ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetAddr2(), ns3::WifiMacHeader::SetAddr3(), ns3::MgtAssocResponseHeader::SetAssociationId(), ns3::MgtAssocResponseHeader::SetCapabilities(), ns3::WifiMacHeader::SetDsNotFrom(), ns3::WifiMacHeader::SetDsNotTo(), ns3::MgtAssocResponseHeader::SetEdcaParameterSet(), ns3::MgtAssocResponseHeader::SetErpInformation(), ns3::MgtAssocResponseHeader::SetExtendedCapabilities(), ns3::StatusCode::SetFailure(), ns3::MgtAssocResponseHeader::SetHeCapabilities(), ns3::MgtAssocResponseHeader::SetHeOperation(), ns3::MgtAssocResponseHeader::SetHtCapabilities(), ns3::MgtAssocResponseHeader::SetHtOperation(), ns3::MgtAssocResponseHeader::SetStatusCode(), ns3::StatusCode::SetSuccess(), ns3::MgtAssocResponseHeader::SetSupportedRates(), ns3::WifiMacHeader::SetType(), ns3::MgtAssocResponseHeader::SetVhtCapabilities(), ns3::MgtAssocResponseHeader::SetVhtOperation(), ns3::WIFI_MAC_MGT_ASSOCIATION_RESPONSE, and ns3::WIFI_MAC_MGT_REASSOCIATION_RESPONSE.
Referenced by Receive().
SendCfEnd()
void ns3::ApWifiMac::SendCfEnd (void) private
Send a CF-End packet.
Definition at line 961 of file ap-wifi-mac.cc.
References ns3::Mac48Address::GetBroadcast(), ns3::InfrastructureWifiMac::GetPcfSupported(), ns3::RegularWifiMac::m_txop, NS_ASSERT, NS_LOG_FUNCTION, ns3::Txop::SendCfFrame(), and ns3::WIFI_MAC_CTL_END.
Referenced by SendNextCfFrame(), and TxOk().
SendCfPoll()
void ns3::ApWifiMac::SendCfPoll (void) private
Send a CF-Poll packet to the next polling STA.
Definition at line 953 of file ap-wifi-mac.cc.
References ns3::InfrastructureWifiMac::GetPcfSupported(), m_itCfPollingList, ns3::RegularWifiMac::m_txop, NS_ASSERT, NS_LOG_FUNCTION, ns3::Txop::SendCfFrame(), and ns3::WIFI_MAC_DATA_NULL_CFPOLL.
Referenced by SendNextCfFrame(), and TxOk().
SendNextCfFrame()
void ns3::ApWifiMac::SendNextCfFrame (void) private
Determine what is the next PCF frame and trigger its transmission.
Definition at line 936 of file ap-wifi-mac.cc.
References ns3::Txop::CanStartNextPolling(), ns3::InfrastructureWifiMac::GetPcfSupported(), ns3::RegularWifiMac::m_low, ns3::RegularWifiMac::m_txop, SendCfEnd(), and SendCfPoll().
Referenced by ApWifiMac(), and TxFailed().
SendOneBeacon()
void ns3::ApWifiMac::SendOneBeacon (void) private
Forward a beacon packet to the beacon special DCF.
Definition at line 861 of file ap-wifi-mac.cc.
References ns3::Packet::AddHeader(), ns3::RegularWifiMac::GetAddress(), GetBeaconInterval(), ns3::Mac48Address::GetBroadcast(), GetCapabilities(), GetCfParameterSet(), GetDsssParameterSet(), ns3::RegularWifiMac::GetDsssSupported(), GetEdcaParameterSet(), GetErpInformation(), ns3::RegularWifiMac::GetErpSupported(), ns3::RegularWifiMac::GetExtendedCapabilities(), ns3::RegularWifiMac::GetHeCapabilities(), GetHeOperation(), ns3::RegularWifiMac::GetHeSupported(), ns3::RegularWifiMac::GetHtCapabilities(), GetHtOperation(), ns3::RegularWifiMac::GetHtSupported(), ns3::InfrastructureWifiMac::GetPcfSupported(), ns3::RegularWifiMac::GetQosSupported(), GetShortPreambleEnabled(), GetShortSlotTimeEnabled(), ns3::RegularWifiMac::GetSsid(), GetSupportedRates(), ns3::RegularWifiMac::GetVhtCapabilities(), GetVhtOperation(), ns3::RegularWifiMac::GetVhtSupported(), m_beaconEvent, m_beaconTxop, ns3::RegularWifiMac::m_phy, ns3::RegularWifiMac::m_stationManager, ns3::MicroSeconds(), NS_LOG_FUNCTION, ns3::Txop::Queue(), ns3::Simulator::Schedule(), ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetAddr2(), ns3::WifiMacHeader::SetAddr3(), ns3::MgtProbeResponseHeader::SetBeaconIntervalUs(), ns3::MgtProbeResponseHeader::SetCapabilities(), ns3::MgtProbeResponseHeader::SetCfParameterSet(), ns3::WifiMacHeader::SetDsNotFrom(), ns3::WifiMacHeader::SetDsNotTo(), ns3::MgtProbeResponseHeader::SetDsssParameterSet(), ns3::MgtProbeResponseHeader::SetEdcaParameterSet(), ns3::MgtProbeResponseHeader::SetErpInformation(), ns3::MgtProbeResponseHeader::SetExtendedCapabilities(), ns3::MgtProbeResponseHeader::SetHeCapabilities(), ns3::MgtProbeResponseHeader::SetHeOperation(), ns3::MgtProbeResponseHeader::SetHtCapabilities(), ns3::MgtProbeResponseHeader::SetHtOperation(), ns3::WifiRemoteStationManager::SetShortPreambleEnabled(), ns3::WifiRemoteStationManager::SetShortSlotTimeEnabled(), ns3::WifiPhy::SetSlot(), ns3::MgtProbeResponseHeader::SetSsid(), ns3::MgtProbeResponseHeader::SetSupportedRates(), ns3::WifiMacHeader::SetType(), ns3::MgtProbeResponseHeader::SetVhtCapabilities(), ns3::MgtProbeResponseHeader::SetVhtOperation(), and ns3::WIFI_MAC_MGT_BEACON.
Referenced by DoInitialize(), and SetBeaconGeneration().
SendProbeResp()
void ns3::ApWifiMac::SendProbeResp (Mac48Address to) private
Forward a probe response packet to the DCF.
The standard is not clear on the correct queue for management frames if QoS is supported. We always use the DCF.
Parameters
to the address of the STA we are sending a probe response to
Definition at line 727 of file ap-wifi-mac.cc.
References ns3::Packet::AddHeader(), ns3::RegularWifiMac::GetAddress(), GetBeaconInterval(), GetCapabilities(), GetDsssParameterSet(), ns3::RegularWifiMac::GetDsssSupported(), GetEdcaParameterSet(), GetErpInformation(), ns3::RegularWifiMac::GetErpSupported(), ns3::RegularWifiMac::GetExtendedCapabilities(), ns3::RegularWifiMac::GetHeCapabilities(), GetHeOperation(), ns3::RegularWifiMac::GetHeSupported(), ns3::RegularWifiMac::GetHtCapabilities(), GetHtOperation(), ns3::RegularWifiMac::GetHtSupported(), ns3::RegularWifiMac::GetQosSupported(), GetShortPreambleEnabled(), GetShortSlotTimeEnabled(), ns3::RegularWifiMac::GetSsid(), GetSupportedRates(), ns3::RegularWifiMac::GetVhtCapabilities(), GetVhtOperation(), ns3::RegularWifiMac::GetVhtSupported(), ns3::RegularWifiMac::m_stationManager, ns3::RegularWifiMac::m_txop, NS_LOG_FUNCTION, ns3::Txop::Queue(), ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetAddr2(), ns3::WifiMacHeader::SetAddr3(), ns3::MgtProbeResponseHeader::SetBeaconIntervalUs(), ns3::MgtProbeResponseHeader::SetCapabilities(), ns3::WifiMacHeader::SetDsNotFrom(), ns3::WifiMacHeader::SetDsNotTo(), ns3::MgtProbeResponseHeader::SetDsssParameterSet(), ns3::MgtProbeResponseHeader::SetEdcaParameterSet(), ns3::MgtProbeResponseHeader::SetErpInformation(), ns3::MgtProbeResponseHeader::SetExtendedCapabilities(), ns3::MgtProbeResponseHeader::SetHeCapabilities(), ns3::MgtProbeResponseHeader::SetHeOperation(), ns3::MgtProbeResponseHeader::SetHtCapabilities(), ns3::MgtProbeResponseHeader::SetHtOperation(), ns3::WifiRemoteStationManager::SetShortPreambleEnabled(), ns3::WifiRemoteStationManager::SetShortSlotTimeEnabled(), ns3::MgtProbeResponseHeader::SetSsid(), ns3::MgtProbeResponseHeader::SetSupportedRates(), ns3::WifiMacHeader::SetType(), ns3::MgtProbeResponseHeader::SetVhtCapabilities(), ns3::MgtProbeResponseHeader::SetVhtOperation(), and ns3::WIFI_MAC_MGT_PROBE_RESPONSE.
Referenced by Receive().
SetAddress()
void ns3::ApWifiMac::SetAddress (Mac48Address address) virtual
Parameters
address the current address of this MAC layer.
Implements ns3::WifiMac.
Definition at line 132 of file ap-wifi-mac.cc.
References first::address, NS_LOG_FUNCTION, ns3::RegularWifiMac::SetAddress(), and ns3::RegularWifiMac::SetBssid().
SetBeaconGeneration()
void ns3::ApWifiMac::SetBeaconGeneration (bool enable) private
Enable or disable beacon generation of the AP.
Parameters
enable enable or disable beacon generation
Definition at line 142 of file ap-wifi-mac.cc.
References ns3::EventId::Cancel(), m_beaconEvent, m_enableBeaconGeneration, NS_LOG_FUNCTION, ns3::Simulator::ScheduleNow(), and SendOneBeacon().
Referenced by GetTypeId().
SetBeaconInterval()
void ns3::ApWifiMac::SetBeaconInterval (Time interval)
Parameters
interval the interval between two beacon transmissions.
Definition at line 192 of file ap-wifi-mac.cc.
References ns3::Time::GetMicroSeconds(), ns3::RegularWifiMac::m_low, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetCfpMaxDuration()
void ns3::ApWifiMac::SetCfpMaxDuration (Time duration)
Parameters
duration the maximum duration for the CF period.
Definition at line 207 of file ap-wifi-mac.cc.
References ns3::Time::GetMicroSeconds(), ns3::RegularWifiMac::m_low, NS_LOG_FUNCTION, and NS_LOG_WARN.
Referenced by GetTypeId().
SetLinkUpCallback()
void ns3::ApWifiMac::SetLinkUpCallback (Callback< void > linkUp) virtual
Parameters
linkUp the callback to invoke when the link becomes up.
Implements ns3::WifiMac.
Definition at line 180 of file ap-wifi-mac.cc.
References NS_LOG_FUNCTION, and ns3::RegularWifiMac::SetLinkUpCallback().
SetWifiRemoteStationManager()
void ns3::ApWifiMac::SetWifiRemoteStationManager (const Ptr< WifiRemoteStationManager > stationManager) virtual
Parameters
stationManager the station manager attached to this MAC.
Reimplemented from ns3::RegularWifiMac.
Definition at line 171 of file ap-wifi-mac.cc.
References ns3::InfrastructureWifiMac::GetPcfSupported(), m_beaconTxop, ns3::RegularWifiMac::m_stationManager, NS_LOG_FUNCTION, ns3::WifiRemoteStationManager::SetPcfSupported(), ns3::Txop::SetWifiRemoteStationManager(), and ns3::RegularWifiMac::SetWifiRemoteStationManager().
SupportsSendFrom()
bool ns3::ApWifiMac::SupportsSendFrom (void) const virtual
Returns
if this MAC supports sending from arbitrary address.
The interface may or may not support sending from arbitrary address. This function returns true if sending from arbitrary address is supported, false otherwise.
Reimplemented from ns3::RegularWifiMac.
Definition at line 397 of file ap-wifi-mac.cc.
References NS_LOG_FUNCTION.
TxFailed()
void ns3::ApWifiMac::TxFailed (const WifiMacHeader & hdr) private virtual
The packet we sent was successfully received by the receiver (i.e.
we did not receive an Ack from the receiver). If the packet was an association response to the receiver, we record that the receiver is not associated with us yet.
Parameters
hdr the header of the packet that we failed to sent
Reimplemented from ns3::RegularWifiMac.
Definition at line 997 of file ap-wifi-mac.cc.
References ns3::WifiMacHeader::GetAddr1(), IncrementPollingListIterator(), ns3::WifiMacHeader::IsAssocResp(), ns3::WifiMacHeader::IsCfPoll(), ns3::WifiMacHeader::IsReassocResp(), ns3::WifiRemoteStationManager::IsWaitAssocTxOk(), ns3::RegularWifiMac::m_stationManager, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::WifiRemoteStationManager::RecordGotAssocTxFailed(), SendNextCfFrame(), and ns3::RegularWifiMac::TxFailed().
TxOk()
void ns3::ApWifiMac::TxOk (const WifiMacHeader & hdr) private virtual
The packet we sent was successfully received by the receiver (i.e.
we received an Ack from the receiver). If the packet was an association response to the receiver, we record that the receiver is now associated with us.
Parameters
hdr the header of the packet that we successfully sent
Reimplemented from ns3::RegularWifiMac.
Definition at line 969 of file ap-wifi-mac.cc.
References ns3::WifiMacHeader::GetAddr1(), ns3::InfrastructureWifiMac::GetPcfSupported(), IncrementPollingListIterator(), ns3::WifiMacHeader::IsAssocResp(), ns3::WifiMacHeader::IsBeacon(), ns3::WifiMacHeader::IsCfPoll(), ns3::WifiMacHeader::IsReassocResp(), ns3::WifiRemoteStationManager::IsWaitAssocTxOk(), m_cfPollingList, ns3::RegularWifiMac::m_stationManager, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::WifiRemoteStationManager::RecordGotAssocTxOk(), SendCfEnd(), SendCfPoll(), and ns3::RegularWifiMac::TxOk().
Referenced by ApWifiMac().
Member Data Documentation
m_beaconEvent
EventId ns3::ApWifiMac::m_beaconEvent private
Event to generate one beacon.
Definition at line 291 of file ap-wifi-mac.h.
Referenced by DoDispose(), DoInitialize(), SendOneBeacon(), and SetBeaconGeneration().
m_beaconJitter
Ptr<UniformRandomVariable> ns3::ApWifiMac::m_beaconJitter private
UniformRandomVariable used to randomize the time of the first beacon.
Definition at line 293 of file ap-wifi-mac.h.
Referenced by AssignStreams(), DoInitialize(), and GetTypeId().
m_beaconTxop
Ptr<Txop> ns3::ApWifiMac::m_beaconTxop private
Dedicated Txop for beacons.
Definition at line 289 of file ap-wifi-mac.h.
Referenced by ApWifiMac(), DoDispose(), DoInitialize(), SendOneBeacon(), and SetWifiRemoteStationManager().
m_cfpEvent
EventId ns3::ApWifiMac::m_cfpEvent private
Event to generate one PCF frame.
Definition at line 292 of file ap-wifi-mac.h.
Referenced by DoDispose().
m_cfPollingList
std::list<Mac48Address> ns3::ApWifiMac::m_cfPollingList private
List of all PCF stations currently associated to the AP.
Definition at line 298 of file ap-wifi-mac.h.
Referenced by ApWifiMac(), ~ApWifiMac(), GetCfParameterSet(), IncrementPollingListIterator(), Receive(), and TxOk().
m_enableBeaconGeneration
bool ns3::ApWifiMac::m_enableBeaconGeneration private
Flag whether beacons are being generated.
Definition at line 290 of file ap-wifi-mac.h.
Referenced by DoDispose(), DoInitialize(), and SetBeaconGeneration().
m_enableBeaconJitter
bool ns3::ApWifiMac::m_enableBeaconJitter private
Flag whether the first beacon should be generated at random time.
Definition at line 294 of file ap-wifi-mac.h.
Referenced by DoInitialize(), and GetTypeId().
m_enableNonErpProtection
bool ns3::ApWifiMac::m_enableNonErpProtection private
Flag whether protection mechanism is used or not when non-ERP STAs are present within the BSS.
Definition at line 300 of file ap-wifi-mac.h.
Referenced by GetTypeId(), and GetUseNonErpProtection().
m_itCfPollingList
std::list<Mac48Address>::iterator ns3::ApWifiMac::m_itCfPollingList private
Iterator to the list of all PCF stations currently associated to the AP.
Definition at line 299 of file ap-wifi-mac.h.
Referenced by ApWifiMac(), IncrementPollingListIterator(), Receive(), and SendCfPoll().
m_nonErpStations
std::list<Mac48Address> ns3::ApWifiMac::m_nonErpStations private
List of all non-ERP stations currently associated to the AP.
Definition at line 296 of file ap-wifi-mac.h.
Referenced by ~ApWifiMac(), GetErpInformation(), GetShortPreambleEnabled(), GetShortSlotTimeEnabled(), GetUseNonErpProtection(), and Receive().
m_nonHtStations
std::list<Mac48Address> ns3::ApWifiMac::m_nonHtStations private
List of all non-HT stations currently associated to the AP.
Definition at line 297 of file ap-wifi-mac.h.
Referenced by ~ApWifiMac(), GetHtOperation(), and Receive().
m_staList
std::map<uint16_t, Mac48Address> ns3::ApWifiMac::m_staList private
Map of all stations currently associated to the AP with their association ID.
Definition at line 295 of file ap-wifi-mac.h.
Referenced by ~ApWifiMac(), GetHeOperation(), GetHtOperation(), GetNextAssociationId(), GetShortSlotTimeEnabled(), GetVhtOperation(), GetVhtOperationalChannelWidth(), IsNonGfHtStasPresent(), Receive(), and SendAssocResp().
The documentation for this class was generated from the following files:
src/wifi/model/ap-wifi-mac.h
src/wifi/model/ap-wifi-mac.cc