ns-3: ns3::FfMacSchedSapUser Class Reference
ns3::FfMacSchedSapUser Class Reference abstract
FfMacSchedSapUser class.
#include "ff-mac-sched-sap.h"
Classes
struct SchedDlConfigIndParameters
Parameters of the API primitives.
struct SchedUlConfigIndParameters
Parameters of the SCHED_UL_CONFIG_IND primitive.
Public Member Functions
virtual ~FfMacSchedSapUser ()
virtual void SchedDlConfigInd (const struct SchedDlConfigIndParameters &params)=0
SCHED_DL_CONFIG_IND.
virtual void SchedUlConfigInd (const struct SchedUlConfigIndParameters &params)=0
SCHED_UL_CONFIG_IND.
Detailed Description
FfMacSchedSapUser class.
Definition at line 280 of file ff-mac-sched-sap.h.
Constructor & Destructor Documentation
~FfMacSchedSapUser()
ns3::FfMacSchedSapUser::~FfMacSchedSapUser () virtual
Definition at line 30 of file ff-mac-sched-sap.cc.
Member Function Documentation
SchedDlConfigInd()
virtual void ns3::FfMacSchedSapUser::SchedDlConfigInd (const struct SchedDlConfigIndParameters & params) pure virtual
SCHED_DL_CONFIG_IND.
Parameters
params SchedDlConfigIndParameters
Implemented in ns3::EnbMacMemberFfMacSchedSapUser.
Referenced by ns3::CqaFfMacScheduler::DoSchedDlTriggerReq(), ns3::FdBetFfMacScheduler::DoSchedDlTriggerReq(), ns3::FdMtFfMacScheduler::DoSchedDlTriggerReq(), ns3::FdTbfqFfMacScheduler::DoSchedDlTriggerReq(), ns3::PfFfMacScheduler::DoSchedDlTriggerReq(), ns3::PssFfMacScheduler::DoSchedDlTriggerReq(), ns3::RrFfMacScheduler::DoSchedDlTriggerReq(), ns3::TdBetFfMacScheduler::DoSchedDlTriggerReq(), ns3::TdMtFfMacScheduler::DoSchedDlTriggerReq(), ns3::TdTbfqFfMacScheduler::DoSchedDlTriggerReq(), and ns3::TtaFfMacScheduler::DoSchedDlTriggerReq().
SchedUlConfigInd()
virtual void ns3::FfMacSchedSapUser::SchedUlConfigInd (const struct SchedUlConfigIndParameters & params) pure virtual
SCHED_UL_CONFIG_IND.
Parameters
params SchedUlConfigIndParameters
Implemented in ns3::EnbMacMemberFfMacSchedSapUser.
Referenced by ns3::CqaFfMacScheduler::DoSchedUlTriggerReq(), ns3::FdBetFfMacScheduler::DoSchedUlTriggerReq(), ns3::FdMtFfMacScheduler::DoSchedUlTriggerReq(), ns3::FdTbfqFfMacScheduler::DoSchedUlTriggerReq(), ns3::PfFfMacScheduler::DoSchedUlTriggerReq(), ns3::PssFfMacScheduler::DoSchedUlTriggerReq(), ns3::RrFfMacScheduler::DoSchedUlTriggerReq(), ns3::TdBetFfMacScheduler::DoSchedUlTriggerReq(), ns3::TdMtFfMacScheduler::DoSchedUlTriggerReq(), ns3::TdTbfqFfMacScheduler::DoSchedUlTriggerReq(), and ns3::TtaFfMacScheduler::DoSchedUlTriggerReq().
The documentation for this class was generated from the following files:
src/lte/model/ff-mac-sched-sap.h
src/lte/model/ff-mac-sched-sap.cc