ns-3: EpsBearerTagUdpClient Class Reference
EpsBearerTagUdpClient Class Reference
LTE Models » lte module tests | Test suites
A Udp client.
Public Member Functions
EpsBearerTagUdpClient ()
EpsBearerTagUdpClient (uint16_t rnti, uint8_t bid)
Constructor.
virtual ~EpsBearerTagUdpClient ()
void SetRemote (Ipv4Address ip, uint16_t port)
set the remote address and port
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Application
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void ScheduleTransmit (Time dt)
Schedule transmit function.
void Send (void)
Send function.
virtual void StartApplication (void)
Application specific startup code.
virtual void StopApplication (void)
Application specific shutdown code.
Private Attributes
uint8_t m_bid
the bearer identificator
uint32_t m_count
maximum number of packets to send
Time m_interval
the time between packets
Ipv4Address m_peerAddress
the peer address of the outbound packets
uint16_t m_peerPort
the destination port of the outbound packets
uint16_t m_rnti
the RNTI
EventId m_sendEvent
the send event
uint32_t m_sent
number of packets sent
uint32_t m_size
the size of packets generated
Ptr< Socket > m_socket
the socket
Additional Inherited Members
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A Udp client.
Sends UDP packet carrying sequence number and time stamp but also including the EpsBearerTag. This tag is normally generated by the LteEnbNetDevice when forwarding packet in the uplink. But in this test we don't have the LteEnbNetDevice, because we test the S1-U interface with simpler devices to make sure it just works.
Definition at line 67 of file epc-test-s1u-uplink.cc.
Constructor & Destructor Documentation
EpsBearerTagUdpClient() [1/2]
EpsBearerTagUdpClient::EpsBearerTagUdpClient ()
Definition at line 160 of file epc-test-s1u-uplink.cc.
References m_sendEvent, m_sent, m_socket, and NS_LOG_FUNCTION_NOARGS.
EpsBearerTagUdpClient() [2/2]
EpsBearerTagUdpClient::EpsBearerTagUdpClient (uint16_t rnti, uint8_t bid)
Constructor.
Parameters
rnti the RNTI
bid the BID
Definition at line 170 of file epc-test-s1u-uplink.cc.
References m_sendEvent, m_sent, m_socket, and NS_LOG_FUNCTION_NOARGS.
~EpsBearerTagUdpClient()
EpsBearerTagUdpClient::~EpsBearerTagUdpClient () virtual
Definition at line 180 of file epc-test-s1u-uplink.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
DoDispose()
void EpsBearerTagUdpClient::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Application.
Definition at line 193 of file epc-test-s1u-uplink.cc.
References NS_LOG_FUNCTION_NOARGS.
GetTypeId()
TypeId EpsBearerTagUdpClient::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 128 of file epc-test-s1u-uplink.cc.
References m_count, m_interval, m_peerAddress, m_peerPort, m_size, ns3::MakeIpv4AddressAccessor(), ns3::MakeIpv4AddressChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeUintegerAccessor(), ns3::Seconds(), and ns3::TypeId::SetParent().
ScheduleTransmit()
void EpsBearerTagUdpClient::ScheduleTransmit (Time dt) private
Schedule transmit function.
Parameters
dt the delta time
Send()
void EpsBearerTagUdpClient::Send (void) private
Send function.
Definition at line 224 of file epc-test-s1u-uplink.cc.
References ns3::Packet::AddHeader(), ns3::Packet::AddPacketTag(), ns3::Packet::GetUid(), ns3::EventId::IsExpired(), m_bid, m_count, m_interval, m_peerAddress, m_rnti, m_sendEvent, m_sent, m_size, m_socket, ns3::Now(), NS_ASSERT, NS_LOG_FUNCTION_NOARGS, NS_LOG_INFO, ns3::Socket::Send(), and ns3::SeqTsHeader::SetSeq().
Referenced by StartApplication().
SetRemote()
void EpsBearerTagUdpClient::SetRemote (Ipv4Address ip, uint16_t port)
set the remote address and port
Parameters
ip remote IP address
port remote port
Definition at line 186 of file epc-test-s1u-uplink.cc.
References m_peerAddress, m_peerPort, and port.
StartApplication()
void EpsBearerTagUdpClient::StartApplication (void) private virtual
Application specific startup code.
The StartApplication method is called at the start time specified by Start This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 200 of file epc-test-s1u-uplink.cc.
References ns3::Socket::Bind(), ns3::Socket::Connect(), ns3::Application::GetNode(), m_peerAddress, m_peerPort, m_sendEvent, m_socket, ns3::MakeNullCallback(), NS_LOG_FUNCTION_NOARGS, ns3::Seconds(), Send(), and ns3::Socket::SetRecvCallback().
StopApplication()
void EpsBearerTagUdpClient::StopApplication (void) private virtual
Application specific shutdown code.
The StopApplication method is called at the stop time specified by Stop This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 217 of file epc-test-s1u-uplink.cc.
References m_sendEvent, and NS_LOG_FUNCTION_NOARGS.
Member Data Documentation
m_bid
uint8_t EpsBearerTagUdpClient::m_bid private
the bearer identificator
Definition at line 121 of file epc-test-s1u-uplink.cc.
Referenced by Send().
m_count
uint32_t EpsBearerTagUdpClient::m_count private
maximum number of packets to send
Definition at line 110 of file epc-test-s1u-uplink.cc.
Referenced by GetTypeId(), and Send().
m_interval
Time EpsBearerTagUdpClient::m_interval private
the time between packets
Definition at line 111 of file epc-test-s1u-uplink.cc.
Referenced by GetTypeId(), and Send().
m_peerAddress
Ipv4Address EpsBearerTagUdpClient::m_peerAddress private
the peer address of the outbound packets
Definition at line 116 of file epc-test-s1u-uplink.cc.
Referenced by GetTypeId(), Send(), SetRemote(), and StartApplication().
m_peerPort
uint16_t EpsBearerTagUdpClient::m_peerPort private
the destination port of the outbound packets
Definition at line 117 of file epc-test-s1u-uplink.cc.
Referenced by GetTypeId(), SetRemote(), and StartApplication().
m_rnti
uint16_t EpsBearerTagUdpClient::m_rnti private
the RNTI
Definition at line 120 of file epc-test-s1u-uplink.cc.
Referenced by Send().
m_sendEvent
EventId EpsBearerTagUdpClient::m_sendEvent private
the send event
Definition at line 118 of file epc-test-s1u-uplink.cc.
Referenced by EpsBearerTagUdpClient(), Send(), StartApplication(), and StopApplication().
m_sent
uint32_t EpsBearerTagUdpClient::m_sent private
number of packets sent
Definition at line 114 of file epc-test-s1u-uplink.cc.
Referenced by EpsBearerTagUdpClient(), and Send().
m_size
uint32_t EpsBearerTagUdpClient::m_size private
the size of packets generated
Definition at line 112 of file epc-test-s1u-uplink.cc.
Referenced by GetTypeId(), and Send().
m_socket
Ptr<Socket> EpsBearerTagUdpClient::m_socket private
the socket
Definition at line 115 of file epc-test-s1u-uplink.cc.
Referenced by EpsBearerTagUdpClient(), Send(), and StartApplication().
The documentation for this class was generated from the following file:
src/lte/test/epc-test-s1u-uplink.cc