ns-3: ns3::ArpL3Protocol Class Reference
ns3::ArpL3Protocol Class Reference
Internet » IPv4 classes and sub-modules » ARP protocol.
An implementation of the ARP protocol.
#include "arp-l3-protocol.h"
Public Member Functions
ArpL3Protocol ()
virtual ~ArpL3Protocol ()
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Ptr< ArpCache > CreateCache (Ptr< NetDevice > device, Ptr< Ipv4Interface > interface)
Create an ARP cache for the device/interface.
bool Lookup (Ptr< Packet > p, const Ipv4Header &ipHeader, Ipv4Address destination, Ptr< NetDevice > device, Ptr< ArpCache > cache, Address *hardwareDestination)
Perform an ARP lookup.
void Receive (Ptr< NetDevice > device, Ptr< const Packet > p, uint16_t protocol, const Address &from, const Address &to, NetDevice::PacketType packetType)
Receive a packet.
void SetNode (Ptr< Node > node)
Set the node the ARP L3 protocol is associated with.
void SetTrafficControl (Ptr< TrafficControlLayer > tc)
Set the TrafficControlLayer.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static const uint16_t PROT_NUMBER = 0x0806
ARP protocol number (0x0806)
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
virtual void NotifyNewAggregate ()
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
typedef std::list< Ptr< ArpCache > > CacheList
container of the ARP caches
Private Member Functions
ArpL3Protocol (const ArpL3Protocol &o)
Copy constructor.
Ptr< ArpCache > FindCache (Ptr< NetDevice > device)
Finds the cache associated with a NetDevice.
ArpL3Protocol & operator= (const ArpL3Protocol &o)
Copy constructor.
void SendArpReply (Ptr< const ArpCache > cache, Ipv4Address myIp, Ipv4Address toIp, Address toMac)
Send an ARP reply to an host.
void SendArpRequest (Ptr< const ArpCache >cache, Ipv4Address to)
Send an ARP request to an host.
Private Attributes
CacheList m_cacheList
ARP cache container.
TracedCallback< Ptr< const Packet > > m_dropTrace
trace for packets dropped by ARP
Ptr< Node > m_node
node the ARP L3 protocol is associated with
Ptr< RandomVariableStream > m_requestJitter
jitter to de-sync ARP requests
Ptr< TrafficControlLayer > m_tc
The associated TrafficControlLayer.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
An implementation of the ARP protocol.
Config Paths
ns3::ArpL3Protocol is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::ArpL3Protocol"
Attributes
CacheList: The list of ARP caches
Set with class: ns3::ObjectPtrContainerValue
Underlying type: ns3::Ptr< ns3::ArpCache>
Flags: read
RequestJitter: The jitter in ms a node is allowed to wait before sending an ARP request. Some jitter aims to prevent collisions. By default, the model will wait for a duration in ms defined by a uniform random-variable between 0 and RequestJitter
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::RandomVariableStream>
Initial value: ns3::UniformRandomVariable[Min=0.0|Max=10.0]
Flags: construct write read
TraceSources
Drop: Packet dropped because not enough room in pending queue for a specific cache entry.
Callback signature: ns3::Packet::TracedCallback
Size of this type is 104 bytes (on a 64-bit architecture).
Definition at line 53 of file arp-l3-protocol.h.
Member Typedef Documentation
CacheList
typedef std::list<Ptr<ArpCache> > ns3::ArpL3Protocol::CacheList private
container of the ARP caches
Definition at line 130 of file arp-l3-protocol.h.
Constructor & Destructor Documentation
ArpL3Protocol() [1/2]
ns3::ArpL3Protocol::ArpL3Protocol ()
Definition at line 75 of file arp-l3-protocol.cc.
References NS_LOG_FUNCTION.
~ArpL3Protocol()
ns3::ArpL3Protocol::~ArpL3Protocol () virtual
Definition at line 81 of file arp-l3-protocol.cc.
References NS_LOG_FUNCTION.
ArpL3Protocol() [2/2]
ns3::ArpL3Protocol::ArpL3Protocol (const ArpL3Protocol & o) private
Copy constructor.
Defined and unimplemented to avoid misuse
Parameters
o
Member Function Documentation
AssignStreams()
int64_t ns3::ArpL3Protocol::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 87 of file arp-l3-protocol.cc.
References m_requestJitter, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
CreateCache()
Ptr< ArpCache > ns3::ArpL3Protocol::CreateCache (Ptr< NetDevice > device, Ptr< Ipv4Interface > interface)
Create an ARP cache for the device/interface.
Parameters
device the NetDevice
interface the Ipv4Interface
Returns
a smart pointer to the ARP cache
Definition at line 145 of file arp-l3-protocol.cc.
References ns3::ArpCache::Flush(), ns3::Object::GetObject(), m_cacheList, m_node, ns3::MakeCallback(), NS_ASSERT, NS_LOG_FUNCTION, and SendArpRequest().
DoDispose()
void ns3::ArpL3Protocol::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 130 of file arp-l3-protocol.cc.
References ns3::Object::Dispose(), ns3::Object::DoDispose(), m_cacheList, m_node, m_tc, and NS_LOG_FUNCTION.
FindCache()
Ptr< ArpCache > ns3::ArpL3Protocol::FindCache (Ptr< NetDevice > device) private
Finds the cache associated with a NetDevice.
Parameters
device the NetDevice
Returns
the ARP cache, or null if no cache is found
Definition at line 159 of file arp-l3-protocol.cc.
References m_cacheList, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by Receive().
GetTypeId()
TypeId ns3::ArpL3Protocol::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 46 of file arp-l3-protocol.cc.
References m_cacheList, m_dropTrace, m_requestJitter, ns3::MakeObjectVectorAccessor(), ns3::MakePointerAccessor(), ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
Lookup()
bool ns3::ArpL3Protocol::Lookup (Ptr< Packet > p, const Ipv4Header & ipHeader, Ipv4Address destination, Ptr< NetDevice > device, Ptr< ArpCache > cache, Address * hardwareDestination)
Perform an ARP lookup.
Parameters
p the packet
ipHeader the IPv4 header
destination destination IP address
device outgoing device
cache ARP cache
hardwareDestination filled with the destination MAC address (if the entry exists)
Returns
true if there is a matching ARP Entry
Definition at line 281 of file arp-l3-protocol.cc.
References ns3::ArpCache::Add(), ns3::Packet::AddHeader(), ns3::Node::GetId(), ns3::ArpCache::Entry::GetMacAddress(), ns3::RandomVariableStream::GetValue(), ns3::ArpCache::Entry::IsAlive(), ns3::ArpCache::Entry::IsDead(), ns3::ArpCache::Entry::IsExpired(), ns3::ArpCache::Entry::IsWaitReply(), ns3::ArpCache::Lookup(), m_dropTrace, m_node, m_requestJitter, ns3::ArpCache::Entry::MarkWaitReply(), ns3::MilliSeconds(), NS_FATAL_ERROR, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Simulator::Schedule(), SendArpRequest(), and ns3::ArpCache::Entry::UpdateWaitReply().
NotifyNewAggregate()
void ns3::ArpL3Protocol::NotifyNewAggregate (void) protected virtual
Notify all Objects aggregated to this one of a new Object being aggregated.
This function must be implemented in the stack that needs to notify other stacks connected to the node of their presence in the node.
This method is invoked whenever two sets of Objects are aggregated together. It is invoked exactly once for each Object in both sets. This method can be overridden by subclasses who wish to be notified of aggregation events. These subclasses must chain up to their base class NotifyNewAggregate() method.
It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 113 of file arp-l3-protocol.cc.
References m_node, ns3::Object::NotifyNewAggregate(), NS_LOG_FUNCTION, and SetNode().
operator=()
ArpL3Protocol& ns3::ArpL3Protocol::operator= (const ArpL3Protocol & o) private
Copy constructor.
Defined and unimplemented to avoid misuse
Parameters
o
Returns
Receive()
void ns3::ArpL3Protocol::Receive (Ptr< NetDevice > device, Ptr< const Packet > p, uint16_t protocol, const Address & from, const Address & to, NetDevice::PacketType packetType)
Receive a packet.
Parameters
device the source NetDevice
p the packet
protocol the protocol
from the source address
to the destination address
packetType type of packet (i.e., unicast, multicast, etc.)
Internal:
Note: we do not update the ARP cache when we receive an ARP request from an unknown node. See Bug 107
Definition at line 175 of file arp-l3-protocol.cc.
References ns3::ArpCache::Entry::DequeuePending(), FindCache(), ns3::Ipv4Interface::GetAddress(), ns3::ArpHeader::GetDestinationHardwareAddress(), ns3::ArpHeader::GetDestinationIpv4Address(), ns3::Node::GetId(), ns3::ArpCache::GetInterface(), ns3::Ipv4InterfaceAddress::GetLocal(), ns3::Packet::GetSize(), ns3::ArpHeader::GetSourceHardwareAddress(), ns3::ArpHeader::GetSourceIpv4Address(), ns3::ArpHeader::IsReply(), ns3::ArpHeader::IsRequest(), ns3::ArpCache::Entry::IsWaitReply(), ns3::ArpCache::Lookup(), m_dropTrace, m_node, ns3::ArpCache::Entry::MarkAlive(), NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Packet::RemoveHeader(), ns3::Ipv4Interface::Send(), and SendArpReply().
Referenced by ns3::Ipv4L3Protocol::AddInterface().
SendArpReply()
void ns3::ArpL3Protocol::SendArpReply (Ptr< const ArpCache > cache, Ipv4Address myIp, Ipv4Address toIp, Address toMac) private
Send an ARP reply to an host.
Parameters
cache the ARP cache to use
myIp the source IP address
toIp the destination IP
toMac the destination MAC address
Definition at line 384 of file arp-l3-protocol.cc.
References ns3::Node::GetId(), m_node, m_tc, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, PROT_NUMBER, and ns3::ArpHeader::SetReply().
Referenced by Receive().
SendArpRequest()
void ns3::ArpL3Protocol::SendArpRequest (Ptr< const ArpCache > cache, Ipv4Address to) private
Send an ARP request to an host.
Parameters
cache the ARP cache to use
to the destination IP
Definition at line 365 of file arp-l3-protocol.cc.
References ns3::Ipv4Address::GetBroadcast(), ns3::Node::GetId(), ns3::Object::GetObject(), ns3::Ipv4InterfaceAddress::GLOBAL, m_node, m_tc, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, PROT_NUMBER, and ns3::ArpHeader::SetRequest().
Referenced by CreateCache(), and Lookup().
SetNode()
void ns3::ArpL3Protocol::SetNode (Ptr< Node > node)
Set the node the ARP L3 protocol is associated with.
Parameters
node the node
Definition at line 95 of file arp-l3-protocol.cc.
References m_node, and NS_LOG_FUNCTION.
Referenced by NotifyNewAggregate().
SetTrafficControl()
void ns3::ArpL3Protocol::SetTrafficControl (Ptr< TrafficControlLayer > tc)
Set the TrafficControlLayer.
Parameters
tc TrafficControlLayer object
Definition at line 102 of file arp-l3-protocol.cc.
References m_tc, and NS_LOG_FUNCTION.
Member Data Documentation
m_cacheList
CacheList ns3::ArpL3Protocol::m_cacheList private
ARP cache container.
Definition at line 169 of file arp-l3-protocol.h.
Referenced by CreateCache(), DoDispose(), FindCache(), and GetTypeId().
m_dropTrace
TracedCallback<Ptr<const Packet> > ns3::ArpL3Protocol::m_dropTrace private
trace for packets dropped by ARP
Definition at line 171 of file arp-l3-protocol.h.
Referenced by GetTypeId(), Lookup(), and Receive().
m_node
Ptr<Node> ns3::ArpL3Protocol::m_node private
node the ARP L3 protocol is associated with
Definition at line 170 of file arp-l3-protocol.h.
Referenced by CreateCache(), DoDispose(), Lookup(), NotifyNewAggregate(), Receive(), SendArpReply(), SendArpRequest(), and SetNode().
m_requestJitter
Ptr<RandomVariableStream> ns3::ArpL3Protocol::m_requestJitter private
jitter to de-sync ARP requests
Definition at line 172 of file arp-l3-protocol.h.
Referenced by AssignStreams(), GetTypeId(), and Lookup().
m_tc
Ptr<TrafficControlLayer> ns3::ArpL3Protocol::m_tc private
The associated TrafficControlLayer.
Definition at line 173 of file arp-l3-protocol.h.
Referenced by DoDispose(), SendArpReply(), SendArpRequest(), and SetTrafficControl().
PROT_NUMBER
const uint16_t ns3::ArpL3Protocol::PROT_NUMBER = 0x0806 static
ARP protocol number (0x0806)
Definition at line 61 of file arp-l3-protocol.h.
Referenced by ns3::Ipv4L3Protocol::AddInterface(), SendArpReply(), and SendArpRequest().
The documentation for this class was generated from the following files:
src/internet/model/arp-l3-protocol.h
src/internet/model/arp-l3-protocol.cc