ns-3: ns3::DataCollector Class Reference
ns3::DataCollector Class Reference
Statistics » Data Output
Collects data.
#include "data-collector.h"
Public Member Functions
DataCollector ()
virtual ~DataCollector ()
void AddDataCalculator (Ptr< DataCalculator > datac)
Add a DataCalculator object to the DataCollector.
void AddMetadata (std::string key, double value)
Add the key and the value as a pair of strings to the metadata list.
void AddMetadata (std::string key, std::string value)
Add the key and the value as a pair of strings to the metadata list.
void AddMetadata (std::string key, uint32_t value)
Add the key and the value as a pair of strings to the metadata list.
DataCalculatorList::iterator DataCalculatorBegin ()
Returns an iterator to the beginning of the DataCalculator list.
DataCalculatorList::iterator DataCalculatorEnd ()
Returns an iterator to the past-the-end of the DataCalculator list.
void DescribeRun (std::string experiment, std::string strategy, std::string input, std::string runID, std::string description="")
Provide specific parameters to the DataCollector.
std::string GetDescription () const
Return the description label.
std::string GetExperimentLabel () const
Return the experiment label.
std::string GetInputLabel () const
Return the input label.
std::string GetRunLabel () const
Return the runID label.
std::string GetStrategyLabel () const
Return the strategy label.
MetadataList::iterator MetadataBegin ()
Returns an iterator to the beginning of the metadata list.
MetadataList::iterator MetadataEnd ()
Returns an iterator to the past-the-end of the metadata list.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose ()
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Attributes
DataCalculatorList m_calcList
List of data calculators.
std::string m_description
Description label.
std::string m_experimentLabel
Experiment label.
std::string m_inputLabel
Input label.
MetadataList m_metadata
List of experiment metadata.
std::string m_runLabel
Run label.
std::string m_strategyLabel
Strategy label.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Collects data.
Definition at line 49 of file data-collector.h.
Constructor & Destructor Documentation
DataCollector()
DataCollector::DataCollector ()
Definition at line 33 of file data-collector.cc.
References NS_LOG_FUNCTION.
~DataCollector()
DataCollector::~DataCollector () virtual
Definition at line 38 of file data-collector.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddDataCalculator()
void DataCollector::AddDataCalculator (Ptr< DataCalculator > datac)
Add a DataCalculator object to the DataCollector.
Parameters
datac DataCalculator object to be added
Definition at line 84 of file data-collector.cc.
References m_calcList, and NS_LOG_FUNCTION.
AddMetadata() [1/3]
void DataCollector::AddMetadata (std::string key, double value)
Add the key and the value as a pair of strings to the metadata list.
Parameters
key Key value to include
value Value to include of type double
Definition at line 128 of file data-collector.cc.
References m_metadata, and NS_LOG_FUNCTION.
AddMetadata() [2/3]
void DataCollector::AddMetadata (std::string key, std::string value)
Add the key and the value as a pair of strings to the metadata list.
Parameters
key Key value to include
value Value to include of type string
Definition at line 107 of file data-collector.cc.
References m_metadata, and NS_LOG_FUNCTION.
AddMetadata() [3/3]
void DataCollector::AddMetadata (std::string key, uint32_t value)
Add the key and the value as a pair of strings to the metadata list.
Parameters
key Key value to include
value Value to include of type uint32_t
Definition at line 116 of file data-collector.cc.
References m_metadata, and NS_LOG_FUNCTION.
DataCalculatorBegin()
DataCalculatorList::iterator DataCollector::DataCalculatorBegin ()
Returns an iterator to the beginning of the DataCalculator list.
Returns
Iterator pointing to the first value of the DataCalculator list
Definition at line 94 of file data-collector.cc.
References m_calcList.
Referenced by ns3::OmnetDataOutput::Output(), and ns3::SqliteDataOutput::Output().
DataCalculatorEnd()
DataCalculatorList::iterator DataCollector::DataCalculatorEnd ()
Returns an iterator to the past-the-end of the DataCalculator list.
Returns
Iterator pointing to the past-the-end element of the DataCalculator list
Definition at line 100 of file data-collector.cc.
References m_calcList.
Referenced by ns3::OmnetDataOutput::Output(), and ns3::SqliteDataOutput::Output().
DescribeRun()
void DataCollector::DescribeRun (std::string experiment, std::string strategy, std::string input, std::string runID, std::string description = "")
Provide specific parameters to the DataCollector.
Parameters
experiment Label for the experiment
strategy Label for the strategy
input Label for the input
runID Label for the runID
description Description
Definition at line 66 of file data-collector.cc.
References experiment(), m_description, m_experimentLabel, m_inputLabel, m_runLabel, m_strategyLabel, and NS_LOG_FUNCTION.
DoDispose()
void DataCollector::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 55 of file data-collector.cc.
References ns3::Object::DoDispose(), m_calcList, m_metadata, and NS_LOG_FUNCTION.
GetDescription()
std::string ns3::DataCollector::GetDescription () const inline
Return the description label.
Returns
Description label
Definition at line 98 of file data-collector.h.
References m_description.
Referenced by ns3::OmnetDataOutput::Output(), and ns3::SqliteDataOutput::Output().
GetExperimentLabel()
std::string ns3::DataCollector::GetExperimentLabel () const inline
Return the experiment label.
Returns
Experiment label
Definition at line 78 of file data-collector.h.
References m_experimentLabel.
Referenced by ns3::OmnetDataOutput::Output(), and ns3::SqliteDataOutput::Output().
GetInputLabel()
std::string ns3::DataCollector::GetInputLabel () const inline
Return the input label.
Returns
Input label
Definition at line 88 of file data-collector.h.
References m_inputLabel.
Referenced by ns3::OmnetDataOutput::Output(), and ns3::SqliteDataOutput::Output().
GetRunLabel()
std::string ns3::DataCollector::GetRunLabel () const inline
Return the runID label.
Returns
Run label
Definition at line 93 of file data-collector.h.
References m_runLabel.
Referenced by ns3::OmnetDataOutput::Output(), and ns3::SqliteDataOutput::Output().
GetStrategyLabel()
std::string ns3::DataCollector::GetStrategyLabel () const inline
Return the strategy label.
Returns
Strategy label
Definition at line 83 of file data-collector.h.
References m_strategyLabel.
Referenced by ns3::OmnetDataOutput::Output(), and ns3::SqliteDataOutput::Output().
GetTypeId()
TypeId DataCollector::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 45 of file data-collector.cc.
References ns3::TypeId::SetParent().
MetadataBegin()
MetadataList::iterator DataCollector::MetadataBegin ()
Returns an iterator to the beginning of the metadata list.
Returns
Iterator pointing to the first value of the metadata list
Definition at line 141 of file data-collector.cc.
References m_metadata.
Referenced by ns3::OmnetDataOutput::Output(), and ns3::SqliteDataOutput::Output().
MetadataEnd()
MetadataList::iterator DataCollector::MetadataEnd ()
Returns an iterator to the past-the-end of the metadata list.
Returns
Iterator pointing to the past-the-end element of the metadata list
Definition at line 147 of file data-collector.cc.
References m_metadata.
Referenced by ns3::OmnetDataOutput::Output(), and ns3::SqliteDataOutput::Output().
Member Data Documentation
m_calcList
DataCalculatorList ns3::DataCollector::m_calcList private
List of data calculators.
Definition at line 156 of file data-collector.h.
Referenced by AddDataCalculator(), DataCalculatorBegin(), DataCalculatorEnd(), and DoDispose().
m_description
std::string ns3::DataCollector::m_description private
Description label.
Definition at line 153 of file data-collector.h.
Referenced by DescribeRun(), and GetDescription().
m_experimentLabel
std::string ns3::DataCollector::m_experimentLabel private
Experiment label.
Definition at line 149 of file data-collector.h.
Referenced by DescribeRun(), and GetExperimentLabel().
m_inputLabel
std::string ns3::DataCollector::m_inputLabel private
Input label.
Definition at line 151 of file data-collector.h.
Referenced by DescribeRun(), and GetInputLabel().
m_metadata
MetadataList ns3::DataCollector::m_metadata private
List of experiment metadata.
Definition at line 155 of file data-collector.h.
Referenced by AddMetadata(), DoDispose(), MetadataBegin(), and MetadataEnd().
m_runLabel
std::string ns3::DataCollector::m_runLabel private
Run label.
Definition at line 152 of file data-collector.h.
Referenced by DescribeRun(), and GetRunLabel().
m_strategyLabel
std::string ns3::DataCollector::m_strategyLabel private
Strategy label.
Definition at line 150 of file data-collector.h.
Referenced by DescribeRun(), and GetStrategyLabel().
The documentation for this class was generated from the following files:
src/stats/model/data-collector.h
src/stats/model/data-collector.cc