ns-3: TcpPacingTest Class Reference
TcpPacingTest Class Reference
Internet » internet module tests | Test suites
Test the behavior of TCP pacing.
Public Member Functions
TcpPacingTest (uint32_t segmentSize, uint32_t packetSize, uint32_t packets, uint16_t pacingSsRatio, uint16_t pacingCaRatio, uint32_t ssThresh, bool paceInitialWindow, uint32_t delAckMaxCount, const TypeId &congControl, const std::string &desc)
Constructor.
Public Member Functions inherited from ns3::TcpGeneralTest
TcpGeneralTest (const std::string &desc)
TcpGeneralTest constructor.
~TcpGeneralTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Member Functions
virtual void BytesInFlightTrace (uint32_t oldValue, uint32_t newValue)
Bytes in flight changes.
virtual void ConfigureEnvironment ()
Change the configuration of the environment.
virtual void ConfigureProperties ()
Change the configuration of the socket properties.
virtual void CWndTrace (uint32_t oldValue, uint32_t newValue)
Tracks the congestion window changes.
virtual void NormalClose (SocketWho who)
Socket closed normally.
virtual void PhyDrop (SocketWho who)
Link drop.
virtual void QueueDrop (SocketWho who)
Drop on the queue.
virtual void RttTrace (Time oldTime, Time newTime)
Rtt changes.
virtual void Rx (const Ptr< const Packet > p, const TcpHeader &h, SocketWho who)
Packet received from IP layer.
virtual void Tx (const Ptr< const Packet > p, const TcpHeader &h, SocketWho who)
Packet transmitted down to IP layer.
virtual void UpdateExpectedInterval (void)
Update the expected interval at which next packet will be sent.
Protected Member Functions inherited from ns3::TcpGeneralTest
virtual void AfterRTOExpired (const Ptr< const TcpSocketState > tcb, SocketWho who)
Rto has expired.
virtual void BeforeRTOExpired (const Ptr< const TcpSocketState > tcb, SocketWho who)
Rto has expired.
virtual void CongStateTrace (const TcpSocketState::TcpCongState_t oldValue, const TcpSocketState::TcpCongState_t newValue)
State on Ack state machine changes.
virtual Ptr< SimpleChannel > CreateChannel ()
Create and return the channel installed between the two socket.
virtual Ptr< ErrorModel > CreateReceiverErrorModel ()
Create and return the error model to install in the receiver node.
virtual Ptr< TcpSocketMsgBase > CreateReceiverSocket (Ptr< Node > node)
Create and install the socket to install on the receiver.
virtual Ptr< ErrorModel > CreateSenderErrorModel ()
Create and return the error model to install in the sender node.
virtual Ptr< TcpSocketMsgBase > CreateSenderSocket (Ptr< Node > node)
Create and install the socket to install on the sender.
virtual Ptr< TcpSocketMsgBase > CreateSocket (Ptr< Node > node, TypeId socketType, TypeId congControl)
Create a socket.
virtual Ptr< TcpSocketMsgBase > CreateSocket (Ptr< Node > node, TypeId socketType, TypeId congControl, TypeId recoveryAlgorithm)
Create a socket.
virtual void CWndInflTrace (uint32_t oldValue, uint32_t newValue)
Tracks the inflated congestion window changes.
virtual void DataSent (uint32_t size, SocketWho who)
Notifying application for sent data.
void DoConnect ()
Scheduled at 0.0, SENDER starts the connection to RECEIVER.
virtual void DoRun (void)
Execute the tcp test.
virtual void DoTeardown (void)
Teardown the TCP test.
virtual void ErrorClose (SocketWho who)
Socket closed with an error.
virtual void FinalChecks ()
Performs the (eventual) final checks through test asserts.
Time GetClockGranularity (SocketWho who)
Get the clock granularity attribute.
Time GetConnTimeout (SocketWho who)
Get the retransmission time for the SYN segments.
uint32_t GetDelAckCount (SocketWho who)
Get the number of delayed ack (if present)
Time GetDelAckTimeout (SocketWho who)
Get the timeout of delayed ack (if present)
uint32_t GetDupAckCount (SocketWho who)
Get the number of dupack received.
SequenceNumber32 GetHighestTxMark (SocketWho who)
Get the highest tx mark of the node specified.
uint32_t GetInitialCwnd (SocketWho who)
Get the initial congestion window.
uint32_t GetInitialSsThresh (SocketWho who)
Get the initial slow start threshold.
Time GetMinRto (SocketWho who)
Get the minimum RTO attribute.
uint32_t GetMtu () const
Get the MTU of the environment.
EventId GetPersistentEvent (SocketWho who)
Get the persistent event of the selected socket.
Time GetPersistentTimeout (SocketWho who)
Get the persistent timeout of the selected socket.
uint32_t GetPktCount () const
Get the number of application packets.
Time GetPktInterval () const
Get the interval to wait for each packet sent down from application to TCP.
uint32_t GetPktSize () const
Get the application packet size.
Time GetPropagationDelay () const
Get the channel Propagation Delay.
Ptr< TcpSocketMsgBase > GetReceiverSocket ()
Get the pointer to a previously created receiver socket.
uint32_t GetReTxThreshold (SocketWho who)
Get the retransmission threshold.
Time GetRto (SocketWho who)
Get the retransmission time.
Ptr< RttEstimator > GetRttEstimator (SocketWho who)
Get the Rtt estimator of the socket.
uint32_t GetRWnd (SocketWho who)
Get the rWnd of the selected socket.
Ptr< TcpRxBuffer > GetRxBuffer (SocketWho who)
Get the Rx buffer from selected socket.
uint32_t GetSegSize (SocketWho who)
Get the segment size of the node specified.
Ptr< TcpSocketMsgBase > GetSenderSocket ()
Get the pointer to a previously created sender socket.
Time GetStartTime () const
Get the data start time.
Ptr< TcpSocketState > GetTcb (SocketWho who)
Get the TCB from selected socket.
TcpSocket::TcpStates_t GetTcpState (SocketWho who)
Get the state of the TCP state machine.
Ptr< TcpTxBuffer > GetTxBuffer (SocketWho who)
Get the Tx buffer from selected socket.
virtual void HighestTxSeqTrace (SequenceNumber32 oldValue, SequenceNumber32 newValue)
Highest tx seq changes.
virtual void NextTxSeqTrace (SequenceNumber32 oldValue, SequenceNumber32 newValue)
Next tx seq changes.
virtual void ProcessedAck (const Ptr< const TcpSocketState > tcb, const TcpHeader &h, SocketWho who)
Processed ack.
virtual void RateSampleUpdatedTrace (const TcpRateLinux::TcpRateSample &sample)
Track the rate sample value of TcpRateLinux.
virtual void RateUpdatedTrace (const TcpRateLinux::TcpRateConnection &rate)
Track the rate value of TcpRateLinux.
virtual void RcvAck (const Ptr< const TcpSocketState > tcb, const TcpHeader &h, SocketWho who)
Received ack.
virtual void ReceivePacket (Ptr< Socket > socket)
Packet received.
virtual void RtoTrace (Time oldValue, Time newValue)
RTO changes.
void SendPacket (Ptr< Socket > socket, uint32_t pktSize, uint32_t pktCount, Time pktInterval)
Send packets to other endpoint.
void SetAppPktCount (uint32_t pktCount)
Set app packet count.
void SetAppPktInterval (Time pktInterval)
Interval between app-generated packet.
void SetAppPktSize (uint32_t pktSize)
Set app packet size.
void SetCongestionControl (TypeId congControl)
Congestion control of the sender socket.
void SetDelAckMaxCount (SocketWho who, uint32_t count)
Forcefully set the delayed acknowledgement count.
void SetInitialCwnd (SocketWho who, uint32_t initialCwnd)
Forcefully set the initial cwnd.
void SetInitialSsThresh (SocketWho who, uint32_t initialSsThresh)
Forcefully set the initial ssthresh.
void SetMTU (uint32_t mtu)
MTU of the bottleneck link.
void SetPaceInitialWindow (SocketWho who, bool paceWindow)
Enable or disable pacing of the initial window.
void SetPacingStatus (SocketWho who, bool pacing)
Enable or disable pacing in the TCP socket.
void SetPropagationDelay (Time propDelay)
Propagation delay of the bottleneck link.
void SetRcvBufSize (SocketWho who, uint32_t size)
Forcefully set a defined size for rx buffer.
void SetRecoveryAlgorithm (TypeId reccovery)
recovery algorithm of the sender socket
void SetSegmentSize (SocketWho who, uint32_t segmentSize)
Forcefully set the segment size.
void SetTransmitStart (Time startTime)
Set the initial time at which the application sends the first data packet.
void SetUseEcn (SocketWho who, TcpSocketState::UseEcn_t useEcn)
Forcefully set the ECN mode of use.
virtual void SsThreshTrace (uint32_t oldValue, uint32_t newValue)
Slow start threshold changes.
virtual void UpdatedRttHistory (const SequenceNumber32 &seq, uint32_t sz, bool isRetransmission, SocketWho who)
Updated the Rtt history.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Private Attributes
uint32_t m_bytesInFlight
Current bytes in flight.
uint32_t m_curCwnd
Current sender cWnd.
uint32_t m_delAckMaxCount
Delayed ack count for receiver.
EventId m_event
Check event.
Time m_expectedInterval
Theoretical estimate of the time at which next packet is scheduled for transmission.
bool m_initial
True on first run.
uint32_t m_initialCwnd
Initial value of cWnd.
bool m_isConnAboutToEnd
True when sender receives a FIN/ACK from receiver.
bool m_isFullCwndSent
True if all bytes for that cWnd is sent and sender is waiting for an ACK.
Time m_nextPacketInterval
Time maintained by Tx () trace about interval at which next packet will be sent.
bool m_paceInitialWindow
True if initial window should be paced.
uint16_t m_pacingCaRatio
Pacing factor during Congestion Avoidance.
uint16_t m_pacingSsRatio
Pacing factor during Slow Start.
uint32_t m_packets
Number of packets.
uint32_t m_packetSize
Size of the packets.
uint32_t m_packetsSent
Number of packets sent by sender so far.
Time m_prevTxTime
Time when Tx was previously called.
uint32_t m_segmentSize
Segment size.
uint32_t m_ssThresh
Slow start threshold.
Time m_tracedRtt
Traced value of RTT, which may be different from the environment RTT in case of delayed ACKs.
Time m_transmissionStartTime
Time at which sender starts data transmission.
Additional Inherited Members
Public Types inherited from ns3::TcpGeneralTest
enum SocketWho { SENDER , RECEIVER }
Used as parameter of methods, specifies on what node the caller is interested (e.g.
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Attributes inherited from ns3::TcpGeneralTest
TypeId m_congControlTypeId
Congestion control.
TypeId m_recoveryTypeId
Recovery.
Detailed Description
Test the behavior of TCP pacing.
This test checks that packets are paced at correct intervals. The test uses a shadow pacing rate calculation assumed to match the internal pacing calculation. Therefore, if you modify the values of pacingSsRatio and pacingCaRatio herein, ensure that you also change values used in the TCP implementation to match.
This test environment uses an RTT of 100ms The time interval between two consecutive packet transmissions is measured Pacing rate should be at least cwnd / rtt to transmit cwnd segments per rtt. Linux multiples this basic ratio by an additional factor, to yield pacingRate = (factor * cwnd) / rtt Since pacingRate can also be written as segmentSize / interval we can solve for interval = (segmentSize * rtt) / (factor * cwnd)
The test checks whether the measured interval lies within a tolerance value of the expected interval. The tolerance or error margin was chosen to be 10 Nanoseconds, that could be due to delay introduced by the application's send process.
This check should not be performed for a packet transmission after the sender has sent all bytes corresponding to the window and is awaiting an ACK from the receiver (corresponding to m_isFullCwndSent). Pacing check should be performed when the sender is actively sending packets from cwnd.
The same argument applies when the sender has finished sending packets and is awaiting a FIN/ACK from the receiver, to send the final ACK
As can be seen in TcpSocketBase::UpdatePacingRate (), different pacing ratios are used when cwnd < ssThresh / 2 and when cwnd > ssThresh / 2
A few key points to note:
In TcpSocketBase, pacing rate is updated whenever an ACK is received.
The factors that could contribute to a different value of pacing rate include congestion window and RTT.
However, the cWnd trace is called after Rx () trace and we therefore update the expected interval in cWnd trace.
An RTT trace is also necessary, since using delayed ACKs may lead to a higher RTT measurement at the sender's end. The expected interval should be updated here as well.
When sending the current packet, TcpSocketBase automatically decides the time at which next packet should be sent. So, if say packet 3 is sent and an ACK is received before packet 4 is sent (thus updating the pacing rate), this does not change the time at which packet 4 is to be sent. When packet 4 is indeed sent later, the new pacing rate is used to decide when packet 5 will be sent. This behavior is captured in m_nextPacketInterval, which is not affected by change of pacing rate before the next packet is sent. The important observation here is to realize the contrast between m_expectedInterval and m_nextPacketInterval.
Definition at line 90 of file tcp-pacing-test.cc.
Constructor & Destructor Documentation
TcpPacingTest()
TcpPacingTest::TcpPacingTest (uint32_t segmentSize, uint32_t packetSize, uint32_t packets, uint16_t pacingSsRatio, uint16_t pacingCaRatio, uint32_t ssThresh, bool paceInitialWindow, uint32_t delAckMaxCount, const TypeId & congControl, const std::string & desc)
Constructor.
Parameters
segmentSize Segment size at the TCP layer (bytes).
packetSize Size of packets sent at the application layer (bytes).
packets Number of packets.
pacingSsRatio Pacing Ratio during Slow Start (multiplied by 100)
pacingCaRatio Pacing Ratio during Congestion Avoidance (multiplied by 100)
ssThresh slow start threshold (bytes)
paceInitialWindow whether to pace the initial window
delAckMaxCount Delayed ACK max count parameter
congControl Type of congestion control.
desc The test description.
Definition at line 155 of file tcp-pacing-test.cc.
References ns3::TcpGeneralTest::m_congControlTypeId.
Member Function Documentation
BytesInFlightTrace()
void TcpPacingTest::BytesInFlightTrace (uint32_t oldValue, uint32_t newValue) protected virtual
Bytes in flight changes.
This applies only for sender socket.
Parameters
oldValue old value
newValue new value
Reimplemented from ns3::TcpGeneralTest.
Definition at line 238 of file tcp-pacing-test.cc.
References m_bytesInFlight.
ConfigureEnvironment()
void TcpPacingTest::ConfigureEnvironment (void) protected virtual
Change the configuration of the environment.
Reimplemented from ns3::TcpGeneralTest.
Definition at line 191 of file tcp-pacing-test.cc.
References m_packets, m_packetSize, ns3::MilliSeconds(), ns3::NanoSeconds(), ns3::Seconds(), ns3::TcpGeneralTest::SetAppPktCount(), ns3::TcpGeneralTest::SetAppPktInterval(), ns3::TcpGeneralTest::SetAppPktSize(), ns3::TcpGeneralTest::SetMTU(), ns3::TcpGeneralTest::SetPropagationDelay(), and ns3::TcpGeneralTest::SetTransmitStart().
ConfigureProperties()
void TcpPacingTest::ConfigureProperties (void) protected virtual
Change the configuration of the socket properties.
Reimplemented from ns3::TcpGeneralTest.
Definition at line 202 of file tcp-pacing-test.cc.
References m_delAckMaxCount, m_initialCwnd, m_paceInitialWindow, m_segmentSize, m_ssThresh, NS_LOG_DEBUG, ns3::TcpGeneralTest::RECEIVER, ns3::TcpGeneralTest::SENDER, ns3::TcpGeneralTest::SetDelAckMaxCount(), ns3::TcpGeneralTest::SetInitialCwnd(), ns3::TcpGeneralTest::SetInitialSsThresh(), ns3::TcpGeneralTest::SetPaceInitialWindow(), ns3::TcpGeneralTest::SetPacingStatus(), and ns3::TcpGeneralTest::SetSegmentSize().
CWndTrace()
void TcpPacingTest::CWndTrace (uint32_t oldValue, uint32_t newValue) protected virtual
Tracks the congestion window changes.
Parameters
oldValue old value
newValue new value
Reimplemented from ns3::TcpGeneralTest.
Definition at line 224 of file tcp-pacing-test.cc.
References m_curCwnd, m_initial, NS_LOG_FUNCTION, and UpdateExpectedInterval().
NormalClose()
void TcpPacingTest::NormalClose (SocketWho who) protected virtual
Socket closed normally.
Parameters
who the socket closed (SENDER or RECEIVER)
Reimplemented from ns3::TcpGeneralTest.
Definition at line 348 of file tcp-pacing-test.cc.
References ns3::EventId::Cancel(), m_event, and ns3::TcpGeneralTest::SENDER.
PhyDrop()
void TcpPacingTest::PhyDrop (SocketWho who) protected virtual
Link drop.
Parameters
who where the drop occurred (SENDER or RECEIVER)
Reimplemented from ns3::TcpGeneralTest.
Definition at line 342 of file tcp-pacing-test.cc.
References NS_FATAL_ERROR.
QueueDrop()
void TcpPacingTest::QueueDrop (SocketWho who) protected virtual
Drop on the queue.
Parameters
who where the drop occurred (SENDER or RECEIVER)
Reimplemented from ns3::TcpGeneralTest.
Definition at line 336 of file tcp-pacing-test.cc.
References NS_FATAL_ERROR.
RttTrace()
void TcpPacingTest::RttTrace (Time oldTime, Time newTime) protected virtual
Rtt changes.
This applies only for sender socket.
Parameters
oldTime old value
newTime new value
Reimplemented from ns3::TcpGeneralTest.
Definition at line 216 of file tcp-pacing-test.cc.
References m_tracedRtt, NS_LOG_FUNCTION, and UpdateExpectedInterval().
Rx()
void TcpPacingTest::Rx (const Ptr< const Packet > p, const TcpHeader & h, SocketWho who) protected virtual
Packet received from IP layer.
Parameters
p packet
h header
who the socket which has received the packet (SENDER or RECEIVER)
Reimplemented from ns3::TcpGeneralTest.
Definition at line 270 of file tcp-pacing-test.cc.
References ns3::TcpHeader::GetFlags(), m_isConnAboutToEnd, NS_LOG_DEBUG, and ns3::TcpGeneralTest::SENDER.
Tx()
void TcpPacingTest::Tx (const Ptr< const Packet > p, const TcpHeader & h, SocketWho who) protected virtual
Packet transmitted down to IP layer.
Parameters
p packet
h header
who the socket which has received the packet (SENDER or RECEIVER)
Reimplemented from ns3::TcpGeneralTest.
Definition at line 291 of file tcp-pacing-test.cc.
References ns3::Time::GetSeconds(), m_bytesInFlight, m_curCwnd, m_expectedInterval, m_isConnAboutToEnd, m_isFullCwndSent, m_nextPacketInterval, m_packetsSent, m_prevTxTime, m_segmentSize, ns3::NanoSeconds(), ns3::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_TEST_ASSERT_MSG_LT_OR_EQ, and ns3::TcpGeneralTest::SENDER.
UpdateExpectedInterval()
void TcpPacingTest::UpdateExpectedInterval (void) protected virtual
Update the expected interval at which next packet will be sent.
Definition at line 244 of file tcp-pacing-test.cc.
References ns3::TcpGeneralTest::GetPropagationDelay(), ns3::Time::GetSeconds(), m_curCwnd, m_expectedInterval, m_initialCwnd, m_paceInitialWindow, m_pacingCaRatio, m_pacingSsRatio, m_segmentSize, m_ssThresh, m_tracedRtt, and ns3::Seconds().
Referenced by CWndTrace(), and RttTrace().
Member Data Documentation
m_bytesInFlight
uint32_t TcpPacingTest::m_bytesInFlight private
Current bytes in flight.
Definition at line 139 of file tcp-pacing-test.cc.
Referenced by BytesInFlightTrace(), and Tx().
m_curCwnd
uint32_t TcpPacingTest::m_curCwnd private
Current sender cWnd.
Definition at line 137 of file tcp-pacing-test.cc.
Referenced by CWndTrace(), Tx(), and UpdateExpectedInterval().
m_delAckMaxCount
uint32_t TcpPacingTest::m_delAckMaxCount private
Delayed ack count for receiver.
Definition at line 145 of file tcp-pacing-test.cc.
Referenced by ConfigureProperties().
m_event
EventId TcpPacingTest::m_event private
Check event.
Definition at line 134 of file tcp-pacing-test.cc.
Referenced by NormalClose().
m_expectedInterval
Time TcpPacingTest::m_expectedInterval private
Theoretical estimate of the time at which next packet is scheduled for transmission.
Definition at line 148 of file tcp-pacing-test.cc.
Referenced by Tx(), and UpdateExpectedInterval().
m_initial
bool TcpPacingTest::m_initial private
True on first run.
Definition at line 135 of file tcp-pacing-test.cc.
Referenced by CWndTrace().
m_initialCwnd
uint32_t TcpPacingTest::m_initialCwnd private
Initial value of cWnd.
Definition at line 136 of file tcp-pacing-test.cc.
Referenced by ConfigureProperties(), and UpdateExpectedInterval().
m_isConnAboutToEnd
bool TcpPacingTest::m_isConnAboutToEnd private
True when sender receives a FIN/ACK from receiver.
Definition at line 146 of file tcp-pacing-test.cc.
Referenced by Rx(), and Tx().
m_isFullCwndSent
bool TcpPacingTest::m_isFullCwndSent private
True if all bytes for that cWnd is sent and sender is waiting for an ACK.
Definition at line 138 of file tcp-pacing-test.cc.
Referenced by Tx().
m_nextPacketInterval
Time TcpPacingTest::m_nextPacketInterval private
Time maintained by Tx () trace about interval at which next packet will be sent.
Definition at line 150 of file tcp-pacing-test.cc.
Referenced by Tx().
m_paceInitialWindow
bool TcpPacingTest::m_paceInitialWindow private
True if initial window should be paced.
Definition at line 144 of file tcp-pacing-test.cc.
Referenced by ConfigureProperties(), and UpdateExpectedInterval().
m_pacingCaRatio
uint16_t TcpPacingTest::m_pacingCaRatio private
Pacing factor during Congestion Avoidance.
Definition at line 142 of file tcp-pacing-test.cc.
Referenced by UpdateExpectedInterval().
m_pacingSsRatio
uint16_t TcpPacingTest::m_pacingSsRatio private
Pacing factor during Slow Start.
Definition at line 141 of file tcp-pacing-test.cc.
Referenced by UpdateExpectedInterval().
m_packets
uint32_t TcpPacingTest::m_packets private
Number of packets.
Definition at line 133 of file tcp-pacing-test.cc.
Referenced by ConfigureEnvironment().
m_packetSize
uint32_t TcpPacingTest::m_packetSize private
Size of the packets.
Definition at line 132 of file tcp-pacing-test.cc.
Referenced by ConfigureEnvironment().
m_packetsSent
uint32_t TcpPacingTest::m_packetsSent private
Number of packets sent by sender so far.
Definition at line 149 of file tcp-pacing-test.cc.
Referenced by Tx().
m_prevTxTime
Time TcpPacingTest::m_prevTxTime private
Time when Tx was previously called.
Definition at line 140 of file tcp-pacing-test.cc.
Referenced by Tx().
m_segmentSize
uint32_t TcpPacingTest::m_segmentSize private
Segment size.
Definition at line 131 of file tcp-pacing-test.cc.
Referenced by ConfigureProperties(), Tx(), and UpdateExpectedInterval().
m_ssThresh
uint32_t TcpPacingTest::m_ssThresh private
Slow start threshold.
Definition at line 143 of file tcp-pacing-test.cc.
Referenced by ConfigureProperties(), and UpdateExpectedInterval().
m_tracedRtt
Time TcpPacingTest::m_tracedRtt private
Traced value of RTT, which may be different from the environment RTT in case of delayed ACKs.
Definition at line 151 of file tcp-pacing-test.cc.
Referenced by RttTrace(), and UpdateExpectedInterval().
m_transmissionStartTime
Time TcpPacingTest::m_transmissionStartTime private
Time at which sender starts data transmission.
Definition at line 147 of file tcp-pacing-test.cc.
The documentation for this class was generated from the following file:
src/internet/test/tcp-pacing-test.cc