ns-3: LrWpanDataIfsTestCase Class Reference
LrWpanDataIfsTestCase Class Reference
LR-WPAN models » LrWpan module tests | Test suites
LrWpan Dataframe transmission with Interframe Space.
Public Member Functions
LrWpanDataIfsTestCase ()
virtual ~LrWpanDataIfsTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Static Private Member Functions
static void DataConfirm (LrWpanDataIfsTestCase *testcase, Ptr< LrWpanNetDevice > dev, McpsDataConfirmParams params)
static void DataReceived (LrWpanDataIfsTestCase *testcase, Ptr< LrWpanNetDevice > dev, Ptr< const Packet >)
static void MacState (LrWpanDataIfsTestCase *testcase, Ptr< LrWpanNetDevice > dev, LrWpanMacState oldValue, LrWpanMacState newValue)
Private Attributes
Time m_ackRxTime
The time of the received acknoledgment.
Time m_endIfs
The time where the Interframe Space ended.
Time m_lastTxTime
The time of the last transmitted packet.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
LrWpan Dataframe transmission with Interframe Space.
Definition at line 46 of file lr-wpan-ifs-test.cc.
Constructor & Destructor Documentation
LrWpanDataIfsTestCase()
LrWpanDataIfsTestCase::LrWpanDataIfsTestCase ()
Definition at line 79 of file lr-wpan-ifs-test.cc.
~LrWpanDataIfsTestCase()
LrWpanDataIfsTestCase::~LrWpanDataIfsTestCase () virtual
Definition at line 85 of file lr-wpan-ifs-test.cc.
Member Function Documentation
DataConfirm()
void LrWpanDataIfsTestCase::DataConfirm (LrWpanDataIfsTestCase * testcase, Ptr< LrWpanNetDevice > dev, McpsDataConfirmParams params) static private
Definition at line 91 of file lr-wpan-ifs-test.cc.
References ns3::Time::GetSeconds(), m_lastTxTime, and ns3::Now().
Referenced by DoRun().
DataReceived()
void LrWpanDataIfsTestCase::DataReceived (LrWpanDataIfsTestCase * testcase, Ptr< LrWpanNetDevice > dev, Ptr< const Packet > p) static private
Definition at line 99 of file lr-wpan-ifs-test.cc.
References ns3::Time::GetSeconds(), ns3::LrWpanMacHeader::IsAcknowledgment(), m_ackRxTime, ns3::Now(), NS_ASSERT, and ns3::Packet::RemoveHeader().
Referenced by DoRun().
DoRun()
void LrWpanDataIfsTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 126 of file lr-wpan-ifs-test.cc.
References ns3::Node::AddDevice(), third::channel, DataConfirm(), DataReceived(), ns3::LrWpanNetDevice::GetMac(), ns3::LrWpanNetDevice::GetPhy(), m_ackRxTime, ns3::McpsDataRequestParams::m_dstAddr, ns3::McpsDataRequestParams::m_dstAddrMode, ns3::McpsDataRequestParams::m_dstPanId, m_endIfs, m_lastTxTime, ns3::McpsDataRequestParams::m_msduHandle, ns3::McpsDataRequestParams::m_srcAddrMode, ns3::McpsDataRequestParams::m_txOptions, MacState(), ns3::MakeBoundCallback(), ns3::MicroSeconds(), NS_TEST_EXPECT_MSG_EQ, ns3::Seconds(), ns3::LrWpanNetDevice::SetAddress(), ns3::LrWpanNetDevice::SetChannel(), ns3::SHORT_ADDR, and ns3::TX_OPTION_ACK.
MacState()
void LrWpanDataIfsTestCase::MacState (LrWpanDataIfsTestCase * testcase, Ptr< LrWpanNetDevice > dev, LrWpanMacState oldValue, LrWpanMacState newValue) static private
Definition at line 112 of file lr-wpan-ifs-test.cc.
References ns3::Time::GetSeconds(), m_endIfs, ns3::MAC_IDLE, and ns3::Now().
Referenced by DoRun().
Member Data Documentation
m_ackRxTime
Time LrWpanDataIfsTestCase::m_ackRxTime private
The time of the received acknoledgment.
Definition at line 72 of file lr-wpan-ifs-test.cc.
Referenced by DataReceived(), and DoRun().
m_endIfs
Time LrWpanDataIfsTestCase::m_endIfs private
The time where the Interframe Space ended.
Definition at line 73 of file lr-wpan-ifs-test.cc.
Referenced by DoRun(), and MacState().
m_lastTxTime
Time LrWpanDataIfsTestCase::m_lastTxTime private
The time of the last transmitted packet.
Definition at line 71 of file lr-wpan-ifs-test.cc.
Referenced by DataConfirm(), and DoRun().
The documentation for this class was generated from the following file:
src/lr-wpan/test/lr-wpan-ifs-test.cc