ns-3: ns3::LrWpanMacTrailer Class Reference
ns3::LrWpanMacTrailer Class Reference
LR-WPAN models
Represent the Mac Trailer with the Frame Check Sequence field.
#include "lr-wpan-mac-trailer.h"
Public Member Functions
LrWpanMacTrailer (void)
Default constructor for a MAC trailer with disabled FCS calculation.
bool CheckFcs (Ptr< const Packet > p)
Check the FCS of a given packet against the FCS value stored in the trailer.
virtual uint32_t Deserialize (Buffer::Iterator start)
void EnableFcs (bool enable)
Enable or disable FCS calculation for this trailer.
uint16_t GetFcs (void) const
Get this trailers FCS value.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize (void) const
bool IsFcsEnabled (void)
Query if FCS calculation is enabled for this trailer.
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetFcs (Ptr< const Packet > p)
Calculate and set the FCS value based on the given packet.
Public Member Functions inherited from ns3::Trailer
virtual ~Trailer ()
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Trailer
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static const uint16_t LR_WPAN_MAC_FCS_LENGTH = 2
The length in octets of the IEEE 802.15.4 MAC FCS field.
Private Member Functions
uint16_t GenerateCrc16 (uint8_t *data, int length)
Calculate the 16-bit FCS value.
Private Attributes
bool m_calcFcs
Only if m_calcFcs is true, FCS values will be calculated and used in the trailer.
uint16_t m_fcs
The FCS value stored in this trailer.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Represent the Mac Trailer with the Frame Check Sequence field.
Introspection did not find any typical Config paths.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 16 bytes (on a 64-bit architecture).
Definition at line 38 of file lr-wpan-mac-trailer.h.
Constructor & Destructor Documentation
LrWpanMacTrailer()
ns3::LrWpanMacTrailer::LrWpanMacTrailer (void)
Default constructor for a MAC trailer with disabled FCS calculation.
Definition at line 32 of file lr-wpan-mac-trailer.cc.
Member Function Documentation
CheckFcs()
bool ns3::LrWpanMacTrailer::CheckFcs (Ptr< const Packet > p)
Check the FCS of a given packet against the FCS value stored in the trailer.
The packet itself should contain no trailer. If FCS calculation is disabled for this trailer, CheckFcs() will always return true.
Parameters
p the packet to be checked
Returns
false, if the FCS values do not match, true otherwise
Definition at line 107 of file lr-wpan-mac-trailer.cc.
References GenerateCrc16(), GetFcs(), and m_calcFcs.
Referenced by ns3::LrWpanMac::PdDataIndication().
Deserialize()
uint32_t ns3::LrWpanMacTrailer::Deserialize (Buffer::Iterator end) virtual
Parameters
end an iterator which points to the end of the buffer where the trailer should be read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveTrailer to re-create a trailer from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this trailer in real networks. The input iterator points to the end of the area where the data shall be written. This method is thus expected to call Buffer::Iterator::Prev prior to actually reading any data.
Implements ns3::Trailer.
Definition at line 75 of file lr-wpan-mac-trailer.cc.
References LR_WPAN_MAC_FCS_LENGTH, m_fcs, and visualizer.core::start().
EnableFcs()
void ns3::LrWpanMacTrailer::EnableFcs (bool enable)
Enable or disable FCS calculation for this trailer.
Parameters
enable flag, indicating if FCS calculation should be enabled or not
Definition at line 128 of file lr-wpan-mac-trailer.cc.
References m_calcFcs, and m_fcs.
Referenced by ns3::LrWpanMac::McpsDataRequest(), ns3::LrWpanMac::PdDataIndication(), ns3::LrWpanMac::SendAck(), and ns3::LrWpanMac::SendOneBeacon().
GenerateCrc16()
uint16_t ns3::LrWpanMacTrailer::GenerateCrc16 (uint8_t * data, int length) private
Calculate the 16-bit FCS value.
CRC16-CCITT with a generator polynomial = ^16 + ^12 + ^5 + 1, LSB first and initial value = 0x0000.
Parameters
data the checksum will be calculated over this data
length the length of the data
Returns
the checksum
Definition at line 144 of file lr-wpan-mac-trailer.cc.
References data.
Referenced by CheckFcs(), and SetFcs().
GetFcs()
uint16_t ns3::LrWpanMacTrailer::GetFcs (void) const
Get this trailers FCS value.
If FCS calculation is disabled for this trailer, the returned value is always 0.
Returns
the FCS value.
Definition at line 84 of file lr-wpan-mac-trailer.cc.
References m_fcs.
Referenced by CheckFcs().
GetInstanceTypeId()
TypeId ns3::LrWpanMacTrailer::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 50 of file lr-wpan-mac-trailer.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::LrWpanMacTrailer::GetSerializedSize (void) const virtual
Returns
the expected size of the trailer.
This method is used by Packet::AddTrailer to store a trailer into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full trailer data by Serialize.
Implements ns3::Trailer.
Definition at line 62 of file lr-wpan-mac-trailer.cc.
References LR_WPAN_MAC_FCS_LENGTH.
GetTypeId()
TypeId ns3::LrWpanMacTrailer::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 39 of file lr-wpan-mac-trailer.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
IsFcsEnabled()
bool ns3::LrWpanMacTrailer::IsFcsEnabled (void)
Query if FCS calculation is enabled for this trailer.
Returns
true, if FCS calculation is enabled, false otherwise.
Definition at line 138 of file lr-wpan-mac-trailer.cc.
References m_calcFcs.
Print()
void ns3::LrWpanMacTrailer::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a trailer as ascii data to a c++ output stream. Although the trailer is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Trailer.
Definition at line 56 of file lr-wpan-mac-trailer.cc.
References m_fcs.
Serialize()
void ns3::LrWpanMacTrailer::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the trailer should be written.
This method is used by Packet::AddTrailer to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this trailer in real networks. The input iterator points to the end of the area where the data shall be written. This method is thus expected to call Buffer::Iterator::Prev prior to actually writing any data.
Implements ns3::Trailer.
Definition at line 68 of file lr-wpan-mac-trailer.cc.
References LR_WPAN_MAC_FCS_LENGTH, m_fcs, and visualizer.core::start().
SetFcs()
void ns3::LrWpanMacTrailer::SetFcs (Ptr< const Packet > p)
Calculate and set the FCS value based on the given packet.
Parameters
p the packet for which the FCS should be calculated
Definition at line 90 of file lr-wpan-mac-trailer.cc.
References GenerateCrc16(), m_calcFcs, and m_fcs.
Referenced by ns3::LrWpanMac::McpsDataRequest(), ns3::LrWpanMac::SendAck(), and ns3::LrWpanMac::SendOneBeacon().
Member Data Documentation
LR_WPAN_MAC_FCS_LENGTH
const uint16_t ns3::LrWpanMacTrailer::LR_WPAN_MAC_FCS_LENGTH = 2 static
The length in octets of the IEEE 802.15.4 MAC FCS field.
Definition at line 44 of file lr-wpan-mac-trailer.h.
Referenced by Deserialize(), GetSerializedSize(), and Serialize().
m_calcFcs
bool ns3::LrWpanMacTrailer::m_calcFcs private
Only if m_calcFcs is true, FCS values will be calculated and used in the trailer.
Definition at line 125 of file lr-wpan-mac-trailer.h.
Referenced by CheckFcs(), EnableFcs(), IsFcsEnabled(), and SetFcs().
m_fcs
uint16_t ns3::LrWpanMacTrailer::m_fcs private
The FCS value stored in this trailer.
Definition at line 119 of file lr-wpan-mac-trailer.h.
Referenced by Deserialize(), EnableFcs(), GetFcs(), Print(), Serialize(), and SetFcs().
The documentation for this class was generated from the following files:
src/lr-wpan/model/lr-wpan-mac-trailer.h
src/lr-wpan/model/lr-wpan-mac-trailer.cc