ns-3: ns3::UdpServerHelper Class Reference
ns3::UdpServerHelper Class Reference
Applications » UdpClientServer
Create a server application which waits for input UDP packets and uses the information carried into their payload to compute delay and to determine if some packets are lost.
#include "udp-client-server-helper.h"
Public Member Functions
UdpServerHelper ()
Create UdpServerHelper which will make life easier for people trying to set up simulations with udp-client-server application.
UdpServerHelper (uint16_t port)
Create UdpServerHelper which will make life easier for people trying to set up simulations with udp-client-server application.
Ptr< UdpServer > GetServer (void)
Return the last created server.
ApplicationContainer Install (NodeContainer c)
Create one UDP server application on each of the Nodes in the NodeContainer.
void SetAttribute (std::string name, const AttributeValue &value)
Record an attribute to be set in each Application after it is is created.
Private Attributes
ObjectFactory m_factory
Object factory.
Ptr< UdpServer > m_server
The last created server application.
Detailed Description
Create a server application which waits for input UDP packets and uses the information carried into their payload to compute delay and to determine if some packets are lost.
Definition at line 37 of file udp-client-server-helper.h.
Constructor & Destructor Documentation
UdpServerHelper() [1/2]
ns3::UdpServerHelper::UdpServerHelper ()
Create UdpServerHelper which will make life easier for people trying to set up simulations with udp-client-server application.
Definition at line 29 of file udp-client-server-helper.cc.
References ns3::UdpServer::GetTypeId(), m_factory, and ns3::ObjectFactory::SetTypeId().
UdpServerHelper() [2/2]
ns3::UdpServerHelper::UdpServerHelper (uint16_t port)
Create UdpServerHelper which will make life easier for people trying to set up simulations with udp-client-server application.
Parameters
port The port the server will wait on for incoming packets
Definition at line 34 of file udp-client-server-helper.cc.
References ns3::UdpServer::GetTypeId(), m_factory, port, SetAttribute(), and ns3::ObjectFactory::SetTypeId().
Member Function Documentation
GetServer()
Ptr< UdpServer > ns3::UdpServerHelper::GetServer (void)
Return the last created server.
This function is mainly used for testing.
Returns
a Ptr to the last created server application
Definition at line 63 of file udp-client-server-helper.cc.
References m_server.
Referenced by UdpClientServerTestCase::DoRun(), and UdpTraceClientServerTestCase::DoRun().
Install()
ApplicationContainer ns3::UdpServerHelper::Install (NodeContainer c)
Create one UDP server application on each of the Nodes in the NodeContainer.
Parameters
c The nodes on which to create the Applications. The nodes are specified by a NodeContainer.
Returns
The applications created, one Application per Node in the NodeContainer.
Definition at line 47 of file udp-client-server-helper.cc.
References ns3::ApplicationContainer::Add(), ns3::Node::AddApplication(), ns3::NodeContainer::Begin(), ns3::ObjectFactory::Create(), ns3::NodeContainer::End(), m_factory, and m_server.
Referenced by UdpClientServerTestCase::DoRun(), UdpTraceClientServerTestCase::DoRun(), Issue211Test::DoRun(), and Experiment::Run().
SetAttribute()
void ns3::UdpServerHelper::SetAttribute (std::string name, const AttributeValue & value)
Record an attribute to be set in each Application after it is is created.
Parameters
name the name of the attribute to set
value the value of the attribute to set
Definition at line 41 of file udp-client-server-helper.cc.
References m_factory, and ns3::ObjectFactory::Set().
Referenced by UdpServerHelper().
Member Data Documentation
m_factory
ObjectFactory ns3::UdpServerHelper::m_factory private
Object factory.
Definition at line 83 of file udp-client-server-helper.h.
Referenced by UdpServerHelper(), Install(), and SetAttribute().
m_server
Ptr<UdpServer> ns3::UdpServerHelper::m_server private
The last created server application.
Definition at line 84 of file udp-client-server-helper.h.
Referenced by GetServer(), and Install().
The documentation for this class was generated from the following files:
src/applications/helper/udp-client-server-helper.h
src/applications/helper/udp-client-server-helper.cc