ns-3: ns3::ThreeGppPropagationLossModel Class Reference
ns3::ThreeGppPropagationLossModel Class Reference abstract
Base class for the 3GPP propagation models.
#include "three-gpp-propagation-loss-model.h"
Classes
struct ShadowingMapItem
Define a struct for the m_shadowingMap entries.
Public Member Functions
ThreeGppPropagationLossModel ()
Constructor.
ThreeGppPropagationLossModel (const ThreeGppPropagationLossModel &)=delete
Copy constructor.
virtual ~ThreeGppPropagationLossModel () override
Destructor.
Ptr< ChannelConditionModel > GetChannelConditionModel (void) const
Returns the associated channel condition model.
double GetFrequency (void) const
Return the current central frequency.
ThreeGppPropagationLossModel & operator= (const ThreeGppPropagationLossModel &)=delete
Copy constructor.
void SetChannelConditionModel (Ptr< ChannelConditionModel > model)
Set the channel condition model used to determine the channel state (e.g., the LOS/NLOS condition)
void SetFrequency (double f)
Set the central frequency of the model.
Public Member Functions inherited from ns3::PropagationLossModel
PropagationLossModel ()
virtual ~PropagationLossModel ()
int64_t AssignStreams (int64_t stream)
If this loss model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
double CalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account all the PropagationLossModel(s) chained to the current one.
Ptr< PropagationLossModel > GetNext ()
Gets the next PropagationLossModel in the chain of loss models that act on the signal.
void SetNext (Ptr< PropagationLossModel > next)
Enables a chain of loss models to act on the signal.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::PropagationLossModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose () override
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Static Protected Member Functions
static double Calculate2dDistance (Vector a, Vector b)
Computes the 2D distance between two 3D vectors.
Protected Attributes
Ptr< ChannelConditionModel > m_channelConditionModel
pointer to the channel condition model
double m_frequency
operating frequency in Hz
Ptr< NormalRandomVariable > m_normRandomVariable
normal random variable
bool m_shadowingEnabled
enable/disable shadowing
std::unordered_map< uint32_t, ShadowingMapItem > m_shadowingMap
map to store the shadowing values
Private Member Functions
virtual int64_t DoAssignStreams (int64_t stream) override
If this model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
virtual double DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const override
Computes the received power by applying the pathloss model described in 3GPP TR 38.901.
double GetLoss (Ptr< ChannelCondition > cond, double distance2D, double distance3D, double hUt, double hBs) const
Computes the pathloss between a and b.
virtual double GetLossLos (double distance2D, double distance3D, double hUt, double hBs) const =0
Computes the pathloss between a and b considering that the line of sight is not obstructed.
virtual double GetLossNlos (double distance2D, double distance3D, double hUt, double hBs) const =0
Computes the pathloss between a and b considering that the line of sight is obstructed.
virtual double GetLossNlosv (double distance2D, double distance3D, double hUt, double hBs) const
Computes the pathloss between a and b considering that the line of sight is obstructed by a vehicle.
double GetShadowing (Ptr< MobilityModel > a, Ptr< MobilityModel > b, ChannelCondition::LosConditionValue cond) const
Retrieves the shadowing value by looking at m_shadowingMap.
virtual double GetShadowingCorrelationDistance (ChannelCondition::LosConditionValue cond) const =0
Returns the shadow fading correlation distance.
virtual double GetShadowingStd (Ptr< MobilityModel > a, Ptr< MobilityModel > b, ChannelCondition::LosConditionValue cond) const =0
Returns the shadow fading standard deviation.
virtual std::pair< double, double > GetUtAndBsHeights (double za, double zb) const
Determines hUT and hBS.
Static Private Member Functions
static uint32_t GetKey (Ptr< MobilityModel > a, Ptr< MobilityModel > b)
Returns an unique key for the channel between a and b.
static Vector GetVectorDifference (Ptr< MobilityModel > a, Ptr< MobilityModel > b)
Get the difference between the node position.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Base class for the 3GPP propagation models.
Config Paths
ns3::ThreeGppPropagationLossModel is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::SpectrumChannel/PropagationLossModel/$ns3::ThreeGppPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::YansWifiChannel/PropagationLossModel/$ns3::ThreeGppPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::LrWpanNetDevice/Channel/PropagationLossModel/$ns3::ThreeGppPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::SpectrumChannel/PropagationLossModel/$ns3::ThreeGppPropagationLossModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::YansWifiChannel/PropagationLossModel/$ns3::ThreeGppPropagationLossModel"
"/ChannelList/[i]/$ns3::SpectrumChannel/PropagationLossModel/$ns3::ThreeGppPropagationLossModel"
"/ChannelList/[i]/$ns3::YansWifiChannel/PropagationLossModel/$ns3::ThreeGppPropagationLossModel"
Attributes
Frequency: The centre frequency in Hz.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 5e+08
Flags: construct write read
ShadowingEnabled: Enable/disable shadowing.
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
ChannelConditionModel: Pointer to the channel condition model.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::ChannelConditionModel>
Initial value: 0x0
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 112 bytes (on a 64-bit architecture).
Definition at line 31 of file three-gpp-propagation-loss-model.h.
Constructor & Destructor Documentation
ThreeGppPropagationLossModel() [1/2]
ns3::ThreeGppPropagationLossModel::ThreeGppPropagationLossModel ()
Constructor.
Definition at line 65 of file three-gpp-propagation-loss-model.cc.
References m_normRandomVariable, and NS_LOG_FUNCTION.
~ThreeGppPropagationLossModel()
ns3::ThreeGppPropagationLossModel::~ThreeGppPropagationLossModel () override virtual
Destructor.
Definition at line 76 of file three-gpp-propagation-loss-model.cc.
References NS_LOG_FUNCTION.
ThreeGppPropagationLossModel() [2/2]
ns3::ThreeGppPropagationLossModel::ThreeGppPropagationLossModel (const ThreeGppPropagationLossModel &) delete
Copy constructor.
Defined and unimplemented to avoid misuse
Member Function Documentation
Calculate2dDistance()
double ns3::ThreeGppPropagationLossModel::Calculate2dDistance (Vector a, Vector b) static protected
Computes the 2D distance between two 3D vectors.
Parameters
a the first 3D vector
b the second 3D vector
Returns
the 2D distance between a and b
Definition at line 257 of file three-gpp-propagation-loss-model.cc.
References sample-rng-plot::x.
Referenced by DoCalcRxPower(), and ns3::ThreeGppRmaPropagationLossModel::GetShadowingStd().
DoAssignStreams()
int64_t ns3::ThreeGppPropagationLossModel::DoAssignStreams (int64_t stream) override private virtual
If this model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream
Returns
the number of stream indices assigned by this model
Implements ns3::PropagationLossModel.
Reimplemented in ns3::ThreeGppUmaPropagationLossModel.
Definition at line 248 of file three-gpp-propagation-loss-model.cc.
References m_normRandomVariable, and NS_LOG_FUNCTION.
DoCalcRxPower()
double ns3::ThreeGppPropagationLossModel::DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const override private virtual
Computes the received power by applying the pathloss model described in 3GPP TR 38.901.
Parameters
txPowerDbm tx power in dBm
a tx mobility model
b rx mobility model
Returns
the rx power in dBm
Implements ns3::PropagationLossModel.
Definition at line 119 of file three-gpp-propagation-loss-model.cc.
References Calculate2dDistance(), ns3::CalculateDistance(), GetLoss(), ns3::MobilityModel::GetPosition(), GetShadowing(), GetUtAndBsHeights(), m_channelConditionModel, m_frequency, m_shadowingEnabled, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
DoDispose()
void ns3::ThreeGppPropagationLossModel::DoDispose (void) override protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 82 of file three-gpp-propagation-loss-model.cc.
References m_channelConditionModel, and m_shadowingMap.
GetChannelConditionModel()
Ptr< ChannelConditionModel > ns3::ThreeGppPropagationLossModel::GetChannelConditionModel (void) const
Returns the associated channel condition model.
Returns
the channel condition model
Definition at line 97 of file three-gpp-propagation-loss-model.cc.
References m_channelConditionModel, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetFrequency()
double ns3::ThreeGppPropagationLossModel::GetFrequency (void) const
Return the current central frequency.
Returns
The current central frequency
Definition at line 112 of file three-gpp-propagation-loss-model.cc.
References m_frequency, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetKey()
uint32_t ns3::ThreeGppPropagationLossModel::GetKey (Ptr< MobilityModel > a, Ptr< MobilityModel > b) static private
Returns an unique key for the channel between a and b.
The key is the value of the Cantor function calculated by using as first parameter the lowest node ID, and as a second parameter the highest node ID.
Parameters
a tx mobility model
b rx mobility model
Returns
channel key
Definition at line 267 of file three-gpp-propagation-loss-model.cc.
References ns3::Node::GetId(), ns3::Object::GetObject(), max, and min.
Referenced by GetShadowing().
GetLoss()
double ns3::ThreeGppPropagationLossModel::GetLoss (Ptr< ChannelCondition > cond, double distance2D, double distance3D, double hUt, double hBs) const private
Computes the pathloss between a and b.
Parameters
cond the channel condition
distance2D the 2D distance between tx and rx in meters
distance3D the 3D distance between tx and rx in meters
hUt the height of the UT in meters
hBs the height of the BS in meters
Returns
pathloss value in dB
Definition at line 153 of file three-gpp-propagation-loss-model.cc.
References GetLossLos(), GetLossNlos(), GetLossNlosv(), NS_FATAL_ERROR, and NS_LOG_FUNCTION.
Referenced by DoCalcRxPower().
GetLossLos()
virtual double ns3::ThreeGppPropagationLossModel::GetLossLos (double distance2D, double distance3D, double hUt, double hBs) const private pure virtual
Computes the pathloss between a and b considering that the line of sight is not obstructed.
Parameters
distance2D the 2D distance between tx and rx in meters
distance3D the 3D distance between tx and rx in meters
hUt the height of the UT in meters
hBs the height of the BS in meters
Returns
pathloss value in dB
Implemented in ns3::ThreeGppV2vHighwayPropagationLossModel, ns3::ThreeGppV2vUrbanPropagationLossModel, ns3::ThreeGppIndoorOfficePropagationLossModel, ns3::ThreeGppUmiStreetCanyonPropagationLossModel, ns3::ThreeGppUmaPropagationLossModel, and ns3::ThreeGppRmaPropagationLossModel.
Referenced by GetLoss().
GetLossNlos()
virtual double ns3::ThreeGppPropagationLossModel::GetLossNlos (double distance2D, double distance3D, double hUt, double hBs) const private pure virtual
Computes the pathloss between a and b considering that the line of sight is obstructed.
Parameters
distance2D the 2D distance between tx and rx in meters
distance3D the 3D distance between tx and rx in meters
hUt the height of the UT in meters
hBs the height of the BS in meters
Returns
pathloss value in dB
Implemented in ns3::ThreeGppV2vUrbanPropagationLossModel, ns3::ThreeGppIndoorOfficePropagationLossModel, ns3::ThreeGppUmiStreetCanyonPropagationLossModel, ns3::ThreeGppUmaPropagationLossModel, and ns3::ThreeGppRmaPropagationLossModel.
Referenced by GetLoss().
GetLossNlosv()
double ns3::ThreeGppPropagationLossModel::GetLossNlosv (double distance2D, double distance3D, double hUt, double hBs) const private virtual
Computes the pathloss between a and b considering that the line of sight is obstructed by a vehicle.
By default it raises an error to avoid misuse.
Parameters
distance2D the 2D distance between tx and rx in meters
distance3D the 3D distance between tx and rx in meters
hUt the height of the UT in meters
hBs the height of the BS in meters
Returns
pathloss value in dB
Reimplemented in ns3::ThreeGppV2vUrbanPropagationLossModel.
Definition at line 178 of file three-gpp-propagation-loss-model.cc.
References NS_FATAL_ERROR, and NS_LOG_FUNCTION.
Referenced by GetLoss().
GetShadowing()
double ns3::ThreeGppPropagationLossModel::GetShadowing (Ptr< MobilityModel > a, Ptr< MobilityModel > b, ChannelCondition::LosConditionValue cond) const private
Retrieves the shadowing value by looking at m_shadowingMap.
If not found or if the channel condition changed it generates a new independent realization and stores it in the map, otherwise it correlates the new value with the previous one using the autocorrelation function defined in 3GPP TR 38.901, Sec. 7.4.4.
Parameters
a tx mobility model
b rx mobility model
cond the LOS/NLOS channel condition
Returns
shadowing loss in dB
Definition at line 186 of file three-gpp-propagation-loss-model.cc.
References GetKey(), ns3::Vector2D::GetLength(), GetShadowingCorrelationDistance(), GetShadowingStd(), GetVectorDifference(), m_normRandomVariable, m_shadowingMap, and NS_LOG_FUNCTION.
Referenced by DoCalcRxPower().
GetShadowingCorrelationDistance()
virtual double ns3::ThreeGppPropagationLossModel::GetShadowingCorrelationDistance (ChannelCondition::LosConditionValue cond) const private pure virtual
Returns the shadow fading correlation distance.
Parameters
cond the LOS/NLOS channel condition
Returns
shadowing correlation distance in meters
Implemented in ns3::ThreeGppV2vUrbanPropagationLossModel, ns3::ThreeGppIndoorOfficePropagationLossModel, ns3::ThreeGppUmiStreetCanyonPropagationLossModel, ns3::ThreeGppUmaPropagationLossModel, and ns3::ThreeGppRmaPropagationLossModel.
Referenced by GetShadowing().
GetShadowingStd()
virtual double ns3::ThreeGppPropagationLossModel::GetShadowingStd (Ptr< MobilityModel > a, Ptr< MobilityModel > b, ChannelCondition::LosConditionValue cond) const private pure virtual
Returns the shadow fading standard deviation.
Parameters
a tx mobility model
b rx mobility model
cond the LOS/NLOS channel condition
Returns
shadowing std in dB
Implemented in ns3::ThreeGppV2vUrbanPropagationLossModel, ns3::ThreeGppIndoorOfficePropagationLossModel, ns3::ThreeGppUmiStreetCanyonPropagationLossModel, ns3::ThreeGppUmaPropagationLossModel, and ns3::ThreeGppRmaPropagationLossModel.
Referenced by GetShadowing().
GetTypeId()
TypeId ns3::ThreeGppPropagationLossModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 42 of file three-gpp-propagation-loss-model.cc.
References GetChannelConditionModel(), GetFrequency(), m_shadowingEnabled, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeDoubleAccessor(), ns3::MakePointerAccessor(), SetChannelConditionModel(), SetFrequency(), and ns3::TypeId::SetParent().
GetUtAndBsHeights()
std::pair< double, double > ns3::ThreeGppPropagationLossModel::GetUtAndBsHeights (double za, double zb) const private virtual
Determines hUT and hBS.
The default implementation assumes that the tallest node is the BS and the smallest is the UT. The derived classes can change the default behavior by overriding this method.
Parameters
za the height of the first node in meters
zb the height of the second node in meters
Returns
std::pair of heights in meters, the first element is hUt and the second is hBs
Reimplemented in ns3::ThreeGppUmiStreetCanyonPropagationLossModel.
Definition at line 237 of file three-gpp-propagation-loss-model.cc.
References max, and min.
Referenced by DoCalcRxPower().
GetVectorDifference()
Vector ns3::ThreeGppPropagationLossModel::GetVectorDifference (Ptr< MobilityModel > a, Ptr< MobilityModel > b) static private
Get the difference between the node position.
The difference is calculated as (b-a) if Id(a) < Id (b), or (a-b) if Id(b) <= Id(a).
Parameters
a First node
b Second node
Returns
the difference between the node vector position
Definition at line 281 of file three-gpp-propagation-loss-model.cc.
References ns3::Object::GetObject(), and ns3::MobilityModel::GetPosition().
Referenced by GetShadowing().
operator=()
ThreeGppPropagationLossModel& ns3::ThreeGppPropagationLossModel::operator= (const ThreeGppPropagationLossModel &) delete
Copy constructor.
Defined and unimplemented to avoid misuse
Returns
the ThreeGppPropagationLossModel instance
SetChannelConditionModel()
void ns3::ThreeGppPropagationLossModel::SetChannelConditionModel (Ptr< ChannelConditionModel > model)
Set the channel condition model used to determine the channel state (e.g., the LOS/NLOS condition)
Parameters
model pointer to the channel condition model
Definition at line 90 of file three-gpp-propagation-loss-model.cc.
References m_channelConditionModel, and NS_LOG_FUNCTION.
Referenced by ThreeGppShadowingTestCase::ChangeChannelCondition(), ThreeGppV2vUrbanPropagationLossModelTestCase::DoRun(), ThreeGppV2vHighwayPropagationLossModelTestCase::DoRun(), GetTypeId(), and ThreeGppShadowingTestCase::RunTest().
SetFrequency()
void ns3::ThreeGppPropagationLossModel::SetFrequency (double f)
Set the central frequency of the model.
Parameters
f the central frequency in the range in Hz, between 500.0e6 and 100.0e9 Hz
Definition at line 104 of file three-gpp-propagation-loss-model.cc.
References f(), m_frequency, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
Member Data Documentation
m_channelConditionModel
Ptr<ChannelConditionModel> ns3::ThreeGppPropagationLossModel::m_channelConditionModel protected
pointer to the channel condition model
Definition at line 235 of file three-gpp-propagation-loss-model.h.
Referenced by ns3::ThreeGppIndoorOfficePropagationLossModel::ThreeGppIndoorOfficePropagationLossModel(), ns3::ThreeGppRmaPropagationLossModel::ThreeGppRmaPropagationLossModel(), ns3::ThreeGppUmaPropagationLossModel::ThreeGppUmaPropagationLossModel(), ns3::ThreeGppUmiStreetCanyonPropagationLossModel::ThreeGppUmiStreetCanyonPropagationLossModel(), DoCalcRxPower(), DoDispose(), GetChannelConditionModel(), and SetChannelConditionModel().
m_frequency
double ns3::ThreeGppPropagationLossModel::m_frequency protected
operating frequency in Hz
Definition at line 236 of file three-gpp-propagation-loss-model.h.
Referenced by DoCalcRxPower(), ns3::ThreeGppUmaPropagationLossModel::GetBpDistance(), ns3::ThreeGppUmiStreetCanyonPropagationLossModel::GetBpDistance(), GetFrequency(), ns3::ThreeGppRmaPropagationLossModel::GetLossLos(), ns3::ThreeGppUmaPropagationLossModel::GetLossLos(), ns3::ThreeGppUmiStreetCanyonPropagationLossModel::GetLossLos(), ns3::ThreeGppIndoorOfficePropagationLossModel::GetLossLos(), ns3::ThreeGppV2vUrbanPropagationLossModel::GetLossLos(), ns3::ThreeGppV2vHighwayPropagationLossModel::GetLossLos(), ns3::ThreeGppRmaPropagationLossModel::GetLossNlos(), ns3::ThreeGppUmaPropagationLossModel::GetLossNlos(), ns3::ThreeGppUmiStreetCanyonPropagationLossModel::GetLossNlos(), ns3::ThreeGppIndoorOfficePropagationLossModel::GetLossNlos(), ns3::ThreeGppV2vUrbanPropagationLossModel::GetLossNlos(), ns3::ThreeGppRmaPropagationLossModel::GetShadowingStd(), and SetFrequency().
m_normRandomVariable
Ptr<NormalRandomVariable> ns3::ThreeGppPropagationLossModel::m_normRandomVariable protected
normal random variable
Definition at line 238 of file three-gpp-propagation-loss-model.h.
Referenced by ThreeGppPropagationLossModel(), DoAssignStreams(), ns3::ThreeGppUmaPropagationLossModel::DoAssignStreams(), and GetShadowing().
m_shadowingEnabled
bool ns3::ThreeGppPropagationLossModel::m_shadowingEnabled protected
enable/disable shadowing
Definition at line 237 of file three-gpp-propagation-loss-model.h.
Referenced by DoCalcRxPower(), and GetTypeId().
m_shadowingMap
std::unordered_map<uint32_t, ShadowingMapItem> ns3::ThreeGppPropagationLossModel::m_shadowingMap mutable protected
map to store the shadowing values
Definition at line 248 of file three-gpp-propagation-loss-model.h.
Referenced by DoDispose(), and GetShadowing().
The documentation for this class was generated from the following files:
src/propagation/model/three-gpp-propagation-loss-model.h
src/propagation/model/three-gpp-propagation-loss-model.cc