ns-3: ns3::GenericMacHeader Class Reference
ns3::GenericMacHeader Class Reference
WiMAX Models
This class implements the Generic mac Header as described by IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems 6.3.2.1.1 Generic MAC header, page 36.
#include "wimax-mac-header.h"
Public Member Functions
GenericMacHeader (void)
~GenericMacHeader (void)
bool check_hcs (void) const
Check HCS.
uint32_t Deserialize (Buffer::Iterator start)
uint8_t GetCi (void) const
Get CI field.
Cid GetCid (void) const
Get CID field.
uint8_t GetEc (void) const
Get EC field.
uint8_t GetEks (void) const
Get EKS field.
uint8_t GetHcs (void) const
Get HCS field.
uint8_t GetHt (void) const
Get HT field.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint16_t GetLen (void) const
Get length field.
std::string GetName (void) const
Get name field.
uint32_t GetSerializedSize (void) const
uint8_t GetType (void) const
Get type field.
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetCi (uint8_t ci)
Set CI field.
void SetCid (Cid cid)
Set CID field.
void SetEc (uint8_t ec)
Set EC field.
void SetEks (uint8_t eks)
Set EKS field.
void SetHcs (uint8_t hcs)
Set HCS field.
void SetHt (uint8_t ht)
Set HT field.
void SetLen (uint16_t len)
Set length field.
void SetType (uint8_t type)
Set type field.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t c_hcs
calculated header check sequence; this is used to check if the received header is correct or not
uint8_t m_ci
CRC Indicator.
Cid m_cid
CID.
uint8_t m_ec
Encryption Control.
uint8_t m_eks
Encryption Key Sequence.
uint8_t m_esf
ESF.
uint8_t m_hcs
Header Check Sequence.
uint8_t m_ht
Header type.
uint16_t m_len
length
uint8_t m_rsv1
RSV.
uint8_t m_type
type
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class implements the Generic mac Header as described by IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems 6.3.2.1.1 Generic MAC header, page 36.
Introspection did not find any typical Config paths.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 24 bytes (on a 64-bit architecture).
Definition at line 108 of file wimax-mac-header.h.
Constructor & Destructor Documentation
GenericMacHeader()
ns3::GenericMacHeader::GenericMacHeader (void)
Definition at line 101 of file wimax-mac-header.cc.
References c_hcs, m_esf, m_hcs, and m_rsv1.
~GenericMacHeader()
ns3::GenericMacHeader::~GenericMacHeader (void)
Definition at line 116 of file wimax-mac-header.cc.
Member Function Documentation
check_hcs()
bool ns3::GenericMacHeader::check_hcs (void) const
Check HCS.
Returns
true if HCS is validated
Definition at line 300 of file wimax-mac-header.cc.
References c_hcs, and m_hcs.
Referenced by ns3::BaseStationNetDevice::DoReceive(), and ns3::SubscriberStationNetDevice::DoReceive().
Deserialize()
uint32_t ns3::GenericMacHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 263 of file wimax-mac-header.cc.
References c_hcs, ns3::CRC8Calculate(), ns3::Buffer::Iterator::GetDistanceFrom(), m_ci, m_cid, m_ec, m_eks, m_esf, m_hcs, m_ht, m_len, m_rsv1, m_type, ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetCi()
uint8_t ns3::GenericMacHeader::GetCi (void) const
Get CI field.
Returns
the CI
Definition at line 175 of file wimax-mac-header.cc.
References m_ci.
GetCid()
Cid ns3::GenericMacHeader::GetCid (void) const
Get CID field.
Returns
the CID
Definition at line 190 of file wimax-mac-header.cc.
References m_cid.
Referenced by ns3::BSSchedulerRtps::BSSchedulerBasicConnection(), ns3::BSSchedulerRtps::BSSchedulerBEConnection(), ns3::BSSchedulerRtps::BSSchedulerBroadcastConnection(), ns3::BSSchedulerRtps::BSSchedulerInitialRangingConnection(), ns3::BSSchedulerRtps::BSSchedulerNRTPSConnection(), ns3::BSSchedulerRtps::BSSchedulerPrimaryConnection(), ns3::BSSchedulerRtps::BSSchedulerRTPSConnection(), ns3::BaseStationNetDevice::DoReceive(), and ns3::SubscriberStationNetDevice::DoReceive().
GetEc()
uint8_t ns3::GenericMacHeader::GetEc (void) const
Get EC field.
Returns
the EC
Definition at line 165 of file wimax-mac-header.cc.
References m_ec.
GetEks()
uint8_t ns3::GenericMacHeader::GetEks (void) const
Get EKS field.
Returns
the EKS
Definition at line 180 of file wimax-mac-header.cc.
References m_eks.
GetHcs()
uint8_t ns3::GenericMacHeader::GetHcs (void) const
Get HCS field.
Returns
the HCS
Definition at line 195 of file wimax-mac-header.cc.
References m_hcs.
GetHt()
uint8_t ns3::GenericMacHeader::GetHt (void) const
Get HT field.
Returns
the HT
Definition at line 160 of file wimax-mac-header.cc.
References m_ht.
Referenced by ns3::BaseStationNetDevice::DoReceive(), and ns3::SubscriberStationNetDevice::DoReceive().
GetInstanceTypeId()
TypeId ns3::GenericMacHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 215 of file wimax-mac-header.cc.
References GetTypeId().
GetLen()
uint16_t ns3::GenericMacHeader::GetLen (void) const
Get length field.
Returns
the length
Definition at line 185 of file wimax-mac-header.cc.
References m_len.
GetName()
std::string ns3::GenericMacHeader::GetName (void) const
Get name field.
Returns
the name
Definition at line 200 of file wimax-mac-header.cc.
GetSerializedSize()
uint32_t ns3::GenericMacHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 227 of file wimax-mac-header.cc.
Referenced by ns3::WimaxMacQueue::Dequeue(), Ns3WimaxFragmentationTestCase::DoRun(), ns3::BaseStationNetDevice::Enqueue(), ns3::SubscriberStationNetDevice::Enqueue(), and ns3::WimaxMacQueue::GetFirstPacketHdrSize().
GetType()
uint8_t ns3::GenericMacHeader::GetType (void) const
Get type field.
Returns
the type
Definition at line 170 of file wimax-mac-header.cc.
References m_type.
Referenced by ns3::WimaxMacQueue::Dequeue(), ns3::BaseStationNetDevice::DoReceive(), ns3::SubscriberStationNetDevice::DoReceive(), and Ns3WimaxFragmentationTestCase::DoRun().
GetTypeId()
TypeId ns3::GenericMacHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 205 of file wimax-mac-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::GenericMacHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 220 of file wimax-mac-header.cc.
References m_ci, m_cid, m_ec, m_eks, m_hcs, m_len, and m_type.
Serialize()
void ns3::GenericMacHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 232 of file wimax-mac-header.cc.
References ns3::CRC8Calculate(), ns3::Cid::GetIdentifier(), m_ci, m_cid, m_ec, m_eks, m_esf, m_ht, m_len, m_rsv1, m_type, visualizer.core::start(), and ns3::Buffer::Iterator::WriteU8().
SetCi()
void ns3::GenericMacHeader::SetCi (uint8_t ci)
Set CI field.
Parameters
ci the CI
Definition at line 135 of file wimax-mac-header.cc.
References m_ci.
SetCid()
void ns3::GenericMacHeader::SetCid (Cid cid)
Set CID field.
Parameters
cid the CID
Definition at line 150 of file wimax-mac-header.cc.
References m_cid.
Referenced by Ns3WimaxFragmentationTestCase::DoRun(), ns3::BaseStationNetDevice::Enqueue(), and ns3::SubscriberStationNetDevice::Enqueue().
SetEc()
void ns3::GenericMacHeader::SetEc (uint8_t ec)
Set EC field.
Parameters
ec the EC
Definition at line 125 of file wimax-mac-header.cc.
References m_ec.
SetEks()
void ns3::GenericMacHeader::SetEks (uint8_t eks)
Set EKS field.
Parameters
eks the EKS
Definition at line 140 of file wimax-mac-header.cc.
References m_eks.
SetHcs()
void ns3::GenericMacHeader::SetHcs (uint8_t hcs)
Set HCS field.
Parameters
hcs the HCS
Definition at line 155 of file wimax-mac-header.cc.
References m_hcs.
SetHt()
void ns3::GenericMacHeader::SetHt (uint8_t ht)
Set HT field.
Parameters
ht the HT
Definition at line 120 of file wimax-mac-header.cc.
References m_ht.
SetLen()
void ns3::GenericMacHeader::SetLen (uint16_t len)
Set length field.
Parameters
len the length
Definition at line 145 of file wimax-mac-header.cc.
References m_len.
Referenced by ns3::WimaxMacQueue::Dequeue(), Ns3WimaxFragmentationTestCase::DoRun(), ns3::BaseStationNetDevice::Enqueue(), and ns3::SubscriberStationNetDevice::Enqueue().
SetType()
void ns3::GenericMacHeader::SetType (uint8_t type)
Set type field.
Parameters
type the type
Definition at line 130 of file wimax-mac-header.cc.
References m_type.
Referenced by ns3::WimaxMacQueue::Dequeue().
Member Data Documentation
c_hcs
uint8_t ns3::GenericMacHeader::c_hcs private
calculated header check sequence; this is used to check if the received header is correct or not
Definition at line 226 of file wimax-mac-header.h.
Referenced by GenericMacHeader(), check_hcs(), and Deserialize().
m_ci
uint8_t ns3::GenericMacHeader::m_ci private
CRC Indicator.
Definition at line 220 of file wimax-mac-header.h.
Referenced by Deserialize(), GetCi(), Print(), Serialize(), and SetCi().
m_cid
Cid ns3::GenericMacHeader::m_cid private
CID.
Definition at line 224 of file wimax-mac-header.h.
Referenced by Deserialize(), GetCid(), Print(), Serialize(), and SetCid().
m_ec
uint8_t ns3::GenericMacHeader::m_ec private
Encryption Control.
Definition at line 217 of file wimax-mac-header.h.
Referenced by Deserialize(), GetEc(), Print(), Serialize(), and SetEc().
m_eks
uint8_t ns3::GenericMacHeader::m_eks private
Encryption Key Sequence.
Definition at line 221 of file wimax-mac-header.h.
Referenced by Deserialize(), GetEks(), Print(), Serialize(), and SetEks().
m_esf
uint8_t ns3::GenericMacHeader::m_esf private
ESF.
Definition at line 219 of file wimax-mac-header.h.
Referenced by GenericMacHeader(), Deserialize(), and Serialize().
m_hcs
uint8_t ns3::GenericMacHeader::m_hcs private
Header Check Sequence.
Definition at line 225 of file wimax-mac-header.h.
Referenced by GenericMacHeader(), check_hcs(), Deserialize(), GetHcs(), Print(), and SetHcs().
m_ht
uint8_t ns3::GenericMacHeader::m_ht private
Header type.
Definition at line 216 of file wimax-mac-header.h.
Referenced by Deserialize(), GetHt(), Serialize(), and SetHt().
m_len
uint16_t ns3::GenericMacHeader::m_len private
length
Definition at line 223 of file wimax-mac-header.h.
Referenced by Deserialize(), GetLen(), Print(), Serialize(), and SetLen().
m_rsv1
uint8_t ns3::GenericMacHeader::m_rsv1 private
RSV.
Definition at line 222 of file wimax-mac-header.h.
Referenced by GenericMacHeader(), Deserialize(), and Serialize().
m_type
uint8_t ns3::GenericMacHeader::m_type private
type
Definition at line 218 of file wimax-mac-header.h.
Referenced by Deserialize(), GetType(), Print(), Serialize(), and SetType().
The documentation for this class was generated from the following files:
src/wimax/model/wimax-mac-header.h
src/wimax/model/wimax-mac-header.cc