ns-3: ns3::ProtocolTlvValue Class Reference
ns3::ProtocolTlvValue Class Reference
WiMAX Models
ProtocolTlvValue class.
#include "wimax-tlv.h"
Public Types
typedef std::vector< uint8_t >::const_iterator Iterator
Iterator typedef.
Public Member Functions
ProtocolTlvValue ()
~ProtocolTlvValue ()
void Add (uint8_t protocol)
Add protocol number.
Iterator Begin () const
Begin iterator.
virtual ProtocolTlvValue * Copy (void) const
Copy.
virtual uint32_t Deserialize (Buffer::Iterator start, uint64_t valueLength)
Deserialize from a buffer.
Iterator End () const
End iterator.
virtual uint32_t GetSerializedSize (void) const
Get serialized size in bytes.
virtual void Serialize (Buffer::Iterator start) const
Serialize to a buffer.
Public Member Functions inherited from ns3::TlvValue
virtual ~TlvValue ()
Private Attributes
std::vector< uint8_t > * m_protocol
protocol
Detailed Description
ProtocolTlvValue class.
Definition at line 516 of file wimax-tlv.h.
Member Typedef Documentation
Iterator
typedef std::vector<uint8_t>::const_iterator ns3::ProtocolTlvValue::Iterator
Iterator typedef.
Definition at line 522 of file wimax-tlv.h.
Constructor & Destructor Documentation
ProtocolTlvValue()
ns3::ProtocolTlvValue::ProtocolTlvValue ()
Definition at line 950 of file wimax-tlv.cc.
References m_protocol.
Referenced by Copy().
~ProtocolTlvValue()
ns3::ProtocolTlvValue::~ProtocolTlvValue ()
Definition at line 954 of file wimax-tlv.cc.
References m_protocol.
Member Function Documentation
Add()
void ns3::ProtocolTlvValue::Add (uint8_t protocol)
Add protocol number.
Parameters
protocol the protocol number
Definition at line 992 of file wimax-tlv.cc.
References m_protocol.
Referenced by Copy(), Deserialize(), and ns3::IpcsClassifierRecord::ToTlv().
Begin()
ProtocolTlvValue::Iterator ns3::ProtocolTlvValue::Begin (void) const
Begin iterator.
Returns
the beginning element
Definition at line 998 of file wimax-tlv.cc.
References m_protocol.
Copy()
ProtocolTlvValue * ns3::ProtocolTlvValue::Copy (void) const virtual
Copy.
Returns
the protocol tlv value
Implements ns3::TlvValue.
Definition at line 1010 of file wimax-tlv.cc.
References ProtocolTlvValue(), Add(), and m_protocol.
Deserialize()
uint32_t ns3::ProtocolTlvValue::Deserialize (Buffer::Iterator start, uint64_t valueLen) virtual
Deserialize from a buffer.
Parameters
start the iterator
valueLen the maximum length of the value
Returns
the
Implements ns3::TlvValue.
Definition at line 980 of file wimax-tlv.cc.
References Add(), and ns3::Buffer::Iterator::ReadU8().
Referenced by ns3::ClassificationRuleVectorTlvValue::Deserialize().
End()
ProtocolTlvValue::Iterator ns3::ProtocolTlvValue::End (void) const
End iterator.
Returns
the ending element
Definition at line 1004 of file wimax-tlv.cc.
References m_protocol.
GetSerializedSize()
uint32_t ns3::ProtocolTlvValue::GetSerializedSize (void) const virtual
Get serialized size in bytes.
Returns
the serialized size
Implements ns3::TlvValue.
Definition at line 965 of file wimax-tlv.cc.
References m_protocol.
Referenced by ns3::ClassificationRuleVectorTlvValue::Deserialize(), and ns3::IpcsClassifierRecord::ToTlv().
Serialize()
void ns3::ProtocolTlvValue::Serialize (Buffer::Iterator start) const virtual
Serialize to a buffer.
Parameters
start the iterator
Implements ns3::TlvValue.
Definition at line 971 of file wimax-tlv.cc.
References m_protocol, and ns3::Buffer::Iterator::WriteU8().
Member Data Documentation
m_protocol
std::vector<uint8_t>* ns3::ProtocolTlvValue::m_protocol private
protocol
Definition at line 547 of file wimax-tlv.h.
Referenced by ProtocolTlvValue(), ~ProtocolTlvValue(), Add(), Begin(), Copy(), End(), GetSerializedSize(), and Serialize().
The documentation for this class was generated from the following files:
src/wimax/model/wimax-tlv.h
src/wimax/model/wimax-tlv.cc