ns-3: ns3::GrantedTimeWindowMpiInterface Class Reference
ns3::GrantedTimeWindowMpiInterface Class Reference
MPI Distributed Simulation
Interface between ns-3 and MPI.
#include "granted-time-window-mpi-interface.h"
Public Member Functions
virtual void Destroy ()
Deletes storage used by the parallel environment.
virtual void Disable ()
Clean up the ns-3 parallel communications interface.
virtual void Enable (int *pargc, char ***pargv)
Setup the parallel communication interface.
virtual void Enable (MPI_Comm communicator)
Setup the parallel communication interface using the specified communicator.
virtual MPI_Comm GetCommunicator ()
Return the communicator used to run ns-3.
virtual uint32_t GetSize ()
Get the number of ranks used by ns-3.
virtual uint32_t GetSystemId ()
Get the id number of this rank.
virtual bool IsEnabled ()
Returns enabled state of parallel environment.
virtual void SendPacket (Ptr< Packet > p, const Time &rxTime, uint32_t node, uint32_t dev)
Send a packet to a remote node.
Public Member Functions inherited from ns3::ParallelCommunicationInterface
virtual ~ParallelCommunicationInterface ()
Destructor.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Private Member Functions
static uint32_t GetRxCount ()
static uint32_t GetTxCount ()
static void ReceiveMessages ()
Check for received messages complete.
static void TestSendComplete ()
Check for completed sends.
Static Private Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Private Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Private Attributes
static MPI_Comm g_communicator = MPI_COMM_WORLD
MPI communicator being used for ns-3 tasks.
static bool g_enabled = false
Has this interface been enabled.
static bool g_freeCommunicator = false
Did ns-3 create the communicator? Have to free it.
static bool g_mpiInitCalled = false
Has MPI Init been called by this interface.
static std::list< SentBuffer > g_pendingTx
List of pending non-blocking sends.
static char ** g_pRxBuffers
Data buffers for non-blocking reads.
static MPI_Request * g_requests
Pending non-blocking receives.
static uint32_t g_rxCount = 0
Total packets received.
static uint32_t g_sid = 0
System ID (rank) for this task.
static uint32_t g_size = 1
Size of the MPI COM_WORLD group.
static uint32_t g_txCount = 0
Total packets sent.
Additional Inherited Members
Private Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Private Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Interface between ns-3 and MPI.
Implements the interface used by the singleton parallel controller to interface between NS3 and the communications layer being used for inter-task packet transfers.
Definition at line 93 of file granted-time-window-mpi-interface.h.
Member Function Documentation
Destroy()
void ns3::GrantedTimeWindowMpiInterface::Destroy () virtual
Deletes storage used by the parallel environment.
Implements ns3::ParallelCommunicationInterface.
Definition at line 105 of file granted-time-window-mpi-interface.cc.
References g_pendingTx, g_pRxBuffers, g_requests, GetSize(), and NS_LOG_FUNCTION.
Disable()
void ns3::GrantedTimeWindowMpiInterface::Disable () virtual
Clean up the ns-3 parallel communications interface.
MPI_Finalize will be called only if Enable (int* pargc, char*** pargv) was called.
Implements ns3::ParallelCommunicationInterface.
Definition at line 320 of file granted-time-window-mpi-interface.cc.
References g_communicator, g_enabled, g_freeCommunicator, g_mpiInitCalled, NS_FATAL_ERROR, and NS_LOG_FUNCTION_NOARGS.
Enable() [1/2]
void ns3::GrantedTimeWindowMpiInterface::Enable (int * pargc, char *** pargv) virtual
Setup the parallel communication interface.
There are two ways to setup the communications interface. This Enable method is the easiest method and should be used in most situations.
Disable() must be invoked at end of an ns-3 application to properly cleanup the parallel communication interface.
This method will call MPI_Init and configure ns-3 to use the MPI_COMM_WORLD communicator.
For more complex situations, such as embedding ns-3 with other MPI simulators or libraries, the Enable(MPI_Comm communcicator) may be used if MPI is initialized externally or if ns-3 needs to be run unique communicator. For example if there are two parallel simulators and the goal is to run each simulator on a different set of ranks.
Note
The `SimulatorImplementationType attribute in ns3::GlobalValues must be set before calling Enable()
Parameters
pargc number of command line arguments
pargv command line arguments
Implements ns3::ParallelCommunicationInterface.
Definition at line 161 of file granted-time-window-mpi-interface.cc.
References g_enabled, g_mpiInitCalled, NS_ASSERT, and NS_LOG_FUNCTION.
Enable() [2/2]
void ns3::GrantedTimeWindowMpiInterface::Enable (MPI_Comm communicator) virtual
Setup the parallel communication interface using the specified communicator.
See Enable (int* pargc, char*** pargv) for additional information.
Parameters
communicator MPI Communicator that should be used by ns-3
Implements ns3::ParallelCommunicationInterface.
Definition at line 175 of file granted-time-window-mpi-interface.cc.
References g_communicator, g_enabled, g_freeCommunicator, g_pRxBuffers, g_requests, g_sid, g_size, GetSize(), ns3::MAX_MPI_MSG_SIZE, NS_ASSERT, and NS_LOG_FUNCTION.
GetCommunicator()
MPI_Comm ns3::GrantedTimeWindowMpiInterface::GetCommunicator () virtual
Return the communicator used to run ns-3.
The communicator returned will be MPI_COMM_WORLD if Enable (int* pargc, char*** pargv) is used to enable or the user specified communicator if Enable (MPI_Comm communicator) is used.
Returns
The MPI Communicator.
Implements ns3::ParallelCommunicationInterface.
Definition at line 154 of file granted-time-window-mpi-interface.cc.
References g_communicator, g_enabled, and NS_ASSERT.
GetRxCount()
uint32_t ns3::GrantedTimeWindowMpiInterface::GetRxCount () static private
Returns
received count in packets
Definition at line 120 of file granted-time-window-mpi-interface.cc.
References g_enabled, g_rxCount, and NS_ASSERT.
Referenced by ns3::DistributedSimulatorImpl::Run().
GetSize()
uint32_t ns3::GrantedTimeWindowMpiInterface::GetSize () virtual
Get the number of ranks used by ns-3.
Returns the size (number of MPI ranks) of the communicator used by ns-3. When running a sequential simulation this will return a size of 1.
Returns
number of parallel tasks
Implements ns3::ParallelCommunicationInterface.
Definition at line 141 of file granted-time-window-mpi-interface.cc.
References g_enabled, g_size, and NS_ASSERT.
Referenced by Destroy(), and Enable().
GetSystemId()
uint32_t ns3::GrantedTimeWindowMpiInterface::GetSystemId () virtual
Get the id number of this rank.
When running a sequential simulation this will return a systemID of 0.
Returns
system identification
Implements ns3::ParallelCommunicationInterface.
Definition at line 134 of file granted-time-window-mpi-interface.cc.
References g_enabled, g_sid, and NS_ASSERT.
GetTxCount()
uint32_t ns3::GrantedTimeWindowMpiInterface::GetTxCount () static private
Returns
transmitted count in packets
Definition at line 127 of file granted-time-window-mpi-interface.cc.
References g_enabled, g_txCount, and NS_ASSERT.
Referenced by ns3::DistributedSimulatorImpl::Run().
GetTypeId()
TypeId ns3::GrantedTimeWindowMpiInterface::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 95 of file granted-time-window-mpi-interface.cc.
References ns3::TypeId::SetParent().
IsEnabled()
bool ns3::GrantedTimeWindowMpiInterface::IsEnabled () virtual
Returns enabled state of parallel environment.
Returns
true if parallel communication is enabled
Implements ns3::ParallelCommunicationInterface.
Definition at line 148 of file granted-time-window-mpi-interface.cc.
References g_enabled.
ReceiveMessages()
void ns3::GrantedTimeWindowMpiInterface::ReceiveMessages () static private
Check for received messages complete.
Definition at line 240 of file granted-time-window-mpi-interface.cc.
References g_communicator, g_pRxBuffers, g_requests, g_rxCount, ns3::Node::GetDevice(), ns3::Node::GetId(), ns3::Node::GetNDevices(), ns3::NodeList::GetNode(), ns3::MpiInterface::GetSize(), ns3::MAX_MPI_MSG_SIZE, ns3::Simulator::Now(), NS_ASSERT, NS_LOG_FUNCTION_NOARGS, ns3::MpiReceiver::Receive(), and ns3::Simulator::ScheduleWithContext().
Referenced by ns3::DistributedSimulatorImpl::Run().
SendPacket()
void ns3::GrantedTimeWindowMpiInterface::SendPacket (Ptr< Packet > p, const Time & rxTime, uint32_t node, uint32_t dev) virtual
Send a packet to a remote node.
Parameters
p packet to send
rxTime received time at destination node
node destination node
dev destination device
Serialize and send a packet to the specified node and net device
Implements ns3::ParallelCommunicationInterface.
Definition at line 209 of file granted-time-window-mpi-interface.cc.
References g_communicator, g_pendingTx, g_txCount, ns3::Time::GetInteger(), ns3::NodeList::GetNode(), ns3::Packet::GetSerializedSize(), ns3::Node::GetSystemId(), ns3::Time::GetTimeStep(), NS_LOG_FUNCTION, and ns3::Packet::Serialize().
TestSendComplete()
void ns3::GrantedTimeWindowMpiInterface::TestSendComplete () static private
Check for completed sends.
Definition at line 300 of file granted-time-window-mpi-interface.cc.
References g_pendingTx, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::DistributedSimulatorImpl::Run().
Member Data Documentation
g_communicator
MPI_Comm ns3::GrantedTimeWindowMpiInterface::g_communicator = MPI_COMM_WORLD static private
MPI communicator being used for ns-3 tasks.
Definition at line 170 of file granted-time-window-mpi-interface.h.
Referenced by Disable(), Enable(), GetCommunicator(), ReceiveMessages(), and SendPacket().
g_enabled
bool ns3::GrantedTimeWindowMpiInterface::g_enabled = false static private
Has this interface been enabled.
Definition at line 152 of file granted-time-window-mpi-interface.h.
Referenced by Disable(), Enable(), GetCommunicator(), GetRxCount(), GetSize(), GetSystemId(), GetTxCount(), and IsEnabled().
g_freeCommunicator
bool ns3::GrantedTimeWindowMpiInterface::g_freeCommunicator = false static private
Did ns-3 create the communicator? Have to free it.
Definition at line 173 of file granted-time-window-mpi-interface.h.
Referenced by Disable(), and Enable().
g_mpiInitCalled
bool ns3::GrantedTimeWindowMpiInterface::g_mpiInitCalled = false static private
Has MPI Init been called by this interface.
Alternatively user supplies a communicator.
Definition at line 158 of file granted-time-window-mpi-interface.h.
Referenced by Disable(), and Enable().
g_pendingTx
std::list< SentBuffer > ns3::GrantedTimeWindowMpiInterface::g_pendingTx static private
List of pending non-blocking sends.
Definition at line 167 of file granted-time-window-mpi-interface.h.
Referenced by Destroy(), SendPacket(), and TestSendComplete().
g_pRxBuffers
char ** ns3::GrantedTimeWindowMpiInterface::g_pRxBuffers static private
Data buffers for non-blocking reads.
Definition at line 164 of file granted-time-window-mpi-interface.h.
Referenced by Destroy(), Enable(), and ReceiveMessages().
g_requests
MPI_Request * ns3::GrantedTimeWindowMpiInterface::g_requests static private
Pending non-blocking receives.
Definition at line 161 of file granted-time-window-mpi-interface.h.
Referenced by Destroy(), Enable(), and ReceiveMessages().
g_rxCount
uint32_t ns3::GrantedTimeWindowMpiInterface::g_rxCount = 0 static private
Total packets received.
Definition at line 146 of file granted-time-window-mpi-interface.h.
Referenced by GetRxCount(), and ReceiveMessages().
g_sid
uint32_t ns3::GrantedTimeWindowMpiInterface::g_sid = 0 static private
System ID (rank) for this task.
Definition at line 141 of file granted-time-window-mpi-interface.h.
Referenced by Enable(), and GetSystemId().
g_size
uint32_t ns3::GrantedTimeWindowMpiInterface::g_size = 1 static private
Size of the MPI COM_WORLD group.
Definition at line 143 of file granted-time-window-mpi-interface.h.
Referenced by Enable(), and GetSize().
g_txCount
uint32_t ns3::GrantedTimeWindowMpiInterface::g_txCount = 0 static private
Total packets sent.
Definition at line 149 of file granted-time-window-mpi-interface.h.
Referenced by GetTxCount(), and SendPacket().
The documentation for this class was generated from the following files:
src/mpi/model/granted-time-window-mpi-interface.h
src/mpi/model/granted-time-window-mpi-interface.cc