ns-3: ns3::Ipv6EndPoint Class Reference
ns3::Ipv6EndPoint Class Reference
Internet » IPv6 classes and sub-modules
A representation of an IPv6 endpoint/connection.
#include "ipv6-end-point.h"
Public Member Functions
Ipv6EndPoint (Ipv6Address addr, uint16_t port)
Constructor.
~Ipv6EndPoint ()
void BindToNetDevice (Ptr< NetDevice > netdevice)
Bind a socket to specific device.
void ForwardIcmp (Ipv6Address src, uint8_t ttl, uint8_t type, uint8_t code, uint32_t info)
Forward the ICMP packet to the upper level.
void ForwardUp (Ptr< Packet > p, Ipv6Header header, uint16_t port, Ptr< Ipv6Interface > incomingInterface)
Forward the packet to the upper level.
Ptr< NetDevice > GetBoundNetDevice (void)
Returns socket's bound netdevice, if any.
Ipv6Address GetLocalAddress ()
Get the local address.
uint16_t GetLocalPort ()
Get the local port.
Ipv6Address GetPeerAddress ()
Get the peer address.
uint16_t GetPeerPort ()
Get the peer port.
bool IsRxEnabled (void)
Checks if the endpoint can receive packets.
void SetDestroyCallback (Callback< void > callback)
Set the default destroy callback.
void SetIcmpCallback (Callback< void, Ipv6Address, uint8_t, uint8_t, uint8_t, uint32_t > callback)
Set the ICMP callback.
void SetLocalAddress (Ipv6Address addr)
Set the local address.
void SetLocalPort (uint16_t port)
Set the local port.
void SetPeer (Ipv6Address addr, uint16_t port)
Set the peer information (address and port).
void SetRxCallback (Callback< void, Ptr< Packet >, Ipv6Header, uint16_t, Ptr< Ipv6Interface > > callback)
Set the reception callback.
void SetRxEnabled (bool enabled)
Enable or Disable the endpoint Rx capability.
Private Attributes
Ptr< NetDevice > m_boundnetdevice
The NetDevice the EndPoint is bound to (if any).
Callback< void > m_destroyCallback
The destroy callback.
Callback< void, Ipv6Address, uint8_t, uint8_t, uint8_t, uint32_t > m_icmpCallback
The ICMPv6 callback.
Ipv6Address m_localAddr
The local address.
uint16_t m_localPort
The local port.
Ipv6Address m_peerAddr
The peer address.
uint16_t m_peerPort
The peer port.
Callback< void, Ptr< Packet >, Ipv6Header, uint16_t, Ptr< Ipv6Interface > > m_rxCallback
The RX callback.
bool m_rxEnabled
true if the endpoint can receive packets.
Detailed Description
A representation of an IPv6 endpoint/connection.
This class provides an Internet four-tuple (source and destination ports and addresses). These are used in the ns3::Ipv6EndPointDemux as targets of lookups. The class also has a callback for notification to higher layers that a packet from a lower layer was received. In the ns3 internet-stack, these notifications are automatically registered to be received by the corresponding socket.
Definition at line 50 of file ipv6-end-point.h.
Constructor & Destructor Documentation
Ipv6EndPoint()
ns3::Ipv6EndPoint::Ipv6EndPoint (Ipv6Address addr, uint16_t port)
Constructor.
Parameters
addr the IPv6 address
port the port
Definition at line 32 of file ipv6-end-point.cc.
~Ipv6EndPoint()
ns3::Ipv6EndPoint::~Ipv6EndPoint ()
Definition at line 41 of file ipv6-end-point.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_destroyCallback, m_icmpCallback, m_rxCallback, and ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::Nullify().
Member Function Documentation
BindToNetDevice()
void ns3::Ipv6EndPoint::BindToNetDevice (Ptr< NetDevice > netdevice)
Bind a socket to specific device.
This method corresponds to using setsockopt() SO_BINDTODEVICE of real network or BSD sockets. If set on a socket, this option will force packets to leave the bound device regardless of the device that IP routing would naturally choose. In the receive direction, only packets received from the bound interface will be delivered.
This option has no particular relationship to binding sockets to an address via Socket::Bind (). It is possible to bind sockets to a specific IP address on the bound interface by calling both Socket::Bind (address) and Socket::BindToNetDevice (device), but it is also possible to bind to mismatching device and address, even if the socket can not receive any packets as a result.
Parameters
netdevice Pointer to Netdevice of desired interface
Definition at line 82 of file ipv6-end-point.cc.
References m_boundnetdevice.
Referenced by ns3::UdpSocketImpl::Bind(), ns3::UdpSocketImpl::Bind6(), ns3::TcpSocketBase::BindToNetDevice(), and ns3::UdpSocketImpl::BindToNetDevice().
ForwardIcmp()
void ns3::Ipv6EndPoint::ForwardIcmp (Ipv6Address src, uint8_t ttl, uint8_t type, uint8_t code, uint32_t info)
Forward the ICMP packet to the upper level.
Called from an L4Protocol implementation to notify an endpoint of an icmp message reception.
Parameters
src source IPv6 address
ttl time-to-live
type ICMPv6 type
code ICMPv6 code
info ICMPv6 info
Definition at line 122 of file ipv6-end-point.cc.
References m_icmpCallback.
Referenced by ns3::TcpL4Protocol::PacketReceived(), and ns3::UdpL4Protocol::Receive().
ForwardUp()
void ns3::Ipv6EndPoint::ForwardUp (Ptr< Packet > p, Ipv6Header header, uint16_t port, Ptr< Ipv6Interface > incomingInterface)
Forward the packet to the upper level.
Called from an L4Protocol implementation to notify an endpoint of a packet reception.
Parameters
p the packet
header the packet header
port source port
incomingInterface incoming interface
Definition at line 114 of file ipv6-end-point.cc.
References m_rxCallback, and port.
GetBoundNetDevice()
Ptr< NetDevice > ns3::Ipv6EndPoint::GetBoundNetDevice (void)
Returns socket's bound netdevice, if any.
This method corresponds to using getsockopt() SO_BINDTODEVICE of real network or BSD sockets.
Returns
Pointer to interface.
Definition at line 88 of file ipv6-end-point.cc.
References m_boundnetdevice.
Referenced by ns3::Ipv6EndPointDemux::Lookup().
GetLocalAddress()
Ipv6Address ns3::Ipv6EndPoint::GetLocalAddress (void)
Get the local address.
Returns
the local address
Definition at line 52 of file ipv6-end-point.cc.
References m_localAddr.
Referenced by ns3::UdpSocketImpl::Bind(), ns3::UdpSocketImpl::BindToNetDevice(), ns3::UdpSocketImpl::DoSendTo(), ns3::TcpSocketBase::ForwardUp6(), ns3::TcpSocketBase::GetSockName(), ns3::UdpSocketImpl::GetSockName(), ns3::Ipv6EndPointDemux::Lookup(), ns3::TcpSocketBase::PersistTimeout(), ns3::TcpSocketBase::SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), ns3::TcpSocketBase::SendEmptyPacket(), and ns3::TcpSocketSmallAcks::SendEmptyPacket().
GetLocalPort()
uint16_t ns3::Ipv6EndPoint::GetLocalPort (void)
Get the local port.
Returns
the local port
Definition at line 62 of file ipv6-end-point.cc.
References m_localPort.
Referenced by ns3::UdpSocketImpl::DoSendTo(), ns3::TcpSocketBase::ForwardUp6(), ns3::TcpSocketBase::GetSockName(), ns3::UdpSocketImpl::GetSockName(), ns3::Ipv6EndPointDemux::Lookup(), ns3::TcpSocketBase::PersistTimeout(), ns3::TcpSocketBase::SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), ns3::TcpSocketBase::SendEmptyPacket(), and ns3::TcpSocketSmallAcks::SendEmptyPacket().
GetPeerAddress()
Ipv6Address ns3::Ipv6EndPoint::GetPeerAddress (void)
Get the peer address.
Returns
the peer address
Definition at line 72 of file ipv6-end-point.cc.
References m_peerAddr.
Referenced by ns3::TcpSocketBase::ForwardUp6(), ns3::TcpSocketBase::GetPeerName(), ns3::Ipv6EndPointDemux::Lookup(), ns3::TcpSocketBase::PersistTimeout(), ns3::TcpSocketBase::RecvFrom(), ns3::TcpSocketBase::SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), ns3::TcpSocketBase::SendEmptyPacket(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), and ns3::TcpSocketBase::SetupEndpoint6().
GetPeerPort()
uint16_t ns3::Ipv6EndPoint::GetPeerPort (void)
Get the peer port.
Returns
the peer port
Definition at line 77 of file ipv6-end-point.cc.
References m_peerPort.
Referenced by ns3::TcpSocketBase::ForwardUp6(), ns3::TcpSocketBase::GetPeerName(), ns3::Ipv6EndPointDemux::Lookup(), ns3::TcpSocketBase::PersistTimeout(), ns3::TcpSocketBase::RecvFrom(), ns3::TcpSocketBase::SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), ns3::TcpSocketBase::SendEmptyPacket(), and ns3::TcpSocketSmallAcks::SendEmptyPacket().
IsRxEnabled()
bool ns3::Ipv6EndPoint::IsRxEnabled (void)
Checks if the endpoint can receive packets.
Returns
true if the endpoint can receive packets.
Definition at line 136 of file ipv6-end-point.cc.
References m_rxEnabled.
Referenced by ns3::Ipv6EndPointDemux::Lookup().
SetDestroyCallback()
void ns3::Ipv6EndPoint::SetDestroyCallback (Callback< void > callback)
Set the default destroy callback.
Parameters
callback callback function
Definition at line 109 of file ipv6-end-point.cc.
References m_destroyCallback.
Referenced by ns3::TcpSocketBase::DeallocateEndPoint(), ns3::UdpSocketImpl::DeallocateEndPoint(), ns3::UdpSocketImpl::FinishBind(), and ns3::TcpSocketBase::SetupCallback().
SetIcmpCallback()
void ns3::Ipv6EndPoint::SetIcmpCallback (Callback< void, Ipv6Address, uint8_t, uint8_t, uint8_t, uint32_t > callback)
Set the ICMP callback.
Parameters
callback callback function
Definition at line 104 of file ipv6-end-point.cc.
References m_icmpCallback.
Referenced by ns3::UdpSocketImpl::FinishBind(), and ns3::TcpSocketBase::SetupCallback().
SetLocalAddress()
void ns3::Ipv6EndPoint::SetLocalAddress (Ipv6Address addr)
Set the local address.
Parameters
addr the address to set
Definition at line 57 of file ipv6-end-point.cc.
References m_localAddr.
Referenced by ns3::TcpSocketBase::SetupEndpoint6().
SetLocalPort()
void ns3::Ipv6EndPoint::SetLocalPort (uint16_t port)
Set the local port.
Parameters
port the port to set
Definition at line 67 of file ipv6-end-point.cc.
References m_localPort, and port.
SetPeer()
void ns3::Ipv6EndPoint::SetPeer (Ipv6Address addr, uint16_t port)
Set the peer information (address and port).
Parameters
addr peer address
port peer port
Definition at line 93 of file ipv6-end-point.cc.
References m_peerAddr, m_peerPort, and port.
Referenced by ns3::Ipv6EndPointDemux::Allocate(), ns3::TcpSocketBase::Connect(), and ns3::TcpSocketBase::ProcessSynRcvd().
SetRxCallback()
void ns3::Ipv6EndPoint::SetRxCallback (Callback< void, Ptr< Packet >, Ipv6Header, uint16_t, Ptr< Ipv6Interface > > callback)
Set the reception callback.
Parameters
callback callback function
Definition at line 99 of file ipv6-end-point.cc.
References m_rxCallback.
Referenced by ns3::UdpSocketImpl::FinishBind(), and ns3::TcpSocketBase::SetupCallback().
SetRxEnabled()
void ns3::Ipv6EndPoint::SetRxEnabled (bool enabled)
Enable or Disable the endpoint Rx capability.
Parameters
enabled true if Rx is enabled
Definition at line 131 of file ipv6-end-point.cc.
References m_rxEnabled.
Referenced by ns3::UdpSocketImpl::ShutdownRecv().
Member Data Documentation
m_boundnetdevice
Ptr<NetDevice> ns3::Ipv6EndPoint::m_boundnetdevice private
The NetDevice the EndPoint is bound to (if any).
Definition at line 218 of file ipv6-end-point.h.
Referenced by BindToNetDevice(), and GetBoundNetDevice().
m_destroyCallback
Callback<void> ns3::Ipv6EndPoint::m_destroyCallback private
The destroy callback.
Definition at line 233 of file ipv6-end-point.h.
Referenced by ~Ipv6EndPoint(), and SetDestroyCallback().
m_icmpCallback
Callback<void, Ipv6Address, uint8_t, uint8_t, uint8_t, uint32_t> ns3::Ipv6EndPoint::m_icmpCallback private
The ICMPv6 callback.
Definition at line 228 of file ipv6-end-point.h.
Referenced by ~Ipv6EndPoint(), ForwardIcmp(), and SetIcmpCallback().
m_localAddr
Ipv6Address ns3::Ipv6EndPoint::m_localAddr private
The local address.
Definition at line 198 of file ipv6-end-point.h.
Referenced by GetLocalAddress(), and SetLocalAddress().
m_localPort
uint16_t ns3::Ipv6EndPoint::m_localPort private
The local port.
Definition at line 203 of file ipv6-end-point.h.
Referenced by GetLocalPort(), and SetLocalPort().
m_peerAddr
Ipv6Address ns3::Ipv6EndPoint::m_peerAddr private
The peer address.
Definition at line 208 of file ipv6-end-point.h.
Referenced by GetPeerAddress(), and SetPeer().
m_peerPort
uint16_t ns3::Ipv6EndPoint::m_peerPort private
The peer port.
Definition at line 213 of file ipv6-end-point.h.
Referenced by GetPeerPort(), and SetPeer().
m_rxCallback
Callback<void, Ptr<Packet>, Ipv6Header, uint16_t, Ptr<Ipv6Interface> > ns3::Ipv6EndPoint::m_rxCallback private
The RX callback.
Definition at line 223 of file ipv6-end-point.h.
Referenced by ~Ipv6EndPoint(), ForwardUp(), and SetRxCallback().
m_rxEnabled
bool ns3::Ipv6EndPoint::m_rxEnabled private
true if the endpoint can receive packets.
Definition at line 238 of file ipv6-end-point.h.
Referenced by IsRxEnabled(), and SetRxEnabled().
The documentation for this class was generated from the following files:
src/internet/model/ipv6-end-point.h
src/internet/model/ipv6-end-point.cc