ns-3: ns3::PhyRxStatsCalculator Class Reference
ns3::PhyRxStatsCalculator Class Reference
LTE Models
Takes care of storing the information generated at PHY layer regarding reception.
#include "phy-rx-stats-calculator.h"
Public Member Functions
PhyRxStatsCalculator ()
Constructor.
virtual ~PhyRxStatsCalculator ()
Destructor.
void DlPhyReception (PhyReceptionStatParameters params)
Notifies the stats calculator that an downlink reception has occurred.
std::string GetDlRxOutputFilename (void)
Get the name of the file where the DL RX PHY statistics will be stored.
std::string GetUlRxOutputFilename (void)
Get the name of the file where the UL RX PHY statistics will be stored.
void SetDlRxOutputFilename (std::string outputFilename)
Set the name of the file where the DL RX PHY statistics will be stored.
void SetUlRxOutputFilename (std::string outputFilename)
Set the name of the file where the UL Rx PHY statistics will be stored.
void UlPhyReception (PhyReceptionStatParameters params)
Notifies the stats calculator that an uplink reception has occurred.
Public Member Functions inherited from ns3::LteStatsCalculator
LteStatsCalculator ()
Constructor.
virtual ~LteStatsCalculator ()
Destructor.
bool ExistsCellIdPath (std::string path)
Checks if there is an already stored cell id for the given path.
bool ExistsImsiPath (std::string path)
Checks if there is an already stored IMSI for the given path.
uint16_t GetCellIdPath (std::string path)
Retrieves the cell id information for the given path.
std::string GetDlOutputFilename (void)
Get the name of the file where the downlink statistics will be stored.
uint64_t GetImsiPath (std::string path)
Retrieves the imsi information for the given path.
std::string GetUlOutputFilename (void)
Get the name of the file where the uplink statistics will be stored.
void SetCellIdPath (std::string path, uint16_t cellId)
Stores the (path, cellId) pairs in a map.
void SetDlOutputFilename (std::string outputFilename)
Set the name of the file where the downlink statistics will be stored.
void SetImsiPath (std::string path, uint64_t imsi)
Stores the (path, imsi) pairs in a map.
void SetUlOutputFilename (std::string outputFilename)
Set the name of the file where the uplink statistics will be stored.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static void DlPhyReceptionCallback (Ptr< PhyRxStatsCalculator > phyRxStats, std::string path, PhyReceptionStatParameters params)
trace sink
static TypeId GetTypeId (void)
Register this type.
static void UlPhyReceptionCallback (Ptr< PhyRxStatsCalculator > phyRxStats, std::string path, PhyReceptionStatParameters params)
trace sink
Static Public Member Functions inherited from ns3::LteStatsCalculator
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
bool m_dlRxFirstWrite
When writing DL RX PHY statistics first time to file, columns description is added.
bool m_ulRxFirstWrite
When writing UL RX PHY statistics first time to file, columns description is added.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Static Protected Member Functions inherited from ns3::LteStatsCalculator
static uint16_t FindCellIdFromEnbMac (std::string path, uint16_t rnti)
Retrieves CellId from Enb MAC path in the attribute system.
static uint16_t FindCellIdFromEnbRlcPath (std::string path)
Retrieves CellId from Enb RLC path in the attribute system.
static uint64_t FindImsiForEnb (std::string path, uint16_t rnti)
Retrieves IMSI from path for Enb in the attribute system.
static uint64_t FindImsiForUe (std::string path, uint16_t rnti)
Retrieves IMSI from path for Ue in the attribute system.
static uint64_t FindImsiFromEnbMac (std::string path, uint16_t rnti)
Retrieves IMSI from Enb MAC path in the attribute system.
static uint64_t FindImsiFromEnbRlcPath (std::string path)
Retrieves IMSI from Enb RLC path in the attribute system.
static uint64_t FindImsiFromLteNetDevice (std::string path)
Retrieves IMSI from LteNetDevice path in the attribute system.
static uint64_t FindImsiFromUePhy (std::string path)
Retrieves IMSI from Ue PHY path in the attribute system.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Takes care of storing the information generated at PHY layer regarding reception.
Introspection did not find any typical Config paths.
Metrics saved are:
Timestamp (in seconds)
Frame index
Subframe index
C-RNTI
MCS for transport block 1
Size of transport block 1
MCS for transport block 2 (0 if not used)
Size of transport block 2 (0 if not used)
Attributes
DlRxOutputFilename: Name of the file where the downlink results will be saved.
Set with class: StringValue
Underlying type:
Initial value: DlRxPhyStats.txt
Flags: construct write
UlRxOutputFilename: Name of the file where the uplink results will be saved.
Set with class: StringValue
Underlying type:
Initial value: UlRxPhyStats.txt
Flags: construct write
No TraceSources are defined for this type.
Size of this type is 136 bytes (on a 64-bit architecture).
Definition at line 50 of file phy-rx-stats-calculator.h.
Constructor & Destructor Documentation
PhyRxStatsCalculator()
ns3::PhyRxStatsCalculator::PhyRxStatsCalculator ()
Constructor.
Definition at line 34 of file phy-rx-stats-calculator.cc.
References NS_LOG_FUNCTION.
~PhyRxStatsCalculator()
ns3::PhyRxStatsCalculator::~PhyRxStatsCalculator () virtual
Destructor.
Definition at line 42 of file phy-rx-stats-calculator.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DlPhyReception()
void ns3::PhyRxStatsCalculator::DlPhyReception (PhyReceptionStatParameters params)
Notifies the stats calculator that an downlink reception has occurred.
Parameters
params Trace information regarding PHY reception stats
Definition at line 93 of file phy-rx-stats-calculator.cc.
References GetDlRxOutputFilename(), ns3::PhyReceptionStatParameters::m_ccId, ns3::PhyReceptionStatParameters::m_cellId, ns3::PhyReceptionStatParameters::m_correctness, m_dlRxFirstWrite, ns3::PhyReceptionStatParameters::m_imsi, ns3::PhyReceptionStatParameters::m_layer, ns3::PhyReceptionStatParameters::m_mcs, ns3::PhyReceptionStatParameters::m_ndi, ns3::PhyReceptionStatParameters::m_rnti, ns3::PhyReceptionStatParameters::m_rv, ns3::PhyReceptionStatParameters::m_size, ns3::PhyReceptionStatParameters::m_timestamp, ns3::PhyReceptionStatParameters::m_txMode, NS_LOG_ERROR, NS_LOG_FUNCTION, and NS_LOG_INFO.
DlPhyReceptionCallback()
void ns3::PhyRxStatsCalculator::DlPhyReceptionCallback (Ptr< PhyRxStatsCalculator > phyRxStats, std::string path, PhyReceptionStatParameters params) static
trace sink
Parameters
phyRxStats
path
params
Definition at line 180 of file phy-rx-stats-calculator.cc.
References ns3::LteStatsCalculator::FindImsiFromLteNetDevice(), ns3::PhyReceptionStatParameters::m_imsi, ns3::PhyReceptionStatParameters::m_rnti, and NS_LOG_FUNCTION.
Referenced by ns3::LteHelper::EnableDlRxPhyTraces().
GetDlRxOutputFilename()
std::string ns3::PhyRxStatsCalculator::GetDlRxOutputFilename (void)
Get the name of the file where the DL RX PHY statistics will be stored.
Returns
the name of the file where the DL RX PHY statistics will be stored
Definition at line 87 of file phy-rx-stats-calculator.cc.
References ns3::LteStatsCalculator::GetDlOutputFilename().
Referenced by DlPhyReception().
GetTypeId()
TypeId ns3::PhyRxStatsCalculator::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 48 of file phy-rx-stats-calculator.cc.
References ns3::MakeStringAccessor(), ns3::MakeStringChecker(), SetDlRxOutputFilename(), ns3::TypeId::SetParent(), and SetUlRxOutputFilename().
GetUlRxOutputFilename()
std::string ns3::PhyRxStatsCalculator::GetUlRxOutputFilename (void)
Get the name of the file where the UL RX PHY statistics will be stored.
Returns
the name of the file where the UL RX PHY statistics will be stored
Definition at line 75 of file phy-rx-stats-calculator.cc.
References ns3::LteStatsCalculator::GetUlOutputFilename().
Referenced by UlPhyReception().
SetDlRxOutputFilename()
void ns3::PhyRxStatsCalculator::SetDlRxOutputFilename (std::string outputFilename)
Set the name of the file where the DL RX PHY statistics will be stored.
Parameters
outputFilename string with the name of the file
Definition at line 81 of file phy-rx-stats-calculator.cc.
References ns3::LteStatsCalculator::SetDlOutputFilename().
Referenced by GetTypeId().
SetUlRxOutputFilename()
void ns3::PhyRxStatsCalculator::SetUlRxOutputFilename (std::string outputFilename)
Set the name of the file where the UL Rx PHY statistics will be stored.
Parameters
outputFilename string with the name of the file
Definition at line 69 of file phy-rx-stats-calculator.cc.
References ns3::LteStatsCalculator::SetUlOutputFilename().
Referenced by GetTypeId().
UlPhyReception()
void ns3::PhyRxStatsCalculator::UlPhyReception (PhyReceptionStatParameters params)
Notifies the stats calculator that an uplink reception has occurred.
Parameters
params Trace information regarding PHY reception stats
Definition at line 137 of file phy-rx-stats-calculator.cc.
References GetUlRxOutputFilename(), ns3::PhyReceptionStatParameters::m_ccId, ns3::PhyReceptionStatParameters::m_cellId, ns3::PhyReceptionStatParameters::m_correctness, ns3::PhyReceptionStatParameters::m_imsi, ns3::PhyReceptionStatParameters::m_layer, ns3::PhyReceptionStatParameters::m_mcs, ns3::PhyReceptionStatParameters::m_ndi, ns3::PhyReceptionStatParameters::m_rnti, ns3::PhyReceptionStatParameters::m_rv, ns3::PhyReceptionStatParameters::m_size, ns3::PhyReceptionStatParameters::m_timestamp, m_ulRxFirstWrite, NS_LOG_ERROR, NS_LOG_FUNCTION, and NS_LOG_INFO.
UlPhyReceptionCallback()
void ns3::PhyRxStatsCalculator::UlPhyReceptionCallback (Ptr< PhyRxStatsCalculator > phyRxStats, std::string path, PhyReceptionStatParameters params) static
trace sink
Parameters
phyRxStats
path
params
Definition at line 203 of file phy-rx-stats-calculator.cc.
References ns3::LteStatsCalculator::FindImsiFromEnbRlcPath(), ns3::PhyReceptionStatParameters::m_imsi, ns3::PhyReceptionStatParameters::m_rnti, and NS_LOG_FUNCTION.
Referenced by ns3::LteHelper::EnableUlRxPhyTraces().
Member Data Documentation
m_dlRxFirstWrite
bool ns3::PhyRxStatsCalculator::m_dlRxFirstWrite private
When writing DL RX PHY statistics first time to file, columns description is added.
Then next lines are appended to file. This value is true if output files have not been opened yet
Definition at line 135 of file phy-rx-stats-calculator.h.
Referenced by DlPhyReception().
m_ulRxFirstWrite
bool ns3::PhyRxStatsCalculator::m_ulRxFirstWrite private
When writing UL RX PHY statistics first time to file, columns description is added.
Then next lines are appended to file. This value is true if output files have not been opened yet
Definition at line 143 of file phy-rx-stats-calculator.h.
Referenced by UlPhyReception().
The documentation for this class was generated from the following files:
src/lte/helper/phy-rx-stats-calculator.h
src/lte/helper/phy-rx-stats-calculator.cc