ns-3: ns3::TableBasedErrorRateModel Class Reference
ns3::TableBasedErrorRateModel Class Reference
Introspection did not find any typical Config paths.
#include "table-based-error-rate-model.h"
Public Member Functions
TableBasedErrorRateModel ()
~TableBasedErrorRateModel ()
double DoGetChunkSuccessRate (WifiMode mode, WifiTxVector txVector, double snr, uint64_t nbits) const
A pure virtual method that must be implemented in the subclass.
Public Member Functions inherited from ns3::ErrorRateModel
double CalculateSnr (WifiTxVector txVector, double ber) const
double GetChunkSuccessRate (WifiMode mode, WifiTxVector txVector, double snr, uint64_t nbits) const
This method returns the probability that the given 'chunk' of the packet will be successfully received by the PHY.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static uint8_t GetMcsForMode (WifiMode mode)
Utility function to convert WifiMode to an MCS value.
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ErrorRateModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
double FetchFsr (WifiMode mode, WifiTxVector txVector, double snr, uint64_t nbits) const
Fetch the frame success rate for a given Wi-Fi mode, TXVECTOR, SNR and frame size.
double RoundSnr (double snr, double precision) const
Round SNR (in dB) to the specified precision.
Private Attributes
Ptr< ErrorRateModel > m_fallbackErrorModel
Error rate model to fallback to if no value is found in the table.
uint64_t m_threshold
Threshold in bytes over which the table for large size frames is used.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Introspection did not find any typical Config paths.
Attributes
FallbackErrorRateModel: Ptr to the fallback error rate model to be used when no matching value is found in a table
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::ErrorRateModel>
Initial value: 0x7fee2bd08ce0
Flags: construct write read
SizeThreshold: Threshold in bytes over which the table for large size frames is used
Set with class: ns3::UintegerValue
Underlying type: uint64_t 0:18446744073709551615
Initial value: 400
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 48 bytes (on a 64-bit architecture).
Definition at line 38 of file table-based-error-rate-model.h.
Constructor & Destructor Documentation
TableBasedErrorRateModel()
ns3::TableBasedErrorRateModel::TableBasedErrorRateModel ()
Definition at line 63 of file table-based-error-rate-model.cc.
References NS_LOG_FUNCTION.
~TableBasedErrorRateModel()
ns3::TableBasedErrorRateModel::~TableBasedErrorRateModel ()
Definition at line 68 of file table-based-error-rate-model.cc.
References m_fallbackErrorModel, and NS_LOG_FUNCTION.
Member Function Documentation
DoGetChunkSuccessRate()
double ns3::TableBasedErrorRateModel::DoGetChunkSuccessRate (WifiMode mode, WifiTxVector txVector, double snr, uint64_t nbits) const virtual
A pure virtual method that must be implemented in the subclass.
Parameters
mode the Wi-Fi mode applicable to this chunk
txVector TXVECTOR of the overall transmission
snr the SNR of the chunk
nbits the number of bits in this chunk
Returns
probability of successfully receiving the chunk
Implements ns3::ErrorRateModel.
Definition at line 143 of file table-based-error-rate-model.cc.
References ns3::AwgnErrorTableBcc1458, ns3::AwgnErrorTableBcc32, ns3::AwgnErrorTableLdpc1458, ns3::ERROR_TABLE_BCC_LARGE_FRAME_SIZE, ns3::ERROR_TABLE_BCC_MAX_NUM_MCS, ns3::ERROR_TABLE_BCC_SMALL_FRAME_SIZE, ns3::ERROR_TABLE_LDPC_FRAME_SIZE, ns3::ERROR_TABLE_LDPC_MAX_NUM_MCS, GetMcsForMode(), ns3::WifiMode::GetModulationClass(), ns3::WifiTxVector::IsLdpc(), m_fallbackErrorModel, m_threshold, NS_LOG_FUNCTION, NS_LOG_WARN, ns3::RatioToDb(), RoundSnr(), SNR_PRECISION, and ns3::WIFI_MOD_CLASS_HT.
FetchFsr()
double ns3::TableBasedErrorRateModel::FetchFsr (WifiMode mode, WifiTxVector txVector, double snr, uint64_t nbits) const private
Fetch the frame success rate for a given Wi-Fi mode, TXVECTOR, SNR and frame size.
Parameters
mode the Wi-Fi mode
txVector the TXVECTOR
snr the SNR (linear scale)
nbits the number of bits
Returns
the frame success rate for a given Wi-Fi mode, TXVECTOR, SNR and frame size
GetMcsForMode()
uint8_t ns3::TableBasedErrorRateModel::GetMcsForMode (WifiMode mode) static
Utility function to convert WifiMode to an MCS value.
Parameters
mode the WifiMode
Returns
the MCS value
Definition at line 84 of file table-based-error-rate-model.cc.
References ns3::WifiMode::GetCodeRate(), ns3::WifiMode::GetConstellationSize(), ns3::WifiMode::GetMcsValue(), ns3::WifiMode::GetModulationClass(), NS_ABORT_MSG_IF, ns3::WIFI_CODE_RATE_1_2, ns3::WIFI_CODE_RATE_2_3, ns3::WIFI_CODE_RATE_3_4, ns3::WIFI_MOD_CLASS_ERP_OFDM, ns3::WIFI_MOD_CLASS_HE, ns3::WIFI_MOD_CLASS_HT, ns3::WIFI_MOD_CLASS_OFDM, and ns3::WIFI_MOD_CLASS_VHT.
Referenced by DoGetChunkSuccessRate().
GetTypeId()
TypeId ns3::TableBasedErrorRateModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 43 of file table-based-error-rate-model.cc.
References m_fallbackErrorModel, m_threshold, ns3::MakePointerAccessor(), ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
RoundSnr()
double ns3::TableBasedErrorRateModel::RoundSnr (double snr, double precision) const private
Round SNR (in dB) to the specified precision.
Parameters
snr the SNR to round (in dB)
precision the precision to use
Returns
the rounded SNR (in dB) to the specified precision
Definition at line 76 of file table-based-error-rate-model.cc.
References NS_LOG_FUNCTION.
Referenced by DoGetChunkSuccessRate().
Member Data Documentation
m_fallbackErrorModel
Ptr<ErrorRateModel> ns3::TableBasedErrorRateModel::m_fallbackErrorModel private
Error rate model to fallback to if no value is found in the table.
Definition at line 81 of file table-based-error-rate-model.h.
Referenced by ~TableBasedErrorRateModel(), DoGetChunkSuccessRate(), and GetTypeId().
m_threshold
uint64_t ns3::TableBasedErrorRateModel::m_threshold private
Threshold in bytes over which the table for large size frames is used.
Definition at line 83 of file table-based-error-rate-model.h.
Referenced by DoGetChunkSuccessRate(), and GetTypeId().
The documentation for this class was generated from the following files:
src/wifi/model/table-based-error-rate-model.h
src/wifi/model/table-based-error-rate-model.cc