ns-3: ns3::UanMacCw Class Reference
ns3::UanMacCw Class Reference
UAN Models
CW-MAC protocol, similar in idea to the 802.11 DCF with constant backoff window.
#include "uan-mac-cw.h"
Public Types
typedef void(* QueueTracedCallback) (Ptr< const Packet > packet, uint16_t proto)
TracedCallback signature for enqueue/dequeue of a packet.
Public Types inherited from ns3::UanMac
typedef void(* PacketModeTracedCallback) (Ptr< const Packet > packet, UanTxMode mode)
TracedCallback signature for packet reception/enqueue/dequeue events.
Public Member Functions
UanMacCw ()
Default constructor.
virtual ~UanMacCw ()
Dummy destructor, DoDispose.
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
virtual void AttachPhy (Ptr< UanPhy > phy)
Attach PHY layer to this MAC.
virtual void Clear (void)
Clears all pointer references.
virtual bool Enqueue (Ptr< Packet > pkt, uint16_t protocolNumber, const Address &dest)
Enqueue packet to be transmitted.
virtual uint32_t GetCw (void)
Get the contention window size.
virtual Time GetSlotTime (void)
Get the slot time duration.
virtual void NotifyCcaEnd (void)
Called when UanPhy stops sensing channel is busy.
virtual void NotifyCcaStart (void)
Called when UanPhy begins sensing channel is busy.
virtual void NotifyRxEndError (void)
Called when UanPhy finishes receiving packet in error.
virtual void NotifyRxEndOk (void)
Called when UanPhy finishes receiving packet without error.
virtual void NotifyRxStart (void)
Called when UanPhy begins receiving packet.
virtual void NotifyTxStart (Time duration)
Called when transmission starts from Phy object.
virtual void SetCw (uint32_t cw)
Set the contention window size.
virtual void SetForwardUpCb (Callback< void, Ptr< Packet >, uint16_t, const Mac8Address & > cb)
Set the callback to forward packets up to higher layers.
virtual void SetSlotTime (Time duration)
Set the slot time duration.
Public Member Functions inherited from ns3::UanMac
UanMac ()
Default constructor.
virtual Address GetAddress (void)
Get the MAC Address.
virtual Address GetBroadcast (void) const
Get the broadcast address.
uint32_t GetTxModeIndex ()
virtual void SetAddress (Mac8Address addr)
Set the address.
void SetTxModeIndex (uint32_t txModeIndex)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Public Member Functions inherited from ns3::UanPhyListener
virtual ~UanPhyListener ()
Default destructor.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::UanMac
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose ()
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
enum State { IDLE , CCABUSY , RUNNING , TX }
Enum defining possible Phy states.
Private Member Functions
void EndTx (void)
End TX state.
void PhyRxPacketError (Ptr< Packet > packet, double sinr)
Packet received at lower layer in error.
void PhyRxPacketGood (Ptr< Packet > packet, double sinr, UanTxMode mode)
Receive packet from lower layer (passed to PHY as callback).
void SaveTimer (void)
Cancel SendEvent and save remaining delay.
void SendPacket (void)
Send packet on PHY.
void StartTimer (void)
Schedule SendPacket after delay.
Private Attributes
bool m_cleared
Flag when we've been cleared.
uint32_t m_cw
Contention window size.
TracedCallback< Ptr< const Packet >, uint16_t > m_dequeueLogger
A packet was passed down to the PHY from the MAC.
TracedCallback< Ptr< const Packet >, uint16_t > m_enqueueLogger
A packet arrived at the MAC for transmission.
Callback< void, Ptr< Packet >, uint16_t, const Mac8Address & > m_forwardUpCb
Forwarding up callback.
Ptr< UanPhy > m_phy
PHY layer attached to this MAC.
Ptr< Packet > m_pktTx
Next packet to send.
uint16_t m_pktTxProt
Next packet protocol number (usage varies by MAC).
Ptr< UniformRandomVariable > m_rv
Provides uniform random variable for contention window.
TracedCallback< Ptr< const Packet >, UanTxMode > m_rxLogger
A packet destined for this MAC was received.
Time m_savedDelayS
Remaining delay until next send.
EventId m_sendEvent
Scheduled SendPacket event.
Time m_sendTime
Time to send next packet.
Time m_slotTime
Slot time duration.
State m_state
Current state.
EventId m_txEndEvent
Scheduled EndTx event.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
CW-MAC protocol, similar in idea to the 802.11 DCF with constant backoff window.
For more information on this MAC protocol, see: Parrish, N.; Tracy, L.; Roy, S.; Arabshahi, P.; Fox, W., "System Design Considerations for Undersea Networks: Link and Multiple Access Protocols," Selected Areas in Communications, IEEE Journal on , vol.26, no.9, pp.1720-1730, December 2008
Config Paths
ns3::UanMacCw is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::UanNetDevice/Mac/$ns3::UanMacCw"
Attributes
CW: The MAC parameter CW.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 10
Flags: construct write read
SlotTime: Time slot duration for MAC backoff.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +2e+07ns
Flags: construct write read
TraceSources
Enqueue: A packet arrived at the MAC for transmission.
Callback signature: ns3::UanMacCw::QueueTracedCallback
Dequeue: A was passed down to the PHY from the MAC.
Callback signature: ns3::UanMacCw::QueueTracedCallback
RX: A packet was destined for this MAC and was received.
Callback signature: ns3::UanMac::PacketModeTracedCallback
Size of this type is 256 bytes (on a 64-bit architecture).
Definition at line 46 of file uan-mac-cw.h.
Member Typedef Documentation
QueueTracedCallback
typedef void(* ns3::UanMacCw::QueueTracedCallback) (Ptr< const Packet > packet, uint16_t proto)
TracedCallback signature for enqueue/dequeue of a packet.
Parameters
[in] packet The Packet being received.
[in] proto The protocol number.
Definition at line 106 of file uan-mac-cw.h.
Member Enumeration Documentation
State
enum ns3::UanMacCw::State private
Enum defining possible Phy states.
Enumerator
IDLE
Idle state.
CCABUSY
Channel busy.
RUNNING
Delay timer running.
TX
Transmitting.
Definition at line 111 of file uan-mac-cw.h.
Constructor & Destructor Documentation
UanMacCw()
ns3::UanMacCw::UanMacCw ()
Default constructor.
Definition at line 36 of file uan-mac-cw.cc.
References m_rv.
~UanMacCw()
ns3::UanMacCw::~UanMacCw () virtual
Dummy destructor, DoDispose.
Definition at line 47 of file uan-mac-cw.cc.
Member Function Documentation
AssignStreams()
int64_t ns3::UanMacCw::AssignStreams (int64_t stream) virtual
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream First stream index to use.
Returns
The number of stream indices assigned by this model.
Implements ns3::UanMac.
Definition at line 276 of file uan-mac-cw.cc.
References m_rv, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
AttachPhy()
void ns3::UanMacCw::AttachPhy (Ptr< UanPhy > phy) virtual
Attach PHY layer to this MAC.
Some MACs may be designed to work with multiple PHY layers. Others may only work with one.
Parameters
phy Phy layer to attach to this MAC.
Implements ns3::UanMac.
Definition at line 186 of file uan-mac-cw.cc.
References m_phy, ns3::MakeCallback(), third::phy, PhyRxPacketError(), and PhyRxPacketGood().
Clear()
void ns3::UanMacCw::Clear (void) virtual
Clears all pointer references.
Implements ns3::UanMac.
Definition at line 52 of file uan-mac-cw.cc.
References ns3::EventId::Cancel(), m_cleared, m_phy, m_pktTx, m_sendEvent, and m_txEndEvent.
Referenced by DoDispose().
DoDispose()
void ns3::UanMacCw::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 70 of file uan-mac-cw.cc.
References Clear(), and ns3::Object::DoDispose().
EndTx()
void ns3::UanMacCw::EndTx (void) private
End TX state.
Definition at line 284 of file uan-mac-cw.cc.
References CCABUSY, ns3::UanMac::GetAddress(), IDLE, m_phy, m_state, ns3::Now(), NS_ASSERT, NS_FATAL_ERROR, NS_LOG_DEBUG, RUNNING, ns3::Time::S, StartTimer(), and TX.
Referenced by NotifyTxStart().
Enqueue()
bool ns3::UanMacCw::Enqueue (Ptr< Packet > pkt, uint16_t protocolNumber, const Address & dest) virtual
Enqueue packet to be transmitted.
Parameters
pkt Packet to be transmitted.
dest Destination address.
protocolNumber The type of the packet.
Returns
True if packet was successfully enqueued.
Implements ns3::UanMac.
Definition at line 111 of file uan-mac-cw.cc.
References ns3::Packet::AddHeader(), ns3::Time::As(), CCABUSY, ns3::Mac8Address::ConvertFrom(), ns3::UanMac::GetAddress(), ns3::Packet::GetSize(), ns3::UanMac::GetTxModeIndex(), ns3::UniformRandomVariable::GetValue(), IDLE, ns3::EventId::IsRunning(), m_cw, m_enqueueLogger, m_phy, m_pktTx, m_pktTxProt, m_rv, m_savedDelayS, m_sendTime, m_slotTime, m_state, m_txEndEvent, ns3::Now(), ns3::Simulator::Now(), NS_ASSERT, NS_LOG_DEBUG, RUNNING, ns3::Time::S, ns3::UanHeaderCommon::SetDest(), ns3::UanHeaderCommon::SetProtocolNumber(), ns3::UanHeaderCommon::SetSrc(), ns3::UanHeaderCommon::SetType(), and TX.
GetCw()
uint32_t ns3::UanMacCw::GetCw (void) virtual
Get the contention window size.
Returns
Contention window size.
Definition at line 316 of file uan-mac-cw.cc.
References m_cw.
GetSlotTime()
Time ns3::UanMacCw::GetSlotTime (void) virtual
Get the slot time duration.
Returns
Slot time duration.
Definition at line 321 of file uan-mac-cw.cc.
References m_slotTime.
GetTypeId()
TypeId ns3::UanMacCw::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 77 of file uan-mac-cw.cc.
References m_cw, m_dequeueLogger, m_enqueueLogger, m_rxLogger, m_slotTime, ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), ns3::MilliSeconds(), and ns3::TypeId::SetParent().
NotifyCcaEnd()
void ns3::UanMacCw::NotifyCcaEnd (void) virtual
Called when UanPhy stops sensing channel is busy.
Implements ns3::UanPhyListener.
Definition at line 243 of file uan-mac-cw.cc.
References CCABUSY, ns3::UanMac::GetAddress(), m_state, ns3::Now(), NS_LOG_DEBUG, RUNNING, ns3::Time::S, and StartTimer().
NotifyCcaStart()
void ns3::UanMacCw::NotifyCcaStart (void) virtual
Called when UanPhy begins sensing channel is busy.
Implements ns3::UanPhyListener.
Definition at line 231 of file uan-mac-cw.cc.
References CCABUSY, ns3::UanMac::GetAddress(), m_state, ns3::Now(), NS_LOG_DEBUG, RUNNING, ns3::Time::S, and SaveTimer().
NotifyRxEndError()
void ns3::UanMacCw::NotifyRxEndError (void) virtual
Called when UanPhy finishes receiving packet in error.
Implements ns3::UanPhyListener.
Definition at line 219 of file uan-mac-cw.cc.
References CCABUSY, ns3::UanMac::GetAddress(), m_phy, m_state, ns3::Now(), NS_LOG_DEBUG, RUNNING, ns3::Time::S, and StartTimer().
NotifyRxEndOk()
void ns3::UanMacCw::NotifyRxEndOk (void) virtual
Called when UanPhy finishes receiving packet without error.
Implements ns3::UanPhyListener.
Definition at line 207 of file uan-mac-cw.cc.
References CCABUSY, ns3::UanMac::GetAddress(), m_phy, m_state, ns3::Now(), NS_LOG_DEBUG, RUNNING, ns3::Time::S, and StartTimer().
NotifyRxStart()
void ns3::UanMacCw::NotifyRxStart (void) virtual
Called when UanPhy begins receiving packet.
Implements ns3::UanPhyListener.
Definition at line 195 of file uan-mac-cw.cc.
References CCABUSY, ns3::UanMac::GetAddress(), m_state, ns3::Now(), NS_LOG_DEBUG, RUNNING, ns3::Time::S, and SaveTimer().
NotifyTxStart()
void ns3::UanMacCw::NotifyTxStart (Time duration) virtual
Called when transmission starts from Phy object.
Parameters
duration Duration of transmission.
Implements ns3::UanPhyListener.
Definition at line 255 of file uan-mac-cw.cc.
References ns3::Time::As(), ns3::Simulator::Cancel(), CCABUSY, EndTx(), ns3::EventId::IsRunning(), m_state, m_txEndEvent, ns3::Now(), NS_ASSERT, NS_LOG_DEBUG, RUNNING, ns3::Time::S, SaveTimer(), and ns3::Simulator::Schedule().
PhyRxPacketError()
void ns3::UanMacCw::PhyRxPacketError (Ptr< Packet > packet, double sinr) private
Packet received at lower layer in error.
Parameters
packet Packet received in error.
sinr SINR of received packet.
Definition at line 338 of file uan-mac-cw.cc.
References NS_UNUSED.
Referenced by AttachPhy().
PhyRxPacketGood()
void ns3::UanMacCw::PhyRxPacketGood (Ptr< Packet > packet, double sinr, UanTxMode mode) private
Receive packet from lower layer (passed to PHY as callback).
Parameters
packet Packet being received.
sinr SINR of received packet.
mode Mode of received packet.
Definition at line 326 of file uan-mac-cw.cc.
References ns3::Mac8Address::ConvertFrom(), ns3::UanMac::GetAddress(), ns3::Mac8Address::GetBroadcast(), ns3::UanHeaderCommon::GetDest(), ns3::UanHeaderCommon::GetProtocolNumber(), ns3::UanHeaderCommon::GetSrc(), m_forwardUpCb, NS_UNUSED, and ns3::Packet::RemoveHeader().
Referenced by AttachPhy().
SaveTimer()
void ns3::UanMacCw::SaveTimer (void) private
Cancel SendEvent and save remaining delay.
Definition at line 343 of file uan-mac-cw.cc.
References ns3::Simulator::Cancel(), ns3::UanMac::GetAddress(), m_pktTx, m_savedDelayS, m_sendEvent, m_sendTime, ns3::Now(), ns3::Simulator::Now(), NS_ASSERT, NS_LOG_DEBUG, and ns3::Time::S.
Referenced by NotifyCcaStart(), NotifyRxStart(), and NotifyTxStart().
SendPacket()
void ns3::UanMacCw::SendPacket (void) private
Send packet on PHY.
Definition at line 370 of file uan-mac-cw.cc.
References ns3::UanMac::GetAddress(), m_phy, m_pktTx, m_pktTxProt, m_savedDelayS, m_sendTime, m_state, ns3::Now(), NS_ASSERT, NS_LOG_DEBUG, RUNNING, ns3::Time::S, ns3::Seconds(), and TX.
Referenced by StartTimer().
SetCw()
void ns3::UanMacCw::SetCw (uint32_t cw) virtual
Set the contention window size.
Parameters
cw Contention window size.
Definition at line 306 of file uan-mac-cw.cc.
References m_cw.
SetForwardUpCb()
void ns3::UanMacCw::SetForwardUpCb (Callback< void, Ptr< Packet >, uint16_t, const Mac8Address & > cb) virtual
Set the callback to forward packets up to higher layers.
Parameters
cb The callback. packet The packet. address The source address.
Implements ns3::UanMac.
Definition at line 180 of file uan-mac-cw.cc.
References m_forwardUpCb.
SetSlotTime()
void ns3::UanMacCw::SetSlotTime (Time duration) virtual
Set the slot time duration.
Parameters
duration Slot time duration.
Definition at line 311 of file uan-mac-cw.cc.
References m_slotTime.
StartTimer()
void ns3::UanMacCw::StartTimer (void) private
Schedule SendPacket after delay.
Definition at line 354 of file uan-mac-cw.cc.
References ns3::Time::As(), ns3::UanMac::GetAddress(), m_savedDelayS, m_sendEvent, m_sendTime, ns3::Now(), ns3::Simulator::Now(), NS_LOG_DEBUG, ns3::Time::S, ns3::Simulator::Schedule(), and SendPacket().
Referenced by EndTx(), NotifyCcaEnd(), NotifyRxEndError(), and NotifyRxEndOk().
Member Data Documentation
m_cleared
bool ns3::UanMacCw::m_cleared private
Flag when we've been cleared.
Definition at line 150 of file uan-mac-cw.h.
Referenced by Clear().
m_cw
uint32_t ns3::UanMacCw::m_cw private
Contention window size.
Definition at line 130 of file uan-mac-cw.h.
Referenced by Enqueue(), GetCw(), GetTypeId(), and SetCw().
m_dequeueLogger
TracedCallback<Ptr<const Packet>, uint16_t > ns3::UanMacCw::m_dequeueLogger private
A packet was passed down to the PHY from the MAC.
Definition at line 127 of file uan-mac-cw.h.
Referenced by GetTypeId().
m_enqueueLogger
TracedCallback<Ptr<const Packet>, uint16_t > ns3::UanMacCw::m_enqueueLogger private
A packet arrived at the MAC for transmission.
Definition at line 125 of file uan-mac-cw.h.
Referenced by Enqueue(), and GetTypeId().
m_forwardUpCb
Callback<void, Ptr<Packet>, uint16_t, const Mac8Address&> ns3::UanMacCw::m_forwardUpCb private
Forwarding up callback.
Definition at line 119 of file uan-mac-cw.h.
Referenced by PhyRxPacketGood(), and SetForwardUpCb().
m_phy
Ptr<UanPhy> ns3::UanMacCw::m_phy private
PHY layer attached to this MAC.
Definition at line 121 of file uan-mac-cw.h.
Referenced by AttachPhy(), Clear(), EndTx(), Enqueue(), NotifyRxEndError(), NotifyRxEndOk(), and SendPacket().
m_pktTx
Ptr<Packet> ns3::UanMacCw::m_pktTx private
Next packet to send.
Definition at line 139 of file uan-mac-cw.h.
Referenced by Clear(), Enqueue(), SaveTimer(), and SendPacket().
m_pktTxProt
uint16_t ns3::UanMacCw::m_pktTxProt private
Next packet protocol number (usage varies by MAC).
Definition at line 141 of file uan-mac-cw.h.
Referenced by Enqueue(), and SendPacket().
m_rv
Ptr<UniformRandomVariable> ns3::UanMacCw::m_rv private
Provides uniform random variable for contention window.
Definition at line 153 of file uan-mac-cw.h.
Referenced by UanMacCw(), AssignStreams(), and Enqueue().
m_rxLogger
TracedCallback<Ptr<const Packet>, UanTxMode > ns3::UanMacCw::m_rxLogger private
A packet destined for this MAC was received.
Definition at line 123 of file uan-mac-cw.h.
Referenced by GetTypeId().
m_savedDelayS
Time ns3::UanMacCw::m_savedDelayS private
Remaining delay until next send.
Definition at line 137 of file uan-mac-cw.h.
Referenced by Enqueue(), SaveTimer(), SendPacket(), and StartTimer().
m_sendEvent
EventId ns3::UanMacCw::m_sendEvent private
Scheduled SendPacket event.
Definition at line 143 of file uan-mac-cw.h.
Referenced by Clear(), SaveTimer(), and StartTimer().
m_sendTime
Time ns3::UanMacCw::m_sendTime private
Time to send next packet.
Definition at line 135 of file uan-mac-cw.h.
Referenced by Enqueue(), SaveTimer(), SendPacket(), and StartTimer().
m_slotTime
Time ns3::UanMacCw::m_slotTime private
Slot time duration.
Definition at line 131 of file uan-mac-cw.h.
Referenced by Enqueue(), GetSlotTime(), GetTypeId(), and SetSlotTime().
m_state
State ns3::UanMacCw::m_state private
Current state.
Definition at line 147 of file uan-mac-cw.h.
Referenced by EndTx(), Enqueue(), NotifyCcaEnd(), NotifyCcaStart(), NotifyRxEndError(), NotifyRxEndOk(), NotifyRxStart(), NotifyTxStart(), and SendPacket().
m_txEndEvent
EventId ns3::UanMacCw::m_txEndEvent private
Scheduled EndTx event.
Definition at line 145 of file uan-mac-cw.h.
Referenced by Clear(), Enqueue(), and NotifyTxStart().
The documentation for this class was generated from the following files:
src/uan/model/uan-mac-cw.h
src/uan/model/uan-mac-cw.cc