ns-3: TcpRateLinuxBasicTest Class Reference
TcpRateLinuxBasicTest Class Reference
Test suites
The TcpRateLinux Basic Test.
Public Member Functions
TcpRateLinuxBasicTest (uint32_t cWnd, SequenceNumber32 tailSeq, SequenceNumber32 nextTx, uint32_t lostOut, uint32_t retransOut, uint32_t testCase, std::string testName)
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void SendSkb (TcpTxItem *skb)
void SkbDelivered (TcpTxItem *skb)
Private Attributes
uint32_t m_cWnd
uint32_t m_delivered
Time m_deliveredTime
uint32_t m_inFlight
SequenceNumber32 m_nextTx
TcpRateLinux m_rateOps
uint32_t m_segmentSize
std::vector< TcpTxItem * > m_skbs
SequenceNumber32 m_tailSeq
uint32_t m_testCase
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
The TcpRateLinux Basic Test.
Definition at line 44 of file tcp-rate-ops-test.cc.
Constructor & Destructor Documentation
TcpRateLinuxBasicTest()
TcpRateLinuxBasicTest::TcpRateLinuxBasicTest (uint32_t cWnd, SequenceNumber32 tailSeq, SequenceNumber32 nextTx, uint32_t lostOut, uint32_t retransOut, uint32_t testCase, std::string testName)
Definition at line 69 of file tcp-rate-ops-test.cc.
Member Function Documentation
DoRun()
void TcpRateLinuxBasicTest::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 85 of file tcp-rate-ops-test.cc.
References m_skbs, ns3::Seconds(), SendSkb(), and SkbDelivered().
SendSkb()
void TcpRateLinuxBasicTest::SendSkb (TcpTxItem * skb) private
Definition at line 108 of file tcp-rate-ops-test.cc.
References ns3::TcpRateLinux::CalculateAppLimited(), ns3::TcpTxItem::GetRateInformation(), ns3::TcpTxItem::GetSeqSize(), m_cWnd, ns3::TcpTxItem::RateInformation::m_delivered, m_delivered, ns3::TcpTxItem::RateInformation::m_deliveredTime, m_deliveredTime, m_inFlight, m_nextTx, m_rateOps, m_segmentSize, m_tailSeq, ns3::Now(), NS_TEST_ASSERT_MSG_EQ, and ns3::TcpRateLinux::SkbSent().
Referenced by DoRun().
SkbDelivered()
void TcpRateLinuxBasicTest::SkbDelivered (TcpTxItem * skb) private
Definition at line 128 of file tcp-rate-ops-test.cc.
References ns3::TcpTxItem::GetRateInformation(), ns3::TcpTxItem::GetSeqSize(), m_delivered, ns3::TcpTxItem::RateInformation::m_deliveredTime, m_deliveredTime, m_inFlight, ns3::TcpTxItem::RateInformation::m_isAppLimited, m_rateOps, m_testCase, Max, ns3::Now(), NS_TEST_ASSERT_MSG_EQ, and ns3::TcpRateLinux::SkbDelivered().
Referenced by DoRun().
Member Data Documentation
m_cWnd
uint32_t TcpRateLinuxBasicTest::m_cWnd private
Definition at line 58 of file tcp-rate-ops-test.cc.
Referenced by SendSkb().
m_delivered
uint32_t TcpRateLinuxBasicTest::m_delivered private
Definition at line 61 of file tcp-rate-ops-test.cc.
Referenced by SendSkb(), and SkbDelivered().
m_deliveredTime
Time TcpRateLinuxBasicTest::m_deliveredTime private
Definition at line 62 of file tcp-rate-ops-test.cc.
Referenced by SendSkb(), and SkbDelivered().
m_inFlight
uint32_t TcpRateLinuxBasicTest::m_inFlight private
Definition at line 59 of file tcp-rate-ops-test.cc.
Referenced by SendSkb(), and SkbDelivered().
m_nextTx
SequenceNumber32 TcpRateLinuxBasicTest::m_nextTx private
Definition at line 64 of file tcp-rate-ops-test.cc.
Referenced by SendSkb().
m_rateOps
TcpRateLinux TcpRateLinuxBasicTest::m_rateOps private
Definition at line 57 of file tcp-rate-ops-test.cc.
Referenced by SendSkb(), and SkbDelivered().
m_segmentSize
uint32_t TcpRateLinuxBasicTest::m_segmentSize private
Definition at line 60 of file tcp-rate-ops-test.cc.
Referenced by SendSkb().
m_skbs
std::vector<TcpTxItem *> TcpRateLinuxBasicTest::m_skbs private
Definition at line 66 of file tcp-rate-ops-test.cc.
Referenced by DoRun().
m_tailSeq
SequenceNumber32 TcpRateLinuxBasicTest::m_tailSeq private
Definition at line 63 of file tcp-rate-ops-test.cc.
Referenced by SendSkb().
m_testCase
uint32_t TcpRateLinuxBasicTest::m_testCase private
Definition at line 65 of file tcp-rate-ops-test.cc.
Referenced by SkbDelivered().
The documentation for this class was generated from the following file:
src/internet/test/tcp-rate-ops-test.cc