ns-3: ns3::CoDelQueueDisc Class Reference
ns3::CoDelQueueDisc Class Reference
Traffic-control
A CoDel packet queue disc.
#include "codel-queue-disc.h"
Public Member Functions
CoDelQueueDisc ()
CoDelQueueDisc Constructor.
virtual ~CoDelQueueDisc ()
uint32_t GetDropNext (void)
Get the time for next packet drop while in the dropping state.
Time GetInterval (void)
Get the interval.
Time GetTarget (void)
Get the target queue delay.
Public Member Functions inherited from ns3::QueueDisc
QueueDisc (QueueDiscSizePolicy policy, QueueSizeUnit unit)
Constructor.
QueueDisc (QueueDiscSizePolicy policy=QueueDiscSizePolicy::SINGLE_INTERNAL_QUEUE)
Constructor.
virtual ~QueueDisc ()
void AddInternalQueue (Ptr< InternalQueue > queue)
Add an internal queue to the tail of the list of queues.
void AddPacketFilter (Ptr< PacketFilter > filter)
Add a packet filter to the tail of the list of filters used to classify packets.
void AddQueueDiscClass (Ptr< QueueDiscClass > qdClass)
Add a queue disc class to the tail of the list of classes.
int32_t Classify (Ptr< QueueDiscItem > item)
Classify a packet by calling the packet filters, one at a time, until either a filter able to classify the packet is found or all the filters have been processed.
Ptr< QueueDiscItem > Dequeue (void)
Extract from the queue disc the packet that has been dequeued by calling Peek, if any, or call the private DoDequeue method (which must be implemented by derived classes) to dequeue a packet, otherwise.
bool Enqueue (Ptr< QueueDiscItem > item)
Pass a packet to store to the queue discipline.
QueueSize GetCurrentSize (void)
Get the current size of the queue disc in bytes, if operating in bytes mode, or packets, otherwise.
Ptr< InternalQueue > GetInternalQueue (std::size_t i) const
Get the i-th internal queue.
QueueSize GetMaxSize (void) const
Get the maximum size of the queue disc.
uint32_t GetNBytes (void) const
Get the amount of bytes stored by the queue disc.
Ptr< NetDeviceQueueInterface > GetNetDeviceQueueInterface (void) const
std::size_t GetNInternalQueues (void) const
Get the number of internal queues.
std::size_t GetNPacketFilters (void) const
Get the number of packet filters.
uint32_t GetNPackets (void) const
Get the number of packets stored by the queue disc.
std::size_t GetNQueueDiscClasses (void) const
Get the number of queue disc classes.
Ptr< PacketFilter > GetPacketFilter (std::size_t i) const
Get the i-th packet filter.
Ptr< QueueDiscClass > GetQueueDiscClass (std::size_t i) const
Get the i-th queue disc class.
virtual uint32_t GetQuota (void) const
Get the maximum number of dequeue operations following a packet enqueue.
SendCallback GetSendCallback (void) const
const Stats & GetStats (void)
Retrieve all the collected statistics.
virtual WakeMode GetWakeMode (void) const
When setting up the wake callbacks on the netdevice queues, it is necessary to determine which queue disc (the root queue disc or one of its children) should be activated when the netdevice wakes one of its transmission queues.
Ptr< const QueueDiscItem > Peek (void)
Get a copy of the next packet the queue discipline will extract.
void Run (void)
Modelled after the Linux function __qdisc_run (net/sched/sch_generic.c) Dequeues multiple packets, until a quota is exceeded or sending a packet to the device failed.
bool SetMaxSize (QueueSize size)
Set the maximum size of the queue disc.
void SetNetDeviceQueueInterface (Ptr< NetDeviceQueueInterface > ndqi)
virtual void SetQuota (const uint32_t quota)
Set the maximum number of dequeue operations following a packet enqueue.
void SetSendCallback (SendCallback func)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::QueueDisc
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static constexpr const char * CE_THRESHOLD_EXCEEDED_MARK = "CE threshold exceeded mark"
Sojourn time above CE threshold.
static constexpr const char * OVERLIMIT_DROP = "Overlimit drop"
Overlimit dropped packet.
static constexpr const char * TARGET_EXCEEDED_DROP = "Target exceeded drop"
Sojourn time above target.
static constexpr const char * TARGET_EXCEEDED_MARK = "Target exceeded mark"
Sojourn time above target.
Static Public Attributes inherited from ns3::QueueDisc
static constexpr const char * CHILD_QUEUE_DISC_DROP = "(Dropped by child queue disc) "
Packet dropped by a child queue disc.
static constexpr const char * CHILD_QUEUE_DISC_MARK = "(Marked by child queue disc) "
Packet marked by a child queue disc.
static constexpr const char * INTERNAL_QUEUE_DROP = "Dropped by internal queue"
Packet dropped by an internal queue.
Private Member Functions
virtual bool CheckConfig (void)
Check whether the current configuration is correct.
bool CoDelTimeAfter (uint32_t a, uint32_t b)
Check if CoDel time a is successive to b.
bool CoDelTimeAfterEq (uint32_t a, uint32_t b)
Check if CoDel time a is successive or equal to b.
bool CoDelTimeBefore (uint32_t a, uint32_t b)
Check if CoDel time a is preceding b.
bool CoDelTimeBeforeEq (uint32_t a, uint32_t b)
Check if CoDel time a is preceding or equal to b.
virtual Ptr< QueueDiscItem > DoDequeue (void)
Remove a packet from queue based on the current state If we are in dropping state, check if we could leave the dropping state or if we should perform next drop If we are not currently in dropping state, check if we need to enter the state and drop the first packet.
virtual bool DoEnqueue (Ptr< QueueDiscItem > item)
Add a packet to the queue.
virtual void InitializeParams (void)
Initialize parameters (if any) before the first packet is enqueued.
bool OkToDrop (Ptr< QueueDiscItem > item, uint32_t now)
Determine whether a packet is OK to be dropped.
uint32_t Time2CoDel (Time t)
Return the unsigned 32-bit integer representation of the input Time object.
Static Private Member Functions
static uint32_t ControlLaw (uint32_t t, uint32_t interval, uint32_t recInvSqrt)
Determine the time for next drop CoDel control law is t + m_interval/sqrt(m_count).
static uint16_t NewtonStep (uint16_t recInvSqrt, uint32_t count)
Calculate the reciprocal square root of m_count by using Newton's method http://en.wikipedia.org/wiki/Methods_of_computing_square_roots#Iterative_methods_for_reciprocal_square_roots m_recInvSqrt (new) = (m_recInvSqrt (old) / 2) * (3 - m_count * m_recInvSqrt^2)
Private Attributes
Time m_ceThreshold
Threshold above which to CE mark.
TracedValue< uint32_t > m_count
Number of packets dropped since entering drop state.
TracedValue< uint32_t > m_dropNext
Time to drop next packet.
TracedValue< bool > m_dropping
True if in dropping state.
uint32_t m_firstAboveTime
Time to declare sojourn time above target.
Time m_interval
100 ms sliding minimum time window width
TracedValue< uint32_t > m_lastCount
Last number of packets dropped since entering drop state.
uint32_t m_minBytes
Minimum bytes in queue to allow a packet drop.
uint16_t m_recInvSqrt
Reciprocal inverse square root.
Time m_target
5 ms target queue delay
bool m_useEcn
True if ECN is used (packets are marked instead of being dropped)
bool m_useL4s
True if L4S is used (ECT1 packets are marked at CE threshold)
Additional Inherited Members
Public Types inherited from ns3::QueueDisc
typedef Queue< QueueDiscItem > InternalQueue
Internal queues store QueueDiscItem objects.
typedef std::function< void(Ptr< QueueDiscItem >)> SendCallback
Callback invoked to send a packet to the receiving object when Run is called.
enum WakeMode { WAKE_ROOT = 0x00 , WAKE_CHILD = 0x01 }
Used to determine whether the queue disc itself or its children must be activated when a netdevice wakes a transmission queue.
Protected Member Functions inherited from ns3::QueueDisc
virtual void DoDispose (void)
Dispose of the object.
void DoInitialize (void)
Check whether the configuration is correct and initialize parameters.
void DropAfterDequeue (Ptr< const QueueDiscItem > item, const char *reason)
Perform the actions required when the queue disc is notified of a packet dropped after dequeue.
void DropBeforeEnqueue (Ptr< const QueueDiscItem > item, const char *reason)
Perform the actions required when the queue disc is notified of a packet dropped before enqueue.
bool Mark (Ptr< QueueDiscItem > item, const char *reason)
Marks the given packet and, if successful, updates the counters associated with the given reason.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A CoDel packet queue disc.
Introspection did not find any typical Config paths.
Attributes
UseEcn: True to use ECN (packets are marked instead of being dropped)
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
UseL4s: True to use L4S (only ECT1 packets are marked at CE threshold)
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
MaxSize: The maximum number of packets/bytes accepted by this queue disc.
Set with class: QueueSizeValue
Underlying type: QueueSize
Initial value: 1500000B
Flags: construct write read
MinBytes: The CoDel algorithm minbytes parameter.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 1500
Flags: construct write read
Interval: The CoDel algorithm interval
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: 100ms
Flags: construct write read
Target: The CoDel algorithm target queue delay
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: 5ms
Flags: construct write read
CeThreshold: The CoDel CE threshold for marking packets
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +9.22337e+18ns
Flags: construct write read
Attributes defined in parent class ns3::QueueDisc
Quota: The maximum number of packets dequeued in a qdisc run
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 64
Flags: construct write read
InternalQueueList: The list of internal queues.
Set with class: ns3::ObjectPtrContainerValue
Underlying type: ns3::Ptr< ns3::Queue<QueueDiscItem>>
Flags: read
PacketFilterList: The list of packet filters.
Set with class: ns3::ObjectPtrContainerValue
Underlying type: ns3::Ptr< ns3::PacketFilter>
Flags: read
QueueDiscClassList: The list of queue disc classes.
Set with class: ns3::ObjectPtrContainerValue
Underlying type: ns3::Ptr< ns3::QueueDiscClass>
Flags: read
TraceSources
Count: CoDel count
Callback signature: ns3::TracedValueCallback::Uint32
LastCount: CoDel lastcount
Callback signature: ns3::TracedValueCallback::Uint32
DropState: Dropping state
Callback signature: ns3::TracedValueCallback::Bool
DropNext: Time until next packet drop
Callback signature: ns3::TracedValueCallback::Uint32
TraceSources defined in parent class ns3::QueueDisc
Enqueue: Enqueue a packet in the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
Dequeue: Dequeue a packet from the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
Requeue: Requeue a packet in the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
Drop: Drop a packet stored in the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
DropBeforeEnqueue: Drop a packet before enqueue
Callback signature: ns3::QueueDiscItem::TracedCallback
DropAfterDequeue: Drop a packet after dequeue
Callback signature: ns3::QueueDiscItem::TracedCallback
Mark: Mark a packet stored in the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
PacketsInQueue: Number of packets currently stored in the queue disc
Callback signature: ns3::TracedValueCallback::Uint32
BytesInQueue: Number of bytes currently stored in the queue disc
Callback signature: ns3::TracedValueCallback::Uint32
SojournTime: Sojourn time of the last packet dequeued from the queue disc
Callback signature: ns3::Time::TracedCallback
Size of this type is 1216 bytes (on a 64-bit architecture).
Definition at line 61 of file codel-queue-disc.h.
Constructor & Destructor Documentation
CoDelQueueDisc()
ns3::CoDelQueueDisc::CoDelQueueDisc ()
CoDelQueueDisc Constructor.
Creates a CoDel queue
Definition at line 133 of file codel-queue-disc.cc.
References NS_LOG_FUNCTION.
~CoDelQueueDisc()
ns3::CoDelQueueDisc::~CoDelQueueDisc () virtual
Definition at line 145 of file codel-queue-disc.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CheckConfig()
bool ns3::CoDelQueueDisc::CheckConfig (void) private virtual
Check whether the current configuration is correct.
Default objects (such as internal queues) might be created by this method to ensure the configuration is correct. This method is automatically called at simulation initialization time, and it is called before the InitializeParams () method. It is appropriate to promote parameter initialization to this method if it aids in checking for correct configuration.
See also
QueueDisc::InitializeParams
Returns
true if the configuration is correct, false otherwise
Implements ns3::QueueDisc.
Definition at line 450 of file codel-queue-disc.cc.
References ns3::QueueDisc::AddInternalQueue(), ns3::CreateObjectWithAttributes(), ns3::QueueDisc::GetMaxSize(), ns3::QueueDisc::GetNInternalQueues(), ns3::QueueDisc::GetNPacketFilters(), ns3::QueueDisc::GetNQueueDiscClasses(), NS_LOG_ERROR, and NS_LOG_FUNCTION.
CoDelTimeAfter()
bool ns3::CoDelQueueDisc::CoDelTimeAfter (uint32_t a, uint32_t b) private
Check if CoDel time a is successive to b.
Parameters
a left operand
b right operand
Returns
true if a is greater than b
Definition at line 420 of file codel-queue-disc.cc.
Referenced by DoDequeue(), and OkToDrop().
CoDelTimeAfterEq()
bool ns3::CoDelQueueDisc::CoDelTimeAfterEq (uint32_t a, uint32_t b) private
Check if CoDel time a is successive or equal to b.
Parameters
a left operand
b right operand
Returns
true if a is greater than or equal to b
Definition at line 426 of file codel-queue-disc.cc.
Referenced by DoDequeue().
CoDelTimeBefore()
bool ns3::CoDelQueueDisc::CoDelTimeBefore (uint32_t a, uint32_t b) private
Check if CoDel time a is preceding b.
Parameters
a left operand
b right operand
Returns
true if a is less than to b
Definition at line 432 of file codel-queue-disc.cc.
Referenced by DoDequeue(), and OkToDrop().
CoDelTimeBeforeEq()
bool ns3::CoDelQueueDisc::CoDelTimeBeforeEq (uint32_t a, uint32_t b) private
Check if CoDel time a is preceding or equal to b.
Parameters
a left operand
b right operand
Returns
true if a is less than or equal to b
Definition at line 438 of file codel-queue-disc.cc.
ControlLaw()
uint32_t ns3::CoDelQueueDisc::ControlLaw (uint32_t t, uint32_t interval, uint32_t recInvSqrt) static private
Determine the time for next drop CoDel control law is t + m_interval/sqrt(m_count).
Here, we use m_recInvSqrt calculated by Newton's method in NewtonStep() to avoid both sqrt() and divide operations
Parameters
t Current next drop time (in units of CoDel time)
interval interval (in units of CoDel time)
recInvSqrt reciprocal value of sqrt (count)
Returns
The new next drop time (in units of CoDel time)
Definition at line 164 of file codel-queue-disc.cc.
References NS_LOG_FUNCTION_NOARGS, REC_INV_SQRT_SHIFT, and ns3::ReciprocalDivide().
Referenced by DoDequeue().
DoDequeue()
Ptr< QueueDiscItem > ns3::CoDelQueueDisc::DoDequeue (void) private virtual
Remove a packet from queue based on the current state If we are in dropping state, check if we could leave the dropping state or if we should perform next drop If we are not currently in dropping state, check if we need to enter the state and drop the first packet.
Returns
The packet that is examined
Implements ns3::QueueDisc.
Definition at line 235 of file codel-queue-disc.cc.
References CE_THRESHOLD_EXCEEDED_MARK, ns3::CoDelGetTime(), CoDelTimeAfter(), CoDelTimeAfterEq(), CoDelTimeBefore(), ControlLaw(), ns3::QueueDisc::DropAfterDequeue(), ns3::QueueDisc::GetInternalQueue(), ns3::QueueDisc::GetNBytes(), ns3::QueueDisc::GetNPackets(), ns3::Time::GetSeconds(), ns3::QueueItem::IP_DSFIELD, m_ceThreshold, m_count, m_dropNext, m_dropping, m_interval, m_lastCount, m_recInvSqrt, m_useEcn, m_useL4s, ns3::QueueDisc::Mark(), NewtonStep(), ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, OkToDrop(), REC_INV_SQRT_SHIFT, TARGET_EXCEEDED_DROP, TARGET_EXCEEDED_MARK, and Time2CoDel().
DoEnqueue()
bool ns3::CoDelQueueDisc::DoEnqueue (Ptr< QueueDiscItem > item) private virtual
Add a packet to the queue.
Parameters
item The item to be added
Returns
True if the packet can be added, False if the packet is dropped due to full queue
Implements ns3::QueueDisc.
Definition at line 171 of file codel-queue-disc.cc.
References ns3::QueueDisc::DropBeforeEnqueue(), ns3::QueueDisc::GetCurrentSize(), ns3::QueueDisc::GetInternalQueue(), ns3::QueueDisc::GetMaxSize(), ns3::QueueDisc::GetNBytes(), ns3::QueueDisc::GetNPackets(), NS_LOG_FUNCTION, NS_LOG_LOGIC, and OVERLIMIT_DROP.
GetDropNext()
uint32_t ns3::CoDelQueueDisc::GetDropNext (void)
Get the time for next packet drop while in the dropping state.
Returns
The time for next packet drop
Definition at line 414 of file codel-queue-disc.cc.
References m_dropNext.
GetInterval()
Time ns3::CoDelQueueDisc::GetInterval (void)
Get the interval.
Returns
The interval
Definition at line 408 of file codel-queue-disc.cc.
References m_interval.
GetTarget()
Time ns3::CoDelQueueDisc::GetTarget (void)
Get the target queue delay.
Returns
The target queue delay
Definition at line 402 of file codel-queue-disc.cc.
References m_target.
GetTypeId()
TypeId ns3::CoDelQueueDisc::GetTypeId (void) static
Get the type ID.
Get the type ID.
Returns
the object TypeId
Definition at line 70 of file codel-queue-disc.cc.
References ns3::BYTES, DEFAULT_CODEL_LIMIT, ns3::QueueDisc::GetMaxSize(), m_ceThreshold, m_count, m_dropNext, m_dropping, m_interval, m_lastCount, m_minBytes, m_target, m_useEcn, m_useL4s, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeQueueSizeAccessor(), ns3::MakeQueueSizeChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), ns3::Time::Max(), ns3::QueueDisc::SetMaxSize(), and ns3::TypeId::SetParent().
InitializeParams()
void ns3::CoDelQueueDisc::InitializeParams (void) private virtual
Initialize parameters (if any) before the first packet is enqueued.
This method is automatically called at simulation initialization time, after the CheckConfig() method has been called.
See also
QueueDisc::CheckConfig
Implements ns3::QueueDisc.
Definition at line 482 of file codel-queue-disc.cc.
References NS_LOG_FUNCTION.
NewtonStep()
uint16_t ns3::CoDelQueueDisc::NewtonStep (uint16_t recInvSqrt, uint32_t count) static private
Calculate the reciprocal square root of m_count by using Newton's method http://en.wikipedia.org/wiki/Methods_of_computing_square_roots#Iterative_methods_for_reciprocal_square_roots m_recInvSqrt (new) = (m_recInvSqrt (old) / 2) * (3 - m_count * m_recInvSqrt^2)
Parameters
recInvSqrt reciprocal value of sqrt (count)
count count value
Returns
The new recInvSqrt value
Definition at line 151 of file codel-queue-disc.cc.
References NS_LOG_FUNCTION_NOARGS, and REC_INV_SQRT_SHIFT.
Referenced by DoDequeue().
OkToDrop()
bool ns3::CoDelQueueDisc::OkToDrop (Ptr< QueueDiscItem > item, uint32_t now) private
Determine whether a packet is OK to be dropped.
The packet may not be actually dropped (depending on the drop state)
Parameters
item The packet that is considered
now The current time represented as 32-bit unsigned integer (us)
Returns
True if it is OK to drop the packet (sojourn time above target for at least interval)
Definition at line 194 of file codel-queue-disc.cc.
References ns3::Time::As(), CoDelTimeAfter(), CoDelTimeBefore(), ns3::QueueDisc::GetInternalQueue(), ns3::QueueDisc::GetNBytes(), m_firstAboveTime, m_interval, m_minBytes, m_target, ns3::Time::MS, ns3::Simulator::Now(), NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, and Time2CoDel().
Referenced by DoDequeue().
Time2CoDel()
uint32_t ns3::CoDelQueueDisc::Time2CoDel (Time t) private
Return the unsigned 32-bit integer representation of the input Time object.
Units are microseconds
Parameters
t the input Time Object
Returns
the unsigned 32-bit integer representation
Definition at line 444 of file codel-queue-disc.cc.
References ns3::CODEL_SHIFT, and ns3::Time::GetNanoSeconds().
Referenced by DoDequeue(), and OkToDrop().
Member Data Documentation
CE_THRESHOLD_EXCEEDED_MARK
constexpr const char* ns3::CoDelQueueDisc::CE_THRESHOLD_EXCEEDED_MARK = "CE threshold exceeded mark" static constexpr
Sojourn time above CE threshold.
Definition at line 106 of file codel-queue-disc.h.
Referenced by DoDequeue().
m_ceThreshold
Time ns3::CoDelQueueDisc::m_ceThreshold private
Threshold above which to CE mark.
Definition at line 209 of file codel-queue-disc.h.
Referenced by DoDequeue(), and GetTypeId().
m_count
TracedValue<uint32_t> ns3::CoDelQueueDisc::m_count private
Number of packets dropped since entering drop state.
Definition at line 210 of file codel-queue-disc.h.
Referenced by DoDequeue(), and GetTypeId().
m_dropNext
TracedValue<uint32_t> ns3::CoDelQueueDisc::m_dropNext private
Time to drop next packet.
Definition at line 215 of file codel-queue-disc.h.
Referenced by DoDequeue(), GetDropNext(), and GetTypeId().
m_dropping
TracedValue<bool> ns3::CoDelQueueDisc::m_dropping private
True if in dropping state.
Definition at line 212 of file codel-queue-disc.h.
Referenced by DoDequeue(), and GetTypeId().
m_firstAboveTime
uint32_t ns3::CoDelQueueDisc::m_firstAboveTime private
Time to declare sojourn time above target.
Definition at line 214 of file codel-queue-disc.h.
Referenced by OkToDrop().
m_interval
Time ns3::CoDelQueueDisc::m_interval private
100 ms sliding minimum time window width
Definition at line 207 of file codel-queue-disc.h.
Referenced by DoDequeue(), GetInterval(), GetTypeId(), and OkToDrop().
m_lastCount
TracedValue<uint32_t> ns3::CoDelQueueDisc::m_lastCount private
Last number of packets dropped since entering drop state.
Definition at line 211 of file codel-queue-disc.h.
Referenced by DoDequeue(), and GetTypeId().
m_minBytes
uint32_t ns3::CoDelQueueDisc::m_minBytes private
Minimum bytes in queue to allow a packet drop.
Definition at line 206 of file codel-queue-disc.h.
Referenced by GetTypeId(), and OkToDrop().
m_recInvSqrt
uint16_t ns3::CoDelQueueDisc::m_recInvSqrt private
Reciprocal inverse square root.
Definition at line 213 of file codel-queue-disc.h.
Referenced by DoDequeue().
m_target
Time ns3::CoDelQueueDisc::m_target private
5 ms target queue delay
Definition at line 208 of file codel-queue-disc.h.
Referenced by GetTarget(), GetTypeId(), and OkToDrop().
m_useEcn
bool ns3::CoDelQueueDisc::m_useEcn private
True if ECN is used (packets are marked instead of being dropped)
Definition at line 204 of file codel-queue-disc.h.
Referenced by DoDequeue(), and GetTypeId().
m_useL4s
bool ns3::CoDelQueueDisc::m_useL4s private
True if L4S is used (ECT1 packets are marked at CE threshold)
Definition at line 205 of file codel-queue-disc.h.
Referenced by DoDequeue(), and GetTypeId().
OVERLIMIT_DROP
constexpr const char* ns3::CoDelQueueDisc::OVERLIMIT_DROP = "Overlimit drop" static constexpr
Overlimit dropped packet.
Definition at line 103 of file codel-queue-disc.h.
Referenced by DoEnqueue().
TARGET_EXCEEDED_DROP
constexpr const char* ns3::CoDelQueueDisc::TARGET_EXCEEDED_DROP = "Target exceeded drop" static constexpr
Sojourn time above target.
Definition at line 102 of file codel-queue-disc.h.
Referenced by DoDequeue().
TARGET_EXCEEDED_MARK
constexpr const char* ns3::CoDelQueueDisc::TARGET_EXCEEDED_MARK = "Target exceeded mark" static constexpr
Sojourn time above target.
Definition at line 105 of file codel-queue-disc.h.
Referenced by DoDequeue().
The documentation for this class was generated from the following files:
src/traffic-control/model/codel-queue-disc.h
src/traffic-control/model/codel-queue-disc.cc