ns-3: ns3::TcpSocketBase Class Reference
ns3::TcpSocketBase Class Reference
Network » Socket | Internet » TCP
A base class for implementation of a stream socket using TCP.
#include "tcp-socket-base.h"
Public Types
typedef void(* TcpTxRxTracedCallback) (const Ptr< const Packet > packet, const TcpHeader &header, const Ptr< const TcpSocketBase > socket)
TracedCallback signature for tcp packet transmission or reception events.
Public Types inherited from ns3::TcpSocket
enum TcpStates_t {
CLOSED = 0 , LISTEN , SYN_SENT , SYN_RCVD ,
ESTABLISHED , CLOSE_WAIT , LAST_ACK , FIN_WAIT_1 ,
FIN_WAIT_2 , CLOSING , TIME_WAIT , LAST_STATE
}
Names of the 11 TCP states.
Public Types inherited from ns3::Socket
enum Ipv6MulticastFilterMode { INCLUDE =1 , EXCLUDE }
Enumeration of the possible filter of a socket.
enum SocketErrno {
ERROR_NOTERROR , ERROR_ISCONN , ERROR_NOTCONN , ERROR_MSGSIZE ,
ERROR_AGAIN , ERROR_SHUTDOWN , ERROR_OPNOTSUPP , ERROR_AFNOSUPPORT ,
ERROR_INVAL , ERROR_BADF , ERROR_NOROUTETOHOST , ERROR_NODEV ,
ERROR_ADDRNOTAVAIL , ERROR_ADDRINUSE , SOCKET_ERRNO_LAST
}
Enumeration of the possible errors returned by a socket.
enum SocketPriority {
NS3_PRIO_BESTEFFORT = 0 , NS3_PRIO_FILLER = 1 , NS3_PRIO_BULK = 2 , NS3_PRIO_INTERACTIVE_BULK = 4 ,
NS3_PRIO_INTERACTIVE = 6 , NS3_PRIO_CONTROL = 7
}
Enumeration of the possible socket priorities.
enum SocketType { NS3_SOCK_STREAM , NS3_SOCK_SEQPACKET , NS3_SOCK_DGRAM , NS3_SOCK_RAW }
Enumeration of the possible socket types.
Public Member Functions
TcpSocketBase (const TcpSocketBase &sock)
Clone a TCP socket, for use upon receiving a connection request in LISTEN state.
TcpSocketBase (void)
Create an unbound TCP socket.
virtual ~TcpSocketBase (void)
virtual int Bind (const Address &address)
Allocate a local endpoint for this socket.
virtual int Bind (void)
Allocate a local IPv4 endpoint for this socket.
virtual int Bind6 (void)
Allocate a local IPv6 endpoint for this socket.
virtual void BindToNetDevice (Ptr< NetDevice > netdevice)
Bind a socket to specific device.
bool CheckEcnCe (uint8_t tos) const
Checks for CE codepoint.
bool CheckEcnEct0 (uint8_t tos) const
Checks for ECT(0) codepoint.
bool CheckEcnEct1 (uint8_t tos) const
Checks for ECT(1) codepoint.
bool CheckNoEcn (uint8_t tos) const
Checks if TOS has no ECN codepoints.
uint8_t ClearEcnBits (uint8_t tos) const
Clears ECN bits from TOS.
virtual int Close (void)
Close a socket.
virtual int Connect (const Address &address)
Initiate a connection to a remote host.
Time GetClockGranularity (void) const
Get the Clock Granularity (used in RTO calcs).
virtual enum SocketErrno GetErrno (void) const
Get last error number.
virtual TypeId GetInstanceTypeId () const
Get the instance TypeId.
Time GetMinRto (void) const
Get the Minimum RTO.
virtual Ptr< Node > GetNode (void) const
Return the node this socket is associated with.
virtual int GetPeerName (Address &address) const
Get the peer address of a connected socket.
uint32_t GetRetxThresh (void) const
Get the retransmission threshold (dup ack threshold for a fast retransmit)
virtual uint32_t GetRxAvailable (void) const
Return number of bytes which can be returned from one or multiple calls to Recv.
Ptr< TcpRxBuffer > GetRxBuffer (void) const
Get a pointer to the Rx buffer.
virtual enum SocketType GetSocketType (void) const
virtual int GetSockName (Address &address) const
Get socket address.
virtual uint32_t GetTxAvailable (void) const
Returns the number of bytes which can be sent in a single call to Send.
Ptr< TcpTxBuffer > GetTxBuffer (void) const
Get a pointer to the Tx buffer.
virtual int Listen (void)
Listen for incoming connections.
uint8_t MarkEcnCe (uint8_t tos) const
Mark CE codepoint.
uint8_t MarkEcnCodePoint (const uint8_t tos, const TcpSocketState::EcnCodePoint_t codePoint) const
mark ECN code point
uint8_t MarkEcnEct0 (uint8_t tos) const
Mark ECT(0) codepoint.
uint8_t MarkEcnEct1 (uint8_t tos) const
Mark ECT(1) codepoint.
virtual Ptr< Packet > Recv (uint32_t maxSize, uint32_t flags)
Read data from the socket.
virtual Ptr< Packet > RecvFrom (uint32_t maxSize, uint32_t flags, Address &fromAddress)
Read a single packet from the socket and retrieve the sender address.
virtual int Send (Ptr< Packet > p, uint32_t flags)
Send data (or dummy data) to the remote host.
virtual int SendTo (Ptr< Packet > p, uint32_t flags, const Address &toAddress)
Send data to a specified peer.
void SetClockGranularity (Time clockGranularity)
Sets the Clock Granularity (used in RTO calcs).
void SetCongestionControlAlgorithm (Ptr< TcpCongestionOps > algo)
Install a congestion control algorithm on this socket.
void SetMinRto (Time minRto)
Sets the Minimum RTO.
virtual void SetNode (Ptr< Node > node)
Set the associated node.
void SetPaceInitialWindow (bool paceWindow)
Enable or disable pacing of the initial window.
void SetPacingStatus (bool pacing)
Enable or disable pacing.
void SetRecoveryAlgorithm (Ptr< TcpRecoveryOps > recovery)
Install a recovery algorithm on this socket.
void SetRetxThresh (uint32_t retxThresh)
Set the retransmission threshold (dup ack threshold for a fast retransmit)
virtual void SetRtt (Ptr< RttEstimator > rtt)
Set the associated RTT estimator.
virtual void SetTcp (Ptr< TcpL4Protocol > tcp)
Set the associated TCP L4 protocol.
void SetUseEcn (TcpSocketState::UseEcn_t useEcn)
Set ECN mode of use on the socket.
virtual int ShutdownRecv (void)
virtual int ShutdownSend (void)
void UpdateBytesInFlight (uint32_t oldValue, uint32_t newValue)
Callback function to hook to TcpSocketState bytes inflight.
void UpdateCongState (TcpSocketState::TcpCongState_t oldValue, TcpSocketState::TcpCongState_t newValue)
Callback function to hook to TcpSocketState congestion state.
void UpdateCwnd (uint32_t oldValue, uint32_t newValue)
Callback function to hook to TcpSocketState congestion window.
void UpdateCwndInfl (uint32_t oldValue, uint32_t newValue)
Callback function to hook to TcpSocketState inflated congestion window.
void UpdateEcnState (TcpSocketState::EcnState_t oldValue, TcpSocketState::EcnState_t newValue)
Callback function to hook to EcnState state.
void UpdateHighTxMark (SequenceNumber32 oldValue, SequenceNumber32 newValue)
Callback function to hook to TcpSocketState high tx mark.
void UpdateNextTxSequence (SequenceNumber32 oldValue, SequenceNumber32 newValue)
Callback function to hook to TcpSocketState next tx sequence.
void UpdatePacingRateTrace (DataRate oldValue, DataRate newValue)
Callback function to hook to TcpSocketState pacing rate.
void UpdateRtt (Time oldValue, Time newValue)
Callback function to hook to TcpSocketState rtt.
void UpdateSsThresh (uint32_t oldValue, uint32_t newValue)
Callback function to hook to TcpSocketState slow start threshold.
Public Member Functions inherited from ns3::TcpSocket
TcpSocket (void)
virtual ~TcpSocket (void)
Public Member Functions inherited from ns3::Socket
Socket (void)
virtual ~Socket (void)
Ptr< NetDevice > GetBoundNetDevice ()
Returns socket's bound NetDevice, if any.
uint8_t GetIpTos (void) const
Query the value of IP Type of Service of this socket.
virtual uint8_t GetIpTtl (void) const
Query the value of IP Time to Live field of this socket.
virtual uint8_t GetIpv6HopLimit (void) const
Query the value of IP Hop Limit field of this socket.
uint8_t GetIpv6Tclass (void) const
Query the value of IPv6 Traffic Class field of this socket.
uint8_t GetPriority (void) const
Query the priority value of this socket.
virtual void Ipv6JoinGroup (Ipv6Address address)
Joins a IPv6 multicast group without filters.
virtual void Ipv6JoinGroup (Ipv6Address address, Ipv6MulticastFilterMode filterMode, std::vector< Ipv6Address > sourceAddresses)
Joins a IPv6 multicast group.
virtual void Ipv6LeaveGroup (void)
Leaves IPv6 multicast group this socket is joined to.
bool IsIpRecvTos (void) const
Ask if the socket is currently passing information about IP Type of Service up the stack.
bool IsIpRecvTtl (void) const
Ask if the socket is currently passing information about IP_TTL up the stack.
bool IsIpv6RecvHopLimit (void) const
Ask if the socket is currently passing information about IPv6 Hop Limit up the stack.
bool IsIpv6RecvTclass (void) const
Ask if the socket is currently passing information about IPv6 Traffic Class up the stack.
bool IsRecvPktInfo () const
Get status indicating whether enable/disable packet information to socket.
int Recv (uint8_t *buf, uint32_t size, uint32_t flags)
Recv data (or dummy data) from the remote host.
Ptr< Packet > Recv (void)
Read a single packet from the socket.
Ptr< Packet > RecvFrom (Address &fromAddress)
Read a single packet from the socket and retrieve the sender address.
int RecvFrom (uint8_t *buf, uint32_t size, uint32_t flags, Address &fromAddress)
Read a single packet from the socket and retrieve the sender address.
int Send (const uint8_t *buf, uint32_t size, uint32_t flags)
Send data (or dummy data) to the remote host.
int Send (Ptr< Packet > p)
Send data (or dummy data) to the remote host.
int SendTo (const uint8_t *buf, uint32_t size, uint32_t flags, const Address &address)
Send data to a specified peer.
void SetAcceptCallback (Callback< bool, Ptr< Socket >, const Address & > connectionRequest, Callback< void, Ptr< Socket >, const Address & > newConnectionCreated)
Accept connection requests from remote hosts.
void SetCloseCallbacks (Callback< void, Ptr< Socket > > normalClose, Callback< void, Ptr< Socket > > errorClose)
Detect socket recv() events such as graceful shutdown or error.
void SetConnectCallback (Callback< void, Ptr< Socket > > connectionSucceeded, Callback< void, Ptr< Socket > > connectionFailed)
Specify callbacks to allow the caller to determine if the connection succeeds of fails.
void SetDataSentCallback (Callback< void, Ptr< Socket >, uint32_t > dataSent)
Notify application when a packet has been sent from transport protocol (non-standard socket call)
void SetIpRecvTos (bool ipv4RecvTos)
Tells a socket to pass information about IP Type of Service up the stack.
void SetIpRecvTtl (bool ipv4RecvTtl)
Tells a socket to pass information about IP_TTL up the stack.
void SetIpTos (uint8_t ipTos)
Manually set IP Type of Service field.
virtual void SetIpTtl (uint8_t ipTtl)
Manually set IP Time to Live field.
virtual void SetIpv6HopLimit (uint8_t ipHopLimit)
Manually set IPv6 Hop Limit.
void SetIpv6RecvHopLimit (bool ipv6RecvHopLimit)
Tells a socket to pass information about IPv6 Hop Limit up the stack.
void SetIpv6RecvTclass (bool ipv6RecvTclass)
Tells a socket to pass information about IPv6 Traffic Class up the stack.
void SetIpv6Tclass (int ipTclass)
Manually set IPv6 Traffic Class field.
void SetPriority (uint8_t priority)
Manually set the socket priority.
void SetRecvCallback (Callback< void, Ptr< Socket > >)
Notify application when new data is available to be read.
void SetRecvPktInfo (bool flag)
Enable/Disable receive packet information to socket.
void SetSendCallback (Callback< void, Ptr< Socket >, uint32_t > sendCb)
Notify application when space in transmit buffer is added.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpSocket
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Socket
static Ptr< Socket > CreateSocket (Ptr< Node > node, TypeId tid)
This method wraps the creation of sockets that is performed on a given node by a SocketFactory specified by TypeId.
static TypeId GetTypeId (void)
Get the type ID.
static uint8_t IpTos2Priority (uint8_t ipTos)
Return the priority corresponding to a given TOS value.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Public Attributes
TracedCallback< uint32_t, uint32_t > m_bytesInFlightTrace
Callback pointer for bytesInFlight trace chaining.
TracedCallback< TcpSocketState::TcpCongState_t, TcpSocketState::TcpCongState_t > m_congStateTrace
Callback pointer for congestion state trace chaining.
TracedCallback< uint32_t, uint32_t > m_cWndInflTrace
Callback pointer for cWndInfl trace chaining.
TracedCallback< uint32_t, uint32_t > m_cWndTrace
Callback pointer for cWnd trace chaining.
TracedCallback< TcpSocketState::EcnState_t, TcpSocketState::EcnState_t > m_ecnStateTrace
Callback pointer for ECN state trace chaining.
TracedCallback< SequenceNumber32, SequenceNumber32 > m_highTxMarkTrace
Callback pointer for high tx mark chaining.
TracedCallback< Time, Time > m_lastRttTrace
Callback pointer for RTT trace chaining.
TracedCallback< SequenceNumber32, SequenceNumber32 > m_nextTxSequenceTrace
Callback pointer for next tx sequence chaining.
TracedCallback< DataRate, DataRate > m_pacingRateTrace
Callback pointer for pacing rate trace chaining.
TracedCallback< uint32_t, uint32_t > m_ssThTrace
Callback pointer for ssTh trace chaining.
Protected Member Functions
void AddOptions (TcpHeader &tcpHeader)
Add options to TcpHeader.
void AddOptionSack (TcpHeader &header)
Add the SACK option to the header.
void AddOptionSackPermitted (TcpHeader &header)
Add the SACK PERMITTED option to the header.
void AddOptionTimestamp (TcpHeader &header)
Add the timestamp option to the header.
void AddOptionWScale (TcpHeader &header)
Add the window scale option to the header.
void AddSocketTags (const Ptr< Packet > &p) const
Add Tags for the Socket.
virtual uint16_t AdvertisedWindowSize (bool scale=true) const
The amount of Rx window announced to the peer.
virtual uint32_t AvailableWindow (void) const
Return unfilled portion of window.
virtual uint32_t BytesInFlight (void) const
Return total bytes in flight.
uint8_t CalculateWScale () const
Calculate window scale value based on receive buffer space.
void CancelAllTimers (void)
Cancel all timer when endpoint is deleted.
void CloseAndNotify (void)
Peacefully close the socket by notifying the upper layer and deallocate end point.
virtual void CompleteFork (Ptr< Packet > p, const TcpHeader &tcpHeader, const Address &fromAddress, const Address &toAddress)
Complete a connection by forking the socket.
void ConnectionSucceeded (void)
Schedule-friendly wrapper for Socket::NotifyConnectionSucceeded()
void DeallocateEndPoint (void)
Deallocate m_endPoint and m_endPoint6.
virtual void DelAckTimeout (void)
Action upon delay ACK timeout, i.e.
void Destroy (void)
Kill this socket by zeroing its attributes (IPv4)
void Destroy6 (void)
Kill this socket by zeroing its attributes (IPv6)
int DoClose (void)
Close a socket by sending RST, FIN, or FIN+ACK, depend on the current state.
int DoConnect (void)
Perform the real connection tasks: Send SYN if allowed, RST if invalid.
virtual void DoForwardUp (Ptr< Packet > packet, const Address &fromAddress, const Address &toAddress)
Called by TcpSocketBase::ForwardUp{,6}().
void DoPeerClose (void)
FIN is in sequence, notify app and respond with a FIN.
void DoRetransmit (void)
Retransmit the first segment marked as lost, without considering available window nor pacing.
void DupAck (uint32_t currentDelivered)
Dupack management.
void EnterCwr (uint32_t currentDelivered)
Enter CA_CWR state upon receipt of an ECN Echo.
void EnterRecovery (uint32_t currentDelivered)
Enter the CA_RECOVERY, and retransmit the head.
virtual void EstimateRtt (const TcpHeader &tcpHeader)
Take into account the packet for RTT estimation.
virtual Ptr< TcpSocketBase > Fork (void)
Call CopyObject<> to clone me.
void ForwardIcmp (Ipv4Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo)
Called by the L3 protocol when it received an ICMP packet to pass on to TCP.
void ForwardIcmp6 (Ipv6Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo)
Called by the L3 protocol when it received an ICMPv6 packet to pass on to TCP.
void ForwardUp (Ptr< Packet > packet, Ipv4Header header, uint16_t port, Ptr< Ipv4Interface > incomingInterface)
Called by the L3 protocol when it received a packet to pass on to TCP.
void ForwardUp6 (Ptr< Packet > packet, Ipv6Header header, uint16_t port, Ptr< Ipv6Interface > incomingInterface)
Called by the L3 protocol when it received a packet to pass on to TCP.
virtual bool GetAllowBroadcast (void) const
Query whether broadcast datagram transmissions are allowed.
virtual Time GetConnTimeout (void) const
Get the connection timeout.
virtual uint32_t GetDataRetries (void) const
Get the number of data transmission retries before giving up.
virtual uint32_t GetDelAckMaxCount (void) const
Get the number of packet to fire an ACK before delay timeout.
virtual Time GetDelAckTimeout (void) const
Get the time to delay an ACK.
SequenceNumber32 GetHighRxAck (void) const
Get the current value of the receiver's highest (in-sequence) sequence number acked.
virtual uint32_t GetInitialCwnd (void) const
Get the initial Congestion Window.
virtual uint32_t GetInitialSSThresh (void) const
Get the initial Slow Start Threshold.
virtual Time GetPersistTimeout (void) const
Get the timeout for persistent connection.
virtual uint32_t GetRcvBufSize (void) const
Get the receive buffer size.
uint32_t GetRWnd (void) const
Get the current value of the receiver's offered window (RCV.WND)
virtual uint32_t GetSegSize (void) const
Get the segment size.
virtual uint32_t GetSndBufSize (void) const
Get the send buffer size.
virtual uint32_t GetSynRetries (void) const
Get the number of connection retries before giving up.
virtual bool GetTcpNoDelay (void) const
Check if Nagle's algorithm is enabled or not.
bool IsPacingEnabled (void) const
Return true if packets in the current window should be paced.
bool IsTcpOptionEnabled (uint8_t kind) const
Return true if the specified option is enabled.
bool IsValidTcpSegment (const SequenceNumber32 seq, const uint32_t tcpHeaderSize, const uint32_t tcpPayloadSize)
Checks whether the given TCP segment is valid or not.
virtual void LastAckTimeout (void)
Timeout at LAST_ACK, close the connection.
virtual void NewAck (SequenceNumber32 const &seq, bool resetRTO)
Update buffers w.r.t.
void NotifyPacingPerformed (void)
Notify Pacing.
bool OutOfRange (SequenceNumber32 head, SequenceNumber32 tail) const
Check if a sequence number range is within the rx window.
void PeerClose (Ptr< Packet > p, const TcpHeader &tcpHeader)
Received a FIN from peer, notify rx buffer.
virtual void PersistTimeout (void)
Send 1 byte probe to get an updated window size.
virtual void ProcessAck (const SequenceNumber32 &ackNumber, bool scoreboardUpdated, uint32_t currentDelivered, const SequenceNumber32 &oldHeadSequence)
Process a received ack.
void ProcessClosing (Ptr< Packet > packet, const TcpHeader &tcpHeader)
Received a packet upon CLOSING.
void ProcessEstablished (Ptr< Packet > packet, const TcpHeader &tcpHeader)
Received a packet upon ESTABLISHED state.
void ProcessLastAck (Ptr< Packet > packet, const TcpHeader &tcpHeader)
Received a packet upon LAST_ACK.
void ProcessListen (Ptr< Packet > packet, const TcpHeader &tcpHeader, const Address &fromAddress, const Address &toAddress)
Received a packet upon LISTEN state.
uint32_t ProcessOptionSack (const Ptr< const TcpOption > option)
Read the SACK option.
void ProcessOptionSackPermitted (const Ptr< const TcpOption > option)
Read the SACK PERMITTED option.
void ProcessOptionTimestamp (const Ptr< const TcpOption > option, const SequenceNumber32 &seq)
Process the timestamp option from other side.
void ProcessOptionWScale (const Ptr< const TcpOption > option)
Read and parse the Window scale option.
void ProcessSynRcvd (Ptr< Packet > packet, const TcpHeader &tcpHeader, const Address &fromAddress, const Address &toAddress)
Received a packet upon SYN_RCVD.
void ProcessSynSent (Ptr< Packet > packet, const TcpHeader &tcpHeader)
Received a packet upon SYN_SENT.
void ProcessWait (Ptr< Packet > packet, const TcpHeader &tcpHeader)
Received a packet upon CLOSE_WAIT, FIN_WAIT_1, FIN_WAIT_2.
void ReadOptions (const TcpHeader &tcpHeader, uint32_t *bytesSacked)
Read TCP options before Ack processing.
virtual void ReceivedAck (Ptr< Packet > packet, const TcpHeader &tcpHeader)
Received an ACK packet.
virtual void ReceivedData (Ptr< Packet > packet, const TcpHeader &tcpHeader)
Recv of a data, put into buffer, call L7 to get it if necessary.
virtual void ReTxTimeout (void)
An RTO event happened.
virtual uint32_t SendDataPacket (SequenceNumber32 seq, uint32_t maxSize, bool withAck)
Extract at most maxSize bytes from the TxBuffer at sequence seq, add the TCP header, and send to TcpL4Protocol.
virtual void SendEmptyPacket (uint8_t flags)
Send a empty packet that carries a flag, e.g., ACK.
uint32_t SendPendingData (bool withAck=false)
Send as much pending data as possible according to the Tx window.
void SendRST (void)
Send reset and tear down this socket.
virtual bool SetAllowBroadcast (bool allowBroadcast)
Configure whether broadcast datagram transmissions are allowed.
virtual void SetConnTimeout (Time timeout)
Set the connection timeout.
virtual void SetDataRetries (uint32_t retries)
Set the number of data transmission retries before giving up.
virtual void SetDelAckMaxCount (uint32_t count)
Set the number of packet to fire an ACK before delay timeout.
virtual void SetDelAckTimeout (Time timeout)
Set the time to delay an ACK.
virtual void SetInitialCwnd (uint32_t cwnd)
Set the initial Congestion Window.
virtual void SetInitialSSThresh (uint32_t threshold)
Set the initial Slow Start Threshold.
virtual void SetPersistTimeout (Time timeout)
Set the timeout for persistent connection.
virtual void SetRcvBufSize (uint32_t size)
Set the receive buffer size.
virtual void SetSegSize (uint32_t size)
Set the segment size.
virtual void SetSndBufSize (uint32_t size)
Set the send buffer size.
virtual void SetSynRetries (uint32_t count)
Set the number of connection retries before giving up.
virtual void SetTcpNoDelay (bool noDelay)
Enable/Disable Nagle's algorithm.
int SetupCallback (void)
Common part of the two Bind(), i.e.
int SetupEndpoint (void)
Configure the endpoint to a local address.
int SetupEndpoint6 (void)
Configure the endpoint v6 to a local address.
void TimeWait (void)
Move from CLOSING or FIN_WAIT_2 to TIME_WAIT state.
virtual uint32_t UnAckDataCount (void) const
Return count of number of unacked bytes.
void UpdatePacingRate (void)
Dynamically update the pacing rate.
virtual void UpdateRttHistory (const SequenceNumber32 &seq, uint32_t sz, bool isRetransmission)
Update the RTT history, when we send TCP segments.
void UpdateWindowSize (const TcpHeader &header)
Update the receiver window (RWND) based on the value of the window field in the header.
virtual uint32_t Window (void) const
Return the max possible number of unacked bytes.
Protected Member Functions inherited from ns3::Socket
virtual void DoDispose (void)
Destructor implementation.
bool IsManualIpTtl (void) const
Checks if the socket has a specific IPv4 TTL set.
bool IsManualIpv6HopLimit (void) const
Checks if the socket has a specific IPv6 Hop Limit set.
bool IsManualIpv6Tclass (void) const
Checks if the socket has a specific IPv6 Tclass set.
void NotifyConnectionFailed (void)
Notify through the callback (if set) that the connection has not been established due to an error.
bool NotifyConnectionRequest (const Address &from)
Notify through the callback (if set) that an incoming connection is being requested by a remote host.
void NotifyConnectionSucceeded (void)
Notify through the callback (if set) that the connection has been established.
void NotifyDataRecv (void)
Notify through the callback (if set) that some data have been received.
void NotifyDataSent (uint32_t size)
Notify through the callback (if set) that some data have been sent.
void NotifyErrorClose (void)
Notify through the callback (if set) that the connection has been closed due to an error.
void NotifyNewConnectionCreated (Ptr< Socket > socket, const Address &from)
Notify through the callback (if set) that a new connection has been created.
void NotifyNormalClose (void)
Notify through the callback (if set) that the connection has been closed.
void NotifySend (uint32_t spaceAvailable)
Notify through the callback (if set) that some data have been sent.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Static Protected Member Functions
static uint32_t SafeSubtraction (uint32_t a, uint32_t b)
Performs a safe subtraction between a and b (a-b)
Protected Attributes
TracedValue< uint32_t > m_advWnd {0}
Advertised Window size.
uint32_t m_bytesAckedNotProcessed {0}
Bytes acked, but not processed.
Time m_clockGranularity {Seconds (0.001)}
Clock Granularity used in RTO calcs.
bool m_closeNotified {false}
Told app to close socket.
bool m_closeOnEmpty {false}
Close socket upon tx buffer emptied.
Time m_cnTimeout {Seconds (0.0)}
Timeout for connection retry.
Ptr< TcpCongestionOps > m_congestionControl
Congestion control.
bool m_connected {false}
Connection established.
uint32_t m_dataRetrCount {0}
Count of remaining data retransmission attempts.
uint32_t m_dataRetries {0}
Number of data retransmission attempts.
uint32_t m_delAckCount {0}
Delayed ACK counter.
EventId m_delAckEvent {}
Delayed ACK timeout event.
uint32_t m_delAckMaxCount {0}
Number of packet to fire an ACK before delay timeout.
Time m_delAckTimeout {Seconds (0.0)}
Time to delay an ACK.
uint32_t m_dupAckCount {0}
Dupack counter.
TracedValue< SequenceNumber32 > m_ecnCESeq {0}
Sequence number of the last received Congestion Experienced.
TracedValue< SequenceNumber32 > m_ecnCWRSeq {0}
Sequence number of the last sent CWR.
TracedValue< SequenceNumber32 > m_ecnEchoSeq {0}
Sequence number of the last received ECN Echo.
Ipv4EndPoint * m_endPoint {nullptr}
the IPv4 endpoint
Ipv6EndPoint * m_endPoint6 {nullptr}
the IPv6 endpoint
TracedValue< SequenceNumber32 > m_highRxAckMark {0}
Highest ack received.
TracedValue< SequenceNumber32 > m_highRxMark {0}
Highest seqno received.
SequenceNumber32 m_highTxAck {0}
Highest ack sent.
std::deque< RttHistory > m_history
List of sent packet.
Callback< void, Ipv4Address, uint8_t, uint8_t, uint8_t, uint32_t > m_icmpCallback
ICMP callback.
Callback< void, Ipv6Address, uint8_t, uint8_t, uint8_t, uint32_t > m_icmpCallback6
ICMPv6 callback.
bool m_isFirstPartialAck {true}
First partial ACK during RECOVERY.
EventId m_lastAckEvent {}
Last ACK timeout event.
bool m_limitedTx {true}
perform limited transmit
uint16_t m_maxWinSize {0}
Maximum window size to advertise.
Time m_minRto {Time::Max ()}
minimum value of the Retransmit timeout
double m_msl {0.0}
Max segment lifetime.
Ptr< Node > m_node
the associated node
bool m_noDelay {false}
Set to true to disable Nagle's algorithm.
Timer m_pacingTimer {Timer::CANCEL_ON_DESTROY}
Pacing Event.
EventId m_persistEvent {}
Persist event: Send 1 byte to probe for a non-zero Rx window.
Time m_persistTimeout {Seconds (0.0)}
Time between sending 1-byte probes.
Ptr< TcpRateOps > m_rateOps
Rate operations.
uint8_t m_rcvWindShift {0}
Window shift to apply to outgoing segments.
SequenceNumber32 m_recover {0}
Previous highest Tx seqnum for fast recovery (set it to initial seq number)
bool m_recoverActive {false}
Whether "m_recover" has been set/activated It is used to avoid comparing with the old m_recover value which was set for handling previous congestion event.
Ptr< TcpRecoveryOps > m_recoveryOps
Recovery Algorithm.
EventId m_retxEvent {}
Retransmission event.
uint32_t m_retxThresh {3}
Fast Retransmit threshold.
TracedValue< Time > m_rto {Seconds (0.0)}
Retransmit timeout.
Ptr< RttEstimator > m_rtt
Round trip time estimator.
TracedValue< uint32_t > m_rWnd {0}
Receiver window (RCV.WND in RFC793)
TracedCallback< Ptr< const Packet >, const TcpHeader &, Ptr< const TcpSocketBase > > m_rxTrace
Trace of received packets.
bool m_sackEnabled {true}
RFC SACK option enabled.
EventId m_sendPendingDataEvent {}
micro-delay event to send pending data
bool m_shutdownRecv {false}
Receive no longer allowed.
bool m_shutdownSend {false}
Send no longer allowed.
uint8_t m_sndWindShift {0}
Window shift to apply to incoming segments.
TracedValue< TcpStates_t > m_state {CLOSED}
TCP state.
uint32_t m_synCount {0}
Count of remaining connection retries.
uint32_t m_synRetries {0}
Number of connection attempts.
Ptr< TcpSocketState > m_tcb
Congestion control information.
Ptr< TcpL4Protocol > m_tcp
the associated TCP L4 protocol
bool m_timestampEnabled {true}
Timestamp option enabled.
uint32_t m_timestampToEcho {0}
Timestamp to echo.
EventId m_timewaitEvent {}
TIME_WAIT expiration event: Move this socket to CLOSED state.
Ptr< TcpTxBuffer > m_txBuffer
Tx buffer.
TracedCallback< Ptr< const Packet >, const TcpHeader &, Ptr< const TcpSocketBase > > m_txTrace
Trace of transmitted packets.
bool m_winScalingEnabled {true}
Window Scale option enabled (RFC 7323)
Protected Attributes inherited from ns3::Socket
Ptr< NetDevice > m_boundnetdevice
the device this socket is bound to (might be null).
Ipv6Address m_ipv6MulticastGroupAddress
IPv6 multicast group address.
bool m_recvPktInfo
if the socket should add packet info tags to the packet forwarded to L4.
Related Functions
(Note that these are not member functions.)
class TcpGeneralTest
TcpGeneralTest friend class (for tests).
Additional Inherited Members
Static Public Attributes inherited from ns3::TcpSocket
static const char *const TcpStateName [TcpSocket::LAST_STATE]
Literal names of TCP states for use in log messages.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A base class for implementation of a stream socket using TCP.
This class contains the essential components of TCP, as well as a sockets interface for upper layers to call. This class provides connection orientation and sliding window flow control; congestion control is delegated to subclasses of TcpCongestionOps. Part of TcpSocketBase is modified from the original NS-3 TCP socket implementation (TcpSocketImpl) by Raj Bhattacharjea raj.b.nosp@m.@gat.nosp@m.ech.e.nosp@m.du of Georgia Tech.
For IPv4 packets, the TOS set for the socket is used. The Bind and Connect operations set the TOS for the socket to the value specified in the provided address. A SocketIpTos tag is only added to the packet if the resulting TOS is non-null. Each packet is assigned the priority set for the socket. Setting a TOS for a socket also sets a priority for the socket (according to the Socket::IpTos2Priority function). A SocketPriority tag is only added to the packet if the priority is non-null.
Congestion state machine
The socket maintains two state machines; the TCP one, and another called "Congestion state machine", which keeps track of the phase we are in. Currently, ns-3 manages the states:
CA_OPEN
CA_DISORDER
CA_RECOVERY
CA_LOSS
CA_CWR
For more information, see the TcpCongState_t documentation.
Congestion control interface
Congestion control, unlike older releases of ns-3, has been split from TcpSocketBase. In particular, each congestion control is now a subclass of the main TcpCongestionOps class. Switching between congestion algorithm is now a matter of setting a pointer into the TcpSocketBase class. The idea and the interfaces are inspired by the Linux operating system, and in particular from the structure tcp_congestion_ops. The reference paper is https://www.sciencedirect.com/science/article/pii/S1569190X15300939.
Transmission Control Block (TCB)
The variables needed to congestion control classes to operate correctly have been moved inside the TcpSocketState class. It contains information on the congestion window, slow start threshold, segment size and the state of the Congestion state machine.
To track the trace inside the TcpSocketState class, a "forward" technique is used, which consists in chaining callbacks from TcpSocketState to TcpSocketBase (see for example cWnd trace source).
Fast retransmit
The fast retransmit enhancement is introduced in RFC 2581 and updated in RFC
It reduces the time a sender waits before retransmitting a lost segment, through the assumption that if it receives a certain number of duplicate ACKs, a segment has been lost and it can be retransmitted. Usually, it is coupled with the Limited Transmit algorithm, defined in RFC 3042. These algorithms are included in this class, and they are implemented inside the ProcessAck method. With the SACK option enabled, the LimitedTransmit algorithm will be always on, as a consequence of how the information in the received SACK block is managed.
The attribute which manages the number of dup ACKs necessary to start the fast retransmit algorithm is named "ReTxThreshold", and by default is 3. The parameter is also used in TcpTxBuffer to determine if a packet is lost (please take a look at TcpTxBuffer documentation to see details) but, right now, it is assumed to be fixed. In future releases this parameter can be made dynamic, to reflect the reordering degree of the network. With SACK, the next sequence to transmit is given by the RFC 6675 algorithm. Without SACK option, the implementation adds "hints" to TcpTxBuffer to make sure it returns, as next transmittable sequence, the first lost (or presumed lost) segment.
Fast recovery
The fast recovery algorithm is introduced RFC 2001, and it avoids to reset cWnd to 1 segment after sensing a loss on the channel. Instead, a new slow start threshold value is asked to the congestion control (for instance, with NewReno the returned amount is half of the previous), and the cWnd is set equal to such value. Ns-3 does not implement any inflation/deflation to the congestion window since it uses an evolved method (borrowed from Linux operating system) to calculate the number of bytes in flight. The fundamental idea is to subtract from the total bytes in flight the lost/sacked amount (the segments that have left the network) and to add the retransmitted count. In this way, congestion window represents the exact number of bytes that should be in flight. The implementation then decides what to transmit, it there is space, between new or already transmitted data portion. If a value of the congestion window with inflation and deflation is needed, there is a traced source named "CongestionWindowInflated". However, the variable behind it is not used in the code, but maintained for backward compatibility.
RTO expiration
When the Retransmission Time Out expires, the TCP faces a significant performance drop. The expiration event is managed in the ReTxTimeout method, which set the cWnd to 1 segment and starts "from scratch" again. The list of sent packet is set as lost entirely, and the transmission is re-started from the SND.UNA sequence number.
Options management
SYN and SYN-ACK options, which are allowed only at the beginning of the connection, are managed in the DoForwardUp and SendEmptyPacket methods. To read all others, we have set up a cycle inside ReadOptions. For adding them, there is no a unique place, since the options (and the information available to build them) are scattered around the code. For instance, the SACK option is built in SendEmptyPacket only under certain conditions.
SACK
The SACK generation/management is delegated to the buffer classes, namely TcpTxBuffer and TcpRxBuffer. In TcpRxBuffer it is managed the creation of the SACK option from the receiver point of view. It must provide an accurate (and efficient) representation of the status of the receiver buffer. On the other side, inside TcpTxBuffer the received options (that contain the SACK block) are processed and a particular data structure, called Scoreboard, is filled. Please take a look at TcpTxBuffer and TcpRxBuffer documentation if you need more information. The reference paper is https://dl.acm.org/citation.cfm?id=3067666.
Config Paths
ns3::TcpSocketBase is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::TcpL4Protocol/SocketList/[i]"
Attributes
MaxSegLifetime: Maximum segment lifetime in seconds, use for TIME_WAIT state transition to CLOSED state
Set with class: ns3::DoubleValue
Underlying type: double 0:1.79769e+308
Initial value: 120
Flags: construct write read
MaxWindowSize: Max size of advertised window
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 65535
Flags: construct write read
IcmpCallback: Callback invoked whenever an icmp error is received on this socket.
Set with class: CallbackValue
Underlying type: Callback
Initial value: 0x0
Flags: construct write read
IcmpCallback6: Callback invoked whenever an icmpv6 error is received on this socket.
Set with class: CallbackValue
Underlying type: Callback
Initial value: 0x0
Flags: construct write read
WindowScaling: Enable or disable Window Scaling option
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
Sack: Enable or disable Sack option
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
Timestamp: Enable or disable Timestamp option
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
MinRto: Minimum retransmit timeout value
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+09ns
Flags: construct write read
ClockGranularity: Clock Granularity used in RTO calculations
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+06ns
Flags: construct write read
TxBuffer: TCP Tx buffer
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::TcpTxBuffer>
Flags: read
RxBuffer: TCP Rx buffer
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::TcpRxBuffer>
Flags: read
CongestionOps: Pointer to TcpCongestionOps object
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::TcpCongestionOps>
Initial value: 0x0
Flags: construct write read
ReTxThreshold: Threshold for fast retransmit
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 3
Flags: construct write read
LimitedTransmit: Enable limited transmit
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
UseEcn: Parameter to set ECN functionality
Set with class: ns3::EnumValue
Underlying type:
Initial value: Off
Flags: construct write
Attributes defined in parent class ns3::TcpSocket
SndBufSize: TcpSocket maximum transmit buffer size (bytes)
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 131072
Flags: construct write read
RcvBufSize: TcpSocket maximum receive buffer size (bytes)
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 131072
Flags: construct write read
SegmentSize: TCP maximum segment size in bytes (may be adjusted based on MTU discovery)
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 536
Flags: construct write read
InitialSlowStartThreshold: TCP initial slow start threshold (bytes)
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 4294967295
Flags: construct write read
InitialCwnd: TCP initial congestion window size (segments)
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 10
Flags: construct write read
ConnTimeout: TCP retransmission timeout when opening connection (seconds)
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +3e+09ns
Flags: construct write read
ConnCount: Number of connection attempts (SYN retransmissions) before returning failure
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 6
Flags: construct write read
DataRetries: Number of data retransmission attempts
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 6
Flags: construct write read
DelAckTimeout: Timeout value for TCP delayed acks, in seconds
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +2e+08ns
Flags: construct write read
DelAckCount: Number of packets to wait before sending a TCP ack
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 2
Flags: construct write read
TcpNoDelay: Set to true to disable Nagle's algorithm
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
PersistTimeout: Persist timeout to probe for rx window
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +6e+09ns
Flags: construct write read
TraceSources
RTO: Retransmission timeout
Callback signature: ns3::TracedValueCallback::Time
RTT: Last RTT sample
Callback signature: ns3::TracedValueCallback::Time
NextTxSequence: Next sequence number to send (SND.NXT)
Callback signature: ns3::SequenceNumber32TracedValueCallback
HighestSequence: Highest sequence number ever sent in socket's life time
Callback signature: ns3::TracedValueCallback::SequenceNumber32
State: TCP state
Callback signature: ns3::TcpStatesTracedValueCallback
CongState: TCP Congestion machine state
Callback signature: ns3::TcpSocketState::TcpCongStatesTracedValueCallback
EcnState: Trace ECN state change of socket
Callback signature: ns3::TcpSocketState::EcnStatesTracedValueCallback
AdvWND: Advertised Window Size
Callback signature: ns3::TracedValueCallback::Uint32
RWND: Remote side's flow control window
Callback signature: ns3::TracedValueCallback::Uint32
BytesInFlight: Socket estimation of bytes in flight
Callback signature: ns3::TracedValueCallback::Uint32
HighestRxSequence: Highest sequence number received from peer
Callback signature: ns3::TracedValueCallback::SequenceNumber32
HighestRxAck: Highest ack received from peer
Callback signature: ns3::TracedValueCallback::SequenceNumber32
PacingRate: The current TCP pacing rate
Callback signature: ns3::TracedValueCallback::DataRate
CongestionWindow: The TCP connection's congestion window
Callback signature: ns3::TracedValueCallback::Uint32
CongestionWindowInflated: The TCP connection's congestion window inflates as in older RFC
Callback signature: ns3::TracedValueCallback::Uint32
SlowStartThreshold: TCP slow start threshold (bytes)
Callback signature: ns3::TracedValueCallback::Uint32
Tx: Send tcp packet to IP protocol
Callback signature: ns3::TcpSocketBase::TcpTxRxTracedCallback
Rx: Receive tcp packet from IP protocol
Callback signature: ns3::TcpSocketBase::TcpTxRxTracedCallback
EcnEchoSeq: Sequence of last received ECN Echo
Callback signature: ns3::SequenceNumber32TracedValueCallback
EcnCeSeq: Sequence of last received CE
Callback signature: ns3::SequenceNumber32TracedValueCallback
EcnCwrSeq: Sequence of last received CWR
Callback signature: ns3::SequenceNumber32TracedValueCallback
Size of this type is 1224 bytes (on a 64-bit architecture).
Definition at line 217 of file tcp-socket-base.h.
Member Typedef Documentation
TcpTxRxTracedCallback
typedef void(* ns3::TcpSocketBase::TcpTxRxTracedCallback) (const Ptr< const Packet > packet, const TcpHeader &header, const Ptr< const TcpSocketBase > socket)
TracedCallback signature for tcp packet transmission or reception events.
Parameters
[in] packet The packet.
[in] header The TcpHeader
[in] socket This socket
Definition at line 603 of file tcp-socket-base.h.
Constructor & Destructor Documentation
TcpSocketBase() [1/2]
ns3::TcpSocketBase::TcpSocketBase (void)
Create an unbound TCP socket.
Definition at line 250 of file tcp-socket-base.cc.
References GetRWnd(), ns3::TcpSocketState::m_maxPacingRate, ns3::TcpSocketState::m_pacingRate, m_pacingTimer, m_rateOps, ns3::TcpSocketState::m_rxBuffer, ns3::TcpSocketState::m_sendEmptyPacketCallback, m_tcb, m_txBuffer, ns3::MakeCallback(), NotifyPacingPerformed(), NS_ASSERT, NS_LOG_FUNCTION, SendEmptyPacket(), ns3::Timer::SetFunction(), ns3::ObjectBase::TraceConnectWithoutContext(), UpdateBytesInFlight(), UpdateCongState(), UpdateCwnd(), UpdateCwndInfl(), UpdateEcnState(), UpdateHighTxMark(), UpdateNextTxSequence(), UpdatePacingRateTrace(), UpdateRtt(), and UpdateSsThresh().
TcpSocketBase() [2/2]
ns3::TcpSocketBase::TcpSocketBase (const TcpSocketBase & sock)
Clone a TCP socket, for use upon receiving a connection request in LISTEN state.
Parameters
sock the original Tcp Socket
Definition at line 309 of file tcp-socket-base.cc.
References ns3::Object::CopyObject, GetRWnd(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_congestionControl, ns3::TcpSocketState::m_maxPacingRate, ns3::TcpSocketState::m_pacingRate, m_pacingTimer, m_rateOps, m_recoveryOps, m_rtt, ns3::TcpSocketState::m_rxBuffer, ns3::TcpSocketState::m_sendEmptyPacketCallback, m_tcb, m_txBuffer, ns3::MakeCallback(), NotifyPacingPerformed(), NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, SendEmptyPacket(), ns3::Socket::SetConnectCallback(), ns3::Socket::SetDataSentCallback(), ns3::Timer::SetFunction(), ns3::Socket::SetRecvCallback(), ns3::Socket::SetSendCallback(), ns3::ObjectBase::TraceConnectWithoutContext(), UpdateBytesInFlight(), UpdateCongState(), UpdateCwnd(), UpdateCwndInfl(), UpdateEcnState(), UpdateHighTxMark(), UpdateNextTxSequence(), UpdatePacingRateTrace(), UpdateRtt(), and UpdateSsThresh().
~TcpSocketBase()
ns3::TcpSocketBase::~TcpSocketBase (void) virtual
Definition at line 443 of file tcp-socket-base.cc.
References CancelAllTimers(), m_endPoint, m_endPoint6, m_node, m_tcp, NS_ASSERT, and NS_LOG_FUNCTION.
Member Function Documentation
AddOptions()
void ns3::TcpSocketBase::AddOptions (TcpHeader & tcpHeader) protected
Add options to TcpHeader.
Test each option, and if it is enabled on our side, add it to the header
Parameters
tcpHeader TcpHeader to add options to
Definition at line 4086 of file tcp-socket-base.cc.
References AddOptionTimestamp(), m_timestampEnabled, and NS_LOG_FUNCTION.
Referenced by DoForwardUp(), PersistTimeout(), SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), SendEmptyPacket(), and ns3::TcpSocketSmallAcks::SendEmptyPacket().
AddOptionSack()
void ns3::TcpSocketBase::AddOptionSack (TcpHeader & header) protected
Add the SACK option to the header.
Parameters
header TcpHeader where the method should add the option
Definition at line 4193 of file tcp-socket-base.cc.
References ns3::TcpHeader::AppendOption(), ns3::Node::GetId(), ns3::TcpHeader::GetMaxOptionLength(), ns3::TcpHeader::GetOptionLength(), m_node, ns3::TcpSocketState::m_rxBuffer, m_tcb, NS_LOG_FUNCTION, NS_LOG_INFO, and NS_LOG_LOGIC.
Referenced by SendEmptyPacket().
AddOptionSackPermitted()
void ns3::TcpSocketBase::AddOptionSackPermitted (TcpHeader & header) protected
Add the SACK PERMITTED option to the header.
Parameters
header TcpHeader where the method should add the option
Definition at line 4182 of file tcp-socket-base.cc.
References ns3::TcpHeader::AppendOption(), ns3::TcpHeader::GetFlags(), ns3::Node::GetId(), m_node, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_INFO, and ns3::TcpHeader::SYN.
Referenced by SendEmptyPacket().
AddOptionTimestamp()
void ns3::TcpSocketBase::AddOptionTimestamp (TcpHeader & header) protected
Add the timestamp option to the header.
Set the timestamp as the lower bits of the Simulator::Now time, and the echo value as the last seen timestamp from the other part.
Parameters
header TcpHeader to which add the option to
Definition at line 4250 of file tcp-socket-base.cc.
References ns3::TcpHeader::AppendOption(), ns3::Node::GetId(), m_node, m_timestampToEcho, ns3::TcpOptionTS::NowToTsValue(), NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by AddOptions().
AddOptionWScale()
void ns3::TcpSocketBase::AddOptionWScale (TcpHeader & header) protected
Add the window scale option to the header.
Calculate our factor from the rxBuffer max size, and add it to the header.
Parameters
header TcpHeader where the method should add the window scale option
Definition at line 4142 of file tcp-socket-base.cc.
References ns3::TcpHeader::AppendOption(), CalculateWScale(), ns3::TcpHeader::GetFlags(), ns3::Node::GetId(), m_node, m_rcvWindShift, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_INFO, and ns3::TcpHeader::SYN.
Referenced by SendEmptyPacket().
AddSocketTags()
void ns3::TcpSocketBase::AddSocketTags (const Ptr< Packet > & p) const protected
Add Tags for the Socket.
Parameters
p Packet
Definition at line 2955 of file tcp-socket-base.cc.
References ns3::Packet::AddPacketTag(), CheckNoEcn(), ns3::TcpSocketState::DctcpEcn, ns3::TcpSocketState::ECN_DISABLED, ns3::Socket::GetIpTos(), ns3::Socket::GetIpTtl(), ns3::Socket::GetIpv6HopLimit(), ns3::Socket::GetIpv6Tclass(), ns3::Socket::GetPriority(), ns3::Packet::GetSize(), ns3::Socket::IsManualIpTtl(), ns3::Socket::IsManualIpv6HopLimit(), ns3::Socket::IsManualIpv6Tclass(), ns3::TcpSocketState::m_ecnMode, ns3::TcpSocketState::m_ecnState, ns3::TcpSocketState::m_ectCodePoint, m_tcb, MarkEcnCodePoint(), ns3::Packet::ReplacePacketTag(), ns3::SocketIpv6HopLimitTag::SetHopLimit(), ns3::SocketPriorityTag::SetPriority(), ns3::SocketIpv6TclassTag::SetTclass(), ns3::SocketIpTosTag::SetTos(), and ns3::SocketIpTtlTag::SetTtl().
Referenced by SendDataPacket(), and SendEmptyPacket().
AdvertisedWindowSize()
uint16_t ns3::TcpSocketBase::AdvertisedWindowSize (bool scale = true) const protected virtual
The amount of Rx window announced to the peer.
Parameters
scale indicate if the window should be scaled. True for almost all cases, except when we are sending a SYN
Returns
size of Rx window announced to the peer
Reimplemented in TcpSocketAdvertisedWindowProxy.
Definition at line 3393 of file tcp-socket-base.cc.
References m_advWnd, m_maxWinSize, m_rcvWindShift, ns3::TcpSocketState::m_rxBuffer, m_tcb, NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, and NS_LOG_WARN.
Referenced by TcpSocketAdvertisedWindowProxy::AdvertisedWindowSize(), DoForwardUp(), PersistTimeout(), SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), SendEmptyPacket(), and ns3::TcpSocketSmallAcks::SendEmptyPacket().
AvailableWindow()
uint32_t ns3::TcpSocketBase::AvailableWindow (void) const protected virtual
Return unfilled portion of window.
Returns
unfilled portion of window
Definition at line 3385 of file tcp-socket-base.cc.
References BytesInFlight(), and Window().
Referenced by Send(), and SendPendingData().
Bind() [1/2]
int ns3::TcpSocketBase::Bind (const Address & address) virtual
Allocate a local endpoint for this socket.
Parameters
address the address to try to allocate
Returns
0 on success, -1 on failure.
Implements ns3::Socket.
Definition at line 549 of file tcp-socket-base.cc.
References first::address, ns3::Inet6SocketAddress::ConvertFrom(), ns3::InetSocketAddress::ConvertFrom(), ns3::Socket::ERROR_ADDRINUSE, ns3::Socket::ERROR_ADDRNOTAVAIL, ns3::Socket::ERROR_INVAL, ns3::Ipv6Address::GetAny(), ns3::Ipv4Address::GetAny(), ns3::Socket::GetBoundNetDevice(), ns3::InetSocketAddress::GetIpv4(), ns3::Inet6SocketAddress::GetIpv6(), ns3::InetSocketAddress::GetPort(), ns3::Inet6SocketAddress::GetPort(), ns3::InetSocketAddress::GetTos(), ns3::Inet6SocketAddress::IsMatchingType(), ns3::InetSocketAddress::IsMatchingType(), m_endPoint, m_endPoint6, m_tcp, NS_LOG_FUNCTION, NS_LOG_LOGIC, port, ns3::Socket::SetIpTos(), and SetupCallback().
Bind() [2/2]
int ns3::TcpSocketBase::Bind (void) virtual
Allocate a local IPv4 endpoint for this socket.
Returns
0 on success, -1 on failure.
Implements ns3::Socket.
Definition at line 516 of file tcp-socket-base.cc.
References ns3::Socket::ERROR_ADDRNOTAVAIL, m_endPoint, m_tcp, NS_LOG_FUNCTION, and SetupCallback().
Referenced by Connect().
Bind6()
int ns3::TcpSocketBase::Bind6 (void) virtual
Allocate a local IPv6 endpoint for this socket.
Returns
0 on success, -1 on failure.
Implements ns3::Socket.
Definition at line 532 of file tcp-socket-base.cc.
References ns3::Socket::ERROR_ADDRNOTAVAIL, m_endPoint6, m_tcp, NS_LOG_FUNCTION, and SetupCallback().
Referenced by Connect().
BindToNetDevice()
void ns3::TcpSocketBase::BindToNetDevice (Ptr< NetDevice > netdevice) virtual
Bind a socket to specific device.
This method corresponds to using setsockopt() SO_BINDTODEVICE of real network or BSD sockets. If set on a socket, this option will force packets to leave the bound device regardless of the device that IP routing would naturally choose. In the receive direction, only packets received from the bound interface will be delivered.
This option has no particular relationship to binding sockets to an address via Socket::Bind (). It is possible to bind sockets to a specific IP address on the bound interface by calling both Socket::Bind (address) and Socket::BindToNetDevice (device), but it is also possible to bind to mismatching device and address, even if the socket can not receive any packets as a result.
Parameters
netdevice Pointer to NetDevice of desired interface
Returns
nothing
Reimplemented from ns3::Socket.
Definition at line 978 of file tcp-socket-base.cc.
References ns3::Ipv4EndPoint::BindToNetDevice(), ns3::Ipv6EndPoint::BindToNetDevice(), ns3::Socket::BindToNetDevice(), m_endPoint, m_endPoint6, and NS_LOG_FUNCTION.
BytesInFlight()
uint32_t ns3::TcpSocketBase::BytesInFlight (void) const protected virtual
Return total bytes in flight.
Does not count segments lost and SACKed (or dupACKed)
Returns
total bytes in flight
Definition at line 3367 of file tcp-socket-base.cc.
References ns3::TcpSocketState::m_bytesInFlight, m_tcb, m_txBuffer, and NS_LOG_DEBUG.
Referenced by AvailableWindow(), EnterCwr(), EnterRecovery(), ProcessAck(), ReceivedAck(), ReTxTimeout(), and SendDataPacket().
CalculateWScale()
uint8_t ns3::TcpSocketBase::CalculateWScale () const protected
Calculate window scale value based on receive buffer space.
Calculate our factor from the rxBuffer max size
Returns
the Window Scale factor
Definition at line 4118 of file tcp-socket-base.cc.
References ns3::Node::GetId(), m_maxWinSize, m_node, ns3::TcpSocketState::m_rxBuffer, m_tcb, NS_LOG_FUNCTION, NS_LOG_INFO, and NS_LOG_WARN.
Referenced by AddOptionWScale().
CancelAllTimers()
void ns3::TcpSocketBase::CancelAllTimers (void) protected
Cancel all timer when endpoint is deleted.
Definition at line 3885 of file tcp-socket-base.cc.
References ns3::EventId::Cancel(), ns3::Timer::Cancel(), m_delAckEvent, m_lastAckEvent, m_pacingTimer, m_persistEvent, m_retxEvent, m_sendPendingDataEvent, and m_timewaitEvent.
Referenced by ~TcpSocketBase(), DeallocateEndPoint(), Destroy(), Destroy6(), and TimeWait().
CheckEcnCe()
bool ns3::TcpSocketBase::CheckEcnCe (uint8_t tos) const inline
Checks for CE codepoint.
Returns
true if TOS has CE codepoint set; otherwise false
Definition at line 538 of file tcp-socket-base.h.
CheckEcnEct0()
bool ns3::TcpSocketBase::CheckEcnEct0 (uint8_t tos) const inline
Checks for ECT(0) codepoint.
Parameters
tos the TOS byte to check
Returns
true if TOS has ECT(0) codepoint set; otherwise false
Definition at line 517 of file tcp-socket-base.h.
CheckEcnEct1()
bool ns3::TcpSocketBase::CheckEcnEct1 (uint8_t tos) const inline
Checks for ECT(1) codepoint.
Parameters
tos the TOS byte to check
Returns
true if TOS has ECT(1) codepoint set; otherwise false
Definition at line 528 of file tcp-socket-base.h.
CheckNoEcn()
bool ns3::TcpSocketBase::CheckNoEcn (uint8_t tos) const inline
Checks if TOS has no ECN codepoints.
Parameters
tos the TOS byte to check
Returns
true if TOS does not have any ECN codepoints set; otherwise false
Definition at line 506 of file tcp-socket-base.h.
Referenced by AddSocketTags().
ClearEcnBits()
uint8_t ns3::TcpSocketBase::ClearEcnBits (uint8_t tos) const inline
Clears ECN bits from TOS.
Parameters
tos the TOS byte to modify
Returns
TOS without ECN bits
Definition at line 495 of file tcp-socket-base.h.
Close()
int ns3::TcpSocketBase::Close (void) virtual
Close a socket.
Returns
zero on success, -1 on failure.
After the Close call, the socket is no longer valid, and cannot safely be used for subsequent operations.
Internal:
First we check to see if there is any unread rx data. Bug 426 claims we should send reset in this case.
Implements ns3::Socket.
Definition at line 746 of file tcp-socket-base.cc.
References DoClose(), m_closeOnEmpty, ns3::TcpSocketState::m_nextTxSequence, ns3::TcpSocketState::m_rxBuffer, m_state, m_tcb, m_txBuffer, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_WARN, SendRST(), and ns3::TcpSocket::TcpStateName.
Referenced by DoPeerClose().
CloseAndNotify()
void ns3::TcpSocketBase::CloseAndNotify (void) protected
Peacefully close the socket by notifying the upper layer and deallocate end point.
Definition at line 1097 of file tcp-socket-base.cc.
References ns3::EventId::Cancel(), ns3::TcpSocket::CLOSED, DeallocateEndPoint(), ns3::EventId::IsRunning(), m_closeNotified, m_lastAckEvent, m_state, ns3::Socket::NotifyNormalClose(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::TcpSocket::TcpStateName.
Referenced by DoClose(), DoConnect(), ProcessClosing(), ProcessEstablished(), ProcessLastAck(), ProcessSynRcvd(), ProcessSynSent(), ProcessWait(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), and TimeWait().
CompleteFork()
void ns3::TcpSocketBase::CompleteFork (Ptr< Packet > p, const TcpHeader & tcpHeader, const Address & fromAddress, const Address & toAddress) protected virtual
Complete a connection by forking the socket.
This function is called only if a SYN received in LISTEN state. After TcpSocketBase cloned, allocate a new end point to handle the incoming connection and send a SYN+ACK to complete the handshake.
Parameters
p the packet triggering the fork
tcpHeader the TCP header of the triggering packet
fromAddress the address of the remote host
toAddress the address the connection is directed to
Reimplemented in ns3::TcpSocketMsgBase.
Definition at line 2888 of file tcp-socket-base.cc.
References ns3::TcpHeader::ACK, ns3::Inet6SocketAddress::ConvertFrom(), ns3::InetSocketAddress::ConvertFrom(), ns3::TcpHeader::CWR, ns3::TcpHeader::ECE, ns3::TcpSocketState::ECN_DISABLED, ns3::TcpSocketState::ECN_IDLE, ns3::TcpSocketState::EcnStateName, ns3::Socket::GetBoundNetDevice(), ns3::TcpHeader::GetFlags(), ns3::TcpHeader::GetSequenceNumber(), ns3::Inet6SocketAddress::IsMatchingType(), ns3::InetSocketAddress::IsMatchingType(), m_dataRetrCount, m_dataRetries, ns3::TcpSocketState::m_ecnState, m_endPoint, m_endPoint6, ns3::TcpSocketState::m_rxBuffer, m_state, m_synCount, m_synRetries, m_tcb, m_tcp, ns3::TcpSocketState::m_useEcn, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_UNUSED, ns3::TcpSocketState::Off, SendEmptyPacket(), SetupCallback(), ns3::TcpHeader::SYN, and ns3::TcpSocket::SYN_RCVD.
Referenced by ns3::TcpSocketMsgBase::CompleteFork(), and ProcessListen().
Connect()
int ns3::TcpSocketBase::Connect (const Address & address) virtual
Initiate a connection to a remote host.
Parameters
address Address of remote.
Returns
0 on success, -1 on error (in which case errno is set).
Implements ns3::Socket.
Definition at line 652 of file tcp-socket-base.cc.
References first::address, Bind(), Bind6(), ns3::Inet6SocketAddress::ConvertFrom(), ns3::InetSocketAddress::ConvertFrom(), DoConnect(), ns3::Socket::ERROR_INVAL, ns3::InetSocketAddress::GetIpv4(), ns3::Ipv6Address::GetIpv4MappedAddress(), ns3::Inet6SocketAddress::GetIpv6(), ns3::InetSocketAddress::GetPort(), ns3::Inet6SocketAddress::GetPort(), ns3::InetSocketAddress::GetTos(), ns3::Ipv6Address::IsIpv4MappedAddress(), ns3::Inet6SocketAddress::IsMatchingType(), ns3::InetSocketAddress::IsMatchingType(), m_dataRetrCount, m_dataRetries, m_endPoint, m_endPoint6, m_rtt, m_synCount, m_synRetries, NS_ASSERT, NS_LOG_ERROR, NS_LOG_FUNCTION, ns3::Socket::SetIpTos(), ns3::Ipv4EndPoint::SetPeer(), ns3::Ipv6EndPoint::SetPeer(), SetupEndpoint(), and SetupEndpoint6().
ConnectionSucceeded()
void ns3::TcpSocketBase::ConnectionSucceeded (void) protected
Schedule-friendly wrapper for Socket::NotifyConnectionSucceeded()
Definition at line 2941 of file tcp-socket-base.cc.
References GetTxAvailable(), ns3::Socket::NotifyConnectionSucceeded(), and ns3::Socket::NotifySend().
Referenced by ProcessSynSent().
DeallocateEndPoint()
void ns3::TcpSocketBase::DeallocateEndPoint (void) protected
Deallocate m_endPoint and m_endPoint6.
Definition at line 2803 of file tcp-socket-base.cc.
References CancelAllTimers(), m_endPoint, m_endPoint6, m_tcp, ns3::Ipv4EndPoint::SetDestroyCallback(), and ns3::Ipv6EndPoint::SetDestroyCallback().
Referenced by CloseAndNotify(), LastAckTimeout(), ReTxTimeout(), SendEmptyPacket(), and SendRST().
DelAckTimeout()
void ns3::TcpSocketBase::DelAckTimeout (void) protected virtual
Action upon delay ACK timeout, i.e.
send an ACK
Definition at line 3756 of file tcp-socket-base.cc.
References ns3::TcpHeader::ACK, ns3::TcpSocketState::CA_EVENT_DELAYED_ACK, ns3::TcpHeader::ECE, ns3::TcpSocketState::ECN_CE_RCVD, ns3::TcpSocketState::ECN_SENDING_ECE, m_congestionControl, m_delAckCount, ns3::TcpSocketState::m_ecnState, m_tcb, and SendEmptyPacket().
Referenced by ReceivedData().
Destroy()
void ns3::TcpSocketBase::Destroy (void) protected
Kill this socket by zeroing its attributes (IPv4)
This is a callback function configured to m_endpoint in SetupCallback(), invoked when the endpoint is destroyed.
Definition at line 2634 of file tcp-socket-base.cc.
References CancelAllTimers(), ns3::Simulator::GetDelayLeft(), m_endPoint, m_retxEvent, m_tcp, ns3::Simulator::Now(), NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by SetupCallback().
Destroy6()
void ns3::TcpSocketBase::Destroy6 (void) protected
Kill this socket by zeroing its attributes (IPv6)
This is a callback function configured to m_endpoint in SetupCallback(), invoked when the endpoint is destroyed.
Definition at line 2650 of file tcp-socket-base.cc.
References CancelAllTimers(), ns3::Simulator::GetDelayLeft(), m_endPoint6, m_retxEvent, m_tcp, ns3::Simulator::Now(), NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by SetupCallback().
DoClose()
int ns3::TcpSocketBase::DoClose (void) protected
Close a socket by sending RST, FIN, or FIN+ACK, depend on the current state.
Returns
0 on success
Definition at line 1055 of file tcp-socket-base.cc.
References ns3::TcpHeader::ACK, ns3::TcpSocket::CLOSE_WAIT, CloseAndNotify(), ns3::TcpSocket::CLOSED, ns3::TcpSocket::CLOSING, ns3::TcpSocket::ESTABLISHED, ns3::TcpHeader::FIN, ns3::TcpSocket::FIN_WAIT_1, ns3::TcpSocket::FIN_WAIT_2, ns3::TcpSocket::LAST_ACK, ns3::TcpSocket::LISTEN, m_state, NS_LOG_DEBUG, NS_LOG_FUNCTION, SendEmptyPacket(), SendRST(), ns3::TcpSocket::SYN_RCVD, ns3::TcpSocket::SYN_SENT, and ns3::TcpSocket::TIME_WAIT.
Referenced by Close().
DoConnect()
int ns3::TcpSocketBase::DoConnect (void) protected
Perform the real connection tasks: Send SYN if allowed, RST if invalid.
Returns
0 on success
Definition at line 1023 of file tcp-socket-base.cc.
References ns3::TcpSocket::CLOSE_WAIT, CloseAndNotify(), ns3::TcpSocket::CLOSED, ns3::TcpHeader::CWR, ns3::TcpHeader::ECE, ns3::TcpSocketState::ECN_DISABLED, ns3::TcpSocket::LAST_ACK, ns3::TcpSocket::LISTEN, ns3::TcpSocketState::m_ecnState, m_state, m_tcb, ns3::TcpSocketState::m_useEcn, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::TcpSocketState::On, SendEmptyPacket(), SendRST(), ns3::TcpHeader::SYN, ns3::TcpSocket::SYN_SENT, ns3::TcpSocket::TcpStateName, and ns3::TcpSocket::TIME_WAIT.
Referenced by Connect().
DoForwardUp()
void ns3::TcpSocketBase::DoForwardUp (Ptr< Packet > packet, const Address & fromAddress, const Address & toAddress) protected virtual
Called by TcpSocketBase::ForwardUp{,6}().
Get a packet from L3. This is the real function to handle the incoming packet from lower layers. This is wrapped by ForwardUp() so that this function can be overloaded by daughter classes.
Parameters
packet the incoming packet
fromAddress the address of the sender of packet
toAddress the address of the receiver of packet (hopefully, us)
Definition at line 1269 of file tcp-socket-base.cc.
References ns3::TcpHeader::ACK, AddOptions(), AdvertisedWindowSize(), ns3::EventId::Cancel(), ns3::TcpSocket::CLOSE_WAIT, ns3::TcpSocket::CLOSED, ns3::TcpSocket::CLOSING, ns3::TcpHeader::CWR, ns3::TcpSocketState::ECN_CE_RCVD, ns3::TcpSocketState::ECN_IDLE, ns3::TcpSocketState::EcnStateName, ns3::TcpSocket::ESTABLISHED, EstimateRtt(), ns3::TcpSocket::FIN_WAIT_1, ns3::TcpSocket::FIN_WAIT_2, ns3::TracedValue< T >::Get(), ns3::TcpHeader::GetAckNumber(), ns3::Simulator::GetDelayLeft(), ns3::TcpHeader::GetDestinationPort(), ns3::TcpHeader::GetFlags(), GetInitialCwnd(), GetInitialSSThresh(), ns3::TcpHeader::GetOption(), GetSegSize(), ns3::TcpHeader::GetSequenceNumber(), ns3::Packet::GetSize(), ns3::TcpHeader::GetSourcePort(), ns3::TcpHeader::GetWindowSize(), ns3::TcpHeader::HasOption(), ns3::EventId::IsExpired(), ns3::EventId::IsRunning(), ns3::TcpSocket::LAST_ACK, ns3::TcpSocket::LISTEN, ns3::Socket::m_boundnetdevice, m_connected, ns3::TcpSocketState::m_cWnd, ns3::TcpSocketState::m_cWndInfl, ns3::TcpSocketState::m_ecnState, m_highRxAckMark, ns3::TcpSocketState::m_nextTxSequence, m_persistEvent, m_persistTimeout, m_retxEvent, m_rWnd, ns3::TcpSocketState::m_rxBuffer, m_rxTrace, m_sackEnabled, ns3::TcpSocketState::m_ssThresh, m_state, m_tcb, m_tcp, m_timestampEnabled, m_txBuffer, m_txTrace, m_winScalingEnabled, ns3::Simulator::Now(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_LOGIC, PersistTimeout(), ProcessClosing(), ProcessEstablished(), ProcessLastAck(), ProcessListen(), ProcessOptionSackPermitted(), ProcessOptionTimestamp(), ProcessOptionWScale(), ProcessSynRcvd(), ProcessSynSent(), ProcessWait(), ns3::TcpHeader::PSH, ns3::Packet::RemoveHeader(), ns3::Packet::RemovePacketTag(), ns3::TcpHeader::RST, ns3::TcpOption::SACKPERMITTED, ns3::Simulator::Schedule(), SendPendingData(), ns3::TcpHeader::SetAckNumber(), ns3::TcpHeader::SetDestinationPort(), ns3::TcpHeader::SetFlags(), ns3::TcpHeader::SetSequenceNumber(), ns3::TcpHeader::SetSourcePort(), ns3::TcpHeader::SetWindowSize(), ns3::TcpHeader::SYN, ns3::TcpSocket::SYN_RCVD, ns3::TcpSocket::SYN_SENT, ns3::TcpSocket::TcpStateName, ns3::TcpSocket::TIME_WAIT, ns3::TcpOption::TS, UpdateWindowSize(), ns3::TcpHeader::URG, and ns3::TcpOption::WINSCALE.
Referenced by ForwardUp(), and ForwardUp6().
DoPeerClose()
void ns3::TcpSocketBase::DoPeerClose (void) protected
FIN is in sequence, notify app and respond with a FIN.
Definition at line 2593 of file tcp-socket-base.cc.
References ns3::TcpHeader::ACK, Close(), ns3::TcpSocket::CLOSE_WAIT, ns3::TcpSocket::ESTABLISHED, ns3::TcpSocket::FIN_WAIT_1, ns3::TcpSocket::FIN_WAIT_2, ns3::TcpSocket::LAST_ACK, LastAckTimeout(), m_clockGranularity, m_closeNotified, m_dataRetrCount, m_dataRetries, m_lastAckEvent, m_rtt, m_shutdownSend, m_state, ns3::Max(), ns3::Socket::NotifyNormalClose(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_LOGIC, ns3::Simulator::Schedule(), SendEmptyPacket(), ns3::TcpSocket::SYN_RCVD, and ns3::TcpSocket::TcpStateName.
Referenced by PeerClose(), and ReceivedData().
DoRetransmit()
void ns3::TcpSocketBase::DoRetransmit (void) protected
Retransmit the first segment marked as lost, without considering available window nor pacing.
Definition at line 3850 of file tcp-socket-base.cc.
References ns3::TcpSocketState::m_nextTxSequence, m_sackEnabled, ns3::TcpSocketState::m_segmentSize, m_tcb, m_txBuffer, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_INFO, and SendDataPacket().
Referenced by EnterRecovery(), and ProcessAck().
DupAck()
void ns3::TcpSocketBase::DupAck (uint32_t currentDelivered) protected
Dupack management.
Parameters
currentDelivered Current (S)ACKed bytes
Definition at line 1659 of file tcp-socket-base.cc.
References ns3::TcpSocketState::CA_DISORDER, ns3::TcpSocketState::CA_LOSS, ns3::TcpSocketState::CA_OPEN, ns3::TcpSocketState::CA_RECOVERY, EnterRecovery(), m_congestionControl, ns3::TcpSocketState::m_congState, ns3::TcpSocketState::m_cWnd, m_dupAckCount, m_highRxAckMark, m_limitedTx, m_recover, m_recoverActive, m_recoveryOps, m_retxThresh, m_sackEnabled, ns3::TcpSocketState::m_segmentSize, m_tcb, m_txBuffer, NS_ASSERT, NS_ASSERT_MSG, NS_LOG_DEBUG, NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by ProcessAck().
EnterCwr()
void ns3::TcpSocketBase::EnterCwr (uint32_t currentDelivered) protected
Enter CA_CWR state upon receipt of an ECN Echo.
Parameters
currentDelivered Currently (S)ACKed bytes
Definition at line 1574 of file tcp-socket-base.cc.
References BytesInFlight(), ns3::TcpSocketState::CA_CWR, m_congestionControl, ns3::TcpSocketState::m_congState, ns3::TcpSocketState::m_cWnd, ns3::TcpSocketState::m_cWndInfl, m_dupAckCount, ns3::TcpSocketState::m_highTxMark, m_recover, m_recoveryOps, ns3::TcpSocketState::m_ssThresh, m_tcb, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::TcpSocketState::TcpCongStateName, and UnAckDataCount().
Referenced by ReceivedAck().
EnterRecovery()
void ns3::TcpSocketBase::EnterRecovery (uint32_t currentDelivered) protected
Enter the CA_RECOVERY, and retransmit the head.
Parameters
currentDelivered Currently (S)ACKed bytes
Definition at line 1601 of file tcp-socket-base.cc.
References BytesInFlight(), ns3::TcpSocketState::CA_RECOVERY, DoRetransmit(), m_congestionControl, ns3::TcpSocketState::m_congState, ns3::TcpSocketState::m_cWnd, m_dupAckCount, ns3::TcpSocketState::m_highTxMark, m_recover, m_recoverActive, m_recoveryOps, m_sackEnabled, ns3::TcpSocketState::m_segmentSize, ns3::TcpSocketState::m_ssThresh, m_tcb, m_txBuffer, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::TcpSocketState::TcpCongStateName, and UnAckDataCount().
Referenced by DupAck().
EstimateRtt()
void ns3::TcpSocketBase::EstimateRtt (const TcpHeader & tcpHeader) protected virtual
Take into account the packet for RTT estimation.
Estimate the RTT.
Parameters
tcpHeader the packet's TCP header
Called by ForwardUp() to estimate RTT.
Parameters
tcpHeader TCP header for the incoming packet
Definition at line 3531 of file tcp-socket-base.cc.
References ns3::RttHistory::count, ns3::TcpOptionTS::ElapsedTimeFromTsValue(), ns3::TracedValue< T >::Get(), ns3::TcpHeader::GetAckNumber(), ns3::TcpHeader::GetOption(), ns3::TcpHeader::HasOption(), ns3::Time::IsZero(), m_clockGranularity, m_history, ns3::TcpSocketState::m_lastRtt, m_minRto, ns3::TcpSocketState::m_minRtt, m_rto, m_rtt, m_tcb, m_timestampEnabled, ns3::Max(), min, ns3::Simulator::Now(), NS_LOG_INFO, ns3::RttHistory::retx, ns3::RttHistory::seq, ns3::RttHistory::time, and ns3::TcpOption::TS.
Referenced by DoForwardUp().
Fork()
Ptr< TcpSocketBase > ns3::TcpSocketBase::Fork (void) protected virtual
Call CopyObject<> to clone me.
Returns
a copy of the socket
Reimplemented in ns3::TcpSocketSmallAcks, ns3::TcpSocketMsgBase, ns3::TcpSocketCongestedRouter, TcpDctcpCongestedRouter, TcpSocketHalfAck, and TcpSocketAdvertisedWindowProxy.
Definition at line 4433 of file tcp-socket-base.cc.
Referenced by ProcessListen().
ForwardIcmp()
void ns3::TcpSocketBase::ForwardIcmp (Ipv4Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo) protected
Called by the L3 protocol when it received an ICMP packet to pass on to TCP.
Parameters
icmpSource the ICMP source address
icmpTtl the ICMP Time to Live
icmpType the ICMP Type
icmpCode the ICMP Code
icmpInfo the ICMP Info
Definition at line 1217 of file tcp-socket-base.cc.
References m_icmpCallback, and NS_LOG_FUNCTION.
Referenced by SetupCallback().
ForwardIcmp6()
void ns3::TcpSocketBase::ForwardIcmp6 (Ipv6Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo) protected
Called by the L3 protocol when it received an ICMPv6 packet to pass on to TCP.
Parameters
icmpSource the ICMP source address
icmpTtl the ICMP Time to Live
icmpType the ICMP Type
icmpCode the ICMP Code
icmpInfo the ICMP Info
Definition at line 1231 of file tcp-socket-base.cc.
References m_icmpCallback6, and NS_LOG_FUNCTION.
Referenced by SetupCallback().
ForwardUp()
void ns3::TcpSocketBase::ForwardUp (Ptr< Packet > packet, Ipv4Header header, uint16_t port, Ptr< Ipv4Interface > incomingInterface) protected
Called by the L3 protocol when it received a packet to pass on to TCP.
Parameters
packet the incoming packet
header the packet's IPv4 header
port the remote port
incomingInterface the incoming interface
Definition at line 1139 of file tcp-socket-base.cc.
References ns3::TcpSocketState::CA_EVENT_ECN_IS_CE, ns3::TcpSocketState::CA_EVENT_ECN_NO_CE, DoForwardUp(), ns3::Ipv4Header::ECN_CE, ns3::TcpSocketState::ECN_CE_RCVD, ns3::TcpSocketState::ECN_DISABLED, ns3::Ipv4Header::ECN_NotECT, ns3::TcpSocketState::EcnStateName, ns3::Ipv4Header::GetDestination(), ns3::Ipv4Header::GetEcn(), ns3::Ipv4EndPoint::GetLocalAddress(), ns3::Ipv4EndPoint::GetLocalPort(), ns3::Ipv4EndPoint::GetPeerAddress(), ns3::Ipv4EndPoint::GetPeerPort(), ns3::TcpHeader::GetSequenceNumber(), ns3::Packet::GetSize(), ns3::Ipv4Header::GetSource(), IsValidTcpSegment(), m_congestionControl, m_ecnCESeq, ns3::TcpSocketState::m_ecnState, m_endPoint, m_tcb, NS_LOG_DEBUG, NS_LOG_INFO, NS_LOG_LOGIC, ns3::Packet::PeekHeader(), and port.
Referenced by SetupCallback().
ForwardUp6()
void ns3::TcpSocketBase::ForwardUp6 (Ptr< Packet > packet, Ipv6Header header, uint16_t port, Ptr< Ipv6Interface > incomingInterface) protected
Called by the L3 protocol when it received a packet to pass on to TCP.
Parameters
packet the incoming packet
header the packet's IPv6 header
port the remote port
incomingInterface the incoming interface
Definition at line 1178 of file tcp-socket-base.cc.
References ns3::TcpSocketState::CA_EVENT_ECN_IS_CE, ns3::TcpSocketState::CA_EVENT_ECN_NO_CE, DoForwardUp(), ns3::Ipv6Header::ECN_CE, ns3::TcpSocketState::ECN_CE_RCVD, ns3::Ipv6Header::ECN_NotECT, ns3::TcpSocketState::EcnStateName, ns3::Ipv6Header::GetDestinationAddress(), ns3::Ipv6Header::GetEcn(), ns3::Ipv6EndPoint::GetLocalAddress(), ns3::Ipv6EndPoint::GetLocalPort(), ns3::Ipv6EndPoint::GetPeerAddress(), ns3::Ipv6EndPoint::GetPeerPort(), ns3::TcpHeader::GetSequenceNumber(), ns3::Packet::GetSize(), ns3::Ipv6Header::GetSourceAddress(), IsValidTcpSegment(), m_congestionControl, m_ecnCESeq, ns3::TcpSocketState::m_ecnState, m_endPoint6, m_tcb, NS_LOG_DEBUG, NS_LOG_INFO, NS_LOG_LOGIC, ns3::Packet::PeekHeader(), and port.
Referenced by SetupCallback().
GetAllowBroadcast()
bool ns3::TcpSocketBase::GetAllowBroadcast (void) const protected virtual
Query whether broadcast datagram transmissions are allowed.
This method corresponds to using getsockopt() SO_BROADCAST of real network or BSD sockets.
Returns
true if broadcast is allowed, false otherwise
Implements ns3::Socket.
Definition at line 4080 of file tcp-socket-base.cc.
GetClockGranularity()
Time ns3::TcpSocketBase::GetClockGranularity (void) const
Get the Clock Granularity (used in RTO calcs).
Returns
The Clock Granularity.
Definition at line 4329 of file tcp-socket-base.cc.
References m_clockGranularity.
Referenced by GetTypeId().
GetConnTimeout()
Time ns3::TcpSocketBase::GetConnTimeout (void) const protected virtual
Get the connection timeout.
Returns
the connection timeout
Implements ns3::TcpSocket.
Definition at line 3988 of file tcp-socket-base.cc.
References m_cnTimeout.
GetDataRetries()
uint32_t ns3::TcpSocketBase::GetDataRetries (void) const protected virtual
Get the number of data transmission retries before giving up.
Returns
the number of data transmission retries
Implements ns3::TcpSocket.
Definition at line 4014 of file tcp-socket-base.cc.
References m_dataRetries, and NS_LOG_FUNCTION.
GetDelAckMaxCount()
uint32_t ns3::TcpSocketBase::GetDelAckMaxCount (void) const protected virtual
Get the number of packet to fire an ACK before delay timeout.
Returns
the number of packet to fire an ACK before delay timeout
Implements ns3::TcpSocket.
Definition at line 4041 of file tcp-socket-base.cc.
References m_delAckMaxCount.
GetDelAckTimeout()
Time ns3::TcpSocketBase::GetDelAckTimeout (void) const protected virtual
Get the time to delay an ACK.
Returns
the time to delay an ACK
Implements ns3::TcpSocket.
Definition at line 4028 of file tcp-socket-base.cc.
References m_delAckTimeout.
GetErrno()
enum Socket::SocketErrno ns3::TcpSocketBase::GetErrno (void) const virtual
Get last error number.
Returns
the errno associated to the last call which failed in this socket. Each socket's errno is initialized to zero when the socket is created.
Implements ns3::Socket.
Definition at line 488 of file tcp-socket-base.cc.
References m_rtt.
GetHighRxAck()
SequenceNumber32 ns3::TcpSocketBase::GetHighRxAck (void) const protected
Get the current value of the receiver's highest (in-sequence) sequence number acked.
Note
This method exists to expose the value to the TcpTxBuffer
Returns
value of receiver's highest sequence number acked.
Definition at line 4554 of file tcp-socket-base.cc.
References ns3::TracedValue< T >::Get(), and m_highRxAckMark.
GetInitialCwnd()
uint32_t ns3::TcpSocketBase::GetInitialCwnd (void) const protected virtual
Get the initial Congestion Window.
Returns
the initial congestion window (in segments)
Implements ns3::TcpSocket.
Definition at line 645 of file tcp-socket-base.cc.
References ns3::TcpSocketState::m_initialCWnd, and m_tcb.
Referenced by DoForwardUp(), and IsPacingEnabled().
GetInitialSSThresh()
uint32_t ns3::TcpSocketBase::GetInitialSSThresh (void) const protected virtual
Get the initial Slow Start Threshold.
Returns
the Slow Start Threshold (in bytes)
Implements ns3::TcpSocket.
Definition at line 630 of file tcp-socket-base.cc.
References ns3::TcpSocketState::m_initialSsThresh, and m_tcb.
Referenced by DoForwardUp().
GetInstanceTypeId()
TypeId ns3::TcpSocketBase::GetInstanceTypeId (void) const virtual
Get the instance TypeId.
Returns
the instance TypeId
Reimplemented from ns3::Object.
Definition at line 245 of file tcp-socket-base.cc.
References GetTypeId().
GetMinRto()
Time ns3::TcpSocketBase::GetMinRto (void) const
Get the Minimum RTO.
Returns
The minimum RTO.
Definition at line 4316 of file tcp-socket-base.cc.
References m_minRto.
Referenced by GetTypeId().
GetNode()
Ptr< Node > ns3::TcpSocketBase::GetNode (void) const virtual
Return the node this socket is associated with.
Returns
the node
Implements ns3::Socket.
Definition at line 509 of file tcp-socket-base.cc.
References m_node.
GetPeerName()
int ns3::TcpSocketBase::GetPeerName (Address & address) const virtual
Get the peer address of a connected socket.
Parameters
address the address this socket is connected to.
Returns
0 if success, -1 otherwise
Implements ns3::Socket.
Definition at line 948 of file tcp-socket-base.cc.
References first::address, ns3::Socket::ERROR_NOTCONN, ns3::Ipv6EndPoint::GetPeerAddress(), ns3::Ipv4EndPoint::GetPeerAddress(), ns3::Ipv6EndPoint::GetPeerPort(), ns3::Ipv4EndPoint::GetPeerPort(), m_endPoint, m_endPoint6, NS_ASSERT, and NS_LOG_FUNCTION.
GetPersistTimeout()
Time ns3::TcpSocketBase::GetPersistTimeout (void) const protected virtual
Get the timeout for persistent connection.
When the timeout expires, send 1-byte data to probe for the window size at the receiver when the local knowledge tells that the receiver has zero window size
Returns
the persistent timeout
Implements ns3::TcpSocket.
Definition at line 4067 of file tcp-socket-base.cc.
References m_persistTimeout.
GetRcvBufSize()
uint32_t ns3::TcpSocketBase::GetRcvBufSize (void) const protected virtual
Get the receive buffer size.
Returns
the buffer size (in bytes)
Implements ns3::TcpSocket.
Definition at line 3959 of file tcp-socket-base.cc.
References ns3::TcpSocketState::m_rxBuffer, and m_tcb.
Referenced by SetRcvBufSize().
GetRetxThresh()
uint32_t ns3::TcpSocketBase::GetRetxThresh (void) const inline
Get the retransmission threshold (dup ack threshold for a fast retransmit)
Returns
the threshold
Definition at line 318 of file tcp-socket-base.h.
References m_retxThresh.
Referenced by GetTypeId().
GetRWnd()
uint32_t ns3::TcpSocketBase::GetRWnd (void) const protected
Get the current value of the receiver's offered window (RCV.WND)
Note
This method exists to expose the value to the TcpTxBuffer
Returns
value of receiver's offered window
Definition at line 4548 of file tcp-socket-base.cc.
References ns3::TracedValue< T >::Get(), and m_rWnd.
Referenced by TcpSocketBase().
GetRxAvailable()
uint32_t ns3::TcpSocketBase::GetRxAvailable (void) const virtual
Return number of bytes which can be returned from one or multiple calls to Recv.
Must be possible to call this method from the Recv callback.
Returns
the number of bytes which can be returned from one or multiple Recv calls.
Implements ns3::Socket.
Definition at line 919 of file tcp-socket-base.cc.
References ns3::TcpSocketState::m_rxBuffer, m_tcb, and NS_LOG_FUNCTION.
GetRxBuffer()
Ptr< TcpRxBuffer > ns3::TcpSocketBase::GetRxBuffer (void) const
Get a pointer to the Rx buffer.
Returns
a pointer to the rx buffer
Definition at line 4341 of file tcp-socket-base.cc.
References ns3::TcpSocketState::m_rxBuffer, and m_tcb.
Referenced by GetTypeId().
GetSegSize()
uint32_t ns3::TcpSocketBase::GetSegSize (void) const protected virtual
Get the segment size.
Returns
the segment size (in bytes)
Implements ns3::TcpSocket.
Definition at line 3975 of file tcp-socket-base.cc.
References ns3::TcpSocketState::m_segmentSize, and m_tcb.
Referenced by DoForwardUp().
GetSndBufSize()
uint32_t ns3::TcpSocketBase::GetSndBufSize (void) const protected virtual
Get the send buffer size.
Returns
the buffer size (in bytes)
Implements ns3::TcpSocket.
Definition at line 3927 of file tcp-socket-base.cc.
References m_txBuffer.
GetSocketType()
enum Socket::SocketType ns3::TcpSocketBase::GetSocketType (void) const virtual
Returns
the socket type, analogous to getsockopt (SO_TYPE)
Implements ns3::Socket.
Definition at line 488 of file tcp-socket-base.cc.
GetSockName()
int ns3::TcpSocketBase::GetSockName (Address & address) const virtual
Get socket address.
Parameters
address the address name this socket is associated with.
Returns
0 if success, -1 otherwise
Implements ns3::Socket.
Definition at line 927 of file tcp-socket-base.cc.
References first::address, ns3::Ipv6EndPoint::GetLocalAddress(), ns3::Ipv4EndPoint::GetLocalAddress(), ns3::Ipv6EndPoint::GetLocalPort(), ns3::Ipv4EndPoint::GetLocalPort(), ns3::Ipv4Address::GetZero(), m_endPoint, m_endPoint6, and NS_LOG_FUNCTION.
GetSynRetries()
uint32_t ns3::TcpSocketBase::GetSynRetries (void) const protected virtual
Get the number of connection retries before giving up.
Returns
the number of connection retries
Implements ns3::TcpSocket.
Definition at line 4001 of file tcp-socket-base.cc.
References m_synRetries.
GetTcpNoDelay()
bool ns3::TcpSocketBase::GetTcpNoDelay (void) const protected virtual
Check if Nagle's algorithm is enabled or not.
Returns
true if Nagle's algorithm is DISABLED
Implements ns3::TcpSocket.
Definition at line 4054 of file tcp-socket-base.cc.
References m_noDelay.
GetTxAvailable()
uint32_t ns3::TcpSocketBase::GetTxAvailable (void) const virtual
Returns the number of bytes which can be sent in a single call to Send.
For datagram sockets, this returns the number of bytes that can be passed atomically through the underlying protocol.
For stream sockets, this returns the available space in bytes left in the transmit buffer.
Returns
The number of bytes which can be sent in a single Send call.
Implements ns3::Socket.
Definition at line 911 of file tcp-socket-base.cc.
References m_txBuffer, and NS_LOG_FUNCTION.
Referenced by ConnectionSucceeded(), NewAck(), ProcessSynRcvd(), and SendPendingData().
GetTxBuffer()
Ptr< TcpTxBuffer > ns3::TcpSocketBase::GetTxBuffer (void) const
Get a pointer to the Tx buffer.
Returns
a pointer to the tx buffer
Definition at line 4335 of file tcp-socket-base.cc.
References m_txBuffer.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::TcpSocketBase::GetTypeId (void) static
Get the type ID.
Get the type ID.
Returns
the object TypeId
Definition at line 73 of file tcp-socket-base.cc.
References ns3::TcpSocketState::AcceptOnly, GetClockGranularity(), GetMinRto(), GetRetxThresh(), GetRxBuffer(), GetTxBuffer(), m_advWnd, m_bytesInFlightTrace, m_congestionControl, m_congStateTrace, m_cWndInflTrace, m_cWndTrace, m_ecnCESeq, m_ecnCWRSeq, m_ecnEchoSeq, m_ecnStateTrace, m_highRxAckMark, m_highRxMark, m_highTxMarkTrace, m_icmpCallback, m_icmpCallback6, m_lastRttTrace, m_limitedTx, m_maxWinSize, m_msl, m_nextTxSequenceTrace, m_pacingRateTrace, m_rto, m_rWnd, m_rxTrace, m_sackEnabled, m_ssThTrace, m_state, m_timestampEnabled, m_txTrace, m_winScalingEnabled, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeCallbackAccessor(), ns3::MakeCallbackChecker(), ns3::MakeDoubleAccessor(), ns3::MakeEnumAccessor(), ns3::MakeEnumChecker(), ns3::MakePointerAccessor(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), ns3::MilliSeconds(), ns3::TcpSocketState::Off, ns3::TcpSocketState::On, ns3::Seconds(), SetClockGranularity(), SetMinRto(), ns3::TypeId::SetParent(), SetRetxThresh(), and SetUseEcn().
Referenced by GetInstanceTypeId().
IsPacingEnabled()
bool ns3::TcpSocketBase::IsPacingEnabled (void) const protected
Return true if packets in the current window should be paced.
Returns
true if pacing is currently enabled
Definition at line 4458 of file tcp-socket-base.cc.
References GetInitialCwnd(), ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::GetValue(), ns3::TcpSocketState::m_highTxMark, ns3::TcpSocketState::m_paceInitialWindow, ns3::TcpSocketState::m_pacing, ns3::TcpSocketState::m_segmentSize, and m_tcb.
Referenced by SendDataPacket(), and SendPendingData().
IsTcpOptionEnabled()
bool ns3::TcpSocketBase::IsTcpOptionEnabled (uint8_t kind) const protected
Return true if the specified option is enabled.
Parameters
kind kind of TCP option
Returns
true if the option is enabled
Definition at line 1529 of file tcp-socket-base.cc.
References m_sackEnabled, m_timestampEnabled, m_winScalingEnabled, NS_LOG_FUNCTION, ns3::TcpOption::SACK, ns3::TcpOption::SACKPERMITTED, ns3::TcpOption::TS, and ns3::TcpOption::WINSCALE.
IsValidTcpSegment()
bool ns3::TcpSocketBase::IsValidTcpSegment (const SequenceNumber32 seq, const uint32_t tcpHeaderSize, const uint32_t tcpPayloadSize) protected
Checks whether the given TCP segment is valid or not.
Parameters
seq the sequence number of packet's TCP header
tcpHeaderSize the size of packet's TCP header
tcpPayloadSize the size of TCP payload
Definition at line 1245 of file tcp-socket-base.cc.
References ns3::TcpHeader::ACK, ns3::TcpSocketState::m_rxBuffer, m_state, m_tcb, NS_LOG_ERROR, NS_LOG_WARN, OutOfRange(), SendEmptyPacket(), and ns3::TcpSocket::TcpStateName.
Referenced by ForwardUp(), and ForwardUp6().
LastAckTimeout()
void ns3::TcpSocketBase::LastAckTimeout (void) protected virtual
Timeout at LAST_ACK, close the connection.
Definition at line 3772 of file tcp-socket-base.cc.
References ns3::TcpHeader::ACK, ns3::EventId::Cancel(), DeallocateEndPoint(), ns3::TcpHeader::FIN, ns3::TcpSocket::LAST_ACK, m_clockGranularity, m_dataRetrCount, m_lastAckEvent, m_rtt, m_state, ns3::Max(), ns3::Socket::NotifyErrorClose(), NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, ns3::Simulator::Schedule(), and SendEmptyPacket().
Referenced by DoPeerClose().
Listen()
int ns3::TcpSocketBase::Listen (void) virtual
Listen for incoming connections.
Returns
0 on success, -1 on error (in which case errno is set).
Implements ns3::Socket.
Definition at line 728 of file tcp-socket-base.cc.
References ns3::TcpSocket::CLOSED, ns3::Socket::ERROR_INVAL, ns3::TcpSocket::LISTEN, m_state, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
MarkEcnCe()
uint8_t ns3::TcpSocketBase::MarkEcnCe (uint8_t tos) const inline
Mark CE codepoint.
Parameters
tos the TOS byte to modify
Returns
TOS with CE codepoint set
Definition at line 484 of file tcp-socket-base.h.
Referenced by ns3::TcpSocketCongestedRouter::SendDataPacket().
MarkEcnCodePoint()
uint8_t ns3::TcpSocketBase::MarkEcnCodePoint (const uint8_t tos, const TcpSocketState::EcnCodePoint_t codePoint) const inline
mark ECN code point
Parameters
tos the TOS byte to modify
codePoint the codepoint to use
Returns
TOS with specified ECN code point
Definition at line 550 of file tcp-socket-base.h.
Referenced by AddSocketTags(), and PersistTimeout().
MarkEcnEct0()
uint8_t ns3::TcpSocketBase::MarkEcnEct0 (uint8_t tos) const inline
Mark ECT(0) codepoint.
Parameters
tos the TOS byte to modify
Returns
TOS with ECT(0) codepoint set
Definition at line 462 of file tcp-socket-base.h.
Referenced by ns3::TcpSocketCongestedRouter::SendDataPacket().
MarkEcnEct1()
uint8_t ns3::TcpSocketBase::MarkEcnEct1 (uint8_t tos) const inline
Mark ECT(1) codepoint.
Parameters
tos the TOS byte to modify
Returns
TOS with ECT(1) codepoint set
Definition at line 473 of file tcp-socket-base.h.
NewAck()
void ns3::TcpSocketBase::NewAck (SequenceNumber32 const & seq, bool resetRTO) protected virtual
Update buffers w.r.t.
ACK
Parameters
seq the sequence number
resetRTO indicates if RTO should be reset
Definition at line 3583 of file tcp-socket-base.cc.
References ns3::EventId::Cancel(), ns3::TcpSocket::CLOSING, ns3::TcpSocket::FIN_WAIT_1, ns3::TracedValue< T >::Get(), ns3::Simulator::GetDelayLeft(), ns3::Time::GetSeconds(), GetTxAvailable(), m_clockGranularity, m_dataRetrCount, m_dataRetries, m_minRto, ns3::TcpSocketState::m_nextTxSequence, m_retxEvent, m_rto, m_rtt, m_state, m_tcb, m_txBuffer, ns3::Max(), ns3::Socket::NotifySend(), ns3::Simulator::Now(), NS_LOG_FUNCTION, NS_LOG_LOGIC, ReTxTimeout(), ns3::Simulator::Schedule(), and ns3::TcpSocket::SYN_RCVD.
Referenced by ProcessAck().
NotifyPacingPerformed()
void ns3::TcpSocketBase::NotifyPacingPerformed (void) protected
Notify Pacing.
Definition at line 4450 of file tcp-socket-base.cc.
References m_connected, NS_LOG_FUNCTION, NS_LOG_INFO, and SendPendingData().
Referenced by TcpSocketBase().
OutOfRange()
bool ns3::TcpSocketBase::OutOfRange (SequenceNumber32 head, SequenceNumber32 tail) const protected
Check if a sequence number range is within the rx window.
Parameters
head start of the Sequence window
tail end of the Sequence window
Returns
true if it is in range
Definition at line 1119 of file tcp-socket-base.cc.
References ns3::TcpSocket::CLOSE_WAIT, ns3::TcpSocket::CLOSING, ns3::TcpSocket::LAST_ACK, ns3::TcpSocket::LISTEN, ns3::TcpSocketState::m_rxBuffer, m_state, m_tcb, ns3::TcpSocket::SYN_RCVD, and ns3::TcpSocket::SYN_SENT.
Referenced by IsValidTcpSegment().
PeerClose()
void ns3::TcpSocketBase::PeerClose (Ptr< Packet > p, const TcpHeader & tcpHeader) protected
Received a FIN from peer, notify rx buffer.
Parameters
p the packet
tcpHeader the packet's TCP header
Definition at line 2556 of file tcp-socket-base.cc.
References ns3::TcpSocket::CLOSING, DoPeerClose(), ns3::TcpSocket::FIN_WAIT_1, ns3::TcpHeader::GetSequenceNumber(), ns3::Packet::GetSize(), ns3::TcpSocketState::m_rxBuffer, m_state, m_tcb, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, and ReceivedData().
Referenced by ProcessEstablished(), and ProcessSynRcvd().
PersistTimeout()
void ns3::TcpSocketBase::PersistTimeout (void) protected virtual
Send 1 byte probe to get an updated window size.
Definition at line 3798 of file tcp-socket-base.cc.
References AddOptions(), ns3::Packet::AddPacketTag(), AdvertisedWindowSize(), ns3::TcpSocketState::ECN_DISABLED, ns3::Ipv6EndPoint::GetLocalAddress(), ns3::Ipv4EndPoint::GetLocalAddress(), ns3::Ipv6EndPoint::GetLocalPort(), ns3::Ipv4EndPoint::GetLocalPort(), ns3::Ipv6EndPoint::GetPeerAddress(), ns3::Ipv4EndPoint::GetPeerAddress(), ns3::Ipv6EndPoint::GetPeerPort(), ns3::Ipv4EndPoint::GetPeerPort(), ns3::Socket::m_boundnetdevice, ns3::TcpSocketState::m_ecnState, ns3::TcpSocketState::m_ectCodePoint, m_endPoint, m_endPoint6, ns3::TcpSocketState::m_nextTxSequence, m_persistEvent, m_persistTimeout, ns3::TcpSocketState::m_rxBuffer, m_tcb, m_tcp, m_txBuffer, m_txTrace, MarkEcnCodePoint(), min, ns3::Simulator::Now(), NS_LOG_LOGIC, ns3::Simulator::Schedule(), ns3::Seconds(), ns3::TcpHeader::SetAckNumber(), ns3::TcpHeader::SetDestinationPort(), ns3::TcpHeader::SetSequenceNumber(), ns3::TcpHeader::SetSourcePort(), ns3::SocketIpv6TclassTag::SetTclass(), ns3::SocketIpTosTag::SetTos(), and ns3::TcpHeader::SetWindowSize().
Referenced by DoForwardUp().
ProcessAck()
void ns3::TcpSocketBase::ProcessAck (const SequenceNumber32 & ackNumber, bool scoreboardUpdated, uint32_t currentDelivered, const SequenceNumber32 & oldHeadSequence) protected virtual
Process a received ack.
Parameters
ackNumber ack number
scoreboardUpdated if true indicates that the scoreboard has been
oldHeadSequence value of HeadSequence before ack updated with SACK information
currentDelivered The number of bytes (S)ACKed
Returns
the number of bytes (newly) acked, or 0 if it was a dupack
Definition at line 1881 of file tcp-socket-base.cc.
References BytesInFlight(), ns3::TcpSocketState::CA_CWR, ns3::TcpSocketState::CA_DISORDER, ns3::TcpSocketState::CA_EVENT_COMPLETE_CWR, ns3::TcpSocketState::CA_LOSS, ns3::TcpSocketState::CA_OPEN, ns3::TcpSocketState::CA_RECOVERY, DoRetransmit(), DupAck(), ns3::TracedValue< T >::Get(), m_bytesAckedNotProcessed, m_congestionControl, ns3::TcpSocketState::m_congState, ns3::TcpSocketState::m_cWnd, ns3::TcpSocketState::m_cWndInfl, m_dupAckCount, ns3::TcpSocketState::m_highTxMark, m_isFirstPartialAck, ns3::TcpSocketState::m_lastAckedSeq, ns3::TcpSocketState::m_lastRtt, ns3::TcpSocketState::m_nextTxSequence, m_recover, m_recoverActive, m_recoveryOps, m_sackEnabled, ns3::TcpSocketState::m_segmentSize, ns3::TcpSocketState::m_ssThresh, m_tcb, m_txBuffer, NewAck(), NS_ASSERT_MSG, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, SafeSubtraction(), ns3::TcpSocketState::TcpCongStateName, and UpdatePacingRate().
Referenced by ReceivedAck().
ProcessClosing()
void ns3::TcpSocketBase::ProcessClosing (Ptr< Packet > packet, const TcpHeader & tcpHeader) protected
Received a packet upon CLOSING.
Parameters
packet the packet
tcpHeader the packet's TCP header
Definition at line 2488 of file tcp-socket-base.cc.
References ns3::TcpHeader::ACK, CloseAndNotify(), ns3::TcpHeader::FIN, ns3::TcpHeader::FlagsToString(), ns3::TcpHeader::GetFlags(), ns3::TcpHeader::GetSequenceNumber(), ns3::TcpSocketState::m_rxBuffer, m_tcb, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::TcpHeader::PSH, ns3::TcpHeader::RST, SendEmptyPacket(), SendRST(), TimeWait(), and ns3::TcpHeader::URG.
Referenced by DoForwardUp().
ProcessEstablished()
void ns3::TcpSocketBase::ProcessEstablished (Ptr< Packet > packet, const TcpHeader & tcpHeader) protected
Received a packet upon ESTABLISHED state.
This function is mimicking the role of tcp_rcv_established() in tcp_input.c in Linux kernel.
Parameters
packet the packet
tcpHeader the packet's TCP header
Definition at line 1451 of file tcp-socket-base.cc.
References ns3::TcpHeader::ACK, CloseAndNotify(), ns3::TcpHeader::CWR, ns3::TcpHeader::ECE, ns3::TcpSocketState::ECN_CE_RCVD, ns3::TcpSocketState::ECN_SENDING_ECE, ns3::TcpSocketState::EcnStateName, ns3::TcpHeader::FIN, ns3::TcpHeader::FlagsToString(), ns3::TcpHeader::GetAckNumber(), ns3::TcpHeader::GetFlags(), ns3::TcpSocketState::m_ecnState, ns3::TcpSocketState::m_highTxMark, ns3::TcpSocketState::m_rxBuffer, m_tcb, m_txBuffer, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, NS_LOG_WARN, PeerClose(), ns3::TcpHeader::PSH, ReceivedAck(), ReceivedData(), ns3::TcpHeader::RST, SendEmptyPacket(), SendRST(), ns3::TcpHeader::SYN, and ns3::TcpHeader::URG.
Referenced by DoForwardUp().
ProcessLastAck()
void ns3::TcpSocketBase::ProcessLastAck (Ptr< Packet > packet, const TcpHeader & tcpHeader) protected
Received a packet upon LAST_ACK.
Parameters
packet the packet
tcpHeader the packet's TCP header
Definition at line 2520 of file tcp-socket-base.cc.
References ns3::TcpHeader::ACK, CloseAndNotify(), ns3::TcpHeader::FIN, ns3::TcpHeader::FlagsToString(), ns3::TcpHeader::GetFlags(), ns3::TcpHeader::GetSequenceNumber(), ns3::TcpSocketState::m_rxBuffer, m_tcb, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::TcpHeader::PSH, ReceivedData(), ns3::TcpHeader::RST, SendEmptyPacket(), SendRST(), and ns3::TcpHeader::URG.
Referenced by DoForwardUp().
ProcessListen()
void ns3::TcpSocketBase::ProcessListen (Ptr< Packet > packet, const TcpHeader & tcpHeader, const Address & fromAddress, const Address & toAddress) protected
Received a packet upon LISTEN state.
Parameters
packet the packet
tcpHeader the packet's TCP header
fromAddress the source address
toAddress the destination address
Definition at line 2181 of file tcp-socket-base.cc.
References CompleteFork(), ns3::TcpHeader::CWR, ns3::TcpHeader::ECE, Fork(), ns3::TcpHeader::GetFlags(), ns3::Socket::NotifyConnectionRequest(), NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::TcpHeader::PSH, ns3::Simulator::ScheduleNow(), ns3::TcpHeader::SYN, and ns3::TcpHeader::URG.
Referenced by DoForwardUp().
ProcessOptionSack()
uint32_t ns3::TcpSocketBase::ProcessOptionSack (const Ptr< const TcpOption > option) protected
Read the SACK option.
Parameters
option SACK option from the header
Returns
the number of bytes sacked by this option
Definition at line 4162 of file tcp-socket-base.cc.
References m_rateOps, m_txBuffer, ns3::MakeCallback(), NS_LOG_FUNCTION, and ns3::TcpRateOps::SkbDelivered().
Referenced by ReadOptions().
ProcessOptionSackPermitted()
void ns3::TcpSocketBase::ProcessOptionSackPermitted (const Ptr< const TcpOption > option) protected
Read the SACK PERMITTED option.
Currently this is a placeholder, since no operations should be done on such option.
Parameters
option SACK PERMITTED option from the header
Definition at line 4171 of file tcp-socket-base.cc.
References ns3::Node::GetId(), m_node, m_sackEnabled, NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by DoForwardUp().
ProcessOptionTimestamp()
void ns3::TcpSocketBase::ProcessOptionTimestamp (const Ptr< const TcpOption > option, const SequenceNumber32 & seq) protected
Process the timestamp option from other side.
Get the timestamp and the echo, then save timestamp (which will be the echo value in our out-packets) and save the echoed timestamp, to utilize later to calculate RTT.
See also
EstimateRtt
Parameters
option Option from the segment
seq Sequence number of the segment
Definition at line 4222 of file tcp-socket-base.cc.
References ns3::Node::GetId(), m_highTxAck, m_node, ns3::TcpSocketState::m_rcvTimestampEchoReply, ns3::TcpSocketState::m_rcvTimestampValue, ns3::TcpSocketState::m_rxBuffer, m_tcb, m_timestampToEcho, NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by DoForwardUp().
ProcessOptionWScale()
void ns3::TcpSocketBase::ProcessOptionWScale (const Ptr< const TcpOption > option) protected
Read and parse the Window scale option.
Read the window scale option (encoded logarithmically) and save it. Per RFC 1323, the value can't exceed 14.
Parameters
option Window scale option read from the header
Definition at line 4097 of file tcp-socket-base.cc.
References ns3::Node::GetId(), m_node, m_sndWindShift, NS_LOG_FUNCTION, NS_LOG_INFO, and NS_LOG_WARN.
Referenced by DoForwardUp().
ProcessSynRcvd()
void ns3::TcpSocketBase::ProcessSynRcvd (Ptr< Packet > packet, const TcpHeader & tcpHeader, const Address & fromAddress, const Address & toAddress) protected
Received a packet upon SYN_RCVD.
Parameters
packet the packet
tcpHeader the packet's TCP header
fromAddress the source address
toAddress the destination address
Definition at line 2305 of file tcp-socket-base.cc.
References ns3::TcpHeader::ACK, ns3::TcpSocketState::CA_OPEN, ns3::EventId::Cancel(), CloseAndNotify(), ns3::Inet6SocketAddress::ConvertFrom(), ns3::InetSocketAddress::ConvertFrom(), ns3::TcpHeader::CWR, ns3::TcpHeader::ECE, ns3::TcpSocketState::ECN_DISABLED, ns3::TcpSocketState::ECN_IDLE, ns3::TcpSocketState::EcnStateName, ns3::TcpSocket::ESTABLISHED, ns3::TcpHeader::FIN, ns3::TcpHeader::FlagsToString(), ns3::TcpHeader::GetAckNumber(), ns3::TcpHeader::GetFlags(), ns3::TcpHeader::GetSequenceNumber(), GetTxAvailable(), m_congestionControl, ns3::TcpSocketState::m_congState, m_connected, m_delAckCount, m_delAckMaxCount, ns3::TcpSocketState::m_ecnState, m_endPoint, m_endPoint6, ns3::TcpSocketState::m_highTxMark, ns3::TcpSocketState::m_nextTxSequence, m_retxEvent, ns3::TcpSocketState::m_rxBuffer, m_state, m_tcb, m_txBuffer, ns3::TcpSocketState::m_useEcn, ns3::Socket::NotifyNewConnectionCreated(), ns3::Socket::NotifySend(), NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, NS_UNUSED, ns3::TcpSocketState::Off, PeerClose(), ns3::TcpHeader::PSH, ReceivedAck(), ns3::TcpHeader::RST, SendEmptyPacket(), SendRST(), ns3::Ipv4EndPoint::SetPeer(), ns3::Ipv6EndPoint::SetPeer(), ns3::TcpHeader::SYN, UpdatePacingRate(), and ns3::TcpHeader::URG.
Referenced by DoForwardUp().
ProcessSynSent()
void ns3::TcpSocketBase::ProcessSynSent (Ptr< Packet > packet, const TcpHeader & tcpHeader) protected
Received a packet upon SYN_SENT.
Parameters
packet the packet
tcpHeader the packet's TCP header
Definition at line 2211 of file tcp-socket-base.cc.
References ns3::TcpHeader::ACK, ns3::TcpSocketState::CA_OPEN, ns3::EventId::Cancel(), CloseAndNotify(), ConnectionSucceeded(), ns3::TcpHeader::CWR, ns3::TcpHeader::ECE, ns3::TcpSocketState::ECN_DISABLED, ns3::TcpSocketState::ECN_IDLE, ns3::TcpSocketState::EcnStateName, ns3::TcpSocket::ESTABLISHED, ns3::TcpHeader::FlagsToString(), ns3::TcpHeader::GetAckNumber(), ns3::TcpHeader::GetFlags(), ns3::TcpHeader::GetSequenceNumber(), m_congestionControl, ns3::TcpSocketState::m_congState, m_connected, m_delAckCount, m_delAckMaxCount, ns3::TcpSocketState::m_ecnState, ns3::TcpSocketState::m_highTxMark, ns3::TcpSocketState::m_nextTxSequence, m_retxEvent, ns3::TcpSocketState::m_rxBuffer, m_state, m_synCount, m_synRetries, m_tcb, m_txBuffer, ns3::TcpSocketState::m_useEcn, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, ns3::TcpSocketState::Off, ns3::TcpHeader::PSH, ReceivedData(), ns3::TcpHeader::RST, ns3::Simulator::ScheduleNow(), SendEmptyPacket(), SendPendingData(), SendRST(), ns3::TcpHeader::SYN, ns3::TcpSocket::SYN_RCVD, UpdatePacingRate(), and ns3::TcpHeader::URG.
Referenced by DoForwardUp().
ProcessWait()
void ns3::TcpSocketBase::ProcessWait (Ptr< Packet > packet, const TcpHeader & tcpHeader) protected
Received a packet upon CLOSE_WAIT, FIN_WAIT_1, FIN_WAIT_2.
Parameters
packet the packet
tcpHeader the packet's TCP header
Definition at line 2416 of file tcp-socket-base.cc.
References ns3::TcpHeader::ACK, CloseAndNotify(), ns3::TcpSocket::CLOSING, ns3::TcpHeader::CWR, ns3::TcpHeader::ECE, ns3::TcpHeader::FIN, ns3::TcpSocket::FIN_WAIT_1, ns3::TcpSocket::FIN_WAIT_2, ns3::TcpHeader::FlagsToString(), ns3::TcpHeader::GetAckNumber(), ns3::TcpHeader::GetFlags(), ns3::TcpHeader::GetSequenceNumber(), ns3::Packet::GetSize(), ns3::TcpSocketState::m_highTxMark, ns3::TcpSocketState::m_rxBuffer, m_shutdownRecv, m_state, m_tcb, m_txBuffer, ns3::Socket::NotifyDataRecv(), NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::TcpHeader::PSH, ReceivedAck(), ReceivedData(), ns3::TcpHeader::RST, SendEmptyPacket(), SendRST(), ns3::TcpHeader::SYN, TimeWait(), and ns3::TcpHeader::URG.
Referenced by DoForwardUp().
ReadOptions()
void ns3::TcpSocketBase::ReadOptions (const TcpHeader & tcpHeader, uint32_t * bytesSacked) protected
Read TCP options before Ack processing.
Timestamp and Window scale are managed in other pieces of code.
Parameters
tcpHeader Header of the segment
[out] bytesSacked Number of bytes SACKed, or 0
Definition at line 1549 of file tcp-socket-base.cc.
References ns3::TcpOption::GetKind(), ns3::TcpHeader::GetOptionList(), NS_LOG_FUNCTION, ProcessOptionSack(), and ns3::TcpOption::SACK.
Referenced by ReceivedAck().
ReceivedAck()
void ns3::TcpSocketBase::ReceivedAck (Ptr< Packet > packet, const TcpHeader & tcpHeader) protected virtual
Received an ACK packet.
Parameters
packet the packet
tcpHeader the packet's TCP header
Reimplemented in ns3::TcpSocketMsgBase.
Definition at line 1766 of file tcp-socket-base.cc.
References ns3::TcpHeader::ACK, BytesInFlight(), ns3::TcpSocketState::CA_CWR, ns3::TcpSocketState::CA_EVENT_COMPLETE_CWR, ns3::TcpSocketState::CA_OPEN, ns3::TcpSocketState::CA_RECOVERY, ns3::TcpHeader::ECE, ns3::TcpSocketState::ECN_DISABLED, ns3::TcpSocketState::ECN_ECE_RCVD, ns3::TcpSocketState::ECN_IDLE, ns3::TcpSocketState::EcnStateName, EnterCwr(), ns3::TcpRateOps::GenerateSample(), ns3::TracedValue< T >::Get(), ns3::TcpHeader::GetAckNumber(), ns3::TcpRateOps::GetConnectionRate(), ns3::TcpHeader::GetFlags(), ns3::Packet::GetSize(), ns3::TcpSocketState::m_bytesInFlight, m_congestionControl, ns3::TcpSocketState::m_congState, m_connected, ns3::TcpSocketState::m_cWnd, ns3::TcpRateOps::TcpRateConnection::m_delivered, m_ecnEchoSeq, ns3::TcpSocketState::m_ecnState, ns3::TcpSocketState::m_isRetransDataAcked, ns3::TcpSocketState::m_minRtt, m_rateOps, m_recover, m_recoveryOps, ns3::TcpSocketState::m_segmentSize, ns3::TcpSocketState::m_ssThresh, m_tcb, m_txBuffer, ns3::MakeCallback(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, ProcessAck(), ReadOptions(), ReceivedData(), SendPendingData(), ns3::TcpRateOps::SkbDelivered(), and ns3::TcpSocketState::TcpCongStateName.
Referenced by ProcessEstablished(), ProcessSynRcvd(), ProcessWait(), and ns3::TcpSocketMsgBase::ReceivedAck().
ReceivedData()
void ns3::TcpSocketBase::ReceivedData (Ptr< Packet > packet, const TcpHeader & tcpHeader) protected virtual
Recv of a data, put into buffer, call L7 to get it if necessary.
Parameters
packet the packet
tcpHeader the packet's TCP header
Reimplemented in TcpSocketHalfAck.
Definition at line 3432 of file tcp-socket-base.cc.
References ns3::TcpHeader::ACK, ns3::TcpSocketState::CA_EVENT_DELAYED_ACK, ns3::TcpSocketState::CA_EVENT_NON_DELAYED_ACK, ns3::EventId::Cancel(), DelAckTimeout(), DoPeerClose(), ns3::TcpHeader::ECE, ns3::TcpSocketState::ECN_CE_RCVD, ns3::TcpSocketState::ECN_SENDING_ECE, ns3::TcpSocketState::EcnStateName, ns3::TcpHeader::FIN, ns3::Simulator::GetDelayLeft(), ns3::TcpHeader::GetFlags(), ns3::TcpHeader::GetSequenceNumber(), ns3::Packet::GetSize(), ns3::EventId::IsExpired(), m_closeNotified, m_congestionControl, m_delAckCount, m_delAckEvent, m_delAckMaxCount, m_delAckTimeout, ns3::TcpSocketState::m_ecnState, ns3::TcpSocketState::m_rxBuffer, m_shutdownRecv, m_tcb, ns3::Socket::NotifyDataRecv(), ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, NS_LOG_WARN, ns3::Simulator::Schedule(), and SendEmptyPacket().
Referenced by PeerClose(), ProcessEstablished(), ProcessLastAck(), ProcessSynSent(), ProcessWait(), ReceivedAck(), and TcpSocketHalfAck::ReceivedData().
Recv()
Ptr< Packet > ns3::TcpSocketBase::Recv (uint32_t maxSize, uint32_t flags) virtual
Read data from the socket.
This function matches closely in semantics to the recv() function call in the standard C library (libc): ssize_t recv (int s, void *buf, size_t len, int flags); except that the receive I/O is asynchronous. This is the primary Recv method at this low-level API and must be implemented by subclasses.
This method is normally used only on a connected socket. In a typical blocking sockets model, this call would block until at least one byte is returned or the connection closes. In ns-3 at this API, the call returns immediately in such a case and returns 0 if nothing is available to be read. However, an application can set a callback, ns3::SetRecvCallback, to be notified of data being available to be read (when it conceptually unblocks); this is an asynchronous I/O model for recv().
This variant of Recv() uses class ns3::Packet to encapsulate data, rather than providing a raw pointer and length field. This allows an ns-3 application to attach tags if desired (such as a flow ID) and may allow the simulator to avoid some data copies. Despite the appearance of receiving Packets on a stream socket, just think of it as a fancy byte buffer with streaming semantics.
The semantics depend on the type of socket. For a datagram socket, each Recv() returns the data from at most one Send(), and order is not necessarily preserved. For a stream socket, the bytes are delivered in order, and on-the-wire packet boundaries are not preserved.
The flags argument is formed by or'ing one or more of the values: MSG_OOB process out-of-band data MSG_PEEK peek at incoming message None of these flags are supported for now.
Some variants of Recv() are supported as additional API, including RecvFrom(), overloaded Recv() without arguments, and variants that use raw character buffers.
Parameters
maxSize reader will accept packet up to maxSize
flags Socket control flags
Returns
Ptr<Packet> of the next in-sequence packet. Returns 0 if the socket cannot return a next in-sequence packet conforming to the maxSize and flags.
See also
SetRecvCallback
Implements ns3::Socket.
Definition at line 872 of file tcp-socket-base.cc.
References ns3::TcpSocket::CLOSE_WAIT, ns3::TcpSocketState::m_rxBuffer, m_state, m_tcb, NS_ABORT_MSG_IF, and NS_LOG_FUNCTION.
RecvFrom()
Ptr< Packet > ns3::TcpSocketBase::RecvFrom (uint32_t maxSize, uint32_t flags, Address & fromAddress) virtual
Read a single packet from the socket and retrieve the sender address.
Calls Recv(maxSize, flags) with maxSize implicitly set to maximum sized integer, and flags set to zero.
This method has similar semantics to Recv () but subclasses may want to provide checks on socket state, so the implementation is pushed to subclasses.
Parameters
maxSize reader will accept packet up to maxSize
flags Socket control flags
fromAddress output parameter that will return the address of the sender of the received packet, if any. Remains untouched if no packet is received.
Returns
Ptr<Packet> of the next in-sequence packet. Returns 0 if the socket cannot return a next in-sequence packet.
Implements ns3::Socket.
Definition at line 886 of file tcp-socket-base.cc.
References ns3::Ipv6EndPoint::GetPeerAddress(), ns3::Ipv4EndPoint::GetPeerAddress(), ns3::Ipv6EndPoint::GetPeerPort(), ns3::Ipv4EndPoint::GetPeerPort(), ns3::Packet::GetSize(), ns3::Ipv4Address::GetZero(), m_endPoint, m_endPoint6, NS_LOG_FUNCTION, and ns3::Socket::Recv().
ReTxTimeout()
void ns3::TcpSocketBase::ReTxTimeout (void) protected virtual
An RTO event happened.
Reimplemented in ns3::TcpSocketMsgBase, ns3::TcpSocketCongestedRouter, and TcpDctcpCongestedRouter.
Definition at line 3627 of file tcp-socket-base.cc.
References BytesInFlight(), ns3::TcpSocketState::CA_EVENT_LOSS, ns3::TcpSocketState::CA_LOSS, ns3::Timer::Cancel(), ns3::TcpSocket::CLOSED, ns3::TcpSocket::CLOSING, ns3::TcpHeader::CWR, DeallocateEndPoint(), ns3::TcpHeader::ECE, ns3::TcpHeader::FIN, ns3::TcpSocket::FIN_WAIT_1, ns3::Time::FromDouble(), ns3::TracedValue< T >::Get(), ns3::Time::GetSeconds(), m_congestionControl, ns3::TcpSocketState::m_congState, m_connected, ns3::TcpSocketState::m_cWnd, ns3::TcpSocketState::m_cWndInfl, m_dataRetrCount, m_dupAckCount, ns3::TcpSocketState::m_highTxMark, m_history, m_pacingTimer, m_recover, m_recoverActive, m_rto, m_sackEnabled, ns3::TcpSocketState::m_segmentSize, ns3::TcpSocketState::m_ssThresh, m_state, m_synCount, m_tcb, m_txBuffer, ns3::TcpSocketState::m_useEcn, ns3::Min(), ns3::Socket::NotifyErrorClose(), ns3::Simulator::Now(), NS_ASSERT, NS_ASSERT_MSG, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, ns3::TcpSocketState::On, ns3::Time::S, SendEmptyPacket(), SendPendingData(), ns3::TcpHeader::SYN, ns3::TcpSocket::SYN_SENT, and ns3::TcpSocket::TIME_WAIT.
Referenced by NewAck(), ns3::TcpSocketCongestedRouter::ReTxTimeout(), ns3::TcpSocketMsgBase::ReTxTimeout(), and SendDataPacket().
SafeSubtraction()
uint32_t ns3::TcpSocketBase::SafeSubtraction (uint32_t a, uint32_t b) static protected
Performs a safe subtraction between a and b (a-b)
Safe is used to indicate that, if b>a, the results returned is 0.
Parameters
a first number
b second number
Returns
0 if b>0, (a-b) otherwise
Definition at line 4439 of file tcp-socket-base.cc.
Referenced by ProcessAck().
Send()
int ns3::TcpSocketBase::Send (Ptr< Packet > p, uint32_t flags) virtual
Send data (or dummy data) to the remote host.
This function matches closely in semantics to the send() function call in the standard C library (libc): ssize_t send (int s, const void *msg, size_t len, int flags); except that the send I/O is asynchronous. This is the primary Send method at this low-level API and must be implemented by subclasses.
In a typical blocking sockets model, this call would block upon lack of space to hold the message to be sent. In ns-3 at this API, the call returns immediately in such a case, but the callback registered with SetSendCallback() is invoked when the socket has space (when it conceptually unblocks); this is an asynchronous I/O model for send().
This variant of Send() uses class ns3::Packet to encapsulate data, rather than providing a raw pointer and length field. This allows an ns-3 application to attach tags if desired (such as a flow ID) and may allow the simulator to avoid some data copies. Despite the appearance of sending Packets on a stream socket, just think of it as a fancy byte buffer with streaming semantics.
If either the message buffer within the Packet is too long to pass atomically through the underlying protocol (for datagram sockets), or the message buffer cannot entirely fit in the transmit buffer (for stream sockets), -1 is returned and SocketErrno is set to ERROR_MSGSIZE. If the packet does not fit, the caller can split the Packet (based on information obtained from GetTxAvailable) and reattempt to send the data.
The flags argument is formed by or'ing one or more of the values: MSG_OOB process out-of-band data MSG_DONTROUTE bypass routing, use direct interface These flags are unsupported as of ns-3.1.
Parameters
p ns3::Packet to send
flags Socket control flags
Returns
the number of bytes accepted for transmission if no error occurs, and -1 otherwise.
See also
SetSendCallback
Implements ns3::Socket.
Definition at line 818 of file tcp-socket-base.cc.
References AvailableWindow(), ns3::TcpRateOps::CalculateAppLimited(), ns3::TcpSocket::CLOSE_WAIT, ns3::Socket::ERROR_MSGSIZE, ns3::Socket::ERROR_NOTCONN, ns3::Socket::ERROR_SHUTDOWN, ns3::TcpSocket::ESTABLISHED, ns3::Packet::GetSize(), ns3::EventId::IsRunning(), ns3::TcpSocketState::m_bytesInFlight, m_connected, ns3::TcpSocketState::m_cWnd, ns3::TcpSocketState::m_nextTxSequence, m_rateOps, ns3::TcpSocketState::m_segmentSize, m_sendPendingDataEvent, m_shutdownSend, m_state, m_tcb, m_txBuffer, NS_ABORT_MSG_IF, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Simulator::Schedule(), SendPendingData(), ns3::TcpSocket::SYN_SENT, and ns3::TcpSocket::TcpStateName.
Referenced by SendTo().
SendDataPacket()
uint32_t ns3::TcpSocketBase::SendDataPacket (SequenceNumber32 seq, uint32_t maxSize, bool withAck) protected virtual
Extract at most maxSize bytes from the TxBuffer at sequence seq, add the TCP header, and send to TcpL4Protocol.
Parameters
seq the sequence number
maxSize the maximum data block to be transmitted (in bytes)
withAck forces an ACK to be sent
Returns
the number of bytes sent
Reimplemented in ns3::TcpSocketCongestedRouter, and TcpDctcpCongestedRouter.
Definition at line 3037 of file tcp-socket-base.cc.
References ns3::TcpHeader::ACK, AddOptions(), AddSocketTags(), AdvertisedWindowSize(), BytesInFlight(), ns3::TcpSocketState::CA_CWR, ns3::TcpSocketState::CA_RECOVERY, ns3::EventId::Cancel(), ns3::TcpSocket::CLOSE_WAIT, ns3::TcpHeader::CWR, ns3::TcpSocketState::ECN_CWR_SENT, ns3::TcpSocketState::ECN_ECE_RCVD, ns3::TcpSocketState::EcnStateName, ns3::TcpSocket::ESTABLISHED, ns3::TcpHeader::FIN, ns3::TcpSocket::FIN_WAIT_1, ns3::TracedValue< T >::Get(), ns3::Ipv6EndPoint::GetLocalAddress(), ns3::Ipv4EndPoint::GetLocalAddress(), ns3::Ipv6EndPoint::GetLocalPort(), ns3::Ipv4EndPoint::GetLocalPort(), ns3::TcpTxItem::GetPacketCopy(), ns3::Ipv6EndPoint::GetPeerAddress(), ns3::Ipv4EndPoint::GetPeerAddress(), ns3::Ipv6EndPoint::GetPeerPort(), ns3::Ipv4EndPoint::GetPeerPort(), ns3::Time::GetSeconds(), ns3::Packet::GetSize(), ns3::EventId::IsExpired(), ns3::Timer::IsExpired(), IsPacingEnabled(), ns3::TcpTxItem::IsRetrans(), ns3::TcpSocket::LAST_ACK, ns3::Socket::m_boundnetdevice, m_closeOnEmpty, ns3::TcpSocketState::m_congState, m_delAckCount, m_delAckEvent, m_ecnCWRSeq, m_ecnEchoSeq, ns3::TcpSocketState::m_ecnState, m_endPoint, m_endPoint6, m_highRxAckMark, ns3::TcpSocketState::m_highTxMark, ns3::TcpSocketState::m_pacingRate, m_pacingTimer, m_rateOps, m_recoveryOps, m_retxEvent, m_rto, m_rWnd, ns3::TcpSocketState::m_rxBuffer, m_state, m_tcb, m_tcp, m_txBuffer, m_txTrace, max, ns3::Socket::NotifyDataSent(), ns3::Simulator::Now(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, ReTxTimeout(), ns3::Simulator::Schedule(), ns3::Timer::Schedule(), ns3::Simulator::ScheduleNow(), ns3::TcpHeader::SetAckNumber(), ns3::TcpHeader::SetDestinationPort(), ns3::TcpHeader::SetFlags(), ns3::TcpHeader::SetSequenceNumber(), ns3::TcpHeader::SetSourcePort(), ns3::TcpHeader::SetWindowSize(), ns3::TcpRateOps::SkbSent(), and UpdateRttHistory().
Referenced by DoRetransmit(), and SendPendingData().
SendEmptyPacket()
void ns3::TcpSocketBase::SendEmptyPacket (uint8_t flags) protected virtual
Send a empty packet that carries a flag, e.g., ACK.
Parameters
flags the packet's flags
Reimplemented in ns3::TcpSocketSmallAcks.
Definition at line 2665 of file tcp-socket-base.cc.
References ns3::TcpHeader::ACK, AddOptions(), AddOptionSack(), AddOptionSackPermitted(), AddOptionWScale(), AddSocketTags(), AdvertisedWindowSize(), ns3::EventId::Cancel(), ns3::TcpSocket::CLOSED, ns3::TcpSocket::CLOSING, DeallocateEndPoint(), ns3::TcpHeader::FIN, ns3::TcpSocket::FIN_WAIT_1, ns3::TracedValue< T >::Get(), ns3::TcpHeader::GetAckNumber(), ns3::Ipv6EndPoint::GetLocalAddress(), ns3::Ipv4EndPoint::GetLocalAddress(), ns3::Ipv6EndPoint::GetLocalPort(), ns3::Ipv4EndPoint::GetLocalPort(), ns3::Ipv6EndPoint::GetPeerAddress(), ns3::Ipv4EndPoint::GetPeerAddress(), ns3::Ipv6EndPoint::GetPeerPort(), ns3::Ipv4EndPoint::GetPeerPort(), ns3::Time::GetSeconds(), ns3::EventId::IsExpired(), ns3::TcpSocket::LAST_ACK, ns3::Socket::m_boundnetdevice, m_clockGranularity, m_cnTimeout, m_delAckCount, m_delAckEvent, m_endPoint, m_endPoint6, m_highTxAck, m_minRto, ns3::TcpSocketState::m_nextTxSequence, m_retxEvent, m_rto, m_rtt, ns3::TcpSocketState::m_rxBuffer, m_sackEnabled, m_state, m_synCount, m_synRetries, m_tcb, m_tcp, m_txTrace, m_winScalingEnabled, ns3::Max(), ns3::Socket::NotifyConnectionFailed(), ns3::Simulator::Now(), NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, NS_LOG_WARN, ns3::Simulator::Schedule(), ns3::TcpHeader::SetAckNumber(), ns3::TcpHeader::SetDestinationPort(), ns3::TcpHeader::SetFlags(), ns3::TcpHeader::SetSequenceNumber(), ns3::TcpHeader::SetSourcePort(), ns3::TcpHeader::SetWindowSize(), ns3::TcpHeader::SYN, and UpdateRttHistory().
Referenced by TcpSocketBase(), CompleteFork(), DelAckTimeout(), DoClose(), DoConnect(), DoPeerClose(), IsValidTcpSegment(), LastAckTimeout(), ProcessClosing(), ProcessEstablished(), ProcessLastAck(), ProcessSynRcvd(), ProcessSynSent(), ProcessWait(), ReceivedData(), ReTxTimeout(), SendRST(), SetRcvBufSize(), and ShutdownSend().
SendPendingData()
uint32_t ns3::TcpSocketBase::SendPendingData (bool withAck = false) protected
Send as much pending data as possible according to the Tx window.
Note that this function did not implement the PSH flag.
Parameters
withAck forces an ACK to be sent
Returns
the number of packets sent
Definition at line 3198 of file tcp-socket-base.cc.
References AvailableWindow(), ns3::TcpSocketState::CA_DISORDER, ns3::TcpSocketState::CA_EVENT_TX_START, ns3::TcpSocketState::CA_OPEN, ns3::TcpSocketState::CA_RECOVERY, ns3::TcpSocket::FIN_WAIT_1, ns3::TracedValue< T >::Get(), ns3::Timer::GetDelayLeft(), GetTxAvailable(), ns3::Timer::IsExpired(), IsPacingEnabled(), ns3::Timer::IsRunning(), ns3::TcpSocketState::m_bytesInFlight, m_congestionControl, ns3::TcpSocketState::m_congState, ns3::TcpSocketState::m_cWnd, m_endPoint, m_endPoint6, m_limitedTx, ns3::TcpSocketState::m_nextTxSequence, m_noDelay, ns3::TcpSocketState::m_pacingRate, m_pacingTimer, m_rWnd, m_sackEnabled, ns3::TcpSocketState::m_segmentSize, m_shutdownSend, m_state, m_tcb, m_txBuffer, min, ns3::Socket::NotifySend(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, ns3::Timer::Schedule(), SendDataPacket(), and UnAckDataCount().
Referenced by DoForwardUp(), NotifyPacingPerformed(), ProcessSynSent(), ReceivedAck(), ReTxTimeout(), and Send().
SendRST()
void ns3::TcpSocketBase::SendRST (void) protected
Send reset and tear down this socket.
Definition at line 2793 of file tcp-socket-base.cc.
References DeallocateEndPoint(), ns3::Socket::NotifyErrorClose(), NS_LOG_FUNCTION, ns3::TcpHeader::RST, and SendEmptyPacket().
Referenced by Close(), DoClose(), DoConnect(), ProcessClosing(), ProcessEstablished(), ProcessLastAck(), ProcessSynRcvd(), ProcessSynSent(), and ProcessWait().
SendTo()
int ns3::TcpSocketBase::SendTo (Ptr< Packet > p, uint32_t flags, const Address & toAddress) virtual
Send data to a specified peer.
This method has similar semantics to Send () but subclasses may want to provide checks on socket state, so the implementation is pushed to subclasses.
Parameters
p packet to send
flags Socket control flags
toAddress IP Address of remote host
Returns
-1 in case of error or the number of bytes copied in the internal buffer and accepted for transmission.
Implements ns3::Socket.
Definition at line 863 of file tcp-socket-base.cc.
References first::address, NS_UNUSED, and Send().
SetAllowBroadcast()
bool ns3::TcpSocketBase::SetAllowBroadcast (bool allowBroadcast) protected virtual
Configure whether broadcast datagram transmissions are allowed.
This method corresponds to using setsockopt() SO_BROADCAST of real network or BSD sockets. If set on a socket, this option will enable or disable packets to be transmitted to broadcast destination addresses.
Parameters
allowBroadcast Whether broadcast is allowed
Returns
true if operation succeeds
Implements ns3::Socket.
Definition at line 4073 of file tcp-socket-base.cc.
SetClockGranularity()
void ns3::TcpSocketBase::SetClockGranularity (Time clockGranularity)
Sets the Clock Granularity (used in RTO calcs).
Parameters
clockGranularity The Clock Granularity
Definition at line 4322 of file tcp-socket-base.cc.
References m_clockGranularity, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetCongestionControlAlgorithm()
void ns3::TcpSocketBase::SetCongestionControlAlgorithm (Ptr< TcpCongestionOps > algo)
Install a congestion control algorithm on this socket.
Parameters
algo Algorithm to be installed
Definition at line 4418 of file tcp-socket-base.cc.
References m_congestionControl, m_tcb, and NS_LOG_FUNCTION.
SetConnTimeout()
void ns3::TcpSocketBase::SetConnTimeout (Time timeout) protected virtual
Set the connection timeout.
Parameters
timeout the connection timeout
Implements ns3::TcpSocket.
Definition at line 3981 of file tcp-socket-base.cc.
References m_cnTimeout, NS_LOG_FUNCTION, and timeout.
SetDataRetries()
void ns3::TcpSocketBase::SetDataRetries (uint32_t retries) protected virtual
Set the number of data transmission retries before giving up.
Parameters
retries the number of data transmission retries
Implements ns3::TcpSocket.
Definition at line 4007 of file tcp-socket-base.cc.
References m_dataRetries, and NS_LOG_FUNCTION.
SetDelAckMaxCount()
void ns3::TcpSocketBase::SetDelAckMaxCount (uint32_t count) protected virtual
Set the number of packet to fire an ACK before delay timeout.
Parameters
count the umber of packet to fire an ACK before delay timeout
Implements ns3::TcpSocket.
Definition at line 4034 of file tcp-socket-base.cc.
References m_delAckMaxCount, and NS_LOG_FUNCTION.
SetDelAckTimeout()
void ns3::TcpSocketBase::SetDelAckTimeout (Time timeout) protected virtual
Set the time to delay an ACK.
Parameters
timeout the time to delay an ACK
Implements ns3::TcpSocket.
Definition at line 4021 of file tcp-socket-base.cc.
References m_delAckTimeout, NS_LOG_FUNCTION, and timeout.
SetInitialCwnd()
void ns3::TcpSocketBase::SetInitialCwnd (uint32_t cwnd) protected virtual
Set the initial Congestion Window.
Parameters
cwnd the initial congestion window (in segments)
Implements ns3::TcpSocket.
Definition at line 636 of file tcp-socket-base.cc.
References ns3::TcpSocket::CLOSED, ns3::TcpSocketState::m_initialCWnd, m_state, m_tcb, and NS_ABORT_MSG_UNLESS.
SetInitialSSThresh()
void ns3::TcpSocketBase::SetInitialSSThresh (uint32_t threshold) protected virtual
Set the initial Slow Start Threshold.
Parameters
threshold the Slow Start Threshold (in bytes)
Implements ns3::TcpSocket.
Definition at line 621 of file tcp-socket-base.cc.
References ns3::TcpSocket::CLOSED, ns3::TcpSocketState::m_initialSsThresh, m_state, m_tcb, and NS_ABORT_MSG_UNLESS.
SetMinRto()
void ns3::TcpSocketBase::SetMinRto (Time minRto)
Sets the Minimum RTO.
Parameters
minRto The minimum RTO.
Definition at line 4309 of file tcp-socket-base.cc.
References m_minRto, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetNode()
void ns3::TcpSocketBase::SetNode (Ptr< Node > node) virtual
Set the associated node.
Parameters
node the node
Definition at line 474 of file tcp-socket-base.cc.
References m_node.
SetPaceInitialWindow()
void ns3::TcpSocketBase::SetPaceInitialWindow (bool paceWindow)
Enable or disable pacing of the initial window.
Parameters
pacing Boolean to enable or disable pacing of the initial window
Definition at line 4534 of file tcp-socket-base.cc.
References ns3::TcpSocketState::m_paceInitialWindow, m_tcb, and NS_LOG_FUNCTION.
SetPacingStatus()
void ns3::TcpSocketBase::SetPacingStatus (bool pacing)
Enable or disable pacing.
Parameters
pacing Boolean to enable or disable pacing
Definition at line 4527 of file tcp-socket-base.cc.
References ns3::TcpSocketState::m_pacing, m_tcb, and NS_LOG_FUNCTION.
SetPersistTimeout()
void ns3::TcpSocketBase::SetPersistTimeout (Time timeout) protected virtual
Set the timeout for persistent connection.
When the timeout expires, send 1-byte data to probe for the window size at the receiver when the local knowledge tells that the receiver has zero window size
Parameters
timeout the persistent timeout
Implements ns3::TcpSocket.
Definition at line 4060 of file tcp-socket-base.cc.
References m_persistTimeout, NS_LOG_FUNCTION, and timeout.
SetRcvBufSize()
void ns3::TcpSocketBase::SetRcvBufSize (uint32_t size) protected virtual
Set the receive buffer size.
Parameters
size the buffer size (in bytes)
Implements ns3::TcpSocket.
Definition at line 3933 of file tcp-socket-base.cc.
References ns3::TcpHeader::ACK, ns3::TcpHeader::ECE, ns3::TcpSocketState::ECN_CE_RCVD, ns3::TcpSocketState::ECN_SENDING_ECE, ns3::TcpSocketState::EcnStateName, GetRcvBufSize(), m_connected, ns3::TcpSocketState::m_ecnState, ns3::TcpSocketState::m_rxBuffer, m_tcb, NS_LOG_DEBUG, NS_LOG_FUNCTION, and SendEmptyPacket().
SetRecoveryAlgorithm()
void ns3::TcpSocketBase::SetRecoveryAlgorithm (Ptr< TcpRecoveryOps > recovery)
Install a recovery algorithm on this socket.
Parameters
recovery Algorithm to be installed
Definition at line 4426 of file tcp-socket-base.cc.
References m_recoveryOps, and NS_LOG_FUNCTION.
SetRetxThresh()
void ns3::TcpSocketBase::SetRetxThresh (uint32_t retxThresh)
Set the retransmission threshold (dup ack threshold for a fast retransmit)
Parameters
retxThresh the threshold
Definition at line 4347 of file tcp-socket-base.cc.
References m_retxThresh, and m_txBuffer.
Referenced by GetTypeId().
SetRtt()
void ns3::TcpSocketBase::SetRtt (Ptr< RttEstimator > rtt) virtual
Set the associated RTT estimator.
Parameters
rtt the RTT estimator
Definition at line 488 of file tcp-socket-base.cc.
SetSegSize()
void ns3::TcpSocketBase::SetSegSize (uint32_t size) protected virtual
Set the segment size.
Parameters
size the segment size (in bytes)
Implements ns3::TcpSocket.
Definition at line 3965 of file tcp-socket-base.cc.
References ns3::TcpSocket::CLOSED, ns3::TcpSocketState::m_segmentSize, m_state, m_tcb, m_txBuffer, NS_ABORT_MSG_UNLESS, and NS_LOG_FUNCTION.
SetSndBufSize()
void ns3::TcpSocketBase::SetSndBufSize (uint32_t size) protected virtual
Set the send buffer size.
Parameters
size the buffer size (in bytes)
Implements ns3::TcpSocket.
Definition at line 3920 of file tcp-socket-base.cc.
References m_txBuffer, and NS_LOG_FUNCTION.
SetSynRetries()
void ns3::TcpSocketBase::SetSynRetries (uint32_t count) protected virtual
Set the number of connection retries before giving up.
Parameters
count the number of connection retries
Implements ns3::TcpSocket.
Definition at line 3994 of file tcp-socket-base.cc.
References m_synRetries, and NS_LOG_FUNCTION.
SetTcp()
void ns3::TcpSocketBase::SetTcp (Ptr< TcpL4Protocol > tcp) virtual
Set the associated TCP L4 protocol.
Parameters
tcp the TCP L4 protocol
Definition at line 481 of file tcp-socket-base.cc.
References m_tcp.
SetTcpNoDelay()
void ns3::TcpSocketBase::SetTcpNoDelay (bool noDelay) protected virtual
Enable/Disable Nagle's algorithm.
Parameters
noDelay true to DISABLE Nagle's algorithm
Implements ns3::TcpSocket.
Definition at line 4047 of file tcp-socket-base.cc.
References m_noDelay, and NS_LOG_FUNCTION.
SetupCallback()
int ns3::TcpSocketBase::SetupCallback (void) protected
Common part of the two Bind(), i.e.
set callback and remembering local addr:port
Returns
0 on success, -1 on failure
Definition at line 997 of file tcp-socket-base.cc.
References Destroy(), Destroy6(), ForwardIcmp(), ForwardIcmp6(), ForwardUp(), ForwardUp6(), m_endPoint, m_endPoint6, ns3::MakeCallback(), NS_LOG_FUNCTION, ns3::Ipv4EndPoint::SetDestroyCallback(), ns3::Ipv6EndPoint::SetDestroyCallback(), ns3::Ipv4EndPoint::SetIcmpCallback(), ns3::Ipv6EndPoint::SetIcmpCallback(), ns3::Ipv4EndPoint::SetRxCallback(), and ns3::Ipv6EndPoint::SetRxCallback().
Referenced by Bind(), Bind6(), and CompleteFork().
SetupEndpoint()
int ns3::TcpSocketBase::SetupEndpoint (void) protected
Configure the endpoint to a local address.
Called by Connect() if Bind() didn't specify one.
Returns
0 on success
Definition at line 2825 of file tcp-socket-base.cc.
References ns3::Object::GetObject(), ns3::Ipv4EndPoint::GetPeerAddress(), ns3::Ipv4Route::GetSource(), ns3::Socket::m_boundnetdevice, m_endPoint, m_node, NS_ASSERT, NS_FATAL_ERROR, NS_LOG_ERROR, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Ipv4Header::SetDestination(), and ns3::Ipv4EndPoint::SetLocalAddress().
Referenced by Connect().
SetupEndpoint6()
int ns3::TcpSocketBase::SetupEndpoint6 (void) protected
Configure the endpoint v6 to a local address.
Called by Connect() if Bind() didn't specify one.
Returns
0 on success
Definition at line 2855 of file tcp-socket-base.cc.
References ns3::Object::GetObject(), ns3::Ipv6EndPoint::GetPeerAddress(), ns3::Socket::m_boundnetdevice, m_endPoint6, m_node, NS_ASSERT, NS_FATAL_ERROR, NS_LOG_ERROR, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Ipv6Header::SetDestinationAddress(), and ns3::Ipv6EndPoint::SetLocalAddress().
Referenced by Connect().
SetUseEcn()
void ns3::TcpSocketBase::SetUseEcn (TcpSocketState::UseEcn_t useEcn)
Set ECN mode of use on the socket.
Parameters
useEcn Mode of ECN to use.
Definition at line 4541 of file tcp-socket-base.cc.
References m_tcb, ns3::TcpSocketState::m_useEcn, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
ShutdownRecv()
int ns3::TcpSocketBase::ShutdownRecv (void) virtual
Returns
zero on success, -1 on failure.
Do not allow any further Recv calls. This method is typically implemented for Tcp sockets by a half close.
Implements ns3::Socket.
Definition at line 808 of file tcp-socket-base.cc.
References m_shutdownRecv, and NS_LOG_FUNCTION.
ShutdownSend()
int ns3::TcpSocketBase::ShutdownSend (void) virtual
Returns
zero on success, -1 on failure.
Do not allow any further Send calls. This method is typically implemented for Tcp sockets by a half close.
Implements ns3::Socket.
Definition at line 774 of file tcp-socket-base.cc.
References ns3::TcpSocket::CLOSE_WAIT, ns3::TcpSocket::ESTABLISHED, ns3::TcpHeader::FIN, ns3::TcpSocket::FIN_WAIT_1, ns3::TcpSocket::LAST_ACK, m_closeOnEmpty, m_shutdownSend, m_state, m_txBuffer, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, and SendEmptyPacket().
TimeWait()
void ns3::TcpSocketBase::TimeWait (void) protected
Move from CLOSING or FIN_WAIT_2 to TIME_WAIT state.
Definition at line 3898 of file tcp-socket-base.cc.
References CancelAllTimers(), CloseAndNotify(), m_closeNotified, m_msl, m_state, m_timewaitEvent, ns3::Socket::NotifyNormalClose(), NS_LOG_DEBUG, ns3::Simulator::Schedule(), ns3::Seconds(), ns3::TcpSocket::TcpStateName, and ns3::TcpSocket::TIME_WAIT.
Referenced by ProcessClosing(), and ProcessWait().
UnAckDataCount()
uint32_t ns3::TcpSocketBase::UnAckDataCount (void) const protected virtual
Return count of number of unacked bytes.
The difference between SND.UNA and HighTx
Returns
count of number of unacked bytes
Definition at line 3361 of file tcp-socket-base.cc.
References ns3::TcpSocketState::m_highTxMark, m_tcb, and m_txBuffer.
Referenced by EnterCwr(), EnterRecovery(), and SendPendingData().
UpdateBytesInFlight()
void ns3::TcpSocketBase::UpdateBytesInFlight (uint32_t oldValue, uint32_t newValue)
Callback function to hook to TcpSocketState bytes inflight.
Parameters
oldValue old bytesInFlight value
newValue new bytesInFlight value
Definition at line 4406 of file tcp-socket-base.cc.
References m_bytesInFlightTrace.
Referenced by TcpSocketBase().
UpdateCongState()
void ns3::TcpSocketBase::UpdateCongState (TcpSocketState::TcpCongState_t oldValue, TcpSocketState::TcpCongState_t newValue)
Callback function to hook to TcpSocketState congestion state.
Parameters
oldValue old congestion state value
newValue new congestion state value
Definition at line 4378 of file tcp-socket-base.cc.
References m_congStateTrace.
Referenced by TcpSocketBase().
UpdateCwnd()
void ns3::TcpSocketBase::UpdateCwnd (uint32_t oldValue, uint32_t newValue)
Callback function to hook to TcpSocketState congestion window.
Parameters
oldValue old cWnd value
newValue new cWnd value
Definition at line 4360 of file tcp-socket-base.cc.
References m_cWndTrace.
Referenced by TcpSocketBase().
UpdateCwndInfl()
void ns3::TcpSocketBase::UpdateCwndInfl (uint32_t oldValue, uint32_t newValue)
Callback function to hook to TcpSocketState inflated congestion window.
Parameters
oldValue old cWndInfl value
newValue new cWndInfl value
Definition at line 4366 of file tcp-socket-base.cc.
References m_cWndInflTrace.
Referenced by TcpSocketBase().
UpdateEcnState()
void ns3::TcpSocketBase::UpdateEcnState (TcpSocketState::EcnState_t oldValue, TcpSocketState::EcnState_t newValue)
Callback function to hook to EcnState state.
Parameters
oldValue old ecn state value
newValue new ecn state value
Definition at line 4385 of file tcp-socket-base.cc.
References m_ecnStateTrace.
Referenced by TcpSocketBase().
UpdateHighTxMark()
void ns3::TcpSocketBase::UpdateHighTxMark (SequenceNumber32 oldValue, SequenceNumber32 newValue)
Callback function to hook to TcpSocketState high tx mark.
Parameters
oldValue old high tx mark
newValue new high tx mark
Definition at line 4400 of file tcp-socket-base.cc.
References m_highTxMarkTrace.
Referenced by TcpSocketBase().
UpdateNextTxSequence()
void ns3::TcpSocketBase::UpdateNextTxSequence (SequenceNumber32 oldValue, SequenceNumber32 newValue)
Callback function to hook to TcpSocketState next tx sequence.
Parameters
oldValue old nextTxSeq value
newValue new nextTxSeq value
Definition at line 4392 of file tcp-socket-base.cc.
References m_nextTxSequenceTrace.
Referenced by TcpSocketBase().
UpdatePacingRate()
void ns3::TcpSocketBase::UpdatePacingRate (void) protected
Dynamically update the pacing rate.
Parameters
tcb internal congestion state
Definition at line 4480 of file tcp-socket-base.cc.
References ns3::TracedValue< T >::Get(), ns3::Time::GetSeconds(), ns3::TcpSocketState::m_bytesInFlight, m_congestionControl, ns3::TcpSocketState::m_cWnd, ns3::TcpSocketState::m_lastRtt, ns3::TcpSocketState::m_maxPacingRate, ns3::TcpSocketState::m_pacing, ns3::TcpSocketState::m_pacingCaRatio, ns3::TcpSocketState::m_pacingRate, ns3::TcpSocketState::m_pacingSsRatio, ns3::TcpSocketState::m_ssThresh, m_tcb, max, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by ProcessAck(), ProcessSynRcvd(), and ProcessSynSent().
UpdatePacingRateTrace()
void ns3::TcpSocketBase::UpdatePacingRateTrace (DataRate oldValue, DataRate newValue)
Callback function to hook to TcpSocketState pacing rate.
Parameters
oldValue old pacing rate value
newValue new pacing rate value
Definition at line 4354 of file tcp-socket-base.cc.
References m_pacingRateTrace.
Referenced by TcpSocketBase().
UpdateRtt()
void ns3::TcpSocketBase::UpdateRtt (Time oldValue, Time newValue)
Callback function to hook to TcpSocketState rtt.
Parameters
oldValue old rtt value
newValue new rtt value
Definition at line 4412 of file tcp-socket-base.cc.
References m_lastRttTrace.
Referenced by TcpSocketBase().
UpdateRttHistory()
void ns3::TcpSocketBase::UpdateRttHistory (const SequenceNumber32 & seq, uint32_t sz, bool isRetransmission) protected virtual
Update the RTT history, when we send TCP segments.
Parameters
seq The sequence number of the TCP segment
sz The segment's size
isRetransmission Whether or not the segment is a retransmission
Reimplemented in ns3::TcpSocketMsgBase.
Definition at line 3172 of file tcp-socket-base.cc.
References m_history, ns3::Simulator::Now(), and NS_LOG_FUNCTION.
Referenced by SendDataPacket(), SendEmptyPacket(), and ns3::TcpSocketMsgBase::UpdateRttHistory().
UpdateSsThresh()
void ns3::TcpSocketBase::UpdateSsThresh (uint32_t oldValue, uint32_t newValue)
Callback function to hook to TcpSocketState slow start threshold.
Parameters
oldValue old ssTh value
newValue new ssTh value
Definition at line 4372 of file tcp-socket-base.cc.
References m_ssThTrace.
Referenced by TcpSocketBase().
UpdateWindowSize()
void ns3::TcpSocketBase::UpdateWindowSize (const TcpHeader & header) protected
Update the receiver window (RWND) based on the value of the window field in the header.
This method suppresses updates unless one of the following three conditions holds: 1) segment contains new data (advancing the right edge of the receive buffer), 2) segment does not contain new data but the segment acks new data (highest sequence number acked advances), or 3) the advertised window is larger than the current send window
Parameters
header TcpHeader from which to extract the new window value
Definition at line 4264 of file tcp-socket-base.cc.
References ns3::TcpSocket::ESTABLISHED, ns3::TcpHeader::GetAckNumber(), ns3::TcpHeader::GetSequenceNumber(), ns3::TcpHeader::GetWindowSize(), m_highRxAckMark, m_highRxMark, m_rWnd, m_sndWindShift, m_state, NS_LOG_FUNCTION, NS_LOG_INFO, and NS_LOG_LOGIC.
Referenced by DoForwardUp().
Window()
uint32_t ns3::TcpSocketBase::Window (void) const protected virtual
Return the max possible number of unacked bytes.
Returns
the max possible number of unacked bytes
Definition at line 3379 of file tcp-socket-base.cc.
References ns3::TracedValue< T >::Get(), ns3::TcpSocketState::m_cWnd, m_rWnd, m_tcb, and min.
Referenced by AvailableWindow().
Friends And Related Function Documentation
TcpGeneralTest
friend class TcpGeneralTest friend
TcpGeneralTest friend class (for tests).
Definition at line 237 of file tcp-socket-base.h.
Member Data Documentation
m_advWnd
TracedValue<uint32_t> ns3::TcpSocketBase::m_advWnd {0} protected
Advertised Window size.
Definition at line 1306 of file tcp-socket-base.h.
Referenced by AdvertisedWindowSize(), and GetTypeId().
m_bytesAckedNotProcessed
uint32_t ns3::TcpSocketBase::m_bytesAckedNotProcessed {0} protected
Bytes acked, but not processed.
Definition at line 1303 of file tcp-socket-base.h.
Referenced by ProcessAck().
m_bytesInFlightTrace
TracedCallback<uint32_t, uint32_t> ns3::TcpSocketBase::m_bytesInFlightTrace
Callback pointer for bytesInFlight trace chaining.
Definition at line 363 of file tcp-socket-base.h.
Referenced by GetTypeId(), and UpdateBytesInFlight().
m_clockGranularity
Time ns3::TcpSocketBase::m_clockGranularity {Seconds (0.001)} protected
Clock Granularity used in RTO calcs.
Definition at line 1270 of file tcp-socket-base.h.
Referenced by DoPeerClose(), EstimateRtt(), GetClockGranularity(), LastAckTimeout(), NewAck(), SendEmptyPacket(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), and SetClockGranularity().
m_closeNotified
bool ns3::TcpSocketBase::m_closeNotified {false} protected
Told app to close socket.
Definition at line 1294 of file tcp-socket-base.h.
Referenced by CloseAndNotify(), DoPeerClose(), ReceivedData(), and TimeWait().
m_closeOnEmpty
bool ns3::TcpSocketBase::m_closeOnEmpty {false} protected
Close socket upon tx buffer emptied.
Definition at line 1295 of file tcp-socket-base.h.
Referenced by Close(), SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), and ShutdownSend().
m_cnTimeout
Time ns3::TcpSocketBase::m_cnTimeout {Seconds (0.0)} protected
Timeout for connection retry.
Definition at line 1273 of file tcp-socket-base.h.
Referenced by GetConnTimeout(), SendEmptyPacket(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), and SetConnTimeout().
m_congestionControl
Ptr<TcpCongestionOps> ns3::TcpSocketBase::m_congestionControl protected
Congestion control.
Definition at line 1330 of file tcp-socket-base.h.
Referenced by TcpSocketBase(), DelAckTimeout(), DupAck(), EnterCwr(), EnterRecovery(), ForwardUp(), ForwardUp6(), GetTypeId(), ProcessAck(), ProcessSynRcvd(), ProcessSynSent(), ReceivedAck(), ReceivedData(), ReTxTimeout(), TcpDctcpCongestedRouter::SendDataPacket(), SendPendingData(), SetCongestionControlAlgorithm(), and UpdatePacingRate().
m_congStateTrace
TracedCallback<TcpSocketState::TcpCongState_t, TcpSocketState::TcpCongState_t> ns3::TcpSocketBase::m_congStateTrace
Callback pointer for congestion state trace chaining.
Definition at line 343 of file tcp-socket-base.h.
Referenced by GetTypeId(), and UpdateCongState().
m_connected
bool ns3::TcpSocketBase::m_connected {false} protected
Connection established.
Definition at line 1298 of file tcp-socket-base.h.
Referenced by DoForwardUp(), NotifyPacingPerformed(), ProcessSynRcvd(), ProcessSynSent(), ReceivedAck(), ReTxTimeout(), Send(), and SetRcvBufSize().
m_cWndInflTrace
TracedCallback<uint32_t, uint32_t> ns3::TcpSocketBase::m_cWndInflTrace
Callback pointer for cWndInfl trace chaining.
Definition at line 333 of file tcp-socket-base.h.
Referenced by GetTypeId(), and UpdateCwndInfl().
m_cWndTrace
TracedCallback<uint32_t, uint32_t> ns3::TcpSocketBase::m_cWndTrace
Callback pointer for cWnd trace chaining.
Definition at line 328 of file tcp-socket-base.h.
Referenced by GetTypeId(), and UpdateCwnd().
m_dataRetrCount
uint32_t ns3::TcpSocketBase::m_dataRetrCount {0} protected
Count of remaining data retransmission attempts.
Definition at line 1264 of file tcp-socket-base.h.
Referenced by CompleteFork(), Connect(), DoPeerClose(), LastAckTimeout(), NewAck(), and ReTxTimeout().
m_dataRetries
uint32_t ns3::TcpSocketBase::m_dataRetries {0} protected
Number of data retransmission attempts.
Definition at line 1265 of file tcp-socket-base.h.
Referenced by CompleteFork(), Connect(), DoPeerClose(), GetDataRetries(), NewAck(), and SetDataRetries().
m_delAckCount
uint32_t ns3::TcpSocketBase::m_delAckCount {0} protected
Delayed ACK counter.
Definition at line 1255 of file tcp-socket-base.h.
Referenced by DelAckTimeout(), ProcessSynRcvd(), ProcessSynSent(), ReceivedData(), SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), SendEmptyPacket(), and ns3::TcpSocketSmallAcks::SendEmptyPacket().
m_delAckEvent
EventId ns3::TcpSocketBase::m_delAckEvent {} protected
Delayed ACK timeout event.
Definition at line 1249 of file tcp-socket-base.h.
Referenced by CancelAllTimers(), ReceivedData(), SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), SendEmptyPacket(), and ns3::TcpSocketSmallAcks::SendEmptyPacket().
m_delAckMaxCount
uint32_t ns3::TcpSocketBase::m_delAckMaxCount {0} protected
Number of packet to fire an ACK before delay timeout.
Definition at line 1256 of file tcp-socket-base.h.
Referenced by GetDelAckMaxCount(), ProcessSynRcvd(), ProcessSynSent(), ReceivedData(), and SetDelAckMaxCount().
m_delAckTimeout
Time ns3::TcpSocketBase::m_delAckTimeout {Seconds (0.0)} protected
Time to delay an ACK.
Definition at line 1271 of file tcp-socket-base.h.
Referenced by GetDelAckTimeout(), ReceivedData(), and SetDelAckTimeout().
m_dupAckCount
uint32_t ns3::TcpSocketBase::m_dupAckCount {0} protected
Dupack counter.
Definition at line 1254 of file tcp-socket-base.h.
Referenced by DupAck(), EnterCwr(), EnterRecovery(), ProcessAck(), and ReTxTimeout().
m_ecnCESeq
TracedValue<SequenceNumber32> ns3::TcpSocketBase::m_ecnCESeq {0} protected
Sequence number of the last received Congestion Experienced.
Definition at line 1349 of file tcp-socket-base.h.
Referenced by ForwardUp(), ForwardUp6(), and GetTypeId().
m_ecnCWRSeq
TracedValue<SequenceNumber32> ns3::TcpSocketBase::m_ecnCWRSeq {0} protected
Sequence number of the last sent CWR.
Definition at line 1350 of file tcp-socket-base.h.
Referenced by GetTypeId(), SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), and ns3::TcpSocketCongestedRouter::SendDataPacket().
m_ecnEchoSeq
TracedValue<SequenceNumber32> ns3::TcpSocketBase::m_ecnEchoSeq {0} protected
Sequence number of the last received ECN Echo.
Definition at line 1348 of file tcp-socket-base.h.
Referenced by GetTypeId(), ReceivedAck(), SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), and ns3::TcpSocketCongestedRouter::SendDataPacket().
m_ecnStateTrace
TracedCallback<TcpSocketState::EcnState_t, TcpSocketState::EcnState_t> ns3::TcpSocketBase::m_ecnStateTrace
Callback pointer for ECN state trace chaining.
Definition at line 348 of file tcp-socket-base.h.
Referenced by GetTypeId(), and UpdateEcnState().
m_endPoint
Ipv4EndPoint* ns3::TcpSocketBase::m_endPoint {nullptr} protected
the IPv4 endpoint
Definition at line 1279 of file tcp-socket-base.h.
Referenced by ~TcpSocketBase(), Bind(), BindToNetDevice(), CompleteFork(), Connect(), DeallocateEndPoint(), Destroy(), ForwardUp(), GetPeerName(), GetSockName(), PersistTimeout(), ProcessSynRcvd(), RecvFrom(), SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), SendEmptyPacket(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), SendPendingData(), SetupCallback(), and SetupEndpoint().
m_endPoint6
Ipv6EndPoint* ns3::TcpSocketBase::m_endPoint6 {nullptr} protected
the IPv6 endpoint
Definition at line 1280 of file tcp-socket-base.h.
Referenced by ~TcpSocketBase(), Bind(), Bind6(), BindToNetDevice(), CompleteFork(), Connect(), DeallocateEndPoint(), Destroy6(), ForwardUp6(), GetPeerName(), GetSockName(), PersistTimeout(), ProcessSynRcvd(), RecvFrom(), SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), SendEmptyPacket(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), SendPendingData(), SetupCallback(), and SetupEndpoint6().
m_highRxAckMark
TracedValue<SequenceNumber32> ns3::TcpSocketBase::m_highRxAckMark {0} protected
Highest ack received.
Definition at line 1308 of file tcp-socket-base.h.
Referenced by DoForwardUp(), DupAck(), GetHighRxAck(), GetTypeId(), SendDataPacket(), and UpdateWindowSize().
m_highRxMark
TracedValue<SequenceNumber32> ns3::TcpSocketBase::m_highRxMark {0} protected
Highest seqno received.
Definition at line 1307 of file tcp-socket-base.h.
Referenced by GetTypeId(), and UpdateWindowSize().
m_highTxAck
SequenceNumber32 ns3::TcpSocketBase::m_highTxAck {0} protected
Highest ack sent.
Definition at line 1304 of file tcp-socket-base.h.
Referenced by ProcessOptionTimestamp(), and SendEmptyPacket().
m_highTxMarkTrace
TracedCallback<SequenceNumber32, SequenceNumber32> ns3::TcpSocketBase::m_highTxMarkTrace
Callback pointer for high tx mark chaining.
Definition at line 353 of file tcp-socket-base.h.
Referenced by GetTypeId(), and UpdateHighTxMark().
m_history
std::deque<RttHistory> ns3::TcpSocketBase::m_history protected
List of sent packet.
Definition at line 1276 of file tcp-socket-base.h.
Referenced by EstimateRtt(), ReTxTimeout(), and UpdateRttHistory().
m_icmpCallback
Callback<void, Ipv4Address,uint8_t,uint8_t,uint8_t,uint32_t> ns3::TcpSocketBase::m_icmpCallback protected
ICMP callback.
Definition at line 1283 of file tcp-socket-base.h.
Referenced by ForwardIcmp(), and GetTypeId().
m_icmpCallback6
Callback<void, Ipv6Address,uint8_t,uint8_t,uint8_t,uint32_t> ns3::TcpSocketBase::m_icmpCallback6 protected
ICMPv6 callback.
Definition at line 1284 of file tcp-socket-base.h.
Referenced by ForwardIcmp6(), and GetTypeId().
m_isFirstPartialAck
bool ns3::TcpSocketBase::m_isFirstPartialAck {true} protected
First partial ACK during RECOVERY.
Definition at line 1335 of file tcp-socket-base.h.
Referenced by ProcessAck().
m_lastAckEvent
EventId ns3::TcpSocketBase::m_lastAckEvent {} protected
Last ACK timeout event.
Definition at line 1248 of file tcp-socket-base.h.
Referenced by CancelAllTimers(), CloseAndNotify(), DoPeerClose(), and LastAckTimeout().
m_lastRttTrace
TracedCallback<Time, Time> ns3::TcpSocketBase::m_lastRttTrace
Callback pointer for RTT trace chaining.
Definition at line 368 of file tcp-socket-base.h.
Referenced by GetTypeId(), and UpdateRtt().
m_limitedTx
bool ns3::TcpSocketBase::m_limitedTx {true} protected
perform limited transmit
Definition at line 1326 of file tcp-socket-base.h.
Referenced by DupAck(), GetTypeId(), and SendPendingData().
m_maxWinSize
uint16_t ns3::TcpSocketBase::m_maxWinSize {0} protected
Maximum window size to advertise.
Definition at line 1302 of file tcp-socket-base.h.
Referenced by AdvertisedWindowSize(), CalculateWScale(), and GetTypeId().
m_minRto
Time ns3::TcpSocketBase::m_minRto {Time::Max ()} protected
minimum value of the Retransmit timeout
Definition at line 1269 of file tcp-socket-base.h.
Referenced by EstimateRtt(), GetMinRto(), NewAck(), SendEmptyPacket(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), and SetMinRto().
m_msl
double ns3::TcpSocketBase::m_msl {0.0} protected
Max segment lifetime.
Definition at line 1299 of file tcp-socket-base.h.
Referenced by GetTypeId(), and TimeWait().
m_nextTxSequenceTrace
TracedCallback<SequenceNumber32, SequenceNumber32> ns3::TcpSocketBase::m_nextTxSequenceTrace
Callback pointer for next tx sequence chaining.
Definition at line 358 of file tcp-socket-base.h.
Referenced by GetTypeId(), and UpdateNextTxSequence().
m_node
Ptr<Node> ns3::TcpSocketBase::m_node protected
the associated node
Definition at line 1281 of file tcp-socket-base.h.
Referenced by ~TcpSocketBase(), AddOptionSack(), AddOptionSackPermitted(), AddOptionTimestamp(), AddOptionWScale(), CalculateWScale(), GetNode(), ProcessOptionSackPermitted(), ProcessOptionTimestamp(), ProcessOptionWScale(), SetNode(), SetupEndpoint(), and SetupEndpoint6().
m_noDelay
bool ns3::TcpSocketBase::m_noDelay {false} protected
Set to true to disable Nagle's algorithm.
Definition at line 1259 of file tcp-socket-base.h.
Referenced by GetTcpNoDelay(), SendPendingData(), and SetTcpNoDelay().
m_pacingRateTrace
TracedCallback<DataRate, DataRate> ns3::TcpSocketBase::m_pacingRateTrace
Callback pointer for pacing rate trace chaining.
Definition at line 323 of file tcp-socket-base.h.
Referenced by GetTypeId(), and UpdatePacingRateTrace().
m_pacingTimer
Timer ns3::TcpSocketBase::m_pacingTimer {Timer::CANCEL_ON_DESTROY} protected
Pacing Event.
Definition at line 1345 of file tcp-socket-base.h.
Referenced by TcpSocketBase(), CancelAllTimers(), ReTxTimeout(), SendDataPacket(), and SendPendingData().
m_persistEvent
EventId ns3::TcpSocketBase::m_persistEvent {} protected
Persist event: Send 1 byte to probe for a non-zero Rx window.
Definition at line 1250 of file tcp-socket-base.h.
Referenced by CancelAllTimers(), DoForwardUp(), and PersistTimeout().
m_persistTimeout
Time ns3::TcpSocketBase::m_persistTimeout {Seconds (0.0)} protected
Time between sending 1-byte probes.
Definition at line 1272 of file tcp-socket-base.h.
Referenced by DoForwardUp(), GetPersistTimeout(), PersistTimeout(), and SetPersistTimeout().
m_rateOps
Ptr<TcpRateOps> ns3::TcpSocketBase::m_rateOps protected
Rate operations.
Definition at line 1332 of file tcp-socket-base.h.
Referenced by TcpSocketBase(), ProcessOptionSack(), ReceivedAck(), Send(), and SendDataPacket().
m_rcvWindShift
uint8_t ns3::TcpSocketBase::m_rcvWindShift {0} protected
Window shift to apply to outgoing segments.
Definition at line 1313 of file tcp-socket-base.h.
Referenced by AddOptionWScale(), and AdvertisedWindowSize().
m_recover
SequenceNumber32 ns3::TcpSocketBase::m_recover {0} protected
Previous highest Tx seqnum for fast recovery (set it to initial seq number)
Definition at line 1321 of file tcp-socket-base.h.
Referenced by DupAck(), EnterCwr(), EnterRecovery(), ProcessAck(), ReceivedAck(), and ReTxTimeout().
m_recoverActive
bool ns3::TcpSocketBase::m_recoverActive {false} protected
Whether "m_recover" has been set/activated It is used to avoid comparing with the old m_recover value which was set for handling previous congestion event.
Definition at line 1322 of file tcp-socket-base.h.
Referenced by DupAck(), EnterRecovery(), ProcessAck(), and ReTxTimeout().
m_recoveryOps
Ptr<TcpRecoveryOps> ns3::TcpSocketBase::m_recoveryOps protected
Recovery Algorithm.
Definition at line 1331 of file tcp-socket-base.h.
Referenced by TcpSocketBase(), DupAck(), EnterCwr(), EnterRecovery(), ProcessAck(), ReceivedAck(), SendDataPacket(), and SetRecoveryAlgorithm().
m_retxEvent
EventId ns3::TcpSocketBase::m_retxEvent {} protected
Retransmission event.
Definition at line 1247 of file tcp-socket-base.h.
Referenced by CancelAllTimers(), Destroy(), Destroy6(), DoForwardUp(), NewAck(), ProcessSynRcvd(), ProcessSynSent(), SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), SendEmptyPacket(), and ns3::TcpSocketSmallAcks::SendEmptyPacket().
m_retxThresh
uint32_t ns3::TcpSocketBase::m_retxThresh {3} protected
Fast Retransmit threshold.
Definition at line 1325 of file tcp-socket-base.h.
Referenced by DupAck(), GetRetxThresh(), and SetRetxThresh().
m_rto
TracedValue<Time> ns3::TcpSocketBase::m_rto {Seconds (0.0)} protected
Retransmit timeout.
Definition at line 1268 of file tcp-socket-base.h.
Referenced by EstimateRtt(), GetTypeId(), NewAck(), ReTxTimeout(), SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), SendEmptyPacket(), and ns3::TcpSocketSmallAcks::SendEmptyPacket().
m_rtt
Ptr<RttEstimator> ns3::TcpSocketBase::m_rtt protected
Round trip time estimator.
Definition at line 1286 of file tcp-socket-base.h.
Referenced by TcpSocketBase(), Connect(), DoPeerClose(), EstimateRtt(), GetErrno(), LastAckTimeout(), NewAck(), SendEmptyPacket(), and ns3::TcpSocketSmallAcks::SendEmptyPacket().
m_rWnd
TracedValue<uint32_t> ns3::TcpSocketBase::m_rWnd {0} protected
Receiver window (RCV.WND in RFC793)
Definition at line 1305 of file tcp-socket-base.h.
Referenced by DoForwardUp(), GetRWnd(), GetTypeId(), SendDataPacket(), SendPendingData(), UpdateWindowSize(), and Window().
m_rxTrace
TracedCallback<Ptr<const Packet>, const TcpHeader&, Ptr<const TcpSocketBase> > ns3::TcpSocketBase::m_rxTrace protected
Trace of received packets.
Definition at line 1342 of file tcp-socket-base.h.
Referenced by DoForwardUp(), and GetTypeId().
m_sackEnabled
bool ns3::TcpSocketBase::m_sackEnabled {true} protected
RFC SACK option enabled.
Definition at line 1311 of file tcp-socket-base.h.
Referenced by DoForwardUp(), DoRetransmit(), DupAck(), EnterRecovery(), GetTypeId(), IsTcpOptionEnabled(), ProcessAck(), ProcessOptionSackPermitted(), ReTxTimeout(), SendEmptyPacket(), and SendPendingData().
m_sendPendingDataEvent
EventId ns3::TcpSocketBase::m_sendPendingDataEvent {} protected
micro-delay event to send pending data
Definition at line 1318 of file tcp-socket-base.h.
Referenced by CancelAllTimers(), and Send().
m_shutdownRecv
bool ns3::TcpSocketBase::m_shutdownRecv {false} protected
Receive no longer allowed.
Definition at line 1297 of file tcp-socket-base.h.
Referenced by ProcessWait(), ReceivedData(), and ShutdownRecv().
m_shutdownSend
bool ns3::TcpSocketBase::m_shutdownSend {false} protected
Send no longer allowed.
Definition at line 1296 of file tcp-socket-base.h.
Referenced by DoPeerClose(), Send(), SendPendingData(), and ShutdownSend().
m_sndWindShift
uint8_t ns3::TcpSocketBase::m_sndWindShift {0} protected
Window shift to apply to incoming segments.
Definition at line 1314 of file tcp-socket-base.h.
Referenced by ProcessOptionWScale(), and UpdateWindowSize().
m_ssThTrace
TracedCallback<uint32_t, uint32_t> ns3::TcpSocketBase::m_ssThTrace
Callback pointer for ssTh trace chaining.
Definition at line 338 of file tcp-socket-base.h.
Referenced by GetTypeId(), and UpdateSsThresh().
m_state
TracedValue<TcpStates_t> ns3::TcpSocketBase::m_state {CLOSED} protected
TCP state.
Definition at line 1292 of file tcp-socket-base.h.
Referenced by Close(), CloseAndNotify(), CompleteFork(), DoClose(), DoConnect(), DoForwardUp(), DoPeerClose(), GetTypeId(), IsValidTcpSegment(), LastAckTimeout(), Listen(), NewAck(), OutOfRange(), PeerClose(), ProcessSynRcvd(), ProcessSynSent(), ProcessWait(), Recv(), ReTxTimeout(), Send(), SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), SendEmptyPacket(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), SendPendingData(), SetInitialCwnd(), SetInitialSSThresh(), SetSegSize(), ShutdownSend(), TimeWait(), and UpdateWindowSize().
m_synCount
uint32_t ns3::TcpSocketBase::m_synCount {0} protected
Count of remaining connection retries.
Definition at line 1262 of file tcp-socket-base.h.
Referenced by CompleteFork(), Connect(), ProcessSynSent(), ReTxTimeout(), SendEmptyPacket(), and ns3::TcpSocketSmallAcks::SendEmptyPacket().
m_synRetries
uint32_t ns3::TcpSocketBase::m_synRetries {0} protected
Number of connection attempts.
Definition at line 1263 of file tcp-socket-base.h.
Referenced by CompleteFork(), Connect(), GetSynRetries(), ProcessSynSent(), SendEmptyPacket(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), and SetSynRetries().
m_tcb
Ptr<TcpSocketState> ns3::TcpSocketBase::m_tcb protected
Congestion control information.
Definition at line 1329 of file tcp-socket-base.h.
Referenced by TcpSocketBase(), AddOptionSack(), AddSocketTags(), AdvertisedWindowSize(), BytesInFlight(), CalculateWScale(), Close(), CompleteFork(), DelAckTimeout(), DoConnect(), DoForwardUp(), DoRetransmit(), DupAck(), EnterCwr(), EnterRecovery(), EstimateRtt(), ForwardUp(), ForwardUp6(), GetInitialCwnd(), GetInitialSSThresh(), GetRcvBufSize(), GetRxAvailable(), GetRxBuffer(), GetSegSize(), IsPacingEnabled(), IsValidTcpSegment(), NewAck(), OutOfRange(), PeerClose(), PersistTimeout(), ProcessAck(), ProcessClosing(), ProcessEstablished(), ProcessLastAck(), ProcessOptionTimestamp(), ProcessSynRcvd(), ProcessSynSent(), ProcessWait(), ReceivedAck(), ReceivedData(), Recv(), ReTxTimeout(), ns3::TcpSocketMsgBase::ReTxTimeout(), Send(), SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), SendEmptyPacket(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), SendPendingData(), SetCongestionControlAlgorithm(), SetInitialCwnd(), SetInitialSSThresh(), SetPaceInitialWindow(), SetPacingStatus(), SetRcvBufSize(), SetSegSize(), SetUseEcn(), UnAckDataCount(), UpdatePacingRate(), and Window().
m_tcp
Ptr<TcpL4Protocol> ns3::TcpSocketBase::m_tcp protected
the associated TCP L4 protocol
Definition at line 1282 of file tcp-socket-base.h.
Referenced by ~TcpSocketBase(), Bind(), Bind6(), CompleteFork(), DeallocateEndPoint(), Destroy(), Destroy6(), DoForwardUp(), PersistTimeout(), SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), SendEmptyPacket(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), and SetTcp().
m_timestampEnabled
bool ns3::TcpSocketBase::m_timestampEnabled {true} protected
Timestamp option enabled.
Definition at line 1315 of file tcp-socket-base.h.
Referenced by AddOptions(), DoForwardUp(), EstimateRtt(), GetTypeId(), and IsTcpOptionEnabled().
m_timestampToEcho
uint32_t ns3::TcpSocketBase::m_timestampToEcho {0} protected
Timestamp to echo.
Definition at line 1316 of file tcp-socket-base.h.
Referenced by AddOptionTimestamp(), and ProcessOptionTimestamp().
m_timewaitEvent
EventId ns3::TcpSocketBase::m_timewaitEvent {} protected
TIME_WAIT expiration event: Move this socket to CLOSED state.
Definition at line 1251 of file tcp-socket-base.h.
Referenced by CancelAllTimers(), and TimeWait().
m_txBuffer
Ptr<TcpTxBuffer> ns3::TcpSocketBase::m_txBuffer protected
Tx buffer.
Definition at line 1289 of file tcp-socket-base.h.
Referenced by TcpSocketBase(), BytesInFlight(), Close(), DoForwardUp(), DoRetransmit(), DupAck(), EnterRecovery(), GetSndBufSize(), GetTxAvailable(), GetTxBuffer(), NewAck(), PersistTimeout(), ProcessAck(), ProcessEstablished(), ProcessOptionSack(), ProcessSynRcvd(), ProcessSynSent(), ProcessWait(), ReceivedAck(), ReTxTimeout(), Send(), SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), SendPendingData(), SetRetxThresh(), SetSegSize(), SetSndBufSize(), ShutdownSend(), and UnAckDataCount().
m_txTrace
TracedCallback<Ptr<const Packet>, const TcpHeader&, Ptr<const TcpSocketBase> > ns3::TcpSocketBase::m_txTrace protected
Trace of transmitted packets.
Definition at line 1339 of file tcp-socket-base.h.
Referenced by DoForwardUp(), GetTypeId(), PersistTimeout(), SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), SendEmptyPacket(), and ns3::TcpSocketSmallAcks::SendEmptyPacket().
m_winScalingEnabled
bool ns3::TcpSocketBase::m_winScalingEnabled {true} protected
Window Scale option enabled (RFC 7323)
Definition at line 1312 of file tcp-socket-base.h.
Referenced by DoForwardUp(), GetTypeId(), IsTcpOptionEnabled(), and SendEmptyPacket().
The documentation for this class was generated from the following files:
src/internet/model/tcp-socket-base.h
src/internet/model/tcp-socket-base.cc