ns-3: ns3::SixLowPanNetDevice Class Reference
ns3::SixLowPanNetDevice Class Reference
6LoWPAN
Shim performing 6LoWPAN compression, decompression and fragmentation.
#include "sixlowpan-net-device.h"
Classes
class Fragments
A Set of Fragments.
Public Types
enum DropReason { DROP_FRAGMENT_TIMEOUT = 1 , DROP_FRAGMENT_BUFFER_FULL , DROP_UNKNOWN_EXTENSION , DROP_DISALLOWED_COMPRESSION }
Enumeration of the dropping reasons in SixLoWPAN.
typedef void(* DropTracedCallback) (DropReason reason, Ptr< const Packet > packet, Ptr< SixLowPanNetDevice > sixNetDevice, uint32_t ifindex)
TracedCallback signature for.
typedef void(* RxTxTracedCallback) (Ptr< const Packet > packet, Ptr< SixLowPanNetDevice > sixNetDevice, uint32_t ifindex)
TracedCallback signature for packet send/receive events.
Public Types inherited from ns3::NetDevice
typedef void(* LinkChangeTracedCallback) (void)
TracedCallback signature for link changed event.
enum PacketType {
PACKET_HOST = 1 , NS3_PACKET_HOST = PACKET_HOST , PACKET_BROADCAST , NS3_PACKET_BROADCAST = PACKET_BROADCAST ,
PACKET_MULTICAST , NS3_PACKET_MULTICAST = PACKET_MULTICAST , PACKET_OTHERHOST , NS3_PACKET_OTHERHOST = PACKET_OTHERHOST
}
Packet types are used as they are in Linux.
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address &, const Address &, enum PacketType > PromiscReceiveCallback
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address & > ReceiveCallback
Public Member Functions
SixLowPanNetDevice ()
Constructor for the SixLowPanNetDevice.
virtual void AddLinkChangeCallback (Callback< void > callback)
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
virtual Address GetAddress (void) const
virtual Address GetBroadcast (void) const
virtual Ptr< Channel > GetChannel (void) const
virtual uint32_t GetIfIndex (void) const
virtual uint16_t GetMtu (void) const
Returns the link-layer MTU for this interface.
virtual Address GetMulticast (Ipv4Address multicastGroup) const
Make and return a MAC multicast address using the provided multicast group.
virtual Address GetMulticast (Ipv6Address addr) const
Get the MAC multicast address corresponding to the IPv6 address provided.
Ptr< NetDevice > GetNetDevice () const
Returns a smart pointer to the underlying NetDevice.
virtual Ptr< Node > GetNode (void) const
virtual bool IsBridge (void) const
Return true if the net device is acting as a bridge.
virtual bool IsBroadcast (void) const
virtual bool IsLinkUp (void) const
virtual bool IsMulticast (void) const
virtual bool IsPointToPoint (void) const
Return true if the net device is on a point-to-point link.
virtual bool NeedsArp (void) const
virtual bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)
virtual bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
virtual void SetAddress (Address address)
Set the address of this interface.
virtual void SetIfIndex (const uint32_t index)
virtual bool SetMtu (const uint16_t mtu)
void SetNetDevice (Ptr< NetDevice > device)
Setup SixLowPan to be a proxy for the specified NetDevice.
virtual void SetNode (Ptr< Node > node)
virtual void SetPromiscReceiveCallback (NetDevice::PromiscReceiveCallback cb)
virtual void SetReceiveCallback (NetDevice::ReceiveCallback cb)
virtual bool SupportsSendFrom () const
Public Member Functions inherited from ns3::NetDevice
virtual ~NetDevice ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::NetDevice
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
typedef std::pair< std::pair< Address, Address >, std::pair< uint16_t, uint16_t > > FragmentKey_t
Fragment identifier type: src/dst address src/dst port.
typedef std::list< std::tuple< Time, FragmentKey_t, uint32_t > > FragmentsTimeoutsList_t
Container for fragment timeouts.
typedef std::list< std::tuple< Time, FragmentKey_t, uint32_t > >::iterator FragmentsTimeoutsListI_t
Container Iterator for fragment timeouts.
typedef std::map< FragmentKey_t, Ptr< Fragments > > MapFragments_t
Container for fragment key -> fragments.
typedef std::map< FragmentKey_t, Ptr< Fragments > >::iterator MapFragmentsI_t
Container Iterator for fragment key -> fragments.
Private Member Functions
SixLowPanNetDevice (SixLowPanNetDevice const &)
Copy constructor.
bool CanCompressLowPanNhc (uint8_t headerType)
Checks if the next header can be compressed using NHC.
uint32_t CompressLowPanHc1 (Ptr< Packet > packet, Address const &src, Address const &dst)
Compress the headers according to HC1 compression.
uint32_t CompressLowPanIphc (Ptr< Packet > packet, Address const &src, Address const &dst)
Compress the headers according to IPHC compression.
uint32_t CompressLowPanNhc (Ptr< Packet > packet, uint8_t headerType, Address const &src, Address const &dst)
Compress the headers according to NHC compression.
uint32_t CompressLowPanUdpNhc (Ptr< Packet > packet, bool omitChecksum)
Compress the headers according to NHC compression.
void DecompressLowPanHc1 (Ptr< Packet > packet, Address const &src, Address const &dst)
Decompress the headers according to HC1 compression.
void DecompressLowPanIphc (Ptr< Packet > packet, Address const &src, Address const &dst)
Decompress the headers according to IPHC compression.
uint8_t DecompressLowPanNhc (Ptr< Packet > packet, Address const &src, Address const &dst, Ipv6Address srcAddress, Ipv6Address dstAddress)
Decompress the headers according to NHC compression.
void DecompressLowPanUdpNhc (Ptr< Packet > packet, Ipv6Address saddr, Ipv6Address daddr)
Decompress the headers according to NHC compression.
void DoFragmentation (Ptr< Packet > packet, uint32_t origPacketSize, uint32_t origHdrSize, std::list< Ptr< Packet > > &listFragments)
Performs a packet fragmentation.
bool DoSend (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber, bool doSendFrom)
void DropOldestFragmentSet ()
Drops the oldest fragment set.
Address Get16MacFrom48Mac (Address addr)
Get a Mac16 from its Mac48 pseudo-MAC.
void HandleFragmentsTimeout (FragmentKey_t key, uint32_t iif)
Process the timeout for packet fragments.
void HandleTimeout (void)
Handles a fragmented packet timeout.
SixLowPanNetDevice & operator= (SixLowPanNetDevice const &)
Copy constructor.
bool ProcessFragment (Ptr< Packet > &packet, Address const &src, Address const &dst, bool isFirst)
Process a packet fragment.
void ReceiveFromDevice (Ptr< NetDevice > device, Ptr< const Packet > packet, uint16_t protocol, Address const &source, Address const &destination, PacketType packetType)
Receives all the packets from a NetDevice for further processing.
FragmentsTimeoutsListI_t SetTimeout (FragmentKey_t key, uint32_t iif)
Set a new timeout "event" for a fragmented packet.
Private Attributes
uint8_t m_bc0Serial
Serial number used in BC0 header.
uint32_t m_compressionThreshold
Minimum L2 payload size.
TracedCallback< DropReason, Ptr< const Packet >, Ptr< SixLowPanNetDevice >, uint32_t > m_dropTrace
Callback to trace drop packets.
uint16_t m_etherType
EtherType number (used only if m_forceEtherType is true).
bool m_forceEtherType
Force the EtherType number.
Time m_fragmentExpirationTimeout
Time limit for fragment rebuilding.
uint16_t m_fragmentReassemblyListSize
How many packets can be rebuilt at the same time.
MapFragments_t m_fragments
Fragments hold to be rebuilt.
uint32_t m_ifIndex
Interface index.
uint16_t m_meshCacheLength
length of the cache for each source.
bool m_meshUnder
Use a mesh-under routing.
uint8_t m_meshUnderHopsLeft
Start value for mesh-under hops left.
Ptr< RandomVariableStream > m_meshUnderJitter
Random variable for the mesh-under packet retransmission.
Ptr< NetDevice > m_netDevice
Smart pointer to the underlying NetDevice.
Ptr< Node > m_node
Smart pointer to the Node.
bool m_omitUdpChecksum
Omit UDP checksum in NC1 encoding.
NetDevice::PromiscReceiveCallback m_promiscRxCallback
The callback used to notify higher layers that a packet has been received in promiscuous mode.
Ptr< UniformRandomVariable > m_rng
Rng for the fragments tag.
NetDevice::ReceiveCallback m_rxCallback
The callback used to notify higher layers that a packet has been received.
TracedCallback< Ptr< const Packet >, Ptr< SixLowPanNetDevice >, uint32_t > m_rxTrace
Callback to trace RX (reception) packets.
std::map< Address, std::list< uint8_t > > m_seenPkts
Seen packets, memorized by OriginatorAdddress, SequenceNumber.
EventId m_timeoutEvent
Event for the next scheduled timeout.
FragmentsTimeoutsList_t m_timeoutEventList
Timeout "events" container.
TracedCallback< Ptr< const Packet >, Ptr< SixLowPanNetDevice >, uint32_t > m_txTrace
Callback to trace TX (transmission) packets.
bool m_useIphc
Use IPHC or HC1.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Shim performing 6LoWPAN compression, decompression and fragmentation.
This class implements the shim between IPv6 and a generic NetDevice, performing packet compression, decompression and fragmentation in a transparent way. To this end, the class pretend to be a normal NetDevice, masquerading some functions of the underlying NetDevice.
Config Paths
ns3::SixLowPanNetDevice is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::SixLowPanNetDevice"
Attributes
Rfc6282: Use RFC6282 (IPHC) if true, RFC4944 (HC1) otherwise.
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
OmitUdpChecksum: Omit the UDP checksum in IPHC compression.
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
FragmentReassemblyListSize: The maximum size of the reassembly buffer (in packets). Zero meaning infinite.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 0
Flags: construct write read
FragmentExpirationTimeout: When this timeout expires, the fragments will be cleared from the buffer.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +6e+10ns
Flags: construct write read
CompressionThreshold: The minimum MAC layer payload size.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 0
Flags: construct write read
ForceEtherType: Force a specific EtherType in L2 frames.
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
EtherType: The specific EtherType to be used in L2 frames.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 65535
Flags: construct write read
UseMeshUnder: Use a mesh-under routing protocol.
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
MeshUnderRadius: Hops Left to use in mesh-under.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Initial value: 10
Flags: construct write read
MeshCacheLength: Length of the cache for each source.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 10
Flags: construct write read
MeshUnderJitter: The jitter in ms a node uses to forward mesh-under packets - used to prevent collisions
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::RandomVariableStream>
Initial value: ns3::UniformRandomVariable[Min=0.0|Max=10.0]
Flags: construct write read
TraceSources
Tx: Send - packet (including 6LoWPAN header), SixLoWPanNetDevice Ptr, interface index.
Callback signature: ns3::SixLowPanNetDevice::RxTxTracedCallback
Rx: Receive - packet (including 6LoWPAN header), SixLoWPanNetDevice Ptr, interface index.
Callback signature: ns3::SixLowPanNetDevice::RxTxTracedCallback
Drop: Drop - DropReason, packet (including 6LoWPAN header), SixLoWPanNetDevice Ptr, interface index.
Callback signature: ns3::SixLowPanNetDevice::DropTracedCallback
Size of this type is 280 bytes (on a 64-bit architecture).
Definition at line 65 of file sixlowpan-net-device.h.
Member Typedef Documentation
DropTracedCallback
typedef void(* ns3::SixLowPanNetDevice::DropTracedCallback) (DropReason reason, Ptr< const Packet > packet, Ptr< SixLowPanNetDevice > sixNetDevice, uint32_t ifindex)
TracedCallback signature for.
Parameters
[in] reason The reason for the drop.
[in] packet The packet.
[in] sixNetDevice The SixLowPanNetDevice.
[in] ifindex The ifindex of the device.
Deprecated:
The non-const Ptr<SixLowPanNetDevice> argument is deprecated and will be changed to Ptr<const SixLowPanNetDevice> in a future release.
Definition at line 175 of file sixlowpan-net-device.h.
FragmentKey_t
typedef std::pair< std::pair<Address, Address>, std::pair<uint16_t, uint16_t> > ns3::SixLowPanNetDevice::FragmentKey_t private
Fragment identifier type: src/dst address src/dst port.
Definition at line 358 of file sixlowpan-net-device.h.
FragmentsTimeoutsList_t
typedef std::list< std::tuple <Time, FragmentKey_t, uint32_t > > ns3::SixLowPanNetDevice::FragmentsTimeoutsList_t private
Container for fragment timeouts.
Definition at line 361 of file sixlowpan-net-device.h.
FragmentsTimeoutsListI_t
typedef std::list< std::tuple <Time, FragmentKey_t, uint32_t > >::iterator ns3::SixLowPanNetDevice::FragmentsTimeoutsListI_t private
Container Iterator for fragment timeouts.
Definition at line 363 of file sixlowpan-net-device.h.
MapFragments_t
typedef std::map< FragmentKey_t, Ptr<Fragments> > ns3::SixLowPanNetDevice::MapFragments_t private
Container for fragment key -> fragments.
Definition at line 512 of file sixlowpan-net-device.h.
MapFragmentsI_t
typedef std::map< FragmentKey_t, Ptr<Fragments> >::iterator ns3::SixLowPanNetDevice::MapFragmentsI_t private
Container Iterator for fragment key -> fragments.
Definition at line 516 of file sixlowpan-net-device.h.
RxTxTracedCallback
typedef void(* ns3::SixLowPanNetDevice::RxTxTracedCallback) (Ptr< const Packet > packet, Ptr< SixLowPanNetDevice > sixNetDevice, uint32_t ifindex)
TracedCallback signature for packet send/receive events.
Parameters
[in] packet The packet.
[in] sixNetDevice The SixLowPanNetDevice.
[in] ifindex The ifindex of the device.
Deprecated:
The non-const Ptr<SixLowPanNetDevice> argument is deprecated and will be changed to Ptr<const SixLowPanNetDevice> in a future release.
Definition at line 160 of file sixlowpan-net-device.h.
Member Enumeration Documentation
DropReason
enum ns3::SixLowPanNetDevice::DropReason
Enumeration of the dropping reasons in SixLoWPAN.
Enumerator
DROP_FRAGMENT_TIMEOUT
Fragment timeout exceeded.
DROP_FRAGMENT_BUFFER_FULL
Fragment buffer size exceeded.
DROP_UNKNOWN_EXTENSION
Unsupported compression kind.
DROP_DISALLOWED_COMPRESSION
HC1 while in IPHC mode or viceversa.
Definition at line 71 of file sixlowpan-net-device.h.
Constructor & Destructor Documentation
SixLowPanNetDevice() [1/2]
ns3::SixLowPanNetDevice::SixLowPanNetDevice ()
Constructor for the SixLowPanNetDevice.
Definition at line 127 of file sixlowpan-net-device.cc.
References m_bc0Serial, m_netDevice, m_rng, and NS_LOG_FUNCTION.
SixLowPanNetDevice() [2/2]
ns3::SixLowPanNetDevice::SixLowPanNetDevice (SixLowPanNetDevice const &) private
Copy constructor.
Defined and unimplemented to avoid misuse.
Member Function Documentation
AddLinkChangeCallback()
void ns3::SixLowPanNetDevice::AddLinkChangeCallback (Callback< void > callback) virtual
Parameters
callback the callback to invoke
Add a callback invoked whenever the link status changes to UP. This callback is typically used by the IP/ARP layer to flush the ARP cache and by IPv6 stack to flush NDISC cache whenever the link goes up.
Implements ns3::NetDevice.
Definition at line 445 of file sixlowpan-net-device.cc.
References m_netDevice, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
AssignStreams()
int64_t ns3::SixLowPanNetDevice::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
[in] stream First stream index to use.
Returns
the number of stream indices assigned by this model.
Definition at line 161 of file sixlowpan-net-device.cc.
References m_meshUnderJitter, m_rng, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
CanCompressLowPanNhc()
bool ns3::SixLowPanNetDevice::CanCompressLowPanNhc (uint8_t headerType) private
Checks if the next header can be compressed using NHC.
Parameters
[in] headerType The header kind to be compressed.
Returns
True if the header can be compressed.
Definition at line 1156 of file sixlowpan-net-device.cc.
References ns3::Ipv6Header::IPV6_EXT_FRAGMENTATION, ns3::Ipv6Header::IPV6_EXT_HOP_BY_HOP, ns3::Ipv6Header::IPV6_EXT_MOBILITY, ns3::Ipv6Header::IPV6_EXT_ROUTING, ns3::Ipv6Header::IPV6_IPV6, and ns3::Ipv6Header::IPV6_UDP.
Referenced by CompressLowPanIphc(), and CompressLowPanNhc().
CompressLowPanHc1()
uint32_t ns3::SixLowPanNetDevice::CompressLowPanHc1 (Ptr< Packet > packet, Address const & src, Address const & dst) private
Compress the headers according to HC1 compression.
Parameters
[in] packet The packet to be compressed.
[in] src The MAC source address.
[in] dst The MAC destination address.
Returns
The size of the removed headers.
Definition at line 706 of file sixlowpan-net-device.cc.
References ns3::Packet::AddHeader(), ns3::Ipv6Address::GetBytes(), ns3::Ipv6Header::GetDestinationAddress(), ns3::Ipv6Header::GetFlowLabel(), ns3::Ipv6Header::GetHopLimit(), ns3::Ipv6Header::GetNextHeader(), ns3::Ipv6Header::GetSerializedSize(), ns3::SixLowPanHc1::GetSerializedSize(), ns3::Packet::GetSize(), ns3::Ipv6Header::GetSourceAddress(), ns3::Ipv6Header::GetTrafficClass(), ns3::SixLowPanHc1::HC1_PCIC, ns3::SixLowPanHc1::HC1_PCII, ns3::SixLowPanHc1::HC1_PIIC, ns3::SixLowPanHc1::HC1_PIII, ns3::Ipv6Address::IsLinkLocal(), ns3::Ipv6Address::MakeAutoconfiguredLinkLocalAddress(), NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Packet::PeekHeader(), ns3::Packet::RemoveHeader(), ns3::SixLowPanHc1::SetDstCompression(), ns3::SixLowPanHc1::SetDstInterface(), ns3::SixLowPanHc1::SetDstPrefix(), ns3::SixLowPanHc1::SetFlowLabel(), ns3::SixLowPanHc1::SetHc2HeaderPresent(), ns3::SixLowPanHc1::SetHopLimit(), ns3::SixLowPanHc1::SetNextHeader(), ns3::SixLowPanHc1::SetSrcCompression(), ns3::SixLowPanHc1::SetSrcInterface(), ns3::SixLowPanHc1::SetSrcPrefix(), ns3::SixLowPanHc1::SetTcflCompression(), and ns3::SixLowPanHc1::SetTrafficClass().
Referenced by DoSend().
CompressLowPanIphc()
uint32_t ns3::SixLowPanNetDevice::CompressLowPanIphc (Ptr< Packet > packet, Address const & src, Address const & dst) private
Compress the headers according to IPHC compression.
Parameters
[in] packet The packet to be compressed.
[in] src The MAC source address.
[in] dst The MAC destination address.
Returns
The size of the removed headers.
Definition at line 929 of file sixlowpan-net-device.cc.
References ns3::Packet::AddHeader(), CanCompressLowPanNhc(), CompressLowPanNhc(), CompressLowPanUdpNhc(), ns3::Ipv6Address::GetBytes(), ns3::Ipv6Header::GetDestinationAddress(), ns3::Ipv6Header::GetFlowLabel(), ns3::Ipv6Header::GetHopLimit(), ns3::SixLowPanIphc::GetM(), ns3::Ipv6Header::GetNextHeader(), ns3::Ipv6Header::GetSerializedSize(), ns3::SixLowPanIphc::GetSerializedSize(), ns3::Packet::GetSize(), ns3::Ipv6Header::GetSourceAddress(), ns3::Ipv6Header::GetTrafficClass(), ns3::SixLowPanIphc::HC_COMPR_0, ns3::SixLowPanIphc::HC_COMPR_16, ns3::SixLowPanIphc::HC_COMPR_64, ns3::SixLowPanIphc::HC_INLINE, ns3::SixLowPanIphc::HLIM_COMPR_1, ns3::SixLowPanIphc::HLIM_COMPR_255, ns3::SixLowPanIphc::HLIM_COMPR_64, ns3::SixLowPanIphc::HLIM_INLINE, ns3::Ipv6Header::IPV6_IPV6, ns3::Ipv6Header::IPV6_UDP, ns3::Ipv6Address::IsLinkLocal(), ns3::Ipv6Address::IsMulticast(), m_omitUdpChecksum, ns3::Ipv6Address::MakeAutoconfiguredLinkLocalAddress(), NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Packet::PeekHeader(), ns3::Packet::RemoveHeader(), ns3::SixLowPanIphc::SetCid(), ns3::SixLowPanIphc::SetDac(), ns3::SixLowPanIphc::SetDam(), ns3::SixLowPanIphc::SetDscp(), ns3::SixLowPanIphc::SetDstAddress(), ns3::SixLowPanIphc::SetEcn(), ns3::SixLowPanIphc::SetFlowLabel(), ns3::SixLowPanIphc::SetHlim(), ns3::SixLowPanIphc::SetHopLimit(), ns3::SixLowPanIphc::SetM(), ns3::SixLowPanIphc::SetNextHeader(), ns3::SixLowPanIphc::SetNh(), ns3::SixLowPanIphc::SetSac(), ns3::SixLowPanIphc::SetSam(), ns3::SixLowPanIphc::SetSrcAddress(), ns3::SixLowPanIphc::SetTf(), ns3::SixLowPanIphc::TF_DSCP_ELIDED, ns3::SixLowPanIphc::TF_ELIDED, ns3::SixLowPanIphc::TF_FL_ELIDED, and ns3::SixLowPanIphc::TF_FULL.
Referenced by CompressLowPanNhc(), and DoSend().
CompressLowPanNhc()
uint32_t ns3::SixLowPanNetDevice::CompressLowPanNhc (Ptr< Packet > packet, uint8_t headerType, Address const & src, Address const & dst) private
Compress the headers according to NHC compression.
Parameters
[in] packet The packet to be compressed.
[in] headerType The header type.
[in] src The MAC source address.
[in] dst The MAC destination address.
Returns
The size of the removed headers.
Definition at line 1302 of file sixlowpan-net-device.cc.
References ns3::Buffer::AddAtStart(), ns3::Packet::AddHeader(), ns3::Buffer::Begin(), CanCompressLowPanNhc(), CompressLowPanIphc(), CompressLowPanUdpNhc(), ns3::SixLowPanNhcExtension::EID_DESTINATION_OPTIONS_H, ns3::SixLowPanNhcExtension::EID_FRAGMENTATION_H, ns3::SixLowPanNhcExtension::EID_HOPBYHOP_OPTIONS_H, ns3::SixLowPanNhcExtension::EID_ROUTING_H, ns3::Ipv6ExtensionHeader::GetLength(), ns3::Ipv6ExtensionHeader::GetNextHeader(), ns3::Ipv6ExtensionHopByHopHeader::GetSerializedSize(), ns3::Ipv6ExtensionDestinationHeader::GetSerializedSize(), ns3::Ipv6ExtensionFragmentHeader::GetSerializedSize(), ns3::Ipv6ExtensionRoutingHeader::GetSerializedSize(), ns3::SixLowPanNhcExtension::GetSerializedSize(), ns3::Buffer::GetSize(), ns3::Packet::GetSize(), ns3::Ipv6Header::IPV6_EXT_DESTINATION, ns3::Ipv6Header::IPV6_EXT_FRAGMENTATION, ns3::Ipv6Header::IPV6_EXT_HOP_BY_HOP, ns3::Ipv6Header::IPV6_EXT_MOBILITY, ns3::Ipv6Header::IPV6_EXT_ROUTING, ns3::Ipv6Header::IPV6_IPV6, ns3::Ipv6Header::IPV6_UDP, m_omitUdpChecksum, NS_ABORT_MSG, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Buffer::PeekData(), ns3::Packet::PeekHeader(), ns3::Buffer::RemoveAtStart(), ns3::Packet::RemoveHeader(), ns3::Ipv6ExtensionHopByHopHeader::Serialize(), ns3::Ipv6ExtensionDestinationHeader::Serialize(), ns3::Ipv6ExtensionFragmentHeader::Serialize(), ns3::Ipv6ExtensionRoutingHeader::Serialize(), ns3::SixLowPanNhcExtension::SetBlob(), ns3::SixLowPanNhcExtension::SetEid(), ns3::SixLowPanNhcExtension::SetNextHeader(), and ns3::SixLowPanNhcExtension::SetNh().
Referenced by CompressLowPanIphc().
CompressLowPanUdpNhc()
uint32_t ns3::SixLowPanNetDevice::CompressLowPanUdpNhc (Ptr< Packet > packet, bool omitChecksum) private
Compress the headers according to NHC compression.
Parameters
[in] packet The packet to be compressed.
[in] omitChecksum Omit UDP checksum (if true).
Returns
The size of the removed headers.
Definition at line 1774 of file sixlowpan-net-device.cc.
References ns3::Packet::AddHeader(), ns3::UdpHeader::GetChecksum(), ns3::UdpHeader::GetDestinationPort(), ns3::SixLowPanUdpNhcExtension::GetSerializedSize(), ns3::Packet::GetSize(), ns3::UdpHeader::GetSourcePort(), ns3::UdpHeader::IsChecksumOk(), NS_ASSERT_MSG, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Packet::PeekHeader(), ns3::SixLowPanUdpNhcExtension::PORTS_ALL_SRC_LAST_DST, ns3::SixLowPanUdpNhcExtension::PORTS_INLINE, ns3::SixLowPanUdpNhcExtension::PORTS_LAST_SRC_ALL_DST, ns3::SixLowPanUdpNhcExtension::PORTS_LAST_SRC_LAST_DST, ns3::Packet::RemoveHeader(), ns3::SixLowPanUdpNhcExtension::SetC(), ns3::SixLowPanUdpNhcExtension::SetChecksum(), ns3::SixLowPanUdpNhcExtension::SetDstPort(), ns3::SixLowPanUdpNhcExtension::SetPorts(), and ns3::SixLowPanUdpNhcExtension::SetSrcPort().
Referenced by CompressLowPanIphc(), and CompressLowPanNhc().
DecompressLowPanHc1()
void ns3::SixLowPanNetDevice::DecompressLowPanHc1 (Ptr< Packet > packet, Address const & src, Address const & dst) private
Decompress the headers according to HC1 compression.
Parameters
[in] packet the packet to be compressed.
[in] src the MAC source address.
[in] dst the MAC destination address.
Definition at line 812 of file sixlowpan-net-device.cc.
References ns3::Packet::AddHeader(), first::address, ns3::SixLowPanHc1::GetDstCompression(), ns3::SixLowPanHc1::GetDstPrefix(), ns3::SixLowPanHc1::GetFlowLabel(), ns3::SixLowPanHc1::GetHopLimit(), ns3::SixLowPanHc1::GetNextHeader(), ns3::Packet::GetSize(), ns3::SixLowPanHc1::GetSrcCompression(), ns3::SixLowPanHc1::GetSrcPrefix(), ns3::SixLowPanHc1::GetTrafficClass(), ns3::SixLowPanHc1::HC1_PCIC, ns3::SixLowPanHc1::HC1_PCII, ns3::SixLowPanHc1::HC1_PIIC, ns3::SixLowPanHc1::HC1_PIII, ns3::SixLowPanHc1::IsHc2HeaderPresent(), ns3::SixLowPanHc1::IsTcflCompression(), ns3::Ipv6Address::MakeAutoconfiguredAddress(), ns3::Ipv6Address::MakeAutoconfiguredLinkLocalAddress(), NS_ASSERT_MSG, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_UNUSED, ns3::Packet::RemoveHeader(), ns3::Ipv6Header::SetDestinationAddress(), ns3::Ipv6Header::SetFlowLabel(), ns3::Ipv6Header::SetHopLimit(), ns3::Ipv6Header::SetNextHeader(), ns3::Ipv6Header::SetPayloadLength(), ns3::Ipv6Header::SetSourceAddress(), and ns3::Ipv6Header::SetTrafficClass().
Referenced by ProcessFragment(), and ReceiveFromDevice().
DecompressLowPanIphc()
void ns3::SixLowPanNetDevice::DecompressLowPanIphc (Ptr< Packet > packet, Address const & src, Address const & dst) private
Decompress the headers according to IPHC compression.
Parameters
[in] packet The packet to be compressed.
[in] src The MAC source address.
[in] dst The MAC destination address.
Definition at line 1177 of file sixlowpan-net-device.cc.
References ns3::Packet::AddHeader(), ns3::Packet::CopyData(), DecompressLowPanNhc(), DecompressLowPanUdpNhc(), ns3::Ipv6Address::GetAny(), ns3::SixLowPanIphc::GetDac(), ns3::SixLowPanIphc::GetDam(), ns3::Ipv6Header::GetDestinationAddress(), ns3::SixLowPanIphc::GetDscp(), ns3::SixLowPanIphc::GetDstAddress(), ns3::SixLowPanIphc::GetEcn(), ns3::SixLowPanIphc::GetFlowLabel(), ns3::SixLowPanIphc::GetHopLimit(), ns3::SixLowPanIphc::GetM(), ns3::SixLowPanIphc::GetNextHeader(), ns3::SixLowPanIphc::GetNh(), ns3::SixLowPanDispatch::GetNhcDispatchType(), ns3::SixLowPanIphc::GetSac(), ns3::SixLowPanIphc::GetSam(), ns3::Packet::GetSize(), ns3::Ipv6Header::GetSourceAddress(), ns3::SixLowPanIphc::GetSrcAddress(), ns3::SixLowPanIphc::GetTf(), ns3::SixLowPanIphc::HC_COMPR_0, ns3::SixLowPanIphc::HC_COMPR_16, ns3::SixLowPanIphc::HC_COMPR_64, ns3::SixLowPanIphc::HC_INLINE, ns3::Ipv6Header::IPV6_UDP, ns3::SixLowPanDispatch::LOWPAN_UDPNHC, ns3::Ipv6Address::MakeAutoconfiguredLinkLocalAddress(), NS_ABORT_MSG, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_UNUSED, ns3::Packet::RemoveHeader(), ns3::Ipv6Header::SetDestinationAddress(), ns3::Ipv6Header::SetFlowLabel(), ns3::Ipv6Header::SetHopLimit(), ns3::Ipv6Header::SetNextHeader(), ns3::Ipv6Header::SetPayloadLength(), ns3::Ipv6Header::SetSourceAddress(), ns3::Ipv6Header::SetTrafficClass(), ns3::SixLowPanIphc::TF_DSCP_ELIDED, ns3::SixLowPanIphc::TF_ELIDED, ns3::SixLowPanIphc::TF_FL_ELIDED, and ns3::SixLowPanIphc::TF_FULL.
Referenced by DecompressLowPanNhc(), ProcessFragment(), and ReceiveFromDevice().
DecompressLowPanNhc()
uint8_t ns3::SixLowPanNetDevice::DecompressLowPanNhc (Ptr< Packet > packet, Address const & src, Address const & dst, Ipv6Address srcAddress, Ipv6Address dstAddress) private
Decompress the headers according to NHC compression.
Parameters
[in] packet The packet to be compressed.
[in] src The MAC source address.
[in] dst The MAC destination address.
[in] srcAddress The IPv6 source address.
[in] dstAddress The IPv6 destination address.
Returns
The decompressed header type.
Definition at line 1561 of file sixlowpan-net-device.cc.
References ns3::Buffer::AddAtStart(), ns3::Packet::AddHeader(), ns3::Buffer::Begin(), ns3::SixLowPanNhcExtension::CopyBlob(), ns3::Packet::CopyData(), DecompressLowPanIphc(), DecompressLowPanUdpNhc(), ns3::Ipv6ExtensionHopByHopHeader::Deserialize(), ns3::Ipv6ExtensionDestinationHeader::Deserialize(), ns3::Ipv6ExtensionFragmentHeader::Deserialize(), ns3::Ipv6ExtensionRoutingHeader::Deserialize(), ns3::SixLowPanNhcExtension::EID_DESTINATION_OPTIONS_H, ns3::SixLowPanNhcExtension::EID_FRAGMENTATION_H, ns3::SixLowPanNhcExtension::EID_HOPBYHOP_OPTIONS_H, ns3::SixLowPanNhcExtension::EID_IPv6_H, ns3::SixLowPanNhcExtension::EID_MOBILITY_H, ns3::SixLowPanNhcExtension::EID_ROUTING_H, ns3::SixLowPanNhcExtension::GetEid(), ns3::SixLowPanNhcExtension::GetNextHeader(), ns3::SixLowPanNhcExtension::GetNh(), ns3::SixLowPanDispatch::GetNhcDispatchType(), ns3::Packet::GetSize(), ns3::Ipv6Header::IPV6_EXT_DESTINATION, ns3::Ipv6Header::IPV6_EXT_FRAGMENTATION, ns3::Ipv6Header::IPV6_EXT_HOP_BY_HOP, ns3::Ipv6Header::IPV6_EXT_ROUTING, ns3::Ipv6Header::IPV6_IPV6, ns3::Ipv6Header::IPV6_UDP, ns3::SixLowPanDispatch::LOWPAN_UDPNHC, NS_ABORT_MSG, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_UNUSED, ns3::Packet::RemoveHeader(), and ns3::Buffer::Iterator::Write().
Referenced by DecompressLowPanIphc().
DecompressLowPanUdpNhc()
void ns3::SixLowPanNetDevice::DecompressLowPanUdpNhc (Ptr< Packet > packet, Ipv6Address saddr, Ipv6Address daddr) private
Decompress the headers according to NHC compression.
Parameters
[in] packet The packet to be compressed.
[in] saddr The IPv6 source address.
[in] daddr The IPv6 destination address.
Definition at line 1829 of file sixlowpan-net-device.cc.
References ns3::Packet::AddHeader(), ns3::Node::ChecksumEnabled(), ns3::UdpHeader::EnableChecksums(), ns3::UdpHeader::ForceChecksum(), ns3::SixLowPanUdpNhcExtension::GetC(), ns3::SixLowPanUdpNhcExtension::GetChecksum(), ns3::SixLowPanUdpNhcExtension::GetDstPort(), ns3::SixLowPanUdpNhcExtension::GetPorts(), ns3::Packet::GetSize(), ns3::SixLowPanUdpNhcExtension::GetSrcPort(), ns3::UdpHeader::InitializeChecksum(), ns3::UdpHeader::IsChecksumOk(), NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, NS_UNUSED, ns3::SixLowPanUdpNhcExtension::PORTS_ALL_SRC_LAST_DST, ns3::SixLowPanUdpNhcExtension::PORTS_INLINE, ns3::SixLowPanUdpNhcExtension::PORTS_LAST_SRC_ALL_DST, ns3::SixLowPanUdpNhcExtension::PORTS_LAST_SRC_LAST_DST, ns3::UdpL4Protocol::PROT_NUMBER, ns3::Packet::RemoveHeader(), ns3::UdpHeader::SetDestinationPort(), and ns3::UdpHeader::SetSourcePort().
Referenced by DecompressLowPanIphc(), and DecompressLowPanNhc().
DoDispose()
void ns3::SixLowPanNetDevice::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 169 of file sixlowpan-net-device.cc.
References ns3::EventId::Cancel(), ns3::Object::DoDispose(), ns3::EventId::IsRunning(), m_fragments, m_netDevice, m_node, m_timeoutEvent, m_timeoutEventList, and NS_LOG_FUNCTION.
DoFragmentation()
void ns3::SixLowPanNetDevice::DoFragmentation (Ptr< Packet > packet, uint32_t origPacketSize, uint32_t origHdrSize, std::list< Ptr< Packet > > & listFragments) private
Performs a packet fragmentation.
Parameters
[in] packet the packet to be fragmented (with headers already compressed with 6LoWPAN).
[in] origPacketSize the size of the IP packet before the 6LoWPAN header compression, including the IP/L4 headers.
[in] origHdrSize the size of the IP header before the 6LoWPAN header compression.
[out] listFragments A reference to the list of the resulting packets, all with the proper headers in place.
Definition at line 1898 of file sixlowpan-net-device.cc.
References ns3::Packet::AddHeader(), ns3::Packet::Copy(), ns3::Packet::CreateFragment(), ns3::SixLowPanFrag1::GetSerializedSize(), ns3::SixLowPanFragN::GetSerializedSize(), ns3::Packet::GetSize(), ns3::UniformRandomVariable::GetValue(), m_netDevice, m_rng, NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, packetSize, ns3::SixLowPanFragN::SetDatagramOffset(), ns3::SixLowPanFrag1::SetDatagramSize(), ns3::SixLowPanFragN::SetDatagramSize(), ns3::SixLowPanFrag1::SetDatagramTag(), and ns3::SixLowPanFragN::SetDatagramTag().
Referenced by DoSend().
DoSend()
bool ns3::SixLowPanNetDevice::DoSend (Ptr< Packet > packet, const Address & source, const Address & dest, uint16_t protocolNumber, bool doSendFrom) private
Parameters
[in] packet Packet sent from above down to Network Device.
[in] source Source mac address (only used if doSendFrom is true, i.e., "MAC spoofing").
[in] dest Mac address of the destination (already resolved).
[in] protocolNumber Identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
[in] doSendFrom Perform a SendFrom instead of a Send.
Called from higher layer to send packet into Network Device with the specified source and destination Addresses.
Returns
Whether the Send operation succeeded.
Definition at line 533 of file sixlowpan-net-device.cc.
References ns3::Packet::AddHeader(), CompressLowPanHc1(), CompressLowPanIphc(), ns3::Packet::Copy(), DoFragmentation(), Get16MacFrom48Mac(), ns3::Node::GetId(), GetIfIndex(), ns3::Object::GetObject(), ns3::SixLowPanBc0::GetSerializedSize(), ns3::SixLowPanMesh::GetSerializedSize(), ns3::Packet::GetSize(), ns3::Mac48Address::IsMatchingType(), m_bc0Serial, m_compressionThreshold, m_etherType, m_forceEtherType, m_meshUnder, m_meshUnderHopsLeft, m_netDevice, m_node, m_txTrace, m_useIphc, NS_ASSERT_MSG, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, pktSize, ns3::SixLowPanMesh::SetFinalDst(), ns3::SixLowPanMesh::SetHopsLeft(), ns3::SixLowPanMesh::SetOriginator(), and ns3::SixLowPanBc0::SetSequenceNumber().
Referenced by Send(), and SendFrom().
DropOldestFragmentSet()
void ns3::SixLowPanNetDevice::DropOldestFragmentSet () private
Drops the oldest fragment set.
Get16MacFrom48Mac()
Address ns3::SixLowPanNetDevice::Get16MacFrom48Mac (Address addr) private
Get a Mac16 from its Mac48 pseudo-MAC.
Parameters
addr the PseudoMac address
Returns
the Mac16Address
Definition at line 2249 of file sixlowpan-net-device.cc.
References ns3::Mac16Address::CopyFrom(), ns3::Address::CopyTo(), ns3::Mac48Address::IsMatchingType(), and NS_ASSERT_MSG.
Referenced by DoSend(), and ReceiveFromDevice().
GetAddress()
Address ns3::SixLowPanNetDevice::GetAddress (void) const virtual
Returns
the current Address of this interface.
Implements ns3::NetDevice.
Definition at line 407 of file sixlowpan-net-device.cc.
References m_netDevice, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
GetBroadcast()
Address ns3::SixLowPanNetDevice::GetBroadcast (void) const virtual
Returns
the broadcast address supported by this netdevice.
Calling this method is invalid if IsBroadcast returns not true.
Implements ns3::NetDevice.
Definition at line 461 of file sixlowpan-net-device.cc.
References m_netDevice, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
GetChannel()
Ptr< Channel > ns3::SixLowPanNetDevice::GetChannel (void) const virtual
Returns
the channel this NetDevice is connected to. The value returned can be zero if the NetDevice is not yet connected to any channel or if the underlying NetDevice has no concept of a channel. i.e., callers must check for zero and be ready to handle it.
Implements ns3::NetDevice.
Definition at line 391 of file sixlowpan-net-device.cc.
References m_netDevice, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
GetIfIndex()
uint32_t ns3::SixLowPanNetDevice::GetIfIndex (void) const virtual
Returns
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 385 of file sixlowpan-net-device.cc.
References m_ifIndex, and NS_LOG_FUNCTION.
Referenced by DoSend(), ProcessFragment(), and ReceiveFromDevice().
GetMtu()
uint16_t ns3::SixLowPanNetDevice::GetMtu (void) const virtual
Returns the link-layer MTU for this interface.
If the link-layer MTU is smaller than IPv6's minimum MTU (RFC 4944), 1280 will be returned.
Returns
The link-level MTU in bytes for this interface.
Implements ns3::NetDevice.
Definition at line 423 of file sixlowpan-net-device.cc.
References m_netDevice, and NS_LOG_FUNCTION.
GetMulticast() [1/2]
Address ns3::SixLowPanNetDevice::GetMulticast (Ipv4Address multicastGroup) const virtual
Make and return a MAC multicast address using the provided multicast group.
RFC 1112 says that an Ipv4 host group address is mapped to an Ethernet multicast address by placing the low-order 23-bits of the IP address into the low-order 23 bits of the Ethernet multicast address 01-00-5E-00-00-00 (hex). Similar RFCs exist for Ipv6 and Eui64 mappings. This method performs the multicast address creation function appropriate to the underlying MAC address of the device. This MAC address is encapsulated in an abstract Address to avoid dependencies on the exact MAC address format.
In the case of net devices that do not support multicast, clients are expected to test NetDevice::IsMulticast and avoid attempting to map multicast packets. Subclasses of NetDevice that do support multicasting are expected to override this method and provide an implementation appropriate to the particular device.
Parameters
multicastGroup The IP address for the multicast group destination of the packet.
Returns
The MAC multicast Address used to send packets to the provided multicast group.
Warning
Calling this method is invalid if IsMulticast returns not true.
See also
IsMulticast()
Implements ns3::NetDevice.
Definition at line 477 of file sixlowpan-net-device.cc.
References m_netDevice, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
GetMulticast() [2/2]
Address ns3::SixLowPanNetDevice::GetMulticast (Ipv6Address addr) const virtual
Get the MAC multicast address corresponding to the IPv6 address provided.
Parameters
addr IPv6 address
Returns
the MAC multicast address
Warning
Calling this method is invalid if IsMulticast returns not true.
Implements ns3::NetDevice.
Definition at line 485 of file sixlowpan-net-device.cc.
References m_netDevice, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
GetNetDevice()
Ptr< NetDevice > ns3::SixLowPanNetDevice::GetNetDevice () const
Returns a smart pointer to the underlying NetDevice.
Returns
A smart pointer to the underlying NetDevice.
Definition at line 138 of file sixlowpan-net-device.cc.
References m_netDevice, and NS_LOG_FUNCTION.
GetNode()
Ptr< Node > ns3::SixLowPanNetDevice::GetNode (void) const virtual
Returns
the node base class which contains this network interface.
When a subclass needs to get access to the underlying node base class to print the nodeid for example, it can invoke this method.
Implements ns3::NetDevice.
Definition at line 667 of file sixlowpan-net-device.cc.
References m_node, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::SixLowPanNetDevice::GetTypeId (void) static
Get the type ID.
Returns
The object TypeId.
Definition at line 49 of file sixlowpan-net-device.cc.
References m_compressionThreshold, m_dropTrace, m_etherType, m_forceEtherType, m_fragmentExpirationTimeout, m_fragmentReassemblyListSize, m_meshCacheLength, m_meshUnder, m_meshUnderHopsLeft, m_meshUnderJitter, m_omitUdpChecksum, m_rxTrace, m_txTrace, m_useIphc, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakePointerAccessor(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), ns3::Seconds(), and ns3::TypeId::SetParent().
HandleFragmentsTimeout()
void ns3::SixLowPanNetDevice::HandleFragmentsTimeout (FragmentKey_t key, uint32_t iif) private
Process the timeout for packet fragments.
Parameters
[in] key A key representing the packet fragments.
[in] iif Input Interface.
Definition at line 2232 of file sixlowpan-net-device.cc.
References DROP_FRAGMENT_TIMEOUT, ns3::Object::GetObject(), list, m_dropTrace, m_fragments, m_node, and NS_LOG_FUNCTION.
Referenced by HandleTimeout().
HandleTimeout()
void ns3::SixLowPanNetDevice::HandleTimeout (void) private
Handles a fragmented packet timeout.
Definition at line 2275 of file sixlowpan-net-device.cc.
References HandleFragmentsTimeout(), m_timeoutEvent, m_timeoutEventList, ns3::Simulator::Now(), and ns3::Simulator::Schedule().
Referenced by SetTimeout().
IsBridge()
bool ns3::SixLowPanNetDevice::IsBridge (void) const virtual
Return true if the net device is acting as a bridge.
Returns
value of m_isBridge flag
Implements ns3::NetDevice.
Definition at line 501 of file sixlowpan-net-device.cc.
References m_netDevice, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
IsBroadcast()
bool ns3::SixLowPanNetDevice::IsBroadcast (void) const virtual
Returns
true if this interface supports a broadcast address, false otherwise.
Implements ns3::NetDevice.
Definition at line 453 of file sixlowpan-net-device.cc.
References m_netDevice, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
IsLinkUp()
bool ns3::SixLowPanNetDevice::IsLinkUp (void) const virtual
Returns
true if link is up; false otherwise
Implements ns3::NetDevice.
Definition at line 437 of file sixlowpan-net-device.cc.
References m_netDevice, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
IsMulticast()
bool ns3::SixLowPanNetDevice::IsMulticast (void) const virtual
Returns
value of m_isMulticast flag
Implements ns3::NetDevice.
Definition at line 469 of file sixlowpan-net-device.cc.
References m_netDevice, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
IsPointToPoint()
bool ns3::SixLowPanNetDevice::IsPointToPoint (void) const virtual
Return true if the net device is on a point-to-point link.
Returns
value of m_isPointToPoint flag
Implements ns3::NetDevice.
Definition at line 493 of file sixlowpan-net-device.cc.
References m_netDevice, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
NeedsArp()
bool ns3::SixLowPanNetDevice::NeedsArp (void) const virtual
Returns
true if ARP is needed, false otherwise.
Called by higher-layers to check if this NetDevice requires ARP to be used.
Implements ns3::NetDevice.
Definition at line 679 of file sixlowpan-net-device.cc.
References m_netDevice, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
operator=()
SixLowPanNetDevice& ns3::SixLowPanNetDevice::operator= (SixLowPanNetDevice const &) private
Copy constructor.
Defined and unimplemented to avoid misuse.
Returns
ProcessFragment()
bool ns3::SixLowPanNetDevice::ProcessFragment (Ptr< Packet > & packet, Address const & src, Address const & dst, bool isFirst) private
Process a packet fragment.
Parameters
[in] packet The packet.
[in] src The source MAC address.
[in] dst The destination MAC address.
[in] isFirst True if it is the first fragment, false otherwise.
Returns
True is the fragment completed the packet.
Definition at line 1970 of file sixlowpan-net-device.cc.
References ns3::SixLowPanNetDevice::Fragments::AddFirstFragment(), ns3::SixLowPanNetDevice::Fragments::AddFragment(), ns3::Packet::Copy(), ns3::Packet::CopyData(), DecompressLowPanHc1(), DecompressLowPanIphc(), DROP_FRAGMENT_BUFFER_FULL, ns3::SixLowPanFragN::GetDatagramOffset(), ns3::SixLowPanFrag1::GetDatagramSize(), ns3::SixLowPanFragN::GetDatagramSize(), ns3::SixLowPanFrag1::GetDatagramTag(), ns3::SixLowPanFragN::GetDatagramTag(), ns3::SixLowPanDispatch::GetDispatchType(), GetIfIndex(), ns3::Object::GetObject(), ns3::SixLowPanNetDevice::Fragments::GetPacket(), ns3::Packet::GetSize(), ns3::SixLowPanNetDevice::Fragments::GetTimeoutIter(), ns3::SixLowPanNetDevice::Fragments::IsEntire(), list, ns3::SixLowPanDispatch::LOWPAN_HC1, ns3::SixLowPanDispatch::LOWPAN_IPHC, ns3::SixLowPanDispatch::LOWPAN_IPv6, m_dropTrace, m_fragmentReassemblyListSize, m_fragments, m_node, m_timeoutEventList, NS_FATAL_ERROR, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, packetSize, ns3::Packet::RemoveHeader(), ns3::SixLowPanNetDevice::Fragments::SetPacketSize(), SetTimeout(), and ns3::SixLowPanNetDevice::Fragments::SetTimeoutIter().
Referenced by ReceiveFromDevice().
ReceiveFromDevice()
void ns3::SixLowPanNetDevice::ReceiveFromDevice (Ptr< NetDevice > device, Ptr< const Packet > packet, uint16_t protocol, Address const & source, Address const & destination, PacketType packetType) private
Receives all the packets from a NetDevice for further processing.
Parameters
[in] device The NetDevice the packet ws received from.
[in] packet The received packet.
[in] protocol The protocol (if known).
[in] source The source address.
[in] destination The destination address.
[in] packetType The packet kind (e.g., HOST, BROADCAST, etc.).
Returns
The IPv6 link-local address.
Definition at line 191 of file sixlowpan-net-device.cc.
References ns3::Packet::AddHeader(), ns3::Mac16Address::ConvertFrom(), ns3::Packet::Copy(), ns3::Packet::CopyData(), DecompressLowPanHc1(), DecompressLowPanIphc(), DROP_DISALLOWED_COMPRESSION, DROP_UNKNOWN_EXTENSION, Get16MacFrom48Mac(), ns3::SixLowPanDispatch::GetDispatchType(), ns3::SixLowPanMesh::GetFinalDst(), ns3::SixLowPanMesh::GetHopsLeft(), GetIfIndex(), ns3::Object::GetObject(), ns3::SixLowPanMesh::GetOriginator(), ns3::SixLowPanBc0::GetSequenceNumber(), ns3::Packet::GetSize(), ns3::RandomVariableStream::GetValue(), ns3::Mac16Address::IsBroadcast(), ns3::Mac16Address::IsMatchingType(), ns3::Mac48Address::IsMatchingType(), ns3::Mac16Address::IsMulticast(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), ns3::SixLowPanDispatch::LOWPAN_BC0, ns3::SixLowPanDispatch::LOWPAN_FRAG1, ns3::SixLowPanDispatch::LOWPAN_FRAGN, ns3::SixLowPanDispatch::LOWPAN_HC1, ns3::SixLowPanDispatch::LOWPAN_IPHC, ns3::SixLowPanDispatch::LOWPAN_IPv6, ns3::SixLowPanDispatch::LOWPAN_MESH, m_dropTrace, m_meshCacheLength, m_meshUnderJitter, m_netDevice, m_node, m_promiscRxCallback, m_rxCallback, m_rxTrace, m_seenPkts, m_useIphc, ns3::MilliSeconds(), NS_ABORT_MSG_IF, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, ProcessFragment(), ns3::Ipv6L3Protocol::PROT_NUMBER, ns3::Packet::RemoveHeader(), ns3::Simulator::Schedule(), ns3::NetDevice::Send(), and ns3::SixLowPanMesh::SetHopsLeft().
Referenced by SetNetDevice().
Send()
bool ns3::SixLowPanNetDevice::Send (Ptr< Packet > packet, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device to the specified destination Address
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 509 of file sixlowpan-net-device.cc.
References DoSend(), and NS_LOG_FUNCTION.
SendFrom()
bool ns3::SixLowPanNetDevice::SendFrom (Ptr< Packet > packet, const Address & source, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
source source mac address (so called "MAC spoofing")
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device with the specified source and destination Addresses.
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 521 of file sixlowpan-net-device.cc.
References DoSend(), and NS_LOG_FUNCTION.
SetAddress()
void ns3::SixLowPanNetDevice::SetAddress (Address address) virtual
Set the address of this interface.
Parameters
address address to set
Implements ns3::NetDevice.
Definition at line 399 of file sixlowpan-net-device.cc.
References first::address, m_netDevice, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
SetIfIndex()
void ns3::SixLowPanNetDevice::SetIfIndex (const uint32_t index) virtual
Parameters
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 379 of file sixlowpan-net-device.cc.
References m_ifIndex, and NS_LOG_FUNCTION.
SetMtu()
bool ns3::SixLowPanNetDevice::SetMtu (const uint16_t mtu) virtual
Parameters
mtu MTU value, in bytes, to set for the device
Returns
whether the MTU value was within legal bounds
Override for default MTU defined on a per-type basis.
Implements ns3::NetDevice.
Definition at line 415 of file sixlowpan-net-device.cc.
References m_netDevice, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
SetNetDevice()
void ns3::SixLowPanNetDevice::SetNetDevice (Ptr< NetDevice > device)
Setup SixLowPan to be a proxy for the specified NetDevice.
All the packets incoming and outgoing from the NetDevice will be processed by SixLowPanNetDevice.
Parameters
[in] device A smart pointer to the NetDevice to be proxied.
Definition at line 144 of file sixlowpan-net-device.cc.
References m_etherType, m_forceEtherType, m_netDevice, m_node, ns3::MakeCallback(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ReceiveFromDevice(), and ns3::Node::RegisterProtocolHandler().
SetNode()
void ns3::SixLowPanNetDevice::SetNode (Ptr< Node > node) virtual
Parameters
node the node associated to this netdevice.
This method is called from ns3::Node::AddDevice.
Implements ns3::NetDevice.
Definition at line 673 of file sixlowpan-net-device.cc.
References m_node, and NS_LOG_FUNCTION.
SetPromiscReceiveCallback()
void ns3::SixLowPanNetDevice::SetPromiscReceiveCallback (NetDevice::PromiscReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received in promiscuous mode and must be forwarded to the higher layers.
Enables netdevice promiscuous mode and sets the callback that will handle promiscuous mode packets. Note, promiscuous mode packets means all packets, including those packets that can be sensed by the netdevice but which are intended to be received by other hosts.
Implements ns3::NetDevice.
Definition at line 693 of file sixlowpan-net-device.cc.
References m_promiscRxCallback, and NS_LOG_FUNCTION.
SetReceiveCallback()
void ns3::SixLowPanNetDevice::SetReceiveCallback (NetDevice::ReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received and must be forwarded to the higher layers.
Set the callback to be used to notify higher layers when a packet has been received.
Implements ns3::NetDevice.
Definition at line 687 of file sixlowpan-net-device.cc.
References m_rxCallback, and NS_LOG_FUNCTION.
SetTimeout()
SixLowPanNetDevice::FragmentsTimeoutsListI_t ns3::SixLowPanNetDevice::SetTimeout (FragmentKey_t key, uint32_t iif) private
Set a new timeout "event" for a fragmented packet.
Parameters
key the fragment identification
iif input interface of the packet
Returns
an iterator to the inserted "event"
Definition at line 2262 of file sixlowpan-net-device.cc.
References HandleTimeout(), m_fragmentExpirationTimeout, m_timeoutEvent, m_timeoutEventList, ns3::Simulator::Now(), and ns3::Simulator::Schedule().
Referenced by ProcessFragment().
SupportsSendFrom()
bool ns3::SixLowPanNetDevice::SupportsSendFrom () const virtual
Returns
true if this interface supports a bridging mode, false otherwise.
Implements ns3::NetDevice.
Definition at line 699 of file sixlowpan-net-device.cc.
References NS_LOG_FUNCTION.
Member Data Documentation
m_bc0Serial
uint8_t ns3::SixLowPanNetDevice::m_bc0Serial private
Serial number used in BC0 header.
Definition at line 530 of file sixlowpan-net-device.h.
Referenced by SixLowPanNetDevice(), and DoSend().
m_compressionThreshold
uint32_t ns3::SixLowPanNetDevice::m_compressionThreshold private
Minimum L2 payload size.
Definition at line 549 of file sixlowpan-net-device.h.
Referenced by DoSend(), and GetTypeId().
m_dropTrace
TracedCallback<DropReason, Ptr<const Packet>, Ptr<SixLowPanNetDevice>, uint32_t> ns3::SixLowPanNetDevice::m_dropTrace private
Callback to trace drop packets.
Data passed:
DropReason
Packet dropped (including 6LoWPAN header)
Ptr to SixLowPanNetDevice
interface index
Deprecated:
The non-const Ptr<SixLowPanNetDevice> argument is deprecated and will be changed to Ptr<const SixLowPanNetDevice> in a future release.
Definition at line 275 of file sixlowpan-net-device.h.
Referenced by GetTypeId(), HandleFragmentsTimeout(), ProcessFragment(), and ReceiveFromDevice().
m_etherType
uint16_t ns3::SixLowPanNetDevice::m_etherType private
EtherType number (used only if m_forceEtherType is true).
Definition at line 546 of file sixlowpan-net-device.h.
Referenced by DoSend(), GetTypeId(), and SetNetDevice().
m_forceEtherType
bool ns3::SixLowPanNetDevice::m_forceEtherType private
Force the EtherType number.
Also implying that the underlying NetDevice is using 48-bit Addresses, e.g., Ethernet, Wi-Fi, etc.
Definition at line 544 of file sixlowpan-net-device.h.
Referenced by DoSend(), GetTypeId(), and SetNetDevice().
m_fragmentExpirationTimeout
Time ns3::SixLowPanNetDevice::m_fragmentExpirationTimeout private
Time limit for fragment rebuilding.
Definition at line 519 of file sixlowpan-net-device.h.
Referenced by GetTypeId(), and SetTimeout().
m_fragmentReassemblyListSize
uint16_t ns3::SixLowPanNetDevice::m_fragmentReassemblyListSize private
How many packets can be rebuilt at the same time.
Some real implementation do limit this. Zero means no limit.
Definition at line 525 of file sixlowpan-net-device.h.
Referenced by GetTypeId(), and ProcessFragment().
m_fragments
MapFragments_t ns3::SixLowPanNetDevice::m_fragments private
Fragments hold to be rebuilt.
Definition at line 518 of file sixlowpan-net-device.h.
Referenced by ns3::SixLowPanNetDevice::Fragments::AddFragment(), DoDispose(), ns3::SixLowPanNetDevice::Fragments::GetFraments(), ns3::SixLowPanNetDevice::Fragments::GetPacket(), HandleFragmentsTimeout(), ns3::SixLowPanNetDevice::Fragments::IsEntire(), and ProcessFragment().
m_ifIndex
uint32_t ns3::SixLowPanNetDevice::m_ifIndex private
Interface index.
Definition at line 538 of file sixlowpan-net-device.h.
Referenced by GetIfIndex(), and SetIfIndex().
m_meshCacheLength
uint16_t ns3::SixLowPanNetDevice::m_meshCacheLength private
length of the cache for each source.
Definition at line 532 of file sixlowpan-net-device.h.
Referenced by GetTypeId(), and ReceiveFromDevice().
m_meshUnder
bool ns3::SixLowPanNetDevice::m_meshUnder private
Use a mesh-under routing.
Definition at line 529 of file sixlowpan-net-device.h.
Referenced by DoSend(), and GetTypeId().
m_meshUnderHopsLeft
uint8_t ns3::SixLowPanNetDevice::m_meshUnderHopsLeft private
Start value for mesh-under hops left.
Definition at line 531 of file sixlowpan-net-device.h.
Referenced by DoSend(), and GetTypeId().
m_meshUnderJitter
Ptr<RandomVariableStream> ns3::SixLowPanNetDevice::m_meshUnderJitter private
Random variable for the mesh-under packet retransmission.
Definition at line 533 of file sixlowpan-net-device.h.
Referenced by AssignStreams(), GetTypeId(), and ReceiveFromDevice().
m_netDevice
Ptr<NetDevice> ns3::SixLowPanNetDevice::m_netDevice private
Smart pointer to the underlying NetDevice.
Definition at line 537 of file sixlowpan-net-device.h.
Referenced by SixLowPanNetDevice(), AddLinkChangeCallback(), DoDispose(), DoFragmentation(), DoSend(), GetAddress(), GetBroadcast(), GetChannel(), GetMtu(), GetMulticast(), GetNetDevice(), IsBridge(), IsBroadcast(), IsLinkUp(), IsMulticast(), IsPointToPoint(), NeedsArp(), ReceiveFromDevice(), SetAddress(), SetMtu(), and SetNetDevice().
m_node
Ptr<Node> ns3::SixLowPanNetDevice::m_node private
Smart pointer to the Node.
Definition at line 536 of file sixlowpan-net-device.h.
Referenced by DoDispose(), DoSend(), GetNode(), HandleFragmentsTimeout(), ProcessFragment(), ReceiveFromDevice(), SetNetDevice(), and SetNode().
m_omitUdpChecksum
bool ns3::SixLowPanNetDevice::m_omitUdpChecksum private
Omit UDP checksum in NC1 encoding.
Definition at line 547 of file sixlowpan-net-device.h.
Referenced by CompressLowPanIphc(), CompressLowPanNhc(), and GetTypeId().
m_promiscRxCallback
NetDevice::PromiscReceiveCallback ns3::SixLowPanNetDevice::m_promiscRxCallback private
The callback used to notify higher layers that a packet has been received in promiscuous mode.
Definition at line 235 of file sixlowpan-net-device.h.
Referenced by ReceiveFromDevice(), and SetPromiscReceiveCallback().
m_rng
Ptr<UniformRandomVariable> ns3::SixLowPanNetDevice::m_rng private
Rng for the fragments tag.
Definition at line 551 of file sixlowpan-net-device.h.
Referenced by SixLowPanNetDevice(), AssignStreams(), and DoFragmentation().
m_rxCallback
NetDevice::ReceiveCallback ns3::SixLowPanNetDevice::m_rxCallback private
The callback used to notify higher layers that a packet has been received.
Definition at line 230 of file sixlowpan-net-device.h.
Referenced by ReceiveFromDevice(), and SetReceiveCallback().
m_rxTrace
TracedCallback<Ptr<const Packet>, Ptr<SixLowPanNetDevice>, uint32_t> ns3::SixLowPanNetDevice::m_rxTrace private
Callback to trace RX (reception) packets.
Data passed:
Packet received (including 6LoWPAN header)
Ptr to SixLowPanNetDevice
interface index
Deprecated:
The non-const Ptr<SixLowPanNetDevice> argument is deprecated and will be changed to Ptr<const SixLowPanNetDevice> in a future release.
Definition at line 261 of file sixlowpan-net-device.h.
Referenced by GetTypeId(), and ReceiveFromDevice().
m_seenPkts
std::map<Address , std::list <uint8_t > > ns3::SixLowPanNetDevice::m_seenPkts private
Seen packets, memorized by OriginatorAdddress, SequenceNumber.
Definition at line 534 of file sixlowpan-net-device.h.
Referenced by ReceiveFromDevice().
m_timeoutEvent
EventId ns3::SixLowPanNetDevice::m_timeoutEvent private
Event for the next scheduled timeout.
Definition at line 380 of file sixlowpan-net-device.h.
Referenced by DoDispose(), HandleTimeout(), and SetTimeout().
m_timeoutEventList
FragmentsTimeoutsList_t ns3::SixLowPanNetDevice::m_timeoutEventList private
Timeout "events" container.
Definition at line 378 of file sixlowpan-net-device.h.
Referenced by DoDispose(), HandleTimeout(), ProcessFragment(), and SetTimeout().
m_txTrace
TracedCallback<Ptr<const Packet>, Ptr<SixLowPanNetDevice>, uint32_t> ns3::SixLowPanNetDevice::m_txTrace private
Callback to trace TX (transmission) packets.
Data passed:
Packet received (including 6LoWPAN header)
Ptr to SixLowPanNetDevice
interface index
Deprecated:
The non-const Ptr<SixLowPanNetDevice> argument is deprecated and will be changed to Ptr<const SixLowPanNetDevice> in a future release.
Definition at line 248 of file sixlowpan-net-device.h.
Referenced by DoSend(), and GetTypeId().
m_useIphc
bool ns3::SixLowPanNetDevice::m_useIphc private
Use IPHC or HC1.
Definition at line 527 of file sixlowpan-net-device.h.
Referenced by DoSend(), GetTypeId(), and ReceiveFromDevice().
The documentation for this class was generated from the following files:
src/sixlowpan/model/sixlowpan-net-device.h
src/sixlowpan/model/sixlowpan-net-device.cc