ns-3: ns3::NoOpComponentCarrierManager Class Reference
ns3::NoOpComponentCarrierManager Class Reference
The default component carrier manager that forwards all traffic, the uplink and the downlink, over the primary carrier, and will not use secondary carriers.
#include "no-op-component-carrier-manager.h"
Public Member Functions
NoOpComponentCarrierManager ()
virtual ~NoOpComponentCarrierManager ()
Public Member Functions inherited from ns3::LteEnbComponentCarrierManager
LteEnbComponentCarrierManager ()
virtual ~LteEnbComponentCarrierManager ()
virtual LteCcmMacSapUser * GetLteCcmMacSapUser ()
This function returns a pointer to the LteCcmMacSapUser interface, which is used by MAC to communicate to CCM when e.g.
virtual LteCcmRrcSapProvider * GetLteCcmRrcSapProvider ()
Export the "provider" part of the ComponentCarrier Management SAP interface.
virtual LteMacSapProvider * GetLteMacSapProvider ()
Returns the pointer to the LteMacSapProvider interface, the provider of MAC, which is this new architecture served by LteEnbComponentCarrierManager object which will behave as a proxy, and will forward calls between to MAC objects of component carriers based on the logic implemented in the specific component carrier manager.
virtual bool SetCcmMacSapProviders (uint8_t componentCarrierId, LteCcmMacSapProvider *sap)
Set LteCcmMacSapProvider interface for the MAC object of the specified component carrier.
virtual void SetLteCcmRrcSapUser (LteCcmRrcSapUser *s)
Set the "user" part of the ComponentCarrier Management SAP interface that this ComponentCarrier algorithm instance will interact with.
virtual bool SetMacSapProvider (uint8_t componentCarrierId, LteMacSapProvider *sap)
Set LteMacSapProvider interface for the MAC object of the specified component carrier.
virtual void SetNumberOfComponentCarriers (uint16_t noOfComponentCarriers)
Sets the total number of component carriers.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::LteEnbComponentCarrierManager
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoAddLc (LteEnbCmacSapProvider::LcInfo lcInfo, LteMacSapUser *msu)
Add LC.
virtual void DoAddUe (uint16_t rnti, uint8_t state)
Add UE.
virtual LteMacSapUser * DoConfigureSignalBearer (LteEnbCmacSapProvider::LcInfo lcinfo, LteMacSapUser *msu)
Configure the signal bearer.
virtual void DoDispose ()
Destructor implementation.
virtual void DoInitialize ()
Initialize() implementation.
virtual void DoNotifyHarqDeliveryFailure ()
Notify HARQ delivery failure.
virtual void DoNotifyPrbOccupancy (double prbOccupancy, uint8_t componentCarrierId)
Function implements the function of the SAP interface of CCM instance which is used by MAC to notify the PRB occupancy reported by scheduler.
virtual void DoNotifyTxOpportunity (LteMacSapUser::TxOpportunityParameters txOpParams)
Notify transmit opportunity.
virtual void DoReceivePdu (LteMacSapUser::ReceivePduParameters rxPduParams)
Receive PDU.
virtual std::vector< uint8_t > DoReleaseDataRadioBearer (uint16_t rnti, uint8_t lcid)
Release data radio bearer.
virtual void DoRemoveUe (uint16_t rnti)
Remove UE.
virtual void DoReportBufferStatus (LteMacSapProvider::ReportBufferStatusParameters params)
Report buffer status.
virtual void DoReportUeMeas (uint16_t rnti, LteRrcSap::MeasResults measResults)
Implementation of ReportUeMeas.
virtual std::vector< LteCcmRrcSapProvider::LcsConfig > DoSetupDataRadioBearer (EpsBearer bearer, uint8_t bearerId, uint16_t rnti, uint8_t lcid, uint8_t lcGroup, LteMacSapUser *msu)
Setup data radio bearer.
virtual void DoTransmitPdu (LteMacSapProvider::TransmitPduParameters params)
Transmit PDU.
virtual void DoUlReceiveMacCe (MacCeListElement_s bsr, uint8_t componentCarrierId)
Forwards uplink BSR to CCM, called by MAC through CCM SAP interface.
virtual void DoUlReceiveSr (uint16_t rnti, uint8_t componentCarrierId)
Forward uplink SR to CCM, called by MAC through CCM SAP interface.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes
std::map< uint8_t, double > m_ccPrbOccupancy
The physical resource block occupancy per carrier.
Protected Attributes inherited from ns3::LteEnbComponentCarrierManager
std::map< uint8_t, LteCcmMacSapProvider * > m_ccmMacSapProviderMap
A map of pointers to the SAP interfaces of CCM instance that provides the CCM specific functionalities to MAC, i.e.
LteCcmMacSapUser * m_ccmMacSapUser
LteCcmMacSapUser is extended version of LteMacSapUser interface.
LteCcmRrcSapProvider * m_ccmRrcSapProvider
A pointer to the SAP interface of the CCM instance to receive API calls from the eNodeB RRC instance.
LteCcmRrcSapUser * m_ccmRrcSapUser
A pointer to SAP interface of RRC instance, i.e.
std::map< uint16_t, uint8_t > m_enabledComponentCarrier
This map tells for each RNTI the number of enabled component carriers.
LteMacSapProvider * m_macSapProvider
A pointer to main SAP interface of the MAC instance, which is in this case handled by CCM.
std::map< uint8_t, LteMacSapProvider * > m_macSapProvidersMap
A map of pointers to real SAP interfaces of MAC instances.
uint16_t m_noOfComponentCarriers
The number component of carriers that are supported by this eNb.
std::map< uint16_t, std::map< uint8_t, LteEnbCmacSapProvider::LcInfo > > m_rlcLcInstantiated
This map contains logical channel configuration per flow Id (rnti, lcid).
Ptr< LteEnbRrc > m_rrc
A pointer to the RRC instance of this eNb.
std::map< uint16_t, std::map< uint8_t, LteMacSapUser * > > m_ueAttached
The map that contains the rnti, lcid, SAP of the RLC instance.
std::map< uint16_t, uint8_t > m_ueState
Map of RRC states per UE (rnti, state), e.g.
Friends
class EnbMacMemberLteMacSapProvider< NoOpComponentCarrierManager >
allow EnbMacMemberLteMacSapProvider<NoOpComponentCarrierManager> class friend access
class MemberLteCcmMacSapUser< NoOpComponentCarrierManager >
allow MemberLteCcmMacSapUser<NoOpComponentCarrierManager> class friend access
class MemberLteCcmRrcSapProvider< NoOpComponentCarrierManager >
allow MemberLteCcmRrcSapProvider<NoOpComponentCarrierManager> class friend access
class MemberLteCcmRrcSapUser< NoOpComponentCarrierManager >
allow MemberLteCcmRrcSapUser<NoOpComponentCarrierManager> class friend access
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The default component carrier manager that forwards all traffic, the uplink and the downlink, over the primary carrier, and will not use secondary carriers.
To enable carrier aggregation feature, select another component carrier manager class, i.e., some of child classes of LteEnbComponentCarrierManager of NoOpComponentCarrierManager.
Config Paths
ns3::NoOpComponentCarrierManager is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteEnbNetDevice/LteEnbComponentCarrierManager/$ns3::NoOpComponentCarrierManager"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteEnbNetDevice/LteEnbComponentCarrierManager/$ns3::NoOpComponentCarrierManager"
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 248 bytes (on a 64-bit architecture).
Definition at line 43 of file no-op-component-carrier-manager.h.
Constructor & Destructor Documentation
NoOpComponentCarrierManager()
ns3::NoOpComponentCarrierManager::NoOpComponentCarrierManager ()
Definition at line 33 of file no-op-component-carrier-manager.cc.
References EnbMacMemberLteMacSapProvider< NoOpComponentCarrierManager >, ns3::LteEnbComponentCarrierManager::m_ccmMacSapUser, ns3::LteEnbComponentCarrierManager::m_ccmRrcSapProvider, ns3::LteEnbComponentCarrierManager::m_ccmRrcSapUser, ns3::LteEnbComponentCarrierManager::m_macSapProvider, MemberLteCcmMacSapUser< NoOpComponentCarrierManager >, MemberLteCcmRrcSapProvider< NoOpComponentCarrierManager >, and NS_LOG_FUNCTION.
~NoOpComponentCarrierManager()
ns3::NoOpComponentCarrierManager::~NoOpComponentCarrierManager () virtual
Definition at line 42 of file no-op-component-carrier-manager.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoAddLc()
void ns3::NoOpComponentCarrierManager::DoAddLc (LteEnbCmacSapProvider::LcInfo lcInfo, LteMacSapUser * msu) protected virtual
Add LC.
Parameters
lcInfo the LC info
msu the MSU
Definition at line 194 of file no-op-component-carrier-manager.cc.
References ns3::LteEnbCmacSapProvider::LcInfo::lcId, ns3::LteEnbComponentCarrierManager::m_rlcLcInstantiated, NS_ASSERT_MSG, NS_LOG_FUNCTION, and ns3::LteEnbCmacSapProvider::LcInfo::rnti.
DoAddUe()
void ns3::NoOpComponentCarrierManager::DoAddUe (uint16_t rnti, uint8_t state) protected virtual
Add UE.
Parameters
rnti the RNTI
state the state
Definition at line 141 of file no-op-component-carrier-manager.cc.
References ns3::LteEnbComponentCarrierManager::m_enabledComponentCarrier, ns3::LteEnbComponentCarrierManager::m_rlcLcInstantiated, ns3::LteEnbComponentCarrierManager::m_ueAttached, ns3::LteEnbComponentCarrierManager::m_ueState, NS_ASSERT_MSG, NS_FATAL_ERROR, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
DoConfigureSignalBearer()
LteMacSapUser * ns3::NoOpComponentCarrierManager::DoConfigureSignalBearer (LteEnbCmacSapProvider::LcInfo lcinfo, LteMacSapUser * msu) protected virtual
Configure the signal bearer.
Parameters
lcinfo the LteEnbCmacSapProvider::LcInfo
msu the MSU
Returns
updated data radio bearer list
Definition at line 352 of file no-op-component-carrier-manager.cc.
References ns3::LteEnbCmacSapProvider::LcInfo::lcId, ns3::LteEnbComponentCarrierManager::m_ccmMacSapUser, ns3::LteEnbComponentCarrierManager::m_ueAttached, NS_ASSERT_MSG, NS_LOG_ERROR, NS_LOG_FUNCTION, and ns3::LteEnbCmacSapProvider::LcInfo::rnti.
DoDispose()
void ns3::NoOpComponentCarrierManager::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::LteEnbComponentCarrierManager.
Definition at line 48 of file no-op-component-carrier-manager.cc.
References ns3::LteEnbComponentCarrierManager::m_ccmMacSapUser, ns3::LteEnbComponentCarrierManager::m_ccmRrcSapProvider, ns3::LteEnbComponentCarrierManager::m_macSapProvider, and NS_LOG_FUNCTION.
DoInitialize()
void ns3::NoOpComponentCarrierManager::DoInitialize (void) protected virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 70 of file no-op-component-carrier-manager.cc.
References ns3::Object::DoInitialize(), and NS_LOG_FUNCTION.
DoNotifyHarqDeliveryFailure()
void ns3::NoOpComponentCarrierManager::DoNotifyHarqDeliveryFailure () protected virtual
Notify HARQ delivery failure.
Definition at line 128 of file no-op-component-carrier-manager.cc.
References NS_LOG_FUNCTION.
DoNotifyPrbOccupancy()
void ns3::NoOpComponentCarrierManager::DoNotifyPrbOccupancy (double prbOccupancy, uint8_t componentCarrierId) protected virtual
Function implements the function of the SAP interface of CCM instance which is used by MAC to notify the PRB occupancy reported by scheduler.
Parameters
prbOccupancy the PRB occupancy
componentCarrierId the component carrier ID
Definition at line 374 of file no-op-component-carrier-manager.cc.
References m_ccPrbOccupancy, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
DoNotifyTxOpportunity()
void ns3::NoOpComponentCarrierManager::DoNotifyTxOpportunity (LteMacSapUser::TxOpportunityParameters txOpParams) protected virtual
Notify transmit opportunity.
Parameters
txOpParams the LteMacSapUser::TxOpportunityParameters
Definition at line 102 of file no-op-component-carrier-manager.cc.
References ns3::LteMacSapUser::TxOpportunityParameters::componentCarrierId, ns3::LteMacSapUser::TxOpportunityParameters::layer, ns3::LteMacSapUser::TxOpportunityParameters::lcid, ns3::LteEnbComponentCarrierManager::m_ueAttached, NS_ASSERT_MSG, NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::LteMacSapUser::TxOpportunityParameters::rnti.
DoReceivePdu()
void ns3::NoOpComponentCarrierManager::DoReceivePdu (LteMacSapUser::ReceivePduParameters rxPduParams) protected virtual
Receive PDU.
Parameters
rxPduParams the LteMacSapUser::ReceivePduParameters
Definition at line 115 of file no-op-component-carrier-manager.cc.
References ns3::LteMacSapUser::ReceivePduParameters::lcid, ns3::LteEnbComponentCarrierManager::m_ueAttached, NS_ASSERT_MSG, NS_LOG_FUNCTION, and ns3::LteMacSapUser::ReceivePduParameters::rnti.
DoReleaseDataRadioBearer()
std::vector< uint8_t > ns3::NoOpComponentCarrierManager::DoReleaseDataRadioBearer (uint16_t rnti, uint8_t lcid) protected virtual
Release data radio bearer.
Parameters
rnti the RNTI
lcid the LCID
Returns
updated data radio bearer list
Definition at line 320 of file no-op-component-carrier-manager.cc.
References ns3::LteEnbComponentCarrierManager::m_enabledComponentCarrier, ns3::LteEnbComponentCarrierManager::m_rlcLcInstantiated, ns3::LteEnbComponentCarrierManager::m_ueAttached, NS_ASSERT_MSG, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
DoRemoveUe()
void ns3::NoOpComponentCarrierManager::DoRemoveUe (uint16_t rnti) protected virtual
Remove UE.
Parameters
rnti the RNTI
Definition at line 203 of file no-op-component-carrier-manager.cc.
References ns3::LteEnbComponentCarrierManager::m_enabledComponentCarrier, ns3::LteEnbComponentCarrierManager::m_rlcLcInstantiated, ns3::LteEnbComponentCarrierManager::m_ueAttached, ns3::LteEnbComponentCarrierManager::m_ueState, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
DoReportBufferStatus()
void ns3::NoOpComponentCarrierManager::DoReportBufferStatus (LteMacSapProvider::ReportBufferStatusParameters params) protected virtual
Report buffer status.
Parameters
params the report buffer status parameters
Reimplemented in ns3::RrComponentCarrierManager.
Definition at line 92 of file no-op-component-carrier-manager.cc.
References ns3::LteCcmRrcSapUser::GetUeManager(), ns3::LteEnbComponentCarrierManager::m_ccmRrcSapUser, ns3::LteEnbComponentCarrierManager::m_macSapProvidersMap, NS_ASSERT_MSG, NS_LOG_FUNCTION, and ns3::LteMacSapProvider::ReportBufferStatusParameters::rnti.
DoReportUeMeas()
void ns3::NoOpComponentCarrierManager::DoReportUeMeas (uint16_t rnti, LteRrcSap::MeasResults measResults) protected virtual
Implementation of ReportUeMeas.
Parameters
rnti Radio Network Temporary Identity, an integer identifying the UE where the report originates from
measResults a single report of one measurement identity
Implements ns3::LteEnbComponentCarrierManager.
Definition at line 134 of file no-op-component-carrier-manager.cc.
References ns3::LteRrcSap::MeasResults::measId, and NS_LOG_FUNCTION.
DoSetupDataRadioBearer()
std::vector< LteCcmRrcSapProvider::LcsConfig > ns3::NoOpComponentCarrierManager::DoSetupDataRadioBearer (EpsBearer bearer, uint8_t bearerId, uint16_t rnti, uint8_t lcid, uint8_t lcGroup, LteMacSapUser * msu) protected virtual
Setup data radio bearer.
Parameters
bearer the radio bearer
bearerId the bearerID
rnti the RNTI
lcid the LCID
lcGroup the LC group
msu the MSU
Returns
std::vector<LteCcmRrcSapProvider::LcsConfig>
Definition at line 228 of file no-op-component-carrier-manager.cc.
References ns3::LteCcmRrcSapProvider::LcsConfig::componentCarrierId, ns3::GbrQosInformation::gbrDl, ns3::LteEnbCmacSapProvider::LcInfo::gbrDl, ns3::EpsBearer::gbrQosInfo, ns3::GbrQosInformation::gbrUl, ns3::LteEnbCmacSapProvider::LcInfo::gbrUl, ns3::EpsBearer::IsGbr(), ns3::LteEnbCmacSapProvider::LcInfo::isGbr, ns3::LteCcmRrcSapProvider::LcsConfig::lc, ns3::LteEnbCmacSapProvider::LcInfo::lcGroup, ns3::LteEnbCmacSapProvider::LcInfo::lcId, ns3::LteEnbComponentCarrierManager::m_ccmMacSapUser, ns3::LteEnbComponentCarrierManager::m_enabledComponentCarrier, ns3::LteEnbComponentCarrierManager::m_noOfComponentCarriers, ns3::LteEnbComponentCarrierManager::m_rlcLcInstantiated, ns3::LteEnbComponentCarrierManager::m_ueAttached, ns3::GbrQosInformation::mbrDl, ns3::LteEnbCmacSapProvider::LcInfo::mbrDl, ns3::GbrQosInformation::mbrUl, ns3::LteEnbCmacSapProvider::LcInfo::mbrUl, ns3::LteCcmRrcSapProvider::LcsConfig::msu, NS_ASSERT_MSG, NS_LOG_DEBUG, NS_LOG_ERROR, NS_LOG_FUNCTION, ns3::EpsBearer::qci, ns3::LteEnbCmacSapProvider::LcInfo::qci, and ns3::LteEnbCmacSapProvider::LcInfo::rnti.
DoTransmitPdu()
void ns3::NoOpComponentCarrierManager::DoTransmitPdu (LteMacSapProvider::TransmitPduParameters params) protected virtual
Transmit PDU.
Parameters
params the transmit PDU parameters
Definition at line 82 of file no-op-component-carrier-manager.cc.
References ns3::LteMacSapProvider::TransmitPduParameters::componentCarrierId, ns3::LteEnbComponentCarrierManager::m_macSapProvidersMap, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
DoUlReceiveMacCe()
void ns3::NoOpComponentCarrierManager::DoUlReceiveMacCe (MacCeListElement_s bsr, uint8_t componentCarrierId) protected virtual
Forwards uplink BSR to CCM, called by MAC through CCM SAP interface.
Parameters
bsr the BSR
componentCarrierId the component carrier ID
Reimplemented in ns3::RrComponentCarrierManager.
Definition at line 382 of file no-op-component-carrier-manager.cc.
References ns3::MacCeListElement_s::BSR, ns3::BufferSizeLevelBsr::BsrId2BufferSize(), ns3::BufferSizeLevelBsr::BufferSize2BsrId(), ns3::MacCeValue_u::m_bufferStatus, ns3::LteEnbComponentCarrierManager::m_ccmMacSapProviderMap, ns3::MacCeValue_u::m_crnti, ns3::MacCeListElement_s::m_macCeType, ns3::MacCeListElement_s::m_macCeValue, ns3::MacCeValue_u::m_phr, ns3::MacCeListElement_s::m_rnti, NS_ASSERT_MSG, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
DoUlReceiveSr()
void ns3::NoOpComponentCarrierManager::DoUlReceiveSr (uint16_t rnti, uint8_t componentCarrierId) protected virtual
Forward uplink SR to CCM, called by MAC through CCM SAP interface.
Parameters
rnti RNTI of the UE that requested SR
componentCarrierId the component carrier ID that forwarded the SR
Reimplemented in ns3::RrComponentCarrierManager.
Definition at line 427 of file no-op-component-carrier-manager.cc.
References ns3::LteEnbComponentCarrierManager::m_ccmMacSapProviderMap, NS_ABORT_MSG_IF, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::NoOpComponentCarrierManager::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 58 of file no-op-component-carrier-manager.cc.
References ns3::TypeId::SetParent().
Friends And Related Function Documentation
EnbMacMemberLteMacSapProvider< NoOpComponentCarrierManager >
friend class EnbMacMemberLteMacSapProvider< NoOpComponentCarrierManager > friend
allow EnbMacMemberLteMacSapProvider<NoOpComponentCarrierManager> class friend access
Definition at line 1 of file no-op-component-carrier-manager.h.
Referenced by NoOpComponentCarrierManager().
MemberLteCcmMacSapUser< NoOpComponentCarrierManager >
friend class MemberLteCcmMacSapUser< NoOpComponentCarrierManager > friend
allow MemberLteCcmMacSapUser<NoOpComponentCarrierManager> class friend access
Definition at line 1 of file no-op-component-carrier-manager.h.
Referenced by NoOpComponentCarrierManager().
MemberLteCcmRrcSapProvider< NoOpComponentCarrierManager >
friend class MemberLteCcmRrcSapProvider< NoOpComponentCarrierManager > friend
allow MemberLteCcmRrcSapProvider<NoOpComponentCarrierManager> class friend access
Definition at line 1 of file no-op-component-carrier-manager.h.
Referenced by NoOpComponentCarrierManager().
MemberLteCcmRrcSapUser< NoOpComponentCarrierManager >
friend class MemberLteCcmRrcSapUser< NoOpComponentCarrierManager > friend
allow MemberLteCcmRrcSapUser<NoOpComponentCarrierManager> class friend access
Definition at line 1 of file no-op-component-carrier-manager.h.
Member Data Documentation
m_ccPrbOccupancy
std::map<uint8_t, double > ns3::NoOpComponentCarrierManager::m_ccPrbOccupancy protected
The physical resource block occupancy per carrier.
Definition at line 157 of file no-op-component-carrier-manager.h.
Referenced by DoNotifyPrbOccupancy().
The documentation for this class was generated from the following files:
src/lte/model/no-op-component-carrier-manager.h
src/lte/model/no-op-component-carrier-manager.cc