ns-3: ns3::IpL4Protocol Class Reference
ns3::IpL4Protocol Class Reference abstract
Internet
L4 Protocol abstract base class.
#include "ip-l4-protocol.h"
Public Types
typedef Callback< void, Ptr< Packet >, Ipv4Address, Ipv4Address, uint8_t, Ptr< Ipv4Route > > DownTargetCallback
callback to send packets over IPv4
typedef Callback< void, Ptr< Packet >, Ipv6Address, Ipv6Address, uint8_t, Ptr< Ipv6Route > > DownTargetCallback6
callback to send packets over IPv6
enum RxStatus { RX_OK , RX_CSUM_FAILED , RX_ENDPOINT_CLOSED , RX_ENDPOINT_UNREACH }
Rx status codes.
Public Member Functions
virtual ~IpL4Protocol ()
virtual DownTargetCallback GetDownTarget (void) const =0
This method allows a caller to get the current down target callback set for this L4 protocol (IPv4 case)
virtual DownTargetCallback6 GetDownTarget6 (void) const =0
This method allows a caller to get the current down target callback set for this L4 protocol (IPv6 case)
virtual int GetProtocolNumber (void) const =0
Returns the protocol number of this protocol.
virtual enum RxStatus Receive (Ptr< Packet > p, Ipv4Header const &header, Ptr< Ipv4Interface > incomingInterface)=0
Called from lower-level layers to send the packet up in the stack.
virtual enum RxStatus Receive (Ptr< Packet > p, Ipv6Header const &header, Ptr< Ipv6Interface > incomingInterface)=0
Called from lower-level layers to send the packet up in the stack.
virtual void ReceiveIcmp (Ipv4Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo, Ipv4Address payloadSource, Ipv4Address payloadDestination, const uint8_t payload[8])
Called from lower-level layers to send the ICMP packet up in the stack.
virtual void ReceiveIcmp (Ipv6Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo, Ipv6Address payloadSource, Ipv6Address payloadDestination, const uint8_t payload[8])
Called from lower-level layers to send the ICMPv6 packet up in the stack.
virtual void SetDownTarget (DownTargetCallback cb)=0
This method allows a caller to set the current down target callback set for this L4 protocol (IPv4 case)
virtual void SetDownTarget6 (DownTargetCallback6 cb)=0
This method allows a caller to set the current down target callback set for this L4 protocol (IPv6 case)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
L4 Protocol abstract base class.
Introspection did not find any typical Config paths.
This is an abstract base class for layer four protocols which use IP as the network layer.
Attributes
ProtocolNumber: The IP protocol number.
Set with class: ns3::IntegerValue
Underlying type: int32_t 0:255
Flags: read
No TraceSources are defined for this type.
Size of this type is 32 bytes (on a 64-bit architecture).
Definition at line 50 of file ip-l4-protocol.h.
Member Typedef Documentation
DownTargetCallback
typedef Callback<void,Ptr<Packet>, Ipv4Address, Ipv4Address, uint8_t, Ptr<Ipv4Route> > ns3::IpL4Protocol::DownTargetCallback
callback to send packets over IPv4
Definition at line 143 of file ip-l4-protocol.h.
DownTargetCallback6
typedef Callback<void,Ptr<Packet>, Ipv6Address, Ipv6Address, uint8_t, Ptr<Ipv6Route> > ns3::IpL4Protocol::DownTargetCallback6
callback to send packets over IPv6
Definition at line 147 of file ip-l4-protocol.h.
Member Enumeration Documentation
RxStatus
enum ns3::IpL4Protocol::RxStatus
Rx status codes.
Enumerator
RX_OK
RX_CSUM_FAILED
RX_ENDPOINT_CLOSED
RX_ENDPOINT_UNREACH
Definition at line 56 of file ip-l4-protocol.h.
Constructor & Destructor Documentation
~IpL4Protocol()
ns3::IpL4Protocol::~IpL4Protocol () virtual
Definition at line 49 of file ip-l4-protocol.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
GetDownTarget()
virtual DownTargetCallback ns3::IpL4Protocol::GetDownTarget (void) const pure virtual
This method allows a caller to get the current down target callback set for this L4 protocol (IPv4 case)
Returns
current Callback for the L4 protocol
Implemented in ns3::UdpL4Protocol, ns3::TcpL4Protocol, ns3::NscTcpL4Protocol, ns3::Icmpv6L4Protocol, ns3::Icmpv4L4Protocol, and ns3::dsr::DsrRouting.
GetDownTarget6()
virtual DownTargetCallback6 ns3::IpL4Protocol::GetDownTarget6 (void) const pure virtual
This method allows a caller to get the current down target callback set for this L4 protocol (IPv6 case)
Returns
current Callback for the L4 protocol
Implemented in ns3::UdpL4Protocol, ns3::TcpL4Protocol, ns3::NscTcpL4Protocol, ns3::Icmpv6L4Protocol, ns3::Icmpv4L4Protocol, and ns3::dsr::DsrRouting.
GetProtocolNumber()
virtual int ns3::IpL4Protocol::GetProtocolNumber (void) const pure virtual
Returns the protocol number of this protocol.
Returns
the protocol number.
Implemented in ns3::UdpL4Protocol, ns3::TcpL4Protocol, ns3::NscTcpL4Protocol, ns3::Icmpv4L4Protocol, ns3::dsr::DsrRouting, and ns3::Icmpv6L4Protocol.
Referenced by GetTypeId(), ns3::Ipv4L3Protocol::Insert(), ns3::Ipv6L3Protocol::Insert(), ns3::Ipv4L3Protocol::Remove(), and ns3::Ipv6L3Protocol::Remove().
GetTypeId()
TypeId ns3::IpL4Protocol::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 35 of file ip-l4-protocol.cc.
References ns3::TypeId::ATTR_GET, GetProtocolNumber(), ns3::MakeIntegerAccessor(), and ns3::TypeId::SetParent().
Receive() [1/2]
virtual enum RxStatus ns3::IpL4Protocol::Receive (Ptr< Packet > p, Ipv4Header const & header, Ptr< Ipv4Interface > incomingInterface) pure virtual
Called from lower-level layers to send the packet up in the stack.
Parameters
p packet to forward up
header IPv4 Header information
incomingInterface the Ipv4Interface on which the packet arrived
Returns
Rx status code
Implemented in ns3::TcpL4Protocol, ns3::UdpL4Protocol, ns3::Icmpv6L4Protocol, ns3::NscTcpL4Protocol, ns3::Icmpv4L4Protocol, and ns3::dsr::DsrRouting.
Referenced by ns3::Ipv4L3Protocol::LocalDeliver(), and ns3::Ipv6L3Protocol::LocalDeliver().
Receive() [2/2]
virtual enum RxStatus ns3::IpL4Protocol::Receive (Ptr< Packet > p, Ipv6Header const & header, Ptr< Ipv6Interface > incomingInterface) pure virtual
Called from lower-level layers to send the packet up in the stack.
Parameters
p packet to forward up
header IPv6 Header information
incomingInterface the Ipv6Interface on which the packet arrived
Returns
Rx status code
Implemented in ns3::TcpL4Protocol, ns3::UdpL4Protocol, ns3::NscTcpL4Protocol, ns3::Icmpv6L4Protocol, ns3::Icmpv4L4Protocol, and ns3::dsr::DsrRouting.
ReceiveIcmp() [1/2]
void ns3::IpL4Protocol::ReceiveIcmp (Ipv4Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo, Ipv4Address payloadSource, Ipv4Address payloadDestination, const uint8_t payload[8]) virtual
Called from lower-level layers to send the ICMP packet up in the stack.
Parameters
icmpSource the source address of the icmp message
icmpTtl the ttl of the icmp message
icmpType the 'type' field of the icmp message
icmpCode the 'code' field of the icmp message
icmpInfo extra information dependent on the icmp message generated by Icmpv4L4Protocol
payloadSource the source address of the packet which triggered the icmp message
payloadDestination the destination address of the packet which triggered the icmp message.
payload the first 8 bytes of the packet payload which triggered the icmp message.
Reimplemented in ns3::UdpL4Protocol, and ns3::TcpL4Protocol.
Definition at line 55 of file ip-l4-protocol.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::Forward().
ReceiveIcmp() [2/2]
void ns3::IpL4Protocol::ReceiveIcmp (Ipv6Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo, Ipv6Address payloadSource, Ipv6Address payloadDestination, const uint8_t payload[8]) virtual
Called from lower-level layers to send the ICMPv6 packet up in the stack.
Parameters
icmpSource the source address of the icmp message
icmpTtl the ttl of the icmp message
icmpType the 'type' field of the icmp message
icmpCode the 'code' field of the icmp message
icmpInfo extra information dependent on the icmp message generated by Icmpv6L4Protocol
payloadSource the source address of the packet which triggered the icmp message
payloadDestination the destination address of the packet which triggered the icmp message.
payload the first 8 bytes of the packet payload which triggered the icmp message.
Reimplemented in ns3::UdpL4Protocol, and ns3::TcpL4Protocol.
Definition at line 63 of file ip-l4-protocol.cc.
References NS_LOG_FUNCTION.
SetDownTarget()
virtual void ns3::IpL4Protocol::SetDownTarget (DownTargetCallback cb) pure virtual
This method allows a caller to set the current down target callback set for this L4 protocol (IPv4 case)
Parameters
cb current Callback for the L4 protocol
Implemented in ns3::UdpL4Protocol, ns3::TcpL4Protocol, ns3::NscTcpL4Protocol, ns3::Icmpv6L4Protocol, ns3::Icmpv4L4Protocol, and ns3::dsr::DsrRouting.
SetDownTarget6()
virtual void ns3::IpL4Protocol::SetDownTarget6 (DownTargetCallback6 cb) pure virtual
This method allows a caller to set the current down target callback set for this L4 protocol (IPv6 case)
Parameters
cb current Callback for the L4 protocol
Implemented in ns3::UdpL4Protocol, ns3::TcpL4Protocol, ns3::NscTcpL4Protocol, ns3::Icmpv6L4Protocol, ns3::Icmpv4L4Protocol, and ns3::dsr::DsrRouting.
The documentation for this class was generated from the following files:
src/internet/model/ip-l4-protocol.h
src/internet/model/ip-l4-protocol.cc