ns-3: ns3::RandomWalk2dOutdoorMobilityModel Class Reference
ns3::RandomWalk2dOutdoorMobilityModel Class Reference
Mobility
2D random walk mobility model which avoids buildings.
#include "random-walk-2d-outdoor-mobility-model.h"
Public Types
enum Mode { MODE_DISTANCE , MODE_TIME }
An enum representing the different working modes of this module.
Public Types inherited from ns3::MobilityModel
typedef void(* TracedCallback) (Ptr< const MobilityModel > model)
TracedCallback signature.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type with the TypeId system.
Static Public Member Functions inherited from ns3::MobilityModel
static TypeId GetTypeId (void)
Register this type with the TypeId system.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void AvoidBuilding (Time delayLeft, Vector intersectPosition)
Avoid a building.
Vector CalculateIntersectionFromOutside (const Vector &current, const Vector &next, const Box boundaries) const
Compute the intersecting point of the box represented by boundaries and the line between current and next Notice that we only consider a 2d plane.
virtual int64_t DoAssignStreams (int64_t)
The default implementation does nothing but return the passed-in parameter.
virtual void DoDispose (void)
Destructor implementation.
virtual Vector DoGetPosition (void) const
virtual Vector DoGetVelocity (void) const
virtual void DoInitialize (void)
Initialize() implementation.
void DoInitializePrivate (void)
Perform initialization of the object before MobilityModel::DoInitialize ()
virtual void DoSetPosition (const Vector &position)
void DoWalk (Time timeLeft)
Walk according to position and velocity, until distance is reached, time is reached, or intersection with the bounding box, or building.
std::pair< bool, Ptr< Building > > IsLineClearOfBuildings (Vector currentPosition, Vector nextPosition) const
Check if there is a building between two positions (or if the nextPosition is inside a building).
void Rebound (Time timeLeft)
Performs the rebound of the node if it reaches a boundary.
Private Attributes
Rectangle m_bounds
Bounds of the area to cruise.
Ptr< RandomVariableStream > m_direction
rv for picking direction
double m_epsilon
Tolerance for the intersection point with buildings.
EventId m_event
stored event ID
ConstantVelocityHelper m_helper
helper for this object
uint32_t m_maxIter
Maximum number of tries to find the next position.
enum Mode m_mode
whether in time or distance mode
double m_modeDistance
Change direction and speed after this distance.
Time m_modeTime
Change current direction and speed after this delay.
Vector m_prevPosition
Store the previous position in case a step back is needed.
Ptr< RandomVariableStream > m_speed
rv for picking speed
Additional Inherited Members
Public Member Functions inherited from ns3::MobilityModel
MobilityModel ()
virtual ~MobilityModel ()=0
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
double GetDistanceFrom (Ptr< const MobilityModel > position) const
Vector GetPosition (void) const
double GetRelativeSpeed (Ptr< const MobilityModel > other) const
Vector GetVelocity (void) const
void SetPosition (const Vector &position)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Protected Member Functions inherited from ns3::MobilityModel
void NotifyCourseChange (void) const
Must be invoked by subclasses when the course of the position changes to notify course change listeners.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
2D random walk mobility model which avoids buildings.
This class reuses most of the code of RandomWalk2dMobilityModel, but adds the awareness of buildings objects which are avoided by moving users. Each instance moves with a speed and direction chosen at random with the user-provided random variables until either a fixed distance has been walked or until a fixed amount of time. If we hit one of the boundaries (specified by a rectangle) of the model, we rebound on the boundary with a reflexive angle and speed. If we hit one of the buildings, we rebound with a random direction which makes sure that the next step does not enter the building.
The default values for the random variable that describes the speed is taken from Figure 1 in the paper: Henderson, L.F., 1971. The statistics of crowd fluids. nature, 229(5284), p.381.
Config Paths
ns3::RandomWalk2dOutdoorMobilityModel is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::MobilityModel/$ns3::RandomWalk2dOutdoorMobilityModel"
Attributes
Bounds: Bounds of the area to cruise.
Set with class: RectangleValue
Underlying type: Rectangle
Initial value: 0|100|0|100
Flags: construct write read
Time: Change current direction and speed after moving for this delay.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +2e+10ns
Flags: construct write read
Distance: Change current direction and speed after moving for this distance.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 30
Flags: construct write read
Mode: The mode indicates the condition used to change the current speed and direction
Set with class: ns3::EnumValue
Underlying type:
Initial value: Distance
Flags: construct write read
Direction: A random variable used to pick the direction (radians).
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::RandomVariableStream>
Initial value: ns3::UniformRandomVariable[Min=0.0|Max=6.283184]
Flags: construct write read
Speed: A random variable used to pick the speed (m/s).The default value is taken from Figure 1 of the paperHenderson, L.F., 1971. The statistics of crowd fluids. nature, 229(5284), p.381.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::RandomVariableStream>
Initial value: ns3::NormalRandomVariable[Mean=1.53|Variance=0.040401]
Flags: construct write read
Tolerance: Tolerance for the intersection point with buildings (m).It represents a small distance from where the building limitis actually placed, for example to represent a sidewalk.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 1e-06
Flags: construct write read
MaxIterations: Maximum number of attempts to find an alternative next positionif the original one is inside a building.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 100
Flags: construct write read
Attributes defined in parent class ns3::MobilityModel
Position: The current position of the mobility model.
Set with class: Vector3DValue
Underlying type: Vector3D
Flags: write read
Velocity: The current velocity of the mobility model.
Set with class: Vector3DValue
Underlying type: Vector3D
Flags: read
No TraceSources are defined for this type.
TraceSources defined in parent class ns3::MobilityModel
CourseChange: The value of the position and/or velocity vector changed
Callback signature: ns3::MobilityModel::TracedCallback
Size of this type is 256 bytes (on a 64-bit architecture).
Definition at line 57 of file random-walk-2d-outdoor-mobility-model.h.
Member Enumeration Documentation
Mode
enum ns3::RandomWalk2dOutdoorMobilityModel::Mode
An enum representing the different working modes of this module.
Enumerator
MODE_DISTANCE
MODE_TIME
Definition at line 66 of file random-walk-2d-outdoor-mobility-model.h.
Member Function Documentation
AvoidBuilding()
void ns3::RandomWalk2dOutdoorMobilityModel::AvoidBuilding (Time delayLeft, Vector intersectPosition) private
Avoid a building.
Parameters
timeLeft The remaining time of the walk
intersectPosition The position at which the building is intersected
Definition at line 308 of file random-walk-2d-outdoor-mobility-model.cc.
References ns3::CalculateDistance(), DoWalk(), ns3::Time::GetSeconds(), ns3::RandomVariableStream::GetValue(), ns3::Rectangle::IsInside(), IsLineClearOfBuildings(), m_bounds, m_direction, m_helper, m_maxIter, m_prevPosition, m_speed, NS_FATAL_ERROR, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, ns3::ConstantVelocityHelper::SetVelocity(), ns3::ConstantVelocityHelper::Unpause(), and ns3::ConstantVelocityHelper::Update().
Referenced by DoWalk().
CalculateIntersectionFromOutside()
Vector ns3::RandomWalk2dOutdoorMobilityModel::CalculateIntersectionFromOutside (const Vector & current, const Vector & next, const Box boundaries) const private
Compute the intersecting point of the box represented by boundaries and the line between current and next Notice that we only consider a 2d plane.
Parameters
current The current position
next The next position
boundaries The boundaries of the building we will intersect
Returns
a vector with the position of the intersection
Definition at line 231 of file random-walk-2d-outdoor-mobility-model.cc.
References ns3::Rectangle::BOTTOM, ns3::Rectangle::GetClosestSide(), ns3::Box::IsInside(), ns3::Rectangle::LEFT, m_epsilon, NS_ABORT_MSG_IF, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::Rectangle::RIGHT, ns3::Rectangle::TOP, ns3::Box::xMax, ns3::Box::xMin, ns3::Box::yMax, and ns3::Box::yMin.
Referenced by DoWalk(), and IsLineClearOfBuildings().
DoAssignStreams()
int64_t ns3::RandomWalk2dOutdoorMobilityModel::DoAssignStreams (int64_t start) private virtual
The default implementation does nothing but return the passed-in parameter.
Subclasses using random variables are expected to override this.
Parameters
start starting stream index
Returns
the number of streams used
Reimplemented from ns3::MobilityModel.
Definition at line 430 of file random-walk-2d-outdoor-mobility-model.cc.
References m_direction, m_speed, and ns3::RandomVariableStream::SetStream().
DoDispose()
void ns3::RandomWalk2dOutdoorMobilityModel::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 405 of file random-walk-2d-outdoor-mobility-model.cc.
References ns3::Object::DoDispose().
DoGetPosition()
Vector ns3::RandomWalk2dOutdoorMobilityModel::DoGetPosition (void) const private virtual
Returns
the current position.
Concrete subclasses of this base class must implement this method.
Implements ns3::MobilityModel.
Definition at line 411 of file random-walk-2d-outdoor-mobility-model.cc.
References ns3::ConstantVelocityHelper::GetCurrentPosition(), m_bounds, m_helper, and ns3::ConstantVelocityHelper::UpdateWithBounds().
DoGetVelocity()
Vector ns3::RandomWalk2dOutdoorMobilityModel::DoGetVelocity (void) const private virtual
Returns
the current velocity.
Concrete subclasses of this base class must implement this method.
Implements ns3::MobilityModel.
Definition at line 425 of file random-walk-2d-outdoor-mobility-model.cc.
References ns3::ConstantVelocityHelper::GetVelocity(), and m_helper.
DoInitialize()
void ns3::RandomWalk2dOutdoorMobilityModel::DoInitialize (void) private virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 99 of file random-walk-2d-outdoor-mobility-model.cc.
References ns3::Object::DoInitialize(), and DoInitializePrivate().
DoInitializePrivate()
void ns3::RandomWalk2dOutdoorMobilityModel::DoInitializePrivate (void) private
Perform initialization of the object before MobilityModel::DoInitialize ()
Definition at line 106 of file random-walk-2d-outdoor-mobility-model.cc.
References DoWalk(), ns3::RandomVariableStream::GetValue(), m_direction, m_helper, m_mode, m_modeDistance, m_modeTime, m_speed, MODE_TIME, ns3::Seconds(), ns3::ConstantVelocityHelper::SetVelocity(), ns3::ConstantVelocityHelper::Unpause(), and ns3::ConstantVelocityHelper::Update().
Referenced by DoInitialize(), DoSetPosition(), and DoWalk().
DoSetPosition()
void ns3::RandomWalk2dOutdoorMobilityModel::DoSetPosition (const Vector & position) private virtual
Parameters
position the position to set.
Concrete subclasses of this base class must implement this method.
Implements ns3::MobilityModel.
Definition at line 417 of file random-walk-2d-outdoor-mobility-model.cc.
References DoInitializePrivate(), ns3::Rectangle::IsInside(), m_bounds, m_event, m_helper, NS_ASSERT, ns3::Simulator::Remove(), ns3::Simulator::ScheduleNow(), and ns3::ConstantVelocityHelper::SetPosition().
DoWalk()
void ns3::RandomWalk2dOutdoorMobilityModel::DoWalk (Time timeLeft) private
Walk according to position and velocity, until distance is reached, time is reached, or intersection with the bounding box, or building.
Definition at line 130 of file random-walk-2d-outdoor-mobility-model.cc.
References AvoidBuilding(), ns3::Rectangle::CalculateIntersection(), CalculateIntersectionFromOutside(), ns3::EventId::Cancel(), DoInitializePrivate(), ns3::ConstantVelocityHelper::GetCurrentPosition(), ns3::Time::GetSeconds(), ns3::ConstantVelocityHelper::GetVelocity(), ns3::Rectangle::IsInside(), IsLineClearOfBuildings(), m_bounds, m_event, m_helper, m_prevPosition, ns3::MobilityModel::NotifyCourseChange(), NS_LOG_FUNCTION, NS_LOG_LOGIC, Rebound(), ns3::Simulator::Schedule(), and ns3::Seconds().
Referenced by AvoidBuilding(), DoInitializePrivate(), and Rebound().
GetTypeId()
TypeId ns3::RandomWalk2dOutdoorMobilityModel::GetTypeId (void) static
Register this type with the TypeId system.
Returns
the object TypeId
Definition at line 41 of file random-walk-2d-outdoor-mobility-model.cc.
References m_bounds, m_direction, m_epsilon, m_maxIter, m_mode, m_modeDistance, m_modeTime, m_speed, ns3::MakeDoubleAccessor(), ns3::MakeEnumAccessor(), ns3::MakeEnumChecker(), ns3::MakePointerAccessor(), ns3::MakeRectangleAccessor(), ns3::MakeRectangleChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeUintegerAccessor(), MODE_DISTANCE, MODE_TIME, ns3::Seconds(), and ns3::TypeId::SetParent().
IsLineClearOfBuildings()
std::pair< bool, Ptr< Building > > ns3::RandomWalk2dOutdoorMobilityModel::IsLineClearOfBuildings (Vector currentPosition, Vector nextPosition) const private
Check if there is a building between two positions (or if the nextPosition is inside a building).
The code is taken from MmWave3gppBuildingsPropagationLossModel from the NYU/UNIPD ns-3 mmWave module
Parameters
currentPosition The current position of the node
nextPosition The position to check
Returns
a pair with a boolean (true if the line between the two position does not intersect building), and a pointer which is 0 if the boolean is true, or it points to the building which is intersected
Definition at line 198 of file random-walk-2d-outdoor-mobility-model.cc.
References ns3::BuildingList::Begin(), ns3::CalculateDistance(), CalculateIntersectionFromOutside(), ns3::BuildingList::End(), max, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by AvoidBuilding(), and DoWalk().
Rebound()
void ns3::RandomWalk2dOutdoorMobilityModel::Rebound (Time timeLeft) private
Performs the rebound of the node if it reaches a boundary.
Parameters
timeLeft The remaining time of the walk
Definition at line 281 of file random-walk-2d-outdoor-mobility-model.cc.
References ns3::Rectangle::BOTTOM, DoWalk(), ns3::Rectangle::GetClosestSide(), ns3::ConstantVelocityHelper::GetCurrentPosition(), ns3::Time::GetSeconds(), ns3::ConstantVelocityHelper::GetVelocity(), ns3::Rectangle::LEFT, m_bounds, m_helper, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::Rectangle::RIGHT, ns3::ConstantVelocityHelper::SetVelocity(), ns3::Rectangle::TOP, ns3::ConstantVelocityHelper::Unpause(), and ns3::ConstantVelocityHelper::UpdateWithBounds().
Referenced by DoWalk().
Member Data Documentation
m_bounds
Rectangle ns3::RandomWalk2dOutdoorMobilityModel::m_bounds private
Bounds of the area to cruise.
Definition at line 126 of file random-walk-2d-outdoor-mobility-model.h.
Referenced by AvoidBuilding(), DoGetPosition(), DoSetPosition(), DoWalk(), GetTypeId(), and Rebound().
m_direction
Ptr<RandomVariableStream> ns3::RandomWalk2dOutdoorMobilityModel::m_direction private
rv for picking direction
Definition at line 125 of file random-walk-2d-outdoor-mobility-model.h.
Referenced by AvoidBuilding(), DoAssignStreams(), DoInitializePrivate(), and GetTypeId().
m_epsilon
double ns3::RandomWalk2dOutdoorMobilityModel::m_epsilon private
Tolerance for the intersection point with buildings.
Definition at line 127 of file random-walk-2d-outdoor-mobility-model.h.
Referenced by CalculateIntersectionFromOutside(), and GetTypeId().
m_event
EventId ns3::RandomWalk2dOutdoorMobilityModel::m_event private
stored event ID
Definition at line 120 of file random-walk-2d-outdoor-mobility-model.h.
Referenced by DoSetPosition(), and DoWalk().
m_helper
ConstantVelocityHelper ns3::RandomWalk2dOutdoorMobilityModel::m_helper private
helper for this object
Definition at line 119 of file random-walk-2d-outdoor-mobility-model.h.
Referenced by AvoidBuilding(), DoGetPosition(), DoGetVelocity(), DoInitializePrivate(), DoSetPosition(), DoWalk(), and Rebound().
m_maxIter
uint32_t ns3::RandomWalk2dOutdoorMobilityModel::m_maxIter private
Maximum number of tries to find the next position.
Definition at line 128 of file random-walk-2d-outdoor-mobility-model.h.
Referenced by AvoidBuilding(), and GetTypeId().
m_mode
enum Mode ns3::RandomWalk2dOutdoorMobilityModel::m_mode private
whether in time or distance mode
Definition at line 120 of file random-walk-2d-outdoor-mobility-model.h.
Referenced by DoInitializePrivate(), and GetTypeId().
m_modeDistance
double ns3::RandomWalk2dOutdoorMobilityModel::m_modeDistance private
Change direction and speed after this distance.
Definition at line 122 of file random-walk-2d-outdoor-mobility-model.h.
Referenced by DoInitializePrivate(), and GetTypeId().
m_modeTime
Time ns3::RandomWalk2dOutdoorMobilityModel::m_modeTime private
Change current direction and speed after this delay.
Definition at line 123 of file random-walk-2d-outdoor-mobility-model.h.
Referenced by DoInitializePrivate(), and GetTypeId().
m_prevPosition
Vector ns3::RandomWalk2dOutdoorMobilityModel::m_prevPosition private
Store the previous position in case a step back is needed.
Definition at line 129 of file random-walk-2d-outdoor-mobility-model.h.
Referenced by AvoidBuilding(), and DoWalk().
m_speed
Ptr<RandomVariableStream> ns3::RandomWalk2dOutdoorMobilityModel::m_speed private
rv for picking speed
Definition at line 124 of file random-walk-2d-outdoor-mobility-model.h.
Referenced by AvoidBuilding(), DoAssignStreams(), DoInitializePrivate(), and GetTypeId().
The documentation for this class was generated from the following files:
src/buildings/model/random-walk-2d-outdoor-mobility-model.h
src/buildings/model/random-walk-2d-outdoor-mobility-model.cc