ns-3: ns3::PacketSink Class Reference
ns3::PacketSink Class Reference
Applications » PacketSink
Receive and consume traffic generated to an IP address and port.
#include "packet-sink.h"
Classes
struct AddressHash
Hashing for the Address class.
Public Types
typedef void(* SeqTsSizeCallback) (Ptr< const Packet > p, const Address &from, const Address &to, const SeqTsSizeHeader &header)
TracedCallback signature for a reception with addresses and SeqTsSizeHeader.
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Public Member Functions
PacketSink ()
virtual ~PacketSink ()
std::list< Ptr< Socket > > GetAcceptedSockets (void) const
Ptr< Socket > GetListeningSocket (void) const
uint64_t GetTotalRx () const
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Application
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void HandleAccept (Ptr< Socket > socket, const Address &from)
Handle an incoming connection.
void HandlePeerClose (Ptr< Socket > socket)
Handle an connection close.
void HandlePeerError (Ptr< Socket > socket)
Handle an connection error.
void HandleRead (Ptr< Socket > socket)
Handle a packet received by the application.
void PacketReceived (const Ptr< Packet > &p, const Address &from, const Address &localAddress)
Packet received: assemble byte stream to extract SeqTsSizeHeader.
virtual void StartApplication (void)
Application specific startup code.
virtual void StopApplication (void)
Application specific shutdown code.
Private Attributes
std::unordered_map< Address, Ptr< Packet >, AddressHash > m_buffer
Buffer for received packets.
bool m_enableSeqTsSizeHeader {false}
Enable or disable the export of SeqTsSize header.
Address m_local
Local address to bind to.
TracedCallback< Ptr< const Packet >, const Address & > m_rxTrace
Traced Callback: received packets, source address.
TracedCallback< Ptr< const Packet >, const Address &, const Address & > m_rxTraceWithAddresses
Callback for tracing the packet Rx events, includes source and destination addresses.
TracedCallback< Ptr< const Packet >, const Address &, const Address &, const SeqTsSizeHeader & > m_rxTraceWithSeqTsSize
Callbacks for tracing the packet Rx events, includes source, destination addresses, and headers.
Ptr< Socket > m_socket
Listening socket.
std::list< Ptr< Socket > > m_socketList
the accepted sockets
TypeId m_tid
Protocol TypeId.
uint64_t m_totalRx
Total bytes received.
Additional Inherited Members
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Receive and consume traffic generated to an IP address and port.
This application was written to complement OnOffApplication, but it is more general so a PacketSink name was selected. Functionally it is important to use in multicast situations, so that reception of the layer-2 multicast frames of interest are enabled, but it is also useful for unicast as an example of how you can write something simple to receive packets at the application layer. Also, if an IP stack generates ICMP Port Unreachable errors, receiving applications will be needed.
The constructor specifies the Address (IP address and port) and the transport protocol to use. A virtual Receive () method is installed as a callback on the receiving socket. By default, when logging is enabled, it prints out the size of packets and their address. A tracing source to Receive() is also available.
Config Paths
ns3::PacketSink is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/ApplicationList/[i]/$ns3::PacketSink"
Attributes
Local: The Address on which to Bind the rx socket.
Set with class: AddressValue
Underlying type: Address
Initial value: 00-00-00
Flags: construct write read
Protocol: The type id of the protocol to use for the rx socket.
Set with class: TypeIdValue
Underlying type: TypeId
Initial value: ns3::UdpSocketFactory
Flags: construct write read
EnableSeqTsSizeHeader: Enable optional header tracing of SeqTsSizeHeader
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
Attributes defined in parent class ns3::Application
StartTime: Time at which the application will start
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
StopTime: Time at which the application will stop
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
TraceSources
Rx: A packet has been received
Callback signature: ns3::Packet::AddressTracedCallback
RxWithAddresses: A packet has been received
Callback signature: ns3::Packet::TwoAddressTracedCallback
RxWithSeqTsSize: A packet with SeqTsSize header has been received
Callback signature: ns3::PacketSink::SeqTsSizeCallback
Size of this type is 288 bytes (on a 64-bit architecture).
Definition at line 71 of file packet-sink.h.
Member Typedef Documentation
SeqTsSizeCallback
typedef void(* ns3::PacketSink::SeqTsSizeCallback) (Ptr< const Packet > p, const Address &from, const Address &to, const SeqTsSizeHeader &header)
TracedCallback signature for a reception with addresses and SeqTsSizeHeader.
Parameters
p The packet received (without the SeqTsSize header)
from From address
to Local address
header The SeqTsSize header
Definition at line 106 of file packet-sink.h.
Constructor & Destructor Documentation
PacketSink()
ns3::PacketSink::PacketSink ()
Definition at line 79 of file packet-sink.cc.
References m_socket, m_totalRx, and NS_LOG_FUNCTION.
~PacketSink()
ns3::PacketSink::~PacketSink () virtual
Definition at line 86 of file packet-sink.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::PacketSink::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Application.
Definition at line 111 of file packet-sink.cc.
References ns3::Application::DoDispose(), m_socket, m_socketList, and NS_LOG_FUNCTION.
GetAcceptedSockets()
std::list< Ptr< Socket > > ns3::PacketSink::GetAcceptedSockets (void) const
Returns
list of pointers to accepted sockets
Definition at line 105 of file packet-sink.cc.
References m_socketList, and NS_LOG_FUNCTION.
GetListeningSocket()
Ptr< Socket > ns3::PacketSink::GetListeningSocket (void) const
Returns
pointer to listening socket
Definition at line 98 of file packet-sink.cc.
References m_socket, and NS_LOG_FUNCTION.
GetTotalRx()
uint64_t ns3::PacketSink::GetTotalRx () const
Returns
the total bytes received in this sink app
Definition at line 91 of file packet-sink.cc.
References m_totalRx, and NS_LOG_FUNCTION.
Referenced by CalculateThroughput(), and LteAggregationThroughputScaleTestCase::GetThroughput().
GetTypeId()
TypeId ns3::PacketSink::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 43 of file packet-sink.cc.
References ns3::UdpSocketFactory::GetTypeId(), m_enableSeqTsSizeHeader, m_local, m_rxTrace, m_rxTraceWithAddresses, m_rxTraceWithSeqTsSize, m_tid, ns3::MakeAddressAccessor(), ns3::MakeAddressChecker(), ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeTypeIdAccessor(), ns3::MakeTypeIdChecker(), and ns3::TypeId::SetParent().
HandleAccept()
void ns3::PacketSink::HandleAccept (Ptr< Socket > socket, const Address & from) private
Handle an incoming connection.
Parameters
socket the incoming connection socket
from the address the connection is from
Definition at line 268 of file packet-sink.cc.
References HandleRead(), m_socketList, ns3::MakeCallback(), NS_LOG_FUNCTION, and ns3::Socket::SetRecvCallback().
Referenced by StartApplication().
HandlePeerClose()
void ns3::PacketSink::HandlePeerClose (Ptr< Socket > socket) private
Handle an connection close.
Parameters
socket the connected socket
Definition at line 258 of file packet-sink.cc.
References NS_LOG_FUNCTION.
Referenced by StartApplication().
HandlePeerError()
void ns3::PacketSink::HandlePeerError (Ptr< Socket > socket) private
Handle an connection error.
Parameters
socket the connected socket
Definition at line 263 of file packet-sink.cc.
References NS_LOG_FUNCTION.
Referenced by StartApplication().
HandleRead()
void ns3::PacketSink::HandleRead (Ptr< Socket > socket) private
Handle a packet received by the application.
Parameters
socket the receiving socket
Definition at line 176 of file packet-sink.cc.
References ns3::Inet6SocketAddress::ConvertFrom(), ns3::InetSocketAddress::ConvertFrom(), ns3::InetSocketAddress::GetIpv4(), ns3::Inet6SocketAddress::GetIpv6(), ns3::InetSocketAddress::GetPort(), ns3::Inet6SocketAddress::GetPort(), ns3::Packet::GetSize(), ns3::Socket::GetSockName(), ns3::Inet6SocketAddress::IsMatchingType(), ns3::InetSocketAddress::IsMatchingType(), m_enableSeqTsSizeHeader, m_rxTrace, m_rxTraceWithAddresses, m_totalRx, ns3::Simulator::Now(), NS_LOG_FUNCTION, NS_LOG_INFO, PacketReceived(), ns3::Socket::RecvFrom(), and ns3::Time::S.
Referenced by HandleAccept(), and StartApplication().
PacketReceived()
void ns3::PacketSink::PacketReceived (const Ptr< Packet > & p, const Address & from, const Address & localAddress) private
Packet received: assemble byte stream to extract SeqTsSizeHeader.
Parameters
p received packet
from from address
localAddress local address
The method assembles a received byte stream and extracts SeqTsSizeHeader instances from the stream to export in a trace source.
Definition at line 219 of file packet-sink.cc.
References ns3::Packet::AddAtEnd(), ns3::Packet::CreateFragment(), ns3::SeqTsSizeHeader::GetSerializedSize(), ns3::SeqTsSizeHeader::GetSize(), ns3::Packet::GetSize(), m_buffer, m_rxTraceWithSeqTsSize, NS_ABORT_IF, NS_LOG_DEBUG, ns3::Packet::PeekHeader(), ns3::Packet::RemoveAtStart(), and ns3::Packet::RemoveHeader().
Referenced by HandleRead().
StartApplication()
void ns3::PacketSink::StartApplication (void) private virtual
Application specific startup code.
The StartApplication method is called at the start time specified by Start This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 123 of file packet-sink.cc.
References ns3::Socket::Bind(), ns3::Socket::CreateSocket(), ns3::Application::GetNode(), HandleAccept(), HandlePeerClose(), HandlePeerError(), HandleRead(), ns3::addressUtils::IsMulticast(), ns3::Socket::Listen(), m_local, m_socket, m_tid, ns3::MakeCallback(), ns3::MakeNullCallback(), NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::Socket::SetAcceptCallback(), ns3::Socket::SetCloseCallbacks(), ns3::Socket::SetRecvCallback(), and ns3::Socket::ShutdownSend().
StopApplication()
void ns3::PacketSink::StopApplication (void) private virtual
Application specific shutdown code.
The StopApplication method is called at the stop time specified by Stop This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 160 of file packet-sink.cc.
References ns3::Socket::Close(), m_socket, m_socketList, ns3::MakeNullCallback(), NS_LOG_FUNCTION, and ns3::Socket::SetRecvCallback().
Member Data Documentation
m_buffer
std::unordered_map<Address, Ptr<Packet>, AddressHash> ns3::PacketSink::m_buffer private
Buffer for received packets.
Definition at line 172 of file packet-sink.h.
Referenced by PacketReceived().
m_enableSeqTsSizeHeader
bool ns3::PacketSink::m_enableSeqTsSizeHeader {false} private
Enable or disable the export of SeqTsSize header.
Definition at line 183 of file packet-sink.h.
Referenced by GetTypeId(), and HandleRead().
m_local
Address ns3::PacketSink::m_local private
Local address to bind to.
Definition at line 179 of file packet-sink.h.
Referenced by GetTypeId(), and StartApplication().
m_rxTrace
TracedCallback<Ptr<const Packet>, const Address &> ns3::PacketSink::m_rxTrace private
Traced Callback: received packets, source address.
Definition at line 186 of file packet-sink.h.
Referenced by GetTypeId(), and HandleRead().
m_rxTraceWithAddresses
TracedCallback<Ptr<const Packet>, const Address &, const Address &> ns3::PacketSink::m_rxTraceWithAddresses private
Callback for tracing the packet Rx events, includes source and destination addresses.
Definition at line 188 of file packet-sink.h.
Referenced by GetTypeId(), and HandleRead().
m_rxTraceWithSeqTsSize
TracedCallback<Ptr<const Packet>, const Address &, const Address &, const SeqTsSizeHeader&> ns3::PacketSink::m_rxTraceWithSeqTsSize private
Callbacks for tracing the packet Rx events, includes source, destination addresses, and headers.
Definition at line 190 of file packet-sink.h.
Referenced by GetTypeId(), and PacketReceived().
m_socket
Ptr<Socket> ns3::PacketSink::m_socket private
Listening socket.
Definition at line 176 of file packet-sink.h.
Referenced by PacketSink(), DoDispose(), GetListeningSocket(), StartApplication(), and StopApplication().
m_socketList
std::list<Ptr<Socket> > ns3::PacketSink::m_socketList private
the accepted sockets
Definition at line 177 of file packet-sink.h.
Referenced by DoDispose(), GetAcceptedSockets(), HandleAccept(), and StopApplication().
m_tid
TypeId ns3::PacketSink::m_tid private
Protocol TypeId.
Definition at line 181 of file packet-sink.h.
Referenced by GetTypeId(), and StartApplication().
m_totalRx
uint64_t ns3::PacketSink::m_totalRx private
Total bytes received.
Definition at line 180 of file packet-sink.h.
Referenced by PacketSink(), GetTotalRx(), and HandleRead().
The documentation for this class was generated from the following files:
src/applications/model/packet-sink.h
src/applications/model/packet-sink.cc