ns-3: ns3::Config::Resolver Class Reference
ns3::Config::Resolver Class Reference abstract
Abstract class to parse Config paths into object references.
Public Member Functions
Resolver (std::string path)
Construct from a base Config path.
virtual ~Resolver ()
Destructor.
void Resolve (Ptr< Object > root)
Parse the stored Config path into an object reference, beginning at the indicated root object.
Private Member Functions
void Canonicalize (void)
Ensure the Config path starts and ends with a '/'.
void DoArrayResolve (std::string path, const ObjectPtrContainerValue &vector)
Parse an index on the Config path.
virtual void DoOne (Ptr< Object > object, std::string path)=0
Handle one found object.
void DoResolve (std::string path, Ptr< Object > root)
Parse the next element in the Config path.
void DoResolveOne (Ptr< Object > object)
Handle one object found on the path.
std::string GetResolvedPath (void) const
Get the current Config path.
Private Attributes
std::string m_path
The Config path.
std::vector< std::string > m_workStack
Current list of path tokens.
Detailed Description
Abstract class to parse Config paths into object references.
Definition at line 301 of file config.cc.
Constructor & Destructor Documentation
Resolver()
ns3::Config::Resolver::Resolver (std::string path)
Construct from a base Config path.
Parameters
[in] path The Config path.
Definition at line 367 of file config.cc.
References Canonicalize(), and NS_LOG_FUNCTION.
~Resolver()
ns3::Config::Resolver::~Resolver () virtual
Destructor.
Definition at line 373 of file config.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Canonicalize()
void ns3::Config::Resolver::Canonicalize (void) private
Ensure the Config path starts and ends with a '/'.
Definition at line 378 of file config.cc.
References m_path, and NS_LOG_FUNCTION.
Referenced by Resolver().
DoArrayResolve()
void ns3::Config::Resolver::DoArrayResolve (std::string path, const ObjectPtrContainerValue & vector) private
Parse an index on the Config path.
Parameters
[in] path The remaining Config path.
[in,out] vector The resulting list of matching objects.
Definition at line 585 of file config.cc.
References ns3::ObjectPtrContainerValue::Begin(), DoResolve(), ns3::ObjectPtrContainerValue::End(), m_workStack, ns3::Config::ArrayMatcher::Matches(), NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by DoResolve().
DoOne()
virtual void ns3::Config::Resolver::DoOne (Ptr< Object > object, std::string path) private pure virtual
Handle one found object.
Parameters
[in] object The found object.
[in] path The matching Config path context.
Referenced by DoResolveOne().
DoResolve()
void ns3::Config::Resolver::DoResolve (std::string path, Ptr< Object > root) private
Parse the next element in the Config path.
Parameters
[in] path The remaining portion of the Config path.
[in] root The object corresponding to the current position in the Config path.
Definition at line 428 of file config.cc.
References ns3::TypeId::AttributeInformation::checker, DoArrayResolve(), DoResolveOne(), ns3::PointerValue::Get(), ns3::TypeId::GetAttribute(), ns3::ObjectBase::GetAttribute(), ns3::TypeId::GetAttributeN(), ns3::Object::GetInstanceTypeId(), ns3::Object::GetObject(), ns3::TypeId::GetParent(), GetResolvedPath(), ns3::TypeId::LookupByName(), m_workStack, ns3::TypeId::AttributeInformation::name, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_ERROR, NS_LOG_FUNCTION, and ns3::PeekPointer().
Referenced by DoArrayResolve(), and Resolve().
DoResolveOne()
void ns3::Config::Resolver::DoResolveOne (Ptr< Object > object) private
Handle one object found on the path.
Parameters
[in] object The current object on the Config path.
Definition at line 419 of file config.cc.
References DoOne(), GetResolvedPath(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by DoResolve().
GetResolvedPath()
std::string ns3::Config::Resolver::GetResolvedPath (void) const private
Get the current Config path.
Returns
The current Config path.
Definition at line 406 of file config.cc.
References m_workStack, and NS_LOG_FUNCTION.
Referenced by DoResolve(), and DoResolveOne().
Resolve()
void ns3::Config::Resolver::Resolve (Ptr< Object > root)
Parse the stored Config path into an object reference, beginning at the indicated root object.
Parameters
[in] root The object corresponding to the current position in in the Config path.
Definition at line 398 of file config.cc.
References DoResolve(), m_path, and NS_LOG_FUNCTION.
Member Data Documentation
m_path
std::string ns3::Config::Resolver::m_path private
The Config path.
Definition at line 363 of file config.cc.
Referenced by Canonicalize(), and Resolve().
m_workStack
std::vector<std::string> ns3::Config::Resolver::m_workStack private
Current list of path tokens.
Definition at line 361 of file config.cc.
Referenced by DoArrayResolve(), DoResolve(), and GetResolvedPath().
The documentation for this class was generated from the following file:
src/core/model/config.cc