ns-3: ns3::Ipv6Extension Class Reference
ns3::Ipv6Extension Class Reference abstract
Internet » IPv6 classes and sub-modules » IPV6 Header extension system.
IPv6 Extension base If you want to implement a new IPv6 extension, all you have to do is implement a subclass of this class and add it to an Ipv6ExtensionDemux.
#include "ipv6-extension.h"
Public Member Functions
Ipv6Extension ()
Constructor.
virtual ~Ipv6Extension ()
Destructor.
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
virtual uint8_t GetExtensionNumber () const =0
Get the extension number.
Ptr< Node > GetNode () const
Get the node.
virtual uint8_t Process (Ptr< Packet > &packet, uint8_t offset, Ipv6Header const &ipv6Header, Ipv6Address dst, uint8_t *nextHeader, bool &stopProcessing, bool &isDropped, Ipv6L3Protocol::DropReason &dropReason)=0
Process method Called from Ipv6L3Protocol::Receive.
virtual uint8_t ProcessOptions (Ptr< Packet > &packet, uint8_t offset, uint8_t length, Ipv6Header const &ipv6Header, Ipv6Address dst, uint8_t *nextHeader, bool &stopProcessing, bool &isDropped, Ipv6L3Protocol::DropReason &dropReason)
Process options Called by implementing classes to process the options.
void SetNode (Ptr< Node > node)
Set the node.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Attributes
Ptr< UniformRandomVariable > m_uvar
Provides uniform random variables.
Private Attributes
Ptr< Node > m_node
The node.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
IPv6 Extension base If you want to implement a new IPv6 extension, all you have to do is implement a subclass of this class and add it to an Ipv6ExtensionDemux.
Introspection did not find any typical Config paths.
Attributes
ExtensionNumber: The IPv6 extension number.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Flags: read
No TraceSources are defined for this type.
Size of this type is 48 bytes (on a 64-bit architecture).
Definition at line 55 of file ipv6-extension.h.
Constructor & Destructor Documentation
Ipv6Extension()
ns3::Ipv6Extension::Ipv6Extension ()
Constructor.
Definition at line 62 of file ipv6-extension.cc.
References m_uvar.
~Ipv6Extension()
ns3::Ipv6Extension::~Ipv6Extension () virtual
Destructor.
Definition at line 67 of file ipv6-extension.cc.
Member Function Documentation
AssignStreams()
int64_t ns3::Ipv6Extension::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 178 of file ipv6-extension.cc.
References m_uvar, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
Referenced by ns3::InternetStackHelper::AssignStreams().
GetExtensionNumber()
virtual uint8_t ns3::Ipv6Extension::GetExtensionNumber () const pure virtual
Get the extension number.
Returns
extension number
Implemented in ns3::Ipv6ExtensionAH, ns3::Ipv6ExtensionESP, ns3::Ipv6ExtensionRouting, ns3::Ipv6ExtensionFragment, ns3::Ipv6ExtensionDestination, and ns3::Ipv6ExtensionHopByHop.
Referenced by GetTypeId().
GetNode()
Ptr< Node > ns3::Ipv6Extension::GetNode (void) const
Get the node.
Returns
the node
Definition at line 78 of file ipv6-extension.cc.
References m_node.
Referenced by ns3::Ipv6ExtensionFragment::GetFragments(), ns3::Ipv6ExtensionFragment::HandleFragmentsTimeout(), ns3::Ipv6ExtensionRouting::Process(), ns3::Ipv6ExtensionLooseRouting::Process(), and ProcessOptions().
GetTypeId()
TypeId ns3::Ipv6Extension::GetTypeId (void) static
Get the type identificator.
Returns
type identificator
Definition at line 49 of file ipv6-extension.cc.
References GetExtensionNumber(), ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
Process()
virtual uint8_t ns3::Ipv6Extension::Process (Ptr< Packet > & packet, uint8_t offset, Ipv6Header const & ipv6Header, Ipv6Address dst, uint8_t * nextHeader, bool & stopProcessing, bool & isDropped, Ipv6L3Protocol::DropReason & dropReason) pure virtual
Process method Called from Ipv6L3Protocol::Receive.
Parameters
packet the packet
offset the offset of the extension to process
ipv6Header the IPv6 header of packet received
dst destination address of the packet received (i.e. us)
nextHeader the next header
stopProcessing true if the packet must not be further processed
isDropped true if the packet must be dropped
dropReason dropping reason
Returns
the size processed
Implemented in ns3::Ipv6ExtensionAH, ns3::Ipv6ExtensionESP, ns3::Ipv6ExtensionLooseRouting, ns3::Ipv6ExtensionRouting, ns3::Ipv6ExtensionFragment, ns3::Ipv6ExtensionDestination, and ns3::Ipv6ExtensionHopByHop.
ProcessOptions()
uint8_t ns3::Ipv6Extension::ProcessOptions (Ptr< Packet > & packet, uint8_t offset, uint8_t length, Ipv6Header const & ipv6Header, Ipv6Address dst, uint8_t * nextHeader, bool & stopProcessing, bool & isDropped, Ipv6L3Protocol::DropReason & dropReason) virtual
Process options Called by implementing classes to process the options.
Parameters
packet the packet
offset the offset of the first option to process
length the total length of all options (as specified in the extension header)
ipv6Header the IPv6 header of packet received
dst destination address of the packet received (i.e. us)
nextHeader the next header
stopProcessing true if the packet must not be further processed
isDropped true if the packet must be dropped
dropReason dropping reason
Returns
the size processed
Definition at line 83 of file ipv6-extension.cc.
References ns3::Packet::AddHeader(), ns3::Packet::Copy(), ns3::Packet::CopyData(), data, ns3::Ipv6L3Protocol::DROP_UNKNOWN_OPTION, ns3::Ipv6Header::GetDestinationAddress(), GetNode(), ns3::Object::GetObject(), ns3::Packet::GetSize(), ns3::Ipv6Header::GetSourceAddress(), ns3::Icmpv6Header::ICMPV6_UNKNOWN_OPTION, ns3::Ipv6Address::IsMulticast(), NS_LOG_FUNCTION, NS_LOG_LOGIC, and ns3::Packet::RemoveAtStart().
Referenced by ns3::Ipv6ExtensionHopByHop::Process(), and ns3::Ipv6ExtensionDestination::Process().
SetNode()
void ns3::Ipv6Extension::SetNode (Ptr< Node > node)
Set the node.
Parameters
node the node to set
Definition at line 71 of file ipv6-extension.cc.
References m_node, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv6L3Protocol::RegisterExtensions().
Member Data Documentation
m_node
Ptr<Node> ns3::Ipv6Extension::m_node private
The node.
Definition at line 161 of file ipv6-extension.h.
Referenced by ns3::Ipv6ExtensionRoutingDemux::DoDispose(), GetNode(), SetNode(), and ns3::Ipv6ExtensionRoutingDemux::SetNode().
m_uvar
Ptr<UniformRandomVariable> ns3::Ipv6Extension::m_uvar protected
Provides uniform random variables.
Definition at line 155 of file ipv6-extension.h.
Referenced by Ipv6Extension(), AssignStreams(), and ns3::Ipv6ExtensionFragment::GetFragments().
The documentation for this class was generated from the following files:
src/internet/model/ipv6-extension.h
src/internet/model/ipv6-extension.cc