ns-3: ns3::UanHeaderRcData Class Reference
ns3::UanHeaderRcData Class Reference
UAN Models
Extra data header information.
#include "uan-header-rc.h"
Public Member Functions
UanHeaderRcData ()
Default constructor.
UanHeaderRcData (uint8_t frameNum, Time propDelay)
Constructor.
virtual ~UanHeaderRcData ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
uint8_t GetFrameNo (void) const
Get the frame number of the reservation being transmitted.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
Time GetPropDelay (void) const
Get the propagation delay found in handshaking.
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
void Print (std::ostream &os, Time::Unit unit) const
Specialized Print with Time::Unit declared.
virtual void Serialize (Buffer::Iterator start) const
void SetFrameNo (uint8_t frameNum)
Set the frame number of the reservation being transmitted.
void SetPropDelay (Time propDelay)
Set the propagation delay as found in handshaking.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_frameNo
Data frame number.
Time m_propDelay
Propagation delay.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Extra data header information.
Introspection did not find any typical Config paths.
Adds propagation delay measure, and frame number info to transmitted data packet.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 24 bytes (on a 64-bit architecture).
Definition at line 41 of file uan-header-rc.h.
Constructor & Destructor Documentation
UanHeaderRcData() [1/2]
ns3::UanHeaderRcData::UanHeaderRcData ()
Default constructor.
Definition at line 35 of file uan-header-rc.cc.
UanHeaderRcData() [2/2]
ns3::UanHeaderRcData::UanHeaderRcData (uint8_t frameNum, Time propDelay)
Constructor.
Parameters
frameNum Data frame # of reservation being transmitted.
propDelay Measured propagation delay found in handshaking.
Note
Prop. delay is transmitted with 16 bits and ms accuracy.
Definition at line 42 of file uan-header-rc.cc.
~UanHeaderRcData()
ns3::UanHeaderRcData::~UanHeaderRcData () virtual
Destructor.
Definition at line 50 of file uan-header-rc.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::UanHeaderRcData::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 102 of file uan-header-rc.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_frameNo, m_propDelay, ns3::Seconds(), and visualizer.core::start().
GetFrameNo()
uint8_t ns3::UanHeaderRcData::GetFrameNo (void) const
Get the frame number of the reservation being transmitted.
Returns
The data frame number.
Definition at line 78 of file uan-header-rc.cc.
References m_frameNo.
Referenced by ns3::UanMacRcGw::ReceivePacket().
GetInstanceTypeId()
TypeId ns3::UanHeaderRcData::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 125 of file uan-header-rc.cc.
References GetTypeId().
GetPropDelay()
Time ns3::UanHeaderRcData::GetPropDelay (void) const
Get the propagation delay found in handshaking.
Returns
The measured propagation delay.
Note
Prop. delay is transmitted with 16 bits and ms accuracy
Definition at line 84 of file uan-header-rc.cc.
References m_propDelay.
Referenced by ns3::UanMacRcGw::ReceivePacket().
GetSerializedSize()
uint32_t ns3::UanHeaderRcData::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 90 of file uan-header-rc.cc.
Referenced by ns3::Reservation::Reservation().
GetTypeId()
TypeId ns3::UanHeaderRcData::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 55 of file uan-header-rc.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print() [1/2]
void ns3::UanHeaderRcData::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 119 of file uan-header-rc.cc.
References Print(), and ns3::Time::S.
Print() [2/2]
void ns3::UanHeaderRcData::Print (std::ostream & os, Time::Unit unit) const
Specialized Print with Time::Unit declared.
Parameters
os ostream.
unit Time unit.
Definition at line 113 of file uan-header-rc.cc.
References ns3::Time::As(), m_frameNo, and m_propDelay.
Referenced by Print().
Serialize()
void ns3::UanHeaderRcData::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 96 of file uan-header-rc.cc.
References ns3::Time::GetMilliSeconds(), m_frameNo, m_propDelay, ns3::Time::MS, ns3::Time::RoundTo(), and visualizer.core::start().
SetFrameNo()
void ns3::UanHeaderRcData::SetFrameNo (uint8_t frameNum)
Set the frame number of the reservation being transmitted.
Parameters
frameNum The data frame number.
Definition at line 66 of file uan-header-rc.cc.
References m_frameNo.
Referenced by ns3::UanMacRc::ScheduleData().
SetPropDelay()
void ns3::UanHeaderRcData::SetPropDelay (Time propDelay)
Set the propagation delay as found in handshaking.
Parameters
propDelay The measured propagation delay.
Note
Prop. delay is transmitted with 16 bits and ms accuracy.
Definition at line 72 of file uan-header-rc.cc.
References m_propDelay.
Referenced by ns3::UanMacRc::ScheduleData().
Member Data Documentation
m_frameNo
uint8_t ns3::UanHeaderRcData::m_frameNo private
Data frame number.
Definition at line 105 of file uan-header-rc.h.
Referenced by Deserialize(), GetFrameNo(), Print(), Serialize(), and SetFrameNo().
m_propDelay
Time ns3::UanHeaderRcData::m_propDelay private
Propagation delay.
Definition at line 106 of file uan-header-rc.h.
Referenced by Deserialize(), GetPropDelay(), Print(), Serialize(), and SetPropDelay().
The documentation for this class was generated from the following files:
src/uan/model/uan-header-rc.h
src/uan/model/uan-header-rc.cc