ns-3: ns3::BuildingsHelper Class Reference
ns3::BuildingsHelper Class Reference
#include "buildings-helper.h"
Static Public Member Functions
static void Install (NodeContainer c)
Install the MobilityBuildingInfo to the set of nodes in a NodeContainer.
static void Install (Ptr< Node > node)
Install the MobilityBuildingInfo to a node.
static NS_DEPRECATED void MakeConsistent (Ptr< MobilityModel > mm)
Make the given mobility model consistent, by determining whether its position falls inside any of the building in BuildingList, and updating accordingly the BuildingInfo aggregated with the MobilityModel.
static NS_DEPRECATED_3_31 void MakeMobilityModelConsistent ()
This method goes through the whole NodeList and, for each node in the list, calls BuildingsHelper::MakeConsistent() passing to it the MobilityModel of that node.
Detailed Description
Definition at line 36 of file buildings-helper.h.
Member Function Documentation
Install() [1/2]
void ns3::BuildingsHelper::Install (NodeContainer c) static
Install the MobilityBuildingInfo to the set of nodes in a NodeContainer.
Parameters
c the NodeContainer including the nodes to be updated
Definition at line 37 of file buildings-helper.cc.
References ns3::NodeContainer::Begin(), ns3::NodeContainer::End(), and Install().
Install() [2/2]
void ns3::BuildingsHelper::Install (Ptr< Node > node) static
Install the MobilityBuildingInfo to a node.
Parameters
node the mobility model of the node to be updated
Definition at line 47 of file buildings-helper.cc.
References ns3::Object::AggregateObject(), ns3::Node::GetId(), ns3::Object::GetObject(), and NS_ABORT_MSG_UNLESS.
Referenced by Install().
MakeConsistent()
void ns3::BuildingsHelper::MakeConsistent (Ptr< MobilityModel > mm) static
Make the given mobility model consistent, by determining whether its position falls inside any of the building in BuildingList, and updating accordingly the BuildingInfo aggregated with the MobilityModel.
Parameters
mm the mobility model to be made consistent
Deprecated:
This method will go away in future release of ns-3. See instead MakeConsistent method of MobilityBuildingInfo class.
Definition at line 80 of file buildings-helper.cc.
References ns3::BuildingList::Begin(), ns3::BuildingList::End(), ns3::Object::GetObject(), ns3::MobilityModel::GetPosition(), NS_ABORT_MSG_UNLESS, and NS_LOG_LOGIC.
MakeMobilityModelConsistent()
void ns3::BuildingsHelper::MakeMobilityModelConsistent () static
This method goes through the whole NodeList and, for each node in the list, calls BuildingsHelper::MakeConsistent() passing to it the MobilityModel of that node.
Deprecated:
This method will go away in future release of ns-3. A node position will be make consistent by the method IsInside () of MobilityBuildingInfo class.
Definition at line 63 of file buildings-helper.cc.
References ns3::NodeList::Begin(), ns3::NodeList::End(), ns3::Object::GetObject(), NS_ABORT_MSG_UNLESS, and NS_LOG_FUNCTION_NOARGS.
The documentation for this class was generated from the following files:
src/buildings/helper/buildings-helper.h
src/buildings/helper/buildings-helper.cc