ns-3: ns3::DropTailQueue< Item > Class Template Reference
ns3::DropTailQueue< Item > Class Template Reference
Network » Queue
A FIFO packet queue that drops tail-end packets on overflow.
#include "drop-tail-queue.h"
Public Member Functions
DropTailQueue ()
DropTailQueue Constructor.
virtual ~DropTailQueue ()
virtual Ptr< Item > Dequeue (void)
Remove an item from the Queue (each subclass defines the position), counting it as dequeued.
virtual bool Enqueue (Ptr< Item > item)
Place an item into the Queue (each subclass defines the position)
virtual Ptr< const Item > Peek (void) const
Get a copy of an item in the queue (each subclass defines the position) without removing it.
virtual Ptr< Item > Remove (void)
Remove an item from the Queue (each subclass defines the position), counting it as dropped.
Public Member Functions inherited from ns3::Queue< Item >
Queue ()
virtual ~Queue ()
void Flush (void)
Flush the queue.
Public Member Functions inherited from ns3::QueueBase
QueueBase ()
virtual ~QueueBase ()
QueueSize GetCurrentSize (void) const
QueueSize GetMaxSize (void) const
uint32_t GetNBytes (void) const
uint32_t GetNPackets (void) const
uint32_t GetTotalDroppedBytes (void) const
uint32_t GetTotalDroppedBytesAfterDequeue (void) const
uint32_t GetTotalDroppedBytesBeforeEnqueue (void) const
uint32_t GetTotalDroppedPackets (void) const
uint32_t GetTotalDroppedPacketsAfterDequeue (void) const
uint32_t GetTotalDroppedPacketsBeforeEnqueue (void) const
uint32_t GetTotalReceivedBytes (void) const
uint32_t GetTotalReceivedPackets (void) const
bool IsEmpty (void) const
void ResetStatistics (void)
Resets the counts for dropped packets, dropped bytes, received packets, and received bytes.
void SetMaxSize (QueueSize size)
Set the maximum size of this queue.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Queue< Item >
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::QueueBase
static void AppendItemTypeIfNotPresent (std::string &typeId, const std::string &itemType)
Append the item type to the provided type ID if the latter does not end with '>'.
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
NS_LOG_TEMPLATE_DECLARE
redefinition of the log component
Additional Inherited Members
Public Types inherited from ns3::Queue< Item >
typedef Item ItemType
Define ItemType as the type of the stored elements.
Protected Types inherited from ns3::Queue< Item >
typedef std::list< Ptr< Item > >::const_iterator ConstIterator
Const iterator.
typedef std::list< Ptr< Item > >::iterator Iterator
Iterator.
Protected Member Functions inherited from ns3::Queue< Item >
Iterator begin (void)
Get an iterator which refers to the first item in the queue.
ConstIterator begin (void) const
Get a const iterator which refers to the first item in the queue.
Ptr< Item > DoDequeue (ConstIterator pos)
Pull the item to dequeue from the queue.
bool DoEnqueue (ConstIterator pos, Ptr< Item > item)
Push an item in the queue.
Ptr< const Item > DoPeek (ConstIterator pos) const
Peek the front item in the queue.
Ptr< Item > DoRemove (ConstIterator pos)
Pull the item to drop from the queue.
void DropAfterDequeue (Ptr< Item > item)
Drop a packet after dequeue.
void DropBeforeEnqueue (Ptr< Item > item)
Drop a packet before enqueue.
Iterator end (void)
Get an iterator which indicates past-the-last item in the queue.
ConstIterator end (void) const
Get a const iterator which indicates past-the-last item in the queue.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
template<typename Item>
class ns3::DropTailQueue< Item >
A FIFO packet queue that drops tail-end packets on overflow.
Definition at line 32 of file drop-tail-queue.h.
Constructor & Destructor Documentation
DropTailQueue()
template<typename Item > ns3::DropTailQueue< Item >::DropTailQueue
DropTailQueue Constructor.
Creates a droptail queue with a maximum size of 100 packets by default
Definition at line 89 of file drop-tail-queue.h.
References NS_LOG_FUNCTION.
~DropTailQueue()
template<typename Item > ns3::DropTailQueue< Item >::~DropTailQueue virtual
Definition at line 97 of file drop-tail-queue.h.
References NS_LOG_FUNCTION.
Member Function Documentation
Dequeue()
template<typename Item > Ptr< Item > ns3::DropTailQueue< Item >::Dequeue (void) virtual
Remove an item from the Queue (each subclass defines the position), counting it as dequeued.
Returns
0 if the operation was not successful; the item otherwise.
Implements ns3::Queue< Item >.
Definition at line 113 of file drop-tail-queue.h.
References NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Enqueue()
template<typename Item > bool ns3::DropTailQueue< Item >::Enqueue (Ptr< Item > item) virtual
Place an item into the Queue (each subclass defines the position)
Parameters
item item to enqueue
Returns
True if the operation was successful; false otherwise
Implements ns3::Queue< Item >.
Definition at line 104 of file drop-tail-queue.h.
References NS_LOG_FUNCTION.
GetTypeId()
template<typename Item > TypeId ns3::DropTailQueue< Item >::GetTypeId (void) static
Get the type ID.
Implementation of the templates declared above.
Returns
the object TypeId
Definition at line 72 of file drop-tail-queue.h.
References ns3::QueueBase::GetMaxSize(), ns3::GetTypeParamName(), ns3::MakeQueueSizeAccessor(), ns3::MakeQueueSizeChecker(), ns3::QueueBase::SetMaxSize(), and ns3::TypeId::SetParent().
Peek()
template<typename Item > Ptr< const Item > ns3::DropTailQueue< Item >::Peek (void) const virtual
Get a copy of an item in the queue (each subclass defines the position) without removing it.
Returns
0 if the operation was not successful; the item otherwise.
Implements ns3::Queue< Item >.
Definition at line 139 of file drop-tail-queue.h.
References NS_LOG_FUNCTION.
Remove()
template<typename Item > Ptr< Item > ns3::DropTailQueue< Item >::Remove (void) virtual
Remove an item from the Queue (each subclass defines the position), counting it as dropped.
Returns
0 if the operation was not successful; the item otherwise.
Implements ns3::Queue< Item >.
Definition at line 126 of file drop-tail-queue.h.
References NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Member Data Documentation
NS_LOG_TEMPLATE_DECLARE
template<typename Item > ns3::DropTailQueue< Item >::NS_LOG_TEMPLATE_DECLARE private
redefinition of the log component
Definition at line 62 of file drop-tail-queue.h.
The documentation for this class was generated from the following file:
src/network/utils/drop-tail-queue.h