ns-3: ns3::dsr::DsrOptionRreqHeader Class Reference
ns3::dsr::DsrOptionRreqHeader Class Reference
DSR Routing
Route Request (RREQ) Message Format.
#include "dsr-option-header.h"
Public Member Functions
DsrOptionRreqHeader ()
Constructor.
virtual ~DsrOptionRreqHeader ()
Destructor.
void AddNodeAddress (Ipv4Address ipv4)
Add one node address.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
virtual Alignment GetAlignment () const
Get the Alignment requirement of this option header.
uint16_t GetId () const
Set the request id number.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
Ipv4Address GetNodeAddress (uint8_t index) const
Get a Node IPv4 Address.
std::vector< Ipv4Address > GetNodesAddresses () const
Get the vector of ipv4 address.
uint32_t GetNodesNumber () const
Get the number of nodes.
virtual uint32_t GetSerializedSize () const
Get the serialized size of the packet.
Ipv4Address GetTarget ()
Get the target ipv4 address.
virtual void Print (std::ostream &os) const
Print some information about the packet.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetId (uint16_t identification)
Set the request id number.
void SetNodeAddress (uint8_t index, Ipv4Address addr)
Set a Node IPv4 Address.
void SetNodesAddress (std::vector< Ipv4Address > ipv4Address)
Set the vector of ipv4 address.
void SetNumberAddress (uint8_t n)
Set the number of ipv4 address.
void SetTarget (Ipv4Address target)
Set the target ipv4 address.
Public Member Functions inherited from ns3::dsr::DsrOptionHeader
DsrOptionHeader ()
Constructor.
virtual ~DsrOptionHeader ()
Destructor.
uint8_t GetLength () const
Get the option length.
uint8_t GetType () const
Get the type of the option.
void SetLength (uint8_t length)
Set the option length.
void SetType (uint8_t type)
Set the type of the option.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::dsr::DsrOptionHeader
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef std::vector< Ipv4Address > VectorIpv4Address_t
A vector of IPv4 Address.
Private Attributes
Ipv4Address m_address
Ipv4 address to write when desearizing the packet.
uint16_t m_identification
Identifier of the packet.
VectorIpv4Address_t m_ipv4Address
The vector of Nodes' IPv4 Address.
Ipv4Address m_target
Ipv4 address of target node.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Route Request (RREQ) Message Format.
Introspection did not find any typical Config paths.
 |      0        |      1        |      2        |      3        |
 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |  Option Type |  Opt Data Len |         Identification         |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                         Target Address                        |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                            Address[1]                         |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                            Address[2]                         |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                               ...                             |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                            Address[n]                         |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 96 bytes (on a 64-bit architecture).
Definition at line 272 of file dsr-option-header.h.
Member Typedef Documentation
VectorIpv4Address_t
typedef std::vector<Ipv4Address> ns3::dsr::DsrOptionRreqHeader::VectorIpv4Address_t private
A vector of IPv4 Address.
Definition at line 394 of file dsr-option-header.h.
Constructor & Destructor Documentation
DsrOptionRreqHeader()
ns3::dsr::DsrOptionRreqHeader::DsrOptionRreqHeader ()
Constructor.
Definition at line 266 of file dsr-option-header.cc.
References m_ipv4Address, ns3::dsr::DsrOptionHeader::SetLength(), and ns3::dsr::DsrOptionHeader::SetType().
~DsrOptionRreqHeader()
ns3::dsr::DsrOptionRreqHeader::~DsrOptionRreqHeader () virtual
Destructor.
Definition at line 273 of file dsr-option-header.cc.
Member Function Documentation
AddNodeAddress()
void ns3::dsr::DsrOptionRreqHeader::AddNodeAddress (Ipv4Address ipv4)
Add one node address.
Parameters
ipv4 The ip address to add
Definition at line 293 of file dsr-option-header.cc.
References m_ipv4Address, and ns3::dsr::DsrOptionHeader::SetLength().
Referenced by ns3::dsr::DsrRouting::SendErrorRequest(), and ns3::dsr::DsrRouting::SendInitialRequest().
Deserialize()
uint32_t ns3::dsr::DsrOptionRreqHeader::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start Buffer iterator
Returns
size of the packet
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 369 of file dsr-option-header.cc.
References ns3::Ipv4Address::Deserialize(), GetSerializedSize(), m_address, m_identification, m_ipv4Address, m_target, ns3::Buffer::Iterator::Read(), ns3::ReadFrom(), ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadU8(), ns3::dsr::DsrOptionHeader::SetLength(), SetNodeAddress(), ns3::dsr::DsrOptionHeader::SetType(), and visualizer.core::start().
GetAlignment()
DsrOptionHeader::Alignment ns3::dsr::DsrOptionRreqHeader::GetAlignment () const virtual
Get the Alignment requirement of this option header.
Returns
The required alignment
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 391 of file dsr-option-header.cc.
GetId()
uint16_t ns3::dsr::DsrOptionRreqHeader::GetId (void) const
Set the request id number.
Returns
request id number
Definition at line 330 of file dsr-option-header.cc.
References m_identification.
Referenced by DsrRreqHeaderTest::DoRun(), and ns3::dsr::DsrOptionRreq::Process().
GetInstanceTypeId()
TypeId ns3::dsr::DsrOptionRreqHeader::GetInstanceTypeId (void) const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 261 of file dsr-option-header.cc.
References GetTypeId().
GetNodeAddress()
Ipv4Address ns3::dsr::DsrOptionRreqHeader::GetNodeAddress (uint8_t index) const
Get a Node IPv4 Address.
Parameters
index the index of the IPv4 Address
Returns
the router IPv4 Address
Definition at line 320 of file dsr-option-header.cc.
References m_ipv4Address.
Referenced by DsrRreqHeaderTest::DoRun().
GetNodesAddresses()
std::vector< Ipv4Address > ns3::dsr::DsrOptionRreqHeader::GetNodesAddresses () const
Get the vector of ipv4 address.
Returns
the vector of ipv4 address
Definition at line 305 of file dsr-option-header.cc.
References m_ipv4Address.
Referenced by ns3::dsr::DsrOptionRreq::Process().
GetNodesNumber()
uint32_t ns3::dsr::DsrOptionRreqHeader::GetNodesNumber () const
Get the number of nodes.
Returns
the number of nodes
Definition at line 310 of file dsr-option-header.cc.
References m_ipv4Address.
GetSerializedSize()
uint32_t ns3::dsr::DsrOptionRreqHeader::GetSerializedSize (void) const virtual
Get the serialized size of the packet.
Returns
size
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 347 of file dsr-option-header.cc.
References m_ipv4Address.
Referenced by Deserialize(), and ns3::dsr::DsrOptionRreq::Process().
GetTarget()
Ipv4Address ns3::dsr::DsrOptionRreqHeader::GetTarget ()
Get the target ipv4 address.
Returns
target the target packet
Definition at line 283 of file dsr-option-header.cc.
References m_target.
Referenced by DsrRreqHeaderTest::DoRun(), and ns3::dsr::DsrOptionRreq::Process().
GetTypeId()
TypeId ns3::dsr::DsrOptionRreqHeader::GetTypeId (void) static
Get the type identificator.
Returns
type identificator
Definition at line 251 of file dsr-option-header.cc.
References ns3::TypeId::AddConstructor().
Referenced by GetInstanceTypeId().
Print()
void ns3::dsr::DsrOptionRreqHeader::Print (std::ostream & os) const virtual
Print some information about the packet.
Parameters
os output stream
Returns
info about this packet
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 335 of file dsr-option-header.cc.
References ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrOptionHeader::GetType(), and m_ipv4Address.
Serialize()
void ns3::dsr::DsrOptionRreqHeader::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start Buffer iterator
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 352 of file dsr-option-header.cc.
References ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrOptionHeader::GetType(), m_identification, m_ipv4Address, m_target, visualizer.core::start(), ns3::Buffer::Iterator::Write(), ns3::Buffer::Iterator::WriteHtonU16(), ns3::WriteTo(), and ns3::Buffer::Iterator::WriteU8().
SetId()
void ns3::dsr::DsrOptionRreqHeader::SetId (uint16_t identification)
Set the request id number.
Parameters
identification the identification number
Definition at line 325 of file dsr-option-header.cc.
References m_identification.
Referenced by DsrRreqHeaderTest::DoRun(), ns3::dsr::DsrRouting::SendErrorRequest(), and ns3::dsr::DsrRouting::SendInitialRequest().
SetNodeAddress()
void ns3::dsr::DsrOptionRreqHeader::SetNodeAddress (uint8_t index, Ipv4Address addr)
Set a Node IPv4 Address.
Parameters
index the index of the IPv4 Address
addr the new IPv4 Address
Definition at line 315 of file dsr-option-header.cc.
References m_ipv4Address.
Referenced by Deserialize().
SetNodesAddress()
void ns3::dsr::DsrOptionRreqHeader::SetNodesAddress (std::vector< Ipv4Address > ipv4Address)
Set the vector of ipv4 address.
Parameters
ipv4Address the vector of ipv4 address
Definition at line 299 of file dsr-option-header.cc.
References m_ipv4Address, and ns3::dsr::DsrOptionHeader::SetLength().
Referenced by DsrRreqHeaderTest::DoRun(), and ns3::dsr::DsrOptionRreq::Process().
SetNumberAddress()
void ns3::dsr::DsrOptionRreqHeader::SetNumberAddress (uint8_t n)
Set the number of ipv4 address.
Parameters
n the number of ipv4 address
Definition at line 277 of file dsr-option-header.cc.
References m_ipv4Address, and sample-rng-plot::n.
Referenced by DsrRreqHeaderTest::DoRun(), and ns3::dsr::DsrOptionRreq::Process().
SetTarget()
void ns3::dsr::DsrOptionRreqHeader::SetTarget (Ipv4Address target)
Set the target ipv4 address.
Parameters
target the target packet
Definition at line 288 of file dsr-option-header.cc.
References m_target.
Referenced by DsrRreqHeaderTest::DoRun(), ns3::dsr::DsrRouting::SendErrorRequest(), and ns3::dsr::DsrRouting::SendInitialRequest().
Member Data Documentation
m_address
Ipv4Address ns3::dsr::DsrOptionRreqHeader::m_address private
Ipv4 address to write when desearizing the packet.
Definition at line 390 of file dsr-option-header.h.
Referenced by Deserialize().
m_identification
uint16_t ns3::dsr::DsrOptionRreqHeader::m_identification private
Identifier of the packet.
Definition at line 382 of file dsr-option-header.h.
Referenced by Deserialize(), GetId(), Serialize(), and SetId().
m_ipv4Address
VectorIpv4Address_t ns3::dsr::DsrOptionRreqHeader::m_ipv4Address private
The vector of Nodes' IPv4 Address.
Definition at line 398 of file dsr-option-header.h.
Referenced by DsrOptionRreqHeader(), AddNodeAddress(), Deserialize(), GetNodeAddress(), GetNodesAddresses(), GetNodesNumber(), GetSerializedSize(), Print(), Serialize(), SetNodeAddress(), SetNodesAddress(), and SetNumberAddress().
m_target
Ipv4Address ns3::dsr::DsrOptionRreqHeader::m_target private
Ipv4 address of target node.
Definition at line 386 of file dsr-option-header.h.
Referenced by Deserialize(), GetTarget(), Serialize(), and SetTarget().
The documentation for this class was generated from the following files:
src/dsr/model/dsr-option-header.h
src/dsr/model/dsr-option-header.cc