ns-3: ns3::WimaxNetDevice Class Reference
ns3::WimaxNetDevice Class Reference abstract
WiMAX Models
Hold together all WiMAX-related objects in a NetDevice.
#include "wimax-net-device.h"
Public Types
enum Direction { DIRECTION_DOWNLINK , DIRECTION_UPLINK }
Direction enumeration.
enum RangingStatus { RANGING_STATUS_EXPIRED , RANGING_STATUS_CONTINUE , RANGING_STATUS_ABORT , RANGING_STATUS_SUCCESS }
RangingStatus enumeration.
typedef void(* TxRxTracedCallback) (Ptr< const Packet > packet, const Mac48Address &mac)
TracedCallback signature for packet and Mac48Address.
Public Types inherited from ns3::NetDevice
typedef void(* LinkChangeTracedCallback) (void)
TracedCallback signature for link changed event.
enum PacketType {
PACKET_HOST = 1 , NS3_PACKET_HOST = PACKET_HOST , PACKET_BROADCAST , NS3_PACKET_BROADCAST = PACKET_BROADCAST ,
PACKET_MULTICAST , NS3_PACKET_MULTICAST = PACKET_MULTICAST , PACKET_OTHERHOST , NS3_PACKET_OTHERHOST = PACKET_OTHERHOST
}
Packet types are used as they are in Linux.
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address &, const Address &, enum PacketType > PromiscReceiveCallback
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address & > ReceiveCallback
Public Member Functions
WimaxNetDevice (void)
virtual ~WimaxNetDevice (void)
virtual void AddLinkChangeCallback (Callback< void > callback)
Add link change callback function.
void Attach (Ptr< WimaxChannel > channel)
Attach device to channel.
void CreateDefaultConnections (void)
Creates the initial ranging and broadcast connections.
virtual void DoDispose (void)
Destructor implementation.
virtual bool Enqueue (Ptr< Packet > packet, const MacHeaderType &hdrType, Ptr< WimaxConnection > connection)=0
Enqueue a packet.
void ForwardDown (Ptr< PacketBurst > burst, WimaxPhy::ModulationType modulationType)
Forward a packet down the stack.
void ForwardUp (Ptr< Packet > packet, const Mac48Address &source, const Mac48Address &dest)
Forward a packet to the next layer above the device.
virtual Address GetAddress (void) const
Get address of the device.
Ptr< BandwidthManager > GetBandwidthManager (void) const
Get the bandwidth manager on the device.
virtual Address GetBroadcast (void) const
Get broadcast address.
Ptr< WimaxConnection > GetBroadcastConnection (void) const
Get the broadcast connection.
Ptr< BurstProfileManager > GetBurstProfileManager (void) const
Get the burst profile manager.
uint64_t GetChannel (uint8_t index) const
Get the channel object by index.
virtual Ptr< Channel > GetChannel (void) const
Get the channel.
Ptr< ConnectionManager > GetConnectionManager (void) const
Get the connection manager of the device.
Dcd GetCurrentDcd (void) const
Get the current DCD.
Ucd GetCurrentUcd (void) const
Get the current UCD.
virtual uint32_t GetIfIndex (void) const
Get interface index.
Ptr< WimaxConnection > GetInitialRangingConnection (void) const
Get the initial ranging connection.
Mac48Address GetMacAddress (void) const
Get the MAC address.
virtual uint16_t GetMtu (void) const
Get MTU of the device.
virtual Address GetMulticast (Ipv4Address multicastGroup) const
Make and return a MAC multicast address using the provided multicast group.
virtual Address GetMulticast (Ipv6Address addr) const
Get the MAC multicast address corresponding to the IPv6 address provided.
virtual Address GetMulticast (void) const
Get multicast address.
virtual std::string GetName (void) const
Get device name.
virtual Ptr< Node > GetNode (void) const
Get node pointer.
uint32_t GetNrFrames (void) const
Get the number of frames.
Ptr< WimaxPhy > GetPhy (void) const
Get the physical layer object.
virtual Ptr< Channel > GetPhyChannel (void) const
Get the channel (this method is redundant with GetChannel())
NetDevice::PromiscReceiveCallback GetPromiscReceiveCallback (void)
Get promiscious receive callback function.
uint16_t GetRtg (void) const
Get receive/transmit transition gap.
uint8_t GetState (void) const
Get the device state.
uint16_t GetTtg (void) const
Get transmission/receive transition gap.
virtual bool IsBridge (void) const
Return true if the net device is acting as a bridge.
virtual bool IsBroadcast (void) const
Check if broadcast enabled.
virtual bool IsLinkUp (void) const
Check if link is up.
virtual bool IsMulticast (void) const
Check if multicast enabled.
virtual bool IsPointToPoint (void) const
Check if device is a point-to-point device.
bool IsPromisc (void)
Check if device is promiscious.
virtual Address MakeMulticastAddress (Ipv4Address multicastGroup) const
Make multicast address.
virtual bool NeedsArp (void) const
Check if device needs ARP.
void NotifyPromiscTrace (Ptr< Packet > p)
Notify promiscious trace of a packet arrival.
virtual bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)
Send function.
virtual bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
Send a packet.
virtual void SetAddress (Address address)
Set address of the device.
void SetBandwidthManager (Ptr< BandwidthManager > bandwidthManager)
Set the bandwidth manager on the device.
void SetBurstProfileManager (Ptr< BurstProfileManager > burstProfileManager)
Set the burst profile manager.
void SetChannel (Ptr< WimaxChannel > wimaxChannel)
Set the channel object.
virtual void SetConnectionManager (Ptr< ConnectionManager > connectionManager)
Set the connection manager of the device.
void SetCurrentDcd (Dcd dcd)
Set the current DCD.
void SetCurrentUcd (Ucd ucd)
Set the current UCD.
virtual void SetIfIndex (const uint32_t index)
Set interface index.
virtual void SetLinkChangeCallback (Callback< void > callback)
Set link change callback function.
void SetMacAddress (Mac48Address address)
Set the MAC address.
virtual bool SetMtu (const uint16_t mtu)
Set MTU value for the device.
virtual void SetName (const std::string name)
Set device name.
virtual void SetNode (Ptr< Node > node)
Set node pointer.
void SetNrFrames (uint32_t nrFrames)
Set the number of frames.
void SetPhy (Ptr< WimaxPhy > phy)
Set the physical layer object.
virtual void SetPromiscReceiveCallback (PromiscReceiveCallback cb)
Set promiscious receive callback function.
virtual void SetReceiveCallback (NetDevice::ReceiveCallback cb)
Set receive callback function.
void SetReceiveCallback (void)
Set receive callback function.
void SetRtg (uint16_t rtg)
Set receive/transmit transition gap.
void SetState (uint8_t state)
Set the device state.
void SetTtg (uint16_t ttg)
Set transmission/receive transition gap.
virtual void Start (void)=0
Start function.
virtual void Stop (void)=0
Stop function.
virtual bool SupportsSendFrom (void) const
Check if device supports the SendFrom method.
Public Member Functions inherited from ns3::NetDevice
virtual ~NetDevice ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::NetDevice
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Public Attributes
TracedCallback< Ptr< const Packet >, const Mac48Address & > m_traceRx
TracedCallback< Ptr< const Packet >, const Mac48Address & > m_traceTx
Static Public Attributes
static uint8_t m_direction = ~0
downlink or uplink
static Time m_frameStartTime = Seconds (0)
temp, to determine the frame start time at SS side, shall actually be determined by frame start preamble
Private Member Functions
WimaxNetDevice (const WimaxNetDevice &)
copy constructor (disabled)
virtual Ptr< WimaxChannel > DoGetChannel (void) const
Get the channel.
virtual void DoReceive (Ptr< Packet > packet)=0
Receive a packet.
virtual bool DoSend (Ptr< Packet > packet, const Mac48Address &source, const Mac48Address &dest, uint16_t protocolNumber)=0
Send a packet.
void InitializeChannels (void)
Initialize channels function.
WimaxNetDevice & operator= (const WimaxNetDevice &)
assignment operator (disabled)
void Receive (Ptr< const PacketBurst > burst)
Receive a packet burst.
Private Attributes
Mac48Address m_address
MAC address.
Ptr< BandwidthManager > m_bandwidthManager
badnwidth manager
Ptr< WimaxConnection > m_broadcastConnection
broadcast connection
Ptr< BurstProfileManager > m_burstProfileManager
burst profile manager
Ptr< ConnectionManager > m_connectionManager
connection manager
Dcd m_currentDcd
DCD.
Ucd m_currentUcd
UCD.
std::vector< uint64_t > m_dlChannels
not sure if it shall be included here
NetDevice::ReceiveCallback m_forwardUp
forward up callback function
uint32_t m_ifIndex
IF index.
Ptr< WimaxConnection > m_initialRangingConnection
initial rnaging connection
Callback< void > m_linkChange
link change callback
bool m_linkUp
link up?
Ptr< Object > m_mobility
modility model
uint16_t m_mtu
MTU.
std::string m_name
service name
Ptr< Node > m_node
the node
Ptr< WimaxPhy > m_phy
the phy
NetDevice::PromiscReceiveCallback m_promiscRx
promiscious receive fcallback function
uint16_t m_rtg
length of RTG in units of PSs
uint8_t m_state
state
uint32_t m_symbolIndex
symbol index
uint16_t m_ttg
length of TTG in units of PSs
Static Private Attributes
static const uint16_t DEFAULT_MSDU_SIZE = 1400
recommended by wimax forum.
static uint32_t m_nrFrames = 0
temp, shall be in BS. defined here to allow SS to access. SS shall actually determine it from DLFP, shall be moved to BS after DLFP is implemented
static const uint16_t MAX_MSDU_SIZE = 1500
Maximum MSDU size.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Hold together all WiMAX-related objects in a NetDevice.
This class holds together ns3::WimaxPhy, ns3::WimaxConnection, ns3::ConectionManager, ns3::BurstProfileManager, and ns3::BandwidthManager.
Config Paths
ns3::WimaxNetDevice is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WimaxNetDevice"
Attributes
Mtu: The MAC-level Maximum Transmission Unit
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:1500
Initial value: 1400
Flags: construct write read
Phy: The PHY layer attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::WimaxPhy>
Initial value: 0x0
Flags: construct write read
Channel: The channel attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::WimaxChannel>
Initial value: 0x0
Flags: construct write read
RTG: receive/transmit transition gap.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:120
Initial value: 0
Flags: construct write read
TTG: transmit/receive transition gap.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:120
Initial value: 0
Flags: construct write read
ConnectionManager: The connection manager attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::ConnectionManager>
Initial value: 0x0
Flags: construct write read
BurstProfileManager: The burst profile manager attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::BurstProfileManager>
Initial value: 0x0
Flags: construct write read
BandwidthManager: The bandwidth manager attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::BandwidthManager>
Initial value: 0x0
Flags: construct write read
InitialRangingConnection: Initial ranging connection
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::WimaxConnection>
Initial value: 0x0
Flags: construct write read
BroadcastConnection: Broadcast connection
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::WimaxConnection>
Initial value: 0x0
Flags: construct write read
TraceSources
Rx: Receive trace
Callback signature: ns3::WimaxNetDevice::TxRxTracedCallback
Tx: Transmit trace
Callback signature: ns3::WimaxNetDevice::TxRxTracedCallback
Size of this type is 408 bytes (on a 64-bit architecture).
Definition at line 68 of file wimax-net-device.h.
Member Typedef Documentation
TxRxTracedCallback
typedef void(* ns3::WimaxNetDevice::TxRxTracedCallback) (Ptr< const Packet > packet, const Mac48Address &mac)
TracedCallback signature for packet and Mac48Address.
Parameters
[in] packet The packet.
[in] mac The Mac48Address.
Deprecated:
The const Mac48Address & argument is deprecated and will be changed to Mac48Address in a future release. The TracedCallback signature will then match Packet::Mac48Address and this typedef can be removed.
Definition at line 441 of file wimax-net-device.h.
Member Enumeration Documentation
Direction
enum ns3::WimaxNetDevice::Direction
Direction enumeration.
Enumerator
DIRECTION_DOWNLINK
DIRECTION_UPLINK
Definition at line 72 of file wimax-net-device.h.
RangingStatus
enum ns3::WimaxNetDevice::RangingStatus
RangingStatus enumeration.
Enumerator
RANGING_STATUS_EXPIRED
RANGING_STATUS_CONTINUE
RANGING_STATUS_ABORT
RANGING_STATUS_SUCCESS
Definition at line 79 of file wimax-net-device.h.
Constructor & Destructor Documentation
WimaxNetDevice() [1/2]
ns3::WimaxNetDevice::WimaxNetDevice (void)
Definition at line 138 of file wimax-net-device.cc.
References InitializeChannels(), m_bandwidthManager, m_burstProfileManager, m_connectionManager, m_direction, m_frameStartTime, m_nrFrames, and ns3::Seconds().
~WimaxNetDevice()
ns3::WimaxNetDevice::~WimaxNetDevice (void) virtual
Definition at line 153 of file wimax-net-device.cc.
WimaxNetDevice() [2/2]
ns3::WimaxNetDevice::WimaxNetDevice (const WimaxNetDevice &) private
copy constructor (disabled)
Member Function Documentation
AddLinkChangeCallback()
void ns3::WimaxNetDevice::AddLinkChangeCallback (Callback< void > callback) virtual
Add link change callback function.
Parameters
callback the link change callback function
Implements ns3::NetDevice.
Definition at line 643 of file wimax-net-device.cc.
References NS_FATAL_ERROR.
Attach()
void ns3::WimaxNetDevice::Attach (Ptr< WimaxChannel > channel)
Attach device to channel.
Parameters
channel channel to attach
Definition at line 357 of file wimax-net-device.cc.
References third::channel, and m_phy.
CreateDefaultConnections()
void ns3::WimaxNetDevice::CreateDefaultConnections (void)
Creates the initial ranging and broadcast connections.
Definition at line 511 of file wimax-net-device.cc.
References ns3::Cid::BROADCAST, ns3::Cid::Broadcast(), ns3::Cid::INITIAL_RANGING, ns3::Cid::InitialRanging(), m_broadcastConnection, and m_initialRangingConnection.
Referenced by ns3::BaseStationNetDevice::Start(), and ns3::SubscriberStationNetDevice::Start().
DoDispose()
void ns3::WimaxNetDevice::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Reimplemented in ns3::SubscriberStationNetDevice, and ns3::BaseStationNetDevice.
Definition at line 158 of file wimax-net-device.cc.
References ns3::Object::DoDispose(), m_bandwidthManager, m_broadcastConnection, m_burstProfileManager, m_connectionManager, m_initialRangingConnection, m_node, and m_phy.
Referenced by ns3::BaseStationNetDevice::DoDispose(), and ns3::SubscriberStationNetDevice::DoDispose().
DoGetChannel()
Ptr< WimaxChannel > ns3::WimaxNetDevice::DoGetChannel (void) const private virtual
Get the channel.
Returns
the wimax channel
Definition at line 532 of file wimax-net-device.cc.
References m_phy.
Referenced by GetChannel(), and GetPhyChannel().
DoReceive()
virtual void ns3::WimaxNetDevice::DoReceive (Ptr< Packet > packet) private pure virtual
Receive a packet.
Parameters
packet the packet received
Implemented in ns3::SubscriberStationNetDevice, and ns3::BaseStationNetDevice.
Referenced by Receive().
DoSend()
virtual bool ns3::WimaxNetDevice::DoSend (Ptr< Packet > packet, const Mac48Address & source, const Mac48Address & dest, uint16_t protocolNumber) private pure virtual
Send a packet.
Parameters
packet the packet
source the source MAC address
dest the destination MAC address
protocolNumber the protocol number
Returns
true if successful
Implemented in ns3::SubscriberStationNetDevice, and ns3::BaseStationNetDevice.
Referenced by Send(), and SendFrom().
Enqueue()
virtual bool ns3::WimaxNetDevice::Enqueue (Ptr< Packet > packet, const MacHeaderType & hdrType, Ptr< WimaxConnection > connection) pure virtual
Enqueue a packet.
Parameters
packet the packet
hdrType the header type
connection the wimax connection
Returns
true if successful
Implemented in ns3::SubscriberStationNetDevice, and ns3::BaseStationNetDevice.
ForwardDown()
void ns3::WimaxNetDevice::ForwardDown (Ptr< PacketBurst > burst, WimaxPhy::ModulationType modulationType)
Forward a packet down the stack.
Parameters
burst the packet burst
modulationType the modulation type
Definition at line 583 of file wimax-net-device.cc.
References m_direction, and m_phy.
Referenced by ns3::SubscriberStationNetDevice::SendBurst(), and ns3::BaseStationNetDevice::SendBursts().
ForwardUp()
void ns3::WimaxNetDevice::ForwardUp (Ptr< Packet > packet, const Mac48Address & source, const Mac48Address & dest)
Forward a packet to the next layer above the device.
Parameters
packet the packet
source the source MAC address
dest the destination MAC address
Definition at line 348 of file wimax-net-device.cc.
References ns3::LlcSnapHeader::GetType(), m_forwardUp, m_traceRx, and ns3::Packet::RemoveHeader().
Referenced by ns3::BaseStationNetDevice::DoReceive(), and ns3::SubscriberStationNetDevice::DoReceive().
GetAddress()
Address ns3::WimaxNetDevice::GetAddress (void) const virtual
Get address of the device.
Returns
the address
Implements ns3::NetDevice.
Definition at line 415 of file wimax-net-device.cc.
References m_address.
Referenced by Send().
GetBandwidthManager()
Ptr< BandwidthManager > ns3::WimaxNetDevice::GetBandwidthManager (void) const
Get the bandwidth manager on the device.
Returns
the bandwidth manager installed on the device
Definition at line 499 of file wimax-net-device.cc.
References m_bandwidthManager.
Referenced by ns3::BaseStationNetDevice::DoReceive(), GetTypeId(), ns3::SubscriberStationNetDevice::ProcessUlMap(), and ns3::BaseStationNetDevice::Start().
GetBroadcast()
Address ns3::WimaxNetDevice::GetBroadcast (void) const virtual
Get broadcast address.
Returns
the address
Implements ns3::NetDevice.
Definition at line 274 of file wimax-net-device.cc.
References ns3::Mac48Address::GetBroadcast().
GetBroadcastConnection()
Ptr< WimaxConnection > ns3::WimaxNetDevice::GetBroadcastConnection (void) const
Get the broadcast connection.
Returns
the broadcast connection
Definition at line 445 of file wimax-net-device.cc.
References m_broadcastConnection.
Referenced by ns3::BaseStationNetDevice::CreateDescriptorMessages(), ns3::BaseStationNetDevice::CreateMapMessages(), ns3::SubscriberStationNetDevice::DoReceive(), ns3::BaseStationNetDevice::GetConnection(), ns3::SubscriberStationNetDevice::ProcessUlMap(), and ns3::BaseStationNetDevice::SendBursts().
GetBurstProfileManager()
Ptr< BurstProfileManager > ns3::WimaxNetDevice::GetBurstProfileManager (void) const
Get the burst profile manager.
Returns
the burst profile manager currently installed in the device
Definition at line 487 of file wimax-net-device.cc.
References m_burstProfileManager.
Referenced by GetTypeId(), ns3::SubscriberStationNetDevice::SendBurst(), ns3::BaseStationNetDevice::SendBursts(), ns3::BaseStationNetDevice::SetDlBurstProfiles(), and ns3::BaseStationNetDevice::SetUlBurstProfiles().
GetChannel() [1/2]
uint64_t ns3::WimaxNetDevice::GetChannel (uint8_t index) const
Get the channel object by index.
Parameters
index the channel index
Returns
the channel being used.
Definition at line 385 of file wimax-net-device.cc.
References m_dlChannels.
GetChannel() [2/2]
Ptr< Channel > ns3::WimaxNetDevice::GetChannel (void) const virtual
Get the channel.
Returns
the channel
Implements ns3::NetDevice.
Definition at line 225 of file wimax-net-device.cc.
References DoGetChannel().
GetConnectionManager()
Ptr< ConnectionManager > ns3::WimaxNetDevice::GetConnectionManager (void) const
Get the connection manager of the device.
Returns
the connection manager of the device
Definition at line 475 of file wimax-net-device.cc.
References m_connectionManager.
Referenced by ns3::BaseStationNetDevice::DoReceive(), ns3::SubscriberStationNetDevice::DoReceive(), ns3::BaseStationNetDevice::GetConnection(), GetTypeId(), and ns3::BaseStationNetDevice::Start().
GetCurrentDcd()
Dcd ns3::WimaxNetDevice::GetCurrentDcd (void) const
Get the current DCD.
Returns
the DCD
Definition at line 457 of file wimax-net-device.cc.
References m_currentDcd.
Referenced by ns3::SubscriberStationNetDevice::ProcessDcd().
GetCurrentUcd()
Ucd ns3::WimaxNetDevice::GetCurrentUcd (void) const
Get the current UCD.
Returns
the UCD
Definition at line 469 of file wimax-net-device.cc.
References m_currentUcd.
Referenced by ns3::SubscriberStationNetDevice::ProcessUcd(), and ns3::SubscriberStationNetDevice::ProcessUlMap().
GetIfIndex()
uint32_t ns3::WimaxNetDevice::GetIfIndex (void) const virtual
Get interface index.
Returns
the interface index
Implements ns3::NetDevice.
Definition at line 219 of file wimax-net-device.cc.
References m_ifIndex.
Referenced by ns3::SubscriberStationNetDevice::SetBasicConnection(), and ns3::SubscriberStationNetDevice::SetPrimaryConnection().
GetInitialRangingConnection()
Ptr< WimaxConnection > ns3::WimaxNetDevice::GetInitialRangingConnection (void) const
Get the initial ranging connection.
Returns
the initial ranging connection
Definition at line 439 of file wimax-net-device.cc.
References m_initialRangingConnection.
Referenced by ns3::SubscriberStationNetDevice::DoReceive(), ns3::BaseStationNetDevice::GetConnection(), and ns3::BaseStationNetDevice::SendBursts().
GetMacAddress()
Mac48Address ns3::WimaxNetDevice::GetMacAddress (void) const
Get the MAC address.
Returns
the mac address of the net device
Definition at line 421 of file wimax-net-device.cc.
References m_address.
Referenced by ns3::BaseStationNetDevice::CreateDcd(), ns3::BaseStationNetDevice::CreateDlMap(), ns3::SubscriberStationNetDevice::DoReceive(), ns3::SubscriberStationNetDevice::DoSend(), Receive(), and ns3::SubscriberStationNetDevice::SendBurst().
GetMtu()
uint16_t ns3::WimaxNetDevice::GetMtu (void) const virtual
Get MTU of the device.
Returns
the MTU
Implements ns3::NetDevice.
Definition at line 248 of file wimax-net-device.cc.
References m_mtu.
Referenced by GetTypeId().
GetMulticast() [1/3]
Address ns3::WimaxNetDevice::GetMulticast (Ipv4Address multicastGroup) const virtual
Make and return a MAC multicast address using the provided multicast group.
RFC 1112 says that an Ipv4 host group address is mapped to an Ethernet multicast address by placing the low-order 23-bits of the IP address into the low-order 23 bits of the Ethernet multicast address 01-00-5E-00-00-00 (hex). Similar RFCs exist for Ipv6 and Eui64 mappings. This method performs the multicast address creation function appropriate to the underlying MAC address of the device. This MAC address is encapsulated in an abstract Address to avoid dependencies on the exact MAC address format.
In the case of net devices that do not support multicast, clients are expected to test NetDevice::IsMulticast and avoid attempting to map multicast packets. Subclasses of NetDevice that do support multicasting are expected to override this method and provide an implementation appropriate to the particular device.
Parameters
multicastGroup The IP address for the multicast group destination of the packet.
Returns
The MAC multicast Address used to send packets to the provided multicast group.
Warning
Calling this method is invalid if IsMulticast returns not true.
See also
IsMulticast()
Implements ns3::NetDevice.
Definition at line 617 of file wimax-net-device.cc.
References ns3::Mac48Address::GetMulticast(), NS_LOG_FUNCTION, and NS_LOG_LOGIC.
GetMulticast() [2/3]
Address ns3::WimaxNetDevice::GetMulticast (Ipv6Address addr) const virtual
Get the MAC multicast address corresponding to the IPv6 address provided.
Parameters
addr IPv6 address
Returns
the MAC multicast address
Warning
Calling this method is invalid if IsMulticast returns not true.
Implements ns3::NetDevice.
Definition at line 634 of file wimax-net-device.cc.
References ns3::Mac48Address::GetMulticast(), and NS_LOG_LOGIC.
GetMulticast() [3/3]
Address ns3::WimaxNetDevice::GetMulticast (void) const virtual
Get multicast address.
Returns
the multicast address
Definition at line 286 of file wimax-net-device.cc.
Referenced by MakeMulticastAddress().
GetName()
std::string ns3::WimaxNetDevice::GetName (void) const virtual
Get device name.
Returns
the device name
Definition at line 207 of file wimax-net-device.cc.
References m_name.
GetNode()
Ptr< Node > ns3::WimaxNetDevice::GetNode (void) const virtual
Get node pointer.
Returns
the node pointer
Implements ns3::NetDevice.
Definition at line 324 of file wimax-net-device.cc.
References m_node.
Referenced by ns3::SubscriberStationNetDevice::SetBasicConnection(), and ns3::SubscriberStationNetDevice::SetPrimaryConnection().
GetNrFrames()
uint32_t ns3::WimaxNetDevice::GetNrFrames (void) const
Get the number of frames.
Returns
the number of frames.
Definition at line 396 of file wimax-net-device.cc.
References m_nrFrames.
Referenced by ns3::BaseStationNetDevice::CreateDcd(), ns3::BaseStationNetDevice::StartDlSubFrame(), and ns3::BaseStationNetDevice::StartFrame().
GetPhy()
Ptr< WimaxPhy > ns3::WimaxNetDevice::GetPhy (void) const
Get the physical layer object.
Returns
a pointer to the physical layer object
Definition at line 369 of file wimax-net-device.cc.
References m_phy.
Referenced by ns3::BaseStationNetDevice::CreateDcd(), ns3::BaseStationNetDevice::CreateUcd(), ns3::SubscriberStationNetDevice::GetTimeToAllocation(), GetTypeId(), ns3::SubscriberStationNetDevice::ProcessDcd(), ns3::SubscriberStationNetDevice::ProcessUlMap(), ns3::BaseStationNetDevice::SendBursts(), ns3::BaseStationNetDevice::Start(), ns3::SubscriberStationNetDevice::Start(), and ns3::BaseStationNetDevice::StartFrame().
GetPhyChannel()
Ptr< Channel > ns3::WimaxNetDevice::GetPhyChannel (void) const virtual
Get the channel (this method is redundant with GetChannel())
Returns
the channel used by the phy layer
Definition at line 231 of file wimax-net-device.cc.
References DoGetChannel().
Referenced by GetTypeId().
GetPromiscReceiveCallback()
NetDevice::PromiscReceiveCallback ns3::WimaxNetDevice::GetPromiscReceiveCallback (void)
Get promiscious receive callback function.
Returns
the promiscious mode callback
GetRtg()
uint16_t ns3::WimaxNetDevice::GetRtg (void) const
Get receive/transmit transition gap.
Returns
receive/transmit transition gap
Definition at line 195 of file wimax-net-device.cc.
References m_rtg.
Referenced by ns3::BaseStationNetDevice::CreateDcd(), ns3::BaseStationNetDevice::EndUlSubFrame(), GetTypeId(), ns3::BaseStationNetDevice::Start(), and ns3::BaseStationNetDevice::StartFrame().
GetState()
uint8_t ns3::WimaxNetDevice::GetState (void) const
Get the device state.
Returns
the state
Definition at line 433 of file wimax-net-device.cc.
References m_state.
Referenced by ns3::SubscriberStationNetDevice::DoReceive(), ns3::SubscriberStationNetDevice::IsRegistered(), ns3::SubscriberStationNetDevice::ProcessUlMap(), and ns3::SubscriberStationNetDevice::SetTimer().
GetTtg()
uint16_t ns3::WimaxNetDevice::GetTtg (void) const
Get transmission/receive transition gap.
Returns
transmit/receive transition gap
Definition at line 183 of file wimax-net-device.cc.
References m_ttg.
Referenced by ns3::BaseStationNetDevice::CreateDcd(), ns3::BaseStationNetDevice::EndDlSubFrame(), GetTypeId(), ns3::BaseStationNetDevice::Start(), and ns3::BaseStationNetDevice::StartFrame().
GetTypeId()
TypeId ns3::WimaxNetDevice::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 52 of file wimax-net-device.cc.
References DEFAULT_MSDU_SIZE, GetBandwidthManager(), GetBurstProfileManager(), GetConnectionManager(), GetMtu(), GetPhy(), GetPhyChannel(), GetRtg(), GetTtg(), m_broadcastConnection, m_initialRangingConnection, m_traceRx, m_traceTx, ns3::MakePointerAccessor(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), MAX_MSDU_SIZE, SetBandwidthManager(), SetBurstProfileManager(), SetChannel(), SetConnectionManager(), SetMtu(), ns3::TypeId::SetParent(), SetPhy(), SetRtg(), and SetTtg().
InitializeChannels()
void ns3::WimaxNetDevice::InitializeChannels (void) private
Initialize channels function.
Definition at line 591 of file wimax-net-device.cc.
References m_dlChannels.
Referenced by WimaxNetDevice().
IsBridge()
bool ns3::WimaxNetDevice::IsBridge (void) const virtual
Return true if the net device is acting as a bridge.
Returns
value of m_isBridge flag
Implements ns3::NetDevice.
Definition at line 610 of file wimax-net-device.cc.
References NS_LOG_FUNCTION_NOARGS.
IsBroadcast()
bool ns3::WimaxNetDevice::IsBroadcast (void) const virtual
Check if broadcast enabled.
Returns
true if broadcast
Implements ns3::NetDevice.
Definition at line 268 of file wimax-net-device.cc.
IsLinkUp()
bool ns3::WimaxNetDevice::IsLinkUp (void) const virtual
Check if link is up.
Returns
true if the link is up
Implements ns3::NetDevice.
Definition at line 254 of file wimax-net-device.cc.
References m_linkUp, and m_phy.
IsMulticast()
bool ns3::WimaxNetDevice::IsMulticast (void) const virtual
Check if multicast enabled.
Returns
true if multicast
Implements ns3::NetDevice.
Definition at line 280 of file wimax-net-device.cc.
IsPointToPoint()
bool ns3::WimaxNetDevice::IsPointToPoint (void) const virtual
Check if device is a point-to-point device.
Returns
true if point to point
Implements ns3::NetDevice.
Definition at line 298 of file wimax-net-device.cc.
IsPromisc()
bool ns3::WimaxNetDevice::IsPromisc (void)
Check if device is promiscious.
Returns
true if promiscious
Definition at line 565 of file wimax-net-device.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), and m_promiscRx.
Referenced by ns3::SubscriberStationNetDevice::DoReceive().
MakeMulticastAddress()
Address ns3::WimaxNetDevice::MakeMulticastAddress (Ipv4Address multicastGroup) const virtual
Make multicast address.
Parameters
multicastGroup the IPv4 address
Returns
the multicast address
Definition at line 292 of file wimax-net-device.cc.
References GetMulticast().
NeedsArp()
bool ns3::WimaxNetDevice::NeedsArp (void) const virtual
Check if device needs ARP.
Returns
true if ARP required
Implements ns3::NetDevice.
Definition at line 330 of file wimax-net-device.cc.
NotifyPromiscTrace()
void ns3::WimaxNetDevice::NotifyPromiscTrace (Ptr< Packet > p)
Notify promiscious trace of a packet arrival.
Parameters
p the packet
Definition at line 571 of file wimax-net-device.cc.
Referenced by ns3::SubscriberStationNetDevice::DoReceive().
operator=()
WimaxNetDevice& ns3::WimaxNetDevice::operator= (const WimaxNetDevice &) private
assignment operator (disabled)
Returns
the wimax net device
Receive()
void ns3::WimaxNetDevice::Receive (Ptr< const PacketBurst > burst) private
Receive a packet burst.
Parameters
burst the packet burst
Definition at line 518 of file wimax-net-device.cc.
References DoReceive(), GetMacAddress(), list, and NS_LOG_DEBUG.
Referenced by SetReceiveCallback().
Send()
bool ns3::WimaxNetDevice::Send (Ptr< Packet > packet, const Address & dest, uint16_t protocolNumber) virtual
Send function.
Parameters
packet the packet
dest the destination address
protocolNumber the protocol number
Returns
true if successful
Implements ns3::NetDevice.
Definition at line 304 of file wimax-net-device.cc.
References ns3::Packet::AddHeader(), ns3::Mac48Address::ConvertFrom(), DoSend(), GetAddress(), m_traceTx, and ns3::LlcSnapHeader::SetType().
SendFrom()
bool ns3::WimaxNetDevice::SendFrom (Ptr< Packet > packet, const Address & source, const Address & dest, uint16_t protocolNumber) virtual
Send a packet.
Parameters
packet the packet
source the source address
dest the destination address
protocolNumber the protocol number
Returns
true if successful
Implements ns3::NetDevice.
Definition at line 544 of file wimax-net-device.cc.
References ns3::Packet::AddHeader(), ns3::Mac48Address::ConvertFrom(), DoSend(), m_traceTx, and ns3::LlcSnapHeader::SetType().
SetAddress()
void ns3::WimaxNetDevice::SetAddress (Address address) virtual
Set address of the device.
Parameters
address the address
Implements ns3::NetDevice.
Definition at line 403 of file wimax-net-device.cc.
References first::address, ns3::Mac48Address::ConvertFrom(), and m_address.
SetBandwidthManager()
void ns3::WimaxNetDevice::SetBandwidthManager (Ptr< BandwidthManager > bandwidthManager)
Set the bandwidth manager on the device.
Parameters
bandwidthManager the bandwidth manager to be installed on the device
Definition at line 505 of file wimax-net-device.cc.
References m_bandwidthManager.
Referenced by GetTypeId().
SetBurstProfileManager()
void ns3::WimaxNetDevice::SetBurstProfileManager (Ptr< BurstProfileManager > burstProfileManager)
Set the burst profile manager.
Parameters
burstProfileManager the burst profile manager to be installed on the device
Definition at line 493 of file wimax-net-device.cc.
References m_burstProfileManager.
Referenced by GetTypeId().
SetChannel()
void ns3::WimaxNetDevice::SetChannel (Ptr< WimaxChannel > wimaxChannel)
Set the channel object.
Parameters
wimaxChannel the channel to be used
Definition at line 375 of file wimax-net-device.cc.
References third::channel, and m_phy.
Referenced by GetTypeId().
SetConnectionManager()
void ns3::WimaxNetDevice::SetConnectionManager (Ptr< ConnectionManager > connectionManager) virtual
Set the connection manager of the device.
Parameters
connectionManager the commection manager to be installed in the device
Definition at line 481 of file wimax-net-device.cc.
References m_connectionManager.
Referenced by GetTypeId().
SetCurrentDcd()
void ns3::WimaxNetDevice::SetCurrentDcd (Dcd dcd)
Set the current DCD.
Parameters
dcd the DCD
Definition at line 451 of file wimax-net-device.cc.
References m_currentDcd.
Referenced by ns3::BaseStationNetDevice::CreateDcd(), and ns3::SubscriberStationNetDevice::ProcessDcd().
SetCurrentUcd()
void ns3::WimaxNetDevice::SetCurrentUcd (Ucd ucd)
Set the current UCD.
Parameters
ucd the UCD
Definition at line 463 of file wimax-net-device.cc.
References m_currentUcd.
Referenced by ns3::BaseStationNetDevice::CreateUcd(), and ns3::SubscriberStationNetDevice::ProcessUcd().
SetIfIndex()
void ns3::WimaxNetDevice::SetIfIndex (const uint32_t index) virtual
Set interface index.
Parameters
index the index
Implements ns3::NetDevice.
Definition at line 213 of file wimax-net-device.cc.
References m_ifIndex.
SetLinkChangeCallback()
void ns3::WimaxNetDevice::SetLinkChangeCallback (Callback< void > callback) virtual
Set link change callback function.
Parameters
callback the callback function
Definition at line 262 of file wimax-net-device.cc.
References m_linkChange.
SetMacAddress()
void ns3::WimaxNetDevice::SetMacAddress (Mac48Address address)
Set the MAC address.
Parameters
address the mac address of the net device
Definition at line 409 of file wimax-net-device.cc.
References first::address, and m_address.
SetMtu()
bool ns3::WimaxNetDevice::SetMtu (const uint16_t mtu) virtual
Set MTU value for the device.
Parameters
mtu the MTU
Returns
true if successful
Implements ns3::NetDevice.
Definition at line 237 of file wimax-net-device.cc.
References m_mtu, and MAX_MSDU_SIZE.
Referenced by GetTypeId().
SetName()
void ns3::WimaxNetDevice::SetName (const std::string name) virtual
Set device name.
Parameters
name the device name
Definition at line 201 of file wimax-net-device.cc.
References m_name.
SetNode()
void ns3::WimaxNetDevice::SetNode (Ptr< Node > node) virtual
Set node pointer.
Parameters
node the node pointer
Implements ns3::NetDevice.
Definition at line 318 of file wimax-net-device.cc.
References m_node.
Referenced by ns3::BaseStationNetDevice::BaseStationNetDevice(), and ns3::SubscriberStationNetDevice::SubscriberStationNetDevice().
SetNrFrames()
void ns3::WimaxNetDevice::SetNrFrames (uint32_t nrFrames)
Set the number of frames.
Parameters
nrFrames the number of frames
Definition at line 391 of file wimax-net-device.cc.
References m_nrFrames.
Referenced by ns3::BaseStationNetDevice::StartDlSubFrame().
SetPhy()
void ns3::WimaxNetDevice::SetPhy (Ptr< WimaxPhy > phy)
Set the physical layer object.
Parameters
phy the phy layer object to use
Definition at line 363 of file wimax-net-device.cc.
References m_phy, and third::phy.
Referenced by ns3::BaseStationNetDevice::BaseStationNetDevice(), ns3::SubscriberStationNetDevice::SubscriberStationNetDevice(), and GetTypeId().
SetPromiscReceiveCallback()
void ns3::WimaxNetDevice::SetPromiscReceiveCallback (PromiscReceiveCallback cb) virtual
Set promiscious receive callback function.
Parameters
cb the promiscious mode callback
Implements ns3::NetDevice.
Definition at line 559 of file wimax-net-device.cc.
References m_promiscRx.
SetReceiveCallback() [1/2]
void ns3::WimaxNetDevice::SetReceiveCallback (NetDevice::ReceiveCallback cb) virtual
Set receive callback function.
Parameters
cb the receive callback function
Implements ns3::NetDevice.
Definition at line 342 of file wimax-net-device.cc.
References m_forwardUp.
SetReceiveCallback() [2/2]
void ns3::WimaxNetDevice::SetReceiveCallback (void)
Set receive callback function.
Definition at line 538 of file wimax-net-device.cc.
References m_phy, ns3::MakeCallback(), and Receive().
Referenced by ns3::BaseStationNetDevice::Start(), and ns3::SubscriberStationNetDevice::Start().
SetRtg()
void ns3::WimaxNetDevice::SetRtg (uint16_t rtg)
Set receive/transmit transition gap.
Parameters
rtg receive/transmit transition gap
Definition at line 189 of file wimax-net-device.cc.
References m_rtg.
Referenced by GetTypeId(), and ns3::BaseStationNetDevice::Start().
SetState()
void ns3::WimaxNetDevice::SetState (uint8_t state)
Set the device state.
Parameters
state the state
Definition at line 427 of file wimax-net-device.cc.
References m_state.
Referenced by ns3::SubscriberStationNetDevice::DoReceive(), ns3::BaseStationNetDevice::EndDlSubFrame(), ns3::BaseStationNetDevice::EndUlSubFrame(), ns3::BaseStationNetDevice::StartDlSubFrame(), ns3::BaseStationNetDevice::StartUlSubFrame(), and ns3::SubscriberStationNetDevice::Stop().
SetTtg()
void ns3::WimaxNetDevice::SetTtg (uint16_t ttg)
Set transmission/receive transition gap.
Parameters
ttg transmit/receive transition gap
Definition at line 177 of file wimax-net-device.cc.
References m_ttg.
Referenced by GetTypeId(), and ns3::BaseStationNetDevice::Start().
Start()
virtual void ns3::WimaxNetDevice::Start (void) pure virtual
Start function.
Implemented in ns3::SubscriberStationNetDevice, and ns3::BaseStationNetDevice.
Stop()
virtual void ns3::WimaxNetDevice::Stop (void) pure virtual
Stop function.
Implemented in ns3::SubscriberStationNetDevice, and ns3::BaseStationNetDevice.
SupportsSendFrom()
bool ns3::WimaxNetDevice::SupportsSendFrom (void) const virtual
Check if device supports the SendFrom method.
Returns
true if SendFrom is supported
Implements ns3::NetDevice.
Definition at line 577 of file wimax-net-device.cc.
Member Data Documentation
DEFAULT_MSDU_SIZE
const uint16_t ns3::WimaxNetDevice::DEFAULT_MSDU_SIZE = 1400 static private
recommended by wimax forum.
Definition at line 488 of file wimax-net-device.h.
Referenced by GetTypeId().
m_address
Mac48Address ns3::WimaxNetDevice::m_address private
MAC address.
Definition at line 537 of file wimax-net-device.h.
Referenced by GetAddress(), GetMacAddress(), SetAddress(), and SetMacAddress().
m_bandwidthManager
Ptr<BandwidthManager> ns3::WimaxNetDevice::m_bandwidthManager private
badnwidth manager
Definition at line 554 of file wimax-net-device.h.
Referenced by WimaxNetDevice(), DoDispose(), GetBandwidthManager(), and SetBandwidthManager().
m_broadcastConnection
Ptr<WimaxConnection> ns3::WimaxNetDevice::m_broadcastConnection private
broadcast connection
Definition at line 550 of file wimax-net-device.h.
Referenced by CreateDefaultConnections(), DoDispose(), GetBroadcastConnection(), and GetTypeId().
m_burstProfileManager
Ptr<BurstProfileManager> ns3::WimaxNetDevice::m_burstProfileManager private
burst profile manager
Definition at line 553 of file wimax-net-device.h.
Referenced by WimaxNetDevice(), DoDispose(), GetBurstProfileManager(), and SetBurstProfileManager().
m_connectionManager
Ptr<ConnectionManager> ns3::WimaxNetDevice::m_connectionManager private
connection manager
Definition at line 552 of file wimax-net-device.h.
Referenced by WimaxNetDevice(), DoDispose(), GetConnectionManager(), and SetConnectionManager().
m_currentDcd
Dcd ns3::WimaxNetDevice::m_currentDcd private
DCD.
Definition at line 546 of file wimax-net-device.h.
Referenced by GetCurrentDcd(), and SetCurrentDcd().
m_currentUcd
Ucd ns3::WimaxNetDevice::m_currentUcd private
UCD.
Definition at line 547 of file wimax-net-device.h.
Referenced by GetCurrentUcd(), and SetCurrentUcd().
m_direction
uint8_t ns3::WimaxNetDevice::m_direction = ~0 static
downlink or uplink
Definition at line 277 of file wimax-net-device.h.
Referenced by WimaxNetDevice(), ForwardDown(), ns3::BaseStationNetDevice::StartDlSubFrame(), and ns3::BaseStationNetDevice::StartUlSubFrame().
m_dlChannels
std::vector<uint64_t> ns3::WimaxNetDevice::m_dlChannels private
not sure if it shall be included here
Definition at line 535 of file wimax-net-device.h.
Referenced by GetChannel(), and InitializeChannels().
m_forwardUp
NetDevice::ReceiveCallback ns3::WimaxNetDevice::m_forwardUp private
forward up callback function
Definition at line 522 of file wimax-net-device.h.
Referenced by ForwardUp(), and SetReceiveCallback().
m_frameStartTime
Time ns3::WimaxNetDevice::m_frameStartTime = Seconds (0) static
temp, to determine the frame start time at SS side, shall actually be determined by frame start preamble
Definition at line 279 of file wimax-net-device.h.
Referenced by WimaxNetDevice(), ns3::SubscriberStationNetDevice::GetTimeToAllocation(), ns3::BaseStationNetDevice::StartDlSubFrame(), and ns3::BaseStationNetDevice::StartFrame().
m_ifIndex
uint32_t ns3::WimaxNetDevice::m_ifIndex private
IF index.
Definition at line 525 of file wimax-net-device.h.
Referenced by GetIfIndex(), and SetIfIndex().
m_initialRangingConnection
Ptr<WimaxConnection> ns3::WimaxNetDevice::m_initialRangingConnection private
initial rnaging connection
Definition at line 549 of file wimax-net-device.h.
Referenced by CreateDefaultConnections(), DoDispose(), GetInitialRangingConnection(), and GetTypeId().
m_linkChange
Callback<void> ns3::WimaxNetDevice::m_linkChange private
link change callback
Definition at line 528 of file wimax-net-device.h.
Referenced by SetLinkChangeCallback().
m_linkUp
bool ns3::WimaxNetDevice::m_linkUp private
link up?
Definition at line 527 of file wimax-net-device.h.
Referenced by IsLinkUp().
m_mobility
Ptr<Object> ns3::WimaxNetDevice::m_mobility private
modility model
Definition at line 556 of file wimax-net-device.h.
m_mtu
uint16_t ns3::WimaxNetDevice::m_mtu mutable private
MTU.
Definition at line 529 of file wimax-net-device.h.
Referenced by GetMtu(), and SetMtu().
m_name
std::string ns3::WimaxNetDevice::m_name private
service name
Definition at line 526 of file wimax-net-device.h.
Referenced by GetName(), and SetName().
m_node
Ptr<Node> ns3::WimaxNetDevice::m_node private
the node
Definition at line 520 of file wimax-net-device.h.
Referenced by DoDispose(), GetNode(), and SetNode().
m_nrFrames
uint32_t ns3::WimaxNetDevice::m_nrFrames = 0 static private
temp, shall be in BS. defined here to allow SS to access. SS shall actually determine it from DLFP, shall be moved to BS after DLFP is implemented
Definition at line 532 of file wimax-net-device.h.
Referenced by WimaxNetDevice(), GetNrFrames(), and SetNrFrames().
m_phy
Ptr<WimaxPhy> ns3::WimaxNetDevice::m_phy private
the phy
Definition at line 521 of file wimax-net-device.h.
Referenced by Attach(), DoDispose(), DoGetChannel(), ForwardDown(), GetPhy(), IsLinkUp(), SetChannel(), SetPhy(), and SetReceiveCallback().
m_promiscRx
NetDevice::PromiscReceiveCallback ns3::WimaxNetDevice::m_promiscRx private
promiscious receive fcallback function
Definition at line 523 of file wimax-net-device.h.
Referenced by IsPromisc(), and SetPromiscReceiveCallback().
m_rtg
uint16_t ns3::WimaxNetDevice::m_rtg private
length of RTG in units of PSs
Definition at line 544 of file wimax-net-device.h.
Referenced by GetRtg(), and SetRtg().
m_state
uint8_t ns3::WimaxNetDevice::m_state private
state
Definition at line 538 of file wimax-net-device.h.
Referenced by GetState(), and SetState().
m_symbolIndex
uint32_t ns3::WimaxNetDevice::m_symbolIndex private
symbol index
Definition at line 539 of file wimax-net-device.h.
m_traceRx
TracedCallback<Ptr<const Packet>, const Mac48Address &> ns3::WimaxNetDevice::m_traceRx
Deprecated:
The const Mac48Address & argument is deprecated and will be changed to Mac48Address in a future release.
The TracedCallback signature will then match Packet::Mac48Address and this typedef can be removed.
Todo:
This member variable should be private.
Definition at line 450 of file wimax-net-device.h.
Referenced by ForwardUp(), and GetTypeId().
m_traceTx
TracedCallback<Ptr<const Packet>, const Mac48Address &> ns3::WimaxNetDevice::m_traceTx
Deprecated:
The const Mac48Address & argument is deprecated and will be changed to Mac48Address in a future release.
The TracedCallback signature will then match Packet::Mac48Address and this typedef can be removed.
Todo:
This member variable should be private.
Definition at line 458 of file wimax-net-device.h.
Referenced by GetTypeId(), Send(), and SendFrom().
m_ttg
uint16_t ns3::WimaxNetDevice::m_ttg private
length of TTG in units of PSs
Definition at line 542 of file wimax-net-device.h.
Referenced by GetTtg(), and SetTtg().
MAX_MSDU_SIZE
const uint16_t ns3::WimaxNetDevice::MAX_MSDU_SIZE = 1500 static private
Maximum MSDU size.
Definition at line 486 of file wimax-net-device.h.
Referenced by GetTypeId(), and SetMtu().
The documentation for this class was generated from the following files:
src/wimax/model/wimax-net-device.h
src/wimax/model/wimax-net-device.cc