ns-3: ns3::LteUeRrcProtocolIdeal Class Reference
ns3::LteUeRrcProtocolIdeal Class Reference
LTE Models
Models the transmission of RRC messages from the UE to the eNB in an ideal fashion, without errors and without consuming any radio resources.
#include "lte-rrc-protocol-ideal.h"
Public Member Functions
LteUeRrcProtocolIdeal ()
virtual ~LteUeRrcProtocolIdeal ()
virtual void DoDispose (void)
Destructor implementation.
LteUeRrcSapUser * GetLteUeRrcSapUser ()
Get LTE UE RRC SAP user function.
void SetLteUeRrcSapProvider (LteUeRrcSapProvider *p)
Set LTE UE RRC SAP provider function.
void SetUeRrc (Ptr< LteUeRrc > rrc)
Set LTE UE RRC function.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void DoSendIdealUeContextRemoveRequest (uint16_t rnti)
Send Ideal UE context remove request function.
void DoSendMeasurementReport (LteRrcSap::MeasurementReport msg)
Send measurement report function.
void DoSendRrcConnectionReconfigurationCompleted (LteRrcSap::RrcConnectionReconfigurationCompleted msg)
Send RRC connection reconfiguration completed function.
void DoSendRrcConnectionReestablishmentComplete (LteRrcSap::RrcConnectionReestablishmentComplete msg)
Send RRC connection reestablishment complete function.
void DoSendRrcConnectionReestablishmentRequest (LteRrcSap::RrcConnectionReestablishmentRequest msg)
Send RRC connection reestablishment request function.
void DoSendRrcConnectionRequest (LteRrcSap::RrcConnectionRequest msg)
Send RRC connection request function.
void DoSendRrcConnectionSetupCompleted (LteRrcSap::RrcConnectionSetupCompleted msg)
Send RRC connection setup completed function.
void DoSetup (LteUeRrcSapUser::SetupParameters params)
Setup function.
void SetEnbRrcSapProvider ()
Set ENB RRC SAP provider.
Private Attributes
LteEnbRrcSapProvider * m_enbRrcSapProvider
the ENB RRC SAP provider
uint16_t m_rnti
the RNTI
Ptr< LteUeRrc > m_rrc
the RRC
LteUeRrcSapProvider * m_ueRrcSapProvider
the UE RRC SAP provider
LteUeRrcSapUser * m_ueRrcSapUser
the RRC SAP user
Friends
class MemberLteUeRrcSapUser< LteUeRrcProtocolIdeal >
allow MemberLteUeRrcSapUser<LteUeRrcProtocolIdeal> class friend access
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Models the transmission of RRC messages from the UE to the eNB in an ideal fashion, without errors and without consuming any radio resources.
Introspection did not find any typical Config paths.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 72 bytes (on a 64-bit architecture).
Definition at line 48 of file lte-rrc-protocol-ideal.h.
Constructor & Destructor Documentation
LteUeRrcProtocolIdeal()
ns3::LteUeRrcProtocolIdeal::LteUeRrcProtocolIdeal ()
Definition at line 48 of file lte-rrc-protocol-ideal.cc.
References m_ueRrcSapUser, and MemberLteUeRrcSapUser< LteUeRrcProtocolIdeal >.
~LteUeRrcProtocolIdeal()
ns3::LteUeRrcProtocolIdeal::~LteUeRrcProtocolIdeal () virtual
Definition at line 55 of file lte-rrc-protocol-ideal.cc.
Member Function Documentation
DoDispose()
void ns3::LteUeRrcProtocolIdeal::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 60 of file lte-rrc-protocol-ideal.cc.
References m_rrc, m_ueRrcSapUser, and NS_LOG_FUNCTION.
DoSendIdealUeContextRemoveRequest()
void ns3::LteUeRrcProtocolIdeal::DoSendIdealUeContextRemoveRequest (uint16_t rnti) private
Send Ideal UE context remove request function.
Notify eNodeB to release UE context once radio link failure or random access failure is detected. It is needed since no RLF detection mechanism at eNodeB is implemented
Parameters
rnti the RNTI of the UE
Definition at line 174 of file lte-rrc-protocol-ideal.cc.
References m_enbRrcSapProvider, m_rnti, m_rrc, NS_ABORT_MSG_IF, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::LteEnbRrcSapProvider::RecvIdealUeContextRemoveRequest(), ns3::RRC_IDEAL_MSG_DELAY, ns3::Simulator::Schedule(), and SetEnbRrcSapProvider().
DoSendMeasurementReport()
void ns3::LteUeRrcProtocolIdeal::DoSendMeasurementReport (LteRrcSap::MeasurementReport msg) private
Send measurement report function.
Parameters
msg LteRrcSap::MeasurementReport
Definition at line 164 of file lte-rrc-protocol-ideal.cc.
References m_enbRrcSapProvider, m_rnti, ns3::LteEnbRrcSapProvider::RecvMeasurementReport(), ns3::RRC_IDEAL_MSG_DELAY, and ns3::Simulator::Schedule().
DoSendRrcConnectionReconfigurationCompleted()
void ns3::LteUeRrcProtocolIdeal::DoSendRrcConnectionReconfigurationCompleted (LteRrcSap::RrcConnectionReconfigurationCompleted msg) private
Send RRC connection reconfiguration completed function.
Parameters
msg LteRrcSap::RrcConnectionReconfigurationCompleted
Definition at line 129 of file lte-rrc-protocol-ideal.cc.
References m_enbRrcSapProvider, m_rnti, m_rrc, ns3::LteEnbRrcSapProvider::RecvRrcConnectionReconfigurationCompleted(), ns3::RRC_IDEAL_MSG_DELAY, ns3::Simulator::Schedule(), and SetEnbRrcSapProvider().
DoSendRrcConnectionReestablishmentComplete()
void ns3::LteUeRrcProtocolIdeal::DoSendRrcConnectionReestablishmentComplete (LteRrcSap::RrcConnectionReestablishmentComplete msg) private
Send RRC connection reestablishment complete function.
Parameters
msg LteRrcSap::RrcConnectionReestablishmentRequest
Definition at line 154 of file lte-rrc-protocol-ideal.cc.
References m_enbRrcSapProvider, m_rnti, ns3::LteEnbRrcSapProvider::RecvRrcConnectionReestablishmentComplete(), ns3::RRC_IDEAL_MSG_DELAY, and ns3::Simulator::Schedule().
DoSendRrcConnectionReestablishmentRequest()
void ns3::LteUeRrcProtocolIdeal::DoSendRrcConnectionReestablishmentRequest (LteRrcSap::RrcConnectionReestablishmentRequest msg) private
Send RRC connection reestablishment request function.
Parameters
msg LteRrcSap::RrcConnectionReestablishmentRequest
Definition at line 144 of file lte-rrc-protocol-ideal.cc.
References m_enbRrcSapProvider, m_rnti, ns3::LteEnbRrcSapProvider::RecvRrcConnectionReestablishmentRequest(), ns3::RRC_IDEAL_MSG_DELAY, and ns3::Simulator::Schedule().
DoSendRrcConnectionRequest()
void ns3::LteUeRrcProtocolIdeal::DoSendRrcConnectionRequest (LteRrcSap::RrcConnectionRequest msg) private
Send RRC connection request function.
Parameters
msg LteRrcSap::RrcConnectionRequest
Definition at line 104 of file lte-rrc-protocol-ideal.cc.
References m_enbRrcSapProvider, m_rnti, m_rrc, ns3::LteEnbRrcSapProvider::RecvRrcConnectionRequest(), ns3::RRC_IDEAL_MSG_DELAY, ns3::Simulator::Schedule(), and SetEnbRrcSapProvider().
DoSendRrcConnectionSetupCompleted()
void ns3::LteUeRrcProtocolIdeal::DoSendRrcConnectionSetupCompleted (LteRrcSap::RrcConnectionSetupCompleted msg) private
Send RRC connection setup completed function.
Parameters
msg LteRrcSap::RrcConnectionSetupCompleted
Definition at line 119 of file lte-rrc-protocol-ideal.cc.
References m_enbRrcSapProvider, m_rnti, ns3::LteEnbRrcSapProvider::RecvRrcConnectionSetupCompleted(), ns3::RRC_IDEAL_MSG_DELAY, and ns3::Simulator::Schedule().
DoSetup()
void ns3::LteUeRrcProtocolIdeal::DoSetup (LteUeRrcSapUser::SetupParameters params) private
Setup function.
Parameters
params LteUeRrcSapUser::SetupParameters
Definition at line 97 of file lte-rrc-protocol-ideal.cc.
References NS_LOG_FUNCTION.
GetLteUeRrcSapUser()
LteUeRrcSapUser * ns3::LteUeRrcProtocolIdeal::GetLteUeRrcSapUser ()
Get LTE UE RRC SAP user function.
Returns
LTE UE RRC SAP user
Definition at line 85 of file lte-rrc-protocol-ideal.cc.
References m_ueRrcSapUser.
GetTypeId()
TypeId ns3::LteUeRrcProtocolIdeal::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 68 of file lte-rrc-protocol-ideal.cc.
References ns3::TypeId::SetParent().
SetEnbRrcSapProvider()
void ns3::LteUeRrcProtocolIdeal::SetEnbRrcSapProvider () private
Set ENB RRC SAP provider.
Definition at line 195 of file lte-rrc-protocol-ideal.cc.
References ns3::NodeList::Begin(), ns3::NodeList::End(), ns3::Node::GetDevice(), ns3::Node::GetNDevices(), ns3::LteEnbNetDevice::GetRrc(), ns3::LteEnbNetDevice::HasCellId(), m_enbRrcSapProvider, m_rnti, m_rrc, m_ueRrcSapProvider, NS_ASSERT_MSG, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by DoSendIdealUeContextRemoveRequest(), DoSendRrcConnectionReconfigurationCompleted(), and DoSendRrcConnectionRequest().
SetLteUeRrcSapProvider()
void ns3::LteUeRrcProtocolIdeal::SetLteUeRrcSapProvider (LteUeRrcSapProvider * p)
Set LTE UE RRC SAP provider function.
Parameters
p LTE UE RRC SAP provider
Definition at line 79 of file lte-rrc-protocol-ideal.cc.
References m_ueRrcSapProvider.
SetUeRrc()
void ns3::LteUeRrcProtocolIdeal::SetUeRrc (Ptr< LteUeRrc > rrc)
Set LTE UE RRC function.
Parameters
rrc LTE UE RRC
Definition at line 91 of file lte-rrc-protocol-ideal.cc.
References m_rrc.
Friends And Related Function Documentation
MemberLteUeRrcSapUser< LteUeRrcProtocolIdeal >
friend class MemberLteUeRrcSapUser< LteUeRrcProtocolIdeal > friend
allow MemberLteUeRrcSapUser<LteUeRrcProtocolIdeal> class friend access
Definition at line 1 of file lte-rrc-protocol-ideal.h.
Referenced by LteUeRrcProtocolIdeal().
Member Data Documentation
m_enbRrcSapProvider
LteEnbRrcSapProvider* ns3::LteUeRrcProtocolIdeal::m_enbRrcSapProvider private
the ENB RRC SAP provider
Definition at line 151 of file lte-rrc-protocol-ideal.h.
Referenced by DoSendIdealUeContextRemoveRequest(), DoSendMeasurementReport(), DoSendRrcConnectionReconfigurationCompleted(), DoSendRrcConnectionReestablishmentComplete(), DoSendRrcConnectionReestablishmentRequest(), DoSendRrcConnectionRequest(), DoSendRrcConnectionSetupCompleted(), and SetEnbRrcSapProvider().
m_rnti
uint16_t ns3::LteUeRrcProtocolIdeal::m_rnti private
the RNTI
Definition at line 148 of file lte-rrc-protocol-ideal.h.
Referenced by DoSendIdealUeContextRemoveRequest(), DoSendMeasurementReport(), DoSendRrcConnectionReconfigurationCompleted(), DoSendRrcConnectionReestablishmentComplete(), DoSendRrcConnectionReestablishmentRequest(), DoSendRrcConnectionRequest(), DoSendRrcConnectionSetupCompleted(), and SetEnbRrcSapProvider().
m_rrc
Ptr<LteUeRrc> ns3::LteUeRrcProtocolIdeal::m_rrc private
the RRC
Definition at line 147 of file lte-rrc-protocol-ideal.h.
Referenced by DoDispose(), DoSendIdealUeContextRemoveRequest(), DoSendRrcConnectionReconfigurationCompleted(), DoSendRrcConnectionRequest(), SetEnbRrcSapProvider(), and SetUeRrc().
m_ueRrcSapProvider
LteUeRrcSapProvider* ns3::LteUeRrcProtocolIdeal::m_ueRrcSapProvider private
the UE RRC SAP provider
Definition at line 149 of file lte-rrc-protocol-ideal.h.
Referenced by SetEnbRrcSapProvider(), and SetLteUeRrcSapProvider().
m_ueRrcSapUser
LteUeRrcSapUser* ns3::LteUeRrcProtocolIdeal::m_ueRrcSapUser private
the RRC SAP user
Definition at line 150 of file lte-rrc-protocol-ideal.h.
Referenced by LteUeRrcProtocolIdeal(), DoDispose(), and GetLteUeRrcSapUser().
The documentation for this class was generated from the following files:
src/lte/model/lte-rrc-protocol-ideal.h
src/lte/model/lte-rrc-protocol-ideal.cc