ns-3: ns3::EpcSgwApplication Class Reference
ns3::EpcSgwApplication Class Reference
LTE Models
This application implements the Serving Gateway Entity (SGW) according to the 3GPP TS 23.401 document.
#include "epc-sgw-application.h"
Classes
struct EnbInfo
EnbInfo structure.
Public Member Functions
EpcSgwApplication (const Ptr< Socket > s1uSocket, Ipv4Address s5Addr, const Ptr< Socket > s5uSocket, const Ptr< Socket > s5cSocket)
Constructor that binds callback methods of sockets.
virtual ~EpcSgwApplication (void)
Destructor.
void AddEnb (uint16_t cellId, Ipv4Address enbAddr, Ipv4Address sgwAddr)
Let the SGW be aware of a new eNB.
void AddMme (Ipv4Address mmeS11Addr, Ptr< Socket > s11Socket)
Let the SGW be aware of an MME.
void AddPgw (Ipv4Address pgwAddr)
Let the SGW be aware of a PGW.
virtual void DoDispose ()
Destructor implementation.
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void DoRecvCreateSessionRequest (Ptr< Packet > packet)
Process GTP-C Create Session Request message.
void DoRecvCreateSessionResponse (Ptr< Packet > packet)
Process GTP-C Create Session Response message.
void DoRecvDeleteBearerCommand (Ptr< Packet > packet)
Process GTP-C Delete Bearer Command message.
void DoRecvDeleteBearerRequest (Ptr< Packet > packet)
Process GTP-C Delete Bearer Request message.
void DoRecvDeleteBearerResponse (Ptr< Packet > packet)
Process GTP-C Delete Bearer Response message.
void DoRecvModifyBearerRequest (Ptr< Packet > packet)
Process GTP-C Modify Bearer Request message.
void DoRecvModifyBearerResponse (Ptr< Packet > packet)
Process GTP-C Modify Bearer Response message.
void RecvFromS11Socket (Ptr< Socket > socket)
Method to be assigned to the recv callback of the S11 socket.
void RecvFromS1uSocket (Ptr< Socket > socket)
Method to be assigned to the recv callback of the S1-U socket.
void RecvFromS5cSocket (Ptr< Socket > socket)
Method to be assigned to the recv callback of the S5-C socket.
void RecvFromS5uSocket (Ptr< Socket > socket)
Method to be assigned to the recv callback of the S5-U socket.
void SendToS1uSocket (Ptr< Packet > packet, Ipv4Address enbS1uAddress, uint32_t teid)
Send a data packet to an eNB via the S1-U interface.
void SendToS5uSocket (Ptr< Packet > packet, Ipv4Address pgwAddr, uint32_t teid)
Send a data packet to the PGW via the S5 interface.
Private Attributes
std::map< uint32_t, Ipv4Address > m_enbByTeidMap
Map for eNB address by TEID.
std::map< uint16_t, EnbInfo > m_enbInfoByCellId
Map for eNB info by cell ID.
uint16_t m_gtpcUdpPort
UDP port to be used for GTP-C.
uint16_t m_gtpuUdpPort
UDP port to be used for GTP-U.
Ipv4Address m_mmeS11Addr
MME address in the S11 interface.
std::map< uint32_t, GtpcHeader::Fteid_t > m_mmeS11FteidBySgwS5cTeid
MME S11 FTEID by SGW S5C TEID.
Ipv4Address m_pgwAddr
PGW address in the S5 interface.
Ptr< Socket > m_s11Socket
UDP socket to send/receive control messages to/from the S11 interface.
Ptr< Socket > m_s1uSocket
UDP socket to send/receive GTP-U packets to/from the S1-U interface.
Ipv4Address m_s5Addr
SGW address in the S5 interface.
Ptr< Socket > m_s5cSocket
UDP socket to send/receive GTP-C packets to/from the S5 interface.
Ptr< Socket > m_s5uSocket
UDP socket to send/receive GTP-U packets to/from the S5 interface.
uint32_t m_teidCount
TEID count.
Additional Inherited Members
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Protected Member Functions inherited from ns3::Application
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This application implements the Serving Gateway Entity (SGW) according to the 3GPP TS 23.401 document.
Introspection did not find any typical Config paths.
This Application implements the SGW side of the S5 interface between the SGW node and the PGW node and the SGW side of the S11 interface between the SGW node and the MME node hosts. It supports the following functions and messages:
S5 connectivity (i.e. GTPv2-C signalling and GTP-U data plane)
Bearer management functions including dedicated bearer establishment
UL and DL bearer binding
Tunnel Management messages
Others functions enumerated in section 4.4.3.2 of 3GPP TS 23.401 are not supported.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 240 bytes (on a 64-bit architecture).
Definition at line 48 of file epc-sgw-application.h.
Constructor & Destructor Documentation
EpcSgwApplication()
ns3::EpcSgwApplication::EpcSgwApplication (const Ptr< Socket > s1uSocket, Ipv4Address s5Addr, const Ptr< Socket > s5uSocket, const Ptr< Socket > s5cSocket)
Constructor that binds callback methods of sockets.
Parameters
s1uSocket socket used to send/receive GTP-U packets to/from the eNBs
s5Addr IPv4 address of the S5 interface
s5uSocket socket used to send/receive GTP-U packets to/from the PGW
s5cSocket socket used to send/receive GTP-C packets to/from the PGW
Definition at line 31 of file epc-sgw-application.cc.
References m_s1uSocket, m_s5cSocket, m_s5uSocket, ns3::MakeCallback(), NS_LOG_FUNCTION, RecvFromS1uSocket(), RecvFromS5cSocket(), RecvFromS5uSocket(), and ns3::Socket::SetRecvCallback().
~EpcSgwApplication()
ns3::EpcSgwApplication::~EpcSgwApplication (void) virtual
Destructor.
Definition at line 47 of file epc-sgw-application.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddEnb()
void ns3::EpcSgwApplication::AddEnb (uint16_t cellId, Ipv4Address enbAddr, Ipv4Address sgwAddr)
Let the SGW be aware of a new eNB.
Parameters
cellId the cell identifier
enbAddr the address of the eNB
sgwAddr the address of the SGW
Definition at line 91 of file epc-sgw-application.cc.
References ns3::EpcSgwApplication::EnbInfo::enbAddr, m_enbInfoByCellId, NS_LOG_FUNCTION, and ns3::EpcSgwApplication::EnbInfo::sgwAddr.
AddMme()
void ns3::EpcSgwApplication::AddMme (Ipv4Address mmeS11Addr, Ptr< Socket > s11Socket)
Let the SGW be aware of an MME.
Parameters
mmeS11Addr the address of the MME
s11Socket the socket to send/receive messages from the MME
Definition at line 75 of file epc-sgw-application.cc.
References m_mmeS11Addr, m_s11Socket, ns3::MakeCallback(), NS_LOG_FUNCTION, RecvFromS11Socket(), and ns3::Socket::SetRecvCallback().
AddPgw()
void ns3::EpcSgwApplication::AddPgw (Ipv4Address pgwAddr)
Let the SGW be aware of a PGW.
Parameters
pgwAddr the address of the PGW
Definition at line 84 of file epc-sgw-application.cc.
References m_pgwAddr, and NS_LOG_FUNCTION.
DoDispose()
void ns3::EpcSgwApplication::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Application.
Definition at line 53 of file epc-sgw-application.cc.
References m_s1uSocket, m_s5cSocket, m_s5uSocket, ns3::MakeNullCallback(), NS_LOG_FUNCTION, and ns3::Socket::SetRecvCallback().
DoRecvCreateSessionRequest()
void ns3::EpcSgwApplication::DoRecvCreateSessionRequest (Ptr< Packet > packet) private
Process GTP-C Create Session Request message.
Parameters
packet the packet containing the message
Definition at line 228 of file epc-sgw-application.cc.
References ns3::Packet::AddHeader(), ns3::GtpcHeader::Fteid_t::addr, ns3::GtpcCreateSessionRequestMessage::BearerContextToBeCreated::bearerLevelQos, ns3::GtpcHeader::ComputeMessageLength(), ns3::GtpcCreateSessionRequestMessage::BearerContextToBeCreated::epsBearerId, ns3::GtpcCreateSessionRequestMessage::GetBearerContextsToBeCreated(), ns3::GtpcCreateSessionRequestMessage::GetImsi(), ns3::GtpcCreateSessionRequestMessage::GetSenderCpFteid(), ns3::GtpcCreateSessionRequestMessage::GetUliEcgi(), ns3::GtpcHeader::Fteid_t::interfaceType, m_enbByTeidMap, m_enbInfoByCellId, m_gtpcUdpPort, m_mmeS11FteidBySgwS5cTeid, m_pgwAddr, m_s5Addr, m_s5cSocket, m_teidCount, NS_ABORT_IF, NS_ASSERT_MSG, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Packet::RemoveHeader(), ns3::GtpcHeader::S11_MME_GTPC, ns3::GtpcHeader::S5_SGW_GTPC, ns3::GtpcHeader::S5_SGW_GTPU, ns3::Socket::SendTo(), ns3::GtpcCreateSessionRequestMessage::SetBearerContextsToBeCreated(), ns3::GtpcCreateSessionRequestMessage::SetImsi(), ns3::GtpcCreateSessionRequestMessage::SetSenderCpFteid(), ns3::GtpcHeader::SetTeid(), ns3::GtpcCreateSessionRequestMessage::SetUliEcgi(), ns3::GtpcCreateSessionRequestMessage::BearerContextToBeCreated::sgwS5uFteid, ns3::GtpcHeader::Fteid_t::teid, and ns3::GtpcCreateSessionRequestMessage::BearerContextToBeCreated::tft.
Referenced by RecvFromS11Socket().
DoRecvCreateSessionResponse()
void ns3::EpcSgwApplication::DoRecvCreateSessionResponse (Ptr< Packet > packet) private
Process GTP-C Create Session Response message.
Parameters
packet the packet containing the message
Definition at line 399 of file epc-sgw-application.cc.
References ns3::Packet::AddHeader(), ns3::GtpcHeader::Fteid_t::addr, ns3::GtpcCreateSessionResponseMessage::BearerContextCreated::bearerLevelQos, ns3::GtpcHeader::ComputeMessageLength(), ns3::GtpcCreateSessionResponseMessage::BearerContextCreated::epsBearerId, ns3::GtpcCreateSessionResponseMessage::BearerContextCreated::fteid, ns3::GtpcCreateSessionResponseMessage::GetBearerContextsCreated(), ns3::GtpcCreateSessionResponseMessage::GetSenderCpFteid(), ns3::GtpcHeader::GetTeid(), ns3::GtpcHeader::Fteid_t::interfaceType, m_gtpcUdpPort, m_mmeS11FteidBySgwS5cTeid, m_s11Socket, m_s5Addr, NS_ASSERT_MSG, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Packet::RemoveHeader(), ns3::GtpcIes::REQUEST_ACCEPTED, ns3::GtpcHeader::S5_PGW_GTPC, ns3::GtpcHeader::S5_SGW_GTPU, ns3::Socket::SendTo(), ns3::GtpcCreateSessionResponseMessage::SetBearerContextsCreated(), ns3::GtpcCreateSessionResponseMessage::SetCause(), ns3::GtpcHeader::SetTeid(), ns3::GtpcHeader::Fteid_t::teid, and ns3::GtpcCreateSessionResponseMessage::BearerContextCreated::tft.
Referenced by RecvFromS5cSocket().
DoRecvDeleteBearerCommand()
void ns3::EpcSgwApplication::DoRecvDeleteBearerCommand (Ptr< Packet > packet) private
Process GTP-C Delete Bearer Command message.
Parameters
packet the packet containing the message
Definition at line 348 of file epc-sgw-application.cc.
References ns3::Packet::AddHeader(), ns3::GtpcHeader::ComputeMessageLength(), ns3::GtpcDeleteBearerCommandMessage::GetBearerContexts(), ns3::GtpcHeader::GetTeid(), ns3::GtpcDeleteBearerCommandMessage::BearerContext::m_epsBearerId, m_gtpcUdpPort, m_pgwAddr, m_s5cSocket, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Packet::RemoveHeader(), ns3::Socket::SendTo(), ns3::GtpcDeleteBearerCommandMessage::SetBearerContexts(), and ns3::GtpcHeader::SetTeid().
Referenced by RecvFromS11Socket().
DoRecvDeleteBearerRequest()
void ns3::EpcSgwApplication::DoRecvDeleteBearerRequest (Ptr< Packet > packet) private
Process GTP-C Delete Bearer Request message.
Parameters
packet the packet containing the message
Definition at line 462 of file epc-sgw-application.cc.
References ns3::Packet::AddHeader(), ns3::GtpcHeader::ComputeMessageLength(), ns3::GtpcDeleteBearerRequestMessage::GetEpsBearerIds(), ns3::GtpcHeader::GetTeid(), m_gtpcUdpPort, m_mmeS11Addr, m_s11Socket, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Packet::RemoveHeader(), ns3::Socket::SendTo(), ns3::GtpcDeleteBearerRequestMessage::SetEpsBearerIds(), and ns3::GtpcHeader::SetTeid().
Referenced by RecvFromS5cSocket().
DoRecvDeleteBearerResponse()
void ns3::EpcSgwApplication::DoRecvDeleteBearerResponse (Ptr< Packet > packet) private
Process GTP-C Delete Bearer Response message.
Parameters
packet the packet containing the message
Definition at line 376 of file epc-sgw-application.cc.
References ns3::Packet::AddHeader(), ns3::GtpcHeader::ComputeMessageLength(), ns3::GtpcDeleteBearerResponseMessage::GetEpsBearerIds(), ns3::GtpcHeader::GetTeid(), m_gtpcUdpPort, m_pgwAddr, m_s5cSocket, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Packet::RemoveHeader(), ns3::Socket::SendTo(), ns3::GtpcDeleteBearerResponseMessage::SetEpsBearerIds(), and ns3::GtpcHeader::SetTeid().
Referenced by RecvFromS11Socket().
DoRecvModifyBearerRequest()
void ns3::EpcSgwApplication::DoRecvModifyBearerRequest (Ptr< Packet > packet) private
Process GTP-C Modify Bearer Request message.
Parameters
packet the packet containing the message
Definition at line 295 of file epc-sgw-application.cc.
References ns3::Packet::AddHeader(), ns3::GtpcHeader::Fteid_t::addr, ns3::GtpcHeader::ComputeMessageLength(), ns3::GtpcModifyBearerRequestMessage::BearerContextToBeModified::epsBearerId, ns3::GtpcModifyBearerRequestMessage::BearerContextToBeModified::fteid, ns3::GtpcModifyBearerRequestMessage::GetBearerContextsToBeModified(), ns3::GtpcModifyBearerRequestMessage::GetImsi(), ns3::GtpcModifyBearerRequestMessage::GetUliEcgi(), ns3::GtpcHeader::Fteid_t::interfaceType, m_enbByTeidMap, m_enbInfoByCellId, m_gtpcUdpPort, m_pgwAddr, m_s5Addr, m_s5cSocket, NS_ASSERT_MSG, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Packet::RemoveHeader(), ns3::GtpcHeader::S1U_ENB_GTPU, ns3::GtpcHeader::S5_SGW_GTPU, ns3::Socket::SendTo(), ns3::GtpcModifyBearerRequestMessage::SetImsi(), ns3::GtpcHeader::SetTeid(), ns3::GtpcModifyBearerRequestMessage::SetUliEcgi(), and ns3::GtpcHeader::Fteid_t::teid.
Referenced by RecvFromS11Socket().
DoRecvModifyBearerResponse()
void ns3::EpcSgwApplication::DoRecvModifyBearerResponse (Ptr< Packet > packet) private
Process GTP-C Modify Bearer Response message.
Parameters
packet the packet containing the message
Definition at line 443 of file epc-sgw-application.cc.
References ns3::Packet::AddHeader(), ns3::GtpcHeader::ComputeMessageLength(), ns3::GtpcHeader::GetTeid(), m_gtpcUdpPort, m_mmeS11Addr, m_s11Socket, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Packet::RemoveHeader(), ns3::GtpcIes::REQUEST_ACCEPTED, ns3::Socket::SendTo(), ns3::GtpcModifyBearerResponseMessage::SetCause(), and ns3::GtpcHeader::SetTeid().
Referenced by RecvFromS5cSocket().
GetTypeId()
TypeId ns3::EpcSgwApplication::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 65 of file epc-sgw-application.cc.
References ns3::TypeId::SetParent().
RecvFromS11Socket()
void ns3::EpcSgwApplication::RecvFromS11Socket (Ptr< Socket > socket) private
Method to be assigned to the recv callback of the S11 socket.
It is called when the SGW receives a control packet from the MME.
Parameters
socket pointer to the S11 socket
Definition at line 102 of file epc-sgw-application.cc.
References ns3::GtpcHeader::CreateSessionRequest, ns3::GtpcHeader::DeleteBearerCommand, ns3::GtpcHeader::DeleteBearerResponse, DoRecvCreateSessionRequest(), DoRecvDeleteBearerCommand(), DoRecvDeleteBearerResponse(), DoRecvModifyBearerRequest(), ns3::GtpcHeader::GetMessageType(), m_s11Socket, ns3::GtpcHeader::ModifyBearerRequest, NS_ASSERT, NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::Packet::PeekHeader(), and ns3::Socket::Recv().
Referenced by AddMme().
RecvFromS1uSocket()
void ns3::EpcSgwApplication::RecvFromS1uSocket (Ptr< Socket > socket) private
Method to be assigned to the recv callback of the S1-U socket.
It is called when the SGW receives a data packet from the eNB that is to be forwarded to the PGW.
Parameters
socket pointer to the S1-U socket
Definition at line 182 of file epc-sgw-application.cc.
References ns3::GtpuHeader::GetTeid(), m_pgwAddr, m_s1uSocket, NS_ASSERT, NS_LOG_FUNCTION, ns3::Socket::Recv(), ns3::Packet::RemoveHeader(), and SendToS5uSocket().
Referenced by EpcSgwApplication().
RecvFromS5cSocket()
void ns3::EpcSgwApplication::RecvFromS5cSocket (Ptr< Socket > socket) private
Method to be assigned to the recv callback of the S5-C socket.
It is called when the SGW receives a control packet from the PGW.
Parameters
socket pointer to the S5-C socket
Definition at line 152 of file epc-sgw-application.cc.
References ns3::GtpcHeader::CreateSessionResponse, ns3::GtpcHeader::DeleteBearerRequest, DoRecvCreateSessionResponse(), DoRecvDeleteBearerRequest(), DoRecvModifyBearerResponse(), ns3::GtpcHeader::GetMessageType(), m_s5cSocket, ns3::GtpcHeader::ModifyBearerResponse, NS_ASSERT, NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::Packet::PeekHeader(), and ns3::Socket::Recv().
Referenced by EpcSgwApplication().
RecvFromS5uSocket()
void ns3::EpcSgwApplication::RecvFromS5uSocket (Ptr< Socket > socket) private
Method to be assigned to the recv callback of the S5-U socket.
It is called when the SGW receives a data packet from the PGW that is to be forwarded to an eNB.
Parameters
socket pointer to the S5-U socket
Definition at line 137 of file epc-sgw-application.cc.
References ns3::GtpuHeader::GetTeid(), m_enbByTeidMap, m_s5uSocket, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Socket::Recv(), ns3::Packet::RemoveHeader(), and SendToS1uSocket().
Referenced by EpcSgwApplication().
SendToS1uSocket()
void ns3::EpcSgwApplication::SendToS1uSocket (Ptr< Packet > packet, Ipv4Address enbS1uAddress, uint32_t teid) private
Send a data packet to an eNB via the S1-U interface.
Parameters
packet packet to be sent
enbS1uAddress the address of the eNB
teid the Tunnel Enpoint IDentifier
Definition at line 195 of file epc-sgw-application.cc.
References ns3::Packet::AddHeader(), ns3::GtpuHeader::GetSerializedSize(), ns3::Packet::GetSize(), m_gtpuUdpPort, m_s1uSocket, NS_LOG_FUNCTION, ns3::Socket::SendTo(), ns3::GtpuHeader::SetLength(), and ns3::GtpuHeader::SetTeid().
Referenced by RecvFromS5uSocket().
SendToS5uSocket()
void ns3::EpcSgwApplication::SendToS5uSocket (Ptr< Packet > packet, Ipv4Address pgwAddr, uint32_t teid) private
Send a data packet to the PGW via the S5 interface.
Parameters
packet packet to be sent
pgwAddr the address of the PGW
teid the Tunnel Enpoint Identifier
Definition at line 209 of file epc-sgw-application.cc.
References ns3::Packet::AddHeader(), ns3::GtpuHeader::GetSerializedSize(), ns3::Packet::GetSize(), m_gtpuUdpPort, m_s5uSocket, NS_LOG_FUNCTION, ns3::Socket::SendTo(), ns3::GtpuHeader::SetLength(), and ns3::GtpuHeader::SetTeid().
Referenced by RecvFromS1uSocket().
Member Data Documentation
m_enbByTeidMap
std::map<uint32_t, Ipv4Address> ns3::EpcSgwApplication::m_enbByTeidMap private
Map for eNB address by TEID.
Definition at line 267 of file epc-sgw-application.h.
Referenced by DoRecvCreateSessionRequest(), DoRecvModifyBearerRequest(), and RecvFromS5uSocket().
m_enbInfoByCellId
std::map<uint16_t, EnbInfo> ns3::EpcSgwApplication::m_enbInfoByCellId private
Map for eNB info by cell ID.
Definition at line 262 of file epc-sgw-application.h.
Referenced by AddEnb(), DoRecvCreateSessionRequest(), and DoRecvModifyBearerRequest().
m_gtpcUdpPort
uint16_t ns3::EpcSgwApplication::m_gtpcUdpPort private
UDP port to be used for GTP-C.
Definition at line 244 of file epc-sgw-application.h.
Referenced by DoRecvCreateSessionRequest(), DoRecvCreateSessionResponse(), DoRecvDeleteBearerCommand(), DoRecvDeleteBearerRequest(), DoRecvDeleteBearerResponse(), DoRecvModifyBearerRequest(), and DoRecvModifyBearerResponse().
m_gtpuUdpPort
uint16_t ns3::EpcSgwApplication::m_gtpuUdpPort private
UDP port to be used for GTP-U.
Definition at line 239 of file epc-sgw-application.h.
Referenced by SendToS1uSocket(), and SendToS5uSocket().
m_mmeS11Addr
Ipv4Address ns3::EpcSgwApplication::m_mmeS11Addr private
MME address in the S11 interface.
Definition at line 209 of file epc-sgw-application.h.
Referenced by AddMme(), DoRecvDeleteBearerRequest(), and DoRecvModifyBearerResponse().
m_mmeS11FteidBySgwS5cTeid
std::map<uint32_t, GtpcHeader::Fteid_t> ns3::EpcSgwApplication::m_mmeS11FteidBySgwS5cTeid private
MME S11 FTEID by SGW S5C TEID.
Definition at line 272 of file epc-sgw-application.h.
Referenced by DoRecvCreateSessionRequest(), and DoRecvCreateSessionResponse().
m_pgwAddr
Ipv4Address ns3::EpcSgwApplication::m_pgwAddr private
PGW address in the S5 interface.
Definition at line 219 of file epc-sgw-application.h.
Referenced by AddPgw(), DoRecvCreateSessionRequest(), DoRecvDeleteBearerCommand(), DoRecvDeleteBearerResponse(), DoRecvModifyBearerRequest(), and RecvFromS1uSocket().
m_s11Socket
Ptr<Socket> ns3::EpcSgwApplication::m_s11Socket private
UDP socket to send/receive control messages to/from the S11 interface.
Definition at line 214 of file epc-sgw-application.h.
Referenced by AddMme(), DoRecvCreateSessionResponse(), DoRecvDeleteBearerRequest(), DoRecvModifyBearerResponse(), and RecvFromS11Socket().
m_s1uSocket
Ptr<Socket> ns3::EpcSgwApplication::m_s1uSocket private
UDP socket to send/receive GTP-U packets to/from the S1-U interface.
Definition at line 234 of file epc-sgw-application.h.
Referenced by EpcSgwApplication(), DoDispose(), RecvFromS1uSocket(), and SendToS1uSocket().
m_s5Addr
Ipv4Address ns3::EpcSgwApplication::m_s5Addr private
SGW address in the S5 interface.
Definition at line 204 of file epc-sgw-application.h.
Referenced by DoRecvCreateSessionRequest(), DoRecvCreateSessionResponse(), and DoRecvModifyBearerRequest().
m_s5cSocket
Ptr<Socket> ns3::EpcSgwApplication::m_s5cSocket private
UDP socket to send/receive GTP-C packets to/from the S5 interface.
Definition at line 229 of file epc-sgw-application.h.
Referenced by EpcSgwApplication(), DoDispose(), DoRecvCreateSessionRequest(), DoRecvDeleteBearerCommand(), DoRecvDeleteBearerResponse(), DoRecvModifyBearerRequest(), and RecvFromS5cSocket().
m_s5uSocket
Ptr<Socket> ns3::EpcSgwApplication::m_s5uSocket private
UDP socket to send/receive GTP-U packets to/from the S5 interface.
Definition at line 224 of file epc-sgw-application.h.
Referenced by EpcSgwApplication(), DoDispose(), RecvFromS5uSocket(), and SendToS5uSocket().
m_teidCount
uint32_t ns3::EpcSgwApplication::m_teidCount private
TEID count.
Definition at line 249 of file epc-sgw-application.h.
Referenced by DoRecvCreateSessionRequest().
The documentation for this class was generated from the following files:
src/lte/model/epc-sgw-application.h
src/lte/model/epc-sgw-application.cc