ns-3: ns3::TcpLp Class Reference
ns3::TcpLp Class Reference
#include "tcp-lp.h"
Public Member Functions
TcpLp (const TcpLp &sock)
Copy constructor.
TcpLp (void)
Creates an unbound tcp socket.
virtual ~TcpLp (void)
virtual Ptr< TcpCongestionOps > Fork ()
Copy the congestion control algorithm across sockets.
virtual std::string GetName () const
Get the name of the congestion control algorithm.
virtual void PktsAcked (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked, const Time &rtt)
Timing information on received ACK.
Public Member Functions inherited from ns3::TcpNewReno
TcpNewReno ()
TcpNewReno (const TcpNewReno &sock)
Copy constructor.
~TcpNewReno ()
virtual uint32_t GetSsThresh (Ptr< const TcpSocketState > tcb, uint32_t bytesInFlight)
Get the slow start threshold after a loss event.
virtual void IncreaseWindow (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
Try to increase the cWnd following the NewReno specification.
Public Member Functions inherited from ns3::TcpCongestionOps
TcpCongestionOps ()
TcpCongestionOps (const TcpCongestionOps &other)
Copy constructor.
virtual ~TcpCongestionOps ()
virtual void CongControl (Ptr< TcpSocketState > tcb, const TcpRateOps::TcpRateConnection &rc, const TcpRateOps::TcpRateSample &rs)
Called when packets are delivered to update cwnd and pacing rate.
virtual void CongestionStateSet (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCongState_t newState)
Trigger events/calculations specific to a congestion state.
virtual void CwndEvent (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCAEvent_t event)
Trigger events/calculations on occurrence of congestion window event.
virtual bool HasCongControl () const
Returns true when Congestion Control Algorithm implements CongControl.
virtual void Init (Ptr< TcpSocketState > tcb)
Set configuration required by congestion control algorithm.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpNewReno
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpCongestionOps
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void CongestionAvoidance (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
Invokes Congestion Avoidance of TcpNewReno if TcpLp is not within inference.
Protected Member Functions inherited from ns3::TcpNewReno
virtual uint32_t SlowStart (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
Tcp NewReno slow start algorithm.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
enum State { LP_VALID_OWD = (1 << 1) , LP_WITHIN_THR = (1 << 3) , LP_WITHIN_INF = (1 << 4) }
Describes the state of TcpLp.
Private Member Functions
uint32_t OwdCalculator (Ptr< TcpSocketState > tcb)
Calculates One-Way Delay using Sender and Receiver timestamps.
void RttSample (Ptr< TcpSocketState > tcb)
Estimates minimum and maximum One-Way Delays and calculates the smoothed One-Way Delay.
Private Attributes
uint32_t m_flag
TcpLp state flag.
Time m_inference
Current inference period.
Time m_lastDrop
Last time when cwnd was reduced.
uint32_t m_owdMax
Maximum One-Way Delay.
uint32_t m_owdMaxRsv
Reserved Maximum One-Way Delay.
uint32_t m_owdMin
Minimum One-Way Delay.
uint32_t m_sOwd
Smoothed One-Way Delay.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Config Paths
ns3::TcpLp is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::TcpL4Protocol/SocketList/[i]/CongestionOps/$ns3::TcpNewReno/$ns3::TcpLp"
"/NodeList/[i]/$ns3::TcpL4Protocol/SocketList/[i]/CongestionOps/$ns3::TcpLp"
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 64 bytes (on a 64-bit architecture).
Definition at line 35 of file tcp-lp.h.
Member Enumeration Documentation
State
enum ns3::TcpLp::State private
Describes the state of TcpLp.
Enumerator
LP_VALID_OWD
Calculated One-Way Delay is valid.
LP_WITHIN_THR
TcpLp is within Threshold.
LP_WITHIN_INF
TcpLp is within Inference.
Definition at line 91 of file tcp-lp.h.
Constructor & Destructor Documentation
TcpLp() [1/2]
ns3::TcpLp::TcpLp (void)
Creates an unbound tcp socket.
Definition at line 45 of file tcp-lp.cc.
References NS_LOG_FUNCTION.
TcpLp() [2/2]
ns3::TcpLp::TcpLp (const TcpLp & sock)
Copy constructor.
Parameters
sock the object to copy
Definition at line 58 of file tcp-lp.cc.
References NS_LOG_FUNCTION.
~TcpLp()
ns3::TcpLp::~TcpLp (void) virtual
Definition at line 71 of file tcp-lp.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CongestionAvoidance()
void ns3::TcpLp::CongestionAvoidance (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked) protected virtual
Invokes Congestion Avoidance of TcpNewReno if TcpLp is not within inference.
Parameters
tcb internal congestion state
segmentsAcked count of segments acked
Reimplemented from ns3::TcpNewReno.
Definition at line 83 of file tcp-lp.cc.
References ns3::TcpNewReno::CongestionAvoidance(), LP_WITHIN_INF, m_flag, and NS_LOG_FUNCTION.
Fork()
Ptr< TcpCongestionOps > ns3::TcpLp::Fork () virtual
Copy the congestion control algorithm across sockets.
Returns
a pointer of the copied object
Reimplemented from ns3::TcpNewReno.
Definition at line 77 of file tcp-lp.cc.
GetName()
std::string ns3::TcpLp::GetName () const virtual
Get the name of the congestion control algorithm.
Returns
A string identifying the name
Reimplemented from ns3::TcpNewReno.
Definition at line 234 of file tcp-lp.cc.
GetTypeId()
TypeId ns3::TcpLp::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 35 of file tcp-lp.cc.
References ns3::TypeId::SetParent().
OwdCalculator()
uint32_t ns3::TcpLp::OwdCalculator (Ptr< TcpSocketState > tcb) private
Calculates One-Way Delay using Sender and Receiver timestamps.
Parameters
tcb internal congestion state
Returns
One-Way Delay
Definition at line 94 of file tcp-lp.cc.
References LP_VALID_OWD, m_flag, ns3::TcpSocketState::m_rcvTimestampEchoReply, ns3::TcpSocketState::m_rcvTimestampValue, and NS_LOG_FUNCTION.
Referenced by RttSample().
PktsAcked()
void ns3::TcpLp::PktsAcked (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked, const Time & rtt) virtual
Timing information on received ACK.
The function is called every time an ACK is received. It determines the state of TcpLp and adjusts the congestion window accordingly.
Parameters
tcb internal congestion state
segmentsAcked count of segments acked
rtt last rtt
Reimplemented from ns3::TcpCongestionOps.
Definition at line 168 of file tcp-lp.cc.
References ns3::TracedValue< T >::Get(), ns3::Time::GetMilliSeconds(), ns3::Time::IsZero(), LP_WITHIN_INF, LP_WITHIN_THR, ns3::TcpSocketState::m_cWnd, m_flag, m_inference, m_lastDrop, m_owdMax, m_owdMaxRsv, m_owdMin, ns3::TcpSocketState::m_rcvTimestampEchoReply, ns3::TcpSocketState::m_segmentSize, m_sOwd, max, ns3::MilliSeconds(), ns3::Simulator::Now(), NS_LOG_FUNCTION, and RttSample().
RttSample()
void ns3::TcpLp::RttSample (Ptr< TcpSocketState > tcb) private
Estimates minimum and maximum One-Way Delays and calculates the smoothed One-Way Delay.
Parameters
tcb internal congestion state
Definition at line 118 of file tcp-lp.cc.
References LP_VALID_OWD, m_flag, m_owdMax, m_owdMaxRsv, m_owdMin, m_sOwd, NS_LOG_FUNCTION, and OwdCalculator().
Referenced by PktsAcked().
Member Data Documentation
m_flag
uint32_t ns3::TcpLp::m_flag private
TcpLp state flag.
Definition at line 98 of file tcp-lp.h.
Referenced by CongestionAvoidance(), OwdCalculator(), PktsAcked(), and RttSample().
m_inference
Time ns3::TcpLp::m_inference private
Current inference period.
Definition at line 104 of file tcp-lp.h.
Referenced by PktsAcked().
m_lastDrop
Time ns3::TcpLp::m_lastDrop private
Last time when cwnd was reduced.
Definition at line 103 of file tcp-lp.h.
Referenced by PktsAcked().
m_owdMax
uint32_t ns3::TcpLp::m_owdMax private
Maximum One-Way Delay.
Definition at line 101 of file tcp-lp.h.
Referenced by PktsAcked(), and RttSample().
m_owdMaxRsv
uint32_t ns3::TcpLp::m_owdMaxRsv private
Reserved Maximum One-Way Delay.
Definition at line 102 of file tcp-lp.h.
Referenced by PktsAcked(), and RttSample().
m_owdMin
uint32_t ns3::TcpLp::m_owdMin private
Minimum One-Way Delay.
Definition at line 100 of file tcp-lp.h.
Referenced by PktsAcked(), and RttSample().
m_sOwd
uint32_t ns3::TcpLp::m_sOwd private
Smoothed One-Way Delay.
Definition at line 99 of file tcp-lp.h.
Referenced by PktsAcked(), and RttSample().
The documentation for this class was generated from the following files:
src/internet/model/tcp-lp.h
src/internet/model/tcp-lp.cc