ns-3: ChannelAccessManagerTest< TxopType > Class Template Reference
ChannelAccessManagerTest< TxopType > Class Template Reference
Wifi Models » wifi module tests | Test suites
Channel Access Manager Test.
Public Member Functions
ChannelAccessManagerTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
void DoRun (void)
Implementation to actually run this TestCase.
void DoRun (void)
Implementation to actually run this TestCase.
void GenerateBackoff (uint32_t i)
Generate backoff function.
void NotifyAccessGranted (uint32_t i)
Notify access granted function.
void NotifyChannelSwitching (uint32_t i)
Notify channel switching function.
void NotifyInternalCollision (uint32_t i)
Notify internal collision function.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Types
typedef std::vector< Ptr< TxopTest< TxopType > > > TxopTests
the TXOP tests typedef
Private Member Functions
void AddAccessRequest (uint64_t at, uint64_t txTime, uint64_t expectedGrantTime, uint32_t from)
Add access function.
void AddAccessRequestWithAckTimeout (uint64_t at, uint64_t txTime, uint64_t expectedGrantTime, uint32_t from)
Add access request with Ack timeout.
void AddAccessRequestWithSuccessfullAck (uint64_t at, uint64_t txTime, uint64_t expectedGrantTime, uint32_t ackDelay, uint32_t from)
Add access request with successful ack.
void AddAckTimeoutReset (uint64_t at)
Add Ack timeout reset function.
void AddCcaBusyEvt (uint64_t at, uint64_t duration)
Add CCA busy event function.
void AddNavReset (uint64_t at, uint64_t duration)
Add NAV reset function.
void AddNavStart (uint64_t at, uint64_t duration)
Add NAV start function.
void AddRxErrorEvt (uint64_t at, uint64_t duration)
Add receive error event function for error at end of frame.
void AddRxErrorEvt (uint64_t at, uint64_t duration, uint64_t timeUntilError)
Add receive error event function for error during frame.
void AddRxInsideSifsEvt (uint64_t at, uint64_t duration)
Add receive inside SIFS event function.
void AddRxOkEvt (uint64_t at, uint64_t duration)
Add receive OK event function.
void AddRxStartEvt (uint64_t at, uint64_t duration)
Add receive start event function.
void AddSwitchingEvt (uint64_t at, uint64_t duration)
Add switching event function.
void AddTxEvt (uint64_t at, uint64_t duration)
Add transmit event function.
void AddTxop (uint32_t aifsn)
Add Txop function.
void DoAccessRequest (uint64_t txTime, uint64_t expectedGrantTime, Ptr< TxopTest< TxopType >> state)
Add access request with successful Ack.
void DoCheckBusy (bool busy)
Perform check that channel access manager is busy or idle.
void EndTest (void)
End test function.
void ExpectBackoff (uint64_t time, uint32_t nSlots, uint32_t from)
Expect generate backoff function.
void ExpectBusy (uint64_t time, bool busy)
Schedule a check that the channel access manager is busy or idle.
void ExpectInternalCollision (uint64_t time, uint32_t nSlots, uint32_t from)
Expect internal collision function.
void StartTest (uint64_t slotTime, uint64_t sifs, uint64_t eifsNoDifsNoSifs, uint32_t ackTimeoutValue=20)
Start test function.
Private Attributes
uint32_t m_ackTimeoutValue
the Ack timeout value
Ptr< ChannelAccessManagerStub > m_ChannelAccessManager
the channel access manager
Ptr< MacLowStub > m_low
the MAC low stubbed
TxopTests m_txop
the vector of Txop test instances
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
template<typename TxopType>
class ChannelAccessManagerTest< TxopType >
Channel Access Manager Test.
Definition at line 216 of file channel-access-manager-test.cc.
Member Typedef Documentation
TxopTests
template<typename TxopType > typedef std::vector<Ptr<TxopTest<TxopType> > > ChannelAccessManagerTest< TxopType >::TxopTests private
the TXOP tests typedef
Definition at line 387 of file channel-access-manager-test.cc.
Constructor & Destructor Documentation
ChannelAccessManagerTest()
template<typename TxopType > ChannelAccessManagerTest< TxopType >::ChannelAccessManagerTest
Definition at line 481 of file channel-access-manager-test.cc.
Member Function Documentation
AddAccessRequest()
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::AddAccessRequest (uint64_t at, uint64_t txTime, uint64_t expectedGrantTime, uint32_t from) private
Add access function.
Parameters
at the event time
txTime the transmit time
expectedGrantTime the expected grant time
from the index of the requesting Txop
Definition at line 709 of file channel-access-manager-test.cc.
AddAccessRequestWithAckTimeout()
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::AddAccessRequestWithAckTimeout (uint64_t at, uint64_t txTime, uint64_t expectedGrantTime, uint32_t from) private
Add access request with Ack timeout.
Parameters
at time to schedule DoAccessRequest event
txTime the transmit time
expectedGrantTime the expected grant time
from the index of the requesting Txop
Definition at line 717 of file channel-access-manager-test.cc.
References ChannelAccessManagerTest< TxopType >::DoAccessRequest(), ns3::MicroSeconds(), and ns3::Now().
AddAccessRequestWithSuccessfullAck()
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::AddAccessRequestWithSuccessfullAck (uint64_t at, uint64_t txTime, uint64_t expectedGrantTime, uint32_t ackDelay, uint32_t from) private
Add access request with successful ack.
Parameters
at time to schedule DoAccessRequest event
txTime the transmit time
expectedGrantTime the expected grant time
ackDelay the delay of the Ack after txEnd
from the index of the requesting Txop
Definition at line 727 of file channel-access-manager-test.cc.
References ChannelAccessManagerTest< TxopType >::DoAccessRequest(), ns3::MicroSeconds(), ns3::Now(), and NS_ASSERT.
AddAckTimeoutReset()
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::AddAckTimeoutReset (uint64_t at) private
Add Ack timeout reset function.
Parameters
at the event time
Definition at line 701 of file channel-access-manager-test.cc.
References ns3::MicroSeconds(), and ns3::Now().
AddCcaBusyEvt()
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::AddCcaBusyEvt (uint64_t at, uint64_t duration) private
Add CCA busy event function.
Parameters
at the event time
duration the duration
Definition at line 752 of file channel-access-manager-test.cc.
References ns3::MicroSeconds(), and ns3::Now().
AddNavReset()
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::AddNavReset (uint64_t at, uint64_t duration) private
Add NAV reset function.
Parameters
at the event time
duration the duration
Definition at line 683 of file channel-access-manager-test.cc.
References ns3::MicroSeconds(), and ns3::Now().
AddNavStart()
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::AddNavStart (uint64_t at, uint64_t duration) private
Add NAV start function.
Parameters
at the event time
duration the duration
Definition at line 692 of file channel-access-manager-test.cc.
References ns3::MicroSeconds(), and ns3::Now().
AddRxErrorEvt() [1/2]
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::AddRxErrorEvt (uint64_t at, uint64_t duration) private
Add receive error event function for error at end of frame.
Parameters
at the event time
duration the duration
Definition at line 660 of file channel-access-manager-test.cc.
References ns3::MicroSeconds(), and ns3::Now().
AddRxErrorEvt() [2/2]
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::AddRxErrorEvt (uint64_t at, uint64_t duration, uint64_t timeUntilError) private
Add receive error event function for error during frame.
Parameters
at the event time
duration the duration
timeUntilError the time after event time to force the error
Definition at line 671 of file channel-access-manager-test.cc.
References ns3::MicroSeconds(), and ns3::Now().
AddRxInsideSifsEvt()
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::AddRxInsideSifsEvt (uint64_t at, uint64_t duration) private
Add receive inside SIFS event function.
Parameters
at the event time
duration the duration
Definition at line 651 of file channel-access-manager-test.cc.
References ns3::MicroSeconds(), and ns3::Now().
AddRxOkEvt()
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::AddRxOkEvt (uint64_t at, uint64_t duration) private
Add receive OK event function.
Parameters
at the event time
duration the duration
Definition at line 640 of file channel-access-manager-test.cc.
References ns3::MicroSeconds(), and ns3::Now().
AddRxStartEvt()
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::AddRxStartEvt (uint64_t at, uint64_t duration) private
Add receive start event function.
Parameters
at the event time
duration the duration
Definition at line 770 of file channel-access-manager-test.cc.
References ns3::MicroSeconds(), and ns3::Now().
AddSwitchingEvt()
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::AddSwitchingEvt (uint64_t at, uint64_t duration) private
Add switching event function.
Parameters
at the event time
duration the duration
Definition at line 761 of file channel-access-manager-test.cc.
References ns3::MicroSeconds(), and ns3::Now().
AddTxEvt()
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::AddTxEvt (uint64_t at, uint64_t duration) private
Add transmit event function.
Parameters
at the event time
duration the duration
Definition at line 504 of file channel-access-manager-test.cc.
References ns3::MicroSeconds(), and ns3::Now().
AddTxop()
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::AddTxop (uint32_t aifsn) private
Add Txop function.
Parameters
aifsn the AIFSN
Definition at line 607 of file channel-access-manager-test.cc.
DoAccessRequest()
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::DoAccessRequest (uint64_t txTime, uint64_t expectedGrantTime, Ptr< TxopTest< TxopType >> state) private
Add access request with successful Ack.
Parameters
txTime the transmit time
expectedGrantTime the expected grant time
state TxopTest
Definition at line 739 of file channel-access-manager-test.cc.
Referenced by ChannelAccessManagerTest< TxopType >::AddAccessRequestWithAckTimeout(), and ChannelAccessManagerTest< TxopType >::AddAccessRequestWithSuccessfullAck().
DoCheckBusy()
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::DoCheckBusy (bool busy) private
Perform check that channel access manager is busy or idle.
Parameters
busy whether expected state is busy
Definition at line 587 of file channel-access-manager-test.cc.
References NS_TEST_EXPECT_MSG_EQ.
Referenced by ChannelAccessManagerTest< TxopType >::ExpectBusy().
DoRun() [1/3]
template<typename TxopType > virtual void ChannelAccessManagerTest< TxopType >::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
DoRun() [2/3]
void ChannelAccessManagerTest< Txop >::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 782 of file channel-access-manager-test.cc.
DoRun() [3/3]
void ChannelAccessManagerTest< QosTxop >::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 1124 of file channel-access-manager-test.cc.
EndTest()
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::EndTest (void) private
End test function.
Definition at line 618 of file channel-access-manager-test.cc.
References NS_TEST_EXPECT_MSG_EQ.
ExpectBackoff()
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::ExpectBackoff (uint64_t time, uint32_t nSlots, uint32_t from) private
Expect generate backoff function.
Parameters
time the expected time
nSlots the number of slots
from the expected from
Definition at line 568 of file channel-access-manager-test.cc.
References TxopTest< TxopType >::m_expectedBackoff.
ExpectBusy()
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::ExpectBusy (uint64_t time, bool busy) private
Schedule a check that the channel access manager is busy or idle.
Parameters
time the expected time
busy whether the manager is expected to be busy
Definition at line 579 of file channel-access-manager-test.cc.
References ChannelAccessManagerTest< TxopType >::DoCheckBusy(), ns3::MicroSeconds(), and ns3::Now().
ExpectInternalCollision()
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::ExpectInternalCollision (uint64_t time, uint32_t nSlots, uint32_t from) private
Expect internal collision function.
Parameters
time the expected time
nSlots the number of slots
from the expected from
Definition at line 557 of file channel-access-manager-test.cc.
References TxopTest< TxopType >::m_expectedInternalCollision.
GenerateBackoff()
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::GenerateBackoff (uint32_t i)
Generate backoff function.
Parameters
i the index of the Txop
Definition at line 528 of file channel-access-manager-test.cc.
References TxopTest< TxopType >::m_expectedBackoff, and NS_TEST_EXPECT_MSG_EQ.
NotifyAccessGranted()
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::NotifyAccessGranted (uint32_t i)
Notify access granted function.
Parameters
i the index of the Txop
Definition at line 488 of file channel-access-manager-test.cc.
References ns3::MicroSeconds(), ns3::Now(), and NS_TEST_EXPECT_MSG_EQ.
NotifyChannelSwitching()
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::NotifyChannelSwitching (uint32_t i)
Notify channel switching function.
Parameters
i the index of the Txop
Definition at line 543 of file channel-access-manager-test.cc.
References ns3::MicroSeconds(), ns3::Now(), and NS_TEST_EXPECT_MSG_EQ.
NotifyInternalCollision()
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::NotifyInternalCollision (uint32_t i)
Notify internal collision function.
Parameters
i the index of the Txop
Definition at line 513 of file channel-access-manager-test.cc.
References TxopTest< TxopType >::m_expectedInternalCollision, and NS_TEST_EXPECT_MSG_EQ.
StartTest()
template<typename TxopType > void ChannelAccessManagerTest< TxopType >::StartTest (uint64_t slotTime, uint64_t sifs, uint64_t eifsNoDifsNoSifs, uint32_t ackTimeoutValue = 20) private
Start test function.
Parameters
slotTime the slot time
sifs the SIFS
eifsNoDifsNoSifs the EIFS no DIFS no SIFS
ackTimeoutValue the Ack timeout value
Definition at line 594 of file channel-access-manager-test.cc.
References ns3::MicroSeconds().
Member Data Documentation
m_ackTimeoutValue
template<typename TxopType > uint32_t ChannelAccessManagerTest< TxopType >::m_ackTimeoutValue private
the Ack timeout value
Definition at line 392 of file channel-access-manager-test.cc.
m_ChannelAccessManager
template<typename TxopType > Ptr<ChannelAccessManagerStub> ChannelAccessManagerTest< TxopType >::m_ChannelAccessManager private
the channel access manager
Definition at line 390 of file channel-access-manager-test.cc.
m_low
template<typename TxopType > Ptr<MacLowStub> ChannelAccessManagerTest< TxopType >::m_low private
the MAC low stubbed
Definition at line 389 of file channel-access-manager-test.cc.
m_txop
template<typename TxopType > TxopTests ChannelAccessManagerTest< TxopType >::m_txop private
the vector of Txop test instances
Definition at line 391 of file channel-access-manager-test.cc.
The documentation for this class was generated from the following file:
src/wifi/test/channel-access-manager-test.cc