ns-3: ns3::LteUeNetDevice Class Reference
ns3::LteUeNetDevice Class Reference
LTE Models
The LteUeNetDevice class implements the UE net device.
#include "lte-ue-net-device.h"
Public Member Functions
LteUeNetDevice (void)
virtual ~LteUeNetDevice (void)
virtual void DoDispose ()
Destructor implementation.
std::map< uint8_t, Ptr< ComponentCarrierUe > > GetCcMap (void)
Get the ComponentCarrier Map for the UE.
Ptr< LteUeComponentCarrierManager > GetComponentCarrierManager (void) const
Get the componentn carrier manager.
uint32_t GetCsgId () const
Returns the CSG ID the UE is currently a member of.
uint32_t GetDlEarfcn () const
uint64_t GetImsi () const
Get the IMSI.
Ptr< LteUeMac > GetMac (void) const
Get the MAC.
Ptr< EpcUeNas > GetNas (void) const
Get the NAS.
Ptr< LteUePhy > GetPhy (void) const
Get the Phy.
Ptr< LteUeRrc > GetRrc () const
Get the RRC.
Ptr< LteEnbNetDevice > GetTargetEnb (void)
Get the target eNB where the UE is registered.
virtual bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)
void SetCcMap (std::map< uint8_t, Ptr< ComponentCarrierUe > > ccm)
Set the ComponentCarrier Map for the UE.
void SetCsgId (uint32_t csgId)
Enlist the UE device as a member of a particular CSG.
void SetDlEarfcn (uint32_t earfcn)
void SetTargetEnb (Ptr< LteEnbNetDevice > enb)
Set the target eNB where the UE is registered.
Public Member Functions inherited from ns3::LteNetDevice
LteNetDevice (void)
virtual ~LteNetDevice (void)
virtual void AddLinkChangeCallback (Callback< void > callback)
virtual Address GetAddress (void) const
virtual Address GetBroadcast (void) const
virtual Ptr< Channel > GetChannel (void) const
virtual uint32_t GetIfIndex (void) const
virtual uint16_t GetMtu (void) const
virtual Address GetMulticast (Ipv4Address addr) const
Make and return a MAC multicast address using the provided multicast group.
virtual Address GetMulticast (Ipv6Address addr) const
Get the MAC multicast address corresponding to the IPv6 address provided.
virtual Ptr< Node > GetNode (void) const
virtual bool IsBridge (void) const
Return true if the net device is acting as a bridge.
virtual bool IsBroadcast (void) const
virtual bool IsLinkUp (void) const
virtual bool IsMulticast (void) const
virtual bool IsPointToPoint (void) const
Return true if the net device is on a point-to-point link.
virtual bool NeedsArp (void) const
void Receive (Ptr< Packet > p)
receive a packet from the lower layers in order to forward it to the upper layers
virtual bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
virtual void SetAddress (Address address)
Set the address of this interface.
virtual void SetIfIndex (const uint32_t index)
virtual bool SetMtu (const uint16_t mtu)
virtual void SetNode (Ptr< Node > node)
virtual void SetPromiscReceiveCallback (PromiscReceiveCallback cb)
virtual void SetReceiveCallback (NetDevice::ReceiveCallback cb)
virtual bool SupportsSendFrom (void) const
Public Member Functions inherited from ns3::NetDevice
virtual ~NetDevice ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::LteNetDevice
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::NetDevice
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void UpdateConfig ()
Propagate attributes and configuration to sub-modules.
Private Attributes
std::map< uint8_t, Ptr< ComponentCarrierUe > > m_ccMap
CC map.
Ptr< LteUeComponentCarrierManager > m_componentCarrierManager
the component carrier manager
uint32_t m_csgId
the CSG ID
uint32_t m_dlEarfcn
downlink carrier frequency
uint64_t m_imsi
the IMSI
bool m_isConstructed
is constructed?
Ptr< EpcUeNas > m_nas
the NAS
Ptr< LteUeRrc > m_rrc
the RRC
Ptr< LteEnbNetDevice > m_targetEnb
target ENB
Additional Inherited Members
Public Types inherited from ns3::NetDevice
typedef void(* LinkChangeTracedCallback) (void)
TracedCallback signature for link changed event.
enum PacketType {
PACKET_HOST = 1 , NS3_PACKET_HOST = PACKET_HOST , PACKET_BROADCAST , NS3_PACKET_BROADCAST = PACKET_BROADCAST ,
PACKET_MULTICAST , NS3_PACKET_MULTICAST = PACKET_MULTICAST , PACKET_OTHERHOST , NS3_PACKET_OTHERHOST = PACKET_OTHERHOST
}
Packet types are used as they are in Linux.
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address &, const Address &, enum PacketType > PromiscReceiveCallback
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address & > ReceiveCallback
Protected Attributes inherited from ns3::LteNetDevice
NetDevice::ReceiveCallback m_rxCallback
receive callback
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The LteUeNetDevice class implements the UE net device.
Config Paths
ns3::LteUeNetDevice is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice/$ns3::LteUeNetDevice"
"/NodeList/[i]/DeviceList/[i]/$ns3::LteUeNetDevice"
Attributes
EpcUeNas: The NAS associated to this UeNetDevice
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::EpcUeNas>
Initial value: 0x0
Flags: construct write read
LteUeRrc: The RRC associated to this UeNetDevice
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::LteUeRrc>
Initial value: 0x0
Flags: construct write read
LteUeComponentCarrierManager: The ComponentCarrierManager associated to this UeNetDevice
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::LteUeComponentCarrierManager>
Initial value: 0x0
Flags: construct write read
ComponentCarrierMapUe: List of all component Carrier.
Set with class: ns3::ObjectPtrContainerValue
Underlying type: ns3::Ptr< ns3::ComponentCarrierUe>
Flags: read
Imsi: International Mobile Subscriber Identity assigned to this UE
Set with class: ns3::UintegerValue
Underlying type: uint64_t 0:18446744073709551615
Initial value: 0
Flags: construct write read
DlEarfcn: Downlink E-UTRA Absolute Radio Frequency Channel Number (EARFCN) as per 3GPP 36.101 Section 5.7.3.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:262143
Initial value: 100
Flags: construct write read
CsgId: The Closed Subscriber Group (CSG) identity that this UE is associated with, i.e., giving the UE access to cells which belong to this particular CSG. This restriction only applies to initial cell selection and EPC-enabled simulation. This does not revoke the UE's access to non-CSG cells.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 0
Flags: construct write read
Attributes defined in parent class ns3::LteNetDevice
Mtu: The MAC-level Maximum Transmission Unit
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 30000
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 168 bytes (on a 64-bit architecture).
Definition at line 56 of file lte-ue-net-device.h.
Constructor & Destructor Documentation
LteUeNetDevice()
ns3::LteUeNetDevice::LteUeNetDevice (void)
Definition at line 116 of file lte-ue-net-device.cc.
References NS_LOG_FUNCTION.
~LteUeNetDevice()
ns3::LteUeNetDevice::~LteUeNetDevice (void) virtual
Definition at line 122 of file lte-ue-net-device.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::LteUeNetDevice::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::LteNetDevice.
Definition at line 128 of file lte-ue-net-device.cc.
References ns3::LteNetDevice::DoDispose(), m_ccMap, m_componentCarrierManager, m_nas, m_rrc, m_targetEnb, and NS_LOG_FUNCTION.
DoInitialize()
void ns3::LteUeNetDevice::DoInitialize (void) protected virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 271 of file lte-ue-net-device.cc.
References m_ccMap, m_isConstructed, m_rrc, NS_LOG_FUNCTION, and UpdateConfig().
GetCcMap()
std::map< uint8_t, Ptr< ComponentCarrierUe > > ns3::LteUeNetDevice::GetCcMap (void)
Get the ComponentCarrier Map for the UE.
Returns
the map of ComponentCarrierUe
Definition at line 259 of file lte-ue-net-device.cc.
References m_ccMap.
GetComponentCarrierManager()
Ptr< LteUeComponentCarrierManager > ns3::LteUeNetDevice::GetComponentCarrierManager (void) const
Get the componentn carrier manager.
Returns
the LTE UE component carrier manager
Definition at line 194 of file lte-ue-net-device.cc.
References m_componentCarrierManager, and NS_LOG_FUNCTION.
GetCsgId()
uint32_t ns3::LteUeNetDevice::GetCsgId () const
Returns the CSG ID the UE is currently a member of.
Returns
the Closed Subscriber Group identity
Definition at line 229 of file lte-ue-net-device.cc.
References m_csgId, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetDlEarfcn()
uint32_t ns3::LteUeNetDevice::GetDlEarfcn () const
Returns
the downlink carrier frequency (EARFCN)
Note that real-life handset typically supports more than one EARFCN, but the sake of simplicity we assume only one EARFCN is supported.
Definition at line 215 of file lte-ue-net-device.cc.
References m_dlEarfcn, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetImsi()
uint64_t ns3::LteUeNetDevice::GetImsi (void) const
Get the IMSI.
Returns
the IMSI
Definition at line 208 of file lte-ue-net-device.cc.
References m_imsi, and NS_LOG_FUNCTION.
Referenced by ns3::LteStatsCalculator::FindImsiFromLteNetDevice().
GetMac()
Ptr< LteUeMac > ns3::LteUeNetDevice::GetMac (void) const
Get the MAC.
Returns
the LTE UE MAC
Definition at line 171 of file lte-ue-net-device.cc.
References m_ccMap, and NS_LOG_FUNCTION.
GetNas()
Ptr< EpcUeNas > ns3::LteUeNetDevice::GetNas (void) const
Get the NAS.
Returns
the LTE UE NAS
Definition at line 201 of file lte-ue-net-device.cc.
References m_nas, and NS_LOG_FUNCTION.
GetPhy()
Ptr< LteUePhy > ns3::LteUeNetDevice::GetPhy (void) const
Get the Phy.
Returns
the LTE UE Phy
Definition at line 187 of file lte-ue-net-device.cc.
References m_ccMap, and NS_LOG_FUNCTION.
Referenced by LteUplinkOpenLoopPowerControlTestCase::DoRun(), LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), and LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun().
GetRrc()
Ptr< LteUeRrc > ns3::LteUeNetDevice::GetRrc (void) const
Get the RRC.
Returns
the LTE UE RRC
Definition at line 179 of file lte-ue-net-device.cc.
References m_rrc, and NS_LOG_FUNCTION.
GetTargetEnb()
Ptr< LteEnbNetDevice > ns3::LteUeNetDevice::GetTargetEnb (void)
Get the target eNB where the UE is registered.
Returns
the pointer to the enb
Definition at line 252 of file lte-ue-net-device.cc.
References m_targetEnb, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::LteUeNetDevice::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 63 of file lte-ue-net-device.cc.
References GetCsgId(), GetDlEarfcn(), m_ccMap, m_componentCarrierManager, m_imsi, m_nas, m_rrc, ns3::MakeObjectMapAccessor(), ns3::MakePointerAccessor(), ns3::MakeUintegerAccessor(), SetCsgId(), SetDlEarfcn(), and ns3::TypeId::SetParent().
Referenced by ns3::LteHelper::LteHelper().
Send()
bool ns3::LteUeNetDevice::Send (Ptr< Packet > packet, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device to the specified destination Address
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 287 of file lte-ue-net-device.cc.
References m_nas, NS_ABORT_MSG_IF, NS_LOG_FUNCTION, ns3::Ipv4L3Protocol::PROT_NUMBER, and ns3::Ipv6L3Protocol::PROT_NUMBER.
SetCcMap()
void ns3::LteUeNetDevice::SetCcMap (std::map< uint8_t, Ptr< ComponentCarrierUe > > ccm)
Set the ComponentCarrier Map for the UE.
Parameters
ccm the map of ComponentCarrierUe
Definition at line 265 of file lte-ue-net-device.cc.
References m_ccMap.
SetCsgId()
void ns3::LteUeNetDevice::SetCsgId (uint32_t csgId)
Enlist the UE device as a member of a particular CSG.
Parameters
csgId the intended Closed Subscriber Group identity
UE is associated with a single CSG identity, and thus becoming a member of this particular CSG. As a result, the UE may gain access to cells which belong to this CSG. This does not revoke the UE's access to non-CSG cells.
Note
This restriction only applies to initial cell selection and EPC-enabled simulation.
Definition at line 236 of file lte-ue-net-device.cc.
References m_csgId, NS_LOG_FUNCTION, and UpdateConfig().
Referenced by GetTypeId().
SetDlEarfcn()
void ns3::LteUeNetDevice::SetDlEarfcn (uint32_t earfcn)
Parameters
earfcn the downlink carrier frequency (EARFCN)
Note that real-life handset typically supports more than one EARFCN, but the sake of simplicity we assume only one EARFCN is supported.
Definition at line 222 of file lte-ue-net-device.cc.
References m_dlEarfcn, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetTargetEnb()
void ns3::LteUeNetDevice::SetTargetEnb (Ptr< LteEnbNetDevice > enb)
Set the target eNB where the UE is registered.
Parameters
enb
Definition at line 244 of file lte-ue-net-device.cc.
References m_targetEnb, and NS_LOG_FUNCTION.
UpdateConfig()
void ns3::LteUeNetDevice::UpdateConfig (void) private
Propagate attributes and configuration to sub-modules.
Several attributes (e.g., the IMSI) are exported as the attributes of the LteUeNetDevice from a user perspective, but are actually used also in other sub-modules (the RRC, the PHY, etc.). This method takes care of updating the configuration of all these sub-modules so that their copy of attribute values are in sync with the one in the LteUeNetDevice.
Definition at line 147 of file lte-ue-net-device.cc.
References m_csgId, m_imsi, m_isConstructed, m_nas, m_rrc, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by DoInitialize(), and SetCsgId().
Member Data Documentation
m_ccMap
std::map< uint8_t, Ptr<ComponentCarrierUe> > ns3::LteUeNetDevice::m_ccMap private
CC map.
Definition at line 202 of file lte-ue-net-device.h.
Referenced by DoDispose(), DoInitialize(), GetCcMap(), GetMac(), GetPhy(), GetTypeId(), and SetCcMap().
m_componentCarrierManager
Ptr<LteUeComponentCarrierManager> ns3::LteUeNetDevice::m_componentCarrierManager private
the component carrier manager
Definition at line 194 of file lte-ue-net-device.h.
Referenced by DoDispose(), GetComponentCarrierManager(), and GetTypeId().
m_csgId
uint32_t ns3::LteUeNetDevice::m_csgId private
the CSG ID
Definition at line 200 of file lte-ue-net-device.h.
Referenced by GetCsgId(), SetCsgId(), and UpdateConfig().
m_dlEarfcn
uint32_t ns3::LteUeNetDevice::m_dlEarfcn private
downlink carrier frequency
Definition at line 198 of file lte-ue-net-device.h.
Referenced by GetDlEarfcn(), and SetDlEarfcn().
m_imsi
uint64_t ns3::LteUeNetDevice::m_imsi private
the IMSI
Definition at line 196 of file lte-ue-net-device.h.
Referenced by GetImsi(), GetTypeId(), and UpdateConfig().
m_isConstructed
bool ns3::LteUeNetDevice::m_isConstructed private
is constructed?
Definition at line 177 of file lte-ue-net-device.h.
Referenced by DoInitialize(), and UpdateConfig().
m_nas
Ptr<EpcUeNas> ns3::LteUeNetDevice::m_nas private
the NAS
Definition at line 193 of file lte-ue-net-device.h.
Referenced by DoDispose(), GetNas(), GetTypeId(), Send(), and UpdateConfig().
m_rrc
Ptr<LteUeRrc> ns3::LteUeNetDevice::m_rrc private
the RRC
Definition at line 192 of file lte-ue-net-device.h.
Referenced by DoDispose(), DoInitialize(), GetRrc(), GetTypeId(), and UpdateConfig().
m_targetEnb
Ptr<LteEnbNetDevice> ns3::LteUeNetDevice::m_targetEnb private
target ENB
Definition at line 190 of file lte-ue-net-device.h.
Referenced by DoDispose(), GetTargetEnb(), and SetTargetEnb().
The documentation for this class was generated from the following files:
src/lte/model/lte-ue-net-device.h
src/lte/model/lte-ue-net-device.cc