ns-3: ns3::Config::MatchContainer Class Reference
ns3::Config::MatchContainer Class Reference
Core » Configuration
hold a set of objects which match a specific search string.
#include "config.h"
Public Types
typedef std::vector< Ptr< Object > >::const_iterator Iterator
Const iterator over the objects in this container.
Public Member Functions
MatchContainer ()
MatchContainer (const std::vector< Ptr< Object > > &objects, const std::vector< std::string > &contexts, std::string path)
Constructor used only by implementation.
MatchContainer::Iterator Begin (void) const
void Connect (std::string name, const CallbackBase &cb)
bool ConnectFailSafe (std::string name, const CallbackBase &cb)
Connect the specified sink to all the objects stored in this container.
void ConnectWithoutContext (std::string name, const CallbackBase &cb)
bool ConnectWithoutContextFailSafe (std::string name, const CallbackBase &cb)
Connect the specified sink to all the objects stored in this container.
void Disconnect (std::string name, const CallbackBase &cb)
void DisconnectWithoutContext (std::string name, const CallbackBase &cb)
MatchContainer::Iterator End (void) const
Ptr< Object > Get (std::size_t i) const
std::string GetMatchedPath (uint32_t i) const
std::size_t GetN (void) const
std::string GetPath (void) const
void Set (std::string name, const AttributeValue &value)
bool SetFailSafe (std::string name, const AttributeValue &value)
Set the specified attribute value to all the objects stored in this container.
Private Attributes
std::vector< std::string > m_contexts
The context for each object.
std::vector< Ptr< Object > > m_objects
The list of objects in this container.
std::string m_path
The path used to perform the object matching.
Detailed Description
hold a set of objects which match a specific search string.
This class also allows you to perform a set of configuration operations on the set of matching objects stored in the container. Specifically, it is possible to perform bulk Connects and Sets.
Definition at line 180 of file config.h.
Member Typedef Documentation
Iterator
typedef std::vector<Ptr<Object> >::const_iterator ns3::Config::MatchContainer::Iterator
Const iterator over the objects in this container.
Definition at line 184 of file config.h.
Constructor & Destructor Documentation
MatchContainer() [1/2]
ns3::Config::MatchContainer::MatchContainer ()
Definition at line 43 of file config.cc.
References NS_LOG_FUNCTION.
MatchContainer() [2/2]
ns3::Config::MatchContainer::MatchContainer (const std::vector< Ptr< Object > > & objects, const std::vector< std::string > & contexts, std::string path)
Constructor used only by implementation.
Parameters
[in] objects The vector of objects to store in this container.
[in] contexts The corresponding contexts.
[in] path The path used for object matching.
Definition at line 47 of file config.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Begin()
MatchContainer::Iterator ns3::Config::MatchContainer::Begin (void) const
Returns
An iterator which points to the first item in the container
Definition at line 57 of file config.cc.
References m_objects, and NS_LOG_FUNCTION.
Referenced by ConnectWithoutContextFailSafe(), DisconnectWithoutContext(), Set(), and SetFailSafe().
Connect()
void ns3::Config::MatchContainer::Connect (std::string name, const CallbackBase & cb)
Parameters
[in] name The name of the trace source to connect to
[in] cb The sink to connect to the trace source
Connect the specified sink to all the objects stored in this container. This method will raise a fatal error if no objects could be connected; use ConnectFailSafe if no connections is a valid possible outcome.
See also
ns3::Config::Connect
Definition at line 117 of file config.cc.
References ConnectFailSafe(), and NS_FATAL_ERROR.
ConnectFailSafe()
bool ns3::Config::MatchContainer::ConnectFailSafe (std::string name, const CallbackBase & cb)
Connect the specified sink to all the objects stored in this container.
This method will return true if any trace sources could be connected, and false otherwise.
Returns
true if any trace sources could be connected.
Definition at line 125 of file config.cc.
References m_contexts, m_objects, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by Connect(), and ns3::Config::ConfigImpl::ConnectFailSafe().
ConnectWithoutContext()
void ns3::Config::MatchContainer::ConnectWithoutContext (std::string name, const CallbackBase & cb)
Parameters
[in] name The name of the trace source to connect to
[in] cb The sink to connect to the trace source
Connect the specified sink to all the objects stored in this container. This method will raise a fatal error if no objects could be connected; use ConnectWithoutContextFailSafe if no connections is a valid possible outcome.
See also
ns3::Config::ConnectWithoutContext
Definition at line 139 of file config.cc.
References ConnectWithoutContextFailSafe(), and NS_FATAL_ERROR.
ConnectWithoutContextFailSafe()
bool ns3::Config::MatchContainer::ConnectWithoutContextFailSafe (std::string name, const CallbackBase & cb)
Connect the specified sink to all the objects stored in this container.
This method will return true if any trace sources could be connected, and false otherwise.
Returns
true if any trace sources could be connected.
Definition at line 147 of file config.cc.
References Begin(), End(), NS_LOG_FUNCTION, and ns3::ObjectBase::TraceConnectWithoutContext().
Referenced by ConnectWithoutContext(), and ns3::Config::ConfigImpl::ConnectWithoutContextFailSafe().
Disconnect()
void ns3::Config::MatchContainer::Disconnect (std::string name, const CallbackBase & cb)
Parameters
[in] name The name of the trace source to disconnect from
[in] cb The sink to disconnect from the trace source
Disconnect the specified sink from all the objects stored in this container.
See also
ns3::Config::Disconnect
Definition at line 159 of file config.cc.
References m_contexts, m_objects, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::Config::ConfigImpl::Disconnect().
DisconnectWithoutContext()
void ns3::Config::MatchContainer::DisconnectWithoutContext (std::string name, const CallbackBase & cb)
Parameters
[in] name The name of the trace source to disconnect from
[in] cb The sink to disconnect from the trace source
Disconnect the specified sink from all the objects stored in this container.
See also
ns3::Config::DisconnectWithoutContext
Definition at line 171 of file config.cc.
References Begin(), End(), NS_LOG_FUNCTION, and ns3::ObjectBase::TraceDisconnectWithoutContext().
Referenced by ns3::Config::ConfigImpl::DisconnectWithoutContext().
End()
MatchContainer::Iterator ns3::Config::MatchContainer::End (void) const
Returns
An iterator which points to the last item in the container
Definition at line 63 of file config.cc.
References m_objects, and NS_LOG_FUNCTION.
Referenced by ConnectWithoutContextFailSafe(), DisconnectWithoutContext(), Set(), and SetFailSafe().
Get()
Ptr< Object > ns3::Config::MatchContainer::Get (std::size_t i) const
Parameters
[in] i Index of item to lookup ([0,n[)
Returns
The item requested.
Definition at line 75 of file config.cc.
References m_objects, and NS_LOG_FUNCTION.
Referenced by ns3::RandomVariableStreamHelper::AssignStreams(), ns3::LteStatsCalculator::FindCellIdFromEnbRlcPath(), ns3::LteStatsCalculator::FindImsiFromEnbRlcPath(), ns3::LteStatsCalculator::FindImsiFromLteNetDevice(), ns3::LteStatsCalculator::FindImsiFromUePhy(), and ns3::RadioEnvironmentMapHelper::Install().
GetMatchedPath()
std::string ns3::Config::MatchContainer::GetMatchedPath (uint32_t i) const
Parameters
[in] i Index of item to lookup ([0,n[)
Returns
The fully-qualified matching path associated to the requested item.
The matching patch uniquely identifies the requested object.
Definition at line 81 of file config.cc.
References m_contexts, and NS_LOG_FUNCTION.
Referenced by ns3::GnuplotHelper::PlotProbe(), and ns3::FileHelper::WriteProbe().
GetN()
std::size_t ns3::Config::MatchContainer::GetN (void) const
Returns
The number of items in the container
Definition at line 69 of file config.cc.
References m_objects, and NS_LOG_FUNCTION.
Referenced by ns3::RandomVariableStreamHelper::AssignStreams(), ns3::Config::ConfigImpl::Disconnect(), ns3::Config::ConfigImpl::DisconnectWithoutContext(), ns3::LteStatsCalculator::FindCellIdFromEnbRlcPath(), ns3::LteStatsCalculator::FindImsiFromEnbRlcPath(), ns3::LteStatsCalculator::FindImsiFromLteNetDevice(), ns3::LteStatsCalculator::FindImsiFromUePhy(), ns3::RadioEnvironmentMapHelper::Install(), ns3::GnuplotHelper::PlotProbe(), and ns3::FileHelper::WriteProbe().
GetPath()
std::string ns3::Config::MatchContainer::GetPath (void) const
Returns
The path used to perform the object matching.
Definition at line 87 of file config.cc.
References m_path, and NS_LOG_FUNCTION.
Set()
void ns3::Config::MatchContainer::Set (std::string name, const AttributeValue & value)
Parameters
[in] name Name of attribute to set
[in] value Value to set to the attribute
Set the specified attribute value to all the objects stored in this container. This method will raise a fatal error if no such attribute exists; use SetFailSafe if the absence of the attribute is to be permitted.
See also
ns3::Config::Set
Definition at line 94 of file config.cc.
References Begin(), End(), NS_LOG_FUNCTION, and ns3::ObjectBase::SetAttribute().
Referenced by ns3::Config::ConfigImpl::Set().
SetFailSafe()
bool ns3::Config::MatchContainer::SetFailSafe (std::string name, const AttributeValue & value)
Set the specified attribute value to all the objects stored in this container.
This method will return true if any attributes could be set, and false otherwise.
Returns
true if any attributes could be set.
Definition at line 105 of file config.cc.
References Begin(), End(), NS_LOG_FUNCTION, and ns3::ObjectBase::SetAttributeFailSafe().
Referenced by ns3::Config::ConfigImpl::SetFailSafe().
Member Data Documentation
m_contexts
std::vector<std::string> ns3::Config::MatchContainer::m_contexts private
The context for each object.
Definition at line 304 of file config.h.
Referenced by ConnectFailSafe(), Disconnect(), and GetMatchedPath().
m_objects
std::vector<Ptr<Object> > ns3::Config::MatchContainer::m_objects private
The list of objects in this container.
Definition at line 302 of file config.h.
Referenced by Begin(), ConnectFailSafe(), Disconnect(), End(), Get(), and GetN().
m_path
std::string ns3::Config::MatchContainer::m_path private
The path used to perform the object matching.
Definition at line 306 of file config.h.
Referenced by GetPath().
The documentation for this class was generated from the following files:
src/core/model/config.h
src/core/model/config.cc