ns-3: ns3::NscTcpL4Protocol Class Reference
ns3::NscTcpL4Protocol Class Reference
Internet » NscTcp
Nsc wrapper glue, to interface with the Ipv4 protocol underneath.
#include "nsc-tcp-l4-protocol.h"
Public Member Functions
NscTcpL4Protocol ()
virtual ~NscTcpL4Protocol ()
Ipv4EndPoint * Allocate (Ipv4Address address)
Allocate an IPv4 Endpoint.
Ipv4EndPoint * Allocate (Ptr< NetDevice > boundNetDevice, Ipv4Address address, uint16_t port)
Allocate an IPv4 Endpoint.
Ipv4EndPoint * Allocate (Ptr< NetDevice > boundNetDevice, Ipv4Address localAddress, uint16_t localPort, Ipv4Address peerAddress, uint16_t peerPort)
Allocate an IPv4 Endpoint.
Ipv4EndPoint * Allocate (Ptr< NetDevice > boundNetDevice, uint16_t port)
Allocate an IPv4 Endpoint.
Ipv4EndPoint * Allocate (void)
Allocate an IPv4 Endpoint.
Ptr< Socket > CreateSocket (void)
void DeAllocate (Ipv4EndPoint *endPoint)
Remove an IPv4 Endpoint.
virtual IpL4Protocol::DownTargetCallback GetDownTarget (void) const
This method allows a caller to get the current down target callback set for this L4 protocol (IPv4 case)
virtual IpL4Protocol::DownTargetCallback6 GetDownTarget6 (void) const
This method allows a caller to get the current down target callback set for this L4 protocol (IPv6 case)
std::string GetNscLibrary (void) const
Get the NSC library being used.
virtual int GetProtocolNumber (void) const
Returns the protocol number of this protocol.
virtual int GetVersion (void) const
Get the NSC version.
virtual IpL4Protocol::RxStatus Receive (Ptr< Packet > p, Ipv4Header const &header, Ptr< Ipv4Interface > incomingInterface)
Called from lower-level layers to send the packet up in the stack.
virtual IpL4Protocol::RxStatus Receive (Ptr< Packet > p, Ipv6Header const &header, Ptr< Ipv6Interface > interface)
Called from lower-level layers to send the packet up in the stack.
virtual void SetDownTarget (IpL4Protocol::DownTargetCallback cb)
This method allows a caller to set the current down target callback set for this L4 protocol (IPv4 case)
virtual void SetDownTarget6 (IpL4Protocol::DownTargetCallback6 cb)
This method allows a caller to set the current down target callback set for this L4 protocol (IPv6 case)
void SetNode (Ptr< Node > node)
Set node associated with this stack.
void SetNscLibrary (const std::string &lib)
Set the NSC library to be used.
Public Member Functions inherited from ns3::IpL4Protocol
virtual ~IpL4Protocol ()
virtual void ReceiveIcmp (Ipv4Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo, Ipv4Address payloadSource, Ipv4Address payloadDestination, const uint8_t payload[8])
Called from lower-level layers to send the ICMP packet up in the stack.
virtual void ReceiveIcmp (Ipv6Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo, Ipv6Address payloadSource, Ipv6Address payloadDestination, const uint8_t payload[8])
Called from lower-level layers to send the ICMPv6 packet up in the stack.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::IpL4Protocol
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static const uint8_t PROT_NUMBER = 6
protocol number (0x6)
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
virtual void NotifyNewAggregate ()
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
NscTcpL4Protocol (NscTcpL4Protocol const &)
Copy constructor.
void AddInterface (void)
Add an interface.
void gettime (unsigned int *sec, unsigned int *usec)
Called by the Linux stack RNG initialization.
NscTcpL4Protocol & operator= (NscTcpL4Protocol const &)
Copy constructor.
void send_callback (const void *data, int datalen)
Invoked by NSCs 'ethernet driver' to re-inject a packet into ns-3.
void SoftInterrupt (void)
Provide a "soft" interrupt to NSC.
void wakeup ()
Called by the NSC stack whenever something of interest has happened.
Private Attributes
void * m_dlopenHandle
dynamic library handle.
IpL4Protocol::DownTargetCallback m_downTarget
Callback to send packets over IPv4.
Ipv4EndPointDemux * m_endPoints
A list of IPv4 end points.
Ptr< Node > m_node
the node this stack is associated with
NscInterfaceImpl * m_nscInterface
the NSC Interface.
std::string m_nscLibrary
path to the NSC library.
INetStack * m_nscStack
the NSC stack.
std::vector< Ptr< NscTcpSocketImpl > > m_sockets
list of sockets
Timer m_softTimer
Soft interrupt timer.
Related Functions
(Note that these are not member functions.)
class NscInterfaceImpl
NscInterfaceImpl friend class.
class NscTcpSocketImpl
NscTcpSocketImpl friend class.
Additional Inherited Members
Public Types inherited from ns3::IpL4Protocol
typedef Callback< void, Ptr< Packet >, Ipv4Address, Ipv4Address, uint8_t, Ptr< Ipv4Route > > DownTargetCallback
callback to send packets over IPv4
typedef Callback< void, Ptr< Packet >, Ipv6Address, Ipv6Address, uint8_t, Ptr< Ipv6Route > > DownTargetCallback6
callback to send packets over IPv6
enum RxStatus { RX_OK , RX_CSUM_FAILED , RX_ENDPOINT_CLOSED , RX_ENDPOINT_UNREACH }
Rx status codes.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Nsc wrapper glue, to interface with the Ipv4 protocol underneath.
Definition at line 47 of file nsc-tcp-l4-protocol.h.
Constructor & Destructor Documentation
NscTcpL4Protocol() [1/2]
ns3::NscTcpL4Protocol::NscTcpL4Protocol ()
Definition at line 157 of file nsc-tcp-l4-protocol.cc.
References m_dlopenHandle, and NS_LOG_LOGIC.
~NscTcpL4Protocol()
ns3::NscTcpL4Protocol::~NscTcpL4Protocol () virtual
Definition at line 167 of file nsc-tcp-l4-protocol.cc.
References m_dlopenHandle, and NS_LOG_FUNCTION.
NscTcpL4Protocol() [2/2]
ns3::NscTcpL4Protocol::NscTcpL4Protocol (NscTcpL4Protocol const &) private
Copy constructor.
Defined and not implemented to avoid misuse
Member Function Documentation
AddInterface()
void ns3::NscTcpL4Protocol::AddInterface (void) private
Add an interface.
Actually NSC only supports one interface per node (Bug 1398)
Definition at line 450 of file nsc-tcp-l4-protocol.cc.
References INetStack::add_default_gateway(), ns3::Ipv4InterfaceAddress::GetLocal(), ns3::Ipv4InterfaceAddress::GetMask(), ns3::Object::GetObject(), INetStack::if_attach(), m_node, m_nscStack, NS_ASSERT_MSG, NS_LOG_LOGIC, ns3::Ipv4Address::Print(), and ns3::Ipv4Mask::Print().
Referenced by SetNode().
Allocate() [1/5]
Ipv4EndPoint * ns3::NscTcpL4Protocol::Allocate (Ipv4Address address)
Allocate an IPv4 Endpoint.
Parameters
address address to use
Returns
the Endpoint
Definition at line 305 of file nsc-tcp-l4-protocol.cc.
References first::address, ns3::Ipv4EndPointDemux::Allocate(), m_endPoints, and NS_LOG_FUNCTION.
Allocate() [2/5]
Ipv4EndPoint * ns3::NscTcpL4Protocol::Allocate (Ptr< NetDevice > boundNetDevice, Ipv4Address address, uint16_t port)
Allocate an IPv4 Endpoint.
Parameters
boundNetDevice Bound NetDevice (if any)
address address to use
port port to use
Returns
the Endpoint
Definition at line 319 of file nsc-tcp-l4-protocol.cc.
References first::address, ns3::Ipv4EndPointDemux::Allocate(), m_endPoints, NS_LOG_FUNCTION, and port.
Allocate() [3/5]
Ipv4EndPoint * ns3::NscTcpL4Protocol::Allocate (Ptr< NetDevice > boundNetDevice, Ipv4Address localAddress, uint16_t localPort, Ipv4Address peerAddress, uint16_t peerPort)
Allocate an IPv4 Endpoint.
Parameters
boundNetDevice Bound NetDevice (if any)
localAddress local address to use
localPort local port to use
peerAddress remote address to use
peerPort remote port to use
Returns
the Endpoint
Definition at line 326 of file nsc-tcp-l4-protocol.cc.
References ns3::Ipv4EndPointDemux::Allocate(), m_endPoints, and NS_LOG_FUNCTION.
Allocate() [4/5]
Ipv4EndPoint * ns3::NscTcpL4Protocol::Allocate (Ptr< NetDevice > boundNetDevice, uint16_t port)
Allocate an IPv4 Endpoint.
Parameters
boundNetDevice Bound NetDevice (if any)
port port to use
Returns
the Endpoint
Definition at line 312 of file nsc-tcp-l4-protocol.cc.
References ns3::Ipv4EndPointDemux::Allocate(), m_endPoints, NS_LOG_FUNCTION, and port.
Allocate() [5/5]
Ipv4EndPoint * ns3::NscTcpL4Protocol::Allocate (void)
Allocate an IPv4 Endpoint.
Returns
the Endpoint
Definition at line 298 of file nsc-tcp-l4-protocol.cc.
References ns3::Ipv4EndPointDemux::Allocate(), m_endPoints, and NS_LOG_FUNCTION.
CreateSocket()
Ptr< Socket > ns3::NscTcpL4Protocol::CreateSocket (void)
Returns
A smart Socket pointer to a NscTcpSocketImpl, allocated by this instance of the TCP protocol
Definition at line 286 of file nsc-tcp-l4-protocol.cc.
References m_node, m_sockets, and NS_LOG_FUNCTION.
DeAllocate()
void ns3::NscTcpL4Protocol::DeAllocate (Ipv4EndPoint * endPoint)
Remove an IPv4 Endpoint.
Parameters
endPoint the end point to remove
Definition at line 337 of file nsc-tcp-l4-protocol.cc.
References NS_LOG_FUNCTION.
DoDispose()
void ns3::NscTcpL4Protocol::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 262 of file nsc-tcp-l4-protocol.cc.
References ns3::Object::DoDispose(), m_downTarget, m_endPoints, m_node, m_nscInterface, m_sockets, NS_LOG_FUNCTION, and ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::Nullify().
GetDownTarget()
IpL4Protocol::DownTargetCallback ns3::NscTcpL4Protocol::GetDownTarget (void) const virtual
This method allows a caller to get the current down target callback set for this L4 protocol (IPv4 case)
Returns
current Callback for the L4 protocol
Implements ns3::IpL4Protocol.
Definition at line 510 of file nsc-tcp-l4-protocol.cc.
References m_downTarget.
GetDownTarget6()
IpL4Protocol::DownTargetCallback6 ns3::NscTcpL4Protocol::GetDownTarget6 (void) const virtual
This method allows a caller to get the current down target callback set for this L4 protocol (IPv6 case)
Returns
current Callback for the L4 protocol
Implements ns3::IpL4Protocol.
Definition at line 516 of file nsc-tcp-l4-protocol.cc.
GetNscLibrary()
std::string ns3::NscTcpL4Protocol::GetNscLibrary (void) const
Get the NSC library being used.
Returns
the library path
Definition at line 187 of file nsc-tcp-l4-protocol.cc.
References m_nscLibrary.
Referenced by GetTypeId().
GetProtocolNumber()
int ns3::NscTcpL4Protocol::GetProtocolNumber (void) const virtual
Returns the protocol number of this protocol.
Returns
the protocol number.
Implements ns3::IpL4Protocol.
Definition at line 251 of file nsc-tcp-l4-protocol.cc.
References PROT_NUMBER.
gettime()
void ns3::NscTcpL4Protocol::gettime (unsigned int * sec, unsigned int * usec) private
Called by the Linux stack RNG initialization.
Its also used by the cradle code to add a timestamp to printk/printf/debug output.
Parameters
sec seconds
usec microseconds
Definition at line 438 of file nsc-tcp-l4-protocol.cc.
References ns3::Time::GetMicroSeconds(), and ns3::Simulator::Now().
GetTypeId()
TypeId ns3::NscTcpL4Protocol::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 125 of file nsc-tcp-l4-protocol.cc.
References ns3::TypeId::ATTR_CONSTRUCT, ns3::TypeId::ATTR_GET, GetNscLibrary(), m_sockets, ns3::MakeObjectVectorAccessor(), ns3::MakeStringAccessor(), ns3::MakeStringChecker(), SetNscLibrary(), and ns3::TypeId::SetParent().
GetVersion()
int ns3::NscTcpL4Protocol::GetVersion (void) const virtual
Get the NSC version.
Returns
the NSC version
Definition at line 256 of file nsc-tcp-l4-protocol.cc.
NotifyNewAggregate()
void ns3::NscTcpL4Protocol::NotifyNewAggregate (void) protected virtual
Notify all Objects aggregated to this one of a new Object being aggregated.
This function must be implemented in the stack that needs to notify other stacks connected to the node of their presence in the node.
This method is invoked whenever two sets of Objects are aggregated together. It is invoked exactly once for each Object in both sets. This method can be overridden by subclasses who wish to be notified of aggregation events. These subclasses must chain up to their base class NotifyNewAggregate() method.
It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 228 of file nsc-tcp-l4-protocol.cc.
References ns3::Object::AggregateObject(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_downTarget, m_node, ns3::MakeCallback(), ns3::Object::NotifyNewAggregate(), ns3::Ipv4L3Protocol::Send(), SetDownTarget(), and SetNode().
operator=()
NscTcpL4Protocol& ns3::NscTcpL4Protocol::operator= (NscTcpL4Protocol const &) private
Copy constructor.
Defined and not implemented to avoid misuse
Returns
Receive() [1/2]
IpL4Protocol::RxStatus ns3::NscTcpL4Protocol::Receive (Ptr< Packet > p, Ipv4Header const & header, Ptr< Ipv4Interface > incomingInterface) virtual
Called from lower-level layers to send the packet up in the stack.
Parameters
p packet to forward up
header IPv4 Header information
incomingInterface the Ipv4Interface on which the packet arrived
Returns
Rx status code
Implements ns3::IpL4Protocol.
Definition at line 344 of file nsc-tcp-l4-protocol.cc.
References ns3::Packet::AddHeader(), ns3::Packet::CopyData(), data, ns3::Ipv4Header::EnableChecksum(), ns3::Ipv4Header::GetDestination(), ns3::Packet::GetSize(), ns3::Ipv4Header::GetSource(), INetStack::if_receive_packet(), m_nscStack, NS_LOG_FUNCTION, packetSize, PROT_NUMBER, ns3::IpL4Protocol::RX_OK, ns3::Ipv4Header::SetDestination(), ns3::Ipv4Header::SetPayloadSize(), ns3::Ipv4Header::SetProtocol(), ns3::Ipv4Header::SetSource(), ns3::Ipv4Header::SetTtl(), and wakeup().
Receive() [2/2]
IpL4Protocol::RxStatus ns3::NscTcpL4Protocol::Receive (Ptr< Packet > p, Ipv6Header const & header, Ptr< Ipv6Interface > incomingInterface) virtual
Called from lower-level layers to send the packet up in the stack.
Parameters
p packet to forward up
header IPv6 Header information
incomingInterface the Ipv6Interface on which the packet arrived
Returns
Rx status code
Implements ns3::IpL4Protocol.
Definition at line 381 of file nsc-tcp-l4-protocol.cc.
References ns3::IpL4Protocol::RX_ENDPOINT_UNREACH.
send_callback()
void ns3::NscTcpL4Protocol::send_callback (const void * data, int datalen) private
Invoked by NSCs 'ethernet driver' to re-inject a packet into ns-3.
A packet is an octet soup consisting of an IP Header, TCP Header and user payload, if any
Parameters
data the data
datalen the data length
Definition at line 393 of file nsc-tcp-l4-protocol.cc.
References data, ns3::Object::GetObject(), INetStack::if_send_finish(), m_downTarget, m_node, m_nscStack, NS_ASSERT, NS_ASSERT_MSG, and PROT_NUMBER.
SetDownTarget()
void ns3::NscTcpL4Protocol::SetDownTarget (IpL4Protocol::DownTargetCallback cb) virtual
This method allows a caller to set the current down target callback set for this L4 protocol (IPv4 case)
Parameters
cb current Callback for the L4 protocol
Implements ns3::IpL4Protocol.
Definition at line 499 of file nsc-tcp-l4-protocol.cc.
References m_downTarget.
Referenced by NotifyNewAggregate().
SetDownTarget6()
void ns3::NscTcpL4Protocol::SetDownTarget6 (IpL4Protocol::DownTargetCallback6 cb) virtual
This method allows a caller to set the current down target callback set for this L4 protocol (IPv6 case)
Parameters
cb current Callback for the L4 protocol
Implements ns3::IpL4Protocol.
Definition at line 505 of file nsc-tcp-l4-protocol.cc.
SetNode()
void ns3::NscTcpL4Protocol::SetNode (Ptr< Node > node)
Set node associated with this stack.
Parameters
node the node
Definition at line 192 of file nsc-tcp-l4-protocol.cc.
References AddInterface(), ns3::Object::AggregateObject(), ns3::external_rand(), INetStack::get_hz(), INetStack::init(), m_dlopenHandle, m_node, m_nscInterface, m_nscStack, m_softTimer, ns3::MilliSeconds(), NS_ASSERT, ns3::Timer::Schedule(), ns3::Simulator::ScheduleNow(), ns3::Timer::SetDelay(), ns3::Timer::SetFunction(), and SoftInterrupt().
Referenced by NotifyNewAggregate().
SetNscLibrary()
void ns3::NscTcpL4Protocol::SetNscLibrary (const std::string & lib)
Set the NSC library to be used.
Parameters
lib the library path
Definition at line 174 of file nsc-tcp-l4-protocol.cc.
References m_dlopenHandle, m_nscLibrary, NS_ASSERT, and NS_FATAL_ERROR.
Referenced by GetTypeId().
SoftInterrupt()
void ns3::NscTcpL4Protocol::SoftInterrupt (void) private
Provide a "soft" interrupt to NSC.
Definition at line 386 of file nsc-tcp-l4-protocol.cc.
References INetStack::increment_ticks(), m_nscStack, m_softTimer, ns3::Timer::Schedule(), and INetStack::timer_interrupt().
Referenced by SetNode().
wakeup()
void ns3::NscTcpL4Protocol::wakeup () private
Called by the NSC stack whenever something of interest has happened.
Examples: when data arrives on a socket, a listen socket has a new connection pending, etc.
Definition at line 424 of file nsc-tcp-l4-protocol.cc.
References ns3::Ipv4EndPointDemux::GetAllEndPoints(), and m_endPoints.
Referenced by Receive().
Friends And Related Function Documentation
NscInterfaceImpl
friend class NscInterfaceImpl friend
NscInterfaceImpl friend class.
Definition at line 212 of file nsc-tcp-l4-protocol.h.
NscTcpSocketImpl
friend class NscTcpSocketImpl friend
NscTcpSocketImpl friend class.
Definition at line 217 of file nsc-tcp-l4-protocol.h.
Member Data Documentation
m_dlopenHandle
void* ns3::NscTcpL4Protocol::m_dlopenHandle private
dynamic library handle.
Definition at line 223 of file nsc-tcp-l4-protocol.h.
Referenced by NscTcpL4Protocol(), ~NscTcpL4Protocol(), SetNode(), and SetNscLibrary().
m_downTarget
IpL4Protocol::DownTargetCallback ns3::NscTcpL4Protocol::m_downTarget private
Callback to send packets over IPv4.
Definition at line 227 of file nsc-tcp-l4-protocol.h.
Referenced by DoDispose(), GetDownTarget(), NotifyNewAggregate(), send_callback(), and SetDownTarget().
m_endPoints
Ipv4EndPointDemux* ns3::NscTcpL4Protocol::m_endPoints private
A list of IPv4 end points.
Definition at line 220 of file nsc-tcp-l4-protocol.h.
Referenced by Allocate(), DoDispose(), and wakeup().
m_node
Ptr<Node> ns3::NscTcpL4Protocol::m_node private
the node this stack is associated with
Definition at line 219 of file nsc-tcp-l4-protocol.h.
Referenced by AddInterface(), CreateSocket(), DoDispose(), NotifyNewAggregate(), send_callback(), and SetNode().
m_nscInterface
NscInterfaceImpl* ns3::NscTcpL4Protocol::m_nscInterface private
the NSC Interface.
Definition at line 222 of file nsc-tcp-l4-protocol.h.
Referenced by DoDispose(), and SetNode().
m_nscLibrary
std::string ns3::NscTcpL4Protocol::m_nscLibrary private
path to the NSC library.
Definition at line 224 of file nsc-tcp-l4-protocol.h.
Referenced by GetNscLibrary(), and SetNscLibrary().
m_nscStack
INetStack* ns3::NscTcpL4Protocol::m_nscStack private
the NSC stack.
Definition at line 221 of file nsc-tcp-l4-protocol.h.
Referenced by AddInterface(), Receive(), send_callback(), SetNode(), and SoftInterrupt().
m_sockets
std::vector<Ptr<NscTcpSocketImpl> > ns3::NscTcpL4Protocol::m_sockets private
list of sockets
Definition at line 226 of file nsc-tcp-l4-protocol.h.
Referenced by CreateSocket(), DoDispose(), and GetTypeId().
m_softTimer
Timer ns3::NscTcpL4Protocol::m_softTimer private
Soft interrupt timer.
Definition at line 225 of file nsc-tcp-l4-protocol.h.
Referenced by SetNode(), and SoftInterrupt().
PROT_NUMBER
const uint8_t ns3::NscTcpL4Protocol::PROT_NUMBER = 6 static
protocol number (0x6)
Definition at line 49 of file nsc-tcp-l4-protocol.h.
Referenced by GetProtocolNumber(), Receive(), and send_callback().
The documentation for this class was generated from the following files:
src/internet/model/nsc-tcp-l4-protocol.h
src/internet/model/nsc-tcp-l4-protocol.cc