ns-3: ns3::LteUePhySapProvider Class Reference
ns3::LteUePhySapProvider Class Reference abstract
Service Access Point (SAP) offered by the UE-PHY to the UE-MAC.
#include "lte-ue-phy-sap.h"
Public Member Functions
virtual ~LteUePhySapProvider ()
virtual void NotifyConnectionSuccessful ()=0
Notify PHY about the successful RRC connection establishment.
virtual void SendLteControlMessage (Ptr< LteControlMessage > msg)=0
Send SendLteControlMessage (PDCCH map, CQI feedbacks) using the ideal control channel.
virtual void SendMacPdu (Ptr< Packet > p)=0
Send the MAC PDU to the channel.
virtual void SendRachPreamble (uint32_t prachId, uint32_t raRnti)=0
Send a preamble on the PRACH.
Detailed Description
Service Access Point (SAP) offered by the UE-PHY to the UE-MAC.
This is the PHY SAP Provider, i.e., the part of the SAP that contains the PHY methods called by the MAC
Definition at line 38 of file lte-ue-phy-sap.h.
Constructor & Destructor Documentation
~LteUePhySapProvider()
ns3::LteUePhySapProvider::~LteUePhySapProvider () virtual
Definition at line 28 of file lte-ue-phy-sap.cc.
Member Function Documentation
NotifyConnectionSuccessful()
virtual void ns3::LteUePhySapProvider::NotifyConnectionSuccessful () pure virtual
Notify PHY about the successful RRC connection establishment.
Implemented in ns3::UeMemberLteUePhySapProvider.
Referenced by ns3::LteUeMac::DoNotifyConnectionSuccessful().
SendLteControlMessage()
virtual void ns3::LteUePhySapProvider::SendLteControlMessage (Ptr< LteControlMessage > msg) pure virtual
Send SendLteControlMessage (PDCCH map, CQI feedbacks) using the ideal control channel.
Parameters
msg the Ideal Control Message to send
Implemented in ns3::UeMemberLteUePhySapProvider.
Referenced by ns3::LteUeMac::SendReportBufferStatus().
SendMacPdu()
virtual void ns3::LteUePhySapProvider::SendMacPdu (Ptr< Packet > p) pure virtual
Send the MAC PDU to the channel.
Parameters
p the MAC PDU to send
Returns
true if
Implemented in ns3::UeMemberLteUePhySapProvider.
Referenced by ns3::LteUeMac::DoReceiveLteControlMessage(), and ns3::LteUeMac::DoTransmitPdu().
SendRachPreamble()
virtual void ns3::LteUePhySapProvider::SendRachPreamble (uint32_t prachId, uint32_t raRnti) pure virtual
Send a preamble on the PRACH.
Parameters
prachId the ID of the preamble
raRnti the RA RNTI
Implemented in ns3::UeMemberLteUePhySapProvider.
Referenced by ns3::LteUeMac::SendRaPreamble().
The documentation for this class was generated from the following files:
src/lte/model/lte-ue-phy-sap.h
src/lte/model/lte-ue-phy-sap.cc