ns-3: ns3::SpectrumPhyHelper Class Reference
ns3::SpectrumPhyHelper Class Reference
Spectrum Models
Create and configure several SpectrumPhy instances and connect them to a channel.
#include "spectrum-helper.h"
Public Member Functions
Ptr< SpectrumPhy > Create (Ptr< Node > node, Ptr< NetDevice > device) const
void SetChannel (Ptr< SpectrumChannel > channel)
set the channel that will be used by SpectrumPhy instances created by this helper
void SetChannel (std::string channelName)
set the channel that will be used by SpectrumPhy instances created by this helper
void SetPhy (std::string name, std::string n0="", const AttributeValue &v0=EmptyAttributeValue(), std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue(), std::string n6="", const AttributeValue &v6=EmptyAttributeValue(), std::string n7="", const AttributeValue &v7=EmptyAttributeValue())
void SetPhyAttribute (std::string name, const AttributeValue &v)
Private Attributes
Ptr< SpectrumChannel > m_channel
Channel.
ObjectFactory m_phy
Object factory for the phy objects.
Detailed Description
Create and configure several SpectrumPhy instances and connect them to a channel.
Definition at line 214 of file spectrum-helper.h.
Member Function Documentation
Create()
Ptr< SpectrumPhy > ns3::SpectrumPhyHelper::Create (Ptr< Node > node, Ptr< NetDevice > device) const
Parameters
node
device
Returns
a newly created SpectrumPhy instance
Definition at line 213 of file spectrum-helper.cc.
References ns3::ObjectFactory::Create(), ns3::Object::GetObject(), m_channel, m_phy, NS_ASSERT, and third::phy.
SetChannel() [1/2]
void ns3::SpectrumPhyHelper::SetChannel (Ptr< SpectrumChannel > channel)
set the channel that will be used by SpectrumPhy instances created by this helper
Parameters
channel
Definition at line 193 of file spectrum-helper.cc.
References third::channel, and m_channel.
SetChannel() [2/2]
void ns3::SpectrumPhyHelper::SetChannel (std::string channelName)
set the channel that will be used by SpectrumPhy instances created by this helper
Parameters
channelName
Definition at line 199 of file spectrum-helper.cc.
References third::channel, and m_channel.
SetPhy()
void ns3::SpectrumPhyHelper::SetPhy (std::string name, std::string n0 = "", const AttributeValue & v0 = EmptyAttributeValue (), std::string n1 = "", const AttributeValue & v1 = EmptyAttributeValue (), std::string n2 = "", const AttributeValue & v2 = EmptyAttributeValue (), std::string n3 = "", const AttributeValue & v3 = EmptyAttributeValue (), std::string n4 = "", const AttributeValue & v4 = EmptyAttributeValue (), std::string n5 = "", const AttributeValue & v5 = EmptyAttributeValue (), std::string n6 = "", const AttributeValue & v6 = EmptyAttributeValue (), std::string n7 = "", const AttributeValue & v7 = EmptyAttributeValue ())
Parameters
name the type of SpectrumPhy to use
n0 the name of the attribute to set
v0 the value of the attribute to set
n1 the name of the attribute to set
v1 the value of the attribute to set
n2 the name of the attribute to set
v2 the value of the attribute to set
n3 the name of the attribute to set
v3 the value of the attribute to set
n4 the name of the attribute to set
v4 the value of the attribute to set
n5 the name of the attribute to set
v5 the value of the attribute to set
n6 the name of the attribute to set
v6 the value of the attribute to set
n7 the name of the attribute to set
v7 the value of the attribute to set
Definition at line 169 of file spectrum-helper.cc.
References m_phy, ns3::ObjectFactory::Set(), and ns3::ObjectFactory::SetTypeId().
SetPhyAttribute()
void ns3::SpectrumPhyHelper::SetPhyAttribute (std::string name, const AttributeValue & v)
Parameters
name the name of the attribute to set
v the value of the attribute
Set an attribute of the SpectrumPhy instances to be created
Definition at line 206 of file spectrum-helper.cc.
References m_phy, and ns3::ObjectFactory::Set().
Member Data Documentation
m_channel
Ptr<SpectrumChannel> ns3::SpectrumPhyHelper::m_channel private
Channel.
Definition at line 281 of file spectrum-helper.h.
Referenced by Create(), and SetChannel().
m_phy
ObjectFactory ns3::SpectrumPhyHelper::m_phy private
Object factory for the phy objects.
Definition at line 280 of file spectrum-helper.h.
Referenced by Create(), SetPhy(), and SetPhyAttribute().
The documentation for this class was generated from the following files:
src/spectrum/helper/spectrum-helper.h
src/spectrum/helper/spectrum-helper.cc