ns-3: ns3::olsr::Bug780Test Class Reference
ns3::olsr::Bug780Test Class Reference
OLSR Routing » olsr module tests | Test suites
See Bug 780
#include "bug780-test.h"
Public Member Functions
Bug780Test ()
~Bug780Test ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CreateNodes ()
Create & configure test network.
void DoRun ()
Implementation to actually run this TestCase.
void Receive (Ptr< Socket > socket)
Receive echo reply.
void SendPing ()
Send one ping.
Private Attributes
uint16_t m_recvCount
Received ECHO Reply counter.
uint16_t m_seq
Sequence number.
Ptr< Socket > m_socket
Socket.
const Time m_time
Total simulation time.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
See Bug 780
Definition at line 35 of file bug780-test.h.
Constructor & Destructor Documentation
Bug780Test()
ns3::olsr::Bug780Test::Bug780Test ()
Definition at line 45 of file bug780-test.cc.
~Bug780Test()
ns3::olsr::Bug780Test::~Bug780Test ()
Definition at line 51 of file bug780-test.cc.
Member Function Documentation
CreateNodes()
void ns3::olsr::Bug780Test::CreateNodes (void) private
Create & configure test network.
Definition at line 71 of file bug780-test.cc.
References ns3::Ipv4AddressHelper::Assign(), ns3::Socket::Bind(), ns3::SimpleChannel::BlackList(), ns3::Socket::Connect(), ns3::NodeContainer::Create(), ns3::Socket::CreateSocket(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::Ipv4Address::GetAny(), ns3::SimpleNetDeviceHelper::Install(), ns3::InternetStackHelper::Install(), ns3::TypeId::LookupByName(), m_socket, ns3::MakeCallback(), NS_TEST_EXPECT_MSG_EQ, Receive(), ns3::Simulator::Schedule(), ns3::Seconds(), SendPing(), ns3::ObjectBase::SetAttribute(), ns3::Ipv4AddressHelper::SetBase(), ns3::SimpleNetDeviceHelper::SetChannelAttribute(), ns3::SimpleNetDeviceHelper::SetDeviceAttribute(), ns3::Socket::SetRecvCallback(), and ns3::InternetStackHelper::SetRoutingHelper().
Referenced by DoRun().
DoRun()
void ns3::olsr::Bug780Test::DoRun () private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 56 of file bug780-test.cc.
References CreateNodes(), ns3::Simulator::Destroy(), m_recvCount, m_time, NS_TEST_EXPECT_MSG_EQ, ns3::Simulator::Run(), ns3::RngSeedManager::SetRun(), ns3::RngSeedManager::SetSeed(), and ns3::Simulator::Stop().
Receive()
void ns3::olsr::Bug780Test::Receive (Ptr< Socket > socket) private
Receive echo reply.
Parameters
socket the socket
Definition at line 145 of file bug780-test.cc.
References ns3::InetSocketAddress::ConvertFrom(), ns3::InetSocketAddress::GetPort(), ns3::Ipv4Header::GetProtocol(), ns3::Socket::GetRxAvailable(), ns3::Icmpv4Header::GetType(), ns3::Icmpv4Header::ICMPV4_ECHO_REPLY, ns3::InetSocketAddress::IsMatchingType(), m_recvCount, m_socket, NS_ASSERT, ns3::Socket::RecvFrom(), and ns3::Packet::RemoveHeader().
Referenced by CreateNodes().
SendPing()
void ns3::olsr::Bug780Test::SendPing () private
Send one ping.
Definition at line 116 of file bug780-test.cc.
References ns3::Packet::AddHeader(), ns3::Node::ChecksumEnabled(), ns3::Icmpv4Header::EnableChecksum(), ns3::Icmpv4Header::ICMPV4_ECHO, m_seq, m_socket, m_time, ns3::Simulator::Now(), ns3::Simulator::Schedule(), ns3::Seconds(), ns3::Socket::Send(), ns3::Icmpv4Header::SetCode(), ns3::Icmpv4Echo::SetData(), ns3::Icmpv4Echo::SetIdentifier(), ns3::Icmpv4Echo::SetSequenceNumber(), and ns3::Icmpv4Header::SetType().
Referenced by CreateNodes().
Member Data Documentation
m_recvCount
uint16_t ns3::olsr::Bug780Test::m_recvCount private
Received ECHO Reply counter.
Definition at line 58 of file bug780-test.h.
Referenced by DoRun(), and Receive().
m_seq
uint16_t ns3::olsr::Bug780Test::m_seq private
Sequence number.
Definition at line 56 of file bug780-test.h.
Referenced by SendPing().
m_socket
Ptr<Socket> ns3::olsr::Bug780Test::m_socket private
Socket.
Definition at line 54 of file bug780-test.h.
Referenced by CreateNodes(), Receive(), and SendPing().
m_time
const Time ns3::olsr::Bug780Test::m_time private
Total simulation time.
Definition at line 42 of file bug780-test.h.
Referenced by DoRun(), and SendPing().
The documentation for this class was generated from the following files:
src/olsr/test/bug780-test.h
src/olsr/test/bug780-test.cc