ns-3: ThreeGppV2vHighwayLosNlosvChCondModelTestCase Class Reference
ThreeGppV2vHighwayLosNlosvChCondModelTestCase Class Reference
Test case for the 3GPP V2V Highway channel condition models (probabilistic model for LOS/NLOSv states).
Classes
struct TestVector
Struct containing the parameters for each test.
Public Member Functions
ThreeGppV2vHighwayLosNlosvChCondModelTestCase ()
Constructor.
virtual ~ThreeGppV2vHighwayLosNlosvChCondModelTestCase ()
Destructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Builds the simulation scenario and perform the tests.
void EvaluateChannelCondition (Ptr< MobilityModel > a, Ptr< MobilityModel > b)
Evaluates the channel condition between two nodes by calling the method GetChannelCondition on m_condModel.
Private Attributes
Ptr< ThreeGppV2vHighwayChannelConditionModel > m_condModel
the channel condition model
uint64_t m_numLos {0}
the number of LOS occurrences
TestVectors< TestVector > m_testVectors
array containing all the test vectors
double m_tolerance
tolerance
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test case for the 3GPP V2V Highway channel condition models (probabilistic model for LOS/NLOSv states).
It determines the channel condition multiple times, estimates the LOS probability and compares it with the value given by the formulas in 3GPP TR 37.885, Table 6.2-1. Methodology from channel-condition-model- test-suite.cc is used.
Definition at line 334 of file three-gpp-v2v-channel-condition-model-test.cc.
Constructor & Destructor Documentation
ThreeGppV2vHighwayLosNlosvChCondModelTestCase()
ThreeGppV2vHighwayLosNlosvChCondModelTestCase::ThreeGppV2vHighwayLosNlosvChCondModelTestCase ()
Constructor.
Definition at line 379 of file three-gpp-v2v-channel-condition-model-test.cc.
~ThreeGppV2vHighwayLosNlosvChCondModelTestCase()
ThreeGppV2vHighwayLosNlosvChCondModelTestCase::~ThreeGppV2vHighwayLosNlosvChCondModelTestCase () virtual
Destructor.
Definition at line 385 of file three-gpp-v2v-channel-condition-model-test.cc.
Member Function Documentation
DoRun()
void ThreeGppV2vHighwayLosNlosvChCondModelTestCase::DoRun (void) private virtual
Builds the simulation scenario and perform the tests.
Implements ns3::TestCase.
Definition at line 399 of file three-gpp-v2v-channel-condition-model-test.cc.
References ns3::ThreeGppChannelConditionModel::AssignStreams(), ns3::ObjectFactory::Create(), EvaluateChannelCondition(), m_condModel, m_numLos, ThreeGppV2vHighwayLosNlosvChCondModelTestCase::TestVector::m_pLos, ThreeGppV2vHighwayLosNlosvChCondModelTestCase::TestVector::m_positionA, ThreeGppV2vHighwayLosNlosvChCondModelTestCase::TestVector::m_positionB, m_testVectors, m_tolerance, ThreeGppV2vHighwayLosNlosvChCondModelTestCase::TestVector::m_typeId, max, ns3::MilliSeconds(), min, first::nodes, NS_LOG_DEBUG, NS_TEST_EXPECT_MSG_EQ_TOL, ns3::ObjectBase::SetAttribute(), ns3::MobilityModel::SetPosition(), and ns3::ObjectFactory::SetTypeId().
EvaluateChannelCondition()
void ThreeGppV2vHighwayLosNlosvChCondModelTestCase::EvaluateChannelCondition (Ptr< MobilityModel > a, Ptr< MobilityModel > b) private
Evaluates the channel condition between two nodes by calling the method GetChannelCondition on m_condModel.
If the channel condition is LOS it increments m_numLos
Parameters
a the mobility model of the first node
b the mobility model of the second node
Definition at line 389 of file three-gpp-v2v-channel-condition-model-test.cc.
References ns3::ThreeGppChannelConditionModel::GetChannelCondition(), m_condModel, and m_numLos.
Referenced by DoRun().
Member Data Documentation
m_condModel
Ptr<ThreeGppV2vHighwayChannelConditionModel> ThreeGppV2vHighwayLosNlosvChCondModelTestCase::m_condModel private
the channel condition model
Definition at line 374 of file three-gpp-v2v-channel-condition-model-test.cc.
Referenced by DoRun(), and EvaluateChannelCondition().
m_numLos
uint64_t ThreeGppV2vHighwayLosNlosvChCondModelTestCase::m_numLos {0} private
the number of LOS occurrences
Definition at line 375 of file three-gpp-v2v-channel-condition-model-test.cc.
Referenced by DoRun(), and EvaluateChannelCondition().
m_testVectors
TestVectors<TestVector> ThreeGppV2vHighwayLosNlosvChCondModelTestCase::m_testVectors private
array containing all the test vectors
Definition at line 373 of file three-gpp-v2v-channel-condition-model-test.cc.
Referenced by DoRun().
m_tolerance
double ThreeGppV2vHighwayLosNlosvChCondModelTestCase::m_tolerance private
tolerance
Definition at line 376 of file three-gpp-v2v-channel-condition-model-test.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/buildings/test/three-gpp-v2v-channel-condition-model-test.cc