ns-3: ns3::dsr::DsrRouting Class Reference
ns3::dsr::DsrRouting Class Reference
Dsr Routing base.
#include "dsr-routing.h"
Public Member Functions
DsrRouting ()
Constructor.
virtual ~DsrRouting ()
Destructor.
uint16_t AddAckReqHeader (Ptr< Packet > &packet, Ipv4Address nextHop)
This function is called to add ack request header for network acknowledgement.
bool AddRoute (DsrRouteCacheEntry &rt)
bool AddRoute_Link (DsrRouteCacheEntry::IP_VECTOR nodelist, Ipv4Address source)
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
void CallCancelPacketTimer (uint16_t ackId, Ipv4Header const &ipv4Header, Ipv4Address realSrc, Ipv4Address realDst)
Call the cancel packet retransmission timer function.
void CancelLinkPacketTimer (DsrMaintainBuffEntry &mb)
Cancel the link packet retransmission timer for a specific maintenance entry.
void CancelNetworkPacketTimer (DsrMaintainBuffEntry &mb)
Cancel the network packet retransmission timer for a specific maintenance entry.
void CancelPacketAllTimer (DsrMaintainBuffEntry &mb)
Cancel all the packet timers.
void CancelPacketTimerNextHop (Ipv4Address nextHop, uint8_t protocol)
Cancel the packet retransmission timer for a all maintenance entries with nextHop address.
void CancelPassivePacketTimer (DsrMaintainBuffEntry &mb)
Cancel the passive packet retransmission timer for a specific maintenance entry.
bool CancelPassiveTimer (Ptr< Packet > packet, Ipv4Address source, Ipv4Address destination, uint8_t segsLeft)
Cancel the passive timer.
void CancelRreqTimer (Ipv4Address dst, bool isRemove)
Cancel the route request timer.
void CheckSendBuffer ()
Check the send buffer of packets with route when send buffer timer expire.
void DeleteAllRoutesIncludeLink (Ipv4Address errorSrc, Ipv4Address unreachNode, Ipv4Address node)
bool FindSourceEntry (Ipv4Address src, Ipv4Address dst, uint16_t id)
void ForwardErrPacket (DsrOptionRerrUnreachHeader &rerr, DsrOptionSRHeader &sourceRoute, Ipv4Address nextHop, uint8_t protocol, Ptr< Ipv4Route > route)
This function is responsible for forwarding error packets along the route.
void ForwardPacket (Ptr< const Packet > packet, DsrOptionSRHeader &sourceRoute, Ipv4Header const &ipv4Header, Ipv4Address source, Ipv4Address destination, Ipv4Address targetAddress, uint8_t protocol, Ptr< Ipv4Route > route)
Forward the packet using the route saved in the source route option header.
IpL4Protocol::DownTargetCallback GetDownTarget (void) const
This method allows a caller to get the current down target callback set for this L4 protocol (IPv4 case)
IpL4Protocol::DownTargetCallback6 GetDownTarget6 (void) const
This method allows a caller to get the current down target callback set for this L4 protocol (IPv6 case)
std::vector< std::string > GetElementsFromContext (std::string context)
Get the elements from the tracing context.
uint16_t GetIDfromIP (Ipv4Address address)
Get the node id from ip address.
Ipv4Address GetIPfromID (uint16_t id)
Get the ip address from id.
Ipv4Address GetIPfromMAC (Mac48Address address)
Get the Ip address from mac address.
Ptr< NetDevice > GetNetDeviceFromContext (std::string context)
Get the netdevice from the context.
Ptr< Node > GetNode () const
Get the node.
Ptr< Node > GetNodeWithAddress (Ipv4Address ipv4Address)
Get the node with give ip address.
Ptr< dsr::DsrOptions > GetOption (int optionNumber)
Get the option corresponding to optionNumber.
Ptr< dsr::DsrPassiveBuffer > GetPassiveBuffer () const
Get the passive buffer.
uint32_t GetPriority (DsrMessageType messageType)
Set the priority of the packet in network queue.
int GetProtocolNumber (void) const
Get the dsr protocol number.
Ptr< dsr::DsrRreqTable > GetRequestTable () const
Get the request table.
Ptr< dsr::DsrRouteCache > GetRouteCache () const
Get the route cache.
void IncreaseRetransTimer ()
This function is called to increase the retransmission timer for data packet in the network queue.
void Insert (Ptr< dsr::DsrOptions > option)
Insert a new Dsr Option.
bool IsLinkCache ()
functions used to direct to route cache
void LinkScheduleTimerExpire (DsrMaintainBuffEntry &mb, uint8_t protocol)
This function deals with packet retransmission timer expire using link acknowledgment.
bool LookupRoute (Ipv4Address id, DsrRouteCacheEntry &rt)
void NetworkScheduleTimerExpire (DsrMaintainBuffEntry &mb, uint8_t protocol)
This function deals with packet retransmission timer expire using network acknowledgment.
void PacketNewRoute (Ptr< Packet > packet, Ipv4Address source, Ipv4Address destination, uint8_t protocol)
When route vector corrupted, originate a new packet, normally not happening.
bool PassiveEntryCheck (Ptr< Packet > packet, Ipv4Address source, Ipv4Address destination, uint8_t segsLeft, uint16_t fragmentOffset, uint16_t identification, bool saveEntry)
Find the same passive entry.
void PassiveScheduleTimerExpire (DsrMaintainBuffEntry &mb, uint8_t protocol)
This function deals with packet retransmission timer expire using passive acknowledgment.
void PrintVector (std::vector< Ipv4Address > &vec)
Print the route vector.
void PriorityScheduler (uint32_t priority, bool continueWithFirst)
This function is called to schedule sending packets from the network queue by priority.
uint8_t Process (Ptr< Packet > &packet, Ipv4Header const &ipv4Header, Ipv4Address dst, uint8_t *nextHeader, uint8_t protocol, bool &isDropped)
Process method Called from Ipv4L3Protocol::Receive.
virtual enum IpL4Protocol::RxStatus Receive (Ptr< Packet > p, Ipv4Header const &header, Ptr< Ipv4Interface > incomingInterface)
virtual enum IpL4Protocol::RxStatus Receive (Ptr< Packet > p, Ipv6Header const &header, Ptr< Ipv6Interface > incomingInterface)
void RouteRequestTimerExpire (Ptr< Packet > packet, std::vector< Ipv4Address > address, uint32_t requestId, uint8_t protocol)
Handle route discovery timer.
void SalvagePacket (Ptr< const Packet > packet, Ipv4Address source, Ipv4Address dst, uint8_t protocol)
Salvage the packet which has been transmitted for 3 times.
void ScheduleCachedReply (Ptr< Packet > packet, Ipv4Address source, Ipv4Address destination, Ptr< Ipv4Route > route, double hops)
Schedule the cached reply to a random start time to avoid possible route reply storm.
void ScheduleInitialReply (Ptr< Packet > packet, Ipv4Address source, Ipv4Address nextHop, Ptr< Ipv4Route > route)
this is a generating the initial route reply from the destination address, a random delay time [0, m_broadcastJitter] is used before unicasting back the route reply packet
void ScheduleInterRequest (Ptr< Packet > packet)
Schedule the intermediate route request.
void ScheduleLinkPacketRetry (DsrMaintainBuffEntry &mb, uint8_t protocol)
Schedule the packet retransmission based on link-layer acknowledgment.
void ScheduleNetworkPacketRetry (DsrMaintainBuffEntry &mb, bool isFirst, uint8_t protocol)
Schedule the packet retransmission based on network layer acknowledgment.
void SchedulePassivePacketRetry (DsrMaintainBuffEntry &mb, uint8_t protocol)
Schedule the packet retransmission based on passive acknowledgment.
void Scheduler (uint32_t priority)
This function is called to schedule sending packets from the network queue.
void ScheduleRreqRetry (Ptr< Packet > packet, std::vector< Ipv4Address > address, bool nonProp, uint32_t requestId, uint8_t protocol)
Schedule the route request retry.
Ipv4Address SearchNextHop (Ipv4Address ipv4Address, std::vector< Ipv4Address > &vec)
Get the next hop of the route.
void Send (Ptr< Packet > packet, Ipv4Address source, Ipv4Address destination, uint8_t protocol, Ptr< Ipv4Route > route)
This function is called by higher layer protocol when sending packets.
void SendAck (uint16_t ackId, Ipv4Address destination, Ipv4Address realSrc, Ipv4Address realDst, uint8_t protocol, Ptr< Ipv4Route > route)
Send network layer acknowledgment back to the earlier hop to notify the receipt of data packet.
void SendBuffTimerExpire ()
The send buffer timer expire.
void SendErrorRequest (DsrOptionRerrUnreachHeader &rerr, uint8_t protocol)
Send the error request packet.
void SendGratuitousReply (Ipv4Address replyTo, Ipv4Address replyFrom, std::vector< Ipv4Address > &nodeList, uint8_t protocol)
Send the gratuitous reply.
void SendInitialRequest (Ipv4Address source, Ipv4Address destination, uint8_t protocol)
Broadcast the route request packet in subnet.
void SendPacket (Ptr< Packet > packet, Ipv4Address source, Ipv4Address nextHop, uint8_t protocol)
This function is called by when really sending out the packet.
void SendPacketFromBuffer (DsrOptionSRHeader const &sourceRoute, Ipv4Address nextHop, uint8_t protocol)
This function is responsible for sending out data packets when have route, if no route found, it will cache the packet and send out route requests.
bool SendRealDown (DsrNetworkQueueEntry &newEntry)
This function is called to send packets down stack.
void SendReply (Ptr< Packet > packet, Ipv4Address source, Ipv4Address nextHop, Ptr< Ipv4Route > route)
Send the route reply back to the request originator with the cumulated route.
void SendRequest (Ptr< Packet > packet, Ipv4Address source)
Forward the route request if the node is not the destination.
void SendUnreachError (Ipv4Address unreachNode, Ipv4Address destination, Ipv4Address originalDst, uint8_t salvage, uint8_t protocol)
This function is responsible for sending error packets in case of break link to next hop.
void SetDownTarget (IpL4Protocol::DownTargetCallback callback)
This method allows a caller to set the current down target callback set for this L4 protocol (IPv4 case)
void SetDownTarget6 (IpL4Protocol::DownTargetCallback6 callback)
This method allows a caller to set the current down target callback set for this L4 protocol (IPv6 case)
void SetNode (Ptr< Node > node)
Set the node.
void SetPassiveBuffer (Ptr< dsr::DsrPassiveBuffer > r)
Set the node.
void SetRequestTable (Ptr< dsr::DsrRreqTable > r)
Set the node.
Ptr< Ipv4Route > SetRoute (Ipv4Address nextHop, Ipv4Address srcAddress)
Set the route to use for data packets, used by the option headers when sending data/control packets.
void SetRouteCache (Ptr< dsr::DsrRouteCache > r)
Set the route cache.
bool UpdateRouteEntry (Ipv4Address dst)
void UseExtends (DsrRouteCacheEntry::IP_VECTOR rt)
Public Member Functions inherited from ns3::IpL4Protocol
virtual ~IpL4Protocol ()
virtual void ReceiveIcmp (Ipv4Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo, Ipv4Address payloadSource, Ipv4Address payloadDestination, const uint8_t payload[8])
Called from lower-level layers to send the ICMP packet up in the stack.
virtual void ReceiveIcmp (Ipv6Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo, Ipv6Address payloadSource, Ipv6Address payloadDestination, const uint8_t payload[8])
Called from lower-level layers to send the ICMPv6 packet up in the stack.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::IpL4Protocol
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static const uint8_t PROT_NUMBER = 48
Define the dsr protocol number.
Protected Member Functions
virtual void DoDispose (void)
Drop trace callback.
virtual void NotifyNewAggregate ()
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes
TracedCallback< Ptr< const Packet > > m_dropTrace
The trace for drop, receive and send data packets.
TracedCallback< const DsrOptionSRHeader & > m_txPacketTrace
packet trace callback
Private Types
typedef std::list< Ptr< DsrOptions > > DsrOptionList_t
Define the list to hold DSR options.
Private Member Functions
bool PromiscReceive (Ptr< NetDevice > device, Ptr< const Packet > packet, uint16_t protocol, const Address &from, const Address &to, NetDevice::PacketType packetType)
Promiscuous receive data packets destined to some other node.
void SendRerrWhenBreaksLinkToNextHop (Ipv4Address nextHop, uint8_t protocol)
Send the route error message when the link breaks to the next hop.
void Start ()
Private Attributes
uint16_t m_ackId
The ack id assigned to each acknowledge.
std::vector< Ipv4Address > m_addresses
The bind ipv4 addresses with next hop, src, destination address in sequence.
std::map< NetworkKey, uint32_t > m_addressForwardCnt
Map network key + forward counts.
std::map< NetworkKey, Timer > m_addressForwardTimer
Map network key + forward timer.
std::map< Ipv4Address, Timer > m_addressReqTimer
Map IP address + RREQ timer.
Time m_blacklistTimeout
The black list time out.
Ipv4Address m_broadcast
The broadcast IP address.
uint32_t m_broadcastJitter
The max time to delay route request broadcast.
std::string m_cacheType
The type of route cache.
std::vector< Ipv4Address > m_clearList
The node that is clear to send packet to.
uint32_t m_discoveryHopLimit
Maximum hops to go for route request.
IpL4Protocol::DownTargetCallback m_downTarget
The callback for down layer.
DsrErrorBuffer m_errorBuffer
The error buffer to save the error messages.
std::vector< Ipv4Address > m_finalRoute
The route cache.
DsrGraReply m_graReply
The gratuitous route reply.
uint32_t m_graReplyTableSize
Set the gratuitous reply table size.
Time m_gratReplyHoldoff
The max gratuitous reply hold off time.
Time m_initStability
The initial stability value for link cache.
Ptr< Ipv4 > m_ip
The ip ptr.
Ptr< Ipv4L3Protocol > m_ipv4
Ipv4l3Protocol.
Ptr< Ipv4Route > m_ipv4Route
Ipv4 Route.
bool m_linkAck
define if we use link acknowledgement or not
Time m_linkAckTimeout
The timeout value for link acknowledge.
std::map< LinkKey, Timer > m_linkAckTimer
The timer for link acknowledgment.
std::map< LinkKey, uint32_t > m_linkCnt
Map packet key + link forward counts.
uint32_t m_linkRetries
std::map< std::string, uint32_t > m_macToNodeIdMap
The map of mac address to node id.
Ipv4Address m_mainAddress
Our own Ip address.
DsrMaintainBuffer m_maintainBuffer
The declaration of maintain buffer.
uint32_t m_maxCacheLen
Max # of cache entries for route cache.
Time m_maxCacheTime
Max time for caching the route cache entry.
uint32_t m_maxEntriesEachDst
Max number of route entries to save for each destination.
uint32_t m_maxMaintainLen
Max # of entries for maintenance buffer.
Time m_maxMaintainTime
Time out for maintenance buffer.
uint32_t m_maxMaintRexmt
Maximum number of retransmissions of data packets.
Time m_maxNetworkDelay
Maximum network delay.
uint32_t m_maxNetworkSize
Maximum network queue size.
Time m_maxRequestPeriod
The max request period.
uint32_t m_maxRreqId
The max number of request ids for a single destination.
Time m_maxRreqTime
Max time for caching the route request entry.
uint8_t m_maxSalvageCount
Maximum # times to salvage a packet.
uint32_t m_maxSendBuffLen
The maximum number of packets that we allow a routing protocol to buffer.
Time m_minLifeTime
The min life time.
DsrNetworkQueue m_networkQueue
The network queue.
Ptr< Node > m_node
The node ptr.
Time m_nodeTraversalTime
Time estimated for packet to travel between two nodes.
std::map< Ipv4Address, Timer > m_nonPropReqTimer
Map IP address + RREQ timer.
Time m_nonpropRequestTimeout
The non-propagation request timeout.
uint32_t m_numPriorityQueues
The number of priority queues used.
DsrOptionList_t m_options
List of DSR Options supported.
Time m_passiveAckTimeout
The timeout value for passive acknowledge.
std::map< PassiveKey, Timer > m_passiveAckTimer
The timer for passive acknowledgment.
Ptr< dsr::DsrPassiveBuffer > m_passiveBuffer
A "drop-front" queue used by the routing layer to cache route request sent.
std::map< PassiveKey, uint32_t > m_passiveCnt
Map packet key + passive forward counts.
uint32_t m_passiveRetries
std::map< uint32_t, Ptr< dsr::DsrNetworkQueue > > m_priorityQueue
priority queues
uint32_t m_requestId
The id assigned to each route request.
Time m_requestPeriod
The base time interval between route requests.
uint32_t m_requestTableIds
The request table identifiers.
uint32_t m_requestTableSize
The max size of the request table size.
Time m_retransIncr
the increase time for retransmission timer when face network congestion
Ptr< dsr::DsrRouteCache > m_routeCache
A "drop-front" queue used by the routing layer to cache routes found.
std::string m_routeSortType
The type of route sort methods.
uint32_t m_rreqRetries
Maximum number of retransmissions of RREQ with TTL = NetDiameter to discover a route.
Ptr< dsr::DsrRreqTable > m_rreqTable
A "drop-front" queue used by the routing layer to cache route request sent.
DsrSendBuffer m_sendBuffer
The send buffer.
Time m_sendBufferTimeout
The maximum period of time that a routing protocol is allowed to buffer a packet for.
Time m_sendBuffInterval
how often to check send buffer
Timer m_sendBuffTimer
The send buffer timer.
uint32_t m_sendRetries
uint32_t m_stabilityDecrFactor
The initial decrease factor for link cache.
uint32_t m_stabilityIncrFactor
The initial increase factor for link cache.
bool m_subRoute
Whether to save sub route or not.
uint32_t m_tryLinkAcks
Maximum number of packet transmission using link acknowledgment.
uint32_t m_tryPassiveAcks
Maximum number of packet transmission using passive acknowledgment.
Ptr< UniformRandomVariable > m_uniformRandomVariable
Provides uniform random variables.
Time m_useExtends
The use extension of the life time for link cache.
uint8_t segsLeft
The segment left value from SR header.
Additional Inherited Members
Public Types inherited from ns3::IpL4Protocol
typedef Callback< void, Ptr< Packet >, Ipv4Address, Ipv4Address, uint8_t, Ptr< Ipv4Route > > DownTargetCallback
callback to send packets over IPv4
typedef Callback< void, Ptr< Packet >, Ipv6Address, Ipv6Address, uint8_t, Ptr< Ipv6Route > > DownTargetCallback6
callback to send packets over IPv6
enum RxStatus { RX_OK , RX_CSUM_FAILED , RX_ENDPOINT_CLOSED , RX_ENDPOINT_UNREACH }
Rx status codes.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Dsr Routing base.
Config Paths
ns3::dsr::DsrRouting is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::dsr::DsrRouting"
Attributes
RouteCache: The route cache for saving routes from route discovery process.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::dsr::DsrRouteCache>
Initial value: 0x0
Flags: construct write read
RreqTable: The request table to manage route requests.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::dsr::DsrRreqTable>
Initial value: 0x0
Flags: construct write read
PassiveBuffer: The passive buffer to manage promisucously received passive ack.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::dsr::DsrPassiveBuffer>
Initial value: 0x0
Flags: construct write read
MaxSendBuffLen: Maximum number of packets that can be stored in send buffer.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 64
Flags: construct write read
MaxSendBuffTime: Maximum time packets can be queued in the send buffer .
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +3e+10ns
Flags: construct write read
MaxMaintLen: Maximum number of packets that can be stored in maintenance buffer.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 50
Flags: construct write read
MaxMaintTime: Maximum time packets can be queued in maintenance buffer.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +3e+10ns
Flags: construct write read
MaxCacheLen: Maximum number of route entries that can be stored in route cache.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 64
Flags: construct write read
RouteCacheTimeout: Maximum time the route cache can be queued in route cache.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +3e+11ns
Flags: construct write read
MaxEntriesEachDst: Maximum number of route entries for a single destination to respond.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 20
Flags: construct write read
SendBuffInterval: How often to check send buffer for packet with route.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +5e+11ns
Flags: construct write read
NodeTraversalTime: The time it takes to traverse two neighboring nodes.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +4e+07ns
Flags: construct write read
RreqRetries: Maximum number of retransmissions for request discovery of a route.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 16
Flags: construct write read
MaintenanceRetries: Maximum number of retransmissions for data packets from maintenance buffer.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 2
Flags: construct write read
RequestTableSize: Maximum number of request entries in the request table, set this as the number of nodes in the simulation.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 64
Flags: construct write read
RequestIdSize: Maximum number of request source Ids in the request table.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 16
Flags: construct write read
UniqueRequestIdSize: Maximum number of request Ids in the request table for a single destination.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 256
Flags: construct write read
NonPropRequestTimeout: The timeout value for non-propagation request.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +3e+07ns
Flags: construct write read
DiscoveryHopLimit: The max discovery hop limit for route requests.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 255
Flags: construct write read
MaxSalvageCount: The max salvage count for a single data packet.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Initial value: 15
Flags: construct write read
BlacklistTimeout: The time for a neighbor to stay in blacklist.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +3e+09ns
Flags: construct write read
GratReplyHoldoff: The time for gratuitous reply entry to expire.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+09ns
Flags: construct write read
BroadcastJitter: The jitter time to avoid collision for broadcast packets.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 10
Flags: construct write read
LinkAckTimeout: The time a packet in maintenance buffer wait for link acknowledgment.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+08ns
Flags: construct write read
TryLinkAcks: The number of link acknowledgment to use.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 1
Flags: construct write read
PassiveAckTimeout: The time a packet in maintenance buffer wait for passive acknowledgment.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+08ns
Flags: construct write read
TryPassiveAcks: The number of passive acknowledgment to use.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 1
Flags: construct write read
RequestPeriod: The base time interval between route requests.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +5e+08ns
Flags: construct write read
MaxRequestPeriod: The max time interval between route requests.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+10ns
Flags: construct write read
GraReplyTableSize: The gratuitous reply table size.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 64
Flags: construct write read
CacheType: Use Link Cache or use Path Cache
Set with class: StringValue
Underlying type:
Initial value: LinkCache
Flags: construct write read
StabilityDecrFactor: The stability decrease factor for link cache
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 2
Flags: construct write read
StabilityIncrFactor: The stability increase factor for link cache
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 4
Flags: construct write read
InitStability: The initial stability factor for link cache
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +2.5e+10ns
Flags: construct write read
MinLifeTime: The minimal life time for link cache
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+09ns
Flags: construct write read
UseExtends: The extension time for link cache
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1.2e+11ns
Flags: construct write read
EnableSubRoute: Enables saving of sub route when receiving route error messages, only available when using path route cache
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
RetransIncr: The increase time for retransmission timer when facing network congestion
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +2e+07ns
Flags: construct write read
MaxNetworkQueueSize: The max number of packet to save in the network queue.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 400
Flags: construct write read
MaxNetworkQueueDelay: The max time for a packet to stay in the network queue.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +3e+10ns
Flags: construct write read
NumPriorityQueues: The max number of packet to save in the network queue.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 2
Flags: construct write read
LinkAcknowledgment: Enable Link layer acknowledgment mechanism
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
Attributes defined in parent class ns3::IpL4Protocol
ProtocolNumber: The IP protocol number.
Set with class: ns3::IntegerValue
Underlying type: int32_t 0:255
Flags: read
TraceSources
Tx: Send DSR packet.
Callback signature: ns3::dsr::DsrOptionSRHeader::TracedCallback
Drop: Drop DSR packet
Callback signature: ns3::Packet::TracedCallback
Size of this type is 1192 bytes (on a 64-bit architecture).
Definition at line 95 of file dsr-routing.h.
Member Typedef Documentation
DsrOptionList_t
typedef std::list<Ptr<DsrOptions> > ns3::dsr::DsrRouting::DsrOptionList_t private
Define the list to hold DSR options.
Definition at line 680 of file dsr-routing.h.
Constructor & Destructor Documentation
DsrRouting()
ns3::dsr::DsrRouting::DsrRouting ()
Constructor.
Definition at line 356 of file dsr-routing.cc.
References Insert(), m_sendBuffTimer, m_uniformRandomVariable, NS_LOG_FUNCTION_NOARGS, ns3::Timer::Schedule(), ns3::Seconds(), SendBuffTimerExpire(), and ns3::Timer::SetFunction().
~DsrRouting()
ns3::dsr::DsrRouting::~DsrRouting () virtual
Destructor.
Definition at line 391 of file dsr-routing.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
AddAckReqHeader()
uint16_t ns3::dsr::DsrRouting::AddAckReqHeader (Ptr< Packet > & packet, Ipv4Address nextHop)
This function is called to add ack request header for network acknowledgement.
Parameters
packet for ack req
nextHop IP address of the next hop
Returns
ack ID
Definition at line 1565 of file dsr-routing.cc.
References ns3::dsr::DsrOptionField::AddDsrOption(), ns3::Packet::AddHeader(), ns3::Packet::Copy(), ns3::Packet::CopyData(), ns3::dsr::DsrFsHeader::GetDestId(), ns3::dsr::DsrOptionField::GetDsrOptionsOffset(), ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrFsHeader::GetNextHeader(), ns3::dsr::DsrFsHeader::GetSourceId(), m_ackId, m_routeCache, NS_LOG_FUNCTION, ns3::Packet::RemoveAtStart(), ns3::Packet::RemoveHeader(), ns3::dsr::DsrOptionAckReqHeader::SetAckId(), ns3::dsr::DsrFsHeader::SetDestId(), ns3::dsr::DsrFsHeader::SetMessageType(), ns3::dsr::DsrFsHeader::SetNextHeader(), ns3::dsr::DsrOptionSRHeader::SetNumberAddress(), ns3::dsr::DsrFsHeader::SetPayloadLength(), and ns3::dsr::DsrFsHeader::SetSourceId().
Referenced by ScheduleNetworkPacketRetry().
AddRoute()
bool ns3::dsr::DsrRouting::AddRoute (DsrRouteCacheEntry & rt)
Definition at line 668 of file dsr-routing.cc.
References ns3::dsr::DsrErrorBuffer::DropPacketForErrLink(), ns3::dsr::DsrRouteCacheEntry::GetVector(), m_errorBuffer, m_mainAddress, m_routeCache, and SearchNextHop().
AddRoute_Link()
bool ns3::dsr::DsrRouting::AddRoute_Link (DsrRouteCacheEntry::IP_VECTOR nodelist, Ipv4Address source)
Definition at line 661 of file dsr-routing.cc.
References ns3::dsr::DsrErrorBuffer::DropPacketForErrLink(), m_errorBuffer, m_routeCache, and SearchNextHop().
AssignStreams()
int64_t ns3::dsr::DsrRouting::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 2619 of file dsr-routing.cc.
References m_uniformRandomVariable, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
CallCancelPacketTimer()
void ns3::dsr::DsrRouting::CallCancelPacketTimer (uint16_t ackId, Ipv4Header const & ipv4Header, Ipv4Address realSrc, Ipv4Address realDst)
Call the cancel packet retransmission timer function.
Parameters
ackId acknowledge ID
ipv4Header header
realSrc source IP address
realDst destination IP address
Definition at line 2033 of file dsr-routing.cc.
References CancelNetworkPacketTimer(), ns3::Ipv4Header::GetDestination(), ns3::Ipv4Header::GetSource(), ns3::Simulator::Now(), and NS_LOG_FUNCTION.
CancelLinkPacketTimer()
void ns3::dsr::DsrRouting::CancelLinkPacketTimer (DsrMaintainBuffEntry & mb)
Cancel the link packet retransmission timer for a specific maintenance entry.
Parameters
mb maintian byffer entry
TODO need to think about this part
Definition at line 2059 of file dsr-routing.cc.
References ns3::dsr::DsrMaintainBuffEntry::GetDst(), ns3::dsr::DsrMaintainBuffEntry::GetNextHop(), ns3::dsr::DsrMaintainBuffEntry::GetOurAdd(), ns3::dsr::DsrMaintainBuffer::GetSize(), ns3::dsr::DsrMaintainBuffEntry::GetSrc(), ns3::dsr::DsrMaintainBuffer::LinkEqual(), ns3::dsr::LinkKey::m_destination, m_linkAckTimer, m_linkCnt, m_maintainBuffer, ns3::dsr::LinkKey::m_nextHop, ns3::dsr::LinkKey::m_ourAdd, ns3::dsr::LinkKey::m_source, NS_LOG_DEBUG, NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by CancelPacketAllTimer().
CancelNetworkPacketTimer()
void ns3::dsr::DsrRouting::CancelNetworkPacketTimer (DsrMaintainBuffEntry & mb)
Cancel the network packet retransmission timer for a specific maintenance entry.
Parameters
mb maintian byffer entry
Definition at line 2108 of file dsr-routing.cc.
References ns3::dsr::DsrMaintainBuffEntry::GetAckId(), ns3::dsr::DsrMaintainBuffEntry::GetDst(), ns3::dsr::DsrMaintainBuffEntry::GetNextHop(), ns3::dsr::DsrMaintainBuffEntry::GetOurAdd(), ns3::dsr::DsrMaintainBuffEntry::GetSegsLeft(), ns3::dsr::DsrMaintainBuffEntry::GetSrc(), ns3::dsr::NetworkKey::m_ackId, m_addressForwardCnt, m_addressForwardTimer, ns3::dsr::NetworkKey::m_destination, m_maintainBuffer, ns3::dsr::NetworkKey::m_nextHop, ns3::dsr::NetworkKey::m_ourAdd, ns3::dsr::NetworkKey::m_source, ns3::dsr::DsrMaintainBuffer::NetworkEqual(), NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by CallCancelPacketTimer(), and CancelPacketAllTimer().
CancelPacketAllTimer()
void ns3::dsr::DsrRouting::CancelPacketAllTimer (DsrMaintainBuffEntry & mb)
Cancel all the packet timers.
Parameters
mb maintain buffer entry
Definition at line 2050 of file dsr-routing.cc.
References CancelLinkPacketTimer(), CancelNetworkPacketTimer(), CancelPassivePacketTimer(), and NS_LOG_FUNCTION.
Referenced by CancelPacketTimerNextHop().
CancelPacketTimerNextHop()
void ns3::dsr::DsrRouting::CancelPacketTimerNextHop (Ipv4Address nextHop, uint8_t protocol)
Cancel the packet retransmission timer for a all maintenance entries with nextHop address.
Parameters
nextHop next hop IP address
protocol number
TODO if the errorDst is not seen before
TODO need to think about whether we need the network queue entry or not
Definition at line 2192 of file dsr-routing.cc.
References CancelPacketAllTimer(), ns3::Packet::Copy(), ns3::Packet::CopyData(), ns3::dsr::DsrMaintainBuffer::Dequeue(), ns3::dsr::DsrMaintainBuffer::Find(), ns3::dsr::DsrOptionField::GetDsrOptionsOffset(), ns3::dsr::DsrMaintainBuffEntry::GetDst(), ns3::UniformRandomVariable::GetInteger(), ns3::dsr::DsrOptionSRHeader::GetNodesAddress(), ns3::dsr::DsrMaintainBuffEntry::GetPacket(), ns3::dsr::DsrOptionSRHeader::GetSalvage(), ns3::dsr::DsrMaintainBuffer::GetSize(), ns3::dsr::DsrMaintainBuffEntry::GetSrc(), m_maintainBuffer, m_uniformRandomVariable, ns3::MilliSeconds(), NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, PrintVector(), ns3::Packet::RemoveAtStart(), ns3::Packet::RemoveHeader(), SalvagePacket(), ns3::Simulator::Schedule(), SendUnreachError(), and ns3::dsr::DsrOptionSRHeader::SetNumberAddress().
Referenced by LinkScheduleTimerExpire(), and NetworkScheduleTimerExpire().
CancelPassivePacketTimer()
void ns3::dsr::DsrRouting::CancelPassivePacketTimer (DsrMaintainBuffEntry & mb)
Cancel the passive packet retransmission timer for a specific maintenance entry.
Parameters
mb maintian byffer entry
Definition at line 2157 of file dsr-routing.cc.
References ns3::dsr::DsrMaintainBuffEntry::GetDst(), ns3::dsr::DsrMaintainBuffEntry::GetSegsLeft(), ns3::dsr::DsrMaintainBuffEntry::GetSrc(), ns3::dsr::PassiveKey::m_ackId, ns3::dsr::PassiveKey::m_destination, m_passiveAckTimer, m_passiveCnt, ns3::dsr::PassiveKey::m_segsLeft, ns3::dsr::PassiveKey::m_source, NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by CancelPacketAllTimer(), CancelPassiveTimer(), PassiveEntryCheck(), and PassiveScheduleTimerExpire().
CancelPassiveTimer()
bool ns3::dsr::DsrRouting::CancelPassiveTimer (Ptr< Packet > packet, Ipv4Address source, Ipv4Address destination, uint8_t segsLeft)
Cancel the passive timer.
Parameters
packet to process
source IP address
destination IP address
segsLeft segments left
Returns
Definition at line 2006 of file dsr-routing.cc.
References CancelPassivePacketTimer(), ns3::Packet::Copy(), m_maintainBuffer, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::dsr::DsrMaintainBuffer::PromiscEqual(), segsLeft, ns3::dsr::DsrMaintainBuffEntry::SetAckId(), ns3::dsr::DsrMaintainBuffEntry::SetDst(), ns3::dsr::DsrMaintainBuffEntry::SetPacket(), ns3::dsr::DsrMaintainBuffEntry::SetSegsLeft(), and ns3::dsr::DsrMaintainBuffEntry::SetSrc().
CancelRreqTimer()
void ns3::dsr::DsrRouting::CancelRreqTimer (Ipv4Address dst, bool isRemove)
Cancel the route request timer.
Parameters
dst The dst address of the route request timer
isRemove whether to remove the route request entry or not
Definition at line 2895 of file dsr-routing.cc.
References m_addressReqTimer, m_nonPropReqTimer, m_rreqTable, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by RouteRequestTimerExpire(), and SendErrorRequest().
CheckSendBuffer()
void ns3::dsr::DsrRouting::CheckSendBuffer ()
Check the send buffer of packets with route when send buffer timer expire.
When found a route and use it, UseExtends to the link cache
This will be priority 0
Todo:
New DsrNetworkQueueEntry
When found a route and use it, UseExtends to the link cache
Definition at line 835 of file dsr-routing.cc.
References ns3::dsr::DsrOptionField::AddDsrOption(), ns3::Packet::AddHeader(), ns3::Packet::Copy(), ns3::Packet::CopyData(), data, ns3::dsr::DSR_CONTROL_PACKET, ns3::dsr::DsrMaintainBuffer::Enqueue(), ns3::dsr::DsrMaintainBuffEntry::GetAckId(), ns3::dsr::DsrSendBuffer::GetBuffer(), ns3::dsr::DsrOptionField::GetDsrOptionsOffset(), ns3::dsr::DsrMaintainBuffEntry::GetDst(), ns3::dsr::DsrOptionRerrUnreachHeader::GetErrorDst(), ns3::dsr::DsrOptionRerrUnreachHeader::GetErrorSrc(), GetIDfromIP(), ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrMaintainBuffEntry::GetNextHop(), ns3::dsr::DsrMaintainBuffEntry::GetOurAdd(), GetPriority(), ns3::dsr::DsrOptionRerrUnreachHeader::GetSalvage(), ns3::dsr::DsrMaintainBuffEntry::GetSegsLeft(), ns3::dsr::DsrSendBuffer::GetSize(), ns3::Packet::GetSize(), ns3::dsr::DsrMaintainBuffEntry::GetSrc(), ns3::dsr::DsrOptionRerrUnreachHeader::GetUnreachNode(), ns3::dsr::DsrRouteCacheEntry::GetVector(), ns3::Timer::IsSuspended(), ns3::dsr::NetworkKey::m_ackId, ns3::dsr::PassiveKey::m_ackId, m_addressForwardCnt, ns3::dsr::LinkKey::m_destination, ns3::dsr::NetworkKey::m_destination, ns3::dsr::PassiveKey::m_destination, m_ip, m_ipv4Route, m_linkAck, m_linkCnt, m_mainAddress, m_maintainBuffer, m_maxMaintainTime, ns3::dsr::LinkKey::m_nextHop, ns3::dsr::NetworkKey::m_nextHop, ns3::dsr::LinkKey::m_ourAdd, ns3::dsr::NetworkKey::m_ourAdd, m_passiveCnt, m_priorityQueue, m_routeCache, ns3::dsr::PassiveKey::m_segsLeft, m_sendBuffer, m_sendBuffInterval, m_sendBuffTimer, ns3::dsr::LinkKey::m_source, ns3::dsr::NetworkKey::m_source, ns3::dsr::PassiveKey::m_source, ns3::Simulator::Now(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_INFO, NS_LOG_LOGIC, PacketNewRoute(), ns3::Packet::RemoveAtStart(), ns3::Packet::RemoveHeader(), ns3::Timer::Resume(), ns3::Time::S, ns3::Simulator::Schedule(), ScheduleLinkPacketRetry(), ScheduleNetworkPacketRetry(), SchedulePassivePacketRetry(), Scheduler(), SearchNextHop(), SendBuffTimerExpire(), ns3::dsr::DsrFsHeader::SetDestId(), ns3::dsr::DsrOptionRerrUnreachHeader::SetErrorDst(), ns3::dsr::DsrOptionRerrUnreachHeader::SetErrorSrc(), ns3::dsr::DsrOptionRerrHeader::SetErrorType(), ns3::dsr::DsrFsHeader::SetMessageType(), ns3::dsr::DsrFsHeader::SetNextHeader(), ns3::dsr::DsrOptionSRHeader::SetNodesAddress(), ns3::Ipv4Route::SetOutputDevice(), ns3::dsr::DsrFsHeader::SetPayloadLength(), SetRoute(), ns3::dsr::DsrOptionSRHeader::SetSalvage(), ns3::dsr::DsrOptionRerrUnreachHeader::SetSalvage(), ns3::dsr::DsrOptionSRHeader::SetSegmentsLeft(), ns3::dsr::DsrFsHeader::SetSourceId(), ns3::dsr::DsrOptionRerrUnreachHeader::SetUnreachNode(), and ns3::Timer::Suspend().
Referenced by SendBuffTimerExpire().
DeleteAllRoutesIncludeLink()
void ns3::dsr::DsrRouting::DeleteAllRoutesIncludeLink (Ipv4Address errorSrc, Ipv4Address unreachNode, Ipv4Address node)
Definition at line 676 of file dsr-routing.cc.
References m_routeCache.
DoDispose()
void ns3::dsr::DsrRouting::DoDispose (void) protected virtual
Drop trace callback.
Reimplemented from ns3::Object.
Definition at line 549 of file dsr-routing.cc.
References ns3::Object::DoDispose(), m_ipv4, m_node, m_routeCache, third::mac, NS_LOG_FUNCTION_NOARGS, and third::wifi.
FindSourceEntry()
bool ns3::dsr::DsrRouting::FindSourceEntry (Ipv4Address src, Ipv4Address dst, uint16_t id)
Definition at line 686 of file dsr-routing.cc.
References m_rreqTable.
ForwardErrPacket()
void ns3::dsr::DsrRouting::ForwardErrPacket (DsrOptionRerrUnreachHeader & rerr, DsrOptionSRHeader & sourceRoute, Ipv4Address nextHop, uint8_t protocol, Ptr< Ipv4Route > route)
This function is responsible for forwarding error packets along the route.
Parameters
rerr unreachable header
sourceRoute source routing header
nextHop IP address of next hop
protocol number
route IP route
Todo:
New DsrNetworkQueueEntry
Definition at line 1380 of file dsr-routing.cc.
References ns3::dsr::DsrOptionField::AddDsrOption(), ns3::Packet::AddHeader(), ns3::dsr::DSR_CONTROL_PACKET, ns3::dsr::DsrOptionRerrUnreachHeader::GetErrorDst(), ns3::dsr::DsrOptionRerrUnreachHeader::GetErrorSrc(), GetIDfromIP(), ns3::dsr::DsrOptionHeader::GetLength(), GetPriority(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_downTarget, m_ip, m_mainAddress, m_priorityQueue, ns3::Simulator::Now(), NS_ASSERT_MSG, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, Scheduler(), ns3::dsr::DsrFsHeader::SetDestId(), ns3::dsr::DsrFsHeader::SetMessageType(), ns3::dsr::DsrFsHeader::SetNextHeader(), ns3::Ipv4Route::SetOutputDevice(), ns3::dsr::DsrFsHeader::SetPayloadLength(), and ns3::dsr::DsrFsHeader::SetSourceId().
ForwardPacket()
void ns3::dsr::DsrRouting::ForwardPacket (Ptr< const Packet > packet, DsrOptionSRHeader & sourceRoute, Ipv4Header const & ipv4Header, Ipv4Address source, Ipv4Address destination, Ipv4Address targetAddress, uint8_t protocol, Ptr< Ipv4Route > route)
Forward the packet using the route saved in the source route option header.
Parameters
packet The packet
sourceRoute Source route saved in option header
ipv4Header IPv4 Header
source source address
destination destination address
targetAddress target address
protocol protocol number
route route
Definition at line 2663 of file dsr-routing.cc.
References ns3::dsr::DsrOptionField::AddDsrOption(), ns3::Packet::AddHeader(), ns3::Packet::Copy(), ns3::dsr::DsrMaintainBuffer::Enqueue(), ns3::dsr::DsrMaintainBuffEntry::GetAckId(), ns3::dsr::DsrMaintainBuffEntry::GetDst(), GetIDfromIP(), ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrMaintainBuffEntry::GetNextHop(), ns3::dsr::DsrMaintainBuffEntry::GetOurAdd(), ns3::dsr::DsrOptionSRHeader::GetSegmentsLeft(), ns3::dsr::DsrMaintainBuffEntry::GetSegsLeft(), ns3::dsr::DsrMaintainBuffEntry::GetSrc(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), ns3::dsr::NetworkKey::m_ackId, ns3::dsr::PassiveKey::m_ackId, m_ackId, m_addressForwardCnt, ns3::dsr::LinkKey::m_destination, ns3::dsr::NetworkKey::m_destination, ns3::dsr::PassiveKey::m_destination, m_downTarget, m_linkAck, m_linkCnt, m_mainAddress, m_maintainBuffer, m_maxMaintainTime, ns3::dsr::LinkKey::m_nextHop, ns3::dsr::NetworkKey::m_nextHop, ns3::dsr::LinkKey::m_ourAdd, ns3::dsr::NetworkKey::m_ourAdd, m_passiveCnt, ns3::dsr::PassiveKey::m_segsLeft, ns3::dsr::LinkKey::m_source, ns3::dsr::NetworkKey::m_source, ns3::dsr::PassiveKey::m_source, NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, ScheduleLinkPacketRetry(), ScheduleNetworkPacketRetry(), SchedulePassivePacketRetry(), ns3::dsr::DsrFsHeader::SetDestId(), ns3::dsr::DsrFsHeader::SetMessageType(), ns3::dsr::DsrFsHeader::SetNextHeader(), ns3::dsr::DsrFsHeader::SetPayloadLength(), and ns3::dsr::DsrFsHeader::SetSourceId().
GetDownTarget()
IpL4Protocol::DownTargetCallback ns3::dsr::DsrRouting::GetDownTarget (void) const virtual
This method allows a caller to get the current down target callback set for this L4 protocol (IPv4 case)
Returns
current Callback for the L4 protocol
Implements ns3::IpL4Protocol.
Definition at line 3508 of file dsr-routing.cc.
References m_downTarget.
GetDownTarget6()
IpL4Protocol::DownTargetCallback6 ns3::dsr::DsrRouting::GetDownTarget6 (void) const virtual
This method allows a caller to get the current down target callback set for this L4 protocol (IPv6 case)
Returns
current Callback for the L4 protocol
Implements ns3::IpL4Protocol.
Definition at line 3514 of file dsr-routing.cc.
References NS_FATAL_ERROR.
GetElementsFromContext()
std::vector< std::string > ns3::dsr::DsrRouting::GetElementsFromContext (std::string context)
Get the elements from the tracing context.
Parameters
context context
Returns
the elements we are looking for
Definition at line 534 of file dsr-routing.cc.
Referenced by GetNetDeviceFromContext().
GetIDfromIP()
uint16_t ns3::dsr::DsrRouting::GetIDfromIP (Ipv4Address address)
Get the node id from ip address.
Parameters
address IPv4 address
Returns
the node id
Definition at line 781 of file dsr-routing.cc.
References first::address, ns3::NodeList::GetNNodes(), ns3::NodeList::GetNode(), and ns3::Object::GetObject().
Referenced by CheckSendBuffer(), ForwardErrPacket(), ForwardPacket(), PacketNewRoute(), Receive(), SalvagePacket(), Send(), SendErrorRequest(), SendGratuitousReply(), SendInitialRequest(), SendPacketFromBuffer(), and SendUnreachError().
GetIPfromID()
Ipv4Address ns3::dsr::DsrRouting::GetIPfromID (uint16_t id)
Get the ip address from id.
Parameters
id unique ID
Returns
the ip address for the id
Definition at line 797 of file dsr-routing.cc.
References ns3::NodeList::GetNode(), ns3::Object::GetObject(), and NS_LOG_DEBUG.
Referenced by PromiscReceive().
GetIPfromMAC()
Ipv4Address ns3::dsr::DsrRouting::GetIPfromMAC (Mac48Address address)
Get the Ip address from mac address.
Parameters
address Mac48Address
Returns
the ip address
Definition at line 692 of file dsr-routing.cc.
References first::address, ns3::NodeList::GetNNodes(), ns3::NodeList::GetNode(), ns3::Object::GetObject(), and NS_LOG_FUNCTION.
Referenced by PromiscReceive().
GetNetDeviceFromContext()
Ptr< NetDevice > ns3::dsr::DsrRouting::GetNetDeviceFromContext (std::string context)
Get the netdevice from the context.
Parameters
context context
Returns
the netdevice we are looking for
Definition at line 522 of file dsr-routing.cc.
References GetElementsFromContext(), ns3::NodeList::GetNode(), sample-rng-plot::n, and NS_ASSERT.
GetNode()
Ptr< Node > ns3::dsr::DsrRouting::GetNode (void) const
Get the node.
Returns
the node
Definition at line 583 of file dsr-routing.cc.
References m_node, and NS_LOG_FUNCTION_NOARGS.
GetNodeWithAddress()
Ptr< Node > ns3::dsr::DsrRouting::GetNodeWithAddress (Ipv4Address ipv4Address)
Get the node with give ip address.
Parameters
ipv4Address IPv4 address
Returns
the node associated with the ip address
Definition at line 629 of file dsr-routing.cc.
References ns3::NodeList::GetNNodes(), ns3::NodeList::GetNode(), ns3::Object::GetObject(), and NS_LOG_FUNCTION.
Referenced by PromiscReceive().
GetOption()
Ptr< dsr::DsrOptions > ns3::dsr::DsrRouting::GetOption (int optionNumber)
Get the option corresponding to optionNumber.
Parameters
optionNumber the option number of the option to retrieve
Returns
a matching Dsr option
Definition at line 3525 of file dsr-routing.cc.
References m_options.
Referenced by PromiscReceive().
GetPassiveBuffer()
Ptr< dsr::DsrPassiveBuffer > ns3::dsr::DsrRouting::GetPassiveBuffer () const
Get the passive buffer.
Returns
the passive buffer
Definition at line 622 of file dsr-routing.cc.
References m_passiveBuffer.
Referenced by GetTypeId().
GetPriority()
uint32_t ns3::dsr::DsrRouting::GetPriority (DsrMessageType messageType)
Set the priority of the packet in network queue.
Parameters
messageType Message type
Returns
the priority value
Definition at line 813 of file dsr-routing.cc.
References ns3::dsr::DSR_CONTROL_PACKET.
Referenced by CheckSendBuffer(), ForwardErrPacket(), IncreaseRetransTimer(), Receive(), SalvagePacket(), SendPacket(), SendPacketFromBuffer(), SendReply(), SendRequest(), and SendUnreachError().
GetProtocolNumber()
int ns3::dsr::DsrRouting::GetProtocolNumber (void) const virtual
Get the dsr protocol number.
Returns
protocol number
Implements ns3::IpL4Protocol.
Definition at line 774 of file dsr-routing.cc.
References PROT_NUMBER.
Referenced by SendRealDown().
GetRequestTable()
Ptr< dsr::DsrRreqTable > ns3::dsr::DsrRouting::GetRequestTable () const
Get the request table.
Returns
the request table
Definition at line 609 of file dsr-routing.cc.
References m_rreqTable.
Referenced by GetTypeId().
GetRouteCache()
Ptr< dsr::DsrRouteCache > ns3::dsr::DsrRouting::GetRouteCache () const
Get the route cache.
Returns
the route cache
Definition at line 596 of file dsr-routing.cc.
References m_routeCache.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::dsr::DsrRouting::GetTypeId (void) static
Get the type identificator.
Returns
type identificator
Definition at line 108 of file dsr-routing.cc.
References GetPassiveBuffer(), GetRequestTable(), GetRouteCache(), m_blacklistTimeout, m_broadcastJitter, m_cacheType, m_discoveryHopLimit, m_dropTrace, m_graReplyTableSize, m_gratReplyHoldoff, m_initStability, m_linkAck, m_linkAckTimeout, m_maxCacheLen, m_maxCacheTime, m_maxEntriesEachDst, m_maxMaintainLen, m_maxMaintainTime, m_maxMaintRexmt, m_maxNetworkDelay, m_maxNetworkSize, m_maxRequestPeriod, m_maxRreqId, m_maxSalvageCount, m_maxSendBuffLen, m_minLifeTime, m_nodeTraversalTime, m_nonpropRequestTimeout, m_numPriorityQueues, m_passiveAckTimeout, m_requestPeriod, m_requestTableIds, m_requestTableSize, m_retransIncr, m_rreqRetries, m_sendBufferTimeout, m_sendBuffInterval, m_stabilityDecrFactor, m_stabilityIncrFactor, m_subRoute, m_tryLinkAcks, m_tryPassiveAcks, m_txPacketTrace, m_useExtends, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakePointerAccessor(), ns3::MakeStringAccessor(), ns3::MakeStringChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), ns3::MilliSeconds(), ns3::Seconds(), ns3::TypeId::SetParent(), SetPassiveBuffer(), SetRequestTable(), and SetRouteCache().
IncreaseRetransTimer()
void ns3::dsr::DsrRouting::IncreaseRetransTimer ()
This function is called to increase the retransmission timer for data packet in the network queue.
Definition at line 1716 of file dsr-routing.cc.
References ns3::dsr::DSR_DATA_PACKET, GetPriority(), m_addressForwardTimer, m_priorityQueue, m_retransIncr, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by PriorityScheduler().
Insert()
void ns3::dsr::DsrRouting::Insert (Ptr< dsr::DsrOptions > option)
Insert a new Dsr Option.
Parameters
option the option to insert
Definition at line 3520 of file dsr-routing.cc.
References m_options.
Referenced by DsrRouting().
IsLinkCache()
bool ns3::dsr::DsrRouting::IsLinkCache ()
functions used to direct to route cache
Definition at line 646 of file dsr-routing.cc.
References m_routeCache.
LinkScheduleTimerExpire()
void ns3::dsr::DsrRouting::LinkScheduleTimerExpire (DsrMaintainBuffEntry & mb, uint8_t protocol)
This function deals with packet retransmission timer expire using link acknowledgment.
Parameters
mb maintenance buffer entry
protocol the protocol number
Definition at line 2533 of file dsr-routing.cc.
References CancelPacketTimerNextHop(), ns3::dsr::DsrMaintainBuffEntry::GetDst(), ns3::dsr::DsrMaintainBuffEntry::GetNextHop(), ns3::dsr::DsrMaintainBuffEntry::GetOurAdd(), ns3::dsr::DsrMaintainBuffEntry::GetPacket(), ns3::dsr::DsrMaintainBuffEntry::GetSrc(), ns3::dsr::LinkKey::m_destination, m_linkAckTimer, m_linkCnt, m_linkRetries, m_mainAddress, ns3::dsr::LinkKey::m_nextHop, ns3::dsr::LinkKey::m_ourAdd, m_routeCache, ns3::dsr::LinkKey::m_source, m_tryLinkAcks, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, ScheduleLinkPacketRetry(), and SetRoute().
Referenced by ScheduleLinkPacketRetry().
LookupRoute()
bool ns3::dsr::DsrRouting::LookupRoute (Ipv4Address id, DsrRouteCacheEntry & rt)
Definition at line 656 of file dsr-routing.cc.
References m_routeCache.
NetworkScheduleTimerExpire()
void ns3::dsr::DsrRouting::NetworkScheduleTimerExpire (DsrMaintainBuffEntry & mb, uint8_t protocol)
This function deals with packet retransmission timer expire using network acknowledgment.
Parameters
mb maintenance buffer entry
protocol the protocol number
Definition at line 2627 of file dsr-routing.cc.
References CancelPacketTimerNextHop(), ns3::dsr::DsrMaintainBuffEntry::GetAckId(), ns3::dsr::DsrMaintainBuffEntry::GetDst(), ns3::dsr::DsrMaintainBuffEntry::GetNextHop(), ns3::dsr::DsrMaintainBuffEntry::GetOurAdd(), ns3::dsr::DsrMaintainBuffEntry::GetPacket(), ns3::dsr::DsrMaintainBuffEntry::GetSrc(), ns3::dsr::NetworkKey::m_ackId, m_addressForwardCnt, ns3::dsr::NetworkKey::m_destination, m_mainAddress, m_maxMaintRexmt, ns3::dsr::NetworkKey::m_nextHop, ns3::dsr::NetworkKey::m_ourAdd, m_routeCache, m_sendRetries, ns3::dsr::NetworkKey::m_source, and ScheduleNetworkPacketRetry().
Referenced by ScheduleNetworkPacketRetry().
NotifyNewAggregate()
void ns3::dsr::DsrRouting::NotifyNewAggregate (void) protected virtual
Notify all Objects aggregated to this one of a new Object being aggregated.
This function must be implemented in the stack that needs to notify other stacks connected to the node of their presence in the node.
This method is invoked whenever two sets of Objects are aggregated together. It is invoked exactly once for each Object in both sets. This method can be overridden by subclasses who wish to be notified of aggregation events. These subclasses must chain up to their base class NotifyNewAggregate() method.
It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 397 of file dsr-routing.cc.
References ns3::Object::GetObject(), m_ip, m_ipv4, m_node, ns3::MakeCallback(), ns3::Object::NotifyNewAggregate(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Simulator::ScheduleNow(), ns3::Ipv4L3Protocol::Send(), SetDownTarget(), SetNode(), and Start().
PacketNewRoute()
void ns3::dsr::DsrRouting::PacketNewRoute (Ptr< Packet > packet, Ipv4Address source, Ipv4Address destination, uint8_t protocol)
When route vector corrupted, originate a new packet, normally not happening.
Parameters
packet to route
source address
destination address
protocol number
When found a route and use it, UseExtends to the link cache
Definition at line 1149 of file dsr-routing.cc.
References ns3::dsr::DsrOptionField::AddDsrOption(), ns3::Packet::AddHeader(), ns3::Packet::Copy(), ns3::dsr::DsrMaintainBuffer::Enqueue(), ns3::dsr::DsrSendBuffer::Enqueue(), ns3::dsr::DsrMaintainBuffEntry::GetAckId(), ns3::dsr::DsrMaintainBuffEntry::GetDst(), GetIDfromIP(), ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrMaintainBuffEntry::GetNextHop(), ns3::dsr::DsrMaintainBuffEntry::GetOurAdd(), ns3::dsr::DsrMaintainBuffEntry::GetSegsLeft(), ns3::dsr::DsrMaintainBuffEntry::GetSrc(), ns3::Packet::GetUid(), ns3::dsr::DsrRouteCacheEntry::GetVector(), ns3::dsr::NetworkKey::m_ackId, ns3::dsr::PassiveKey::m_ackId, m_addressForwardCnt, m_addressReqTimer, ns3::dsr::LinkKey::m_destination, ns3::dsr::NetworkKey::m_destination, ns3::dsr::PassiveKey::m_destination, m_linkAck, m_linkCnt, m_mainAddress, m_maintainBuffer, m_maxMaintainTime, ns3::dsr::LinkKey::m_nextHop, ns3::dsr::NetworkKey::m_nextHop, m_nonPropReqTimer, ns3::dsr::LinkKey::m_ourAdd, ns3::dsr::NetworkKey::m_ourAdd, m_passiveCnt, m_routeCache, ns3::dsr::PassiveKey::m_segsLeft, m_sendBuffer, m_sendBufferTimeout, ns3::dsr::LinkKey::m_source, ns3::dsr::NetworkKey::m_source, ns3::dsr::PassiveKey::m_source, ns3::Simulator::Now(), NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, ns3::Time::S, ScheduleLinkPacketRetry(), ScheduleNetworkPacketRetry(), SchedulePassivePacketRetry(), SearchNextHop(), SendInitialRequest(), ns3::dsr::DsrFsHeader::SetDestId(), ns3::dsr::DsrFsHeader::SetMessageType(), ns3::dsr::DsrFsHeader::SetNextHeader(), ns3::dsr::DsrOptionSRHeader::SetNodesAddress(), ns3::dsr::DsrFsHeader::SetPayloadLength(), SetRoute(), ns3::dsr::DsrOptionSRHeader::SetSalvage(), ns3::dsr::DsrOptionSRHeader::SetSegmentsLeft(), and ns3::dsr::DsrFsHeader::SetSourceId().
Referenced by CheckSendBuffer(), RouteRequestTimerExpire(), SalvagePacket(), Send(), SendErrorRequest(), and SendUnreachError().
PassiveEntryCheck()
bool ns3::dsr::DsrRouting::PassiveEntryCheck (Ptr< Packet > packet, Ipv4Address source, Ipv4Address destination, uint8_t segsLeft, uint16_t fragmentOffset, uint16_t identification, bool saveEntry)
Find the same passive entry.
Parameters
packet to process
source IP address
destination IP address
segsLeft segments left
fragmentOffset
identification
saveEntry
Returns
true if passive buffer entry
Save this passive buffer entry for later check
Definition at line 1963 of file dsr-routing.cc.
References CancelPassivePacketTimer(), ns3::Packet::Copy(), m_passiveBuffer, NS_LOG_DEBUG, NS_LOG_FUNCTION, segsLeft, ns3::dsr::DsrMaintainBuffEntry::SetAckId(), ns3::dsr::DsrPassiveBuffEntry::SetDestination(), ns3::dsr::DsrMaintainBuffEntry::SetDst(), ns3::dsr::DsrPassiveBuffEntry::SetFragmentOffset(), ns3::dsr::DsrPassiveBuffEntry::SetIdentification(), ns3::dsr::DsrMaintainBuffEntry::SetPacket(), ns3::dsr::DsrPassiveBuffEntry::SetPacket(), ns3::dsr::DsrPassiveBuffEntry::SetSegsLeft(), ns3::dsr::DsrMaintainBuffEntry::SetSegsLeft(), ns3::dsr::DsrPassiveBuffEntry::SetSource(), and ns3::dsr::DsrMaintainBuffEntry::SetSrc().
PassiveScheduleTimerExpire()
void ns3::dsr::DsrRouting::PassiveScheduleTimerExpire (DsrMaintainBuffEntry & mb, uint8_t protocol)
This function deals with packet retransmission timer expire using passive acknowledgment.
Parameters
mb maintenance buffer entry
protocol the protocol number
Definition at line 2579 of file dsr-routing.cc.
References CancelPassivePacketTimer(), ns3::dsr::DsrMaintainBuffEntry::GetDst(), ns3::dsr::DsrMaintainBuffEntry::GetNextHop(), ns3::dsr::DsrMaintainBuffEntry::GetPacket(), ns3::dsr::DsrMaintainBuffEntry::GetSegsLeft(), ns3::dsr::DsrMaintainBuffEntry::GetSrc(), ns3::dsr::PassiveKey::m_ackId, ns3::dsr::PassiveKey::m_destination, m_mainAddress, m_passiveAckTimer, m_passiveCnt, m_passiveRetries, ns3::dsr::PassiveKey::m_segsLeft, ns3::dsr::PassiveKey::m_source, m_tryPassiveAcks, NS_LOG_DEBUG, NS_LOG_FUNCTION, ScheduleNetworkPacketRetry(), SchedulePassivePacketRetry(), and SetRoute().
Referenced by SchedulePassivePacketRetry().
PrintVector()
void ns3::dsr::DsrRouting::PrintVector (std::vector< Ipv4Address > & vec)
Print the route vector.
Parameters
vec the vector to print.
Definition at line 710 of file dsr-routing.cc.
References NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by CancelPacketTimerNextHop().
PriorityScheduler()
void ns3::dsr::DsrRouting::PriorityScheduler (uint32_t priority, bool continueWithFirst)
This function is called to schedule sending packets from the network queue by priority.
Parameters
priority schedule
continueWithFirst use all priorities
Definition at line 1643 of file dsr-routing.cc.
References ns3::UniformRandomVariable::GetInteger(), IncreaseRetransTimer(), m_numPriorityQueues, m_priorityQueue, m_uniformRandomVariable, ns3::MicroSeconds(), NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, ns3::Simulator::Schedule(), ns3::Seconds(), and SendRealDown().
Referenced by Scheduler().
Process()
uint8_t ns3::dsr::DsrRouting::Process (Ptr< Packet > & packet, Ipv4Header const & ipv4Header, Ipv4Address dst, uint8_t * nextHeader, uint8_t protocol, bool & isDropped)
Process method Called from Ipv4L3Protocol::Receive.
Parameters
packet the packet
ipv4Header IPv4 header of the packet
dst destination address of the packet received (i.e. us)
nextHeader the next header
protocol the protocol number
isDropped if the packet must be dropped
Returns
the size processed
PromiscReceive()
bool ns3::dsr::DsrRouting::PromiscReceive (Ptr< NetDevice > device, Ptr< const Packet > packet, uint16_t protocol, const Address & from, const Address & to, NetDevice::PacketType packetType) private
Promiscuous receive data packets destined to some other node.
Parameters
device The network device
packet Data packet we just received
protocol The protocol we receive, need to verify it is dsr protocol
from The from address we received the packet
to The address this packet is destined for
packetType The dsr packet type, 0 is for control packet, 1 for data packet
Returns
true if the packet was processed, false otherwise
This is the ip address we just received data packet from
Remember this is the entry for previous node
Get the previous node's maintenance buffer and passive ack
Definition at line 1047 of file dsr-routing.cc.
References ns3::Mac48Address::ConvertFrom(), ns3::Packet::Copy(), ns3::Packet::CopyData(), data, ns3::dsr::DsrFsHeader::GetDestId(), ns3::Ipv4Header::GetDestination(), ns3::dsr::DsrOptionField::GetDsrOptionsOffset(), GetIPfromID(), GetIPfromMAC(), ns3::dsr::DsrFsHeader::GetMessageType(), ns3::dsr::DsrFsHeader::GetNextHeader(), GetNodeWithAddress(), ns3::Object::GetObject(), GetOption(), ns3::Ipv4Header::GetProtocol(), ns3::Packet::GetSize(), ns3::Ipv4Header::GetSource(), ns3::dsr::DsrFsHeader::GetSourceId(), ns3::Packet::GetUid(), m_ipv4, m_mainAddress, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_INFO, ns3::NetDevice::PACKET_OTHERHOST, PROT_NUMBER, ns3::Ipv4L3Protocol::PROT_NUMBER, ns3::Packet::RemoveAtStart(), ns3::Packet::RemoveHeader(), ns3::Time::S, ns3::dsr::DsrMaintainBuffEntry::SetDst(), ns3::dsr::DsrMaintainBuffEntry::SetNextHop(), ns3::dsr::DsrMaintainBuffEntry::SetOurAdd(), ns3::dsr::DsrMaintainBuffEntry::SetPacket(), and ns3::dsr::DsrMaintainBuffEntry::SetSrc().
Referenced by Start().
Receive() [1/2]
enum IpL4Protocol::RxStatus ns3::dsr::DsrRouting::Receive (Ptr< Packet > p, Ipv4Header const & header, Ptr< Ipv4Interface > incomingInterface) virtual
Parameters
p packet to forward up
header IPv4 Header information
incomingInterface the Ipv4Interface on which the packet arrived
Returns
receive status
Called from lower-level layers to send the packet up in the stack.
this is just here for the sake of passing in the promisc source
Implements ns3::IpL4Protocol.
Definition at line 3244 of file dsr-routing.cc.
References ns3::dsr::DsrOptionField::AddDsrOption(), ns3::Packet::AddHeader(), ns3::dsr::DSR_CONTROL_PACKET, GetIDfromIP(), ns3::dsr::DsrOptionHeader::GetLength(), GetPriority(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_downTarget, m_ip, m_mainAddress, m_priorityQueue, ns3::Simulator::Now(), NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, Scheduler(), ns3::dsr::DsrOptionAckHeader::SetAckId(), ns3::dsr::DsrFsHeader::SetDestId(), ns3::dsr::DsrFsHeader::SetMessageType(), ns3::dsr::DsrFsHeader::SetNextHeader(), ns3::Ipv4Route::SetOutputDevice(), ns3::dsr::DsrFsHeader::SetPayloadLength(), ns3::dsr::DsrOptionAckHeader::SetRealDst(), ns3::dsr::DsrOptionAckHeader::SetRealSrc(), and ns3::dsr::DsrFsHeader::SetSourceId().
Receive() [2/2]
enum IpL4Protocol::RxStatus ns3::dsr::DsrRouting::Receive (Ptr< Packet > p, Ipv6Header const & header, Ptr< Ipv6Interface > incomingInterface) virtual
Parameters
p packet to forward up
header IPv6 Header information
incomingInterface the Ipv6Interface on which the packet arrived
Returns
receive status
Called from lower-level layers to send the packet up in the stack. Not implemented (IPv6).
Implements ns3::IpL4Protocol.
Definition at line 3244 of file dsr-routing.cc.
RouteRequestTimerExpire()
void ns3::dsr::DsrRouting::RouteRequestTimerExpire (Ptr< Packet > packet, std::vector< Ipv4Address > address, uint32_t requestId, uint8_t protocol)
Handle route discovery timer.
Parameters
packet the original packet
address List of IPv4 addresses
requestId Unique request ID
protocol the protocol number
Set the salvage value to 0
Try to send out data packet from the send buffer if found
Definition at line 3013 of file dsr-routing.cc.
References ns3::Packet::AddPacketTag(), first::address, CancelRreqTimer(), ns3::Packet::Copy(), ns3::dsr::DsrSendBuffer::DropPacketWithDst(), ns3::dsr::DsrSendBuffer::Find(), ns3::dsr::DsrSendBuffer::GetSize(), ns3::dsr::DsrRouteCacheEntry::GetVector(), m_discoveryHopLimit, m_mainAddress, m_routeCache, m_rreqRetries, m_rreqTable, m_sendBuffer, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, PacketNewRoute(), ns3::Packet::RemoveHeader(), ScheduleRreqRetry(), SearchNextHop(), SendPacketFromBuffer(), SendRequest(), ns3::dsr::DsrOptionSRHeader::SetNodesAddress(), SetRoute(), ns3::dsr::DsrOptionSRHeader::SetSalvage(), ns3::dsr::DsrOptionSRHeader::SetSegmentsLeft(), and ns3::SocketIpTtlTag::SetTtl().
Referenced by ScheduleRreqRetry().
SalvagePacket()
void ns3::dsr::DsrRouting::SalvagePacket (Ptr< const Packet > packet, Ipv4Address source, Ipv4Address dst, uint8_t protocol)
Salvage the packet which has been transmitted for 3 times.
Parameters
packet to process
source IP address
dst destination IP address
protocol number
When found a route and use it, UseExtends to the link cache
Todo:
New DsrNetworkQueueEntry
Definition at line 2267 of file dsr-routing.cc.
References ns3::dsr::DsrOptionField::AddDsrOption(), ns3::Packet::AddHeader(), ns3::Packet::CopyData(), ns3::dsr::DSR_DATA_PACKET, ns3::dsr::DsrOptionField::GetDsrOptionsOffset(), GetIDfromIP(), ns3::dsr::DsrOptionHeader::GetLength(), GetPriority(), ns3::dsr::DsrOptionSRHeader::GetSalvage(), ns3::dsr::DsrRouteCacheEntry::GetVector(), m_ip, m_ipv4Route, m_mainAddress, m_maxSalvageCount, m_priorityQueue, m_routeCache, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, PacketNewRoute(), ns3::Packet::RemoveAtStart(), ns3::Packet::RemoveHeader(), Scheduler(), SearchNextHop(), ns3::dsr::DsrFsHeader::SetDestId(), ns3::dsr::DsrFsHeader::SetMessageType(), ns3::dsr::DsrFsHeader::SetNextHeader(), ns3::dsr::DsrOptionSRHeader::SetNodesAddress(), ns3::dsr::DsrOptionSRHeader::SetNumberAddress(), ns3::Ipv4Route::SetOutputDevice(), ns3::dsr::DsrFsHeader::SetPayloadLength(), SetRoute(), ns3::dsr::DsrOptionSRHeader::SetSalvage(), ns3::dsr::DsrOptionSRHeader::SetSegmentsLeft(), and ns3::dsr::DsrFsHeader::SetSourceId().
Referenced by CancelPacketTimerNextHop().
ScheduleCachedReply()
void ns3::dsr::DsrRouting::ScheduleCachedReply (Ptr< Packet > packet, Ipv4Address source, Ipv4Address destination, Ptr< Ipv4Route > route, double hops)
Schedule the cached reply to a random start time to avoid possible route reply storm.
Parameters
packet the original packet
source IPv4 address of the source (i.e. request originator)
destination IPv4 address of the destination
route Route
hops number of hops
Definition at line 3233 of file dsr-routing.cc.
References ns3::UniformRandomVariable::GetValue(), m_nodeTraversalTime, m_uniformRandomVariable, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), and SendReply().
ScheduleInitialReply()
void ns3::dsr::DsrRouting::ScheduleInitialReply (Ptr< Packet > packet, Ipv4Address source, Ipv4Address nextHop, Ptr< Ipv4Route > route)
this is a generating the initial route reply from the destination address, a random delay time [0, m_broadcastJitter] is used before unicasting back the route reply packet
Parameters
packet the original packet
source IPv4 address of the source (i.e. request originator)
nextHop IPv4 address of the next hop
route Route
Definition at line 3222 of file dsr-routing.cc.
References NS_LOG_FUNCTION, ns3::Simulator::ScheduleNow(), and SendReply().
ScheduleInterRequest()
void ns3::dsr::DsrRouting::ScheduleInterRequest (Ptr< Packet > packet)
Schedule the intermediate route request.
Parameters
packet the original packet
Definition at line 3116 of file dsr-routing.cc.
References ns3::UniformRandomVariable::GetInteger(), m_broadcastJitter, m_mainAddress, m_uniformRandomVariable, ns3::MilliSeconds(), NS_LOG_FUNCTION, ns3::Simulator::Schedule(), and SendRequest().
ScheduleLinkPacketRetry()
void ns3::dsr::DsrRouting::ScheduleLinkPacketRetry (DsrMaintainBuffEntry & mb, uint8_t protocol)
Schedule the packet retransmission based on link-layer acknowledgment.
Parameters
mb maintenance buffer entry
protocol the protocol number
Definition at line 2364 of file dsr-routing.cc.
References ns3::Timer::CANCEL_ON_DESTROY, ns3::dsr::DsrMaintainBuffEntry::GetDst(), ns3::dsr::DsrMaintainBuffEntry::GetNextHop(), ns3::dsr::DsrMaintainBuffEntry::GetOurAdd(), ns3::dsr::DsrMaintainBuffEntry::GetPacket(), ns3::dsr::DsrMaintainBuffEntry::GetSrc(), LinkScheduleTimerExpire(), ns3::dsr::LinkKey::m_destination, m_linkAckTimeout, m_linkAckTimer, ns3::dsr::LinkKey::m_nextHop, ns3::dsr::LinkKey::m_ourAdd, ns3::dsr::LinkKey::m_source, NS_LOG_FUNCTION, and SendPacket().
Referenced by CheckSendBuffer(), ForwardPacket(), LinkScheduleTimerExpire(), PacketNewRoute(), Send(), and SendPacketFromBuffer().
ScheduleNetworkPacketRetry()
void ns3::dsr::DsrRouting::ScheduleNetworkPacketRetry (DsrMaintainBuffEntry & mb, bool isFirst, uint8_t protocol)
Schedule the packet retransmission based on network layer acknowledgment.
Parameters
mb maintenance buffer entry
isFirst see if this is the first packet retry or not
protocol the protocol number
Definition at line 2425 of file dsr-routing.cc.
References AddAckReqHeader(), ns3::dsr::DsrMaintainBuffer::AllEqual(), ns3::Timer::CANCEL_ON_DESTROY, ns3::Packet::Copy(), ns3::dsr::DsrMaintainBuffer::Enqueue(), ns3::dsr::DsrMaintainBuffEntry::GetAckId(), ns3::dsr::DsrMaintainBuffEntry::GetDst(), ns3::dsr::DsrMaintainBuffEntry::GetNextHop(), ns3::dsr::DsrMaintainBuffEntry::GetOurAdd(), ns3::dsr::DsrMaintainBuffEntry::GetPacket(), ns3::Packet::GetSize(), ns3::dsr::DsrMaintainBuffEntry::GetSrc(), ns3::dsr::NetworkKey::m_ackId, m_addressForwardCnt, m_addressForwardTimer, ns3::dsr::NetworkKey::m_destination, m_maintainBuffer, m_maxMaintainTime, ns3::dsr::NetworkKey::m_nextHop, m_nodeTraversalTime, ns3::dsr::NetworkKey::m_ourAdd, m_sendRetries, ns3::dsr::NetworkKey::m_source, NetworkScheduleTimerExpire(), NS_LOG_DEBUG, NS_LOG_ERROR, ns3::Time::S, SendPacket(), ns3::dsr::DsrMaintainBuffEntry::SetAckId(), ns3::dsr::DsrMaintainBuffEntry::SetExpireTime(), and ns3::dsr::DsrMaintainBuffEntry::SetPacket().
Referenced by CheckSendBuffer(), ForwardPacket(), NetworkScheduleTimerExpire(), PacketNewRoute(), PassiveScheduleTimerExpire(), Send(), and SendPacketFromBuffer().
SchedulePassivePacketRetry()
void ns3::dsr::DsrRouting::SchedulePassivePacketRetry (DsrMaintainBuffEntry & mb, uint8_t protocol)
Schedule the packet retransmission based on passive acknowledgment.
Parameters
mb maintenance buffer entry
protocol the protocol number
Definition at line 2394 of file dsr-routing.cc.
References ns3::Timer::CANCEL_ON_DESTROY, ns3::dsr::DsrMaintainBuffEntry::GetDst(), ns3::dsr::DsrMaintainBuffEntry::GetNextHop(), ns3::dsr::DsrMaintainBuffEntry::GetPacket(), ns3::dsr::DsrMaintainBuffEntry::GetSegsLeft(), ns3::dsr::DsrMaintainBuffEntry::GetSrc(), ns3::dsr::PassiveKey::m_ackId, ns3::dsr::PassiveKey::m_destination, m_passiveAckTimeout, m_passiveAckTimer, ns3::dsr::PassiveKey::m_segsLeft, ns3::dsr::PassiveKey::m_source, NS_LOG_DEBUG, NS_LOG_FUNCTION, PassiveScheduleTimerExpire(), and SendPacket().
Referenced by CheckSendBuffer(), ForwardPacket(), PacketNewRoute(), PassiveScheduleTimerExpire(), Send(), and SendPacketFromBuffer().
Scheduler()
void ns3::dsr::DsrRouting::Scheduler (uint32_t priority)
This function is called to schedule sending packets from the network queue.
Parameters
priority for sending
Definition at line 1636 of file dsr-routing.cc.
References NS_LOG_FUNCTION, and PriorityScheduler().
Referenced by CheckSendBuffer(), ForwardErrPacket(), Receive(), SalvagePacket(), SendPacket(), SendPacketFromBuffer(), SendReply(), SendRequest(), and SendUnreachError().
ScheduleRreqRetry()
void ns3::dsr::DsrRouting::ScheduleRreqRetry (Ptr< Packet > packet, std::vector< Ipv4Address > address, bool nonProp, uint32_t requestId, uint8_t protocol)
Schedule the route request retry.
Parameters
packet the original packet
address List of IPv4 addresses
nonProp flag if RREQ is non-propagating
requestId Unique request ID
protocol the protocol number
Definition at line 2942 of file dsr-routing.cc.
References first::address, ns3::Time::As(), ns3::Timer::CANCEL_ON_DESTROY, m_addressReqTimer, m_maxRequestPeriod, m_nonPropReqTimer, m_nonpropRequestTimeout, m_requestPeriod, m_rreqTable, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, RouteRequestTimerExpire(), and ns3::Time::S.
Referenced by RouteRequestTimerExpire(), SendErrorRequest(), and SendInitialRequest().
SearchNextHop()
Ipv4Address ns3::dsr::DsrRouting::SearchNextHop (Ipv4Address ipv4Address, std::vector< Ipv4Address > & vec)
Get the next hop of the route.
Parameters
ipv4Address
vec Route
Returns
the next hop address of the route
Definition at line 730 of file dsr-routing.cc.
References NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by AddRoute(), AddRoute_Link(), CheckSendBuffer(), PacketNewRoute(), RouteRequestTimerExpire(), SalvagePacket(), Send(), SendErrorRequest(), and SendUnreachError().
Send()
void ns3::dsr::DsrRouting::Send (Ptr< Packet > packet, Ipv4Address source, Ipv4Address destination, uint8_t protocol, Ptr< Ipv4Route > route)
This function is called by higher layer protocol when sending packets.
Parameters
packet to send
source IP address
destination IP address
protocol number
route IP route
When found a route and use it, UseExtends to the link cache
Definition at line 1424 of file dsr-routing.cc.
References ns3::dsr::DsrOptionField::AddDsrOption(), ns3::Packet::AddHeader(), ns3::Packet::Copy(), ns3::dsr::DsrMaintainBuffer::Enqueue(), ns3::dsr::DsrSendBuffer::Enqueue(), ns3::dsr::DsrSendBuffer::Find(), ns3::dsr::DsrMaintainBuffEntry::GetAckId(), ns3::dsr::DsrMaintainBuffEntry::GetDst(), GetIDfromIP(), ns3::UniformRandomVariable::GetInteger(), ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrMaintainBuffEntry::GetNextHop(), ns3::dsr::DsrMaintainBuffEntry::GetOurAdd(), ns3::dsr::DsrMaintainBuffEntry::GetSegsLeft(), ns3::dsr::DsrSendBuffer::GetSize(), ns3::Packet::GetSize(), ns3::dsr::DsrMaintainBuffEntry::GetSrc(), ns3::Packet::GetUid(), ns3::dsr::DsrRouteCacheEntry::GetVector(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), ns3::dsr::NetworkKey::m_ackId, ns3::dsr::PassiveKey::m_ackId, m_addressForwardCnt, m_addressReqTimer, ns3::dsr::LinkKey::m_destination, ns3::dsr::NetworkKey::m_destination, ns3::dsr::PassiveKey::m_destination, m_downTarget, m_linkAck, m_linkCnt, m_mainAddress, m_maintainBuffer, m_maxMaintainTime, ns3::dsr::LinkKey::m_nextHop, ns3::dsr::NetworkKey::m_nextHop, m_nonPropReqTimer, ns3::dsr::LinkKey::m_ourAdd, ns3::dsr::NetworkKey::m_ourAdd, m_passiveCnt, m_routeCache, m_rreqTable, ns3::dsr::PassiveKey::m_segsLeft, m_sendBuffer, m_sendBufferTimeout, ns3::dsr::LinkKey::m_source, ns3::dsr::NetworkKey::m_source, ns3::dsr::PassiveKey::m_source, m_uniformRandomVariable, ns3::MilliSeconds(), ns3::Simulator::Now(), NS_ASSERT_MSG, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, PacketNewRoute(), ns3::Time::S, ns3::Simulator::Schedule(), ScheduleLinkPacketRetry(), ScheduleNetworkPacketRetry(), SchedulePassivePacketRetry(), SearchNextHop(), SendInitialRequest(), SendPacketFromBuffer(), ns3::dsr::DsrFsHeader::SetDestId(), ns3::dsr::DsrFsHeader::SetMessageType(), ns3::dsr::DsrFsHeader::SetNextHeader(), ns3::dsr::DsrOptionSRHeader::SetNodesAddress(), ns3::dsr::DsrFsHeader::SetPayloadLength(), ns3::dsr::DsrOptionSRHeader::SetSalvage(), ns3::dsr::DsrOptionSRHeader::SetSegmentsLeft(), and ns3::dsr::DsrFsHeader::SetSourceId().
Referenced by ns3::DsrHelper::Create().
SendAck()
void ns3::dsr::DsrRouting::SendAck (uint16_t ackId, Ipv4Address destination, Ipv4Address realSrc, Ipv4Address realDst, uint8_t protocol, Ptr< Ipv4Route > route)
Send network layer acknowledgment back to the earlier hop to notify the receipt of data packet.
Parameters
ackId ACK ID
destination IPv4 address of the immediate ACK receiver
realSrc IPv4 address of the real source
realDst IPv4 address of the real destination
protocol the protocol number
route Route
Todo:
New DsrNetworkQueueEntry
Definition at line 3244 of file dsr-routing.cc.
SendBuffTimerExpire()
void ns3::dsr::DsrRouting::SendBuffTimerExpire ()
The send buffer timer expire.
Definition at line 825 of file dsr-routing.cc.
References ns3::Timer::Cancel(), CheckSendBuffer(), ns3::Timer::IsRunning(), m_sendBuffInterval, m_sendBuffTimer, and ns3::Timer::Schedule().
Referenced by DsrRouting(), and CheckSendBuffer().
SendErrorRequest()
void ns3::dsr::DsrRouting::SendErrorRequest (DsrOptionRerrUnreachHeader & rerr, uint8_t protocol)
Send the error request packet.
Parameters
rerr the route error header
protocol the protocol number
When found a route and use it, UseExtends to the link cache
Try to send out the packet from the buffer once we found one route
Definition at line 2790 of file dsr-routing.cc.
References ns3::dsr::DsrOptionField::AddDsrOption(), ns3::Packet::AddHeader(), ns3::dsr::DsrOptionRreqHeader::AddNodeAddress(), ns3::Packet::AddPacketTag(), first::address, CancelRreqTimer(), ns3::Packet::Copy(), ns3::dsr::DsrSendBuffer::Find(), ns3::dsr::DsrOptionRerrUnreachHeader::GetErrorDst(), ns3::dsr::DsrOptionRerrUnreachHeader::GetErrorSrc(), GetIDfromIP(), ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrOptionRerrUnreachHeader::GetOriginalDst(), ns3::dsr::DsrOptionRerrUnreachHeader::GetSalvage(), ns3::dsr::DsrSendBuffer::GetSize(), ns3::dsr::DsrOptionRerrUnreachHeader::GetUnreachNode(), ns3::dsr::DsrRouteCacheEntry::GetVector(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_addressReqTimer, m_discoveryHopLimit, m_downTarget, m_mainAddress, m_nonPropReqTimer, m_requestId, m_routeCache, m_rreqTable, m_sendBuffer, NS_ASSERT_MSG, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, PacketNewRoute(), ScheduleRreqRetry(), SearchNextHop(), SendPacketFromBuffer(), SendRequest(), ns3::dsr::DsrFsHeader::SetDestId(), ns3::dsr::DsrOptionRreqHeader::SetId(), ns3::dsr::DsrFsHeader::SetMessageType(), ns3::dsr::DsrFsHeader::SetNextHeader(), ns3::dsr::DsrOptionSRHeader::SetNodesAddress(), ns3::dsr::DsrFsHeader::SetPayloadLength(), SetRoute(), ns3::dsr::DsrOptionSRHeader::SetSalvage(), ns3::dsr::DsrOptionSRHeader::SetSegmentsLeft(), ns3::dsr::DsrFsHeader::SetSourceId(), ns3::dsr::DsrOptionRreqHeader::SetTarget(), and ns3::SocketIpTtlTag::SetTtl().
Referenced by SendUnreachError().
SendGratuitousReply()
void ns3::dsr::DsrRouting::SendGratuitousReply (Ipv4Address replyTo, Ipv4Address replyFrom, std::vector< Ipv4Address > & nodeList, uint8_t protocol)
Send the gratuitous reply.
Parameters
replyTo The destination address to send the reply to
replyFrom The source address sending the reply
nodeList Route
protocol the protocol number
Push back the node addresses other than those between srcAddress and our own ip address
Definition at line 3128 of file dsr-routing.cc.
References ns3::dsr::DsrOptionField::AddDsrOption(), ns3::dsr::DsrGraReply::AddEntry(), ns3::Packet::AddHeader(), ns3::dsr::DsrGraReply::FindAndUpdate(), GetIDfromIP(), ns3::dsr::DsrOptionHeader::GetLength(), m_finalRoute, m_graReply, m_gratReplyHoldoff, m_ipv4Route, m_mainAddress, ns3::Simulator::Now(), NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, SendReply(), ns3::dsr::DsrFsHeader::SetDestId(), ns3::dsr::DsrFsHeader::SetMessageType(), ns3::dsr::DsrFsHeader::SetNextHeader(), ns3::dsr::DsrOptionRrepHeader::SetNodesAddress(), ns3::dsr::DsrFsHeader::SetPayloadLength(), SetRoute(), and ns3::dsr::DsrFsHeader::SetSourceId().
SendInitialRequest()
void ns3::dsr::DsrRouting::SendInitialRequest (Ipv4Address source, Ipv4Address destination, uint8_t protocol)
Broadcast the route request packet in subnet.
Parameters
source source address
destination destination address
protocol protocol number
Definition at line 2741 of file dsr-routing.cc.
References ns3::dsr::DsrOptionField::AddDsrOption(), ns3::Packet::AddHeader(), ns3::dsr::DsrOptionRreqHeader::AddNodeAddress(), ns3::Packet::AddPacketTag(), first::address, ns3::Packet::Copy(), GetIDfromIP(), ns3::dsr::DsrOptionHeader::GetLength(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_downTarget, m_mainAddress, m_requestId, m_rreqTable, NS_ASSERT_MSG, NS_LOG_FUNCTION, ScheduleRreqRetry(), SendRequest(), ns3::dsr::DsrFsHeader::SetDestId(), ns3::dsr::DsrOptionRreqHeader::SetId(), ns3::dsr::DsrFsHeader::SetMessageType(), ns3::dsr::DsrFsHeader::SetNextHeader(), ns3::dsr::DsrFsHeader::SetPayloadLength(), ns3::dsr::DsrFsHeader::SetSourceId(), ns3::dsr::DsrOptionRreqHeader::SetTarget(), and ns3::SocketIpTtlTag::SetTtl().
Referenced by PacketNewRoute(), Send(), and SendUnreachError().
SendPacket()
void ns3::dsr::DsrRouting::SendPacket (Ptr< Packet > packet, Ipv4Address source, Ipv4Address nextHop, uint8_t protocol)
This function is called by when really sending out the packet.
Parameters
packet to send
source IP address
nextHop IP address
protocol number
Todo:
New DsrNetworkQueueEntry
Definition at line 1607 of file dsr-routing.cc.
References ns3::dsr::DSR_DATA_PACKET, GetPriority(), m_ip, m_ipv4Route, m_mainAddress, m_priorityQueue, ns3::Simulator::Now(), NS_LOG_FUNCTION, NS_LOG_INFO, Scheduler(), ns3::Ipv4Route::SetOutputDevice(), and SetRoute().
Referenced by ScheduleLinkPacketRetry(), ScheduleNetworkPacketRetry(), and SchedulePassivePacketRetry().
SendPacketFromBuffer()
void ns3::dsr::DsrRouting::SendPacketFromBuffer (DsrOptionSRHeader const & sourceRoute, Ipv4Address nextHop, uint8_t protocol)
This function is responsible for sending out data packets when have route, if no route found, it will cache the packet and send out route requests.
Parameters
sourceRoute source route
nextHop next hop IP address
protocol number
When found a route and use it, UseExtends to the link cache
When found a route and use it, UseExtends to the link cache
Todo:
New DsrNetworkQueueEntry
Definition at line 1752 of file dsr-routing.cc.
References ns3::dsr::DsrOptionField::AddDsrOption(), ns3::Packet::AddHeader(), ns3::Packet::Copy(), ns3::Packet::CopyData(), data, ns3::dsr::DsrErrorBuffer::Dequeue(), ns3::dsr::DsrSendBuffer::Dequeue(), ns3::dsr::DSR_CONTROL_PACKET, ns3::dsr::DsrMaintainBuffer::Enqueue(), ns3::dsr::DsrErrorBuffer::Find(), ns3::dsr::DsrSendBuffer::Find(), ns3::dsr::DsrMaintainBuffEntry::GetAckId(), ns3::dsr::DsrOptionField::GetDsrOptionsOffset(), ns3::dsr::DsrMaintainBuffEntry::GetDst(), ns3::dsr::DsrOptionRerrUnreachHeader::GetErrorDst(), ns3::dsr::DsrOptionRerrUnreachHeader::GetErrorSrc(), GetIDfromIP(), ns3::UniformRandomVariable::GetInteger(), ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrMaintainBuffEntry::GetNextHop(), ns3::dsr::DsrOptionSRHeader::GetNodesAddress(), ns3::dsr::DsrOptionRerrUnreachHeader::GetOriginalDst(), ns3::dsr::DsrMaintainBuffEntry::GetOurAdd(), ns3::dsr::DsrErrorBuffEntry::GetPacket(), ns3::dsr::DsrSendBuffEntry::GetPacket(), GetPriority(), ns3::dsr::DsrOptionRerrUnreachHeader::GetSalvage(), ns3::dsr::DsrMaintainBuffEntry::GetSegsLeft(), ns3::dsr::DsrErrorBuffer::GetSize(), ns3::dsr::DsrSendBuffer::GetSize(), ns3::Packet::GetSize(), ns3::dsr::DsrMaintainBuffEntry::GetSrc(), ns3::dsr::DsrOptionRerrUnreachHeader::GetUnreachNode(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), ns3::dsr::NetworkKey::m_ackId, ns3::dsr::PassiveKey::m_ackId, m_addressForwardCnt, ns3::dsr::LinkKey::m_destination, ns3::dsr::NetworkKey::m_destination, ns3::dsr::PassiveKey::m_destination, m_downTarget, m_errorBuffer, m_ip, m_ipv4Route, m_linkAck, m_linkCnt, m_mainAddress, m_maintainBuffer, m_maxMaintainTime, ns3::dsr::LinkKey::m_nextHop, ns3::dsr::NetworkKey::m_nextHop, ns3::dsr::LinkKey::m_ourAdd, ns3::dsr::NetworkKey::m_ourAdd, m_passiveCnt, m_priorityQueue, m_routeCache, ns3::dsr::PassiveKey::m_segsLeft, m_sendBuffer, ns3::dsr::LinkKey::m_source, ns3::dsr::NetworkKey::m_source, ns3::dsr::PassiveKey::m_source, m_uniformRandomVariable, ns3::MilliSeconds(), ns3::Simulator::Now(), NS_ASSERT, NS_ASSERT_MSG, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, ns3::Packet::RemoveAtStart(), ns3::Packet::RemoveHeader(), ns3::Simulator::Schedule(), ScheduleLinkPacketRetry(), ScheduleNetworkPacketRetry(), SchedulePassivePacketRetry(), Scheduler(), ns3::dsr::DsrFsHeader::SetDestId(), ns3::dsr::DsrOptionRerrUnreachHeader::SetErrorDst(), ns3::dsr::DsrOptionRerrUnreachHeader::SetErrorSrc(), ns3::dsr::DsrOptionRerrHeader::SetErrorType(), ns3::dsr::DsrFsHeader::SetMessageType(), ns3::dsr::DsrFsHeader::SetNextHeader(), ns3::dsr::DsrOptionRerrUnreachHeader::SetOriginalDst(), ns3::Ipv4Route::SetOutputDevice(), ns3::dsr::DsrFsHeader::SetPayloadLength(), SetRoute(), ns3::dsr::DsrOptionRerrUnreachHeader::SetSalvage(), ns3::dsr::DsrFsHeader::SetSourceId(), and ns3::dsr::DsrOptionRerrUnreachHeader::SetUnreachNode().
Referenced by RouteRequestTimerExpire(), Send(), and SendErrorRequest().
SendRealDown()
bool ns3::dsr::DsrRouting::SendRealDown (DsrNetworkQueueEntry & newEntry)
This function is called to send packets down stack.
Parameters
newEntry queue entry
Returns
true if success
Definition at line 1740 of file dsr-routing.cc.
References ns3::dsr::DsrNetworkQueueEntry::GetIpv4Route(), ns3::dsr::DsrNetworkQueueEntry::GetNextHopAddress(), ns3::dsr::DsrNetworkQueueEntry::GetPacket(), GetProtocolNumber(), ns3::dsr::DsrNetworkQueueEntry::GetSourceAddress(), m_downTarget, and NS_LOG_FUNCTION.
Referenced by PriorityScheduler().
SendReply()
void ns3::dsr::DsrRouting::SendReply (Ptr< Packet > packet, Ipv4Address source, Ipv4Address nextHop, Ptr< Ipv4Route > route)
Send the route reply back to the request originator with the cumulated route.
Parameters
packet the original packet
source IPv4 address of the source (i.e. request originator)
nextHop IPv4 address of the next hop
route Route
Todo:
New DsrNetworkQueueEntry
Definition at line 3190 of file dsr-routing.cc.
References ns3::dsr::DSR_CONTROL_PACKET, GetPriority(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_downTarget, m_ipv4, m_mainAddress, m_priorityQueue, ns3::Simulator::Now(), NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_INFO, Scheduler(), and ns3::Ipv4Route::SetOutputDevice().
Referenced by ScheduleCachedReply(), ScheduleInitialReply(), and SendGratuitousReply().
SendRequest()
void ns3::dsr::DsrRouting::SendRequest (Ptr< Packet > packet, Ipv4Address source)
Forward the route request if the node is not the destination.
Parameters
packet the original packet
source address
Todo:
New DsrNetworkQueueEntry
Definition at line 3087 of file dsr-routing.cc.
References ns3::dsr::DSR_CONTROL_PACKET, GetPriority(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_broadcast, m_downTarget, m_priorityQueue, ns3::Simulator::Now(), NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, and Scheduler().
Referenced by RouteRequestTimerExpire(), ScheduleInterRequest(), SendErrorRequest(), and SendInitialRequest().
SendRerrWhenBreaksLinkToNextHop()
void ns3::dsr::DsrRouting::SendRerrWhenBreaksLinkToNextHop (Ipv4Address nextHop, uint8_t protocol) private
Send the route error message when the link breaks to the next hop.
Parameters
nextHop next hop address
protocol protocol number
SendUnreachError()
void ns3::dsr::DsrRouting::SendUnreachError (Ipv4Address unreachNode, Ipv4Address destination, Ipv4Address originalDst, uint8_t salvage, uint8_t protocol)
This function is responsible for sending error packets in case of break link to next hop.
Parameters
unreachNode unreachable node
destination address
originalDst address
salvage packet flag
protocol number
When found a route and use it, UseExtends to the link cache
Todo:
New DsrNetworkQueueEntry
Definition at line 1268 of file dsr-routing.cc.
References ns3::dsr::DsrOptionField::AddDsrOption(), ns3::Packet::AddHeader(), ns3::Packet::Copy(), ns3::dsr::DSR_CONTROL_PACKET, ns3::dsr::DsrErrorBuffer::Enqueue(), GetIDfromIP(), ns3::dsr::DsrOptionHeader::GetLength(), GetPriority(), ns3::Packet::GetSize(), ns3::Packet::GetUid(), ns3::dsr::DsrRouteCacheEntry::GetVector(), m_addressReqTimer, m_errorBuffer, m_ip, m_ipv4Route, m_mainAddress, m_nonPropReqTimer, m_priorityQueue, m_routeCache, m_sendBufferTimeout, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, PacketNewRoute(), ns3::Time::S, Scheduler(), SearchNextHop(), SendErrorRequest(), SendInitialRequest(), ns3::dsr::DsrFsHeader::SetDestId(), ns3::dsr::DsrOptionRerrUnreachHeader::SetErrorDst(), ns3::dsr::DsrOptionRerrUnreachHeader::SetErrorSrc(), ns3::dsr::DsrOptionRerrHeader::SetErrorType(), ns3::dsr::DsrFsHeader::SetMessageType(), ns3::dsr::DsrFsHeader::SetNextHeader(), ns3::dsr::DsrOptionSRHeader::SetNodesAddress(), ns3::dsr::DsrOptionRerrUnreachHeader::SetOriginalDst(), ns3::Ipv4Route::SetOutputDevice(), ns3::dsr::DsrFsHeader::SetPayloadLength(), SetRoute(), ns3::dsr::DsrOptionRerrUnreachHeader::SetSalvage(), ns3::dsr::DsrOptionSRHeader::SetSegmentsLeft(), ns3::dsr::DsrFsHeader::SetSourceId(), and ns3::dsr::DsrOptionRerrUnreachHeader::SetUnreachNode().
Referenced by CancelPacketTimerNextHop().
SetDownTarget()
void ns3::dsr::DsrRouting::SetDownTarget (IpL4Protocol::DownTargetCallback cb) virtual
This method allows a caller to set the current down target callback set for this L4 protocol (IPv4 case)
Parameters
cb current Callback for the L4 protocol
Implements ns3::IpL4Protocol.
Definition at line 3495 of file dsr-routing.cc.
References m_downTarget.
Referenced by NotifyNewAggregate().
SetDownTarget6()
void ns3::dsr::DsrRouting::SetDownTarget6 (IpL4Protocol::DownTargetCallback6 cb) virtual
This method allows a caller to set the current down target callback set for this L4 protocol (IPv6 case)
Parameters
cb current Callback for the L4 protocol
Implements ns3::IpL4Protocol.
Definition at line 3501 of file dsr-routing.cc.
References NS_FATAL_ERROR.
SetNode()
void ns3::dsr::DsrRouting::SetNode (Ptr< Node > node)
Set the node.
Parameters
node the node to set
Definition at line 577 of file dsr-routing.cc.
References m_node.
Referenced by NotifyNewAggregate().
SetPassiveBuffer()
void ns3::dsr::DsrRouting::SetPassiveBuffer (Ptr< dsr::DsrPassiveBuffer > r)
Set the node.
Parameters
r the passive buffer to set
Definition at line 615 of file dsr-routing.cc.
References m_passiveBuffer.
Referenced by GetTypeId(), and Start().
SetRequestTable()
void ns3::dsr::DsrRouting::SetRequestTable (Ptr< dsr::DsrRreqTable > r)
Set the node.
Parameters
r the request table to set
Definition at line 602 of file dsr-routing.cc.
References m_rreqTable.
Referenced by GetTypeId(), and Start().
SetRoute()
Ptr< Ipv4Route > ns3::dsr::DsrRouting::SetRoute (Ipv4Address nextHop, Ipv4Address srcAddress)
Set the route to use for data packets, used by the option headers when sending data/control packets.
Parameters
nextHop next hop IPv4 address
srcAddress IPv4 address of the source
Returns
the route
Definition at line 763 of file dsr-routing.cc.
References m_ipv4Route, NS_LOG_FUNCTION, ns3::Ipv4Route::SetDestination(), ns3::Ipv4Route::SetGateway(), and ns3::Ipv4Route::SetSource().
Referenced by CheckSendBuffer(), LinkScheduleTimerExpire(), PacketNewRoute(), PassiveScheduleTimerExpire(), RouteRequestTimerExpire(), SalvagePacket(), SendErrorRequest(), SendGratuitousReply(), SendPacket(), SendPacketFromBuffer(), and SendUnreachError().
SetRouteCache()
void ns3::dsr::DsrRouting::SetRouteCache (Ptr< dsr::DsrRouteCache > r)
Set the route cache.
Parameters
r the route cache to set
Definition at line 589 of file dsr-routing.cc.
References m_routeCache.
Referenced by GetTypeId(), and Start().
Start()
void ns3::dsr::DsrRouting::Start (void) private
TODO whether this SendRerrWhenBreaksLinkToNextHop is used or not
Definition at line 424 of file dsr-routing.cc.
References ns3::Time::As(), m_broadcast, m_cacheType, m_discoveryHopLimit, m_errorBuffer, m_graReply, m_graReplyTableSize, m_initStability, m_ipv4, m_mainAddress, m_maintainBuffer, m_maxCacheLen, m_maxCacheTime, m_maxEntriesEachDst, m_maxMaintainLen, m_maxMaintainTime, m_maxNetworkDelay, m_maxNetworkSize, m_maxRreqId, m_maxSendBuffLen, m_minLifeTime, m_numPriorityQueues, m_priorityQueue, m_requestTableIds, m_requestTableSize, m_sendBuffer, m_sendBufferTimeout, m_stabilityDecrFactor, m_stabilityIncrFactor, m_subRoute, m_useExtends, third::mac, ns3::MakeCallback(), NS_ASSERT, NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, PromiscReceive(), ns3::Time::S, ns3::dsr::DsrErrorBuffer::SetErrorBufferTimeout(), ns3::dsr::DsrGraReply::SetGraTableSize(), ns3::dsr::DsrMaintainBuffer::SetMaintainBufferTimeout(), ns3::dsr::DsrErrorBuffer::SetMaxQueueLen(), ns3::dsr::DsrMaintainBuffer::SetMaxQueueLen(), ns3::dsr::DsrSendBuffer::SetMaxQueueLen(), SetPassiveBuffer(), SetRequestTable(), SetRouteCache(), ns3::dsr::DsrSendBuffer::SetSendBufferTimeout(), and third::wifi.
Referenced by NotifyNewAggregate().
UpdateRouteEntry()
bool ns3::dsr::DsrRouting::UpdateRouteEntry (Ipv4Address dst)
Definition at line 681 of file dsr-routing.cc.
References m_routeCache.
UseExtends()
void ns3::dsr::DsrRouting::UseExtends (DsrRouteCacheEntry::IP_VECTOR rt)
Definition at line 651 of file dsr-routing.cc.
References m_routeCache.
Member Data Documentation
m_ackId
uint16_t ns3::dsr::DsrRouting::m_ackId private
The ack id assigned to each acknowledge.
Definition at line 748 of file dsr-routing.h.
Referenced by AddAckReqHeader(), and ForwardPacket().
m_addresses
std::vector<Ipv4Address> ns3::dsr::DsrRouting::m_addresses private
The bind ipv4 addresses with next hop, src, destination address in sequence.
Definition at line 834 of file dsr-routing.h.
m_addressForwardCnt
std::map<NetworkKey, uint32_t> ns3::dsr::DsrRouting::m_addressForwardCnt private
Map network key + forward counts.
Definition at line 806 of file dsr-routing.h.
Referenced by CancelNetworkPacketTimer(), CheckSendBuffer(), ForwardPacket(), NetworkScheduleTimerExpire(), PacketNewRoute(), ScheduleNetworkPacketRetry(), Send(), and SendPacketFromBuffer().
m_addressForwardTimer
std::map<NetworkKey, Timer> ns3::dsr::DsrRouting::m_addressForwardTimer private
Map network key + forward timer.
Definition at line 804 of file dsr-routing.h.
Referenced by CancelNetworkPacketTimer(), IncreaseRetransTimer(), and ScheduleNetworkPacketRetry().
m_addressReqTimer
std::map<Ipv4Address, Timer> ns3::dsr::DsrRouting::m_addressReqTimer private
Map IP address + RREQ timer.
Definition at line 800 of file dsr-routing.h.
Referenced by CancelRreqTimer(), PacketNewRoute(), ScheduleRreqRetry(), Send(), SendErrorRequest(), and SendUnreachError().
m_blacklistTimeout
Time ns3::dsr::DsrRouting::m_blacklistTimeout private
The black list time out.
Definition at line 756 of file dsr-routing.h.
Referenced by GetTypeId().
m_broadcast
Ipv4Address ns3::dsr::DsrRouting::m_broadcast private
The broadcast IP address.
Definition at line 758 of file dsr-routing.h.
Referenced by SendRequest(), and Start().
m_broadcastJitter
uint32_t ns3::dsr::DsrRouting::m_broadcastJitter private
The max time to delay route request broadcast.
Definition at line 760 of file dsr-routing.h.
Referenced by GetTypeId(), and ScheduleInterRequest().
m_cacheType
std::string ns3::dsr::DsrRouting::m_cacheType private
The type of route cache.
Definition at line 780 of file dsr-routing.h.
Referenced by GetTypeId(), and Start().
m_clearList
std::vector<Ipv4Address> ns3::dsr::DsrRouting::m_clearList private
The node that is clear to send packet to.
Definition at line 832 of file dsr-routing.h.
m_discoveryHopLimit
uint32_t ns3::dsr::DsrRouting::m_discoveryHopLimit private
Maximum hops to go for route request.
Definition at line 704 of file dsr-routing.h.
Referenced by GetTypeId(), RouteRequestTimerExpire(), SendErrorRequest(), and Start().
m_downTarget
IpL4Protocol::DownTargetCallback ns3::dsr::DsrRouting::m_downTarget private
The callback for down layer.
Definition at line 698 of file dsr-routing.h.
Referenced by ForwardErrPacket(), ForwardPacket(), GetDownTarget(), Receive(), Send(), SendErrorRequest(), SendInitialRequest(), SendPacketFromBuffer(), SendRealDown(), SendReply(), SendRequest(), and SetDownTarget().
m_dropTrace
TracedCallback<Ptr<const Packet> > ns3::dsr::DsrRouting::m_dropTrace protected
The trace for drop, receive and send data packets.
packet drop trace callback
Definition at line 654 of file dsr-routing.h.
Referenced by GetTypeId().
m_errorBuffer
DsrErrorBuffer ns3::dsr::DsrRouting::m_errorBuffer private
The error buffer to save the error messages.
Definition at line 730 of file dsr-routing.h.
Referenced by AddRoute(), AddRoute_Link(), SendPacketFromBuffer(), SendUnreachError(), and Start().
m_finalRoute
std::vector<Ipv4Address> ns3::dsr::DsrRouting::m_finalRoute private
The route cache.
Definition at line 798 of file dsr-routing.h.
Referenced by SendGratuitousReply().
m_graReply
DsrGraReply ns3::dsr::DsrRouting::m_graReply private
The gratuitous route reply.
Definition at line 828 of file dsr-routing.h.
Referenced by SendGratuitousReply(), and Start().
m_graReplyTableSize
uint32_t ns3::dsr::DsrRouting::m_graReplyTableSize private
Set the gratuitous reply table size.
Definition at line 778 of file dsr-routing.h.
Referenced by GetTypeId(), and Start().
m_gratReplyHoldoff
Time ns3::dsr::DsrRouting::m_gratReplyHoldoff private
The max gratuitous reply hold off time.
Definition at line 774 of file dsr-routing.h.
Referenced by GetTypeId(), and SendGratuitousReply().
m_initStability
Time ns3::dsr::DsrRouting::m_initStability private
The initial stability value for link cache.
Definition at line 788 of file dsr-routing.h.
Referenced by GetTypeId(), and Start().
m_ip
Ptr<Ipv4> ns3::dsr::DsrRouting::m_ip private
The ip ptr.
Definition at line 690 of file dsr-routing.h.
Referenced by CheckSendBuffer(), ForwardErrPacket(), NotifyNewAggregate(), Receive(), SalvagePacket(), SendPacket(), SendPacketFromBuffer(), and SendUnreachError().
m_ipv4
Ptr<Ipv4L3Protocol> ns3::dsr::DsrRouting::m_ipv4 private
Ipv4l3Protocol.
Definition at line 686 of file dsr-routing.h.
Referenced by DoDispose(), NotifyNewAggregate(), PromiscReceive(), SendReply(), and Start().
m_ipv4Route
Ptr<Ipv4Route> ns3::dsr::DsrRouting::m_ipv4Route private
Ipv4 Route.
Definition at line 688 of file dsr-routing.h.
Referenced by CheckSendBuffer(), SalvagePacket(), SendGratuitousReply(), SendPacket(), SendPacketFromBuffer(), SendUnreachError(), and SetRoute().
m_linkAck
bool ns3::dsr::DsrRouting::m_linkAck private
define if we use link acknowledgement or not
Definition at line 824 of file dsr-routing.h.
Referenced by CheckSendBuffer(), ForwardPacket(), GetTypeId(), PacketNewRoute(), Send(), and SendPacketFromBuffer().
m_linkAckTimeout
Time ns3::dsr::DsrRouting::m_linkAckTimeout private
The timeout value for link acknowledge.
Definition at line 766 of file dsr-routing.h.
Referenced by GetTypeId(), and ScheduleLinkPacketRetry().
m_linkAckTimer
std::map<LinkKey, Timer> ns3::dsr::DsrRouting::m_linkAckTimer private
The timer for link acknowledgment.
Definition at line 814 of file dsr-routing.h.
Referenced by CancelLinkPacketTimer(), LinkScheduleTimerExpire(), and ScheduleLinkPacketRetry().
m_linkCnt
std::map<LinkKey, uint32_t> ns3::dsr::DsrRouting::m_linkCnt private
Map packet key + link forward counts.
Definition at line 812 of file dsr-routing.h.
Referenced by CancelLinkPacketTimer(), CheckSendBuffer(), ForwardPacket(), LinkScheduleTimerExpire(), PacketNewRoute(), Send(), and SendPacketFromBuffer().
m_linkRetries
uint32_t ns3::dsr::DsrRouting::m_linkRetries private
of retries have been sent for link acknowledgment
Definition at line 716 of file dsr-routing.h.
Referenced by LinkScheduleTimerExpire().
m_macToNodeIdMap
std::map<std::string, uint32_t> ns3::dsr::DsrRouting::m_macToNodeIdMap private
The map of mac address to node id.
Definition at line 836 of file dsr-routing.h.
m_mainAddress
Ipv4Address ns3::dsr::DsrRouting::m_mainAddress private
Our own Ip address.
Definition at line 694 of file dsr-routing.h.
Referenced by AddRoute(), CheckSendBuffer(), ForwardErrPacket(), ForwardPacket(), LinkScheduleTimerExpire(), NetworkScheduleTimerExpire(), PacketNewRoute(), PassiveScheduleTimerExpire(), PromiscReceive(), Receive(), RouteRequestTimerExpire(), SalvagePacket(), ScheduleInterRequest(), Send(), SendErrorRequest(), SendGratuitousReply(), SendInitialRequest(), SendPacket(), SendPacketFromBuffer(), SendReply(), SendUnreachError(), and Start().
m_maintainBuffer
DsrMaintainBuffer ns3::dsr::DsrRouting::m_maintainBuffer private
The declaration of maintain buffer.
Definition at line 744 of file dsr-routing.h.
Referenced by CancelLinkPacketTimer(), CancelNetworkPacketTimer(), CancelPacketTimerNextHop(), CancelPassiveTimer(), CheckSendBuffer(), ForwardPacket(), PacketNewRoute(), ScheduleNetworkPacketRetry(), Send(), SendPacketFromBuffer(), and Start().
m_maxCacheLen
uint32_t ns3::dsr::DsrRouting::m_maxCacheLen private
Max # of cache entries for route cache.
Definition at line 736 of file dsr-routing.h.
Referenced by GetTypeId(), and Start().
m_maxCacheTime
Time ns3::dsr::DsrRouting::m_maxCacheTime private
Max time for caching the route cache entry.
Definition at line 738 of file dsr-routing.h.
Referenced by GetTypeId(), and Start().
m_maxEntriesEachDst
uint32_t ns3::dsr::DsrRouting::m_maxEntriesEachDst private
Max number of route entries to save for each destination.
Definition at line 742 of file dsr-routing.h.
Referenced by GetTypeId(), and Start().
m_maxMaintainLen
uint32_t ns3::dsr::DsrRouting::m_maxMaintainLen private
Max # of entries for maintenance buffer.
Definition at line 732 of file dsr-routing.h.
Referenced by GetTypeId(), and Start().
m_maxMaintainTime
Time ns3::dsr::DsrRouting::m_maxMaintainTime private
Time out for maintenance buffer.
Definition at line 734 of file dsr-routing.h.
Referenced by CheckSendBuffer(), ForwardPacket(), GetTypeId(), PacketNewRoute(), ScheduleNetworkPacketRetry(), Send(), SendPacketFromBuffer(), and Start().
m_maxMaintRexmt
uint32_t ns3::dsr::DsrRouting::m_maxMaintRexmt private
Maximum number of retransmissions of data packets.
Definition at line 720 of file dsr-routing.h.
Referenced by GetTypeId(), and NetworkScheduleTimerExpire().
m_maxNetworkDelay
Time ns3::dsr::DsrRouting::m_maxNetworkDelay private
Maximum network delay.
Definition at line 702 of file dsr-routing.h.
Referenced by GetTypeId(), and Start().
m_maxNetworkSize
uint32_t ns3::dsr::DsrRouting::m_maxNetworkSize private
Maximum network queue size.
Definition at line 700 of file dsr-routing.h.
Referenced by GetTypeId(), and Start().
m_maxRequestPeriod
Time ns3::dsr::DsrRouting::m_maxRequestPeriod private
The max request period.
Definition at line 776 of file dsr-routing.h.
Referenced by GetTypeId(), and ScheduleRreqRetry().
m_maxRreqId
uint32_t ns3::dsr::DsrRouting::m_maxRreqId private
The max number of request ids for a single destination.
Definition at line 754 of file dsr-routing.h.
Referenced by GetTypeId(), and Start().
m_maxRreqTime
Time ns3::dsr::DsrRouting::m_maxRreqTime private
Max time for caching the route request entry.
Definition at line 740 of file dsr-routing.h.
m_maxSalvageCount
uint8_t ns3::dsr::DsrRouting::m_maxSalvageCount private
Maximum # times to salvage a packet.
Definition at line 706 of file dsr-routing.h.
Referenced by GetTypeId(), and SalvagePacket().
m_maxSendBuffLen
uint32_t ns3::dsr::DsrRouting::m_maxSendBuffLen private
The maximum number of packets that we allow a routing protocol to buffer.
Definition at line 724 of file dsr-routing.h.
Referenced by GetTypeId(), and Start().
m_minLifeTime
Time ns3::dsr::DsrRouting::m_minLifeTime private
The min life time.
Definition at line 790 of file dsr-routing.h.
Referenced by GetTypeId(), and Start().
m_networkQueue
DsrNetworkQueue ns3::dsr::DsrRouting::m_networkQueue private
The network queue.
Definition at line 830 of file dsr-routing.h.
m_node
Ptr<Node> ns3::dsr::DsrRouting::m_node private
The node ptr.
Definition at line 692 of file dsr-routing.h.
Referenced by DoDispose(), GetNode(), NotifyNewAggregate(), and SetNode().
m_nodeTraversalTime
Time ns3::dsr::DsrRouting::m_nodeTraversalTime private
Time estimated for packet to travel between two nodes.
Definition at line 722 of file dsr-routing.h.
Referenced by GetTypeId(), ScheduleCachedReply(), and ScheduleNetworkPacketRetry().
m_nonPropReqTimer
std::map<Ipv4Address, Timer> ns3::dsr::DsrRouting::m_nonPropReqTimer private
Map IP address + RREQ timer.
Definition at line 802 of file dsr-routing.h.
Referenced by CancelRreqTimer(), PacketNewRoute(), ScheduleRreqRetry(), Send(), SendErrorRequest(), and SendUnreachError().
m_nonpropRequestTimeout
Time ns3::dsr::DsrRouting::m_nonpropRequestTimeout private
The non-propagation request timeout.
Definition at line 710 of file dsr-routing.h.
Referenced by GetTypeId(), and ScheduleRreqRetry().
m_numPriorityQueues
uint32_t ns3::dsr::DsrRouting::m_numPriorityQueues private
The number of priority queues used.
Definition at line 822 of file dsr-routing.h.
Referenced by GetTypeId(), PriorityScheduler(), and Start().
m_options
DsrOptionList_t ns3::dsr::DsrRouting::m_options private
List of DSR Options supported.
Definition at line 684 of file dsr-routing.h.
Referenced by GetOption(), and Insert().
m_passiveAckTimeout
Time ns3::dsr::DsrRouting::m_passiveAckTimeout private
The timeout value for passive acknowledge.
Definition at line 762 of file dsr-routing.h.
Referenced by GetTypeId(), and SchedulePassivePacketRetry().
m_passiveAckTimer
std::map<PassiveKey, Timer> ns3::dsr::DsrRouting::m_passiveAckTimer private
The timer for passive acknowledgment.
Definition at line 810 of file dsr-routing.h.
Referenced by CancelPassivePacketTimer(), PassiveScheduleTimerExpire(), and SchedulePassivePacketRetry().
m_passiveBuffer
Ptr<dsr::DsrPassiveBuffer> ns3::dsr::DsrRouting::m_passiveBuffer private
A "drop-front" queue used by the routing layer to cache route request sent.
Definition at line 820 of file dsr-routing.h.
Referenced by GetPassiveBuffer(), PassiveEntryCheck(), and SetPassiveBuffer().
m_passiveCnt
std::map<PassiveKey, uint32_t> ns3::dsr::DsrRouting::m_passiveCnt private
Map packet key + passive forward counts.
Definition at line 808 of file dsr-routing.h.
Referenced by CancelPassivePacketTimer(), CheckSendBuffer(), ForwardPacket(), PacketNewRoute(), PassiveScheduleTimerExpire(), Send(), and SendPacketFromBuffer().
m_passiveRetries
uint32_t ns3::dsr::DsrRouting::m_passiveRetries private
of retries have been sent for passive acknowledgment
Definition at line 714 of file dsr-routing.h.
Referenced by PassiveScheduleTimerExpire().
m_priorityQueue
std::map<uint32_t, Ptr<dsr::DsrNetworkQueue> > ns3::dsr::DsrRouting::m_priorityQueue private
priority queues
Definition at line 826 of file dsr-routing.h.
Referenced by CheckSendBuffer(), ForwardErrPacket(), IncreaseRetransTimer(), PriorityScheduler(), Receive(), SalvagePacket(), SendPacket(), SendPacketFromBuffer(), SendReply(), SendRequest(), SendUnreachError(), and Start().
m_requestId
uint32_t ns3::dsr::DsrRouting::m_requestId private
The id assigned to each route request.
Definition at line 746 of file dsr-routing.h.
Referenced by SendErrorRequest(), and SendInitialRequest().
m_requestPeriod
Time ns3::dsr::DsrRouting::m_requestPeriod private
The base time interval between route requests.
Definition at line 708 of file dsr-routing.h.
Referenced by GetTypeId(), and ScheduleRreqRetry().
m_requestTableIds
uint32_t ns3::dsr::DsrRouting::m_requestTableIds private
The request table identifiers.
Definition at line 752 of file dsr-routing.h.
Referenced by GetTypeId(), and Start().
m_requestTableSize
uint32_t ns3::dsr::DsrRouting::m_requestTableSize private
The max size of the request table size.
Definition at line 750 of file dsr-routing.h.
Referenced by GetTypeId(), and Start().
m_retransIncr
Time ns3::dsr::DsrRouting::m_retransIncr private
the increase time for retransmission timer when face network congestion
Definition at line 796 of file dsr-routing.h.
Referenced by GetTypeId(), and IncreaseRetransTimer().
m_routeCache
Ptr<dsr::DsrRouteCache> ns3::dsr::DsrRouting::m_routeCache private
A "drop-front" queue used by the routing layer to cache routes found.
Definition at line 816 of file dsr-routing.h.
Referenced by AddAckReqHeader(), AddRoute(), AddRoute_Link(), CheckSendBuffer(), DeleteAllRoutesIncludeLink(), DoDispose(), GetRouteCache(), IsLinkCache(), LinkScheduleTimerExpire(), LookupRoute(), NetworkScheduleTimerExpire(), PacketNewRoute(), RouteRequestTimerExpire(), SalvagePacket(), Send(), SendErrorRequest(), SendPacketFromBuffer(), SendUnreachError(), SetRouteCache(), UpdateRouteEntry(), and UseExtends().
m_routeSortType
std::string ns3::dsr::DsrRouting::m_routeSortType private
The type of route sort methods.
Definition at line 782 of file dsr-routing.h.
m_rreqRetries
uint32_t ns3::dsr::DsrRouting::m_rreqRetries private
Maximum number of retransmissions of RREQ with TTL = NetDiameter to discover a route.
Definition at line 718 of file dsr-routing.h.
Referenced by GetTypeId(), and RouteRequestTimerExpire().
m_rreqTable
Ptr<dsr::DsrRreqTable> ns3::dsr::DsrRouting::m_rreqTable private
A "drop-front" queue used by the routing layer to cache route request sent.
Definition at line 818 of file dsr-routing.h.
Referenced by CancelRreqTimer(), FindSourceEntry(), GetRequestTable(), RouteRequestTimerExpire(), ScheduleRreqRetry(), Send(), SendErrorRequest(), SendInitialRequest(), and SetRequestTable().
m_sendBuffer
DsrSendBuffer ns3::dsr::DsrRouting::m_sendBuffer private
The send buffer.
Definition at line 728 of file dsr-routing.h.
Referenced by CheckSendBuffer(), PacketNewRoute(), RouteRequestTimerExpire(), Send(), SendErrorRequest(), SendPacketFromBuffer(), and Start().
m_sendBufferTimeout
Time ns3::dsr::DsrRouting::m_sendBufferTimeout private
The maximum period of time that a routing protocol is allowed to buffer a packet for.
Definition at line 726 of file dsr-routing.h.
Referenced by GetTypeId(), PacketNewRoute(), Send(), SendUnreachError(), and Start().
m_sendBuffInterval
Time ns3::dsr::DsrRouting::m_sendBuffInterval private
how often to check send buffer
Definition at line 772 of file dsr-routing.h.
Referenced by CheckSendBuffer(), GetTypeId(), and SendBuffTimerExpire().
m_sendBuffTimer
Timer ns3::dsr::DsrRouting::m_sendBuffTimer private
The send buffer timer.
Definition at line 770 of file dsr-routing.h.
Referenced by DsrRouting(), CheckSendBuffer(), and SendBuffTimerExpire().
m_sendRetries
uint32_t ns3::dsr::DsrRouting::m_sendRetries private
of retries have been sent for network acknowledgment
Definition at line 712 of file dsr-routing.h.
Referenced by NetworkScheduleTimerExpire(), and ScheduleNetworkPacketRetry().
m_stabilityDecrFactor
uint32_t ns3::dsr::DsrRouting::m_stabilityDecrFactor private
The initial decrease factor for link cache.
Definition at line 784 of file dsr-routing.h.
Referenced by GetTypeId(), and Start().
m_stabilityIncrFactor
uint32_t ns3::dsr::DsrRouting::m_stabilityIncrFactor private
The initial increase factor for link cache.
Definition at line 786 of file dsr-routing.h.
Referenced by GetTypeId(), and Start().
m_subRoute
bool ns3::dsr::DsrRouting::m_subRoute private
Whether to save sub route or not.
Definition at line 794 of file dsr-routing.h.
Referenced by GetTypeId(), and Start().
m_tryLinkAcks
uint32_t ns3::dsr::DsrRouting::m_tryLinkAcks private
Maximum number of packet transmission using link acknowledgment.
Definition at line 768 of file dsr-routing.h.
Referenced by GetTypeId(), and LinkScheduleTimerExpire().
m_tryPassiveAcks
uint32_t ns3::dsr::DsrRouting::m_tryPassiveAcks private
Maximum number of packet transmission using passive acknowledgment.
Definition at line 764 of file dsr-routing.h.
Referenced by GetTypeId(), and PassiveScheduleTimerExpire().
m_txPacketTrace
TracedCallback<const DsrOptionSRHeader &> ns3::dsr::DsrRouting::m_txPacketTrace protected
packet trace callback
Definition at line 655 of file dsr-routing.h.
Referenced by GetTypeId().
m_uniformRandomVariable
Ptr<UniformRandomVariable> ns3::dsr::DsrRouting::m_uniformRandomVariable private
Provides uniform random variables.
Definition at line 838 of file dsr-routing.h.
Referenced by DsrRouting(), AssignStreams(), CancelPacketTimerNextHop(), PriorityScheduler(), ScheduleCachedReply(), ScheduleInterRequest(), Send(), and SendPacketFromBuffer().
m_useExtends
Time ns3::dsr::DsrRouting::m_useExtends private
The use extension of the life time for link cache.
Definition at line 792 of file dsr-routing.h.
Referenced by GetTypeId(), and Start().
PROT_NUMBER
const uint8_t ns3::dsr::DsrRouting::PROT_NUMBER = 48 static
Define the dsr protocol number.
Definition at line 106 of file dsr-routing.h.
Referenced by GetProtocolNumber(), and PromiscReceive().
segsLeft
uint8_t ns3::dsr::DsrRouting::segsLeft private
The segment left value from SR header.
Definition at line 696 of file dsr-routing.h.
Referenced by CancelPassiveTimer(), and PassiveEntryCheck().
The documentation for this class was generated from the following files:
src/dsr/model/dsr-routing.h
src/dsr/model/dsr-routing.cc