ns-3: ns3::LteHelper Class Reference
ns3::LteHelper Class Reference
LTE Models
Creation and configuration of LTE entities.
#include "lte-helper.h"
Public Member Functions
LteHelper (void)
virtual ~LteHelper (void)
void ActivateDataRadioBearer (NetDeviceContainer ueDevices, EpsBearer bearer)
Activate a Data Radio Bearer on a given UE devices (for LTE-only simulation).
void ActivateDataRadioBearer (Ptr< NetDevice > ueDevice, EpsBearer bearer)
Activate a Data Radio Bearer on a UE device (for LTE-only simulation).
uint8_t ActivateDedicatedEpsBearer (NetDeviceContainer ueDevices, EpsBearer bearer, Ptr< EpcTft > tft)
Activate a dedicated EPS bearer on a given set of UE devices.
uint8_t ActivateDedicatedEpsBearer (Ptr< NetDevice > ueDevice, EpsBearer bearer, Ptr< EpcTft > tft)
Activate a dedicated EPS bearer on a given UE device.
void AddX2Interface (NodeContainer enbNodes)
Create an X2 interface between all the eNBs in a given set.
void AddX2Interface (Ptr< Node > enbNode1, Ptr< Node > enbNode2)
Create an X2 interface between two eNBs.
int64_t AssignStreams (NetDeviceContainer c, int64_t stream)
Assign a fixed random variable stream number to the random variables used.
void Attach (NetDeviceContainer ueDevices)
Enables automatic attachment of a set of UE devices to a suitable cell using Idle mode initial cell selection procedure.
void Attach (NetDeviceContainer ueDevices, Ptr< NetDevice > enbDevice)
Manual attachment of a set of UE devices to the network via a given eNodeB.
void Attach (Ptr< NetDevice > ueDevice)
Enables automatic attachment of a UE device to a suitable cell using Idle mode initial cell selection procedure.
void Attach (Ptr< NetDevice > ueDevice, Ptr< NetDevice > enbDevice)
Manual attachment of a UE device to the network via a given eNodeB.
void AttachToClosestEnb (NetDeviceContainer ueDevices, NetDeviceContainer enbDevices)
Manual attachment of a set of UE devices to the network via the closest eNodeB (with respect to distance) among those in the set.
void AttachToClosestEnb (Ptr< NetDevice > ueDevice, NetDeviceContainer enbDevices)
Manual attachment of a UE device to the network via the closest eNodeB (with respect to distance) among those in the set.
void DeActivateDedicatedEpsBearer (Ptr< NetDevice > ueDevice, Ptr< NetDevice > enbDevice, uint8_t bearerId)
Manually trigger dedicated bearer de-activation at specific simulation time.
virtual void DoDispose (void)
Destructor implementation.
void EnableDlMacTraces (void)
Enable trace sinks for DL MAC layer.
void EnableDlPhyTraces (void)
Enable trace sinks for DL PHY layer.
void EnableDlRxPhyTraces (void)
Enable trace sinks for DL reception PHY layer.
void EnableDlTxPhyTraces (void)
Enable trace sinks for DL transmission PHY layer.
void EnableLogComponents (void)
Enables full-blown logging for major components of the LENA architecture.
void EnableMacTraces (void)
Enable trace sinks for MAC layer.
void EnablePdcpTraces (void)
Enable trace sinks for PDCP layer.
void EnablePhyTraces (void)
Enable trace sinks for PHY layer.
void EnableRlcTraces (void)
Enable trace sinks for RLC layer.
void EnableTraces (void)
Enables trace sinks for PHY, MAC, RLC and PDCP.
void EnableUlMacTraces (void)
Enable trace sinks for UL MAC layer.
void EnableUlPhyTraces (void)
Enable trace sinks for UL PHY layer.
void EnableUlRxPhyTraces (void)
Enable trace sinks for UL reception PHY layer.
void EnableUlTxPhyTraces (void)
Enable trace sinks for UL transmission PHY layer.
Ptr< SpectrumChannel > GetDownlinkSpectrumChannel (void) const
std::string GetEnbComponentCarrierManagerType () const
std::string GetFfrAlgorithmType () const
std::string GetHandoverAlgorithmType () const
Ptr< RadioBearerStatsCalculator > GetPdcpStats (void)
Ptr< RadioBearerStatsCalculator > GetRlcStats (void)
std::string GetSchedulerType () const
std::string GetUeComponentCarrierManagerType () const
Ptr< SpectrumChannel > GetUplinkSpectrumChannel (void) const
void HandoverRequest (Time hoTime, Ptr< NetDevice > ueDev, Ptr< NetDevice > sourceEnbDev, Ptr< NetDevice > targetEnbDev)
Manually trigger an X2-based handover.
void HandoverRequest (Time hoTime, Ptr< NetDevice > ueDev, Ptr< NetDevice > sourceEnbDev, uint16_t targetCellId)
Manually trigger an X2-based handover.
NetDeviceContainer InstallEnbDevice (NodeContainer c)
Create a set of eNodeB devices.
NetDeviceContainer InstallUeDevice (NodeContainer c)
Create a set of UE devices.
void SetEnbAntennaModelAttribute (std::string n, const AttributeValue &v)
Set an attribute for the eNodeB antenna model to be created.
void SetEnbAntennaModelType (std::string type)
Set the type of antenna model to be used by eNodeB devices.
void SetEnbComponentCarrierManagerAttribute (std::string n, const AttributeValue &v)
Set an attribute for the enb component carrier manager to be created.
void SetEnbComponentCarrierManagerType (std::string type)
Set the type of carrier component algorithm to be used by eNodeB devices.
void SetEnbDeviceAttribute (std::string n, const AttributeValue &v)
Set an attribute for the eNodeB devices (LteEnbNetDevice) to be created.
void SetEpcHelper (Ptr< EpcHelper > h)
Set the EpcHelper to be used to setup the EPC network in conjunction with the setup of the LTE radio access network.
void SetFadingModel (std::string type)
Set the type of fading model to be used in both DL and UL.
void SetFadingModelAttribute (std::string n, const AttributeValue &v)
Set an attribute for the fading model to be created (both DL and UL).
void SetFfrAlgorithmAttribute (std::string n, const AttributeValue &v)
Set an attribute for the FFR algorithm to be created.
void SetFfrAlgorithmType (std::string type)
Set the type of FFR algorithm to be used by eNodeB devices.
void SetHandoverAlgorithmAttribute (std::string n, const AttributeValue &v)
Set an attribute for the handover algorithm to be created.
void SetHandoverAlgorithmType (std::string type)
Set the type of handover algorithm to be used by eNodeB devices.
void SetPathlossModelAttribute (std::string n, const AttributeValue &v)
Set an attribute for the path loss models to be created.
void SetPathlossModelType (TypeId type)
Set the type of path loss model to be used for both DL and UL channels.
void SetSchedulerAttribute (std::string n, const AttributeValue &v)
Set an attribute for the scheduler to be created.
void SetSchedulerType (std::string type)
Set the type of scheduler to be used by eNodeB devices.
void SetSpectrumChannelAttribute (std::string n, const AttributeValue &v)
Set an attribute for the spectrum channel to be created (both DL and UL).
void SetSpectrumChannelType (std::string type)
Set the type of spectrum channel to be used in both DL and UL.
void SetUeAntennaModelAttribute (std::string n, const AttributeValue &v)
Set an attribute for the UE antenna model to be created.
void SetUeAntennaModelType (std::string type)
Set the type of antenna model to be used by UE devices.
void SetUeComponentCarrierManagerAttribute (std::string n, const AttributeValue &v)
Set an attribute for the ue component carrier manager to be created.
void SetUeComponentCarrierManagerType (std::string type)
Set the type of Component Carrier Manager to be used by Ue devices.
void SetUeDeviceAttribute (std::string n, const AttributeValue &v)
Set an attribute for the UE devices (LteUeNetDevice) to be created.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void ChannelModelInitialization (void)
Function that performs a channel model initialization of all component carriers.
void DoComponentCarrierConfigure (uint32_t ulEarfcn, uint32_t dlEarfcn, uint16_t ulbw, uint16_t dlbw)
Configure the component carriers.
void DoDeActivateDedicatedEpsBearer (Ptr< NetDevice > ueDevice, Ptr< NetDevice > enbDevice, uint8_t bearerId)
The actual function to trigger a manual bearer de-activation.
void DoHandoverRequest (Ptr< NetDevice > ueDev, Ptr< NetDevice > sourceEnbDev, uint16_t targetCellId)
The actual function to trigger a manual handover.
Ptr< NetDevice > InstallSingleEnbDevice (Ptr< Node > n)
Create an eNodeB device (LteEnbNetDevice) on the given node.
Ptr< NetDevice > InstallSingleUeDevice (Ptr< Node > n)
Create a UE device (LteUeNetDevice) on the given node.
Private Attributes
uint16_t m_cellIdCounter
Keep track of the number of cell ID allocated.
ObjectFactory m_channelFactory
Factory of both the downlink and uplink LTE channels.
std::map< uint8_t, ComponentCarrier > m_componentCarrierPhyParams
This contains all the information about each component carrier.
Ptr< SpectrumChannel > m_downlinkChannel
This function create the component carrier based on provided configuration parameters.
Ptr< Object > m_downlinkPathlossModel
The path loss model used in the downlink channel.
ObjectFactory m_enbAntennaModelFactory
Factory of antenna object for eNodeB.
ObjectFactory m_enbComponentCarrierManagerFactory
Factory of enb component carrier manager object.
ObjectFactory m_enbNetDeviceFactory
Factory of LteEnbNetDevice objects.
Ptr< EpcHelper > m_epcHelper
Helper which provides implementation of core network.
Ptr< SpectrumPropagationLossModel > m_fadingModel
The fading model used in both the downlink and uplink channels.
ObjectFactory m_fadingModelFactory
Factory of fading model object for both the downlink and uplink channels.
std::string m_fadingModelType
Name of fading model type, e.g., "ns3::TraceFadingLossModel".
bool m_fadingStreamsAssigned
True if a random variable stream number has been assigned for the fading model.
ObjectFactory m_ffrAlgorithmFactory
Factory of FFR (frequency reuse) algorithm object.
ObjectFactory m_handoverAlgorithmFactory
Factory of handover algorithm object.
uint64_t m_imsiCounter
Keep track of the number of IMSI allocated.
bool m_isAnrEnabled
The AnrEnabled attribute.
Ptr< MacStatsCalculator > m_macStats
Container of MAC layer statistics.
uint16_t m_noOfCcs
Number of component carriers that will be installed by default at eNodeB and UE devices.
ObjectFactory m_pathlossModelFactory
Factory of path loss model object.
Ptr< RadioBearerStatsCalculator > m_pdcpStats
Container of PDCP layer statistics.
Ptr< PhyRxStatsCalculator > m_phyRxStats
Container of PHY layer statistics related to reception.
Ptr< PhyStatsCalculator > m_phyStats
Container of PHY layer statistics.
Ptr< PhyTxStatsCalculator > m_phyTxStats
Container of PHY layer statistics related to transmission.
RadioBearerStatsConnector m_radioBearerStatsConnector
Connects RLC and PDCP statistics containers to appropriate trace sources.
Ptr< RadioBearerStatsCalculator > m_rlcStats
Container of RLC layer statistics.
ObjectFactory m_schedulerFactory
Factory of MAC scheduler object.
ObjectFactory m_ueAntennaModelFactory
Factory of antenna object for UE.
ObjectFactory m_ueComponentCarrierManagerFactory
Factory of ue component carrier manager object.
ObjectFactory m_ueNetDeviceFactory
Factory for LteUeNetDevice objects.
Ptr< SpectrumChannel > m_uplinkChannel
The uplink LTE channel used in the simulation.
Ptr< Object > m_uplinkPathlossModel
The path loss model used in the uplink channel.
bool m_useCa
The UseCa attribute.
bool m_useIdealRrc
The UseIdealRrc attribute.
bool m_usePdschForCqiGeneration
The UsePdschForCqiGeneration attribute.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Creation and configuration of LTE entities.
Introspection did not find any typical Config paths.
One LteHelper instance is typically enough for an LTE simulation. To create it:
Ptr<LteHelper> lteHelper = CreateObject<LteHelper> ();
The general responsibility of the helper is to create various LTE objects and arrange them together to make the whole LTE system. The overall arrangement would look like the following:
Downlink spectrum channel
Path loss model
Fading model
Uplink spectrum channel
Path loss model
Fading model
eNodeB node(s)
Mobility model
eNodeB device(s)
Antenna model
eNodeB PHY (includes spectrum PHY, interference model, HARQ model)
eNodeB MAC
eNodeB RRC (includes RRC protocol)
Scheduler
Handover algorithm
FFR (frequency reuse) algorithm
ANR (automatic neighbour relation)
CCM (Carrier Component Manager)
EPC related models (EPC application, Internet stack, X2 interface)
UE node(s)
Mobility model
UE device(s)
Antenna model
UE PHY (includes spectrum PHY, interference model, HARQ model)
UE MAC
UE RRC (includes RRC protocol)
NAS
EPC helper
Various statistics calculator objects
Spetrum channels are created automatically: one for DL, and one for UL. eNodeB devices are created by calling InstallEnbDevice(), while UE devices are created by calling InstallUeDevice(). EPC helper can be set by using SetEpcHelper().
Attributes
Scheduler: The type of scheduler to be used for eNBs. The allowed values for this attributes are the type names of any class inheriting from ns3::FfMacScheduler.
Set with class: StringValue
Underlying type:
Initial value: ns3::PfFfMacScheduler
Flags: construct write read
FfrAlgorithm: The type of FFR algorithm to be used for eNBs. The allowed values for this attributes are the type names of any class inheriting from ns3::LteFfrAlgorithm.
Set with class: StringValue
Underlying type:
Initial value: ns3::LteFrNoOpAlgorithm
Flags: construct write read
HandoverAlgorithm: The type of handover algorithm to be used for eNBs. The allowed values for this attributes are the type names of any class inheriting from ns3::LteHandoverAlgorithm.
Set with class: StringValue
Underlying type:
Initial value: ns3::NoOpHandoverAlgorithm
Flags: construct write read
PathlossModel: The type of pathloss model to be used. The allowed values for this attributes are the type names of any class inheriting from ns3::PropagationLossModel.
Set with class: TypeIdValue
Underlying type: TypeId
Initial value: ns3::FriisPropagationLossModel
Flags: construct write
FadingModel: The type of fading model to be used.The allowed values for this attributes are the type names of any class inheriting from ns3::SpectrumPropagationLossModel.If the type is set to an empty string, no fading model is used.
Set with class: StringValue
Underlying type:
Initial value:
Flags: construct write
UseIdealRrc: If true, LteRrcProtocolIdeal will be used for RRC signaling. If false, LteRrcProtocolReal will be used.
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
AnrEnabled: Activate or deactivate Automatic Neighbour Relation function
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
UsePdschForCqiGeneration: If true, DL-CQI will be calculated from PDCCH as signal and PDSCH as interference If false, DL-CQI will be calculated from PDCCH as signal and PDCCH as interference
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
EnbComponentCarrierManager: The type of Component Carrier Manager to be used for eNBs. The allowed values for this attributes are the type names of any class inheriting ns3::LteEnbComponentCarrierManager.
Set with class: StringValue
Underlying type:
Initial value: ns3::NoOpComponentCarrierManager
Flags: construct write read
UeComponentCarrierManager: The type of Component Carrier Manager to be used for UEs. The allowed values for this attributes are the type names of any class inheriting ns3::LteUeComponentCarrierManager.
Set with class: StringValue
Underlying type:
Initial value: ns3::SimpleUeComponentCarrierManager
Flags: construct write read
UseCa: If true, Carrier Aggregation feature is enabled and a valid Component Carrier Map is expected.If false, single carrier simulation.
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
NumberOfComponentCarriers: Set the number of Component carrier to use If it is more than one and m_useCa is false, it will raise an error
Set with class: ns3::UintegerValue
Underlying type: uint16_t 1:5
Initial value: 1
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 640 bytes (on a 64-bit architecture).
Definition at line 102 of file lte-helper.h.
Constructor & Destructor Documentation
LteHelper()
ns3::LteHelper::LteHelper (void)
Definition at line 75 of file lte-helper.cc.
References ns3::IsotropicAntennaModel::GetTypeId(), ns3::LteEnbNetDevice::GetTypeId(), ns3::LteUeNetDevice::GetTypeId(), ns3::MultiModelSpectrumChannel::GetTypeId(), m_channelFactory, m_enbAntennaModelFactory, m_enbNetDeviceFactory, m_ueAntennaModelFactory, m_ueNetDeviceFactory, NS_LOG_FUNCTION, and ns3::ObjectFactory::SetTypeId().
~LteHelper()
ns3::LteHelper::~LteHelper (void) virtual
Definition at line 101 of file lte-helper.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
ActivateDataRadioBearer() [1/2]
void ns3::LteHelper::ActivateDataRadioBearer (NetDeviceContainer ueDevices, EpsBearer bearer)
Activate a Data Radio Bearer on a given UE devices (for LTE-only simulation).
Parameters
ueDevices the set of UE devices
bearer the characteristics of the bearer to be activated
Definition at line 1314 of file lte-helper.cc.
References ns3::NetDeviceContainer::Begin(), ns3::NetDeviceContainer::End(), and NS_LOG_FUNCTION.
Referenced by LteRrcConnectionEstablishmentTestCase::Connect(), LteUeMeasurementsPiecewiseTestCase1::DoRun(), LteUeMeasurementsPiecewiseTestCase2::DoRun(), LteUeMeasurementsPiecewiseTestCase3::DoRun(), CarrierAggregationConfigTestCase::DoRun(), CarrierAggregationTestCase::DoRun(), LteCqiGenerationTestCase::DoRun(), LteCqiGenerationDlPowerControlTestCase::DoRun(), LteDownlinkPowerControlTestCase::DoRun(), LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::DoRun(), LenaFdBetFfMacSchedulerTestCase1::DoRun(), LenaFdBetFfMacSchedulerTestCase2::DoRun(), LenaFdMtFfMacSchedulerTestCase::DoRun(), LteHardFrTestCase::DoRun(), LteStrictFrTestCase::DoRun(), LteStrictFrAreaTestCase::DoRun(), LteSoftFrAreaTestCase::DoRun(), LteSoftFfrAreaTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), LenaHarqTestCase::DoRun(), LteInterferenceHardFrTestCase::DoRun(), LteInterferenceStrictFrTestCase::DoRun(), LteInterferenceTestCase::DoRun(), LteLinkAdaptationTestCase::DoRun(), LenaMimoTestCase::DoRun(), LtePathlossModelSystemTestCase::DoRun(), LenaPfFfMacSchedulerTestCase1::DoRun(), LenaPfFfMacSchedulerTestCase2::DoRun(), LenaDataPhyErrorModelTestCase::DoRun(), LenaDlCtrlPhyErrorModelTestCase::DoRun(), LenaRrFfMacSchedulerTestCase::DoRun(), LenaTdBetFfMacSchedulerTestCase1::DoRun(), LenaTdBetFfMacSchedulerTestCase2::DoRun(), LenaTdMtFfMacSchedulerTestCase::DoRun(), LenaTtaFfMacSchedulerTestCase::DoRun(), LteUeMeasurementsTestCase::DoRun(), LteUplinkOpenLoopPowerControlTestCase::DoRun(), LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun(), LteEnbAntennaTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), and LteX2HandoverTestCase::DoRun().
ActivateDataRadioBearer() [2/2]
void ns3::LteHelper::ActivateDataRadioBearer (Ptr< NetDevice > ueDevice, EpsBearer bearer)
Activate a Data Radio Bearer on a UE device (for LTE-only simulation).
This method will schedule the actual activation the bearer so that it happens after the UE got connected.
Parameters
ueDevice the UE device
bearer the characteristics of the bearer to be activated
Definition at line 1199 of file lte-helper.cc.
References ns3::DrbActivator::ActivateCallback(), ns3::Config::Connect(), ns3::Node::GetId(), ns3::LteNetDevice::GetIfIndex(), ns3::LteNetDevice::GetNode(), m_epcHelper, ns3::MakeBoundCallback(), NS_ASSERT_MSG, and NS_LOG_FUNCTION.
ActivateDedicatedEpsBearer() [1/2]
uint8_t ns3::LteHelper::ActivateDedicatedEpsBearer (NetDeviceContainer ueDevices, EpsBearer bearer, Ptr< EpcTft > tft)
Activate a dedicated EPS bearer on a given set of UE devices.
Parameters
ueDevices the set of UE devices
bearer the characteristics of the bearer to be activated
tft the Traffic Flow Template that identifies the traffic to go on this bearer
Returns
bearer ID
Definition at line 1069 of file lte-helper.cc.
References ns3::NetDeviceContainer::Begin(), ns3::NetDeviceContainer::End(), and NS_LOG_FUNCTION.
Referenced by LteRadioLinkFailureTestCase::DoRun(), LenaCqaFfMacSchedulerTestCase1::DoRun(), LenaCqaFfMacSchedulerTestCase2::DoRun(), ns3::LenaDeactivateBearerTestCase::DoRun(), LenaFdTbfqFfMacSchedulerTestCase1::DoRun(), LenaFdTbfqFfMacSchedulerTestCase2::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LenaPssFfMacSchedulerTestCase1::DoRun(), LenaPssFfMacSchedulerTestCase2::DoRun(), LenaTdTbfqFfMacSchedulerTestCase1::DoRun(), LenaTdTbfqFfMacSchedulerTestCase2::DoRun(), LteEpcE2eDataTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), and LteX2HandoverTestCase::DoRun().
ActivateDedicatedEpsBearer() [2/2]
uint8_t ns3::LteHelper::ActivateDedicatedEpsBearer (Ptr< NetDevice > ueDevice, EpsBearer bearer, Ptr< EpcTft > tft)
Activate a dedicated EPS bearer on a given UE device.
Parameters
ueDevice the UE device
bearer the characteristics of the bearer to be activated
tft the Traffic Flow Template that identifies the traffic to go on this bearer.
Returns
bearer ID
Definition at line 1082 of file lte-helper.cc.
References m_epcHelper, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
AddX2Interface() [1/2]
void ns3::LteHelper::AddX2Interface (NodeContainer enbNodes)
Create an X2 interface between all the eNBs in a given set.
Parameters
enbNodes the set of eNB nodes
Definition at line 1221 of file lte-helper.cc.
References ns3::NodeContainer::Begin(), ns3::NodeContainer::End(), m_epcHelper, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
Referenced by LteUeMeasurementsHandoverTestCase::DoRun(), LteHandoverTargetTestCase::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), and LteX2HandoverTestCase::DoRun().
AddX2Interface() [2/2]
void ns3::LteHelper::AddX2Interface (Ptr< Node > enbNode1, Ptr< Node > enbNode2)
Create an X2 interface between two eNBs.
Parameters
enbNode1 one eNB of the X2 interface
enbNode2 the other eNB of the X2 interface
Definition at line 1237 of file lte-helper.cc.
References m_epcHelper, NS_LOG_FUNCTION, and NS_LOG_INFO.
AssignStreams()
int64_t ns3::LteHelper::AssignStreams (NetDeviceContainer c, int64_t stream)
Assign a fixed random variable stream number to the random variables used.
The InstallEnbDevice() or InstallUeDevice method should have previously been called by the user on the given devices.
If TraceFadingLossModel has been set as the fading model type, this method will also assign a stream number to it, if none has been assigned before.
Parameters
c NetDeviceContainer of the set of net devices for which the LteNetDevice should be modified to use a fixed stream
stream first stream index to use
Returns
the number of stream indices (possibly zero) that have been assigned
Definition at line 1444 of file lte-helper.cc.
References ns3::NetDeviceContainer::Begin(), ns3::NetDeviceContainer::End(), ns3::LteEnbNetDevice::GetCcMap(), m_fadingModel, and m_fadingStreamsAssigned.
Referenced by LteCellSelectionTestCase::DoRun(), LteRadioLinkFailureTestCase::DoRun(), CarrierAggregationConfigTestCase::DoRun(), LenaDataPhyErrorModelTestCase::DoRun(), LenaDlCtrlPhyErrorModelTestCase::DoRun(), LteRrcConnectionEstablishmentTestCase::DoRun(), LteRrcConnectionEstablishmentErrorTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), and LteX2HandoverTestCase::DoRun().
Attach() [1/4]
void ns3::LteHelper::Attach (NetDeviceContainer ueDevices)
Enables automatic attachment of a set of UE devices to a suitable cell using Idle mode initial cell selection procedure.
Parameters
ueDevices the set of UE devices to be attached
By calling this, the UE will start the initial cell selection procedure at the beginning of simulation. In addition, the function also instructs each UE to immediately enter CONNECTED mode and activates the default EPS bearer.
If this function is called when the UE is in a situation where entering CONNECTED mode is not possible (e.g. before the simulation begin), then the UE will attempt to connect at the earliest possible time (e.g. after it camps to a suitable cell).
Note that this function can only be used in EPC-enabled simulation.
Definition at line 961 of file lte-helper.cc.
References ns3::NetDeviceContainer::Begin(), ns3::NetDeviceContainer::End(), and NS_LOG_FUNCTION.
Referenced by Attach(), AttachToClosestEnb(), LteRrcConnectionEstablishmentTestCase::Connect(), LteCellSelectionTestCase::DoRun(), LteRadioLinkFailureTestCase::DoRun(), LteUeMeasurementsPiecewiseTestCase1::DoRun(), LteUeMeasurementsPiecewiseTestCase2::DoRun(), LteUeMeasurementsPiecewiseTestCase3::DoRun(), LteUeMeasurementsHandoverTestCase::DoRun(), LteHandoverTargetTestCase::DoRun(), CarrierAggregationConfigTestCase::DoRun(), CarrierAggregationTestCase::DoRun(), LenaCqaFfMacSchedulerTestCase1::DoRun(), LenaCqaFfMacSchedulerTestCase2::DoRun(), LteCqiGenerationTestCase::DoRun(), LteCqiGenerationDlPowerControlTestCase::DoRun(), ns3::LenaDeactivateBearerTestCase::DoRun(), LteDownlinkPowerControlTestCase::DoRun(), LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::DoRun(), LenaFdBetFfMacSchedulerTestCase1::DoRun(), LenaFdBetFfMacSchedulerTestCase2::DoRun(), LenaFdMtFfMacSchedulerTestCase::DoRun(), LenaFdTbfqFfMacSchedulerTestCase1::DoRun(), LenaFdTbfqFfMacSchedulerTestCase2::DoRun(), LteHardFrTestCase::DoRun(), LteStrictFrTestCase::DoRun(), LteStrictFrAreaTestCase::DoRun(), LteSoftFrAreaTestCase::DoRun(), LteSoftFfrAreaTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LenaHarqTestCase::DoRun(), LteInterferenceHardFrTestCase::DoRun(), LteInterferenceStrictFrTestCase::DoRun(), LteInterferenceTestCase::DoRun(), LteIpv6RoutingTestCase::DoRun(), LteLinkAdaptationTestCase::DoRun(), LenaMimoTestCase::DoRun(), LtePathlossModelSystemTestCase::DoRun(), LenaPfFfMacSchedulerTestCase1::DoRun(), LenaPfFfMacSchedulerTestCase2::DoRun(), LenaDataPhyErrorModelTestCase::DoRun(), LenaDlCtrlPhyErrorModelTestCase::DoRun(), LenaPssFfMacSchedulerTestCase1::DoRun(), LenaPssFfMacSchedulerTestCase2::DoRun(), LenaRrFfMacSchedulerTestCase::DoRun(), LenaTdBetFfMacSchedulerTestCase1::DoRun(), LenaTdBetFfMacSchedulerTestCase2::DoRun(), LenaTdMtFfMacSchedulerTestCase::DoRun(), LenaTdTbfqFfMacSchedulerTestCase1::DoRun(), LenaTdTbfqFfMacSchedulerTestCase2::DoRun(), LenaTtaFfMacSchedulerTestCase::DoRun(), LteUeMeasurementsTestCase::DoRun(), LteUplinkOpenLoopPowerControlTestCase::DoRun(), LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun(), LteEnbAntennaTestCase::DoRun(), LteEpcE2eDataTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), and LteX2HandoverTestCase::DoRun().
Attach() [2/4]
void ns3::LteHelper::Attach (NetDeviceContainer ueDevices, Ptr< NetDevice > enbDevice)
Manual attachment of a set of UE devices to the network via a given eNodeB.
Parameters
ueDevices the set of UE devices to be attached
enbDevice the destination eNodeB device
In addition, the function also instructs each UE to immediately enter CONNECTED mode and activates the default EPS bearer.
The function can be used in both LTE-only and EPC-enabled simulations. Note that this function will disable Idle mode initial cell selection procedure.
Definition at line 1002 of file lte-helper.cc.
References Attach(), ns3::NetDeviceContainer::Begin(), ns3::NetDeviceContainer::End(), and NS_LOG_FUNCTION.
Attach() [3/4]
void ns3::LteHelper::Attach (Ptr< NetDevice > ueDevice)
Enables automatic attachment of a UE device to a suitable cell using Idle mode initial cell selection procedure.
Parameters
ueDevice the UE device to be attached
By calling this, the UE will start the initial cell selection procedure at the beginning of simulation. In addition, the function also instructs the UE to immediately enter CONNECTED mode and activates the default EPS bearer.
If this function is called when the UE is in a situation where entering CONNECTED mode is not possible (e.g. before the simulation begin), then the UE will attempt to connect at the earliest possible time (e.g. after it camps to a suitable cell).
Note that this function can only be used in EPC-enabled simulation.
Definition at line 971 of file lte-helper.cc.
References ns3::EpcTft::Default(), m_epcHelper, ns3::EpsBearer::NGBR_VIDEO_TCP_DEFAULT, NS_ASSERT, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
Attach() [4/4]
void ns3::LteHelper::Attach (Ptr< NetDevice > ueDevice, Ptr< NetDevice > enbDevice)
Manual attachment of a UE device to the network via a given eNodeB.
Parameters
ueDevice the UE device to be attached
enbDevice the destination eNodeB device
In addition, the function also instructs the UE to immediately enter CONNECTED mode and activates the default EPS bearer.
The function can be used in both LTE-only and EPC-enabled simulations. Note that this function will disable Idle mode initial cell selection procedure.
Definition at line 1012 of file lte-helper.cc.
References ns3::EpcTft::Default(), m_epcHelper, ns3::EpsBearer::NGBR_VIDEO_TCP_DEFAULT, and NS_LOG_FUNCTION.
AttachToClosestEnb() [1/2]
void ns3::LteHelper::AttachToClosestEnb (NetDeviceContainer ueDevices, NetDeviceContainer enbDevices)
Manual attachment of a set of UE devices to the network via the closest eNodeB (with respect to distance) among those in the set.
Parameters
ueDevices the set of UE devices to be attached
enbDevices the set of eNodeB devices to be considered
This function finds among the eNodeB set the closest eNodeB for each UE, and then invokes manual attachment between the pair.
Users are encouraged to use automatic attachment (Idle mode cell selection) instead of this function.
See also
LteHelper::Attach(NetDeviceContainer ueDevices);
Definition at line 1037 of file lte-helper.cc.
References ns3::NetDeviceContainer::Begin(), ns3::NetDeviceContainer::End(), and NS_LOG_FUNCTION.
AttachToClosestEnb() [2/2]
void ns3::LteHelper::AttachToClosestEnb (Ptr< NetDevice > ueDevice, NetDeviceContainer enbDevices)
Manual attachment of a UE device to the network via the closest eNodeB (with respect to distance) among those in the set.
Parameters
ueDevice the UE device to be attached
enbDevices the set of eNodeB devices to be considered
This function finds among the eNodeB set the closest eNodeB for the UE, and then invokes manual attachment between the pair.
Users are encouraged to use automatic attachment (Idle mode cell selection) instead of this function.
See also
LteHelper::Attach(Ptr<NetDevice> ueDevice);
Definition at line 1047 of file lte-helper.cc.
References Attach(), ns3::NetDeviceContainer::Begin(), ns3::CalculateDistance(), ns3::NetDeviceContainer::End(), ns3::NetDeviceContainer::GetN(), GetPosition(), NS_ASSERT, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
ChannelModelInitialization()
void ns3::LteHelper::ChannelModelInitialization (void) private
Function that performs a channel model initialization of all component carriers.
Definition at line 224 of file lte-helper.cc.
References ns3::ObjectFactory::Create(), ns3::Object::GetObject(), m_channelFactory, m_downlinkChannel, m_downlinkPathlossModel, m_fadingModel, m_fadingModelFactory, m_fadingModelType, m_noOfCcs, m_pathlossModelFactory, m_uplinkChannel, m_uplinkPathlossModel, NS_ASSERT_MSG, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by DoInitialize().
DeActivateDedicatedEpsBearer()
void ns3::LteHelper::DeActivateDedicatedEpsBearer (Ptr< NetDevice > ueDevice, Ptr< NetDevice > enbDevice, uint8_t bearerId)
Manually trigger dedicated bearer de-activation at specific simulation time.
Parameters
ueDevice the UE on which dedicated bearer to be de-activated must be of the type LteUeNetDevice
enbDevice eNB, must be of the type LteEnbNetDevice
bearerId Bearer Identity which is to be de-activated
Warning
Requires the use of EPC mode. See SetEpcHelper() method.
Definition at line 1273 of file lte-helper.cc.
References DoDeActivateDedicatedEpsBearer(), m_epcHelper, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
Referenced by ns3::LenaDeactivateBearerTestCase::DoRun().
DoComponentCarrierConfigure()
void ns3::LteHelper::DoComponentCarrierConfigure (uint32_t ulEarfcn, uint32_t dlEarfcn, uint16_t ulbw, uint16_t dlbw) private
Configure the component carriers.
Parameters
ulEarfcn uplink EARFCN
dlEarfcn downlink EARFCN
ulbw uplink bandwidth for each CC
dlbw downlink bandwidth for each CC
Definition at line 1298 of file lte-helper.cc.
References m_componentCarrierPhyParams, m_noOfCcs, NS_ABORT_MSG_IF, and NS_LOG_FUNCTION.
Referenced by InstallSingleEnbDevice(), and InstallSingleUeDevice().
DoDeActivateDedicatedEpsBearer()
void ns3::LteHelper::DoDeActivateDedicatedEpsBearer (Ptr< NetDevice > ueDevice, Ptr< NetDevice > enbDevice, uint8_t bearerId) private
The actual function to trigger a manual bearer de-activation.
Parameters
ueDevice the UE on which bearer to be de-activated must be of the type LteUeNetDevice
enbDevice eNB, must be of the type LteEnbNetDevice
bearerId Bearer Identity which is to be de-activated
This method is normally scheduled by DeActivateDedicatedEpsBearer() to run at a specific time when a manual bearer de-activation is desired by the simulation user.
Definition at line 1283 of file lte-helper.cc.
References NS_LOG_FUNCTION.
Referenced by DeActivateDedicatedEpsBearer().
DoDispose()
void ns3::LteHelper::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 202 of file lte-helper.cc.
References ns3::Object::DoDispose(), m_componentCarrierPhyParams, m_downlinkChannel, m_uplinkChannel, and NS_LOG_FUNCTION.
DoHandoverRequest()
void ns3::LteHelper::DoHandoverRequest (Ptr< NetDevice > ueDev, Ptr< NetDevice > sourceEnbDev, uint16_t targetCellId) private
The actual function to trigger a manual handover.
Parameters
ueDev the UE that hands off, must be of the type LteUeNetDevice
sourceEnbDev source eNB, must be of the type LteEnbNetDevice (originally the UE is attached to this eNB)
targetCellId target CellId (the UE primary component carrier will be connected to this cell after the handover)
This method is normally scheduled by HandoverRequest() to run at a specific time where a manual handover is desired by the simulation user.
Definition at line 1263 of file lte-helper.cc.
References NS_LOG_FUNCTION.
Referenced by HandoverRequest().
DoInitialize()
void ns3::LteHelper::DoInitialize (void) protected virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 89 of file lte-helper.cc.
References ChannelModelInitialization(), ns3::Object::DoInitialize(), m_macStats, m_phyRxStats, m_phyStats, m_phyTxStats, and NS_LOG_FUNCTION.
EnableDlMacTraces()
void ns3::LteHelper::EnableDlMacTraces (void)
Enable trace sinks for DL MAC layer.
Definition at line 1538 of file lte-helper.cc.
References ns3::Config::Connect(), ns3::MacStatsCalculator::DlSchedulingCallback(), m_macStats, ns3::MakeBoundCallback(), and NS_LOG_FUNCTION_NOARGS.
Referenced by EnableMacTraces().
EnableDlPhyTraces()
void ns3::LteHelper::EnableDlPhyTraces (void)
Enable trace sinks for DL PHY layer.
Definition at line 1554 of file lte-helper.cc.
References ns3::Config::Connect(), m_phyStats, ns3::MakeBoundCallback(), NS_LOG_FUNCTION_NOARGS, and ns3::PhyStatsCalculator::ReportCurrentCellRsrpSinrCallback().
Referenced by EnablePhyTraces().
EnableDlRxPhyTraces()
void ns3::LteHelper::EnableDlRxPhyTraces (void)
Enable trace sinks for DL reception PHY layer.
Definition at line 1515 of file lte-helper.cc.
References ns3::Config::Connect(), ns3::PhyRxStatsCalculator::DlPhyReceptionCallback(), m_phyRxStats, and ns3::MakeBoundCallback().
Referenced by EnablePhyTraces().
EnableDlTxPhyTraces()
void ns3::LteHelper::EnableDlTxPhyTraces (void)
Enable trace sinks for DL transmission PHY layer.
Definition at line 1501 of file lte-helper.cc.
References ns3::Config::Connect(), ns3::PhyTxStatsCalculator::DlPhyTransmissionCallback(), m_phyTxStats, and ns3::MakeBoundCallback().
Referenced by EnablePhyTraces().
EnableLogComponents()
void ns3::LteHelper::EnableLogComponents (void)
Enables full-blown logging for major components of the LENA architecture.
Definition at line 1324 of file lte-helper.cc.
References ns3::LOG_LEVEL_ALL, ns3::LOG_PREFIX_FUNC, ns3::LOG_PREFIX_NODE, ns3::LOG_PREFIX_TIME, ns3::LogComponentEnable(), and ns3::LogComponentEnableAll().
EnableMacTraces()
void ns3::LteHelper::EnableMacTraces (void)
Enable trace sinks for MAC layer.
Definition at line 1530 of file lte-helper.cc.
References EnableDlMacTraces(), and EnableUlMacTraces().
Referenced by LenaCqaFfMacSchedulerTestCase1::DoRun(), LenaFdBetFfMacSchedulerTestCase1::DoRun(), LenaFdBetFfMacSchedulerTestCase2::DoRun(), LenaFdMtFfMacSchedulerTestCase::DoRun(), LenaFdTbfqFfMacSchedulerTestCase1::DoRun(), LenaHarqTestCase::DoRun(), LteLinkAdaptationTestCase::DoRun(), LenaMimoTestCase::DoRun(), LtePathlossModelSystemTestCase::DoRun(), LenaPfFfMacSchedulerTestCase1::DoRun(), LenaPssFfMacSchedulerTestCase1::DoRun(), LenaTdBetFfMacSchedulerTestCase1::DoRun(), LenaTdBetFfMacSchedulerTestCase2::DoRun(), LenaTdMtFfMacSchedulerTestCase::DoRun(), LenaTdTbfqFfMacSchedulerTestCase1::DoRun(), LenaTtaFfMacSchedulerTestCase::DoRun(), and EnableTraces().
EnablePdcpTraces()
void ns3::LteHelper::EnablePdcpTraces (void)
Enable trace sinks for PDCP layer.
Definition at line 1579 of file lte-helper.cc.
References ns3::RadioBearerStatsConnector::EnablePdcpStats(), m_pdcpStats, m_radioBearerStatsConnector, and NS_ASSERT_MSG.
Referenced by LteEpcE2eDataTestCase::DoRun(), and EnableTraces().
EnablePhyTraces()
void ns3::LteHelper::EnablePhyTraces (void)
Enable trace sinks for PHY layer.
Definition at line 1490 of file lte-helper.cc.
References EnableDlPhyTraces(), EnableDlRxPhyTraces(), EnableDlTxPhyTraces(), EnableUlPhyTraces(), EnableUlRxPhyTraces(), and EnableUlTxPhyTraces().
Referenced by EnableTraces().
EnableRlcTraces()
void ns3::LteHelper::EnableRlcTraces (void)
Enable trace sinks for RLC layer.
Definition at line 1436 of file lte-helper.cc.
References ns3::RadioBearerStatsConnector::EnableRlcStats(), m_radioBearerStatsConnector, m_rlcStats, and NS_ASSERT_MSG.
Referenced by LenaCqaFfMacSchedulerTestCase1::DoRun(), LenaCqaFfMacSchedulerTestCase2::DoRun(), ns3::LenaDeactivateBearerTestCase::DoRun(), LenaFdBetFfMacSchedulerTestCase1::DoRun(), LenaFdBetFfMacSchedulerTestCase2::DoRun(), LenaFdMtFfMacSchedulerTestCase::DoRun(), LenaFdTbfqFfMacSchedulerTestCase1::DoRun(), LenaFdTbfqFfMacSchedulerTestCase2::DoRun(), LenaHarqTestCase::DoRun(), LteLinkAdaptationTestCase::DoRun(), LenaMimoTestCase::DoRun(), LtePathlossModelSystemTestCase::DoRun(), LenaPfFfMacSchedulerTestCase1::DoRun(), LenaPfFfMacSchedulerTestCase2::DoRun(), LenaDataPhyErrorModelTestCase::DoRun(), LenaDlCtrlPhyErrorModelTestCase::DoRun(), LenaPssFfMacSchedulerTestCase1::DoRun(), LenaPssFfMacSchedulerTestCase2::DoRun(), LenaRrFfMacSchedulerTestCase::DoRun(), LenaTdBetFfMacSchedulerTestCase1::DoRun(), LenaTdBetFfMacSchedulerTestCase2::DoRun(), LenaTdMtFfMacSchedulerTestCase::DoRun(), LenaTdTbfqFfMacSchedulerTestCase1::DoRun(), LenaTdTbfqFfMacSchedulerTestCase2::DoRun(), LenaTtaFfMacSchedulerTestCase::DoRun(), and EnableTraces().
EnableTraces()
void ns3::LteHelper::EnableTraces (void)
Enables trace sinks for PHY, MAC, RLC and PDCP.
To make sure all nodes are traced, traces should be enabled once all UEs and eNodeBs are in place and connected, just before starting the simulation.
Definition at line 1427 of file lte-helper.cc.
References EnableMacTraces(), EnablePdcpTraces(), EnablePhyTraces(), and EnableRlcTraces().
Referenced by LteRadioLinkFailureTestCase::DoRun(), and CarrierAggregationTestCase::DoRun().
EnableUlMacTraces()
void ns3::LteHelper::EnableUlMacTraces (void)
Enable trace sinks for UL MAC layer.
Definition at line 1546 of file lte-helper.cc.
References ns3::Config::Connect(), m_macStats, ns3::MakeBoundCallback(), NS_LOG_FUNCTION_NOARGS, and ns3::MacStatsCalculator::UlSchedulingCallback().
Referenced by EnableMacTraces().
EnableUlPhyTraces()
void ns3::LteHelper::EnableUlPhyTraces (void)
Enable trace sinks for UL PHY layer.
Definition at line 1562 of file lte-helper.cc.
References ns3::Config::Connect(), m_phyStats, ns3::MakeBoundCallback(), NS_LOG_FUNCTION_NOARGS, ns3::PhyStatsCalculator::ReportInterference(), and ns3::PhyStatsCalculator::ReportUeSinr().
Referenced by EnablePhyTraces().
EnableUlRxPhyTraces()
void ns3::LteHelper::EnableUlRxPhyTraces (void)
Enable trace sinks for UL reception PHY layer.
Definition at line 1522 of file lte-helper.cc.
References ns3::Config::Connect(), m_phyRxStats, ns3::MakeBoundCallback(), and ns3::PhyRxStatsCalculator::UlPhyReceptionCallback().
Referenced by EnablePhyTraces().
EnableUlTxPhyTraces()
void ns3::LteHelper::EnableUlTxPhyTraces (void)
Enable trace sinks for UL transmission PHY layer.
Definition at line 1508 of file lte-helper.cc.
References ns3::Config::Connect(), m_phyTxStats, ns3::MakeBoundCallback(), and ns3::PhyTxStatsCalculator::UlPhyTransmissionCallback().
Referenced by EnablePhyTraces().
GetDownlinkSpectrumChannel()
Ptr< SpectrumChannel > ns3::LteHelper::GetDownlinkSpectrumChannel (void) const
Returns
a pointer to the SpectrumChannel instance used for the downlink
Definition at line 218 of file lte-helper.cc.
References m_downlinkChannel.
GetEnbComponentCarrierManagerType()
std::string ns3::LteHelper::GetEnbComponentCarrierManagerType () const
Returns
the carrier enb component carrier manager type
Definition at line 343 of file lte-helper.cc.
References ns3::TypeId::GetName(), ns3::ObjectFactory::GetTypeId(), and m_enbComponentCarrierManagerFactory.
Referenced by GetTypeId().
GetFfrAlgorithmType()
std::string ns3::LteHelper::GetFfrAlgorithmType () const
Returns
the FFR algorithm type
Definition at line 300 of file lte-helper.cc.
References ns3::TypeId::GetName(), ns3::ObjectFactory::GetTypeId(), and m_ffrAlgorithmFactory.
Referenced by GetTypeId().
GetHandoverAlgorithmType()
std::string ns3::LteHelper::GetHandoverAlgorithmType () const
Returns
the handover algorithm type
Definition at line 321 of file lte-helper.cc.
References ns3::TypeId::GetName(), ns3::ObjectFactory::GetTypeId(), and m_handoverAlgorithmFactory.
Referenced by GetTypeId().
GetPdcpStats()
Ptr< RadioBearerStatsCalculator > ns3::LteHelper::GetPdcpStats (void)
Returns
the PDCP stats calculator object
Definition at line 1587 of file lte-helper.cc.
References m_pdcpStats.
Referenced by LteEpcE2eDataTestCase::DoRun().
GetRlcStats()
Ptr< RadioBearerStatsCalculator > ns3::LteHelper::GetRlcStats (void)
Returns
the RLC stats calculator object
Definition at line 1573 of file lte-helper.cc.
References m_rlcStats.
Referenced by LenaCqaFfMacSchedulerTestCase1::DoRun(), LenaCqaFfMacSchedulerTestCase2::DoRun(), ns3::LenaDeactivateBearerTestCase::DoRun(), LenaFdBetFfMacSchedulerTestCase1::DoRun(), LenaFdBetFfMacSchedulerTestCase2::DoRun(), LenaFdMtFfMacSchedulerTestCase::DoRun(), LenaFdTbfqFfMacSchedulerTestCase1::DoRun(), LenaFdTbfqFfMacSchedulerTestCase2::DoRun(), LenaHarqTestCase::DoRun(), LenaMimoTestCase::DoRun(), LenaPfFfMacSchedulerTestCase1::DoRun(), LenaPfFfMacSchedulerTestCase2::DoRun(), LenaDataPhyErrorModelTestCase::DoRun(), LenaDlCtrlPhyErrorModelTestCase::DoRun(), LenaPssFfMacSchedulerTestCase1::DoRun(), LenaPssFfMacSchedulerTestCase2::DoRun(), LenaRrFfMacSchedulerTestCase::DoRun(), LenaTdBetFfMacSchedulerTestCase1::DoRun(), LenaTdBetFfMacSchedulerTestCase2::DoRun(), LenaTdMtFfMacSchedulerTestCase::DoRun(), LenaTdTbfqFfMacSchedulerTestCase1::DoRun(), LenaTdTbfqFfMacSchedulerTestCase2::DoRun(), and LenaTtaFfMacSchedulerTestCase::DoRun().
GetSchedulerType()
std::string ns3::LteHelper::GetSchedulerType () const
Returns
the scheduler type
Definition at line 287 of file lte-helper.cc.
References ns3::TypeId::GetName(), ns3::ObjectFactory::GetTypeId(), and m_schedulerFactory.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::LteHelper::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 106 of file lte-helper.cc.
References GetEnbComponentCarrierManagerType(), GetFfrAlgorithmType(), GetHandoverAlgorithmType(), GetSchedulerType(), ns3::FriisPropagationLossModel::GetTypeId(), GetUeComponentCarrierManagerType(), m_isAnrEnabled, m_noOfCcs, m_useCa, m_useIdealRrc, m_usePdschForCqiGeneration, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeStringAccessor(), ns3::MakeStringChecker(), ns3::MakeTypeIdAccessor(), ns3::MakeTypeIdChecker(), ns3::MakeUintegerAccessor(), MAX_NO_CC, MIN_NO_CC, SetEnbComponentCarrierManagerType(), SetFadingModel(), SetFfrAlgorithmType(), SetHandoverAlgorithmType(), ns3::TypeId::SetParent(), SetPathlossModelType(), SetSchedulerType(), and SetUeComponentCarrierManagerType().
GetUeComponentCarrierManagerType()
std::string ns3::LteHelper::GetUeComponentCarrierManagerType () const
Returns
the carrier ue component carrier manager type
Definition at line 364 of file lte-helper.cc.
References ns3::TypeId::GetName(), ns3::ObjectFactory::GetTypeId(), and m_ueComponentCarrierManagerFactory.
Referenced by GetTypeId().
GetUplinkSpectrumChannel()
Ptr< SpectrumChannel > ns3::LteHelper::GetUplinkSpectrumChannel (void) const
Returns
a pointer to the SpectrumChannel instance used for the uplink
Definition at line 212 of file lte-helper.cc.
References m_uplinkChannel.
HandoverRequest() [1/2]
void ns3::LteHelper::HandoverRequest (Time hoTime, Ptr< NetDevice > ueDev, Ptr< NetDevice > sourceEnbDev, Ptr< NetDevice > targetEnbDev)
Manually trigger an X2-based handover.
Parameters
hoTime when the handover shall be initiated
ueDev the UE that hands off, must be of the type LteUeNetDevice
sourceEnbDev source eNB, must be of the type LteEnbNetDevice (originally the UE is attached to this eNB)
targetEnbDev target eNB, must be of the type LteEnbNetDevice (the UE would be connected to this eNB after the handover)
Warning
Requires the use of EPC mode. See SetEpcHelper() method
Definition at line 1246 of file lte-helper.cc.
References DoHandoverRequest(), m_epcHelper, NS_ASSERT_MSG, NS_LOG_FUNCTION, and ns3::Simulator::Schedule().
Referenced by LteUeMeasurementsHandoverTestCase::DoRun(), and LteX2HandoverTestCase::DoRun().
HandoverRequest() [2/2]
void ns3::LteHelper::HandoverRequest (Time hoTime, Ptr< NetDevice > ueDev, Ptr< NetDevice > sourceEnbDev, uint16_t targetCellId)
Manually trigger an X2-based handover.
Parameters
hoTime when the handover shall be initiated
ueDev the UE that hands off, must be of the type LteUeNetDevice
sourceEnbDev source eNB, must be of the type LteEnbNetDevice (originally the UE is attached to this eNB)
targetCellId target CellId (the UE primary component carrier will be connected to this cell after the handover)
Warning
Requires the use of EPC mode. See SetEpcHelper() method
Definition at line 1255 of file lte-helper.cc.
References DoHandoverRequest(), m_epcHelper, NS_ASSERT_MSG, NS_LOG_FUNCTION, and ns3::Simulator::Schedule().
InstallEnbDevice()
NetDeviceContainer ns3::LteHelper::InstallEnbDevice (NodeContainer c)
Create a set of eNodeB devices.
Parameters
c the node container where the devices are to be installed
Returns
the NetDeviceContainer with the newly created devices
Definition at line 474 of file lte-helper.cc.
References ns3::NodeContainer::Begin(), first::devices, ns3::NodeContainer::End(), ns3::Object::Initialize(), InstallSingleEnbDevice(), and NS_LOG_FUNCTION.
Referenced by LteCellSelectionTestCase::DoRun(), LteRadioLinkFailureTestCase::DoRun(), LteUeMeasurementsPiecewiseTestCase1::DoRun(), LteUeMeasurementsPiecewiseTestCase2::DoRun(), LteUeMeasurementsPiecewiseTestCase3::DoRun(), LteUeMeasurementsHandoverTestCase::DoRun(), LteHandoverTargetTestCase::DoRun(), CarrierAggregationConfigTestCase::DoRun(), CarrierAggregationTestCase::DoRun(), LenaCqaFfMacSchedulerTestCase1::DoRun(), LenaCqaFfMacSchedulerTestCase2::DoRun(), LteCqiGenerationTestCase::DoRun(), LteCqiGenerationDlPowerControlTestCase::DoRun(), ns3::LenaDeactivateBearerTestCase::DoRun(), LteDownlinkPowerControlTestCase::DoRun(), LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::DoRun(), LenaFdBetFfMacSchedulerTestCase1::DoRun(), LenaFdBetFfMacSchedulerTestCase2::DoRun(), LenaFdMtFfMacSchedulerTestCase::DoRun(), LenaFdTbfqFfMacSchedulerTestCase1::DoRun(), LenaFdTbfqFfMacSchedulerTestCase2::DoRun(), LteHardFrTestCase::DoRun(), LteStrictFrTestCase::DoRun(), LteStrictFrAreaTestCase::DoRun(), LteSoftFrAreaTestCase::DoRun(), LteSoftFfrAreaTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LenaHarqTestCase::DoRun(), LteInterferenceHardFrTestCase::DoRun(), LteInterferenceStrictFrTestCase::DoRun(), LteInterferenceTestCase::DoRun(), LteIpv6RoutingTestCase::DoRun(), LteLinkAdaptationTestCase::DoRun(), LenaMimoTestCase::DoRun(), LtePathlossModelSystemTestCase::DoRun(), LenaPfFfMacSchedulerTestCase1::DoRun(), LenaPfFfMacSchedulerTestCase2::DoRun(), LenaDataPhyErrorModelTestCase::DoRun(), LenaDlCtrlPhyErrorModelTestCase::DoRun(), LenaPssFfMacSchedulerTestCase1::DoRun(), LenaPssFfMacSchedulerTestCase2::DoRun(), LenaRrFfMacSchedulerTestCase::DoRun(), LenaTdBetFfMacSchedulerTestCase1::DoRun(), LenaTdBetFfMacSchedulerTestCase2::DoRun(), LenaTdMtFfMacSchedulerTestCase::DoRun(), LenaTdTbfqFfMacSchedulerTestCase1::DoRun(), LenaTdTbfqFfMacSchedulerTestCase2::DoRun(), LenaTtaFfMacSchedulerTestCase::DoRun(), LteUeMeasurementsTestCase::DoRun(), LteUplinkOpenLoopPowerControlTestCase::DoRun(), LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun(), LteEnbAntennaTestCase::DoRun(), LteEpcE2eDataTestCase::DoRun(), LteRrcConnectionEstablishmentTestCase::DoRun(), LteRrcConnectionEstablishmentErrorTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), LteX2HandoverTestCase::DoRun(), and ns3::LteHexGridEnbTopologyHelper::SetPositionAndInstallEnbDevice().
InstallSingleEnbDevice()
Ptr< NetDevice > ns3::LteHelper::InstallSingleEnbDevice (Ptr< Node > n) private
Create an eNodeB device (LteEnbNetDevice) on the given node.
Parameters
n the node where the device is to be installed
Returns
pointer to the created device
Definition at line 504 of file lte-helper.cc.
References ns3::ObjectFactory::Create(), DoComponentCarrierConfigure(), ns3::LteEnbPhy::GenerateCtrlCqiReport(), ns3::LteEnbPhy::GenerateDataCqiReport(), ns3::EnumValue::Get(), ns3::LteSpectrumValueHelper::GetCarrierFrequency(), ns3::LteEnbNetDevice::GetCellId(), ns3::LteEnbNetDevice::GetDlBandwidth(), ns3::LteEnbNetDevice::GetDlEarfcn(), ns3::LteEnbNetDevice::GetUlBandwidth(), ns3::LteEnbNetDevice::GetUlEarfcn(), ns3::Object::Initialize(), m_cellIdCounter, m_componentCarrierPhyParams, m_downlinkChannel, m_downlinkPathlossModel, m_enbAntennaModelFactory, m_enbComponentCarrierManagerFactory, m_enbNetDeviceFactory, m_epcHelper, m_ffrAlgorithmFactory, m_handoverAlgorithmFactory, m_isAnrEnabled, m_noOfCcs, m_schedulerFactory, m_uplinkChannel, m_uplinkPathlossModel, m_useCa, m_useIdealRrc, third::mac, ns3::MakeCallback(), sample-rng-plot::n, NS_ABORT_MSG_IF, NS_ASSERT, NS_ASSERT_MSG, NS_FATAL_ERROR, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, NS_LOG_WARN, third::phy, ns3::LteEnbPhy::PhyPduReceived(), ns3::LteNetDevice::Receive(), ns3::LteEnbPhy::ReceiveLteControlMessageList(), ns3::LteEnbPhy::ReportInterference(), ns3::LteEnbPhy::ReportUlHarqFeedback(), ns3::LteEnbRrc::RLC_SM_ALWAYS, ns3::LteEnbRrc::RLC_UM_ALWAYS, ns3::ObjectBase::SetAttribute(), ns3::ObjectBase::SetAttributeFailSafe(), ns3::LteEnbNetDevice::SetCcMap(), ns3::LteNetDevice::SetNode(), and ns3::LteSpectrumPhy::UpdateSinrPerceived().
Referenced by InstallEnbDevice().
InstallSingleUeDevice()
Ptr< NetDevice > ns3::LteHelper::InstallSingleUeDevice (Ptr< Node > n) private
Create a UE device (LteUeNetDevice) on the given node.
Parameters
n the node where the device is to be installed
Returns
pointer to the created device
Definition at line 761 of file lte-helper.cc.
References ns3::Mac64Address::Allocate(), ns3::ObjectFactory::Create(), DoComponentCarrierConfigure(), ns3::LteUePhy::EnqueueDlHarqFeedback(), ns3::LteUePhy::GenerateCtrlCqiReport(), ns3::LteUePhy::GenerateMixedCqiReport(), m_componentCarrierPhyParams, m_downlinkChannel, m_epcHelper, m_imsiCounter, m_noOfCcs, m_ueAntennaModelFactory, m_ueComponentCarrierManagerFactory, m_ueNetDeviceFactory, m_uplinkChannel, m_useIdealRrc, m_usePdschForCqiGeneration, third::mac, ns3::MakeCallback(), sample-rng-plot::n, NS_ABORT_MSG_IF, NS_ASSERT_MSG, NS_FATAL_ERROR, NS_LOG_FUNCTION, third::phy, ns3::LteUePhy::PhyPduReceived(), ns3::LteNetDevice::Receive(), ns3::LteUePhy::ReceiveLteControlMessageList(), ns3::LteUePhy::ReceivePss(), ns3::LteUePhy::ReportDataInterference(), ns3::LteUePhy::ReportInterference(), ns3::LteUePhy::ReportRsReceivedPower(), and ns3::LteSpectrumPhy::UpdateSinrPerceived().
Referenced by InstallUeDevice().
InstallUeDevice()
NetDeviceContainer ns3::LteHelper::InstallUeDevice (NodeContainer c)
Create a set of UE devices.
Parameters
c the node container where the devices are to be installed
Returns
the NetDeviceContainer with the newly created devices
Definition at line 489 of file lte-helper.cc.
References ns3::NodeContainer::Begin(), first::devices, ns3::NodeContainer::End(), InstallSingleUeDevice(), and NS_LOG_FUNCTION.
Referenced by LteCellSelectionTestCase::DoRun(), LteRadioLinkFailureTestCase::DoRun(), LteUeMeasurementsPiecewiseTestCase1::DoRun(), LteUeMeasurementsPiecewiseTestCase2::DoRun(), LteUeMeasurementsPiecewiseTestCase3::DoRun(), LteUeMeasurementsHandoverTestCase::DoRun(), LteHandoverTargetTestCase::DoRun(), CarrierAggregationConfigTestCase::DoRun(), CarrierAggregationTestCase::DoRun(), LenaCqaFfMacSchedulerTestCase1::DoRun(), LenaCqaFfMacSchedulerTestCase2::DoRun(), LteCqiGenerationTestCase::DoRun(), LteCqiGenerationDlPowerControlTestCase::DoRun(), ns3::LenaDeactivateBearerTestCase::DoRun(), LteDownlinkPowerControlTestCase::DoRun(), LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::DoRun(), LenaFdBetFfMacSchedulerTestCase1::DoRun(), LenaFdBetFfMacSchedulerTestCase2::DoRun(), LenaFdMtFfMacSchedulerTestCase::DoRun(), LenaFdTbfqFfMacSchedulerTestCase1::DoRun(), LenaFdTbfqFfMacSchedulerTestCase2::DoRun(), LteHardFrTestCase::DoRun(), LteStrictFrTestCase::DoRun(), LteStrictFrAreaTestCase::DoRun(), LteSoftFrAreaTestCase::DoRun(), LteSoftFfrAreaTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LenaHarqTestCase::DoRun(), LteInterferenceHardFrTestCase::DoRun(), LteInterferenceStrictFrTestCase::DoRun(), LteInterferenceTestCase::DoRun(), LteIpv6RoutingTestCase::DoRun(), LteLinkAdaptationTestCase::DoRun(), LenaMimoTestCase::DoRun(), LtePathlossModelSystemTestCase::DoRun(), LenaPfFfMacSchedulerTestCase1::DoRun(), LenaPfFfMacSchedulerTestCase2::DoRun(), LenaDataPhyErrorModelTestCase::DoRun(), LenaDlCtrlPhyErrorModelTestCase::DoRun(), LenaPssFfMacSchedulerTestCase1::DoRun(), LenaPssFfMacSchedulerTestCase2::DoRun(), LenaRrFfMacSchedulerTestCase::DoRun(), LenaTdBetFfMacSchedulerTestCase1::DoRun(), LenaTdBetFfMacSchedulerTestCase2::DoRun(), LenaTdMtFfMacSchedulerTestCase::DoRun(), LenaTdTbfqFfMacSchedulerTestCase1::DoRun(), LenaTdTbfqFfMacSchedulerTestCase2::DoRun(), LenaTtaFfMacSchedulerTestCase::DoRun(), LteUeMeasurementsTestCase::DoRun(), LteUplinkOpenLoopPowerControlTestCase::DoRun(), LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun(), LteEnbAntennaTestCase::DoRun(), LteEpcE2eDataTestCase::DoRun(), LteRrcConnectionEstablishmentTestCase::DoRun(), LteRrcConnectionEstablishmentErrorTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), and LteX2HandoverTestCase::DoRun().
SetEnbAntennaModelAttribute()
void ns3::LteHelper::SetEnbAntennaModelAttribute (std::string n, const AttributeValue & v)
Set an attribute for the eNodeB antenna model to be created.
Parameters
n the name of the attribute.
v the value of the attribute
Definition at line 415 of file lte-helper.cc.
References m_enbAntennaModelFactory, sample-rng-plot::n, NS_LOG_FUNCTION, and ns3::ObjectFactory::Set().
Referenced by LteEnbAntennaTestCase::DoRun(), and ns3::LteHexGridEnbTopologyHelper::SetPositionAndInstallEnbDevice().
SetEnbAntennaModelType()
void ns3::LteHelper::SetEnbAntennaModelType (std::string type)
Set the type of antenna model to be used by eNodeB devices.
Parameters
type type of antenna model, must be a type name of any class inheriting from ns3::AntennaModel, for example: "ns3::IsotropicAntennaModel"
Definition at line 408 of file lte-helper.cc.
References m_enbAntennaModelFactory, NS_LOG_FUNCTION, and ns3::ObjectFactory::SetTypeId().
Referenced by LteEnbAntennaTestCase::DoRun().
SetEnbComponentCarrierManagerAttribute()
void ns3::LteHelper::SetEnbComponentCarrierManagerAttribute (std::string n, const AttributeValue & v)
Set an attribute for the enb component carrier manager to be created.
Parameters
n the name of the attribute
v the value of the attribute
Definition at line 357 of file lte-helper.cc.
References m_enbComponentCarrierManagerFactory, sample-rng-plot::n, NS_LOG_FUNCTION, and ns3::ObjectFactory::Set().
SetEnbComponentCarrierManagerType()
void ns3::LteHelper::SetEnbComponentCarrierManagerType (std::string type)
Set the type of carrier component algorithm to be used by eNodeB devices.
Parameters
type type of carrier component manager
Definition at line 349 of file lte-helper.cc.
References m_enbComponentCarrierManagerFactory, NS_LOG_FUNCTION, ns3::Object::ObjectFactory, and ns3::ObjectFactory::SetTypeId().
Referenced by GetTypeId().
SetEnbDeviceAttribute()
void ns3::LteHelper::SetEnbDeviceAttribute (std::string n, const AttributeValue & v)
Set an attribute for the eNodeB devices (LteEnbNetDevice) to be created.
Parameters
n the name of the attribute.
v the value of the attribute
Definition at line 400 of file lte-helper.cc.
References m_enbNetDeviceFactory, sample-rng-plot::n, NS_LOG_FUNCTION, and ns3::ObjectFactory::Set().
Referenced by LteCellSelectionTestCase::DoRun(), LteRadioLinkFailureTestCase::DoRun(), CarrierAggregationConfigTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LtePathlossModelSystemTestCase::DoRun(), LteUplinkOpenLoopPowerControlTestCase::DoRun(), LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), and LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun().
SetEpcHelper()
void ns3::LteHelper::SetEpcHelper (Ptr< EpcHelper > h)
Set the EpcHelper to be used to setup the EPC network in conjunction with the setup of the LTE radio access network.
Note
if no EpcHelper is ever set, then LteHelper will default to creating an LTE-only simulation with no EPC, using LteRlcSm as the RLC model, and without supporting any IP networking. In other words, it will be a radio-level simulation involving only LTE PHY and MAC and the FF Scheduler, with a saturation traffic model for the RLC.
Parameters
h a pointer to the EpcHelper to be used
Definition at line 272 of file lte-helper.cc.
References m_epcHelper, and NS_LOG_FUNCTION.
Referenced by LteCellSelectionTestCase::DoRun(), LteRadioLinkFailureTestCase::DoRun(), LteUeMeasurementsHandoverTestCase::DoRun(), LteHandoverTargetTestCase::DoRun(), LenaCqaFfMacSchedulerTestCase1::DoRun(), LenaCqaFfMacSchedulerTestCase2::DoRun(), ns3::LenaDeactivateBearerTestCase::DoRun(), LenaFdTbfqFfMacSchedulerTestCase1::DoRun(), LenaFdTbfqFfMacSchedulerTestCase2::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LteIpv6RoutingTestCase::DoRun(), LenaPssFfMacSchedulerTestCase1::DoRun(), LenaPssFfMacSchedulerTestCase2::DoRun(), LenaTdTbfqFfMacSchedulerTestCase1::DoRun(), LenaTdTbfqFfMacSchedulerTestCase2::DoRun(), LteEpcE2eDataTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), and LteX2HandoverTestCase::DoRun().
SetFadingModel()
void ns3::LteHelper::SetFadingModel (std::string type)
Set the type of fading model to be used in both DL and UL.
Parameters
type type of fading model, must be a type name of any class inheriting from ns3::SpectrumPropagationLossModel, for example: "ns3::TraceFadingLossModel"
Definition at line 443 of file lte-helper.cc.
References m_fadingModelFactory, m_fadingModelType, NS_LOG_FUNCTION, ns3::Object::ObjectFactory, and ns3::ObjectFactory::SetTypeId().
Referenced by GetTypeId().
SetFadingModelAttribute()
void ns3::LteHelper::SetFadingModelAttribute (std::string n, const AttributeValue & v)
Set an attribute for the fading model to be created (both DL and UL).
Parameters
n the name of the attribute
v the value of the attribute
Definition at line 455 of file lte-helper.cc.
References m_fadingModelFactory, sample-rng-plot::n, and ns3::ObjectFactory::Set().
SetFfrAlgorithmAttribute()
void ns3::LteHelper::SetFfrAlgorithmAttribute (std::string n, const AttributeValue & v)
Set an attribute for the FFR algorithm to be created.
Parameters
n the name of the attribute
v the value of the attribute
Definition at line 314 of file lte-helper.cc.
References m_ffrAlgorithmFactory, sample-rng-plot::n, NS_LOG_FUNCTION, and ns3::ObjectFactory::Set().
Referenced by LteCqiGenerationTestCase::DoRun(), LteHardFrTestCase::DoRun(), LteStrictFrTestCase::DoRun(), LteStrictFrAreaTestCase::DoRun(), LteSoftFrAreaTestCase::DoRun(), LteSoftFfrAreaTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LteInterferenceHardFrTestCase::DoRun(), LteInterferenceStrictFrTestCase::DoRun(), and ns3::LteHexGridEnbTopologyHelper::SetPositionAndInstallEnbDevice().
SetFfrAlgorithmType()
void ns3::LteHelper::SetFfrAlgorithmType (std::string type)
Set the type of FFR algorithm to be used by eNodeB devices.
Parameters
type type of FFR algorithm, must be a type name of any class inheriting from ns3::LteFfrAlgorithm, for example: "ns3::LteFrNoOpAlgorithm"
Equivalent with setting the FfrAlgorithm attribute.
Definition at line 306 of file lte-helper.cc.
References m_ffrAlgorithmFactory, NS_LOG_FUNCTION, ns3::Object::ObjectFactory, and ns3::ObjectFactory::SetTypeId().
Referenced by LteCqiGenerationTestCase::DoRun(), LteCqiGenerationDlPowerControlTestCase::DoRun(), LteDownlinkPowerControlTestCase::DoRun(), LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::DoRun(), LteHardFrTestCase::DoRun(), LteStrictFrTestCase::DoRun(), LteStrictFrAreaTestCase::DoRun(), LteSoftFrAreaTestCase::DoRun(), LteSoftFfrAreaTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LteInterferenceHardFrTestCase::DoRun(), LteInterferenceStrictFrTestCase::DoRun(), LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun(), and GetTypeId().
SetHandoverAlgorithmAttribute()
void ns3::LteHelper::SetHandoverAlgorithmAttribute (std::string n, const AttributeValue & v)
Set an attribute for the handover algorithm to be created.
Parameters
n the name of the attribute
v the value of the attribute
Definition at line 335 of file lte-helper.cc.
References m_handoverAlgorithmFactory, sample-rng-plot::n, NS_LOG_FUNCTION, and ns3::ObjectFactory::Set().
Referenced by LteHandoverTargetTestCase::DoRun(), and LteX2HandoverMeasuresTestCase::DoRun().
SetHandoverAlgorithmType()
void ns3::LteHelper::SetHandoverAlgorithmType (std::string type)
Set the type of handover algorithm to be used by eNodeB devices.
Parameters
type type of handover algorithm, must be a type name of any class inheriting from ns3::LteHandoverAlgorithm, for example: "ns3::NoOpHandoverAlgorithm"
Equivalent with setting the HandoverAlgorithm attribute.
Definition at line 327 of file lte-helper.cc.
References m_handoverAlgorithmFactory, NS_LOG_FUNCTION, ns3::Object::ObjectFactory, and ns3::ObjectFactory::SetTypeId().
Referenced by LteHandoverTargetTestCase::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), LteX2HandoverTestCase::DoRun(), and GetTypeId().
SetPathlossModelAttribute()
void ns3::LteHelper::SetPathlossModelAttribute (std::string n, const AttributeValue & v)
Set an attribute for the path loss models to be created.
Parameters
n the name of the attribute
v the value of the attribute
Definition at line 393 of file lte-helper.cc.
References m_pathlossModelFactory, sample-rng-plot::n, NS_LOG_FUNCTION, and ns3::ObjectFactory::Set().
Referenced by LteRadioLinkFailureTestCase::DoRun(), LenaHarqTestCase::DoRun(), LteLinkAdaptationTestCase::DoRun(), LenaMimoTestCase::DoRun(), LtePathlossModelSystemTestCase::DoRun(), LenaDataPhyErrorModelTestCase::DoRun(), LenaDlCtrlPhyErrorModelTestCase::DoRun(), and LteEnbAntennaTestCase::DoRun().
SetPathlossModelType()
void ns3::LteHelper::SetPathlossModelType (TypeId type)
Set the type of path loss model to be used for both DL and UL channels.
Parameters
type type of path loss model, must be a type name of any class inheriting from ns3::PropagationLossModel, for example: "ns3::FriisPropagationLossModel"
Definition at line 385 of file lte-helper.cc.
References m_pathlossModelFactory, NS_LOG_FUNCTION, ns3::Object::ObjectFactory, and ns3::ObjectFactory::SetTypeId().
Referenced by LteRadioLinkFailureTestCase::DoRun(), and GetTypeId().
SetSchedulerAttribute()
void ns3::LteHelper::SetSchedulerAttribute (std::string n, const AttributeValue & v)
Set an attribute for the scheduler to be created.
Parameters
n the name of the attribute
v the value of the attribute
Definition at line 293 of file lte-helper.cc.
References m_schedulerFactory, sample-rng-plot::n, NS_LOG_FUNCTION, and ns3::ObjectFactory::Set().
Referenced by LteUeMeasurementsPiecewiseTestCase1::DoRun(), LteUeMeasurementsPiecewiseTestCase2::DoRun(), LteUeMeasurementsPiecewiseTestCase3::DoRun(), CarrierAggregationTestCase::DoRun(), LenaCqaFfMacSchedulerTestCase1::DoRun(), LenaCqaFfMacSchedulerTestCase2::DoRun(), LteCqiGenerationTestCase::DoRun(), LteCqiGenerationDlPowerControlTestCase::DoRun(), LenaFdBetFfMacSchedulerTestCase1::DoRun(), LenaFdBetFfMacSchedulerTestCase2::DoRun(), LenaFdMtFfMacSchedulerTestCase::DoRun(), LenaFdTbfqFfMacSchedulerTestCase1::DoRun(), LenaFdTbfqFfMacSchedulerTestCase2::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), LenaHarqTestCase::DoRun(), LteInterferenceHardFrTestCase::DoRun(), LteInterferenceStrictFrTestCase::DoRun(), LteInterferenceTestCase::DoRun(), LenaPfFfMacSchedulerTestCase1::DoRun(), LenaPfFfMacSchedulerTestCase2::DoRun(), LenaDataPhyErrorModelTestCase::DoRun(), LenaDlCtrlPhyErrorModelTestCase::DoRun(), LenaPssFfMacSchedulerTestCase1::DoRun(), LenaPssFfMacSchedulerTestCase2::DoRun(), LenaRrFfMacSchedulerTestCase::DoRun(), LenaTdBetFfMacSchedulerTestCase1::DoRun(), LenaTdBetFfMacSchedulerTestCase2::DoRun(), LenaTdMtFfMacSchedulerTestCase::DoRun(), LenaTdTbfqFfMacSchedulerTestCase1::DoRun(), LenaTtaFfMacSchedulerTestCase::DoRun(), LteUeMeasurementsTestCase::DoRun(), and LteEnbAntennaTestCase::DoRun().
SetSchedulerType()
void ns3::LteHelper::SetSchedulerType (std::string type)
Set the type of scheduler to be used by eNodeB devices.
Parameters
type type of scheduler, must be a type name of any class inheriting from ns3::FfMacScheduler, for example: "ns3::PfFfMacScheduler"
Equivalent with setting the Scheduler attribute.
Definition at line 279 of file lte-helper.cc.
References m_schedulerFactory, NS_LOG_FUNCTION, ns3::Object::ObjectFactory, and ns3::ObjectFactory::SetTypeId().
Referenced by LteRadioLinkFailureTestCase::DoRun(), LteUeMeasurementsPiecewiseTestCase1::DoRun(), LteUeMeasurementsPiecewiseTestCase2::DoRun(), LteUeMeasurementsPiecewiseTestCase3::DoRun(), CarrierAggregationTestCase::DoRun(), LenaCqaFfMacSchedulerTestCase1::DoRun(), LenaCqaFfMacSchedulerTestCase2::DoRun(), LteCqiGenerationTestCase::DoRun(), LteCqiGenerationDlPowerControlTestCase::DoRun(), ns3::LenaDeactivateBearerTestCase::DoRun(), LteDownlinkPowerControlTestCase::DoRun(), LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::DoRun(), LenaFdBetFfMacSchedulerTestCase1::DoRun(), LenaFdBetFfMacSchedulerTestCase2::DoRun(), LenaFdMtFfMacSchedulerTestCase::DoRun(), LenaFdTbfqFfMacSchedulerTestCase1::DoRun(), LenaFdTbfqFfMacSchedulerTestCase2::DoRun(), LteHardFrTestCase::DoRun(), LteStrictFrTestCase::DoRun(), LteStrictFrAreaTestCase::DoRun(), LteSoftFrAreaTestCase::DoRun(), LteSoftFfrAreaTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LenaHarqTestCase::DoRun(), LteInterferenceHardFrTestCase::DoRun(), LteInterferenceStrictFrTestCase::DoRun(), LteInterferenceTestCase::DoRun(), LteLinkAdaptationTestCase::DoRun(), LenaMimoTestCase::DoRun(), LtePathlossModelSystemTestCase::DoRun(), LenaPfFfMacSchedulerTestCase1::DoRun(), LenaPfFfMacSchedulerTestCase2::DoRun(), LenaDataPhyErrorModelTestCase::DoRun(), LenaDlCtrlPhyErrorModelTestCase::DoRun(), LenaPssFfMacSchedulerTestCase1::DoRun(), LenaPssFfMacSchedulerTestCase2::DoRun(), LenaRrFfMacSchedulerTestCase::DoRun(), LenaTdBetFfMacSchedulerTestCase1::DoRun(), LenaTdBetFfMacSchedulerTestCase2::DoRun(), LenaTdMtFfMacSchedulerTestCase::DoRun(), LenaTdTbfqFfMacSchedulerTestCase1::DoRun(), LenaTdTbfqFfMacSchedulerTestCase2::DoRun(), LenaTtaFfMacSchedulerTestCase::DoRun(), LteUeMeasurementsTestCase::DoRun(), LteUplinkOpenLoopPowerControlTestCase::DoRun(), LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun(), LteEnbAntennaTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), LteX2HandoverTestCase::DoRun(), and GetTypeId().
SetSpectrumChannelAttribute()
void ns3::LteHelper::SetSpectrumChannelAttribute (std::string n, const AttributeValue & v)
Set an attribute for the spectrum channel to be created (both DL and UL).
Parameters
n the name of the attribute
v the value of the attribute
Definition at line 468 of file lte-helper.cc.
References m_channelFactory, sample-rng-plot::n, and ns3::ObjectFactory::Set().
SetSpectrumChannelType()
void ns3::LteHelper::SetSpectrumChannelType (std::string type)
Set the type of spectrum channel to be used in both DL and UL.
Parameters
type type of spectrum channel model, must be a type name of any class inheriting from ns3::SpectrumChannel, for example: "ns3::MultiModelSpectrumChannel"
Definition at line 461 of file lte-helper.cc.
References m_channelFactory, NS_LOG_FUNCTION, and ns3::ObjectFactory::SetTypeId().
SetUeAntennaModelAttribute()
void ns3::LteHelper::SetUeAntennaModelAttribute (std::string n, const AttributeValue & v)
Set an attribute for the UE antenna model to be created.
Parameters
n the name of the attribute
v the value of the attribute
Definition at line 436 of file lte-helper.cc.
References m_ueAntennaModelFactory, sample-rng-plot::n, NS_LOG_FUNCTION, and ns3::ObjectFactory::Set().
SetUeAntennaModelType()
void ns3::LteHelper::SetUeAntennaModelType (std::string type)
Set the type of antenna model to be used by UE devices.
Parameters
type type of antenna model, must be a type name of any class inheriting from ns3::AntennaModel, for example: "ns3::IsotropicAntennaModel"
Definition at line 429 of file lte-helper.cc.
References m_ueAntennaModelFactory, NS_LOG_FUNCTION, and ns3::ObjectFactory::SetTypeId().
SetUeComponentCarrierManagerAttribute()
void ns3::LteHelper::SetUeComponentCarrierManagerAttribute (std::string n, const AttributeValue & v)
Set an attribute for the ue component carrier manager to be created.
Parameters
n the name of the attribute
v the value of the attribute
Definition at line 378 of file lte-helper.cc.
References m_ueComponentCarrierManagerFactory, sample-rng-plot::n, NS_LOG_FUNCTION, and ns3::ObjectFactory::Set().
SetUeComponentCarrierManagerType()
void ns3::LteHelper::SetUeComponentCarrierManagerType (std::string type)
Set the type of Component Carrier Manager to be used by Ue devices.
Parameters
type type of UE Component Carrier Manager
Definition at line 370 of file lte-helper.cc.
References m_ueComponentCarrierManagerFactory, NS_LOG_FUNCTION, ns3::Object::ObjectFactory, and ns3::ObjectFactory::SetTypeId().
Referenced by GetTypeId().
SetUeDeviceAttribute()
void ns3::LteHelper::SetUeDeviceAttribute (std::string n, const AttributeValue & v)
Set an attribute for the UE devices (LteUeNetDevice) to be created.
Parameters
n the name of the attribute.
v the value of the attribute
Definition at line 422 of file lte-helper.cc.
References m_ueNetDeviceFactory, sample-rng-plot::n, NS_LOG_FUNCTION, and ns3::ObjectFactory::Set().
Referenced by LteCellSelectionTestCase::DoRun(), CarrierAggregationConfigTestCase::DoRun(), and LtePathlossModelSystemTestCase::DoRun().
Member Data Documentation
m_cellIdCounter
uint16_t ns3::LteHelper::m_cellIdCounter private
Keep track of the number of cell ID allocated.
Increases by one every time a new eNodeB is installed (by InstallSingleEnbDevice()). The first eNodeB will have a cell ID of 1. The maximum number of eNodeB is 65535.
Definition at line 813 of file lte-helper.h.
Referenced by InstallSingleEnbDevice().
m_channelFactory
ObjectFactory ns3::LteHelper::m_channelFactory private
Factory of both the downlink and uplink LTE channels.
Definition at line 766 of file lte-helper.h.
Referenced by LteHelper(), ChannelModelInitialization(), SetSpectrumChannelAttribute(), and SetSpectrumChannelType().
m_componentCarrierPhyParams
std::map< uint8_t, ComponentCarrier > ns3::LteHelper::m_componentCarrierPhyParams private
This contains all the information about each component carrier.
Definition at line 843 of file lte-helper.h.
Referenced by DoComponentCarrierConfigure(), DoDispose(), InstallSingleEnbDevice(), and InstallSingleUeDevice().
m_downlinkChannel
Ptr<SpectrumChannel> ns3::LteHelper::m_downlinkChannel private
This function create the component carrier based on provided configuration parameters.
The downlink LTE channel used in the simulation.
Definition at line 737 of file lte-helper.h.
Referenced by ChannelModelInitialization(), DoDispose(), GetDownlinkSpectrumChannel(), InstallSingleEnbDevice(), and InstallSingleUeDevice().
m_downlinkPathlossModel
Ptr<Object> ns3::LteHelper::m_downlinkPathlossModel private
The path loss model used in the downlink channel.
Definition at line 741 of file lte-helper.h.
Referenced by ChannelModelInitialization(), and InstallSingleEnbDevice().
m_enbAntennaModelFactory
ObjectFactory ns3::LteHelper::m_enbAntennaModelFactory private
Factory of antenna object for eNodeB.
Definition at line 758 of file lte-helper.h.
Referenced by LteHelper(), InstallSingleEnbDevice(), SetEnbAntennaModelAttribute(), and SetEnbAntennaModelType().
m_enbComponentCarrierManagerFactory
ObjectFactory ns3::LteHelper::m_enbComponentCarrierManagerFactory private
Factory of enb component carrier manager object.
Definition at line 752 of file lte-helper.h.
Referenced by GetEnbComponentCarrierManagerType(), InstallSingleEnbDevice(), SetEnbComponentCarrierManagerAttribute(), and SetEnbComponentCarrierManagerType().
m_enbNetDeviceFactory
ObjectFactory ns3::LteHelper::m_enbNetDeviceFactory private
Factory of LteEnbNetDevice objects.
Definition at line 756 of file lte-helper.h.
Referenced by LteHelper(), InstallSingleEnbDevice(), and SetEnbDeviceAttribute().
m_epcHelper
Ptr<EpcHelper> ns3::LteHelper::m_epcHelper private
Helper which provides implementation of core network.
Initially empty (i.e., LTE-only simulation without any core network) and then might be set using SetEpcHelper().
Definition at line 800 of file lte-helper.h.
Referenced by ActivateDataRadioBearer(), ActivateDedicatedEpsBearer(), AddX2Interface(), Attach(), DeActivateDedicatedEpsBearer(), HandoverRequest(), InstallSingleEnbDevice(), InstallSingleUeDevice(), and SetEpcHelper().
m_fadingModel
Ptr<SpectrumPropagationLossModel> ns3::LteHelper::m_fadingModel private
The fading model used in both the downlink and uplink channels.
Definition at line 773 of file lte-helper.h.
Referenced by AssignStreams(), and ChannelModelInitialization().
m_fadingModelFactory
ObjectFactory ns3::LteHelper::m_fadingModelFactory private
Factory of fading model object for both the downlink and uplink channels.
Definition at line 771 of file lte-helper.h.
Referenced by ChannelModelInitialization(), SetFadingModel(), and SetFadingModelAttribute().
m_fadingModelType
std::string ns3::LteHelper::m_fadingModelType private
Name of fading model type, e.g., "ns3::TraceFadingLossModel".
Definition at line 769 of file lte-helper.h.
Referenced by ChannelModelInitialization(), and SetFadingModel().
m_fadingStreamsAssigned
bool ns3::LteHelper::m_fadingStreamsAssigned private
True if a random variable stream number has been assigned for the fading model.
Used to prevent such assignment to be done more than once.
Definition at line 778 of file lte-helper.h.
Referenced by AssignStreams().
m_ffrAlgorithmFactory
ObjectFactory ns3::LteHelper::m_ffrAlgorithmFactory private
Factory of FFR (frequency reuse) algorithm object.
Definition at line 748 of file lte-helper.h.
Referenced by GetFfrAlgorithmType(), InstallSingleEnbDevice(), SetFfrAlgorithmAttribute(), and SetFfrAlgorithmType().
m_handoverAlgorithmFactory
ObjectFactory ns3::LteHelper::m_handoverAlgorithmFactory private
Factory of handover algorithm object.
Definition at line 750 of file lte-helper.h.
Referenced by GetHandoverAlgorithmType(), InstallSingleEnbDevice(), SetHandoverAlgorithmAttribute(), and SetHandoverAlgorithmType().
m_imsiCounter
uint64_t ns3::LteHelper::m_imsiCounter private
Keep track of the number of IMSI allocated.
Increases by one every time a new UE is installed (by InstallSingleUeDevice()). The first UE will have an IMSI of 1. The maximum number of UE is 2^64 (~4.2e9).
Definition at line 807 of file lte-helper.h.
Referenced by InstallSingleUeDevice().
m_isAnrEnabled
bool ns3::LteHelper::m_isAnrEnabled private
The AnrEnabled attribute.
Activate or deactivate Automatic Neighbour Relation function.
Definition at line 824 of file lte-helper.h.
Referenced by GetTypeId(), and InstallSingleEnbDevice().
m_macStats
Ptr<MacStatsCalculator> ns3::LteHelper::m_macStats private
Container of MAC layer statistics.
Definition at line 787 of file lte-helper.h.
Referenced by DoInitialize(), EnableDlMacTraces(), and EnableUlMacTraces().
m_noOfCcs
uint16_t ns3::LteHelper::m_noOfCcs private
Number of component carriers that will be installed by default at eNodeB and UE devices.
Definition at line 848 of file lte-helper.h.
Referenced by ChannelModelInitialization(), DoComponentCarrierConfigure(), GetTypeId(), InstallSingleEnbDevice(), and InstallSingleUeDevice().
m_pathlossModelFactory
ObjectFactory ns3::LteHelper::m_pathlossModelFactory private
Factory of path loss model object.
Definition at line 764 of file lte-helper.h.
Referenced by ChannelModelInitialization(), SetPathlossModelAttribute(), and SetPathlossModelType().
m_pdcpStats
Ptr<RadioBearerStatsCalculator> ns3::LteHelper::m_pdcpStats private
Container of PDCP layer statistics.
Definition at line 791 of file lte-helper.h.
Referenced by EnablePdcpTraces(), and GetPdcpStats().
m_phyRxStats
Ptr<PhyRxStatsCalculator> ns3::LteHelper::m_phyRxStats private
Container of PHY layer statistics related to reception.
Definition at line 785 of file lte-helper.h.
Referenced by DoInitialize(), EnableDlRxPhyTraces(), and EnableUlRxPhyTraces().
m_phyStats
Ptr<PhyStatsCalculator> ns3::LteHelper::m_phyStats private
Container of PHY layer statistics.
Definition at line 781 of file lte-helper.h.
Referenced by DoInitialize(), EnableDlPhyTraces(), and EnableUlPhyTraces().
m_phyTxStats
Ptr<PhyTxStatsCalculator> ns3::LteHelper::m_phyTxStats private
Container of PHY layer statistics related to transmission.
Definition at line 783 of file lte-helper.h.
Referenced by DoInitialize(), EnableDlTxPhyTraces(), and EnableUlTxPhyTraces().
m_radioBearerStatsConnector
RadioBearerStatsConnector ns3::LteHelper::m_radioBearerStatsConnector private
Connects RLC and PDCP statistics containers to appropriate trace sources.
Definition at line 793 of file lte-helper.h.
Referenced by EnablePdcpTraces(), and EnableRlcTraces().
m_rlcStats
Ptr<RadioBearerStatsCalculator> ns3::LteHelper::m_rlcStats private
Container of RLC layer statistics.
Definition at line 789 of file lte-helper.h.
Referenced by EnableRlcTraces(), and GetRlcStats().
m_schedulerFactory
ObjectFactory ns3::LteHelper::m_schedulerFactory private
Factory of MAC scheduler object.
Definition at line 746 of file lte-helper.h.
Referenced by GetSchedulerType(), InstallSingleEnbDevice(), SetSchedulerAttribute(), and SetSchedulerType().
m_ueAntennaModelFactory
ObjectFactory ns3::LteHelper::m_ueAntennaModelFactory private
Factory of antenna object for UE.
Definition at line 762 of file lte-helper.h.
Referenced by LteHelper(), InstallSingleUeDevice(), SetUeAntennaModelAttribute(), and SetUeAntennaModelType().
m_ueComponentCarrierManagerFactory
ObjectFactory ns3::LteHelper::m_ueComponentCarrierManagerFactory private
Factory of ue component carrier manager object.
Definition at line 754 of file lte-helper.h.
Referenced by GetUeComponentCarrierManagerType(), InstallSingleUeDevice(), SetUeComponentCarrierManagerAttribute(), and SetUeComponentCarrierManagerType().
m_ueNetDeviceFactory
ObjectFactory ns3::LteHelper::m_ueNetDeviceFactory private
Factory for LteUeNetDevice objects.
Definition at line 760 of file lte-helper.h.
Referenced by LteHelper(), InstallSingleUeDevice(), and SetUeDeviceAttribute().
m_uplinkChannel
Ptr<SpectrumChannel> ns3::LteHelper::m_uplinkChannel private
The uplink LTE channel used in the simulation.
Definition at line 739 of file lte-helper.h.
Referenced by ChannelModelInitialization(), DoDispose(), GetUplinkSpectrumChannel(), InstallSingleEnbDevice(), and InstallSingleUeDevice().
m_uplinkPathlossModel
Ptr<Object> ns3::LteHelper::m_uplinkPathlossModel private
The path loss model used in the uplink channel.
Definition at line 743 of file lte-helper.h.
Referenced by ChannelModelInitialization(), and InstallSingleEnbDevice().
m_useCa
bool ns3::LteHelper::m_useCa private
The UseCa attribute.
If true, Carrier Aggregation is enabled. Hence, the helper will expect a valid component carrier map If it is false, the component carrier will be created within the LteHelper this is to maintain the backwards compatibility with user script
Definition at line 838 of file lte-helper.h.
Referenced by GetTypeId(), and InstallSingleEnbDevice().
m_useIdealRrc
bool ns3::LteHelper::m_useIdealRrc private
The UseIdealRrc attribute.
If true, LteRrcProtocolIdeal will be used for RRC signaling. If false, LteRrcProtocolReal will be used.
Definition at line 819 of file lte-helper.h.
Referenced by GetTypeId(), InstallSingleEnbDevice(), and InstallSingleUeDevice().
m_usePdschForCqiGeneration
bool ns3::LteHelper::m_usePdschForCqiGeneration private
The UsePdschForCqiGeneration attribute.
If true, DL-CQI will be calculated from PDCCH as signal and PDSCH as interference. If false, DL-CQI will be calculated from PDCCH as signal and PDCCH as interference.
Definition at line 830 of file lte-helper.h.
Referenced by GetTypeId(), and InstallSingleUeDevice().
The documentation for this class was generated from the following files:
src/lte/helper/lte-helper.h
src/lte/helper/lte-helper.cc