ns-3: ns3::SocketIpTosTag Class Reference
ns3::SocketIpTosTag Class Reference
indicates whether the socket has IP_TOS set.
#include "socket.h"
Public Member Functions
SocketIpTosTag ()
virtual void Deserialize (TagBuffer i)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize (void) const
uint8_t GetTos (void) const
Get the tag's TOS.
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer i) const
void SetTos (uint8_t tos)
Set the tag's TOS.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_ipTos
the TOS carried by the tag
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
indicates whether the socket has IP_TOS set.
This tag is for IPv4 socket.
Definition at line 1261 of file socket.h.
Constructor & Destructor Documentation
SocketIpTosTag()
ns3::SocketIpTosTag::SocketIpTosTag ()
Definition at line 780 of file socket.cc.
Member Function Documentation
Deserialize()
void ns3::SocketIpTosTag::Deserialize (TagBuffer i) virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 826 of file socket.cc.
References m_ipTos, and ns3::TagBuffer::ReadU8().
GetInstanceTypeId()
TypeId ns3::SocketIpTosTag::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 808 of file socket.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::SocketIpTosTag::GetSerializedSize (void) const virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 814 of file socket.cc.
GetTos()
uint8_t ns3::SocketIpTosTag::GetTos (void) const
Get the tag's TOS.
Returns
the TOS
Definition at line 791 of file socket.cc.
References m_ipTos.
Referenced by ReceivePacket(), ns3::Ipv4L3Protocol::Send(), TcpDctcpCodePointsTest::Tx(), and ns3::TcpEcnTest::Tx().
GetTypeId()
TypeId ns3::SocketIpTosTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 797 of file socket.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::SocketIpTosTag::Print (std::ostream & os) const virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 831 of file socket.cc.
References m_ipTos.
Serialize()
void ns3::SocketIpTosTag::Serialize (TagBuffer i) const virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 820 of file socket.cc.
References m_ipTos, and ns3::TagBuffer::WriteU8().
SetTos()
void ns3::SocketIpTosTag::SetTos (uint8_t tos)
Set the tag's TOS.
Parameters
tos the TOS
Definition at line 785 of file socket.cc.
References m_ipTos.
Referenced by ns3::TcpSocketBase::AddSocketTags(), ns3::UdpSocketImpl::DoSendTo(), ns3::Ipv4RawSocketImpl::ForwardUp(), ns3::UdpSocketImpl::ForwardUp(), ns3::TcpSocketBase::PersistTimeout(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), and ns3::Ipv4RawSocketImpl::SendTo().
Member Data Documentation
m_ipTos
uint8_t ns3::SocketIpTosTag::m_ipTos private
the TOS carried by the tag
Definition at line 1301 of file socket.h.
Referenced by Deserialize(), GetTos(), Print(), Serialize(), and SetTos().
The documentation for this class was generated from the following files:
src/network/model/socket.h
src/network/model/socket.cc