ns-3: ns3::dsr::DsrOptions Class Reference
ns3::dsr::DsrOptions Class Reference abstract
Introspection did not find any typical Config paths.
#include "dsr-options.h"
Public Member Functions
DsrOptions ()
Constructor.
virtual ~DsrOptions ()
Destructor.
bool CheckDuplicates (Ipv4Address ipv4Address, std::vector< Ipv4Address > &vec)
Check if the route already contains the node ip address.
bool ContainAddressAfter (Ipv4Address ipv4Address, Ipv4Address destAddress, std::vector< Ipv4Address > &nodeList)
Search for the ipv4 address in the node list.
std::vector< Ipv4Address > CutRoute (Ipv4Address ipv4Address, std::vector< Ipv4Address > &nodeList)
Cut the route from ipv4Address to the end of the route vector.
uint32_t GetIDfromIP (Ipv4Address address)
Get the node id with Ipv4Address.
Ptr< Node > GetNode () const
Get the node.
Ptr< Node > GetNodeWithAddress (Ipv4Address ipv4Address)
Get the node object with Ipv4Address.
virtual uint8_t GetOptionNumber () const =0
Get the option number.
bool IfDuplicates (std::vector< Ipv4Address > &vec, std::vector< Ipv4Address > &vec2)
Check if the two vectors contain duplicate or not.
void PrintVector (std::vector< Ipv4Address > &vec)
Print out the elements in the route vector.
virtual uint8_t Process (Ptr< Packet > packet, Ptr< Packet > dsrP, Ipv4Address ipv4Address, Ipv4Address source, Ipv4Header const &ipv4Header, uint8_t protocol, bool &isPromisc, Ipv4Address promiscSource)=0
Process method.
void RemoveDuplicates (std::vector< Ipv4Address > &vec)
Remove the duplicates from the route.
bool ReverseRoutes (std::vector< Ipv4Address > &vec)
Reverse the routes.
Ipv4Address ReverseSearchNextHop (Ipv4Address ipv4Address, std::vector< Ipv4Address > &vec)
Reverse search for the next hop in the route.
Ipv4Address ReverseSearchNextTwoHop (Ipv4Address ipv4Address, std::vector< Ipv4Address > &vec)
Reverse search for the next two hop in the route.
void ScheduleReply (Ptr< Packet > &packet, std::vector< Ipv4Address > &nodeList, Ipv4Address &source, Ipv4Address &destination)
Schedule the intermediate node route request broadcast.
Ipv4Address SearchNextHop (Ipv4Address ipv4Address, std::vector< Ipv4Address > &vec)
Search for the next hop in the route.
void SetNode (Ptr< Node > node)
Set the node.
virtual Ptr< Ipv4Route > SetRoute (Ipv4Address nextHop, Ipv4Address srcAddress)
Set the route to use for data packets, used by the option headers when sending data/control packets.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type identificator.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Attributes
Time ActiveRouteTimeout
The active route timeout value.
Ipv4Address Broadcast
The broadcast IP address.
TracedCallback< Ptr< const Packet > > m_dropTrace
Drop trace callback.
std::vector< Ipv4Address > m_finalRoute
The vector of final Ipv4 address.
Ptr< Ipv4 > m_ipv4
The ipv4.
std::vector< Ipv4Address > m_ipv4Address
The vector of Ipv4 address.
Ptr< Ipv4Route > m_ipv4Route
The ipv4 route.
Ptr< dsr::DsrRouteCache > m_routeCache
The route cache table.
Ptr< dsr::DsrRreqTable > m_rreqTable
The route request table.
TracedCallback< const DsrOptionSRHeader & > m_rxPacketTrace
The receive trace back, only triggered when final destination receive data packet.
Private Attributes
Ptr< Node > m_node
the node
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Introspection did not find any typical Config paths.
Attributes
OptionNumber: The Dsr option number.
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Flags: read
TraceSources
Drop: Packet dropped.
Callback signature: ns3::Packet::TracedCallback
Rx: Receive DSR packet.
Callback signature: ns3::dsr::DsrOptionSRHeader::TracedCallback
Size of this type is 184 bytes (on a 64-bit architecture).
Definition at line 74 of file dsr-options.h.
Constructor & Destructor Documentation
DsrOptions()
ns3::dsr::DsrOptions::DsrOptions ()
Constructor.
Definition at line 89 of file dsr-options.cc.
References NS_LOG_FUNCTION_NOARGS.
~DsrOptions()
ns3::dsr::DsrOptions::~DsrOptions () virtual
Destructor.
Definition at line 94 of file dsr-options.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
CheckDuplicates()
bool ns3::dsr::DsrOptions::CheckDuplicates (Ipv4Address ipv4Address, std::vector< Ipv4Address > & vec)
Check if the route already contains the node ip address.
Parameters
ipv4Address the IPv4 address that we are looking for
vec List of IPv4 addresses
Returns
true if it already exists
Definition at line 284 of file dsr-options.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::dsr::DsrOptionRreq::Process().
ContainAddressAfter()
bool ns3::dsr::DsrOptions::ContainAddressAfter (Ipv4Address ipv4Address, Ipv4Address destAddress, std::vector< Ipv4Address > & nodeList)
Search for the ipv4 address in the node list.
Parameters
ipv4Address IPv4 address to search for
destAddress IPv4 address in the list that we begin the search
nodeList List of IPv4 addresses
Returns
true if contain ip address
Definition at line 111 of file dsr-options.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::dsr::DsrOptionSR::Process().
CutRoute()
std::vector< Ipv4Address > ns3::dsr::DsrOptions::CutRoute (Ipv4Address ipv4Address, std::vector< Ipv4Address > & nodeList)
Cut the route from ipv4Address to the end of the route vector.
Parameters
ipv4Address the address to begin cutting
nodeList List of IPv4 addresses
Returns
the vector after the route cut
Definition at line 127 of file dsr-options.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::dsr::DsrOptionRrep::Process().
GetIDfromIP()
uint32_t ns3::dsr::DsrOptions::GetIDfromIP (Ipv4Address address)
Get the node id with Ipv4Address.
Parameters
address IPv4 address to look for ID
Returns
the id of the node
Definition at line 346 of file dsr-options.cc.
References first::address, ns3::NodeList::GetNNodes(), ns3::NodeList::GetNode(), ns3::Object::GetObject(), and NS_LOG_FUNCTION.
Referenced by ns3::dsr::DsrOptionRreq::Process(), and ns3::dsr::DsrOptionRrep::Process().
GetNode()
Ptr< Node > ns3::dsr::DsrOptions::GetNode (void) const
Get the node.
Returns
the node
Definition at line 105 of file dsr-options.cc.
References m_node, and NS_LOG_FUNCTION_NOARGS.
GetNodeWithAddress()
Ptr< Node > ns3::dsr::DsrOptions::GetNodeWithAddress (Ipv4Address ipv4Address)
Get the node object with Ipv4Address.
Parameters
ipv4Address IPv4 address of the node
Returns
the object of the node
Definition at line 362 of file dsr-options.cc.
References ns3::NodeList::GetNNodes(), ns3::NodeList::GetNode(), ns3::Object::GetObject(), and NS_LOG_FUNCTION.
Referenced by ns3::dsr::DsrOptionRerr::DoSendError(), ns3::dsr::DsrOptionRreq::Process(), ns3::dsr::DsrOptionRrep::Process(), ns3::dsr::DsrOptionSR::Process(), ns3::dsr::DsrOptionRerr::Process(), ns3::dsr::DsrOptionAckReq::Process(), and ns3::dsr::DsrOptionAck::Process().
GetOptionNumber()
virtual uint8_t ns3::dsr::DsrOptions::GetOptionNumber () const pure virtual
Get the option number.
Returns
option number
Implemented in ns3::dsr::DsrOptionAck, ns3::dsr::DsrOptionAckReq, ns3::dsr::DsrOptionRerr, ns3::dsr::DsrOptionSR, ns3::dsr::DsrOptionRrep, ns3::dsr::DsrOptionRreq, ns3::dsr::DsrOptionPadn, and ns3::dsr::DsrOptionPad1.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::dsr::DsrOptions::GetTypeId (void) static
Get the type identificator.
Returns
type identificator
Definition at line 68 of file dsr-options.cc.
References GetOptionNumber(), m_dropTrace, m_rxPacketTrace, ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
IfDuplicates()
bool ns3::dsr::DsrOptions::IfDuplicates (std::vector< Ipv4Address > & vec, std::vector< Ipv4Address > & vec2)
Check if the two vectors contain duplicate or not.
Parameters
vec the first list of IPv4 addresses
vec2 the second list of IPv4 addresses
Returns
true if contains duplicate
Definition at line 264 of file dsr-options.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::dsr::DsrOptionRreq::Process().
PrintVector()
void ns3::dsr::DsrOptions::PrintVector (std::vector< Ipv4Address > & vec)
Print out the elements in the route vector.
Parameters
vec The route vector to print.
Definition at line 244 of file dsr-options.cc.
References NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by ns3::dsr::DsrOptionRreq::Process(), ns3::dsr::DsrOptionRrep::Process(), ns3::dsr::DsrOptionSR::Process(), and RemoveDuplicates().
Process()
virtual uint8_t ns3::dsr::DsrOptions::Process (Ptr< Packet > packet, Ptr< Packet > dsrP, Ipv4Address ipv4Address, Ipv4Address source, Ipv4Header const & ipv4Header, uint8_t protocol, bool & isPromisc, Ipv4Address promiscSource) pure virtual
Process method.
Called from DsrRouting::Receive.
Parameters
packet the packet
dsrP the clean packet with payload
ipv4Address the IPv4 address
source IPv4 address of the source
ipv4Header the IPv4 header of packet received
protocol the protocol number of the up layer
isPromisc if the packet must be dropped
promiscSource IPv4 address
Returns
the processed size
Implemented in ns3::dsr::DsrOptionAck, ns3::dsr::DsrOptionAckReq, ns3::dsr::DsrOptionRerr, ns3::dsr::DsrOptionSR, ns3::dsr::DsrOptionRrep, ns3::dsr::DsrOptionRreq, ns3::dsr::DsrOptionPadn, and ns3::dsr::DsrOptionPad1.
RemoveDuplicates()
void ns3::dsr::DsrOptions::RemoveDuplicates (std::vector< Ipv4Address > & vec)
Remove the duplicates from the route.
Parameters
vec List of IPv4 addresses to be clean
Returns
the route after route shorten
Definition at line 301 of file dsr-options.cc.
References NS_LOG_FUNCTION, and PrintVector().
Referenced by ns3::dsr::DsrOptionRrep::Process().
ReverseRoutes()
bool ns3::dsr::DsrOptions::ReverseRoutes (std::vector< Ipv4Address > & vec)
Reverse the routes.
Parameters
vec List of IPv4 addresses
Returns
true if successfully reversed
Definition at line 149 of file dsr-options.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::dsr::DsrOptionRreq::Process().
ReverseSearchNextHop()
Ipv4Address ns3::dsr::DsrOptions::ReverseSearchNextHop (Ipv4Address ipv4Address, std::vector< Ipv4Address > & vec)
Reverse search for the next hop in the route.
Parameters
ipv4Address the IPv4 address of the node we are looking for its next hop address
vec List of IPv4 addresses
Returns
the previous next hop address if found
Definition at line 199 of file dsr-options.cc.
References NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by ns3::dsr::DsrOptionRreq::Process(), and ns3::dsr::DsrOptionRrep::Process().
ReverseSearchNextTwoHop()
Ipv4Address ns3::dsr::DsrOptions::ReverseSearchNextTwoHop (Ipv4Address ipv4Address, std::vector< Ipv4Address > & vec)
Reverse search for the next two hop in the route.
Parameters
ipv4Address the IPv4 address of the node we are looking for its next two hop address
vec List of IPv4 addresses
Returns
the previous next two hop address if found
Definition at line 225 of file dsr-options.cc.
References NS_ASSERT, NS_FATAL_ERROR, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
ScheduleReply()
void ns3::dsr::DsrOptions::ScheduleReply (Ptr< Packet > & packet, std::vector< Ipv4Address > & nodeList, Ipv4Address & source, Ipv4Address & destination)
Schedule the intermediate node route request broadcast.
Parameters
packet the original packet
nodeList The list of IPv4 addresses
source address
destination address
SearchNextHop()
Ipv4Address ns3::dsr::DsrOptions::SearchNextHop (Ipv4Address ipv4Address, std::vector< Ipv4Address > & vec)
Search for the next hop in the route.
Parameters
ipv4Address the IPv4 address of the node we are looking for its next hop address
vec List of IPv4 addresses
Returns
the next hop address if found
Definition at line 167 of file dsr-options.cc.
References NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by ns3::dsr::DsrOptionRreq::Process(), ns3::dsr::DsrOptionRrep::Process(), and ns3::dsr::DsrOptionSR::Process().
SetNode()
void ns3::dsr::DsrOptions::SetNode (Ptr< Node > node)
Set the node.
Parameters
node the node to set
Definition at line 99 of file dsr-options.cc.
References m_node, and NS_LOG_FUNCTION.
SetRoute()
Ptr< Ipv4Route > ns3::dsr::DsrOptions::SetRoute (Ipv4Address nextHop, Ipv4Address srcAddress) virtual
Set the route to use for data packets, used by the option headers when sending data/control packets.
Parameters
nextHop IPv4 address of the next hop
srcAddress IPv4 address of the source
Returns
the route
Definition at line 139 of file dsr-options.cc.
References m_ipv4Route, NS_LOG_FUNCTION, ns3::Ipv4Route::SetDestination(), ns3::Ipv4Route::SetGateway(), and ns3::Ipv4Route::SetSource().
Referenced by ns3::dsr::DsrOptionRerr::DoSendError(), ns3::dsr::DsrOptionRreq::Process(), ns3::dsr::DsrOptionRrep::Process(), and ns3::dsr::DsrOptionSR::Process().
Member Data Documentation
ActiveRouteTimeout
Time ns3::dsr::DsrOptions::ActiveRouteTimeout protected
The active route timeout value.
Definition at line 264 of file dsr-options.h.
Referenced by ns3::dsr::DsrOptionRreq::Process(), and ns3::dsr::DsrOptionRrep::Process().
Broadcast
Ipv4Address ns3::dsr::DsrOptions::Broadcast protected
The broadcast IP address.
Definition at line 236 of file dsr-options.h.
m_dropTrace
TracedCallback<Ptr<const Packet> > ns3::dsr::DsrOptions::m_dropTrace protected
Drop trace callback.
Definition at line 232 of file dsr-options.h.
Referenced by ns3::dsr::DsrOptionRerr::DoSendError(), GetTypeId(), ns3::dsr::DsrOptionRreq::Process(), ns3::dsr::DsrOptionRrep::Process(), and ns3::dsr::DsrOptionSR::Process().
m_finalRoute
std::vector<Ipv4Address> ns3::dsr::DsrOptions::m_finalRoute protected
The vector of final Ipv4 address.
Definition at line 260 of file dsr-options.h.
Referenced by ns3::dsr::DsrOptionRreq::Process().
m_ipv4
Ptr<Ipv4> ns3::dsr::DsrOptions::m_ipv4 protected
The ipv4.
Definition at line 252 of file dsr-options.h.
m_ipv4Address
std::vector<Ipv4Address> ns3::dsr::DsrOptions::m_ipv4Address protected
The vector of Ipv4 address.
Definition at line 256 of file dsr-options.h.
m_ipv4Route
Ptr<Ipv4Route> ns3::dsr::DsrOptions::m_ipv4Route protected
The ipv4 route.
Definition at line 248 of file dsr-options.h.
Referenced by ns3::dsr::DsrOptionRerr::DoSendError(), ns3::dsr::DsrOptionRreq::Process(), ns3::dsr::DsrOptionRrep::Process(), ns3::dsr::DsrOptionSR::Process(), and SetRoute().
m_node
Ptr<Node> ns3::dsr::DsrOptions::m_node private
the node
Definition at line 271 of file dsr-options.h.
Referenced by GetNode(), and SetNode().
m_routeCache
Ptr<dsr::DsrRouteCache> ns3::dsr::DsrOptions::m_routeCache protected
The route cache table.
Definition at line 244 of file dsr-options.h.
m_rreqTable
Ptr<dsr::DsrRreqTable> ns3::dsr::DsrOptions::m_rreqTable protected
The route request table.
Definition at line 240 of file dsr-options.h.
m_rxPacketTrace
TracedCallback<const DsrOptionSRHeader &> ns3::dsr::DsrOptions::m_rxPacketTrace protected
The receive trace back, only triggered when final destination receive data packet.
Definition at line 268 of file dsr-options.h.
Referenced by GetTypeId().
The documentation for this class was generated from the following files:
src/dsr/model/dsr-options.h
src/dsr/model/dsr-options.cc