ns-3: ns3::ArpCache Class Reference
ns3::ArpCache Class Reference
Internet » IPv4 classes and sub-modules » ARP protocol.
An ARP cache.
#include "arp-cache.h"
Classes
class Entry
A record that that holds information about an ArpCache entry.
Public Types
typedef std::pair< Ptr< Packet >, Ipv4Header > Ipv4PayloadHeaderPair
Pair of a packet and an Ipv4 header.
Public Member Functions
ArpCache ()
~ArpCache ()
ArpCache::Entry * Add (Ipv4Address to)
Add an Ipv4Address to this ARP cache.
void Flush (void)
Clear the ArpCache of all entries.
Time GetAliveTimeout (void) const
Get the time the entry will be in ALIVE state (unless refreshed)
Time GetDeadTimeout (void) const
Get the time the entry will be in DEAD state before being removed.
Ptr< NetDevice > GetDevice (void) const
Returns the NetDevice that this ARP cache is associated with.
Ptr< Ipv4Interface > GetInterface (void) const
Returns the Ipv4Interface that this ARP cache is associated with.
Time GetWaitReplyTimeout (void) const
Get the time the entry will be in WAIT_REPLY state.
ArpCache::Entry * Lookup (Ipv4Address destination)
Do lookup in the ARP cache against an IP address.
std::list< ArpCache::Entry * > LookupInverse (Address destination)
Do lookup in the ARP cache against a MAC address.
void PrintArpCache (Ptr< OutputStreamWrapper > stream)
Print the ARP cache entries.
void Remove (ArpCache::Entry *entry)
Remove an entry.
void SetAliveTimeout (Time aliveTimeout)
Set the time the entry will be in ALIVE state (unless refreshed)
void SetArpRequestCallback (Callback< void, Ptr< const ArpCache >, Ipv4Address > arpRequestCallback)
This callback is set when the ArpCache is set up and allows the cache to generate an Arp request when the WaitReply time expires and a retransmission must be sent.
void SetDeadTimeout (Time deadTimeout)
Set the time the entry will be in DEAD state before being removed.
void SetDevice (Ptr< NetDevice > device, Ptr< Ipv4Interface > interface)
Set the NetDevice and Ipv4Interface associated with the ArpCache.
void SetWaitReplyTimeout (Time waitReplyTimeout)
Set the time the entry will be in WAIT_REPLY state.
void StartWaitReplyTimer (void)
This method will schedule a timeout at WaitReplyTimeout interval in the future, unless a timer is already running for the cache, in which case this method does nothing.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef sgi::hash_map< Ipv4Address, ArpCache::Entry *, Ipv4AddressHash > Cache
ARP Cache container.
typedef sgi::hash_map< Ipv4Address, ArpCache::Entry *, Ipv4AddressHash >::iterator CacheI
ARP Cache container iterator.
Private Member Functions
ArpCache (ArpCache const &)
Copy constructor.
virtual void DoDispose (void)
Destructor implementation.
void HandleWaitReplyTimeout (void)
This function is an event handler for the event that the ArpCache wants to check whether it must retry any Arp requests.
ArpCache & operator= (ArpCache const &)
Copy constructor.
Private Attributes
Time m_aliveTimeout
cache alive state timeout
Cache m_arpCache
the ARP cache
Callback< void, Ptr< const ArpCache >, Ipv4Address > m_arpRequestCallback
reply timeout callback
Time m_deadTimeout
cache dead state timeout
Ptr< NetDevice > m_device
NetDevice associated with the cache.
TracedCallback< Ptr< const Packet > > m_dropTrace
trace for packets dropped by the ARP cache queue
Ptr< Ipv4Interface > m_interface
Ipv4Interface associated with the cache.
uint32_t m_maxRetries
max retries for a resolution
uint32_t m_pendingQueueSize
number of packets waiting for a resolution
Time m_waitReplyTimeout
cache reply state timeout
EventId m_waitReplyTimer
cache alive state timer
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
An ARP cache.
A cached lookup table for translating layer 3 addresses to layer 2. This implementation does lookups from IPv4 to a MAC address
Config Paths
ns3::ArpCache is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::Ipv4L3Protocol/InterfaceList/[i]/ArpCache"
"/NodeList/[i]/$ns3::ArpL3Protocol/CacheList/[i]"
Attributes
AliveTimeout: When this timeout expires, the matching cache entry needs refreshing
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1.2e+11ns
Flags: construct write read
DeadTimeout: When this timeout expires, a new attempt to resolve the matching entry is made
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+11ns
Flags: construct write read
WaitReplyTimeout: When this timeout expires, the cache entries will be scanned and entries in WaitReply state will resend ArpRequest unless MaxRetries has been exceeded, in which case the entry is marked dead
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+09ns
Flags: construct write read
MaxRetries: Number of retransmissions of ArpRequest before marking dead
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 3
Flags: construct write read
PendingQueueSize: The size of the queue for packets pending an arp reply.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 3
Flags: construct write read
TraceSources
Drop: Packet dropped due to ArpCache entry in WaitReply expiring.
Callback signature: ns3::Packet::TracedCallback
Size of this type is 176 bytes (on a 64-bit architecture).
Definition at line 51 of file arp-cache.h.
Member Typedef Documentation
Cache
typedef sgi::hash_map<Ipv4Address, ArpCache::Entry *, Ipv4AddressHash> ns3::ArpCache::Cache private
ARP Cache container.
Definition at line 316 of file arp-cache.h.
CacheI
typedef sgi::hash_map<Ipv4Address, ArpCache::Entry *, Ipv4AddressHash>::iterator ns3::ArpCache::CacheI private
ARP Cache container iterator.
Definition at line 320 of file arp-cache.h.
Ipv4PayloadHeaderPair
typedef std::pair<Ptr<Packet>, Ipv4Header> ns3::ArpCache::Ipv4PayloadHeaderPair
Pair of a packet and an Ipv4 header.
Definition at line 183 of file arp-cache.h.
Constructor & Destructor Documentation
ArpCache() [1/2]
ns3::ArpCache::ArpCache (ArpCache const &) private
Copy constructor.
Defined and unimplemented to avoid misuse
ArpCache() [2/2]
ns3::ArpCache::ArpCache ()
Definition at line 87 of file arp-cache.cc.
References NS_LOG_FUNCTION.
~ArpCache()
ns3::ArpCache::~ArpCache ()
Definition at line 94 of file arp-cache.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Add()
ArpCache::Entry * ns3::ArpCache::Add (Ipv4Address to)
Add an Ipv4Address to this ARP cache.
Parameters
to the destination address of the ARP entry.
Returns
A pointer to a new ARP Entry.
Definition at line 330 of file arp-cache.cc.
References m_arpCache, NS_ASSERT, NS_LOG_FUNCTION, and ns3::ArpCache::Entry::SetIpv4Address().
Referenced by EpcS1uUlTestCase::DoRun(), and ns3::ArpL3Protocol::Lookup().
DoDispose()
void ns3::ArpCache::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 100 of file arp-cache.cc.
References ns3::EventId::Cancel(), ns3::Object::DoDispose(), Flush(), ns3::EventId::IsRunning(), m_device, m_interface, m_waitReplyTimer, and NS_LOG_FUNCTION.
Flush()
void ns3::ArpCache::Flush (void)
Clear the ArpCache of all entries.
Definition at line 244 of file arp-cache.cc.
References ns3::EventId::Cancel(), ns3::EventId::IsRunning(), m_arpCache, m_waitReplyTimer, ns3::Simulator::Now(), NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by ns3::ArpL3Protocol::CreateCache(), and DoDispose().
GetAliveTimeout()
Time ns3::ArpCache::GetAliveTimeout (void) const
Get the time the entry will be in ALIVE state (unless refreshed)
Returns
the Alive state timeout
Definition at line 155 of file arp-cache.cc.
References m_aliveTimeout, and NS_LOG_FUNCTION.
GetDeadTimeout()
Time ns3::ArpCache::GetDeadTimeout (void) const
Get the time the entry will be in DEAD state before being removed.
Returns
the Dead state timeout
Definition at line 161 of file arp-cache.cc.
References m_deadTimeout, and NS_LOG_FUNCTION.
GetDevice()
Ptr< NetDevice > ns3::ArpCache::GetDevice (void) const
Returns the NetDevice that this ARP cache is associated with.
Returns
The NetDevice that this ARP cache is associated with
Definition at line 122 of file arp-cache.cc.
References m_device, and NS_LOG_FUNCTION.
GetInterface()
Ptr< Ipv4Interface > ns3::ArpCache::GetInterface (void) const
Returns the Ipv4Interface that this ARP cache is associated with.
Returns
the Ipv4Interface that this ARP cache is associated with
Definition at line 129 of file arp-cache.cc.
References m_interface, and NS_LOG_FUNCTION.
Referenced by ns3::ArpL3Protocol::Receive().
GetTypeId()
TypeId ns3::ArpCache::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 41 of file arp-cache.cc.
References m_aliveTimeout, m_deadTimeout, m_dropTrace, m_maxRetries, m_pendingQueueSize, m_waitReplyTimeout, ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), ns3::Seconds(), and ns3::TypeId::SetParent().
GetWaitReplyTimeout()
Time ns3::ArpCache::GetWaitReplyTimeout (void) const
Get the time the entry will be in WAIT_REPLY state.
Returns
the WAIT_REPLY state timeout
Definition at line 167 of file arp-cache.cc.
References m_waitReplyTimeout, and NS_LOG_FUNCTION.
HandleWaitReplyTimeout()
void ns3::ArpCache::HandleWaitReplyTimeout (void) private
This function is an event handler for the event that the ArpCache wants to check whether it must retry any Arp requests.
If there are no Arp requests pending, this event is not scheduled.
Definition at line 195 of file arp-cache.cc.
References ns3::ArpCache::Entry::ClearRetries(), ns3::ArpCache::Entry::DequeuePending(), ns3::ArpCache::Entry::GetIpv4Address(), ns3::ArpCache::Entry::GetRetries(), ns3::ArpCache::Entry::IncrementRetries(), ns3::ArpCache::Entry::IsWaitReply(), m_arpCache, m_arpRequestCallback, m_device, m_dropTrace, m_maxRetries, m_waitReplyTimeout, m_waitReplyTimer, ns3::ArpCache::Entry::MarkDead(), ns3::Simulator::Now(), NS_LOG_FUNCTION, NS_LOG_LOGIC, and ns3::Simulator::Schedule().
Referenced by StartWaitReplyTimer().
Lookup()
ArpCache::Entry * ns3::ArpCache::Lookup (Ipv4Address destination)
Do lookup in the ARP cache against an IP address.
Parameters
destination The destination IPv4 address to lookup the MAC address of
Returns
An ArpCache::Entry with info about layer 2
Definition at line 318 of file arp-cache.cc.
References m_arpCache, and NS_LOG_FUNCTION.
Referenced by ns3::ArpL3Protocol::Lookup(), ns3::ArpL3Protocol::Receive(), and ns3::Ipv4L3Protocol::Receive().
LookupInverse()
std::list< ArpCache::Entry * > ns3::ArpCache::LookupInverse (Address destination)
Do lookup in the ARP cache against a MAC address.
Parameters
destination The destination MAC address to lookup of
Returns
A std::list of ArpCache::Entry with info about layer 2
Definition at line 300 of file arp-cache.cc.
References ns3::ArpCache::Entry::GetMacAddress(), m_arpCache, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4L3Protocol::Receive().
operator=()
ArpCache& ns3::ArpCache::operator= (ArpCache const &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Returns
PrintArpCache()
void ns3::ArpCache::PrintArpCache (Ptr< OutputStreamWrapper > stream)
Print the ARP cache entries.
Parameters
stream the ostream the ARP cache entries is printed to
Definition at line 260 of file arp-cache.cc.
References ns3::Names::FindName(), ns3::OutputStreamWrapper::GetStream(), m_arpCache, m_device, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4RoutingHelper::PrintArpCache(), and ns3::Ipv4RoutingHelper::PrintArpCacheEvery().
Remove()
void ns3::ArpCache::Remove (ArpCache::Entry * entry)
Remove an entry.
Parameters
entry pointer to delete it from the list
Definition at line 342 of file arp-cache.cc.
References ns3::ArpCache::Entry::ClearPendingPacket(), m_arpCache, NS_LOG_FUNCTION, and NS_LOG_WARN.
SetAliveTimeout()
void ns3::ArpCache::SetAliveTimeout (Time aliveTimeout)
Set the time the entry will be in ALIVE state (unless refreshed)
Parameters
aliveTimeout the Alive state timeout
Definition at line 136 of file arp-cache.cc.
References m_aliveTimeout, and NS_LOG_FUNCTION.
Referenced by EpcS1uUlTestCase::DoRun().
SetArpRequestCallback()
void ns3::ArpCache::SetArpRequestCallback (Callback< void, Ptr< const ArpCache >, Ipv4Address > arpRequestCallback)
This callback is set when the ArpCache is set up and allows the cache to generate an Arp request when the WaitReply time expires and a retransmission must be sent.
Parameters
arpRequestCallback Callback for transmitting an Arp request.
Definition at line 174 of file arp-cache.cc.
References m_arpRequestCallback, and NS_LOG_FUNCTION.
SetDeadTimeout()
void ns3::ArpCache::SetDeadTimeout (Time deadTimeout)
Set the time the entry will be in DEAD state before being removed.
Parameters
deadTimeout the Dead state timeout
Definition at line 142 of file arp-cache.cc.
References m_deadTimeout, and NS_LOG_FUNCTION.
SetDevice()
void ns3::ArpCache::SetDevice (Ptr< NetDevice > device, Ptr< Ipv4Interface > interface)
Set the NetDevice and Ipv4Interface associated with the ArpCache.
Parameters
device The hardware NetDevice associated with this ARP cache
interface the Ipv4Interface associated with this ARP cache
Definition at line 114 of file arp-cache.cc.
References m_device, m_interface, and NS_LOG_FUNCTION.
SetWaitReplyTimeout()
void ns3::ArpCache::SetWaitReplyTimeout (Time waitReplyTimeout)
Set the time the entry will be in WAIT_REPLY state.
Parameters
waitReplyTimeout the WAIT_REPLY state timeout
Definition at line 148 of file arp-cache.cc.
References m_waitReplyTimeout, and NS_LOG_FUNCTION.
StartWaitReplyTimer()
void ns3::ArpCache::StartWaitReplyTimer (void)
This method will schedule a timeout at WaitReplyTimeout interval in the future, unless a timer is already running for the cache, in which case this method does nothing.
Definition at line 182 of file arp-cache.cc.
References HandleWaitReplyTimeout(), ns3::EventId::IsRunning(), m_waitReplyTimeout, m_waitReplyTimer, ns3::Simulator::Now(), NS_LOG_FUNCTION, NS_LOG_LOGIC, and ns3::Simulator::Schedule().
Member Data Documentation
m_aliveTimeout
Time ns3::ArpCache::m_aliveTimeout private
cache alive state timeout
Definition at line 326 of file arp-cache.h.
Referenced by GetAliveTimeout(), GetTypeId(), and SetAliveTimeout().
m_arpCache
Cache ns3::ArpCache::m_arpCache private
the ARP cache
Definition at line 340 of file arp-cache.h.
Referenced by Add(), Flush(), HandleWaitReplyTimeout(), Lookup(), LookupInverse(), PrintArpCache(), and Remove().
m_arpRequestCallback
Callback<void, Ptr<const ArpCache>, Ipv4Address> ns3::ArpCache::m_arpRequestCallback private
reply timeout callback
Definition at line 330 of file arp-cache.h.
Referenced by HandleWaitReplyTimeout(), and SetArpRequestCallback().
m_deadTimeout
Time ns3::ArpCache::m_deadTimeout private
cache dead state timeout
Definition at line 327 of file arp-cache.h.
Referenced by GetDeadTimeout(), GetTypeId(), and SetDeadTimeout().
m_device
Ptr<NetDevice> ns3::ArpCache::m_device private
NetDevice associated with the cache.
Definition at line 324 of file arp-cache.h.
Referenced by DoDispose(), GetDevice(), HandleWaitReplyTimeout(), PrintArpCache(), and SetDevice().
m_dropTrace
TracedCallback<Ptr<const Packet> > ns3::ArpCache::m_dropTrace private
trace for packets dropped by the ARP cache queue
Definition at line 341 of file arp-cache.h.
Referenced by GetTypeId(), and HandleWaitReplyTimeout().
m_interface
Ptr<Ipv4Interface> ns3::ArpCache::m_interface private
Ipv4Interface associated with the cache.
Definition at line 325 of file arp-cache.h.
Referenced by DoDispose(), GetInterface(), and SetDevice().
m_maxRetries
uint32_t ns3::ArpCache::m_maxRetries private
max retries for a resolution
Definition at line 331 of file arp-cache.h.
Referenced by GetTypeId(), and HandleWaitReplyTimeout().
m_pendingQueueSize
uint32_t ns3::ArpCache::m_pendingQueueSize private
number of packets waiting for a resolution
Definition at line 339 of file arp-cache.h.
Referenced by GetTypeId().
m_waitReplyTimeout
Time ns3::ArpCache::m_waitReplyTimeout private
cache reply state timeout
Definition at line 328 of file arp-cache.h.
Referenced by GetTypeId(), GetWaitReplyTimeout(), HandleWaitReplyTimeout(), SetWaitReplyTimeout(), and StartWaitReplyTimer().
m_waitReplyTimer
EventId ns3::ArpCache::m_waitReplyTimer private
cache alive state timer
Definition at line 329 of file arp-cache.h.
Referenced by DoDispose(), Flush(), HandleWaitReplyTimeout(), and StartWaitReplyTimer().
The documentation for this class was generated from the following files:
src/internet/model/arp-cache.h
src/internet/model/arp-cache.cc