ns-3: ns3::Ipv4ListRouting Class Reference
ns3::Ipv4ListRouting Class Reference
Internet » IPv4 Routing Protocols.
IPv4 list routing.
#include "ipv4-list-routing.h"
Public Member Functions
Ipv4ListRouting ()
virtual ~Ipv4ListRouting ()
virtual void AddRoutingProtocol (Ptr< Ipv4RoutingProtocol > routingProtocol, int16_t priority)
Register a new routing protocol to be used in this IPv4 stack.
virtual uint32_t GetNRoutingProtocols (void) const
virtual Ptr< Ipv4RoutingProtocol > GetRoutingProtocol (uint32_t index, int16_t &priority) const
Return pointer to routing protocol stored at index, with the first protocol (index 0) the highest priority, the next one (index 1) the second highest priority, and so on.
virtual void NotifyAddAddress (uint32_t interface, Ipv4InterfaceAddress address)
virtual void NotifyInterfaceDown (uint32_t interface)
virtual void NotifyInterfaceUp (uint32_t interface)
virtual void NotifyRemoveAddress (uint32_t interface, Ipv4InterfaceAddress address)
virtual void PrintRoutingTable (Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S) const
Print the Routing Table entries.
virtual bool RouteInput (Ptr< const Packet > p, const Ipv4Header &header, Ptr< const NetDevice > idev, UnicastForwardCallback ucb, MulticastForwardCallback mcb, LocalDeliverCallback lcb, ErrorCallback ecb)
Route an input packet (to be forwarded or locally delivered)
virtual Ptr< Ipv4Route > RouteOutput (Ptr< Packet > p, const Ipv4Header &header, Ptr< NetDevice > oif, Socket::SocketErrno &sockerr)
Query routing cache for an existing route, for an outbound packet.
virtual void SetIpv4 (Ptr< Ipv4 > ipv4)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID of this class.
Static Public Member Functions inherited from ns3::Ipv4RoutingProtocol
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
typedef std::pair< int16_t, Ptr< Ipv4RoutingProtocol > > Ipv4RoutingProtocolEntry
Container identifying an IPv4 Routing Protocol entry in the list.
typedef std::list< Ipv4RoutingProtocolEntry > Ipv4RoutingProtocolList
Container of the IPv4 Routing Protocols.
Static Private Member Functions
static bool Compare (const Ipv4RoutingProtocolEntry &a, const Ipv4RoutingProtocolEntry &b)
Compare two routing protocols.
Private Attributes
Ptr< Ipv4 > m_ipv4
Ipv4 this protocol is associated with.
Ipv4RoutingProtocolList m_routingProtocols
List of routing protocols.
Additional Inherited Members
Public Types inherited from ns3::Ipv4RoutingProtocol
typedef Callback< void, Ptr< const Packet >, const Ipv4Header &, Socket::SocketErrno > ErrorCallback
Callback for routing errors (e.g., no route found)
typedef Callback< void, Ptr< const Packet >, const Ipv4Header &, uint32_t > LocalDeliverCallback
Callback for packets to be locally delivered.
typedef Callback< void, Ptr< Ipv4MulticastRoute >, Ptr< const Packet >, const Ipv4Header & > MulticastForwardCallback
Callback for multicast packets to be forwarded.
typedef Callback< void, Ptr< Ipv4Route >, Ptr< const Packet >, const Ipv4Header & > UnicastForwardCallback
Callback for unicast packets to be forwarded.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
IPv4 list routing.
Introspection did not find any typical Config paths.
This class is a specialization of Ipv4RoutingProtocol that allows other instances of Ipv4RoutingProtocol to be inserted in a prioritized list. Routing protocols in the list are consulted one by one, from highest to lowest priority, until a routing protocol is found that will take the packet (this corresponds to a non-zero return value to RouteOutput, or a return value of true to RouteInput). The order by which routing protocols with the same priority value are consulted is undefined.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 64 bytes (on a 64-bit architecture).
Definition at line 44 of file ipv4-list-routing.h.
Member Typedef Documentation
Ipv4RoutingProtocolEntry
typedef std::pair<int16_t, Ptr<Ipv4RoutingProtocol> > ns3::Ipv4ListRouting::Ipv4RoutingProtocolEntry private
Container identifying an IPv4 Routing Protocol entry in the list.
Definition at line 101 of file ipv4-list-routing.h.
Ipv4RoutingProtocolList
typedef std::list<Ipv4RoutingProtocolEntry> ns3::Ipv4ListRouting::Ipv4RoutingProtocolList private
Container of the IPv4 Routing Protocols.
Definition at line 105 of file ipv4-list-routing.h.
Constructor & Destructor Documentation
Ipv4ListRouting()
ns3::Ipv4ListRouting::Ipv4ListRouting ()
Definition at line 45 of file ipv4-list-routing.cc.
References NS_LOG_FUNCTION.
~Ipv4ListRouting()
ns3::Ipv4ListRouting::~Ipv4ListRouting () virtual
Definition at line 51 of file ipv4-list-routing.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddRoutingProtocol()
void ns3::Ipv4ListRouting::AddRoutingProtocol (Ptr< Ipv4RoutingProtocol > routingProtocol, int16_t priority) virtual
Register a new routing protocol to be used in this IPv4 stack.
Parameters
routingProtocol new routing protocol implementation object
priority priority to give to this routing protocol. Values may range between -32768 and +32767.
Definition at line 253 of file ipv4-list-routing.cc.
References Compare(), m_ipv4, m_routingProtocols, and NS_LOG_FUNCTION.
Compare()
bool ns3::Ipv4ListRouting::Compare (const Ipv4RoutingProtocolEntry & a, const Ipv4RoutingProtocolEntry & b) static private
Compare two routing protocols.
Parameters
a first object to compare
b second object to compare
Returns
true if they are the same, false otherwise
Definition at line 293 of file ipv4-list-routing.cc.
References NS_LOG_FUNCTION.
Referenced by AddRoutingProtocol().
DoDispose()
void ns3::Ipv4ListRouting::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 57 of file ipv4-list-routing.cc.
References m_ipv4, m_routingProtocols, and NS_LOG_FUNCTION.
DoInitialize()
void ns3::Ipv4ListRouting::DoInitialize (void) protected virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 89 of file ipv4-list-routing.cc.
References ns3::Object::DoInitialize(), m_routingProtocols, and NS_LOG_FUNCTION.
GetNRoutingProtocols()
uint32_t ns3::Ipv4ListRouting::GetNRoutingProtocols (void) const virtual
Returns
number of routing protocols in the list
Definition at line 265 of file ipv4-list-routing.cc.
References m_routingProtocols, and NS_LOG_FUNCTION.
GetRoutingProtocol()
Ptr< Ipv4RoutingProtocol > ns3::Ipv4ListRouting::GetRoutingProtocol (uint32_t index, int16_t & priority) const virtual
Return pointer to routing protocol stored at index, with the first protocol (index 0) the highest priority, the next one (index 1) the second highest priority, and so on.
The priority parameter is an output parameter and it returns the integer priority of the protocol.
Returns
pointer to routing protocol indexed by
Parameters
index index of protocol to return
priority output parameter, set to the priority of the protocol being returned
Definition at line 272 of file ipv4-list-routing.cc.
References m_routingProtocols, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::Ipv4ListRouting::GetTypeId (void) static
Get the type ID of this class.
Returns
type ID
Definition at line 34 of file ipv4-list-routing.cc.
References ns3::TypeId::SetParent().
Referenced by RouteOutput().
NotifyAddAddress()
void ns3::Ipv4ListRouting::NotifyAddAddress (uint32_t interface, Ipv4InterfaceAddress address) virtual
Parameters
interface the index of the interface we are being notified about
address a new address being added to an interface
Protocols are expected to implement this method to be notified whenever a new address is added to an interface. Typically used to add a 'network route' on an interface. Can be invoked on an up or down interface.
Implements ns3::Ipv4RoutingProtocol.
Definition at line 214 of file ipv4-list-routing.cc.
References first::address, m_routingProtocols, and NS_LOG_FUNCTION.
NotifyInterfaceDown()
void ns3::Ipv4ListRouting::NotifyInterfaceDown (uint32_t interface) virtual
Parameters
interface the index of the interface we are being notified about
Protocols are expected to implement this method to be notified of the state change of an interface in a node.
Implements ns3::Ipv4RoutingProtocol.
Definition at line 202 of file ipv4-list-routing.cc.
References m_routingProtocols, and NS_LOG_FUNCTION.
NotifyInterfaceUp()
void ns3::Ipv4ListRouting::NotifyInterfaceUp (uint32_t interface) virtual
Parameters
interface the index of the interface we are being notified about
Protocols are expected to implement this method to be notified of the state change of an interface in a node.
Implements ns3::Ipv4RoutingProtocol.
Definition at line 190 of file ipv4-list-routing.cc.
References m_routingProtocols, and NS_LOG_FUNCTION.
NotifyRemoveAddress()
void ns3::Ipv4ListRouting::NotifyRemoveAddress (uint32_t interface, Ipv4InterfaceAddress address) virtual
Parameters
interface the index of the interface we are being notified about
address a new address being added to an interface
Protocols are expected to implement this method to be notified whenever a new address is removed from an interface. Typically used to remove the 'network route' of an interface. Can be invoked on an up or down interface.
Implements ns3::Ipv4RoutingProtocol.
Definition at line 226 of file ipv4-list-routing.cc.
References first::address, m_routingProtocols, and NS_LOG_FUNCTION.
PrintRoutingTable()
void ns3::Ipv4ListRouting::PrintRoutingTable (Ptr< OutputStreamWrapper > stream, Time::Unit unit = Time::S) const virtual
Print the Routing Table entries.
Parameters
stream The ostream the Routing table is printed to
unit The time unit to be used in the report
Implements ns3::Ipv4RoutingProtocol.
Definition at line 73 of file ipv4-list-routing.cc.
References ns3::Time::As(), ns3::OutputStreamWrapper::GetStream(), m_ipv4, m_routingProtocols, ns3::Now(), and NS_LOG_FUNCTION.
RouteInput()
bool ns3::Ipv4ListRouting::RouteInput (Ptr< const Packet > p, const Ipv4Header & header, Ptr< const NetDevice > idev, UnicastForwardCallback ucb, MulticastForwardCallback mcb, LocalDeliverCallback lcb, ErrorCallback ecb) virtual
Route an input packet (to be forwarded or locally delivered)
This lookup is used in the forwarding process. The packet is handed over to the Ipv4RoutingProtocol, and will get forwarded onward by one of the callbacks. The Linux equivalent is ip_route_input(). There are four valid outcomes, and a matching callbacks to handle each.
Parameters
p received packet
header input parameter used to form a search key for a route
idev Pointer to ingress network device
ucb Callback for the case in which the packet is to be forwarded as unicast
mcb Callback for the case in which the packet is to be forwarded as multicast
lcb Callback for the case in which the packet is to be locally delivered
ecb Callback to call if there is an error in forwarding
Returns
true if the Ipv4RoutingProtocol takes responsibility for forwarding or delivering the packet, false otherwise
Implements ns3::Ipv4RoutingProtocol.
Definition at line 129 of file ipv4-list-routing.cc.
References ns3::Socket::ERROR_NOROUTETOHOST, ns3::Ipv4Header::GetDestination(), ns3::Node::GetId(), ns3::Ipv4Address::IsMulticast(), m_ipv4, m_routingProtocols, NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
RouteOutput()
Ptr< Ipv4Route > ns3::Ipv4ListRouting::RouteOutput (Ptr< Packet > p, const Ipv4Header & header, Ptr< NetDevice > oif, Socket::SocketErrno & sockerr) virtual
Query routing cache for an existing route, for an outbound packet.
This lookup is used by transport protocols. It does not cause any packet to be forwarded, and is synchronous. Can be used for multicast or unicast. The Linux equivalent is ip_route_output()
The header input parameter may have an uninitialized value for the source address, but the destination address should always be properly set by the caller.
Parameters
p packet to be routed. Note that this method may modify the packet. Callers may also pass in a null pointer.
header input parameter (used to form key to search for the route)
oif Output interface Netdevice. May be zero, or may be bound via socket options to a particular output interface.
sockerr Output parameter; socket errno
Returns
a code that indicates what happened in the lookup
Implements ns3::Ipv4RoutingProtocol.
Definition at line 103 of file ipv4-list-routing.cc.
References ns3::Socket::ERROR_NOROUTETOHOST, ns3::Socket::ERROR_NOTERROR, ns3::Ipv4Header::GetDestination(), ns3::Ipv4Header::GetSource(), GetTypeId(), m_routingProtocols, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
SetIpv4()
void ns3::Ipv4ListRouting::SetIpv4 (Ptr< Ipv4 > ipv4) virtual
Parameters
ipv4 the ipv4 object this routing protocol is being associated with
Typically, invoked directly or indirectly from ns3::Ipv4::SetRoutingProtocol
Implements ns3::Ipv4RoutingProtocol.
Definition at line 238 of file ipv4-list-routing.cc.
References m_ipv4, m_routingProtocols, NS_ASSERT, and NS_LOG_FUNCTION.
Member Data Documentation
m_ipv4
Ptr<Ipv4> ns3::Ipv4ListRouting::m_ipv4 private
Ipv4 this protocol is associated with.
Definition at line 115 of file ipv4-list-routing.h.
Referenced by AddRoutingProtocol(), DoDispose(), PrintRoutingTable(), RouteInput(), and SetIpv4().
m_routingProtocols
Ipv4RoutingProtocolList ns3::Ipv4ListRouting::m_routingProtocols private
List of routing protocols.
Definition at line 106 of file ipv4-list-routing.h.
Referenced by AddRoutingProtocol(), DoDispose(), DoInitialize(), GetNRoutingProtocols(), GetRoutingProtocol(), NotifyAddAddress(), NotifyInterfaceDown(), NotifyInterfaceUp(), NotifyRemoveAddress(), PrintRoutingTable(), RouteInput(), RouteOutput(), and SetIpv4().
The documentation for this class was generated from the following files:
src/internet/model/ipv4-list-routing.h
src/internet/model/ipv4-list-routing.cc