ns-3: Sender Class Reference
Sender Class Reference
#include "wifi-example-apps.h"
Public Member Functions
Sender ()
virtual ~Sender ()
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Application
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void SendPacket ()
virtual void StartApplication (void)
Application specific startup code.
virtual void StopApplication (void)
Application specific shutdown code.
Private Attributes
uint32_t m_count
Ipv4Address m_destAddr
uint32_t m_destPort
Ptr< ConstantRandomVariable > m_interval
uint32_t m_numPkts
uint32_t m_pktSize
EventId m_sendEvent
Ptr< Socket > m_socket
TracedCallback< Ptr< const Packet > > m_txTrace
Additional Inherited Members
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 38 of file wifi-example-apps.h.
Constructor & Destructor Documentation
Sender()
Sender::Sender ()
Definition at line 76 of file wifi-example-apps.cc.
References NS_LOG_FUNCTION_NOARGS.
~Sender()
Sender::~Sender () virtual
Definition at line 83 of file wifi-example-apps.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
DoDispose()
void Sender::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Application.
Definition at line 89 of file wifi-example-apps.cc.
References ns3::Application::DoDispose(), and NS_LOG_FUNCTION_NOARGS.
GetTypeId()
TypeId Sender::GetTypeId (void) static
Definition at line 43 of file wifi-example-apps.cc.
References m_destAddr, m_destPort, m_interval, m_numPkts, m_pktSize, m_txTrace, ns3::MakeIpv4AddressAccessor(), ns3::MakeIpv4AddressChecker(), ns3::MakePointerAccessor(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
SendPacket()
void Sender::SendPacket () private
Definition at line 124 of file wifi-example-apps.cc.
References ns3::Packet::AddByteTag(), ns3::Simulator::Now(), NS_LOG_INFO, ns3::Simulator::Schedule(), ns3::Seconds(), and TimestampTag::SetTimestamp().
Referenced by StartApplication().
StartApplication()
void Sender::StartApplication (void) private virtual
Application specific startup code.
The StartApplication method is called at the start time specified by Start This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 98 of file wifi-example-apps.cc.
References ns3::Simulator::Cancel(), ns3::UdpSocketFactory::GetTypeId(), NS_LOG_FUNCTION_NOARGS, ns3::Simulator::ScheduleNow(), and SendPacket().
StopApplication()
void Sender::StopApplication (void) private virtual
Application specific shutdown code.
The StopApplication method is called at the stop time specified by Stop This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 117 of file wifi-example-apps.cc.
References ns3::Simulator::Cancel(), and NS_LOG_FUNCTION_NOARGS.
Member Data Documentation
m_count
uint32_t Sender::m_count private
Definition at line 64 of file wifi-example-apps.h.
m_destAddr
Ipv4Address Sender::m_destAddr private
Definition at line 54 of file wifi-example-apps.h.
Referenced by GetTypeId().
m_destPort
uint32_t Sender::m_destPort private
Definition at line 55 of file wifi-example-apps.h.
Referenced by GetTypeId().
m_interval
Ptr<ConstantRandomVariable> Sender::m_interval private
Definition at line 56 of file wifi-example-apps.h.
Referenced by GetTypeId().
m_numPkts
uint32_t Sender::m_numPkts private
Definition at line 57 of file wifi-example-apps.h.
Referenced by GetTypeId().
m_pktSize
uint32_t Sender::m_pktSize private
Definition at line 53 of file wifi-example-apps.h.
Referenced by GetTypeId().
m_sendEvent
EventId Sender::m_sendEvent private
Definition at line 60 of file wifi-example-apps.h.
m_socket
Ptr<Socket> Sender::m_socket private
Definition at line 59 of file wifi-example-apps.h.
m_txTrace
TracedCallback<Ptr<const Packet> > Sender::m_txTrace private
Definition at line 62 of file wifi-example-apps.h.
Referenced by GetTypeId().
The documentation for this class was generated from the following files:
examples/stats/wifi-example-apps.h
examples/stats/wifi-example-apps.cc