ns-3: ns3::HalfDuplexIdealPhy Class Reference
ns3::HalfDuplexIdealPhy Class Reference
Spectrum Models
This PHY layer implementation realizes an ideal OFDM PHY which transmits half-duplex (i.e., it can either receive or transmit at a given time).
#include "half-duplex-ideal-phy.h"
Public Types
enum State { IDLE , TX , RX }
PHY states.
Public Member Functions
HalfDuplexIdealPhy ()
virtual ~HalfDuplexIdealPhy ()
Ptr< NetDevice > GetDevice () const
Get the associated NetDevice instance.
Ptr< MobilityModel > GetMobility ()
Get the associated MobilityModel instance.
DataRate GetRate () const
Get the PHY rate to be used by this PHY.
Ptr< AntennaModel > GetRxAntenna ()
Get the AntennaModel used by the NetDevice for reception.
Ptr< const SpectrumModel > GetRxSpectrumModel () const
void SetAntenna (Ptr< AntennaModel > a)
set the AntennaModel to be used
void SetChannel (Ptr< SpectrumChannel > c)
Set the channel attached to this device.
void SetDevice (Ptr< NetDevice > d)
Set the associated NetDevice instance.
void SetGenericPhyRxEndErrorCallback (GenericPhyRxEndErrorCallback c)
set the callback for the end of a RX in error, as part of the interconnections between the PHY and the MAC
void SetGenericPhyRxEndOkCallback (GenericPhyRxEndOkCallback c)
set the callback for the successful end of a RX, as part of the interconnections between the PHY and the MAC
void SetGenericPhyRxStartCallback (GenericPhyRxStartCallback c)
Set the callback for the start of RX, as part of the interconnections between the PHY and the MAC.
void SetGenericPhyTxEndCallback (GenericPhyTxEndCallback c)
Set the callback for the end of a TX, as part of the interconnections between the PHY and the MAC.
void SetMobility (Ptr< MobilityModel > m)
Set the mobility model associated with this device.
void SetNoisePowerSpectralDensity (Ptr< const SpectrumValue > noisePsd)
Set the Noise Power Spectral Density in power units (Watt, Pascal...) per Hz.
void SetRate (DataRate rate)
Set the PHY rate to be used by this PHY.
void SetTxPowerSpectralDensity (Ptr< SpectrumValue > txPsd)
Set the Power Spectral Density of outgoing signals in power units (Watt, Pascal...) per Hz.
void StartRx (Ptr< SpectrumSignalParameters > params)
Notify the SpectrumPhy instance of an incoming signal.
bool StartTx (Ptr< Packet > p)
Start a transmission.
Public Member Functions inherited from ns3::SpectrumPhy
SpectrumPhy ()
virtual ~SpectrumPhy ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::SpectrumPhy
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void AbortRx ()
About current Rx.
void ChangeState (State newState)
Change the PHY state.
virtual void DoDispose (void)
Destructor implementation.
void EndRx ()
End current Rx.
void EndTx ()
End the current Tx.
Private Attributes
Ptr< AntennaModel > m_antenna
Antenna model.
Ptr< SpectrumChannel > m_channel
Channel.
EventId m_endRxEventId
End Rx event.
SpectrumInterference m_interference
Received interference.
Ptr< MobilityModel > m_mobility
Mobility model.
Ptr< NetDevice > m_netDevice
NetDevice connected to theis phy.
GenericPhyRxEndErrorCallback m_phyMacRxEndErrorCallback
Callback - Rx error.
GenericPhyRxEndOkCallback m_phyMacRxEndOkCallback
Callback - Rx end.
GenericPhyRxStartCallback m_phyMacRxStartCallback
Callback - Rx start.
GenericPhyTxEndCallback m_phyMacTxEndCallback
Callback - Tx end.
TracedCallback< Ptr< const Packet > > m_phyRxAbortTrace
Trace - Rx abort.
TracedCallback< Ptr< const Packet > > m_phyRxEndErrorTrace
Trace - Rx end (error)
TracedCallback< Ptr< const Packet > > m_phyRxEndOkTrace
Trace - Tx end (ok)
TracedCallback< Ptr< const Packet > > m_phyRxStartTrace
Trace - Rx start.
TracedCallback< Ptr< const Packet > > m_phyTxEndTrace
Trace - Tx end.
TracedCallback< Ptr< const Packet > > m_phyTxStartTrace
Trace - Tx start.
DataRate m_rate
Datarate.
Ptr< Packet > m_rxPacket
Rx packet.
Ptr< const SpectrumValue > m_rxPsd
Rx power spectral density.
State m_state
PHY state.
Ptr< Packet > m_txPacket
Tx packet.
Ptr< SpectrumValue > m_txPsd
Tx power spectral density.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This PHY layer implementation realizes an ideal OFDM PHY which transmits half-duplex (i.e., it can either receive or transmit at a given time).
Introspection did not find any typical Config paths.
The device is ideal in the sense that: 1) it uses an error model based on the Shannon capacity, which assumes ideal channel coding; 2) it uses ideal signal acquisition, i.e., preamble detection and synchronization are always successful 3) it has no PHY layer overhead
Being half duplex, if a RX is ongoing but a TX is requested, the RX is aborted and the TX is started. Of course, no RX can be performed while there is an ongoing TX.
The use of OFDM is modeled by means of the Spectrum framework. By calling the method SetTxPowerSpectralDensity(), the user can specify how much of the spectrum is used, how many subcarriers are used, and what power is allocated to each subcarrier.
The user can also specify the PHY rate at which communications take place by using SetRate(). This is equivalent to choosing a particular modulation and coding scheme.
The use of the ShannonSpectrumErrorModel allows us to account for the following aspects in determining whether a transmission is successful or not:
the PHY rate (trades off communication speed with reliability)
the power spectral density (trade-off among total power consumed, total bandwidth used (i.e., how much of the spectrum is occupied), and communication reliability)
the signal propagation
This PHY model supports a single antenna model instance which is used for both transmission and reception.
Attributes
Rate: The PHY rate used by this device
Set with class: DataRateValue
Underlying type: DataRate
Initial value: 1000000bps
Flags: construct write read
TraceSources
TxStart: Trace fired when a new transmission is started
Callback signature: ns3::Packet::TracedCallback
TxEnd: Trace fired when a previously started transmission is finished
Callback signature: ns3::Packet::TracedCallback
RxStart: Trace fired when the start of a signal is detected
Callback signature: ns3::Packet::TracedCallback
RxAbort: Trace fired when a previously started RX is aborted before time
Callback signature: ns3::Packet::TracedCallback
RxEndOk: Trace fired when a previously started RX terminates successfully
Callback signature: ns3::Packet::TracedCallback
RxEndError: Trace fired when a previously started RX terminates with an error (packet is corrupted)
Callback signature: ns3::Packet::TracedCallback
Size of this type is 384 bytes (on a 64-bit architecture).
Definition at line 78 of file half-duplex-ideal-phy.h.
Member Enumeration Documentation
State
enum ns3::HalfDuplexIdealPhy::State
PHY states.
Enumerator
IDLE
Idle state.
TX
Transmitting state.
RX
Receiving state.
Definition at line 88 of file half-duplex-ideal-phy.h.
Constructor & Destructor Documentation
HalfDuplexIdealPhy()
ns3::HalfDuplexIdealPhy::HalfDuplexIdealPhy ()
Definition at line 41 of file half-duplex-ideal-phy.cc.
References m_interference, and ns3::SpectrumInterference::SetErrorModel().
~HalfDuplexIdealPhy()
ns3::HalfDuplexIdealPhy::~HalfDuplexIdealPhy () virtual
Definition at line 52 of file half-duplex-ideal-phy.cc.
Member Function Documentation
AbortRx()
void ns3::HalfDuplexIdealPhy::AbortRx () private
About current Rx.
Definition at line 406 of file half-duplex-ideal-phy.cc.
References ns3::SpectrumInterference::AbortRx(), ns3::EventId::Cancel(), ChangeState(), IDLE, m_endRxEventId, m_interference, m_phyRxAbortTrace, m_rxPacket, m_state, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, and RX.
Referenced by StartTx().
ChangeState()
void ns3::HalfDuplexIdealPhy::ChangeState (State newState) private
Change the PHY state.
Parameters
newState new state
Definition at line 273 of file half-duplex-ideal-phy.cc.
References m_state, and NS_LOG_LOGIC.
Referenced by AbortRx(), EndRx(), EndTx(), StartRx(), and StartTx().
DoDispose()
void ns3::HalfDuplexIdealPhy::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 57 of file half-duplex-ideal-phy.cc.
References ns3::Object::DoDispose(), m_channel, m_mobility, m_netDevice, m_phyMacRxEndErrorCallback, m_phyMacRxEndOkCallback, m_phyMacRxStartCallback, m_phyMacTxEndCallback, m_rxPacket, m_rxPsd, m_txPacket, m_txPsd, and NS_LOG_FUNCTION.
EndRx()
void ns3::HalfDuplexIdealPhy::EndRx () private
End current Rx.
Definition at line 421 of file half-duplex-ideal-phy.cc.
References ChangeState(), ns3::SpectrumInterference::EndRx(), IDLE, ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_interference, m_phyMacRxEndErrorCallback, m_phyMacRxEndOkCallback, m_phyRxEndErrorTrace, m_phyRxEndOkTrace, m_rxPacket, m_rxPsd, m_state, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, and RX.
Referenced by StartRx().
EndTx()
void ns3::HalfDuplexIdealPhy::EndTx (void) private
End the current Tx.
Definition at line 321 of file half-duplex-ideal-phy.cc.
References ChangeState(), IDLE, ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_phyMacTxEndCallback, m_phyTxEndTrace, m_state, m_txPacket, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, and TX.
Referenced by StartTx().
GetDevice()
Ptr< NetDevice > ns3::HalfDuplexIdealPhy::GetDevice () const virtual
Get the associated NetDevice instance.
Returns
a Ptr to the associated NetDevice instance
Implements ns3::SpectrumPhy.
Definition at line 145 of file half-duplex-ideal-phy.cc.
References m_netDevice, and NS_LOG_FUNCTION.
GetMobility()
Ptr< MobilityModel > ns3::HalfDuplexIdealPhy::GetMobility () virtual
Get the associated MobilityModel instance.
Returns
a Ptr to the associated MobilityModel instance
Implements ns3::SpectrumPhy.
Definition at line 153 of file half-duplex-ideal-phy.cc.
References m_mobility, and NS_LOG_FUNCTION.
GetRate()
DataRate ns3::HalfDuplexIdealPhy::GetRate (void) const
Get the PHY rate to be used by this PHY.
Returns
the PHY rate used by this PHY.
Definition at line 221 of file half-duplex-ideal-phy.cc.
References m_rate, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetRxAntenna()
Ptr< AntennaModel > ns3::HalfDuplexIdealPhy::GetRxAntenna () virtual
Get the AntennaModel used by the NetDevice for reception.
Returns
a Ptr to the AntennaModel used by the NetDevice for reception
Implements ns3::SpectrumPhy.
Definition at line 259 of file half-duplex-ideal-phy.cc.
References m_antenna, and NS_LOG_FUNCTION.
GetRxSpectrumModel()
Ptr< const SpectrumModel > ns3::HalfDuplexIdealPhy::GetRxSpectrumModel () const virtual
Returns
returns the SpectrumModel that this SpectrumPhy expects to be used for all SpectrumValues that are passed to StartRx. If 0 is returned, it means that any model will be accepted.
Implements ns3::SpectrumPhy.
Definition at line 184 of file half-duplex-ideal-phy.cc.
References ns3::SpectrumValue::GetSpectrumModel(), and m_txPsd.
GetTypeId()
TypeId ns3::HalfDuplexIdealPhy::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 102 of file half-duplex-ideal-phy.cc.
References GetRate(), m_phyRxAbortTrace, m_phyRxEndErrorTrace, m_phyRxEndOkTrace, m_phyRxStartTrace, m_phyTxEndTrace, m_phyTxStartTrace, ns3::MakeDataRateAccessor(), ns3::MakeDataRateChecker(), ns3::MakeTraceSourceAccessor(), ns3::TypeId::SetParent(), and SetRate().
SetAntenna()
void ns3::HalfDuplexIdealPhy::SetAntenna (Ptr< AntennaModel > a)
set the AntennaModel to be used
Parameters
a the Antenna Model
Definition at line 266 of file half-duplex-ideal-phy.cc.
References m_antenna, and NS_LOG_FUNCTION.
SetChannel()
void ns3::HalfDuplexIdealPhy::SetChannel (Ptr< SpectrumChannel > c) virtual
Set the channel attached to this device.
Parameters
c the channel
Implements ns3::SpectrumPhy.
Definition at line 177 of file half-duplex-ideal-phy.cc.
References m_channel, and NS_LOG_FUNCTION.
SetDevice()
void ns3::HalfDuplexIdealPhy::SetDevice (Ptr< NetDevice > d) virtual
Set the associated NetDevice instance.
Parameters
d the NetDevice instance
Implements ns3::SpectrumPhy.
Definition at line 161 of file half-duplex-ideal-phy.cc.
References m_netDevice, and NS_LOG_FUNCTION.
SetGenericPhyRxEndErrorCallback()
void ns3::HalfDuplexIdealPhy::SetGenericPhyRxEndErrorCallback (GenericPhyRxEndErrorCallback c)
set the callback for the end of a RX in error, as part of the interconnections between the PHY and the MAC
Parameters
c the callback
Definition at line 244 of file half-duplex-ideal-phy.cc.
References m_phyMacRxEndErrorCallback, and NS_LOG_FUNCTION.
SetGenericPhyRxEndOkCallback()
void ns3::HalfDuplexIdealPhy::SetGenericPhyRxEndOkCallback (GenericPhyRxEndOkCallback c)
set the callback for the successful end of a RX, as part of the interconnections between the PHY and the MAC
Parameters
c the callback
Definition at line 252 of file half-duplex-ideal-phy.cc.
References m_phyMacRxEndOkCallback, and NS_LOG_FUNCTION.
SetGenericPhyRxStartCallback()
void ns3::HalfDuplexIdealPhy::SetGenericPhyRxStartCallback (GenericPhyRxStartCallback c)
Set the callback for the start of RX, as part of the interconnections between the PHY and the MAC.
Parameters
c the callback
Definition at line 236 of file half-duplex-ideal-phy.cc.
References m_phyMacRxStartCallback, and NS_LOG_FUNCTION.
SetGenericPhyTxEndCallback()
void ns3::HalfDuplexIdealPhy::SetGenericPhyTxEndCallback (GenericPhyTxEndCallback c)
Set the callback for the end of a TX, as part of the interconnections between the PHY and the MAC.
Parameters
c the callback
Definition at line 229 of file half-duplex-ideal-phy.cc.
References m_phyMacTxEndCallback, and NS_LOG_FUNCTION.
SetMobility()
void ns3::HalfDuplexIdealPhy::SetMobility (Ptr< MobilityModel > m) virtual
Set the mobility model associated with this device.
Parameters
m the mobility model
Implements ns3::SpectrumPhy.
Definition at line 169 of file half-duplex-ideal-phy.cc.
References m_mobility, and NS_LOG_FUNCTION.
SetNoisePowerSpectralDensity()
void ns3::HalfDuplexIdealPhy::SetNoisePowerSpectralDensity (Ptr< const SpectrumValue > noisePsd)
Set the Noise Power Spectral Density in power units (Watt, Pascal...) per Hz.
Parameters
noisePsd the Noise Power Spectral Density
Definition at line 206 of file half-duplex-ideal-phy.cc.
References m_interference, NS_ASSERT, NS_LOG_FUNCTION, and ns3::SpectrumInterference::SetNoisePowerSpectralDensity().
SetRate()
void ns3::HalfDuplexIdealPhy::SetRate (DataRate rate)
Set the PHY rate to be used by this PHY.
Parameters
rate DataRate
Definition at line 214 of file half-duplex-ideal-phy.cc.
References m_rate, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetTxPowerSpectralDensity()
void ns3::HalfDuplexIdealPhy::SetTxPowerSpectralDensity (Ptr< SpectrumValue > txPsd)
Set the Power Spectral Density of outgoing signals in power units (Watt, Pascal...) per Hz.
Parameters
txPsd Tx Power Spectral Density
Definition at line 197 of file half-duplex-ideal-phy.cc.
References m_txPsd, NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_INFO.
StartRx()
void ns3::HalfDuplexIdealPhy::StartRx (Ptr< SpectrumSignalParameters > params) virtual
Notify the SpectrumPhy instance of an incoming signal.
Parameters
params the parameters of the signals being received
Implements ns3::SpectrumPhy.
Definition at line 341 of file half-duplex-ideal-phy.cc.
References ns3::SpectrumInterference::AddSignal(), ChangeState(), EndRx(), IDLE, ns3::Integral(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_endRxEventId, m_interference, m_phyMacRxStartCallback, m_phyRxStartTrace, m_rxPacket, m_rxPsd, m_state, NS_LOG_FUNCTION, NS_LOG_LOGIC, RX, ns3::Simulator::Schedule(), ns3::SpectrumInterference::StartRx(), and TX.
StartTx()
bool ns3::HalfDuplexIdealPhy::StartTx (Ptr< Packet > p)
Start a transmission.
Parameters
p the packet to be transmitted
Returns
true if an error occurred and the transmission was not started, false otherwise.
Definition at line 280 of file half-duplex-ideal-phy.cc.
References AbortRx(), ns3::DataRate::CalculateBytesTxTime(), ChangeState(), EndTx(), ns3::Packet::GetSize(), IDLE, ns3::Integral(), m_antenna, m_channel, m_phyTxStartTrace, m_rate, m_state, m_txPacket, m_txPsd, NS_LOG_FUNCTION, NS_LOG_LOGIC, RX, ns3::Simulator::Schedule(), and TX.
Referenced by ns3::AdhocAlohaNoackIdealPhyHelper::Install().
Member Data Documentation
m_antenna
Ptr<AntennaModel> ns3::HalfDuplexIdealPhy::m_antenna private
Antenna model.
Definition at line 216 of file half-duplex-ideal-phy.h.
Referenced by GetRxAntenna(), SetAntenna(), and StartTx().
m_channel
Ptr<SpectrumChannel> ns3::HalfDuplexIdealPhy::m_channel private
Channel.
Definition at line 218 of file half-duplex-ideal-phy.h.
Referenced by DoDispose(), SetChannel(), and StartTx().
m_endRxEventId
EventId ns3::HalfDuplexIdealPhy::m_endRxEventId private
End Rx event.
Definition at line 213 of file half-duplex-ideal-phy.h.
Referenced by AbortRx(), and StartRx().
m_interference
SpectrumInterference ns3::HalfDuplexIdealPhy::m_interference private
Received interference.
Definition at line 240 of file half-duplex-ideal-phy.h.
Referenced by HalfDuplexIdealPhy(), AbortRx(), EndRx(), SetNoisePowerSpectralDensity(), and StartRx().
m_mobility
Ptr<MobilityModel> ns3::HalfDuplexIdealPhy::m_mobility private
Mobility model.
Definition at line 215 of file half-duplex-ideal-phy.h.
Referenced by DoDispose(), GetMobility(), and SetMobility().
m_netDevice
Ptr<NetDevice> ns3::HalfDuplexIdealPhy::m_netDevice private
NetDevice connected to theis phy.
Definition at line 217 of file half-duplex-ideal-phy.h.
Referenced by DoDispose(), GetDevice(), and SetDevice().
m_phyMacRxEndErrorCallback
GenericPhyRxEndErrorCallback ns3::HalfDuplexIdealPhy::m_phyMacRxEndErrorCallback private
Callback - Rx error.
Definition at line 237 of file half-duplex-ideal-phy.h.
Referenced by DoDispose(), EndRx(), and SetGenericPhyRxEndErrorCallback().
m_phyMacRxEndOkCallback
GenericPhyRxEndOkCallback ns3::HalfDuplexIdealPhy::m_phyMacRxEndOkCallback private
Callback - Rx end.
Definition at line 238 of file half-duplex-ideal-phy.h.
Referenced by DoDispose(), EndRx(), and SetGenericPhyRxEndOkCallback().
m_phyMacRxStartCallback
GenericPhyRxStartCallback ns3::HalfDuplexIdealPhy::m_phyMacRxStartCallback private
Callback - Rx start.
Definition at line 236 of file half-duplex-ideal-phy.h.
Referenced by DoDispose(), SetGenericPhyRxStartCallback(), and StartRx().
m_phyMacTxEndCallback
GenericPhyTxEndCallback ns3::HalfDuplexIdealPhy::m_phyMacTxEndCallback private
Callback - Tx end.
Definition at line 235 of file half-duplex-ideal-phy.h.
Referenced by DoDispose(), EndTx(), and SetGenericPhyTxEndCallback().
m_phyRxAbortTrace
TracedCallback<Ptr<const Packet> > ns3::HalfDuplexIdealPhy::m_phyRxAbortTrace private
Trace - Rx abort.
Definition at line 231 of file half-duplex-ideal-phy.h.
Referenced by AbortRx(), and GetTypeId().
m_phyRxEndErrorTrace
TracedCallback<Ptr<const Packet> > ns3::HalfDuplexIdealPhy::m_phyRxEndErrorTrace private
Trace - Rx end (error)
Definition at line 233 of file half-duplex-ideal-phy.h.
Referenced by EndRx(), and GetTypeId().
m_phyRxEndOkTrace
TracedCallback<Ptr<const Packet> > ns3::HalfDuplexIdealPhy::m_phyRxEndOkTrace private
Trace - Tx end (ok)
Definition at line 232 of file half-duplex-ideal-phy.h.
Referenced by EndRx(), and GetTypeId().
m_phyRxStartTrace
TracedCallback<Ptr<const Packet> > ns3::HalfDuplexIdealPhy::m_phyRxStartTrace private
Trace - Rx start.
Definition at line 230 of file half-duplex-ideal-phy.h.
Referenced by GetTypeId(), and StartRx().
m_phyTxEndTrace
TracedCallback<Ptr<const Packet> > ns3::HalfDuplexIdealPhy::m_phyTxEndTrace private
Trace - Tx end.
Definition at line 229 of file half-duplex-ideal-phy.h.
Referenced by EndTx(), and GetTypeId().
m_phyTxStartTrace
TracedCallback<Ptr<const Packet> > ns3::HalfDuplexIdealPhy::m_phyTxStartTrace private
Trace - Tx start.
Definition at line 228 of file half-duplex-ideal-phy.h.
Referenced by GetTypeId(), and StartTx().
m_rate
DataRate ns3::HalfDuplexIdealPhy::m_rate private
Datarate.
Definition at line 225 of file half-duplex-ideal-phy.h.
Referenced by GetRate(), SetRate(), and StartTx().
m_rxPacket
Ptr<Packet> ns3::HalfDuplexIdealPhy::m_rxPacket private
Rx packet.
Definition at line 223 of file half-duplex-ideal-phy.h.
Referenced by AbortRx(), DoDispose(), EndRx(), and StartRx().
m_rxPsd
Ptr<const SpectrumValue> ns3::HalfDuplexIdealPhy::m_rxPsd private
Rx power spectral density.
Definition at line 221 of file half-duplex-ideal-phy.h.
Referenced by DoDispose(), EndRx(), and StartRx().
m_state
State ns3::HalfDuplexIdealPhy::m_state private
PHY state.
Definition at line 226 of file half-duplex-ideal-phy.h.
Referenced by AbortRx(), ChangeState(), EndRx(), EndTx(), StartRx(), and StartTx().
m_txPacket
Ptr<Packet> ns3::HalfDuplexIdealPhy::m_txPacket private
Tx packet.
Definition at line 222 of file half-duplex-ideal-phy.h.
Referenced by DoDispose(), EndTx(), and StartTx().
m_txPsd
Ptr<SpectrumValue> ns3::HalfDuplexIdealPhy::m_txPsd private
Tx power spectral density.
Definition at line 220 of file half-duplex-ideal-phy.h.
Referenced by DoDispose(), GetRxSpectrumModel(), SetTxPowerSpectralDensity(), and StartTx().
The documentation for this class was generated from the following files:
src/spectrum/model/half-duplex-ideal-phy.h
src/spectrum/model/half-duplex-ideal-phy.cc