ns-3: ns3::ThreeGppChannelConditionModel Class Reference
ns3::ThreeGppChannelConditionModel Class Reference abstract
Propagation Models
Base class for the 3GPP channel condition models.
#include "channel-condition-model.h"
Classes
struct Item
Struct to store the channel condition in the m_channelConditionMap.
Public Member Functions
ThreeGppChannelConditionModel ()
Constructor for the ThreeGppRmaChannelConditionModel class.
virtual ~ThreeGppChannelConditionModel () override
Destructor for the ThreeGppRmaChannelConditionModel class.
virtual int64_t AssignStreams (int64_t stream) override
If this model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
virtual Ptr< ChannelCondition > GetChannelCondition (Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const override
Retrieve the condition of the channel between a and b.
Public Member Functions inherited from ns3::ChannelConditionModel
ChannelConditionModel ()
Constructor for the ChannelConditionModel class.
ChannelConditionModel (const ChannelConditionModel &)=delete
Copy constructor.
virtual ~ChannelConditionModel ()
Destructor for the ChannelConditionModel class.
ChannelConditionModel & operator= (const ChannelConditionModel &)=delete
Copy constructor.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ChannelConditionModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Types
enum VehicleDensity { LOW , MEDIUM , HIGH , INVALID }
Determine the density of vehicles in a V2V scenario.
Protected Member Functions
virtual void DoDispose () override
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Static Protected Member Functions
static double Calculate2dDistance (const Vector &a, const Vector &b)
Computes the 2D distance between two 3D vectors.
Protected Attributes
Ptr< UniformRandomVariable > m_uniformVar
uniform random variable
Private Member Functions
Ptr< ChannelCondition > ComputeChannelCondition (Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const
This method computes the channel condition based on a probabilistic model that is specific for the scenario of interest.
virtual double ComputePlos (Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const =0
Compute the LOS probability.
virtual double ComputePnlos (Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const
Compute the NLOS probability.
Static Private Member Functions
static uint32_t GetKey (Ptr< const MobilityModel > a, Ptr< const MobilityModel > b)
Returns a unique and reciprocal key for the channel between a and b.
Private Attributes
std::unordered_map< uint32_t, Item > m_channelConditionMap
map to store the channel conditions
Time m_updatePeriod
the update period for the channel condition
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Base class for the 3GPP channel condition models.
Config Paths
ns3::ThreeGppChannelConditionModel is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::SpectrumChannel/PropagationLossModel/$ns3::ThreeGppPropagationLossModel/ChannelConditionModel/$ns3::ThreeGppChannelConditionModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Channel/$ns3::YansWifiChannel/PropagationLossModel/$ns3::ThreeGppPropagationLossModel/ChannelConditionModel/$ns3::ThreeGppChannelConditionModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::LrWpanNetDevice/Channel/PropagationLossModel/$ns3::ThreeGppPropagationLossModel/ChannelConditionModel/$ns3::ThreeGppChannelConditionModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::SpectrumChannel/PropagationLossModel/$ns3::ThreeGppPropagationLossModel/ChannelConditionModel/$ns3::ThreeGppChannelConditionModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/Channel/$ns3::YansWifiChannel/PropagationLossModel/$ns3::ThreeGppPropagationLossModel/ChannelConditionModel/$ns3::ThreeGppChannelConditionModel"
"/ChannelList/[i]/$ns3::SpectrumChannel/PropagationLossModel/$ns3::ThreeGppPropagationLossModel/ChannelConditionModel/$ns3::ThreeGppChannelConditionModel"
"/ChannelList/[i]/$ns3::YansWifiChannel/PropagationLossModel/$ns3::ThreeGppPropagationLossModel/ChannelConditionModel/$ns3::ThreeGppChannelConditionModel"
Attributes
UpdatePeriod: Specifies the time period after which the channel condition is recomputed. If set to 0, the channel condition is never updated.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 88 bytes (on a 64-bit architecture).
Definition at line 446 of file channel-condition-model.h.
Member Enumeration Documentation
VehicleDensity
enum ns3::ThreeGppChannelConditionModel::VehicleDensity protected
Determine the density of vehicles in a V2V scenario.
Enumerator
LOW
MEDIUM
HIGH
INVALID
Definition at line 496 of file channel-condition-model.h.
Constructor & Destructor Documentation
ThreeGppChannelConditionModel()
ns3::ThreeGppChannelConditionModel::ThreeGppChannelConditionModel ()
Constructor for the ThreeGppRmaChannelConditionModel class.
Definition at line 296 of file channel-condition-model.cc.
References m_uniformVar, and ns3::ObjectBase::SetAttribute().
~ThreeGppChannelConditionModel()
ns3::ThreeGppChannelConditionModel::~ThreeGppChannelConditionModel () override virtual
Destructor for the ThreeGppRmaChannelConditionModel class.
Definition at line 304 of file channel-condition-model.cc.
Member Function Documentation
AssignStreams()
int64_t ns3::ThreeGppChannelConditionModel::AssignStreams (int64_t stream) override virtual
If this model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream the offset used to set the stream numbers
Returns
the number of stream indices assigned by this model
Implements ns3::ChannelConditionModel.
Definition at line 407 of file channel-condition-model.cc.
References m_uniformVar, and ns3::RandomVariableStream::SetStream().
Referenced by ThreeGppV2vUrbanLosNlosvChCondModelTestCase::DoRun(), ThreeGppV2vHighwayLosNlosvChCondModelTestCase::DoRun(), V2vUrbanProbChCondModelTestCase::DoRun(), and V2vHighwayProbChCondModelTestCase::DoRun().
Calculate2dDistance()
double ns3::ThreeGppChannelConditionModel::Calculate2dDistance (const Vector & a, const Vector & b) static protected
Computes the 2D distance between two 3D vectors.
Parameters
a the first 3D vector
b the second 3D vector
Returns
the 2D distance between a and b
Definition at line 414 of file channel-condition-model.cc.
References sample-rng-plot::x.
Referenced by ns3::ThreeGppV2vUrbanChannelConditionModel::ComputePlos(), ns3::ThreeGppV2vHighwayChannelConditionModel::ComputePlos(), ns3::ThreeGppRmaChannelConditionModel::ComputePlos(), ns3::ThreeGppUmaChannelConditionModel::ComputePlos(), ns3::ThreeGppUmiStreetCanyonChannelConditionModel::ComputePlos(), ns3::ThreeGppIndoorMixedOfficeChannelConditionModel::ComputePlos(), ns3::ThreeGppIndoorOpenOfficeChannelConditionModel::ComputePlos(), ns3::ProbabilisticV2vUrbanChannelConditionModel::ComputePlos(), ns3::ProbabilisticV2vHighwayChannelConditionModel::ComputePlos(), ns3::ProbabilisticV2vUrbanChannelConditionModel::ComputePnlos(), and ns3::ProbabilisticV2vHighwayChannelConditionModel::ComputePnlos().
ComputeChannelCondition()
Ptr< ChannelCondition > ns3::ThreeGppChannelConditionModel::ComputeChannelCondition (Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const private
This method computes the channel condition based on a probabilistic model that is specific for the scenario of interest.
Parameters
a tx mobility model
b rx mobility model
Returns
the channel condition
Definition at line 362 of file channel-condition-model.cc.
References ComputePlos(), ComputePnlos(), ns3::UniformRandomVariable::GetValue(), m_uniformVar, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by GetChannelCondition().
ComputePlos()
virtual double ns3::ThreeGppChannelConditionModel::ComputePlos (Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const private pure virtual
Compute the LOS probability.
Parameters
a tx mobility model
b rx mobility model
Returns
the LOS probability
Implemented in ns3::ProbabilisticV2vHighwayChannelConditionModel, ns3::ProbabilisticV2vUrbanChannelConditionModel, ns3::ThreeGppIndoorOpenOfficeChannelConditionModel, ns3::ThreeGppIndoorMixedOfficeChannelConditionModel, ns3::ThreeGppUmiStreetCanyonChannelConditionModel, ns3::ThreeGppUmaChannelConditionModel, ns3::ThreeGppRmaChannelConditionModel, ns3::ThreeGppV2vHighwayChannelConditionModel, and ns3::ThreeGppV2vUrbanChannelConditionModel.
Referenced by ComputeChannelCondition(), and ComputePnlos().
ComputePnlos()
double ns3::ThreeGppChannelConditionModel::ComputePnlos (Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const private virtual
Compute the NLOS probability.
By default returns 1 - PLOS
Parameters
a tx mobility model
b rx mobility model
Returns
the LOS probability
Reimplemented in ns3::ProbabilisticV2vHighwayChannelConditionModel, ns3::ProbabilisticV2vUrbanChannelConditionModel, ns3::ThreeGppV2vHighwayChannelConditionModel, and ns3::ThreeGppV2vUrbanChannelConditionModel.
Definition at line 398 of file channel-condition-model.cc.
References ComputePlos(), and NS_LOG_FUNCTION.
Referenced by ComputeChannelCondition().
DoDispose()
void ns3::ThreeGppChannelConditionModel::DoDispose (void) override protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 307 of file channel-condition-model.cc.
References m_channelConditionMap, m_updatePeriod, and ns3::Seconds().
GetChannelCondition()
Ptr< ChannelCondition > ns3::ThreeGppChannelConditionModel::GetChannelCondition (Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const override virtual
Retrieve the condition of the channel between a and b.
If the channel condition does not exists, the method computes it by calling ComputeChannelCondition and stores it in a local cache, that will be updated following the "UpdatePeriod" parameter.
Parameters
a mobility model
b mobility model
Returns
the condition of the channel between a and b
Implements ns3::ChannelConditionModel.
Definition at line 314 of file channel-condition-model.cc.
References ComputeChannelCondition(), GetKey(), ns3::Time::IsZero(), m_channelConditionMap, ns3::ThreeGppChannelConditionModel::Item::m_condition, ns3::ThreeGppChannelConditionModel::Item::m_generatedTime, m_updatePeriod, ns3::Simulator::Now(), and NS_LOG_DEBUG.
Referenced by ThreeGppV2vUrbanLosNlosvChCondModelTestCase::EvaluateChannelCondition(), ThreeGppV2vHighwayLosNlosvChCondModelTestCase::EvaluateChannelCondition(), ThreeGppChannelConditionModelTestCase::EvaluateChannelCondition(), V2vUrbanProbChCondModelTestCase::EvaluateChannelCondition(), and V2vHighwayProbChCondModelTestCase::EvaluateChannelCondition().
GetKey()
uint32_t ns3::ThreeGppChannelConditionModel::GetKey (Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) static private
Returns a unique and reciprocal key for the channel between a and b.
Parameters
a tx mobility model
b rx mobility model
Returns
channel key
Definition at line 424 of file channel-condition-model.cc.
References ns3::Node::GetId(), max, and min.
Referenced by GetChannelCondition().
GetTypeId()
TypeId ns3::ThreeGppChannelConditionModel::GetTypeId (void) static
Get the type ID.
Get the type ID.
Returns
the object TypeId
Definition at line 283 of file channel-condition-model.cc.
References m_updatePeriod, ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MilliSeconds(), and ns3::TypeId::SetParent().
Member Data Documentation
m_channelConditionMap
std::unordered_map<uint32_t, Item> ns3::ThreeGppChannelConditionModel::m_channelConditionMap private
map to store the channel conditions
Definition at line 560 of file channel-condition-model.h.
Referenced by DoDispose(), and GetChannelCondition().
m_uniformVar
Ptr<UniformRandomVariable> ns3::ThreeGppChannelConditionModel::m_uniformVar protected
uniform random variable
Definition at line 512 of file channel-condition-model.h.
Referenced by ThreeGppChannelConditionModel(), AssignStreams(), and ComputeChannelCondition().
m_updatePeriod
Time ns3::ThreeGppChannelConditionModel::m_updatePeriod private
the update period for the channel condition
Definition at line 561 of file channel-condition-model.h.
Referenced by DoDispose(), GetChannelCondition(), and GetTypeId().
The documentation for this class was generated from the following files:
src/propagation/model/channel-condition-model.h
src/propagation/model/channel-condition-model.cc