ns-3: anonymous_namespace{sample-simulator.cc}::MyModel Class Reference
anonymous_namespace{sample-simulator.cc}::MyModel Class Reference
Simple model object to illustrate event handling.
Public Member Functions
void Start (void)
Start model execution by scheduling a HandleEvent.
Private Member Functions
void HandleEvent (double eventValue)
Simple event handler.
Detailed Description
Simple model object to illustrate event handling.
Definition at line 40 of file sample-simulator.cc.
Member Function Documentation
HandleEvent()
void anonymous_namespace{sample-simulator.cc}::MyModel::HandleEvent (double eventValue) private
Simple event handler.
Parameters
[in] eventValue Event argument.
Definition at line 63 of file sample-simulator.cc.
References ns3::Time::GetSeconds(), and ns3::Simulator::Now().
Referenced by sample-simulator.MyModel::Start().
Start()
void anonymous_namespace{sample-simulator.cc}::MyModel::Start (void)
Start model execution by scheduling a HandleEvent.
Definition at line 56 of file sample-simulator.cc.
References ns3::Simulator::Now(), ns3::Simulator::Schedule(), and ns3::Seconds().
Referenced by anonymous_namespace{sample-simulator.cc}::ExampleFunction().
The documentation for this class was generated from the following file:
src/core/examples/sample-simulator.cc