ns-3: ns3::SsServiceFlowManager Class Reference
ns3::SsServiceFlowManager Class Reference
WiMAX Models
SsServiceFlowManager class.
#include "ss-service-flow-manager.h"
Public Types
enum ConfirmationCode { CONFIRMATION_CODE_SUCCESS , CONFIRMATION_CODE_REJECT }
Confirmation code enumeration.
Public Types inherited from ns3::ServiceFlowManager
enum ConfirmationCode { CONFIRMATION_CODE_SUCCESS , CONFIRMATION_CODE_REJECT }
confirmation code enumeration as per Table 384 (not all codes implemented)
Public Member Functions
SsServiceFlowManager (Ptr< SubscriberStationNetDevice > device)
creates a service flow manager and attaches it to a device
~SsServiceFlowManager (void)
void AddServiceFlow (ServiceFlow *serviceFlow)
add a service flow to the list
void AddServiceFlow (ServiceFlow serviceFlow)
add a service flow to the list
Ptr< Packet > CreateDsaAck (void)
Create DSA ack.
DsaReq CreateDsaReq (const ServiceFlow *serviceFlow)
Create DSA request.
void DoDispose (void)
Destructor implementation.
EventId GetDsaAckTimeoutEvent (void) const
Get DSA ack timeout event.
EventId GetDsaRspTimeoutEvent (void) const
Get DSA response timeout event.
uint8_t GetMaxDsaReqRetries (void) const
void InitiateServiceFlows (void)
Initiate service flows.
void ProcessDsaRsp (const DsaRsp &dsaRsp)
Process DSA response.
void ScheduleDsaReq (const ServiceFlow *serviceFlow)
Schedule DSA response.
void SetMaxDsaReqRetries (uint8_t maxDsaReqRetries)
sets the maximum retries on DSA request message
Public Member Functions inherited from ns3::ServiceFlowManager
ServiceFlowManager ()
~ServiceFlowManager (void)
void AddServiceFlow (ServiceFlow *serviceFlow)
Add service flow function.
bool AreServiceFlowsAllocated ()
bool AreServiceFlowsAllocated (std::vector< ServiceFlow * > *serviceFlows)
bool AreServiceFlowsAllocated (std::vector< ServiceFlow * > serviceFlows)
ServiceFlow * DoClassify (Ipv4Address SrcAddress, Ipv4Address DstAddress, uint16_t SrcPort, uint16_t DstPort, uint8_t Proto, ServiceFlow::Direction dir) const
ServiceFlow * GetNextServiceFlowToAllocate ()
uint32_t GetNrServiceFlows (void) const
ServiceFlow * GetServiceFlow (Cid cid) const
Get service flow by CID.
ServiceFlow * GetServiceFlow (uint32_t sfid) const
Get service flow by flow id.
std::vector< ServiceFlow * > GetServiceFlows (enum ServiceFlow::SchedulingType schedulingType) const
Get service flows function.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ServiceFlowManager
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint16_t m_currentTransactionId
current transaction ID
Ptr< SubscriberStationNetDevice > m_device
the device
DsaAck m_dsaAck
DSA ack.
EventId m_dsaAckTimeoutEvent
DSA ack timeout event.
DsaReq m_dsaReq
DSA request.
uint8_t m_dsaReqRetries
DSA request retries.
EventId m_dsaRspTimeoutEvent
DSA response timeout event.
uint8_t m_maxDsaReqRetries
maximum DSA request retries
ServiceFlow * m_pendingServiceFlow
pending service flow
uint16_t m_transactionIdIndex
transaction ID index
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
SsServiceFlowManager class.
Definition at line 43 of file ss-service-flow-manager.h.
Member Enumeration Documentation
ConfirmationCode
enum ns3::SsServiceFlowManager::ConfirmationCode
Confirmation code enumeration.
Enumerator
CONFIRMATION_CODE_SUCCESS
CONFIRMATION_CODE_REJECT
Definition at line 47 of file ss-service-flow-manager.h.
Constructor & Destructor Documentation
SsServiceFlowManager()
ns3::SsServiceFlowManager::SsServiceFlowManager (Ptr< SubscriberStationNetDevice > device)
creates a service flow manager and attaches it to a device
Parameters
device the device to which the service flow manager will be attached Constructor
device subscriber station device
Definition at line 46 of file ss-service-flow-manager.cc.
~SsServiceFlowManager()
ns3::SsServiceFlowManager::~SsServiceFlowManager (void)
Definition at line 58 of file ss-service-flow-manager.cc.
Member Function Documentation
AddServiceFlow() [1/2]
void ns3::SsServiceFlowManager::AddServiceFlow (ServiceFlow * serviceFlow)
add a service flow to the list
Parameters
serviceFlow the service flow to add
Definition at line 113 of file ss-service-flow-manager.cc.
References ns3::ServiceFlowManager::AddServiceFlow().
AddServiceFlow() [2/2]
void ns3::SsServiceFlowManager::AddServiceFlow (ServiceFlow serviceFlow)
add a service flow to the list
Parameters
serviceFlow the service flow to add
Definition at line 105 of file ss-service-flow-manager.cc.
References ns3::ServiceFlowManager::AddServiceFlow(), and ns3::ServiceFlow::CopyParametersFrom().
CreateDsaAck()
Ptr< Packet > ns3::SsServiceFlowManager::CreateDsaAck (void)
Create DSA ack.
Returns
the packet
Definition at line 143 of file ss-service-flow-manager.cc.
References ns3::Packet::AddHeader(), CONFIRMATION_CODE_SUCCESS, ns3::DsaReq::GetTransactionId(), m_dsaAck, m_dsaReq, ns3::ManagementMessageType::MESSAGE_TYPE_DSA_ACK, ns3::DsaAck::SetConfirmationCode(), and ns3::DsaAck::SetTransactionId().
Referenced by ProcessDsaRsp().
CreateDsaReq()
DsaReq ns3::SsServiceFlowManager::CreateDsaReq (const ServiceFlow * serviceFlow)
Create DSA request.
Parameters
serviceFlow the service flow
Returns
the DSA request
Definition at line 129 of file ss-service-flow-manager.cc.
References m_currentTransactionId, m_transactionIdIndex, ns3::DsaReq::SetServiceFlow(), and ns3::DsaReq::SetTransactionId().
Referenced by ScheduleDsaReq().
DoDispose()
void ns3::SsServiceFlowManager::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::ServiceFlowManager.
Definition at line 75 of file ss-service-flow-manager.cc.
References ns3::ServiceFlowManager::DoDispose().
GetDsaAckTimeoutEvent()
EventId ns3::SsServiceFlowManager::GetDsaAckTimeoutEvent (void) const
Get DSA ack timeout event.
Returns
the DSA ack timeput event
Definition at line 99 of file ss-service-flow-manager.cc.
References m_dsaAckTimeoutEvent.
GetDsaRspTimeoutEvent()
EventId ns3::SsServiceFlowManager::GetDsaRspTimeoutEvent (void) const
Get DSA response timeout event.
Returns
the DSA response timeout event
Definition at line 93 of file ss-service-flow-manager.cc.
References m_dsaRspTimeoutEvent.
GetMaxDsaReqRetries()
uint8_t ns3::SsServiceFlowManager::GetMaxDsaReqRetries (void) const
Returns
the maximum retries on DSA request message
Definition at line 87 of file ss-service-flow-manager.cc.
References m_maxDsaReqRetries.
GetTypeId()
TypeId ns3::SsServiceFlowManager::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 64 of file ss-service-flow-manager.cc.
References ns3::TypeId::SetParent().
InitiateServiceFlows()
void ns3::SsServiceFlowManager::InitiateServiceFlows (void)
Initiate service flows.
Definition at line 120 of file ss-service-flow-manager.cc.
References ns3::ServiceFlowManager::GetNextServiceFlowToAllocate(), m_pendingServiceFlow, NS_ASSERT_MSG, and ScheduleDsaReq().
ProcessDsaRsp()
void ns3::SsServiceFlowManager::ProcessDsaRsp (const DsaRsp & dsaRsp)
Process DSA response.
Parameters
dsaRsp the DSA response
Definition at line 198 of file ss-service-flow-manager.cc.
References CreateDsaAck(), ns3::ServiceFlow::GetCid(), ns3::ServiceFlowManager::GetNextServiceFlowToAllocate(), ns3::DsaRsp::GetServiceFlow(), ns3::DsaRsp::GetTransactionId(), m_currentTransactionId, m_device, m_dsaReqRetries, m_pendingServiceFlow, ScheduleDsaReq(), ns3::ServiceFlow::SetConnection(), ns3::ServiceFlow::SetIsEnabled(), ns3::ServiceFlow::SetUnsolicitedGrantInterval(), ns3::ServiceFlow::SetUnsolicitedPollingInterval(), and ns3::Cid::TRANSPORT.
ScheduleDsaReq()
void ns3::SsServiceFlowManager::ScheduleDsaReq (const ServiceFlow * serviceFlow)
Schedule DSA response.
Parameters
serviceFlow the service flow
Definition at line 156 of file ss-service-flow-manager.cc.
References ns3::Packet::AddHeader(), ns3::Simulator::Cancel(), CreateDsaReq(), ns3::EventId::IsRunning(), m_device, m_dsaReq, m_dsaReqRetries, m_dsaRspTimeoutEvent, m_maxDsaReqRetries, ns3::ManagementMessageType::MESSAGE_TYPE_DSA_REQ, NS_LOG_DEBUG, and ns3::Simulator::Schedule().
Referenced by InitiateServiceFlows(), and ProcessDsaRsp().
SetMaxDsaReqRetries()
void ns3::SsServiceFlowManager::SetMaxDsaReqRetries (uint8_t maxDsaReqRetries)
sets the maximum retries on DSA request message
Parameters
maxDsaReqRetries the maximum retries on DSA request message
Definition at line 81 of file ss-service-flow-manager.cc.
References m_maxDsaReqRetries.
Member Data Documentation
m_currentTransactionId
uint16_t ns3::SsServiceFlowManager::m_currentTransactionId private
current transaction ID
Definition at line 142 of file ss-service-flow-manager.h.
Referenced by CreateDsaReq(), and ProcessDsaRsp().
m_device
Ptr<SubscriberStationNetDevice> ns3::SsServiceFlowManager::m_device private
the device
Definition at line 132 of file ss-service-flow-manager.h.
Referenced by ProcessDsaRsp(), and ScheduleDsaReq().
m_dsaAck
DsaAck ns3::SsServiceFlowManager::m_dsaAck private
DSA ack.
Definition at line 140 of file ss-service-flow-manager.h.
Referenced by CreateDsaAck().
m_dsaAckTimeoutEvent
EventId ns3::SsServiceFlowManager::m_dsaAckTimeoutEvent private
DSA ack timeout event.
Definition at line 137 of file ss-service-flow-manager.h.
Referenced by GetDsaAckTimeoutEvent().
m_dsaReq
DsaReq ns3::SsServiceFlowManager::m_dsaReq private
DSA request.
Definition at line 139 of file ss-service-flow-manager.h.
Referenced by CreateDsaAck(), and ScheduleDsaReq().
m_dsaReqRetries
uint8_t ns3::SsServiceFlowManager::m_dsaReqRetries private
DSA request retries.
Definition at line 144 of file ss-service-flow-manager.h.
Referenced by ProcessDsaRsp(), and ScheduleDsaReq().
m_dsaRspTimeoutEvent
EventId ns3::SsServiceFlowManager::m_dsaRspTimeoutEvent private
DSA response timeout event.
Definition at line 136 of file ss-service-flow-manager.h.
Referenced by GetDsaRspTimeoutEvent(), and ScheduleDsaReq().
m_maxDsaReqRetries
uint8_t ns3::SsServiceFlowManager::m_maxDsaReqRetries private
maximum DSA request retries
Definition at line 134 of file ss-service-flow-manager.h.
Referenced by GetMaxDsaReqRetries(), ScheduleDsaReq(), and SetMaxDsaReqRetries().
m_pendingServiceFlow
ServiceFlow* ns3::SsServiceFlowManager::m_pendingServiceFlow private
pending service flow
Definition at line 147 of file ss-service-flow-manager.h.
Referenced by InitiateServiceFlows(), and ProcessDsaRsp().
m_transactionIdIndex
uint16_t ns3::SsServiceFlowManager::m_transactionIdIndex private
transaction ID index
Definition at line 143 of file ss-service-flow-manager.h.
Referenced by CreateDsaReq().
The documentation for this class was generated from the following files:
src/wimax/model/ss-service-flow-manager.h
src/wimax/model/ss-service-flow-manager.cc