ns-3: ns3::LteEnbRrcProtocolReal Class Reference
ns3::LteEnbRrcProtocolReal Class Reference
Models the transmission of RRC messages from the UE to the eNB in a real fashion, by creating real RRC PDUs and transmitting them over Signaling Radio Bearers using radio resources allocated by the LTE MAC scheduler.
#include "lte-rrc-protocol-real.h"
Public Member Functions
LteEnbRrcProtocolReal ()
virtual ~LteEnbRrcProtocolReal ()
virtual void DoDispose (void)
Destructor implementation.
LteEnbRrcSapUser * GetLteEnbRrcSapUser ()
Get LTE ENB RRC SAP user function.
LteUeRrcSapProvider * GetUeRrcSapProvider (uint16_t rnti)
Get UE RRC SAP provider function.
void SetCellId (uint16_t cellId)
Set cell ID function.
void SetLteEnbRrcSapProvider (LteEnbRrcSapProvider *p)
Set LTE ENB RRC SAP provider function.
void SetUeRrcSapProvider (uint16_t rnti, LteUeRrcSapProvider *p)
Set UE RRC SAP provider function.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
LteRrcSap::RrcConnectionReconfiguration DoDecodeHandoverCommand (Ptr< Packet > p)
Decode handover command function.
LteRrcSap::HandoverPreparationInfo DoDecodeHandoverPreparationInformation (Ptr< Packet > p)
Decode handover preparation information function.
Ptr< Packet > DoEncodeHandoverCommand (LteRrcSap::RrcConnectionReconfiguration msg)
Encode handover command function.
Ptr< Packet > DoEncodeHandoverPreparationInformation (LteRrcSap::HandoverPreparationInfo msg)
Encode handover preparation information function.
void DoReceivePdcpPdu (uint16_t rnti, Ptr< Packet > p)
Receive PDCP PDU function.
void DoReceivePdcpSdu (LtePdcpSapUser::ReceivePdcpSduParameters params)
Receive PDCP SDU function.
void DoRemoveUe (uint16_t rnti)
Remove UE function.
void DoSendRrcConnectionReconfiguration (uint16_t rnti, LteRrcSap::RrcConnectionReconfiguration msg)
Send RRC connection reconfiguration function.
void DoSendRrcConnectionReestablishment (uint16_t rnti, LteRrcSap::RrcConnectionReestablishment msg)
Send RRC connection reestabishment function.
void DoSendRrcConnectionReestablishmentReject (uint16_t rnti, LteRrcSap::RrcConnectionReestablishmentReject msg)
Send RRC connection reestabishment reject function.
void DoSendRrcConnectionReject (uint16_t rnti, LteRrcSap::RrcConnectionReject msg)
Send RRC connection reject function.
void DoSendRrcConnectionRelease (uint16_t rnti, LteRrcSap::RrcConnectionRelease msg)
Send RRC connection release function.
void DoSendRrcConnectionSetup (uint16_t rnti, LteRrcSap::RrcConnectionSetup msg)
Send RRC connection setup function.
void DoSendSystemInformation (uint16_t cellId, LteRrcSap::SystemInformation msg)
Send system information function.
void DoSetupUe (uint16_t rnti, LteEnbRrcSapUser::SetupUeParameters params)
Setup UE function.
void SendSystemInformation (uint16_t cellId, LteRrcSap::SystemInformation msg)
Send system information function.
Private Attributes
uint16_t m_cellId
the cell ID
std::map< uint16_t, LteEnbRrcSapProvider::CompleteSetupUeParameters > m_completeSetupUeParametersMap
complete setup UE parameters map
LteEnbRrcSapProvider * m_enbRrcSapProvider
ENB RRC SAP provider.
std::map< uint16_t, LteUeRrcSapProvider * > m_enbRrcSapProviderMap
ENB RRC SAP provider map.
LteEnbRrcSapUser * m_enbRrcSapUser
ENB RRC SAP user.
uint16_t m_rnti
the RNTI
std::map< uint16_t, LteEnbRrcSapUser::SetupUeParameters > m_setupUeParametersMap
setup UE parameters map
Friends
class LtePdcpSpecificLtePdcpSapUser< LteEnbRrcProtocolReal >
allow LtePdcpSpecificLtePdcpSapUser<LteEnbRrcProtocolReal> class friend access
class LteRlcSpecificLteRlcSapUser< LteEnbRrcProtocolReal >
allow LteRlcSpecificLteRlcSapUser<LteEnbRrcProtocolReal> class friend access
class MemberLteEnbRrcSapUser< LteEnbRrcProtocolReal >
allow MemberLteEnbRrcSapUser<LteEnbRrcProtocolReal> class friend access
class RealProtocolRlcSapUser
allow RealProtocolRlcSapUser class friend access
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Models the transmission of RRC messages from the UE to the eNB in a real fashion, by creating real RRC PDUs and transmitting them over Signaling Radio Bearers using radio resources allocated by the LTE MAC scheduler.
Introspection did not find any typical Config paths.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 120 bytes (on a 64-bit architecture).
Definition at line 184 of file lte-rrc-protocol-real.h.
Constructor & Destructor Documentation
LteEnbRrcProtocolReal()
ns3::LteEnbRrcProtocolReal::LteEnbRrcProtocolReal ()
Definition at line 380 of file lte-rrc-protocol-real.cc.
References m_enbRrcSapUser, MemberLteEnbRrcSapUser< LteEnbRrcProtocolReal >, and NS_LOG_FUNCTION.
~LteEnbRrcProtocolReal()
ns3::LteEnbRrcProtocolReal::~LteEnbRrcProtocolReal () virtual
Definition at line 387 of file lte-rrc-protocol-real.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDecodeHandoverCommand()
LteRrcSap::RrcConnectionReconfiguration ns3::LteEnbRrcProtocolReal::DoDecodeHandoverCommand (Ptr< Packet > p) private
Decode handover command function.
Parameters
p the packet
Returns
LteRrcSap::RrcConnectionReconfiguration
Definition at line 777 of file lte-rrc-protocol-real.cc.
References ns3::RrcConnectionReconfigurationHeader::GetMessage(), and ns3::Packet::RemoveHeader().
DoDecodeHandoverPreparationInformation()
LteRrcSap::HandoverPreparationInfo ns3::LteEnbRrcProtocolReal::DoDecodeHandoverPreparationInformation (Ptr< Packet > p) private
Decode handover preparation information function.
Parameters
p the packet
Returns
LteRrcSap::HandoverPreparationInfo
Definition at line 758 of file lte-rrc-protocol-real.cc.
References ns3::HandoverPreparationInfoHeader::GetMessage(), and ns3::Packet::RemoveHeader().
DoDispose()
void ns3::LteEnbRrcProtocolReal::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 393 of file lte-rrc-protocol-real.cc.
References m_completeSetupUeParametersMap, m_enbRrcSapUser, and NS_LOG_FUNCTION.
DoEncodeHandoverCommand()
Ptr< Packet > ns3::LteEnbRrcProtocolReal::DoEncodeHandoverCommand (LteRrcSap::RrcConnectionReconfiguration msg) private
Encode handover command function.
Parameters
msg LteRrcSap::RrcConnectionReconfiguration
Returns
the packet
Definition at line 767 of file lte-rrc-protocol-real.cc.
References ns3::Packet::AddHeader(), and ns3::RrcConnectionReconfigurationHeader::SetMessage().
DoEncodeHandoverPreparationInformation()
Ptr< Packet > ns3::LteEnbRrcProtocolReal::DoEncodeHandoverPreparationInformation (LteRrcSap::HandoverPreparationInfo msg) private
Encode handover preparation information function.
Parameters
msg LteRrcSap::HandoverPreparationInfo
Returns
the packet
Definition at line 747 of file lte-rrc-protocol-real.cc.
References ns3::Packet::AddHeader(), and ns3::HandoverPreparationInfoHeader::SetMessage().
DoReceivePdcpPdu()
void ns3::LteEnbRrcProtocolReal::DoReceivePdcpPdu (uint16_t rnti, Ptr< Packet > p) private
Receive PDCP PDU function.
Parameters
rnti the RNTI
p the packet
Definition at line 673 of file lte-rrc-protocol-real.cc.
References ns3::RrcConnectionRequestHeader::GetMessage(), ns3::RrcConnectionReestablishmentRequestHeader::GetMessage(), ns3::RrcAsn1Header::GetMessageType(), m_enbRrcSapProvider, ns3::Packet::PeekHeader(), ns3::LteEnbRrcSapProvider::RecvRrcConnectionReestablishmentRequest(), ns3::LteEnbRrcSapProvider::RecvRrcConnectionRequest(), and ns3::Packet::RemoveHeader().
Referenced by ns3::RealProtocolRlcSapUser::ReceivePdcpPdu().
DoReceivePdcpSdu()
void ns3::LteEnbRrcProtocolReal::DoReceivePdcpSdu (LtePdcpSapUser::ReceivePdcpSduParameters params) private
Receive PDCP SDU function.
Parameters
params LtePdcpSapUser::ReceivePdcpSduParameters
Definition at line 702 of file lte-rrc-protocol-real.cc.
References ns3::RrcConnectionSetupCompleteHeader::GetMessage(), ns3::RrcConnectionReconfigurationCompleteHeader::GetMessage(), ns3::RrcConnectionReestablishmentCompleteHeader::GetMessage(), ns3::MeasurementReportHeader::GetMessage(), ns3::RrcAsn1Header::GetMessageType(), m_enbRrcSapProvider, ns3::LtePdcpSapUser::ReceivePdcpSduParameters::pdcpSdu, ns3::Packet::PeekHeader(), ns3::LteEnbRrcSapProvider::RecvMeasurementReport(), ns3::LteEnbRrcSapProvider::RecvRrcConnectionReconfigurationCompleted(), ns3::LteEnbRrcSapProvider::RecvRrcConnectionReestablishmentComplete(), ns3::LteEnbRrcSapProvider::RecvRrcConnectionSetupCompleted(), ns3::Packet::RemoveHeader(), and ns3::LtePdcpSapUser::ReceivePdcpSduParameters::rnti.
DoRemoveUe()
void ns3::LteEnbRrcProtocolReal::DoRemoveUe (uint16_t rnti) private
Remove UE function.
Parameters
rnti the RNTI
Definition at line 519 of file lte-rrc-protocol-real.cc.
References m_completeSetupUeParametersMap, m_enbRrcSapProviderMap, m_setupUeParametersMap, NS_ASSERT, and NS_LOG_FUNCTION.
DoSendRrcConnectionReconfiguration()
void ns3::LteEnbRrcProtocolReal::DoSendRrcConnectionReconfiguration (uint16_t rnti, LteRrcSap::RrcConnectionReconfiguration msg) private
Send RRC connection reconfiguration function.
Parameters
rnti the RNTI
msg LteRrcSap::RrcConnectionReconfiguration
Definition at line 601 of file lte-rrc-protocol-real.cc.
References ns3::Packet::AddHeader(), ns3::LtePdcpSapProvider::TransmitPdcpSduParameters::lcid, m_setupUeParametersMap, ns3::LtePdcpSapProvider::TransmitPdcpSduParameters::pdcpSdu, ns3::LtePdcpSapProvider::TransmitPdcpSduParameters::rnti, and ns3::RrcConnectionReconfigurationHeader::SetMessage().
DoSendRrcConnectionReestablishment()
void ns3::LteEnbRrcProtocolReal::DoSendRrcConnectionReestablishment (uint16_t rnti, LteRrcSap::RrcConnectionReestablishment msg) private
Send RRC connection reestabishment function.
Parameters
rnti the RNTI
msg LteRrcSap::RrcConnectionReestablishment
Definition at line 619 of file lte-rrc-protocol-real.cc.
References ns3::Packet::AddHeader(), ns3::LteRlcSapProvider::TransmitPdcpPduParameters::lcid, m_setupUeParametersMap, ns3::LteRlcSapProvider::TransmitPdcpPduParameters::pdcpPdu, ns3::LteRlcSapProvider::TransmitPdcpPduParameters::rnti, and ns3::RrcConnectionReestablishmentHeader::SetMessage().
DoSendRrcConnectionReestablishmentReject()
void ns3::LteEnbRrcProtocolReal::DoSendRrcConnectionReestablishmentReject (uint16_t rnti, LteRrcSap::RrcConnectionReestablishmentReject msg) private
Send RRC connection reestabishment reject function.
Parameters
rnti the RNTI
msg LteRrcSap::RrcConnectionReestablishmentReject
Definition at line 637 of file lte-rrc-protocol-real.cc.
References ns3::Packet::AddHeader(), ns3::LteRlcSapProvider::TransmitPdcpPduParameters::lcid, m_setupUeParametersMap, ns3::LteRlcSapProvider::TransmitPdcpPduParameters::pdcpPdu, ns3::LteRlcSapProvider::TransmitPdcpPduParameters::rnti, and ns3::RrcConnectionReestablishmentRejectHeader::SetMessage().
DoSendRrcConnectionReject()
void ns3::LteEnbRrcProtocolReal::DoSendRrcConnectionReject (uint16_t rnti, LteRrcSap::RrcConnectionReject msg) private
Send RRC connection reject function.
Parameters
rnti the RNTI
msg LteRrcSap::RrcConnectionReject
Definition at line 583 of file lte-rrc-protocol-real.cc.
References ns3::Packet::AddHeader(), ns3::LteRlcSapProvider::TransmitPdcpPduParameters::lcid, m_setupUeParametersMap, ns3::LteRlcSapProvider::TransmitPdcpPduParameters::pdcpPdu, ns3::LteRlcSapProvider::TransmitPdcpPduParameters::rnti, and ns3::RrcConnectionRejectHeader::SetMessage().
DoSendRrcConnectionRelease()
void ns3::LteEnbRrcProtocolReal::DoSendRrcConnectionRelease (uint16_t rnti, LteRrcSap::RrcConnectionRelease msg) private
Send RRC connection release function.
Parameters
rnti the RNTI
msg LteRrcSap::RrcConnectionRelease
Definition at line 655 of file lte-rrc-protocol-real.cc.
References ns3::Packet::AddHeader(), ns3::LtePdcpSapProvider::TransmitPdcpSduParameters::lcid, m_setupUeParametersMap, ns3::LtePdcpSapProvider::TransmitPdcpSduParameters::pdcpSdu, ns3::LtePdcpSapProvider::TransmitPdcpSduParameters::rnti, and ns3::RrcConnectionReleaseHeader::SetMessage().
DoSendRrcConnectionSetup()
void ns3::LteEnbRrcProtocolReal::DoSendRrcConnectionSetup (uint16_t rnti, LteRrcSap::RrcConnectionSetup msg) private
Send RRC connection setup function.
Parameters
rnti the RNTI
msg LteRrcSap::RrcConnectionSetup
Definition at line 565 of file lte-rrc-protocol-real.cc.
References ns3::Packet::AddHeader(), ns3::LteRlcSapProvider::TransmitPdcpPduParameters::lcid, m_setupUeParametersMap, ns3::LteRlcSapProvider::TransmitPdcpPduParameters::pdcpPdu, ns3::LteRlcSapProvider::TransmitPdcpPduParameters::rnti, and ns3::RrcConnectionSetupHeader::SetMessage().
DoSendSystemInformation()
void ns3::LteEnbRrcProtocolReal::DoSendSystemInformation (uint16_t cellId, LteRrcSap::SystemInformation msg) private
Send system information function.
Parameters
cellId cell ID
msg LteRrcSap::SystemInformation
Definition at line 533 of file lte-rrc-protocol-real.cc.
References ns3::NodeList::Begin(), ns3::NodeList::End(), ns3::Node::GetDevice(), ns3::Node::GetId(), ns3::Node::GetNDevices(), NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::LteUeRrcSapProvider::RecvSystemInformation(), ns3::RRC_REAL_MSG_DELAY, and ns3::Simulator::ScheduleWithContext().
DoSetupUe()
void ns3::LteEnbRrcProtocolReal::DoSetupUe (uint16_t rnti, LteEnbRrcSapUser::SetupUeParameters params) private
Setup UE function.
Parameters
rnti the RNTI
params LteEnbRrcSapUser::SetupUeParameters
Definition at line 457 of file lte-rrc-protocol-real.cc.
References ns3::LteEnbRrcSapProvider::CompleteSetupUe(), LtePdcpSpecificLtePdcpSapUser< LteEnbRrcProtocolReal >, m_completeSetupUeParametersMap, m_enbRrcSapProvider, m_enbRrcSapProviderMap, m_setupUeParametersMap, NS_LOG_FUNCTION, RealProtocolRlcSapUser, ns3::LteEnbRrcSapProvider::CompleteSetupUeParameters::srb0SapUser, and ns3::LteEnbRrcSapProvider::CompleteSetupUeParameters::srb1SapUser.
GetLteEnbRrcSapUser()
LteEnbRrcSapUser * ns3::LteEnbRrcProtocolReal::GetLteEnbRrcSapUser ()
Get LTE ENB RRC SAP user function.
Returns
LteEnbRrcSapUser *
Definition at line 426 of file lte-rrc-protocol-real.cc.
References m_enbRrcSapUser.
GetTypeId()
TypeId ns3::LteEnbRrcProtocolReal::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 409 of file lte-rrc-protocol-real.cc.
References ns3::TypeId::SetParent().
GetUeRrcSapProvider()
LteUeRrcSapProvider * ns3::LteEnbRrcProtocolReal::GetUeRrcSapProvider (uint16_t rnti)
Get UE RRC SAP provider function.
Parameters
rnti the RNTI
Returns
LteUeRrcSapProvider *
Definition at line 438 of file lte-rrc-protocol-real.cc.
References m_enbRrcSapProviderMap, and NS_ASSERT_MSG.
SendSystemInformation()
void ns3::LteEnbRrcProtocolReal::SendSystemInformation (uint16_t cellId, LteRrcSap::SystemInformation msg) private
Send system information function.
Parameters
cellId cell ID
msg LteRrcSap::SystemInformation
SetCellId()
void ns3::LteEnbRrcProtocolReal::SetCellId (uint16_t cellId)
Set cell ID function.
Parameters
cellId the cell ID
Definition at line 432 of file lte-rrc-protocol-real.cc.
References m_cellId.
SetLteEnbRrcSapProvider()
void ns3::LteEnbRrcProtocolReal::SetLteEnbRrcSapProvider (LteEnbRrcSapProvider * p)
Set LTE ENB RRC SAP provider function.
Parameters
p LteEnbRrcSapProvider *
Definition at line 420 of file lte-rrc-protocol-real.cc.
References m_enbRrcSapProvider.
SetUeRrcSapProvider()
void ns3::LteEnbRrcProtocolReal::SetUeRrcSapProvider (uint16_t rnti, LteUeRrcSapProvider * p)
Set UE RRC SAP provider function.
Parameters
rnti the RNTI
p LteUeRrcSapProvider *
Definition at line 447 of file lte-rrc-protocol-real.cc.
References m_cellId, m_enbRrcSapProviderMap, and NS_ASSERT_MSG.
Friends And Related Function Documentation
LtePdcpSpecificLtePdcpSapUser< LteEnbRrcProtocolReal >
friend class LtePdcpSpecificLtePdcpSapUser< LteEnbRrcProtocolReal > friend
allow LtePdcpSpecificLtePdcpSapUser<LteEnbRrcProtocolReal> class friend access
Definition at line 172 of file lte-rrc-protocol-real.h.
Referenced by DoSetupUe().
LteRlcSpecificLteRlcSapUser< LteEnbRrcProtocolReal >
friend class LteRlcSpecificLteRlcSapUser< LteEnbRrcProtocolReal > friend
allow LteRlcSpecificLteRlcSapUser<LteEnbRrcProtocolReal> class friend access
Definition at line 172 of file lte-rrc-protocol-real.h.
MemberLteEnbRrcSapUser< LteEnbRrcProtocolReal >
friend class MemberLteEnbRrcSapUser< LteEnbRrcProtocolReal > friend
allow MemberLteEnbRrcSapUser<LteEnbRrcProtocolReal> class friend access
Definition at line 172 of file lte-rrc-protocol-real.h.
Referenced by LteEnbRrcProtocolReal().
RealProtocolRlcSapUser
friend class RealProtocolRlcSapUser friend
allow RealProtocolRlcSapUser class friend access
Definition at line 193 of file lte-rrc-protocol-real.h.
Referenced by DoSetupUe().
Member Data Documentation
m_cellId
uint16_t ns3::LteEnbRrcProtocolReal::m_cellId private
the cell ID
Definition at line 357 of file lte-rrc-protocol-real.h.
Referenced by SetCellId(), and SetUeRrcSapProvider().
m_completeSetupUeParametersMap
std::map<uint16_t, LteEnbRrcSapProvider::CompleteSetupUeParameters> ns3::LteEnbRrcProtocolReal::m_completeSetupUeParametersMap private
complete setup UE parameters map
Definition at line 362 of file lte-rrc-protocol-real.h.
Referenced by DoDispose(), DoRemoveUe(), and DoSetupUe().
m_enbRrcSapProvider
LteEnbRrcSapProvider* ns3::LteEnbRrcProtocolReal::m_enbRrcSapProvider private
ENB RRC SAP provider.
Definition at line 358 of file lte-rrc-protocol-real.h.
Referenced by DoReceivePdcpPdu(), DoReceivePdcpSdu(), DoSetupUe(), and SetLteEnbRrcSapProvider().
m_enbRrcSapProviderMap
std::map<uint16_t, LteUeRrcSapProvider*> ns3::LteEnbRrcProtocolReal::m_enbRrcSapProviderMap private
ENB RRC SAP provider map.
Definition at line 360 of file lte-rrc-protocol-real.h.
Referenced by DoRemoveUe(), DoSetupUe(), GetUeRrcSapProvider(), and SetUeRrcSapProvider().
m_enbRrcSapUser
LteEnbRrcSapUser* ns3::LteEnbRrcProtocolReal::m_enbRrcSapUser private
ENB RRC SAP user.
Definition at line 359 of file lte-rrc-protocol-real.h.
Referenced by LteEnbRrcProtocolReal(), DoDispose(), and GetLteEnbRrcSapUser().
m_rnti
uint16_t ns3::LteEnbRrcProtocolReal::m_rnti private
the RNTI
Definition at line 356 of file lte-rrc-protocol-real.h.
m_setupUeParametersMap
std::map<uint16_t, LteEnbRrcSapUser::SetupUeParameters> ns3::LteEnbRrcProtocolReal::m_setupUeParametersMap private
setup UE parameters map
Definition at line 361 of file lte-rrc-protocol-real.h.
Referenced by DoRemoveUe(), DoSendRrcConnectionReconfiguration(), DoSendRrcConnectionReestablishment(), DoSendRrcConnectionReestablishmentReject(), DoSendRrcConnectionReject(), DoSendRrcConnectionRelease(), DoSendRrcConnectionSetup(), and DoSetupUe().
The documentation for this class was generated from the following files:
src/lte/model/lte-rrc-protocol-real.h
src/lte/model/lte-rrc-protocol-real.cc