ns-3: ns3::ThreeGppHttpServer Class Reference
ns3::ThreeGppHttpServer Class Reference
Applications » ThreeGppHttpClientServer
Model application which simulates the traffic of a web server.
#include "three-gpp-http-server.h"
Public Types
typedef void(* ConnectionEstablishedCallback) (Ptr< const ThreeGppHttpServer > httpServer, Ptr< Socket > socket)
Callback signature for ConnectionEstablished trace source.
enum State_t { NOT_STARTED = 0 , STARTED , STOPPED }
The possible states of the application.
typedef void(* ThreeGppHttpObjectCallback) (uint32_t size)
Common callback signature for MainObject and EmbeddedObject trace sources.
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Public Member Functions
ThreeGppHttpServer ()
Creates a new instance of HTTP server application.
Ptr< Socket > GetSocket () const
Returns a pointer to the listening socket.
State_t GetState () const
Returns the current state of the application.
std::string GetStateString () const
Returns the current state of the application in string format.
void SetMtuSize (uint32_t mtuSize)
Sets the maximum transmission unit (MTU) size used by the application.
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static std::string GetStateString (State_t state)
Returns the given state in string format.
static TypeId GetTypeId ()
Returns the object TypeId.
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose ()
Destructor implementation.
virtual void StartApplication ()
Application specific startup code.
virtual void StopApplication ()
Application specific shutdown code.
Protected Member Functions inherited from ns3::Application
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
bool ConnectionRequestCallback (Ptr< Socket > socket, const Address &address)
Invoked when m_initialSocket receives a connection request.
void ErrorCloseCallback (Ptr< Socket > socket)
Invoked when a connection with a web client is terminated.
void NewConnectionCreatedCallback (Ptr< Socket > socket, const Address &address)
Invoked when a new connection has been established.
void NormalCloseCallback (Ptr< Socket > socket)
Invoked when a connection with a web client is terminated.
void ReceivedDataCallback (Ptr< Socket > socket)
Invoked when m_initialSocket receives some packet data.
void SendCallback (Ptr< Socket > socket, uint32_t availableBufferSize)
Invoked when more buffer space for transmission is added to a socket.
uint32_t ServeFromTxBuffer (Ptr< Socket > socket)
Creates a packet out of a pending object in the Tx buffer send it over the given socket.
void ServeNewEmbeddedObject (Ptr< Socket > socket)
Generates a new embedded object and push it into the Tx buffer.
void ServeNewMainObject (Ptr< Socket > socket)
Generates a new main object and push it into the Tx buffer.
void SwitchToState (State_t state)
Change the state of the server.
Private Attributes
TracedCallback< Ptr< const ThreeGppHttpServer >, Ptr< Socket > > m_connectionEstablishedTrace
The ConnectionEstablished trace source.
TracedCallback< uint32_t > m_embeddedObjectTrace
The EmbeddedObject trace source.
Ptr< ThreeGppHttpVariables > m_httpVariables
The Variables attribute.
Ptr< Socket > m_initialSocket
The listening socket, for receiving connection requests from clients.
Address m_localAddress
The LocalAddress attribute.
uint16_t m_localPort
The LocalPort attribute.
TracedCallback< uint32_t > m_mainObjectTrace
The MainObject trace source.
uint32_t m_mtuSize
The Mtu attribute.
TracedCallback< const Time &, const Address & > m_rxDelayTrace
The RxDelay trace source.
TracedCallback< Ptr< const Packet >, const Address & > m_rxTrace
The Rx trace source.
State_t m_state
The current state of the client application. Begins with NOT_STARTED.
TracedCallback< const std::string &, const std::string & > m_stateTransitionTrace
The StateTransition trace source.
Ptr< ThreeGppHttpServerTxBuffer > m_txBuffer
Pointer to the transmission buffer.
TracedCallback< Ptr< const Packet > > m_txTrace
The Tx trace source.
Additional Inherited Members
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Model application which simulates the traffic of a web server.
This application works in conjunction with ThreeGppHttpClient applications.
The application works by responding to requests. Each request is a small packet of data which contains ThreeGppHttpHeader. The value of the content type field of the header determines the type of object that the client is requesting. The possible type is either a main object or an embedded object.
The application is responsible to generate the right type of object and send it back to the client. The size of each object to be sent is randomly determined (see ThreeGppHttpVariables). Each object may be sent as multiple packets due to limited socket buffer space.
To assist with the transmission, the application maintains several instances of ThreeGppHttpServerTxBuffer. Each instance keeps track of the object type to be served and the number of bytes left to be sent.
The application accepts connection request from clients. Every connection is kept open until the client disconnects.
Config Paths
ns3::ThreeGppHttpServer is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/ApplicationList/[i]/$ns3::ThreeGppHttpServer"
Attributes
Variables: Variable collection, which is used to control e.g. processing and object generation delays.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::ThreeGppHttpVariables>
Initial value: 0x0
Flags: construct write read
LocalAddress: The local address of the server, i.e., the address on which to bind the Rx socket.
Set with class: AddressValue
Underlying type: Address
Initial value: 00-00-00
Flags: construct write read
LocalPort: Port on which the application listen for incoming packets.
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 80
Flags: construct write read
Mtu: Maximum transmission unit (in bytes) of the TCP sockets used in this application, excluding the compulsory 40 bytes TCP header. Typical values are 1460 and 536 bytes. The attribute is read-only because the value is randomly determined.
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Flags: read
Attributes defined in parent class ns3::Application
StartTime: Time at which the application will start
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
StopTime: Time at which the application will stop
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
TraceSources
ConnectionEstablished: Connection to a remote web client has been established.
Callback signature: ns3::HttpServer::ConnectionEstablishedCallback
MainObject: A main object has been generated.
Callback signature: ns3::HttpServer::HttpObjectCallback
EmbeddedObject: An embedded object has been generated.
Callback signature: ns3::HttpServer::HttpObjectCallback
Tx: A packet has been sent.
Callback signature: ns3::Packet::TracedCallback
Rx: A packet has been received.
Callback signature: ns3::Packet::PacketAddressTracedCallback
RxDelay: A packet has been received with delay information.
Callback signature: ns3::Application::DelayAddressCallback
StateTransition: Trace fired upon every HTTP client state transition.
Callback signature: ns3::Application::StateTransitionCallback
Size of this type is 336 bytes (on a 64-bit architecture).
Definition at line 69 of file three-gpp-http-server.h.
Member Typedef Documentation
ConnectionEstablishedCallback
typedef void(* ns3::ThreeGppHttpServer::ConnectionEstablishedCallback) (Ptr< const ThreeGppHttpServer > httpServer, Ptr< Socket > socket)
Callback signature for ConnectionEstablished trace source.
Parameters
httpServer Pointer to this instance of ThreeGppHttpServer, which is where the trace originated.
socket Pointer to the socket where the connection is established.
Definition at line 148 of file three-gpp-http-server.h.
ThreeGppHttpObjectCallback
typedef void(* ns3::ThreeGppHttpServer::ThreeGppHttpObjectCallback) (uint32_t size)
Common callback signature for MainObject and EmbeddedObject trace sources.
Parameters
size Size of the generated object in bytes.
Definition at line 140 of file three-gpp-http-server.h.
Member Enumeration Documentation
State_t
enum ns3::ThreeGppHttpServer::State_t
The possible states of the application.
Enumerator
NOT_STARTED
Before StartApplication() is invoked.
STARTED
Passively listening and responding to requests.
STOPPED
After StopApplication() is invoked.
Definition at line 109 of file three-gpp-http-server.h.
Constructor & Destructor Documentation
ThreeGppHttpServer()
ns3::ThreeGppHttpServer::ThreeGppHttpServer ()
Creates a new instance of HTTP server application.
After creation, the application must be further configured through attributes. To avoid having to do this process manually, please use ThreeGppHttpServerHelper.
Upon creation, the application randomly determines the MTU size that it will use (either 536 or 1460 bytes). The chosen size will be used while creating the listener socket.
Definition at line 52 of file three-gpp-http-server.cc.
References m_httpVariables, m_mtuSize, NS_LOG_FUNCTION, and NS_LOG_INFO.
Member Function Documentation
ConnectionRequestCallback()
bool ns3::ThreeGppHttpServer::ConnectionRequestCallback (Ptr< Socket > socket, const Address & address) private
Invoked when m_initialSocket receives a connection request.
Parameters
socket Pointer to the socket where the event originates from.
address The address of the remote client where the connection request comes from.
Returns
Always true, to indicate to the other end that the connection request is accepted.
Definition at line 314 of file three-gpp-http-server.cc.
References first::address, and NS_LOG_FUNCTION.
Referenced by StartApplication().
DoDispose()
void ns3::ThreeGppHttpServer::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Application.
Definition at line 186 of file three-gpp-http-server.cc.
References ns3::Application::DoDispose(), ns3::Simulator::IsFinished(), NS_LOG_FUNCTION, and StopApplication().
ErrorCloseCallback()
void ns3::ThreeGppHttpServer::ErrorCloseCallback (Ptr< Socket > socket) private
Invoked when a connection with a web client is terminated.
The corresponding socket will be removed from Tx buffer.
Parameters
socket Pointer to the socket where the event originates from.
Definition at line 392 of file three-gpp-http-server.cc.
References m_initialSocket, m_state, m_txBuffer, NS_FATAL_ERROR, NS_LOG_FUNCTION, and STARTED.
Referenced by NewConnectionCreatedCallback(), and StartApplication().
GetSocket()
Ptr< Socket > ns3::ThreeGppHttpServer::GetSocket (void) const
Returns a pointer to the listening socket.
Returns
Pointer to the listening socket
Definition at line 142 of file three-gpp-http-server.cc.
References m_initialSocket.
GetState()
ThreeGppHttpServer::State_t ns3::ThreeGppHttpServer::GetState () const
Returns the current state of the application.
Returns
The current state of the application.
Definition at line 149 of file three-gpp-http-server.cc.
References m_state.
GetStateString() [1/2]
std::string ns3::ThreeGppHttpServer::GetStateString () const
Returns the current state of the application in string format.
Returns
The current state of the application in string format.
Definition at line 156 of file three-gpp-http-server.cc.
References m_state.
Referenced by StartApplication(), and SwitchToState().
GetStateString() [2/2]
std::string ns3::ThreeGppHttpServer::GetStateString (ThreeGppHttpServer::State_t state) static
Returns the given state in string format.
Parameters
state An arbitrary state of an application.
Returns
The given state equivalently expressed in string format.
Definition at line 164 of file three-gpp-http-server.cc.
References NOT_STARTED, NS_FATAL_ERROR, STARTED, and STOPPED.
GetTypeId()
TypeId ns3::ThreeGppHttpServer::GetTypeId (void) static
Returns the object TypeId.
Returns
The object TypeId.
Definition at line 68 of file three-gpp-http-server.cc.
References ns3::TypeId::ATTR_GET, m_connectionEstablishedTrace, m_embeddedObjectTrace, m_httpVariables, m_localAddress, m_localPort, m_mainObjectTrace, m_mtuSize, m_rxDelayTrace, m_rxTrace, m_stateTransitionTrace, m_txTrace, ns3::MakeAddressAccessor(), ns3::MakeAddressChecker(), ns3::MakePointerAccessor(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
NewConnectionCreatedCallback()
void ns3::ThreeGppHttpServer::NewConnectionCreatedCallback (Ptr< Socket > socket, const Address & address) private
Invoked when a new connection has been established.
Parameters
socket Pointer to the socket that maintains the connection to the remote client. This socket will be saved to the Tx buffer.
address The address the connection is incoming from.
Definition at line 323 of file three-gpp-http-server.cc.
References first::address, ErrorCloseCallback(), m_connectionEstablishedTrace, m_txBuffer, ns3::MakeCallback(), NormalCloseCallback(), NS_LOG_FUNCTION, ReceivedDataCallback(), SendCallback(), ns3::Socket::SetCloseCallbacks(), ns3::Socket::SetRecvCallback(), and ns3::Socket::SetSendCallback().
Referenced by StartApplication().
NormalCloseCallback()
void ns3::ThreeGppHttpServer::NormalCloseCallback (Ptr< Socket > socket) private
Invoked when a connection with a web client is terminated.
The corresponding socket will be removed from Tx buffer.
Parameters
socket Pointer to the socket where the event originates from.
Definition at line 355 of file three-gpp-http-server.cc.
References m_initialSocket, m_state, m_txBuffer, NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::Socket::ShutdownSend(), and STARTED.
Referenced by NewConnectionCreatedCallback(), and StartApplication().
ReceivedDataCallback()
void ns3::ThreeGppHttpServer::ReceivedDataCallback (Ptr< Socket > socket) private
Invoked when m_initialSocket receives some packet data.
It will check the packet for ThreeGppHttpHeader. It also fires the Rx trace source.
Depending on the type of object requested, the method will trigger ServeMainObject() or ServeEmbeddedObject() after some delays.
Parameters
socket Pointer to the socket where the event originates from.
Definition at line 412 of file three-gpp-http-server.cc.
References ns3::Time::As(), ns3::Inet6SocketAddress::ConvertFrom(), ns3::InetSocketAddress::ConvertFrom(), ns3::ThreeGppHttpHeader::EMBEDDED_OBJECT, ns3::ThreeGppHttpHeader::GetClientTs(), ns3::ThreeGppHttpHeader::GetContentType(), ns3::InetSocketAddress::GetIpv4(), ns3::Inet6SocketAddress::GetIpv6(), ns3::InetSocketAddress::GetPort(), ns3::Inet6SocketAddress::GetPort(), ns3::Packet::GetSize(), ns3::Inet6SocketAddress::IsMatchingType(), ns3::InetSocketAddress::IsMatchingType(), m_httpVariables, m_rxDelayTrace, m_rxTrace, m_txBuffer, ns3::ThreeGppHttpHeader::MAIN_OBJECT, ns3::Simulator::Now(), NS_FATAL_ERROR, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::Packet::PeekHeader(), ns3::Socket::RecvFrom(), ns3::Time::S, ns3::Simulator::Schedule(), ServeNewEmbeddedObject(), and ServeNewMainObject().
Referenced by NewConnectionCreatedCallback(), and StartApplication().
SendCallback()
void ns3::ThreeGppHttpServer::SendCallback (Ptr< Socket > socket, uint32_t availableBufferSize) private
Invoked when more buffer space for transmission is added to a socket.
The method will invoke ServeFromTxBuffer() to start some transmission using the socket.
Parameters
socket Pointer to the socket where the event originates from.
availableBufferSize The number of bytes available in the socket's transmission buffer.
Definition at line 488 of file three-gpp-http-server.cc.
References ns3::ThreeGppHttpHeader::EMBEDDED_OBJECT, m_txBuffer, ns3::ThreeGppHttpHeader::MAIN_OBJECT, NS_FATAL_ERROR, NS_LOG_FUNCTION, NS_LOG_INFO, NS_UNUSED, and ServeFromTxBuffer().
Referenced by NewConnectionCreatedCallback(), and StartApplication().
ServeFromTxBuffer()
uint32_t ns3::ThreeGppHttpServer::ServeFromTxBuffer (Ptr< Socket > socket) private
Creates a packet out of a pending object in the Tx buffer send it over the given socket.
If the socket capacity is smaller than the object size, then the method only convert a part of the object into a packet.
ThreeGppHttpHeader will be attached in the beginning of each application layer packet - if a packet is split, then then the following parts will not have the header. The method fires the Tx trace source after sending the packet to the socket.
This method is invoked when a new object is generated by ServeNewMainObject() or ServeNewEmbeddedObject(). It's also invoked when the socket informs (through SendCallback()) that more buffer space for transmission has become available.
Parameters
socket Pointer to the socket which is associated with the destination client.
Returns
Size of the packet sent (in bytes).
Definition at line 593 of file three-gpp-http-server.cc.
References ns3::Packet::AddHeader(), ns3::ThreeGppHttpHeader::GetClientTs(), ns3::Socket::GetErrno(), ns3::ThreeGppHttpHeader::GetSerializedSize(), ns3::Socket::GetTxAvailable(), m_txBuffer, m_txTrace, min, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC, packetSize, ns3::Time::S, ns3::Socket::Send(), ns3::ThreeGppHttpHeader::SetClientTs(), ns3::ThreeGppHttpHeader::SetContentLength(), ns3::ThreeGppHttpHeader::SetContentType(), and ns3::ThreeGppHttpHeader::SetServerTs().
Referenced by SendCallback(), ServeNewEmbeddedObject(), and ServeNewMainObject().
ServeNewEmbeddedObject()
void ns3::ThreeGppHttpServer::ServeNewEmbeddedObject (Ptr< Socket > socket) private
Generates a new embedded object and push it into the Tx buffer.
The size of the object is randomly determined by ThreeGppHttpVariables. Fires the EmbeddedObject trace source. It then immediately triggers ServeFromTxBuffer() to send the object.
Parameters
socket Pointer to the socket which is associated with the destination client.
Definition at line 568 of file three-gpp-http-server.cc.
References ns3::ThreeGppHttpHeader::EMBEDDED_OBJECT, m_embeddedObjectTrace, m_httpVariables, m_txBuffer, NS_LOG_FUNCTION, NS_LOG_INFO, and ServeFromTxBuffer().
Referenced by ReceivedDataCallback().
ServeNewMainObject()
void ns3::ThreeGppHttpServer::ServeNewMainObject (Ptr< Socket > socket) private
Generates a new main object and push it into the Tx buffer.
The size of the object is randomly determined by ThreeGppHttpVariables. Fires the MainObject trace source. It then immediately triggers ServeFromTxBuffer() to send the object.
Parameters
socket Pointer to the socket which is associated with the destination client.
Definition at line 543 of file three-gpp-http-server.cc.
References m_httpVariables, m_mainObjectTrace, m_txBuffer, ns3::ThreeGppHttpHeader::MAIN_OBJECT, NS_LOG_FUNCTION, NS_LOG_INFO, and ServeFromTxBuffer().
Referenced by ReceivedDataCallback().
SetMtuSize()
void ns3::ThreeGppHttpServer::SetMtuSize (uint32_t mtuSize)
Sets the maximum transmission unit (MTU) size used by the application.
This overrides the MTU size which is randomly determined once the application is created. Values other than the standard 536 and 1460 bytes can be set using this method.
Parameters
mtuSize MTU size in bytes.
Definition at line 134 of file three-gpp-http-server.cc.
References m_mtuSize, and NS_LOG_FUNCTION.
StartApplication()
void ns3::ThreeGppHttpServer::StartApplication (void) protected virtual
Application specific startup code.
The StartApplication method is called at the start time specified by Start This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 200 of file three-gpp-http-server.cc.
References ns3::Socket::Bind(), ConnectionRequestCallback(), ns3::Ipv4Address::ConvertFrom(), ns3::Ipv6Address::ConvertFrom(), ns3::Socket::CreateSocket(), ErrorCloseCallback(), ns3::TypeId::GetAttribute(), ns3::TypeId::GetAttributeN(), ns3::Socket::GetErrno(), ns3::Application::GetNode(), GetStateString(), ns3::TcpSocketFactory::GetTypeId(), ns3::TcpSocket::GetTypeId(), ns3::TypeId::AttributeInformation::initialValue, ns3::Ipv4Address::IsMatchingType(), ns3::Ipv6Address::IsMatchingType(), ns3::Socket::Listen(), m_httpVariables, m_initialSocket, m_localAddress, m_localPort, m_mtuSize, m_state, ns3::MakeCallback(), ns3::TypeId::AttributeInformation::name, NewConnectionCreatedCallback(), NormalCloseCallback(), NOT_STARTED, NS_ASSERT_MSG, NS_FATAL_ERROR, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, NS_UNUSED, ReceivedDataCallback(), SendCallback(), ns3::Socket::SetAcceptCallback(), ns3::ObjectBase::SetAttribute(), ns3::Socket::SetCloseCallbacks(), ns3::Socket::SetRecvCallback(), ns3::Socket::SetSendCallback(), STARTED, and SwitchToState().
StopApplication()
void ns3::ThreeGppHttpServer::StopApplication (void) protected virtual
Application specific shutdown code.
The StopApplication method is called at the stop time specified by Stop This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 290 of file three-gpp-http-server.cc.
References ns3::Socket::Close(), m_initialSocket, m_txBuffer, ns3::MakeNullCallback(), NS_LOG_FUNCTION, ns3::Socket::SetAcceptCallback(), ns3::Socket::SetCloseCallbacks(), ns3::Socket::SetRecvCallback(), ns3::Socket::SetSendCallback(), STOPPED, and SwitchToState().
Referenced by DoDispose().
SwitchToState()
void ns3::ThreeGppHttpServer::SwitchToState (ThreeGppHttpServer::State_t state) private
Change the state of the server.
Fires the StateTransition trace source.
Parameters
state The new state.
Definition at line 675 of file three-gpp-http-server.cc.
References GetStateString(), m_state, m_stateTransitionTrace, NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by StartApplication(), and StopApplication().
Member Data Documentation
m_connectionEstablishedTrace
TracedCallback<Ptr<const ThreeGppHttpServer>, Ptr<Socket> > ns3::ThreeGppHttpServer::m_connectionEstablishedTrace private
The ConnectionEstablished trace source.
Definition at line 284 of file three-gpp-http-server.h.
Referenced by GetTypeId(), and NewConnectionCreatedCallback().
m_embeddedObjectTrace
TracedCallback<uint32_t> ns3::ThreeGppHttpServer::m_embeddedObjectTrace private
The EmbeddedObject trace source.
Definition at line 288 of file three-gpp-http-server.h.
Referenced by GetTypeId(), and ServeNewEmbeddedObject().
m_httpVariables
Ptr<ThreeGppHttpVariables> ns3::ThreeGppHttpServer::m_httpVariables private
The Variables attribute.
Definition at line 273 of file three-gpp-http-server.h.
Referenced by ThreeGppHttpServer(), GetTypeId(), ReceivedDataCallback(), ServeNewEmbeddedObject(), ServeNewMainObject(), and StartApplication().
m_initialSocket
Ptr<Socket> ns3::ThreeGppHttpServer::m_initialSocket private
The listening socket, for receiving connection requests from clients.
Definition at line 266 of file three-gpp-http-server.h.
Referenced by ErrorCloseCallback(), GetSocket(), NormalCloseCallback(), StartApplication(), and StopApplication().
m_localAddress
Address ns3::ThreeGppHttpServer::m_localAddress private
The LocalAddress attribute.
Definition at line 275 of file three-gpp-http-server.h.
Referenced by GetTypeId(), and StartApplication().
m_localPort
uint16_t ns3::ThreeGppHttpServer::m_localPort private
The LocalPort attribute.
Definition at line 277 of file three-gpp-http-server.h.
Referenced by GetTypeId(), and StartApplication().
m_mainObjectTrace
TracedCallback<uint32_t> ns3::ThreeGppHttpServer::m_mainObjectTrace private
The MainObject trace source.
Definition at line 286 of file three-gpp-http-server.h.
Referenced by GetTypeId(), and ServeNewMainObject().
m_mtuSize
uint32_t ns3::ThreeGppHttpServer::m_mtuSize private
The Mtu attribute.
Definition at line 279 of file three-gpp-http-server.h.
Referenced by ThreeGppHttpServer(), GetTypeId(), SetMtuSize(), and StartApplication().
m_rxDelayTrace
TracedCallback<const Time &, const Address &> ns3::ThreeGppHttpServer::m_rxDelayTrace private
The RxDelay trace source.
Definition at line 294 of file three-gpp-http-server.h.
Referenced by GetTypeId(), and ReceivedDataCallback().
m_rxTrace
TracedCallback<Ptr<const Packet>, const Address &> ns3::ThreeGppHttpServer::m_rxTrace private
The Rx trace source.
Definition at line 292 of file three-gpp-http-server.h.
Referenced by GetTypeId(), and ReceivedDataCallback().
m_state
State_t ns3::ThreeGppHttpServer::m_state private
The current state of the client application. Begins with NOT_STARTED.
Definition at line 264 of file three-gpp-http-server.h.
Referenced by ErrorCloseCallback(), GetState(), GetStateString(), NormalCloseCallback(), StartApplication(), and SwitchToState().
m_stateTransitionTrace
TracedCallback<const std::string &, const std::string &> ns3::ThreeGppHttpServer::m_stateTransitionTrace private
The StateTransition trace source.
Definition at line 296 of file three-gpp-http-server.h.
Referenced by GetTypeId(), and SwitchToState().
m_txBuffer
Ptr<ThreeGppHttpServerTxBuffer> ns3::ThreeGppHttpServer::m_txBuffer private
Pointer to the transmission buffer.
Definition at line 268 of file three-gpp-http-server.h.
Referenced by ErrorCloseCallback(), NewConnectionCreatedCallback(), NormalCloseCallback(), ReceivedDataCallback(), SendCallback(), ServeFromTxBuffer(), ServeNewEmbeddedObject(), ServeNewMainObject(), and StopApplication().
m_txTrace
TracedCallback<Ptr<const Packet> > ns3::ThreeGppHttpServer::m_txTrace private
The Tx trace source.
Definition at line 290 of file three-gpp-http-server.h.
Referenced by GetTypeId(), and ServeFromTxBuffer().
The documentation for this class was generated from the following files:
src/applications/model/three-gpp-http-server.h
src/applications/model/three-gpp-http-server.cc