ns-3: ns3::UeMemberLteUePhySapUser Class Reference
ns3::UeMemberLteUePhySapUser Class Reference
UeMemberLteUePhySapUser.
Public Member Functions
UeMemberLteUePhySapUser (LteUeMac *mac)
Constructor.
virtual void ReceiveLteControlMessage (Ptr< LteControlMessage > msg)
Receive SendLteControlMessage (PDCCH map, CQI feedbacks) using the ideal control channel.
virtual void ReceivePhyPdu (Ptr< Packet > p)
Receive Phy Pdu funtion.
virtual void SubframeIndication (uint32_t frameNo, uint32_t subframeNo)
Trigger the start from a new frame (input from Phy layer)
Public Member Functions inherited from ns3::LteUePhySapUser
virtual ~LteUePhySapUser ()
Private Attributes
LteUeMac * m_mac
the UE MAC
Detailed Description
UeMemberLteUePhySapUser.
Definition at line 181 of file lte-ue-mac.cc.
Constructor & Destructor Documentation
UeMemberLteUePhySapUser()
ns3::UeMemberLteUePhySapUser::UeMemberLteUePhySapUser (LteUeMac * mac)
Constructor.
Parameters
mac the UE MAC
Definition at line 200 of file lte-ue-mac.cc.
Member Function Documentation
ReceiveLteControlMessage()
void ns3::UeMemberLteUePhySapUser::ReceiveLteControlMessage (Ptr< LteControlMessage > msg) virtual
Receive SendLteControlMessage (PDCCH map, CQI feedbacks) using the ideal control channel.
Parameters
msg the Ideal Control Message to receive
Implements ns3::LteUePhySapUser.
Definition at line 219 of file lte-ue-mac.cc.
References ns3::LteUeMac::DoReceiveLteControlMessage(), and m_mac.
ReceivePhyPdu()
void ns3::UeMemberLteUePhySapUser::ReceivePhyPdu (Ptr< Packet > p) virtual
Receive Phy Pdu funtion.
It is called by the Phy to notify the MAC of the reception of a new PHY-PDU
Parameters
p
Implements ns3::LteUePhySapUser.
Definition at line 206 of file lte-ue-mac.cc.
References ns3::LteUeMac::DoReceivePhyPdu(), and m_mac.
SubframeIndication()
void ns3::UeMemberLteUePhySapUser::SubframeIndication (uint32_t frameNo, uint32_t subframeNo) virtual
Trigger the start from a new frame (input from Phy layer)
Parameters
frameNo frame number
subframeNo subframe number
Implements ns3::LteUePhySapUser.
Definition at line 213 of file lte-ue-mac.cc.
References ns3::LteUeMac::DoSubframeIndication(), and m_mac.
Member Data Documentation
m_mac
LteUeMac* ns3::UeMemberLteUePhySapUser::m_mac private
the UE MAC
Definition at line 197 of file lte-ue-mac.cc.
Referenced by ReceiveLteControlMessage(), ReceivePhyPdu(), and SubframeIndication().
The documentation for this class was generated from the following file:
src/lte/model/lte-ue-mac.cc