ns-3: ns3::UanHeaderRcRts Class Reference
ns3::UanHeaderRcRts Class Reference
UAN Models
RTS header.
#include "uan-header-rc.h"
Public Member Functions
UanHeaderRcRts ()
Default constructor.
UanHeaderRcRts (uint8_t frameNo, uint8_t retryNo, uint8_t noFrames, uint16_t length, Time ts)
Constructor.
virtual ~UanHeaderRcRts ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
uint8_t GetFrameNo (void) const
Get the frame number.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint16_t GetLength (void) const
Get the total number of bytes in the reservation, including headers.
uint8_t GetNoFrames (void) const
Get the number of data frames in the reservation.
uint8_t GetRetryNo (void) const
Get the retry number of this RTS packet.
virtual uint32_t GetSerializedSize (void) const
Time GetTimeStamp (void) const
Get the transmit timestamp of this RTS packet.
virtual void Print (std::ostream &os) const
void Print (std::ostream &os, Time::Unit unit) const
Specialized Print with Time::Unit declared.
virtual void Serialize (Buffer::Iterator start) const
void SetFrameNo (uint8_t fno)
Set the frame number.
void SetLength (uint16_t length)
Set the number of data bytes in the reservation.
void SetNoFrames (uint8_t no)
Set the number of data frames included in this reservation request.
void SetRetryNo (uint8_t no)
Set the retry number of this RTS packet.
void SetTimeStamp (Time timeStamp)
Set RTS transmission time.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_frameNo
Reservation frame number.
uint16_t m_length
Number of bytes (including headers) in data.
uint8_t m_noFrames
Number of data frames in reservation.
uint8_t m_retryNo
Retry number of RTS packet.
Time m_timeStamp
RTS TX timestamp.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
RTS header.
Introspection did not find any typical Config paths.
Contains frame number, retry number, number of frames, length, and timestamp.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 32 bytes (on a 64-bit architecture).
Definition at line 117 of file uan-header-rc.h.
Constructor & Destructor Documentation
UanHeaderRcRts() [1/2]
ns3::UanHeaderRcRts::UanHeaderRcRts ()
Default constructor.
Definition at line 131 of file uan-header-rc.cc.
UanHeaderRcRts() [2/2]
ns3::UanHeaderRcRts::UanHeaderRcRts (uint8_t frameNo, uint8_t retryNo, uint8_t noFrames, uint16_t length, Time ts)
Constructor.
Parameters
frameNo Reservation frame number.
retryNo Retry number of RTS packet.
noFrames Number of data frames in reservation.
length Number of bytes (including headers) in data.
ts RTS TX timestamp.
Note
Timestamp is serialized into 32 bits with ms accuracy.
Definition at line 142 of file uan-header-rc.cc.
~UanHeaderRcRts()
ns3::UanHeaderRcRts::~UanHeaderRcRts () virtual
Destructor.
Definition at line 153 of file uan-header-rc.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::UanHeaderRcRts::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 245 of file uan-header-rc.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_frameNo, m_length, m_noFrames, m_retryNo, m_timeStamp, ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU32(), ns3::Buffer::Iterator::ReadU8(), ns3::Seconds(), and visualizer.core::start().
GetFrameNo()
uint8_t ns3::UanHeaderRcRts::GetFrameNo (void) const
Get the frame number.
Returns
The frame number.
Definition at line 223 of file uan-header-rc.cc.
References m_frameNo.
Referenced by ns3::UanMacRcGw::ReceivePacket().
GetInstanceTypeId()
TypeId ns3::UanHeaderRcRts::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 270 of file uan-header-rc.cc.
References GetTypeId().
GetLength()
uint16_t ns3::UanHeaderRcRts::GetLength (void) const
Get the total number of bytes in the reservation, including headers.
Returns
Total number of bytes in data packets for reservation.
Definition at line 205 of file uan-header-rc.cc.
References m_length.
Referenced by ns3::UanMacRcGw::ReceivePacket().
GetNoFrames()
uint8_t ns3::UanHeaderRcRts::GetNoFrames (void) const
Get the number of data frames in the reservation.
Returns
The number of data frames.
Definition at line 199 of file uan-header-rc.cc.
References m_noFrames.
Referenced by ns3::UanMacRcGw::ReceivePacket().
GetRetryNo()
uint8_t ns3::UanHeaderRcRts::GetRetryNo (void) const
Get the retry number of this RTS packet.
Returns
The retry number.
Definition at line 217 of file uan-header-rc.cc.
References m_retryNo.
Referenced by ns3::UanMacRcGw::ReceivePacket().
GetSerializedSize()
uint32_t ns3::UanHeaderRcRts::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 229 of file uan-header-rc.cc.
Referenced by ns3::UanMacRcGw::UanMacRcGw().
GetTimeStamp()
Time ns3::UanHeaderRcRts::GetTimeStamp (void) const
Get the transmit timestamp of this RTS packet.
Returns
The TX time.
Note
Timestamp is serialized with 32 bits in ms precision.
Definition at line 211 of file uan-header-rc.cc.
References m_timeStamp.
GetTypeId()
TypeId ns3::UanHeaderRcRts::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 159 of file uan-header-rc.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print() [1/2]
void ns3::UanHeaderRcRts::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 264 of file uan-header-rc.cc.
References Print(), and ns3::Time::S.
Print() [2/2]
void ns3::UanHeaderRcRts::Print (std::ostream & os, Time::Unit unit) const
Specialized Print with Time::Unit declared.
Parameters
os ostream.
unit Time unit.
Definition at line 258 of file uan-header-rc.cc.
References ns3::Time::As(), m_frameNo, m_length, m_noFrames, m_retryNo, and m_timeStamp.
Referenced by Print().
Serialize()
void ns3::UanHeaderRcRts::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 235 of file uan-header-rc.cc.
References ns3::Time::GetMilliSeconds(), m_frameNo, m_length, m_noFrames, m_retryNo, m_timeStamp, ns3::Time::MS, ns3::Time::RoundTo(), and visualizer.core::start().
SetFrameNo()
void ns3::UanHeaderRcRts::SetFrameNo (uint8_t fno)
Set the frame number.
Parameters
fno TX frame number
Definition at line 171 of file uan-header-rc.cc.
References m_frameNo.
Referenced by ns3::UanMacRc::CreateRtsHeader().
SetLength()
void ns3::UanHeaderRcRts::SetLength (uint16_t length)
Set the number of data bytes in the reservation.
Parameters
length Total number of data bytes in reservation (including headers).
Note
Timestamp is serialized with 32 bits in ms precision.
Definition at line 183 of file uan-header-rc.cc.
References m_length.
Referenced by ns3::UanMacRc::CreateRtsHeader().
SetNoFrames()
void ns3::UanHeaderRcRts::SetNoFrames (uint8_t no)
Set the number of data frames included in this reservation request.
Parameters
no Number of frames.
Definition at line 177 of file uan-header-rc.cc.
References m_noFrames.
Referenced by ns3::UanMacRc::CreateRtsHeader().
SetRetryNo()
void ns3::UanHeaderRcRts::SetRetryNo (uint8_t no)
Set the retry number of this RTS packet.
This is used to match timestamp to correctly received RTS.
Parameters
no Retry number.
Definition at line 194 of file uan-header-rc.cc.
References m_retryNo.
Referenced by ns3::UanMacRc::CreateRtsHeader().
SetTimeStamp()
void ns3::UanHeaderRcRts::SetTimeStamp (Time timeStamp)
Set RTS transmission time.
Parameters
timeStamp The RTS transmission time.
Definition at line 188 of file uan-header-rc.cc.
References m_timeStamp.
Referenced by ns3::UanMacRc::CreateRtsHeader().
Member Data Documentation
m_frameNo
uint8_t ns3::UanHeaderRcRts::m_frameNo private
Reservation frame number.
Definition at line 223 of file uan-header-rc.h.
Referenced by Deserialize(), GetFrameNo(), Print(), Serialize(), and SetFrameNo().
m_length
uint16_t ns3::UanHeaderRcRts::m_length private
Number of bytes (including headers) in data.
Definition at line 225 of file uan-header-rc.h.
Referenced by Deserialize(), GetLength(), Print(), Serialize(), and SetLength().
m_noFrames
uint8_t ns3::UanHeaderRcRts::m_noFrames private
Number of data frames in reservation.
Definition at line 224 of file uan-header-rc.h.
Referenced by Deserialize(), GetNoFrames(), Print(), Serialize(), and SetNoFrames().
m_retryNo
uint8_t ns3::UanHeaderRcRts::m_retryNo private
Retry number of RTS packet.
Definition at line 227 of file uan-header-rc.h.
Referenced by Deserialize(), GetRetryNo(), Print(), Serialize(), and SetRetryNo().
m_timeStamp
Time ns3::UanHeaderRcRts::m_timeStamp private
RTS TX timestamp.
Definition at line 226 of file uan-header-rc.h.
Referenced by Deserialize(), GetTimeStamp(), Print(), Serialize(), and SetTimeStamp().
The documentation for this class was generated from the following files:
src/uan/model/uan-header-rc.h
src/uan/model/uan-header-rc.cc