ns-3: ns3::WifiActionHeader Class Reference
ns3::WifiActionHeader Class Reference
Wifi Models
See IEEE 802.11 chapter 7.3.1.11 Header format: | category: 1 | action value: 1 |.
#include "mgt-headers.h"
Classes
union ActionValue
typedef for union of different ActionValues
Public Types
enum BlockAckActionValue { BLOCK_ACK_ADDBA_REQUEST = 0 , BLOCK_ACK_ADDBA_RESPONSE = 1 , BLOCK_ACK_DELBA = 2 }
Block Ack Action field values See 802.11 Table 8-202.
enum CategoryValue {
BLOCK_ACK = 3 , MESH = 13 , MULTIHOP = 14 , SELF_PROTECTED = 15 ,
VENDOR_SPECIFIC_ACTION = 127
}
CategoryValue enumeration.
enum MeshActionValue {
LINK_METRIC_REPORT = 0 , PATH_SELECTION = 1 , PORTAL_ANNOUNCEMENT = 2 , CONGESTION_CONTROL_NOTIFICATION = 3 ,
MDA_SETUP_REQUEST = 4 , MDA_SETUP_REPLY = 5 , MDAOP_ADVERTISMENT_REQUEST = 6 , MDAOP_ADVERTISMENTS = 7 ,
MDAOP_SET_TEARDOWN = 8 , TBTT_ADJUSTMENT_REQUEST = 9 , TBTT_ADJUSTMENT_RESPONSE = 10
}
MeshActionValue enumeration.
enum MultihopActionValue { PROXY_UPDATE = 0 , PROXY_UPDATE_CONFIRMATION = 1 }
MultihopActionValue enumeration.
enum SelfProtectedActionValue {
PEER_LINK_OPEN = 1 , PEER_LINK_CONFIRM = 2 , PEER_LINK_CLOSE = 3 , GROUP_KEY_INFORM = 4 ,
GROUP_KEY_ACK = 5
}
SelfProtectedActionValue enumeration.
Public Member Functions
WifiActionHeader ()
~WifiActionHeader ()
uint32_t Deserialize (Buffer::Iterator start)
ActionValue GetAction ()
Return the action value.
CategoryValue GetCategory ()
Return the category value.
TypeId GetInstanceTypeId () const
Get the most derived TypeId for this Object.
uint32_t GetSerializedSize () const
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetAction (CategoryValue type, ActionValue action)
Set action for this Action header.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
std::string CategoryValueToString (CategoryValue value) const
Category value to string function.
std::string SelfProtectedActionValueToString (SelfProtectedActionValue value) const
Self protected action value to string function.
Private Attributes
uint8_t m_actionValue
Action value.
uint8_t m_category
Category of the action.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
See IEEE 802.11 chapter 7.3.1.11 Header format: | category: 1 | action value: 1 |.
Definition at line 870 of file mgt-headers.h.
Member Enumeration Documentation
BlockAckActionValue
enum ns3::WifiActionHeader::BlockAckActionValue
Block Ack Action field values See 802.11 Table 8-202.
Enumerator
BLOCK_ACK_ADDBA_REQUEST
BLOCK_ACK_ADDBA_RESPONSE
BLOCK_ACK_DELBA
Definition at line 930 of file mgt-headers.h.
CategoryValue
enum ns3::WifiActionHeader::CategoryValue
CategoryValue enumeration.
Enumerator
BLOCK_ACK
MESH
MULTIHOP
SELF_PROTECTED
VENDOR_SPECIFIC_ACTION
Definition at line 882 of file mgt-headers.h.
MeshActionValue
enum ns3::WifiActionHeader::MeshActionValue
MeshActionValue enumeration.
Enumerator
LINK_METRIC_REPORT
PATH_SELECTION
PORTAL_ANNOUNCEMENT
CONGESTION_CONTROL_NOTIFICATION
MDA_SETUP_REQUEST
MDA_SETUP_REPLY
MDAOP_ADVERTISMENT_REQUEST
MDAOP_ADVERTISMENTS
MDAOP_SET_TEARDOWN
TBTT_ADJUSTMENT_REQUEST
TBTT_ADJUSTMENT_RESPONSE
Definition at line 911 of file mgt-headers.h.
MultihopActionValue
enum ns3::WifiActionHeader::MultihopActionValue
MultihopActionValue enumeration.
Enumerator
PROXY_UPDATE
PROXY_UPDATE_CONFIRMATION
Definition at line 904 of file mgt-headers.h.
SelfProtectedActionValue
enum ns3::WifiActionHeader::SelfProtectedActionValue
SelfProtectedActionValue enumeration.
Enumerator
PEER_LINK_OPEN
PEER_LINK_CONFIRM
PEER_LINK_CLOSE
GROUP_KEY_INFORM
GROUP_KEY_ACK
Definition at line 894 of file mgt-headers.h.
Constructor & Destructor Documentation
WifiActionHeader()
ns3::WifiActionHeader::WifiActionHeader ()
Definition at line 1168 of file mgt-headers.cc.
~WifiActionHeader()
ns3::WifiActionHeader::~WifiActionHeader ()
Definition at line 1172 of file mgt-headers.cc.
Member Function Documentation
CategoryValueToString()
std::string ns3::WifiActionHeader::CategoryValueToString (CategoryValue value) const private
Category value to string function.
Parameters
value the category value
Returns
the category value string
Definition at line 1358 of file mgt-headers.cc.
References BLOCK_ACK, MESH, SELF_PROTECTED, and VENDOR_SPECIFIC_ACTION.
Referenced by Print().
Deserialize()
uint32_t ns3::WifiActionHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 1435 of file mgt-headers.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_actionValue, m_category, ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetAction()
WifiActionHeader::ActionValue ns3::WifiActionHeader::GetAction ()
Return the action value.
Returns
ActionValue
Definition at line 1232 of file mgt-headers.cc.
References BLOCK_ACK, BLOCK_ACK_ADDBA_REQUEST, BLOCK_ACK_ADDBA_RESPONSE, BLOCK_ACK_DELBA, ns3::WifiActionHeader::ActionValue::blockAck, CONGESTION_CONTROL_NOTIFICATION, GROUP_KEY_ACK, GROUP_KEY_INFORM, LINK_METRIC_REPORT, m_actionValue, m_category, MDA_SETUP_REPLY, MDA_SETUP_REQUEST, MDAOP_ADVERTISMENT_REQUEST, MDAOP_ADVERTISMENTS, MDAOP_SET_TEARDOWN, MESH, ns3::WifiActionHeader::ActionValue::meshAction, MULTIHOP, ns3::WifiActionHeader::ActionValue::multihopAction, NS_FATAL_ERROR, PATH_SELECTION, PEER_LINK_CLOSE, PEER_LINK_CONFIRM, PEER_LINK_OPEN, PORTAL_ANNOUNCEMENT, PROXY_UPDATE, PROXY_UPDATE_CONFIRMATION, SELF_PROTECTED, ns3::WifiActionHeader::ActionValue::selfProtectedAction, TBTT_ADJUSTMENT_REQUEST, and TBTT_ADJUSTMENT_RESPONSE.
Referenced by ns3::GetTid(), ns3::QosTxop::GotAck(), ns3::dot11s::PeerManagementProtocolMac::Receive(), and ns3::RegularWifiMac::Receive().
GetCategory()
WifiActionHeader::CategoryValue ns3::WifiActionHeader::GetCategory (void)
Return the category value.
Returns
CategoryValue
Definition at line 1211 of file mgt-headers.cc.
References BLOCK_ACK, m_category, MESH, MULTIHOP, NS_FATAL_ERROR, SELF_PROTECTED, and VENDOR_SPECIFIC_ACTION.
Referenced by ns3::GetTid(), ns3::QosTxop::GotAck(), ns3::QosTxop::MissedAck(), ns3::QosTxop::MissedBlockAck(), ns3::dot11s::PeerManagementProtocolMac::Receive(), ns3::RegularWifiMac::Receive(), ns3::dot11s::HwmpProtocolMac::ReceiveAction(), and ns3::dot11s::PeerManagementProtocolMac::UpdateOutcomingFrame().
GetInstanceTypeId()
TypeId ns3::WifiActionHeader::GetInstanceTypeId () const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 1352 of file mgt-headers.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::WifiActionHeader::GetSerializedSize () const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 1422 of file mgt-headers.cc.
GetTypeId()
TypeId ns3::WifiActionHeader::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 1341 of file mgt-headers.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::WifiActionHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 1415 of file mgt-headers.cc.
References CategoryValueToString(), m_actionValue, m_category, and SelfProtectedActionValueToString().
SelfProtectedActionValueToString()
std::string ns3::WifiActionHeader::SelfProtectedActionValueToString (SelfProtectedActionValue value) const private
Self protected action value to string function.
Parameters
value the protected action value
Returns
the self protected action value string
Definition at line 1384 of file mgt-headers.cc.
References GROUP_KEY_ACK, GROUP_KEY_INFORM, PEER_LINK_CLOSE, PEER_LINK_CONFIRM, and PEER_LINK_OPEN.
Referenced by Print().
Serialize()
void ns3::WifiActionHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 1428 of file mgt-headers.cc.
References m_actionValue, m_category, and visualizer.core::start().
SetAction()
void ns3::WifiActionHeader::SetAction (WifiActionHeader::CategoryValue type, WifiActionHeader::ActionValue action)
Set action for this Action header.
Parameters
type category
action action
Definition at line 1177 of file mgt-headers.cc.
References BLOCK_ACK, ns3::WifiActionHeader::ActionValue::blockAck, m_actionValue, m_category, MESH, ns3::WifiActionHeader::ActionValue::meshAction, MULTIHOP, ns3::WifiActionHeader::ActionValue::multihopAction, SELF_PROTECTED, ns3::WifiActionHeader::ActionValue::selfProtectedAction, and VENDOR_SPECIFIC_ACTION.
Referenced by ns3::dot11s::HwmpProtocolMac::GetWifiActionHeader(), ns3::QosTxop::SendAddBaRequest(), ns3::RegularWifiMac::SendAddBaResponse(), ns3::QosTxop::SendDelbaFrame(), and ns3::dot11s::PeerManagementProtocolMac::SendPeerLinkManagementFrame().
Member Data Documentation
m_actionValue
uint8_t ns3::WifiActionHeader::m_actionValue private
Action value.
Definition at line 995 of file mgt-headers.h.
Referenced by Deserialize(), GetAction(), Print(), Serialize(), and SetAction().
m_category
uint8_t ns3::WifiActionHeader::m_category private
Category of the action.
Definition at line 994 of file mgt-headers.h.
Referenced by Deserialize(), GetAction(), GetCategory(), Print(), Serialize(), and SetAction().
The documentation for this class was generated from the following files:
src/wifi/model/mgt-headers.h
src/wifi/model/mgt-headers.cc