ns-3: ns3::RawTextConfigSave Class Reference
ns3::RawTextConfigSave Class Reference
Configuration Store/Load
A class to enable saving of configuration store in a raw text file.
#include "raw-text-config.h"
Public Member Functions
RawTextConfigSave ()
default constructor
virtual ~RawTextConfigSave ()
destructor
virtual void Attributes (void)
Load or save the attributes values.
virtual void Default (void)
Load or save the default values.
virtual void Global (void)
Load or save the global values.
virtual void SetFilename (std::string filename)
Set the file name.
Public Member Functions inherited from ns3::FileConfig
virtual ~FileConfig ()
Private Attributes
std::ofstream * m_os
Config store output stream.
Detailed Description
A class to enable saving of configuration store in a raw text file.
Definition at line 35 of file raw-text-config.h.
Constructor & Destructor Documentation
RawTextConfigSave()
ns3::RawTextConfigSave::RawTextConfigSave ()
default constructor
Definition at line 38 of file raw-text-config.cc.
References NS_LOG_FUNCTION.
~RawTextConfigSave()
ns3::RawTextConfigSave::~RawTextConfigSave () virtual
destructor
Definition at line 43 of file raw-text-config.cc.
References m_os, and NS_LOG_FUNCTION.
Member Function Documentation
Attributes()
void ns3::RawTextConfigSave::Attributes (void) virtual
Load or save the attributes values.
Implements ns3::FileConfig.
Definition at line 98 of file raw-text-config.cc.
References ns3::StringValue::Get(), m_os, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by ns3::save_clicked_attribute().
Default()
void ns3::RawTextConfigSave::Default (void) virtual
Load or save the default values.
Implements ns3::FileConfig.
Definition at line 61 of file raw-text-config.cc.
References m_os, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by ns3::save_clicked_default().
Global()
void ns3::RawTextConfigSave::Global (void) virtual
Load or save the global values.
Implements ns3::FileConfig.
Definition at line 86 of file raw-text-config.cc.
References ns3::GlobalValue::Begin(), ns3::GlobalValue::End(), ns3::StringValue::Get(), m_os, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
SetFilename()
void ns3::RawTextConfigSave::SetFilename (std::string filename) virtual
Set the file name.
Parameters
filename the filename
Implements ns3::FileConfig.
Definition at line 54 of file raw-text-config.cc.
References m_os, and NS_LOG_FUNCTION.
Referenced by ns3::save_clicked_attribute(), and ns3::save_clicked_default().
Member Data Documentation
m_os
std::ofstream* ns3::RawTextConfigSave::m_os private
Config store output stream.
Definition at line 47 of file raw-text-config.h.
Referenced by ~RawTextConfigSave(), Attributes(), Default(), Global(), and SetFilename().
The documentation for this class was generated from the following files:
src/config-store/model/raw-text-config.h
src/config-store/model/raw-text-config.cc