ns-3: ns3::WifiRadioEnergyModelHelper Class Reference
ns3::WifiRadioEnergyModelHelper Class Reference
Energy Models
Assign WifiRadioEnergyModel to wifi devices.
#include "wifi-radio-energy-model-helper.h"
Public Member Functions
WifiRadioEnergyModelHelper ()
Construct a helper which is used to add a radio energy model to a node.
~WifiRadioEnergyModelHelper ()
Destroy a RadioEnergy Helper.
void Set (std::string name, const AttributeValue &v)
void SetDepletionCallback (WifiRadioEnergyModel::WifiRadioEnergyDepletionCallback callback)
void SetRechargedCallback (WifiRadioEnergyModel::WifiRadioEnergyRechargedCallback callback)
void SetTxCurrentModel (std::string name, std::string n0="", const AttributeValue &v0=EmptyAttributeValue(), std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue(), std::string n6="", const AttributeValue &v6=EmptyAttributeValue(), std::string n7="", const AttributeValue &v7=EmptyAttributeValue())
Public Member Functions inherited from ns3::DeviceEnergyModelHelper
virtual ~DeviceEnergyModelHelper ()
DeviceEnergyModelContainer Install (NetDeviceContainer deviceContainer, EnergySourceContainer sourceContainer) const
DeviceEnergyModelContainer Install (Ptr< NetDevice > device, Ptr< EnergySource > source) const
Private Member Functions
virtual Ptr< DeviceEnergyModel > DoInstall (Ptr< NetDevice > device, Ptr< EnergySource > source) const
Private Attributes
WifiRadioEnergyModel::WifiRadioEnergyDepletionCallback m_depletionCallback
radio energy depletion callback
ObjectFactory m_radioEnergy
radio energy
WifiRadioEnergyModel::WifiRadioEnergyRechargedCallback m_rechargedCallback
radio energy recharged callback
ObjectFactory m_txCurrentModel
transmit current model
Detailed Description
Assign WifiRadioEnergyModel to wifi devices.
This installer installs WifiRadioEnergyModel for only WifiNetDevice objects.
Definition at line 36 of file wifi-radio-energy-model-helper.h.
Constructor & Destructor Documentation
WifiRadioEnergyModelHelper()
ns3::WifiRadioEnergyModelHelper::WifiRadioEnergyModelHelper ()
Construct a helper which is used to add a radio energy model to a node.
Definition at line 28 of file wifi-radio-energy-model-helper.cc.
References m_depletionCallback, m_radioEnergy, m_rechargedCallback, ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::Nullify(), and ns3::ObjectFactory::SetTypeId().
~WifiRadioEnergyModelHelper()
ns3::WifiRadioEnergyModelHelper::~WifiRadioEnergyModelHelper ()
Destroy a RadioEnergy Helper.
Definition at line 35 of file wifi-radio-energy-model-helper.cc.
Member Function Documentation
DoInstall()
Ptr< DeviceEnergyModel > ns3::WifiRadioEnergyModelHelper::DoInstall (Ptr< NetDevice > device, Ptr< EnergySource > source) const private virtual
Parameters
device Pointer to the NetDevice to install DeviceEnergyModel.
source Pointer to EnergySource to install.
Returns
Ptr<DeviceEnergyModel>
Implements DeviceEnergyModel::Install.
Implements ns3::DeviceEnergyModelHelper.
Definition at line 89 of file wifi-radio-energy-model-helper.cc.
References ns3::ObjectFactory::Create(), ns3::Object::GetObject(), ns3::WifiNetDevice::GetPhy(), ns3::ObjectFactory::GetTypeId(), ns3::TypeId::GetUid(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_depletionCallback, m_radioEnergy, m_rechargedCallback, m_txCurrentModel, ns3::MakeCallback(), NS_ASSERT, NS_FATAL_ERROR, ns3::WifiPhy::RegisterListener(), ns3::WifiPhy::ResumeFromOff(), ns3::WifiPhy::SetOffMode(), and ns3::WifiPhy::SetWifiRadioEnergyModel().
Set()
void ns3::WifiRadioEnergyModelHelper::Set (std::string name, const AttributeValue & v) virtual
Parameters
name the name of the attribute to set
v the value of the attribute
Sets an attribute of the underlying PHY object.
Implements ns3::DeviceEnergyModelHelper.
Definition at line 40 of file wifi-radio-energy-model-helper.cc.
References m_radioEnergy, and ns3::ObjectFactory::Set().
Referenced by BatteryLifetimeTest::ConstantLoadTest(), and BatteryLifetimeTest::VariableLoadTest().
SetDepletionCallback()
void ns3::WifiRadioEnergyModelHelper::SetDepletionCallback (WifiRadioEnergyModel::WifiRadioEnergyDepletionCallback callback)
Parameters
callback Callback function for energy depletion handling.
Sets the callback to be invoked when energy is depleted.
Definition at line 46 of file wifi-radio-energy-model-helper.cc.
References m_depletionCallback.
Referenced by BasicEnergyDepletionTest::DepletionTestCase().
SetRechargedCallback()
void ns3::WifiRadioEnergyModelHelper::SetRechargedCallback (WifiRadioEnergyModel::WifiRadioEnergyRechargedCallback callback)
Parameters
callback Callback function for energy recharged handling.
Sets the callback to be invoked when energy is recharged.
Definition at line 53 of file wifi-radio-energy-model-helper.cc.
References m_rechargedCallback.
SetTxCurrentModel()
void ns3::WifiRadioEnergyModelHelper::SetTxCurrentModel (std::string name, std::string n0 = "", const AttributeValue & v0 = EmptyAttributeValue (), std::string n1 = "", const AttributeValue & v1 = EmptyAttributeValue (), std::string n2 = "", const AttributeValue & v2 = EmptyAttributeValue (), std::string n3 = "", const AttributeValue & v3 = EmptyAttributeValue (), std::string n4 = "", const AttributeValue & v4 = EmptyAttributeValue (), std::string n5 = "", const AttributeValue & v5 = EmptyAttributeValue (), std::string n6 = "", const AttributeValue & v6 = EmptyAttributeValue (), std::string n7 = "", const AttributeValue & v7 = EmptyAttributeValue ())
Parameters
name the name of the model to set
n0 the name of the attribute to set
v0 the value of the attribute to set
n1 the name of the attribute to set
v1 the value of the attribute to set
n2 the name of the attribute to set
v2 the value of the attribute to set
n3 the name of the attribute to set
v3 the value of the attribute to set
n4 the name of the attribute to set
v4 the value of the attribute to set
n5 the name of the attribute to set
v5 the value of the attribute to set
n6 the name of the attribute to set
v6 the value of the attribute to set
n7 the name of the attribute to set
v7 the value of the attribute to set
Configure a Transmission Current model for this EnergySource.
Definition at line 60 of file wifi-radio-energy-model-helper.cc.
References m_txCurrentModel, ns3::ObjectFactory::Set(), and ns3::ObjectFactory::SetTypeId().
Member Data Documentation
m_depletionCallback
WifiRadioEnergyModel::WifiRadioEnergyDepletionCallback ns3::WifiRadioEnergyModelHelper::m_depletionCallback private
radio energy depletion callback
Definition at line 115 of file wifi-radio-energy-model-helper.h.
Referenced by WifiRadioEnergyModelHelper(), DoInstall(), and SetDepletionCallback().
m_radioEnergy
ObjectFactory ns3::WifiRadioEnergyModelHelper::m_radioEnergy private
radio energy
Definition at line 114 of file wifi-radio-energy-model-helper.h.
Referenced by WifiRadioEnergyModelHelper(), DoInstall(), and Set().
m_rechargedCallback
WifiRadioEnergyModel::WifiRadioEnergyRechargedCallback ns3::WifiRadioEnergyModelHelper::m_rechargedCallback private
radio energy recharged callback
Definition at line 116 of file wifi-radio-energy-model-helper.h.
Referenced by WifiRadioEnergyModelHelper(), DoInstall(), and SetRechargedCallback().
m_txCurrentModel
ObjectFactory ns3::WifiRadioEnergyModelHelper::m_txCurrentModel private
transmit current model
Definition at line 117 of file wifi-radio-energy-model-helper.h.
Referenced by DoInstall(), and SetTxCurrentModel().
The documentation for this class was generated from the following files:
src/wifi/helper/wifi-radio-energy-model-helper.h
src/wifi/helper/wifi-radio-energy-model-helper.cc