ns-3: ns3::LteEnbPhySapUser Class Reference
ns3::LteEnbPhySapUser Class Reference abstract
Service Access Point (SAP) offered by the eNB-PHY to the eNB-MAC.
#include "lte-enb-phy-sap.h"
Public Member Functions
virtual ~LteEnbPhySapUser ()
virtual void DlInfoListElementHarqFeeback (DlInfoListElement_s params)=0
Notify the HARQ on the DL tranmission status.
virtual void ReceiveLteControlMessage (Ptr< LteControlMessage > msg)=0
Receive SendLteControlMessage (PDCCH map, CQI feedbacks) using the ideal control channel.
virtual void ReceivePhyPdu (Ptr< Packet > p)=0
Called by the Phy to notify the MAC of the reception of a new PHY-PDU.
virtual void ReceiveRachPreamble (uint32_t prachId)=0
notify the reception of a RACH preamble on the PRACH
virtual void SubframeIndication (uint32_t frameNo, uint32_t subframeNo)=0
Trigger the start from a new frame (input from Phy layer)
virtual void UlCqiReport (FfMacSchedSapProvider::SchedUlCqiInfoReqParameters ulcqi)=0
Returns to MAC level the UL-CQI evaluated.
virtual void UlInfoListElementHarqFeeback (UlInfoListElement_s params)=0
Notify the HARQ on the UL tranmission status.
Detailed Description
Service Access Point (SAP) offered by the eNB-PHY to the eNB-MAC.
This is the MAC SAP User, i.e., the part of the SAP that contains the MAC methods called by the PHY
Definition at line 74 of file lte-enb-phy-sap.h.
Constructor & Destructor Documentation
~LteEnbPhySapUser()
ns3::LteEnbPhySapUser::~LteEnbPhySapUser () virtual
Definition at line 33 of file lte-enb-phy-sap.cc.
Member Function Documentation
DlInfoListElementHarqFeeback()
virtual void ns3::LteEnbPhySapUser::DlInfoListElementHarqFeeback (DlInfoListElement_s params) pure virtual
Notify the HARQ on the DL tranmission status.
Parameters
params
Implemented in ns3::EnbMacMemberLteEnbPhySapUser.
ReceiveLteControlMessage()
virtual void ns3::LteEnbPhySapUser::ReceiveLteControlMessage (Ptr< LteControlMessage > msg) pure virtual
Receive SendLteControlMessage (PDCCH map, CQI feedbacks) using the ideal control channel.
Parameters
msg the Ideal Control Message to receive
Implemented in ns3::EnbMacMemberLteEnbPhySapUser.
Referenced by ns3::LteEnbPhy::ReceiveLteControlMessage(), and ns3::LteEnbPhy::ReceiveLteControlMessageList().
ReceivePhyPdu()
virtual void ns3::LteEnbPhySapUser::ReceivePhyPdu (Ptr< Packet > p) pure virtual
Called by the Phy to notify the MAC of the reception of a new PHY-PDU.
Parameters
p
Implemented in ns3::EnbMacMemberLteEnbPhySapUser.
Referenced by ns3::LteEnbPhy::PhyPduReceived().
ReceiveRachPreamble()
virtual void ns3::LteEnbPhySapUser::ReceiveRachPreamble (uint32_t prachId) pure virtual
notify the reception of a RACH preamble on the PRACH
Parameters
prachId the ID of the preamble
Implemented in ns3::EnbMacMemberLteEnbPhySapUser.
Referenced by ns3::LteEnbPhy::ReceiveLteControlMessageList().
SubframeIndication()
virtual void ns3::LteEnbPhySapUser::SubframeIndication (uint32_t frameNo, uint32_t subframeNo) pure virtual
Trigger the start from a new frame (input from Phy layer)
Parameters
frameNo frame number
subframeNo subframe number
Implemented in ns3::EnbMacMemberLteEnbPhySapUser.
Referenced by ns3::LteEnbPhy::StartSubFrame().
UlCqiReport()
virtual void ns3::LteEnbPhySapUser::UlCqiReport (FfMacSchedSapProvider::SchedUlCqiInfoReqParameters ulcqi) pure virtual
Returns to MAC level the UL-CQI evaluated.
Parameters
ulcqi the UL-CQI (see FF MAC API 4.3.29)
Implemented in ns3::EnbMacMemberLteEnbPhySapUser.
Referenced by ns3::LteEnbPhy::GenerateCtrlCqiReport(), and ns3::LteEnbPhy::GenerateDataCqiReport().
UlInfoListElementHarqFeeback()
virtual void ns3::LteEnbPhySapUser::UlInfoListElementHarqFeeback (UlInfoListElement_s params) pure virtual
Notify the HARQ on the UL tranmission status.
Parameters
params
Implemented in ns3::EnbMacMemberLteEnbPhySapUser.
Referenced by ns3::LteEnbPhy::ReportUlHarqFeedback().
The documentation for this class was generated from the following files:
src/lte/model/lte-enb-phy-sap.h
src/lte/model/lte-enb-phy-sap.cc