ns-3: ns3::NodeList Class Reference
ns3::NodeList Class Reference
Network
the list of simulation nodes.
#include "node-list.h"
Public Types
typedef std::vector< Ptr< Node > >::const_iterator Iterator
Node container iterator.
Static Public Member Functions
static uint32_t Add (Ptr< Node > node)
static Iterator Begin (void)
static Iterator End (void)
static uint32_t GetNNodes (void)
static Ptr< Node > GetNode (uint32_t n)
Detailed Description
the list of simulation nodes.
Every Node created is automatically added to this list.
Definition at line 40 of file node-list.h.
Member Typedef Documentation
Iterator
typedef std::vector< Ptr<Node> >::const_iterator ns3::NodeList::Iterator
Node container iterator.
Definition at line 44 of file node-list.h.
Member Function Documentation
Add()
uint32_t ns3::NodeList::Add (Ptr< Node > node) static
Parameters
node node to add
Returns
index of node in list.
This method is called automatically from Node::Node so the user has little reason to call it himself.
Definition at line 223 of file node-list.cc.
References ns3::NodeListPriv::Get(), and NS_LOG_FUNCTION.
Referenced by ns3::Node::Construct().
Begin()
NodeList::Iterator ns3::NodeList::Begin (void) static
Returns
a C++ iterator located at the beginning of this list.
Definition at line 229 of file node-list.cc.
References ns3::NodeListPriv::Get(), and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::GlobalRouteManagerImpl::BuildGlobalRoutingDatabase(), ns3::Ipv4NixVectorRouting::BuildIpv4AddressToNodeMap(), ns3::AnimationInterface::ConnectLte(), ns3::GlobalRouteManagerImpl::DeleteGlobalRoutes(), ns3::LteEnbRrcProtocolIdeal::DoSendSystemInformation(), ns3::LteEnbRrcProtocolReal::DoSendSystemInformation(), ns3::AnimationInterface::EnableIpv4L3ProtocolCounters(), ns3::AnimationInterface::EnableQueueCounters(), ns3::AnimationInterface::EnableWifiMacCounters(), ns3::AnimationInterface::EnableWifiPhyCounters(), ns3::GlobalRouteManagerImpl::FindOutgoingInterfaceId(), ns3::Ipv4NixVectorRouting::FlushGlobalNixRoutingCache(), ns3::NodeContainer::GetGlobal(), ns3::AnimationInterface::GetMovedNodes(), ns3::GlobalRouteManagerImpl::InitializeRoutes(), ns3::Ns2MobilityHelper::Install(), ns3::FlowMonitorHelper::InstallAll(), ns3::BuildingsHelper::MakeMobilityModelConsistent(), PrintGnuplottableEnbListToFile(), PrintGnuplottableUeListToFile(), PrintUePosition(), ns3::LteUeRrcProtocolIdeal::SetEnbRrcSapProvider(), ns3::LteUeRrcProtocolReal::SetEnbRrcSapProvider(), ns3::GlobalRouteManagerImpl::SPFAddASExternal(), ns3::GlobalRouteManagerImpl::SPFIntraAddRouter(), ns3::GlobalRouteManagerImpl::SPFIntraAddStub(), ns3::GlobalRouteManagerImpl::SPFIntraAddTransit(), ns3::AnimationInterface::TrackIpv4L3ProtocolCounters(), ns3::AnimationInterface::TrackIpv4Route(), ns3::AnimationInterface::TrackQueueCounters(), ns3::AnimationInterface::TrackWifiMacCounters(), ns3::AnimationInterface::TrackWifiPhyCounters(), ns3::AnimationInterface::WriteLinkProperties(), ns3::AnimationInterface::WriteNodeColors(), ns3::AnimationInterface::WriteNodeEnergies(), ns3::AnimationInterface::WriteNodes(), and ns3::AnimationInterface::WriteNodeSizes().
End()
NodeList::Iterator ns3::NodeList::End (void) static
Returns
a C++ iterator located at the end of this list.
Definition at line 235 of file node-list.cc.
References ns3::NodeListPriv::Get(), and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::GlobalRouteManagerImpl::BuildGlobalRoutingDatabase(), ns3::Ipv4NixVectorRouting::BuildIpv4AddressToNodeMap(), ns3::AnimationInterface::ConnectLte(), ns3::GlobalRouteManagerImpl::DeleteGlobalRoutes(), ns3::LteEnbRrcProtocolIdeal::DoSendSystemInformation(), ns3::LteEnbRrcProtocolReal::DoSendSystemInformation(), ns3::AnimationInterface::EnableIpv4L3ProtocolCounters(), ns3::AnimationInterface::EnableQueueCounters(), ns3::AnimationInterface::EnableWifiMacCounters(), ns3::AnimationInterface::EnableWifiPhyCounters(), ns3::GlobalRouteManagerImpl::FindOutgoingInterfaceId(), ns3::Ipv4NixVectorRouting::FlushGlobalNixRoutingCache(), ns3::NodeContainer::GetGlobal(), ns3::AnimationInterface::GetMovedNodes(), ns3::GlobalRouteManagerImpl::InitializeRoutes(), ns3::Ns2MobilityHelper::Install(), ns3::FlowMonitorHelper::InstallAll(), ns3::BuildingsHelper::MakeMobilityModelConsistent(), PrintGnuplottableEnbListToFile(), PrintGnuplottableUeListToFile(), PrintUePosition(), ns3::LteUeRrcProtocolIdeal::SetEnbRrcSapProvider(), ns3::LteUeRrcProtocolReal::SetEnbRrcSapProvider(), ns3::GlobalRouteManagerImpl::SPFAddASExternal(), ns3::GlobalRouteManagerImpl::SPFIntraAddRouter(), ns3::GlobalRouteManagerImpl::SPFIntraAddStub(), ns3::GlobalRouteManagerImpl::SPFIntraAddTransit(), ns3::AnimationInterface::TrackIpv4L3ProtocolCounters(), ns3::AnimationInterface::TrackIpv4Route(), ns3::AnimationInterface::TrackQueueCounters(), ns3::AnimationInterface::TrackWifiMacCounters(), ns3::AnimationInterface::TrackWifiPhyCounters(), ns3::AnimationInterface::WriteLinkProperties(), ns3::AnimationInterface::WriteNodeColors(), ns3::AnimationInterface::WriteNodeEnergies(), ns3::AnimationInterface::WriteNodes(), and ns3::AnimationInterface::WriteNodeSizes().
GetNNodes()
uint32_t ns3::NodeList::GetNNodes (void) static
Returns
the number of nodes currently in the list.
Definition at line 247 of file node-list.cc.
References ns3::NodeListPriv::Get(), and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::dsr::DsrOptions::GetIDfromIP(), ns3::dsr::DsrRouting::GetIDfromIP(), ns3::dsr::DsrRouting::GetIPfromMAC(), ns3::Ipv4NixVectorRouting::GetNixVector(), ns3::dsr::DsrOptions::GetNodeWithAddress(), ns3::dsr::DsrRouting::GetNodeWithAddress(), ns3::Ipv4RoutingHelper::PrintNeighborCacheAllAt(), ns3::Ipv6RoutingHelper::PrintNeighborCacheAllAt(), ns3::Ipv4RoutingHelper::PrintNeighborCacheAllEvery(), ns3::Ipv6RoutingHelper::PrintNeighborCacheAllEvery(), ns3::Ipv4RoutingHelper::PrintRoutingTableAllAt(), ns3::Ipv6RoutingHelper::PrintRoutingTableAllAt(), ns3::Ipv4RoutingHelper::PrintRoutingTableAllEvery(), ns3::Ipv6RoutingHelper::PrintRoutingTableAllEvery(), ns3::dsr::DsrOptionSR::Process(), and ns3::GlobalRouteManagerImpl::SPFCalculate().
GetNode()
Ptr< Node > ns3::NodeList::GetNode (uint32_t n) static
Parameters
n index of requested node.
Returns
the Node associated to index n.
Definition at line 241 of file node-list.cc.
References ns3::NodeListPriv::Get(), sample-rng-plot::n, and NS_LOG_FUNCTION.
Referenced by ContextToMac(), ns3::PyViz::FindNetDeviceStatistics(), ns3::dsr::DsrOptions::GetIDfromIP(), ns3::dsr::DsrRouting::GetIDfromIP(), ns3::dsr::DsrRouting::GetIPfromID(), ns3::dsr::DsrRouting::GetIPfromMAC(), ns3::AnimationInterface::GetIpv4Address(), ns3::AnimationInterface::GetIpv4Addresses(), ns3::AnimationInterface::GetIpv6Address(), ns3::AnimationInterface::GetIpv6Addresses(), ns3::dsr::DsrRouting::GetNetDeviceFromContext(), ns3::GlobalRoutingLSA::GetNode(), ns3::AnimationInterface::GetNodeFromContext(), ns3::dsr::DsrOptions::GetNodeWithAddress(), ns3::dsr::DsrRouting::GetNodeWithAddress(), ns3::Ipv4RoutingHelper::PrintNeighborCacheAllAt(), ns3::Ipv6RoutingHelper::PrintNeighborCacheAllAt(), ns3::Ipv4RoutingHelper::PrintNeighborCacheAllEvery(), ns3::Ipv6RoutingHelper::PrintNeighborCacheAllEvery(), ns3::Ipv4RoutingHelper::PrintRoutingTableAllAt(), ns3::Ipv6RoutingHelper::PrintRoutingTableAllAt(), ns3::Ipv4RoutingHelper::PrintRoutingTableAllEvery(), ns3::Ipv6RoutingHelper::PrintRoutingTableAllEvery(), ns3::dsr::DsrOptionSR::Process(), ns3::GrantedTimeWindowMpiInterface::ReceiveMessages(), ns3::NullMessageMpiInterface::ReceiveMessages(), ns3::AnimationInterface::RecursiveIpv4RoutePathSearch(), ns3::GrantedTimeWindowMpiInterface::SendPacket(), ns3::NullMessageMpiInterface::SendPacket(), ns3::PyViz::TraceDevQueueDrop(), ns3::PyViz::TraceNetDevRxCommon(), ns3::PyViz::TraceNetDevTxCommon(), ns3::AnimationInterface::TrackIpv4RoutePaths(), ns3::AnimationInterface::UpdateNodeColor(), ns3::AnimationInterface::UpdateNodeDescription(), ns3::AnimationInterface::WavePhyRxBeginTrace(), ns3::AnimationInterface::WifiPhyRxBeginTrace(), and ns3::AnimationInterface::WriteNodeEnergies().
The documentation for this class was generated from the following files:
src/network/model/node-list.h
src/network/model/node-list.cc