ns-3: ns3::UdpL4Protocol Class Reference
ns3::UdpL4Protocol Class Reference
Internet » UDP
Implementation of the UDP protocol.
#include "udp-l4-protocol.h"
Public Member Functions
UdpL4Protocol ()
virtual ~UdpL4Protocol ()
Ipv4EndPoint * Allocate (Ipv4Address address)
Allocate an IPv4 Endpoint.
Ipv4EndPoint * Allocate (Ptr< NetDevice > boundNetDevice, Ipv4Address address, uint16_t port)
Allocate an IPv4 Endpoint.
Ipv4EndPoint * Allocate (Ptr< NetDevice > boundNetDevice, Ipv4Address localAddress, uint16_t localPort, Ipv4Address peerAddress, uint16_t peerPort)
Allocate an IPv4 Endpoint.
Ipv4EndPoint * Allocate (Ptr< NetDevice > boundNetDevice, uint16_t port)
Allocate an IPv4 Endpoint.
Ipv4EndPoint * Allocate (void)
Allocate an IPv4 Endpoint.
Ipv6EndPoint * Allocate6 (Ipv6Address address)
Allocate an IPv6 Endpoint.
Ipv6EndPoint * Allocate6 (Ptr< NetDevice > boundNetDevice, Ipv6Address address, uint16_t port)
Allocate an IPv6 Endpoint.
Ipv6EndPoint * Allocate6 (Ptr< NetDevice > boundNetDevice, Ipv6Address localAddress, uint16_t localPort, Ipv6Address peerAddress, uint16_t peerPort)
Allocate an IPv6 Endpoint.
Ipv6EndPoint * Allocate6 (Ptr< NetDevice > boundNetDevice, uint16_t port)
Allocate an IPv6 Endpoint.
Ipv6EndPoint * Allocate6 (void)
Allocate an IPv6 Endpoint.
Ptr< Socket > CreateSocket (void)
void DeAllocate (Ipv4EndPoint *endPoint)
Remove an IPv4 Endpoint.
void DeAllocate (Ipv6EndPoint *endPoint)
Remove an IPv6 Endpoint.
virtual IpL4Protocol::DownTargetCallback GetDownTarget (void) const
This method allows a caller to get the current down target callback set for this L4 protocol (IPv4 case)
virtual IpL4Protocol::DownTargetCallback6 GetDownTarget6 (void) const
This method allows a caller to get the current down target callback set for this L4 protocol (IPv6 case)
virtual int GetProtocolNumber (void) const
Returns the protocol number of this protocol.
virtual enum IpL4Protocol::RxStatus Receive (Ptr< Packet > p, Ipv4Header const &header, Ptr< Ipv4Interface > interface)
Called from lower-level layers to send the packet up in the stack.
virtual enum IpL4Protocol::RxStatus Receive (Ptr< Packet > p, Ipv6Header const &header, Ptr< Ipv6Interface > interface)
Called from lower-level layers to send the packet up in the stack.
virtual void ReceiveIcmp (Ipv4Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo, Ipv4Address payloadSource, Ipv4Address payloadDestination, const uint8_t payload[8])
Called from lower-level layers to send the ICMP packet up in the stack.
virtual void ReceiveIcmp (Ipv6Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo, Ipv6Address payloadSource, Ipv6Address payloadDestination, const uint8_t payload[8])
Called from lower-level layers to send the ICMPv6 packet up in the stack.
void Send (Ptr< Packet > packet, Ipv4Address saddr, Ipv4Address daddr, uint16_t sport, uint16_t dport)
Send a packet via UDP (IPv4)
void Send (Ptr< Packet > packet, Ipv4Address saddr, Ipv4Address daddr, uint16_t sport, uint16_t dport, Ptr< Ipv4Route > route)
Send a packet via UDP (IPv4)
void Send (Ptr< Packet > packet, Ipv6Address saddr, Ipv6Address daddr, uint16_t sport, uint16_t dport)
Send a packet via UDP (IPv6)
void Send (Ptr< Packet > packet, Ipv6Address saddr, Ipv6Address daddr, uint16_t sport, uint16_t dport, Ptr< Ipv6Route > route)
Send a packet via UDP (IPv6)
virtual void SetDownTarget (IpL4Protocol::DownTargetCallback cb)
This method allows a caller to set the current down target callback set for this L4 protocol (IPv4 case)
virtual void SetDownTarget6 (IpL4Protocol::DownTargetCallback6 cb)
This method allows a caller to set the current down target callback set for this L4 protocol (IPv6 case)
void SetNode (Ptr< Node > node)
Set node associated with this stack.
Public Member Functions inherited from ns3::IpL4Protocol
virtual ~IpL4Protocol ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::IpL4Protocol
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static const uint8_t PROT_NUMBER = 17
protocol number (0x11)
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
virtual void NotifyNewAggregate ()
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
UdpL4Protocol (const UdpL4Protocol &)
Copy constructor.
UdpL4Protocol & operator= (const UdpL4Protocol &)
Copy constructor.
Private Attributes
IpL4Protocol::DownTargetCallback m_downTarget
Callback to send packets over IPv4.
IpL4Protocol::DownTargetCallback6 m_downTarget6
Callback to send packets over IPv6.
Ipv4EndPointDemux * m_endPoints
A list of IPv4 end points.
Ipv6EndPointDemux * m_endPoints6
A list of IPv6 end points.
Ptr< Node > m_node
the node this stack is associated with
std::vector< Ptr< UdpSocketImpl > > m_sockets
list of sockets
Additional Inherited Members
Public Types inherited from ns3::IpL4Protocol
typedef Callback< void, Ptr< Packet >, Ipv4Address, Ipv4Address, uint8_t, Ptr< Ipv4Route > > DownTargetCallback
callback to send packets over IPv4
typedef Callback< void, Ptr< Packet >, Ipv6Address, Ipv6Address, uint8_t, Ptr< Ipv6Route > > DownTargetCallback6
callback to send packets over IPv6
enum RxStatus { RX_OK , RX_CSUM_FAILED , RX_ENDPOINT_CLOSED , RX_ENDPOINT_UNREACH }
Rx status codes.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implementation of the UDP protocol.
Config Paths
ns3::UdpL4Protocol is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::UdpL4Protocol"
Attributes
SocketList: The list of sockets associated to this protocol.
Set with class: ns3::ObjectPtrContainerValue
Underlying type: ns3::Ptr< ns3::UdpSocketImpl>
Flags: read
Attributes defined in parent class ns3::IpL4Protocol
ProtocolNumber: The IP protocol number.
Set with class: ns3::IntegerValue
Underlying type: int32_t 0:255
Flags: read
No TraceSources are defined for this type.
Size of this type is 96 bytes (on a 64-bit architecture).
Definition at line 61 of file udp-l4-protocol.h.
Constructor & Destructor Documentation
UdpL4Protocol() [1/2]
ns3::UdpL4Protocol::UdpL4Protocol ()
Definition at line 67 of file udp-l4-protocol.cc.
References NS_LOG_FUNCTION.
~UdpL4Protocol()
ns3::UdpL4Protocol::~UdpL4Protocol () virtual
Definition at line 73 of file udp-l4-protocol.cc.
References NS_LOG_FUNCTION.
UdpL4Protocol() [2/2]
ns3::UdpL4Protocol::UdpL4Protocol (const UdpL4Protocol &) private
Copy constructor.
Defined and not implemented to avoid misuse
Member Function Documentation
Allocate() [1/5]
Ipv4EndPoint * ns3::UdpL4Protocol::Allocate (Ipv4Address address)
Allocate an IPv4 Endpoint.
Parameters
address address to use
Returns
the Endpoint
Definition at line 181 of file udp-l4-protocol.cc.
References first::address, ns3::Ipv4EndPointDemux::Allocate(), m_endPoints, and NS_LOG_FUNCTION.
Allocate() [2/5]
Ipv4EndPoint * ns3::UdpL4Protocol::Allocate (Ptr< NetDevice > boundNetDevice, Ipv4Address address, uint16_t port)
Allocate an IPv4 Endpoint.
Parameters
boundNetDevice Bound NetDevice (if any)
address address to use
port port to use
Returns
the Endpoint
Definition at line 195 of file udp-l4-protocol.cc.
References first::address, ns3::Ipv4EndPointDemux::Allocate(), m_endPoints, NS_LOG_FUNCTION, and port.
Allocate() [3/5]
Ipv4EndPoint * ns3::UdpL4Protocol::Allocate (Ptr< NetDevice > boundNetDevice, Ipv4Address localAddress, uint16_t localPort, Ipv4Address peerAddress, uint16_t peerPort)
Allocate an IPv4 Endpoint.
Parameters
boundNetDevice Bound NetDevice (if any)
localAddress local address to use
localPort local port to use
peerAddress remote address to use
peerPort remote port to use
Returns
the Endpoint
Definition at line 201 of file udp-l4-protocol.cc.
References ns3::Ipv4EndPointDemux::Allocate(), m_endPoints, and NS_LOG_FUNCTION.
Allocate() [4/5]
Ipv4EndPoint * ns3::UdpL4Protocol::Allocate (Ptr< NetDevice > boundNetDevice, uint16_t port)
Allocate an IPv4 Endpoint.
Parameters
boundNetDevice Bound NetDevice (if any)
port port to use
Returns
the Endpoint
Definition at line 188 of file udp-l4-protocol.cc.
References ns3::Ipv4EndPointDemux::Allocate(), m_endPoints, NS_LOG_FUNCTION, and port.
Allocate() [5/5]
Ipv4EndPoint * ns3::UdpL4Protocol::Allocate (void)
Allocate an IPv4 Endpoint.
Returns
the Endpoint
Definition at line 174 of file udp-l4-protocol.cc.
References ns3::Ipv4EndPointDemux::Allocate(), m_endPoints, and NS_LOG_FUNCTION.
Allocate6() [1/5]
Ipv6EndPoint * ns3::UdpL4Protocol::Allocate6 (Ipv6Address address)
Allocate an IPv6 Endpoint.
Parameters
address address to use
Returns
the Endpoint
Definition at line 226 of file udp-l4-protocol.cc.
References first::address, ns3::Ipv6EndPointDemux::Allocate(), m_endPoints6, and NS_LOG_FUNCTION.
Allocate6() [2/5]
Ipv6EndPoint * ns3::UdpL4Protocol::Allocate6 (Ptr< NetDevice > boundNetDevice, Ipv6Address address, uint16_t port)
Allocate an IPv6 Endpoint.
Parameters
boundNetDevice Bound NetDevice (if any)
address address to use
port port to use
Returns
the Endpoint
Definition at line 240 of file udp-l4-protocol.cc.
References first::address, ns3::Ipv6EndPointDemux::Allocate(), m_endPoints6, NS_LOG_FUNCTION, and port.
Allocate6() [3/5]
Ipv6EndPoint * ns3::UdpL4Protocol::Allocate6 (Ptr< NetDevice > boundNetDevice, Ipv6Address localAddress, uint16_t localPort, Ipv6Address peerAddress, uint16_t peerPort)
Allocate an IPv6 Endpoint.
Parameters
boundNetDevice Bound NetDevice (if any)
localAddress local address to use
localPort local port to use
peerAddress remote address to use
peerPort remote port to use
Returns
the Endpoint
Definition at line 246 of file udp-l4-protocol.cc.
References ns3::Ipv6EndPointDemux::Allocate(), m_endPoints6, and NS_LOG_FUNCTION.
Allocate6() [4/5]
Ipv6EndPoint * ns3::UdpL4Protocol::Allocate6 (Ptr< NetDevice > boundNetDevice, uint16_t port)
Allocate an IPv6 Endpoint.
Parameters
boundNetDevice Bound NetDevice (if any)
port port to use
Returns
the Endpoint
Definition at line 233 of file udp-l4-protocol.cc.
References ns3::Ipv6EndPointDemux::Allocate(), m_endPoints6, NS_LOG_FUNCTION, and port.
Allocate6() [5/5]
Ipv6EndPoint * ns3::UdpL4Protocol::Allocate6 (void)
Allocate an IPv6 Endpoint.
Returns
the Endpoint
Definition at line 219 of file udp-l4-protocol.cc.
References ns3::Ipv6EndPointDemux::Allocate(), m_endPoints6, and NS_LOG_FUNCTION.
CreateSocket()
Ptr< Socket > ns3::UdpL4Protocol::CreateSocket (void)
Returns
A smart Socket pointer to a UdpSocket, allocated by this instance of the UDP protocol
Definition at line 163 of file udp-l4-protocol.cc.
References m_node, m_sockets, and NS_LOG_FUNCTION.
DeAllocate() [1/2]
void ns3::UdpL4Protocol::DeAllocate (Ipv4EndPoint * endPoint)
Remove an IPv4 Endpoint.
Parameters
endPoint the end point to remove
Definition at line 212 of file udp-l4-protocol.cc.
References ns3::Ipv4EndPointDemux::DeAllocate(), m_endPoints, and NS_LOG_FUNCTION.
DeAllocate() [2/2]
void ns3::UdpL4Protocol::DeAllocate (Ipv6EndPoint * endPoint)
Remove an IPv6 Endpoint.
Parameters
endPoint the end point to remove
Definition at line 257 of file udp-l4-protocol.cc.
References ns3::Ipv6EndPointDemux::DeAllocate(), m_endPoints6, and NS_LOG_FUNCTION.
DoDispose()
void ns3::UdpL4Protocol::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 134 of file udp-l4-protocol.cc.
References ns3::Object::DoDispose(), m_downTarget, m_downTarget6, m_endPoints, m_endPoints6, m_node, m_sockets, NS_LOG_FUNCTION, and ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::Nullify().
GetDownTarget()
IpL4Protocol::DownTargetCallback ns3::UdpL4Protocol::GetDownTarget (void) const virtual
This method allows a caller to get the current down target callback set for this L4 protocol (IPv4 case)
Returns
current Callback for the L4 protocol
Implements ns3::IpL4Protocol.
Definition at line 515 of file udp-l4-protocol.cc.
References m_downTarget.
GetDownTarget6()
IpL4Protocol::DownTargetCallback6 ns3::UdpL4Protocol::GetDownTarget6 (void) const virtual
This method allows a caller to get the current down target callback set for this L4 protocol (IPv6 case)
Returns
current Callback for the L4 protocol
Implements ns3::IpL4Protocol.
Definition at line 528 of file udp-l4-protocol.cc.
References m_downTarget6.
GetProtocolNumber()
int ns3::UdpL4Protocol::GetProtocolNumber (void) const virtual
Returns the protocol number of this protocol.
Returns
the protocol number.
Implements ns3::IpL4Protocol.
Definition at line 127 of file udp-l4-protocol.cc.
References PROT_NUMBER.
GetTypeId()
TypeId ns3::UdpL4Protocol::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 53 of file udp-l4-protocol.cc.
References m_sockets, ns3::MakeObjectVectorAccessor(), and ns3::TypeId::SetParent().
NotifyNewAggregate()
void ns3::UdpL4Protocol::NotifyNewAggregate (void) protected virtual
Notify all Objects aggregated to this one of a new Object being aggregated.
This function must be implemented in the stack that needs to notify other stacks connected to the node of their presence in the node.
This method is invoked whenever two sets of Objects are aggregated together. It is invoked exactly once for each Object in both sets. This method can be overridden by subclasses who wish to be notified of aggregation events. These subclasses must chain up to their base class NotifyNewAggregate() method.
It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 90 of file udp-l4-protocol.cc.
References ns3::Object::AggregateObject(), ns3::Object::GetObject(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_downTarget, m_downTarget6, m_node, ns3::MakeCallback(), ns3::Object::NotifyNewAggregate(), NS_LOG_FUNCTION, ns3::Ipv4::Send(), ns3::Ipv6::Send(), SetDownTarget(), SetDownTarget6(), and SetNode().
operator=()
UdpL4Protocol& ns3::UdpL4Protocol::operator= (const UdpL4Protocol &) private
Copy constructor.
Defined and not implemented to avoid misuse
Returns
Receive() [1/2]
enum IpL4Protocol::RxStatus ns3::UdpL4Protocol::Receive (Ptr< Packet > p, Ipv4Header const & header, Ptr< Ipv4Interface > incomingInterface) virtual
Called from lower-level layers to send the packet up in the stack.
Parameters
p packet to forward up
header IPv4 Header information
incomingInterface the Ipv4Interface on which the packet arrived
Returns
Rx status code
Implements ns3::IpL4Protocol.
Definition at line 291 of file udp-l4-protocol.cc.
References ns3::Ipv6EndPoint::ForwardIcmp(), m_endPoints6, NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::Ipv6EndPointDemux::SimpleLookup().
Receive() [2/2]
enum IpL4Protocol::RxStatus ns3::UdpL4Protocol::Receive (Ptr< Packet > p, Ipv6Header const & header, Ptr< Ipv6Interface > incomingInterface) virtual
Called from lower-level layers to send the packet up in the stack.
Parameters
p packet to forward up
header IPv6 Header information
incomingInterface the Ipv6Interface on which the packet arrived
Returns
Rx status code
Implements ns3::IpL4Protocol.
Definition at line 291 of file udp-l4-protocol.cc.
ReceiveIcmp() [1/2]
void ns3::UdpL4Protocol::ReceiveIcmp (Ipv4Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo, Ipv4Address payloadSource, Ipv4Address payloadDestination, const uint8_t payload[8]) virtual
Called from lower-level layers to send the ICMP packet up in the stack.
Parameters
icmpSource the source address of the icmp message
icmpTtl the ttl of the icmp message
icmpType the 'type' field of the icmp message
icmpCode the 'code' field of the icmp message
icmpInfo extra information dependent on the icmp message generated by Icmpv4L4Protocol
payloadSource the source address of the packet which triggered the icmp message
payloadDestination the destination address of the packet which triggered the icmp message.
payload the first 8 bytes of the packet payload which triggered the icmp message.
Reimplemented from ns3::IpL4Protocol.
Definition at line 264 of file udp-l4-protocol.cc.
References ns3::Ipv4EndPoint::ForwardIcmp(), m_endPoints, NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::Ipv4EndPointDemux::SimpleLookup().
ReceiveIcmp() [2/2]
void ns3::UdpL4Protocol::ReceiveIcmp (Ipv6Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo, Ipv6Address payloadSource, Ipv6Address payloadDestination, const uint8_t payload[8]) virtual
Called from lower-level layers to send the ICMPv6 packet up in the stack.
Parameters
icmpSource the source address of the icmp message
icmpTtl the ttl of the icmp message
icmpType the 'type' field of the icmp message
icmpCode the 'code' field of the icmp message
icmpInfo extra information dependent on the icmp message generated by Icmpv6L4Protocol
payloadSource the source address of the packet which triggered the icmp message
payloadDestination the destination address of the packet which triggered the icmp message.
payload the first 8 bytes of the packet payload which triggered the icmp message.
Reimplemented from ns3::IpL4Protocol.
Definition at line 291 of file udp-l4-protocol.cc.
Send() [1/4]
void ns3::UdpL4Protocol::Send (Ptr< Packet > packet, Ipv4Address saddr, Ipv4Address daddr, uint16_t sport, uint16_t dport)
Send a packet via UDP (IPv4)
Parameters
packet The packet to send
saddr The source Ipv4Address
daddr The destination Ipv4Address
sport The source port number
dport The destination port number
Definition at line 416 of file udp-l4-protocol.cc.
References ns3::Packet::AddHeader(), ns3::Node::ChecksumEnabled(), ns3::UdpHeader::EnableChecksums(), ns3::UdpHeader::InitializeChecksum(), m_downTarget, NS_LOG_FUNCTION, PROT_NUMBER, ns3::UdpHeader::SetDestinationPort(), and ns3::UdpHeader::SetSourcePort().
Send() [2/4]
void ns3::UdpL4Protocol::Send (Ptr< Packet > packet, Ipv4Address saddr, Ipv4Address daddr, uint16_t sport, uint16_t dport, Ptr< Ipv4Route > route)
Send a packet via UDP (IPv4)
Parameters
packet The packet to send
saddr The source Ipv4Address
daddr The destination Ipv4Address
sport The source port number
dport The destination port number
route The route
Definition at line 439 of file udp-l4-protocol.cc.
References ns3::Packet::AddHeader(), ns3::Node::ChecksumEnabled(), ns3::UdpHeader::EnableChecksums(), ns3::UdpHeader::InitializeChecksum(), m_downTarget, NS_LOG_FUNCTION, PROT_NUMBER, ns3::UdpHeader::SetDestinationPort(), and ns3::UdpHeader::SetSourcePort().
Send() [3/4]
void ns3::UdpL4Protocol::Send (Ptr< Packet > packet, Ipv6Address saddr, Ipv6Address daddr, uint16_t sport, uint16_t dport)
Send a packet via UDP (IPv6)
Parameters
packet The packet to send
saddr The source Ipv4Address
daddr The destination Ipv4Address
sport The source port number
dport The destination port number
Definition at line 462 of file udp-l4-protocol.cc.
References ns3::Packet::AddHeader(), ns3::Node::ChecksumEnabled(), ns3::UdpHeader::EnableChecksums(), ns3::UdpHeader::InitializeChecksum(), m_downTarget6, NS_LOG_FUNCTION, PROT_NUMBER, ns3::UdpHeader::SetDestinationPort(), and ns3::UdpHeader::SetSourcePort().
Send() [4/4]
void ns3::UdpL4Protocol::Send (Ptr< Packet > packet, Ipv6Address saddr, Ipv6Address daddr, uint16_t sport, uint16_t dport, Ptr< Ipv6Route > route)
Send a packet via UDP (IPv6)
Parameters
packet The packet to send
saddr The source Ipv4Address
daddr The destination Ipv4Address
sport The source port number
dport The destination port number
route The route
Definition at line 485 of file udp-l4-protocol.cc.
References ns3::Packet::AddHeader(), ns3::Node::ChecksumEnabled(), ns3::UdpHeader::EnableChecksums(), ns3::UdpHeader::InitializeChecksum(), m_downTarget6, NS_LOG_FUNCTION, PROT_NUMBER, ns3::UdpHeader::SetDestinationPort(), and ns3::UdpHeader::SetSourcePort().
SetDownTarget()
void ns3::UdpL4Protocol::SetDownTarget (IpL4Protocol::DownTargetCallback cb) virtual
This method allows a caller to set the current down target callback set for this L4 protocol (IPv4 case)
Parameters
cb current Callback for the L4 protocol
Implements ns3::IpL4Protocol.
Definition at line 508 of file udp-l4-protocol.cc.
References m_downTarget, and NS_LOG_FUNCTION.
Referenced by NotifyNewAggregate().
SetDownTarget6()
void ns3::UdpL4Protocol::SetDownTarget6 (IpL4Protocol::DownTargetCallback6 cb) virtual
This method allows a caller to set the current down target callback set for this L4 protocol (IPv6 case)
Parameters
cb current Callback for the L4 protocol
Implements ns3::IpL4Protocol.
Definition at line 521 of file udp-l4-protocol.cc.
References m_downTarget6, and NS_LOG_FUNCTION.
Referenced by NotifyNewAggregate().
SetNode()
void ns3::UdpL4Protocol::SetNode (Ptr< Node > node)
Set node associated with this stack.
Parameters
node the node
Definition at line 79 of file udp-l4-protocol.cc.
References m_node.
Referenced by NotifyNewAggregate().
Member Data Documentation
m_downTarget
IpL4Protocol::DownTargetCallback ns3::UdpL4Protocol::m_downTarget private
Callback to send packets over IPv4.
Definition at line 275 of file udp-l4-protocol.h.
Referenced by DoDispose(), GetDownTarget(), NotifyNewAggregate(), Send(), and SetDownTarget().
m_downTarget6
IpL4Protocol::DownTargetCallback6 ns3::UdpL4Protocol::m_downTarget6 private
Callback to send packets over IPv6.
Definition at line 276 of file udp-l4-protocol.h.
Referenced by DoDispose(), GetDownTarget6(), NotifyNewAggregate(), Send(), and SetDownTarget6().
m_endPoints
Ipv4EndPointDemux* ns3::UdpL4Protocol::m_endPoints private
A list of IPv4 end points.
Definition at line 257 of file udp-l4-protocol.h.
Referenced by Allocate(), DeAllocate(), DoDispose(), and ReceiveIcmp().
m_endPoints6
Ipv6EndPointDemux* ns3::UdpL4Protocol::m_endPoints6 private
A list of IPv6 end points.
Definition at line 258 of file udp-l4-protocol.h.
Referenced by Allocate6(), DeAllocate(), DoDispose(), and Receive().
m_node
Ptr<Node> ns3::UdpL4Protocol::m_node private
the node this stack is associated with
Definition at line 256 of file udp-l4-protocol.h.
Referenced by CreateSocket(), DoDispose(), NotifyNewAggregate(), and SetNode().
m_sockets
std::vector<Ptr<UdpSocketImpl> > ns3::UdpL4Protocol::m_sockets private
list of sockets
Definition at line 274 of file udp-l4-protocol.h.
Referenced by CreateSocket(), DoDispose(), and GetTypeId().
PROT_NUMBER
const uint8_t ns3::UdpL4Protocol::PROT_NUMBER = 17 static
protocol number (0x11)
Definition at line 68 of file udp-l4-protocol.h.
Referenced by ns3::IpcsClassifier::Classify(), ns3::EpcTftClassifier::Classify(), ns3::olsr::HelloRegressionTest::CreateNodes(), ns3::olsr::TcRegressionTest::CreateNodes(), ns3::SixLowPanNetDevice::DecompressLowPanUdpNhc(), ns3::UdpSocketImpl::DoSendTo(), GetProtocolNumber(), ns3::aodv::RoutingProtocol::RouteInput(), and Send().
The documentation for this class was generated from the following files:
src/internet/model/udp-l4-protocol.h
src/internet/model/udp-l4-protocol.cc