ns-3: Bug772ChainTest Class Reference
Bug772ChainTest Class Reference
AODV Routing
AODV deferred route lookup test case (see Bug 772)
#include "bug-772.h"
Public Member Functions
Bug772ChainTest (const char *const prefix, const char *const proto, Time time, uint32_t size)
Create test case.
~Bug772ChainTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CheckResults ()
Compare traces with reference ones.
void CreateDevices ()
Create devices, install TCP/IP stack and applications.
void CreateNodes ()
Create test topology.
void DoRun ()
Go.
void HandleRead (Ptr< Socket > socket)
Receive data function.
void SendData (Ptr< Socket > socket)
Send data.
Private Attributes
NodeContainer * m_nodes
const uint16_t m_port
port number
const std::string m_prefix
PCAP file names prefix.
const std::string m_proto
Socket factory TID.
uint32_t m_receivedPackets
Received packet count.
Ptr< Socket > m_recvSocket
Receiving socket.
Ptr< Socket > m_sendSocket
Transmitting socket.
const uint32_t m_size
Chain size.
const double m_step
Chain step, meters.
const Time m_time
Total simulation time.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
AODV deferred route lookup test case (see Bug 772)
UDP packet transfers are delayed while a route is found and then while ARP completes. Eight packets should be sent, queued until the path becomes functional, and then delivered.
Definition at line 40 of file bug-772.h.
Constructor & Destructor Documentation
Bug772ChainTest()
Bug772ChainTest::Bug772ChainTest (const char *const prefix, const char *const proto, Time time, uint32_t size)
Create test case.
Parameters
prefix Unique file names prefix
proto ns3::UdpSocketFactory or ns3::TcpSocketFactory
size Number of nodes in the chain
time Simulation time
Definition at line 49 of file bug-772.cc.
~Bug772ChainTest()
Bug772ChainTest::~Bug772ChainTest ()
Definition at line 62 of file bug-772.cc.
References m_nodes.
Member Function Documentation
CheckResults()
void Bug772ChainTest::CheckResults () private
Compare traces with reference ones.
Definition at line 182 of file bug-772.cc.
References m_receivedPackets, and NS_TEST_EXPECT_MSG_EQ.
Referenced by DoRun().
CreateDevices()
void Bug772ChainTest::CreateDevices () private
Create devices, install TCP/IP stack and applications.
Definition at line 123 of file bug-772.cc.
References first::address, ns3::AodvHelper::AssignStreams(), ns3::InternetStackHelper::AssignStreams(), ns3::YansWifiChannelHelper::AssignStreams(), ns3::Socket::Bind(), ns3::Socket::Connect(), ns3::YansWifiChannelHelper::Create(), first::devices, ns3::WifiPhyHelper::DisablePreambleDetectionModel(), ns3::NodeContainer::Get(), ns3::Node::GetId(), ns3::Socket::GetNode(), HandleRead(), ns3::InternetStackHelper::Install(), first::interfaces, ns3::Socket::Listen(), m_nodes, m_port, m_proto, m_recvSocket, m_sendSocket, m_size, ns3::MakeCallback(), NS_TEST_ASSERT_MSG_EQ, ns3::Seconds(), SendData(), ns3::WifiPhyHelper::Set(), ns3::Socket::SetAllowBroadcast(), ns3::YansWifiPhyHelper::SetChannel(), ns3::WifiPhyHelper::SetErrorRateModel(), ns3::Socket::SetRecvCallback(), ns3::InternetStackHelper::SetRoutingHelper(), ns3::WifiMacHelper::SetType(), ns3::Socket::ShutdownSend(), and third::wifi.
Referenced by DoRun().
CreateNodes()
void Bug772ChainTest::CreateNodes () private
Create test topology.
Definition at line 106 of file bug-772.cc.
References ns3::NodeContainer::Create(), m_nodes, m_size, m_step, and third::mobility.
Referenced by DoRun().
DoRun()
void Bug772ChainTest::DoRun (void) private virtual
Go.
Implements ns3::TestCase.
Definition at line 85 of file bug-772.cc.
References CheckResults(), CreateDevices(), CreateNodes(), m_nodes, m_time, ns3::Seconds(), and ns3::Config::SetDefault().
HandleRead()
void Bug772ChainTest::HandleRead (Ptr< Socket > socket) private
Receive data function.
Parameters
socket the socket to receive from
Definition at line 79 of file bug-772.cc.
References m_receivedPackets.
Referenced by CreateDevices().
SendData()
void Bug772ChainTest::SendData (Ptr< Socket > socket) private
Send data.
Parameters
socket the sending socket
Definition at line 68 of file bug-772.cc.
References ns3::Node::GetId(), ns3::Socket::GetNode(), m_time, ns3::Now(), ns3::Seconds(), and ns3::Socket::Send().
Referenced by CreateDevices().
Member Data Documentation
m_nodes
NodeContainer* Bug772ChainTest::m_nodes private
Internal: It is important to have pointers here
Definition at line 56 of file bug-772.h.
Referenced by ~Bug772ChainTest(), CreateDevices(), CreateNodes(), and DoRun().
m_port
const uint16_t Bug772ChainTest::m_port private
port number
Definition at line 69 of file bug-772.h.
Referenced by CreateDevices().
m_prefix
const std::string Bug772ChainTest::m_prefix private
PCAP file names prefix.
Definition at line 59 of file bug-772.h.
m_proto
const std::string Bug772ChainTest::m_proto private
Socket factory TID.
Definition at line 61 of file bug-772.h.
Referenced by CreateDevices().
m_receivedPackets
uint32_t Bug772ChainTest::m_receivedPackets private
Received packet count.
Definition at line 91 of file bug-772.h.
Referenced by CheckResults(), and HandleRead().
m_recvSocket
Ptr<Socket> Bug772ChainTest::m_recvSocket private
Receiving socket.
Definition at line 86 of file bug-772.h.
Referenced by CreateDevices().
m_sendSocket
Ptr<Socket> Bug772ChainTest::m_sendSocket private
Transmitting socket.
Definition at line 88 of file bug-772.h.
Referenced by CreateDevices().
m_size
const uint32_t Bug772ChainTest::m_size private
Chain size.
Definition at line 65 of file bug-772.h.
Referenced by CreateDevices(), and CreateNodes().
m_step
const double Bug772ChainTest::m_step private
Chain step, meters.
Definition at line 67 of file bug-772.h.
Referenced by CreateNodes().
m_time
const Time Bug772ChainTest::m_time private
Total simulation time.
Definition at line 63 of file bug-772.h.
Referenced by DoRun(), and SendData().
The documentation for this class was generated from the following files:
src/aodv/test/bug-772.h
src/aodv/test/bug-772.cc