ns-3: ns3::CtrlBAckResponseHeader Class Reference
ns3::CtrlBAckResponseHeader Class Reference
Wifi Models
Headers for BlockAck response.
#include "ctrl-headers.h"
Public Member Functions
CtrlBAckResponseHeader ()
~CtrlBAckResponseHeader ()
uint32_t Deserialize (Buffer::Iterator start)
const uint16_t * GetBitmap (void) const
Return the bitmap from the BlockAck response header.
uint64_t GetCompressedBitmap (void) const
Return the compressed bitmap from the BlockAck response header.
const uint64_t * GetExtendedCompressedBitmap (void) const
Return the extended compressed bitmap from the BlockAck response header.
TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint32_t GetSerializedSize (void) const
uint16_t GetStartingSequence (void) const
Return the starting sequence number.
uint16_t GetStartingSequenceControl (void) const
Return the starting sequence control.
uint8_t GetTidInfo (void) const
Return the Traffic ID (TID).
BlockAckType GetType (void) const
Return the block ack type ID.
bool IsBasic (void) const
Check if the current BA policy is Basic Block Ack.
bool IsCompressed (void) const
Check if the current BA policy is Compressed Block Ack.
bool IsExtendedCompressed (void) const
Check if the current BA policy is Extended Compressed Block Ack.
bool IsFragmentReceived (uint16_t seq, uint8_t frag) const
Check if the packet with the given sequence number and fragment number was acknowledged in this BlockAck response.
bool IsMultiTid (void) const
Check if the current BA policy is Multi-TID Block Ack.
bool IsPacketReceived (uint16_t seq) const
Check if the packet with the given sequence number was acknowledged in this BlockAck response.
bool MustSendHtImmediateAck (void) const
Check if the current Ack Policy is immediate.
void Print (std::ostream &os) const
void ResetBitmap (void)
Reset the bitmap to 0.
void Serialize (Buffer::Iterator start) const
void SetHtImmediateAck (bool immediateAck)
Enable or disable HT immediate Ack.
void SetReceivedFragment (uint16_t seq, uint8_t frag)
Set the bitmap that the packet with the given sequence number and fragment number was received.
void SetReceivedPacket (uint16_t seq)
Set the bitmap that the packet with the given sequence number was received.
void SetStartingSequence (uint16_t seq)
Set the starting sequence number from the given raw sequence control field.
void SetStartingSequenceControl (uint16_t seqControl)
Set the starting sequence control with the given sequence control value.
void SetTidInfo (uint8_t tid)
Set Traffic ID (TID).
void SetType (BlockAckType type)
Set the block ack type.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
Buffer::Iterator DeserializeBitmap (Buffer::Iterator start)
Deserialize bitmap from the given buffer.
uint16_t GetBaControl (void) const
Return the Block Ack control.
uint16_t IndexInBitmap (uint16_t seq) const
This function is used to correctly index in both bitmap and compressed bitmap, one bit or one block of 16 bits respectively.
bool IsInBitmap (uint16_t seq) const
Checks if sequence number seq can be acknowledged in the bitmap.
Buffer::Iterator SerializeBitmap (Buffer::Iterator start) const
Serialize bitmap to the given buffer.
void SetBaControl (uint16_t ba)
Set the Block Ack control.
Private Attributes
union {
uint16_t m_bitmap [64]
the basic BlockAck bitmap
uint64_t m_compressedBitmap
the compressed BlockAck bitmap
uint64_t m_extendedCompressedBitmap [4]
the extended compressed BlockAck bitmap
} bitmap
bitmap union type
bool m_baAckPolicy
The LSB bit of the BA control field is used only for the HT (High Throughput) delayed block ack configuration.
BlockAckType m_baType
BA type.
uint16_t m_startingSeq
starting sequence number
uint16_t m_tidInfo
TID info.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Headers for BlockAck response.
Introspection did not find any typical Config paths.
802.11n standard includes three types of BlockAck:
Basic BlockAck (unique type in 802.11e)
Compressed BlockAck
Multi-TID BlockAck For now only basic BlockAck and compressed BlockAck are supported. Basic BlockAck is also default variant.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 152 bytes (on a 64-bit architecture).
Definition at line 193 of file ctrl-headers.h.
Constructor & Destructor Documentation
CtrlBAckResponseHeader()
ns3::CtrlBAckResponseHeader::CtrlBAckResponseHeader ()
Definition at line 270 of file ctrl-headers.cc.
References bitmap.
~CtrlBAckResponseHeader()
ns3::CtrlBAckResponseHeader::~CtrlBAckResponseHeader ()
Definition at line 277 of file ctrl-headers.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::CtrlBAckResponseHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 353 of file ctrl-headers.cc.
References ns3::BASIC_BLOCK_ACK, ns3::COMPRESSED_BLOCK_ACK, DeserializeBitmap(), ns3::EXTENDED_COMPRESSED_BLOCK_ACK, ns3::Buffer::Iterator::GetDistanceFrom(), m_baType, ns3::MULTI_TID_BLOCK_ACK, NS_FATAL_ERROR, ns3::Buffer::Iterator::ReadLsbtohU16(), SetBaControl(), SetStartingSequenceControl(), and visualizer.core::start().
DeserializeBitmap()
Buffer::Iterator ns3::CtrlBAckResponseHeader::DeserializeBitmap (Buffer::Iterator start) private
Deserialize bitmap from the given buffer.
Parameters
start the iterator
Returns
Buffer::Iterator to the next available buffer
Definition at line 544 of file ctrl-headers.cc.
References ns3::BASIC_BLOCK_ACK, bitmap, ns3::COMPRESSED_BLOCK_ACK, ns3::EXTENDED_COMPRESSED_BLOCK_ACK, m_baType, ns3::MULTI_TID_BLOCK_ACK, NS_FATAL_ERROR, ns3::Buffer::Iterator::ReadLsbtohU16(), ns3::Buffer::Iterator::ReadLsbtohU64(), and visualizer.core::start().
Referenced by Deserialize().
GetBaControl()
uint16_t ns3::CtrlBAckResponseHeader::GetBaControl (void) const private
Return the Block Ack control.
Returns
the Block Ack control
Definition at line 449 of file ctrl-headers.cc.
References ns3::BASIC_BLOCK_ACK, ns3::COMPRESSED_BLOCK_ACK, ns3::EXTENDED_COMPRESSED_BLOCK_ACK, m_baAckPolicy, m_baType, m_tidInfo, ns3::MULTI_TID_BLOCK_ACK, and NS_FATAL_ERROR.
Referenced by Serialize().
GetBitmap()
const uint16_t * ns3::CtrlBAckResponseHeader::GetBitmap (void) const
Return the bitmap from the BlockAck response header.
Returns
the bitmap from the BlockAck response header
Definition at line 762 of file ctrl-headers.cc.
References bitmap.
GetCompressedBitmap()
uint64_t ns3::CtrlBAckResponseHeader::GetCompressedBitmap (void) const
Return the compressed bitmap from the BlockAck response header.
Returns
the compressed bitmap from the BlockAck response header
Definition at line 768 of file ctrl-headers.cc.
References bitmap.
Referenced by CtrlBAckResponseHeaderTest::DoRun().
GetExtendedCompressedBitmap()
const uint64_t * ns3::CtrlBAckResponseHeader::GetExtendedCompressedBitmap (void) const
Return the extended compressed bitmap from the BlockAck response header.
Returns
the extended compressed bitmap from the BlockAck response header
Definition at line 774 of file ctrl-headers.cc.
References bitmap.
GetInstanceTypeId()
TypeId ns3::CtrlBAckResponseHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 293 of file ctrl-headers.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::CtrlBAckResponseHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 305 of file ctrl-headers.cc.
References ns3::BASIC_BLOCK_ACK, ns3::COMPRESSED_BLOCK_ACK, ns3::EXTENDED_COMPRESSED_BLOCK_ACK, m_baType, m_tidInfo, ns3::MULTI_TID_BLOCK_ACK, and NS_FATAL_ERROR.
Referenced by ns3::GetBlockAckSize().
GetStartingSequence()
uint16_t ns3::CtrlBAckResponseHeader::GetStartingSequence (void) const
Return the starting sequence number.
Returns
the starting sequence number
Definition at line 419 of file ctrl-headers.cc.
References m_startingSeq.
Referenced by ns3::BlockAckCache::FillBlockAckBitmap().
GetStartingSequenceControl()
uint16_t ns3::CtrlBAckResponseHeader::GetStartingSequenceControl (void) const
Return the starting sequence control.
Returns
the starting sequence control
Definition at line 501 of file ctrl-headers.cc.
References m_startingSeq.
Referenced by Serialize().
GetTidInfo()
uint8_t ns3::CtrlBAckResponseHeader::GetTidInfo (void) const
Return the Traffic ID (TID).
Returns
TID
Definition at line 412 of file ctrl-headers.cc.
References m_tidInfo.
Referenced by ns3::GetTid(), ns3::QosTxop::NeedBarRetransmission(), and ns3::BlockAckManager::NotifyGotBlockAck().
GetType()
BlockAckType ns3::CtrlBAckResponseHeader::GetType (void) const
Return the block ack type ID.
Returns
type
Definition at line 388 of file ctrl-headers.cc.
References m_baType.
Referenced by ns3::MacLow::SendBlockAckResponse().
GetTypeId()
TypeId ns3::CtrlBAckResponseHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 282 of file ctrl-headers.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
IndexInBitmap()
uint16_t ns3::CtrlBAckResponseHeader::IndexInBitmap (uint16_t seq) const private
This function is used to correctly index in both bitmap and compressed bitmap, one bit or one block of 16 bits respectively.
for more details see 7.2.1.8 in IEEE 802.11n/D4.00
Parameters
seq the sequence number
Returns
If we are using basic block ack, return value represents index of block of 16 bits for packet having sequence number equals to seq. If we are using compressed block ack, return value represents bit to set to 1 in the compressed bitmap to indicate that packet having sequence number equals to seq was correctly received.
Definition at line 726 of file ctrl-headers.cc.
References ns3::EXTENDED_COMPRESSED_BLOCK_ACK, m_baType, m_startingSeq, and NS_ASSERT.
Referenced by IsFragmentReceived(), IsPacketReceived(), SetReceivedFragment(), and SetReceivedPacket().
IsBasic()
bool ns3::CtrlBAckResponseHeader::IsBasic (void) const
Check if the current BA policy is Basic Block Ack.
Returns
true if the current BA policy is Basic Block Ack, false otherwise
Definition at line 425 of file ctrl-headers.cc.
References ns3::BASIC_BLOCK_ACK, and m_baType.
Referenced by ns3::BlockAckCache::FillBlockAckBitmap(), and ns3::BlockAckManager::NotifyGotBlockAck().
IsCompressed()
bool ns3::CtrlBAckResponseHeader::IsCompressed (void) const
Check if the current BA policy is Compressed Block Ack.
Returns
true if the current BA policy is Compressed Block Ack, false otherwise
Definition at line 431 of file ctrl-headers.cc.
References ns3::COMPRESSED_BLOCK_ACK, and m_baType.
Referenced by ns3::BlockAckCache::FillBlockAckBitmap(), and ns3::BlockAckManager::NotifyGotBlockAck().
IsExtendedCompressed()
bool ns3::CtrlBAckResponseHeader::IsExtendedCompressed (void) const
Check if the current BA policy is Extended Compressed Block Ack.
Returns
true if the current BA policy is Extended Compressed Block Ack, false otherwise
Definition at line 437 of file ctrl-headers.cc.
References ns3::EXTENDED_COMPRESSED_BLOCK_ACK, and m_baType.
Referenced by ns3::BlockAckCache::FillBlockAckBitmap(), and ns3::BlockAckManager::NotifyGotBlockAck().
IsFragmentReceived()
bool ns3::CtrlBAckResponseHeader::IsFragmentReceived (uint16_t seq, uint8_t frag) const
Check if the packet with the given sequence number and fragment number was acknowledged in this BlockAck response.
Parameters
seq the sequence number
frag the fragment number
Returns
true if the packet with the given sequence number and sequence number was acknowledged in this BlockAck response, false otherwise
Definition at line 684 of file ctrl-headers.cc.
References ns3::BASIC_BLOCK_ACK, bitmap, ns3::COMPRESSED_BLOCK_ACK, ns3::EXTENDED_COMPRESSED_BLOCK_ACK, IndexInBitmap(), IsInBitmap(), m_baType, ns3::MULTI_TID_BLOCK_ACK, NS_ASSERT, and NS_FATAL_ERROR.
Referenced by ns3::BlockAckManager::NotifyGotBlockAck().
IsInBitmap()
bool ns3::CtrlBAckResponseHeader::IsInBitmap (uint16_t seq) const private
Checks if sequence number seq can be acknowledged in the bitmap.
Parameters
seq the sequence number
Returns
true if the sequence number is concerned by the bitmap
Definition at line 749 of file ctrl-headers.cc.
References ns3::EXTENDED_COMPRESSED_BLOCK_ACK, m_baType, and m_startingSeq.
Referenced by IsFragmentReceived(), IsPacketReceived(), SetReceivedFragment(), and SetReceivedPacket().
IsMultiTid()
bool ns3::CtrlBAckResponseHeader::IsMultiTid (void) const
Check if the current BA policy is Multi-TID Block Ack.
Returns
true if the current BA policy is Multi-TID Block Ack, false otherwise
Definition at line 443 of file ctrl-headers.cc.
References m_baType, and ns3::MULTI_TID_BLOCK_ACK.
Referenced by ns3::BlockAckCache::FillBlockAckBitmap(), and ns3::BlockAckManager::NotifyGotBlockAck().
IsPacketReceived()
bool ns3::CtrlBAckResponseHeader::IsPacketReceived (uint16_t seq) const
Check if the packet with the given sequence number was acknowledged in this BlockAck response.
Parameters
seq the sequence number
Returns
true if the packet with the given sequence number was ACKed in this BlockAck response, false otherwise
Definition at line 642 of file ctrl-headers.cc.
References ns3::BASIC_BLOCK_ACK, bitmap, ns3::COMPRESSED_BLOCK_ACK, ns3::EXTENDED_COMPRESSED_BLOCK_ACK, IndexInBitmap(), IsInBitmap(), m_baType, ns3::MULTI_TID_BLOCK_ACK, and NS_FATAL_ERROR.
Referenced by CtrlBAckResponseHeaderTest::DoRun(), and ns3::BlockAckManager::NotifyGotBlockAck().
MustSendHtImmediateAck()
bool ns3::CtrlBAckResponseHeader::MustSendHtImmediateAck (void) const
Check if the current Ack Policy is immediate.
Returns
true if the current Ack Policy is immediate, false otherwise
Definition at line 406 of file ctrl-headers.cc.
References m_baAckPolicy.
Print()
void ns3::CtrlBAckResponseHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 299 of file ctrl-headers.cc.
References m_startingSeq, and m_tidInfo.
ResetBitmap()
void ns3::CtrlBAckResponseHeader::ResetBitmap (void)
Reset the bitmap to 0.
Definition at line 780 of file ctrl-headers.cc.
References bitmap.
Referenced by CtrlBAckResponseHeaderTest::DoRun().
Serialize()
void ns3::CtrlBAckResponseHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 331 of file ctrl-headers.cc.
References ns3::BASIC_BLOCK_ACK, ns3::COMPRESSED_BLOCK_ACK, ns3::EXTENDED_COMPRESSED_BLOCK_ACK, GetBaControl(), GetStartingSequenceControl(), m_baType, ns3::MULTI_TID_BLOCK_ACK, NS_FATAL_ERROR, SerializeBitmap(), visualizer.core::start(), and ns3::Buffer::Iterator::WriteHtolsbU16().
SerializeBitmap()
Buffer::Iterator ns3::CtrlBAckResponseHeader::SerializeBitmap (Buffer::Iterator start) const private
Serialize bitmap to the given buffer.
Parameters
start the iterator
Returns
Buffer::Iterator to the next available buffer
Definition at line 513 of file ctrl-headers.cc.
References ns3::BASIC_BLOCK_ACK, bitmap, ns3::COMPRESSED_BLOCK_ACK, ns3::EXTENDED_COMPRESSED_BLOCK_ACK, m_baType, ns3::MULTI_TID_BLOCK_ACK, NS_FATAL_ERROR, visualizer.core::start(), ns3::Buffer::Iterator::WriteHtolsbU16(), and ns3::Buffer::Iterator::WriteHtolsbU64().
Referenced by Serialize().
SetBaControl()
void ns3::CtrlBAckResponseHeader::SetBaControl (uint16_t ba) private
Set the Block Ack control.
Parameters
ba the BA control to set
Definition at line 478 of file ctrl-headers.cc.
References ns3::BASIC_BLOCK_ACK, ns3::COMPRESSED_BLOCK_ACK, ns3::EXTENDED_COMPRESSED_BLOCK_ACK, m_baAckPolicy, m_baType, m_tidInfo, and ns3::MULTI_TID_BLOCK_ACK.
Referenced by Deserialize().
SetHtImmediateAck()
void ns3::CtrlBAckResponseHeader::SetHtImmediateAck (bool immediateAck)
Enable or disable HT immediate Ack.
Parameters
immediateAck enable or disable HT immediate Ack
Definition at line 376 of file ctrl-headers.cc.
References m_baAckPolicy.
SetReceivedFragment()
void ns3::CtrlBAckResponseHeader::SetReceivedFragment (uint16_t seq, uint8_t frag)
Set the bitmap that the packet with the given sequence number and fragment number was received.
Parameters
seq the sequence number
frag the fragment number
Definition at line 615 of file ctrl-headers.cc.
References ns3::BASIC_BLOCK_ACK, bitmap, ns3::COMPRESSED_BLOCK_ACK, ns3::EXTENDED_COMPRESSED_BLOCK_ACK, IndexInBitmap(), IsInBitmap(), m_baType, ns3::MULTI_TID_BLOCK_ACK, NS_ASSERT, and NS_FATAL_ERROR.
SetReceivedPacket()
void ns3::CtrlBAckResponseHeader::SetReceivedPacket (uint16_t seq)
Set the bitmap that the packet with the given sequence number was received.
Parameters
seq the sequence number
Definition at line 575 of file ctrl-headers.cc.
References ns3::BASIC_BLOCK_ACK, bitmap, ns3::COMPRESSED_BLOCK_ACK, ns3::EXTENDED_COMPRESSED_BLOCK_ACK, IndexInBitmap(), IsInBitmap(), m_baType, ns3::MULTI_TID_BLOCK_ACK, and NS_FATAL_ERROR.
Referenced by CtrlBAckResponseHeaderTest::DoRun(), and ns3::BlockAckCache::FillBlockAckBitmap().
SetStartingSequence()
void ns3::CtrlBAckResponseHeader::SetStartingSequence (uint16_t seq)
Set the starting sequence number from the given raw sequence control field.
Parameters
seq the raw sequence control
Definition at line 400 of file ctrl-headers.cc.
References m_startingSeq.
Referenced by CtrlBAckResponseHeaderTest::DoRun(), ns3::MacLow::SendBlockAckAfterAmpdu(), and ns3::MacLow::SendBlockAckAfterBlockAckRequest().
SetStartingSequenceControl()
void ns3::CtrlBAckResponseHeader::SetStartingSequenceControl (uint16_t seqControl)
Set the starting sequence control with the given sequence control value.
Parameters
seqControl the raw sequence control value
Definition at line 507 of file ctrl-headers.cc.
References m_startingSeq.
Referenced by Deserialize().
SetTidInfo()
void ns3::CtrlBAckResponseHeader::SetTidInfo (uint8_t tid)
Set Traffic ID (TID).
Parameters
tid the TID
Definition at line 394 of file ctrl-headers.cc.
References m_tidInfo.
Referenced by ns3::MacLow::SendBlockAckAfterAmpdu(), and ns3::MacLow::SendBlockAckAfterBlockAckRequest().
SetType()
void ns3::CtrlBAckResponseHeader::SetType (BlockAckType type)
Set the block ack type.
Parameters
type the BA type
Definition at line 382 of file ctrl-headers.cc.
References m_baType.
Referenced by CtrlBAckResponseHeaderTest::DoRun(), ns3::GetBlockAckSize(), ns3::MacLow::SendBlockAckAfterAmpdu(), and ns3::MacLow::SendBlockAckAfterBlockAckRequest().
Member Data Documentation
union { ... } ns3::CtrlBAckResponseHeader::bitmap
bitmap union type
Referenced by CtrlBAckResponseHeader(), DeserializeBitmap(), GetBitmap(), GetCompressedBitmap(), GetExtendedCompressedBitmap(), IsFragmentReceived(), IsPacketReceived(), ResetBitmap(), SerializeBitmap(), SetReceivedFragment(), and SetReceivedPacket().
m_baAckPolicy
bool ns3::CtrlBAckResponseHeader::m_baAckPolicy private
The LSB bit of the BA control field is used only for the HT (High Throughput) delayed block ack configuration.
For now only non HT immediate block ack is implemented so this field is here only for a future implementation of HT delayed variant. BA Ack Policy
Definition at line 423 of file ctrl-headers.h.
Referenced by GetBaControl(), MustSendHtImmediateAck(), SetBaControl(), and SetHtImmediateAck().
m_baType
BlockAckType ns3::CtrlBAckResponseHeader::m_baType private
BA type.
Definition at line 424 of file ctrl-headers.h.
Referenced by Deserialize(), DeserializeBitmap(), GetBaControl(), GetSerializedSize(), GetType(), IndexInBitmap(), IsBasic(), IsCompressed(), IsExtendedCompressed(), IsFragmentReceived(), IsInBitmap(), IsMultiTid(), IsPacketReceived(), Serialize(), SerializeBitmap(), SetBaControl(), SetReceivedFragment(), SetReceivedPacket(), and SetType().
m_bitmap
uint16_t ns3::CtrlBAckResponseHeader::m_bitmap[64]
the basic BlockAck bitmap
Definition at line 430 of file ctrl-headers.h.
m_compressedBitmap
uint64_t ns3::CtrlBAckResponseHeader::m_compressedBitmap
the compressed BlockAck bitmap
Definition at line 431 of file ctrl-headers.h.
m_extendedCompressedBitmap
uint64_t ns3::CtrlBAckResponseHeader::m_extendedCompressedBitmap[4]
the extended compressed BlockAck bitmap
Definition at line 432 of file ctrl-headers.h.
m_startingSeq
uint16_t ns3::CtrlBAckResponseHeader::m_startingSeq private
starting sequence number
Definition at line 426 of file ctrl-headers.h.
Referenced by GetStartingSequence(), GetStartingSequenceControl(), IndexInBitmap(), IsInBitmap(), Print(), SetStartingSequence(), and SetStartingSequenceControl().
m_tidInfo
uint16_t ns3::CtrlBAckResponseHeader::m_tidInfo private
TID info.
Definition at line 425 of file ctrl-headers.h.
Referenced by GetBaControl(), GetSerializedSize(), GetTidInfo(), Print(), SetBaControl(), and SetTidInfo().
The documentation for this class was generated from the following files:
src/wifi/model/ctrl-headers.h
src/wifi/model/ctrl-headers.cc