ns-3: ns3::PcapHelperForDevice Class Reference
ns3::PcapHelperForDevice Class Reference abstract
Base class providing common user-level pcap operations for helpers representing net devices.
#include "trace-helper.h"
Public Member Functions
PcapHelperForDevice ()
Construct a PcapHelperForDevice.
virtual ~PcapHelperForDevice ()
Destroy a PcapHelperForDevice.
void EnablePcap (std::string prefix, NetDeviceContainer d, bool promiscuous=false)
Enable pcap output on each device in the container which is of the appropriate type.
void EnablePcap (std::string prefix, NodeContainer n, bool promiscuous=false)
Enable pcap output on each device (which is of the appropriate type) in the nodes provided in the container.
void EnablePcap (std::string prefix, Ptr< NetDevice > nd, bool promiscuous=false, bool explicitFilename=false)
Enable pcap output the indicated net device.
void EnablePcap (std::string prefix, std::string ndName, bool promiscuous=false, bool explicitFilename=false)
Enable pcap output the indicated net device using a device previously named using the ns-3 object name service.
void EnablePcap (std::string prefix, uint32_t nodeid, uint32_t deviceid, bool promiscuous=false)
Enable pcap output on the device specified by a global node-id (of a previously created node) and associated device-id.
void EnablePcapAll (std::string prefix, bool promiscuous=false)
Enable pcap output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
virtual void EnablePcapInternal (std::string prefix, Ptr< NetDevice > nd, bool promiscuous, bool explicitFilename)=0
Enable pcap output the indicated net device.
Detailed Description
Base class providing common user-level pcap operations for helpers representing net devices.
Definition at line 552 of file trace-helper.h.
Constructor & Destructor Documentation
PcapHelperForDevice()
ns3::PcapHelperForDevice::PcapHelperForDevice () inline
Construct a PcapHelperForDevice.
Definition at line 558 of file trace-helper.h.
~PcapHelperForDevice()
virtual ns3::PcapHelperForDevice::~PcapHelperForDevice () inline virtual
Destroy a PcapHelperForDevice.
Definition at line 563 of file trace-helper.h.
Member Function Documentation
EnablePcap() [1/5]
void ns3::PcapHelperForDevice::EnablePcap (std::string prefix, NetDeviceContainer d, bool promiscuous = false)
Enable pcap output on each device in the container which is of the appropriate type.
Parameters
prefix Filename prefix to use for pcap files.
d container of devices of type ns3::CsmaNetDevice
promiscuous If true capture all possible packets available at the device.
Definition at line 414 of file trace-helper.cc.
References ns3::NetDeviceContainer::Begin(), EnablePcap(), and ns3::NetDeviceContainer::End().
EnablePcap() [2/5]
void ns3::PcapHelperForDevice::EnablePcap (std::string prefix, NodeContainer n, bool promiscuous = false)
Enable pcap output on each device (which is of the appropriate type) in the nodes provided in the container.
Parameters
prefix Filename prefix to use for pcap files.
n container of nodes.
promiscuous If true capture all possible packets available at the device.
Definition at line 424 of file trace-helper.cc.
References ns3::NetDeviceContainer::Add(), EnablePcap(), ns3::Node::GetDevice(), ns3::Node::GetNDevices(), and sample-rng-plot::n.
EnablePcap() [3/5]
void ns3::PcapHelperForDevice::EnablePcap (std::string prefix, Ptr< NetDevice > nd, bool promiscuous = false, bool explicitFilename = false)
Enable pcap output the indicated net device.
Parameters
prefix Filename prefix to use for pcap files.
nd Net device for which you want to enable tracing.
promiscuous If true capture all possible packets available at the device.
explicitFilename Treat the prefix as an explicit filename if true
Definition at line 401 of file trace-helper.cc.
References EnablePcapInternal().
Referenced by WaveNetDeviceExample::CreateWaveNodes(), WifiMsduAggregatorThroughputTest::DoRun(), EnablePcap(), and EnablePcapAll().
EnablePcap() [4/5]
void ns3::PcapHelperForDevice::EnablePcap (std::string prefix, std::string ndName, bool promiscuous = false, bool explicitFilename = false)
Enable pcap output the indicated net device using a device previously named using the ns-3 object name service.
Parameters
prefix filename prefix to use for pcap files.
ndName The name of the net device in which you want to enable tracing.
promiscuous If true capture all possible packets available at the device.
explicitFilename Treat the prefix as an explicit filename if true
Definition at line 407 of file trace-helper.cc.
References EnablePcap().
EnablePcap() [5/5]
void ns3::PcapHelperForDevice::EnablePcap (std::string prefix, uint32_t nodeid, uint32_t deviceid, bool promiscuous = false)
Enable pcap output on the device specified by a global node-id (of a previously created node) and associated device-id.
Parameters
prefix Filename prefix to use for pcap files.
nodeid the node id
deviceid the device id
promiscuous If true capture all possible packets available at the device.
Definition at line 445 of file trace-helper.cc.
References EnablePcap(), ns3::Node::GetDevice(), ns3::NodeContainer::GetGlobal(), ns3::Node::GetId(), ns3::Node::GetNDevices(), sample-rng-plot::n, and NS_ABORT_MSG_IF.
EnablePcapAll()
void ns3::PcapHelperForDevice::EnablePcapAll (std::string prefix, bool promiscuous = false)
Enable pcap output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
Parameters
prefix Filename prefix to use for pcap files.
promiscuous If true capture all possible packets available at the device.
Definition at line 439 of file trace-helper.cc.
References EnablePcap(), and ns3::NodeContainer::GetGlobal().
Referenced by ns3::PointToPointEpcHelper::AddEnb(), ns3::NoBackhaulEpcHelper::AddX2Interface(), AodvExample::CreateDevices(), ChainRegressionTest::CreateDevices(), TracerouteExample::CreateDevices(), HwmpProactiveRegressionTest::CreateDevices(), HwmpReactiveRegressionTest::CreateDevices(), HwmpSimplestRegressionTest::CreateDevices(), HwmpDoRfRegressionTest::CreateDevices(), PeerManagementProtocolRegressionTest::CreateDevices(), FlameRegressionTest::CreateDevices(), DsdvManetExample::CreateDevices(), MeshTest::CreateNodes(), Ns3TcpLossTestCase::DoRun(), Ns3TcpStateTestCase::DoRun(), and VanetRoutingExperiment::SetupAdhocDevices().
EnablePcapInternal()
virtual void ns3::PcapHelperForDevice::EnablePcapInternal (std::string prefix, Ptr< NetDevice > nd, bool promiscuous, bool explicitFilename) pure virtual
Enable pcap output the indicated net device.
Parameters
prefix Filename prefix to use for pcap files.
nd Net device for which you want to enable tracing.
promiscuous If true capture all possible packets available at the device.
explicitFilename Treat the prefix as an explicit filename if true
Implemented in ns3::WifiPhyHelper, ns3::YansWavePhyHelper, ns3::PointToPointHelper, ns3::LrWpanHelper, ns3::FdNetDeviceHelper, ns3::CsmaHelper, and ns3::WimaxHelper.
Referenced by EnablePcap().
The documentation for this class was generated from the following files:
src/network/helper/trace-helper.h
src/network/helper/trace-helper.cc