ns-3: ns3::PointToPointStarHelper Class Reference
ns3::PointToPointStarHelper Class Reference
Point-to-Point Layout Helpers
A helper to make it easier to create a star topology with PointToPoint links.
#include "point-to-point-star.h"
Public Member Functions
PointToPointStarHelper (uint32_t numSpokes, PointToPointHelper p2pHelper)
Create a PointToPointStarHelper in order to easily create star topologies using p2p links.
~PointToPointStarHelper ()
void AssignIpv4Addresses (Ipv4AddressHelper address)
void AssignIpv6Addresses (Ipv6Address network, Ipv6Prefix prefix)
void BoundingBox (double ulx, double uly, double lrx, double lry)
Sets up the node canvas locations for every node in the star.
Ptr< Node > GetHub () const
Ipv4Address GetHubIpv4Address (uint32_t i) const
Ipv6Address GetHubIpv6Address (uint32_t i) const
Ipv4Address GetSpokeIpv4Address (uint32_t i) const
Ipv6Address GetSpokeIpv6Address (uint32_t i) const
Ptr< Node > GetSpokeNode (uint32_t i) const
void InstallStack (InternetStackHelper stack)
uint32_t SpokeCount () const
Private Attributes
NodeContainer m_hub
Hub node.
NetDeviceContainer m_hubDevices
Hub node NetDevices.
Ipv4InterfaceContainer m_hubInterfaces
IPv4 hub interfaces.
Ipv6InterfaceContainer m_hubInterfaces6
IPv6 hub interfaces.
NetDeviceContainer m_spokeDevices
Spoke nodes NetDevices.
Ipv4InterfaceContainer m_spokeInterfaces
IPv4 spoke nodes interfaces.
Ipv6InterfaceContainer m_spokeInterfaces6
IPv6 spoke nodes interfaces.
NodeContainer m_spokes
Spoke nodes.
Detailed Description
A helper to make it easier to create a star topology with PointToPoint links.
Definition at line 44 of file point-to-point-star.h.
Constructor & Destructor Documentation
PointToPointStarHelper()
ns3::PointToPointStarHelper::PointToPointStarHelper (uint32_t numSpokes, PointToPointHelper p2pHelper)
Create a PointToPointStarHelper in order to easily create star topologies using p2p links.
Parameters
numSpokes the number of links attached to the hub node, creating a total of numSpokes + 1 nodes
p2pHelper the link helper for p2p links, used to link nodes together
Definition at line 37 of file point-to-point-star.cc.
References ns3::NetDeviceContainer::Add(), ns3::NodeContainer::Create(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::NodeContainer::GetN(), ns3::PointToPointHelper::Install(), m_hub, m_hubDevices, m_spokeDevices, and m_spokes.
~PointToPointStarHelper()
ns3::PointToPointStarHelper::~PointToPointStarHelper ()
Definition at line 51 of file point-to-point-star.cc.
Member Function Documentation
AssignIpv4Addresses()
void ns3::PointToPointStarHelper::AssignIpv4Addresses (Ipv4AddressHelper address)
Parameters
address an Ipv4AddressHelper which is used to install Ipv4 addresses on all the node interfaces in the star
Definition at line 105 of file point-to-point-star.cc.
References ns3::Ipv4InterfaceContainer::Add(), first::address, ns3::NetDeviceContainer::Get(), ns3::NodeContainer::GetN(), m_hubDevices, m_hubInterfaces, m_spokeDevices, m_spokeInterfaces, and m_spokes.
AssignIpv6Addresses()
void ns3::PointToPointStarHelper::AssignIpv6Addresses (Ipv6Address network, Ipv6Prefix prefix)
Parameters
network an IPv6 address representing the network portion of the IPv6 Address
prefix the prefix length
Definition at line 116 of file point-to-point-star.cc.
References ns3::Ipv6InterfaceContainer::Add(), ns3::Ipv6AddressHelper::Assign(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::GetN(), ns3::Ipv6AddressGenerator::GetNetwork(), ns3::Ipv6AddressGenerator::Init(), m_hubDevices, m_hubInterfaces6, m_spokeDevices, m_spokeInterfaces6, m_spokes, ns3::Ipv6AddressGenerator::NextNetwork(), and ns3::Ipv6AddressHelper::SetBase().
BoundingBox()
void ns3::PointToPointStarHelper::BoundingBox (double ulx, double uly, double lrx, double lry)
Sets up the node canvas locations for every node in the star.
This is needed for use with the animation interface
Parameters
ulx upper left x value
uly upper left y value
lrx lower right x value
lry lower right y value
Definition at line 137 of file point-to-point-star.cc.
References ns3::Object::AggregateObject(), ns3::NodeContainer::Get(), ns3::NodeContainer::GetN(), ns3::Object::GetObject(), m_hub, and m_spokes.
GetHub()
Ptr< Node > ns3::PointToPointStarHelper::GetHub () const
Returns
a node pointer to the hub node in the star, i.e., the center node
Definition at line 56 of file point-to-point-star.cc.
References ns3::NodeContainer::Get(), and m_hub.
GetHubIpv4Address()
Ipv4Address ns3::PointToPointStarHelper::GetHubIpv4Address (uint32_t i) const
Parameters
i index into the hub interfaces
Returns
Ipv4Address according to indexed hub interface
Definition at line 68 of file point-to-point-star.cc.
References ns3::Ipv4InterfaceContainer::GetAddress(), and m_hubInterfaces.
GetHubIpv6Address()
Ipv6Address ns3::PointToPointStarHelper::GetHubIpv6Address (uint32_t i) const
Parameters
i index into the hub interfaces
Returns
Ipv6Address according to indexed hub interface
Definition at line 80 of file point-to-point-star.cc.
References ns3::Ipv6InterfaceContainer::GetAddress(), and m_hubInterfaces6.
GetSpokeIpv4Address()
Ipv4Address ns3::PointToPointStarHelper::GetSpokeIpv4Address (uint32_t i) const
Parameters
i index into the spoke interfaces
Returns
Ipv4Address according to indexed spoke interface
Definition at line 74 of file point-to-point-star.cc.
References ns3::Ipv4InterfaceContainer::GetAddress(), and m_spokeInterfaces.
GetSpokeIpv6Address()
Ipv6Address ns3::PointToPointStarHelper::GetSpokeIpv6Address (uint32_t i) const
Parameters
i index into the spoke interfaces
Returns
Ipv6Address according to indexed spoke interface
Definition at line 86 of file point-to-point-star.cc.
References ns3::Ipv6InterfaceContainer::GetAddress(), and m_spokeInterfaces6.
GetSpokeNode()
Ptr< Node > ns3::PointToPointStarHelper::GetSpokeNode (uint32_t i) const
Parameters
i an index into the spokes of the star
Returns
a node pointer to the node at the indexed spoke
Definition at line 62 of file point-to-point-star.cc.
References ns3::NodeContainer::Get(), and m_spokes.
InstallStack()
void ns3::PointToPointStarHelper::InstallStack (InternetStackHelper stack)
Parameters
stack an InternetStackHelper which is used to install on every node in the star
Definition at line 98 of file point-to-point-star.cc.
References m_hub, m_spokes, and first::stack.
SpokeCount()
uint32_t ns3::PointToPointStarHelper::SpokeCount () const
Returns
the total number of spokes in the star
Definition at line 92 of file point-to-point-star.cc.
References ns3::NodeContainer::GetN(), and m_spokes.
Member Data Documentation
m_hub
NodeContainer ns3::PointToPointStarHelper::m_hub private
Hub node.
Definition at line 142 of file point-to-point-star.h.
Referenced by PointToPointStarHelper(), BoundingBox(), GetHub(), and InstallStack().
m_hubDevices
NetDeviceContainer ns3::PointToPointStarHelper::m_hubDevices private
Hub node NetDevices.
Definition at line 143 of file point-to-point-star.h.
Referenced by PointToPointStarHelper(), AssignIpv4Addresses(), and AssignIpv6Addresses().
m_hubInterfaces
Ipv4InterfaceContainer ns3::PointToPointStarHelper::m_hubInterfaces private
IPv4 hub interfaces.
Definition at line 146 of file point-to-point-star.h.
Referenced by AssignIpv4Addresses(), and GetHubIpv4Address().
m_hubInterfaces6
Ipv6InterfaceContainer ns3::PointToPointStarHelper::m_hubInterfaces6 private
IPv6 hub interfaces.
Definition at line 148 of file point-to-point-star.h.
Referenced by AssignIpv6Addresses(), and GetHubIpv6Address().
m_spokeDevices
NetDeviceContainer ns3::PointToPointStarHelper::m_spokeDevices private
Spoke nodes NetDevices.
Definition at line 145 of file point-to-point-star.h.
Referenced by PointToPointStarHelper(), AssignIpv4Addresses(), and AssignIpv6Addresses().
m_spokeInterfaces
Ipv4InterfaceContainer ns3::PointToPointStarHelper::m_spokeInterfaces private
IPv4 spoke nodes interfaces.
Definition at line 147 of file point-to-point-star.h.
Referenced by AssignIpv4Addresses(), and GetSpokeIpv4Address().
m_spokeInterfaces6
Ipv6InterfaceContainer ns3::PointToPointStarHelper::m_spokeInterfaces6 private
IPv6 spoke nodes interfaces.
Definition at line 149 of file point-to-point-star.h.
Referenced by AssignIpv6Addresses(), and GetSpokeIpv6Address().
m_spokes
NodeContainer ns3::PointToPointStarHelper::m_spokes private
Spoke nodes.
Definition at line 144 of file point-to-point-star.h.
Referenced by PointToPointStarHelper(), AssignIpv4Addresses(), AssignIpv6Addresses(), BoundingBox(), GetSpokeNode(), InstallStack(), and SpokeCount().
The documentation for this class was generated from the following files:
src/point-to-point-layout/model/point-to-point-star.h
src/point-to-point-layout/model/point-to-point-star.cc