ns-3: ns3::UdpHeader Class Reference
ns3::UdpHeader Class Reference
Internet » UDP
Packet header for UDP packets.
#include "udp-header.h"
Public Member Functions
UdpHeader ()
Constructor.
~UdpHeader ()
virtual uint32_t Deserialize (Buffer::Iterator start)
void EnableChecksums (void)
Enable checksum calculation for UDP.
void ForceChecksum (uint16_t checksum)
Force the UDP checksum to a given value.
void ForcePayloadSize (uint16_t payloadSize)
Force the UDP payload length to a given value.
uint16_t GetChecksum ()
Return the checksum (only known after a Deserialize)
uint16_t GetDestinationPort (void) const
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize (void) const
uint16_t GetSourcePort (void) const
void InitializeChecksum (Address source, Address destination, uint8_t protocol)
void InitializeChecksum (Ipv4Address source, Ipv4Address destination, uint8_t protocol)
void InitializeChecksum (Ipv6Address source, Ipv6Address destination, uint8_t protocol)
bool IsChecksumOk (void) const
Is the UDP checksum correct ?
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetDestinationPort (uint16_t port)
void SetSourcePort (uint16_t port)
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
uint16_t CalculateHeaderChecksum (uint16_t size) const
Calculate the header checksum.
Private Attributes
bool m_calcChecksum
Flag to calculate checksum.
uint16_t m_checksum
Forced Checksum value.
Address m_destination
Destination IP address.
uint16_t m_destinationPort
Destination port.
bool m_goodChecksum
Flag to indicate that checksum is correct.
uint16_t m_payloadSize
Payload size.
uint8_t m_protocol
Protocol number.
Address m_source
Source IP address.
uint16_t m_sourcePort
Source port.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Packet header for UDP packets.
Introspection did not find any typical Config paths.
This class has fields corresponding to those in a network UDP header (port numbers, payload size, checksum) as well as methods for serialization to and deserialization from a byte buffer.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 64 bytes (on a 64-bit architecture).
Definition at line 39 of file udp-header.h.
Constructor & Destructor Documentation
UdpHeader()
ns3::UdpHeader::UdpHeader ()
Constructor.
Creates a null header
Definition at line 32 of file udp-header.cc.
~UdpHeader()
ns3::UdpHeader::~UdpHeader ()
Definition at line 41 of file udp-header.cc.
References m_destinationPort, m_payloadSize, and m_sourcePort.
Member Function Documentation
CalculateHeaderChecksum()
uint16_t ns3::UdpHeader::CalculateHeaderChecksum (uint16_t size) const private
Calculate the header checksum.
Parameters
size packet size
Returns
the checksum
Definition at line 102 of file udp-header.cc.
References ns3::Buffer::AddAtStart(), ns3::Buffer::Begin(), ns3::Buffer::Iterator::CalculateIpChecksum(), ns3::Ipv4Address::IsMatchingType(), ns3::Ipv6Address::IsMatchingType(), m_destination, m_protocol, m_source, ns3::Address::MAX_SIZE, ns3::WriteTo(), ns3::Buffer::Iterator::WriteU16(), and ns3::Buffer::Iterator::WriteU8().
Referenced by Deserialize(), and Serialize().
Deserialize()
uint32_t ns3::UdpHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 220 of file udp-header.cc.
References CalculateHeaderChecksum(), ns3::Buffer::Iterator::CalculateIpChecksum(), GetSerializedSize(), m_calcChecksum, m_checksum, m_destinationPort, m_goodChecksum, m_payloadSize, m_sourcePort, ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadU16(), and visualizer.core::start().
EnableChecksums()
void ns3::UdpHeader::EnableChecksums (void)
Enable checksum calculation for UDP.
Definition at line 49 of file udp-header.cc.
References m_calcChecksum.
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanUdpNhc(), and ns3::UdpL4Protocol::Send().
ForceChecksum()
void ns3::UdpHeader::ForceChecksum (uint16_t checksum)
Force the UDP checksum to a given value.
This might be useful for test purposes or to restore the UDP checksum when the UDP header has been compressed (e.g., in 6LoWPAN). Note that, normally, the header checksum is calculated on the fly when the packet is serialized.
When this option is used, the UDP checksum is written in the header, regardless of the global ChecksumEnabled option.
Note
The checksum value must be a big endian number.
Parameters
checksum the checksum to use (big endian).
Definition at line 142 of file udp-header.cc.
References m_checksum.
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanUdpNhc().
ForcePayloadSize()
void ns3::UdpHeader::ForcePayloadSize (uint16_t payloadSize)
Force the UDP payload length to a given value.
This might be useful when forging a packet for test purposes.
Parameters
payloadSize the payload length to use.
Definition at line 148 of file udp-header.cc.
References m_payloadSize.
GetChecksum()
uint16_t ns3::UdpHeader::GetChecksum ()
Return the checksum (only known after a Deserialize)
Returns
The checksum for this UdpHeader
Definition at line 241 of file udp-header.cc.
References m_checksum.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanUdpNhc().
GetDestinationPort()
uint16_t ns3::UdpHeader::GetDestinationPort (void) const
Returns
the destination port for this UdpHeader
Definition at line 70 of file udp-header.cc.
References m_destinationPort.
Referenced by LteIpv6RoutingTestCase::Checker(), ns3::IpcsClassifier::Classify(), ns3::EpcTftClassifier::Classify(), ns3::SixLowPanNetDevice::CompressLowPanUdpNhc(), ns3::Ipv4QueueDiscItem::Hash(), ns3::Ipv6QueueDiscItem::Hash(), and ns3::aodv::RoutingProtocol::RouteInput().
GetInstanceTypeId()
TypeId ns3::UdpHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 164 of file udp-header.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::UdpHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 178 of file udp-header.cc.
Referenced by Deserialize(), ns3::Rip::DoSendRouteUpdate(), ns3::RipNg::DoSendRouteUpdate(), ns3::Rip::HandleRequests(), ns3::RipNg::HandleRequests(), and Print().
GetSourcePort()
uint16_t ns3::UdpHeader::GetSourcePort (void) const
Returns
The source port for this UdpHeader
Definition at line 65 of file udp-header.cc.
References m_sourcePort.
Referenced by LteIpv6RoutingTestCase::Checker(), ns3::IpcsClassifier::Classify(), ns3::EpcTftClassifier::Classify(), ns3::SixLowPanNetDevice::CompressLowPanUdpNhc(), ns3::Ipv4QueueDiscItem::Hash(), and ns3::Ipv6QueueDiscItem::Hash().
GetTypeId()
TypeId ns3::UdpHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 154 of file udp-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
InitializeChecksum() [1/3]
void ns3::UdpHeader::InitializeChecksum (Address source, Address destination, uint8_t protocol)
Parameters
source the ip source to use in the underlying ip packet.
destination the ip destination to use in the underlying ip packet.
protocol the protocol number to use in the underlying ip packet.
If you want to use udp checksums, you should call this method prior to adding the header to a packet.
Definition at line 75 of file udp-header.cc.
References m_destination, m_protocol, and m_source.
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanUdpNhc(), and ns3::UdpL4Protocol::Send().
InitializeChecksum() [2/3]
void ns3::UdpHeader::InitializeChecksum (Ipv4Address source, Ipv4Address destination, uint8_t protocol)
Parameters
source the ip source to use in the underlying ip packet.
destination the ip destination to use in the underlying ip packet.
protocol the protocol number to use in the underlying ip packet.
If you want to use udp checksums, you should call this method prior to adding the header to a packet.
Definition at line 84 of file udp-header.cc.
References m_destination, m_protocol, and m_source.
InitializeChecksum() [3/3]
void ns3::UdpHeader::InitializeChecksum (Ipv6Address source, Ipv6Address destination, uint8_t protocol)
Parameters
source the ip source to use in the underlying ip packet.
destination the ip destination to use in the underlying ip packet.
protocol the protocol number to use in the underlying ip packet.
If you want to use udp checksums, you should call this method prior to adding the header to a packet.
Definition at line 93 of file udp-header.cc.
References m_destination, m_protocol, and m_source.
IsChecksumOk()
bool ns3::UdpHeader::IsChecksumOk (void) const
Is the UDP checksum correct ?
Returns
true if the checksum is correct, false otherwise.
Definition at line 136 of file udp-header.cc.
References m_goodChecksum.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanUdpNhc(), and ns3::SixLowPanNetDevice::DecompressLowPanUdpNhc().
Print()
void ns3::UdpHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 169 of file udp-header.cc.
References GetSerializedSize(), m_destinationPort, m_payloadSize, and m_sourcePort.
Serialize()
void ns3::UdpHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 184 of file udp-header.cc.
References CalculateHeaderChecksum(), ns3::Buffer::Iterator::CalculateIpChecksum(), m_calcChecksum, m_checksum, m_destinationPort, m_payloadSize, m_sourcePort, ns3::Buffer::Iterator::Next(), visualizer.core::start(), ns3::Buffer::Iterator::WriteHtonU16(), and ns3::Buffer::Iterator::WriteU16().
SetDestinationPort()
void ns3::UdpHeader::SetDestinationPort (uint16_t port)
Parameters
port the destination port for this UdpHeader
Definition at line 55 of file udp-header.cc.
References m_destinationPort, and port.
Referenced by EpcTftClassifierTestCase::EpcTftClassifierTestCase(), ns3::SixLowPanNetDevice::DecompressLowPanUdpNhc(), FqCoDelQueueDiscUDPFlowsSeparation::DoRun(), and ns3::UdpL4Protocol::Send().
SetSourcePort()
void ns3::UdpHeader::SetSourcePort (uint16_t port)
Parameters
port The source port for this UdpHeader
Definition at line 60 of file udp-header.cc.
References m_sourcePort, and port.
Referenced by EpcTftClassifierTestCase::EpcTftClassifierTestCase(), ns3::SixLowPanNetDevice::DecompressLowPanUdpNhc(), FqCoDelQueueDiscUDPFlowsSeparation::DoRun(), and ns3::UdpL4Protocol::Send().
Member Data Documentation
m_calcChecksum
bool ns3::UdpHeader::m_calcChecksum private
Flag to calculate checksum.
Definition at line 184 of file udp-header.h.
Referenced by Deserialize(), EnableChecksums(), and Serialize().
m_checksum
uint16_t ns3::UdpHeader::m_checksum private
Forced Checksum value.
Definition at line 183 of file udp-header.h.
Referenced by Deserialize(), ForceChecksum(), GetChecksum(), and Serialize().
m_destination
Address ns3::UdpHeader::m_destination private
Destination IP address.
Definition at line 181 of file udp-header.h.
Referenced by CalculateHeaderChecksum(), and InitializeChecksum().
m_destinationPort
uint16_t ns3::UdpHeader::m_destinationPort private
Destination port.
Definition at line 177 of file udp-header.h.
Referenced by ~UdpHeader(), Deserialize(), GetDestinationPort(), Print(), Serialize(), and SetDestinationPort().
m_goodChecksum
bool ns3::UdpHeader::m_goodChecksum private
Flag to indicate that checksum is correct.
Definition at line 185 of file udp-header.h.
Referenced by Deserialize(), and IsChecksumOk().
m_payloadSize
uint16_t ns3::UdpHeader::m_payloadSize private
Payload size.
Definition at line 178 of file udp-header.h.
Referenced by ~UdpHeader(), Deserialize(), ForcePayloadSize(), Print(), and Serialize().
m_protocol
uint8_t ns3::UdpHeader::m_protocol private
Protocol number.
Definition at line 182 of file udp-header.h.
Referenced by CalculateHeaderChecksum(), and InitializeChecksum().
m_source
Address ns3::UdpHeader::m_source private
Source IP address.
Definition at line 180 of file udp-header.h.
Referenced by CalculateHeaderChecksum(), and InitializeChecksum().
m_sourcePort
uint16_t ns3::UdpHeader::m_sourcePort private
Source port.
Definition at line 176 of file udp-header.h.
Referenced by ~UdpHeader(), Deserialize(), GetSourcePort(), Print(), Serialize(), and SetSourcePort().
The documentation for this class was generated from the following files:
src/internet/model/udp-header.h
src/internet/model/udp-header.cc