ns-3: ConfigStoreHelper Class Reference
ConfigStoreHelper Class Reference
WAVE module
The ConfigStoreHelper class simplifies config-store raw text load and save.
Public Member Functions
ConfigStoreHelper ()
Constructor.
void LoadConfig (std::string configFilename)
Loads a saved config-store raw text configuration from a given named file.
void SaveConfig (std::string configFilename)
Saves a configuration to a given named config-store raw text configuration file.
Detailed Description
The ConfigStoreHelper class simplifies config-store raw text load and save.
Definition at line 1018 of file vanet-routing-compare.cc.
Constructor & Destructor Documentation
ConfigStoreHelper()
ConfigStoreHelper::ConfigStoreHelper ()
Constructor.
Returns
none
Definition at line 1042 of file vanet-routing-compare.cc.
Member Function Documentation
LoadConfig()
void ConfigStoreHelper::LoadConfig (std::string configFilename)
Loads a saved config-store raw text configuration from a given named file.
Parameters
configFilename the name of the config-store raw text file
Returns
none
Definition at line 1047 of file vanet-routing-compare.cc.
References ns3::ConfigStore::ConfigureDefaults(), and ns3::Config::SetDefault().
Referenced by VanetRoutingExperiment::CommandSetup().
SaveConfig()
void ConfigStoreHelper::SaveConfig (std::string configFilename)
Saves a configuration to a given named config-store raw text configuration file.
Parameters
configFilename the name of the config-store raw text file
Returns
none
Definition at line 1059 of file vanet-routing-compare.cc.
References ns3::ConfigStore::ConfigureDefaults(), and ns3::Config::SetDefault().
Referenced by VanetRoutingExperiment::ParseCommandLineArguments().
The documentation for this class was generated from the following file:
src/wave/examples/vanet-routing-compare.cc