ns-3: ns3::dsr::DsrLinkStab Class Reference
ns3::dsr::DsrLinkStab Class Reference
DsrLinkStab class (DSR link stability)
#include "dsr-rcache.h"
Public Member Functions
DsrLinkStab (Time linkStab=Simulator::Now())
Constructor.
virtual ~DsrLinkStab ()
Destructor.
Time GetLinkStability () const
get the link stability
void Print () const
Print function.
void SetLinkStability (Time linkStab)
set the link stability
Private Attributes
Time m_linkStability
The link stability lifetime expected, when the time is due, the link expires the expiration happens when purge the node and link cache before update them when receiving new information.
Detailed Description
DsrLinkStab class (DSR link stability)
Definition at line 140 of file dsr-rcache.h.
Constructor & Destructor Documentation
DsrLinkStab()
ns3::dsr::DsrLinkStab::DsrLinkStab (Time linkStab = Simulator::Now ())
Constructor.
Parameters
linkStab duration of the link stability
Definition at line 90 of file dsr-rcache.cc.
~DsrLinkStab()
ns3::dsr::DsrLinkStab::~DsrLinkStab () virtual
Destructor.
Definition at line 95 of file dsr-rcache.cc.
Member Function Documentation
GetLinkStability()
Time ns3::dsr::DsrLinkStab::GetLinkStability () const inline
get the link stability
Returns
remaining duration of the link stability
Definition at line 165 of file dsr-rcache.h.
References m_linkStability, and ns3::Simulator::Now().
Referenced by ns3::dsr::DsrRouteCache::AddRoute_Link(), and Print().
Print()
void ns3::dsr::DsrLinkStab::Print (void) const
Print function.
Definition at line 99 of file dsr-rcache.cc.
References GetLinkStability(), NS_LOG_LOGIC, and ns3::Time::S.
Referenced by ns3::dsr::DsrRouteCache::AddRoute_Link().
SetLinkStability()
void ns3::dsr::DsrLinkStab::SetLinkStability (Time linkStab) inline
set the link stability
Parameters
linkStab duration of the link stability
Definition at line 157 of file dsr-rcache.h.
References m_linkStability, and ns3::Simulator::Now().
Referenced by ns3::dsr::DsrRouteCache::AddRoute_Link().
Member Data Documentation
m_linkStability
Time ns3::dsr::DsrLinkStab::m_linkStability private
The link stability lifetime expected, when the time is due, the link expires the expiration happens when purge the node and link cache before update them when receiving new information.
Definition at line 178 of file dsr-rcache.h.
Referenced by GetLinkStability(), and SetLinkStability().
The documentation for this class was generated from the following files:
src/dsr/model/dsr-rcache.h
src/dsr/model/dsr-rcache.cc