ns-3: ns3::ErpInformation Class Reference
ns3::ErpInformation Class Reference
Wifi Models
The ErpInformation Information Element.
#include "erp-information.h"
Public Member Functions
ErpInformation ()
uint8_t DeserializeInformationField (Buffer::Iterator start, uint8_t length)
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
WifiInformationElementId ElementId () const
uint8_t GetBarkerPreambleMode (void) const
Return the Barker_Preamble_Mode field in the ErpInformation information element.
uint8_t GetInformationFieldSize () const
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
uint8_t GetNonErpPresent (void) const
Return the Non_Erp_Present field in the ErpInformation information element.
uint16_t GetSerializedSize () const
uint8_t GetUseProtection (void) const
Return the Use_Protection field in the ErpInformation information element.
Buffer::Iterator Serialize (Buffer::Iterator start) const
void SerializeInformationField (Buffer::Iterator start) const
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
void SetBarkerPreambleMode (uint8_t barkerPreambleMode)
Set the Barker_Preamble_Mode field in the ErpInformation information element.
void SetErpSupported (uint8_t erpSupported)
Set the ERP supported field.
void SetNonErpPresent (uint8_t nonErpPresent)
Set the Non_Erp_Present field in the ErpInformation information element.
void SetUseProtection (uint8_t useProtection)
Set the Use_Protection field in the ErpInformation information element.
Public Member Functions inherited from ns3::WifiInformationElement
virtual ~WifiInformationElement ()
Buffer::Iterator Deserialize (Buffer::Iterator i)
Deserialize entire IE, which must be present.
Buffer::Iterator DeserializeIfPresent (Buffer::Iterator i)
Deserialize entire IE if it is present.
virtual WifiInformationElementId ElementIdExt () const
uint16_t GetSerializedSize () const
Get the size of the serialized IE including Element ID and length fields.
virtual bool operator== (WifiInformationElement const &a) const
Compare two IEs for equality by ID & Length, and then through memcmp of serialised version.
virtual void Print (std::ostream &os) const
Generate human-readable form of IE.
Buffer::Iterator Serialize (Buffer::Iterator i) const
Serialize entire IE including Element ID and length fields.
Public Member Functions inherited from ns3::SimpleRefCount< WifiInformationElement >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
uint8_t m_erpInformation
ERP information.
bool m_erpSupported
This is used to decide whether this element should be added to the frame or not.
Detailed Description
The ErpInformation Information Element.
This class knows how to serialise and deserialise the ErpInformation Information Element.
Definition at line 34 of file erp-information.h.
Constructor & Destructor Documentation
ErpInformation()
ns3::ErpInformation::ErpInformation ()
Definition at line 25 of file erp-information.cc.
Member Function Documentation
DeserializeInformationField()
uint8_t ns3::ErpInformation::DeserializeInformationField (Buffer::Iterator start, uint8_t length) virtual
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
length
Returns
the number of bytes read
Implements ns3::WifiInformationElement.
Definition at line 116 of file erp-information.cc.
References m_erpInformation, ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
ElementId()
WifiInformationElementId ns3::ErpInformation::ElementId () const virtual
Returns
Own unique Element ID
Implements ns3::WifiInformationElement.
Definition at line 32 of file erp-information.cc.
References IE_ERP_INFORMATION.
GetBarkerPreambleMode()
uint8_t ns3::ErpInformation::GetBarkerPreambleMode (void) const
Return the Barker_Preamble_Mode field in the ErpInformation information element.
Returns
the Barker_Preamble_Mode field in the ErpInformation information element
Definition at line 62 of file erp-information.cc.
References m_erpInformation.
Referenced by ns3::operator<<(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), ns3::StaWifiMac::UpdateApInfoFromBeacon(), and ns3::StaWifiMac::UpdateApInfoFromProbeResp().
GetInformationFieldSize()
uint8_t ns3::ErpInformation::GetInformationFieldSize () const virtual
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
This is the value that will appear in the second octet of the entire IE - the length field)
Returns
the length of serialized information
Implements ns3::WifiInformationElement.
Definition at line 80 of file erp-information.cc.
References m_erpSupported, and NS_ASSERT.
GetNonErpPresent()
uint8_t ns3::ErpInformation::GetNonErpPresent (void) const
Return the Non_Erp_Present field in the ErpInformation information element.
Returns
the Non_Erp_Present field in the ErpInformation information element
Definition at line 74 of file erp-information.cc.
References m_erpInformation.
Referenced by ns3::operator<<().
GetSerializedSize()
uint16_t ns3::ErpInformation::GetSerializedSize (void) const
Definition at line 97 of file erp-information.cc.
References ns3::WifiInformationElement::GetSerializedSize(), and m_erpSupported.
Referenced by ns3::MgtAssocResponseHeader::GetSerializedSize(), and ns3::MgtProbeResponseHeader::GetSerializedSize().
GetUseProtection()
uint8_t ns3::ErpInformation::GetUseProtection (void) const
Return the Use_Protection field in the ErpInformation information element.
Returns
the Use_Protection field in the ErpInformation information element
Definition at line 68 of file erp-information.cc.
References m_erpInformation.
Referenced by ns3::operator<<(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
Serialize()
Buffer::Iterator ns3::ErpInformation::Serialize (Buffer::Iterator start) const
Definition at line 87 of file erp-information.cc.
References m_erpSupported, and ns3::WifiInformationElement::Serialize().
Referenced by ns3::MgtAssocResponseHeader::Serialize(), and ns3::MgtProbeResponseHeader::Serialize().
SerializeInformationField()
void ns3::ErpInformation::SerializeInformationField (Buffer::Iterator start) const virtual
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
Implements ns3::WifiInformationElement.
Definition at line 107 of file erp-information.cc.
References m_erpInformation, m_erpSupported, and visualizer.core::start().
SetBarkerPreambleMode()
void ns3::ErpInformation::SetBarkerPreambleMode (uint8_t barkerPreambleMode)
Set the Barker_Preamble_Mode field in the ErpInformation information element.
Parameters
barkerPreambleMode the Barker_Preamble_Mode field in the ErpInformation information element
Definition at line 44 of file erp-information.cc.
References m_erpInformation.
Referenced by ns3::ApWifiMac::GetErpInformation().
SetErpSupported()
void ns3::ErpInformation::SetErpSupported (uint8_t erpSupported)
Set the ERP supported field.
Parameters
erpSupported the ERP supported field in the ErpInformation information element
Definition at line 38 of file erp-information.cc.
References m_erpSupported.
Referenced by ns3::ApWifiMac::GetErpInformation().
SetNonErpPresent()
void ns3::ErpInformation::SetNonErpPresent (uint8_t nonErpPresent)
Set the Non_Erp_Present field in the ErpInformation information element.
Parameters
nonErpPresent the Non_Erp_Present field in the ErpInformation information element
Definition at line 56 of file erp-information.cc.
References m_erpInformation.
Referenced by ns3::ApWifiMac::GetErpInformation().
SetUseProtection()
void ns3::ErpInformation::SetUseProtection (uint8_t useProtection)
Set the Use_Protection field in the ErpInformation information element.
Parameters
useProtection the Use_Protection field in the ErpInformation information element
Definition at line 50 of file erp-information.cc.
References m_erpInformation.
Referenced by ns3::ApWifiMac::GetErpInformation().
Member Data Documentation
m_erpInformation
uint8_t ns3::ErpInformation::m_erpInformation private
ERP information.
Definition at line 100 of file erp-information.h.
Referenced by DeserializeInformationField(), GetBarkerPreambleMode(), GetNonErpPresent(), GetUseProtection(), SerializeInformationField(), SetBarkerPreambleMode(), SetNonErpPresent(), and SetUseProtection().
m_erpSupported
bool ns3::ErpInformation::m_erpSupported private
This is used to decide whether this element should be added to the frame or not.
Definition at line 103 of file erp-information.h.
Referenced by GetInformationFieldSize(), GetSerializedSize(), Serialize(), SerializeInformationField(), and SetErpSupported().
The documentation for this class was generated from the following files:
src/wifi/model/erp-information.h
src/wifi/model/erp-information.cc