ns-3: ns3::CapabilityInformation Class Reference
ns3::CapabilityInformation Class Reference
Wifi Models
Capability information.
#include "capability-information.h"
Public Member Functions
CapabilityInformation ()
Buffer::Iterator Deserialize (Buffer::Iterator start)
Deserialize capability information from the given buffer.
uint32_t GetSerializedSize (void) const
Return the serialized size of capability information.
bool IsCfPollable (void) const
Check if the CF-Pollable bit in the capability information field is set to 1.
bool IsEss (void) const
Check if the Extended Service Set (ESS) bit in the capability information field is set to 1.
bool IsIbss (void) const
Check if the Independent BSS (IBSS) bit in the capability information field is set to 1.
bool IsShortPreamble (void) const
Check if the short preamble bit in the capability information field is set to 1.
bool IsShortSlotTime (void) const
Check if the short slot time in the capability information field is set to 1.
Buffer::Iterator Serialize (Buffer::Iterator start) const
Serialize capability information to the given buffer.
void SetCfPollable (void)
Set the CF-Pollable bit in the capability information field.
void SetEss (void)
Set the Extended Service Set (ESS) bit in the capability information field.
void SetIbss (void)
Set the Independent BSS (IBSS) bit in the capability information field.
void SetShortPreamble (bool shortPreamble)
Set the short preamble bit in the capability information field.
void SetShortSlotTime (bool shortSlotTime)
Set the short slot time bit in the capability information field.
Private Member Functions
void Clear (uint8_t n)
Set bit n to 0.
bool Is (uint8_t n) const
Check if bit n is set to 1.
void Set (uint8_t n)
Set bit n to 1.
Private Attributes
uint16_t m_capability
capability
Detailed Description
Capability information.
Definition at line 33 of file capability-information.h.
Constructor & Destructor Documentation
CapabilityInformation()
ns3::CapabilityInformation::CapabilityInformation ()
Definition at line 25 of file capability-information.cc.
Member Function Documentation
Clear()
void ns3::CapabilityInformation::Clear (uint8_t n) private
Set bit n to 0.
Parameters
n the bit position
Definition at line 106 of file capability-information.cc.
References m_capability, and sample-rng-plot::n.
Referenced by SetEss(), and SetIbss().
Deserialize()
Buffer::Iterator ns3::CapabilityInformation::Deserialize (Buffer::Iterator start)
Deserialize capability information from the given buffer.
Parameters
start an iterator to a buffer
Returns
an iterator to a buffer after capability information was deserialized
Definition at line 133 of file capability-information.cc.
References m_capability, and visualizer.core::start().
Referenced by ns3::MgtAssocRequestHeader::Deserialize(), ns3::MgtReassocRequestHeader::Deserialize(), ns3::MgtAssocResponseHeader::Deserialize(), and ns3::MgtProbeResponseHeader::Deserialize().
GetSerializedSize()
uint32_t ns3::CapabilityInformation::GetSerializedSize (void) const
Return the serialized size of capability information.
Returns
the serialized size
Definition at line 120 of file capability-information.cc.
Referenced by ns3::MgtAssocRequestHeader::GetSerializedSize(), ns3::MgtReassocRequestHeader::GetSerializedSize(), ns3::MgtAssocResponseHeader::GetSerializedSize(), and ns3::MgtProbeResponseHeader::GetSerializedSize().
Is()
bool ns3::CapabilityInformation::Is (uint8_t n) const private
Check if bit n is set to 1.
Parameters
n the bit position
Returns
true if bit n is set to 1, false otherwise
Definition at line 113 of file capability-information.cc.
References m_capability, and sample-rng-plot::n.
Referenced by IsCfPollable(), IsEss(), IsIbss(), IsShortPreamble(), and IsShortSlotTime().
IsCfPollable()
bool ns3::CapabilityInformation::IsCfPollable (void) const
Check if the CF-Pollable bit in the capability information field is set to 1.
Returns
CF-Pollable bit in the capability information field is set to 1
Definition at line 93 of file capability-information.cc.
References Is().
Referenced by ns3::ApWifiMac::Receive().
IsEss()
bool ns3::CapabilityInformation::IsEss (void) const
Check if the Extended Service Set (ESS) bit in the capability information field is set to 1.
Returns
ESS bit in the capability information field is set to 1
Definition at line 69 of file capability-information.cc.
References Is().
Referenced by ns3::StaWifiMac::Receive().
IsIbss()
bool ns3::CapabilityInformation::IsIbss (void) const
Check if the Independent BSS (IBSS) bit in the capability information field is set to 1.
Returns
IBSS bit in the capability information field is set to 1
Definition at line 75 of file capability-information.cc.
References Is().
IsShortPreamble()
bool ns3::CapabilityInformation::IsShortPreamble (void) const
Check if the short preamble bit in the capability information field is set to 1.
Returns
short preamble bit in the capability information field is set to 1
Definition at line 81 of file capability-information.cc.
References Is().
Referenced by ns3::ApWifiMac::Receive(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), ns3::StaWifiMac::UpdateApInfoFromBeacon(), and ns3::StaWifiMac::UpdateApInfoFromProbeResp().
IsShortSlotTime()
bool ns3::CapabilityInformation::IsShortSlotTime (void) const
Check if the short slot time in the capability information field is set to 1.
Returns
short slot time bit in the capability information field is set to 1
Definition at line 87 of file capability-information.cc.
References Is().
Referenced by ns3::ApWifiMac::Receive(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), ns3::StaWifiMac::UpdateApInfoFromBeacon(), and ns3::StaWifiMac::UpdateApInfoFromProbeResp().
Serialize()
Buffer::Iterator ns3::CapabilityInformation::Serialize (Buffer::Iterator start) const
Serialize capability information to the given buffer.
Parameters
start an iterator to a buffer
Returns
an iterator to a buffer after capability information was serialized
Definition at line 126 of file capability-information.cc.
References m_capability, and visualizer.core::start().
Referenced by ns3::MgtAssocRequestHeader::Serialize(), ns3::MgtReassocRequestHeader::Serialize(), ns3::MgtAssocResponseHeader::Serialize(), and ns3::MgtProbeResponseHeader::Serialize().
Set()
void ns3::CapabilityInformation::Set (uint8_t n) private
Set bit n to 1.
Parameters
n the bit position
Definition at line 99 of file capability-information.cc.
References m_capability, and sample-rng-plot::n.
Referenced by SetCfPollable(), SetEss(), SetIbss(), SetShortPreamble(), and SetShortSlotTime().
SetCfPollable()
void ns3::CapabilityInformation::SetCfPollable (void)
Set the CF-Pollable bit in the capability information field.
Definition at line 63 of file capability-information.cc.
References Set().
Referenced by ns3::ApWifiMac::GetCapabilities(), and ns3::StaWifiMac::GetCapabilities().
SetEss()
void ns3::CapabilityInformation::SetEss (void)
Set the Extended Service Set (ESS) bit in the capability information field.
Definition at line 31 of file capability-information.cc.
References Clear(), and Set().
Referenced by ns3::ApWifiMac::GetCapabilities().
SetIbss()
void ns3::CapabilityInformation::SetIbss (void)
Set the Independent BSS (IBSS) bit in the capability information field.
Definition at line 38 of file capability-information.cc.
References Clear(), and Set().
SetShortPreamble()
void ns3::CapabilityInformation::SetShortPreamble (bool shortPreamble)
Set the short preamble bit in the capability information field.
Parameters
shortPreamble the short preamble bit
Definition at line 45 of file capability-information.cc.
References Set().
Referenced by ns3::ApWifiMac::GetCapabilities(), and ns3::StaWifiMac::GetCapabilities().
SetShortSlotTime()
void ns3::CapabilityInformation::SetShortSlotTime (bool shortSlotTime)
Set the short slot time bit in the capability information field.
Parameters
shortSlotTime the short preamble bit
Definition at line 54 of file capability-information.cc.
References Set().
Referenced by ns3::ApWifiMac::GetCapabilities(), and ns3::StaWifiMac::GetCapabilities().
Member Data Documentation
m_capability
uint16_t ns3::CapabilityInformation::m_capability private
capability
Definition at line 159 of file capability-information.h.
Referenced by Clear(), Deserialize(), Is(), Serialize(), and Set().
The documentation for this class was generated from the following files:
src/wifi/model/capability-information.h
src/wifi/model/capability-information.cc