ns-3: ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > Class Template Reference
ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > Class Template Reference
Network » Sequence Counter
Generic "sequence number" class.
#include "sequence-number.h"
Public Member Functions
SequenceNumber ()
SequenceNumber (NUMERIC_TYPE value)
Constructs a SequenceNumber with the given value.
SequenceNumber (SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > const &value)
Constructs a SequenceNumber from a copy.
NUMERIC_TYPE GetValue () const
Extracts the numeric value of the sequence number.
bool operator!= (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > &other) const
Inequality operator for comparing sequence numbers.
SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > operator+ (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > &other) const
Operator defining addition of two sequence numbers.
SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > operator+ (SIGNED_TYPE delta) const
Addition operator for adding numeric value to sequence number.
SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > operator++ ()
Prefix increment operator.
SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > operator++ (int)
Postfix increment operator.
SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > & operator+= (SIGNED_TYPE value)
Plus equals operator.
SIGNED_TYPE operator- (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > &other) const
Subtraction operator for subtracting sequence number from sequence number.
SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > operator- (SIGNED_TYPE delta) const
Subtraction operator for subtracting numeric value from sequence number.
SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > operator-- ()
Prefix decrement operator.
SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > operator-- (int)
Postfix decrement operator.
SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > & operator-= (SIGNED_TYPE value)
Minus equals operator.
bool operator< (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > &other) const
Less than operator for comparing sequence numbers.
bool operator<= (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > &other) const
Less than or equal operator for comparing sequence numbers.
SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > & operator= (NUMERIC_TYPE value)
Constructs a SequenceNumber from an assignment of given value.
SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > & operator= (SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > const &value)
Constructs a SequenceNumber from an assignment of another sequence number.
bool operator== (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > &other) const
Equality operator for comparing sequence number.
bool operator> (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > &other) const
Here is the critical part, how the comparison is made taking into account wrap-around.
bool operator>= (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > &other) const
Greater than or equal operator for comparing sequence numbers.
Private Member Functions
bool operator! () const
Logical NOT operator - unimplemented.
SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > operator% (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > &b) const
Modulo operator - unimplemented.
SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > operator& (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > &b) const
Bitwise AND operator - unimplemented.
bool operator&& (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > &b) const
Logical AND operator - unimplemented.
int operator* ()
Indirection operator - unimplemented.
SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > operator* (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > &b) const
Multiplication operator - unimplemented.
SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > & operator+= (SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > const &value)
Plus equals operator - unimplemented.
SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > & operator-= (SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > const &value)
Minus equals operator - unimplemented.
SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > operator/ (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > &b) const
Division operator - unimplemented.
SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > operator<< (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > &b) const
Bitwise left shift operator - unimplemented.
SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > operator>> (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > &b) const
Bitwise right shift operator - unimplemented.
SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > operator^ (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > &b) const
Bitwise XOR operator - unimplemented.
SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > operator| (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > &b) const
Bitwise OR operator - unimplemented.
bool operator|| (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > &b) const
Logical OR operator - unimplemented.
SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > operator~ () const
Bitwise NOT operator - unimplemented.
Private Attributes
NUMERIC_TYPE m_value
Sequence number value.
Friends
template<typename NUMERIC_TYPE2 , typename SIGNED_TYPE2 >
std::ostream & operator<< (std::ostream &os, const SequenceNumber< NUMERIC_TYPE2, SIGNED_TYPE2 > &val)
For printing sequence number.
template<typename NUMERIC_TYPE2 , typename SIGNED_TYPE2 >
std::istream & operator>> (std::istream &is, const SequenceNumber< NUMERIC_TYPE2, SIGNED_TYPE2 > &val)
For loading sequence number from input streams.
Detailed Description
template<typename NUMERIC_TYPE, typename SIGNED_TYPE>
class ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >
Generic "sequence number" class.
This class can be used to handle sequence numbers. In networking protocols, sequence numbers are fixed precision integer numbers that are used to order events relative to each other. A sequence number is expected to increase over time but, since it has a limited number of bits, the number will "wrap around" from the maximum value that can represented with the given number of bits back to zero. For this reason, comparison of two sequence numbers, and subtraction, is non-trivial. The SequenceNumber class behaves like a number, with the usual arithmetic operators implemented, but knows how to correctly compare and subtract sequence numbers.
This is a templated class. To use it you need to supply two fundamental types as template parameters: NUMERIC_TYPE and SIGNED_TYPE. For instance, SequenceNumber<uint32_t, int32_t> gives you a 32-bit sequence number, while SequenceNumber<uint16_t, int16_t> is a 16-bit one. For your convenience, these are typedef'ed as SequenceNumber32 and SequenceNumber16, respectively.
Definition at line 59 of file sequence-number.h.
Constructor & Destructor Documentation
SequenceNumber() [1/3]
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::SequenceNumber () inline
Definition at line 62 of file sequence-number.h.
SequenceNumber() [2/3]
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::SequenceNumber (NUMERIC_TYPE value) inline explicit
Constructs a SequenceNumber with the given value.
Parameters
value the sequence number value
Definition at line 70 of file sequence-number.h.
SequenceNumber() [3/3]
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::SequenceNumber (SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > const & value) inline
Constructs a SequenceNumber from a copy.
Parameters
value sequence number to copy
Definition at line 78 of file sequence-number.h.
Member Function Documentation
GetValue()
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > NUMERIC_TYPE ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::GetValue (void) const inline
Extracts the numeric value of the sequence number.
Returns
the sequence number value
Definition at line 116 of file sequence-number.h.
References ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::m_value.
Referenced by ns3::TcpTxBuffer::CopyFromSequence(), SequenceNumberTestCase::DoRun(), TcpFastRetrTest::FinalChecks(), ns3::TcpSocketBase::IsPacingEnabled(), ns3::LrWpanMac::McpsDataRequest(), ns3::LrWpanMac::MlmePollRequest(), ns3::TcpTxBuffer::NextSeg(), TcpFastRetrTest::ProcessedAck(), TcpFastRetrTest::RcvAck(), TcpFastRetrTest::Rx(), TcpPktsAckedOpenTest::Rx(), TcpSlowStartNormalTest::Rx(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), ns3::LrWpanMac::SendOneBeacon(), ns3::TcpHeader::Serialize(), ns3::TcpOptionSack::Serialize(), TcpTxBufferTestCase::TestNextSeg(), anonymous_namespace{traced-value-callback-typedef-test-suite.cc}::TracedValueCbSink< SequenceNumber32 >(), TcpFastRetrTest::Tx(), and TcpTimeRtoTest::Tx().
operator!()
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > bool ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator! () const private
Logical NOT operator - unimplemented.
Returns
condition
operator!=()
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > bool ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator!= (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > & other) const inline
Inequality operator for comparing sequence numbers.
Parameters
other sequence number to compare to this sequence number
Returns
true if the sequence numbers are not equal
Definition at line 297 of file sequence-number.h.
References ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::m_value.
operator%()
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > SequenceNumber<NUMERIC_TYPE, SIGNED_TYPE> ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator% (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > & b) const private
Modulo operator - unimplemented.
Parameters
b value
Returns
sequence number
operator&()
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > SequenceNumber<NUMERIC_TYPE, SIGNED_TYPE> ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator& (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > & b) const private
Bitwise AND operator - unimplemented.
Parameters
b value
Returns
sequence number
operator&&()
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > bool ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator&& (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > & b) const private
Logical AND operator - unimplemented.
Parameters
b value
Returns
condition
operator*() [1/2]
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > int ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator* () private
Indirection operator - unimplemented.
Returns
integer
operator*() [2/2]
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > SequenceNumber<NUMERIC_TYPE, SIGNED_TYPE> ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator* (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > & b) const private
Multiplication operator - unimplemented.
Parameters
b value
Returns
sequence number
operator+() [1/2]
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > SequenceNumber<NUMERIC_TYPE, SIGNED_TYPE> ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator+ (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > & other) const inline
Operator defining addition of two sequence numbers.
Parameters
other sequence number added to this
Returns
sequence number representing sum
Definition at line 190 of file sequence-number.h.
References ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::m_value.
operator+() [2/2]
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > SequenceNumber<NUMERIC_TYPE, SIGNED_TYPE> ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator+ (SIGNED_TYPE delta) const inline
Addition operator for adding numeric value to sequence number.
Parameters
delta value to add to sequence number
Returns
sequence number representing sum
Definition at line 200 of file sequence-number.h.
References ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::m_value.
operator++() [1/2]
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > SequenceNumber<NUMERIC_TYPE, SIGNED_TYPE> ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator++ () inline
Prefix increment operator.
Returns
incremented sequence number
Definition at line 125 of file sequence-number.h.
References ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::m_value.
operator++() [2/2]
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > SequenceNumber<NUMERIC_TYPE, SIGNED_TYPE> ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator++ (int) inline
Postfix increment operator.
Returns
incremented sequence number
Definition at line 135 of file sequence-number.h.
References ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::m_value.
operator+=() [1/2]
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > SequenceNumber<NUMERIC_TYPE, SIGNED_TYPE>& ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator+= (SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > const & value) private
Plus equals operator - unimplemented.
Parameters
value value
Returns
sequence number
operator+=() [2/2]
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > SequenceNumber<NUMERIC_TYPE, SIGNED_TYPE>& ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator+= (SIGNED_TYPE value) inline
Plus equals operator.
Parameters
value value to add to sequence number
Returns
incremented sequence number
Definition at line 168 of file sequence-number.h.
References ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::m_value.
operator-() [1/2]
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > SIGNED_TYPE ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator- (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > & other) const inline
Subtraction operator for subtracting sequence number from sequence number.
Parameters
other sequence number to subtract from this sequence number
Returns
numeric value representing the difference
Definition at line 220 of file sequence-number.h.
References ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::m_value, and max.
operator-() [2/2]
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > SequenceNumber<NUMERIC_TYPE, SIGNED_TYPE> ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator- (SIGNED_TYPE delta) const inline
Subtraction operator for subtracting numeric value from sequence number.
Parameters
delta value to subtract from sequence number
Returns
sequence number representing difference
Definition at line 210 of file sequence-number.h.
References ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::m_value.
operator--() [1/2]
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > SequenceNumber<NUMERIC_TYPE, SIGNED_TYPE> ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator-- () inline
Prefix decrement operator.
Returns
decremented sequence number
Definition at line 146 of file sequence-number.h.
References ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::m_value.
operator--() [2/2]
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > SequenceNumber<NUMERIC_TYPE, SIGNED_TYPE> ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator-- (int) inline
Postfix decrement operator.
Returns
incremented sequence number
Definition at line 156 of file sequence-number.h.
References ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::m_value.
operator-=() [1/2]
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > SequenceNumber<NUMERIC_TYPE, SIGNED_TYPE>& ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator-= (SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > const & value) private
Minus equals operator - unimplemented.
Parameters
value value
Returns
sequence number
operator-=() [2/2]
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > SequenceNumber<NUMERIC_TYPE, SIGNED_TYPE>& ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator-= (SIGNED_TYPE value) inline
Minus equals operator.
Parameters
value value to subtract from sequence number
Returns
decremented sequence number
Definition at line 179 of file sequence-number.h.
References ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::m_value.
operator/()
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > SequenceNumber<NUMERIC_TYPE, SIGNED_TYPE> ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator/ (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > & b) const private
Division operator - unimplemented.
Parameters
b value
Returns
sequence number
operator<()
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > bool ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator< (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > & other) const inline
Less than operator for comparing sequence numbers.
Parameters
other sequence number to compare to this sequence number
Returns
true if this sequence number is less than other
Definition at line 327 of file sequence-number.h.
References ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::m_value, and ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator>().
operator<<()
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > SequenceNumber<NUMERIC_TYPE, SIGNED_TYPE> ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator<< (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > & b) const private
Bitwise left shift operator - unimplemented.
Parameters
b value
Returns
sequence number
operator<=()
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > bool ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator<= (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > & other) const inline
Less than or equal operator for comparing sequence numbers.
Parameters
other sequence number to compare to this sequence number
Returns
true if this sequence number is less than or equal to other
Definition at line 307 of file sequence-number.h.
operator=() [1/2]
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > SequenceNumber<NUMERIC_TYPE, SIGNED_TYPE>& ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator= (NUMERIC_TYPE value) inline
Constructs a SequenceNumber from an assignment of given value.
Parameters
value sequence number to copy
Returns
reference to the assignee
Definition at line 87 of file sequence-number.h.
References ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::m_value.
operator=() [2/2]
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > SequenceNumber<NUMERIC_TYPE, SIGNED_TYPE>& ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator= (SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > const & value) inline
Constructs a SequenceNumber from an assignment of another sequence number.
Parameters
value sequence number to copy
Returns
reference to the assignee
Definition at line 98 of file sequence-number.h.
References ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::m_value.
operator==()
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > bool ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator== (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > & other) const inline
Equality operator for comparing sequence number.
Parameters
other sequence number to compare to this sequence number
Returns
true if the sequence numbers are equal
Definition at line 287 of file sequence-number.h.
References ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::m_value.
operator>()
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > bool ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator> (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > & other) const inline
Here is the critical part, how the comparison is made taking into account wrap-around.
From RFC 3626:
The sequence number S1 is said to be "greater than" the sequence number S2 if: S1 > S2 AND S1 - S2 <= MAXVALUE/2 OR S2 > S1 AND S2 - S1 > MAXVALUE/2
Parameters
other sequence number to compare to this one
Returns
true if this sequence number is greater than other
Definition at line 274 of file sequence-number.h.
References ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::m_value, and max.
Referenced by ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator<().
operator>=()
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > bool ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator>= (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > & other) const inline
Greater than or equal operator for comparing sequence numbers.
Parameters
other sequence number to compare to this sequence number
Returns
true if this sequence number is greater than or equal to other
Definition at line 317 of file sequence-number.h.
operator>>()
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > SequenceNumber<NUMERIC_TYPE, SIGNED_TYPE> ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator>> (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > & b) const private
Bitwise right shift operator - unimplemented.
Parameters
b value
Returns
sequence number
operator^()
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > SequenceNumber<NUMERIC_TYPE, SIGNED_TYPE> ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator^ (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > & b) const private
Bitwise XOR operator - unimplemented.
Parameters
b value
Returns
sequence number
operator|()
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > SequenceNumber<NUMERIC_TYPE, SIGNED_TYPE> ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator| (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > & b) const private
Bitwise OR operator - unimplemented.
Parameters
b value
Returns
sequence number
operator||()
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > bool ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator|| (const SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE > & b) const private
Logical OR operator - unimplemented.
Parameters
b value
Returns
condition
operator~()
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > SequenceNumber<NUMERIC_TYPE, SIGNED_TYPE> ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator~ () const private
Bitwise NOT operator - unimplemented.
Returns
sequence number
Friends And Related Function Documentation
operator<<
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > template<typename NUMERIC_TYPE2 , typename SIGNED_TYPE2 > std::ostream& operator<< (std::ostream & os, const SequenceNumber< NUMERIC_TYPE2, SIGNED_TYPE2 > & val) friend
For printing sequence number.
Parameters
os output stream
val sequence number to display
Returns
output stream os
operator>>
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > template<typename NUMERIC_TYPE2 , typename SIGNED_TYPE2 > std::istream& operator>> (std::istream & is, const SequenceNumber< NUMERIC_TYPE2, SIGNED_TYPE2 > & val) friend
For loading sequence number from input streams.
Parameters
is input stream
val sequence number to load
Returns
input stream is
Member Data Documentation
m_value
template<typename NUMERIC_TYPE , typename SIGNED_TYPE > NUMERIC_TYPE ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::m_value private
Sequence number value.
Definition at line 441 of file sequence-number.h.
Referenced by ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::GetValue(), ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator!=(), ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator+(), ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator++(), ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator+=(), ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator-(), ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator--(), ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator-=(), ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator<(), ns3::operator<<(), ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator=(), ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator==(), ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::operator>(), and ns3::operator>>().
The documentation for this class was generated from the following file:
src/network/utils/sequence-number.h