ns-3: ns3::FlowMonitor Class Reference
ns3::FlowMonitor Class Reference
Flow Monitor
An object that monitors and reports back packet flows observed during a simulation.
#include "flow-monitor.h"
Classes
struct FlowStats
Structure that represents the measured metrics of an individual packet flow.
struct TrackedPacket
Structure to represent a single tracked packet data.
Public Types
typedef std::vector< Ptr< FlowProbe > > FlowProbeContainer
Container: FlowProbe.
typedef std::vector< Ptr< FlowProbe > >::const_iterator FlowProbeContainerCI
Container Const Iterator: FlowProbe.
typedef std::vector< Ptr< FlowProbe > >::iterator FlowProbeContainerI
Container Iterator: FlowProbe.
typedef std::map< FlowId, FlowStats > FlowStatsContainer
Container: FlowId, FlowStats.
typedef std::map< FlowId, FlowStats >::const_iterator FlowStatsContainerCI
Container Const Iterator: FlowId, FlowStats.
typedef std::map< FlowId, FlowStats >::iterator FlowStatsContainerI
Container Iterator: FlowId, FlowStats.
Public Member Functions
FlowMonitor ()
void AddFlowClassifier (Ptr< FlowClassifier > classifier)
Add a FlowClassifier to be used by the flow monitor.
void AddProbe (Ptr< FlowProbe > probe)
Register a new FlowProbe that will begin monitoring and report events to this monitor.
void CheckForLostPackets ()
Check right now for packets that appear to be lost.
void CheckForLostPackets (Time maxDelay)
Check right now for packets that appear to be lost, considering packets as lost if not seen in the network for a time larger than maxDelay.
const FlowProbeContainer & GetAllProbes () const
Get a list of all FlowProbe's associated with this FlowMonitor.
const FlowStatsContainer & GetFlowStats () const
Retrieve all collected the flow statistics.
virtual TypeId GetInstanceTypeId () const
Get the most derived TypeId for this Object.
void ReportDrop (Ptr< FlowProbe > probe, FlowId flowId, FlowPacketId packetId, uint32_t packetSize, uint32_t reasonCode)
FlowProbe implementations are supposed to call this method to report that a known packet is being dropped due to some reason.
void ReportFirstTx (Ptr< FlowProbe > probe, FlowId flowId, FlowPacketId packetId, uint32_t packetSize)
FlowProbe implementations are supposed to call this method to report that a new packet was transmitted (but keep in mind the distinction between a new packet entering the system and a packet that is already known and is only being forwarded).
void ReportForwarding (Ptr< FlowProbe > probe, FlowId flowId, FlowPacketId packetId, uint32_t packetSize)
FlowProbe implementations are supposed to call this method to report that a known packet is being forwarded.
void ReportLastRx (Ptr< FlowProbe > probe, FlowId flowId, FlowPacketId packetId, uint32_t packetSize)
FlowProbe implementations are supposed to call this method to report that a known packet is being received.
void SerializeToXmlFile (std::string fileName, bool enableHistograms, bool enableProbes)
Same as SerializeToXmlStream, but writes to a file instead.
void SerializeToXmlStream (std::ostream &os, uint16_t indent, bool enableHistograms, bool enableProbes)
Serializes the results to an std::ostream in XML format.
std::string SerializeToXmlString (uint16_t indent, bool enableHistograms, bool enableProbes)
Same as SerializeToXmlStream, but returns the output as a std::string.
void Start (const Time &time)
Set the time, counting from the current time, from which to start monitoring flows.
void StartRightNow ()
Begin monitoring flows right now
void Stop (const Time &time)
Set the time, counting from the current time, from which to stop monitoring flows.
void StopRightNow ()
End monitoring flows right now
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
virtual void NotifyConstructionCompleted ()
Notifier called once the ObjectBase is fully constructed.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
Private Types
typedef std::map< std::pair< FlowId, FlowPacketId >, TrackedPacket > TrackedPacketMap
(FlowId,PacketId) --> TrackedPacket
Private Member Functions
FlowStats & GetStatsForFlow (FlowId flowId)
Get the stats for a given flow.
void PeriodicCheckForLostPackets ()
Periodic function to check for lost packets and prune statistics.
Private Attributes
std::list< Ptr< FlowClassifier > > m_classifiers
the FlowClassifiers
double m_delayBinWidth
Delay bin width (for histograms)
bool m_enabled
FlowMon is enabled.
double m_flowInterruptionsBinWidth
Flow interruptions bin width (for histograms)
Time m_flowInterruptionsMinTime
Flow interruptions minimum time.
FlowProbeContainer m_flowProbes
all the FlowProbes
FlowStatsContainer m_flowStats
FlowId --> FlowStats.
double m_jitterBinWidth
Jitter bin width (for histograms)
Time m_maxPerHopDelay
Minimum per-hop delay.
double m_packetSizeBinWidth
packet size bin width (for histograms)
EventId m_startEvent
Start event.
EventId m_stopEvent
Stop event.
TrackedPacketMap m_trackedPackets
Tracked packets.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
An object that monitors and reports back packet flows observed during a simulation.
Introspection did not find any typical Config paths.
The FlowMonitor class is responsible for coordinating efforts regarding probes, and collects end-to-end flow statistics.
Attributes
MaxPerHopDelay: The maximum per-hop delay that should be considered. Packets still not received after this delay are to be considered lost.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+10ns
Flags: construct write read
StartTime: The time when the monitoring starts.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write
DelayBinWidth: The width used in the delay histogram.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0.001
Flags: construct write read
JitterBinWidth: The width used in the jitter histogram.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0.001
Flags: construct write read
PacketSizeBinWidth: The width used in the packetSize histogram.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 20
Flags: construct write read
FlowInterruptionsBinWidth: The width used in the flowInterruptions histogram.
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0.25
Flags: construct write read
FlowInterruptionsMinTime: The minimum inter-arrival time that is considered a flow interruption.
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +5e+08ns
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 232 bytes (on a 64-bit architecture).
Definition at line 50 of file flow-monitor.h.
Member Typedef Documentation
FlowProbeContainer
typedef std::vector< Ptr<FlowProbe> > ns3::FlowMonitor::FlowProbeContainer
Container: FlowProbe.
Definition at line 224 of file flow-monitor.h.
FlowProbeContainerCI
typedef std::vector< Ptr<FlowProbe> >::const_iterator ns3::FlowMonitor::FlowProbeContainerCI
Container Const Iterator: FlowProbe.
Definition at line 228 of file flow-monitor.h.
FlowProbeContainerI
typedef std::vector< Ptr<FlowProbe> >::iterator ns3::FlowMonitor::FlowProbeContainerI
Container Iterator: FlowProbe.
Definition at line 226 of file flow-monitor.h.
FlowStatsContainer
typedef std::map<FlowId, FlowStats> ns3::FlowMonitor::FlowStatsContainer
Container: FlowId, FlowStats.
Definition at line 218 of file flow-monitor.h.
FlowStatsContainerCI
typedef std::map<FlowId, FlowStats>::const_iterator ns3::FlowMonitor::FlowStatsContainerCI
Container Const Iterator: FlowId, FlowStats.
Definition at line 222 of file flow-monitor.h.
FlowStatsContainerI
typedef std::map<FlowId, FlowStats>::iterator ns3::FlowMonitor::FlowStatsContainerI
Container Iterator: FlowId, FlowStats.
Definition at line 220 of file flow-monitor.h.
TrackedPacketMap
typedef std::map< std::pair<FlowId, FlowPacketId>, TrackedPacket> ns3::FlowMonitor::TrackedPacketMap private
(FlowId,PacketId) --> TrackedPacket
Definition at line 281 of file flow-monitor.h.
Constructor & Destructor Documentation
FlowMonitor()
ns3::FlowMonitor::FlowMonitor ()
Definition at line 82 of file flow-monitor.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddFlowClassifier()
void ns3::FlowMonitor::AddFlowClassifier (Ptr< FlowClassifier > classifier)
Add a FlowClassifier to be used by the flow monitor.
Parameters
classifier the FlowClassifier
Definition at line 413 of file flow-monitor.cc.
References m_classifiers.
AddProbe()
void ns3::FlowMonitor::AddProbe (Ptr< FlowProbe > probe)
Register a new FlowProbe that will begin monitoring and report events to this monitor.
This method is normally only used by FlowProbe implementations.
Parameters
probe the probe to add
Definition at line 349 of file flow-monitor.cc.
References m_flowProbes.
CheckForLostPackets() [1/2]
void ns3::FlowMonitor::CheckForLostPackets ()
Check right now for packets that appear to be lost.
Definition at line 329 of file flow-monitor.cc.
References m_maxPerHopDelay.
Referenced by PeriodicCheckForLostPackets(), SerializeToXmlStream(), and StopRightNow().
CheckForLostPackets() [2/2]
void ns3::FlowMonitor::CheckForLostPackets (Time maxDelay)
Check right now for packets that appear to be lost, considering packets as lost if not seen in the network for a time larger than maxDelay.
Parameters
maxDelay the max delay for a packet
Definition at line 303 of file flow-monitor.cc.
References ns3::Time::As(), m_flowStats, m_trackedPackets, ns3::Simulator::Now(), NS_ASSERT, NS_LOG_FUNCTION, and ns3::Time::S.
DoDispose()
void ns3::FlowMonitor::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 89 of file flow-monitor.cc.
References ns3::Simulator::Cancel(), ns3::Object::DoDispose(), list, m_classifiers, m_flowProbes, m_startEvent, m_stopEvent, and NS_LOG_FUNCTION.
GetAllProbes()
const FlowMonitor::FlowProbeContainer & ns3::FlowMonitor::GetAllProbes () const
Get a list of all FlowProbe's associated with this FlowMonitor.
Returns
a list of all the probes
Definition at line 356 of file flow-monitor.cc.
References m_flowProbes.
GetFlowStats()
const FlowMonitor::FlowStatsContainer & ns3::FlowMonitor::GetFlowStats () const
Retrieve all collected the flow statistics.
Note, if the FlowMonitor has not stopped monitoring yet, you should call CheckForLostPackets() to make sure all possibly lost packets are accounted for.
Returns
the flows statistics
Definition at line 296 of file flow-monitor.cc.
References m_flowStats.
GetInstanceTypeId()
TypeId ns3::FlowMonitor::GetInstanceTypeId () const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Reimplemented from ns3::Object.
Definition at line 77 of file flow-monitor.cc.
References GetTypeId().
GetStatsForFlow()
FlowMonitor::FlowStats & ns3::FlowMonitor::GetStatsForFlow (FlowId flowId) inline private
Get the stats for a given flow.
Parameters
flowId the Flow identification
Returns
the stats of the flow
Definition at line 109 of file flow-monitor.cc.
References ns3::FlowMonitor::FlowStats::delayHistogram, ns3::FlowMonitor::FlowStats::delaySum, ns3::FlowMonitor::FlowStats::flowInterruptionsHistogram, ns3::FlowMonitor::FlowStats::jitterHistogram, ns3::FlowMonitor::FlowStats::jitterSum, ns3::FlowMonitor::FlowStats::lastDelay, ns3::FlowMonitor::FlowStats::lostPackets, m_delayBinWidth, m_flowInterruptionsBinWidth, m_flowStats, m_jitterBinWidth, m_packetSizeBinWidth, NS_LOG_FUNCTION, ns3::FlowMonitor::FlowStats::packetSizeHistogram, ns3::FlowMonitor::FlowStats::rxBytes, ns3::FlowMonitor::FlowStats::rxPackets, ns3::Seconds(), ns3::Histogram::SetDefaultBinWidth(), ns3::FlowMonitor::FlowStats::timesForwarded, ns3::FlowMonitor::FlowStats::txBytes, and ns3::FlowMonitor::FlowStats::txPackets.
Referenced by ReportDrop(), ReportFirstTx(), and ReportLastRx().
GetTypeId()
TypeId ns3::FlowMonitor::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 37 of file flow-monitor.cc.
References m_delayBinWidth, m_flowInterruptionsBinWidth, m_flowInterruptionsMinTime, m_jitterBinWidth, m_maxPerHopDelay, m_packetSizeBinWidth, ns3::MakeDoubleAccessor(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::Seconds(), ns3::TypeId::SetParent(), and Start().
Referenced by GetInstanceTypeId().
NotifyConstructionCompleted()
void ns3::FlowMonitor::NotifyConstructionCompleted (void) protected virtual
Notifier called once the ObjectBase is fully constructed.
This method is invoked once all member attributes have been initialized. Subclasses can override this method to be notified of this event but if they do this, they must chain up to their parent's NotifyConstructionCompleted method.
Reimplemented from ns3::ObjectBase.
Definition at line 342 of file flow-monitor.cc.
References ns3::ObjectBase::NotifyConstructionCompleted(), PERIODIC_CHECK_INTERVAL, PeriodicCheckForLostPackets(), and ns3::Simulator::Schedule().
PeriodicCheckForLostPackets()
void ns3::FlowMonitor::PeriodicCheckForLostPackets () private
Periodic function to check for lost packets and prune statistics.
Definition at line 335 of file flow-monitor.cc.
References CheckForLostPackets(), PERIODIC_CHECK_INTERVAL, and ns3::Simulator::Schedule().
Referenced by NotifyConstructionCompleted().
ReportDrop()
void ns3::FlowMonitor::ReportDrop (Ptr< FlowProbe > probe, FlowId flowId, FlowPacketId packetId, uint32_t packetSize, uint32_t reasonCode)
FlowProbe implementations are supposed to call this method to report that a known packet is being dropped due to some reason.
Parameters
probe the reporting probe
flowId flow identification
packetId Packet ID
packetSize packet size
reasonCode drop reason code
Definition at line 261 of file flow-monitor.cc.
References ns3::FlowProbe::AddPacketDropStats(), ns3::FlowMonitor::FlowStats::bytesDropped, GetStatsForFlow(), ns3::FlowMonitor::FlowStats::lostPackets, m_enabled, m_trackedPackets, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::FlowMonitor::FlowStats::packetsDropped, and packetSize.
ReportFirstTx()
void ns3::FlowMonitor::ReportFirstTx (Ptr< FlowProbe > probe, FlowId flowId, FlowPacketId packetId, uint32_t packetSize)
FlowProbe implementations are supposed to call this method to report that a new packet was transmitted (but keep in mind the distinction between a new packet entering the system and a packet that is already known and is only being forwarded).
Parameters
probe the reporting probe
flowId flow identification
packetId Packet ID
packetSize packet size
Definition at line 140 of file flow-monitor.cc.
References ns3::FlowProbe::AddPacketStats(), ns3::FlowMonitor::TrackedPacket::firstSeenTime, GetStatsForFlow(), ns3::FlowMonitor::TrackedPacket::lastSeenTime, m_enabled, m_trackedPackets, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, packetSize, ns3::Seconds(), ns3::FlowMonitor::FlowStats::timeFirstTxPacket, ns3::FlowMonitor::FlowStats::timeLastTxPacket, ns3::FlowMonitor::TrackedPacket::timesForwarded, ns3::FlowMonitor::FlowStats::txBytes, and ns3::FlowMonitor::FlowStats::txPackets.
ReportForwarding()
void ns3::FlowMonitor::ReportForwarding (Ptr< FlowProbe > probe, FlowId flowId, FlowPacketId packetId, uint32_t packetSize)
FlowProbe implementations are supposed to call this method to report that a known packet is being forwarded.
Parameters
probe the reporting probe
flowId flow identification
packetId Packet ID
packetSize packet size
Definition at line 170 of file flow-monitor.cc.
References ns3::FlowProbe::AddPacketStats(), m_enabled, m_trackedPackets, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_WARN, and packetSize.
ReportLastRx()
void ns3::FlowMonitor::ReportLastRx (Ptr< FlowProbe > probe, FlowId flowId, FlowPacketId packetId, uint32_t packetSize)
FlowProbe implementations are supposed to call this method to report that a known packet is being received.
Parameters
probe the reporting probe
flowId flow identification
packetId Packet ID
packetSize packet size
Definition at line 196 of file flow-monitor.cc.
References ns3::FlowProbe::AddPacketStats(), ns3::Histogram::AddValue(), ns3::FlowMonitor::FlowStats::delayHistogram, ns3::FlowMonitor::FlowStats::delaySum, ns3::FlowMonitor::FlowStats::flowInterruptionsHistogram, ns3::Time::GetSeconds(), GetStatsForFlow(), ns3::FlowMonitor::FlowStats::jitterHistogram, ns3::FlowMonitor::FlowStats::jitterSum, ns3::FlowMonitor::FlowStats::lastDelay, m_enabled, m_flowInterruptionsMinTime, m_trackedPackets, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_WARN, packetSize, ns3::FlowMonitor::FlowStats::packetSizeHistogram, ns3::FlowMonitor::FlowStats::rxBytes, ns3::FlowMonitor::FlowStats::rxPackets, ns3::Seconds(), ns3::FlowMonitor::FlowStats::timeFirstRxPacket, ns3::FlowMonitor::FlowStats::timeLastRxPacket, and ns3::FlowMonitor::FlowStats::timesForwarded.
SerializeToXmlFile()
void ns3::FlowMonitor::SerializeToXmlFile (std::string fileName, bool enableHistograms, bool enableProbes)
Same as SerializeToXmlStream, but writes to a file instead.
Parameters
fileName name or path of the output file that will be created
enableHistograms if true, include also the histograms in the output
enableProbes if true, include also the per-probe/flow pair statistics in the output
Definition at line 514 of file flow-monitor.cc.
References NS_LOG_FUNCTION, and SerializeToXmlStream().
SerializeToXmlStream()
void ns3::FlowMonitor::SerializeToXmlStream (std::ostream & os, uint16_t indent, bool enableHistograms, bool enableProbes)
Serializes the results to an std::ostream in XML format.
Parameters
os the output stream
indent number of spaces to use as base indentation level
enableHistograms if true, include also the histograms in the output
enableProbes if true, include also the per-probe/flow pair statistics in the output
Definition at line 419 of file flow-monitor.cc.
References ATTRIB, CheckForLostPackets(), check-style::indent(), list, m_classifiers, m_flowProbes, m_flowStats, and NS_LOG_FUNCTION.
Referenced by SerializeToXmlFile(), and SerializeToXmlString().
SerializeToXmlString()
std::string ns3::FlowMonitor::SerializeToXmlString (uint16_t indent, bool enableHistograms, bool enableProbes)
Same as SerializeToXmlStream, but returns the output as a std::string.
Parameters
indent number of spaces to use as base indentation level
enableHistograms if true, include also the histograms in the output
enableProbes if true, include also the per-probe/flow pair statistics in the output
Returns
the XML output as string
Definition at line 504 of file flow-monitor.cc.
References check-style::indent(), NS_LOG_FUNCTION, and SerializeToXmlStream().
Start()
void ns3::FlowMonitor::Start (const Time & time)
Set the time, counting from the current time, from which to start monitoring flows.
This method overwrites any previous calls to Start()
Parameters
time delta time to start
Definition at line 363 of file flow-monitor.cc.
References ns3::Time::As(), ns3::Simulator::Cancel(), m_enabled, m_startEvent, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Time::S, ns3::Simulator::Schedule(), and StartRightNow().
Referenced by GetTypeId().
StartRightNow()
void ns3::FlowMonitor::StartRightNow ()
Begin monitoring flows right now
Definition at line 387 of file flow-monitor.cc.
References m_enabled, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by Start().
Stop()
void ns3::FlowMonitor::Stop (const Time & time)
Set the time, counting from the current time, from which to stop monitoring flows.
This method overwrites any previous calls to Stop()
Parameters
time delta time to stop
Definition at line 377 of file flow-monitor.cc.
References ns3::Time::As(), ns3::Simulator::Cancel(), m_stopEvent, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Time::S, ns3::Simulator::Schedule(), and StopRightNow().
StopRightNow()
void ns3::FlowMonitor::StopRightNow ()
End monitoring flows right now
Definition at line 400 of file flow-monitor.cc.
References CheckForLostPackets(), m_enabled, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by Stop().
Member Data Documentation
m_classifiers
std::list<Ptr<FlowClassifier> > ns3::FlowMonitor::m_classifiers private
the FlowClassifiers
Definition at line 287 of file flow-monitor.h.
Referenced by AddFlowClassifier(), DoDispose(), and SerializeToXmlStream().
m_delayBinWidth
double ns3::FlowMonitor::m_delayBinWidth private
Delay bin width (for histograms)
Definition at line 292 of file flow-monitor.h.
Referenced by GetStatsForFlow(), and GetTypeId().
m_enabled
bool ns3::FlowMonitor::m_enabled private
FlowMon is enabled.
Definition at line 291 of file flow-monitor.h.
Referenced by ReportDrop(), ReportFirstTx(), ReportForwarding(), ReportLastRx(), Start(), StartRightNow(), and StopRightNow().
m_flowInterruptionsBinWidth
double ns3::FlowMonitor::m_flowInterruptionsBinWidth private
Flow interruptions bin width (for histograms)
Definition at line 295 of file flow-monitor.h.
Referenced by GetStatsForFlow(), and GetTypeId().
m_flowInterruptionsMinTime
Time ns3::FlowMonitor::m_flowInterruptionsMinTime private
Flow interruptions minimum time.
Definition at line 296 of file flow-monitor.h.
Referenced by GetTypeId(), and ReportLastRx().
m_flowProbes
FlowProbeContainer ns3::FlowMonitor::m_flowProbes private
all the FlowProbes
Definition at line 284 of file flow-monitor.h.
Referenced by AddProbe(), DoDispose(), GetAllProbes(), and SerializeToXmlStream().
m_flowStats
FlowStatsContainer ns3::FlowMonitor::m_flowStats private
FlowId --> FlowStats.
Definition at line 278 of file flow-monitor.h.
Referenced by CheckForLostPackets(), GetFlowStats(), GetStatsForFlow(), and SerializeToXmlStream().
m_jitterBinWidth
double ns3::FlowMonitor::m_jitterBinWidth private
Jitter bin width (for histograms)
Definition at line 293 of file flow-monitor.h.
Referenced by GetStatsForFlow(), and GetTypeId().
m_maxPerHopDelay
Time ns3::FlowMonitor::m_maxPerHopDelay private
Minimum per-hop delay.
Definition at line 283 of file flow-monitor.h.
Referenced by CheckForLostPackets(), and GetTypeId().
m_packetSizeBinWidth
double ns3::FlowMonitor::m_packetSizeBinWidth private
packet size bin width (for histograms)
Definition at line 294 of file flow-monitor.h.
Referenced by GetStatsForFlow(), and GetTypeId().
m_startEvent
EventId ns3::FlowMonitor::m_startEvent private
Start event.
Definition at line 289 of file flow-monitor.h.
Referenced by DoDispose(), and Start().
m_stopEvent
EventId ns3::FlowMonitor::m_stopEvent private
Stop event.
Definition at line 290 of file flow-monitor.h.
Referenced by DoDispose(), and Stop().
m_trackedPackets
TrackedPacketMap ns3::FlowMonitor::m_trackedPackets private
Tracked packets.
Definition at line 282 of file flow-monitor.h.
Referenced by CheckForLostPackets(), ReportDrop(), ReportFirstTx(), ReportForwarding(), and ReportLastRx().
The documentation for this class was generated from the following files:
src/flow-monitor/model/flow-monitor.h
src/flow-monitor/model/flow-monitor.cc