ns-3: CsmaPingTestCase Class Reference
CsmaPingTestCase Class Reference
Public Member Functions
CsmaPingTestCase ()
virtual ~CsmaPingTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void DropEvent (Ptr< const Packet > p)
void PingRtt (std::string context, Time rtt)
void SinkRx (Ptr< const Packet > p, const Address &ad)
Private Attributes
uint32_t m_countPingRtt
uint32_t m_countSinkRx
uint32_t m_drops
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 672 of file csma-system-test-suite.cc.
Constructor & Destructor Documentation
CsmaPingTestCase()
CsmaPingTestCase::CsmaPingTestCase ()
Definition at line 689 of file csma-system-test-suite.cc.
~CsmaPingTestCase()
CsmaPingTestCase::~CsmaPingTestCase () virtual
Definition at line 694 of file csma-system-test-suite.cc.
Member Function Documentation
DoRun()
void CsmaPingTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 726 of file csma-system-test-suite.cc.
References ns3::NodeContainer::Add(), ns3::Ipv4AddressHelper::Assign(), ns3::Config::Connect(), ns3::Config::ConnectWithoutContext(), ns3::NodeContainer::Create(), second::csma, ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::OnOffHelper::Install(), ns3::V4PingHelper::Install(), ns3::InternetStackHelper::Install(), m_countPingRtt, m_countSinkRx, ns3::MakeCallback(), ns3::MilliSeconds(), NS_TEST_ASSERT_MSG_EQ, PingRtt(), ns3::Seconds(), ns3::Ipv4AddressHelper::SetBase(), ns3::OnOffHelper::SetConstantRate(), ns3::Config::SetDefault(), sink, SinkRx(), ns3::ApplicationContainer::Start(), and ns3::ApplicationContainer::Stop().
DropEvent()
void CsmaPingTestCase::DropEvent (Ptr< const Packet > p) private
Definition at line 711 of file csma-system-test-suite.cc.
References m_drops.
PingRtt()
void CsmaPingTestCase::PingRtt (std::string context, Time rtt) private
Definition at line 705 of file csma-system-test-suite.cc.
References m_countPingRtt.
Referenced by DoRun().
SinkRx()
void CsmaPingTestCase::SinkRx (Ptr< const Packet > p, const Address & ad) private
Definition at line 699 of file csma-system-test-suite.cc.
References m_countSinkRx.
Referenced by DoRun().
Member Data Documentation
m_countPingRtt
uint32_t CsmaPingTestCase::m_countPingRtt private
Definition at line 684 of file csma-system-test-suite.cc.
Referenced by DoRun(), and PingRtt().
m_countSinkRx
uint32_t CsmaPingTestCase::m_countSinkRx private
Definition at line 683 of file csma-system-test-suite.cc.
Referenced by DoRun(), and SinkRx().
m_drops
uint32_t CsmaPingTestCase::m_drops private
Definition at line 685 of file csma-system-test-suite.cc.
Referenced by DropEvent().
The documentation for this class was generated from the following file:
src/test/csma-system-test-suite.cc