ns-3: V2vHighwayProbChCondModelTestCase Class Reference
V2vHighwayProbChCondModelTestCase Class Reference
Test case for the V2V Highway channel condition models using a fully probabilistic model to determine LOS, NLOS and NLOSv states.
Classes
struct TestVector
Struct containing the parameters for each test.
Public Member Functions
V2vHighwayProbChCondModelTestCase ()
Constructor.
virtual ~V2vHighwayProbChCondModelTestCase ()
Destructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Builds the simulation scenario and perform the tests.
void EvaluateChannelCondition (Ptr< MobilityModel > a, Ptr< MobilityModel > b)
Evaluates the channel condition between two nodes by calling the method GetChannelCondition on m_condModel.
Private Attributes
Ptr< ProbabilisticV2vHighwayChannelConditionModel > m_condModel
the channel condition model
uint64_t m_numLos {0}
the number of LOS occurrences
uint64_t m_numNlos {0}
the number of NLOS occurrences
TestVectors< TestVector > m_testVectors
array containing all the test vectors
double m_tolerance
tolerance
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test case for the V2V Highway channel condition models using a fully probabilistic model to determine LOS, NLOS and NLOSv states.
The test determines the channel condition multiple times, estimates the LOS and NLOS probabilities and compares them with the values given by M. Boban, X.Gong, and W. Xu, “Modeling the evolution of line-of-sight blockage for V2V channels,” in IEEE 84th Vehicular Technology Conference (VTC-Fall), 2016. Methodology from channel-condition-model- test-suite.cc is used, extended to a system with three states.
Definition at line 238 of file probabilistic-v2v-channel-condition-model-test.cc.
Constructor & Destructor Documentation
V2vHighwayProbChCondModelTestCase()
V2vHighwayProbChCondModelTestCase::V2vHighwayProbChCondModelTestCase ()
Constructor.
Definition at line 286 of file probabilistic-v2v-channel-condition-model-test.cc.
~V2vHighwayProbChCondModelTestCase()
V2vHighwayProbChCondModelTestCase::~V2vHighwayProbChCondModelTestCase () virtual
Destructor.
Definition at line 292 of file probabilistic-v2v-channel-condition-model-test.cc.
Member Function Documentation
DoRun()
void V2vHighwayProbChCondModelTestCase::DoRun (void) private virtual
Builds the simulation scenario and perform the tests.
Implements ns3::TestCase.
Definition at line 310 of file probabilistic-v2v-channel-condition-model-test.cc.
References ns3::ThreeGppChannelConditionModel::AssignStreams(), ns3::ObjectFactory::Create(), EvaluateChannelCondition(), m_condModel, V2vHighwayProbChCondModelTestCase::TestVector::m_density, m_numLos, m_numNlos, V2vHighwayProbChCondModelTestCase::TestVector::m_pLos, V2vHighwayProbChCondModelTestCase::TestVector::m_pNlos, V2vHighwayProbChCondModelTestCase::TestVector::m_positionA, V2vHighwayProbChCondModelTestCase::TestVector::m_positionB, m_testVectors, m_tolerance, V2vHighwayProbChCondModelTestCase::TestVector::m_typeId, max, ns3::MilliSeconds(), min, first::nodes, NS_LOG_DEBUG, NS_TEST_EXPECT_MSG_EQ_TOL, ns3::ObjectBase::SetAttribute(), ns3::MobilityModel::SetPosition(), and ns3::ObjectFactory::SetTypeId().
EvaluateChannelCondition()
void V2vHighwayProbChCondModelTestCase::EvaluateChannelCondition (Ptr< MobilityModel > a, Ptr< MobilityModel > b) private
Evaluates the channel condition between two nodes by calling the method GetChannelCondition on m_condModel.
If the channel condition is LOS it increments m_numLos, if NLOS it increments m_numNlos
Parameters
a the mobility model of the first node
b the mobility model of the second node
Definition at line 296 of file probabilistic-v2v-channel-condition-model-test.cc.
References ns3::ThreeGppChannelConditionModel::GetChannelCondition(), m_condModel, m_numLos, and m_numNlos.
Referenced by DoRun().
Member Data Documentation
m_condModel
Ptr<ProbabilisticV2vHighwayChannelConditionModel> V2vHighwayProbChCondModelTestCase::m_condModel private
the channel condition model
Definition at line 280 of file probabilistic-v2v-channel-condition-model-test.cc.
Referenced by DoRun(), and EvaluateChannelCondition().
m_numLos
uint64_t V2vHighwayProbChCondModelTestCase::m_numLos {0} private
the number of LOS occurrences
Definition at line 281 of file probabilistic-v2v-channel-condition-model-test.cc.
Referenced by DoRun(), and EvaluateChannelCondition().
m_numNlos
uint64_t V2vHighwayProbChCondModelTestCase::m_numNlos {0} private
the number of NLOS occurrences
Definition at line 282 of file probabilistic-v2v-channel-condition-model-test.cc.
Referenced by DoRun(), and EvaluateChannelCondition().
m_testVectors
TestVectors<TestVector> V2vHighwayProbChCondModelTestCase::m_testVectors private
array containing all the test vectors
Definition at line 279 of file probabilistic-v2v-channel-condition-model-test.cc.
Referenced by DoRun().
m_tolerance
double V2vHighwayProbChCondModelTestCase::m_tolerance private
tolerance
Definition at line 283 of file probabilistic-v2v-channel-condition-model-test.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/propagation/test/probabilistic-v2v-channel-condition-model-test.cc