ns-3: ns3::EpcEnbApplication Class Reference
ns3::EpcEnbApplication Class Reference
LTE Models
This application is installed inside eNBs and provides the bridge functionality for user data plane packets between the radio interface and the S1-U interface.
#include "epc-enb-application.h"
Classes
struct EpsFlowId_t
EPS flow ID structure.
Public Types
typedef void(* RxTracedCallback) (Ptr< Packet > packet)
TracedCallback signature for data Packet reception event.
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Public Member Functions
EpcEnbApplication (Ptr< Socket > lteSocket, Ptr< Socket > lteSocket6, uint16_t cellId)
Constructor.
virtual ~EpcEnbApplication (void)
Destructor.
void AddS1Interface (Ptr< Socket > s1uSocket, Ipv4Address enbAddress, Ipv4Address sgwAddress)
Add a S1-U interface to the eNB.
EpcS1apSapEnb * GetS1apSapEnb ()
EpcEnbS1SapProvider * GetS1SapProvider ()
void RecvFromLteSocket (Ptr< Socket > socket)
Method to be assigned to the recv callback of the LTE socket.
void RecvFromS1uSocket (Ptr< Socket > socket)
Method to be assigned to the recv callback of the S1-U socket.
void SetS1apSapMme (EpcS1apSapMme *s)
Set the MME side of the S1-AP SAP.
void SetS1SapUser (EpcEnbS1SapUser *s)
Set the S1 SAP User.
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Application
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void DoInitialContextSetupRequest (uint64_t mmeUeS1Id, uint16_t enbUeS1Id, std::list< EpcS1apSapEnb::ErabToBeSetupItem > erabToBeSetupList)
Initial Context Setup Request.
void DoInitialUeMessage (uint64_t imsi, uint16_t rnti)
Initial UE message function.
void DoPathSwitchRequest (EpcEnbS1SapProvider::PathSwitchRequestParameters params)
Path switch request function.
void DoPathSwitchRequestAcknowledge (uint64_t enbUeS1Id, uint64_t mmeUeS1Id, uint16_t cgi, std::list< EpcS1apSapEnb::ErabSwitchedInUplinkItem > erabToBeSwitchedInUplinkList)
Path Switch Request Acknowledge.
void DoReleaseIndication (uint64_t imsi, uint16_t rnti, uint8_t bearerId)
This function accepts bearer id corresponding to a particular UE and schedules indication of bearer release towards MME.
void DoUeContextRelease (uint16_t rnti)
UE Context Release function.
void SendToLteSocket (Ptr< Packet > packet, uint16_t rnti, uint8_t bid)
Send a packet to the UE via the LTE radio interface of the eNB.
void SendToS1uSocket (Ptr< Packet > packet, uint32_t teid)
Send a packet to the SGW via the S1-U interface.
void SetupS1Bearer (uint32_t teid, uint16_t rnti, uint8_t bid)
internal method used for the actual setup of the S1 Bearer
Private Attributes
uint16_t m_cellId
cell ID
Ipv4Address m_enbS1uAddress
address of the eNB for S1-U communications
uint16_t m_gtpuUdpPort
UDP port to be used for GTP.
std::map< uint64_t, uint16_t > m_imsiRntiMap
UE context info.
Ptr< Socket > m_lteSocket
raw packet socket to send and receive the packets to and from the LTE radio interface
Ptr< Socket > m_lteSocket6
raw packet socket to send and receive the packets to and from the LTE radio interface
std::map< uint16_t, std::map< uint8_t, uint32_t > > m_rbidTeidMap
map of maps telling for each RNTI and BID the corresponding S1-U TEID
TracedCallback< Ptr< Packet > > m_rxLteSocketPktTrace
Callback to trace RX (reception) data packets from LTE Socket.
TracedCallback< Ptr< Packet > > m_rxS1uSocketPktTrace
Callback to trace RX (reception) data packets from S1-U Socket.
EpcS1apSapEnb * m_s1apSapEnb
ENB side of the S1-AP SAP.
EpcS1apSapMme * m_s1apSapMme
MME side of the S1-AP SAP.
EpcEnbS1SapProvider * m_s1SapProvider
Provider for the S1 SAP.
EpcEnbS1SapUser * m_s1SapUser
User for the S1 SAP.
Ptr< Socket > m_s1uSocket
UDP socket to send and receive GTP-U the packets to and from the S1-U interface.
Ipv4Address m_sgwS1uAddress
address of the SGW which terminates all S1-U tunnels
std::map< uint32_t, EpsFlowId_t > m_teidRbidMap
map telling for each S1-U TEID the corresponding RNTI,BID
Friends
class MemberEpcEnbS1SapProvider< EpcEnbApplication >
allow MemberEpcEnbS1SapProvider<EpcEnbApplication> class friend access
class MemberEpcS1apSapEnb< EpcEnbApplication >
allow MemberEpcS1apSapEnb<EpcEnbApplication> class friend access
Additional Inherited Members
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This application is installed inside eNBs and provides the bridge functionality for user data plane packets between the radio interface and the S1-U interface.
Definition at line 49 of file epc-enb-application.h.
Member Typedef Documentation
RxTracedCallback
typedef void(* ns3::EpcEnbApplication::RxTracedCallback) (Ptr< Packet > packet)
TracedCallback signature for data Packet reception event.
Parameters
[in] packet The data packet sent from the internet.
Definition at line 143 of file epc-enb-application.h.
Constructor & Destructor Documentation
EpcEnbApplication()
ns3::EpcEnbApplication::EpcEnbApplication (Ptr< Socket > lteSocket, Ptr< Socket > lteSocket6, uint16_t cellId)
Constructor.
Parameters
lteSocket the socket to be used to send/receive IPv4 packets to/from the LTE radio interface
lteSocket6 the socket to be used to send/receive IPv6 packets to/from the LTE radio interface
cellId the identifier of the eNB
Definition at line 90 of file epc-enb-application.cc.
References m_lteSocket, m_lteSocket6, m_s1apSapEnb, m_s1SapProvider, ns3::MakeCallback(), MemberEpcEnbS1SapProvider< EpcEnbApplication >, MemberEpcS1apSapEnb< EpcEnbApplication >, NS_LOG_FUNCTION, RecvFromLteSocket(), and ns3::Socket::SetRecvCallback().
~EpcEnbApplication()
ns3::EpcEnbApplication::~EpcEnbApplication (void) virtual
Destructor.
Definition at line 119 of file epc-enb-application.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddS1Interface()
void ns3::EpcEnbApplication::AddS1Interface (Ptr< Socket > s1uSocket, Ipv4Address enbAddress, Ipv4Address sgwAddress)
Add a S1-U interface to the eNB.
Parameters
s1uSocket the socket to be used to send/receive packets to/from the S1-U interface connected with the SGW
enbS1uAddress the IPv4 address of the S1-U interface of this eNB
sgwS1uAddress the IPv4 address at which this eNB will be able to reach its SGW for S1-U communications
Definition at line 108 of file epc-enb-application.cc.
References m_enbS1uAddress, m_s1uSocket, m_sgwS1uAddress, ns3::MakeCallback(), NS_LOG_FUNCTION, RecvFromS1uSocket(), and ns3::Socket::SetRecvCallback().
DoDispose()
void ns3::EpcEnbApplication::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Application.
Definition at line 80 of file epc-enb-application.cc.
References m_lteSocket, m_lteSocket6, m_s1apSapEnb, m_s1SapProvider, m_s1uSocket, and NS_LOG_FUNCTION.
DoInitialContextSetupRequest()
void ns3::EpcEnbApplication::DoInitialContextSetupRequest (uint64_t mmeUeS1Id, uint16_t enbUeS1Id, std::list< EpcS1apSapEnb::ErabToBeSetupItem > erabToBeSetupList) private
Initial Context Setup Request.
Parameters
mmeUeS1Id the MME UE S1 ID
enbUeS1Id the ENB UE S1 ID
erabToBeSetupList the ERAB setup list
Definition at line 217 of file epc-enb-application.cc.
References ns3::EpcEnbS1SapUser::DataRadioBearerSetupRequestParameters::bearer, ns3::EpcEnbS1SapUser::DataRadioBearerSetupRequestParameters::bearerId, ns3::EpcEnbS1SapUser::DataRadioBearerSetupRequest(), ns3::EpcEnbS1SapUser::DataRadioBearerSetupRequestParameters::gtpTeid, ns3::EpcEnbS1SapUser::InitialContextSetupRequest(), m_imsiRntiMap, m_rbidTeidMap, m_s1SapUser, m_teidRbidMap, NS_ASSERT_MSG, NS_LOG_FUNCTION, ns3::EpcEnbS1SapUser::InitialContextSetupRequestParameters::rnti, and ns3::EpcEnbS1SapUser::DataRadioBearerSetupRequestParameters::rnti.
DoInitialUeMessage()
void ns3::EpcEnbApplication::DoInitialUeMessage (uint64_t imsi, uint16_t rnti) private
Initial UE message function.
Parameters
imsi the IMSI
rnti the RNTI
Definition at line 152 of file epc-enb-application.cc.
References ns3::EpcS1apSapMme::InitialUeMessage(), m_cellId, m_imsiRntiMap, m_s1apSapMme, and NS_LOG_FUNCTION.
DoPathSwitchRequest()
void ns3::EpcEnbApplication::DoPathSwitchRequest (EpcEnbS1SapProvider::PathSwitchRequestParameters params) private
Path switch request function.
Parameters
params PathSwitchRequestParameters
Definition at line 161 of file epc-enb-application.cc.
References ns3::EpcEnbS1SapProvider::PathSwitchRequestParameters::bearersToBeSwitched, ns3::EpcEnbS1SapProvider::PathSwitchRequestParameters::cellId, ns3::EpcS1apSapMme::ErabSwitchedInDownlinkItem::enbTeid, ns3::EpcS1apSapMme::ErabSwitchedInDownlinkItem::enbTransportLayerAddress, ns3::EpcS1apSapMme::ErabSwitchedInDownlinkItem::erabId, ns3::EpcEnbApplication::EpsFlowId_t::m_bid, m_enbS1uAddress, m_imsiRntiMap, m_rbidTeidMap, ns3::EpcEnbApplication::EpsFlowId_t::m_rnti, m_s1apSapMme, m_teidRbidMap, ns3::EpcEnbS1SapProvider::PathSwitchRequestParameters::mmeUeS1Id, NS_LOG_FUNCTION, ns3::EpcS1apSapMme::PathSwitchRequest(), and ns3::EpcEnbS1SapProvider::PathSwitchRequestParameters::rnti.
DoPathSwitchRequestAcknowledge()
void ns3::EpcEnbApplication::DoPathSwitchRequestAcknowledge (uint64_t enbUeS1Id, uint64_t mmeUeS1Id, uint16_t cgi, std::list< EpcS1apSapEnb::ErabSwitchedInUplinkItem > erabToBeSwitchedInUplinkList) private
Path Switch Request Acknowledge.
Parameters
mmeUeS1Id the MME UE S1 ID
enbUeS1Id the ENB UE S1 ID
cgi the CGI
erabToBeSwitchedInUplinkList the ERAB switched in uplink list
Definition at line 251 of file epc-enb-application.cc.
References m_imsiRntiMap, m_s1SapUser, NS_ASSERT_MSG, NS_LOG_FUNCTION, ns3::EpcEnbS1SapUser::PathSwitchRequestAcknowledge(), and ns3::EpcEnbS1SapUser::PathSwitchRequestAcknowledgeParameters::rnti.
DoReleaseIndication()
void ns3::EpcEnbApplication::DoReleaseIndication (uint64_t imsi, uint16_t rnti, uint8_t bearerId) private
This function accepts bearer id corresponding to a particular UE and schedules indication of bearer release towards MME.
Parameters
imsi maps to mmeUeS1Id
rnti maps to enbUeS1Id
bearerId Bearer Identity which is to be de-activated
Definition at line 364 of file epc-enb-application.cc.
References ns3::EpcS1apSapMme::ErabToBeReleasedIndication::erabId, ns3::EpcS1apSapMme::ErabReleaseIndication(), m_s1apSapMme, and NS_LOG_FUNCTION.
DoUeContextRelease()
void ns3::EpcEnbApplication::DoUeContextRelease (uint16_t rnti) private
UE Context Release function.
Parameters
rnti the RNTI
Definition at line 197 of file epc-enb-application.cc.
References m_rbidTeidMap, m_teidRbidMap, NS_LOG_FUNCTION, and NS_LOG_INFO.
GetS1apSapEnb()
EpcS1apSapEnb * ns3::EpcEnbApplication::GetS1apSapEnb ()
Returns
the ENB side of the S1-AP SAP
Definition at line 146 of file epc-enb-application.cc.
References m_s1apSapEnb.
GetS1SapProvider()
EpcEnbS1SapProvider * ns3::EpcEnbApplication::GetS1SapProvider ()
Returns
the S1 SAP Provider
Definition at line 133 of file epc-enb-application.cc.
References m_s1SapProvider.
GetTypeId()
TypeId ns3::EpcEnbApplication::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 62 of file epc-enb-application.cc.
References m_rxLteSocketPktTrace, m_rxS1uSocketPktTrace, ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
RecvFromLteSocket()
void ns3::EpcEnbApplication::RecvFromLteSocket (Ptr< Socket > socket)
Method to be assigned to the recv callback of the LTE socket.
It is called when the eNB receives a data packet from the radio interface that is to be forwarded to the SGW.
Parameters
socket pointer to the LTE socket
Definition at line 265 of file epc-enb-application.cc.
References ns3::Packet::Copy(), ns3::EpsBearerTag::GetBid(), ns3::EpsBearerTag::GetRnti(), m_lteSocket, m_lteSocket6, m_rbidTeidMap, m_rxLteSocketPktTrace, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, NS_LOG_WARN, ns3::Socket::Recv(), ns3::Packet::RemovePacketTag(), and SendToS1uSocket().
Referenced by EpcEnbApplication().
RecvFromS1uSocket()
void ns3::EpcEnbApplication::RecvFromS1uSocket (Ptr< Socket > socket)
Method to be assigned to the recv callback of the S1-U socket.
It is called when the eNB receives a data packet from the SGW that is to be forwarded to the UE.
Parameters
socket pointer to the S1-U socket
Definition at line 300 of file epc-enb-application.cc.
References ns3::Packet::Copy(), ns3::GtpuHeader::GetTeid(), m_cellId, m_rxS1uSocketPktTrace, m_s1uSocket, m_teidRbidMap, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_WARN, ns3::Socket::Recv(), ns3::Packet::RemoveHeader(), and SendToLteSocket().
Referenced by AddS1Interface().
SendToLteSocket()
void ns3::EpcEnbApplication::SendToLteSocket (Ptr< Packet > packet, uint16_t rnti, uint8_t bid) private
Send a packet to the UE via the LTE radio interface of the eNB.
Parameters
packet t
rnti maps to enbUeS1Id
bid the EPS Bearer IDentifier
Definition at line 321 of file epc-enb-application.cc.
References ns3::Packet::AddPacketTag(), ns3::Packet::CopyData(), ns3::Packet::GetSize(), m_lteSocket, m_lteSocket6, NS_ABORT_MSG, NS_ASSERT, NS_LOG_FUNCTION, and ns3::Socket::Send().
Referenced by RecvFromS1uSocket().
SendToS1uSocket()
void ns3::EpcEnbApplication::SendToS1uSocket (Ptr< Packet > packet, uint32_t teid) private
Send a packet to the SGW via the S1-U interface.
Parameters
packet packet to be sent
teid the Tunnel Enpoint IDentifier
Definition at line 350 of file epc-enb-application.cc.
References ns3::Packet::AddHeader(), ns3::GtpuHeader::GetSerializedSize(), ns3::Packet::GetSize(), m_gtpuUdpPort, m_s1uSocket, m_sgwS1uAddress, NS_LOG_FUNCTION, ns3::Socket::SendTo(), ns3::GtpuHeader::SetLength(), and ns3::GtpuHeader::SetTeid().
Referenced by RecvFromLteSocket().
SetS1apSapMme()
void ns3::EpcEnbApplication::SetS1apSapMme (EpcS1apSapMme * s)
Set the MME side of the S1-AP SAP.
Parameters
s the MME side of the S1-AP SAP
Definition at line 139 of file epc-enb-application.cc.
References m_s1apSapMme.
SetS1SapUser()
void ns3::EpcEnbApplication::SetS1SapUser (EpcEnbS1SapUser * s)
Set the S1 SAP User.
Parameters
s the S1 SAP User
Definition at line 126 of file epc-enb-application.cc.
References m_s1SapUser.
SetupS1Bearer()
void ns3::EpcEnbApplication::SetupS1Bearer (uint32_t teid, uint16_t rnti, uint8_t bid) private
internal method used for the actual setup of the S1 Bearer
Parameters
teid the Tunnel Endpoint IDentifier
rnti maps to enbUeS1Id
bid the S1-U Bearer IDentifier
Friends And Related Function Documentation
MemberEpcEnbS1SapProvider< EpcEnbApplication >
friend class MemberEpcEnbS1SapProvider< EpcEnbApplication > friend
allow MemberEpcEnbS1SapProvider<EpcEnbApplication> class friend access
Definition at line 1 of file epc-enb-application.h.
Referenced by EpcEnbApplication().
MemberEpcS1apSapEnb< EpcEnbApplication >
friend class MemberEpcS1apSapEnb< EpcEnbApplication > friend
allow MemberEpcS1apSapEnb<EpcEnbApplication> class friend access
Definition at line 1 of file epc-enb-application.h.
Referenced by EpcEnbApplication().
Member Data Documentation
m_cellId
uint16_t ns3::EpcEnbApplication::m_cellId private
cell ID
Definition at line 328 of file epc-enb-application.h.
Referenced by DoInitialUeMessage(), and RecvFromS1uSocket().
m_enbS1uAddress
Ipv4Address ns3::EpcEnbApplication::m_enbS1uAddress private
address of the eNB for S1-U communications
Definition at line 276 of file epc-enb-application.h.
Referenced by AddS1Interface(), and DoPathSwitchRequest().
m_gtpuUdpPort
uint16_t ns3::EpcEnbApplication::m_gtpuUdpPort private
UDP port to be used for GTP.
Definition at line 298 of file epc-enb-application.h.
Referenced by SendToS1uSocket().
m_imsiRntiMap
std::map<uint64_t, uint16_t> ns3::EpcEnbApplication::m_imsiRntiMap private
UE context info.
Definition at line 326 of file epc-enb-application.h.
Referenced by DoInitialContextSetupRequest(), DoInitialUeMessage(), DoPathSwitchRequest(), and DoPathSwitchRequestAcknowledge().
m_lteSocket
Ptr<Socket> ns3::EpcEnbApplication::m_lteSocket private
raw packet socket to send and receive the packets to and from the LTE radio interface
Definition at line 261 of file epc-enb-application.h.
Referenced by EpcEnbApplication(), DoDispose(), RecvFromLteSocket(), and SendToLteSocket().
m_lteSocket6
Ptr<Socket> ns3::EpcEnbApplication::m_lteSocket6 private
raw packet socket to send and receive the packets to and from the LTE radio interface
Definition at line 266 of file epc-enb-application.h.
Referenced by EpcEnbApplication(), DoDispose(), RecvFromLteSocket(), and SendToLteSocket().
m_rbidTeidMap
std::map<uint16_t, std::map<uint8_t, uint32_t> > ns3::EpcEnbApplication::m_rbidTeidMap private
map of maps telling for each RNTI and BID the corresponding S1-U TEID
Definition at line 287 of file epc-enb-application.h.
Referenced by DoInitialContextSetupRequest(), DoPathSwitchRequest(), DoUeContextRelease(), and RecvFromLteSocket().
m_rxLteSocketPktTrace
TracedCallback<Ptr<Packet> > ns3::EpcEnbApplication::m_rxLteSocketPktTrace private
Callback to trace RX (reception) data packets from LTE Socket.
Definition at line 333 of file epc-enb-application.h.
Referenced by GetTypeId(), and RecvFromLteSocket().
m_rxS1uSocketPktTrace
TracedCallback<Ptr<Packet> > ns3::EpcEnbApplication::m_rxS1uSocketPktTrace private
Callback to trace RX (reception) data packets from S1-U Socket.
Definition at line 338 of file epc-enb-application.h.
Referenced by GetTypeId(), and RecvFromS1uSocket().
m_s1apSapEnb
EpcS1apSapEnb* ns3::EpcEnbApplication::m_s1apSapEnb private
ENB side of the S1-AP SAP.
Definition at line 320 of file epc-enb-application.h.
Referenced by EpcEnbApplication(), DoDispose(), and GetS1apSapEnb().
m_s1apSapMme
EpcS1apSapMme* ns3::EpcEnbApplication::m_s1apSapMme private
MME side of the S1-AP SAP.
Definition at line 314 of file epc-enb-application.h.
Referenced by DoInitialUeMessage(), DoPathSwitchRequest(), DoReleaseIndication(), and SetS1apSapMme().
m_s1SapProvider
EpcEnbS1SapProvider* ns3::EpcEnbApplication::m_s1SapProvider private
Provider for the S1 SAP.
Definition at line 303 of file epc-enb-application.h.
Referenced by EpcEnbApplication(), DoDispose(), and GetS1SapProvider().
m_s1SapUser
EpcEnbS1SapUser* ns3::EpcEnbApplication::m_s1SapUser private
User for the S1 SAP.
Definition at line 308 of file epc-enb-application.h.
Referenced by DoInitialContextSetupRequest(), DoPathSwitchRequestAcknowledge(), and SetS1SapUser().
m_s1uSocket
Ptr<Socket> ns3::EpcEnbApplication::m_s1uSocket private
UDP socket to send and receive GTP-U the packets to and from the S1-U interface.
Definition at line 271 of file epc-enb-application.h.
Referenced by AddS1Interface(), DoDispose(), RecvFromS1uSocket(), and SendToS1uSocket().
m_sgwS1uAddress
Ipv4Address ns3::EpcEnbApplication::m_sgwS1uAddress private
address of the SGW which terminates all S1-U tunnels
Definition at line 281 of file epc-enb-application.h.
Referenced by AddS1Interface(), and SendToS1uSocket().
m_teidRbidMap
std::map<uint32_t, EpsFlowId_t> ns3::EpcEnbApplication::m_teidRbidMap private
map telling for each S1-U TEID the corresponding RNTI,BID
Definition at line 293 of file epc-enb-application.h.
Referenced by DoInitialContextSetupRequest(), DoPathSwitchRequest(), DoUeContextRelease(), and RecvFromS1uSocket().
The documentation for this class was generated from the following files:
src/lte/model/epc-enb-application.h
src/lte/model/epc-enb-application.cc