ns-3: TestUtils Class Reference
TestUtils Class Reference
LTE Models » lte module tests | Test suites
Contains ASN encoding test utility functions.
Static Public Member Functions
static void LogPacketContents (Ptr< Packet > pkt)
Function to log packet contents.
template<class T >
static void LogPacketInfo (T source, std::string s)
Function to log packet info.
static std::string sprintPacketContentsBin (Ptr< Packet > pkt)
Function to convert packet contents in binary format.
static std::string sprintPacketContentsHex (Ptr< Packet > pkt)
Function to convert packet contents in hex format.
Detailed Description
Contains ASN encoding test utility functions.
Definition at line 43 of file test-asn1-encoding.cc.
Member Function Documentation
LogPacketContents()
static void TestUtils::LogPacketContents (Ptr< Packet > pkt) inline static
Function to log packet contents.
Parameters
pkt the packet
Definition at line 86 of file test-asn1-encoding.cc.
References NS_LOG_DEBUG, ns3::TestUtils::sprintPacketContentsBin(), and ns3::TestUtils::sprintPacketContentsHex().
Referenced by RrcConnectionRequestTestCase::DoRun(), RrcConnectionSetupTestCase::DoRun(), RrcConnectionSetupCompleteTestCase::DoRun(), RrcConnectionReconfigurationCompleteTestCase::DoRun(), RrcConnectionReconfigurationTestCase::DoRun(), HandoverPreparationInfoTestCase::DoRun(), RrcConnectionReestablishmentRequestTestCase::DoRun(), RrcConnectionReestablishmentTestCase::DoRun(), RrcConnectionReestablishmentCompleteTestCase::DoRun(), RrcConnectionRejectTestCase::DoRun(), and MeasurementReportTestCase::DoRun().
LogPacketInfo()
template<class T > static void TestUtils::LogPacketInfo (T source, std::string s) inline static
Function to log packet info.
Parameters
source T
s the string
Definition at line 99 of file test-asn1-encoding.cc.
References NS_LOG_DEBUG.
sprintPacketContentsBin()
static std::string TestUtils::sprintPacketContentsBin (Ptr< Packet > pkt) inline static
Function to convert packet contents in binary format.
Parameters
pkt the packet
Returns
the text string
Definition at line 69 of file test-asn1-encoding.cc.
References ns3::Packet::CopyData(), and ns3::Packet::GetSize().
sprintPacketContentsHex()
static std::string TestUtils::sprintPacketContentsHex (Ptr< Packet > pkt) inline static
Function to convert packet contents in hex format.
Parameters
pkt the packet
Returns
the text string
Definition at line 51 of file test-asn1-encoding.cc.
References ns3::Packet::CopyData(), and ns3::Packet::GetSize().
The documentation for this class was generated from the following file:
src/lte/test/test-asn1-encoding.cc