ns-3: ns3::LteUePhySapUser Class Reference
ns3::LteUePhySapUser Class Reference abstract
Service Access Point (SAP) offered by the PHY to the MAC.
#include "lte-ue-phy-sap.h"
Public Member Functions
virtual ~LteUePhySapUser ()
virtual void ReceiveLteControlMessage (Ptr< LteControlMessage > msg)=0
Receive SendLteControlMessage (PDCCH map, CQI feedbacks) using the ideal control channel.
virtual void ReceivePhyPdu (Ptr< Packet > p)=0
Receive Phy Pdu funtion.
virtual void SubframeIndication (uint32_t frameNo, uint32_t subframeNo)=0
Trigger the start from a new frame (input from Phy layer)
Detailed Description
Service Access Point (SAP) offered by the PHY to the MAC.
This is the PHY SAP User, i.e., the part of the SAP that contains the MAC methods called by the PHY
Definition at line 81 of file lte-ue-phy-sap.h.
Constructor & Destructor Documentation
~LteUePhySapUser()
ns3::LteUePhySapUser::~LteUePhySapUser () virtual
Definition at line 33 of file lte-ue-phy-sap.cc.
Member Function Documentation
ReceiveLteControlMessage()
virtual void ns3::LteUePhySapUser::ReceiveLteControlMessage (Ptr< LteControlMessage > msg) pure virtual
Receive SendLteControlMessage (PDCCH map, CQI feedbacks) using the ideal control channel.
Parameters
msg the Ideal Control Message to receive
Implemented in ns3::UeMemberLteUePhySapUser.
Referenced by ns3::LteUePhy::ReceiveLteControlMessageList().
ReceivePhyPdu()
virtual void ns3::LteUePhySapUser::ReceivePhyPdu (Ptr< Packet > p) pure virtual
Receive Phy Pdu funtion.
It is called by the Phy to notify the MAC of the reception of a new PHY-PDU
Parameters
p
Implemented in ns3::UeMemberLteUePhySapUser.
Referenced by ns3::LteUePhy::PhyPduReceived().
SubframeIndication()
virtual void ns3::LteUePhySapUser::SubframeIndication (uint32_t frameNo, uint32_t subframeNo) pure virtual
Trigger the start from a new frame (input from Phy layer)
Parameters
frameNo frame number
subframeNo subframe number
Implemented in ns3::UeMemberLteUePhySapUser.
Referenced by ns3::LteUePhy::SubframeIndication().
The documentation for this class was generated from the following files:
src/lte/model/lte-ue-phy-sap.h
src/lte/model/lte-ue-phy-sap.cc