ns-3: ns3::PieQueueDisc Class Reference
ns3::PieQueueDisc Class Reference
Traffic-control
Implements PIE Active Queue Management discipline.
#include "pie-queue-disc.h"
Public Types
enum BurstStateT { NO_BURST , IN_BURST , IN_BURST_PROTECTING }
Burst types.
Public Types inherited from ns3::QueueDisc
typedef Queue< QueueDiscItem > InternalQueue
Internal queues store QueueDiscItem objects.
typedef std::function< void(Ptr< QueueDiscItem >)> SendCallback
Callback invoked to send a packet to the receiving object when Run is called.
enum WakeMode { WAKE_ROOT = 0x00 , WAKE_CHILD = 0x01 }
Used to determine whether the queue disc itself or its children must be activated when a netdevice wakes a transmission queue.
Public Member Functions
PieQueueDisc ()
PieQueueDisc Constructor.
virtual ~PieQueueDisc ()
PieQueueDisc Destructor.
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Time GetQueueDelay (void)
Get queue delay.
Public Member Functions inherited from ns3::QueueDisc
QueueDisc (QueueDiscSizePolicy policy, QueueSizeUnit unit)
Constructor.
QueueDisc (QueueDiscSizePolicy policy=QueueDiscSizePolicy::SINGLE_INTERNAL_QUEUE)
Constructor.
virtual ~QueueDisc ()
void AddInternalQueue (Ptr< InternalQueue > queue)
Add an internal queue to the tail of the list of queues.
void AddPacketFilter (Ptr< PacketFilter > filter)
Add a packet filter to the tail of the list of filters used to classify packets.
void AddQueueDiscClass (Ptr< QueueDiscClass > qdClass)
Add a queue disc class to the tail of the list of classes.
int32_t Classify (Ptr< QueueDiscItem > item)
Classify a packet by calling the packet filters, one at a time, until either a filter able to classify the packet is found or all the filters have been processed.
Ptr< QueueDiscItem > Dequeue (void)
Extract from the queue disc the packet that has been dequeued by calling Peek, if any, or call the private DoDequeue method (which must be implemented by derived classes) to dequeue a packet, otherwise.
bool Enqueue (Ptr< QueueDiscItem > item)
Pass a packet to store to the queue discipline.
QueueSize GetCurrentSize (void)
Get the current size of the queue disc in bytes, if operating in bytes mode, or packets, otherwise.
Ptr< InternalQueue > GetInternalQueue (std::size_t i) const
Get the i-th internal queue.
QueueSize GetMaxSize (void) const
Get the maximum size of the queue disc.
uint32_t GetNBytes (void) const
Get the amount of bytes stored by the queue disc.
Ptr< NetDeviceQueueInterface > GetNetDeviceQueueInterface (void) const
std::size_t GetNInternalQueues (void) const
Get the number of internal queues.
std::size_t GetNPacketFilters (void) const
Get the number of packet filters.
uint32_t GetNPackets (void) const
Get the number of packets stored by the queue disc.
std::size_t GetNQueueDiscClasses (void) const
Get the number of queue disc classes.
Ptr< PacketFilter > GetPacketFilter (std::size_t i) const
Get the i-th packet filter.
Ptr< QueueDiscClass > GetQueueDiscClass (std::size_t i) const
Get the i-th queue disc class.
virtual uint32_t GetQuota (void) const
Get the maximum number of dequeue operations following a packet enqueue.
SendCallback GetSendCallback (void) const
const Stats & GetStats (void)
Retrieve all the collected statistics.
virtual WakeMode GetWakeMode (void) const
When setting up the wake callbacks on the netdevice queues, it is necessary to determine which queue disc (the root queue disc or one of its children) should be activated when the netdevice wakes one of its transmission queues.
Ptr< const QueueDiscItem > Peek (void)
Get a copy of the next packet the queue discipline will extract.
void Run (void)
Modelled after the Linux function __qdisc_run (net/sched/sch_generic.c) Dequeues multiple packets, until a quota is exceeded or sending a packet to the device failed.
bool SetMaxSize (QueueSize size)
Set the maximum size of the queue disc.
void SetNetDeviceQueueInterface (Ptr< NetDeviceQueueInterface > ndqi)
virtual void SetQuota (const uint32_t quota)
Set the maximum number of dequeue operations following a packet enqueue.
void SetSendCallback (SendCallback func)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::QueueDisc
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static constexpr const char * FORCED_DROP = "Forced drop"
Drops due to queue limit: reactive.
static constexpr const char * UNFORCED_DROP = "Unforced drop"
Early probability drops: proactive.
static constexpr const char * UNFORCED_MARK = "Unforced mark"
Early probability marks: proactive.
Static Public Attributes inherited from ns3::QueueDisc
static constexpr const char * CHILD_QUEUE_DISC_DROP = "(Dropped by child queue disc) "
Packet dropped by a child queue disc.
static constexpr const char * CHILD_QUEUE_DISC_MARK = "(Marked by child queue disc) "
Packet marked by a child queue disc.
static constexpr const char * INTERNAL_QUEUE_DROP = "Dropped by internal queue"
Packet dropped by an internal queue.
Protected Member Functions
virtual void DoDispose (void)
Dispose of the object.
Protected Member Functions inherited from ns3::QueueDisc
void DoInitialize (void)
Check whether the configuration is correct and initialize parameters.
void DropAfterDequeue (Ptr< const QueueDiscItem > item, const char *reason)
Perform the actions required when the queue disc is notified of a packet dropped after dequeue.
void DropBeforeEnqueue (Ptr< const QueueDiscItem > item, const char *reason)
Perform the actions required when the queue disc is notified of a packet dropped before enqueue.
bool Mark (Ptr< QueueDiscItem > item, const char *reason)
Marks the given packet and, if successful, updates the counters associated with the given reason.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void CalculateP ()
Periodically update the drop probability based on the delay samples: not only the current delay sample but also the trend where the delay is going, up or down.
virtual bool CheckConfig (void)
Check whether the current configuration is correct.
virtual Ptr< QueueDiscItem > DoDequeue (void)
This function actually extracts a packet from the queue disc.
virtual bool DoEnqueue (Ptr< QueueDiscItem > item)
This function actually enqueues a packet into the queue disc.
bool DropEarly (Ptr< QueueDiscItem > item, uint32_t qSize)
Check if a packet needs to be dropped due to probability drop.
virtual void InitializeParams (void)
Initialize the queue parameters.
Private Attributes
double m_a
Parameter to pie controller.
double m_accuProb
Accumulated drop probability.
bool m_active
Indicates whether PIE is in active state or not.
Time m_activeThreshold
Threshold for activating PIE (disabled by default)
double m_avgDqRate
Time averaged dequeue rate.
double m_b
Parameter to pie controller.
Time m_burstAllowance
Current max burst value in seconds that is allowed before random drops kick in.
uint32_t m_burstReset
Used to reset value of burst allowance.
BurstStateT m_burstState
Used to determine the current state of burst.
uint64_t m_dqCount
Number of bytes departed since current measurement cycle starts.
double m_dqStart
Start timestamp of current measurement cycle.
uint32_t m_dqThreshold
Minimum queue size in bytes before dequeue rate is measured.
double m_dropProb
Variable used in calculation of drop probability.
bool m_inMeasurement
Indicates whether we are in a measurement cycle.
bool m_isCapDropAdjustment
Enable/Disable Cap Drop Adjustment feature mentioned in RFC 8033.
double m_markEcnTh
ECN marking threshold (default 10% as suggested in RFC 8033)
Time m_maxBurst
Maximum burst allowed before random early dropping kicks in.
uint32_t m_meanPktSize
Average packet size in bytes.
Time m_qDelay
Current value of queue delay.
Time m_qDelayOld
Old value of queue delay.
Time m_qDelayRef
Desired queue delay.
EventId m_rtrsEvent
Event used to decide the decision of interval of drop probability calculation.
Time m_sUpdate
Start time of the update timer.
Time m_tUpdate
Time period after which CalculateP () is called.
bool m_useDerandomization
Enable Derandomization feature mentioned in RFC 8033.
bool m_useDqRateEstimator
Enable/Disable usage of dequeue rate estimator for queue delay calculation.
bool m_useEcn
Enable ECN Marking functionality.
Ptr< UniformRandomVariable > m_uv
Rng stream.
Static Private Attributes
static const uint64_t DQCOUNT_INVALID = std::numeric_limits<uint64_t>::max()
Invalid dqCount value.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implements PIE Active Queue Management discipline.
Introspection did not find any typical Config paths.
Attributes
MeanPktSize: Average of packet size
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 1000
Flags: construct write read
A: Value of alpha
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0.125
Flags: construct write read
B: Value of beta
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 1.25
Flags: construct write read
Tupdate: Time period to calculate drop probability
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1.5e+07ns
Flags: construct write read
Supdate: Start time of the update timer
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
MaxSize: The maximum number of packets accepted by this queue disc
Set with class: QueueSizeValue
Underlying type: QueueSize
Initial value: 25p
Flags: construct write read
DequeueThreshold: Minimum queue size in bytes before dequeue rate is measured
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 16384
Flags: construct write read
QueueDelayReference: Desired queue delay
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1.5e+07ns
Flags: construct write read
MaxBurstAllowance: Current max burst allowance before random drop
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1.5e+07ns
Flags: construct write read
UseDequeueRateEstimator: Enable/Disable usage of Dequeue Rate Estimator
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
UseCapDropAdjustment: Enable/Disable Cap Drop Adjustment feature mentioned in RFC 8033
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
UseEcn: True to use ECN (packets are marked instead of being dropped)
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
MarkEcnThreshold: ECN marking threshold (RFC 8033 suggests 0.1 (i.e., 10%) default)
Set with class: ns3::DoubleValue
Underlying type: double 0:1
Initial value: 0.1
Flags: construct write read
UseDerandomization: Enable/Disable Derandomization feature mentioned in RFC 8033
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
ActiveThreshold: Threshold for activating PIE (disabled by default)
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +9.22337e+18ns
Flags: construct write read
Attributes defined in parent class ns3::QueueDisc
Quota: The maximum number of packets dequeued in a qdisc run
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 64
Flags: construct write read
InternalQueueList: The list of internal queues.
Set with class: ns3::ObjectPtrContainerValue
Underlying type: ns3::Ptr< ns3::Queue<QueueDiscItem>>
Flags: read
PacketFilterList: The list of packet filters.
Set with class: ns3::ObjectPtrContainerValue
Underlying type: ns3::Ptr< ns3::PacketFilter>
Flags: read
QueueDiscClassList: The list of queue disc classes.
Set with class: ns3::ObjectPtrContainerValue
Underlying type: ns3::Ptr< ns3::QueueDiscClass>
Flags: read
No TraceSources are defined for this type.
TraceSources defined in parent class ns3::QueueDisc
Enqueue: Enqueue a packet in the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
Dequeue: Dequeue a packet from the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
Requeue: Requeue a packet in the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
Drop: Drop a packet stored in the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
DropBeforeEnqueue: Drop a packet before enqueue
Callback signature: ns3::QueueDiscItem::TracedCallback
DropAfterDequeue: Drop a packet after dequeue
Callback signature: ns3::QueueDiscItem::TracedCallback
Mark: Mark a packet stored in the queue disc
Callback signature: ns3::QueueDiscItem::TracedCallback
PacketsInQueue: Number of packets currently stored in the queue disc
Callback signature: ns3::TracedValueCallback::Uint32
BytesInQueue: Number of bytes currently stored in the queue disc
Callback signature: ns3::TracedValueCallback::Uint32
SojournTime: Sojourn time of the last packet dequeued from the queue disc
Callback signature: ns3::Time::TracedCallback
Size of this type is 1248 bytes (on a 64-bit architecture).
Definition at line 52 of file pie-queue-disc.h.
Member Enumeration Documentation
BurstStateT
enum ns3::PieQueueDisc::BurstStateT
Burst types.
Enumerator
NO_BURST
IN_BURST
IN_BURST_PROTECTING
Definition at line 74 of file pie-queue-disc.h.
Constructor & Destructor Documentation
PieQueueDisc()
ns3::PieQueueDisc::PieQueueDisc ()
PieQueueDisc Constructor.
Definition at line 130 of file pie-queue-disc.cc.
References CalculateP(), m_rtrsEvent, m_sUpdate, m_uv, NS_LOG_FUNCTION, and ns3::Simulator::Schedule().
~PieQueueDisc()
ns3::PieQueueDisc::~PieQueueDisc () virtual
PieQueueDisc Destructor.
Definition at line 138 of file pie-queue-disc.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AssignStreams()
int64_t ns3::PieQueueDisc::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 159 of file pie-queue-disc.cc.
References m_uv, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
CalculateP()
void ns3::PieQueueDisc::CalculateP () private
Periodically update the drop probability based on the delay samples: not only the current delay sample but also the trend where the delay is going, up or down.
Definition at line 304 of file pie-queue-disc.cc.
References BURST_RESET_TIMEOUT, DQCOUNT_INVALID, ns3::QueueDisc::GetInternalQueue(), ns3::Time::GetMilliSeconds(), ns3::QueueDisc::GetNBytes(), ns3::Time::GetSeconds(), IN_BURST, IN_BURST_PROTECTING, m_a, m_avgDqRate, m_b, m_burstAllowance, m_burstReset, m_burstState, m_dqCount, m_dropProb, m_isCapDropAdjustment, m_qDelay, m_qDelayOld, m_qDelayRef, m_rtrsEvent, m_tUpdate, m_useDqRateEstimator, NO_BURST, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), and ns3::Seconds().
Referenced by PieQueueDisc().
CheckConfig()
bool ns3::PieQueueDisc::CheckConfig (void) private virtual
Check whether the current configuration is correct.
Default objects (such as internal queues) might be created by this method to ensure the configuration is correct. This method is automatically called at simulation initialization time, and it is called before the InitializeParams () method. It is appropriate to promote parameter initialization to this method if it aids in checking for correct configuration.
See also
QueueDisc::InitializeParams
Returns
true if the configuration is correct, false otherwise
Implements ns3::QueueDisc.
Definition at line 517 of file pie-queue-disc.cc.
References ns3::QueueDisc::AddInternalQueue(), ns3::CreateObjectWithAttributes(), ns3::QueueDisc::GetMaxSize(), ns3::QueueDisc::GetNInternalQueues(), ns3::QueueDisc::GetNPacketFilters(), ns3::QueueDisc::GetNQueueDiscClasses(), NS_LOG_ERROR, and NS_LOG_FUNCTION.
DoDequeue()
Ptr< QueueDiscItem > ns3::PieQueueDisc::DoDequeue (void) private virtual
This function actually extracts a packet from the queue disc.
Returns
0 if the operation was not successful; the item otherwise.
Implements ns3::QueueDisc.
Definition at line 441 of file pie-queue-disc.cc.
References ns3::QueueDisc::GetInternalQueue(), ns3::QueueDisc::GetNBytes(), ns3::Time::GetSeconds(), m_avgDqRate, m_dqCount, m_dqStart, m_dqThreshold, m_inMeasurement, m_qDelay, m_useDqRateEstimator, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, pktSize, and ns3::Seconds().
DoDispose()
void ns3::PieQueueDisc::DoDispose (void) protected virtual
Dispose of the object.
Reimplemented from ns3::QueueDisc.
Definition at line 144 of file pie-queue-disc.cc.
References ns3::EventId::Cancel(), ns3::QueueDisc::DoDispose(), m_rtrsEvent, m_uv, and NS_LOG_FUNCTION.
DoEnqueue()
bool ns3::PieQueueDisc::DoEnqueue (Ptr< QueueDiscItem > item) private virtual
This function actually enqueues a packet into the queue disc.
Parameters
item item to enqueue
Returns
True if the operation was successful; false otherwise
Implements ns3::QueueDisc.
Definition at line 167 of file pie-queue-disc.cc.
References ns3::QueueDisc::DropBeforeEnqueue(), DropEarly(), FORCED_DROP, ns3::QueueDisc::GetCurrentSize(), ns3::QueueDisc::GetInternalQueue(), ns3::QueueDisc::GetMaxSize(), ns3::Time::GetMilliSeconds(), ns3::QueueDisc::GetNBytes(), ns3::QueueDisc::GetNPackets(), ns3::Time::GetSeconds(), ns3::QueueSize::GetValue(), m_accuProb, m_active, m_activeThreshold, m_avgDqRate, m_burstAllowance, m_dqCount, m_dqStart, m_dropProb, m_inMeasurement, m_markEcnTh, m_maxBurst, m_qDelay, m_qDelayOld, m_useEcn, ns3::QueueDisc::Mark(), ns3::Time::Max(), ns3::Simulator::Now(), NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Seconds(), UNFORCED_DROP, and UNFORCED_MARK.
DropEarly()
bool ns3::PieQueueDisc::DropEarly (Ptr< QueueDiscItem > item, uint32_t qSize) private
Check if a packet needs to be dropped due to probability drop.
Parameters
item queue item
qSize queue size
Returns
0 for no drop, 1 for drop
Definition at line 240 of file pie-queue-disc.cc.
References ns3::BYTES, ns3::QueueDisc::GetMaxSize(), ns3::Time::GetSeconds(), ns3::UniformRandomVariable::GetValue(), IN_BURST_PROTECTING, m_accuProb, m_burstAllowance, m_burstState, m_dropProb, m_maxBurst, m_meanPktSize, m_qDelayOld, m_qDelayRef, m_useDerandomization, m_uv, NO_BURST, NS_LOG_FUNCTION, ns3::PACKETS, and packetSize.
Referenced by DoEnqueue().
GetQueueDelay()
Time ns3::PieQueueDisc::GetQueueDelay (void)
Get queue delay.
Returns
The current queue delay.
Definition at line 153 of file pie-queue-disc.cc.
References m_qDelay.
GetTypeId()
TypeId ns3::PieQueueDisc::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 43 of file pie-queue-disc.cc.
References ns3::QueueDisc::GetMaxSize(), m_a, m_activeThreshold, m_b, m_dqThreshold, m_isCapDropAdjustment, m_markEcnTh, m_maxBurst, m_meanPktSize, m_qDelayRef, m_sUpdate, m_tUpdate, m_useDerandomization, m_useDqRateEstimator, m_useEcn, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeDoubleAccessor(), ns3::MakeQueueSizeAccessor(), ns3::MakeQueueSizeChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeUintegerAccessor(), ns3::Time::Max(), ns3::MilliSeconds(), ns3::Seconds(), ns3::QueueDisc::SetMaxSize(), and ns3::TypeId::SetParent().
InitializeParams()
void ns3::PieQueueDisc::InitializeParams (void) private virtual
Initialize the queue parameters.
Implements ns3::QueueDisc.
Definition at line 226 of file pie-queue-disc.cc.
References DQCOUNT_INVALID, m_accuProb, m_active, m_avgDqRate, m_burstState, m_dqCount, m_dqStart, m_dropProb, m_inMeasurement, m_qDelayOld, NO_BURST, and ns3::Seconds().
Member Data Documentation
DQCOUNT_INVALID
const uint64_t ns3::PieQueueDisc::DQCOUNT_INVALID = std::numeric_limits<uint64_t>::max() static private
Invalid dqCount value.
Definition at line 134 of file pie-queue-disc.h.
Referenced by CalculateP(), and InitializeParams().
FORCED_DROP
constexpr const char* ns3::PieQueueDisc::FORCED_DROP = "Forced drop" static constexpr
Drops due to queue limit: reactive.
Definition at line 99 of file pie-queue-disc.h.
Referenced by DoEnqueue().
m_a
double ns3::PieQueueDisc::m_a private
Parameter to pie controller.
Definition at line 142 of file pie-queue-disc.h.
Referenced by CalculateP(), and GetTypeId().
m_accuProb
double ns3::PieQueueDisc::m_accuProb private
Accumulated drop probability.
Definition at line 165 of file pie-queue-disc.h.
Referenced by DoEnqueue(), DropEarly(), and InitializeParams().
m_active
bool ns3::PieQueueDisc::m_active private
Indicates whether PIE is in active state or not.
Definition at line 166 of file pie-queue-disc.h.
Referenced by DoEnqueue(), and InitializeParams().
m_activeThreshold
Time ns3::PieQueueDisc::m_activeThreshold private
Threshold for activating PIE (disabled by default)
Definition at line 150 of file pie-queue-disc.h.
Referenced by DoEnqueue(), and GetTypeId().
m_avgDqRate
double ns3::PieQueueDisc::m_avgDqRate private
Time averaged dequeue rate.
Definition at line 160 of file pie-queue-disc.h.
Referenced by CalculateP(), DoDequeue(), DoEnqueue(), and InitializeParams().
m_b
double ns3::PieQueueDisc::m_b private
Parameter to pie controller.
Definition at line 143 of file pie-queue-disc.h.
Referenced by CalculateP(), and GetTypeId().
m_burstAllowance
Time ns3::PieQueueDisc::m_burstAllowance private
Current max burst value in seconds that is allowed before random drops kick in.
Definition at line 156 of file pie-queue-disc.h.
Referenced by CalculateP(), DoEnqueue(), and DropEarly().
m_burstReset
uint32_t ns3::PieQueueDisc::m_burstReset private
Used to reset value of burst allowance.
Definition at line 157 of file pie-queue-disc.h.
Referenced by CalculateP().
m_burstState
BurstStateT ns3::PieQueueDisc::m_burstState private
Used to determine the current state of burst.
Definition at line 158 of file pie-queue-disc.h.
Referenced by CalculateP(), DropEarly(), and InitializeParams().
m_dqCount
uint64_t ns3::PieQueueDisc::m_dqCount private
Number of bytes departed since current measurement cycle starts.
Definition at line 162 of file pie-queue-disc.h.
Referenced by CalculateP(), DoDequeue(), DoEnqueue(), and InitializeParams().
m_dqStart
double ns3::PieQueueDisc::m_dqStart private
Start timestamp of current measurement cycle.
Definition at line 161 of file pie-queue-disc.h.
Referenced by DoDequeue(), DoEnqueue(), and InitializeParams().
m_dqThreshold
uint32_t ns3::PieQueueDisc::m_dqThreshold private
Minimum queue size in bytes before dequeue rate is measured.
Definition at line 144 of file pie-queue-disc.h.
Referenced by DoDequeue(), and GetTypeId().
m_dropProb
double ns3::PieQueueDisc::m_dropProb private
Variable used in calculation of drop probability.
Definition at line 153 of file pie-queue-disc.h.
Referenced by CalculateP(), DoEnqueue(), DropEarly(), and InitializeParams().
m_inMeasurement
bool ns3::PieQueueDisc::m_inMeasurement private
Indicates whether we are in a measurement cycle.
Definition at line 159 of file pie-queue-disc.h.
Referenced by DoDequeue(), DoEnqueue(), and InitializeParams().
m_isCapDropAdjustment
bool ns3::PieQueueDisc::m_isCapDropAdjustment private
Enable/Disable Cap Drop Adjustment feature mentioned in RFC 8033.
Definition at line 146 of file pie-queue-disc.h.
Referenced by CalculateP(), and GetTypeId().
m_markEcnTh
double ns3::PieQueueDisc::m_markEcnTh private
ECN marking threshold (default 10% as suggested in RFC 8033)
Definition at line 149 of file pie-queue-disc.h.
Referenced by DoEnqueue(), and GetTypeId().
m_maxBurst
Time ns3::PieQueueDisc::m_maxBurst private
Maximum burst allowed before random early dropping kicks in.
Definition at line 141 of file pie-queue-disc.h.
Referenced by DoEnqueue(), DropEarly(), and GetTypeId().
m_meanPktSize
uint32_t ns3::PieQueueDisc::m_meanPktSize private
Average packet size in bytes.
Definition at line 140 of file pie-queue-disc.h.
Referenced by DropEarly(), and GetTypeId().
m_qDelay
Time ns3::PieQueueDisc::m_qDelay private
Current value of queue delay.
Definition at line 155 of file pie-queue-disc.h.
Referenced by CalculateP(), DoDequeue(), DoEnqueue(), and GetQueueDelay().
m_qDelayOld
Time ns3::PieQueueDisc::m_qDelayOld private
Old value of queue delay.
Definition at line 154 of file pie-queue-disc.h.
Referenced by CalculateP(), DoEnqueue(), DropEarly(), and InitializeParams().
m_qDelayRef
Time ns3::PieQueueDisc::m_qDelayRef private
Desired queue delay.
Definition at line 139 of file pie-queue-disc.h.
Referenced by CalculateP(), DropEarly(), and GetTypeId().
m_rtrsEvent
EventId ns3::PieQueueDisc::m_rtrsEvent private
Event used to decide the decision of interval of drop probability calculation.
Definition at line 163 of file pie-queue-disc.h.
Referenced by PieQueueDisc(), CalculateP(), and DoDispose().
m_sUpdate
Time ns3::PieQueueDisc::m_sUpdate private
Start time of the update timer.
Definition at line 137 of file pie-queue-disc.h.
Referenced by PieQueueDisc(), and GetTypeId().
m_tUpdate
Time ns3::PieQueueDisc::m_tUpdate private
Time period after which CalculateP () is called.
Definition at line 138 of file pie-queue-disc.h.
Referenced by CalculateP(), and GetTypeId().
m_useDerandomization
bool ns3::PieQueueDisc::m_useDerandomization private
Enable Derandomization feature mentioned in RFC 8033.
Definition at line 148 of file pie-queue-disc.h.
Referenced by DropEarly(), and GetTypeId().
m_useDqRateEstimator
bool ns3::PieQueueDisc::m_useDqRateEstimator private
Enable/Disable usage of dequeue rate estimator for queue delay calculation.
Definition at line 145 of file pie-queue-disc.h.
Referenced by CalculateP(), DoDequeue(), and GetTypeId().
m_useEcn
bool ns3::PieQueueDisc::m_useEcn private
Enable ECN Marking functionality.
Definition at line 147 of file pie-queue-disc.h.
Referenced by DoEnqueue(), and GetTypeId().
m_uv
Ptr<UniformRandomVariable> ns3::PieQueueDisc::m_uv private
Rng stream.
Definition at line 164 of file pie-queue-disc.h.
Referenced by PieQueueDisc(), AssignStreams(), DoDispose(), and DropEarly().
UNFORCED_DROP
constexpr const char* ns3::PieQueueDisc::UNFORCED_DROP = "Unforced drop" static constexpr
Early probability drops: proactive.
Definition at line 98 of file pie-queue-disc.h.
Referenced by DoEnqueue().
UNFORCED_MARK
constexpr const char* ns3::PieQueueDisc::UNFORCED_MARK = "Unforced mark" static constexpr
Early probability marks: proactive.
Definition at line 100 of file pie-queue-disc.h.
Referenced by DoEnqueue().
The documentation for this class was generated from the following files:
src/traffic-control/model/pie-queue-disc.h
src/traffic-control/model/pie-queue-disc.cc