ns-3: ns3::SimulationSingleton< T > Class Template Reference
ns3::SimulationSingleton< T > Class Template Reference
Core
This singleton class template ensures that the type for which we want a singleton has a lifetime bounded by the simulation run lifetime.
#include "simulation-singleton.h"
Static Public Member Functions
static T * Get (void)
Get a pointer to the singleton instance.
Private Member Functions
Singleton pattern
Private constructor, copy and assignment operator.
Note these do not have to be implemented, since they are never called.
SimulationSingleton (void)
Default constructor.
SimulationSingleton (const SimulationSingleton< T > &)
Copy constructor.
SimulationSingleton< T > operator= (const SimulationSingleton< T > &)
Assignment.
Static Private Member Functions
static void DeleteObject (void)
Delete the static instance.
static T ** GetObject (void)
Get the singleton object, creating a new one if it doesn't exist yet.
Detailed Description
template<typename T>
class ns3::SimulationSingleton< T >
This singleton class template ensures that the type for which we want a singleton has a lifetime bounded by the simulation run lifetime.
That it, the underlying type will be automatically deleted upon a call to Simulator::Destroy.
For a singleton with a lifetime bounded by the process, not the simulation run, see Singleton.
Definition at line 43 of file simulation-singleton.h.
Constructor & Destructor Documentation
SimulationSingleton() [1/2]
template<typename T > ns3::SimulationSingleton< T >::SimulationSingleton (void) private
Default constructor.
SimulationSingleton() [2/2]
template<typename T > ns3::SimulationSingleton< T >::SimulationSingleton (const SimulationSingleton< T > &) private
Copy constructor.
Member Function Documentation
DeleteObject()
template<typename T > void ns3::SimulationSingleton< T >::DeleteObject (void) static private
Delete the static instance.
Definition at line 128 of file simulation-singleton.h.
Get()
template<typename T > T * ns3::SimulationSingleton< T >::Get (void) static
Get a pointer to the singleton instance.
This instance will be automatically deleted when the simulation is destroyed by a call to Simulator::Destroy.
Returns
A pointer to the singleton instance.
Definition at line 107 of file simulation-singleton.h.
Referenced by ns3::Ipv4AddressGenerator::AddAllocated(), ns3::Ipv6AddressGenerator::AddAllocated(), ns3::GlobalRouteManager::BuildGlobalRoutingDatabase(), ns3::GlobalRouteManager::DeleteGlobalRoutes(), ns3::Ipv4AddressGenerator::GetAddress(), ns3::Ipv6AddressGenerator::GetAddress(), ns3::Ipv4AddressGenerator::GetNetwork(), ns3::Ipv6AddressGenerator::GetNetwork(), ns3::Ipv4AddressGenerator::Init(), ns3::Ipv6AddressGenerator::Init(), ns3::Ipv4AddressGenerator::InitAddress(), ns3::Ipv6AddressGenerator::InitAddress(), ns3::GlobalRouteManager::InitializeRoutes(), ns3::Ipv4AddressGenerator::IsAddressAllocated(), ns3::Ipv6AddressGenerator::IsAddressAllocated(), ns3::Ipv4AddressGenerator::IsNetworkAllocated(), ns3::Ipv6AddressGenerator::IsNetworkAllocated(), ns3::Ipv4AddressGenerator::NextAddress(), ns3::Ipv6AddressGenerator::NextAddress(), ns3::Ipv4AddressGenerator::NextNetwork(), ns3::Ipv6AddressGenerator::NextNetwork(), ns3::Ipv4AddressGenerator::Reset(), ns3::Ipv6AddressGenerator::Reset(), ns3::Ipv4AddressGenerator::TestMode(), and ns3::Ipv6AddressGenerator::TestMode().
GetObject()
template<typename T > T ** ns3::SimulationSingleton< T >::GetObject (void) static private
Get the singleton object, creating a new one if it doesn't exist yet.
Internal:
When a new object is created, this method schedules it's own destruction using Simulator::ScheduleDestroy().
Returns
The address of the pointer holding the static instance.
Definition at line 115 of file simulation-singleton.h.
References ns3::Simulator::ScheduleDestroy().
operator=()
template<typename T > SimulationSingleton<T> ns3::SimulationSingleton< T >::operator= (const SimulationSingleton< T > &) private
Assignment.
Returns
The Singleton.
The documentation for this class was generated from the following file:
src/core/model/simulation-singleton.h