ns-3: ns3::TcpLedbat Class Reference
ns3::TcpLedbat Class Reference
Internet » TCP » Congestion Control Algorithms.
An implementation of LEDBAT.
#include "tcp-ledbat.h"
Classes
struct OwdCircBuf
Buffer structure to store delays.
Public Member Functions
TcpLedbat (const TcpLedbat &sock)
Copy constructor.
TcpLedbat (void)
Create an unbound tcp socket.
virtual ~TcpLedbat (void)
Destructor.
virtual Ptr< TcpCongestionOps > Fork ()
Copy the congestion control algorithm across sockets.
virtual std::string GetName () const
Get the name of the TCP flavour.
virtual void IncreaseWindow (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
Adjust cwnd following LEDBAT algorithm.
virtual void PktsAcked (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked, const Time &rtt)
Get information from the acked packet.
void SetDoSs (SlowStartType doSS)
Change the Slow Start Capability.
Public Member Functions inherited from ns3::TcpNewReno
TcpNewReno ()
TcpNewReno (const TcpNewReno &sock)
Copy constructor.
~TcpNewReno ()
virtual uint32_t GetSsThresh (Ptr< const TcpSocketState > tcb, uint32_t bytesInFlight)
Get the slow start threshold after a loss event.
Public Member Functions inherited from ns3::TcpCongestionOps
TcpCongestionOps ()
TcpCongestionOps (const TcpCongestionOps &other)
Copy constructor.
virtual ~TcpCongestionOps ()
virtual void CongControl (Ptr< TcpSocketState > tcb, const TcpRateOps::TcpRateConnection &rc, const TcpRateOps::TcpRateSample &rs)
Called when packets are delivered to update cwnd and pacing rate.
virtual void CongestionStateSet (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCongState_t newState)
Trigger events/calculations specific to a congestion state.
virtual void CwndEvent (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCAEvent_t event)
Trigger events/calculations on occurrence of congestion window event.
virtual bool HasCongControl () const
Returns true when Congestion Control Algorithm implements CongControl.
virtual void Init (Ptr< TcpSocketState > tcb)
Set configuration required by congestion control algorithm.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpNewReno
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpCongestionOps
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void CongestionAvoidance (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
Reduce Congestion.
Protected Member Functions inherited from ns3::TcpNewReno
virtual uint32_t SlowStart (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
Tcp NewReno slow start algorithm.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
typedef uint32_t(* FilterFunction) (struct OwdCircBuf &)
Filter function used by LEDBAT for current delay.
enum SlowStartType { DO_NOT_SLOWSTART , DO_SLOWSTART }
The slowstart types.
enum State : uint32_t { LEDBAT_VALID_OWD = (1 << 1) , LEDBAT_CAN_SS = (1 << 3) }
The state of LEDBAT.
Private Member Functions
void AddDelay (struct OwdCircBuf &cb, uint32_t owd, uint32_t maxlen)
Add new delay to the buffers.
uint32_t BaseDelay ()
Return the value of base delay.
uint32_t CurrentDelay (FilterFunction filter)
Return the value of current delay.
void InitCircBuf (struct OwdCircBuf &buffer)
Initialise a new buffer.
void UpdateBaseDelay (uint32_t owd)
Update the base delay buffer.
Static Private Member Functions
static uint32_t MinCircBuf (struct OwdCircBuf &b)
Return the minimum delay of the buffer.
Private Attributes
uint32_t m_baseHistoLen
Length of base delay history buffer.
OwdCircBuf m_baseHistory
Buffer to store the base delay.
SlowStartType m_doSs
Permissible Slow Start State.
uint32_t m_flag
LEDBAT Flag.
double m_gain
GAIN value from RFC.
uint64_t m_lastRollover
Timestamp of last added delay.
uint32_t m_minCwnd
Minimum cWnd value mentioned in RFC 6817.
OwdCircBuf m_noiseFilter
Buffer to store the current delay.
uint32_t m_noiseFilterLen
Length of current delay buffer.
int32_t m_sndCwndCnt
The congestion window addition parameter.
Time m_target
Target Queue Delay.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
An implementation of LEDBAT.
Config Paths
ns3::TcpLedbat is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::TcpL4Protocol/SocketList/[i]/CongestionOps/$ns3::TcpNewReno/$ns3::TcpLedbat"
"/NodeList/[i]/$ns3::TcpL4Protocol/SocketList/[i]/CongestionOps/$ns3::TcpLedbat"
Attributes
TargetDelay: Targeted Queue Delay
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+08ns
Flags: construct write read
BaseHistoryLen: Number of Base delay samples
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 10
Flags: construct write read
NoiseFilterLen: Number of Current delay samples
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 4
Flags: construct write read
Gain: Offset Gain
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 1
Flags: construct write read
SSParam: Possibility of Slow Start
Set with class: ns3::EnumValue
Underlying type:
Initial value: yes
Flags: construct write
MinCwnd: Minimum cWnd for Ledbat
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 2
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 152 bytes (on a 64-bit architecture).
Definition at line 39 of file tcp-ledbat.h.
Member Typedef Documentation
FilterFunction
typedef uint32_t(* ns3::TcpLedbat::FilterFunction) (struct OwdCircBuf &) private
Filter function used by LEDBAT for current delay.
Definition at line 146 of file tcp-ledbat.h.
Member Enumeration Documentation
SlowStartType
enum ns3::TcpLedbat::SlowStartType private
The slowstart types.
Enumerator
DO_NOT_SLOWSTART
Do not Slow Start.
DO_SLOWSTART
Do NewReno Slow Start.
Definition at line 45 of file tcp-ledbat.h.
State
enum ns3::TcpLedbat::State : uint32_t private
The state of LEDBAT.
If LEDBAT is not in VALID_OWD state, it falls to default congestion ops.
Enumerator
LEDBAT_VALID_OWD
If valid timestamps are present.
LEDBAT_CAN_SS
If LEDBAT allows Slow Start.
Definition at line 55 of file tcp-ledbat.h.
Constructor & Destructor Documentation
TcpLedbat() [1/2]
ns3::TcpLedbat::TcpLedbat (void)
Create an unbound tcp socket.
Definition at line 89 of file tcp-ledbat.cc.
References DO_SLOWSTART, InitCircBuf(), LEDBAT_CAN_SS, m_baseHistoLen, m_baseHistory, m_doSs, m_flag, m_gain, m_lastRollover, m_minCwnd, m_noiseFilter, m_noiseFilterLen, m_sndCwndCnt, m_target, ns3::MilliSeconds(), and NS_LOG_FUNCTION.
TcpLedbat() [2/2]
ns3::TcpLedbat::TcpLedbat (const TcpLedbat & sock)
Copy constructor.
Parameters
sock the object to copy
Definition at line 113 of file tcp-ledbat.cc.
References m_baseHistoLen, m_baseHistory, m_doSs, m_flag, m_gain, m_lastRollover, m_minCwnd, m_noiseFilter, m_noiseFilterLen, m_sndCwndCnt, m_target, and NS_LOG_FUNCTION.
~TcpLedbat()
ns3::TcpLedbat::~TcpLedbat (void) virtual
Destructor.
Definition at line 130 of file tcp-ledbat.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddDelay()
void ns3::TcpLedbat::AddDelay (struct OwdCircBuf & cb, uint32_t owd, uint32_t maxlen) private
Add new delay to the buffers.
Parameters
cb The buffer
owd The new delay
maxlen The maximum permitted length
Definition at line 231 of file tcp-ledbat.cc.
References ns3::TcpLedbat::OwdCircBuf::buffer, ns3::TcpLedbat::OwdCircBuf::min, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by PktsAcked(), and UpdateBaseDelay().
BaseDelay()
uint32_t ns3::TcpLedbat::BaseDelay () private
Return the value of base delay.
Returns
The base delay
Definition at line 166 of file tcp-ledbat.cc.
References m_baseHistory, MinCircBuf(), and NS_LOG_FUNCTION.
Referenced by CongestionAvoidance().
CongestionAvoidance()
void ns3::TcpLedbat::CongestionAvoidance (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked) protected virtual
Reduce Congestion.
Parameters
tcb internal congestion state
segmentsAcked count of segments ACKed
Reimplemented from ns3::TcpNewReno.
Definition at line 190 of file tcp-ledbat.cc.
References BaseDelay(), ns3::TcpNewReno::CongestionAvoidance(), CurrentDelay(), ns3::TracedValue< T >::Get(), ns3::Time::GetMilliSeconds(), LEDBAT_VALID_OWD, ns3::TcpSocketState::m_cWnd, m_flag, m_gain, ns3::TcpSocketState::m_highTxMark, ns3::TcpSocketState::m_lastAckedSeq, m_minCwnd, ns3::TcpSocketState::m_segmentSize, m_sndCwndCnt, ns3::TcpSocketState::m_ssThresh, m_target, max, min, MinCircBuf(), and NS_LOG_FUNCTION.
Referenced by IncreaseWindow().
CurrentDelay()
uint32_t ns3::TcpLedbat::CurrentDelay (FilterFunction filter) private
Return the value of current delay.
Parameters
filter The filter function
Returns
The current delay
Definition at line 160 of file tcp-ledbat.cc.
References m_noiseFilter, and NS_LOG_FUNCTION.
Referenced by CongestionAvoidance().
Fork()
Ptr< TcpCongestionOps > ns3::TcpLedbat::Fork () virtual
Copy the congestion control algorithm across sockets.
Returns
a pointer of the copied object
Reimplemented from ns3::TcpNewReno.
Definition at line 136 of file tcp-ledbat.cc.
GetName()
std::string ns3::TcpLedbat::GetName (void) const virtual
Get the name of the TCP flavour.
Returns
The name of the TCP
Reimplemented from ns3::TcpNewReno.
Definition at line 142 of file tcp-ledbat.cc.
GetTypeId()
TypeId ns3::TcpLedbat::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 34 of file tcp-ledbat.cc.
References DO_NOT_SLOWSTART, DO_SLOWSTART, m_baseHistoLen, m_gain, m_minCwnd, m_noiseFilterLen, m_target, ns3::MakeDoubleAccessor(), ns3::MakeEnumAccessor(), ns3::MakeEnumChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeUintegerAccessor(), ns3::MilliSeconds(), SetDoSs(), and ns3::TypeId::SetParent().
IncreaseWindow()
void ns3::TcpLedbat::IncreaseWindow (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked) virtual
Adjust cwnd following LEDBAT algorithm.
Parameters
tcb internal congestion state
segmentsAcked count of segments ACKed
Reimplemented from ns3::TcpNewReno.
Definition at line 172 of file tcp-ledbat.cc.
References CongestionAvoidance(), DO_SLOWSTART, ns3::TracedValue< T >::Get(), LEDBAT_CAN_SS, ns3::TcpSocketState::m_cWnd, m_doSs, m_flag, ns3::TcpSocketState::m_segmentSize, ns3::TcpSocketState::m_ssThresh, NS_LOG_FUNCTION, and ns3::TcpNewReno::SlowStart().
InitCircBuf()
void ns3::TcpLedbat::InitCircBuf (struct OwdCircBuf & buffer) private
Initialise a new buffer.
Parameters
buffer The buffer to be initialised
Definition at line 106 of file tcp-ledbat.cc.
References ns3::TcpLedbat::OwdCircBuf::buffer, ns3::TcpLedbat::OwdCircBuf::min, and NS_LOG_FUNCTION.
Referenced by TcpLedbat().
MinCircBuf()
uint32_t ns3::TcpLedbat::MinCircBuf (struct OwdCircBuf & b) static private
Return the minimum delay of the buffer.
Parameters
b The buffer
Returns
The minimum delay
Definition at line 147 of file tcp-ledbat.cc.
References ns3::TcpLedbat::OwdCircBuf::buffer, ns3::TcpLedbat::OwdCircBuf::min, and NS_LOG_FUNCTION_NOARGS.
Referenced by BaseDelay(), and CongestionAvoidance().
PktsAcked()
void ns3::TcpLedbat::PktsAcked (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked, const Time & rtt) virtual
Get information from the acked packet.
Parameters
tcb internal congestion state
segmentsAcked count of segments ACKed
rtt The estimated rtt
Reimplemented from ns3::TcpCongestionOps.
Definition at line 291 of file tcp-ledbat.cc.
References AddDelay(), ns3::Time::IsPositive(), LEDBAT_VALID_OWD, m_flag, m_noiseFilter, m_noiseFilterLen, ns3::TcpSocketState::m_rcvTimestampEchoReply, ns3::TcpSocketState::m_rcvTimestampValue, NS_LOG_FUNCTION, and UpdateBaseDelay().
SetDoSs()
void ns3::TcpLedbat::SetDoSs (SlowStartType doSS)
Change the Slow Start Capability.
Parameters
doSS Slow Start Option
Definition at line 75 of file tcp-ledbat.cc.
References LEDBAT_CAN_SS, m_doSs, m_flag, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
UpdateBaseDelay()
void ns3::TcpLedbat::UpdateBaseDelay (uint32_t owd) private
Update the base delay buffer.
Parameters
owd The delay
Definition at line 262 of file tcp-ledbat.cc.
References AddDelay(), ns3::TcpLedbat::OwdCircBuf::buffer, ns3::Time::GetSeconds(), m_baseHistoLen, m_baseHistory, m_lastRollover, ns3::TcpLedbat::OwdCircBuf::min, ns3::Simulator::Now(), and NS_LOG_FUNCTION.
Referenced by PktsAcked().
Member Data Documentation
m_baseHistoLen
uint32_t ns3::TcpLedbat::m_baseHistoLen private
Length of base delay history buffer.
Definition at line 190 of file tcp-ledbat.h.
Referenced by TcpLedbat(), GetTypeId(), and UpdateBaseDelay().
m_baseHistory
OwdCircBuf ns3::TcpLedbat::m_baseHistory private
Buffer to store the base delay.
Definition at line 194 of file tcp-ledbat.h.
Referenced by TcpLedbat(), BaseDelay(), and UpdateBaseDelay().
m_doSs
SlowStartType ns3::TcpLedbat::m_doSs private
Permissible Slow Start State.
Definition at line 189 of file tcp-ledbat.h.
Referenced by TcpLedbat(), IncreaseWindow(), and SetDoSs().
m_flag
uint32_t ns3::TcpLedbat::m_flag private
LEDBAT Flag.
Definition at line 196 of file tcp-ledbat.h.
Referenced by TcpLedbat(), CongestionAvoidance(), IncreaseWindow(), PktsAcked(), and SetDoSs().
m_gain
double ns3::TcpLedbat::m_gain private
GAIN value from RFC.
Definition at line 188 of file tcp-ledbat.h.
Referenced by TcpLedbat(), CongestionAvoidance(), and GetTypeId().
m_lastRollover
uint64_t ns3::TcpLedbat::m_lastRollover private
Timestamp of last added delay.
Definition at line 192 of file tcp-ledbat.h.
Referenced by TcpLedbat(), and UpdateBaseDelay().
m_minCwnd
uint32_t ns3::TcpLedbat::m_minCwnd private
Minimum cWnd value mentioned in RFC 6817.
Definition at line 197 of file tcp-ledbat.h.
Referenced by TcpLedbat(), CongestionAvoidance(), and GetTypeId().
m_noiseFilter
OwdCircBuf ns3::TcpLedbat::m_noiseFilter private
Buffer to store the current delay.
Definition at line 195 of file tcp-ledbat.h.
Referenced by TcpLedbat(), CurrentDelay(), and PktsAcked().
m_noiseFilterLen
uint32_t ns3::TcpLedbat::m_noiseFilterLen private
Length of current delay buffer.
Definition at line 191 of file tcp-ledbat.h.
Referenced by TcpLedbat(), GetTypeId(), and PktsAcked().
m_sndCwndCnt
int32_t ns3::TcpLedbat::m_sndCwndCnt private
The congestion window addition parameter.
Definition at line 193 of file tcp-ledbat.h.
Referenced by TcpLedbat(), and CongestionAvoidance().
m_target
Time ns3::TcpLedbat::m_target private
Target Queue Delay.
Definition at line 187 of file tcp-ledbat.h.
Referenced by TcpLedbat(), CongestionAvoidance(), and GetTypeId().
The documentation for this class was generated from the following files:
src/internet/model/tcp-ledbat.h
src/internet/model/tcp-ledbat.cc