ns-3: ns3::UanMac Class Reference
ns3::UanMac Class Reference abstract
UAN Models
Virtual base class for all UAN MAC protocols.
#include "uan-mac.h"
Public Types
typedef void(* PacketModeTracedCallback) (Ptr< const Packet > packet, UanTxMode mode)
TracedCallback signature for packet reception/enqueue/dequeue events.
Public Member Functions
UanMac ()
Default constructor.
virtual int64_t AssignStreams (int64_t stream)=0
Assign a fixed random variable stream number to the random variables used by this model.
virtual void AttachPhy (Ptr< UanPhy > phy)=0
Attach PHY layer to this MAC.
virtual void Clear (void)=0
Clears all pointer references.
virtual bool Enqueue (Ptr< Packet > pkt, uint16_t protocolNumber, const Address &dest)=0
Enqueue packet to be transmitted.
virtual Address GetAddress (void)
Get the MAC Address.
virtual Address GetBroadcast (void) const
Get the broadcast address.
uint32_t GetTxModeIndex ()
virtual void SetAddress (Mac8Address addr)
Set the address.
virtual void SetForwardUpCb (Callback< void, Ptr< Packet >, uint16_t, const Mac8Address & > cb)=0
Set the callback to forward packets up to higher layers.
void SetTxModeIndex (uint32_t txModeIndex)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Mac8Address m_address
The MAC address.
uint32_t m_txModeIndex
Modulation type.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Virtual base class for all UAN MAC protocols.
Config Paths
ns3::UanMac is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::UanNetDevice/Mac"
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 48 bytes (on a 64-bit architecture).
Definition at line 49 of file uan-mac.h.
Member Typedef Documentation
PacketModeTracedCallback
typedef void(* ns3::UanMac::PacketModeTracedCallback) (Ptr< const Packet > packet, UanTxMode mode)
TracedCallback signature for packet reception/enqueue/dequeue events.
Parameters
[in] packet The Packet.
[in] mode The UanTxMode.
Definition at line 128 of file uan-mac.h.
Constructor & Destructor Documentation
UanMac()
ns3::UanMac::UanMac ()
Default constructor.
Definition at line 27 of file uan-mac.cc.
Member Function Documentation
AssignStreams()
virtual int64_t ns3::UanMac::AssignStreams (int64_t stream) pure virtual
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream First stream index to use.
Returns
The number of stream indices assigned by this model.
Implemented in ns3::UanMacRc, ns3::UanMacRcGw, ns3::UanMacCw, and ns3::UanMacAloha.
AttachPhy()
virtual void ns3::UanMac::AttachPhy (Ptr< UanPhy > phy) pure virtual
Attach PHY layer to this MAC.
Some MACs may be designed to work with multiple PHY layers. Others may only work with one.
Parameters
phy Phy layer to attach to this MAC.
Implemented in ns3::UanMacRc, ns3::UanMacRcGw, ns3::UanMacCw, and ns3::UanMacAloha.
Clear()
virtual void ns3::UanMac::Clear (void) pure virtual
Clears all pointer references.
Implemented in ns3::UanMacRc, ns3::UanMacRcGw, ns3::UanMacCw, and ns3::UanMacAloha.
Enqueue()
virtual bool ns3::UanMac::Enqueue (Ptr< Packet > pkt, uint16_t protocolNumber, const Address & dest) pure virtual
Enqueue packet to be transmitted.
Parameters
pkt Packet to be transmitted.
dest Destination address.
protocolNumber The type of the packet.
Returns
True if packet was successfully enqueued.
Implemented in ns3::UanMacRc, ns3::UanMacRcGw, ns3::UanMacCw, and ns3::UanMacAloha.
GetAddress()
Address ns3::UanMac::GetAddress (void) virtual
Get the MAC Address.
Returns
MAC Address.
Definition at line 55 of file uan-mac.cc.
References m_address.
Referenced by ns3::UanMacRc::Associate(), ns3::UanMacRc::AssociateTimeout(), ns3::UanMacRcGw::EndCycle(), ns3::UanMacCw::EndTx(), ns3::UanMacAloha::Enqueue(), ns3::UanMacCw::Enqueue(), ns3::UanMacRc::IsPhy1Ok(), ns3::UanMacCw::NotifyCcaEnd(), ns3::UanMacCw::NotifyCcaStart(), ns3::UanMacCw::NotifyRxEndError(), ns3::UanMacCw::NotifyRxEndOk(), ns3::UanMacCw::NotifyRxStart(), ns3::UanMacCw::PhyRxPacketGood(), ns3::UanMacRc::ProcessAck(), ns3::UanMacRc::ReceiveOkFromPhy(), ns3::UanMacRcGw::ReceivePacket(), ns3::UanMacRc::RtsTimeout(), ns3::UanMacAloha::RxPacketError(), ns3::UanMacAloha::RxPacketGood(), ns3::UanMacCw::SaveTimer(), ns3::UanMacRc::ScheduleData(), ns3::UanMacRc::SendPacket(), ns3::UanMacCw::SendPacket(), ns3::UanMacRc::SendRts(), ns3::UanMacRcGw::StartCycle(), and ns3::UanMacCw::StartTimer().
GetBroadcast()
Address ns3::UanMac::GetBroadcast (void) const virtual
Get the broadcast address.
Returns
The broadcast address.
Definition at line 67 of file uan-mac.cc.
GetTxModeIndex()
uint32_t ns3::UanMac::GetTxModeIndex ()
Definition at line 49 of file uan-mac.cc.
References m_txModeIndex.
Referenced by ns3::UanMacAloha::Enqueue(), and ns3::UanMacCw::Enqueue().
GetTypeId()
TypeId ns3::UanMac::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 33 of file uan-mac.cc.
References ns3::TypeId::SetParent().
SetAddress()
void ns3::UanMac::SetAddress (Mac8Address addr) virtual
Set the address.
Parameters
addr Mac8Address for this MAC.
Definition at line 61 of file uan-mac.cc.
References m_address.
SetForwardUpCb()
virtual void ns3::UanMac::SetForwardUpCb (Callback< void, Ptr< Packet >, uint16_t, const Mac8Address & > cb) pure virtual
Set the callback to forward packets up to higher layers.
Parameters
cb The callback. packet The packet. address The source address.
Implemented in ns3::UanMacRc, ns3::UanMacRcGw, ns3::UanMacCw, and ns3::UanMacAloha.
SetTxModeIndex()
void ns3::UanMac::SetTxModeIndex (uint32_t txModeIndex)
Definition at line 43 of file uan-mac.cc.
References m_txModeIndex.
Member Data Documentation
m_address
Mac8Address ns3::UanMac::m_address private
The MAC address.
Definition at line 138 of file uan-mac.h.
Referenced by GetAddress(), and SetAddress().
m_txModeIndex
uint32_t ns3::UanMac::m_txModeIndex private
Modulation type.
Definition at line 136 of file uan-mac.h.
Referenced by GetTxModeIndex(), and SetTxModeIndex().
The documentation for this class was generated from the following files:
src/uan/model/uan-mac.h
src/uan/model/uan-mac.cc