ns-3: PieQueueDiscTestCase Class Reference
PieQueueDiscTestCase Class Reference
Traffic-control » traffic-control module tests | Test suites
Pie Queue Disc Test Case.
Public Member Functions
PieQueueDiscTestCase ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CheckAccuProb (Ptr< PieQueueDisc > queue, Ptr< PieQueueDiscTestItem > testAttributes)
Check Accumulated Drop Probability.
void CheckDropProb (Ptr< PieQueueDisc > queue, Ptr< PieQueueDiscTestItem > testAttributes)
Check Drop Probability.
void CheckMaxAccuProb (Ptr< PieQueueDisc > queue, Ptr< PieQueueDiscTestItem > testAttributes)
Check Maximum Accumulated Drop Probability.
void Dequeue (Ptr< PieQueueDisc > queue, uint32_t nPkt)
Dequeue function.
void DequeueWithDelay (Ptr< PieQueueDisc > queue, double delay, uint32_t nPkt)
Dequeue with delay function.
void Enqueue (Ptr< PieQueueDisc > queue, uint32_t size, uint32_t nPkt, Ptr< PieQueueDiscTestItem > testAttributes)
Enqueue function.
void EnqueueWithDelay (Ptr< PieQueueDisc > queue, uint32_t size, uint32_t nPkt, Ptr< PieQueueDiscTestItem > testAttributes)
Enqueue with delay function.
void RunPieTest (QueueSizeUnit mode)
Run test function.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Pie Queue Disc Test Case.
Definition at line 120 of file pie-queue-disc-test-suite.cc.
Constructor & Destructor Documentation
PieQueueDiscTestCase()
PieQueueDiscTestCase::PieQueueDiscTestCase ()
Definition at line 180 of file pie-queue-disc-test-suite.cc.
Member Function Documentation
CheckAccuProb()
void PieQueueDiscTestCase::CheckAccuProb (Ptr< PieQueueDisc > queue, Ptr< PieQueueDiscTestItem > testAttributes) private
Check Accumulated Drop Probability.
Parameters
queue the queue disc
testAttributes attributes for testing
Definition at line 654 of file pie-queue-disc-test-suite.cc.
Referenced by Enqueue().
CheckDropProb()
void PieQueueDiscTestCase::CheckDropProb (Ptr< PieQueueDisc > queue, Ptr< PieQueueDiscTestItem > testAttributes) private
Check Drop Probability.
Parameters
queue the queue disc
testAttributes attributes for testing
Definition at line 635 of file pie-queue-disc-test-suite.cc.
Referenced by Enqueue().
CheckMaxAccuProb()
void PieQueueDiscTestCase::CheckMaxAccuProb (Ptr< PieQueueDisc > queue, Ptr< PieQueueDiscTestItem > testAttributes) private
Check Maximum Accumulated Drop Probability.
Parameters
queue the queue disc
testAttributes attributes for testing
Definition at line 667 of file pie-queue-disc-test-suite.cc.
References ns3::BYTES, ns3::QueueSize::GetUnit(), ns3::QueueSize::GetValue(), and ns3::PACKETS.
Referenced by Enqueue().
Dequeue()
void PieQueueDiscTestCase::Dequeue (Ptr< PieQueueDisc > queue, uint32_t nPkt) private
Dequeue function.
Parameters
queue the queue disc
nPkt the number of packets
Definition at line 689 of file pie-queue-disc-test-suite.cc.
Referenced by DequeueWithDelay().
DequeueWithDelay()
void PieQueueDiscTestCase::DequeueWithDelay (Ptr< PieQueueDisc > queue, double delay, uint32_t nPkt) private
Dequeue with delay function.
Parameters
queue the queue disc
delay the delay
nPkt the number of packets
Definition at line 698 of file pie-queue-disc-test-suite.cc.
References Dequeue(), and ns3::Seconds().
Referenced by RunPieTest().
DoRun()
void PieQueueDiscTestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 707 of file pie-queue-disc-test-suite.cc.
References ns3::BYTES, ns3::PACKETS, and RunPieTest().
Enqueue()
void PieQueueDiscTestCase::Enqueue (Ptr< PieQueueDisc > queue, uint32_t size, uint32_t nPkt, Ptr< PieQueueDiscTestItem > testAttributes) private
Enqueue function.
Parameters
queue the queue disc
size the size
nPkt the number of packets
testAttributes attributes for testing
Definition at line 609 of file pie-queue-disc-test-suite.cc.
References CheckAccuProb(), CheckDropProb(), and CheckMaxAccuProb().
Referenced by EnqueueWithDelay().
EnqueueWithDelay()
void PieQueueDiscTestCase::EnqueueWithDelay (Ptr< PieQueueDisc > queue, uint32_t size, uint32_t nPkt, Ptr< PieQueueDiscTestItem > testAttributes) private
Enqueue with delay function.
Parameters
queue the queue disc
size the size
nPkt the number of packets
testAttributes attributes for testing
Definition at line 678 of file pie-queue-disc-test-suite.cc.
References Enqueue(), and ns3::Seconds().
Referenced by RunPieTest().
RunPieTest()
void PieQueueDiscTestCase::RunPieTest (QueueSizeUnit mode) private
Run test function.
Parameters
mode the test mode
Definition at line 186 of file pie-queue-disc-test-suite.cc.
References ns3::BYTES, DequeueWithDelay(), EnqueueWithDelay(), ns3::QueueDisc::Stats::GetNDroppedPackets(), ns3::QueueDisc::Stats::GetNMarkedPackets(), ns3::Packet::GetUid(), NS_TEST_EXPECT_MSG_EQ, NS_TEST_EXPECT_MSG_GT, NS_TEST_EXPECT_MSG_LT, NS_TEST_EXPECT_MSG_NE, pktSize, and ns3::Seconds().
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/traffic-control/test/pie-queue-disc-test-suite.cc