ns-3: ns3::Tlv Class Reference
ns3::Tlv Class Reference
WiMAX Models
This class implements the Type-Len-Value structure channel encodings as described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems".
#include "wimax-tlv.h"
Public Types
enum CommonTypes {
HMAC_TUPLE = 149 , MAC_VERSION_ENCODING = 148 , CURRENT_TRANSMIT_POWER = 147 , DOWNLINK_SERVICE_FLOW = 146 ,
UPLINK_SERVICE_FLOW = 145 , VENDOR_ID_EMCODING = 144 , VENDOR_SPECIFIC_INFORMATION = 143
}
CommonTypes enumeration.
Public Member Functions
Tlv (const Tlv &tlv)
type conversion operator
Tlv (uint8_t type, uint64_t length, const TlvValue &value)
Constructor.
Tlv (void)
~Tlv (void)
Tlv * Copy (void) const
Copy TLV.
TlvValue * CopyValue (void) const
Copy TlvValue.
virtual uint32_t Deserialize (Buffer::Iterator start)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint64_t GetLength (void) const
Get length value.
virtual uint32_t GetSerializedSize (void) const
uint8_t GetSizeOfLen (void) const
Get size of length field.
uint8_t GetType (void) const
Get type value.
Tlv & operator= (Tlv const &o)
assignment operator
TlvValue * PeekValue (void)
Peek value.
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint64_t m_length
length
uint8_t m_type
type
TlvValue * m_value
value
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class implements the Type-Len-Value structure channel encodings as described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems".
TLV encodings, page 645
Definition at line 83 of file wimax-tlv.h.
Member Enumeration Documentation
CommonTypes
enum ns3::Tlv::CommonTypes
CommonTypes enumeration.
Enumerator
HMAC_TUPLE
MAC_VERSION_ENCODING
CURRENT_TRANSMIT_POWER
DOWNLINK_SERVICE_FLOW
UPLINK_SERVICE_FLOW
VENDOR_ID_EMCODING
VENDOR_SPECIFIC_INFORMATION
Definition at line 87 of file wimax-tlv.h.
Constructor & Destructor Documentation
Tlv() [1/3]
ns3::Tlv::Tlv (uint8_t type, uint64_t length, const TlvValue & value)
Constructor.
Parameters
type type
length the length
value TLV value
Definition at line 52 of file wimax-tlv.cc.
References ns3::TlvValue::Copy(), m_length, m_type, and m_value.
Tlv() [2/3]
ns3::Tlv::Tlv (void)
Definition at line 59 of file wimax-tlv.cc.
References m_length, m_type, and m_value.
Referenced by Copy().
~Tlv()
ns3::Tlv::~Tlv (void)
Definition at line 66 of file wimax-tlv.cc.
References m_value.
Tlv() [3/3]
ns3::Tlv::Tlv (const Tlv & tlv)
type conversion operator
Parameters
tlv the TLV
Definition at line 81 of file wimax-tlv.cc.
References CopyValue(), GetLength(), GetType(), m_length, m_type, and m_value.
Member Function Documentation
Copy()
Tlv * ns3::Tlv::Copy (void) const
Copy TLV.
Returns
a pointer to a TLV copy
Definition at line 230 of file wimax-tlv.cc.
References Tlv(), m_length, m_type, and m_value.
Referenced by ns3::VectorTlvValue::Add().
CopyValue()
TlvValue * ns3::Tlv::CopyValue (void) const
Copy TlvValue.
Returns
the TLV value
Definition at line 76 of file wimax-tlv.cc.
References ns3::TlvValue::Copy(), and m_value.
Referenced by Tlv(), and operator=().
Deserialize()
uint32_t ns3::Tlv::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Todo:
implement Deserialize HMAC_TUPLE
Todo:
implement Deserialize MAC_VERSION_ENCODING
Todo:
implement Deserialize CURRENT_TRANSMIT_POWER
Todo:
implement Deserialize VENDOR_ID_EMCODING
Todo:
implement Deserialize VENDOR_SPECIFIC_INFORMATION
Implements ns3::Header.
Definition at line 147 of file wimax-tlv.cc.
References ns3::SfVectorTlvValue::Copy(), CURRENT_TRANSMIT_POWER, ns3::SfVectorTlvValue::Deserialize(), DOWNLINK_SERVICE_FLOW, HMAC_TUPLE, m_length, m_type, m_value, MAC_VERSION_ENCODING, NS_ASSERT_MSG, NS_FATAL_ERROR, ns3::Buffer::Iterator::ReadU8(), UPLINK_SERVICE_FLOW, VENDOR_ID_EMCODING, VENDOR_SPECIFIC_INFORMATION, and WIMAX_TLV_EXTENDED_LENGTH_MASK.
Referenced by ns3::DsaReq::Deserialize(), and ns3::DsaRsp::Deserialize().
GetInstanceTypeId()
TypeId ns3::Tlv::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 42 of file wimax-tlv.cc.
References GetTypeId().
GetLength()
uint64_t ns3::Tlv::GetLength (void) const
Get length value.
Returns
the length
Definition at line 219 of file wimax-tlv.cc.
References m_length.
Referenced by Tlv(), and operator=().
GetSerializedSize()
uint32_t ns3::Tlv::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 103 of file wimax-tlv.cc.
References ns3::TlvValue::GetSerializedSize(), GetSizeOfLen(), and m_value.
Referenced by ns3::DsaReq::GetSerializedSize(), and ns3::DsaRsp::GetSerializedSize().
GetSizeOfLen()
uint8_t ns3::Tlv::GetSizeOfLen (void) const
Get size of length field.
Returns
the size of length field
Definition at line 109 of file wimax-tlv.cc.
References m_length.
Referenced by GetSerializedSize(), and Serialize().
GetType()
uint8_t ns3::Tlv::GetType (void) const
Get type value.
Returns
the type
Definition at line 214 of file wimax-tlv.cc.
References m_type.
Referenced by ns3::CsParameters::CsParameters(), ns3::IpcsClassifierRecord::IpcsClassifierRecord(), ns3::ServiceFlow::ServiceFlow(), Tlv(), Ns3WimaxCsParamTlvTestCase::DoRun(), and operator=().
GetTypeId()
TypeId ns3::Tlv::GetTypeId (void) static
Register this type.
Returns
the TypeId.
Definition at line 32 of file wimax-tlv.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
operator=()
Tlv & ns3::Tlv::operator= (Tlv const & o)
assignment operator
Parameters
o the TLV to assign
Returns
the TLV
Definition at line 89 of file wimax-tlv.cc.
References CopyValue(), GetLength(), GetType(), m_length, m_type, and m_value.
PeekValue()
TlvValue * ns3::Tlv::PeekValue (void)
Peek value.
Returns
the TLV value
Definition at line 224 of file wimax-tlv.cc.
References m_value.
Referenced by ns3::CsParameters::CsParameters(), ns3::IpcsClassifierRecord::IpcsClassifierRecord(), ns3::ServiceFlow::ServiceFlow(), and Ns3WimaxCsParamTlvTestCase::DoRun().
Print()
void ns3::Tlv::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 47 of file wimax-tlv.cc.
References m_length, and m_type.
Serialize()
void ns3::Tlv::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 127 of file wimax-tlv.cc.
References GetSizeOfLen(), m_length, m_type, m_value, ns3::TlvValue::Serialize(), WIMAX_TLV_EXTENDED_LENGTH_MASK, and ns3::Buffer::Iterator::WriteU8().
Referenced by ns3::DsaReq::Serialize(), and ns3::DsaRsp::Serialize().
Member Data Documentation
m_length
uint64_t ns3::Tlv::m_length private
length
Definition at line 161 of file wimax-tlv.h.
Referenced by Tlv(), Copy(), Deserialize(), GetLength(), GetSizeOfLen(), operator=(), Print(), and Serialize().
m_type
uint8_t ns3::Tlv::m_type private
type
Definition at line 160 of file wimax-tlv.h.
Referenced by Tlv(), Copy(), Deserialize(), GetType(), operator=(), Print(), and Serialize().
m_value
TlvValue* ns3::Tlv::m_value private
value
Definition at line 162 of file wimax-tlv.h.
Referenced by Tlv(), ~Tlv(), Copy(), CopyValue(), Deserialize(), GetSerializedSize(), operator=(), PeekValue(), and Serialize().
The documentation for this class was generated from the following files:
src/wimax/model/wimax-tlv.h
src/wimax/model/wimax-tlv.cc