ns-3: ns3::UdpClientHelper Class Reference
ns3::UdpClientHelper Class Reference
Applications » UdpClientServer
Create a client application which sends UDP packets carrying a 32bit sequence number and a 64 bit time stamp.
#include "udp-client-server-helper.h"
Public Member Functions
UdpClientHelper ()
Create UdpClientHelper which will make life easier for people trying to set up simulations with udp-client-server.
UdpClientHelper (Address addr)
Create UdpClientHelper which will make life easier for people trying to set up simulations with udp-client-server.
UdpClientHelper (Address ip, uint16_t port)
Create UdpClientHelper which will make life easier for people trying to set up simulations with udp-client-server.
ApplicationContainer Install (NodeContainer c)
void SetAttribute (std::string name, const AttributeValue &value)
Record an attribute to be set in each Application after it is is created.
Private Attributes
ObjectFactory m_factory
Object factory.
Detailed Description
Create a client application which sends UDP packets carrying a 32bit sequence number and a 64 bit time stamp.
Definition at line 93 of file udp-client-server-helper.h.
Constructor & Destructor Documentation
UdpClientHelper() [1/3]
ns3::UdpClientHelper::UdpClientHelper ()
Create UdpClientHelper which will make life easier for people trying to set up simulations with udp-client-server.
Definition at line 68 of file udp-client-server-helper.cc.
References ns3::UdpClient::GetTypeId(), m_factory, and ns3::ObjectFactory::SetTypeId().
UdpClientHelper() [2/3]
ns3::UdpClientHelper::UdpClientHelper (Address ip, uint16_t port)
Create UdpClientHelper which will make life easier for people trying to set up simulations with udp-client-server.
Use this variant with addresses that do not include a port value (e.g., Ipv4Address and Ipv6Address).
Parameters
ip The IP address of the remote UDP server
port The port number of the remote UDP server
Definition at line 73 of file udp-client-server-helper.cc.
References first::address, ns3::UdpClient::GetTypeId(), m_factory, port, SetAttribute(), and ns3::ObjectFactory::SetTypeId().
UdpClientHelper() [3/3]
ns3::UdpClientHelper::UdpClientHelper (Address addr)
Create UdpClientHelper which will make life easier for people trying to set up simulations with udp-client-server.
Use this variant with addresses that do include a port value (e.g., InetSocketAddress and Inet6SocketAddress).
Parameters
addr The address of the remote UDP server
Definition at line 80 of file udp-client-server-helper.cc.
References first::address, ns3::UdpClient::GetTypeId(), m_factory, SetAttribute(), and ns3::ObjectFactory::SetTypeId().
Member Function Documentation
Install()
ApplicationContainer ns3::UdpClientHelper::Install (NodeContainer c)
Parameters
c the nodes
Create one UDP client application on each of the input nodes
Returns
the applications created, one application per input node.
Definition at line 93 of file udp-client-server-helper.cc.
References ns3::ApplicationContainer::Add(), ns3::Node::AddApplication(), ns3::NodeContainer::Begin(), ns3::ObjectFactory::Create(), ns3::NodeContainer::End(), and m_factory.
Referenced by LteRadioLinkFailureTestCase::DoRun(), UdpClientServerTestCase::DoRun(), LenaCqaFfMacSchedulerTestCase1::DoRun(), LenaCqaFfMacSchedulerTestCase2::DoRun(), ns3::LenaDeactivateBearerTestCase::DoRun(), LenaFdTbfqFfMacSchedulerTestCase1::DoRun(), LenaFdTbfqFfMacSchedulerTestCase2::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LenaPssFfMacSchedulerTestCase1::DoRun(), LenaPssFfMacSchedulerTestCase2::DoRun(), LenaTdTbfqFfMacSchedulerTestCase1::DoRun(), LenaTdTbfqFfMacSchedulerTestCase2::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), LteX2HandoverTestCase::DoRun(), Issue211Test::DoRun(), and Experiment::Run().
SetAttribute()
void ns3::UdpClientHelper::SetAttribute (std::string name, const AttributeValue & value)
Record an attribute to be set in each Application after it is is created.
Parameters
name the name of the attribute to set
value the value of the attribute to set
Definition at line 87 of file udp-client-server-helper.cc.
References m_factory, and ns3::ObjectFactory::Set().
Referenced by UdpClientHelper(), LteRadioLinkFailureTestCase::DoRun(), UdpClientServerTestCase::DoRun(), LenaCqaFfMacSchedulerTestCase1::DoRun(), LenaCqaFfMacSchedulerTestCase2::DoRun(), ns3::LenaDeactivateBearerTestCase::DoRun(), LenaFdTbfqFfMacSchedulerTestCase1::DoRun(), LenaFdTbfqFfMacSchedulerTestCase2::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LenaPssFfMacSchedulerTestCase1::DoRun(), LenaPssFfMacSchedulerTestCase2::DoRun(), LenaTdTbfqFfMacSchedulerTestCase1::DoRun(), LenaTdTbfqFfMacSchedulerTestCase2::DoRun(), Issue211Test::DoRun(), and Experiment::Run().
Member Data Documentation
m_factory
ObjectFactory ns3::UdpClientHelper::m_factory private
Object factory.
Definition at line 144 of file udp-client-server-helper.h.
Referenced by UdpClientHelper(), Install(), and SetAttribute().
The documentation for this class was generated from the following files:
src/applications/helper/udp-client-server-helper.h
src/applications/helper/udp-client-server-helper.cc