ns-3: ns3::dot11s::HwmpProtocol Class Reference
ns3::dot11s::HwmpProtocol Class Reference
Mesh Device » IEEE 802.11s draft
Hybrid wireless mesh protocol – a mesh routing protocol defined in IEEE 802.11-2012 standard.
#include "hwmp-protocol.h"
Classes
struct FailedDestination
structure of unreachable destination - address and sequence number
struct PathError
Structure of path error: IePerr and list of receivers: interfaces and MAC address.
struct PreqEvent
PreqEvent structure.
struct QueuedPacket
Packet waiting its routing information.
struct Statistics
Statistics structure.
Public Types
typedef struct FailedDestination FailedDestination
Public Types inherited from ns3::MeshL2RoutingProtocol
typedef Callback< void, bool, Ptr< Packet >, Mac48Address, Mac48Address, uint16_t, uint32_t > RouteReplyCallback
Callback to be invoked when route discovery procedure is completed.
Public Member Functions
HwmpProtocol ()
~HwmpProtocol ()
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
void DoDispose ()
Destructor implementation.
Ptr< HwmpRtable > GetRoutingTable (void) const
Get pointer to HWMP routing table.
bool Install (Ptr< MeshPointDevice >)
Install HWMP on given mesh point.
void PeerLinkStatus (Mac48Address meshPontAddress, Mac48Address peerAddress, uint32_t interface, bool status)
Peer link status function.
bool RemoveRoutingStuff (uint32_t fromIface, const Mac48Address source, const Mac48Address destination, Ptr< Packet > packet, uint16_t &protocolType)
Clean HWMP packet tag from packet; only the packet parameter is used.
void Report (std::ostream &) const
Statistics:
bool RequestRoute (uint32_t sourceIface, const Mac48Address source, const Mac48Address destination, Ptr< const Packet > packet, uint16_t protocolType, RouteReplyCallback routeReply)
Route request, inherited from MeshL2RoutingProtocol.
void ResetStats ()
Reset Statistics:
void SetNeighboursCallback (Callback< std::vector< Mac48Address >, uint32_t > cb)
This callback is used to obtain active neighbours on a given interface.
Proactive PREQ mechanism:
void SetRoot ()
void UnsetRoot ()
Public Member Functions inherited from ns3::MeshL2RoutingProtocol
virtual ~MeshL2RoutingProtocol ()
virtual D-tor for subclasses
Ptr< MeshPointDevice > GetMeshPoint () const
Each mesh protocol must be installed on the mesh point to work.
void SetMeshPoint (Ptr< MeshPointDevice > mp)
Set host mesh point, analog of SetNode (...) methods for upper layer protocols.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::MeshL2RoutingProtocol
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef std::map< uint32_t, Ptr< HwmpProtocolMac > > HwmpProtocolMacMap
HwmpProtocolMacMap typedef.
Private Member Functions
HwmpProtocol (const HwmpProtocol &)
type conversion
virtual void DoInitialize ()
Initialize() implementation.
bool ForwardUnicast (uint32_t sourceIface, const Mac48Address source, const Mac48Address destination, Ptr< Packet > packet, uint16_t protocolType, RouteReplyCallback routeReply, uint32_t ttl)
Like RequestRoute, but for unicast packets.
Mac48Address GetAddress ()
HwmpProtocol & operator= (const HwmpProtocol &hwmp)
assignment operator
Methods related to Queue/Dequeue procedures
bool QueuePacket (QueuedPacket packet)
QueuedPacket DequeueFirstPacketByDst (Mac48Address dst)
QueuedPacket DequeueFirstPacket ()
void ReactivePathResolved (Mac48Address dst)
void ProactivePathResolved ()
Methods responsible for path discovery retry procedure:
bool ShouldSendPreq (Mac48Address dst)
checks when the last path discovery procedure was started for a given destination.
void RetryPathDiscovery (Mac48Address dst, uint8_t numOfRetry)
Generates PREQ retry when retry timeout has expired and route is still unresolved.
void SendProactivePreq ()
Proactive Preq routines:
Private Attributes
Ptr< UniformRandomVariable > m_coefficient
Random variable for random start time.
Callback< std::vector< Mac48Address >, uint32_t > m_neighboursCallback
neighbors callback
std::map< Mac48Address, PreqEvent > m_preqTimeouts
PREQ timeouts.
EventId m_proactivePreqTimer
proactive PREQ timer
Time m_randomStart
Random start in Proactive PREQ propagation.
std::vector< QueuedPacket > m_rqueue
Packet Queue.
Ptr< HwmpRtable > m_rtable
Routing table.
Sequence number filters
Data sequence number database
std::map< Mac48Address, uint32_t > m_lastDataSeqno
keeps HWMP seqno (first in pair) and HWMP metric (second in pair) for each address
std::map< Mac48Address, std::pair< uint32_t, uint32_t > > m_hwmpSeqnoMetricDatabase
keeps HWMP seqno (first in pair) and HWMP metric (second in pair) for each address
HWMP-protocol parameters
These are all Attributes
uint16_t m_maxQueueSize
uint8_t m_dot11MeshHWMPmaxPREQretries
Time m_dot11MeshHWMPnetDiameterTraversalTime
Time m_dot11MeshHWMPpreqMinInterval
Time m_dot11MeshHWMPperrMinInterval
Time m_dot11MeshHWMPactiveRootTimeout
Time m_dot11MeshHWMPactivePathTimeout
Time m_dot11MeshHWMPpathToRootInterval
Time m_dot11MeshHWMPrannInterval
bool m_isRoot
uint8_t m_maxTtl
uint8_t m_unicastPerrThreshold
uint8_t m_unicastPreqThreshold
uint8_t m_unicastDataThreshold
bool m_doFlag
bool m_rfFlag
Friends
class HwmpProtocolMac
allow HwmpProtocolMac class friend access
Interaction with HWMP MAC plugin
typedef TracedCallback< struct RouteChange > RouteChangeTracedCallback
RouteChangeTracedCallback typedef.
TracedCallback< Time > m_routeDiscoveryTimeCallback
Route discovery time:
TracedCallback< struct RouteChange > m_routeChangeTraceSource
Route change trace source.
void ReceivePreq (IePreq preq, Mac48Address from, uint32_t interface, Mac48Address fromMp, uint32_t metric)
Handler for receiving Path Request.
void ReceivePrep (IePrep prep, Mac48Address from, uint32_t interface, Mac48Address fromMp, uint32_t metric)
Handler for receiving Path Reply.
void ReceivePerr (std::vector< FailedDestination > destinations, Mac48Address from, uint32_t interface, Mac48Address fromMp)
Handler for receiving Path Error.
void SendPrep (Mac48Address src, Mac48Address dst, Mac48Address retransmitter, uint32_t initMetric, uint32_t originatorDsn, uint32_t destinationSN, uint32_t lifetime, uint32_t interface)
Send Path Reply.
PathError MakePathError (std::vector< FailedDestination > destinations)
forms a path error information element when list of destination fails on a given interface
void ForwardPathError (PathError perr)
Forwards a received path error.
void InitiatePathError (PathError perr)
Passes a self-generated PERR to interface-plugin.
std::vector< std::pair< uint32_t, Mac48Address > > GetPerrReceivers (std::vector< FailedDestination > failedDest)
Get PERR receivers.
std::vector< Mac48Address > GetPreqReceivers (uint32_t interface)
Get PREQ receivers.
std::vector< Mac48Address > GetBroadcastReceivers (uint32_t interface)
Get broadcast receivers.
bool DropDataFrame (uint32_t seqno, Mac48Address source)
MAC-plugin asks whether the frame can be dropped.
Methods needed by HwmpMacLugin to access protocol parameters:
Statistics m_stats
statistics
HwmpProtocolMacMap m_interfaces
interfaces
Mac48Address m_address
address
uint32_t m_dataSeqno
data sequence no
uint32_t m_hwmpSeqno
HWMP sequence no.
uint32_t m_preqId
PREQ ID.
bool GetDoFlag ()
Get do flag function.
bool GetRfFlag ()
Get rf flag function.
Time GetPreqMinInterval ()
Get PREQ minimum interval function.
Time GetPerrMinInterval ()
Get PERR minimum interval function.
uint8_t GetMaxTtl ()
Get maximum TTL function.
uint32_t GetNextPreqId ()
Get next period function.
uint32_t GetNextHwmpSeqno ()
Get next HWMP sequence no function.
uint32_t GetActivePathLifetime ()
Get active path lifetime function.
uint8_t GetUnicastPerrThreshold ()
Get unicast PERR threshold function.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::MeshL2RoutingProtocol
Ptr< MeshPointDevice > m_mp
Host mesh point.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Hybrid wireless mesh protocol – a mesh routing protocol defined in IEEE 802.11-2012 standard.
Config Paths
ns3::dot11s::HwmpProtocol is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::MeshPointDevice/RoutingProtocol/$ns3::dot11s::HwmpProtocol"
Attributes
RandomStart: Random delay at first proactive PREQ
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+08ns
Flags: construct write read
MaxQueueSize: Maximum number of packets we can store when resolving route
Set with class: ns3::UintegerValue
Underlying type: uint16_t 1:65535
Initial value: 255
Flags: construct write read
Dot11MeshHWMPmaxPREQretries: Maximum number of retries before we suppose the destination to be unreachable
Set with class: ns3::UintegerValue
Underlying type: uint8_t 1:255
Initial value: 3
Flags: construct write read
Dot11MeshHWMPnetDiameterTraversalTime: Time we suppose the packet to go from one edge of the network to another
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1.024e+08ns
Flags: construct write read
Dot11MeshHWMPpreqMinInterval: Minimal interval between to successive PREQs
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1.024e+08ns
Flags: construct write read
Dot11MeshHWMPperrMinInterval: Minimal interval between to successive PREQs
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1.024e+08ns
Flags: construct write read
Dot11MeshHWMPactiveRootTimeout: Lifetime of poractive routing information
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +5.12e+09ns
Flags: construct write read
Dot11MeshHWMPactivePathTimeout: Lifetime of reactive routing information
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +5.12e+09ns
Flags: construct write read
Dot11MeshHWMPpathToRootInterval: Interval between two successive proactive PREQs
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +2.048e+09ns
Flags: construct write read
Dot11MeshHWMPrannInterval: Lifetime of poractive routing information
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +5.12e+09ns
Flags: construct write read
MaxTtl: Initial value of Time To Live field
Set with class: ns3::UintegerValue
Underlying type: uint8_t 2:255
Initial value: 32
Flags: construct write read
UnicastPerrThreshold: Maximum number of PERR receivers, when we send a PERR as a chain of unicasts
Set with class: ns3::UintegerValue
Underlying type: uint8_t 1:255
Initial value: 32
Flags: construct write read
UnicastPreqThreshold: Maximum number of PREQ receivers, when we send a PREQ as a chain of unicasts
Set with class: ns3::UintegerValue
Underlying type: uint8_t 1:255
Initial value: 1
Flags: construct write read
UnicastDataThreshold: Maximum number ofbroadcast receivers, when we send a broadcast as a chain of unicasts
Set with class: ns3::UintegerValue
Underlying type: uint8_t 1:255
Initial value: 1
Flags: construct write read
DoFlag: Destination only HWMP flag
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
RfFlag: Reply and forward flag
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
TraceSources
RouteDiscoveryTime: The time of route discovery procedure
Callback signature: ns3::Time::TracedCallback
RouteChange: Routing table changed
Callback signature: ns3::HwmpProtocol::RouteChangeTracedCallback
Size of this type is 384 bytes (on a 64-bit architecture).
Definition at line 62 of file hwmp-protocol.h.
Member Typedef Documentation
FailedDestination
typedef struct FailedDestination ns3::dot11s::HwmpProtocol::FailedDestination
Definition at line 72 of file hwmp-protocol.h.
HwmpProtocolMacMap
typedef std::map<uint32_t, Ptr<HwmpProtocolMac> > ns3::dot11s::HwmpProtocol::HwmpProtocolMacMap private
HwmpProtocolMacMap typedef.
Definition at line 195 of file hwmp-protocol.h.
RouteChangeTracedCallback
typedef TracedCallback<struct RouteChange> ns3::dot11s::HwmpProtocol::RouteChangeTracedCallback private
RouteChangeTracedCallback typedef.
Definition at line 314 of file hwmp-protocol.h.
Constructor & Destructor Documentation
HwmpProtocol() [1/2]
ns3::dot11s::HwmpProtocol::HwmpProtocol ()
Definition at line 179 of file hwmp-protocol.cc.
References m_coefficient, and NS_LOG_FUNCTION.
~HwmpProtocol()
ns3::dot11s::HwmpProtocol::~HwmpProtocol ()
Definition at line 206 of file hwmp-protocol.cc.
References NS_LOG_FUNCTION.
HwmpProtocol() [2/2]
ns3::dot11s::HwmpProtocol::HwmpProtocol (const HwmpProtocol &) private
type conversion
Returns
the HWMP protocol
Member Function Documentation
AssignStreams()
int64_t ns3::dot11s::HwmpProtocol::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 1279 of file hwmp-protocol.cc.
References m_coefficient, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
DequeueFirstPacket()
HwmpProtocol::QueuedPacket ns3::dot11s::HwmpProtocol::DequeueFirstPacket () private
Definition at line 1001 of file hwmp-protocol.cc.
References m_rqueue, NS_LOG_FUNCTION, and ns3::dot11s::HwmpProtocol::QueuedPacket::pkt.
Referenced by ProactivePathResolved().
DequeueFirstPacketByDst()
HwmpProtocol::QueuedPacket ns3::dot11s::HwmpProtocol::DequeueFirstPacketByDst (Mac48Address dst) private
Definition at line 983 of file hwmp-protocol.cc.
References m_rqueue, NS_LOG_FUNCTION, and ns3::dot11s::HwmpProtocol::QueuedPacket::pkt.
Referenced by ReactivePathResolved(), and RetryPathDiscovery().
DoDispose()
void ns3::dot11s::HwmpProtocol::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 224 of file hwmp-protocol.cc.
References ns3::EventId::Cancel(), m_hwmpSeqnoMetricDatabase, m_interfaces, m_lastDataSeqno, ns3::MeshL2RoutingProtocol::m_mp, m_preqTimeouts, m_proactivePreqTimer, m_rqueue, m_rtable, and NS_LOG_FUNCTION.
DoInitialize()
void ns3::dot11s::HwmpProtocol::DoInitialize (void) private virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 212 of file hwmp-protocol.cc.
References ns3::Time::GetSeconds(), ns3::UniformRandomVariable::GetValue(), m_coefficient, m_isRoot, m_proactivePreqTimer, m_randomStart, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), ns3::Seconds(), SendProactivePreq(), and ns3::ObjectBase::SetAttribute().
DropDataFrame()
bool ns3::dot11s::HwmpProtocol::DropDataFrame (uint32_t seqno, Mac48Address source) private
MAC-plugin asks whether the frame can be dropped.
Protocol automatically updates seqno.
Returns
true if frame can be dropped
Parameters
seqno is the sequence number of source
source is the source address
Definition at line 815 of file hwmp-protocol.cc.
References GetAddress(), m_lastDataSeqno, and NS_LOG_FUNCTION.
ForwardPathError()
void ns3::dot11s::HwmpProtocol::ForwardPathError (PathError perr) private
Forwards a received path error.
Parameters
perr the path error
Definition at line 880 of file hwmp-protocol.cc.
References ns3::dot11s::HwmpProtocol::PathError::destinations, m_interfaces, NS_LOG_FUNCTION, and ns3::dot11s::HwmpProtocol::PathError::receivers.
Referenced by ReceivePerr().
ForwardUnicast()
bool ns3::dot11s::HwmpProtocol::ForwardUnicast (uint32_t sourceIface, const Mac48Address source, const Mac48Address destination, Ptr< Packet > packet, uint16_t protocolType, RouteReplyCallback routeReply, uint32_t ttl) private
Like RequestRoute, but for unicast packets.
Parameters
sourceIface the source interface
source the source address
destination the destination address
packet the packet to route
protocolType the protocol type
routeReply the route reply callback
ttl the TTL
Returns
true if forwarded
Definition at line 335 of file hwmp-protocol.cc.
References ns3::Packet::AddPacketTag(), ns3::dot11s::HwmpProtocol::QueuedPacket::dst, GetAddress(), ns3::Mac48Address::GetBroadcast(), ns3::MeshL2RoutingProtocol::GetMeshPoint(), GetNextHwmpSeqno(), ns3::Packet::GetSize(), ns3::dot11s::HwmpRtable::GetUnreachableDestinations(), ns3::dot11s::HwmpRtable::LookupResult::ifIndex, ns3::dot11s::HwmpProtocol::QueuedPacket::inInterface, ns3::dot11s::HwmpProtocol::Statistics::initiatedPreq, InitiatePathError(), ns3::dot11s::HwmpRtable::LookupProactive(), ns3::dot11s::HwmpRtable::LookupProactiveExpired(), ns3::dot11s::HwmpRtable::LookupReactive(), ns3::dot11s::HwmpRtable::LookupReactiveExpired(), m_interfaces, m_rtable, m_stats, MakePathError(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::dot11s::HwmpProtocol::QueuedPacket::pkt, ns3::dot11s::HwmpProtocol::QueuedPacket::protocol, QueuePacket(), ns3::dot11s::HwmpProtocol::QueuedPacket::reply, ns3::dot11s::HwmpRtable::LookupResult::retransmitter, ns3::dot11s::HwmpRtable::LookupResult::seqnum, ns3::dot11s::HwmpTag::SetAddress(), ns3::dot11s::HwmpTag::SetTtl(), ShouldSendPreq(), ns3::dot11s::HwmpProtocol::QueuedPacket::src, ns3::dot11s::HwmpProtocol::Statistics::totalDropped, ns3::dot11s::HwmpProtocol::Statistics::totalQueued, ns3::dot11s::HwmpProtocol::Statistics::txBytes, and ns3::dot11s::HwmpProtocol::Statistics::txUnicast.
Referenced by RequestRoute().
GetActivePathLifetime()
uint32_t ns3::dot11s::HwmpProtocol::GetActivePathLifetime () private
Get active path lifetime function.
Returns
the active path lifetime
Definition at line 1199 of file hwmp-protocol.cc.
References ns3::Time::GetMicroSeconds(), and m_dot11MeshHWMPactivePathTimeout.
GetAddress()
Mac48Address ns3::dot11s::HwmpProtocol::GetAddress (void) private
Returns
address of MeshPointDevice
Definition at line 1209 of file hwmp-protocol.cc.
References m_address.
Referenced by DropDataFrame(), ForwardUnicast(), ReceivePerr(), ReceivePrep(), ReceivePreq(), and SendProactivePreq().
GetBroadcastReceivers()
std::vector< Mac48Address > ns3::dot11s::HwmpProtocol::GetBroadcastReceivers (uint32_t interface) private
Get broadcast receivers.
Parameters
interface
Returns
list of addresses where a broadcast should be retransmitted
Definition at line 954 of file hwmp-protocol.cc.
References ns3::Mac48Address::GetBroadcast(), m_neighboursCallback, m_unicastDataThreshold, and NS_LOG_FUNCTION.
Referenced by RequestRoute().
GetDoFlag()
bool ns3::dot11s::HwmpProtocol::GetDoFlag () private
Get do flag function.
Returns
DO flag
Definition at line 1162 of file hwmp-protocol.cc.
References m_doFlag.
GetMaxTtl()
uint8_t ns3::dot11s::HwmpProtocol::GetMaxTtl () private
Get maximum TTL function.
Returns
the maximum TTL
Definition at line 1182 of file hwmp-protocol.cc.
References m_maxTtl.
GetNextHwmpSeqno()
uint32_t ns3::dot11s::HwmpProtocol::GetNextHwmpSeqno () private
Get next HWMP sequence no function.
Returns
the next HWMP sequence number
Definition at line 1193 of file hwmp-protocol.cc.
References m_hwmpSeqno.
Referenced by ForwardUnicast(), ReceivePreq(), RetryPathDiscovery(), and SendProactivePreq().
GetNextPreqId()
uint32_t ns3::dot11s::HwmpProtocol::GetNextPreqId () private
Get next period function.
Returns
the next period
Definition at line 1187 of file hwmp-protocol.cc.
References m_preqId.
Referenced by SendProactivePreq().
GetPerrMinInterval()
Time ns3::dot11s::HwmpProtocol::GetPerrMinInterval () private
Get PERR minimum interval function.
Returns
the PERR minimum interval
Definition at line 1177 of file hwmp-protocol.cc.
References m_dot11MeshHWMPperrMinInterval.
GetPerrReceivers()
std::vector< std::pair< uint32_t, Mac48Address > > ns3::dot11s::HwmpProtocol::GetPerrReceivers (std::vector< FailedDestination > failedDest) private
Get PERR receivers.
Parameters
failedDest
Returns
list of addresses where a PERR should be sent to
Definition at line 898 of file hwmp-protocol.cc.
References ns3::dot11s::HwmpRtable::DeleteProactivePath(), ns3::dot11s::HwmpRtable::DeleteReactivePath(), ns3::dot11s::RouteChange::destination, ns3::dot11s::HwmpRtable::GetPrecursors(), m_routeChangeTraceSource, m_rtable, NS_LOG_FUNCTION, ns3::dot11s::RouteChange::seqnum, and ns3::dot11s::RouteChange::type.
Referenced by MakePathError().
GetPreqMinInterval()
Time ns3::dot11s::HwmpProtocol::GetPreqMinInterval () private
Get PREQ minimum interval function.
Returns
the PREQ
Definition at line 1172 of file hwmp-protocol.cc.
References m_dot11MeshHWMPpreqMinInterval.
GetPreqReceivers()
std::vector< Mac48Address > ns3::dot11s::HwmpProtocol::GetPreqReceivers (uint32_t interface) private
Get PREQ receivers.
Parameters
interface
Returns
list of addresses where a PREQ should be sent to
Definition at line 938 of file hwmp-protocol.cc.
References ns3::Mac48Address::GetBroadcast(), m_neighboursCallback, m_unicastPreqThreshold, and NS_LOG_FUNCTION.
GetRfFlag()
bool ns3::dot11s::HwmpProtocol::GetRfFlag () private
Get rf flag function.
Returns
the RF flag
Definition at line 1167 of file hwmp-protocol.cc.
References m_rfFlag.
GetRoutingTable()
Ptr< HwmpRtable > ns3::dot11s::HwmpProtocol::GetRoutingTable (void) const
Get pointer to HWMP routing table.
Returns
pointer to routing table
Definition at line 1287 of file hwmp-protocol.cc.
References m_rtable.
GetTypeId()
TypeId ns3::dot11s::HwmpProtocol::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 47 of file hwmp-protocol.cc.
References m_doFlag, m_dot11MeshHWMPactivePathTimeout, m_dot11MeshHWMPactiveRootTimeout, m_dot11MeshHWMPmaxPREQretries, m_dot11MeshHWMPnetDiameterTraversalTime, m_dot11MeshHWMPpathToRootInterval, m_dot11MeshHWMPperrMinInterval, m_dot11MeshHWMPpreqMinInterval, m_dot11MeshHWMPrannInterval, m_maxQueueSize, m_maxTtl, m_randomStart, m_rfFlag, m_routeChangeTraceSource, m_routeDiscoveryTimeCallback, m_unicastDataThreshold, m_unicastPerrThreshold, m_unicastPreqThreshold, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), ns3::MicroSeconds(), ns3::Seconds(), and ns3::TypeId::SetParent().
GetUnicastPerrThreshold()
uint8_t ns3::dot11s::HwmpProtocol::GetUnicastPerrThreshold () private
Get unicast PERR threshold function.
Returns
the unicast PERR threshold
Definition at line 1204 of file hwmp-protocol.cc.
References m_unicastPerrThreshold.
InitiatePathError()
void ns3::dot11s::HwmpProtocol::InitiatePathError (PathError perr) private
Passes a self-generated PERR to interface-plugin.
Parameters
perr the path error
Definition at line 863 of file hwmp-protocol.cc.
References ns3::dot11s::HwmpProtocol::PathError::destinations, m_interfaces, NS_LOG_FUNCTION, and ns3::dot11s::HwmpProtocol::PathError::receivers.
Referenced by ForwardUnicast(), and PeerLinkStatus().
Install()
bool ns3::dot11s::HwmpProtocol::Install (Ptr< MeshPointDevice > mp)
Install HWMP on given mesh point.
Returns
true if successful
Installing protocol causes installation of its interface MAC plugins.
Also MP aggregates all installed protocols, HWMP protocol can be accessed via MeshPointDevice::GetObject<dot11s::HwmpProtocol>();
Definition at line 765 of file hwmp-protocol.cc.
References ns3::dot11s::AirtimeLinkMetricCalculator::CalculateMetric(), ns3::Mac48Address::ConvertFrom(), ns3::WifiNetDevice::GetIfIndex(), ns3::WifiNetDevice::GetMac(), ns3::Object::GetObject(), first::interfaces, m_address, m_interfaces, ns3::MeshL2RoutingProtocol::m_mp, third::mac, ns3::MakeCallback(), and NS_LOG_FUNCTION.
MakePathError()
HwmpProtocol::PathError ns3::dot11s::HwmpProtocol::MakePathError (std::vector< FailedDestination > destinations) private
forms a path error information element when list of destination fails on a given interface
Attention
removes all entries from routing table!
Parameters
destinations vector of failed destinations
Returns
PathError
Definition at line 838 of file hwmp-protocol.cc.
References ns3::dot11s::HwmpRtable::DeleteReactivePath(), ns3::dot11s::RouteChange::destination, ns3::dot11s::HwmpProtocol::PathError::destinations, GetPerrReceivers(), ns3::dot11s::HwmpProtocol::Statistics::initiatedPerr, m_routeChangeTraceSource, m_rtable, m_stats, NS_LOG_FUNCTION, ns3::dot11s::HwmpProtocol::PathError::receivers, ns3::dot11s::RouteChange::seqnum, and ns3::dot11s::RouteChange::type.
Referenced by ForwardUnicast(), PeerLinkStatus(), and ReceivePerr().
operator=()
HwmpProtocol& ns3::dot11s::HwmpProtocol::operator= (const HwmpProtocol & hwmp) private
assignment operator
Parameters
hwmp the HWMP protocol to assign
Returns
the assigned value
PeerLinkStatus()
void ns3::dot11s::HwmpProtocol::PeerLinkStatus (Mac48Address meshPontAddress, Mac48Address peerAddress, uint32_t interface, bool status)
Peer link status function.
Parameters
meshPontAddress The MAC address of the mesh point
peerAddress The MAC address of the peer
interface The interface number
status The status of the peer link
Definition at line 798 of file hwmp-protocol.cc.
References ns3::dot11s::HwmpRtable::GetUnreachableDestinations(), InitiatePathError(), m_rtable, MakePathError(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by ns3::Dot11sStack::InstallStack().
ProactivePathResolved()
void ns3::dot11s::HwmpProtocol::ProactivePathResolved () private
Definition at line 1043 of file hwmp-protocol.cc.
References ns3::Packet::AddPacketTag(), DequeueFirstPacket(), ns3::dot11s::HwmpProtocol::QueuedPacket::dst, ns3::Mac48Address::GetBroadcast(), ns3::Packet::GetSize(), ns3::dot11s::HwmpRtable::LookupResult::ifIndex, ns3::dot11s::HwmpRtable::LookupProactive(), m_rtable, m_stats, NS_ASSERT, NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::dot11s::HwmpProtocol::QueuedPacket::pkt, ns3::dot11s::HwmpProtocol::QueuedPacket::protocol, ns3::Packet::RemovePacketTag(), ns3::dot11s::HwmpProtocol::QueuedPacket::reply, ns3::dot11s::HwmpRtable::LookupResult::retransmitter, ns3::dot11s::HwmpTag::SetAddress(), ns3::dot11s::HwmpProtocol::QueuedPacket::src, ns3::dot11s::HwmpProtocol::Statistics::txBytes, and ns3::dot11s::HwmpProtocol::Statistics::txUnicast.
Referenced by ReceivePreq().
QueuePacket()
bool ns3::dot11s::HwmpProtocol::QueuePacket (QueuedPacket packet) private
Definition at line 971 of file hwmp-protocol.cc.
References m_maxQueueSize, m_rqueue, and NS_LOG_FUNCTION.
Referenced by ForwardUnicast().
ReactivePathResolved()
void ns3::dot11s::HwmpProtocol::ReactivePathResolved (Mac48Address dst) private
Definition at line 1015 of file hwmp-protocol.cc.
References ns3::Packet::AddPacketTag(), DequeueFirstPacketByDst(), ns3::dot11s::HwmpProtocol::QueuedPacket::dst, ns3::Mac48Address::GetBroadcast(), ns3::Packet::GetSize(), ns3::dot11s::HwmpRtable::LookupResult::ifIndex, ns3::dot11s::HwmpRtable::LookupReactive(), m_preqTimeouts, m_routeDiscoveryTimeCallback, m_rtable, m_stats, ns3::Simulator::Now(), NS_ASSERT, NS_LOG_FUNCTION, ns3::dot11s::HwmpProtocol::QueuedPacket::pkt, ns3::dot11s::HwmpProtocol::QueuedPacket::protocol, ns3::Packet::RemovePacketTag(), ns3::dot11s::HwmpProtocol::QueuedPacket::reply, ns3::dot11s::HwmpRtable::LookupResult::retransmitter, ns3::dot11s::HwmpTag::SetAddress(), ns3::dot11s::HwmpProtocol::QueuedPacket::src, ns3::dot11s::HwmpProtocol::Statistics::txBytes, and ns3::dot11s::HwmpProtocol::Statistics::txUnicast.
Referenced by ReceivePrep(), and ReceivePreq().
ReceivePerr()
void ns3::dot11s::HwmpProtocol::ReceivePerr (std::vector< FailedDestination > destinations, Mac48Address from, uint32_t interface, Mac48Address fromMp) private
Handler for receiving Path Error.
Parameters
destinations the list of failed destinations
from the from address
interface the interface
fromMp the from MP address
Definition at line 714 of file hwmp-protocol.cc.
References ForwardPathError(), GetAddress(), ns3::dot11s::HwmpRtable::LookupResult::ifIndex, ns3::dot11s::HwmpRtable::LookupReactiveExpired(), m_rtable, MakePathError(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::dot11s::HwmpRtable::LookupResult::retransmitter, and ns3::dot11s::HwmpRtable::LookupResult::seqnum.
ReceivePrep()
void ns3::dot11s::HwmpProtocol::ReceivePrep (IePrep prep, Mac48Address from, uint32_t interface, Mac48Address fromMp, uint32_t metric) private
Handler for receiving Path Reply.
Parameters
prep the IE prep
from the from address
interface the interface
fromMp the 'from MP' address
metric the metric
Definition at line 614 of file hwmp-protocol.cc.
References ns3::dot11s::HwmpRtable::AddPrecursor(), ns3::dot11s::HwmpRtable::AddReactivePath(), ns3::dot11s::RouteChange::destination, GetAddress(), ns3::Mac48Address::GetBroadcast(), ns3::dot11s::IePrep::GetDestinationAddress(), ns3::dot11s::IePrep::GetDestinationSeqNumber(), ns3::dot11s::IePrep::GetLifetime(), ns3::dot11s::IePrep::GetMetric(), ns3::dot11s::IePrep::GetOriginatorAddress(), ns3::dot11s::HwmpRtable::LookupResult::ifIndex, ns3::dot11s::IePrep::IncrementMetric(), ns3::dot11s::RouteChange::interface, ns3::dot11s::RouteChange::lifetime, ns3::dot11s::HwmpRtable::LookupResult::lifetime, ns3::dot11s::HwmpRtable::LookupReactive(), m_hwmpSeqnoMetricDatabase, m_interfaces, m_routeChangeTraceSource, m_rtable, ns3::dot11s::RouteChange::metric, ns3::MicroSeconds(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, ReactivePathResolved(), ns3::dot11s::RouteChange::retransmitter, ns3::dot11s::HwmpRtable::LookupResult::retransmitter, ns3::dot11s::RouteChange::seqnum, and ns3::dot11s::RouteChange::type.
ReceivePreq()
void ns3::dot11s::HwmpProtocol::ReceivePreq (IePreq preq, Mac48Address from, uint32_t interface, Mac48Address fromMp, uint32_t metric) private
Handler for receiving Path Request.
Parameters
preq the IE preq
from the from address
interface the interface
fromMp the 'from MP' address
metric the metric
Definition at line 420 of file hwmp-protocol.cc.
References ns3::dot11s::HwmpRtable::AddPrecursor(), ns3::dot11s::HwmpRtable::AddProactivePath(), ns3::dot11s::HwmpRtable::AddReactivePath(), ns3::dot11s::IePreq::DelDestinationAddressElement(), ns3::dot11s::RouteChange::destination, GetAddress(), ns3::Mac48Address::GetBroadcast(), ns3::dot11s::IePreq::GetDestCount(), ns3::dot11s::IePreq::GetDestinationList(), ns3::dot11s::IePreq::GetLifetime(), ns3::dot11s::IePreq::GetMetric(), ns3::Time::GetMicroSeconds(), GetNextHwmpSeqno(), ns3::dot11s::IePreq::GetOriginatorAddress(), ns3::dot11s::IePreq::GetOriginatorSeqNumber(), ns3::dot11s::IePreq::IncrementMetric(), ns3::dot11s::RouteChange::interface, ns3::dot11s::IePreq::IsNeedNotPrep(), ns3::dot11s::RouteChange::lifetime, ns3::dot11s::HwmpRtable::LookupResult::lifetime, ns3::dot11s::HwmpRtable::LookupProactive(), ns3::dot11s::HwmpRtable::LookupReactive(), m_hwmpSeqnoMetricDatabase, m_interfaces, m_routeChangeTraceSource, m_rtable, ns3::dot11s::RouteChange::metric, ns3::dot11s::HwmpRtable::LookupResult::metric, ns3::MicroSeconds(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, ProactivePathResolved(), ReactivePathResolved(), ns3::dot11s::RouteChange::retransmitter, ns3::dot11s::HwmpRtable::LookupResult::retransmitter, SendPrep(), ns3::dot11s::RouteChange::seqnum, ns3::dot11s::HwmpRtable::LookupResult::seqnum, and ns3::dot11s::RouteChange::type.
RemoveRoutingStuff()
bool ns3::dot11s::HwmpProtocol::RemoveRoutingStuff (uint32_t fromIface, const Mac48Address source, const Mac48Address destination, Ptr< Packet > packet, uint16_t & protocolType) virtual
Clean HWMP packet tag from packet; only the packet parameter is used.
Parameters
fromIface the from interface
source the source address
destination the destination address
packet the packet to route
protocolType the protocol type
Returns
true if successful
Implements ns3::MeshL2RoutingProtocol.
Definition at line 324 of file hwmp-protocol.cc.
References NS_FATAL_ERROR, and ns3::Packet::RemovePacketTag().
Report()
void ns3::dot11s::HwmpProtocol::Report (std::ostream & os) const
Statistics:
Definition at line 1240 of file hwmp-protocol.cc.
References ns3::Time::GetSeconds(), m_address, m_doFlag, m_dot11MeshHWMPactivePathTimeout, m_dot11MeshHWMPactiveRootTimeout, m_dot11MeshHWMPmaxPREQretries, m_dot11MeshHWMPnetDiameterTraversalTime, m_dot11MeshHWMPpathToRootInterval, m_dot11MeshHWMPperrMinInterval, m_dot11MeshHWMPpreqMinInterval, m_dot11MeshHWMPrannInterval, m_interfaces, m_isRoot, m_maxQueueSize, m_maxTtl, m_rfFlag, m_stats, m_unicastDataThreshold, m_unicastPerrThreshold, m_unicastPreqThreshold, and ns3::dot11s::HwmpProtocol::Statistics::Print().
RequestRoute()
bool ns3::dot11s::HwmpProtocol::RequestRoute (uint32_t sourceIface, const Mac48Address source, const Mac48Address destination, Ptr< const Packet > packet, uint16_t protocolType, MeshL2RoutingProtocol::RouteReplyCallback routeReply) virtual
Route request, inherited from MeshL2RoutingProtocol.
Parameters
sourceIface the source interface
source the source address
destination the destination address
packet the packet to route
protocolType the protocol type
routeReply the route reply
Returns
true if route exists
Implements ns3::MeshL2RoutingProtocol.
Definition at line 242 of file hwmp-protocol.cc.
References ns3::Packet::AddPacketTag(), first::address, ns3::Packet::Copy(), ns3::dot11s::HwmpTag::DecrementTtl(), ns3::dot11s::HwmpProtocol::Statistics::droppedTtl, ForwardUnicast(), ns3::Mac48Address::GetBroadcast(), GetBroadcastReceivers(), ns3::MeshL2RoutingProtocol::GetMeshPoint(), ns3::Packet::GetSize(), ns3::dot11s::HwmpTag::GetTtl(), m_dataSeqno, m_interfaces, m_maxTtl, m_stats, NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::Packet::PeekPacketTag(), ns3::Packet::RemovePacketTag(), ns3::dot11s::HwmpTag::SetAddress(), ns3::dot11s::HwmpTag::SetSeqno(), ns3::dot11s::HwmpTag::SetTtl(), ns3::dot11s::HwmpProtocol::Statistics::txBroadcast, and ns3::dot11s::HwmpProtocol::Statistics::txBytes.
ResetStats()
void ns3::dot11s::HwmpProtocol::ResetStats ()
Reset Statistics:
Definition at line 1268 of file hwmp-protocol.cc.
References m_interfaces, m_stats, and NS_LOG_FUNCTION.
RetryPathDiscovery()
void ns3::dot11s::HwmpProtocol::RetryPathDiscovery (Mac48Address dst, uint8_t numOfRetry) private
Generates PREQ retry when retry timeout has expired and route is still unresolved.
Parameters
dst is the destination address
numOfRetry is the number of retries
When PREQ retry has achieved the maximum level - retry mechanism should be canceled
Definition at line 1084 of file hwmp-protocol.cc.
References DequeueFirstPacketByDst(), ns3::dot11s::HwmpProtocol::QueuedPacket::dst, ns3::Mac48Address::GetBroadcast(), GetNextHwmpSeqno(), ns3::dot11s::HwmpRtable::LookupProactive(), ns3::dot11s::HwmpRtable::LookupReactive(), ns3::dot11s::HwmpRtable::LookupReactiveExpired(), m_dot11MeshHWMPmaxPREQretries, m_dot11MeshHWMPnetDiameterTraversalTime, m_interfaces, m_preqTimeouts, m_routeDiscoveryTimeCallback, m_rtable, m_stats, ns3::dot11s::HwmpRtable::MAX_METRIC, ns3::Simulator::Now(), NS_ASSERT, NS_LOG_FUNCTION, ns3::dot11s::HwmpProtocol::QueuedPacket::pkt, ns3::dot11s::HwmpProtocol::QueuedPacket::protocol, ns3::dot11s::HwmpProtocol::QueuedPacket::reply, ns3::dot11s::HwmpRtable::LookupResult::retransmitter, ns3::Simulator::Schedule(), ns3::dot11s::HwmpRtable::LookupResult::seqnum, ns3::dot11s::HwmpProtocol::QueuedPacket::src, and ns3::dot11s::HwmpProtocol::Statistics::totalDropped.
Referenced by ShouldSendPreq().
SendPrep()
void ns3::dot11s::HwmpProtocol::SendPrep (Mac48Address src, Mac48Address dst, Mac48Address retransmitter, uint32_t initMetric, uint32_t originatorDsn, uint32_t destinationSN, uint32_t lifetime, uint32_t interface) private
Send Path Reply.
Parameters
src the source address
dst the destination address
retransmitter the retransmitter address
initMetric the initial metric
originatorDsn the originator DSN
destinationSN the destination DSN
lifetime the lifetime
interface the interface
Definition at line 740 of file hwmp-protocol.cc.
References ns3::dot11s::HwmpProtocol::Statistics::initiatedPrep, m_interfaces, m_maxTtl, m_stats, NS_ASSERT, ns3::dot11s::IePrep::SetDestinationAddress(), ns3::dot11s::IePrep::SetDestinationSeqNumber(), ns3::dot11s::IePrep::SetHopcount(), ns3::dot11s::IePrep::SetLifetime(), ns3::dot11s::IePrep::SetMetric(), ns3::dot11s::IePrep::SetOriginatorAddress(), ns3::dot11s::IePrep::SetOriginatorSeqNumber(), and ns3::dot11s::IePrep::SetTtl().
Referenced by ReceivePreq().
SendProactivePreq()
void ns3::dot11s::HwmpProtocol::SendProactivePreq () private
Proactive Preq routines:
Definition at line 1141 of file hwmp-protocol.cc.
References ns3::dot11s::IePreq::AddDestinationAddressElement(), GetAddress(), ns3::Mac48Address::GetBroadcast(), ns3::Time::GetMicroSeconds(), GetNextHwmpSeqno(), GetNextPreqId(), m_dot11MeshHWMPactiveRootTimeout, m_dot11MeshHWMPpathToRootInterval, m_interfaces, m_maxTtl, m_proactivePreqTimer, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), ns3::dot11s::IePreq::SetHopcount(), ns3::dot11s::IePreq::SetLifetime(), ns3::dot11s::IePreq::SetOriginatorAddress(), ns3::dot11s::IePreq::SetOriginatorSeqNumber(), ns3::dot11s::IePreq::SetPreqID(), and ns3::dot11s::IePreq::SetTTL().
Referenced by DoInitialize().
SetNeighboursCallback()
void ns3::dot11s::HwmpProtocol::SetNeighboursCallback (Callback< std::vector< Mac48Address >, uint32_t > cb)
This callback is used to obtain active neighbours on a given interface.
Parameters
cb is a callback, which returns a list of addresses on given interface (uint32_t)
Definition at line 810 of file hwmp-protocol.cc.
References m_neighboursCallback.
SetRoot()
void ns3::dot11s::HwmpProtocol::SetRoot ()
Definition at line 1128 of file hwmp-protocol.cc.
References m_address, m_isRoot, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
ShouldSendPreq()
bool ns3::dot11s::HwmpProtocol::ShouldSendPreq (Mac48Address dst) private
checks when the last path discovery procedure was started for a given destination.
Returns
true if should send PREQ
Parameters
dst is the destination address
If the retry counter has not achieved the maximum level - preq should not be sent
Definition at line 1069 of file hwmp-protocol.cc.
References m_dot11MeshHWMPnetDiameterTraversalTime, m_preqTimeouts, ns3::Simulator::Now(), NS_LOG_FUNCTION, RetryPathDiscovery(), and ns3::Simulator::Schedule().
Referenced by ForwardUnicast().
UnsetRoot()
void ns3::dot11s::HwmpProtocol::UnsetRoot ()
Definition at line 1135 of file hwmp-protocol.cc.
References ns3::EventId::Cancel(), m_proactivePreqTimer, and NS_LOG_FUNCTION.
Friends And Related Function Documentation
HwmpProtocolMac
friend class HwmpProtocolMac friend
allow HwmpProtocolMac class friend access
Definition at line 158 of file hwmp-protocol.h.
Member Data Documentation
m_address
Mac48Address ns3::dot11s::HwmpProtocol::m_address private
address
Definition at line 420 of file hwmp-protocol.h.
Referenced by GetAddress(), Install(), Report(), and SetRoot().
m_coefficient
Ptr<UniformRandomVariable> ns3::dot11s::HwmpProtocol::m_coefficient private
Random variable for random start time.
coefficient
Definition at line 470 of file hwmp-protocol.h.
Referenced by HwmpProtocol(), AssignStreams(), and DoInitialize().
m_dataSeqno
uint32_t ns3::dot11s::HwmpProtocol::m_dataSeqno private
data sequence no
Definition at line 421 of file hwmp-protocol.h.
Referenced by RequestRoute().
m_doFlag
bool ns3::dot11s::HwmpProtocol::m_doFlag private
Definition at line 465 of file hwmp-protocol.h.
Referenced by GetDoFlag(), GetTypeId(), and Report().
m_dot11MeshHWMPactivePathTimeout
Time ns3::dot11s::HwmpProtocol::m_dot11MeshHWMPactivePathTimeout private
Definition at line 457 of file hwmp-protocol.h.
Referenced by GetActivePathLifetime(), GetTypeId(), and Report().
m_dot11MeshHWMPactiveRootTimeout
Time ns3::dot11s::HwmpProtocol::m_dot11MeshHWMPactiveRootTimeout private
Definition at line 456 of file hwmp-protocol.h.
Referenced by GetTypeId(), Report(), and SendProactivePreq().
m_dot11MeshHWMPmaxPREQretries
uint8_t ns3::dot11s::HwmpProtocol::m_dot11MeshHWMPmaxPREQretries private
Definition at line 452 of file hwmp-protocol.h.
Referenced by GetTypeId(), Report(), and RetryPathDiscovery().
m_dot11MeshHWMPnetDiameterTraversalTime
Time ns3::dot11s::HwmpProtocol::m_dot11MeshHWMPnetDiameterTraversalTime private
Definition at line 453 of file hwmp-protocol.h.
Referenced by GetTypeId(), Report(), RetryPathDiscovery(), and ShouldSendPreq().
m_dot11MeshHWMPpathToRootInterval
Time ns3::dot11s::HwmpProtocol::m_dot11MeshHWMPpathToRootInterval private
Definition at line 458 of file hwmp-protocol.h.
Referenced by GetTypeId(), Report(), and SendProactivePreq().
m_dot11MeshHWMPperrMinInterval
Time ns3::dot11s::HwmpProtocol::m_dot11MeshHWMPperrMinInterval private
Definition at line 455 of file hwmp-protocol.h.
Referenced by GetPerrMinInterval(), GetTypeId(), and Report().
m_dot11MeshHWMPpreqMinInterval
Time ns3::dot11s::HwmpProtocol::m_dot11MeshHWMPpreqMinInterval private
Definition at line 454 of file hwmp-protocol.h.
Referenced by GetPreqMinInterval(), GetTypeId(), and Report().
m_dot11MeshHWMPrannInterval
Time ns3::dot11s::HwmpProtocol::m_dot11MeshHWMPrannInterval private
Definition at line 459 of file hwmp-protocol.h.
Referenced by GetTypeId(), and Report().
m_hwmpSeqno
uint32_t ns3::dot11s::HwmpProtocol::m_hwmpSeqno private
HWMP sequence no.
Definition at line 422 of file hwmp-protocol.h.
Referenced by GetNextHwmpSeqno().
m_hwmpSeqnoMetricDatabase
std::map<Mac48Address, std::pair<uint32_t, uint32_t> > ns3::dot11s::HwmpProtocol::m_hwmpSeqnoMetricDatabase private
keeps HWMP seqno (first in pair) and HWMP metric (second in pair) for each address
Definition at line 429 of file hwmp-protocol.h.
Referenced by DoDispose(), ReceivePrep(), and ReceivePreq().
m_interfaces
HwmpProtocolMacMap ns3::dot11s::HwmpProtocol::m_interfaces private
interfaces
Definition at line 419 of file hwmp-protocol.h.
Referenced by DoDispose(), ForwardPathError(), ForwardUnicast(), InitiatePathError(), Install(), ReceivePrep(), ReceivePreq(), Report(), RequestRoute(), ResetStats(), RetryPathDiscovery(), SendPrep(), and SendProactivePreq().
m_isRoot
bool ns3::dot11s::HwmpProtocol::m_isRoot private
Definition at line 460 of file hwmp-protocol.h.
Referenced by DoInitialize(), Report(), and SetRoot().
m_lastDataSeqno
std::map<Mac48Address, uint32_t> ns3::dot11s::HwmpProtocol::m_lastDataSeqno private
keeps HWMP seqno (first in pair) and HWMP metric (second in pair) for each address
Definition at line 427 of file hwmp-protocol.h.
Referenced by DoDispose(), and DropDataFrame().
m_maxQueueSize
uint16_t ns3::dot11s::HwmpProtocol::m_maxQueueSize private
Definition at line 451 of file hwmp-protocol.h.
Referenced by GetTypeId(), QueuePacket(), and Report().
m_maxTtl
uint8_t ns3::dot11s::HwmpProtocol::m_maxTtl private
Definition at line 461 of file hwmp-protocol.h.
Referenced by GetMaxTtl(), GetTypeId(), Report(), RequestRoute(), SendPrep(), and SendProactivePreq().
m_neighboursCallback
Callback<std::vector<Mac48Address>, uint32_t> ns3::dot11s::HwmpProtocol::m_neighboursCallback private
neighbors callback
Definition at line 471 of file hwmp-protocol.h.
Referenced by GetBroadcastReceivers(), GetPreqReceivers(), and SetNeighboursCallback().
m_preqId
uint32_t ns3::dot11s::HwmpProtocol::m_preqId private
PREQ ID.
Definition at line 423 of file hwmp-protocol.h.
Referenced by GetNextPreqId().
m_preqTimeouts
std::map<Mac48Address, PreqEvent> ns3::dot11s::HwmpProtocol::m_preqTimeouts private
PREQ timeouts.
Definition at line 441 of file hwmp-protocol.h.
Referenced by DoDispose(), ReactivePathResolved(), RetryPathDiscovery(), and ShouldSendPreq().
m_proactivePreqTimer
EventId ns3::dot11s::HwmpProtocol::m_proactivePreqTimer private
proactive PREQ timer
Definition at line 442 of file hwmp-protocol.h.
Referenced by DoDispose(), DoInitialize(), SendProactivePreq(), and UnsetRoot().
m_randomStart
Time ns3::dot11s::HwmpProtocol::m_randomStart private
Random start in Proactive PREQ propagation.
Definition at line 444 of file hwmp-protocol.h.
Referenced by DoInitialize(), and GetTypeId().
m_rfFlag
bool ns3::dot11s::HwmpProtocol::m_rfFlag private
Definition at line 466 of file hwmp-protocol.h.
Referenced by GetRfFlag(), GetTypeId(), and Report().
m_routeChangeTraceSource
TracedCallback<struct RouteChange> ns3::dot11s::HwmpProtocol::m_routeChangeTraceSource private
Route change trace source.
Definition at line 316 of file hwmp-protocol.h.
Referenced by GetPerrReceivers(), GetTypeId(), MakePathError(), ReceivePrep(), and ReceivePreq().
m_routeDiscoveryTimeCallback
TracedCallback<Time> ns3::dot11s::HwmpProtocol::m_routeDiscoveryTimeCallback private
Route discovery time:
Definition at line 312 of file hwmp-protocol.h.
Referenced by GetTypeId(), ReactivePathResolved(), and RetryPathDiscovery().
m_rqueue
std::vector<QueuedPacket> ns3::dot11s::HwmpProtocol::m_rqueue private
Packet Queue.
Definition at line 446 of file hwmp-protocol.h.
Referenced by DequeueFirstPacket(), DequeueFirstPacketByDst(), DoDispose(), and QueuePacket().
m_rtable
Ptr<HwmpRtable> ns3::dot11s::HwmpProtocol::m_rtable private
Routing table.
Definition at line 433 of file hwmp-protocol.h.
Referenced by DoDispose(), ForwardUnicast(), GetPerrReceivers(), GetRoutingTable(), MakePathError(), PeerLinkStatus(), ProactivePathResolved(), ReactivePathResolved(), ReceivePerr(), ReceivePrep(), ReceivePreq(), and RetryPathDiscovery().
m_stats
Statistics ns3::dot11s::HwmpProtocol::m_stats private
statistics
Definition at line 417 of file hwmp-protocol.h.
Referenced by ForwardUnicast(), MakePathError(), ProactivePathResolved(), ReactivePathResolved(), Report(), RequestRoute(), ResetStats(), RetryPathDiscovery(), and SendPrep().
m_unicastDataThreshold
uint8_t ns3::dot11s::HwmpProtocol::m_unicastDataThreshold private
Definition at line 464 of file hwmp-protocol.h.
Referenced by GetBroadcastReceivers(), GetTypeId(), and Report().
m_unicastPerrThreshold
uint8_t ns3::dot11s::HwmpProtocol::m_unicastPerrThreshold private
Definition at line 462 of file hwmp-protocol.h.
Referenced by GetTypeId(), GetUnicastPerrThreshold(), and Report().
m_unicastPreqThreshold
uint8_t ns3::dot11s::HwmpProtocol::m_unicastPreqThreshold private
Definition at line 463 of file hwmp-protocol.h.
Referenced by GetPreqReceivers(), GetTypeId(), and Report().
The documentation for this class was generated from the following files:
src/mesh/model/dot11s/hwmp-protocol.h
src/mesh/model/dot11s/hwmp-protocol.cc