ns-3: ns3::WifiNetDevice Class Reference
ns3::WifiNetDevice Class Reference
Wifi Models
Hold together all Wifi-related objects.
#include "wifi-net-device.h"
Public Member Functions
WifiNetDevice ()
virtual ~WifiNetDevice ()
void AddLinkChangeCallback (Callback< void > callback)
Address GetAddress (void) const
Address GetBroadcast (void) const
Ptr< Channel > GetChannel (void) const
Ptr< HeConfiguration > GetHeConfiguration (void) const
Ptr< HtConfiguration > GetHtConfiguration (void) const
uint32_t GetIfIndex (void) const
Ptr< WifiMac > GetMac (void) const
uint16_t GetMtu (void) const
Address GetMulticast (Ipv4Address multicastGroup) const
Make and return a MAC multicast address using the provided multicast group.
Address GetMulticast (Ipv6Address addr) const
Get the MAC multicast address corresponding to the IPv6 address provided.
Ptr< Node > GetNode (void) const
Ptr< WifiPhy > GetPhy (void) const
Ptr< WifiRemoteStationManager > GetRemoteStationManager (void) const
Ptr< VhtConfiguration > GetVhtConfiguration (void) const
bool IsBridge (void) const
Return true if the net device is acting as a bridge.
bool IsBroadcast (void) const
bool IsLinkUp (void) const
bool IsMulticast (void) const
bool IsPointToPoint (void) const
Return true if the net device is on a point-to-point link.
bool NeedsArp (void) const
bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)
bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
void SetAddress (Address address)
Set the address of this interface.
void SetHeConfiguration (Ptr< HeConfiguration > heConfiguration)
void SetHtConfiguration (Ptr< HtConfiguration > htConfiguration)
void SetIfIndex (const uint32_t index)
void SetMac (const Ptr< WifiMac > mac)
bool SetMtu (const uint16_t mtu)
void SetNode (const Ptr< Node > node)
void SetPhy (const Ptr< WifiPhy > phy)
void SetPromiscReceiveCallback (PromiscReceiveCallback cb)
void SetReceiveCallback (NetDevice::ReceiveCallback cb)
void SetRemoteStationManager (const Ptr< WifiRemoteStationManager > manager)
void SetVhtConfiguration (Ptr< VhtConfiguration > vhtConfiguration)
bool SupportsSendFrom (void) const
Public Member Functions inherited from ns3::NetDevice
virtual ~NetDevice ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::NetDevice
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
void DoDispose (void)
Destructor implementation.
void DoInitialize (void)
Initialize() implementation.
void ForwardUp (Ptr< const Packet > packet, Mac48Address from, Mac48Address to)
Receive a packet from the lower layer and pass the packet up the stack.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
WifiNetDevice (const WifiNetDevice &o)
Copy constructor.
void CompleteConfig (void)
Complete the configuration of this Wi-Fi device by connecting all lower components (e.g.
void LinkDown (void)
Set that the link is down (i.e.
void LinkUp (void)
Set that the link is up.
WifiNetDevice & operator= (const WifiNetDevice &o)
Assignment operator.
Private Attributes
bool m_configComplete
configuration complete
NetDevice::ReceiveCallback m_forwardUp
forward up callback
Ptr< HeConfiguration > m_heConfiguration
the HeConfiguration
Ptr< HtConfiguration > m_htConfiguration
the HtConfiguration
uint32_t m_ifIndex
IF index.
TracedCallback m_linkChanges
link change callback
bool m_linkUp
link up
Ptr< WifiMac > m_mac
the MAC
uint16_t m_mtu
MTU.
Ptr< Node > m_node
the node
Ptr< WifiPhy > m_phy
the phy
NetDevice::PromiscReceiveCallback m_promiscRx
promiscuous receive callback
TracedCallback< Ptr< const Packet >, Mac48Address > m_rxLogger
receive trace callback
Ptr< WifiRemoteStationManager > m_stationManager
the station manager
TracedCallback< Ptr< const Packet >, Mac48Address > m_txLogger
transmit trace callback
Ptr< VhtConfiguration > m_vhtConfiguration
the VhtConfiguration
Additional Inherited Members
Public Types inherited from ns3::NetDevice
typedef void(* LinkChangeTracedCallback) (void)
TracedCallback signature for link changed event.
enum PacketType {
PACKET_HOST = 1 , NS3_PACKET_HOST = PACKET_HOST , PACKET_BROADCAST , NS3_PACKET_BROADCAST = PACKET_BROADCAST ,
PACKET_MULTICAST , NS3_PACKET_MULTICAST = PACKET_MULTICAST , PACKET_OTHERHOST , NS3_PACKET_OTHERHOST = PACKET_OTHERHOST
}
Packet types are used as they are in Linux.
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address &, const Address &, enum PacketType > PromiscReceiveCallback
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address & > ReceiveCallback
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Hold together all Wifi-related objects.
This class holds together ns3::Channel, ns3::WifiPhy, ns3::WifiMac, and, ns3::WifiRemoteStationManager.
Config Paths
ns3::WifiNetDevice is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice"
Attributes
Mtu: The MAC-level Maximum Transmission Unit
Set with class: ns3::UintegerValue
Underlying type: uint16_t 1:2296
Initial value: 2296
Flags: construct write read
Channel: The channel attached to this device
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::Channel>
Flags: read
Phy: The PHY layer attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::WifiPhy>
Initial value: 0x0
Flags: construct write read
Mac: The MAC layer attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::WifiMac>
Initial value: 0x0
Flags: construct write read
RemoteStationManager: The station manager attached to this device.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::WifiRemoteStationManager>
Initial value: 0x0
Flags: construct write read
HtConfiguration: The HtConfiguration object.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::HtConfiguration>
Flags: read
VhtConfiguration: The VhtConfiguration object.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::VhtConfiguration>
Flags: read
HeConfiguration: The HeConfiguration object.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::HeConfiguration>
Flags: read
No TraceSources are defined for this type.
Size of this type is 192 bytes (on a 64-bit architecture).
Definition at line 53 of file wifi-net-device.h.
Constructor & Destructor Documentation
WifiNetDevice() [1/2]
ns3::WifiNetDevice::WifiNetDevice ()
Definition at line 90 of file wifi-net-device.cc.
References NS_LOG_FUNCTION_NOARGS.
~WifiNetDevice()
ns3::WifiNetDevice::~WifiNetDevice () virtual
Definition at line 96 of file wifi-net-device.cc.
References NS_LOG_FUNCTION_NOARGS.
WifiNetDevice() [2/2]
ns3::WifiNetDevice::WifiNetDevice (const WifiNetDevice & o) private
Copy constructor.
Parameters
o object to copy
Defined and unimplemented to avoid misuse
Member Function Documentation
AddLinkChangeCallback()
void ns3::WifiNetDevice::AddLinkChangeCallback (Callback< void > callback) virtual
Parameters
callback the callback to invoke
Add a callback invoked whenever the link status changes to UP. This callback is typically used by the IP/ARP layer to flush the ARP cache and by IPv6 stack to flush NDISC cache whenever the link goes up.
Implements ns3::NetDevice.
Definition at line 272 of file wifi-net-device.cc.
References ns3::TracedCallback< Ts >::ConnectWithoutContext(), and m_linkChanges.
CompleteConfig()
void ns3::WifiNetDevice::CompleteConfig (void) private
Complete the configuration of this Wi-Fi device by connecting all lower components (e.g.
MAC, WifiRemoteStation) together.
Definition at line 159 of file wifi-net-device.cc.
References ForwardUp(), LinkDown(), LinkUp(), m_configComplete, m_mac, m_node, m_phy, m_stationManager, ns3::MakeCallback(), ns3::WifiRemoteStationManager::SetupMac(), and ns3::WifiRemoteStationManager::SetupPhy().
Referenced by SetMac(), SetNode(), SetPhy(), and SetRemoteStationManager().
DoDispose()
void ns3::WifiNetDevice::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 102 of file wifi-net-device.cc.
References ns3::Object::Dispose(), ns3::Object::DoDispose(), m_heConfiguration, m_htConfiguration, m_mac, m_node, m_phy, m_stationManager, m_vhtConfiguration, and NS_LOG_FUNCTION_NOARGS.
DoInitialize()
void ns3::WifiNetDevice::DoInitialize (void) protected virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 140 of file wifi-net-device.cc.
References ns3::Object::DoInitialize(), ns3::Object::Initialize(), m_mac, m_phy, m_stationManager, and NS_LOG_FUNCTION_NOARGS.
ForwardUp()
void ns3::WifiNetDevice::ForwardUp (Ptr< const Packet > packet, Mac48Address from, Mac48Address to) protected
Receive a packet from the lower layer and pass the packet up the stack.
Parameters
packet the packet to forward up
from the source address
to the destination address
Definition at line 361 of file wifi-net-device.cc.
References ns3::LlcSnapHeader::GetType(), ns3::Mac48Address::IsBroadcast(), ns3::Mac48Address::IsGroup(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_forwardUp, m_mac, m_promiscRx, NS_LOG_FUNCTION, ns3::NetDevice::PACKET_BROADCAST, ns3::NetDevice::PACKET_HOST, ns3::NetDevice::PACKET_MULTICAST, ns3::NetDevice::PACKET_OTHERHOST, and ns3::Packet::RemoveHeader().
Referenced by CompleteConfig().
GetAddress()
Address ns3::WifiNetDevice::GetAddress (void) const virtual
Returns
the current Address of this interface.
Implements ns3::NetDevice.
Definition at line 243 of file wifi-net-device.cc.
References m_mac.
Referenced by ContextToMac(), BlockAckAggregationDisabledTest::DoRun(), PreservePacketsInAmpdus::DoRun(), Bug730TestCase::DoRun(), QosFragmentationTestCase::DoRun(), Bug2222TestCase::DoRun(), OcbWifiMacTestCase::PostDeviceConfiguration(), and TestInterBssConstantObssPdAlgo::SendOnePacket().
GetBroadcast()
Address ns3::WifiNetDevice::GetBroadcast (void) const virtual
Returns
the broadcast address supported by this netdevice.
Calling this method is invalid if IsBroadcast returns not true.
Implements ns3::NetDevice.
Definition at line 284 of file wifi-net-device.cc.
References ns3::Mac48Address::GetBroadcast().
Referenced by WifiTest::SendOnePacket(), InterferenceHelperSequenceTest::SendOnePacket(), and DcfImmediateAccessBroadcastTestCase::SendOnePacket().
GetChannel()
Ptr< Channel > ns3::WifiNetDevice::GetChannel (void) const virtual
Returns
the channel this NetDevice is connected to. The value returned can be zero if the NetDevice is not yet connected to any channel or if the underlying NetDevice has no concept of a channel. i.e., callers must check for zero and be ready to handle it.
Implements ns3::NetDevice.
Definition at line 231 of file wifi-net-device.cc.
References ns3::WifiPhy::GetChannel(), and m_phy.
Referenced by GetTypeId().
GetHeConfiguration()
Ptr< HeConfiguration > ns3::WifiNetDevice::GetHeConfiguration (void) const
Returns
pointer to HeConfiguration if it exists
Definition at line 480 of file wifi-net-device.cc.
References m_heConfiguration.
Referenced by ns3::ConvertGuardIntervalToNanoSeconds(), ns3::WifiPhy::GetAddressedPsduInPpdu(), ns3::WifiRemoteStationManager::GetDataTxVector(), ns3::WifiRemoteStationManager::GetGuardInterval(), ns3::WifiMac::GetHeConfiguration(), ns3::WifiRemoteStationManager::GetHeSupported(), GetTypeId(), ns3::ConstantObssPdAlgorithm::ReceiveHeSig(), ns3::ObssPdAlgorithm::ResetPhy(), and TestInterBssConstantObssPdAlgo::RunOne().
GetHtConfiguration()
Ptr< HtConfiguration > ns3::WifiNetDevice::GetHtConfiguration (void) const
Returns
pointer to HtConfiguration if it exists
Definition at line 456 of file wifi-net-device.cc.
References m_htConfiguration.
Referenced by ns3::ConvertGuardIntervalToNanoSeconds(), ns3::WifiRemoteStationManager::GetGreenfieldSupported(), ns3::WifiMac::GetHtConfiguration(), ns3::WifiRemoteStationManager::GetHtSupported(), ns3::WifiRemoteStationManager::GetLdpcSupported(), ns3::WifiRemoteStationManager::GetShortGuardIntervalSupported(), GetTypeId(), and Experiment::Run().
GetIfIndex()
uint32_t ns3::WifiNetDevice::GetIfIndex (void) const virtual
Returns
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 225 of file wifi-net-device.cc.
References m_ifIndex.
Referenced by BlockAckAggregationDisabledTest::DoRun(), PreservePacketsInAmpdus::DoRun(), Bug730TestCase::DoRun(), QosFragmentationTestCase::DoRun(), Bug2222TestCase::DoRun(), ns3::dot11s::HwmpProtocol::Install(), ns3::flame::FlameProtocol::Install(), and OcbWifiMacTestCase::PostDeviceConfiguration().
GetMac()
Ptr< WifiMac > ns3::WifiNetDevice::GetMac (void) const
Returns
the MAC we are currently using.
Definition at line 201 of file wifi-net-device.cc.
References m_mac.
Referenced by NodeStatistics::NodeStatistics(), ns3::MeshPointDevice::AddInterface(), ns3::WaveNetDevice::CancelTx(), BlockAckAggregationDisabledTest::DoRun(), PreservePacketsInAmpdus::DoRun(), QosFragmentationTestCase::DoRun(), ns3::WaveNetDevice::ForwardUp(), ns3::AnimationInterface::GenericWirelessTxTrace(), ns3::WaveNetDevice::GetAddress(), ns3::MpduAggregator::GetMaxAmpduSize(), ns3::MsduAggregator::GetMaxAmsduSize(), ns3::WifiPhy::GetStaId(), GetTypeId(), ns3::dot11s::HwmpProtocol::Install(), ns3::dot11s::PeerManagementProtocol::Install(), ns3::flame::FlameProtocol::Install(), OcbWifiMacTestCase::PostDeviceConfiguration(), ns3::ConstantObssPdAlgorithm::ReceiveHeSig(), ns3::Dot11sStack::Report(), ns3::Dot11sStack::ResetStats(), Experiment::Run(), Issue40TestCase::RunOne(), ns3::WaveNetDevice::Send(), ns3::WaveNetDevice::SendX(), ns3::WaveNetDevice::SupportsSendFrom(), StaWifiMacScanningTestCase::TurnBeaconGenerationOn(), and ns3::AnimationInterface::WifiPhyTxBeginTrace().
GetMtu()
uint16_t ns3::WifiNetDevice::GetMtu (void) const virtual
Returns
the link-level MTU in bytes for this interface.
This value is typically used by the IP layer to perform IP fragmentation when needed.
Implements ns3::NetDevice.
Definition at line 260 of file wifi-net-device.cc.
References m_mtu.
Referenced by GetTypeId().
GetMulticast() [1/2]
Address ns3::WifiNetDevice::GetMulticast (Ipv4Address multicastGroup) const virtual
Make and return a MAC multicast address using the provided multicast group.
RFC 1112 says that an Ipv4 host group address is mapped to an Ethernet multicast address by placing the low-order 23-bits of the IP address into the low-order 23 bits of the Ethernet multicast address 01-00-5E-00-00-00 (hex). Similar RFCs exist for Ipv6 and Eui64 mappings. This method performs the multicast address creation function appropriate to the underlying MAC address of the device. This MAC address is encapsulated in an abstract Address to avoid dependencies on the exact MAC address format.
In the case of net devices that do not support multicast, clients are expected to test NetDevice::IsMulticast and avoid attempting to map multicast packets. Subclasses of NetDevice that do support multicasting are expected to override this method and provide an implementation appropriate to the particular device.
Parameters
multicastGroup The IP address for the multicast group destination of the packet.
Returns
The MAC multicast Address used to send packets to the provided multicast group.
Warning
Calling this method is invalid if IsMulticast returns not true.
See also
IsMulticast()
Implements ns3::NetDevice.
Definition at line 296 of file wifi-net-device.cc.
References ns3::Mac48Address::GetMulticast().
GetMulticast() [2/2]
Address ns3::WifiNetDevice::GetMulticast (Ipv6Address addr) const virtual
Get the MAC multicast address corresponding to the IPv6 address provided.
Parameters
addr IPv6 address
Returns
the MAC multicast address
Warning
Calling this method is invalid if IsMulticast returns not true.
Implements ns3::NetDevice.
Definition at line 301 of file wifi-net-device.cc.
References ns3::Mac48Address::GetMulticast().
GetNode()
Ptr< Node > ns3::WifiNetDevice::GetNode (void) const virtual
Returns
the node base class which contains this network interface.
When a subclass needs to get access to the underlying node base class to print the nodeid for example, it can invoke this method.
Implements ns3::NetDevice.
Definition at line 336 of file wifi-net-device.cc.
References m_node.
Referenced by ns3::AnimationInterface::GenericWirelessTxTrace(), and ns3::AnimationInterface::WifiPhyTxBeginTrace().
GetPhy()
Ptr< WifiPhy > ns3::WifiNetDevice::GetPhy (void) const
Returns
the PHY we are currently using.
Definition at line 207 of file wifi-net-device.cc.
References m_phy.
Referenced by NodeStatistics::NodeStatistics(), TestInterBssConstantObssPdAlgo::CheckPhyState(), ns3::ConstantObssPdAlgorithm::ConnectWifiNetDevice(), ns3::WifiRadioEnergyModelHelper::DoInstall(), ns3::WifiPhyHelper::EnablePcapInternal(), ns3::WaveNetDevice::GetChannel(), GetTypeId(), GetYansWifiPhyPtr(), SetChannelFrequencyTest::GetYansWifiPhyPtr(), ns3::ObssPdAlgorithm::ResetPhy(), InterferenceHelperSequenceTest::SwitchCh(), and StaWifiMacScanningTestCase::TurnApOff().
GetRemoteStationManager()
Ptr< WifiRemoteStationManager > ns3::WifiNetDevice::GetRemoteStationManager (void) const
Returns
the remote station manager we are currently using.
Definition at line 213 of file wifi-net-device.cc.
References m_stationManager.
Referenced by ns3::MpduAggregator::GetMaxAmpduSize(), ns3::MsduAggregator::GetMaxAmsduSize(), GetTypeId(), PowerRateAdaptationTest::TestAparf(), PowerRateAdaptationTest::TestParf(), and PowerRateAdaptationTest::TestRrpaa().
GetTypeId()
TypeId ns3::WifiNetDevice::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 41 of file wifi-net-device.cc.
References GetChannel(), GetHeConfiguration(), GetHtConfiguration(), GetMac(), GetMtu(), GetPhy(), GetRemoteStationManager(), GetVhtConfiguration(), ns3::LLC_SNAP_HEADER_LENGTH, ns3::MakePointerAccessor(), ns3::MakeUintegerAccessor(), ns3::MAX_MSDU_SIZE, SetMac(), SetMtu(), ns3::TypeId::SetParent(), SetPhy(), and SetRemoteStationManager().
GetVhtConfiguration()
Ptr< VhtConfiguration > ns3::WifiNetDevice::GetVhtConfiguration (void) const
Returns
pointer to VhtConfiguration if it exists
Definition at line 468 of file wifi-net-device.cc.
References m_vhtConfiguration.
Referenced by GetTypeId(), ns3::WifiMac::GetVhtConfiguration(), and ns3::WifiRemoteStationManager::GetVhtSupported().
IsBridge()
bool ns3::WifiNetDevice::IsBridge (void) const virtual
Return true if the net device is acting as a bridge.
Returns
value of m_isBridge flag
Implements ns3::NetDevice.
Definition at line 313 of file wifi-net-device.cc.
IsBroadcast()
bool ns3::WifiNetDevice::IsBroadcast (void) const virtual
Returns
true if this interface supports a broadcast address, false otherwise.
Implements ns3::NetDevice.
Definition at line 278 of file wifi-net-device.cc.
IsLinkUp()
bool ns3::WifiNetDevice::IsLinkUp (void) const virtual
Returns
true if link is up; false otherwise
Implements ns3::NetDevice.
Definition at line 266 of file wifi-net-device.cc.
References m_linkUp, and m_phy.
IsMulticast()
bool ns3::WifiNetDevice::IsMulticast (void) const virtual
Returns
value of m_isMulticast flag
Implements ns3::NetDevice.
Definition at line 290 of file wifi-net-device.cc.
IsPointToPoint()
bool ns3::WifiNetDevice::IsPointToPoint (void) const virtual
Return true if the net device is on a point-to-point link.
Returns
value of m_isPointToPoint flag
Implements ns3::NetDevice.
Definition at line 307 of file wifi-net-device.cc.
LinkDown()
void ns3::WifiNetDevice::LinkDown (void) private
Set that the link is down (i.e.
STA is not associated).
Definition at line 410 of file wifi-net-device.cc.
References m_linkChanges, and m_linkUp.
Referenced by CompleteConfig().
LinkUp()
void ns3::WifiNetDevice::LinkUp (void) private
Set that the link is up.
A link is always up in ad-hoc mode. For a STA, a link is up when the STA is associated with an AP.
Definition at line 403 of file wifi-net-device.cc.
References m_linkChanges, and m_linkUp.
Referenced by CompleteConfig().
NeedsArp()
bool ns3::WifiNetDevice::NeedsArp (void) const virtual
Returns
true if ARP is needed, false otherwise.
Called by higher-layers to check if this NetDevice requires ARP to be used.
Implements ns3::NetDevice.
Definition at line 349 of file wifi-net-device.cc.
operator=()
WifiNetDevice& ns3::WifiNetDevice::operator= (const WifiNetDevice & o) private
Assignment operator.
Parameters
o object to copy
Returns
the copied object
Defined and unimplemented to avoid misuse
Send()
bool ns3::WifiNetDevice::Send (Ptr< Packet > packet, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device to the specified destination Address
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 319 of file wifi-net-device.cc.
References ns3::Packet::AddHeader(), ns3::Mac48Address::ConvertFrom(), ns3::Mac48Address::IsMatchingType(), m_mac, NS_ASSERT, NS_LOG_FUNCTION, and ns3::LlcSnapHeader::SetType().
Referenced by WifiTest::SendOnePacket(), InterferenceHelperSequenceTest::SendOnePacket(), DcfImmediateAccessBroadcastTestCase::SendOnePacket(), TestInterBssConstantObssPdAlgo::SendOnePacket(), PowerRateAdaptationTest::TestAparf(), PowerRateAdaptationTest::TestParf(), and PowerRateAdaptationTest::TestRrpaa().
SendFrom()
bool ns3::WifiNetDevice::SendFrom (Ptr< Packet > packet, const Address & source, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
source source mac address (so called "MAC spoofing")
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device with the specified source and destination Addresses.
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 417 of file wifi-net-device.cc.
References ns3::Packet::AddHeader(), ns3::Mac48Address::ConvertFrom(), ns3::Mac48Address::IsMatchingType(), m_mac, NS_ASSERT, NS_LOG_FUNCTION, and ns3::LlcSnapHeader::SetType().
SetAddress()
void ns3::WifiNetDevice::SetAddress (Address address) virtual
Set the address of this interface.
Parameters
address address to set
Implements ns3::NetDevice.
Definition at line 237 of file wifi-net-device.cc.
References first::address, ns3::Mac48Address::ConvertFrom(), and m_mac.
SetHeConfiguration()
void ns3::WifiNetDevice::SetHeConfiguration (Ptr< HeConfiguration > heConfiguration)
Parameters
heConfiguration pointer to HeConfiguration
Definition at line 474 of file wifi-net-device.cc.
References m_heConfiguration.
Referenced by HeAggregationTest::DoRunSubTest(), and ns3::WifiHelper::Install().
SetHtConfiguration()
void ns3::WifiNetDevice::SetHtConfiguration (Ptr< HtConfiguration > htConfiguration)
Parameters
htConfiguration pointer to HtConfiguration
Definition at line 450 of file wifi-net-device.cc.
References m_htConfiguration.
Referenced by AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), Bug2831TestCase::DoRun(), HeAggregationTest::DoRunSubTest(), and ns3::WifiHelper::Install().
SetIfIndex()
void ns3::WifiNetDevice::SetIfIndex (const uint32_t index) virtual
Parameters
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 219 of file wifi-net-device.cc.
References m_ifIndex.
SetMac()
void ns3::WifiNetDevice::SetMac (const Ptr< WifiMac > mac)
Parameters
mac the MAC layer to use.
Definition at line 180 of file wifi-net-device.cc.
References CompleteConfig(), m_mac, and third::mac.
Referenced by PowerRateAdaptationTest::ConfigureNode(), ns3::MeshHelper::CreateInterface(), WifiTest::CreateOne(), InterferenceHelperSequenceTest::CreateOne(), AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), DcfImmediateAccessBroadcastTestCase::DoRun(), Bug2831TestCase::DoRun(), HeAggregationTest::DoRunSubTest(), GetTypeId(), and ns3::WifiHelper::Install().
SetMtu()
bool ns3::WifiNetDevice::SetMtu (const uint16_t mtu) virtual
Parameters
mtu MTU value, in bytes, to set for the device
Returns
whether the MTU value was within legal bounds
Override for default MTU defined on a per-type basis.
Implements ns3::NetDevice.
Definition at line 249 of file wifi-net-device.cc.
References ns3::LLC_SNAP_HEADER_LENGTH, m_mtu, and ns3::MAX_MSDU_SIZE.
Referenced by GetTypeId().
SetNode()
void ns3::WifiNetDevice::SetNode (const Ptr< Node > node) virtual
Parameters
node the node associated to this netdevice.
This method is called from ns3::Node::AddDevice.
Implements ns3::NetDevice.
Definition at line 342 of file wifi-net-device.cc.
References CompleteConfig(), and m_node.
SetPhy()
void ns3::WifiNetDevice::SetPhy (const Ptr< WifiPhy > phy)
Parameters
phy the PHY layer to use.
Definition at line 187 of file wifi-net-device.cc.
References CompleteConfig(), m_phy, and third::phy.
Referenced by PowerRateAdaptationTest::ConfigureNode(), ns3::MeshHelper::CreateInterface(), WifiTest::CreateOne(), InterferenceHelperSequenceTest::CreateOne(), AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), DcfImmediateAccessBroadcastTestCase::DoRun(), Bug2831TestCase::DoRun(), HeAggregationTest::DoRunSubTest(), SpectrumWifiPhyFilterTest::DoSetup(), TestDlOfdmaPhyTransmission::DoSetup(), GetTypeId(), ns3::WifiHelper::Install(), and InterferenceExperiment::Run().
SetPromiscReceiveCallback()
void ns3::WifiNetDevice::SetPromiscReceiveCallback (PromiscReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received in promiscuous mode and must be forwarded to the higher layers.
Enables netdevice promiscuous mode and sets the callback that will handle promiscuous mode packets. Note, promiscuous mode packets means all packets, including those packets that can be sensed by the netdevice but which are intended to be received by other hosts.
Implements ns3::NetDevice.
Definition at line 437 of file wifi-net-device.cc.
References m_mac, and m_promiscRx.
SetReceiveCallback()
void ns3::WifiNetDevice::SetReceiveCallback (NetDevice::ReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received and must be forwarded to the higher layers.
Set the callback to be used to notify higher layers when a packet has been received.
Implements ns3::NetDevice.
Definition at line 355 of file wifi-net-device.cc.
References m_forwardUp.
SetRemoteStationManager()
void ns3::WifiNetDevice::SetRemoteStationManager (const Ptr< WifiRemoteStationManager > manager)
Parameters
manager the manager to use.
Definition at line 194 of file wifi-net-device.cc.
References CompleteConfig(), and m_stationManager.
Referenced by PowerRateAdaptationTest::ConfigureNode(), ns3::MeshHelper::CreateInterface(), WifiTest::CreateOne(), InterferenceHelperSequenceTest::CreateOne(), AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), DcfImmediateAccessBroadcastTestCase::DoRun(), Bug2831TestCase::DoRun(), HeAggregationTest::DoRunSubTest(), GetTypeId(), and ns3::WifiHelper::Install().
SetVhtConfiguration()
void ns3::WifiNetDevice::SetVhtConfiguration (Ptr< VhtConfiguration > vhtConfiguration)
Parameters
vhtConfiguration pointer to VhtConfiguration
Definition at line 462 of file wifi-net-device.cc.
References m_vhtConfiguration.
Referenced by HeAggregationTest::DoRunSubTest(), and ns3::WifiHelper::Install().
SupportsSendFrom()
bool ns3::WifiNetDevice::SupportsSendFrom (void) const virtual
Returns
true if this interface supports a bridging mode, false otherwise.
Implements ns3::NetDevice.
Definition at line 444 of file wifi-net-device.cc.
References m_mac.
Member Data Documentation
m_configComplete
bool ns3::WifiNetDevice::m_configComplete private
configuration complete
Definition at line 206 of file wifi-net-device.h.
Referenced by CompleteConfig().
m_forwardUp
NetDevice::ReceiveCallback ns3::WifiNetDevice::m_forwardUp private
forward up callback
Definition at line 196 of file wifi-net-device.h.
Referenced by ForwardUp(), and SetReceiveCallback().
m_heConfiguration
Ptr<HeConfiguration> ns3::WifiNetDevice::m_heConfiguration private
the HeConfiguration
Definition at line 195 of file wifi-net-device.h.
Referenced by DoDispose(), GetHeConfiguration(), and SetHeConfiguration().
m_htConfiguration
Ptr<HtConfiguration> ns3::WifiNetDevice::m_htConfiguration private
the HtConfiguration
Definition at line 193 of file wifi-net-device.h.
Referenced by DoDispose(), GetHtConfiguration(), and SetHtConfiguration().
m_ifIndex
uint32_t ns3::WifiNetDevice::m_ifIndex private
IF index.
Definition at line 202 of file wifi-net-device.h.
Referenced by GetIfIndex(), and SetIfIndex().
m_linkChanges
TracedCallback ns3::WifiNetDevice::m_linkChanges private
link change callback
Definition at line 204 of file wifi-net-device.h.
Referenced by AddLinkChangeCallback(), LinkDown(), and LinkUp().
m_linkUp
bool ns3::WifiNetDevice::m_linkUp private
link up
Definition at line 203 of file wifi-net-device.h.
Referenced by IsLinkUp(), LinkDown(), and LinkUp().
m_mac
Ptr<WifiMac> ns3::WifiNetDevice::m_mac private
the MAC
Definition at line 191 of file wifi-net-device.h.
Referenced by CompleteConfig(), DoDispose(), DoInitialize(), ForwardUp(), GetAddress(), GetMac(), Send(), SendFrom(), SetAddress(), SetMac(), SetPromiscReceiveCallback(), and SupportsSendFrom().
m_mtu
uint16_t ns3::WifiNetDevice::m_mtu mutable private
MTU.
Definition at line 205 of file wifi-net-device.h.
Referenced by GetMtu(), and SetMtu().
m_node
Ptr<Node> ns3::WifiNetDevice::m_node private
the node
Definition at line 189 of file wifi-net-device.h.
Referenced by CompleteConfig(), DoDispose(), GetNode(), and SetNode().
m_phy
Ptr<WifiPhy> ns3::WifiNetDevice::m_phy private
the phy
Definition at line 190 of file wifi-net-device.h.
Referenced by CompleteConfig(), DoDispose(), DoInitialize(), GetChannel(), GetPhy(), IsLinkUp(), and SetPhy().
m_promiscRx
NetDevice::PromiscReceiveCallback ns3::WifiNetDevice::m_promiscRx private
promiscuous receive callback
Definition at line 197 of file wifi-net-device.h.
Referenced by ForwardUp(), and SetPromiscReceiveCallback().
m_rxLogger
TracedCallback<Ptr<const Packet>, Mac48Address> ns3::WifiNetDevice::m_rxLogger private
receive trace callback
Definition at line 199 of file wifi-net-device.h.
m_stationManager
Ptr<WifiRemoteStationManager> ns3::WifiNetDevice::m_stationManager private
the station manager
Definition at line 192 of file wifi-net-device.h.
Referenced by CompleteConfig(), DoDispose(), DoInitialize(), GetRemoteStationManager(), and SetRemoteStationManager().
m_txLogger
TracedCallback<Ptr<const Packet>, Mac48Address> ns3::WifiNetDevice::m_txLogger private
transmit trace callback
Definition at line 200 of file wifi-net-device.h.
m_vhtConfiguration
Ptr<VhtConfiguration> ns3::WifiNetDevice::m_vhtConfiguration private
the VhtConfiguration
Definition at line 194 of file wifi-net-device.h.
Referenced by DoDispose(), GetVhtConfiguration(), and SetVhtConfiguration().
The documentation for this class was generated from the following files:
src/wifi/model/wifi-net-device.h
src/wifi/model/wifi-net-device.cc