ns-3: ns3::RngStream Class Reference
ns3::RngStream Class Reference
Core » Random Variables » RNG Implementation
Combined Multiple-Recursive Generator MRG32k3a.
#include "rng-stream.h"
Public Member Functions
RngStream (const RngStream &r)
Copy constructor.
RngStream (uint32_t seed, uint64_t stream, uint64_t substream)
Construct from explicit seed, stream and substream values.
double RandU01 (void)
Generate the next random number for this stream.
Private Member Functions
void AdvanceNthBy (uint64_t nth, int by, double state[6])
Advance state of the RNG by leaps and bounds.
Private Attributes
double m_currentState [6]
The RNG state vector.
Detailed Description
Combined Multiple-Recursive Generator MRG32k3a.
This class is the combined multiple-recursive random number generator called MRG32k3a. The ns3::RandomVariableBase class holds a static instance of this class. The details of this class are explained in: http://www.iro.umontreal.ca/~lecuyer/myftp/papers/streams00.pdf
Definition at line 49 of file rng-stream.h.
Constructor & Destructor Documentation
RngStream() [1/2]
ns3::RngStream::RngStream (uint32_t seed, uint64_t stream, uint64_t substream)
Construct from explicit seed, stream and substream values.
Parameters
[in] seed The starting seed.
[in] stream The stream number.
[in] substream The sub-stream number.
Definition at line 370 of file rng-stream.cc.
References MRG32k3a::m1, MRG32k3a::m2, and NS_FATAL_ERROR.
RngStream() [2/2]
ns3::RngStream::RngStream (const RngStream & r)
Copy constructor.
Parameters
[in] r The RngStream to copy.
Definition at line 384 of file rng-stream.cc.
References m_currentState.
Member Function Documentation
AdvanceNthBy()
void ns3::RngStream::AdvanceNthBy (uint64_t nth, int by, double state[6]) private
Advance state of the RNG by leaps and bounds.
Parameters
[in] nth The stream or substream index.
[in] by The log2 base of nth.
[in] state The state vector to advance.
Definition at line 393 of file rng-stream.cc.
References MRG32k3a::m1, MRG32k3a::m2, MRG32k3a::MatVecModM(), and MRG32k3a::PowerOfTwoMatrix().
RandU01()
double ns3::RngStream::RandU01 (void)
Generate the next random number for this stream.
Uniformly distributed between 0 and 1.
Returns
The next random.
Definition at line 335 of file rng-stream.cc.
References MRG32k3a::a12, MRG32k3a::a13n, MRG32k3a::a21, MRG32k3a::a23n, MRG32k3a::m1, MRG32k3a::m2, and MRG32k3a::norm.
Referenced by ns3::ErlangRandomVariable::GetExponentialValue(), ns3::GammaRandomVariable::GetNormalValue(), ns3::GammaRandomVariable::GetValue(), ns3::ExponentialRandomVariable::GetValue(), ns3::TriangularRandomVariable::GetValue(), ns3::NormalRandomVariable::GetValue(), ns3::UniformRandomVariable::GetValue(), ns3::LogNormalRandomVariable::GetValue(), ns3::ParetoRandomVariable::GetValue(), ns3::WeibullRandomVariable::GetValue(), ns3::ZipfRandomVariable::GetValue(), and ns3::EmpiricalRandomVariable::PreSample().
Member Data Documentation
m_currentState
double ns3::RngStream::m_currentState[6] private
The RNG state vector.
Definition at line 85 of file rng-stream.h.
Referenced by RngStream().
The documentation for this class was generated from the following files:
src/core/model/rng-stream.h
src/core/model/rng-stream.cc