ns-3: Ns2MobilityHelperTest Class Reference
Ns2MobilityHelperTest Class Reference
Mobility » mobility module tests | Test suites
Every test case is supposed to:
Classes
struct ReferencePoint
Single record in mobility reference.
Public Member Functions
Ns2MobilityHelperTest (std::string const &name, Time timeLimit, uint32_t nodes=1)
Create new test case.
virtual ~Ns2MobilityHelperTest ()
Empty.
void AddReferencePoint (const char *id, double sec, Vector const &p, Vector const &v)
Sugar.
void AddReferencePoint (ReferencePoint const &r)
Add next reference point.
void SetTrace (std::string const &trace)
Set NS-2 trace to read as single large string (don't forget to add \n and quote "'s)
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
bool CheckInitialPositions ()
Check that all initial positions are correct.
void CourseChange (std::string context, Ptr< const MobilityModel > mobility)
Listen for course change events.
void CreateNodes ()
Create and name nodes.
void DoRun ()
Go.
void DoSetup ()
Implementation to do any local setup required for this TestCase.
void DoTeardown ()
Implementation to do any local setup required for this TestCase.
bool WriteTrace ()
Dump NS-2 trace to tmp file.
Private Attributes
size_t m_nextRefPoint
Next reference point to be checked.
uint32_t m_nodeCount
Number of nodes used in the test.
std::vector< ReferencePoint > m_reference
Reference mobility.
Time m_timeLimit
Test time limit.
std::string m_trace
Trace as string.
std::string m_traceFile
TMP trace file name.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Every test case is supposed to:
Generate short mobility trace file
Read it back using Ns2MobilityHelper
Check initial node positions and speeds.
Run simulation listening for all CourseChange events and compare actual mobility with the reference
Definition at line 86 of file ns2-mobility-helper-test-suite.cc.
Constructor & Destructor Documentation
Ns2MobilityHelperTest()
Ns2MobilityHelperTest::Ns2MobilityHelperTest (std::string const & name, Time timeLimit, uint32_t nodes = 1) inline
Create new test case.
To make it useful SetTrace () and AddReferencePoint () must be called
Parameters
name Short description
timeLimit Test time limit
nodes Number of nodes used in the test trace, 1 by default
Definition at line 125 of file ns2-mobility-helper-test-suite.cc.
~Ns2MobilityHelperTest()
virtual Ns2MobilityHelperTest::~Ns2MobilityHelperTest () inline virtual
Empty.
Definition at line 133 of file ns2-mobility-helper-test-suite.cc.
Member Function Documentation
AddReferencePoint() [1/2]
void Ns2MobilityHelperTest::AddReferencePoint (const char * id, double sec, Vector const & p, Vector const & v) inline
Sugar.
Definition at line 147 of file ns2-mobility-helper-test-suite.cc.
References ns3::Seconds().
AddReferencePoint() [2/2]
void Ns2MobilityHelperTest::AddReferencePoint (ReferencePoint const & r) inline
Add next reference point.
Definition at line 142 of file ns2-mobility-helper-test-suite.cc.
Referenced by Ns2MobilityHelperTestSuite::Ns2MobilityHelperTestSuite().
CheckInitialPositions()
bool Ns2MobilityHelperTest::CheckInitialPositions () inline private
Check that all initial positions are correct.
Definition at line 190 of file ns2-mobility-helper-test-suite.cc.
References AreVectorsEqual(), ns3::Object::GetObject(), ns3::MobilityModel::GetPosition(), ns3::MobilityModel::GetVelocity(), Ns2MobilityHelperTest::ReferencePoint::node, NS_TEST_ASSERT_MSG_NE_RETURNS_BOOL, NS_TEST_EXPECT_MSG_EQ, Ns2MobilityHelperTest::ReferencePoint::pos, ns3::Seconds(), and Ns2MobilityHelperTest::ReferencePoint::vel.
CourseChange()
void Ns2MobilityHelperTest::CourseChange (std::string context, Ptr< const MobilityModel > mobility) inline private
Listen for course change events.
Definition at line 210 of file ns2-mobility-helper-test-suite.cc.
References AreVectorsEqual(), ns3::Names::FindName(), ns3::Time::GetSeconds(), third::mobility, Ns2MobilityHelperTest::ReferencePoint::node, ns3::Simulator::Now(), NS_ASSERT, NS_TEST_EXPECT_MSG_EQ, NS_TEST_EXPECT_MSG_LT, Ns2MobilityHelperTest::ReferencePoint::pos, Ns2MobilityHelperTest::ReferencePoint::time, and Ns2MobilityHelperTest::ReferencePoint::vel.
Referenced by DoRun().
CreateNodes()
void Ns2MobilityHelperTest::CreateNodes () inline private
Create and name nodes.
Definition at line 178 of file ns2-mobility-helper-test-suite.cc.
References ns3::Names::Add(), and first::nodes.
DoRun()
void Ns2MobilityHelperTest::DoRun (void) inline private virtual
Go.
Implements ns3::TestCase.
Definition at line 247 of file ns2-mobility-helper-test-suite.cc.
References ns3::Config::Connect(), CourseChange(), ns3::MakeCallback(), third::mobility, NS_TEST_ASSERT_MSG_EQ, ns3::Simulator::Run(), and ns3::Simulator::Stop().
DoSetup()
void Ns2MobilityHelperTest::DoSetup (void) inline private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test setup before DoRun is invoked.
Reimplemented from ns3::TestCase.
Definition at line 235 of file ns2-mobility-helper-test-suite.cc.
DoTeardown()
void Ns2MobilityHelperTest::DoTeardown (void) inline private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test teardown
Reimplemented from ns3::TestCase.
Definition at line 240 of file ns2-mobility-helper-test-suite.cc.
References ns3::Names::Clear(), and ns3::Simulator::Destroy().
SetTrace()
void Ns2MobilityHelperTest::SetTrace (std::string const & trace) inline
Set NS-2 trace to read as single large string (don't forget to add \n and quote "'s)
Definition at line 137 of file ns2-mobility-helper-test-suite.cc.
Referenced by Ns2MobilityHelperTestSuite::Ns2MobilityHelperTestSuite().
WriteTrace()
bool Ns2MobilityHelperTest::WriteTrace () inline private
Dump NS-2 trace to tmp file.
Definition at line 168 of file ns2-mobility-helper-test-suite.cc.
References NS_TEST_ASSERT_MSG_EQ_RETURNS_BOOL.
Member Data Documentation
m_nextRefPoint
size_t Ns2MobilityHelperTest::m_nextRefPoint private
Next reference point to be checked.
Definition at line 162 of file ns2-mobility-helper-test-suite.cc.
m_nodeCount
uint32_t Ns2MobilityHelperTest::m_nodeCount private
Number of nodes used in the test.
Definition at line 156 of file ns2-mobility-helper-test-suite.cc.
m_reference
std::vector<ReferencePoint> Ns2MobilityHelperTest::m_reference private
Reference mobility.
Definition at line 160 of file ns2-mobility-helper-test-suite.cc.
m_timeLimit
Time Ns2MobilityHelperTest::m_timeLimit private
Test time limit.
Definition at line 154 of file ns2-mobility-helper-test-suite.cc.
m_trace
std::string Ns2MobilityHelperTest::m_trace private
Trace as string.
Definition at line 158 of file ns2-mobility-helper-test-suite.cc.
m_traceFile
std::string Ns2MobilityHelperTest::m_traceFile private
TMP trace file name.
Definition at line 164 of file ns2-mobility-helper-test-suite.cc.
The documentation for this class was generated from the following file:
src/mobility/test/ns2-mobility-helper-test-suite.cc