ns-3: ns3::MeshPointDevice Class Reference
ns3::MeshPointDevice Class Reference
Mesh Device
Virtual net device modeling mesh point.
#include "mesh-point-device.h"
Classes
struct Statistics
statistics counters
Public Member Functions
MeshPointDevice ()
C-tor create empty (without interfaces and protocols) mesh point.
virtual ~MeshPointDevice ()
D-tor.
Interfaces
void AddInterface (Ptr< NetDevice > port)
Attach new interface to the station.
uint32_t GetNInterfaces () const
Ptr< NetDevice > GetInterface (uint32_t id) const
std::vector< Ptr< NetDevice > > GetInterfaces () const
Protocols
void SetRoutingProtocol (Ptr< MeshL2RoutingProtocol > protocol)
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Ptr< MeshL2RoutingProtocol > GetRoutingProtocol () const
Access current routing protocol.
virtual void SetIfIndex (const uint32_t index)
Register routing protocol to be used. Protocol must be already installed on this mesh point.
virtual uint32_t GetIfIndex () const
Register routing protocol to be used. Protocol must be already installed on this mesh point.
virtual Ptr< Channel > GetChannel () const
Register routing protocol to be used. Protocol must be already installed on this mesh point.
virtual Address GetAddress () const
Register routing protocol to be used. Protocol must be already installed on this mesh point.
virtual void SetAddress (Address a)
Register routing protocol to be used. Protocol must be already installed on this mesh point.
virtual bool SetMtu (const uint16_t mtu)
Register routing protocol to be used. Protocol must be already installed on this mesh point.
virtual uint16_t GetMtu () const
Register routing protocol to be used. Protocol must be already installed on this mesh point.
virtual bool IsLinkUp () const
Register routing protocol to be used. Protocol must be already installed on this mesh point.
virtual void AddLinkChangeCallback (Callback< void > callback)
Register routing protocol to be used. Protocol must be already installed on this mesh point.
virtual bool IsBroadcast () const
Register routing protocol to be used. Protocol must be already installed on this mesh point.
virtual Address GetBroadcast () const
Register routing protocol to be used. Protocol must be already installed on this mesh point.
virtual bool IsMulticast () const
Register routing protocol to be used. Protocol must be already installed on this mesh point.
virtual Address GetMulticast (Ipv4Address multicastGroup) const
Register routing protocol to be used. Protocol must be already installed on this mesh point.
virtual bool IsPointToPoint () const
Register routing protocol to be used. Protocol must be already installed on this mesh point.
virtual bool IsBridge () const
Register routing protocol to be used. Protocol must be already installed on this mesh point.
virtual bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)
Register routing protocol to be used. Protocol must be already installed on this mesh point.
virtual bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
Register routing protocol to be used. Protocol must be already installed on this mesh point.
virtual Ptr< Node > GetNode () const
Register routing protocol to be used. Protocol must be already installed on this mesh point.
virtual void SetNode (Ptr< Node > node)
Register routing protocol to be used. Protocol must be already installed on this mesh point.
virtual bool NeedsArp () const
Register routing protocol to be used. Protocol must be already installed on this mesh point.
virtual void SetReceiveCallback (NetDevice::ReceiveCallback cb)
Register routing protocol to be used. Protocol must be already installed on this mesh point.
virtual void SetPromiscReceiveCallback (NetDevice::PromiscReceiveCallback cb)
Register routing protocol to be used. Protocol must be already installed on this mesh point.
virtual bool SupportsSendFrom () const
Register routing protocol to be used. Protocol must be already installed on this mesh point.
virtual Address GetMulticast (Ipv6Address addr) const
Register routing protocol to be used. Protocol must be already installed on this mesh point.
virtual void DoDispose ()
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Public Member Functions inherited from ns3::NetDevice
virtual ~NetDevice ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::NetDevice
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Statistics
NetDevice::ReceiveCallback m_rxCallback
Receive action.
NetDevice::PromiscReceiveCallback m_promiscRxCallback
Promisc receive action.
Mac48Address m_address
Mesh point MAC address, supposed to be the address of the first added interface.
Ptr< Node > m_node
Parent node.
std::vector< Ptr< NetDevice > > m_ifaces
List of interfaces.
uint32_t m_ifIndex
If index.
uint16_t m_mtu
MTU in bytes.
Ptr< BridgeChannel > m_channel
Virtual channel for upper layers.
Ptr< MeshL2RoutingProtocol > m_routingProtocol
Current routing protocol, used mainly by GetRoutingProtocol.
Statistics m_rxStats
Counters.
Statistics m_txStats
transmit statistics
Statistics m_fwdStats
forward statistics
void Report (std::ostream &os) const
Print statistics counters.
void ResetStats ()
Reset statistics counters.
void ReceiveFromDevice (Ptr< NetDevice > device, Ptr< const Packet > packet, uint16_t protocol, Address const &source, Address const &destination, PacketType packetType)
Receive packet from interface.
void Forward (Ptr< NetDevice > incomingPort, Ptr< const Packet > packet, uint16_t protocol, const Mac48Address src, const Mac48Address dst)
Forward packet down to interfaces.
void DoSend (bool success, Ptr< Packet > packet, Mac48Address src, Mac48Address dst, uint16_t protocol, uint32_t iface)
Response callback for L2 routing protocol.
Additional Inherited Members
Public Types inherited from ns3::NetDevice
typedef void(* LinkChangeTracedCallback) (void)
TracedCallback signature for link changed event.
enum PacketType {
PACKET_HOST = 1 , NS3_PACKET_HOST = PACKET_HOST , PACKET_BROADCAST , NS3_PACKET_BROADCAST = PACKET_BROADCAST ,
PACKET_MULTICAST , NS3_PACKET_MULTICAST = PACKET_MULTICAST , PACKET_OTHERHOST , NS3_PACKET_OTHERHOST = PACKET_OTHERHOST
}
Packet types are used as they are in Linux.
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address &, const Address &, enum PacketType > PromiscReceiveCallback
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address & > ReceiveCallback
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Virtual net device modeling mesh point.
Mesh point is a virtual net device which is responsible for
Aggregating and coordinating 1..* real devices – mesh interfaces, see MeshInterfaceDevice class.
Hosting all mesh-related level 2 protocols.
One of hosted L2 protocols must inplement L2RoutingProtocol interface and is used for packets forwarding.
From the level 3 point of view MeshPointDevice is similar to BridgeNetDevice, but the packets, which going through may be changed (because L2 protocols may require their own headers or tags).
Attributes:
Todo:
Config Paths
ns3::MeshPointDevice is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::MeshPointDevice"
Attributes
Mtu: The MAC-level Maximum Transmission Unit
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 65535
Flags: construct write read
RoutingProtocol: The mesh routing protocol used by this mesh point.
Set with class: ns3::PointerValue
Underlying type: ns3::Ptr< ns3::MeshL2RoutingProtocol>
Initial value: 0x0
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 160 bytes (on a 64-bit architecture).
Definition at line 49 of file mesh-point-device.h.
Constructor & Destructor Documentation
MeshPointDevice()
ns3::MeshPointDevice::MeshPointDevice ()
C-tor create empty (without interfaces and protocols) mesh point.
Definition at line 57 of file mesh-point-device.cc.
References m_channel, and NS_LOG_FUNCTION.
~MeshPointDevice()
ns3::MeshPointDevice::~MeshPointDevice () virtual
D-tor.
Definition at line 64 of file mesh-point-device.cc.
References m_channel, m_node, m_routingProtocol, and NS_LOG_FUNCTION.
Member Function Documentation
AddInterface()
void ns3::MeshPointDevice::AddInterface (Ptr< NetDevice > port)
Attach new interface to the station.
Interface must support 48-bit MAC address and SendFrom method.
Parameters
port the port used
Attention
Only MeshPointDevice can have IP address, but not individual interfaces.
Definition at line 358 of file mesh-point-device.cc.
References ns3::Mac48Address::ConvertFrom(), ns3::WifiNetDevice::GetMac(), ns3::Mac48Address::IsMatchingType(), m_address, m_channel, m_ifaces, m_node, ns3::MakeCallback(), NS_ASSERT, NS_FATAL_ERROR, NS_LOG_FUNCTION, ReceiveFromDevice(), and ns3::Node::RegisterProtocolHandler().
AddLinkChangeCallback()
void ns3::MeshPointDevice::AddLinkChangeCallback (Callback< void > callback) virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Implements ns3::NetDevice.
Definition at line 209 of file mesh-point-device.cc.
References NS_LOG_FUNCTION, and NS_LOG_WARN.
DoDispose()
void ns3::MeshPointDevice::DoDispose (void) virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Reimplemented from ns3::Object.
Definition at line 73 of file mesh-point-device.cc.
References ns3::Object::DoDispose(), m_channel, m_ifaces, m_node, m_routingProtocol, and NS_LOG_FUNCTION.
DoSend()
void ns3::MeshPointDevice::DoSend (bool success, Ptr< Packet > packet, Mac48Address src, Mac48Address dst, uint16_t protocol, uint32_t iface) private
Response callback for L2 routing protocol.
This will be executed when routing information is ready.
Parameters
success True is route found.
packet Packet to send
src Source MAC address
dst Destination MAC address
protocol Protocol ID
iface Interface to use (ID) for send (decided by routing protocol). All interfaces will be used if outIface = 0xffffffff
Todo:
diagnose routing errors
Definition at line 418 of file mesh-point-device.cc.
References ns3::MeshPointDevice::Statistics::broadcastData, ns3::MeshPointDevice::Statistics::broadcastDataBytes, ns3::Packet::Copy(), GetInterface(), ns3::Packet::GetSize(), ns3::Mac48Address::IsBroadcast(), m_address, m_fwdStats, m_ifaces, m_txStats, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::MeshPointDevice::Statistics::unicastData, and ns3::MeshPointDevice::Statistics::unicastDataBytes.
Referenced by Forward(), Send(), and SendFrom().
Forward()
void ns3::MeshPointDevice::Forward (Ptr< NetDevice > incomingPort, Ptr< const Packet > packet, uint16_t protocol, const Mac48Address src, const Mac48Address dst) private
Forward packet down to interfaces.
Parameters
incomingPort the incoming port
packet the packet to forward
protocol the protocol
src the source MAC address
dst the destination MAC address
Definition at line 136 of file mesh-point-device.cc.
References DoSend(), m_address, m_routingProtocol, ns3::MakeCallback(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by ReceiveFromDevice().
GetAddress()
Address ns3::MeshPointDevice::GetAddress (void) const virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Implements ns3::NetDevice.
Definition at line 172 of file mesh-point-device.cc.
References m_address, and NS_LOG_FUNCTION.
GetBroadcast()
Address ns3::MeshPointDevice::GetBroadcast (void) const virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Implements ns3::NetDevice.
Definition at line 224 of file mesh-point-device.cc.
References NS_LOG_FUNCTION.
GetChannel()
Ptr< Channel > ns3::MeshPointDevice::GetChannel (void) const virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Implements ns3::NetDevice.
Definition at line 165 of file mesh-point-device.cc.
References m_channel, and NS_LOG_FUNCTION.
GetIfIndex()
uint32_t ns3::MeshPointDevice::GetIfIndex (void) const virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Implements ns3::NetDevice.
Definition at line 158 of file mesh-point-device.cc.
References m_ifIndex, and NS_LOG_FUNCTION.
GetInterface()
Ptr< NetDevice > ns3::MeshPointDevice::GetInterface (uint32_t id) const
Returns
interface device by its index (aka ID)
Parameters
id is interface id, 0 <= id < GetNInterfaces
Definition at line 339 of file mesh-point-device.cc.
References m_ifaces, sample-rng-plot::n, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
Referenced by DoSend().
GetInterfaces()
std::vector< Ptr< NetDevice > > ns3::MeshPointDevice::GetInterfaces () const
Returns
vector of interfaces
Definition at line 353 of file mesh-point-device.cc.
References m_ifaces.
GetMtu()
uint16_t ns3::MeshPointDevice::GetMtu (void) const virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Implements ns3::NetDevice.
Definition at line 195 of file mesh-point-device.cc.
References m_mtu, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetMulticast() [1/2]
Address ns3::MeshPointDevice::GetMulticast (Ipv4Address multicastGroup) const virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Implements ns3::NetDevice.
Definition at line 238 of file mesh-point-device.cc.
References ns3::Mac48Address::GetMulticast(), and NS_LOG_FUNCTION.
GetMulticast() [2/2]
Address ns3::MeshPointDevice::GetMulticast (Ipv6Address addr) const virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Implements ns3::NetDevice.
Definition at line 322 of file mesh-point-device.cc.
References ns3::Mac48Address::GetMulticast(), and NS_LOG_FUNCTION.
GetNInterfaces()
uint32_t ns3::MeshPointDevice::GetNInterfaces (void) const
Returns
number of interfaces
Definition at line 332 of file mesh-point-device.cc.
References m_ifaces, and NS_LOG_FUNCTION.
GetNode()
Ptr< Node > ns3::MeshPointDevice::GetNode (void) const virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Implements ns3::NetDevice.
Definition at line 280 of file mesh-point-device.cc.
References m_node, and NS_LOG_FUNCTION.
GetRoutingProtocol()
Ptr< MeshL2RoutingProtocol > ns3::MeshPointDevice::GetRoutingProtocol (void) const
Access current routing protocol.
Definition at line 411 of file mesh-point-device.cc.
References m_routingProtocol, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::MeshPointDevice::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 36 of file mesh-point-device.cc.
References GetMtu(), GetRoutingProtocol(), ns3::MakePointerAccessor(), ns3::MakePointerChecker(), ns3::MakeUintegerAccessor(), SetMtu(), ns3::TypeId::SetParent(), and SetRoutingProtocol().
IsBridge()
bool ns3::MeshPointDevice::IsBridge (void) const virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Implements ns3::NetDevice.
Definition at line 253 of file mesh-point-device.cc.
References NS_LOG_FUNCTION.
IsBroadcast()
bool ns3::MeshPointDevice::IsBroadcast (void) const virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Implements ns3::NetDevice.
Definition at line 217 of file mesh-point-device.cc.
References NS_LOG_FUNCTION.
IsLinkUp()
bool ns3::MeshPointDevice::IsLinkUp (void) const virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Implements ns3::NetDevice.
Definition at line 202 of file mesh-point-device.cc.
References NS_LOG_FUNCTION.
IsMulticast()
bool ns3::MeshPointDevice::IsMulticast (void) const virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Implements ns3::NetDevice.
Definition at line 231 of file mesh-point-device.cc.
References NS_LOG_FUNCTION.
IsPointToPoint()
bool ns3::MeshPointDevice::IsPointToPoint (void) const virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Implements ns3::NetDevice.
Definition at line 246 of file mesh-point-device.cc.
References NS_LOG_FUNCTION.
NeedsArp()
bool ns3::MeshPointDevice::NeedsArp (void) const virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Implements ns3::NetDevice.
Definition at line 294 of file mesh-point-device.cc.
References NS_LOG_FUNCTION.
ReceiveFromDevice()
void ns3::MeshPointDevice::ReceiveFromDevice (Ptr< NetDevice > device, Ptr< const Packet > packet, uint16_t protocol, Address const & source, Address const & destination, PacketType packetType) private
Receive packet from interface.
Parameters
device the device to receive from
packet the received packet
protocol the protocol
source the source address
destination the destination address
packetType the packet type
Definition at line 93 of file mesh-point-device.cc.
References ns3::MeshPointDevice::Statistics::broadcastData, ns3::MeshPointDevice::Statistics::broadcastDataBytes, ns3::Mac48Address::ConvertFrom(), Forward(), ns3::Mac48Address::IsGroup(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_address, m_promiscRxCallback, m_routingProtocol, m_rxCallback, m_rxStats, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::MeshPointDevice::Statistics::unicastData, and ns3::MeshPointDevice::Statistics::unicastDataBytes.
Referenced by AddInterface().
Report()
void ns3::MeshPointDevice::Report (std::ostream & os) const
Print statistics counters.
Definition at line 462 of file mesh-point-device.cc.
References ns3::MeshPointDevice::Statistics::broadcastData, ns3::MeshPointDevice::Statistics::broadcastDataBytes, m_fwdStats, m_rxStats, m_txStats, NS_LOG_FUNCTION, ns3::MeshPointDevice::Statistics::unicastData, and ns3::MeshPointDevice::Statistics::unicastDataBytes.
ResetStats()
void ns3::MeshPointDevice::ResetStats ()
Reset statistics counters.
Definition at line 482 of file mesh-point-device.cc.
References m_fwdStats, m_rxStats, m_txStats, and NS_LOG_FUNCTION.
Send()
bool ns3::MeshPointDevice::Send (Ptr< Packet > packet, const Address & dest, uint16_t protocolNumber) virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Implements ns3::NetDevice.
Definition at line 260 of file mesh-point-device.cc.
References ns3::Mac48Address::ConvertFrom(), DoSend(), m_address, m_ifIndex, m_routingProtocol, ns3::MakeCallback(), and NS_LOG_FUNCTION.
SendFrom()
bool ns3::MeshPointDevice::SendFrom (Ptr< Packet > packet, const Address & source, const Address & dest, uint16_t protocolNumber) virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Implements ns3::NetDevice.
Definition at line 269 of file mesh-point-device.cc.
References ns3::Mac48Address::ConvertFrom(), DoSend(), m_ifIndex, m_routingProtocol, ns3::MakeCallback(), and NS_LOG_FUNCTION.
SetAddress()
void ns3::MeshPointDevice::SetAddress (Address a) virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Implements ns3::NetDevice.
Definition at line 179 of file mesh-point-device.cc.
References ns3::Mac48Address::ConvertFrom(), m_address, NS_LOG_FUNCTION, and NS_LOG_WARN.
SetIfIndex()
void ns3::MeshPointDevice::SetIfIndex (const uint32_t index) virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Implements ns3::NetDevice.
Definition at line 151 of file mesh-point-device.cc.
References m_ifIndex, and NS_LOG_FUNCTION.
SetMtu()
bool ns3::MeshPointDevice::SetMtu (const uint16_t mtu) virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Implements ns3::NetDevice.
Definition at line 187 of file mesh-point-device.cc.
References m_mtu, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetNode()
void ns3::MeshPointDevice::SetNode (Ptr< Node > node) virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Implements ns3::NetDevice.
Definition at line 287 of file mesh-point-device.cc.
References m_node, and NS_LOG_FUNCTION.
SetPromiscReceiveCallback()
void ns3::MeshPointDevice::SetPromiscReceiveCallback (NetDevice::PromiscReceiveCallback cb) virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Implements ns3::NetDevice.
Definition at line 308 of file mesh-point-device.cc.
References m_promiscRxCallback, and NS_LOG_FUNCTION.
SetReceiveCallback()
void ns3::MeshPointDevice::SetReceiveCallback (NetDevice::ReceiveCallback cb) virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Implements ns3::NetDevice.
Definition at line 301 of file mesh-point-device.cc.
References m_rxCallback, and NS_LOG_FUNCTION.
SetRoutingProtocol()
void ns3::MeshPointDevice::SetRoutingProtocol (Ptr< MeshL2RoutingProtocol > protocol)
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Definition at line 402 of file mesh-point-device.cc.
References m_routingProtocol, NS_ASSERT_MSG, NS_LOG_FUNCTION, and ns3::PeekPointer().
Referenced by GetTypeId().
SupportsSendFrom()
bool ns3::MeshPointDevice::SupportsSendFrom (void) const virtual
Register routing protocol to be used. Protocol must be already installed on this mesh point.
Implements ns3::NetDevice.
Definition at line 315 of file mesh-point-device.cc.
References NS_LOG_FUNCTION.
Member Data Documentation
m_address
Mac48Address ns3::MeshPointDevice::m_address private
Mesh point MAC address, supposed to be the address of the first added interface.
Definition at line 175 of file mesh-point-device.h.
Referenced by AddInterface(), DoSend(), Forward(), GetAddress(), ReceiveFromDevice(), Send(), and SetAddress().
m_channel
Ptr<BridgeChannel> ns3::MeshPointDevice::m_channel private
Virtual channel for upper layers.
Definition at line 185 of file mesh-point-device.h.
Referenced by MeshPointDevice(), ~MeshPointDevice(), AddInterface(), DoDispose(), and GetChannel().
m_fwdStats
Statistics ns3::MeshPointDevice::m_fwdStats private
forward statistics
Definition at line 203 of file mesh-point-device.h.
Referenced by DoSend(), Report(), and ResetStats().
m_ifaces
std::vector< Ptr<NetDevice> > ns3::MeshPointDevice::m_ifaces private
List of interfaces.
Definition at line 179 of file mesh-point-device.h.
Referenced by AddInterface(), DoDispose(), DoSend(), GetInterface(), GetInterfaces(), and GetNInterfaces().
m_ifIndex
uint32_t ns3::MeshPointDevice::m_ifIndex private
If index.
Definition at line 181 of file mesh-point-device.h.
Referenced by GetIfIndex(), Send(), SendFrom(), and SetIfIndex().
m_mtu
uint16_t ns3::MeshPointDevice::m_mtu private
MTU in bytes.
Definition at line 183 of file mesh-point-device.h.
Referenced by GetMtu(), and SetMtu().
m_node
Ptr<Node> ns3::MeshPointDevice::m_node private
Parent node.
Definition at line 177 of file mesh-point-device.h.
Referenced by ~MeshPointDevice(), AddInterface(), DoDispose(), GetNode(), and SetNode().
m_promiscRxCallback
NetDevice::PromiscReceiveCallback ns3::MeshPointDevice::m_promiscRxCallback private
Promisc receive action.
Definition at line 173 of file mesh-point-device.h.
Referenced by ReceiveFromDevice(), and SetPromiscReceiveCallback().
m_routingProtocol
Ptr<MeshL2RoutingProtocol> ns3::MeshPointDevice::m_routingProtocol private
Current routing protocol, used mainly by GetRoutingProtocol.
Definition at line 187 of file mesh-point-device.h.
Referenced by ~MeshPointDevice(), DoDispose(), Forward(), GetRoutingProtocol(), ReceiveFromDevice(), Send(), SendFrom(), and SetRoutingProtocol().
m_rxCallback
NetDevice::ReceiveCallback ns3::MeshPointDevice::m_rxCallback private
Receive action.
Definition at line 171 of file mesh-point-device.h.
Referenced by ReceiveFromDevice(), and SetReceiveCallback().
m_rxStats
Statistics ns3::MeshPointDevice::m_rxStats private
Counters.
receive statistics
Definition at line 201 of file mesh-point-device.h.
Referenced by ReceiveFromDevice(), Report(), and ResetStats().
m_txStats
Statistics ns3::MeshPointDevice::m_txStats private
transmit statistics
Definition at line 202 of file mesh-point-device.h.
Referenced by DoSend(), Report(), and ResetStats().
The documentation for this class was generated from the following files:
src/mesh/model/mesh-point-device.h
src/mesh/model/mesh-point-device.cc