ns-3: ns3::Ping6Helper Class Reference
ns3::Ping6Helper Class Reference
Internet Applications » Ping6
Ping6 application helper.
#include "ping6-helper.h"
Public Member Functions
Ping6Helper ()
Constructor.
ApplicationContainer Install (NodeContainer c)
Install the application in Nodes.
void SetAttribute (std::string name, const AttributeValue &value)
Set some attributes.
void SetIfIndex (uint32_t ifIndex)
Set the out interface index.
void SetLocal (Ipv6Address ip)
Set the local IPv6 address.
void SetRemote (Ipv6Address ip)
Set the remote IPv6 address.
void SetRoutersAddress (std::vector< Ipv6Address > routers)
Set routers addresses for routing type 0.
Private Attributes
ObjectFactory m_factory
An object factory.
uint32_t m_ifIndex
Out interface index.
Ipv6Address m_localIp
The local IPv6 address.
Ipv6Address m_remoteIp
The remote IPv6 address.
std::vector< Ipv6Address > m_routers
Routers addresses.
Detailed Description
Ping6 application helper.
Definition at line 38 of file ping6-helper.h.
Constructor & Destructor Documentation
Ping6Helper()
ns3::Ping6Helper::Ping6Helper ()
Constructor.
Definition at line 29 of file ping6-helper.cc.
References ns3::Ping6::GetTypeId(), m_factory, and ns3::ObjectFactory::SetTypeId().
Member Function Documentation
Install()
ApplicationContainer ns3::Ping6Helper::Install (NodeContainer c)
Install the application in Nodes.
Parameters
c list of Nodes
Returns
application container
Definition at line 50 of file ping6-helper.cc.
References ns3::ApplicationContainer::Add(), ns3::Node::AddApplication(), ns3::NodeContainer::Begin(), ns3::ObjectFactory::Create(), ns3::NodeContainer::End(), m_factory, m_ifIndex, m_localIp, m_remoteIp, and m_routers.
SetAttribute()
void ns3::Ping6Helper::SetAttribute (std::string name, const AttributeValue & value)
Set some attributes.
Parameters
name attribute name
value attribute value
Definition at line 45 of file ping6-helper.cc.
References m_factory, and ns3::ObjectFactory::Set().
SetIfIndex()
void ns3::Ping6Helper::SetIfIndex (uint32_t ifIndex)
Set the out interface index.
This is to send to link-local (unicast or multicast) address when a node has multiple interfaces.
Parameters
ifIndex interface index
Definition at line 67 of file ping6-helper.cc.
References m_ifIndex.
SetLocal()
void ns3::Ping6Helper::SetLocal (Ipv6Address ip)
Set the local IPv6 address.
Parameters
ip local IPv6 address
Definition at line 35 of file ping6-helper.cc.
References m_localIp.
SetRemote()
void ns3::Ping6Helper::SetRemote (Ipv6Address ip)
Set the remote IPv6 address.
Parameters
ip remote IPv6 address
Definition at line 40 of file ping6-helper.cc.
References m_remoteIp.
SetRoutersAddress()
void ns3::Ping6Helper::SetRoutersAddress (std::vector< Ipv6Address > routers)
Set routers addresses for routing type 0.
Parameters
routers routers addresses
Definition at line 72 of file ping6-helper.cc.
References m_routers.
Member Data Documentation
m_factory
ObjectFactory ns3::Ping6Helper::m_factory private
An object factory.
Definition at line 91 of file ping6-helper.h.
Referenced by Ping6Helper(), Install(), and SetAttribute().
m_ifIndex
uint32_t ns3::Ping6Helper::m_ifIndex private
Out interface index.
Definition at line 106 of file ping6-helper.h.
Referenced by Install(), and SetIfIndex().
m_localIp
Ipv6Address ns3::Ping6Helper::m_localIp private
The local IPv6 address.
Definition at line 96 of file ping6-helper.h.
Referenced by Install(), and SetLocal().
m_remoteIp
Ipv6Address ns3::Ping6Helper::m_remoteIp private
The remote IPv6 address.
Definition at line 101 of file ping6-helper.h.
Referenced by Install(), and SetRemote().
m_routers
std::vector<Ipv6Address> ns3::Ping6Helper::m_routers private
Routers addresses.
Definition at line 111 of file ping6-helper.h.
Referenced by Install(), and SetRoutersAddress().
The documentation for this class was generated from the following files:
src/internet-apps/helper/ping6-helper.h
src/internet-apps/helper/ping6-helper.cc