ns-3: ns3::HeSigHeader Class Reference
ns3::HeSigHeader Class Reference
Wifi Models
Implements the IEEE 802.11ax HE-SIG PHY header (HE-SIG-A1/A2/B)
#include "wifi-phy-header.h"
Public Member Functions
HeSigHeader ()
virtual ~HeSigHeader ()
uint32_t Deserialize (Buffer::Iterator start)
uint8_t GetBssColor (void) const
Return the BSS Color field in the HE-SIG-A1.
uint16_t GetChannelWidth (void) const
Return the channel width (in MHz).
uint16_t GetGuardInterval (void) const
Return the guard interval (in nanoseconds).
TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint8_t GetMcs (void) const
Return the MCS field of HE-SIG-A1.
uint8_t GetNStreams (void) const
Return the number of streams.
uint32_t GetSerializedSize (void) const
bool IsLdpcCoding (void) const
Return whether LDPC is used or not.
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetBssColor (uint8_t bssColor)
Fill the BSS Color field of HE-SIG-A1.
void SetChannelWidth (uint16_t channelWidth)
Fill the channel width field of HE-SIG-A1 (in MHz).
void SetCoding (bool ldpc)
Fill the coding field of HE-SIG-A2.
void SetGuardIntervalAndLtfSize (uint16_t gi, uint8_t ltf)
Fill the GI + LTF size field of HE-SIG-A1.
void SetMcs (uint8_t mcs)
Fill the MCS field of HE-SIG-A1.
void SetMuFlag (bool mu)
Set the Multi-User (MU) flag.
void SetNStreams (uint8_t nStreams)
Fill the number of streams field of HE-SIG-A1.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_bandwidth
Bandwidth field.
uint8_t m_bssColor
BSS color field.
uint8_t m_coding
Coding (0 for BCC, 1 for LDPC)
uint8_t m_format
Format bit.
uint8_t m_gi_ltf_size
GI+LTF Size field.
uint8_t m_mcs
MCS field.
bool m_mu
This is used to decide whether MU SIG-B should be added or not.
uint8_t m_nsts
NSTS.
uint8_t m_spatialReuse
Spatial Reuse field.
uint8_t m_ul_dl
UL/DL bit.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implements the IEEE 802.11ax HE-SIG PHY header (HE-SIG-A1/A2/B)
Introspection did not find any typical Config paths.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 24 bytes (on a 64-bit architecture).
Definition at line 372 of file wifi-phy-header.h.
Constructor & Destructor Documentation
HeSigHeader()
ns3::HeSigHeader::HeSigHeader ()
Definition at line 711 of file wifi-phy-header.cc.
~HeSigHeader()
ns3::HeSigHeader::~HeSigHeader () virtual
Definition at line 724 of file wifi-phy-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::HeSigHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 940 of file wifi-phy-header.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_bandwidth, m_bssColor, m_coding, m_format, m_gi_ltf_size, m_mcs, m_mu, m_nsts, m_spatialReuse, m_ul_dl, ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU32(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetBssColor()
uint8_t ns3::HeSigHeader::GetBssColor (void) const
Return the BSS Color field in the HE-SIG-A1.
Returns
the BSS Color field in the HE-SIG-A1
Definition at line 797 of file wifi-phy-header.cc.
References m_bssColor.
Referenced by ns3::WifiPpdu::GetPsdu(), and ns3::WifiPpdu::GetTxVector().
GetChannelWidth()
uint16_t ns3::HeSigHeader::GetChannelWidth (void) const
Return the channel width (in MHz).
Returns
the channel width (in MHz)
Definition at line 824 of file wifi-phy-header.cc.
References m_bandwidth.
Referenced by ns3::WifiPpdu::GetTxVector(), and Print().
GetGuardInterval()
uint16_t ns3::HeSigHeader::GetGuardInterval (void) const
Return the guard interval (in nanoseconds).
Returns
the guard interval (in nanoseconds)
Definition at line 866 of file wifi-phy-header.cc.
References m_gi_ltf_size.
Referenced by ns3::WifiPpdu::GetTxVector(), and Print().
GetInstanceTypeId()
TypeId ns3::HeSigHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 740 of file wifi-phy-header.cc.
References GetTypeId().
GetMcs()
uint8_t ns3::HeSigHeader::GetMcs (void) const
Return the MCS field of HE-SIG-A1.
Returns
the MCS field of HE-SIG-A1
Definition at line 784 of file wifi-phy-header.cc.
References m_mcs.
Referenced by ns3::WifiPpdu::GetTxVector().
GetNStreams()
uint8_t ns3::HeSigHeader::GetNStreams (void) const
Return the number of streams.
Returns
the number of streams
Definition at line 891 of file wifi-phy-header.cc.
References m_nsts.
Referenced by ns3::WifiPpdu::GetTxVector().
GetSerializedSize()
uint32_t ns3::HeSigHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 758 of file wifi-phy-header.cc.
References m_mu.
GetTypeId()
TypeId ns3::HeSigHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 729 of file wifi-phy-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
IsLdpcCoding()
bool ns3::HeSigHeader::IsLdpcCoding (void) const
Return whether LDPC is used or not.
Returns
whether LDPC is used or not
Definition at line 903 of file wifi-phy-header.cc.
References m_coding.
Referenced by ns3::WifiPpdu::GetTxVector().
Print()
void ns3::HeSigHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 746 of file wifi-phy-header.cc.
References GetChannelWidth(), GetGuardInterval(), m_bssColor, m_coding, m_mcs, m_mu, and m_nsts.
Serialize()
void ns3::HeSigHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 910 of file wifi-phy-header.cc.
References m_bandwidth, m_bssColor, m_coding, m_format, m_gi_ltf_size, m_mcs, m_mu, m_nsts, m_spatialReuse, m_ul_dl, and visualizer.core::start().
SetBssColor()
void ns3::HeSigHeader::SetBssColor (uint8_t bssColor)
Fill the BSS Color field of HE-SIG-A1.
Parameters
bssColor the BSS Color value
Definition at line 790 of file wifi-phy-header.cc.
References m_bssColor, and NS_ASSERT.
Referenced by ns3::WifiPpdu::SetPhyHeaders().
SetChannelWidth()
void ns3::HeSigHeader::SetChannelWidth (uint16_t channelWidth)
Fill the channel width field of HE-SIG-A1 (in MHz).
Parameters
channelWidth the channel width (in MHz)
Definition at line 803 of file wifi-phy-header.cc.
References m_bandwidth.
Referenced by ns3::WifiPpdu::SetPhyHeaders().
SetCoding()
void ns3::HeSigHeader::SetCoding (bool ldpc)
Fill the coding field of HE-SIG-A2.
Parameters
ldpc whether LDPC is used or not
Definition at line 897 of file wifi-phy-header.cc.
References m_coding.
Referenced by ns3::WifiPpdu::SetPhyHeaders().
SetGuardIntervalAndLtfSize()
void ns3::HeSigHeader::SetGuardIntervalAndLtfSize (uint16_t gi, uint8_t ltf)
Fill the GI + LTF size field of HE-SIG-A1.
Parameters
gi the guard interval (in nanoseconds)
ltf the sequence of HE-LTF
Definition at line 845 of file wifi-phy-header.cc.
References m_gi_ltf_size.
Referenced by ns3::WifiPpdu::SetPhyHeaders().
SetMcs()
void ns3::HeSigHeader::SetMcs (uint8_t mcs)
Fill the MCS field of HE-SIG-A1.
Parameters
mcs the MCS field of HE-SIG-A1
Definition at line 777 of file wifi-phy-header.cc.
References m_mcs, and NS_ASSERT.
Referenced by ns3::WifiPpdu::SetPhyHeaders().
SetMuFlag()
void ns3::HeSigHeader::SetMuFlag (bool mu)
Set the Multi-User (MU) flag.
Parameters
mu the MU flag
Definition at line 771 of file wifi-phy-header.cc.
References m_mu.
Referenced by ns3::WifiPpdu::SetPhyHeaders().
SetNStreams()
void ns3::HeSigHeader::SetNStreams (uint8_t nStreams)
Fill the number of streams field of HE-SIG-A1.
Parameters
nStreams the number of streams
Definition at line 884 of file wifi-phy-header.cc.
References m_nsts, and NS_ASSERT.
Referenced by ns3::WifiPpdu::SetPhyHeaders().
Member Data Documentation
m_bandwidth
uint8_t ns3::HeSigHeader::m_bandwidth private
Bandwidth field.
Definition at line 477 of file wifi-phy-header.h.
Referenced by Deserialize(), GetChannelWidth(), Serialize(), and SetChannelWidth().
m_bssColor
uint8_t ns3::HeSigHeader::m_bssColor private
BSS color field.
Definition at line 473 of file wifi-phy-header.h.
Referenced by Deserialize(), GetBssColor(), Print(), Serialize(), and SetBssColor().
m_coding
uint8_t ns3::HeSigHeader::m_coding private
Coding (0 for BCC, 1 for LDPC)
Definition at line 482 of file wifi-phy-header.h.
Referenced by Deserialize(), IsLdpcCoding(), Print(), Serialize(), and SetCoding().
m_format
uint8_t ns3::HeSigHeader::m_format private
Format bit.
Definition at line 472 of file wifi-phy-header.h.
Referenced by Deserialize(), and Serialize().
m_gi_ltf_size
uint8_t ns3::HeSigHeader::m_gi_ltf_size private
GI+LTF Size field.
Definition at line 478 of file wifi-phy-header.h.
Referenced by Deserialize(), GetGuardInterval(), Serialize(), and SetGuardIntervalAndLtfSize().
m_mcs
uint8_t ns3::HeSigHeader::m_mcs private
MCS field.
Definition at line 475 of file wifi-phy-header.h.
Referenced by Deserialize(), GetMcs(), Print(), Serialize(), and SetMcs().
m_mu
bool ns3::HeSigHeader::m_mu private
This is used to decide whether MU SIG-B should be added or not.
Definition at line 485 of file wifi-phy-header.h.
Referenced by Deserialize(), GetSerializedSize(), Print(), Serialize(), and SetMuFlag().
m_nsts
uint8_t ns3::HeSigHeader::m_nsts private
NSTS.
Definition at line 479 of file wifi-phy-header.h.
Referenced by Deserialize(), GetNStreams(), Print(), Serialize(), and SetNStreams().
m_spatialReuse
uint8_t ns3::HeSigHeader::m_spatialReuse private
Spatial Reuse field.
Definition at line 476 of file wifi-phy-header.h.
Referenced by Deserialize(), and Serialize().
m_ul_dl
uint8_t ns3::HeSigHeader::m_ul_dl private
UL/DL bit.
Definition at line 474 of file wifi-phy-header.h.
Referenced by Deserialize(), and Serialize().
The documentation for this class was generated from the following files:
src/wifi/model/wifi-phy-header.h
src/wifi/model/wifi-phy-header.cc