ns-3: ns3::LteEnbRrcProtocolIdeal Class Reference
ns3::LteEnbRrcProtocolIdeal Class Reference
Models the transmission of RRC messages from the UE to the eNB in an ideal fashion, without errors and without consuming any radio resources.
#include "lte-rrc-protocol-ideal.h"
Public Member Functions
LteEnbRrcProtocolIdeal ()
virtual ~LteEnbRrcProtocolIdeal ()
virtual void DoDispose (void)
Destructor implementation.
LteEnbRrcSapUser * GetLteEnbRrcSapUser ()
Get LTE ENB RRC SAP user function.
LteUeRrcSapProvider * GetUeRrcSapProvider (uint16_t rnti)
Get LTE UE RRC SAP provider function.
void SetCellId (uint16_t cellId)
Set the cell ID function.
void SetLteEnbRrcSapProvider (LteEnbRrcSapProvider *p)
Set LTE ENB RRC SAP provider function.
void SetUeRrcSapProvider (uint16_t rnti, LteUeRrcSapProvider *p)
Set UE RRC SAP provider function.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
LteRrcSap::RrcConnectionReconfiguration DoDecodeHandoverCommand (Ptr< Packet > p)
Decode handover command function.
LteRrcSap::HandoverPreparationInfo DoDecodeHandoverPreparationInformation (Ptr< Packet > p)
Encode handover preparation information function.
Ptr< Packet > DoEncodeHandoverCommand (LteRrcSap::RrcConnectionReconfiguration msg)
Encode handover command function.
Ptr< Packet > DoEncodeHandoverPreparationInformation (LteRrcSap::HandoverPreparationInfo msg)
Encode handover preparation information function.
void DoRemoveUe (uint16_t rnti)
Remove UE function.
void DoSendRrcConnectionReconfiguration (uint16_t rnti, LteRrcSap::RrcConnectionReconfiguration msg)
Send RRC connection reconfiguration function.
void DoSendRrcConnectionReestablishment (uint16_t rnti, LteRrcSap::RrcConnectionReestablishment msg)
Send RRC connection reestablishment function.
void DoSendRrcConnectionReestablishmentReject (uint16_t rnti, LteRrcSap::RrcConnectionReestablishmentReject msg)
Send RRC connection reestablishment reject function.
void DoSendRrcConnectionReject (uint16_t rnti, LteRrcSap::RrcConnectionReject msg)
Send RRC connection reject function.
void DoSendRrcConnectionRelease (uint16_t rnti, LteRrcSap::RrcConnectionRelease msg)
Send RRC connection release function.
void DoSendRrcConnectionSetup (uint16_t rnti, LteRrcSap::RrcConnectionSetup msg)
Send RRC connection setup function.
void DoSendSystemInformation (uint16_t cellId, LteRrcSap::SystemInformation msg)
Send system information function.
void DoSetupUe (uint16_t rnti, LteEnbRrcSapUser::SetupUeParameters params)
Setup UE function.
void SendSystemInformation (LteRrcSap::SystemInformation msg)
Send system information function.
Private Attributes
uint16_t m_cellId
the cell ID
LteEnbRrcSapProvider * m_enbRrcSapProvider
the ENB RRC SAP provider
std::map< uint16_t, LteUeRrcSapProvider * > m_enbRrcSapProviderMap
the LTE UE RRC SAP provider
LteEnbRrcSapUser * m_enbRrcSapUser
the ENB RRC SAP user
uint16_t m_rnti
the RNTI
Friends
class MemberLteEnbRrcSapUser< LteEnbRrcProtocolIdeal >
allow MemberLteEnbRrcSapUser<LteEnbRrcProtocolIdeal> class friend access
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Models the transmission of RRC messages from the UE to the eNB in an ideal fashion, without errors and without consuming any radio resources.
Introspection did not find any typical Config paths.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 72 bytes (on a 64-bit architecture).
Definition at line 162 of file lte-rrc-protocol-ideal.h.
Constructor & Destructor Documentation
LteEnbRrcProtocolIdeal()
ns3::LteEnbRrcProtocolIdeal::LteEnbRrcProtocolIdeal ()
Definition at line 240 of file lte-rrc-protocol-ideal.cc.
References m_enbRrcSapUser, MemberLteEnbRrcSapUser< LteEnbRrcProtocolIdeal >, and NS_LOG_FUNCTION.
~LteEnbRrcProtocolIdeal()
ns3::LteEnbRrcProtocolIdeal::~LteEnbRrcProtocolIdeal () virtual
Definition at line 247 of file lte-rrc-protocol-ideal.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDecodeHandoverCommand()
LteRrcSap::RrcConnectionReconfiguration ns3::LteEnbRrcProtocolIdeal::DoDecodeHandoverCommand (Ptr< Packet > p) private
Decode handover command function.
Parameters
p the packet
Returns
LteRrcSap::RrcConnectionReconfiguration
Definition at line 680 of file lte-rrc-protocol-ideal.cc.
References ns3::g_handoverCommandMsgMap, ns3::IdealHandoverCommandHeader::GetMsgId(), NS_ASSERT_MSG, NS_LOG_INFO, and ns3::Packet::RemoveHeader().
DoDecodeHandoverPreparationInformation()
LteRrcSap::HandoverPreparationInfo ns3::LteEnbRrcProtocolIdeal::DoDecodeHandoverPreparationInformation (Ptr< Packet > p) private
Encode handover preparation information function.
Parameters
p the packet
Returns
LteRrcSap::HandoverPreparationInfo
Definition at line 559 of file lte-rrc-protocol-ideal.cc.
References ns3::g_handoverPreparationInfoMsgMap, ns3::IdealHandoverPreparationInfoHeader::GetMsgId(), NS_ASSERT_MSG, NS_LOG_INFO, and ns3::Packet::RemoveHeader().
DoDispose()
void ns3::LteEnbRrcProtocolIdeal::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 253 of file lte-rrc-protocol-ideal.cc.
References m_enbRrcSapUser, and NS_LOG_FUNCTION.
DoEncodeHandoverCommand()
Ptr< Packet > ns3::LteEnbRrcProtocolIdeal::DoEncodeHandoverCommand (LteRrcSap::RrcConnectionReconfiguration msg) private
Encode handover command function.
Parameters
msg LteRrcSap::RrcConnectionReconfiguration
Returns
rnti the RNTI
Definition at line 666 of file lte-rrc-protocol-ideal.cc.
References ns3::Packet::AddHeader(), ns3::g_handoverCommandMsgIdCounter, ns3::g_handoverCommandMsgMap, NS_ASSERT_MSG, NS_LOG_INFO, and ns3::IdealHandoverCommandHeader::SetMsgId().
DoEncodeHandoverPreparationInformation()
Ptr< Packet > ns3::LteEnbRrcProtocolIdeal::DoEncodeHandoverPreparationInformation (LteRrcSap::HandoverPreparationInfo msg) private
Encode handover preparation information function.
Parameters
msg LteRrcSap::HandoverPreparationInfo
Returns
the packet
Definition at line 545 of file lte-rrc-protocol-ideal.cc.
References ns3::Packet::AddHeader(), ns3::g_handoverPreparationInfoMsgIdCounter, ns3::g_handoverPreparationInfoMsgMap, NS_ASSERT_MSG, NS_LOG_INFO, and ns3::IdealHandoverPreparationInfoHeader::SetMsgId().
DoRemoveUe()
void ns3::LteEnbRrcProtocolIdeal::DoRemoveUe (uint16_t rnti) private
Remove UE function.
Parameters
rnti the RNTI
Definition at line 350 of file lte-rrc-protocol-ideal.cc.
References m_enbRrcSapProviderMap, and NS_LOG_FUNCTION.
DoSendRrcConnectionReconfiguration()
void ns3::LteEnbRrcProtocolIdeal::DoSendRrcConnectionReconfiguration (uint16_t rnti, LteRrcSap::RrcConnectionReconfiguration msg) private
Send RRC connection reconfiguration function.
Parameters
rnti the RNTI
msg LteRrcSap::RrcConnectionReconfiguration
Definition at line 397 of file lte-rrc-protocol-ideal.cc.
References GetUeRrcSapProvider(), ns3::LteUeRrcSapProvider::RecvRrcConnectionReconfiguration(), ns3::RRC_IDEAL_MSG_DELAY, and ns3::Simulator::Schedule().
DoSendRrcConnectionReestablishment()
void ns3::LteEnbRrcProtocolIdeal::DoSendRrcConnectionReestablishment (uint16_t rnti, LteRrcSap::RrcConnectionReestablishment msg) private
Send RRC connection reestablishment function.
Parameters
rnti the RNTI
msg LteRrcSap::RrcConnectionReestablishment
Definition at line 406 of file lte-rrc-protocol-ideal.cc.
References GetUeRrcSapProvider(), ns3::LteUeRrcSapProvider::RecvRrcConnectionReestablishment(), ns3::RRC_IDEAL_MSG_DELAY, and ns3::Simulator::Schedule().
DoSendRrcConnectionReestablishmentReject()
void ns3::LteEnbRrcProtocolIdeal::DoSendRrcConnectionReestablishmentReject (uint16_t rnti, LteRrcSap::RrcConnectionReestablishmentReject msg) private
Send RRC connection reestablishment reject function.
Parameters
rnti the RNTI
msg LteRrcSap::RrcConnectionReestablishmentReject
Definition at line 415 of file lte-rrc-protocol-ideal.cc.
References GetUeRrcSapProvider(), ns3::LteUeRrcSapProvider::RecvRrcConnectionReestablishmentReject(), ns3::RRC_IDEAL_MSG_DELAY, and ns3::Simulator::Schedule().
DoSendRrcConnectionReject()
void ns3::LteEnbRrcProtocolIdeal::DoSendRrcConnectionReject (uint16_t rnti, LteRrcSap::RrcConnectionReject msg) private
Send RRC connection reject function.
Parameters
rnti the RNTI
msg LteRrcSap::RrcConnectionReject
Definition at line 433 of file lte-rrc-protocol-ideal.cc.
References GetUeRrcSapProvider(), ns3::LteUeRrcSapProvider::RecvRrcConnectionReject(), ns3::RRC_IDEAL_MSG_DELAY, and ns3::Simulator::Schedule().
DoSendRrcConnectionRelease()
void ns3::LteEnbRrcProtocolIdeal::DoSendRrcConnectionRelease (uint16_t rnti, LteRrcSap::RrcConnectionRelease msg) private
Send RRC connection release function.
Parameters
rnti the RNTI
msg LteRrcSap::RrcConnectionRelease
Definition at line 424 of file lte-rrc-protocol-ideal.cc.
References GetUeRrcSapProvider(), ns3::LteUeRrcSapProvider::RecvRrcConnectionRelease(), ns3::RRC_IDEAL_MSG_DELAY, and ns3::Simulator::Schedule().
DoSendRrcConnectionSetup()
void ns3::LteEnbRrcProtocolIdeal::DoSendRrcConnectionSetup (uint16_t rnti, LteRrcSap::RrcConnectionSetup msg) private
Send RRC connection setup function.
Parameters
rnti the RNTI
msg LteRrcSap::RrcConnectionSetup
Definition at line 388 of file lte-rrc-protocol-ideal.cc.
References GetUeRrcSapProvider(), ns3::LteUeRrcSapProvider::RecvRrcConnectionSetup(), ns3::RRC_IDEAL_MSG_DELAY, and ns3::Simulator::Schedule().
DoSendSystemInformation()
void ns3::LteEnbRrcProtocolIdeal::DoSendSystemInformation (uint16_t cellId, LteRrcSap::SystemInformation msg) private
Send system information function.
Parameters
cellId cell ID
msg LteRrcSap::SystemInformation
Definition at line 357 of file lte-rrc-protocol-ideal.cc.
References ns3::NodeList::Begin(), ns3::NodeList::End(), ns3::Node::GetDevice(), ns3::Node::GetNDevices(), NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::LteUeRrcSapProvider::RecvSystemInformation(), ns3::RRC_IDEAL_MSG_DELAY, and ns3::Simulator::Schedule().
DoSetupUe()
void ns3::LteEnbRrcProtocolIdeal::DoSetupUe (uint16_t rnti, LteEnbRrcSapUser::SetupUeParameters params) private
Setup UE function.
Parameters
rnti the RNTI
params LteEnbRrcSapUser::SetupUeParameters
Definition at line 308 of file lte-rrc-protocol-ideal.cc.
References m_enbRrcSapProviderMap, and NS_LOG_FUNCTION.
GetLteEnbRrcSapUser()
LteEnbRrcSapUser * ns3::LteEnbRrcProtocolIdeal::GetLteEnbRrcSapUser ()
Get LTE ENB RRC SAP user function.
Returns
LTE ENB RRC SAP user
Definition at line 277 of file lte-rrc-protocol-ideal.cc.
References m_enbRrcSapUser.
GetTypeId()
TypeId ns3::LteEnbRrcProtocolIdeal::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 260 of file lte-rrc-protocol-ideal.cc.
References ns3::TypeId::SetParent().
GetUeRrcSapProvider()
LteUeRrcSapProvider * ns3::LteEnbRrcProtocolIdeal::GetUeRrcSapProvider (uint16_t rnti)
Get LTE UE RRC SAP provider function.
Parameters
rnti the RNTI
Returns
LTE UE RRC SAP provider
Definition at line 289 of file lte-rrc-protocol-ideal.cc.
References m_enbRrcSapProviderMap, and NS_ASSERT_MSG.
Referenced by DoSendRrcConnectionReconfiguration(), DoSendRrcConnectionReestablishment(), DoSendRrcConnectionReestablishmentReject(), DoSendRrcConnectionReject(), DoSendRrcConnectionRelease(), and DoSendRrcConnectionSetup().
SendSystemInformation()
void ns3::LteEnbRrcProtocolIdeal::SendSystemInformation (LteRrcSap::SystemInformation msg) private
Send system information function.
Parameters
msg LteRrcSap::SystemInformation
SetCellId()
void ns3::LteEnbRrcProtocolIdeal::SetCellId (uint16_t cellId)
Set the cell ID function.
Parameters
cellId the cell ID
Definition at line 283 of file lte-rrc-protocol-ideal.cc.
References m_cellId.
SetLteEnbRrcSapProvider()
void ns3::LteEnbRrcProtocolIdeal::SetLteEnbRrcSapProvider (LteEnbRrcSapProvider * p)
Set LTE ENB RRC SAP provider function.
Parameters
p the LTE ENB RRC SAP provider
Definition at line 271 of file lte-rrc-protocol-ideal.cc.
References m_enbRrcSapProvider.
SetUeRrcSapProvider()
void ns3::LteEnbRrcProtocolIdeal::SetUeRrcSapProvider (uint16_t rnti, LteUeRrcSapProvider * p)
Set UE RRC SAP provider function.
Parameters
rnti the RNTI
p the UE RRC SAP provider
Definition at line 298 of file lte-rrc-protocol-ideal.cc.
References m_cellId, m_enbRrcSapProviderMap, and NS_ASSERT_MSG.
Friends And Related Function Documentation
MemberLteEnbRrcSapUser< LteEnbRrcProtocolIdeal >
friend class MemberLteEnbRrcSapUser< LteEnbRrcProtocolIdeal > friend
allow MemberLteEnbRrcSapUser<LteEnbRrcProtocolIdeal> class friend access
Definition at line 151 of file lte-rrc-protocol-ideal.h.
Referenced by LteEnbRrcProtocolIdeal().
Member Data Documentation
m_cellId
uint16_t ns3::LteEnbRrcProtocolIdeal::m_cellId private
the cell ID
Definition at line 317 of file lte-rrc-protocol-ideal.h.
Referenced by SetCellId(), and SetUeRrcSapProvider().
m_enbRrcSapProvider
LteEnbRrcSapProvider* ns3::LteEnbRrcProtocolIdeal::m_enbRrcSapProvider private
the ENB RRC SAP provider
Definition at line 318 of file lte-rrc-protocol-ideal.h.
Referenced by SetLteEnbRrcSapProvider().
m_enbRrcSapProviderMap
std::map<uint16_t, LteUeRrcSapProvider*> ns3::LteEnbRrcProtocolIdeal::m_enbRrcSapProviderMap private
the LTE UE RRC SAP provider
Definition at line 320 of file lte-rrc-protocol-ideal.h.
Referenced by DoRemoveUe(), DoSetupUe(), GetUeRrcSapProvider(), and SetUeRrcSapProvider().
m_enbRrcSapUser
LteEnbRrcSapUser* ns3::LteEnbRrcProtocolIdeal::m_enbRrcSapUser private
the ENB RRC SAP user
Definition at line 319 of file lte-rrc-protocol-ideal.h.
Referenced by LteEnbRrcProtocolIdeal(), DoDispose(), and GetLteEnbRrcSapUser().
m_rnti
uint16_t ns3::LteEnbRrcProtocolIdeal::m_rnti private
the RNTI
Definition at line 316 of file lte-rrc-protocol-ideal.h.
The documentation for this class was generated from the following files:
src/lte/model/lte-rrc-protocol-ideal.h
src/lte/model/lte-rrc-protocol-ideal.cc