ns-3: ns3::HeConfiguration Class Reference
ns3::HeConfiguration Class Reference
Wifi Models
HE configuration.
#include "he-configuration.h"
Public Member Functions
HeConfiguration ()
Time GetGuardInterval (void) const
uint16_t GetMpduBufferSize (void) const
void SetGuardInterval (Time guardInterval)
void SetMpduBufferSize (uint16_t size)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_bssColor
BSS color.
Time m_guardInterval
Supported HE guard interval.
uint16_t m_mpduBufferSize
MPDU buffer size.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
HE configuration.
This object stores HE configuration information, for use in modifying AP or STA behavior and for constructing HE-related information elements.
Config Paths
ns3::HeConfiguration is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/HeConfiguration"
Attributes
GuardInterval: Specify the shortest guard interval duration that can be used for HE transmissions.Possible values are 800ns, 1600ns or 3200ns.
Set with class: ns3::TimeValue
Underlying type: Time +800ns:+3200ns
Initial value: +3200ns
Flags: construct write read
BssColor: The BSS color
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Initial value: 0
Flags: construct write read
MpduBufferSize: The MPDU buffer size for receiving A-MPDUs
Set with class: ns3::UintegerValue
Underlying type: uint16_t 64:256
Initial value: 64
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 48 bytes (on a 64-bit architecture).
Definition at line 36 of file he-configuration.h.
Constructor & Destructor Documentation
HeConfiguration()
ns3::HeConfiguration::HeConfiguration ()
Definition at line 30 of file he-configuration.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
GetGuardInterval()
Time ns3::HeConfiguration::GetGuardInterval (void) const
Returns
the supported HE guard interval
Definition at line 73 of file he-configuration.cc.
References m_guardInterval.
Referenced by GetTypeId().
GetMpduBufferSize()
uint16_t ns3::HeConfiguration::GetMpduBufferSize (void) const
Returns
the MPDU buffer size to receive A-MPDUs
Definition at line 86 of file he-configuration.cc.
References m_mpduBufferSize.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::HeConfiguration::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 36 of file he-configuration.cc.
References GetGuardInterval(), GetMpduBufferSize(), m_bssColor, ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeUintegerAccessor(), ns3::NanoSeconds(), SetGuardInterval(), SetMpduBufferSize(), and ns3::TypeId::SetParent().
SetGuardInterval()
void ns3::HeConfiguration::SetGuardInterval (Time guardInterval)
Parameters
guardInterval the supported HE guard interval
Definition at line 65 of file he-configuration.cc.
References m_guardInterval, ns3::NanoSeconds(), NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetMpduBufferSize()
void ns3::HeConfiguration::SetMpduBufferSize (uint16_t size)
Parameters
size the MPDU buffer size to receive A-MPDUs
Definition at line 79 of file he-configuration.cc.
References m_mpduBufferSize, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
Member Data Documentation
m_bssColor
uint8_t ns3::HeConfiguration::m_bssColor private
BSS color.
Definition at line 67 of file he-configuration.h.
Referenced by GetTypeId().
m_guardInterval
Time ns3::HeConfiguration::m_guardInterval private
Supported HE guard interval.
Definition at line 66 of file he-configuration.h.
Referenced by GetGuardInterval(), and SetGuardInterval().
m_mpduBufferSize
uint16_t ns3::HeConfiguration::m_mpduBufferSize private
MPDU buffer size.
Definition at line 68 of file he-configuration.h.
Referenced by GetMpduBufferSize(), and SetMpduBufferSize().
The documentation for this class was generated from the following files:
src/wifi/model/he-configuration.h
src/wifi/model/he-configuration.cc