ns-3: ns3::DpdkNetDevice Class Reference
ns3::DpdkNetDevice Class Reference
File Descriptor Network Device
a NetDevice to read/write network traffic from/into a Dpdk enabled port.
#include "dpdk-net-device.h"
Public Member Functions
DpdkNetDevice ()
Constructor for the DpdkNetDevice.
~DpdkNetDevice ()
Destructor for the DpdkNetDevice.
virtual uint8_t * AllocateBuffer (size_t len)
Allocate packet buffer.
void CheckAllPortsLinkStatus (void)
Check the link status of all ports in up to 9s and print them finally.
virtual void FreeBuffer (uint8_t *buf)
Free the given packet buffer.
void HandleRx ()
Receive packets in burst from the nic to the rx_buffer.
void HandleTx ()
Transmit packets in burst from the tx_buffer to the nic.
void InitDpdk (int argc, char **argv, std::string dpdkDriver)
Initialize Dpdk.
bool IsLinkUp (void) const
Check the status of the link.
void SetDeviceName (std::string deviceName)
Set device name.
Public Member Functions inherited from ns3::FdNetDevice
FdNetDevice ()
Constructor for the FdNetDevice.
virtual ~FdNetDevice ()
Destructor for the FdNetDevice.
virtual void AddLinkChangeCallback (Callback< void > callback)
virtual Address GetAddress (void) const
virtual Address GetBroadcast (void) const
virtual Ptr< Channel > GetChannel (void) const
FdNetDevice::EncapsulationMode GetEncapsulationMode (void) const
Get the link layer encapsulation mode of this device.
virtual uint32_t GetIfIndex (void) const
virtual uint16_t GetMtu (void) const
virtual Address GetMulticast (Ipv4Address multicastGroup) const
Make and return a MAC multicast address using the provided multicast group.
virtual Address GetMulticast (Ipv6Address addr) const
Get the MAC multicast address corresponding to the IPv6 address provided.
virtual Ptr< Node > GetNode (void) const
virtual bool IsBridge (void) const
Return true if the net device is acting as a bridge.
virtual bool IsBroadcast (void) const
virtual bool IsMulticast (void) const
virtual bool IsPointToPoint (void) const
Return true if the net device is on a point-to-point link.
virtual bool NeedsArp (void) const
virtual bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)
virtual bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
virtual void SetAddress (Address address)
Set the address of this interface.
void SetEncapsulationMode (FdNetDevice::EncapsulationMode mode)
Set the link layer encapsulation mode of this device.
void SetFileDescriptor (int fd)
Set the associated file descriptor.
virtual void SetIfIndex (const uint32_t index)
virtual void SetIsBroadcast (bool broadcast)
Set if the NetDevice is able to send Broadcast messages.
virtual void SetIsMulticast (bool multicast)
Set if the NetDevice is able to send Multicast messages.
virtual bool SetMtu (const uint16_t mtu)
virtual void SetNode (Ptr< Node > node)
virtual void SetPromiscReceiveCallback (NetDevice::PromiscReceiveCallback cb)
virtual void SetReceiveCallback (NetDevice::ReceiveCallback cb)
void Start (Time tStart)
Set a start time for the device.
void Stop (Time tStop)
Set a stop time for the device.
virtual bool SupportsSendFrom () const
Public Member Functions inherited from ns3::NetDevice
virtual ~NetDevice ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
static int LaunchCore (void *arg)
A function to handle rx & tx operations.
static void SignalHandler (int signum)
A signal handler for SIGINT and SIGTERM signals.
Static Public Member Functions inherited from ns3::FdNetDevice
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::NetDevice
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
ssize_t Write (uint8_t *buffer, size_t length)
Write packet data to device.
Protected Member Functions inherited from ns3::FdNetDevice
virtual void DoDispose (void)
Destructor implementation.
int GetFileDescriptor (void) const
Get the associated file descriptor.
void ReceiveCallback (uint8_t *buf, ssize_t len)
Callback to invoke when a new frame is received.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes
std::string m_deviceName
The device name;.
uint16_t m_portId
The port number of the device to be used.
Protected Attributes inherited from ns3::FdNetDevice
std::queue< std::pair< uint8_t *, ssize_t > > m_pendingQueue
Number of packets that were received and scheduled for read but not yet read.
SystemMutex m_pendingReadMutex
Mutex to increase pending read counter.
Private Member Functions
void DoFinishStoppingDevice (void)
Complete additional actions, if any, to tear down the device.
Private Attributes
uint32_t m_maxRxPktBurst
Size of Rx burst.
uint32_t m_maxTxPktBurst
Size of Tx burst.
struct rte_mempool * m_mempool
Packet memory pool.
uint32_t m_mempoolCacheSize
Mempool cache size.
uint16_t m_nbRxDesc
Number of Rx descriptors.
uint16_t m_nbTxDesc
Number of Tx descriptors.
struct rte_eth_dev_tx_buffer * m_rxBuffer
Buffer to handle burst reception.
struct rte_eth_dev_tx_buffer * m_txBuffer
Buffer to handle burst transmission.
EventId m_txEvent
Event for stale packet transmission.
Time m_txTimeout
The time to wait before transmitting burst from Tx buffer.
Static Private Attributes
static volatile bool m_forceQuit = false
Condition variable for Dpdk to stop.
Additional Inherited Members
Public Types inherited from ns3::FdNetDevice
enum EncapsulationMode { DIX , LLC , DIXPI }
Enumeration of the types of frames supported in the class.
Public Types inherited from ns3::NetDevice
typedef void(* LinkChangeTracedCallback) (void)
TracedCallback signature for link changed event.
enum PacketType {
PACKET_HOST = 1 , NS3_PACKET_HOST = PACKET_HOST , PACKET_BROADCAST , NS3_PACKET_BROADCAST = PACKET_BROADCAST ,
PACKET_MULTICAST , NS3_PACKET_MULTICAST = PACKET_MULTICAST , PACKET_OTHERHOST , NS3_PACKET_OTHERHOST = PACKET_OTHERHOST
}
Packet types are used as they are in Linux.
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address &, const Address &, enum PacketType > PromiscReceiveCallback
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address & > ReceiveCallback
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
a NetDevice to read/write network traffic from/into a Dpdk enabled port.
A DpdkNetDevice object will read and write frames/packets from/to a Dpdk enabled port.
Definition at line 48 of file dpdk-net-device.h.
Constructor & Destructor Documentation
DpdkNetDevice()
ns3::DpdkNetDevice::DpdkNetDevice ()
Constructor for the DpdkNetDevice.
Definition at line 98 of file dpdk-net-device.cc.
References NS_LOG_FUNCTION.
~DpdkNetDevice()
ns3::DpdkNetDevice::~DpdkNetDevice ()
Destructor for the DpdkNetDevice.
Definition at line 104 of file dpdk-net-device.cc.
References ns3::Simulator::Cancel(), m_forceQuit, m_portId, m_txEvent, and NS_LOG_FUNCTION.
Member Function Documentation
AllocateBuffer()
uint8_t * ns3::DpdkNetDevice::AllocateBuffer (size_t len) virtual
Allocate packet buffer.
Reimplemented from ns3::FdNetDevice.
Definition at line 419 of file dpdk-net-device.cc.
References m_mempool.
CheckAllPortsLinkStatus()
void ns3::DpdkNetDevice::CheckAllPortsLinkStatus (void)
Check the link status of all ports in up to 9s and print them finally.
Definition at line 124 of file dpdk-net-device.cc.
References CHECK_INTERVAL, m_forceQuit, m_portId, MAX_CHECK_TIME, and NS_LOG_FUNCTION.
Referenced by InitDpdk().
DoFinishStoppingDevice()
void ns3::DpdkNetDevice::DoFinishStoppingDevice (void) private virtual
Complete additional actions, if any, to tear down the device.
Reimplemented from ns3::FdNetDevice.
Definition at line 477 of file dpdk-net-device.cc.
References FreeBuffer(), ns3::FdNetDevice::m_pendingQueue, and ns3::FdNetDevice::m_pendingReadMutex.
FreeBuffer()
void ns3::DpdkNetDevice::FreeBuffer (uint8_t * buf) virtual
Free the given packet buffer.
Reimplemented from ns3::FdNetDevice.
Definition at line 431 of file dpdk-net-device.cc.
Referenced by DoFinishStoppingDevice().
GetTypeId()
TypeId ns3::DpdkNetDevice::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 58 of file dpdk-net-device.cc.
References m_maxRxPktBurst, m_maxTxPktBurst, m_mempoolCacheSize, m_nbRxDesc, m_nbTxDesc, m_txTimeout, ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeUintegerAccessor(), ns3::MicroSeconds(), and ns3::TypeId::SetParent().
HandleRx()
void ns3::DpdkNetDevice::HandleRx ()
Receive packets in burst from the nic to the rx_buffer.
Definition at line 207 of file dpdk-net-device.cc.
References m_maxRxPktBurst, m_portId, and m_rxBuffer.
Referenced by LaunchCore().
HandleTx()
void ns3::DpdkNetDevice::HandleTx ()
Transmit packets in burst from the tx_buffer to the nic.
Definition at line 200 of file dpdk-net-device.cc.
References m_portId, and m_txBuffer.
Referenced by Write().
InitDpdk()
void ns3::DpdkNetDevice::InitDpdk (int argc, char ** argv, std::string dpdkDriver)
Initialize Dpdk.
Initializes EAL.
Parameters
argc Dpdk EAL args count.
argv Dpdk EAL args list.
dpdkDriver Dpdk Driver to bind NIC to.
Definition at line 260 of file dpdk-net-device.cc.
References CheckAllPortsLinkStatus(), LaunchCore(), m_deviceName, m_forceQuit, m_maxRxPktBurst, m_maxTxPktBurst, m_mempool, m_mempoolCacheSize, m_nbRxDesc, m_nbTxDesc, m_portId, m_rxBuffer, m_txBuffer, NS_LOG_FUNCTION, NS_LOG_INFO, and SignalHandler().
IsLinkUp()
bool ns3::DpdkNetDevice::IsLinkUp (void) const virtual
Check the status of the link.
Returns
Status of the link - up/down as true/false.
Reimplemented from ns3::FdNetDevice.
Definition at line 253 of file dpdk-net-device.cc.
LaunchCore()
int ns3::DpdkNetDevice::LaunchCore (void * arg) static
A function to handle rx & tx operations.
Definition at line 234 of file dpdk-net-device.cc.
References HandleRx(), and m_forceQuit.
Referenced by InitDpdk().
SetDeviceName()
void ns3::DpdkNetDevice::SetDeviceName (std::string deviceName)
Set device name.
Parameters
deviceName The device name.
Definition at line 116 of file dpdk-net-device.cc.
References m_deviceName, and NS_LOG_FUNCTION.
SignalHandler()
void ns3::DpdkNetDevice::SignalHandler (int signum) static
A signal handler for SIGINT and SIGTERM signals.
Parameters
signum The signal number.
Definition at line 189 of file dpdk-net-device.cc.
References m_forceQuit.
Referenced by InitDpdk().
Write()
ssize_t ns3::DpdkNetDevice::Write (uint8_t * buffer, size_t length) protected virtual
Write packet data to device.
Parameters
buffer The data.
length The data length.
Returns
The size of data written.
Reimplemented from ns3::FdNetDevice.
Definition at line 447 of file dpdk-net-device.cc.
References ns3::Simulator::Cancel(), HandleTx(), m_maxTxPktBurst, m_portId, m_txBuffer, m_txEvent, m_txTimeout, NS_LOG_ERROR, and ns3::Simulator::Schedule().
Member Data Documentation
m_deviceName
std::string ns3::DpdkNetDevice::m_deviceName protected
The device name;.
Definition at line 145 of file dpdk-net-device.h.
Referenced by InitDpdk(), and SetDeviceName().
m_forceQuit
volatile bool ns3::DpdkNetDevice::m_forceQuit = false static private
Condition variable for Dpdk to stop.
Definition at line 152 of file dpdk-net-device.h.
Referenced by ~DpdkNetDevice(), CheckAllPortsLinkStatus(), InitDpdk(), LaunchCore(), and SignalHandler().
m_maxRxPktBurst
uint32_t ns3::DpdkNetDevice::m_maxRxPktBurst private
Size of Rx burst.
Definition at line 182 of file dpdk-net-device.h.
Referenced by GetTypeId(), HandleRx(), and InitDpdk().
m_maxTxPktBurst
uint32_t ns3::DpdkNetDevice::m_maxTxPktBurst private
Size of Tx burst.
Definition at line 187 of file dpdk-net-device.h.
Referenced by GetTypeId(), InitDpdk(), and Write().
m_mempool
struct rte_mempool* ns3::DpdkNetDevice::m_mempool private
Packet memory pool.
Definition at line 157 of file dpdk-net-device.h.
Referenced by AllocateBuffer(), and InitDpdk().
m_mempoolCacheSize
uint32_t ns3::DpdkNetDevice::m_mempoolCacheSize private
Mempool cache size.
Definition at line 192 of file dpdk-net-device.h.
Referenced by GetTypeId(), and InitDpdk().
m_nbRxDesc
uint16_t ns3::DpdkNetDevice::m_nbRxDesc private
Number of Rx descriptors.
Definition at line 197 of file dpdk-net-device.h.
Referenced by GetTypeId(), and InitDpdk().
m_nbTxDesc
uint16_t ns3::DpdkNetDevice::m_nbTxDesc private
Number of Tx descriptors.
Definition at line 202 of file dpdk-net-device.h.
Referenced by GetTypeId(), and InitDpdk().
m_portId
uint16_t ns3::DpdkNetDevice::m_portId protected
The port number of the device to be used.
Definition at line 140 of file dpdk-net-device.h.
Referenced by ~DpdkNetDevice(), CheckAllPortsLinkStatus(), HandleRx(), HandleTx(), InitDpdk(), and Write().
m_rxBuffer
struct rte_eth_dev_tx_buffer* ns3::DpdkNetDevice::m_rxBuffer private
Buffer to handle burst reception.
Definition at line 167 of file dpdk-net-device.h.
Referenced by HandleRx(), and InitDpdk().
m_txBuffer
struct rte_eth_dev_tx_buffer* ns3::DpdkNetDevice::m_txBuffer private
Buffer to handle burst transmission.
Definition at line 162 of file dpdk-net-device.h.
Referenced by HandleTx(), InitDpdk(), and Write().
m_txEvent
EventId ns3::DpdkNetDevice::m_txEvent private
Event for stale packet transmission.
Definition at line 172 of file dpdk-net-device.h.
Referenced by ~DpdkNetDevice(), and Write().
m_txTimeout
Time ns3::DpdkNetDevice::m_txTimeout private
The time to wait before transmitting burst from Tx buffer.
Definition at line 177 of file dpdk-net-device.h.
Referenced by GetTypeId(), and Write().
The documentation for this class was generated from the following files:
src/fd-net-device/model/dpdk-net-device.h
src/fd-net-device/model/dpdk-net-device.cc