ns-3: ns3::CtrlBAckRequestHeader Class Reference
ns3::CtrlBAckRequestHeader Class Reference
Wifi Models
Headers for BlockAckRequest.
#include "ctrl-headers.h"
Public Member Functions
CtrlBAckRequestHeader ()
~CtrlBAckRequestHeader ()
uint32_t Deserialize (Buffer::Iterator start)
TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint32_t GetSerializedSize (void) const
uint16_t GetStartingSequence (void) const
Return the starting sequence number.
uint16_t GetStartingSequenceControl (void) const
Return the starting sequence control.
uint8_t GetTidInfo (void) const
Return the Traffic ID (TID).
BlockAckType GetType (void) const
Return the Block Ack type ID.
bool IsBasic (void) const
Check if the current Ack Policy is Basic Block Ack (i.e.
bool IsCompressed (void) const
Check if the current Ack Policy is Compressed Block Ack and not multi-TID.
bool IsExtendedCompressed (void) const
Check if the current Ack Policy is Extended Compressed Block Ack.
bool IsMultiTid (void) const
Check if the current Ack Policy has Multi-TID Block Ack.
bool MustSendHtImmediateAck (void) const
Check if the current Ack Policy is immediate.
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetHtImmediateAck (bool immediateAck)
Enable or disable HT immediate Ack.
void SetStartingSequence (uint16_t seq)
Set the starting sequence number from the given raw sequence control field.
void SetTidInfo (uint8_t tid)
Set Traffic ID (TID).
void SetType (BlockAckType type)
Set the block ack type.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
uint16_t GetBarControl (void) const
Return the Block Ack control.
void SetBarControl (uint16_t bar)
Set the Block Ack control.
void SetStartingSequenceControl (uint16_t seqControl)
Set the starting sequence control with the given sequence control value.
Private Attributes
bool m_barAckPolicy
The LSB bit of the BAR control field is used only for the HT (High Throughput) delayed block ack configuration.
BlockAckType m_baType
BA type.
uint16_t m_startingSeq
starting sequence number
uint16_t m_tidInfo
TID info.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Headers for BlockAckRequest.
Introspection did not find any typical Config paths.
802.11n standard includes three types of BlockAck:
Basic BlockAck (unique type in 802.11e)
Compressed BlockAck
Multi-TID BlockAck For now only basic BlockAck and compressed BlockAck are supported. Basic BlockAck is also default variant.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 24 bytes (on a 64-bit architecture).
Definition at line 41 of file ctrl-headers.h.
Constructor & Destructor Documentation
CtrlBAckRequestHeader()
ns3::CtrlBAckRequestHeader::CtrlBAckRequestHeader ()
Definition at line 32 of file ctrl-headers.cc.
~CtrlBAckRequestHeader()
ns3::CtrlBAckRequestHeader::~CtrlBAckRequestHeader ()
Definition at line 38 of file ctrl-headers.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::CtrlBAckRequestHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 109 of file ctrl-headers.cc.
References ns3::BASIC_BLOCK_ACK, ns3::COMPRESSED_BLOCK_ACK, ns3::EXTENDED_COMPRESSED_BLOCK_ACK, ns3::Buffer::Iterator::GetDistanceFrom(), m_baType, ns3::MULTI_TID_BLOCK_ACK, NS_FATAL_ERROR, ns3::Buffer::Iterator::ReadLsbtohU16(), SetBarControl(), SetStartingSequenceControl(), and visualizer.core::start().
GetBarControl()
uint16_t ns3::CtrlBAckRequestHeader::GetBarControl (void) const private
Return the Block Ack control.
Returns
the Block Ack control
Definition at line 131 of file ctrl-headers.cc.
References ns3::BASIC_BLOCK_ACK, ns3::COMPRESSED_BLOCK_ACK, ns3::EXTENDED_COMPRESSED_BLOCK_ACK, m_baType, m_tidInfo, ns3::MULTI_TID_BLOCK_ACK, and NS_FATAL_ERROR.
Referenced by Serialize().
GetInstanceTypeId()
TypeId ns3::CtrlBAckRequestHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 54 of file ctrl-headers.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::CtrlBAckRequestHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 66 of file ctrl-headers.cc.
References ns3::BASIC_BLOCK_ACK, ns3::COMPRESSED_BLOCK_ACK, ns3::EXTENDED_COMPRESSED_BLOCK_ACK, m_baType, m_tidInfo, ns3::MULTI_TID_BLOCK_ACK, and NS_FATAL_ERROR.
Referenced by ns3::GetBlockAckRequestSize().
GetStartingSequence()
uint16_t ns3::CtrlBAckRequestHeader::GetStartingSequence (void) const
Return the starting sequence number.
Returns
the starting sequence number
Definition at line 234 of file ctrl-headers.cc.
References m_startingSeq.
Referenced by ns3::BlockAckManager::GetBar(), ns3::MacLow::ReceiveOk(), and ns3::MacLow::SendBlockAckAfterBlockAckRequest().
GetStartingSequenceControl()
uint16_t ns3::CtrlBAckRequestHeader::GetStartingSequenceControl (void) const
Return the starting sequence control.
Returns
the starting sequence control
Definition at line 179 of file ctrl-headers.cc.
References m_startingSeq.
Referenced by ns3::MacLow::SendBlockAckAfterBlockAckRequest(), and Serialize().
GetTidInfo()
uint8_t ns3::CtrlBAckRequestHeader::GetTidInfo (void) const
Return the Traffic ID (TID).
Returns
TID
Definition at line 227 of file ctrl-headers.cc.
References m_tidInfo.
Referenced by ns3::GetTid(), ns3::QosTxop::GetTransmissionParameters(), ns3::QosTxop::NeedBarRetransmission(), ns3::MacLow::ReceiveOk(), ns3::BlockAckManager::ScheduleBar(), and ns3::MacLow::SendBlockAckAfterBlockAckRequest().
GetType()
BlockAckType ns3::CtrlBAckRequestHeader::GetType (void) const
Return the Block Ack type ID.
Returns
the BA type
Definition at line 203 of file ctrl-headers.cc.
References m_baType.
GetTypeId()
TypeId ns3::CtrlBAckRequestHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 43 of file ctrl-headers.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
IsBasic()
bool ns3::CtrlBAckRequestHeader::IsBasic (void) const
Check if the current Ack Policy is Basic Block Ack (i.e.
not multi-TID nor compressed).
Returns
true if the current Ack Policy is Basic Block Ack, false otherwise
Definition at line 240 of file ctrl-headers.cc.
References ns3::BASIC_BLOCK_ACK, and m_baType.
Referenced by ns3::MacLow::SendBlockAckAfterBlockAckRequest().
IsCompressed()
bool ns3::CtrlBAckRequestHeader::IsCompressed (void) const
Check if the current Ack Policy is Compressed Block Ack and not multi-TID.
Returns
true if the current Ack Policy is Compressed Block Ack, false otherwise
Definition at line 246 of file ctrl-headers.cc.
References ns3::COMPRESSED_BLOCK_ACK, and m_baType.
Referenced by ns3::MacLow::SendBlockAckAfterBlockAckRequest().
IsExtendedCompressed()
bool ns3::CtrlBAckRequestHeader::IsExtendedCompressed (void) const
Check if the current Ack Policy is Extended Compressed Block Ack.
Returns
true if the current Ack Policy is Extended Compressed Block Ack, false otherwise
Definition at line 252 of file ctrl-headers.cc.
References ns3::EXTENDED_COMPRESSED_BLOCK_ACK, and m_baType.
Referenced by ns3::MacLow::SendBlockAckAfterBlockAckRequest().
IsMultiTid()
bool ns3::CtrlBAckRequestHeader::IsMultiTid (void) const
Check if the current Ack Policy has Multi-TID Block Ack.
Returns
true if the current Ack Policy has Multi-TID Block Ack, false otherwise
Definition at line 258 of file ctrl-headers.cc.
References m_baType, and ns3::MULTI_TID_BLOCK_ACK.
Referenced by ns3::MacLow::ReceiveOk(), and ns3::MacLow::SendBlockAckAfterBlockAckRequest().
MustSendHtImmediateAck()
bool ns3::CtrlBAckRequestHeader::MustSendHtImmediateAck (void) const
Check if the current Ack Policy is immediate.
Returns
true if the current Ack Policy is immediate, false otherwise
Definition at line 221 of file ctrl-headers.cc.
References m_barAckPolicy.
Print()
void ns3::CtrlBAckRequestHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 60 of file ctrl-headers.cc.
References m_startingSeq, and m_tidInfo.
Serialize()
void ns3::CtrlBAckRequestHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 88 of file ctrl-headers.cc.
References ns3::BASIC_BLOCK_ACK, ns3::COMPRESSED_BLOCK_ACK, ns3::EXTENDED_COMPRESSED_BLOCK_ACK, GetBarControl(), GetStartingSequenceControl(), m_baType, ns3::MULTI_TID_BLOCK_ACK, NS_FATAL_ERROR, visualizer.core::start(), and ns3::Buffer::Iterator::WriteHtolsbU16().
SetBarControl()
void ns3::CtrlBAckRequestHeader::SetBarControl (uint16_t bar) private
Set the Block Ack control.
Parameters
bar the BAR control value
Definition at line 156 of file ctrl-headers.cc.
References ns3::BASIC_BLOCK_ACK, ns3::COMPRESSED_BLOCK_ACK, ns3::EXTENDED_COMPRESSED_BLOCK_ACK, m_barAckPolicy, m_baType, m_tidInfo, and ns3::MULTI_TID_BLOCK_ACK.
Referenced by Deserialize().
SetHtImmediateAck()
void ns3::CtrlBAckRequestHeader::SetHtImmediateAck (bool immediateAck)
Enable or disable HT immediate Ack.
Parameters
immediateAck enable or disable HT immediate Ack
Definition at line 191 of file ctrl-headers.cc.
References m_barAckPolicy.
SetStartingSequence()
void ns3::CtrlBAckRequestHeader::SetStartingSequence (uint16_t seq)
Set the starting sequence number from the given raw sequence control field.
Parameters
seq the raw sequence control
Definition at line 215 of file ctrl-headers.cc.
References m_startingSeq.
Referenced by ns3::BlockAckManager::GetBar(), and ns3::BlockAckManager::GetBlockAckReqHeader().
SetStartingSequenceControl()
void ns3::CtrlBAckRequestHeader::SetStartingSequenceControl (uint16_t seqControl) private
Set the starting sequence control with the given sequence control value.
Parameters
seqControl the sequence control value
Definition at line 185 of file ctrl-headers.cc.
References m_startingSeq.
Referenced by Deserialize().
SetTidInfo()
void ns3::CtrlBAckRequestHeader::SetTidInfo (uint8_t tid)
Set Traffic ID (TID).
Parameters
tid the TID
Definition at line 209 of file ctrl-headers.cc.
References m_tidInfo.
Referenced by ns3::BlockAckManager::GetBlockAckReqHeader().
SetType()
void ns3::CtrlBAckRequestHeader::SetType (BlockAckType type)
Set the block ack type.
Parameters
type the BA type
Definition at line 197 of file ctrl-headers.cc.
References m_baType.
Referenced by ns3::BlockAckManager::GetBlockAckReqHeader(), and ns3::GetBlockAckRequestSize().
Member Data Documentation
m_barAckPolicy
bool ns3::CtrlBAckRequestHeader::m_barAckPolicy private
The LSB bit of the BAR control field is used only for the HT (High Throughput) delayed block ack configuration.
For now only non HT immediate BlockAck is implemented so this field is here only for a future implementation of HT delayed variant. BAR Ack Policy
Definition at line 174 of file ctrl-headers.h.
Referenced by MustSendHtImmediateAck(), SetBarControl(), and SetHtImmediateAck().
m_baType
BlockAckType ns3::CtrlBAckRequestHeader::m_baType private
BA type.
Definition at line 175 of file ctrl-headers.h.
Referenced by Deserialize(), GetBarControl(), GetSerializedSize(), GetType(), IsBasic(), IsCompressed(), IsExtendedCompressed(), IsMultiTid(), Serialize(), SetBarControl(), and SetType().
m_startingSeq
uint16_t ns3::CtrlBAckRequestHeader::m_startingSeq private
starting sequence number
Definition at line 177 of file ctrl-headers.h.
Referenced by GetStartingSequence(), GetStartingSequenceControl(), Print(), SetStartingSequence(), and SetStartingSequenceControl().
m_tidInfo
uint16_t ns3::CtrlBAckRequestHeader::m_tidInfo private
TID info.
Definition at line 176 of file ctrl-headers.h.
Referenced by GetBarControl(), GetSerializedSize(), GetTidInfo(), Print(), SetBarControl(), and SetTidInfo().
The documentation for this class was generated from the following files:
src/wifi/model/ctrl-headers.h
src/wifi/model/ctrl-headers.cc