ns-3: ns3::DoubleValue Class Reference
ns3::DoubleValue Class Reference
Double Attribute
This class can be used to hold variables of floating point type such as 'double' or 'float'.
#include "double.h"
Public Member Functions
DoubleValue ()
DoubleValue (const double &value)
Copy constructor.
virtual Ptr< AttributeValue > Copy (void) const
virtual bool DeserializeFromString (std::string value, Ptr< const AttributeChecker > checker)
double Get (void) const
template<typename T >
bool GetAccessor (T &value) const
Access the Double value as type T.
virtual std::string SerializeToString (Ptr< const AttributeChecker > checker) const
void Set (const double &value)
Set the value.
Public Member Functions inherited from ns3::AttributeValue
AttributeValue ()
virtual ~AttributeValue ()
Public Member Functions inherited from ns3::SimpleRefCount< AttributeValue >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
double m_value
The stored Double instance.
Detailed Description
This class can be used to hold variables of floating point type such as 'double' or 'float'.
AttributeValue implementation for Double.
The internal format is 'double'.
See also
AttributeValue
Definition at line 41 of file double.h.
Constructor & Destructor Documentation
DoubleValue() [1/2]
ns3::DoubleValue::DoubleValue ()
Definition at line 35 of file double.cc.
DoubleValue() [2/2]
Double ns3::DoubleValue::DoubleValue (const double & value)
Copy constructor.
Parameters
[in] value The Double value to copy.
Definition at line 35 of file double.cc.
Member Function Documentation
Copy()
Ptr< AttributeValue > ns3::DoubleValue::Copy (void) const virtual
Returns
a deep copy of this class, wrapped into an Attribute object.
Implements ns3::AttributeValue.
Definition at line 35 of file double.cc.
DeserializeFromString()
bool ns3::DoubleValue::DeserializeFromString (std::string value, Ptr< const AttributeChecker > checker) virtual
Parameters
[in] value A string representation of the value
[in] checker A pointer to the checker associated to the attribute.
Returns
true if the input string was correctly-formatted and could be successfully deserialized, false otherwise.
Upon return of this function, this AttributeValue instance contains the deserialized value. In most cases, this method will not make any use of the checker argument. However, in a very limited set of cases, the checker argument is needed to perform proper serialization. A nice example of code which needs it is the EnumValue::SerializeToString code.
Implements ns3::AttributeValue.
Definition at line 35 of file double.cc.
Get()
double ns3::DoubleValue::Get (void) const
Returns
The Double value.
Definition at line 35 of file double.cc.
Referenced by TcpIllinoisTest::CalculateAlpha(), TcpIllinoisTest::CalculateBeta(), RttEstimatorTestCase::DoRun(), TcpScalableDecrementTest::DoRun(), TcpBicDecrementTest::ExecuteTest(), ns3::ThreeGppSpectrumPropagationLossModel::GetFrequency(), ns3::TvSpectrumTransmitterHelper::InstallAdjacent(), ns3::internal::MakeDoubleChecker(), TcpIllinoisTest::RecalcParam(), and VanetRoutingExperiment::SetConfigFromGlobals().
GetAccessor()
template<typename T > bool ns3::DoubleValue::GetAccessor (T & value) const inline
Access the Double value as type T.
Template Parameters
T [explicit] The type to cast to.
Parameters
[out] value The Double value, as type T.
Returns
true.
Definition at line 41 of file double.h.
SerializeToString()
std::string ns3::DoubleValue::SerializeToString (Ptr< const AttributeChecker > checker) const virtual
Parameters
[in] checker The checker associated to the attribute
Returns
A string representation of this value.
In most cases, this method will not make any use of the checker argument. However, in a very limited set of cases, the checker argument is needed to perform proper serialization. A nice example of code which needs it is the EnumValue::SerializeToString code.
Implements ns3::AttributeValue.
Definition at line 35 of file double.cc.
Set()
void ns3::DoubleValue::Set (const double & value)
Set the value.
Parameters
[in] value The value to adopt.
Definition at line 35 of file double.cc.
Member Data Documentation
m_value
double ns3::DoubleValue::m_value private
The stored Double instance.
Definition at line 41 of file double.h.
The documentation for this class was generated from the following files:
src/core/model/double.h
src/core/model/double.cc
doc/introspected-doxygen.h