ns-3: ns3::dsr::DsrSendBuffEntry Class Reference
ns3::dsr::DsrSendBuffEntry Class Reference
DSR Routing
DSR Send Buffer Entry.
#include "dsr-rsendbuff.h"
Public Member Functions
DsrSendBuffEntry (Ptr< const Packet > pa=0, Ipv4Address d=Ipv4Address(), Time exp=Simulator::Now(), uint8_t p=0)
Construct DsrSendBuffEntry with the given parameters.
Ipv4Address GetDestination () const
Get destination address of entry.
Time GetExpireTime () const
Get expire time for entry.
Ptr< const Packet > GetPacket () const
Get pointer to entry's packet.
uint8_t GetProtocol () const
Get protocol value.
bool operator== (DsrSendBuffEntry const &o) const
Compare send buffer entries.
void SetDestination (Ipv4Address d)
Set destination address of entry.
void SetExpireTime (Time exp)
Set expire time for entry.
void SetPacket (Ptr< const Packet > p)
Set pointer to entry's packet.
void SetProtocol (uint8_t p)
Set protocol value.
Private Attributes
Ipv4Address m_dst
Destination address.
Time m_expire
Expire time for queue entry.
Ptr< const Packet > m_packet
Data packet.
uint8_t m_protocol
The protocol number.
Detailed Description
DSR Send Buffer Entry.
Definition at line 45 of file dsr-rsendbuff.h.
Constructor & Destructor Documentation
DsrSendBuffEntry()
ns3::dsr::DsrSendBuffEntry::DsrSendBuffEntry (Ptr< const Packet > pa = 0, Ipv4Address d = Ipv4Address (), Time exp = Simulator::Now (), uint8_t p = 0) inline
Construct DsrSendBuffEntry with the given parameters.
Parameters
pa packet
d destination address
exp expiration time
p protocol number
Definition at line 56 of file dsr-rsendbuff.h.
Member Function Documentation
GetDestination()
Ipv4Address ns3::dsr::DsrSendBuffEntry::GetDestination () const inline
Get destination address of entry.
Returns
the destination IPv4 address
Definition at line 95 of file dsr-rsendbuff.h.
References m_dst.
Referenced by ns3::dsr::DsrSendBuffer::Drop(), and ns3::dsr::DsrSendBuffer::Enqueue().
GetExpireTime()
Time ns3::dsr::DsrSendBuffEntry::GetExpireTime () const inline
Get expire time for entry.
Returns
the expire time
Definition at line 119 of file dsr-rsendbuff.h.
References m_expire, and ns3::Simulator::Now().
Referenced by ns3::dsr::IsExpired::operator()().
GetPacket()
Ptr<const Packet> ns3::dsr::DsrSendBuffEntry::GetPacket () const inline
Get pointer to entry's packet.
Returns
the current packet
Definition at line 79 of file dsr-rsendbuff.h.
References m_packet.
Referenced by ns3::dsr::DsrSendBuffer::Dequeue(), ns3::dsr::DsrSendBuffer::Drop(), ns3::dsr::DsrSendBuffer::Enqueue(), and ns3::dsr::DsrRouting::SendPacketFromBuffer().
GetProtocol()
uint8_t ns3::dsr::DsrSendBuffEntry::GetProtocol () const inline
Get protocol value.
Returns
the protocol
Definition at line 135 of file dsr-rsendbuff.h.
References m_protocol.
operator==()
bool ns3::dsr::DsrSendBuffEntry::operator== (DsrSendBuffEntry const & o) const inline
Compare send buffer entries.
Parameters
o another DsrSendBuffEntry
Returns
true if equal
Definition at line 69 of file dsr-rsendbuff.h.
References m_dst, m_expire, and m_packet.
SetDestination()
void ns3::dsr::DsrSendBuffEntry::SetDestination (Ipv4Address d) inline
Set destination address of entry.
Parameters
d the destination IP address
Definition at line 103 of file dsr-rsendbuff.h.
References m_dst.
SetExpireTime()
void ns3::dsr::DsrSendBuffEntry::SetExpireTime (Time exp) inline
Set expire time for entry.
Parameters
exp the expire time
Definition at line 111 of file dsr-rsendbuff.h.
References m_expire, and ns3::Simulator::Now().
Referenced by ns3::dsr::DsrSendBuffer::Enqueue().
SetPacket()
void ns3::dsr::DsrSendBuffEntry::SetPacket (Ptr< const Packet > p) inline
Set pointer to entry's packet.
Parameters
p the current packet
Definition at line 87 of file dsr-rsendbuff.h.
References m_packet.
SetProtocol()
void ns3::dsr::DsrSendBuffEntry::SetProtocol (uint8_t p) inline
Set protocol value.
Parameters
p the protocol
Definition at line 127 of file dsr-rsendbuff.h.
References m_protocol.
Member Data Documentation
m_dst
Ipv4Address ns3::dsr::DsrSendBuffEntry::m_dst private
Destination address.
Definition at line 144 of file dsr-rsendbuff.h.
Referenced by GetDestination(), operator==(), and SetDestination().
m_expire
Time ns3::dsr::DsrSendBuffEntry::m_expire private
Expire time for queue entry.
Definition at line 146 of file dsr-rsendbuff.h.
Referenced by GetExpireTime(), operator==(), and SetExpireTime().
m_packet
Ptr<const Packet> ns3::dsr::DsrSendBuffEntry::m_packet private
Data packet.
Definition at line 142 of file dsr-rsendbuff.h.
Referenced by GetPacket(), operator==(), and SetPacket().
m_protocol
uint8_t ns3::dsr::DsrSendBuffEntry::m_protocol private
The protocol number.
Definition at line 148 of file dsr-rsendbuff.h.
Referenced by GetProtocol(), and SetProtocol().
The documentation for this class was generated from the following file:
src/dsr/model/dsr-rsendbuff.h