ns-3: ns3::AsciiTraceHelperForDevice Class Reference
ns3::AsciiTraceHelperForDevice Class Reference abstract
Base class providing common user-level ascii trace operations for helpers representing net devices.
#include "trace-helper.h"
Public Member Functions
AsciiTraceHelperForDevice ()
Construct an AsciiTraceHelperForDevice.
virtual ~AsciiTraceHelperForDevice ()
Destroy an AsciiTraceHelperForDevice.
void EnableAscii (Ptr< OutputStreamWrapper > stream, NetDeviceContainer d)
Enable ascii trace output on each device in the container which is of the appropriate type.
void EnableAscii (Ptr< OutputStreamWrapper > stream, NodeContainer n)
Enable ascii trace output on each device (which is of the appropriate type) in the nodes provided in the container.
void EnableAscii (Ptr< OutputStreamWrapper > stream, Ptr< NetDevice > nd)
Enable ascii trace output on the indicated net device.
void EnableAscii (Ptr< OutputStreamWrapper > stream, std::string ndName)
Enable ascii trace output the indicated net device using a device previously named using the ns-3 object name service.
void EnableAscii (Ptr< OutputStreamWrapper > stream, uint32_t nodeid, uint32_t deviceid)
Enable ascii trace output on the device specified by a global node-id (of a previously created node) and associated device-id.
void EnableAscii (std::string prefix, NetDeviceContainer d)
Enable ascii trace output on each device in the container which is of the appropriate type.
void EnableAscii (std::string prefix, NodeContainer n)
Enable ascii trace output on each device (which is of the appropriate type) in the nodes provided in the container.
void EnableAscii (std::string prefix, Ptr< NetDevice > nd, bool explicitFilename=false)
Enable ascii trace output on the indicated net device.
void EnableAscii (std::string prefix, std::string ndName, bool explicitFilename=false)
Enable ascii trace output the indicated net device using a device previously named using the ns-3 object name service.
void EnableAscii (std::string prefix, uint32_t nodeid, uint32_t deviceid, bool explicitFilename)
Enable ascii trace output on the device specified by a global node-id (of a previously created node) and associated device-id.
void EnableAsciiAll (Ptr< OutputStreamWrapper > stream)
Enable ascii trace output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
void EnableAsciiAll (std::string prefix)
Enable ascii trace output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
virtual void EnableAsciiInternal (Ptr< OutputStreamWrapper > stream, std::string prefix, Ptr< NetDevice > nd, bool explicitFilename)=0
Enable ascii trace output on the indicated net device.
Private Member Functions
void EnableAsciiImpl (Ptr< OutputStreamWrapper > stream, std::string prefix, NetDeviceContainer d)
Enable ascii trace output on each device in the container which is of the appropriate type (implementation).
void EnableAsciiImpl (Ptr< OutputStreamWrapper > stream, std::string prefix, NodeContainer n)
Enable ascii trace output on each device (which is of the appropriate type) in the nodes provided in the container (implementation).
void EnableAsciiImpl (Ptr< OutputStreamWrapper > stream, std::string prefix, Ptr< NetDevice > nd, bool explicitFilename)
Enable ascii trace output the indicated net device (implementation).
void EnableAsciiImpl (Ptr< OutputStreamWrapper > stream, std::string prefix, std::string ndName, bool explicitFilename)
Enable ascii trace output the indicated net device using a device previously named using the ns-3 object name service (implementation).
void EnableAsciiImpl (Ptr< OutputStreamWrapper > stream, std::string prefix, uint32_t nodeid, uint32_t deviceid, bool explicitFilename)
Enable ascii trace output on the device specified by a global node-id (of a previously created node) and associated device-id (implementation)
Detailed Description
Base class providing common user-level ascii trace operations for helpers representing net devices.
Definition at line 641 of file trace-helper.h.
Constructor & Destructor Documentation
AsciiTraceHelperForDevice()
ns3::AsciiTraceHelperForDevice::AsciiTraceHelperForDevice () inline
Construct an AsciiTraceHelperForDevice.
Definition at line 647 of file trace-helper.h.
~AsciiTraceHelperForDevice()
virtual ns3::AsciiTraceHelperForDevice::~AsciiTraceHelperForDevice () inline virtual
Destroy an AsciiTraceHelperForDevice.
Definition at line 652 of file trace-helper.h.
Member Function Documentation
EnableAscii() [1/10]
void ns3::AsciiTraceHelperForDevice::EnableAscii (Ptr< OutputStreamWrapper > stream, NetDeviceContainer d)
Enable ascii trace output on each device in the container which is of the appropriate type.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
d container of devices
Definition at line 528 of file trace-helper.cc.
References EnableAsciiImpl().
EnableAscii() [2/10]
void ns3::AsciiTraceHelperForDevice::EnableAscii (Ptr< OutputStreamWrapper > stream, NodeContainer n)
Enable ascii trace output on each device (which is of the appropriate type) in the nodes provided in the container.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
n container of nodes.
Definition at line 559 of file trace-helper.cc.
References EnableAsciiImpl(), and sample-rng-plot::n.
EnableAscii() [3/10]
void ns3::AsciiTraceHelperForDevice::EnableAscii (Ptr< OutputStreamWrapper > stream, Ptr< NetDevice > nd)
Enable ascii trace output on the indicated net device.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
nd Net device for which you want to enable tracing.
Definition at line 478 of file trace-helper.cc.
References EnableAsciiInternal().
EnableAscii() [4/10]
void ns3::AsciiTraceHelperForDevice::EnableAscii (Ptr< OutputStreamWrapper > stream, std::string ndName)
Enable ascii trace output the indicated net device using a device previously named using the ns-3 object name service.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
ndName The name of the net device in which you want to enable tracing.
Definition at line 496 of file trace-helper.cc.
References EnableAsciiImpl().
EnableAscii() [5/10]
void ns3::AsciiTraceHelperForDevice::EnableAscii (Ptr< OutputStreamWrapper > stream, uint32_t nodeid, uint32_t deviceid)
Enable ascii trace output on the device specified by a global node-id (of a previously created node) and associated device-id.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
nodeid The node identifier/number of the node on which to enable ascii tracing
deviceid The device identifier/index of the device on which to enable ascii tracing
Definition at line 604 of file trace-helper.cc.
References EnableAsciiImpl().
EnableAscii() [6/10]
void ns3::AsciiTraceHelperForDevice::EnableAscii (std::string prefix, NetDeviceContainer d)
Enable ascii trace output on each device in the container which is of the appropriate type.
Parameters
prefix Filename prefix to use for ascii files.
d container of devices
Definition at line 519 of file trace-helper.cc.
References EnableAsciiImpl().
EnableAscii() [7/10]
void ns3::AsciiTraceHelperForDevice::EnableAscii (std::string prefix, NodeContainer n)
Enable ascii trace output on each device (which is of the appropriate type) in the nodes provided in the container.
Parameters
prefix Filename prefix to use for ascii files.
n container of nodes.
Definition at line 550 of file trace-helper.cc.
References EnableAsciiImpl(), and sample-rng-plot::n.
EnableAscii() [8/10]
void ns3::AsciiTraceHelperForDevice::EnableAscii (std::string prefix, Ptr< NetDevice > nd, bool explicitFilename = false)
Enable ascii trace output on the indicated net device.
Parameters
prefix Filename prefix to use for ascii files.
nd Net device for which you want to enable tracing.
explicitFilename Treat the prefix as an explicit filename if true
Definition at line 469 of file trace-helper.cc.
References EnableAsciiInternal().
Referenced by LrWpanAckTestCase::DoRun().
EnableAscii() [9/10]
void ns3::AsciiTraceHelperForDevice::EnableAscii (std::string prefix, std::string ndName, bool explicitFilename = false)
Enable ascii trace output the indicated net device using a device previously named using the ns-3 object name service.
Parameters
prefix filename prefix to use for ascii files.
ndName The name of the net device in which you want to enable tracing.
explicitFilename Treat the prefix as an explicit filename if true
Definition at line 487 of file trace-helper.cc.
References EnableAsciiImpl().
EnableAscii() [10/10]
void ns3::AsciiTraceHelperForDevice::EnableAscii (std::string prefix, uint32_t nodeid, uint32_t deviceid, bool explicitFilename)
Enable ascii trace output on the device specified by a global node-id (of a previously created node) and associated device-id.
Parameters
prefix Filename prefix to use when creating ascii trace files
nodeid The node identifier/number of the node on which to enable ascii tracing
deviceid The device identifier/index of the device on which to enable ascii tracing
explicitFilename Treat the prefix as an explicit filename if true
Definition at line 613 of file trace-helper.cc.
References EnableAsciiImpl().
EnableAsciiAll() [1/2]
void ns3::AsciiTraceHelperForDevice::EnableAsciiAll (Ptr< OutputStreamWrapper > stream)
Enable ascii trace output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
Definition at line 595 of file trace-helper.cc.
References EnableAsciiImpl(), and ns3::NodeContainer::GetGlobal().
EnableAsciiAll() [2/2]
void ns3::AsciiTraceHelperForDevice::EnableAsciiAll (std::string prefix)
Enable ascii trace output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
Parameters
prefix Filename prefix to use for ascii files.
Definition at line 586 of file trace-helper.cc.
References EnableAsciiImpl(), and ns3::NodeContainer::GetGlobal().
Referenced by DsdvManetExample::CreateDevices(), MeshTest::CreateNodes(), Ns3TcpLossTestCase::DoRun(), Ns3TcpStateTestCase::DoRun(), and VanetRoutingExperiment::SetupAdhocDevices().
EnableAsciiImpl() [1/5]
void ns3::AsciiTraceHelperForDevice::EnableAsciiImpl (Ptr< OutputStreamWrapper > stream, std::string prefix, NetDeviceContainer d) private
Enable ascii trace output on each device in the container which is of the appropriate type (implementation).
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
prefix Filename prefix to use for ascii files.
d container of devices
Definition at line 537 of file trace-helper.cc.
References ns3::NetDeviceContainer::Begin(), EnableAsciiInternal(), and ns3::NetDeviceContainer::End().
EnableAsciiImpl() [2/5]
void ns3::AsciiTraceHelperForDevice::EnableAsciiImpl (Ptr< OutputStreamWrapper > stream, std::string prefix, NodeContainer n) private
Enable ascii trace output on each device (which is of the appropriate type) in the nodes provided in the container (implementation).
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
prefix Filename prefix to use for ascii files.
n container of nodes.
Definition at line 568 of file trace-helper.cc.
References ns3::NetDeviceContainer::Add(), EnableAsciiImpl(), ns3::Node::GetDevice(), ns3::Node::GetNDevices(), and sample-rng-plot::n.
EnableAsciiImpl() [3/5]
void ns3::AsciiTraceHelperForDevice::EnableAsciiImpl (Ptr< OutputStreamWrapper > stream, std::string prefix, Ptr< NetDevice > nd, bool explicitFilename) private
Enable ascii trace output the indicated net device (implementation).
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
prefix filename prefix to use for ascii files.
nd Net device for which you want to enable tracing
explicitFilename Treat the prefix as an explicit filename if true
EnableAsciiImpl() [4/5]
void ns3::AsciiTraceHelperForDevice::EnableAsciiImpl (Ptr< OutputStreamWrapper > stream, std::string prefix, std::string ndName, bool explicitFilename) private
Enable ascii trace output the indicated net device using a device previously named using the ns-3 object name service (implementation).
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
prefix filename prefix to use for ascii files.
ndName The name of the net device in which you want to enable tracing.
explicitFilename Treat the prefix as an explicit filename if true
Definition at line 505 of file trace-helper.cc.
References EnableAsciiInternal().
EnableAsciiImpl() [5/5]
void ns3::AsciiTraceHelperForDevice::EnableAsciiImpl (Ptr< OutputStreamWrapper > stream, std::string prefix, uint32_t nodeid, uint32_t deviceid, bool explicitFilename) private
Enable ascii trace output on the device specified by a global node-id (of a previously created node) and associated device-id (implementation)
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
prefix Filename prefix to use for ascii trace files.
nodeid The node identifier/number of the node on which to enable ascii tracing
deviceid The device identifier/index of the device on which to enable ascii tracing
explicitFilename Treat the prefix as an explicit filename if true
Definition at line 626 of file trace-helper.cc.
References EnableAsciiInternal(), ns3::Node::GetDevice(), ns3::NodeContainer::GetGlobal(), ns3::Node::GetId(), ns3::Node::GetNDevices(), sample-rng-plot::n, and NS_ABORT_MSG_IF.
Referenced by EnableAscii(), EnableAsciiAll(), and EnableAsciiImpl().
EnableAsciiInternal()
virtual void ns3::AsciiTraceHelperForDevice::EnableAsciiInternal (Ptr< OutputStreamWrapper > stream, std::string prefix, Ptr< NetDevice > nd, bool explicitFilename) pure virtual
Enable ascii trace output on the indicated net device.
The implementation is expected to use a provided Ptr<OutputStreamWrapper> if it is non-null. If the OutputStreamWrapper is null, the implementation is expected to use a provided prefix to construct a new file name for each net device using the rules described in the class overview.
If the prefix is provided, there will be one file per net device created. In this case, adding a trace context to the file would be pointless, so the device implementation is expected to TraceConnectWithoutContext.
If the output stream object is provided, there may be many different devices writing to a single file. In this case, the device adding a trace context could be important, so the device implementation is expected to TraceConnect.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
prefix Filename prefix to use for ascii trace files.
nd Net device for which you want to enable tracing
explicitFilename Treat the prefix as an explicit filename if true
Implemented in ns3::WimaxHelper, ns3::WifiPhyHelper, ns3::YansWavePhyHelper, ns3::PointToPointHelper, ns3::LrWpanHelper, ns3::FdNetDeviceHelper, and ns3::CsmaHelper.
Referenced by EnableAscii(), and EnableAsciiImpl().
The documentation for this class was generated from the following files:
src/network/helper/trace-helper.h
src/network/helper/trace-helper.cc