ns-3: IcmpTimeExceedTestCase Class Reference
IcmpTimeExceedTestCase Class Reference
Internet Applications » ICMP protocol tests | Test suites
ICMP Time Exceed Reply Test.
Public Member Functions
IcmpTimeExceedTestCase ()
virtual ~IcmpTimeExceedTestCase ()
void DoSendData (Ptr< Socket > socket, Ipv4Address dst)
void ReceivePkt (Ptr< Socket > socket)
void SendData (Ptr< Socket > socket, Ipv4Address dst)
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
Ptr< Packet > m_receivedPacket
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
ICMP Time Exceed Reply Test.
Definition at line 228 of file icmp-test.cc.
Constructor & Destructor Documentation
IcmpTimeExceedTestCase()
IcmpTimeExceedTestCase::IcmpTimeExceedTestCase ()
Definition at line 245 of file icmp-test.cc.
~IcmpTimeExceedTestCase()
IcmpTimeExceedTestCase::~IcmpTimeExceedTestCase () virtual
Definition at line 252 of file icmp-test.cc.
Member Function Documentation
DoRun()
void IcmpTimeExceedTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 312 of file icmp-test.cc.
References ns3::NodeContainer::Add(), first::address, ns3::Socket::Bind(), third::channel, first::devices, ns3::Ipv4InterfaceContainer::GetAddress(), ns3::Packet::GetSize(), ns3::SimpleNetDeviceHelper::Install(), ns3::InternetStackHelper::Install(), m_receivedPacket, ns3::MakeCallback(), sample-rng-plot::n, n1n2, NS_TEST_EXPECT_MSG_EQ, ReceivePkt(), SendData(), ns3::ObjectBase::SetAttribute(), ns3::Socket::SetIpTtl(), ns3::SimpleNetDeviceHelper::SetNetDevicePointToPointMode(), and ns3::Socket::SetRecvCallback().
DoSendData()
void IcmpTimeExceedTestCase::DoSendData (Ptr< Socket > socket, Ipv4Address dst)
Definition at line 259 of file icmp-test.cc.
References ns3::Packet::AddHeader(), ns3::Packet::GetSize(), NS_TEST_EXPECT_MSG_EQ, ns3::Socket::SendTo(), ns3::Icmpv4Header::SetCode(), ns3::Icmpv4Echo::SetIdentifier(), ns3::Icmpv4Echo::SetSequenceNumber(), and ns3::Icmpv4Header::SetType().
Referenced by SendData().
ReceivePkt()
void IcmpTimeExceedTestCase::ReceivePkt (Ptr< Socket > socket)
Definition at line 290 of file icmp-test.cc.
References ns3::Packet::Copy(), ns3::Ipv4Header::GetProtocol(), ns3::Ipv4Header::GetSource(), ns3::Icmpv4Header::GetType(), m_receivedPacket, NS_TEST_EXPECT_MSG_EQ, ns3::Socket::RecvFrom(), and ns3::Packet::RemoveHeader().
Referenced by DoRun().
SendData()
void IcmpTimeExceedTestCase::SendData (Ptr< Socket > socket, Ipv4Address dst)
Definition at line 280 of file icmp-test.cc.
References DoSendData(), ns3::Node::GetId(), ns3::Socket::GetNode(), m_receivedPacket, and ns3::Seconds().
Referenced by DoRun().
Member Data Documentation
m_receivedPacket
Ptr<Packet> IcmpTimeExceedTestCase::m_receivedPacket private
Definition at line 240 of file icmp-test.cc.
Referenced by DoRun(), ReceivePkt(), and SendData().
The documentation for this class was generated from the following file:
src/internet/test/icmp-test.cc