ns-3: ns3::LlcSnapHeader Class Reference
ns3::LlcSnapHeader Class Reference
Network
Header for the LLC/SNAP encapsulation.
#include "llc-snap-header.h"
Public Member Functions
LlcSnapHeader ()
virtual uint32_t Deserialize (Buffer::Iterator start)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize (void) const
uint16_t GetType (void)
Return the Ethertype.
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetType (uint16_t type)
Set the Ethertype.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint16_t m_etherType
the Ethertype
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Header for the LLC/SNAP encapsulation.
Introspection did not find any typical Config paths.
For a list of EtherTypes, see http://www.iana.org/assignments/ieee-802-numbers/ieee-802-numbers.xhtml
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 16 bytes (on a 64-bit architecture).
Definition at line 42 of file llc-snap-header.h.
Constructor & Destructor Documentation
LlcSnapHeader()
ns3::LlcSnapHeader::LlcSnapHeader ()
Definition at line 32 of file llc-snap-header.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Deserialize()
uint32_t ns3::LlcSnapHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 92 of file llc-snap-header.cc.
References GetSerializedSize(), m_etherType, ns3::Buffer::Iterator::Next(), NS_LOG_FUNCTION, ns3::Buffer::Iterator::ReadNtohU16(), and visualizer.core::start().
GetInstanceTypeId()
TypeId ns3::LlcSnapHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 68 of file llc-snap-header.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::LlcSnapHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 51 of file llc-snap-header.cc.
References ns3::LLC_SNAP_HEADER_LENGTH, and NS_LOG_FUNCTION.
Referenced by Deserialize(), ns3::TapBridge::Filter(), and ns3::FdNetDevice::ForwardUp().
GetType()
uint16_t ns3::LlcSnapHeader::GetType (void)
Return the Ethertype.
Returns
Ethertype
Definition at line 44 of file llc-snap-header.cc.
References m_etherType, and NS_LOG_FUNCTION.
Referenced by ns3::TapBridge::Filter(), ns3::WaveNetDevice::ForwardUp(), ns3::WifiNetDevice::ForwardUp(), ns3::WimaxNetDevice::ForwardUp(), ns3::FdNetDevice::ForwardUp(), ns3::AlohaNoackNetDevice::NotifyReceptionEndOk(), WifiAcMappingTest::PacketEnqueuedInWifiMacQueue(), and ns3::CsmaNetDevice::Receive().
GetTypeId()
TypeId ns3::LlcSnapHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 58 of file llc-snap-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::LlcSnapHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 73 of file llc-snap-header.cc.
References m_etherType, and NS_LOG_FUNCTION.
Serialize()
void ns3::LlcSnapHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 83 of file llc-snap-header.cc.
References m_etherType, NS_LOG_FUNCTION, visualizer.core::start(), ns3::Buffer::Iterator::Write(), and ns3::Buffer::Iterator::WriteHtonU16().
SetType()
void ns3::LlcSnapHeader::SetType (uint16_t type)
Set the Ethertype.
Parameters
type the Ethertype
Definition at line 38 of file llc-snap-header.cc.
References m_etherType, and NS_LOG_FUNCTION.
Referenced by ns3::CsmaNetDevice::AddHeader(), ns3::WaveNetDevice::Send(), ns3::WifiNetDevice::Send(), ns3::WimaxNetDevice::Send(), ns3::FdNetDevice::SendFrom(), ns3::AlohaNoackNetDevice::SendFrom(), ns3::WifiNetDevice::SendFrom(), ns3::WimaxNetDevice::SendFrom(), and ns3::WaveNetDevice::SendX().
Member Data Documentation
m_etherType
uint16_t ns3::LlcSnapHeader::m_etherType private
the Ethertype
Definition at line 69 of file llc-snap-header.h.
Referenced by Deserialize(), GetType(), Print(), Serialize(), and SetType().
The documentation for this class was generated from the following files:
src/network/utils/llc-snap-header.h
src/network/utils/llc-snap-header.cc