ns-3: ns3::UdpSocketImpl Class Reference
ns3::UdpSocketImpl Class Reference
Network » Socket | Internet » UDP
A sockets interface to UDP.
#include "udp-socket-impl.h"
Public Member Functions
UdpSocketImpl ()
Create an unbound udp socket.
virtual ~UdpSocketImpl ()
virtual int Bind (const Address &address)
Allocate a local endpoint for this socket.
virtual int Bind (void)
Allocate a local IPv4 endpoint for this socket.
virtual int Bind6 (void)
Allocate a local IPv6 endpoint for this socket.
virtual void BindToNetDevice (Ptr< NetDevice > netdevice)
Bind a socket to specific device.
virtual int Close (void)
Close a socket.
virtual int Connect (const Address &address)
Initiate a connection to a remote host.
virtual bool GetAllowBroadcast () const
Query whether broadcast datagram transmissions are allowed.
virtual enum SocketErrno GetErrno (void) const
Get last error number.
virtual Ptr< Node > GetNode (void) const
Return the node this socket is associated with.
virtual int GetPeerName (Address &address) const
Get the peer address of a connected socket.
virtual uint32_t GetRxAvailable (void) const
Return number of bytes which can be returned from one or multiple calls to Recv.
virtual enum SocketType GetSocketType (void) const
virtual int GetSockName (Address &address) const
Get socket address.
virtual uint32_t GetTxAvailable (void) const
Returns the number of bytes which can be sent in a single call to Send.
virtual void Ipv6JoinGroup (Ipv6Address address, Socket::Ipv6MulticastFilterMode filterMode, std::vector< Ipv6Address > sourceAddresses)
Joins a IPv6 multicast group.
virtual int Listen (void)
Listen for incoming connections.
virtual int MulticastJoinGroup (uint32_t interfaceIndex, const Address &groupAddress)
Corresponds to socket option MCAST_JOIN_GROUP.
virtual int MulticastLeaveGroup (uint32_t interfaceIndex, const Address &groupAddress)
Corresponds to socket option MCAST_LEAVE_GROUP.
virtual Ptr< Packet > Recv (uint32_t maxSize, uint32_t flags)
Read data from the socket.
virtual Ptr< Packet > RecvFrom (uint32_t maxSize, uint32_t flags, Address &fromAddress)
Read a single packet from the socket and retrieve the sender address.
virtual int Send (Ptr< Packet > p, uint32_t flags)
Send data (or dummy data) to the remote host.
virtual int SendTo (Ptr< Packet > p, uint32_t flags, const Address &address)
Send data to a specified peer.
virtual bool SetAllowBroadcast (bool allowBroadcast)
Configure whether broadcast datagram transmissions are allowed.
void SetNode (Ptr< Node > node)
Set the associated node.
void SetUdp (Ptr< UdpL4Protocol > udp)
Set the associated UDP L4 protocol.
virtual int ShutdownRecv (void)
virtual int ShutdownSend (void)
Public Member Functions inherited from ns3::UdpSocket
UdpSocket (void)
virtual ~UdpSocket (void)
Public Member Functions inherited from ns3::Socket
Socket (void)
virtual ~Socket (void)
Ptr< NetDevice > GetBoundNetDevice ()
Returns socket's bound NetDevice, if any.
uint8_t GetIpTos (void) const
Query the value of IP Type of Service of this socket.
virtual uint8_t GetIpTtl (void) const
Query the value of IP Time to Live field of this socket.
virtual uint8_t GetIpv6HopLimit (void) const
Query the value of IP Hop Limit field of this socket.
uint8_t GetIpv6Tclass (void) const
Query the value of IPv6 Traffic Class field of this socket.
uint8_t GetPriority (void) const
Query the priority value of this socket.
virtual void Ipv6JoinGroup (Ipv6Address address)
Joins a IPv6 multicast group without filters.
virtual void Ipv6LeaveGroup (void)
Leaves IPv6 multicast group this socket is joined to.
bool IsIpRecvTos (void) const
Ask if the socket is currently passing information about IP Type of Service up the stack.
bool IsIpRecvTtl (void) const
Ask if the socket is currently passing information about IP_TTL up the stack.
bool IsIpv6RecvHopLimit (void) const
Ask if the socket is currently passing information about IPv6 Hop Limit up the stack.
bool IsIpv6RecvTclass (void) const
Ask if the socket is currently passing information about IPv6 Traffic Class up the stack.
bool IsRecvPktInfo () const
Get status indicating whether enable/disable packet information to socket.
int Recv (uint8_t *buf, uint32_t size, uint32_t flags)
Recv data (or dummy data) from the remote host.
Ptr< Packet > Recv (void)
Read a single packet from the socket.
Ptr< Packet > RecvFrom (Address &fromAddress)
Read a single packet from the socket and retrieve the sender address.
int RecvFrom (uint8_t *buf, uint32_t size, uint32_t flags, Address &fromAddress)
Read a single packet from the socket and retrieve the sender address.
int Send (const uint8_t *buf, uint32_t size, uint32_t flags)
Send data (or dummy data) to the remote host.
int Send (Ptr< Packet > p)
Send data (or dummy data) to the remote host.
int SendTo (const uint8_t *buf, uint32_t size, uint32_t flags, const Address &address)
Send data to a specified peer.
void SetAcceptCallback (Callback< bool, Ptr< Socket >, const Address & > connectionRequest, Callback< void, Ptr< Socket >, const Address & > newConnectionCreated)
Accept connection requests from remote hosts.
void SetCloseCallbacks (Callback< void, Ptr< Socket > > normalClose, Callback< void, Ptr< Socket > > errorClose)
Detect socket recv() events such as graceful shutdown or error.
void SetConnectCallback (Callback< void, Ptr< Socket > > connectionSucceeded, Callback< void, Ptr< Socket > > connectionFailed)
Specify callbacks to allow the caller to determine if the connection succeeds of fails.
void SetDataSentCallback (Callback< void, Ptr< Socket >, uint32_t > dataSent)
Notify application when a packet has been sent from transport protocol (non-standard socket call)
void SetIpRecvTos (bool ipv4RecvTos)
Tells a socket to pass information about IP Type of Service up the stack.
void SetIpRecvTtl (bool ipv4RecvTtl)
Tells a socket to pass information about IP_TTL up the stack.
void SetIpTos (uint8_t ipTos)
Manually set IP Type of Service field.
virtual void SetIpTtl (uint8_t ipTtl)
Manually set IP Time to Live field.
virtual void SetIpv6HopLimit (uint8_t ipHopLimit)
Manually set IPv6 Hop Limit.
void SetIpv6RecvHopLimit (bool ipv6RecvHopLimit)
Tells a socket to pass information about IPv6 Hop Limit up the stack.
void SetIpv6RecvTclass (bool ipv6RecvTclass)
Tells a socket to pass information about IPv6 Traffic Class up the stack.
void SetIpv6Tclass (int ipTclass)
Manually set IPv6 Traffic Class field.
void SetPriority (uint8_t priority)
Manually set the socket priority.
void SetRecvCallback (Callback< void, Ptr< Socket > >)
Notify application when new data is available to be read.
void SetRecvPktInfo (bool flag)
Enable/Disable receive packet information to socket.
void SetSendCallback (Callback< void, Ptr< Socket >, uint32_t > sendCb)
Notify application when space in transmit buffer is added.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::UdpSocket
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Socket
static Ptr< Socket > CreateSocket (Ptr< Node > node, TypeId tid)
This method wraps the creation of sockets that is performed on a given node by a SocketFactory specified by TypeId.
static TypeId GetTypeId (void)
Get the type ID.
static uint8_t IpTos2Priority (uint8_t ipTos)
Return the priority corresponding to a given TOS value.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void DeallocateEndPoint (void)
Deallocate m_endPoint and m_endPoint6.
void Destroy (void)
Kill this socket by zeroing its attributes (IPv4)
void Destroy6 (void)
Kill this socket by zeroing its attributes (IPv6)
int DoSend (Ptr< Packet > p)
Send a packet.
int DoSendTo (Ptr< Packet > p, Ipv4Address daddr, uint16_t dport, uint8_t tos)
Send a packet to a specific destination and port (IPv4)
int DoSendTo (Ptr< Packet > p, Ipv6Address daddr, uint16_t dport)
Send a packet to a specific destination and port (IPv6)
int FinishBind (void)
Finish the binding process.
void ForwardIcmp (Ipv4Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo)
Called by the L3 protocol when it received an ICMP packet to pass on to TCP.
void ForwardIcmp6 (Ipv6Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo)
Called by the L3 protocol when it received an ICMPv6 packet to pass on to TCP.
void ForwardUp (Ptr< Packet > packet, Ipv4Header header, uint16_t port, Ptr< Ipv4Interface > incomingInterface)
Called by the L3 protocol when it received a packet to pass on to TCP.
void ForwardUp6 (Ptr< Packet > packet, Ipv6Header header, uint16_t port, Ptr< Ipv6Interface > incomingInterface)
Called by the L3 protocol when it received a packet to pass on to TCP.
virtual int32_t GetIpMulticastIf (void) const
Get the IP multicast interface.
virtual bool GetIpMulticastLoop (void) const
Get the IP multicast loop capability.
virtual uint8_t GetIpMulticastTtl (void) const
Get the IP multicast TTL.
virtual bool GetMtuDiscover (void) const
Get the MTU discover capability.
virtual uint32_t GetRcvBufSize (void) const
Get the receiving buffer size.
virtual void SetIpMulticastIf (int32_t ipIf)
Set the IP multicast interface.
virtual void SetIpMulticastLoop (bool loop)
Set the IP multicast loop capability.
virtual void SetIpMulticastTtl (uint8_t ipTtl)
Set the IP multicast TTL.
virtual void SetMtuDiscover (bool discover)
Set the MTU discover capability.
virtual void SetRcvBufSize (uint32_t size)
Set the receiving buffer size.
Private Attributes
bool m_allowBroadcast
Allow send broadcast packets.
bool m_connected
Connection established.
Address m_defaultAddress
Default address.
uint16_t m_defaultPort
Default port.
std::queue< std::pair< Ptr< Packet >, Address > > m_deliveryQueue
Queue for incoming packets.
TracedCallback< Ptr< const Packet > > m_dropTrace
Trace for dropped packets.
Ipv4EndPoint * m_endPoint
the IPv4 endpoint
Ipv6EndPoint * m_endPoint6
the IPv6 endpoint
enum SocketErrno m_errno
Socket error code.
Callback< void, Ipv4Address, uint8_t, uint8_t, uint8_t, uint32_t > m_icmpCallback
ICMP callback.
Callback< void, Ipv6Address, uint8_t, uint8_t, uint8_t, uint32_t > m_icmpCallback6
ICMPv6 callback.
int32_t m_ipMulticastIf
Multicast Interface.
bool m_ipMulticastLoop
Allow multicast loop.
uint8_t m_ipMulticastTtl
Multicast TTL.
bool m_mtuDiscover
Allow MTU discovery.
Ptr< Node > m_node
the associated node
uint32_t m_rcvBufSize
Receive buffer size.
uint32_t m_rxAvailable
Number of available bytes to be received.
bool m_shutdownRecv
Receive no longer allowed.
bool m_shutdownSend
Send no longer allowed.
Ptr< UdpL4Protocol > m_udp
the associated UDP L4 protocol
Related Functions
(Note that these are not member functions.)
class UdpSocketFactory
UdpSocketFactory friend class.
Additional Inherited Members
Public Types inherited from ns3::Socket
enum Ipv6MulticastFilterMode { INCLUDE =1 , EXCLUDE }
Enumeration of the possible filter of a socket.
enum SocketErrno {
ERROR_NOTERROR , ERROR_ISCONN , ERROR_NOTCONN , ERROR_MSGSIZE ,
ERROR_AGAIN , ERROR_SHUTDOWN , ERROR_OPNOTSUPP , ERROR_AFNOSUPPORT ,
ERROR_INVAL , ERROR_BADF , ERROR_NOROUTETOHOST , ERROR_NODEV ,
ERROR_ADDRNOTAVAIL , ERROR_ADDRINUSE , SOCKET_ERRNO_LAST
}
Enumeration of the possible errors returned by a socket.
enum SocketPriority {
NS3_PRIO_BESTEFFORT = 0 , NS3_PRIO_FILLER = 1 , NS3_PRIO_BULK = 2 , NS3_PRIO_INTERACTIVE_BULK = 4 ,
NS3_PRIO_INTERACTIVE = 6 , NS3_PRIO_CONTROL = 7
}
Enumeration of the possible socket priorities.
enum SocketType { NS3_SOCK_STREAM , NS3_SOCK_SEQPACKET , NS3_SOCK_DGRAM , NS3_SOCK_RAW }
Enumeration of the possible socket types.
Protected Member Functions inherited from ns3::Socket
virtual void DoDispose (void)
Destructor implementation.
bool IsManualIpTtl (void) const
Checks if the socket has a specific IPv4 TTL set.
bool IsManualIpv6HopLimit (void) const
Checks if the socket has a specific IPv6 Hop Limit set.
bool IsManualIpv6Tclass (void) const
Checks if the socket has a specific IPv6 Tclass set.
void NotifyConnectionFailed (void)
Notify through the callback (if set) that the connection has not been established due to an error.
bool NotifyConnectionRequest (const Address &from)
Notify through the callback (if set) that an incoming connection is being requested by a remote host.
void NotifyConnectionSucceeded (void)
Notify through the callback (if set) that the connection has been established.
void NotifyDataRecv (void)
Notify through the callback (if set) that some data have been received.
void NotifyDataSent (uint32_t size)
Notify through the callback (if set) that some data have been sent.
void NotifyErrorClose (void)
Notify through the callback (if set) that the connection has been closed due to an error.
void NotifyNewConnectionCreated (Ptr< Socket > socket, const Address &from)
Notify through the callback (if set) that a new connection has been created.
void NotifyNormalClose (void)
Notify through the callback (if set) that the connection has been closed.
void NotifySend (uint32_t spaceAvailable)
Notify through the callback (if set) that some data have been sent.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Socket
Ptr< NetDevice > m_boundnetdevice
the device this socket is bound to (might be null).
Ipv6Address m_ipv6MulticastGroupAddress
IPv6 multicast group address.
bool m_recvPktInfo
if the socket should add packet info tags to the packet forwarded to L4.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A sockets interface to UDP.
This class subclasses ns3::UdpSocket, and provides a socket interface to ns3's implementation of UDP.
For IPv4 packets, the TOS is set according to the following rules:
if the socket is connected, the TOS set for the socket is used
if the socket is not connected, the TOS specified in the destination address passed to SendTo is used, while the TOS set for the socket is ignored In both cases, a SocketIpTos tag is only added to the packet if the resulting TOS is non-null. The Bind and Connect operations set the TOS for the socket to the value specified in the provided address. If the TOS determined for a packet (as described above) is not null, the packet is assigned a priority based on that TOS value (according to the Socket::IpTos2Priority function). Otherwise, the priority set for the socket is assigned to the packet. Setting a TOS for a socket also sets a priority for the socket (according to the Socket::IpTos2Priority function). A SocketPriority tag is only added to the packet if the resulting priority is non-null.
Config Paths
ns3::UdpSocketImpl is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::UdpL4Protocol/SocketList/[i]"
Attributes
IcmpCallback: Callback invoked whenever an icmp error is received on this socket.
Set with class: CallbackValue
Underlying type: Callback
Initial value: 0x0
Flags: construct write read
IcmpCallback6: Callback invoked whenever an icmpv6 error is received on this socket.
Set with class: CallbackValue
Underlying type: Callback
Initial value: 0x0
Flags: construct write read
Attributes defined in parent class ns3::UdpSocket
RcvBufSize: UdpSocket maximum receive buffer size (bytes)
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 131072
Flags: construct write read
IpTtl: socket-specific TTL for unicast IP packets (if non-zero)
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Initial value: 0
Flags: construct write read
IpMulticastTtl: socket-specific TTL for multicast IP packets (if non-zero)
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Initial value: 0
Flags: construct write read
IpMulticastIf: interface index for outgoing multicast on this socket; -1 indicates to use default interface
Set with class: ns3::IntegerValue
Underlying type: int32_t -2147483648:2147483647
Initial value: -1
Flags: construct write read
IpMulticastLoop: whether outgoing multicast sent also to loopback interface
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
MtuDiscover: If enabled, every outgoing ip packet will have the DF flag set.
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
TraceSources
Drop: Drop UDP packet due to receive buffer overflow
Callback signature: ns3::Packet::TracedCallback
Size of this type is 328 bytes (on a 64-bit architecture).
Definition at line 69 of file udp-socket-impl.h.
Constructor & Destructor Documentation
UdpSocketImpl()
ns3::UdpSocketImpl::UdpSocketImpl ()
Create an unbound udp socket.
Definition at line 78 of file udp-socket-impl.cc.
References m_allowBroadcast, and NS_LOG_FUNCTION.
~UdpSocketImpl()
ns3::UdpSocketImpl::~UdpSocketImpl () virtual
Todo:
leave any multicast groups that have been joined
Note: actually this function is called AFTER UdpSocketImpl::Destroy or UdpSocketImpl::Destroy6 so the code below is unnecessary in normal operations
Note that this piece of code is a bit tricky: when DeAllocate is called, it will call into Ipv4EndPointDemux::Deallocate which triggers a delete of the associated endPoint which triggers in turn a call to the method UdpSocketImpl::Destroy below will will zero the m_endPoint field.
Note that this piece of code is a bit tricky: when DeAllocate is called, it will call into Ipv4EndPointDemux::Deallocate which triggers a delete of the associated endPoint which triggers in turn a call to the method UdpSocketImpl::Destroy below will will zero the m_endPoint field.
Definition at line 93 of file udp-socket-impl.cc.
References m_endPoint, m_endPoint6, m_node, m_udp, NS_ASSERT, and NS_LOG_FUNCTION.
Member Function Documentation
Bind() [1/2]
int ns3::UdpSocketImpl::Bind (const Address & address) virtual
Allocate a local endpoint for this socket.
Parameters
address the address to try to allocate
Returns
0 on success, -1 on failure.
Implements ns3::Socket.
Definition at line 256 of file udp-socket-impl.cc.
References first::address, ns3::Ipv4EndPoint::BindToNetDevice(), ns3::Ipv6EndPoint::BindToNetDevice(), ns3::Inet6SocketAddress::ConvertFrom(), ns3::InetSocketAddress::ConvertFrom(), ns3::Socket::ERROR_ADDRINUSE, ns3::Socket::ERROR_ADDRNOTAVAIL, ns3::Socket::ERROR_INVAL, FinishBind(), ns3::Ipv6Address::GetAny(), ns3::Ipv4Address::GetAny(), ns3::Socket::GetBoundNetDevice(), ns3::InetSocketAddress::GetIpv4(), ns3::Inet6SocketAddress::GetIpv6(), ns3::Ipv6EndPoint::GetLocalAddress(), ns3::Object::GetObject(), ns3::InetSocketAddress::GetPort(), ns3::Inet6SocketAddress::GetPort(), ns3::InetSocketAddress::GetTos(), ns3::Inet6SocketAddress::IsMatchingType(), ns3::InetSocketAddress::IsMatchingType(), ns3::Ipv6Address::IsMulticast(), ns3::Socket::m_boundnetdevice, m_endPoint, m_endPoint6, m_errno, m_node, m_udp, NS_ASSERT_MSG, NS_LOG_ERROR, NS_LOG_FUNCTION, port, and ns3::Socket::SetIpTos().
Bind() [2/2]
int ns3::UdpSocketImpl::Bind (void) virtual
Allocate a local IPv4 endpoint for this socket.
Returns
0 on success, -1 on failure.
Implements ns3::Socket.
Definition at line 232 of file udp-socket-impl.cc.
References ns3::Ipv4EndPoint::BindToNetDevice(), FinishBind(), ns3::Socket::m_boundnetdevice, m_endPoint, m_udp, and NS_LOG_FUNCTION.
Referenced by DoSend(), and DoSendTo().
Bind6()
int ns3::UdpSocketImpl::Bind6 (void) virtual
Allocate a local IPv6 endpoint for this socket.
Returns
0 on success, -1 on failure.
Implements ns3::Socket.
Definition at line 244 of file udp-socket-impl.cc.
References ns3::Ipv6EndPoint::BindToNetDevice(), FinishBind(), ns3::Socket::m_boundnetdevice, m_endPoint6, m_udp, and NS_LOG_FUNCTION.
Referenced by DoSend(), and DoSendTo().
BindToNetDevice()
void ns3::UdpSocketImpl::BindToNetDevice (Ptr< NetDevice > netdevice) virtual
Bind a socket to specific device.
This method corresponds to using setsockopt() SO_BINDTODEVICE of real network or BSD sockets. If set on a socket, this option will force packets to leave the bound device regardless of the device that IP routing would naturally choose. In the receive direction, only packets received from the bound interface will be delivered.
This option has no particular relationship to binding sockets to an address via Socket::Bind (). It is possible to bind sockets to a specific IP address on the bound interface by calling both Socket::Bind (address) and Socket::BindToNetDevice (device), but it is also possible to bind to mismatching device and address, even if the socket can not receive any packets as a result.
Parameters
netdevice Pointer to NetDevice of desired interface
Returns
nothing
Reimplemented from ns3::Socket.
Definition at line 948 of file udp-socket-impl.cc.
References ns3::Ipv4EndPoint::BindToNetDevice(), ns3::Ipv6EndPoint::BindToNetDevice(), ns3::Socket::BindToNetDevice(), ns3::Ipv6EndPoint::GetLocalAddress(), ns3::Object::GetObject(), ns3::Ipv6Address::IsMulticast(), ns3::Socket::m_boundnetdevice, m_endPoint, m_endPoint6, m_node, and NS_LOG_FUNCTION.
Close()
int ns3::UdpSocketImpl::Close (void) virtual
Close a socket.
Returns
zero on success, -1 on failure.
After the Close call, the socket is no longer valid, and cannot safely be used for subsequent operations.
Implements ns3::Socket.
Definition at line 380 of file udp-socket-impl.cc.
References DeallocateEndPoint(), ns3::Socket::ERROR_BADF, ns3::Socket::Ipv6LeaveGroup(), m_errno, m_shutdownRecv, m_shutdownSend, and NS_LOG_FUNCTION.
Connect()
int ns3::UdpSocketImpl::Connect (const Address & address) virtual
Initiate a connection to a remote host.
Parameters
address Address of remote.
Returns
0 on success, -1 on error (in which case errno is set).
Implements ns3::Socket.
Definition at line 396 of file udp-socket-impl.cc.
References first::address, ns3::Inet6SocketAddress::ConvertFrom(), ns3::InetSocketAddress::ConvertFrom(), ns3::InetSocketAddress::GetIpv4(), ns3::Inet6SocketAddress::GetIpv6(), ns3::InetSocketAddress::GetPort(), ns3::Inet6SocketAddress::GetPort(), ns3::InetSocketAddress::GetTos(), ns3::Inet6SocketAddress::IsMatchingType(), ns3::InetSocketAddress::IsMatchingType(), m_connected, m_defaultAddress, m_defaultPort, ns3::Socket::NotifyConnectionFailed(), ns3::Socket::NotifyConnectionSucceeded(), NS_LOG_FUNCTION, and ns3::Socket::SetIpTos().
DeallocateEndPoint()
void ns3::UdpSocketImpl::DeallocateEndPoint (void) private
Deallocate m_endPoint and m_endPoint6.
Definition at line 188 of file udp-socket-impl.cc.
References m_endPoint, m_endPoint6, m_udp, ns3::Ipv4EndPoint::SetDestroyCallback(), and ns3::Ipv6EndPoint::SetDestroyCallback().
Referenced by Close().
Destroy()
void ns3::UdpSocketImpl::Destroy (void) private
Kill this socket by zeroing its attributes (IPv4)
This is a callback function configured to m_endpoint in SetupCallback(), invoked when the endpoint is destroyed.
Definition at line 173 of file udp-socket-impl.cc.
References m_endPoint, and NS_LOG_FUNCTION.
Referenced by FinishBind().
Destroy6()
void ns3::UdpSocketImpl::Destroy6 (void) private
Kill this socket by zeroing its attributes (IPv6)
This is a callback function configured to m_endpoint in SetupCallback(), invoked when the endpoint is destroyed.
Definition at line 180 of file udp-socket-impl.cc.
References m_endPoint6, and NS_LOG_FUNCTION.
Referenced by FinishBind().
DoSend()
int ns3::UdpSocketImpl::DoSend (Ptr< Packet > p) private
Send a packet.
Parameters
p packet
Returns
0 on success, -1 on failure
Definition at line 447 of file udp-socket-impl.cc.
References Bind(), Bind6(), ns3::Ipv4Address::ConvertFrom(), ns3::Ipv6Address::ConvertFrom(), DoSendTo(), ns3::Socket::ERROR_AFNOSUPPORT, ns3::Socket::ERROR_SHUTDOWN, ns3::Socket::GetIpTos(), ns3::Ipv4Address::IsMatchingType(), ns3::Ipv6Address::IsMatchingType(), m_defaultAddress, m_defaultPort, m_endPoint, m_endPoint6, m_errno, m_shutdownSend, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by Send().
DoSendTo() [1/2]
int ns3::UdpSocketImpl::DoSendTo (Ptr< Packet > p, Ipv4Address daddr, uint16_t dport, uint8_t tos) private
Send a packet to a specific destination and port (IPv4)
Parameters
p packet
daddr destination address
dport destination port
tos ToS
Returns
0 on success, -1 on failure
Definition at line 488 of file udp-socket-impl.cc.
References ns3::Packet::AddPacketTag(), Bind(), ns3::Packet::Copy(), ns3::SocketSetDontFragmentTag::Disable(), ns3::SocketSetDontFragmentTag::Enable(), ns3::Socket::ERROR_MSGSIZE, ns3::Socket::ERROR_NOROUTETOHOST, ns3::Socket::ERROR_OPNOTSUPP, ns3::Socket::ERROR_SHUTDOWN, ns3::Ipv4Address::GetAny(), ns3::Ipv4InterfaceAddress::GetBroadcast(), ns3::Ipv4Header::GetDestination(), ns3::Socket::GetIpTtl(), ns3::Ipv4InterfaceAddress::GetLocal(), ns3::Ipv4EndPoint::GetLocalAddress(), ns3::Ipv4EndPoint::GetLocalPort(), ns3::Object::GetObject(), ns3::Ipv4Route::GetOutputDevice(), ns3::Socket::GetPriority(), ns3::Packet::GetSize(), ns3::Ipv4Header::GetSource(), ns3::Ipv4Route::GetSource(), GetTxAvailable(), ns3::Socket::IpTos2Priority(), ns3::Ipv4Address::IsBroadcast(), ns3::Socket::IsManualIpTtl(), ns3::Ipv4Address::IsMulticast(), m_allowBroadcast, ns3::Socket::m_boundnetdevice, m_endPoint, m_errno, m_ipMulticastTtl, m_mtuDiscover, m_node, m_shutdownSend, m_udp, ns3::Socket::NotifyDataSent(), ns3::Socket::NotifySend(), NS_ASSERT, NS_LOG_ERROR, NS_LOG_FUNCTION, NS_LOG_LOGIC, port, ns3::UdpL4Protocol::PROT_NUMBER, ns3::Packet::RemovePacketTag(), ns3::Packet::ReplacePacketTag(), ns3::Ipv4Header::SetDestination(), ns3::SocketPriorityTag::SetPriority(), ns3::Ipv4Header::SetProtocol(), ns3::Ipv4Header::SetSource(), ns3::SocketIpTosTag::SetTos(), and ns3::SocketIpTtlTag::SetTtl().
Referenced by DoSend(), DoSendTo(), and SendTo().
DoSendTo() [2/2]
int ns3::UdpSocketImpl::DoSendTo (Ptr< Packet > p, Ipv6Address daddr, uint16_t dport) private
Send a packet to a specific destination and port (IPv6)
Parameters
p packet
daddr destination address
dport destination port
Returns
0 on success, -1 on failure
Definition at line 666 of file udp-socket-impl.cc.
References ns3::Packet::AddPacketTag(), Bind6(), ns3::Packet::Copy(), DoSendTo(), ns3::Socket::ERROR_MSGSIZE, ns3::Socket::ERROR_NOROUTETOHOST, ns3::Socket::ERROR_SHUTDOWN, ns3::Ipv6Address::GetAny(), ns3::Ipv6Header::GetDestinationAddress(), ns3::Ipv6Address::GetIpv4MappedAddress(), ns3::Socket::GetIpv6HopLimit(), ns3::Socket::GetIpv6Tclass(), ns3::Ipv6EndPoint::GetLocalAddress(), ns3::Ipv6EndPoint::GetLocalPort(), ns3::Object::GetObject(), ns3::Socket::GetPriority(), ns3::Packet::GetSize(), ns3::Ipv6Header::GetSourceAddress(), GetTxAvailable(), ns3::Ipv6Address::IsIpv4MappedAddress(), ns3::Socket::IsManualIpv6HopLimit(), ns3::Socket::IsManualIpv6Tclass(), ns3::Ipv6Address::IsMulticast(), ns3::Socket::m_boundnetdevice, m_endPoint6, m_errno, m_ipMulticastTtl, m_node, m_shutdownSend, m_udp, ns3::Socket::NotifyDataSent(), ns3::Socket::NotifySend(), NS_ASSERT, NS_LOG_ERROR, NS_LOG_FUNCTION, NS_LOG_LOGIC, port, ns3::UdpL4Protocol::PROT_NUMBER, ns3::Packet::ReplacePacketTag(), ns3::Ipv6Header::SetDestinationAddress(), ns3::SocketIpv6HopLimitTag::SetHopLimit(), ns3::Ipv6Header::SetNextHeader(), ns3::SocketPriorityTag::SetPriority(), ns3::Ipv6Header::SetSourceAddress(), and ns3::SocketIpv6TclassTag::SetTclass().
FinishBind()
int ns3::UdpSocketImpl::FinishBind (void) private
Finish the binding process.
Returns
0 on success, -1 on failure
Definition at line 206 of file udp-socket-impl.cc.
References Destroy(), Destroy6(), ForwardIcmp(), ForwardIcmp6(), ForwardUp(), ForwardUp6(), m_endPoint, m_endPoint6, ns3::MakeCallback(), NS_LOG_FUNCTION, ns3::Ipv4EndPoint::SetDestroyCallback(), ns3::Ipv6EndPoint::SetDestroyCallback(), ns3::Ipv4EndPoint::SetIcmpCallback(), ns3::Ipv6EndPoint::SetIcmpCallback(), ns3::Ipv4EndPoint::SetRxCallback(), and ns3::Ipv6EndPoint::SetRxCallback().
Referenced by Bind(), and Bind6().
ForwardIcmp()
void ns3::UdpSocketImpl::ForwardIcmp (Ipv4Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo) private
Called by the L3 protocol when it received an ICMP packet to pass on to TCP.
Parameters
icmpSource the ICMP source address
icmpTtl the ICMP Time to Live
icmpType the ICMP Type
icmpCode the ICMP Code
icmpInfo the ICMP Info
Definition at line 1119 of file udp-socket-impl.cc.
References m_icmpCallback, and NS_LOG_FUNCTION.
Referenced by FinishBind().
ForwardIcmp6()
void ns3::UdpSocketImpl::ForwardIcmp6 (Ipv6Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo) private
Called by the L3 protocol when it received an ICMPv6 packet to pass on to TCP.
Parameters
icmpSource the ICMP source address
icmpTtl the ICMP Time to Live
icmpType the ICMP Type
icmpCode the ICMP Code
icmpInfo the ICMP Info
Definition at line 1132 of file udp-socket-impl.cc.
References m_icmpCallback6, and NS_LOG_FUNCTION.
Referenced by FinishBind().
ForwardUp()
void ns3::UdpSocketImpl::ForwardUp (Ptr< Packet > packet, Ipv4Header header, uint16_t port, Ptr< Ipv4Interface > incomingInterface) private
Called by the L3 protocol when it received a packet to pass on to TCP.
Parameters
packet the incoming packet
header the packet's IPv4 header
port the remote port
incomingInterface the incoming interface
Definition at line 999 of file udp-socket-impl.cc.
References ns3::Packet::AddPacketTag(), first::address, ns3::Ipv4Header::GetDestination(), ns3::Ipv4Interface::GetDevice(), ns3::Packet::GetSize(), ns3::Ipv4Header::GetSource(), ns3::Ipv4Header::GetTos(), ns3::Ipv4Header::GetTtl(), ns3::Socket::IsIpRecvTos(), ns3::Socket::IsIpRecvTtl(), ns3::Socket::IsRecvPktInfo(), m_deliveryQueue, m_dropTrace, m_rcvBufSize, m_rxAvailable, m_shutdownRecv, ns3::Socket::NotifyDataRecv(), NS_LOG_FUNCTION, NS_LOG_WARN, port, ns3::Packet::RemovePacketTag(), ns3::Ipv4PacketInfoTag::SetAddress(), ns3::Ipv4PacketInfoTag::SetRecvIf(), ns3::SocketIpTosTag::SetTos(), ns3::Ipv4PacketInfoTag::SetTtl(), and ns3::SocketIpTtlTag::SetTtl().
Referenced by FinishBind().
ForwardUp6()
void ns3::UdpSocketImpl::ForwardUp6 (Ptr< Packet > packet, Ipv6Header header, uint16_t port, Ptr< Ipv6Interface > incomingInterface) private
Called by the L3 protocol when it received a packet to pass on to TCP.
Parameters
packet the incoming packet
header the packet's IPv6 header
port the remote port
incomingInterface the incoming interface
Definition at line 1059 of file udp-socket-impl.cc.
References ns3::Packet::AddPacketTag(), first::address, ns3::Ipv6Header::GetDestinationAddress(), ns3::Ipv6Interface::GetDevice(), ns3::Ipv6Header::GetHopLimit(), ns3::Packet::GetSize(), ns3::Ipv6Header::GetSourceAddress(), ns3::Ipv6Header::GetTrafficClass(), ns3::Socket::IsIpv6RecvHopLimit(), ns3::Socket::IsIpv6RecvTclass(), ns3::Socket::IsRecvPktInfo(), m_deliveryQueue, m_dropTrace, m_rcvBufSize, m_rxAvailable, m_shutdownRecv, ns3::Socket::NotifyDataRecv(), NS_LOG_FUNCTION, NS_LOG_WARN, port, ns3::Packet::RemovePacketTag(), ns3::Ipv6PacketInfoTag::SetAddress(), ns3::SocketIpv6HopLimitTag::SetHopLimit(), ns3::Ipv6PacketInfoTag::SetHoplimit(), ns3::Ipv6PacketInfoTag::SetRecvIf(), ns3::SocketIpv6TclassTag::SetTclass(), and ns3::Ipv6PacketInfoTag::SetTrafficClass().
Referenced by FinishBind().
GetAllowBroadcast()
bool ns3::UdpSocketImpl::GetAllowBroadcast () const virtual
Query whether broadcast datagram transmissions are allowed.
This method corresponds to using getsockopt() SO_BROADCAST of real network or BSD sockets.
Returns
true if broadcast is allowed, false otherwise
Implements ns3::Socket.
Definition at line 1211 of file udp-socket-impl.cc.
References m_allowBroadcast.
GetErrno()
enum Socket::SocketErrno ns3::UdpSocketImpl::GetErrno (void) const virtual
Get last error number.
Returns
the errno associated to the last call which failed in this socket. Each socket's errno is initialized to zero when the socket is created.
Implements ns3::Socket.
Definition at line 145 of file udp-socket-impl.cc.
References m_udp, and NS_LOG_FUNCTION.
GetIpMulticastIf()
int32_t ns3::UdpSocketImpl::GetIpMulticastIf (void) const private virtual
Get the IP multicast interface.
Returns
the IP multicast interface
Implements ns3::UdpSocket.
Definition at line 1175 of file udp-socket-impl.cc.
References m_ipMulticastIf.
GetIpMulticastLoop()
bool ns3::UdpSocketImpl::GetIpMulticastLoop (void) const private virtual
Get the IP multicast loop capability.
This means that the socket will receive the packets sent by itself on a multicast address. Equivalent to setsockopt IP_MULTICAST_LOOP
Returns
the IP multicast loop capability
Implements ns3::UdpSocket.
Definition at line 1187 of file udp-socket-impl.cc.
References m_ipMulticastLoop.
GetIpMulticastTtl()
uint8_t ns3::UdpSocketImpl::GetIpMulticastTtl (void) const private virtual
Get the IP multicast TTL.
Returns
the IP multicast TTL
Implements ns3::UdpSocket.
Definition at line 1163 of file udp-socket-impl.cc.
References m_ipMulticastTtl.
GetMtuDiscover()
bool ns3::UdpSocketImpl::GetMtuDiscover (void) const private virtual
Get the MTU discover capability.
Returns
the MTU discover capability
Implements ns3::UdpSocket.
Definition at line 1198 of file udp-socket-impl.cc.
References m_mtuDiscover.
GetNode()
Ptr< Node > ns3::UdpSocketImpl::GetNode (void) const virtual
Return the node this socket is associated with.
Returns
the node
Implements ns3::Socket.
Definition at line 166 of file udp-socket-impl.cc.
References m_node, and NS_LOG_FUNCTION.
GetPeerName()
int ns3::UdpSocketImpl::GetPeerName (Address & address) const virtual
Get the peer address of a connected socket.
Parameters
address the address this socket is connected to.
Returns
0 if success, -1 otherwise
Implements ns3::Socket.
Definition at line 889 of file udp-socket-impl.cc.
References first::address, ns3::Ipv4Address::ConvertFrom(), ns3::Ipv6Address::ConvertFrom(), ns3::Socket::ERROR_NOTCONN, ns3::Socket::GetIpTos(), ns3::Ipv4Address::IsMatchingType(), ns3::Ipv6Address::IsMatchingType(), m_connected, m_defaultAddress, m_defaultPort, m_errno, NS_ASSERT_MSG, NS_LOG_FUNCTION, and ns3::InetSocketAddress::SetTos().
GetRcvBufSize()
uint32_t ns3::UdpSocketImpl::GetRcvBufSize (void) const private virtual
Get the receiving buffer size.
Returns
the buffer size
Implements ns3::UdpSocket.
Definition at line 1151 of file udp-socket-impl.cc.
References m_rcvBufSize.
GetRxAvailable()
uint32_t ns3::UdpSocketImpl::GetRxAvailable (void) const virtual
Return number of bytes which can be returned from one or multiple calls to Recv.
Must be possible to call this method from the Recv callback.
Returns
the number of bytes which can be returned from one or multiple Recv calls.
Implements ns3::Socket.
Definition at line 823 of file udp-socket-impl.cc.
References m_rxAvailable, and NS_LOG_FUNCTION.
GetSocketType()
enum Socket::SocketType ns3::UdpSocketImpl::GetSocketType (void) const virtual
Returns
the socket type, analogous to getsockopt (SO_TYPE)
Implements ns3::Socket.
Definition at line 145 of file udp-socket-impl.cc.
GetSockName()
int ns3::UdpSocketImpl::GetSockName (Address & address) const virtual
Get socket address.
Parameters
address the address name this socket is associated with.
Returns
0 if success, -1 otherwise
Implements ns3::Socket.
Definition at line 868 of file udp-socket-impl.cc.
References first::address, ns3::Ipv6EndPoint::GetLocalAddress(), ns3::Ipv4EndPoint::GetLocalAddress(), ns3::Ipv6EndPoint::GetLocalPort(), ns3::Ipv4EndPoint::GetLocalPort(), ns3::Ipv4Address::GetZero(), m_endPoint, m_endPoint6, and NS_LOG_FUNCTION.
GetTxAvailable()
uint32_t ns3::UdpSocketImpl::GetTxAvailable (void) const virtual
Returns the number of bytes which can be sent in a single call to Send.
For datagram sockets, this returns the number of bytes that can be passed atomically through the underlying protocol.
For stream sockets, this returns the available space in bytes left in the transmit buffer.
Returns
The number of bytes which can be sent in a single Send call.
Implements ns3::Socket.
Definition at line 792 of file udp-socket-impl.cc.
References ns3::MAX_IPV4_UDP_DATAGRAM_SIZE, and NS_LOG_FUNCTION.
Referenced by DoSendTo().
GetTypeId()
TypeId ns3::UdpSocketImpl::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 56 of file udp-socket-impl.cc.
References m_dropTrace, m_icmpCallback, m_icmpCallback6, ns3::MakeCallbackAccessor(), ns3::MakeCallbackChecker(), ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
Ipv6JoinGroup()
void ns3::UdpSocketImpl::Ipv6JoinGroup (Ipv6Address address, Socket::Ipv6MulticastFilterMode filterMode, std::vector< Ipv6Address > sourceAddresses) virtual
Joins a IPv6 multicast group.
Based on the filter mode and source addresses this can be interpreted as a join, leave, or modification to source filtering on a multicast group.
Mind that a socket can join only one multicast group. Any attempt to join another group will remove the old one.
Parameters
address Requested multicast address.
filterMode Socket filtering mode (INCLUDE | EXCLUDE).
sourceAddresses All the source addresses on which socket is interested or not interested.
Reimplemented from ns3::Socket.
Definition at line 1217 of file udp-socket-impl.cc.
References first::address, ns3::Object::GetObject(), ns3::Socket::INCLUDE, ns3::Ipv6Address::IsAny(), ns3::Socket::m_boundnetdevice, ns3::Socket::m_ipv6MulticastGroupAddress, m_node, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
Listen()
int ns3::UdpSocketImpl::Listen (void) virtual
Listen for incoming connections.
Returns
0 on success, -1 on error (in which case errno is set).
Implements ns3::Socket.
Definition at line 426 of file udp-socket-impl.cc.
References ns3::Socket::ERROR_OPNOTSUPP, and m_errno.
MulticastJoinGroup()
int ns3::UdpSocketImpl::MulticastJoinGroup (uint32_t interface, const Address & groupAddress) virtual
Corresponds to socket option MCAST_JOIN_GROUP.
Parameters
interface interface number, or 0
groupAddress multicast group address
Returns
on success, zero is returned. On error, -1 is returned, and errno is set appropriately
Enable reception of multicast datagrams for this socket on the interface number specified. If zero is specified as the interface, then a single local interface is chosen by system. In the future, this function will generate trigger IGMP joins as necessary when IGMP is implemented, but for now, this just enables multicast datagram reception in the system if not already enabled for this interface/groupAddress combination.
Attention
IGMP is not yet implemented in ns-3
This function may be called repeatedly on a given socket but each join must be for a different multicast address, or for the same multicast address but on a different interface from previous joins. This enables host multihoming, and the ability to join the same group on different interfaces.
Implements ns3::UdpSocket.
Definition at line 920 of file udp-socket-impl.cc.
References NS_LOG_FUNCTION.
MulticastLeaveGroup()
int ns3::UdpSocketImpl::MulticastLeaveGroup (uint32_t interface, const Address & groupAddress) virtual
Corresponds to socket option MCAST_LEAVE_GROUP.
Parameters
interface interface number, or 0
groupAddress multicast group address
Returns
on success, zero is returned. On error, -1 is returned, and errno is set appropriately
Disable reception of multicast datagrams for this socket on the interface number specified. If zero is specified as the interfaceIndex, then a single local interface is chosen by system. In the future, this function will generate trigger IGMP leaves as necessary when IGMP is implemented, but for now, this just disables multicast datagram reception in the system if this socket is the last for this interface/groupAddress combination.
Attention
IGMP is not yet implemented in ns-3
Implements ns3::UdpSocket.
Definition at line 934 of file udp-socket-impl.cc.
References NS_LOG_FUNCTION.
Recv()
Ptr< Packet > ns3::UdpSocketImpl::Recv (uint32_t maxSize, uint32_t flags) virtual
Read data from the socket.
This function matches closely in semantics to the recv() function call in the standard C library (libc): ssize_t recv (int s, void *buf, size_t len, int flags); except that the receive I/O is asynchronous. This is the primary Recv method at this low-level API and must be implemented by subclasses.
This method is normally used only on a connected socket. In a typical blocking sockets model, this call would block until at least one byte is returned or the connection closes. In ns-3 at this API, the call returns immediately in such a case and returns 0 if nothing is available to be read. However, an application can set a callback, ns3::SetRecvCallback, to be notified of data being available to be read (when it conceptually unblocks); this is an asynchronous I/O model for recv().
This variant of Recv() uses class ns3::Packet to encapsulate data, rather than providing a raw pointer and length field. This allows an ns-3 application to attach tags if desired (such as a flow ID) and may allow the simulator to avoid some data copies. Despite the appearance of receiving Packets on a stream socket, just think of it as a fancy byte buffer with streaming semantics.
The semantics depend on the type of socket. For a datagram socket, each Recv() returns the data from at most one Send(), and order is not necessarily preserved. For a stream socket, the bytes are delivered in order, and on-the-wire packet boundaries are not preserved.
The flags argument is formed by or'ing one or more of the values: MSG_OOB process out-of-band data MSG_PEEK peek at incoming message None of these flags are supported for now.
Some variants of Recv() are supported as additional API, including RecvFrom(), overloaded Recv() without arguments, and variants that use raw character buffers.
Parameters
maxSize reader will accept packet up to maxSize
flags Socket control flags
Returns
Ptr<Packet> of the next in-sequence packet. Returns 0 if the socket cannot return a next in-sequence packet conforming to the maxSize and flags.
See also
SetRecvCallback
Implements ns3::Socket.
Definition at line 832 of file udp-socket-impl.cc.
References NS_LOG_FUNCTION, and RecvFrom().
RecvFrom()
Ptr< Packet > ns3::UdpSocketImpl::RecvFrom (uint32_t maxSize, uint32_t flags, Address & fromAddress) virtual
Read a single packet from the socket and retrieve the sender address.
Calls Recv(maxSize, flags) with maxSize implicitly set to maximum sized integer, and flags set to zero.
This method has similar semantics to Recv () but subclasses may want to provide checks on socket state, so the implementation is pushed to subclasses.
Parameters
maxSize reader will accept packet up to maxSize
flags Socket control flags
fromAddress output parameter that will return the address of the sender of the received packet, if any. Remains untouched if no packet is received.
Returns
Ptr<Packet> of the next in-sequence packet. Returns 0 if the socket cannot return a next in-sequence packet.
Implements ns3::Socket.
Definition at line 842 of file udp-socket-impl.cc.
References ns3::Socket::ERROR_AGAIN, ns3::Packet::GetSize(), m_deliveryQueue, m_errno, m_rxAvailable, and NS_LOG_FUNCTION.
Referenced by Recv().
Send()
int ns3::UdpSocketImpl::Send (Ptr< Packet > p, uint32_t flags) virtual
Send data (or dummy data) to the remote host.
This function matches closely in semantics to the send() function call in the standard C library (libc): ssize_t send (int s, const void *msg, size_t len, int flags); except that the send I/O is asynchronous. This is the primary Send method at this low-level API and must be implemented by subclasses.
In a typical blocking sockets model, this call would block upon lack of space to hold the message to be sent. In ns-3 at this API, the call returns immediately in such a case, but the callback registered with SetSendCallback() is invoked when the socket has space (when it conceptually unblocks); this is an asynchronous I/O model for send().
This variant of Send() uses class ns3::Packet to encapsulate data, rather than providing a raw pointer and length field. This allows an ns-3 application to attach tags if desired (such as a flow ID) and may allow the simulator to avoid some data copies. Despite the appearance of sending Packets on a stream socket, just think of it as a fancy byte buffer with streaming semantics.
If either the message buffer within the Packet is too long to pass atomically through the underlying protocol (for datagram sockets), or the message buffer cannot entirely fit in the transmit buffer (for stream sockets), -1 is returned and SocketErrno is set to ERROR_MSGSIZE. If the packet does not fit, the caller can split the Packet (based on information obtained from GetTxAvailable) and reattempt to send the data.
The flags argument is formed by or'ing one or more of the values: MSG_OOB process out-of-band data MSG_DONTROUTE bypass routing, use direct interface These flags are unsupported as of ns-3.1.
Parameters
p ns3::Packet to send
flags Socket control flags
Returns
the number of bytes accepted for transmission if no error occurs, and -1 otherwise.
See also
SetSendCallback
Implements ns3::Socket.
Definition at line 433 of file udp-socket-impl.cc.
References DoSend(), ns3::Socket::ERROR_NOTCONN, m_connected, m_errno, and NS_LOG_FUNCTION.
SendTo()
int ns3::UdpSocketImpl::SendTo (Ptr< Packet > p, uint32_t flags, const Address & toAddress) virtual
Send data to a specified peer.
This method has similar semantics to Send () but subclasses may want to provide checks on socket state, so the implementation is pushed to subclasses.
Parameters
p packet to send
flags Socket control flags
toAddress IP Address of remote host
Returns
-1 in case of error or the number of bytes copied in the internal buffer and accepted for transmission.
Implements ns3::Socket.
Definition at line 801 of file udp-socket-impl.cc.
References first::address, ns3::Inet6SocketAddress::ConvertFrom(), ns3::InetSocketAddress::ConvertFrom(), DoSendTo(), ns3::InetSocketAddress::GetIpv4(), ns3::Inet6SocketAddress::GetIpv6(), ns3::InetSocketAddress::GetPort(), ns3::Inet6SocketAddress::GetPort(), ns3::InetSocketAddress::GetTos(), ns3::Inet6SocketAddress::IsMatchingType(), ns3::InetSocketAddress::IsMatchingType(), NS_LOG_FUNCTION, and port.
SetAllowBroadcast()
bool ns3::UdpSocketImpl::SetAllowBroadcast (bool allowBroadcast) virtual
Configure whether broadcast datagram transmissions are allowed.
This method corresponds to using setsockopt() SO_BROADCAST of real network or BSD sockets. If set on a socket, this option will enable or disable packets to be transmitted to broadcast destination addresses.
Parameters
allowBroadcast Whether broadcast is allowed
Returns
true if operation succeeds
Implements ns3::Socket.
Definition at line 1204 of file udp-socket-impl.cc.
References m_allowBroadcast.
SetIpMulticastIf()
void ns3::UdpSocketImpl::SetIpMulticastIf (int32_t ipIf) private virtual
Set the IP multicast interface.
Parameters
ipIf the IP multicast interface
Implements ns3::UdpSocket.
Definition at line 1169 of file udp-socket-impl.cc.
References m_ipMulticastIf.
SetIpMulticastLoop()
void ns3::UdpSocketImpl::SetIpMulticastLoop (bool loop) private virtual
Set the IP multicast loop capability.
This means that the socket will receive the packets sent by itself on a multicast address. Equivalent to setsockopt IP_MULTICAST_LOOP
Parameters
loop the IP multicast loop capability
Implements ns3::UdpSocket.
Definition at line 1181 of file udp-socket-impl.cc.
References m_ipMulticastLoop.
SetIpMulticastTtl()
void ns3::UdpSocketImpl::SetIpMulticastTtl (uint8_t ipTtl) private virtual
Set the IP multicast TTL.
Parameters
ipTtl the IP multicast TTL
Implements ns3::UdpSocket.
Definition at line 1157 of file udp-socket-impl.cc.
References m_ipMulticastTtl.
SetMtuDiscover()
void ns3::UdpSocketImpl::SetMtuDiscover (bool discover) private virtual
Set the MTU discover capability.
Parameters
discover the MTU discover capability
Implements ns3::UdpSocket.
Definition at line 1193 of file udp-socket-impl.cc.
References m_mtuDiscover.
SetNode()
void ns3::UdpSocketImpl::SetNode (Ptr< Node > node)
Set the associated node.
Parameters
node the node
Definition at line 138 of file udp-socket-impl.cc.
References m_node, and NS_LOG_FUNCTION.
SetRcvBufSize()
void ns3::UdpSocketImpl::SetRcvBufSize (uint32_t size) private virtual
Set the receiving buffer size.
Parameters
size the buffer size
Implements ns3::UdpSocket.
Definition at line 1145 of file udp-socket-impl.cc.
References m_rcvBufSize.
SetUdp()
void ns3::UdpSocketImpl::SetUdp (Ptr< UdpL4Protocol > udp)
Set the associated UDP L4 protocol.
Parameters
udp the UDP L4 protocol
Definition at line 145 of file udp-socket-impl.cc.
ShutdownRecv()
int ns3::UdpSocketImpl::ShutdownRecv (void) virtual
Returns
zero on success, -1 on failure.
Do not allow any further Recv calls. This method is typically implemented for Tcp sockets by a half close.
Implements ns3::Socket.
Definition at line 364 of file udp-socket-impl.cc.
References m_endPoint, m_endPoint6, m_shutdownRecv, NS_LOG_FUNCTION, ns3::Ipv4EndPoint::SetRxEnabled(), and ns3::Ipv6EndPoint::SetRxEnabled().
ShutdownSend()
int ns3::UdpSocketImpl::ShutdownSend (void) virtual
Returns
zero on success, -1 on failure.
Do not allow any further Send calls. This method is typically implemented for Tcp sockets by a half close.
Implements ns3::Socket.
Definition at line 356 of file udp-socket-impl.cc.
References m_shutdownSend, and NS_LOG_FUNCTION.
Friends And Related Function Documentation
UdpSocketFactory
friend class UdpSocketFactory friend
UdpSocketFactory friend class.
Definition at line 139 of file udp-socket-impl.h.
Member Data Documentation
m_allowBroadcast
bool ns3::UdpSocketImpl::m_allowBroadcast private
Allow send broadcast packets.
Definition at line 251 of file udp-socket-impl.h.
Referenced by UdpSocketImpl(), DoSendTo(), GetAllowBroadcast(), and SetAllowBroadcast().
m_connected
bool ns3::UdpSocketImpl::m_connected private
Connection established.
Definition at line 250 of file udp-socket-impl.h.
Referenced by Connect(), GetPeerName(), and Send().
m_defaultAddress
Address ns3::UdpSocketImpl::m_defaultAddress private
Default address.
Definition at line 243 of file udp-socket-impl.h.
Referenced by Connect(), DoSend(), and GetPeerName().
m_defaultPort
uint16_t ns3::UdpSocketImpl::m_defaultPort private
Default port.
Definition at line 244 of file udp-socket-impl.h.
Referenced by Connect(), DoSend(), and GetPeerName().
m_deliveryQueue
std::queue<std::pair<Ptr<Packet>, Address> > ns3::UdpSocketImpl::m_deliveryQueue private
Queue for incoming packets.
Definition at line 253 of file udp-socket-impl.h.
Referenced by ForwardUp(), ForwardUp6(), and RecvFrom().
m_dropTrace
TracedCallback<Ptr<const Packet> > ns3::UdpSocketImpl::m_dropTrace private
Trace for dropped packets.
Definition at line 245 of file udp-socket-impl.h.
Referenced by ForwardUp(), ForwardUp6(), and GetTypeId().
m_endPoint
Ipv4EndPoint* ns3::UdpSocketImpl::m_endPoint private
the IPv4 endpoint
Definition at line 236 of file udp-socket-impl.h.
Referenced by ~UdpSocketImpl(), Bind(), BindToNetDevice(), DeallocateEndPoint(), Destroy(), DoSend(), DoSendTo(), FinishBind(), GetSockName(), and ShutdownRecv().
m_endPoint6
Ipv6EndPoint* ns3::UdpSocketImpl::m_endPoint6 private
the IPv6 endpoint
Definition at line 237 of file udp-socket-impl.h.
Referenced by ~UdpSocketImpl(), Bind(), Bind6(), BindToNetDevice(), DeallocateEndPoint(), Destroy6(), DoSend(), DoSendTo(), FinishBind(), GetSockName(), and ShutdownRecv().
m_errno
enum SocketErrno ns3::UdpSocketImpl::m_errno mutable private
Socket error code.
Definition at line 245 of file udp-socket-impl.h.
Referenced by Bind(), Close(), DoSend(), DoSendTo(), GetPeerName(), Listen(), RecvFrom(), and Send().
m_icmpCallback
Callback<void, Ipv4Address,uint8_t,uint8_t,uint8_t,uint32_t> ns3::UdpSocketImpl::m_icmpCallback private
ICMP callback.
Definition at line 240 of file udp-socket-impl.h.
Referenced by ForwardIcmp(), and GetTypeId().
m_icmpCallback6
Callback<void, Ipv6Address,uint8_t,uint8_t,uint8_t,uint32_t> ns3::UdpSocketImpl::m_icmpCallback6 private
ICMPv6 callback.
Definition at line 241 of file udp-socket-impl.h.
Referenced by ForwardIcmp6(), and GetTypeId().
m_ipMulticastIf
int32_t ns3::UdpSocketImpl::m_ipMulticastIf private
Multicast Interface.
Definition at line 259 of file udp-socket-impl.h.
Referenced by GetIpMulticastIf(), and SetIpMulticastIf().
m_ipMulticastLoop
bool ns3::UdpSocketImpl::m_ipMulticastLoop private
Allow multicast loop.
Definition at line 260 of file udp-socket-impl.h.
Referenced by GetIpMulticastLoop(), and SetIpMulticastLoop().
m_ipMulticastTtl
uint8_t ns3::UdpSocketImpl::m_ipMulticastTtl private
Multicast TTL.
Definition at line 258 of file udp-socket-impl.h.
Referenced by DoSendTo(), GetIpMulticastTtl(), and SetIpMulticastTtl().
m_mtuDiscover
bool ns3::UdpSocketImpl::m_mtuDiscover private
Allow MTU discovery.
Definition at line 261 of file udp-socket-impl.h.
Referenced by DoSendTo(), GetMtuDiscover(), and SetMtuDiscover().
m_node
Ptr<Node> ns3::UdpSocketImpl::m_node private
the associated node
Definition at line 238 of file udp-socket-impl.h.
Referenced by ~UdpSocketImpl(), Bind(), BindToNetDevice(), DoSendTo(), GetNode(), Ipv6JoinGroup(), and SetNode().
m_rcvBufSize
uint32_t ns3::UdpSocketImpl::m_rcvBufSize private
Receive buffer size.
Definition at line 257 of file udp-socket-impl.h.
Referenced by ForwardUp(), ForwardUp6(), GetRcvBufSize(), and SetRcvBufSize().
m_rxAvailable
uint32_t ns3::UdpSocketImpl::m_rxAvailable private
Number of available bytes to be received.
Definition at line 254 of file udp-socket-impl.h.
Referenced by ForwardUp(), ForwardUp6(), GetRxAvailable(), and RecvFrom().
m_shutdownRecv
bool ns3::UdpSocketImpl::m_shutdownRecv private
Receive no longer allowed.
Definition at line 249 of file udp-socket-impl.h.
Referenced by Close(), ForwardUp(), ForwardUp6(), and ShutdownRecv().
m_shutdownSend
bool ns3::UdpSocketImpl::m_shutdownSend private
Send no longer allowed.
Definition at line 248 of file udp-socket-impl.h.
Referenced by Close(), DoSend(), DoSendTo(), and ShutdownSend().
m_udp
Ptr<UdpL4Protocol> ns3::UdpSocketImpl::m_udp private
the associated UDP L4 protocol
Definition at line 239 of file udp-socket-impl.h.
Referenced by ~UdpSocketImpl(), Bind(), Bind6(), DeallocateEndPoint(), DoSendTo(), and GetErrno().
The documentation for this class was generated from the following files:
src/internet/model/udp-socket-impl.h
src/internet/model/udp-socket-impl.cc