ns-3: TestDlOfdmaPhyTransmission Class Reference
TestDlOfdmaPhyTransmission Class Reference
Wifi Models » wifi module tests | Test suites
DL-OFDMA PHY test.
Public Member Functions
TestDlOfdmaPhyTransmission ()
virtual ~TestDlOfdmaPhyTransmission ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CheckPhyState (Ptr< OfdmaSpectrumWifiPhy > phy, WifiPhyState expectedState)
Schedule now to check the PHY state.
void CheckResultsSta1 (uint32_t expectedRxSuccess, uint32_t expectedRxFailure, uint32_t expectedRxBytes)
Check the results for STA 1.
void CheckResultsSta2 (uint32_t expectedRxSuccess, uint32_t expectedRxFailure, uint32_t expectedRxBytes)
Check the results for STA 2.
void CheckResultsSta3 (uint32_t expectedRxSuccess, uint32_t expectedRxFailure, uint32_t expectedRxBytes)
Check the results for STA 3.
void DoCheckPhyState (Ptr< OfdmaSpectrumWifiPhy > phy, WifiPhyState expectedState)
Check the PHY state now.
virtual void DoRun (void)
Implementation to actually run this TestCase.
virtual void DoSetup (void)
Implementation to do any local setup required for this TestCase.
void GenerateInterference (Ptr< SpectrumValue > interferencePsd, Time duration)
Generate interference function.
void ResetResults ()
Reset the results.
void RunOne ()
Run one function.
void RxFailureSta1 (Ptr< WifiPsdu > psdu)
Receive failure function for STA 1.
void RxFailureSta2 (Ptr< WifiPsdu > psdu)
Receive failure function for STA 2.
void RxFailureSta3 (Ptr< WifiPsdu > psdu)
Receive failure function for STA 3.
void RxSuccessSta1 (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector, std::vector< bool > statusPerMpdu)
Receive success function for STA 1.
void RxSuccessSta2 (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector, std::vector< bool > statusPerMpdu)
Receive success function for STA 2.
void RxSuccessSta3 (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector, std::vector< bool > statusPerMpdu)
Receive success function for STA 3.
void SendMuPpdu (uint16_t rxStaId1, uint16_t rxStaId2)
Send MU-PPDU function.
void StopInterference (void)
Stop interference function.
Private Attributes
uint16_t m_channelWidth
channel width in MHz
uint32_t m_countRxBytesSta1
count RX bytes for STA 1
uint32_t m_countRxBytesSta2
count RX bytes for STA 2
uint32_t m_countRxBytesSta3
count RX bytes for STA 3
uint32_t m_countRxFailureSta1
count RX failure for STA 1
uint32_t m_countRxFailureSta2
count RX failure for STA 2
uint32_t m_countRxFailureSta3
count RX failure for STA 3
uint32_t m_countRxSuccessSta1
count RX success for STA 1
uint32_t m_countRxSuccessSta2
count RX success for STA 2
uint32_t m_countRxSuccessSta3
count RX success for STA 3
Time m_expectedPpduDuration
expected duration to send MU PPDU
uint16_t m_frequency
frequency in MHz
Ptr< SpectrumWifiPhy > m_phyAp
PHY of AP.
Ptr< WaveformGenerator > m_phyInterferer
PHY of interferer.
Ptr< OfdmaSpectrumWifiPhy > m_phySta1
PHY of STA 1.
Ptr< OfdmaSpectrumWifiPhy > m_phySta2
PHY of STA 2.
Ptr< OfdmaSpectrumWifiPhy > m_phySta3
PHY of STA 3.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
DL-OFDMA PHY test.
Definition at line 92 of file wifi-phy-ofdma-test.cc.
Constructor & Destructor Documentation
TestDlOfdmaPhyTransmission()
TestDlOfdmaPhyTransmission::TestDlOfdmaPhyTransmission ()
Definition at line 227 of file wifi-phy-ofdma-test.cc.
~TestDlOfdmaPhyTransmission()
TestDlOfdmaPhyTransmission::~TestDlOfdmaPhyTransmission () virtual
Definition at line 338 of file wifi-phy-ofdma-test.cc.
References m_phyAp, m_phyInterferer, m_phySta1, m_phySta2, and m_phySta3.
Member Function Documentation
CheckPhyState()
void TestDlOfdmaPhyTransmission::CheckPhyState (Ptr< OfdmaSpectrumWifiPhy > phy, WifiPhyState expectedState) private
Schedule now to check the PHY state.
Parameters
phy the PHY
expectedState the expected state of the PHY
Definition at line 417 of file wifi-phy-ofdma-test.cc.
References DoCheckPhyState(), and third::phy.
Referenced by RunOne().
CheckResultsSta1()
void TestDlOfdmaPhyTransmission::CheckResultsSta1 (uint32_t expectedRxSuccess, uint32_t expectedRxFailure, uint32_t expectedRxBytes) private
Check the results for STA 1.
Parameters
expectedRxSuccess the expected number of RX success
expectedRxFailure the expected number of RX failures
expectedRxBytes the expected number of RX bytes
Definition at line 393 of file wifi-phy-ofdma-test.cc.
References m_countRxBytesSta1, m_countRxFailureSta1, m_countRxSuccessSta1, and NS_TEST_ASSERT_MSG_EQ.
Referenced by RunOne().
CheckResultsSta2()
void TestDlOfdmaPhyTransmission::CheckResultsSta2 (uint32_t expectedRxSuccess, uint32_t expectedRxFailure, uint32_t expectedRxBytes) private
Check the results for STA 2.
Parameters
expectedRxSuccess the expected number of RX success
expectedRxFailure the expected number of RX failures
expectedRxBytes the expected number of RX bytes
Definition at line 401 of file wifi-phy-ofdma-test.cc.
References m_countRxBytesSta2, m_countRxFailureSta2, m_countRxSuccessSta2, and NS_TEST_ASSERT_MSG_EQ.
Referenced by RunOne().
CheckResultsSta3()
void TestDlOfdmaPhyTransmission::CheckResultsSta3 (uint32_t expectedRxSuccess, uint32_t expectedRxFailure, uint32_t expectedRxBytes) private
Check the results for STA 3.
Parameters
expectedRxSuccess the expected number of RX success
expectedRxFailure the expected number of RX failures
expectedRxBytes the expected number of RX bytes
Definition at line 409 of file wifi-phy-ofdma-test.cc.
References m_countRxBytesSta3, m_countRxFailureSta3, m_countRxSuccessSta3, and NS_TEST_ASSERT_MSG_EQ.
Referenced by RunOne().
DoCheckPhyState()
void TestDlOfdmaPhyTransmission::DoCheckPhyState (Ptr< OfdmaSpectrumWifiPhy > phy, WifiPhyState expectedState) private
Check the PHY state now.
Parameters
phy the PHY
expectedState the expected state of the PHY
Definition at line 424 of file wifi-phy-ofdma-test.cc.
References ns3::PointerValue::Get(), ns3::Now(), NS_LOG_FUNCTION, NS_TEST_ASSERT_MSG_EQ, and third::phy.
Referenced by CheckPhyState().
DoRun()
void TestDlOfdmaPhyTransmission::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 700 of file wifi-phy-ofdma-test.cc.
References m_channelWidth, m_expectedPpduDuration, m_frequency, ns3::NanoSeconds(), and RunOne().
DoSetup()
void TestDlOfdmaPhyTransmission::DoSetup (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test setup before DoRun is invoked.
Reimplemented from ns3::TestCase.
Definition at line 436 of file wifi-phy-ofdma-test.cc.
References ns3::Node::AddDevice(), ns3::Object::AggregateObject(), ns3::SpectrumWifiPhy::ConfigureStandardAndBand(), ns3::SpectrumWifiPhy::CreateWifiSpectrumPhyInterface(), m_frequency, m_phyAp, m_phyInterferer, m_phySta1, m_phySta2, m_phySta3, ns3::MakeCallback(), RxFailureSta1(), RxFailureSta2(), RxFailureSta3(), RxSuccessSta1(), RxSuccessSta2(), RxSuccessSta3(), ns3::SpectrumWifiPhy::SetChannel(), ns3::WaveformGenerator::SetChannel(), ns3::WifiPhy::SetDevice(), ns3::WaveformGenerator::SetDevice(), ns3::WaveformGenerator::SetDutyCycle(), ns3::WifiPhy::SetErrorRateModel(), ns3::WifiPhy::SetMobility(), ns3::WifiNetDevice::SetPhy(), ns3::WifiPhy::SetReceiveErrorCallback(), ns3::WifiPhy::SetReceiveOkCallback(), ns3::WIFI_PHY_BAND_5GHZ, and ns3::WIFI_PHY_STANDARD_80211ax.
GenerateInterference()
void TestDlOfdmaPhyTransmission::GenerateInterference (Ptr< SpectrumValue > interferencePsd, Time duration) private
Generate interference function.
Parameters
interferencePsd the PSD of the interference to be generated
duration the duration of the interference
Definition at line 324 of file wifi-phy-ofdma-test.cc.
References m_phyInterferer, ns3::WaveformGenerator::SetPeriod(), ns3::WaveformGenerator::SetTxPowerSpectralDensity(), ns3::WaveformGenerator::Start(), and StopInterference().
Referenced by RunOne().
ResetResults()
void TestDlOfdmaPhyTransmission::ResetResults (void) private
Reset the results.
Definition at line 245 of file wifi-phy-ofdma-test.cc.
References m_countRxBytesSta1, m_countRxBytesSta2, m_countRxBytesSta3, m_countRxFailureSta1, m_countRxFailureSta2, m_countRxFailureSta3, m_countRxSuccessSta1, m_countRxSuccessSta2, and m_countRxSuccessSta3.
Referenced by RunOne().
RunOne()
void TestDlOfdmaPhyTransmission::RunOne (void) private
Run one function.
Definition at line 518 of file wifi-phy-ofdma-test.cc.
References ns3::WifiPhy::AssignStreams(), CCA_BUSY, CheckPhyState(), CheckResultsSta1(), CheckResultsSta2(), CheckResultsSta3(), ns3::BandInfo::fc, ns3::BandInfo::fh, ns3::BandInfo::fl, GenerateInterference(), IDLE, m_channelWidth, m_expectedPpduDuration, m_frequency, m_phyAp, m_phySta1, m_phySta2, m_phySta3, ns3::MicroSeconds(), ns3::MilliSeconds(), ns3::NanoSeconds(), ResetResults(), RX, ns3::Seconds(), SendMuPpdu(), ns3::SpectrumWifiPhy::SetChannelWidth(), and ns3::SpectrumWifiPhy::SetFrequency().
Referenced by DoRun().
RxFailureSta1()
void TestDlOfdmaPhyTransmission::RxFailureSta1 (Ptr< WifiPsdu > psdu) private
Receive failure function for STA 1.
Parameters
psdu the PSDU
Definition at line 372 of file wifi-phy-ofdma-test.cc.
References m_countRxFailureSta1, and NS_LOG_FUNCTION.
Referenced by DoSetup().
RxFailureSta2()
void TestDlOfdmaPhyTransmission::RxFailureSta2 (Ptr< WifiPsdu > psdu) private
Receive failure function for STA 2.
Parameters
psdu the PSDU
Definition at line 379 of file wifi-phy-ofdma-test.cc.
References m_countRxFailureSta2, and NS_LOG_FUNCTION.
Referenced by DoSetup().
RxFailureSta3()
void TestDlOfdmaPhyTransmission::RxFailureSta3 (Ptr< WifiPsdu > psdu) private
Receive failure function for STA 3.
Parameters
psdu the PSDU
Definition at line 386 of file wifi-phy-ofdma-test.cc.
References m_countRxFailureSta3, and NS_LOG_FUNCTION.
Referenced by DoSetup().
RxSuccessSta1()
void TestDlOfdmaPhyTransmission::RxSuccessSta1 (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector, std::vector< bool > statusPerMpdu) private
Receive success function for STA 1.
Parameters
psdu the PSDU
snr the SNR
txVector the transmit vector
statusPerMpdu reception status per MPDU
Definition at line 348 of file wifi-phy-ofdma-test.cc.
References m_countRxBytesSta1, m_countRxSuccessSta1, and NS_LOG_FUNCTION.
Referenced by DoSetup().
RxSuccessSta2()
void TestDlOfdmaPhyTransmission::RxSuccessSta2 (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector, std::vector< bool > statusPerMpdu) private
Receive success function for STA 2.
Parameters
psdu the PSDU
snr the SNR
txVector the transmit vector
statusPerMpdu reception status per MPDU
Definition at line 356 of file wifi-phy-ofdma-test.cc.
References m_countRxBytesSta2, m_countRxSuccessSta2, and NS_LOG_FUNCTION.
Referenced by DoSetup().
RxSuccessSta3()
void TestDlOfdmaPhyTransmission::RxSuccessSta3 (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector, std::vector< bool > statusPerMpdu) private
Receive success function for STA 3.
Parameters
psdu the PSDU
snr the SNR
txVector the transmit vector
statusPerMpdu reception status per MPDU
Definition at line 364 of file wifi-phy-ofdma-test.cc.
References m_countRxBytesSta3, m_countRxSuccessSta3, and NS_LOG_FUNCTION.
Referenced by DoSetup().
SendMuPpdu()
void TestDlOfdmaPhyTransmission::SendMuPpdu (uint16_t rxStaId1, uint16_t rxStaId2) private
Send MU-PPDU function.
Parameters
rxStaId1 the ID of the recipient STA for the first PSDU
rxStaId2 the ID of the recipient STA for the second PSDU
Definition at line 259 of file wifi-phy-ofdma-test.cc.
References ns3::HeRu::RuSpec::index, m_channelWidth, m_phyAp, NS_ASSERT_MSG, NS_LOG_FUNCTION, ns3::HeRu::RuSpec::primary80MHz, ns3::HeRu::RuSpec::ruType, ns3::WifiPhy::Send(), ns3::WifiMacHeader::SetAddr1(), ns3::WifiTxVector::SetMode(), ns3::WifiTxVector::SetNss(), ns3::WifiMacHeader::SetQosTid(), ns3::WifiTxVector::SetRu(), ns3::WifiMacHeader::SetSequenceNumber(), ns3::WifiMacHeader::SetType(), ns3::WIFI_MAC_QOSDATA, and ns3::WIFI_PREAMBLE_HE_MU.
Referenced by RunOne().
StopInterference()
void TestDlOfdmaPhyTransmission::StopInterference (void) private
Stop interference function.
Definition at line 333 of file wifi-phy-ofdma-test.cc.
References m_phyInterferer, and ns3::WaveformGenerator::Stop().
Referenced by GenerateInterference().
Member Data Documentation
m_channelWidth
uint16_t TestDlOfdmaPhyTransmission::m_channelWidth private
channel width in MHz
Definition at line 223 of file wifi-phy-ofdma-test.cc.
Referenced by DoRun(), RunOne(), and SendMuPpdu().
m_countRxBytesSta1
uint32_t TestDlOfdmaPhyTransmission::m_countRxBytesSta1 private
count RX bytes for STA 1
Definition at line 212 of file wifi-phy-ofdma-test.cc.
Referenced by CheckResultsSta1(), ResetResults(), and RxSuccessSta1().
m_countRxBytesSta2
uint32_t TestDlOfdmaPhyTransmission::m_countRxBytesSta2 private
count RX bytes for STA 2
Definition at line 213 of file wifi-phy-ofdma-test.cc.
Referenced by CheckResultsSta2(), ResetResults(), and RxSuccessSta2().
m_countRxBytesSta3
uint32_t TestDlOfdmaPhyTransmission::m_countRxBytesSta3 private
count RX bytes for STA 3
Definition at line 214 of file wifi-phy-ofdma-test.cc.
Referenced by CheckResultsSta3(), ResetResults(), and RxSuccessSta3().
m_countRxFailureSta1
uint32_t TestDlOfdmaPhyTransmission::m_countRxFailureSta1 private
count RX failure for STA 1
Definition at line 209 of file wifi-phy-ofdma-test.cc.
Referenced by CheckResultsSta1(), ResetResults(), and RxFailureSta1().
m_countRxFailureSta2
uint32_t TestDlOfdmaPhyTransmission::m_countRxFailureSta2 private
count RX failure for STA 2
Definition at line 210 of file wifi-phy-ofdma-test.cc.
Referenced by CheckResultsSta2(), ResetResults(), and RxFailureSta2().
m_countRxFailureSta3
uint32_t TestDlOfdmaPhyTransmission::m_countRxFailureSta3 private
count RX failure for STA 3
Definition at line 211 of file wifi-phy-ofdma-test.cc.
Referenced by CheckResultsSta3(), ResetResults(), and RxFailureSta3().
m_countRxSuccessSta1
uint32_t TestDlOfdmaPhyTransmission::m_countRxSuccessSta1 private
count RX success for STA 1
Definition at line 206 of file wifi-phy-ofdma-test.cc.
Referenced by CheckResultsSta1(), ResetResults(), and RxSuccessSta1().
m_countRxSuccessSta2
uint32_t TestDlOfdmaPhyTransmission::m_countRxSuccessSta2 private
count RX success for STA 2
Definition at line 207 of file wifi-phy-ofdma-test.cc.
Referenced by CheckResultsSta2(), ResetResults(), and RxSuccessSta2().
m_countRxSuccessSta3
uint32_t TestDlOfdmaPhyTransmission::m_countRxSuccessSta3 private
count RX success for STA 3
Definition at line 208 of file wifi-phy-ofdma-test.cc.
Referenced by CheckResultsSta3(), ResetResults(), and RxSuccessSta3().
m_expectedPpduDuration
Time TestDlOfdmaPhyTransmission::m_expectedPpduDuration private
expected duration to send MU PPDU
Definition at line 224 of file wifi-phy-ofdma-test.cc.
Referenced by DoRun(), and RunOne().
m_frequency
uint16_t TestDlOfdmaPhyTransmission::m_frequency private
frequency in MHz
Definition at line 222 of file wifi-phy-ofdma-test.cc.
Referenced by DoRun(), DoSetup(), and RunOne().
m_phyAp
Ptr<SpectrumWifiPhy> TestDlOfdmaPhyTransmission::m_phyAp private
PHY of AP.
Definition at line 216 of file wifi-phy-ofdma-test.cc.
Referenced by ~TestDlOfdmaPhyTransmission(), DoSetup(), RunOne(), and SendMuPpdu().
m_phyInterferer
Ptr<WaveformGenerator> TestDlOfdmaPhyTransmission::m_phyInterferer private
PHY of interferer.
Definition at line 220 of file wifi-phy-ofdma-test.cc.
Referenced by ~TestDlOfdmaPhyTransmission(), DoSetup(), GenerateInterference(), and StopInterference().
m_phySta1
Ptr<OfdmaSpectrumWifiPhy> TestDlOfdmaPhyTransmission::m_phySta1 private
PHY of STA 1.
Definition at line 217 of file wifi-phy-ofdma-test.cc.
Referenced by ~TestDlOfdmaPhyTransmission(), DoSetup(), and RunOne().
m_phySta2
Ptr<OfdmaSpectrumWifiPhy> TestDlOfdmaPhyTransmission::m_phySta2 private
PHY of STA 2.
Definition at line 218 of file wifi-phy-ofdma-test.cc.
Referenced by ~TestDlOfdmaPhyTransmission(), DoSetup(), and RunOne().
m_phySta3
Ptr<OfdmaSpectrumWifiPhy> TestDlOfdmaPhyTransmission::m_phySta3 private
PHY of STA 3.
Definition at line 219 of file wifi-phy-ofdma-test.cc.
Referenced by ~TestDlOfdmaPhyTransmission(), DoSetup(), and RunOne().
The documentation for this class was generated from the following file:
src/wifi/test/wifi-phy-ofdma-test.cc