ns-3: WifiPhyThresholdsStrongWifiSignalTest Class Reference
WifiPhyThresholdsStrongWifiSignalTest Class Reference
Wifi Models » wifi module tests | Test suites
Wifi Phy Threshold Strong Wifi Signal Test.
Public Member Functions
WifiPhyThresholdsStrongWifiSignalTest ()
virtual ~WifiPhyThresholdsStrongWifiSignalTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from WifiPhyThresholdsTest
WifiPhyThresholdsTest (std::string test_name)
Constructor.
virtual ~WifiPhyThresholdsTest ()
Destructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from WifiPhyThresholdsTest
virtual Ptr< SpectrumSignalParameters > MakeForeignSignal (double txPowerWatts)
Make foreign signal function.
virtual Ptr< SpectrumSignalParameters > MakeWifiSignal (double txPowerWatts)
Make wifi signal function.
virtual void PhyStateChanged (Time start, Time duration, WifiPhyState newState)
PHY state changed callback function.
void RxDropped (Ptr< const Packet > p, WifiPhyRxfailureReason reason)
PHY dropped packet callback function.
virtual void RxFailure (Ptr< WifiPsdu > psdu)
PHY receive failure callback function.
virtual void RxSuccess (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector, std::vector< bool > statusPerMpdu)
PHY receive success callback function.
virtual void SendSignal (double txPowerWatts, bool wifiSignal)
Send signal function.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Protected Attributes inherited from WifiPhyThresholdsTest
uint32_t m_ccabusyStateCount
count number of PHY state change to CCA_BUSY state
uint32_t m_idleStateCount
count number of PHY state change to IDLE state
Ptr< SpectrumWifiPhy > m_phy
PHY object.
uint32_t m_rxDropped
count number of dropped packets
uint32_t m_rxFailure
count number of unsuccessfully received packets
uint32_t m_rxStateCount
count number of PHY state change to RX state
uint32_t m_rxSuccess
count number of successfully received packets
uint32_t m_stateChanged
count number of PHY state change
Detailed Description
Wifi Phy Threshold Strong Wifi Signal Test.
This test makes sure PHY processes a Wi-Fi signal with a received power higher than RxSensitivity.
Definition at line 329 of file wifi-phy-thresholds-test.cc.
Constructor & Destructor Documentation
WifiPhyThresholdsStrongWifiSignalTest()
WifiPhyThresholdsStrongWifiSignalTest::WifiPhyThresholdsStrongWifiSignalTest ()
Definition at line 337 of file wifi-phy-thresholds-test.cc.
~WifiPhyThresholdsStrongWifiSignalTest()
WifiPhyThresholdsStrongWifiSignalTest::~WifiPhyThresholdsStrongWifiSignalTest () virtual
Definition at line 342 of file wifi-phy-thresholds-test.cc.
Member Function Documentation
DoRun()
void WifiPhyThresholdsStrongWifiSignalTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 347 of file wifi-phy-thresholds-test.cc.
References ns3::DbmToW(), WifiPhyThresholdsTest::m_ccabusyStateCount, WifiPhyThresholdsTest::m_idleStateCount, WifiPhyThresholdsTest::m_rxDropped, WifiPhyThresholdsTest::m_rxFailure, WifiPhyThresholdsTest::m_rxStateCount, WifiPhyThresholdsTest::m_rxSuccess, WifiPhyThresholdsTest::m_stateChanged, NS_TEST_ASSERT_MSG_EQ, ns3::Seconds(), and WifiPhyThresholdsTest::SendSignal().
The documentation for this class was generated from the following file:
src/wifi/test/wifi-phy-thresholds-test.cc