ns-3: ns3::Ipv6StaticRoutingHelper Class Reference
ns3::Ipv6StaticRoutingHelper Class Reference
Internet » IPv6 Helper classes
Helper class that adds ns3::Ipv6StaticRouting objects.
#include "ipv6-static-routing-helper.h"
Public Member Functions
Ipv6StaticRoutingHelper ()
Constructor.
Ipv6StaticRoutingHelper (const Ipv6StaticRoutingHelper &)
Construct an Ipv6ListRoutingHelper from another previously initialized instance (Copy Constructor).
void AddMulticastRoute (Ptr< Node > n, Ipv6Address source, Ipv6Address group, Ptr< NetDevice > input, NetDeviceContainer output)
Add a multicast route to a node and net device using explicit Ptr<Node> and Ptr<NetDevice>
void AddMulticastRoute (Ptr< Node > n, Ipv6Address source, Ipv6Address group, std::string inputName, NetDeviceContainer output)
Add a multicast route to a node and device using a Ptr<Node> and a name string previously associated to the device using the Object Name Service.
void AddMulticastRoute (std::string n, Ipv6Address source, Ipv6Address group, Ptr< NetDevice > input, NetDeviceContainer output)
Add a multicast route to a node and device using a name string previously associated to the node using the Object Name Service and a Ptr<NetDevice>
void AddMulticastRoute (std::string nName, Ipv6Address source, Ipv6Address group, std::string inputName, NetDeviceContainer output)
Add a multicast route to a node and device using name strings previously associated to both the node and device using the Object Name Service.
Ipv6StaticRoutingHelper * Copy (void) const
virtual Ptr< Ipv6RoutingProtocol > Create (Ptr< Node > node) const
Ptr< Ipv6StaticRouting > GetStaticRouting (Ptr< Ipv6 > ipv6) const
Get Ipv6StaticRouting pointer from IPv6 stack.
Public Member Functions inherited from ns3::Ipv6RoutingHelper
virtual ~Ipv6RoutingHelper ()
Destroy an Ipv6 Ipv6RoutingHelper.
Private Member Functions
Ipv6StaticRoutingHelper & operator= (const Ipv6StaticRoutingHelper &o)
Assignment operator declared private and not implemented to disallow assignment and prevent the compiler from happily inserting its own.
Additional Inherited Members
Static Public Member Functions inherited from ns3::Ipv6RoutingHelper
template<class T >
static Ptr< T > GetRouting (Ptr< Ipv6RoutingProtocol > protocol)
Request a specified routing protocol <T> from Ipv6RoutingProtocol protocol.
static void PrintNeighborCacheAllAt (Time printTime, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the neighbor cache of all nodes at a particular time.
static void PrintNeighborCacheAllEvery (Time printInterval, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the neighbor cache of all nodes at regular intervals specified by user.
static void PrintNeighborCacheAt (Time printTime, Ptr< Node > node, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the neighbor cache of a node at a particular time.
static void PrintNeighborCacheEvery (Time printInterval, Ptr< Node > node, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the neighbor cache of a node at regular intervals specified by user.
static void PrintRoutingTableAllAt (Time printTime, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of all nodes at a particular time.
static void PrintRoutingTableAllEvery (Time printInterval, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of all nodes at regular intervals specified by user.
static void PrintRoutingTableAt (Time printTime, Ptr< Node > node, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of a node at a particular time.
static void PrintRoutingTableEvery (Time printInterval, Ptr< Node > node, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of a node at regular intervals specified by user.
Detailed Description
Helper class that adds ns3::Ipv6StaticRouting objects.
This class is expected to be used in conjunction with ns3::InternetStackHelper::SetRoutingHelper
Definition at line 43 of file ipv6-static-routing-helper.h.
Constructor & Destructor Documentation
Ipv6StaticRoutingHelper() [1/2]
ns3::Ipv6StaticRoutingHelper::Ipv6StaticRoutingHelper ()
Constructor.
Definition at line 38 of file ipv6-static-routing-helper.cc.
Referenced by Copy().
Ipv6StaticRoutingHelper() [2/2]
ns3::Ipv6StaticRoutingHelper::Ipv6StaticRoutingHelper (const Ipv6StaticRoutingHelper & o)
Construct an Ipv6ListRoutingHelper from another previously initialized instance (Copy Constructor).
Definition at line 42 of file ipv6-static-routing-helper.cc.
Member Function Documentation
AddMulticastRoute() [1/4]
void ns3::Ipv6StaticRoutingHelper::AddMulticastRoute (Ptr< Node > n, Ipv6Address source, Ipv6Address group, Ptr< NetDevice > input, NetDeviceContainer output)
Add a multicast route to a node and net device using explicit Ptr<Node> and Ptr<NetDevice>
Parameters
n The node.
source Source address.
group Multicast group.
input Input NetDevice.
output Output NetDevices.
Definition at line 89 of file ipv6-static-routing-helper.cc.
References ns3::NetDeviceContainer::Begin(), ns3::NetDeviceContainer::End(), GetStaticRouting(), sample-rng-plot::n, and NS_ASSERT_MSG.
Referenced by AddMulticastRoute().
AddMulticastRoute() [2/4]
void ns3::Ipv6StaticRoutingHelper::AddMulticastRoute (Ptr< Node > n, Ipv6Address source, Ipv6Address group, std::string inputName, NetDeviceContainer output)
Add a multicast route to a node and device using a Ptr<Node> and a name string previously associated to the device using the Object Name Service.
Parameters
n The node.
source Source address.
group Multicast group.
inputName Input NetDevice.
output Output NetDevices.
Definition at line 127 of file ipv6-static-routing-helper.cc.
References AddMulticastRoute(), and sample-rng-plot::n.
AddMulticastRoute() [3/4]
void ns3::Ipv6StaticRoutingHelper::AddMulticastRoute (std::string n, Ipv6Address source, Ipv6Address group, Ptr< NetDevice > input, NetDeviceContainer output)
Add a multicast route to a node and device using a name string previously associated to the node using the Object Name Service and a Ptr<NetDevice>
Parameters
n The node.
source Source address.
group Multicast group.
input Input NetDevice.
output Output NetDevices.
Definition at line 139 of file ipv6-static-routing-helper.cc.
References AddMulticastRoute(), and sample-rng-plot::n.
AddMulticastRoute() [4/4]
void ns3::Ipv6StaticRoutingHelper::AddMulticastRoute (std::string nName, Ipv6Address source, Ipv6Address group, std::string inputName, NetDeviceContainer output)
Add a multicast route to a node and device using name strings previously associated to both the node and device using the Object Name Service.
Parameters
nName The node.
source Source address.
group Multicast group.
inputName Input NetDevice.
output Output NetDevices.
Definition at line 151 of file ipv6-static-routing-helper.cc.
References AddMulticastRoute(), and sample-rng-plot::n.
Copy()
Ipv6StaticRoutingHelper * ns3::Ipv6StaticRoutingHelper::Copy (void) const virtual
Returns
pointer to clone of this Ipv6StaticRoutingHelper
This method is mainly for internal use by the other helpers; clients are expected to free the dynamic memory allocated by this method
Implements ns3::Ipv6RoutingHelper.
Definition at line 47 of file ipv6-static-routing-helper.cc.
References Ipv6StaticRoutingHelper().
Create()
Ptr< Ipv6RoutingProtocol > ns3::Ipv6StaticRoutingHelper::Create (Ptr< Node > node) const virtual
Parameters
node the node on which the routing protocol will run
Returns
a newly-created routing protocol
This method will be called by ns3::InternetStackHelper::Install
Implements ns3::Ipv6RoutingHelper.
Definition at line 53 of file ipv6-static-routing-helper.cc.
GetStaticRouting()
Ptr< Ipv6StaticRouting > ns3::Ipv6StaticRoutingHelper::GetStaticRouting (Ptr< Ipv6 > ipv6) const
Get Ipv6StaticRouting pointer from IPv6 stack.
Parameters
ipv6 Ipv6 pointer
Returns
Ipv6StaticRouting pointer or 0 if not found
Definition at line 59 of file ipv6-static-routing-helper.cc.
References NS_ASSERT_MSG, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by ns3::NoBackhaulEpcHelper::NoBackhaulEpcHelper(), AddMulticastRoute(), LteIpv6RoutingTestCase::DoRun(), StackHelper::PrintRoutingTable(), ns3::Ipv6InterfaceContainer::SetDefaultRoute(), and ns3::Ipv6InterfaceContainer::SetDefaultRouteInAllNodes().
operator=()
Ipv6StaticRoutingHelper& ns3::Ipv6StaticRoutingHelper::operator= (const Ipv6StaticRoutingHelper & o) private
Assignment operator declared private and not implemented to disallow assignment and prevent the compiler from happily inserting its own.
Parameters
o object to copy from
Returns
a reference to the new object
The documentation for this class was generated from the following files:
src/internet/helper/ipv6-static-routing-helper.h
src/internet/helper/ipv6-static-routing-helper.cc