ns-3: ns3::LteAmc Class Reference
ns3::LteAmc Class Reference
LTE Models
Implements the Adaptive Modulation And Coding Scheme.
#include "lte-amc.h"
Public Types
enum AmcModel { PiroEW2010 , MiErrorModel }
Types of AMC model.
Public Member Functions
LteAmc ()
virtual ~LteAmc ()
std::vector< int > CreateCqiFeedbacks (const SpectrumValue &sinr, uint8_t rbgSize=0)
Create a message with CQI feedback.
int GetCqiFromSpectralEfficiency (double s)
Get a proper CQI for the spectral efficiency value.
int GetDlTbSizeFromMcs (int mcs, int nprb)
Get the Transport Block Size for a selected MCS and number of PRB (table 7.1.7.2.1-1 of 36.213)
int GetMcsFromCqi (int cqi)
Get the Modulation and Coding Scheme for a CQI value.
double GetSpectralEfficiencyFromCqi (int cqi)
Get the spectral efficiency value associated to the received CQI.
int GetUlTbSizeFromMcs (int mcs, int nprb)
Get the Transport Block Size for a selected MCS and number of PRB (table 8.6.1-1 of 36.213)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
AmcModel m_amcModel
The AmcModel attribute.
double m_ber
The Ber attribute.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implements the Adaptive Modulation And Coding Scheme.
Introspection did not find any typical Config paths.
As proposed in 3GPP TSG-RAN WG1 R1-081483 Conveying MCS and TB size via PDCCH.
Attributes
Ber: The requested BER in assigning MCS (default is 0.00005).
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 5e-05
Flags: construct write read
AmcModel: AMC model used to assign CQI
Set with class: ns3::EnumValue
Underlying type:
Initial value: Vienna
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 48 bytes (on a 64-bit architecture).
Definition at line 40 of file lte-amc.h.
Member Enumeration Documentation
AmcModel
enum ns3::LteAmc::AmcModel
Types of AMC model.
Enumerator
PiroEW2010
An AMC model based on Piro, G.; Grieco, L.A; Boggia, G.; Camarda, P., "A two-level scheduling algorithm for QoS support in the downlink of LTE cellular networks," Wireless Conference (EW), 2010 European, pp.246,253, 12-15 April 2010.
MiErrorModel
An AMC model based on 10% of BER according to LteMiErrorModel.
Definition at line 54 of file lte-amc.h.
Constructor & Destructor Documentation
LteAmc()
ns3::LteAmc::LteAmc ()
Definition at line 233 of file lte-amc.cc.
~LteAmc()
ns3::LteAmc::~LteAmc () virtual
Definition at line 238 of file lte-amc.cc.
Member Function Documentation
CreateCqiFeedbacks()
std::vector< int > ns3::LteAmc::CreateCqiFeedbacks (const SpectrumValue & sinr, uint8_t rbgSize = 0)
Create a message with CQI feedback.
Parameters
sinr the SpectrumValue vector of SINR for evaluating the CQI
rbgSize size of RB group (in RBs) for evaluating subband/wideband CQI
Returns
a vector of CQI feedbacks
Definition at line 330 of file lte-amc.cc.
References ns3::SpectrumValue::ConstValuesBegin(), ns3::SpectrumValue::ConstValuesEnd(), NS_ASSERT_MSG, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::SpectralEfficiencyForCqi, ns3::SpectralEfficiencyForMcs, and ns3::TbStats_t::tbler.
GetCqiFromSpectralEfficiency()
int ns3::LteAmc::GetCqiFromSpectralEfficiency (double s)
Get a proper CQI for the spectral efficiency value.
In order to assure a lower block error rate, the AMC chooses the lower CQI value for a given spectral efficiency
Parameters
s the spectral efficiency
Returns
the CQI value
Definition at line 265 of file lte-amc.cc.
References NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, and ns3::SpectralEfficiencyForCqi.
GetDlTbSizeFromMcs()
int ns3::LteAmc::GetDlTbSizeFromMcs (int mcs, int nprb)
Get the Transport Block Size for a selected MCS and number of PRB (table 7.1.7.2.1-1 of 36.213)
Parameters
mcs the MCS index
nprb the no. of PRB
Returns
the Transport Block Size in bits
Definition at line 295 of file lte-amc.cc.
References ns3::McsToItbsDl, NS_ASSERT_MSG, NS_LOG_FUNCTION, and ns3::TransportBlockSizeTable.
GetMcsFromCqi()
int ns3::LteAmc::GetMcsFromCqi (int cqi)
Get the Modulation and Coding Scheme for a CQI value.
Parameters
cqi the cqi value
Returns
the MCS value
Definition at line 280 of file lte-amc.cc.
References NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::SpectralEfficiencyForCqi, and ns3::SpectralEfficiencyForMcs.
GetSpectralEfficiencyFromCqi()
double ns3::LteAmc::GetSpectralEfficiencyFromCqi (int cqi)
Get the spectral efficiency value associated to the received CQI.
Parameters
cqi the cqi value
Returns
the spectral efficiency in (bit/s)/Hz
Definition at line 320 of file lte-amc.cc.
References NS_ASSERT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, and ns3::SpectralEfficiencyForCqi.
GetTypeId()
TypeId ns3::LteAmc::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 243 of file lte-amc.cc.
References ns3::MakeDoubleAccessor(), ns3::MakeEnumAccessor(), ns3::MakeEnumChecker(), and ns3::TypeId::SetParent().
GetUlTbSizeFromMcs()
int ns3::LteAmc::GetUlTbSizeFromMcs (int mcs, int nprb)
Get the Transport Block Size for a selected MCS and number of PRB (table 8.6.1-1 of 36.213)
Parameters
mcs the MCS index
nprb the no. of PRB
Returns
the Transport Block Size in bits
Definition at line 307 of file lte-amc.cc.
References ns3::McsToItbsUl, NS_ASSERT_MSG, NS_LOG_FUNCTION, and ns3::TransportBlockSizeTable.
Member Data Documentation
m_amcModel
AmcModel ns3::LteAmc::m_amcModel private
The AmcModel attribute.
AMC model used to assign CQI.
Definition at line 134 of file lte-amc.h.
m_ber
double ns3::LteAmc::m_ber private
The Ber attribute.
The requested BER in assigning MCS (default is 0.00005).
Definition at line 127 of file lte-amc.h.
The documentation for this class was generated from the following files:
src/lte/model/lte-amc.h
src/lte/model/lte-amc.cc