ns-3: ns3::aodv::RoutingTable Class Reference
ns3::aodv::RoutingTable Class Reference
AODV Routing
The Routing table used by AODV protocol.
#include "aodv-rtable.h"
Public Member Functions
RoutingTable (Time t)
constructor
Handle lifetime of invalid route
std::map< Ipv4Address, RoutingTableEntry > m_ipv4AddressEntry
The routing table.
Time m_badLinkLifetime
Deletion time for invalid routes.
Time GetBadLinkLifetime () const
The routing table.
void SetBadLinkLifetime (Time t)
The routing table.
bool AddRoute (RoutingTableEntry &r)
Add routing table entry if it doesn't yet exist in routing table.
bool DeleteRoute (Ipv4Address dst)
Delete routing table entry with destination address dst, if it exists.
bool LookupRoute (Ipv4Address dst, RoutingTableEntry &rt)
Lookup routing table entry with destination address dst.
bool LookupValidRoute (Ipv4Address dst, RoutingTableEntry &rt)
Lookup route in VALID state.
bool Update (RoutingTableEntry &rt)
Update routing table.
bool SetEntryState (Ipv4Address dst, RouteFlags state)
Set routing table entry flags.
void GetListOfDestinationWithNextHop (Ipv4Address nextHop, std::map< Ipv4Address, uint32_t > &unreachable)
Lookup routing entries with next hop Address dst and not empty list of precursors.
void InvalidateRoutesWithDst (std::map< Ipv4Address, uint32_t > const &unreachable)
Update routing entries with this destination as follows:
void DeleteAllRoutesFromInterface (Ipv4InterfaceAddress iface)
Delete all route from interface with address iface.
void Clear ()
Delete all entries from routing table.
void Purge ()
Delete all outdated entries and invalidate valid entry if Lifetime is expired.
bool MarkLinkAsUnidirectional (Ipv4Address neighbor, Time blacklistTimeout)
Mark entry as unidirectional (e.g.
void Print (Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S) const
Print routing table.
void Purge (std::map< Ipv4Address, RoutingTableEntry > &table) const
const version of Purge, for use by Print() method
Detailed Description
The Routing table used by AODV protocol.
Definition at line 388 of file aodv-rtable.h.
Constructor & Destructor Documentation
RoutingTable()
ns3::aodv::RoutingTable::RoutingTable (Time t)
constructor
Parameters
t the routing table entry lifetime
Definition at line 208 of file aodv-rtable.cc.
Member Function Documentation
AddRoute()
bool ns3::aodv::RoutingTable::AddRoute (RoutingTableEntry & r)
Add routing table entry if it doesn't yet exist in routing table.
Parameters
r routing table entry
Returns
true in success
Definition at line 263 of file aodv-rtable.cc.
References ns3::aodv::RoutingTableEntry::GetDestination(), ns3::aodv::RoutingTableEntry::GetFlag(), ns3::aodv::IN_SEARCH, m_ipv4AddressEntry, NS_LOG_FUNCTION, Purge(), and ns3::aodv::RoutingTableEntry::SetRreqCnt().
Referenced by ns3::aodv::AodvRtableTest::DoRun(), ns3::aodv::RoutingProtocol::NotifyAddAddress(), ns3::aodv::RoutingProtocol::NotifyInterfaceUp(), ns3::aodv::RoutingProtocol::NotifyRemoveAddress(), ns3::aodv::RoutingProtocol::ProcessHello(), ns3::aodv::RoutingProtocol::RecvReply(), ns3::aodv::RoutingProtocol::RecvRequest(), ns3::aodv::RoutingProtocol::SendRequest(), ns3::aodv::RoutingProtocol::SetIpv4(), and ns3::aodv::RoutingProtocol::UpdateRouteToNeighbor().
Clear()
void ns3::aodv::RoutingTable::Clear () inline
Delete all entries from routing table.
Definition at line 468 of file aodv-rtable.h.
References m_ipv4AddressEntry.
Referenced by ns3::aodv::RoutingProtocol::NotifyInterfaceDown(), and ns3::aodv::RoutingProtocol::NotifyRemoveAddress().
DeleteAllRoutesFromInterface()
void ns3::aodv::RoutingTable::DeleteAllRoutesFromInterface (Ipv4InterfaceAddress iface)
Delete all route from interface with address iface.
Parameters
iface the interface IP address
Definition at line 351 of file aodv-rtable.cc.
References m_ipv4AddressEntry, and NS_LOG_FUNCTION.
Referenced by ns3::aodv::RoutingProtocol::NotifyInterfaceDown(), and ns3::aodv::RoutingProtocol::NotifyRemoveAddress().
DeleteRoute()
bool ns3::aodv::RoutingTable::DeleteRoute (Ipv4Address dst)
Delete routing table entry with destination address dst, if it exists.
Parameters
dst destination address
Returns
true on success
Definition at line 249 of file aodv-rtable.cc.
References m_ipv4AddressEntry, NS_LOG_FUNCTION, NS_LOG_LOGIC, and Purge().
Referenced by ns3::aodv::AodvRtableTest::DoRun(), and ns3::aodv::RoutingProtocol::RouteRequestTimerExpire().
GetBadLinkLifetime()
Time ns3::aodv::RoutingTable::GetBadLinkLifetime () const inline
The routing table.
Definition at line 398 of file aodv-rtable.h.
References m_badLinkLifetime.
Referenced by ns3::aodv::AodvRtableTest::DoRun().
GetListOfDestinationWithNextHop()
void ns3::aodv::RoutingTable::GetListOfDestinationWithNextHop (Ipv4Address nextHop, std::map< Ipv4Address, uint32_t > & unreachable)
Lookup routing entries with next hop Address dst and not empty list of precursors.
Parameters
nextHop the next hop IP address
unreachable
Definition at line 314 of file aodv-rtable.cc.
References m_ipv4AddressEntry, NS_LOG_FUNCTION, NS_LOG_LOGIC, and Purge().
Referenced by ns3::aodv::AodvRtableTest::DoRun(), ns3::aodv::RoutingProtocol::RecvError(), and ns3::aodv::RoutingProtocol::SendRerrWhenBreaksLinkToNextHop().
InvalidateRoutesWithDst()
void ns3::aodv::RoutingTable::InvalidateRoutesWithDst (std::map< Ipv4Address, uint32_t > const & unreachable)
Update routing entries with this destination as follows:
The destination sequence number of this routing entry, if it exists and is valid, is incremented.
The entry is invalidated by marking the route entry as invalid
The Lifetime field is updated to current time plus DELETE_PERIOD.
Parameters
unreachable routes to invalidate
Definition at line 331 of file aodv-rtable.cc.
References m_badLinkLifetime, m_ipv4AddressEntry, NS_LOG_FUNCTION, NS_LOG_LOGIC, Purge(), and ns3::aodv::VALID.
Referenced by ns3::aodv::AodvRtableTest::DoRun(), ns3::aodv::RoutingProtocol::RecvError(), and ns3::aodv::RoutingProtocol::SendRerrWhenBreaksLinkToNextHop().
LookupRoute()
bool ns3::aodv::RoutingTable::LookupRoute (Ipv4Address dst, RoutingTableEntry & rt)
Lookup routing table entry with destination address dst.
Parameters
dst destination address
rt entry with destination address dst, if exists
Returns
true on success
Definition at line 214 of file aodv-rtable.cc.
References m_ipv4AddressEntry, NS_LOG_FUNCTION, NS_LOG_LOGIC, and Purge().
Referenced by ns3::aodv::RoutingProtocol::DeferredRouteOutput(), ns3::aodv::AodvRtableTest::DoRun(), ns3::aodv::RoutingProtocol::Forwarding(), LookupValidRoute(), ns3::aodv::RoutingProtocol::ProcessHello(), ns3::aodv::RoutingProtocol::RecvError(), ns3::aodv::RoutingProtocol::RecvReply(), ns3::aodv::RoutingProtocol::RecvReplyAck(), ns3::aodv::RoutingProtocol::RecvRequest(), ns3::aodv::RoutingProtocol::RouteInput(), ns3::aodv::RoutingProtocol::ScheduleRreqRetry(), ns3::aodv::RoutingProtocol::SendReplyAck(), ns3::aodv::RoutingProtocol::SendReplyByIntermediateNode(), ns3::aodv::RoutingProtocol::SendRequest(), ns3::aodv::RoutingProtocol::SendRerrWhenBreaksLinkToNextHop(), ns3::aodv::RoutingProtocol::UpdateRouteLifeTime(), and ns3::aodv::RoutingProtocol::UpdateRouteToNeighbor().
LookupValidRoute()
bool ns3::aodv::RoutingTable::LookupValidRoute (Ipv4Address dst, RoutingTableEntry & rt)
Lookup route in VALID state.
Parameters
dst destination address
rt entry with destination address dst, if exists
Returns
true on success
Definition at line 236 of file aodv-rtable.cc.
References ns3::aodv::RoutingTableEntry::GetFlag(), LookupRoute(), NS_LOG_FUNCTION, NS_LOG_LOGIC, and ns3::aodv::VALID.
Referenced by ns3::aodv::RoutingProtocol::RecvReply(), ns3::aodv::RoutingProtocol::RouteInput(), ns3::aodv::RoutingProtocol::RouteOutput(), ns3::aodv::RoutingProtocol::RouteRequestTimerExpire(), ns3::aodv::RoutingProtocol::SendRerrMessage(), and ns3::aodv::RoutingProtocol::SendRerrWhenNoRouteToForward().
MarkLinkAsUnidirectional()
bool ns3::aodv::RoutingTable::MarkLinkAsUnidirectional (Ipv4Address neighbor, Time blacklistTimeout)
Mark entry as unidirectional (e.g.
add this neighbor to "blacklist" for blacklistTimeout period)
Parameters
neighbor - neighbor address link to which assumed to be unidirectional
blacklistTimeout - time for which the neighboring node is put into the blacklist
Returns
true on success
Definition at line 449 of file aodv-rtable.cc.
References ns3::Time::As(), m_ipv4AddressEntry, NS_LOG_FUNCTION, NS_LOG_LOGIC, and ns3::Time::S.
Referenced by ns3::aodv::RoutingProtocol::AckTimerExpire(), and ns3::aodv::AodvRtableTest::DoRun().
Print()
void ns3::aodv::RoutingTable::Print (Ptr< OutputStreamWrapper > stream, Time::Unit unit = Time::S) const
Print routing table.
Parameters
stream the output stream
Definition at line 467 of file aodv-rtable.cc.
References ns3::OutputStreamWrapper::GetStream(), m_ipv4AddressEntry, and Purge().
Referenced by ns3::aodv::RoutingProtocol::PrintRoutingTable().
Purge() [1/2]
void ns3::aodv::RoutingTable::Purge ()
Delete all outdated entries and invalidate valid entry if Lifetime is expired.
Definition at line 375 of file aodv-rtable.cc.
References ns3::aodv::INVALID, m_badLinkLifetime, m_ipv4AddressEntry, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Seconds(), and ns3::aodv::VALID.
Referenced by AddRoute(), DeleteRoute(), ns3::aodv::RoutingProtocol::Forwarding(), GetListOfDestinationWithNextHop(), InvalidateRoutesWithDst(), LookupRoute(), and Print().
Purge() [2/2]
void ns3::aodv::RoutingTable::Purge (std::map< Ipv4Address, RoutingTableEntry > & table) const private
const version of Purge, for use by Print() method
Parameters
table the routing table entry to purge
Definition at line 412 of file aodv-rtable.cc.
References ns3::aodv::INVALID, m_badLinkLifetime, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Seconds(), and ns3::aodv::VALID.
SetBadLinkLifetime()
void ns3::aodv::RoutingTable::SetBadLinkLifetime (Time t) inline
The routing table.
Definition at line 402 of file aodv-rtable.h.
References m_badLinkLifetime.
Referenced by ns3::aodv::AodvRtableTest::DoRun().
SetEntryState()
bool ns3::aodv::RoutingTable::SetEntryState (Ipv4Address dst, RouteFlags state)
Set routing table entry flags.
Parameters
dst destination address
state the routing flags
Returns
true on success
Definition at line 297 of file aodv-rtable.cc.
References m_ipv4AddressEntry, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by ns3::aodv::AodvRtableTest::DoRun().
Update()
bool ns3::aodv::RoutingTable::Update (RoutingTableEntry & rt)
Update routing table.
Parameters
rt entry with destination address dst, if exists
Returns
true on success
Definition at line 277 of file aodv-rtable.cc.
References ns3::aodv::RoutingTableEntry::GetDestination(), ns3::aodv::IN_SEARCH, m_ipv4AddressEntry, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
Referenced by ns3::aodv::AodvRtableTest::DoRun(), ns3::aodv::RoutingProtocol::ProcessHello(), ns3::aodv::RoutingProtocol::RecvReply(), ns3::aodv::RoutingProtocol::RecvReplyAck(), ns3::aodv::RoutingProtocol::RecvRequest(), ns3::aodv::RoutingProtocol::SendReplyByIntermediateNode(), ns3::aodv::RoutingProtocol::SendRequest(), ns3::aodv::RoutingProtocol::UpdateRouteLifeTime(), and ns3::aodv::RoutingProtocol::UpdateRouteToNeighbor().
Member Data Documentation
m_badLinkLifetime
Time ns3::aodv::RoutingTable::m_badLinkLifetime private
Deletion time for invalid routes.
Definition at line 490 of file aodv-rtable.h.
Referenced by GetBadLinkLifetime(), InvalidateRoutesWithDst(), Purge(), and SetBadLinkLifetime().
m_ipv4AddressEntry
std::map<Ipv4Address, RoutingTableEntry> ns3::aodv::RoutingTable::m_ipv4AddressEntry private
The routing table.
Definition at line 488 of file aodv-rtable.h.
Referenced by AddRoute(), Clear(), DeleteAllRoutesFromInterface(), DeleteRoute(), GetListOfDestinationWithNextHop(), InvalidateRoutesWithDst(), LookupRoute(), MarkLinkAsUnidirectional(), Print(), Purge(), SetEntryState(), and Update().
The documentation for this class was generated from the following files:
src/aodv/model/aodv-rtable.h
src/aodv/model/aodv-rtable.cc