ns-3: ns3::UanMacAloha Class Reference
ns3::UanMacAloha Class Reference
UAN Models
ALOHA MAC Protocol, the simplest MAC protocol for wireless networks.
#include "uan-mac-aloha.h"
Public Member Functions
UanMacAloha ()
Default constructor.
virtual ~UanMacAloha ()
Dummy destructor, see DoDispose.
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
virtual void AttachPhy (Ptr< UanPhy > phy)
Attach PHY layer to this MAC.
virtual void Clear (void)
Clears all pointer references.
virtual bool Enqueue (Ptr< Packet > pkt, uint16_t protocolNumber, const Address &dest)
Enqueue packet to be transmitted.
virtual void SetForwardUpCb (Callback< void, Ptr< Packet >, uint16_t, const Mac8Address & > cb)
Set the callback to forward packets up to higher layers.
Public Member Functions inherited from ns3::UanMac
UanMac ()
Default constructor.
virtual Address GetAddress (void)
Get the MAC Address.
virtual Address GetBroadcast (void) const
Get the broadcast address.
uint32_t GetTxModeIndex ()
virtual void SetAddress (Mac8Address addr)
Set the address.
void SetTxModeIndex (uint32_t txModeIndex)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::UanMac
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose ()
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void RxPacketError (Ptr< Packet > pkt, double sinr)
Packet received at lower layer in error.
void RxPacketGood (Ptr< Packet > pkt, double sinr, UanTxMode txMode)
Receive packet from lower layer (passed to PHY as callback).
Private Attributes
bool m_cleared
Flag when we've been cleared.
Callback< void, Ptr< Packet >, uint16_t, const Mac8Address & > m_forUpCb
Forwarding up callback.
Ptr< UanPhy > m_phy
PHY layer attached to this MAC.
Additional Inherited Members
Public Types inherited from ns3::UanMac
typedef void(* PacketModeTracedCallback) (Ptr< const Packet > packet, UanTxMode mode)
TracedCallback signature for packet reception/enqueue/dequeue events.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
ALOHA MAC Protocol, the simplest MAC protocol for wireless networks.
Packets enqueued are immediately transmitted. This MAC attaches a UanHeaderCommon to outgoing packets for address information. (The type field is not used)
Config Paths
ns3::UanMacAloha is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::UanNetDevice/Mac/$ns3::UanMacAloha"
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 72 bytes (on a 64-bit architecture).
Definition at line 43 of file uan-mac-aloha.h.
Constructor & Destructor Documentation
UanMacAloha()
ns3::UanMacAloha::UanMacAloha ()
Default constructor.
Definition at line 36 of file uan-mac-aloha.cc.
~UanMacAloha()
ns3::UanMacAloha::~UanMacAloha () virtual
Dummy destructor, see DoDispose.
Definition at line 42 of file uan-mac-aloha.cc.
Member Function Documentation
AssignStreams()
int64_t ns3::UanMacAloha::AssignStreams (int64_t stream) virtual
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream First stream index to use.
Returns
The number of stream indices assigned by this model.
Implements ns3::UanMac.
Definition at line 138 of file uan-mac-aloha.cc.
References NS_LOG_FUNCTION.
AttachPhy()
void ns3::UanMacAloha::AttachPhy (Ptr< UanPhy > phy) virtual
Attach PHY layer to this MAC.
Some MACs may be designed to work with multiple PHY layers. Others may only work with one.
Parameters
phy Phy layer to attach to this MAC.
Implements ns3::UanMac.
Definition at line 109 of file uan-mac-aloha.cc.
References m_phy, ns3::MakeCallback(), third::phy, RxPacketError(), and RxPacketGood().
Clear()
void ns3::UanMacAloha::Clear (void) virtual
Clears all pointer references.
Implements ns3::UanMac.
Definition at line 47 of file uan-mac-aloha.cc.
References m_cleared, and m_phy.
Referenced by DoDispose().
DoDispose()
void ns3::UanMacAloha::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 62 of file uan-mac-aloha.cc.
References Clear(), and ns3::Object::DoDispose().
Enqueue()
bool ns3::UanMacAloha::Enqueue (Ptr< Packet > pkt, uint16_t protocolNumber, const Address & dest) virtual
Enqueue packet to be transmitted.
Parameters
pkt Packet to be transmitted.
dest Destination address.
protocolNumber The type of the packet.
Returns
True if packet was successfully enqueued.
Implements ns3::UanMac.
Definition at line 80 of file uan-mac-aloha.cc.
References ns3::Packet::AddHeader(), ns3::Mac8Address::ConvertFrom(), ns3::UanMac::GetAddress(), ns3::UanMac::GetTxModeIndex(), m_phy, ns3::Now(), NS_LOG_DEBUG, ns3::Time::S, ns3::UanHeaderCommon::SetDest(), ns3::UanHeaderCommon::SetProtocolNumber(), ns3::UanHeaderCommon::SetSrc(), and ns3::UanHeaderCommon::SetType().
GetTypeId()
TypeId ns3::UanMacAloha::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 69 of file uan-mac-aloha.cc.
References ns3::TypeId::SetParent().
RxPacketError()
void ns3::UanMacAloha::RxPacketError (Ptr< Packet > pkt, double sinr) private
Packet received at lower layer in error.
Parameters
pkt Packet received in error.
sinr SINR of received packet.
Definition at line 132 of file uan-mac-aloha.cc.
References ns3::Mac8Address::ConvertFrom(), ns3::UanMac::GetAddress(), ns3::Simulator::Now(), and NS_LOG_DEBUG.
Referenced by AttachPhy().
RxPacketGood()
void ns3::UanMacAloha::RxPacketGood (Ptr< Packet > pkt, double sinr, UanTxMode txMode) private
Receive packet from lower layer (passed to PHY as callback).
Parameters
pkt Packet being received.
sinr SINR of received packet.
txMode Mode of received packet.
Definition at line 117 of file uan-mac-aloha.cc.
References ns3::UanMac::GetAddress(), ns3::Mac8Address::GetBroadcast(), ns3::UanHeaderCommon::GetDest(), ns3::UanHeaderCommon::GetProtocolNumber(), ns3::UanHeaderCommon::GetSrc(), m_forUpCb, NS_LOG_DEBUG, NS_UNUSED, and ns3::Packet::RemoveHeader().
Referenced by AttachPhy().
SetForwardUpCb()
void ns3::UanMacAloha::SetForwardUpCb (Callback< void, Ptr< Packet >, uint16_t, const Mac8Address & > cb) virtual
Set the callback to forward packets up to higher layers.
Parameters
cb The callback. packet The packet. address The source address.
Implements ns3::UanMac.
Definition at line 104 of file uan-mac-aloha.cc.
References m_forUpCb.
Member Data Documentation
m_cleared
bool ns3::UanMacAloha::m_cleared private
Flag when we've been cleared.
Definition at line 70 of file uan-mac-aloha.h.
Referenced by Clear().
m_forUpCb
Callback<void, Ptr<Packet>, uint16_t, const Mac8Address& > ns3::UanMacAloha::m_forUpCb private
Forwarding up callback.
Definition at line 68 of file uan-mac-aloha.h.
Referenced by RxPacketGood(), and SetForwardUpCb().
m_phy
Ptr<UanPhy> ns3::UanMacAloha::m_phy private
PHY layer attached to this MAC.
Definition at line 66 of file uan-mac-aloha.h.
Referenced by AttachPhy(), Clear(), and Enqueue().
The documentation for this class was generated from the following files:
src/uan/model/uan-mac-aloha.h
src/uan/model/uan-mac-aloha.cc