ns-3: ns3::dot11s::PeerManagementProtocol Class Reference
ns3::dot11s::PeerManagementProtocol Class Reference
Mesh Device » IEEE 802.11s draft
802.11s Peer Management Protocol model
#include "peer-management-protocol.h"
Classes
struct BeaconInfo
Keeps information about beacon of peer station: beacon interval, association ID, last time we have received a beacon.
struct Statistics
Statistics structure.
Public Member Functions
PeerManagementProtocol ()
~PeerManagementProtocol ()
void DoDispose ()
Destructor implementation.
bool Install (Ptr< MeshPointDevice >)
Install PMP on given mesh point.
This methods interact with MAC_layer plug-in
Methods that handle beacon sending/receiving procedure.
Ptr< IeBeaconTiming > GetBeaconTimingElement (uint32_t interface)
When we are sending a beacon - we fill beacon timing element.
void ReceiveBeacon (uint32_t interface, Mac48Address peerAddress, Time beaconInterval, Ptr< IeBeaconTiming > beaconTiming)
To initiate peer link we must notify about received beacon.
void ReceivePeerLinkFrame (uint32_t interface, Mac48Address peerAddress, Mac48Address peerMeshPointAddress, uint16_t aid, IePeerManagement peerManagementElement, IeConfiguration meshConfig)
Methods that handle Peer link management frames interaction:
void ConfigurationMismatch (uint32_t interface, Mac48Address peerAddress)
Cancels peer link due to broken configuration (Mesh ID or Supported rates)
void TransmissionFailure (uint32_t interface, const Mac48Address peerAddress)
Cancels peer link due to successive transmission failures.
void TransmissionSuccess (uint32_t interface, const Mac48Address peerAddress)
resets transmission failure statistics
bool IsActiveLink (uint32_t interface, Mac48Address peerAddress)
Checks if there is established link.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
External peer-chooser
bool ShouldSendOpen (uint32_t interface, Mac48Address peerAddress)
Indicates changes in peer links.
bool ShouldAcceptOpen (uint32_t interface, Mac48Address peerAddress, PmpReasonCode &reasonCode)
Indicates changes in peer links.
void PeerLinkStatus (uint32_t interface, Mac48Address peerAddress, Mac48Address peerMeshPointAddres, PeerLink::PeerState ostate, PeerLink::PeerState nstate)
Indicates changes in peer links.
void CheckBeaconCollisions (uint32_t interface)
BCA.
void ShiftOwnBeacon (uint32_t interface)
Shift own beacon function.
Interface to other protocols (MLME)
typedef void(* LinkOpenCloseTracedCallback) (Mac48Address src, const Mac48Address dst)
TracedCallback signature for link open/close events.
typedef std::vector< Ptr< PeerLink > > PeerLinksOnInterface
We keep a vector of pointers to PeerLink class.
typedef std::map< uint32_t, PeerLinksOnInterface > PeerLinksMap
This map keeps all peer links.
typedef std::map< Mac48Address, BeaconInfo > BeaconsOnInterface
This map keeps relationship between peer address and its beacon information.
typedef std::map< uint32_t, BeaconsOnInterface > BeaconInfoMap
This map keeps beacon information on all interfaces.
typedef std::map< uint32_t, Ptr< PeerManagementProtocolMac > > PeerManagementProtocolMacMap
this vector keeps pointers to MAC-plugins
void SetPeerLinkStatusCallback (Callback< void, Mac48Address, Mac48Address, uint32_t, bool > cb)
Set peer link status change callback.
Ptr< PeerLink > FindPeerLink (uint32_t interface, Mac48Address peerAddress)
Find active peer link by my interface and peer interface MAC.
std::vector< Ptr< PeerLink > > GetPeerLinks () const
Get list of all active peer links.
std::vector< Mac48Address > GetPeers (uint32_t interface) const
Get list of active peers of my given interface.
Mac48Address GetAddress ()
Get mesh point address.
uint8_t GetNumberOfLinks ()
Get number of links.
void SetMeshId (std::string s)
Set mesh ID to a string value.
Ptr< IeMeshId > GetMeshId () const
Get mesh ID information element.
void SetBeaconCollisionAvoidance (bool enable)
Enable or disable beacon collision avoidance.
bool GetBeaconCollisionAvoidance () const
Get beacon collision avoidance.
void NotifyBeaconSent (uint32_t interface, Time beaconInterval)
Notify about beacon send event, needed to schedule BCA.
void Report (std::ostream &os) const
: Report statistics
void ResetStats ()
Reset statistics function.
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
virtual void DoInitialize ()
TracedCallback signature for link open/close events.
PeerManagementProtocol & operator= (const PeerManagementProtocol &peer)
assignment operator
PeerManagementProtocol (const PeerManagementProtocol &)
type conversion operator
Ptr< PeerLink > InitiateLink (uint32_t interface, Mac48Address peerAddress, Mac48Address peerMeshPointAddress)
Initiate link function.
Peer Links
typedef TracedCallback< Mac48Address, Mac48Address > LinkEventCallback
Simple link open/close trace source type. Addresses are: src interface, dst interface.
PeerLinksMap m_peerLinks
Simple link open/close trace source type. Addresses are: src interface, dst interface.
Callback< void, Mac48Address, Mac48Address, uint32_t, bool > m_peerStatusCallback
Callback to notify about peer link changes: Mac48Address is peer address of mesh point, Mac48Address is peer address of interface, uint32_t - interface ID, bool is status - true when new link has appeared, false - when link was closed,.
LinkEventCallback m_linkOpenTraceSrc
LinkOpen trace source.
LinkEventCallback m_linkCloseTraceSrc
LinkClose trace source.
struct Statistics m_stats
statistics
Ptr< UniformRandomVariable > m_beaconShift
Add randomness to beacon shift.
Time<-->TU converters:
PeerManagementProtocolMacMap m_plugins
plugins
Mac48Address m_address
address
Ptr< IeMeshId > m_meshId
mesh ID
uint16_t m_lastAssocId
last associated ID
uint16_t m_lastLocalLinkId
last local link ID
uint8_t m_maxNumberOfPeerLinks
maimum number of peer links
bool m_enableBca
Flag which enables BCA.
uint16_t m_maxBeaconShift
Beacon can be shifted at [-m_maxBeaconShift; +m_maxBeaconShift] TUs.
std::map< uint32_t, Time > m_lastBeacon
Last beacon at each interface.
std::map< uint32_t, Time > m_beaconInterval
Beacon interval at each interface.
Time TuToTime (int x)
plugins
int TimeToTu (Time x)
plugins
void NotifyLinkOpen (Mac48Address peerMp, Mac48Address peerIface, Mac48Address myIface, uint32_t interface)
Aux. method to register open links.
void NotifyLinkClose (Mac48Address peerMp, Mac48Address peerIface, Mac48Address myIface, uint32_t interface)
Aux. method to register closed links.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
802.11s Peer Management Protocol model
Introspection did not find any typical Config paths.
Attributes
MaxNumberOfPeerLinks: Maximum number of peer links
Set with class: ns3::UintegerValue
Underlying type: uint8_t 0:255
Initial value: 32
Flags: construct write read
MaxBeaconShiftValue: Maximum number of TUs for beacon shifting
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 15
Flags: construct write read
EnableBeaconCollisionAvoidance: Enable/Disable Beacon collision avoidance.
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
TraceSources
LinkOpen: New peer link opened
Callback signature: ns3::PeerManagementProtocol::LinkOpenCloseTracedCallback
LinkClose: New peer link closed
Callback signature: ns3::PeerManagementProtocol::LinkOpenCloseTracedCallback
Size of this type is 224 bytes (on a 64-bit architecture).
Definition at line 49 of file peer-management-protocol.h.
Member Typedef Documentation
BeaconInfoMap
typedef std::map<uint32_t, BeaconsOnInterface> ns3::dot11s::PeerManagementProtocol::BeaconInfoMap private
This map keeps beacon information on all interfaces.
Definition at line 229 of file peer-management-protocol.h.
BeaconsOnInterface
typedef std::map<Mac48Address, BeaconInfo> ns3::dot11s::PeerManagementProtocol::BeaconsOnInterface private
This map keeps relationship between peer address and its beacon information.
Definition at line 227 of file peer-management-protocol.h.
LinkEventCallback
typedef TracedCallback<Mac48Address, Mac48Address> ns3::dot11s::PeerManagementProtocol::LinkEventCallback private
Simple link open/close trace source type. Addresses are: src interface, dst interface.
Definition at line 320 of file peer-management-protocol.h.
LinkOpenCloseTracedCallback
typedef void(* ns3::dot11s::PeerManagementProtocol::LinkOpenCloseTracedCallback) (Mac48Address src, const Mac48Address dst)
TracedCallback signature for link open/close events.
Parameters
[in] src MAC address of source interface.
[in] dst MAC address of destination interface.
Definition at line 206 of file peer-management-protocol.h.
PeerLinksMap
typedef std::map<uint32_t, PeerLinksOnInterface> ns3::dot11s::PeerManagementProtocol::PeerLinksMap private
This map keeps all peer links.
Definition at line 225 of file peer-management-protocol.h.
PeerLinksOnInterface
typedef std::vector<Ptr<PeerLink> > ns3::dot11s::PeerManagementProtocol::PeerLinksOnInterface private
We keep a vector of pointers to PeerLink class.
This vector keeps all peer links at a given interface.
Definition at line 223 of file peer-management-protocol.h.
PeerManagementProtocolMacMap
typedef std::map<uint32_t, Ptr<PeerManagementProtocolMac> > ns3::dot11s::PeerManagementProtocol::PeerManagementProtocolMacMap private
this vector keeps pointers to MAC-plugins
Definition at line 231 of file peer-management-protocol.h.
Constructor & Destructor Documentation
PeerManagementProtocol() [1/2]
ns3::dot11s::PeerManagementProtocol::PeerManagementProtocol ()
Definition at line 91 of file peer-management-protocol.cc.
References m_beaconShift.
~PeerManagementProtocol()
ns3::dot11s::PeerManagementProtocol::~PeerManagementProtocol ()
Definition at line 96 of file peer-management-protocol.cc.
References m_meshId.
PeerManagementProtocol() [2/2]
ns3::dot11s::PeerManagementProtocol::PeerManagementProtocol (const PeerManagementProtocol &) private
type conversion operator
Member Function Documentation
AssignStreams()
int64_t ns3::dot11s::PeerManagementProtocol::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 590 of file peer-management-protocol.cc.
References m_beaconShift, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
CheckBeaconCollisions()
void ns3::dot11s::PeerManagementProtocol::CheckBeaconCollisions (uint32_t interface) private
BCA.
Definition at line 384 of file peer-management-protocol.cc.
References GetBeaconCollisionAvoidance(), m_beaconInterval, m_lastBeacon, m_maxBeaconShift, m_peerLinks, m_plugins, NS_ASSERT, NS_ASSERT_MSG, ShiftOwnBeacon(), TimeToTu(), and TuToTime().
Referenced by NotifyBeaconSent().
ConfigurationMismatch()
void ns3::dot11s::PeerManagementProtocol::ConfigurationMismatch (uint32_t interface, Mac48Address peerAddress)
Cancels peer link due to broken configuration (Mesh ID or Supported rates)
Definition at line 241 of file peer-management-protocol.cc.
References FindPeerLink(), and ns3::dot11s::REASON11S_MESH_CAPABILITY_POLICY_VIOLATION.
DoDispose()
void ns3::dot11s::PeerManagementProtocol::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 101 of file peer-management-protocol.cc.
References m_peerLinks, and m_plugins.
DoInitialize()
void ns3::dot11s::PeerManagementProtocol::DoInitialize (void) private virtual
TracedCallback signature for link open/close events.
Parameters
[in] src MAC address of source interface.
[in] dst MAC address of destination interface.
Reimplemented from ns3::Object.
Definition at line 598 of file peer-management-protocol.cc.
References m_beaconShift, m_maxBeaconShift, and ns3::ObjectBase::SetAttribute().
FindPeerLink()
Ptr< PeerLink > ns3::dot11s::PeerManagementProtocol::FindPeerLink (uint32_t interface, Mac48Address peerAddress)
Find active peer link by my interface and peer interface MAC.
Definition at line 296 of file peer-management-protocol.cc.
References m_peerLinks, and NS_ASSERT.
Referenced by ConfigurationMismatch(), InitiateLink(), IsActiveLink(), PeerLinkStatus(), ReceiveBeacon(), ReceivePeerLinkFrame(), TransmissionFailure(), and TransmissionSuccess().
GetAddress()
Mac48Address ns3::dot11s::PeerManagementProtocol::GetAddress (void)
Get mesh point address.
Todo:
this used by plugins only. Now MAC plugins can ask MP address directly from main MAC
Returns
Mac48Address
Definition at line 537 of file peer-management-protocol.cc.
References m_address.
Referenced by TransmissionFailure(), and TransmissionSuccess().
GetBeaconCollisionAvoidance()
bool ns3::dot11s::PeerManagementProtocol::GetBeaconCollisionAvoidance () const
Get beacon collision avoidance.
Returns
the beacon collision avoidance flag
Definition at line 613 of file peer-management-protocol.cc.
References m_enableBca.
Referenced by CheckBeaconCollisions(), GetBeaconTimingElement(), GetTypeId(), and ReceiveBeacon().
GetBeaconTimingElement()
Ptr< IeBeaconTiming > ns3::dot11s::PeerManagementProtocol::GetBeaconTimingElement (uint32_t interface)
When we are sending a beacon - we fill beacon timing element.
Returns
IeBeaconTiming is a beacon timing element that should be present in beacon
Parameters
interface is a interface sending a beacon
Definition at line 146 of file peer-management-protocol.cc.
References GetBeaconCollisionAvoidance(), m_peerLinks, NS_ASSERT, and ns3::Seconds().
GetMeshId()
Ptr< IeMeshId > ns3::dot11s::PeerManagementProtocol::GetMeshId () const
Get mesh ID information element.
Returns
the mesh ID information element
Definition at line 526 of file peer-management-protocol.cc.
References m_meshId, and NS_ASSERT.
GetNumberOfLinks()
uint8_t ns3::dot11s::PeerManagementProtocol::GetNumberOfLinks ()
Get number of links.
Returns
the number of links
Definition at line 521 of file peer-management-protocol.cc.
References ns3::dot11s::PeerManagementProtocol::Statistics::linksTotal, and m_stats.
GetPeerLinks()
std::vector< Ptr< PeerLink > > ns3::dot11s::PeerManagementProtocol::GetPeerLinks () const
Get list of all active peer links.
Definition at line 342 of file peer-management-protocol.cc.
References m_peerLinks.
GetPeers()
std::vector< Mac48Address > ns3::dot11s::PeerManagementProtocol::GetPeers (uint32_t interface) const
Get list of active peers of my given interface.
Definition at line 326 of file peer-management-protocol.cc.
References m_peerLinks, and NS_ASSERT.
Referenced by ns3::Dot11sStack::InstallStack().
GetTypeId()
TypeId ns3::dot11s::PeerManagementProtocol::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 48 of file peer-management-protocol.cc.
References GetBeaconCollisionAvoidance(), m_linkCloseTraceSrc, m_linkOpenTraceSrc, m_maxBeaconShift, m_maxNumberOfPeerLinks, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), SetBeaconCollisionAvoidance(), and ns3::TypeId::SetParent().
InitiateLink()
Ptr< PeerLink > ns3::dot11s::PeerManagementProtocol::InitiateLink (uint32_t interface, Mac48Address peerAddress, Mac48Address peerMeshPointAddress) private
Initiate link function.
Parameters
interface the interface to use
peerAddress the peer address
peerMeshPointAddress the peer mesh point address
Returns
the peer link
Definition at line 270 of file peer-management-protocol.cc.
References FindPeerLink(), m_lastAssocId, m_lastLocalLinkId, m_peerLinks, m_plugins, ns3::MakeCallback(), NS_ASSERT, NS_FATAL_ERROR, and PeerLinkStatus().
Referenced by ReceiveBeacon(), and ReceivePeerLinkFrame().
Install()
bool ns3::dot11s::PeerManagementProtocol::Install (Ptr< MeshPointDevice > mp)
Install PMP on given mesh point.
Returns
true if successful
Installing protocol causes installation of its interface MAC plugins.
Also MP aggregates all installed protocols, PMP protocol can be accessed via MeshPointDevice::GetObject<PeerManagementProtocol>();
Definition at line 118 of file peer-management-protocol.cc.
References ns3::Mac48Address::ConvertFrom(), ns3::WifiNetDevice::GetMac(), ns3::Object::GetObject(), first::interfaces, m_address, m_peerLinks, m_plugins, and third::mac.
IsActiveLink()
bool ns3::dot11s::PeerManagementProtocol::IsActiveLink (uint32_t interface, Mac48Address peerAddress)
Checks if there is established link.
Definition at line 356 of file peer-management-protocol.cc.
References FindPeerLink().
NotifyBeaconSent()
void ns3::dot11s::PeerManagementProtocol::NotifyBeaconSent (uint32_t interface, Time beaconInterval)
Notify about beacon send event, needed to schedule BCA.
Parameters
interface the interface to use
beaconInterval the beacon interval
Definition at line 542 of file peer-management-protocol.cc.
References CheckBeaconCollisions(), m_beaconInterval, m_lastBeacon, m_maxBeaconShift, ns3::Simulator::Now(), ns3::Simulator::Schedule(), and TuToTime().
NotifyLinkClose()
void ns3::dot11s::PeerManagementProtocol::NotifyLinkClose (Mac48Address peerMp, Mac48Address peerIface, Mac48Address myIface, uint32_t interface) private
Aux. method to register closed links.
Definition at line 483 of file peer-management-protocol.cc.
References ns3::dot11s::PeerManagementProtocol::Statistics::linksClosed, ns3::dot11s::PeerManagementProtocol::Statistics::linksTotal, m_linkCloseTraceSrc, m_peerStatusCallback, m_stats, and NS_LOG_LOGIC.
Referenced by PeerLinkStatus().
NotifyLinkOpen()
void ns3::dot11s::PeerManagementProtocol::NotifyLinkOpen (Mac48Address peerMp, Mac48Address peerIface, Mac48Address myIface, uint32_t interface) private
Aux. method to register open links.
Definition at line 470 of file peer-management-protocol.cc.
References ns3::dot11s::PeerManagementProtocol::Statistics::linksOpened, ns3::dot11s::PeerManagementProtocol::Statistics::linksTotal, m_linkOpenTraceSrc, m_peerStatusCallback, m_stats, and NS_LOG_LOGIC.
Referenced by PeerLinkStatus().
operator=()
PeerManagementProtocol& ns3::dot11s::PeerManagementProtocol::operator= (const PeerManagementProtocol & peer) private
assignment operator
Parameters
peer the value to assign
Returns
the assigned value
PeerLinkStatus()
void ns3::dot11s::PeerManagementProtocol::PeerLinkStatus (uint32_t interface, Mac48Address peerAddress, Mac48Address peerMeshPointAddres, PeerLink::PeerState ostate, PeerLink::PeerState nstate) private
Indicates changes in peer links.
Definition at line 496 of file peer-management-protocol.cc.
References ns3::dot11s::PeerLink::ESTAB, FindPeerLink(), ns3::dot11s::PeerLink::IDLE, m_address, m_plugins, NotifyLinkClose(), NotifyLinkOpen(), NS_ASSERT, NS_LOG_DEBUG, and ns3::dot11s::PeerLink::PeerStateNames.
Referenced by InitiateLink().
ReceiveBeacon()
void ns3::dot11s::PeerManagementProtocol::ReceiveBeacon (uint32_t interface, Mac48Address peerAddress, Time beaconInterval, Ptr< IeBeaconTiming > beaconTiming)
To initiate peer link we must notify about received beacon.
Parameters
interface the interface where a beacon was received from
peerAddress address of station, which sent a beacon
beaconInterval beacon interval (needed by beacon loss counter)
beaconTiming beacon timing element (needed by BCA)
Definition at line 170 of file peer-management-protocol.cc.
References FindPeerLink(), GetBeaconCollisionAvoidance(), ns3::Mac48Address::GetBroadcast(), InitiateLink(), m_plugins, ns3::Simulator::Now(), ns3::PeekPointer(), and ShouldSendOpen().
ReceivePeerLinkFrame()
void ns3::dot11s::PeerManagementProtocol::ReceivePeerLinkFrame (uint32_t interface, Mac48Address peerAddress, Mac48Address peerMeshPointAddress, uint16_t aid, IePeerManagement peerManagementElement, IeConfiguration meshConfig)
Methods that handle Peer link management frames interaction:
Deliver Peer link management information to the protocol-part
Parameters
interface is a interface ID of a given MAC (interfaceID rather than MAC address, because many interfaces may have the same MAC)
peerAddress is address of peer
peerMeshPointAddress is address of peer mesh point device (equal to peer address when only one interface)
aid is association ID, which peer has assigned to us
peerManagementElement is peer link management element
meshConfig is mesh configuration element taken from the peer management frame
Definition at line 202 of file peer-management-protocol.cc.
References FindPeerLink(), ns3::dot11s::IePeerManagement::GetLocalLinkId(), ns3::dot11s::IePeerManagement::GetPeerLinkId(), ns3::dot11s::IePeerManagement::GetReasonCode(), InitiateLink(), ns3::dot11s::REASON11S_RESERVED, ShouldAcceptOpen(), ns3::dot11s::IePeerManagement::SubtypeIsClose(), ns3::dot11s::IePeerManagement::SubtypeIsConfirm(), and ns3::dot11s::IePeerManagement::SubtypeIsOpen().
Report()
void ns3::dot11s::PeerManagementProtocol::Report (std::ostream & os) const
: Report statistics
Parameters
os the output stream
Definition at line 561 of file peer-management-protocol.cc.
References m_peerLinks, m_plugins, m_stats, NS_ASSERT, visualizer.base::plugins, and ns3::dot11s::PeerManagementProtocol::Statistics::Print().
ResetStats()
void ns3::dot11s::PeerManagementProtocol::ResetStats ()
Reset statistics function.
Definition at line 580 of file peer-management-protocol.cc.
References ns3::dot11s::PeerManagementProtocol::Statistics::linksTotal, m_plugins, m_stats, and visualizer.base::plugins.
SetBeaconCollisionAvoidance()
void ns3::dot11s::PeerManagementProtocol::SetBeaconCollisionAvoidance (bool enable)
Enable or disable beacon collision avoidance.
Parameters
enable true to enable beacon collision avoidance
Definition at line 608 of file peer-management-protocol.cc.
References m_enableBca.
Referenced by GetTypeId().
SetMeshId()
void ns3::dot11s::PeerManagementProtocol::SetMeshId (std::string s)
Set mesh ID to a string value.
Parameters
s the mesh ID string value
Definition at line 532 of file peer-management-protocol.cc.
References m_meshId.
SetPeerLinkStatusCallback()
void ns3::dot11s::PeerManagementProtocol::SetPeerLinkStatusCallback (Callback< void, Mac48Address, Mac48Address, uint32_t, bool > cb)
Set peer link status change callback.
Definition at line 319 of file peer-management-protocol.cc.
References m_peerStatusCallback.
ShiftOwnBeacon()
void ns3::dot11s::PeerManagementProtocol::ShiftOwnBeacon (uint32_t interface) private
Shift own beacon function.
Definition at line 444 of file peer-management-protocol.cc.
References ns3::UniformRandomVariable::GetValue(), m_beaconShift, m_plugins, NS_ASSERT, and TuToTime().
Referenced by CheckBeaconCollisions().
ShouldAcceptOpen()
bool ns3::dot11s::PeerManagementProtocol::ShouldAcceptOpen (uint32_t interface, Mac48Address peerAddress, PmpReasonCode & reasonCode) private
Indicates changes in peer links.
Definition at line 372 of file peer-management-protocol.cc.
References ns3::dot11s::PeerManagementProtocol::Statistics::linksTotal, m_maxNumberOfPeerLinks, m_stats, and ns3::dot11s::REASON11S_MESH_MAX_PEERS.
Referenced by ReceivePeerLinkFrame().
ShouldSendOpen()
bool ns3::dot11s::PeerManagementProtocol::ShouldSendOpen (uint32_t interface, Mac48Address peerAddress) private
Indicates changes in peer links.
Definition at line 366 of file peer-management-protocol.cc.
References ns3::dot11s::PeerManagementProtocol::Statistics::linksTotal, m_maxNumberOfPeerLinks, and m_stats.
Referenced by ReceiveBeacon().
TimeToTu()
int ns3::dot11s::PeerManagementProtocol::TimeToTu (Time x) private
plugins
Definition at line 464 of file peer-management-protocol.cc.
References sample-rng-plot::x.
Referenced by CheckBeaconCollisions().
TransmissionFailure()
void ns3::dot11s::PeerManagementProtocol::TransmissionFailure (uint32_t interface, const Mac48Address peerAddress)
Cancels peer link due to successive transmission failures.
Definition at line 250 of file peer-management-protocol.cc.
References FindPeerLink(), GetAddress(), and NS_LOG_DEBUG.
TransmissionSuccess()
void ns3::dot11s::PeerManagementProtocol::TransmissionSuccess (uint32_t interface, const Mac48Address peerAddress)
resets transmission failure statistics
Definition at line 260 of file peer-management-protocol.cc.
References FindPeerLink(), GetAddress(), and NS_LOG_DEBUG.
TuToTime()
Time ns3::dot11s::PeerManagementProtocol::TuToTime (int x) private
plugins
Definition at line 459 of file peer-management-protocol.cc.
References ns3::MicroSeconds(), and sample-rng-plot::x.
Referenced by CheckBeaconCollisions(), NotifyBeaconSent(), and ShiftOwnBeacon().
Member Data Documentation
m_address
Mac48Address ns3::dot11s::PeerManagementProtocol::m_address private
address
Definition at line 291 of file peer-management-protocol.h.
Referenced by GetAddress(), Install(), and PeerLinkStatus().
m_beaconInterval
std::map<uint32_t, Time> ns3::dot11s::PeerManagementProtocol::m_beaconInterval private
Beacon interval at each interface.
Definition at line 304 of file peer-management-protocol.h.
Referenced by CheckBeaconCollisions(), and NotifyBeaconSent().
m_beaconShift
Ptr<UniformRandomVariable> ns3::dot11s::PeerManagementProtocol::m_beaconShift private
Add randomness to beacon shift.
Definition at line 347 of file peer-management-protocol.h.
Referenced by PeerManagementProtocol(), AssignStreams(), DoInitialize(), and ShiftOwnBeacon().
m_enableBca
bool ns3::dot11s::PeerManagementProtocol::m_enableBca private
Flag which enables BCA.
Definition at line 298 of file peer-management-protocol.h.
Referenced by GetBeaconCollisionAvoidance(), and SetBeaconCollisionAvoidance().
m_lastAssocId
uint16_t ns3::dot11s::PeerManagementProtocol::m_lastAssocId private
last associated ID
Definition at line 294 of file peer-management-protocol.h.
Referenced by InitiateLink().
m_lastBeacon
std::map<uint32_t, Time> ns3::dot11s::PeerManagementProtocol::m_lastBeacon private
Last beacon at each interface.
Definition at line 302 of file peer-management-protocol.h.
Referenced by CheckBeaconCollisions(), and NotifyBeaconSent().
m_lastLocalLinkId
uint16_t ns3::dot11s::PeerManagementProtocol::m_lastLocalLinkId private
last local link ID
Definition at line 295 of file peer-management-protocol.h.
Referenced by InitiateLink().
m_linkCloseTraceSrc
LinkEventCallback ns3::dot11s::PeerManagementProtocol::m_linkCloseTraceSrc private
LinkClose trace source.
Definition at line 324 of file peer-management-protocol.h.
Referenced by GetTypeId(), and NotifyLinkClose().
m_linkOpenTraceSrc
LinkEventCallback ns3::dot11s::PeerManagementProtocol::m_linkOpenTraceSrc private
LinkOpen trace source.
Definition at line 322 of file peer-management-protocol.h.
Referenced by GetTypeId(), and NotifyLinkOpen().
m_maxBeaconShift
uint16_t ns3::dot11s::PeerManagementProtocol::m_maxBeaconShift private
Beacon can be shifted at [-m_maxBeaconShift; +m_maxBeaconShift] TUs.
Definition at line 300 of file peer-management-protocol.h.
Referenced by CheckBeaconCollisions(), DoInitialize(), GetTypeId(), and NotifyBeaconSent().
m_maxNumberOfPeerLinks
uint8_t ns3::dot11s::PeerManagementProtocol::m_maxNumberOfPeerLinks private
maimum number of peer links
Definition at line 296 of file peer-management-protocol.h.
Referenced by GetTypeId(), ShouldAcceptOpen(), and ShouldSendOpen().
m_meshId
Ptr<IeMeshId> ns3::dot11s::PeerManagementProtocol::m_meshId private
mesh ID
Definition at line 292 of file peer-management-protocol.h.
Referenced by ~PeerManagementProtocol(), GetMeshId(), and SetMeshId().
m_peerLinks
PeerLinksMap ns3::dot11s::PeerManagementProtocol::m_peerLinks private
Simple link open/close trace source type. Addresses are: src interface, dst interface.
Definition at line 309 of file peer-management-protocol.h.
Referenced by CheckBeaconCollisions(), DoDispose(), FindPeerLink(), GetBeaconTimingElement(), GetPeerLinks(), GetPeers(), InitiateLink(), Install(), and Report().
m_peerStatusCallback
Callback<void, Mac48Address, Mac48Address, uint32_t, bool> ns3::dot11s::PeerManagementProtocol::m_peerStatusCallback private
Callback to notify about peer link changes: Mac48Address is peer address of mesh point, Mac48Address is peer address of interface, uint32_t - interface ID, bool is status - true when new link has appeared, false - when link was closed,.
Definition at line 317 of file peer-management-protocol.h.
Referenced by NotifyLinkClose(), NotifyLinkOpen(), and SetPeerLinkStatusCallback().
m_plugins
PeerManagementProtocolMacMap ns3::dot11s::PeerManagementProtocol::m_plugins private
plugins
Definition at line 290 of file peer-management-protocol.h.
Referenced by CheckBeaconCollisions(), DoDispose(), InitiateLink(), Install(), PeerLinkStatus(), ReceiveBeacon(), Report(), ResetStats(), and ShiftOwnBeacon().
m_stats
struct Statistics ns3::dot11s::PeerManagementProtocol::m_stats private
statistics
Definition at line 324 of file peer-management-protocol.h.
Referenced by GetNumberOfLinks(), NotifyLinkClose(), NotifyLinkOpen(), Report(), ResetStats(), ShouldAcceptOpen(), and ShouldSendOpen().
The documentation for this class was generated from the following files:
src/mesh/model/dot11s/peer-management-protocol.h
src/mesh/model/dot11s/peer-management-protocol.cc