ns-3: ns3::ServiceFlow Class Reference
ns3::ServiceFlow Class Reference
WiMAX Models
This class implements service flows as described by the IEEE-802.16 standard.
#include "service-flow.h"
Public Types
enum CsSpecification {
ATM = 99 , IPV4 = 100 , IPV6 = 101 , ETHERNET = 102 ,
VLAN = 103 , IPV4_OVER_ETHERNET = 104 , IPV6_OVER_ETHERNET = 105 , IPV4_OVER_VLAN = 106 ,
IPV6_OVER_VLAN = 107
}
section 11.13.19.2 CS parameter encoding rules, page 707
enum Direction { SF_DIRECTION_DOWN , SF_DIRECTION_UP }
Direction enumeration.
enum ModulationType {
MODULATION_TYPE_BPSK_12 , MODULATION_TYPE_QPSK_12 , MODULATION_TYPE_QPSK_34 , MODULATION_TYPE_QAM16_12 ,
MODULATION_TYPE_QAM16_34 , MODULATION_TYPE_QAM64_23 , MODULATION_TYPE_QAM64_34
}
Modulation type enumeration, Table 356 and 362.
enum SchedulingType {
SF_TYPE_NONE = 0 , SF_TYPE_UNDEF = 1 , SF_TYPE_BE = 2 , SF_TYPE_NRTPS = 3 ,
SF_TYPE_RTPS = 4 , SF_TYPE_UGS = 6 , SF_TYPE_ALL = 255
}
section 11.13.11 Service flow scheduling type, page 701
enum Type { SF_TYPE_PROVISIONED , SF_TYPE_ADMITTED , SF_TYPE_ACTIVE }
Type enumeration.
Public Member Functions
ServiceFlow ()
default constructor
ServiceFlow (const ServiceFlow &sf)
Constructor.
ServiceFlow (enum Direction direction)
Constructor.
ServiceFlow (Tlv tlv)
creates a service flow from a TLV
ServiceFlow (uint32_t sfid, enum Direction direction, Ptr< WimaxConnection > connection)
Constructor.
~ServiceFlow (void)
bool CheckClassifierMatch (Ipv4Address srcAddress, Ipv4Address dstAddress, uint16_t srcPort, uint16_t dstPort, uint8_t proto) const
void CleanUpQueue (void)
shall be called only by BS
void CopyParametersFrom (ServiceFlow sf)
Copy parameters from another service flow.
uint16_t GetArqBlockLifeTime (void) const
Get ARQ block lifetime.
uint16_t GetArqBlockSize (void) const
Get ARQ block size.
uint8_t GetArqDeliverInOrder (void) const
Get ARQ deliver in order.
uint8_t GetArqEnable (void) const
Get ARQ enable.
uint16_t GetArqPurgeTimeout (void) const
Get ARQ purge timeout.
uint16_t GetArqRetryTimeoutRx (void) const
Get ARQ retry timeout receive.
uint16_t GetArqRetryTimeoutTx (void) const
Get ARQ retry timeout transmit.
uint16_t GetArqSyncLoss (void) const
Get ARQ sync loss.
uint16_t GetArqWindowSize (void) const
Get ARQ retry timeout transmit.
uint16_t GetCid (void) const
Get CID.
Ptr< WimaxConnection > GetConnection (void) const
Can return a null connection is this service flow has not been associated yet to a connection.
CsParameters GetConvergenceSublayerParam (void) const
Get convergence sublayer.
enum CsSpecification GetCsSpecification (void) const
Get CS specification.
enum Direction GetDirection (void) const
Get direction.
uint8_t GetFixedversusVariableSduIndicator (void) const
Get fixed versus varaiable SDU indicator.
bool GetIsEnabled (void) const
Get is enabled flag.
bool GetIsMulticast (void) const
Get is multicast.
uint32_t GetMaximumLatency (void) const
Get maximum latency.
uint32_t GetMaxSustainedTrafficRate (void) const
Get max sustained traffic rate.
uint32_t GetMaxTrafficBurst (void) const
Get max traffic burst.
uint32_t GetMinReservedTrafficRate (void) const
Get minimum reserved traffic rate.
uint32_t GetMinTolerableTrafficRate (void) const
Get minimum tolerable traffic rate.
enum WimaxPhy::ModulationType GetModulation (void) const
Get modulation.
uint8_t GetQosParamSetType (void) const
Get QOS parameter set type.
Ptr< WimaxMacQueue > GetQueue (void) const
Get pointer to queue.
ServiceFlowRecord * GetRecord (void) const
Get service flow record.
uint32_t GetRequestTransmissionPolicy (void) const
Get request transmission policy.
enum ServiceFlow::SchedulingType GetSchedulingType (void) const
Get scheduling type.
char * GetSchedulingTypeStr (void) const
Get scheduling type string.
uint8_t GetSduSize (void) const
Get SDU size.
std::string GetServiceClassName () const
Get service class name.
enum ServiceFlow::SchedulingType GetServiceSchedulingType (void) const
Get service scheduling type.
uint32_t GetSfid (void) const
Get SFID.
uint16_t GetTargetSAID (void) const
Get target SAID.
uint32_t GetToleratedJitter (void) const
Get tolerated jitter.
uint8_t GetTrafficPriority (void) const
Get traffic priority.
enum Type GetType (void) const
Get type of service flow.
uint16_t GetUnsolicitedGrantInterval (void) const
Get unsolicited grant interval.
uint16_t GetUnsolicitedPollingInterval (void) const
Get unsolicited polling interval.
bool HasPackets (MacHeaderType::HeaderType packetType) const
Check if packets of particular type are present.
bool HasPackets (void) const
Check if packets are present.
void InitValues (void)
Initial values.
ServiceFlow & operator= (ServiceFlow const &o)
assignment operator
void PrintQoSParameters (void) const
Print QOS parameters.
void SetArqBlockLifeTime (uint16_t lifeTime)
Set ARQ block lifetime.
void SetArqBlockSize (uint16_t size)
Set ARQ block size.
void SetArqDeliverInOrder (uint8_t inOrder)
Set ARQ deliver in order.
void SetArqEnable (uint8_t arqEnable)
Set ARQ enable.
void SetArqPurgeTimeout (uint16_t timeout)
Set ARQ purge timeout.
void SetArqRetryTimeoutRx (uint16_t timeout)
Set ARQ retry timeout receive.
void SetArqRetryTimeoutTx (uint16_t timeout)
Set ARQ retry timeout transmit.
void SetArqSyncLoss (uint16_t syncLoss)
Set ARQ sync loss.
void SetArqWindowSize (uint16_t arqWindowSize)
Set ARQ retry timeout transmit.
void SetConnection (Ptr< WimaxConnection > connection)
Set connection.
void SetConvergenceSublayerParam (CsParameters csparam)
Set convergence sublayer parameters.
void SetCsSpecification (enum CsSpecification spec)
Set CS specification.
void SetDirection (enum Direction direction)
Set direction.
void SetFixedversusVariableSduIndicator (uint8_t sduIndicator)
Set fixed versus variable SDU indicator.
void SetIsEnabled (bool isEnabled)
Set is enabled flag.
void SetIsMulticast (bool isMulticast)
Set is multicast.
void SetMaximumLatency (uint32_t MaximumLatency)
Set maximum latency.
void SetMaxSustainedTrafficRate (uint32_t maxSustainedRate)
Set max sustained traffic rate.
void SetMaxTrafficBurst (uint32_t maxTrafficBurst)
Set maximum traffic burst.
void SetMinReservedTrafficRate (uint32_t minResvRate)
Set minimum reserved traffic rate.
void SetMinTolerableTrafficRate (uint32_t minJitter)
Set minimum tolerable traffic rate.
void SetModulation (enum WimaxPhy::ModulationType modulationType)
Set modulation.
void SetQosParamSetType (uint8_t type)
Set QOS parameter set type.
void SetRecord (ServiceFlowRecord *record)
Set service flow record.
void SetRequestTransmissionPolicy (uint32_t policy)
Set request transmission policy.
void SetSduSize (uint8_t sduSize)
Set SDU size.
void SetServiceClassName (std::string name)
Set service class name.
void SetServiceSchedulingType (enum ServiceFlow::SchedulingType schedType)
Set service scheduling type.
void SetSfid (uint32_t sfid)
Set SFID.
void SetTargetSAID (uint16_t targetSaid)
Set target SAID.
void SetToleratedJitter (uint32_t jitter)
Set tolerated jitter.
void SetTrafficPriority (uint8_t priority)
Set traffic priority.
void SetType (enum Type type)
Set type of service flow.
void SetUnsolicitedGrantInterval (uint16_t unsolicitedGrantInterval)
Set unsolicied grant interval.
void SetUnsolicitedPollingInterval (uint16_t unsolicitedPollingInterval)
Set unsolicited polling interval.
Tlv ToTlv (void) const
creates a TLV from this service flow
Private Attributes
uint16_t m_arqBlockLifeTime
ARQ block life time.
uint16_t m_arqBlockSize
ARQ block size.
uint8_t m_arqDeliverInOrder
ARQ deliver in order.
uint8_t m_arqEnable
ARQ enable.
uint16_t m_arqPurgeTimeout
ARQ purge timeout.
uint16_t m_arqRetryTimeoutRx
ARQ retry timeout receive.
uint16_t m_arqRetryTimeoutTx
ARQ retry timeout transmit.
uint16_t m_arqSyncLoss
ARQ sync loss.
uint16_t m_arqWindowSize
ARQ window size.
Ptr< WimaxConnection > m_connection
connection
CsParameters m_convergenceSublayerParam
convergence sublayer parameters
enum CsSpecification m_csSpecification
CS specification.
Direction m_direction
direction
uint8_t m_fixedversusVariableSduIndicator
fixed versus variable SDI indicator
bool m_isEnabled
is enabled?
bool m_isMulticast
is multicast?
uint32_t m_maximumLatency
maximum latency
uint32_t m_maxSustainedTrafficRate
maximum sustained traffic rate
uint32_t m_maxTrafficBurst
maximum traffic burst
uint32_t m_minReservedTrafficRate
minimum reserved traffic rate
uint32_t m_minTolerableTrafficRate
minimum tolerable traffic rate
enum WimaxPhy::ModulationType m_modulationType
modulation type
uint8_t m_qosParamSetType
QOS parameter type.
ServiceFlowRecord * m_record
service flow record
uint32_t m_requestTransmissionPolicy
request transmission policy
enum ServiceFlow::SchedulingType m_schedulingType
scheduling type
uint8_t m_sduSize
SDU size.
std::string m_serviceClassName
service class name
uint32_t m_sfid
SFID.
uint16_t m_targetSAID
traget SAID
uint32_t m_toleratedJitter
tolerated jitter
uint8_t m_trafficPriority
traffic priority
Type m_type
type
uint16_t m_unsolicitedGrantInterval
unsolicited grant interval
uint16_t m_unsolicitedPollingInterval
unsolicited polling interval
Detailed Description
This class implements service flows as described by the IEEE-802.16 standard.
Definition at line 39 of file service-flow.h.
Member Enumeration Documentation
CsSpecification
enum ns3::ServiceFlow::CsSpecification
section 11.13.19.2 CS parameter encoding rules, page 707
Enumerator
ATM
IPV4
IPV6
ETHERNET
VLAN
IPV4_OVER_ETHERNET
IPV6_OVER_ETHERNET
IPV4_OVER_VLAN
IPV6_OVER_VLAN
Definition at line 69 of file service-flow.h.
Direction
enum ns3::ServiceFlow::Direction
Direction enumeration.
Enumerator
SF_DIRECTION_DOWN
SF_DIRECTION_UP
Definition at line 43 of file service-flow.h.
ModulationType
enum ns3::ServiceFlow::ModulationType
Modulation type enumeration, Table 356 and 362.
Enumerator
MODULATION_TYPE_BPSK_12
MODULATION_TYPE_QPSK_12
MODULATION_TYPE_QPSK_34
MODULATION_TYPE_QAM16_12
MODULATION_TYPE_QAM16_34
MODULATION_TYPE_QAM64_23
MODULATION_TYPE_QAM64_34
Definition at line 82 of file service-flow.h.
SchedulingType
enum ns3::ServiceFlow::SchedulingType
section 11.13.11 Service flow scheduling type, page 701
Enumerator
SF_TYPE_NONE
SF_TYPE_UNDEF
SF_TYPE_BE
SF_TYPE_NRTPS
SF_TYPE_RTPS
SF_TYPE_UGS
SF_TYPE_ALL
Definition at line 58 of file service-flow.h.
Type
enum ns3::ServiceFlow::Type
Type enumeration.
Enumerator
SF_TYPE_PROVISIONED
SF_TYPE_ADMITTED
SF_TYPE_ACTIVE
Definition at line 50 of file service-flow.h.
Constructor & Destructor Documentation
ServiceFlow() [1/5]
ns3::ServiceFlow::ServiceFlow (Tlv tlv)
creates a service flow from a TLV
Parameters
tlv the tlv from which the service flow will be created
Definition at line 71 of file service-flow.cc.
References ns3::VectorTlvValue::Begin(), ns3::SfVectorTlvValue::CID, ns3::SfVectorTlvValue::CS_Specification, ns3::Tlv::DOWNLINK_SERVICE_FLOW, ns3::VectorTlvValue::End(), ns3::SfVectorTlvValue::Fixed_length_versus_Variable_length_SDU_Indicator, ns3::Tlv::GetType(), InitValues(), ns3::SfVectorTlvValue::IPV4_CS_Parameters, m_connection, m_convergenceSublayerParam, m_csSpecification, m_direction, m_fixedversusVariableSduIndicator, m_isEnabled, m_isMulticast, m_maximumLatency, m_maxSustainedTrafficRate, m_maxTrafficBurst, m_minReservedTrafficRate, m_minTolerableTrafficRate, m_modulationType, m_qosParamSetType, m_record, m_requestTransmissionPolicy, m_schedulingType, m_sfid, m_toleratedJitter, m_trafficPriority, ns3::SfVectorTlvValue::Maximum_Latency, ns3::SfVectorTlvValue::Maximum_Sustained_Traffic_Rate, ns3::SfVectorTlvValue::Maximum_Traffic_Burst, ns3::SfVectorTlvValue::Minimum_Reserved_Traffic_Rate, ns3::SfVectorTlvValue::Minimum_Tolerable_Traffic_Rate, ns3::WimaxPhy::MODULATION_TYPE_QPSK_12, NS_ASSERT_MSG, ns3::Tlv::PeekValue(), ns3::SfVectorTlvValue::QoS_Parameter_Set_Type, ns3::SfVectorTlvValue::Request_Transmission_Policy, ns3::SfVectorTlvValue::Service_Flow_Scheduling_Type, SF_DIRECTION_DOWN, SF_DIRECTION_UP, ns3::SfVectorTlvValue::SFID, ns3::SfVectorTlvValue::Tolerated_Jitter, ns3::SfVectorTlvValue::Traffic_Priority, ns3::Cid::TRANSPORT, and ns3::Tlv::UPLINK_SERVICE_FLOW.
ServiceFlow() [2/5]
ns3::ServiceFlow::ServiceFlow ()
default constructor
Definition at line 43 of file service-flow.cc.
References InitValues(), m_isMulticast, m_modulationType, and ns3::WimaxPhy::MODULATION_TYPE_QPSK_12.
ServiceFlow() [3/5]
ns3::ServiceFlow::ServiceFlow (enum Direction direction)
Constructor.
Parameters
direction the direction
Definition at line 30 of file service-flow.cc.
References InitValues(), m_connection, m_direction, m_isEnabled, m_isMulticast, m_modulationType, m_record, m_sfid, m_type, ns3::WimaxPhy::MODULATION_TYPE_QPSK_12, and SF_TYPE_PROVISIONED.
ServiceFlow() [4/5]
ns3::ServiceFlow::ServiceFlow (const ServiceFlow & sf)
Constructor.
Parameters
sf service flow
Definition at line 701 of file service-flow.cc.
References GetArqEnable(), GetArqRetryTimeoutRx(), GetArqRetryTimeoutTx(), GetArqWindowSize(), GetConnection(), GetConvergenceSublayerParam(), GetCsSpecification(), GetDirection(), GetFixedversusVariableSduIndicator(), GetIsEnabled(), GetIsMulticast(), GetMaximumLatency(), GetMaxSustainedTrafficRate(), GetMaxTrafficBurst(), GetMinReservedTrafficRate(), GetMinTolerableTrafficRate(), GetModulation(), GetQosParamSetType(), GetRecord(), GetRequestTransmissionPolicy(), GetSduSize(), GetServiceClassName(), GetServiceSchedulingType(), GetSfid(), GetTargetSAID(), GetToleratedJitter(), GetTrafficPriority(), GetType(), GetUnsolicitedGrantInterval(), GetUnsolicitedPollingInterval(), m_arqEnable, m_arqRetryTimeoutRx, m_arqRetryTimeoutTx, m_arqWindowSize, m_connection, m_convergenceSublayerParam, m_csSpecification, m_direction, m_fixedversusVariableSduIndicator, m_isEnabled, m_isMulticast, m_maximumLatency, m_maxSustainedTrafficRate, m_maxTrafficBurst, m_minReservedTrafficRate, m_minTolerableTrafficRate, m_modulationType, m_qosParamSetType, m_record, m_requestTransmissionPolicy, m_schedulingType, m_sduSize, m_serviceClassName, m_sfid, m_targetSAID, m_toleratedJitter, m_trafficPriority, m_type, m_unsolicitedGrantInterval, and m_unsolicitedPollingInterval.
ServiceFlow() [5/5]
ns3::ServiceFlow::ServiceFlow (uint32_t sfid, enum Direction direction, Ptr< WimaxConnection > connection)
Constructor.
Parameters
sfid the SFID
direction the direction
connection the connection object
Definition at line 57 of file service-flow.cc.
References InitValues(), m_connection, m_direction, m_isEnabled, m_isMulticast, m_modulationType, m_record, m_sfid, m_type, ns3::WimaxPhy::MODULATION_TYPE_QPSK_12, and SF_TYPE_PROVISIONED.
~ServiceFlow()
ns3::ServiceFlow::~ServiceFlow (void)
Definition at line 180 of file service-flow.cc.
References m_connection, and m_record.
Member Function Documentation
CheckClassifierMatch()
bool ns3::ServiceFlow::CheckClassifierMatch (Ipv4Address srcAddress, Ipv4Address dstAddress, uint16_t srcPort, uint16_t dstPort, uint8_t proto) const
Returns
true if the passed parameters match the classifier of the service flow, false otherwise
Parameters
srcAddress the source ip address
dstAddress the destination ip address
srcPort the source port
dstPort the destination port
proto the layer 4 protocol
Definition at line 837 of file service-flow.cc.
References ns3::IpcsClassifierRecord::CheckMatch(), ns3::CsParameters::GetPacketClassifierRule(), and m_convergenceSublayerParam.
CleanUpQueue()
void ns3::ServiceFlow::CleanUpQueue (void)
shall be called only by BS
Definition at line 288 of file service-flow.cc.
References GetMaximumLatency(), m_connection, ns3::MilliSeconds(), and ns3::Simulator::Now().
CopyParametersFrom()
void ns3::ServiceFlow::CopyParametersFrom (ServiceFlow sf)
Copy parameters from another service flow.
Parameters
sf the service flow
Definition at line 672 of file service-flow.cc.
References GetArqEnable(), GetArqRetryTimeoutRx(), GetArqRetryTimeoutTx(), GetArqWindowSize(), GetConvergenceSublayerParam(), GetCsSpecification(), GetDirection(), GetFixedversusVariableSduIndicator(), GetIsMulticast(), GetMaximumLatency(), GetMaxSustainedTrafficRate(), GetMaxTrafficBurst(), GetMinReservedTrafficRate(), GetMinTolerableTrafficRate(), GetModulation(), GetQosParamSetType(), GetRequestTransmissionPolicy(), GetSduSize(), GetServiceClassName(), GetServiceSchedulingType(), GetTargetSAID(), GetToleratedJitter(), GetTrafficPriority(), GetUnsolicitedGrantInterval(), GetUnsolicitedPollingInterval(), m_arqEnable, m_arqRetryTimeoutRx, m_arqRetryTimeoutTx, m_arqWindowSize, m_convergenceSublayerParam, m_csSpecification, m_direction, m_fixedversusVariableSduIndicator, m_isMulticast, m_maximumLatency, m_maxSustainedTrafficRate, m_maxTrafficBurst, m_minReservedTrafficRate, m_minTolerableTrafficRate, m_modulationType, m_qosParamSetType, m_requestTransmissionPolicy, m_schedulingType, m_sduSize, m_serviceClassName, m_targetSAID, m_toleratedJitter, m_trafficPriority, m_unsolicitedGrantInterval, and m_unsolicitedPollingInterval.
Referenced by ns3::BsServiceFlowManager::AddMulticastServiceFlow(), ns3::SsServiceFlowManager::AddServiceFlow(), and ns3::BsServiceFlowManager::ProcessDsaReq().
GetArqBlockLifeTime()
uint16_t ns3::ServiceFlow::GetArqBlockLifeTime (void) const
Get ARQ block lifetime.
Returns
the ARQ block lifetime
Definition at line 425 of file service-flow.cc.
References m_arqBlockLifeTime.
GetArqBlockSize()
uint16_t ns3::ServiceFlow::GetArqBlockSize (void) const
Get ARQ block size.
Returns
the ARQ block size
Definition at line 445 of file service-flow.cc.
References m_arqBlockSize.
GetArqDeliverInOrder()
uint8_t ns3::ServiceFlow::GetArqDeliverInOrder (void) const
Get ARQ deliver in order.
Returns
the ARQ deliver in order
Definition at line 435 of file service-flow.cc.
References m_arqDeliverInOrder.
GetArqEnable()
uint8_t ns3::ServiceFlow::GetArqEnable (void) const
Get ARQ enable.
Returns
the ARQ enable
Definition at line 404 of file service-flow.cc.
References m_arqEnable.
Referenced by ServiceFlow(), CopyParametersFrom(), and operator=().
GetArqPurgeTimeout()
uint16_t ns3::ServiceFlow::GetArqPurgeTimeout (void) const
Get ARQ purge timeout.
Returns
the ARQ purge timeout value
Definition at line 440 of file service-flow.cc.
References m_arqPurgeTimeout.
GetArqRetryTimeoutRx()
uint16_t ns3::ServiceFlow::GetArqRetryTimeoutRx (void) const
Get ARQ retry timeout receive.
Returns
the ARQ retry timeout receive
Definition at line 419 of file service-flow.cc.
References m_arqRetryTimeoutRx.
Referenced by ServiceFlow(), CopyParametersFrom(), and operator=().
GetArqRetryTimeoutTx()
uint16_t ns3::ServiceFlow::GetArqRetryTimeoutTx (void) const
Get ARQ retry timeout transmit.
Returns
the ARQ retry timeout transmit
Definition at line 414 of file service-flow.cc.
References m_arqRetryTimeoutTx.
Referenced by ServiceFlow(), CopyParametersFrom(), and operator=().
GetArqSyncLoss()
uint16_t ns3::ServiceFlow::GetArqSyncLoss (void) const
Get ARQ sync loss.
Returns
the ARQ sync loss value
Definition at line 430 of file service-flow.cc.
References m_arqSyncLoss.
GetArqWindowSize()
uint16_t ns3::ServiceFlow::GetArqWindowSize (void) const
Get ARQ retry timeout transmit.
Returns
the ARQ retry timeout
Definition at line 409 of file service-flow.cc.
References m_arqWindowSize.
Referenced by ServiceFlow(), CopyParametersFrom(), and operator=().
GetCid()
uint16_t ns3::ServiceFlow::GetCid (void) const
Get CID.
Returns
the CID
Definition at line 325 of file service-flow.cc.
References m_connection.
Referenced by ns3::SubscriberStationNetDevice::DoSend(), ns3::BsServiceFlowManager::ProcessDsaReq(), ns3::SsServiceFlowManager::ProcessDsaRsp(), and ToTlv().
GetConnection()
Ptr< WimaxConnection > ns3::ServiceFlow::GetConnection (void) const
Can return a null connection is this service flow has not been associated yet to a connection.
Returns
pointer to the WimaxConnection
Definition at line 222 of file service-flow.cc.
References m_connection.
Referenced by ServiceFlow(), ns3::BSSchedulerRtps::CreateUgsBurst(), ns3::BSSchedulerSimple::CreateUgsBurst(), ns3::BaseStationNetDevice::DoSend(), ns3::SubscriberStationNetDevice::DoSend(), operator=(), ns3::BandwidthManager::SendBandwidthRequest(), ns3::UplinkSchedulerMBQoS::ServiceBandwidthRequests(), ns3::UplinkSchedulerRtps::ServiceBandwidthRequests(), ns3::UplinkSchedulerMBQoS::ServiceBandwidthRequestsBytes(), ns3::UplinkSchedulerMBQoS::ServiceUnsolicitedGrants(), ns3::UplinkSchedulerRtps::ServiceUnsolicitedGrants(), and ns3::UplinkSchedulerSimple::ServiceUnsolicitedGrants().
GetConvergenceSublayerParam()
CsParameters ns3::ServiceFlow::GetConvergenceSublayerParam (void) const
Get convergence sublayer.
Returns
the convergence sublayer
Definition at line 455 of file service-flow.cc.
References m_convergenceSublayerParam.
Referenced by ServiceFlow(), CopyParametersFrom(), operator=(), and ns3::BsServiceFlowManager::ProcessDsaReq().
GetCsSpecification()
enum ServiceFlow::CsSpecification ns3::ServiceFlow::GetCsSpecification (void) const
Get CS specification.
Returns
the CS specification
Definition at line 445 of file service-flow.cc.
Referenced by ServiceFlow(), CopyParametersFrom(), DsaRequestTestCase::DoRun(), Ns3WimaxSfTlvTestCase::DoRun(), and operator=().
GetDirection()
ServiceFlow::Direction ns3::ServiceFlow::GetDirection (void) const
Get direction.
Returns
the direction
Definition at line 197 of file service-flow.cc.
References m_direction.
Referenced by ServiceFlow(), CopyParametersFrom(), DsaRequestTestCase::DoRun(), Ns3WimaxSfTlvTestCase::DoRun(), operator=(), and ns3::BsServiceFlowManager::ProcessDsaReq().
GetFixedversusVariableSduIndicator()
uint8_t ns3::ServiceFlow::GetFixedversusVariableSduIndicator (void) const
Get fixed versus varaiable SDU indicator.
Returns
the fixed vs variable SDU indicator
Definition at line 389 of file service-flow.cc.
References m_fixedversusVariableSduIndicator.
Referenced by ServiceFlow(), CopyParametersFrom(), and operator=().
GetIsEnabled()
bool ns3::ServiceFlow::GetIsEnabled (void) const
Get is enabled flag.
Returns
is enabled
Definition at line 234 of file service-flow.cc.
References m_isEnabled.
Referenced by ServiceFlow(), ns3::BaseStationNetDevice::DoSend(), ns3::SubscriberStationNetDevice::DoSend(), and operator=().
GetIsMulticast()
bool ns3::ServiceFlow::GetIsMulticast (void) const
Get is multicast.
Returns
the is multicast flag
Definition at line 471 of file service-flow.cc.
References m_isMulticast.
Referenced by ServiceFlow(), CopyParametersFrom(), operator=(), ns3::UplinkSchedulerMBQoS::SetupServiceFlow(), ns3::UplinkSchedulerRtps::SetupServiceFlow(), and ns3::UplinkSchedulerSimple::SetupServiceFlow().
GetMaximumLatency()
uint32_t ns3::ServiceFlow::GetMaximumLatency (void) const
Get maximum latency.
Returns
the maximum latency
Definition at line 384 of file service-flow.cc.
References m_maximumLatency.
Referenced by ServiceFlow(), CleanUpQueue(), CopyParametersFrom(), ns3::UplinkSchedulerMBQoS::DetermineDeadline(), DsaRequestTestCase::DoRun(), Ns3WimaxSfTlvTestCase::DoRun(), and operator=().
GetMaxSustainedTrafficRate()
uint32_t ns3::ServiceFlow::GetMaxSustainedTrafficRate (void) const
Get max sustained traffic rate.
Returns
the maximum sustained traffic rate
Definition at line 349 of file service-flow.cc.
References m_maxSustainedTrafficRate.
Referenced by ServiceFlow(), CopyParametersFrom(), DsaRequestTestCase::DoRun(), Ns3WimaxSfTlvTestCase::DoRun(), and operator=().
GetMaxTrafficBurst()
uint32_t ns3::ServiceFlow::GetMaxTrafficBurst (void) const
Get max traffic burst.
Returns
the maximum traffic burst
Definition at line 354 of file service-flow.cc.
References m_maxTrafficBurst.
Referenced by ServiceFlow(), CopyParametersFrom(), DsaRequestTestCase::DoRun(), Ns3WimaxSfTlvTestCase::DoRun(), and operator=().
GetMinReservedTrafficRate()
uint32_t ns3::ServiceFlow::GetMinReservedTrafficRate (void) const
Get minimum reserved traffic rate.
Returns
the minimum reserved traffic rate
Definition at line 359 of file service-flow.cc.
References m_minReservedTrafficRate.
Referenced by ServiceFlow(), ns3::UplinkSchedulerMBQoS::CheckMinimumBandwidth(), CopyParametersFrom(), DsaRequestTestCase::DoRun(), Ns3WimaxSfTlvTestCase::DoRun(), operator=(), ns3::UplinkSchedulerMBQoS::SetupServiceFlow(), ns3::UplinkSchedulerRtps::SetupServiceFlow(), ns3::UplinkSchedulerSimple::SetupServiceFlow(), and ns3::UplinkSchedulerMBQoS::UplinkSchedWindowTimer().
GetMinTolerableTrafficRate()
uint32_t ns3::ServiceFlow::GetMinTolerableTrafficRate (void) const
Get minimum tolerable traffic rate.
Returns
the minimum tolerable traffic rate
Definition at line 364 of file service-flow.cc.
References m_minTolerableTrafficRate.
Referenced by ServiceFlow(), CopyParametersFrom(), DsaRequestTestCase::DoRun(), Ns3WimaxSfTlvTestCase::DoRun(), and operator=().
GetModulation()
enum WimaxPhy::ModulationType ns3::ServiceFlow::GetModulation (void) const
Get modulation.
Returns
the modulation
Definition at line 471 of file service-flow.cc.
Referenced by ServiceFlow(), CopyParametersFrom(), operator=(), ns3::UplinkSchedulerMBQoS::SetupServiceFlow(), ns3::UplinkSchedulerRtps::SetupServiceFlow(), and ns3::UplinkSchedulerSimple::SetupServiceFlow().
GetQosParamSetType()
uint8_t ns3::ServiceFlow::GetQosParamSetType (void) const
Get QOS parameter set type.
Returns
the QOS parameter set type
Definition at line 339 of file service-flow.cc.
References m_qosParamSetType.
Referenced by ServiceFlow(), CopyParametersFrom(), and operator=().
GetQueue()
Ptr< WimaxMacQueue > ns3::ServiceFlow::GetQueue (void) const
Get pointer to queue.
Returns
pointer to the wimax mac queue
Definition at line 252 of file service-flow.cc.
References m_connection.
Referenced by ns3::BandwidthManager::SelectFlowForRequest().
GetRecord()
ServiceFlowRecord * ns3::ServiceFlow::GetRecord (void) const
Get service flow record.
Returns
pointer to the service flow record
Definition at line 246 of file service-flow.cc.
References m_record.
Referenced by ServiceFlow(), ns3::BandwidthManager::CalculateAllocationSize(), ns3::UplinkSchedulerMBQoS::CheckMinimumBandwidth(), ns3::UplinkSchedulerMBQoS::CountSymbolsJobs(), ns3::UplinkSchedulerMBQoS::DetermineDeadline(), ns3::SubscriberStationNetDevice::DoReceive(), operator=(), ns3::UplinkSchedulerMBQoS::ServiceBandwidthRequests(), ns3::UplinkSchedulerRtps::ServiceBandwidthRequests(), ns3::UplinkSchedulerSimple::ServiceBandwidthRequests(), ns3::UplinkSchedulerMBQoS::ServiceBandwidthRequestsBytes(), ns3::UplinkSchedulerMBQoS::ServiceUnsolicitedGrants(), ns3::UplinkSchedulerRtps::ServiceUnsolicitedGrants(), ns3::UplinkSchedulerSimple::ServiceUnsolicitedGrants(), ns3::UplinkSchedulerMBQoS::SetupServiceFlow(), ns3::UplinkSchedulerRtps::SetupServiceFlow(), ns3::UplinkSchedulerSimple::SetupServiceFlow(), and ns3::UplinkSchedulerMBQoS::UplinkSchedWindowTimer().
GetRequestTransmissionPolicy()
uint32_t ns3::ServiceFlow::GetRequestTransmissionPolicy (void) const
Get request transmission policy.
Returns
the request transmission policy
Definition at line 374 of file service-flow.cc.
References m_requestTransmissionPolicy.
Referenced by ServiceFlow(), CopyParametersFrom(), and operator=().
GetSchedulingType()
enum ServiceFlow::SchedulingType ns3::ServiceFlow::GetSchedulingType (void) const
Get scheduling type.
Returns
the scheduling type
Definition at line 252 of file service-flow.cc.
Referenced by ns3::BandwidthManager::CalculateAllocationSize(), ns3::UplinkSchedulerMBQoS::CheckMinimumBandwidth(), ns3::WimaxConnection::GetSchedulingType(), ns3::UplinkSchedulerMBQoS::ProcessBandwidthRequest(), ns3::BandwidthManager::SelectFlowForRequest(), ns3::UplinkSchedulerMBQoS::ServiceUnsolicitedGrants(), ns3::UplinkSchedulerRtps::ServiceUnsolicitedGrants(), ns3::UplinkSchedulerSimple::ServiceUnsolicitedGrants(), ns3::UplinkSchedulerMBQoS::SetupServiceFlow(), ns3::UplinkSchedulerRtps::SetupServiceFlow(), ns3::UplinkSchedulerSimple::SetupServiceFlow(), and ns3::UplinkSchedulerMBQoS::UplinkSchedWindowTimer().
GetSchedulingTypeStr()
char * ns3::ServiceFlow::GetSchedulingTypeStr (void) const
Get scheduling type string.
Returns
the name of the scheduling type
Definition at line 781 of file service-flow.cc.
References m_schedulingType, NS_FATAL_ERROR, SF_TYPE_BE, SF_TYPE_NRTPS, SF_TYPE_RTPS, and SF_TYPE_UGS.
Referenced by ns3::UplinkSchedulerMBQoS::ServiceBandwidthRequests(), ns3::UplinkSchedulerRtps::ServiceBandwidthRequests(), ns3::UplinkSchedulerMBQoS::ServiceBandwidthRequestsBytes(), ns3::UplinkSchedulerMBQoS::ServiceUnsolicitedGrants(), and ns3::UplinkSchedulerRtps::ServiceUnsolicitedGrants().
GetSduSize()
uint8_t ns3::ServiceFlow::GetSduSize (void) const
Get SDU size.
Returns
the SDU size
Definition at line 394 of file service-flow.cc.
References m_sduSize.
Referenced by ServiceFlow(), ns3::UplinkSchedulerMBQoS::CheckMinimumBandwidth(), CopyParametersFrom(), ns3::UplinkSchedulerMBQoS::CountSymbolsJobs(), operator=(), ns3::UplinkSchedulerMBQoS::ServiceBandwidthRequests(), ns3::UplinkSchedulerRtps::ServiceBandwidthRequests(), ns3::UplinkSchedulerSimple::ServiceBandwidthRequests(), ns3::UplinkSchedulerRtps::SetupServiceFlow(), and ns3::UplinkSchedulerSimple::SetupServiceFlow().
GetServiceClassName()
std::string ns3::ServiceFlow::GetServiceClassName () const
Get service class name.
Returns
the service class name
Definition at line 334 of file service-flow.cc.
References m_serviceClassName.
Referenced by ServiceFlow(), CopyParametersFrom(), and operator=().
GetServiceSchedulingType()
enum ServiceFlow::SchedulingType ns3::ServiceFlow::GetServiceSchedulingType (void) const
Get service scheduling type.
Returns
the scheduling type
Definition at line 364 of file service-flow.cc.
Referenced by ServiceFlow(), CopyParametersFrom(), DsaRequestTestCase::DoRun(), Ns3WimaxSfTlvTestCase::DoRun(), and operator=().
GetSfid()
uint32_t ns3::ServiceFlow::GetSfid (void) const
Get SFID.
Returns
the SFID
Definition at line 320 of file service-flow.cc.
References m_sfid.
Referenced by ServiceFlow(), DsaRequestTestCase::DoRun(), Ns3WimaxSfTlvTestCase::DoRun(), ns3::SubscriberStationNetDevice::DoSend(), operator=(), ns3::BsServiceFlowManager::ProcessDsaReq(), ns3::UplinkSchedulerMBQoS::ServiceBandwidthRequests(), ns3::UplinkSchedulerRtps::ServiceBandwidthRequests(), ns3::UplinkSchedulerMBQoS::ServiceBandwidthRequestsBytes(), ns3::UplinkSchedulerMBQoS::ServiceUnsolicitedGrants(), ns3::UplinkSchedulerRtps::ServiceUnsolicitedGrants(), and ns3::UplinkSchedulerSimple::ServiceUnsolicitedGrants().
GetTargetSAID()
uint16_t ns3::ServiceFlow::GetTargetSAID (void) const
Get target SAID.
Returns
the target SAID
Definition at line 399 of file service-flow.cc.
References m_targetSAID.
Referenced by ServiceFlow(), CopyParametersFrom(), and operator=().
GetToleratedJitter()
uint32_t ns3::ServiceFlow::GetToleratedJitter (void) const
Get tolerated jitter.
Returns
the tolerated jitter
Definition at line 379 of file service-flow.cc.
References m_toleratedJitter.
Referenced by ServiceFlow(), CopyParametersFrom(), operator=(), ns3::UplinkSchedulerMBQoS::SetupServiceFlow(), ns3::UplinkSchedulerRtps::SetupServiceFlow(), and ns3::UplinkSchedulerSimple::SetupServiceFlow().
GetTrafficPriority()
uint8_t ns3::ServiceFlow::GetTrafficPriority (void) const
Get traffic priority.
Returns
the traffic priority
Definition at line 344 of file service-flow.cc.
References m_trafficPriority.
Referenced by ServiceFlow(), CopyParametersFrom(), DsaRequestTestCase::DoRun(), Ns3WimaxSfTlvTestCase::DoRun(), and operator=().
GetType()
ServiceFlow::Type ns3::ServiceFlow::GetType (void) const
Get type of service flow.
Returns
the type
Definition at line 209 of file service-flow.cc.
References m_type.
Referenced by ServiceFlow(), and operator=().
GetUnsolicitedGrantInterval()
uint16_t ns3::ServiceFlow::GetUnsolicitedGrantInterval (void) const
Get unsolicited grant interval.
Returns
the unsolicited grant interval
Definition at line 460 of file service-flow.cc.
References m_unsolicitedGrantInterval.
Referenced by ServiceFlow(), ns3::BandwidthManager::CalculateAllocationSize(), CopyParametersFrom(), and operator=().
GetUnsolicitedPollingInterval()
uint16_t ns3::ServiceFlow::GetUnsolicitedPollingInterval (void) const
Get unsolicited polling interval.
Returns
the unsolicited polling interval
Definition at line 465 of file service-flow.cc.
References m_unsolicitedPollingInterval.
Referenced by ServiceFlow(), ns3::BandwidthManager::CalculateAllocationSize(), CopyParametersFrom(), ns3::UplinkSchedulerMBQoS::CountSymbolsJobs(), and operator=().
HasPackets() [1/2]
bool ns3::ServiceFlow::HasPackets (MacHeaderType::HeaderType packetType) const
Check if packets of particular type are present.
Parameters
packetType the packet type to select
Returns
true if there are packets of the packet type
Definition at line 278 of file service-flow.cc.
References m_connection.
HasPackets() [2/2]
bool ns3::ServiceFlow::HasPackets (void) const
Check if packets are present.
Returns
true if there are packets
Definition at line 268 of file service-flow.cc.
References m_connection.
Referenced by ns3::BSSchedulerRtps::CreateUgsBurst(), ns3::BSSchedulerSimple::CreateUgsBurst(), and ns3::BandwidthManager::SelectFlowForRequest().
InitValues()
void ns3::ServiceFlow::InitValues (void)
Initial values.
Definition at line 636 of file service-flow.cc.
References IPV4, m_arqBlockLifeTime, m_arqBlockSize, m_arqDeliverInOrder, m_arqEnable, m_arqPurgeTimeout, m_arqRetryTimeoutRx, m_arqRetryTimeoutTx, m_arqSyncLoss, m_arqWindowSize, m_csSpecification, m_direction, m_fixedversusVariableSduIndicator, m_isMulticast, m_maximumLatency, m_maxSustainedTrafficRate, m_maxTrafficBurst, m_minReservedTrafficRate, m_minTolerableTrafficRate, m_modulationType, m_qosParamSetType, m_requestTransmissionPolicy, m_schedulingType, m_sduSize, m_serviceClassName, m_sfid, m_targetSAID, m_toleratedJitter, m_trafficPriority, m_type, m_unsolicitedGrantInterval, m_unsolicitedPollingInterval, ns3::WimaxPhy::MODULATION_TYPE_QPSK_12, SF_DIRECTION_DOWN, SF_TYPE_ACTIVE, and SF_TYPE_NONE.
Referenced by ServiceFlow().
operator=()
ServiceFlow & ns3::ServiceFlow::operator= (ServiceFlow const & o)
assignment operator
Parameters
o the service flow to assign
Returns
the service flow
Definition at line 737 of file service-flow.cc.
References GetArqEnable(), GetArqRetryTimeoutRx(), GetArqRetryTimeoutTx(), GetArqWindowSize(), GetConnection(), GetConvergenceSublayerParam(), GetCsSpecification(), GetDirection(), GetFixedversusVariableSduIndicator(), GetIsEnabled(), GetIsMulticast(), GetMaximumLatency(), GetMaxSustainedTrafficRate(), GetMaxTrafficBurst(), GetMinReservedTrafficRate(), GetMinTolerableTrafficRate(), GetModulation(), GetQosParamSetType(), GetRecord(), GetRequestTransmissionPolicy(), GetSduSize(), GetServiceClassName(), GetServiceSchedulingType(), GetSfid(), GetTargetSAID(), GetToleratedJitter(), GetTrafficPriority(), GetType(), GetUnsolicitedGrantInterval(), GetUnsolicitedPollingInterval(), m_arqEnable, m_arqRetryTimeoutRx, m_arqRetryTimeoutTx, m_arqWindowSize, m_connection, m_convergenceSublayerParam, m_csSpecification, m_direction, m_fixedversusVariableSduIndicator, m_isEnabled, m_isMulticast, m_maximumLatency, m_maxSustainedTrafficRate, m_maxTrafficBurst, m_minReservedTrafficRate, m_minTolerableTrafficRate, m_modulationType, m_qosParamSetType, m_record, m_requestTransmissionPolicy, m_schedulingType, m_sduSize, m_serviceClassName, m_sfid, m_targetSAID, m_toleratedJitter, m_trafficPriority, m_type, m_unsolicitedGrantInterval, and m_unsolicitedPollingInterval.
PrintQoSParameters()
void ns3::ServiceFlow::PrintQoSParameters (void) const
Print QOS parameters.
Definition at line 313 of file service-flow.cc.
SetArqBlockLifeTime()
void ns3::ServiceFlow::SetArqBlockLifeTime (uint16_t lifeTime)
Set ARQ block lifetime.
Parameters
lifeTime the ARQ block life time
Definition at line 580 of file service-flow.cc.
References m_arqBlockLifeTime.
SetArqBlockSize()
void ns3::ServiceFlow::SetArqBlockSize (uint16_t size)
Set ARQ block size.
Parameters
size the size
Definition at line 600 of file service-flow.cc.
References m_arqBlockSize.
SetArqDeliverInOrder()
void ns3::ServiceFlow::SetArqDeliverInOrder (uint8_t inOrder)
Set ARQ deliver in order.
Parameters
inOrder the deliver in order setting
Definition at line 590 of file service-flow.cc.
References m_arqDeliverInOrder.
SetArqEnable()
void ns3::ServiceFlow::SetArqEnable (uint8_t arqEnable)
Set ARQ enable.
Parameters
arqEnable the ARQ enable setting
Definition at line 560 of file service-flow.cc.
References m_arqEnable.
SetArqPurgeTimeout()
void ns3::ServiceFlow::SetArqPurgeTimeout (uint16_t timeout)
Set ARQ purge timeout.
Parameters
timeout the timeout value
Definition at line 595 of file service-flow.cc.
References m_arqPurgeTimeout, and timeout.
SetArqRetryTimeoutRx()
void ns3::ServiceFlow::SetArqRetryTimeoutRx (uint16_t timeout)
Set ARQ retry timeout receive.
Parameters
timeout the timeout
Definition at line 575 of file service-flow.cc.
References m_arqRetryTimeoutRx, and timeout.
SetArqRetryTimeoutTx()
void ns3::ServiceFlow::SetArqRetryTimeoutTx (uint16_t timeout)
Set ARQ retry timeout transmit.
Parameters
timeout the ARQ retry timeout transmit
Definition at line 570 of file service-flow.cc.
References m_arqRetryTimeoutTx, and timeout.
SetArqSyncLoss()
void ns3::ServiceFlow::SetArqSyncLoss (uint16_t syncLoss)
Set ARQ sync loss.
Parameters
syncLoss the ARQ sync loss
Definition at line 585 of file service-flow.cc.
References m_arqSyncLoss.
SetArqWindowSize()
void ns3::ServiceFlow::SetArqWindowSize (uint16_t arqWindowSize)
Set ARQ retry timeout transmit.
Parameters
arqWindowSize the ARQ retry timeout transmit
Definition at line 565 of file service-flow.cc.
References m_arqWindowSize.
SetConnection()
void ns3::ServiceFlow::SetConnection (Ptr< WimaxConnection > connection)
Set connection.
Parameters
connection the connection
Definition at line 215 of file service-flow.cc.
References m_connection.
Referenced by ns3::BsServiceFlowManager::AddMulticastServiceFlow(), and ns3::SsServiceFlowManager::ProcessDsaRsp().
SetConvergenceSublayerParam()
void ns3::ServiceFlow::SetConvergenceSublayerParam (CsParameters csparam)
Set convergence sublayer parameters.
Parameters
csparam the convergence sublayer parameters
Definition at line 610 of file service-flow.cc.
References m_convergenceSublayerParam.
Referenced by ns3::WimaxHelper::CreateServiceFlow(), DsaRequestTestCase::DoRun(), Ns3WimaxSfCreationTestCase::DoRun(), Ns3WimaxSfTlvTestCase::DoRun(), and ns3::BsServiceFlowManager::ProcessDsaReq().
SetCsSpecification()
void ns3::ServiceFlow::SetCsSpecification (enum CsSpecification spec)
Set CS specification.
Parameters
spec the CS specification
Definition at line 605 of file service-flow.cc.
References m_csSpecification.
Referenced by ns3::WimaxHelper::CreateServiceFlow(), DsaRequestTestCase::DoRun(), Ns3WimaxSfCreationTestCase::DoRun(), and Ns3WimaxSfTlvTestCase::DoRun().
SetDirection()
void ns3::ServiceFlow::SetDirection (enum Direction direction)
Set direction.
Parameters
direction the direction value
Definition at line 191 of file service-flow.cc.
References m_direction.
SetFixedversusVariableSduIndicator()
void ns3::ServiceFlow::SetFixedversusVariableSduIndicator (uint8_t sduIndicator)
Set fixed versus variable SDU indicator.
Parameters
sduIndicator fixed vs variable SDU indicator
Definition at line 545 of file service-flow.cc.
References m_fixedversusVariableSduIndicator.
SetIsEnabled()
void ns3::ServiceFlow::SetIsEnabled (bool isEnabled)
Set is enabled flag.
Parameters
isEnabled is enabled flag
Definition at line 228 of file service-flow.cc.
References m_isEnabled.
Referenced by ns3::BsServiceFlowManager::AddMulticastServiceFlow(), ns3::SsServiceFlowManager::ProcessDsaRsp(), and ns3::BsServiceFlowManager::ScheduleDsaRsp().
SetIsMulticast()
void ns3::ServiceFlow::SetIsMulticast (bool isMulticast)
Set is multicast.
Parameters
isMulticast the is multicast flag
Definition at line 625 of file service-flow.cc.
References m_isMulticast.
Referenced by ns3::BsServiceFlowManager::AddMulticastServiceFlow().
SetMaximumLatency()
void ns3::ServiceFlow::SetMaximumLatency (uint32_t MaximumLatency)
Set maximum latency.
Parameters
MaximumLatency the maximjum latency
Definition at line 540 of file service-flow.cc.
References m_maximumLatency.
Referenced by ns3::WimaxHelper::CreateServiceFlow(), DsaRequestTestCase::DoRun(), Ns3WimaxSfCreationTestCase::DoRun(), and Ns3WimaxSfTlvTestCase::DoRun().
SetMaxSustainedTrafficRate()
void ns3::ServiceFlow::SetMaxSustainedTrafficRate (uint32_t maxSustainedRate)
Set max sustained traffic rate.
Parameters
maxSustainedRate the maximum sustained traffic rate
Definition at line 505 of file service-flow.cc.
References m_maxSustainedTrafficRate.
Referenced by ns3::WimaxHelper::CreateServiceFlow(), DsaRequestTestCase::DoRun(), Ns3WimaxSfCreationTestCase::DoRun(), and Ns3WimaxSfTlvTestCase::DoRun().
SetMaxTrafficBurst()
void ns3::ServiceFlow::SetMaxTrafficBurst (uint32_t maxTrafficBurst)
Set maximum traffic burst.
Parameters
maxTrafficBurst the maximum traffic burst
Definition at line 510 of file service-flow.cc.
References m_maxTrafficBurst.
Referenced by ns3::WimaxHelper::CreateServiceFlow(), DsaRequestTestCase::DoRun(), Ns3WimaxSfCreationTestCase::DoRun(), and Ns3WimaxSfTlvTestCase::DoRun().
SetMinReservedTrafficRate()
void ns3::ServiceFlow::SetMinReservedTrafficRate (uint32_t minResvRate)
Set minimum reserved traffic rate.
Parameters
minResvRate the minimum reserved traffic rate
Definition at line 515 of file service-flow.cc.
References m_minReservedTrafficRate.
Referenced by ns3::WimaxHelper::CreateServiceFlow(), DsaRequestTestCase::DoRun(), Ns3WimaxSfCreationTestCase::DoRun(), and Ns3WimaxSfTlvTestCase::DoRun().
SetMinTolerableTrafficRate()
void ns3::ServiceFlow::SetMinTolerableTrafficRate (uint32_t minJitter)
Set minimum tolerable traffic rate.
Parameters
minJitter the minimum tolerable traffic rate
Definition at line 520 of file service-flow.cc.
References m_minTolerableTrafficRate.
Referenced by ns3::WimaxHelper::CreateServiceFlow(), DsaRequestTestCase::DoRun(), Ns3WimaxSfCreationTestCase::DoRun(), and Ns3WimaxSfTlvTestCase::DoRun().
SetModulation()
void ns3::ServiceFlow::SetModulation (enum WimaxPhy::ModulationType modulationType)
Set modulation.
Parameters
modulationType the modulation type
Definition at line 630 of file service-flow.cc.
References m_modulationType.
Referenced by ns3::BsServiceFlowManager::AddMulticastServiceFlow().
SetQosParamSetType()
void ns3::ServiceFlow::SetQosParamSetType (uint8_t type)
Set QOS parameter set type.
Parameters
type the QOS paraneter set type
Definition at line 495 of file service-flow.cc.
References m_qosParamSetType.
SetRecord()
void ns3::ServiceFlow::SetRecord (ServiceFlowRecord * record)
Set service flow record.
Parameters
record pointer to the service flow record
Definition at line 240 of file service-flow.cc.
References m_record.
SetRequestTransmissionPolicy()
void ns3::ServiceFlow::SetRequestTransmissionPolicy (uint32_t policy)
Set request transmission policy.
Parameters
policy the request transmission policy
Definition at line 530 of file service-flow.cc.
References m_requestTransmissionPolicy.
Referenced by ns3::WimaxHelper::CreateServiceFlow().
SetSduSize()
void ns3::ServiceFlow::SetSduSize (uint8_t sduSize)
Set SDU size.
Parameters
sduSize the SDU size
Definition at line 550 of file service-flow.cc.
References m_sduSize.
Referenced by ns3::WimaxHelper::CreateServiceFlow().
SetServiceClassName()
void ns3::ServiceFlow::SetServiceClassName (std::string name)
Set service class name.
Parameters
name the service class name
Definition at line 490 of file service-flow.cc.
References m_serviceClassName.
SetServiceSchedulingType()
void ns3::ServiceFlow::SetServiceSchedulingType (enum ServiceFlow::SchedulingType schedType)
Set service scheduling type.
Parameters
schedType the service scheduling type
Definition at line 525 of file service-flow.cc.
References m_schedulingType.
Referenced by ns3::WimaxHelper::CreateServiceFlow(), DsaRequestTestCase::DoRun(), Ns3WimaxSfCreationTestCase::DoRun(), and Ns3WimaxSfTlvTestCase::DoRun().
SetSfid()
void ns3::ServiceFlow::SetSfid (uint32_t sfid)
Set SFID.
Parameters
sfid the SFID
Definition at line 485 of file service-flow.cc.
References m_sfid.
Referenced by DsaRequestTestCase::DoRun(), and Ns3WimaxSfTlvTestCase::DoRun().
SetTargetSAID()
void ns3::ServiceFlow::SetTargetSAID (uint16_t targetSaid)
Set target SAID.
Parameters
targetSaid the target SAID value
Definition at line 555 of file service-flow.cc.
References m_targetSAID.
SetToleratedJitter()
void ns3::ServiceFlow::SetToleratedJitter (uint32_t jitter)
Set tolerated jitter.
Parameters
jitter the tolerated jitter
Definition at line 535 of file service-flow.cc.
References m_toleratedJitter.
Referenced by ns3::WimaxHelper::CreateServiceFlow().
SetTrafficPriority()
void ns3::ServiceFlow::SetTrafficPriority (uint8_t priority)
Set traffic priority.
Parameters
priority the traffic priority
Definition at line 500 of file service-flow.cc.
References m_trafficPriority.
Referenced by ns3::WimaxHelper::CreateServiceFlow(), DsaRequestTestCase::DoRun(), Ns3WimaxSfCreationTestCase::DoRun(), and Ns3WimaxSfTlvTestCase::DoRun().
SetType()
void ns3::ServiceFlow::SetType (enum Type type)
Set type of service flow.
Parameters
type the type value
Definition at line 203 of file service-flow.cc.
References m_type.
Referenced by ns3::BsServiceFlowManager::AddMulticastServiceFlow(), and ns3::BsServiceFlowManager::ScheduleDsaRsp().
SetUnsolicitedGrantInterval()
void ns3::ServiceFlow::SetUnsolicitedGrantInterval (uint16_t unsolicitedGrantInterval)
Set unsolicied grant interval.
Parameters
unsolicitedGrantInterval the unsolicited grant interval
Definition at line 615 of file service-flow.cc.
References m_unsolicitedGrantInterval.
Referenced by ns3::WimaxHelper::CreateServiceFlow(), ns3::BsServiceFlowManager::ProcessDsaReq(), ns3::SsServiceFlowManager::ProcessDsaRsp(), ns3::UplinkSchedulerMBQoS::SetupServiceFlow(), ns3::UplinkSchedulerRtps::SetupServiceFlow(), and ns3::UplinkSchedulerSimple::SetupServiceFlow().
SetUnsolicitedPollingInterval()
void ns3::ServiceFlow::SetUnsolicitedPollingInterval (uint16_t unsolicitedPollingInterval)
Set unsolicited polling interval.
Parameters
unsolicitedPollingInterval the unsolicited polling interval
Definition at line 620 of file service-flow.cc.
References m_unsolicitedPollingInterval.
Referenced by ns3::BsServiceFlowManager::ProcessDsaReq(), ns3::SsServiceFlowManager::ProcessDsaRsp(), ns3::UplinkSchedulerMBQoS::SetupServiceFlow(), ns3::UplinkSchedulerRtps::SetupServiceFlow(), and ns3::UplinkSchedulerSimple::SetupServiceFlow().
ToTlv()
Tlv ns3::ServiceFlow::ToTlv (void) const
creates a TLV from this service flow
Returns
the created tlv
Definition at line 804 of file service-flow.cc.
References ns3::VectorTlvValue::Add(), ns3::SfVectorTlvValue::CID, ns3::SfVectorTlvValue::CS_Specification, ns3::Tlv::DOWNLINK_SERVICE_FLOW, ns3::SfVectorTlvValue::Fixed_length_versus_Variable_length_SDU_Indicator, GetCid(), ns3::VectorTlvValue::GetSerializedSize(), m_convergenceSublayerParam, m_csSpecification, m_direction, m_fixedversusVariableSduIndicator, m_maximumLatency, m_maxSustainedTrafficRate, m_maxTrafficBurst, m_minReservedTrafficRate, m_minTolerableTrafficRate, m_qosParamSetType, m_requestTransmissionPolicy, m_schedulingType, m_sduSize, m_sfid, m_targetSAID, m_toleratedJitter, m_trafficPriority, ns3::SfVectorTlvValue::Maximum_Latency, ns3::SfVectorTlvValue::Maximum_Sustained_Traffic_Rate, ns3::SfVectorTlvValue::Maximum_Traffic_Burst, ns3::SfVectorTlvValue::Minimum_Reserved_Traffic_Rate, ns3::SfVectorTlvValue::Minimum_Tolerable_Traffic_Rate, ns3::SfVectorTlvValue::QoS_Parameter_Set_Type, ns3::SfVectorTlvValue::Request_Transmission_Policy, ns3::SfVectorTlvValue::SDU_Size, ns3::SfVectorTlvValue::Service_Flow_Scheduling_Type, SF_DIRECTION_UP, ns3::SfVectorTlvValue::SFID, ns3::SfVectorTlvValue::Target_SAID, ns3::SfVectorTlvValue::Tolerated_Jitter, ns3::CsParameters::ToTlv(), ns3::SfVectorTlvValue::Traffic_Priority, and ns3::Tlv::UPLINK_SERVICE_FLOW.
Referenced by Ns3WimaxSfTlvTestCase::DoRun(), ns3::DsaReq::GetSerializedSize(), ns3::DsaRsp::GetSerializedSize(), ns3::DsaReq::Serialize(), and ns3::DsaRsp::Serialize().
Member Data Documentation
m_arqBlockLifeTime
uint16_t ns3::ServiceFlow::m_arqBlockLifeTime private
ARQ block life time.
Definition at line 574 of file service-flow.h.
Referenced by GetArqBlockLifeTime(), InitValues(), and SetArqBlockLifeTime().
m_arqBlockSize
uint16_t ns3::ServiceFlow::m_arqBlockSize private
ARQ block size.
Definition at line 578 of file service-flow.h.
Referenced by GetArqBlockSize(), InitValues(), and SetArqBlockSize().
m_arqDeliverInOrder
uint8_t ns3::ServiceFlow::m_arqDeliverInOrder private
ARQ deliver in order.
Definition at line 576 of file service-flow.h.
Referenced by GetArqDeliverInOrder(), InitValues(), and SetArqDeliverInOrder().
m_arqEnable
uint8_t ns3::ServiceFlow::m_arqEnable private
ARQ enable.
Definition at line 570 of file service-flow.h.
Referenced by ServiceFlow(), CopyParametersFrom(), GetArqEnable(), InitValues(), operator=(), and SetArqEnable().
m_arqPurgeTimeout
uint16_t ns3::ServiceFlow::m_arqPurgeTimeout private
ARQ purge timeout.
Definition at line 577 of file service-flow.h.
Referenced by GetArqPurgeTimeout(), InitValues(), and SetArqPurgeTimeout().
m_arqRetryTimeoutRx
uint16_t ns3::ServiceFlow::m_arqRetryTimeoutRx private
ARQ retry timeout receive.
Definition at line 573 of file service-flow.h.
Referenced by ServiceFlow(), CopyParametersFrom(), GetArqRetryTimeoutRx(), InitValues(), operator=(), and SetArqRetryTimeoutRx().
m_arqRetryTimeoutTx
uint16_t ns3::ServiceFlow::m_arqRetryTimeoutTx private
ARQ retry timeout transmit.
Definition at line 572 of file service-flow.h.
Referenced by ServiceFlow(), CopyParametersFrom(), GetArqRetryTimeoutTx(), InitValues(), operator=(), and SetArqRetryTimeoutTx().
m_arqSyncLoss
uint16_t ns3::ServiceFlow::m_arqSyncLoss private
ARQ sync loss.
Definition at line 575 of file service-flow.h.
Referenced by GetArqSyncLoss(), InitValues(), and SetArqSyncLoss().
m_arqWindowSize
uint16_t ns3::ServiceFlow::m_arqWindowSize private
ARQ window size.
Definition at line 571 of file service-flow.h.
Referenced by ServiceFlow(), CopyParametersFrom(), GetArqWindowSize(), InitValues(), operator=(), and SetArqWindowSize().
m_connection
Ptr<WimaxConnection> ns3::ServiceFlow::m_connection private
connection
Definition at line 585 of file service-flow.h.
Referenced by ServiceFlow(), ~ServiceFlow(), CleanUpQueue(), GetCid(), GetConnection(), GetQueue(), HasPackets(), operator=(), and SetConnection().
m_convergenceSublayerParam
CsParameters ns3::ServiceFlow::m_convergenceSublayerParam private
convergence sublayer parameters
Definition at line 580 of file service-flow.h.
Referenced by ServiceFlow(), CheckClassifierMatch(), CopyParametersFrom(), GetConvergenceSublayerParam(), operator=(), SetConvergenceSublayerParam(), and ToTlv().
m_csSpecification
enum CsSpecification ns3::ServiceFlow::m_csSpecification private
CS specification.
Definition at line 578 of file service-flow.h.
Referenced by ServiceFlow(), CopyParametersFrom(), InitValues(), operator=(), SetCsSpecification(), and ToTlv().
m_direction
Direction ns3::ServiceFlow::m_direction private
direction
Definition at line 583 of file service-flow.h.
Referenced by ServiceFlow(), CopyParametersFrom(), GetDirection(), InitValues(), operator=(), SetDirection(), and ToTlv().
m_fixedversusVariableSduIndicator
uint8_t ns3::ServiceFlow::m_fixedversusVariableSduIndicator private
fixed versus variable SDI indicator
Definition at line 567 of file service-flow.h.
Referenced by ServiceFlow(), CopyParametersFrom(), GetFixedversusVariableSduIndicator(), InitValues(), operator=(), SetFixedversusVariableSduIndicator(), and ToTlv().
m_isEnabled
bool ns3::ServiceFlow::m_isEnabled private
is enabled?
Definition at line 586 of file service-flow.h.
Referenced by ServiceFlow(), GetIsEnabled(), operator=(), and SetIsEnabled().
m_isMulticast
bool ns3::ServiceFlow::m_isMulticast private
is multicast?
Definition at line 587 of file service-flow.h.
Referenced by ServiceFlow(), CopyParametersFrom(), GetIsMulticast(), InitValues(), operator=(), and SetIsMulticast().
m_maximumLatency
uint32_t ns3::ServiceFlow::m_maximumLatency private
maximum latency
Definition at line 566 of file service-flow.h.
Referenced by ServiceFlow(), CopyParametersFrom(), GetMaximumLatency(), InitValues(), operator=(), SetMaximumLatency(), and ToTlv().
m_maxSustainedTrafficRate
uint32_t ns3::ServiceFlow::m_maxSustainedTrafficRate private
maximum sustained traffic rate
Definition at line 559 of file service-flow.h.
Referenced by ServiceFlow(), CopyParametersFrom(), GetMaxSustainedTrafficRate(), InitValues(), operator=(), SetMaxSustainedTrafficRate(), and ToTlv().
m_maxTrafficBurst
uint32_t ns3::ServiceFlow::m_maxTrafficBurst private
maximum traffic burst
Definition at line 560 of file service-flow.h.
Referenced by ServiceFlow(), CopyParametersFrom(), GetMaxTrafficBurst(), InitValues(), operator=(), SetMaxTrafficBurst(), and ToTlv().
m_minReservedTrafficRate
uint32_t ns3::ServiceFlow::m_minReservedTrafficRate private
minimum reserved traffic rate
Definition at line 561 of file service-flow.h.
Referenced by ServiceFlow(), CopyParametersFrom(), GetMinReservedTrafficRate(), InitValues(), operator=(), SetMinReservedTrafficRate(), and ToTlv().
m_minTolerableTrafficRate
uint32_t ns3::ServiceFlow::m_minTolerableTrafficRate private
minimum tolerable traffic rate
Definition at line 562 of file service-flow.h.
Referenced by ServiceFlow(), CopyParametersFrom(), GetMinTolerableTrafficRate(), InitValues(), operator=(), SetMinTolerableTrafficRate(), and ToTlv().
m_modulationType
enum WimaxPhy::ModulationType ns3::ServiceFlow::m_modulationType private
modulation type
Definition at line 587 of file service-flow.h.
Referenced by ServiceFlow(), CopyParametersFrom(), InitValues(), operator=(), and SetModulation().
m_qosParamSetType
uint8_t ns3::ServiceFlow::m_qosParamSetType private
QOS parameter type.
Definition at line 557 of file service-flow.h.
Referenced by ServiceFlow(), CopyParametersFrom(), GetQosParamSetType(), InitValues(), operator=(), SetQosParamSetType(), and ToTlv().
m_record
ServiceFlowRecord* ns3::ServiceFlow::m_record private
service flow record
Definition at line 590 of file service-flow.h.
Referenced by ServiceFlow(), ~ServiceFlow(), GetRecord(), operator=(), and SetRecord().
m_requestTransmissionPolicy
uint32_t ns3::ServiceFlow::m_requestTransmissionPolicy private
request transmission policy
Definition at line 564 of file service-flow.h.
Referenced by ServiceFlow(), CopyParametersFrom(), GetRequestTransmissionPolicy(), InitValues(), operator=(), SetRequestTransmissionPolicy(), and ToTlv().
m_schedulingType
enum ServiceFlow::SchedulingType ns3::ServiceFlow::m_schedulingType private
scheduling type
Definition at line 562 of file service-flow.h.
Referenced by ServiceFlow(), CopyParametersFrom(), GetSchedulingTypeStr(), InitValues(), operator=(), SetServiceSchedulingType(), and ToTlv().
m_sduSize
uint8_t ns3::ServiceFlow::m_sduSize private
SDU size.
Definition at line 568 of file service-flow.h.
Referenced by ServiceFlow(), CopyParametersFrom(), GetSduSize(), InitValues(), operator=(), SetSduSize(), and ToTlv().
m_serviceClassName
std::string ns3::ServiceFlow::m_serviceClassName private
service class name
Definition at line 556 of file service-flow.h.
Referenced by ServiceFlow(), CopyParametersFrom(), GetServiceClassName(), InitValues(), operator=(), and SetServiceClassName().
m_sfid
uint32_t ns3::ServiceFlow::m_sfid private
SFID.
Definition at line 555 of file service-flow.h.
Referenced by ServiceFlow(), GetSfid(), InitValues(), operator=(), SetSfid(), and ToTlv().
m_targetSAID
uint16_t ns3::ServiceFlow::m_targetSAID private
traget SAID
Definition at line 569 of file service-flow.h.
Referenced by ServiceFlow(), CopyParametersFrom(), GetTargetSAID(), InitValues(), operator=(), SetTargetSAID(), and ToTlv().
m_toleratedJitter
uint32_t ns3::ServiceFlow::m_toleratedJitter private
tolerated jitter
Definition at line 565 of file service-flow.h.
Referenced by ServiceFlow(), CopyParametersFrom(), GetToleratedJitter(), InitValues(), operator=(), SetToleratedJitter(), and ToTlv().
m_trafficPriority
uint8_t ns3::ServiceFlow::m_trafficPriority private
traffic priority
Definition at line 558 of file service-flow.h.
Referenced by ServiceFlow(), CopyParametersFrom(), GetTrafficPriority(), InitValues(), operator=(), SetTrafficPriority(), and ToTlv().
m_type
Type ns3::ServiceFlow::m_type private
type
Definition at line 584 of file service-flow.h.
Referenced by ServiceFlow(), GetType(), InitValues(), operator=(), and SetType().
m_unsolicitedGrantInterval
uint16_t ns3::ServiceFlow::m_unsolicitedGrantInterval private
unsolicited grant interval
Definition at line 581 of file service-flow.h.
Referenced by ServiceFlow(), CopyParametersFrom(), GetUnsolicitedGrantInterval(), InitValues(), operator=(), and SetUnsolicitedGrantInterval().
m_unsolicitedPollingInterval
uint16_t ns3::ServiceFlow::m_unsolicitedPollingInterval private
unsolicited polling interval
Definition at line 582 of file service-flow.h.
Referenced by ServiceFlow(), CopyParametersFrom(), GetUnsolicitedPollingInterval(), InitValues(), operator=(), and SetUnsolicitedPollingInterval().
The documentation for this class was generated from the following files:
src/wimax/model/service-flow.h
src/wimax/model/service-flow.cc