ns-3: ns3::SimpleNetDeviceHelper Class Reference
ns3::SimpleNetDeviceHelper Class Reference
build a set of SimpleNetDevice objects
#include "simple-net-device-helper.h"
Public Member Functions
SimpleNetDeviceHelper ()
Construct a SimpleNetDeviceHelper.
virtual ~SimpleNetDeviceHelper ()
NetDeviceContainer Install (const NodeContainer &c) const
This method creates an ns3::SimpleChannel with the attributes configured by SimpleNetDeviceHelper::SetChannelAttribute.
NetDeviceContainer Install (const NodeContainer &c, Ptr< SimpleChannel > channel) const
For each Ptr<node> in the provided container, this method creates an ns3::SimpleNetDevice (with the attributes configured by SimpleNetDeviceHelper::SetDeviceAttribute); adds the device to the node; and attaches the provided channel to the device.
NetDeviceContainer Install (Ptr< Node > node) const
This method creates an ns3::SimpleChannel with the attributes configured by SimpleNetDeviceHelper::SetChannelAttribute, an ns3::SimpleNetDevice with the attributes configured by SimpleNetDeviceHelper::SetDeviceAttribute and then adds the device to the node and attaches the channel to the device.
NetDeviceContainer Install (Ptr< Node > node, Ptr< SimpleChannel > channel) const
This method creates an ns3::SimpleNetDevice with the attributes configured by SimpleNetDeviceHelper::SetDeviceAttribute and then adds the device to the node and attaches the provided channel to the device.
void SetChannel (std::string type, std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue())
Each net device must have a channel to pass packets through.
void SetChannelAttribute (std::string n1, const AttributeValue &v1)
void SetDeviceAttribute (std::string n1, const AttributeValue &v1)
void SetNetDevicePointToPointMode (bool pointToPointMode)
SimpleNetDevice is Broadcast capable and ARP needing.
void SetQueue (std::string type, std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue())
Each net device must have a queue to pass packets through.
Private Member Functions
Ptr< NetDevice > InstallPriv (Ptr< Node > node, Ptr< SimpleChannel > channel) const
This method creates an ns3::SimpleNetDevice with the attributes configured by SimpleNetDeviceHelper::SetDeviceAttribute and then adds the device to the node and attaches the provided channel to the device.
Private Attributes
ObjectFactory m_channelFactory
Channel factory.
ObjectFactory m_deviceFactory
NetDevice factory.
bool m_pointToPointMode
Install PointToPoint SimpleNetDevice or Broadcast ones.
ObjectFactory m_queueFactory
Queue factory.
Detailed Description
build a set of SimpleNetDevice objects
Definition at line 36 of file simple-net-device-helper.h.
Constructor & Destructor Documentation
SimpleNetDeviceHelper()
ns3::SimpleNetDeviceHelper::SimpleNetDeviceHelper ()
Construct a SimpleNetDeviceHelper.
Definition at line 43 of file simple-net-device-helper.cc.
References m_channelFactory, m_deviceFactory, m_pointToPointMode, m_queueFactory, and ns3::ObjectFactory::SetTypeId().
~SimpleNetDeviceHelper()
virtual ns3::SimpleNetDeviceHelper::~SimpleNetDeviceHelper () inline virtual
Definition at line 43 of file simple-net-device-helper.h.
Member Function Documentation
Install() [1/4]
NetDeviceContainer ns3::SimpleNetDeviceHelper::Install (const NodeContainer & c) const
This method creates an ns3::SimpleChannel with the attributes configured by SimpleNetDeviceHelper::SetChannelAttribute.
For each Ptr<node> in the provided container: it creates an ns3::SimpleNetDevice (with the attributes configured by SimpleNetDeviceHelper::SetDeviceAttribute); adds the device to the node; and attaches the channel to the device.
Parameters
c The NodeContainer holding the nodes to be changed.
Returns
A container holding the added net devices.
Definition at line 113 of file simple-net-device-helper.cc.
References third::channel, ns3::ObjectFactory::Create(), Install(), and m_channelFactory.
Install() [2/4]
NetDeviceContainer ns3::SimpleNetDeviceHelper::Install (const NodeContainer & c, Ptr< SimpleChannel > channel) const
For each Ptr<node> in the provided container, this method creates an ns3::SimpleNetDevice (with the attributes configured by SimpleNetDeviceHelper::SetDeviceAttribute); adds the device to the node; and attaches the provided channel to the device.
Parameters
c The NodeContainer holding the nodes to be changed.
channel The channel to attach to the devices.
Returns
A container holding the added net devices.
Definition at line 121 of file simple-net-device-helper.cc.
References ns3::NetDeviceContainer::Add(), ns3::NodeContainer::Begin(), third::channel, ns3::NodeContainer::End(), and InstallPriv().
Install() [3/4]
NetDeviceContainer ns3::SimpleNetDeviceHelper::Install (Ptr< Node > node) const
This method creates an ns3::SimpleChannel with the attributes configured by SimpleNetDeviceHelper::SetChannelAttribute, an ns3::SimpleNetDevice with the attributes configured by SimpleNetDeviceHelper::SetDeviceAttribute and then adds the device to the node and attaches the channel to the device.
Parameters
node The node to install the device in
Returns
A container holding the added net device.
Definition at line 100 of file simple-net-device-helper.cc.
References third::channel, ns3::ObjectFactory::Create(), and m_channelFactory.
Referenced by ns3::olsr::Bug780Test::CreateNodes(), ns3::olsr::HelloRegressionTest::CreateNodes(), ns3::olsr::TcRegressionTest::CreateNodes(), BulkSendBasicTestCase::DoRun(), BulkSendSeqTsSizeTestCase::DoRun(), DhcpTestCase::DoRun(), IcmpTimeExceedTestCase::DoRun(), IcmpV6TimeExceedTestCase::DoRun(), Ipv4DeduplicationTest::DoRun(), Ipv4DeduplicationPerformanceTest::DoRun(), Ipv4FragmentationTest::DoRun(), Ipv4DynamicGlobalRoutingTestCase::DoRun(), Ipv4GlobalRoutingSlash32TestCase::DoRun(), Ipv4PacketInfoTagTest::DoRun(), Ipv4RawSocketImplTest::DoRun(), Ipv4StaticRoutingSlash32TestCase::DoRun(), Ipv6DadTest::DoRun(), Ipv6ForwardingTest::DoRun(), Ipv6PacketInfoTagTest::DoRun(), Ipv6RawSocketImplTest::DoRun(), ns3::TcpGeneralTest::DoRun(), UdpSocketImplTest::DoRun(), Udp6SocketImplTest::DoRun(), TcFlowControlTestCase::DoRun(), LinkTest::DoSetup(), LanTest::DoSetup(), TwoLinkTest::DoSetup(), TwoLanTest::DoSetup(), BridgeTest::DoSetup(), TwoBridgeTest::DoSetup(), and Install().
Install() [4/4]
NetDeviceContainer ns3::SimpleNetDeviceHelper::Install (Ptr< Node > node, Ptr< SimpleChannel > channel) const
This method creates an ns3::SimpleNetDevice with the attributes configured by SimpleNetDeviceHelper::SetDeviceAttribute and then adds the device to the node and attaches the provided channel to the device.
Parameters
node The node to install the device in
channel The channel to attach to the device.
Returns
A container holding the added net device.
Definition at line 107 of file simple-net-device-helper.cc.
References third::channel, and InstallPriv().
InstallPriv()
Ptr< NetDevice > ns3::SimpleNetDeviceHelper::InstallPriv (Ptr< Node > node, Ptr< SimpleChannel > channel) const private
This method creates an ns3::SimpleNetDevice with the attributes configured by SimpleNetDeviceHelper::SetDeviceAttribute and then adds the device to the node and attaches the provided channel to the device.
Parameters
node The node to install the device in
channel The channel to attach to the device.
Returns
The new net device.
Definition at line 134 of file simple-net-device-helper.cc.
References ns3::Node::AddDevice(), ns3::Mac48Address::Allocate(), third::channel, ns3::ObjectFactory::Create(), m_deviceFactory, m_pointToPointMode, m_queueFactory, and NS_ASSERT_MSG.
Referenced by Install().
SetChannel()
void ns3::SimpleNetDeviceHelper::SetChannel (std::string type, std::string n1 = "", const AttributeValue & v1 = EmptyAttributeValue (), std::string n2 = "", const AttributeValue & v2 = EmptyAttributeValue (), std::string n3 = "", const AttributeValue & v3 = EmptyAttributeValue (), std::string n4 = "", const AttributeValue & v4 = EmptyAttributeValue ())
Each net device must have a channel to pass packets through.
This method allows one to set the type of the channel that is automatically created when the device is created and attached to a node.
Parameters
type the type of queue
n1 the name of the attribute to set on the queue
v1 the value of the attribute to set on the queue
n2 the name of the attribute to set on the queue
v2 the value of the attribute to set on the queue
n3 the name of the attribute to set on the queue
v3 the value of the attribute to set on the queue
n4 the name of the attribute to set on the queue
v4 the value of the attribute to set on the queue
Set the type of channel to create and associated to each SimpleNetDevice created through SimpleNetDeviceHelper::Install.
Definition at line 68 of file simple-net-device-helper.cc.
References m_channelFactory, ns3::ObjectFactory::Set(), and ns3::ObjectFactory::SetTypeId().
SetChannelAttribute()
void ns3::SimpleNetDeviceHelper::SetChannelAttribute (std::string n1, const AttributeValue & v1)
Parameters
n1 the name of the attribute to set
v1 the value of the attribute to set
Set these attributes on each ns3::CsmaChannel created by SimpleNetDeviceHelper::Install
Definition at line 88 of file simple-net-device-helper.cc.
References m_channelFactory, and ns3::ObjectFactory::Set().
Referenced by ns3::olsr::Bug780Test::CreateNodes(), ns3::olsr::HelloRegressionTest::CreateNodes(), ns3::olsr::TcRegressionTest::CreateNodes(), BulkSendBasicTestCase::DoRun(), BulkSendSeqTsSizeTestCase::DoRun(), and DhcpTestCase::DoRun().
SetDeviceAttribute()
void ns3::SimpleNetDeviceHelper::SetDeviceAttribute (std::string n1, const AttributeValue & v1)
Parameters
n1 the name of the attribute to set
v1 the value of the attribute to set
Set these attributes on each ns3::SimpleNetDevice created by SimpleNetDeviceHelper::Install
Definition at line 82 of file simple-net-device-helper.cc.
References m_deviceFactory, and ns3::ObjectFactory::Set().
Referenced by ns3::olsr::Bug780Test::CreateNodes(), ns3::olsr::HelloRegressionTest::CreateNodes(), ns3::olsr::TcRegressionTest::CreateNodes(), BulkSendBasicTestCase::DoRun(), BulkSendSeqTsSizeTestCase::DoRun(), DhcpTestCase::DoRun(), and TcFlowControlTestCase::DoRun().
SetNetDevicePointToPointMode()
void ns3::SimpleNetDeviceHelper::SetNetDevicePointToPointMode (bool pointToPointMode)
SimpleNetDevice is Broadcast capable and ARP needing.
This function limits the number of SimpleNetDevices on one channel to two, disables Broadcast and ARP and enables PointToPoint mode.
Warning
It must be used before installing a NetDevice on a node.
Parameters
pointToPointMode True for PointToPoint SimpleNetDevice
Definition at line 94 of file simple-net-device-helper.cc.
References m_pointToPointMode.
Referenced by IcmpTimeExceedTestCase::DoRun(), IcmpV6TimeExceedTestCase::DoRun(), Ipv4FragmentationTest::DoRun(), Ipv4DynamicGlobalRoutingTestCase::DoRun(), Ipv4RawSocketImplTest::DoRun(), Ipv6DadTest::DoRun(), Ipv6ForwardingTest::DoRun(), Ipv6RawSocketImplTest::DoRun(), ns3::TcpGeneralTest::DoRun(), UdpSocketImplTest::DoRun(), Udp6SocketImplTest::DoRun(), LinkTest::DoSetup(), and TwoLinkTest::DoSetup().
SetQueue()
void ns3::SimpleNetDeviceHelper::SetQueue (std::string type, std::string n1 = "", const AttributeValue & v1 = EmptyAttributeValue (), std::string n2 = "", const AttributeValue & v2 = EmptyAttributeValue (), std::string n3 = "", const AttributeValue & v3 = EmptyAttributeValue (), std::string n4 = "", const AttributeValue & v4 = EmptyAttributeValue ())
Each net device must have a queue to pass packets through.
This method allows one to set the type of the queue that is automatically created when the device is created and attached to a node.
Parameters
type the type of queue
n1 the name of the attribute to set on the queue
v1 the value of the attribute to set on the queue
n2 the name of the attribute to set on the queue
v2 the value of the attribute to set on the queue
n3 the name of the attribute to set on the queue
v3 the value of the attribute to set on the queue
n4 the name of the attribute to set on the queue
v4 the value of the attribute to set on the queue
Set the type of queue to create and associated to each SimpleNetDevice created through SimpleNetDeviceHelper::Install.
Definition at line 52 of file simple-net-device-helper.cc.
References ns3::QueueBase::AppendItemTypeIfNotPresent(), m_queueFactory, ns3::ObjectFactory::Set(), and ns3::ObjectFactory::SetTypeId().
Referenced by TcFlowControlTestCase::DoRun().
Member Data Documentation
m_channelFactory
ObjectFactory ns3::SimpleNetDeviceHelper::m_channelFactory private
Channel factory.
Definition at line 183 of file simple-net-device-helper.h.
Referenced by SimpleNetDeviceHelper(), Install(), SetChannel(), and SetChannelAttribute().
m_deviceFactory
ObjectFactory ns3::SimpleNetDeviceHelper::m_deviceFactory private
NetDevice factory.
Definition at line 182 of file simple-net-device-helper.h.
Referenced by SimpleNetDeviceHelper(), InstallPriv(), and SetDeviceAttribute().
m_pointToPointMode
bool ns3::SimpleNetDeviceHelper::m_pointToPointMode private
Install PointToPoint SimpleNetDevice or Broadcast ones.
Definition at line 184 of file simple-net-device-helper.h.
Referenced by SimpleNetDeviceHelper(), InstallPriv(), and SetNetDevicePointToPointMode().
m_queueFactory
ObjectFactory ns3::SimpleNetDeviceHelper::m_queueFactory private
Queue factory.
Definition at line 181 of file simple-net-device-helper.h.
Referenced by SimpleNetDeviceHelper(), InstallPriv(), and SetQueue().
The documentation for this class was generated from the following files:
src/network/helper/simple-net-device-helper.h
src/network/helper/simple-net-device-helper.cc