ns-3: ns3::ErrorModel Class Reference
ns3::ErrorModel Class Reference abstract
Network » Error Model
General error model that can be used to corrupt packets.
#include "error-model.h"
Public Member Functions
ErrorModel ()
virtual ~ErrorModel ()
void Disable (void)
Disable the error model.
void Enable (void)
Enable the error model.
bool IsCorrupt (Ptr< Packet > pkt)
Note: Depending on the error model, this function may or may not alter the contents of the packet upon returning true.
bool IsEnabled (void) const
void Reset (void)
Reset any state associated with the error model.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual bool DoCorrupt (Ptr< Packet > p)=0
Corrupt a packet according to the specified model.
virtual void DoReset (void)=0
Re-initialize any state.
Private Attributes
bool m_enable
True if the error model is enabled.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
General error model that can be used to corrupt packets.
This object is used to flag packets as being lost/errored or not. It is part of the Object framework and can be aggregated to other ns3 objects and handled by the Ptr class.
The main method is IsCorrupt(Ptr<Packet> p) which returns true if the packet is to be corrupted according to the underlying model. Depending on the error model, the packet itself may have its packet data buffer errored or not, or side information may be returned to the client in the form of a packet tag. (Note: No such error models that actually error the bits in a packet presently exist). The object can have state (resettable by Reset()). The object can also be enabled and disabled via two public member functions.
Typical code (simplified) to use an ErrorModel may look something like this:
Ptr<ErrorModel> rem = CreateObject<RateErrorModel> ();
Ptr<UniformRandomVariable> uv = CreateObject<UniformRandomVariable> ();
rem->SetRandomVariable (uv);
rem->SetRate (0.001);
...
Ptr<Packet> p;
if (rem->IsCorrupt (p))
  {
    dropTrace(p);
  } else {
    Forward (p);
  }
Four practical error models, a RateErrorModel, a BurstErrorModel, a ListErrorModel, and a ReceiveListErrorModel, are currently implemented.
Config Paths
ns3::ErrorModel is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::SimpleNetDevice/ReceiveErrorModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Phy/PostReceptionErrorModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::PointToPointNetDevice/ReceiveErrorModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::CsmaNetDevice/ReceiveErrorModel"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/PhyEntities/[i]/PostReceptionErrorModel"
Attributes
IsEnabled: Whether this ErrorModel is enabled or not.
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 32 bytes (on a 64-bit architecture).
Definition at line 115 of file error-model.h.
Constructor & Destructor Documentation
ErrorModel()
ns3::ErrorModel::ErrorModel ()
Definition at line 95 of file error-model.cc.
References NS_LOG_FUNCTION.
~ErrorModel()
ns3::ErrorModel::~ErrorModel () virtual
Definition at line 101 of file error-model.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Disable()
void ns3::ErrorModel::Disable (void)
Disable the error model.
Definition at line 132 of file error-model.cc.
References m_enable, and NS_LOG_FUNCTION.
DoCorrupt()
virtual bool ns3::ErrorModel::DoCorrupt (Ptr< Packet > p) private pure virtual
Corrupt a packet according to the specified model.
Parameters
p the packet to corrupt
Returns
true if the packet is corrupted
Implemented in ns3::BinaryErrorModel, ns3::ReceiveListErrorModel, ns3::ListErrorModel, ns3::BurstErrorModel, ns3::RateErrorModel, and ns3::TcpGeneralErrorModel.
Referenced by IsCorrupt().
DoReset()
virtual void ns3::ErrorModel::DoReset (void) private pure virtual
Re-initialize any state.
Implemented in ns3::BinaryErrorModel, ns3::ReceiveListErrorModel, ns3::ListErrorModel, ns3::BurstErrorModel, ns3::RateErrorModel, ns3::TcpFlagErrorModel, ns3::TcpSeqErrorModel, and TcpDropRatioErrorModel.
Referenced by Reset().
Enable()
void ns3::ErrorModel::Enable (void)
Enable the error model.
Definition at line 125 of file error-model.cc.
References m_enable, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::ErrorModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 82 of file error-model.cc.
References m_enable, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), and ns3::TypeId::SetParent().
IsCorrupt()
bool ns3::ErrorModel::IsCorrupt (Ptr< Packet > pkt)
Note: Depending on the error model, this function may or may not alter the contents of the packet upon returning true.
Returns
true if the Packet is to be considered as errored/corrupted
Parameters
pkt Packet to apply error model to
Definition at line 107 of file error-model.cc.
References DoCorrupt(), and NS_LOG_FUNCTION.
IsEnabled()
bool ns3::ErrorModel::IsEnabled (void) const
Returns
true if error model is enabled; false otherwise
Definition at line 139 of file error-model.cc.
References m_enable, and NS_LOG_FUNCTION.
Referenced by ns3::TcpGeneralErrorModel::DoCorrupt(), ns3::RateErrorModel::DoCorrupt(), ns3::BurstErrorModel::DoCorrupt(), ns3::ListErrorModel::DoCorrupt(), ns3::ReceiveListErrorModel::DoCorrupt(), and ns3::BinaryErrorModel::DoCorrupt().
Reset()
void ns3::ErrorModel::Reset (void)
Reset any state associated with the error model.
Definition at line 118 of file error-model.cc.
References DoReset(), and NS_LOG_FUNCTION.
Member Data Documentation
m_enable
bool ns3::ErrorModel::m_enable private
True if the error model is enabled.
Definition at line 164 of file error-model.h.
Referenced by Disable(), Enable(), GetTypeId(), and IsEnabled().
The documentation for this class was generated from the following files:
src/network/utils/error-model.h
src/network/utils/error-model.cc