ns-3: FlameRegressionTest Class Reference
FlameRegressionTest Class Reference
Mesh Device » mesh module tests » flame sub-module tests | Test suites
FLAME protocol regression test of three stations:
#include "flame-regression.h"
Public Member Functions
FlameRegressionTest ()
virtual ~FlameRegressionTest ()
void CheckResults ()
Check results function.
virtual void DoRun ()
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CreateDevices ()
Create devices function.
void CreateNodes ()
Create nodes function.
void HandleReadClient (Ptr< Socket > socket)
Handle a packet reception.
void HandleReadServer (Ptr< Socket > socket)
Handle a packet reception.
void InstallApplications ()
Install application function.
void SendData (Ptr< Socket > socket)
Send data.
Private Attributes
Ptr< Socket > m_clientSocket
Client-side socket.
Ipv4InterfaceContainer m_interfaces
Needed to install applications.
NodeContainer * m_nodes
uint32_t m_sentPktsCounter
sent packets counter
Ptr< Socket > m_serverSocket
Server-side socket.
Time m_time
Simulation time.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
FLAME protocol regression test of three stations:
* <-----------|----------->   Broadcast frame
*             |----------->|  Unicast frame
*           Source                   Destination
* <-----------|----------->|            |             ARP request
*             |<-----------|----------->|             ARP request
*             |            |<-----------|             ARP reply
*             |<-----------|            |             ARP reply
*             |----------->|            |             Data
*             |            |----------->|             Data
*             |            |<-----------|-----------> PATH_UPDATE (no broadcast was sent)
*             |<-----------|----------->|             PATH_UPDATE
* <-----------|----------->|            |             PATH_UPDATE
*             |            |<-----------|-----------> ARP request
*             |<-----------|----------->|             ARP request
* <-----------|----------->|            |             ARP request
*             |----------->|            |             ARP reply
*             |            |----------->|             ARP reply
*             |            |<-----------|             Data
*             |<-----------|            |             Data
*             |............|............|
*             After five seconds data is transmitted again as
*             broadcast, and PATH_UPDATE is sent
*
Definition at line 64 of file flame-regression.h.
Constructor & Destructor Documentation
FlameRegressionTest()
FlameRegressionTest::FlameRegressionTest ()
Definition at line 44 of file flame-regression.cc.
~FlameRegressionTest()
FlameRegressionTest::~FlameRegressionTest () virtual
Definition at line 51 of file flame-regression.cc.
References m_nodes.
Member Function Documentation
CheckResults()
void FlameRegressionTest::CheckResults ()
Check results function.
Definition at line 144 of file flame-regression.cc.
References NS_PCAP_TEST_EXPECT_EQ, and PREFIX.
Referenced by DoRun().
CreateDevices()
void FlameRegressionTest::CreateDevices () private
Create devices function.
Definition at line 92 of file flame-regression.cc.
References first::address, ns3::MeshHelper::AssignStreams(), ns3::InternetStackHelper::AssignStreams(), ns3::YansWifiChannelHelper::AssignStreams(), ns3::YansWifiChannelHelper::Create(), ns3::TestCase::CreateTempDirFilename(), ns3::PcapHelperForDevice::EnablePcapAll(), ns3::NetDeviceContainer::GetN(), ns3::MeshHelper::Install(), ns3::InternetStackHelper::Install(), m_interfaces, m_nodes, NS_TEST_ASSERT_MSG_EQ, PREFIX, ns3::Seconds(), ns3::YansWifiPhyHelper::SetChannel(), ns3::WifiPhyHelper::SetErrorRateModel(), ns3::MeshHelper::SetMacType(), ns3::MeshHelper::SetNumberOfInterfaces(), and ns3::MeshHelper::SetStackInstaller().
Referenced by DoRun().
CreateNodes()
void FlameRegressionTest::CreateNodes () private
Create nodes function.
Definition at line 75 of file flame-regression.cc.
References ns3::NodeContainer::Create(), m_nodes, and third::mobility.
Referenced by DoRun().
DoRun()
void FlameRegressionTest::DoRun () virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 57 of file flame-regression.cc.
References CheckResults(), CreateDevices(), CreateNodes(), InstallApplications(), m_nodes, and m_time.
HandleReadClient()
void FlameRegressionTest::HandleReadClient (Ptr< Socket > socket) private
Handle a packet reception.
This function is called by lower layers.
Parameters
socket the socket the packet was received to.
Definition at line 179 of file flame-regression.cc.
References ns3::Socket::RecvFrom().
Referenced by InstallApplications().
HandleReadServer()
void FlameRegressionTest::HandleReadServer (Ptr< Socket > socket) private
Handle a packet reception.
This function is called by lower layers.
Parameters
socket the socket the packet was received to.
Definition at line 165 of file flame-regression.cc.
References ns3::Socket::RecvFrom(), ns3::Packet::RemoveAllByteTags(), ns3::Packet::RemoveAllPacketTags(), and ns3::Socket::SendTo().
Referenced by InstallApplications().
InstallApplications()
void FlameRegressionTest::InstallApplications () private
Install application function.
Definition at line 127 of file flame-regression.cc.
References ns3::Socket::Bind(), ns3::Socket::Connect(), ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::Node::GetId(), ns3::Socket::GetNode(), HandleReadClient(), HandleReadServer(), m_clientSocket, m_interfaces, m_nodes, m_serverSocket, ns3::MakeCallback(), ns3::Seconds(), SendData(), and ns3::Socket::SetRecvCallback().
Referenced by DoRun().
SendData()
void FlameRegressionTest::SendData (Ptr< Socket > socket) private
Send data.
Parameters
socket the sending socket
Definition at line 153 of file flame-regression.cc.
References ns3::Node::GetId(), ns3::Socket::GetNode(), m_sentPktsCounter, m_time, ns3::Now(), ns3::Seconds(), and ns3::Socket::Send().
Referenced by InstallApplications().
Member Data Documentation
m_clientSocket
Ptr<Socket> FlameRegressionTest::m_clientSocket private
Client-side socket.
Definition at line 92 of file flame-regression.h.
Referenced by InstallApplications().
m_interfaces
Ipv4InterfaceContainer FlameRegressionTest::m_interfaces private
Needed to install applications.
Definition at line 80 of file flame-regression.h.
Referenced by CreateDevices(), and InstallApplications().
m_nodes
NodeContainer* FlameRegressionTest::m_nodes private
Internal: It is important to have pointers here
Definition at line 76 of file flame-regression.h.
Referenced by ~FlameRegressionTest(), CreateDevices(), CreateNodes(), DoRun(), and InstallApplications().
m_sentPktsCounter
uint32_t FlameRegressionTest::m_sentPktsCounter private
sent packets counter
Definition at line 95 of file flame-regression.h.
Referenced by SendData().
m_serverSocket
Ptr<Socket> FlameRegressionTest::m_serverSocket private
Server-side socket.
Definition at line 90 of file flame-regression.h.
Referenced by InstallApplications().
m_time
Time FlameRegressionTest::m_time private
Simulation time.
Definition at line 78 of file flame-regression.h.
Referenced by DoRun(), and SendData().
The documentation for this class was generated from the following files:
src/mesh/test/flame/flame-regression.h
src/mesh/test/flame/flame-regression.cc