ns-3: ns3::Ipv6Prefix Class Reference
ns3::Ipv6Prefix Class Reference
Network » Address
Describes an IPv6 prefix.
#include "ipv6-address.h"
Public Member Functions
Ipv6Prefix ()
Default constructor.
Ipv6Prefix (char const *prefix)
Constructs an Ipv6Prefix by using the input string.
Ipv6Prefix (char const *prefix, uint8_t prefixLength)
Constructs an Ipv6Prefix by using the input string.
Ipv6Prefix (Ipv6Prefix const &prefix)
Copy constructor.
Ipv6Prefix (Ipv6Prefix const *prefix)
Copy constructor.
Ipv6Prefix (uint8_t prefix)
Constructs an Ipv6Prefix by using the input number of bits.
Ipv6Prefix (uint8_t prefix[16])
Constructs an Ipv6Prefix by using the input 16 bytes.
Ipv6Prefix (uint8_t prefix[16], uint8_t prefixLength)
Constructs an Ipv6Prefix by using the input 16 bytes.
~Ipv6Prefix ()
Destructor.
void GetBytes (uint8_t buf[16]) const
Get the bytes corresponding to the prefix.
uint8_t GetMinimumPrefixLength () const
Get the minimum prefix length, i.e., 128 - the length of the largest sequence trailing zeroes.
uint8_t GetPrefixLength () const
Get prefix length.
NS_DEPRECATED_3_31 bool IsEqual (const Ipv6Prefix &other) const
Comparison operation between two Ipv6Prefix.
bool IsMatch (Ipv6Address a, Ipv6Address b) const
If the Address match the type.
void Print (std::ostream &os) const
Print this address to the given output stream.
void SetPrefixLength (uint8_t prefixLength)
Set prefix length.
Static Public Member Functions
static Ipv6Prefix GetLoopback ()
Get the loopback prefix (/128).
static Ipv6Prefix GetOnes ()
Get the "all-1" IPv6 mask (ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff).
static Ipv6Prefix GetZero ()
Get the zero prefix (/0).
Private Attributes
uint8_t m_prefix [16]
The prefix representation.
uint8_t m_prefixLength
The prefix length.
Friends
bool operator!= (Ipv6Prefix const &a, Ipv6Prefix const &b)
Not equal to operator.
bool operator== (Ipv6Prefix const &a, Ipv6Prefix const &b)
Equal to operator.
Detailed Description
Describes an IPv6 prefix.
It is just a bitmask like Ipv4Mask.
See also
Ipv6Address
Ipv6Prefix Attribute
Definition at line 455 of file ipv6-address.h.
Constructor & Destructor Documentation
Ipv6Prefix() [1/8]
ns3::Ipv6Prefix::Ipv6Prefix ()
Default constructor.
Definition at line 957 of file ipv6-address.cc.
References m_prefix, m_prefixLength, and NS_LOG_FUNCTION.
Ipv6Prefix() [2/8]
ns3::Ipv6Prefix::Ipv6Prefix (uint8_t prefix[16])
Constructs an Ipv6Prefix by using the input 16 bytes.
The prefix length is calculated as the minimum prefix length, i.e., 2001:db8:cafe:: will have a 47 bit prefix length.
Parameters
prefix the 128-bit prefix
Definition at line 971 of file ipv6-address.cc.
References GetMinimumPrefixLength(), m_prefix, m_prefixLength, and NS_LOG_FUNCTION.
Ipv6Prefix() [3/8]
ns3::Ipv6Prefix::Ipv6Prefix (char const * prefix)
Constructs an Ipv6Prefix by using the input string.
The prefix length is calculated as the minimum prefix length, i.e., 2001:db8:cafe:: will have a 47 bit prefix length.
Parameters
prefix the 128-bit prefix
Definition at line 964 of file ipv6-address.cc.
References ns3::AsciiToIpv6Host(), GetMinimumPrefixLength(), m_prefix, m_prefixLength, and NS_LOG_FUNCTION.
Ipv6Prefix() [4/8]
ns3::Ipv6Prefix::Ipv6Prefix (uint8_t prefix[16], uint8_t prefixLength)
Constructs an Ipv6Prefix by using the input 16 bytes.
Parameters
prefix the 128-bit prefix
prefixLength the prefix length
Definition at line 989 of file ipv6-address.cc.
References GetMinimumPrefixLength(), m_prefix, m_prefixLength, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
Ipv6Prefix() [5/8]
ns3::Ipv6Prefix::Ipv6Prefix (char const * prefix, uint8_t prefixLength)
Constructs an Ipv6Prefix by using the input string.
Parameters
prefix the 128-bit prefix
prefixLength the prefix length
Definition at line 978 of file ipv6-address.cc.
References ns3::AsciiToIpv6Host(), GetMinimumPrefixLength(), m_prefix, m_prefixLength, NS_ASSERT_MSG, and NS_LOG_FUNCTION.
Ipv6Prefix() [6/8]
ns3::Ipv6Prefix::Ipv6Prefix (uint8_t prefix)
Constructs an Ipv6Prefix by using the input number of bits.
Parameters
prefix number of bits of the prefix (0 - 128)
Note
A valid number of bits is between 0 and 128).
Definition at line 1000 of file ipv6-address.cc.
References m_prefix, m_prefixLength, NS_ASSERT, and NS_LOG_FUNCTION.
Ipv6Prefix() [7/8]
ns3::Ipv6Prefix::Ipv6Prefix (Ipv6Prefix const & prefix)
Copy constructor.
Parameters
prefix Ipv6Prefix object
Definition at line 1036 of file ipv6-address.cc.
References m_prefix, and m_prefixLength.
Ipv6Prefix() [8/8]
ns3::Ipv6Prefix::Ipv6Prefix (Ipv6Prefix const * prefix)
Copy constructor.
Parameters
prefix Ipv6Prefix pointer
Definition at line 1042 of file ipv6-address.cc.
References m_prefix, and m_prefixLength.
~Ipv6Prefix()
ns3::Ipv6Prefix::~Ipv6Prefix ()
Destructor.
Definition at line 1048 of file ipv6-address.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
GetBytes()
void ns3::Ipv6Prefix::GetBytes (uint8_t buf[16]) const
Get the bytes corresponding to the prefix.
Parameters
buf buffer to store the data
Definition at line 1103 of file ipv6-address.cc.
References m_prefix, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv6AddressGeneratorImpl::Init(), and ns3::Ipv6AddressGeneratorImpl::PrefixToIndex().
GetLoopback()
Ipv6Prefix ns3::Ipv6Prefix::GetLoopback (void) static
Get the loopback prefix (/128).
Returns
a Ipv6Prefix corresponding to loopback prefix
Definition at line 1082 of file ipv6-address.cc.
References NS_LOG_FUNCTION_NOARGS.
GetMinimumPrefixLength()
uint8_t ns3::Ipv6Prefix::GetMinimumPrefixLength () const
Get the minimum prefix length, i.e., 128 - the length of the largest sequence trailing zeroes.
Returns
minimum prefix length
Definition at line 1121 of file ipv6-address.cc.
References m_prefix, and NS_LOG_FUNCTION.
Referenced by Ipv6Prefix().
GetOnes()
Ipv6Prefix ns3::Ipv6Prefix::GetOnes (void) static
Get the "all-1" IPv6 mask (ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff).
Returns
/128 Ipv6Prefix representation
Definition at line 1089 of file ipv6-address.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Ipv6StaticRouting::AddHostRouteTo(), ns3::Ipv6RoutingTableEntry::CreateHostRouteTo(), and ns3::Ipv6RoutingTableEntry::IsHost().
GetPrefixLength()
uint8_t ns3::Ipv6Prefix::GetPrefixLength (void) const
Get prefix length.
Returns
prefix length
Definition at line 1109 of file ipv6-address.cc.
References m_prefixLength, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv6StaticRouting::GetDefaultRoute(), ns3::RipNg::Lookup(), ns3::Ipv6StaticRouting::LookupStatic(), ns3::Ipv6AddressHelper::NewNetwork(), ns3::operator<<(), Print(), ns3::Ipv6StaticRouting::PrintRoutingTable(), and ns3::RipNg::PrintRoutingTable().
GetZero()
Ipv6Prefix ns3::Ipv6Prefix::GetZero (void) static
Get the zero prefix (/0).
Returns
an Ipv6Prefix
Definition at line 1096 of file ipv6-address.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::RipNg::AddDefaultRouteTo(), ns3::RipNg::DoSendRouteUpdate(), ns3::RipNg::HandleRequests(), and ns3::Ipv6StaticRouting::SetDefaultRoute().
IsEqual()
bool ns3::Ipv6Prefix::IsEqual (const Ipv6Prefix & other) const
Comparison operation between two Ipv6Prefix.
Deprecated:
Use the == operator (same functionality)
Parameters
other the IPv6 prefix to which to compare this prefix
Returns
true if the prefixes are equal, false otherwise
Definition at line 1149 of file ipv6-address.cc.
References m_prefix.
IsMatch()
bool ns3::Ipv6Prefix::IsMatch (Ipv6Address a, Ipv6Address b) const
If the Address match the type.
Parameters
a a first address
b a second address
Returns
true if the type match, false otherwise
Definition at line 1054 of file ipv6-address.cc.
References ns3::Ipv6Address::GetBytes(), m_prefix, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv6Interface::GetAddressMatchingDestination(), ns3::Ipv6StaticRouting::HasNetworkDest(), ns3::RipNg::Lookup(), and ns3::Ipv6StaticRouting::LookupStatic().
Print()
void ns3::Ipv6Prefix::Print (std::ostream & os) const
Print this address to the given output stream.
The print format is in the typical "2001:660:4701::1".
Parameters
os the output stream to which this Ipv6Address is printed
Definition at line 1075 of file ipv6-address.cc.
References GetPrefixLength(), and NS_LOG_FUNCTION.
Referenced by ns3::operator<<().
SetPrefixLength()
void ns3::Ipv6Prefix::SetPrefixLength (uint8_t prefixLength)
Set prefix length.
Parameters
prefixLength the prefix length
Definition at line 1115 of file ipv6-address.cc.
References m_prefixLength, and NS_LOG_FUNCTION.
Friends And Related Function Documentation
operator!=
bool operator!= (Ipv6Prefix const & a, Ipv6Prefix const & b) friend
Not equal to operator.
Parameters
a the first operand
b the first operand
Returns
true if the operands are not equal
Definition at line 679 of file ipv6-address.h.
operator==
bool operator== (Ipv6Prefix const & a, Ipv6Prefix const & b) friend
Equal to operator.
Parameters
a the first operand
b the first operand
Returns
true if the operands are equal
Definition at line 674 of file ipv6-address.h.
Member Data Documentation
m_prefix
uint8_t ns3::Ipv6Prefix::m_prefix[16] private
The prefix representation.
Definition at line 594 of file ipv6-address.h.
Referenced by Ipv6Prefix(), GetBytes(), GetMinimumPrefixLength(), IsEqual(), and IsMatch().
m_prefixLength
uint8_t ns3::Ipv6Prefix::m_prefixLength private
The prefix length.
Definition at line 599 of file ipv6-address.h.
Referenced by Ipv6Prefix(), GetPrefixLength(), and SetPrefixLength().
The documentation for this class was generated from the following files:
src/network/utils/ipv6-address.h
src/network/utils/ipv6-address.cc