ns-3: ns3::WifiPhyStateHelper Class Reference
ns3::WifiPhyStateHelper Class Reference
Wifi Models
This objects implements the PHY state machine of the Wifi device.
#include "wifi-phy-state-helper.h"
Public Types
typedef void(* RxEndErrorTracedCallback) (Ptr< const Packet > packet, double snr)
TracedCallback signature for receive end error event.
typedef void(* RxOkTracedCallback) (Ptr< const Packet > packet, double snr, WifiMode mode, WifiPreamble preamble)
TracedCallback signature for receive end OK event.
typedef void(* StateTracedCallback) (Time start, Time duration, WifiPhyState state)
TracedCallback signature for state changes.
typedef void(* TxTracedCallback) (Ptr< const Packet > packet, WifiMode mode, WifiPreamble preamble, uint8_t power)
TracedCallback signature for transmit event.
Public Member Functions
WifiPhyStateHelper ()
void ContinueRxNextMpdu (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector)
Continue RX after the reception of an MPDU in an A-MPDU was successful.
Time GetDelayUntilIdle (void) const
Return the time before the state is back to IDLE.
Time GetLastRxEndTime (void) const
Return the time the last RX end.
Time GetLastRxStartTime (void) const
Return the time the last RX start.
WifiPhyState GetState (void) const
Return the current state of WifiPhy.
bool IsStateCcaBusy (void) const
Check whether the current state is CCA busy.
bool IsStateIdle (void) const
Check whether the current state is IDLE.
bool IsStateOff (void) const
Check whether the current state is OFF.
bool IsStateRx (void) const
Check whether the current state is RX.
bool IsStateSleep (void) const
Check whether the current state is SLEEP.
bool IsStateSwitching (void) const
Check whether the current state is SWITCHING.
bool IsStateTx (void) const
Check whether the current state is TX.
void RegisterListener (WifiPhyListener *listener)
Register WifiPhyListener to this WifiPhyStateHelper.
void SetReceiveErrorCallback (RxErrorCallback callback)
Set a callback for a failed reception.
void SetReceiveOkCallback (RxOkCallback callback)
Set a callback for a successful reception.
void SwitchFromOff (Time duration)
Switch from off mode.
void SwitchFromRxAbort (void)
Abort current reception.
void SwitchFromRxEndError (Ptr< WifiPsdu > psdu, double snr)
Switch from RX after the reception failed.
void SwitchFromRxEndOk (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector, uint16_t staId, std::vector< bool > statusPerMpdu)
Switch from RX after the reception was successful.
void SwitchFromSleep (Time duration)
Switch from sleep mode.
void SwitchMaybeToCcaBusy (Time duration)
Switch to CCA busy.
void SwitchToChannelSwitching (Time switchingDuration)
Switch state to channel switching for the given duration.
void SwitchToOff (void)
Switch to off mode.
void SwitchToRx (Time rxDuration)
Switch state to RX for the given duration.
void SwitchToSleep (void)
Switch to sleep mode.
void SwitchToTx (Time txDuration, WifiConstPsduMap psdus, double txPowerDbm, WifiTxVector txVector)
Switch state to TX for the given duration.
void UnregisterListener (WifiPhyListener *listener)
Remove WifiPhyListener from this WifiPhyStateHelper.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef std::vector< WifiPhyListener * > Listeners
typedef for a list of WifiPhyListeners
typedef std::vector< WifiPhyListener * >::iterator ListenersI
typedef for a list of WifiPhyListeners iterator
Private Member Functions
void DoSwitchFromRx (void)
Switch the state from RX.
void LogPreviousIdleAndCcaBusyStates (void)
Log the ideal and CCA states.
void NotifyMaybeCcaBusyStart (Time duration)
Notify all WifiPhyListener that the CCA has started for the given duration.
void NotifyOff (void)
Notify all WifiPhyListener that we are going to switch off.
void NotifyOn (void)
Notify all WifiPhyListener that we are going to switch on.
void NotifyRxEndError (void)
Notify all WifiPhyListener that the reception was not successful.
void NotifyRxEndOk (void)
Notify all WifiPhyListener that the reception was successful.
void NotifyRxStart (Time duration)
Notify all WifiPhyListener that the reception has started for the given duration.
void NotifySleep (void)
Notify all WifiPhyListener that we are going to sleep.
void NotifySwitchingStart (Time duration)
Notify all WifiPhyListener that we are switching channel with the given channel switching delay.
void NotifyTxStart (Time duration, double txPowerDbm)
Notify all WifiPhyListener that the transmission has started for the given duration.
void NotifyWakeup (void)
Notify all WifiPhyListener that we woke up.
Private Attributes
Time m_endCcaBusy
end CCA busy
Time m_endRx
end receive
Time m_endSwitching
end switching
Time m_endTx
end transmit
bool m_isOff
switched off
Listeners m_listeners
listeners
Time m_previousStateChangeTime
previous state change time
RxErrorCallback m_rxErrorCallback
receive error callback
TracedCallback< Ptr< const Packet >, double > m_rxErrorTrace
receive error trace callback
RxOkCallback m_rxOkCallback
receive OK callback
TracedCallback< Ptr< const Packet >, double, WifiMode, WifiPreamble > m_rxOkTrace
receive OK trace callback
bool m_sleeping
sleeping
Time m_startCcaBusy
start CCA busy
Time m_startRx
start receive
Time m_startSleep
start sleep
Time m_startSwitching
start switching
Time m_startTx
start transmit
TracedCallback< Time, Time, WifiPhyState > m_stateLogger
The trace source fired when state is changed.
TracedCallback< Ptr< const Packet >, WifiMode, WifiPreamble, uint8_t > m_txTrace
transmit trace callback
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This objects implements the PHY state machine of the Wifi device.
Config Paths
ns3::WifiPhyStateHelper is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::WifiNetDevice/Phy/State"
"/NodeList/[i]/DeviceList/[i]/$ns3::WaveNetDevice/PhyEntities/[i]/State"
No Attributes are defined for this type.
TraceSources
State: The state of the PHY layer
Callback signature: ns3::WifiPhyStateHelper::StateTracedCallback
RxOk: A packet has been received successfully.
Callback signature: ns3::WifiPhyStateHelper::RxOkTracedCallback
RxError: A packet has been received unsuccessfully.
Callback signature: ns3::WifiPhyStateHelper::RxEndErrorTracedCallback
Tx: Packet transmission is starting.
Callback signature: ns3::WifiPhyStateHelper::TxTracedCallback
Size of this type is 256 bytes (on a 64-bit architecture).
Definition at line 63 of file wifi-phy-state-helper.h.
Member Typedef Documentation
Listeners
typedef std::vector<WifiPhyListener *> ns3::WifiPhyStateHelper::Listeners private
typedef for a list of WifiPhyListeners
Definition at line 286 of file wifi-phy-state-helper.h.
ListenersI
typedef std::vector<WifiPhyListener *>::iterator ns3::WifiPhyStateHelper::ListenersI private
typedef for a list of WifiPhyListeners iterator
Definition at line 290 of file wifi-phy-state-helper.h.
RxEndErrorTracedCallback
typedef void(* ns3::WifiPhyStateHelper::RxEndErrorTracedCallback) (Ptr< const Packet > packet, double snr)
TracedCallback signature for receive end error event.
Parameters
[in] packet The received packet.
[in] snr The SNR of the received packet in linear scale.
Definition at line 268 of file wifi-phy-state-helper.h.
RxOkTracedCallback
typedef void(* ns3::WifiPhyStateHelper::RxOkTracedCallback) (Ptr< const Packet > packet, double snr, WifiMode mode, WifiPreamble preamble)
TracedCallback signature for receive end OK event.
Parameters
[in] packet The received packet.
[in] snr The SNR of the received packet in linear scale.
[in] mode The transmission mode of the packet.
[in] preamble The preamble of the packet.
Definition at line 260 of file wifi-phy-state-helper.h.
StateTracedCallback
typedef void(* ns3::WifiPhyStateHelper::StateTracedCallback) (Time start, Time duration, WifiPhyState state)
TracedCallback signature for state changes.
Parameters
[in] start Time when the state started.
[in] duration Amount of time we've been in (or will be in) the state.
[in] state The state.
Definition at line 250 of file wifi-phy-state-helper.h.
TxTracedCallback
typedef void(* ns3::WifiPhyStateHelper::TxTracedCallback) (Ptr< const Packet > packet, WifiMode mode, WifiPreamble preamble, uint8_t power)
TracedCallback signature for transmit event.
Parameters
[in] packet The received packet.
[in] mode The transmission mode of the packet.
[in] preamble The preamble of the packet.
[in] power The transmit power level.
Definition at line 278 of file wifi-phy-state-helper.h.
Constructor & Destructor Documentation
WifiPhyStateHelper()
ns3::WifiPhyStateHelper::WifiPhyStateHelper ()
Definition at line 62 of file wifi-phy-state-helper.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
ContinueRxNextMpdu()
void ns3::WifiPhyStateHelper::ContinueRxNextMpdu (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector)
Continue RX after the reception of an MPDU in an A-MPDU was successful.
Parameters
psdu the successfully received PSDU
snr the SNR of the received PSDU in linear scale
txVector TXVECTOR of the PSDU
Definition at line 467 of file wifi-phy-state-helper.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_rxOkCallback, and NS_LOG_FUNCTION.
DoSwitchFromRx()
void ns3::WifiPhyStateHelper::DoSwitchFromRx (void) private
Switch the state from RX.
Definition at line 508 of file wifi-phy-state-helper.cc.
References IsStateCcaBusy(), IsStateIdle(), m_endRx, m_previousStateChangeTime, m_startRx, m_stateLogger, ns3::Simulator::Now(), NS_ASSERT, NS_LOG_FUNCTION, and RX.
Referenced by SwitchFromRxAbort(), SwitchFromRxEndError(), and SwitchFromRxEndOk().
GetDelayUntilIdle()
Time ns3::WifiPhyStateHelper::GetDelayUntilIdle (void) const
Return the time before the state is back to IDLE.
Returns
the delay before the state is back to IDLE
Definition at line 150 of file wifi-phy-state-helper.cc.
References CCA_BUSY, GetState(), IDLE, m_endCcaBusy, m_endRx, m_endSwitching, m_endTx, ns3::Max(), ns3::Simulator::Now(), NS_FATAL_ERROR, OFF, RX, ns3::Seconds(), SLEEP, SWITCHING, and TX.
GetLastRxEndTime()
Time ns3::WifiPhyStateHelper::GetLastRxEndTime (void) const
Return the time the last RX end.
Returns
the time the last RX end.
Definition at line 189 of file wifi-phy-state-helper.cc.
References m_endRx.
GetLastRxStartTime()
Time ns3::WifiPhyStateHelper::GetLastRxStartTime (void) const
Return the time the last RX start.
Returns
the time the last RX start.
Definition at line 183 of file wifi-phy-state-helper.cc.
References m_startRx.
GetState()
WifiPhyState ns3::WifiPhyStateHelper::GetState (void) const
Return the current state of WifiPhy.
Returns
the current state of WifiPhy
Definition at line 195 of file wifi-phy-state-helper.cc.
References CCA_BUSY, IDLE, m_endCcaBusy, m_endRx, m_endSwitching, m_endTx, m_isOff, m_sleeping, ns3::Simulator::Now(), OFF, RX, SLEEP, SWITCHING, and TX.
Referenced by GetDelayUntilIdle(), IsStateCcaBusy(), IsStateIdle(), IsStateOff(), IsStateRx(), IsStateSleep(), IsStateSwitching(), IsStateTx(), SwitchMaybeToCcaBusy(), SwitchToChannelSwitching(), SwitchToOff(), SwitchToRx(), SwitchToSleep(), and SwitchToTx().
GetTypeId()
TypeId ns3::WifiPhyStateHelper::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 37 of file wifi-phy-state-helper.cc.
References m_rxErrorTrace, m_rxOkTrace, m_stateLogger, m_txTrace, ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
IsStateCcaBusy()
bool ns3::WifiPhyStateHelper::IsStateCcaBusy (void) const
Check whether the current state is CCA busy.
Returns
true if the current state is CCA busy, false otherwise
Definition at line 114 of file wifi-phy-state-helper.cc.
References CCA_BUSY, and GetState().
Referenced by DoSwitchFromRx(), and SwitchToRx().
IsStateIdle()
bool ns3::WifiPhyStateHelper::IsStateIdle (void) const
Check whether the current state is IDLE.
Returns
true if the current state is IDLE, false otherwise
Definition at line 108 of file wifi-phy-state-helper.cc.
References GetState(), and IDLE.
Referenced by DoSwitchFromRx(), SwitchFromRxAbort(), and SwitchToRx().
IsStateOff()
bool ns3::WifiPhyStateHelper::IsStateOff (void) const
Check whether the current state is OFF.
Returns
true if the current state is OFF, false otherwise
Definition at line 144 of file wifi-phy-state-helper.cc.
References GetState(), and OFF.
Referenced by SwitchFromOff(), and SwitchToOff().
IsStateRx()
bool ns3::WifiPhyStateHelper::IsStateRx (void) const
Check whether the current state is RX.
Returns
true if the current state is RX, false otherwise
Definition at line 120 of file wifi-phy-state-helper.cc.
References GetState(), and RX.
Referenced by SwitchFromRxAbort(), and SwitchToRx().
IsStateSleep()
bool ns3::WifiPhyStateHelper::IsStateSleep (void) const
Check whether the current state is SLEEP.
Returns
true if the current state is SLEEP, false otherwise
Definition at line 138 of file wifi-phy-state-helper.cc.
References GetState(), and SLEEP.
Referenced by SwitchFromSleep(), and SwitchToSleep().
IsStateSwitching()
bool ns3::WifiPhyStateHelper::IsStateSwitching (void) const
Check whether the current state is SWITCHING.
Returns
true if the current state is SWITCHING, false otherwise
Definition at line 132 of file wifi-phy-state-helper.cc.
References GetState(), and SWITCHING.
Referenced by SwitchToChannelSwitching().
IsStateTx()
bool ns3::WifiPhyStateHelper::IsStateTx (void) const
Check whether the current state is TX.
Returns
true if the current state is TX, false otherwise
Definition at line 126 of file wifi-phy-state-helper.cc.
References GetState(), and TX.
LogPreviousIdleAndCcaBusyStates()
void ns3::WifiPhyStateHelper::LogPreviousIdleAndCcaBusyStates (void) private
Log the ideal and CCA states.
Definition at line 328 of file wifi-phy-state-helper.cc.
References CCA_BUSY, IDLE, ns3::Time::IsStrictlyPositive(), m_endCcaBusy, m_endRx, m_endSwitching, m_endTx, m_startCcaBusy, m_stateLogger, ns3::Max(), ns3::Simulator::Now(), NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by SwitchMaybeToCcaBusy(), SwitchToChannelSwitching(), SwitchToOff(), SwitchToRx(), SwitchToSleep(), and SwitchToTx().
NotifyMaybeCcaBusyStart()
void ns3::WifiPhyStateHelper::NotifyMaybeCcaBusyStart (Time duration) private
Notify all WifiPhyListener that the CCA has started for the given duration.
Parameters
duration the duration of the CCA state
Definition at line 268 of file wifi-phy-state-helper.cc.
References m_listeners, and NS_LOG_FUNCTION.
Referenced by SwitchFromOff(), SwitchFromRxAbort(), SwitchFromSleep(), and SwitchMaybeToCcaBusy().
NotifyOff()
void ns3::WifiPhyStateHelper::NotifyOff (void) private
Notify all WifiPhyListener that we are going to switch off.
Definition at line 298 of file wifi-phy-state-helper.cc.
References m_listeners, and NS_LOG_FUNCTION.
Referenced by SwitchToOff().
NotifyOn()
void ns3::WifiPhyStateHelper::NotifyOn (void) private
Notify all WifiPhyListener that we are going to switch on.
Definition at line 318 of file wifi-phy-state-helper.cc.
References m_listeners, and NS_LOG_FUNCTION.
Referenced by SwitchFromOff().
NotifyRxEndError()
void ns3::WifiPhyStateHelper::NotifyRxEndError (void) private
Notify all WifiPhyListener that the reception was not successful.
Definition at line 258 of file wifi-phy-state-helper.cc.
References m_listeners, and NS_LOG_FUNCTION.
Referenced by SwitchFromRxEndError().
NotifyRxEndOk()
void ns3::WifiPhyStateHelper::NotifyRxEndOk (void) private
Notify all WifiPhyListener that the reception was successful.
Definition at line 248 of file wifi-phy-state-helper.cc.
References m_listeners, and NS_LOG_FUNCTION.
Referenced by SwitchFromRxAbort(), and SwitchFromRxEndOk().
NotifyRxStart()
void ns3::WifiPhyStateHelper::NotifyRxStart (Time duration) private
Notify all WifiPhyListener that the reception has started for the given duration.
Parameters
duration the duration of the reception
Definition at line 238 of file wifi-phy-state-helper.cc.
References m_listeners, and NS_LOG_FUNCTION.
Referenced by SwitchToRx().
NotifySleep()
void ns3::WifiPhyStateHelper::NotifySleep (void) private
Notify all WifiPhyListener that we are going to sleep.
Definition at line 288 of file wifi-phy-state-helper.cc.
References m_listeners, and NS_LOG_FUNCTION.
Referenced by SwitchToSleep().
NotifySwitchingStart()
void ns3::WifiPhyStateHelper::NotifySwitchingStart (Time duration) private
Notify all WifiPhyListener that we are switching channel with the given channel switching delay.
Parameters
duration the delay to switch the channel
Definition at line 278 of file wifi-phy-state-helper.cc.
References m_listeners, and NS_LOG_FUNCTION.
Referenced by SwitchToChannelSwitching().
NotifyTxStart()
void ns3::WifiPhyStateHelper::NotifyTxStart (Time duration, double txPowerDbm) private
Notify all WifiPhyListener that the transmission has started for the given duration.
Parameters
duration the duration of the transmission
txPowerDbm the nominal TX power in dBm
Definition at line 228 of file wifi-phy-state-helper.cc.
References m_listeners, and NS_LOG_FUNCTION.
Referenced by SwitchToTx().
NotifyWakeup()
void ns3::WifiPhyStateHelper::NotifyWakeup (void) private
Notify all WifiPhyListener that we woke up.
Definition at line 308 of file wifi-phy-state-helper.cc.
References m_listeners, and NS_LOG_FUNCTION.
Referenced by SwitchFromSleep().
RegisterListener()
void ns3::WifiPhyStateHelper::RegisterListener (WifiPhyListener * listener)
Register WifiPhyListener to this WifiPhyStateHelper.
Parameters
listener the WifiPhyListener to register
Definition at line 92 of file wifi-phy-state-helper.cc.
References m_listeners.
SetReceiveErrorCallback()
void ns3::WifiPhyStateHelper::SetReceiveErrorCallback (RxErrorCallback callback)
Set a callback for a failed reception.
Parameters
callback the RxErrorCallback to set
Definition at line 86 of file wifi-phy-state-helper.cc.
References m_rxErrorCallback.
SetReceiveOkCallback()
void ns3::WifiPhyStateHelper::SetReceiveOkCallback (RxOkCallback callback)
Set a callback for a successful reception.
Parameters
callback the RxOkCallback to set
Definition at line 80 of file wifi-phy-state-helper.cc.
References m_rxOkCallback.
SwitchFromOff()
void ns3::WifiPhyStateHelper::SwitchFromOff (Time duration)
Switch from off mode.
Parameters
duration the duration of CCA busy state
Definition at line 644 of file wifi-phy-state-helper.cc.
References IsStateOff(), m_endCcaBusy, m_isOff, m_previousStateChangeTime, max, NotifyMaybeCcaBusyStart(), NotifyOn(), ns3::Simulator::Now(), NS_ASSERT, and NS_LOG_FUNCTION.
SwitchFromRxAbort()
void ns3::WifiPhyStateHelper::SwitchFromRxAbort (void)
Abort current reception.
Definition at line 591 of file wifi-phy-state-helper.cc.
References DoSwitchFromRx(), IsStateIdle(), IsStateRx(), m_endCcaBusy, NotifyMaybeCcaBusyStart(), NotifyRxEndOk(), ns3::Simulator::Now(), NS_ASSERT, NS_LOG_FUNCTION, and ns3::Seconds().
SwitchFromRxEndError()
void ns3::WifiPhyStateHelper::SwitchFromRxEndError (Ptr< WifiPsdu > psdu, double snr)
Switch from RX after the reception failed.
Parameters
psdu the PSDU that we failed to received
snr the SNR of the received PSDU in linear scale
Definition at line 494 of file wifi-phy-state-helper.cc.
References DoSwitchFromRx(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_endRx, m_rxErrorCallback, m_rxErrorTrace, NotifyRxEndError(), ns3::Simulator::Now(), NS_ASSERT, and NS_LOG_FUNCTION.
SwitchFromRxEndOk()
void ns3::WifiPhyStateHelper::SwitchFromRxEndOk (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector, uint16_t staId, std::vector< bool > statusPerMpdu)
Switch from RX after the reception was successful.
Parameters
psdu the successfully received PSDU
snr the SNR of the received PSDU in linear scale
txVector TXVECTOR of the PSDU
staId the station ID of the PSDU (only used for MU)
statusPerMpdu reception status per MPDU
Definition at line 478 of file wifi-phy-state-helper.cc.
References DoSwitchFromRx(), ns3::WifiTxVector::GetMode(), ns3::WifiTxVector::GetPreambleType(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_endRx, m_rxOkCallback, m_rxOkTrace, NotifyRxEndOk(), ns3::Simulator::Now(), NS_ASSERT, and NS_LOG_FUNCTION.
SwitchFromSleep()
void ns3::WifiPhyStateHelper::SwitchFromSleep (Time duration)
Switch from sleep mode.
Parameters
duration the duration of CCA busy state
Definition at line 573 of file wifi-phy-state-helper.cc.
References IsStateSleep(), m_endCcaBusy, m_previousStateChangeTime, m_sleeping, m_startSleep, m_stateLogger, max, NotifyMaybeCcaBusyStart(), NotifyWakeup(), ns3::Simulator::Now(), NS_ASSERT, NS_LOG_FUNCTION, and SLEEP.
SwitchMaybeToCcaBusy()
void ns3::WifiPhyStateHelper::SwitchMaybeToCcaBusy (Time duration)
Switch to CCA busy.
Parameters
duration the duration of CCA busy state
Definition at line 519 of file wifi-phy-state-helper.cc.
References CCA_BUSY, GetState(), IDLE, LogPreviousIdleAndCcaBusyStates(), m_endCcaBusy, m_startCcaBusy, max, NotifyMaybeCcaBusyStart(), ns3::Simulator::Now(), NS_LOG_FUNCTION, and RX.
SwitchToChannelSwitching()
void ns3::WifiPhyStateHelper::SwitchToChannelSwitching (Time switchingDuration)
Switch state to channel switching for the given duration.
Parameters
switchingDuration the duration of required to switch the channel
Definition at line 425 of file wifi-phy-state-helper.cc.
References CCA_BUSY, GetState(), IDLE, IsStateSwitching(), LogPreviousIdleAndCcaBusyStates(), m_endCcaBusy, m_endRx, m_endSwitching, m_endTx, m_previousStateChangeTime, m_startCcaBusy, m_startRx, m_startSwitching, m_stateLogger, ns3::Max(), NotifySwitchingStart(), ns3::Simulator::Now(), NS_ASSERT, NS_FATAL_ERROR, NS_LOG_FUNCTION, RX, and SWITCHING.
SwitchToOff()
void ns3::WifiPhyStateHelper::SwitchToOff (void)
Switch to off mode.
Definition at line 603 of file wifi-phy-state-helper.cc.
References CCA_BUSY, GetState(), IDLE, IsStateOff(), LogPreviousIdleAndCcaBusyStates(), m_endRx, m_endSwitching, m_endTx, m_isOff, m_previousStateChangeTime, m_startCcaBusy, m_startRx, m_startTx, m_stateLogger, ns3::Max(), NotifyOff(), ns3::Simulator::Now(), NS_ASSERT, NS_FATAL_ERROR, NS_LOG_FUNCTION, RX, and TX.
SwitchToRx()
void ns3::WifiPhyStateHelper::SwitchToRx (Time rxDuration)
Switch state to RX for the given duration.
Parameters
rxDuration the duration of the RX
Definition at line 396 of file wifi-phy-state-helper.cc.
References CCA_BUSY, GetState(), IDLE, IsStateCcaBusy(), IsStateIdle(), IsStateRx(), LogPreviousIdleAndCcaBusyStates(), m_endRx, m_endSwitching, m_endTx, m_previousStateChangeTime, m_startCcaBusy, m_startRx, m_stateLogger, ns3::Max(), NotifyRxStart(), ns3::Simulator::Now(), NS_ASSERT, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
SwitchToSleep()
void ns3::WifiPhyStateHelper::SwitchToSleep (void)
Switch to sleep mode.
Definition at line 545 of file wifi-phy-state-helper.cc.
References CCA_BUSY, GetState(), IDLE, IsStateSleep(), LogPreviousIdleAndCcaBusyStates(), m_endRx, m_endSwitching, m_endTx, m_previousStateChangeTime, m_sleeping, m_startCcaBusy, m_startSleep, m_stateLogger, ns3::Max(), NotifySleep(), ns3::Simulator::Now(), NS_ASSERT, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
SwitchToTx()
void ns3::WifiPhyStateHelper::SwitchToTx (Time txDuration, WifiConstPsduMap psdus, double txPowerDbm, WifiTxVector txVector)
Switch state to TX for the given duration.
Parameters
txDuration the duration of the PPDU to transmit
psdus the PSDUs in the transmitted PPDU (only one unless it is a MU PPDU)
txPowerDbm the nominal TX power in dBm
txVector the TX vector for the transmission
Definition at line 357 of file wifi-phy-state-helper.cc.
References CCA_BUSY, ns3::WifiTxVector::GetMode(), ns3::WifiTxVector::GetPreambleType(), GetState(), ns3::WifiTxVector::GetTxPowerLevel(), IDLE, LogPreviousIdleAndCcaBusyStates(), m_endRx, m_endSwitching, m_endTx, m_previousStateChangeTime, m_startCcaBusy, m_startRx, m_startTx, m_stateLogger, m_txTrace, ns3::Max(), NotifyTxStart(), ns3::Simulator::Now(), NS_FATAL_ERROR, NS_LOG_FUNCTION, RX, and TX.
UnregisterListener()
void ns3::WifiPhyStateHelper::UnregisterListener (WifiPhyListener * listener)
Remove WifiPhyListener from this WifiPhyStateHelper.
Parameters
listener the WifiPhyListener to unregister
Definition at line 98 of file wifi-phy-state-helper.cc.
References m_listeners.
Member Data Documentation
m_endCcaBusy
Time ns3::WifiPhyStateHelper::m_endCcaBusy private
end CCA busy
Definition at line 361 of file wifi-phy-state-helper.h.
Referenced by GetDelayUntilIdle(), GetState(), LogPreviousIdleAndCcaBusyStates(), SwitchFromOff(), SwitchFromRxAbort(), SwitchFromSleep(), SwitchMaybeToCcaBusy(), and SwitchToChannelSwitching().
m_endRx
Time ns3::WifiPhyStateHelper::m_endRx private
end receive
Definition at line 360 of file wifi-phy-state-helper.h.
Referenced by DoSwitchFromRx(), GetDelayUntilIdle(), GetLastRxEndTime(), GetState(), LogPreviousIdleAndCcaBusyStates(), SwitchFromRxEndError(), SwitchFromRxEndOk(), SwitchToChannelSwitching(), SwitchToOff(), SwitchToRx(), SwitchToSleep(), and SwitchToTx().
m_endSwitching
Time ns3::WifiPhyStateHelper::m_endSwitching private
end switching
Definition at line 362 of file wifi-phy-state-helper.h.
Referenced by GetDelayUntilIdle(), GetState(), LogPreviousIdleAndCcaBusyStates(), SwitchToChannelSwitching(), SwitchToOff(), SwitchToRx(), SwitchToSleep(), and SwitchToTx().
m_endTx
Time ns3::WifiPhyStateHelper::m_endTx private
end transmit
Definition at line 359 of file wifi-phy-state-helper.h.
Referenced by GetDelayUntilIdle(), GetState(), LogPreviousIdleAndCcaBusyStates(), SwitchToChannelSwitching(), SwitchToOff(), SwitchToRx(), SwitchToSleep(), and SwitchToTx().
m_isOff
bool ns3::WifiPhyStateHelper::m_isOff private
switched off
Definition at line 358 of file wifi-phy-state-helper.h.
Referenced by GetState(), SwitchFromOff(), and SwitchToOff().
m_listeners
Listeners ns3::WifiPhyStateHelper::m_listeners private
listeners
Definition at line 370 of file wifi-phy-state-helper.h.
Referenced by NotifyMaybeCcaBusyStart(), NotifyOff(), NotifyOn(), NotifyRxEndError(), NotifyRxEndOk(), NotifyRxStart(), NotifySleep(), NotifySwitchingStart(), NotifyTxStart(), NotifyWakeup(), RegisterListener(), and UnregisterListener().
m_previousStateChangeTime
Time ns3::WifiPhyStateHelper::m_previousStateChangeTime private
previous state change time
Definition at line 368 of file wifi-phy-state-helper.h.
Referenced by DoSwitchFromRx(), SwitchFromOff(), SwitchFromSleep(), SwitchToChannelSwitching(), SwitchToOff(), SwitchToRx(), SwitchToSleep(), and SwitchToTx().
m_rxErrorCallback
RxErrorCallback ns3::WifiPhyStateHelper::m_rxErrorCallback private
receive error callback
Definition at line 375 of file wifi-phy-state-helper.h.
Referenced by SetReceiveErrorCallback(), and SwitchFromRxEndError().
m_rxErrorTrace
TracedCallback<Ptr<const Packet>, double> ns3::WifiPhyStateHelper::m_rxErrorTrace private
receive error trace callback
Definition at line 372 of file wifi-phy-state-helper.h.
Referenced by GetTypeId(), and SwitchFromRxEndError().
m_rxOkCallback
RxOkCallback ns3::WifiPhyStateHelper::m_rxOkCallback private
receive OK callback
Definition at line 374 of file wifi-phy-state-helper.h.
Referenced by ContinueRxNextMpdu(), SetReceiveOkCallback(), and SwitchFromRxEndOk().
m_rxOkTrace
TracedCallback<Ptr<const Packet>, double, WifiMode, WifiPreamble> ns3::WifiPhyStateHelper::m_rxOkTrace private
receive OK trace callback
Definition at line 371 of file wifi-phy-state-helper.h.
Referenced by GetTypeId(), and SwitchFromRxEndOk().
m_sleeping
bool ns3::WifiPhyStateHelper::m_sleeping private
sleeping
Definition at line 357 of file wifi-phy-state-helper.h.
Referenced by GetState(), SwitchFromSleep(), and SwitchToSleep().
m_startCcaBusy
Time ns3::WifiPhyStateHelper::m_startCcaBusy private
start CCA busy
Definition at line 365 of file wifi-phy-state-helper.h.
Referenced by LogPreviousIdleAndCcaBusyStates(), SwitchMaybeToCcaBusy(), SwitchToChannelSwitching(), SwitchToOff(), SwitchToRx(), SwitchToSleep(), and SwitchToTx().
m_startRx
Time ns3::WifiPhyStateHelper::m_startRx private
start receive
Definition at line 364 of file wifi-phy-state-helper.h.
Referenced by DoSwitchFromRx(), GetLastRxStartTime(), SwitchToChannelSwitching(), SwitchToOff(), SwitchToRx(), and SwitchToTx().
m_startSleep
Time ns3::WifiPhyStateHelper::m_startSleep private
start sleep
Definition at line 367 of file wifi-phy-state-helper.h.
Referenced by SwitchFromSleep(), and SwitchToSleep().
m_startSwitching
Time ns3::WifiPhyStateHelper::m_startSwitching private
start switching
Definition at line 366 of file wifi-phy-state-helper.h.
Referenced by SwitchToChannelSwitching().
m_startTx
Time ns3::WifiPhyStateHelper::m_startTx private
start transmit
Definition at line 363 of file wifi-phy-state-helper.h.
Referenced by SwitchToOff(), and SwitchToTx().
m_stateLogger
TracedCallback<Time, Time, WifiPhyState> ns3::WifiPhyStateHelper::m_stateLogger private
The trace source fired when state is changed.
Definition at line 355 of file wifi-phy-state-helper.h.
Referenced by DoSwitchFromRx(), GetTypeId(), LogPreviousIdleAndCcaBusyStates(), SwitchFromSleep(), SwitchToChannelSwitching(), SwitchToOff(), SwitchToRx(), SwitchToSleep(), and SwitchToTx().
m_txTrace
TracedCallback<Ptr<const Packet>, WifiMode, WifiPreamble, uint8_t> ns3::WifiPhyStateHelper::m_txTrace private
transmit trace callback
Definition at line 373 of file wifi-phy-state-helper.h.
Referenced by GetTypeId(), and SwitchToTx().
The documentation for this class was generated from the following files:
src/wifi/model/wifi-phy-state-helper.h
src/wifi/model/wifi-phy-state-helper.cc