ns-3: LengthTestCase Class Reference
LengthTestCase Class Reference
Implements tests for the Length class.
Public Member Functions
LengthTestCase ()
Constructor.
virtual ~LengthTestCase ()=default
Destructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Member Functions
void AssertFalse (bool condition, std::string msg)
Helper function to compare results with false.
void AssertTrue (bool condition, std::string msg)
Helper function to compare results with true.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Private Member Functions
virtual void DoRun ()
Implementation to actually run this TestCase.
void TestConstructLengthFromQuantity ()
Test that a Length object can be constructed from a Quantity object.
void TestConstructLengthFromSIUnits ()
Test that a Length object constructed from various SI units has the correct value in meters.
void TestConstructLengthFromUSUnits ()
Test that a Length object constructed from various US units has the correct value in meters.
void TestCopyAssignment ()
Test that a length object can be updated by assignment from another length object.
void TestDefaultLengthIsZero ()
Test that a default constructed Length object has a value of 0.
void TestInputStreamOperator ()
Test reading length object from a stream produces the expected length value.
void TestLengthCopyConstructor ()
Test that the value from one length is copied to another using the copy constructor.
void TestLengthMoveConstructor ()
Test that the value from one length is copied to another using the move constructor.
template<class T >
void TestLengthSerialization (const Length &l, const T &unit, const std::string &expectedOutput, const std::string &context)
Generic function for testing serialization of a Length object in various units.
void TestMoveAssignment ()
Test that a length object can be updated by assignment from a moved length object.
void TestOutputStreamOperator ()
Test writing length object to a stream produces the expected output.
void TestQuantityAssignment ()
Test that a length object can be updated by assignment from a quantity.
void TestSerializeLengthWithUnit ()
Test serializing a length object to all of the supported unit types.
void TestTryParseReturnsFalse ()
Test the TryParse function returns false on bad input.
void TestTryParseReturnsTrue ()
Test the TryParse function returns true on success.
void TestConstructLengthFromString (double unitValue, double meterValue, double tolerance, const std::initializer_list< std::string > &symbols)
Test that a length object can be constructed from a string.
void TestConstructLengthFromMeterString ()
Test that a length object can be constructed from a string.
void TestConstructLengthFromNanoMeterString ()
Test that a length object can be constructed from a string.
void TestConstructLengthFromMicroMeterString ()
Test that a length object can be constructed from a string.
void TestConstructLengthFromMilliMeterString ()
Test that a length object can be constructed from a string.
void TestConstructLengthFromCentiMeterString ()
Test that a length object can be constructed from a string.
void TestConstructLengthFromKiloMeterString ()
Test that a length object can be constructed from a string.
void TestConstructLengthFromNauticalMileString ()
Test that a length object can be constructed from a string.
void TestConstructLengthFromInchString ()
Test that a length object can be constructed from a string.
void TestConstructLengthFromFootString ()
Test that a length object can be constructed from a string.
void TestConstructLengthFromYardString ()
Test that a length object can be constructed from a string.
void TestConstructLengthFromMileString ()
Test that a length object can be constructed from a string.
void TestBuilderFreeFunctions ()
Test constructing length objects using the builder free functions.
void TestIsEqualReturnsTrue ()
Test member comparison operators.
void TestIsEqualReturnsFalse ()
Test member comparison operators.
void TestIsEqualWithToleranceReturnsTrue ()
Test member comparison operators.
void TestIsEqualWithToleranceReturnsFalse ()
Test member comparison operators.
void TestIsNotEqualReturnsTrue ()
Test member comparison operators.
void TestIsNotEqualReturnsFalse ()
Test member comparison operators.
void TestIsNotEqualWithToleranceReturnsTrue ()
Test member comparison operators.
void TestIsNotEqualWithToleranceReturnsFalse ()
Test member comparison operators.
void TestIsLessReturnsTrue ()
Test member comparison operators.
void TestIsLessReturnsFalse ()
Test member comparison operators.
void TestIsLessWithToleranceReturnsFalse ()
Test member comparison operators.
void TestIsGreaterReturnsTrue ()
Test member comparison operators.
void TestIsGreaterReturnsFalse ()
Test member comparison operators.
void TestIsGreaterWithToleranceReturnsFalse ()
Test member comparison operators.
void TestOperatorEqualsReturnsTrue ()
Test free function comparison operators.
void TestOperatorEqualsReturnsFalse ()
Test free function comparison operators.
void TestOperatorNotEqualsReturnsTrue ()
Test free function comparison operators.
void TestOperatorNotEqualsReturnsFalse ()
Test free function comparison operators.
void TestOperatorLessThanReturnsTrue ()
Test free function comparison operators.
void TestOperatorLessThanReturnsFalse ()
Test free function comparison operators.
void TestOperatorLessOrEqualReturnsTrue ()
Test free function comparison operators.
void TestOperatorLessOrEqualReturnsFalse ()
Test free function comparison operators.
void TestOperatorGreaterThanReturnsTrue ()
Test free function comparison operators.
void TestOperatorGreaterThanReturnsFalse ()
Test free function comparison operators.
void TestOperatorGreaterOrEqualReturnsTrue ()
Test free function comparison operators.
void TestOperatorGreaterOrEqualReturnsFalse ()
Test free function comparison operators.
void TestAddingTwoLengths ()
Test arithmetic operations.
void TestAddingLengthAndQuantity ()
Test arithmetic operations.
void TestAddingQuantityAndLength ()
Test arithmetic operations.
void TestSubtractingTwoLengths ()
Test arithmetic operations.
void TestSubtractingLengthAndQuantity ()
Test arithmetic operations.
void TestSubtractingQuantityAndLength ()
Test arithmetic operations.
void TestMultiplyLengthByScalar ()
Test arithmetic operations.
void TestMultiplyScalarByLength ()
Test arithmetic operations.
void TestDivideLengthByScalar ()
Test arithmetic operations.
void TestDivideLengthByLength ()
Test arithmetic operations.
void TestDivideLengthByLengthReturnsNaN ()
Test arithmetic operations.
void TestDivReturnsCorrectResult ()
Test Div function.
void TestDivReturnsZeroRemainder ()
Test Div function.
void TestDivReturnsCorrectRemainder ()
Test Div function.
void TestModReturnsZero ()
Test Mod function.
void TestModReturnsNonZero ()
Test Mod function.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Detailed Description
Implements tests for the Length class.
Definition at line 67 of file length-test-suite.cc.
Constructor & Destructor Documentation
LengthTestCase()
LengthTestCase::LengthTestCase () inline
Constructor.
Definition at line 73 of file length-test-suite.cc.
~LengthTestCase()
virtual LengthTestCase::~LengthTestCase () virtual default
Destructor.
Member Function Documentation
AssertFalse()
void LengthTestCase::AssertFalse (bool condition, std::string msg) inline protected
Helper function to compare results with false.
Parameters
condition The boolean condition to test
msg The message to print if the test fails
Definition at line 89 of file length-test-suite.cc.
References NS_TEST_ASSERT_MSG_EQ.
AssertTrue()
void LengthTestCase::AssertTrue (bool condition, std::string msg) inline protected
Helper function to compare results with true.
Parameters
condition The boolean condition to test
msg The message to print if the test fails
Definition at line 100 of file length-test-suite.cc.
References NS_TEST_ASSERT_MSG_EQ.
DoRun()
void LengthTestCase::DoRun () private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 1381 of file length-test-suite.cc.
TestAddingLengthAndQuantity()
void LengthTestCase::TestAddingLengthAndQuantity () private
Test arithmetic operations.
Definition at line 1134 of file length-test-suite.cc.
References ns3::Length::GetDouble(), and NS_TEST_ASSERT_MSG_EQ.
TestAddingQuantityAndLength()
void LengthTestCase::TestAddingQuantityAndLength () private
Test arithmetic operations.
Definition at line 1150 of file length-test-suite.cc.
References ns3::Length::GetDouble(), and NS_TEST_ASSERT_MSG_EQ.
TestAddingTwoLengths()
void LengthTestCase::TestAddingTwoLengths () private
Test arithmetic operations.
Definition at line 1115 of file length-test-suite.cc.
References ns3::Length::GetDouble(), and NS_TEST_ASSERT_MSG_EQ.
TestBuilderFreeFunctions()
void LengthTestCase::TestBuilderFreeFunctions () private
Test constructing length objects using the builder free functions.
Definition at line 614 of file length-test-suite.cc.
References ns3::CentiMeters(), ns3::Feet(), ns3::Inches(), ns3::KiloMeters(), ns3::Meters(), ns3::MicroMeters(), ns3::Miles(), ns3::MilliMeters(), ns3::NanoMeters(), ns3::NauticalMiles(), NS_TEST_ASSERT_MSG_EQ, and ns3::Yards().
TestConstructLengthFromCentiMeterString()
void LengthTestCase::TestConstructLengthFromCentiMeterString () private
Test that a length object can be constructed from a string.
Definition at line 481 of file length-test-suite.cc.
TestConstructLengthFromFootString()
void LengthTestCase::TestConstructLengthFromFootString () private
Test that a length object can be constructed from a string.
Definition at line 524 of file length-test-suite.cc.
TestConstructLengthFromInchString()
void LengthTestCase::TestConstructLengthFromInchString () private
Test that a length object can be constructed from a string.
Definition at line 513 of file length-test-suite.cc.
TestConstructLengthFromKiloMeterString()
void LengthTestCase::TestConstructLengthFromKiloMeterString () private
Test that a length object can be constructed from a string.
Definition at line 493 of file length-test-suite.cc.
TestConstructLengthFromMeterString()
void LengthTestCase::TestConstructLengthFromMeterString () private
Test that a length object can be constructed from a string.
Definition at line 437 of file length-test-suite.cc.
TestConstructLengthFromMicroMeterString()
void LengthTestCase::TestConstructLengthFromMicroMeterString () private
Test that a length object can be constructed from a string.
Definition at line 457 of file length-test-suite.cc.
TestConstructLengthFromMileString()
void LengthTestCase::TestConstructLengthFromMileString () private
Test that a length object can be constructed from a string.
Definition at line 546 of file length-test-suite.cc.
TestConstructLengthFromMilliMeterString()
void LengthTestCase::TestConstructLengthFromMilliMeterString () private
Test that a length object can be constructed from a string.
Definition at line 469 of file length-test-suite.cc.
TestConstructLengthFromNanoMeterString()
void LengthTestCase::TestConstructLengthFromNanoMeterString () private
Test that a length object can be constructed from a string.
Definition at line 446 of file length-test-suite.cc.
TestConstructLengthFromNauticalMileString()
void LengthTestCase::TestConstructLengthFromNauticalMileString () private
Test that a length object can be constructed from a string.
Definition at line 504 of file length-test-suite.cc.
TestConstructLengthFromQuantity()
void LengthTestCase::TestConstructLengthFromQuantity () private
Test that a Length object can be constructed from a Quantity object.
Definition at line 326 of file length-test-suite.cc.
References ns3::Length::GetDouble(), NS_TEST_ASSERT_MSG_EQ, and ns3::Length::Quantity::Value().
TestConstructLengthFromSIUnits()
void LengthTestCase::TestConstructLengthFromSIUnits () private
Test that a Length object constructed from various SI units has the correct value in meters.
Definition at line 337 of file length-test-suite.cc.
References ns3::Length::GetDouble(), and NS_TEST_ASSERT_MSG_EQ.
TestConstructLengthFromString()
void LengthTestCase::TestConstructLengthFromString (double unitValue, double meterValue, double tolerance, const std::initializer_list< std::string > & symbols) private
Test that a length object can be constructed from a string.
Definition at line 411 of file length-test-suite.cc.
References ns3::Length::GetDouble(), and NS_TEST_ASSERT_MSG_EQ_TOL.
TestConstructLengthFromUSUnits()
void LengthTestCase::TestConstructLengthFromUSUnits () private
Test that a Length object constructed from various US units has the correct value in meters.
Definition at line 362 of file length-test-suite.cc.
References ns3::Length::GetDouble(), and NS_TEST_ASSERT_MSG_EQ_TOL.
TestConstructLengthFromYardString()
void LengthTestCase::TestConstructLengthFromYardString () private
Test that a length object can be constructed from a string.
Definition at line 535 of file length-test-suite.cc.
TestCopyAssignment()
void LengthTestCase::TestCopyAssignment () private
Test that a length object can be updated by assignment from another length object.
Definition at line 691 of file length-test-suite.cc.
References ns3::Length::GetDouble(), and NS_TEST_ASSERT_MSG_EQ.
TestDefaultLengthIsZero()
void LengthTestCase::TestDefaultLengthIsZero () private
Test that a default constructed Length object has a value of 0.
Definition at line 318 of file length-test-suite.cc.
References ns3::Length::GetDouble(), and NS_TEST_ASSERT_MSG_EQ.
TestDivideLengthByLength()
void LengthTestCase::TestDivideLengthByLength () private
Test arithmetic operations.
Definition at line 1265 of file length-test-suite.cc.
References ns3::Length::GetDouble(), and NS_TEST_ASSERT_MSG_EQ.
TestDivideLengthByLengthReturnsNaN()
void LengthTestCase::TestDivideLengthByLengthReturnsNaN () private
Test arithmetic operations.
Definition at line 1286 of file length-test-suite.cc.
TestDivideLengthByScalar()
void LengthTestCase::TestDivideLengthByScalar () private
Test arithmetic operations.
Definition at line 1249 of file length-test-suite.cc.
References ns3::Length::GetDouble(), and NS_TEST_ASSERT_MSG_EQ.
TestDivReturnsCorrectRemainder()
void LengthTestCase::TestDivReturnsCorrectRemainder () private
Test Div function.
Definition at line 1336 of file length-test-suite.cc.
References ns3::Div(), ns3::Length::GetDouble(), and NS_TEST_ASSERT_MSG_EQ.
TestDivReturnsCorrectResult()
void LengthTestCase::TestDivReturnsCorrectResult () private
Test Div function.
Definition at line 1300 of file length-test-suite.cc.
References ns3::Div(), and NS_TEST_ASSERT_MSG_EQ.
TestDivReturnsZeroRemainder()
void LengthTestCase::TestDivReturnsZeroRemainder () private
Test Div function.
Definition at line 1316 of file length-test-suite.cc.
References ns3::Div(), ns3::Length::GetDouble(), and NS_TEST_ASSERT_MSG_EQ.
TestInputStreamOperator()
void LengthTestCase::TestInputStreamOperator () private
Test reading length object from a stream produces the expected length value.
Definition at line 908 of file length-test-suite.cc.
References ns3::Length::GetDouble(), and NS_TEST_ASSERT_MSG_EQ.
TestIsEqualReturnsFalse()
void LengthTestCase::TestIsEqualReturnsFalse () private
Test member comparison operators.
Definition at line 743 of file length-test-suite.cc.
References ns3::Length::IsEqual().
TestIsEqualReturnsTrue()
void LengthTestCase::TestIsEqualReturnsTrue () private
Test member comparison operators.
Definition at line 733 of file length-test-suite.cc.
References ns3::Length::IsEqual().
TestIsEqualWithToleranceReturnsFalse()
void LengthTestCase::TestIsEqualWithToleranceReturnsFalse () private
Test member comparison operators.
Definition at line 766 of file length-test-suite.cc.
References ns3::Length::IsEqual().
TestIsEqualWithToleranceReturnsTrue()
void LengthTestCase::TestIsEqualWithToleranceReturnsTrue () private
Test member comparison operators.
Definition at line 753 of file length-test-suite.cc.
References ns3::Length::IsEqual().
TestIsGreaterReturnsFalse()
void LengthTestCase::TestIsGreaterReturnsFalse () private
Test member comparison operators.
Definition at line 873 of file length-test-suite.cc.
References ns3::Length::IsGreater().
TestIsGreaterReturnsTrue()
void LengthTestCase::TestIsGreaterReturnsTrue () private
Test member comparison operators.
Definition at line 863 of file length-test-suite.cc.
References ns3::Length::IsGreater().
TestIsGreaterWithToleranceReturnsFalse()
void LengthTestCase::TestIsGreaterWithToleranceReturnsFalse () private
Test member comparison operators.
Definition at line 883 of file length-test-suite.cc.
References ns3::Length::IsGreater().
TestIsLessReturnsFalse()
void LengthTestCase::TestIsLessReturnsFalse () private
Test member comparison operators.
Definition at line 839 of file length-test-suite.cc.
References ns3::Length::IsLess().
TestIsLessReturnsTrue()
void LengthTestCase::TestIsLessReturnsTrue () private
Test member comparison operators.
Definition at line 827 of file length-test-suite.cc.
References ns3::Length::IsLess().
TestIsLessWithToleranceReturnsFalse()
void LengthTestCase::TestIsLessWithToleranceReturnsFalse () private
Test member comparison operators.
Definition at line 851 of file length-test-suite.cc.
References ns3::Length::IsLess().
TestIsNotEqualReturnsFalse()
void LengthTestCase::TestIsNotEqualReturnsFalse () private
Test member comparison operators.
Definition at line 791 of file length-test-suite.cc.
References ns3::Length::IsNotEqual().
TestIsNotEqualReturnsTrue()
void LengthTestCase::TestIsNotEqualReturnsTrue () private
Test member comparison operators.
Definition at line 779 of file length-test-suite.cc.
References ns3::Length::IsNotEqual().
TestIsNotEqualWithToleranceReturnsFalse()
void LengthTestCase::TestIsNotEqualWithToleranceReturnsFalse () private
Test member comparison operators.
Definition at line 815 of file length-test-suite.cc.
References ns3::Length::IsNotEqual().
TestIsNotEqualWithToleranceReturnsTrue()
void LengthTestCase::TestIsNotEqualWithToleranceReturnsTrue () private
Test member comparison operators.
Definition at line 803 of file length-test-suite.cc.
References ns3::Length::IsNotEqual().
TestLengthCopyConstructor()
void LengthTestCase::TestLengthCopyConstructor () private
Test that the value from one length is copied to another using the copy constructor.
Definition at line 387 of file length-test-suite.cc.
References ns3::Length::GetDouble(), and NS_TEST_ASSERT_MSG_EQ.
TestLengthMoveConstructor()
void LengthTestCase::TestLengthMoveConstructor () private
Test that the value from one length is copied to another using the move constructor.
Definition at line 399 of file length-test-suite.cc.
References ns3::Length::GetDouble(), and NS_TEST_ASSERT_MSG_EQ.
TestLengthSerialization()
template<class T > void LengthTestCase::TestLengthSerialization (const Length & l, const T & unit, const std::string & expectedOutput, const std::string & context) private
Generic function for testing serialization of a Length object in various units.
Template Parameters
T Type of the length unit that should be output during serialization
Parameters
l Length object to serialize
unit Unit that the length value will be converted to before serialization
expectedOutput Expected result of the serialization
context Included in the error message if the test fails
Definition at line 926 of file length-test-suite.cc.
References ns3::Length::As(), and NS_TEST_ASSERT_MSG_EQ.
TestModReturnsNonZero()
void LengthTestCase::TestModReturnsNonZero () private
Test Mod function.
Definition at line 1368 of file length-test-suite.cc.
References ns3::Mod(), and NS_TEST_ASSERT_MSG_EQ.
TestModReturnsZero()
void LengthTestCase::TestModReturnsZero () private
Test Mod function.
Definition at line 1356 of file length-test-suite.cc.
References ns3::Mod(), and NS_TEST_ASSERT_MSG_EQ.
TestMoveAssignment()
void LengthTestCase::TestMoveAssignment () private
Test that a length object can be updated by assignment from a moved length object.
Definition at line 705 of file length-test-suite.cc.
References ns3::Length::GetDouble(), and NS_TEST_ASSERT_MSG_EQ.
TestMultiplyLengthByScalar()
void LengthTestCase::TestMultiplyLengthByScalar () private
Test arithmetic operations.
Definition at line 1217 of file length-test-suite.cc.
References ns3::Length::GetDouble(), and NS_TEST_ASSERT_MSG_EQ.
TestMultiplyScalarByLength()
void LengthTestCase::TestMultiplyScalarByLength () private
Test arithmetic operations.
Definition at line 1233 of file length-test-suite.cc.
References ns3::Length::GetDouble(), and NS_TEST_ASSERT_MSG_EQ.
TestOperatorEqualsReturnsFalse()
void LengthTestCase::TestOperatorEqualsReturnsFalse () private
Test free function comparison operators.
Definition at line 973 of file length-test-suite.cc.
TestOperatorEqualsReturnsTrue()
void LengthTestCase::TestOperatorEqualsReturnsTrue () private
Test free function comparison operators.
Definition at line 961 of file length-test-suite.cc.
TestOperatorGreaterOrEqualReturnsFalse()
void LengthTestCase::TestOperatorGreaterOrEqualReturnsFalse () private
Test free function comparison operators.
Definition at line 1103 of file length-test-suite.cc.
TestOperatorGreaterOrEqualReturnsTrue()
void LengthTestCase::TestOperatorGreaterOrEqualReturnsTrue () private
Test free function comparison operators.
Definition at line 1087 of file length-test-suite.cc.
TestOperatorGreaterThanReturnsFalse()
void LengthTestCase::TestOperatorGreaterThanReturnsFalse () private
Test free function comparison operators.
Definition at line 1075 of file length-test-suite.cc.
TestOperatorGreaterThanReturnsTrue()
void LengthTestCase::TestOperatorGreaterThanReturnsTrue () private
Test free function comparison operators.
Definition at line 1063 of file length-test-suite.cc.
TestOperatorLessOrEqualReturnsFalse()
void LengthTestCase::TestOperatorLessOrEqualReturnsFalse () private
Test free function comparison operators.
Definition at line 1051 of file length-test-suite.cc.
TestOperatorLessOrEqualReturnsTrue()
void LengthTestCase::TestOperatorLessOrEqualReturnsTrue () private
Test free function comparison operators.
Definition at line 1035 of file length-test-suite.cc.
TestOperatorLessThanReturnsFalse()
void LengthTestCase::TestOperatorLessThanReturnsFalse () private
Test free function comparison operators.
Definition at line 1023 of file length-test-suite.cc.
TestOperatorLessThanReturnsTrue()
void LengthTestCase::TestOperatorLessThanReturnsTrue () private
Test free function comparison operators.
Definition at line 1011 of file length-test-suite.cc.
TestOperatorNotEqualsReturnsFalse()
void LengthTestCase::TestOperatorNotEqualsReturnsFalse () private
Test free function comparison operators.
Definition at line 998 of file length-test-suite.cc.
TestOperatorNotEqualsReturnsTrue()
void LengthTestCase::TestOperatorNotEqualsReturnsTrue () private
Test free function comparison operators.
Definition at line 985 of file length-test-suite.cc.
TestOutputStreamOperator()
void LengthTestCase::TestOutputStreamOperator () private
Test writing length object to a stream produces the expected output.
Definition at line 895 of file length-test-suite.cc.
References NS_TEST_ASSERT_MSG_EQ.
TestQuantityAssignment()
void LengthTestCase::TestQuantityAssignment () private
Test that a length object can be updated by assignment from a quantity.
Definition at line 719 of file length-test-suite.cc.
References NS_TEST_ASSERT_MSG_EQ.
TestSerializeLengthWithUnit()
void LengthTestCase::TestSerializeLengthWithUnit () private
Test serializing a length object to all of the supported unit types.
Definition at line 943 of file length-test-suite.cc.
TestSubtractingLengthAndQuantity()
void LengthTestCase::TestSubtractingLengthAndQuantity () private
Test arithmetic operations.
Definition at line 1185 of file length-test-suite.cc.
References ns3::Length::GetDouble(), and NS_TEST_ASSERT_MSG_EQ.
TestSubtractingQuantityAndLength()
void LengthTestCase::TestSubtractingQuantityAndLength () private
Test arithmetic operations.
Definition at line 1201 of file length-test-suite.cc.
References ns3::Length::GetDouble(), and NS_TEST_ASSERT_MSG_EQ.
TestSubtractingTwoLengths()
void LengthTestCase::TestSubtractingTwoLengths () private
Test arithmetic operations.
Definition at line 1166 of file length-test-suite.cc.
References ns3::Length::GetDouble(), and NS_TEST_ASSERT_MSG_EQ.
TestTryParseReturnsFalse()
void LengthTestCase::TestTryParseReturnsFalse () private
Test the TryParse function returns false on bad input.
Definition at line 647 of file length-test-suite.cc.
References ns3::Length::TryParse().
TestTryParseReturnsTrue()
void LengthTestCase::TestTryParseReturnsTrue () private
Test the TryParse function returns true on success.
Definition at line 658 of file length-test-suite.cc.
References ns3::Length::GetDouble(), NS_TEST_ASSERT_MSG_EQ_TOL, and ns3::Length::TryParse().
The documentation for this class was generated from the following file:
src/core/test/length-test-suite.cc