ns-3: ns3::Dcd Class Reference
ns3::Dcd Class Reference
This class implements Downlink channel descriptor as described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems" 6.3.2.3.1 Downlink Channel Descriptor (DCD) message, page 45.
#include "dl-mac-messages.h"
Public Member Functions
Dcd (void)
virtual ~Dcd (void)
void AddDlBurstProfile (OfdmDlBurstProfile dlBurstProfile)
Add DL burst profile field.
uint32_t Deserialize (Buffer::Iterator start)
OfdmDcdChannelEncodings GetChannelEncodings (void) const
Get channel encodings field.
uint8_t GetConfigurationChangeCount (void) const
Get configuration change count field.
std::vector< OfdmDlBurstProfile > GetDlBurstProfiles (void) const
Get DL burst profile field.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
std::string GetName (void) const
Get name field.
uint8_t GetNrDlBurstProfiles (void) const
Get number DL burst profiles field.
uint32_t GetSerializedSize (void) const
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetChannelEncodings (OfdmDcdChannelEncodings channelEncodings)
Set channel encodings field.
void SetConfigurationChangeCount (uint8_t configurationChangeCount)
Set configuration change count field.
void SetNrDlBurstProfiles (uint8_t nrDlBurstProfiles)
Set number DL burst profile field.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
OfdmDcdChannelEncodings m_channelEncodings
TLV Encoded information for the overall channel.
uint8_t m_configurationChangeCount
configuration change count
std::vector< OfdmDlBurstProfile > m_dlBurstProfiles
vector of download burst profiles
uint8_t m_nrDlBurstProfiles
number DL purst profiles
uint8_t m_reserved
changed as per the amendment 802.16e-2005
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class implements Downlink channel descriptor as described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems" 6.3.2.3.1 Downlink Channel Descriptor (DCD) message, page 45.
Introspection did not find any typical Config paths.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 80 bytes (on a 64-bit architecture).
Definition at line 355 of file dl-mac-messages.h.
Constructor & Destructor Documentation
Dcd()
ns3::Dcd::Dcd (void)
Definition at line 317 of file dl-mac-messages.cc.
~Dcd()
ns3::Dcd::~Dcd (void) virtual
Definition at line 324 of file dl-mac-messages.cc.
Member Function Documentation
AddDlBurstProfile()
void ns3::Dcd::AddDlBurstProfile (OfdmDlBurstProfile dlBurstProfile)
Add DL burst profile field.
Parameters
dlBurstProfile the DL burst profile
Definition at line 347 of file dl-mac-messages.cc.
References m_dlBurstProfiles.
Referenced by Deserialize(), and ns3::BaseStationNetDevice::SetDlBurstProfiles().
Deserialize()
uint32_t ns3::Dcd::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 439 of file dl-mac-messages.cc.
References AddDlBurstProfile(), ns3::Buffer::Iterator::GetDistanceFrom(), m_channelEncodings, m_configurationChangeCount, m_nrDlBurstProfiles, m_reserved, ns3::DcdChannelEncodings::Read(), ns3::OfdmDlBurstProfile::Read(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetChannelEncodings()
OfdmDcdChannelEncodings ns3::Dcd::GetChannelEncodings (void) const
Get channel encodings field.
Returns
the channel encodings
Definition at line 359 of file dl-mac-messages.cc.
References m_channelEncodings.
Referenced by ns3::SubscriberStationNetDevice::ProcessDcd().
GetConfigurationChangeCount()
uint8_t ns3::Dcd::GetConfigurationChangeCount (void) const
Get configuration change count field.
Returns
the configuration change count
Definition at line 353 of file dl-mac-messages.cc.
References m_configurationChangeCount.
Referenced by ns3::SubscriberStationNetDevice::ProcessDcd().
GetDlBurstProfiles()
std::vector< OfdmDlBurstProfile > ns3::Dcd::GetDlBurstProfiles (void) const
Get DL burst profile field.
Returns
the DL burst profiles
Definition at line 365 of file dl-mac-messages.cc.
References m_dlBurstProfiles.
Referenced by ns3::SubscriberStationNetDevice::ProcessDcd().
GetInstanceTypeId()
TypeId ns3::Dcd::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 394 of file dl-mac-messages.cc.
References GetTypeId().
GetName()
std::string ns3::Dcd::GetName (void) const
Get name field.
Returns
the name string
Definition at line 377 of file dl-mac-messages.cc.
GetNrDlBurstProfiles()
uint8_t ns3::Dcd::GetNrDlBurstProfiles (void) const
Get number DL burst profiles field.
Returns
the number of DL burst profiles
Definition at line 371 of file dl-mac-messages.cc.
References m_nrDlBurstProfiles.
GetSerializedSize()
uint32_t ns3::Dcd::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 408 of file dl-mac-messages.cc.
References ns3::OfdmDcdChannelEncodings::GetSize(), ns3::OfdmDlBurstProfile::GetSize(), m_channelEncodings, and m_dlBurstProfiles.
GetTypeId()
TypeId ns3::Dcd::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 383 of file dl-mac-messages.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::Dcd::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 400 of file dl-mac-messages.cc.
References m_configurationChangeCount, and m_dlBurstProfiles.
Serialize()
void ns3::Dcd::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 423 of file dl-mac-messages.cc.
References m_channelEncodings, m_configurationChangeCount, m_dlBurstProfiles, m_reserved, visualizer.core::start(), ns3::DcdChannelEncodings::Write(), ns3::OfdmDlBurstProfile::Write(), and ns3::Buffer::Iterator::WriteU8().
SetChannelEncodings()
void ns3::Dcd::SetChannelEncodings (OfdmDcdChannelEncodings channelEncodings)
Set channel encodings field.
Parameters
channelEncodings the channel encodings
Definition at line 335 of file dl-mac-messages.cc.
References m_channelEncodings.
Referenced by ns3::BaseStationNetDevice::CreateDcd().
SetConfigurationChangeCount()
void ns3::Dcd::SetConfigurationChangeCount (uint8_t configurationChangeCount)
Set configuration change count field.
Parameters
configurationChangeCount the configuration change count
Definition at line 329 of file dl-mac-messages.cc.
References m_configurationChangeCount.
Referenced by ns3::BaseStationNetDevice::CreateDcd().
SetNrDlBurstProfiles()
void ns3::Dcd::SetNrDlBurstProfiles (uint8_t nrDlBurstProfiles)
Set number DL burst profile field.
Parameters
nrDlBurstProfiles the number of DL burst profiles
Definition at line 341 of file dl-mac-messages.cc.
References m_nrDlBurstProfiles.
Referenced by ns3::SubscriberStationNetDevice::DoReceive().
Member Data Documentation
m_channelEncodings
OfdmDcdChannelEncodings ns3::Dcd::m_channelEncodings private
TLV Encoded information for the overall channel.
Definition at line 421 of file dl-mac-messages.h.
Referenced by Deserialize(), GetChannelEncodings(), GetSerializedSize(), Serialize(), and SetChannelEncodings().
m_configurationChangeCount
uint8_t ns3::Dcd::m_configurationChangeCount private
configuration change count
Definition at line 420 of file dl-mac-messages.h.
Referenced by Deserialize(), GetConfigurationChangeCount(), Print(), Serialize(), and SetConfigurationChangeCount().
m_dlBurstProfiles
std::vector<OfdmDlBurstProfile> ns3::Dcd::m_dlBurstProfiles private
vector of download burst profiles
Definition at line 422 of file dl-mac-messages.h.
Referenced by AddDlBurstProfile(), GetDlBurstProfiles(), GetSerializedSize(), Print(), and Serialize().
m_nrDlBurstProfiles
uint8_t ns3::Dcd::m_nrDlBurstProfiles private
number DL purst profiles
Definition at line 424 of file dl-mac-messages.h.
Referenced by Deserialize(), GetNrDlBurstProfiles(), and SetNrDlBurstProfiles().
m_reserved
uint8_t ns3::Dcd::m_reserved private
changed as per the amendment 802.16e-2005
Definition at line 419 of file dl-mac-messages.h.
Referenced by Deserialize(), and Serialize().
The documentation for this class was generated from the following files:
src/wimax/model/dl-mac-messages.h
src/wimax/model/dl-mac-messages.cc