ns-3: ns3::TimeValue Class Reference
ns3::TimeValue Class Reference
Time Attribute
AttributeValue implementation for Time.
#include "nstime.h"
Public Member Functions
TimeValue ()
TimeValue (const Time &value)
Copy constructor.
virtual Ptr< AttributeValue > Copy (void) const
virtual bool DeserializeFromString (std::string value, Ptr< const AttributeChecker > checker)
Time Get (void) const
template<typename T >
bool GetAccessor (T &value) const
Access the Time value as type T.
virtual std::string SerializeToString (Ptr< const AttributeChecker > checker) const
void Set (const Time &value)
Set the value.
Public Member Functions inherited from ns3::AttributeValue
AttributeValue ()
virtual ~AttributeValue ()
Public Member Functions inherited from ns3::SimpleRefCount< AttributeValue >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
Time m_value
The stored Time instance.
Detailed Description
AttributeValue implementation for Time.
See also
AttributeValue
Definition at line 1353 of file nstime.h.
Constructor & Destructor Documentation
TimeValue() [1/2]
ns3::TimeValue::TimeValue ()
Definition at line 530 of file time.cc.
TimeValue() [2/2]
Time ns3::TimeValue::TimeValue (const Time & value)
Copy constructor.
Parameters
[in] value The Time value to copy.
Definition at line 530 of file time.cc.
Member Function Documentation
Copy()
Ptr< AttributeValue > ns3::TimeValue::Copy (void) const virtual
Returns
a deep copy of this class, wrapped into an Attribute object.
Implements ns3::AttributeValue.
Definition at line 530 of file time.cc.
DeserializeFromString()
bool ns3::TimeValue::DeserializeFromString (std::string value, Ptr< const AttributeChecker > checker) virtual
Parameters
[in] value A string representation of the value
[in] checker A pointer to the checker associated to the attribute.
Returns
true if the input string was correctly-formatted and could be successfully deserialized, false otherwise.
Upon return of this function, this AttributeValue instance contains the deserialized value. In most cases, this method will not make any use of the checker argument. However, in a very limited set of cases, the checker argument is needed to perform proper serialization. A nice example of code which needs it is the EnumValue::SerializeToString code.
Implements ns3::AttributeValue.
Definition at line 530 of file time.cc.
Get()
Time ns3::TimeValue::Get (void) const
Returns
The Time value.
Definition at line 530 of file time.cc.
Referenced by ns3::DistributedSimulatorImpl::CalculateLookAhead(), ns3::NullMessageSimulatorImpl::CalculateLookAhead(), RttEstimatorTestCase::DoRun(), TcpHyblaIncrementTest::DoRun(), ns3::MakeTimeChecker(), and VanetRoutingExperiment::SetConfigFromGlobals().
GetAccessor()
template<typename T > bool ns3::TimeValue::GetAccessor (T & value) const inline
Access the Time value as type T.
Template Parameters
T [explicit] The type to cast to.
Parameters
[out] value The Time value, as type T.
Returns
true.
Definition at line 1353 of file nstime.h.
SerializeToString()
std::string ns3::TimeValue::SerializeToString (Ptr< const AttributeChecker > checker) const virtual
Parameters
[in] checker The checker associated to the attribute
Returns
A string representation of this value.
In most cases, this method will not make any use of the checker argument. However, in a very limited set of cases, the checker argument is needed to perform proper serialization. A nice example of code which needs it is the EnumValue::SerializeToString code.
Implements ns3::AttributeValue.
Definition at line 530 of file time.cc.
Set()
void ns3::TimeValue::Set (const Time & value)
Set the value.
Parameters
[in] value The value to adopt.
Definition at line 530 of file time.cc.
Member Data Documentation
m_value
Time ns3::TimeValue::m_value private
The stored Time instance.
Definition at line 1353 of file nstime.h.
The documentation for this class was generated from the following files:
src/core/model/nstime.h
src/core/model/time.cc
doc/introspected-doxygen.h