ns-3: ns3::PbbTlvBlock Class Reference
ns3::PbbTlvBlock Class Reference
A block of packet or message TLVs (PbbTlv).
#include "packetbb.h"
Public Types
typedef std::list< Ptr< PbbTlv > >::const_iterator ConstIterator
PbbTlv container const iterator.
typedef std::list< Ptr< PbbTlv > >::iterator Iterator
PbbTlv container iterator.
Public Member Functions
PbbTlvBlock (void)
~PbbTlvBlock (void)
Ptr< PbbTlv > Back (void) const
Iterator Begin (void)
ConstIterator Begin (void) const
void Clear (void)
Removes all TLVs from this block.
void Deserialize (Buffer::Iterator &start)
Deserializes a block from the specified buffer.
bool Empty (void) const
Iterator End (void)
ConstIterator End (void) const
Iterator Erase (Iterator first, Iterator last)
Removes all TLVs from [first, last) (includes first, not includes last).
Iterator Erase (Iterator position)
Removes the TLV at the specified position.
Ptr< PbbTlv > Front (void) const
uint32_t GetSerializedSize (void) const
Iterator Insert (Iterator position, const Ptr< PbbTlv > tlv)
Inserts a TLV at the specified position in this block.
bool operator!= (const PbbTlvBlock &other) const
Inequality operator for PbbTlvBlock.
bool operator== (const PbbTlvBlock &other) const
Equality operator for PbbTlvBlock.
void PopBack (void)
Removes a TLV from the back of this block.
void PopFront (void)
Removes a TLV from the front of this block.
void Print (std::ostream &os) const
Pretty-prints the contents of this block.
void Print (std::ostream &os, int level) const
Pretty-prints the contents of this block, with specified indentation.
void PushBack (Ptr< PbbTlv > tlv)
Appends a TLV to the back of this block.
void PushFront (Ptr< PbbTlv > tlv)
Prepends a TLV to the front of this block.
void Serialize (Buffer::Iterator &start) const
Serializes this block into the specified buffer.
int Size (void) const
Private Attributes
std::list< Ptr< PbbTlv > > m_tlvList
PbbTlv container.
Detailed Description
A block of packet or message TLVs (PbbTlv).
Acts similar to a C++ STL container. Should not be used for Address TLVs.
Definition at line 55 of file packetbb.h.
Member Typedef Documentation
ConstIterator
typedef std::list< Ptr<PbbTlv> >::const_iterator ns3::PbbTlvBlock::ConstIterator
PbbTlv container const iterator.
Definition at line 61 of file packetbb.h.
Iterator
typedef std::list< Ptr<PbbTlv> >::iterator ns3::PbbTlvBlock::Iterator
PbbTlv container iterator.
Definition at line 59 of file packetbb.h.
Constructor & Destructor Documentation
PbbTlvBlock()
ns3::PbbTlvBlock::PbbTlvBlock (void)
Definition at line 63 of file packetbb.cc.
References NS_LOG_FUNCTION.
~PbbTlvBlock()
ns3::PbbTlvBlock::~PbbTlvBlock (void)
Definition at line 69 of file packetbb.cc.
References Clear(), and NS_LOG_FUNCTION.
Member Function Documentation
Back()
Ptr< PbbTlv > ns3::PbbTlvBlock::Back (void) const
Returns
a smart pointer to the last TLV in this block.
Definition at line 125 of file packetbb.cc.
References m_tlvList, and NS_LOG_FUNCTION.
Referenced by ns3::PbbPacket::TlvBack(), and ns3::PbbMessage::TlvBack().
Begin() [1/2]
PbbTlvBlock::Iterator ns3::PbbTlvBlock::Begin (void)
Returns
an iterator to the first TLV in this block.
Definition at line 76 of file packetbb.cc.
References m_tlvList, and NS_LOG_FUNCTION.
Referenced by Clear(), GetSerializedSize(), operator==(), Print(), Serialize(), ns3::PbbMessage::TlvBegin(), and ns3::PbbPacket::TlvBegin().
Begin() [2/2]
PbbTlvBlock::ConstIterator ns3::PbbTlvBlock::Begin (void) const
Returns
a const iterator to the first TLV in this block.
Definition at line 83 of file packetbb.cc.
References m_tlvList, and NS_LOG_FUNCTION.
Clear()
void ns3::PbbTlvBlock::Clear (void)
Removes all TLVs from this block.
Definition at line 181 of file packetbb.cc.
References Begin(), End(), m_tlvList, and NS_LOG_FUNCTION.
Referenced by ~PbbTlvBlock(), ns3::PbbPacket::TlvClear(), and ns3::PbbMessage::TlvClear().
Deserialize()
void ns3::PbbTlvBlock::Deserialize (Buffer::Iterator & start)
Deserializes a block from the specified buffer.
Parameters
start a reference to the point in a buffer to begin deserializing.
Users should not need to call this. Blocks will be deserialized by their containing packet.
Definition at line 228 of file packetbb.cc.
References NS_LOG_FUNCTION, PushBack(), and visualizer.core::start().
Referenced by ns3::PbbMessage::Deserialize(), and ns3::PbbPacket::Deserialize().
Empty()
bool ns3::PbbTlvBlock::Empty (void) const
Returns
true if there are no TLVs in this block, false otherwise.
Definition at line 111 of file packetbb.cc.
References m_tlvList, and NS_LOG_FUNCTION.
Referenced by Serialize(), ns3::PbbPacket::TlvEmpty(), and ns3::PbbMessage::TlvEmpty().
End() [1/2]
PbbTlvBlock::Iterator ns3::PbbTlvBlock::End (void)
Returns
an iterator to the past-the-end element in this block.
Definition at line 90 of file packetbb.cc.
References m_tlvList, and NS_LOG_FUNCTION.
Referenced by Clear(), GetSerializedSize(), operator==(), Print(), Serialize(), ns3::PbbMessage::TlvEnd(), and ns3::PbbPacket::TlvEnd().
End() [2/2]
PbbTlvBlock::ConstIterator ns3::PbbTlvBlock::End (void) const
Returns
a const iterator to the past-the-end element in this block.
Definition at line 97 of file packetbb.cc.
References m_tlvList, and NS_LOG_FUNCTION.
Erase() [1/2]
PbbTlvBlock::Iterator ns3::PbbTlvBlock::Erase (PbbTlvBlock::Iterator first, PbbTlvBlock::Iterator last)
Removes all TLVs from [first, last) (includes first, not includes last).
Parameters
first an Iterator pointing to the first TLV to erase (inclusive).
last an Iterator pointing to the element past the last TLV to erase.
Returns
an iterator pointing to the next TLV in the block.
Definition at line 174 of file packetbb.cc.
References m_tlvList, and NS_LOG_FUNCTION.
Erase() [2/2]
PbbTlvBlock::Iterator ns3::PbbTlvBlock::Erase (PbbTlvBlock::Iterator position)
Removes the TLV at the specified position.
Parameters
position an Iterator pointing to the TLV to erase.
Returns
an iterator pointing to the next TLV in the block.
Definition at line 167 of file packetbb.cc.
References m_tlvList, and NS_LOG_FUNCTION.
Referenced by ns3::PbbPacket::Erase(), and ns3::PbbMessage::TlvErase().
Front()
Ptr< PbbTlv > ns3::PbbTlvBlock::Front (void) const
Returns
a smart pointer to the first TLV in this block.
Definition at line 118 of file packetbb.cc.
References m_tlvList, and NS_LOG_FUNCTION.
Referenced by ns3::PbbPacket::TlvFront(), and ns3::PbbMessage::TlvFront().
GetSerializedSize()
uint32_t ns3::PbbTlvBlock::GetSerializedSize (void) const
Returns
The size (in bytes) needed to serialize this block.
Definition at line 192 of file packetbb.cc.
References Begin(), End(), and NS_LOG_FUNCTION.
Referenced by ns3::PbbPacket::GetSerializedSize(), and ns3::PbbMessage::GetSerializedSize().
Insert()
PbbTlvBlock::Iterator ns3::PbbTlvBlock::Insert (PbbTlvBlock::Iterator position, const Ptr< PbbTlv > tlv)
Inserts a TLV at the specified position in this block.
Parameters
position an Iterator pointing to the position in this block to insert the TLV.
tlv a smart pointer to the TLV to insert.
Returns
An iterator pointing to the newly inserted TLV.
Definition at line 160 of file packetbb.cc.
References m_tlvList, and NS_LOG_FUNCTION.
operator!=()
bool ns3::PbbTlvBlock::operator!= (const PbbTlvBlock & other) const
Inequality operator for PbbTlvBlock.
Parameters
other PbbTlvBlock to compare this one to
Returns
true if the blocks are not equal
Definition at line 297 of file packetbb.cc.
operator==()
bool ns3::PbbTlvBlock::operator== (const PbbTlvBlock & other) const
Equality operator for PbbTlvBlock.
Parameters
other PbbTlvBlock to compare this one to
Returns
true if the blocks are equal
Definition at line 276 of file packetbb.cc.
References Begin(), End(), and Size().
PopBack()
void ns3::PbbTlvBlock::PopBack (void)
Removes a TLV from the back of this block.
Definition at line 153 of file packetbb.cc.
References m_tlvList, and NS_LOG_FUNCTION.
Referenced by ns3::PbbPacket::TlvPopBack(), and ns3::PbbMessage::TlvPopBack().
PopFront()
void ns3::PbbTlvBlock::PopFront (void)
Removes a TLV from the front of this block.
Definition at line 139 of file packetbb.cc.
References m_tlvList, and NS_LOG_FUNCTION.
Referenced by ns3::PbbPacket::TlvPopFront(), and ns3::PbbMessage::TlvPopFront().
Print() [1/2]
void ns3::PbbTlvBlock::Print (std::ostream & os) const
Pretty-prints the contents of this block.
Parameters
os a stream object to print to.
Definition at line 246 of file packetbb.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::PbbPacket::Print(), and ns3::PbbMessage::Print().
Print() [2/2]
void ns3::PbbTlvBlock::Print (std::ostream & os, int level) const
Pretty-prints the contents of this block, with specified indentation.
Parameters
os a stream object to print to.
level level of indentation.
This probably never needs to be called by users. This is used when recursively printing sub-objects.
Definition at line 253 of file packetbb.cc.
References Begin(), End(), NS_LOG_FUNCTION, and Size().
PushBack()
void ns3::PbbTlvBlock::PushBack (Ptr< PbbTlv > tlv)
Appends a TLV to the back of this block.
Parameters
tlv a smart pointer to the TLV to append.
Definition at line 146 of file packetbb.cc.
References m_tlvList, and NS_LOG_FUNCTION.
Referenced by Deserialize(), ns3::PbbPacket::TlvPushBack(), and ns3::PbbMessage::TlvPushBack().
PushFront()
void ns3::PbbTlvBlock::PushFront (Ptr< PbbTlv > tlv)
Prepends a TLV to the front of this block.
Parameters
tlv a smart pointer to the TLV to prepend.
Definition at line 132 of file packetbb.cc.
References m_tlvList, and NS_LOG_FUNCTION.
Referenced by ns3::PbbPacket::TlvPushFront(), and ns3::PbbMessage::TlvPushFront().
Serialize()
void ns3::PbbTlvBlock::Serialize (Buffer::Iterator & start) const
Serializes this block into the specified buffer.
Parameters
start a reference to the point in a buffer to begin serializing.
Users should not need to call this. Blocks will be serialized by their containing packet.
Definition at line 205 of file packetbb.cc.
References Begin(), Empty(), End(), NS_LOG_FUNCTION, visualizer.core::start(), and ns3::Buffer::Iterator::WriteHtonU16().
Referenced by ns3::PbbMessage::Serialize(), and ns3::PbbPacket::Serialize().
Size()
int ns3::PbbTlvBlock::Size (void) const
Returns
the number of TLVs in this block.
Definition at line 104 of file packetbb.cc.
References m_tlvList, and NS_LOG_FUNCTION.
Referenced by operator==(), Print(), ns3::PbbPacket::TlvSize(), and ns3::PbbMessage::TlvSize().
Member Data Documentation
m_tlvList
std::list< Ptr<PbbTlv> > ns3::PbbTlvBlock::m_tlvList private
PbbTlv container.
Definition at line 211 of file packetbb.h.
Referenced by Back(), Begin(), Clear(), Empty(), End(), Erase(), Front(), Insert(), PopBack(), PopFront(), PushBack(), PushFront(), and Size().
The documentation for this class was generated from the following files:
src/network/utils/packetbb.h
src/network/utils/packetbb.cc