ns-3: DsrSendBuffTest Class Reference
DsrSendBuffTest Class Reference
DSR Routing » DSR routing module tests | Test suites
Unit test for Send Buffer.
Public Member Functions
DsrSendBuffTest ()
~DsrSendBuffTest ()
void CheckSizeLimit ()
Check size limit function.
void CheckTimeout ()
Check timeout function.
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Public Attributes
dsr::DsrSendBuffer q
send buffer
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Unit test for Send Buffer.
Definition at line 448 of file dsr-test-suite.cc.
Constructor & Destructor Documentation
DsrSendBuffTest()
DsrSendBuffTest::DsrSendBuffTest ()
Definition at line 462 of file dsr-test-suite.cc.
~DsrSendBuffTest()
DsrSendBuffTest::~DsrSendBuffTest ()
Definition at line 467 of file dsr-test-suite.cc.
Member Function Documentation
CheckSizeLimit()
void DsrSendBuffTest::CheckSizeLimit ()
Check size limit function.
Definition at line 519 of file dsr-test-suite.cc.
References ns3::dsr::DsrSendBuffer::Enqueue(), ns3::dsr::DsrSendBuffer::GetMaxQueueLen(), ns3::dsr::DsrSendBuffer::GetSize(), NS_TEST_EXPECT_MSG_EQ, q, and ns3::Seconds().
Referenced by DoRun().
CheckTimeout()
void DsrSendBuffTest::CheckTimeout ()
Check timeout function.
Definition at line 538 of file dsr-test-suite.cc.
References ns3::dsr::DsrSendBuffer::GetSize(), NS_TEST_EXPECT_MSG_EQ, and q.
Referenced by DoRun().
DoRun()
void DsrSendBuffTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 471 of file dsr-test-suite.cc.
References CheckSizeLimit(), CheckTimeout(), ns3::dsr::DsrSendBuffer::Dequeue(), ns3::dsr::DsrSendBuffer::DropPacketWithDst(), ns3::dsr::DsrSendBuffer::Enqueue(), ns3::dsr::DsrSendBuffer::Find(), ns3::dsr::DsrSendBuffer::GetMaxQueueLen(), ns3::dsr::DsrSendBuffer::GetSendBufferTimeout(), ns3::dsr::DsrSendBuffer::GetSize(), NS_TEST_EXPECT_MSG_EQ, q, ns3::Seconds(), ns3::dsr::DsrSendBuffer::SetMaxQueueLen(), and ns3::dsr::DsrSendBuffer::SetSendBufferTimeout().
Member Data Documentation
q
dsr::DsrSendBuffer DsrSendBuffTest::q
send buffer
Definition at line 460 of file dsr-test-suite.cc.
Referenced by CheckSizeLimit(), CheckTimeout(), and DoRun().
The documentation for this class was generated from the following file:
src/dsr/test/dsr-test-suite.cc