ns-3: ns3::LteNetDevice Class Reference
ns3::LteNetDevice Class Reference
LTE Models
LteNetDevice provides basic implementation for all LTE network devices.
#include "lte-net-device.h"
Public Member Functions
LteNetDevice (void)
virtual ~LteNetDevice (void)
virtual void AddLinkChangeCallback (Callback< void > callback)
virtual void DoDispose (void)
Destructor implementation.
virtual Address GetAddress (void) const
virtual Address GetBroadcast (void) const
virtual Ptr< Channel > GetChannel (void) const
virtual uint32_t GetIfIndex (void) const
virtual uint16_t GetMtu (void) const
virtual Address GetMulticast (Ipv4Address addr) const
Make and return a MAC multicast address using the provided multicast group.
virtual Address GetMulticast (Ipv6Address addr) const
Get the MAC multicast address corresponding to the IPv6 address provided.
virtual Ptr< Node > GetNode (void) const
virtual bool IsBridge (void) const
Return true if the net device is acting as a bridge.
virtual bool IsBroadcast (void) const
virtual bool IsLinkUp (void) const
virtual bool IsMulticast (void) const
virtual bool IsPointToPoint (void) const
Return true if the net device is on a point-to-point link.
virtual bool NeedsArp (void) const
void Receive (Ptr< Packet > p)
receive a packet from the lower layers in order to forward it to the upper layers
virtual bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
virtual void SetAddress (Address address)
Set the address of this interface.
virtual void SetIfIndex (const uint32_t index)
virtual bool SetMtu (const uint16_t mtu)
virtual void SetNode (Ptr< Node > node)
virtual void SetPromiscReceiveCallback (PromiscReceiveCallback cb)
virtual void SetReceiveCallback (NetDevice::ReceiveCallback cb)
virtual bool SupportsSendFrom (void) const
Public Member Functions inherited from ns3::NetDevice
virtual ~NetDevice ()
virtual bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)=0
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::NetDevice
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Attributes
NetDevice::ReceiveCallback m_rxCallback
receive callback
Private Member Functions
LteNetDevice (const LteNetDevice &)
type conversion operator
LteNetDevice & operator= (const LteNetDevice &)
assignment operator
Private Attributes
Mac64Address m_address
MAC address - only relevant for UEs.
uint32_t m_ifIndex
interface index
TracedCallback m_linkChangeCallbacks
link change callback
bool m_linkUp
link uo
uint16_t m_mtu
MTU.
Ptr< Node > m_node
the node
Additional Inherited Members
Public Types inherited from ns3::NetDevice
typedef void(* LinkChangeTracedCallback) (void)
TracedCallback signature for link changed event.
enum PacketType {
PACKET_HOST = 1 , NS3_PACKET_HOST = PACKET_HOST , PACKET_BROADCAST , NS3_PACKET_BROADCAST = PACKET_BROADCAST ,
PACKET_MULTICAST , NS3_PACKET_MULTICAST = PACKET_MULTICAST , PACKET_OTHERHOST , NS3_PACKET_OTHERHOST = PACKET_OTHERHOST
}
Packet types are used as they are in Linux.
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address &, const Address &, enum PacketType > PromiscReceiveCallback
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address & > ReceiveCallback
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
LteNetDevice provides basic implementation for all LTE network devices.
Config Paths
ns3::LteNetDevice is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/DeviceList/[i]/$ns3::LteNetDevice"
Attributes
Mtu: The MAC-level Maximum Transmission Unit
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 30000
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 88 bytes (on a 64-bit architecture).
Definition at line 48 of file lte-net-device.h.
Constructor & Destructor Documentation
LteNetDevice() [1/2]
ns3::LteNetDevice::LteNetDevice (void)
Definition at line 65 of file lte-net-device.cc.
References NS_LOG_FUNCTION.
~LteNetDevice()
ns3::LteNetDevice::~LteNetDevice (void) virtual
Definition at line 71 of file lte-net-device.cc.
References NS_LOG_FUNCTION.
LteNetDevice() [2/2]
ns3::LteNetDevice::LteNetDevice (const LteNetDevice &) private
type conversion operator
Member Function Documentation
AddLinkChangeCallback()
void ns3::LteNetDevice::AddLinkChangeCallback (Callback< void > callback) virtual
Parameters
callback the callback to invoke
Add a callback invoked whenever the link status changes to UP. This callback is typically used by the IP/ARP layer to flush the ARP cache and by IPv6 stack to flush NDISC cache whenever the link goes up.
Implements ns3::NetDevice.
Definition at line 264 of file lte-net-device.cc.
References ns3::TracedCallback< Ts >::ConnectWithoutContext(), m_linkChangeCallbacks, and NS_LOG_FUNCTION.
DoDispose()
void ns3::LteNetDevice::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Reimplemented in ns3::LteEnbNetDevice, and ns3::LteUeNetDevice.
Definition at line 78 of file lte-net-device.cc.
References ns3::Object::DoDispose(), m_node, and NS_LOG_FUNCTION.
Referenced by ns3::LteUeNetDevice::DoDispose(), and ns3::LteEnbNetDevice::DoDispose().
GetAddress()
Address ns3::LteNetDevice::GetAddress (void) const virtual
Returns
the current Address of this interface.
Implements ns3::NetDevice.
Definition at line 105 of file lte-net-device.cc.
References m_address, and NS_LOG_FUNCTION.
GetBroadcast()
Address ns3::LteNetDevice::GetBroadcast (void) const virtual
Returns
the broadcast address supported by this netdevice.
Calling this method is invalid if IsBroadcast returns not true.
Implements ns3::NetDevice.
Definition at line 199 of file lte-net-device.cc.
References ns3::Mac48Address::GetBroadcast(), and NS_LOG_FUNCTION.
GetChannel()
Ptr< Channel > ns3::LteNetDevice::GetChannel (void) const virtual
Returns
the channel this NetDevice is connected to. The value returned can be zero if the NetDevice is not yet connected to any channel or if the underlying NetDevice has no concept of a channel. i.e., callers must check for zero and be ready to handle it.
Implements ns3::NetDevice.
Definition at line 88 of file lte-net-device.cc.
References NS_LOG_FUNCTION.
GetIfIndex()
uint32_t ns3::LteNetDevice::GetIfIndex (void) const virtual
Returns
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 176 of file lte-net-device.cc.
References m_ifIndex, and NS_LOG_FUNCTION.
Referenced by ns3::LteHelper::ActivateDataRadioBearer().
GetMtu()
uint16_t ns3::LteNetDevice::GetMtu (void) const virtual
Returns
the link-level MTU in bytes for this interface.
This value is typically used by the IP layer to perform IP fragmentation when needed.
Implements ns3::NetDevice.
Definition at line 161 of file lte-net-device.cc.
References m_mtu, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetMulticast() [1/2]
Address ns3::LteNetDevice::GetMulticast (Ipv4Address multicastGroup) const virtual
Make and return a MAC multicast address using the provided multicast group.
RFC 1112 says that an Ipv4 host group address is mapped to an Ethernet multicast address by placing the low-order 23-bits of the IP address into the low-order 23 bits of the Ethernet multicast address 01-00-5E-00-00-00 (hex). Similar RFCs exist for Ipv6 and Eui64 mappings. This method performs the multicast address creation function appropriate to the underlying MAC address of the device. This MAC address is encapsulated in an abstract Address to avoid dependencies on the exact MAC address format.
In the case of net devices that do not support multicast, clients are expected to test NetDevice::IsMulticast and avoid attempting to map multicast packets. Subclasses of NetDevice that do support multicasting are expected to override this method and provide an implementation appropriate to the particular device.
Parameters
multicastGroup The IP address for the multicast group destination of the packet.
Returns
The MAC multicast Address used to send packets to the provided multicast group.
Warning
Calling this method is invalid if IsMulticast returns not true.
See also
IsMulticast()
Implements ns3::NetDevice.
Definition at line 237 of file lte-net-device.cc.
References ns3::Mac48Address::GetMulticast(), NS_LOG_FUNCTION, and NS_LOG_LOGIC.
GetMulticast() [2/2]
Address ns3::LteNetDevice::GetMulticast (Ipv6Address addr) const virtual
Get the MAC multicast address corresponding to the IPv6 address provided.
Parameters
addr IPv6 address
Returns
the MAC multicast address
Warning
Calling this method is invalid if IsMulticast returns not true.
Implements ns3::NetDevice.
Definition at line 254 of file lte-net-device.cc.
References ns3::Mac48Address::GetMulticast(), NS_LOG_FUNCTION, and NS_LOG_LOGIC.
GetNode()
Ptr< Node > ns3::LteNetDevice::GetNode (void) const virtual
Returns
the node base class which contains this network interface.
When a subclass needs to get access to the underlying node base class to print the nodeid for example, it can invoke this method.
Implements ns3::NetDevice.
Definition at line 120 of file lte-net-device.cc.
References m_node, and NS_LOG_FUNCTION.
Referenced by ns3::LteHelper::ActivateDataRadioBearer().
GetTypeId()
TypeId ns3::LteNetDevice::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 51 of file lte-net-device.cc.
References GetMtu(), ns3::MakeUintegerAccessor(), SetMtu(), and ns3::TypeId::SetParent().
IsBridge()
bool ns3::LteNetDevice::IsBridge (void) const virtual
Return true if the net device is acting as a bridge.
Returns
value of m_isBridge flag
Implements ns3::NetDevice.
Definition at line 230 of file lte-net-device.cc.
References NS_LOG_FUNCTION.
IsBroadcast()
bool ns3::LteNetDevice::IsBroadcast (void) const virtual
Returns
true if this interface supports a broadcast address, false otherwise.
Implements ns3::NetDevice.
Definition at line 192 of file lte-net-device.cc.
References NS_LOG_FUNCTION.
IsLinkUp()
bool ns3::LteNetDevice::IsLinkUp (void) const virtual
Returns
true if link is up; false otherwise
Implements ns3::NetDevice.
Definition at line 184 of file lte-net-device.cc.
References m_linkUp, and NS_LOG_FUNCTION.
IsMulticast()
bool ns3::LteNetDevice::IsMulticast (void) const virtual
Returns
value of m_isMulticast flag
Implements ns3::NetDevice.
Definition at line 206 of file lte-net-device.cc.
References NS_LOG_FUNCTION.
IsPointToPoint()
bool ns3::LteNetDevice::IsPointToPoint (void) const virtual
Return true if the net device is on a point-to-point link.
Returns
value of m_isPointToPoint flag
Implements ns3::NetDevice.
Definition at line 214 of file lte-net-device.cc.
References NS_LOG_FUNCTION.
NeedsArp()
bool ns3::LteNetDevice::NeedsArp (void) const virtual
Returns
true if ARP is needed, false otherwise.
Called by higher-layers to check if this NetDevice requires ARP to be used.
Implements ns3::NetDevice.
Definition at line 222 of file lte-net-device.cc.
References NS_LOG_FUNCTION.
operator=()
LteNetDevice& ns3::LteNetDevice::operator= (const LteNetDevice &) private
assignment operator
Returns
LteNetDevice
Receive()
void ns3::LteNetDevice::Receive (Ptr< Packet > p)
receive a packet from the lower layers in order to forward it to the upper layers
Parameters
p the packet
Definition at line 278 of file lte-net-device.cc.
References m_rxCallback, NS_ABORT_MSG, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Packet::PeekHeader(), ns3::Ipv4L3Protocol::PROT_NUMBER, and ns3::Ipv6L3Protocol::PROT_NUMBER.
Referenced by ns3::LteHelper::InstallSingleEnbDevice(), and ns3::LteHelper::InstallSingleUeDevice().
SendFrom()
bool ns3::LteNetDevice::SendFrom (Ptr< Packet > packet, const Address & source, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
source source mac address (so called "MAC spoofing")
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device with the specified source and destination Addresses.
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 136 of file lte-net-device.cc.
References NS_FATAL_ERROR.
SetAddress()
void ns3::LteNetDevice::SetAddress (Address address) virtual
Set the address of this interface.
Parameters
address address to set
Implements ns3::NetDevice.
Definition at line 97 of file lte-net-device.cc.
References first::address, ns3::Mac64Address::ConvertFrom(), m_address, and NS_LOG_FUNCTION.
SetIfIndex()
void ns3::LteNetDevice::SetIfIndex (const uint32_t index) virtual
Parameters
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 169 of file lte-net-device.cc.
References m_ifIndex, and NS_LOG_FUNCTION.
SetMtu()
bool ns3::LteNetDevice::SetMtu (const uint16_t mtu) virtual
Parameters
mtu MTU value, in bytes, to set for the device
Returns
whether the MTU value was within legal bounds
Override for default MTU defined on a per-type basis.
Implements ns3::NetDevice.
Definition at line 153 of file lte-net-device.cc.
References m_mtu, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetNode()
void ns3::LteNetDevice::SetNode (Ptr< Node > node) virtual
Parameters
node the node associated to this netdevice.
This method is called from ns3::Node::AddDevice.
Implements ns3::NetDevice.
Definition at line 112 of file lte-net-device.cc.
References m_node, and NS_LOG_FUNCTION.
Referenced by ns3::LteHelper::InstallSingleEnbDevice().
SetPromiscReceiveCallback()
void ns3::LteNetDevice::SetPromiscReceiveCallback (PromiscReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received in promiscuous mode and must be forwarded to the higher layers.
Enables netdevice promiscuous mode and sets the callback that will handle promiscuous mode packets. Note, promiscuous mode packets means all packets, including those packets that can be sensed by the netdevice but which are intended to be received by other hosts.
Implements ns3::NetDevice.
Definition at line 271 of file lte-net-device.cc.
References NS_LOG_FUNCTION, and NS_LOG_WARN.
SetReceiveCallback()
void ns3::LteNetDevice::SetReceiveCallback (NetDevice::ReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received and must be forwarded to the higher layers.
Set the callback to be used to notify higher layers when a packet has been received.
Implements ns3::NetDevice.
Definition at line 128 of file lte-net-device.cc.
References m_rxCallback, and NS_LOG_FUNCTION.
SupportsSendFrom()
bool ns3::LteNetDevice::SupportsSendFrom (void) const virtual
Returns
true if this interface supports a bridging mode, false otherwise.
Implements ns3::NetDevice.
Definition at line 144 of file lte-net-device.cc.
References NS_LOG_FUNCTION.
Member Data Documentation
m_address
Mac64Address ns3::LteNetDevice::m_address private
MAC address - only relevant for UEs.
Definition at line 115 of file lte-net-device.h.
Referenced by GetAddress(), and SetAddress().
m_ifIndex
uint32_t ns3::LteNetDevice::m_ifIndex private
interface index
Definition at line 111 of file lte-net-device.h.
Referenced by GetIfIndex(), and SetIfIndex().
m_linkChangeCallbacks
TracedCallback ns3::LteNetDevice::m_linkChangeCallbacks private
link change callback
Definition at line 109 of file lte-net-device.h.
Referenced by AddLinkChangeCallback().
m_linkUp
bool ns3::LteNetDevice::m_linkUp private
link uo
Definition at line 112 of file lte-net-device.h.
Referenced by IsLinkUp().
m_mtu
uint16_t ns3::LteNetDevice::m_mtu mutable private
MTU.
Definition at line 113 of file lte-net-device.h.
Referenced by GetMtu(), and SetMtu().
m_node
Ptr<Node> ns3::LteNetDevice::m_node private
the node
Definition at line 107 of file lte-net-device.h.
Referenced by DoDispose(), GetNode(), and SetNode().
m_rxCallback
NetDevice::ReceiveCallback ns3::LteNetDevice::m_rxCallback protected
receive callback
Definition at line 96 of file lte-net-device.h.
Referenced by Receive(), and SetReceiveCallback().
The documentation for this class was generated from the following files:
src/lte/model/lte-net-device.h
src/lte/model/lte-net-device.cc