ns-3: ns3::RawTextConfigLoad Class Reference
ns3::RawTextConfigLoad Class Reference
Configuration Store/Load
A class to enable loading of configuration store from a raw text file.
#include "raw-text-config.h"
Public Member Functions
RawTextConfigLoad ()
default constructor
virtual ~RawTextConfigLoad ()
destructor
virtual void Attributes (void)
Load or save the attributes values.
virtual void Default (void)
Load or save the default values.
virtual void Global (void)
Load or save the global values.
virtual void SetFilename (std::string filename)
Set the file name.
Public Member Functions inherited from ns3::FileConfig
virtual ~FileConfig ()
Private Member Functions
virtual bool ParseLine (const std::string &line, std::string &type, std::string &name, std::string &value)
Parse (potentially multi-) line configs into type, name, and values.
std::string Strip (std::string value)
Strip out attribute value.
Private Attributes
std::ifstream * m_is
Config store input stream.
Detailed Description
A class to enable loading of configuration store from a raw text file.
Definition at line 55 of file raw-text-config.h.
Constructor & Destructor Documentation
RawTextConfigLoad()
ns3::RawTextConfigLoad::RawTextConfigLoad ()
default constructor
Definition at line 120 of file raw-text-config.cc.
References NS_LOG_FUNCTION.
~RawTextConfigLoad()
ns3::RawTextConfigLoad::~RawTextConfigLoad () virtual
destructor
Definition at line 125 of file raw-text-config.cc.
References m_is, and NS_LOG_FUNCTION.
Member Function Documentation
Attributes()
void ns3::RawTextConfigLoad::Attributes (void) virtual
Load or save the attributes values.
Implements ns3::FileConfig.
Definition at line 204 of file raw-text-config.cc.
References m_is, NS_LOG_DEBUG, NS_LOG_FUNCTION, ParseLine(), ns3::Config::Set(), and Strip().
Referenced by ns3::load_clicked_attribute().
Default()
void ns3::RawTextConfigLoad::Default (void) virtual
Load or save the default values.
Implements ns3::FileConfig.
Definition at line 154 of file raw-text-config.cc.
References m_is, NS_LOG_DEBUG, NS_LOG_FUNCTION, ParseLine(), ns3::Config::SetDefault(), and Strip().
Referenced by ns3::load_clicked_default().
Global()
void ns3::RawTextConfigLoad::Global (void) virtual
Load or save the global values.
Implements ns3::FileConfig.
Definition at line 179 of file raw-text-config.cc.
References m_is, NS_LOG_DEBUG, NS_LOG_FUNCTION, ParseLine(), ns3::Config::SetGlobal(), and Strip().
ParseLine()
bool ns3::RawTextConfigLoad::ParseLine (const std::string & line, std::string & type, std::string & name, std::string & value) private virtual
Parse (potentially multi-) line configs into type, name, and values.
This will return false for blank lines, comments (lines beginning with '#'), and incomplete entries. An entry is considered complete when a type and name have been found and the value contains two delimiting quotation marks '"'.
Parameters
line the config file line
type the config type {default, global, value}
name the config attribute name
value the value to set
Returns
true if all of type, name, and value parsed; false otherwise
Definition at line 230 of file raw-text-config.cc.
References NS_LOG_FUNCTION.
Referenced by Attributes(), Default(), and Global().
SetFilename()
void ns3::RawTextConfigLoad::SetFilename (std::string filename) virtual
Set the file name.
Parameters
filename the filename
Implements ns3::FileConfig.
Definition at line 136 of file raw-text-config.cc.
References m_is, and NS_LOG_FUNCTION.
Referenced by ns3::load_clicked_attribute(), and ns3::load_clicked_default().
Strip()
std::string ns3::RawTextConfigLoad::Strip (std::string value) private
Strip out attribute value.
Parameters
value the input string
Returns
the updated string
Definition at line 143 of file raw-text-config.cc.
References NS_ABORT_MSG_IF, NS_LOG_FUNCTION, and visualizer.core::start().
Referenced by Attributes(), Default(), and Global().
Member Data Documentation
m_is
std::ifstream* ns3::RawTextConfigLoad::m_is private
Config store input stream.
Definition at line 87 of file raw-text-config.h.
Referenced by ~RawTextConfigLoad(), Attributes(), Default(), Global(), and SetFilename().
The documentation for this class was generated from the following files:
src/config-store/model/raw-text-config.h
src/config-store/model/raw-text-config.cc