ns-3: ns3::LteUeRrcProtocolReal Class Reference
ns3::LteUeRrcProtocolReal Class Reference
LTE Models
Models the transmission of RRC messages from the UE to the eNB in a real fashion, by creating real RRC PDUs and transmitting them over Signaling Radio Bearers using radio resources allocated by the LTE MAC scheduler.
#include "lte-rrc-protocol-real.h"
Public Member Functions
LteUeRrcProtocolReal ()
virtual ~LteUeRrcProtocolReal ()
virtual void DoDispose (void)
Destructor implementation.
LteUeRrcSapUser * GetLteUeRrcSapUser ()
Get LTE UE RRC SAP user function.
void SetLteUeRrcSapProvider (LteUeRrcSapProvider *p)
Set LTE UE RRC SAP provider function.
void SetUeRrc (Ptr< LteUeRrc > rrc)
Set UE RRC function.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void DoReceivePdcpPdu (Ptr< Packet > p)
Receive PDCP PDU function.
void DoReceivePdcpSdu (LtePdcpSapUser::ReceivePdcpSduParameters params)
Receive PDCP SDU function.
void DoSendIdealUeContextRemoveRequest (uint16_t rnti)
Send ideal UE context remove request function.
void DoSendMeasurementReport (LteRrcSap::MeasurementReport msg)
Send measurement report function.
void DoSendRrcConnectionReconfigurationCompleted (LteRrcSap::RrcConnectionReconfigurationCompleted msg)
Send RRC connection reconfiguration setup completed function.
void DoSendRrcConnectionReestablishmentComplete (LteRrcSap::RrcConnectionReestablishmentComplete msg)
Send RRC connection reestablishment complete function.
void DoSendRrcConnectionReestablishmentRequest (LteRrcSap::RrcConnectionReestablishmentRequest msg)
Send RRC connection reestablishment request function.
void DoSendRrcConnectionRequest (LteRrcSap::RrcConnectionRequest msg)
Send RRC connection request function.
void DoSendRrcConnectionSetupCompleted (LteRrcSap::RrcConnectionSetupCompleted msg)
Send RRC connection setup completed function.
void DoSetup (LteUeRrcSapUser::SetupParameters params)
Setup function.
void SetEnbRrcSapProvider ()
Set ENB RRC SAP provider.
Private Attributes
LteUeRrcSapProvider::CompleteSetupParameters m_completeSetupParameters
complete setup parameters
LteEnbRrcSapProvider * m_enbRrcSapProvider
ENB RRC SAP provider.
uint16_t m_rnti
the RNTI
Ptr< LteUeRrc > m_rrc
the RRC
LteUeRrcSapUser::SetupParameters m_setupParameters
setup parameters
LteUeRrcSapProvider * m_ueRrcSapProvider
UE RRC SAP provider.
LteUeRrcSapUser * m_ueRrcSapUser
UE RRC SAP user.
Friends
class LtePdcpSpecificLtePdcpSapUser< LteUeRrcProtocolReal >
allow LtePdcpSpecificLtePdcpSapUser<LteUeRrcProtocolReal> class friend access
class LteRlcSpecificLteRlcSapUser< LteUeRrcProtocolReal >
allow LteRlcSpecificLteRlcSapUser<LteUeRrcProtocolReal> class friend access
class MemberLteUeRrcSapUser< LteUeRrcProtocolReal >
allow MemberLteUeRrcSapUser<LteUeRrcProtocolReal> class friend access
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Models the transmission of RRC messages from the UE to the eNB in a real fashion, by creating real RRC PDUs and transmitting them over Signaling Radio Bearers using radio resources allocated by the LTE MAC scheduler.
Introspection did not find any typical Config paths.
No Attributes are defined for this type.
No TraceSources are defined for this type.
Size of this type is 104 bytes (on a 64-bit architecture).
Definition at line 53 of file lte-rrc-protocol-real.h.
Constructor & Destructor Documentation
LteUeRrcProtocolReal()
ns3::LteUeRrcProtocolReal::LteUeRrcProtocolReal ()
Definition at line 44 of file lte-rrc-protocol-real.cc.
References LtePdcpSpecificLtePdcpSapUser< LteUeRrcProtocolReal >, LteRlcSpecificLteRlcSapUser< LteUeRrcProtocolReal >, m_completeSetupParameters, m_ueRrcSapUser, MemberLteUeRrcSapUser< LteUeRrcProtocolReal >, ns3::LteUeRrcSapProvider::CompleteSetupParameters::srb0SapUser, and ns3::LteUeRrcSapProvider::CompleteSetupParameters::srb1SapUser.
~LteUeRrcProtocolReal()
ns3::LteUeRrcProtocolReal::~LteUeRrcProtocolReal () virtual
Definition at line 53 of file lte-rrc-protocol-real.cc.
Member Function Documentation
DoDispose()
void ns3::LteUeRrcProtocolReal::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 58 of file lte-rrc-protocol-real.cc.
References m_completeSetupParameters, m_rrc, m_ueRrcSapUser, NS_LOG_FUNCTION, ns3::LteUeRrcSapProvider::CompleteSetupParameters::srb0SapUser, and ns3::LteUeRrcSapProvider::CompleteSetupParameters::srb1SapUser.
DoReceivePdcpPdu()
void ns3::LteUeRrcProtocolReal::DoReceivePdcpPdu (Ptr< Packet > p) private
Receive PDCP PDU function.
Parameters
p the packet
Definition at line 299 of file lte-rrc-protocol-real.cc.
References ns3::RrcConnectionSetupHeader::GetMessage(), ns3::RrcConnectionReestablishmentHeader::GetMessage(), ns3::RrcConnectionReestablishmentRejectHeader::GetMessage(), ns3::RrcConnectionRejectHeader::GetMessage(), ns3::RrcAsn1Header::GetMessageType(), m_ueRrcSapProvider, ns3::Packet::PeekHeader(), ns3::LteUeRrcSapProvider::RecvRrcConnectionReestablishment(), ns3::LteUeRrcSapProvider::RecvRrcConnectionReject(), ns3::LteUeRrcSapProvider::RecvRrcConnectionSetup(), and ns3::Packet::RemoveHeader().
DoReceivePdcpSdu()
void ns3::LteUeRrcProtocolReal::DoReceivePdcpSdu (LtePdcpSapUser::ReceivePdcpSduParameters params) private
Receive PDCP SDU function.
Parameters
params LtePdcpSapUser::ReceivePdcpSduParameters
Definition at line 348 of file lte-rrc-protocol-real.cc.
References ns3::RrcConnectionReconfigurationHeader::GetMessage(), ns3::RrcConnectionReleaseHeader::GetMessage(), ns3::RrcAsn1Header::GetMessageType(), m_ueRrcSapProvider, ns3::LtePdcpSapUser::ReceivePdcpSduParameters::pdcpSdu, ns3::Packet::PeekHeader(), ns3::LteUeRrcSapProvider::RecvRrcConnectionReconfiguration(), and ns3::Packet::RemoveHeader().
DoSendIdealUeContextRemoveRequest()
void ns3::LteUeRrcProtocolReal::DoSendIdealUeContextRemoveRequest (uint16_t rnti) private
Send ideal UE context remove request function.
Notify eNodeB to release UE context once radio link failure or random access failure is detected. It is needed since no RLF detection mechanism at eNodeB is implemented
Parameters
rnti the RNTI of the UE
Definition at line 197 of file lte-rrc-protocol-real.cc.
References m_enbRrcSapProvider, m_rnti, m_rrc, NS_ABORT_MSG_IF, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::LteEnbRrcSapProvider::RecvIdealUeContextRemoveRequest(), ns3::RRC_REAL_MSG_DELAY, ns3::Simulator::Schedule(), and SetEnbRrcSapProvider().
DoSendMeasurementReport()
void ns3::LteUeRrcProtocolReal::DoSendMeasurementReport (LteRrcSap::MeasurementReport msg) private
Send measurement report function.
Parameters
msg LteRrcSap::MeasurementReport
Definition at line 174 of file lte-rrc-protocol-real.cc.
References ns3::Packet::AddHeader(), ns3::LtePdcpSapProvider::TransmitPdcpSduParameters::lcid, m_rnti, m_rrc, m_setupParameters, ns3::LtePdcpSapProvider::TransmitPdcpSduParameters::pdcpSdu, ns3::LtePdcpSapProvider::TransmitPdcpSduParameters::rnti, SetEnbRrcSapProvider(), ns3::MeasurementReportHeader::SetMessage(), ns3::LteUeRrcSapUser::SetupParameters::srb1SapProvider, and ns3::LtePdcpSapProvider::TransmitPdcpSdu().
DoSendRrcConnectionReconfigurationCompleted()
void ns3::LteUeRrcProtocolReal::DoSendRrcConnectionReconfigurationCompleted (LteRrcSap::RrcConnectionReconfigurationCompleted msg) private
Send RRC connection reconfiguration setup completed function.
Parameters
msg LteRrcSap::RrcConnectionReconfigurationCompleted
Definition at line 151 of file lte-rrc-protocol-real.cc.
References ns3::Packet::AddHeader(), ns3::LtePdcpSapProvider::TransmitPdcpSduParameters::lcid, m_rnti, m_rrc, m_setupParameters, ns3::LtePdcpSapProvider::TransmitPdcpSduParameters::pdcpSdu, ns3::LtePdcpSapProvider::TransmitPdcpSduParameters::rnti, SetEnbRrcSapProvider(), ns3::RrcConnectionReconfigurationCompleteHeader::SetMessage(), ns3::LteUeRrcSapUser::SetupParameters::srb1SapProvider, and ns3::LtePdcpSapProvider::TransmitPdcpSdu().
DoSendRrcConnectionReestablishmentComplete()
void ns3::LteUeRrcProtocolReal::DoSendRrcConnectionReestablishmentComplete (LteRrcSap::RrcConnectionReestablishmentComplete msg) private
Send RRC connection reestablishment complete function.
Parameters
msg LteRrcSap::RrcConnectionReestablishmentComplete
Definition at line 236 of file lte-rrc-protocol-real.cc.
References ns3::Packet::AddHeader(), ns3::LtePdcpSapProvider::TransmitPdcpSduParameters::lcid, m_rnti, m_setupParameters, ns3::LtePdcpSapProvider::TransmitPdcpSduParameters::pdcpSdu, ns3::LtePdcpSapProvider::TransmitPdcpSduParameters::rnti, ns3::RrcConnectionReestablishmentCompleteHeader::SetMessage(), ns3::LteUeRrcSapUser::SetupParameters::srb1SapProvider, and ns3::LtePdcpSapProvider::TransmitPdcpSdu().
DoSendRrcConnectionReestablishmentRequest()
void ns3::LteUeRrcProtocolReal::DoSendRrcConnectionReestablishmentRequest (LteRrcSap::RrcConnectionReestablishmentRequest msg) private
Send RRC connection reestablishment request function.
Parameters
msg LteRrcSap::RrcConnectionReestablishmentRequest
Definition at line 218 of file lte-rrc-protocol-real.cc.
References ns3::Packet::AddHeader(), ns3::LteRlcSapProvider::TransmitPdcpPduParameters::lcid, m_rnti, m_setupParameters, ns3::LteRlcSapProvider::TransmitPdcpPduParameters::pdcpPdu, ns3::LteRlcSapProvider::TransmitPdcpPduParameters::rnti, ns3::RrcConnectionReestablishmentRequestHeader::SetMessage(), ns3::LteUeRrcSapUser::SetupParameters::srb0SapProvider, and ns3::LteRlcSapProvider::TransmitPdcpPdu().
DoSendRrcConnectionRequest()
void ns3::LteUeRrcProtocolReal::DoSendRrcConnectionRequest (LteRrcSap::RrcConnectionRequest msg) private
Send RRC connection request function.
Parameters
msg LteRrcSap::RrcConnectionRequest
Definition at line 107 of file lte-rrc-protocol-real.cc.
References ns3::Packet::AddHeader(), ns3::LteRlcSapProvider::TransmitPdcpPduParameters::lcid, m_rnti, m_rrc, m_setupParameters, ns3::LteRlcSapProvider::TransmitPdcpPduParameters::pdcpPdu, ns3::LteRlcSapProvider::TransmitPdcpPduParameters::rnti, SetEnbRrcSapProvider(), ns3::RrcConnectionRequestHeader::SetMessage(), ns3::LteUeRrcSapUser::SetupParameters::srb0SapProvider, and ns3::LteRlcSapProvider::TransmitPdcpPdu().
DoSendRrcConnectionSetupCompleted()
void ns3::LteUeRrcProtocolReal::DoSendRrcConnectionSetupCompleted (LteRrcSap::RrcConnectionSetupCompleted msg) private
Send RRC connection setup completed function.
Parameters
msg LteRrcSap::RrcConnectionSetupCompleted
Definition at line 130 of file lte-rrc-protocol-real.cc.
References ns3::Packet::AddHeader(), ns3::LtePdcpSapProvider::TransmitPdcpSduParameters::lcid, m_rnti, m_setupParameters, ns3::LtePdcpSapProvider::TransmitPdcpSduParameters::pdcpSdu, ns3::LtePdcpSapProvider::TransmitPdcpSduParameters::rnti, ns3::RrcConnectionSetupCompleteHeader::SetMessage(), ns3::LteUeRrcSapUser::SetupParameters::srb1SapProvider, and ns3::LtePdcpSapProvider::TransmitPdcpSdu().
DoSetup()
void ns3::LteUeRrcProtocolReal::DoSetup (LteUeRrcSapUser::SetupParameters params) private
Setup function.
Parameters
params LteUeRrcSapUser::SetupParameters
Definition at line 97 of file lte-rrc-protocol-real.cc.
References ns3::LteUeRrcSapProvider::CompleteSetup(), m_completeSetupParameters, m_setupParameters, m_ueRrcSapProvider, NS_LOG_FUNCTION, ns3::LteUeRrcSapUser::SetupParameters::srb0SapProvider, and ns3::LteUeRrcSapUser::SetupParameters::srb1SapProvider.
GetLteUeRrcSapUser()
LteUeRrcSapUser * ns3::LteUeRrcProtocolReal::GetLteUeRrcSapUser ()
Get LTE UE RRC SAP user function.
Returns
LTE UE RRC SAP user
Definition at line 85 of file lte-rrc-protocol-real.cc.
References m_ueRrcSapUser.
GetTypeId()
TypeId ns3::LteUeRrcProtocolReal::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 68 of file lte-rrc-protocol-real.cc.
References ns3::TypeId::SetParent().
SetEnbRrcSapProvider()
void ns3::LteUeRrcProtocolReal::SetEnbRrcSapProvider () private
Set ENB RRC SAP provider.
Definition at line 255 of file lte-rrc-protocol-real.cc.
References ns3::NodeList::Begin(), ns3::NodeList::End(), ns3::Node::GetDevice(), ns3::Node::GetNDevices(), ns3::LteEnbNetDevice::GetRrc(), ns3::LteEnbNetDevice::HasCellId(), m_enbRrcSapProvider, m_rnti, m_rrc, m_ueRrcSapProvider, NS_ASSERT_MSG, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by DoSendIdealUeContextRemoveRequest(), DoSendMeasurementReport(), DoSendRrcConnectionReconfigurationCompleted(), and DoSendRrcConnectionRequest().
SetLteUeRrcSapProvider()
void ns3::LteUeRrcProtocolReal::SetLteUeRrcSapProvider (LteUeRrcSapProvider * p)
Set LTE UE RRC SAP provider function.
Parameters
p the LTE UE RRC SAP provider
Definition at line 79 of file lte-rrc-protocol-real.cc.
References m_ueRrcSapProvider.
SetUeRrc()
void ns3::LteUeRrcProtocolReal::SetUeRrc (Ptr< LteUeRrc > rrc)
Set UE RRC function.
Parameters
rrc the LTE UE RRC
Definition at line 91 of file lte-rrc-protocol-real.cc.
References m_rrc.
Friends And Related Function Documentation
LtePdcpSpecificLtePdcpSapUser< LteUeRrcProtocolReal >
friend class LtePdcpSpecificLtePdcpSapUser< LteUeRrcProtocolReal > friend
allow LtePdcpSpecificLtePdcpSapUser<LteUeRrcProtocolReal> class friend access
Definition at line 1 of file lte-rrc-protocol-real.h.
Referenced by LteUeRrcProtocolReal().
LteRlcSpecificLteRlcSapUser< LteUeRrcProtocolReal >
friend class LteRlcSpecificLteRlcSapUser< LteUeRrcProtocolReal > friend
allow LteRlcSpecificLteRlcSapUser<LteUeRrcProtocolReal> class friend access
Definition at line 1 of file lte-rrc-protocol-real.h.
Referenced by LteUeRrcProtocolReal().
MemberLteUeRrcSapUser< LteUeRrcProtocolReal >
friend class MemberLteUeRrcSapUser< LteUeRrcProtocolReal > friend
allow MemberLteUeRrcSapUser<LteUeRrcProtocolReal> class friend access
Definition at line 1 of file lte-rrc-protocol-real.h.
Referenced by LteUeRrcProtocolReal().
Member Data Documentation
m_completeSetupParameters
LteUeRrcSapProvider::CompleteSetupParameters ns3::LteUeRrcProtocolReal::m_completeSetupParameters private
complete setup parameters
Definition at line 172 of file lte-rrc-protocol-real.h.
Referenced by LteUeRrcProtocolReal(), DoDispose(), and DoSetup().
m_enbRrcSapProvider
LteEnbRrcSapProvider* ns3::LteUeRrcProtocolReal::m_enbRrcSapProvider private
ENB RRC SAP provider.
Definition at line 169 of file lte-rrc-protocol-real.h.
Referenced by DoSendIdealUeContextRemoveRequest(), and SetEnbRrcSapProvider().
m_rnti
uint16_t ns3::LteUeRrcProtocolReal::m_rnti private
the RNTI
Definition at line 166 of file lte-rrc-protocol-real.h.
Referenced by DoSendIdealUeContextRemoveRequest(), DoSendMeasurementReport(), DoSendRrcConnectionReconfigurationCompleted(), DoSendRrcConnectionReestablishmentComplete(), DoSendRrcConnectionReestablishmentRequest(), DoSendRrcConnectionRequest(), DoSendRrcConnectionSetupCompleted(), and SetEnbRrcSapProvider().
m_rrc
Ptr<LteUeRrc> ns3::LteUeRrcProtocolReal::m_rrc private
the RRC
Definition at line 165 of file lte-rrc-protocol-real.h.
Referenced by DoDispose(), DoSendIdealUeContextRemoveRequest(), DoSendMeasurementReport(), DoSendRrcConnectionReconfigurationCompleted(), DoSendRrcConnectionRequest(), SetEnbRrcSapProvider(), and SetUeRrc().
m_setupParameters
LteUeRrcSapUser::SetupParameters ns3::LteUeRrcProtocolReal::m_setupParameters private
setup parameters
Definition at line 171 of file lte-rrc-protocol-real.h.
Referenced by DoSendMeasurementReport(), DoSendRrcConnectionReconfigurationCompleted(), DoSendRrcConnectionReestablishmentComplete(), DoSendRrcConnectionReestablishmentRequest(), DoSendRrcConnectionRequest(), DoSendRrcConnectionSetupCompleted(), and DoSetup().
m_ueRrcSapProvider
LteUeRrcSapProvider* ns3::LteUeRrcProtocolReal::m_ueRrcSapProvider private
UE RRC SAP provider.
Definition at line 167 of file lte-rrc-protocol-real.h.
Referenced by DoReceivePdcpPdu(), DoReceivePdcpSdu(), DoSetup(), SetEnbRrcSapProvider(), and SetLteUeRrcSapProvider().
m_ueRrcSapUser
LteUeRrcSapUser* ns3::LteUeRrcProtocolReal::m_ueRrcSapUser private
UE RRC SAP user.
Definition at line 168 of file lte-rrc-protocol-real.h.
Referenced by LteUeRrcProtocolReal(), DoDispose(), and GetLteUeRrcSapUser().
The documentation for this class was generated from the following files:
src/lte/model/lte-rrc-protocol-real.h
src/lte/model/lte-rrc-protocol-real.cc