ns-3: ns3::LteFfConverter Class Reference
ns3::LteFfConverter Class Reference
LteFfConverter class.
#include "lte-common.h"
Static Public Member Functions
static uint16_t double2fpS11dot3 (double val)
Convert from double to fixed point S11.3 notation.
static double fpS11dot3toDouble (uint16_t val)
Convert from fixed point S11.3 notation to double.
static double getMinFpS11dot3Value ()
Get minimum fixed point S11.3 value.
Detailed Description
LteFfConverter class.
Definition at line 119 of file lte-common.h.
Member Function Documentation
double2fpS11dot3()
uint16_t ns3::LteFfConverter::double2fpS11dot3 (double val) static
Convert from double to fixed point S11.3 notation.
Parameters
val double value
Returns
fixed point S11.3 value
Definition at line 138 of file lte-common.cc.
Referenced by ns3::LteEnbPhy::CreatePuschCqiReport(), and ns3::LteEnbPhy::CreateSrsCqiReport().
fpS11dot3toDouble()
double ns3::LteFfConverter::fpS11dot3toDouble (uint16_t val) static
Convert from fixed point S11.3 notation to double.
Parameters
val fixed point S11.3 value
Returns
double value
Definition at line 155 of file lte-common.cc.
Referenced by ns3::LteFfrEnhancedAlgorithm::DoReportUlCqiInfo(), ns3::CqaFfMacScheduler::DoSchedUlCqiInfoReq(), ns3::FdBetFfMacScheduler::DoSchedUlCqiInfoReq(), ns3::FdMtFfMacScheduler::DoSchedUlCqiInfoReq(), ns3::FdTbfqFfMacScheduler::DoSchedUlCqiInfoReq(), ns3::PfFfMacScheduler::DoSchedUlCqiInfoReq(), ns3::PssFfMacScheduler::DoSchedUlCqiInfoReq(), ns3::RrFfMacScheduler::DoSchedUlCqiInfoReq(), ns3::TdBetFfMacScheduler::DoSchedUlCqiInfoReq(), ns3::TdMtFfMacScheduler::DoSchedUlCqiInfoReq(), ns3::TdTbfqFfMacScheduler::DoSchedUlCqiInfoReq(), and ns3::TtaFfMacScheduler::DoSchedUlCqiInfoReq().
getMinFpS11dot3Value()
double ns3::LteFfConverter::getMinFpS11dot3Value () static
Get minimum fixed point S11.3 value.
Returns
double value for the minimum fixed point S11.3 value
Definition at line 163 of file lte-common.cc.
The documentation for this class was generated from the following files:
src/lte/model/lte-common.h
src/lte/model/lte-common.cc