ns-3: ns3::Ipv4GlobalRouting Class Reference
ns3::Ipv4GlobalRouting Class Reference
Internet » IPv4 classes and sub-modules
Global routing protocol for IPv4 stacks.
#include "ipv4-global-routing.h"
Public Member Functions
Ipv4GlobalRouting ()
Construct an empty Ipv4GlobalRouting routing protocol,.
virtual ~Ipv4GlobalRouting ()
void AddASExternalRouteTo (Ipv4Address network, Ipv4Mask networkMask, Ipv4Address nextHop, uint32_t interface)
Add an external route to the global routing table.
void AddHostRouteTo (Ipv4Address dest, Ipv4Address nextHop, uint32_t interface)
Add a host route to the global routing table.
void AddHostRouteTo (Ipv4Address dest, uint32_t interface)
Add a host route to the global routing table.
void AddNetworkRouteTo (Ipv4Address network, Ipv4Mask networkMask, Ipv4Address nextHop, uint32_t interface)
Add a network route to the global routing table.
void AddNetworkRouteTo (Ipv4Address network, Ipv4Mask networkMask, uint32_t interface)
Add a network route to the global routing table.
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
uint32_t GetNRoutes (void) const
Get the number of individual unicast routes that have been added to the routing table.
Ipv4RoutingTableEntry * GetRoute (uint32_t i) const
Get a route from the global unicast routing table.
virtual void NotifyAddAddress (uint32_t interface, Ipv4InterfaceAddress address)
virtual void NotifyInterfaceDown (uint32_t interface)
virtual void NotifyInterfaceUp (uint32_t interface)
virtual void NotifyRemoveAddress (uint32_t interface, Ipv4InterfaceAddress address)
virtual void PrintRoutingTable (Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S) const
Print the Routing Table entries.
void RemoveRoute (uint32_t i)
Remove a route from the global unicast routing table.
virtual bool RouteInput (Ptr< const Packet > p, const Ipv4Header &header, Ptr< const NetDevice > idev, UnicastForwardCallback ucb, MulticastForwardCallback mcb, LocalDeliverCallback lcb, ErrorCallback ecb)
Route an input packet (to be forwarded or locally delivered)
virtual Ptr< Ipv4Route > RouteOutput (Ptr< Packet > p, const Ipv4Header &header, Ptr< NetDevice > oif, Socket::SocketErrno &sockerr)
Query routing cache for an existing route, for an outbound packet.
virtual void SetIpv4 (Ptr< Ipv4 > ipv4)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Ipv4RoutingProtocol
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
typedef std::list< Ipv4RoutingTableEntry * > ASExternalRoutes
container of Ipv4RoutingTableEntry (routes to external AS)
typedef std::list< Ipv4RoutingTableEntry * >::const_iterator ASExternalRoutesCI
const iterator of container of Ipv4RoutingTableEntry (routes to external AS)
typedef std::list< Ipv4RoutingTableEntry * >::iterator ASExternalRoutesI
iterator of container of Ipv4RoutingTableEntry (routes to external AS)
typedef std::list< Ipv4RoutingTableEntry * > HostRoutes
container of Ipv4RoutingTableEntry (routes to hosts)
typedef std::list< Ipv4RoutingTableEntry * >::const_iterator HostRoutesCI
const iterator of container of Ipv4RoutingTableEntry (routes to hosts)
typedef std::list< Ipv4RoutingTableEntry * >::iterator HostRoutesI
iterator of container of Ipv4RoutingTableEntry (routes to hosts)
typedef std::list< Ipv4RoutingTableEntry * > NetworkRoutes
container of Ipv4RoutingTableEntry (routes to networks)
typedef std::list< Ipv4RoutingTableEntry * >::const_iterator NetworkRoutesCI
const iterator of container of Ipv4RoutingTableEntry (routes to networks)
typedef std::list< Ipv4RoutingTableEntry * >::iterator NetworkRoutesI
iterator of container of Ipv4RoutingTableEntry (routes to networks)
Private Member Functions
Ptr< Ipv4Route > LookupGlobal (Ipv4Address dest, Ptr< NetDevice > oif=0)
Lookup in the forwarding table for destination.
Private Attributes
ASExternalRoutes m_ASexternalRoutes
External routes imported.
HostRoutes m_hostRoutes
Routes to hosts.
Ptr< Ipv4 > m_ipv4
associated IPv4 instance
NetworkRoutes m_networkRoutes
Routes to networks.
Ptr< UniformRandomVariable > m_rand
A uniform random number generator for randomly routing packets among ECMP.
bool m_randomEcmpRouting
Set to true if packets are randomly routed among ECMP; set to false for using only one route consistently.
bool m_respondToInterfaceEvents
Set to true if this interface should respond to interface events by globallly recomputing routes.
Additional Inherited Members
Public Types inherited from ns3::Ipv4RoutingProtocol
typedef Callback< void, Ptr< const Packet >, const Ipv4Header &, Socket::SocketErrno > ErrorCallback
Callback for routing errors (e.g., no route found)
typedef Callback< void, Ptr< const Packet >, const Ipv4Header &, uint32_t > LocalDeliverCallback
Callback for packets to be locally delivered.
typedef Callback< void, Ptr< Ipv4MulticastRoute >, Ptr< const Packet >, const Ipv4Header & > MulticastForwardCallback
Callback for multicast packets to be forwarded.
typedef Callback< void, Ptr< Ipv4Route >, Ptr< const Packet >, const Ipv4Header & > UnicastForwardCallback
Callback for unicast packets to be forwarded.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Global routing protocol for IPv4 stacks.
Introspection did not find any typical Config paths.
In ns-3 we have the concept of a pluggable routing protocol. Routing protocols are added to a list maintained by the Ipv4L3Protocol. Every stack gets one routing protocol for free – the Ipv4StaticRouting routing protocol is added in the constructor of the Ipv4L3Protocol (this is the piece of code that implements the functionality of the IP layer).
As an option to running a dynamic routing protocol, a GlobalRouteManager object has been created to allow users to build routes for all participating nodes. One can think of this object as a "routing oracle"; it has an omniscient view of the topology, and can construct shortest path routes between all pairs of nodes. These routes must be stored somewhere in the node, so therefore this class Ipv4GlobalRouting is used as one of the pluggable routing protocols. It is kept distinct from Ipv4StaticRouting because these routes may be dynamically cleared and rebuilt in the middle of the simulation, while manually entered routes into the Ipv4StaticRouting may need to be kept distinct.
This class deals with Ipv4 unicast routes only.
See also
Ipv4RoutingProtocol
GlobalRouteManager
Attributes
RandomEcmpRouting: Set to true if packets are randomly routed among ECMP; set to false for using only one route consistently
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
RespondToInterfaceEvents: Set to true if you want to dynamically recompute the global routes upon Interface notification events (up/down, or add/remove address)
Set with class: BooleanValue
Underlying type: bool
Initial value: false
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 120 bytes (on a 64-bit architecture).
Definition at line 71 of file ipv4-global-routing.h.
Member Typedef Documentation
ASExternalRoutes
typedef std::list<Ipv4RoutingTableEntry *> ns3::Ipv4GlobalRouting::ASExternalRoutes private
container of Ipv4RoutingTableEntry (routes to external AS)
Definition at line 257 of file ipv4-global-routing.h.
ASExternalRoutesCI
typedef std::list<Ipv4RoutingTableEntry *>::const_iterator ns3::Ipv4GlobalRouting::ASExternalRoutesCI private
const iterator of container of Ipv4RoutingTableEntry (routes to external AS)
Definition at line 259 of file ipv4-global-routing.h.
ASExternalRoutesI
typedef std::list<Ipv4RoutingTableEntry *>::iterator ns3::Ipv4GlobalRouting::ASExternalRoutesI private
iterator of container of Ipv4RoutingTableEntry (routes to external AS)
Definition at line 261 of file ipv4-global-routing.h.
HostRoutes
typedef std::list<Ipv4RoutingTableEntry *> ns3::Ipv4GlobalRouting::HostRoutes private
container of Ipv4RoutingTableEntry (routes to hosts)
Definition at line 243 of file ipv4-global-routing.h.
HostRoutesCI
typedef std::list<Ipv4RoutingTableEntry *>::const_iterator ns3::Ipv4GlobalRouting::HostRoutesCI private
const iterator of container of Ipv4RoutingTableEntry (routes to hosts)
Definition at line 245 of file ipv4-global-routing.h.
HostRoutesI
typedef std::list<Ipv4RoutingTableEntry *>::iterator ns3::Ipv4GlobalRouting::HostRoutesI private
iterator of container of Ipv4RoutingTableEntry (routes to hosts)
Definition at line 247 of file ipv4-global-routing.h.
NetworkRoutes
typedef std::list<Ipv4RoutingTableEntry *> ns3::Ipv4GlobalRouting::NetworkRoutes private
container of Ipv4RoutingTableEntry (routes to networks)
Definition at line 250 of file ipv4-global-routing.h.
NetworkRoutesCI
typedef std::list<Ipv4RoutingTableEntry *>::const_iterator ns3::Ipv4GlobalRouting::NetworkRoutesCI private
const iterator of container of Ipv4RoutingTableEntry (routes to networks)
Definition at line 252 of file ipv4-global-routing.h.
NetworkRoutesI
typedef std::list<Ipv4RoutingTableEntry *>::iterator ns3::Ipv4GlobalRouting::NetworkRoutesI private
iterator of container of Ipv4RoutingTableEntry (routes to networks)
Definition at line 254 of file ipv4-global-routing.h.
Constructor & Destructor Documentation
Ipv4GlobalRouting()
ns3::Ipv4GlobalRouting::Ipv4GlobalRouting ()
Construct an empty Ipv4GlobalRouting routing protocol,.
The Ipv4GlobalRouting class supports host and network unicast routes. This method initializes the lists containing these routes to empty.
See also
Ipv4GlobalRouting
Definition at line 60 of file ipv4-global-routing.cc.
References m_rand, and NS_LOG_FUNCTION.
~Ipv4GlobalRouting()
ns3::Ipv4GlobalRouting::~Ipv4GlobalRouting () virtual
Definition at line 69 of file ipv4-global-routing.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddASExternalRouteTo()
void ns3::Ipv4GlobalRouting::AddASExternalRouteTo (Ipv4Address network, Ipv4Mask networkMask, Ipv4Address nextHop, uint32_t interface)
Add an external route to the global routing table.
Parameters
network The Ipv4Address network for this route.
networkMask The Ipv4Mask to extract the network.
nextHop The next hop Ipv4Address
interface The network interface index used to send packets to the destination.
Definition at line 124 of file ipv4-global-routing.cc.
References ns3::Ipv4RoutingTableEntry::CreateNetworkRouteTo(), m_ASexternalRoutes, and NS_LOG_FUNCTION.
AddHostRouteTo() [1/2]
void ns3::Ipv4GlobalRouting::AddHostRouteTo (Ipv4Address dest, Ipv4Address nextHop, uint32_t interface)
Add a host route to the global routing table.
Parameters
dest The Ipv4Address destination for this route.
nextHop The Ipv4Address of the next hop in the route.
interface The network interface index used to send packets to the destination.
See also
Ipv4Address
Definition at line 75 of file ipv4-global-routing.cc.
References ns3::Ipv4RoutingTableEntry::CreateHostRouteTo(), m_hostRoutes, and NS_LOG_FUNCTION.
AddHostRouteTo() [2/2]
void ns3::Ipv4GlobalRouting::AddHostRouteTo (Ipv4Address dest, uint32_t interface)
Add a host route to the global routing table.
Parameters
dest The Ipv4Address destination for this route.
interface The network interface index used to send packets to the destination.
See also
Ipv4Address
Definition at line 86 of file ipv4-global-routing.cc.
References ns3::Ipv4RoutingTableEntry::CreateHostRouteTo(), m_hostRoutes, and NS_LOG_FUNCTION.
AddNetworkRouteTo() [1/2]
void ns3::Ipv4GlobalRouting::AddNetworkRouteTo (Ipv4Address network, Ipv4Mask networkMask, Ipv4Address nextHop, uint32_t interface)
Add a network route to the global routing table.
Parameters
network The Ipv4Address network for this route.
networkMask The Ipv4Mask to extract the network.
nextHop The next hop in the route to the destination network.
interface The network interface index used to send packets to the destination.
See also
Ipv4Address
Definition at line 96 of file ipv4-global-routing.cc.
References ns3::Ipv4RoutingTableEntry::CreateNetworkRouteTo(), m_networkRoutes, and NS_LOG_FUNCTION.
AddNetworkRouteTo() [2/2]
void ns3::Ipv4GlobalRouting::AddNetworkRouteTo (Ipv4Address network, Ipv4Mask networkMask, uint32_t interface)
Add a network route to the global routing table.
Parameters
network The Ipv4Address network for this route.
networkMask The Ipv4Mask to extract the network.
interface The network interface index used to send packets to the destination.
See also
Ipv4Address
Definition at line 111 of file ipv4-global-routing.cc.
References ns3::Ipv4RoutingTableEntry::CreateNetworkRouteTo(), m_networkRoutes, and NS_LOG_FUNCTION.
AssignStreams()
int64_t ns3::Ipv4GlobalRouting::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 366 of file ipv4-global-routing.cc.
References m_rand, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
DoDispose()
void ns3::Ipv4GlobalRouting::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 374 of file ipv4-global-routing.cc.
References ns3::Object::DoDispose(), m_ASexternalRoutes, m_hostRoutes, m_networkRoutes, and NS_LOG_FUNCTION.
GetNRoutes()
uint32_t ns3::Ipv4GlobalRouting::GetNRoutes (void) const
Get the number of individual unicast routes that have been added to the routing table.
Warning
The default route counts as one of the routes.
Returns
the number of routes
Definition at line 249 of file ipv4-global-routing.cc.
References m_ASexternalRoutes, m_hostRoutes, m_networkRoutes, sample-rng-plot::n, and NS_LOG_FUNCTION.
Referenced by PrintRoutingTable().
GetRoute()
Ipv4RoutingTableEntry * ns3::Ipv4GlobalRouting::GetRoute (uint32_t i) const
Get a route from the global unicast routing table.
Externally, the unicast global routing table appears simply as a table with n entries. The one subtlety of note is that if a default route has been set it will appear as the zeroth entry in the table. This means that if you add only a default route, the table will have one entry that can be accessed either by explicitly calling GetDefaultRoute () or by calling GetRoute (0).
Similarly, if the default route has been set, calling RemoveRoute (0) will remove the default route.
Parameters
i The index (into the routing table) of the route to retrieve. If the default route has been set, it will occupy index zero.
Returns
If route is set, a pointer to that Ipv4RoutingTableEntry is returned, otherwise a zero pointer is returned.
See also
Ipv4RoutingTableEntry
Ipv4GlobalRouting::RemoveRoute
Definition at line 260 of file ipv4-global-routing.cc.
References m_ASexternalRoutes, m_hostRoutes, m_networkRoutes, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by PrintRoutingTable().
GetTypeId()
TypeId ns3::Ipv4GlobalRouting::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 41 of file ipv4-global-routing.cc.
References m_randomEcmpRouting, m_respondToInterfaceEvents, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), and ns3::TypeId::SetParent().
LookupGlobal()
Ptr< Ipv4Route > ns3::Ipv4GlobalRouting::LookupGlobal (Ipv4Address dest, Ptr< NetDevice > oif = 0) private
Lookup in the forwarding table for destination.
Parameters
dest destination address
oif output interface if any (put 0 otherwise)
Returns
Ipv4Route to route the packet to reach dest address
Todo:
handle multi-address case
Definition at line 140 of file ipv4-global-routing.cc.
References ns3::Ipv4RoutingTableEntry::GetDest(), ns3::Ipv4RoutingTableEntry::GetGateway(), ns3::UniformRandomVariable::GetInteger(), ns3::Ipv4RoutingTableEntry::GetInterface(), ns3::Ipv4Mask::IsMatch(), m_ASexternalRoutes, m_hostRoutes, m_ipv4, m_networkRoutes, m_rand, m_randomEcmpRouting, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC, ns3::Ipv4Route::SetDestination(), ns3::Ipv4Route::SetGateway(), ns3::Ipv4Route::SetOutputDevice(), and ns3::Ipv4Route::SetSource().
Referenced by RouteInput(), and RouteOutput().
NotifyAddAddress()
void ns3::Ipv4GlobalRouting::NotifyAddAddress (uint32_t interface, Ipv4InterfaceAddress address) virtual
Parameters
interface the index of the interface we are being notified about
address a new address being added to an interface
Protocols are expected to implement this method to be notified whenever a new address is added to an interface. Typically used to add a 'network route' on an interface. Can be invoked on an up or down interface.
Implements ns3::Ipv4RoutingProtocol.
Definition at line 559 of file ipv4-global-routing.cc.
References first::address, ns3::GlobalRouteManager::BuildGlobalRoutingDatabase(), ns3::GlobalRouteManager::DeleteGlobalRoutes(), ns3::GlobalRouteManager::InitializeRoutes(), m_respondToInterfaceEvents, ns3::Simulator::Now(), and NS_LOG_FUNCTION.
NotifyInterfaceDown()
void ns3::Ipv4GlobalRouting::NotifyInterfaceDown (uint32_t interface) virtual
Parameters
interface the index of the interface we are being notified about
Protocols are expected to implement this method to be notified of the state change of an interface in a node.
Implements ns3::Ipv4RoutingProtocol.
Definition at line 547 of file ipv4-global-routing.cc.
References ns3::GlobalRouteManager::BuildGlobalRoutingDatabase(), ns3::GlobalRouteManager::DeleteGlobalRoutes(), ns3::GlobalRouteManager::InitializeRoutes(), m_respondToInterfaceEvents, ns3::Simulator::Now(), and NS_LOG_FUNCTION.
NotifyInterfaceUp()
void ns3::Ipv4GlobalRouting::NotifyInterfaceUp (uint32_t interface) virtual
Parameters
interface the index of the interface we are being notified about
Protocols are expected to implement this method to be notified of the state change of an interface in a node.
Implements ns3::Ipv4RoutingProtocol.
Definition at line 535 of file ipv4-global-routing.cc.
References ns3::GlobalRouteManager::BuildGlobalRoutingDatabase(), ns3::GlobalRouteManager::DeleteGlobalRoutes(), ns3::GlobalRouteManager::InitializeRoutes(), m_respondToInterfaceEvents, ns3::Simulator::Now(), and NS_LOG_FUNCTION.
NotifyRemoveAddress()
void ns3::Ipv4GlobalRouting::NotifyRemoveAddress (uint32_t interface, Ipv4InterfaceAddress address) virtual
Parameters
interface the index of the interface we are being notified about
address a new address being added to an interface
Protocols are expected to implement this method to be notified whenever a new address is removed from an interface. Typically used to remove the 'network route' of an interface. Can be invoked on an up or down interface.
Implements ns3::Ipv4RoutingProtocol.
Definition at line 571 of file ipv4-global-routing.cc.
References first::address, ns3::GlobalRouteManager::BuildGlobalRoutingDatabase(), ns3::GlobalRouteManager::DeleteGlobalRoutes(), ns3::GlobalRouteManager::InitializeRoutes(), m_respondToInterfaceEvents, ns3::Simulator::Now(), and NS_LOG_FUNCTION.
PrintRoutingTable()
void ns3::Ipv4GlobalRouting::PrintRoutingTable (Ptr< OutputStreamWrapper > stream, Time::Unit unit = Time::S) const virtual
Print the Routing Table entries.
Parameters
stream The ostream the Routing table is printed to
unit The time unit to be used in the report
Implements ns3::Ipv4RoutingProtocol.
Definition at line 401 of file ipv4-global-routing.cc.
References ns3::Time::As(), ns3::Names::FindName(), ns3::Ipv4RoutingTableEntry::GetDest(), ns3::Ipv4RoutingTableEntry::GetDestNetworkMask(), ns3::Ipv4RoutingTableEntry::GetGateway(), ns3::Ipv4RoutingTableEntry::GetInterface(), GetNRoutes(), GetRoute(), ns3::OutputStreamWrapper::GetStream(), ns3::Ipv4RoutingTableEntry::IsGateway(), ns3::Ipv4RoutingTableEntry::IsHost(), m_ipv4, ns3::Now(), and NS_LOG_FUNCTION.
RemoveRoute()
void ns3::Ipv4GlobalRouting::RemoveRoute (uint32_t i)
Remove a route from the global unicast routing table.
Externally, the unicast global routing table appears simply as a table with n entries. The one subtlety of note is that if a default route has been set it will appear as the zeroth entry in the table. This means that if the default route has been set, calling RemoveRoute (0) will remove the default route.
Parameters
i The index (into the routing table) of the route to remove. If the default route has been set, it will occupy index zero.
See also
Ipv4RoutingTableEntry
Ipv4GlobalRouting::GetRoute
Ipv4GlobalRouting::AddRoute
Definition at line 309 of file ipv4-global-routing.cc.
References m_ASexternalRoutes, m_hostRoutes, m_networkRoutes, NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
RouteInput()
bool ns3::Ipv4GlobalRouting::RouteInput (Ptr< const Packet > p, const Ipv4Header & header, Ptr< const NetDevice > idev, UnicastForwardCallback ucb, MulticastForwardCallback mcb, LocalDeliverCallback lcb, ErrorCallback ecb) virtual
Route an input packet (to be forwarded or locally delivered)
This lookup is used in the forwarding process. The packet is handed over to the Ipv4RoutingProtocol, and will get forwarded onward by one of the callbacks. The Linux equivalent is ip_route_input(). There are four valid outcomes, and a matching callbacks to handle each.
Parameters
p received packet
header input parameter used to form a search key for a route
idev Pointer to ingress network device
ucb Callback for the case in which the packet is to be forwarded as unicast
mcb Callback for the case in which the packet is to be forwarded as multicast
lcb Callback for the case in which the packet is to be locally delivered
ecb Callback to call if there is an error in forwarding
Returns
true if the Ipv4RoutingProtocol takes responsibility for forwarding or delivering the packet, false otherwise
Implements ns3::Ipv4RoutingProtocol.
Definition at line 484 of file ipv4-global-routing.cc.
References ns3::Socket::ERROR_NOROUTETOHOST, ns3::Ipv4Header::GetDestination(), ns3::Ipv4Header::GetSource(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), LookupGlobal(), m_ipv4, NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_LOGIC.
RouteOutput()
Ptr< Ipv4Route > ns3::Ipv4GlobalRouting::RouteOutput (Ptr< Packet > p, const Ipv4Header & header, Ptr< NetDevice > oif, Socket::SocketErrno & sockerr) virtual
Query routing cache for an existing route, for an outbound packet.
This lookup is used by transport protocols. It does not cause any packet to be forwarded, and is synchronous. Can be used for multicast or unicast. The Linux equivalent is ip_route_output()
The header input parameter may have an uninitialized value for the source address, but the destination address should always be properly set by the caller.
Parameters
p packet to be routed. Note that this method may modify the packet. Callers may also pass in a null pointer.
header input parameter (used to form key to search for the route)
oif Output interface Netdevice. May be zero, or may be bound via socket options to a particular output interface.
sockerr Output parameter; socket errno
Returns
a code that indicates what happened in the lookup
Implements ns3::Ipv4RoutingProtocol.
Definition at line 455 of file ipv4-global-routing.cc.
References ns3::Socket::ERROR_NOROUTETOHOST, ns3::Socket::ERROR_NOTERROR, ns3::Ipv4Header::GetDestination(), ns3::Ipv4Address::IsMulticast(), LookupGlobal(), NS_LOG_FUNCTION, and NS_LOG_LOGIC.
SetIpv4()
void ns3::Ipv4GlobalRouting::SetIpv4 (Ptr< Ipv4 > ipv4) virtual
Parameters
ipv4 the ipv4 object this routing protocol is being associated with
Typically, invoked directly or indirectly from ns3::Ipv4::SetRoutingProtocol
Implements ns3::Ipv4RoutingProtocol.
Definition at line 583 of file ipv4-global-routing.cc.
References m_ipv4, NS_ASSERT, and NS_LOG_FUNCTION.
Member Data Documentation
m_ASexternalRoutes
ASExternalRoutes ns3::Ipv4GlobalRouting::m_ASexternalRoutes private
External routes imported.
Definition at line 273 of file ipv4-global-routing.h.
Referenced by AddASExternalRouteTo(), DoDispose(), GetNRoutes(), GetRoute(), LookupGlobal(), and RemoveRoute().
m_hostRoutes
HostRoutes ns3::Ipv4GlobalRouting::m_hostRoutes private
Routes to hosts.
Definition at line 271 of file ipv4-global-routing.h.
Referenced by AddHostRouteTo(), DoDispose(), GetNRoutes(), GetRoute(), LookupGlobal(), and RemoveRoute().
m_ipv4
Ptr<Ipv4> ns3::Ipv4GlobalRouting::m_ipv4 private
associated IPv4 instance
Definition at line 275 of file ipv4-global-routing.h.
Referenced by LookupGlobal(), PrintRoutingTable(), RouteInput(), and SetIpv4().
m_networkRoutes
NetworkRoutes ns3::Ipv4GlobalRouting::m_networkRoutes private
Routes to networks.
Definition at line 272 of file ipv4-global-routing.h.
Referenced by AddNetworkRouteTo(), DoDispose(), GetNRoutes(), GetRoute(), LookupGlobal(), and RemoveRoute().
m_rand
Ptr<UniformRandomVariable> ns3::Ipv4GlobalRouting::m_rand private
A uniform random number generator for randomly routing packets among ECMP.
Definition at line 240 of file ipv4-global-routing.h.
Referenced by Ipv4GlobalRouting(), AssignStreams(), and LookupGlobal().
m_randomEcmpRouting
bool ns3::Ipv4GlobalRouting::m_randomEcmpRouting private
Set to true if packets are randomly routed among ECMP; set to false for using only one route consistently.
Definition at line 236 of file ipv4-global-routing.h.
Referenced by GetTypeId(), and LookupGlobal().
m_respondToInterfaceEvents
bool ns3::Ipv4GlobalRouting::m_respondToInterfaceEvents private
Set to true if this interface should respond to interface events by globallly recomputing routes.
Definition at line 238 of file ipv4-global-routing.h.
Referenced by GetTypeId(), NotifyAddAddress(), NotifyInterfaceDown(), NotifyInterfaceUp(), and NotifyRemoveAddress().
The documentation for this class was generated from the following files:
src/internet/model/ipv4-global-routing.h
src/internet/model/ipv4-global-routing.cc