ns-3: ns3::TcpHtcp Class Reference
ns3::TcpHtcp Class Reference
Internet » TCP » Congestion Control Algorithms.
An implementation of the H-TCP variant of TCP.
#include "tcp-htcp.h"
Public Member Functions
TcpHtcp (const TcpHtcp &sock)
Copy constructor.
TcpHtcp (void)
Create an unbound tcp socket.
virtual ~TcpHtcp (void)
virtual Ptr< TcpCongestionOps > Fork ()
Copy the congestion control algorithm across sockets.
virtual std::string GetName () const
Get the name of the congestion control algorithm.
virtual uint32_t GetSsThresh (Ptr< const TcpSocketState > tcb, uint32_t bytesInFlight)
Get the slow start threshold after a loss event.
virtual void PktsAcked (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked, const Time &rtt)
Timing information on received ACK.
Public Member Functions inherited from ns3::TcpNewReno
TcpNewReno ()
TcpNewReno (const TcpNewReno &sock)
Copy constructor.
~TcpNewReno ()
virtual void IncreaseWindow (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
Try to increase the cWnd following the NewReno specification.
Public Member Functions inherited from ns3::TcpCongestionOps
TcpCongestionOps ()
TcpCongestionOps (const TcpCongestionOps &other)
Copy constructor.
virtual ~TcpCongestionOps ()
virtual void CongControl (Ptr< TcpSocketState > tcb, const TcpRateOps::TcpRateConnection &rc, const TcpRateOps::TcpRateSample &rs)
Called when packets are delivered to update cwnd and pacing rate.
virtual void CongestionStateSet (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCongState_t newState)
Trigger events/calculations specific to a congestion state.
virtual void CwndEvent (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCAEvent_t event)
Trigger events/calculations on occurrence of congestion window event.
virtual bool HasCongControl () const
Returns true when Congestion Control Algorithm implements CongControl.
virtual void Init (Ptr< TcpSocketState > tcb)
Set configuration required by congestion control algorithm.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpNewReno
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpCongestionOps
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void CongestionAvoidance (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
NewReno congestion avoidance.
Protected Member Functions inherited from ns3::TcpNewReno
virtual uint32_t SlowStart (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
Tcp NewReno slow start algorithm.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void UpdateAlpha (void)
Updates the additive increase parameter for H-TCP.
void UpdateBeta (void)
Updates the multiplicative decrease factor beta for H-TCP.
Private Attributes
double m_alpha
AIMD additive increase parameter.
double m_beta
AIMD multiplicative decrease factor.
uint32_t m_dataSent
Current amount of data sent since last congestion.
double m_defaultBackoff
default value when throughput ratio less than default
Time m_delta
Time in second that has elapsed since the.
Time m_deltaL
Threshold for switching between standard and new increase function.
Time m_lastCon
Time of the last congestion for the flow.
uint32_t m_lastThroughput
Throughput in last congestion period.
Time m_maxRtt
Maximum RTT in each congestion period.
Time m_minRtt
Minimum RTT in each congestion period.
uint32_t m_throughput
Current throughput since last congestion.
double m_throughputRatio
ratio of two consequence throughput
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
An implementation of the H-TCP variant of TCP.
This class contains the H-TCP implementation of TCP, according to Internet-Draft draft-leith-tcp-htcp-03 and its related paper, "H-TCP: TCP for high-speed and long-distance networks" H-TCP is a congestion control protocol suitable for high bandwidth-delay product networks. It is fair to similar flows present in the network and also friendly with conventional TCP. It also makes use of free bandwidth when it is available.
Config Paths
ns3::TcpHtcp is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/$ns3::TcpL4Protocol/SocketList/[i]/CongestionOps/$ns3::TcpNewReno/$ns3::TcpHtcp"
"/NodeList/[i]/$ns3::TcpL4Protocol/SocketList/[i]/CongestionOps/$ns3::TcpHtcp"
Attributes
DefaultBackoff: The default AIMD backoff factor
Set with class: ns3::DoubleValue
Underlying type: double 0:1
Initial value: 0.5
Flags: construct write read
ThroughputRatio: Threshold value for updating beta
Set with class: ns3::DoubleValue
Underlying type: double -1.79769e+308:1.79769e+308
Initial value: 0.2
Flags: construct write read
DeltaL: Delta_L parameter in increase function
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +1e+09ns
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 120 bytes (on a 64-bit architecture).
Definition at line 49 of file tcp-htcp.h.
Constructor & Destructor Documentation
TcpHtcp() [1/2]
ns3::TcpHtcp::TcpHtcp (void)
Create an unbound tcp socket.
Definition at line 67 of file tcp-htcp.cc.
References NS_LOG_FUNCTION.
TcpHtcp() [2/2]
ns3::TcpHtcp::TcpHtcp (const TcpHtcp & sock)
Copy constructor.
Parameters
sock the object to copy
Definition at line 82 of file tcp-htcp.cc.
References NS_LOG_FUNCTION.
~TcpHtcp()
ns3::TcpHtcp::~TcpHtcp (void) virtual
Definition at line 100 of file tcp-htcp.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CongestionAvoidance()
void ns3::TcpHtcp::CongestionAvoidance (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked) protected virtual
NewReno congestion avoidance.
During congestion avoidance, cwnd is incremented by roughly 1 full-sized segment per round-trip time (RTT).
Parameters
tcb internal congestion state
segmentsAcked count of segments acked
Reimplemented from ns3::TcpNewReno.
Definition at line 111 of file tcp-htcp.cc.
References m_alpha, ns3::TcpSocketState::m_cWnd, ns3::TcpSocketState::m_segmentSize, ns3::TcpSocketState::m_ssThresh, max, NS_LOG_FUNCTION, and NS_LOG_INFO.
Fork()
Ptr< TcpCongestionOps > ns3::TcpHtcp::Fork () virtual
Copy the congestion control algorithm across sockets.
Returns
a pointer of the copied object
Reimplemented from ns3::TcpNewReno.
Definition at line 105 of file tcp-htcp.cc.
References NS_LOG_FUNCTION.
GetName()
std::string ns3::TcpHtcp::GetName () const virtual
Get the name of the congestion control algorithm.
Returns
A string identifying the name
Reimplemented from ns3::TcpNewReno.
Definition at line 62 of file tcp-htcp.cc.
GetSsThresh()
uint32_t ns3::TcpHtcp::GetSsThresh (Ptr< const TcpSocketState > tcb, uint32_t bytesInFlight) virtual
Get the slow start threshold after a loss event.
Is guaranteed that the congestion control state (TcpAckState_t) is changed BEFORE the invocation of this method. The implementator should return the slow start threshold (and not change it directly) because, in the future, the TCP implementation may require to instantly recover from a loss event (e.g. when there is a network with an high reordering factor).
Parameters
tcb internal congestion state
bytesInFlight total bytes in flight
Returns
Slow start threshold
Reimplemented from ns3::TcpNewReno.
Definition at line 169 of file tcp-htcp.cc.
References m_beta, m_dataSent, m_lastCon, m_lastThroughput, m_maxRtt, m_minRtt, m_throughput, ns3::Time::Max(), max, ns3::Time::Min(), ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, UpdateAlpha(), and UpdateBeta().
GetTypeId()
TypeId ns3::TcpHtcp::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 37 of file tcp-htcp.cc.
References m_defaultBackoff, m_deltaL, m_throughputRatio, ns3::MakeDoubleAccessor(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::Seconds(), and ns3::TypeId::SetParent().
PktsAcked()
void ns3::TcpHtcp::PktsAcked (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked, const Time & rtt) virtual
Timing information on received ACK.
The function is called every time an ACK is received (only one time also for cumulative ACKs) and contains timing information. It is optional (congestion controls need not implement it) and the default implementation does nothing.
Parameters
tcb internal congestion state
segmentsAcked count of segments acked
rtt last rtt
Reimplemented from ns3::TcpCongestionOps.
Definition at line 191 of file tcp-htcp.cc.
References ns3::TcpSocketState::CA_OPEN, ns3::Time::GetSeconds(), ns3::TcpSocketState::m_congState, m_dataSent, m_lastCon, m_maxRtt, m_minRtt, ns3::TcpSocketState::m_segmentSize, m_throughput, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and UpdateAlpha().
UpdateAlpha()
void ns3::TcpHtcp::UpdateAlpha (void) private
Updates the additive increase parameter for H-TCP.
Definition at line 126 of file tcp-htcp.cc.
References ns3::Time::GetSeconds(), m_alpha, m_beta, m_delta, m_deltaL, m_lastCon, ns3::Simulator::Now(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by GetSsThresh(), and PktsAcked().
UpdateBeta()
void ns3::TcpHtcp::UpdateBeta (void) private
Updates the multiplicative decrease factor beta for H-TCP.
Definition at line 151 of file tcp-htcp.cc.
References ns3::Time::GetDouble(), m_beta, m_defaultBackoff, m_lastThroughput, m_maxRtt, m_minRtt, m_throughput, m_throughputRatio, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by GetSsThresh().
Member Data Documentation
m_alpha
double ns3::TcpHtcp::m_alpha private
AIMD additive increase parameter.
Definition at line 91 of file tcp-htcp.h.
Referenced by CongestionAvoidance(), and UpdateAlpha().
m_beta
double ns3::TcpHtcp::m_beta private
AIMD multiplicative decrease factor.
Definition at line 92 of file tcp-htcp.h.
Referenced by GetSsThresh(), UpdateAlpha(), and UpdateBeta().
m_dataSent
uint32_t ns3::TcpHtcp::m_dataSent private
Current amount of data sent since last congestion.
Definition at line 103 of file tcp-htcp.h.
Referenced by GetSsThresh(), and PktsAcked().
m_defaultBackoff
double ns3::TcpHtcp::m_defaultBackoff private
default value when throughput ratio less than default
Definition at line 93 of file tcp-htcp.h.
Referenced by GetTypeId(), and UpdateBeta().
m_delta
Time ns3::TcpHtcp::m_delta private
Time in second that has elapsed since the.
Definition at line 95 of file tcp-htcp.h.
Referenced by UpdateAlpha().
m_deltaL
Time ns3::TcpHtcp::m_deltaL private
Threshold for switching between standard and new increase function.
Definition at line 97 of file tcp-htcp.h.
Referenced by GetTypeId(), and UpdateAlpha().
m_lastCon
Time ns3::TcpHtcp::m_lastCon private
Time of the last congestion for the flow.
Definition at line 98 of file tcp-htcp.h.
Referenced by GetSsThresh(), PktsAcked(), and UpdateAlpha().
m_lastThroughput
uint32_t ns3::TcpHtcp::m_lastThroughput private
Throughput in last congestion period.
Definition at line 102 of file tcp-htcp.h.
Referenced by GetSsThresh(), and UpdateBeta().
m_maxRtt
Time ns3::TcpHtcp::m_maxRtt private
Maximum RTT in each congestion period.
Definition at line 100 of file tcp-htcp.h.
Referenced by GetSsThresh(), PktsAcked(), and UpdateBeta().
m_minRtt
Time ns3::TcpHtcp::m_minRtt private
Minimum RTT in each congestion period.
Definition at line 99 of file tcp-htcp.h.
Referenced by GetSsThresh(), PktsAcked(), and UpdateBeta().
m_throughput
uint32_t ns3::TcpHtcp::m_throughput private
Current throughput since last congestion.
Definition at line 101 of file tcp-htcp.h.
Referenced by GetSsThresh(), PktsAcked(), and UpdateBeta().
m_throughputRatio
double ns3::TcpHtcp::m_throughputRatio private
ratio of two consequence throughput
Definition at line 94 of file tcp-htcp.h.
Referenced by GetTypeId(), and UpdateBeta().
The documentation for this class was generated from the following files:
src/internet/model/tcp-htcp.h
src/internet/model/tcp-htcp.cc