ns-3: ns3::PointerValue Class Reference
ns3::PointerValue Class Reference
Pointer Attribute
Hold objects of type Ptr<T>.
#include "pointer.h"
Public Member Functions
PointerValue ()
template<typename T >
PointerValue (const Ptr< T > &object)
Construct this PointerValue by referencing an explicit Object.
PointerValue (Ptr< Object > object)
Construct this PointerValue by referencing an explicit Object.
virtual Ptr< AttributeValue > Copy (void) const
virtual bool DeserializeFromString (std::string value, Ptr< const AttributeChecker > checker)
template<typename T >
Ptr< T > Get (void) const
template<typename T >
bool GetAccessor (Ptr< T > &value) const
Access the Pointer value as type T.
Ptr< Object > GetObject (void) const
Get the Object referenced by the PointerValue.
template<typename T >
operator Ptr< T > () const
Cast to an Object of type T.
virtual std::string SerializeToString (Ptr< const AttributeChecker > checker) const
template<typename T >
void Set (const Ptr< T > &value)
Set the value.
void SetObject (Ptr< Object > object)
Set the value from by reference an Object.
Public Member Functions inherited from ns3::AttributeValue
AttributeValue ()
virtual ~AttributeValue ()
Public Member Functions inherited from ns3::SimpleRefCount< AttributeValue >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
Ptr< Object > m_value
The stored Pointer instance.
Detailed Description
Hold objects of type Ptr<T>.
AttributeValue implementation for Pointer.
See also
AttributeValue
Definition at line 36 of file pointer.h.
Constructor & Destructor Documentation
PointerValue() [1/3]
ns3::PointerValue::PointerValue ()
Definition at line 35 of file pointer.cc.
References NS_LOG_FUNCTION.
PointerValue() [2/3]
ns3::PointerValue::PointerValue (Ptr< Object > object)
Construct this PointerValue by referencing an explicit Object.
Parameters
[in] object The object to begin with.
Definition at line 41 of file pointer.cc.
References NS_LOG_FUNCTION.
PointerValue() [3/3]
template<typename T > ns3::PointerValue::PointerValue (const Ptr< T > & object)
Construct this PointerValue by referencing an explicit Object.
Template Parameters
T [deduced] The type of the object.
Parameters
[in] object The object to begin with.
Definition at line 187 of file pointer.h.
References m_value.
Member Function Documentation
Copy()
Ptr< AttributeValue > ns3::PointerValue::Copy (void) const virtual
Returns
a deep copy of this class, wrapped into an Attribute object.
Implements ns3::AttributeValue.
Definition at line 62 of file pointer.cc.
References NS_LOG_FUNCTION.
DeserializeFromString()
bool ns3::PointerValue::DeserializeFromString (std::string value, Ptr< const AttributeChecker > checker) virtual
Parameters
[in] value A string representation of the value
[in] checker A pointer to the checker associated to the attribute.
Returns
true if the input string was correctly-formatted and could be successfully deserialized, false otherwise.
Upon return of this function, this AttributeValue instance contains the deserialized value. In most cases, this method will not make any use of the checker argument. However, in a very limited set of cases, the checker argument is needed to perform proper serialization. A nice example of code which needs it is the EnumValue::SerializeToString code.
Implements ns3::AttributeValue.
Definition at line 77 of file pointer.cc.
References ns3::ObjectFactory::Create(), m_value, and NS_LOG_FUNCTION.
Get()
template<typename T > Pointer ns3::PointerValue::Get (void) const
Template Parameters
T [explicit] The type to cast to.
Returns
The Pointer value.
Definition at line 201 of file pointer.h.
References m_value, and ns3::PeekPointer().
Referenced by ns3::MeshHelper::AssignStreams(), ns3::WaveHelper::AssignStreams(), ns3::WifiHelper::AssignStreams(), ns3::RandomVariableStreamHelper::AssignStreams(), AssignWifiRandomStreams(), TcFlowControlTestCase::CheckPacketsInDeviceQueue(), TestInterBssConstantObssPdAlgo::CheckPhyState(), TestAmpduReception::CheckPhyState(), ns3::MeshHelper::CreateInterface(), TestDlOfdmaPhyTransmission::DoCheckPhyState(), TestThresholdPreambleDetectionWithoutFrameCapture::DoCheckPhyState(), TestThresholdPreambleDetectionWithFrameCapture::DoCheckPhyState(), TestPhyHeadersReception::DoCheckPhyState(), ns3::AttributeIterator::DoIterate(), ns3::Config::Resolver::DoResolve(), PointerAttributeTestCase::DoRun(), LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun(), WifiAcMappingTest::DoRun(), BlockAckAggregationDisabledTest::DoRun(), PreservePacketsInAmpdus::DoRun(), QosFragmentationTestCase::DoRun(), ns3::WaveHelper::Install(), ns3::WifiHelper::Install(), Experiment::Run(), and Issue40TestCase::RunOne().
GetAccessor()
template<typename T > bool ns3::PointerValue::GetAccessor (Ptr< T > & value) const
Access the Pointer value as type T.
Template Parameters
T [explicit] The type to cast to.
Parameters
[out] value The Pointer value, as type T.
Returns
true.
Definition at line 215 of file pointer.h.
References m_value, and ns3::PeekPointer().
GetObject()
Ptr< Object > ns3::PointerValue::GetObject (void) const
Get the Object referenced by the PointerValue.
Returns
The Object.
Definition at line 55 of file pointer.cc.
References m_value, and NS_LOG_FUNCTION.
Referenced by ns3::cell_tooltip_callback(), ns3::internal::PointerChecker< T >::Check(), LteCqiGenerationDlPowerControlTestCase::DoRun(), LteDownlinkPowerControlTestCase::DoRun(), LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::DoRun(), LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), and LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun().
operator Ptr< T >()
template<typename T > ns3::PointerValue::operator Ptr< T >
Cast to an Object of type T.
Template Parameters
T [explicit] The type to cast to.
Definition at line 208 of file pointer.h.
SerializeToString()
std::string ns3::PointerValue::SerializeToString (Ptr< const AttributeChecker > checker) const virtual
Parameters
[in] checker The checker associated to the attribute
Returns
A string representation of this value.
In most cases, this method will not make any use of the checker argument. However, in a very limited set of cases, the checker argument is needed to perform proper serialization. A nice example of code which needs it is the EnumValue::SerializeToString code.
Implements ns3::AttributeValue.
Definition at line 68 of file pointer.cc.
References m_value, and NS_LOG_FUNCTION.
Set()
template<typename T > void ns3::PointerValue::Set (const Ptr< T > & value)
Set the value.
Parameters
[in] value The value to adopt.
Definition at line 194 of file pointer.h.
References m_value.
SetObject()
void ns3::PointerValue::SetObject (Ptr< Object > object)
Set the value from by reference an Object.
Parameters
[in] object The object to reference.
Definition at line 48 of file pointer.cc.
References m_value, and NS_LOG_FUNCTION.
Member Data Documentation
m_value
Pointer ns3::PointerValue::m_value private
The stored Pointer instance.
Definition at line 93 of file pointer.h.
Referenced by PointerValue(), DeserializeFromString(), Get(), GetAccessor(), GetObject(), SerializeToString(), Set(), and SetObject().
The documentation for this class was generated from the following files:
src/core/model/pointer.h
src/core/model/pointer.cc
doc/introspected-doxygen.h