ns-3: src/core/examples/empirical-random-variable-example.cc File Reference
empirical-random-variable-example.cc File Reference
Core » Core module examples | Core » Random Variables
Example program illustrating use of ns3::EmpiricalRandomVariable.
#include "ns3/simulator.h"
#include "ns3/nstime.h"
#include "ns3/command-line.h"
#include "ns3/random-variable-stream.h"
#include "ns3/histogram.h"
#include "ns3/ptr.h"
#include <iomanip>
#include <iostream>
#include <map>
Functions
void PrintStatsLine (const double value, const long count, const long n)
void PrintSummary (long sum, long n, double weighted, double expected)
void RunBothModes (std::string mode, Ptr< EmpiricalRandomVariable > erv, long n)
void RunSingleSample (std::string mode, Ptr< EmpiricalRandomVariable > erv)
Detailed Description
Example program illustrating use of ns3::EmpiricalRandomVariable.
This example illustrates
Creating an EmpiricalRandomVariable instance.
Switching the mode.
Using the sampling mode
Switching modes
Using the interpolating mode
Consult the ns-3 manual for more information about the use of the random number generator
Definition in file empirical-random-variable-example.cc.
Function Documentation
PrintStatsLine()
void PrintStatsLine (const double value, const long count, const long n)
Definition at line 72 of file empirical-random-variable-example.cc.
References sample-rng-plot::n.
Referenced by RunBothModes().
PrintSummary()
void PrintSummary (long sum, long n, double weighted, double expected)
Definition at line 83 of file empirical-random-variable-example.cc.
References sample-rng-plot::n.
Referenced by RunBothModes().
RunBothModes()
void RunBothModes (std::string mode, Ptr< EmpiricalRandomVariable > erv, long n)
Definition at line 104 of file empirical-random-variable-example.cc.
References ns3::Histogram::AddValue(), ns3::Histogram::GetBinCount(), ns3::Histogram::GetBinStart(), ns3::Histogram::GetBinWidth(), ns3::Histogram::GetNBins(), sample-rng-plot::n, PrintStatsLine(), PrintSummary(), and visualizer.core::start().
RunSingleSample()
void RunSingleSample (std::string mode, Ptr< EmpiricalRandomVariable > erv)
Definition at line 53 of file empirical-random-variable-example.cc.