ns-3: examples/tcp/tcp-linux-reno.cc File Reference
tcp-linux-reno.cc File Reference
#include <iostream>
#include <string>
#include <fstream>
#include <sys/stat.h>
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/point-to-point-module.h"
#include "ns3/applications-module.h"
#include "ns3/traffic-control-module.h"
Functions
void CheckQueueSize (Ptr< QueueDisc > queue)
static void CwndChange (uint32_t oldCwnd, uint32_t newCwnd)
static void DropAtQueue (Ptr< OutputStreamWrapper > stream, Ptr< const QueueDiscItem > item)
void InstallBulkSend (Ptr< Node > node, Ipv4Address address, uint16_t port, std::string socketFactory, uint32_t nodeId, uint32_t cwndWindow, Callback< void, uint32_t, uint32_t > CwndTrace)
void InstallPacketSink (Ptr< Node > node, uint16_t port, std::string socketFactory)
void TraceCwnd (uint32_t node, uint32_t cwndWindow, Callback< void, uint32_t, uint32_t > CwndTrace)
Variables
std::string dir = "results/"
uint32_t segmentSize = 524
Time stopTime = Seconds (60)
Function Documentation
CheckQueueSize()
void CheckQueueSize (Ptr< QueueDisc > queue)
Definition at line 57 of file tcp-linux-reno.cc.
References dir, ns3::QueueDisc::GetCurrentSize(), ns3::Time::GetSeconds(), ns3::QueueSize::GetValue(), ns3::Simulator::Now(), ns3::Simulator::Schedule(), and ns3::Seconds().
CwndChange()
static void CwndChange (uint32_t oldCwnd, uint32_t newCwnd) static
Definition at line 70 of file tcp-linux-reno.cc.
References dir, ns3::Time::GetSeconds(), ns3::Simulator::Now(), and segmentSize.
DropAtQueue()
static void DropAtQueue (Ptr< OutputStreamWrapper > stream, Ptr< const QueueDiscItem > item) static
Definition at line 79 of file tcp-linux-reno.cc.
References ns3::Time::GetSeconds(), ns3::OutputStreamWrapper::GetStream(), and ns3::Simulator::Now().
InstallBulkSend()
void InstallBulkSend (Ptr< Node > node, Ipv4Address address, uint16_t port, std::string socketFactory, uint32_t nodeId, uint32_t cwndWindow, Callback< void, uint32_t, uint32_t > CwndTrace)
Definition at line 93 of file tcp-linux-reno.cc.
References first::address, CwndTrace(), ns3::BulkSendHelper::Install(), port, ns3::Simulator::Schedule(), ns3::Seconds(), ns3::BulkSendHelper::SetAttribute(), ns3::ApplicationContainer::Start(), ns3::ApplicationContainer::Stop(), stopTime, and TraceCwnd().
InstallPacketSink()
void InstallPacketSink (Ptr< Node > node, uint16_t port, std::string socketFactory)
Definition at line 106 of file tcp-linux-reno.cc.
References ns3::Ipv4Address::GetAny(), port, ns3::Seconds(), sink, ns3::ApplicationContainer::Start(), ns3::ApplicationContainer::Stop(), and stopTime.
TraceCwnd()
void TraceCwnd (uint32_t node, uint32_t cwndWindow, Callback< void, uint32_t, uint32_t > CwndTrace)
Definition at line 86 of file tcp-linux-reno.cc.
References ns3::Config::ConnectWithoutContext(), and CwndTrace().
Referenced by InstallBulkSend().
Variable Documentation
dir
std::string dir = "results/"
Definition at line 51 of file tcp-linux-reno.cc.
Referenced by CheckQueueSize(), ns3::IpcsClassifier::Classify(), CwndChange(), ns3::ServiceFlowManager::DoClassify(), and ns3::OnoeWifiManager::UpdateMode().
segmentSize
uint32_t segmentSize = 524
Definition at line 53 of file tcp-linux-reno.cc.
Referenced by TcpPacingTestSuite::TcpPacingTestSuite(), ns3::TcpRateLinux::CalculateAppLimited(), CwndChange(), ns3::TcpGeneralTest::SetSegmentSize(), ns3::TcpTxBuffer::SetSegmentSize(), and TcpTxBufferTestCase::TestNextSeg().
stopTime
Time stopTime = Seconds (60)
Definition at line 52 of file tcp-linux-reno.cc.
Referenced by CreateBulkFlow(), CreateOnOffFlow(), LteRlcAmE2eTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), LteX2HandoverTestCase::DoRun(), ns3::AnimationInterface::EnableIpv4L3ProtocolCounters(), ns3::AnimationInterface::EnableIpv4RouteTracking(), ns3::AnimationInterface::EnableQueueCounters(), ns3::AnimationInterface::EnableWifiMacCounters(), ns3::AnimationInterface::EnableWifiPhyCounters(), experiment(), InstallBulkSend(), InstallPacketSink(), and ns3::DataCalculator::Stop().