ns-3: src/fd-net-device/examples/fd-emu-tc.cc File Reference
fd-emu-tc.cc File Reference
#include "ns3/abort.h"
#include "ns3/core-module.h"
#include "ns3/internet-module.h"
#include "ns3/network-module.h"
#include "ns3/fd-net-device-module.h"
#include "ns3/internet-apps-module.h"
#include "ns3/ipv4-list-routing-helper.h"
#include "ns3/traffic-control-module.h"
Functions
void TcPacketsInQueue (Ptr< QueueDisc > q, Ptr< OutputStreamWrapper > stream)
Function Documentation
TcPacketsInQueue()
void TcPacketsInQueue (Ptr< QueueDisc > q, Ptr< OutputStreamWrapper > stream)
Definition at line 57 of file fd-emu-tc.cc.
References ns3::QueueDisc::GetNBytes(), ns3::QueueDisc::GetNPackets(), ns3::Time::GetSeconds(), ns3::QueueDisc::GetStats(), ns3::OutputStreamWrapper::GetStream(), ns3::Simulator::Now(), ns3::QueueDisc::Stats::nTotalDroppedBytes, ns3::QueueDisc::Stats::nTotalDroppedPackets, ns3::Simulator::Schedule(), and ns3::Seconds().