ns-3: src/traffic-control/examples/fqcodel-l4s-example.cc File Reference
fqcodel-l4s-example.cc File Reference
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/flow-monitor-helper.h"
#include "ns3/point-to-point-module.h"
#include "ns3/applications-module.h"
#include "ns3/internet-apps-module.h"
#include "ns3/traffic-control-module.h"
Functions
static void PacketDequeue (std::ofstream *n0OfStream, std::ofstream *n1OfStream, Ptr< QueueDiscItem const > item)
void ScheduleN0PacketSinkConnection (void)
void ScheduleN0TcpCwndTraceConnection (std::ofstream *ofStream)
void ScheduleN0TcpRttTraceConnection (std::ofstream *ofStream)
void ScheduleN1PacketSinkConnection (void)
void ScheduleN1TcpCwndTraceConnection (std::ofstream *ofStream)
void ScheduleN1TcpRttTraceConnection (std::ofstream *ofStream)
void TraceDrop (std::ofstream *ofStream, Ptr< const QueueDiscItem > item)
void TraceDropsFrequency (std::ofstream *ofStream, Time dropsSamplingInterval)
void TraceMark (std::ofstream *ofStream, Ptr< const QueueDiscItem > item, const char *reason)
void TraceMarksFrequency (std::ofstream *ofStream, Time marksSamplingInterval)
void TraceN0Cwnd (std::ofstream *ofStream, uint32_t oldCwnd, uint32_t newCwnd)
void TraceN0Rtt (std::ofstream *ofStream, Time oldRtt, Time newRtt)
void TraceN0Rx (Ptr< const Packet > packet, const Address &address)
void TraceN0Throughput (std::ofstream *ofStream, Time throughputInterval)
void TraceN1Cwnd (std::ofstream *ofStream, uint32_t oldCwnd, uint32_t newCwnd)
void TraceN1Rtt (std::ofstream *ofStream, Time oldRtt, Time newRtt)
void TraceN1Rx (Ptr< const Packet > packet, const Address &address)
void TraceN1Throughput (std::ofstream *ofStream, Time throughputInterval)
void TracePingRtt (std::ofstream *ofStream, Time rtt)
void TraceQueueLength (std::ofstream *ofStream, DataRate linkRate, uint32_t oldVal, uint32_t newVal)
Variables
double avgQueueDiscSize
uint32_t checkTimes
uint32_t g_dropsObserved = 0
uint32_t g_marksObserved = 0
uint32_t g_n0BytesReceived = 0
uint32_t g_n1BytesReceived = 0
Function Documentation
PacketDequeue()
static void PacketDequeue (std::ofstream * n0OfStream, std::ofstream * n1OfStream, Ptr< QueueDiscItem const > item) static
Definition at line 439 of file fqcodel-l4s-example.cc.
References first::address, ns3::Time::GetMicroSeconds(), ns3::Time::GetSeconds(), ns3::Simulator::Now(), and ns3::PeekPointer().
ScheduleN0PacketSinkConnection()
void ScheduleN0PacketSinkConnection (void)
Definition at line 415 of file fqcodel-l4s-example.cc.
References ns3::Config::ConnectWithoutContext(), ns3::MakeCallback(), and TraceN0Rx().
ScheduleN0TcpCwndTraceConnection()
void ScheduleN0TcpCwndTraceConnection (std::ofstream * ofStream)
Definition at line 403 of file fqcodel-l4s-example.cc.
References ns3::Config::ConnectWithoutContext(), ns3::MakeBoundCallback(), and TraceN0Cwnd().
ScheduleN0TcpRttTraceConnection()
void ScheduleN0TcpRttTraceConnection (std::ofstream * ofStream)
Definition at line 409 of file fqcodel-l4s-example.cc.
References ns3::Config::ConnectWithoutContext(), ns3::MakeBoundCallback(), and TraceN0Rtt().
ScheduleN1PacketSinkConnection()
void ScheduleN1PacketSinkConnection (void)
Definition at line 433 of file fqcodel-l4s-example.cc.
References ns3::Config::ConnectWithoutContext(), ns3::MakeCallback(), and TraceN1Rx().
ScheduleN1TcpCwndTraceConnection()
void ScheduleN1TcpCwndTraceConnection (std::ofstream * ofStream)
Definition at line 421 of file fqcodel-l4s-example.cc.
References ns3::Config::ConnectWithoutContext(), ns3::MakeBoundCallback(), and TraceN1Cwnd().
ScheduleN1TcpRttTraceConnection()
void ScheduleN1TcpRttTraceConnection (std::ofstream * ofStream)
Definition at line 427 of file fqcodel-l4s-example.cc.
References ns3::Config::ConnectWithoutContext(), ns3::MakeBoundCallback(), and TraceN1Rtt().
TraceDrop()
void TraceDrop (std::ofstream * ofStream, Ptr< const QueueDiscItem > item)
Definition at line 350 of file fqcodel-l4s-example.cc.
References g_dropsObserved, ns3::Time::GetSeconds(), and ns3::Simulator::Now().
TraceDropsFrequency()
void TraceDropsFrequency (std::ofstream * ofStream, Time dropsSamplingInterval)
Definition at line 371 of file fqcodel-l4s-example.cc.
References g_dropsObserved, ns3::Time::GetSeconds(), ns3::Simulator::Now(), and ns3::Simulator::Schedule().
TraceMark()
void TraceMark (std::ofstream * ofStream, Ptr< const QueueDiscItem > item, const char * reason)
Definition at line 357 of file fqcodel-l4s-example.cc.
References g_marksObserved, ns3::Time::GetSeconds(), and ns3::Simulator::Now().
TraceMarksFrequency()
void TraceMarksFrequency (std::ofstream * ofStream, Time marksSamplingInterval)
Definition at line 379 of file fqcodel-l4s-example.cc.
References g_marksObserved, ns3::Time::GetSeconds(), ns3::Simulator::Now(), and ns3::Simulator::Schedule().
TraceN0Cwnd()
void TraceN0Cwnd (std::ofstream * ofStream, uint32_t oldCwnd, uint32_t newCwnd)
Definition at line 304 of file fqcodel-l4s-example.cc.
References ns3::Time::GetSeconds(), and ns3::Simulator::Now().
Referenced by ScheduleN0TcpCwndTraceConnection().
TraceN0Rtt()
void TraceN0Rtt (std::ofstream * ofStream, Time oldRtt, Time newRtt)
Definition at line 320 of file fqcodel-l4s-example.cc.
References ns3::Time::GetSeconds(), and ns3::Simulator::Now().
Referenced by ScheduleN0TcpRttTraceConnection().
TraceN0Rx()
void TraceN0Rx (Ptr< const Packet > packet, const Address & address)
Definition at line 338 of file fqcodel-l4s-example.cc.
References g_n0BytesReceived.
Referenced by ScheduleN0PacketSinkConnection().
TraceN0Throughput()
void TraceN0Throughput (std::ofstream * ofStream, Time throughputInterval)
Definition at line 387 of file fqcodel-l4s-example.cc.
References g_n0BytesReceived, ns3::Time::GetSeconds(), ns3::Simulator::Now(), and ns3::Simulator::Schedule().
TraceN1Cwnd()
void TraceN1Cwnd (std::ofstream * ofStream, uint32_t oldCwnd, uint32_t newCwnd)
Definition at line 312 of file fqcodel-l4s-example.cc.
References ns3::Time::GetSeconds(), and ns3::Simulator::Now().
Referenced by ScheduleN1TcpCwndTraceConnection().
TraceN1Rtt()
void TraceN1Rtt (std::ofstream * ofStream, Time oldRtt, Time newRtt)
Definition at line 326 of file fqcodel-l4s-example.cc.
References ns3::Time::GetSeconds(), and ns3::Simulator::Now().
Referenced by ScheduleN1TcpRttTraceConnection().
TraceN1Rx()
void TraceN1Rx (Ptr< const Packet > packet, const Address & address)
Definition at line 344 of file fqcodel-l4s-example.cc.
References g_n1BytesReceived.
Referenced by ScheduleN1PacketSinkConnection().
TraceN1Throughput()
void TraceN1Throughput (std::ofstream * ofStream, Time throughputInterval)
Definition at line 395 of file fqcodel-l4s-example.cc.
References g_n1BytesReceived, ns3::Time::GetSeconds(), ns3::Simulator::Now(), and ns3::Simulator::Schedule().
TracePingRtt()
void TracePingRtt (std::ofstream * ofStream, Time rtt)
Definition at line 332 of file fqcodel-l4s-example.cc.
References ns3::Time::GetSeconds(), and ns3::Simulator::Now().
TraceQueueLength()
void TraceQueueLength (std::ofstream * ofStream, DataRate linkRate, uint32_t oldVal, uint32_t newVal)
Definition at line 364 of file fqcodel-l4s-example.cc.
References ns3::DataRate::GetBitRate(), ns3::Time::GetSeconds(), and ns3::Simulator::Now().
Variable Documentation
avgQueueDiscSize
double avgQueueDiscSize
Definition at line 296 of file fqcodel-l4s-example.cc.
checkTimes
uint32_t checkTimes
Definition at line 295 of file fqcodel-l4s-example.cc.
g_dropsObserved
uint32_t g_dropsObserved = 0
Definition at line 301 of file fqcodel-l4s-example.cc.
Referenced by TraceDrop(), and TraceDropsFrequency().
g_marksObserved
uint32_t g_marksObserved = 0
Definition at line 300 of file fqcodel-l4s-example.cc.
Referenced by TraceMark(), and TraceMarksFrequency().
g_n0BytesReceived
uint32_t g_n0BytesReceived = 0
Definition at line 298 of file fqcodel-l4s-example.cc.
Referenced by TraceN0Rx(), and TraceN0Throughput().
g_n1BytesReceived
uint32_t g_n1BytesReceived = 0
Definition at line 299 of file fqcodel-l4s-example.cc.
Referenced by TraceN1Rx(), and TraceN1Throughput().