ns-3: Integer Attribute
Integer Attribute
Attribute implementation for Integer.
Files
file integer.cc
ns3::MakeIntegerChecker implementation.
file integer.h
ns3::IntegerValue attribute value declarations and template implementations.
Classes
class IntegerChecker
AttributeChecker implementation for IntegerValue.
class ns3::IntegerValue
Hold a signed integer type.
Functions
template<typename T1 >
Ptr< const AttributeAccessor > ns3::MakeIntegerAccessor (T1 a1)
Create an AttributeAccessor for a class data member, or a lone class get functor or set method.
template<typename T1 , typename T2 >
Ptr< const AttributeAccessor > ns3::MakeIntegerAccessor (T1 a1, T2 a2)
Create an AttributeAccessor using a pair of get functor and set methods from a class.
Ptr< const AttributeChecker > ns3::internal::MakeIntegerChecker (int64_t min, int64_t max, std::string name)
Make an Integer attribute checker with embedded numeric type name.
template<typename T >
Ptr< const AttributeChecker > ns3::MakeIntegerChecker (void)
Detailed Description
Attribute implementation for Integer.
Function Documentation
MakeIntegerAccessor() [1/2]
template<typename T1 > ns3::Ptr< const ns3::AttributeAccessor > ns3::MakeIntegerAccessor (T1 a1)
Create an AttributeAccessor for a class data member, or a lone class get functor or set method.
The get functor method should have a signature like
typedef U (T::*getter)(void) const
where T is the class and U is the type of the return value.
The set method should have one of these signatures:
typedef void (T::*setter)(U)
typedef bool (T::*setter)(U)
where T is the class and U is the type of the value to set the attribute to, which should be compatible with the specific AttributeValue type V which holds the value (or the type implied by the name Make<V>Accessor of this function.) In the case of a setter returning bool, the return value should be true if the value could be set successfully.
Template Parameters
V [explicit] (If present) The specific AttributeValue type to use to represent the Attribute. (If not present, the type V is implicit in the name of this function, as "Make<V>Accessor"
T1 [deduced] The type of the class data member, or the type of the class get functor or set method.
Parameters
[in] a1 The address of the data member, or the get or set method.
Returns
The AttributeAccessor
See also
AttributeAccessor
Definition at line 45 of file integer.h.
Referenced by ns3::Icmpv6L4Protocol::GetTypeId(), ns3::ThreeGppChannelModel::GetTypeId(), ConfigExample::GetTypeId(), ns3::RandomVariableStream::GetTypeId(), ns3::SequentialRandomVariable::GetTypeId(), ns3::ErlangRandomVariable::GetTypeId(), ns3::ZipfRandomVariable::GetTypeId(), AttributeObjectTest::GetTypeId(), ns3::tests::ConfigTestObject::GetTypeId(), ns3::tests::BaseConfigObject::GetTypeId(), DeprecatedAttribute::GetTypeId(), ns3::RvBatteryModel::GetTypeId(), ns3::IpL4Protocol::GetTypeId(), ns3::TcpCubic::GetTypeId(), ns3::UdpSocket::GetTypeId(), ns3::LrWpanLqiTag::GetTypeId(), ns3::RadioEnvironmentMapHelper::GetTypeId(), ns3::FdTbfqFfMacScheduler::GetTypeId(), ns3::LteEnbRrc::GetTypeId(), ns3::LteUePowerControl::GetTypeId(), and ns3::TdTbfqFfMacScheduler::GetTypeId().
MakeIntegerAccessor() [2/2]
template<typename T1 , typename T2 > ns3::Ptr< const ns3::AttributeAccessor > ns3::MakeIntegerAccessor (T1 a1, T2 a2)
Create an AttributeAccessor using a pair of get functor and set methods from a class.
The get functor method should have a signature like
typedef U (T::*getter)(void) const
where T is the class and U is the type of the return value.
The set method should have one of these signatures:
typedef void (T::*setter)(U)
typedef bool (T::*setter)(U)
where T is the class and U is the type of the value to set the attribute to, which should be compatible with the specific AttributeValue type V which holds the value (or the type implied by the name Make<V>Accessor of this function.) In the case of a setter returning bool, the return value should be true if the value could be set successfully.
In practice the setter and getter arguments can appear in either order, but setter first is preferred.
Template Parameters
V [explicit] (If present) The specific AttributeValue type to use to represent the Attribute. (If not present, the type V is implicit in the name of this function as "Make<V>Accessor"
T1 [deduced] The type of the class data member, or the type of the class get functor or set method.
T2 [deduced] The type of the getter class functor method.
Parameters
[in] a2 The address of the class method to set the attribute.
[in] a1 The address of the data member, or the get or set method.
Returns
The AttributeAccessor
See also
AttributeAccessor
Definition at line 45 of file integer.h.
MakeIntegerChecker() [1/2]
Ptr< const AttributeChecker > ns3::internal::MakeIntegerChecker (int64_t min, int64_t max, std::string name)
Make an Integer attribute checker with embedded numeric type name.
Parameters
[in] min The minimum allowed value.
[in] max The maximum allowed value.
[in] name The original type name ("int8_t", "int16_t", etc.).
Returns
The AttributeChecker.
Definition at line 49 of file integer.cc.
References ns3::Copy(), ns3::Create(), ns3::IntegerValue::Get(), ns3::max(), ns3::min(), NS_LOG_FUNCTION, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::MakeIntegerChecker().
MakeIntegerChecker() [2/2]
template<typename T > ns3::Ptr< const ns3::AttributeChecker > ns3::MakeIntegerChecker (void)
Returns
The AttributeChecker.
See also
AttributeChecker
Definition at line 111 of file integer.h.
References ns3::internal::MakeIntegerChecker(), max, and min.