ns-3: High Precision Q64.64
High Precision Q64.64
Core
Functions and class for high precision Q64.64 fixed point arithmetic.
Files
file cairo-wideint-private.h
cairo_x function declarations, which provide the fallback high precision arithmetic implementation.
file cairo-wideint.c
Implementation of the cairo_x functions which implement high precision arithmetic.
file int64x64-128.cc
Implementation of the ns3::int64x64_t type using a native int128_t type.
file int64x64-128.h
Declaration of the ns3::int64x64_t type using a native int128_t type.
file int64x64-cairo.cc
Implementation of the ns3::int64x64_t type using the Cairo implementation.
file int64x64-cairo.h
Declaration of the ns3::int64x64_t type using the Cairo implementation.
file int64x64-double.h
Declaration and implementation of the ns3::int64x64_t type using the double type.
file int64x64.cc
Implementation of the streaming input and output operators for the ns3::int64x64_t type.
file int64x64.h
Declaration of the ns3::int64x64_t type and associated operators.
Classes
class ns3::int64x64_t
High precision numerical type, implementing Q64.64 fixed precision.
Macros
#define HEXHILOW(hi, lo)
Print the high and low words of an int64x64 in hex, for debugging.
Functions
int64x64_t ns3::Abs (const int64x64_t &value)
Absolute value.
int64x64_t ns3::Max (const int64x64_t &a, const int64x64_t &b)
Maximum.
int64x64_t ns3::Min (const int64x64_t &a, const int64x64_t &b)
Minimum.
int64x64_t ns3::operator! (const int64x64_t &lhs)
Logical not operator.
bool ns3::operator!= (const int64x64_t &lhs, const int64x64_t &rhs)
Inequality operator.
int64x64_t ns3::operator* (const int64x64_t &lhs, const int64x64_t &rhs)
Multiplication operator.
int64x64_t & ns3::operator*= (int64x64_t &lhs, const int64x64_t &rhs)
Compound multiplication operator.
int64x64_t ns3::operator+ (const int64x64_t &lhs)
Unary plus operator.
int64x64_t ns3::operator+ (const int64x64_t &lhs, const int64x64_t &rhs)
Addition operator.
int64x64_t & ns3::operator+= (int64x64_t &lhs, const int64x64_t &rhs)
Compound addition operator.
int64x64_t ns3::operator- (const int64x64_t &lhs)
Unary negation operator (change sign operator).
int64x64_t ns3::operator- (const int64x64_t &lhs, const int64x64_t &rhs)
Subtraction operator.
int64x64_t & ns3::operator-= (int64x64_t &lhs, const int64x64_t &rhs)
Compound subtraction operator.
int64x64_t ns3::operator/ (const int64x64_t &lhs, const int64x64_t &rhs)
Division operator.
int64x64_t & ns3::operator/= (int64x64_t &lhs, const int64x64_t &rhs)
Compound division operator.
bool ns3::operator< (const int64x64_t &lhs, const int64x64_t &rhs)
Less than operator.
std::ostream & ns3::operator<< (std::ostream &os, const int64x64_t &value)
Output streamer for int64x64_t.
bool ns3::operator<= (const int64x64_t &lhs, const int64x64_t &rhs)
Less or equal operator.
bool ns3::operator== (const int64x64_t &lhs, const int64x64_t &rhs)
Equality operator.
bool ns3::operator> (const int64x64_t &lhs, const int64x64_t &rhs)
Greater operator.
bool ns3::operator>= (const int64x64_t &lhs, const int64x64_t &rhs)
Greater or equal operator.
std::istream & ns3::operator>> (std::istream &is, int64x64_t &value)
Input streamer for int64x64_t.
static bool ns3::output_sign (const cairo_int128_t sa, const cairo_int128_t sb, cairo_uint128_t &ua, cairo_uint128_t &ub)
Compute the sign of the result of multiplying or dividing Q64.64 fixed precision operands.
static bool ns3::output_sign (const int128_t sa, const int128_t sb, uint128_t &ua, uint128_t &ub)
Compute the sign of the result of multiplying or dividing Q64.64 fixed precision operands.
static uint64_t ns3::ReadHiDigits (std::string str)
Read the integer portion of a number from a string containing just the integral digits (no decimal point or fractional part).
static uint64_t ns3::ReadLoDigits (std::string str)
Read the fractional part of a number from a string containing just the decimal digits of the fractional part (no integral part or decimal point).
Detailed Description
Functions and class for high precision Q64.64 fixed point arithmetic.
A Q64.64 fixed precision number consists of:
Bits Function
1 Sign bit
63 Integer portion
64 Fractional portion
The high word consists of the sign bit and integer value; the low word is the fractional part, unscaled.
All standard arithmetic operations are supported:
Category Operators
Computation +, +=, -, -=, *, *=, /, /=
Comparison ==, !=, <, <=, >, >=
Unary +, -, !
Macro Definition Documentation
HEXHILOW
#define HEXHILOW (hi, lo)
Value:
  std::hex << std::setfill ('0') << std::right << " (0x"                \
           << std::setw (16) << hi << " "                               \
           << std::setw (16) << lo                                      \
           << std::dec << std::setfill (' ') << std::left << ")"
Print the high and low words of an int64x64 in hex, for debugging.
Parameters
[in] hi The high (integer) word.
[in] lo The low (fractional) work.
Definition at line 49 of file int64x64.cc.
Function Documentation
Abs()
int64x64_t ns3::Abs (const int64x64_t & value) inline
Absolute value.
Parameters
[in] value The value to operate on.
Returns
The absolute value of value.
Definition at line 205 of file int64x64.h.
Referenced by ns3::UanPhyCalcSinrFhFsk::CalcSinrDb(), ns3::int64x64::test::Int64x64DoubleTestCase::Check(), ns3::int64x64::test::Int64x64InputOutputTestCase::Check(), ns3::int64x64::test::Int64x64InvertTestCase::CheckCase(), ns3::RttMeanDeviation::FloatingPointUpdate(), ns3::DelayJitterEstimation::RecordRx(), and BatteryLifetimeTest::VariableLoadTest().
Max()
int64x64_t ns3::Max (const int64x64_t & a, const int64x64_t & b) inline
Maximum.
Parameters
[in] a The first value.
[in] b The second value.
Returns
The larger of the arguments.
Definition at line 230 of file int64x64.h.
Referenced by ns3::int64x64::test::Int64x64HiLoTestCase::Check(), ns3::int64x64::test::Int64x64InputTestCase::Check(), ns3::WifiMacQueueItem::DoAggregate(), ns3::TcpSocketBase::DoPeerClose(), ns3::AarfWifiManager::DoReportDataFailed(), ns3::AarfcdWifiManager::DoReportDataFailed(), ns3::TcpSocketBase::EstimateRtt(), ns3::WifiPhyStateHelper::GetDelayUntilIdle(), ns3::TcpSocketBase::LastAckTimeout(), ns3::WifiPhyStateHelper::LogPreviousIdleAndCcaBusyStates(), ns3::TcpSocketBase::NewAck(), ns3::MinstrelHtWifiManager::PrintTable(), ns3::TcpSocketBase::SendEmptyPacket(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), ns3::WifiPhyStateHelper::SwitchToChannelSwitching(), ns3::WifiPhyStateHelper::SwitchToOff(), ns3::WifiPhyStateHelper::SwitchToRx(), ns3::WifiPhyStateHelper::SwitchToSleep(), and ns3::WifiPhyStateHelper::SwitchToTx().
Min()
int64x64_t ns3::Min (const int64x64_t & a, const int64x64_t & b) inline
Minimum.
Parameters
[in] a The first value.
[in] b The second value.
Returns
The smaller of the arguments.
Definition at line 218 of file int64x64.h.
Referenced by ns3::RemoteChannelBundle::AddChannel(), ns3::DistributedSimulatorImpl::BoundLookAhead(), ns3::NullMessageSimulatorImpl::CalculateGuaranteeTime(), ns3::InterferenceHelper::CalculatePayloadPer(), ns3::MinstrelHtWifiManager::CalculateRetransmits(), ns3::int64x64::test::Int64x64HiLoTestCase::Check(), ns3::int64x64::test::Int64x64InputTestCase::Check(), ns3::ConstantRateWifiManager::DoGetDataTxVector(), ns3::AarfWifiManager::DoReportDataFailed(), ns3::AarfcdWifiManager::DoReportDataFailed(), ns3::RemoteChannelBundleManager::GetSafeTime(), ns3::NullMessageSimulatorImpl::NullMessageEventHandler(), and ns3::TcpSocketBase::ReTxTimeout().
operator!()
int64x64_t ns3::operator! (const int64x64_t & lhs) inline
Logical not operator.
Parameters
[in] lhs Left hand argument
Returns
The result of the operator.
Definition at line 511 of file int64x64-128.h.
operator!=()
bool ns3::operator!= (const int64x64_t & lhs, const int64x64_t & rhs) inline
Inequality operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 144 of file int64x64.h.
operator*()
int64x64_t ns3::operator* (const int64x64_t & lhs, const int64x64_t & rhs) inline
Multiplication operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 117 of file int64x64.h.
operator*=()
int64x64_t & ns3::operator*= (int64x64_t & lhs, const int64x64_t & rhs) inline
Compound multiplication operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 467 of file int64x64-128.h.
operator+() [1/2]
int64x64_t ns3::operator+ (const int64x64_t & lhs) inline
Unary plus operator.
Parameters
[in] lhs Left hand argument
Returns
The result of the operator.
Definition at line 491 of file int64x64-128.h.
operator+() [2/2]
int64x64_t ns3::operator+ (const int64x64_t & lhs, const int64x64_t & rhs) inline
Addition operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 89 of file int64x64.h.
operator+=()
int64x64_t & ns3::operator+= (int64x64_t & lhs, const int64x64_t & rhs) inline
Compound addition operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 443 of file int64x64-128.h.
operator-() [1/2]
int64x64_t ns3::operator- (const int64x64_t & lhs) inline
Unary negation operator (change sign operator).
Unary operator.
Unary negation operator (change sign operator)
Parameters
[in] lhs Left hand argument
Returns
The result of the operator.
Definition at line 501 of file int64x64-128.h.
operator-() [2/2]
int64x64_t ns3::operator- (const int64x64_t & lhs, const int64x64_t & rhs) inline
Subtraction operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 103 of file int64x64.h.
operator-=()
int64x64_t & ns3::operator-= (int64x64_t & lhs, const int64x64_t & rhs) inline
Compound subtraction operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 455 of file int64x64-128.h.
operator/()
int64x64_t ns3::operator/ (const int64x64_t & lhs, const int64x64_t & rhs) inline
Division operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 131 of file int64x64.h.
operator/=()
int64x64_t & ns3::operator/= (int64x64_t & lhs, const int64x64_t & rhs) inline
Compound division operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 479 of file int64x64-128.h.
operator<()
bool ns3::operator< (const int64x64_t & lhs, const int64x64_t & rhs) inline
Less than operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 420 of file int64x64-128.h.
operator<<()
std::ostream & ns3::operator<< (std::ostream & os, const int64x64_t & value)
Output streamer for int64x64_t.
Internal:
This algorithm is exact to the precision requested, up to the full 64 decimal digits required to exactly represent a 64-bit fraction.
Proper rounding turns out to be surprisingly hard. In y.xxxx5|6, where the | marks follows the last output digit, rounding the 5|6 to 6| is straightforward. However, rounding y.xxx99|6 should result in y.xx100|. Notice the effect of rounding percolates to higher digits. We accumulate the output digits in a string, then carry out the rounding in the string directly.
Values are printed with the following format flags (independent of the stream flags):
showpos
left
The stream width is ignored. If floatfield is set, precision decimal places are printed. If floatfield is not set, all digits of the fractional part are printed, up to the representation limit of 20 digits; trailing zeros are omitted.
Parameters
[in,out] os The output stream.
[in] value The numerical value to print.
Returns
The stream.
Definition at line 69 of file int64x64.cc.
References ns3::int64x64_t::GetHigh(), ns3::int64x64_t::GetLow(), HEXHILOW, NS_ASSERT_MSG, and NS_LOG_LOGIC.
operator<=()
bool ns3::operator<= (const int64x64_t & lhs, const int64x64_t & rhs) inline
Less or equal operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 155 of file int64x64.h.
operator==()
bool ns3::operator== (const int64x64_t & lhs, const int64x64_t & rhs) inline
Equality operator.
Arithmetic operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 409 of file int64x64-128.h.
operator>()
bool ns3::operator> (const int64x64_t & lhs, const int64x64_t & rhs) inline
Greater operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 431 of file int64x64-128.h.
operator>=()
bool ns3::operator>= (const int64x64_t & lhs, const int64x64_t & rhs) inline
Greater or equal operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 166 of file int64x64.h.
operator>>()
std::istream & ns3::operator>> (std::istream & is, int64x64_t & value)
Input streamer for int64x64_t.
Parameters
[in,out] is The input stream.
[out] value The numerical value to set.
Returns
The stream.
Definition at line 222 of file int64x64.cc.
References ns3::ReadHiDigits(), and ns3::ReadLoDigits().
output_sign() [1/2]
static bool ns3::output_sign (const cairo_int128_t sa, const cairo_int128_t sb, cairo_uint128_t & ua, cairo_uint128_t & ub) inline static
Compute the sign of the result of multiplying or dividing Q64.64 fixed precision operands.
Parameters
[in] sa The signed value of the first operand.
[in] sb The signed value of the second operand.
[out] ua The unsigned magnitude of the first operand.
[out] ub The unsigned magnitude of the second operand.
Returns
True if the result will be negative.
Definition at line 59 of file int64x64-cairo.cc.
References _cairo_int128_negative, _cairo_int128_to_uint128, and _cairo_uint128_negate().
output_sign() [2/2]
static bool ns3::output_sign (const int128_t sa, const int128_t sb, uint128_t & ua, uint128_t & ub) inline static
Compute the sign of the result of multiplying or dividing Q64.64 fixed precision operands.
Parameters
[in] sa The signed value of the first operand.
[in] sb The signed value of the second operand.
[out] ua The unsigned magnitude of the first operand.
[out] ub The unsigned magnitude of the second operand.
Returns
true if the result will be negative.
Definition at line 51 of file int64x64-128.cc.
Referenced by ns3::int64x64_t::Div(), and ns3::int64x64_t::Mul().
ReadHiDigits()
static uint64_t ns3::ReadHiDigits (std::string str) static
Read the integer portion of a number from a string containing just the integral digits (no decimal point or fractional part).
Parameters
[in] str The string representation of the integral part of a number, with no fractional part or decimal point.
Returns
The integer.
Definition at line 180 of file int64x64.cc.
Referenced by ns3::operator>>().
ReadLoDigits()
static uint64_t ns3::ReadLoDigits (std::string str) static
Read the fractional part of a number from a string containing just the decimal digits of the fractional part (no integral part or decimal point).
Parameters
[in] str The string representation of the fractional part of a number, without integral part or decimal point.
Returns
The decimal portion of the input number.
Definition at line 203 of file int64x64.cc.
References ns3::int64x64_t::GetLow(), and NS_ASSERT_MSG.
Referenced by ns3::operator>>().