ns-3: Wifi Models
Wifi Models
This section documents the API of the ns-3 Wifi module.
Modules
wifi module tests
Classes
class ns3::AarfcdWifiManager
an implementation of the AARF-CD algorithm
class ns3::AarfWifiManager
AARF Rate control algorithm.
class ns3::AdhocWifiMac
Wifi MAC high model for an ad-hoc Wifi MAC.
class ns3::AmpduSubframeHeader
Headers for A-MPDU subframes.
class ns3::AmpduTag
The aim of the AmpduTag is to provide means for a MAC to specify that a packet includes A-MPDU since this is done in HT-SIG and there is no HT-SIG representation in ns-3.
class ns3::AmrrWifiManager
AMRR Rate control algorithm.
class ns3::AmsduSubframeHeader
Headers for A-MSDU subframes.
class ns3::AparfWifiManager
APARF Power and rate control algorithm.
struct ns3::ApInfo
Struct to hold information regarding observed AP through active/passive scanning.
class ns3::ApWifiMac
Wi-Fi AP state machine.
class ns3::ArfWifiManager
ARF Rate control algorithm.
struct ns3::Bar
BlockAckRequest frame information.
class ns3::BlockAckAgreement
Maintains information for a block ack agreement.
class ns3::BlockAckCache
BlockAckCache cache.
class ns3::BlockAckManager
Manages all block ack agreements for an originator station.
class ns3::BlockAckWindow
Block ack window.
class ns3::CapabilityInformation
Capability information.
class ns3::CaraWifiManager
implement the CARA rate control algorithm
class CarrierAggregationTestCase
This system test program creates different test cases with a single eNB and several UEs, all having the same Radio Bearer specification.
class ns3::CfParameterSet
The CF Parameter Set.
class ns3::ChannelAccessManager
Manage a set of ns3::Txop.
class ns3::ConstantObssPdAlgorithm
Constant OBSS PD algorithm.
class ns3::ConstantRateWifiManager
use constant rates for data and RTS transmissions
class ns3::ConstantWifiAckPolicySelector
A constant ack policy selector operating based on the values of its attributes.
class ns3::CtrlBAckRequestHeader
Headers for BlockAckRequest.
class ns3::CtrlBAckResponseHeader
Headers for BlockAck response.
class ns3::DsssErrorRateModel
an implementation of DSSS error rate model
class ns3::DsssParameterSet
The DSSS Parameter Set.
class ns3::DsssSigHeader
Implements the IEEE 802.11 DSSS SIG PHY header.
class ns3::EdcaParameterSet
The EDCA Parameter Set.
class ns3::ErpInformation
The ErpInformation Information Element.
class ns3::ErrorRateModel
the interface for Wifi's error models
class ns3::Event
handles interference calculations
class ns3::ExtendedCapabilities
The Extended Capabilities Information Element.
class ns3::ExtendedSupportedRatesIE
The Extended Supported Rates Information Element.
class ns3::FrameCaptureModel
the interface for Wifi's frame capture models
class ns3::HeCapabilities
The IEEE 802.11ax HE Capabilities.
class ns3::HeConfiguration
HE configuration.
class ns3::HeOperation
The HE Operation Information Element.
class ns3::HeSigHeader
Implements the IEEE 802.11ax HE-SIG PHY header (HE-SIG-A1/A2/B)
class ns3::HtCapabilities
The HT Capabilities Information Element.
class ns3::HtConfiguration
HT configuration.
class ns3::HtOperation
The HT Operation Information Element.
class ns3::HtSigHeader
Implements the IEEE 802.11n PHY header (HT-SIG1/2).
class ns3::IdealWifiManager
Ideal rate control algorithm.
class ns3::InfrastructureWifiMac
The Wifi MAC high model for a STA or AP in a BSS.
class ns3::InterferenceHelper
handles interference calculations
class ns3::LSigHeader
Implements the IEEE 802.11 OFDM and ERP OFDM L-SIG PHY header.
class ns3::MacLow
handle RTS/CTS/Data/Ack transactions.
class ns3::MacLowTransmissionParameters
control how a packet is transmitted.
class ns3::MacRxMiddle
This class handles duplicate detection and recomposition of fragments.
class ns3::MacTxMiddle
Handles sequence numbering of IEEE 802.11 data frames.
class ns3::MgtAddBaRequestHeader
Implement the header for management frames of type Add Block Ack request.
class ns3::MgtAddBaResponseHeader
Implement the header for management frames of type Add Block Ack response.
class ns3::MgtAssocRequestHeader
Implement the header for management frames of type association request.
class ns3::MgtAssocResponseHeader
Implement the header for management frames of type association and reassociation response.
class ns3::MgtBeaconHeader
Implement the header for management frames of type beacon.
class ns3::MgtDelBaHeader
Implement the header for management frames of type Delete Block Ack.
class ns3::MgtProbeRequestHeader
Implement the header for management frames of type probe request.
class ns3::MgtProbeResponseHeader
Implement the header for management frames of type probe response.
class ns3::MgtReassocRequestHeader
Implement the header for management frames of type reassociation request.
class ns3::MinstrelHtWifiManager
Implementation of Minstrel HT Rate Control Algorithm.
class ns3::MinstrelWifiManager
Implementation of Minstrel Rate Control Algorithm.
class ns3::MpduAggregator
Aggregator used to construct A-MPDUs.
class ns3::MsduAggregator
Aggregator used to construct A-MSDUs.
class ns3::NistErrorRateModel
A model for the error rate for different modulations.
class ns3::ObssPdAlgorithm
OBSS PD algorithm interface.
class ns3::OnoeWifiManager
an implementation of the rate control algorithm developed by Atsushi Onoe
class ns3::OriginatorBlockAckAgreement
Maintains the state and information about transmitted MPDUs with Ack Policy set to Block Ack for an originator station.
class ns3::ParfWifiManager
PARF Rate control algorithm.
class ns3::PreambleDetectionModel
the interface for Wifi's preamble detection models
class ns3::QosTxop
Handle packet fragmentation and retransmissions for QoS data frames as well as MSDU aggregation (A-MSDU) and block ack sessions, for a given access class.
class ns3::RegularWifiMac
base class for all MAC-level wifi objects.
class ns3::RraaWifiManager
Robust Rate Adaptation Algorithm.
class ns3::SimpleFrameCaptureModel
A simple threshold-based model for frame capture effect.
class ns3::SpectrumWifiPhy
802.11 PHY layer model
class ns3::Ssid
The IEEE 802.11 SSID Information Element.
class ns3::StaWifiMac
The Wifi MAC high model for a non-AP STA in a BSS.
class ns3::SupportedRates
The Supported Rates Information Element.
class ns3::ThresholdPreambleDetectionModel
A threshold-based model for detecting PHY preamble.
class ns3::Txop
Handle packet fragmentation and retransmissions for data and management frames.
class ns3::VhtCapabilities
The IEEE 802.11ac VHT Capabilities.
class ns3::VhtConfiguration
VHT configuration.
class ns3::VhtOperation
The VHT Operation Information Element.
class ns3::VhtSigHeader
Implements the IEEE 802.11ac PHY header (VHT-SIG-A1/A2/B).
class ns3::WifiAckPolicySelector
WifiAckPolicySelector is in charge of selecting the acknowledgment policy for PSDUs containing QoS Data frames.
class ns3::WifiActionHeader
See IEEE 802.11 chapter 7.3.1.11 Header format: | category: 1 | action value: 1 |.
class ns3::WifiInformationElement
Information element, as defined in 802.11-2007 standard.
class ns3::WifiInformationElementVector
Information element vector.
class ns3::WifiMac
base class for all MAC-level wifi objects.
class ns3::WifiMacHeader
Implements the IEEE 802.11 MAC header.
class ns3::WifiMacQueue
This queue implements the timeout procedure described in (Section 9.19.2.6 "Retransmit procedures" paragraph 6; IEEE 802.11-2012).
class ns3::WifiMacQueueItem
WifiMacQueueItem stores (const) packets along with their Wifi MAC headers and the time when they were enqueued.
class ns3::WifiMacTrailer
Implements the IEEE 802.11 MAC trailer.
class ns3::WifiMode
represent a single transmission mode
class ns3::WifiNetDevice
Hold together all Wifi-related objects.
class ns3::WifiPhy
802.11 PHY layer model
class ns3::WifiPhyStateHelper
This objects implements the PHY state machine of the Wifi device.
class ns3::WifiPhyTag
Tag for WifiTxVector and WifiPreamble information to be embedded in outgoing transmissions as a PacketTag.
class ns3::WifiPpdu
WifiPpdu stores a preamble, a modulation class, PHY headers and a PSDU.
class ns3::WifiPsdu
WifiPsdu stores an MPDU, S-MPDU or A-MPDU, by keeping header(s) and payload(s) separate for each constituent MPDU.
class ns3::WifiRemoteStationManager
hold a list of per-remote-station state.
struct ns3::WifiRrpaaThresholds
Robust Rate and Power Adaptation Algorithm.
class ns3::WifiSpectrumPhyInterface
This class is an adaptor between class SpectrumWifiPhy (which inherits from WifiPhy) and class SpectrumChannel (which expects objects derived from class SpectrumPhy to be connected to it).
struct ns3::WifiSpectrumSignalParameters
Signal parameters for wifi.
class ns3::YansErrorRateModel
Model the error rate for different modulations.
class ns3::YansWifiChannel
a channel to interconnect ns3::YansWifiPhy objects.
class ns3::YansWifiPhy
802.11 PHY layer model
Enumerations
enum ns3::AcIndex {
ns3::AC_BE = 0 , ns3::AC_BK = 1 , ns3::AC_VI = 2 , ns3::AC_VO = 3 ,
ns3::AC_BE_NQOS = 4 , ns3::AC_UNDEF
}
This enumeration defines the Access Categories as an enumeration with values corresponding to the AC index (ACI) values specified (Table 8-104 "ACI-to-AC coding"; IEEE 802.11-2012).
enum ns3::BlockAckType { ns3::BASIC_BLOCK_ACK , ns3::COMPRESSED_BLOCK_ACK , ns3::EXTENDED_COMPRESSED_BLOCK_ACK , ns3::MULTI_TID_BLOCK_ACK }
The different block ack policies.
enum ns3::MpduType {
ns3::NORMAL_MPDU , ns3::SINGLE_MPDU , ns3::FIRST_MPDU_IN_AGGREGATE , ns3::MIDDLE_MPDU_IN_AGGREGATE ,
ns3::LAST_MPDU_IN_AGGREGATE
}
The type of an MPDU.
enum ns3::WifiMacStandard { ns3::WIFI_MAC_STANDARD_80211 , ns3::WIFI_MAC_STANDARD_80211n , ns3::WIFI_MAC_STANDARD_80211ac , ns3::WIFI_MAC_STANDARD_80211ax }
Identifies the MAC specification that a Wifi device is configured to use.
enum ns3::WifiPhyBand { ns3::WIFI_PHY_BAND_2_4GHZ , ns3::WIFI_PHY_BAND_5GHZ , ns3::WIFI_PHY_BAND_6GHZ , ns3::WIFI_PHY_BAND_UNSPECIFIED }
Identifies the PHY band.
enum ns3::WifiPhyStandard {
ns3::WIFI_PHY_STANDARD_80211a , ns3::WIFI_PHY_STANDARD_80211b , ns3::WIFI_PHY_STANDARD_80211g , ns3::WIFI_PHY_STANDARD_80211_10MHZ ,
ns3::WIFI_PHY_STANDARD_80211_5MHZ , ns3::WIFI_PHY_STANDARD_80211p , ns3::WIFI_PHY_STANDARD_holland , ns3::WIFI_PHY_STANDARD_80211n_2_4GHZ ,
ns3::WIFI_PHY_STANDARD_80211n_5GHZ , ns3::WIFI_PHY_STANDARD_80211n , ns3::WIFI_PHY_STANDARD_80211ac , ns3::WIFI_PHY_STANDARD_80211ax ,
ns3::WIFI_PHY_STANDARD_UNSPECIFIED
}
Identifies the PHY specification that a Wifi device is configured to use.
enum ns3::WifiPreamble {
ns3::WIFI_PREAMBLE_LONG , ns3::WIFI_PREAMBLE_SHORT , ns3::WIFI_PREAMBLE_HT_MF , ns3::WIFI_PREAMBLE_HT_GF ,
ns3::WIFI_PREAMBLE_VHT_SU , ns3::WIFI_PREAMBLE_VHT_MU , ns3::WIFI_PREAMBLE_HE_SU , ns3::WIFI_PREAMBLE_HE_ER_SU ,
ns3::WIFI_PREAMBLE_HE_MU , ns3::WIFI_PREAMBLE_HE_TB
}
The type of preamble to be used by an IEEE 802.11 transmission.
enum ns3::WifiStandard {
ns3::WIFI_STANDARD_80211a , ns3::WIFI_STANDARD_80211b , ns3::WIFI_STANDARD_80211g , ns3::WIFI_STANDARD_80211p ,
ns3::WIFI_STANDARD_holland , ns3::WIFI_STANDARD_80211n_2_4GHZ , ns3::WIFI_STANDARD_80211n_5GHZ , ns3::WIFI_STANDARD_80211ac ,
ns3::WIFI_STANDARD_80211ax_2_4GHZ , ns3::WIFI_STANDARD_80211ax_5GHZ , ns3::WIFI_STANDARD_80211ax_6GHZ
}
Identifies the allowed configurations that a Wifi device is configured to use.
Functions
uint8_t ns3::GetTid (Ptr< const Packet > packet, const WifiMacHeader hdr)
Extraction operator for TypeId.
uint8_t ns3::QosUtilsGetTidForPacket (Ptr< const Packet > packet)
If a QoS tag is attached to the packet, returns a value < 8.
bool ns3::QosUtilsIsOldPacket (uint16_t startingSeq, uint16_t seqNumber)
This function checks if packet with sequence number seqNumber is an "old" packet.
uint32_t ns3::QosUtilsMapSeqControlToUniqueInteger (uint16_t seqControl, uint16_t endSequence)
Next function is useful to correctly sort buffered packets under block ack.
AcIndex ns3::QosUtilsMapTidToAc (uint8_t tid)
Maps TID (Traffic ID) to Access classes.
uint8_t ns3::SelectQueueByDSField (Ptr< QueueItem > item)
Determine the TX queue for a given packet.
Detailed Description
This section documents the API of the ns-3 Wifi module.
For a generic functional description, please refer to the ns-3 manual.
Enumeration Type Documentation
AcIndex
enum ns3::AcIndex
This enumeration defines the Access Categories as an enumeration with values corresponding to the AC index (ACI) values specified (Table 8-104 "ACI-to-AC coding"; IEEE 802.11-2012).
Enumerator
AC_BE
Best Effort.
AC_BK
Background.
AC_VI
Video.
AC_VO
Voice.
AC_BE_NQOS
Total number of ACs.
AC_UNDEF
Definition at line 38 of file qos-utils.h.
BlockAckType
enum ns3::BlockAckType
The different block ack policies.
Enumerator
BASIC_BLOCK_ACK
COMPRESSED_BLOCK_ACK
EXTENDED_COMPRESSED_BLOCK_ACK
MULTI_TID_BLOCK_ACK
Definition at line 30 of file block-ack-type.h.
MpduType
enum ns3::MpduType
The type of an MPDU.
Enumerator
NORMAL_MPDU
The MPDU is not part of an A-MPDU.
SINGLE_MPDU
The MPDU is a single MPDU.
FIRST_MPDU_IN_AGGREGATE
The MPDU is the first aggregate in an A-MPDU with multiple MPDUs, but is not the last aggregate.
MIDDLE_MPDU_IN_AGGREGATE
The MPDU is part of an A-MPDU with multiple MPDUs, but is neither the first nor the last aggregate.
LAST_MPDU_IN_AGGREGATE
The MPDU is the last aggregate in an A-MPDU with multiple MPDUs.
Definition at line 30 of file wifi-mpdu-type.h.
WifiMacStandard
enum ns3::WifiMacStandard
Identifies the MAC specification that a Wifi device is configured to use.
Enumerator
WIFI_MAC_STANDARD_80211
WIFI_MAC_STANDARD_80211n
WIFI_MAC_STANDARD_80211ac
WIFI_MAC_STANDARD_80211ax
Definition at line 108 of file wifi-standards.h.
WifiPhyBand
enum ns3::WifiPhyBand
Identifies the PHY band.
Enumerator
WIFI_PHY_BAND_2_4GHZ
The 2.4 GHz band.
WIFI_PHY_BAND_5GHZ
The 5 GHz band.
WIFI_PHY_BAND_6GHZ
The 6 GHz band.
WIFI_PHY_BAND_UNSPECIFIED
Unspecified.
Definition at line 30 of file wifi-phy-band.h.
WifiPhyStandard
enum ns3::WifiPhyStandard
Identifies the PHY specification that a Wifi device is configured to use.
Enumerator
WIFI_PHY_STANDARD_80211a
OFDM PHY (Clause 17)
WIFI_PHY_STANDARD_80211b
DSSS PHY (Clause 15) and HR/DSSS PHY (Clause 18)
WIFI_PHY_STANDARD_80211g
ERP-OFDM PHY (Clause 19, Section 19.5)
WIFI_PHY_STANDARD_80211_10MHZ
OFDM PHY for the 5 GHz band (Clause 17 with 10 MHz channel bandwidth)
this value is NS_DEPRECATED_3_32
WIFI_PHY_STANDARD_80211_5MHZ
OFDM PHY for the 5 GHz band (Clause 17 with 5 MHz channel bandwidth)
this value is NS_DEPRECATED_3_32
WIFI_PHY_STANDARD_80211p
OFDM PHY (Clause 17 - amendment for 10 MHz and 5 MHz channels)
WIFI_PHY_STANDARD_holland
This is intended to be the configuration used in this paper: Gavin Holland, Nitin Vaidya and Paramvir Bahl, "A Rate-Adaptive MAC Protocol for Multi-Hop Wireless Networks", in Proc.
of ACM MOBICOM, 2001.
WIFI_PHY_STANDARD_80211n_2_4GHZ
HT PHY for the 2.4 GHz band (clause 20)
this value is NS_DEPRECATED_3_32
WIFI_PHY_STANDARD_80211n_5GHZ
HT PHY for the 5 GHz band (clause 20)
this value is NS_DEPRECATED_3_32
WIFI_PHY_STANDARD_80211n
HT PHY (clause 20)
WIFI_PHY_STANDARD_80211ac
VHT PHY (clause 22)
WIFI_PHY_STANDARD_80211ax
HE PHY (clause 26)
WIFI_PHY_STANDARD_UNSPECIFIED
Unspecified.
Definition at line 33 of file wifi-standards.h.
WifiPreamble
enum ns3::WifiPreamble
The type of preamble to be used by an IEEE 802.11 transmission.
Enumerator
WIFI_PREAMBLE_LONG
WIFI_PREAMBLE_SHORT
WIFI_PREAMBLE_HT_MF
WIFI_PREAMBLE_HT_GF
WIFI_PREAMBLE_VHT_SU
WIFI_PREAMBLE_VHT_MU
WIFI_PREAMBLE_HE_SU
WIFI_PREAMBLE_HE_ER_SU
WIFI_PREAMBLE_HE_MU
WIFI_PREAMBLE_HE_TB
Definition at line 32 of file wifi-preamble.h.
WifiStandard
enum ns3::WifiStandard
Identifies the allowed configurations that a Wifi device is configured to use.
Enumerator
WIFI_STANDARD_80211a
WIFI_STANDARD_80211b
WIFI_STANDARD_80211g
WIFI_STANDARD_80211p
WIFI_STANDARD_holland
WIFI_STANDARD_80211n_2_4GHZ
WIFI_STANDARD_80211n_5GHZ
WIFI_STANDARD_80211ac
WIFI_STANDARD_80211ax_2_4GHZ
WIFI_STANDARD_80211ax_5GHZ
WIFI_STANDARD_80211ax_6GHZ
Definition at line 144 of file wifi-standards.h.
Function Documentation
GetTid()
uint8_t ns3::GetTid (Ptr< const Packet > packet, const WifiMacHeader hdr)
Extraction operator for TypeId.
Next function is useful to get traffic id of different packet types.
Parameters
[in] packet is the packet
[in] hdr is Wifi MAC header
Returns
the TypeId of the MAC header
Parameters
packet packet to check
hdr 802.11 header for packet to check
Returns TID of different packet types
Definition at line 99 of file qos-utils.cc.
References ns3::WifiActionHeader::BLOCK_ACK, ns3::WifiActionHeader::BLOCK_ACK_ADDBA_REQUEST, ns3::WifiActionHeader::BLOCK_ACK_ADDBA_RESPONSE, ns3::WifiActionHeader::BLOCK_ACK_DELBA, ns3::WifiActionHeader::ActionValue::blockAck, ns3::WifiActionHeader::GetAction(), ns3::WifiActionHeader::GetCategory(), ns3::WifiMacHeader::GetQosTid(), ns3::MgtAddBaRequestHeader::GetTid(), ns3::MgtAddBaResponseHeader::GetTid(), ns3::MgtDelBaHeader::GetTid(), ns3::CtrlBAckRequestHeader::GetTidInfo(), ns3::CtrlBAckResponseHeader::GetTidInfo(), ns3::WifiMacHeader::IsAction(), ns3::WifiMacHeader::IsBlockAck(), ns3::WifiMacHeader::IsBlockAckReq(), ns3::WifiMacHeader::IsMgt(), ns3::WifiMacHeader::IsQosData(), NS_ASSERT, NS_FATAL_ERROR, and ns3::Packet::RemoveHeader().
Referenced by ns3::MpduAggregator::GetNextAmpdu(), ns3::QosTxop::MissedAck(), ns3::QosTxop::MissedBlockAck(), and ns3::QosTxop::NeedFragmentation().
QosUtilsGetTidForPacket()
uint8_t ns3::QosUtilsGetTidForPacket (Ptr< const Packet > packet)
If a QoS tag is attached to the packet, returns a value < 8.
A value >= 8 is returned otherwise.
Parameters
packet the packet to checked for a QoS tag
Returns
a value less than 8 if QoS tag was present, a value >= 8 is returned if no QoS tag was present
Definition at line 58 of file qos-utils.cc.
References ns3::SocketPriorityTag::GetPriority().
Referenced by ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::StaWifiMac::Enqueue(), ns3::ApWifiMac::ForwardDown(), and ns3::OcbWifiMac::SendVsc().
QosUtilsIsOldPacket()
bool ns3::QosUtilsIsOldPacket (uint16_t startingSeq, uint16_t seqNumber)
This function checks if packet with sequence number seqNumber is an "old" packet.
The sequence number space is considered divided into two parts, one of which is "old" and one of which is "new" by means of a boundary created by adding half the sequence number range to the starting sequence number startingSeq. So this function works fine also when seqNumber is smaller than startingSeq and startingSeq + 2048 is greater than 4096 because all comparison are circular modulo 2^12. The following are possible scenarios:
--— = old packets +++++ = new packets
CASE A:
0 4095 |++++++|-------------—|++++++| ^ ^ | endSeq | startingSeq
CASE B:
0 4095 |---—|++++++++++++++++|--—| ^ ^ | startingSeq | endSeq
Here in the examples endSeq is the sequenceNumber of the "last" new packet. So this function, when specified a starting sequence and a sequence number, returns true if that packet (with sequence number numberSeq)) belongs to the section of the sequence number space marked with '-' characters. The function returns false otherwise.
Parameters
startingSeq the starting sequence number
seqNumber the sequence number to be checked
Returns
true if the packet is old, false otherwise
Definition at line 84 of file qos-utils.cc.
References NS_ASSERT.
Referenced by ns3::QosTxop::DequeuePeekedFrame(), QosUtilsIsOldPacketTest::DoRun(), ns3::WifiPsdu::GetMaxDistFromStartingSeq(), ns3::QosTxop::IsQosOldPacket(), ns3::BlockAckManager::NotifyDiscardedMpdu(), ns3::BlockAckManager::NotifyGotBlockAck(), ns3::MacLow::ReceiveMpdu(), ns3::MacLow::SendBlockAckAfterBlockAckRequest(), ns3::BlockAckCache::UpdateWithBlockAckReq(), and ns3::BlockAckCache::UpdateWithMpdu().
QosUtilsMapSeqControlToUniqueInteger()
uint32_t ns3::QosUtilsMapSeqControlToUniqueInteger (uint16_t seqControl, uint16_t endSequence)
Next function is useful to correctly sort buffered packets under block ack.
When an BAR is received from originator station, completed "old" (see section 9.10.3 in IEEE 802.11e) packets must be forwarded up before "new" packets.
Parameters
seqControl the sequence control field
endSequence the sequence number ending the acknowledgment window
Returns
a unique integer for the given sequence control and end sequence
Definition at line 73 of file qos-utils.cc.
Referenced by PacketBufferingCaseA::DoRun(), PacketBufferingCaseB::DoRun(), ns3::MacLow::RxCompleteBufferedPacketsWithSmallerSequence(), and ns3::MacLow::StoreMpduIfNeeded().
QosUtilsMapTidToAc()
AcIndex ns3::QosUtilsMapTidToAc (uint8_t tid)
Maps TID (Traffic ID) to Access classes.
For more details see (Table 9-1 "UP-to-AC mapping"; IEEE 802.11-2012).
Parameters
tid the Traffic ID to be mapped to Access class
Returns
the access class for the given TID
Definition at line 32 of file qos-utils.cc.
References ns3::AC_BE, ns3::AC_BK, ns3::AC_UNDEF, ns3::AC_VI, ns3::AC_VO, and NS_ASSERT_MSG.
Referenced by ns3::MacLow::CreateBlockAckAgreement(), ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::StaWifiMac::Enqueue(), ns3::MacLow::ForwardDown(), ns3::MeshWifiInterfaceMac::ForwardDown(), ns3::ApWifiMac::ForwardDown(), ns3::MacLow::GetEdca(), ns3::MpduAggregator::GetMaxAmpduSize(), ns3::MsduAggregator::GetMaxAmsduSize(), ns3::MpduAggregator::GetNextAmpdu(), ns3::MsduAggregator::GetNextAmsdu(), ns3::WifiRemoteStationManager::NeedRetransmission(), ns3::RegularWifiMac::Receive(), ns3::MacLow::ReceiveOk(), ns3::WifiRemoteStationManager::ReportDataFailed(), ns3::WifiRemoteStationManager::ReportDataOk(), ns3::WifiRemoteStationManager::ReportFinalDataFailed(), ns3::WifiRemoteStationManager::ReportFinalRtsFailed(), ns3::WifiRemoteStationManager::ReportRtsFailed(), ns3::WifiRemoteStationManager::ReportRtsOk(), ns3::MacLow::ResetBlockAckInactivityTimerIfNeeded(), ns3::SelectQueueByDSField(), ns3::RegularWifiMac::SendAddBaResponse(), ns3::OcbWifiMac::SendVsc(), and ns3::MacLow::StartTransmission().
SelectQueueByDSField()
uint8_t ns3::SelectQueueByDSField (Ptr< QueueItem > item)
Determine the TX queue for a given packet.
Parameters
item the packet
Returns
the access category
Modeled after the Linux function ieee80211_select_queue (net/mac80211/wme.c). A SocketPriority tag is attached to the packet (or the existing one is replaced) to carry the user priority, which is set to the three most significant bits of the DS field (TOS field in case of IPv4 and Traffic Class field in case of IPv6). The Access Category corresponding to the user priority according to the QosUtilsMapTidToAc function is returned.
The following table shows the mapping for the Diffserv Per Hop Behaviors.
PHB TOS (binary) UP Access Category
EF 101110xx 5 AC_VI
AF11 001010xx 1 AC_BK
AF21 010010xx 2 AC_BK
AF31 011010xx 3 AC_BE
AF41 100010xx 4 AC_VI
AF12 001100xx 1 AC_BK
AF22 010100xx 2 AC_BK
AF32 011100xx 3 AC_BE
AF42 100100xx 4 AC_VI
AF13 001110xx 1 AC_BK
AF23 010110xx 2 AC_BK
AF33 011110xx 3 AC_BE
AF43 100110xx 4 AC_VI
CS0 000000xx 0 AC_BE
CS1 001000xx 1 AC_BK
CS2 010000xx 2 AC_BK
CS3 011000xx 3 AC_BE
CS4 100000xx 4 AC_VI
CS5 101000xx 5 AC_VI
CS6 110000xx 6 AC_VO
CS7 111000xx 7 AC_VO
This method is called by the traffic control layer before enqueuing a packet in the queue disc, if a queue disc is installed on the outgoing device, or passing a packet to the device, otherwise.
Definition at line 164 of file qos-utils.cc.
References ns3::QueueItem::IP_DSFIELD, ns3::QosUtilsMapTidToAc(), and ns3::SocketPriorityTag::SetPriority().