ns-3: Time Attribute
Time Attribute
Attribute implementation for Time.
Classes
class TimeChecker
AttributeChecker implementation for TimeValue.
class ns3::TimeValue
AttributeValue implementation for Time.
Functions
template<typename T1 >
Ptr< const AttributeAccessor > ns3::MakeTimeAccessor (T1 a1)
Create an AttributeAccessor for a class data member, or a lone class get functor or set method.
template<typename T1 , typename T2 >
Ptr< const AttributeAccessor > ns3::MakeTimeAccessor (T1 a1, T2 a2)
Create an AttributeAccessor using a pair of get functor and set methods from a class.
Ptr< const AttributeChecker > ns3::MakeTimeChecker (void)
Helper to make an unbounded Time checker.
Detailed Description
Attribute implementation for Time.
See also
ns3::Time
Function Documentation
MakeTimeAccessor() [1/2]
template<typename T1 > ns3::Ptr< const ns3::AttributeAccessor > ns3::MakeTimeAccessor (T1 a1)
Create an AttributeAccessor for a class data member, or a lone class get functor or set method.
The get functor method should have a signature like
typedef U (T::*getter)(void) const
where T is the class and U is the type of the return value.
The set method should have one of these signatures:
typedef void (T::*setter)(U)
typedef bool (T::*setter)(U)
where T is the class and U is the type of the value to set the attribute to, which should be compatible with the specific AttributeValue type V which holds the value (or the type implied by the name Make<V>Accessor of this function.) In the case of a setter returning bool, the return value should be true if the value could be set successfully.
Template Parameters
V [explicit] (If present) The specific AttributeValue type to use to represent the Attribute. (If not present, the type V is implicit in the name of this function, as "Make<V>Accessor"
T1 [deduced] The type of the class data member, or the type of the class get functor or set method.
Parameters
[in] a1 The address of the data member, or the get or set method.
Returns
The AttributeAccessor
See also
AttributeAccessor
Definition at line 1354 of file nstime.h.
Referenced by ns3::ThreeGppHttpVariables::GetTypeId(), ns3::dsr::DsrRouting::GetTypeId(), ns3::FlowMonitor::GetTypeId(), ns3::Ping6::GetTypeId(), ns3::Icmpv6L4Protocol::GetTypeId(), ns3::Ipv6ExtensionFragment::GetTypeId(), ns3::Ipv6PmtuCache::GetTypeId(), ns3::A3RsrpHandoverAlgorithm::GetTypeId(), ns3::LteFfrDistributedAlgorithm::GetTypeId(), ns3::dot11s::HwmpProtocol::GetTypeId(), ns3::dot11s::PeerLink::GetTypeId(), ns3::flame::FlameProtocol::GetTypeId(), ns3::flame::FlameRtable::GetTypeId(), ns3::MeshWifiInterfaceMac::GetTypeId(), ns3::ThreeGppChannelModel::GetTypeId(), ns3::TraceFadingLossModel::GetTypeId(), ns3::Probe::GetTypeId(), TimestampTag::GetTypeId(), ns3::aodv::RoutingProtocol::GetTypeId(), ns3::UdpClient::GetTypeId(), ns3::UdpEchoClient::GetTypeId(), ns3::BridgeNetDevice::GetTypeId(), ns3::RandomWalk2dOutdoorMobilityModel::GetTypeId(), ns3::RealtimeSimulatorImpl::GetTypeId(), AttributeObjectTest::GetTypeId(), ns3::CsmaChannel::GetTypeId(), ns3::dsdv::RoutingProtocol::GetTypeId(), ns3::BasicEnergyHarvester::GetTypeId(), ns3::BasicEnergySource::GetTypeId(), ns3::LiIonEnergySource::GetTypeId(), ns3::RvBatteryModel::GetTypeId(), ns3::DpdkNetDevice::GetTypeId(), ns3::FdNetDevice::GetTypeId(), ns3::DhcpClient::GetTypeId(), ns3::DhcpServer::GetTypeId(), ns3::V4Ping::GetTypeId(), ns3::V4TraceRoute::GetTypeId(), ns3::ArpCache::GetTypeId(), ns3::Ipv4L3Protocol::GetTypeId(), ns3::Rip::GetTypeId(), ns3::RipNg::GetTypeId(), ns3::RttEstimator::GetTypeId(), ns3::TcpCubic::GetTypeId(), ns3::TcpHtcp::GetTypeId(), ns3::TcpHybla::GetTypeId(), ns3::TcpLedbat::GetTypeId(), ns3::TcpSocketBase::GetTypeId(), ns3::TcpSocket::GetTypeId(), ns3::NoBackhaulEpcHelper::GetTypeId(), ns3::PointToPointEpcHelper::GetTypeId(), ns3::RadioBearerStatsCalculator::GetTypeId(), ns3::LteEnbRrc::GetTypeId(), ns3::LteRlcAm::GetTypeId(), ns3::LteRlcUm::GetTypeId(), ns3::LteUePhy::GetTypeId(), ns3::LteUeRrc::GetTypeId(), EpsBearerTagUdpClient::GetTypeId(), ns3::GaussMarkovMobilityModel::GetTypeId(), ns3::RandomWalk2dMobilityModel::GetTypeId(), ns3::DelayJitterEstimationTimestampTag::GetTypeId(), ns3::Application::GetTypeId(), ns3::DynamicQueueLimits::GetTypeId(), ns3::PacketSocketClient::GetTypeId(), ns3::SimpleChannel::GetTypeId(), ns3::olsr::RoutingProtocol::GetTypeId(), ns3::PointToPointChannel::GetTypeId(), ns3::PointToPointNetDevice::GetTypeId(), ns3::ThreeGppChannelConditionModel::GetTypeId(), ns3::SixLowPanNetDevice::GetTypeId(), ns3::SpectrumAnalyzer::GetTypeId(), ns3::TvSpectrumTransmitter::GetTypeId(), ns3::WaveformGenerator::GetTypeId(), ns3::TapBridge::GetTypeId(), ns3::CobaltQueueDisc::GetTypeId(), ns3::CoDelQueueDisc::GetTypeId(), ns3::FqCoDelQueueDisc::GetTypeId(), ns3::PieQueueDisc::GetTypeId(), ns3::RedQueueDisc::GetTypeId(), ns3::UanMacCw::GetTypeId(), ns3::UanMacRcGw::GetTypeId(), ns3::UanMacRc::GetTypeId(), ns3::ChannelCoordinator::GetTypeId(), ns3::AthstatsWifiTraceSink::GetTypeId(), ns3::AmrrWifiManager::GetTypeId(), ns3::ApWifiMac::GetTypeId(), ns3::FrameCaptureModel::GetTypeId(), ns3::HeConfiguration::GetTypeId(), ns3::MinstrelHtWifiManager::GetTypeId(), ns3::MinstrelWifiManager::GetTypeId(), ns3::OnoeWifiManager::GetTypeId(), ns3::QosTxop::GetTypeId(), ns3::RraaWifiManager::GetTypeId(), ns3::RrpaaWifiManager::GetTypeId(), ns3::StaWifiMac::GetTypeId(), ns3::Txop::GetTypeId(), ns3::WifiMacQueue::GetTypeId(), ns3::WifiPhy::GetTypeId(), ns3::BaseStationNetDevice::GetTypeId(), ns3::UplinkSchedulerMBQoS::GetTypeId(), ns3::SubscriberStationNetDevice::GetTypeId(), and ns3::WimaxPhy::GetTypeId().
MakeTimeAccessor() [2/2]
template<typename T1 , typename T2 > ns3::Ptr< const ns3::AttributeAccessor > ns3::MakeTimeAccessor (T1 a1, T2 a2)
Create an AttributeAccessor using a pair of get functor and set methods from a class.
The get functor method should have a signature like
typedef U (T::*getter)(void) const
where T is the class and U is the type of the return value.
The set method should have one of these signatures:
typedef void (T::*setter)(U)
typedef bool (T::*setter)(U)
where T is the class and U is the type of the value to set the attribute to, which should be compatible with the specific AttributeValue type V which holds the value (or the type implied by the name Make<V>Accessor of this function.) In the case of a setter returning bool, the return value should be true if the value could be set successfully.
In practice the setter and getter arguments can appear in either order, but setter first is preferred.
Template Parameters
V [explicit] (If present) The specific AttributeValue type to use to represent the Attribute. (If not present, the type V is implicit in the name of this function as "Make<V>Accessor"
T1 [deduced] The type of the class data member, or the type of the class get functor or set method.
T2 [deduced] The type of the getter class functor method.
Parameters
[in] a2 The address of the class method to set the attribute.
[in] a1 The address of the data member, or the get or set method.
Returns
The AttributeAccessor
See also
AttributeAccessor
Definition at line 1354 of file nstime.h.
MakeTimeChecker()
ns3::Ptr< const ns3::AttributeChecker > ns3::MakeTimeChecker (void) inline
Helper to make an unbounded Time checker.
Returns
The AttributeChecker
The AttributeChecker.
See also
AttributeChecker
Definition at line 1374 of file nstime.h.
References ns3::MakeTimeChecker(), ns3::Time::Max(), and ns3::Time::Min().