ns-3: Spectrum Models
Spectrum Models
Classes
class ns3::AdhocAlohaNoackIdealPhyHelper
create the AlohaNoackNetDevice
class ns3::AlohaNoackMacHeader
Header for the AlohaNoack NetDevice.
class ns3::AlohaNoackNetDevice
This devices implements the following features:
struct ns3::BandInfo
The building block of a SpectrumModel.
class ns3::ConstantSpectrumPropagationLossModel
A Constant (fixed) propagation loss.
class ns3::FriisSpectrumPropagationLossModel
Friis spectrum propagation loss model.
class GlobalPathlossDatabase
Store the last pathloss value for each TX-RX pair.
class ns3::HalfDuplexIdealPhy
This PHY layer implementation realizes an ideal OFDM PHY which transmits half-duplex (i.e., it can either receive or transmit at a given time).
struct ns3::HalfDuplexIdealPhySignalParameters
Signal parameters for HalfDuplexIdealPhy.
class ns3::MatrixBasedChannelModel
This is an interface for a channel model that can be described by a channel matrix, e.g., the 3GPP Spatial Channel Models, which is generally used in combination with antenna arrays.
class ns3::MicrowaveOvenSpectrumModel5MhzInitializer
Init a static class containing the MWO #2 model (5Mhz)
class ns3::MicrowaveOvenSpectrumModel6MhzInitializer
Init a static class containing the MWO #1 model (6Mhz)
class ns3::MicrowaveOvenSpectrumValueHelper
This class provides methods for the creation of SpectrumValue instances that mimic the Power Spectral Density of commercial microwave ovens based on the measurements reported in the following paper: Tanim M.
class ns3::MultiModelSpectrumChannel
This SpectrumChannel implementation can handle the presence of SpectrumPhy instances which can use different spectrum models, i.e., different SpectrumModel.
class ns3::NonCommunicatingNetDevice
This class implements a device which does not communicate, in the sense that it does not interact with the above protocol stack.
class ns3::RxSpectrumModelInfo
The Rx spectrum model information.
class ns3::ShannonSpectrumErrorModel
This class implements the error model described in this paper: N.
class ns3::SingleModelSpectrumChannel
SpectrumChannel implementation which handles a single spectrum model.
class ns3::SpectrumAnalyzer
Simple SpectrumPhy implementation that averages the spectrum power density of incoming transmissions to produce a spectrogram.
class ns3::SpectrumAnalyzerHelper
Class to allow the Spectrum Analysis.
class ns3::SpectrumChannel
Defines the interface for spectrum-aware channel implementations.
class ns3::SpectrumChannelHelper
Setup a SpectrumChannel.
class ns3::SpectrumConverter
Class which implements a converter between SpectrumValue which are defined over different SpectrumModel.
class ns3::SpectrumErrorModel
Introspection did not find any typical Config paths.
class ns3::SpectrumInterference
This class implements a gaussian interference model, i.e., all incoming signals are added to the total interference.
class ns3::SpectrumPhy
Abstract base class for Spectrum-aware PHY layers.
class ns3::SpectrumPhyHelper
Create and configure several SpectrumPhy instances and connect them to a channel.
class ns3::SpectrumPropagationLossModel
spectrum-aware propagation loss model
struct ns3::SpectrumSignalParameters
This struct provides the generic signal representation to be used by all wireless technologies.
class ns3::SpectrumValue
Set of values corresponding to a given SpectrumModel.
class ns3::ThreeGppChannelModel
Channel Matrix Generation following 3GPP TR 38.901.
class ThreeGppChannelTestSuite
Test suite for the ThreeGppChannelModel class.
class ns3::ThreeGppSpectrumPropagationLossModel
3GPP Spectrum Propagation Loss Model
class ns3::TraceFadingLossModel
fading loss model based on precalculated fading traces
class ns3::TvSpectrumTransmitter
SpectrumPhy implementation that creates a customizable TV transmitter which transmits a PSD spectrum specified by user-set attributes.
class ns3::TvSpectrumTransmitterHelper
Helper class which uses TvSpectrumTransmitter class to create customizable TV transmitter(s) that transmit PSD spectrum specified by user-set attributes.
class ns3::TxSpectrumModelInfo
The Tx spectrum model information.
class ns3::WaveformGenerator
Simple SpectrumPhy implementation that sends customizable waveform.
class ns3::WaveformGeneratorHelper
Create a Waveform generator, which can be used to inject specific noise in the channel.
class ns3::WifiSpectrumValue5MhzFactory
Implements Wifi SpectrumValue for the 2.4 GHz ISM band only, with a 5 MHz spectrum resolution.
class ns3::WifiSpectrumValueHelper
This class defines all functions to create a spectrum model for Wi-Fi based on a a spectral model aligned with an OFDM subcarrier spacing of 312.5 KHz (model also reused for DSSS modulations)
Typedefs
typedef std::map< SpectrumModelUid_t, RxSpectrumModelInfo > ns3::RxSpectrumModelInfoMap_t
Container: SpectrumModelUid_t, RxSpectrumModelInfo.
typedef std::map< SpectrumModelUid_t, SpectrumConverter > ns3::SpectrumConverterMap_t
Container: SpectrumModelUid_t, SpectrumConverter.
typedef std::map< SpectrumModelUid_t, TxSpectrumModelInfo > ns3::TxSpectrumModelInfoMap_t
Container: SpectrumModelUid_t, TxSpectrumModelInfo.
Functions
static void ns3::WriteAveragePowerSpectralDensityReport (Ptr< OutputStreamWrapper > streamWrapper, Ptr< const SpectrumValue > avgPowerSpectralDensity)
Writes a report of the Average Power Spectral Density.
Variables
static class ns3::MicrowaveOvenSpectrumModel5MhzInitializer ns3::g_MicrowaveOvenSpectrumModel5MhzInitializerInstance
MWO model #2.
static class ns3::MicrowaveOvenSpectrumModel6MhzInitializer ns3::g_MicrowaveOvenSpectrumModel6MhzInitializerInstance
MWO model #1.
Detailed Description
Typedef Documentation
RxSpectrumModelInfoMap_t
typedef std::map<SpectrumModelUid_t, RxSpectrumModelInfo> ns3::RxSpectrumModelInfoMap_t
Container: SpectrumModelUid_t, RxSpectrumModelInfo.
Definition at line 90 of file multi-model-spectrum-channel.h.
SpectrumConverterMap_t
typedef std::map<SpectrumModelUid_t, SpectrumConverter> ns3::SpectrumConverterMap_t
Container: SpectrumModelUid_t, SpectrumConverter.
Definition at line 40 of file multi-model-spectrum-channel.h.
TxSpectrumModelInfoMap_t
typedef std::map<SpectrumModelUid_t, TxSpectrumModelInfo> ns3::TxSpectrumModelInfoMap_t
Container: SpectrumModelUid_t, TxSpectrumModelInfo.
Definition at line 65 of file multi-model-spectrum-channel.h.
Function Documentation
WriteAveragePowerSpectralDensityReport()
static void ns3::WriteAveragePowerSpectralDensityReport (Ptr< OutputStreamWrapper > streamWrapper, Ptr< const SpectrumValue > avgPowerSpectralDensity) static
Writes a report of the Average Power Spectral Density.
Parameters
streamWrapper the wrapper to the output stream
avgPowerSpectralDensity Average Power Spectral Density
Definition at line 49 of file spectrum-analyzer-helper.cc.
References ns3::Time::GetSeconds(), ns3::OutputStreamWrapper::GetStream(), ns3::Now(), NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::SpectrumAnalyzerHelper::Install().
Variable Documentation
g_MicrowaveOvenSpectrumModel5MhzInitializerInstance
class ns3::MicrowaveOvenSpectrumModel5MhzInitializer ns3::g_MicrowaveOvenSpectrumModel5MhzInitializerInstance static
MWO model #2.
g_MicrowaveOvenSpectrumModel6MhzInitializerInstance
class ns3::MicrowaveOvenSpectrumModel6MhzInitializer ns3::g_MicrowaveOvenSpectrumModel6MhzInitializerInstance static
MWO model #1.