ns-3: TypeId Attribute
TypeId Attribute
Attribute implementation for TypeId.
Classes
class ns3::TypeIdChecker
AttributeChecker implementation for TypeIdValue.
class ns3::TypeIdValue
AttributeValue implementation for TypeId.
Functions
template<typename T1 >
Ptr< const AttributeAccessor > ns3::MakeTypeIdAccessor (T1 a1)
Create an AttributeAccessor for a class data member, or a lone class get functor or set method.
template<typename T1 , typename T2 >
Ptr< const AttributeAccessor > ns3::MakeTypeIdAccessor (T1 a1, T2 a2)
Create an AttributeAccessor using a pair of get functor and set methods from a class.
Ptr< const AttributeChecker > ns3::MakeTypeIdChecker (void)
Detailed Description
Attribute implementation for TypeId.
See also
ns3::TypeId
Function Documentation
MakeTypeIdAccessor() [1/2]
template<typename T1 > ns3::Ptr< const ns3::AttributeAccessor > ns3::MakeTypeIdAccessor (T1 a1)
Create an AttributeAccessor for a class data member, or a lone class get functor or set method.
The get functor method should have a signature like
typedef U (T::*getter)(void) const
where T is the class and U is the type of the return value.
The set method should have one of these signatures:
typedef void (T::*setter)(U)
typedef bool (T::*setter)(U)
where T is the class and U is the type of the value to set the attribute to, which should be compatible with the specific AttributeValue type V which holds the value (or the type implied by the name Make<V>Accessor of this function.) In the case of a setter returning bool, the return value should be true if the value could be set successfully.
Template Parameters
V [explicit] (If present) The specific AttributeValue type to use to represent the Attribute. (If not present, the type V is implicit in the name of this function, as "Make<V>Accessor"
T1 [deduced] The type of the class data member, or the type of the class get functor or set method.
Parameters
[in] a1 The address of the data member, or the get or set method.
Returns
The AttributeAccessor
See also
AttributeAccessor
Definition at line 595 of file type-id.h.
Referenced by ns3::BulkSendApplication::GetTypeId(), ns3::OnOffApplication::GetTypeId(), ns3::PacketSink::GetTypeId(), ns3::TcpL4Protocol::GetTypeId(), ns3::LteHelper::GetTypeId(), and ns3::NetDeviceQueueInterface::GetTypeId().
MakeTypeIdAccessor() [2/2]
template<typename T1 , typename T2 > ns3::Ptr< const ns3::AttributeAccessor > ns3::MakeTypeIdAccessor (T1 a1, T2 a2)
Create an AttributeAccessor using a pair of get functor and set methods from a class.
The get functor method should have a signature like
typedef U (T::*getter)(void) const
where T is the class and U is the type of the return value.
The set method should have one of these signatures:
typedef void (T::*setter)(U)
typedef bool (T::*setter)(U)
where T is the class and U is the type of the value to set the attribute to, which should be compatible with the specific AttributeValue type V which holds the value (or the type implied by the name Make<V>Accessor of this function.) In the case of a setter returning bool, the return value should be true if the value could be set successfully.
In practice the setter and getter arguments can appear in either order, but setter first is preferred.
Template Parameters
V [explicit] (If present) The specific AttributeValue type to use to represent the Attribute. (If not present, the type V is implicit in the name of this function as "Make<V>Accessor"
T1 [deduced] The type of the class data member, or the type of the class get functor or set method.
T2 [deduced] The type of the getter class functor method.
Parameters
[in] a2 The address of the class method to set the attribute.
[in] a1 The address of the data member, or the get or set method.
Returns
The AttributeAccessor
See also
AttributeAccessor
Definition at line 595 of file type-id.h.
MakeTypeIdChecker()
ns3::Ptr< const ns3::AttributeChecker > ns3::MakeTypeIdChecker (void)
Returns
The AttributeChecker.
See also
AttributeChecker
Definition at line 1227 of file type-id.cc.
Referenced by ns3::BulkSendApplication::GetTypeId(), ns3::OnOffApplication::GetTypeId(), ns3::PacketSink::GetTypeId(), ns3::TcpL4Protocol::GetTypeId(), ns3::LteHelper::GetTypeId(), and ns3::NetDeviceQueueInterface::GetTypeId().