ns-3: Configuration
Configuration
Core
Configuration of simulation parameters and tracing.
Files
file config-test-suite.cc
Config test suite.
file config.cc
ns3::Config implementations.
file config.h
Declaration of the various ns3::Config functions and classes.
file names-test-suite.cc
Object Names test suite.
file names.cc
ns3::Names, ns3::NamesNode and ns3::NamePriv implementations.
file names.h
Declaration of class ns3::Names.
Classes
class ns3::Config::MatchContainer
hold a set of objects which match a specific search string.
class ns3::NameNode
Node in the naming tree.
class ns3::Names
A directory of name and Ptr<Object> associations that allows us to give any ns3 Object a name.
class ns3::NamesPriv
The singleton root Names object.
Functions
void ns3::Config::Connect (std::string path, const CallbackBase &cb)
void ns3::Config::ConnectWithoutContext (std::string path, const CallbackBase &cb)
void ns3::Config::Disconnect (std::string path, const CallbackBase &cb)
void ns3::Config::DisconnectWithoutContext (std::string path, const CallbackBase &cb)
Ptr< Object > ns3::Config::GetRootNamespaceObject (uint32_t i)
std::size_t ns3::Config::GetRootNamespaceObjectN (void)
MatchContainer ns3::Config::LookupMatches (std::string path)
void ns3::Config::RegisterRootNamespaceObject (Ptr< Object > obj)
void ns3::Config::Reset (void)
Reset the initial value of every attribute as well as the value of every global to what they were before any call to SetDefault and SetGlobal.
void ns3::Config::Set (std::string path, const AttributeValue &value)
void ns3::Config::SetDefault (std::string name, const AttributeValue &value)
bool ns3::Config::SetDefaultFailSafe (std::string name, const AttributeValue &value)
void ns3::Config::SetGlobal (std::string name, const AttributeValue &value)
bool ns3::Config::SetGlobalFailSafe (std::string name, const AttributeValue &value)
void ns3::Config::UnregisterRootNamespaceObject (Ptr< Object > obj)
Detailed Description
Configuration of simulation parameters and tracing.
Function Documentation
Connect()
void ns3::Config::Connect (std::string path, const CallbackBase & cb)
Parameters
[in] path A path to match trace sources.
[in] cb The callback to connect to the matching trace sources.
This function will attempt to find all trace sources which match the input path and will then connect the input callback to them in such a way that the callback will receive an extra context string upon trace event notification. If no matching trace sources are found, this method will throw a fatal error. Use ConnectFailSafe if the absence of matching trace sources should not be fatal.
Definition at line 918 of file config.cc.
References ns3::Config::ConnectFailSafe(), NS_FATAL_ERROR, and NS_LOG_FUNCTION.
Referenced by ns3::LteHelper::ActivateDataRadioBearer(), VanetRoutingExperiment::ConfigureApplications(), VanetRoutingExperiment::ConfigureDevices(), ns3::RadioBearerStatsConnector::ConnectTracesDrbEnb(), ns3::RadioBearerStatsConnector::ConnectTracesDrbUe(), ns3::RadioBearerStatsConnector::ConnectTracesSrb0(), ns3::RadioBearerStatsConnector::ConnectTracesSrb1(), ns3::DoMakeTraceSourceAccessor(), LteCellSelectionTestCase::DoRun(), LteRadioLinkFailureTestCase::DoRun(), LteUeMeasurementsPiecewiseTestCase1::DoRun(), LteUeMeasurementsPiecewiseTestCase2::DoRun(), LteUeMeasurementsPiecewiseTestCase3::DoRun(), LteUeMeasurementsHandoverTestCase::DoRun(), LteHandoverTargetTestCase::DoRun(), Ns2MobilityHelperTest::DoRun(), ns3::tests::ObjectVectorTraceConfigTestCase::DoRun(), CarrierAggregationConfigTestCase::DoRun(), CarrierAggregationTestCase::DoRun(), LteCqiGenerationTestCase::DoRun(), LteCqiGenerationDlPowerControlTestCase::DoRun(), LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::DoRun(), LteInterferenceTestCase::DoRun(), LteLinkAdaptationTestCase::DoRun(), LteUeMeasurementsTestCase::DoRun(), LteEnbAntennaTestCase::DoRun(), LteHandoverDelayTestCase::DoRun(), LteRrcConnectionEstablishmentTestCase::DoRun(), LteRrcConnectionEstablishmentErrorTestCase::DoRun(), SpectrumIdealPhyTestCase::DoRun(), CsmaPacketSocketTestCase::DoRun(), CsmaPingTestCase::DoRun(), Ns3TcpInteroperabilityTestCase::DoRun(), Ns3TcpLossTestCase::DoRun(), Ns3TcpNoDelayTestCase::DoRun(), Ns3TcpSocketTestCase1::DoRun(), Ns3TcpSocketTestCase2::DoRun(), Ns3TcpStateTestCase::DoRun(), NscTcpLossTestCase1::DoRun(), NscTcpLossTestCase2::DoRun(), BlockAckAggregationDisabledTest::DoRun(), Bug730TestCase::DoRun(), QosFragmentationTestCase::DoRun(), Bug2222TestCase::DoRun(), Bug2843TestCase::DoRun(), Bug2831TestCase::DoRun(), Issue169TestCase::DoRun(), IdealRateManagerChannelWidthTest::DoRun(), IdealRateManagerMimoTest::DoRun(), ns3::UanHelper::EnableAscii(), ns3::WimaxHelper::EnableAsciiForConnection(), ns3::CsmaHelper::EnableAsciiInternal(), ns3::FdNetDeviceHelper::EnableAsciiInternal(), ns3::PointToPointHelper::EnableAsciiInternal(), ns3::YansWavePhyHelper::EnableAsciiInternal(), ns3::WifiPhyHelper::EnableAsciiInternal(), ns3::WimaxHelper::EnableAsciiInternal(), ns3::InternetStackHelper::EnableAsciiIpv4Internal(), ns3::InternetStackHelper::EnableAsciiIpv6Internal(), ns3::AthstatsHelper::EnableAthstats(), ns3::LteHelper::EnableDlMacTraces(), ns3::LteHelper::EnableDlPhyTraces(), ns3::LteHelper::EnableDlRxPhyTraces(), ns3::LteHelper::EnableDlTxPhyTraces(), ns3::LteHelper::EnableUlMacTraces(), ns3::LteHelper::EnableUlPhyTraces(), ns3::LteHelper::EnableUlRxPhyTraces(), ns3::LteHelper::EnableUlTxPhyTraces(), ns3::RadioBearerStatsConnector::EnsureConnected(), OcbWifiMacTestCase::PostDeviceConfiguration(), ns3::PyViz::RegisterCsmaLikeDevice(), ns3::PyViz::RegisterDropTracePath(), ns3::PyViz::RegisterPointToPointLikeDevice(), ns3::PyViz::RegisterWifiLikeDevice(), Experiment::Run(), TestInterBssConstantObssPdAlgo::RunOne(), Issue40TestCase::RunOne(), Bug2470TestCase::RunSubtest(), ns3::SubscriberStationNetDevice::SetBasicConnection(), ns3::SubscriberStationNetDevice::SetPrimaryConnection(), StaWifiMacScanningTestCase::Setup(), VanetRoutingExperiment::SetupAdhocMobilityNodes(), and ns3::RadioBearerStatsConnector::StoreUeManagerPath().
ConnectWithoutContext()
void ns3::Config::ConnectWithoutContext (std::string path, const CallbackBase & cb)
Parameters
[in] path A path to match trace sources.
[in] cb The callback to connect to the matching trace sources.
This function will attempt to find all trace sources which match the input path and will then connect the input callback to them. If no matching trace sources are found, this method will throw a fatal error. Use ConnectWithoutContextFailSafe if the absence of matching trace sources should not be fatal.
Definition at line 899 of file config.cc.
References ns3::Config::ConnectWithoutContextFailSafe(), NS_FATAL_ERROR, and NS_LOG_FUNCTION.
Referenced by ns3::ApplicationPacketProbe::ConnectByPath(), ns3::Ipv4PacketProbe::ConnectByPath(), ns3::Ipv6PacketProbe::ConnectByPath(), ns3::PacketProbe::ConnectByPath(), ns3::BooleanProbe::ConnectByPath(), ns3::DoubleProbe::ConnectByPath(), ns3::TimeProbe::ConnectByPath(), ns3::Uinteger16Probe::ConnectByPath(), ns3::Uinteger32Probe::ConnectByPath(), ns3::Uinteger8Probe::ConnectByPath(), ConnectSocketTraces(), ns3::DoMakeTraceSourceAccessor(), ns3::tests::ObjectVectorTraceConfigTestCase::DoRun(), Ipv4DeduplicationTest::DoRun(), CsmaBridgeTestCase::DoRun(), CsmaBroadcastTestCase::DoRun(), CsmaMulticastTestCase::DoRun(), CsmaOneSubnetTestCase::DoRun(), CsmaPingTestCase::DoRun(), CsmaRawIpSocketTestCase::DoRun(), CsmaStarTestCase::DoRun(), Ns3TcpLossTestCase::DoRun(), ns3::YansWavePhyHelper::EnableAsciiInternal(), ns3::WifiPhyHelper::EnableAsciiInternal(), ns3::SpectrumAnalyzerHelper::Install(), ScheduleN0PacketSinkConnection(), ScheduleN0TcpCwndTraceConnection(), ScheduleN0TcpRttTraceConnection(), ScheduleN1PacketSinkConnection(), ScheduleN1TcpCwndTraceConnection(), ScheduleN1TcpRttTraceConnection(), ScheduleSecondPacketSinkConnection(), ScheduleSecondTcpCwndTraceConnection(), ScheduleSecondTcpRttTraceConnection(), TraceCwnd(), TraceDroppingState(), TraceEveryDrop(), TraceInFlight(), TraceNextRx(), TraceNextTx(), TraceQueueLength(), TraceRto(), TraceRtt(), TraceSojourn(), and TraceSsThresh().
Disconnect()
void ns3::Config::Disconnect (std::string path, const CallbackBase & cb)
Parameters
[in] path A path to match trace sources.
[in] cb The callback to connect to the matching trace sources.
This function undoes the work of Config::ConnectWithContext.
Definition at line 933 of file config.cc.
References ns3::Config::ConfigImpl::Disconnect(), ns3::Singleton< ConfigImpl >::Get(), and NS_LOG_FUNCTION.
Referenced by ns3::DoMakeTraceSourceAccessor().
DisconnectWithoutContext()
void ns3::Config::DisconnectWithoutContext (std::string path, const CallbackBase & cb)
Parameters
[in] path A path to match trace sources.
[in] cb The callback to disconnect to the matching trace sources.
This function undoes the work of Config::Connect.
Definition at line 912 of file config.cc.
References ns3::Config::ConfigImpl::DisconnectWithoutContext(), ns3::Singleton< ConfigImpl >::Get(), and NS_LOG_FUNCTION.
Referenced by ns3::TracedCallback< Ts >::Disconnect(), and ns3::DoMakeTraceSourceAccessor().
GetRootNamespaceObject()
Ptr< Object > ns3::Config::GetRootNamespaceObject (uint32_t i)
Parameters
[in] i The index of the requested object.
Returns
The requested root namespace object
Definition at line 962 of file config.cc.
References ns3::Singleton< ConfigImpl >::Get(), ns3::Config::ConfigImpl::GetRootNamespaceObject(), and NS_LOG_FUNCTION.
Referenced by GetTypicalAggregations(), and ns3::AttributeIterator::Iterate().
GetRootNamespaceObjectN()
std::size_t ns3::Config::GetRootNamespaceObjectN (void)
Returns
The number of registered root namespace objects.
Definition at line 956 of file config.cc.
References ns3::Singleton< ConfigImpl >::Get(), ns3::Config::ConfigImpl::GetRootNamespaceObjectN(), and NS_LOG_FUNCTION_NOARGS.
Referenced by GetTypicalAggregations(), and ns3::AttributeIterator::Iterate().
LookupMatches()
MatchContainer ns3::Config::LookupMatches (std::string path)
Parameters
[in] path The path to perform a match against
Returns
A container which contains all the objects which match the input path.
Definition at line 938 of file config.cc.
References ns3::Singleton< ConfigImpl >::Get(), ns3::Config::ConfigImpl::LookupMatches(), and NS_LOG_FUNCTION.
Referenced by ns3::RandomVariableStreamHelper::AssignStreams(), ns3::LteStatsCalculator::FindCellIdFromEnbRlcPath(), ns3::LteStatsCalculator::FindImsiFromEnbRlcPath(), ns3::LteStatsCalculator::FindImsiFromLteNetDevice(), ns3::LteStatsCalculator::FindImsiFromUePhy(), ns3::RadioEnvironmentMapHelper::Install(), ns3::GnuplotHelper::PlotProbe(), and ns3::FileHelper::WriteProbe().
RegisterRootNamespaceObject()
void ns3::Config::RegisterRootNamespaceObject (Ptr< Object > obj)
Parameters
[in] obj A new root object
Each root object is used during path matching as the root of the path by Config::Connect, and Config::Set.
Definition at line 944 of file config.cc.
References ns3::Singleton< ConfigImpl >::Get(), NS_LOG_FUNCTION, and ns3::Config::ConfigImpl::RegisterRootNamespaceObject().
Referenced by ns3::BuildingListPriv::DoGet(), ns3::ChannelListPriv::DoGet(), ns3::NodeListPriv::DoGet(), ns3::tests::RootNamespaceConfigTestCase::DoRun(), ns3::tests::UnderRootNamespaceConfigTestCase::DoRun(), ns3::tests::ObjectVectorConfigTestCase::DoRun(), ns3::tests::ObjectVectorTraceConfigTestCase::DoRun(), and ns3::tests::SearchAttributesOfParentObjectsTestCase::DoRun().
Reset()
void ns3::Config::Reset (void)
Reset the initial value of every attribute as well as the value of every global to what they were before any call to SetDefault and SetGlobal.
Definition at line 820 of file config.cc.
References ns3::GlobalValue::Begin(), ns3::GlobalValue::End(), ns3::TypeId::GetAttribute(), ns3::TypeId::GetAttributeN(), ns3::TypeId::GetRegistered(), ns3::TypeId::GetRegisteredN(), NS_LOG_FUNCTION_NOARGS, ns3::TypeId::AttributeInformation::originalInitialValue, and ns3::TypeId::SetAttributeInitialValue().
Referenced by LteCqiGenerationTestCase::DoRun(), LteCqiGenerationDlPowerControlTestCase::DoRun(), LteDownlinkPowerControlTestCase::DoRun(), LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::DoRun(), LteHardFrTestCase::DoRun(), LteStrictFrTestCase::DoRun(), LteStrictFrAreaTestCase::DoRun(), LteSoftFrAreaTestCase::DoRun(), LteSoftFfrAreaTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LteInterferenceHardFrTestCase::DoRun(), LteInterferenceStrictFrTestCase::DoRun(), LteLinkAdaptationTestCase::DoRun(), LteUplinkOpenLoopPowerControlTestCase::DoRun(), LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun(), LteEnbAntennaTestCase::DoRun(), LteEpcE2eDataTestCase::DoRun(), LteRrcConnectionEstablishmentTestCase::DoRun(), LteRrcConnectionEstablishmentErrorTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), LteX2HandoverTestCase::DoRun(), NetworkNumberAllocatorTestCase::DoTeardown(), AddressAllocatorTestCase::DoTeardown(), NetworkAndAddressTestCase::DoTeardown(), ExampleAddressGeneratorTestCase::DoTeardown(), AddressCollisionTestCase::DoTeardown(), NetworkAllocatorHelperTestCase::DoTeardown(), AddressAllocatorHelperTestCase::DoTeardown(), ResetAllocatorHelperTestCase::DoTeardown(), IpAddressHelperTestCasev4::DoTeardown(), NetworkNumber6AllocatorTestCase::DoTeardown(), AddressAllocator6TestCase::DoTeardown(), NetworkAndAddress6TestCase::DoTeardown(), ExampleAddress6GeneratorTestCase::DoTeardown(), AddressCollision6TestCase::DoTeardown(), and IpAddressHelperTestCasev6::DoTeardown().
Set()
void ns3::Config::Set (std::string path, const AttributeValue & value)
Parameters
[in] path A path to match attributes.
[in] value The value to set in all matching attributes.
This function will attempt to find attributes which match the input path and will then set their value to the input value. If no such attributes are found, the function will throw a fatal error; use SetFailSafe if the lack of a match is to be permitted.
Definition at line 839 of file config.cc.
References ns3::Singleton< ConfigImpl >::Get(), NS_LOG_FUNCTION, and ns3::Config::ConfigImpl::Set().
Referenced by ns3::RawTextConfigLoad::Attributes(), ns3::XmlConfigLoad::Attributes(), IdealRateManagerChannelWidthTest::ChangeChannelWidth(), ns3::tests::RootNamespaceConfigTestCase::DoRun(), ns3::tests::UnderRootNamespaceConfigTestCase::DoRun(), ns3::tests::ObjectVectorConfigTestCase::DoRun(), ns3::tests::SearchAttributesOfParentObjectsTestCase::DoRun(), LteEpcE2eDataTestCase::DoRun(), Bug730TestCase::DoRun(), QosFragmentationTestCase::DoRun(), SetChannelFrequencyTest::DoRun(), NetAnimExperiment::IncrementCw(), Experiment::IncrementCw(), Experiment::Run(), TestInterBssConstantObssPdAlgo::RunOne(), IdealRateManagerMimoTest::SetApMimoSettings(), and IdealRateManagerMimoTest::SetStaMimoSettings().
SetDefault()
void ns3::Config::SetDefault (std::string name, const AttributeValue & value)
Parameters
[in] name The full name of the attribute
[in] value The value to set.
This method overrides the initial value of the matching attribute. This method cannot fail: it will crash if the input attribute name or value is invalid.
Definition at line 849 of file config.cc.
References NS_FATAL_ERROR, NS_LOG_FUNCTION, and ns3::Config::SetDefaultFailSafe().
Referenced by VanetRoutingExperiment::ConfigureDefaults(), TcpBytesInFlightTest::ConfigureEnvironment(), TcpDctcpCodePointsTest::ConfigureEnvironment(), TcpRateLinuxWithSocketsTest::ConfigureEnvironment(), BatteryLifetimeTest::ConstantLoadTest(), ns3::RawTextConfigLoad::Default(), ns3::XmlConfigLoad::Default(), BasicEnergyDepletionTest::DepletionTestCase(), ChainRegressionTest::DoRun(), Bug772ChainTest::DoRun(), LteRadioLinkFailureTestCase::DoRun(), LteUeMeasurementsPiecewiseTestCase1::DoRun(), LteUeMeasurementsPiecewiseTestCase2::DoRun(), LteUeMeasurementsPiecewiseTestCase3::DoRun(), LteUeMeasurementsHandoverTestCase::DoRun(), LteHandoverTargetTestCase::DoRun(), AttributeTestCase< T >::DoRun(), ns3::tests::ManyUniformRandomVariablesOneGetValueCallTestCase::DoRun(), ns3::tests::OneUniformRandomVariableManyGetValueCallsTestCase::DoRun(), Ipv4DeduplicationTest::DoRun(), Ipv4DeduplicationPerformanceTest::DoRun(), Ipv4FragmentationTest::DoRun(), Ipv4DynamicGlobalRoutingTestCase::DoRun(), RttEstimatorTestCase::DoRun(), EpcS1uDlTestCase::DoRun(), EpcS1uUlTestCase::DoRun(), CarrierAggregationConfigTestCase::DoRun(), CarrierAggregationTestCase::DoRun(), LenaCqaFfMacSchedulerTestCase1::DoRun(), LenaCqaFfMacSchedulerTestCase2::DoRun(), LteCqiGenerationTestCase::DoRun(), LteCqiGenerationDlPowerControlTestCase::DoRun(), ns3::LenaDeactivateBearerTestCase::DoRun(), LteDownlinkPowerControlTestCase::DoRun(), LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::DoRun(), LteDownlinkDataSinrTestCase::DoRun(), LteDownlinkCtrlSinrTestCase::DoRun(), LenaFdBetFfMacSchedulerTestCase1::DoRun(), LenaFdBetFfMacSchedulerTestCase2::DoRun(), LenaFdMtFfMacSchedulerTestCase::DoRun(), LenaFdTbfqFfMacSchedulerTestCase1::DoRun(), LenaFdTbfqFfMacSchedulerTestCase2::DoRun(), LteHardFrTestCase::DoRun(), LteStrictFrTestCase::DoRun(), LteStrictFrAreaTestCase::DoRun(), LteSoftFrAreaTestCase::DoRun(), LteSoftFfrAreaTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LenaHarqTestCase::DoRun(), LteInterferenceHardFrTestCase::DoRun(), LteInterferenceStrictFrTestCase::DoRun(), LteInterferenceTestCase::DoRun(), LteLinkAdaptationTestCase::DoRun(), LenaMimoTestCase::DoRun(), LtePathlossModelSystemTestCase::DoRun(), LenaPfFfMacSchedulerTestCase1::DoRun(), LenaPfFfMacSchedulerTestCase2::DoRun(), LenaDataPhyErrorModelTestCase::DoRun(), LenaDlCtrlPhyErrorModelTestCase::DoRun(), LenaPssFfMacSchedulerTestCase1::DoRun(), LenaPssFfMacSchedulerTestCase2::DoRun(), LteRlcAmE2eTestCase::DoRun(), LenaRrFfMacSchedulerTestCase::DoRun(), LenaTdBetFfMacSchedulerTestCase1::DoRun(), LenaTdBetFfMacSchedulerTestCase2::DoRun(), LenaTdMtFfMacSchedulerTestCase::DoRun(), LenaTdTbfqFfMacSchedulerTestCase1::DoRun(), LenaTdTbfqFfMacSchedulerTestCase2::DoRun(), LenaTtaFfMacSchedulerTestCase::DoRun(), LteUeMeasurementsTestCase::DoRun(), LteUplinkOpenLoopPowerControlTestCase::DoRun(), LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun(), LteEnbAntennaTestCase::DoRun(), LteEpcE2eDataTestCase::DoRun(), LteRrcConnectionEstablishmentTestCase::DoRun(), LteRrcConnectionEstablishmentErrorTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), LteX2HandoverTestCase::DoRun(), FriisPropagationLossModelTestCase::DoRun(), TwoRayGroundPropagationLossModelTestCase::DoRun(), LogDistancePropagationLossModelTestCase::DoRun(), RangePropagationLossModelTestCase::DoRun(), ThreeGppSpectrumPropagationLossModelTest::DoRun(), CsmaMulticastTestCase::DoRun(), CsmaPingTestCase::DoRun(), CsmaRawIpSocketTestCase::DoRun(), Ns3TcpCwndTestCase1::DoRun(), Ns3TcpCwndTestCase2::DoRun(), Ns3TcpLossTestCase::DoRun(), Ns3TcpNoDelayTestCase::DoRun(), Ns3TcpSocketTestCase2::DoRun(), Ns3TcpStateTestCase::DoRun(), NscTcpLossTestCase1::DoRun(), NscTcpLossTestCase2::DoRun(), Issue211Test::DoRun(), Ns3TcpLossTestCase::DoSetup(), experiment(), LteAggregationThroughputScaleTestCase::GetThroughput(), ConfigStoreHelper::LoadConfig(), RoutingExperiment::Run(), Experiment::Run(), InterferenceExperiment::Run(), TbfQueueDiscTestCase::RunTbfTest(), ConfigStoreHelper::SaveConfig(), and BatteryLifetimeTest::VariableLoadTest().
SetDefaultFailSafe()
bool ns3::Config::SetDefaultFailSafe (std::string name, const AttributeValue & value)
Parameters
[in] name The full name of the attribute
[in] value The value to set.
Returns
true if the value was set successfully, false otherwise.
This method overrides the initial value of the matching attribute.
Definition at line 857 of file config.cc.
References ns3::TypeId::AttributeInformation::checker, ns3::TypeId::GetAttribute(), ns3::TypeId::GetAttributeN(), ns3::TypeId::LookupByNameFailSafe(), ns3::TypeId::AttributeInformation::name, NS_LOG_FUNCTION, and ns3::TypeId::SetAttributeInitialValue().
Referenced by ns3::cell_edited_callback_config_default(), AttributeTestCase< T >::DoRun(), ns3::CommandLine::HandleArgument(), ns3::CommandLine::HandleAttribute(), and ns3::Config::SetDefault().
SetGlobal()
void ns3::Config::SetGlobal (std::string name, const AttributeValue & value)
Parameters
[in] name The name of the requested GlobalValue.
[in] value The value to set
This method is equivalent to GlobalValue::Bind
Definition at line 889 of file config.cc.
References ns3::GlobalValue::Bind(), and NS_LOG_FUNCTION.
Referenced by ThreeGppHttpObjectTestCase::DoRun(), LteCellSelectionTestCase::DoRun(), LenaDataPhyErrorModelTestCase::DoRun(), LenaDlCtrlPhyErrorModelTestCase::DoRun(), LteRlcAmE2eTestCase::DoRun(), ThreadedSimulatorEventsTestCase::DoSetup(), ThreadedSimulatorEventsTestCase::DoTeardown(), ns3::RawTextConfigLoad::Global(), ns3::XmlConfigLoad::Global(), ns3::RngSeedManager::SetRun(), and ns3::RngSeedManager::SetSeed().
SetGlobalFailSafe()
bool ns3::Config::SetGlobalFailSafe (std::string name, const AttributeValue & value)
Parameters
[in] name The name of the requested GlobalValue.
[in] value The value to set
Returns
true if the GlobalValue could be set.
This method is equivalent to GlobalValue::BindFailSafe
Definition at line 894 of file config.cc.
References ns3::GlobalValue::BindFailSafe(), and NS_LOG_FUNCTION.
Referenced by ns3::CommandLine::HandleArgument(), and ns3::CommandLine::HandleAttribute().
UnregisterRootNamespaceObject()
void ns3::Config::UnregisterRootNamespaceObject (Ptr< Object > obj)
Parameters
[in] obj A new root object
This function undoes the work of Config::RegisterRootNamespaceObject.
Definition at line 950 of file config.cc.
References ns3::Singleton< ConfigImpl >::Get(), NS_LOG_FUNCTION, and ns3::Config::ConfigImpl::UnregisterRootNamespaceObject().
Referenced by ns3::BuildingListPriv::Delete(), ns3::ChannelListPriv::Delete(), and ns3::NodeListPriv::Delete().