ns-3: Tracing
Tracing
Core
Publish/subscribe tools to collect and report changes to any values used by the various model components.
Files
file trace-source-accessor.cc
ns3::TraceSourceAccessor implementation (constructor and destructor).
file trace-source-accessor.h
ns3::TraceSourceAccessor and ns3::MakeTraceSourceAccessor declarations.
file traced-callback.h
ns3::TracedCallback declaration and template implementation.
file traced-value.h
ns3::TracedValue declaration and template implementation.
Classes
class ns3::TracedCallback< Ts >
Forward calls to a chain of Callback.
class ns3::TracedValue< T >
Trace classes with value semantics.
class ns3::TraceSourceAccessor
Control access to objects' trace sources.
Functions
template<typename T , typename SOURCE >
Ptr< const TraceSourceAccessor > ns3::DoMakeTraceSourceAccessor (SOURCE T::*a)
MakeTraceSourceAccessor() implementation.
static Ptr< const TraceSourceAccessor > ns3::MakeEmptyTraceSourceAccessor ()
Create an empty TraceSourceAccessor.
template<typename T >
Ptr< const TraceSourceAccessor > ns3::MakeTraceSourceAccessor (T a)
Create a TraceSourceAccessor which will control access to the underlying trace source.
template<typename T >
TracedValue< T > ns3::operator! (const TracedValue< T > &lhs)
Unary arithmetic operator for TracedValue.
template<typename T , typename U >
bool ns3::operator!= (const TracedValue< T > &lhs, const TracedValue< U > &rhs)
Boolean operator for TracedValue.
template<typename T , typename U >
bool ns3::operator!= (const TracedValue< T > &lhs, const U &rhs)
Boolean operator for TracedValue.
template<typename T , typename U >
bool ns3::operator!= (const U &lhs, const TracedValue< T > &rhs)
Boolean operator for TracedValue.
template<typename T , typename U >
auto ns3::operator% (const TracedValue< T > &lhs, const TracedValue< U > &rhs) -> TracedValue< decltype(lhs.Get() % rhs.Get())>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
auto ns3::operator% (const TracedValue< T > &lhs, const U &rhs) -> TracedValue< decltype(lhs.Get() % rhs)>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
auto ns3::operator% (const U &lhs, const TracedValue< T > &rhs) -> TracedValue< decltype(lhs % rhs.Get())>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
TracedValue< T > & ns3::operator%= (TracedValue< T > &lhs, const U &rhs)
Operator assignment for TracedValue.
template<typename T , typename U >
auto ns3::operator& (const TracedValue< T > &lhs, const TracedValue< U > &rhs) -> TracedValue< decltype(lhs.Get() &rhs.Get())>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
auto ns3::operator& (const TracedValue< T > &lhs, const U &rhs) -> TracedValue< decltype(lhs.Get() &rhs)>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
auto ns3::operator& (const U &lhs, const TracedValue< T > &rhs) -> TracedValue< decltype(lhs &rhs.Get())>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
TracedValue< T > & ns3::operator&= (TracedValue< T > &lhs, const U &rhs)
Operator assignment for TracedValue.
template<typename T , typename U >
auto ns3::operator* (const TracedValue< T > &lhs, const TracedValue< U > &rhs) -> TracedValue< decltype(lhs.Get() *rhs.Get())>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
auto ns3::operator* (const TracedValue< T > &lhs, const U &rhs) -> TracedValue< decltype(lhs.Get() *rhs)>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
auto ns3::operator* (const U &lhs, const TracedValue< T > &rhs) -> TracedValue< decltype(lhs+rhs.Get())>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
TracedValue< T > & ns3::operator*= (TracedValue< T > &lhs, const U &rhs)
Operator assignment for TracedValue.
template<typename T >
TracedValue< T > ns3::operator+ (const TracedValue< T > &lhs)
Unary arithmetic operator for TracedValue.
template<typename T , typename U >
auto ns3::operator+ (const TracedValue< T > &lhs, const TracedValue< U > &rhs) -> TracedValue< decltype(lhs.Get()+rhs.Get())>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
auto ns3::operator+ (const TracedValue< T > &lhs, const U &rhs) -> TracedValue< decltype(lhs.Get()+rhs)>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
auto ns3::operator+ (const U &lhs, const TracedValue< T > &rhs) -> TracedValue< decltype(lhs+rhs.Get())>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
TracedValue< T > & ns3::operator+= (TracedValue< T > &lhs, const U &rhs)
Operator assignment for TracedValue.
template<typename T >
TracedValue< T > ns3::operator- (const TracedValue< T > &lhs)
Unary arithmetic operator for TracedValue.
template<typename T , typename U >
auto ns3::operator- (const TracedValue< T > &lhs, const TracedValue< U > &rhs) -> TracedValue< decltype(lhs.Get() - rhs.Get())>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
auto ns3::operator- (const TracedValue< T > &lhs, const U &rhs) -> TracedValue< decltype(lhs.Get() - rhs)>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
auto ns3::operator- (const U &lhs, const TracedValue< T > &rhs) -> TracedValue< decltype(lhs - rhs.Get())>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
TracedValue< T > & ns3::operator-= (TracedValue< T > &lhs, const U &rhs)
Operator assignment for TracedValue.
template<typename T , typename U >
auto ns3::operator/ (const TracedValue< T > &lhs, const TracedValue< U > &rhs) -> TracedValue< decltype(lhs.Get()/rhs.Get())>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
auto ns3::operator/ (const TracedValue< T > &lhs, const U &rhs) -> TracedValue< decltype(lhs.Get()/rhs)>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
auto ns3::operator/ (const U &lhs, const TracedValue< T > &rhs) -> TracedValue< decltype(lhs/rhs.Get())>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
TracedValue< T > & ns3::operator/= (TracedValue< T > &lhs, const U &rhs)
Operator assignment for TracedValue.
template<typename T , typename U >
bool ns3::operator< (const TracedValue< T > &lhs, const TracedValue< U > &rhs)
Boolean operator for TracedValue.
template<typename T , typename U >
bool ns3::operator< (const TracedValue< T > &lhs, const U &rhs)
Boolean operator for TracedValue.
template<typename T , typename U >
bool ns3::operator< (const U &lhs, const TracedValue< T > &rhs)
Boolean operator for TracedValue.
template<typename T , typename U >
auto ns3::operator<< (const TracedValue< T > &lhs, const TracedValue< U > &rhs) -> TracedValue< decltype(lhs.Get()<< rhs.Get())>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
auto ns3::operator<< (const TracedValue< T > &lhs, const U &rhs) -> TracedValue< decltype(lhs.Get()<< rhs)>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
auto ns3::operator<< (const U &lhs, const TracedValue< T > &rhs) -> TracedValue< decltype(lhs<< rhs.Get())>
Infix arithmetic operator for TracedValue.
template<typename T >
std::ostream & ns3::operator<< (std::ostream &os, const TracedValue< T > &rhs)
Output streamer for TracedValue.
template<typename T , typename U >
TracedValue< T > & ns3::operator<<= (TracedValue< T > &lhs, const U &rhs)
Operator assignment for TracedValue.
template<typename T , typename U >
bool ns3::operator<= (const TracedValue< T > &lhs, const TracedValue< U > &rhs)
Boolean operator for TracedValue.
template<typename T , typename U >
bool ns3::operator<= (const TracedValue< T > &lhs, const U &rhs)
Boolean operator for TracedValue.
template<typename T , typename U >
bool ns3::operator<= (const U &lhs, const TracedValue< T > &rhs)
Boolean operator for TracedValue.
template<typename T , typename U >
bool ns3::operator== (const TracedValue< T > &lhs, const TracedValue< U > &rhs)
Boolean operator for TracedValue.
template<typename T , typename U >
bool ns3::operator== (const TracedValue< T > &lhs, const U &rhs)
Boolean operator for TracedValue.
template<typename T , typename U >
bool ns3::operator== (const U &lhs, const TracedValue< T > &rhs)
Boolean operator for TracedValue.
template<typename T , typename U >
bool ns3::operator> (const TracedValue< T > &lhs, const TracedValue< U > &rhs)
Boolean operator for TracedValue.
template<typename T , typename U >
bool ns3::operator> (const TracedValue< T > &lhs, const U &rhs)
Boolean operator for TracedValue.
template<typename T , typename U >
bool ns3::operator> (const U &lhs, const TracedValue< T > &rhs)
Boolean operator for TracedValue.
template<typename T , typename U >
bool ns3::operator>= (const TracedValue< T > &lhs, const TracedValue< U > &rhs)
Boolean operator for TracedValue.
template<typename T , typename U >
bool ns3::operator>= (const TracedValue< T > &lhs, const U &rhs)
Boolean operator for TracedValue.
template<typename T , typename U >
bool ns3::operator>= (const U &lhs, const TracedValue< T > &rhs)
Boolean operator for TracedValue.
template<typename T , typename U >
auto ns3::operator>> (const TracedValue< T > &lhs, const TracedValue< U > &rhs) -> TracedValue< decltype(lhs.Get() >> rhs.Get())>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
auto ns3::operator>> (const TracedValue< T > &lhs, const U &rhs) -> TracedValue< decltype(lhs.Get() >> rhs)>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
auto ns3::operator>> (const U &lhs, const TracedValue< T > &rhs) -> TracedValue< decltype(lhs >> rhs.Get())>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
TracedValue< T > & ns3::operator>>= (TracedValue< T > &lhs, const U &rhs)
Operator assignment for TracedValue.
template<typename T , typename U >
auto ns3::operator^ (const TracedValue< T > &lhs, const TracedValue< U > &rhs) -> TracedValue< decltype(lhs.Get() ^ rhs.Get())>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
auto ns3::operator^ (const TracedValue< T > &lhs, const U &rhs) -> TracedValue< decltype(lhs.Get() ^ rhs)>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
auto ns3::operator^ (const U &lhs, const TracedValue< T > &rhs) -> TracedValue< decltype(lhs ^ rhs.Get())>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
TracedValue< T > & ns3::operator^= (TracedValue< T > &lhs, const U &rhs)
Operator assignment for TracedValue.
template<typename T , typename U >
auto ns3::operator| (const TracedValue< T > &lhs, const TracedValue< U > &rhs) -> TracedValue< decltype(lhs.Get()|rhs.Get())>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
auto ns3::operator| (const TracedValue< T > &lhs, const U &rhs) -> TracedValue< decltype(lhs.Get()|rhs)>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
auto ns3::operator| (const U &lhs, const TracedValue< T > &rhs) -> TracedValue< decltype(lhs|rhs.Get())>
Infix arithmetic operator for TracedValue.
template<typename T , typename U >
TracedValue< T > & ns3::operator|= (TracedValue< T > &lhs, const U &rhs)
Operator assignment for TracedValue.
template<typename T >
TracedValue< T > ns3::operator~ (const TracedValue< T > &lhs)
Unary arithmetic operator for TracedValue.
Detailed Description
Publish/subscribe tools to collect and report changes to any values used by the various model components.
Additional callback function signatures defined elsewhere:
TracedValueCallback::Time
TracedValueCallback::SequenceNumber32
TracedValueCallback::LrWpanMacState
TracedValueCallback::LrWpanPhyEnumeration
Function Documentation
DoMakeTraceSourceAccessor()
template<typename T , typename SOURCE > Ptr<const TraceSourceAccessor> ns3::DoMakeTraceSourceAccessor (SOURCE T::* a)
MakeTraceSourceAccessor() implementation.
Template Parameters
T [deduced] Class type of the TracedCallback
SOURCE [deduced] Type of the underlying value.
Parameters
[in] a The underlying data value.
Returns
The TraceSourceAccessor
Definition at line 151 of file trace-source-accessor.h.
References ns3::Config::Connect(), ns3::Config::ConnectWithoutContext(), ns3::Config::Disconnect(), and ns3::Config::DisconnectWithoutContext().
Referenced by ns3::MakeTraceSourceAccessor().
MakeEmptyTraceSourceAccessor()
static Ptr<const TraceSourceAccessor> ns3::MakeEmptyTraceSourceAccessor () inline static
Create an empty TraceSourceAccessor.
Returns
The empty TraceSourceAccessor (runtime exception if used)
Definition at line 126 of file trace-source-accessor.h.
Referenced by DeprecatedAttribute::GetTypeId().
MakeTraceSourceAccessor()
template<typename T > Ptr< const TraceSourceAccessor > ns3::MakeTraceSourceAccessor (T a)
Create a TraceSourceAccessor which will control access to the underlying trace source.
This helper template method assumes that the underlying type implements a statically-polymorphic set of Connect and Disconnect methods and creates a dynamic-polymorphic class to wrap the underlying static-polymorphic class. This functionality is typically provided by wrapping an object data member in a TracedCallback or TracedValue.
Parameters
[in] a The trace source
Returns
The TraceSourceAccessor
Definition at line 202 of file trace-source-accessor.h.
References ns3::DoMakeTraceSourceAccessor().
Referenced by ns3::ApplicationPacketProbe::GetTypeId(), ns3::ThreeGppHttpClient::GetTypeId(), ns3::ThreeGppHttpServer::GetTypeId(), ns3::dsr::DsrRouting::GetTypeId(), ns3::Ipv4PacketProbe::GetTypeId(), ns3::Ipv6L3Protocol::GetTypeId(), ns3::Ipv6PacketProbe::GetTypeId(), ns3::LteFfrSimple::GetTypeId(), ns3::dot11s::HwmpProtocol::GetTypeId(), ns3::dot11s::PeerManagementProtocol::GetTypeId(), ns3::PacketProbe::GetTypeId(), ns3::BooleanProbe::GetTypeId(), ns3::DoubleProbe::GetTypeId(), ns3::TimeProbe::GetTypeId(), ns3::Uinteger16Probe::GetTypeId(), ns3::Uinteger32Probe::GetTypeId(), ns3::Uinteger8Probe::GetTypeId(), ns3::UanPhyDual::GetTypeId(), Sender::GetTypeId(), MyObject::GetTypeId(), ns3::BulkSendApplication::GetTypeId(), ns3::OnOffApplication::GetTypeId(), ns3::PacketSink::GetTypeId(), ns3::UdpEchoClient::GetTypeId(), ns3::UdpEchoServer::GetTypeId(), ns3::UdpServer::GetTypeId(), AttributeObjectTest::GetTypeId(), ns3::tests::ConfigTestObject::GetTypeId(), DeprecatedAttribute::GetTypeId(), ns3::CsmaNetDevice::GetTypeId(), ns3::dsr::DsrOptions::GetTypeId(), ns3::BasicEnergyHarvester::GetTypeId(), ns3::BasicEnergySource::GetTypeId(), ns3::LiIonEnergySource::GetTypeId(), ns3::RvBatteryModel::GetTypeId(), ns3::SimpleDeviceEnergyModel::GetTypeId(), ns3::FdNetDevice::GetTypeId(), ns3::DhcpClient::GetTypeId(), ns3::V4Ping::GetTypeId(), ns3::ArpCache::GetTypeId(), ns3::ArpL3Protocol::GetTypeId(), ns3::Ipv4L3Protocol::GetTypeId(), ns3::NscTcpSocketImpl::GetTypeId(), ns3::TcpDctcp::GetTypeId(), ns3::TcpHybla::GetTypeId(), ns3::TcpRateLinux::GetTypeId(), ns3::TcpRxBuffer::GetTypeId(), ns3::TcpSocketBase::GetTypeId(), ns3::TcpSocketState::GetTypeId(), ns3::TcpTxBuffer::GetTypeId(), ns3::TcpWestwood::GetTypeId(), ns3::UdpSocketImpl::GetTypeId(), ns3::LrWpanMac::GetTypeId(), ns3::LrWpanPhy::GetTypeId(), ns3::EpcEnbApplication::GetTypeId(), ns3::EpcPgwApplication::GetTypeId(), ns3::EpcUeNas::GetTypeId(), ns3::LteEnbMac::GetTypeId(), ns3::LteEnbPhy::GetTypeId(), ns3::UeManager::GetTypeId(), ns3::LteEnbRrc::GetTypeId(), ns3::LtePdcp::GetTypeId(), ns3::LteRlc::GetTypeId(), ns3::LteSpectrumPhy::GetTypeId(), ns3::LteUeMac::GetTypeId(), ns3::LteUePhy::GetTypeId(), ns3::LteUePowerControl::GetTypeId(), ns3::LteUeRrc::GetTypeId(), ns3::LteSimpleSpectrumPhy::GetTypeId(), ns3::MobilityModel::GetTypeId(), anonymous_namespace{sequence-number-test-suite.cc}::SequenceNumberTestObj::GetTypeId(), ns3::DynamicQueueLimits::GetTypeId(), ns3::PacketSocketClient::GetTypeId(), ns3::PacketSocketServer::GetTypeId(), ns3::PacketSocket::GetTypeId(), ns3::QueueBase::GetTypeId(), ns3::Queue< Item >::GetTypeId(), ns3::SimpleNetDevice::GetTypeId(), ns3::olsr::RoutingProtocol::GetTypeId(), ns3::PointToPointChannel::GetTypeId(), ns3::PointToPointNetDevice::GetTypeId(), ns3::SixLowPanNetDevice::GetTypeId(), ns3::AlohaNoackNetDevice::GetTypeId(), ns3::HalfDuplexIdealPhy::GetTypeId(), ns3::SpectrumAnalyzer::GetTypeId(), ns3::SpectrumChannel::GetTypeId(), ns3::WaveformGenerator::GetTypeId(), Emitter::GetTypeId(), ns3::TimeSeriesAdaptor::GetTypeId(), SampleEmitter::GetTypeId(), TracedValueCallbackTestCase::CheckTvCb< T >::GetTypeId(), ns3::CobaltQueueDisc::GetTypeId(), ns3::CoDelQueueDisc::GetTypeId(), ns3::QueueDisc::GetTypeId(), ns3::TbfQueueDisc::GetTypeId(), ns3::AcousticModemEnergyModel::GetTypeId(), ns3::UanMacCw::GetTypeId(), ns3::UanMacRcGw::GetTypeId(), ns3::UanMacRc::GetTypeId(), ns3::UanNetDevice::GetTypeId(), ns3::UanPhyGen::GetTypeId(), ns3::UanPhy::GetTypeId(), ns3::VirtualNetDevice::GetTypeId(), ns3::AarfWifiManager::GetTypeId(), ns3::AarfcdWifiManager::GetTypeId(), ns3::AmrrWifiManager::GetTypeId(), ns3::AparfWifiManager::GetTypeId(), ns3::ArfWifiManager::GetTypeId(), ns3::BlockAckManager::GetTypeId(), ns3::CaraWifiManager::GetTypeId(), ns3::IdealWifiManager::GetTypeId(), ns3::MinstrelHtWifiManager::GetTypeId(), ns3::MinstrelWifiManager::GetTypeId(), ns3::ObssPdAlgorithm::GetTypeId(), ns3::OnoeWifiManager::GetTypeId(), ns3::ParfWifiManager::GetTypeId(), ns3::QosTxop::GetTypeId(), ns3::RegularWifiMac::GetTypeId(), ns3::RraaWifiManager::GetTypeId(), ns3::RrpaaWifiManager::GetTypeId(), ns3::SpectrumWifiPhy::GetTypeId(), ns3::StaWifiMac::GetTypeId(), ns3::Txop::GetTypeId(), ns3::WifiMacQueue::GetTypeId(), ns3::WifiMac::GetTypeId(), ns3::WifiPhyStateHelper::GetTypeId(), ns3::WifiPhy::GetTypeId(), ns3::WifiRadioEnergyModel::GetTypeId(), ns3::WifiRemoteStationManager::GetTypeId(), ns3::BaseStationNetDevice::GetTypeId(), ns3::SimpleOfdmWimaxPhy::GetTypeId(), ns3::SubscriberStationNetDevice::GetTypeId(), ns3::WimaxMacQueue::GetTypeId(), and ns3::WimaxNetDevice::GetTypeId().
operator!()
template<typename T > TracedValue<T> ns3::operator! (const TracedValue< T > & lhs)
Unary arithmetic operator for TracedValue.
Template Parameters
T [deduced] The underlying type held by the TracedValue.
Parameters
[in] lhs The TracedValue.
Returns
The result of doing the operator on the underlying values.
Definition at line 823 of file traced-value.h.
References ns3::TracedValue< T >::Get(), and TRACED_VALUE_DEBUG.
operator!=() [1/3]
template<typename T , typename U > bool ns3::operator!= (const TracedValue< T > & lhs, const TracedValue< U > & rhs)
Boolean operator for TracedValue.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The Boolean result of comparing the underlying values.
Definition at line 339 of file traced-value.h.
References ns3::TracedValue< T >::Get(), and TRACED_VALUE_DEBUG.
operator!=() [2/3]
template<typename T , typename U > bool ns3::operator!= (const TracedValue< T > & lhs, const U & rhs)
Boolean operator for TracedValue.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The Boolean result of comparing the underlying values.
Definition at line 346 of file traced-value.h.
References ns3::TracedValue< T >::Get(), and TRACED_VALUE_DEBUG.
operator!=() [3/3]
template<typename T , typename U > bool ns3::operator!= (const U & lhs, const TracedValue< T > & rhs)
Boolean operator for TracedValue.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The Boolean result of comparing the underlying values.
Definition at line 353 of file traced-value.h.
References ns3::TracedValue< T >::Get(), and TRACED_VALUE_DEBUG.
operator%() [1/3]
template<typename T , typename U > auto ns3::operator% (const TracedValue< T > & lhs, const TracedValue< U > & rhs) -> TracedValue<decltype(lhs.Get () % rhs.Get ())>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 548 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator%() [2/3]
template<typename T , typename U > auto ns3::operator% (const TracedValue< T > & lhs, const U & rhs) -> TracedValue<decltype(lhs.Get () % rhs)>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 555 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator%() [3/3]
template<typename T , typename U > auto ns3::operator% (const U & lhs, const TracedValue< T > & rhs) -> TracedValue<decltype(lhs % rhs.Get ())>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 562 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator%=()
template<typename T , typename U > TracedValue<T>& ns3::operator%= (TracedValue< T > & lhs, const U & rhs)
Operator assignment for TracedValue.
The result of the arithmetic operation on the underlying values is assigned to the lhs TracedValue. If the new value is different, the Callback will be invoked.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 733 of file traced-value.h.
References ns3::TracedValue< T >::Get(), ns3::TracedValue< T >::Set(), and TRACED_VALUE_DEBUG.
operator&() [1/3]
template<typename T , typename U > auto ns3::operator& (const TracedValue< T > & lhs, const TracedValue< U > & rhs) -> TracedValue<decltype(lhs.Get () & rhs.Get ())>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 614 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator&() [2/3]
template<typename T , typename U > auto ns3::operator& (const TracedValue< T > & lhs, const U & rhs) -> TracedValue<decltype(lhs.Get () & rhs)>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 621 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator&() [3/3]
template<typename T , typename U > auto ns3::operator& (const U & lhs, const TracedValue< T > & rhs) -> TracedValue<decltype(lhs & rhs.Get ())>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 628 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator&=()
template<typename T , typename U > TracedValue<T>& ns3::operator&= (TracedValue< T > & lhs, const U & rhs)
Operator assignment for TracedValue.
The result of the arithmetic operation on the underlying values is assigned to the lhs TracedValue. If the new value is different, the Callback will be invoked.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 763 of file traced-value.h.
References ns3::TracedValue< T >::Get(), ns3::TracedValue< T >::Set(), and TRACED_VALUE_DEBUG.
operator*() [1/3]
template<typename T , typename U > auto ns3::operator* (const TracedValue< T > & lhs, const TracedValue< U > & rhs) -> TracedValue<decltype(lhs.Get () * rhs.Get ())>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 504 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator*() [2/3]
template<typename T , typename U > auto ns3::operator* (const TracedValue< T > & lhs, const U & rhs) -> TracedValue<decltype(lhs.Get () * rhs)>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 511 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator*() [3/3]
template<typename T , typename U > auto ns3::operator* (const U & lhs, const TracedValue< T > & rhs) -> TracedValue<decltype(lhs + rhs.Get ())>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 518 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator*=()
template<typename T , typename U > TracedValue<T>& ns3::operator*= (TracedValue< T > & lhs, const U & rhs)
Operator assignment for TracedValue.
The result of the arithmetic operation on the underlying values is assigned to the lhs TracedValue. If the new value is different, the Callback will be invoked.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 713 of file traced-value.h.
References ns3::TracedValue< T >::Get(), ns3::TracedValue< T >::Set(), and TRACED_VALUE_DEBUG.
operator+() [1/4]
template<typename T > TracedValue<T> ns3::operator+ (const TracedValue< T > & lhs)
Unary arithmetic operator for TracedValue.
Template Parameters
T [deduced] The underlying type held by the TracedValue.
Parameters
[in] lhs The TracedValue.
Returns
The result of doing the operator on the underlying values.
Definition at line 802 of file traced-value.h.
References ns3::TracedValue< T >::Get(), and TRACED_VALUE_DEBUG.
operator+() [2/4]
template<typename T , typename U > auto ns3::operator+ (const TracedValue< T > & lhs, const TracedValue< U > & rhs) -> TracedValue<decltype(lhs.Get () + rhs.Get ())>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 460 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator+() [3/4]
template<typename T , typename U > auto ns3::operator+ (const TracedValue< T > & lhs, const U & rhs) -> TracedValue<decltype(lhs.Get () + rhs)>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 467 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator+() [4/4]
template<typename T , typename U > auto ns3::operator+ (const U & lhs, const TracedValue< T > & rhs) -> TracedValue<decltype(lhs + rhs.Get ())>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 474 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator+=()
template<typename T , typename U > TracedValue<T>& ns3::operator+= (TracedValue< T > & lhs, const U & rhs)
Operator assignment for TracedValue.
The result of the arithmetic operation on the underlying values is assigned to the lhs TracedValue. If the new value is different, the Callback will be invoked.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 693 of file traced-value.h.
References ns3::TracedValue< T >::Get(), ns3::TracedValue< T >::Set(), and TRACED_VALUE_DEBUG.
operator-() [1/4]
template<typename T > TracedValue<T> ns3::operator- (const TracedValue< T > & lhs)
Unary arithmetic operator for TracedValue.
Template Parameters
T [deduced] The underlying type held by the TracedValue.
Parameters
[in] lhs The TracedValue.
Returns
The result of doing the operator on the underlying values.
Definition at line 809 of file traced-value.h.
References ns3::TracedValue< T >::Get(), and TRACED_VALUE_DEBUG.
operator-() [2/4]
template<typename T , typename U > auto ns3::operator- (const TracedValue< T > & lhs, const TracedValue< U > & rhs) -> TracedValue<decltype(lhs.Get () - rhs.Get ())>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 482 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator-() [3/4]
template<typename T , typename U > auto ns3::operator- (const TracedValue< T > & lhs, const U & rhs) -> TracedValue<decltype(lhs.Get () - rhs)>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 489 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator-() [4/4]
template<typename T , typename U > auto ns3::operator- (const U & lhs, const TracedValue< T > & rhs) -> TracedValue<decltype(lhs - rhs.Get ())>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 496 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator-=()
template<typename T , typename U > TracedValue<T>& ns3::operator-= (TracedValue< T > & lhs, const U & rhs)
Operator assignment for TracedValue.
The result of the arithmetic operation on the underlying values is assigned to the lhs TracedValue. If the new value is different, the Callback will be invoked.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 703 of file traced-value.h.
References ns3::TracedValue< T >::Get(), ns3::TracedValue< T >::Set(), and TRACED_VALUE_DEBUG.
operator/() [1/3]
template<typename T , typename U > auto ns3::operator/ (const TracedValue< T > & lhs, const TracedValue< U > & rhs) -> TracedValue<decltype(lhs.Get () / rhs.Get ())>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 526 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator/() [2/3]
template<typename T , typename U > auto ns3::operator/ (const TracedValue< T > & lhs, const U & rhs) -> TracedValue<decltype(lhs.Get () / rhs)>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 533 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator/() [3/3]
template<typename T , typename U > auto ns3::operator/ (const U & lhs, const TracedValue< T > & rhs) -> TracedValue<decltype(lhs / rhs.Get ())>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 540 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator/=()
template<typename T , typename U > TracedValue<T>& ns3::operator/= (TracedValue< T > & lhs, const U & rhs)
Operator assignment for TracedValue.
The result of the arithmetic operation on the underlying values is assigned to the lhs TracedValue. If the new value is different, the Callback will be invoked.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 723 of file traced-value.h.
References ns3::TracedValue< T >::Get(), ns3::TracedValue< T >::Set(), and TRACED_VALUE_DEBUG.
operator<() [1/3]
template<typename T , typename U > bool ns3::operator< (const TracedValue< T > & lhs, const TracedValue< U > & rhs)
Boolean operator for TracedValue.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The Boolean result of comparing the underlying values.
Definition at line 404 of file traced-value.h.
References ns3::TracedValue< T >::Get(), and TRACED_VALUE_DEBUG.
operator<() [2/3]
template<typename T , typename U > bool ns3::operator< (const TracedValue< T > & lhs, const U & rhs)
Boolean operator for TracedValue.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The Boolean result of comparing the underlying values.
Definition at line 411 of file traced-value.h.
References ns3::TracedValue< T >::Get(), and TRACED_VALUE_DEBUG.
operator<() [3/3]
template<typename T , typename U > bool ns3::operator< (const U & lhs, const TracedValue< T > & rhs)
Boolean operator for TracedValue.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The Boolean result of comparing the underlying values.
Definition at line 418 of file traced-value.h.
References ns3::TracedValue< T >::Get(), and TRACED_VALUE_DEBUG.
operator<<() [1/4]
template<typename T , typename U > auto ns3::operator<< (const TracedValue< T > & lhs, const TracedValue< U > & rhs) -> TracedValue<decltype(lhs.Get () << rhs.Get ())>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 636 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator<<() [2/4]
template<typename T , typename U > auto ns3::operator<< (const TracedValue< T > & lhs, const U & rhs) -> TracedValue<decltype(lhs.Get () << rhs)>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 643 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator<<() [3/4]
template<typename T , typename U > auto ns3::operator<< (const U & lhs, const TracedValue< T > & rhs) -> TracedValue<decltype(lhs << rhs.Get ())>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 650 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator<<() [4/4]
template<typename T > std::ostream& ns3::operator<< (std::ostream & os, const TracedValue< T > & rhs)
Output streamer for TracedValue.
The underlying value will be written to the stream.
Template Parameters
T [deduced] The underlying type of the TracedValue.
Parameters
[in,out] os The output stream.
[in] rhs The TracedValue to stream.
Returns
The stream.
Definition at line 303 of file traced-value.h.
References ns3::TracedValue< T >::Get().
operator<<=()
template<typename T , typename U > TracedValue<T>& ns3::operator<<= (TracedValue< T > & lhs, const U & rhs)
Operator assignment for TracedValue.
The result of the arithmetic operation on the underlying values is assigned to the lhs TracedValue. If the new value is different, the Callback will be invoked.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 733 of file traced-value.h.
operator<=() [1/3]
template<typename T , typename U > bool ns3::operator<= (const TracedValue< T > & lhs, const TracedValue< U > & rhs)
Boolean operator for TracedValue.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The Boolean result of comparing the underlying values.
Definition at line 361 of file traced-value.h.
References ns3::TracedValue< T >::Get(), and TRACED_VALUE_DEBUG.
operator<=() [2/3]
template<typename T , typename U > bool ns3::operator<= (const TracedValue< T > & lhs, const U & rhs)
Boolean operator for TracedValue.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The Boolean result of comparing the underlying values.
Definition at line 368 of file traced-value.h.
References ns3::TracedValue< T >::Get(), and TRACED_VALUE_DEBUG.
operator<=() [3/3]
template<typename T , typename U > bool ns3::operator<= (const U & lhs, const TracedValue< T > & rhs)
Boolean operator for TracedValue.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The Boolean result of comparing the underlying values.
Definition at line 375 of file traced-value.h.
References ns3::TracedValue< T >::Get(), and TRACED_VALUE_DEBUG.
operator==() [1/3]
template<typename T , typename U > bool ns3::operator== (const TracedValue< T > & lhs, const TracedValue< U > & rhs)
Boolean operator for TracedValue.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The Boolean result of comparing the underlying values.
Definition at line 317 of file traced-value.h.
References ns3::TracedValue< T >::Get(), and TRACED_VALUE_DEBUG.
operator==() [2/3]
template<typename T , typename U > bool ns3::operator== (const TracedValue< T > & lhs, const U & rhs)
Boolean operator for TracedValue.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The Boolean result of comparing the underlying values.
Definition at line 324 of file traced-value.h.
References ns3::TracedValue< T >::Get(), and TRACED_VALUE_DEBUG.
operator==() [3/3]
template<typename T , typename U > bool ns3::operator== (const U & lhs, const TracedValue< T > & rhs)
Boolean operator for TracedValue.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The Boolean result of comparing the underlying values.
Definition at line 331 of file traced-value.h.
References ns3::TracedValue< T >::Get(), and TRACED_VALUE_DEBUG.
operator>() [1/3]
template<typename T , typename U > bool ns3::operator> (const TracedValue< T > & lhs, const TracedValue< U > & rhs)
Boolean operator for TracedValue.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The Boolean result of comparing the underlying values.
Definition at line 425 of file traced-value.h.
References ns3::TracedValue< T >::Get(), and TRACED_VALUE_DEBUG.
operator>() [2/3]
template<typename T , typename U > bool ns3::operator> (const TracedValue< T > & lhs, const U & rhs)
Boolean operator for TracedValue.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The Boolean result of comparing the underlying values.
Definition at line 432 of file traced-value.h.
References ns3::TracedValue< T >::Get(), and TRACED_VALUE_DEBUG.
operator>() [3/3]
template<typename T , typename U > bool ns3::operator> (const U & lhs, const TracedValue< T > & rhs)
Boolean operator for TracedValue.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The Boolean result of comparing the underlying values.
Definition at line 439 of file traced-value.h.
References ns3::TracedValue< T >::Get(), and TRACED_VALUE_DEBUG.
operator>=() [1/3]
template<typename T , typename U > bool ns3::operator>= (const TracedValue< T > & lhs, const TracedValue< U > & rhs)
Boolean operator for TracedValue.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The Boolean result of comparing the underlying values.
Definition at line 382 of file traced-value.h.
References ns3::TracedValue< T >::Get(), and TRACED_VALUE_DEBUG.
operator>=() [2/3]
template<typename T , typename U > bool ns3::operator>= (const TracedValue< T > & lhs, const U & rhs)
Boolean operator for TracedValue.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The Boolean result of comparing the underlying values.
Definition at line 389 of file traced-value.h.
References ns3::TracedValue< T >::Get(), and TRACED_VALUE_DEBUG.
operator>=() [3/3]
template<typename T , typename U > bool ns3::operator>= (const U & lhs, const TracedValue< T > & rhs)
Boolean operator for TracedValue.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The Boolean result of comparing the underlying values.
Definition at line 396 of file traced-value.h.
References ns3::TracedValue< T >::Get(), and TRACED_VALUE_DEBUG.
operator>>() [1/3]
template<typename T , typename U > auto ns3::operator>> (const TracedValue< T > & lhs, const TracedValue< U > & rhs) -> TracedValue<decltype(lhs.Get () >> rhs.Get ())>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 658 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator>>() [2/3]
template<typename T , typename U > auto ns3::operator>> (const TracedValue< T > & lhs, const U & rhs) -> TracedValue<decltype(lhs.Get () >> rhs)>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 665 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator>>() [3/3]
template<typename T , typename U > auto ns3::operator>> (const U & lhs, const TracedValue< T > & rhs) -> TracedValue<decltype(lhs >> rhs.Get ())>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 672 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator>>=()
template<typename T , typename U > TracedValue<T>& ns3::operator>>= (TracedValue< T > & lhs, const U & rhs)
Operator assignment for TracedValue.
The result of the arithmetic operation on the underlying values is assigned to the lhs TracedValue. If the new value is different, the Callback will be invoked.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 753 of file traced-value.h.
References ns3::TracedValue< T >::Get(), ns3::TracedValue< T >::Set(), and TRACED_VALUE_DEBUG.
operator^() [1/3]
template<typename T , typename U > auto ns3::operator^ (const TracedValue< T > & lhs, const TracedValue< U > & rhs) -> TracedValue<decltype(lhs.Get () ^ rhs.Get ())>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 570 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator^() [2/3]
template<typename T , typename U > auto ns3::operator^ (const TracedValue< T > & lhs, const U & rhs) -> TracedValue<decltype(lhs.Get () ^ rhs)>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 577 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator^() [3/3]
template<typename T , typename U > auto ns3::operator^ (const U & lhs, const TracedValue< T > & rhs) -> TracedValue<decltype(lhs ^ rhs.Get ())>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 584 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator^=()
template<typename T , typename U > TracedValue<T>& ns3::operator^= (TracedValue< T > & lhs, const U & rhs)
Operator assignment for TracedValue.
The result of the arithmetic operation on the underlying values is assigned to the lhs TracedValue. If the new value is different, the Callback will be invoked.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 783 of file traced-value.h.
References ns3::TracedValue< T >::Get(), ns3::TracedValue< T >::Set(), and TRACED_VALUE_DEBUG.
operator|() [1/3]
template<typename T , typename U > auto ns3::operator| (const TracedValue< T > & lhs, const TracedValue< U > & rhs) -> TracedValue<decltype(lhs.Get () | rhs.Get ())>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 592 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator|() [2/3]
template<typename T , typename U > auto ns3::operator| (const TracedValue< T > & lhs, const U & rhs) -> TracedValue<decltype(lhs.Get () | rhs)>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 599 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator|() [3/3]
template<typename T , typename U > auto ns3::operator| (const U & lhs, const TracedValue< T > & rhs) -> TracedValue<decltype(lhs | rhs.Get ())>
Infix arithmetic operator for TracedValue.
This returns the arithmetic result in a new TracedValue, which has no Callback connected.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 606 of file traced-value.h.
References TRACED_VALUE_DEBUG.
operator|=()
template<typename T , typename U > TracedValue<T>& ns3::operator|= (TracedValue< T > & lhs, const U & rhs)
Operator assignment for TracedValue.
The result of the arithmetic operation on the underlying values is assigned to the lhs TracedValue. If the new value is different, the Callback will be invoked.
Template Parameters
T [deduced] The underlying type held by the left-hand argument.
U [deduced] The underlying type held by the right-hand argument.
Parameters
[in] lhs The left-hand argument.
[in] rhs The right-hand argument.
Returns
The result of doing the operator on the underlying values.
Definition at line 773 of file traced-value.h.
References ns3::TracedValue< T >::Get(), ns3::TracedValue< T >::Set(), and TRACED_VALUE_DEBUG.
operator~()
template<typename T > TracedValue<T> ns3::operator~ (const TracedValue< T > & lhs)
Unary arithmetic operator for TracedValue.
Template Parameters
T [deduced] The underlying type held by the TracedValue.
Parameters
[in] lhs The TracedValue.
Returns
The result of doing the operator on the underlying values.
Definition at line 816 of file traced-value.h.
References ns3::TracedValue< T >::Get(), and TRACED_VALUE_DEBUG.