ns-3: Standard Time Units.
Standard Time Units.
Core » Virtual Time
Convenience constructors in standard units.
Time ns3::Years (double value)
Construct a Time in the indicated unit.
Time ns3::Years (int64x64_t value)
Construct a Time in the indicated unit.
Time ns3::Days (double value)
Construct a Time in the indicated unit.
Time ns3::Days (int64x64_t value)
Construct a Time in the indicated unit.
Time ns3::Hours (double value)
Construct a Time in the indicated unit.
Time ns3::Hours (int64x64_t value)
Construct a Time in the indicated unit.
Time ns3::Minutes (double value)
Construct a Time in the indicated unit.
Time ns3::Minutes (int64x64_t value)
Construct a Time in the indicated unit.
Time ns3::Seconds (double value)
Construct a Time in the indicated unit.
Time ns3::Seconds (int64x64_t value)
Construct a Time in the indicated unit.
Time ns3::MilliSeconds (uint64_t value)
Construct a Time in the indicated unit.
Time ns3::MilliSeconds (int64x64_t value)
Construct a Time in the indicated unit.
Time ns3::MicroSeconds (uint64_t value)
Construct a Time in the indicated unit.
Time ns3::MicroSeconds (int64x64_t value)
Construct a Time in the indicated unit.
Time ns3::NanoSeconds (uint64_t value)
Construct a Time in the indicated unit.
Time ns3::NanoSeconds (int64x64_t value)
Construct a Time in the indicated unit.
Time ns3::PicoSeconds (uint64_t value)
Construct a Time in the indicated unit.
Time ns3::PicoSeconds (int64x64_t value)
Construct a Time in the indicated unit.
Time ns3::FemtoSeconds (uint64_t value)
Construct a Time in the indicated unit.
Time ns3::FemtoSeconds (int64x64_t value)
Construct a Time in the indicated unit.
Detailed Description
Convenience constructors in standard units.
For example:
Time t = Seconds (2.0);
Simulator::Schedule (Seconds (5.0), ...);
Function Documentation
Days() [1/2]
Time ns3::Days (double value) inline
Construct a Time in the indicated unit.
Parameters
[in] value The value
Returns
The Time
Definition at line 1265 of file nstime.h.
References ns3::Time::D, and ns3::Time::FromDouble().
Referenced by TimeSimpleTestCase::DoRun().
Days() [2/2]
Time ns3::Days (int64x64_t value) inline
Construct a Time in the indicated unit.
Parameters
[in] value The value
Returns
The Time
Definition at line 1269 of file nstime.h.
References ns3::Time::D, and ns3::Time::From().
FemtoSeconds() [1/2]
Time ns3::FemtoSeconds (int64x64_t value) inline
Construct a Time in the indicated unit.
Parameters
[in] value The value
Returns
The Time
Definition at line 1333 of file nstime.h.
References ns3::Time::From(), and ns3::Time::FS.
FemtoSeconds() [2/2]
Time ns3::FemtoSeconds (uint64_t value) inline
Construct a Time in the indicated unit.
Parameters
[in] value The value
Returns
The Time
Definition at line 1329 of file nstime.h.
References ns3::Time::FromInteger(), and ns3::Time::FS.
Referenced by TimeSimpleTestCase::DoRun(), DataRateTestCase1::DoRun(), and ns3::WifiPhy::GetPayloadDuration().
Hours() [1/2]
Time ns3::Hours (double value) inline
Construct a Time in the indicated unit.
Parameters
[in] value The value
Returns
The Time
Definition at line 1273 of file nstime.h.
References ns3::Time::FromDouble(), and ns3::Time::H.
Referenced by TimeSimpleTestCase::DoRun(), and UanExperiment::SendPackets().
Hours() [2/2]
Time ns3::Hours (int64x64_t value) inline
Construct a Time in the indicated unit.
Parameters
[in] value The value
Returns
The Time
Definition at line 1277 of file nstime.h.
References ns3::Time::From(), and ns3::Time::H.
MicroSeconds() [1/2]
Time ns3::MicroSeconds (int64x64_t value) inline
Construct a Time in the indicated unit.
Parameters
[in] value The value
Returns
The Time
Definition at line 1309 of file nstime.h.
References ns3::Time::From(), and ns3::Time::US.
MicroSeconds() [2/2]
Time ns3::MicroSeconds (uint64_t value) inline
Construct a Time in the indicated unit.
Parameters
[in] value The value
Returns
The Time
Definition at line 1305 of file nstime.h.
References ns3::Time::FromInteger(), and ns3::Time::US.
Referenced by ns3::Backoff::Backoff(), Ipv4DeduplicationTestSuite::Ipv4DeduplicationTestSuite(), ChannelAccessManagerTest< TxopType >::AddAccessRequestWithAckTimeout(), ChannelAccessManagerTest< TxopType >::AddAccessRequestWithSuccessfullAck(), ChannelAccessManagerTest< TxopType >::AddAckTimeoutReset(), ChannelAccessManagerTest< TxopType >::AddCcaBusyEvt(), ChannelAccessManagerTest< TxopType >::AddNavReset(), ChannelAccessManagerTest< TxopType >::AddNavStart(), ChannelAccessManagerTest< TxopType >::AddRxErrorEvt(), ChannelAccessManagerTest< TxopType >::AddRxInsideSifsEvt(), ChannelAccessManagerTest< TxopType >::AddRxOkEvt(), ChannelAccessManagerTest< TxopType >::AddRxStartEvt(), ChannelAccessManagerTest< TxopType >::AddSwitchingEvt(), ChannelAccessManagerTest< TxopType >::AddTxEvt(), TxDurationTest::CheckHeMuTxDuration(), TxDurationTest::CheckPayloadDuration(), TxDurationTest::CheckTxDuration(), ns3::WifiPhy::Configure80211a(), ns3::WifiPhy::Configure80211b(), ns3::WifiPhy::Configure80211n(), ns3::WifiPhy::Configure80211p(), ns3::WifiMac::ConfigureDcf(), TcpSsThreshRtoTest::ConfigureEnvironment(), TcpLargeTransferLossTest::ConfigureEnvironment(), ns3::WifiPhy::ConfigureHolland(), ns3::MacLow::CreateBlockAckAgreement(), ns3::ApWifiMac::DoInitialize(), SimulatorEventsTestCase::DoRun(), ThreadedSimulatorEventsTestCase::DoRun(), TimeSimpleTestCase::DoRun(), ns3::tests::WatchdogTestCase::DoRun(), RttEstimatorTestCase::DoRun(), LrWpanDataIfsTestCase::DoRun(), DataRateTestCase1::DoRun(), WifiMsduAggregatorThroughputTest::DoRun(), BlockAckAggregationDisabledTest::DoRun(), SpectrumWifiPhyBasicTest::DoRun(), TxDurationTest::DoRun(), PreservePacketsInAmpdus::DoRun(), TestThresholdPreambleDetectionWithoutFrameCapture::DoRun(), TestThresholdPreambleDetectionWithFrameCapture::DoRun(), TestSimpleFrameCaptureModel::DoRun(), TestPhyHeadersReception::DoRun(), TestAmpduReception::DoRun(), DcfImmediateAccessBroadcastTestCase::DoRun(), QosFragmentationTestCase::DoRun(), TestThresholdPreambleDetectionWithFrameCapture::DoSetup(), TestSimpleFrameCaptureModel::DoSetup(), TestAmpduReception::DoSetup(), ThreadedSimulatorEventsTestCase::EventA(), SimulatorEventsTestCase::EventB(), ThreadedSimulatorEventsTestCase::EventB(), ThreadedSimulatorEventsTestCase::EventC(), ThreadedSimulatorEventsTestCase::EventD(), ChannelAccessManagerTest< TxopType >::ExpectBusy(), ns3::MeshWifiBeacon::GetBeaconInterval(), ns3::SubscriberStationNetDevice::GetDefaultLostDlMapInterval(), ns3::WifiMacHeader::GetDuration(), ns3::InterferenceHelper::GetEnergyDuration(), ns3::WifiPhy::GetPayloadDuration(), ns3::WifiPhy::GetPhyHeaderDuration(), ns3::WifiPhy::GetPhyHtSigHeaderDuration(), ns3::WifiPhy::GetPhyPreambleDuration(), ns3::WifiPhy::GetPhySigA1Duration(), ns3::WifiPhy::GetPhySigA2Duration(), ns3::WifiPhy::GetPhySigBDuration(), ns3::WifiPhy::GetPhyTrainingSymbolDuration(), ns3::GetPpduMaxTime(), ns3::WifiPhy::GetPreambleDetectionDuration(), ns3::WifiPhy::GetStartOfPacketDuration(), ns3::WifiPpdu::GetTxDuration(), ns3::dot11s::HwmpProtocol::GetTypeId(), ns3::dot11s::PeerLink::GetTypeId(), ns3::DpdkNetDevice::GetTypeId(), ns3::ApWifiMac::GetTypeId(), ns3::FrameCaptureModel::GetTypeId(), ns3::WifiPhy::GetTypeId(), ns3::LrWpanMac::McpsDataRequest(), ChannelAccessManagerTest< TxopType >::NotifyAccessGranted(), ChannelAccessManagerTest< TxopType >::NotifyChannelSwitching(), ns3::BlockAckManager::NotifyGotBlockAck(), PrintPsrVsCollisionInterval(), ns3::dsr::DsrRouting::PriorityScheduler(), ns3::PcapFileWrapper::Read(), ns3::dot11s::PeerManagementProtocolMac::Receive(), ns3::StaWifiMac::Receive(), ns3::dot11s::HwmpProtocol::ReceivePrep(), ns3::dot11s::HwmpProtocol::ReceivePreq(), ns3::dsdv::RoutingProtocol::RecvDsdv(), ns3::MacLow::ResetBlockAckInactivityTimerIfNeeded(), ns3::dsdv::RoutingProtocol::RouteOutput(), Experiment::Run(), TestDlOfdmaPhyTransmission::RunOne(), Bug2470TestCase::RunSubtest(), ns3::StaWifiMac::ScanningTimeout(), ThreadedSimulatorEventsTestCase::SchedulingThread(), Ipv4DynamicGlobalRoutingTestCase::SendData(), ns3::ApWifiMac::SendOneBeacon(), ns3::dsdv::RoutingProtocol::SendPeriodicUpdate(), ns3::aodv::RoutingProtocol::SendRequest(), TestInterBssConstantObssPdAlgo::SetupSimulation(), ns3::dsdv::RoutingProtocol::Start(), ns3::LteChunkProcessor::Start(), ChannelAccessManagerTest< TxopType >::StartTest(), ns3::MultiModelSpectrumChannel::StartTx(), ns3::SingleModelSpectrumChannel::StartTx(), ns3::dot11s::PeerManagementProtocol::TuToTime(), ns3::BlockAckManager::UpdateAgreement(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), ns3::StaWifiMac::UpdateApInfoFromBeacon(), and ns3::StaWifiMac::UpdateApInfoFromProbeResp().
MilliSeconds() [1/2]
Time ns3::MilliSeconds (int64x64_t value) inline
Construct a Time in the indicated unit.
Parameters
[in] value The value
Returns
The Time
Definition at line 1301 of file nstime.h.
References ns3::Time::From(), and ns3::Time::MS.
MilliSeconds() [2/2]
Time ns3::MilliSeconds (uint64_t value) inline
Construct a Time in the indicated unit.
Parameters
[in] value The value
Returns
The Time
Definition at line 1297 of file nstime.h.
References ns3::Time::FromInteger(), and ns3::Time::MS.
Referenced by LteCellSelectionTestSuite::LteCellSelectionTestSuite(), LteX2HandoverTestSuite::LteX2HandoverTestSuite(), TcpDctcpTestSuite::TcpDctcpTestSuite(), TcpHtcpTestSuite::TcpHtcpTestSuite(), TcpHyblaTestSuite::TcpHyblaTestSuite(), TcpIllinoisTestSuite::TcpIllinoisTestSuite(), ns3::TcpLedbat::TcpLedbat(), TcpLedbatTestSuite::TcpLedbatTestSuite(), ns3::TcpLpTestSuite::TcpLpTestSuite(), TcpVegasTestSuite::TcpVegasTestSuite(), TcpVenoTestSuite::TcpVenoTestSuite(), TcpYeahTestSuite::TcpYeahTestSuite(), ThreeGppHttpClientServerTestSuite::ThreeGppHttpClientServerTestSuite(), ns3::DefaultChannelScheduler::AssignExtendedAccess(), ns3::LrWpanHelper::AssociateToBeaconPan(), ns3::BSSchedulerRtps::BSSchedulerUGSConnection(), ns3::MinstrelHtWifiManager::CalculateRetransmits(), CalculateThroughput(), ns3::dsr::DsrRouting::CancelPacketTimerNextHop(), TimestampValueTestCase::Check(), ns3::ShowProgress::CheckProgress(), CheckT1QueueSize(), CheckT2QueueSize(), ns3::ServiceFlow::CleanUpQueue(), ns3::LteEnbRrc::ConfigureCell(), TcpAdvertisedWindowTest::ConfigureEnvironment(), TcpAdvWindowOnLossTest::ConfigureEnvironment(), TcpBytesInFlightTest::ConfigureEnvironment(), TcpLinuxRenoSSTest::ConfigureEnvironment(), TcpPacingTest::ConfigureEnvironment(), TcpRateLinuxWithSocketsTest::ConfigureEnvironment(), TcpSsThreshRtoTest::ConfigureEnvironment(), TcpRttEstimationTest::ConfigureEnvironment(), TcpZeroWindowTest::ConfigureEnvironment(), ns3::TcpGeneralTest::ConfigureEnvironment(), ns3::TcpCloseWithLossTestCase::ConfigureProperties(), LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::ConnectionReconfigurationEnb(), LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::ConnectionReconfigurationUe(), CoDelQueueDiscBasicMark::Dequeue(), ns3::UplinkSchedulerMBQoS::DetermineDeadline(), LteFrAreaTestCase::DlDataRxStart(), CarrierAggregationTestCase::DlScheduling(), LteCqiGenerationTestCase::DlScheduling(), LteCqiGenerationDlPowerControlTestCase::DlScheduling(), LteInterferenceTestCase::DlScheduling(), LtePathlossModelSystemTestCase::DlScheduling(), ns3::LteEnbMac::DoAllocateNcRaPreamble(), ns3::Icmpv6L4Protocol::DoDAD(), ns3::aodv::RoutingProtocol::DoInitialize(), ns3::LteRlcAm::DoNotifyTxOpportunity(), ns3::LteRlcTm::DoNotifyTxOpportunity(), ns3::LteRlcUm::DoNotifyTxOpportunity(), ns3::LteRlcAm::DoReceivePdu(), ns3::aodv::RrepHeaderTest::DoRun(), ns3::aodv::AodvRtableEntryTest::DoRun(), LteCellSelectionTestCase::DoRun(), LteUeMeasurementsPiecewiseTestCase1::DoRun(), LteUeMeasurementsPiecewiseTestCase2::DoRun(), LteUeMeasurementsPiecewiseTestCase3::DoRun(), LteUeMeasurementsHandoverTestCase::DoRun(), LteHandoverTargetTestCase::DoRun(), ThreeGppV2vUrbanLosNlosvChCondModelTestCase::DoRun(), ThreeGppV2vHighwayLosNlosvChCondModelTestCase::DoRun(), TimeSimpleTestCase::DoRun(), DhcpTestCase::DoRun(), RttEstimatorTestCase::DoRun(), TcpHtcpIncrementTest::DoRun(), TcpVegasTest::DoRun(), TcpVenoTest::DoRun(), EpcS1uDlTestCase::DoRun(), EpcS1uUlTestCase::DoRun(), LenaCqaFfMacSchedulerTestCase1::DoRun(), LenaCqaFfMacSchedulerTestCase2::DoRun(), ns3::LenaDeactivateBearerTestCase::DoRun(), LenaFdTbfqFfMacSchedulerTestCase1::DoRun(), LenaFdTbfqFfMacSchedulerTestCase2::DoRun(), LteStrictFrAreaTestCase::DoRun(), LteSoftFrAreaTestCase::DoRun(), LteSoftFfrAreaTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LenaPssFfMacSchedulerTestCase1::DoRun(), LenaPssFfMacSchedulerTestCase2::DoRun(), LteRlcAmE2eTestCase::DoRun(), LenaTdTbfqFfMacSchedulerTestCase1::DoRun(), LenaTdTbfqFfMacSchedulerTestCase2::DoRun(), LteUplinkOpenLoopPowerControlTestCase::DoRun(), LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun(), LteRrcConnectionEstablishmentTestCase::DoRun(), LteRrcConnectionEstablishmentErrorTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), LteX2HandoverTestCase::DoRun(), ThreeGppChannelConditionModelTestCase::DoRun(), V2vUrbanProbChCondModelTestCase::DoRun(), V2vHighwayProbChCondModelTestCase::DoRun(), ThreeGppChannelMatrixComputationTest::DoRun(), ThreeGppChannelMatrixUpdateTest::DoRun(), ThreeGppSpectrumPropagationLossModelTest::DoRun(), CsmaBridgeTestCase::DoRun(), CsmaBroadcastTestCase::DoRun(), CsmaMulticastTestCase::DoRun(), CsmaOneSubnetTestCase::DoRun(), CsmaPacketSocketTestCase::DoRun(), CsmaPingTestCase::DoRun(), CsmaRawIpSocketTestCase::DoRun(), FqCoDelQueueDiscECNMarking::DoRun(), FqCoDelQueueDiscL4sMode::DoRun(), Ns3TcpCwndTestCase2::DoRun(), Issue211Test::DoRun(), CoDelQueueDiscControlLawTest::DoRun(), CoDelQueueDiscBasicMark::DoRun(), TcFlowControlTestCase::DoRun(), ChannelCoordinationTestCase::DoRun(), AnnexC_TestCase::DoRun(), WifiErrorRateModelsTestCaseMimo::DoRun(), ns3::LteEnbPhy::DoSetSrsConfigurationIndex(), ns3::LteUePhy::DoSetSrsConfigurationIndex(), ns3::TcpOptionTS::ElapsedTimeFromTsValue(), ns3::LteRlcAm::ExpirePollRetransmitTimer(), ns3::LteRlcTm::ExpireRbsTimer(), ns3::LteRlcUm::ExpireRbsTimer(), ns3::ChannelCoordinator::GetDefaultCchInterval(), ns3::ChannelCoordinator::GetDefaultGuardInterval(), ns3::ChannelCoordinator::GetDefaultSchInterval(), ns3::ChannelCoordinator::GetIntervalTime(), ns3::aodv::RrepHeader::GetLifeTime(), ns3::ThreeGppHttpVariables::GetTypeId(), ns3::dsr::DsrRouting::GetTypeId(), ns3::A3RsrpHandoverAlgorithm::GetTypeId(), ns3::ThreeGppChannelModel::GetTypeId(), ns3::aodv::RoutingProtocol::GetTypeId(), ns3::Ipv4L3Protocol::GetTypeId(), ns3::TcpCubic::GetTypeId(), ns3::TcpHybla::GetTypeId(), ns3::TcpLedbat::GetTypeId(), ns3::TcpSocketBase::GetTypeId(), ns3::LteEnbRrc::GetTypeId(), ns3::LteRlcAm::GetTypeId(), ns3::LteRlcUm::GetTypeId(), ns3::LteUePhy::GetTypeId(), ns3::LteUeRrc::GetTypeId(), ns3::ThreeGppChannelConditionModel::GetTypeId(), ns3::SpectrumAnalyzer::GetTypeId(), ns3::PieQueueDisc::GetTypeId(), ns3::RedQueueDisc::GetTypeId(), ns3::UanMacCw::GetTypeId(), ns3::MinstrelHtWifiManager::GetTypeId(), ns3::QosTxop::GetTypeId(), ns3::RrpaaWifiManager::GetTypeId(), ns3::StaWifiMac::GetTypeId(), ns3::Txop::GetTypeId(), ns3::WifiMacQueue::GetTypeId(), ns3::SubscriberStationNetDevice::GetTypeId(), ns3::Radvd::HandleRead(), TcpVegasTest::IncreaseWindow(), ns3::BaseStationNetDevice::InitBaseStationNetDevice(), ns3::SubscriberStationNetDevice::InitSubscriberStationNetDevice(), ns3::ArpL3Protocol::Lookup(), ns3::LteUeRrc::MeasurementReportTriggering(), ns3::ChannelCoordinator::NeedTimeToCchInterval(), ns3::ChannelCoordinator::NeedTimeToGuardInterval(), ns3::ChannelCoordinator::NeedTimeToSchInterval(), ns3::TcpLp::PktsAcked(), LteUplinkPowerControlTestCase::PucchTxPowerTrace(), LteUplinkPowerControlTestCase::PuschTxPowerTrace(), ns3::MinstrelWifiManager::RateInit(), ns3::ThreeGppHttpClient::ReceiveEmbeddedObject(), ns3::SixLowPanNetDevice::ReceiveFromDevice(), ns3::ThreeGppHttpClient::ReceiveMainObject(), LteUeMeasurementsTestCase::RecvMeasurementReport(), ns3::aodv::RoutingProtocol::RecvRequest(), LteUeMeasurementsTestCase::ReportUeMeasurements(), Experiment::Run(), TestDlOfdmaPhyTransmission::RunOne(), ThreeGppShadowingTestCase::RunTest(), ns3::UplinkSchedulerMBQoS::Schedule(), ns3::dsr::DsrRouting::ScheduleInterRequest(), ns3::BSSchedulerSimple::SelectConnection(), ns3::SSScheduler::SelectConnection(), ns3::dsr::DsrRouting::Send(), ns3::Radvd::Send(), ns3::UdpTraceClient::Send(), ns3::aodv::RoutingProtocol::SendHello(), ns3::LteUeRrc::SendMeasurementReport(), ns3::Icmpv6L4Protocol::SendNS(), Ipv4DeduplicationTest::SendPacket(), ns3::dsr::DsrRouting::SendPacketFromBuffer(), ns3::dsdv::RoutingProtocol::SendPacketFromQueue(), ns3::LteUeMac::SendRaPreamble(), ns3::aodv::RoutingProtocol::SendRequest(), ns3::aodv::RoutingProtocol::SendRerrMessage(), ns3::Icmpv6L4Protocol::SendRS(), ns3::VsaManager::SendVsa(), ns3::NscTcpL4Protocol::SetNode(), ns3::AmpduTag::SetRemainingAmpduDuration(), VanetRoutingExperiment::SetupWaveMessages(), LteUplinkPowerControlTestCase::SrsTxPowerTrace(), LteFrAreaTestCase::UlDataRxStart(), LteCqiGenerationTestCase::UlScheduling(), LteCqiGenerationDlPowerControlTestCase::UlScheduling(), LteInterferenceTestCase::UlScheduling(), and CarrierAggregationTestCase::UlScheduling().
Minutes() [1/2]
Time ns3::Minutes (double value) inline
Construct a Time in the indicated unit.
Parameters
[in] value The value
Returns
The Time
Definition at line 1281 of file nstime.h.
References ns3::Time::FromDouble(), and ns3::Time::MIN.
Referenced by TimeSimpleTestCase::DoRun().
Minutes() [2/2]
Time ns3::Minutes (int64x64_t value) inline
Construct a Time in the indicated unit.
Parameters
[in] value The value
Returns
The Time
Definition at line 1285 of file nstime.h.
References ns3::Time::From(), and ns3::Time::MIN.
NanoSeconds() [1/2]
Time ns3::NanoSeconds (int64x64_t value) inline
Construct a Time in the indicated unit.
Parameters
[in] value The value
Returns
The Time
Definition at line 1317 of file nstime.h.
References ns3::Time::From(), and ns3::Time::NS.
NanoSeconds() [2/2]
Time ns3::NanoSeconds (uint64_t value) inline
Construct a Time in the indicated unit.
Parameters
[in] value The value
Returns
The Time
Definition at line 1313 of file nstime.h.
References ns3::Time::FromInteger(), and ns3::Time::NS.
Referenced by Bench::Cb(), TxDurationTest::CheckHeMuTxDuration(), RttEstimatorTestCase::CheckValuesWithTolerance(), TcpPacingTest::ConfigureEnvironment(), TimestampTag::Deserialize(), ns3::PdcpTag::Deserialize(), ns3::RlcTag::Deserialize(), ns3::ConstantRateWifiManager::DoGetDataTxVector(), ns3::ConstantRateWifiManager::DoGetRtsTxVector(), ns3::SimpleOfdmWimaxPhy::DoGetTransmissionTime(), TimeSimpleTestCase::DoRun(), DataRateTestCase1::DoRun(), TxDurationTest::DoRun(), TestDlOfdmaPhyTransmission::DoRun(), TestThresholdPreambleDetectionWithoutFrameCapture::DoRun(), TestThresholdPreambleDetectionWithFrameCapture::DoRun(), TestPhyHeadersReception::DoRun(), TestAmpduReception::DoRun(), ns3::WifiPhy::EndReceive(), ns3::MacLow::ForwardDown(), ns3::BsmApplication::GenerateWaveTraffic(), ns3::RegularWifiMac::GetHeCapabilities(), ns3::WifiPhy::GetPayloadDuration(), ns3::WifiPpdu::GetTxDuration(), ns3::HeConfiguration::GetTypeId(), ns3::RedQueueDisc::InitializeParams(), ns3::Synchronizer::NanosecondToTimeStep(), ns3::PcapFileWrapper::Read(), ns3::MacLow::ReceiveOk(), Bench::RunBench(), TestDlOfdmaPhyTransmission::RunOne(), ns3::MacLow::RxStartIndication(), ns3::WifiPhy::ScheduleEndOfMpdus(), ns3::HeConfiguration::SetGuardInterval(), ns3::BsmApplication::StartApplication(), ns3::WifiPhy::StartReceivePayload(), and TcpPacingTest::Tx().
PicoSeconds() [1/2]
Time ns3::PicoSeconds (int64x64_t value) inline
Construct a Time in the indicated unit.
Parameters
[in] value The value
Returns
The Time
Definition at line 1325 of file nstime.h.
References ns3::Time::From(), and ns3::Time::PS.
PicoSeconds() [2/2]
Time ns3::PicoSeconds (uint64_t value) inline
Construct a Time in the indicated unit.
Parameters
[in] value The value
Returns
The Time
Definition at line 1321 of file nstime.h.
References ns3::Time::FromInteger(), and ns3::Time::PS.
Referenced by TimeSimpleTestCase::DoRun(), and DataRateTestCase1::DoRun().
Seconds() [1/2]
Time ns3::Seconds (double value) inline
Construct a Time in the indicated unit.
Parameters
[in] value The value
Returns
The Time
Definition at line 1289 of file nstime.h.
References ns3::Time::FromDouble(), and ns3::Time::S.
Referenced by ns3::AcousticModemEnergyModel::AcousticModemEnergyModel(), AodvRegressionTestSuite::AodvRegressionTestSuite(), ns3::BasicEnergySource::BasicEnergySource(), CarrierAggregationConfigTestSuite::CarrierAggregationConfigTestSuite(), ns3::CsmaNetDevice::CsmaNetDevice(), ns3::DistributedSimulatorImpl::DistributedSimulatorImpl(), ns3::dsr::DsrRouting::DsrRouting(), ns3::ErrorChannel::ErrorChannel(), LenaTestPhyErrorModelSuite::LenaTestPhyErrorModelSuite(), LrWpanAckTestCase::LrWpanAckTestCase(), ns3::LrWpanPhy::LrWpanPhy(), LteHandoverDelayTestSuite::LteHandoverDelayTestSuite(), LteRadioLinkFailureTestSuite::LteRadioLinkFailureTestSuite(), LteRrcTestSuite::LteRrcTestSuite(), ns3::LteTestMac::LteTestMac(), LteUeMeasurementsHandoverTestSuite::LteUeMeasurementsHandoverTestSuite(), LteX2HandoverMeasuresTestSuite::LteX2HandoverMeasuresTestSuite(), Ns2MobilityHelperTestSuite::Ns2MobilityHelperTestSuite(), ns3::NullMessageSimulatorImpl::NullMessageSimulatorImpl(), ns3::RvBatteryModel::RvBatteryModel(), ns3::ServiceFlowRecord::ServiceFlowRecord(), ns3::SimpleDeviceEnergyModel::SimpleDeviceEnergyModel(), TcpHyblaTestSuite::TcpHyblaTestSuite(), TcpRtoTestSuite::TcpRtoTestSuite(), ns3::UanPdp::UanPdp(), ns3::UplinkSchedulerRtps::UplinkSchedulerRtps(), ns3::UplinkSchedulerSimple::UplinkSchedulerSimple(), ns3::WimaxNetDevice::WimaxNetDevice(), ns3::Ipv6Interface::AddAddress(), ns3::Node::AddApplication(), ns3::Node::AddDevice(), FqCoDelQueueDiscL4sMode::AddPacketWithDelay(), Ns2MobilityHelperTest::AddReferencePoint(), ns3::LteEnbRrc::AddUeMeasReportConfig(), Experiment::AdvancePosition(), AdvancePosition(), OcbWifiMacTestCase::AdvancePosition(), NodeStatistics::AdvancePosition(), TcpTimeRtoTest::AfterRTOExpired(), ns3::UplinkSchedulerMBQoS::AllocateInitialRangingInterval(), ns3::UplinkSchedulerRtps::AllocateInitialRangingInterval(), ns3::UplinkSchedulerSimple::AllocateInitialRangingInterval(), Experiment::ApplicationSetup(), ns3::UanMacRc::Associate(), ns3::UanMacRc::AssociateTimeout(), ns3::LrWpanMac::BeaconSearchTimeout(), ns3::RandomDirection2dMobilityModel::BeginPause(), ns3::RandomWaypointMobilityModel::BeginWalk(), ns3::SteadyStateRandomWaypointMobilityModel::BeginWalk(), BuildAppsTest(), ns3::UanPhyCalcSinrFhFsk::CalcSinrDb(), ns3::DataRate::CalculateBitsTxTime(), ns3::DataRate::CalculateBytesTxTime(), ns3::DistributedSimulatorImpl::CalculateLookAhead(), ns3::MacLow::CalculateOverheadTxTime(), ns3::PieQueueDisc::CalculateP(), ns3::WifiPhy::CalculateTxDuration(), ns3::LrWpanPhy::CalculateTxTime(), ns3::PyViz::CallbackStopSimulation(), ns3::LrWpanCsmaCa::CanProceed(), DsdvManetExample::CaseRun(), ChangeSignalAndReportRate(), TcpNewRenoCongAvoidNormalTest::Check(), TimestampValueTestCase::Check(), Ns2MobilityHelperTest::CheckInitialPositions(), CheckQueueDiscSize(), CheckQueueSize(), ns3::aodv::AodvRqueueTest::CheckSizeLimit(), DsrSendBuffTest::CheckSizeLimit(), NodeStatistics::CheckStatistics(), CheckT1QueueSize(), CheckT2QueueSize(), RoutingExperiment::CheckThroughput(), Experiment::CheckThroughput(), DsdvManetExample::CheckThroughput(), VanetRoutingExperiment::CheckThroughput(), ThreeGppHttpObjectTestCase::ClientRxEmbeddedObjectCallback(), ThreeGppHttpObjectTestCase::ClientRxMainObjectCallback(), TcpAdvertisedWindowTest::ConfigureEnvironment(), TcpAdvWindowOnLossTest::ConfigureEnvironment(), TcpBytesInFlightTest::ConfigureEnvironment(), TcpPacingTest::ConfigureEnvironment(), TcpRateLinuxWithSocketsTest::ConfigureEnvironment(), TcpRttEstimationTest::ConfigureEnvironment(), TcpZeroWindowTest::ConfigureEnvironment(), ns3::TcpGeneralTest::ConfigureEnvironment(), TcpLargeTransferLossTest::ConfigureEnvironment(), BatteryLifetimeTest::ConstantLoadTest(), ns3::BriteTopologyHelper::ConstructTopology(), Emitter::Count(), WaypointMobilityModelAddWaypointTest::CourseChangeCallback(), CreateBulkFlow(), Bug772ChainTest::CreateDevices(), HwmpProactiveRegressionTest::CreateDevices(), HwmpReactiveRegressionTest::CreateDevices(), HwmpSimplestRegressionTest::CreateDevices(), HwmpDoRfRegressionTest::CreateDevices(), PeerManagementProtocolRegressionTest::CreateDevices(), FlameRegressionTest::CreateDevices(), ns3::UanPdp::CreateImpulsePdp(), BatteryLifetimeTest::CreateLoadProfiles(), MeshTest::CreateNodes(), HwmpReactiveRegressionTest::CreateNodes(), HwmpSimplestRegressionTest::CreateNodes(), ns3::olsr::Bug780Test::CreateNodes(), WifiTest::CreateOne(), CreateOnOffFlow(), TcpZeroWindowTest::CreateReceiverSocket(), TcpFastRetrTest::CreateSenderSocket(), TcpRtoTest::CreateSenderSocket(), ns3::WimaxHelper::CreateUplinkScheduler(), TcpNewRenoCongAvoidNormalTest::CWndTrace(), ns3::RadioEnvironmentMapHelper::DelayedInstall(), BasicEnergyDepletionTest::DepletionTestCase(), FqCoDelQueueDiscECNMarking::DequeueWithDelay(), FqCoDelQueueDiscL4sMode::DequeueWithDelay(), PieQueueDiscTestCase::DequeueWithDelay(), ns3::UanHeaderRcData::Deserialize(), ns3::UanHeaderRcRts::Deserialize(), ns3::UanHeaderRcCtsGlobal::Deserialize(), ns3::UanHeaderRcCts::Deserialize(), ns3::RvBatteryModel::Discharge(), ns3::PieQueueDisc::DoDequeue(), ns3::ThreeGppChannelConditionModel::DoDispose(), ns3::PieQueueDisc::DoEnqueue(), ns3::SimpleOfdmWimaxPhy::DoGetFrameDuration(), ns3::SimpleOfdmWimaxPhy::DoGetNrBytes(), ns3::SimpleOfdmWimaxPhy::DoGetNrSymbols(), ns3::SimpleOfdmWimaxPhy::DoGetTransmissionTime(), ns3::Rip::DoInitialize(), ns3::RipNg::DoInitialize(), ns3::dot11s::HwmpProtocol::DoInitialize(), ns3::MeshWifiInterfaceMac::DoInitialize(), ns3::LteEnbPhy::DoInitialize(), ns3::LteUePhy::DoInitialize(), Emitter::DoInitialize(), ns3::RandomWalk2dOutdoorMobilityModel::DoInitializePrivate(), ns3::RandomWalk2dMobilityModel::DoInitializePrivate(), ns3::RandomWaypointMobilityModel::DoInitializePrivate(), ns3::SteadyStateRandomWaypointMobilityModel::DoInitializePrivate(), UanTest::DoOnePhyTest(), UanTest::DoPhyTests(), ns3::LteRlcAm::DoReportBufferStatus(), ns3::aodv::IdCacheTest::DoRun(), ns3::aodv::NeighborTest::DoRun(), ns3::aodv::RrepHeaderTest::DoRun(), ns3::aodv::QueueEntryTest::DoRun(), ns3::aodv::AodvRqueueTest::DoRun(), ns3::aodv::AodvRtableEntryTest::DoRun(), ns3::aodv::AodvRtableTest::DoRun(), Bug772ChainTest::DoRun(), ns3::aodv::LoopbackTestCase::DoRun(), ThreeGppHttpObjectTestCase::DoRun(), LteCellSelectionTestCase::DoRun(), LteRadioLinkFailureTestCase::DoRun(), LteUeMeasurementsPiecewiseTestCase1::DoRun(), LteUeMeasurementsPiecewiseTestCase2::DoRun(), LteUeMeasurementsPiecewiseTestCase3::DoRun(), LteUeMeasurementsHandoverTestCase::DoRun(), LteHandoverTargetTestCase::DoRun(), HwmpRtableTest::DoRun(), FlameRtableTest::DoRun(), MeshInformationElementVectorBist::DoRun(), BulkSendBasicTestCase::DoRun(), BulkSendSeqTsSizeTestCase::DoRun(), UdpClientServerTestCase::DoRun(), UdpTraceClientServerTestCase::DoRun(), UdpEchoClientSetFillTestCase::DoRun(), BriteTopologyFunctionTestCase::DoRun(), OutdoorRandomWalkTestCase::DoRun(), AttributeTestCase< T >::DoRun(), SimulatorTemplateTestCase::DoRun(), ThreadedSimulatorEventsTestCase::DoRun(), TimeSimpleTestCase::DoRun(), TimerStateTestCase::DoRun(), TimerTemplateTestCase::DoRun(), ns3::tests::WatchdogTestCase::DoRun(), DsdvTableTestCase::DoRun(), DsrCacheEntryTest::DoRun(), DsrSendBuffTest::DoRun(), BasicEnergyHarvesterTestCase::DoRun(), LiIonEnergyTestCase::DoRun(), DhcpTestCase::DoRun(), Ipv4DeduplicationPerformanceTest::DoRun(), Ipv4FragmentationTest::DoRun(), Ipv4DynamicGlobalRoutingTestCase::DoRun(), Ipv4PacketInfoTagTest::DoRun(), Ipv4RipSplitHorizonStrategyTest::DoRun(), Ipv6FragmentationTest::DoRun(), Ipv6PacketInfoTagTest::DoRun(), Ipv6RipngSplitHorizonStrategyTest::DoRun(), RttEstimatorTestCase::DoRun(), TcpBicIncrementTest::DoRun(), TcpBicDecrementTest::DoRun(), TcpDctcpToLinuxReno::DoRun(), ns3::TcpGeneralTest::DoRun(), TcpLedbatToNewReno::DoRun(), TcpLedbatIncrementTest::DoRun(), TcpLedbatDecrementTest::DoRun(), ns3::TcpLpToNewReno::DoRun(), ns3::TcpLpInferenceTest1::DoRun(), ns3::TcpLpInferenceTest2::DoRun(), TcpRateLinuxBasicTest::DoRun(), TcpRateLinuxWithBufferTest::DoRun(), TimestampValueTestCase::DoRun(), TcpTxBufferTestCase::DoRun(), LrWpanCollisionTestCase::DoRun(), LrWpanEdTestCase::DoRun(), LrWpanErrorDistanceTestCase::DoRun(), LrWpanDataIfsTestCase::DoRun(), LrWpanSlottedCsmacaTestCase::DoRun(), EpcS1uDlTestCase::DoRun(), EpcS1uUlTestCase::DoRun(), CarrierAggregationTestCase::DoRun(), LenaCqaFfMacSchedulerTestCase1::DoRun(), LenaCqaFfMacSchedulerTestCase2::DoRun(), LteCqiGenerationTestCase::DoRun(), LteCqiGenerationDlPowerControlTestCase::DoRun(), ns3::LenaDeactivateBearerTestCase::DoRun(), LteDownlinkPowerControlTestCase::DoRun(), LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::DoRun(), LteDownlinkDataSinrTestCase::DoRun(), LteDownlinkCtrlSinrTestCase::DoRun(), LenaFdBetFfMacSchedulerTestCase1::DoRun(), LenaFdBetFfMacSchedulerTestCase2::DoRun(), LenaFdMtFfMacSchedulerTestCase::DoRun(), LenaFdTbfqFfMacSchedulerTestCase1::DoRun(), LenaFdTbfqFfMacSchedulerTestCase2::DoRun(), LteHardFrTestCase::DoRun(), LteStrictFrTestCase::DoRun(), LteStrictFrAreaTestCase::DoRun(), LteSoftFrAreaTestCase::DoRun(), LteSoftFfrAreaTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LenaHarqTestCase::DoRun(), LteInterferenceHardFrTestCase::DoRun(), LteInterferenceStrictFrTestCase::DoRun(), LteInterferenceTestCase::DoRun(), LteIpv6RoutingTestCase::DoRun(), LteLinkAdaptationTestCase::DoRun(), LenaMimoTestCase::DoRun(), LtePathlossModelSystemTestCase::DoRun(), LenaPfFfMacSchedulerTestCase1::DoRun(), LenaPfFfMacSchedulerTestCase2::DoRun(), LenaDataPhyErrorModelTestCase::DoRun(), LenaDlCtrlPhyErrorModelTestCase::DoRun(), LenaPssFfMacSchedulerTestCase1::DoRun(), LenaPssFfMacSchedulerTestCase2::DoRun(), LteRlcAmE2eTestCase::DoRun(), LteRlcAmTransmitterOneSduTestCase::DoRun(), LteRlcAmTransmitterSegmentationTestCase::DoRun(), LteRlcAmTransmitterConcatenationTestCase::DoRun(), LteRlcAmTransmitterReportBufferStatusTestCase::DoRun(), LteRlcUmE2eTestCase::DoRun(), LteRlcUmTransmitterOneSduTestCase::DoRun(), LteRlcUmTransmitterSegmentationTestCase::DoRun(), LteRlcUmTransmitterConcatenationTestCase::DoRun(), LteRlcUmTransmitterReportBufferStatusTestCase::DoRun(), LenaRrFfMacSchedulerTestCase::DoRun(), LenaTdBetFfMacSchedulerTestCase1::DoRun(), LenaTdBetFfMacSchedulerTestCase2::DoRun(), LenaTdMtFfMacSchedulerTestCase::DoRun(), LenaTdTbfqFfMacSchedulerTestCase1::DoRun(), LenaTdTbfqFfMacSchedulerTestCase2::DoRun(), LenaTtaFfMacSchedulerTestCase::DoRun(), LteUeMeasurementsTestCase::DoRun(), LteUplinkOpenLoopPowerControlTestCase::DoRun(), LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun(), LteUplinkDataSinrTestCase::DoRun(), LteUplinkSrsSinrTestCase::DoRun(), LteEnbAntennaTestCase::DoRun(), LteEpcE2eDataTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), LteX2HandoverTestCase::DoRun(), WaypointLazyNotifyFalse::DoRun(), WaypointLazyNotifyTrue::DoRun(), WaypointInitialPositionIsWaypoint::DoRun(), WaypointMobilityModelViaHelper::DoRun(), MobilityTraceTestCase::DoRun(), SteadyStateRandomWaypointTest::DoRun(), WaypointMobilityModelNotifyTest::DoRun(), WaypointMobilityModelAddWaypointTest::DoRun(), ErrorModelSimple::DoRun(), BurstErrorModelSimple::DoRun(), OlsrMidTestCase::DoRun(), OlsrHelloTestCase::DoRun(), OlsrMprTestCase::DoRun(), PointToPointTest::DoRun(), SixlowpanFragmentationTest::DoRun(), SpectrumIdealPhyTestCase::DoRun(), SpectrumInterferenceTestCase::DoRun(), WaveformGeneratorTestCase::DoRun(), ProbeTestCase1::DoRun(), CsmaBridgeTestCase::DoRun(), CsmaBroadcastTestCase::DoRun(), CsmaMulticastTestCase::DoRun(), CsmaOneSubnetTestCase::DoRun(), CsmaPacketSocketTestCase::DoRun(), CsmaPingTestCase::DoRun(), CsmaRawIpSocketTestCase::DoRun(), CsmaStarTestCase::DoRun(), FqCoDelQueueDiscECNMarking::DoRun(), FqCoDelQueueDiscL4sMode::DoRun(), Ns3TcpCwndTestCase1::DoRun(), Ns3TcpCwndTestCase2::DoRun(), Ns3TcpInteroperabilityTestCase::DoRun(), Ns3TcpLossTestCase::DoRun(), Ns3TcpNoDelayTestCase::DoRun(), Ns3TcpSocketTestCase1::DoRun(), Ns3TcpSocketTestCase2::DoRun(), Ns3TcpStateTestCase::DoRun(), NscTcpLossTestCase1::DoRun(), NscTcpLossTestCase2::DoRun(), WifiAcMappingTest::DoRun(), Issue211Test::DoRun(), WifiMsduAggregatorThroughputTest::DoRun(), CoDelQueueDiscControlLawTest::DoRun(), TcFlowControlTestCase::DoRun(), AcousticModemEnergyTestCase::DoRun(), AcousticModemEnergyDepletionTestCase::DoRun(), ChannelCoordinationTestCase::DoRun(), ChannelRoutingTestCase::DoRun(), ChannelAccessTestCase::DoRun(), AnnexC_TestCase::DoRun(), OcbWifiMacTestCase::DoRun(), BlockAckAggregationDisabledTest::DoRun(), SpectrumWifiPhyBasicTest::DoRun(), SpectrumWifiPhyListenerTest::DoRun(), PreservePacketsInAmpdus::DoRun(), TestThresholdPreambleDetectionWithoutFrameCapture::DoRun(), TestThresholdPreambleDetectionWithFrameCapture::DoRun(), TestSimpleFrameCaptureModel::DoRun(), TestPhyHeadersReception::DoRun(), TestAmpduReception::DoRun(), WifiPhyThresholdsWeakWifiSignalTest::DoRun(), WifiPhyThresholdsWeakForeignSignalTest::DoRun(), WifiPhyThresholdsStrongWifiSignalTest::DoRun(), WifiPhyThresholdsStrongForeignSignalTest::DoRun(), InterferenceHelperSequenceTest::DoRun(), DcfImmediateAccessBroadcastTestCase::DoRun(), Bug730TestCase::DoRun(), QosFragmentationTestCase::DoRun(), Bug2222TestCase::DoRun(), Bug2843TestCase::DoRun(), Bug2831TestCase::DoRun(), StaWifiMacScanningTestCase::DoRun(), Issue169TestCase::DoRun(), IdealRateManagerChannelWidthTest::DoRun(), IdealRateManagerMimoTest::DoRun(), Ns3WimaxNetworkEntryTestCase::DoRun(), Ns3WimaxManagementConnectionsTestCase::DoRun(), Ns3WimaxSfCreationTestCase::DoRun(), Ns3WimaxSimpleOFDMTestCase::DoRunOnce(), Ns3WimaxSFTypeTestCase::DoRunOnce(), Ns3WimaxSchedulingTestCase::DoRunOnce(), Ipv4DeduplicationPerformanceTest::DoSendData(), ns3::VsaManager::DoSendVsa(), ns3::SimpleOfdmWimaxPhy::DoSetPhyParameters(), ns3::LteTestMac::DoTransmitPdu(), ns3::RandomWalk2dOutdoorMobilityModel::DoWalk(), ns3::GaussMarkovMobilityModel::DoWalk(), ns3::RandomWalk2dMobilityModel::DoWalk(), ns3::TcpOptionTS::ElapsedTimeFromTsValue(), Emitter::Emit(), LteHandoverDelayTestCase::EnbHandoverEndOkCallback(), ns3::UanMacRcGw::EndCycle(), ns3::BaseStationNetDevice::EndDlSubFrame(), ns3::SimpleOfdmWimaxPhy::EndReceiveFecBlock(), ns3::UanTransducerHd::EndTx(), ns3::BaseStationNetDevice::EndUlSubFrame(), CobaltQueueDiscDropTest::EnqueueWithDelay(), PieQueueDiscTestCase::EnqueueWithDelay(), AredQueueDiscTestCase::EnqueueWithDelay(), anonymous_namespace{sample-show-progress.cc}::Hold::Event(), experiment(), ns3::Icmpv6L4Protocol::FunctionDadTimeout(), ns3::TcpRateLinux::GenerateSample(), GenerateTraffic(), ns3::dot11s::PeerManagementProtocol::GetBeaconTimingElement(), ns3::SimpleOfdmWimaxPhy::GetBlockTransmissionTime(), NodeStatistics::GetCalcTxTime(), ns3::RraaWifiManager::GetCalcTxTime(), ns3::RrpaaWifiManager::GetCalcTxTime(), ns3::RandomPropagationDelayModel::GetDelay(), ns3::ConstantSpeedPropagationDelayModel::GetDelay(), ns3::UanPropModelIdeal::GetDelay(), ns3::UanPropModelThorp::GetDelay(), ns3::WifiPhyStateHelper::GetDelayUntilIdle(), ns3::ThreeGppHttpVariables::GetEmbeddedObjectGenerationDelay(), ns3::aodv::Neighbors::GetExpireTime(), ns3::dsr::DsrRouteCache::GetExpireTime(), ns3::olsr::MessageHeader::Hello::GetHTime(), ns3::ThreeGppHttpVariables::GetMainObjectGenerationDelay(), ns3::WifiRadioEnergyModel::GetMaximumTimeInState(), ns3::ThreeGppHttpVariables::GetParsingTime(), ns3::WifiPhy::GetPayloadDuration(), ns3::LrWpanPhy::GetPpduHeaderTxTime(), ns3::ThreeGppHttpVariables::GetReadingTime(), ns3::MacLow::GetResponseDuration(), ns3::dsdv::RoutingProtocol::GetSettlingTime(), ns3::FlowMonitor::GetStatsForFlow(), LteAggregationThroughputScaleTestCase::GetThroughput(), ns3::LrWpanCsmaCa::GetTimeLeftInCap(), ns3::ArpCache::Entry::GetTimeout(), ns3::SubscriberStationNetDevice::GetTimeToAllocation(), ns3::LrWpanCsmaCa::GetTimeToNextSlot(), ns3::WifiPpdu::GetTxDuration(), ns3::QosTxop::GetTxopRemaining(), ns3::Txop::GetTxopRemaining(), ns3::ThreeGppHttpVariables::GetTypeId(), ns3::dsr::DsrRouting::GetTypeId(), ns3::FlowMonitor::GetTypeId(), ns3::Ping6::GetTypeId(), ns3::Icmpv6L4Protocol::GetTypeId(), ns3::Ipv6ExtensionFragment::GetTypeId(), ns3::Ipv6PmtuCache::GetTypeId(), ns3::LteFfrDistributedAlgorithm::GetTypeId(), ns3::dot11s::HwmpProtocol::GetTypeId(), ns3::flame::FlameProtocol::GetTypeId(), ns3::flame::FlameRtable::GetTypeId(), ns3::MeshWifiInterfaceMac::GetTypeId(), ns3::TraceFadingLossModel::GetTypeId(), ns3::Probe::GetTypeId(), ns3::aodv::RoutingProtocol::GetTypeId(), ns3::UdpClient::GetTypeId(), ns3::UdpEchoClient::GetTypeId(), ns3::BridgeNetDevice::GetTypeId(), ns3::RandomWalk2dOutdoorMobilityModel::GetTypeId(), ns3::RealtimeSimulatorImpl::GetTypeId(), AttributeObjectTest::GetTypeId(), ns3::CsmaChannel::GetTypeId(), ns3::dsdv::RoutingProtocol::GetTypeId(), ns3::BasicEnergyHarvester::GetTypeId(), ns3::BasicEnergySource::GetTypeId(), ns3::LiIonEnergySource::GetTypeId(), ns3::RvBatteryModel::GetTypeId(), ns3::FdNetDevice::GetTypeId(), ns3::DhcpClient::GetTypeId(), ns3::DhcpServer::GetTypeId(), ns3::V4Ping::GetTypeId(), ns3::V4TraceRoute::GetTypeId(), ns3::ArpCache::GetTypeId(), ns3::Ipv4L3Protocol::GetTypeId(), ns3::Rip::GetTypeId(), ns3::RipNg::GetTypeId(), ns3::RttEstimator::GetTypeId(), ns3::TcpHtcp::GetTypeId(), ns3::TcpSocketBase::GetTypeId(), ns3::TcpSocket::GetTypeId(), ns3::NoBackhaulEpcHelper::GetTypeId(), ns3::PointToPointEpcHelper::GetTypeId(), ns3::RadioBearerStatsCalculator::GetTypeId(), EpsBearerTagUdpClient::GetTypeId(), ns3::GaussMarkovMobilityModel::GetTypeId(), ns3::RandomWalk2dMobilityModel::GetTypeId(), ns3::Application::GetTypeId(), ns3::PacketSocketClient::GetTypeId(), ns3::SimpleChannel::GetTypeId(), ns3::olsr::RoutingProtocol::GetTypeId(), ns3::PointToPointChannel::GetTypeId(), ns3::PointToPointNetDevice::GetTypeId(), ns3::SixLowPanNetDevice::GetTypeId(), ns3::TvSpectrumTransmitter::GetTypeId(), ns3::WaveformGenerator::GetTypeId(), ns3::TapBridge::GetTypeId(), ns3::PieQueueDisc::GetTypeId(), ns3::RedQueueDisc::GetTypeId(), ns3::UanMacRcGw::GetTypeId(), ns3::UanMacRc::GetTypeId(), ns3::AthstatsWifiTraceSink::GetTypeId(), ns3::AmrrWifiManager::GetTypeId(), ns3::MinstrelWifiManager::GetTypeId(), ns3::OnoeWifiManager::GetTypeId(), ns3::RraaWifiManager::GetTypeId(), ns3::StaWifiMac::GetTypeId(), ns3::BaseStationNetDevice::GetTypeId(), ns3::UplinkSchedulerMBQoS::GetTypeId(), ns3::SubscriberStationNetDevice::GetTypeId(), ns3::WimaxPhy::GetTypeId(), ns3::olsr::MessageHeader::GetVTime(), GoodputSampling(), ns3::aodv::RoutingProtocol::HelloTimerExpire(), ns3::BaseStationNetDevice::InitBaseStationNetDevice(), ns3::PieQueueDisc::InitializeParams(), ns3::TbfQueueDisc::InitializeParams(), ns3::SubscriberStationNetDevice::InitSubscriberStationNetDevice(), ns3::RadioEnvironmentMapHelper::Install(), ns3::WaveBsmHelper::Install(), ns3::WimaxHelper::Install(), MeshTest::InstallApplication(), AodvExample::InstallApplications(), DsdvManetExample::InstallApplications(), TracerouteExample::InstallApplications(), HwmpProactiveRegressionTest::InstallApplications(), HwmpReactiveRegressionTest::InstallApplications(), HwmpSimplestRegressionTest::InstallApplications(), HwmpDoRfRegressionTest::InstallApplications(), FlameRegressionTest::InstallApplications(), InstallBulkSend(), AodvExample::InstallInternetStack(), TracerouteExample::InstallInternetStack(), DsdvManetExample::InstallInternetStack(), InstallPacketSink(), ns3::Probe::IsEnabled(), ns3::TcpRateOps::TcpRateSample::IsValid(), ns3::olsr::RoutingProtocol::LinkSensing(), ns3::dot11s::HwmpRtable::LookupReactive(), WifiPhyThresholdsTest::MakeForeignSignal(), ns3::LrWpanMac::MlmeSyncRequest(), modify(), ns3::ChannelAccessManager::NeedBackoffUponAccess(), ns3::MacLow::NotifyNav(), ns3::MacLow::NotifyOffNow(), ns3::MacLow::NotifySleepNow(), ns3::MacLow::NotifySwitchingStartNow(), ns3::dsr::IsExpired::operator()(), ns3::aodv::IsExpired::operator()(), ns3::dsdv::IsExpired::operator()(), ns3::LrWpanMac::PdDataConfirm(), ns3::LrWpanMac::PdDataIndication(), ns3::SSLinkManager::PerformBackoff(), ns3::TcpSocketBase::PersistTimeout(), ns3::LrWpanPhy::PlmeCcaRequest(), ns3::LrWpanPhy::PlmeEdRequest(), ns3::LrWpanPhy::PlmeSetTRXStateRequest(), OcbWifiMacTestCase::PostDeviceConfiguration(), AnimationInterfaceTestCase::PrepareNetwork(), AnimationRemainingEnergyTestCase::PrepareNetwork(), PrintCellInfo(), ns3::dsr::DsrRouting::PriorityScheduler(), ns3::BSLinkManager::ProcessRangingRequest(), ns3::SubscriberStationNetDevice::ProcessUlMap(), Progress(), ThreeGppHttpObjectTestCase::ProgressCallback(), ns3::aodv::RoutingTable::Purge(), ns3::dsr::DsrRouteCache::Purge(), ns3::dsr::DsrRouteCache::PurgeLinkNode(), ns3::LrWpanCsmaCa::RandomBackoffDelay(), ns3::MinstrelWifiManager::RateInit(), ns3::TapBridge::ReadCallback(), ns3::UanTransducerHd::Receive(), Bug730TestCase::Receive(), ns3::dsr::DsrRreqTable::RemoveLeastExpire(), ns3::flame::FlameProtocol::RemoveRoutingStuff(), ns3::FlowMonitor::ReportFirstTx(), ns3::FlowMonitor::ReportLastRx(), ns3::aodv::RoutingProtocol::RerrRateLimitTimerExpire(), SampleEmitter::Reschedule(), ns3::aodv::RoutingProtocol::RreqRateLimitTimerExpire(), ns3::UanMacRc::RtsTimeout(), AodvExample::Run(), TracerouteExample::Run(), MeshTest::Run(), VanetRoutingExperiment::Run(), Experiment::Run(), RoutingExperiment::Run(), InterferenceExperiment::Run(), NetAnimExperiment::Run(), AredQueueDiscTestCase::RunAredDiscTest(), CobaltQueueDiscDropTest::RunDropTest(), SpectrumWifiPhyFilterTest::RunOne(), TestDlOfdmaPhyTransmission::RunOne(), Issue40TestCase::RunOne(), WifiTest::RunOne(), ns3::RadioEnvironmentMapHelper::RunOneIteration(), PieQueueDiscTestCase::RunPieTest(), Bug2470TestCase::RunSubtest(), TbfQueueDiscTestCase::RunTbfTest(), ThreeGppShadowingTestCase::RunTest(), ns3::UanMacRc::ScheduleData(), ns3::OnOffApplication::ScheduleNextTx(), ns3::OnOffApplication::ScheduleStartEvent(), ns3::OnOffApplication::ScheduleStopEvent(), MyApp::ScheduleTx(), SimpleSource::ScheduleTx(), ns3::DhcpClient::Select(), ns3::ErrorChannel::Send(), ns3::LoopbackNetDevice::Send(), ns3::SimpleOfdmWimaxChannel::Send(), ns3::BaseStationNetDevice::SendBursts(), ns3::MacLow::SendCtsToSelf(), Bug772ChainTest::SendData(), ns3::aodv::LoopbackTestCase::SendData(), UdpSocketImplTest::SendData(), HwmpProactiveRegressionTest::SendData(), HwmpReactiveRegressionTest::SendData(), HwmpSimplestRegressionTest::SendData(), FlameRegressionTest::SendData(), IcmpEchoReplyTestCase::SendData(), IcmpTimeExceedTestCase::SendData(), IcmpV6EchoReplyTestCase::SendData(), IcmpV6TimeExceedTestCase::SendData(), Ipv4ForwardingTest::SendData(), Ipv4GlobalRoutingSlash32TestCase::SendData(), Ipv4RawSocketImplTest::SendData(), Ipv4RipTest::SendData(), Ipv4RipCountToInfinityTest::SendData(), Ipv4StaticRoutingSlash32TestCase::SendData(), Ipv6ForwardingTest::SendData(), Ipv6RawSocketImplTest::SendData(), Ipv6RipngTest::SendData(), Ipv6RipngCountToInfinityTest::SendData(), SixlowpanHc1ImplTest::SendData(), SixlowpanIphcImplTest::SendData(), Ipv4RawSocketImplTest::SendData_IpHdr(), Ipv4HeaderTest::SendData_IpHdr_Dscp(), HwmpDoRfRegressionTest::SendDataA(), HwmpDoRfRegressionTest::SendDataB(), HwmpDoRfRegressionTest::SendDataC(), UdpSocketImplTest::SendDataTo(), Udp6SocketImplTest::SendDataTo(), ns3::LoopbackNetDevice::SendFrom(), WaveNetDeviceExample::SendIpExample(), ns3::LteUeRrc::SendMeasurementReport(), AcousticModemEnergyTestCase::SendOnePacket(), AcousticModemEnergyDepletionTestCase::SendOnePacket(), Sender::SendPacket(), ns3::UanPhyGen::SendPacket(), ns3::UanMacCw::SendPacket(), UanExperiment::SendPackets(), ChainRegressionTest::SendPing(), ns3::olsr::Bug780Test::SendPing(), ns3::UanMacRc::SendRts(), ns3::MacLow::SendRtsForPacket(), ns3::Rip::SendTriggeredRouteUpdate(), ns3::RipNg::SendTriggeredRouteUpdate(), ns3::LteTestMac::SendTxOpportunity(), ns3::Rip::SendUnsolicitedRouteUpdate(), ns3::RipNg::SendUnsolicitedRouteUpdate(), WaveNetDeviceExample::SendWsaExample(), WaveNetDeviceExample::SendWsmpExample(), ThreeGppHttpObjectTestCase::ServerRxCallback(), ns3::UplinkSchedulerRtps::ServiceUnsolicitedGrants(), ns3::UplinkSchedulerSimple::ServiceUnsolicitedGrants(), ns3::dot11s::PeerLink::SetBeaconInformation(), ns3::dot11s::PeerManagementProtocolMac::SetBeaconShift(), ns3::RandomDirection2dMobilityModel::SetDirectionAndSpeed(), ns3::SetMovement(), ns3::Ipv6PmtuCache::SetPmtuValidityTime(), ns3::SetSchedPosition(), SetTimeout(), ns3::LteTestMac::SetTxOpportunityMode(), UanExperiment::SetupCommunications(), RoutingHelper::SetupRoutingMessages(), TestInterBssConstantObssPdAlgo::SetupSimulation(), VanetRoutingExperiment::SetupWaveMessages(), showPosition(), ns3::PyViz::SimulatorRunUntil(), ns3::aodv::RoutingProtocol::Start(), ns3::LteTestRrc::Start(), anonymous_namespace{sample-simulator.cc}::MyModel::Start(), ns3::SteadyStateRandomWaypointMobilityModel::Start(), ns3::SubscriberStationNetDevice::Start(), ns3::Ping6::StartApplication(), ns3::Radvd::StartApplication(), ns3::UdpClient::StartApplication(), ns3::UdpEchoClient::StartApplication(), ns3::UdpTraceClient::StartApplication(), ns3::DhcpServer::StartApplication(), EpsBearerTagUdpClient::StartApplication(), ns3::BsmApplication::StartApplication(), ns3::LrWpanMac::StartCAP(), ns3::LrWpanMac::StartCFP(), ns3::UanMacRcGw::StartCycle(), ns3::BaseStationNetDevice::StartDlSubFrame(), ns3::LrWpanMac::StartInactivePeriod(), ns3::Ipv6AutoconfiguredPrefix::StartPreferredTimer(), ns3::UanPhyGen::StartRxPacket(), ns3::LteEnbPhy::StartSubFrame(), ns3::BaseStationNetDevice::StartUlSubFrame(), ns3::Ipv6AutoconfiguredPrefix::StartValidTimer(), ns3::ApplicationContainer::StartWithJitter(), BasicEnergyUpdateTest::StateSwitchTest(), ns3::SteadyStateRandomWaypointMobilityModel::SteadyStateBeginWalk(), ns3::LteUePhy::SubframeIndication(), ns3::UanPdp::SumTapsC(), ns3::UanPdp::SumTapsFromMaxC(), ns3::UanPdp::SumTapsFromMaxNc(), ns3::UanPdp::SumTapsNc(), ns3::MeshWifiInterfaceMac::SwitchFrequencyChannel(), ns3::WifiPhyStateHelper::SwitchFromRxAbort(), TcPacketsInQueue(), TestDeterministic(), TimeSimpleTestCase::TestDivisionByDecimalTypes(), TimeSimpleTestCase::TestDivisionByIntegerTypes(), TimeSimpleTestCase::TestMultiplicationByDecimalTypes(), TimeSimpleTestCase::TestMultiplicationByIntegerTypes(), HwmpRtableTest::TestPrecursorAdd(), TestProbabilistic(), PowerRateAdaptationTest::TestRrpaa(), python-unit-tests.TestSimulator::testSchedule(), python-unit-tests.TestSimulator::testScheduleDestroy(), python-unit-tests.TestSimulator::testTimeComparison(), python-unit-tests.TestSimulator::testTimeNumericOperations(), TcpRateLinuxWithBufferTest::TestWithSackBlocks(), ns3::DhcpServer::TimerHandler(), ns3::TcpSocketBase::TimeWait(), ProbeTestCase1::TraceSink(), ns3::UanTransducerHd::Transmit(), TcpTimeRtoTest::Tx(), TcpRttEstimationTest::Tx(), LteHandoverDelayTestCase::UeHandoverEndOkCallback(), ns3::WaypointMobilityModel::Update(), ns3::Ipv4L3Protocol::UpdateDuplicate(), TcpPacingTest::UpdateExpectedInterval(), ns3::MinstrelWifiManager::UpdateStats(), and BatteryLifetimeTest::VariableLoadTest().
Seconds() [2/2]
Time ns3::Seconds (int64x64_t value) inline
Construct a Time in the indicated unit.
Parameters
[in] value The value
Returns
The Time
Definition at line 1293 of file nstime.h.
References ns3::Time::From(), and ns3::Time::S.
Years() [1/2]
Time ns3::Years (double value) inline
Construct a Time in the indicated unit.
Parameters
[in] value The value
Returns
The Time
Definition at line 1257 of file nstime.h.
References ns3::Time::FromDouble(), and ns3::Time::Y.
Referenced by TimeSimpleTestCase::DoRun().
Years() [2/2]
Time ns3::Years (int64x64_t value) inline
Construct a Time in the indicated unit.
Parameters
[in] value The value
Returns
The Time
Definition at line 1261 of file nstime.h.
References ns3::Time::From(), and ns3::Time::Y.