ns-3: src/lte/examples/lena-radio-link-failure.cc File Reference
lena-radio-link-failure.cc File Reference
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/mobility-module.h"
#include "ns3/lte-module.h"
#include "ns3/applications-module.h"
#include "ns3/point-to-point-module.h"
#include <iostream>
#include <vector>
#include <stdio.h>
#include <iomanip>
Functions
void EnbRrcTimeout (uint64_t imsi, uint16_t rnti, uint16_t cellId, std::string cause)
void NotifyConnectionEstablishedEnb (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti)
void NotifyConnectionEstablishedUe (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
void NotifyConnectionReleaseAtEnodeB (uint64_t imsi, uint16_t cellId, uint16_t rnti)
void NotifyConnectionTimeoutUe (uint64_t imsi, uint16_t cellId, uint16_t rnti, uint8_t connEstFailCount)
void NotifyRandomAccessErrorUe (uint64_t imsi, uint16_t cellId, uint16_t rnti)
void NotifyRaResponseTimeoutUe (uint64_t imsi, bool contention, uint8_t preambleTxCounter, uint8_t maxPreambleTxLimit)
void PhySyncDetection (uint16_t n310, uint64_t imsi, uint16_t rnti, uint16_t cellId, std::string type, uint8_t count)
void PrintUePosition (uint64_t imsi)
void RadioLinkFailure (Time t310, uint64_t imsi, uint16_t cellId, uint16_t rnti)
void ReceivePacket (Ptr< const Packet > packet, const Address &)
void Throughput (bool firstWrite, Time binSize, std::string fileName)
static const std::string & ToString (LteUeRrc::State s)
void UeStateTransition (uint64_t imsi, uint16_t cellId, uint16_t rnti, LteUeRrc::State oldState, LteUeRrc::State newState)
Variables
uint32_t ByteCounter = 0
uint16_t counterN310FirsteNB = 0
static const std::string g_ueRrcStateName [LteUeRrc::NUM_STATES]
Map each of UE RRC states to its string representation.
uint32_t oldByteCounter = 0
Time t310StartTimeFirstEnb = Seconds (0)
Function Documentation
EnbRrcTimeout()
void EnbRrcTimeout (uint64_t imsi, uint16_t rnti, uint16_t cellId, std::string cause)
Definition at line 146 of file lena-radio-link-failure.cc.
References ns3::Time::As(), ns3::Simulator::Now(), and ns3::Time::S.
NotifyConnectionEstablishedEnb()
void NotifyConnectionEstablishedEnb (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti)
Definition at line 83 of file lena-radio-link-failure.cc.
References ns3::Time::As(), counterN310FirsteNB, ns3::Simulator::Now(), and ns3::Time::S.
NotifyConnectionEstablishedUe()
void NotifyConnectionEstablishedUe (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
Definition at line 69 of file lena-radio-link-failure.cc.
References ns3::Time::As(), ns3::Simulator::Now(), and ns3::Time::S.
NotifyConnectionReleaseAtEnodeB()
void NotifyConnectionReleaseAtEnodeB (uint64_t imsi, uint16_t cellId, uint16_t rnti)
Definition at line 155 of file lena-radio-link-failure.cc.
References ns3::Simulator::Now().
NotifyConnectionTimeoutUe()
void NotifyConnectionTimeoutUe (uint64_t imsi, uint16_t cellId, uint16_t rnti, uint8_t connEstFailCount)
Definition at line 205 of file lena-radio-link-failure.cc.
References ns3::Time::As(), ns3::Simulator::Now(), and ns3::Time::S.
NotifyRandomAccessErrorUe()
void NotifyRandomAccessErrorUe (uint64_t imsi, uint16_t cellId, uint16_t rnti)
Definition at line 197 of file lena-radio-link-failure.cc.
References ns3::Time::As(), ns3::Simulator::Now(), and ns3::Time::S.
NotifyRaResponseTimeoutUe()
void NotifyRaResponseTimeoutUe (uint64_t imsi, bool contention, uint8_t preambleTxCounter, uint8_t maxPreambleTxLimit)
Definition at line 216 of file lena-radio-link-failure.cc.
References ns3::Time::As(), ns3::Simulator::Now(), NS_FATAL_ERROR, and ns3::Time::S.
PhySyncDetection()
void PhySyncDetection (uint16_t n310, uint64_t imsi, uint16_t rnti, uint16_t cellId, std::string type, uint8_t count)
Definition at line 162 of file lena-radio-link-failure.cc.
References ns3::Time::As(), counterN310FirsteNB, ns3::Simulator::Now(), NS_LOG_DEBUG, ns3::Time::S, and t310StartTimeFirstEnb.
PrintUePosition()
void PrintUePosition (uint64_t imsi)
Definition at line 46 of file lena-radio-link-failure.cc.
References ns3::NodeList::Begin(), ns3::NodeList::End(), ns3::Node::GetDevice(), ns3::Node::GetNDevices(), ns3::Object::GetObject(), and GetPosition().
Referenced by RadioLinkFailure().
RadioLinkFailure()
void RadioLinkFailure (Time t310, uint64_t imsi, uint16_t cellId, uint16_t rnti)
Definition at line 181 of file lena-radio-link-failure.cc.
References ns3::Simulator::Now(), NS_ABORT_MSG_IF, PrintUePosition(), and t310StartTimeFirstEnb.
ReceivePacket()
void ReceivePacket (Ptr< const Packet > packet, const Address &)
Definition at line 229 of file lena-radio-link-failure.cc.
References ByteCounter.
Throughput()
void Throughput (bool firstWrite, Time binSize, std::string fileName)
Definition at line 235 of file lena-radio-link-failure.cc.
References ns3::Time::As(), ByteCounter, ns3::Time::GetSeconds(), ns3::Simulator::Now(), oldByteCounter, ns3::Time::S, and ns3::Simulator::Schedule().
ToString()
static const std::string& ToString (LteUeRrc::State s) static
Parameters
s The UE RRC state.
Returns
The string representation of the given state.
Definition at line 129 of file lena-radio-link-failure.cc.
References ns3::g_ueRrcStateName.
UeStateTransition()
void UeStateTransition (uint64_t imsi, uint16_t cellId, uint16_t rnti, LteUeRrc::State oldState, LteUeRrc::State newState)
Definition at line 135 of file lena-radio-link-failure.cc.
References ns3::Time::As(), ns3::Simulator::Now(), ns3::Time::S, and ns3::ToString().
Variable Documentation
ByteCounter
uint32_t ByteCounter = 0
Definition at line 41 of file lena-radio-link-failure.cc.
Referenced by ReceivePacket(), and Throughput().
counterN310FirsteNB
uint16_t counterN310FirsteNB = 0
Definition at line 39 of file lena-radio-link-failure.cc.
Referenced by NotifyConnectionEstablishedEnb(), and PhySyncDetection().
g_ueRrcStateName
const std::string g_ueRrcStateName[LteUeRrc::NUM_STATES] static
Initial value:
=
{
  "IDLE_START",
  "IDLE_CELL_SEARCH",
  "IDLE_WAIT_MIB_SIB1",
  "IDLE_WAIT_MIB",
  "IDLE_WAIT_SIB1",
  "IDLE_CAMPED_NORMALLY",
  "IDLE_WAIT_SIB2",
  "IDLE_RANDOM_ACCESS",
  "IDLE_CONNECTING",
  "CONNECTED_NORMALLY",
  "CONNECTED_HANDOVER",
  "CONNECTED_PHY_PROBLEM",
  "CONNECTED_REESTABLISHING"
}
Map each of UE RRC states to its string representation.
Definition at line 108 of file lena-radio-link-failure.cc.
oldByteCounter
uint32_t oldByteCounter = 0
Definition at line 42 of file lena-radio-link-failure.cc.
Referenced by Throughput().
t310StartTimeFirstEnb
Time t310StartTimeFirstEnb = Seconds (0)
Definition at line 40 of file lena-radio-link-failure.cc.
Referenced by PhySyncDetection(), and RadioLinkFailure().