ns-3: src/lte/examples/lena-cqi-threshold.cc File Reference
lena-cqi-threshold.cc File Reference
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/mobility-module.h"
#include "ns3/lte-module.h"
#include "ns3/config-store.h"
#include <ns3/buildings-helper.h>
Functions
static void ChangePosition (Ptr< Node > node)
static Vector GetPosition (Ptr< Node > node)
static void SetPosition (Ptr< Node > node, Vector position)
Function Documentation
ChangePosition()
static void ChangePosition (Ptr< Node > node) static
Definition at line 48 of file lena-cqi-threshold.cc.
References GetPosition(), and SetPosition().
GetPosition()
static Vector GetPosition (Ptr< Node > node) static
Definition at line 41 of file lena-cqi-threshold.cc.
References ns3::Object::GetObject(), and third::mobility.
Referenced by ChangePosition().
SetPosition()
static void SetPosition (Ptr< Node > node, Vector position) static
Definition at line 34 of file lena-cqi-threshold.cc.
References ns3::Object::GetObject(), and third::mobility.
Referenced by ChangePosition().