ns-3: src/lr-wpan/examples/lr-wpan-data.cc File Reference
lr-wpan-data.cc File Reference
#include <ns3/log.h>
#include <ns3/core-module.h>
#include <ns3/lr-wpan-module.h>
#include <ns3/propagation-loss-model.h>
#include <ns3/propagation-delay-model.h>
#include <ns3/simulator.h>
#include <ns3/single-model-spectrum-channel.h>
#include <ns3/constant-position-mobility-model.h>
#include <ns3/packet.h>
#include <iostream>
Functions
static void DataConfirm (McpsDataConfirmParams params)
static void DataIndication (McpsDataIndicationParams params, Ptr< Packet > p)
static void StateChangeNotification (std::string context, Time now, LrWpanPhyEnumeration oldState, LrWpanPhyEnumeration newState)
Function Documentation
DataConfirm()
static void DataConfirm (McpsDataConfirmParams params) static
Definition at line 47 of file lr-wpan-data.cc.
References ns3::McpsDataConfirmParams::m_status, and NS_LOG_UNCOND.
DataIndication()
static void DataIndication (McpsDataIndicationParams params, Ptr< Packet > p) static
Definition at line 42 of file lr-wpan-data.cc.
References ns3::Packet::GetSize(), and NS_LOG_UNCOND.
StateChangeNotification()
static void StateChangeNotification (std::string context, Time now, LrWpanPhyEnumeration oldState, LrWpanPhyEnumeration newState) static
Definition at line 52 of file lr-wpan-data.cc.
References ns3::Time::As(), ns3::LrWpanHelper::LrWpanPhyEnumerationPrinter(), NS_LOG_UNCOND, and ns3::Time::S.