ns-3: src/lr-wpan/examples/lr-wpan-mlme.cc File Reference
lr-wpan-mlme.cc File Reference
#include <ns3/log.h>
#include <ns3/core-module.h>
#include <ns3/lr-wpan-module.h>
#include <ns3/propagation-loss-model.h>
#include <ns3/propagation-delay-model.h>
#include <ns3/simulator.h>
#include <ns3/single-model-spectrum-channel.h>
#include <ns3/constant-position-mobility-model.h>
#include <ns3/packet.h>
#include <iostream>
Functions
static void BeaconIndication (MlmeBeaconNotifyIndicationParams params, Ptr< Packet > p)
static void DataIndication (McpsDataIndicationParams params, Ptr< Packet > p)
static void DataIndicationCoordinator (McpsDataIndicationParams params, Ptr< Packet > p)
static void StartConfirm (MlmeStartConfirmParams params)
static void TransEndIndication (McpsDataConfirmParams params)
Function Documentation
BeaconIndication()
static void BeaconIndication (MlmeBeaconNotifyIndicationParams params, Ptr< Packet > p) static
Definition at line 50 of file lr-wpan-mlme.cc.
References ns3::Packet::GetSize(), ns3::Simulator::Now(), and NS_LOG_UNCOND.
DataIndication()
static void DataIndication (McpsDataIndicationParams params, Ptr< Packet > p) static
Definition at line 55 of file lr-wpan-mlme.cc.
References ns3::Packet::GetSize(), ns3::Simulator::Now(), and NS_LOG_UNCOND.
DataIndicationCoordinator()
static void DataIndicationCoordinator (McpsDataIndicationParams params, Ptr< Packet > p) static
Definition at line 70 of file lr-wpan-mlme.cc.
References ns3::Packet::GetSize(), ns3::Simulator::Now(), and NS_LOG_UNCOND.
StartConfirm()
static void StartConfirm (MlmeStartConfirmParams params) static
Definition at line 75 of file lr-wpan-mlme.cc.
References ns3::MlmeStartConfirmParams::m_status, ns3::MLMESTART_SUCCESS, ns3::Simulator::Now(), and NS_LOG_UNCOND.
TransEndIndication()
static void TransEndIndication (McpsDataConfirmParams params) static
Definition at line 60 of file lr-wpan-mlme.cc.
References ns3::IEEE_802_15_4_SUCCESS, ns3::McpsDataConfirmParams::m_status, ns3::Simulator::Now(), and NS_LOG_UNCOND.