ns-3: src/lte/test/lte-test-cqi-generation.cc File Reference
lte-test-cqi-generation.cc File Reference
#include <ns3/simulator.h>
#include <ns3/log.h>
#include <ns3/callback.h>
#include <ns3/config.h>
#include <ns3/string.h>
#include <ns3/double.h>
#include <ns3/enum.h>
#include <ns3/boolean.h>
#include <ns3/pointer.h>
#include "ns3/ff-mac-scheduler.h"
#include "ns3/mobility-helper.h"
#include "ns3/lte-helper.h"
#include "lte-ffr-simple.h"
#include "ns3/lte-rrc-sap.h"
#include <ns3/lte-ue-net-device.h>
#include <ns3/lte-ue-mac.h>
#include "lte-test-cqi-generation.h"
Functions
void LteTestDlSchedulingCallback (LteCqiGenerationTestCase *testcase, std::string path, DlSchedulingCallbackInfo dlInfo)
void LteTestDlSchedulingCallback2 (LteCqiGenerationDlPowerControlTestCase *testcase, std::string path, DlSchedulingCallbackInfo dlInfo)
void LteTestUlSchedulingCallback (LteCqiGenerationTestCase *testcase, std::string path, uint32_t frameNo, uint32_t subframeNo, uint16_t rnti, uint8_t mcs, uint16_t sizeTb, uint8_t ccId)
void LteTestUlSchedulingCallback2 (LteCqiGenerationDlPowerControlTestCase *testcase, std::string path, uint32_t frameNo, uint32_t subframeNo, uint16_t rnti, uint8_t mcs, uint16_t sizeTb, uint8_t componentCarrierId)
Variables
static LteCqiGenerationTestSuite lteCqiGenerationTestSuite
Function Documentation
LteTestDlSchedulingCallback()
void LteTestDlSchedulingCallback (LteCqiGenerationTestCase * testcase, std::string path, DlSchedulingCallbackInfo dlInfo)
Definition at line 47 of file lte-test-cqi-generation.cc.
References LteCqiGenerationTestCase::DlScheduling().
Referenced by LteCqiGenerationTestCase::DoRun().
LteTestDlSchedulingCallback2()
void LteTestDlSchedulingCallback2 (LteCqiGenerationDlPowerControlTestCase * testcase, std::string path, DlSchedulingCallbackInfo dlInfo)
Definition at line 61 of file lte-test-cqi-generation.cc.
References LteCqiGenerationDlPowerControlTestCase::DlScheduling().
Referenced by LteCqiGenerationDlPowerControlTestCase::DoRun().
LteTestUlSchedulingCallback()
void LteTestUlSchedulingCallback (LteCqiGenerationTestCase * testcase, std::string path, uint32_t frameNo, uint32_t subframeNo, uint16_t rnti, uint8_t mcs, uint16_t sizeTb, uint8_t ccId)
Definition at line 53 of file lte-test-cqi-generation.cc.
References LteCqiGenerationTestCase::UlScheduling().
Referenced by LteCqiGenerationTestCase::DoRun().
LteTestUlSchedulingCallback2()
void LteTestUlSchedulingCallback2 (LteCqiGenerationDlPowerControlTestCase * testcase, std::string path, uint32_t frameNo, uint32_t subframeNo, uint16_t rnti, uint8_t mcs, uint16_t sizeTb, uint8_t componentCarrierId)
Definition at line 68 of file lte-test-cqi-generation.cc.
References LteCqiGenerationDlPowerControlTestCase::UlScheduling().
Referenced by LteCqiGenerationDlPowerControlTestCase::DoRun().
Variable Documentation
lteCqiGenerationTestSuite
LteCqiGenerationTestSuite lteCqiGenerationTestSuite static
Definition at line 106 of file lte-test-cqi-generation.cc.