ns-3: src/lte/test/lte-test-interference.cc File Reference
lte-test-interference.cc File Reference
#include "ns3/simulator.h"
#include "ns3/log.h"
#include "ns3/string.h"
#include "ns3/double.h"
#include <ns3/enum.h>
#include "ns3/boolean.h"
#include "ns3/mobility-helper.h"
#include "ns3/lte-helper.h"
#include "ns3/ff-mac-scheduler.h"
#include "ns3/lte-enb-phy.h"
#include "ns3/lte-enb-net-device.h"
#include "ns3/lte-ue-phy.h"
#include "ns3/lte-ue-net-device.h"
#include <ns3/lte-chunk-processor.h>
#include "lte-test-interference.h"
Functions
void LteTestDlSchedulingCallback (LteInterferenceTestCase *testcase, std::string path, DlSchedulingCallbackInfo dlInfo)
void LteTestUlSchedulingCallback (LteInterferenceTestCase *testcase, std::string path, uint32_t frameNo, uint32_t subframeNo, uint16_t rnti, uint8_t mcs, uint16_t sizeTb, uint8_t ccId)
Variables
static LteInterferenceTestSuite lteLinkAdaptationWithInterferenceTestSuite
Function Documentation
LteTestDlSchedulingCallback()
void LteTestDlSchedulingCallback (LteInterferenceTestCase * testcase, std::string path, DlSchedulingCallbackInfo dlInfo)
Definition at line 48 of file lte-test-interference.cc.
References LteInterferenceTestCase::DlScheduling().
Referenced by LteInterferenceTestCase::DoRun().
LteTestUlSchedulingCallback()
void LteTestUlSchedulingCallback (LteInterferenceTestCase * testcase, std::string path, uint32_t frameNo, uint32_t subframeNo, uint16_t rnti, uint8_t mcs, uint16_t sizeTb, uint8_t ccId)
Definition at line 55 of file lte-test-interference.cc.
References LteInterferenceTestCase::UlScheduling().
Referenced by LteInterferenceTestCase::DoRun().
Variable Documentation
lteLinkAdaptationWithInterferenceTestSuite
LteInterferenceTestSuite lteLinkAdaptationWithInterferenceTestSuite static
Definition at line 90 of file lte-test-interference.cc.