ns-3: src/lte/test/lte-test-frequency-reuse.cc File Reference
lte-test-frequency-reuse.cc File Reference
#include <ns3/simulator.h>
#include <ns3/log.h>
#include <ns3/callback.h>
#include <ns3/config.h>
#include <ns3/string.h>
#include <ns3/double.h>
#include <ns3/enum.h>
#include <ns3/boolean.h>
#include <ns3/pointer.h>
#include "ns3/mobility-helper.h"
#include "ns3/lte-helper.h"
#include "ns3/point-to-point-epc-helper.h"
#include "ns3/internet-module.h"
#include "ns3/point-to-point-module.h"
#include "ns3/applications-module.h"
#include <ns3/ff-mac-scheduler.h>
#include <ns3/lte-enb-net-device.h>
#include <ns3/lte-enb-phy.h>
#include <ns3/lte-enb-rrc.h>
#include <ns3/lte-ue-net-device.h>
#include <ns3/lte-ue-phy.h>
#include <ns3/lte-ue-rrc.h>
#include "lte-ffr-simple.h"
#include "lte-simple-spectrum-phy.h"
#include <ns3/lte-common.h>
#include "lte-test-frequency-reuse.h"
Functions
void DlDataRxStartNofitication (LteFrTestCase *testcase, Ptr< const SpectrumValue > spectrumValue)
TestCase Data.
void DlDataRxStartNofiticationArea (LteFrAreaTestCase *testcase, Ptr< const SpectrumValue > spectrumValue)
void UlDataRxStartNofitication (LteFrTestCase *testcase, Ptr< const SpectrumValue > spectrumValue)
void UlDataRxStartNofiticationArea (LteFrAreaTestCase *testcase, Ptr< const SpectrumValue > spectrumValue)
Variables
static LteFrequencyReuseTestSuite lteFrequencyReuseTestSuite
Function Documentation
DlDataRxStartNofitication()
void DlDataRxStartNofitication (LteFrTestCase * testcase, Ptr< const SpectrumValue > spectrumValue)
TestCase Data.
Definition at line 164 of file lte-test-frequency-reuse.cc.
References LteFrTestCase::DlDataRxStart().
Referenced by LteHardFrTestCase::DoRun(), and LteStrictFrTestCase::DoRun().
DlDataRxStartNofiticationArea()
void DlDataRxStartNofiticationArea (LteFrAreaTestCase * testcase, Ptr< const SpectrumValue > spectrumValue)
Definition at line 470 of file lte-test-frequency-reuse.cc.
References LteFrAreaTestCase::DlDataRxStart().
Referenced by LteStrictFrAreaTestCase::DoRun(), LteSoftFrAreaTestCase::DoRun(), LteSoftFfrAreaTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), and LteDistributedFfrAreaTestCase::DoRun().
UlDataRxStartNofitication()
void UlDataRxStartNofitication (LteFrTestCase * testcase, Ptr< const SpectrumValue > spectrumValue)
Definition at line 171 of file lte-test-frequency-reuse.cc.
References LteFrTestCase::UlDataRxStart().
Referenced by LteHardFrTestCase::DoRun(), and LteStrictFrTestCase::DoRun().
UlDataRxStartNofiticationArea()
void UlDataRxStartNofiticationArea (LteFrAreaTestCase * testcase, Ptr< const SpectrumValue > spectrumValue)
Definition at line 477 of file lte-test-frequency-reuse.cc.
References LteFrAreaTestCase::UlDataRxStart().
Referenced by LteStrictFrAreaTestCase::DoRun(), LteSoftFrAreaTestCase::DoRun(), LteSoftFfrAreaTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), and LteDistributedFfrAreaTestCase::DoRun().
Variable Documentation
lteFrequencyReuseTestSuite
LteFrequencyReuseTestSuite lteFrequencyReuseTestSuite static
Definition at line 157 of file lte-test-frequency-reuse.cc.