ns-3: src/lte/test/lte-test-uplink-power-control.cc File Reference
lte-test-uplink-power-control.cc File Reference
#include <ns3/simulator.h>
#include <ns3/log.h>
#include <ns3/callback.h>
#include <ns3/config.h>
#include <ns3/string.h>
#include <ns3/double.h>
#include <ns3/enum.h>
#include <ns3/boolean.h>
#include <ns3/pointer.h>
#include <ns3/integer.h>
#include "ns3/mobility-helper.h"
#include "ns3/lte-helper.h"
#include <ns3/ff-mac-scheduler.h>
#include <ns3/lte-enb-net-device.h>
#include <ns3/lte-enb-phy.h>
#include <ns3/lte-enb-rrc.h>
#include <ns3/lte-ue-net-device.h>
#include <ns3/lte-ue-phy.h>
#include <ns3/lte-ue-rrc.h>
#include "lte-ffr-simple.h"
#include <ns3/lte-common.h>
#include "lte-test-uplink-power-control.h"
#include <ns3/lte-rrc-sap.h>
Functions
void PucchTxPowerNofitication (LteUplinkPowerControlTestCase *testcase, uint16_t cellId, uint16_t rnti, double txPower)
void PuschTxPowerNofitication (LteUplinkPowerControlTestCase *testcase, uint16_t cellId, uint16_t rnti, double txPower)
TestCase Data.
void SrsTxPowerNofitication (LteUplinkPowerControlTestCase *testcase, uint16_t cellId, uint16_t rnti, double txPower)
Variables
static LteUplinkPowerControlTestSuite lteUplinkPowerControlTestSuite
Function Documentation
PucchTxPowerNofitication()
void PucchTxPowerNofitication (LteUplinkPowerControlTestCase * testcase, uint16_t cellId, uint16_t rnti, double txPower)
Definition at line 83 of file lte-test-uplink-power-control.cc.
References LteUplinkPowerControlTestCase::PucchTxPowerTrace().
Referenced by LteUplinkOpenLoopPowerControlTestCase::DoRun(), LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), and LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun().
PuschTxPowerNofitication()
void PuschTxPowerNofitication (LteUplinkPowerControlTestCase * testcase, uint16_t cellId, uint16_t rnti, double txPower)
TestCase Data.
Definition at line 76 of file lte-test-uplink-power-control.cc.
References LteUplinkPowerControlTestCase::PuschTxPowerTrace().
Referenced by LteUplinkOpenLoopPowerControlTestCase::DoRun(), LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), and LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun().
SrsTxPowerNofitication()
void SrsTxPowerNofitication (LteUplinkPowerControlTestCase * testcase, uint16_t cellId, uint16_t rnti, double txPower)
Definition at line 90 of file lte-test-uplink-power-control.cc.
References LteUplinkPowerControlTestCase::SrsTxPowerTrace().
Referenced by LteUplinkOpenLoopPowerControlTestCase::DoRun(), LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), and LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun().
Variable Documentation
lteUplinkPowerControlTestSuite
LteUplinkPowerControlTestSuite lteUplinkPowerControlTestSuite static
Definition at line 70 of file lte-test-uplink-power-control.cc.