ns-3: src/internet/examples/main-simple.cc File Reference
main-simple.cc File Reference
#include <iostream>
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
Functions
static void GenerateTraffic (Ptr< Socket > socket, uint32_t size)
static void PrintTraffic (Ptr< Socket > socket)
void RunSimulation (void)
static void SocketPrinter (Ptr< Socket > socket)
Function Documentation
GenerateTraffic()
static void GenerateTraffic (Ptr< Socket > socket, uint32_t size) static
Definition at line 30 of file main-simple.cc.
References ns3::Socket::Close(), ns3::Time::GetSeconds(), ns3::Simulator::Now(), ns3::Simulator::Schedule(), ns3::Seconds(), and ns3::Socket::Send().
Referenced by RunSimulation().
PrintTraffic()
static void PrintTraffic (Ptr< Socket > socket) static
Definition at line 55 of file main-simple.cc.
References ns3::MakeCallback(), ns3::Socket::SetRecvCallback(), and SocketPrinter().
Referenced by RunSimulation().
RunSimulation()
void RunSimulation (void)
Definition at line 61 of file main-simple.cc.
References ns3::Socket::Connect(), ns3::NodeContainer::Create(), ns3::Socket::CreateSocket(), ns3::Simulator::Destroy(), GenerateTraffic(), ns3::NodeContainer::Get(), ns3::Ipv4Address::GetAny(), ns3::Ipv4Address::GetLoopback(), ns3::InternetStackHelper::Install(), ns3::TypeId::LookupByName(), PrintTraffic(), ns3::Simulator::Run(), and sink.
SocketPrinter()
static void SocketPrinter (Ptr< Socket > socket) static
Definition at line 45 of file main-simple.cc.
References ns3::Time::GetSeconds(), ns3::Packet::GetSize(), ns3::Simulator::Now(), and ns3::Socket::Recv().
Referenced by PrintTraffic().