ns-3: anonymous_namespace{length.cc} Namespace Reference
anonymous_namespace{length.cc} Namespace Reference
Unnamed namespace.
Classes
class EnumHash
Functor for hashing Length::Unit values.
Functions
double Convert (const ns3::Length::Quantity &from, ns3::Length::Unit toUnit)
Convert a Length::Quantity to the equivalent value in another unit.
double Convert (double value, ns3::Length::Unit fromUnit, ns3::Length::Unit toUnit)
Convert a value in one unit to the equivalent value in another unit.
double FootToMeter (double value)
Convert a value in feet to the equivalent value in meters.
double MeterToFoot (double value)
Convert a value in meters to the equivalent value in feet.
template<class R >
double MeterToUS (double value)
Convert a value from meters to a US Customary unit (inches, feet, yards etc.)
template<class R >
double ScaleValue (double value)
Helper function to scale an input value by a given ratio.
template<class R >
double USToMeter (double value)
Convert a value from a US Customary unit (inches, feet, yards etc.) to meters.
Detailed Description
Unnamed namespace.
Function Documentation
Convert() [1/2]
double anonymous_namespace{length.cc}::Convert (const ns3::Length::Quantity & from, ns3::Length::Unit toUnit)
Convert a Length::Quantity to the equivalent value in another unit.
Parameters
from Quantity with the current value and unit
toUnit Target unit
Returns
Result of converting the quantity value to the requested units
Definition at line 202 of file length.cc.
References ns3::Length::Quantity::Unit(), and ns3::Length::Quantity::Value().
Referenced by ns3::Length::Length(), ns3::Length::As(), and ns3::Length::operator=().
Convert() [2/2]
double anonymous_namespace{length.cc}::Convert (double value, ns3::Length::Unit fromUnit, ns3::Length::Unit toUnit)
Convert a value in one unit to the equivalent value in another unit.
Parameters
value Length value in fromUnit units
fromUnit Unit of value
toUnit Target unit
Returns
Result of converting value from fromUnit to toUnit
Helper to generate hash values from pairs of Length::Units
Definition at line 133 of file length.cc.
References FootToMeter(), MeterToFoot(), and NS_FATAL_ERROR.
FootToMeter()
double anonymous_namespace{length.cc}::FootToMeter (double value)
Convert a value in feet to the equivalent value in meters.
Parameters
value Input value in feet
Returns
Equivalent value in meters
Definition at line 73 of file length.cc.
Referenced by Convert(), and USToMeter().
MeterToFoot()
double anonymous_namespace{length.cc}::MeterToFoot (double value)
Convert a value in meters to the equivalent value in feet.
Parameters
value Input value in meters
Returns
Equivalent value in feet
Definition at line 85 of file length.cc.
Referenced by Convert(), and MeterToUS().
MeterToUS()
template<class R > double anonymous_namespace{length.cc}::MeterToUS (double value)
Convert a value from meters to a US Customary unit (inches, feet, yards etc.)
Value is converted to feet then scaled to the desired US Customary unit
Template Parameters
R std::ratio needed to convert feet to desired US customary unit
Parameters
value Input value in meters
Returns
Equivalent value in a US customary unit
Definition at line 119 of file length.cc.
References MeterToFoot().
ScaleValue()
template<class R > double anonymous_namespace{length.cc}::ScaleValue (double value)
Helper function to scale an input value by a given ratio.
Template Parameters
R a std::ratio
Parameters
value Input value to scale by R
Returns
The result of value * R::num / R::den
Definition at line 61 of file length.cc.
USToMeter()
template<class R > double anonymous_namespace{length.cc}::USToMeter (double value)
Convert a value from a US Customary unit (inches, feet, yards etc.) to meters.
Value is scaled to feet then converted to meters
Template Parameters
R std::ratio needed to convert value to feet
Parameters
value Input value in some US Customary unit
Returns
Equivalent value in meters
Definition at line 102 of file length.cc.
References FootToMeter().