ns-3: ns3::olsr Namespace Reference
ns3::olsr Namespace Reference
Namespaces
anonymous_namespace{olsr-routing-protocol.cc}
Classes
struct Association
Association.
struct AssociationTuple
An Association Tuple.
class Bug780Test
See Bug 780
struct DuplicateTuple
A Duplicate Tuple.
class HelloRegressionTest
Trivial (still useful) test of OLSR operation.
struct IfaceAssocTuple
An Interface Association Tuple.
struct LinkTuple
A Link Tuple.
class MessageHeader
This header can store HELP, TC, MID and HNA messages.
struct MprSelectorTuple
An MPR-Selector Tuple.
struct NeighborTuple
A Neighbor Tuple.
class OlsrState
This class encapsulates all data structures needed for maintaining internal state of an OLSR node.
class PacketHeader
The basic layout of any packet in OLSR is as follows (omitting IP and UDP headers):
class RoutingProtocol
OLSR routing protocol for IPv4.
struct RoutingTableEntry
An OLSR's routing table entry.
class TcRegressionTest
Less trivial test of OLSR Topology Control message generation.
struct TopologyTuple
A Topology Tuple.
struct TwoHopNeighborTuple
A 2-hop Tuple.
Typedefs
typedef std::vector< Association > Associations
Association Set type.
typedef std::vector< AssociationTuple > AssociationSet
Association Set type.
typedef std::vector< DuplicateTuple > DuplicateSet
Duplicate Set type.
typedef std::vector< IfaceAssocTuple > IfaceAssocSet
Interface Association Set type.
typedef std::vector< LinkTuple > LinkSet
Link Set type.
typedef std::vector< MessageHeader > MessageList
typedef std::vector< MprSelectorTuple > MprSelectorSet
MPR Selector Set type.
typedef std::set< Ipv4Address > MprSet
MPR Set type.
typedef std::vector< NeighborTuple > NeighborSet
Neighbor Set type.
typedef std::vector< TopologyTuple > TopologySet
Topology Set type.
typedef std::vector< TwoHopNeighborTuple > TwoHopNeighborSet
2-hop Neighbor Set type.
Functions
double EmfToSeconds (uint8_t olsrFormat)
Converts a number of seconds in the mantissa/exponent format to a decimal number.
static std::ostream & operator<< (std::ostream &os, const Association &tuple)
static std::ostream & operator<< (std::ostream &os, const AssociationTuple &tuple)
static std::ostream & operator<< (std::ostream &os, const IfaceAssocTuple &tuple)
static std::ostream & operator<< (std::ostream &os, const LinkTuple &tuple)
static std::ostream & operator<< (std::ostream &os, const MessageHeader &message)
static std::ostream & operator<< (std::ostream &os, const MessageList &messages)
static std::ostream & operator<< (std::ostream &os, const NeighborTuple &tuple)
static std::ostream & operator<< (std::ostream &os, const PacketHeader &packet)
static std::ostream & operator<< (std::ostream &os, const TopologyTuple &tuple)
static std::ostream & operator<< (std::ostream &os, const TwoHopNeighborTuple &tuple)
static bool operator== (const Association &a, const Association &b)
static bool operator== (const AssociationTuple &a, const AssociationTuple &b)
static bool operator== (const DuplicateTuple &a, const DuplicateTuple &b)
static bool operator== (const IfaceAssocTuple &a, const IfaceAssocTuple &b)
static bool operator== (const LinkTuple &a, const LinkTuple &b)
static bool operator== (const MprSelectorTuple &a, const MprSelectorTuple &b)
static bool operator== (const NeighborTuple &a, const NeighborTuple &b)
static bool operator== (const TopologyTuple &a, const TopologyTuple &b)
static bool operator== (const TwoHopNeighborTuple &a, const TwoHopNeighborTuple &b)
uint8_t SecondsToEmf (double seconds)
Converts a decimal number of seconds to the mantissa/exponent format.
Typedef Documentation
Associations
typedef std::vector<Association> ns3::olsr::Associations
Association Set type.
Definition at line 305 of file olsr-repositories.h.
AssociationSet
typedef std::vector<AssociationTuple> ns3::olsr::AssociationSet
Association Set type.
Definition at line 304 of file olsr-repositories.h.
DuplicateSet
typedef std::vector<DuplicateTuple> ns3::olsr::DuplicateSet
Duplicate Set type.
Definition at line 302 of file olsr-repositories.h.
IfaceAssocSet
typedef std::vector<IfaceAssocTuple> ns3::olsr::IfaceAssocSet
Interface Association Set type.
Definition at line 303 of file olsr-repositories.h.
LinkSet
typedef std::vector<LinkTuple> ns3::olsr::LinkSet
Link Set type.
Definition at line 298 of file olsr-repositories.h.
MessageList
typedef std::vector<MessageHeader> ns3::olsr::MessageList
Definition at line 695 of file olsr-header.h.
MprSelectorSet
typedef std::vector<MprSelectorTuple> ns3::olsr::MprSelectorSet
MPR Selector Set type.
Definition at line 297 of file olsr-repositories.h.
MprSet
typedef std::set<Ipv4Address> ns3::olsr::MprSet
MPR Set type.
Definition at line 296 of file olsr-repositories.h.
NeighborSet
typedef std::vector<NeighborTuple> ns3::olsr::NeighborSet
Neighbor Set type.
Definition at line 299 of file olsr-repositories.h.
TopologySet
typedef std::vector<TopologyTuple> ns3::olsr::TopologySet
Topology Set type.
Definition at line 301 of file olsr-repositories.h.
TwoHopNeighborSet
typedef std::vector<TwoHopNeighborTuple> ns3::olsr::TwoHopNeighborSet
2-hop Neighbor Set type.
Definition at line 300 of file olsr-repositories.h.
Function Documentation
EmfToSeconds()
double ns3::olsr::EmfToSeconds (uint8_t olsrFormat)
Converts a number of seconds in the mantissa/exponent format to a decimal number.
Parameters
olsr_format number of seconds in mantissa/exponent format.
Returns
the decimal number of seconds.
Definition at line 91 of file olsr-header.cc.
References OLSR_C.
Referenced by OlsrEmfTestCase::DoRun(), ns3::olsr::MessageHeader::Hello::GetHTime(), and ns3::olsr::MessageHeader::GetVTime().
operator<<() [1/10]
static std::ostream& ns3::olsr::operator<< (std::ostream & os, const Association & tuple) inline static
Definition at line 253 of file olsr-repositories.h.
References ns3::olsr::Association::netmask, and ns3::olsr::Association::networkAddr.
operator<<() [2/10]
static std::ostream& ns3::olsr::operator<< (std::ostream & os, const AssociationTuple & tuple) inline static
Definition at line 284 of file olsr-repositories.h.
References ns3::olsr::AssociationTuple::expirationTime, ns3::olsr::AssociationTuple::gatewayAddr, ns3::olsr::AssociationTuple::netmask, and ns3::olsr::AssociationTuple::networkAddr.
operator<<() [3/10]
static std::ostream& ns3::olsr::operator<< (std::ostream & os, const IfaceAssocTuple & tuple) inline static
Definition at line 56 of file olsr-repositories.h.
References ns3::olsr::IfaceAssocTuple::ifaceAddr, ns3::olsr::IfaceAssocTuple::mainAddr, and ns3::olsr::IfaceAssocTuple::time.
operator<<() [4/10]
static std::ostream& ns3::olsr::operator<< (std::ostream & os, const LinkTuple & tuple) inline static
Definition at line 88 of file olsr-repositories.h.
References ns3::olsr::LinkTuple::asymTime, ns3::olsr::LinkTuple::localIfaceAddr, ns3::olsr::LinkTuple::neighborIfaceAddr, ns3::olsr::LinkTuple::symTime, and ns3::olsr::LinkTuple::time.
operator<<() [5/10]
static std::ostream& ns3::olsr::operator<< (std::ostream & os, const MessageHeader & message) inline static
Definition at line 689 of file olsr-header.h.
References ns3::olsr::MessageHeader::Print().
operator<<() [6/10]
static std::ostream& ns3::olsr::operator<< (std::ostream & os, const MessageList & messages) inline static
Definition at line 697 of file olsr-header.h.
operator<<() [7/10]
static std::ostream& ns3::olsr::operator<< (std::ostream & os, const NeighborTuple & tuple) inline static
Definition at line 124 of file olsr-repositories.h.
References ns3::olsr::NeighborTuple::neighborMainAddr, ns3::olsr::NeighborTuple::status, ns3::olsr::NeighborTuple::STATUS_SYM, and ns3::olsr::NeighborTuple::willingness.
operator<<() [8/10]
static std::ostream& ns3::olsr::operator<< (std::ostream & os, const PacketHeader & packet) inline static
Definition at line 683 of file olsr-header.h.
References ns3::olsr::PacketHeader::Print().
operator<<() [9/10]
static std::ostream& ns3::olsr::operator<< (std::ostream & os, const TopologyTuple & tuple) inline static
Definition at line 227 of file olsr-repositories.h.
References ns3::olsr::TopologyTuple::destAddr, ns3::olsr::TopologyTuple::expirationTime, ns3::olsr::TopologyTuple::lastAddr, and ns3::olsr::TopologyTuple::sequenceNumber.
operator<<() [10/10]
static std::ostream& ns3::olsr::operator<< (std::ostream & os, const TwoHopNeighborTuple & tuple) inline static
Definition at line 145 of file olsr-repositories.h.
References ns3::olsr::TwoHopNeighborTuple::expirationTime, ns3::olsr::TwoHopNeighborTuple::neighborMainAddr, and ns3::olsr::TwoHopNeighborTuple::twoHopNeighborAddr.
operator==() [1/9]
static bool ns3::olsr::operator== (const Association & a, const Association & b) inline static
Definition at line 247 of file olsr-repositories.h.
References ns3::olsr::Association::netmask, and ns3::olsr::Association::networkAddr.
operator==() [2/9]
static bool ns3::olsr::operator== (const AssociationTuple & a, const AssociationTuple & b) inline static
Definition at line 277 of file olsr-repositories.h.
References ns3::olsr::AssociationTuple::gatewayAddr, ns3::olsr::AssociationTuple::netmask, and ns3::olsr::AssociationTuple::networkAddr.
operator==() [3/9]
static bool ns3::olsr::operator== (const DuplicateTuple & a, const DuplicateTuple & b) inline static
Definition at line 199 of file olsr-repositories.h.
References ns3::olsr::DuplicateTuple::address, and ns3::olsr::DuplicateTuple::sequenceNumber.
operator==() [4/9]
static bool ns3::olsr::operator== (const IfaceAssocTuple & a, const IfaceAssocTuple & b) inline static
Definition at line 50 of file olsr-repositories.h.
References ns3::olsr::IfaceAssocTuple::ifaceAddr, and ns3::olsr::IfaceAssocTuple::mainAddr.
operator==() [5/9]
static bool ns3::olsr::operator== (const LinkTuple & a, const LinkTuple & b) inline static
Definition at line 82 of file olsr-repositories.h.
References ns3::olsr::LinkTuple::localIfaceAddr, and ns3::olsr::LinkTuple::neighborIfaceAddr.
operator==() [6/9]
static bool ns3::olsr::operator== (const MprSelectorTuple & a, const MprSelectorTuple & b) inline static
Definition at line 173 of file olsr-repositories.h.
References ns3::olsr::MprSelectorTuple::mainAddr.
operator==() [7/9]
static bool ns3::olsr::operator== (const NeighborTuple & a, const NeighborTuple & b) inline static
Definition at line 117 of file olsr-repositories.h.
References ns3::olsr::NeighborTuple::neighborMainAddr, ns3::olsr::NeighborTuple::status, and ns3::olsr::NeighborTuple::willingness.
operator==() [8/9]
static bool ns3::olsr::operator== (const TopologyTuple & a, const TopologyTuple & b) inline static
Definition at line 220 of file olsr-repositories.h.
References ns3::olsr::TopologyTuple::destAddr, ns3::olsr::TopologyTuple::lastAddr, and ns3::olsr::TopologyTuple::sequenceNumber.
operator==() [9/9]
static bool ns3::olsr::operator== (const TwoHopNeighborTuple & a, const TwoHopNeighborTuple & b) inline static
Definition at line 156 of file olsr-repositories.h.
References ns3::olsr::TwoHopNeighborTuple::neighborMainAddr, and ns3::olsr::TwoHopNeighborTuple::twoHopNeighborAddr.
SecondsToEmf()
uint8_t ns3::olsr::SecondsToEmf (double seconds)
Converts a decimal number of seconds to the mantissa/exponent format.
Parameters
seconds decimal number of seconds we want to convert.
Returns
the number of seconds in mantissa/exponent format.
Definition at line 49 of file olsr-header.cc.
References NS_ASSERT, NS_ASSERT_MSG, and OLSR_C.
Referenced by OlsrEmfTestCase::DoRun(), ns3::olsr::MessageHeader::Hello::SetHTime(), and ns3::olsr::MessageHeader::SetVTime().