ns-3: anonymous_namespace{sample-log-time-format.cc} Namespace Reference
anonymous_namespace{sample-log-time-format.cc} Namespace Reference
Functions
void ReplacementTimePrinter (std::ostream &os)
Pre-ns-3.26 TimePrinter equivalent (was called LogTimePrinter).
void ReplaceTimePrinter (void)
Set ReplacementTimePrinter as the time printer for log messages.
Function Documentation
ReplacementTimePrinter()
void anonymous_namespace{sample-log-time-format.cc}::ReplacementTimePrinter (std::ostream & os)
Pre-ns-3.26 TimePrinter equivalent (was called LogTimePrinter).
Prior to ns-3.26, the time printer used default C++ iostream precision This function sets it back to the format used before ns-3.26
Parameters
[in] os The stream to print on.
Definition at line 106 of file sample-log-time-format.cc.
References ns3::Time::GetSeconds(), and ns3::Simulator::Now().
Referenced by ReplaceTimePrinter().
ReplaceTimePrinter()
void anonymous_namespace{sample-log-time-format.cc}::ReplaceTimePrinter (void)
Set ReplacementTimePrinter as the time printer for log messages.
Definition at line 113 of file sample-log-time-format.cc.
References ns3::LogSetTimePrinter(), and ReplacementTimePrinter().