ns-3: ns3::dsr Namespace Reference
ns3::dsr Namespace Reference
Classes
struct BlackList
BlackList description.
struct CloseNeighbor
CloseNeighbor structure.
class DsrErrorBuffEntry
DSR Error Buffer Entry.
class DsrErrorBuffer
DSR error buffer.
class DsrFsHeader
Dsr fixed size header Format.
class DsrGraReply
maintain the gratuitous reply
class DsrLinkStab
DsrLinkStab class (DSR link stability)
class DsrMaintainBuffEntry
DSR Maintain Buffer Entry.
class DsrMaintainBuffer
DSR maintain buffer.
class DsrNetworkQueue
Introspection did not find any typical Config paths.
class DsrNetworkQueueEntry
DSR Network Queue Entry.
class DsrNodeStab
DsrNodeStab class (DSR node stability)
class DsrOptionAck
Dsr Option Ack.
class DsrOptionAckHeader
Acknowledgement (ACK) Message Format.
class DsrOptionAckReq
Dsr Option.
class DsrOptionAckReqHeader
Acknowledgement Request (ACK_RREQ) Message Format.
class DsrOptionField
Option field for an DsrFsHeader Enables adding options to an DsrFsHeader.
class DsrOptionHeader
Header for Dsr Options.
class DsrOptionPad1
Dsr Option Pad1.
class DsrOptionPad1Header
Header of Dsr Option Pad1.
class DsrOptionPadn
IPv4 Option Padn.
class DsrOptionPadnHeader
Header of Dsr Option Padn.
class DsrOptionRerr
Dsr Option Route Error.
class DsrOptionRerrHeader
Header of Dsr Option Route Error.
class DsrOptionRerrUnreachHeader
Route Error (RERR) Unreachable node address option Message Format.
class DsrOptionRerrUnsupportHeader
Route Error (RERR) Unsupported option Message Format.
class DsrOptionRrep
Dsr Option Route Reply.
class DsrOptionRrepHeader
Route Reply (RREP) Message Format.
class DsrOptionRreq
Dsr Option Rreq.
class DsrOptionRreqHeader
Route Request (RREQ) Message Format.
class DsrOptions
Introspection did not find any typical Config paths.
class DsrOptionSR
Dsr Option Source Route.
class DsrOptionSRHeader
Source Route (SR) Message Format.
class DsrPassiveBuffEntry
DSR Passive Buffer Entry.
class DsrPassiveBuffer
DSR passive buffer.
class DsrReceivedRreqEntry
The request entry for intermediate nodes to check if they have received this request or not This is used to control the duplication request from being processed.
class DsrRouteCache
DSR route request queue Since DSR is an on demand routing we queue requests while looking for route.
class DsrRouteCacheEntry
DsrRouteCacheEntry class for entries in the route cache.
class DsrRouting
Dsr Routing base.
class DsrRoutingHeader
Header of Dsr Routing.
class DsrRreqTable
maintain list of DsrRreqTable entry
class DsrSendBuffEntry
DSR Send Buffer Entry.
class DsrSendBuffer
DSR send buffer.
struct GraReplyEntry
The gratuitous table entries, it maintains the already sent gratuitous route reply entries.
struct IsExpired
IsExpired structure.
struct Link
The route cache structure.
struct LinkKey
The maintenance buffer is responsible for maintaining packet next hop delivery The data packet is saved in maintenance buffer whenever the data packet is sent out of send buffer.
struct NetworkKey
NetworkKey structure.
struct PassiveKey
PassiveKey structure.
struct RreqTableEntry
The route request table entries.
Typedefs
typedef std::list< DsrRouteCacheEntry >::value_type route_pair
Enumerations
enum DsrMessageType { DSR_CONTROL_PACKET = 1 , DSR_DATA_PACKET = 2 }
enum ErrorType { NODE_UNREACHABLE = 1 , FLOW_STATE_NOT_SUPPORTED = 2 , OPTION_NOT_SUPPORTED = 3 }
Route Error (RERR) Message Format.
enum LinkStates { PROBABLE = 0 , QUESTIONABLE = 1 }
State of link.
Functions
bool CompareRoutesBoth (const DsrRouteCacheEntry &a, const DsrRouteCacheEntry &b)
bool CompareRoutesExpire (const DsrRouteCacheEntry &a, const DsrRouteCacheEntry &b)
bool CompareRoutesHops (const DsrRouteCacheEntry &a, const DsrRouteCacheEntry &b)
static std::ostream & operator<< (std::ostream &os, const DsrOptionSRHeader &sr)
static std::ostream & operator<< (std::ostream &os, const DsrRoutingHeader &dsr)
Typedef Documentation
route_pair
typedef std::list<DsrRouteCacheEntry>::value_type ns3::dsr::route_pair
Definition at line 104 of file dsr-rcache.cc.
Enumeration Type Documentation
DsrMessageType
enum ns3::dsr::DsrMessageType
Enumerator
DSR_CONTROL_PACKET
DSR_DATA_PACKET
Definition at line 44 of file dsr-network-queue.h.
LinkStates
enum ns3::dsr::LinkStates
State of link.
Enumerator
PROBABLE
PROBABLE.
QUESTIONABLE
QUESTIONABLE.
Definition at line 49 of file dsr-rreq-table.h.
Function Documentation
CompareRoutesBoth()
bool ns3::dsr::CompareRoutesBoth (const DsrRouteCacheEntry & a, const DsrRouteCacheEntry & b)
Definition at line 56 of file dsr-rcache.cc.
References ns3::dsr::DsrRouteCacheEntry::GetExpireTime(), and ns3::dsr::DsrRouteCacheEntry::GetVector().
CompareRoutesExpire()
bool ns3::dsr::CompareRoutesExpire (const DsrRouteCacheEntry & a, const DsrRouteCacheEntry & b)
Definition at line 70 of file dsr-rcache.cc.
References ns3::dsr::DsrRouteCacheEntry::GetExpireTime().
Referenced by ns3::dsr::DsrRouteCache::AddRoute(), ns3::dsr::DsrRouteCache::DeleteAllRoutesIncludeLink(), ns3::dsr::DsrRouteCache::FindSameRoute(), ns3::dsr::DsrRouteCache::LookupRoute(), and ns3::dsr::DsrRouteCache::UpdateRouteEntry().
CompareRoutesHops()
bool ns3::dsr::CompareRoutesHops (const DsrRouteCacheEntry & a, const DsrRouteCacheEntry & b)
Definition at line 64 of file dsr-rcache.cc.
References ns3::dsr::DsrRouteCacheEntry::GetVector().
operator<<() [1/2]
static std::ostream& ns3::dsr::operator<< (std::ostream & os, const DsrOptionSRHeader & sr) inline static
Definition at line 1347 of file dsr-option-header.h.
References ns3::dsr::DsrOptionSRHeader::Print().
operator<<() [2/2]
static std::ostream& ns3::dsr::operator<< (std::ostream & os, const DsrRoutingHeader & dsr) inline static
Definition at line 323 of file dsr-fs-header.h.
References ns3::dsr::DsrRoutingHeader::Print().