ns-3: src/openflow/examples/openflow-switch.cc File Reference
openflow-switch.cc File Reference
#include <iostream>
#include <fstream>
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/csma-module.h"
#include "ns3/internet-module.h"
#include "ns3/applications-module.h"
#include "ns3/openflow-module.h"
#include "ns3/log.h"
Functions
bool SetDrop (std::string value)
bool SetTimeout (std::string value)
bool SetVerbose (std::string value)
Variables
ns3::Time timeout = ns3::Seconds (0)
bool use_drop = false
bool verbose = false
Function Documentation
SetDrop()
bool SetDrop (std::string value)
Definition at line 62 of file openflow-switch.cc.
References use_drop.
SetTimeout()
bool SetTimeout (std::string value)
Definition at line 69 of file openflow-switch.cc.
References ns3::Seconds(), and timeout.
SetVerbose()
bool SetVerbose (std::string value)
Definition at line 55 of file openflow-switch.cc.
References verbose.
Variable Documentation
timeout
ns3::Time timeout = ns3::Seconds (0)
Definition at line 52 of file openflow-switch.cc.
Referenced by ns3::UanMacRc::Associate(), ns3::UanMacRc::AssociateTimeout(), ns3::MacLow::CreateBlockAckAgreement(), ns3::ArpCache::Entry::IsExpired(), ns3::BlockAckManager::NotifyGotBlockAck(), ns3::MacLow::ResetBlockAckInactivityTimerIfNeeded(), ns3::UanMacRc::RtsTimeout(), ns3::UanMacRc::ScheduleData(), ns3::QosTxop::SendAddBaRequest(), ns3::UanMacRc::SendRts(), ns3::ServiceFlow::SetArqPurgeTimeout(), ns3::ServiceFlow::SetArqRetryTimeoutRx(), ns3::ServiceFlow::SetArqRetryTimeoutTx(), ns3::RegularWifiMac::SetBeBlockAckInactivityTimeout(), ns3::RegularWifiMac::SetBkBlockAckInactivityTimeout(), ns3::QosTxop::SetBlockAckInactivityTimeout(), ns3::NscTcpSocketImpl::SetConnTimeout(), ns3::TcpSocketBase::SetConnTimeout(), ns3::NscTcpSocketImpl::SetDelAckTimeout(), ns3::TcpSocketBase::SetDelAckTimeout(), ns3::NscTcpSocketImpl::SetPersistTimeout(), ns3::TcpSocketBase::SetPersistTimeout(), SetTimeout(), ns3::BlockAckAgreement::SetTimeout(), ns3::MgtAddBaRequestHeader::SetTimeout(), ns3::MgtAddBaResponseHeader::SetTimeout(), ns3::RegularWifiMac::SetViBlockAckInactivityTimeout(), ns3::RegularWifiMac::SetVoBlockAckInactivityTimeout(), ns3::WimaxPhy::StartScanning(), and ns3::BlockAckManager::UpdateAgreement().
use_drop
bool use_drop = false
Definition at line 51 of file openflow-switch.cc.
Referenced by SetDrop().
verbose
bool verbose = false
Definition at line 50 of file openflow-switch.cc.
Referenced by PacketTagListTest::AddRemoveTime(), NotifyViaProbe(), NotifyViaTraceSource(), ns3::ShowProgress::SetVerbose(), and SetVerbose().