ns-3: examples/traffic-control/queue-discs-benchmark.cc File Reference
queue-discs-benchmark.cc File Reference
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/point-to-point-module.h"
#include "ns3/applications-module.h"
#include "ns3/internet-apps-module.h"
#include "ns3/traffic-control-module.h"
#include "ns3/flow-monitor-module.h"
Functions
void BytesInQueueTrace (Ptr< OutputStreamWrapper > stream, uint32_t oldVal, uint32_t newVal)
static void GoodputSampling (std::string fileName, ApplicationContainer app, Ptr< OutputStreamWrapper > stream, float period)
void LimitsTrace (Ptr< OutputStreamWrapper > stream, uint32_t oldVal, uint32_t newVal)
static void PingRtt (std::string context, Time rtt)
Function Documentation
BytesInQueueTrace()
void BytesInQueueTrace (Ptr< OutputStreamWrapper > stream, uint32_t oldVal, uint32_t newVal)
Definition at line 76 of file queue-discs-benchmark.cc.
References ns3::Time::GetSeconds(), ns3::OutputStreamWrapper::GetStream(), and ns3::Simulator::Now().
GoodputSampling()
static void GoodputSampling (std::string fileName, ApplicationContainer app, Ptr< OutputStreamWrapper > stream, float period) static
Definition at line 82 of file queue-discs-benchmark.cc.
References ns3::ApplicationContainer::Get(), ns3::Time::GetSeconds(), ns3::OutputStreamWrapper::GetStream(), ns3::Simulator::Now(), ns3::Simulator::Schedule(), and ns3::Seconds().
LimitsTrace()
void LimitsTrace (Ptr< OutputStreamWrapper > stream, uint32_t oldVal, uint32_t newVal)
Definition at line 70 of file queue-discs-benchmark.cc.
References ns3::Time::GetSeconds(), ns3::OutputStreamWrapper::GetStream(), and ns3::Simulator::Now().
PingRtt()
static void PingRtt (std::string context, Time rtt) static
Definition at line 91 of file queue-discs-benchmark.cc.
References ns3::Time::GetMilliSeconds().