ns-3: src/traffic-control/examples/red-tests.cc File Reference
red-tests.cc File Reference
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/flow-monitor-helper.h"
#include "ns3/point-to-point-module.h"
#include "ns3/applications-module.h"
#include "ns3/traffic-control-module.h"
Functions
void BuildAppsTest (uint32_t test)
void CheckQueueSize (Ptr< QueueDisc > queue)
Variables
double avgQueueSize
uint32_t checkTimes
double client_start_time
double client_stop_time
std::stringstream filePlotQueue
std::stringstream filePlotQueueAvg
double global_start_time
double global_stop_time
Ipv4InterfaceContainer i0i2
Ipv4InterfaceContainer i1i2
Ipv4InterfaceContainer i2i3
Ipv4InterfaceContainer i3i4
Ipv4InterfaceContainer i3i5
NodeContainer n0n2
NodeContainer n1n2
NodeContainer n2n3
NodeContainer n3n4
NodeContainer n3n5
double sink_start_time
double sink_stop_time
Function Documentation
BuildAppsTest()
void BuildAppsTest (uint32_t test)
Definition at line 100 of file red-tests.cc.
CheckQueueSize()
void CheckQueueSize (Ptr< QueueDisc > queue)
Definition at line 80 of file red-tests.cc.
References avgQueueSize, checkTimes, filePlotQueue, filePlotQueueAvg, ns3::QueueDisc::GetCurrentSize(), ns3::Time::GetSeconds(), ns3::QueueSize::GetValue(), ns3::Simulator::Now(), ns3::Simulator::Schedule(), and ns3::Seconds().
Variable Documentation
avgQueueSize
double avgQueueSize
Definition at line 54 of file red-tests.cc.
Referenced by CheckQueueSize().
checkTimes
uint32_t checkTimes
Definition at line 53 of file red-tests.cc.
Referenced by CheckQueueSize().
client_start_time
double client_start_time
Definition at line 61 of file red-tests.cc.
client_stop_time
double client_stop_time
Definition at line 62 of file red-tests.cc.
filePlotQueue
std::stringstream filePlotQueue
Definition at line 76 of file red-tests.cc.
Referenced by CheckQueueSize().
filePlotQueueAvg
std::stringstream filePlotQueueAvg
Definition at line 77 of file red-tests.cc.
Referenced by CheckQueueSize().
global_start_time
double global_start_time
Definition at line 57 of file red-tests.cc.
global_stop_time
double global_stop_time
Definition at line 58 of file red-tests.cc.
i0i2
Ipv4InterfaceContainer i0i2
Definition at line 70 of file red-tests.cc.
i1i2
Ipv4InterfaceContainer i1i2
Definition at line 71 of file red-tests.cc.
i2i3
Ipv4InterfaceContainer i2i3
Definition at line 72 of file red-tests.cc.
i3i4
Ipv4InterfaceContainer i3i4
Definition at line 73 of file red-tests.cc.
i3i5
Ipv4InterfaceContainer i3i5
Definition at line 74 of file red-tests.cc.
n0n2
NodeContainer n0n2
Definition at line 64 of file red-tests.cc.
n1n2
NodeContainer n1n2
Definition at line 65 of file red-tests.cc.
n2n3
NodeContainer n2n3
Definition at line 66 of file red-tests.cc.
n3n4
NodeContainer n3n4
Definition at line 67 of file red-tests.cc.
n3n5
NodeContainer n3n5
Definition at line 68 of file red-tests.cc.
sink_start_time
double sink_start_time
Definition at line 59 of file red-tests.cc.
sink_stop_time
double sink_stop_time
Definition at line 60 of file red-tests.cc.