ns-3: src/netanim/examples/resources-counters.cc File Reference
resources-counters.cc File Reference
#include <iostream>
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/point-to-point-module.h"
#include "ns3/netanim-module.h"
#include "ns3/applications-module.h"
#include "ns3/point-to-point-layout-module.h"
Classes
struct rgb
RGB structure.
Functions
void modify ()
Variables
struct rgb colors []
uint32_t nodeCounterIdDouble1
uint32_t nodeCounterIdDouble2
uint32_t nodeCounterIdUint32
AnimationInterface * pAnim = 0
uint32_t resourceId1
uint32_t resourceId2
Function Documentation
modify()
void modify ()
Definition at line 52 of file resources-counters.cc.
References rgb::b, colors, rgb::g, ns3::Time::GetSeconds(), ns3::UniformRandomVariable::GetValue(), nodeCounterIdDouble1, nodeCounterIdDouble2, nodeCounterIdUint32, ns3::Simulator::Now(), pAnim, rgb::r, resourceId1, resourceId2, ns3::Simulator::Schedule(), ns3::Seconds(), ns3::AnimationInterface::UpdateLinkDescription(), ns3::AnimationInterface::UpdateNodeColor(), ns3::AnimationInterface::UpdateNodeCounter(), ns3::AnimationInterface::UpdateNodeDescription(), ns3::AnimationInterface::UpdateNodeImage(), and ns3::AnimationInterface::UpdateNodeSize().
Variable Documentation
colors
struct rgb colors[]
Initial value:
= {
                        { 255, 0, 0 },
                        { 0, 255, 0 },
                        { 0, 0, 255 }
                        }
Definition at line 31 of file resources-counters.cc.
Referenced by modify().
nodeCounterIdDouble1
uint32_t nodeCounterIdDouble1
Definition at line 49 of file resources-counters.cc.
Referenced by modify().
nodeCounterIdDouble2
uint32_t nodeCounterIdDouble2
Definition at line 50 of file resources-counters.cc.
Referenced by modify().
nodeCounterIdUint32
uint32_t nodeCounterIdUint32
Definition at line 48 of file resources-counters.cc.
Referenced by modify().
pAnim
AnimationInterface* pAnim = 0
Definition at line 31 of file resources-counters.cc.
Referenced by modify().
resourceId1
uint32_t resourceId1
Definition at line 46 of file resources-counters.cc.
Referenced by modify().
resourceId2
uint32_t resourceId2
Definition at line 47 of file resources-counters.cc.
Referenced by modify().