ns-3: examples/socket/socket-bound-static-routing.cc File Reference
socket-bound-static-routing.cc File Reference
#include <iostream>
#include <fstream>
#include <string>
#include <cassert>
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/point-to-point-module.h"
#include "ns3/ipv4-static-routing-helper.h"
#include "ns3/ipv4-list-routing-helper.h"
Functions
void BindSock (Ptr< Socket > sock, Ptr< NetDevice > netdev)
void dstSocketRecv (Ptr< Socket > socket)
void SendStuff (Ptr< Socket > sock, Ipv4Address dstaddr, uint16_t port)
void srcSocketRecv (Ptr< Socket > socket)
Function Documentation
BindSock()
void BindSock (Ptr< Socket > sock, Ptr< NetDevice > netdev)
Definition at line 183 of file socket-bound-static-routing.cc.
References ns3::Socket::BindToNetDevice().
dstSocketRecv()
void dstSocketRecv (Ptr< Socket > socket)
Definition at line 208 of file socket-bound-static-routing.cc.
References first::address, ns3::InetSocketAddress::ConvertFrom(), ns3::Packet::GetSize(), NS_LOG_INFO, ns3::Socket::RecvFrom(), ns3::Packet::RemoveAllByteTags(), ns3::Packet::RemoveAllPacketTags(), and SendStuff().
SendStuff()
void SendStuff (Ptr< Socket > sock, Ipv4Address dstaddr, uint16_t port)
Definition at line 175 of file socket-bound-static-routing.cc.
References ns3::Packet::AddPaddingAtEnd(), port, and ns3::Socket::SendTo().
Referenced by dstSocketRecv().
srcSocketRecv()
void srcSocketRecv (Ptr< Socket > socket)
Definition at line 190 of file socket-bound-static-routing.cc.
References ns3::InetSocketAddress::ConvertFrom(), ns3::Socket::GetBoundNetDevice(), ns3::InetSocketAddress::GetIpv4(), ns3::Packet::GetSize(), NS_LOG_INFO, ns3::Socket::RecvFrom(), ns3::Packet::RemoveAllByteTags(), and ns3::Packet::RemoveAllPacketTags().