ns-3: examples/socket/socket-options-ipv6.cc File Reference
socket-options-ipv6.cc File Reference
#include <fstream>
#include "ns3/core-module.h"
#include "ns3/csma-module.h"
#include "ns3/applications-module.h"
#include "ns3/internet-module.h"
#include "ns3/network-module.h"
Functions
void ReceivePacket (Ptr< Socket > socket)
static void SendPacket (Ptr< Socket > socket, uint32_t pktSize, uint32_t pktCount, Time pktInterval)
Function Documentation
ReceivePacket()
void ReceivePacket (Ptr< Socket > socket)
Definition at line 37 of file socket-options-ipv6.cc.
References ns3::SocketIpv6HopLimitTag::GetHopLimit(), ns3::SocketIpv6TclassTag::GetTclass(), NS_LOG_INFO, ns3::Socket::Recv(), and ns3::Packet::RemovePacketTag().
SendPacket()
static void SendPacket (Ptr< Socket > socket, uint32_t pktSize, uint32_t pktCount, Time pktInterval) static
Definition at line 53 of file socket-options-ipv6.cc.
References ns3::Socket::Close(), pktSize, ns3::Simulator::Schedule(), and ns3::Socket::Send().