ns-3: ns3::UdpTraceClient Class Reference
ns3::UdpTraceClient Class Reference
Applications » UdpClientServer
Default trace to send.
#include "udp-trace-client.h"
Classes
struct TraceEntry
Entry to send.
Public Member Functions
UdpTraceClient ()
UdpTraceClient (Ipv4Address ip, uint16_t port, char *traceFile)
Creates a traceBasedStreamer application.
~UdpTraceClient ()
uint16_t GetMaxPacketSize (void)
Return the maximum packet size.
void SetMaxPacketSize (uint16_t maxPacketSize)
Set the maximum packet size.
void SetRemote (Address addr)
set the remote address
void SetRemote (Address ip, uint16_t port)
set the remote address and port
void SetTraceFile (std::string filename)
Set the trace file to be used by the application.
void SetTraceLoop (bool traceLoop)
Set the trace loop flag.
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<>
Ptr< Object > GetObject () const
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<>
Ptr< Object > GetObject (TypeId tid) const
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Application
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void LoadDefaultTrace (void)
Load the default trace.
void LoadTrace (std::string filename)
Load a trace file.
void Send (void)
Send a packet.
void SendPacket (uint32_t size)
Send a packet of a given size.
virtual void StartApplication (void)
Application specific startup code.
virtual void StopApplication (void)
Application specific shutdown code.
Private Attributes
uint32_t m_currentEntry
Current entry index.
std::vector< struct TraceEntry > m_entries
Entries in the trace to send.
uint16_t m_maxPacketSize
Maximum packet size to send (including the SeqTsHeader)
Address m_peerAddress
Remote peer address.
uint16_t m_peerPort
Remote peer port.
EventId m_sendEvent
Event to send the next packet.
uint32_t m_sent
Counter for sent packets.
Ptr< Socket > m_socket
Socket.
bool m_traceLoop
Loop through the trace file.
Static Private Attributes
static struct TraceEntry g_defaultEntries []
Default trace to send.
Additional Inherited Members
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Default trace to send.
A trace based streamer.
Sends UDP packets based on a trace file of an MPEG4 stream trace files could be downloaded form: http://www2.tkn.tu-berlin.de/research/trace/ltvt.html (the 2 first lines of the file should be removed) A valid trace file is a file with 4 columns:
-1- the first one represents the frame index
-2- the second one indicates the type of the frame: I, P or B
-3- the third one indicates the time on which the frame was generated by the encoder (integer, milliseconds)
-4- the fourth one indicates the frame size in byte
If no valid MPEG4 trace file is provided to the application the trace from g_defaultEntries array will be loaded.
Also note that:
-1- consecutive 'B' frames are sent together,
-2- any trace file is (by default) read again once finished (loop).
The latter behavior can be changed through the "TraceLoop" attribute.
Config Paths
ns3::UdpTraceClient is accessible through the following paths with Config::Set and Config::Connect:
"/NodeList/[i]/ApplicationList/[i]/$ns3::UdpTraceClient"
Attributes
RemoteAddress: The destination Address of the outbound packets
Set with class: AddressValue
Underlying type: Address
Initial value: 00-00-00
Flags: construct write read
RemotePort: The destination port of the outbound packets
Set with class: ns3::UintegerValue
Underlying type: uint16_t 0:65535
Initial value: 100
Flags: construct write read
MaxPacketSize: The maximum size of a packet (including the SeqTsHeader, 12 bytes).
Set with class: ns3::UintegerValue
Underlying type: uint32_t 0:4294967295
Initial value: 1024
Flags: construct write read
TraceFilename: Name of file to load a trace from. By default, uses a hardcoded trace.
Set with class: StringValue
Underlying type:
Initial value:
Flags: construct write
TraceLoop: Loops through the trace file, starting again once it is over.
Set with class: BooleanValue
Underlying type: bool
Initial value: true
Flags: construct write
Attributes defined in parent class ns3::Application
StartTime: Time at which the application will start
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
StopTime: Time at which the application will stop
Set with class: ns3::TimeValue
Underlying type: Time -9.22337e+18ns:+9.22337e+18ns
Initial value: +0ns
Flags: construct write read
No TraceSources are defined for this type.
Size of this type is 200 bytes (on a 64-bit architecture).
Definition at line 48 of file udp-trace-client.cc.
Constructor & Destructor Documentation
UdpTraceClient() [1/2]
ns3::UdpTraceClient::UdpTraceClient ()
Definition at line 98 of file udp-trace-client.cc.
References m_maxPacketSize, m_sendEvent, m_sent, m_socket, and NS_LOG_FUNCTION.
UdpTraceClient() [2/2]
ns3::UdpTraceClient::UdpTraceClient (Ipv4Address ip, uint16_t port, char * traceFile)
Creates a traceBasedStreamer application.
Parameters
ip the destination ip address to which the stream will be sent
port the destination udp port to which the stream will be sent
traceFile a path to an MPEG4 trace file formatted as follows: FrameNo Frametype Time[ms] Length [byte] FrameNo Frametype Time[ms] Length [byte] ...
Definition at line 107 of file udp-trace-client.cc.
References m_currentEntry, m_maxPacketSize, m_peerAddress, m_peerPort, m_sendEvent, m_sent, m_socket, NS_LOG_FUNCTION, port, and SetTraceFile().
~UdpTraceClient()
ns3::UdpTraceClient::~UdpTraceClient ()
Definition at line 124 of file udp-trace-client.cc.
References m_entries, and NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::UdpTraceClient::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Application.
Definition at line 177 of file udp-trace-client.cc.
References ns3::Application::DoDispose(), and NS_LOG_FUNCTION.
GetMaxPacketSize()
uint16_t ns3::UdpTraceClient::GetMaxPacketSize (void)
Return the maximum packet size.
Returns
the maximum packet size
Definition at line 169 of file udp-trace-client.cc.
References m_maxPacketSize, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::UdpTraceClient::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 62 of file udp-trace-client.cc.
References m_maxPacketSize, m_peerAddress, m_peerPort, ns3::MakeAddressAccessor(), ns3::MakeAddressChecker(), ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeStringAccessor(), ns3::MakeStringChecker(), ns3::MakeUintegerAccessor(), ns3::TypeId::SetParent(), SetTraceFile(), and SetTraceLoop().
Referenced by ns3::UdpTraceClientHelper::UdpTraceClientHelper().
LoadDefaultTrace()
void ns3::UdpTraceClient::LoadDefaultTrace (void) private
Load the default trace.
Definition at line 228 of file udp-trace-client.cc.
References ns3::UdpTraceClient::TraceEntry::frameType, g_defaultEntries, m_currentEntry, m_entries, NS_LOG_FUNCTION, and ns3::UdpTraceClient::TraceEntry::timeToSend.
Referenced by LoadTrace(), and SetTraceFile().
LoadTrace()
void ns3::UdpTraceClient::LoadTrace (std::string filename) private
Load a trace file.
Parameters
filename the trace file path
Definition at line 184 of file udp-trace-client.cc.
References ns3::UdpTraceClient::TraceEntry::frameType, LoadDefaultTrace(), m_currentEntry, m_entries, NS_ASSERT_MSG, NS_LOG_FUNCTION, ns3::UdpTraceClient::TraceEntry::packetSize, and ns3::UdpTraceClient::TraceEntry::timeToSend.
Referenced by SetTraceFile().
Send()
void ns3::UdpTraceClient::Send (void) private
Send a packet.
Definition at line 355 of file udp-trace-client.cc.
References ns3::EventId::IsExpired(), m_currentEntry, m_entries, m_maxPacketSize, m_sendEvent, m_traceLoop, ns3::MilliSeconds(), NS_ASSERT, NS_LOG_FUNCTION, ns3::UdpTraceClient::TraceEntry::packetSize, ns3::Simulator::Schedule(), SendPacket(), and ns3::UdpTraceClient::TraceEntry::timeToSend.
Referenced by StartApplication().
SendPacket()
void ns3::UdpTraceClient::SendPacket (uint32_t size) private
Send a packet of a given size.
Parameters
size the packet size
Definition at line 309 of file udp-trace-client.cc.
References ns3::Packet::AddHeader(), ns3::Ipv4Address::ConvertFrom(), ns3::Ipv6Address::ConvertFrom(), ns3::Ipv4Address::IsMatchingType(), ns3::Ipv6Address::IsMatchingType(), m_peerAddress, m_sent, m_socket, NS_LOG_FUNCTION, NS_LOG_INFO, packetSize, ns3::Socket::Send(), and ns3::SeqTsHeader::SetSeq().
Referenced by Send().
SetMaxPacketSize()
void ns3::UdpTraceClient::SetMaxPacketSize (uint16_t maxPacketSize)
Set the maximum packet size.
Parameters
maxPacketSize The maximum packet size
Definition at line 162 of file udp-trace-client.cc.
References m_maxPacketSize, and NS_LOG_FUNCTION.
SetRemote() [1/2]
void ns3::UdpTraceClient::SetRemote (Address addr)
set the remote address
Parameters
addr remote address
Definition at line 140 of file udp-trace-client.cc.
References m_entries, m_peerAddress, and NS_LOG_FUNCTION.
SetRemote() [2/2]
void ns3::UdpTraceClient::SetRemote (Address ip, uint16_t port)
set the remote address and port
Parameters
ip remote IP address
port remote port
Definition at line 131 of file udp-trace-client.cc.
References m_entries, m_peerAddress, m_peerPort, NS_LOG_FUNCTION, and port.
SetTraceFile()
void ns3::UdpTraceClient::SetTraceFile (std::string filename)
Set the trace file to be used by the application.
Parameters
filename a path to an MPEG4 trace file formatted as follows: Frame No Frametype Time[ms] Length [byte] Frame No Frametype Time[ms] Length [byte] ...
Definition at line 148 of file udp-trace-client.cc.
References LoadDefaultTrace(), LoadTrace(), and NS_LOG_FUNCTION.
Referenced by UdpTraceClient(), and GetTypeId().
SetTraceLoop()
void ns3::UdpTraceClient::SetTraceLoop (bool traceLoop)
Set the trace loop flag.
Parameters
traceLoop true if the trace should be re-used
Definition at line 391 of file udp-trace-client.cc.
References m_traceLoop.
Referenced by GetTypeId().
StartApplication()
void ns3::UdpTraceClient::StartApplication (void) private virtual
Application specific startup code.
The StartApplication method is called at the start time specified by Start This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 251 of file udp-trace-client.cc.
References ns3::Socket::Bind(), ns3::Socket::Bind6(), ns3::Socket::Connect(), ns3::Ipv4Address::ConvertFrom(), ns3::Ipv6Address::ConvertFrom(), ns3::Socket::CreateSocket(), ns3::Application::GetNode(), ns3::Inet6SocketAddress::IsMatchingType(), ns3::InetSocketAddress::IsMatchingType(), ns3::Ipv4Address::IsMatchingType(), ns3::Ipv6Address::IsMatchingType(), ns3::TypeId::LookupByName(), m_peerAddress, m_peerPort, m_sendEvent, m_socket, ns3::MakeNullCallback(), NS_ASSERT_MSG, NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), ns3::Seconds(), Send(), ns3::Socket::SetAllowBroadcast(), and ns3::Socket::SetRecvCallback().
StopApplication()
void ns3::UdpTraceClient::StopApplication (void) private virtual
Application specific shutdown code.
The StopApplication method is called at the stop time specified by Stop This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 302 of file udp-trace-client.cc.
References ns3::Simulator::Cancel(), m_sendEvent, and NS_LOG_FUNCTION.
Member Data Documentation
g_defaultEntries
struct TraceEntry ns3::UdpTraceClient::g_defaultEntries[] static private
Default trace to send.
Definition at line 169 of file udp-trace-client.h.
Referenced by LoadDefaultTrace().
m_currentEntry
uint32_t ns3::UdpTraceClient::m_currentEntry private
Current entry index.
Definition at line 169 of file udp-trace-client.h.
Referenced by UdpTraceClient(), LoadDefaultTrace(), LoadTrace(), and Send().
m_entries
std::vector<struct TraceEntry> ns3::UdpTraceClient::m_entries private
Entries in the trace to send.
Definition at line 168 of file udp-trace-client.h.
Referenced by ~UdpTraceClient(), LoadDefaultTrace(), LoadTrace(), Send(), and SetRemote().
m_maxPacketSize
uint16_t ns3::UdpTraceClient::m_maxPacketSize private
Maximum packet size to send (including the SeqTsHeader)
Definition at line 171 of file udp-trace-client.h.
Referenced by UdpTraceClient(), GetMaxPacketSize(), GetTypeId(), Send(), and SetMaxPacketSize().
m_peerAddress
Address ns3::UdpTraceClient::m_peerAddress private
Remote peer address.
Definition at line 164 of file udp-trace-client.h.
Referenced by UdpTraceClient(), GetTypeId(), SendPacket(), SetRemote(), and StartApplication().
m_peerPort
uint16_t ns3::UdpTraceClient::m_peerPort private
Remote peer port.
Definition at line 165 of file udp-trace-client.h.
Referenced by UdpTraceClient(), GetTypeId(), SetRemote(), and StartApplication().
m_sendEvent
EventId ns3::UdpTraceClient::m_sendEvent private
Event to send the next packet.
Definition at line 166 of file udp-trace-client.h.
Referenced by UdpTraceClient(), Send(), StartApplication(), and StopApplication().
m_sent
uint32_t ns3::UdpTraceClient::m_sent private
Counter for sent packets.
Definition at line 162 of file udp-trace-client.h.
Referenced by UdpTraceClient(), and SendPacket().
m_socket
Ptr<Socket> ns3::UdpTraceClient::m_socket private
Socket.
Definition at line 163 of file udp-trace-client.h.
Referenced by UdpTraceClient(), SendPacket(), and StartApplication().
m_traceLoop
bool ns3::UdpTraceClient::m_traceLoop private
Loop through the trace file.
Definition at line 172 of file udp-trace-client.h.
Referenced by Send(), and SetTraceLoop().
The documentation for this class was generated from the following files:
src/applications/model/udp-trace-client.cc
src/applications/model/udp-trace-client.h