ns-3: ns3::aodv::NeighborTest Struct Reference
ns3::aodv::NeighborTest Struct Reference
AODV Routing » AODV module tests | Test suites
Unit test for neighbors.
Public Member Functions
NeighborTest ()
void CheckTimeout1 ()
Check timeout function 1.
void CheckTimeout2 ()
Check timeout function 2.
void CheckTimeout3 ()
Check timeout function 3.
virtual void DoRun ()
Implementation to actually run this TestCase.
void Handler (Ipv4Address addr)
Handler test function.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Public Attributes
Neighbors * neighbor
The Neighbors.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Unit test for neighbors.
Definition at line 36 of file aodv-test-suite.cc.
Constructor & Destructor Documentation
NeighborTest()
ns3::aodv::NeighborTest::NeighborTest () inline
Definition at line 38 of file aodv-test-suite.cc.
Member Function Documentation
CheckTimeout1()
void ns3::aodv::NeighborTest::CheckTimeout1 ()
Check timeout function 1.
Definition at line 64 of file aodv-test-suite.cc.
References ns3::aodv::Neighbors::IsNeighbor(), neighbor, and NS_TEST_EXPECT_MSG_EQ.
Referenced by DoRun().
CheckTimeout2()
void ns3::aodv::NeighborTest::CheckTimeout2 ()
Check timeout function 2.
Definition at line 72 of file aodv-test-suite.cc.
References ns3::aodv::Neighbors::IsNeighbor(), neighbor, and NS_TEST_EXPECT_MSG_EQ.
Referenced by DoRun().
CheckTimeout3()
void ns3::aodv::NeighborTest::CheckTimeout3 ()
Check timeout function 3.
Definition at line 80 of file aodv-test-suite.cc.
References ns3::aodv::Neighbors::IsNeighbor(), neighbor, and NS_TEST_EXPECT_MSG_EQ.
Referenced by DoRun().
DoRun()
void ns3::aodv::NeighborTest::DoRun () virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 89 of file aodv-test-suite.cc.
References CheckTimeout1(), CheckTimeout2(), CheckTimeout3(), ns3::Simulator::Destroy(), ns3::aodv::Neighbors::GetExpireTime(), Handler(), ns3::aodv::Neighbors::IsNeighbor(), ns3::MakeCallback(), neighbor, NS_TEST_EXPECT_MSG_EQ, ns3::Simulator::Run(), ns3::Simulator::Schedule(), ns3::Seconds(), ns3::aodv::Neighbors::SetCallback(), and ns3::aodv::Neighbors::Update().
Handler()
void ns3::aodv::NeighborTest::Handler (Ipv4Address addr)
Handler test function.
Parameters
addr the IPv4 address of the neighbor
Definition at line 59 of file aodv-test-suite.cc.
Referenced by DoRun().
Member Data Documentation
neighbor
Neighbors* ns3::aodv::NeighborTest::neighbor
The Neighbors.
Definition at line 55 of file aodv-test-suite.cc.
Referenced by CheckTimeout1(), CheckTimeout2(), CheckTimeout3(), and DoRun().
The documentation for this struct was generated from the following file:
src/aodv/test/aodv-test-suite.cc