ns-3: ns3::aodv::AodvRqueueTest Struct Reference
ns3::aodv::AodvRqueueTest Struct Reference
Unit test for RequestQueue.
Public Member Functions
AodvRqueueTest ()
void CheckSizeLimit ()
Check size limit function.
void CheckTimeout ()
Check timeout function.
virtual void DoRun ()
Implementation to actually run this TestCase.
void Error (Ptr< const Packet > p, const Ipv4Header &h, Socket::SocketErrno e)
Error test function.
void Unicast (Ptr< Ipv4Route > route, Ptr< const Packet > packet, const Ipv4Header &header)
Unicast test function.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Public Attributes
RequestQueue q
Request queue.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1 , EXTENSIVE = 2 , TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Unit test for RequestQueue.
Definition at line 377 of file aodv-test-suite.cc.
Constructor & Destructor Documentation
AodvRqueueTest()
ns3::aodv::AodvRqueueTest::AodvRqueueTest () inline
Definition at line 379 of file aodv-test-suite.cc.
Member Function Documentation
CheckSizeLimit()
void ns3::aodv::AodvRqueueTest::CheckSizeLimit ()
Check size limit function.
Definition at line 471 of file aodv-test-suite.cc.
References ns3::aodv::RequestQueue::Enqueue(), Error(), ns3::aodv::RequestQueue::GetMaxQueueLen(), ns3::aodv::RequestQueue::GetSize(), ns3::MakeCallback(), NS_TEST_EXPECT_MSG_EQ, q, ns3::Seconds(), and Unicast().
Referenced by DoRun().
CheckTimeout()
void ns3::aodv::AodvRqueueTest::CheckTimeout ()
Check timeout function.
Definition at line 493 of file aodv-test-suite.cc.
References ns3::aodv::RequestQueue::GetSize(), NS_TEST_EXPECT_MSG_EQ, and q.
Referenced by DoRun().
DoRun()
void ns3::aodv::AodvRqueueTest::DoRun () virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 412 of file aodv-test-suite.cc.
References CheckSizeLimit(), CheckTimeout(), ns3::aodv::RequestQueue::Dequeue(), ns3::Simulator::Destroy(), ns3::aodv::RequestQueue::DropPacketWithDst(), ns3::aodv::RequestQueue::Enqueue(), Error(), ns3::aodv::RequestQueue::Find(), ns3::aodv::RequestQueue::GetMaxQueueLen(), ns3::aodv::RequestQueue::GetQueueTimeout(), ns3::aodv::RequestQueue::GetSize(), ns3::MakeCallback(), NS_TEST_EXPECT_MSG_EQ, q, ns3::Simulator::Run(), ns3::Simulator::Schedule(), ns3::Seconds(), ns3::Ipv4Header::SetDestination(), ns3::aodv::RequestQueue::SetMaxQueueLen(), ns3::aodv::RequestQueue::SetQueueTimeout(), ns3::Ipv4Header::SetSource(), and Unicast().
Error()
void ns3::aodv::AodvRqueueTest::Error (Ptr< const Packet > p, const Ipv4Header & h, Socket::SocketErrno e) inline
Error test function.
Parameters
p The packet
h The header
e the socket error
Definition at line 399 of file aodv-test-suite.cc.
Referenced by CheckSizeLimit(), and DoRun().
Unicast()
void ns3::aodv::AodvRqueueTest::Unicast (Ptr< Ipv4Route > route, Ptr< const Packet > packet, const Ipv4Header & header) inline
Unicast test function.
Parameters
route the IPv4 route
packet the packet
header the IPv4 header
Definition at line 390 of file aodv-test-suite.cc.
Referenced by CheckSizeLimit(), and DoRun().
Member Data Documentation
q
RequestQueue ns3::aodv::AodvRqueueTest::q
Request queue.
Definition at line 408 of file aodv-test-suite.cc.
Referenced by CheckSizeLimit(), CheckTimeout(), and DoRun().
The documentation for this struct was generated from the following file:
src/aodv/test/aodv-test-suite.cc