ns-3: examples/tcp/tcp-pacing.cc File Reference
tcp-pacing.cc File Reference
#include <iomanip>
#include <iostream>
#include <string>
#include <fstream>
#include "ns3/core-module.h"
#include "ns3/point-to-point-module.h"
#include "ns3/internet-module.h"
#include "ns3/applications-module.h"
#include "ns3/network-module.h"
#include "ns3/packet-sink.h"
#include "ns3/flow-monitor-module.h"
#include "ns3/ipv4-global-routing-helper.h"
#include "ns3/traffic-control-module.h"
Functions
void ConnectSocketTraces (void)
static void CwndTracer (uint32_t oldval, uint32_t newval)
static void PacingRateTracer (DataRate oldval, DataRate newval)
static void RxTracer (Ptr< const Packet > p, Ptr< Ipv4 > ipv4, uint32_t interface)
static void SsThreshTracer (uint32_t oldval, uint32_t newval)
static void TxTracer (Ptr< const Packet > p, Ptr< Ipv4 > ipv4, uint32_t interface)
Variables
std::ofstream cwndStream
std::ofstream pacingRateStream
std::ofstream packetTraceStream
std::ofstream ssThreshStream
Function Documentation
ConnectSocketTraces()
void ConnectSocketTraces (void)
Definition at line 136 of file tcp-pacing.cc.
References ns3::Config::ConnectWithoutContext(), CwndTracer(), ns3::MakeCallback(), PacingRateTracer(), RxTracer(), SsThreshTracer(), and TxTracer().
CwndTracer()
static void CwndTracer (uint32_t oldval, uint32_t newval) static
Definition at line 106 of file tcp-pacing.cc.
References cwndStream, ns3::Time::GetSeconds(), and ns3::Simulator::Now().
Referenced by ConnectSocketTraces().
PacingRateTracer()
static void PacingRateTracer (DataRate oldval, DataRate newval) static
Definition at line 112 of file tcp-pacing.cc.
References ns3::DataRate::GetBitRate(), ns3::Time::GetSeconds(), ns3::Simulator::Now(), and pacingRateStream.
Referenced by ConnectSocketTraces().
RxTracer()
static void RxTracer (Ptr< const Packet > p, Ptr< Ipv4 > ipv4, uint32_t interface) static
Definition at line 130 of file tcp-pacing.cc.
References ns3::Time::GetSeconds(), ns3::Simulator::Now(), and packetTraceStream.
Referenced by ConnectSocketTraces().
SsThreshTracer()
static void SsThreshTracer (uint32_t oldval, uint32_t newval) static
Definition at line 118 of file tcp-pacing.cc.
References ns3::Time::GetSeconds(), ns3::Simulator::Now(), and ssThreshStream.
Referenced by ConnectSocketTraces().
TxTracer()
static void TxTracer (Ptr< const Packet > p, Ptr< Ipv4 > ipv4, uint32_t interface) static
Definition at line 124 of file tcp-pacing.cc.
References ns3::Time::GetSeconds(), ns3::Simulator::Now(), and packetTraceStream.
Referenced by ConnectSocketTraces().
Variable Documentation
cwndStream
std::ofstream cwndStream
Definition at line 100 of file tcp-pacing.cc.
Referenced by CwndTracer().
pacingRateStream
std::ofstream pacingRateStream
Definition at line 101 of file tcp-pacing.cc.
Referenced by PacingRateTracer().
packetTraceStream
std::ofstream packetTraceStream
Definition at line 103 of file tcp-pacing.cc.
Referenced by RxTracer(), and TxTracer().
ssThreshStream
std::ofstream ssThreshStream
Definition at line 102 of file tcp-pacing.cc.
Referenced by SsThreshTracer().