ns-3: examples/tcp/tcp-validation.cc File Reference
tcp-validation.cc File Reference
#include <iostream>
#include <fstream>
#include <string>
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/applications-module.h"
#include "ns3/traffic-control-module.h"
#include "ns3/internet-module.h"
#include "ns3/internet-apps-module.h"
#include "ns3/point-to-point-module.h"
Functions
void ScheduleFirstDctcpTraceConnection (std::ofstream *ofStream)
void ScheduleFirstPacketSinkConnection (void)
void ScheduleFirstTcpCwndTraceConnection (std::ofstream *ofStream)
void ScheduleFirstTcpRttTraceConnection (std::ofstream *ofStream)
void ScheduleSecondDctcpTraceConnection (std::ofstream *ofStream)
void ScheduleSecondPacketSinkConnection (void)
void ScheduleSecondTcpCwndTraceConnection (std::ofstream *ofStream)
void ScheduleSecondTcpRttTraceConnection (std::ofstream *ofStream)
void TraceFirstCwnd (std::ofstream *ofStream, uint32_t oldCwnd, uint32_t newCwnd)
void TraceFirstDctcp (std::ofstream *ofStream, uint32_t bytesMarked, uint32_t bytesAcked, double alpha)
void TraceFirstRtt (std::ofstream *ofStream, Time oldRtt, Time newRtt)
void TraceFirstRx (Ptr< const Packet > packet, const Address &address)
void TraceFirstThroughput (std::ofstream *ofStream, Time throughputInterval)
void TraceMarksFrequency (std::ofstream *ofStream, Time marksSamplingInterval)
void TracePingRtt (std::ofstream *ofStream, Time rtt)
void TraceQueueDrop (std::ofstream *ofStream, Ptr< const QueueDiscItem > item)
void TraceQueueLength (std::ofstream *ofStream, DataRate queueLinkRate, uint32_t oldVal, uint32_t newVal)
void TraceQueueMark (std::ofstream *ofStream, Ptr< const QueueDiscItem > item, const char *reason)
void TraceSecondCwnd (std::ofstream *ofStream, uint32_t oldCwnd, uint32_t newCwnd)
void TraceSecondDctcp (std::ofstream *ofStream, uint32_t bytesMarked, uint32_t bytesAcked, double alpha)
void TraceSecondRtt (std::ofstream *ofStream, Time oldRtt, Time newRtt)
void TraceSecondRx (Ptr< const Packet > packet, const Address &address)
void TraceSecondThroughput (std::ofstream *ofStream, Time throughputInterval)
Variables
uint32_t g_dropsObserved = 0
uint32_t g_firstBytesReceived = 0
uint32_t g_marksObserved = 0
uint32_t g_secondBytesReceived = 0
std::string g_validate = ""
bool g_validationFailed = false
Function Documentation
ScheduleFirstDctcpTraceConnection()
void ScheduleFirstDctcpTraceConnection (std::ofstream * ofStream)
Definition at line 399 of file tcp-validation.cc.
References ns3::Config::ConnectWithoutContextFailSafe(), ns3::MakeBoundCallback(), and TraceFirstDctcp().
ScheduleFirstPacketSinkConnection()
void ScheduleFirstPacketSinkConnection (void)
Definition at line 411 of file tcp-validation.cc.
References ns3::Config::ConnectWithoutContextFailSafe(), ns3::MakeCallback(), and TraceFirstRx().
ScheduleFirstTcpCwndTraceConnection()
void ScheduleFirstTcpCwndTraceConnection (std::ofstream * ofStream)
Definition at line 387 of file tcp-validation.cc.
References ns3::Config::ConnectWithoutContextFailSafe(), ns3::MakeBoundCallback(), and TraceFirstCwnd().
ScheduleFirstTcpRttTraceConnection()
void ScheduleFirstTcpRttTraceConnection (std::ofstream * ofStream)
Definition at line 393 of file tcp-validation.cc.
References ns3::Config::ConnectWithoutContextFailSafe(), ns3::MakeBoundCallback(), and TraceFirstRtt().
ScheduleSecondDctcpTraceConnection()
void ScheduleSecondDctcpTraceConnection (std::ofstream * ofStream)
Definition at line 405 of file tcp-validation.cc.
References ns3::Config::ConnectWithoutContextFailSafe(), ns3::MakeBoundCallback(), and TraceSecondDctcp().
ScheduleSecondPacketSinkConnection()
void ScheduleSecondPacketSinkConnection (void)
Definition at line 429 of file tcp-validation.cc.
References ns3::Config::ConnectWithoutContext(), ns3::MakeCallback(), and TraceSecondRx().
ScheduleSecondTcpCwndTraceConnection()
void ScheduleSecondTcpCwndTraceConnection (std::ofstream * ofStream)
Definition at line 417 of file tcp-validation.cc.
References ns3::Config::ConnectWithoutContext(), ns3::MakeBoundCallback(), and TraceSecondCwnd().
ScheduleSecondTcpRttTraceConnection()
void ScheduleSecondTcpRttTraceConnection (std::ofstream * ofStream)
Definition at line 423 of file tcp-validation.cc.
References ns3::Config::ConnectWithoutContext(), ns3::MakeBoundCallback(), and TraceSecondRtt().
TraceFirstCwnd()
void TraceFirstCwnd (std::ofstream * ofStream, uint32_t oldCwnd, uint32_t newCwnd)
Definition at line 169 of file tcp-validation.cc.
References g_validate, g_validationFailed, ns3::Time::GetSeconds(), and ns3::Simulator::Now().
Referenced by ScheduleFirstTcpCwndTraceConnection().
TraceFirstDctcp()
void TraceFirstDctcp (std::ofstream * ofStream, uint32_t bytesMarked, uint32_t bytesAcked, double alpha)
Definition at line 202 of file tcp-validation.cc.
References sample-rng-plot::alpha, g_validate, g_validationFailed, ns3::Time::GetSeconds(), and ns3::Simulator::Now().
Referenced by ScheduleFirstDctcpTraceConnection().
TraceFirstRtt()
void TraceFirstRtt (std::ofstream * ofStream, Time oldRtt, Time newRtt)
Definition at line 240 of file tcp-validation.cc.
References g_validate, ns3::Time::GetSeconds(), and ns3::Simulator::Now().
Referenced by ScheduleFirstTcpRttTraceConnection().
TraceFirstRx()
void TraceFirstRx (Ptr< const Packet > packet, const Address & address)
Definition at line 287 of file tcp-validation.cc.
References g_firstBytesReceived.
Referenced by ScheduleFirstPacketSinkConnection().
TraceFirstThroughput()
void TraceFirstThroughput (std::ofstream * ofStream, Time throughputInterval)
Definition at line 340 of file tcp-validation.cc.
References g_firstBytesReceived, g_validate, g_validationFailed, ns3::Time::GetSeconds(), ns3::Simulator::Now(), and ns3::Simulator::Schedule().
TraceMarksFrequency()
void TraceMarksFrequency (std::ofstream * ofStream, Time marksSamplingInterval)
Definition at line 329 of file tcp-validation.cc.
References g_marksObserved, g_validate, ns3::Time::GetSeconds(), ns3::Simulator::Now(), and ns3::Simulator::Schedule().
TracePingRtt()
void TracePingRtt (std::ofstream * ofStream, Time rtt)
Definition at line 278 of file tcp-validation.cc.
References g_validate, ns3::Time::GetSeconds(), and ns3::Simulator::Now().
TraceQueueDrop()
void TraceQueueDrop (std::ofstream * ofStream, Ptr< const QueueDiscItem > item)
Definition at line 299 of file tcp-validation.cc.
References g_dropsObserved, g_validate, ns3::Time::GetSeconds(), and ns3::Simulator::Now().
TraceQueueLength()
void TraceQueueLength (std::ofstream * ofStream, DataRate queueLinkRate, uint32_t oldVal, uint32_t newVal)
Definition at line 319 of file tcp-validation.cc.
References g_validate, ns3::DataRate::GetBitRate(), ns3::Time::GetSeconds(), and ns3::Simulator::Now().
TraceQueueMark()
void TraceQueueMark (std::ofstream * ofStream, Ptr< const QueueDiscItem > item, const char * reason)
Definition at line 309 of file tcp-validation.cc.
References g_marksObserved, g_validate, ns3::Time::GetSeconds(), and ns3::Simulator::Now().
TraceSecondCwnd()
void TraceSecondCwnd (std::ofstream * ofStream, uint32_t oldCwnd, uint32_t newCwnd)
Definition at line 249 of file tcp-validation.cc.
References g_validate, ns3::Time::GetSeconds(), and ns3::Simulator::Now().
Referenced by ScheduleSecondTcpCwndTraceConnection().
TraceSecondDctcp()
void TraceSecondDctcp (std::ofstream * ofStream, uint32_t bytesMarked, uint32_t bytesAcked, double alpha)
Definition at line 269 of file tcp-validation.cc.
References sample-rng-plot::alpha, g_validate, ns3::Time::GetSeconds(), and ns3::Simulator::Now().
Referenced by ScheduleSecondDctcpTraceConnection().
TraceSecondRtt()
void TraceSecondRtt (std::ofstream * ofStream, Time oldRtt, Time newRtt)
Definition at line 260 of file tcp-validation.cc.
References g_validate, ns3::Time::GetSeconds(), and ns3::Simulator::Now().
Referenced by ScheduleSecondTcpRttTraceConnection().
TraceSecondRx()
void TraceSecondRx (Ptr< const Packet > packet, const Address & address)
Definition at line 293 of file tcp-validation.cc.
References g_secondBytesReceived.
Referenced by ScheduleSecondPacketSinkConnection().
TraceSecondThroughput()
void TraceSecondThroughput (std::ofstream * ofStream, Time throughputInterval)
Definition at line 376 of file tcp-validation.cc.
References g_secondBytesReceived, g_validate, ns3::Time::GetSeconds(), ns3::Simulator::Now(), and ns3::Simulator::Schedule().
Variable Documentation
g_dropsObserved
uint32_t g_dropsObserved = 0
Definition at line 164 of file tcp-validation.cc.
Referenced by TraceQueueDrop().
g_firstBytesReceived
uint32_t g_firstBytesReceived = 0
Definition at line 161 of file tcp-validation.cc.
Referenced by TraceFirstRx(), and TraceFirstThroughput().
g_marksObserved
uint32_t g_marksObserved = 0
Definition at line 163 of file tcp-validation.cc.
Referenced by TraceMarksFrequency(), and TraceQueueMark().
g_secondBytesReceived
uint32_t g_secondBytesReceived = 0
Definition at line 162 of file tcp-validation.cc.
Referenced by TraceSecondRx(), and TraceSecondThroughput().
g_validate
std::string g_validate = ""
Definition at line 165 of file tcp-validation.cc.
Referenced by TraceFirstCwnd(), TraceFirstDctcp(), TraceFirstRtt(), TraceFirstThroughput(), TraceMarksFrequency(), TracePingRtt(), TraceQueueDrop(), TraceQueueLength(), TraceQueueMark(), TraceSecondCwnd(), TraceSecondDctcp(), TraceSecondRtt(), and TraceSecondThroughput().
g_validationFailed
bool g_validationFailed = false
Definition at line 166 of file tcp-validation.cc.
Referenced by TraceFirstCwnd(), TraceFirstDctcp(), and TraceFirstThroughput().