ns-3: src/wave/examples/vanet-routing-compare.cc File Reference
vanet-routing-compare.cc File Reference
#include <fstream>
#include <iostream>
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/mobility-module.h"
#include "ns3/aodv-module.h"
#include "ns3/olsr-module.h"
#include "ns3/dsdv-module.h"
#include "ns3/dsr-module.h"
#include "ns3/applications-module.h"
#include "ns3/itu-r-1411-los-propagation-loss-model.h"
#include "ns3/ocb-wifi-mac.h"
#include "ns3/wifi-80211p-helper.h"
#include "ns3/wave-mac-helper.h"
#include "ns3/flow-monitor-module.h"
#include "ns3/config-store-module.h"
#include "ns3/integer.h"
#include "ns3/wave-bsm-helper.h"
#include "ns3/wave-helper.h"
#include "ns3/yans-wifi-helper.h"
Classes
class ConfigStoreHelper
The ConfigStoreHelper class simplifies config-store raw text load and save.
class RoutingHelper
The RoutingHelper class generates routing data between nodes (vehicles) and uses the RoutingStats class to collect statistics on routing data (application-data packet and byte counts).
class RoutingStats
The RoutingStats class manages collects statistics on routing data (application-data packet and byte counts) for the vehicular network.
class VanetRoutingExperiment
The VanetRoutingExperiment class implements a wifi app that allows VANET routing experiments to be simulated.
class WifiApp
The WifiApp class enforces program flow for ns-3 wifi applications.
class WifiPhyStats
The WifiPhyStats class collects Wifi MAC/PHY statistics.
Functions
static std::string PrintReceivedRoutingPacket (Ptr< Socket > socket, Ptr< Packet > packet, Address srcAddress)
Variables
static ns3::GlobalValue g_80211mode ("VRC80211mode", "802.11 mode (0=802.11a;1=802.11p)", ns3::UintegerValue(1), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_asciiTrace ("VRCasciiTrace", "Dump ASCII trace 0=no;1=yes", ns3::UintegerValue(0), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_CSVfileName ("VRCCSVfileName", "CSV filename (for time series data)", ns3::StringValue("vanet-routing.output.csv"), ns3::MakeStringChecker())
static ns3::GlobalValue g_CSVfileName2 ("VRCCSVfileName2", "CSV filename 2 (for overall simulation scenario results)", ns3::StringValue("vanet-routing.output2.csv"), ns3::MakeStringChecker())
static ns3::GlobalValue g_cumulativeBsmCaptureStart ("VRCcumulativeBsmCaptureStart", "Simulation starte time for capturing cumulative BSM", ns3::UintegerValue(0), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_fading ("VRCfading", "Fast Fading Model", ns3::UintegerValue(0), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_gpsAccuracyNs ("VRCgpsAccuracyNs", "GPS sync accuracy (ns)", ns3::DoubleValue(40), ns3::MakeDoubleChecker< double >())
static ns3::GlobalValue g_logFile ("VRClogFile", "Log filename", ns3::StringValue("low99-ct-unterstrass-1day.filt.7.adj.log"), ns3::MakeStringChecker())
static ns3::GlobalValue g_lossModel ("VRClossModel", "Propagation Loss Model", ns3::UintegerValue(3), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_mobility ("VRCmobility", "Mobility mode 0=random waypoint;1=mobility trace file", ns3::UintegerValue(1), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_nNodes ("VRCnNodes", "Number of nodes (vehicles)", ns3::UintegerValue(156), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_nodePause ("VRCnodePause", "Node pause time (s) for RWP model", ns3::UintegerValue(0), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_nodeSpeed ("VRCnodeSpeed", "Node speed (m/s) for RWP model", ns3::UintegerValue(20), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_nSinks ("VRCnSinks", "Number of sink nodes for routing non-BSM traffic", ns3::UintegerValue(10), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_pcap ("VRCpcap", "Generate PCAP files 0=no;1=yes", ns3::UintegerValue(0), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_phyMode ("VRCphyMode", "PHY mode (802.11p)", ns3::StringValue("OfdmRate6MbpsBW10MHz"), ns3::MakeStringChecker())
static ns3::GlobalValue g_phyModeB ("VRCphyModeB", "PHY mode (802.11a)", ns3::StringValue("DsssRate11Mbps"), ns3::MakeStringChecker())
static ns3::GlobalValue g_port ("VRCport", "Port", ns3::UintegerValue(9), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_protocol ("VRCprotocol", "Routing protocol", ns3::UintegerValue(2), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_rate ("VRCrate", "Data rate", ns3::StringValue("2048bps"), ns3::MakeStringChecker())
static ns3::GlobalValue g_routingTables ("VRCroutingTables", "Dump routing tables at t=5 seconds 0=no;1=yes", ns3::UintegerValue(0), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_scenario ("VRCscenario", "Scenario", ns3::UintegerValue(1), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_totalTime ("VRCtotalTime", "Total simulation time (s)", ns3::DoubleValue(300.01), ns3::MakeDoubleChecker< double >())
static ns3::GlobalValue g_traceFile ("VRCtraceFile", "Mobility trace filename", ns3::StringValue("./src/wave/examples/low99-ct-unterstrass-1day.filt.7.adj.mob"), ns3::MakeStringChecker())
static ns3::GlobalValue g_traceMobility ("VRCtraceMobility", "Trace mobility 1=yes;0=no", ns3::UintegerValue(0), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_trName ("VRCtrName", "Trace name", ns3::StringValue("vanet-routing-compare"), ns3::MakeStringChecker())
static ns3::GlobalValue g_txMaxDelayMs ("VRCtxMaxDelayMs", "Tx May Delay (ms)", ns3::DoubleValue(10), ns3::MakeDoubleChecker< double >())
static ns3::GlobalValue g_txp ("VRCtxp", "Transmission power dBm", ns3::DoubleValue(7.5), ns3::MakeDoubleChecker< double >())
static ns3::GlobalValue g_txSafetyRange1 ("VRCtxSafetyRange1", "BSM range for PDR inclusion", ns3::DoubleValue(50.0), ns3::MakeDoubleChecker< double >())
static ns3::GlobalValue g_txSafetyRange10 ("VRCtxSafetyRange10", "BSM range for PDR inclusion", ns3::DoubleValue(500.0), ns3::MakeDoubleChecker< double >())
static ns3::GlobalValue g_txSafetyRange2 ("VRCtxSafetyRange2", "BSM range for PDR inclusion", ns3::DoubleValue(100.0), ns3::MakeDoubleChecker< double >())
static ns3::GlobalValue g_txSafetyRange3 ("VRCtxSafetyRange3", "BSM range for PDR inclusion", ns3::DoubleValue(150.0), ns3::MakeDoubleChecker< double >())
static ns3::GlobalValue g_txSafetyRange4 ("VRCtxSafetyRange4", "BSM range for PDR inclusion", ns3::DoubleValue(200.0), ns3::MakeDoubleChecker< double >())
static ns3::GlobalValue g_txSafetyRange5 ("VRCtxSafetyRange5", "BSM range for PDR inclusion", ns3::DoubleValue(250.0), ns3::MakeDoubleChecker< double >())
static ns3::GlobalValue g_txSafetyRange6 ("VRCtxSafetyRange6", "BSM range for PDR inclusion", ns3::DoubleValue(300.0), ns3::MakeDoubleChecker< double >())
static ns3::GlobalValue g_txSafetyRange7 ("VRCtxSafetyRange7", "BSM range for PDR inclusion", ns3::DoubleValue(350.0), ns3::MakeDoubleChecker< double >())
static ns3::GlobalValue g_txSafetyRange8 ("VRCtxSafetyRange8", "BSM range for PDR inclusion", ns3::DoubleValue(400.0), ns3::MakeDoubleChecker< double >())
static ns3::GlobalValue g_txSafetyRange9 ("VRCtxSafetyRange9", "BSM range for PDR inclusion", ns3::DoubleValue(450.0), ns3::MakeDoubleChecker< double >())
static ns3::GlobalValue g_verbose ("VRCverbose", "Verbose 0=no;1=yes", ns3::UintegerValue(0), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_waveInterval ("VRCwaveInterval", "Interval (s) between WAVE BSMs", ns3::DoubleValue(0.1), ns3::MakeDoubleChecker< double >())
static ns3::GlobalValue g_wavePacketSize ("VRCwavePacketSize", "Size in bytes of WAVE BSM", ns3::UintegerValue(200), ns3::MakeUintegerChecker< uint32_t >())
Function Documentation
PrintReceivedRoutingPacket()
static std::string PrintReceivedRoutingPacket (Ptr< Socket > socket, Ptr< Packet > packet, Address srcAddress) inline static
Definition at line 663 of file vanet-routing-compare.cc.
References ns3::Time::As(), ns3::Node::GetId(), ns3::InetSocketAddress::GetIpv4(), ns3::Socket::GetNode(), and ns3::Now().
Referenced by RoutingHelper::ReceiveRoutingPacket().
Variable Documentation
g_80211mode
ns3::GlobalValue g_80211mode("VRC80211mode", "802.11 mode (0=802.11a;1=802.11p)", ns3::UintegerValue(1), ns3::MakeUintegerChecker< uint32_t >()) ("VRC80211mode" , "802.11 mode (0=802.11a;1=802.11p)" , ns3::UintegerValue(1) , ns3::MakeUintegerChecker< uint32_t > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_asciiTrace
ns3::GlobalValue g_asciiTrace("VRCasciiTrace", "Dump ASCII trace 0=no;1=yes", ns3::UintegerValue(0), ns3::MakeUintegerChecker< uint32_t >()) ("VRCasciiTrace") static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_CSVfileName
ns3::GlobalValue g_CSVfileName("VRCCSVfileName", "CSV filename (for time series data)", ns3::StringValue("vanet-routing.output.csv"), ns3::MakeStringChecker()) ("VRCCSVfileName" , "CSV filename (for time series data)" , ns3::StringValue("vanet-routing.output.csv") , ns3::MakeStringChecker()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_CSVfileName2
ns3::GlobalValue g_CSVfileName2("VRCCSVfileName2", "CSV filename 2 (for overall simulation scenario results)", ns3::StringValue("vanet-routing.output2.csv"), ns3::MakeStringChecker()) ("VRCCSVfileName2" , "CSV filename 2 (for overall simulation scenario results)" , ns3::StringValue("vanet-routing.output2.csv") , ns3::MakeStringChecker()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_cumulativeBsmCaptureStart
ns3::GlobalValue g_cumulativeBsmCaptureStart("VRCcumulativeBsmCaptureStart", "Simulation starte time for capturing cumulative BSM", ns3::UintegerValue(0), ns3::MakeUintegerChecker< uint32_t >()) ("VRCcumulativeBsmCaptureStart" , "Simulation starte time for capturing cumulative BSM" , ns3::UintegerValue(0) , ns3::MakeUintegerChecker< uint32_t > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_fading
ns3::GlobalValue g_fading("VRCfading", "Fast Fading Model", ns3::UintegerValue(0), ns3::MakeUintegerChecker< uint32_t >()) ("VRCfading" , "Fast Fading Model" , ns3::UintegerValue(0) , ns3::MakeUintegerChecker< uint32_t > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_gpsAccuracyNs
ns3::GlobalValue g_gpsAccuracyNs("VRCgpsAccuracyNs", "GPS sync accuracy (ns)", ns3::DoubleValue(40), ns3::MakeDoubleChecker< double >()) ("VRCgpsAccuracyNs" , "GPS sync accuracy (ns)" , ns3::DoubleValue(40) , ns3::MakeDoubleChecker< double > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_logFile
ns3::GlobalValue g_logFile("VRClogFile", "Log filename", ns3::StringValue("low99-ct-unterstrass-1day.filt.7.adj.log"), ns3::MakeStringChecker()) ("VRClogFile" , "Log filename" , ns3::StringValue("low99-ct-unterstrass-1day.filt.7.adj.log") , ns3::MakeStringChecker()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_lossModel
ns3::GlobalValue g_lossModel("VRClossModel", "Propagation Loss Model", ns3::UintegerValue(3), ns3::MakeUintegerChecker< uint32_t >()) ("VRClossModel" , "Propagation Loss Model" , ns3::UintegerValue(3) , ns3::MakeUintegerChecker< uint32_t > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_mobility
ns3::GlobalValue g_mobility("VRCmobility", "Mobility mode 0=random waypoint;1=mobility trace file", ns3::UintegerValue(1), ns3::MakeUintegerChecker< uint32_t >()) ("VRCmobility") static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_nNodes
ns3::GlobalValue g_nNodes("VRCnNodes", "Number of nodes (vehicles)", ns3::UintegerValue(156), ns3::MakeUintegerChecker< uint32_t >()) ("VRCnNodes" , "Number of nodes (vehicles)" , ns3::UintegerValue(156) , ns3::MakeUintegerChecker< uint32_t > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_nodePause
ns3::GlobalValue g_nodePause("VRCnodePause", "Node pause time (s) for RWP model", ns3::UintegerValue(0), ns3::MakeUintegerChecker< uint32_t >()) ("VRCnodePause" , "Node pause time (s) for RWP model" , ns3::UintegerValue(0) , ns3::MakeUintegerChecker< uint32_t > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_nodeSpeed
ns3::GlobalValue g_nodeSpeed("VRCnodeSpeed", "Node speed (m/s) for RWP model", ns3::UintegerValue(20), ns3::MakeUintegerChecker< uint32_t >()) ("VRCnodeSpeed" , "Node speed (m/s) for RWP model" , ns3::UintegerValue(20) , ns3::MakeUintegerChecker< uint32_t > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_nSinks
ns3::GlobalValue g_nSinks("VRCnSinks", "Number of sink nodes for routing non-BSM traffic", ns3::UintegerValue(10), ns3::MakeUintegerChecker< uint32_t >()) ("VRCnSinks" , "Number of sink nodes for routing non-BSM traffic" , ns3::UintegerValue(10) , ns3::MakeUintegerChecker< uint32_t > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_pcap
ns3::GlobalValue g_pcap("VRCpcap", "Generate PCAP files 0=no;1=yes", ns3::UintegerValue(0), ns3::MakeUintegerChecker< uint32_t >()) ("VRCpcap") static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_phyMode
ns3::GlobalValue g_phyMode("VRCphyMode", "PHY mode (802.11p)", ns3::StringValue("OfdmRate6MbpsBW10MHz"), ns3::MakeStringChecker()) ("VRCphyMode" , "PHY mode (802.11p)" , ns3::StringValue("OfdmRate6MbpsBW10MHz") , ns3::MakeStringChecker()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_phyModeB
ns3::GlobalValue g_phyModeB("VRCphyModeB", "PHY mode (802.11a)", ns3::StringValue("DsssRate11Mbps"), ns3::MakeStringChecker()) ("VRCphyModeB" , "PHY mode (802.11a)" , ns3::StringValue("DsssRate11Mbps") , ns3::MakeStringChecker()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_port
ns3::GlobalValue g_port("VRCport", "Port", ns3::UintegerValue(9), ns3::MakeUintegerChecker< uint32_t >()) ("VRCport" , "Port" , ns3::UintegerValue(9) , ns3::MakeUintegerChecker< uint32_t > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_protocol
ns3::GlobalValue g_protocol("VRCprotocol", "Routing protocol", ns3::UintegerValue(2), ns3::MakeUintegerChecker< uint32_t >()) ("VRCprotocol" , "Routing protocol" , ns3::UintegerValue(2) , ns3::MakeUintegerChecker< uint32_t > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_rate
ns3::GlobalValue g_rate("VRCrate", "Data rate", ns3::StringValue("2048bps"), ns3::MakeStringChecker()) ("VRCrate" , "Data rate" , ns3::StringValue("2048bps") , ns3::MakeStringChecker()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_routingTables
ns3::GlobalValue g_routingTables("VRCroutingTables", "Dump routing tables at t=5 seconds 0=no;1=yes", ns3::UintegerValue(0), ns3::MakeUintegerChecker< uint32_t >()) ("VRCroutingTables") static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_scenario
ns3::GlobalValue g_scenario("VRCscenario", "Scenario", ns3::UintegerValue(1), ns3::MakeUintegerChecker< uint32_t >()) ("VRCscenario" , "Scenario" , ns3::UintegerValue(1) , ns3::MakeUintegerChecker< uint32_t > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_totalTime
ns3::GlobalValue g_totalTime("VRCtotalTime", "Total simulation time (s)", ns3::DoubleValue(300.01), ns3::MakeDoubleChecker< double >()) ("VRCtotalTime" , "Total simulation time (s)" , ns3::DoubleValue(300.01) , ns3::MakeDoubleChecker< double > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_traceFile
ns3::GlobalValue g_traceFile("VRCtraceFile", "Mobility trace filename", ns3::StringValue("./src/wave/examples/low99-ct-unterstrass-1day.filt.7.adj.mob"), ns3::MakeStringChecker()) ("VRCtraceFile" , "Mobility trace filename" , ns3::StringValue("./src/wave/examples/low99-ct-unterstrass-1day.filt.7.adj.mob") , ns3::MakeStringChecker()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_traceMobility
ns3::GlobalValue g_traceMobility("VRCtraceMobility", "Trace mobility 1=yes;0=no", ns3::UintegerValue(0), ns3::MakeUintegerChecker< uint32_t >()) ("VRCtraceMobility") static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_trName
ns3::GlobalValue g_trName("VRCtrName", "Trace name", ns3::StringValue("vanet-routing-compare"), ns3::MakeStringChecker()) ("VRCtrName" , "Trace name" , ns3::StringValue("vanet-routing-compare") , ns3::MakeStringChecker()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_txMaxDelayMs
ns3::GlobalValue g_txMaxDelayMs("VRCtxMaxDelayMs", "Tx May Delay (ms)", ns3::DoubleValue(10), ns3::MakeDoubleChecker< double >()) ("VRCtxMaxDelayMs" , "Tx May Delay (ms)" , ns3::DoubleValue(10) , ns3::MakeDoubleChecker< double > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_txp
ns3::GlobalValue g_txp("VRCtxp", "Transmission power dBm", ns3::DoubleValue(7.5), ns3::MakeDoubleChecker< double >()) ("VRCtxp" , "Transmission power dBm" , ns3::DoubleValue(7.5) , ns3::MakeDoubleChecker< double > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_txSafetyRange1
ns3::GlobalValue g_txSafetyRange1("VRCtxSafetyRange1", "BSM range for PDR inclusion", ns3::DoubleValue(50.0), ns3::MakeDoubleChecker< double >()) ("VRCtxSafetyRange1" , "BSM range for PDR inclusion" , ns3::DoubleValue(50.0) , ns3::MakeDoubleChecker< double > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_txSafetyRange10
ns3::GlobalValue g_txSafetyRange10("VRCtxSafetyRange10", "BSM range for PDR inclusion", ns3::DoubleValue(500.0), ns3::MakeDoubleChecker< double >()) ("VRCtxSafetyRange10" , "BSM range for PDR inclusion" , ns3::DoubleValue(500.0) , ns3::MakeDoubleChecker< double > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_txSafetyRange2
ns3::GlobalValue g_txSafetyRange2("VRCtxSafetyRange2", "BSM range for PDR inclusion", ns3::DoubleValue(100.0), ns3::MakeDoubleChecker< double >()) ("VRCtxSafetyRange2" , "BSM range for PDR inclusion" , ns3::DoubleValue(100.0) , ns3::MakeDoubleChecker< double > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_txSafetyRange3
ns3::GlobalValue g_txSafetyRange3("VRCtxSafetyRange3", "BSM range for PDR inclusion", ns3::DoubleValue(150.0), ns3::MakeDoubleChecker< double >()) ("VRCtxSafetyRange3" , "BSM range for PDR inclusion" , ns3::DoubleValue(150.0) , ns3::MakeDoubleChecker< double > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_txSafetyRange4
ns3::GlobalValue g_txSafetyRange4("VRCtxSafetyRange4", "BSM range for PDR inclusion", ns3::DoubleValue(200.0), ns3::MakeDoubleChecker< double >()) ("VRCtxSafetyRange4" , "BSM range for PDR inclusion" , ns3::DoubleValue(200.0) , ns3::MakeDoubleChecker< double > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_txSafetyRange5
ns3::GlobalValue g_txSafetyRange5("VRCtxSafetyRange5", "BSM range for PDR inclusion", ns3::DoubleValue(250.0), ns3::MakeDoubleChecker< double >()) ("VRCtxSafetyRange5" , "BSM range for PDR inclusion" , ns3::DoubleValue(250.0) , ns3::MakeDoubleChecker< double > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_txSafetyRange6
ns3::GlobalValue g_txSafetyRange6("VRCtxSafetyRange6", "BSM range for PDR inclusion", ns3::DoubleValue(300.0), ns3::MakeDoubleChecker< double >()) ("VRCtxSafetyRange6" , "BSM range for PDR inclusion" , ns3::DoubleValue(300.0) , ns3::MakeDoubleChecker< double > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_txSafetyRange7
ns3::GlobalValue g_txSafetyRange7("VRCtxSafetyRange7", "BSM range for PDR inclusion", ns3::DoubleValue(350.0), ns3::MakeDoubleChecker< double >()) ("VRCtxSafetyRange7" , "BSM range for PDR inclusion" , ns3::DoubleValue(350.0) , ns3::MakeDoubleChecker< double > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_txSafetyRange8
ns3::GlobalValue g_txSafetyRange8("VRCtxSafetyRange8", "BSM range for PDR inclusion", ns3::DoubleValue(400.0), ns3::MakeDoubleChecker< double >()) ("VRCtxSafetyRange8" , "BSM range for PDR inclusion" , ns3::DoubleValue(400.0) , ns3::MakeDoubleChecker< double > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_txSafetyRange9
ns3::GlobalValue g_txSafetyRange9("VRCtxSafetyRange9", "BSM range for PDR inclusion", ns3::DoubleValue(450.0), ns3::MakeDoubleChecker< double >()) ("VRCtxSafetyRange9" , "BSM range for PDR inclusion" , ns3::DoubleValue(450.0) , ns3::MakeDoubleChecker< double > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_verbose
ns3::GlobalValue g_verbose("VRCverbose", "Verbose 0=no;1=yes", ns3::UintegerValue(0), ns3::MakeUintegerChecker< uint32_t >()) ("VRCverbose") static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_waveInterval
ns3::GlobalValue g_waveInterval("VRCwaveInterval", "Interval (s) between WAVE BSMs", ns3::DoubleValue(0.1), ns3::MakeDoubleChecker< double >()) ("VRCwaveInterval" , "Interval (s) between WAVE BSMs" , ns3::DoubleValue(0.1) , ns3::MakeDoubleChecker< double > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().
g_wavePacketSize
ns3::GlobalValue g_wavePacketSize("VRCwavePacketSize", "Size in bytes of WAVE BSM", ns3::UintegerValue(200), ns3::MakeUintegerChecker< uint32_t >()) ("VRCwavePacketSize" , "Size in bytes of WAVE BSM" , ns3::UintegerValue(200) , ns3::MakeUintegerChecker< uint32_t > ()) static
Referenced by VanetRoutingExperiment::SetGlobalsFromConfig().