ns-3: src/wifi/test/wifi-test.cc File Reference
wifi-test.cc File Reference
#include "ns3/string.h"
#include "ns3/yans-wifi-helper.h"
#include "ns3/mobility-helper.h"
#include "ns3/wifi-net-device.h"
#include "ns3/adhoc-wifi-mac.h"
#include "ns3/ap-wifi-mac.h"
#include "ns3/propagation-loss-model.h"
#include "ns3/yans-error-rate-model.h"
#include "ns3/constant-position-mobility-model.h"
#include "ns3/test.h"
#include "ns3/pointer.h"
#include "ns3/rng-seed-manager.h"
#include "ns3/config.h"
#include "ns3/error-model.h"
#include "ns3/socket.h"
#include "ns3/packet-socket-server.h"
#include "ns3/packet-socket-client.h"
#include "ns3/packet-socket-helper.h"
#include "ns3/spectrum-wifi-helper.h"
#include "ns3/multi-model-spectrum-channel.h"
#include "ns3/wifi-spectrum-signal-parameters.h"
#include "ns3/yans-wifi-phy.h"
#include "ns3/mgt-headers.h"
#include "ns3/ht-configuration.h"
#include "ns3/wifi-ppdu.h"
#include "ns3/wifi-psdu.h"
#include "ns3/waypoint-mobility-model.h"
Classes
class Bug2222TestCase
Make sure that when virtual collision occurs the wifi remote station manager is triggered and the retry counter is increased.
class Bug2470TestCase
Make sure that the ADDBA handshake process is protected.
class Bug2831TestCase
Make sure that the channel width and the channel number can be changed at runtime.
class Bug2843TestCase
Make sure that the correct channel width and center frequency have been set for OFDM basic rate transmissions and BSS channel widths larger than 20 MHz.
class Bug730TestCase
Make sure that when changing the fragmentation threshold during the simulation, the TCP transmission does not unexpectedly stop.
class DcfImmediateAccessBroadcastTestCase
Make sure that when multiple broadcast packets are queued on the same device in a short succession, that: 1) no backoff occurs if the frame arrives and the idle time >= DIFS or AIFSn (this is 'DCF immediate access', Figure 9-3 of IEEE 802.11-2012) 2) a backoff occurs for the second frame that arrives (this is clearly stated in Sec.
class HeRuMcsDataRateTestCase
Data rate verification test for MCSs of different RU sizes.
class IdealRateManagerChannelWidthTest
Make sure that Ideal rate manager properly selects MCS based on the configured channel width.
class IdealRateManagerMimoTest
Test to validate that Ideal rate manager properly selects TXVECTOR in scenarios where MIMO is used.
class InterferenceHelperSequenceTest
See Bug 991
class Issue169TestCase
Make sure that Ideal rate manager is able to handle non best-effort traffic.
class Issue40TestCase
Make sure that Ideal rate manager recovers when the station is moving away from the access point.
class QosFragmentationTestCase
Make sure that fragmentation works with QoS stations.
class QosUtilsIsOldPacketTest
Qos Utils Is Old Packet Test.
class SetChannelFrequencyTest
Set Channel Frequency Test.
class StaWifiMacScanningTestCase
Make sure that Wifi STA is correctly associating to the best AP (i.e., nearest from STA).
class WifiTest
Wifi Test.
class WifiTestSuite
Wifi Test Suite.
Functions
static void AssignWifiRandomStreams (Ptr< WifiMac > mac, int64_t stream)
Variables
static WifiTestSuite g_wifiTestSuite
the test suite
Function Documentation
AssignWifiRandomStreams()
static void AssignWifiRandomStreams (Ptr< WifiMac > mac, int64_t stream) static
Definition at line 57 of file wifi-test.cc.
References ns3::Txop::AssignStreams(), ns3::PointerValue::Get(), and third::mac.
Referenced by DcfImmediateAccessBroadcastTestCase::DoRun().
Variable Documentation
g_wifiTestSuite
WifiTestSuite g_wifiTestSuite static
the test suite
Definition at line 3087 of file wifi-test.cc.